### PR TITLE
wip: try mold linker

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7mLu756MRovCLqI5b:-NQ7mLu756MRovCLqI5c:bfdpjk6) (no related file):*
Results expected: jammy provisioned builds fail, everything else should pass. focal and mac should not be affected at all.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7mLu756MRovCLqI5b:-NQB4y-R45qjQhLd-I_E:bnxm974) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Results expected: jammy provisioned builds fail, everything else should pass. focal and mac should not be affected at all.
</blockquote></details>

So, in fact, the build of interest also failed a bunch of install tests, with this lovely note:

```
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
```

Fascinating.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7mLu756MRovCLqI5b:-NQB7tKF3weoMhaJ0JUt:blfomm6) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, in fact, the build of interest also failed a bunch of install tests, with this lovely note:

```
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
```

Fascinating.
</blockquote></details>

I'm not yet entirely sure that message represents the heart of the problem; quick internet research turns up a bunch of "oh i rebooted and it went away" type nonsense. I'll try a local repro.

___

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7mLu756MRovCLqI5b:-NQ_iewQ4YhAsOvlU9OP:b8en8gy) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Not reproduced locally after 1 attempt.
</blockquote></details>

Alas I also cannot reproduce this locally.
My best guess is that there is some piece of ld-specific information that's getting cached in kernelspace, such that the ld->mold switch has an undocumented reboot requirement?

___

**Comment by jwnimmer-tri** [comment]
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Part of the trouble also is that our CI is misreporting this result -- it's marking linux-jammy-unprovisioned-clang-bazel-experimental-debug as failed even though its last run succeeded, and the failure it's reporting isn't even a recent build.
</blockquote></details>

It looks like maybe you used the web UI to launch https://drake-jenkins.csail.mit.edu/job/linux-jammy-unprovisioned-clang-bazel-experimental-debug/8/ ?

That doesn't associate the build result with the PR.  If you want PR status updates, you need to use the 'bot command.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please.
</blockquote></details>

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NREsnXd8tmzwPJ3sJmx:-NREsnXd8tmzwPJ3sJmy:bjntvc2) (no related file):*
BTW To get out in front of one concern ...

I am loathe to switch our _default_ linker we expose to users and build our packages with to be something different that the Ubuntu default.

Switching it globally for CI canary testing is no problem of course, but for actually landing this my push will be to have it associated with off-nominal build options like `--config=asan` or `--config=kcov` or whatever, not the vanilla build.

___

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please.
</blockquote></details>

@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NRj3KUIA0qTgxMp6WXP:b-yrkjvm) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please.
</blockquote></details>

So far, the //:py/install_test problem appears to be isolated to clang+mold...

___

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So far, the //:py/install_test problem appears to be isolated to clang+mold...
</blockquote></details>

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NSN2fTk9waHcOLhNdQ9:b-jh1lc9) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please.

</blockquote></details>

Failure reproduced on local puget. Running a hand-built latest version of `mold` helps a little, but doesn't fix everything:

mold 1.0.3 (Jammy apt package): fails //:py/install_test,  both clang release and debug
mold 1.11.0 (hand-built): fails //:py/install_test, clang debug only

Given these data points, I will say that mold is not quite cooked yet. It may be good enough for off-nominal builds that don't need to load pydrake .so's, but that is about it. It might be good enough for projects that don't export .so's for public consumption.

___

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @drake-jenkins-bot and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NSfZC2ZAase5AVLCRzo:b-pgrnyc) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Failure reproduced on local puget. Running a hand-built latest version of `mold` helps a little, but doesn't fix everything:

mold 1.0.3 (Jammy apt package): fails //:py/install_test,  both clang release and debug
mold 1.11.0 (hand-built): fails //:py/install_test, clang debug only

Given these data points, I will say that mold is not quite cooked yet. It may be good enough for off-nominal builds that don't need to load pydrake .so's, but that is about it. It might be good enough for projects that don't export .so's for public consumption.
</blockquote></details>

Alas I must agree.  If there's trouble around sos, that will be a deep rabbit hole to debug even if it is confined to specific and special cases.

Is this something we can practically contribute upstream?

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @drake-jenkins-bot, @ggould-tri, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NSfhNFz7CXzGoxNBZ2I:b-yugktl) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Alas I must agree.  If there's trouble around sos, that will be a deep rabbit hole to debug even if it is confined to specific and special cases.

Is this something we can practically contribute upstream?
</blockquote></details>

We could file an issue upstream. Producing a decent patch might well be a lot of work. And after that, we would likely have to vendor `mold` to get access to the fix. But, if we are saving significant CI money, it could be worthwhile.

OTOH, it could be that the mold developers determine that clang is the offending party...

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NSfz-uDBiycRDCRAZib:b-f4yscn) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I think the issue would be of value, even if a patch would be excessive work.  Good repro cases of linker misbehavior are rare and I assume they would appreciate knowing about ti.
</blockquote></details>

I will file an upstream issue.

___

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NSrKZRoDbkbVhRMOdpv:b-eoipg5) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Welp, sonofagun. In trying to repro the failures again locally, I am unable to. It will maybe take some time to work out why (do drake source versions matter? :scream: ). 
</blockquote></details>

Nevermind. Improved my repro techniques and now I never miss :speak_no_evil: 

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18970)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18970#-NQ7gMdbEy7cQRKZZl6M:-NT-kY697J4pB8RWCRmb:b-s7fg89) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Nevermind. Improved my repro techniques and now I never miss :speak_no_evil: 
</blockquote></details>

Alas. There was a `mold` bug, apparently fixed between v1.1 and v1.2.0 (by my bisect of `mold`). The `apt` packaged version for Jammy is v1.0.3.  Future in-process Ubuntu releases have new-enough versions (kinetic has v1.4.2 so far).

The symptom is that .so files written by older `mold` can end up with R_X86_64_PLT32 relocations, which jammy's `ld.so` Does. Not. Want. 

I haven't pushed the `mold` bisect far enough to find a fixing patch or corresponding issue number; I don't know that it matters.

So, absent some other efforts to get a current version of `mold`, I think this is where we give up and wait two years.

___

**Pull request closed without merging**
