### PR TITLE
Add Homebrew opt prefix paths to PKG_CONFIG_PATH

### PR DESCRIPTION
**Pull request by jamiesnape**
This is necessary for creating a Drake Homebrew formula. <s>I still have issues finding `dreal`, but</s> this is a step in the direction of #1183.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7969)

### CODE REVIEW

**Comment by soonho-tri** [comment]
>  I still have issues finding dreal

FWIW, `ibex@2.6.5` is out and I'm updating dReal to use it. Please let me know if there is something else I can help.

**Comment by jamiesnape** [comment]
> FWIW, ibex@2.6.5 is out and I'm updating dReal to use it. Please let me know if there is something else I can help.

Will do. At the moment it is puzzling.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
:lgtm: 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7969#-:-L4hV_8oz19GAA04_AIl:bg7igkv)*

**Comment by soonho-tri** [comment]
+@ggould-tri for platform-review, please (per rotation).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7969#-:-L4hnYxNeYXOAx6UNtMl:b3fy9x9)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7969#-:-L4kZ1cP1yB1wNqpn6_W:bnfp4nl)*

**Pull request merged**
