### PR TITLE
preparing for val_sim_pr

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
separating #4152, this pr has the non examples/Valkyrie parts. 
@david-german-tri for platform review. thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4159)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/kinematics_results.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsfnDwD1HUkmVcApoj:-KWsfnDwD1HUkmVcApok:b-y2sfkw) ([raw file](https://github.com/robotlocomotion/drake/blob/a4673b7c413125ea151b24605b6f09fdbba3b3eb/drake/multibody/rigid_body_plant/kinematics_results.cc#L75)):*
> ```cpp
>   auto twist_in_world = get_twist_in_world_frame(body);
>   auto body_to_world = get_pose_in_world(body);
>   Eigen::Isometry3d world_to_world_aligned_body(
> ```

Why isn't this templated on T?

---

*[drake/multibody/rigid_body_plant/kinematics_results.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsfzj56ucE3QjITtlb:-KWsfzj56ucE3QjITtlc:b-9p9n4r) ([raw file](https://github.com/robotlocomotion/drake/blob/a4673b7c413125ea151b24605b6f09fdbba3b3eb/drake/multibody/rigid_body_plant/kinematics_results.h#L23)):*
> ```objc
>   /// An alias to @param tree is maintained so that the tree's lifetime must
>   /// exceed this object's lifetime.
>   explicit KinematicsResults(const RigidBodyTree<T>* tree);
> ```

Making this constructor public seems like a big change.  I guess @amcastro-tri is OK with it, given his previous LGTM, but could you explain why it's OK?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by david-german-tri** [comment]
Also, please use a PR and commit message that actually explains the motivation.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-:-KWsh1LiwVeB0K2FpCuL:b-sk4jhi)*

**Comment by siyuanfeng-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/kinematics_results.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsfnDwD1HUkmVcApoj:-KWsiwP6OwmBbt5v7L0W:b-uvnevx) ([raw file](https://github.com/robotlocomotion/drake/blob/a4673b7c413125ea151b24605b6f09fdbba3b3eb/drake/multibody/rigid_body_plant/kinematics_results.cc#L75)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why isn't this templated on T?
</details>
Done. good catch. 

---

*[drake/multibody/rigid_body_plant/kinematics_results.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsfzj56ucE3QjITtlb:-KWsj2Jmv30DHD6lr111:bzuvdy) ([raw file](https://github.com/robotlocomotion/drake/blob/a4673b7c413125ea151b24605b6f09fdbba3b3eb/drake/multibody/rigid_body_plant/kinematics_results.h#L23)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Making this constructor public seems like a big change.  I guess @amcastro-tri is OK with it, given his previous LGTM, but could you explain why it's OK?
</details>
I believe @amcastro-tri's initial intention is for this to be a intermediate class that only rigid body plant outputs. But there is a more common use case for it hold additional information to kinematics cache. In this case, kinematics result will be an output of a lcm message parser. So there is need to make it public. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by david-german-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/kinematics_results.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsljvwVkuAPp3GkdQ6:-KWsljvwVkuAPp3GkdQ7:bi5rvc) ([raw file](https://github.com/robotlocomotion/drake/blob/aff65f9c5a269ba4a58feef4a4f369a9a2027686/drake/multibody/rigid_body_plant/kinematics_results.h#L18)):*
> ```objc
> /// @tparam T The scalar type. Must be a valid Eigen scalar.
> template <typename T>
> class KinematicsResults {
> ```

All of the new methods here need unit test coverage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/kinematics_results.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsljvwVkuAPp3GkdQ6:-KWsm2-AkCGzXe5F-9sw:b7p97f8) ([raw file](https://github.com/robotlocomotion/drake/blob/aff65f9c5a269ba4a58feef4a4f369a9a2027686/drake/multibody/rigid_body_plant/kinematics_results.h#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> All of the new methods here need unit test coverage.
</details>
These are all simple getter wrappers on existing rbt / kinematics cache / transformation functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/kinematics_results.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsljvwVkuAPp3GkdQ6:-KWss6TDJpHoNsvu0iA8:b27qcht) ([raw file](https://github.com/robotlocomotion/drake/blob/aff65f9c5a269ba4a58feef4a4f369a9a2027686/drake/multibody/rigid_body_plant/kinematics_results.h#L18)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> These are all simple getter wrappers on existing rbt / kinematics cache / transformation functions.
</details>
Nonetheless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by siyuanfeng-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/kinematics_results.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWsljvwVkuAPp3GkdQ6:-KWt9buhmZsRUyKoc_y7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aff65f9c5a269ba4a58feef4a4f369a9a2027686/drake/multibody/rigid_body_plant/kinematics_results.h#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Nonetheless.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 18 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWtPkO57RIG8Oyyan8h:-KWtPkO57RIG8Oyyan8i:b4qb5ub) ([raw file](https://github.com/robotlocomotion/drake/blob/2426d6cd6cbe74576189c975bc4b9066f287e5bf/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L18)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(KinematicsResultsTest, Test) {
> ```

Consider splitting this into more focused pieces, possibly using TEST_F.

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWtJW2WuVeNgKdLEw_K:-KWtJW2XKHXUVbhXBpn7:b-271was) ([raw file](https://github.com/robotlocomotion/drake/blob/2426d6cd6cbe74576189c975bc4b9066f287e5bf/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L27)):*
> ```cpp
>   // Set state.
>   std::default_random_engine generator;
>   VectorX<double> q = robot.getRandomConfiguration(generator);
> ```

Can this test be made deterministic?

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWtOv_SKUtBOAbrkrOo:-KWtOv_THizv0VGJ-rmV:b29za2w) ([raw file](https://github.com/robotlocomotion/drake/blob/2426d6cd6cbe74576189c975bc4b9066f287e5bf/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L53)):*
> ```cpp
>   Vector3<double> rpydot = v.segment<3>(3);
>   Matrix3<double> phi = Matrix3<double>::Zero();
>   angularvel2rpydotMatrix(rpy, phi, static_cast<Matrix3<double>*>(nullptr),
> ```

btw I don't think these `static_cast`s are meaningful/necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by siyuanfeng-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 18 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWtPkO57RIG8Oyyan8h:-KWtV_or8HTtSNvYiQjz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2426d6cd6cbe74576189c975bc4b9066f287e5bf/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Consider splitting this into more focused pieces, possibly using TEST_F.
</details>
Done.

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWtJW2WuVeNgKdLEw_K:-KWtVaAgE6lgi36S4G_n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2426d6cd6cbe74576189c975bc4b9066f287e5bf/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Can this test be made deterministic?
</details>
Done.

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-KWtOv_SKUtBOAbrkrOo:-KWtWcru33BMMu8faqTY:b3nb1h2) ([raw file](https://github.com/robotlocomotion/drake/blob/2426d6cd6cbe74576189c975bc4b9066f287e5bf/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L53)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw I don't think these `static_cast`s are meaningful/necessary?
</details>
it was left there to make it compile, otherwise it complains about can't do substitution correctly. 
I copied something else from twan's code, see if that looks prettier. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159)*

**Comment by david-german-tri** [comment]
:lgtm: thanks!

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-:-KWtYl_HkGGXLxvx9dG5:brfqlux)*

**Comment by siyuanfeng-tri** [comment]
thanks to you!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4159#-:-KWtYyos-3xM78iT09fN:bl99pw5)*

**Pull request merged**
