### PR TITLE
add a generic lcm translator class between VectorX and bot_core::robot_state_t message. 

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Extracted the message translator from Valkyrie to manip/util. works for floating base / fixed base robot, also under actuate. see class doc for more detail.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6043)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@hongkai-dai for feature review. 
cc @naveenoid 

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjOb-DsMXpAkjmfDYFn:bf1thqw)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 19 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043)*

**Comment by hongkai-dai** [comment]
Checkpoint

---

Reviewed 2 of 19 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjOuo8d9JCe-qhU6rIH:-KjOuo8d9JCe-qhU6rII:b-tzg1ls) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L43)):*
> ```objc
>    * Constructs a translator using the model given in @p robot. A const
>    * reference of @p robot is saved, and thus its life span must be longer
>    * that this. The following assumptions must be met by @p robot, otherwise
> ```

typo `that`->`than`

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjOv3-c_kTuEn6WY2J6:-KjOv3-dqVa6Uv6uzSsu:bsck90a) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L44)):*
> ```objc
>    * reference of @p robot is saved, and thus its life span must be longer
>    * that this. The following assumptions must be met by @p robot, otherwise
>    * the constructor aborts:
> ```

Instead of aborting, could you throw a runtime error? The error message would be more meaningful to the user.

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjPBhIt7VW6IFtynlxa:-KjPBhIu-CseMT56hk5t:btg2mu8) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L62)):*
> ```objc
> 
>   /**
>    * Decodes only the kinematic values (q, v) from @p msg to @p q and @p v.
> ```

It is probably more readable, to put single quotation mark around `msg`, `q` and `v`, rather than using `@p`. Doxygen renders them the same.

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjPC1NiKOSSlLFGWxGw:-KjPC1NiKOSSlLFGWxGx:b-ud4gj5) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L64)):*
> ```objc
>    * Decodes only the kinematic values (q, v) from @p msg to @p q and @p v.
>    * @p q and @p v are resized to match the rigid body tree's generalized
>    * position and velocity size. Note that the values in @p p and @p q that
> ```

`@ p` -> `@ v`?

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjPCVCeJPlNdA3QLW9X:-KjPCVCeJPlNdA3QLW9Y:b-lfjkkk) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L97)):*
> ```objc
>    * @param[in, out] msg Lcm message to be encoded.
>    */
>   void EncodeMessageKinematics(const VectorX<double>& q,
> ```

Is it better to use `const Eigen::Ref<const VectorX<double>>` rather than `const VectorX<double>` here? So that `q` can be an expression, a block, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjQ0ntLPHk44sniymP4:b13s2ul)*

**Comment by hongkai-dai** [comment]
checkpoint.

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjThLRZzqPGnt9u2abX:-KjThLRZzqPGnt9u2abY:bu0xbpg) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/robot_state_msg_translator.cc#L20)):*
> ```cpp
>                  std::vector<float>* msg_values) {
>   for (size_t i = 0; i < names.size(); ++i) {
>     const std::string& q_name = names[i];
> ```

`q_name` can be unclear, I think this function is used for encoding not only `q`, but `v` and `torque` as well?

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjTjgn3wPPMFlyUVQ5V:-KjTjgn3wPPMFlyUVQ5W:b-r84wb9) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/robot_state_msg_translator.cc#L63)):*
> ```cpp
>         // Assuming for the non floating joints, the sizes for q and v are
>         // both 1.
>         int position_index = body->get_position_start_index();
> ```

Maybe add a sanity check here
```C++
DRAKE_ASSERT(joint.get_num_positions() == 1);
DRAKE_ASSERT(joint.get_num_velocities() == 1);
```

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjU1sti3wOIL-7HkRrT:-KjU1sti3wOIL-7HkRrU:bqvdon9) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/robot_state_msg_translator.cc#L139)):*
> ```cpp
>       world_aligned_body_to_body.translation().setZero();
>       world_aligned_body_to_body.makeAffine();
>       TwistVector<double> floating_base_twist_in_body =
> ```

It would be helpful if you could document that `V_WB` represent both the angular/linear velocity of the body in the world frame, and also the twist of the body in the world-aligned body frame.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjU7Ur-KLILGcywLkRW:b6o68ox)*

**Comment by siyuanfeng-tri** [comment]
Review status: 15 of 19 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjThLRZzqPGnt9u2abX:-KjUM0Jkfs76PTGXmn04:b-dvcf48) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/robot_state_msg_translator.cc#L20)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`q_name` can be unclear, I think this function is used for encoding not only `q`, but `v` and `torque` as well?
</blockquote></details>

how about just name? 

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjTjgn3wPPMFlyUVQ5V:-KjUMUihBu5V8GPglPPv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/robot_state_msg_translator.cc#L63)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe add a sanity check here
```C++
DRAKE_ASSERT(joint.get_num_positions() == 1);
DRAKE_ASSERT(joint.get_num_velocities() == 1);
```

</blockquote></details>

Done.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjU1sti3wOIL-7HkRrT:-KjUNyYEKGMJ41AmtMOr:b4f8aua) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/robot_state_msg_translator.cc#L139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It would be helpful if you could document that `V_WB` represent both the angular/linear velocity of the body in the world frame, and also the twist of the body in the world-aligned body frame.
</blockquote></details>

i redid the entire part, i am trying to avoid all the twist stuff. 

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjOuo8d9JCe-qhU6rIH:-KjUOKt2HdcdbAxFvJVN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L43)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

typo `that`->`than`
</blockquote></details>

Done.

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjPBhIt7VW6IFtynlxa:-KjUOW-3BqX7dqBMj8la:b-3orvbb) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L62)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is probably more readable, to put single quotation mark around `msg`, `q` and `v`, rather than using `@p`. Doxygen renders them the same.
</blockquote></details>

yeah i agree for q v..
there was some discussion a while ago about `` vs @p, i think @p wins at the end but i forgot why. i am going to stick with @p since i think that's more common. 

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjPC1NiKOSSlLFGWxGw:-KjUOpnbQVf7BAqvi1sF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L64)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`@ p` -> `@ v`?
</blockquote></details>

Done.

---

*[drake/manipulation/util/robot_state_msg_translator.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjPCVCeJPlNdA3QLW9X:-KjUOrCPCHv8x_w6ZBsk:b-etnlwc) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L97)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is it better to use `const Eigen::Ref<const VectorX<double>>` rather than `const VectorX<double>` here? So that `q` can be an expression, a block, etc.
</blockquote></details>

good point. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043)*

**Comment by siyuanfeng-tri** [comment]
*[drake/manipulation/util/robot_state_msg_translator.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjOv3-c_kTuEn6WY2J6:-KjUlw9rCdtK9ljeCCTz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36656a35ce6943308c39234093bd4d1a9af6b826/drake/manipulation/util/robot_state_msg_translator.h#L44)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Instead of aborting, could you throw a runtime error? The error message would be more meaningful to the user.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please.

---

Review status: 15 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjVjWZFQmmMJqvpSvEU:b-ioqdtq)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review please.

---

Reviewed 14 of 19 files at r1, 1 of 3 files at r2, 2 of 4 files at r3.
Review status: 17 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 241 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjWAqJFUGiZxLJJQXTe:-KjWAqJFUGiZxLJJQXTf:b-wd99gu) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L241)):*
> ```cpp
>                               static_cast<Matrix3<double>*>(nullptr));
> 
>       V_WB.head<3>() = phi.inverse() * rpydot;
> ```

It is probably faster to use `colPivHouseholderQR` to solve `phi\rpydot`, rather than computing the inverse of a matrix.

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 97 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjWC-7oG7lofggjsrJS:-KjWC-7oG7lofggjsrJT:b-hs1bar) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L97)):*
> ```cpp
>       } else if (base_type_ ==
>                  multibody::joints::FloatingBaseType::kQuaternion) {
>         // Checks for -quat = quat.
> ```

BTW, you can check if two quaternions are equal, by computing if the absolute value of their inner product is 1.

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 273 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjWCQBhq1EJghPrpCw1:-KjWCQBhq1EJghPrpCw2:bg3vls6) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L273)):*
> ```cpp
> 
>   // Should leave the unknown joint as is.
>   EXPECT_EQ(message_.joint_name[kExtraIndex], "bilibili");
> ```

`bilibili` and `233`? Hmm I know what you watch on the internet 😉

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjWEOd9l8q2Rv1o5bNO:b-os5xp3)*

**Comment by siyuanfeng-tri** [comment]
-@jwnimmer-tri +@sammy-tri for platform, i'd like sammy to take a look at this. 

---

Review status: 17 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 97 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjWC-7oG7lofggjsrJS:-KjYGj66XungT-wFfGYh:b-hjm8mx) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L97)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, you can check if two quaternions are equal, by computing if the absolute value of their inner product is 1.
</blockquote></details>

yeah. i did this most to reuse the matrix comparison for the rest. 

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 273 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjWCQBhq1EJghPrpCw1:-KjYGt1qhlNDbpjg_0fg:bb7hf0f) ([raw file](https://github.com/robotlocomotion/drake/blob/3559764364373cccdcbf63a8e110699685180254/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L273)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`bilibili` and `233`? Hmm I know what you watch on the internet 😉
</blockquote></details>

hehe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjYGR806U7KPqMlYz1c:bjsac1g)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
checkpoint, only completed partial pass

---

Reviewed 3 of 19 files at r1, 1 of 4 files at r3.
Review status: 17 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/BUILD, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjcc0IgUntQAVw9lKz6:-Kjcc0IgUntQAVw9lKz7:b3l53c) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/BUILD#L31)):*
> ```Python
>     data = [
>         "//drake/examples/Valkyrie:models",
>         "//drake/examples/schunk_wsg:models",
> ```

FYI In general, I'd like to move the models we're using for tests out of examples and into the 'main' drake code.  I'm definitely planning on doing this with the schunk_wsg model, though Valkyrie is a little bigger and more complicated (there's also some precedent because multibody has tests which use Valkyrie too).  Perhaps this is at least worth a TODO moving models used in tests out of examples?

(FWIW, the thing from #5809 is a pretty different model which I don't think would work with this test)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjcfoTYtnGfho9NU4lH:bi59bdk)*

**Comment by sammy-tri** [comment]
first pass complete

---

Reviewed 12 of 19 files at r1, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 163 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjcuBvsRnkw9zF127xM:-KjcuBvsRnkw9zF127xN:b-al5xra) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L163)):*
> ```cpp
>   // Encode all the other joints assuming they are all 1 dof.
>   size_t num_1dof_q = robot_.get_num_positions();
>   size_t num_1dof_v = robot_.get_num_velocities();
> ```

Is this actually used for anything?  I think I only see num_1dof_q below.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 182 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjcu1w36I-7wHmuL4ys:-Kjcu1w4w-v7U7siZhII:blusyor) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L182)):*
> ```cpp
> 
>   // Initialize joints.
>   int joint_ctr = 0;
> ```

Is this an abbreviation for "counter"?  It wasn't obvious to me.  https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 183 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjcuKFUSe-ssMLDMRCk:-KjcuKFVvTdziHvmu4N9:b-4n4ebj) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L183)):*
> ```cpp
>   // Initialize joints.
>   int joint_ctr = 0;
>   for (int i = 0; i < robot_.get_num_positions(); i++) {
> ```

Does this work correctly in the case of the floating base?  I feel like in that case we should start at a non-zero offset (among other possible issues?)

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 319 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjd6J_gth1KmJO8QszF:-Kjd6J_hi1VvBEgdyqA6:bcrnn1n) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L319)):*
> ```cpp
>   message_.joint_effort.erase(message_.joint_effort.begin() + kExtraIndex);
> 
>   SetRandomQVTorque(&q, &v, &torque);
> ```

This appears to duplicate the same call a few lines above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-Kjd8H_yDw7kdtLK-7fo:b-ajvgvh)*

**Comment by siyuanfeng-tri** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/manipulation/util/BUILD, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjcc0IgUntQAVw9lKz6:-KjdEbMYvUnwArboH_Iv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/BUILD#L31)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

FYI In general, I'd like to move the models we're using for tests out of examples and into the 'main' drake code.  I'm definitely planning on doing this with the schunk_wsg model, though Valkyrie is a little bigger and more complicated (there's also some precedent because multibody has tests which use Valkyrie too).  Perhaps this is at least worth a TODO moving models used in tests out of examples?

(FWIW, the thing from #5809 is a pretty different model which I don't think would work with this test)
</blockquote></details>

Done.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 163 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjcuBvsRnkw9zF127xM:-KjdD6KgBV6REqlt-k42:by2zfe2) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L163)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this actually used for anything?  I think I only see num_1dof_q below.
</blockquote></details>

there is a assertion down there. 

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 182 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjcu1w36I-7wHmuL4ys:-KjdD9kV0j2X8qNnI-7N:b-cyafn9) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L182)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this an abbreviation for "counter"?  It wasn't obvious to me.  https://google.github.io/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

ok fine. 

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 183 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjcuKFUSe-ssMLDMRCk:-KjdDZk6zPiprc2NYIYO:b-xpcs5g) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L183)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this work correctly in the case of the floating base?  I feel like in that case we should start at a non-zero offset (among other possible issues?)
</blockquote></details>

yes. it's checking against joint_name_to_q_index_, which is constructed to exclude the floating base. 

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 241 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjWAqJFUGiZxLJJQXTe:-KjdFj72sVghgr_1VL1w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L241)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is probably faster to use `colPivHouseholderQR` to solve `phi\rpydot`, rather than computing the inverse of a matrix.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 319 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjd6J_gth1KmJO8QszF:-KjdEF3dbPuf9AwFYZPP:bintplq) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L319)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This appears to duplicate the same call a few lines above.
</blockquote></details>

rm the previous one. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 163 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjcuBvsRnkw9zF127xM:-KjdN9A0dr5Mf738WV5t:b2cz0ik) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L163)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

there is a assertion down there. 
</blockquote></details>

So there is!

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 183 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-KjcuKFUSe-ssMLDMRCk:-KjdNFuu6Dnbp63TAcA0:b-nylnzc) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/robot_state_msg_translator.cc#L183)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

yes. it's checking against joint_name_to_q_index_, which is constructed to exclude the floating base. 
</blockquote></details>

which explains how the tests pass...   and is consistent with the comments in the header.

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 319 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-Kjd6J_gth1KmJO8QszF:-KjdNaTUOrXuI2jM6fEv:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/9074c4e080392d7c2b2027621612c477b7dbc396/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L319)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

rm the previous one. 
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6043#-:-KjdNcfVpAU_pS399wJs:bnfp4nl)*

**Pull request merged**
