### PR TITLE
Adds PriusVis.

### PR DESCRIPTION
**Pull request by liangfok**
This is another incremental step towards #5541.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5602)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review since this PR builds upon #5582.
+@jwnimmer-tri for platform and car reviews please.
Thanks!

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-:-Kg7t5edwkeJyKZMHm9V:b-5orfqs)*

**Comment by liangfok** [comment]
It just occurred to me that we might be able to switch to quaternion floating joints and thus partially address spiral 3 of #3919. I'm not yet sure if I want to include that in this PR or a follow-up PR. I will try and see how difficult it is.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-:-Kg9QtDHOjqNKPvr4HTp:b-pfnr8d)*

**Comment by jwnimmer-tri** [comment]
Please don't add spiral 3.  It's not an objective right now.

:car: approved.

---

Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/BUILD, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9VZSIpRJ8PQpk1EYo:-Kg9VZSJ-L9R2ntuRZg7:b34lt05) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/BUILD#L235)):*
> ```Python
>         "//drake/systems/rendering:pose_vector",
>     ],
> )
> ```

The `data=[]` should go here (and not on the unit test )since this is the component that hard-codes the SDF filename.

---

*[drake/automotive/prius_vis.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9WTAbG0k4erhCmFdb:-Kg9WTAccvi5cNKajTse:b-2mp8k5) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/prius_vis.cc#L70)):*
> ```cpp
>   q(4) = rpy(1);
>   q(5) = rpy(0);
>   const KinematicsCache<T> cache = tree_->doKinematics(q);
> ```

FYI ... and this is why the `lcmt_draw` abstraction is evil, and we should stop using it ASAP.  There is absolutely no reason why we should have kinematics happening for this rendering.  For rendering, the internal bodies of the car should be expressed relative to the car's origin.

---

*[drake/automotive/prius_vis.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9WD5AiGFYi5JFFGne:-Kg9WD5BMcyxCIGYeFJ3:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/prius_vis.h#L13)):*
> ```objc
> #include "drake/common/drake_copyable.h"
> #include "drake/lcmtypes/drake/lcmt_viewer_link_data.hpp"
> #include "drake/multibody/kinematics_cache.h"
> ```

Unused.

---

*[drake/automotive/prius_vis.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9VtIX07CjEOHMpX0x:-Kg9VtIX07CjEOHMpX0y:butkudi) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/prius_vis.h#L43)):*
> ```objc
>  private:
>   static const int kNumPositionDofs;
>   static const int kNumVelocityDofs;
> ```

BTW Putting the kConstants in the class (instead of the cc file) is a lot of syntax for no gain.

---

*[drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9VGDYzdt1ffhMKKqr:-Kg9VGDYzdt1ffhMKKqs:b-jh6t6k) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h#L1)):*
> ```objc
> #pragma once
> ```

Since this is code pulled out of `drake_visualizer`, and is visualization related, why not put this code into the same folder as where it came from?  It doesn't seem like a top-level multibody concept.

---

*[drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9V7x8izAZ1gTgiRhb:-Kg9V7x9ZyKLLYeST1yw:b-fvm1hn) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h#L20)):*
> ```objc
> /// @ingroup automotive_systems
> template <typename T>
> lcmt_viewer_load_robot CreateLoadMessage(const RigidBodyTree<double>& tree);
> ```

BTW Usually I would expect the filename and function name to be more consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-:-Kg9X6qEcGQwNLjPnRn2:b-nstx77)*

**Comment by liangfok** [comment]
Alright, I will make the switch to quaternion floating joints in a future PR.

---

Review status: 1 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/BUILD, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9VZSIpRJ8PQpk1EYo:-Kg9XqvT3wG2LXMG8asc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/BUILD#L235)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `data=[]` should go here (and not on the unit test )since this is the component that hard-codes the SDF filename.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9WTAbG0k4erhCmFdb:-Kg9YBRuIGNBqrImzCN9:b-3glmgh) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/prius_vis.cc#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI ... and this is why the `lcmt_draw` abstraction is evil, and we should stop using it ASAP.  There is absolutely no reason why we should have kinematics happening for this rendering.  For rendering, the internal bodies of the car should be expressed relative to the car's origin.
</blockquote></details>

Agreed. 

---

*[drake/automotive/prius_vis.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9WD5AiGFYi5JFFGne:-Kg9YQor8LySc5-5PzlC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/prius_vis.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9VtIX07CjEOHMpX0x:-Kg9YgkxkhJ38nuOG-vR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/automotive/prius_vis.h#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Putting the kConstants in the class (instead of the cc file) is a lot of syntax for no gain.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9VGDYzdt1ffhMKKqr:-Kg9bT189LW180ecEPc_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since this is code pulled out of `drake_visualizer`, and is visualization related, why not put this code into the same folder as where it came from?  It doesn't seem like a top-level multibody concept.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9V7x8izAZ1gTgiRhb:-Kg9bUEPlSVEX36HxFb6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32c415daa6b9f5f5f39f219a87d1d80463a251ad/drake/multibody/rigid_body_tree_create_lcm_viewer_load_message.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Usually I would expect the filename and function name to be more consistent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-:-Kg9XdDY-zX5_LLHkQv-:b-79a5eb)*

**Comment by jwnimmer-tri** [comment]
Reviewed 10 of 12 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/CMakeLists.txt, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9lbDTkehlW6sYkJde:-Kg9lbDU0n4CgjvaO-nU:b-47vbpm) ([raw file](https://github.com/robotlocomotion/drake/blob/34604409e7de08d9c74755e9bb269d7e89129132/drake/multibody/rigid_body_plant/CMakeLists.txt#L85)):*
> ```CMake
>   drake_install_libraries(drakeCreateLoadRobotMessage)
>   drake_install_headers(create_load_robot_message.h)
> endif ()
> ```

FYI If I were author, I would have put the new code into the `lcm_dependent_{header,source}_files` lists, instead of making a new library.  A CMake library for a single function seems a bit excessive; even moreso when the plant _and visualizer_ are both already in a single, convenient library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602)*

**Comment by liangfok** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/CMakeLists.txt, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9lbDTkehlW6sYkJde:-Kg9rp3uni2RLJTRYrFP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34604409e7de08d9c74755e9bb269d7e89129132/drake/multibody/rigid_body_plant/CMakeLists.txt#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If I were author, I would have put the new code into the `lcm_dependent_{header,source}_files` lists, instead of making a new library.  A CMake library for a single function seems a bit excessive; even moreso when the plant _and visualizer_ are both already in a single, convenient library.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 14 files at r1, 9 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[drake/automotive/BUILD, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFQU6mOB2mTcrTF45R:-KgFQU6nSNoqGpXp_pux:bzczimh) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/BUILD#L227)):*
> ```Python
>     data = ["//drake/automotive:models"],
>     deps = [
>         ":car_vis_applicator",
> ```

too broad. use `:car_vis` instead, in conjunction with include hygiene noted elsewhere.

---

*[drake/automotive/BUILD, line 228 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFQtHHDae3yLRak0dY:-KgFQtHHDae3yLRak0dZ:bzg5crh) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/BUILD#L228)):*
> ```Python
>     deps = [
>         ":car_vis_applicator",
>         ":generated_vectors",
> ```

unused (i think).

---

*[drake/automotive/prius_vis.cc, line 3 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFL4c4SdHnEb8w6WmI:-KgFL4c55i1RTxj_gzRS:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L3)):*
> ```cpp
> #include "drake/automotive/prius_vis.h"
> 
> #include <utility>
> ```

unused.

---

*[drake/automotive/prius_vis.cc, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFKkGZxw4yoD_vIs_f:-KgFKkG_SPlPD87kaPnc:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L5)):*
> ```cpp
> #include <utility>
> 
> #include <Eigen/Geometry>
> ```

unused.

---

*[drake/automotive/prius_vis.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFKXzvdRvrvg0Nq66P:-KgFKXzvdRvrvg0Nq66Q:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L14)):*
> ```cpp
> #include "drake/multibody/parsers/sdf_parser.h"
> #include "drake/multibody/rigid_body_plant/create_load_robot_message.h"
> #include "drake/multibody/shapes/visual_element.h"
> ```

unused.

---

*[drake/automotive/prius_vis.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNygCoewESPJp6k83:-KgFNygCoewESPJp6k84:b-6dojnu) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L15)):*
> ```cpp
> #include "drake/multibody/rigid_body_plant/create_load_robot_message.h"
> #include "drake/multibody/shapes/visual_element.h"
> #include "drake/systems/framework/value.h"
> ```

unused, once the vacuous alias below is removed.

---

*[drake/automotive/prius_vis.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFOBZstaiSmzfuLEbj:-KgFOBZtddXR1n180Q0T:b-6dojnu) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L16)):*
> ```cpp
> #include "drake/multibody/shapes/visual_element.h"
> #include "drake/systems/framework/value.h"
> #include "drake/systems/rendering/drake_visualizer_client.h"
> ```

unused, once the vacuous alias below is removed.

---

*[drake/automotive/prius_vis.cc, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNL0HZBmMHVBjcsDW:-KgFNL0HZBmMHVBjcsDX:b4fsqkj) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L23)):*
> ```cpp
> namespace drake {
> 
> using multibody::CreateLoadRobotMessage;
> ```

unused alias.

---

*[drake/automotive/prius_vis.cc, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNf1aCcapGNv7TuXp:-KgFNf1aCcapGNv7TuXq:ba9pykr) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L25)):*
> ```cpp
> using multibody::CreateLoadRobotMessage;
> using multibody::joints::kRollPitchYaw;
> using systems::rendering::MakeGeometryData;
> ```

unused entirely.

---

*[drake/automotive/prius_vis.cc, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNkvSlA5YdlN8eXZa:-KgFNkvSlA5YdlN8eXZb:ba9pykr) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L27)):*
> ```cpp
> using systems::rendering::MakeGeometryData;
> using systems::rendering::PoseBundle;
> using systems::rendering::PoseVector;
> ```

unused entirely.

---

*[drake/automotive/prius_vis.cc, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNosNyA-ybMoyZIl7:-KgFNosNyA-ybMoyZIl8:ba9pykr) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L28)):*
> ```cpp
> using systems::rendering::PoseBundle;
> using systems::rendering::PoseVector;
> using systems::Value;
> ```

unused entirely.

---

*[drake/automotive/prius_vis.h, line 7 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFCyzrD9C6NmvoMmOG:-KgFCyzsextTpPvMhHL6:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.h#L7)):*
> ```objc
> #include <vector>
> 
> #include <Eigen/Dense>
> ```

unused.

---

*[drake/automotive/prius_vis.h, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFD-17cE2_ZMT_Jp0w:-KgFD-17cE2_ZMT_Jp0x:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.h#L8)):*
> ```objc
> 
> #include <Eigen/Dense>
> #include <Eigen/Geometry>
> ```

unused.

---

*[drake/automotive/prius_vis.h, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFD0SGTdjpxPNxflFE:-KgFD0SHVbyHqxU4B7na:bfu8xot) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.h#L10)):*
> ```objc
> #include <Eigen/Geometry>
> 
> #include "drake/automotive/car_vis_applicator.h"
> ```

way too broad; use `car_vis.h` and `pose_vector.h` instead.

---

*[drake/automotive/test/prius_vis_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFLs8K-KTfOqouoZlY:-KgFLs8LNTn6Vtucj2D1:bv6r900) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/test/prius_vis_test.cc#L14)):*
> ```cpp
> #include "drake/systems/rendering/pose_bundle.h"
> 
> using std::vector;
> ```

this is weird. Of four mentions of std::vector in the code, only one avails itself of  this alias. suggest ditching the alias and just spelling out std::vector everywhere.

---

*[drake/automotive/test/prius_vis_test.cc, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFMlYgsI9bJOZrfZQm:-KgFMlYgsI9bJOZrfZQn:b4q5tvr) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/test/prius_vis_test.cc#L19)):*
> ```cpp
> 
> using systems::rendering::FrameVelocity;
> using systems::rendering::PoseBundle;
> ```

this alias is unused in the code below.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9hJgUAf2K-jE0R_n_:-Kg9hJgUAf2K-jE0R_na:b-6i0yln) ([raw file](https://github.com/robotlocomotion/drake/blob/34604409e7de08d9c74755e9bb269d7e89129132/drake/multibody/rigid_body_plant/drake_visualizer.cc#L11)):*
> ```cpp
> 
> namespace drake {
> namespace systems {
> ```

are these namespaces conforming? they look stale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602)*

**Comment by liangfok** [comment]
Review status: 6 of 10 files reviewed at latest revision, 17 unresolved discussions.

---

*[drake/automotive/BUILD, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFQU6mOB2mTcrTF45R:-KgFVxVZvgNsZxptQnPe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/BUILD#L227)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

too broad. use `:car_vis` instead, in conjunction with include hygiene noted elsewhere.
</blockquote></details>

Done.

---

*[drake/automotive/BUILD, line 228 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFQtHHDae3yLRak0dY:-KgFWAhTXLpCNxUQ8zJW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/BUILD#L228)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused (i think).
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 3 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFL4c4SdHnEb8w6WmI:-KgFWJaqWhZn3Ul1j8vM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFKkGZxw4yoD_vIs_f:-KgFWKLgY1Dr8-LDC2ge:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L5)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFKXzvdRvrvg0Nq66P:-KgFWMei-21ZYZgQQ70p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNygCoewESPJp6k83:-KgFWXnd8tpq9g0voPhi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L15)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused, once the vacuous alias below is removed.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFOBZstaiSmzfuLEbj:-KgFW_qGVEfEOYl1FkNy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L16)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused, once the vacuous alias below is removed.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNL0HZBmMHVBjcsDW:-KgFWTRw0s5n6YwOW11I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L23)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused alias.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNf1aCcapGNv7TuXp:-KgFWbQ28snFAc_4VR47:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L25)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused entirely.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNkvSlA5YdlN8eXZa:-KgFWdFG5UlDjH5LsQ2T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused entirely.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.cc, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFNosNyA-ybMoyZIl7:-KgFWgyAOZJiyxbTkHZC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.cc#L28)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused entirely.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.h, line 7 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFCyzrD9C6NmvoMmOG:-KgFWlO85Izq2tC8KhuX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.h#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.h, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFD-17cE2_ZMT_Jp0w:-KgFWm0C1OGyMn2hOszC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.h#L8)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[drake/automotive/prius_vis.h, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFD0SGTdjpxPNxflFE:-KgFWo0Q3BDW1ZrlXQyr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/prius_vis.h#L10)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

way too broad; use `car_vis.h` and `pose_vector.h` instead.
</blockquote></details>

Done.

---

*[drake/automotive/test/prius_vis_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFLs8K-KTfOqouoZlY:-KgFWx93VoJpy4y-bth8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/test/prius_vis_test.cc#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

this is weird. Of four mentions of std::vector in the code, only one avails itself of  this alias. suggest ditching the alias and just spelling out std::vector everywhere.
</blockquote></details>

Done.

---

*[drake/automotive/test/prius_vis_test.cc, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-KgFMlYgsI9bJOZrfZQm:-KgFX8vDAgvbRxXzcMSu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68cecfd290d4449f7ce09e53b01959472b5b3969/drake/automotive/test/prius_vis_test.cc#L19)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

this alias is unused in the code below.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-Kg9hJgUAf2K-jE0R_n_:-KgFXCarewuzxIPCzp-i:b4kz0ck) ([raw file](https://github.com/robotlocomotion/drake/blob/34604409e7de08d9c74755e9bb269d7e89129132/drake/multibody/rigid_body_plant/drake_visualizer.cc#L11)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

are these namespaces conforming? they look stale.
</blockquote></details>

They are definitely stale: #5511.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: 6 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-:-KgFcb35c14WQrTS83Os:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-debug please.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5602#-:-KgFnUwZ4wfVlIGRH4NL:bcpz082)*

**Pull request merged**
