### PR TITLE
Introduce ToAutoDiffXd for Diagrams.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #3967.  Uses some template-magic infrastructure that should be easily extensible to other scalar types.

@sherm1 catches this for platform review, since it's Monday (and bonus points for shared interest in #3967).  Will shop around on Slack for a feature reviewer.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4210)

### CODE REVIEW

**Comment by sherm1** [comment]
Two cpplint complaints [here](https://drake-cdash.csail.mit.edu/viewBuildError.php?type=1&buildid=210158).

**Comment by amcastro-tri** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/system.h, line 464 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXBv2qf--mbHd9H6INz:-KXBv2qg_uZ9HoSuA4R6:b-9gi3z2) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L464)):*
> ```objc
>   /// @tparam S The specific System pointer type to return.
>   template <template <typename> class S = ::drake::systems::System>
>   static std::unique_ptr<S<AutoDiffXd>> ToAutoDiffXd(
> ```

BTW, I see. So the previous version of this code was leaking when the downcast was unsuccessful? 
But I thought the `template <typename> class S = ::drake::systems::System` line above was making this method to only take Systems? I'm confused :-(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Comment by sherm1** [comment]
*[drake/systems/framework/system.h, line 459 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC-d4eAotHByHlox9L:-KXBxx40DLeDRnvcOHWK:bgqhpju) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L459)):*
> ```objc
>   ///   MySystem<double> plant;
>   ///   std::unique_ptr<MySystem<AutoDiffXd>> ad_plant =
>   ///       systems::System<double>::ToAutoDiffXd<MySystem>(plant);
> ```

I've forgotten why this static method & template magic is needed. Is there something wrong with this:
```c++
MySystem<double> plant;
std::unique_ptr<MySystem<AutoDiffXd>> ad_plant = plant.ToAutoDiffXd();
```
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Comment by david-german-tri** [comment]
Done.

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 459 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC-d4eAotHByHlox9L:-KXCABJEKiIhEV0s_TB-:bcjarjj) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L459)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I've forgotten why this static method & template magic is needed. Is there something wrong with this:
> ```c++
> MySystem<double> plant;
> std::unique_ptr<MySystem<AutoDiffXd>> ad_plant = plant.ToAutoDiffXd();
> ```
> ?
</details>
`System<T>::ToAutoDiffXd` can't have `MySystem` in its signature; the user would have to write a cast.  This static method just hides the details of that cast (which are now uglier than before, so the benefit has increased!).

---

*[drake/systems/framework/system.h, line 464 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXBv2qf--mbHd9H6INz:-KXCA-v6mSy4L9J7Q5CW:b7a96t6) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L464)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, I see. So the previous version of this code was leaking when the downcast was unsuccessful? 
> But I thought the `template <typename> class S = ::drake::systems::System` line above was making this method to only take Systems? I'm confused :-(
</details>
By default, `S` is `System`, but the caller might request `ToAutoDiffXd<MyParticularSystem>`, which would return nullptr if the instance is not actually a `MyParticularSystem`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-:-KXCAlLaZV9AGlYDgf5B:b-896fix)*

**Comment by sherm1** [comment]
Awesome. A few comments, PTAL.

---

Reviewed 6 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 473 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC9KX0YsD-Bi4qgnBb:-KXC9KX1hzWQ-34d-fQ2:b-jbw2o4) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/diagram.h#L473)):*
> ```objc
>   /// @tparam NewType The scalar type to which to convert.
>   /// @tparam T1 SFINAE boilerplate.
>   template <typename NewType, typename T1 = T>
> ```

Is T1 necessary? I would have thought you could use `std::is_same<T, double>` below with the same effect.

---

*[drake/systems/framework/diagram.h, line 487 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXCB2-Ums8o2TZv1TgM:-KXCB2-VAzjNcIleRlLs:bge45oj) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/diagram.h#L487)):*
> ```objc
> 
>     // Set up the blueprint.
>     typename Diagram<NewType>::Blueprint blueprint;
> ```

This is really cool!
Do you think this Blueprint-building functionality would be better placed with DiagramBuilder rather than Diagram?

---

*[drake/systems/framework/system.h, line 459 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC-d4eAotHByHlox9L:-KXCBt6ceNiI3CGtgs7i:b-xvo2vr) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L459)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> `System<T>::ToAutoDiffXd` can't have `MySystem` in its signature; the user would have to write a cast.  This static method just hides the details of that cast (which are now uglier than before, so the benefit has increased!).
</details>
With NVI, the public MySystem::ToAutoDiffXd() can hide System::ToAutoDiffXd() and return `unique_ptr<MySystem<AutoDiffXd>>` with no dynamic casting at all. But that does take some cooperation from the System writer. The casting method here seems useful, but I think there ought to be a System public method
```c++
std::unique_ptr<System<AutoDiffXd>> ToAutoDiffXd() const {
  return std::unique_ptr<System<AutoDiffXd>>(DoToAutoDiffXd());
}
```
that follows the standard NVI pattern, with this additional signature as sugar to help with the messy casting if needed.

---

*[drake/systems/framework/primitives/adder.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXCEk_BsGDXES00ulp4:-KXCEk_BsGDXES00ulp5:b-bdi1id) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/primitives/adder.h#L42)):*
> ```objc
>   void EvalOutput(const Context<T>& context,
>                   SystemOutput<T>* output) const override;
> ```

BTW, consider adding
```c++
std::unique_ptr<Adder<AutoDiffXd>> ToAutoDiffXd() const {
  return std::unique_ptr<Adder<AutoDiffXd>>(DoToAutoDiffXd());
}
```

---

*[drake/systems/framework/primitives/integrator.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXCFA103FRNINlbCXGu:-KXCFA103FRNINlbCXGv:b83id5v) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/primitives/integrator.h#L44)):*
> ```objc
>   void EvalTimeDerivatives(const Context<T>& context,
>                            ContinuousState<T>* derivatives) const override;
> ```

BTW, consider adding
```c++
std::unique_ptr<Integrator<AutoDiffXd>> ToAutoDiffXd() const {
  return std::unique_ptr<Integrator<AutoDiffXd>>(DoToAutoDiffXd());
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-:-KXCGrR9CHSZhQjYeI2o:b24z54w)*

**Comment by sherm1** [comment]
Reviewed 1 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Comment by amcastro-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/system.h, line 464 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXBv2qf--mbHd9H6INz:-KXCgAL8aA7dozqu8tU2:b-m044iu) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L464)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> By default, `S` is `System`, but the caller might request `ToAutoDiffXd<MyParticularSystem>`, which would return nullptr if the instance is not actually a `MyParticularSystem`.
</details>
I see. Thank you for the f2f.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Comment by david-german-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 473 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC9KX0YsD-Bi4qgnBb:-KXCi6s2Cgaylk3FuGxZ:bdux2mk) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/diagram.h#L473)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Is T1 necessary? I would have thought you could use `std::is_same<T, double>` below with the same effect.
</details>
http://stackoverflow.com/questions/30953248/why-doesnt-sfinae-enable-if-work-for-member-functions-of-a-class-template

---

*[drake/systems/framework/diagram.h, line 487 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXCB2-Ums8o2TZv1TgM:-KXCfNsi916MqNOgQTqZ:bty9xtj) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/diagram.h#L487)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is really cool!
> Do you think this Blueprint-building functionality would be better placed with DiagramBuilder rather than Diagram?
</details>
That's what I did in my first draft; then the compiler pointed out I was creating a circular dependency.  

---

*[drake/systems/framework/system.h, line 459 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC-d4eAotHByHlox9L:-KXCg0DUsZyBMNsqGvyU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/system.h#L459)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> With NVI, the public MySystem::ToAutoDiffXd() can hide System::ToAutoDiffXd() and return `unique_ptr<MySystem<AutoDiffXd>>` with no dynamic casting at all. But that does take some cooperation from the System writer. The casting method here seems useful, but I think there ought to be a System public method
> ```c++
> std::unique_ptr<System<AutoDiffXd>> ToAutoDiffXd() const {
>   return std::unique_ptr<System<AutoDiffXd>>(DoToAutoDiffXd());
> }
> ```
> that follows the standard NVI pattern, with this additional signature as sugar to help with the messy casting if needed.
> 
</details>
Done.

---

*[drake/systems/framework/primitives/adder.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXCEk_BsGDXES00ulp4:-KXChAvYjnpAezDRhlRx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/primitives/adder.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, consider adding
> ```c++
> std::unique_ptr<Adder<AutoDiffXd>> ToAutoDiffXd() const {
>   return std::unique_ptr<Adder<AutoDiffXd>>(DoToAutoDiffXd());
> }
> ```
</details>
Done.

---

*[drake/systems/framework/primitives/integrator.h, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXCFA103FRNINlbCXGu:-KXChBamhVm4BLIdo5SJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/primitives/integrator.h#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, consider adding
> ```c++
> std::unique_ptr<Integrator<AutoDiffXd>> ToAutoDiffXd() const {
>   return std::unique_ptr<Integrator<AutoDiffXd>>(DoToAutoDiffXd());
> }
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Comment by sherm1** [comment]
One BTW comment fix needed, then :lgtm:.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 473 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXC9KX0YsD-Bi4qgnBb:-KXDHNkK53btUzTxow9Z:b-x96psc) ([raw file](https://github.com/robotlocomotion/drake/blob/fcb9b364f879394ad4a7425d1c54f909cba63aae/drake/systems/framework/diagram.h#L473)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> http://stackoverflow.com/questions/30953248/why-doesnt-sfinae-enable-if-work-for-member-functions-of-a-class-template
</details>
Got it -- thanks!

---

*[drake/systems/framework/system.h, line 479 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXDI4w9IHJ_tvtBbVqR:-KXDI4w9IHJ_tvtBbVqS:b4a1ovv) ([raw file](https://github.com/robotlocomotion/drake/blob/2f804e8ce1b8dc58a2579e413d36a2aed752d9e9/drake/systems/framework/system.h#L479)):*
> ```objc
>   }
> 
>   /// Creates a deep copy of @p from, transmogrified to use the autodiff
> ```

BTW, "a deep copy of `this`"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-:-KXDIYmX5Bkhct4mkjG1:b-xfx6ky)*

**Comment by david-german-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 479 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXDI4w9IHJ_tvtBbVqR:-KXDKX8R7c8Do5GQfAty:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f804e8ce1b8dc58a2579e413d36a2aed752d9e9/drake/systems/framework/system.h#L479)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, "a deep copy of `this`"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Comment by david-german-tri** [comment]
+@amcastro-tri for feature review - you made the mistake of showing interest!

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-:-KXDKcqwfdLYMTq3e_VW:b17ktjo)*

**Comment by amcastro-tri** [comment]
Just one small comment on the unit testing of the new API you added in r2.

---

Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 246 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXGaM7kqS3gCKmvPeF6:-KXGaM7lWDuoQOXOL48q:bjkqvhg) ([raw file](https://github.com/robotlocomotion/drake/blob/4df897027ec0f31eacbc073318242d8064dd3b16/drake/systems/framework/test/diagram_test.cc#L246)):*
> ```cpp
> TEST_F(DiagramTest, ToAutoDiffXd) {
>   std::unique_ptr<System<AutoDiffXd>> ad_diagram =
>       System<double>::ToAutoDiffXd(*diagram_);
> ```

now per this PR we have the method `System<T>::ToAutoDiffXd()` and we could do `ad_diagram = diagram->ToAutoDiffXd()`? should we unit test that as well? Maybe just same test but calling that API instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-:-KXGayIs8mnPl7v7wrkc:b-jdp8t)*

**Comment by RussTedrake** [comment]
fwiw - a lot of the code i'm writing would be MUCH easier if this was in.

**Comment by amcastro-tri** [comment]
Besides my small comment on testing here this :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-:-KXfHrtsAFI2bs3PM5k7:b-8nt3il)*

**Comment by david-german-tri** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/framework/test/diagram_test.cc, line 246 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4210#-KXGaM7kqS3gCKmvPeF6:-KXfSryCuZQmkwA6MdCP:b-r536yw) ([raw file](https://github.com/robotlocomotion/drake/blob/4df897027ec0f31eacbc073318242d8064dd3b16/drake/systems/framework/test/diagram_test.cc#L246)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

now per this PR we have the method `System<T>::ToAutoDiffXd()` and we could do `ad_diagram = diagram->ToAutoDiffXd()`? should we unit test that as well? Maybe just same test but calling that API instead.
</blockquote></details>

That's a good idea, but I'll do it in a small follow-up PR since this is blocking Russ.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4210)*

**Pull request merged**
