### PR TITLE
[C-IRIS] support cylinder geometry.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18613)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-monterey-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18613)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 574 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM525Tl5frQc4Akm6yU:-NM525Tl5frQc4Akm6yV:b-jraiwk) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d1406ab39221500f7614cdf4140cb050c4de15c/geometry/optimization/dev/collision_geometry.cc#L574)):*
> ```cpp
>     case GeometryType::kPolytope:
>       return 0;
>     case GeometryType::kSphere:
> ```

missing code for the `kSphere` case.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM632q_1e0gwk-qH3tg:-NM632q_1e0gwk-qH3th:b9afkmi) ([raw file](https://github.com/RobotLocomotion/drake/blob/abc6606e0deaf9d51eb1af211401721fd84619c0/geometry/optimization/dev/collision_geometry.cc#L256)):*
> ```cpp
> 
>   void ImplementGeometry(const Cylinder& cylinder, void* data) {
>     // Consider a cylinder with radius r and length l, if this cylinder is on
> ```

We use height `h` in the `ImplementGeometry` for the signed distance in `collision_geometry.cc` but here we use `l`. I would prefer to keep these unified.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 267 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM5vZuSEI0PGYvAWPcK:-NM5vZuSEI0PGYvAWPcL:b-5bg0yc) ([raw file](https://github.com/RobotLocomotion/drake/blob/abc6606e0deaf9d51eb1af211401721fd84619c0/geometry/optimization/dev/collision_geometry.cc#L267)):*
> ```cpp
>     // only if both the top and bottom rims of the cylinder are on the positive
>     // side of the plane, namely a_G.dot([r*cosθ, r*sinθ, ±l/2]) + b_G ≥ 0 for
>     // any θ, which is equivalent to
> ```

I would change this to "... for any θ. Minimizing over θ implies that this condition is equivalent to."
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 355 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM6BJjZ-D523KdHhaSZ:-NM6BJjZ-D523KdHhaS_:b-5d9jgw) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb7d2b7624117e26738e212fae5b5b975a069d8d/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L355)):*
> ```cpp
>       throw std::runtime_error(
>           "Cylinder has not been implemented yet for C-IRIS.");
>     }
> ```

BTW: Awesome we can remove this now!
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 883 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM6BQ8iEk9gfsIda07g:-NM6BQ8iEk9gfsIda07h:b-2old6b) ([raw file](https://github.com/RobotLocomotion/drake/blob/abc6606e0deaf9d51eb1af211401721fd84619c0/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L883)):*
> ```cpp
>             plane.decision_variables, certificate->plane_decision_var_vals, C,
>             d, tester, 0);
>         const double small_coeff_tol = 1E-4;
> ```

BTW: I wonder what we/Mosek are doing to make this the acceptable constraint violation threshold?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18613)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 574 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM525Tl5frQc4Akm6yU:-NMALDYf72Xm_uUz0WHj:bkf2h3r) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d1406ab39221500f7614cdf4140cb050c4de15c/geometry/optimization/dev/collision_geometry.cc#L574)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

missing code for the `kSphere` case.
</blockquote></details>

Here by using
```cc
case GeometryType::kSphere:
case GeometryType::kCapsule:
  return 3;
```
it means for both sphere and capsule, return 3. Check https://www.tutorialspoint.com/cplusplus/cpp_switch_statement.htm#:~:text=Not%20every%20case%20needs%20to%20contain%20a%20break.%20If%20no%20break%20appears%2C%20the%20flow%20of%20control%20will%20fall%20through%20to%20subsequent%20cases%20until%20a%20break%20is%20reached
___
*[`geometry/optimization/dev/collision_geometry.cc` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM632q_1e0gwk-qH3tg:-NMAKsaFECuDXyB10VHd:boirwoy) ([raw file](https://github.com/RobotLocomotion/drake/blob/abc6606e0deaf9d51eb1af211401721fd84619c0/geometry/optimization/dev/collision_geometry.cc#L256)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We use height `h` in the `ImplementGeometry` for the signed distance in `collision_geometry.cc` but here we use `l`. I would prefer to keep these unified.
</blockquote></details>

Done. I changed both to `l` as `Cylinder` class function is named `length()`.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 267 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM5vZuSEI0PGYvAWPcK:-NMALBVE4kdA2Rc_TEB3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/abc6606e0deaf9d51eb1af211401721fd84619c0/geometry/optimization/dev/collision_geometry.cc#L267)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would change this to "... for any θ. Minimizing over θ implies that this condition is equivalent to."
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 883 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NM6BQ8iEk9gfsIda07g:-NMALnrt6K1rLdhynj1m:b-gu0mez) ([raw file](https://github.com/RobotLocomotion/drake/blob/abc6606e0deaf9d51eb1af211401721fd84619c0/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L883)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: I wonder what we/Mosek are doing to make this the acceptable constraint violation threshold?
</blockquote></details>

From my shallow understanding of Mosek, it homogenizes the problem. Namely instead of solving
```
min c' * x
s.t A*x = b
  x in K
```
it actually adds a scaling factor τ to the right handside of `A*x=b`
```
min c'  x
s.t A* x = b * τ
x in K
```
This program is always feasible (with x = 0, τ = 0). So when Mosek terminates for this scaled problem, it doesn't always mean that the original problem is satisfied to a high precision (if τ != 1).

I suspect that when there is large constraint violation, the τ solution is not exactly 1. But I don't know how to query the value of τ from Mosek.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-:-NMAOyQF008akaRPHM8d:bnfp4nl)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NMAOnwb-vaM0MaRadUD:-NMAOnwb-vaM0MaRadUE:ba1pctr) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e79ab4c80be203115c404fab034c861f980e325/geometry/optimization/dev/collision_geometry.cc#L267)):*
> ```cpp
>     // only if both the top and bottom rims of the cylinder are on the positive
>     // side of the plane, namely a_G.dot([r*cosθ, r*sinθ, ±l/2]) + b_G ≥ 0 for
>     // any θ, Minimizing over θ implies that this condition is equivalent to
> ```

there should be a period after the first θ on this line

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18613)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 267 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18613#-NMAOnwb-vaM0MaRadUD:-NMAPDAk2q8j_Ly_yiBp:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e79ab4c80be203115c404fab034c861f980e325/geometry/optimization/dev/collision_geometry.cc#L267)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

there should be a period after the first θ on this line
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18613)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
