### PR TITLE
Replace quadratic cost with affine cone constraint and linear cost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185#-:-NFJzWlH-ViE-3PIn-Wj:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm: except for a few minor issues.

Per schedule for 10/31/22, +@seancurtis-tri for platform review, please.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185#-:-NFUspeT-gWtLs2jE-99:bowg10z)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[`solvers/mosek_solver_internal.h` line 429 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUPU77DFx5NA8ly427:-NFUPU77DFx5NA8ly428:b-aau9vx) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.h#L429)):*
> ```objc
>       // zₙ₋₁² where z = A*x + b, while Mosek's rotated Lorentz cone imposes 2 *
>       // z₀ * z₁ ≥ z₂² + z₃² + ... zₙ₋₁² (notice the factor of 2). Hence we will
>       // change the coefficients of F and g in the affine expression.
> ```

BTW, I think you use F and g due to Mosek notation, however, there are no such terms in the corresponding code. So, "A and b" may make more sense here. Or, consider adding a comment somewhere explaining the correspondence between A - F and b - g.



_Code quote:_
```objc
F and g
```
___
*[`solvers/mosek_solver_internal.cc` line 565 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUlIJBC8-5YWWvkQLH:-NFUlIJBC8-5YWWvkQLI:bn3an5f) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L565)):*
> ```cpp
>     return rescode;
>   }
>   // Add g vector
> ```

typo, missing period at the end of the line



_Code quote:_
```cpp
// Add g vector
```
___
*[`solvers/mosek_solver_internal.cc` line 598 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUh5Q83eT8fXPigfhd:-NFUh5Q83eT8fXPigfhe:b1dow0n) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L598)):*
> ```cpp
>     }
>     default: {
>       throw std::runtime_error("MosekSolverProgram: unsupported cone types.");
> ```

FYI, this should be singular, I guess?



_Suggestion:_
```cpp
types
```
___
*[`solvers/mosek_solver_internal.cc` line 604 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUnmXz1Zw514qivBmR:-NFUnmXz1Zw514qivBmS:b82aftt) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L604)):*
> ```cpp
>     return rescode;
>   }
>   rescode = MSK_getnumacc(task_, acc_index);
> ```

FYI, I think adding a comment above this line (e.g., "// Update the ACC index.") could improve readability.



_Code quote:_
```cpp
  rescode = MSK_getnumacc(task_, acc_index);
```
___
*[`solvers/mosek_solver_internal.cc` line 806 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUhpHn1HZWhXNXE1G4:-NFUhpHn1HZWhXNXE1G5:b-7tcn7h) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L806)):*
> ```cpp
>     const MathematicalProgram& prog) {
>   // We can add the quaratic cost 0.5 * quadratic_vars' * Q * quadratic_vars as
>   // a linear cost with a rotated Lorentz cone constraint. To do so, we
> ```

nit, in this way, the introduction of s is explained twice (first in the sentence starting with "To do so" and then in the last sentence). I'd recommend removing the last sentence or making it more coherent.

(BTW, I guess the previous version was wrong in saying "we add new variables z", but nevertheless, might be helpful in describing how s was incorporated.)

At least, in the last sentence, "add new variables" should be changed to "add a new variable" since there is only one slack variable added. 



_Code quote:_
```cpp
  // a linear cost with a rotated Lorentz cone constraint. To do so, we
  // introduce a slack variable s, with the rotated Lorentz cone constraint
  // 2s >= | L * quadratic_vars|²,
  // where L'L = Q. We then minimize s. In Mosek, we
  // add new variables s.
```
___
*[`solvers/mosek_solver_internal.cc` line 823 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUkCEq07915dH7rt0K:-NFUkCEq07915dH7rt0L:b-4t3a5s) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L823)):*
> ```cpp
>     return rescode;
>   }
>   // Add new variable s
> ```

typo, "Add a new", also missing period at the end of the line



_Code quote:_
```cpp
Add new
```
___
*[`solvers/mosek_solver_internal.cc` line 829 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUlZp_-__ELQEioQ1Q:-NFUlZp_-__ELQEioQ1R:bn3an5f) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L829)):*
> ```cpp
>   }
>   const MSKint32t s_index = num_mosek_vars;
>   // Put bound on s as s >= 0
> ```

typo, missing period at the end of the line



_Code quote:_
```cpp
// Put bound on s as s >= 0
```
___
*[`solvers/mosek_solver_internal.cc` line 849 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUpsb0-IBJ-hFpbxoM:-NFUpsb0-IBJ-hFpbxoN:bjdkxxu) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L849)):*
> ```cpp
>   L_bar.bottomRows(L.rows()) = L;
>   const Eigen::SparseMatrix<double> L_bar_sparse = L_bar.sparseView();
>   // one_zero_vec = [1;0;...;0]
> ```

nit, isn't the value supposed to be `[0;1;0;...;0]`?



_Code quote:_
```cpp
one_zero_vec = [1;0;...;0]
```
___
*[`solvers/test/mosek_solver_internal_test.cc` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUqGxB-sUStFeRR7O0:-NFUqGxB-sUStFeRR7O1:biejsik) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/test/mosek_solver_internal_test.cc#L18)):*
> ```cpp
>     MSKint64t, std::pair<std::vector<MSKint64t>, std::vector<MSKrealt>>>>;
> 
> // By default, the newly appended variables in Mosek are fixed to 0. I will need
> ```

FWIW, I think something like "Hence, they need to be explicitly made unbounded." could read better.



_Suggestion:_
```cpp
// I will need to explicitly set the variable bound to -inf and inf.
```
___
*[`solvers/test/mosek_solver_internal_test.cc` line 476 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUrQJK3ZipxC64BaOa:-NFUrQJK3ZipxC64BaOb:b-3bttxa) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/test/mosek_solver_internal_test.cc#L476)):*
> ```cpp
> }
> 
> GTEST_TEST(AddQuadraticCostAsLinearCost, Test) {
> ```

FYI, a description of the test's intention could help the reader.



_Code quote:_
```cpp
GTEST_TEST(AddQuadraticCostAsLinearCost, Test) {
```
___
*[`solvers/test/mosek_solver_internal_test.cc` line 506 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUrqilDRXlDhSH6CpU:-NFUrqilDRXlDhSH6CpV:b-l8pyow) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/test/mosek_solver_internal_test.cc#L506)):*
> ```cpp
>   EXPECT_EQ(domain_type, MSK_DOMAIN_RQUADRATIC_CONE);
> 
>   // check cost.
> ```

typo, please capitalize the first letter



_Code quote:_
```cpp
// check cost.
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`solvers/mosek_solver_internal.h` line 429 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUPU77DFx5NA8ly427:-NFW4Fqp-QE849MlbwN2:b-k9w4yb) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.h#L429)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

BTW, I think you use F and g due to Mosek notation, however, there are no such terms in the corresponding code. So, "A and b" may make more sense here. Or, consider adding a comment somewhere explaining the correspondence between A - F and b - g.
</blockquote></details>

Done. I removed mentioning `A, b, F, g` here and just say the coefficient of the affine expression.
___
*[`solvers/mosek_solver_internal.cc` line 806 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUhpHn1HZWhXNXE1G4:-NFW4uJrEqW0_T__EJJy:bgm9woh) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L806)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

nit, in this way, the introduction of s is explained twice (first in the sentence starting with "To do so" and then in the last sentence). I'd recommend removing the last sentence or making it more coherent.

(BTW, I guess the previous version was wrong in saying "we add new variables z", but nevertheless, might be helpful in describing how s was incorporated.)

At least, in the last sentence, "add new variables" should be changed to "add a new variable" since there is only one slack variable added. 
</blockquote></details>

Done. Good call. The last sentence should not appear here.
___
*[`solvers/mosek_solver_internal.cc` line 849 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUpsb0-IBJ-hFpbxoM:-NFW5jBY3XF_TSEEOtIY:bwn9b52) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/mosek_solver_internal.cc#L849)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

nit, isn't the value supposed to be `[0;1;0;...;0]`?
</blockquote></details>

Done. Good catch. I also changed the variable name to be more meaningful.
___
*[`solvers/test/mosek_solver_internal_test.cc` line 476 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFUrQJK3ZipxC64BaOa:-NFW8VKqDxhMwbWKrU4O:bxbc2zo) ([raw file](https://github.com/robotlocomotion/drake/blob/02eff00a140bac0ab3d164c69a5b27dc45179b84/solvers/test/mosek_solver_internal_test.cc#L476)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

FYI, a description of the test's intention could help the reader.
</blockquote></details>

Done.

BTW I normally use `GTEST_TEST(TestFunctionName, extra_info)` where the first argument `TestFunctionName` says which function is being tested.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some ignorable comments relating to my ignorance.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185#-:-NFiWQDSAItop--JAf4P:biisx65)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.h` line 434 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiT2FGEKLm2ipkPfKq:-NFiT2FGEKLm2ipkPfKr:b-blhksa) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.h#L434)):*
> ```objc
>       for (int k = 0; k < A.outerSize(); ++k) {
>         for (Eigen::SparseMatrix<double>::InnerIterator it(A, k); it; ++it) {
>           if (it.row() == 0) {
> ```

BTW The comment above about the factor of two was helpful. In my ignorance, however, it wasn't obvious to me why we only care about row 0.

On a related theme, we have b(0) *= 0.5 and the relationship between A, b, and the z_i documented above.

Is that something that someone who would actively maintain this code would be comfortable with? Or would further elaboration be beneficial?
___
*[`solvers/mosek_solver_internal.cc` line 570 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiUMLD624Bkx4MowT5:-NFiUMLD624Bkx4MowT6:b-ef0ggx) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.cc#L570)):*
> ```cpp
>     return rescode;
>   }
>   if (!bar_F.empty()) {
> ```

nit The semantics of this aren't completely clear to me. But...

Can you reverse the two loops? If you can move the inner loop to the outer loop, it seems you could skip the initial `if (!bar_F.empty())` test. The only thing I can imagine is that the order in which you call `MSK_putafebarfentry()` matters and requires iterating through j more quickly than i.

If that's the case, can you put a note to that effect? If it isn't the case, can we flip the loops to simplify the code?
___
*[`solvers/mosek_solver_internal.cc` line 611 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiV7BF0KO4zZzuEGCx:-NFiV7BF0KO4zZzuEGCy:beo8anj) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.cc#L611)):*
> ```cpp
>   // Add the actual affine cone constraint.
>   rescode = MSK_appendaccseq(task_, dom_idx, afe_dim, num_afe, nullptr);
>   if (rescode != MSK_RES_OK) {
> ```

BTW The next four lines of code can simply be `return rescode;`.

I assume the reason you haven't done this is to continue the explicit "I'm checking for an error" pattern, yes? It seems to be the standard in this file.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185)* status: 3 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[`solvers/mosek_solver_internal.h` line 434 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiT2FGEKLm2ipkPfKq:-NFioYdEECFLOEBl5k8C:b9c2t1i) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.h#L434)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The comment above about the factor of two was helpful. In my ignorance, however, it wasn't obvious to me why we only care about row 0.

On a related theme, we have b(0) *= 0.5 and the relationship between A, b, and the z_i documented above.

Is that something that someone who would actively maintain this code would be comfortable with? Or would further elaboration be beneficial?
</blockquote></details>

I modified the documentation. Is it more clear now?
___
*[`solvers/mosek_solver_internal.cc` line 570 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiUMLD624Bkx4MowT5:-NFipqz5-hDiC5vVgbgl:b53rhuu) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.cc#L570)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit The semantics of this aren't completely clear to me. But...

Can you reverse the two loops? If you can move the inner loop to the outer loop, it seems you could skip the initial `if (!bar_F.empty())` test. The only thing I can imagine is that the order in which you call `MSK_putafebarfentry()` matters and requires iterating through j more quickly than i.

If that's the case, can you put a note to that effect? If it isn't the case, can we flip the loops to simplify the code?
</blockquote></details>

I don't think I can skip the initial `if (!bar_F.empty())` test. 

I am trying to handle the part of affine expression that involves matrix variables `bar_X`, namely the linear expression `trace(bar_F, bar_X)`. bar_F is non-empty if and only if this affine expression involves this linear expression `trace(bar_F, bar_X)`. 

If I skip the test `if (!bar_F.empty())`, then in the inner for loop `for (const auto& [j, sub_weights] : bar_F[i])`, it would throw segmentation fault when it tries to call `bar_F[i]` whereas `bar_F` is empty.

I added some documentation, does it make this logic cleaner?
___
*[`solvers/mosek_solver_internal.cc` line 611 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiV7BF0KO4zZzuEGCx:-NFir7PG35TXYNWmXoGV:b-bnbm17) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.cc#L611)):*
> I assume the reason you haven't done this is to continue the explicit "I'm checking for an error" pattern, yes? It seems to be the standard in this file.

That is right. I think I would like to keep this pattern. Moreover, I want to make this code more maintainable. If the future maintainer adds some new mosek calls after the line `rescode = MSK_appendaccseq(...)`, he/she won't need to remember to add the check on `rescode != MSK_RES_OK`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(release notes: feature)  +(release notes: none) 

Note: You're modifying *internal* code, so that is not a feature change.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185#-:-NFjV8XW3rQudhGiCSqt:b-rg971d)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.cc` line 570 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiUMLD624Bkx4MowT5:-NFjUqx0Cq9XfGs7k0Ga:bdajmds) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.cc#L570)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think I can skip the initial `if (!bar_F.empty())` test. 

I am trying to handle the part of affine expression that involves matrix variables `bar_X`, namely the linear expression `trace(bar_F, bar_X)`. bar_F is non-empty if and only if this affine expression involves this linear expression `trace(bar_F, bar_X)`. 

If I skip the test `if (!bar_F.empty())`, then in the inner for loop `for (const auto& [j, sub_weights] : bar_F[i])`, it would throw segmentation fault when it tries to call `bar_F[i]` whereas `bar_F` is empty.

I added some documentation, does it make this logic cleaner?
</blockquote></details>

I realize now that I misread it. I made you waste your time. Sorry about that.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18185)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,SeanCurtis-TRI(platform)

___
*[`solvers/mosek_solver_internal.cc` line 570 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18185#-NFiUMLD624Bkx4MowT5:-NFjcyKw5Sq8Dt6pyZhf:b-8tn3dw) ([raw file](https://github.com/robotlocomotion/drake/blob/87196835306c698e797c0b8d1497aafc7b917467/solvers/mosek_solver_internal.cc#L570)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I realize now that I misread it. I made you waste your time. Sorry about that.
</blockquote></details>

No worries. If you misread the code, there is good possibility it would happen to the future maintainers, so I added the documentation.

**Pull request merged**
