### PR TITLE
[workspace] Upgrade petsc to latest release v3.17.3

### LINKED ISSUE #17495: Upgrade petsc to latest
Towards #17494.

As part of the monthly external upgrades (#17494), [petsc](https://github.com/petsc/petsc) needs to be upgraded to the latest commit. This may entail recreating `petscconf.h`. Also, the patches are a mess and may need manual fixing.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #17495.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17509)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
It looks like https://gitlab.com/petsc/petsc/-/merge_requests/5228/commits did not get into 3.17.3, and thus `baij.patch` needs to be retained (possibly updated to the version in the upstream MR).

**Review by xuchenhan-tri — COMMENTED** [review]
Ah thanks. I saw the PR was merged and assumed that it made the release. Reverted`baij.patch`.

+@jwnimmer-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17509#-:-N6KT1SO5BkgRVwmxsWe:bp97f7r)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17509#-:-N6KpYiY1NPwUrHjoG-k:bbboct3)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17509#-:-N6L-T22CkMs-On52E6G:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
