### PR TITLE
Update the kuka demo to use a piecewise polynomial 

### PR DESCRIPTION
**Pull request by sammy-tri**
This was a bit of a learning process for me and not necessarily the final best way to do it, but it's at least as good (I think better) as an example for dealing with IK output.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3050)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-:-KOGqW2y52AxjAD-c2PQ:-1973176957)*

**Comment by ggould-tri** [comment]
The `PPMatrix` stuff is incomprehensible, but that isn't really a defect of this code which in any event comments it about as well as could be expected.  Some comment and nomenclature notes below.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOGxcBBB5G8kUpCOw9A:-KOGxcBCi0mDDe1BM5pg:72812467) ([raw file](https://github.com/robotlocomotion/drake/blob/7fbd61fe03afdd9a0406cbb209963025d698aec2/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L54)):*
> ```cpp
>     typedef PPType::PolynomialType PPPoly;
>     typedef PPType::PolynomialMatrix PPMatrix;
>     std::vector<PPMatrix> polys;
> ```

yo dawg, I heard you like matrices...

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOKYF8pxXDQmiHIl7d8:-KOKYF8pxXDQmiHIl7d9:-798500863) ([raw file](https://github.com/robotlocomotion/drake/blob/7fbd61fe03afdd9a0406cbb209963025d698aec2/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L81)):*
> ```cpp
>     PPType pp_traj(polys, times);
> 
>     int64_t start_time = -1;
> ```

If these are in milliseconds (as I assume from the `1e3` below, please add that to their variable names.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOKYZP7DkkY8gWengko:-KOKYZP7DkkY8gWengkp:-804122987) ([raw file](https://github.com/robotlocomotion/drake/blob/7fbd61fe03afdd9a0406cbb209963025d698aec2/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L93)):*
> ```cpp
> 
>     while (cur_time < (start_time + end_time_offset)) {
>       int handled  = lcm_->handleTimeout(10);  // timeout is in msec -
> ```

"timeout" in this comment does not name a variable.  Is it meant to refer to `end_time_offset`?  If so, please refer to it by name.  If not please clarify whence the timeout here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-:-KOKYtkJW0YSDXVUoF3v:-379971163)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOKYF8pxXDQmiHIl7d8:-KOLQK9A4fhgqhDyfpSN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7fbd61fe03afdd9a0406cbb209963025d698aec2/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L81)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> If these are in milliseconds (as I assume from the `1e3` below, please add that to their variable names.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOKYZP7DkkY8gWengko:-KOLQXXei2y2ELINzDxI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7fbd61fe03afdd9a0406cbb209963025d698aec2/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L93)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> "timeout" in this comment does not name a variable.  Is it meant to refer to `end_time_offset`?  If so, please refer to it by name.  If not please clarify whence the timeout here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-:-KOLbDLknti-MfVt7MsH:1417088721)*

**Comment by sammy-tri** [comment]
hmm....   I'm today's platform reviewer, @ggould-tri is tomorrows...   so I guess we'll go to Monday: +@sherm1 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-:-KOLbnep4aeRLErakPfA:-1917133014)*

**Comment by sherm1** [comment]
OK, platform review pass done: one complaint and a few BTW comments.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOGxcBBB5G8kUpCOw9A:-KOMkUcjHi2oOgYamLRU:-823287491) ([raw file](https://github.com/robotlocomotion/drake/blob/7fbd61fe03afdd9a0406cbb209963025d698aec2/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L54)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> yo dawg, I heard you like matrices...
</details>
I thought he must like "P"s.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMp0Lx451cQbnx2PRK:-KOMojQ249sk_wJMxXUm:586893326) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L58)):*
> ```cpp
> 
>     // For each timestep, create a PolynomialMatrix for each joint
>     // position (joint positions correspond to rows in traj_).
> ```

BTW, this is a good comment but I was still confused. I suggest adding: `So each column of traj_ represents a particular time and contains a value for each joint coordinate at that time.` 

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMpxC8ZAVh5eFd5TUr:-KOMpxC8ZAVh5eFd5TUs:-368036922) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L63)):*
> ```cpp
>       const auto traj_now = traj_.col(i);
> 
>       for (int row = 0; row < traj_.rows(); row++) {
> ```

BTW, this would have helped me: `// Produce interpolating polynomials for each joint coordinate.`

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 71 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMnbQontEObxeZIhrC:-KOMnbQontEObxeZIhrD:200514618) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L71)):*
> ```cpp
>           // piece.  In the event that we're at the end of the
>           // trajectory, this will be left 0.
>           coeffs[1] = (traj_.col(i + 1)(row) - coeffs[0]) / (t_[i + 1] - t_[i]);
> ```

BTW, consider two-argument indexing `traj_(row, i+1)` -- clearer, I think.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 82 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMqrQPUUU2qGcV28WT:-KOMqrQPUUU2qGcV28WU:1257219748) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L82)):*
> ```cpp
> 
>     int64_t start_time_ms = -1;
>     int64_t cur_time_ms = -1;
> ```

This is too weird not to be explained in English. At first I thought these were just set to -1 to mean "not initialized yet" which would be typical. But then I saw ...

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 92 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMrFoxXQbwh5I2_eU-:-KOMrFoxXQbwh5I2_eU0:-90025535) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L92)):*
> ```cpp
>     iiwa_command.joint_torque.resize(kNumJoints, 0.);
> 
>     while (cur_time_ms < (start_time_ms + end_time_offset_ms)) {
> ```

... yikes! Both cur and start are -1 the first time through this loop!

You could fix this with a lot of comments on the lines of "although cur and start are -1 the first time through this loop, this will work fine because ...". But, I think you should look for a more straightforward way to express this in which start and cur are actually either (a) uninitialized and hence not used in computation, or (b) some time in ms.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 101 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMs6XSLzlTtYvfj7fr:-KOMs6XSLzlTtYvfj7fs:-551674754) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L101)):*
> ```cpp
>       }
> 
>       if (start_time_ms == -1) {
> ```

BTW, here the "-1" means uninitialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-:-KOMsXAEH683wJg1pvfY:955239385)*

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMp0Lx451cQbnx2PRK:-KOQxfZF8p3iBDLpRpEf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this is a good comment but I was still confused. I suggest adding: `So each column of traj_ represents a particular time and contains a value for each joint coordinate at that time.` 
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMpxC8ZAVh5eFd5TUr:-KOQxleX91IF4oF5gjn7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this would have helped me: `// Produce interpolating polynomials for each joint coordinate.`
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 71 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMnbQontEObxeZIhrC:-KOQxos7mood1EFXnLui:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, consider two-argument indexing `traj_(row, i+1)` -- clearer, I think.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 82 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMqrQPUUU2qGcV28WT:-KOQy87c6FnpdUkYQamg:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L82)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is too weird not to be explained in English. At first I thought these were just set to -1 to mean "not initialized yet" which would be typical. But then I saw ...
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 92 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMrFoxXQbwh5I2_eU-:-KOQy98Sd1_DcmmPF9-l:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> ... yikes! Both cur and start are -1 the first time through this loop!
> 
> You could fix this with a lot of comments on the lines of "although cur and start are -1 the first time through this loop, this will work fine because ...". But, I think you should look for a more straightforward way to express this in which start and cur are actually either (a) uninitialized and hence not used in computation, or (b) some time in ms.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 101 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMs6XSLzlTtYvfj7fr:-KOQyATjJKLk6iPjjUt_:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L101)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, here the "-1" means uninitialized.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050)*

**Comment by sherm1** [comment]
Platform: :lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 92 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-KOMrFoxXQbwh5I2_eU-:-KORJ7c3lBmeOuAxM9Ku:b-9typzd) ([raw file](https://github.com/robotlocomotion/drake/blob/9bb71f430aff58d3a38d20cfe126090cf5d0f230/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L92)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Done.
</details>
Beautiful -- very clear. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3050#-:-KORJLMcovbOxgfwXxwi:b-nxaeye)*

**Pull request merged**
