### PR TITLE
Improve new_release script

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify `new_release` to accept more than one external at a time, and to directly commit the changes, rather than prompting the user to do so. Update documentation to reflect the new usage.

+@jwnimmer-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/new_release.py` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18548#-NLLzRRU9YPP9qtz_hOy:-NLLzRRV1XKnm-RsWTCn:b-dhkp8r) ([raw file](https://github.com/robotlocomotion/drake/blob/d14c031b723908abc69c9a5202f84a9e54356bf5/tools/workspace/new_release.py#L38)):*
> ```Python
> import argparse
> import getpass
> import git
> ```

This import appears to require a new dependency that is not present in the `WORKSPACE`.

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel build //tools/workspace:new_release
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tools/workspace:new_release (46 packages loaded, 385 targets configured).
INFO: Found 1 target...
Target //tools/workspace:new_release up-to-date:
  bazel-bin/tools/workspace/new_release
INFO: Elapsed time: 4.149s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel-bin/tools/workspace/new_release
Traceback (most recent call last):
  File "/home/jwnimmer/jwnimmer-tri/drake/bazel-bin/tools/workspace/new_release.runfiles/drake/tools/workspace/new_release.py", line 38, in <module>
    import git
ModuleNotFoundError: No module named 'git'
```

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/new_release.py` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18548#-NLLzRRU9YPP9qtz_hOy:-NLM7Kx9AJVm57wSRJEu:b-ro2y6r) ([raw file](https://github.com/robotlocomotion/drake/blob/d14c031b723908abc69c9a5202f84a9e54356bf5/tools/workspace/new_release.py#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This import appears to require a new dependency that is not present in the `WORKSPACE`.

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel build //tools/workspace:new_release
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tools/workspace:new_release (46 packages loaded, 385 targets configured).
INFO: Found 1 target...
Target //tools/workspace:new_release up-to-date:
  bazel-bin/tools/workspace/new_release
INFO: Elapsed time: 4.149s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel-bin/tools/workspace/new_release
Traceback (most recent call last):
  File "/home/jwnimmer/jwnimmer-tri/drake/bazel-bin/tools/workspace/new_release.runfiles/drake/tools/workspace/new_release.py", line 38, in <module>
    import git
ModuleNotFoundError: No module named 'git'
```
</blockquote></details>

My machine already had it. Given this is a maintainer-only tool, I'm not convinced it makes sense to vendor that. I updated `packages-{focal,jammy}-maintainer-only.txt` instead.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri do you have the cycles to take over feature review?  I'm a bit overloaded.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548#-:-NLMV6KS-vskHoyRgOIG:b-xps770)* status: LGTM missing from assignees jwnimmer-tri(platform),rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`tools/workspace/new_release.py` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18548#-NLLzRRU9YPP9qtz_hOy:-NLMUdGH5_cbSpwfaXbE:bb73djm) ([raw file](https://github.com/robotlocomotion/drake/blob/d14c031b723908abc69c9a5202f84a9e54356bf5/tools/workspace/new_release.py#L38)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

My machine already had it. Given this is a maintainer-only tool, I'm not convinced it makes sense to vendor that. I updated `packages-{focal,jammy}-maintainer-only.txt` instead.
</blockquote></details>

SGTM

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

___
*[`tools/workspace/new_release.py` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18548#-NLLzRRU9YPP9qtz_hOy:-NLMeulqAc0XspdUqg_b:b5d5wdz) ([raw file](https://github.com/robotlocomotion/drake/blob/d14c031b723908abc69c9a5202f84a9e54356bf5/tools/workspace/new_release.py#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

Given that the whole point of bazel-building this script is to catch missing dependencies, shouldn't there be a change to the `deps` list in workspace/BUILD.bazel?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`tools/workspace/new_release.py` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18548#-NLLzRRU9YPP9qtz_hOy:-NLMfgwj12Cn7-pFpLEY:b-pv52zk) ([raw file](https://github.com/robotlocomotion/drake/blob/d14c031b723908abc69c9a5202f84a9e54356bf5/tools/workspace/new_release.py#L38)):*
> ... shouldn't there be a change to the deps list in workspace/BUILD.bazel?

The Python interpreter on Ubuntu hard-codes `/usr/lib/python3/dist-packages` onto the `sys.path`, so there's no need to adjust any input paths for importing to work.

I don't think we have anywhere in Drake that tries to detech at fetch-time if the user has not run install_prereqs.  We just let the ImportError pop out and that generally clues people in that they need to install the prereqs.

> ... the whole point of bazel-building this script is to catch missing dependencies ...

That's not the whole point of using Bazel for this.  We need to use `github3.py`, which is not available on Ubuntu, so we need Bazel to fetch it for us.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
Thanks for the reviews! I added one more small feature I thought of last night, and also tweaked the "main" report to stand out better.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548#-:-NLRFDaz3WYuPwyOa7BL:b-6irmjy)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`tools/workspace/new_release.py` line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18548#-NLNSn5s2xyYCUpm15Vs:-NLRF4202X_fQtPJuxkd:biistrq) ([raw file](https://github.com/robotlocomotion/drake/blob/a067257d491d947906edd8fc0d10613d8eca20f3/tools/workspace/new_release.py#L25)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This text about `--upgrade` is now stale.
</blockquote></details>

Good catch; thanks!

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review, by schedule.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18548#-:-NLRVnrr0Hl6S0acZHiH:bbev5z1)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18548)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`tools/workspace/new_release.py` line 212 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18548#-NLRk7PxDyF5G1z2Az2L:-NLS7O2O93Xj1vlwIxb7:bo4b41x) ([raw file](https://github.com/RobotLocomotion/drake/blob/06bb6e864ba4d0d5138db9ad641e5e04e01169bf/tools/workspace/new_release.py#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit These arguments "repo" and "other" are too obscure for a causal reader to grok.  Especially the word "repo" is heavily overloaded within this program.  (A github repository; the local Drake checkout; Bazel's name for an external.)  And the word "other" could mean anything.

At minimum, we need documentation about what this function does, and the types/meaning of its arguments.

On the other hand, folding it into it's sole call site is probably even more clear:

```py
def _is_modified(repo, path):
    """Returns true iff the given `path` is modified in the current
    Drake local git checkout given by `repo`.
    """
    for other in [None, 'HEAD']:
        if path in [item.b_path for item in repo.index.diff(other)]
            return True
    return False
```

(See also below about renaming `repo` throughout the file.)
</blockquote></details>

Done. Yeah, I don't love "other" either, but it's the name `Index.diff` uses. Suggestion seems reasonable, except I don't think it should mention *what* repository it's operating on.
___
*[`tools/workspace/new_release.py` line 216 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18548#-NLRkwtX27_Vjb3ewmXX:-NLSA3nP7qSqz-uce_nE:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/06bb6e864ba4d0d5138db9ad641e5e04e01169bf/tools/workspace/new_release.py#L216)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Function requires a docstring (see example above).
</blockquote></details>

Done.
___
*[`tools/workspace/new_release.py` line 386 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18548#-NLRl8RD7XpcuR91VyqA:-NLS8WRv9xlzNq4ykf6-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/06bb6e864ba4d0d5138db9ad641e5e04e01169bf/tools/workspace/new_release.py#L386)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The word "repo" is heavily overloaded within this program.

We should use a more descriptive name (throughout).
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18548)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
