### PR TITLE
workspace: Bump ccd to latest upstream commit

### LINKED ISSUE #10577: Drake fails when built against the newest libccd
The error, as shown in PR #10578:
```
[4:27:40 PM] ==================== Test output for //examples/manipulation_station:proof_of_life_test:
[4:27:40 PM] No HOME defined in the environment. Will not log.
[4:27:40 PM] terminate called after throwing an instance of 'std::logic_error'
[4:27:40 PM]   what():  Vector appears to be nearly zero.
[4:27:40 PM] ================================================================================
```

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #10577.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10578)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot retest this please

**Comment by SeanCurtis-TRI** [comment]
Notes to myself on diagnosing the problem.

## Reproducing the problem

The problem manifests in manipulation_station. Specifically, it occurs because of the penetration query on a box and a cylinder. Both the box and the cylinder have unfortunate aspect ratios (long and skinny). The following code reproduces the problem:

```c++
ProximityEngine<double> engine;
  GeometryId id_A = GeometryId::get_new_id();
  GeometryId id_B = GeometryId::get_new_id();
  GeometryIndex index_A(0);
  GeometryIndex index_B(1);
  ProximityIndex engine_index_A =
      engine.AddDynamicGeometry(Box(0.49, 0.63, 0.015), index_A);
  ProximityIndex engine_index_B =
      engine.AddDynamicGeometry(Cylinder(0.08, 0.002), index_B);
  ASSERT_EQ(engine_index_A, 0);
  ASSERT_EQ(engine_index_B, 1);
  std::vector<GeometryIndex> indices{index_A, index_B};
  Isometry3<double> X_WA;
  X_WA.matrix() << 0, -1, 0, -0.145,
                   1, 0, 0, -0.63,
                   0, 0, 1, 0.2425,
                   0, 0, 0, 1;
  Isometry3<double> X_WB;
  X_WB.matrix() << 1, 0, 0, 0,
                   0, 1, 0, -0.6,
                   0, 0, 1, 0.251,
                   0, 0, 0, 1;
  std::vector<Isometry3<double>> X_WG{X_WA, X_WB};
  engine.UpdateWorldPoses(X_WG, indices);
  std::vector<GeometryId> geometry_map{id_A, id_B};
  auto pairs = engine.ComputePointPairPenetration(geometry_map);
  EXPECT_EQ(pairs.size(), 1);
  EXPECT_NEAR(pairs[0].depth, 0, 1e-16);  // passes under old and new.
  // Under *old* libccd this test will fail, under the new libccd, it passes.
  EXPECT_EQ(pairs[0].nhat_BA_W.norm(), 0);
```

## Analysis

1. The geometry is simple enough that the true answer can be assessed. The cylinder is simply lying on the face of the box with a penetration depth of 0. There is no penetration, only osculation. (This is reasonably well reflected in the expected and reported depth values.
2. If there were a normal for the contact, it would be in the <0, 0, 1> direction. The normal reported under the old version of libccd was basically gibberish (in one run, I got the normal <-0.536, 0.84, 0.086>. This hasn't proven to be an obvious problem because the force in the normal direction is always scaled by the distance (so it vanishes to near zero).
3. FCL is reporting this as penetration but without a meaningful normal.

## Proposed resolution

1. FCL has a bug; if it's reporting penetration but can't provide consistent information for that penetration, it's wrong. In this case, it has decided that osculation = collision, but doesn't report the normal at contact. We need to take the example above and submit it as an FCL issue.
2. Fixing FCL will be time consuming. The query in question is used to generate contact forces in a compliant model. We can get away with defining penetration as a penetration depth greater than epsilon. This would allow us to cull the failure case exposed above and could be removed once FCL's results become more trustworthy.

**Comment by SeanCurtis-TRI** [comment]
See issue: https://github.com/flexible-collision-library/fcl/issues/375

**Comment by jwnimmer-tri** [comment]
Superseded by #10740.

**Pull request closed without merging**
