### PR TITLE
[geometry/optimization] Add Intersection Convex Set

### PR DESCRIPTION
**Pull request by mpetersen94**
Also adds the ability to generate an HPolyhedron from the intersection of 2 HPolyhedrons.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@RussTedrake for feature review or delegation.

**Review by RussTedrake — COMMENTED** [review]
+@russtedrake for feature review.
Very nice!  A few small issues below.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629#-:-MwI-wNA5VHBeJwAwJ1d:b-f1wb4d)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

___
*[geometry/optimization/intersection.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHuzd49-xflp82Jjx2:-MwHuzd49-xflp82Jjx3:b-2jwa7k) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.h#L14)):*
> ```objc
> 
> /** Implements a rotated second order cone convex set where \f$ z=Ax+b \f$ lies
> within rotated Lorentz cone.  Note: This set is unbounded.
> ```

Update this
___
*[geometry/optimization/intersection.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHw61E1y7XCtSJ-yqN:-MwHw61F7rGRv8An1Sa7:bipsz3f) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.h#L30)):*
> ```objc
> 
>   /** The number of factors (or sets) used in the intersection. */
>   int num_factors() const { return sets_.size(); }
> ```

i don't think factors is the right word here? i think we avoided `sets` in an earlier parallel discussion, but perhaps `elements`?  or `operands`?
___
*[geometry/optimization/intersection.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHxYD7ANJF1SIsbjR0:-MwHxYD7ANJF1SIsbjR1:b-zapzxa) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.cc#L43)):*
> ```cpp
> 
> // TODO(mpetersen94): Cover case where sets are unbounded but intersection is
> // bounded.
> ```

how hard is it to do this?  i don't want to block the PR, but i also worry that this is not will silently give the wrong answer for some cases until implemented.

depending on if you need this yet, it honestly might be better to throw with an unsupported message instead of returning false?  perhaps just logging a warning would be sufficient.

cc @hongkai-dai @frankpermenter @tobiamarcucci in case they know a simple spelling of this (e.g. a Farkas' lemma style certificate for checking boundedness for an intersection of (general) convex sets).

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @frankpermenter, @hongkai-dai, and @mpetersen94)

___
*[geometry/optimization/intersection.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHxYD7ANJF1SIsbjR0:-MwIsjL25wpziLMM7ayv:b-s9j3dq) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.cc#L43)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

how hard is it to do this?  i don't want to block the PR, but i also worry that this is not will silently give the wrong answer for some cases until implemented.

depending on if you need this yet, it honestly might be better to throw with an unsupported message instead of returning false?  perhaps just logging a warning would be sufficient.

cc @hongkai-dai @frankpermenter @tobiamarcucci in case they know a simple spelling of this (e.g. a Farkas' lemma style certificate for checking boundedness for an intersection of (general) convex sets).
</blockquote></details>

I'm thinking about it. I might have something.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @frankpermenter, @hongkai-dai, and @RussTedrake)

___
*[geometry/optimization/intersection.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHuzd49-xflp82Jjx2:-MwJi0Yx4g_-F_--wt1v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.h#L14)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Update this
</blockquote></details>

Done.
___
*[geometry/optimization/intersection.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHw61E1y7XCtSJ-yqN:-MwJiWE-1OUYLJdA4rp-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.h#L30)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't think factors is the right word here? i think we avoided `sets` in an earlier parallel discussion, but perhaps `elements`?  or `operands`?
</blockquote></details>

Done.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @frankpermenter, @hongkai-dai, and @RussTedrake)

___
*[geometry/optimization/intersection.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHxYD7ANJF1SIsbjR0:-MwXp8ZA5CBUVcA3q_8L:b-23z57d) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.cc#L43)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

I'm thinking about it. I might have something.
</blockquote></details>

Could I set up an optimization that maximizes the distance between two points in the intersection and if the problem has a solution it is bounded?  Or will that be too inefficient?

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @frankpermenter and @hongkai-dai)

___
*[geometry/optimization/intersection.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHxYD7ANJF1SIsbjR0:-MwXqYhGANfyZ5l3Uaj3:bx74k28) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.cc#L43)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Could I set up an optimization that maximizes the distance between two points in the intersection and if the problem has a solution it is bounded?  Or will that be too inefficient?
</blockquote></details>

maximizing the distance will be non-convex, no?
I don't think we need to hold up this PR for it.  Assuming you don't need it for your workflow, I think it's ok for now to return true when we are sure it's true and throw an exception with a descriptive message when we aren't sure.  We can fill in an implementation later if it becomes important.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @frankpermenter, @hongkai-dai, and @RussTedrake)

___
*[geometry/optimization/intersection.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16629#-MwHxYD7ANJF1SIsbjR0:-MwY34-q-Aodqr51fSsK:b-q2p15) ([raw file](https://github.com/robotlocomotion/drake/blob/8935715ce4609513dff8bd6e4120583184f82b51/geometry/optimization/intersection.cc#L43)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

maximizing the distance will be non-convex, no?
I don't think we need to hold up this PR for it.  Assuming you don't need it for your workflow, I think it's ok for now to return true when we are sure it's true and throw an exception with a descriptive message when we aren't sure.  We can fill in an implementation later if it becomes important.
</blockquote></details>

Done. I think you might be right.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@rpoyner-tri for platform review, please.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629#-:-MwYCJyiDoxxjnyeronf:b-5mhjlt)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 1 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16629#-:-MwYUh5Z2FIm4F-EhPhI:bnfp4nl)* status: missing label for release notes (waiting on @mpetersen94)

**Comment by TobiaMarcucci** [comment]
@RussTedrake @mpetersen94 I think the efficient way to check if a general convex set is bounded is the following (I can open an issue if it is more appropriate):
- The set `S = {x: g_i(x) >= 0 for all i}` is the convex set under analysis
- The recession cone is `S_inf = {x: g_i_inf(x) >= 0 for all i}`, where `g_i_inf(x)` is the recession function of `g_i`, which is equal to the perspective function evaluated for the scaling coefficient equal to zero `tilde g_i(x, 0)`
- `S` is bounded iff `S_inf` contains a point different from the origin
- First we need to ensure that if `x != 0` then `g_i_inf(x) > 0` (this should be easy, I need to pin down the math still)
- We then check if `S_inf` contains a point different from the origin by checking if the convex following program has positive objective: `max sum y_k s.t. g_i_inf(x) >= y for all i, y >= 0`
- Note: this is essentially the dual of the check we currently do to see if a polyhedron is bounded

**Comment by RussTedrake** [comment]
@TobiaMarcucci -- great!  Please do open an issue so we don't lose track.

**Pull request merged**
