### PR TITLE
Remove unused tools/{blacklist.txt,valgrind-cmake.supp}

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
I think these files were used by the CMake build at one point, but are now unused.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7152)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7152#-:-KvS3S191pqRwY-v9fBr:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per rotation, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7152#-:-KvTCTkooujBmyvE4eEN:bnfp4nl)*

**Pull request merged**
