### PR TITLE
Add state_derivative_output_port to RigidBodyPlant

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove RigidBodyPlantThatPublishesXdot and AccelerometerXdotHack.
This is a prerequisite of fixing the LCM threading model.

(See #4682 for where this all got introduced.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8414)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@edrumwri for feature review

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-:-L85SnVLG36KdhoIpU4s:b-p4pzus)*

**Comment by edrumwri** [comment]
This is missing an inherent means to provide the same functionality for the time stepping version of the plant. How do you think that could be provided?

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/rigid_body_plant/rigid_body_plant.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-L85V9dpIa1AGcirRGgf:-L85V9dpIa1AGcirRGgg:bl4bvyl) ([raw file](https://github.com/robotlocomotion/drake/blob/e6a51abd74a249b8536ffe872f155276652fb4bd/multibody/rigid_body_plant/rigid_body_plant.cc#L73)):*
> ```cpp
>                                     &RigidBodyPlant::CopyStateToOutput)
>           .get_index();
>   if (timestep_ == 0.0) {
> ```

BTW Suggest: `is_state_discrete()` instead. 

---

*[multibody/rigid_body_plant/rigid_body_plant.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-L85Uc7NvRVhsYNQdHrv:-L85Uc7OFXM52GE2dlII:bkny3nq) ([raw file](https://github.com/robotlocomotion/drake/blob/e6a51abd74a249b8536ffe872f155276652fb4bd/multibody/rigid_body_plant/rigid_body_plant.h#L61)):*
> ```objc
> ///
> /// - state_derivative_output_port(): A vector-valued port containing the time
> ///   derivative `xcdot` of the state vector.
> ```

You might want to point out the ordering of the vector- time derivatives of generalized positions first then velocities, with coordinate indices dictated by RigidBodyTree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-:-L85V7OfBj7_hnUxqIFs:bln4wew)*

**Comment by jwnimmer-tri** [comment]
I hadn't tried to figure that out yet -- assuming that someone else could do so if / when they needed it in a future PR (hopefully using MBP!).  Having vdot only available for continuous-time plants seemed like a big enough win to do on its own here.

(My best guess for discrete time is that we'd output the DoCalcDiscreteVariableUpdates result divided by the timestep to yield an instantaneous approximation, perhaps?  I would defer to dynamics team judgement, in any case.)

---

Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/rigid_body_plant/rigid_body_plant.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-L85V9dpIa1AGcirRGgf:-L85_3b5-EqgStMZqAtg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e6a51abd74a249b8536ffe872f155276652fb4bd/multibody/rigid_body_plant/rigid_body_plant.cc#L73)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Suggest: `is_state_discrete()` instead. 
</blockquote></details>

Done.

---

*[multibody/rigid_body_plant/rigid_body_plant.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-L85Uc7NvRVhsYNQdHrv:-L85ZzOwCfmXfVqgnL8q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e6a51abd74a249b8536ffe872f155276652fb4bd/multibody/rigid_body_plant/rigid_body_plant.h#L61)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You might want to point out the ordering of the vector- time derivatives of generalized positions first then velocities, with coordinate indices dictated by RigidBodyTree.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-:-L85_7lwz0Xv-hA2pvk7:b-hk7cvz)*

**Comment by edrumwri** [comment]
Ok, so here's a common case for us as we're debugging robotics applications with the manipulation team (Rick): we want to test the entire Anzu setup using both the discrete time (time stepping) and continuous time rigid body plants. At the moment, that requires only flipping a little switch- setting `dt` to a positive value on RigidBodyPlant construction. This PR would make creating a diagram with such a flexible RigidBodyPlant and a consumer for your new output port cumbersome. 

Sending the state output from the plant to a `Derivatives` (numerical differencing block) would definitely work, though I imagine we're going to want to chew this one over. We need to discuss how to make the process most transparent to the user and keep the computation fast. Depending on the accelerometer update frequency, the computation in the context of the time stepping method could increase significantly, whereas I expect the continuous time approach to accrue no overhead whatsoever.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-:-L85r_ZwLNp-cwOadKiB:b-f6qega)*

**Comment by jwnimmer-tri** [comment]
This PR takes the RigidBodyPlantThatPublishesXdot functionality, which is continuous-time-only right now anyway, and rolls it into RigidBodyPlant directly, removing the need for an extra class, and removing the use of an LCM hack as a kind of Diagram wiring to avoid a computational loop.  Its not scoped to add new discrete-time capability, but rather just changing the wiring mechanism.

I understand that _if_ someone were going to use this port, and _if_ they were doing the "flip between continuous time vs discrete time", they would not be able to do so yet.  I am unconvinced that I should spend time addressing that now.  Maybe there is I way that I could add more disclaimers or TODOs here, so that users would not be accidentally surprised that it wasn't working?

That being said, I am willing to defer to dynamics team as an area owner for RBP.  If you don't feel like RBP should offer this port when it only works for continuous time, then I will revert that change and instead refactor this PR to delete the Accelerometer system instead.  (That was my original plan, before I thought up this current approach.)

One way or the other, RigidBodyPlantThatPublishesXdot is going to die today, without too much more work on my part.  I'd prefer to do it by rolling it to RBP, but I am also OK to delete Accelerometer if that seems better.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8414#-:-L87VORysAAAjSqFkQV_:b2ek7b)*

**Comment by edrumwri** [comment]
Ok, please put a TODO in the new output port function for adding an approximation from time stepping. I can then output the approximate acceleration. Then, :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8414#-:-L88ORiGBgnYeqXHlt4m:b-rrnesr)*

**Comment by jwnimmer-tri** [comment]
Done.

+@ggould-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8414#-:-L88R_qTCyTnieIVbMgO:bik77ca)*

**Comment by ggould-tri** [comment]
Looks like a strict improvement to me. :lgtm:.

---

Reviewed 14 of 16 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8414#-:-L88nkuHDtZhfS2AH2UL:bw5qrjx)*

**Pull request merged**
