### PR TITLE
Install bot2-lcmgl

### PR DESCRIPTION
**Pull request by jamiesnape**
Apparently Director needs this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6383)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review. High priority. FYI @fbudin69500.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/libbot.BUILD, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0YVZ37rgJ4kj2xrzb:-Kn0YVZ8_Fp8Cw8AQO2N:b-2z7lk1) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L150)):*
> ```
> 
> py_binary(
>     name = "bot-log2mat",
> ```

BTW, why does this need to be split into a `py_library` *and* a `py_binary`?

---

*[tools/libbot.BUILD, line 349 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0YgMaT_d1jYDzjMe7:-Kn0YgMkGiLUHmUBlsQd:b7yru6a) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L349)):*
> ```
> )
> 
> # bot2-lcmgl
> ```

BTW, given how many sections there are (and how huge this file is), maybe `BEGIN`/`END` markers and rules would help readers find their place?

---

*[tools/libbot.BUILD, line 420 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0Z7QWwalQ0-v27iUU:-Kn0Z7QWwalQ0-v27iUV:btzqit1) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L420)):*
> ```
>     name = "bot2_lcmgl_render",
>     srcs = [
>         "bot2-lcmgl/src/bot_lcmgl_client/lcmgl.h",
> ```

BTW, should this be in `hdrs`?

---

*[tools/libbot.BUILD, line 527 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0ZNuzVGf95AnEZ_rW:-Kn0ZNuzVGf95AnEZ_rX:b-w0ct5e) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L527)):*
> ```
> install(
>     name = "install_bot2_param",
>     hdrs = BOT2_PARAM_PUBLIC_HDRS,
> ```

BTW, did buildifier do this? Seems like the previous order was better... if this is buildifier's fault, we should add a custom tables (see bazelbuild/buildtools#45); not necessarily now, but at some point...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-:-Kn0_llnjwLu0gxCbU35:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/libbot.BUILD, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0YVZ37rgJ4kj2xrzb:-Kn0baqlhpvHUQVJZ2eU:b-3xdra4) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L150)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, why does this need to be split into a `py_library` *and* a `py_binary`?
</blockquote></details>

BTW This is a Bazel approximation of how upstream uses shell scripts.

---

*[tools/libbot.BUILD, line 420 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0Z7QWwalQ0-v27iUU:-Kn0bzWn6U20_HF9klm9:b-aecrq1) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L420)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, should this be in `hdrs`?
</blockquote></details>

BTW No see bot2_lcmgl_client above. Libbot does some ugly things, so it cannot be picked up by specifying a dep.

---

*[tools/libbot.BUILD, line 527 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0ZNuzVGf95AnEZ_rW:-Kn0cOR5AJbyOXmEiISe:b-z85juk) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L527)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, did buildifier do this? Seems like the previous order was better... if this is buildifier's fault, we should add a custom tables (see bazelbuild/buildtools#45); not necessarily now, but at some point...
</blockquote></details>

BTW It did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 420 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0Z7QWwalQ0-v27iUU:-Kn0dH4n1hE6LZE-ODHh:b-7buuk2) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L420)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW No see bot2_lcmgl_client above. Libbot does some ugly things, so it cannot be picked up by specifying a dep.
</blockquote></details>

BTW I'm confused; since `bot2_lcmgl_client` is *already* a dep, won't any users of `bot2_lcmgl_render` pick up this header anyway? (Or is this another "Bazel is horrible" thing?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 420 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0Z7QWwalQ0-v27iUU:-Kn0e_5X6Ax3aoSbN1AV:b-xygc7m) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L420)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW I'm confused; since `bot2_lcmgl_client` is *already* a dep, won't any users of `bot2_lcmgl_render` pick up this header anyway? (Or is this another "Bazel is horrible" thing?)
</blockquote></details>

Libbot thing: `#include "../bot_lcmgl_client/lcmgl.h"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 420 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0Z7QWwalQ0-v27iUU:-Kn0ibrGm1BtFa6cZJpS:bgh1ivl) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L420)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Maybe I am unclear; I wasn't suggesting to rely on picking it up via a dep, I was asking what is wrong with it being three lines lower, in `hdrs` of `bot2_lcmgl_render` instead of `srcs` of the same. "It's private" doesn't seem to be a reason?
</blockquote></details>

To this package it is effectively private. Depends on your philosophy and whether you think the same header should be public for two different packages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/libbot.BUILD, line 420 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0Z7QWwalQ0-v27iUU:-Kn0npEOg2RwaZi5alS8:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L420)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

To this package it is effectively private. Depends on your philosophy and whether you think the same header should be public for two different packages.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Comment by jwnimmer-tri** [comment]
I guess once we've decided that Director needs to use Drake's build of libbot, then this is a necessary outcome.  I'm not 100% why we're doing that, but I'll assume there's a good reason and just do a correctness review, rather dig into the appropriateness.

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0yv1tmgkNVnUPVDYM:-Kn0yv1tmgkNVnUPVDYN:b-9vu7vk) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L401)):*
> ```
>     "bot2-lcmgl/src/bot_lcmgl_client/lcmgl.h",
>     "bot2-lcmgl/src/bot_lcmgl_render/lcmgl_decode.h",
> ]
> ```

BTW Do we need this variable?  It seems to duplicate the `hdrs` of the two `cc_library` targets in question, so it seems like `guess_hdrs` could do the job?  Of if `guess...` is undesirable, perhaps the `cc_library` rules should refer to (a twain'd version of) this variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-:-Kn0xPBM7SLS8BBCSn-u:b-3fh8gv)*

**Comment by jwnimmer-tri** [comment]
*[tools/libbot.BUILD, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0yv1tmgkNVnUPVDYM:-Kn1-J_aiVj3U09NlBke:b-1anjrz) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L401)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do we need this variable?  It seems to duplicate the `hdrs` of the two `cc_library` targets in question, so it seems like `guess_hdrs` could do the job?  Of if `guess...` is undesirable, perhaps the `cc_library` rules should refer to (a twain'd version of) this variable?
</blockquote></details>

(Oops.  The `Of if` ... should read `Or if` ...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6383#-Kn0yv1tmgkNVnUPVDYM:-Kn11Sui0Z7dBEzDtwJc:b-jeza9w) ([raw file](https://github.com/robotlocomotion/drake/blob/2af8acf9191b1c2d44a9f1886b6053e4e018060e/tools/libbot.BUILD#L401)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(Oops.  The `Of if` ... should read `Or if` ...)
</blockquote></details>

The LCM types cause the issue. You end up with them being installed twice into two different locations if you use `PACKAGE`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6383)*

**Pull request merged**
