### PR TITLE
[solvers] Support L2NormCost in SnoptSolver and IpoptSolver.

### PR DESCRIPTION
**Pull request by RussTedrake**
+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`solvers/test/optimization_examples.cc` line 840 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18184#-NFHNN180W4T3Vx7hRlW:-NFHNN180W4T3Vx7hRlX:b-ekmukw) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1d67b7e0dd09efbb08559fcfa090e5bdd430d6/solvers/test/optimization_examples.cc#L840)):*
> ```cpp
>   auto x = prog.NewContinuousVariables(1, "x");
> 
>   prog.AddL2NormCost(Vector1d{1}, Vector1d{0}, x);
> ```

Here `x` is just a scalar, hence the L2 norm is just the absolute value |x|, which is the same as `x`'s l1, l2, ..., l_infinity norm. Maybe consider to use a vector of `x` where the lp norms are different for each `p`?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/optimization_examples.cc` line 840 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18184#-NFHNN180W4T3Vx7hRlW:-NFJBM6z9xyNhx9SajXt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1d67b7e0dd09efbb08559fcfa090e5bdd430d6/solvers/test/optimization_examples.cc#L840)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Here `x` is just a scalar, hence the L2 norm is just the absolute value |x|, which is the same as `x`'s l1, l2, ..., l_infinity norm. Maybe consider to use a vector of `x` where the lp norms are different for each `p`?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sherm1 for platform review please, thanks!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184#-:-NFK-CYA5EXjbVUYXyQF:b-z000um)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one nit

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184#-:-NFK8vaj7aw_blUGk__G:b-8gq7ov)* status: 1 unresolved discussion, missing label for release notes (waiting on @RussTedrake)

___
*[`solvers/snopt_solver.cc` line 469 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18184#-NFK78mw3Ekek7mJo1qH:-NFK78mw3Ekek7mJo1qI:bkjr8wv) ([raw file](https://github.com/robotlocomotion/drake/blob/cc94d94fd107028a6d09157fa9924655137ccafe/solvers/snopt_solver.cc#L469)):*
> ```cpp
> std::set<int> GetAllNonlinearCostNonzeroGradientIndices(
>     const MathematicalProgram& prog) {
>   // The nonlinear costs include the quadratic and generic costs. Linear costs
> ```

nit: "quadratic, L2, and generic costs" ? (Comment above says L2 is not quadratic since we don't square it.)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184)* status: missing label for release notes (waiting on @hongkai-dai and @sherm1)

___
*[`solvers/snopt_solver.cc` line 469 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18184#-NFK78mw3Ekek7mJo1qH:-NFKLKnG33_f81GkzAC_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc94d94fd107028a6d09157fa9924655137ccafe/solvers/snopt_solver.cc#L469)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "quadratic, L2, and generic costs" ? (Comment above says L2 is not quadratic since we don't square it.)
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18184)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
