### PR TITLE
Remove terms with small coefficients in a symbolic polynomial

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091#-:-LGWLDrhAFXQcEELWRB1:bpno49v)*

**Comment by soonho-tri** [comment]
:lgtm:

+@sammy-tri for platform-review, please.

---

Reviewed 3 of 3 files at r1.
Review status: 1 unresolved discussion, platform LGTM from [soonho-tri]

---

*[common/symbolic_polynomial.cc, line 610 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9091#-LGWMEP94IBELVjflaSK:-LGWMEP94IBELVjflaSL:bism73m) ([raw file](https://github.com/robotlocomotion/drake/blob/865964eec8d6f72372bbfa8b9c199bee1861eaf2/common/symbolic_polynomial.cc#L610)):*
> ```cpp
> 
> Polynomial Polynomial::RemoveTermsWithSmallCoefficients(
>     double coefficient_tol) const {
> ```

nit, Add `DRAKE_ASSERT/DEMAND(coefficient_tol > 0)`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091#-:-LGWMKJnBISLfOfFvBrZ:bsflq0i)*

**Comment by soonho-tri** [comment]
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [soonho-tri]

---

*[common/symbolic_polynomial.cc, line 610 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9091#-LGWMEP94IBELVjflaSK:-LGWMUKdBSRX8vYED3Tj:b-elbi8z) ([raw file](https://github.com/robotlocomotion/drake/blob/865964eec8d6f72372bbfa8b9c199bee1861eaf2/common/symbolic_polynomial.cc#L610)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, Add `DRAKE_ASSERT/DEMAND(coefficient_tol > 0)`?
</blockquote></details>

Done :-)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091)*

**Comment by soonho-tri** [comment]
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [soonho-tri]

---

*[common/symbolic_polynomial.cc, line 616 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9091#-LGWNCP37yr_nE-NAO2y:-LGWNCP37yr_nE-NAO2z:bs5kfw9) ([raw file](https://github.com/robotlocomotion/drake/blob/7e7bed8b6e75a0b3f215b123b0ae1988946eb1e0/common/symbolic_polynomial.cc#L616)):*
> ```cpp
>   for (const auto& term : monomial_to_coefficient_map_) {
>     if (is_constant(term.second) &&
>         std::abs(to_constant(term.second)->get_value()) <= coefficient_tol) {
> ```

BTW, the following is slightly better I think:

```c++
std::abs(get_constant_value(term.second)) <= coefficient_tol)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091)*

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri, sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091#-:-LGWQo8b68hAvAq31Inr:b-pu9q93)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all discussions resolved, platform LGTM from [soonho-tri, sammy-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9091#-:-LGWfIJc8oxJNy-_VGFi:b-l70wzf)*

**Pull request merged**
