### PR TITLE
fix eigen include when eigen3.pc not found

### PR DESCRIPTION
**Pull request by rdeits**
FindEigen3.cmake sets `EIGEN3_FOUND`, not `Eigen3_FOUND`, and we were previously including the folder "EIGEN3_INCLUDE_DIR" rather than the contents of that variable.

### CODE REVIEW

**Comment by rdeits** [comment]
We could also just get rid of all this code, since it was clearly never being run by anyone. I only noticed that it was broken when I tried to copy it into another project that wasn't using pkg-config to find eigen.

**Comment by RussTedrake** [comment]
then you’re a user.  :)

**Comment by RussTedrake** [comment]
the question is — are we ok forcing people to a local install of eigen even if they have it already installed on their system?  i was hoping to avoid it, but right now it’s got a special place as our only required prereq… maybe it’s ok?

**Comment by rdeits** [comment]
Are we actually forcing people to do a local install? If the user sets WITH_EIGEN to OFF, then this logic should pick up their systemwide version and use it.

**Pull request merged**
