### PR TITLE
 Update drake-visualizer and add LCMGL support

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9172)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Mac failure is a problem in master.

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review and local testing on Linux and +@soonho-tri  for feature review and local testing on Mac.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Not sure why this got closed. Maybe I cleaned up the wrong branch...

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
(Rebased on master)

@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
Confirmed that I can still see the dropdown menu and import `bot_lcmgl` in Drake Visualizer's terminal.

**Pull request merged**
