### PR TITLE
Adds Support for Loading URDF Multiple Times

### LINKED ISSUE #2583: Add Support for Loading Same URDF Multiple Times Into Same Rigid Body System
This is the URDF counterpart to https://github.com/RobotLocomotion/drake/pull/2426.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #2583.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2859)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR is the URDF analog to #2426. Since that PR was feature reviewed by @amcastro-tri, +@amcastro-tri for feature review please. Thanks!

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-:-KN834DMogMWO-7Dujrf:-1266690155)*

**Comment by amcastro-tri** [comment]
This is a very first pass. I need to study the `demo_multi_car.cc` to understand how these model id's get used. It really doesn't help that there is so much refactoring intermixed because it is difficult to see the new usages of model id's. 
Also I thought we were against model id's but this PR promotes them and even adds model id's to force elements and exposes them to public API's.

---

Reviewed 2 of 18 files at r1.
Review status: 2 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN90bWLFFzJ7a-0x3Ju:-KN90bWLFFzJ7a-0x3Jv:-964794343) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBody.cpp#L17)):*
> ```cpp
> using std::vector;
> 
> // RigidBody::RigidBody()
> ```

Dead comment block.

---

*[drake/systems/plants/RigidBody.h, line 36 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN90nk2izeQNl-9R0Uw:-KN90nk2izeQNl-9R0Ux:646131248) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBody.h#L36)):*
> ```objc
>    * @param[in] name The name of the rigid body.
>    */
>   explicit RigidBody(const std::string& model_name, int model_id,
> ```

I don't think this should be part of RigidBody's public API.

---

*[drake/systems/plants/RigidBody.h, line 74 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN918jlb_J_4IhWAWS8:-KN918jlb_J_4IhWAWS9:666949734) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBody.h#L74)):*
> ```objc
>    * Sets the ID of the model to which this rigid body belongs.
>    */
>   // void set_model_id(int model_id);
> ```

Dead comment here.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 334 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN92eKlNhXDd7V_ntt5:-KN92eKlNhXDd7V_ntt6:673031851) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBodySystem.cpp#L334)):*
> ```cpp
> }
> 
> RigidBodyPropellor::RigidBodyPropellor(RigidBodySystem& sys, XMLElement* node,
> ```

I thought we were unhappy with RigidBody's having this model_id member and even unhappier exposing it to the public API. So why is that you are deciding to mimic this for ForceElement's. What happened to the idea of a `Model`?

---

*[drake/systems/plants/RigidBodySystem.h, line 327 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN933FNd8-vrB4crvGO:-KN933FNd8-vrB4crvGP:-2091643673) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBodySystem.h#L327)):*
> ```objc
>    * belongs.
>    */
>   RigidBodyForceElement(RigidBodySystem& sys, const std::string& name,
> ```

See comment above. Why to expose model_id to the user? is this what we want in the long term?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN93MsyN_WCpWvY_cr6:-KN93MsyN_WCpWvY_cr7:1763342546) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBodyTree.cpp#L46)):*
> ```cpp
> const char* const RigidBodyTree::kWorldBodyName = "world";
> const char* const RigidBodyTree::kWorldModelName = "world";
> ```

This is confusing. Now there is also a kWorldModelName? and we put it in RigidBodyTree.cpp?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-:-KN94A8YLDMg7o-6dhmK:-251375144)*

**Comment by liangfok** [comment]
Sorry, perhaps I should have provided more context.

Yes, the long term goal is to reduce, and eventually eliminate, the `model_id`. However, as you know, we must get there incrementally. This PR is an incremental step towards the long-term vision. Here is why:

The long-term vision is to introduce a new class called `Model` that encapsulates all modeling elements belonging to a particular model (e.g., `RigidBody`, `DrakeJoint`, `ForceElement`, `Sensor`, `LoopJoint`, etc., objects). The `Model` object serves two purposes. The first is to transfer the model's elements to the `RigidBodySystem`, as shown below.



A second objective is to allow users to differentiate which modeling elements in the `RigidBodySystem` belong to which model (i.e., the current purpose of `model_id`). This is possible since users can maintain the `Model` objects even after their modeling elements are added to the `RigidBodySystem`. Each `Model` object effectively points to the modeling elements within the `RigidBodySystem` that belong to a particular model.

To incrementally achieve the above vision, one must first unify the URDF, SDF, and other parsers so they can all output the same `Model` abstraction. This PR takes a step in this direction by making the URDF parser identical to the SDF parser in terms of their outputs. Note that the SDF parser already uses the model_id to support multiple models (see [here](https://github.com/RobotLocomotion/drake/blob/feba81d06699d61afa72ec41b499ba6148ce7fd4/drake/systems/plants/parser_sdf.cc#L651) and [here](https://github.com/RobotLocomotion/drake/blob/feba81d06699d61afa72ec41b499ba6148ce7fd4/drake/systems/plants/RigidBodySystem.cpp#L829)). This is necessary since currently (and through the mid term -- see paragraph below) the only way to differentiate multiple identical models in a `RigidBodySystem` is through the `model_id`. This PR makes the URDF parser match the SDF parser so they can both be modified to make use of the `Model` abstraction discussed above.

Once the `Model` abstraction is added, it will be possible to incrementally reduce reliance on the `model_id`, and the existence of the `model_id` can be better hidden by automatically assigning it when a `Model` is added to the `RigidBodySystem`, as opposed to now where the `ModelID` is set while the URDF / SDF is being parsed. However, I suspect it will take a long time to _eliminate_ the `model_id` from the API due to (1) the number of methods inside `RigidBodySystem` and `RigidBodyTree` that require the model ID, (2) the large amount of software outside of `RigidBodySystem` that use these methods,  and (3) the need to support downstream dependencies. In other words, I believe we should plan on keeping the `model_id` for the mid term, and provide an alternate API through the `Model` class that allows applications to optionally _not_ rely on the `model_id`when simulating / controlling multiple models simulaneously. Once we have this in place, we will be in a good position to monitor usages of the `model_id` and determine whether it can / should be eliminated.

In summary, once this PR is merged, we will be in a much better position to introduce the above-mentioned `Model` abstraction. 

---

Review status: 2 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN90bWLFFzJ7a-0x3Ju:-KNAJB89VyR2QddmNVvE:1740281843) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBody.cpp#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Dead comment block.
</details>
Removed.

---

*[drake/systems/plants/RigidBody.h, line 36 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN90nk2izeQNl-9R0Uw:-KNAJDvO81Lxpn8TgqWb:1121316881) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBody.h#L36)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I don't think this should be part of RigidBody's public API.
</details>
I could remove the `model_name` and `model_id` from the constructor and instead provide setter / getter methods. The tradeoff is then the member variables that hold the model name and model ID cannot be `const`. Would you prefer that?

---

*[drake/systems/plants/RigidBody.h, line 74 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN918jlb_J_4IhWAWS8:-KNAJggx8nlPqP4muVoj:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBody.h#L74)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Dead comment here.
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 334 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN92eKlNhXDd7V_ntt5:-KN9Sr_G41zbTA0Br-0Y:-1918514046) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBodySystem.cpp#L334)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I thought we were unhappy with RigidBody's having this model_id member and even unhappier exposing it to the public API. So why is that you are deciding to mimic this for ForceElement's. What happened to the idea of a `Model`?
</details>
This is an incremental PR towards the eventual elimination of a model ID. Once we've fully decoupled 

---

*[drake/systems/plants/RigidBodySystem.h, line 327 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN933FNd8-vrB4crvGO:-KNAJilIXMHTmX6kMWYf:-1688601049) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBodySystem.h#L327)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> See comment above. Why to expose model_id to the user? is this what we want in the long term?
</details>
As described above, the current design of `RigidBodySystem` and `RigidBodyTree` requires that `model_id` be used to differentiate multiple models within the system / tree. I don't see a problem exposing this fact through the constructor since that enables the member variables that hold this information to be `const`, which I believe it safer and clearer.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KN93MsyN_WCpWvY_cr6:-KNAKBYDmS4QLMfLxnHA:-2080611847) ([raw file](https://github.com/robotlocomotion/drake/blob/b3b09355a63e360a5138779685774466ca9dccdd/drake/systems/plants/RigidBodyTree.cpp#L46)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This is confusing. Now there is also a kWorldModelName? and we put it in RigidBodyTree.cpp?
</details>
Yes, this is actual more clear now because the previous code was leaving the model name of the `RigidBody` that represents the world undefined, which is technically a bug (see [this code](https://github.com/RobotLocomotion/drake/blob/59b23e47067b0b47b878cb45c8e8934a300ea05a/drake/systems/plants/RigidBodyTree.cpp#L85).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-:-KN9VPcNVKauf44cnEKe:1507721328)*

**Comment by liangfok** [comment]
Review status: 2 of 18 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Cars/demo_multi_car.cc, line 72 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KNAXtS80zf1AAlHcIU5:-KNAXtS80zf1AAlHcIU6:33301223) ([raw file](https://github.com/robotlocomotion/drake/blob/3f4d48f98643f5212e5a3619b87769488dd1cfbe/drake/examples/Cars/demo_multi_car.cc#L72)):*
> ```cpp
>       (i % 5) ? kSedanUrdf : kBreadtruckUrdf, DrakeJoint::ROLLPITCHYAW,
>       nullptr /*weld_to_frame*/, world_tree.get());
>     world_tree->bodies.back()->robotnum = i + 1;
> ```

@jwnimmer-tri and @maddog-tri can verify that this is correct. Note that this PR moves the setting of the `robotnum` (a.k.a. `model_id`) into the parser itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2859)*

**Comment by liangfok** [comment]
Review status: 2 of 18 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Cars/demo_multi_car.cc, line 72 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KNAXtS80zf1AAlHcIU5:-KNClTgoWvphy1eH1zx4:-2147449605) ([raw file](https://github.com/robotlocomotion/drake/blob/3f4d48f98643f5212e5a3619b87769488dd1cfbe/drake/examples/Cars/demo_multi_car.cc#L72)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> @jwnimmer-tri and @maddog-tri can verify that this is correct. Note that this PR moves the setting of the `robotnum` (a.k.a. `model_id`) into the parser itself.
</details>
FTR, the fact that the `model_id` is set by the parser is simply a short-term solution based on the current state of the code (note that the SDF parser already does this). Once this PR is merged and a `Model` abstraction is introduced, the plan is for the `model_id` to be set when a `Model` is added to a `RigidBodySystem`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2859)*

**Comment by maddog-tri** [comment]
Review status: 2 of 18 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Cars/demo_multi_car.cc, line 72 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2859#-KNAXtS80zf1AAlHcIU5:-KND6M0oC-DV2smJfBQQ:-13816665) ([raw file](https://github.com/robotlocomotion/drake/blob/3f4d48f98643f5212e5a3619b87769488dd1cfbe/drake/examples/Cars/demo_multi_car.cc#L72)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> FTR, the fact that the `model_id` is set by the parser is simply a short-term solution based on the current state of the code (note that the SDF parser already does this). Once this PR is merged and a `Model` abstraction is introduced, the plan is for the `model_id` to be set when a `Model` is added to a `RigidBodySystem`.
</details>
"Whatever."  In other words:  originally, this line of code (or it predecessor) was accompanied by a comment saying "This is a hack that appears to be necessary to make this work."  Calling `AddRobotFromURDF()` *without* hacking the `robotnum`/`model_id`/etc to be unique would cause all but one of the loaded models to be ignored/lost-in-the-ether. If multiple models can now be effectively loaded without hacking `robotnum`, great, this line can go away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2859)*

**Comment by liangfok** [comment]
I'm going to close this PR, break it down into smaller pieces, and switch to the "instance name" idea that was decided in a meeting with @amcastro-tri, @jwnimmer-tri, and @maddog-tri.

**Comment by amcastro-tri** [comment]
Thank you @liangfok!! Could I suggest you PR all the refactor changes in a separate PR first?

**Comment by liangfok** [comment]
Yes of course. They will be in flight soon.

**Pull request closed without merging**
