### PR TITLE
Cleanup GcsTrajectoryOptimization::EdgesBetweenSubgraphs

### PR DESCRIPTION
**Pull request by RussTedrake**
To use less placeholder variables, and make use of the new BezierCurve::AsLinearInControlPoints() to avoid symbolic expressions.

+wrangelvid for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@wrangelvid for feature review, please.

**Comment by RussTedrake** [comment]
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 405 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NapoEWY4_YcYKPCJeiO:-NapoEWY4_YcYKPCJeiP:b-y5h9bp) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf7bd550f686a4d1f10f725ba1df1719d664c186/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L405)):*
> ```cpp
>         vr_trajectory_.AsLinearInControlPoints(1).row(0);
>     SparseMatrix<double> H_ub = H_lb;
>     for (int i = 0; i < num_positions(); ++i) {
> ```

btw -- these loops aren't as clean/simple as I'd like.  Maybe I *should* consider returning just the really big, repeated, matrix from AsLinearInControlPoints().

**Review by RussTedrake — COMMENTED** [review]
fwiw -- i think i have a much cleaner version; I'll push it shortly.  (but it requires reverting my change to the transpose on the AsLinearInControlPoints!). ;-)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-:-Napt1S2-QcCVpD2GddI:b-3v5x67)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
Done.  The code didn't get much cleaner, but I've added substantially to the documentation of the AsLinearInControlPoints, and I think it's much more clear now why we shouldn't have taken the transpose.  PTAL.

I'm going to mark this as high priority, since we're still in a sort of grace period of the AsLinearInControlPoints change.  But I don't want that out there for long if it's about to change.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-:-NaqOKFo3BSN0r9KC5Uq:b-92j4w)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907)* status: 4 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/bezier_curve.h` line 75 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NarrrPk88BVW-XN7otD:-NarrrPk88BVW-XN7otE:b-shvzh8) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/common/trajectories/bezier_curve.h#L75)):*
> ```objc
>      auto c = std::make_shared<solvers::LinearConstraint>(
>        M.col(k).transpose(), Vector1d(lb(i)), Vector1d(ub(i)));
>      prog.AddConstraint(c, p.row(i).transpose());
> ```

It's not clear that p is the kth control point that you are iterating through.
___
*[`common/trajectories/bezier_curve.h` line 85 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-Narry7K2B3BYtpKZDnH:-Narry7K2B3BYtpKZDnI:b-7663d) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/common/trajectories/bezier_curve.h#L85)):*
> ```objc
>    <pre>
>    vec(derivative.control_points().T) = blockMT * vec(this.control_points().T),
>    blockMT = [ M.T,   0, .... 0 ]
> ```

Can you provide an example similar to the one above?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 405 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NapoEWY4_YcYKPCJeiO:-NarsoVK7jakjP8FjJFq:b-myc3lc) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf7bd550f686a4d1f10f725ba1df1719d664c186/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L405)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- these loops aren't as clean/simple as I'd like.  Maybe I *should* consider returning just the really big, repeated, matrix from AsLinearInControlPoints().
</blockquote></details>

I agree. In most cases, we end up constraining all dimensions of a control point. So we might as well return a big matrix.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 262 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NarpRxd0fu6Y_Cu7k1-:-NarpRxd0fu6Y_Cu7k10:b-ahsyja) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L262)):*
> ```cpp
> 
>   // Zeroth order continuity constraints.
>   //  u.r.control_points.col(-1) == v.r.control_points(0).
> ```

It would be nice to stay consistent with the comment you had in the continuity constraints in subgraph.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 335 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-Narq9JW4KIB4MKR8th2:-Narq9JW4KIB4MKR8th3:btojbfd) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L335)):*
> ```cpp
>     // Otherwise, we can formulate a problem to check if a point is contained in
>     // A, B and the subspace.
>     Intersection intersection(MakeConvexSets(A, B, subspace));
> ```

Great!

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907)* status: 3 unresolved discussions, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/bezier_curve.h` line 75 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NarrrPk88BVW-XN7otD:-Nasfirn-1kZJFm3TNsy:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/common/trajectories/bezier_curve.h#L75)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

It's not clear that p is the kth control point that you are iterating through.
</blockquote></details>

Done.
___
*[`common/trajectories/bezier_curve.h` line 85 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-Narry7K2B3BYtpKZDnH:-NasjdtYCKuNCwJCzH53:b-nimvg0) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/common/trajectories/bezier_curve.h#L85)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Can you provide an example similar to the one above?
</blockquote></details>

Done.  I've done it in the tests, but there is not enough support for SparseMatrix to make it usable yet.  I've also added a TODO to implement some helpers at some point.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 405 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NapoEWY4_YcYKPCJeiO:-NaskAip0mPHFCtKyQgu:b-4u5kmq) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf7bd550f686a4d1f10f725ba1df1719d664c186/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L405)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I agree. In most cases, we end up constraining all dimensions of a control point. So we might as well return a big matrix.
</blockquote></details>

Done.  unfortunately, I can't make it better without adding a helper for block diagonal SparseMatrix.  (See the TODO in the bezier test)
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 262 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NarpRxd0fu6Y_Cu7k1-:-Nask8ru1fyNJf-Q_Ch5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c76d9a012e02c72685f702e40f8952fc110919/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L262)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

It would be nice to stay consistent with the comment you had in the continuity constraints in subgraph.
</blockquote></details>

Done.

**Review by wrangelvid — COMMENTED** [review]
Great work! I am looking forward to see another iteration on returning a block matrix ;) :lgtm: 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-:-Natcrqw9J17eZXxd9Tn:b-4xk20r)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/test/bezier_curve_test.cc` line 293 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-NatcOp-Ck-XViVF9d1n:-NatcOp03upv5XMWJDaK:b-usxna1) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4184be74b3a7e2cc27b6d0eab42a84c692b9084/common/trajectories/test/bezier_curve_test.cc#L293)):*
> ```cpp
>       curve.rows() * (deriv_bezier.order() + 1));
>   EXPECT_TRUE(
>       CompareMatrices(vec_deriv_points, blockMT * vec_curve_points, 1e-12));
> ```

This is very nice! Looking forward to see `AsLinearInControlPoints()` returns this block matrix.

**Review by RussTedrake — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19907#-:-NavAWgs0LXhndhwaqBq:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform)

**Pull request merged**
