### PR TITLE
Improves error message when Fortran compiler version is too low.

### PR DESCRIPTION
**Pull request by liangfok**
This builds upon #4150.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4237)

### CODE REVIEW

**Comment by liangfok** [comment]
+@mrhebert for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4237#-:-KXGZID6vmsrKxBLREZl:bhwppfs)*

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4237#-:-KXGZW4HJODwJ878w4Jl:b86ql3n)*

**Comment by mrhebert** [comment]
:lgtm: Great change, thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4237#-:-KXGd3jAJTvQ9ftluJ7z:bloqas2)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4237#-:-KXGmhcf724IwWCSBk--:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4237#-:-KXGmmBUP4tFSvFc0d43:bnfp4nl)*

**Pull request merged**
