### PR TITLE
[geometry] IllustrationProperties can be updated after parsing

### LINKED ISSUE #13126: Can't programmatically alter transparency of model loaded from URDF/SDF in visualization
A user requested the ability to visualize a robot with transparency. The robot is specified in a URDF/SDF file, which in turn references objs and mtl files. The challenge, is that the user wants to apply transparency *on top* of those specifications. In other words, they shouldn't have to change the specification on disk to achieve a run-time effect.

The relationship between `IllustrationProperties` and `drake_visualizer` is such that if the ("phong", "diffuse") value has a non-unit alpha channel, that alpha value will *still* affect the visualization of the robot whose visual appearance would *otherwise* be defined by the mtl file. This provides the means.

The missing piece is that `SceneGraph::AssignRole()` isn't implemented for `IllustrationProperty` and `RoleAssign.kReplace` so the diffuse value *cannot* be changed after parsing. We need to implement this in order to enable this behavior.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This PR has two curated commits:

1. The first extends `GeometryProperties` functionality to make it easier to modify properties. A mutable instance of `GeometryProperties` can have properties removed, updated, or overwritten.
2. The second enables `AssignRole(..., IllustrationProperties, AssignRole::kReplace)`. Previously, that would throw. Due to issues in the greater ecosystem, this added functionality comes with limitations and warnings.
  - there are warnings in the documentation.
  - Warnings will likewise get printed to the console.

resolves #13126

(While not the total solution, it is sufficient to empower workflows to change visual appearance of parsed geometry.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13598)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI while it is not a defect (yet?) per our merge process, I'd like to encourage you when using "properly curated" style to frequently rebase the PR onto recent master, so that we don't have long stretches of parallel history like so (the brown line):

image

**Comment by SeanCurtis-TRI** [comment]
Thank you. I was uneasy when I hit merge, suspicious I'd forgotten something. And that was it.  :-(

**Comment by jwnimmer-tri** [comment]
=> https://github.com/Reviewable/Reviewable/issues/763 would allow us to automate this reminder

**Comment by SeanCurtis-TRI** [comment]
I like that.

**Pull request merged**
