### PR TITLE
[vtk] Unify include spelling, add comments, fix deps

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19945 and #16502.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20024)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, if you please.  I'd offer this doesn't necessarily need a full cross-check, rather more like a spot check + endorsement of the approach.

\CC @SeanCurtis-TRI for awareness.

**Review by rpoyner-tri — COMMENTED** [review]
/me glances a "What would Lakos do?" rubber bracelet

Sigh. Is there any tool support for maintaining the annotations?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20024#-:-NcNljRQ2QuUIJLjWJXA:bk5kdkl)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
Maybe it would be good enough to have write-up somewhere to guide maintainers for this idiom.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20024#-:-NcNrKYq5klp3LlctonL:b-pjhaxj)* status: LGTM missing from assignee rpoyner-tri(platform)

**Comment by jwnimmer-tri** [comment]
> Maybe it would be good enough to have write-up somewhere to guide maintainers for this idiom.

It's difficult for me to put myself in those shoes and guess what they might need.  Here's some brain dumping:

For a VTK header we already use somewhere, the easy answer is to cargo cult from an existing Drake `#include` when including that VTK header in a new Drake file.

If a developer wants to use a particular VTK header for the first time inside Drake, the trick is to find the header in the VTK source tree (e.g., https://github.com/Kitware/VTK/blob/master/IO/Image/vtkImageExport.h) and so `#include <vtkImageExport.h>` gets the comment `// vtkIOImage` based on the parent directory names.

As a last resort, I could add that to the commit message.  I wonder where else someone would look.  Maybe `tools/workspace/vtk/README.md` is the best option, but I'm not sure anyone would look there?

**Review by rpoyner-tri — COMMENTED** [review]
Yup, I grant that knowing **where** to write is a hard problem. I'd settle for commit message now, and we see what needs arise later.

:lgtm: 

> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20024#-:-NcNw0Yq4hRA1Plf1JCB:b67yw9t)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Comment by jwnimmer-tri** [comment]
> I'd settle for commit message now, ...

Done.

**Pull request merged**
