### PR TITLE
[cmake] Use Bazelisk to download Bazel

### LINKED ISSUE #19923: CMakeLists should auto-fetch Bazel
**Is your feature request related to a problem? Please describe.**

When using the [drake_cmake_external](https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_cmake_external ) workflow, we currently expect/assume that the user has already installed `bazel` somehow.

The drake-external-examples CI does this with some [PPA magic here](https://github.com/RobotLocomotion/drake-external-examples/blob/b5fc71e37860193826cbf4984c3caa4be7105460/scripts/setup/linux/ubuntu/focal/install_prereqs#L83).

However, that install-prep step is pretty brutal for the (quite reasonable) users who want to pretend that Drake only uses CMake when they run the CMake build.

**Describe the solution you'd like**

When the user runs our CMake build, and does not have a suitable local copy of Bazel already available, our listfile should automatically fetch a pinned & checksum-verified precompiled stable release of Bazel, and use that automatically.  There should be no requirement to pre-install Bazel prior to running Drake's CMake install.

Note that one possible way to do this would be to use `bazelisk` as our Bazel.  The code at https://github.com/RobotLocomotion/drake-blender has an example of this.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19923.

See also https://github.com/bazelbuild/bazelisk/pull/494.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@svenevs and/or +@mwoehlke-kitware for feature review, please.  Feel free to unassign the other if you think your own review will be sufficient.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please.

running mac wheel while testing locally

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 1 unresolved discussion, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-NcwuxRP7dMW8vG5pWbm:b-bg8oet) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
> ```CMake
> find_program(Bazel_EXECUTABLE
>   NAMES bazel bazelisk bazelisk.py
>   PATHS "${PROJECT_SOURCE_DIR}/third_party/com_github_bazelbuild_bazelisk"
> ```

Working, I'm having a hard time understanding our desired outcome here.  Just using a single thread here, at the very least we probably want to add `NO_DEFAULT_PATHS` to [CMake's `find_program`](https://cmake.org/cmake/help/latest/command/find_program.html) and probably every other `NO_*_PATH` variable.

When looking at how things are being done differently on macOS vs linux in the `install_prereqs_user_environment.sh`, I don't understand why we're keeping the split.  I was under the impression that if we're going to vendor `com_github_bazelbuild_bazelisk`, then we want our `setup/` scripts to stop installing bazel at all (on macOS we are still installing `bazelisk` from `brew`, and on linux we still download it if it is not already there).

I believe the impact here is that what happens in CMake and what happens in bazel are different now.  Are we not trying to remove the stuff from `setup/` using this?

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 1 unresolved discussion, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-Ncwy7P8D0YmfH1ScjW2:brmprnw) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, I'm having a hard time understanding our desired outcome here.  Just using a single thread here, at the very least we probably want to add `NO_DEFAULT_PATHS` to [CMake's `find_program`](https://cmake.org/cmake/help/latest/command/find_program.html) and probably every other `NO_*_PATH` variable.

When looking at how things are being done differently on macOS vs linux in the `install_prereqs_user_environment.sh`, I don't understand why we're keeping the split.  I was under the impression that if we're going to vendor `com_github_bazelbuild_bazelisk`, then we want our `setup/` scripts to stop installing bazel at all (on macOS we are still installing `bazelisk` from `brew`, and on linux we still download it if it is not already there).

I believe the impact here is that what happens in CMake and what happens in bazel are different now.  Are we not trying to remove the stuff from `setup/` using this?
</blockquote></details>

If I understand the docs correctly, `NO_DEFAULT_PATHS` is the superset of `NO_*_PATH`.

Do we want that? It's unclear; as written, we'll still use `bazel` if it exists in the user's environment. I was (also?) under the impression the idea was to *always* use bazelisk, but maybe that impression is wrong?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 1 unresolved discussion, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-Ncx-essE3jqTsSGPOip:bhrtkc) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... at the very least we probably want to add `NO_DEFAULT_PATHS`

What would be the upside of that?  If the user has a proper bazel already installed on a default path, I think we should use it without any extra downloads.  Our vendored bazelisk is intended to be a fallback of last resort.

The thing I didn't implement here, but considered as future work, would be to keep searching the paths (in a proper order) until a suitable version is found, in case some earlier hits were too old.  My thinking was to defer that until necessary, since `install_prereqs.sh` still defaults to installing a proper bazel or bazelisk natively.

> I don't understand why we're keeping the split.

Our vendored python bazelisk is neutered.  The native homebrew version has a lot more features, and is better for Drake developers to use.
</blockquote></details>

Or in other words...

If a Drake developer or user keeps doing the default "install prereqs with bazel" setup, the changes to this file are a no-op.

If a linux user does "install prereqs without bazel" (and does not have any bazel-like things installed anywhere, e.g., in a docker container) then this will fall back to the vendored bazelisk.  This allows people building using CMake in a container to depend only on stock Ubuntu debs.

**Review by svenevs — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 6 of 12 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 2 unresolved discussions, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-Ncx6Edd0GShZt8K2w9-:bc6iavb) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Or in other words...

If a Drake developer or user keeps doing the default "install prereqs with bazel" setup, the changes to this file are a no-op.

If a linux user does "install prereqs without bazel" (and does not have any bazel-like things installed anywhere, e.g., in a docker container) then this will fall back to the vendored bazelisk.  This allows people building using CMake in a container to depend only on stock Ubuntu debs.
</blockquote></details>

Ok, I don't think this does that correctly.  Before looking at implementing, if somebody (a) has bazel installed and (b) it is too old of a version, should the build fail?  Or should it get the one we need?

Making it fail makes life a little easier, but the idea is in the `CMakeLists.txt` we probably want to do something a little more differently:

```
# The version passed to find_package(Bazel) should match the
# minimum_bazel_version value in the call to versions.check() in WORKSPACE.
set(MINIMUM_BAZEL_VERSION 4.0)
find_package(Bazel ${MINIMUM_BAZEL_VERSION} MODULE)
if(NOT Bazel_FOUND)
  # manually search our vendored third party and run `bazelisk version`?
  # do not put this logic in the find module, makes it more difficult for no reason
  # e.g., I don't want to find_package(Bazel) here with a new Bazel_ROOT
  # and different names to search for (bazelisk and bazelisk.py)
endif()
```

Like, I think we want it to "find the first `bazel`" (user is responsible for this, e.g., via `PATH`).  If not found, we can either error, or get the right one.  If their system version is too old, we have a similar choice.
___
*[`tools/wheel/image/build-drake.sh` line 12 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-Ncx0ddf2rdpJe9i-a8t:-Ncx0ddg5VVVBRgU1n0q:b-lgppst) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/tools/wheel/image/build-drake.sh#L12)):*
> ```Shell
> git apply < /image/pip-drake.patch
> 
> export BAZELISK_HOME=/var/cache/bazel/bazelisk
> ```

working, this path concerns me, waiting for the mac monterey queue to run the wheel job but if it takes too long I will test locally

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 2 unresolved discussions, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-Ncx8OW16GaEumMvIeh-:b-by1oox) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
> If somebody (a) has bazel installed and (b) it is too old of a version, should the build fail? Or should it get the one we need?

All else being equal, fetching the one we need would be nice.  However, on master today the build would fail, so sticking with "fail" for now is OK.

> I don't think this does that correctly.

Could you describe the conditions where something goes wrong?

In any case, I need to turn some of the context in this discussion into comments in the code, but I'm holding off on that until we're on the same page.
___
*[`tools/wheel/image/build-drake.sh` line 12 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-Ncx0ddf2rdpJe9i-a8t:-Ncx93OB9R6ZTABxxrd2:b-rv00cz) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/tools/wheel/image/build-drake.sh#L12)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, this path concerns me, waiting for the mac monterey queue to run the wheel job but if it takes too long I will test locally
</blockquote></details>

This is the path where downloads of the versioned `bazel` get dumped.  It seemed nice to keep them in the cache instead of always re-downloading them.

(I should add a comment about this.)

**Comment by mwoehlke-kitware** [comment]
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-NcxEAMTEifXEcMD35kW:b-x8cspt) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
> Our vendored bazelisk is intended to be a fallback of last resort

Okay, I guess I'd missed that.

I wonder if this isn't over-thinking things. I suspect it makes sense to accept `bazelisk` as an alternate spelling of `bazel` (is that sufficient for homebrew?). But on further consideration, I'm not sure `FindBazel.cmake` should know anything about our vendored Bzelisk. Maybe we should just make the `find_package` not required and add `if(NOT Bazel_FOUND)` followed by setting `Bazel_EXECUTABLE` to our internal Bazelisk. (Possibly with a warning that we're doing so.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 2 unresolved discussions, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master

___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-NcxFU8dBqKhN1bPed-a:bcsyaok) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
On homebrew, `brew bazelisk` provides both `bazel` and `bazelisk` on the default path (and they are both symlinks to the bottled `bazelisk` binary).

> Maybe we should just make the `find_package` not required ...

Now that you mention it, that does sound a lot simpler.  I'll try that out locally.

**Comment by mwoehlke-kitware** [comment]
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-NcxGwId3sfmr3_uebGk:b63e13x) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On homebrew, `brew bazelisk` provides both `bazel` and `bazelisk` on the default path (and they are both symlinks to the bottled `bazelisk` binary).

> Maybe we should just make the `find_package` not required ...

Now that you mention it, that does sound a lot simpler.  I'll try that out locally.
</blockquote></details>

Right; I think our current thoughts are:
- Don't add `PATHS` to the find module. `NAMES bazelisk` is probably good; not sure if `bazelisk.py` still makes sense.
- `find_package(Bazel)` is not `REQUIRED`
- `if(NOT Bazel_FOUND)` then set `Bazel_EXECUTABLE` to vendored Bazelisk. Maybe warn that we're doing so.

Stephen also pointed out that if the module finds Bazelisk, the `execute_process` is going to download Bazel. We might want to try to detect first if `Bazel_EXECUTABLE` is Bazelisk and skip the version check if so.

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 6 of 12 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 4 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 3 unresolved discussions, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcxINtB0dYK0KeXmhT8):*
FYI, I take it this is the list of people that authored bazelisk.py? (Do we normally do this when importing sources, vs. just having authorship information alongside somewhere?)
___
*[`tools/workspace/bazelisk/test/lint_test.py` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcxJFz1A2cE5n9GVe0_:-NcxJFz1A2cE5n9GVe0a:b-iiynml) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/tools/workspace/bazelisk/test/lint_test.py#L9)):*
> ```Python
> $ cp bazel-drake/external/bazelisk/LICENSE \
>      bazel-drake/external/bazelisk/bazelisk.py \
>      third_party/com_github_bazelbuild_bazelisk/
> ```

`cp -t`¹ won't accidentally overwrite src2 with src1... (One might add `-i` also, but that might be excessive.)

(¹ ...although `-t` is GNU-only; is it okay to specify doing this on Ubuntu?)



_Suggestion:_
```Python
$ cp -t third_party/com_github_bazelbuild_bazelisk/ \
     bazel-drake/external/bazelisk/LICENSE \
     bazel-drake/external/bazelisk/bazelisk.py
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064)* status: 3 unresolved discussions, LGTM missing from assignees svenevs,mwoehlke-kitware, needs platform reviewer assigned

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcxINtB0dYK0KeXmhT8):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, I take it this is the list of people that authored bazelisk.py? (Do we normally do this when importing sources, vs. just having authorship information alongside somewhere?)
</blockquote></details>

I got carried away.  Removed.
___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-NcxwtyR-e0i3Zd6KlNh:b28k64m) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Right; I think our current thoughts are:
- Don't add `PATHS` to the find module. `NAMES bazelisk` is probably good; not sure if `bazelisk.py` still makes sense.
- `find_package(Bazel)` is not `REQUIRED`
- `if(NOT Bazel_FOUND)` then set `Bazel_EXECUTABLE` to vendored Bazelisk. Maybe warn that we're doing so.

Stephen also pointed out that if the module finds Bazelisk, the `execute_process` is going to download Bazel. We might want to try to detect first if `Bazel_EXECUTABLE` is Bazelisk and skip the version check if so.
</blockquote></details>

Makes sense, thanks.  I took a stab at it.
___
*[`tools/wheel/image/build-drake.sh` line 12 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-Ncx0ddf2rdpJe9i-a8t:-Ncxxm9x2P9lOSqq41T0:boag87p) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/tools/wheel/image/build-drake.sh#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is the path where downloads of the versioned `bazel` get dumped.  It seemed nice to keep them in the cache instead of always re-downloading them.

(I should add a comment about this.)
</blockquote></details>

Commented.
___
*[`tools/workspace/bazelisk/test/lint_test.py` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcxJFz1A2cE5n9GVe0_:-Ncxx2p3DhIDIDpu7Tl6:bkzf3u1) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/tools/workspace/bazelisk/test/lint_test.py#L9)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

`cp -t`¹ won't accidentally overwrite src2 with src1... (One might add `-i` also, but that might be excessive.)

(¹ ...although `-t` is GNU-only; is it okay to specify doing this on Ubuntu?)
</blockquote></details>

It's _probably_ only going to be run on Ubuntu, but anyway I don't think the mistake is very likely or recovery from it very difficult.  If we find the instructions are too difficult as-is, the plan would be to provide a program to do it (e.g. an `--update` argparse flag to this test).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-cmake-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-:-Nd0k5QDCecCP88b1_do:bg7igkv)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcxINtB0dYK0KeXmhT8):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I got carried away.  Removed.
</blockquote></details>

:+1: 
___
*[`cmake/modules/FindBazel.cmake` line 6 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcwuxRO0NyZuWnerbec:-Nd0jXDp4WxPobB97rx9:b-8fx2u7) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/cmake/modules/FindBazel.cmake#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Makes sense, thanks.  I took a stab at it.
</blockquote></details>

:+1: 
___
*[`tools/workspace/bazelisk/test/lint_test.py` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-NcxJFz1A2cE5n9GVe0_:-Nd0jxRnDhkiwvAkQVu5:b-xm854w) ([raw file](https://github.com/RobotLocomotion/drake/blob/e568d6a21eb777de63253940e48335c17650335e/tools/workspace/bazelisk/test/lint_test.py#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's _probably_ only going to be run on Ubuntu, but anyway I don't think the mistake is very likely or recovery from it very difficult.  If we find the instructions are too difficult as-is, the plan would be to provide a program to do it (e.g. an `--update` argparse flag to this test).
</blockquote></details>

:shrug:

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

We still have some feature comments from @svenevs pending, but I'm hoping this is close enough to final form that platform review now will be OK.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-:-Nd0nJuo7w560fWrLZNK:b-kr5d7t)* status: 2 unresolved discussions, LGTM missing from assignees svenevs,rpoyner-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 6 of 12 files at r2, 1 of 1 files at r3, 3 of 6 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20064#-:-Nd0ykTlAiFVs1cQql5k:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Pull request merged**
