### PR TITLE
[parsing] Complete adding diagnostic policy in urdf_geometry

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #16782

This patch finishes plumbing diagnostic policy through
detail_urdf_geometry. It also rewrites the existing tests to reduce
copy-paste, and adds numerous new tests to reach full coverage of all
the modified error and warning branches.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 
+@sammy-tri for feature review please. Let me know if you'd like me to find another reviewer; this one is a bear.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910#-:-MzwjuK--WWK534QMQRK:bc3zwks)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16910#-MzwnK6g19WJtqwU9H71:-MzwnK6g19WJtqwU9H72:b-mbz4ko) (no related file):*
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please.

rattin' frattin' jdk11 download...

---

**Review by sammy-tri — COMMENTED** [review]
Pausing review for a bit, should hopefully get back to this later today.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910#-:-N--71HB3dNu8E2qzSX0:b-7upt5p)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sammy-tri)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 399 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--3sVC8bU2CrglN5tM:-N--3sVC8bU2CrglN5tN:b5fe9z5) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L399)):*
> ```cpp
> 
>   // Ensures there is a geometry child element. Since this is a required
>   // element, throws an exception if a geometry element does not exist.
> ```

nit: Is the comment still accurate to say that we throw an exception?  (It's true in the default case...)
___
*[multibody/parsing/detail_urdf_geometry.cc, line 417 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--57JW9kbGm47qp8UZ:-N--57JW9kbGm47qp8U_:bln34ew) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L417)):*
> ```cpp
>   }
> 
>   std::unique_ptr<geometry::Shape> shape =
> ```

Should there be an early return here if shape is empty?  (`ParseCollision` does this)
___
*[multibody/parsing/detail_urdf_geometry.cc, line 425 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--5af44Jg_cHe84dbL:-N--5af44Jg_cHe84dbM:buifrnv) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L425)):*
> ```cpp
>   const XMLElement* material_node = node->FirstChildElement("material");
>   if (material_node) {
>     UrdfMaterial material =
> ```

What happens here if `ParseMaterial` has an error?  Should we have a check and return?  Or a comment that we want to keep going anyway?

I wrote this before I realized that proceeding with the default is what we seem to have chosen to do deliberately, so maybe this is fine (will close this issue if you think no change is needed)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sammy-tri)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 399 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--3sVC8bU2CrglN5tM:-N--E1veDoUBX0MpyO7B:bxi9ysq) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L399)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: Is the comment still accurate to say that we throw an exception?  (It's true in the default case...)
</blockquote></details>

Will fix to the more cagey "emit an error" language.
___
*[multibody/parsing/detail_urdf_geometry.cc, line 417 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--57JW9kbGm47qp8UZ:-N--DkEL4EdUiE-Li_eW:b-f1l1w2) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L417)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should there be an early return here if shape is empty?  (`ParseCollision` does this)
</blockquote></details>

This probably is a problem. I'll do some digging.
___
*[multibody/parsing/detail_urdf_geometry.cc, line 425 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--5af44Jg_cHe84dbL:-N--BawLAQpwAVJ1-UgW:bch6h02) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L425)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

What happens here if `ParseMaterial` has an error?  Should we have a check and return?  Or a comment that we want to keep going anyway?

I wrote this before I realized that proceeding with the default is what we seem to have chosen to do deliberately, so maybe this is fine (will close this issue if you think no change is needed)
</blockquote></details>

This is a good example of my struggle through this whole train. In conversations with Nimmer, we got to a policy something like the following. Errors (and maybe warnings, depending on config) are the sources of truth about parsing failure;  it's fine for a failed parse to return an incomplete or incorrect model (maybe useful for debugging?), but not fine to crash. The design of DiagnosticPolicy allows for errors to not throw, but so far that has only been used in unit tests. I suspect if a production configuration of errors-don't-throw happens, its use will be narrow and specialized.

With all that in mind, ParseMaterial will have already emitted an error on parse failure, so our only job as the caller is to not crash in the (maybe rare? artificial?) case where errors are not implemented to throw. Also, the general yank of control flow is why I have tried hard to improve the coverage to 100% of statements, and in some places try to cover corner cases of values, etc. It's possible there is a crash hazard I have missed, but I think the `material` returned will always be valid enough to leave this function alive.

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sammy-tri)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 425 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--5af44Jg_cHe84dbL:-N--Eq0D076VHQKIofGP:b1bu16r) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L425)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This is a good example of my struggle through this whole train. In conversations with Nimmer, we got to a policy something like the following. Errors (and maybe warnings, depending on config) are the sources of truth about parsing failure;  it's fine for a failed parse to return an incomplete or incorrect model (maybe useful for debugging?), but not fine to crash. The design of DiagnosticPolicy allows for errors to not throw, but so far that has only been used in unit tests. I suspect if a production configuration of errors-don't-throw happens, its use will be narrow and specialized.

With all that in mind, ParseMaterial will have already emitted an error on parse failure, so our only job as the caller is to not crash in the (maybe rare? artificial?) case where errors are not implemented to throw. Also, the general yank of control flow is why I have tried hard to improve the coverage to 100% of statements, and in some places try to cover corner cases of values, etc. It's possible there is a crash hazard I have missed, but I think the `material` returned will always be valid enough to leave this function alive.
</blockquote></details>

Ok, I think it's fine as is based on that philosophy.  I agree it won't crash (similar to the case when parsing friction for collision elements).

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 417 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--57JW9kbGm47qp8UZ:-N--WuJH7_60gZjk-4xl:bsxc27v) ([raw file](https://github.com/robotlocomotion/drake/blob/03f724cf91c8825daa49c398c01c26b8cb18fabd/multibody/parsing/detail_urdf_geometry.cc#L417)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This probably is a problem. I'll do some digging.
</blockquote></details>

Done. Required another test case to maintain full statement coverage.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +@xuchenhan-tri for platform review (rotation)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910#-:-N--iLpZEOnwoWHCyp0F:b-push3h)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm:
Too many branches in the logic to keep track of test coverage. I'm relying on feature reviewer and kcov.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910#-:-N-06BH12nJ1gLv-BFjg:b5sqfeq)* status: 5 unresolved discussions (waiting on @rpoyner-tri)

___
*[multibody/parsing/detail_urdf_geometry.h, line 81 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N-00BWq6VAT3unw0ctD:-N-00BWq6VAT3unw0ctE:b-6zyyeu) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/detail_urdf_geometry.h#L81)):*
> ```objc
> 
>  @param[in] node The <material> XML node.
>  @param[in] name_required If true, throws if the tag doesn't have the name
> ```

nit, this doesn't necessarily throw now. There are a few other place within this file where the doc has gone out of sync.
___
*[multibody/parsing/detail_urdf_geometry.h, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--z6PE0Wsm2ymf4sO4:-N--z6PE0Wsm2ymf4sO5:bypxfds) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/detail_urdf_geometry.h#L94)):*
> ```objc
>        released by companies and organizations like Robotiq and ROS Industrial
>        (for example, see this URDF by Robotiq: http://bit.ly/28P0pmo).  */
> UrdfMaterial ParseMaterial(const TinyXml2Diagnostic& diagnostic,
> ```

nit, consistency: this parameter should be mentioned in the doc too,
___
*[multibody/parsing/detail_urdf_geometry.h, line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N--z-V_CeLC6rXxm0MK:-N--z-V_CeLC6rXxm0ML:bi400ep) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/detail_urdf_geometry.h#L147)):*
> ```objc
> */
> std::optional<geometry::GeometryInstance> ParseVisual(
>     const TinyXml2Diagnostic& diagnostic,
> ```

nit, consistency: this parameter should be mentioned in the doc too. Ditto below.
___
*[multibody/parsing/detail_urdf_geometry.cc, line 266 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N-0C2HIAY7NGgPZdIPz:-N-0C2HIAY7NGgPZdIQ-:bfm1kjj) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/detail_urdf_geometry.cc#L266)):*
> ```cpp
>     }
>   }
>   return std::make_unique<geometry::Ellipsoid>(axes[0], axes[1], axes[2]);
> ```

minor, one last line not covered according to kcov.
___
*[multibody/parsing/detail_urdf_geometry.cc, line 582 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N-00Smo2oSj_vZCsNan:-N-00Smo2oSj_vZCsNao:brnnsn2) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/detail_urdf_geometry.cc#L582)):*
> ```cpp
> 
>   // Ensures there is a geometry child element. Since this is a required
>   // element, throws an exception if a geometry element does not exist.
> ```

nit, stale comment.
___
*[multibody/parsing/test/detail_urdf_geometry_test.cc, line 260 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N-02h5C5j6fejZV1iIA:-N-02h5C5j6fejZV1iIB:b2nhoia) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/test/detail_urdf_geometry_test.cc#L260)):*
> ```cpp
>     MakeCollisionDocFromString(collision_spec);
>     const XMLElement* collision_node = xml_doc_.FirstChildElement("collision");
>     EXPECT_NE(collision_node, nullptr) << collision_spec;
> ```

TIL

**Review by rpoyner-tri — COMMENTED** [review]
Agreed. Since it's essentially error-behavior coverage, it's all branches. kcov is essential.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910#-:-N-3eVZXEHiBqC7O9wwJ:bkhi2vn)* status: 3 unresolved discussions (waiting on @rpoyner-tri, @sammy-tri, and @xuchenhan-tri)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 266 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N-0C2HIAY7NGgPZdIPz:-N-3hfM41j7bChGlBqsl:bs28nv5) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/detail_urdf_geometry.cc#L266)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, one last line not covered according to kcov.
</blockquote></details>

Hm, fault injection (`DRAKE_DEMAND(false)`) says otherwise. This may be a case where kcov reports lie a little bit. I suppose kcov is necessary, but not sufficient, thanks to cases like this.
___
*[multibody/parsing/test/detail_urdf_geometry_test.cc, line 260 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16910#-N-02h5C5j6fejZV1iIA:-N-3VEElBhwgK8UIE5is:b-8j33x9) ([raw file](https://github.com/robotlocomotion/drake/blob/fa7337befa35c374c0c91a9b8f94b9bec67c36af/multibody/parsing/test/detail_urdf_geometry_test.cc#L260)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

TIL
</blockquote></details>

spooky, ain't it?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16910)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
