### PR TITLE
Update/fix osx_cc_wrapper.sh

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7405)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Toward https://github.com/RobotLocomotion/drake/issues/7387

**Comment by jwnimmer-tri** [comment]
Also update `third_party/com_github_bazelbuild_bazel/vendor.txt`?

**Comment by soonho-tri** [comment]
> Also update third_party/com_github_bazelbuild_bazel/vendor.txt?

Updated.

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please.
+@jwnimmer-tri for platform-review, please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7405#-:-Ky3O5PvWJNcoPTROWbv:b-stsg9u)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7405#-:-Ky3ONq_pMKSZNa6Zy-e:b-96twws)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

For completeness, please cite the upstream bug report here once it happens.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7405#-:-Ky3PO9Uh4TTLIlU4dBb:b-lv2fvq)*

**Comment by soonho-tri** [comment]
I've added a comment at the upstream commit: bazelbuild/bazel@600ab49#commitcomment-25387448. I've added the link in the commit message, see https://github.com/RobotLocomotion/drake/pull/7405/commits/a6c64ba464ea4f8196ff6754771759387e5ba2ee. If I don't hear anything after a couple of days, I'll open a PR upstream.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7405#-:-Ky3TljTFBMpUuaZlYtR:b-kc7og2)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7405#-:-Ky3a-4RhbnrPbQrwjYM:bnfp4nl)*

**Pull request merged**
