### PR TITLE
pydrake: Collision filtering bindings

### PR DESCRIPTION
**Pull request by mntan3**
Added pydrake bindings needed for basic collision filtering in MBP and included a test

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13358)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI do you have cycles to review this?

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 243 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13358#-M7oHzwME9NLCqb4g5W3:-M7oVoB1-70SGJEDCy-_:b-3sj3zx) ([raw file](https://github.com/robotlocomotion/drake/blob/9329995a21073d511043847b56e8db57f8578a4b/bindings/pydrake/geometry_py.cc#L243)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This looks good to me. Nicely compact.

I note that the `AssignRole` bindings use lambdas to accomplish the same end. I wonder if that is merely a function of when things happened. @ericcousineau-tri could you weigh in on this?
</blockquote></details>

OK Not sure entirely what ya mean by "when things happen", but if you mean "when the C++ compiler throws a fit about stuff that looks like it should work", then yeah, basically, it's expected.
Here's a minor description of it:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeOverloads

Haven't decided to dig in any further, can't in the near future. Would love help to figure it out :)

Personally, don't really care as long as it's readable.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 243 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13358#-M7oHzwME9NLCqb4g5W3:-M7ob0uj209sigzi0uGP:b-xmhq1c) ([raw file](https://github.com/robotlocomotion/drake/blob/9329995a21073d511043847b56e8db57f8578a4b/bindings/pydrake/geometry_py.cc#L243)):*
OK Ah, gotcha. Yeah, possibly that the other lambdas didn't work, or possibly that I chose it arbitrarily (sorry!).

> Is there really no preference or standard in this regard?

Sorry, shouldn't have stated my personal preference ;)
We do have a standard, that's in the docs (in the link I sent).

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI you can click "reveal" to see if you're crazy or not ;)

image

**Pull request merged**
