### PR TITLE
Remove MATLAB ZMP example

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6369.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6378)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+(label: do not merge)
Blocked on #6367 and #6368 merging first.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.

**Comment by RussTedrake** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6378#-:-Kn1rcWBQsqdeC6IPX2A:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please.
-(status: do not merge)

**Comment by ggould-tri** [comment]
Zomp zomp.  :lgtm:

---

Reviewed 3 of 20 files at r1.
Review status: 3 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6378#-:-Kn9qY3uXNJANRabLyhn:b-tan8n5)*

**Comment by ggould-tri** [comment]
Reviewed 17 of 20 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6378)*

**Pull request merged**
