### PR TITLE
Updates Drake + ROS install instructions to include ROS Kinetic + Ubuntu 16.04

### PR DESCRIPTION
**Pull request by liangfok**
As promised, given the desire to transition to Ubuntu 16.04, this PR contains updated instructions on how to run Drake on ROS Kinetic on Ubuntu 16.04.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4538)

### CODE REVIEW

**Comment by liangfok** [comment]
+@naveenoid for feature review please since you're students are using Drake + ROS.
+@sherm1 for platform review per rotation schedule.

/CC: @patmarion - this PR contains the need to manually update the `LD_LIBRARY_PATH` and `PYTHONPATH` environment variables in Ubuntu 16.04. It would be great if this were not necessary.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-:-KZJ8AihqUFvxFcz5qlz:bftgxdu)*

**Comment by sherm1** [comment]
Platform: :lgtm:. Still needs feature review. I left a couple of ignorable BTWs.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source_ros_indigo.rst, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZKCPazVjvaqe8SbhiJ:-KZKCPb-4D4iKgmMZ_pn:bmzrzlb) ([raw file](https://github.com/robotlocomotion/drake/blob/de901c2bd8eafe90540eb13e3ebf347fdc0fa3fa/drake/doc/from_source_ros_indigo.rst#L11)):*
> ```reStructuredText
> Step 1: Install Prerequisites
> =============================
> ```

BTW, extra blank line I think.

---

*[drake/doc/from_source_ros_kinetic.rst, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZKCukRH9lCGMXUTu45:-KZKCukRH9lCGMXUTu46:bmzrzlb) ([raw file](https://github.com/robotlocomotion/drake/blob/de901c2bd8eafe90540eb13e3ebf347fdc0fa3fa/drake/doc/from_source_ros_kinetic.rst#L12)):*
> ```reStructuredText
> =============================
> ```

BTW, extra blank line I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-:-KZKDFMRBpLtOEuxM9CL:b-mxpl02)*

**Comment by liangfok** [comment]
@sherm1, I addressed your comments. Thanks. Now waiting on a feature review from @naveenoid.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source_ros_indigo.rst, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZKCPazVjvaqe8SbhiJ:-KZLcw3U9JhbotpaJxsM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de901c2bd8eafe90540eb13e3ebf347fdc0fa3fa/drake/doc/from_source_ros_indigo.rst#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, extra blank line I think.
</blockquote></details>

Done.

---

*[drake/doc/from_source_ros_kinetic.rst, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZKCukRH9lCGMXUTu45:-KZLcxlEZi834ranwNYj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de901c2bd8eafe90540eb13e3ebf347fdc0fa3fa/drake/doc/from_source_ros_kinetic.rst#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, extra blank line I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-:-KZLdXS1X6jrN7xdTeC4:b-jlsn07)*

**Comment by naveenoid** [comment]
I have a couple of BTW comments. Otherwise :lgtm: 

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source_ros.rst, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZMRli8IUUPegNRdqKN:-KZMRli8IUUPegNRdqKO:bqk8xw1) ([raw file](https://github.com/robotlocomotion/drake/blob/22d4fdee99921781ebae29860faec3a4945232d4/drake/doc/from_source_ros.rst#L125)):*
> ```reStructuredText
> ----------------------------
> 
> To do a clean build, execute::
> ```

BTW: How about a comment here saying "also colloquially referred to as a `comprehensive nuke` by the Drake Development community"...I found it a useful instruction to give my students.

---

*[drake/doc/from_source_ros_indigo.rst, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZMSslGC89I0UAje9lm:-KZMSslGC89I0UAje9ln:b-qn0l9g) ([raw file](https://github.com/robotlocomotion/drake/blob/22d4fdee99921781ebae29860faec3a4945232d4/drake/doc/from_source_ros_indigo.rst#L56)):*
> ```reStructuredText
> 
>     cd ~/dev/drake_catkin_workspace/src
>     git clone git@github.com:RobotLocomotion/drake.git
> ```

BTW: Im slightly confused. If I were to follow these instructions verbatim starting from the main page at http://drake.mit.edu/from_source.html, 

when do I have to setup the remote URL to match my personal fork?
i.e. the instructions of  : 
git remote set-url origin git@github.com:[your github user name]/drake.git
git remote add upstream git@github.com:RobotLocomotion/drake.git
git remote set-url --push upstream no_push

Or is it obvious that these instructions can be followed anytime after the initial clone?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-:-KZMSg2ATya88wN1MKd8:b-lnc6fx)*

**Comment by liangfok** [comment]
I addressed all reviewer comments and am now waiting for CI to complete.

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source_ros.rst, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZMRli8IUUPegNRdqKN:-KZMY7CG_mWxN4bBKe8r:b-896fja) ([raw file](https://github.com/robotlocomotion/drake/blob/22d4fdee99921781ebae29860faec3a4945232d4/drake/doc/from_source_ros.rst#L125)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: How about a comment here saying "also colloquially referred to as a `comprehensive nuke` by the Drake Development community"...I found it a useful instruction to give my students.
</blockquote></details>

Done!

---

*[drake/doc/from_source_ros_indigo.rst, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-KZMSslGC89I0UAje9lm:-KZMXk3VAbcyG04eX_Nr:be6hj3w) ([raw file](https://github.com/robotlocomotion/drake/blob/22d4fdee99921781ebae29860faec3a4945232d4/drake/doc/from_source_ros_indigo.rst#L56)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Im slightly confused. If I were to follow these instructions verbatim starting from the main page at http://drake.mit.edu/from_source.html, 

when do I have to setup the remote URL to match my personal fork?
i.e. the instructions of  : 
git remote set-url origin git@github.com:[your github user name]/drake.git
git remote add upstream git@github.com:RobotLocomotion/drake.git
git remote set-url --push upstream no_push

Or is it obvious that these instructions can be followed anytime after the initial clone?
</blockquote></details>

Good question. I added the commands to establish the recommended configuration of remotes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4538#-:-KZMdVtoBQ8h2VqQslzw:b-icmjjw)*

**Pull request merged**
