### PR TITLE
Use the RK2 integrator in iiwa_wsg_simulation.

### PR DESCRIPTION
**Pull request by sammy-tri**
This was the default prior to #6677, and this should have been changed along with monolithic_pick_and_place demo in that PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7374)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@edrumwri for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-Kxj8WMN1aGWh42MfVTW:b-p4pzus)*

**Comment by edrumwri** [comment]
Would you mind adding a comment to the simulation saying why it is not using the default integrator?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-KxjlJlwuE_x7Tjx3DQR:-KxjlJlwuE_x7Tjx3DQS:b-9u6n9l) ([raw file](https://github.com/robotlocomotion/drake/blob/c92dec28b2c19d68655048b6ddc43b451e54604c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L118)):*
> ```cpp
>   // the table top exactly, it may start colliding the table (which is
>   // not good, as it will likely shoot off into space).
>   const Eigen::Vector3d kBoxBase(0.8, 0., kTableTopZInWorld + 0.1);
> ```

Why the change to these parameters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-KxjlNrqIFCOsMCdr-gX:b3aqqwm)*

**Comment by sammy-tri** [comment]
Not at all, but I'm afraid I won't be able to add a comment much more informative than "When using the default RK3 integrator, the simulation stops advancing when the gripper grasps the box."  Does that work for you?  Or is there some more specific language you might suggest?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-KxjlJlwuE_x7Tjx3DQR:-Kxmqyk4l95JjWeLeHcD:b7fz46b) ([raw file](https://github.com/robotlocomotion/drake/blob/c92dec28b2c19d68655048b6ddc43b451e54604c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L118)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why the change to these parameters?
</blockquote></details>

They should have been changed in #7339 but were missed there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-Kxmqg7dPJIzNXTPTX85:b-hdzpy3)*

**Comment by edrumwri** [comment]
You can say (per me) that the grasping makes the problem computationally stiff, which brings the default RK3 integrator to its knees. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-KxndPRTnRbLWucTcPw3:b-2juz3e)*

**Comment by sammy-tri** [comment]
Done.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-KxoPJO3zo2xwhBgGqtZ:b-896fix)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-KxokZUd-wyOW_2x7wCL:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-Kxs3k5Vn4S6kOcisoAh:b-gbk9vg)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-KxjlJlwuE_x7Tjx3DQR:-Kxs8rh-DGZ62wwpQ5bf:b-dujvdp) ([raw file](https://github.com/robotlocomotion/drake/blob/c92dec28b2c19d68655048b6ddc43b451e54604c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L118)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

They should have been changed in #7339 but were missed there.
</blockquote></details>

BTW that should be mentioned in the commit message lest future `git blame`rs become confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-Kxs66n4_Z1gM_6dxBgy:bnfp4nl)*

**Comment by ggould-tri** [comment]
(note however my comment below about commit message)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-:-Kxs99DY2_9bCpQdCeI9:bwjjmz5)*

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7374#-KxjlJlwuE_x7Tjx3DQR:-KxsEW4Il9KwHugvmn1k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c92dec28b2c19d68655048b6ddc43b451e54604c/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L118)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW that should be mentioned in the commit message lest future `git blame`rs become confused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7374)*

**Pull request merged**
