### PR TITLE
Add ConstructPlaneSearchProgram to CspaceFreeBox.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for review please, thanks!

You could skip the code change in cspace_free_polytope.cc and cspace_free_polytope_base.cc, I just moved the code from one file to another.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-:-NYYxhrh3mUjoV1QCGql:b-84b1h7)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-:-NZ3TaQb8fR0s-hjPaFT:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_box.cc` line 252 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZ3PO4l2hFCaVP8d4Lw:-NZ3PO4l2hFCaVP8d4Lx:b-d4rt90) ([raw file](https://github.com/RobotLocomotion/drake/blob/87cd596d8d3817ff04a548f59f707b3ec3eca492/geometry/optimization/cspace_free_box.cc#L252)):*
> ```cpp
>   }
>   DRAKE_DEMAND(gram_var_count == gram_vars.rows());
>   return ret;
> ```

My only comment is that a lot of this code seem copy and pasted from `cspace_free_polytope`. I am not sure if that is avoidable or if we would even want to avoid it. But perhaps some of these very large lambda functions can be moved either to internal or the base class.
___
*[`geometry/optimization/test/c_iris_test_utilities.cc` line 372 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZ3Q4s51dz_WliQ8DfX:-NZ3Q4s51dz_WliQ8DfY:b-q7syuj) ([raw file](https://github.com/RobotLocomotion/drake/blob/87cd596d8d3817ff04a548f59f707b3ec3eca492/geometry/optimization/test/c_iris_test_utilities.cc#L372)):*
> ```cpp
>     indeterminates_vec(indeterminate_count++) = v;
>   }
>   prog.AddIndeterminates(indeterminates_vec);
> ```

nit: you can directly call `prog.AddIndeterminates(p.indeterminates()` now.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`geometry/optimization/cspace_free_box.cc` line 252 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZ3PO4l2hFCaVP8d4Lw:-NZ8xa0w5I0b__DsLcxS:b-olb88m) ([raw file](https://github.com/RobotLocomotion/drake/blob/87cd596d8d3817ff04a548f59f707b3ec3eca492/geometry/optimization/cspace_free_box.cc#L252)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

My only comment is that a lot of this code seem copy and pasted from `cspace_free_polytope`. I am not sure if that is avoidable or if we would even want to avoid it. But perhaps some of these very large lambda functions can be moved either to internal or the base class.
</blockquote></details>

Thanks!

I think it is hard to refactor out the code into the base class CspaceFreePolytopeBase, because the code operate on objects (like CspaceFreePolytope::SeparationCertificate and CspaceFreeBox::SeparationCertificate), which internally has different data structures.

I re-wrote the part of the duplicated code to make it shorter, so hopefully it looks better.
___
*[`geometry/optimization/test/c_iris_test_utilities.cc` line 372 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZ3Q4s51dz_WliQ8DfX:-NZ8yIxe0B7I2aDmnlYh:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/87cd596d8d3817ff04a548f59f707b3ec3eca492/geometry/optimization/test/c_iris_test_utilities.cc#L372)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: you can directly call `prog.AddIndeterminates(p.indeterminates()` now.
</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for Wednesday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-:-NZY_p0a82tzh46Mh4Ej:b9q16kq)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few minor comments

> Reviewed 6 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-:-NZcJex33YZdjGtqCTbN:bef1vyz)* status: 7 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_box.h` line 136 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZc7oqI0DrdkATRojUS:-NZc7oqI0DrdkATRojUT:bd4ntvy) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/cspace_free_box.h#L136)):*
> ```objc
>     DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(SeparationCertificateProgram)
>     SeparationCertificateProgram() = default;
>     virtual ~SeparationCertificateProgram() = default;
> ```

minor: `virtual` doesn't make sense in a `final` struct since no one can override. Likely you meant `override` here instead?
___
*[`geometry/optimization/cspace_free_box.cc` line 148 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZc9DYp4f5og_ccHHwF:-NZc9DYp4f5og_ccHHwG:b-wqqsqf) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/cspace_free_box.cc#L148)):*
> ```cpp
>       s_for_plane_indices.begin(), s_for_plane_indices.end()};
>   VectorX<symbolic::Variable> s_for_plane(s_for_plane_indices.size());
>   for (int i = 0; i < static_cast<int>(s_for_plane_indices.size()); ++i) {
> ```

BTW you can use `ssize()` to avoid this ugly boilerplate



_Suggestion:_
```cpp
ssize(s_for_plane_indices)
```
___
*[`geometry/optimization/cspace_free_polytope_base.h` line 138 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZcAwSg4QevAXEhgvSD:-NZcAwSh6VJZdVbwjs1H:bird0dx) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/cspace_free_polytope_base.h#L138)):*
> ```objc
>   // Returns -1 if the pair is not in map_geometries_to_separating_planes_.
>   int GetSeparatingPlaneIndex(
>       const SortedPair<geometry::GeometryId>& pair) const;
> ```

minor: this is now in a `protected:` section (was private before move) -- is that intentional? If so it needs appropriate Doxygen.
___
*[`geometry/optimization/cspace_free_polytope_base.h` line 295 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZcBstb9LIz8bmosYCN:-NZcBstc1n46lceli9bZ:byicv8o) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/cspace_free_polytope_base.h#L295)):*
> ```objc
>       bool with_cross_y, int num_y);
> 
>   // Add the constraint that the polynomial represented by this Gram and
> ```

nit: Add -> Adds
___
*[`geometry/optimization/test/cspace_free_box_with_mosek_test.cc` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZcEuUwCxp_XcsykAD0:-NZcEuUwCxp_XcsykAD1:b-rp32xo) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/test/cspace_free_box_with_mosek_test.cc#L10)):*
> ```cpp
> namespace drake {
> namespace geometry {
> namespace optimization {
> ```

BTW conventional (and possibly better) to wrap test code in anonymous namespace. That eliminates any possibility that names introduced here could conflict with other names in Drake.
___
*[`geometry/optimization/test/cspace_free_box_with_mosek_test.cc` line 143 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZcGUqc3FmaOXETBNHx:-NZcGUqc3FmaOXETBNHy:b-h663sv) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/test/cspace_free_box_with_mosek_test.cc#L143)):*
> ```cpp
> 
>   {
>     // Test the program for polytopic geometris.
> ```

typo: geometris -> geometries
___
*[`geometry/optimization/test/cspace_free_box_with_mosek_test.cc` line 193 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZcGlAX4Og8ssssYCHF:-NZcGlAX4Og8ssssYCHG:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/test/cspace_free_box_with_mosek_test.cc#L193)):*
> ```cpp
> 
>   {
>     // Test the program for non-polytopic geometris.
> ```

typo

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658)* status: 1 unresolved discussion, missing label for release notes

___
*[`geometry/optimization/cspace_free_box.h` line 136 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19658#-NZc7oqI0DrdkATRojUS:-NZhCdXR-nxdilNtV2cS:bhqy2l7) ([raw file](https://github.com/RobotLocomotion/drake/blob/97ccfd60ed969b6da3e77b6097103da56b37457b/geometry/optimization/cspace_free_box.h#L136)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: `virtual` doesn't make sense in a `final` struct since no one can override. Likely you meant `override` here instead?
</blockquote></details>

I removed the `virtual` keyword.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19658)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
