### PR TITLE
When SWIG is absent, disable all bindings

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
When SWIG is absent, disable python bindings and matlab bindings.  For matlab bindings, all code and tests directly depend on the swig libraries, so are useless without it -- so disabling it should be no problem.

For python bindings, most code (and all tests) directly depend on the swig libraries, so are useless without it.  However, the files `pydrake/insource_path.py` and `pydrake/autogenerated_path.py` could conceivably be used by other code, even without the SWIG libraries present.

I'd argue that it's fair to ask someone to enable SWIG if they want those files, because the build system gymnastics to do a selective install seem difficult, and there is only small value to knowing the directory paths in python, without any other python code to be run.  We can revisit if need be -- either due to comments in this PR, or if future complaints are raised.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3028)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot linux-clang-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
@david-german-tri for all reviews and merge, please.

**Comment by jwnimmer-tri** [comment]
The `linux-clang-experimental-minimal` shows that the 6 tests in #2972 are still failing, but that the pydrake unit tests are no longer failing (not being run).

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3028#-:-KOBK8VTAJeYFhgRWr1a:1417088721)*

**Pull request merged**
