### PR TITLE
tutorials: Fix camera + robot positioning; show depth rendering

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Preview:
https://nbviewer.jupyter.org/github/EricCousineau-TRI/drake/blob/feature-render-touch-up/tutorials/rendering_multibody_plant.ipynb

Before:
> image

After:
> image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@benburchfiel-tri for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841#-:-Mkifi3z90tSfHpEhGtA:bt6k2bp)* status: LGTM missing from assignee BenBurchfiel-TRI, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BenBurchfiel-TRI)

**Review by BenBurchfiel-TRI — COMMENTED** [review]
Some (very) small nits, but :lgtm:, thanks Eric!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841#-:-MklpIee1EDsSofXyYfV:b-s1v4o9)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[tutorials/rendering_multibody_plant.ipynb, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkloBDw9fhrt7mouwT_:-MkloBDw9fhrt7mouwTa:b-slz4ts) ([raw file](https://github.com/robotlocomotion/drake/blob/1a8e9d1323e6198f9c03da6003c00b55d1801557/tutorials/rendering_multibody_plant.ipynb#L129)):*
> ```
>     "def colorize_depth(depth_m, invalid_color=(100, 0, 0)):\n",
>     "    assert depth_m.dtype in [np.float32, np.float64]\n",
>     "    invalid = (depth_m == 0) | ~np.isfinite(depth)\n",
> ```

nit: What about doing ```invalid = (depth_m <= 0) | ~np.isfinite(depth)```? Likely will never matter but it's perhaps safer.
___
*[tutorials/rendering_multibody_plant.ipynb, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15841#-Mklp1Tn8P7bb9gEqOrB:-Mklp1To7Zy7oDQZKkV1:b-rtw38) ([raw file](https://github.com/robotlocomotion/drake/blob/1a8e9d1323e6198f9c03da6003c00b55d1801557/tutorials/rendering_multibody_plant.ipynb#L384)):*
> ```
>     "fig, ax = plt.subplots(1, 3, figsize=(15, 10))\n",
>     "ax[0].imshow(color)\n",
>     "ax[1].imshow(colorize_depth(depth))\n",
> ```

Nit: In a perfect world you'd rely in a Matplotlib colormap, but it would make dealing with invalid depth slightly awkward so I think this way is fine.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BenBurchfiel-TRI)

___
*[tutorials/rendering_multibody_plant.ipynb, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkloBDw9fhrt7mouwT_:-Mkm2RQX6u6bWzTgaqPO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a8e9d1323e6198f9c03da6003c00b55d1801557/tutorials/rendering_multibody_plant.ipynb#L129)):*
<details><summary><i>Previously, BenBurchfiel-TRI wrote…</i></summary><blockquote>

nit: What about doing ```invalid = (depth_m <= 0) | ~np.isfinite(depth)```? Likely will never matter but it's perhaps safer.
</blockquote></details>

Done.
___
*[tutorials/rendering_multibody_plant.ipynb, line 384 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15841#-Mklp1Tn8P7bb9gEqOrB:-Mkm2SVaD9IsqJgCgr9r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a8e9d1323e6198f9c03da6003c00b55d1801557/tutorials/rendering_multibody_plant.ipynb#L384)):*
<details><summary><i>Previously, BenBurchfiel-TRI wrote…</i></summary><blockquote>

Nit: In a perfect world you'd rely in a Matplotlib colormap, but it would make dealing with invalid depth slightly awkward so I think this way is fine.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841#-:-Mkm3q9VA23jZpiIcuaZ:b-wcm2v)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @BenBurchfiel-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841#-:-MkmGkyQALHa5X62OOIf:bnfp4nl)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tutorials/rendering_multibody_plant.ipynb, line 101 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkmGIeh9APcbxVENrba:-MkmGIeh9APcbxVENrbb:b-r4hre9) ([raw file](https://github.com/robotlocomotion/drake/blob/085e1f7a75d21bd5809d4e9c7b8141870de31598/tutorials/rendering_multibody_plant.ipynb#L101)):*
> ```
>   },
>   {
>    "cell_type": "code",
> ```

Why does this open a new cell?  We're still in "helpers" land.  Did you want to put your _new_ helper into its own cell as well?  (Be consistent.)
___
*[tutorials/rendering_multibody_plant.ipynb, line 128 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkmDRnO4u2PsCsE6Hh2:-MkmDRnPA9KfJ5ZeiSln:bt6sdc6) ([raw file](https://github.com/robotlocomotion/drake/blob/085e1f7a75d21bd5809d4e9c7b8141870de31598/tutorials/rendering_multibody_plant.ipynb#L128)):*
> ```
>     "    return color_image\n",
>     "\n",
>     "def colorize_depth(depth_m, invalid_color=(100, 0, 0)):\n",
> ```

I don't understand what `_m` here denotes?  Is it supposed to indicate units of meters?  If so, then I think it's a fine name, but the docstring should mention it to forestall this confusion.
___
*[tutorials/rendering_multibody_plant.ipynb, line 137 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkmDgO654H61jFRbdxy:-MkmDgO654H61jFRbdxz:ba93rwv) ([raw file](https://github.com/robotlocomotion/drake/blob/085e1f7a75d21bd5809d4e9c7b8141870de31598/tutorials/rendering_multibody_plant.ipynb#L137)):*
> ```
>     "    assert depth_m.dtype in [np.float32, np.float64]\n",
>     "    invalid = (depth_m <= 0) | ~np.isfinite(depth)\n",
>     "    scale_m_min = np.min(depth[~invalid])\n",
> ```

I am having trouble understanding where the variable `depth` comes from.  (It also appears in the prior line, and the next line.)

Later: Aha! it's a global on L418.  Probably you don't want that here.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[tutorials/rendering_multibody_plant.ipynb, line 101 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkmGIeh9APcbxVENrba:-MknLNX07L6mr6XkV0Li:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/085e1f7a75d21bd5809d4e9c7b8141870de31598/tutorials/rendering_multibody_plant.ipynb#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why does this open a new cell?  We're still in "helpers" land.  Did you want to put your _new_ helper into its own cell as well?  (Be consistent.)
</blockquote></details>

Done.
___
*[tutorials/rendering_multibody_plant.ipynb, line 128 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkmDRnO4u2PsCsE6Hh2:-MknLOczEOwgMOioHE7G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/085e1f7a75d21bd5809d4e9c7b8141870de31598/tutorials/rendering_multibody_plant.ipynb#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand what `_m` here denotes?  Is it supposed to indicate units of meters?  If so, then I think it's a fine name, but the docstring should mention it to forestall this confusion.
</blockquote></details>

Done.
___
*[tutorials/rendering_multibody_plant.ipynb, line 137 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15841#-MkmDgO654H61jFRbdxy:-MknLPL91pv7v4AyNYVs:bq55fxh) ([raw file](https://github.com/robotlocomotion/drake/blob/085e1f7a75d21bd5809d4e9c7b8141870de31598/tutorials/rendering_multibody_plant.ipynb#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am having trouble understanding where the variable `depth` comes from.  (It also appears in the prior line, and the next line.)

Later: Aha! it's a global on L418.  Probably you don't want that here.
</blockquote></details>

Done. Oops!!!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15841)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),BenBurchfiel-TRI (waiting on @EricCousineau-TRI)

**Pull request merged**
