### PR TITLE
Bazel: Add LCM rules

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This adds build rules for:
- drake/lcmtypes
- drake/lcm
- drake/systems/lcm
- drake/automotive use of LCM

As with earlier PRs, I'm just doing the easy parts now, and staying away from macros until a larger whole-project review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4010)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVj_Kb0DID_iZftbxHC:b2w89jm) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
> ```
> new_http_archive(
>     name = "lcm",
>     url = "https://github.com/lcm-proj/lcm/archive/v1.3.1.zip",
> ```

This is a different revision than we use in CMake, right?  I can see the argument for using a release instead of bleeding-edge, since the changes we need in bleeding-edge are all CMake infrastructure TTBOMK.  However, I think consistency is more important, in case there are actual software differences too.

---

*[drake/lcm/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjcpfg8EMGkUyv-rXy:-KVjcpfg8EMGkUyv-rXz:b-bt9lun) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/drake/lcm/BUILD#L12)):*
> ```Python
>     name = "interface",
>     hdrs = [
>         "drake_lcm_interface.h",    
> ```

btw trailing whitespace

---

*[drake/lcm/BUILD, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjexUwgy-r7Hz0a7ZM:-KVjexUwgy-r7Hz0a7ZN:bdakbdh) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/drake/lcm/BUILD#L27)):*
> ```Python
> 
> cc_library(
>     name = "real",
> ```

I'd suggest just "lcm"

---

*[drake/lcm/BUILD, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjerlanVxdOB8CQg9E:-KVjerlbi3O-vKwQx6hl:b-oxjygj) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/drake/lcm/BUILD#L36)):*
> ":mock"

really?  Among other things this seems like a `testonly` violation; I don't understand why the build succeeds for me.

---

*[tools/lcm.bzl, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjak9aGeCt625Bg4K_:-KVjak9aGeCt625Bg4Ka:b-mgjq33) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L6)):*
> ```Python
> # See http://bazel.io/ .
> 
> def _lcm_srcs_to_hdrs(lcm_package, lcm_srcs):
> ```

function comments throughout this file, please?

---

*[tools/lcm.bzl, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjbfxiNzci7ZOHwX2_:-KVjbfxiNzci7ZOHwX2a:b7vkug5) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L16)):*
> ```Python
> def _lcmhpp_impl(ctx):
>     for lcm_src, output in zip(ctx.files.lcm_srcs, ctx.outputs.outs):
>         ctx.action(
> ```

Please explain somewhere that `ctx` is a Skylark thing: https://bazel.build/versions/master/docs/skylark/lib/ctx.html#action

---

*[tools/lcm.bzl, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjatXlPnfQ4sUy7l_N:-KVjatXm2RT_XiOZcDD7:b32vlz) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L21)):*
> ```Python
>             arguments = [
>                 "--cpp", "--cpp-std=c++11",
>                 # TODO(jwnimmer-tri) Replace "6" with len(lcm_package).
> ```

?!

---

*[tools/lcm.bzl, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_0RLR4vHlJAIRnH6:-KVj_0RLR4vHlJAIRnH7:bwtuq69) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L33)):*
> ```Python
>         "lcm_srcs": attr.label_list(allow_files = True),
>         "lcmgen": attr.label(
>             cfg = HOST_CFG, executable = True,
> ```

```
WARNING: /media/dgerman/ssd-build/4010/drake-distro/tools/lcm.bzl:32:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
```

---

*[tools/lcm.bzl, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjcVuueWROxyjhp13m:-KVjcVuvTtpsUW2UJ_Zx:b4sdugv) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L40)):*
> ```Python
> )
> 
> def lcm_cc_library(
> ```

Especially function comment for this, since it's API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVju3cgSMSC-GXQslpm:bj969n8) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This is a different revision than we use in CMake, right?  I can see the argument for using a release instead of bleeding-edge, since the changes we need in bleeding-edge are all CMake infrastructure TTBOMK.  However, I think consistency is more important, in case there are actual software differences too.
</details>
So I just tried to switch to git, but it turns out that `lcm-1.3.1.zip` provides `lcm_version.h`, and a naive Bazel build of lcm from git fails due to lacking it.   Thoughts on sticking with `git` and writing a genrule vs keep this PR as-is?

---

*[drake/lcm/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjcpfg8EMGkUyv-rXy:-KVjqla9kgAZwB-vznbJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/drake/lcm/BUILD#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw trailing whitespace
</details>
Done.

---

*[drake/lcm/BUILD, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjexUwgy-r7Hz0a7ZM:-KVjrQU018SrWjb6czJv:b-t20p1v) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/drake/lcm/BUILD#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I'd suggest just "lcm"
</details>
That lets `//drake/lcm` get you the real library, which only main programs will want, but I was worried that folks would (ab)use too widely as an abbreviation.  But, perhaps too early to worry about that.  Done.

---

*[drake/lcm/BUILD, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjerlanVxdOB8CQg9E:-KVjrucV7_jzrIYqkoup:bt2om4x) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/drake/lcm/BUILD#L36)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > ":mock"
> 
> really?  Among other things this seems like a `testonly` violation; I don't understand why the build succeeds for me.
</details>
Interesting.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by david-german-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVjwEZF0m1-qqAzeM9W:b-kyj79v) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> So I just tried to switch to git, but it turns out that `lcm-1.3.1.zip` provides `lcm_version.h`, and a naive Bazel build of lcm from git fails due to lacking it.   Thoughts on sticking with `git` and writing a genrule vs keep this PR as-is?
</details>
`lcm_version.h`  appears to be on-tree at head of master.  What am I missing?  https://github.com/lcm-proj/lcm/blob/master/lcm/lcm_version.h

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVkKKf1vXygHq4eVrtA:bpjw63x) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> `lcm_version.h`  appears to be on-tree at head of master.  What am I missing?  https://github.com/lcm-proj/lcm/blob/master/lcm/lcm_version.h
</details>
Oops, that one was a PEBKAC (forgot to add it to hdrs).  That I need to genrule `lcm_export.h` is the next problem, but I guess I'll just do that also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVkM1EjYzbEfbRuNN9u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Oops, that one was a PEBKAC (forgot to add it to hdrs).  That I need to genrule `lcm_export.h` is the next problem, but I guess I'll just do that also.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 4 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVkORUZkMEULS9UE7pf:b-ngewc4) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
> That I need to genrule lcm_export.h is the next problem, but I guess I'll just do that also.

BTW, "lcm_export.h" doesn't seem to appear anywhere in this PR.   Should that be a TODO in the vicinity of the LCM_PYTHON hack?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVkO116i8V1rzK2s1OJ:b-s794vx)*

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_Kb0DID_iZftbxHB:-KVkQb85aAR-faY1vX4i:b6nfsnp) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/WORKSPACE#L31)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > That I need to genrule lcm_export.h is the next problem, but I guess I'll just do that also.
> 
> BTW, "lcm_export.h" doesn't seem to appear anywhere in this PR.   Should that be a TODO in the vicinity of the LCM_PYTHON hack?
</details>
Alright.  I fixed it for real, which turned out to be easier than documenting the hack.

---

*[tools/lcm.bzl, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjbfxiNzci7ZOHwX2_:-KVkWn6oT7L0pNNtKG2a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L16)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please explain somewhere that `ctx` is a Skylark thing: https://bazel.build/versions/master/docs/skylark/lib/ctx.html#action
</details>
Done.

---

*[tools/lcm.bzl, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVj_0RLR4vHlJAIRnH6:-KVkNuI9OmYHMHUbI_uM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L33)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ```
> WARNING: /media/dgerman/ssd-build/4010/drake-distro/tools/lcm.bzl:32:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
> ```
</details>
Done.

---

*[tools/lcm.bzl, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjcVuueWROxyjhp13m:-KVkWktuqXsTJpmdOXt8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L40)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Especially function comment for this, since it's API.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/lcm.BUILD, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVkXCSaM2Dd4ZY4qaBU:-KVkXCSaM2Dd4ZY4qaBV:b312izu) ([raw file](https://github.com/robotlocomotion/drake/blob/e69ae56ad766bac3f2bbca0b2ef07feded608af6/tools/lcm.BUILD#L11)):*
> ```
> # contains preprocessor conditionals for library decoration settings, based on
> # what kindsof compilation step is being run.  For our Bazel build of LCM, we
> # don't want those values in a header file because set them directly via our
> ```

nit: we set

---

*[tools/lcm.bzl, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVkXZZtZyov0SZb7I9B:-KVkXZZtZyov0SZb7I9C:bkwt78s) ([raw file](https://github.com/robotlocomotion/drake/blob/e69ae56ad766bac3f2bbca0b2ef07feded608af6/tools/lcm.bzl#L61)):*
> ```Python
>     The lcm_package= string parameter must match the `package ...;` statement
>     in all of the `*.lcm` files in lcm_srcs.  The Bazel-standard includes= and
>     deps= parameters are passed through to cc_library after adding the items
> ```

BTW, I'm a little unclear when we would ever need this - it seems like it could only be used to do horrible things - but I guess it doesn't hurt to have the knob for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
*[tools/lcm.bzl, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVkXZZtZyov0SZb7I9B:-KVkZz3TEv4zj4Omex6O:bq687lr) ([raw file](https://github.com/robotlocomotion/drake/blob/e69ae56ad766bac3f2bbca0b2ef07feded608af6/tools/lcm.bzl#L61)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, I'm a little unclear when we would ever need this - it seems like it could only be used to do horrible things - but I guess it doesn't hurt to have the knob for now.
</details>
For deps part at least, imagine that one lcmtypes library depends on another lcmtypes library.  (Some of the lcmtypes I haven't ported yet do that, e.g. use libbot primitives.)  I don't think I have a use case for adding includes yet, but _shrug_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/lcm.BUILD, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVkXCSaM2Dd4ZY4qaBU:-KVkb6ItOf1FIaOLRIkg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e69ae56ad766bac3f2bbca0b2ef07feded608af6/tools/lcm.BUILD#L11)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: we set
</details>
Done.

---

*[tools/lcm.bzl, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjak9aGeCt625Bg4K_:-KVkmRS8o3KF0LvYQu_4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L6)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> function comments throughout this file, please?
</details>
Done.

---

*[tools/lcm.bzl, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVjatXlPnfQ4sUy7l_N:-KVkmSV0ymoqaXJtslJW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/370fdd34457a5be71c5d93a2276e87c0fbae3371/tools/lcm.bzl#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ?!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
BTW Why `+curate`?  Does that still apply?

---

Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVkmYMeEgn_QCGlklBe:bbzaexb)*

**Comment by david-german-tri** [comment]
-(status: curate commits before merging) 

---

Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVkpXI3iq6tyWk4gJDE:b-l70wzf)*

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri 

---

Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVl8XOufAQqI-NeW__0:bbpa3zd)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/lcm.bzl, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVlDE5GY0Lz6YAz50cu:-KVlDE5GY0Lz6YAz50cv:b-vt56av) ([raw file](https://github.com/robotlocomotion/drake/blob/4873f27ed4dd56e4e4b4147ff3734af41102ec86/tools/lcm.bzl#L66)):*
> ```Python
>         name,
>         lcm_package=None,
>         lcm_srcs=[],
> ```

Does Skylark have the mutable default value hazard that Python has? I don't know, but I'm trained to be suspicious of default lists.

 Also, why treat this parameter differently from includes and deps in this very same function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/lcm.bzl, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVlDE5GY0Lz6YAz50cu:-KVlk8difTm4pZcfmKuL:brm8li7) ([raw file](https://github.com/robotlocomotion/drake/blob/4873f27ed4dd56e4e4b4147ff3734af41102ec86/tools/lcm.bzl#L66)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Does Skylark have the mutable default value hazard that Python has? I don't know, but I'm trained to be suspicious of default lists.
> 
>  Also, why treat this parameter differently from includes and deps in this very same function?
</details>
(1) Only very narrowly.  After a certain point during build file analysis, mutable lists are frozen.  In any case, I agree best not to risk it, so I've removed it.

(2) Probably from the qt_moc rules that I cargo culted from.  I've replaced it with something more sensible IMO.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by rpoyner-tri** [comment]
What bazel version are you using? I'm seeing warnings when I build, and I wonder if I have a different/newer version.

I have bazel 0.3.1, and I'm seeing:

```
WARNING: /home/rico/checkout/drake-distro/externals/gflags/BUILD:40:16: in includes attribute of cc_library rule //externals/gflags:gflags: 'include' resolves to 'externals/gflags/include' not in 'third_party'. This will be an error in the future.
WARNING: /home/rico/checkout/drake-distro/drake/lcmtypes/BUILD:27:1: in includes attribute of cc_library rule //drake/lcmtypes:iiwa: '.' resolves to 'drake/lcmtypes' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'lcm_cc_library', the error might have been caused by the macro implementation in /home/rico/checkout/drake-distro/tools/lcm.bzl:110:18.
WARNING: /home/rico/checkout/drake-distro/drake/lcmtypes/BUILD:9:1: in includes attribute of cc_library rule //drake/lcmtypes:drake_signal: '.' resolves to 'drake/lcmtypes' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'lcm_cc_library', the error might have been caused by the macro implementation in /home/rico/checkout/drake-distro/tools/lcm.bzl:110:18.
WARNING: /home/rico/checkout/drake-distro/drake/lcmtypes/BUILD:15:1: in includes attribute of cc_library rule //drake/lcmtypes:automotive: '.' resolves to 'drake/lcmtypes' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'lcm_cc_library', the error might have been caused by the macro implementation in /home/rico/checkout/drake-distro/tools/lcm.bzl:110:18.
```

Have you seen these?

---

Reviewed 2 of 13 files at r1, 3 of 4 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVp5gIHZaKYpA5mWKEM:b9x8wi7)*

**Comment by jwnimmer-tri** [comment]
Yes, those also occur for me.  I also have 0.3.1.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVp6_FTx1cmo6BzpuR_:b-s218c9)*

**Comment by rpoyner-tri** [comment]
ok then. :lgtm: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVp7562246TX7BtmiaR:bqg2que)*

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 13 files at r1, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/test/BUILD, line 13 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVpK3fRSDZuwyzu-0M-:-KVpK3fS6BWbczGXkpBD:bsq7a68) ([raw file](https://github.com/robotlocomotion/drake/blob/b3ddd7a345135aa3c1415a1200b767857b591710/drake/systems/lcm/test/BUILD#L13)):*
> ```Python
>     "//drake/systems/lcm:lcmt_drake_signal_translator",
>     "@gtest//:main"]
> cc_test(
> ```

blank lines between stanzas? please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by jwnimmer-tri** [comment]
Review status: 9 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/test/BUILD, line 13 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-KVpK3fRSDZuwyzu-0M-:-KVpYCTAYSYx7RAnia0J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3ddd7a345135aa3c1415a1200b767857b591710/drake/systems/lcm/test/BUILD#L13)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> blank lines between stanzas? please?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVpg1h4u3isW8R2zT3J:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4010#-:-KVzADjAR-cMTtkv7dUe:bnfp4nl)*

**Pull request merged**
