### PR TITLE
[multibody] Fix to enable Expression in MakeFromCentralInertia

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@ggould-tri  for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469#-:-Muf_SelCB8owtT9he9n:b-ophmop)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469#-:-MukliG93OQOughBedlZ:bnfp4nl)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[multibody/tree/test/spatial_inertia_test.cc, line 570 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16469#-MuklPY_0e92CVdJjCLH:-MuklPY_0e92CVdJjCLI:bj27cys) ([raw file](https://github.com/robotlocomotion/drake/blob/c8076c36b8961bd984f97374b41a55eb2a559196/multibody/tree/test/spatial_inertia_test.cc#L570)):*
> ```cpp
> 
> // Ensure that MakeFromCentralInertia works for Expression.  This test
> // represents a minimal reproduction from a user issue.
> ```

minor:  Is it possible to link to the user issue here?  If it isn't already archived, copy-paste it to an issue and immediately close it to get a permalink?

**Review by ggould-tri — COMMENTED** [review]
+(release notes: yes) -(release notes: none) This can go in the bugfixes section of the relnotes with no further work.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469#-:-Mukm12U5fdC5AW3xWuv:bthajc4)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
___
*[multibody/tree/test/spatial_inertia_test.cc, line 570 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16469#-MuklPY_0e92CVdJjCLH:-Mul770o9wpAAbQTLjl0:b-20pvl2) ([raw file](https://github.com/robotlocomotion/drake/blob/c8076c36b8961bd984f97374b41a55eb2a559196/multibody/tree/test/spatial_inertia_test.cc#L570)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Is it possible to link to the user issue here?  If it isn't already archived, copy-paste it to an issue and immediately close it to get a permalink?
</blockquote></details>

it was on slack, and I don't think making a new issue for it would add any information beyond what the test provides...?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469)* status: 2 unresolved discussions (waiting on @ggould-tri and @RussTedrake)

___
*[multibody/tree/unit_inertia.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16469#-Mul7nOt08U4xM-t3GGK:-Mul7nOu4Dpd1CihqI0-:btddu3j) ([raw file](https://github.com/robotlocomotion/drake/blob/c8076c36b8961bd984f97374b41a55eb2a559196/multibody/tree/unit_inertia.h#L95)):*
> ```objc
>   UnitInertia<T>& SetFromRotationalInertia(
>       const RotationalInertia<T>& I, const T& mass) {
>     if (!std::is_same_v<T, symbolic::Expression> && mass <= 0) {
> ```

nit When nerfing error checks that require direct conditional evaluation, we have a uniform spelling that we should use (see suggestion below).  We test type-traits vs `Expression` when we're dealing with types that `@tparam` opted out of.  When it's supported but nerfed, use `scalar_predicate` for clarity.



_Suggestion:_
```objc
scalar_predicate<T>::is_bool
```

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @RussTedrake)

___
*[multibody/tree/unit_inertia.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16469#-Mul7nOt08U4xM-t3GGK:-MulAT9TCWbzypuSl1M3:bb741sf) ([raw file](https://github.com/robotlocomotion/drake/blob/c8076c36b8961bd984f97374b41a55eb2a559196/multibody/tree/unit_inertia.h#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When nerfing error checks that require direct conditional evaluation, we have a uniform spelling that we should use (see suggestion below).  We test type-traits vs `Expression` when we're dealing with types that `@tparam` opted out of.  When it's supported but nerfed, use `scalar_predicate` for clarity.
</blockquote></details>

TIL!

**Comment by RussTedrake** [comment]
___
*[multibody/tree/unit_inertia.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16469#-Mul7nOt08U4xM-t3GGK:-MumY6lg-Zgv2tk_Efht:b1oapo6) ([raw file](https://github.com/robotlocomotion/drake/blob/c8076c36b8961bd984f97374b41a55eb2a559196/multibody/tree/unit_inertia.h#L95)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

TIL!
</blockquote></details>

I also didn't know we had that.  Just spent a few minutes reading about it.  I have to admit... I don't like it.  I think it's indirect and confusing (is it just me)?  Anybody that sees the `is_same_v` can understand it.  `scalar_predicate<T>::is_bool` is way more confusing.

I understand that the intent is to possibly support more types in the future.  But readability matters, too.  No?

Moreover, I think T==Expression is actually closer to what I want here that is_bool?   It's true that the error checking is guarded by a bool... but I would want to disable the error checking for Expression in any case.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469)* status: 1 unresolved discussion (waiting on @ggould-tri and @jwnimmer-tri)

___
*[multibody/tree/unit_inertia.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16469#-Mul7nOt08U4xM-t3GGK:-MumvuM57riaKI59_-B2:btti8yy) ([raw file](https://github.com/robotlocomotion/drake/blob/c8076c36b8961bd984f97374b41a55eb2a559196/multibody/tree/unit_inertia.h#L95)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I also didn't know we had that.  Just spent a few minutes reading about it.  I have to admit... I don't like it.  I think it's indirect and confusing (is it just me)?  Anybody that sees the `is_same_v` can understand it.  `scalar_predicate<T>::is_bool` is way more confusing.

I understand that the intent is to possibly support more types in the future.  But readability matters, too.  No?

Moreover, I think T==Expression is actually closer to what I want here that is_bool?   It's true that the error checking is guarded by a bool... but I would want to disable the error checking for Expression in any case. 
</blockquote></details>

per the discussion on slack, I've gone ahead with DRAKE_THROW_UNLESS instead.  Sorry to be picky!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @RussTedrake)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16469)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
