### PR TITLE
[tools] Attempt to fail-fast when violating ODR in pydrake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Discussed in [drakedevelopers#python](https://app.slack.com/client/T0JNB2DS4/CAHNDSJUB/thread/C3YB3EV5W-1637277861.042200).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri and +@EricCousineau-TRI for reviews, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129#-:-MostsKv2s7mH7V2AfgW:b-v6scke)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[tools/skylark/pybind.bzl, line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mostl0E5Dwif4plFFbA:-Mostl0E5Dwif4plFFbB:b-7eqlnf) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L105)):*
> ```Starlark
> def _check_cc_deps(*, cc_deps, testonly):
>     """Fails-fast in case of potential ODR violations."""
>     allowed_prefix = [
> ```

Unclear if this will allow `_pybind` header libraries to be used.

Should there be an `allowed_suffix` as well?
___
*[tools/skylark/pybind.bzl, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-MostAyzDrASwVHTGDVm:-MostAyzDrASwVHTGDVn:b-6vf5se) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L120)):*
> ```Starlark
>             "//common/test_utilities",
>             # TODO(jwnimmer-tri) This *definitely* violates ODR, but is not
>             # quite easy to remove from the once place it's currently used.
> ```

nit "once => one"
___
*[tools/skylark/pybind.bzl, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Most_MdBfllPB3tayjD:-Most_MdBfllPB3tayjE:b-yj2o5t) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L126)):*
> ```Starlark
>         if any([item.startswith(p) for p in allowed_prefix]):
>             continue
>         fail("Not allowed to link {} statically".format(item))
> ```

nit As a user, I will see the first bad condition, rather than all bad conditions. Consider printing enumeation.

From similar code in Anzu:
```
def _check_pybind_cc_deps(cc_deps):
    # Reject any pyinbd11 dependencies that may violate ODR.
    bad_cc_deps = []
    for cc_dep in cc_deps:
        if _valid_cc_dep(cc_dep):
            continue
        if cc_dep in _PYBIND_CC_DEP_ALLOWLIST:
            continue
        if cc_dep.endswith("_pybind"):
            continue
        bad_cc_deps.append(cc_dep)
    if bad_cc_deps:
        fail("The following pybind11 C++ dependencies are invalid due to " +
             "potential ODR violations: " + str(bad_cc_deps))
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @rpoyner-tri)

___
*[tools/skylark/pybind.bzl, line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mostl0E5Dwif4plFFbA:-Mosuvc292XwPSowi-QV:bvu81rx) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear if this will allow `_pybind` header libraries to be used.

Should there be an `allowed_suffix` as well?
</blockquote></details>

My understanding is that placing any such code outside of `@drake//bindings/pydrake` would be a code organization defect (though maybe not an ODR defect)?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with small nit

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129#-:-Mot0dpo9FvTS6h-qnm-:b-qo29t7)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[tools/skylark/pybind.bzl, line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mostl0E5Dwif4plFFbA:-Mot0Eiy9qbAndAVsv_j:bhs81wf) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My understanding is that placing any such code outside of `@drake//bindings/pydrake` would be a code organization defect (though maybe not an ODR defect)?
</blockquote></details>

Ah, missed part about prefix. Will mark myself satisfied on this point, but will bring up small secondary defect.
___
*[tools/skylark/pybind.bzl, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mot0tQl2msW2JoK3hMb:-Mot0tQmEPtjo4jy09i8:b-qjmi8p) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L107)):*
> ```Starlark
>     allowed_prefix = [
>         # The dep uses a fully-qualified path to pydrake.
>         "//bindings/pydrake",
> ```

nit Below, you use `//lcmtypes:` to constrain to subpackages, but here, it's allowed to be anything prefixed with this name. (Dunno why any cc dep would depend on roll-up, which is currently admitted here).

Consider specifying `//bindings/pydrake:`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[tools/skylark/pybind.bzl, line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mostl0E5Dwif4plFFbA:-Mot3BXn2H6WPlh5H3uC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, missed part about prefix. Will mark myself satisfied on this point, but will bring up small secondary defect.
</blockquote></details>

Done.
___
*[tools/skylark/pybind.bzl, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mot0tQl2msW2JoK3hMb:-Mot2-DT0iqLowJTjZKy:b-ki9o0x) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L107)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Below, you use `//lcmtypes:` to constrain to subpackages, but here, it's allowed to be anything prefixed with this name. (Dunno why any cc dep would depend on roll-up, which is currently admitted here).

Consider specifying `//bindings/pydrake:`
</blockquote></details>

I think here we _do_ want to allow sub-packages, which would be spelled like `//bindings/pydrake/stuff:foo` -- adding a colon here would require all helpers to be in the top-level pydrake package, which I don't think is what we want.  I've updated the comment to hopefully spell this out more clearly.

This discussion also made me realize that the lcmtypes are already part of libdrake, so we should _not_ be writing them down in pydrake bindings in the first place.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[tools/skylark/pybind.bzl, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16129#-Mot0tQl2msW2JoK3hMb:-Mot5SYHAKacrObLXHxx:b-vx6zlg) ([raw file](https://github.com/robotlocomotion/drake/blob/bc61e25ff4de6fcdb20aa995dc40a70ebf34859f/tools/skylark/pybind.bzl#L107)):*
OK Gotcha.

Intent could be made slightly more clear by allowing `//bindings/pydrake:` or `//bindings/pydrake/`, but will mark myself satisfied anywho.

> This discussion also made me realize that the lcmtypes are already part of libdrake, so we should not be writing them down in pydrake bindings in the first place.

Nice!

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16129#-:-MotcCEV56P8vHoC18Kb:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
