### PR TITLE
workspace: Upgrade pybind fork to use merge with latest upstream

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires:
- [x] https://github.com/RobotLocomotion/pybind11/pull/34

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12572)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
This upgrade is notably great because it allows for less-crappy error messages inside `PYBIND11_MODULE`, using this commit: https://github.com/pybind/pybind11/commit/bf2b031449c8c8156443655a80bdaf41433b2534

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
LGTM but will wait for RobotLocomotion/pybind11#34 to merge.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Pull request merged**
