### PR TITLE
system: Deprecate and rename ValidateChildOfContext()

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #12560

Resolves a review comment raised in PR #14378.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for feature review, as original plaintiff.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZomSbP8jZS0l6g_z5r:bc11xkt)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I scanned through the comments in #14378 but didn't find one that seemed relevant. Can you link to the specific comment? (The comment link hides under the date.)

Feature :lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZsIfTU4h7SM8RqkpwI:b-5h78wm)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Here's why: i swapped some digits. The correct PR is #14738 .

Exact comment was here: https://github.com/RobotLocomotion/drake/pull/14738#pullrequestreview-604408637

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZrvZr14nrI0P-bH-lj:b-qtg99h)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@sammy-tri for platform review, since today is my duty day.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZsTRgX9QhY1MuqT1Mb:b-7d600o)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sherm1 — COMMENTED** [review]
Oh, makes sense now! Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZsZFN_8NDtngtybH0X:b7earjj)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
-@sammy-tri +@jwnimmer-tri for load balancing, and since I know this area.

:lgtm platform.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZtEldHCZazsYYw6EvO:b-dpgpf6)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14999#-MZtEqDzDkDIhMZFbvXi:-MZtEqDzDkDIhMZFbvXj:bgdyuln) (no related file):*
nit Be sure to fix the issue number in the commit message while merging.

---

**Review by rpoyner-tri — COMMENTED** [review]
Sadly, your lgtm above has a typo, @jwnimmer-tri .
One more once?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14999#-:-MZtJluK1WBhju4gbpa6:b-tll2e1)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
:facepalm: :lgtm: :car: :emoji:

**Pull request merged**
