### PR TITLE
Migrate testDrakeGradientUtil to gtest. 

### PR DESCRIPTION
**Pull request by david-german-tri**
Delete some CPU-burning benchmarks, and delete some assertion-free tests.

@sammy-tri for both levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3892)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/test/testDrakeGradientUtil.cpp, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3892#-KUsm4lKLVrhwN37b4Bk:-KUsm4lLdVY3V613oQ1-:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/d0b1ab25a6ebe91c0048700339b1811ece7fe328/drake/util/test/testDrakeGradientUtil.cpp#L15)):*
> ```cpp
> 
> #include "drake/common/eigen_matrix_compare.h"
> #include "drake/common/test/measure_execution.h"
> ```

Unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3892)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3892)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/test/testDrakeGradientUtil.cpp, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3892#-KUsm4lKLVrhwN37b4Bk:-KUso4gJv81C6iCyvyKr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0b1ab25a6ebe91c0048700339b1811ece7fe328/drake/util/test/testDrakeGradientUtil.cpp#L15)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Unused?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3892)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3892#-:-KUsp85Wt91vhz8RMcub:bnfp4nl)*

**Pull request merged**
