### PR TITLE
Adds MultibodyPlant::MakeActuationMatrixInverse

### PR DESCRIPTION
**Pull request by RussTedrake**
+@sherm1 for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20975)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: but with a design question.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20975#-:-Nr2SxP6-kN25CLI1ZqX:bn3512z)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.h` line 4403 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20975#-Nr2P7SJDGCTd5NUlh2i:-Nr2P7SJDGCTd5NUlh2j:b-j8slm0) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d114426b772511593994d06e758b60f6d487e1a/multibody/plant/multibody_plant.h#L4403)):*
> ```objc
>   /// an explicit inverse calculation). See MakeActuationMatrix().
>   /// @throws std::exception if B is not a square and invertible matrix.
>   Eigen::SparseMatrix<double> MakeActuationMatrixInverse() const;
> ```

BTW it's not obvious to me why we have to enforce the "square and invertible" condition. We're just computing the transpose anyway so could return Bᵀ always, with it being B⁻¹ if B is square. I think Bᵀ would always be the pseudoinverse B⁺ of B when B isn't square. Bᵀ would be nu x nv and map some of the taus to their actuators, ignoring the others. Do you have a reason for prohibiting that? Maybe it is inherently useless for some reason? If not, consider relaxing this restriction.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20975)* status: needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.h` line 4403 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20975#-Nr2P7SJDGCTd5NUlh2i:-Nr5hak8BQz9WIfByP-K:bpc0jtj) ([raw file](https://github.com/RobotLocomotion/drake/blob/0d114426b772511593994d06e758b60f6d487e1a/multibody/plant/multibody_plant.h#L4403)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it's not obvious to me why we have to enforce the "square and invertible" condition. We're just computing the transpose anyway so could return Bᵀ always, with it being B⁻¹ if B is square. I think Bᵀ would always be the pseudoinverse B⁺ of B when B isn't square. Bᵀ would be nu x nv and map some of the taus to their actuators, ignoring the others. Do you have a reason for prohibiting that? Maybe it is inherently useless for some reason? If not, consider relaxing this restriction.
</blockquote></details>

Done.  Thanks!  I thought about this originally, too, and agree.  That's much better.

**Review by sherm1 — COMMENTED** [review]
Nice! +@ggould-tri for platform review per schedule, please

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20975#-:-Nr6S7zJCrIX9I2PmzgR:bbdi3o8)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; nice to have a break from grinding through today's 1200 line mega-PR :-)

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20975#-:-Nr6ppZY8v0SAr_tKRWV:bnr5i7w)* status: 1 unresolved discussion

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3291 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20975#-Nr6qXjK1G8cIYePq0Vk:-Nr6qXjK1G8cIYePq0Vl:b-xgj5as) ([raw file](https://github.com/RobotLocomotion/drake/blob/963e0c3113da81c41f159af354ddeff290d28022/multibody/plant/test/multibody_plant_test.cc#L3291)):*
> ```cpp
>   EXPECT_EQ(Bplus.rows(), nu);
>   EXPECT_EQ(Bplus.cols(), nv);
>   // since nv > nu, it's a true left inverse.
> ```

nit:  Isn't this condition `>=`?



_Suggestion:_
```cpp
>=
```

**Pull request merged**
