### PR TITLE
Use default autogenerated toolchain

### LINKED ISSUE #8684: Consider removing CROSSTOOL, pass required flags via `bazel.rc` if possible?
(Per conversations with @jamiesnape - just transcribing what I remember, but will definitely accept corrections to my understanding!)

Jamie has mentioned that our usage of `CROSSTOOL` could possibly be replaced by updating our `bazel.rc` flags. This could possibly help to better address issues like #7835, cache invalidation, etc. Additionally, the `CROSSTOOL` format seems like a moving target, frequently changes with Bazel releases, and the only documentation for this feature appears to be some `bazelbuild/bazel` Wiki entries.

Given that we're not doing any insane cross-compilation, we could possibly do away with it?

@jamiesnape Can I ask if this accurately describes what we have discussed? (And sorry for the delay in posting this!)

\cc @jwnimmer-tri

### PR DESCRIPTION
**Pull request by jamiesnape**
**Note this changes the default compiler to the system default, which is GCC rather than Clang on Ubuntu.**

FYI @EricCousineau-TRI. Closes #8684.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)

### CODE REVIEW

**Comment by jamiesnape** [comment]
An alternative may be to wrap something like https://github.com/bazelbuild/bazel/blob/master/tools/cpp/unix_cc_configure.bzl so still have a drake-specific CROSSTOOL, but it is autogenerated.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Once we have upgraded to Bazel 0.14.0, it looks like this should be ready.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
FYI Support for 0.14.1 has reached Drake master.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
LGTM, but I want to test locally on Ubuntu and with integrations at TRI before posting the emoji.

---

Reviewed 18 of 18 files at r1.
Review status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT3RIp6bRbz5sUnQNu:-LFT3RIp6bRbz5sUnQNv:bk71aiq) (no related file):*
Please double-check a `-packaging-` build result before merging.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT3V8A4AJ7O8F9hKy_:-LFT3V8A4AJ7O8F9hKya:bfxxwb3) (no related file):*
Please assign a macOS feature reviewer for local testing.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT3aRIC6CqrZtK1LBv:-LFT3aRIC6CqrZtK1LBw:b-r5zy33) (no related file):*
Needs platform review.

---

*[doc/bazel.rst, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT0Laf55KruTADWUNW:-LFT0Laf55KruTADWUNX:bhixoqy) ([raw file](https://github.com/robotlocomotion/drake/blob/849edfeffa9b20b9daf742de2506f8d3b60b05bb/doc/bazel.rst#L51)):*
> ```reStructuredText
>   bazel test //...                  # Build and test the entire project.
>   CC=clang-4.0 bazel build //...    # Build using Clang 4.0 on Xenial.
>   CC=clang-4.0 bazel test //...     # Build and test using Clang 4.0 on Xenial.
> ```

Our docs and CI should match.  This doc only sets `CC`; the CI configuration that is turned on by this PR [980f13a](https://github.com/RobotLocomotion/drake-ci/commit/980f13a8f9470ff190e6beac4d7abd3db9493ad4) sets both `CC` and `CXX`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881#-:-LFT14aX229G_dU897NR:by8ugnu)*

**Comment by jamiesnape** [comment]
+@soonho-tri for local mac testing.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental-snopt-packaging please

**Comment by jamiesnape** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT3V8A4AJ7O8F9hKy_:-LFT8u1DEZL8zA5Tq6pY:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please assign a macOS feature reviewer for local testing.
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT3RIp6bRbz5sUnQNu:-LFT8vCoCF7aYrYR0K8r:ba17pet) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please double-check a `-packaging-` build result before merging.
</blockquote></details>

Requested.

---

*[doc/bazel.rst, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFT0Laf55KruTADWUNW:-LFT8sj45l6rUOt8LESk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/849edfeffa9b20b9daf742de2506f8d3b60b05bb/doc/bazel.rst#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Our docs and CI should match.  This doc only sets `CC`; the CI configuration that is turned on by this PR [980f13a](https://github.com/RobotLocomotion/drake-ci/commit/980f13a8f9470ff190e6beac4d7abd3db9493ad4) sets both `CC` and `CXX`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[doc/bazel.rst, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTIPppCsFXPPAH2dDc:-LFTIPppCsFXPPAH2dDd:bmoowky) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/doc/bazel.rst#L41)):*
> ```reStructuredText
> 
> On Ubuntu Xenial, the default compiler is the first ``gcc`` compiler in the
> ``PATH``, usually GCC 5.4. On macOS, the default compiler is Apple Clang. To
> ```

CI settings and user settings should match.  In our `linux-xenial-gcc-*` CI, we set `CC=gcc-5` and `CXX=g++-5`, but here we've documented that for users Bazel will be using the first `gcc` on the path (which is true).

Since (I'd posit) we don't want to document that users set `CC=gcc` or `CC=/usr/bin/gcc` or whatever, I think CI should change to leave those unset when the compiler variant is the OS default.

I suspect this same line of reasoning applies on macOS as well, though I haven't checked)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jamiesnape** [comment]
Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[doc/bazel.rst, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTIPppCsFXPPAH2dDc:-LFTJvdG1CwKzUUoD8ar:b3yvfo0) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/doc/bazel.rst#L41)):*
>   I think CI should change to leave those unset when the compiler variant is the OS default.

I am not definitely not comfortable with that given we advertise those as GCC builds. I do not want a build silently calling back to clang or some other compiler if there is an issue with the image.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by soonho-tri** [comment]
@jamiesnape , `bazel build //...` completed without an error on a mac.

---

Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881#-:-LFTM9P-DIA6ZAF2a6yh:bcn0zgb)*

**Comment by jamiesnape** [comment]
Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[doc/bazel.rst, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTIPppCsFXPPAH2dDc:-LFTMDXT0wPmHSpAxDPm:bh2m84n) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/doc/bazel.rst#L41)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

>   I think CI should change to leave those unset when the compiler variant is the OS default.

I am not definitely not comfortable with that given we advertise those as GCC builds. I do not want a build silently calling back to clang or some other compiler if there is an issue with the image.
</blockquote></details>

(I would happily change CI to CC=gcc, though.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[doc/bazel.rst, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTIPppCsFXPPAH2dDc:-LFTLJiT122dHcjTWPEh:b-l3sg62) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/doc/bazel.rst#L41)):*
> ... silently calling back to clang or some other compiler ...

That is a fair point.  One solution would be to read back the selected compiler and make assertions in CI that we got what we wanted.  But I'm not wed to any particular solution, so long as the steps a user runs and steps CI runs are congruent.

I am not sure that `CC=gcc` in CI is good enough.  If we indicate the user they can leave it empty, it really seems like CI should do the same -- at least in a nightly or something.

---

*[tools/skylark/drake_cc.bzl, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTL-gOEe4VAbp0XSgQ:-LFTL-gQ-S8eFvUGMWLz:b-yyqvjd) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/tools/skylark/drake_cc.bzl#L60)):*
> ```Python
>         ),
>         "//tools/cc_toolchain:clang": (
>             CLANG_FLAGS + rule_copts + rule_clang_copts
> ```

On Ubuntu, when I set `CC=clang-4.0 CXX=clang++-4.0` and run a build, neither the CXX_FLAGS nor CLANG_FLAGS appear to be applied (tested by adding a malformed flag to those lists).  If I add the malformed flag to `conditions:default` below it triggers, so somehow the clang condition is not being matched.

(I'm still locally testing all of the other configs.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jwnimmer-tri** [comment]
*[tools/skylark/drake_cc.bzl, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTL-gOEe4VAbp0XSgQ:-LFTNibJ5P5XXqces2L_:btr60rl) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/tools/skylark/drake_cc.bzl#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On Ubuntu, when I set `CC=clang-4.0 CXX=clang++-4.0` and run a build, neither the CXX_FLAGS nor CLANG_FLAGS appear to be applied (tested by adding a malformed flag to those lists).  If I add the malformed flag to `conditions:default` below it triggers, so somehow the clang condition is not being matched.

(I'm still locally testing all of the other configs.)
</blockquote></details>

Similarly, if I add a bad flag to `GCC_FLAGS` or `CXX_FLAGS`, it does not get used no matter if I leave env unset, or set to `gcc`, or set to `gcc-5`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jamiesnape** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[tools/skylark/drake_cc.bzl, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTL-gOEe4VAbp0XSgQ:-LFTOFtoBOlfuGmKClqk:b5g81jr) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/tools/skylark/drake_cc.bzl#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Similarly, if I add a bad flag to `GCC_FLAGS` or `CXX_FLAGS`, it does not get used no matter if I leave env unset, or set to `gcc`, or set to `gcc-5`.
</blockquote></details>

I have a bad feeling that was not implemented (correctly) on the Bazel side. Just looking in their repo now to be sure. Certainly the platform constraints are good, but the compiler ones are looking less promising.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[doc/bazel.rst, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTIPppCsFXPPAH2dDc:-LFTUxpH8RcsnWx93eWz:bdr3uom) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/doc/bazel.rst#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... silently calling back to clang or some other compiler ...

That is a fair point.  One solution would be to read back the selected compiler and make assertions in CI that we got what we wanted.  But I'm not wed to any particular solution, so long as the steps a user runs and steps CI runs are congruent.

I am not sure that `CC=gcc` in CI is good enough.  If we indicate the user they can leave it empty, it really seems like CI should do the same -- at least in a nightly or something.
</blockquote></details>

I guess I could live with `CC=gcc` in CI as a stepping stone (or even with `CC=gcc-5`), assume there's an issue / TODO to resolve this more permanently within a few weeks in a follow-up.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jwnimmer-tri** [comment]
In the meantime, if you want to, I think we could merge in another PR:
- Remove CMake-specific compiler wrapper and relocate template for bazelrc file
- Use platform constraint value to identify operating system rather than cpu value

and most of the
- Move C++14 flags from CROSSTOOL to bazel.rc

---

Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881#-:-LFTf3O5AI0gGi20NQFN:b-ofzbcm)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

---

*[tools/skylark/drake_cc.bzl, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8881#-LFTL-gOEe4VAbp0XSgQ:-LFXYT8DCP2475GP_nI7:b-ucfkn4) ([raw file](https://github.com/robotlocomotion/drake/blob/29ba75c643720e96188ed213d2952604b084a63c/tools/skylark/drake_cc.bzl#L60)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I have a bad feeling that was not implemented (correctly) on the Bazel side. Just looking in their repo now to be sure. Certainly the platform constraints are good, but the compiler ones are looking less promising.
</blockquote></details>

Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8881)*

**Comment by jamiesnape** [comment]
Resolved merge conflicts. Probably need to write our own compiler detection since Bazel does not actually do so itself.

**Comment by jamiesnape** [comment]
I have a solution, but it would mean losing the unused parameters `clang_copts` and `gcc_copts` on the various rules, at least in the interim, since it does the compiler detection within a repository rule.

**Comment by jwnimmer-tri** [comment]
A repository rule can output constants, though.  Just emit a BUILD.bazel file with `IS_GCC = True` or etc.  Then the `drake_cc.bzl` code can `load()` the constants and use if-else logic to concatenate options?

**Comment by jamiesnape** [comment]
Yes, for some reason I was thinking that would not work, but it should be fine.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Install test is not happy on Mac, strangely enough. Worked fine locally.

**Comment by jamiesnape** [comment]
Apparently the install tests are broken in `master` too, so this PR is not to blame.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Forcing a rebuild of the documentation so people have up-to-date instructions for changing compiler.

**Pull request merged**
