### PR TITLE
Add and document CLion/Bazel integration.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4814)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-Kang1lvaFRxdx2BQbvJ:-Kang1lvaFRxdx2BQbvK:bus39u7) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L164)):*
> to to
Repeated word.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/clion.rst, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KaniQrGLDJLHYiF6-mF:-KaniQrHyQcWcED62XX-:bh3onij) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L82)):*
> ```reStructuredText
> 2. Click an executable, or start typing to find your favorite executable and hit enter.
> 
> Debugging .mex functions in OSX
> ```

Does this only work in OSX?

---

*[drake/doc/clion.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KanhqxH_T3lq7Wr3_e_:-KanhqxH_T3lq7Wr3_ea:b-fbdp5b) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L93)):*
> ```reStructuredText
> 6. Browse to your Matlab executable. For OSX you can just use
>    Applications/MATLAB_R2014a.app or something similar.
> 7. As the working directory, use /Users/twan/code/drake-distro/drake (adapted
> ```

This would normally be represented in some `$HOME/drake-distro/drake` or `$DRAKE_DISTRO/drake` kind of way.  In particularly we use something so specific?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/clion.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KanhqxH_T3lq7Wr3_e_:-KanjYgSCFjQ_SG-sHG8:b-y2lmlw) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L93)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This would normally be represented in some `$HOME/drake-distro/drake` or `$DRAKE_DISTRO/drake` kind of way.  In particularly we use something so specific?
</blockquote></details>

I think this just relocates pre-existing text.  Would be okay to leave it alone in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/clion.rst, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KaniQrGLDJLHYiF6-mF:-KanjmBkQBstEnGt0urN:b-y2lmlw) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L82)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Does this only work in OSX?
</blockquote></details>

I think this just relocates pre-existing text.  Would be okay to leave it alone in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KaniQrGLDJLHYiF6-mF:-KankEi9Ui_eJ1mlgqfw:b-txc6cz) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this just relocates pre-existing text.  Would be okay to leave it alone in this PR?
</blockquote></details>

Absolutely. I realized belatedly that I'd forgotten the BTW.  (Although, if it's relocated, how come the deletion isn't included in this PR?)

---

*[drake/doc/clion.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KanhqxH_T3lq7Wr3_e_:-KankNXDfHJtH1y4IX1W:b-beshme) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L93)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this just relocates pre-existing text.  Would be okay to leave it alone in this PR?
</blockquote></details>

Same answer.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/clion.rst, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KaniQrGLDJLHYiF6-mF:-KanlHjW6QQSO5RCi6_T:bxjwxna) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L82)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Absolutely. I realized belatedly that I'd forgotten the BTW.  (Although, if it's relocated, how come the deletion isn't included in this PR?)
</blockquote></details>

It is, in the "prior revision" (left side) of this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KaniQrGLDJLHYiF6-mF:-KanmFuBEo7Li9clcVOt:b-sfck0d) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is, in the "prior revision" (left side) of this file?
</blockquote></details>

Oh...you mean if I scroll ALL the way down.  Yeah, I can see that would help.  :")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by david-german-tri** [comment]
+@lucy-tri, I've applied the improvements from our in-person review.  also, +@jwnimmer-tri for platform review.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-KanhqxH_T3lq7Wr3_e_:-KanmEl13ltc91W4qwlx:b-38wd93) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L93)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Same answer.  :)
</blockquote></details>

This is egregious enough that I'm going to fix it anyway.  Done.

---

*[drake/doc/clion.rst, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-Kang1lvaFRxdx2BQbvJ:-KanmMJ3uVb7YzTcWmkl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9184bef6bd78308436d9759cce943adf3aa0d96e/drake/doc/clion.rst#L164)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

> to to
Repeated word.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-:-Kanp-9TlK5z59Cz_8t5:b-crrbth)*

**Comment by SeanCurtis-TRI** [comment]
I'm content; I'll stay out of the way.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-:-Kanpdgz_FBcdbT7tVJo:b-x4i3uw)*

**Comment by jwnimmer-tri** [comment]
:lgtm:  I didn't test it locally.  I figure this is likely close enough (and its just a doc), and we can PR fixups as we find them.

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.bazelproject, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-Kao505PbUICl2fN7wLT:-Kao505PbUICl2fN7wLU:bv1cw8t) ([raw file](https://github.com/robotlocomotion/drake/blob/c4072e02c3689c1d535fc2b68b5ca6e882e4f583/.bazelproject#L1)):*
> ```
> 
> ```

BTW Is there an allowed comment syntax, where the purpose of this file can be communicated to someone who stumbles across it, or wants to edit it?

---

*[drake/doc/clion.rst, line 188 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-Kao6gZIWWHR5BQbaOgx:-Kao6gZIWWHR5BQbaOgy:b-tu6uvk) ([raw file](https://github.com/robotlocomotion/drake/blob/c4072e02c3689c1d535fc2b68b5ca6e882e4f583/drake/doc/clion.rst#L188)):*
> ```reStructuredText
> ``Bazel > Sync Project With BUILD Files``.
> ```

BTW double blank line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-:-Kao6uh9uM1T-gTdgkCr:bglpjak)*

**Comment by david-german-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[.bazelproject, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-Kao505PbUICl2fN7wLT:-Kar9kTx-wObY6TnMklU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4072e02c3689c1d535fc2b68b5ca6e882e4f583/.bazelproject#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there an allowed comment syntax, where the purpose of this file can be communicated to someone who stumbles across it, or wants to edit it?
</blockquote></details>

Done.

---

*[drake/doc/clion.rst, line 188 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-Kao6gZIWWHR5BQbaOgx:-Kar853nuz-4hOnBdzTM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4072e02c3689c1d535fc2b68b5ca6e882e4f583/drake/doc/clion.rst#L188)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW double blank line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814)*

**Comment by david-german-tri** [comment]
I'm going to -@Lucy-tri and merge, since we had a positive f2f review yesterday, and it's getting really annoying that `.bazelproject` disappears when I switch away from this branch.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-:-KarBi2BjRx3aIxwKjm3:bma5ezs)*

**Comment by david-german-tri** [comment]
Override-merging because no CI impact.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4814#-:-KarBtbrnjaIzmA9uWG5:br7ff4c)*

**Pull request merged**
