### PR TITLE
First pass at public `maliput` design document.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5603)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@jwnimmer-tri for "honk honk" review.  I'm not sure who else should review this at this point.  At _some_ point, we should have it reviewed by someone with (near)zero-knowledge of `maliput` but some working knowledge of differential geometry, to make sure it has no technical gaffes yet also explains what is going on.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5603#-:-KfvtnyywrzcjVJ-CWKc:b9neu3f)*

**Comment by jwnimmer-tri** [comment]
:car: honk honk
:lgtm: platform

I am open to different workflow ideas.

I think merging this now would be okay, and then we iterate it into Doxygen, add images, and then do a full re-review at the end.

If you're rather have one feature-review pass over the prose now, that's okay too.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5603#-:-KfxU3pzQnPi72ZpgKcP:b-fd26vd)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Comment by maddog-tri** [comment]
FYI:  I'm just gonna merge it as is.  Then I can collect feedback from anyone who happens to read it while I draw figures and/or it becomes Doxygenated.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5603#-:-Kg0YRgXRgGzIrCaU196:bml054h)*

**Comment by liangfok** [comment]
I'll take a look at this over the weekend.

**Comment by maddog-tri** [comment]
ps:  This contributes to #5116.  Ongoing feedback should be posted there.

**Pull request merged**
