### PR TITLE
[workspace] Straighten out repo rules for MOSEK, TBB, OpenUSD

### LINKED ISSUE #20233: [workspace] Use package.BUILD.bazel uniformly, not repo_ctx.file
See #20230.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20898.

Closes #20233 (incidentally).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri how is your feature-review bandwidth these days?  We could also pass this along to Xuchen if you prefer.

**Review by rpoyner-tri — COMMENTED** [review]
I'll give a look, and delegate if needed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-:-NtN2BQo-30G-Y8Zts0P:bxuqk90)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
I'm good -- still looking at the mosek-salad refactorings.

> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-:-NtN3YsQ9RQj-kl98HvR:b-xovssu)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-:-NtN7h982x-L9yYKX99f:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review (tomorrow), please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-:-NtOR33w7_6Upggnapti:bg7igkv)* status: 3 unresolved discussions

___
*[`tools/skylark/cc.bzl` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOFZ-VA7BDqMKbnU9x:-NtOFZ-VA7BDqMKbnU9y:bur0n12) ([raw file](https://github.com/RobotLocomotion/drake/blob/eec20faba4dc8086c04d67e9c2fa2377961a4b5c/tools/skylark/cc.bzl#L17)):*
> ```Starlark
> 
> def cc_import(**kwargs):
>     native.cc_input(**kwargs)
> ```

BTW, this never yelled because we never do `cc_import` before?

A search on the current master shows one use though.
___
*[`tools/workspace/mosek/repository_impl.bzl` line 77 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOQdul76Dbox9FfYy4:-NtOQdul76Dbox9FfYy5:bv89lpi) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a095453ebfb38dafb8bf149e2b5dda2c289d8d/tools/workspace/mosek/repository_impl.bzl#L77)):*
> ```Starlark
> 
>     # Add the BUILD file.
>     repo_ctx.symlink(
> ```

BTW, I'm not understanding what this is doing here. Can you explain? What happens to the BUILD.bazel file that already exists? What does `Label` do exactly? https://bazel.build/rules/lib/builtins/Label isn't particularly helpful.
___
*[`tools/workspace/onetbb_internal/package.BUILD.bazel` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOIKgTDBGr6mQaxYdD:-NtOIKgTDBGr6mQaxYdE:bgpfrv8) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a095453ebfb38dafb8bf149e2b5dda2c289d8d/tools/workspace/onetbb_internal/package.BUILD.bazel#L17)):*
> ```
>     ],
>     deps = [
>         "@mosek//:tbb",
> ```

BTW, I'm confused by this. Why are we using the headers from oneapi but the library from mosek (instead of building from source)? Is it just for convenience?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155)* status: 2 unresolved discussions

___
*[`tools/skylark/cc.bzl` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOFZ-VA7BDqMKbnU9x:-NtRSlvdCaUCTVfS_NkY:boal9fu) ([raw file](https://github.com/RobotLocomotion/drake/blob/eec20faba4dc8086c04d67e9c2fa2377961a4b5c/tools/skylark/cc.bzl#L17)):*
> This never yelled because we never do `cc_import` before?

Correct.

> A search on the current master shows one use though.

The tools/install/drake.BUILD.bazel calls the `native.cc_import` not this alias (because it doesn't import this file).
___
*[`tools/workspace/mosek/repository_impl.bzl` line 77 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOQdul76Dbox9FfYy4:-NtRTOwh0nkwfV8ImWaX:b8sy8v1) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a095453ebfb38dafb8bf149e2b5dda2c289d8d/tools/workspace/mosek/repository_impl.bzl#L77)):*
FYI https://bazel.build/rules/lib/builtins/repository_ctx#symlink for reference.  The `target` of the symlink can be spelled in several different ways.  We can symlink to a relative path filename, but in this case we want the symlink to point to our file as named by a label (https://bazel.build/concepts/labels).

> What happens to the BUILD.bazel file that already exists?

The MOSEK tarball doesn't have any build file.

Maybe I can clarify what this is doing?  It's creating a file named `BUILD.bazel` in the mosek external which is a symlink pointing to `drake/tools/workspace/mosek/package.BUILD.bazel`.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155)* status: 1 unresolved discussion

___
*[`tools/workspace/mosek/repository_impl.bzl` line 77 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOQdul76Dbox9FfYy4:-NtRtAW241tf-m84wya8:b-9dr20u) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a095453ebfb38dafb8bf149e2b5dda2c289d8d/tools/workspace/mosek/repository_impl.bzl#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI https://bazel.build/rules/lib/builtins/repository_ctx#symlink for reference.  The `target` of the symlink can be spelled in several different ways.  We can symlink to a relative path filename, but in this case we want the symlink to point to our file as named by a label (https://bazel.build/concepts/labels).

> What happens to the BUILD.bazel file that already exists?

The MOSEK tarball doesn't have any build file.

Maybe I can clarify what this is doing?  It's creating a file named `BUILD.bazel` in the mosek external which is a symlink pointing to `drake/tools/workspace/mosek/package.BUILD.bazel`.
</blockquote></details>

I see. My confusion was with the BUILD.bazel file in `drake/tools/workspace/mosek`. If IIUC now, this is a different BUILD file in the external mosek repo.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21155)* status: 1 unresolved discussion

___
*[`tools/workspace/onetbb_internal/package.BUILD.bazel` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21155#-NtOIKgTDBGr6mQaxYdD:-NtSCV2g2EDdDLvL5uwI:br452j1) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a095453ebfb38dafb8bf149e2b5dda2c289d8d/tools/workspace/onetbb_internal/package.BUILD.bazel#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm confused by this. Why are we using the headers from oneapi but the library from mosek (instead of building from source)? Is it just for convenience?
</blockquote></details>

Working

I need to add better comments to these files to explain this.  We use the MOSEK copy of TBB because that's what we've always been using, because it's the version that MOSEK was built & tested against, and because compiling TBB with bazel is probably not a lot of fun.

**Pull request merged**
