### PR TITLE
InverseKinematics: set non-zero initial guess for quaternion joints.

### LINKED ISSUE #17726: Initialize the floating base quaternion to non-zero value in IK
Currently in InverseKinematics class, for each floating base, we add a constraint `zᵀz = 1` for its quaternion `z`. On the other hand, we initialize all decision variables to 0 by default. This is a very bad initialization for quaternions, as the gradient of the constraint `zᵀz-1 = 0` is 0 at this initialization `z=0`, hence the gradient-based optimizer will likely get stuck here.

I propose that when we add the constraint `zᵀz=1`, we also set the initial guess of `z` to a non-zero value, for example [1, 0, 0, 0].

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #17726.

+@hongkai-dai for feature review, please.
cc @cohnt

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20624)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-:-NkmO4JWA_ZxJ4La-fh8:buxscyd)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Comment by jwnimmer-tri** [comment]
Reminder ping @RussTedrake this is on your plate.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20624)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-NkpMyNS0O3UmfCtZA4M:-NnawVS10B44U3ejozJh:baj707t) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Possibly the documentation in `unit_quaternion_constraint.h` should remind users to set the default value.  I even wonder if `AddUnitQuaternionConstraintOnPlant` should change the initial guess, even though that might trump the users existing guess.  Maybe only change the guess in case when was singular?
</blockquote></details>

Done.  I've implemented this, but only changed the initial guess if it was not previously set.

___
___
*[`multibody/inverse_kinematics/test/inverse_kinematics_test.cc` line 186 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-NkpNUJv73fiJoeYE874:-Nnaxdh-5EEVDaejs1h9:bs7wumx) ([raw file](https://github.com/RobotLocomotion/drake/blob/7a50eaa51aaa869b7b816538c1f41260abb7fa83/multibody/inverse_kinematics/test/inverse_kinematics_test.cc#L186)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This says "un-normalized" but it's normalized now.  I think the intent of the test was to check that a locked quat joint properly calls `normalized` internally, which we've lost now.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20624)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-NnbZR_F6nuleV4zCl9G:-NnbZR_F6nuleV4zCl9H:bvdbi0) (no related file):*
@hongkai-dai please re-feature-review the new edits.

___
___
*[`multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-NnbZGSN43bZZVIL-mXE:-NnbZGSN43bZZVIL-mXF:bmu333i) ([raw file](https://github.com/RobotLocomotion/drake/blob/a0afd61eee5455e3f9a601a3b7e811db590f208f/multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc#L53)):*
> ```cpp
>       q.segment<4>(plant_->GetBodyByName("body1").floating_positions_start()),
>       body1_guess);
>   log()->info("{}", fmt_eigen(prog.initial_guess()));
> ```

nit Stray debugging?

(It would be OK to log in a unit test, but in that case it should have some extra text ahead of the value so it's clear on the console what is happening.)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20624)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

___
*[`multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-NnbZGSN43bZZVIL-mXE:-Nncqco18nmd1QnObSnq:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a0afd61eee5455e3f9a601a3b7e811db590f208f/multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Stray debugging?

(It would be OK to log in a unit test, but in that case it should have some extra text ahead of the value so it's clear on the console what is happening.)
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20624)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20624#-NnbZR_F6nuleV4zCl9G:-Nne-oRG7F-sHKFMyQA9:bg7igkv) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@hongkai-dai please re-feature-review the new edits.
</blockquote></details>

:lgtm: 

___

**Pull request merged**
