### PR TITLE
Update IIWA `.obj` references to `.gltf`

### PR DESCRIPTION
**Pull request by siddancha**
Related: https://github.com/RobotLocomotion/models/pull/36

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by siddancha** [comment]
@jwnimmer-tri  It seems that `planar_scenegraph_visualizer.py` requires `.obj` files, which causes the tests to break since we're now removing IIWA obj files: [LINK](https://github.com/RobotLocomotion/drake/blob/9faddc40891e2b63ae11b67f597286a6e8bce21d/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L256-L260).

**Comment by jwnimmer-tri** [comment]
Good find!

I had not accounted for that code as one of our geometry endpoints, so I had never checked over it when adding glTF support throughout Drake.

I'll need to think on this a bit more.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvFA11BAe3yoK_7piw:-NrvFA11BAe3yoK_7pix:b8db3s7) (no related file):*
> > It seems that `planar_scenegraph_visualizer.py` requires `.obj` files, which causes the tests to break since we're now removing IIWA obj files.
>
> I had not accounted for that code as one of our geometry endpoints, so I had never checked over it when adding glTF support throughout Drake.

@SeanCurtis-TRI we found one more "illustration geometry" place in Drake that doesn't support glTF yet.  All of us forgot about it until now, it seems.

Given your work on #21061 and similar, I'm hoping you can help out here either with code, or at least design advice.

This particular visualizer needs to compute the convex hull of visual meshes (and then project that onto a plane).  I don't think we have any code yet to do chull on glTF files?  Do you think we could enhance some code in your recent PR train to allow for glTF meshes (presumably parsed via our VTK libraries), so that the planar visualizer could be adapted to use that new API?

I imagine we would do that in a separate PR, and then once that lands we can rebase here and everything would be happy.

___
___
*[`manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NrvERUNBWWJvD2WFPju:b-az0xs2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25)):*
> ```
>         </geometry>
>         <material>
>           <diffuse>0.4 0.4 0.4 1.0</diffuse>
> ```

This goes for all of the SDFormat and/or URDF files changed in this PR:

Now that visual meshes are glTF, I believe all of the phong materials in these files will cause warnings that they are being ignored.

Please check with e.g. `bazel run //tools:model_visualizer -- --show_rgbd_sensor package://drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` and see are warnings show up in your terminal.

I'm guessing that this PR will need to delete all of these `<material>` stanzas anywhere glTF is used.  As you noted in the `models` PR, the coloring is part of the glTF data itself now, so we probably should not be repeating it here.

**Comment by siddancha** [comment]
> _[manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NrvERUNBWWJvD2WFPju:b-az0xs2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25))_:
> 
>         </geometry>
>         <material>
>           <diffuse>0.4 0.4 0.4 1.0</diffuse>
> This goes for all of the SDFormat and/or URDF files changed in this PR:
> 
> Now that visual meshes are glTF, I believe all of the phong materials in these files will cause warnings that they are being ignored.
> 
> Please check with e.g. `bazel run //tools:model_visualizer -- --show_rgbd_sensor package://drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` and see are warnings show up in your terminal.
> 
> I'm guessing that this PR will need to delete all of these `<material>` stanzas anywhere glTF is used. As you noted in the `models` PR, the coloring is part of the glTF data itself now, so we probably should not be repeating it here.

@jwnimmer-tri Just removed all redundant `<material>` tags for glTF meshes in all relevant `*.sdf/*.urdf` files.

Now, the _"glTF defines its own materials, so post hoc materials will be ignored and should be removed from the model specification"_ warnings go away.

**Comment by SeanCurtis-TRI** [comment]
I'm going spelunking. I'll get back to you.

**Comment by SeanCurtis-TRI** [comment]
Some observations:

 - `planar_scenegraph_visualizer` does use the co-located .obj logic. So, if we have both .glTF and .obj that is a short term paliative.
 - I'll quickly look into:
    - Drake code for getting a convex hull from a .glTF file and
    - making that API bound and publicly available.
    
 [This function](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/make_convex_hull_mesh.h#L21) already supports .obj and .vtk volume meshes. It probably won't be that hard to include .glTF files.
 
 Stay tuned.

**Comment by jwnimmer-tri** [comment]
> So, if we have both .glTF and .obj that is a short term palliative.

Right.  My current thought is that there is nothing time-critical here, so we might as well just wait for the correct fix to land before we start porting this model and all of our other models to glTF.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

___
*[`manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NsAXwnFCSXzhcz__bb3:b-aiudzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25)):*
<details><summary><i>Previously, siddancha (Siddharth Ancha) wrote…</i></summary><blockquote>

@jwnimmer-tri Just removed all redundant `<material>` tags for glTF meshes in all relevant `*.sdf/*.urdf` files.

Now, the _"glTF defines its own materials, so post hoc materials will be ignored and should be removed from the model specification"_ warnings go away.

</blockquote></details>

Something else we'll need to consider.

`planar_scenegraph_visualizer` *uses* this value in order to figure out how to color the 2D polygon. If we strip out this data here, it will have no recourse but to use its default color, rendering everything homogeneously light grey.

We'd probably like some utility that can look at objects with materials and provides, heuristically, some representative color. I can easily conceive that that would quickly spiral out of control.

It would be best if we could define a "fallback" material on a per-geometry basis.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvFA11BAe3yoK_7piw:-NsA_ZZN3H1lvOOnyhzx:bk796iy) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> > It seems that `planar_scenegraph_visualizer.py` requires `.obj` files, which causes the tests to break since we're now removing IIWA obj files.
>
> I had not accounted for that code as one of our geometry endpoints, so I had never checked over it when adding glTF support throughout Drake.

@SeanCurtis-TRI we found one more "illustration geometry" place in Drake that doesn't support glTF yet.  All of us forgot about it until now, it seems.

Given your work on #21061 and similar, I'm hoping you can help out here either with code, or at least design advice.

This particular visualizer needs to compute the convex hull of visual meshes (and then project that onto a plane).  I don't think we have any code yet to do chull on glTF files?  Do you think we could enhance some code in your recent PR train to allow for glTF meshes (presumably parsed via our VTK libraries), so that the planar visualizer could be adapted to use that new API?

I imagine we would do that in a separate PR, and then once that lands we can rebase here and everything would be happy.
</blockquote></details>

See #21091. I'll probably PR something tomorrow.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

___
*[`manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NsA_VFF2OAtDCa5h0fC:b-ti7o6x) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Something else we'll need to consider.

`planar_scenegraph_visualizer` *uses* this value in order to figure out how to color the 2D polygon. If we strip out this data here, it will have no recourse but to use its default color, rendering everything homogeneously light grey.

We'd probably like some utility that can look at objects with materials and provides, heuristically, some representative color. I can easily conceive that that would quickly spiral out of control.

It would be best if we could define a "fallback" material on a per-geometry basis.
</blockquote></details>

I'm willing to chalk that up as "planar scene graph visualizer is still broken, and has always been broken, for meshes that define their own intrinsic materials" (like if there was an mtl file with the coloring).  I don't think it needs to block this PR, and I don't think we need to plan any tasks to fix it from the TRI side.  People who use this visualizer are invited to improve it along those lines.  My only goal here is not to break the overall capability of showing at least the chull.  The `use_random_colors=True` is the existing work-around for that kind of situation.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

___
*[`manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NsB9POC16yKhD1RvxSA:b-hxbuy5) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm willing to chalk that up as "planar scene graph visualizer is still broken, and has always been broken, for meshes that define their own intrinsic materials" (like if there was an mtl file with the coloring).  I don't think it needs to block this PR, and I don't think we need to plan any tasks to fix it from the TRI side.  People who use this visualizer are invited to improve it along those lines.  My only goal here is not to break the overall capability of showing at least the chull.  The `use_random_colors=True` is the existing work-around for that kind of situation.
</blockquote></details>

"Always been broken"? That feels a bit retconned. Those material declarations used to be meaningful. And with an obj with out a .mtl file, they were the only way to color it. Because we're changing the .sdf files to refer to .gltf instead of the old .objs we are, in some sense, breaking it.

Admittedly, if the user backs up to .mtl-less objs they can go back to using the material definitions and see the colored meshes again.

Fortunately, they should be able to hack the materials and put the declarations back in. They can either a) not include render engines, b) change their logging to only have errors, or c) ignore the warnings and they can have colored drawings.

(Personally, I wonder if it isn't the right time to change the warning to info -- hey, we're ignoring the declaration.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

___
*[`manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NsBCSSd-qgAk46YDxnj:b-4x4qgv) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

"Always been broken"? That feels a bit retconned. Those material declarations used to be meaningful. And with an obj with out a .mtl file, they were the only way to color it. Because we're changing the .sdf files to refer to .gltf instead of the old .objs we are, in some sense, breaking it.

Admittedly, if the user backs up to .mtl-less objs they can go back to using the material definitions and see the colored meshes again.

Fortunately, they should be able to hack the materials and put the declarations back in. They can either a) not include render engines, b) change their logging to only have errors, or c) ignore the warnings and they can have colored drawings.

(Personally, I wonder if it isn't the right time to change the warning to info -- hey, we're ignoring the declaration.)
</blockquote></details>

What we are doing in this PR is changing the IIWA model files so that they don't work as well anymore with that visualizer.  That is completely fine -- our model files are a best-effort basis, they are not Stable API, they will always randomly break downstream people who make the mistake of depending on them directly instead of vendoring locally stable copies of them.  We can go wild and make them be whatever we want, delete them, etc.  They are in a sense just documentation / examples / illustrative.  They are not "code" that people should ever count on.

The question in this thread is how well the planar visualizer works or doesn't work, for any specific model file the user has (not these files).  If the user had objs with mtls, then it was always crap colors and still have crap colors.  If they had objs with no mtls, the colors were nice before and are still nice as of this PR.  If they try to use glTFs with not objs to fall back on, it will not work at all.  We should at least make it work with random colors.

The fact that this PR is discussing both the iiwa model details and the planar visualizer details is just by the merest chance.  The two topics are completely independent.  The visualizer has _never_ worked when the mesh file has intrinsic coloring.  This PR isn't changing that in any way.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

___
*[`manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf` line 25 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvERUNBWWJvD2WFPjt:-NsBFIWz1h0g7UeIxM9V:bsqk3re) ([raw file](https://github.com/RobotLocomotion/drake/blob/d8f6b8449bc28632767c05932df1ce16c453980f/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf#L25)):*
> The visualizer has _never_ worked when the mesh file has intrinsic coloring.

It has *always* worked by using the single declared color. It's just that in the interim, we've started yelling about that in other places. Certainly, those materials are the right and proper thing to do for primitive geometries.

But I'm marking myself satisfied because, as you point out, as long as you don't care how the gltfs look in the planar visualizer (or any tutorial/example we might have), then it has nothing to do with this PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NrvFA11BAe3yoK_7piw:-NsolImG2WKt8UmqQzXb:bp4yin3) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

See #21091. I'll probably PR something tomorrow.
</blockquote></details>

Update -- once #21131 merges, we can return here.

___
___
*[`manipulation/models/iiwa_description/BUILD.bazel` line 38 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-NsolcwK9mYOqEpHLtln:-NsolcwK9mYOqEpHLtlo:bqqh2j5) ([raw file](https://github.com/RobotLocomotion/drake/blob/6cae007b52bcaac3eb3ba0aeefd02aca4008244d/manipulation/models/iiwa_description/BUILD.bazel#L38)):*
> ```Starlark
>         "@drake_models//:iiwa_description/meshes/iiwa14/collision/link_7.obj",
>         "@drake_models//:iiwa_description/meshes/iiwa14/collision/link_7_polytope.obj",  # noqa
>         "@drake_models//:iiwa_description/meshes/iiwa14/visual/band.gltf",
> ```

I think we'll need both the `*.gltf` and `*.bin` files listed here, to be complete.

**Comment by siddancha** [comment]
> I think we'll need both the `*.gltf` and `*.bin` files listed here, to be complete.

@jwnimmer-tri Done!

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks for your patience.  I was pretty busy but finally found time for this.

I pushed a merge-up to master plus fixes for the planar visualizer's fallback logic.  If you have anything more to push, be sure to merge in my changes to your local copy first.

I've tested _all_ models before (on master) and after (this PR) using the model visualizer with VTK render engine, e.g., `bazel run //tools:model_visualizer -- --show_rgbd_sensor package://drake/manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf`.  They all look good.

:lgtm: feature.

+@rpoyner-tri for platform review, please.

> Reviewed 1 of 3 files at r2, 12 of 12 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-:-NtclnLU2wLoVCz9Vnox:b-mk5n16)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-Ntc_cptDGwJKZryBcbd:-Ntc_cptDGwJKZryBcbe:b-115u8x) ([raw file](https://github.com/RobotLocomotion/drake/blob/26a690a0a7b5a14467dc0e7e81e6688e55d38e10/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "5e9f85b6706aca1a45f79152c1e53e669f7a18b2",
> ```

Working

Reminder to myself to fix / check this commit sha once the drake_models PR lands.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 12 files at r3, 1 of 1 files at r5, 10 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21079#-:-NtqGEPD6ktRG9MMFNak:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @siddancha)

**Pull request merged**
