### PR TITLE
Remove Compat-Version entries from CPS files

### PR DESCRIPTION
**Pull request by jamiesnape**
So Drake requires at least the version specified of each package. Relates #7382.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7396)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7396#-:-KxxLikFDLV-8hqHp3b0:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

Does it set `Compat-Version` == `Version`?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7396#-:-KxxP3rf2fYsKRToNHq6:bn4v5mv)*

**Comment by jamiesnape** [comment]
Yes.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7396#-:-KxxPD7JXXSKlm7OJeYB:bb77ufg)*

**Pull request merged**
