### PR TITLE
[solvers]: QuadraticConstraint stores the Hessian type.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Indicate whether the Hessian is positive/negative semidefinite or indefinite. This will be useful for checking the convexity of the constraint.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-:-NQ31jxuEBmMJeZFesdG:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice)

___
*[`solvers/test/constraint_test.cc` line 185 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQCJ-zQBE2D25bIeagp:-NQDdb5J-PYRNB4Hw9j7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/90cbb10c875fb62e9a424256c50f350f9e83af24/solvers/test/constraint_test.cc#L185)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would add a comment that says "the constraint is not convex due to the lower bound not being -inf". I missed that initially.
</blockquote></details>

Done.
___
*[`solvers/test/constraint_test.cc` line 243 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQCKIVS7QWqoK6ByWwR:-NQDe-P69l3Sp0T0s7EM:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/90cbb10c875fb62e9a424256c50f350f9e83af24/solvers/test/constraint_test.cc#L243)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We are missing a test for PSD hessian being convex.
</blockquote></details>

Done. Good call.
___
*[`bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc` line 1808 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQCJhnADCoDYOL9Ill4:-NQDeE9e0qQe7zF0uJdd:b-pt7zy4) ([raw file](https://github.com/RobotLocomotion/drake/blob/90cbb10c875fb62e9a424256c50f350f9e83af24/bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc#L1808)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Why the `py_rvp::reference_internal` here? 
</blockquote></details>

Typically when we return `const Foo&` for the getter function, I will add `py_rvp::reference_internal`. See https://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies for the explanation.
___
*[`bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc` line 1810 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQCK4hm3EgTog7YOggv:-NQDeMsT3KpsHnEAKgOb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/90cbb10c875fb62e9a424256c50f350f9e83af24/bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc#L1810)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`bindings/pydrake/solvers/test/mathematicalprogram_test.py` line 615 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQCKbN-1IwTLe_9eMlZ:-NQDemDk1xIeVjTyqXyk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/90cbb10c875fb62e9a424256c50f350f9e83af24/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L615)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you add a test for the binding `HessianType.kIndefinite`
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-:-NQHvhXICDq-A4rxB2yJ:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-:-NQM9h5p-QbahGaWuU3C:b-jarjz8)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-:-NQQ7d5i1vvyZu7GN7Dn:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`solvers/constraint.h` line 223 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQQ7l5l49p5NHfx30mm:-NQQ7l5l49p5NHfx30mn:b-4mdovp) ([raw file](https://github.com/RobotLocomotion/drake/blob/809c5380e7dbd84e05e1f830568ec4ed2251c3d3/solvers/constraint.h#L223)):*
> ```objc
>    * Q0. If hessian_type=std::nullopt, then QuadraticConstraint will check the
>    * type of Q0. To speed up the constructor, set hessian_type != std::nullopt
>    * if you can.
> ```

minor:  It would be good to indicate what happens if the user passes in an incorrect value for `hessian_type` (ie, one that is inconsistent with `Q0`)
(similarly below).  I assume the answer is "the solver will return infeasible solutions" or something similar?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice (waiting on @hongkai-dai)

___
*[`solvers/constraint.h` line 223 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18965#-NQQ7l5l49p5NHfx30mm:-NQQxtIQ-LUXkYSK3SZj:b-iudpjk) ([raw file](https://github.com/RobotLocomotion/drake/blob/809c5380e7dbd84e05e1f830568ec4ed2251c3d3/solvers/constraint.h#L223)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It would be good to indicate what happens if the user passes in an incorrect value for `hessian_type` (ie, one that is inconsistent with `Q0`)
(similarly below).  I assume the answer is "the solver will return infeasible solutions" or something similar?
</blockquote></details>

Done. I added some documentation.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18965)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice (waiting on @hongkai-dai)

**Pull request merged**
