### PR TITLE
Logic integer constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This PR transcribe expression on boolean variables, to linear constraints. Currently we handle the expression with `and, or, xor`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6676)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-:-Kq-XLLlRyXalwyIJQGA:bpno49v)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/test/CMakeLists.txt, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq0CYsU-5h4d4pVLXl6:-Kq0CYsU-5h4d4pVLXl7:b5fjurg) ([raw file](https://github.com/robotlocomotion/drake/blob/d08b96be3adc1bea39d0a9b6bc3bf783b9a89659/drake/solvers/test/CMakeLists.txt#L28)):*
> ```CMake
> target_link_libraries(bilinear_product_util_test drakeBilinearProductUtil)
> 
> drake_add_cc_test(integer_optimization_util_test)
> ```

FYI, we have:
```
[ RUN      ] IntegerOptimizationUtilTest.TestAnd
unknown file: Failure
C++ exception with description "MathematicalProgram::Solve: No solver available for the given optimization problem!" thrown in the test body.
```
https://drake-cdash.csail.mit.edu/testDetails.php?test=15321880&build=715526

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676)*

**Comment by soonho-tri** [comment]
Checkpoint, PTAL.

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/solvers/integer_optimization_util.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq3N-9UDp84gR9VX4Gj:-Kq3N-9UDp84gR9VX4Gk:bkk4c6f) ([raw file](https://github.com/robotlocomotion/drake/blob/d08b96be3adc1bea39d0a9b6bc3bf783b9a89659/drake/solvers/integer_optimization_util.h#L10)):*
> ```objc
> /**
>  * For two binary expressions b1 and b2, each can only take value 0 or 1,
>  * impose constraints on b1, b2, together with b1_and_b2, such that
> ```

BTW, nit, META
 - `impose` -> `imposes`
 - `take value` -> `take a value`
 - `take binary value` -> `take a binary value`

---

*[drake/solvers/test/integer_optimization_util_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq3O4bh4Iqhfcsc_6L0:-Kq3O4bh4Iqhfcsc_6L1:bkpyf9y) ([raw file](https://github.com/robotlocomotion/drake/blob/d08b96be3adc1bea39d0a9b6bc3bf783b9a89659/drake/solvers/test/integer_optimization_util_test.cc#L57)):*
> ```cpp
>         case LogicalOperand::kAnd:
>           operand_result_expected =
>               static_cast<double>(static_cast<bool>(b_vals_[i](0)) &
> ```

FYI, the uses of `static_cast<bool>` are redundant. The following works:

```c++
        case LogicalOperand::kAnd:
          operand_result_expected =
              static_cast<double>(b_vals_[i](0) & b_vals_[i](1));
          break;
        case LogicalOperand::kOr:
          operand_result_expected =
              static_cast<double>(b_vals_[i](0) | b_vals_[i](1));
          break;
        case LogicalOperand::kXor:
          operand_result_expected =
              static_cast<double>(b_vals_[i](0) ^ b_vals_[i](1));
```

Note that bitwise operations `&`, `|`, `^` are not defined over `bool`. In the current implementation, `b_vals_[i](0)` is first cast to `bool` and implicitly cast back to `int` for bitwise operations. Of course, a compiler will optimize them out but it can mislead a reader.

 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-:-Kq3Q_c2F0ybGH59BfQU:biz4o9q)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/integer_optimization_util.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq3N-9UDp84gR9VX4Gj:-Kq3qO5oc39OHpoaN-TB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d08b96be3adc1bea39d0a9b6bc3bf783b9a89659/drake/solvers/integer_optimization_util.h#L10)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, META
 - `impose` -> `imposes`
 - `take value` -> `take a value`
 - `take binary value` -> `take a binary value`

</blockquote></details>

Done.

---

*[drake/solvers/test/CMakeLists.txt, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq0CYsU-5h4d4pVLXl6:-Kq3xu3QDw--pOt-zkEF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d08b96be3adc1bea39d0a9b6bc3bf783b9a89659/drake/solvers/test/CMakeLists.txt#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, we have:
```
[ RUN      ] IntegerOptimizationUtilTest.TestAnd
unknown file: Failure
C++ exception with description "MathematicalProgram::Solve: No solver available for the given optimization problem!" thrown in the test body.
```
https://drake-cdash.csail.mit.edu/testDetails.php?test=15321880&build=715526
</blockquote></details>

Done.

---

*[drake/solvers/test/integer_optimization_util_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq3O4bh4Iqhfcsc_6L0:-Kq3xvPVZtuQiB_i1Gep:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/d08b96be3adc1bea39d0a9b6bc3bf783b9a89659/drake/solvers/test/integer_optimization_util_test.cc#L57)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, the uses of `static_cast<bool>` are redundant. The following works:

```c++
        case LogicalOperand::kAnd:
          operand_result_expected =
              static_cast<double>(b_vals_[i](0) & b_vals_[i](1));
          break;
        case LogicalOperand::kOr:
          operand_result_expected =
              static_cast<double>(b_vals_[i](0) | b_vals_[i](1));
          break;
        case LogicalOperand::kXor:
          operand_result_expected =
              static_cast<double>(b_vals_[i](0) ^ b_vals_[i](1));
```

Note that bitwise operations `&`, `|`, `^` are not defined over `bool`. In the current implementation, `b_vals_[i](0)` is first cast to `bool` and implicitly cast back to `int` for bitwise operations. Of course, a compiler will optimize them out but it can mislead a reader.

 

</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676)*

**Comment by soonho-tri** [comment]
+(status: curate commits before merging) 
:lgtm: 
+@SeanCurtis-Tri, platform-review please.

---

Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-:-Kq4-1TkyC9Y8PEo64cw:bisi91x)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/integer_optimization_util.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4PFEOyqbwDJWvwhgL:-Kq4QmI6ykokZunCo2yd:bw9unjp) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/integer_optimization_util.h#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

meta: This documentation feels a bit tortured. We have a convention to start documentation with an implied subject. But when we precede that with a clause, it gets really weird. Also, *what* the *significance* of what this function does is lost. The comment on the return value does a *great* job of explaining what this function *accomplishes*. (Turning boolean constraints into numerical constraints such that satisfying the latter satisfies the former.)
</blockquote></details>

Typos: 
1. __*Adds*__ linear constraints...
2. b1_xor_b2 -> b1_and_b2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/BUILD, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4KRZdh9vsJt8VPIF3:-Kq55ZOpocaM4mNKaXaw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/BUILD#L299)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Looks like this got beaten up on. 'Ware Clion's re-orderin' ways.
</blockquote></details>

Done.

---

*[drake/solvers/BUILD, line 309 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4KYOVFZpXmwO-O3ju:-Kq55_9eYnuM4Wmo3gjd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/BUILD#L309)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Same re-orderin' here.
</blockquote></details>

Done.

---

*[drake/solvers/integer_optimization_util.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4PFEOyqbwDJWvwhgL:-Kq55aVkFo7DASOiOc0_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/integer_optimization_util.h#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Typos: 
1. __*Adds*__ linear constraints...
2. b1_xor_b2 -> b1_and_b2.
</blockquote></details>

Done.

---

*[drake/solvers/test/integer_optimization_util_test.cc, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4Q466NoLNavhTiFhw:-Kq55drpwS2R-yA2YFZK:bqh46za) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/test/integer_optimization_util_test.cc#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Haven't seen this used in tests before. Nothing wrong with that, of course. But probably unnecessary.
</blockquote></details>

I thought we put this by default, in case anyone try to move, copy or assign the object in the future.

---

*[drake/solvers/test/integer_optimization_util_test.cc, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4QOv-nOKUQ6osHW8L:-Kq55mvLa-kdAcD7ZmZl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/test/integer_optimization_util_test.cc#L47)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

META: We require "proper" sentences with cappunc, even on this internal stuff.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r3, 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/integer_optimization_util_test.cc, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4Q466NoLNavhTiFhw:-Kq5ETGlBonluqFymwj9:b6fb5ve) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/test/integer_optimization_util_test.cc#L12)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I thought we put this by default, in case anyone try to move, copy or assign the object in the future.
</blockquote></details>

BTW We definitely do for "real" code. But in tests? It lives only in this compilation unit and then dies. No one else can instantiate it.

---

*[drake/solvers/test/integer_optimization_util_test.cc, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-Kq4QOv-nOKUQ6osHW8L:-Kq5EbgbUpgI7B9qbfRt:b-yxy75n) ([raw file](https://github.com/robotlocomotion/drake/blob/d351d0ed24c4343d063f48cdf10987903d7a56f1/drake/solvers/test/integer_optimization_util_test.cc#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Aaaah....I hadn't realize that three line comment was intended to be a single sentence.  Still, the period is good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6676#-:-Kq5Ehp2tqbtcStAP2-O:bmxilld)*

**Pull request merged**
