### PR TITLE
Extend convex hull computation to include in-memory glTF files

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
We use VTK to parse the glTF files. This moves from vtkGLTFImporter to vtkGLTFDocumentLoader. This latter class supports parsing from a stream. However, we do patch it so we can silence it regarding missing supporting files that we simply don't care about (e.g., texture images).

To be able to parse from memory, we need a custom vtkURILoader to resolve the file URI for a glTF's .bin file. We create one that knows about MeshSource so that it can serve files to VTK appropriately.

To properly test a glTF file, we clean up rainbox_box.gltf, so that its transforms more fully reflect the intended value (they'd been written out with imprecision which was irrelevant to its visual appearance, but messed up the convex hull).

In support of all of the above, we also do the following:

- Introduce vtk-based helper provides utilities to work with glTF files in VTK.
- Patching VTK
  - Add VTK::IOCore to our visible VTK packages.
  - The aforementioned patch.
- Make the VtkDiagnosticEventObserver visible to the convex hull computation.

Relates #15263.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@DamrongGuoy For feature review, please. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O7j4IuqAjD_VLcw9dcl:bcgj0f9)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@DamrongGuoy +@jwnimmer-tri for feature review. This is also glTF + VTK and it turns out I have more PRs dependent on this than I was originally thinking. 

+(priority: high) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O7jPpvC-Rh5fRLeKxVx:b-dogskb)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
First pass complete.

+(release notes: none) 

> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O7kMiBmDgJWcD6cGhSK:b-3m58kb)* status: 12 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`geometry/BUILD.bazel` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kA57H9hwTNcB0BfsM:-O7kA57H9hwTNcB0BfsN:b-f0fqrz) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/BUILD.bazel#L317)):*
> ```Starlark
>         "//common:memory_file",
>         "//common:overloaded",
>         "@vtk_internal//:vtkCommonCore",
> ```

nit None of the EOL include comments mention "vtkCommonCore".
___
*[`geometry/internal_gltf_vtk.h` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kGjGX9jkN1DTUUu4N:-O7kGjGX9jkN1DTUUu4O:bvzwwcl) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.h#L33)):*
> ```objc
>                 The data will be aliased and must stay alive longer than this.
>    */
>   explicit MeshMemoryLoader(const InMemoryMesh* data);
> ```

It seems to me like the encapsulation and robustness of the VTK-related GLTF helpers in this file would be improved by changing this class to accept the more general `const MeshSource*` instead of `const InMemoryMesh*`.  Internally it can handle the `ReadGltfToMemory` step.  It can then also offer a `MakeMainContentsStream() const` member function instead of the free function below.  The decoupling you have here is plausible, but I imagine that on balance the calling code would be more clear if these two ideas were fused into one.  I grepped the WIP branch and both uses of this utility seem consistent with this proposal.  (The rendering call site would happen to only ever pass an in-memory file source, but that's not a problem.)

That edit would also help fix the incongruous header-filename-vs-API-names inconsistency.  The file could be named `mesh_memory_loader.h` since it just has the one class.  (Plausibly the work "VTK" could also be part of the classname + filename, if that is more clear.)
___
*[`geometry/internal_gltf_vtk.h` line 34 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kJLRI7dZluA9FQI9y:-O7kJLRI7dZluA9FQI9z:b-uiupyx) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.h#L34)):*
> ```objc
>    */
>   explicit MeshMemoryLoader(const InMemoryMesh* data);
> ```

nit Probably we need a non-inline destructor here?
___
*[`geometry/internal_gltf_vtk.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kKAVW2-1s4nnDxN81:-O7kKAVW2-1s4nnDxN82:b19qvc2) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.cc#L23)):*
> ```cpp
> 
> constexpr char kBaseUriPrefix[] = "/MeshMemoryLoader/";
> constexpr int kBaseUriPrefxLength = 18;
> ```

nit Too magic / brittle across these two!  Use e.g. `sizeof()` or some other constexpr spelling.
___
*[`geometry/internal_gltf_vtk.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kKYno4emvd_uaTHAf:-O7kKYno4emvd_uaTHAg:bcuroqt) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.cc#L23)):*
> ```cpp
> 
> constexpr char kBaseUriPrefix[] = "/MeshMemoryLoader/";
> constexpr int kBaseUriPrefxLength = 18;
> ```

typo `Prefix`
___
*[`geometry/internal_gltf_vtk.cc` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kL-P7DRSu-Gpm1GrE:-O7kL-P7DRSu-Gpm1GrF:b2iurcp) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.cc#L46)):*
> ```cpp
>     // (e.g., ../foo.bin), then this trick will not work. But the glTF spec
>     // explicitly disallows that.
>     auto pos = path.find(kBaseUriPrefix);
> ```

I am not sure why we do `find` here, probably because I don't understand how VTK is mapping things between the document and this function's  argument.  Why isn't `/MeshMemoryLoader/` in a well-known position, e.g., at offset zero, or some fixed constant?  Maybe we just need some comments.
___
*[`geometry/internal_gltf_vtk.cc` line 68 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kLnq60Tjb0D8xQsrq:-O7kLnq60Tjb0D8xQsrr:b1gjknu) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.cc#L68)):*
> ```cpp
>                      vtkNew<vtkFileResourceStream> stream;
>                      if (!stream->Open(source_path.c_str())) {
>                        throw std::runtime_error("Unable to open file");
> ```

nit We should probably add more detail to this error message?  Or would we rather return nullptr and let the parser yell about it, like we did with the no-such-supporting-file above?
___
*[`geometry/proximity/BUILD.bazel` line 553 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7k9LqyBU561adfFXd0:-O7k9LqyBU561adfFXd1:b-24d0mn) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/proximity/BUILD.bazel#L553)):*
> ```Starlark
>         "@qhull_internal//:qhull",
>         "@vtk_internal//:vtkCommonCore",
>         "@vtk_internal//:vtkIOImport",
> ```

nit We want IOGeometry now, I think?  To match the include-comment change in the cc file.
___
*[`geometry/proximity/make_convex_hull_mesh_impl.cc` line 174 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kCp_m7qHbGN4aFARD:-O7kCp_m7qHbGN4aFARE:b-ts0h8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/proximity/make_convex_hull_mesh_impl.cc#L174)):*
> ```cpp
> 
>   if (!loader->LoadModelMetaDataFromStream(gltf_stream, &uri_loader) ||
>       !loader->LoadModelData({}) || !loader->BuildModelVTKGeometry()) {
> ```

BTW I have somewhat of a personal readability opinion that the load-bearing work of a function should not happen as a side-effect of a guard.  Could something like the below be cleaner?

```c++
bool success = true;
success = success && loader->LoadModelMetaDataFromStream(gltf_stream, &uri_loader);
success = success && loader->LoadModelData({});
success = success && loader->BuildModelVTKGeometry();
if (!success) {
  throw ...;
}
```

For me it also help clarify the sense of the functions return values as "true <==> success" -- whereas the if-spelling is somewhat "backwards".  (If you keep the `if (...)` spelling, going a demorgan it would probably help, with one ! on the outside and joining inside on &&.)
___
*[`geometry/proximity/make_convex_hull_mesh_impl.cc` line 177 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kCjs18rUOKzclnz5a:-O7kCjs18rUOKzclnz5b:b-biy4zd) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/proximity/make_convex_hull_mesh_impl.cc#L177)):*
> ```cpp
>     // Note: we don't generally expect this exception to be thrown. We expect
>     // the event observer will convert VTK errors to thrown exceptions for us.
>     // This is her on the off chance that VTK returns failure on any of the
> ```

typo `here`
___
*[`geometry/proximity/make_convex_hull_mesh_impl.cc` line 186 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kBvh9BUOu-rvExaoc:-O7kBvh9BUOu-rvExaod:b-fr6e34) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/proximity/make_convex_hull_mesh_impl.cc#L186)):*
> ```cpp
> 
>   // Now get the vertex data, transformed to the geometry frame G.
>   auto model = loader->GetInternalModel();
> ```

nit Can we spell out something better than `auto` here?  I don't have any intuition for what class will be returned here.
___
*[`tools/workspace/vtk_internal/patches/gltf_selected_load.patch` line 44 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kMFc62JcOW3OKHNZ7:-O7kMFc62JcOW3OKHNZ8:b-fmnekh) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/tools/workspace/vtk_internal/patches/gltf_selected_load.patch#L44)):*
> ```Diff
>  
> --- IO/Geometry/vtkGLTFDocumentLoader.h
> +++ IO/Geometry/vtkGLTFDocumentLoader.h
> ```

nit I know this is the order that `diff` lists the patches, but it would make this `*.patch` file easier to read if the header edits came first, then the cc edits.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First round done.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O7o8RAZ5kM-fL6ienaA:btuciqt)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7o2FO_3aY7ONOkfmWx:-O7o2FO_3aY7ONOkfmWy:b-xzbq59) (no related file):*
If you run one of the tests that depends on this new code, e.g.,:

`bazel test geometry/proximity:make_convex_hull_mesh_impl_test --test_output=all --test_filter="*GltfMesh"`

You'll get a number of error messages:

```bash
[ RUN      ] MakeConvexHullMeshTest.GltfMesh
ERROR: In vtkObject.cxx, line 175
vtkObject (0x7ffce21ed040): Trying to delete object with non-zero reference count.

Generic Warning: In vtkObjectBase.cxx, line 159
Trying to delete object with non-zero reference count.

[       OK ] MakeConvexHullMeshTest.GltfMesh (0 ms)
```

Curiously, the sanitizers don't seem to choke on this (these problems existed in the first revision as well). I'm going to keep poking to figure out how to silence it, but I wanted this clearly out there even if CI passes.

___
___
*[`geometry/internal_gltf_vtk.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kKAVW2-1s4nnDxN81:-O7o1M2JCHVXUb81Hs1N:b-8vwbrn) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Too magic / brittle across these two!  Use e.g. `sizeof()` or some other constexpr spelling.
</blockquote></details>

TIL that `string_view` is immensely `constexpr`.
___
*[`geometry/internal_gltf_vtk.cc` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kL-P7DRSu-Gpm1GrE:-O7o1SLqAhV6kwFQPcsL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.cc#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not sure why we do `find` here, probably because I don't understand how VTK is mapping things between the document and this function's  argument.  Why isn't `/MeshMemoryLoader/` in a well-known position, e.g., at offset zero, or some fixed constant?  Maybe we just need some comments.
</blockquote></details>

Done.
___
*[`geometry/internal_gltf_vtk.h` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7kGjGX9jkN1DTUUu4N:-O7o2np15l69mgWItpWK:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/acd4843f358c2b7894ca4e7dcff82a7e091e061c/geometry/internal_gltf_vtk.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me like the encapsulation and robustness of the VTK-related GLTF helpers in this file would be improved by changing this class to accept the more general `const MeshSource*` instead of `const InMemoryMesh*`.  Internally it can handle the `ReadGltfToMemory` step.  It can then also offer a `MakeMainContentsStream() const` member function instead of the free function below.  The decoupling you have here is plausible, but I imagine that on balance the calling code would be more clear if these two ideas were fused into one.  I grepped the WIP branch and both uses of this utility seem consistent with this proposal.  (The rendering call site would happen to only ever pass an in-memory file source, but that's not a problem.)

That edit would also help fix the incongruous header-filename-vs-API-names inconsistency.  The file could be named `mesh_memory_loader.h` since it just has the one class.  (Plausibly the work "VTK" could also be part of the classname + filename, if that is more clear.)
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7o2FO_3aY7ONOkfmWx:-O7oDstJ0ZnCfiGuZu59:bbd7qmt) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

If you run one of the tests that depends on this new code, e.g.,:

`bazel test geometry/proximity:make_convex_hull_mesh_impl_test --test_output=all --test_filter="*GltfMesh"`

You'll get a number of error messages:

```bash
[ RUN      ] MakeConvexHullMeshTest.GltfMesh
ERROR: In vtkObject.cxx, line 175
vtkObject (0x7ffce21ed040): Trying to delete object with non-zero reference count.

Generic Warning: In vtkObjectBase.cxx, line 159
Trying to delete object with non-zero reference count.

[       OK ] MakeConvexHullMeshTest.GltfMesh (0 ms)
```

Curiously, the sanitizers don't seem to choke on this (these problems existed in the first revision as well). I'm going to keep poking to figure out how to silence it, but I wanted this clearly out there even if CI passes.
</blockquote></details>

Alright, resolved. I didn't hew enough to the VTK standards for creating VTK things. Now the reference counting is happy.

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

CI has a little lint.

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O7oPAaI3U8fxUxcvK8y:b-czr2mf)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/vtk_gltf_uri_loader.h` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7oMUDz4W_Gha2UngMa:-O7oMUDz4W_Gha2UngMb:byw828l) ([raw file](https://github.com/RobotLocomotion/drake/blob/3fb6b3287e11de07a20f6d287f62aa53fda3f994/geometry/vtk_gltf_uri_loader.h#L3)):*
> ```objc
> #pragma once
> 
> /* @file
> ```

BTW Do we still need the file-overview doxygen?
___
*[`geometry/vtk_gltf_uri_loader.h` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7oNKBfD69HDTQ-m001:-O7oNKBfD69HDTQ-m002:b47k5j4) ([raw file](https://github.com/RobotLocomotion/drake/blob/3fb6b3287e11de07a20f6d287f62aa53fda3f994/geometry/vtk_gltf_uri_loader.h#L30)):*
> ```objc
>   static VtkGltfUriLoader* New();
> 
>   /* Sets the source fo this URI loader. It must be called before any other API.
> ```

typo `for`
___
*[`geometry/vtk_gltf_uri_loader.cc` line 66 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7oNVfZ9KD57jglMNcp:-O7oNVfZ9KD57jglMNcq:b-g9gihj) ([raw file](https://github.com/RobotLocomotion/drake/blob/3fb6b3287e11de07a20f6d287f62aa53fda3f994/geometry/vtk_gltf_uri_loader.cc#L66)):*
> ```cpp
> 
> vtkSmartPointer<vtkResourceStream> VtkGltfUriLoader::MakeGltfStream() const {
>   if (source_ == nullptr) {
> ```

BTW For my money, this could be a simpler `DRAKE_THROW_UNLESS`, since this is (and always will be) internal-use-only API.  Shrug.

Ditto below.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for out-of-order platform review, please. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O82CoNE-FmH1w4x44s6:b-6zgp1w)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/vtk_gltf_uri_loader.cc` line 66 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O7oNVfZ9KD57jglMNcp:-O82CbDf9u7deydmRxA6:bj9beza) ([raw file](https://github.com/RobotLocomotion/drake/blob/3fb6b3287e11de07a20f6d287f62aa53fda3f994/geometry/vtk_gltf_uri_loader.cc#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For my money, this could be a simpler `DRAKE_THROW_UNLESS`, since this is (and always will be) internal-use-only API.  Shrug.

Ditto below.
</blockquote></details>

I see your point. But given the anti-RAII nature of the VTK infrastructure, I'm going to leave the messages in place.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 11 files at r1, 5 of 9 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-:-O82ur1f1RXcJAgxHM1V:bnfp4nl)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/internal_gltf_vtk.cc` line 1 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O82kY07B6iRJ8TjQWjY:-O82kY07B6iRJ8TjQWjZ:bsbedwo) ([raw file](https://github.com/RobotLocomotion/drake/blob/7caa61370a5e94987cd44766867bc1c1b86062e1/geometry/internal_gltf_vtk.cc#L1)):*
> ```cpp
> #include "drake/geometry/vtk_gltf_uri_loader.h"
> ```

These changes all look like dead/duplicate code. Why is this file here?
___
*[`geometry/vtk_gltf_uri_loader.cc` line 91 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O82knnnBq3I4r00nPh7:-O82knnnBq3I4r00nPh8:b-1wixv8) ([raw file](https://github.com/RobotLocomotion/drake/blob/7caa61370a5e94987cd44766867bc1c1b86062e1/geometry/vtk_gltf_uri_loader.cc#L91)):*
> ```cpp
>   }
> 
>   // Case insensitive
> ```

nit GSG likes complete sentences with punctuation.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959)* status: 1 unresolved discussion

___
*[`geometry/internal_gltf_vtk.cc` line 1 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21959#-O82kY07B6iRJ8TjQWjY:-O83Dv-g20Kwj3KZzYtF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7caa61370a5e94987cd44766867bc1c1b86062e1/geometry/internal_gltf_vtk.cc#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

These changes all look like dead/duplicate code. Why is this file here?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> Dismissed @rpoyner-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21959)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
