### PR TITLE
Add the documentation on plant_context to minimum distance constraints.

### PR DESCRIPTION
**Pull request by hongkai-dai**
@wrangelvid ran into this issue that the documentation for plant_context is missing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20816)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@wrangelvid for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20816#-:-NoxTrd_-DVthD6HI1AA:bb9rzce)* status: LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20816#-:-NoxVEcjCVLYlRYGSfL0:b-3lhrgq)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20816#-:-NoxfWp_6JIa7ZBOKXel:b-vtj4wo)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.h` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20816#-Noxf8iiBFFGVFeCBiJM:-Noxf8iiBFFGVFeCBiJN:b-xfsps2) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b9713800b8a33fa416fe4be53af007997cdd2c/multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.h#L46)):*
> ```objc
>   minimum signed distance between any candidate pair of geometries.
>   @param plant_context The context of `plant`. The context is obtained as a
>   subsystem context from the diagram context, where the diagram (that contains
> ```

BTW, do you mean that the context _can be_ obtained from a diagram context, or does the context _must_ come from a sub-context of a diagram consisting of mbp and scene graph (i.e. this function doesn't work for a standalone mbp)? I suspect the later based on the name of the class. Consider clarifying this point.



_Code quote:_
```objc
  @param plant_context The context of `plant`. The context is obtained as a
  subsystem context from the diagram context, where the diagram (that contains
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20816)* status: missing label for release notes

**Pull request merged**
