### PR TITLE
Standardize System2 on int per #2514.

### PR DESCRIPTION
**Pull request by david-german-tri**
This should fix some sign-mismatch warnings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2629)

### CODE REVIEW

**Comment by sherm1** [comment]
This makes the sign mismatch warnings worse, I think. Check out the 32 bit ninja build. I think there may be some places where the int64_t is being put into a (32 bit) size_t. Also, `Eigen::Index` is 32 bits there so produces a warning whenever you try to squeeze an int64_t into it. Here are a few examples from the log:
```
 ..\systems\framework\primitives\adder.cc(20): warning C4244: 'argument': conversion from 'const int64_t' to 'unsigned int', possible loss of data
..\systems\framework\primitives\adder.cc(62): warning C4244: 'argument': conversion from 'int64_t' to 'unsigned int', possible loss of data
..\..\drake/systems/framework/basic_vector.h(28): warning C4244: 'argument': conversion from 'int64_t' to 'Eigen::EigenBase<Derived>::Index', possible loss of data
..\..\drake/systems/framework/state_vector.h(67): warning C4244: 'argument': conversion from 'int64_t' to 'Eigen::EigenBase<Derived>::Index', possible loss of data

```

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKz7QhQOdVRAab7kAj_:1817006669)*

**Comment by jwnimmer-tri** [comment]
In my experience, battling warnings like C4244 (integer narrowing "possible loss of data") is an intractable battle to win, and should not be attempted.  I didn't look yet at any other warnings, just that bit of quoted text.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKz9pgOnEccW9izs_8b:-754663882)*

**Comment by sherm1** [comment]
Hmmm ... I've never had any any trouble with this (maybe because VC++ has that warning on by default). Why is it ever good to shove a wide integer into a narrow one without casting to show it was done on purpose? And if we don't want the extra space we could standardize on `int` or `int32_t` instead.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKzBhlFRpkHwirAcMmL:-1144774729)*

**Comment by jwnimmer-tri** [comment]
If all C++ code always used fixed-size integers (`intNN_t`), the warning would be easy to conquer.  But various standard libraries and/or third-party libraries disagree on what the "best" spelling of integers are -- some use fixed-size, some use bare types like `long`, some use meaningfully-variable sizes (`size_t`), and some use their own typedefs (the transitive includes of`mex.h`) and when we glue them all together with our code, multiplied by 6 supported compiler configurations, the amount of care and feeding we will need to remove warnings will be large, and IMO no worth the effort.

Using a plain `int` in this case may be fine -- I haven't looked.  My primary point is that C4244 should not drive our conclusions -- or at least, C4244 on 32-bit platforms should not.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKzD7uCei3xw0yZ0SMl:-1349280864)*

**Comment by david-german-tri** [comment]
On modern platforms, this change doesn't shove a wide integer into a narrow one - the Win64 build is free of these warnings.  The way I see it, our options are (a) to sacrifice integer width on all platforms (by adding a cast, or switching to `int`) or (b) to sacrifice integer width on Win32 only (by leaving this change as-is, or finding some way to suppress the warnings on Win32).

There's a pretty good argument no one will ever need state or input/output vectors with billions of entries, so I'm fine with plain `int`.  Making that change now.  Of course, I still hope we'll someday drop Win32, but Russ vetoed that on #2038 so no sense asking again.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKzCuJkhigbNyHQ-w24:760811554)*

**Comment by david-german-tri** [comment]
Done, PTAL.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKzdyjxfUOsDZDYzxkb:899333092)*

**Comment by sherm1** [comment]
These changes all look good. In fact the code looks a lot nicer this way -- I hope it works. I'm rather fond of `int`. CI seems stuck so I haven't been able to look at the warning situation.

---

Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KKzZW32mics9OLGAvc9:-1057622526)*

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by david-german-tri** [comment]
CI has run, warnings are gone.  @sherm1, can I have an LGTM?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KLIbgP3YZyvGGDDlwog:1999709613)*

**Comment by sherm1** [comment]
BTW, one signed/unsigned mismatch warning in framework code:
```

10:01:01 ..\systems\framework\primitives\adder.cc(60): warning C4018: '<': signed/unsigned mismatch

10:01:01 ..\systems\framework\primitives\adder.cc(39): note: while compiling class template member function 'void drake::systems::Adder<double>::Output(const drake::systems::Context<T> &,drake::systems::SystemOutput<T> *) const'
```

Address if you want. Looks great. :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2629#-:-KLIghVrqoUsdRSMy-Au:-1243021571)*

**Pull request merged**
