### PR TITLE
Fixed bug where witness-triggered events did not have their composite event collections cleared.

### PR DESCRIPTION
**Pull request by edrumwri**
The practical effect was that the vector of witness-triggered events grew (without bound!) over time. Of course, the vector of triggers to publish, discrete update, and unrestricted update events was not correct. Slightly modified an existing test to catch this.

Also added some logging code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7511)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@siyuanfeng-tri for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7511#-:-KzVDg2XEgYUF4twtDw1:bgdoi2o)*

**Comment by sherm1** [comment]
:lgtm: (in case you need a vacation substitute reviewer)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7511#-:-KzVh6fiIthrBnJrpV7V:bv9k953)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.h, line 748 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7511#-KzZ_AMo9kuhoO1o2Jml:-KzZ_AMpKYIAQzw1OWNG:b-1yg1p4) ([raw file](https://github.com/robotlocomotion/drake/blob/0c0f3288815380323d8ef5d4c7dbf726f9b1dbaf/drake/systems/analysis/simulator.h#L748)):*
> ```objc
> 
> // Integrates the continuous state forward in time while attempting to locate
> // the first zero of any triggered witness functions.
> ```

BTW can you add a note here saying events is cleared on entry? thanks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7511#-:-KzZ_IRAOe2Je0MVUfKS:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7511)*

**Pull request merged**
