### PR TITLE
[solvers] Tweak OSQP solver test to satisfy CI

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Decrease the solve time so that the solver times out as expected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17975)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-debug please.

**Review by xuchenhan-tri — COMMENTED** [review]
+@hongkai-dai for feature review please. 
+(release notes: none) 

Related to CI failure here: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-big-sur-clang-bazel-nightly-debug/595/

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17975#-:-NCkkZfm9w7BzWegSgz9:b-uuhv88)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17975)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17975#-NCkjncKBxEuwU4ythbc:-NClrskZ6ljP3tMMnO4U:bg7igkv) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-debug please.
</blockquote></details>

:lgtm: 

___

**Review by xuchenhan-tri — COMMENTED** [review]
+@ggould-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17975#-:-NCrcqYP59STldd5YxA_:bsp3y1t)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17975#-:-NCtnmz48sFjhRhhUEiS:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @xuchenhan-tri)

**Pull request merged**
