### PR TITLE
Add required abstract geomery input model values

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Almost all DeclareAbstractInputPort calls should provide a model value.  Only if the system overrides DoAllocateInputAbstract may it be omitted.

This corrects missing allocators for geometry-related inputs.

Relates #9669 and #9670.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9671)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Comment by jwnimmer-tri** [comment]
Ugh, the merge of `geometry/dev` to master which duplicated a bunch of files and examples has totally clobbered this PR.  Stay tuned for more updates.

**Comment by jwnimmer-tri** [comment]
Hopefully fixed now, but its grown novel enough for +@EricCousineau-TRI for platform review, please.  @SeanCurtis-TRI only needs to feature review.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please.
(Testing post-merge of #9672, just in case)

**Pull request merged**
