### PR TITLE
Implements RollPitchYawToQuaternion()

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements a method to obtain an `Eigen::Quaternion` given the a set of Euler angles.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5438)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeBDn_ZpE1hF4Hzvfn:-KeeBDnaIUGzDKI7Pd9E:b-z7esiw) (no related file):*
Submitted in response to a thread [here](https://reviewable.io/reviews/robotlocomotion/drake/5419#-Ke_A1_kMD2-jfoUFYUf) in #5419. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeBDn_ZpE1hF4Hzvfn:-KeeBSoa100OS2qtt0CY:b-3rr2h) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Submitted in response to a thread [here](https://reviewable.io/reviews/robotlocomotion/drake/5419#-Ke_A1_kMD2-jfoUFYUf) in #5419. 
</blockquote></details>

+@hongkai-dai and @edrumwri for feature review since I believe you worked on the previous quaternion transformation methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438)*

**Comment by amcastro-tri** [comment]
cc'ing @liangfok

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/roll_pitch_yaw_using_quaternion.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeH7H89vb73RPH7Akj:-KeeH7H89vb73RPH7Akk:bxq461z) ([raw file](https://github.com/robotlocomotion/drake/blob/330ea1f273496d0c4a9a465f1abe21f823030a4e/drake/math/roll_pitch_yaw_using_quaternion.h#L47)):*
> ```objc
>  */
> template <typename Derived>
> Quaternion<typename Derived::Scalar> RollPitchYawToQuaternion(
> ```

BTW, `quaternion.h` has a function `quat2eigenQuaternion`, so you could reuse the code by return `quat2eigenQuaternion(rpy2quat(rpy))`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438)*

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by sherm1** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/math/roll_pitch_yaw_using_quaternion.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeiLhC-L_4xPVur9b9:-KeeiLhC-L_4xPVur9bA:b-6iekvu) ([raw file](https://github.com/robotlocomotion/drake/blob/330ea1f273496d0c4a9a465f1abe21f823030a4e/drake/math/roll_pitch_yaw_using_quaternion.h#L39)):*
> ```objc
>  * Computes the Quaternion representation of a rotation given the set of Euler
>  * angles describing this rotation. These angles follow the Tait–Bryan formalism
>  * about body-fixed z-y'-x'' axes.
> ```

BTW, mention that this is the same as a space-fixed x-y-z sequence.

---

*[drake/math/roll_pitch_yaw_using_quaternion.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeiX-AAN80T71Y1y-X:-KeeiX-AAN80T71Y1y-Y:b-dnt94b) ([raw file](https://github.com/robotlocomotion/drake/blob/330ea1f273496d0c4a9a465f1abe21f823030a4e/drake/math/roll_pitch_yaw_using_quaternion.h#L40)):*
> ```objc
>  * angles describing this rotation. These angles follow the Tait–Bryan formalism
>  * about body-fixed z-y'-x'' axes.
>  * @param rpy A vector in ℝ³ with the Euler angles `rpy = [roll, pitch, yaw]`.
> ```

BTW, these three angles do not form a (mathematical) vector. Really they are just being packed into a convenient Eigen container for three numbers. Better just to say this is a Vector3 containing the rpy angles. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeBDn_ZpE1hF4Hzvfn:-Keeoi_fJW09up5P17nb:b-cmbozg) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

+@hongkai-dai and @edrumwri for feature review since I believe you worked on the previous quaternion transformation methods.
</blockquote></details>

I addressed the reviews. PTAL

---

*[drake/math/roll_pitch_yaw_using_quaternion.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeiLhC-L_4xPVur9b9:-KeenWg6cUA74trb3OPc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/330ea1f273496d0c4a9a465f1abe21f823030a4e/drake/math/roll_pitch_yaw_using_quaternion.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, mention that this is the same as a space-fixed x-y-z sequence.
</blockquote></details>

Done.

---

*[drake/math/roll_pitch_yaw_using_quaternion.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeiX-AAN80T71Y1y-X:-Keenm_Ddgn3Ih_824GF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/330ea1f273496d0c4a9a465f1abe21f823030a4e/drake/math/roll_pitch_yaw_using_quaternion.h#L40)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, these three angles do not form a (mathematical) vector. Really they are just being packed into a convenient Eigen container for three numbers. Better just to say this is a Vector3 containing the rpy angles. 
</blockquote></details>

Done.

---

*[drake/math/roll_pitch_yaw_using_quaternion.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-KeeH7H89vb73RPH7Akj:-KeeoXvB7-2H-eBlxmRN:b-9y2da6) ([raw file](https://github.com/robotlocomotion/drake/blob/330ea1f273496d0c4a9a465f1abe21f823030a4e/drake/math/roll_pitch_yaw_using_quaternion.h#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, `quaternion.h` has a function `quat2eigenQuaternion`, so you could reuse the code by return `quat2eigenQuaternion(rpy2quat(rpy))`.
</blockquote></details>

Excellent! thanks! It'd be so much nicer if all this was inside `Eigen::Quaternion`... one day, maybe one day...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-:-Keeuxatngah1WXeFzP1:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-:-Keew8XrGaFZgl3Wfy9A:bnfp4nl)*

**Comment by edrumwri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5438#-:-Keez1kTerzy6VCpWun9:bnfp4nl)*

**Pull request merged**
