### PR TITLE
docker: Fix acrobot target. Minor doc fixes

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Periodic check of Docker instructions, found that this target was stale.
Also does minor reformatting of the docs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8542)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature and platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8542#-:-L9abmLs5NpzM_4PCWHy:b-5a5hi0)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.  I assume you've tested it locally which can count as feature review.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8542#-:-L9b3o6VD0qR2zDNfV09:b-43j66w)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8542)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please.

**Pull request merged**
