### PR TITLE
Quadratic cost added

### PR DESCRIPTION
**Pull request by naveenoid**
Implementation of Quadratic Cost independent to Generic Cos. Also existing nonlinear solvers to additionally use QuadraticCosts in their overall evaluation. 

Feature : +@sammy-tri 
Platform : +@david-german-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2678)

### CODE REVIEW

**Comment by naveenoid** [comment]
I will remove do not review as soon as Jenkins is happy (I cannot currently test IPOpt on OSX)

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/Optimization.h, line 814 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2678#-KLN8WrZAXn12LTINp0t:-KLN8WrZAXn12LTINp0u:-642921319) ([raw file](https://github.com/robotlocomotion/drake/blob/db59d4816f97f84ebe3bf3109ed079f670760b46/drake/solvers/Optimization.h#L814)):*
> ```objc
>   std::list<Binding<Constraint>> generic_constraints_;
>   std::list<Binding<Constraint>> quadratic_costs_;
>   std::list<Binding<Constraint>> quadratic_constraints_;
> ```

It seems like it's a little early to add this if it's only used in a getter and never set?

---

*[drake/solvers/SnoptSolver.cpp, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2678#-KLN8lJ_ECZv52w-ct7h:-KLN8lJ_ECZv52w-ct7i:1779103979) ([raw file](https://github.com/robotlocomotion/drake/blob/db59d4816f97f84ebe3bf3109ed079f670760b46/drake/solvers/SnoptSolver.cpp#L22)):*
> ```cpp
> // todo(sammy-tri) :  return more information that just the solution (INFO, infeasible
> // constraints, ...)
> // todo(sammy-tri) :  avoid all dynamic allocation
> ```

These 4 TODOs predate me be quite a bit...  though actually some of them are partially done (by me) so perhaps they should be left like that for me to clean up.   sigh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2678)*

**Comment by naveenoid** [comment]
I may have introduced merge artefacts but probably not.  If I should rollback and rebase instead, please let me know. I think its sufficient to review the same files that @sammy-tri reviewed earlier.

---

Review status: 0 of 55 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/Optimization.h, line 814 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2678#-KLN8WrZAXn12LTINp0t:-KLQD4X0V4W1EQOpRNuz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/db59d4816f97f84ebe3bf3109ed079f670760b46/drake/solvers/Optimization.h#L814)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> It seems like it's a little early to add this if it's only used in a getter and never set?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2678#-:-KLQD7C49mNsYAPS4q3T:-677042029)*

**Comment by liangfok** [comment]
I'm seeing unrelated merge artifacts unfortunately. Last this time happened to me, I had to close this PR and then submit a new one.

---

Review status: 0 of 55 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2678#-:-KLQRD9is2QgFtjS9Tnu:-738608311)*

**Comment by naveenoid** [comment]
ok I think I will do that too to be safe..its not too hard to start from a clean branch

---

Review status: 0 of 55 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2678#-:-KLQqrdCf_fgoYmQUjHD:422745475)*

**Comment by naveenoid** [comment]
I will close this and build a new PR without merge issues

**Pull request closed without merging**
