### PR TITLE
[doc] Add new Doxygen header, footer, and style customizations

### LINKED ISSUE #16993: Add uniform style for Doxygen and Pydrake API reference
Split out from https://github.com/RobotLocomotion/drake/issues/14757#issue-826830314 for tracking purposes.

The main drake.mit.edu website has a nice style (the red color, logo, etc.).  We should apply the same to the Doxygen and Pydrake API references.

Specific suggestions:
- Add backlinks to top page, tweak header style for color.
- Make it as nice as possible, within the budget.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #16993.

Local preview is available as:
```
bazel run //doc/doxygen_cxx:build -- --serve
```

---

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N-xtVrpAbpLAzfRR3EH:blr65vz)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Class name links used to be blue, now they are a mix of blue and red. Is that intentional? If so, what is the distinction between the blue and red ones? Here is a sample from Cache:


Lunch checkpoint.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N-y2gIG9XZo-wMuvd-S:b-ymr5an)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
I believe the color difference comes from whether the link has been previously visited or not.  I _thought_ that's what the main site [drake.mit.edu/](https://drake.mit.edu/) was also doing, but now I see that things there are always red, I think?  This seems like a bug in the style sheet.  I'll check with the contractor.

**Comment by rpoyner-tri** [comment]
I think the red/blue thing is just the typical browser trick of different colors for links you've already visited. We could maybe quibble with the color choices...

Took a casual look at some pages with which I am familiar. Big :thumbsup: for better styling of code/fixed-with elements in running text!

**Review by sherm1 — COMMENTED** [review]
I can confirm that in the new style the red links turn blue after I visit them. At least for me, the old style had all the links blue regardless of whether I had visited them (same Chrome browser). I'm not sure there is much value in color changing links in Doxygen, but I have no objection if that is intentional.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N-yIY5wCo2mMrqE6SDE:b-yibz74)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
The new layout looks fine to me. I was surprised though at how much code is added here (1300 inscrutable lines) for what appears to be only a marginal change.  IMO it looks a _little_ better than the existing Doxygen but not 1300 lines worth.

But :lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N-yN-530gsg4PlmueIM:b-12hybp)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16960#-N-yNnk60RWIedAP_N5s:-N-yNnk60RWIedAP_N5t:b-z5veed) (no related file):*
Working

Need to fix link blue/red style before merging.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

___
*[doc/doxygen_cxx/doxygen_extra.css, line 1315 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16960#-N-yO-Fr7Ckii0E6m6y7:-N-yO-Fr7Ckii0E6m6y8:b-q1ypjf) ([raw file](https://github.com/robotlocomotion/drake/blob/da22e7d25e83a2ce6143dda64c6a00f99c75b81a/doc/doxygen_cxx/doxygen_extra.css#L1315)):*
> ```CSS
> h2.groupheader {
> 	color: black;
> 	border-bottom: 1px solid #b5b5b5;
> ```

nit It looks like I missed some whitespace fixups.  This file is not supposed to have literal tabs, nor it is supposed to have any trailing whitespace.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16960#-N-yNnk60RWIedAP_N5s:-N02OHsx4FvUu3L4N--w:b-xmdn90) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Need to fix link blue/red style before merging.
</blockquote></details>

I've confirmed that the red/blue distinction was unintentional.  Stay tuned for the fix (so it's all red).

---

**Review by jwnimmer-tri — COMMENTED** [review]
(Rebase conflict fixed.  Still waiting on contractors for the hyperlink style fix.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N0C1eDV6gPM1gmQGPiH:be7z9bs)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 1 unresolved discussion (waiting on @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[doc/doxygen_cxx/doxygen_extra.css, line 1315 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16960#-N-yO-Fr7Ckii0E6m6y7:-N0CxNnf5FIrMxwAtETQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/da22e7d25e83a2ce6143dda64c6a00f99c75b81a/doc/doxygen_cxx/doxygen_extra.css#L1315)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It looks like I missed some whitespace fixups.  This file is not supposed to have literal tabs, nor it is supposed to have any trailing whitespace.
</blockquote></details>

Done.
___
*[doc/BUILD.bazel, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16960#-N0Cwq20-NclG-TQthVf:-N0Cwq20-NclG-TQthVg:bou7igp) ([raw file](https://github.com/robotlocomotion/drake/blob/f71d2701033a0047a49feb26caf7b3135749bf96/doc/BUILD.bazel#L25)):*
> ```Starlark
>     name = "defs",
>     srcs = ["defs.py"],
>     data = [
> ```

FYI The changes to header and foot image preview have already been merged into master, so they no longer appear in this PR.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I worked through the CXX fix on my own.  Please confirm in your local preview that the links are well-styled now.  There should be no more blue links, only red.  In particular please check that the navigation menus still work for you.  (They are usually red background, not red foreground; in some earlier drafts, I had red foreground _and_ background, which of course doesn't work well.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N0CzxL9BQQx05iFTCuX:blmavkb)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16960#-N-yNnk60RWIedAP_N5s:-N0CzwQMDLlkNlLhkIhm:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I've confirmed that the red/blue distinction was unintentional.  Stay tuned for the fix (so it's all red).
</blockquote></details>

Done.

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
I can confirm that the links are red and stay that way now. I spotted another problem with this style sheet though. Formerly back-ticked code was rendered in a fixed font but otherwise was the same color as normal text. Now it is rendered in pink and looks very different than other text. Several problems with that:
- it seems more extreme than is warranted, making the text look clickable even though it is just fixed width
- worse, it now makes the formatting inconsistent because we don't require perfect consistency of back-ticking and other ways of getting fixed-width fonts don't trigger the highlighting. Here is an example:



Note that the same symbols occur nearly adjacent but in different colors. There is no corresponding difference in meaning.

My suggestion would be to continue rendering the back-ticked stuff in black. I don't think the new color scheme is adding anything and it is definitely a notch down in consistency. :lgtm_cancel: for discussion

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N0D4iiz25ZWN3QbdDxa:b-tbvie6)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Done.  I changed `<code>` to match our regular paragraph text color.

For the record, it looks like the style inconsistency you noted was for `<code>` (pink) vs `<pre>` (black) blocks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N0DC1VxDpkKg_Ss4OxZ:bh6qi9m)* status: LGTM missing from assignee sherm1(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
Looks great now, thanks!
:lgtm: 

> Reviewed 1 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16960#-:-N0DIemd0i19ZSQ8Amho:bs0eygs)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
