### PR TITLE
pydrake: Add roll-up of symbols which still allows decoupled testing.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
\cc @gizatt @peteflorence 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7911)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@sammy-tri for platform review, please.

\cc @russtedrake Would this help consolidate the code for class examples? (per prior discussions)

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-:-L47U_5FTLdadBwqMyOS:bltx28)*

**Comment by EricCousineau-TRI** [comment]
Relates to #7912.

**Comment by jwnimmer-tri** [comment]
So I've read this code and I can see what's specifically different, but could you please provide a more detailed explanation or sample that illustrates how a developer (or user?) would benefit from this change overall?

---

Reviewed 9 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/all.py, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47iVeIc7BzFhv-7Xef:-L47iVeJVWL-4QyX85Fv:b-zfg6k4) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/all.py#L6)):*
> ```Python
> Please *only* use `all` modules when the convenience is worth it, e.g.
> for introductory examples, or when tinkering in a REPL interface.
> If writing production code, *please* use the actual modules.
> ```

FYI  When I first read this I didn't really understand well.  Coming back to it after finishing the PR it makes sense now, but I'll try to offer a guess as to what would have helped me more the first time.

Something like these ideas in this order (but in prose form):
- The `all` modules in pydrake are intended as convenient end-user shortcut for interactive or tutorial use.
- Code within pydrake itself should not use the `all` shortcut, but rather import only exactly what is needed.
- The downside of importing an `all` module is .. TBD.  (I guess I'm unclear on what "worth it" meant?)

It might also be useful, in the doc here, to show an example of how a user would import this?  (Possibly also an example of how prod code _should not_ use it (i.e., spell out the alternative with an example.)

---

*[bindings/pydrake/BUILD.bazel, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47g3oYJ6JUZTMZo7V2:-L47g3oZUsHd43Muznc-:b-iveo1l) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/BUILD.bazel#L165)):*
> ```Python
> drake_py_test(
>     name = "all_test",
>     deps = ["all_py"],
> ```

BTW `:all_py` by convention?  (I'm surprised buildifier didn't fix it, actually.)

---

*[bindings/pydrake/test/all_test.py, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47grqOiHVWaVx69ugA:-L47grqOiHVWaVx69ugB:b-klf5f) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/test/all_test.py#L4)):*
> ```Python
> 
> import unittest
> import pydrake.common
> ```

This seems unfriendly?  As a user I would expect `from pydrake.all import *` to be the only line that I'd need.  (I saw some related discussion on github; should there be a TODO here?)

---

*[bindings/pydrake/test/all_test.py, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47gf9GFInPlt3kynRu:-L47gf9HOfScJlJ9BsWs:b-18fojo) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/test/all_test.py#L37)):*
> ```Python
>         # statement.
>         for expected_symbol in expected_symbols:
>             assert expected_symbol in globals()
> ```

Prefer `unittest self.assertSomething` for unit tests?

---

*[tools/skylark/pybind.bzl, line 262 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47aQSybysYBie9YzWm:-L47aQSybysYBie9YzWn:b-ch59vt) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/tools/skylark/pybind.bzl#L262)):*
> ```Python
>         deps = []):
>     """Defines a roll-up `all` module, and ensures that its not included in
>     `deps`.
> ```

The "ensures not included" phrase mislead me for a while.  I took it as fact (interpreting "ensures" to mean "demands") and then read the calling code and was confused.

As it turns out, this macro doesn't "demand" at all.  It actually _removes_ `:all_py` from deps, out from under us!  To me that was a surprising formulation of how `deps` is understood in Bazeldom.

If the thesis is something like that we're going to declare a library `:name` whose src is already `all.py`, and so its correct to strip the deps and add the src, then it seems like we should _insist_ that deps has `:name`, instead of having an if-check.

I could probably get on board with that formulation (its obscure, but at least is rigid and fails fast), though I would still prefer to `deps` be truth (and not contain `:all_py` when drake_py_all_library called).

---

*[tools/skylark/pybind.bzl, line 262 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47ay-ZRIJ8X48umx7b:-L47ay-ZRIJ8X48umx7c:bkzytea) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/tools/skylark/pybind.bzl#L262)):*
> ```Python
>         deps = []):
>     """Defines a roll-up `all` module, and ensures that its not included in
>     `deps`.
> ```

BTW Document that the source file name is assumed to be `all.py`?

---

*[tools/skylark/pybind.bzl, line 265 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47g6hheU-001PwBI2E:-L47g6hheU-001PwBI2F:b-z6zn5q) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/tools/skylark/pybind.bzl#L265)):*
> ```Python
>     """
>     target = ":" + name
>     if target in deps:
> ```

FYI Should probably also disallow `name` directly (since the colon is optional?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-:-L47cWW40acInjiKd8Uj:b-5953g3)*

**Comment by jwnimmer-tri** [comment]
Is the gist just that a user can `from pydrake.all import *` as sugar?  If so then probably this PR could merge without any extra docs, though maybe http://drake.mit.edu/python_bindings.html could get a three-line example?

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-:-L47kV-wJU9l1ZGXk1_I:bbehzut)*

**Comment by sammy-tri** [comment]
First pass complete.  I didn't have anything to add beyond Jeremy's existing comments.

---

Reviewed 9 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-:-L48VuIy1DlMAAVJx02d:b-s7jveu)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/all.py, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47iVeIc7BzFhv-7Xef:-L4IClQ8zmqHrWI3xQs6:b-7ddm5c) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/all.py#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI  When I first read this I didn't really understand well.  Coming back to it after finishing the PR it makes sense now, but I'll try to offer a guess as to what would have helped me more the first time.

Something like these ideas in this order (but in prose form):
- The `all` modules in pydrake are intended as convenient end-user shortcut for interactive or tutorial use.
- Code within pydrake itself should not use the `all` shortcut, but rather import only exactly what is needed.
- The downside of importing an `all` module is .. TBD.  (I guess I'm unclear on what "worth it" meant?)

It might also be useful, in the doc here, to show an example of how a user would import this?  (Possibly also an example of how prod code _should not_ use it (i.e., spell out the alternative with an example.)
</blockquote></details>

Done. Moved examples to exclusively be in `doc/python_bindings.rst` to reduce number of duplicates for testing.

---

*[bindings/pydrake/BUILD.bazel, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47g3oYJ6JUZTMZo7V2:-L4ICtS__P9Beul0MzSv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/BUILD.bazel#L165)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `:all_py` by convention?  (I'm surprised buildifier didn't fix it, actually.)
</blockquote></details>

Done.

---

*[bindings/pydrake/test/all_test.py, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47grqOiHVWaVx69ugA:-L4ICzaPc2CHEjVvcgoV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/test/all_test.py#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems unfriendly?  As a user I would expect `from pydrake.all import *` to be the only line that I'd need.  (I saw some related discussion on github; should there be a TODO here?)
</blockquote></details>

Done.

---

*[bindings/pydrake/test/all_test.py, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47gf9GFInPlt3kynRu:-L4ID07reMY6jRGELI2r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/bindings/pydrake/test/all_test.py#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Prefer `unittest self.assertSomething` for unit tests?
</blockquote></details>

Done.

---

*[tools/skylark/pybind.bzl, line 262 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47aQSybysYBie9YzWm:-L4ID2nYAQjqzks8cHs1:bn2vk37) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/tools/skylark/pybind.bzl#L262)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The "ensures not included" phrase mislead me for a while.  I took it as fact (interpreting "ensures" to mean "demands") and then read the calling code and was confused.

As it turns out, this macro doesn't "demand" at all.  It actually _removes_ `:all_py` from deps, out from under us!  To me that was a surprising formulation of how `deps` is understood in Bazeldom.

If the thesis is something like that we're going to declare a library `:name` whose src is already `all.py`, and so its correct to strip the deps and add the src, then it seems like we should _insist_ that deps has `:name`, instead of having an if-check.

I could probably get on board with that formulation (its obscure, but at least is rigid and fails fast), though I would still prefer to `deps` be truth (and not contain `:all_py` when drake_py_all_library called).
</blockquote></details>

Done. Nuked `drake_py_all_library` for simplicity.

---

*[tools/skylark/pybind.bzl, line 262 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47ay-ZRIJ8X48umx7b:-L4ID5qJ7owNsB9YFX3B:bn2vk37) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/tools/skylark/pybind.bzl#L262)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Document that the source file name is assumed to be `all.py`?
</blockquote></details>

Done. Nuked `drake_py_all_library` for simplicity.

---

*[tools/skylark/pybind.bzl, line 265 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-L47g6hheU-001PwBI2E:-L4ID6G7TDB2iP_qtXfs:bn2vk37) ([raw file](https://github.com/robotlocomotion/drake/blob/fdb14b097169a03f2a2df06a2ce067c8a12517dd/tools/skylark/pybind.bzl#L265)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Should probably also disallow `name` directly (since the colon is optional?).
</blockquote></details>

Done. Nuked `drake_py_all_library` for simplicity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-:-L4IFElIngYLYApiBiDS:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7911#-:-L4IhvZSAK7hRCeM1Cas:bnfp4nl)*

**Pull request merged**
