### PR TITLE
Add SpatialInertia::SolidCubeWithDensity()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/18866 is work to helping resolve part of issue https://github.com/RobotLocomotion/drake/issues/18416.

**Review by mitiguy — COMMENTED** [review]
Feature review +@SeanCurtis-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-:-NP0LydP9QftDoc2Oskv:b-j0fgx5)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-:-NPJ3sl0B_-PJyGa34LJ:bnfp4nl)* status: 3 unresolved discussions (waiting on @mitiguy)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866)* status: 4 unresolved discussions (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-NPJ46WF3e99AzQFCIzX:-NPJ46WF3e99AzQFCIzY:b98prxu) ([raw file](https://github.com/RobotLocomotion/drake/blob/c714e662811c0578673a8e12c4ae8e8087d44e5a/multibody/tree/spatial_inertia.cc#L38)):*
> ```cpp
> template <typename T>
> SpatialInertia<T> SpatialInertia<T>::SolidCubeWithDensity(
>     const T& density, const T& l) {
> ```

minor:  Why not just`return SolidBoxWithDensity(density, l, l, l);`?

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`multibody/tree/spatial_inertia.h` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-NPIN8Tj1PjKH7RCYbvE:-NPJtfi2C5BIpkjwVUju:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c714e662811c0578673a8e12c4ae8e8087d44e5a/multibody/tree/spatial_inertia.h#L143)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: You've otherwise consistently made use of the *full* monogram notation throughout this family of functions. We should probably stay consistent. You can still make your point about the fact that the expressed-in frame doesn't matter, but, as a starting point, its absence probably causes more confusion than help.

(In fact, I first misread the comment, with my imagination filling in the missing underscore, which made the "'s" nonsensical.)
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.h` line 147 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-NPIO09G47jr9lRfMXSF:-NPJtix5-44ucUW1lB1n:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c714e662811c0578673a8e12c4ae8e8087d44e5a/multibody/tree/spatial_inertia.h#L147)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit; Extraneous possessive.
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-NPJ46WF3e99AzQFCIzX:-NPJuMNcDRgqxfrLsgaF:b-l1ihdz) ([raw file](https://github.com/RobotLocomotion/drake/blob/c714e662811c0578673a8e12c4ae8e8087d44e5a/multibody/tree/spatial_inertia.cc#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Why not just`return SolidBoxWithDensity(density, l, l, l);`?
</blockquote></details>

Yes -- I agree that can be done.  
The overarching PR is to have a SpatialInertia for each UnitInertia.
I would have preferred that there was no UnitInertia for a solid cube, but since it exists, it seems reasonable to use it.
___
*[`multibody/tree/spatial_inertia.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-NPIOsEt8h3lsaWMyjs8:-NPJuEzyEolqPAQoYbVn:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c714e662811c0578673a8e12c4ae8e8087d44e5a/multibody/tree/spatial_inertia.cc#L41)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: very funky formatting
</blockquote></details>

Done.

**Review by mitiguy — COMMENTED** [review]
@ggould-tri   -- FYI blocking comment ?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-:-NPKBGuX1AiDbB5VBGvr:bct3tis)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by mitiguy — COMMENTED** [review]
@ggould-tri  Note:  A little while ago today, I merged another pR into the same 3 files that this PR uses.
As such, I think it best for me to manually rebase on the then current master before trying to squash/merge.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-:-NPKJB-H2P48q9zxcdwt:b11nfgo)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-release  please.

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18866#-:-NPP9NIYDKLY-iNdUDdC:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @mitiguy)

**Pull request merged**
