### PR TITLE
Add A_sparse and A_dense to L2NormCost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is a preparation PR for #20552

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
Good call, thanks Jeremy.

+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-:-Nu-fJf34YMDCJr6Al5u:bo6wqe6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
I am unclear on why this is on the critical path for #20552 (or even part of the plan at all).  I'm guessing that it's because the solver back-ends will need the sparse A in order to solve efficiently, but if that were the only reason then the easier path forward is just to have each solver convert to sparse when necessary, instead of changing this user-facing Cost object.

CI needs some linter fixes.

> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-:-Nu02L2d2uY-CxrLSxXF:bvjp41a)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`solvers/cost.h` line 325 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu03mgw7ZLMpDxkcdow:-Nu03mgw7ZLMpDxkcdox:biea1vc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f54336e5d1e4fa2dd9d2922ddcb220ad322a8a8/solvers/cost.h#L325)):*
> ```objc
>   const Eigen::MatrixXd& A() const { return A_dense(); }
> 
>   const Eigen::SparseMatrix<double>& A_sparse() const {
> ```

The `LinearConstraint` calls this `get_sparse_A` (and the other getter `GetDenseA`).

We should probably have some consistency across our various costs and constraints about how to name the getters?
___
*[`solvers/cost.h` line 329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu03_iIA9ZWff-6PI0C:-Nu03_iJ0Vb_dtZxbf9M:b-3lr8fj) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f54336e5d1e4fa2dd9d2922ddcb220ad322a8a8/solvers/cost.h#L329)):*
> ```objc
>   }
> 
>   const Eigen::MatrixXd& A_dense() const { return A_.GetAsDense(); }
> ```

As currently implemented, this cannot have a snake_case name because it might not be fast (constant-time complexity).

However, all of the Eval functions always convert to dense anyway, so if that's the long-term plan then the constructor could convert to dense up-front and then this function can use a snake_case name.

**Review by hongkai-dai — COMMENTED** [review]
> I am unclear on why this is on the critical path for [ AddL2NormCost is a footgun #20552](https://github.com/RobotLocomotion/drake/issues/20552) (or even part of the plan at all). I'm guessing that it's because the solver back-ends will need the sparse A in order to solve efficiently

Exactly! Also to stay consistent with LinearConstraint and LorentzConeConstraint which provide the sparse A matrix.

I can hold on this PR for the moment and work on the other PRs that resolves #20552 more directly.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-:-Nu0ovWP4aU4acIidilx:b-ldt96g)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Okay, so the purpose of this PR is three things?

(1) Consistency.

(2) If users already have a sparse A, then passing that directly to the solvers can be more efficient.

(3) If users are solving the same program more than once, having the sparse form in the constraint object means that the solvers won't re-compute it every Solve.

Did I get it right?

Those are fine goals and I'm happy to continue review here under those goals, but the code still need some rework before it meets those goals.  I'll defer to whatever pace you want.

**Review by hongkai-dai — COMMENTED** [review]
Yes, that is exactly right, thanks for the nice summary.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-:-Nu5HANA4HbRnduY4gXE:b-j2pg4p)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`solvers/cost.h` line 325 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu03mgw7ZLMpDxkcdow:-Nu5HM5GEIUcjltQZ8TJ:ba3r5eu) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f54336e5d1e4fa2dd9d2922ddcb220ad322a8a8/solvers/cost.h#L325)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `LinearConstraint` calls this `get_sparse_A` (and the other getter `GetDenseA`).

We should probably have some consistency across our various costs and constraints about how to name the getters?
</blockquote></details>

I think `get_sparse_A` and `GetDenseA` are good names. I will change the LorentzConeConstraint and RotatedLorentzConeConstraint to follow this convention, in a separate PR.

The L1NormCost and LinfNormCost also returns the dense A in `A()` function, I will change those in another separate PR as well.
___
*[`solvers/cost.h` line 329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu03_iIA9ZWff-6PI0C:-Nu5I3RM10266gqXYq6m:b-i9awok) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f54336e5d1e4fa2dd9d2922ddcb220ad322a8a8/solvers/cost.h#L329)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As currently implemented, this cannot have a snake_case name because it might not be fast (constant-time complexity).

However, all of the Eval functions always convert to dense anyway, so if that's the long-term plan then the constructor could convert to dense up-front and then this function can use a snake_case name.
</blockquote></details>

I actually prefer not to always convert to dense. I am working on PRs such that we don't often call `Eval` function for L2NormCost. Ideally the convex solvers (Clarabel, SCS, Gurobi, Mosek) will treat L2NormCost as a slack variable with a LorentzConeConstraint, and don't call Eval function. Only the nonlinear nonconvex solvers (such as snopt and ipopt) will call the Eval function, but that is not the best use of L2NormCost.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-:-Nu5ciJ9-oYfCcAV9BqA:b-n37teh)* status: 4 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 651 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5ZrD-0gSEVOupdPzX:-Nu5ZrD-0gSEVOupdPzY:bnk79b7) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/geometry/optimization/graph_of_convex_sets.cc#L651)):*
> ```cpp
>     A_cone.block(1, 0, l2c->get_sparse_A().rows(), 1) = l2c->b();  // bϕ.
>     A_cone.block(1, 2, l2c->get_sparse_A().rows(), l2c->get_sparse_A().cols()) =
>         l2c->GetDenseA();  // Ax.
> ```

I'm not what the reason is for preferring dense assignment here?

Here (and below at 1375), if I change `GetDenseA` to `get_sparseA()` all of the code compiles and passes its tests.
___
*[`solvers/cost.h` line 329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu03_iIA9ZWff-6PI0C:-Nu5YAS78XlJ9fhCn_zs:b-x98kof) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f54336e5d1e4fa2dd9d2922ddcb220ad322a8a8/solvers/cost.h#L329)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I actually prefer not to always convert to dense. I am working on PRs such that we don't often call `Eval` function for L2NormCost. Ideally the convex solvers (Clarabel, SCS, Gurobi, Mosek) will treat L2NormCost as a slack variable with a LorentzConeConstraint, and don't call Eval function. Only the nonlinear nonconvex solvers (such as snopt and ipopt) will call the Eval function, but that is not the best use of L2NormCost.
</blockquote></details>

Yup.  I eventually realized that on my own, too.

Aside: I suppose the `Eval()` could do a sparse dot product (maybe depending on the nnz / size ratio?).  Anyway, this particular review discussion is resolved just fine, no action required.
___
*[`solvers/test/cost_test.cc` line 499 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5bdDb-cKlnLwQU5FO:-Nu5bdDb-cKlnLwQU5FP:b-ju6nsk) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/solvers/test/cost_test.cc#L499)):*
> ```cpp
>   cost.UpdateCoefficients(new_A, Vector4d::Zero());
>   EXPECT_EQ(cost.get_sparse_A().rows(), 4);
>   EXPECT_EQ(cost.GetDenseA().rows(), 4);
> ```

nit Now that we're calling CompareMatrices on the full `cost.get_sparse_A()` and `cost.GetDenseA()`, I think we can lean on that to check their size?  I don't understand the purpose of these two EXPECT_EQ on A's size.
___
*[`solvers/test/cost_test.cc` line 505 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5c7RAC2iwqMzKU4Vq:-Nu5c7RB6VahtgaAiGvJ:b-k067hk) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/solvers/test/cost_test.cc#L505)):*
> ```cpp
> 
>   // Call UpdateCoefficients with a sparse A.
>   cost.UpdateCoefficients(new_A.sparseView(), Vector4d::Zero());
> ```

The coeffs in `cost` were already set to `new_A` here.  This function's implementation could be a no-op and we wouldn't notice, right?  I think we need a different `new_A` value (and shape?) here, to make sure the implementation is actually working correctly.
___
*[`bindings/pydrake/solvers/solvers_py_evaluators.cc` line 704 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5cMXnBFTpeq8ncqdH:-Nu5cMXnBFTpeq8ncqdI:boiwpfm) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/bindings/pydrake/solvers/solvers_py_evaluators.cc#L704)):*
> ```cpp
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>     // To be removed on 2024-08-01.
>     cls.def("A", &L2NormCost::A);
> ```

We need a `WrapDeprecated(...)` here so that the Python user receives a deprecation warning. 

After that, the unit test will also need a change to notice the warning (`catch_drake_warnings`).

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 651 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5ZrD-0gSEVOupdPzX:-Nu65ErfC9PmWp_K6TlN:bygz5tf) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/geometry/optimization/graph_of_convex_sets.cc#L651)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not what the reason is for preferring dense assignment here?

Here (and below at 1375), if I change `GetDenseA` to `get_sparseA()` all of the code compiles and passes its tests.
</blockquote></details>

Done. Good call, I didn't realize that we can assign a sparse matrix to a dense matrix.
___
*[`solvers/test/cost_test.cc` line 499 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5bdDb-cKlnLwQU5FO:-Nu65U4IBclvE_3Rw-DW:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/solvers/test/cost_test.cc#L499)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Now that we're calling CompareMatrices on the full `cost.get_sparse_A()` and `cost.GetDenseA()`, I think we can lean on that to check their size?  I don't understand the purpose of these two EXPECT_EQ on A's size.
</blockquote></details>

Done.
___
*[`solvers/test/cost_test.cc` line 505 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5c7RAC2iwqMzKU4Vq:-Nu65iFz0L9m1mJP5mJf:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/solvers/test/cost_test.cc#L505)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The coeffs in `cost` were already set to `new_A` here.  This function's implementation could be a no-op and we wouldn't notice, right?  I think we need a different `new_A` value (and shape?) here, to make sure the implementation is actually working correctly.
</blockquote></details>

Done. Good call.
___
*[`bindings/pydrake/solvers/solvers_py_evaluators.cc` line 704 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu5cMXnBFTpeq8ncqdH:-Nu6IbCUBP4fjG9004D7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d14760bba0ff3bdd069e72ea077da966b0b11655/bindings/pydrake/solvers/solvers_py_evaluators.cc#L704)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We need a `WrapDeprecated(...)` here so that the Python user receives a deprecation warning. 

After that, the unit test will also need a change to notice the warning (`catch_drake_warnings`).
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`bindings/pydrake/solvers/solvers_py_evaluators.cc` line 681 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21199#-Nu6Jl5zBsHUZuD7BXfF:-Nu6Jl5zBsHUZuD7BXfG:b-3hs9xd) ([raw file](https://github.com/RobotLocomotion/drake/blob/6cd826f77e414e2f54a17f93a2b066994f470d58/bindings/pydrake/solvers/solvers_py_evaluators.cc#L681)):*
> ```cpp
>         }),
>             py::arg("A"), py::arg("b"), doc.L2NormCost.ctor.doc_sparse_A)
>         .def("get_sparse_A", &L2NormCost::get_sparse_A,
> ```

nit Hmm, I missed it in the first review, but -- the new getters here need pydrake test coverage still.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21199)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Pull request merged**
