### PR TITLE
Revert "refactors dircol to use the system2.0 classes more completely"

### PR DESCRIPTION
**Pull request by jonathan-owens**
Reverts RobotLocomotion/drake#4399.

I'm not sure this commit was the problem with most of the linux nightlies failing, but I believe it is. Will revert and see what happens.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4437)

### CODE REVIEW

**Comment by jonathan-owens** [comment]
@drake-jenkins-bot linux-gcc-bazel-nightly-release please

**Comment by RussTedrake** [comment]
Can you link to the cdash failures for me?

**Comment by liangfok** [comment]
Here is one example: https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-mac-clang-nightly-minimal-debug-129&field2=buildstarttime&compare2=84&value2=now

**Comment by liangfok** [comment]
The error is:
```
C++ exception with description "Failure at /Users/elcapitan/workspace/mac-clang-nightly-minimal-debug/drake/../drake/systems/analysis/simulator.h:380 in StepTo(): condition 'boundary_time >= context_->get_time()' failed." thrown in the test body.
```

**Comment by david-german-tri** [comment]
The original post said "linux nightlyies" but presumably meant "mac nightlies" (as per @liangfok's link and https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/)

We can also see this in continuous Mac builds, e.g. here since #1027 (https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-clang-ninja-continuous-debug/), which did not include #4399, so I think this revert is a red herring.  Before closing it, though, let's run a Mac build just to be sure.

**Comment by jamiesnape** [comment]
We are talking about two different failures here.

**Comment by david-german-tri** [comment]
number 217 here: https://drake-jenkins.csail.mit.edu/view/OS%20X/job/mac-clang-ninja-experimental/#

**Comment by jamiesnape** [comment]
This looks like the error @jonathan-owens is talking about https://drake-cdash.csail.mit.edu/viewBuildError.php?onlydeltap&buildid=245583.

**Comment by jamiesnape** [comment]
It is a bazel error so we should fix forward.

**Comment by david-german-tri** [comment]
> It is a bazel error so we should fix forward.
Got it, and agreed.

**Comment by jamiesnape** [comment]
We do need a revert PR on #4431, though.

**Comment by david-german-tri** [comment]
> We do need a revert PR on #4431, though.
 
#4438, but I am hoping to fix forward.

**Pull request closed without merging**
