### PR TITLE
[render_vtk] Nerf the macOS arm64 tests even harder

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19424.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20205)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20205)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 555 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20205#-Ned81Tj5trbu602gHA2:-Ned8ocz815OcxqLGYfC:b-2vsp9o) ([raw file](https://github.com/RobotLocomotion/drake/blob/639bc661f35431196c23752c0f5b2ef6e2c71807/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L555)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW a "typical lifecycle" would include a bit more. I'd suggest it is worth beefing up the test slightly. I considered editing the file directly but didn't for two reasons:

1. I wanted to give you the chance to disagree.
2. I don't have permissions via github to simply edit in place and was too lazy to go the longer route (this was truly the *real* reason):

By the way, calling render on the *original* renderer is probably not typical of the lifespan, but it is typical of these tests. But rendering on the clone is very much typical.
</blockquote></details>

I don't think a test named `NoRender` should call `Render`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20205)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 555 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20205#-Ned81Tj5trbu602gHA2:-Ned93_L2qihMGyVrHND:b-8regxy) ([raw file](https://github.com/RobotLocomotion/drake/blob/639bc661f35431196c23752c0f5b2ef6e2c71807/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L555)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think a test named `NoRender` should call `Render`.
</blockquote></details>

Touche. I fixated on "typical lifecycle" and glossed over "NoRender".

That said, is having it not render truly desirable? Our problem on macOS is predicting what the CI images look like. But, surely, asking that it happen without complaint is worth testing. So, instead of `LifecycleNoRender` it should be `LifecycleSmoke`. We're exercising *most* of the `RenderEngine` API but missing out on `Render` seems like a glaring omission. After all, without calling `Render()` every other API is truly pointless.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20205)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 555 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20205#-Ned81Tj5trbu602gHA2:-NedCRZQ30AkA-e0GClS:b-ehfwxa) ([raw file](https://github.com/RobotLocomotion/drake/blob/639bc661f35431196c23752c0f5b2ef6e2c71807/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L555)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Touche. I fixated on "typical lifecycle" and glossed over "NoRender".

That said, is having it not render truly desirable? Our problem on macOS is predicting what the CI images look like. But, surely, asking that it happen without complaint is worth testing. So, instead of `LifecycleNoRender` it should be `LifecycleSmoke`. We're exercising *most* of the `RenderEngine` API but missing out on `Render` seems like a glaring omission. After all, without calling `Render()` every other API is truly pointless.
</blockquote></details>

Looking again, I see that my first draft was confused.  It claimed to not even touch OpenGL, but creating the engine (probably(?)) created an OpenGL context.

The better answer is "CI doesn't work.  Attempting to mitigate is falling into the trap of the sunk cost fallacy.  Just turn it all off, and instead invest time in fixing the CI servers, not mitigations."

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20205)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 555 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20205#-Ned81Tj5trbu602gHA2:-NedGaW67nJ_5M3OFA5-:b-qgkin9) ([raw file](https://github.com/RobotLocomotion/drake/blob/639bc661f35431196c23752c0f5b2ef6e2c71807/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L555)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Looking again, I see that my first draft was confused.  It claimed to not even touch OpenGL, but creating the engine (probably(?)) created an OpenGL context.

The better answer is "CI doesn't work.  Attempting to mitigate is falling into the trap of the sunk cost fallacy.  Just turn it all off, and instead invest time in fixing the CI servers, not mitigations."
</blockquote></details>

I like the resolution. Simple, unambiguous.

**Pull request merged**
