### PR TITLE
Remove deprecated code 2021-02

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14607)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape to feature review the setup (brew) change, please.

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14607#-:-MSY0swh2Bvpd18UCww7:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14607#-:-MSYUBteBkzLADWHw_IZ:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jamiesnape,sherm1(platform)

**Pull request merged**
