### PR TITLE
tools: Re-enable relnotes_test using new ubuntu_only macros

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Move its dependencies from maintainer-only to test-only.

This amends #14456, reverting the manual test marker added in #14466.

Closes #14465.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14470)

### CODE REVIEW

**Comment by jamiesnape** [comment]
The Mac maintainer prereqs are going to be nuked completely, IIRC?

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
> The Mac maintainer prereqs are going to be nuked completely, IIRC?

Maybe?  Though relnotes was never supported on macOS, so I don't think that matters in terms of this PR.

**Comment by jamiesnape** [comment]
> Maybe? Though relnotes was never supported on macOS, so I don't think that matters in terms of this PR.

Certainly not in the this PR, but Mac is in a semi-broken state with regard maintenance scripts in general.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@ggould-tri for platform review per schedule, please.

**Comment by jamiesnape** [comment]
(Since we nuked documentation generation on Mac, probably nuking maintainer script support on Mac makes sense. It only affects me, I imagine. We can discuss elsewhere.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14470#-:-MOm-2gV1sY9K1wOpoT7:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[tools/release_engineering/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14470#-MOm-KO4AsfYsGNtnRnx:-MOm-KO4AsfYsGNtnRny:b-f2rwtz) ([raw file](https://github.com/robotlocomotion/drake/blob/8d18244d64cc68836f510763432c225e72b883f1/tools/release_engineering/BUILD.bazel#L12)):*
> ```Starlark
> package(default_visibility = ["//visibility:private"])
> 
> drake_py_binary_ubuntu_only(
> ```

minor:  It would be helpful to document or TODO-to-issue here the reason that our release tooling doesn't support mac.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14470)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @ggould-tri and @rpoyner-tri)

___
*[tools/release_engineering/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14470#-MOm-KO4AsfYsGNtnRnx:-MOm7It4-wc1nQ6R-1AZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8d18244d64cc68836f510763432c225e72b883f1/tools/release_engineering/BUILD.bazel#L12)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It would be helpful to document or TODO-to-issue here the reason that our release tooling doesn't support mac.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14470)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14470#-:-MOmGBkI4ifG3WlRTlCw:bnfp4nl)* status: labeled "do not merge"

**Review by rpoyner-tri — COMMENTED** [review]
All that remains is removal of the DNM label. I don't see any comment explaining why, so I'm leaving as-is.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14470#-:-MOmGhcE-CmdL5kL3iFO:babzlxp)* status: labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Pull request merged**
