### PR TITLE
Add DISABLE_FORTRAN and DISABLE_PYTHON

### PR DESCRIPTION
**Pull request by jamiesnape**
Mostly for the benefit of the various memory checkers/sanitizers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4135)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@david-german-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
:lgtm: with one verification-of-intent question

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4135#-KWdU8SVvNH9pOYMumBQ:-KWdU8SW7wT2fB7fblSD:bprydpt) ([raw file](https://github.com/robotlocomotion/drake/blob/ec9486d8594e378136b3f80c9d99be3c254d2671/cmake/options.cmake#L218)):*
> ```CMake
> 
>   drake_optional_external(SWIGMAKE ON
>     DEPENDS "NOT DISABLE_MATLAB OR NOT DISABLE_PYTHON"
> ```

If *either* Python *or* MATLAB is not forcibly disabled, this will be built... is that correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4135#-:-KWdUyFUzZMT_HoCzFE5:bk9zbk1)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4135#-KWdU8SVvNH9pOYMumBQ:-KWdVLAwIWRiruY97MTN:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/ec9486d8594e378136b3f80c9d99be3c254d2671/cmake/options.cmake#L218)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> If *either* Python *or* MATLAB is not forcibly disabled, this will be built... is that correct?
</details>
Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4135)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4135#-:-KWe1ZwFA-NWMy2EcF3j:bnfp4nl)*

**Pull request merged**
