### PR TITLE
Add CheckSatisfiability and Minimize in DrealSolver

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7416)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
CI fails with the following message:

```
16:58:45 ERROR: /home/ubuntu/workspace/linux-xenial-clang-bazel-experimental-debug/src/drake/examples/cubic_polynomial/BUILD.bazel:7:1: Couldn't build file drake/examples/cubic_polynomial/region_of_attraction: Linking of rule '//drake/examples/cubic_polynomial:region_of_attraction' failed (Exit 1)
16:58:45 /usr/bin/ld: cannot find -lbz2
```

and I think the `-lbz2` part comes from `coinor-libclp-dev` package (which we have in the setup script).
FYI, `pkg-config clp --libs` gives us:
```
-lClp -lCoinUtils -lbz2 -lz -llapack -lblas -lm
```
I have no idea why `libbz2-dev` is not installed when `coinor-libclp-dev` is installed. Anyway, I think a quick fix is to include `libbz2-dev` in the setup script. @jamiesnape , could you give me an advice on this?

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
I was tracing through the dependencies and there is no mention of `libbz2-dev`. It looks like a bug with `coinor-libcoinutils-dev` that was not fixed until `artful`, so we need to explicitly add `libbz2-dev` to the setup script.

**Comment by soonho-tri** [comment]
+@jamiesnape , could you feature-review those files outside of `drake` directory?  (the ones related to #7387)

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-:-KyR5hY084IjPp8750WP:b-ga4k7m)*

**Comment by soonho-tri** [comment]
+@nikos-tri for feature-review, please (only the files in `drake` directory).

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-:-KySCn5TqRc-B-cAE6qA:b-z0qzy6)*

**Comment by soonho-tri** [comment]
To test it locally, please make sure running the script in `setup` first. We've added new packages recently.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-:-KySCzzEyYFerSW_DOvC:bzdab4)*

**Comment by nikos-tri** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/dreal_solver.h, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-KySdm8MRx8b76KYy0j4:-KySdm8MRx8b76KYy0j5:b-z2th7l) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/drake/solvers/dreal_solver.h#L46)):*
> ```objc
>   /// @returns a nullopt, if @p is unsatisfiable.
>   static optional<IntervalBox> CheckSatisfiability(const symbolic::Formula& f,
>                                                    double delta);
> ```

Maybe consider having a default value for delta? So the user can just call it without delta for simple cases, similar to the commandline interface of dReal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416)*

**Comment by soonho-tri** [comment]
I've found that I still need to add 'install'-related code. Will add soon.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/dreal_solver.h, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-KySdm8MRx8b76KYy0j4:-KyWJ0_Vtco7U7uOai-B:b-axymco) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/drake/solvers/dreal_solver.h#L46)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

Maybe consider having a default value for delta? So the user can just call it without delta for simple cases, similar to the commandline interface of dReal.
</blockquote></details>

I was thinking about this one. I think it's better to ask users to specify what he/she wants explicitly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-:-KyWJXdZ3Vo1pOnMrRBn:bujk4q2)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot, linux-xenial-gcc-bazel-experimental please.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-:-KyXBaX-5_fiKhvSru40:b8vsa45)*

**Comment by nikos-tri** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/dreal_solver.h, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-KySdm8MRx8b76KYy0j4:-KyXNGNOdi7Ya4I3yHE6:bg7igkv) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/drake/solvers/dreal_solver.h#L46)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I was thinking about this one. I think it's better to ask users to specify what he/she wants explicitly.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-:-KyXNJxs8CiZSh3ezn5I:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
Reviewed 1 of 2 files at r1, 7 of 12 files at r3.
Review status: 8 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tools/workspace/deb.bzl, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nEsmPiz5jhemTuI_l:-L-nEsmPiz5jhemTuI_m:b26hdut) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/deb.bzl#L40)):*
> ```Python
>             sha256 = ""
>         if not sha256:
>             # We can't permit an empty checksum; empty means "don't care".
> ```

`don't permit`?

---

*[tools/workspace/homebrew_bottle.bzl, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nEcw7BBahVVY9yyvj:-L-nEcw7BBahVVY9yyvk:bk0qk3r) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/homebrew_bottle.bzl#L11)):*
> ```Python
>     """
>     codenames = {
>         "10.11": "el_capitan",
> ```

BTW I would not object if you wanted to drop `el_capitan` since it is now unsupported by Drake.

---

*[tools/workspace/homebrew_bottle.bzl, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nCdCHsXc3bRDTK9GU:-L-nCdCHsXc3bRDTK9GV:b-gogjb4) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/homebrew_bottle.bzl#L55)):*
> ```Python
>     """
>     chmod_path = "/bin/chmod"
>     install_name_tool_path = "/usr/bin/install_name_tool"
> ```

Should this call `which` or `xcrun -f` instead of hardcoding?

---

*[tools/workspace/homebrew_bottle.bzl, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nDK9BjuxpeSRuymol:-L-nDK9BjuxpeSRuymom:b-dx50tq) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/homebrew_bottle.bzl#L59)):*
> ```Python
>     lib_pathname = _find_lib_pathname(repository_ctx, formula_name)
>     # Bottles have read-only permission, makes it writable to make changes.
>     repository_ctx.execute([chmod_path, "+w", lib_pathname])
> ```

BTW Maybe defining a `chmod` helper Skylark function would be neater (surprised there is not one already, really).  Same could be said for encapsulating the `install_name_tool` calls. Not essential, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416)*

**Comment by soonho-tri** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/deb.bzl, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nEsmPiz5jhemTuI_l:-L0Fcz7JTRp7g7t3ofu9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/deb.bzl#L40)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`don't permit`?
</blockquote></details>

Done.

---

*[tools/workspace/homebrew_bottle.bzl, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nEcw7BBahVVY9yyvj:-L0Fd3DyxfM2-Pe_Cal8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/homebrew_bottle.bzl#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I would not object if you wanted to drop `el_capitan` since it is now unsupported by Drake.
</blockquote></details>

Done.

---

*[tools/workspace/homebrew_bottle.bzl, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7416#-L-nCdCHsXc3bRDTK9GU:-L0FdQBd7v0JjUNfrefa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fe323d28c9055c2a5c0068f4320ffb1c023068a8/tools/workspace/homebrew_bottle.bzl#L55)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Should this call `which` or `xcrun -f` instead of hardcoding?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7416)*

**Comment by soonho-tri** [comment]
Will open a new one shortly.

**Pull request closed without merging**
