### PR TITLE
[systems] Add DiagramBuilder::RemoveSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19158.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

+@sherm1 for high-level feature review, please -- as well as platform review.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[`systems/framework/diagram_builder.cc` line 98 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NToL0ce5MpGtZut4DqZ:-NToL0ce5MpGtZut4Dq_:b-uhfbzm) ([raw file](https://github.com/RobotLocomotion/drake/blob/b016700ce99257d1715ab845331580bc99fb17ab/systems/framework/diagram_builder.cc#L98)):*
> ```cpp
>   }
> 
>   // Disconnect any internal connections associated with this system.
> ```

Whoops.  I forgot to test coverage for this block.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243)* status: LGTM missing from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[`systems/framework/diagram_builder.cc` line 98 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NToL0ce5MpGtZut4DqZ:-NToM5nV8_2JGtEB1bB9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b016700ce99257d1715ab845331580bc99fb17ab/systems/framework/diagram_builder.cc#L98)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Whoops.  I forgot to test coverage for this block.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-:-NTonnsP3TChqj5GVTyK:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[`systems/framework/diagram_builder.h` line 255 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTolZov39reZKCIqsCs:-NTolZov39reZKCIqsCt:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f88beb5383a7a607c3a6871a289be25512475d85/systems/framework/diagram_builder.h#L255)):*
> ```objc
>   /// decrementing the indices of all higher-numbered ports that remain.
>   ///
>   /// @warning Because a DigramBuilder owns the objects it contains, the system
> ```

typo



_Suggestion:_
```objc
DiagramBuilder
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
It's not clear to me how this is related to render camera preview in #19158 -- please explain if that is the motivation for this PR.

High-level feature, and platform :lgtm: with a few minor comments

> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-:-NTp3a9G5KCd8dxYws5P:b188xs8)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`systems/framework/diagram_builder.h` line 256 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTowk2y5m3tu9R2bIrV:-NTowk2y5m3tu9R2bIrW:b-nn3jbv) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/diagram_builder.h#L256)):*
> ```objc
>   ///
>   /// @warning Because a DiagramBuilder owns the objects it contains, the system
>   /// will be deleted.
> ```

BTW consider mentioning that this must be done prior to Build() -- might not be obvious to someone who doesn't realize Build() transfers ownership out.
___
*[`systems/framework/diagram_builder.cc` line 51 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NToxZPQC9upLXb830q5:-NToxZPQC9upLXb830q6:b-w0i7kl) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/diagram_builder.cc#L51)):*
> ```cpp
>                      return item.get() == &system;
>                    }));
>   DRAKE_DEMAND(system_index < registered_systems_.size());
> ```

BTW I doubt there is a performance concern here, but you could use a find_if==end result to issue the above error message without doing the search twice. I think system_index==registered_systems_.size() is the same condition as systems_.count()==0.
___
*[`systems/framework/test/diagram_builder_test.cc` line 64 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTp3JF540hhmKFhHIik:-NTp3JF540hhmKFhHIil:b5anzbr) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/test/diagram_builder_test.cc#L64)):*
> ```cpp
>   //
>   // This setup is carefully chosen such that removing 'adder' will cover all
>   // branching conditions within the implementation.
> ```

BTW confirmed with kcov

The only thing that wasn't covered was CheckInvariants() which is called only in Debug. You could consider a manual call here in the test cases FWIW.

**Review by jwnimmer-tri — COMMENTED** [review]
> It's not clear to me how this is related to render camera preview in #19158 -- please explain if that is the motivation for this PR.

That PR contains a call to this new function:

```py
            # Disable LCM image transmission. It has a non-trivial cost, and
            # at the moment Meldis can't display LCM images anyway.
            self._builder.builder().RemoveSystem(camera_publisher)
````

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-:-NTp5m0q4bS50VX4m0qo:blaktl8)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

___
*[`systems/framework/diagram_builder.h` line 256 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTowk2y5m3tu9R2bIrV:-NTp6rFYCV4Sp8N6NJO3:b8s1pek) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/diagram_builder.h#L256)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider mentioning that this must be done prior to Build() -- might not be obvious to someone who doesn't realize Build() transfers ownership out.
</blockquote></details>

That's true of all functions in the the header.  I won't try to fix it in this PR.
___
*[`systems/framework/diagram_builder.cc` line 51 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NToxZPQC9upLXb830q5:-NTp6IUG3LcxSrGUaSme:b-8ol42t) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/diagram_builder.cc#L51)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I doubt there is a performance concern here, but you could use a find_if==end result to issue the above error message without doing the search twice. I think system_index==registered_systems_.size() is the same condition as systems_.count()==0.
</blockquote></details>

I don't think performance carries any weight here.
___
*[`systems/framework/test/diagram_builder_test.cc` line 64 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTp3JF540hhmKFhHIik:-NTp6zPgEgKBCSgxdhc0:b-qm2pht) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/test/diagram_builder_test.cc#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW confirmed with kcov

The only thing that wasn't covered was CheckInvariants() which is called only in Debug. You could consider a manual call here in the test cases FWIW.
</blockquote></details>

For my own taste, running `bazel test //systems/framework:diagram_builder_test -c dbg` during development was sufficient.  Checking the invariants buys us the most when they are running continuously in all test cases, not just one line here.

**Comment by jwnimmer-tri** [comment]
Merging now, to unblock a train of coming PRs.  If there are other lingering improvements I'm happy to fix in a follow-up.

**Comment by sherm1** [comment]
*[`systems/framework/diagram_builder.cc` line 18 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTtEara27z_JyrTXIF_:-NTtEara27z_JyrTXIFa:b6ht1q) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/diagram_builder.cc#L18)):*
> ```cpp
> /* Erases the i'th element of vec, shifting everything after it over by one. */
> template <typename StdVector>
> void VectorErase(StdVector* vec, size_t i) {
> ```

FYI (irrelevent here where performance is not a concern, but I should have at least mentioned it): 
When an std::vector is used as a set (rather than a sequence) you can do O(1) erasure of element i by moving the last element of the vector to position i and shortening the vector by 1. Less renumbering required also.

**Comment by jwnimmer-tri** [comment]
*[`systems/framework/diagram_builder.cc` line 18 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19243#-NTtEara27z_JyrTXIF_:-NTtGMlzERxlzZjVEL9f:bl7yu53) ([raw file](https://github.com/RobotLocomotion/drake/blob/1a1d98b2a3b41b35c1bb7aa3ff4f6e5c37fbd89a/systems/framework/diagram_builder.cc#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI (irrelevent here where performance is not a concern, but I should have at least mentioned it): 
When an std::vector is used as a set (rather than a sequence) you can do O(1) erasure of element i by moving the last element of the vector to position i and shortening the vector by 1. Less renumbering required also.
</blockquote></details>

I actually did that initially.  It fails to meet the API promise that the relative order of the systems and ports remains unchanged.

**Pull request merged**
