### PR TITLE
Add IiwaPlanSource (toward replacing kuka_plan_runner)

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5380)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@siyuanfeng-tri for feature review

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-:-KeEvJCjyrABrEnQCrTT:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzIOeARN0uOBIZ2_M:-KeEzIOeARN0uOBIZ2_N:b-evdx25) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L28)):*
> ```cpp
> }  // namespace
> 
> // TODO(sam.creasey) If we had version of Trajectory which supported
> ```

probably dont need this. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzGbKU-OyvGh5AUmG:-KeEzGbKU-OyvGh5AUmH:b-lhs5fk) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L35)):*
> ```cpp
>   std::vector<char> encoded_msg;
>   PiecewisePolynomial<double> pp;
>   PiecewisePolynomial<double> pp_deriv;
> ```

probably don't need this 

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeF17kJFc2vsxgTowwD:-KeF17kKLV61KjQxBUN-:b-2xz6nv) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L42)):*
> ```cpp
>       status_input_port_(this->DeclareAbstractInputPort().get_index()) {
>   parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
>       GetDrakePath() + "/examples/kuka_iiwa_arm/models/iiwa14/iiwa14.urdf",
> ```

might be better if passed in. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeF-rUdlMQPXrIwmSeU:-KeF-rUdlMQPXrIwmSeV:bxg3n2n) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L54)):*
> ```cpp
> IiwaPlanSource::AllocateAbstractState() const {
>   std::vector<std::unique_ptr<systems::AbstractValue>> abstract_vals;
>   const PlanData default_plan;
> ```

probably default_plan.start_time = 0? i suppose you can set it above as default. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEz_LW_BKqO5LiwAOe:-KeEz_LXP-7J7NsEkMmi:bp1abk6) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L63)):*
> ```cpp
>     const systems::Context<double>& context,
>     systems::SystemOutput<double>* output) const {
>   const PlanData& plan = context.get_abstract_state<PlanData>(0);
> ```

BTW my version started to use abstract_state_index_plan instead of 0. useful if you have more states.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzukFduxL05EkS-mH:-KeEzukFduxL05EkS-mI:b-u4645y) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L80)):*
> ```cpp
>     // with no velocity.
>     for (int i = 0; i < kNumJoints; i++) {
>       output_vec(i) = status.joint_position_measured[i];
> ```

is this case actually triggered? 
somehow i think DoCalcUnrestrictedUpdate always happens before calc output? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by sammy-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzIOeARN0uOBIZ2_M:-KeF1fCs2V61HGVMygP4:bnaf0e3) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L28)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

probably dont need this. 
</blockquote></details>

Already removed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzGbKU-OyvGh5AUmG:-KeF1gyHjNWVgBNDOMTx:bnaf0e3) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L35)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

probably don't need this 
</blockquote></details>

Already removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by sammy-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeF17kJFc2vsxgTowwD:-KeFMBQwAWziHo5O8fwH:b-y3vnvc) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L42)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

might be better if passed in. 
</blockquote></details>

Maybe wait until we have a use/need for a different model?  I guess it's a simply enough change...  (I feel like passing in the RigidBodyTree itself would probably just be tedious).

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeF-rUdlMQPXrIwmSeU:-KeFLN8N54B7eJ-temQz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L54)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

probably default_plan.start_time = 0? i suppose you can set it above as default. 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzukFduxL05EkS-mH:-KeFLTaBCwFZdAGWn05d:baepmnh) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L80)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

is this case actually triggered? 
somehow i think DoCalcUnrestrictedUpdate always happens before calc output? 
</blockquote></details>

I don't actually know...   Maybe if a downstream system had this as it's input and a more frequent update period?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by sammy-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzIOeARN0uOBIZ2_M:-KeFWd-ouMDv_nm55bQM:b-r2ays5) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L28)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Already removed.
</blockquote></details>

(and then put back after f2f conversation)

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzGbKU-OyvGh5AUmG:-KeFWZC7qdY0zvMz4rHR:b-r2ays5) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L35)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Already removed.
</blockquote></details>

(and then put back after f2f conversation)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-memcheck-lsan please

---

Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-:-KeFZibiVeNgKkHI64Ip:b-j75p6n)*

**Comment by siyuanfeng-tri** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeF17kJFc2vsxgTowwD:-KeH18EBifsFKI3ESKRY:bl5vsmf) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L42)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Maybe wait until we have a use/need for a different model?  I guess it's a simply enough change...  (I feel like passing in the RigidBodyTree itself would probably just be tedious).
</blockquote></details>

Oh, i meant to say pass in the model path. just one few place to change the path when we do model migration later. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzukFduxL05EkS-mH:-KeH1Q9sfQ3PadPxS_0h:bozhukk) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L80)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't actually know...   Maybe if a downstream system had this as it's input and a more frequent update period?
</blockquote></details>

hmm. ok, i suppose that's possible. 
i feel doing init here is somewhat degenerate case. for my stuff, i have a explicit Initialize method, and whoever made the eventual diagram is responsible to explicitly call it. otherwise things explode in very obvious ways... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-:-KeH364i2fzNiJzihgA4:b-uwkowd)*

**Comment by naveenoid** [comment]
I guess since @sammy-tri isnt here..
+@ggould-tri for platform review.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-:-KeJj-fsOpPyz2KAilo6:b-1116rr)*

**Comment by ggould-tri** [comment]
:lgtm:, nits below.

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeJmVcMGpmu_vrGdAkN:-KeJmVcMGpmu_vrGdAkO:bga1f92) ([raw file](https://github.com/robotlocomotion/drake/blob/ec5fa76b620adce390efd268afdcbccf64f3de94/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L27)):*
> ```cpp
> namespace {
> 
> const int kNumJoints = 7;
> ```

FYI Consider `constexpr` here and next line.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 86 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeJnsFA0Y6TnUYJospT:-KeJnsFA0Y6TnUYJospU:b-zfj3jx) ([raw file](https://github.com/robotlocomotion/drake/blob/ec5fa76b620adce390efd268afdcbccf64f3de94/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L86)):*
> ```cpp
>       output_vec(i) = status.joint_position_measured[i];
>     }
>     output_vec.tail(kNumJoints) = Eigen::VectorXd::Zero(kNumJoints);
> ```

FYI -- This head/tail thing isn't rule-of-three yet, so author's discretion, but I feel like this is a comparatively obscure way to spell "positions" and "velocities" and might be clearer behind a named function.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 151 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeJqPf8NsIgNaMwwS9Z:-KeJqPf9Qtd3sHKV75ZY:bxq6yqr) ([raw file](https://github.com/robotlocomotion/drake/blob/ec5fa76b620adce390efd268afdcbccf64f3de94/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L151)):*
> ```cpp
> 
>     std::vector<double> input_time;
>     for (int k = 0; k < static_cast<int>(plan_input.plan.size()); ++k) {
> ```

FYI -- A range-based for would be slightly more readable here. (possibly also in the `j` loop above?  I'm not sure of the underlying type...).  Consider (author's discretion, naturally)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-:-KeJrhtsy40eejxv1tSR:b-m6l2g2)*

**Comment by sammy-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeF17kJFc2vsxgTowwD:-KeZG0bBaAUtToenJKj0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L42)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Oh, i meant to say pass in the model path. just one few place to change the path when we do model migration later. 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzukFduxL05EkS-mH:-KeZG6amNFyL6HqA58jV:b-286yxi) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L80)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

hmm. ok, i suppose that's possible. 
i feel doing init here is somewhat degenerate case. for my stuff, i have a explicit Initialize method, and whoever made the eventual diagram is responsible to explicitly call it. otherwise things explode in very obvious ways... 
</blockquote></details>

Should I still change this in some way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by siyuanfeng-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-KeEzukFduxL05EkS-mH:-KeZGZRPsOqxAZpj3uQB:b-ra7365) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d2eb9eb2eac3a827b0cf7c305e37407538a3a3/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L80)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should I still change this in some way?
</blockquote></details>

i am marking it as resolved for now. things are very likely to evolve here anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380#-:-KeZKP8W_SR2VGUc0hgS:b-3f2dwx)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5380)*

**Pull request merged**
