### PR TITLE
Added LCMInputSystem based on System 2.0 Framework

### PR DESCRIPTION
**Pull request by liangfok**
It also includes a unit test based on the `SpringMassLCMVector` that was introduced in #2729.

This PR builds upon #2729 and should thus _not_ be merged or reviewed until #2729 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2737)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
I just met F2F with @jwnimmer-tri and have a new design that does not rely on templates. I will thus close this PR and open a new one with the updated design.

**Pull request closed without merging**
