### PR TITLE
Update yaml-cpp submodule SHA

### PR DESCRIPTION
**Pull request by jamiesnape**
Enables building of shared library on macOS / OS X.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3644)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by jamiesnape** [comment]
+@sherm1 for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3644#-:-KTBD_4ue4K9aHcfR_Lr:bnfp4nl)*

**Comment by david-german-tri** [comment]
For future reference, https://github.com/jbeder/yaml-cpp/commit/85af926ddc5f3c8fb438001743e65ec3a039ceec fixed RPATH in yaml-cpp.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3644#-:-KTBDnPVeQdn4He2tSdw:b-5amo0j)*

**Comment by david-german-tri** [comment]
Hence, shared libraries work, hence this change.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3644#-:-KTBDsOX1n2dE-73QOt3:b9y7o6m)*

**Comment by david-german-tri** [comment]
-@sherm1 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3644#-:-KTBDyaqJ-GADCSHJqRO:blu3ide)*

**Pull request merged**
