### PR TITLE
File name and location compliance for Polynomial and TrigPoly

### PR DESCRIPTION
**Pull request by ggould-tri**
Per our conventions, Polynomial and TrigPoly are:
 * filename downcased
 * cpp -> cc and testFoo to foo_test renamed
 * moved to common

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2984)

### CODE REVIEW

**Comment by ggould-tri** [comment]
Merge conflicts resolved.

+@liangfok for feature review
+@sherm1 as on-call platformer

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KO52gyDCTvDRcepH3gA:2111060178)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 22 of 31 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KO5G564E5HvsEjQsx5B:1417088721)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984)*

**Comment by ggould-tri** [comment]
Pinging @sherm1 .  If you don't have time to review this, consider passing it over to @sammy-tri or @david-german-tri ?  I'd like to get this landed before more folks come back from vacation and inadvertently make conflicts.

---

Review status: 18 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KOBDAQ171-LUdVweFas:1192554015)*

**Comment by sherm1** [comment]
Oh, sorry Grant -- passing the platform baton to +@david-german-tri, -@sherm1.

---

Review status: 18 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KOBK1V0wbteXpoVn1ct:-289355490)*

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
:lgtm: except for some strange ordering of entries in the CHANGELOG.

---

Reviewed 1 of 31 files at r1, 4 of 12 files at r5, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 27 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-KOFlY6r6dxuyaZMirn_:-KOFlY6r6dxuyaZMirna:-926845150) ([raw file](https://github.com/robotlocomotion/drake/blob/79952a1dc2b1a8058c731d9c348be2db8b6cb7dd/CHANGELOG.md#L27)):*
> ```Markdown
>  - [#2984][] Renamed and moved `Polynomial.h` and `TrigPoly.h` from `drake/util` to `drake/common` and into the `drakeCommon` library.
>  - [#2963][] Rename RigidBody::CollisionElement to RigidBodyCollisionElement.
>  - [#3010][] All header file names under `solvers` are now spelled with lower case and underscore names.
> ```

BTW, strange ordering.

---

*[CHANGELOG.md, line 116 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-KOFm0Emh753_tsyJ8fb:-KOFm0Emh753_tsyJ8fc:-926845150) ([raw file](https://github.com/robotlocomotion/drake/blob/79952a1dc2b1a8058c731d9c348be2db8b6cb7dd/CHANGELOG.md#L116)):*
> ```Markdown
> [#3003]: https://github.com/RobotLocomotion/drake/issues/3003
> [#3010]: https://github.com/RobotLocomotion/drake/issues/3010
> [#2984]: https://github.com/RobotLocomotion/drake/issues/2984
> ```

BTW, strange ordering.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KOFmBNj77hbD_JzOX1J:-653521514)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 27 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-KOFlY6r6dxuyaZMirn_:-KOFmir8FiqhbQDJh4ZA:2012602843) ([raw file](https://github.com/robotlocomotion/drake/blob/79952a1dc2b1a8058c731d9c348be2db8b6cb7dd/CHANGELOG.md#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, strange ordering.
</details>
I think that order is reverse chronological by landing date.

---

*[CHANGELOG.md, line 116 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-KOFm0Emh753_tsyJ8fb:-KOFmsZTdXNa--KPtYLu:988963331) ([raw file](https://github.com/robotlocomotion/drake/blob/79952a1dc2b1a8058c731d9c348be2db8b6cb7dd/CHANGELOG.md#L116)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, strange ordering.
</details>
This list is maintained by an automated tool and probably shouldn't be adjusted manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/@VanDerPolCpp/dynamicsRHS.cpp, line 7 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-KOG8nQXeeu6vA8ZiQxb:-KOG8nQXeeu6vA8ZiQxc:545653997) ([raw file](https://github.com/robotlocomotion/drake/blob/79952a1dc2b1a8058c731d9c348be2db8b6cb7dd/drake/examples/@VanDerPolCpp/dynamicsRHS.cpp#L7)):*
> ```cpp
> #include <iostream>
> #include "drake/util/drakeMexUtil.h"
> #include "drake/common/polynomial.h"
> ```

BTW, alphabetize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KOG8jvCHJBjoO1yec3H:1417088721)*

**Comment by ggould-tri** [comment]
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/examples/@VanDerPolCpp/dynamicsRHS.cpp, line 7 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-KOG8nQXeeu6vA8ZiQxb:-KOGGItp1ATfzxTp_H7L:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/79952a1dc2b1a8058c731d9c348be2db8b6cb7dd/drake/examples/@VanDerPolCpp/dynamicsRHS.cpp#L7)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, alphabetize
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2984#-:-KOGJ8xGTPHa4c9n-NdU:1417088721)*

**Pull request merged**
