### PR TITLE
Implements FunctionHandleTrajectory

### LINKED ISSUE #20699: Represent the Image of a Trajectory Under Arbitrary Mappings
If I'm given a trajectory $q:[t_0,t_1]\to\mathbb R^n$, and a smooth function $f:\mathbb R^n\to\mathbb R^m$, then the composition $f\circ q:[t_0,t_1]\to\mathbb R^m$ is also a valid trajectory. However, there's no general way to represent such an object in Drake, so I can't use features such as Toppra (which requires a trajectory object as input).

My current workaround is to densely sample points from the trajectory and then interpolate them to construct a new trajectory, but this has been very finicky in practice (and is how I encountered the issue described in #20619). Such a feature would be extremely helpful for my constrained bimanual manipulation work, where robot trajectories live parametrization of configuration space that is more amenable to planning. Ideally, the feature would be compatible with functions defined with Drake's symbolic engine and "autodiff"-able functions.

cc @sageshoyu @shrutigarg914 @RussTedrake

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20699.

I still need to write more tests, but I hope this gets you unstuck @cohnt and @shrutigarg914 .

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@cohnt for feature review, please?  I'd like to land this (or decide it's not needed/useful and close it out).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-Nuxx5Me5Jf7in7TAsDM:b-tw1ibf)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by cohnt** [comment]
One feature that Shruti and I really need from this class is the ability to take derivatives of the trajectory, since Toppra needs those. I have a hacky branch [here](https://github.com/cohnt/drake/blob/a12f0b9c9e4d2323529cd190617be0e12a7a1e44/common/trajectories/function_handle_trajectory.cc#L43) where I implemented finite-differencing, which was sufficient for our experiments. But that's probably not the most mature way of handling that -- I would think it's better to autodiff through the given function. I'm fine reviewing this PR without that feature, and leaving that as a request for the future.

**Review by RussTedrake — COMMENTED** [review]
I added a TODO for the approach that we talked about before, but would think we should land this as is first.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-NuzO1p63-4HJY0vvSEP:b-xdhuwb)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by cohnt — COMMENTED** [review]
:lgtm: with a minor question about testing

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-NvZ2IrAANxXcUINhDDa:brnjmbc)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-NvZ1uolDS955lIAfCAH:-NvZ1uolDS955lIAfCAI:b-i4a8i4) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf998c6236d201528240820437c5a6f55eb2fff/common/trajectories/test/function_handle_trajectory_test.cc#L93)):*
> ```cpp
> }
> 
> GTEST_TEST(FunctionHandleTrajectoryTest, Invalid) {
> ```

nit: Should we have a test case that verifies the program throws if you give a function that doesn't output a matrix of the expected shape? I guess in C++, that should end up being a compilation error, but what would happen if you accessed it through the python bindings?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-NvZ1uolDS955lIAfCAH:-Nw1KFxD-PWcw0SAtSVp:b9crj9x) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf998c6236d201528240820437c5a6f55eb2fff/common/trajectories/test/function_handle_trajectory_test.cc#L93)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

nit: Should we have a test case that verifies the program throws if you give a function that doesn't output a matrix of the expected shape? I guess in C++, that should end up being a compilation error, but what would happen if you accessed it through the python bindings?
</blockquote></details>

so currently it only throws in the constructor in debug mode.  so i don't have that test.

there are a couple of things I could do differently.
1) i could eval the function handle even in runtime mode during the constructor, to fail fast.  if i did this, then I could even remove the rows and cols arguments, and just take the size of the evaluated return value.  this still wouldn't protect if someone has a function handle that returns different sized matrices at different times.

separately,
2) I _could_ check the size of the computed return value on every evaluation, and throw if it's invalid.  this would be the most safe.  it seems slightly inelegant.

wdyt?

**Review by cohnt — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-NvZ1uolDS955lIAfCAH:-Nw2XhHu2pfQX-vd533h:bjr56qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf998c6236d201528240820437c5a6f55eb2fff/common/trajectories/test/function_handle_trajectory_test.cc#L93)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

so currently it only throws in the constructor in debug mode.  so i don't have that test.

there are a couple of things I could do differently.
1) i could eval the function handle even in runtime mode during the constructor, to fail fast.  if i did this, then I could even remove the rows and cols arguments, and just take the size of the evaluated return value.  this still wouldn't protect if someone has a function handle that returns different sized matrices at different times.

separately,
2) I _could_ check the size of the computed return value on every evaluation, and throw if it's invalid.  this would be the most safe.  it seems slightly inelegant.

wdyt?
</blockquote></details>

As long as the behavior is clearly documented, I think either of these options would be acceptable. You could even leave the code as-is, and just note in the documentation that no matrix size/shape checking is done, and that using a function which returns the wrong shape is undefined behavior.

I like the idea of using option (1) and removing the rows and cols arguments. It's up to your preference on whether to make that change.

Option (2) is nice, and doesn't strike me as inelegant. But I'd be concerned about runtime performance.

**Comment by cohnt** [comment]
What's the plan on this -- are you hoping to start a fresh PR, or something else? Shruti and I are still actively using this WIP code, with the aforementioned finite differencing hack.

**Comment by RussTedrake** [comment]
I thought you had moved on... I didn't realize you were using it.  I can put it back on my queue to finish up.

**Comment by cohnt** [comment]
Just dropping by this PR to note that Shruti and I would still really like to see this feature in Drake master. I can even try adding derivatives myself as a followup PR.

**Review by RussTedrake — COMMENTED** [review]
Updated.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-O9PJQRV1AXyiLaWIZym:bqyk4pz)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 93 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-NvZ1uolDS955lIAfCAH:-O9PJTI9DClGZDpN1sXE:b-7ltyxe) ([raw file](https://github.com/RobotLocomotion/drake/blob/adf998c6236d201528240820437c5a6f55eb2fff/common/trajectories/test/function_handle_trajectory_test.cc#L93)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

As long as the behavior is clearly documented, I think either of these options would be acceptable. You could even leave the code as-is, and just note in the documentation that no matrix size/shape checking is done, and that using a function which returns the wrong shape is undefined behavior.

I like the idea of using option (1) and removing the rows and cols arguments. It's up to your preference on whether to make that change.

Option (2) is nice, and doesn't strike me as inelegant. But I'd be concerned about runtime performance.
</blockquote></details>

Done.  I've kept the constructor but added a TODO, and implemented the runtime check + test.

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-O9Pojlu3nOq3i5CKZoV:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/function_handle_trajectory.h` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9PoVrr1JVSeyLB2N8j:-O9PoVrr1JVSeyLB2N8k:bn3nsuj) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e695e3163c77ef59ea030fc8fe19f60d6d1f159/common/trajectories/function_handle_trajectory.h#L26)):*
> ```objc
>   @param func The function to be used to evaluate the trajectory.
>   @param rows The number of rows in the output of the function.
>   @param cols The number of columns in the output of the function.
> ```

nit: Is there a reason you got rid of this documentation?

**Review by RussTedrake — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-O9SQZ34418KgR7RpNmn:bk1c533)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`common/trajectories/function_handle_trajectory.h` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9PoVrr1JVSeyLB2N8j:-O9SQKqgBJYRWOlTfkGa:bmpf8d5) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e695e3163c77ef59ea030fc8fe19f60d6d1f159/common/trajectories/function_handle_trajectory.h#L26)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

nit: Is there a reason you got rid of this documentation?
</blockquote></details>

Done.  (that was a mistake)

**Review by cohnt — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I pushed a commit I hope will get past mac CI.

I'm deferring the debug build CI failures to the discussion below.

First pass done.

> Reviewed 5 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-O9VXS8I-ib1_YIikkdB:ba3jb3v)* status: 10 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`common/trajectories/function_handle_trajectory.h` line 3 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VOp890I5IDVsv0-01:-O9VOp890I5IDVsv0-02:b-mddbzx) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.h#L3)):*
> ```objc
> #pragma once
> 
> #include <limits>
> ```

btw: Given you're using `std::function`, this would ideally include `<functional>`
___
*[`common/trajectories/function_handle_trajectory.h` line 33 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VP4Q3ARq7xkcpgO90:-O9VP4Q3ARq7xkcpgO91:b-ykn685) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.h#L33)):*
> ```objc
>   */
>   FunctionHandleTrajectory(
>       const std::function<MatrixX<T>(const T&)>& func, int rows, int cols = 1,
> ```

BTW You might consider pass-by-value and moving the function into the member.
___
*[`common/trajectories/function_handle_trajectory.cc` line 21 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VOOm-Cj9AtGAau7gA:-O9VOOm-Cj9AtGAau7gB:b-elgnnz) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.cc#L21)):*
> ```cpp
>   DRAKE_THROW_UNLESS(cols >= 0);
>   DRAKE_THROW_UNLESS(start_time <= end_time);
>   DRAKE_ASSERT(func_(start_time).rows() == rows);
> ```

nit: These asserts are breaking CI. The `value()` method never gets a chance to throw its exception, because the constructor aborts here. You should either simply throw here (with supporting documentation) or do nothing, relying on `value()` to take care of things.

If you choose to have a documented throw here, then the exception in `value` seems unnecessary.

If you're worried about the cost of evaluating `func_`, you *could* evaluate it once and then test the rows and columns of that one returned value.

If even one evaluation is too expensive to allow for general evaluation in release mode, then you'd have to rephrase the test to be sensitive to whether assert is armed or not. Even then, throwing when assert is armed would allow for a better test over aborting.

That said, I'm inclined to think that simply adding it to the constructor's throwing conditions is the best thing to do. It'd be a shame to blow up in different locations in code for the same bug depending on whether asserts are armed or not.

It's a trajectory, after all. One assumes that we're going to call `value()` a lot (evaluating `func_`). One additional evaluation upon construction would be meaningless.
___
*[`common/trajectories/function_handle_trajectory.cc` line 31 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VQ4wPBkS9uiboGbqz:-O9VQ4wPBkS9uiboGbr-:bbkezoz) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.cc#L31)):*
> ```cpp
> std::unique_ptr<Trajectory<T>> FunctionHandleTrajectory<T>::Clone() const {
>   using Self = FunctionHandleTrajectory<T>;
>   return std::unique_ptr<Self>(
> ```

nit: simpler and keeps us away from raw pointers:

```c++
return std::make_unique<Self>(func_, rows_, cols_, start_time_, end_time_);
```
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 0 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VSlTdDk_jmtrKrq42:-O9VSlTdDk_jmtrKrq43:b-sowa56) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L0)):*
BTW It would be nice if somewhere in this test, you included a function that didn't return a 1x1 matrix. Replacing one of the valid functions with a different size would allow us to believe that 1x1 isn't hard coded.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 25 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VSU8zErtA-KmB9fQU:-O9VSU8zErtA-KmB9fQV:b-euho0g) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L25)):*
> ```cpp
> 
>   for (double t = 0; t < 1; t += 0.1) {
>     EXPECT_TRUE(CompareMatrices(dut.value(t),
> ```

BTW It's not clear to me why you're promoting to matrix instead of devolving to scalar:

```c++
EXPECT_EQ(dut.value(t)(0, 0), std::sin(t));
```

That reads simpler to me.

Alternatively:

```c++
EXPECT_TRUE(CompareMatrices(dut.value(t), sin_func(t)));
```

This latter spelling would allow you to change `sin_func` to `circle_func` and return a 2x1 matrix (where one is cos and the other is sin), addressing my comment at the top.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 29 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VX-SwEvPBEQBY-zAm:-O9VX-SwEvPBEQBY-zAn:b7icl46) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L29)):*
> ```cpp
>   }
> 
>   auto clone = dut.Clone();
> ```

BTW `clone` is of type `std::unique_ptr<Trajectory<double>>`. Do we not want a test that it *actually* is a `FunctionHandleTrajectory<double>`? Or do we infer that from evaluation of the `Trajectory` API?
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 90 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VTbT13I6MoeIv3bdh:-O9VTbT13I6MoeIv3bdi:bgmu0vd) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L90)):*
> ```cpp
>   EXPECT_EQ(dut.value(t).rows(), 0);
>   EXPECT_EQ(dut.value(t).cols(), 0);
>   DRAKE_EXPECT_THROWS_MESSAGE(dut.Clone(), ".*func_ != nullptr.*");
> ```

You've got strange semantics for a "moved" (aka empty) trajectory.

I can:
  - Evaluate it
  - Copy it (via copy constructor)
I can't:
  - Clone it
  - Copy it (via move constructor)

This strange splintering of functionality seems broken. I think your constructor tests need to be conditioned on whether an "empty" trajectory is being constructed.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 110 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VUpCg9NiDOnyxCQwi:-O9VUpCg9NiDOnyxCQwj:bj76v0y) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L110)):*
> ```cpp
>     return Eigen::Matrix<double, 2, 1>(std::sin(t), std::cos(t));
>   };
>   FunctionHandleTrajectory<double> dut(my_func, 1, 1, 0, 1);
> ```

BTW (In support of earlier comment). This is the line that blows up when you have a debug build.
___
*[`bindings/pydrake/test/trajectories_test.py` line 228 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VWPR13UvVyvf7Kx_U:-O9VWPR13UvVyvf7Kx_V:b1nw138) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/bindings/pydrake/test/trajectories_test.py#L228)):*
> ```Python
>         for t in [0.0, 0.5, 1.0]:
>             numpy_compare.assert_float_equal(dut.value(t), f(t))
>         dut.Clone()
> ```

BTW I know this doesn't appear to be a pattern in this test, but is there a reason that this test isn't:

```py
self.assertIsInstance(dut.Clone(), FunctionHandleTrajectory_[T])
```

Do we just take for granted that the existence and successful invocation of a `Clone()` method implies the appropriate type (given inspection of the C++ implementation)?

**Review by RussTedrake — COMMENTED** [review]
Done.  Thanks. PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-O9r0o_3ELIm-n_JlksJ:b-5cmgrn)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`common/trajectories/function_handle_trajectory.h` line 3 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VOp890I5IDVsv0-01:-O9quo473Z3IdLSIlzpT:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.h#L3)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: Given you're using `std::function`, this would ideally include `<functional>`
</blockquote></details>

Done.
___
*[`common/trajectories/function_handle_trajectory.h` line 33 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VP4Q3ARq7xkcpgO90:-O9qux392Zgd8Rgk1WtY:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.h#L33)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You might consider pass-by-value and moving the function into the member.
</blockquote></details>

Done.
___
*[`common/trajectories/function_handle_trajectory.cc` line 21 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VOOm-Cj9AtGAau7gA:-O9r-W2L31LphWJ41_o5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.cc#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: These asserts are breaking CI. The `value()` method never gets a chance to throw its exception, because the constructor aborts here. You should either simply throw here (with supporting documentation) or do nothing, relying on `value()` to take care of things.

If you choose to have a documented throw here, then the exception in `value` seems unnecessary.

If you're worried about the cost of evaluating `func_`, you *could* evaluate it once and then test the rows and columns of that one returned value.

If even one evaluation is too expensive to allow for general evaluation in release mode, then you'd have to rephrase the test to be sensitive to whether assert is armed or not. Even then, throwing when assert is armed would allow for a better test over aborting.

That said, I'm inclined to think that simply adding it to the constructor's throwing conditions is the best thing to do. It'd be a shame to blow up in different locations in code for the same bug depending on whether asserts are armed or not.

It's a trajectory, after all. One assumes that we're going to call `value()` a lot (evaluating `func_`). One additional evaluation upon construction would be meaningless.
</blockquote></details>

Done.
___
*[`common/trajectories/function_handle_trajectory.cc` line 31 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VQ4wPBkS9uiboGbqz:-O9qvBzd388bLGVeYM1H:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/function_handle_trajectory.cc#L31)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: simpler and keeps us away from raw pointers:

```c++
return std::make_unique<Self>(func_, rows_, cols_, start_time_, end_time_);
```
</blockquote></details>

Done.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 25 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VSU8zErtA-KmB9fQU:-O9qvKzb3_FEFf3v6LMg:b9gql8s) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It's not clear to me why you're promoting to matrix instead of devolving to scalar:

```c++
EXPECT_EQ(dut.value(t)(0, 0), std::sin(t));
```

That reads simpler to me.

Alternatively:

```c++
EXPECT_TRUE(CompareMatrices(dut.value(t), sin_func(t)));
```

This latter spelling would allow you to change `sin_func` to `circle_func` and return a 2x1 matrix (where one is cos and the other is sin), addressing my comment at the top.
</blockquote></details>

Done.  (I thought promoting to a matrix was better because it also checks the shape, but the update to circle_func makes that moot.)
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 29 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VX-SwEvPBEQBY-zAm:-O9qwDmG8dQMSgnwZ-F8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW `clone` is of type `std::unique_ptr<Trajectory<double>>`. Do we not want a test that it *actually* is a `FunctionHandleTrajectory<double>`? Or do we infer that from evaluation of the `Trajectory` API?
</blockquote></details>

Done.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 90 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VTbT13I6MoeIv3bdh:-O9r0dXp3Yy4fPUEP8td:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L90)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You've got strange semantics for a "moved" (aka empty) trajectory.

I can:
  - Evaluate it
  - Copy it (via copy constructor)
I can't:
  - Clone it
  - Copy it (via move constructor)

This strange splintering of functionality seems broken. I think your constructor tests need to be conditioned on whether an "empty" trajectory is being constructed.
</blockquote></details>

Done.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 110 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VUpCg9NiDOnyxCQwi:-O9r0uEU0etEg553nFbv:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L110)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW (In support of earlier comment). This is the line that blows up when you have a debug build.
</blockquote></details>

Done.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line  at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VSlTdDk_jmtrKrq42:-O9qwCpp0w30cPptaE-h:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/common/trajectories/test/function_handle_trajectory_test.cc#L)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It would be nice if somewhere in this test, you included a function that didn't return a 1x1 matrix. Replacing one of the valid functions with a different size would allow us to believe that 1x1 isn't hard coded.
</blockquote></details>

Done.
___
*[`bindings/pydrake/test/trajectories_test.py` line 228 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9VWPR13UvVyvf7Kx_U:-O9r10lpARpKKLhSTpu6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6c738af5923a85abc5a05d8d7127ac61aa22e796/bindings/pydrake/test/trajectories_test.py#L228)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I know this doesn't appear to be a pattern in this test, but is there a reason that this test isn't:

```py
self.assertIsInstance(dut.Clone(), FunctionHandleTrajectory_[T])
```

Do we just take for granted that the existence and successful invocation of a `Clone()` method implies the appropriate type (given inspection of the C++ implementation)?
</blockquote></details>

Done.

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-:-O9wCWaA022AVib3ONFH:bnfp4nl)* status: 2 unresolved discussions

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21093)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),cohnt

___
*[`common/trajectories/function_handle_trajectory.cc` line 28 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9t_K1i4l1GPk1lZ--5:-O9wCbMO84ZrcniWCxzU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/78d114760ea8f5e7d83525a1f24b6b2a56606c65/common/trajectories/function_handle_trajectory.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I actually originally wrote a comment here suggesting this line was wrong. But then I read the tests and I realized that your test in `value()` was to protect from a badly implemented function that isn't consistent.

I think making that intention *explicit* in this file would help future readers. It might keep people from thinking, "Why is this here? Why not in the constructor?" like I did.
</blockquote></details>

Done.
___
*[`common/trajectories/test/function_handle_trajectory_test.cc` line 112 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21093#-O9taJbl3ouGzhOLfM8a:-O9wCc41A7F08DSqra7u:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/78d114760ea8f5e7d83525a1f24b6b2a56606c65/common/trajectories/test/function_handle_trajectory_test.cc#L112)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Not a defect, but this comment is a pretty direct rephrasing of what the next line of code declares.  :)
</blockquote></details>

Done.

**Pull request merged**
