### PR TITLE
[geometry] Add cleanup logic for unexpected websocket thread exit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A lemma towards #16659.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.  Sorry, this one will be a beast.

I've tried to make this as clear and correct as possible, but I welcome any suggestions (either to code or comments) that would make it better.

In case you decide to poke at the implementation locally, the important test condition is this one:

```
CC=clang-9 CXX=clang++-9 bazel test --compilation_mode=dbg --config=lsan //geometry:meshcat_test
```

In particular, one thing to note is that this PR only make the code _exit_-safe, not _exception_-safe.  I'm saving the exception safety for the next PR.  This lemma is only about shutdown coordination, not fault detection.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670#-:-MwmmIst-XHAy0HNAkzw:b-ckpsob)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor stuff

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670#-:-MwnEIQk3OUkWUtOM_c4:bo23mka)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mwn3Ake4ZxsKyn9k66S):*
typo



_Code quote:_
```
geoemtry
```
___
*[geometry/meshcat.cc, line 686 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-MwnDwM2AmrHWWQ-6mWr:-MwnDwM2AmrHWWQ-6mWs:b-y6cllk) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/meshcat.cc#L686)):*
> ```cpp
>   void SetObject(std::string_view path, const perception::PointCloud& cloud,
>                  double point_size, const Rgba& rgba) {
>     DRAKE_DEMAND(std::this_thread::get_id() == main_thread_id_);
> ```

BTW outside your patch, but a few of these could be promoted to IsThread().
___
*[geometry/meshcat.cc, line 1649 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-MwnCYnn0xnOpt9Gsvs9:-MwnCYnn0xnOpt9GsvsA:bxz70ba) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/meshcat.cc#L1649)):*
> ```cpp
> 
> std::string Meshcat::web_url() const {
>   publisher_->CheckWebsocketThread();
> ```

nit Maintaining these call sites seems maybe error-prone. Would it be less trouble to do these checks in the publisher methods whose precondition is `IsThread(main_thread_id_)` ?
___
*[geometry/test/meshcat_test.cc, line 167 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mwn40h7-Wu1pAAjVUzQ:-Mwn40h7-Wu1pAAjVUzR:b-23osnz) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/test/meshcat_test.cc#L167)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(checker(), ".*thread exited.*");
> 
>   // The object can be destroyed without an errors nor sanitizer leaks.
> ```

typo, suggest s/without an/with neither/



_Code quote:_
```cpp
without an
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[geometry/meshcat.cc, line 1649 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-MwnCYnn0xnOpt9Gsvs9:-MwnM3nh7NGMzLUFv0Ic:b-ors4j) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/meshcat.cc#L1649)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Maintaining these call sites seems maybe error-prone. Would it be less trouble to do these checks in the publisher methods whose precondition is `IsThread(main_thread_id_)` ?
</blockquote></details>

Interesting.  My hope was that by placing them within the outer class functions, it would be the easiest pattern to follow -- that every public entry point gets a check, and nothing else.  I was hoping that the terseness of the outer class functions would help as well, such that every one of them is always calling two functions on the publisher.  Let me play with some other options.  Working.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 1649 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-MwnCYnn0xnOpt9Gsvs9:-MwnPLei8hYVBfnvoRqR:bbz1b6v) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/meshcat.cc#L1649)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Interesting.  My hope was that by placing them within the outer class functions, it would be the easiest pattern to follow -- that every public entry point gets a check, and nothing else.  I was hoping that the terseness of the outer class functions would help as well, such that every one of them is always calling two functions on the publisher.  Let me play with some other options.  Working.
</blockquote></details>

I couldn't swear it will be better the other way, but as i read through the changes, they felt like a Publisher responsibility that was perhaps leaking out.

The other train of thought was something like:
* do all outer-class calls have a check? no, only ones that directly call some other publisher_-> method directly.
* should we write down that condition? hmm....

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 1649 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-MwnCYnn0xnOpt9Gsvs9:-Mws8yqT5i7Jl12hW4LT:b-b25hor) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/meshcat.cc#L1649)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here's one attempt -- WDYT? +(status: do not merge) 

If you like it, I'll stage the const-correct `publisher()` helpers as a preemptive PR.

(I could also call them `impl()` instead of `publisher()`.  I think the inner class has grown a bit beyond just being a "publisher" -- it's the full impl, not just the publisher portion of it.)
</blockquote></details>

 I like it. Also agree that "publisher" no longer seems to quite fit.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 1649 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16670#-MwnCYnn0xnOpt9Gsvs9:-MwsOMOaBlAxh_XgYuGJ:b-i0krp5) ([raw file](https://github.com/robotlocomotion/drake/blob/9d6809e5e7715711d94431f25e19714d83188aa3/geometry/meshcat.cc#L1649)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

=>  #16682

Leaving as Working and "do not merge" here until this gets rebased away.
</blockquote></details>

Done -(status: do not merge).

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[geometry/meshcat.cc, line 1756 at r8](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mww55bKD35uCibOp0VH:-Mww55bLAB8F3BujZBU3:bjjupzy) ([raw file](https://github.com/robotlocomotion/drake/blob/1034af129c1b8a5178cb9ee9249672e890673c4d/geometry/meshcat.cc#L1756)):*
> ```cpp
> 
> // This overloaded function ensures that CheckWebsocketThread always happens
> // before using WebSocketPublisher.
> ```

nit that name is stale now?



_Code quote:_
```cpp
WebSocketPublisher
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
Wow, this PR has been through some stuff!  I'm going to need a bit of time to really understand this one.  Review by end-of-day.

> Reviewed 1 of 4 files at r1, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670#-:-Mx-SEgK3DZNg4Kh0WM2:bt97o0b)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 1691 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx-T-Jg8qV5xQnnjo3J:-Mx-T-Jg8qV5xQnnjo3K:b-8skdb0) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/meshcat.cc#L1691)):*
> ```cpp
>   // which is a *thread_local static object*. When the thread finishes, the C++
>   // runtime will destroy the thread_local object and our loop_ will become a
>   // dangling pointer. Calling any function on it would lead to nasal demons.
> ```

FYI I am definitely going to remember that "nasal demons" is now approved Drake terminology.

**Review by jwnimmer-tri — COMMENTED** [review]
Yes, please take your time!  You are my go-to TOCTOU expert.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670#-:-Mx-xOsL1QkyXX8pTFZ_:b-eezatf)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 1691 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx-T-Jg8qV5xQnnjo3J:-Mx-xQ1H4FNP21DqBUT_:b-9tp8rg) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/meshcat.cc#L1691)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI I am definitely going to remember that "nasal demons" is now approved Drake terminology.
</blockquote></details>

Hah!  The demons are even less fun as corefiles in Deepnote.  (Though it does let me open up gdb in a terminal in the web browser, which was a new experience for me.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

___
*[geometry/test/meshcat_test.cc, line 158 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx0-2Hp2z1cRozxsGtR:-Mx0-2Hq79_QHIL2zaQk:bc534dl) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/test/meshcat_test.cc#L158)):*
> ```cpp
>   // able to call *any* function and have it report the fault; we use web_url
>   // out of simplicity, and rely on code inspection of meshcat.cc to confirm
>   // that every single public function is annotated with CheckWebsocketThread.
> ```

Working

This last sentence is a hold-over from a prior implementation.  It should really say that the `impl()` accessor (not code inspection) enforces that `CheckWebsocketThread` is always used.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @rpoyner-tri)

___
*[geometry/test/meshcat_test.cc, line 158 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx0-2Hp2z1cRozxsGtR:-Mx0y0as6FEzfcj93yYf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/test/meshcat_test.cc#L158)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This last sentence is a hold-over from a prior implementation.  It should really say that the `impl()` accessor (not code inspection) enforces that `CheckWebsocketThread` is always used.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
checkpoint as I finish up for the day

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670#-:-Mx1Lx2O70U-kMNLfngc:bv6um3w)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx1FCbR0nWSHaWbzcAz:-Mx1FCbSBgQr2eaZhHPc:b-wv2yc7) (no related file):*
Not finishing this today, so scribing my current analysis as a breadcrumb for when I pick it back up tomorrow:

* Thread lifecycle is gated with a three-phase lock around `defer_`; defer is not an enum but a nullable function pointer.
  * Only the task thread changes `defer_` from nominal to discard
  * Only the main thread changes `defer_` from discard to nullptr.
  * In error cases the main thread can change from nominal to nullptr.
  * No other transitions are permitted.
* A three-phase handshake for lifecycle is presumptively correct.  The direct nominal->nullptr transitions violate this and require analysis, but by eye they look correct.
* The `loop_` pointer is brought out of null on the main thread and into null on the task thread.

The big obvious hazard point is `Defer()`, this is almost certainly provably correct but I haven't proven it yet.
The big obvious question is how the phased operation can be make clear and explicit enough for this code to be edited without immediately imploding.

---
___
*[geometry/meshcat.cc, line 553 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx1-O336b31qPOaWlLq:-Mx1-O336b31qPOaWlLr:b74nrox) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/meshcat.cc#L553)):*
> ```cpp
>   // presume that success here means that additional calls into the websocket
>   // will continue to succeed.
>   void CheckWebsocketThread() const {
> ```

minor:  Given the long caveat above that this function's success doesn't prove anything, the name "Check...." is misleading.  `RelayWebsocketErrors` or similar might be clearer.
___
*[geometry/meshcat.cc, line 558 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx11irOCXWGGpGcV9gz:-Mx11irOCXWGGpGcV9h-:bt65df6) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/meshcat.cc#L558)):*
> ```cpp
>     // fields to help understand what's happening here.
>     DeferImpl discard = &DeferImplDiscard;
>     const bool is_discard = defer_.compare_exchange_strong(discard, nullptr);
> ```

minor:  The name `is_discard` is misleading, since `defer_` cannot be `DeferImplDiscard` after this call.  `was_discard` is more to the point.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[geometry/meshcat.cc, line 553 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx1-O336b31qPOaWlLq:-Mx1nivW58HcPxUJo2vD:b-el6aql) ([raw file](https://github.com/robotlocomotion/drake/blob/7d143a0d36010f291dcbfbcd826f667713d1b601/geometry/meshcat.cc#L553)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Given the long caveat above that this function's success doesn't prove anything, the name "Check...." is misleading.  `RelayWebsocketErrors` or similar might be clearer.
</blockquote></details>

Done(?).

**Review by dmcconachie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx1FCbR0nWSHaWbzcAz:-Mx268Xl4McrsPQcZAY1:bj1kfq0) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Not finishing this today, so scribing my current analysis as a breadcrumb for when I pick it back up tomorrow:

* Thread lifecycle is gated with a three-phase lock around `defer_`; defer is not an enum but a nullable function pointer.
  * Only the task thread changes `defer_` from nominal to discard
  * Only the main thread changes `defer_` from discard to nullptr.
  * In error cases the main thread can change from nominal to nullptr.
  * No other transitions are permitted.
* A three-phase handshake for lifecycle is presumptively correct.  The direct nominal->nullptr transitions violate this and require analysis, but by eye they look correct.
* The `loop_` pointer is brought out of null on the main thread and into null on the task thread.

The big obvious hazard point is `Defer()`, this is almost certainly provably correct but I haven't proven it yet.
The big obvious question is how the phased operation can be make clear and explicit enough for this code to be edited without immediately imploding.
</blockquote></details>

Pinging myself so as to follow the discussion to hopefully learn things.

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: with notes below.  This code is afact sound (one note).  But I'm worried about brittleness.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670#-:-Mx5VhY23PfBzshILAxS:bjogfxr)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx1FCbR0nWSHaWbzcAz:-Mx53nApBwpoRYZH-71n:b-y7vyq3) (no related file):*
<details><summary><i>Previously, dmcconachie (Dale McConachie) wrote…</i></summary><blockquote>

Pinging myself so as to follow the discussion to hopefully learn things.
</blockquote></details>

Okay, here's the analysis that anyone editing this code is going to have to do to understand how not to fail:

* The Impl ctor can null out the defer pointer.  As is proper, it does not call any nontrivial class methods (GetUrlContent is a free function) and so is safe. It starts the task thread but does not enroll anything on it.  Its postcondition is that either:
  * defer_ is null and the task thread is stopped and joined, OR
  * defer_ is nonnull and the task thread is not joined.
* WebSocketMain is started only from the Impl ctor.  It is always entered with defer_ nominal, and it has a scope guard that first assures that defer_ is nonnominal and then sleep locks to guarantee that defer_ is null.  Assuming that all of our C++ implementations provide uncaught exception unwinding and that none of the other std::terminate laws apply, this provides postcondition:
  * defer_ is null and the task thread is stopped.
* The Impl dtor is the only other call to join().  It sets defer_ null before doing so.
* Nothing in this code can ever transition defer_ out of null.
* From the above we may reason that defer_ is always null between the exit and the join of the task thread.

* loop_ is initialized null, becomes nonnull exactly once in WebSocketMain and is restored to null exactly once at the exit of WebSocketMain after defer_ is nulled.  Thus loop_ is nonnull during each of the three defer_ phases.
  * This brings us to the app_promise.  This creates a synchronization point between WebSocketMain and the Impl ctor, whereby the impl ctor cannot exit until loop_ has become nonnull.  Combined with the guard logic of WebSocketMain, we know that
* Therefore loop_ is nonnull if defer_ is nonnull.
* Because loop_ is nulled before it is invalidated, we also do not need to be concerned about invalidation; the problems are the same.

So the whole ballgame is whether nominal defer can ever be called when defer_ is null -- the space between lines 1610 (when per 1611 defer_ was not null) and 1612 (where the value loaded at 1610 is used).  And because the only place defer_ becomes null is in the Impl dtor, this can only happen with threading or re-entrance.

The threading case is trival; I've suggested one assertion below to nail this down.

The re-entrance case is also correct.  The dtor calls Defer, which is bad mojo.  But that defer call completes before defer_ is nulled, so while it may nop it will never ub.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx5RREECdDZyEy2WG5x:-Mx5RREECdDZyEy2WG5y:b-r5wt0o) (no related file):*
For discussion:  This code seems safe, and with the trivial assertion requested below is more or less provably so modulo the silly edge cases of the `std::terminate` spec.  But I am terrified at the notion of anyone other than its authors (or even its authors after a few days to forget) making any edit to it in the future.

This situation is worsened by these small sections of brittle code being scattered in a 2000-line file.  We are laying landmines in an open field.

I think it would be worth considering, beyond the scope of this PR, two possible design improvements:
 * Factor the web socket management matter into a separate minimal class in a separate file with the same scope (via has-a / RAII) but that separates and reifies the Defer mechanism and its supporting thread logic
 * If possible, base that class on a more traditional approach using a mutex lock rather than atomics.  It would of course be less performant, but it might be clearer to have a mutex-controlled structure that gates access to the phase enum and loop pointer.  This logic is in effect trying to treat multiple values as jointly atomic wrt an invariant, and that's just mutex-controlled access by another name.

This is very much author's discretion stuff -- I don't really know the destiny or vision for this feature, and maybe you already have a refactor in view.

---
___
*[geometry/meshcat.cc, line 1609 at r11](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx5R-r58vSpX4h25sx9:-Mx5R-r58vSpX4h25sxA:b-y508uz) ([raw file](https://github.com/robotlocomotion/drake/blob/b555276046e7b00d88117141eec1001d825b0a55/geometry/meshcat.cc#L1609)):*
> ```cpp
>   // If the websocket thread is no longer operating, then this function will
>   // destroy the callback, without ever invoking it.
>   void Defer(Callback&& callback) const {
> ```

Please assert that you are on the main thread here, to guarantee that `this` is valid for the length of this function (because the main thread cannot be here and in the dtor at the same time).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx1FCbR0nWSHaWbzcAz:-Mx5fer36fLzqwvDTj4S:bhx6hrg) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Okay, here's the analysis that anyone editing this code is going to have to do to understand how not to fail:

* The Impl ctor can null out the defer pointer.  As is proper, it does not call any nontrivial class methods (GetUrlContent is a free function) and so is safe. It starts the task thread but does not enroll anything on it.  Its postcondition is that either:
  * defer_ is null and the task thread is stopped and joined, OR
  * defer_ is nonnull and the task thread is not joined.
* WebSocketMain is started only from the Impl ctor.  It is always entered with defer_ nominal, and it has a scope guard that first assures that defer_ is nonnominal and then sleep locks to guarantee that defer_ is null.  Assuming that all of our C++ implementations provide uncaught exception unwinding and that none of the other std::terminate laws apply, this provides postcondition:
  * defer_ is null and the task thread is stopped.
* The Impl dtor is the only other call to join().  It sets defer_ null before doing so.
* Nothing in this code can ever transition defer_ out of null.
* From the above we may reason that defer_ is always null between the exit and the join of the task thread.

* loop_ is initialized null, becomes nonnull exactly once in WebSocketMain and is restored to null exactly once at the exit of WebSocketMain after defer_ is nulled.  Thus loop_ is nonnull during each of the three defer_ phases.
  * This brings us to the app_promise.  This creates a synchronization point between WebSocketMain and the Impl ctor, whereby the impl ctor cannot exit until loop_ has become nonnull.  Combined with the guard logic of WebSocketMain, we know that
* Therefore loop_ is nonnull if defer_ is nonnull.
* Because loop_ is nulled before it is invalidated, we also do not need to be concerned about invalidation; the problems are the same.

So the whole ballgame is whether nominal defer can ever be called when defer_ is null -- the space between lines 1610 (when per 1611 defer_ was not null) and 1612 (where the value loaded at 1610 is used).  And because the only place defer_ becomes null is in the Impl dtor, this can only happen with threading or re-entrance.

The threading case is trival; I've suggested one assertion below to nail this down.

The re-entrance case is also correct.  The dtor calls Defer, which is bad mojo.  But that defer call completes before defer_ is nulled, so while it may nop it will never ub.
</blockquote></details>

Thanks for this!  It will serve as a great reference for anyone debugging who does `git blame` on my commit and goes to investigate the pull request.  I've also incorporated some of these notes into comments in the code.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx5RREECdDZyEy2WG5x:-Mx5b52Q2cW2oTZ2YllL:b3588hp) (no related file):*
> Factor the web socket management matter into a separate minimal class in a separate file with the same scope (via has-a / RAII) but that separates and reifies the Defer mechanism and its supporting thread logic.

Full agree on this one, I'd already come to the same conclusion myself.  The `meshcat.cc` file is was already too big, and this cleanup pushes it even further.  I'm not sure if I'll have time to refactor this soon, but it is on my list.

> ... phase enum ...

I had tried this approach in my early prototyping, but actually found it less readable, even setting aside the performance question.  However, that was prior to a lot of the other refactors that got staged out of this PR, so it's possible now that using an enum could be a win.  What I'll plan to do is merge this PR as-is to get this form of the better guards in place, and soonafter open a draft PR of what the enum solution would look like, and we can discuss there (=> #16695).

---
___
*[geometry/meshcat.cc, line 1609 at r11](https://reviewable.io/reviews/robotlocomotion/drake/16670#-Mx5R-r58vSpX4h25sx9:-Mx5b0Hg0Zln8HCUVi4O:b-hlfbqz) ([raw file](https://github.com/robotlocomotion/drake/blob/b555276046e7b00d88117141eec1001d825b0a55/geometry/meshcat.cc#L1609)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Please assert that you are on the main thread here, to guarantee that `this` is valid for the length of this function (because the main thread cannot be here and in the dtor at the same time).
</blockquote></details>

Done.  While working through this, I found one more id-check that was missing, and added it also.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16670)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
