### PR TITLE
Port drake/solvers to use drake_copyable

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #4861.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4895)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review, please.

/CC @soonho-tri @hongkai-dai you are welcome to weigh in / review if you like.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-:-KbI9_QstsxIU8WzEJUE:bd5j9xd)*

**Comment by soonho-tri** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbLDYLXaJlUQmacM-lm:-KbLDYLYgwAHTJDR3ZMP:b-i13v8a) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L20)):*
> ```objc
> #include "drake/common/drake_assert.h"
> #include "drake/common/eigen_autodiff_types.h"
> #include "drake/common/drake_copyable.h"
> ```

FYI, this section is not sorted.

---

*[drake/solvers/mathematical_program.h, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbLDnQ5SxLdaAWxTcGQ:-KbLDnQ5SxLdaAWxTcGR:b-9maksg) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L190)):*
> ```objc
> 
>    public:
>     DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(ConstraintImpl)
> ```

First of all, this looks perfectly fine to me. I have a non-blocking question for learning.

Here its base class `Constraint` has `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`. Does that fact still leave any choice for this derived class `ConstraintImpl`? In other words, is this line more about explicitly documenting the status or actually constraining this class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895)*

**Comment by soonho-tri** [comment]
:lgtm: (one minor comment and one non-blocking question)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-:-KbLGS-V8ufG3sL_Xu0j:b1puhkq)*

**Comment by jwnimmer-tri** [comment]
*[drake/solvers/mathematical_program.h, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbLDnQ5SxLdaAWxTcGQ:-KbLx8xvSzOCd3jtxq5z:bpz4ucc) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L190)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

First of all, this looks perfectly fine to me. I have a non-blocking question for learning.

Here its base class `Constraint` has `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`. Does that fact still leave any choice for this derived class `ConstraintImpl`? In other words, is this line more about explicitly documenting the status or actually constraining this class?
</blockquote></details>

As I understand it, subclasses can choose to implement the special functions (not using `= default`) even if the base class does not.  For example, the subclass copy ctor can call the base class default ctor, and manually transcribe any base class information that's needed.  So in some way there is a choice.  Of course, by default the special functions would be ill-formed, so absent -- and a developer would have to be pretty dedicated to add them back in a subclass!

However, my rationale in using the macro here is for (1) clearly documenting the choice for every class, and (2) preventing changes in the base class from silently changing the behavior of the subclass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbLDnQ5SxLdaAWxTcGQ:-KbLz3hsVAXEv52Dcrmg:bthegzp) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L190)):*
I see. Thanks for the explanation!

> my rationale in using the macro here is for (1) clearly documenting the choice for every class, and (2) preventing changes in the base class from silently changing the behavior of the subclass.

Perfect!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895)*

**Comment by sammy-tri** [comment]
Sigh...  It's really necessary to do this to all of the derived classes even when the parent already declared itself not copy/assignable?

:lgtm: despite my whining below.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/dreal_solver.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbM5jM7hmdnPO0sbzX3:-KbM5jM7hmdnPO0sbzX4:b-g28sxe) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/dreal_solver.h#L15)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(DrealSolver)
> 
>   DrealSolver() = default;
> ```

BTW does the code style guide now mandate this default?

---

*[drake/solvers/mathematical_program.h, line 2095 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbM5r9Dk8P8oqn_YCky:-KbM5r9EiZ7LhKxJc-Nq:b-5j1hxr) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L2095)):*
> ```objc
>     DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(SolverData)
>     SolverData() = default;
>     virtual ~SolverData() = default;
> ```

BTW Is "= default" now mandatory vs. "{}"?

---

*[drake/solvers/mosek_solver.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbM6BGGnWLUz2oQqFPn:-KbM6BGGnWLUz2oQqFPo:b4caws9) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mosek_solver.h#L18)):*
> ```objc
> 
>   MosekSolver() = default;
> ```

BTW if the style guide now mandates the default destructor also be explicitly specified, META.  If it doesn't, ignore this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-:-KbM5T3Y_BukRRq0Hu5p:b245b3o)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-:-KbM86ye6NDyA-UCF3JJ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
> Sigh...  It's really necessary to do this to all of the derived classes even when the parent already declared itself not copy/assignable?

I think yes, both for clarity, and because cppguide says so (at least for noncopyable classes).

---

Review status: 16 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/dreal_solver.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbM5jM7hmdnPO0sbzX3:-KbMbx2wQ_94HbIzc4-7:bwhcdzx) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/dreal_solver.h#L15)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW does the code style guide now mandate this default?
</blockquote></details>

Do you mean having to declare the constructor?  That is required by the compiler, because otherwise it disappears when a copy-constructor is declared (via the macro).

Or if you mean `= default;` vs `{}`?  That is discretionary.

---

*[drake/solvers/mathematical_program.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbLDYLXaJlUQmacM-lm:-KbMdYv2vMETlXrtBV-v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L20)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this section is not sorted.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 2095 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbM5r9Dk8P8oqn_YCky:-KbMddzYFs2cRTPraiiS:b-83og3x) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mathematical_program.h#L2095)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Is "= default" now mandatory vs. "{}"?
</blockquote></details>

Nope.

---

*[drake/solvers/mosek_solver.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-KbM6BGGnWLUz2oQqFPn:-KbMdkQdEkbyaVxQMXHU:bb6f9nr) ([raw file](https://github.com/robotlocomotion/drake/blob/eef616d67eeb2ee85f1bb0e388a1d069473cb2c5/drake/solvers/mosek_solver.h#L18)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW if the style guide now mandates the default destructor also be explicitly specified, META.  If it doesn't, ignore this.
</blockquote></details>

I don't think there's any rule about the dtor, other than "if you are a base class, your dtor must be virtual".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-:-KbMbmfv4UcmLFCjt5dD:b-yxl7cp)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4895#-:-KbQOB302bgC8QylDyLz:bnfp4nl)*

**Pull request merged**
