### PR TITLE
Fixed Center Of Mass modeling of Extra Heavy Duty Table

### PR DESCRIPTION
**Pull request by liangfok**
This fixes the center of mass modeling of the extra heavy duty table. The version in master has the center of mass sitting on the ground:

screenshot from 2016-09-08 20 42 04

The version in this PR has the center of mass in the middle of the table, which is expected given the spatial inertia equation that was employed.

table_collision_model_and_com

I also added `model.config` files and a README that informs users of how to load the models into Gazebo, which is useful for testing and debugging purposes.

This PR requires that #3387 be merged first since it references the cuboid spatial inertia calculator.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3396)

### CODE REVIEW

**Comment by liangfok** [comment]
+@lucy-tri for feature review please. Thanks.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KRBPqWiuMstKL9hRPMc:b-kykn05)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by Lucy-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KREKt0_0YgbSJrypJcf:b-wfxicu) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
> <author>
>     <name>Lucy</name>
>     <email>drake-users@mit.edu</email>
>   </author>

Do we have to include the author? Its in git history. Having to manually update this is prone to error.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREOWrWUJxS_djJs8ta:-KREOWrWUJxS_djJs8tb:bjlsmz3) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L38)):*
> TODO(lucy-tri): Compute a more accurate spatial inertia of this table.
This TODO is done, right?  Remove it.

---

*[drake/examples/kuka_iiwa_arm/models/table/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREL2MqPiuIf6TZJJC6:-KREL2MqPiuIf6TZJJC7:b6ebaop) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/model.config#L10)):*
> <author>
>     <name>Lucy</name>
>     <email>drake-users@mit.edu</email>
>   </author>
Do we have to include the author? Its in git history. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KRERMskp85fBVza6h03:b-3mztue) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > <author>
> >     <name>Lucy</name>
> >     <email>drake-users@mit.edu</email>
> >   </author>
> 
> Do we have to include the author? Its in git history. Having to manually update this is prone to error.
</details>
Unfortunately, the `model.config` specification states that the author is a "required" field:

http://gazebosim.org/tutorials?tut=model_structure#ModelConfig

Should I change it to be "Drake developers" instead of "Lucy"?

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREOWrWUJxS_djJs8ta:-KRER_ZEtMXvFxWOd-jh:b6bwu5) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L38)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > TODO(lucy-tri): Compute a more accurate spatial inertia of this table.
> This TODO is done, right?  Remove it.
</details>
Unfortunately, no. We currently modeling the table's spatial inertia as if it were a solid cuboid. The table is obviously _not_ solid. I can see big holes through the actual table :smile: .

---

*[drake/examples/kuka_iiwa_arm/models/table/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREL2MqPiuIf6TZJJC6:-KRERr1iPBDP4BH44WyE:b-wt0kkv) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/model.config#L10)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > <author>
> >     <name>Lucy</name>
> >     <email>drake-users@mit.edu</email>
> >   </author>
> Do we have to include the author? Its in git history. 
</details>
Same comment as above. Should I change it to be "Drake developers"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KRETbsnPwOGqAFe9Gx1:bchxssl) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Unfortunately, the `model.config` specification states that the author is a "required" field:
> 
> http://gazebosim.org/tutorials?tut=model_structure#ModelConfig
> 
> Should I change it to be "Drake developers" instead of "Lucy"?
</details>
Maybe we should ask on Slack.  But "Drake developers" sounds ok to me.  What about the email? That doesn't sound like an email to get tech support (or is it?).

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREOWrWUJxS_djJs8ta:-KRETptq8vpu5CuZH0H_:b-t91gdk) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L38)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Unfortunately, no. We currently modeling the table's spatial inertia as if it were a solid cuboid. The table is obviously _not_ solid. I can see big holes through the actual table :smile: .
</details>
Oh right, it's still modeled as solid. OK.

---

*[drake/examples/kuka_iiwa_arm/models/table/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREL2MqPiuIf6TZJJC6:-KRETwRnMzhipA7bX9Bk:b-7k8p1w) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/model.config#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Same comment as above. Should I change it to be "Drake developers"?
</details>
Do as above. Thanks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KREYdy8pu3LIXN2QRX_:bm3yuy5) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Maybe we should ask on Slack.  But "Drake developers" sounds ok to me.  What about the email? That doesn't sound like an email to get tech support (or is it?).
</details>
TTBOMK, `drake-users@mit.edu` is the only e-mail associated with Drake. I suppose we can discuss whether to add some more like `drake-support@mit.edu`. I wonder if a system should be setup to create a Github issue upon reception of an e-mail.

http://stackoverflow.com/questions/25051686/create-github-issue-via-email

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by jwnimmer-tri** [comment]
Perhaps consider `nobody@example.com` for the email.  If we don't care what it says, why make it appear real?

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KRF-Nh5CVqPd0c7bpLM:b-k2k7tj) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> TTBOMK, `drake-users@mit.edu` is the only e-mail associated with Drake. I suppose we can discuss whether to add some more like `drake-support@mit.edu`. I wonder if a system should be setup to create a Github issue upon reception of an e-mail.
> 
> http://stackoverflow.com/questions/25051686/create-github-issue-via-email
</details>
If that email (drake-users@mit.edu) is the current valid email, then let's just use that.  I was merely questioning if it was correct, and it seems like that is an email to use for this kind of thing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KRF0dbUvNDqv2yim5Wy:bcaz9u2) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> If that email (drake-users@mit.edu) is the current valid email, then let's just use that.  I was merely questioning if it was correct, and it seems like that is an email to use for this kind of thing. 
</details>
Yes, it is a valid e-mail address: http://mailman.mit.edu/mailman/listinfo/drake-users

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KRF4oDHrldjDAECm4Pi:bnfp4nl)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRTvLGcRIpP6D85WIi9:-KRTvLGcRIpP6D85WIiA:b-fnyr72) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/README.md#L4)):*
> the them
Typo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by liangfok** [comment]
@lucy-tri: Thanks!

Since today's Monday, +@sherm1 for platform review please.

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/README.md, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRTvLGcRIpP6D85WIi9:-KRTy6K8d5Ch_r8RNfLv:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/README.md#L4)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > the them
> Typo.
</details>
Done. Thanks.

---

*[drake/examples/kuka_iiwa_arm/models/desk/model.config, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREKt0ZmNpW9sjA8574:-KRTydOKu7I9azJ8oFAJ:b-rgfz4f) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/desk/model.config#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yes, it is a valid e-mail address: http://mailman.mit.edu/mailman/listinfo/drake-users
</details>
Since it's a valid e-mail address, I left it as is.

---

*[drake/examples/kuka_iiwa_arm/models/table/model.config, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KREL2MqPiuIf6TZJJC6:-KRTxcafsa3LjPw19Ciy:bhf2tf1) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9429f3f821f5a4cf5cea46ba3f02d8988a2fe5/drake/examples/kuka_iiwa_arm/models/table/model.config#L10)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Do as above. Thanks. 
</details>
Done. I left it unchanged since the e-mail is valid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KRTygLmy5_3zF2jjdgA:b-bq7cyk)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by sherm1** [comment]
Platform review: I don't buy the inertia properties, PTAL.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWgrShRpGC6DmHfRvW:-KRWgrSipgp9yMAiOf-2:bcx14ov) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L8)):*
> ```
>   The table is oriented such that its X axis is parallel with the table's depth,
>   the Y axis is parallel with the table's width, and its Z axis is parallel with
>   the table's height.
> ```

This is ambiguous. One of these needs a direction, like Z is positive up. Then the right hand rule is sufficient to orient the other two. Also, where is the origin?

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWgYXaCy4TIo7JWkyi:-KRWgYXaCy4TIo7JWkyj:b-2n5m5d) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L30)):*
> ```
> 
>         $ cd drake-distro/drake/common/spatial_inertia_calculators
>         $ ./spatial_inertia_solid_cuboid.py 0.7112 0.762 0.762 53.5
> ```

BTW, is this comment still accurate? You could just give the simple formula here; user can use any calculator.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWhN0OXMdzaP0JHW0C:-KRWhN0OXMdzaP0JHW0D:bhodtlx) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L33)):*
> ```
> 
>         Obviously, the table is not a cuboid meaning the spatial inertia matrix
>         is imperfect. Having accurate spatial inertia information may be
> ```

Actually this calculation seems likely to be absurdly incorrect. This is just a table top and some legs -- why would a rectangular solid be a good approximation? More reasonable would be a rectangular solid with dimensions of the table top, added to a collection of smaller rectangular solids representing the legs and cross members. That would qualify as "imperfect" but would at least get the general mass distribution right. I don't think the current calculation makes it all the way to "imperfect"! Please provide a more reasonable estimate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KRWiX768T4gTfhfZo0a:b-sh8ois)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWgrShRpGC6DmHfRvW:-KRYiF0M9iaZrA3xFVmx:bip9n2p) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is ambiguous. One of these needs a direction, like Z is positive up. Then the right hand rule is sufficient to orient the other two. Also, where is the origin?
</details>
Ah, I believe the confusion stems from my attempt at explaining the meaning of "width", "depth" and "height", which were terms used [here](http://www.mcmaster.com/#8020T32). I agree they are ambiguous.

However, I also think using the right hand rule is ambiguous since the X and Y axis can rotate around the Z axis.

I updated the statement to be what I consider to be absolutely clear. PTAL. Thanks.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWgYXaCy4TIo7JWkyi:-KRYk6tZ5ElxqRFVKYv1:bh5oug8) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, is this comment still accurate? You could just give the simple formula here; user can use any calculator.
</details>
Oh yeah, since we decided not to merge #3387, this is no longer valid. I've deleted it. The link to Wikipedia above has the equations.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWhN0OXMdzaP0JHW0C:-KRYoWM_-m6aRLvVs6ug:biz75e0) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Actually this calculation seems likely to be absurdly incorrect. This is just a table top and some legs -- why would a rectangular solid be a good approximation? More reasonable would be a rectangular solid with dimensions of the table top, added to a collection of smaller rectangular solids representing the legs and cross members. That would qualify as "imperfect" but would at least get the general mass distribution right. I don't think the current calculation makes it all the way to "imperfect"! Please provide a more reasonable estimate.
</details>
I would be happy to compute a more accurate spatial inertia for this cable. Can you please point me to code and/or math explaining how I can compute the overall spatial inertia given the individual spatial inertia of bodies that are welded together?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by liangfok** [comment]
Win32 CI failed while uploading results:

```
10:14:44    Error when uploading file: C:/Users/Administrator/workspace/experimental/0b4ef046/drake/build/Testing/20160913-1400/Update.xml
10:14:44    Error message was: The requested URL returned error: 504 Gateway Time-out
10:14:44    Problems when submitting via HTTP
```

@drake-jenkins-bot retest this please.

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWhN0OXMdzaP0JHW0C:-KRZJO-ifHUcsdbSkNL6:b-9ddylx) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L33)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I would be happy to compute a more accurate spatial inertia for this cable. Can you please point me to code and/or math explaining how I can compute the overall spatial inertia given the individual spatial inertia of bodies that are welded together?
</details>
This needs a little model-building software to do the calculation; it's not easy to do by hand. I suggest we ask Paul @Mitiguy the best way to do it or ask him for reasonable inertia properties. He isn't here today but will be back Wednesday. I'll email him and cc you, @liangfok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-KRWhN0OXMdzaP0JHW0C:-KRZLSjVdZ-t6xsh6IDq:b-ufbyvu) ([raw file](https://github.com/robotlocomotion/drake/blob/1acffe9e558e4432ef119ca74e8c08f815466866/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This needs a little model-building software to do the calculation; it's not easy to do by hand. I suggest we ask Paul @Mitiguy the best way to do it or ask him for reasonable inertia properties. He isn't here today but will be back Wednesday. I'll email him and cc you, @liangfok.
</details>
Thanks! I think knowing how to do this will be _very useful_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396)*

**Comment by Lucy-tri** [comment]
For the sake of history I have these thoughts (some of which we discuss in email). When this PR first came across, it seemed done so I approved it. When Sherm pointed out some inaccuracies, I started to wonder if it really makes sense to do detailed inertia for this particular table. The table has the Kuka iiwa arm bolted to it (at least at CAM3: and PAL bought the same table for that purpose). The table is meant to never move: it should be bolted to the floor, or have sandbags on it to prevent it from tipping. If it tipped in real life, the expensive arm would be damaged. 

While we could do simulations of this table moving, we would never want to move the table in real life life.  There would be no way to easily compare the simulation to real life.

Perhaps there are other objects that make more sense for accurate inertia.

After I emailed portions of the above, several of us discussed it and Liang and others talked about how it might still be a good exercise to learn how to do this kind of thing. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KRnF6jFcz8kedtIZCy9:b-65lwrm)*

**Comment by RussTedrake** [comment]
Coming in late here, but my first reaction is this:
If the table has sandbags, etc, then it should be added into the world using a fixed joint, and it’s inertial parameters are irrelevant.

**Comment by liangfok** [comment]
Quick update: @mitiguy provided inertia modeling parameters he derived using professional CAD software ([SimWise](https://www.design-simulation.com/SimWise4d/index.php)). Now that we have that, we might as well try to use it! I'll evaluate his numbers soon.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KRsC42WmLHZW88gXvsL:bs3zvsm)*

**Comment by RussTedrake** [comment]
It’s fine to have reasonable numbers in there.  But you don’t want the model’s state to include the 6 dof of the table w/ respect to the world.  Since the table is fixed in the world, its inertia is irrelevant.

**Comment by liangfok** [comment]
Agreed. I'm treating this simply as an exercise in learning _how_ to derive an initial inertia model, which can then be refined using system identification techniques.

**Comment by mitiguy** [comment]
Hi Liang,

Attached is screen shot:
McMasterTableMassInertiaPropertiesMKSUnits.jpg
Material:  Steel - ANSI C1020.

Simwise calculated the following:
Mass = *50.4 kg*   (which agree's with the mass listed on the data sheet).
Center of mass:   x*=0.356 m, y = 0.381 m, z = 0.498 m*.
Moments of inertia in kg*m^2:  I*xx = 8.73,  Iyy = 8.2,  Izz = 8.34*.
Products of inertia are negligible (approximately 0.0).

World origin is bottom of back-left leg.

Note: Liang and I understand the table can be rigidly connected to World
and that the mass properties are not relevant for this analysis.
Liang wanted an example of what could be done to calculate mass,
center of mass, and inertia properties of more relevant objects.
We decided to use the robot table as a simple example.
Next time, it may be best to do calculations on a more relevant object.
I apologize if this test case caused confusion.

All the best,


- Paul

**Comment by mitiguy** [comment]
Hi Liang,
 
Attached (see below) is screen shot:
McMasterTableMassInertiaPropertiesMKSUnits.jpg
Material:  Steel - ANSI C1020.

Simwise calculated the following:
Mass = 50.4 kg   (which agree's with the mass listed on the data sheet).
Center of mass:   x=0.356 m, y = 0.381 m, z = 0.498 m.
Moments of inertia in kg*m^2:  Ixx = 8.73,  Iyy = 8.2,  Izz = 8.34.
Products of inertia are negligible (approximately 0.0).
 
World origin is bottom of back-left leg.

Note: Liang and I understand the table can be rigidly connected to World
and that the mass properties are not relevant for this analysis.
Liang wanted an example of what could be done to calculate mass,
center of mass, and inertia properties of more relevant objects.
We decided to use the robot table as a simple example.
Next time, it may be best to do calculations on a more relevant object.
I apologize if this test case caused confusion.

All the best,


- Paul
mcmastertablemassinertiapropertiesmksunits

**Comment by liangfok** [comment]
Thanks @mitiguy! I will get back to this soon. Currently focused on getting #3494 into master.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3396#-:-KSBLoJLqr8VfmEkRlSS:b-odvlqe)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-matlab please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
I believe this PR (at best) awaits further edits based on Paul's information, thus I'll tag it DNM & DNR.  Feel free to remove the tags once it has been updated.

**Comment by Lucy-tri** [comment]
I'm taking myself off of this as an assignee and adding @liangfok as an assignee, since Liang said he will work on this next.

**Comment by jwnimmer-tri** [comment]
Thank you for your interest in contributing to Drake!  This PR has seen no updates in over one month, so I am going to close it.  Please feel free to re-open (or open a fresh PR) if there are new updates to consider.

**Pull request closed without merging**
