### PR TITLE
Port drake/multibody tests to FindResource

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5893.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6435)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Comment by amcastro-tri** [comment]
Thank you @jwnimmer-tri, just a few BTW's. :lgtm: 

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/collision/BUILD, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-Knd_WjVFvddR3KKbnv8:-Knd_WjVFvddR3KKbnv9:b-4dj6z2) ([raw file](https://github.com/robotlocomotion/drake/blob/b48a7254ed340fa749234643de802b9a4d174d35/drake/multibody/collision/BUILD#L116)):*
> ```Python
>         "//drake/multibody/joints",
>         "//drake/multibody/parsers",
>         "//drake/common:find_resource",
> ```

BTW, alphabetize?

---

*[drake/multibody/parsers/BUILD, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-Knd_jNsGze3xZguk-Wv:-Knd_jNsGze3xZguk-Ww:b-4dj6z2) ([raw file](https://github.com/robotlocomotion/drake/blob/b48a7254ed340fa749234643de802b9a4d174d35/drake/multibody/parsers/BUILD#L113)):*
> ```Python
>         ":test_models",
>         "//drake/examples/Atlas:models",
>         "//drake/common:find_resource",
> ```

BTW, alphabetize?

---

*[drake/multibody/parsers/test/urdf_parser_test/urdf_parser_test.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-Knd_zGQ_9Zyx7vlVs_0:-Knd_zGQ_9Zyx7vlVs_1:be96pja) ([raw file](https://github.com/robotlocomotion/drake/blob/b48a7254ed340fa749234643de802b9a4d174d35/drake/multibody/parsers/test/urdf_parser_test/urdf_parser_test.cc#L96)):*
> ```cpp
> 
> GTEST_TEST(URDFParserTest, TestParseMaterial) {
>   const string base{"drake/multibody/parsers/test/urdf_parser_test/"};
> ```

BTW, since you are changing this variable name here; "base" could be (somewhere a 100 lines below) be understood like a "robot base" or link. Maybe rename to "path" or "resources_path"?

---

*[drake/multibody/rigid_body_plant/BUILD, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-KndaL56bmWpP6U_K2mb:-KndaL56bmWpP6U_K2mc:b-4dj6z2) ([raw file](https://github.com/robotlocomotion/drake/blob/b48a7254ed340fa749234643de802b9a4d174d35/drake/multibody/rigid_body_plant/BUILD#L179)):*
> ```Python
>     deps = [
>         ":rigid_body_plant",
>         "//drake/common:find_resource",
> ```

BTW, alphabetize?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-:-KndbRpkXNkROQRMGx2J:b-q6rs67)*

**Comment by jwnimmer-tri** [comment]
Thanks for reading it all!

+@sammy-tri for platform review per on-call rotation, please.

---

Review status: 32 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/test/urdf_parser_test/urdf_parser_test.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-Knd_zGQ_9Zyx7vlVs_0:-Knded6lzxfwdeWweOvD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b48a7254ed340fa749234643de802b9a4d174d35/drake/multibody/parsers/test/urdf_parser_test/urdf_parser_test.cc#L96)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, since you are changing this variable name here; "base" could be (somewhere a 100 lines below) be understood like a "robot base" or link. Maybe rename to "path" or "resources_path"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-:-Kndbu-euT7fm92q5093:b-3278fv)*

**Comment by amcastro-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/multibody/parsers/BUILD, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-Knd_jNsGze3xZguk-Wv:-KndnDpTIc9eh3s3kcTF:bmu0hll) ([raw file](https://github.com/robotlocomotion/drake/blob/b48a7254ed340fa749234643de802b9a4d174d35/drake/multibody/parsers/BUILD#L113)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, alphabetize?
</blockquote></details>

oh wow, I just realized this was in "data"! good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6435)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 32 of 37 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-KnekyAzR1jMYS1a9Qwr:-KnekyB0SpOFeHSFLekN:bnsplt4) ([raw file](https://github.com/robotlocomotion/drake/blob/290724ea6a057a98459a55ebca6855ed376bbab1/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L11)):*
> ```cpp
> #include "drake/common/eigen_matrix_compare.h"
> #include "drake/common/eigen_types.h"
> #include "drake/common/find_resource.h"
> ```

BTW this test doesn't explicitly list find_resource as a dep like some of the others do in the BUILD file  (not new vs. drake_path and not necessarily a problem)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-:-Knem218a-LFv2LHRbyh:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/rigid_body_plant/test/kinematics_results_test.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6435#-KnekyAzR1jMYS1a9Qwr:-Knep1PA0YtMdTYrWqVc:b38sk9r) ([raw file](https://github.com/robotlocomotion/drake/blob/290724ea6a057a98459a55ebca6855ed376bbab1/drake/multibody/rigid_body_plant/test/kinematics_results_test.cc#L11)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this test doesn't explicitly list find_resource as a dep like some of the others do in the BUILD file  (not new vs. drake_path and not necessarily a problem)
</blockquote></details>

Yeah.  The parsers pull it in implicitly, and that seemed okay?  _Shrug._

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6435)*

**Pull request merged**
