### PR TITLE
Function that shifts a body's center of mass location and preserves its central unit inertia.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR #18582 is part of resolution towards issue #17571.

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NM1_R0qDkYTawUwnNt0:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature pass done. I had some trouble following the logic, PTAL.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NMAXCF57Y9CWIxHUosB:b-qzl6jk)* status: 17 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rigid_body.h` line 225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAJDYO6S1hHpefZMPN:-NMAJDYO6S1hHpefZMPO:bojk3gg) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L225)):*
nit: set -> sets per style guide. Also consider wordsmithing for readability, e.g.
> Sets the center of mass position for `this` rigid body B ...

BTW Remember that the first sentence in Doxygen doc is the "brief" that shows up next to the "table of contents" entry for the function in the RigidBody class. That should be worded to help user pick the right function to look at in more detail so doesn't need to have everything crammed in. You could make it "Sets the center of mass location while preserving the central inertia." and then introduce symbols and details in the next sentences.
___
*[`multibody/tree/rigid_body.h` line 228 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAM4sE6ukt5p12-Ehx:-NMAM4sE6ukt5p12-Ehy:b-3gefxb) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L228)):*
> ```objc
>   /// to center_of_mass_position and modify B's inertia about Bo (B's origin) so
>   /// B's inertia about Bcm (B's center of mass) is unchanged.
>   /// @param[out] context contains the state of the multibody system.
> ```

nit: in,out
___
*[`multibody/tree/rigid_body.h` line 230 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAKtBc4F49-H3fdK6v:-NMAKtBd9OE5eaLL553W:bh9rrep) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L230)):*
> ```objc
>   /// @param[out] context contains the state of the multibody system.
>   /// @param[in] center_of_mass_position position vector from Bo (B's origin) to
>   /// Bcm (B's center of mass), expressed in B.
> ```

nit: you just defined Bcm 3 lines above this; no need to repeat it (same for Bo)
___
*[`multibody/tree/rigid_body.h` line 231 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAL6vDAHPMms5PEQLV:-NMAL6vE4l9rly80UBZV:b-h2a6l5) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L231)):*
> ```objc
>   /// @param[in] center_of_mass_position position vector from Bo (B's origin) to
>   /// Bcm (B's center of mass), expressed in B.
>   /// @note G_BBo_B (this body B's rotational inertia about Bo, expressed in B)
> ```

nit: G is the _unit_ inertia or gyration matrix
___
*[`multibody/tree/rigid_body.h` line 235 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMALkYqBUAKroQzH0Lm:-NMALkYqBUAKroQzH0Ln:buxx379) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L235)):*
> ```objc
>   /// function can work well when a rigid body's mass is concentrated at a
>   /// single point (or mostly concentrated near a single point), its general
>   /// utility for properly accounting for inertia changes due to center of mass
> ```

BTW suggestion: inertia changes due to _arbitrary_ center of mass changes
___
*[`multibody/tree/rigid_body.h` line 236 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMALaRn-x7-RLYiiOds:-NMALaRn-x7-RLYiiOdt:b-sktos0) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L236)):*
> ```objc
>   /// single point (or mostly concentrated near a single point), its general
>   /// utility for properly accounting for inertia changes due to center of mass
>   /// changes questionable. If needed, use SetSpatialInertiaInBodyFrame().
> ```

BTW suggestion: "Consider using SetSpatialInertiaInBodyFrame() instead."
___
*[`multibody/tree/rigid_body.h` line 403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAI1dZ7fUKWO6xpbln:-NMAI1dZ7fUKWO6xpblo:bsjmblv) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L403)):*
> ```objc
> 
>  private:
>   /// For `this` rigid body B, set its center of mass position stored in context
> ```

nit: private function should not use doxygen "///" comments, just "//"
___
*[`multibody/tree/rigid_body.h` line 404 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAICPcBPUIs_QQgkCc:-NMAICPcBPUIs_QQgkCd:bdp2x1l) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L404)):*
> ```objc
>  private:
>   /// For `this` rigid body B, set its center of mass position stored in context
>   /// to center_of_mass_position, but does not modify other inertia properties..
> ```

nit: extra "." at eol
___
*[`multibody/tree/rigid_body.h` line 405 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAIKuGEHxknwin-Dk_:-NMAIKuGEHxknwin-Dka:botkfns) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L405)):*
> ```objc
>   /// For `this` rigid body B, set its center of mass position stored in context
>   /// to center_of_mass_position, but does not modify other inertia properties..
>   /// @param[out] context contains the state of the multibody system.
> ```

nit: in,out (also below)
___
*[`multibody/tree/rigid_body.cc` line 71 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAOZi1566-aeniybRY:-NMAOZi1566-aeniybRZ:b-bbyvwp) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L71)):*
> ```cpp
> void RigidBody<T>::SetCenterOfMassInBodyFrameAndPreserveCentralInertia(
>     systems::Context<T>* context,
>     const Vector3<T>& center_of_mass_offset) const {
> ```

minor: this parameter is called "center_of_mass_position" in the declaration. That seems very different from center_of_mass_offset. Please clarify and check that the code matches the documentation. Should definitely use the same name in both places!
___
*[`multibody/tree/rigid_body.cc` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMANL-K8hUsQ9fw9uEe:-NMANL-L-ZmsDA3PUH_y:b-lm6w1f) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L78)):*
> ```cpp
>   // Get B's initial spatial inertia about Bo (before Bcm changes location).
>   const SpatialInertia<T>& Mi_BBo_B =
>       CalcSpatialInertiaInBodyFrame(*context);
> ```

nit: this function and the previous one don't return a reference (remove "&" to avoid confusion)

Actually, I don't think you need to call the previous one at all. Doesn't M_BBo_B contain p_BoBcm_B already? You can just use `get_com()` which does return a reference.
___
*[`multibody/tree/rigid_body.cc` line 84 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAQD9-4FtJZ1V2ePMo:-NMAQD9-4FtJZ1V2ePMp:b-x1xod7) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L84)):*
> ```cpp
>   const UnitInertia<T>& Gi_BBo_B = Mi_BBo_B.get_unit_inertia();
>   const RotationalInertia<T> I_BBo_B = Gi_BBo_B.ShiftToThenAwayFromCenterOfMass(
>       /* mass = */ 1, pi_BoBcm_B, center_of_mass_offset);
> ```

I can't follow this. Looking at the docs for the ShiftToThen... function it is intended for shifting an inertia from one "about" point to another. But here we want to leave the about point alone, while preserving the inertia's value if it were shifted to the new Bcm. Assuming this is right, can you improve the documentation? I don't think just fixing the name of the center_of_mass_position/offset parameter would be enough for me to understand it. Maybe some notation for the initial and final com, like Bcmi/Bcmf would help? I'd like to understand how using the Shift function this way produces the behavior we want. 
___
*[`multibody/tree/rigid_body.cc` line 86 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAPhVr5R4s_DAVez5e:-NMAPhVr5R4s_DAVez5f:bk2b61b) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L86)):*
> ```cpp
>       /* mass = */ 1, pi_BoBcm_B, center_of_mass_offset);
> 
>   // Modify the context -- update B's uint inertia about Bo.
> ```

nit: typo uint -> unit
___
*[`multibody/tree/rigid_body.cc` line 87 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMARZY8-MG5dfkkWh8f:-NMARZY8-MG5dfkkWh8g:b-ce4p98) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L87)):*
> ```cpp
> 
>   // Modify the context -- update B's uint inertia about Bo.
>   SetUnitInertiaAboutBodyOrigin(context, UnitInertia<T>(I_BBo_B));
> ```

minor: this is bothering me a little. Since we haven't moved the COM yet, it is possible that the SpatialInertia for this body is invalid at this point. I guess since this is a private method we can ensure it doesn't blow up. But I'd like to see some documentation here noting that _both_ of these methods must be called together to avoid invalid mass props. Consider combining these into a single private method that sets both the com and unit inertia. The original (bad) public method could then just call that single routine with the new COM and original unit inertia, which I think would actually be more clearly a misuse than what appears there now.
___
*[`multibody/tree/test/rigid_body_test.cc` line 169 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMASTSt2gRB_4It-7n1:-NMASTSt2gRB_4It-7n2:b-hgq4n6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/test/rigid_body_test.cc#L169)):*
> ```cpp
> TEST_F(RigidBodyTest, SetCenterOfMassInBodyFrameAndPreserveCentralInertia) {
>   // Construct a multibody plant having a cube B of dimension 2*L whose spatial
>   // inertia correspondds to all mass concentrated at Bcm (B's center of mass).
> ```

typo dd -> d
___
*[`multibody/tree/test/rigid_body_test.cc` line 174 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMASxaq3_PmMAUBKgt1:-NMASxaq3_PmMAUBKgt2:b-qgu68g) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/test/rigid_body_test.cc#L174)):*
> ```cpp
>   Vector3d p_BoBcm_B(L, 0, 0);  // Position from Bo to Bcm, expressed in B.
>   const UnitInertia<double> G_BBo_B(0, L*L, L*L);  // By-hand calculation.
>   SpatialInertia<double> M_BBo_B(mass, p_BoBcm_B, G_BBo_B);
> ```

minor: I'm having trouble reconciling this SpatialInertia with the comment above that claims we have a cube. Where is Bo for the cube? This looks more like a line of length 2L along x with Bo at one end and the COM at the middle. But then the inertia about Bo doesn't seem right for a thin rod ml^2/12. Consider starting out with an easy-to-grasp central inertia and then shifting to Bo? Maybe use an actual cube? Can you make this clearer somehow? An ASCII sketch?
___
*[`multibody/tree/test/rigid_body_test.cc` line 229 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAWbQx3vLluNFGC064:-NMAWbQx3vLluNFGC065:br7xjup) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/test/rigid_body_test.cc#L229)):*
> ```cpp
>       I_BBo_B_expected.CopyToFullMatrix3(), kTolerance));
> 
>   // Verify B's unit inertia about Bcm is still zero.
> ```

BTW it seems like a special case to start (and end) with a zero inertia matrix. Can you do something more general or add a comment at the start of the test explaining why this is general despite appearances?

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/tree/rigid_body.h` line 225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAJDYO6S1hHpefZMPN:-NMkRFTE54otFf9FEciX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L225)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: set -> sets per style guide. Also consider wordsmithing for readability, e.g.
> Sets the center of mass position for `this` rigid body B ...

BTW Remember that the first sentence in Doxygen doc is the "brief" that shows up next to the "table of contents" entry for the function in the RigidBody class. That should be worded to help user pick the right function to look at in more detail so doesn't need to have everything crammed in. You could make it "Sets the center of mass location while preserving the central inertia." and then introduce symbols and details in the next sentences.
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 228 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAM4sE6ukt5p12-Ehx:-NMkSNCTEGCbTjRMV-Z_:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L228)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: in,out
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 230 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAKtBc4F49-H3fdK6v:-NMkTKWu1uxApRXfxw6s:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L230)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: you just defined Bcm 3 lines above this; no need to repeat it (same for Bo)
</blockquote></details>

Done
___
*[`multibody/tree/rigid_body.h` line 231 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAL6vDAHPMms5PEQLV:-NMkTV6f2FIg_qYtm7Qx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L231)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: G is the _unit_ inertia or gyration matrix
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 235 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMALkYqBUAKroQzH0Lm:-NMkTuNR80hIyQ4gUPD5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L235)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW suggestion: inertia changes due to _arbitrary_ center of mass changes
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 236 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMALaRn-x7-RLYiiOds:-NMkUE1W9MwUAqY-P-Lg:bs7wumb) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L236)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW suggestion: "Consider using SetSpatialInertiaInBodyFrame() instead."
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAI1dZ7fUKWO6xpbln:-NMkUPovBA5RxAh6nez5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L403)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: private function should not use doxygen "///" comments, just "//"
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 404 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAICPcBPUIs_QQgkCc:-NMkUQo512qi6aPgIvi-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L404)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: extra "." at eol
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 405 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAIKuGEHxknwin-Dk_:-NMkUZJT60gcRNSaxxIL:b-axt0xg) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.h#L405)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: in,out (also below)
</blockquote></details>

Done (done also below).
___
*[`multibody/tree/rigid_body.cc` line 71 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAOZi1566-aeniybRY:-NMkUt8bE4dm-ZW0OxmO:bkw4icz) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L71)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this parameter is called "center_of_mass_position" in the declaration. That seems very different from center_of_mass_offset. Please clarify and check that the code matches the documentation. Should definitely use the same name in both places!
</blockquote></details>

Done. Changed to center_of_mass_offset to center_of_mass_position everywhere.
___
*[`multibody/tree/rigid_body.cc` line 78 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMANL-K8hUsQ9fw9uEe:-NMkVfAc0haP786ed0AM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L78)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this function and the previous one don't return a reference (remove "&" to avoid confusion)

Actually, I don't think you need to call the previous one at all. Doesn't M_BBo_B contain p_BoBcm_B already? You can just use `get_com()` which does return a reference.
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.cc` line 84 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAQD9-4FtJZ1V2ePMo:-NMksLQg8G0VXnqjJowb:bq0vryu) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L84)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I can't follow this. Looking at the docs for the ShiftToThen... function it is intended for shifting an inertia from one "about" point to another. But here we want to leave the about point alone, while preserving the inertia's value if it were shifted to the new Bcm. Assuming this is right, can you improve the documentation? I don't think just fixing the name of the center_of_mass_position/offset parameter would be enough for me to understand it. Maybe some notation for the initial and final com, like Bcmi/Bcmf would help? I'd like to understand how using the Shift function this way produces the behavior we want. 
</blockquote></details>

Updated documentation and names.  
I have to draw a picture to make sense of this.
___
*[`multibody/tree/rigid_body.cc` line 86 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAPhVr5R4s_DAVez5e:-NMkVtwB3YCKxWLBje17:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: typo uint -> unit
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.cc` line 87 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMARZY8-MG5dfkkWh8f:-NMkjjeN90dCk1Y8UHaP:by0ypd0) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/rigid_body.cc#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this is bothering me a little. Since we haven't moved the COM yet, it is possible that the SpatialInertia for this body is invalid at this point. I guess since this is a private method we can ensure it doesn't blow up. But I'd like to see some documentation here noting that _both_ of these methods must be called together to avoid invalid mass props. Consider combining these into a single private method that sets both the com and unit inertia. The original (bad) public method could then just call that single routine with the new COM and original unit inertia, which I think would actually be more clearly a misuse than what appears there now.
</blockquote></details>

Done.  Added documentation to clarify possible need to call both functions.
___
*[`multibody/tree/test/rigid_body_test.cc` line 169 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMASTSt2gRB_4It-7n1:-NMkvL3j-R5LblRXEXiR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/test/rigid_body_test.cc#L169)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo dd -> d
</blockquote></details>

Done.
___
*[`multibody/tree/test/rigid_body_test.cc` line 174 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMASxaq3_PmMAUBKgt1:-NMkxWNL4yiF-QjmicDL:b-47fhu1) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/test/rigid_body_test.cc#L174)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I'm having trouble reconciling this SpatialInertia with the comment above that claims we have a cube. Where is Bo for the cube? This looks more like a line of length 2L along x with Bo at one end and the COM at the middle. But then the inertia about Bo doesn't seem right for a thin rod ml^2/12. Consider starting out with an easy-to-grasp central inertia and then shifting to Bo? Maybe use an actual cube? Can you make this clearer somehow? An ASCII sketch?
</blockquote></details>

My fault: This was not a cube -- it is just a particle.
___
*[`multibody/tree/test/rigid_body_test.cc` line 229 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NMAWbQx3vLluNFGC064:-NMkxkzpDyqvy83O09Ta:bxqnvuq) ([raw file](https://github.com/RobotLocomotion/drake/blob/b3f3138232cf0e2f40b7e5709a925e0861097616/multibody/tree/test/rigid_body_test.cc#L229)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it seems like a special case to start (and end) with a zero inertia matrix. Can you do something more general or add a comment at the start of the test explaining why this is general despite appearances?
</blockquote></details>

Since it is a particle (not a rigid body), it is not that general.  
Is it enough of a test?  Hmmmm.

**Review by sherm1 — COMMENTED** [review]
Thanks, it's much clearer now! Feature :lgtm: with a few minor comments.

@rpoyner-tri for platform review Tuesday per rotation, please

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NN3waCK7NlG69m_1_pg:b-j7h1gi)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rigid_body.h` line 210 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NN3sLDe8RfJDgTh00Dh:-NN3sLDf6K4crf6skFRu:bc7pgyo) ([raw file](https://github.com/RobotLocomotion/drake/blob/fca4857c86bf7084aa231cdf80e97c8085be096d/multibody/tree/rigid_body.h#L210)):*
> ```objc
> 
>   /// Sets this body's center of mass position while preserving its inertia
>   /// about its body origin.
> ```

BTW this brief isn't scary enough for this awful function. Consider preceding with "(Advanced)" and/or adding something like "(dangerous)"
___
*[`multibody/tree/rigid_body.h` line 216 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NN3tF2o8pzomUyEiTR3:-NN3tF2o8pzomUyEiTR4:b-c9vaih) ([raw file](https://github.com/RobotLocomotion/drake/blob/fca4857c86bf7084aa231cdf80e97c8085be096d/multibody/tree/rigid_body.h#L216)):*
> ```objc
>   /// (B's center of mass), expressed in B.
>   /// @note This function changes B's center of mass position without modifying
>   /// G_BBo_B (B's unit inertia about Bo, expressed in B).
> ```

BTW Consider emphasizing here that this is very unlikely to be what the caller wants to do. (Either in the note or add a separate `@warning`)
___
*[`multibody/tree/rigid_body.h` line 218 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NN3tYWy7BdbzJgC8mFa:-NN3tYWy7BdbzJgC8mFb:b-4phwr) ([raw file](https://github.com/RobotLocomotion/drake/blob/fca4857c86bf7084aa231cdf80e97c8085be096d/multibody/tree/rigid_body.h#L218)):*
> ```objc
>   /// G_BBo_B (B's unit inertia about Bo, expressed in B).
>   /// Consider using SetSpatialInertiaInBodyFrame() or
>   /// SetCenterOfMassInBodyFrameAndPreserveCentralInertia().
> ```

minor: this documentation needs to be more direct throughout about warning the user about the horribleness of moving the com without preserving the central inertia

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/tree/rigid_body.h` line 210 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NN3sLDe8RfJDgTh00Dh:-NN4fRcf-Ry6GFucTpkN:bs7wumb) ([raw file](https://github.com/RobotLocomotion/drake/blob/fca4857c86bf7084aa231cdf80e97c8085be096d/multibody/tree/rigid_body.h#L210)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this brief isn't scary enough for this awful function. Consider preceding with "(Advanced)" and/or adding something like "(dangerous)"
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 216 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NN3tF2o8pzomUyEiTR3:-NN4fUIZ04XxW_XFj38Y:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fca4857c86bf7084aa231cdf80e97c8085be096d/multibody/tree/rigid_body.h#L216)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Consider emphasizing here that this is very unlikely to be what the caller wants to do. (Either in the note or add a separate `@warning`)
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 218 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-NN3tYWy7BdbzJgC8mFa:-NN4gNkxDFZfUURJBgug:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fca4857c86bf7084aa231cdf80e97c8085be096d/multibody/tree/rigid_body.h#L218)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this documentation needs to be more direct throughout about warning the user about the horribleness of moving the com without preserving the central inertia
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri plus for actual assignment :)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NN84XloCIGg4TBY3HT6:bckgjd0)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NN8YZlz5Caw7xBMEg0m:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
Commits need curation. We can do `squashing now` but would like some hint for the commit log message. Is the message for the first commit good enough @mitiguy ?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NN8Yp6p4kXRy934U_4w:b-vlqxwz)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18582#-:-NN8rGo2AkOaKanFitzu:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/18582 resolves https://github.com/RobotLocomotion/drake/issues/17571.

**Pull request merged**
