### PR TITLE
[fem] Add unit tests for DeformableBodyConfig

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17099)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for sole review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17099#-:-N1BWVD93wmexBmGc2oK:b-4spwk0)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17099#-:-N1EIL6T14rGSoeKitjh:bg7igkv)* status: 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHKar0Fa0OHlirZiS:-N1EHKar0Fa0OHlirZiT:b-l102e3) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L32)):*
> ```objc
>    0.49.
>  - Mass damping coefficient: Controls the strength of mass damping. The damping
>    ratio contributed by mass damping is inversely proportional to the frequency
> ```

minor, re damping ratio relationship to frequency. Would you happen to have a reference we can cite here?
Not sure how useful or confusing this is to someone with no continuous mechanics background. (it skims over details like having vibration modes with different frequencies)
___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHDFb44_215Yr9aa6:-N1EHDFb44_215Yr9aa7:b9bvn0s) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L34)):*
> ```objc
>    ratio contributed by mass damping is inversely proportional to the frequency
>    of the motion. Must be non-negative. Default to 0. See DampingModel.
>  - Stiffness damping coefficient: Controls the strength of stiffness damping.
> ```

nit, add units for damping?
___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHwpx22kEYHNiriea:-N1EHwpx22kEYHNirieb:bvjaiff) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L55)):*
> ```objc
>   DeformableBodyConfig() = default;
> 
>   /* Setters. */
> ```

minor, I don't think this /*Setters*/ will render ok in Doxygen? 
I'd remove. But if you like it, you might consider using a `@group`.
___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHnXM3Y8EBEHwlBse:-N1EHnXN7dNKl0UkxkMA:b62m5ze) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L90)):*
> ```objc
>   }
> 
>   /* Getters. */
> ```

minor, remove /* Getters */

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17099)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHKar0Fa0OHlirZiS:-N1FRs4sBM0T29CUt6fG:b6mzxxl) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, re damping ratio relationship to frequency. Would you happen to have a reference we can cite here?
Not sure how useful or confusing this is to someone with no continuous mechanics background. (it skims over details like having vibration modes with different frequencies)
</blockquote></details>

I don't have a good reference. I'm ok with just gutting this sentence. Does that help?
___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHDFb44_215Yr9aa6:-N1FTGSK2SheD-5pTcbD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L34)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, add units for damping?
</blockquote></details>

Done.
___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHwpx22kEYHNiriea:-N1FS1EtCIrqhonk9FIW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L55)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, I don't think this /*Setters*/ will render ok in Doxygen? 
I'd remove. But if you like it, you might consider using a `@group`.
</blockquote></details>

Done.
___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHnXM3Y8EBEHwlBse:-N1FS24qDEYNm_UyuJv0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L90)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, remove /* Getters */
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17099)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHKar0Fa0OHlirZiS:-N1FaYJwAiPw_phnzBy5:b-touak0) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L32)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't have a good reference. I'm ok with just gutting this sentence. Does that help?
</blockquote></details>

I personally like the extra info. It'd just be nice to reference a paper. I remember reading about this in the past. I'll see it I find it again.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17099)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @amcastro-tri)

___
*[`multibody/fixed_fem/dev/deformable_body_config.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17099#-N1EHKar0Fa0OHlirZiS:-N1GCNR674Np7bavRdl-:bvbb5y5) ([raw file](https://github.com/robotlocomotion/drake/blob/e7628ff62d426738489a022dbb28eec0f39524ed/multibody/fixed_fem/dev/deformable_body_config.h#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I personally like the extra info. It'd just be nice to reference a paper. I remember reading about this in the past. I'll see it I find it again.
</blockquote></details>

Ok, I added a TODO.

**Pull request merged**
