### PR TITLE
Fix and/or cleanup OpenGL dependencies

### LINKED ISSUE #13606: Additional Focal Dependencies for Binary Install
Recently upgraded from 18.04 to 20.04 via clean install. 

Today installed Drake via binary [https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz](https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz).

Added drake to python path. 

`import pydrake` => `ImportError: libClp.so.1`.

This was because I forgot to run `sudo .\install_prereqs`.  After running script, first error resolved.

Try again: `import pydrake` => `ImportError: libnlopt.so.0`. Resolved with `sudo apt install libnlopt0`

Try again: `import pydrake` => `ImportError: libOpenGL.so.0`. Resolved with `sudo apt install libopengl0`

Didn't have this issue with 18.04, although likely because these libraries were available on my system from all the other projects over time.  Not sure if `sudo apt install libopengl-dev` is preferred over non-dev version.  I don't think I missed any install steps (running setup script and adding to Python path).

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #13606.

---

We need either `libOpenGL.so`, `libOpenGL.so.0`, `libGLX.so`, `libGLX.0`, `GL/gl.h`, and
`GL/glx.h` (modern, vendor neutral) or `libGL.so`, `libGL.so.1`, `GL/gl.h`, and `GL/glx.h`
(legacy). Vendor neutral is preferable, for NVIDIA users and others, so we choose `libOpenGL.so` and `libGLX.so`
rather than `libGL.so`.

Also rebuild VTK and drake-visualizer to ensure they are correctly linked to
`libOpenGL.so` and `libGLX.so` rather than `libGL.so`.

**Ubuntu 18.04 (Bionic)**

*package contents:*

| package           | libraries                                            | headers               | pkg-config  |
|-------------------|------------------------------------------------------|-----------------------|-------------|
| libgl1-mesa-dev   |                                                      |                       | gl.pc       |
| mesa-common-dev   |                                                      | **GL/gl.h GL/glx.h**  |             |
| libglvnd-dev      | libGL.so libGLdispatch.so **libGLX.so libOpenGL.so** |                       |             |
| libglvnd-core-dev |                                                      | glvnd/GLdispatchABI.h | libglvnd.pc |
| libglvnd0         | libGLdispatch.so.0                                   |                       |             |
| libgl1            | libGL.so.1                                           |                       |             |
| libglx0           | **libGLX.so.0**                                      |                       |             |
| libglx-mesa0      | libGLX_mesa.so.0                                     |                       |             |
| libopengl0        | **libOpenGL.so.0**                                   |                       |             |

*dependency graph:*

```
           libgl1-mesa-dev
                |
                +----------------+
                |                |
            libglvnd-dev   mesa-common-dev
                |
+---------------+----------------+----------------+---------------------------------+
|               |                |                |                                 |
|        libglvnd-core-dev     libgl1             |                            libopengl0
|                                |                |                                 |
|                                +----------------+                                 |
|                                |                |                                 |
|                                |             libglx0                              |                                 |
|                                |                |                                 |
|                                |                +----------------+                |
|                                |                |                |                |
|                                |                |           libglx-mesa0          |
|                                |                |                                 |
+--------------------------------+----------------+---------------------------------+
                                                  |
                                              libglvnd0
```

**Ubuntu 20.04 (Focal)**

*package contents:*

| package       | libraries          | headers               | pkg-config  |
|---------------|--------------------|-----------------------|-------------|
| libglvnd-dev  | libGLdispatch.so   | glvnd/GLdispatchABI.h | libglvnd.pc |
| libglvnd0     | libGLdispatch.so.0 |                       |             |
| libgl-dev     | libGL.so           | **GL/gl.h**           | gl.pc       |
| libgl1        | libGL.so.1         |                       |             |
| libglx-dev    | **libGLX.so**      | **GL/glx.h**          | glx.pc      |
| libglx0       | **libGLX.so.0**    |                       |             |
| libopengl-dev | **libOpenGL.so**   |                       | opengl.pc   |
| libopengl0    | **libOpenGL.so.0** |                       |             |

*dependency graph:*

```
                  libglvnd-dev
                       |
       + --------------+----------------+----------------+
       |               |                |                |
       |           libgl-dev        libglx-dev      libopengl-dev
       |               |                |                |
       |            libgl1           libglx0         libopengl0
       |               |                |                |
       +---------------+----------------+----------------+
                       |
                   libglvnd0
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13649)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-snopt-packaging please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
IMO, this blocks #13654, though the Focal packages were broken beforehand.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
:lgtm: feature.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.

**Comment by jwnimmer-tri** [comment]
@jamiesnape I think this is ready to merge now (modulo your "do not merge" label).

**Pull request merged**
