### PR TITLE
Add note about slow reads during Bazel builds to build cop playbook

### LINKED ISSUE #6129: "Slow read"s when building with Bazel
For example:
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything/7/console

at time `17:15:27` in the log above.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #6129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6904)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@stonier for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.

**Comment by jamiesnape** [comment]
Pinging @stonier for feature review.

**Comment by stonier** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6904#-:-KtCgitwecmN0CTQnU0b:bnfp4nl)*

**Pull request merged**
