### PR TITLE
Add hash and operator!= for symbolic::Polynomial

### LINKED ISSUE #8159: Implement hash in symbolic::Polynomial
https://github.com/robotlocomotion/drake/pull/8140#issuecomment-368091770

### PR DESCRIPTION
**Pull request by soonho-tri**
Also add python bindings for them.

Close #8159

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8268)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@sherm1 for both-reviews, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-:-L6whRAZYkkZRl3kKEpB:b33qh8q)*

**Comment by sherm1** [comment]
2x :lgtm: pending a few BTWs.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/test/symbolic_test.py, line 661 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x6mg4Z6Yd3bjMZR3U:-L6x6mg4Z6Yd3bjMZR3V:b-bbuozb) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/bindings/pydrake/test/symbolic_test.py#L661)):*
> ```Python
>         self.assertEqual(hash(p1), hash(p2))
>         p1 += 1
>         self.assertNotEqual(p1, p2)
> ```

BTW consider `self.assertNotEqual(hash(p1), hash(p2))` also

---

*[common/symbolic_polynomial.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x8rsyC1ady3jA_GYn:-L6x8rsyC1ady3jA_GYo:b-1jc1ch) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/symbolic_polynomial.h#L147)):*
> ```objc
>   /// Returns a symbolic formula representing the condition where this
>   /// polynomial and @p p are not the same.
>   Formula operator!=(const Polynomial& p) const;
> ```

BTW this takes a const Polynomial reference but the == operator takes its argument by value. Seems like they should have same sig?

---

*[common/symbolic_polynomial.h, line 263 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x9annm4bHvZ3cuXeK:-L6x9annm4bHvZ3cuXeL:b-7301db) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/symbolic_polynomial.h#L263)):*
> ```objc
> // for details.
> template <>
> struct __is_fast_hash<hash<drake::symbolic::Polynomial>> : std::false_type {};
> ```

FYI Yikes! Does this also work in clang or just gcc? 

---

*[common/test/symbolic_polynomial_test.cc, line 777 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x9ul23NREGzYWm0KO:-L6x9ul23NREGzYWm0KP:b9ro7gm) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/test/symbolic_polynomial_test.cc#L777)):*
> ```cpp
> size_t get_std_hash(const T& item) {
>   return std::hash<T>{}(item);
> }
> ```

BTW why do you need this method rather than using std::hash directly? (Please add a comment if it is needed for some reason.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-:-L6xAD9-KC6icIui6ekO:b-wd7573)*

**Comment by jwnimmer-tri** [comment]
*[common/symbolic_polynomial.h, line 263 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x9annm4bHvZ3cuXeK:-L6xBDQQlzQn3-btNUx-:bbua8wj) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/symbolic_polynomial.h#L263)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI Yikes! Does this also work in clang or just gcc? 
</blockquote></details>

The `libstdc++` default is to recompute hashes, instead of storing them.  This line opts-in to storing them.

The `libc++` default is to store hashes, instead of recomputing them, so we don't need to change anything.

The `__is_fash_hash` trait is only defined by `libstdc++` and would be a compile error with `libc++`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8268)*

**Comment by soonho-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/test/symbolic_test.py, line 661 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x6mg4Z6Yd3bjMZR3U:-L760wQvvj1OE8PaUigM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/bindings/pydrake/test/symbolic_test.py#L661)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `self.assertNotEqual(hash(p1), hash(p2))` also
</blockquote></details>

Done.

---

*[common/symbolic_polynomial.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x8rsyC1ady3jA_GYn:-L76034O0TO7_Isq3xIb:b-x5js9y) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/symbolic_polynomial.h#L147)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this takes a const Polynomial reference but the == operator takes its argument by value. Seems like they should have same sig?
</blockquote></details>

`p1 == p2` creates a polynomial `p2 - p1` and checks if this polynomial is equal to zero.  Internally, we reuse the argument polynomial `p2` to construct `p2 - p1`.

---

*[common/test/symbolic_polynomial_test.cc, line 777 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8268#-L6x9ul23NREGzYWm0KO:-L761GyaxP1nBy_m2X26:b6ju51r) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/test/symbolic_polynomial_test.cc#L777)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why do you need this method rather than using std::hash directly? (Please add a comment if it is needed for some reason.)
</blockquote></details>

Done. (removed it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8268)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[common/symbolic_polynomial.h, line 147 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8268#-L6x8rsyC1ady3jA_GYn:-L76Brbr0HHdFY1dtxWu:bkqbux0) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/symbolic_polynomial.h#L147)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`p1 == p2` creates a polynomial `p2 - p1` and checks if this polynomial is equal to zero.  Internally, we reuse the argument polynomial `p2` to construct `p2 - p1`.
</blockquote></details>

BTW consider creating the temp copy internally in op== so that implementation detail doesn't leak through to the API -- cost would be the same. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8268)*

**Comment by soonho-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[common/symbolic_polynomial.h, line 147 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8268#-L6x8rsyC1ady3jA_GYn:-L76FyR28KA_u7ngOwZF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8ad657ea4ef63a9cba6ac9197e1b0aaaf081b4bd/common/symbolic_polynomial.h#L147)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider creating the temp copy internally in op== so that implementation detail doesn't leak through to the API -- cost would be the same. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8268)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8268)*

**Pull request merged**
