### PR TITLE
[vtk] Add missing member field initialization

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #20765 and #20492.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20853)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-undefined-behavior-sanitizer please

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

For want of a nail....

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20853#-:-NpVRNiW1Ovt7ARjESHn:b-r8wniq)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20853#-:-NpVRXf25TYc4VP5LM31:b-safpmt)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Lol.  That's an _extremely_ appropriate analogy.

**Comment by SeanCurtis-TRI** [comment]
I encountered something similar vis a vis shadows. I made my symptom go away with a simple initialization. (Admittedly, the full fix was initialization plus something else...but, still, uninitialized members....)

**Pull request merged**
