### PR TITLE
Add unique_ptr_ref for API cleanup

### PR DESCRIPTION
**Pull request by sherm1**
This PR adds a new smart pointer, `unique_ptr_ref` that is identical to `unique_ptr` except that it remembers the pointer after ownership has been moved elsewhere.

This is from a discussion with @amcastro-tri and @david-german-tri about how to make a clean `shared-ptr`-free API that allows a user to create elements (like bodies and joints), hand off ownership to a larger object (like a rigid body tree), yet retain the ability to access the concrete elements. This was the best we could come up with that doesn't require a PIMPL design pattern. This is experimental and may take some playing around to see if we like it in practice. I converted some existing tests and code to use it.

Here is an API example using this smart pointer. First, assume the library defines these:
```c++
  class PinJoint    : public Joint { public: double GetAngle(); };
  class SliderJoint : public Joint { public: double GetDisplacement(); };
  class Tree {
   public:  void AddJoint(std::unique_ptr<Joint> joint);
   private: std::vector<std::unique_ptr<Joint>> joints_;
  };
```
Then here is what user code would look like:
```c++
  Tree tree;

  // Create some concrete Joint elements.
  auto pin    = drake::make_unique_ref<PinJoint>(pin_axis);
  auto slider = drake::make_unique_ref<SlidingJoint>(slider_axis);

  // (At this point pin and slider own the managed objects; early termination
  // or failure to add these to a Tree would clean up with no leaks.)

  // Transfer ownership to tree; pin and slider will be deleted when tree is.
  tree.AddJoint(pin.move());
  tree.AddJoint(slider.move());

  // Can still reference concrete class methods (as long as tree exists).
  pin.GetAngle();
  slider.GetDisplacement();
```

Reviews please (others welcome also):
Feature: @amcastro-tri 
Platform: @jwnimmer-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2360)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri platform.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> #### Add unique\_ptr\_ref for API cleanup
> 
> This PR adds a new smart pointer, `unique_ptr_ref` that is identical to `unique_ptr` except that it remembers the pointer after ownership has been moved elsewhere.
> 
> 
> 
> This is from a discussion with @amcastro-tri and @david-german-tri about how to make a clean `shared-ptr`-free API that allows a user to create elements (like bodies and joints), hand off ownership to a larger object (like a rigid body tree), yet retain the ability to access the concrete elements. This was the best we could come up with that doesn't require a PIMPL design pattern. This is experimental and may take some playing around to see if we like it in practice. I converted some existing tests and code to use it.
> 
> 
> 
> Here is an API example using this smart pointer. First, assume the library defines these:
> 
> ```c++
> 
>   class PinJoint    : public Joint { public: double GetAngle(); };
> 
>   class SliderJoint : public Joint { public: double GetDisplacement(); };
> 
>   class Tree {
> 
>    public:  void AddJoint(std::unique_ptr<Joint> joint);
> 
>    private: std::vector<std::unique_ptr<Joint>> joints_;
> 
>   };
> 
> ```
> 
> Then here is what user code would look like:
> 
> ```c++
> 
>   Tree tree;
> 
> 
> 
>   // Create some concrete Joint elements.
> 
>   auto pin    = drake::make_unique_ref<PinJoint>(pin_axis);
> 
>   auto slider = drake::make_unique_ref<SlidingJoint>(slider_axis);
> 
> 
> 
>   // (At this point pin and slider own the managed objects; early termination
> 
>   // or failure to add these to a Tree would clean up with no leaks.)
> 
> 
> 
>   // Transfer ownership to tree; pin and slider will be deleted when tree is.
> 
>   tree.AddJoint(pin.move());
> 
>   tree.AddJoint(slider.move());
> 
> 
> 
>   // Can still reference concrete class methods (as long as tree exists).
> 
>   pin.GetAngle();
> 
>   slider.GetDisplacement();
> 
> ```
> 
> 
> 
> Reviews please (others welcome also):
> 
> Feature: @amcastro-tri 
> 
> Platform: @jwnimmer-tri
> 
> 
> </details>


---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHtG_6Rt5TppE-5BbgH:1088834024)*

**Comment by jwnimmer-tri** [comment]
I am generally unconvinced by this idea.  Once all of the other (very good) refactorings to the fooSDF.cpp / fooURDF.cpp files are set aside, this really just comes down to folding two lines into one (declaring two separate variables, vs this one).  To me, that doesn't trade off well vs the additional mental overhead of learning the semantics of a new pointer type.

FWIW, even I later become convinced that this is a good idea, it can't be named `make_unique_ref`; it'd have to be `MakeUniqueRef` or similar.

**Comment by david-german-tri** [comment]
@sherm1 I guess I didn't express my point of view clearly in that conversation - I apologize!  While I think retaining a raw pointer is the right way to reference an object after transferring ownership of it, I don't think a stateful smart pointer is the best way to represent that transaction.

When I'm reading your code example and get to `pin.GetAngle()`, I have to review the entire history of `pin` to determine whether it's owned or not.  In contrast, if it's up to the user code to maintain its own references, I only have to look at the declaration site.  If `pin` is a `unique_ptr`, I know it's owned; if it's a raw `*`, I know it isn't.

**Comment by amcastro-tri** [comment]
@david-german-tri: are you then saying that having this smart pointer is a bad idea?

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> @sherm1 I guess I didn't express my point of view clearly in that conversation - I apologize!  While I think retaining a raw pointer is the right way to reference an object after transferring ownership of it, I don't think a stateful smart pointer is the best way to represent that transaction.
> 
> 
> 
> When I'm reading your code example and get to `pin.GetAngle()`, I have to review the entire history of `pin` to determine whether it's owned or not.  In contrast, if it's up to the user code to maintain its own references, I only have to look at the declaration site.  If `pin` is a `unique_ptr`, I know it's owned; if it's a raw `*`, I know it isn't.</details>


---

Reviewed 2 of 9 files at r1.
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/test/unique_ptr_ref_test.cc, line 61 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtwBssWF9QyzIljOq4:-KHtwBssWF9QyzIljOq5:854906347) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L61)):*
> ```cpp
>   auto sj = make_unique_ref<SlidingJoint>();
> 
>   // Verify that we initially have ownership.
> ```

"Verify"-->"Verifies".
The [google style guide](https://google.github.io/styleguide/cppguide.html#Function_Comments) requires we use descriptive rather than imperative comments.

---

*[drake/common/test/unique_ptr_ref_test.cc, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtwV026uYpWUZslILL:-KHtwV026uYpWUZslILM:-807908232) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L65)):*
> ```cpp
>   EXPECT_TRUE(sj.is_owner());
> 
>   // Transfer ownership to compound class object, but retain references.
> ```

"Transfer"-->"Transfers"

---

*[drake/common/test/unique_ptr_ref_test.cc, line 78 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtw_sotB0J28iYUqCx:-KHtw_sotB0J28iYUqCy:1050071328) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L78)):*
> ```cpp
>   EXPECT_EQ(sj->get_joint_num(), 1);
> 
>   // Check that the original object got moved into Mechanism.
> ```

"Check" --> "Checks"

---

*[drake/common/test/unique_ptr_ref_test.cc, line 262 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtuZAysyqZ4P2vqUyE:-KHtuZAysyqZ4P2vqUyF:-169271765) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L262)):*
> ```cpp
> }
> 
> GTEST_TEST(UniquePtrRefTest, Hash) {
> ```

Nice! I am glad you included this test here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHtx9i7vLc_xUCHfYmr:1296817249)*

**Comment by david-german-tri** [comment]
@amcastro-tri: yes (or at least, I am not convinced it's a good one)

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> @david-german-tri: are you then saying that having this smart pointer is a bad idea?</details>


---

Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHtxo9a6eEailwWgYaI:-1655791974)*

**Comment by sherm1** [comment]
(I thought this would be controversial, but I didn't think we could have a substantive conversation about it without it existing. So I sacrificed a Sunday on it (my wife had to work anyway) -- no worries if we don't end up using it.)

> I have to review the entire history of pin to determine whether it's owned or not 

The point of this pointer is that there is no need to make that determination. Instead of the user having to manage ownership with two variables tracking each object (easy for us C++ hackers to do, not so easy for controls engineers), ownership is dealt with safely with no help needed from the amateur. This is exactly what is achieved using a PIMPL design pattern, but doing it this way is a lot less work.

I think there is a lot of value in being able to make simple APIs where each line has end user meaning rather than being about C++ quirks. I believe that's what the original authors were trying to achieve with their use of std::shared_ptr. That part was nice (IMO), while the use of shared_ptr was horrifying.



---

Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHuY6cktaOJo_EOSCBO:-759249199)*

**Comment by jwnimmer-tri** [comment]
TBH, I disbelieve both @sherm1's and @david-german-tri's points about the lifetimes being hard to understand.  I think its super clear in both the pre-existing code, and the new code.

(1) In the old code, nobody every uses `body_owned` except for the `std::move` to transfer ownership, so the lifecycle of body_owned is super clear.  And the lifecycle of `body` is just as clear -- its valid for the entire scope.

(2) In the new code, there is only one variable, `body`, whose accessible lifetime is the entire scope, so is also plenty clear.  You have to be careful to call `.move()` only once on it to give it away, but that's just as true in the old code.

My hesitation here is not about lifecycle confusion, it's that the payoff isn't actually demonstrated in the patches.  I don't think the `...SDF.cpp` changes are enough to tip the complexity balance here.  The "joint" example in the overview here may be, but it is just inline code in the PR, not an actual improvement in its real context.

@sherm1 Is there a more compelling small patch that you can add into the PR, for a call site where the benefit of this abstraction is even stronger?

My tentative hypothesis is that all of the problems that this is trying to solve can instead be solved by fixing the RigidBodyFoo designs to be less finicky in their APIs, which would benefit not only this facet of their design, but several other facets as well.

**Comment by sherm1** [comment]
> I don't think the ...SDF.cpp changes are enough to tip the complexity balance here.

That's for sure -- I didn't actually use `unique_ptr_ref` there or in ...URDF.cpp! I set out to do that but it turned out those files were just misusing raw pointers and were fixable using only `unique_ptr`. Then I forgot to remove the new header inclusion. :blush: Will fix.

> Is there a more compelling small patch that you can add into the PR, for a call site where the benefit of this abstraction is even stronger?

Possibly. I think the benefit (if any!) will only be apparent in user-facing "main" code -- internal code like SDF/URDF.cpp only has to be gotten right once and regular humans won't have to see it. I'll look around.

> My tentative hypothesis is that all of the problems that this is trying to solve can instead be solved by fixing the RigidBodyFoo designs to be less finicky in their APIs

Agreed - easier said than done, though. That is how we got started on this. If those used a PIMPL design pattern ownership issues could be stuffed under the covers the way Java objects would do it. That is what I did in Simbody and the API came out very nice and got used successfully (e.g., leak- and coredump-free) by lots of not-too-competent programmers. But ... applying PIMPL to big hierarchies of polymorphic objects like Joints is really a *lot* of work. We had special CRTP base classes to help, and it was still a *lot* of work, and most of our programmers didn't really grasp the concept. Every object gets a "handle" and an "implementation" subobject, with parallel hierarchies. The result is beautiful for users but did I mention it was a *lot* of work? This tweaked unique_ptr comes very close to producing the same API without all the hassle. If I'd had it when I was designing the Simbody API I could have saved ... a *lot* of work :smile:!

**Comment by jwnimmer-tri** [comment]
> That's for sure -- I didn't actually use unique_ptr_ref there or in ...URDF.cpp ...

But the PR _did_ use `make_unique_ref` with `auto`.

**Comment by sherm1** [comment]
> You have to be careful to call .move() only once on it to give it away

Actually `.move()` knows whether it was already given away. If it was, it returns a null `unique_ptr` rvalue. It could instead throw an exception -- my thought was that a null return would be dramatic enough.

**Comment by sherm1** [comment]
> But the PR did use make_unique_ref with auto.

You're right -- I forgot I had used it once in each file. But I agree it didn't improve anything in RBTSdf/Urdf.cpp.

**Comment by sherm1** [comment]
> perhaps the function can still be snake_case; the classname, however, definitely can't be snake_case

I disagree. See Google Style Guide [here](https://google.github.io/styleguide/cppguide.html#Exceptions_to_Naming_Rules): 
> If you are naming something that is analogous to an existing C or C++ entity then you can follow the existing naming convention scheme. Example:
```
sparse_hash_map
    STL-like entity; follows STL naming conventions
```

I named `unique_ptr_ref` and `make_unique_ref` specifically for this reason. The idea is to make use of these classes obvious to anyone who knows the standard versions -- the differences are very small.

**Comment by sherm1** [comment]
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/test/unique_ptr_ref_test.cc, line 61 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtwBssWF9QyzIljOq4:-KHwufnGQIwTl0Cu0zne:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L61)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "Verify"-->"Verifies".
> The [google style guide](https://google.github.io/styleguide/cppguide.html#Function_Comments) requires we use descriptive rather than imperative comments.</details>
Done.

---

*[drake/common/test/unique_ptr_ref_test.cc, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtwV026uYpWUZslILL:-KHwugDzX7ieTzhEhIWM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "Transfer"-->"Transfers"</details>
Done.

---

*[drake/common/test/unique_ptr_ref_test.cc, line 78 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHtw_sotB0J28iYUqCx:-KHwuhT3cWTLoiHOQX0V:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c557bf7f14aeabd847d398d7b95b574add7ed816/drake/common/test/unique_ptr_ref_test.cc#L78)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "Check" --> "Checks"</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360)*

**Comment by sherm1** [comment]
> Is there a more compelling small patch that you can add into the PR, for a call site where the benefit of this abstraction is even stronger?

Partial response: check out Drake's Quadrotor example [starting here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Quadrotor/runDynamics.cpp#L64). This is the same kind of API in a different context. There are 11 calls to `make_shared`, this time for Systems and Sensors rather than Joints. I believe only the first of those is justified (for LCM). The rest of them are there to allow for retained access to the concrete objects (although nothing much gets done with those in this small example). IMO the alternative of adding 10 additional pointer variables is duplicative, obscure, and generally unappealing.

I can't fix that in this PR because it requires separate changes to `RigidBodySystem::addSensor()` and `cascade` to use `std::unique_ptr` rather than `std::shared_ptr`, and likely downstream changes to match (see Alejandro's #2207 for difficulty). But with those changes and replacing `make_shared` with `make_unique_ref` the code would look identical but would involve only unique ownership -- the sensors and subsystems would be owned by their containing systems.

There are several more examples like this in our small collection of Drake C++ examples, with unnecessary shared_ptrs everywhere. They are like the GPL license -- once they get in they infect all the downstream code. Regardless of the API we end up with, I think we need to get rid of these shared_ptrs for code health. So far I think `make_unique_ref` is the tidiest way to do that.

If we switch the internals to `unique_ptr` from `shared_ptr`, both the two-pointer method and the `unique_ptr_ref` method will work; the latter is not needed internally. I would like to see this PR merged to encourage subsequent shared->unique replacement and allow playing with the API in examples until we know what we want.

**Comment by sherm1** [comment]
Revision: the quadrotor's noise model really is shared! Is that good?

**Comment by amcastro-tri** [comment]
@sherm1: you mean because of the calls to `setNoiseModel` from accelerometer, magnetometer and gyroscope?. IMO, those should just take raw pointers and hold onto one. They are just non-owned references.

**Comment by amcastro-tri** [comment]
The Quadrotor example demonstrates our current API issues very well. #2207 was a first step towards fixing this API in the RBT. However we still must make a similar API change for systems and sensors. 

We cannot, and we should not, keep using the hack with the `owned_object`/`object` pair as we did in RBTUrdf/RBTSdf. That might be ok for expert programmers but definitely we cannot expect the users to do something like that. Even when we rewrote all of our examples (like the Quadrotor) to use this `owned_object`/`object` pair I am sure users just won't stick to this style. 

One of my concerns however with  `unique_ptr_ref` that I expressed to @sherm1 yesterday is that our design might by necessity switch to some sort of PIMPL. I am talking of RBT (and the family) and system, given they are required to have an interface that supports things like doubles, auto-diffs and polynomials (and maybe others) needing most likely to internally switch to the proper implementation. 

If we are, due to this specifications constraint, forced to use a PIMP design, then we won't need to worry about ownership anymore and smart pointers won't be needed on the user's side. 
Also, don't forget about #1854!, where one of the solutions proposed was a PIMPL design.

**Comment by jwnimmer-tri** [comment]
I am very confused why _pimpl_ keeps coming up in this discussion.  I get the "add_item gives you an opaque handle, which you use from then on reference the added object" design pattern that sherm seems to be referencing from simbody, but that isn't _pimpl_.  The _pimpl_ is "moving member fields into a nested struct" for implementation hiding, and I can't see how that has do to with anything in this proposal, or ownership transfer in general.

@amcastro-tri And as I said upthread, I don't think that having two local variables (foo, foo_owned) for every, e.g., sensor is a great resolution.  I've said that fixing the APIs of RigidBody to make all-everything simpler is a better answer.  Having to create a Sensor, with an immediate back-reference so the System in its constructor, and then transfer the shared-Sensor ownership to the System with a later, separate add call, is a disaster waiting to happen no matter what pointer abstraction is chosen.  Why should the user even be allowed to create Sensors from a System and never transfer ownership (forgetting to call add)?  If we close that error-window, we also end up solving the complicated-ownership problem by side-effect.

I can write up a gist of the new quadcopter API's I'd suggest, if that would help.

**Comment by david-german-tri** [comment]
This thread has become impossible to converge.  Can we have a meeting instead?  I'll grab some time on everyone's calendar.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am very confused why _pimpl_ keeps coming up in this discussion.  I get the "add_item gives you an opaque handle, which you use from then on reference the added object" design pattern that sherm seems to be referencing from simbody, but that isn't _pimpl_.  The _pimpl_ is "moving member fields into a nested struct" for implementation hiding, and I can't see how that has do to with anything in this proposal, or ownership transfer in general.
> 
> 
> 
> @amcastro-tri And as I said upthread, I don't think that having two local variables (foo, foo_owned) for every, e.g., sensor is a great resolution.  I've said that fixing the APIs of RigidBody to make all-everything simpler is a better answer.  Having to create a Sensor, with an immediate back-reference so the System in its constructor, and then transfer the shared-Sensor ownership to the System with a later, separate add call, is a disaster waiting to happen no matter what pointer abstraction is chosen.  Why should the user even be allowed to create Sensors from a System and never transfer ownership (forgetting to call add)?  If we close that error-window, we also end up solving the complicated-ownership problem by side-effect.
> 
> 
> 
> I can write up a gist of the new quadcopter API's I'd suggest, if that would help.
> 
> </details>


---

Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHzBfGoaEBUbdvgf07q:-1348353731)*

**Comment by liangfok** [comment]
I don't mean to add more fuel to the fire, but: I like this idea of a `unique_ptr_ref` since it appears to supersede the existing `unique_ptr` by enforcing single ownership and is yet more more flexible in terms of access after ownership transfer. Can we try to push it to the next version of the C++ standard library? What is the process for doing that?

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This thread has become impossible to converge.  Can we have a meeting instead?  I'll grab some time on everyone's calendar.
> 
> </details>


---

Reviewed 4 of 9 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/common/unique_ptr_ref.h, line 90 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-KHzLPR0jLFXS34grF8n:-KHzLPR0jLFXS34grF8o:-1318408951) ([raw file](https://github.com/robotlocomotion/drake/blob/8268f6c4624ceb18964a8b1fbb2d2ebd02f89e5b/drake/common/unique_ptr_ref.h#L90)):*
> ```objc
> @see make_unique_ref() **/
> template <class T>
> class unique_ptr_ref {
> ```

Is this class thread safe? Should it be?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHz4Fu99U_7xlWyijMj:-773009152)*

**Comment by amcastro-tri** [comment]
I agree with you @liangfok, I think this design will force us cleanup the code even further (removing all those overused shared_ptr's and using the simple raw pointers when only a non-owning reference is needed). I don't think my concern with PIMPL's and other possible future designs collides with this idea (sorry then for bringing it up here). Actually, if we do need to migrate to a design like that one having a clean-shared_ptr-free code will definitely help the transition. Right now having all of these shared_ptr's block us from making any progress towards a clean and safe API for the user (and for us!).

**Comment by david-german-tri** [comment]
@liangfok, I've added you to the scheduled meeting.  In the meantime, I implore everyone to please consider not adding to this thread.

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I agree with you @liangfok, I think this design will force us cleanup the code even further (removing all those overused shared_ptr's and using the simple raw pointers when only a non-owning reference is needed). I don't think my concern with PIMPL's and other possible future designs collides with this idea (sorry then for bringing it up here). Actually, if we do need to migrate to a design like that one having a clean-shared_ptr-free code will definitely help the transition. Right now having all of these shared_ptr's block us from making any progress towards a clean and safe API for the user (and for us!). </details>


---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2360#-:-KHzPEzyzPCSFdMvssQb:543454209)*

**Comment by sherm1** [comment]
Per f2f discussion, I will close this PR while we explore a different approach proposed by @jwnimmer-tri. A sketch: each concrete object must provide a factory method that constructs the object and adds it to the parent container, returning a reference to the contained object. Something like ...

```c++
Tree tree;

PinJoint& pin = PinJoint::CreateAndAdd(tree, /*constructor arguments go here*/);
// do stuff with tree
std::cout << pin.getAngle() << std::endl; // access concrete class method
```
Minor controversy over whether the return type should be a reference or a pointer remains. Although I prefer references I might be persuaded by whichever one looks nicer with `auto`!

**Pull request closed without merging**
