### PR TITLE
Provides proper unit test coverage of the DirectTrajectoryOptimization class

### PR DESCRIPTION
**Pull request by RussTedrake**
also
- separates out direct collocation tests to their own file
- includes some additional API cleanups
- zaps the pendulum trajectory optimization test, which was only there because we didn't have proper test coverage on the actual trajectory optimization code.  the optimization problem still exists in the pendulum swing-up example.  

follows #6850 (that commit is included here).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6861)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review please

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-:-Krkb8d1C0asWODCLfl_:b-85dizs)*

**Comment by RussTedrake** [comment]
#6850 landed and I've curated the commits.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-:-Krl5x4dHi_Sqlz_M6VT:b8823go)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor request for an additional test case (positive case for initial trajectories). Thanks!

---

Reviewed 6 of 18 files at r1, 1 of 3 files at r2.
Review status: 7 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/pendulum/pendulum_run_swing_up.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrksuQ3hrnk5KyMCMpx:-KrksuQ4zDthSEy_MHV8:bwwu6l8) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/examples/pendulum/pendulum_run_swing_up.cc#L70)):*
> ```cpp
>       kTrajectoryTimeUpperBound);
> 
>   auto u = dircol.input();
> ```

BTW The type of `u` may not be obvious in this call site. If the type is not too cumbersome, could it be included here?

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkthoQNBCS7zk1CUMJ:-KrkthoQNBCS7zk1CUMK:b-qv5zex) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L20)):*
> ```cpp
> namespace {
> 
> // qddot = u.
> ```

BTW Could this comment be expanded to a full sentence? "Implements a double integrator, qddot = u"?

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkxrC7V3FQyEcONt3S:-KrkxrC8LUa7wEGgoVOd:b-ia54s3) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L55)):*
> ```cpp
> };
> 
> // Tests the double integrator minimum-time problem known solution.
> ```

BTW nit Grammar, "with a known solution".

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkuKzX-8R2zrNIX9Br:-KrkuKzX-8R2zrNIX9Bs:b-693czx) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L115)):*
> ```cpp
> }
> 
> /// A simple example where the plant has no inputs.
> ```

BTW Should be an internal comment, `//`

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkuhUNT9dVL_a1KQsS:-KrkuhUNT9dVL_a1KQsT:b-90fyqx) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L60)):*
> ```cpp
> 
>   EXPECT_EQ(prog.num_vars(), 6);
>   const auto times = prog.GetSampleTimes();
> ```

BTW nit Usage of `auto` here and in other places may obscure the type.

(This is general convention that I've seen. Should we see if we should loosen this rule, or keep it strict?)

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkwM1GffSq0Xj9I14L:-KrkwM1GffSq0Xj9I14M:b-om3g37) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L219)):*
> ```cpp
>   // u(2) = h(0)+h(1).
>   EXPECT_NEAR(prog.GetSolution(prog.input(2).coeff(0)),
>               prog.GetSolution(prog.h_vars()).array().sum(), 1e-6);
> ```

BTW For `VectorX<>`, `X.sum()` and `X.array().sum()` should be equivalent.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 268 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkwdG07Y4VWhKyCdKu:-KrkwdG07Y4VWhKyCdKv:bav6e4l) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L268)):*
> ```cpp
>   EXPECT_EQ(prog.GetSampleTimes(), Eigen::Vector3d(0.0, 1.5, 3.0));
> 
>   // Throws if trajectories don't match.
> ```

Is there a positive test which succeeds when `input_traj.t == state_traj.t`?
Perhaps just checking `prog.SetInitialTrajectory(traj1, traj1)`?

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkxEz0yZfhykBfAF4J:-KrkxEz13AW6MX2eBuQ-:b-5pqomg) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L293)):*
> ```cpp
> 
>   EXPECT_TRUE(CompareMatrices(prog.GetSampleTimes(),
>                               Eigen::Vector2d(0.0, kFixedTimeStep), 0.0));
> ```

BTW minor nit Default `tolerance` is `0.0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-:-KrlHQYu5ofjeaOAg19L:b-cun6i1)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 18 files at r1, 2 of 3 files at r2.
Review status: 10 of 18 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861)*

**Comment by RussTedrake** [comment]
Review status: 10 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/pendulum/pendulum_run_swing_up.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrksuQ3hrnk5KyMCMpx:-KrlSA4NPuCEyjwikAzb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/examples/pendulum/pendulum_run_swing_up.cc#L70)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW The type of `u` may not be obvious in this call site. If the type is not too cumbersome, could it be included here?
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkthoQNBCS7zk1CUMJ:-KrlSegFXLL9qEZk-fzz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could this comment be expanded to a full sentence? "Implements a double integrator, qddot = u"?
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkxrC7V3FQyEcONt3S:-KrlSmHXu0n9tf7hsWgw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L55)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW nit Grammar, "with a known solution".
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkuKzX-8R2zrNIX9Br:-KrlSosLapC44zYhWIWW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L115)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should be an internal comment, `//`
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkuhUNT9dVL_a1KQsS:-KrlTSKjJR1LkussNWzX:b-bhzuku) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L60)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW nit Usage of `auto` here and in other places may obscure the type.

(This is general convention that I've seen. Should we see if we should loosen this rule, or keep it strict?)
</blockquote></details>

Done.  Cleaned up the ones that were not clear.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkwM1GffSq0Xj9I14L:-KrlU4C1UNeLTzNaCU1-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L219)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW For `VectorX<>`, `X.sum()` and `X.array().sum()` should be equivalent.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 268 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkwdG07Y4VWhKyCdKu:-KrlXLreYLIkhxowlzrs:bkz5ckv) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L268)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is there a positive test which succeeds when `input_traj.t == state_traj.t`?
Perhaps just checking `prog.SetInitialTrajectory(traj1, traj1)`?
</blockquote></details>

Done.  Good catch.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkxEz0yZfhykBfAF4J:-KrlVTFyTBnssKiK_t-u:b-hb6sjz) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L293)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Default `tolerance` is `0.0`.
</blockquote></details>

I still think it's cleaner to write it explicitly.  No?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review, please.

---

Review status: 8 of 18 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-:-Krlc4AtmHgqvI8x2x5M:bxwr5c8)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 7 of 18 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkwM1GffSq0Xj9I14L:-KrlcxABvhQtORpnO8EH:b-iuyzpg) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L219)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW This change may have not been incorporated in the most recent push (but it's minor anywho).

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkxEz0yZfhykBfAF4J:-KrldDTgN-EUYiifUNSC:b-bk5ipd) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L293)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I still think it's cleaner to write it explicitly.  No?
</blockquote></details>

Works for me!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrkwM1GffSq0Xj9I14L:-KrleG4fo4HPBUpS2OB3:b-o83ldp) ([raw file](https://github.com/robotlocomotion/drake/blob/c0145c28ad2c441e1fbff2a78ec243243d230354/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L219)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This change may have not been incorporated in the most recent push (but it's minor anywho).
</blockquote></details>

hah.  there were two .array.sums() in the code.  now they're both fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861)*

**Comment by soonho-tri** [comment]
:lgtm: (in addition to a note to @ericcousineau-tri )

---

Reviewed 13 of 18 files at r1, 2 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc, line 112 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-KrlyuGE2CXoqEJfyCGR:-KrlyuGE2CXoqEJfyCGS:b3ens98) ([raw file](https://github.com/robotlocomotion/drake/blob/ef7aedf28f9b4d6bc8ddba950be90e1536e36ebd/drake/systems/trajectory_optimization/test/trajectory_optimization_test.cc#L112)):*
> ```cpp
>                std::runtime_error);
> 
>   // TODO(soonho): These should THROW, but currently do not.
> ```

BTW, @ericcousineau-tri , I believe that this is related to the line https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/mathematical_program.cc#L373. Could you take care of it later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6861#-:-Krm-4lTEnEIILzkVUKe:b-n5jxa5)*

**Pull request merged**
