### PR TITLE
MBT Geometric Jacobian for frame spatial velocity

### PR DESCRIPTION
**Pull request by amcastro-tri**
Computation of the geometric Jacobian for the spatial velocity of a given frame.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8026)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@siyuanfeng-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-:-L5GLJvfI0XYVstXzRLM:bakb6i6)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.cc, line 700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5HP1qPu0Difxx_ykNG:-L5HP1qPu0Difxx_ykNH:b2ni5vy) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.cc#L700)):*
> ```cpp
>     const systems::Context<T>& context,
>     const Frame<T>& frame_B, const Eigen::Ref<const Vector3<T>>& p_BoFo_B,
>     EigenPtr<MatrixX<T>> Jg_WF) const {
> ```

jv?

---

*[multibody/multibody_tree/multibody_tree.h, line 988 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5JGYEWRPCLLC_HBGyP:-L5JGYEWRPCLLC_HBGyQ:b2ni5vy) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.h#L988)):*
> ```objc
> 
>   /// @param[out] Jg_WF
>   ///   The geometric Jacobian `Jv_WFi(q)`, function of the generalized
> ```

jv?

---

*[multibody/multibody_tree/multibody_tree.h, line 989 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5JHRJ7OfX0lBIeupmO:-L5JHRJ7OfX0lBIeupmP:bx6nqq9) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.h#L989)):*
> ```objc
>   /// @param[out] Jg_WF
>   ///   The geometric Jacobian `Jv_WFi(q)`, function of the generalized
>   ///   positions q only. This Jacobian relates the spatial velocity `V_WFi` of
> ```

"the input set" or "Fi" is not well defined here. why not just call it F? 

---

*[multibody/multibody_tree/multibody_tree.h, line 1008 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5JDjUCNHD5LOYJqorP:-L5JDjUCNHD5LOYJqorQ:b2ni5vy) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.h#L1008)):*
> ```objc
>       const systems::Context<T>& context,
>       const Frame<T>& frame_B, const Eigen::Ref<const Vector3<T>>& p_BoFo_B,
>       EigenPtr<MatrixX<T>> Jg_WF) const;
> ```

jv?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026)*

**Comment by siyuanfeng-tri** [comment]
minor comments, mostly :lgtm: 
it it possible to have a dummy test just for EvalBodySpatialVelocityInWorld against paul's math?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-:-L5JLX9CSjKjonf0tfNO:b-my4clk)*

**Comment by amcastro-tri** [comment]
Done. I had to make some minro fixes to the benchmark itself (mostly build stuff but there was an actual bug, the missing `makeAffine()` call)

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.cc, line 700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5HP1qPu0Difxx_ykNG:-L5Jy20e9tq425kfLIGh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.cc#L700)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

jv?
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_tree.h, line 988 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5JGYEWRPCLLC_HBGyP:-L5JxtrSJLwdVCNn9Rf-:b-envp9o) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.h#L988)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

jv?
</blockquote></details>

sorry, I completely forgot to document this properly. PTAL.

---

*[multibody/multibody_tree/multibody_tree.h, line 989 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5JHRJ7OfX0lBIeupmO:-L5JxxfL7tS3bDULL7kF:byr4ffv) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.h#L989)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

"the input set" or "Fi" is not well defined here. why not just call it F? 
</blockquote></details>

see above

---

*[multibody/multibody_tree/multibody_tree.h, line 1008 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5JDjUCNHD5LOYJqorP:-L5Jy0W8KRGDH5z-ZtqA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d43967dc9ae71b601f6dcfa1bdbd0cb99276117a/multibody/multibody_tree/multibody_tree.h#L1008)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

jv?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-:-L5K5LoSnASWvmb-2GOo:b58nzhp)*

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for platform review please.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-:-L5K6NHECJrpFmyhdEb2:b-tnzbcp)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With some minor BTW cosmetic issues (and some ignorable FYI suggesestions/thoughts)

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5L_m0zUBoEwu67XcZy:-L5L_m1-NCrwAktU6nzi:bbv15mh) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/multibody_tree.cc#L21)):*
> ```cpp
> using internal::BodyNodeWelded;
> 
> #define MBT_THROW_IF_NOT_FINALIZED ThrowIfNotFinalized(__FUNCTION__);
> ```

FYI This looks familiar.  :)

---

*[multibody/multibody_tree/multibody_tree.cc, line 709 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5Lc8_mGrsXfAXH-jct:-L5Lc8_mGrsXfAXH-jcu:b-m46lx8) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/multibody_tree.cc#L709)):*
> ```cpp
> 
>   // Compute kinematic path from body B to the world:
>   std::vector<BodyNodeIndex> path_to_world;
> ```

FYI Any reason this includes world? If it didn't, then subsequent operations that *skip* world, wouldn't have to skip it.  For example, the for loop below would be:

```C++
for (BodyNodeIndex body_node_index : path_to_world) {
```

---

*[multibody/multibody_tree/multibody_tree.h, line 904 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LdfbZ2IiR0_68MNyV:-L5LdfbZ2IiR0_68MNyW:b-s1txwj) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/multibody_tree.h#L904)):*
> ```objc
>   /// @param[in] body_B
>   ///   The body B for which the pose is requested.
>   /// @returns X_WB
> ```

FYI swap @returns with @retval?  Same below.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 166 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LedcpHE8QxzxI8mDO:-L5LedcqBtM9iVePy3_R:b-anyjjo) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L166)):*
> ```cpp
>   // Gets an arm state to an arbitrary configuration in which joint angles and
>   // rates are non-zero.
>   void GetArbitraryNonZeroConfiguration(
> ```

BTW This declaration fits on a single line.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 173 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5Les5VZrL5rBtRT_Tk:-L5Les5WnAnhw1_4YE4t:b-7p3p7b) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L173)):*
> ```cpp
> 
>     // A set of values for the joint's angles chosen mainly to avoid in-plane
>     // motions.
> ```

FYI I don't know that naming these has particular value. I.e., if you simply did:

```C++
*q << q60, q30, q60, q30, q60, q30, q60;`
```

it doesn't seem to have lost much information -- after all, in this context A-G aren't particularly meaningful. Certainly gives no insight into interpreting the polar values.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 248 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5Lhw8zHrav5q9bCrUZ:-L5Lhw8zHrav5q9bCrU_:bdx4325) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L248)):*
> ```cpp
> 
>  protected:
>   // Acceleration of gravity:
> ```

FYI Seeing a positive value for "gravity" was surprising. I would've thought -9.81.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 298 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LiAssq2zXWuD-6zBn:-L5LiAssq2zXWuD-6zBo:bbogqex) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L298)):*
> ```cpp
>   // motions.
>   VectorX<double> q, v;
>   GetArbitraryNonZeroConfiguration(&q, &v);;
> ```

BTW Extra ";"

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LiLCGdR9PcnMPXDOw:-L5LiLCGdR9PcnMPXDOx:bip8xbd) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L465)):*
> ```cpp
>   const double kTolerance = 10 * std::numeric_limits<double>::epsilon();
> 
>   // A set of values for the joint's angles chosen mainly to avoid in-plane
> ```

BTW s/joint's/joints'

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 478 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LiUKIhIoaEFQ5iuAW:-L5LiUKIhIoaEFQ5iuAX:b-rzj9fr) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L478)):*
> ```cpp
>   }
> 
>   // Spatial velocity of the end effector.
> ```

BTW The next comment includes "in the world frame", this doesn't.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 516 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LifpV4jo8o-WO9zwA:-L5LifpV4jo8o-WO9zwB:bip8xbd) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L516)):*
> ```cpp
>   const double kTolerance = 10 * std::numeric_limits<double>::epsilon();
> 
>   // A set of values for the joint's angles chosen mainly to avoid in-plane
> ```

BTW s/joint's/joints'

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 538 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5Lio0xmxD_fYbCzlWt:-L5Lio0xmxD_fYbCzlWu:bxbsq8i) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L538)):*
> ```cpp
> 
>   // Position of a frame F measured and expressed in frame E.
>   const Vector3d p_EoFo_E = Vector3d(0.2, -0.1, 0.5);  // p_EoFo for short.
> ```

BTW I'm a bit confused by this abbreviation. It only gets used once in one comment. All of this to not type "_E"?

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 549 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5LiyjMSufMnEIZjMFF:-L5LiyjMSufMnEIZjMFG:by0d4ml) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L549)):*
> ```cpp
> 
>   MatrixX<double> Jv_WF(6, model_->get_num_velocities());
>   // Compute the Jacobina Jv_WF for that relate the generalized velocities with
> ```

BTW s/Jacobina/Jacobian

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-:-L5LjLeZJUNKQlUGzGET:b-dn00lv)*

**Comment by SeanCurtis-TRI** [comment]
By the way -- this is beautiful code.

---

Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-:-L5LjdwlsGGDmo2pp6k0:bahhy1u)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5M76k15joeYIkzHTDy:-L5M76k15joeYIkzHTDz:b59bimy) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L24)):*
> ```cpp
> 
> using drake::multibody::benchmarks::kuka_iiwa_robot::MakeKukaIiwaModel;
> using drake::multibody::benchmarks::kuka_iiwa_robot::MG::MGKukaIIwaRobot;
> ```

btw, do you need all the namespace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5M76k15joeYIkzHTDy:-L5MqQwlUdpdkMVNk8Q8:b-qs1spd) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/test/multibody_tree_test.cc#L24)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

btw, do you need all the namespace?
</blockquote></details>

BTW Good point -- `drake::multibody` isn't necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5L_m0zUBoEwu67XcZy:-L5oJTrXz-KXwaxSLso6:bhbyhj3) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/multibody_tree.cc#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This looks familiar.  :)
</blockquote></details>

FYI I learnt from the best

---

*[multibody/multibody_tree/multibody_tree.cc, line 709 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8026#-L5Lc8_mGrsXfAXH-jct:-L5oOBz8Fud3OM9qg7QH:b4pd9cz) ([raw file](https://github.com/robotlocomotion/drake/blob/6632f7648fa138d4c55ccebdcccc3ec72a3e5d6e/multibody/multibody_tree/multibody_tree.cc#L709)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Any reason this includes world? If it didn't, then subsequent operations that *skip* world, wouldn't have to skip it.  For example, the for loop below would be:

```C++
for (BodyNodeIndex body_node_index : path_to_world) {
```
</blockquote></details>

BTW I had my reasons at some point but I can't really recall. But it is a good suggestion, I'll ponder on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8026)*

**Pull request merged**
