### PR TITLE
Add support for (simple) discrete-time systems in LQR methods.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8334)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@siyuanfeng-tri for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-:-L7Hylg05u8VhjfY1nUN:b-1z9bi2)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-:-L7LPGz3DI7HlzhDo1Q5:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-:-L7LYsJZAqXDzyNn2mUg:b-ruv0ff)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[systems/controllers/linear_quadratic_regulator.cc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7MdmnrXK8BzhoIsMoz:-L7MdmnrXK8BzhoIsMp-:ban0itk) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/linear_quadratic_regulator.cc#L65)):*
> ```cpp
>   ret.S = math::DiscreteAlgebraicRiccatiEquation(A, B, Q, R);
> 
>   Eigen::MatrixXd tmp = B.transpose() * ret.S *B + R;
> ```

BTW Inconsistent whitespace near `*B`.

---

*[systems/controllers/linear_quadratic_regulator.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7MdItCYzqdsgC_duYH:-L7MdItDKNjAj8Broe95:bbovgnu) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/linear_quadratic_regulator.h#L55)):*
> ```objc
> /// @param R A symmetric positive definite cost matrix of size num_inputs x
> /// num_inputs.
> /// @param N A cost matrix of size num_states x num_inputs.
> ```

BTW There's no `N` in the signature (yet).

---

*[systems/controllers/linear_quadratic_regulator.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7Me89fZmb7hSOIyMP6:-L7Me89fZmb7hSOIyMP7:b-sqieum) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/linear_quadratic_regulator.h#L103)):*
> ```objc
> /// @param context Defines the desired state and control input to regulate the
> /// system to.  Note that this state/input must be an equilibrium point of the
> /// system.  See drake::systems::Linearize for more details.
> ```

FYI Should any of this functions docs be updated to account for discrete time support?  (I didn't find anything obviously wrong or that needed adding.)

---

*[systems/controllers/test/linear_quadratic_regulator_test.cc, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7Mfe2Xihd6Qty-BsTT:-L7Mfe2YAWNqnufv_mbt:b-5l4eko) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/test/linear_quadratic_regulator_test.cc#L190)):*
> ```cpp
> 
>   LinearSystem<double> sys(A, B, Eigen::Matrix<double, 0, 2>::Zero(),
>                          Eigen::Matrix<double, 0, 1>::Zero(), 0.1);
> ```

BTW Wrong indentation.

---

*[systems/controllers/test/linear_quadratic_regulator_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7MhTScAGWYJTc7Qp2Q:-L7MhTScAGWYJTc7Qp2R:b-6utwrt) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/test/linear_quadratic_regulator_test.cc#L192)):*
> ```cpp
>                          Eigen::Matrix<double, 0, 1>::Zero(), 0.1);
> ```

BTW Extra vertical whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-:-L7MjHfpLcvFTUmHaTph:b-vtj4vo)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[systems/controllers/linear_quadratic_regulator.cc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7MdmnrXK8BzhoIsMoz:-L7N1jVWHRWEfn3Q7fGd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/linear_quadratic_regulator.cc#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Inconsistent whitespace near `*B`.
</blockquote></details>

Done.

---

*[systems/controllers/linear_quadratic_regulator.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7MdItCYzqdsgC_duYH:-L7N1rsEY_Kqb1ludUWF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/linear_quadratic_regulator.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW There's no `N` in the signature (yet).
</blockquote></details>

Done.

---

*[systems/controllers/linear_quadratic_regulator.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7Me89fZmb7hSOIyMP6:-L7N3PAnv4f3zyO0SRXA:b-gnnbt) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/linear_quadratic_regulator.h#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Should any of this functions docs be updated to account for discrete time support?  (I didn't find anything obviously wrong or that needed adding.)
</blockquote></details>

it was needed indeed.  done.

---

*[systems/controllers/test/linear_quadratic_regulator_test.cc, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7Mfe2Xihd6Qty-BsTT:-L7N3YIrKoZm7ZoF_eh8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/test/linear_quadratic_regulator_test.cc#L190)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Wrong indentation.
</blockquote></details>

Done.

---

*[systems/controllers/test/linear_quadratic_regulator_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8334#-L7MhTScAGWYJTc7Qp2Q:-L7N3ZycRoIAQyW5FbJx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/488cbaa6eb5e85b2eb563f44ac4c68b416dd45a9/systems/controllers/test/linear_quadratic_regulator_test.cc#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Extra vertical whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8334)*

**Pull request merged**
