### PR TITLE
Add pybind for CommonSolverOption

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312#-:-MdevT-r06G2MmtymRiy:ba7uda8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/common_solver_option_py.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwCsCJ0Ll4JaAEUnfm:-MdwCsCK4eA29L0cccV2:baedbx7) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/common_solver_option_py.cc#L18)):*
> ```cpp
>   m.doc() = "common_solver_option bindings for MathematicalProgram";
> 
>   py::enum_<CommonSolverOption>(
> ```

The class `SolverOptions` is in the `mathematicalprogram` package.  I don't know why the `CommonSolverOption` should be in a different package than `SolverOptions`?
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 409 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwCFwoErvd9DLldKBi:-MdwCFwoErvd9DLldKBj:b-ehxc96) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L409)):*
> ```cpp
>               &SolverOptions::SetOption),
>           py::arg("solver_id"), py::arg("solver_option"),
>           py::arg("option_value"), doc.SolverOptions.SetOption.doc)
> ```

nit If you read `doc.SolverOptions.SetOption.doc`, it's actual referring to the common overload _only_, so all of these existing bindings are documented with lies.

https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.SolverOptions.SetOption

Would you consider adding Doxygen comments in `solver_options.h` on the SolverId-based set methods, and therefore have different `doc_foo` strings here to choose from?
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 422 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwBSSg3L1XEGHV6oGk:-MdwBSSh1I8ooFG51ZXS:bjtsp83) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L422)):*
> ```cpp
>       .def(
>           "SetOption",
>           [](SolverOptions* self, CommonSolverOption key, double value) {
> ```

nit Writing out lambdas is the least desirable choice, per https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeOverloads.

Does `overload_cast` not work here?  I would have expected it to.
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1065 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwD2kS05Yg2jFvUIfm:-MdwD2kT886IfUdrDTgl:bku2pxc) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1065)):*
> ```Python
>         options_object.SetOption(solver_id, "int_key", 2)
>         options_object.SetOption(solver_id, "string_key", "3")
>         options_object.SetOption(CommonSolverOption.kPrintToConsole, 1)
> ```

Missing tests for `float` and `str` overloads.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 409 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwCFwoErvd9DLldKBi:-MdxI52SAfb91_7K9QwQ:b955rom) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L409)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If you read `doc.SolverOptions.SetOption.doc`, it's actual referring to the common overload _only_, so all of these existing bindings are documented with lies.

https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.SolverOptions.SetOption

Would you consider adding Doxygen comments in `solver_options.h` on the SolverId-based set methods, and therefore have different `doc_foo` strings here to choose from?
</blockquote></details>

Done, good call
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 422 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwBSSg3L1XEGHV6oGk:-MdyYgkh2hgIK1rb2QAN:b-um5iuc) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L422)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Writing out lambdas is the least desirable choice, per https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeOverloads.

Does `overload_cast` not work here?  I would have expected it to.
</blockquote></details>

The overload_cast doesn't work here because the second argument is of type `double`, which mismatches with `std::variant<double, int, std::string>`.
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1065 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwD2kS05Yg2jFvUIfm:-MdybI8618X8sUttKLKQ:b21w7v8) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1065)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing tests for `float` and `str` overloads.
</blockquote></details>

We don't have a CommonSolverOption that support `float`. Currently we only have `kPrintFileName` and `kPrintToConsole`, which would throw a runtime error if we pass a float value.
___
*[bindings/pydrake/solvers/common_solver_option_py.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwCsCJ0Ll4JaAEUnfm:-MdxEIKK881YV7FfbweV:b-awpj4b) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/common_solver_option_py.cc#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The class `SolverOptions` is in the `mathematicalprogram` package.  I don't know why the `CommonSolverOption` should be in a different package than `SolverOptions`?
</blockquote></details>

I was trying to avoid `mathematicalprogram` package growing too big. I moved CommonSolverOption to `mathematicalprogram` package.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 422 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwBSSg3L1XEGHV6oGk:-Mdylfi47kAaQ2YzCIl6:b-j5yqou) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L422)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The overload_cast doesn't work here because the second argument is of type `double`, which mismatches with `std::variant<double, int, std::string>`.
</blockquote></details>

Exactly!

This passes all current unit tests
```patch
--- a/bindings/pydrake/solvers/mathematicalprogram_py.cc
+++ b/bindings/pydrake/solvers/mathematicalprogram_py.cc
@@ -418,24 +418,10 @@ top-level documentation for :py:mod:`pydrake.math`.
               const std::string&>(&SolverOptions::SetOption),
           py::arg("solver_id"), py::arg("solver_option"),
           py::arg("option_value"), doc.SolverOptions.SetOption.doc_str_option)
-      .def(
-          "SetOption",
-          [](SolverOptions* self, CommonSolverOption key, double value) {
-            self->SetOption(key, value);
-          },
-          py::arg("key"), py::arg("value"),
-          doc.SolverOptions.SetOption.doc_common_option)
-      .def(
-          "SetOption",
-          [](SolverOptions* self, CommonSolverOption key, int value) {
-            self->SetOption(key, value);
-          },
-          py::arg("key"), py::arg("value"),
-          doc.SolverOptions.SetOption.doc_common_option)
-      .def(
-          "SetOption",
-          [](SolverOptions* self, CommonSolverOption key,
-              const std::string& value) { self->SetOption(key, value); },
+      .def("SetOption",
+          py::overload_cast<CommonSolverOption,
+              const std::variant<double, int, std::string>&>(
+              &SolverOptions::SetOption),
           py::arg("key"), py::arg("value"),
           doc.SolverOptions.SetOption.doc_common_option)
       .def(
```

When pybind11 is working out a function call, it knows how python arguments turn into variants.
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1065 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwD2kS05Yg2jFvUIfm:-Mdyj-DG5TKI6gKpAGYn:b-ekws64) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1065)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We don't have a CommonSolverOption that support `float`. Currently we only have `kPrintFileName` and `kPrintToConsole`, which would throw a runtime error if we pass a float value.
</blockquote></details>

In that case, there is no reason to bind the float overload yet?

But anyway, this discussion is moot once you apply my other patch, where we only bind a single overload.
___
*[bindings/pydrake/solvers/common_solver_option_py.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwCsCJ0Ll4JaAEUnfm:-Mdyj7_H4ZjAhFnS0Ojf:b-dxl0ce) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/common_solver_option_py.cc#L18)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I was trying to avoid `mathematicalprogram` package growing too big. I moved CommonSolverOption to `mathematicalprogram` package.
</blockquote></details>

Ah, okay.  I guess if we wanted to move both SolverOption and CommonSolverOption into their own package that would be consistent, but I don't think the package is too large as-is.  (We have been talking about moving everything into top-level packages in pydrake anyway, so _everything_ would be in pydrake.solvers, even the solver-specific stuff.  Having nested packages is atypical in the Python world)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 422 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwBSSg3L1XEGHV6oGk:-MdzRJ9j59i9Z3p6XhKi:b-wdj8zi) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L422)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Exactly!

This passes all current unit tests
```patch
--- a/bindings/pydrake/solvers/mathematicalprogram_py.cc
+++ b/bindings/pydrake/solvers/mathematicalprogram_py.cc
@@ -418,24 +418,10 @@ top-level documentation for :py:mod:`pydrake.math`.
               const std::string&>(&SolverOptions::SetOption),
           py::arg("solver_id"), py::arg("solver_option"),
           py::arg("option_value"), doc.SolverOptions.SetOption.doc_str_option)
-      .def(
-          "SetOption",
-          [](SolverOptions* self, CommonSolverOption key, double value) {
-            self->SetOption(key, value);
-          },
-          py::arg("key"), py::arg("value"),
-          doc.SolverOptions.SetOption.doc_common_option)
-      .def(
-          "SetOption",
-          [](SolverOptions* self, CommonSolverOption key, int value) {
-            self->SetOption(key, value);
-          },
-          py::arg("key"), py::arg("value"),
-          doc.SolverOptions.SetOption.doc_common_option)
-      .def(
-          "SetOption",
-          [](SolverOptions* self, CommonSolverOption key,
-              const std::string& value) { self->SetOption(key, value); },
+      .def("SetOption",
+          py::overload_cast<CommonSolverOption,
+              const std::variant<double, int, std::string>&>(
+              &SolverOptions::SetOption),
           py::arg("key"), py::arg("value"),
           doc.SolverOptions.SetOption.doc_common_option)
       .def(
```

When pybind11 is working out a function call, it knows how python arguments turn into variants.
</blockquote></details>

Nice, thanks!
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1065 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwD2kS05Yg2jFvUIfm:-MdzRM6C956VrlTwd2cb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1065)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In that case, there is no reason to bind the float overload yet?

But anyway, this discussion is moot once you apply my other patch, where we only bind a single overload.
</blockquote></details>

Done.
___
*[bindings/pydrake/solvers/common_solver_option_py.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15312#-MdwCsCJ0Ll4JaAEUnfm:-MdzRO1C0wQcn6PJ-EbP:bayc2bk) ([raw file](https://github.com/robotlocomotion/drake/blob/ae23c01b01dfb88b092d6ba59c9def1717ca704c/bindings/pydrake/solvers/common_solver_option_py.cc#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, okay.  I guess if we wanted to move both SolverOption and CommonSolverOption into their own package that would be consistent, but I don't think the package is too large as-is.  (We have been talking about moving everything into top-level packages in pydrake anyway, so _everything_ would be in pydrake.solvers, even the solver-specific stuff.  Having nested packages is atypical in the Python world)
</blockquote></details>

I see, I didn't realize that we want to put all the bindings in the directory to a single package.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15312#-:-Me08oxH1e_p7LBrj1ap:bb6yyy8)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
