### PR TITLE
Removed System 1.0 Code From drake/automotive

### PR DESCRIPTION
**Pull request by liangfok**
We're moving everything to System 2.0.

Resolves https://github.com/RobotLocomotion/drake/issues/3978.

Contributes towards https://github.com/RobotLocomotion/drake/issues/3979.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4119)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWIoyRI9ZBOd5q_3AJy:b20t32n)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/CMakeLists.txt, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-KWIr7Dl9AvwM8kqwVJK:-KWIr7DmwZh0RotLGHPS:b-lqwo1m) ([raw file](https://github.com/robotlocomotion/drake/blob/dfe980dbcdf23ae20c2f67b0b64544ded5d57ac1/drake/automotive/CMakeLists.txt#L22)):*
> ```CMake
> target_link_libraries(drakeAutomotive
>   drakeCommon
>   drakeShapes
> ```

BTW Is this still needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWIrAV7ojKiIC0f0TA9:bnfp4nl)*

**Comment by liangfok** [comment]
+@ggould-tri for platform review please.

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/CMakeLists.txt, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-KWIr7Dl9AvwM8kqwVJK:-KWItRaPiWIa88yDM-Aa:b-viliv4) ([raw file](https://github.com/robotlocomotion/drake/blob/dfe980dbcdf23ae20c2f67b0b64544ded5d57ac1/drake/automotive/CMakeLists.txt#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Is this still needed?
</details>
Nope. Removed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWIu3lGLF3GJ7mtk0HK:b-irfx5k)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119)*

**Comment by ggould-tri** [comment]
:lgtm:  I love to see code go away!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWJMJdZsuYFbLgZCnSo:b-75rdq6)*

**Comment by liangfok** [comment]
Dear @jwnimmer-tri and @ggould-tri, I went ahead and also removed the System 1.0 Drake+ROS car demo. PTAL.

---

Review status: 6 of 13 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWJoZjmhVyRrGpYR0nM:b-nry2gc)*

**Comment by jwnimmer-tri** [comment]
Are you sure that's what you want?  If so, it seems like all of the ROS drake_cars_examples items should go -- right now it looks to me like a launcher and other stuff is left around, with no code to run?

---

Review status: 6 of 13 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWJqlK8EEQr3aiolfdq:b-luo2ch)*

**Comment by liangfok** [comment]
Good point. I removed the whole `drake_cars_examples` package. PTAL. 

---

Review status: 6 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119#-:-KWJw2wF_X3hbuxA7112:bmmj4r3)*

**Comment by jwnimmer-tri** [comment]
Reviewed 21 of 21 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119)*

**Comment by ggould-tri** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 21 of 21 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4119)*

**Pull request merged**
