### PR TITLE
Adds Check Verifying Port Sizes Match When Connecting Them

### PR DESCRIPTION
**Pull request by liangfok**
Added a DEMAND to DiagramBuilder::Connect() insisting that the source and destination ports have the same size().

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3992)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for both levels of review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3992#-:-KVXDBzAz1ELtRvVOHKP:b-jzcju5)*

**Comment by david-german-tri** [comment]
:lgtm:  Thanks for adding this!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_builder_test.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3992#-KV_IgiGwGXkjMqJKWHc:-KV_IgiH99keI8U12bou:b4mmg3l) ([raw file](https://github.com/robotlocomotion/drake/blob/58c54eb2609d64cef006c4544d146191003efa00/drake/systems/framework/test/diagram_builder_test.cc#L153)):*
> ```cpp
> 
> // Tests that ports of different sizes cannot be connected.
> GTEST_TEST(DiagramBuilderTest, ConnectPortSizeMismatch) {
> ```

It's good to know this passes, but I don't think we should actually commit it.  Death tests are slow.  If you feel test coverage is important, use DRAKE_THROW_UNLESS, but I think it's fine not to have coverage for a simple sanity-check like this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3992#-:-KV_Iv7SFzVOrRyASjXW:b-ty517j)*

**Comment by liangfok** [comment]
@david-german-tri, thanks for the review. I'm now just waiting on CI to pass.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_builder_test.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3992#-KV_IgiGwGXkjMqJKWHc:-KV_NGx3sCMm4d148-S1:b-6j7swz) ([raw file](https://github.com/robotlocomotion/drake/blob/58c54eb2609d64cef006c4544d146191003efa00/drake/systems/framework/test/diagram_builder_test.cc#L153)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> It's good to know this passes, but I don't think we should actually commit it.  Death tests are slow.  If you feel test coverage is important, use DRAKE_THROW_UNLESS, but I think it's fine not to have coverage for a simple sanity-check like this one.
</details>
Done. I removed the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3992#-:-KV_NIgqRf_Q4WAa_H_y:b5culoi)*

**Comment by liangfok** [comment]
@david-german-tri Wow I'm surprised you were able to merge this without removing the "status: curate commits before merging" tag!

**Comment by david-german-tri** [comment]
Whoops! You're right, I shouldn't have been able to.  Possibly the button in reviewable.io wields my admin powers without asking me to confirm.  Sorry about that!!

**Comment by liangfok** [comment]
No problem! Thanks for merging this PR.

**Pull request merged**
