### PR TITLE
SpatialVector supports symbolic::Expression

### PR DESCRIPTION
**Pull request by amcastro-tri**
Small fixes having to do with `symbolic::Formula` conversion to `bool`. Unit tests added.
Notice a lot of these unit tests (about 40 I believe) are automatically generated with a `TYPED` fixture.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8296)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@soonho-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-:-L71YAZJoOMoGg5ur6ET:bpno49v)*

**Comment by amcastro-tri** [comment]
do you mind if I make you platform for this @jwnimmer-tri? (since you helped me in Slack and you are also reviewing the other symbolic PR).

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-:-L74pgMF9LzrRpwY_2ZM:bp5t06p)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L74wpvsHsjSLev6xEPc:-L74wpvtfCVlIwwaU0Mc:br47e9p) (no related file):*
What do you think about adding `spatial_accleration.cc` and `spatial_force.cc` and `spatial_velocity.cc` with INSTANTIATE...DEFAULT_SCALARS stuff, to prove that this works, even as we evolve the default scalars?

---

*[multibody/multibody_tree/math/test/spatial_algebra_test.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L74yDCnFCf5ZH75XEBs:-L74yDCnFCf5ZH75XEBt:b-ioyl5v) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/test/spatial_algebra_test.cc#L142)):*
> ```cpp
>   EXPECT_EQ(V_AB.size(), 6);
> 
>   // Comparison to Eigen::NumTraits<double>::epsilon() precision.
> ```

FYI Is this comment still true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-:-L74ynciDBXKnYg3bLiz:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SABLhEmBWyDH6M4F:-L75SABLhEmBWyDH6M4G:b-z71cek) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L161)):*
> ```objc
>   /// within @p rotational_tolerance and the translational part of `this` and
>   /// `other` are equal within @p translational_tolerance.
>   decltype(T() < T()) IsNearlyEqualWithinAbsoluteTolerance(
> ```

BTW, @jwnimmer-tri , what do you think about using `auto` in the return type instead of `decltype(T() < T())` in these `Is...` methods?

---

*[multibody/multibody_tree/math/spatial_vector.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SbjiJ6H3jNqmyJ5z:-L75SbjiJ6H3jNqmyJ6-:b-kalbzv) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L163)):*
> ```objc
>   decltype(T() < T()) IsNearlyEqualWithinAbsoluteTolerance(
>       const SpatialQuantity& other, double rotational_tolerance,
>       const double translational_tolerance) const {
> ```

BTW, nit, `const double` -> `double`.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 174 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SsrefDvYvbcd3MFl:-L75SsrefDvYvbcd3MFm:bfaekiq) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L174)):*
> ```objc
>   /// within a specified tolerance.
>   /// Mathematically, if `this` is the spatial vector U and `other` is the
>   /// spatial vector V, then this method returns `true` if `‖U-V‖∞ < ε` and
> ```

BTW, nit, `‖U-V‖∞` -> `‖U-V‖_∞`? (or something better)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-:-L75TOQYayzVv3CV923d:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SABLhEmBWyDH6M4F:-L75WO11MNr7shmyENZZ:b5urz5o) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L161)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, @jwnimmer-tri , what do you think about using `auto` in the return type instead of `decltype(T() < T())` in these `Is...` methods?
</blockquote></details>

OK Given https://eigen.tuxfamily.org/dox/TopicPitfalls.html I'm not sure that we want `auto` anywhere near an Eigen-related code.  Here they are just scalars so I think OK, but for something like `(foo.array() < bar.array()).all()` I'm not sure if thats a boolean or an expression tree.

I think a `drake::formula_over_t<T>` would be better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SABLhEmBWyDH6M4F:-L75X0Bhdmvf-YmEUUYT:balht5l) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L161)):*
> I think a drake::formula_over_t<T> would be better?

SGTM!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L74wpvsHsjSLev6xEPc:-L75XyXWwFz86uPbQ3Zz:bscmx5e) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What do you think about adding `spatial_accleration.cc` and `spatial_force.cc` and `spatial_velocity.cc` with INSTANTIATE...DEFAULT_SCALARS stuff, to prove that this works, even as we evolve the default scalars?
</blockquote></details>

Sure thing. Done.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SABLhEmBWyDH6M4F:-L75YlF7NCMXR3V9dLqy:b-n14yz) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L161)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> I think a drake::formula_over_t<T> would be better?

SGTM!
</blockquote></details>

BTW, sorry, I global search didn't show me any `formula_over_t` in Drake. Is that an upcoming feature?

---

*[multibody/multibody_tree/math/spatial_vector.h, line 174 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SsrefDvYvbcd3MFl:-L75Yy0Z0-b5CnyDAVCg:b-pbiwcr) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L174)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, `‖U-V‖∞` -> `‖U-V‖_∞`? (or something better)
</blockquote></details>

BTW sighs... the limitations of unicode. Personally I do not like how it looks with the underscore.

---

*[multibody/multibody_tree/math/test/spatial_algebra_test.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L74yDCnFCf5ZH75XEBs:-L75ZCeywjVIFEExY8BV:bb7lgjf) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/test/spatial_algebra_test.cc#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Is this comment still true?
</blockquote></details>

nope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SABLhEmBWyDH6M4F:-L75ZZD9sMqdkrmtFdiU:bcdlm6c) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L161)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, sorry, I global search didn't show me any `formula_over_t` in Drake. Is that an upcoming feature?
</blockquote></details>

We had discussed this before but we don't have it yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/math/spatial_vector.h, line 174 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8296#-L75SsrefDvYvbcd3MFl:-L75ZiAxhR6k7ZT3XjqA:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/31950859c7ba89b758ff1b2b8f0593f9d69eb9ed/multibody/multibody_tree/math/spatial_vector.h#L174)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW sighs... the limitations of unicode. Personally I do not like how it looks with the underscore.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Comment by soonho-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8296)*

**Pull request merged**
