### PR TITLE
Guard Eigen::internal::scalar_cmp_op by version

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5739)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5739#-:-Kh-CbqNI2hi4hmj1eb1:b-83dehw)*

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5739#-:-Kh-Ce8Mobv3c4ycXTdC:b-v3eqt6)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5739)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5739#-:-Kh-CjXfO7AGSNXORn8n:bnfp4nl)*

**Pull request merged**
