### PR TITLE
Replace the RigidBodyFrame constructor in RigidBodyTreeURDF.cpp with a factory method

### PR DESCRIPTION
**Pull request by david-german-tri**
Along the way, make some const-flavored XML parsing methods actually const.

CI results for this are uncertain - please hold review until Jenkins replies.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2065)

### CODE REVIEW

**Comment by sherm1** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/rigid_body_tree_urdf.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2065#-KF79uWVkU2P8u8JmE9D:-KF79uWVkU2P8u8JmE9E:1616075587) ([raw file](https://github.com/robotlocomotion/drake/blob/5272c014c61f41fb13d9a30155d38964aeb252b6/drake/systems/plants/rigid_body_tree_urdf.h#L19)):*
`const std::string& name`? (mostly because it is a good habit for places where the extra heap allocation and copy would matter; unlikely it does here)

---

*[drake/systems/plants/RigidBodySystem.cpp, line 328 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2065#-KF7ANjGT_21ijKAXp-S:-KF7ANjGT_21ijKAXp-T:2035567715) ([raw file](https://github.com/robotlocomotion/drake/blob/5272c014c61f41fb13d9a30155d38964aeb252b6/drake/systems/plants/RigidBodySystem.cpp#L328)):*
That's so much nicer!

---

*[drake/systems/plants/RigidBodySystem.cpp, line 365 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2065#-KF7AR08GOTDMwdFrmVG:-KF7AR08GOTDMwdFrmVH:402511206) ([raw file](https://github.com/robotlocomotion/drake/blob/5272c014c61f41fb13d9a30155d38964aeb252b6/drake/systems/plants/RigidBodySystem.cpp#L365)):*
missing comma between `*tree` and `link_ref_node` ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2065)*

**Comment by david-german-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_tree_urdf.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2065#-KF79uWVkU2P8u8JmE9D:-KF9h0_lVRXrTJh9BOaR:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5272c014c61f41fb13d9a30155d38964aeb252b6/drake/systems/plants/rigid_body_tree_urdf.h#L19)):*
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 365 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2065#-KF7AR08GOTDMwdFrmVG:-KF9h7le--08by38LAxH:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5272c014c61f41fb13d9a30155d38964aeb252b6/drake/systems/plants/RigidBodySystem.cpp#L365)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2065)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2065#-:-KFAfdpjL68tLvEh8D_s:1417088721)*

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Pull request merged**
