### PR TITLE
Make SignalLogger::sample_time const-correct

### PR DESCRIPTION
**Pull request by david-german-tri**
Burned by the `Eigen::VectorBlock` CRTP!  The `Derived` part of the return type must have exactly the same `const`-qualification as the vector from which the block was segmented, and a `mutable` class member is non-const even inside a const method.

This is the first time I've ever used `const_cast` to add a `const`.

Also add SignalLogger to the Bazel build.  This change developed without CMake!

@RussTedrake for both levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4295)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/test/signal_logger_test.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-KXlYij-1OLiJ4nNGtM1:-KXlYij04tWd4P19GQ7U:bpsuvs7) ([raw file](https://github.com/robotlocomotion/drake/blob/5c478a9c955dc3b95501c9b4435b00d5aa6e70c6/drake/systems/framework/primitives/test/signal_logger_test.cc#L10)):*
> ```cpp
> #include "drake/systems/framework/diagram_builder.h"
> #include "drake/systems/framework/primitives/linear_system.h"
> #include "drake/systems/framework/primitives/signal_logger.h"
> ```

Shouldn't this be the first line in this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295)*

**Comment by RussTedrake** [comment]
:lgtm: thanks!

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-:-KXld1Vj36vnUyzZOLVY:brfqlux)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for Bazel

**Comment by david-german-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/test/signal_logger_test.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-KXlYij-1OLiJ4nNGtM1:-KXldOUQfsOhD3cbISHw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c478a9c955dc3b95501c9b4435b00d5aa6e70c6/drake/systems/framework/primitives/test/signal_logger_test.cc#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Shouldn't this be the first line in this file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-:-KXlfi7Lq2b0_tjcj5K6:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/BUILD, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-KXlgd3WMCe2_Y5M5HOZ:-KXlgd3XZHEyJ6poCZRF:bx78iec) ([raw file](https://github.com/robotlocomotion/drake/blob/6367867955453034cee3540bb371daaf24acc91c/drake/systems/framework/primitives/BUILD#L89)):*
> ```Python
>     hdrs = [
>         "signal_logger.h",
>     ],
> ```

BTW Why not up on the same line?
(Maybe I should just let buildifier nitpick stuff like this, though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-:-KXlgpC3AW6Qu813PlZW:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/BUILD, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4295#-KXlgd3WMCe2_Y5M5HOZ:-KXlh3OpDjEl8FEwBK0Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6367867955453034cee3540bb371daaf24acc91c/drake/systems/framework/primitives/BUILD#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Why not up on the same line?
(Maybe I should just let buildifier nitpick stuff like this, though.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4295)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-cpplint-experimental please

**Pull request merged**
