### PR TITLE
[systems] Add optional LcmPublisherSystem publish_offset

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19898.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19899)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19899)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: WIth some small nits.

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-:-NajIMOY1HWgMulg0Zs5:b-lwxoqu)* status: 5 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/lcm/lcm_publisher_system.h` line 75 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-Naj8_Ge-N-WXaEDZc06:-Naj8_Ge-N-WXaEDZc07:b1l4bak) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/lcm_publisher_system.h#L75)):*
> ```objc
>    *
>    * @pre publish_period is non-negative.
>    * @pre publish_offset must be finite and non-negative.
> ```

nit: Prerequisites should be stated as fact and not ideals. For both.

And the remaining added prerequisites below.



_Suggestion:_
```objc
is
```
___
*[`systems/lcm/test/lcm_publisher_system_test.cc` line 257 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NajBYaxDrHXjCcYBunr:-NajBYaxDrHXjCcYBuns:by2tdlp) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/test/lcm_publisher_system_test.cc#L257)):*
> ```cpp
> GTEST_TEST(LcmPublisherSystemTest, TestPublishPeriodTrigger) {
>   const double kPublishPeriod = 1.5;  // Seconds between publications.
>   const double kPublishOffset = 0.1;
> ```

BTW Was there a reason to change this *trigger* test to have a non-zero offset? 
___
*[`systems/lcm/test/lcm_publisher_system_test.cc` line 285 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NajAgfDBGvFsVbLY-HF:-NajAgfDBGvFsVbLY-HG:bk4uszx) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/test/lcm_publisher_system_test.cc#L285)):*
> ```cpp
> 
> 
> // Tests that the published LCM message has the expected timestamps, when we've
> ```

nit: Extra empty line above this comment.

(BTW reviewable is currently misbehaving itself for me. Just clicking doesn't work. I have to highlight text to make a "suggestion", hence the reason why this comment is one line down.)
___
*[`systems/lcm/test/lcm_publisher_system_test.cc` line 286 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NajAvFxDiOL3oLRy6Ld:-NajAvFxDiOL3oLRy6Le:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/test/lcm_publisher_system_test.cc#L286)):*
> ```cpp
> 
> // Tests that the published LCM message has the expected timestamps, when we've
> // configured it begin *after* time zero.
> ```

nit: grammar



_Suggestion:_
```cpp
it to begin
```
___
*[`systems/lcm/test/lcm_publisher_system_test.cc` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NajBoep9otubdswFkct:-NajBoep9otubdswFkcu:b76dl0q) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/test/lcm_publisher_system_test.cc#L317)):*
> ```cpp
>     interface.HandleSubscriptions(0);
>     EXPECT_NEAR(simulator.get_mutable_context().get_time(), time, 1e-10);
>     const double expected_publish_time =
> ```

BTW While I can see the benefit of this test, it does lead to kind of hard-to-read code; the calculation for `expected_publish_time` is difficult to grok.

One option is to reduce the discriminative power but make it *really* easy to read by, creating a set of time values {0, 0.1, 1.6, 3.1} * 1000 and just checked that the timestamp was in the set?

Another option to eliminate the math by enumerating the expected message times:

```c++
  const std::vector<double> message_times{0, 0.1, 1.6, 3.1, 4.6};
  int expected_index = 0;
  for (double time = 0; time < 4; time += 0.01) {
    simulator.AdvanceTo(time);
    interface.HandleSubscriptions(0);
    EXPECT_NEAR(simulator.get_mutable_context().get_time(), time, 1e-10);
    if (time >= message_times.at(expected_index + 1)) {
      ++expected_index;
    }
    EXPECT_EQ(sub.message().timestamp, message_times[expected_index] * 1000)
        << fmt::format("time = {}", time);
  }
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19899)* status: needs at least two assigned reviewers

___
*[`systems/lcm/test/lcm_publisher_system_test.cc` line 257 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NajBYaxDrHXjCcYBunr:-NalViUD-T8fEGyxOkCu:berz6xc) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/test/lcm_publisher_system_test.cc#L257)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Was there a reason to change this *trigger* test to have a non-zero offset? 
</blockquote></details>

Yes.  It confirms that this overload of `Make` propagates the offset through to the constructor, instead of accidentally using the default value.
___
*[`systems/lcm/test/lcm_publisher_system_test.cc` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NajBoep9otubdswFkct:-NalWUA9AJa-Hvb6MXok:bn31hk3) ([raw file](https://github.com/RobotLocomotion/drake/blob/24c5bec1ee421268e107b7229bb1a5d3935df9ee/systems/lcm/test/lcm_publisher_system_test.cc#L317)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW While I can see the benefit of this test, it does lead to kind of hard-to-read code; the calculation for `expected_publish_time` is difficult to grok.

One option is to reduce the discriminative power but make it *really* easy to read by, creating a set of time values {0, 0.1, 1.6, 3.1} * 1000 and just checked that the timestamp was in the set?

Another option to eliminate the math by enumerating the expected message times:

```c++
  const std::vector<double> message_times{0, 0.1, 1.6, 3.1, 4.6};
  int expected_index = 0;
  for (double time = 0; time < 4; time += 0.01) {
    simulator.AdvanceTo(time);
    interface.HandleSubscriptions(0);
    EXPECT_NEAR(simulator.get_mutable_context().get_time(), time, 1e-10);
    if (time >= message_times.at(expected_index + 1)) {
      ++expected_index;
    }
    EXPECT_EQ(sub.message().timestamp, message_times[expected_index] * 1000)
        << fmt::format("time = {}", time);
  }
```
</blockquote></details>

I improved the comments a little bit.  I'm not totally in love with the current code, but it's similar the existing test case up above, so for now I'll leave it alone.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-:-Nalw0dUABeO1C7I1vr7:bnfp4nl)* status: 1 unresolved discussion

___
*[`bindings/pydrake/systems/lcm_py.cc` line 224 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19899#-NalvvCfAvO7meQSde5n:-NalvvCg1S757w672YH-:b-zxda0) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc7c4683ca64c454ecd904a20daa34e4371cbb2a/bindings/pydrake/systems/lcm_py.cc#L224)):*
> ```cpp
>             py::arg("publish_offset") = 0.0,
>             // Keep alive, reference: `self` keeps `lcm` alive.
>             py::keep_alive<1, 4>(), cls_doc.ctor.doc_6args);
> ```

btw I'm a bit baffled by the mapping of doc strings, but apparently this is the best we can do?

**Pull request merged**
