### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/issues/13942.

Twin PR: https://github.com/RobotLocomotion/models/pull/48

Unlike other model-moves I've done, here we are _only_ bumping the models sha, not actually deleting the duplicated files yet.  Because there are so many places that use these models, it will be a lot easier to bump the sha, then fix all of the call sites, then delete this repo's copy of the files.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-Nu9wB_sDAinLYzzgA9k:-Nu9wB_sDAinLYzzgA9l:b8coqsw) ([raw file](https://github.com/RobotLocomotion/drake/blob/983ef964f2eb2f63fa7d16ff2a2c7c79255abfbe/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "7ede868f6dd76f1a68c9dc34da991e16ba61dfca",
> ```

Working

Needs a real sha from master

**Comment by jwnimmer-tri** [comment]
Anzu CI passed

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 19 of 20 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review (to match the twin PR).

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 19 of 20 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-:-NuQdEjeBkWOpvucwrVP:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`manipulation/models/README.md` line 11 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-NuQP0yj1vocFC0AKiSR:-NuQP0yj1vocFC0AKiSS:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9601aa10763623393818d03cc58e50f00bc1137/manipulation/models/README.md#L11)):*
> ```Markdown
> # Drake Developers
> 
> Do not many any further changes to these model files.
> ```

typo



_Suggestion:_
```Markdown
Do not make any 
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: needs at least two assigned reviewers

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-Nu9wB_sDAinLYzzgA9k:-NuQitw58NnlR2w8u4Vy:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/983ef964f2eb2f63fa7d16ff2a2c7c79255abfbe/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs a real sha from master
</blockquote></details>

Done

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please (high priority).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 20 files at r2, 5 of 9 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-:-NuU3q1j5SBXrZIMl6Oc:bnfp4nl)* status: 2 unresolved discussions

___
*[`examples/manipulation_station/manipulation_station.cc` line 466 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-NuU2V6T88yjCnww1eQH:-NuU2V6UEYnvnXELXuX3:b-d5iip9) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8e071d9d104c9af856cb7e4147ee156113a748/examples/manipulation_station/manipulation_station.cc#L466)):*
> ```cpp
>         sdf_url, "iiwa", plant_->world_frame(), "iiwa_link_0", X_WI, plant_);
>     RegisterIiwaControllerModel(
>         PackageMap{}.ResolveUrl(sdf_url), iiwa_instance, plant_->world_frame(),
> ```

minor:  This curious idiom is rule-of-three, suggesting that we probably need a proper named function for it.



_Code quote:_
```cpp
PackageMap{}.ResolveUrl
```
___
*[`manipulation/models/jaco_description/BUILD.bazel` line 53 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-NuU3K_HEb9hq5_PRayq:-NuU3K_HEb9hq5_PRayr:b1nlnao) ([raw file](https://github.com/RobotLocomotion/drake/blob/272641faea1629479dc6727fc867d3da2a019144/manipulation/models/jaco_description/BUILD.bazel#L53)):*
> ```Starlark
> # === test/ ===
> 
> drake_cc_googletest(
> ```

Here, and 3x below:  This test goes away here, but does not (and afaict cannot) appear in the models repo.  Is this a deliberate loss of test coverage?

It seems like the test could probably be relocated rather than killed outright.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: 2 unresolved discussions

___
*[`manipulation/models/jaco_description/BUILD.bazel` line 53 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-NuU3K_HEb9hq5_PRayq:-NuU4rsqCe0ZE8BO_VGa:b-jv20l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/272641faea1629479dc6727fc867d3da2a019144/manipulation/models/jaco_description/BUILD.bazel#L53)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Here, and 3x below:  This test goes away here, but does not (and afaict cannot) appear in the models repo.  Is this a deliberate loss of test coverage?

It seems like the test could probably be relocated rather than killed outright.
</blockquote></details>

The https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/drake_models/test/parse_test.py checks that all models in the drake_models repo parse without any warning or errors.  That covers the majority of what was being tested in these programs.

There were a few tests that count how many bodies etc. are in the model (like the jaco one here), and it's true that we've lost those.  I'd argue that they were unnecessary in the first place.

If you think not, I'll open a tracking issue to resurrect those tests in the models repo.  (It does have CI, and we do plant to do parse-checks there https://github.com/RobotLocomotion/models/issues/50.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: 1 unresolved discussion

___
*[`examples/manipulation_station/manipulation_station.cc` line 466 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-NuU2V6T88yjCnww1eQH:-NuU6-d4ApM2bpkXRNVK:b-roqqjl) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8e071d9d104c9af856cb7e4147ee156113a748/examples/manipulation_station/manipulation_station.cc#L466)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This curious idiom is rule-of-three, suggesting that we probably need a proper named function for it.
</blockquote></details>

I'd argue that this is already exactly the function we need -- we want to look up the given URL, using the default package map.

Anyway, the real problem is the poor API design in this class, so I've added a TODO.  I'm not inclined to invest too much time in this file, since the plan is to delete/rewrite it from scratch.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21218)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

___
*[`manipulation/models/jaco_description/BUILD.bazel` line 53 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21218#-NuU3K_HEb9hq5_PRayq:-NuU8GO2AVtQlalZzy-B:b-a1mbgr) ([raw file](https://github.com/RobotLocomotion/drake/blob/272641faea1629479dc6727fc867d3da2a019144/manipulation/models/jaco_description/BUILD.bazel#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/drake_models/test/parse_test.py checks that all models in the drake_models repo parse without any warning or errors.  That covers the majority of what was being tested in these programs.

There were a few tests that count how many bodies etc. are in the model (like the jaco one here), and it's true that we've lost those.  I'd argue that they were unnecessary in the first place.

If you think not, I'll open a tracking issue to resurrect those tests in the models repo.  (It does have CI, and we do plant to do parse-checks there https://github.com/RobotLocomotion/models/issues/50.)
</blockquote></details>

OK:  Seems fine to me, the remaining test coverage you describe seems adequate.

**Pull request merged**
