### PR TITLE
[geometry] Update default resolution hint

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) use a less huge default for resolution hint.

Hazard: the reification penalty is pretty bad in debug builds. Let's see how many tests time out in CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-:-NzTtMqU6kVowVU20sK4:buu9n86)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/scene_graph_config.h` line 55 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-NzU-rg59Nd7ItyMU6aY:-NzU-rg59Nd7ItyMU6aZ:b-6aeds7) ([raw file](https://github.com/RobotLocomotion/drake/blob/48d653d5cf24cd2675f72d767c0fd3c1c108ffbd/geometry/scene_graph_config.h#L55)):*
nit: I'd advocate some additional text on this field's documentation:

> While no single value is universally appropriate, this value was selected based on the following idea. We're attempting to make introducing novel manipulands as easy as possible. Considering a simple soup can as a representative manipuland, we've picked a value that would result in a tessellated cylinder with enough faces to be appropriate for contact with compliant gripper.

Also, for a soup can with diameter of 6.6 cm, a value between 1.17 and 2.33 will produce a tessellation with 8 edges around the circumference. And a value between 0.58 and 1.17 will produce 16 edges (all measures in cms). Assuming I haven't made a silly math mistake.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/scene_graph_config.h` line 55 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-NzU-rg59Nd7ItyMU6aY:-NzUAVjR4PmX8x1Aioab:b-e7qjzv) ([raw file](https://github.com/RobotLocomotion/drake/blob/48d653d5cf24cd2675f72d767c0fd3c1c108ffbd/geometry/scene_graph_config.h#L55)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'd advocate some additional text on this field's documentation:

> While no single value is universally appropriate, this value was selected based on the following idea. We're attempting to make introducing novel manipulands as easy as possible. Considering a simple soup can as a representative manipuland, we've picked a value that would result in a tessellated cylinder with enough faces to be appropriate for contact with compliant gripper.

Also, for a soup can with diameter of 6.6 cm, a value between 1.17 and 2.33 will produce a tessellation with 8 edges around the circumference. And a value between 0.58 and 1.17 will produce 16 edges (all measures in cms). Assuming I haven't made a silly math mistake.
</blockquote></details>

Done, and dialed hint down to 2cm.

**Review by rpoyner-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-:-NzUAcEv0EtYjJeMERcK:b-gpqagm)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: 

(Fingers crossed that reducing the default resolution hint from 0.5 to 0.02 doesn't blow up CI.)

We might consider picking some nightly-ish PRs that are most likely to slow down - sanitizers? Coverage?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-:-NzUCf1C2-U0iRKAf7NO:bjwmgvc)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/scene_graph_config.h` line 61 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-NzUCXAu5Hi617tIRAWO:-NzUCXAu5Hi617tIRAWP:b-j7g59k) ([raw file](https://github.com/RobotLocomotion/drake/blob/bfdb2a8b60977352370f8768de85661e698bfa05/geometry/scene_graph_config.h#L61)):*
> ```objc
>   manipulands as easy as possible. Considering a simple soup can as a
>   representative manipuland, we've picked a value that would result in a
>   tessellated cylinder with enough faces to be appropriate for contact with
> ```

Oops...I like it when my typos get copied in:

"...appropriate for contact with __*a*__ compliant gripper."

**Comment by rpoyner-tri** [comment]
I'm thinking an anzu-drake-pr build is a good idea. I'll kick a coverage build as well.

@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-coverage please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/scene_graph_config.h` line 61 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-NzUCXAu5Hi617tIRAWO:-NzUGYfp8NYzHDOpXUL6:b-uir11d) ([raw file](https://github.com/RobotLocomotion/drake/blob/bfdb2a8b60977352370f8768de85661e698bfa05/geometry/scene_graph_config.h#L61)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Oops...I like it when my typos get copied in:

"...appropriate for contact with __*a*__ compliant gripper."
</blockquote></details>

will do. delaying to avoid blowing up the hand-scheduled kcov build.

**Review by rpoyner-tri — COMMENTED** [review]
anzu-drake-pr succeeded.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-:-NzUOXtt-FrcjZvEOj3A:b-txcdf9)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/scene_graph_config.h` line 61 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-NzUCXAu5Hi617tIRAWO:-NzVhjuW4NrK7pyzS1xP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bfdb2a8b60977352370f8768de85661e698bfa05/geometry/scene_graph_config.h#L61)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

will do. delaying to avoid blowing up the hand-scheduled kcov build.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
So, we like the chances of this to get through nightly/weekly CI? If you want to single-review this, that's fine with me and we can merge it tonight.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-:-NzVobqc-s5kFoR1f53n:b-7dq2r1)* status: needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21511#-:-NzYCq3IDl4uJsCxH8yi:b3dcro0)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
