### PR TITLE
Fix pkg-config -framework CoreFoundation vs Bazel linkopts

### LINKED ISSUE #4593: Fix Bazel python on OSX
Regression as of #4571.

OSX `pkg-config python2` has `-framework CoreFoundation`.
```
-framework name[,suffix]
                This option tells the linker to search for `name.frame-
                work/name' the framework search path. If the optional suffix
                is specified the framework is first searched for the name
                with the suffix and then without (e.g. look for `name.frame-
                work/name_suffix' first, if not there try `name.frame-
                work/name').
```

The issue is that kythe's `bazel-pkg-config` script chops up the return value from `pkg-config` using spaces as a delimiter.

- Possible solution: https://github.com/tensorflow/tensorflow/tree/master/util/python.
- Or else: `$(brew --prefix python)/bin/python-config --exec-prefix` or similar, perhaps.
- FYI `drake-jenkins-bot mac-clang-bazel-experimental please` is now live.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #4593.

For now, this is just a CI test, though.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4609)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Sigh.  Typo'd when refactoring for readability.

@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Has anyone tested this locally on their Mac yet?  CI likes it, but I'd like someone to confirm it work locally also, to be extra cautious.

/CC @RussTedrake @soonho-tri @jamiesnape

**Comment by soonho-tri** [comment]
@jwnimmer-tri , I'll check it on my macs.

**Comment by jamiesnape** [comment]
Yes: https://gist.github.com/jamiesnape/c41ad60634478d57cd35e300f1e37030

**Comment by jwnimmer-tri** [comment]
+@sammy-tri platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4609#-:-K_00MhhuCozDKBr6_Dx:b-ubiskk)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4609#-:-K_01kaAKqGFp5oKhtHX:bnfp4nl)*

**Comment by soonho-tri** [comment]
It works on my mac.

**Pull request merged**
