### PR TITLE
Increase sleep time in collision_checker_test

### LINKED ISSUE #18797: CI Failure: //planning:collision_checker_test
### What happened?

`//planning:collision_checker_test`  fails sporadically on CI. Most recently on [linux-jammy-unprovisioned-gcc-bazel-nightly-everything-debug](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-unprovisioned-gcc-bazel-nightly-everything-debug/222/).

See slack discussions: [here](https://drakedevelopers.slack.com/archives/C270MN28G/p1673718251223099) and [here](https://drakedevelopers.slack.com/archives/C270MN28G/p1676557552736059)

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by calderpg-tri**
Resolves #18797 (properly speaking, mitigates, does not resolve completely)

+@rpoyner-tri for review, thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18800)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18800)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@sammy-tri for platform review.
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18800#-:-NOQwt_G6pYiQYif_mIg:bpfy1jb)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18800#-:-NOQzfYS58cjWZCH88eh:bnfp4nl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @calderpg-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18800#-:-NORUUTW1vs8YH9rISFD:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @calderpg-tri)

**Pull request merged**
