### PR TITLE
Make pick_and_place_state_machine_test more robust to platform differences. 

### PR DESCRIPTION
**Pull request by avalenzu**
Needed for #8263.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8306)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@sammy-tri  for feature review
+@soonho-tri  for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L76SR8s0BbiXOTWQorY:bgsxpz)*

**Comment by avalenzu** [comment]
-@sammy-tri  -@sammy-tri  +(status: do not review) 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L76SizXrMTbQZRWjL3e:b-cai7s9)*

**Comment by avalenzu** [comment]
-@soonho-tri  (darn autocomplete)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L76SnaebhrLiTmG5ePl:b1wgyay)*

**Comment by jwnimmer-tri** [comment]
I ran this through macOS CI in #8263 with the newer SNOPT and it passed.  I think we can review and merge this patch as part of this PR, and then I'll do my PR second?

FYI @hongkai-dai in case you've already reviewed this.

I will self-assign myself here for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.  I saw the "do not review" but maybe this helps anyway.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-L779ctdnWyYd8K_Eu9Q:-L779ctdnWyYd8K_Eu9R:bobjhr7) ([raw file](https://github.com/robotlocomotion/drake/blob/ff98f2c0300926a6835eac71163d79b4531ed1c4/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L109)):*
> ```cpp
>   int step_count = 0;
>   while (dut.state() == PickAndPlaceState::kOpenGripper ||
>          dut.state() == PickAndPlaceState::kPlan) {
> ```

FYI You could throw `(...) && (step_count < 20)` or similar in here to fail earlier than the test runner's timeout if something goes awry?

---

*[examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-L779MLDOrBRPMz8Rpmo:-L779MLEkKS6uECT40ZF:bxhajzy) ([raw file](https://github.com/robotlocomotion/drake/blob/ff98f2c0300926a6835eac71163d79b4531ed1c4/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L112)):*
> ```cpp
>     EXPECT_EQ(iiwa_plan_count, 0);
>     EXPECT_EQ(wsg_command_count, 1);
>     drake::log()->info("asdfasd: {}", static_cast<int>(dut.state()));
> ```

BTW asdfasd

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L779uMwRCraoBVdTZfz:b9jhdip)*

**Comment by avalenzu** [comment]
OK, I had made it do-not-review because I thought you were going to cherry-pick directly into #8263. I'll address your comments and remove the tag.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7AIDYT3af-Yr05abO_:b-op2fcs)*

**Comment by avalenzu** [comment]
+@sammy-tri for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-L779ctdnWyYd8K_Eu9Q:-L7AKKprqBQoMFVckFeW:b-ry9yjt) ([raw file](https://github.com/robotlocomotion/drake/blob/ff98f2c0300926a6835eac71163d79b4531ed1c4/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI You could throw `(...) && (step_count < 20)` or similar in here to fail earlier than the test runner's timeout if something goes awry?
</blockquote></details>

Changed to `ASSERT_LE` and moved into the loop.

---

*[examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-L779MLDOrBRPMz8Rpmo:-L7AKK43gWcT0ANRH23I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ff98f2c0300926a6835eac71163d79b4531ed1c4/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW asdfasd
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7AKQWshmE4q8zf3Nus:bp61js4)*

**Comment by avalenzu** [comment]
-(status: do not review) 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7ALOsGFFf1BSlLG37g:ba0k9zt)*

**Comment by jwnimmer-tri** [comment]
Sounds good.

(The mechanics of having two authors on a PR during review-iteration are not great, so in cases where having two PRs works, I tend to prefer it.  I should have explained this more clearly earlier.)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7ANt05aXZlMao35h-x:b4gbd7k)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 120 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-L7Ah1Jll1CEaX2wIwf_:-L7Ah1Jmn1v_sk179irZ:b4xfi8m) ([raw file](https://github.com/robotlocomotion/drake/blob/62e70023186f7e98e082ce61281a82608449822f/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L120)):*
> ```cpp
>     // small number of steps.
>     iiwa_msg.utime += 5000000;
>     if (!iiwa_plan.plan.empty()) {
> ```

Do we need this if block (and the code inside it) at all?  Since it's at the start of the for loop below we should pick up the plan there...   and I don't think `iiwa_plan.plan` will ever be non-empty while this loop is running?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7BGKRWU52R21-csIpS:bvb1a6z)*

**Comment by avalenzu** [comment]
Addressed reviewer comment.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 120 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-L7Ah1Jll1CEaX2wIwf_:-L7PeQUodTc-apVnwlyB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/62e70023186f7e98e082ce61281a82608449822f/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L120)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Do we need this if block (and the code inside it) at all?  Since it's at the start of the for loop below we should pick up the plan there...   and I don't think `iiwa_plan.plan` will ever be non-empty while this loop is running?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7PeRI9ALpr1OvomtAH:bey2h94)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8306#-:-L7Q-HTrhsM_xr2BpigV:bnfp4nl)*

**Pull request merged**
