### PR TITLE
third_party: Fix license installation for bender

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up on #12305.

\CC @tehbelinda

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12327)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jwnimmer-tri** [comment]
Note that `bazel run //third_party/com_github_finetjul_bender:install -- /tmp/drake --list` prints the list of paths that are installed by that rule.

It used to say:
```
share/doc/drake/LICENSE
```

But with this PR it says:
```
share/doc/bender/LICENSE
share/doc/bender/NOTICE
```

**Comment by jamiesnape** [comment]
Yes, because it's not in a different workspace, it defaulted to `share/doc/drake` and the Drake license is called `LICENSE.txt` so not duplicate file error.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Comment by tehbelinda** [comment]
Thanks!

**Pull request merged**
