### PR TITLE
setup: Add libspdlog-dev on Ubuntu 20.04 Focal

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Adding in anticipation of compiling against the host library, instead of our own separate copy, in #14427.

Towards #14220.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14429)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for platform review per schedule, please.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14429#-:-MO4PDcH88UgEouGQjwK:bnfp4nl)* status: LGTM missing from assignee jamiesnape (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14429#-:-MO7SOqx6CxQfiOky_u1:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),jamiesnape

**Pull request merged**
