### PR TITLE
Fix github3_py on Jammy

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
`github3_py` requires `jwt`. It seems something is causing this to be available on Focal, but on Jammy it needs to be explicitly installed.

This specifically affects `//tools/release_engineering:py/relnotes_test`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17430)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
> so should jwt_py_internal [come from github](https://github.com/davedoesdev/python-jwt)

Why? We use Focal's jwt. Do we also need to use jwcrypto from Github?

**Comment by jwnimmer-tri** [comment]
We don't want to pollute every developer's machine with maintainer-only requirements.  (This PR is adding to test-only requirements, but the relnotes and new_release tools are maintainer-only.)

Perhaps the better solution is to nuke the unit test from `bazel test` (delete it entirely) for now.  We can add CI coverage in the future (e.g., running and posting the "new releases" report automatically every week), though the monthly manual check is probably sufficient for the foreseeable future.

**Comment by jwnimmer-tri** [comment]
I'd say move (both) to maintainer-only, and toss the test.  (Tests can't depend on maintainer-only.)

**Comment by mwoehlke-kitware** [comment]
> I'd say move (both) to maintainer-only, and toss the test.

:+1: Sounds good. I had a look, and the test is fairly dumb anyway, basically just verifying that the script doesn't immediately fall over (e.g. due to an `import` error 🙂 ).

Hopefully I'll have this reworked shortly.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@sherm1 for platform review per schedule, please.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17430#-:-N5Ak2pjDp59wZ0Uy8gX:b2s8ag6)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17430#-:-N5B0s6T9CGm4ZsNmxuu:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
