### PR TITLE
Add more @ingroup tags to doxygen to improve discoverability

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai  for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911#-:-MYPV6LbEMuABRKD8jed:b-jnvn1d)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@seancurtis-tri for platform review on Monday

> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911#-:-MYSUU7m8PRNsPGx4y5S:b-xla8ea)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[systems/trajectory_optimization/direct_collocation.h, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYSUCon3CzOLq7sO0g7:-MYSUCon3CzOLq7sO0g8:bc744yg) ([raw file](https://github.com/robotlocomotion/drake/blob/06414a0f300f89a6bfabcd6b3e7f7fdf1b96299e/systems/trajectory_optimization/direct_collocation.h#L96)):*
> ```objc
> /// Note that the DirectCollocation implementation allocates only ONE of
> /// these constraints, but binds that constraint multiple times (with
> /// different decision variables, along the trajectory).
> ```

BTW, Add `@ingroup solver_evaluators` here?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[systems/trajectory_optimization/direct_collocation.h, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYSUCon3CzOLq7sO0g7:-MYV0m43BacZiIRtc-cM:b-7rl0jd) ([raw file](https://github.com/robotlocomotion/drake/blob/06414a0f300f89a6bfabcd6b3e7f7fdf1b96299e/systems/trajectory_optimization/direct_collocation.h#L96)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, Add `@ingroup solver_evaluators` here?
</blockquote></details>

done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some minor formatting issues.

> Reviewed 30 of 31 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911#-:-MYehI0j2pL9u7oedXYQ:bumf4yt)* status: 3 unresolved discussions (waiting on @RussTedrake)

___
*[doc/doxygen_cxx/doxygen.h, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYeeLEc4-uENHfwABxD:-MYeeLEc4-uENHfwABxE:b-qwopku) ([raw file](https://github.com/robotlocomotion/drake/blob/76e68a4044cefe4fd254d61d14d02a1777effc99/doc/doxygen_cxx/doxygen.h#L52)):*
> ```objc
> */
> 
> namespace solvers {
> ```

BTW If I were to be pedantic, I'd expect the subgroups to be ordered relative to the ordering of the parent groups. As terminology precedes solvers, I'd expect this to come after the two submodules referencing `terminology_and_notation`.

Similarly, the `control` and `planning` submodules are likewise out of order from the modules they belong to.

I won't block on this, but consistent ordering helps people find things.  :)
___
*[doc/doxygen_cxx/doxygen.h, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYeg5If2Gk0J8g27GPY:-MYeg5If2Gk0J8g27GPZ:b2jb15a) ([raw file](https://github.com/robotlocomotion/drake/blob/76e68a4044cefe4fd254d61d14d02a1777effc99/doc/doxygen_cxx/doxygen.h#L55)):*
> ```objc
> /**
>   @{
>     @defgroup solver_evaluators Costs and Constraints
> ```

BTW Is there any concern that the objects that are independently added to this module (and other modules, many predating this PR) will have an order based on doxygen voodoo order (as opposed to, say, alphabetical order)? 
___
*[doc/doxygen_cxx/doxygen.h, line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYef3zK3-YA0LLpGXhd:-MYef3zLBXFZRxtEKLkO:b16oolv) ([raw file](https://github.com/robotlocomotion/drake/blob/76e68a4044cefe4fd254d61d14d02a1777effc99/doc/doxygen_cxx/doxygen.h#L102)):*
> ```objc
>    A collection of algorithms for synthesizing feedback control.
> 
>    A number of control design algorithms can also be found in @ref control_systems (if the design produces a systems::System).
> ```

nit: Line breaks in these two new groups, please. These should fit in our 80 columns.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[doc/doxygen_cxx/doxygen.h, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYeeLEc4-uENHfwABxD:-MYf98JWEBEdfZccfB4r:b-fj1yok) ([raw file](https://github.com/robotlocomotion/drake/blob/76e68a4044cefe4fd254d61d14d02a1777effc99/doc/doxygen_cxx/doxygen.h#L52)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW If I were to be pedantic, I'd expect the subgroups to be ordered relative to the ordering of the parent groups. As terminology precedes solvers, I'd expect this to come after the two submodules referencing `terminology_and_notation`.

Similarly, the `control` and `planning` submodules are likewise out of order from the modules they belong to.

I won't block on this, but consistent ordering helps people find things.  :)
</blockquote></details>

Done. i've tried to reorder the entire file.
___
*[doc/doxygen_cxx/doxygen.h, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYeg5If2Gk0J8g27GPY:-MYfAabPDPPisPApOH6S:brard02) ([raw file](https://github.com/robotlocomotion/drake/blob/76e68a4044cefe4fd254d61d14d02a1777effc99/doc/doxygen_cxx/doxygen.h#L55)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is there any concern that the objects that are independently added to this module (and other modules, many predating this PR) will have an order based on doxygen voodoo order (as opposed to, say, alphabetical order)? 
</blockquote></details>

No concern on my part.  Any lack of discoverability today is due to *lack* of tags (not an unordered overabundance).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14911)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @RussTedrake)

___
*[doc/doxygen_cxx/doxygen.h, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14911#-MYeg5If2Gk0J8g27GPY:-MYfv_3r9pySOLGYzByi:b-lcvz5g) ([raw file](https://github.com/robotlocomotion/drake/blob/76e68a4044cefe4fd254d61d14d02a1777effc99/doc/doxygen_cxx/doxygen.h#L55)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

No concern on my part.  Any lack of discoverability today is due to *lack* of tags (not an unordered overabundance). 
</blockquote></details>

Sounds good. It's a shame that doxygen doesn't have a feature that can handle that.

**Pull request merged**
