### PR TITLE
[WIP] Use user-defined NumPy dtypes for AutoDiffXd, Expression, etc.

### LINKED ISSUE #8116: pydrake: Test reference semantics for matrices of `AutoDiffXd` and `Expression`
Per this comment:
https://github.com/pybind/pybind11/pull/1152#issuecomment-355725117

We can return `Eigen::Ref<>` in `pybind` which, if it has a reference return-value-policy and has a parent, will be converted to a `numpy.ndarray` which is a *view* to the original data (not a copy of the data). This holds for both immutable and mutable references.

However, custom object data types are presently cast using the effective equivalent of `np.array(..., dtype=object)`, which means the matrix data as a whole will not be aliased.

Resolution is to (a) see if there's a way to do the custom NumPy data types. If that is not feasible, then (b) `pydrake` should change its semantics to always "mutate" using parent container mutators / return values (which requries extra copying - blech).

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8116

See tracking issue for progress.

\cc @soonho-tri @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8452)

### CODE REVIEW

**Comment by RussTedrake** [comment]
yuck, but I understand .  if you think that this is the best outcome, i can live with it.

**Comment by EricCousineau-TRI** [comment]
I do believe the other benefits outweigh this cost, but I've submitted https://github.com/numpy/numpy/issues/10876 as a request.

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri This PR has an initial incantation of building NumPy from an upstream PR and using the resulting wheel in a build.
I've also submitted RussTedrake/underactuated#113, which just needed the dot product adjustments.

Do you think I should lump the NumPy repository stuff all together in this PR, or make a separate one?
(My preference is the same one, but I can separate it out if it's less to deal with.)

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, if you have time.

---

Review status: 0 of 45 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8452#-:-LCFWKwj1FOsQiEQFpSK:b8gwv0t)*

**Comment by EricCousineau-TRI** [comment]
Yuppers, can do!

**Comment by sherm1** [comment]
@EricCousineau-TRI -- last activity on this PR was in May. Do you want to keep it open?

**Comment by EricCousineau-TRI** [comment]
Yes, I would like to keep this open. Once deadlines settle down here, I'd like to finish this up, especially in light of MultibodyTree, and supporting autodiff (and eventually symbolic) for them.

**Comment by SeanCurtis-TRI** [comment]
@EricCousineau-TRI assigned to you for PR hygiene.

**Comment by EricCousineau-TRI** [comment]
Closing for now. Can re-open later.

**Pull request closed without merging**
