### PR TITLE
Fix bad dereference on a move'd rvalue, when F&& with perfectly forwa…

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Following up on a Slack conversation. I had introduced a defect in a unittest, by derefencing a move'd `shared_ptr<>` and `unique_ptr<>`, causing a `nullptr` dereference.

Fix is to dereference before forwarding.
(Also cleaned up dereferencing cruft.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6699)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@m-chaturvedi for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6699#-:-Kq9_pSm8SOF9OZa_2Ig:b5o40dz)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please
[ Re-running because of a git flake ]

**Comment by m-chaturvedi** [comment]
:lgtm:

Note that linux-xenial-clang-experimental-memcheck-ubsan is not a required build and it has been run to make sure that we're indeed reducing the number of defects by this PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6699#-:-Kq9nAB71EQtwJBAlC5x:b-r7ozxk)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6699)*

**Comment by sherm1** [comment]
Platform :lgtm:, assuming you are happy with the ubsan run.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6699#-:-Kq9oZzXH0pKp817BNBP:b-835yyr)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6699)*

**Pull request merged**
