### PR TITLE
Prune unwanted dependencies and reorganize

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #12783 and #13168. The criteria I am using here a dependency is included in `binary_distribution` or `source_distribution` iff CI needs it. I do not mind disagreement, but it is probably easier to present this and iterate. Looking at the `binary_distribution`, a dependency is included iff it is needed by drake. We bundle extra headers that we don't use (and a number of which I hope to reduce in time) and any dependencies that are only needed by those are not included. Overall this removes a few convenience tools: `bash-completion`, `gdb`, `virtualenv`. Using `python3-all-dev` is a packaging convention. Not exactly sure where to put `clang-9` for the best, and whether `cmake` should appear in a list is also up for debate (at the moment, our CMake wrapper is not really compatible with the most helpful packaging tools).

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13753)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-snopt-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-snopt-release please

**Comment by jamiesnape** [comment]
Saves about 400 MB on Focal.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-snopt-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review (or initial comments, at least).

**Comment by jwnimmer-tri** [comment]
The PR overview post is a good start, but I also need a definition of "test only" and "maintainer only" written down here, so that I can (1) make sure it makes sense, and (2) check that dependencies are filed roughly correctly.

Writing it out in the PR thread here quickly is fine to help bootstrap my review, but we'll also want that documentation incorporated into the diffs before this PR merges.

**Comment by jamiesnape** [comment]
"test only" = used by `bazel test ...` for some configuration, but not used by `bazel build ...` for any configuration.
"maintenance only" = not used by `bazel test` for any configuration, used by select maintenance scripts, currently `mirror_to_s3.py` and `new_release.py`.

I don't especially mind collapsing the two into one category, and I am not particularly bothered about the names either.

**Comment by jwnimmer-tri** [comment]
I think the regime sounds good.  I'll check over the details later today.

**Comment by jamiesnape** [comment]
Just realized we do not actually install anything to do with Jupyter. Was just trying to find an example where a package actually does. I will probably leave it in the `binary_distribution` for now, however.

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Pull request merged**
