### PR TITLE
Removes unused include from hash.h and updates BUILD file.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7390)

### CODE REVIEW

**Comment by liangfok** [comment]
+@soonho-tri for feature review please. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7390#-:-KxtCtm3RjEy9Shcyxiw:bgak6vv)*

**Comment by soonho-tri** [comment]
I think this is fine. But note that https://github.com/RobotLocomotion/drake/pull/7357 (which is using `"drake/common/drake_assert.h"`) is under review and will be merged soon.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7390#-:-KxtDRi2V_DG8fWlNniY:b-d4hken)*

**Comment by soonho-tri** [comment]
/cc @jwnimmer-tri , the author of #7357.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7390#-:-KxtDkYUszRy5cmNUvro:bc11qkn)*

**Comment by jwnimmer-tri** [comment]
FYI I have no objection to this merging.  My PR merging is ~2 weeks out still.

**Comment by soonho-tri** [comment]
:lgtm:

OK. BTW, I don't think this needs another reviewer.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7390#-:-KxtFHMInm7vMsYD1HZB:ber95o6)*

**Pull request merged**
