### PR TITLE
Analytical solution for mass-damper-spring system with unit tests.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6313)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review: +@edrumwri       
Platform review: +@sherm1

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-:-KmEOcL5w392WLJPF4-1:bhivjav)*

**Comment by edrumwri** [comment]
I worked it over, poked it, and prodded it. :lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmESDhtwTtJM_h5JrPr:-KmESDhtwTtJM_h5JrPs:bdopt94) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc#L20)):*
> ```cpp
> Eigen::Vector3d MassDamperSpringAnalyticalSolution::CalculateOutput(
>     const double t) const {
>   // TODO(@mitiguy) Enhance algorithm to provide for any real values of m, b, k,
> ```

Why would you want to be able to handle negative values for m, b, or k?

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmESZ4_5W7GICjpDgvJ:-KmESZ4_5W7GICjpDgvK:b-wj5lkn) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc#L27)):*
> ```cpp
>   double x, xDt, xDtDt;
> 
>   using std::sqrt;
> ```

Since you're not using AutoDiff, it's a little strange here to use the "using" statements, particularly as you use, for example, `std::abs` below.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmET4fyYqJUTbDcFObd:-KmET4fyYqJUTbDcFObe:b-m8smj) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L12)):*
> ```objc
> namespace benchmarks {
> 
> /// This class provides an analytical solution to a mass-damper-spring system.
> ```

BTW I really like the precision in this description.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmETEP0O7uOBpb22gQK:-KmETEP0O7uOBpb22gQL:b-7v5gcp) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L22)):*
> ```objc
> /// and ẋ is the time-derivative of x.
> ///
> /// @note All units must be self-consistent (e.g., standard SI units).
> ```

This statement allows you to ignore units for mass, b, and k below. But the assumption in drake is MKS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-:-KmEXK1KOQzhkM4yGC_8:b-8m8akj)*

**Comment by mitiguy** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmESDhtwTtJM_h5JrPr:-KmT9p0aaVZaOz0Cb5Xw:b-3msypf) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why would you want to be able to handle negative values for m, b, or k?
</blockquote></details>

Done.  Comment update to answer the question.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmESZ4_5W7GICjpDgvJ:-KmT9t_SD829gdMKSfMo:b-evjtgn) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc#L27)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Since you're not using AutoDiff, it's a little strange here to use the "using" statements, particularly as you use, for example, `std::abs` below.
</blockquote></details>

Done.  I prefer the "using" statements as it makes the solution easier to read.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmETEP0O7uOBpb22gQK:-KmTJBq37wunbhOMzb8v:bxgvm3s) ([raw file](https://github.com/robotlocomotion/drake/blob/8318ead018e8cb420311e3cb98d7ad321a11ad5b/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L22)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This statement allows you to ignore units for mass, b, and k below. But the assumption in drake is MKS.
</blockquote></details>

Done.  Comment updated - including rotational equivalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6313)*

**Comment by sherm1** [comment]
Awesome! :lgtm: with a few BTWs to fix before merging.

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmTzQhTFwAjk-zKM8Vv:-KmTzQhTFwAjk-zKM8Vw:bxrq2za) ([raw file](https://github.com/robotlocomotion/drake/blob/564db0722071c312bc5726eaaa253fb22321c32d/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc#L17)):*
> ```cpp
> // - [Kane, 1985] "Dynamics: Theory and Applications," McGraw-Hill Book Co.,
> //   New York, 1985 (with D. A. Levinson).  Available for free .pdf download:
> //   https://ecommons.cornell.edu/handle/1813/637
> ```

BTW better if the above comment says something like "invokes CalcOutputImpl() using parameters taken from class data members". It really doesn't implement Kane's problem set -- just punts to someone who does. No need to duplicate the documentation here.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmTzqlG3C2zEqFtv271:-KmTzqlG3C2zEqFtv272:b5otmgk) ([raw file](https://github.com/robotlocomotion/drake/blob/564db0722071c312bc5726eaaa253fb22321c32d/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.cc#L53)):*
> ```cpp
> 
>   constexpr double epsilon = std::numeric_limits<double>::epsilon();
>   const double is_zeta_nearly_1 = std::abs(zeta - 1) < 10 * epsilon;
> ```

BTW do you want to treat `std::abs` the same way as sin,cos,exp,sqrt? (with "using")

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmTvKtkINuTuZkfm5pG:-KmTvKtkINuTuZkfm5pH:b-24jnsq) ([raw file](https://github.com/robotlocomotion/drake/blob/564db0722071c312bc5726eaaa253fb22321c32d/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L27)):*
> ```objc
> class MassDamperSpringAnalyticalSolution {
>  public:
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(MassDamperSpringAnalyticalSolution);
> ```

BTW do you need to copy/move/assign objects of this class? If not, the Drake convention is to use DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN instead.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmTvjVLcUKrJQ4LuiJC:-KmTvjVLcUKrJQ4LuiJD:b-qr1x55) ([raw file](https://github.com/robotlocomotion/drake/blob/564db0722071c312bc5726eaaa253fb22321c32d/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L36)):*
> ```objc
>   MassDamperSpringAnalyticalSolution(const double mass,
>                                      const double b,
>                                      const double k) :
> ```

BTW these spurious consts are not allowed in the API because they show in doxygen but don't mean anything. See style guide [clarifications](http://drake.mit.edu/code_style_guide.html#clarifications) "Use of const" for discussion.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-KmTz4XWa3dsQ_npYCNg:-KmTz4XX9_Tqu-2ooI62:bs61oxf) ([raw file](https://github.com/robotlocomotion/drake/blob/564db0722071c312bc5726eaaa253fb22321c32d/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L94)):*
> ```objc
>   //
>   // @returns Three-element matrix consisting of x, ẋ, ẍ, respectively.
>   static Eigen::Vector3d CalculateOutput(const double zeta, const double wn,
> ```

BTW I found it confusing that this private method has the same name as one of the public methods, esp. when looking in the .cc file. How about something like CalcOutputImpl() here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6313#-:-KmU-6pWT5aCgP_NEbiM:bwu9jf6)*

**Pull request merged**
