### PR TITLE
Adds support for sparse A,B,C,D matrices in AffineSystem.

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards properly supporting MatrixGain for sparse matrix multiplicatoin of the actuation matrix in #20971.

This PR relocates sparse_and_dense_matrix from solvers into math with no changes (apart from the namespace), and uses it in AffineSystem.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21591)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for feature review, if you're willing?  I know you helped make the SparseAndDenseMatrix workflow.

I also could use your help with the python bindings (currently my use of SparseMatrix seems to infect the entire primitives module with an unmet dependency on scipy, causing import failures).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21591#-:-O-liKDSE4A2vfOfeKIB:bndu89n)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Do you have any (even manual, unreliable) benchmarks that using sparse instead of dense is faster in cases we care about (e.g., inverse dynamics)?  There is a possibility that sparse matmul is a serious performance degradation for a meaningful number of user of this class, so at least we should be sure that there is any upside before we dig into that question.  In mathematical programs with hundreds or thousands of variables, the sparsity is usually a win (especially as it helps the solver know that some variables are irrelevant).  Here though, for a `num_robot_dofs`-sized matmul, it's not clear to me that the branchy sparse index chasing will be a net win.  It would be a more convincing PR if you had a performance measurement you could post alongside it.

> I also could use your help with the python bindings ...

Is this maybe the first time we have sparse matrix arguments with default values?  That might be the problem.  I think the default arguments get eagerly converted to Python objects during loading, even if the user never calls that overload.  If so, you might need to change e.g. `py::arg("D") = Eigen::SparseMatrix<double>(),` to be `py::arg("D") = Eigen::MatrixXd(),` instead.  Or maybe default them to `None` and then in the body of the binding convert `nullptr` to an empty C++ matrix.

**Comment by jwnimmer-tri** [comment]
One way around the perf question would be to remember whether the user did the dense constructor or sparse constructor, and then likewise the Calc function would then use either dense or sparse matrix operations.  That way, most existing users would be unaffected.

**Comment by jwnimmer-tri** [comment]
To summarize, my main concerns are:

(1) For existing users whose A,B,C,D are mostly non-zeros, we need to be careful not to hurt their performance.

(2) To entertain the implementation complexity of sparse support in this system, we should have at least one offhand example that demonstrates an interesting speedup in practice.

Until those have some progress, I'm -@jwnimmer-tri removing from my dashboard, and +(status: do not review).

**Comment by RussTedrake** [comment]
I understand. The flip side is I felt that I cannot change the use cases which need this (adding the B matrix multiplication into inverse dynamics controller, etc) without convincing you and others that it won't slow down _those_ hot spots. But those are core elements that are clearly broken... and will stay broken if the burden of proof is too high.

My proposal would be to modify this PR to have a SparseOrDenseMatrix version of the class, and land that, without too heavy of a requirement for a convincing performance example.

**Review by RussTedrake — COMMENTED** [review]
for completeness, here is a link to the discussion where @sherm1 worried about using the dense matrix in the inverse dynamics controller: https://reviewable.io/reviews/RobotLocomotion/drake/20971#-Nqyykuh6rzY795cf64J 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21591#-:-O0nTbtd9488ErQNHhP4:bo1ixcl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
> (adding the B matrix multiplication into inverse dynamics controller, etc)

In case you haven't considered it yet, if the only thing needed for IDC is a Permutation system, that might be easier (in terms of development cost), faster (in terms of runtime speed), and clearer (readability in the code, and in graphviz) than trying to use a MatrixGain.

**Review by RussTedrake — COMMENTED** [review]
It's not quite a permutation matrix, but i take the point. I'll just write a new SparseMatrixGain system instead.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21591#-:-O0qDDwT41rIJ0tt8ZvK:bsw52g)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Pull request closed without merging**
