### PR TITLE
Create method to convert angular acceleration to 2nd-time-derivative …

### PR DESCRIPTION
**Pull request by mitiguy**
…of roll-pitch-yaw

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829#-:-LCku_ACE5kdIRcyUjVy:b9rqlek)*

**Comment by hongkai-dai** [comment]
:lgtm: a few minor comments.
+@sherm1 for platform review please.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[math/roll_pitch_yaw.h, line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnlQ1n3TS9Tw0whq5M:-LCnlQ1n3TS9Tw0whq5N:b266n8i) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L232)):*
> ```objc
>   /// @returns `[r̈, p̈, ÿ]`, the 2ⁿᵈ time-derivative of `this` %RollPitchYaw.
>   Vector3<T> AngularAccelerationAToRollPitchYawDDt(
>       const Vector3<T>& rpyDt, const Vector3<T>& alpha_AD_A) const {
> ```

BTW, you could consider to replace the input type of `rpyDt` and `alpha_AD_A` to `const Eigen::Ref<const Vector3<T>>&`. Using `const Eigen::Ref` allows the input to be an Eigen::Expression, such as `Eigen::Vector3d::Zero()`.

---

*[math/roll_pitch_yaw.h, line 411 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnkulJ1-cYwf0hDzs-:-LCnkulJ1-cYwf0hDzs0:bhlk2j7) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L411)):*
> ```objc
>     Matrix3<T> M;
>     // clang-format on
>     M << -sp * cy * pDt - cp * sy * yDt,   -cy * yDt,    T(0),
> ```

BTW, you could factor `sp * pDt` and `cp * yDt`

---

*[math/roll_pitch_yaw.h, line 449 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnl5_Y1Yhy27Mt1g4g:-LCnl5_Y1Yhy27Mt1g4h:blc9746) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L449)):*
> ```objc
>     const T& p = get_pitch_angle();
>     const T& y = get_yaw_angle();
>     const T sp = sin(p), cp = cos(p), one_over_cp = 1.0/cp;
> ```

What if `cp = 0` Namely the Euler angles are at the gimbal lock?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829#-:-LCnloKnDiRsRCfKbxeU:b-v6vajm)*

**Comment by sherm1** [comment]
Checkpoint.

---

Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/quadrotor/quadrotor_plant.cc, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnt1D_7umI_EIoYTZd:-LCnt1Da9n6VmhKy4lIe:b-macn8a) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/examples/quadrotor/quadrotor_plant.cc#L119)):*
> ```cpp
>   // To compute B's angular acceleration in N, expressed in B, due to the net
>   // moment on B, rearrange Euler rigid body equation to solve for alpha_BN_B.
>   // Euler's equation: M = I_.Dot(alpha_BN_B) + w.Cross(I_.Dot(w)).
> ```

BTW above comment seems somewhat self-inconsistent, with a mix of variable names and decorated and undecorated symbols. Also, "Dot" is a vector operator but "I" isn't a vector so this is really a matrix-vector multiply. The capital "M" looks like a matrix rather than a vector (I thought "mass matrix" at first) - lower case would be more conventional I think. Consider unicode something like 𝛕=Iα+ω×(Iω) to make the math clear?

---

*[examples/quadrotor/quadrotor_plant.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnwmA061ERzAdkCGEA:-LCnwmA061ERzAdkCGEB:bq81f2f) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/examples/quadrotor/quadrotor_plant.cc#L126)):*
> ```cpp
>   // Calculate the 2nd time-derivative of rpy.
>   const Vector3<T> rpyDDt =
>       rpy.AngularAccelerationAToRollPitchYawDDt(rpyDt, alpha_BN_N);
> ```

A few thoughts here:
- There seems to be an extra "A" in this method name. I see now from the declaration that "A" is supposed to be a frame, but there is no "A" frame here. Also, the symbol here doesn't map to the formal parameter, which is alpha_AD_A with the _first_ frame repeated, not the second frame. 
- If you want to include a frame in the method name it should be clear that it is a frame by saying something like "InA", but also it should be meaningful at the call site rather than an arbitrary symbol. I'm thinking something like "InParent" or "InChild" or "InWorld" or "InBody".
- BTW "World" or "W" is universally recognized by Drake users but "N" (your favorite) and "G" (my favorite) are not. So if you want shorthand for an inertial frame in a user-visible name, use W rather than N.
- Consider consistently abbreviating acceleration "Accel" to save space. The method name is already consuming half a line of code and it is easy to imagine needing to cram more into it.
- Speaking of that, there is no verb in this method name. I _think_ the "To" in the name makes it clear that this is a conversion or mapping. A verb is not required by the style guide but is a general convention in Drake, please give it some thought. For example, this method could be 
`CalcRollPitchYawDDtFromAngularAccelInParent()`. That also has the advantage that the computed quantity is at the beginning of the name and the RPY,alpha ordering of the arguments is the same as in the name. However Sean and I weren't sure if the "Calc" adds anything or it's fine to have it implied by "From", just wanted to bring up the topic. Let's discuss f2f.

---

*[math/roll_pitch_yaw.h, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo4loFDB0tT7F8_Uy8:-LCo4loFDB0tT7F8_Uy9:b-ptn9x8) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L113)):*
> ```objc
> 
>   /// Returns the yaw-angle underlying a %RollPitchYaw.
>   const T& get_yaw_angle() const { return roll_pitch_yaw_(2); }
> ```

FYI these just-plain-getters are the one place where we conventionally don't use a verb in the function name (optional).  Prefer `roll_angle()` `pitch_angle()` etc.

---

*[math/roll_pitch_yaw.h, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo5HXZ5OMyO3n9b9wz:-LCo5HXZ5OMyO3n9b9x-:blsicwz) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L178)):*
> ```objc
>   /// as Ṙ = ∂R/∂r * ṙ + ∂R/∂p * ṗ + ∂R/∂y * ẏ.  In other words, the returned
>   /// (i, j) element is ∂Rij/∂r * ṙ + ∂Rij/∂p * ṗ + ∂Rij/∂y * ẏ.
>   Matrix3<T> OrdinaryDerivativeRotationMatrix(const Vector3<T>& rpyDt) const {
> ```

META important to have a verb here since this is a (possibly expensive) computation. "Calc" is conventional. (Also other methods here)

---

*[math/roll_pitch_yaw.h, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo6lYz283n2Ufy0R5M:-LCo6lYz283n2Ufy0R5N:bmdvwb5) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L178)):*
> ```objc
>   /// as Ṙ = ∂R/∂r * ṙ + ∂R/∂p * ṗ + ∂R/∂y * ẏ.  In other words, the returned
>   /// (i, j) element is ∂Rij/∂r * ṙ + ∂Rij/∂p * ṗ + ∂Rij/∂y * ẏ.
>   Matrix3<T> OrdinaryDerivativeRotationMatrix(const Vector3<T>& rpyDt) const {
> ```

BTW consider `CalcRotationMatrixDt()` since you already introduced the `Dt` and `DDt` conventions in the API and they are documented in our notation. They save a lot of space and are very easy to read compared to "OrdinaryDerivative".

---

*[math/roll_pitch_yaw.h, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo3wbeCNEBrx1rHm5w:-LCo3wbeCNEBrx1rHm5x:b-11egqr) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L195)):*
> ```objc
>   /// @param[in] rpyDt Time-derivative of `[r; p; y]`, i.e., `[ṙ; ṗ; ẏ]`.
>   /// @returns w_AD_A, frame D's angular velocity in frame A, expressed in A.
>   Vector3<T> RollPitchYawDtToAngularVelocityA(const Vector3<T>& rpyDt) const {
> ```

META See comment in quadrotor_plant.cc: the "A" here doesn't work at the call site for several reasons: it doesn't read as a frame ("InA" would fix that), and "A" is meaningless there ("InParent") or something like that would fix it.

---

*[math/roll_pitch_yaw.h, line 217 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo7jrC6BtA8udPaDEV:-LCo7jrC6BtA8udPaDEW:b-qw8u9r) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L217)):*
> ```objc
>   /// @param[in] w_AD_A, frame D's angular velocity in frame A, expressed in A.
>   /// @returns `[ṙ; ṗ; ẏ]`, the 1ˢᵗ time-derivative of `this` %RollPitchYaw.
>   Vector3<T> AngularVelocityAToRollPitchYawDt(const Vector3<T>& w_AD_A) const {
> ```

BTW consider: `CalcRollPitchYawDtFromAngularVelocityInParent()`.

---

*[math/roll_pitch_yaw.h, line 218 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo9v680lSg5M_rI-Qc:-LCo9v680lSg5M_rI-Qd:byafsfu) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L218)):*
> ```objc
>   /// @returns `[ṙ; ṗ; ẏ]`, the 1ˢᵗ time-derivative of `this` %RollPitchYaw.
>   Vector3<T> AngularVelocityAToRollPitchYawDt(const Vector3<T>& w_AD_A) const {
>     // Get the 3x3 M matrix that contains the partial derivatives of [ṙ, ṗ, ẏ]
> ```

BTW "Get" implies data access; "Calculate" would be better here.

---

*[math/roll_pitch_yaw.h, line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCoA39MDy9zXZXpVxNH:-LCoA39MDy9zXZXpVxNI:bu8mzq3) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L219)):*
> ```objc
>   Vector3<T> AngularVelocityAToRollPitchYawDt(const Vector3<T>& w_AD_A) const {
>     // Get the 3x3 M matrix that contains the partial derivatives of [ṙ, ṗ, ẏ]
>     // with respect to [wAx; wAy; wAz] (which is w_AD_A expressed in A).
> ```

BTW unclear: wAx looks like a product, w_AD_A is already expressed in A so the comment is redundant. Maybe "[wx wy wz], the individual components of w=w_AD_A"?

---

*[math/roll_pitch_yaw.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCoAwFN1H52RcL4sErD:-LCoAwFN1H52RcL4sErE:b-9foxfh) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L231)):*
> ```objc
>   /// expressed in frame A.
>   /// @returns `[r̈, p̈, ÿ]`, the 2ⁿᵈ time-derivative of `this` %RollPitchYaw.
>   Vector3<T> AngularAccelerationAToRollPitchYawDDt(
> ```

See earlier comment. Consider `CalcRollPitchYawDDtFromAngularAccelInParent()` to improve readability at the call site.

---

*[math/roll_pitch_yaw.h, line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo7Pm488U2g5yXy6Hf:-LCo7Pm488U2g5yXy6Hg:b-so1csy) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L249)):*
> ```objc
>   // some algorithms when pitch angle is within 1E-6 of π/2 or -π/2.
>   //
>   // <h3>Theory</h3>
> ```

BTW this (very nice) large private implementation comment should be placed with the implementation in .cc rather than here in the header.

---

*[math/roll_pitch_yaw.h, line 399 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo4K-B5DZxnYNpIJ5a:-LCo4K-B5DZxnYNpIJ5b:bpt4cs6) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L399)):*
> ```objc
>   // @param[in] rpyDt Time-derivative of `[r; p; y]`, i.e., `[ṙ; ṗ; ẏ]`.
>   // @see MatrixRelatingAngularVelocityAToRpyDt()
>   const Matrix3<T> DtMatrixRelatingAngularVelocityAToRpyDt(
> ```

META should have an initial verb ("Calc" would work). At the call site I thought this was just an accessor. Better to make it clear that it is a computation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829#-:-LCoBKYY1HHR8hjq4SaC:by96gdd)*

**Comment by sherm1** [comment]
Platform pass done, ptal.

---

Reviewed 2 of 3 files at r1, 9 of 12 files at r2.
Review status: 9 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[math/roll_pitch_yaw.h, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCowK4BBfPVfgDWNtrm:-LCowK4BBfPVfgDWNtrn:b-1pwjn7) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L222)):*
> ```objc
>     // In other words, `rpyDt = M * w_AD_A`.
>     const Matrix3<T> M = MatrixRelatingRpyDtToAngularVelocityA();
>     return M * w_AD_A;
> ```

BTW this could be done faster if it were expanded out because M's last column is (0,0,1). I don't think you should do that now but I think a TODO here would be good in case we are looking for speedups later.

---

*[math/roll_pitch_yaw.h, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCowwnz1VW8op-_bueo:-LCowwnz1VW8op-_buep:b-fly8pt) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L235)):*
> ```objc
>     const Matrix3<T> Minv = MatrixRelatingRpyDtToAngularVelocityA();
>     const Matrix3<T> MDt = DtMatrixRelatingAngularVelocityAToRpyDt(rpyDt);
>     return Minv * (alpha_AD_A - MDt * rpyDt);
> ```

BTW I think this would be a _lot_ cheaper written out since both Minv and MDt have lots of zeroes. Also I think they have a lot of expensive calculations in common like sin/cos. Please add a TODO if you agree.

---

*[math/roll_pitch_yaw.h, line 442 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCoy11R8PmNY0dUQKpV:-LCoy11R8PmNY0dUQKpW:b-pn868n) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L442)):*
> ```objc
>   // relate the orientation of two generic frames A and D, returns the 3x3
>   // matrix M that contains the partial derivatives of [ṙ, ṗ, ẏ] with respect to
>   // `[wAx; wAy; wAz]` (which is w_AD_A expressed in A).
> ```

BTW ditto here earlier comment.

---

*[math/roll_pitch_yaw.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCp-_BW6fw2AvL7QgSb:-LCp-_BW6fw2AvL7QgSc:bfs1dke) ([raw file](https://github.com/robotlocomotion/drake/blob/af4ca77a03a32b83ac1eb092d4fb6dfba80c36e0/math/roll_pitch_yaw.cc#L26)):*
> ```cpp
> //
> // This accurate algorithm avoids numerical round-off issues encountered by
> // some algorithms when pitch angle is within 1E-6 of π/2 or -π/2.
> ```

BTW the above part of the comment makes sense in the header if you want to leave it there since it describes what the routine does rather than how it does it.

---

*[math/test/roll_pitch_yaw_test.cc, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCozUKu4CKc5KBxmZ2n:-LCozUKu4CKc5KBxmZ2o:b-kagxlr) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/test/roll_pitch_yaw_test.cc#L142)):*
> ```cpp
> }
> 
> // For a RollPitchYaw rpy that relates orientation of a frame A to a frame D,
> ```

FYI seems slightly ambiguous. Consider "For a RollPitchYaw R_AD(rpy) giving frame D's orientation in A ..." ?

---

*[math/test/roll_pitch_yaw_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCp-AgyEHRH-D3JwTOL:-LCp-AgyEHRH-D3JwTOM:b-hc2woh) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/test/roll_pitch_yaw_test.cc#L165)):*
> ```cpp
>   const double pDDt =  alfAy * cos(y) - alfAx * sin(y) - cos(p) * rDt * yDt;
>   const double yDDt = alfAz + cos(p) * pDt * rDt + tan(p) * (alfAx * cos(y)
>                     + alfAy * sin(y) + pDt * yDt + sin(p) * pDt * rDt);
> ```

FYI would be nice to have a reference for this computation if you have one handy.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829#-:-LCp-pL-38Reai085Ii-:b-fhovz2)*

**Comment by hongkai-dai** [comment]
Reviewed 10 of 12 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829)*

**Comment by mitiguy** [comment]
Review status: 8 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/quadrotor/quadrotor_plant.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnwmA061ERzAdkCGEA:-LCorKinCTLOOg-FufKJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/examples/quadrotor/quadrotor_plant.cc#L126)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

A few thoughts here:
- There seems to be an extra "A" in this method name. I see now from the declaration that "A" is supposed to be a frame, but there is no "A" frame here. Also, the symbol here doesn't map to the formal parameter, which is alpha_AD_A with the _first_ frame repeated, not the second frame. 
- If you want to include a frame in the method name it should be clear that it is a frame by saying something like "InA", but also it should be meaningful at the call site rather than an arbitrary symbol. I'm thinking something like "InParent" or "InChild" or "InWorld" or "InBody".
- BTW "World" or "W" is universally recognized by Drake users but "N" (your favorite) and "G" (my favorite) are not. So if you want shorthand for an inertial frame in a user-visible name, use W rather than N.
- Consider consistently abbreviating acceleration "Accel" to save space. The method name is already consuming half a line of code and it is easy to imagine needing to cram more into it.
- Speaking of that, there is no verb in this method name. I _think_ the "To" in the name makes it clear that this is a conversion or mapping. A verb is not required by the style guide but is a general convention in Drake, please give it some thought. For example, this method could be 
`CalcRollPitchYawDDtFromAngularAccelInParent()`. That also has the advantage that the computed quantity is at the beginning of the name and the RPY,alpha ordering of the arguments is the same as in the name. However Sean and I weren't sure if the "Calc" adds anything or it's fine to have it implied by "From", just wanted to bring up the topic. Let's discuss f2f.
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 178 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo5HXZ5OMyO3n9b9wz:-LCorNyWAy5bss0mJFG0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L178)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

META important to have a verb here since this is a (possibly expensive) computation. "Calc" is conventional. (Also other methods here)
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo3wbeCNEBrx1rHm5w:-LCor_PD7ok7lA0hK5K1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L195)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

META See comment in quadrotor_plant.cc: the "A" here doesn't work at the call site for several reasons: it doesn't read as a frame ("InA" would fix that), and "A" is meaningless there ("InParent") or something like that would fix it.
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCoAwFN1H52RcL4sErD:-LCowhEvBRfzyQsSQzj9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L231)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

See earlier comment. Consider `CalcRollPitchYawDDtFromAngularAccelInParent()` to improve readability at the call site.
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 399 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCo4K-B5DZxnYNpIJ5a:-LCoy-KY5ZDno2_4y6xo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L399)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

META should have an initial verb ("Calc" would work). At the call site I thought this was just an accessor. Better to make it clear that it is a computation.
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 449 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8829#-LCnl5_Y1Yhy27Mt1g4g:-LCoymyXA9iok_I5ZXxZ:b-w4lc2x) ([raw file](https://github.com/robotlocomotion/drake/blob/eaf160b22736c36d7e53f6688f0e4a2167d0c9e3/math/roll_pitch_yaw.h#L449)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

What if `cp = 0` Namely the Euler angles are at the gimbal lock?
</blockquote></details>

Done.  Added a comment.  Should there be an assertion ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r3.
Review status: 11 of 12 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8829)*

**Pull request merged**
