### PR TITLE
Added on option to specify the type of interpolation scheme for the R…

### PR DESCRIPTION
**Pull request by rcory**
…obotPlanInterpolator class

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7080)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@sammy-tri for feature review (by author request)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-Kuf4NUVFnJcubvhhRSi:b3cvcu0)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/manipulation/planner/robot_plan_interpolator.cc, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufDOZn6KSBIqagGPNy:-KufDOZomqmMHVIMiYOc:b-ww0n6z) ([raw file](https://github.com/robotlocomotion/drake/blob/70f0e25da8c8fb21df9fbab08c50c29d4a7aa47d/drake/manipulation/planner/robot_plan_interpolator.cc#L228)):*
> ```cpp
>               input_time, knots);
>           break;
>         case InterpolatorType::Pchip :
> ```

It seems strange that requesting pchip interpolation at construction time produces a result which isn't `PiecewisePolynomial::Pchip()`.  I think this could at least use a comment if it is deliberate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by rcory** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/robot_plan_interpolator.cc, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufDOZn6KSBIqagGPNy:-KufH4QxYe_BHKJewlZD:b-dvzgtt) ([raw file](https://github.com/robotlocomotion/drake/blob/70f0e25da8c8fb21df9fbab08c50c29d4a7aa47d/drake/manipulation/planner/robot_plan_interpolator.cc#L228)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems strange that requesting pchip interpolation at construction time produces a result which isn't `PiecewisePolynomial::Pchip()`.  I think this could at least use a comment if it is deliberate?
</blockquote></details>

Yup. That's a copy/paste bug! Good catch!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufKuUwUMGVR5mgHiL8:-KufKuUwUMGVR5mgHiL9:b-cl1z05) (no related file):*
It bothers me a little bit that there's no test that the non-default interpolation modes produce sane output.  Looking at `TrajectoryTest` from `robot_plan_interpolator_test.cc`, it looks like it might not be too difficult to produce a version which tests each mode (probably with the exception of `ZeroOrderHold`, which I suspect will not produce suitable derivatives).  I think it's worth investigating and either improving the test coverage or stating why we think only testing `Cubic` is adequate.  If all we have to do is move `TrajectoryTest` into a function which takes the interpolation type is an argument and call it from three different tests, that doesn't seem too hard.  If I'm wrong and it doesn't work I apologize in advance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-KufKwKabOMDkpVxBOPk:b-s794vx)*

**Comment by rcory** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufKuUwUMGVR5mgHiL8:-KufgkaT2QhgAyUjJtAx:b-tq0y7s) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It bothers me a little bit that there's no test that the non-default interpolation modes produce sane output.  Looking at `TrajectoryTest` from `robot_plan_interpolator_test.cc`, it looks like it might not be too difficult to produce a version which tests each mode (probably with the exception of `ZeroOrderHold`, which I suspect will not produce suitable derivatives).  I think it's worth investigating and either improving the test coverage or stating why we think only testing `Cubic` is adequate.  If all we have to do is move `TrajectoryTest` into a function which takes the interpolation type is an argument and call it from three different tests, that doesn't seem too hard.  If I'm wrong and it doesn't work I apologize in advance.
</blockquote></details>

This is a good idea. I've taken a pass at this and it seems that all but Cubic fails the test. I'll have to dig a little more to understand the failure. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufKuUwUMGVR5mgHiL8:-Kut_w7rbUt-Sf-GZEU4:b-4r4n6b) (no related file):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

This is a good idea. I've taken a pass at this and it seems that all but Cubic fails the test. I'll have to dig a little more to understand the failure. 
</blockquote></details>

Ouch, sorry for making you wade into that test, it's not exactly representative of my finest work.  I was hoping that since the test only looks at the signs of the derivative values between the knot points it wouldn't be so sensitive to the interpolation chosen (obviously I was wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by rcory** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufKuUwUMGVR5mgHiL8:-KuynOy5Mfv4H13nAD-9:b-w5pxjf) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ouch, sorry for making you wade into that test, it's not exactly representative of my finest work.  I was hoping that since the test only looks at the signs of the derivative values between the knot points it wouldn't be so sensitive to the interpolation chosen (obviously I was wrong.
</blockquote></details>

Would you be ok with having the test check actual values (pos, vel, and accel) instead of just signs? Using something like the gtest macro EXPECT_NEAR? Is there any reason to think that would be a bad idea?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufKuUwUMGVR5mgHiL8:-Kuz1MxDRBmdtao1RlSu:bx2tuvt) (no related file):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Would you be ok with having the test check actual values (pos, vel, and accel) instead of just signs? Using something like the gtest macro EXPECT_NEAR? Is there any reason to think that would be a bad idea?
</blockquote></details>

I don't think I see any significant downside...  You'd presumably need different expected values for different interpolation schemes, but that also seems reasonable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KufKuUwUMGVR5mgHiL8:-KuzNseg8JO0cYOtA1bx:bscux7x) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think I see any significant downside...  You'd presumably need different expected values for different interpolation schemes, but that also seems reasonable.
</blockquote></details>

Thanks for adding this!

---

*[drake/manipulation/planner/robot_plan_interpolator.cc, line 230 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KuzNJxVngs1TroZCzIK:-KuzNJxVngs1TroZCzIL:b-hjqi5j) ([raw file](https://github.com/robotlocomotion/drake/blob/66cf4f075657e4314e857dac03b5f7199400881a/drake/manipulation/planner/robot_plan_interpolator.cc#L230)):*
> ```cpp
>         case InterpolatorType::Pchip :
>           plan.pp = PiecewisePolynomial<double>::Pchip(
>               input_time, knots);
> ```

When using cubic interpolation, we pass in zero values of `knot_dot` for the end point derivativies.  When doing pchip interpolation, should we set `zero_end_point_derivatives` to zero for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by rcory** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/robot_plan_interpolator.cc, line 230 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-KuzNJxVngs1TroZCzIK:-KuzSFu-ho3C0W6GRbbZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66cf4f075657e4314e857dac03b5f7199400881a/drake/manipulation/planner/robot_plan_interpolator.cc#L230)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

When using cubic interpolation, we pass in zero values of `knot_dot` for the end point derivativies.  When doing pchip interpolation, should we set `zero_end_point_derivatives` to zero for consistency?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by sammy-tri** [comment]
One last (hopefully final) comment.  Thanks for bearing with me!

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/test/robot_plan_interpolator_test.cc, line 177 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-Kuzb5EmNX74J9NPiaMY:-Kuzb5EmNX74J9NPiaMZ:b-t5hk7t) ([raw file](https://github.com/robotlocomotion/drake/blob/91bb129e9d7d6692a1d86f3d54989cf2ea3c3e19/drake/manipulation/planner/test/robot_plan_interpolator_test.cc#L177)):*
> ```cpp
>   // velocity.
>   if (interp_type == InterpolatorType::Cubic ||
>       interp_type == InterpolatorType::ZeroOrderHold) {
> ```

Now that we're setting `zero_end_point_derivatives` for pchip, should it be included in this part of the test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-KuzbIO2UCccPgcjw9FG:b-y44sxq)*

**Comment by rcory** [comment]
No problem! These are good catches!

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/planner/test/robot_plan_interpolator_test.cc, line 177 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-Kuzb5EmNX74J9NPiaMY:-KuzhMWcVG2E-LZXU2YV:b-acqmhu) ([raw file](https://github.com/robotlocomotion/drake/blob/91bb129e9d7d6692a1d86f3d54989cf2ea3c3e19/drake/manipulation/planner/test/robot_plan_interpolator_test.cc#L177)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Now that we're setting `zero_end_point_derivatives` for pchip, should it be included in this part of the test?
</blockquote></details>

Yup! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-KuzhUKbNef-3WKubCOE:b-ctzprm)*

**Comment by sammy-tri** [comment]
:lgtm: +@seancurtis-tri for platform review per rotation

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-KuzwC8McJXXzj9Ve9Y7:b3fwr6c)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Modulo two minor typographical issues.

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/planner/robot_plan_interpolator.h, line 16 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-Kv2qhQ_SaPqvOT2nKhK:-Kv2qhQ_SaPqvOT2nKhL:bs31fl6) ([raw file](https://github.com/robotlocomotion/drake/blob/a03cb1290edf14863b365e2fa0171b3c786371c9/drake/manipulation/planner/robot_plan_interpolator.h#L16)):*
> ```objc
> namespace planner {
> 
> /// This enum specifies the type of interpolator to use in constructing
> ```

BTW Nit: missing final period.

---

*[drake/manipulation/planner/test/robot_plan_interpolator_test.cc, line 65 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-Kv2rO8cH2UNX8IPbd2K:-Kv2rO8cH2UNX8IPbd2L:b6bcy41) ([raw file](https://github.com/robotlocomotion/drake/blob/a03cb1290edf14863b365e2fa0171b3c786371c9/drake/manipulation/planner/test/robot_plan_interpolator_test.cc#L65)):*
> ```cpp
> 
>   const double time{};
>   const double position {};
> ```

Extra space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-Kv2s5dTLQPQf2i4esZb:bpd0i2x)*

**Comment by rcory** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/planner/robot_plan_interpolator.h, line 16 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-Kv2qhQ_SaPqvOT2nKhK:-Kv35mBqlLWwnFfyXgjE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a03cb1290edf14863b365e2fa0171b3c786371c9/drake/manipulation/planner/robot_plan_interpolator.h#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Nit: missing final period.
</blockquote></details>

Done.

---

*[drake/manipulation/planner/test/robot_plan_interpolator_test.cc, line 65 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-Kv2rO8cH2UNX8IPbd2K:-Kv35miBKiCGpk9Nn0_V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a03cb1290edf14863b365e2fa0171b3c786371c9/drake/manipulation/planner/test/robot_plan_interpolator_test.cc#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Extra space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7080#-:-Kv3gRKY7XNnUR4rHEem:b-l70wzf)*

**Pull request merged**
