### PR TITLE
new_release now prompts to check if Bazel needs to be upgraded

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
When reporting the list of external dependencies that can be upgraded, always print a reminder to check if a new version of Bazel is available.

Towards #20741

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21697)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21697#-:-O1NyQzHDBEtKV3n0lVH:bk3jhcb)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21697#-:-O1X9fXP07eQ_be2iXFo:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
+@EricCousineau-TRI for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21697#-:-O1Xe9sw4sda228ybGo7:bwu48t1)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21697#-:-O1Xjzaw2SNHQbMIAFcQ:bcpz082)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),mwoehlke-kitware

**Pull request merged**
