### PR TITLE
Separate out articulated ICP test utilities.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is in prep for submitting simple closed-form ICP / PCA methods:
https://github.com/RobotLocomotion/drake/compare/master...EricCousineau-TRI:feature/icp_closed_form-wip

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6753)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please. (Hopefully this is just a short one.)

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6753#-:-KqZNMRK62yWPVAwsf9w:btiz0h3)*

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Reviewed 3 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/perception/estimators/dev/test/test_util.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6753#-KqZOnnSfvaUqH5_n4pq:-KqZOnnSfvaUqH5_n4pr:b-to7ttk) ([raw file](https://github.com/robotlocomotion/drake/blob/17535b97fd2f65482d04c0c215c459cf471299f5/drake/perception/estimators/dev/test/test_util.cc#L88)):*
> ```cpp
>   // First, ensure that R_actual is a rotation matrix.
>   ::testing::AssertionResult check_rotation = CompareMatrices(
>       Matrix3d::Identity(), R_actual.transpose() * R_actual, tolerance);
> ```

Also check determinant of `R_actual`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6753#-:-Kqcr4WZG5o71F4uMsYZ:b-mkkz8q)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/perception/estimators/dev/test/test_util.cc, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6753#-KqZOnnSfvaUqH5_n4pq:-KqcsRpl4smA5LdT9off:b-heyywu) ([raw file](https://github.com/robotlocomotion/drake/blob/17535b97fd2f65482d04c0c215c459cf471299f5/drake/perception/estimators/dev/test/test_util.cc#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also check determinant of `R_actual`?
</blockquote></details>

Sorry, I realized that this function was out of scope for this review. Will do it in a subsequent PR, where it is actually used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6753)*

**Comment by soonho-tri** [comment]
FYI, code under `dev` directory does not require a platform-review. -@soonho-tri  (let me know if reviewable insists it).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6753#-:-Kqd0DlOF2ylGs6tTp4j:b-c3ic89)*

**Comment by hongkai-dai** [comment]
Got it, thanks!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6753#-:-Kqd0ulomT6K5fXtJM6L:bcr5s2o)*

**Pull request merged**
