### PR TITLE
Fix Wunused-parameter in bouncing_ball and contact_model

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6034)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.  This repairs unused parameters using the guidelines in [drake::unused's documentation](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0).

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6034#-:-KjNtoDNp9SXaIPOp1Dz:bmxilld)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6034#-:-KjOpA0p8lCD6OHFTsik:bnfp4nl)*

**Pull request merged**
