### PR TITLE
Update lcm-related bazel library names

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove `//util:lcm_util` forwarding header, long since deprecated.

Rename `//lcm:lcm` to `//lcm:real` to clarify that it is only a concrete implementation of the interface, instead of everything in the package. Do not rename in-tree uses to match; they can use the package-level library without adding overly many spurious dependencies.

Rename `//systems/lcm:lcm` to `//systems/lcm:lcm_pubsub` to clarify that it is only the publisher and subscriber systems, instead of everything in the package.  Rename all in-tree uses to match.

Add `drake_cc_package_library` for `//lcm` and `//systems/lcm`.

Builds on #8664. Relates #6464.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8727)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review, please.

**Comment by sammy-tri** [comment]
One minor question + one really minor BTW.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[lcm/BUILD.bazel, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8727#-LBRhXCz6pp8aIpWu0oT:-LBRhXCz6pp8aIpWu0oU:b-j3v938) ([raw file](https://github.com/robotlocomotion/drake/blob/ac1152d99b14205906290230cc95f9ff2bf49aa4/lcm/BUILD.bazel#L9)):*
> ```Python
>     "drake_cc_package_library",
> )
> load("//tools/skylark:drake_py.bzl", "drake_py_test")
> ```

BTW the spelling of the path to `tools/skylark` is now inconsistent in this file.

---

*[tools/install/libdrake/build_components.bzl, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8727#-LBRiI866X9D_e4yYTGm:-LBRiI866X9D_e4yYTGn:b-6571st) ([raw file](https://github.com/robotlocomotion/drake/blob/ac1152d99b14205906290230cc95f9ff2bf49aa4/tools/install/libdrake/build_components.bzl#L110)):*
> ```Python
>     "//geometry:shape_specification",
>     "//lcm:interface",
>     "//lcm:lcm",
> ```

BTW Now that `//lcm:lcm` is the package library, are the entries below redundant?  Or is the convention here to always list out all of the individual components even when the package library is included?  (since it happens again below in `//systems/lcm` it seemed like it might be conventional)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8727#-:-LBRj-BW7qR2UJBq6VhQ:b-x1qbrq)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/install/libdrake/build_components.bzl, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8727#-LBRiI866X9D_e4yYTGm:-LBRklci5ucqgLu5MdKT:bxrd1oy) ([raw file](https://github.com/robotlocomotion/drake/blob/ac1152d99b14205906290230cc95f9ff2bf49aa4/tools/install/libdrake/build_components.bzl#L110)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Now that `//lcm:lcm` is the package library, are the entries below redundant?  Or is the convention here to always list out all of the individual components even when the package library is included?  (since it happens again below in `//systems/lcm` it seemed like it might be conventional)
</blockquote></details>

/me facepalm.  It's autogenerated.  Never mind.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8727)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[lcm/BUILD.bazel, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8727#-LBRhXCz6pp8aIpWu0oT:-LBRnILs-9FmaUsHsjK7:buyhxhp) ([raw file](https://github.com/robotlocomotion/drake/blob/ac1152d99b14205906290230cc95f9ff2bf49aa4/lcm/BUILD.bazel#L9)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW the spelling of the path to `tools/skylark` is now inconsistent in this file.
</blockquote></details>

OK Hmm, I see that's a project-wide problem now.  I'll open an issue => #8732.

---

*[tools/install/libdrake/build_components.bzl, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8727#-LBRiI866X9D_e4yYTGm:-LBRnfoN3Lspe6p2Ygh0:b-uznhp6) ([raw file](https://github.com/robotlocomotion/drake/blob/ac1152d99b14205906290230cc95f9ff2bf49aa4/tools/install/libdrake/build_components.bzl#L110)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

/me facepalm.  It's autogenerated.  Never mind.
</blockquote></details>

OK Right!  Also the work on #6464 actually makes it so all of the colon-library details here get eviscerated, very soon now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8727)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8727#-:-LBRtrno1DkFwggMYfaM:bnfp4nl)*

**Pull request merged**
