### PR TITLE
Add private dependencies and resource root variable to Drake CPS file

### PR DESCRIPTION
**Pull request by jamiesnape**
Since Bazel unfortunately does not link its dependent shared libraries, they must be included here.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6909)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@stonier for feature review.

**Comment by stonier** [comment]
For reference, the `drake_RESOURCE_ROOT` is so CMake users of the Drake binary can easily access the drake resources via the `find_package(Drake)` invocation (see [here](https://github.com/RobotLocomotion/drake-shambhala/pull/30).

:lgtm:

+@sherm1 for platform review please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6909#-:-KsOU7lvLdde5vlsJC-y:b-nx7bpx)*

**Comment by sherm1** [comment]
Platform :lgtm: (cursory -- I am counting on a good feature review here since I know very little about this). One BTW question.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake.cps, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6909#-KsPCOp2wlQGZPg8YhPw:-KsPCOp333ytISO4lA6P:b-ybtwgy) ([raw file](https://github.com/robotlocomotion/drake/blob/eefddf059e73ff9cb66381dc2b01415d49ca59f6/tools/drake.cps#L88)):*
> ```delphi
>       ],
>       "Compile-Features": ["c++14"],
>       "Link-Flags": ["-lz"],
> ```

BTW I'm not sure where this `-lz` flag ends up. A quick look at `man ld` shows a `-z` flag but it appears to require a keyword argument. Is something missing here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6909#-:-KsPJkDb9108qodf-wkd:b-zepuzv)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake.cps, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6909#-KsPCOp2wlQGZPg8YhPw:-KsPKJn_IXnvrl_rWc3E:b-cbbva2) ([raw file](https://github.com/robotlocomotion/drake/blob/eefddf059e73ff9cb66381dc2b01415d49ca59f6/tools/drake.cps#L88)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm not sure where this `-lz` flag ends up. A quick look at `man ld` shows a `-z` flag but it appears to require a keyword argument. Is something missing here?
</blockquote></details>

`-lz` = `-l/usr/lib/libz.{dylib|so}` = Link to zlib.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6909)*

**Pull request merged**
