### PR TITLE
[geometry/optimization] Fix preprocessing for GraphOfConvexSets

### PR DESCRIPTION
**Pull request by mpetersen94**
Re-enables preprocessing in the tests changed in #17855 and fixes a bug with the preprocessing tests.
Fix to #17397 

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-undefined-behavior-sanitizer please

**Comment by EricCousineau-TRI** [comment]
Howdy Mark! This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer. If not, could you label it “status: do not review”?

(per checklist - https://drake.mit.edu/platform_reviewer_checklist.html)

**Review by mpetersen94 — COMMENTED** [review]
+@russtedrake for delegation of feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876#-:-NBYEbGy3Ob7-QtPjjYO:b1k0cub)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
@mpetersen94 -- which bug was fixed by this PR?  Just the passing of the options struct?  Was there supposed to be more?

+@ggould-tri for platform review, please.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876#-:-NBcxeWQ8lWPFc-PJKnY:b1h4u7a)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBcyEtQ1tVHRHSz5pkU:-NBcyEtQ1tVHRHSz5pkV:b-v27thk) ([raw file](https://github.com/robotlocomotion/drake/blob/09c7db71116b907d1c721dcea423612d3ec2b09f/geometry/optimization/graph_of_convex_sets.h#L39)):*
> ```objc
>   Note that this preprocessing is not exact. There may be edges that cannot
>   lie on the path from source to target that this does not detect. */
>   bool preprocessing{false};
> ```

btw -- @ggould-tri -- note that this addresses some post-merge feedback we received in https://github.com/RobotLocomotion/drake/pull/17397

**Review by RussTedrake — COMMENTED** [review]
Oops.  Scratch my question.  I was only seeing the diff from the last commit.  Looking at the entire PR answered my question!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876#-:-NBcysP2AMnulUag3j2e:bjb5j4d)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+(release notes: fix) :lgtm: 

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876#-:-NBljQVe8_RbNcXBHlfV:b37sbli)* status: 2 unresolved discussions (waiting on @mpetersen94)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBljFpND6_7hodyDzQM):*
minor:  It would be good to mention #17397 here so that the release engineer will know that these commits belong together on a single line for the release notes.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBcyEtQ1tVHRHSz5pkU:-NBlj94FCVq31TCeFhSV:b7aypxu) ([raw file](https://github.com/robotlocomotion/drake/blob/09c7db71116b907d1c721dcea423612d3ec2b09f/geometry/optimization/graph_of_convex_sets.h#L39)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- @ggould-tri -- note that this addresses some post-merge feedback we received in https://github.com/RobotLocomotion/drake/pull/17397
</blockquote></details>

Thanks!  Noted that for the commit message.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 390 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBlktipCx_JHvWftQMN:-NBlktipCx_JHvWftQMO:b1qal7t) ([raw file](https://github.com/robotlocomotion/drake/blob/09c7db71116b907d1c721dcea423612d3ec2b09f/geometry/optimization/graph_of_convex_sets.cc#L390)):*
> ```cpp
> 
>   for (const auto& [edge_id, e] : edges_) {
>     if (unusable_edges.find(edge_id) != unusable_edges.end()) {
> ```

minor:  `std::set::count` is a bit terser and will make `std::set::contains` a drop-in replacement when it arrives.



_Suggestion:_
```cpp
if (unusable_edges.count(edge_id))
```

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBljFpND6_7hodyDzQM):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It would be good to mention #17397 here so that the release engineer will know that these commits belong together on a single line for the release notes.
</blockquote></details>

Added a comment in the PR description. Should it be in the PR name or is reference in the description sufficient?
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 390 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBlktipCx_JHvWftQMN:-NBmuEfp1R21nEgFttZF:blvwa4w) ([raw file](https://github.com/robotlocomotion/drake/blob/09c7db71116b907d1c721dcea423612d3ec2b09f/geometry/optimization/graph_of_convex_sets.cc#L390)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  `std::set::count` is a bit terser and will make `std::set::contains` a drop-in replacement when it arrives.
</blockquote></details>

TIL! Done here and another place.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17876)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @mpetersen94)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17876#-NBljFpND6_7hodyDzQM):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Added a comment in the PR description. Should it be in the PR name or is reference in the description sufficient?
</blockquote></details>

A reference in the description is fine.

**Pull request merged**
