### PR TITLE
Deprecate some drakeGeometryUtil constants in favor of drake-namespaced ones.

### PR DESCRIPTION
**Pull request by david-german-tri**
We are getting close to zapping `#include "drakeGeometryUtil.h"` from the last header files where it appears.

@sherm1 for feature and platform review, since this change is trivial.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2785)

### CODE REVIEW

**Comment by sherm1** [comment]
Looks good except:
- RpySize is a distinct concept from SpaceDimension and shouldn't be collapsed.
- I hate these constants! (not your fault :). Saying QuaternionSize=4 to me is like having constants Three=3 and Five=5. I think this was originally just an attempt to avoid making typedefs or having to write comments to convey meaning. I don't think they are helpful. (I'm just ranting -- not saying you should change this in this PR.)

---

Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/common/constants.h, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUkRf08XL0dwxyqyER:-KMUkRf08XL0dwxyqyES:-1701223302) ([raw file](https://github.com/robotlocomotion/drake/blob/1fef1d76a248be341724950bd015f4bda260c75d/drake/common/constants.h#L6)):*
> ```objc
> 
> constexpr int kQuaternionSize = 4;
> ```

`constexpr int kRpySize = 3;`

---

*[drake/systems/plants/RigidBodyTree.h, line 399 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUgnIBFILoqcEGAXUD:-KMUgnIBFILoqcEGAXUE:1987656444) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/RigidBodyTree.h#L399)):*
> ```objc
> 
>   template <typename Scalar>
>   Eigen::Matrix<Scalar, drake::kSpaceDimension, Eigen::Dynamic>
> ```

(For the record, I don't think these constants are helpful at all. Typedefs or even just comments would be more illuminating, IMO.)

That said, RPYSize(3) is a distinct concept from SpaceDimension(also 3) and the two should not be collapsed here. There are many ways to represent 3d orientation using varied numbers of scalars (quaternion=4, rotation matrix=9, rpy=3).

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 80 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjClpFqP4LjynLBb0:-KMUjClpFqP4LjynLBb1:-1331292315) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/joints/QuaternionFloatingJoint.h#L80)):*
> ```objc
> 
>     Eigen::Matrix<Scalar, 4, 1> quattilde;
>     typename drake::math::Gradient<Eigen::Matrix<Scalar, 4, 1>,
> ```

BTW, `Vector4<Scalar>`

---

*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjTqrtE3G6znbZvCF:-KMUjTqrtE3G6znbZvCG:2103313204) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L29)):*
> ```objc
>     auto pos = q.template middleRows<drake::kSpaceDimension>(0);
>     auto rpy =
>         q.template middleRows<drake::kSpaceDimension>(drake::kSpaceDimension);
> ```

`kRpySize`

---

*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjb0Wk_tEQUH1uJiZ:-KMUjb0XXt7eVkrhQyrw:-623994123) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L46)):*
> ```objc
>     auto rpy =
>         q.template middleRows<drake::kSpaceDimension>(drake::kSpaceDimension);
>     Eigen::Matrix<Scalar, drake::kSpaceDimension, drake::kSpaceDimension> E;
> ```

`kRpySize` (several places and below)

---

*[drake/util/drakeGeometryUtil.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjiq0iGmjYxHT_YUY:-KMUjiq0iGmjYxHT_YUZ:2084596529) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L25)):*
> ```objc
> DRAKE_DEPRECATED("Use drake::kQuaternionSize instead.")
> const int QUAT_SIZE = 4;
> DRAKE_DEPRECATED("Use drake::kSpaceDimension instead.")
> ```

`"Use kRpySize instead"`

---

*[drake/util/drakeGeometryUtil.h, line 383 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjyu0A-tEXuxrZ2MT:-KMUjyu0A-tEXuxrZ2MU:2103313204) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L383)):*
> ```objc
> template <typename DerivedR, typename DerivedDR>
> typename drake::math::Gradient<
>     Eigen::Matrix<typename DerivedR::Scalar, drake::kSpaceDimension, 1>,
> ```

`kRpySize`

---

*[drake/util/drakeGeometryUtil.h, line 397 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUk3y2RByGpefzV84k:-KMUk3y2RByGpefzV84l:2103313204) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L397)):*
> ```objc
>   typedef typename DerivedR::Scalar Scalar;
>   typedef typename drake::math::Gradient<
>       Eigen::Matrix<Scalar, drake::kSpaceDimension, 1>,
> ```

`kRpySize`

---

*[drake/util/drakeGeometryUtil.h, line 399 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUk4jdhG032EwLw5HQ:-KMUk4jdhG032EwLw5HR:2103313204) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L399)):*
> ```objc
>       Eigen::Matrix<Scalar, drake::kSpaceDimension, 1>,
>       DerivedDR::ColsAtCompileTime>::type ReturnType;
>   ReturnType drpy(drake::kSpaceDimension, nq);
> ```

`kRpySize`

---

*[drake/util/drakeGeometryUtil.h, line 650 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUk9-V7gEPKj3XQCJI:-KMUk9-V7gEPKj3XQCJJ:208065212) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L650)):*
> ```objc
>       Scalar(1);
>   if (dphi) {
>     dphi->resize(phi.size(), drake::kSpaceDimension);
> ```

`kRpySize` and below

---

*[drake/util/drakeGeometryUtil.h, line 728 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUkFA7m48NzzMDbYl2:-KMUkFA7m48NzzMDbYl3:208065212) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L728)):*
> ```objc
>     const Eigen::MatrixBase<DerivedRPYdot>& rpydot,
>     Eigen::MatrixBase<DerivedOMEGA>& omega,
>     typename drake::math::Gradient<DerivedOMEGA, drake::kSpaceDimension,
> ```

`kRpySize` and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-:-KMUkfkCe40xc6DkE49W:-1880647740)*

**Comment by david-german-tri** [comment]
Review status: 4 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/common/constants.h, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUkRf08XL0dwxyqyER:-KMV8LjG3FFDu04HmkIN:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1fef1d76a248be341724950bd015f4bda260c75d/drake/common/constants.h#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `constexpr int kRpySize = 3;`
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 399 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUgnIBFILoqcEGAXUD:-KMV8MZeRl20o_SjaTT8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/RigidBodyTree.h#L399)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> (For the record, I don't think these constants are helpful at all. Typedefs or even just comments would be more illuminating, IMO.)
> 
> That said, RPYSize(3) is a distinct concept from SpaceDimension(also 3) and the two should not be collapsed here. There are many ways to represent 3d orientation using varied numbers of scalars (quaternion=4, rotation matrix=9, rpy=3).
</details>
Done.

---

*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjTqrtE3G6znbZvCF:-KMV8RgF-DuOMVmqNvWi:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize`
</details>
Done.

---

*[drake/systems/plants/joints/RollPitchYawFloatingJoint.h, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjb0Wk_tEQUH1uJiZ:-KMV8ST56eMbKhE25Buk:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/systems/plants/joints/RollPitchYawFloatingJoint.h#L46)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize` (several places and below)
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjiq0iGmjYxHT_YUY:-KMV8NM1-RrQuiNHKx6W:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `"Use kRpySize instead"`
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 383 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUjyu0A-tEXuxrZ2MT:-KMV8NpR9T55erF8T8QZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L383)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize`
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 397 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUk3y2RByGpefzV84k:-KMV8OPjxMhNASWUigjj:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L397)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize`
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 399 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUk4jdhG032EwLw5HQ:-KMV8OnbHoDDCTbj2Ma2:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L399)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize`
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 650 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUk9-V7gEPKj3XQCJI:-KMV8P_il2noPWDPFLd3:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L650)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize` and below
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 728 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-KMUkFA7m48NzzMDbYl2:-KMV8QNndkxJkxh4uSza:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15909550d85458542d3c56aba9bdadc6309b7c04/drake/util/drakeGeometryUtil.h#L728)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `kRpySize` and below
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2785)*

**Comment by david-german-tri** [comment]
Windows CI failures look like spurious infrastructure flakes - all the tests pass.

---

Review status: 4 of 8 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-:-KMVGmlg-H0aVQvkaPwF:-2128922243)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2785#-:-KMVW26Oz74iu2H08ARL:1417088721)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
LGTM.

**Pull request merged**
