### PR TITLE
[doc] Remove "newly bound" itemization

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18523)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
This change in documentation represents a change in policy, right? My best understanding from my most recent release experience is that the "newly bound" was for the bindings that got introduced "out of phase" with the C++. We're no longer doing that, as a rule (but are free to call out new bindings if they are particularly of interest)?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18523#-:-NKtb2Em0yXd2f3zEUvk:b-qqede4)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by jwnimmer-tri** [comment]
I retooled this a bit.  We want the PR numbers in the notes, we just don't want to make anyone itemize function and class names.  So, it goes back to working like any other PR, where we just put the commit subject line into the notes.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.
+@rpoyner-tri for platform review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Does the `release_playbook.md` file need to be updated? It has the phrase:

> In general you should mention new bindings and deprecated/removed classes and methods using their exact name...

While the *point* of the comment is to emphasize "exact name", the reference to "new bindings" implies that they *should* be itemized.

:LGTM:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18523#-:-NKxQ76pE4bdZdanG4Rt:b-kamvf7)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18523#-:-NKyADk9E0auCyEBm1BJ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18523)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
