### PR TITLE
Fix install with new bazel 0.5.3

### PR DESCRIPTION
**Pull request by fbudin69500**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6736)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqTStAl1hk9QUy_g5-H:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736)*

**Comment by soonho-tri** [comment]
I have the following problem on my local mac. FYI, this is not something introduced by this PR. But I expected that it's resolved by this PR but it's not the case:

```
INFO: Found 105 targets and 265 test targets...
FAIL: //drake/common:resource_tool_installed_test (see /private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/execroot/drake/bazel-out/osx-dbg/testlogs/drake/common/resource_tool_installed_test/test.log).
INFO: From Testing //drake/common:resource_tool_installed_test:
==================== Test output for //drake/common:resource_tool_installed_test:
[Installing] libexec/drake/drake/common/resource_tool
Traceback (most recent call last):
  File "drake/common/install", line 81, in <module>
    main(sys.argv[1:])
  File "drake/common/install", line 75, in main
    install("drake/common/resource_tool", "libexec/drake/drake/common/resource_tool")
  File "drake/common/install", line 47, in install
    shutil.copy2(src, dst_full)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'drake/common/resource_tool'
E
======================================================================
ERROR: test_install_and_run (__main__.TestResourceTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/bazel-sandbox/5978266533241409104/execroot/drake/bazel-out/osx-dbg/bin/drake/common/resource_tool_installed_test.runfiles/drake/drake/common/test/resource_tool_installed_test.py", line 15, in test_install_and_run
    os.path.abspath("tmp"),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['drake/common/install', '/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/bazel-sandbox/5978266533241409104/execroot/drake/bazel-out/osx-dbg/bin/drake/common/resource_tool_installed_test.runfiles/drake/tmp']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 1 test in 0.050s

FAILED (errors=1)
================================================================================
INFO: Elapsed time: 0.605s, Critical Path: 0.29s
//drake/common:resource_tool_installed_test                              FAILED in 0.3s
  /private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/execroot/drake/bazel-out/osx-dbg/testlogs/drake/common/resource_tool_installed_test/test.log
```

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqTYSHjEsGkHGKB0Bbe:bfkidei)*

**Comment by soonho-tri** [comment]
oh.. wait. I might run it with a wrong PR. Retesting it now..

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqTahANaPf7barSUxl0:b-ptrhkj)*

**Comment by soonho-tri** [comment]
OK. I'm happy to report that it actually fixed my PR.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqTbW0JI9V_Uf-mGwJ-:bhxkfmq)*

**Comment by jwnimmer-tri** [comment]
It seems like the change to spellings of `load` is to work around a possible Bazel bug.  Can you please be sure to file that upstream?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqTkybrXHY089-fLzcP:-KqTkybrXHY089-fLzcQ:b-phy5f2) (no related file):*
My read of the commit message is that the bug is only with `install.bzl` (and maybe `check_licenses`?).  This PR changes _all_ load statements in files that have `install.bzl` rules.  If that's what we want then so be it, but then _all_ `BUILD` files in tree should switch to that style, for consistency -- not just ones that mentioned `install.bzl`.  Alternatively, only the relevant `load` statements could be changed, so that we have per-bzl consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqTl-kAw8Ub1eTaDuIa:bqnspk2)*

**Comment by fbudin69500** [comment]
The problem has been reported here:
https://groups.google.com/forum/#!topic/bazel-discuss/7ZCPvG3pXns

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqTkybrXHY089-fLzcP:-KqUl-7xkqVWFBJTcLNH:b-ya16li) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My read of the commit message is that the bug is only with `install.bzl` (and maybe `check_licenses`?).  This PR changes _all_ load statements in files that have `install.bzl` rules.  If that's what we want then so be it, but then _all_ `BUILD` files in tree should switch to that style, for consistency -- not just ones that mentioned `install.bzl`.  Alternatively, only the relevant `load` statements could be changed, so that we have per-bzl consistency.
</blockquote></details>

The load statements of files that are used in `@drake`and outside should have their workspace-qualified path, otherwise they are loaded twice and seen as different files by bazel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqUkrcTRvquMegHUjDH:b-lcbzf7)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqTkybrXHY089-fLzcP:-KqUphJ-xhTIwJJy4XA_:b61b9go) (no related file):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

The load statements of files that are used in `@drake`and outside should have their workspace-qualified path, otherwise they are loaded twice and seen as different files by bazel.
</blockquote></details>

Let me be more specific, by way of example.  In `drake/bindings/BUILD` this PR changes the spelling of the `load` path as  `@drake//tools:mosek.bzl`, but leaves `drake/solvers/BUILD` spelling unchanged.  Why should this PR leave the two spellings inconsistent?  Same for `lint.bzl`, etc. etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqTkybrXHY089-fLzcP:-KqUu4E7vEOEyquZzvIP:b4ybwvh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Let me be more specific, by way of example.  In `drake/bindings/BUILD` this PR changes the spelling of the `load` path as  `@drake//tools:mosek.bzl`, but leaves `drake/solvers/BUILD` spelling unchanged.  Why should this PR leave the two spellings inconsistent?  Same for `lint.bzl`, etc. etc.
</blockquote></details>

... or in other words, this PR seems to imply a convention of _"If a BUILD file mentions install.bzl, then all of its load statements should be `@drake` prefixed"_.  I think that is a difficult convention for developers to follow.

Easier conventions to follow would be:
(1) "install.bzl" must always be drake-prefixed (but not other bzl files); or
(2) all load statements in the whole project must always be drake-prefixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736)*

**Comment by fbudin69500** [comment]
Review status: 4 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqTkybrXHY089-fLzcP:-KqYRW5bigUh0xmMSTma:b-g2uuyw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... or in other words, this PR seems to imply a convention of _"If a BUILD file mentions install.bzl, then all of its load statements should be `@drake` prefixed"_.  I think that is a difficult convention for developers to follow.

Easier conventions to follow would be:
(1) "install.bzl" must always be drake-prefixed (but not other bzl files); or
(2) all load statements in the whole project must always be drake-prefixed.
</blockquote></details>

That's correct. I updated the code to follow 1).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/BUILD, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqYS2RAhS6B43dR_uM9:-KqYS2RBBVIcZ4qU66O-:b6acwk8) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4a3bd22677898cd5a191d658a4b602c7e162e/drake/common/BUILD#L5)):*
> ```Python
> 
> load(
>     "@drake//tools:drake.bzl",
> ```

This change is a straggler?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqYS9_fA7wwCx4RNX9Y:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/BUILD, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-KqYS2RAhS6B43dR_uM9:-KqYT9vD0URsvta-ArpR:b-e5857g) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4a3bd22677898cd5a191d658a4b602c7e162e/drake/common/BUILD#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This change is a straggler?
</blockquote></details>

Yes, just updated that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736)*

**Comment by fbudin69500** [comment]
+@seancurtis-tri  Plateform review please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqYTOtIsH868ekikasU:bhrkjav)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@ggould-tri for final platform review.

---

Reviewed 3 of 12 files at r1, 1 of 1 files at r2, 8 of 9 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqYX4N00Qe1-YeUulqq:bfla94a)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6736#-:-KqYz5eaKwRg-rXvBdsV:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For posterity, the Bazel upstream issue here was https://github.com/bazelbuild/bazel/issues/3115.

**Pull request merged**
