### PR TITLE
[hydroelastic] Modify contact surface visualization LCM

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This changes the representation of a mesh in the contact surface lcm message. This change makes it forward compatible with when we want to render polygonal meshes. It leads to the removal of a custom triangle
message for contact surfaces.

The various call sites that are responsible for generating such a message have been updated to write to the new format. Incidentally, various variable names (e.g., msg) that were *not* styleguide compliant have been
updated to remove the bad abbreviation.

The `drake_visualizer` plugin has been likewise modified to handle the new representation. In addition, how it handles drawing edges on the contact surface has been streamlined (it uses VTK functionality for drawing
hidden line objects instead of creating multiple meshes).

Relates #15796

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102#-:-Mocxm0f6x4BEYI7lFHD:b-bpi9p7)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a few minor things. Passing the mesh instead of broken triangles is much better!

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102#-:-MoeNYaOD_xt-WkJoiWi:b-dg8fz6)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[examples/scene_graph/simple_contact_surface_vis.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeKDKM2H0sUME2jAI0:-MoeKDKNEyewV_2EsTaL:bctyoke) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5fbf929f1eb1e439c70db22bd3a5b3ab13a523/examples/scene_graph/simple_contact_surface_vis.cc#L239)):*
> ```cpp
>           msg.hydroelastic_contacts[i];
> 
>       // We'll simulate MbP's model instance/body paradigm. We have a look up
> ```

BTW, why is this comment deleted? It still seems relevant.
___
*[lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Mody4qo62WpBA3mnaOw:-Mody4qpDCAajCWKlZoF:b77aek2) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L44)):*
> ```
>   double moment_C_W[3];
> 
>   // The number of quadrature points. The number of quadrature points can vary
> ```

BTW, perhaps worth mentioning this is the total number of quadrature points. The second sentence led me to believe that this is number quadrature points per face for a second.
___
*[multibody/plant/contact_results_to_lcm.cc, line 150 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Modz1af349Ek9qIXPJy:-Modz1af349Ek9qIXPJz:bork45n) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/contact_results_to_lcm.cc#L150)):*
> ```cpp
> namespace {
> 
> // Writes a Vector3<T> to an array of doubles (with a converstion to double as
> ```

nit, s/converstion/conversion.
___
*[multibody/plant/contact_results_to_lcm.cc, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-ModznkM3shOv8xuTyFg:-ModznkM3shOv8xuTyFh:bzdq4bs) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/contact_results_to_lcm.cc#L168)):*
> ```cpp
>   const auto& contact_results =
>       get_contact_result_input_port().template Eval<ContactResults<T>>(context);
>   // TODO(SeanCurtis-TRI): Here, and below, the abbreviation "msg" is not
> ```

BTW, since you are already doing the good deed of cleaning up, why not clean this one up as well?
Seems like a find and replace "msg"->"message" and removing the TODO is enough.
___
*[multibody/plant/contact_results_to_lcm.cc, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Moe0jy27TGSGnIk6K3h:-Moe0jy27TGSGnIk6K3i:bjxhi5k) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/contact_results_to_lcm.cc#L199)):*
> ```cpp
>   // Here we enable the standard triangulated contact patches, so the unit
>   // test //multibody/plant:contact_results_to_lcm_test can pass.
>   // However, you might want to switch `#if 1` to `#if 0` when visualizing
> ```

I wasn't too thrilled to read this, but then I realize this is probably a stale comment.
___
*[multibody/plant/test/contact_results_to_lcm_test.cc, line 697 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeBNuQ4WONFMtdDfm_:-MoeBNuQ4WONFMtdDfma:b-80a9n8) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/test/contact_results_to_lcm_test.cc#L697)):*
> ```cpp
>     // [3, i0, i1, i2] in the face data. Confirm size and contents. */
>     EXPECT_EQ(pair_message.poly_data_int_count, mesh.num_triangles() * 4);
>     EXPECT_EQ(pair_message.poly_data.size(), mesh.num_triangles() * 4);
> ```

BTW, unexpected choice of EXPECT_EQ and ASSERT_EQ below. I would expect them to be swapped (i.e. assert here and expect in the loop). Could you explain?
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeMwKQCZdP5dsegBoS:-MoeMwKQCZdP5dsegBoT:bykqwlu) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1152)):*
> ```Python
>             poly_indices = itertools.islice(surface.poly_data,
>                                             i, i + vertex_count)
>             poly_indices = surface.poly_data[i:i + vertex_count]
> ```

What's wrong with just using this line and getting rid of the line with `itertools`?
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeEFxV-9ODXAlybSYe:-MoeEFxV-9ODXAlybSYf:be1wjqx) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
> ```Python
>         vtk_polydata = vtk.vtkPolyData()
>         vtk_polydata.SetPoints(vnp.getVtkPointsFromNumpy(p_WVs))
>         vtk_polydata.SetPolys(vtk_polys)
> ```

BTW, VTK can handle heterogeneous collection of polygons just fine, right?
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Modx_J5BLrWQFzliTh_:-Modx_J5BLrWQFzliTha:b95tw7c) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5fbf929f1eb1e439c70db22bd3a5b3ab13a523/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L83)):*
> ```cpp
>   BindCppSerializer<drake::lcmt_header>("drake");
>   BindCppSerializer<drake::lcmt_hydroelastic_contact_surface_for_viz>("drake");
>   BindCppSerializer<drake::lcmt_hydroelastic_contact_surface_tri_for_viz>(
> ```

So much I still don't know about python binding, but this is one fewer item today.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for platform review, per schedule.

+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102#-:-Mof-Z7996K6WwWueJUZ:bvu816g)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[examples/scene_graph/simple_contact_surface_vis.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeKDKM2H0sUME2jAI0:-Moew2Bu0fbbvoEQ56V4:b34rcdj) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5fbf929f1eb1e439c70db22bd3a5b3ab13a523/examples/scene_graph/simple_contact_surface_vis.cc#L239)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why is this comment deleted? It still seems relevant.
</blockquote></details>

Done

A bit too much hack and slash there.
___
*[lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Mody4qo62WpBA3mnaOw:-MoewR7sDooW_8Q5rzpH:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, perhaps worth mentioning this is the total number of quadrature points. The second sentence led me to believe that this is number quadrature points per face for a second.
</blockquote></details>

Done
___
*[multibody/plant/contact_results_to_lcm.cc, line 150 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Modz1af349Ek9qIXPJy:-MoewVNi4NIPXtNef9nZ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/contact_results_to_lcm.cc#L150)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, s/converstion/conversion.
</blockquote></details>

Done
___
*[multibody/plant/contact_results_to_lcm.cc, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-ModznkM3shOv8xuTyFg:-MoewgiP6e3BxJZLuDSn:btv764g) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/contact_results_to_lcm.cc#L168)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, since you are already doing the good deed of cleaning up, why not clean this one up as well?
Seems like a find and replace "msg"->"message" and removing the TODO is enough.
</blockquote></details>

Done

particularly since I did it elsewhere.
___
*[multibody/plant/contact_results_to_lcm.cc, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-Moe0jy27TGSGnIk6K3h:-MoewmZv5lkm9uFn8zrZ:bhbymro) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/contact_results_to_lcm.cc#L199)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I wasn't too thrilled to read this, but then I realize this is probably a stale comment.
</blockquote></details>

Done

Yep. Stale.
___
*[multibody/plant/test/contact_results_to_lcm_test.cc, line 697 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeBNuQ4WONFMtdDfm_:-MoewxbM6MePAZoudILR:b-of6o6r) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/test/contact_results_to_lcm_test.cc#L697)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, unexpected choice of EXPECT_EQ and ASSERT_EQ below. I would expect them to be swapped (i.e. assert here and expect in the loop). Could you explain?
</blockquote></details>

Done

I've unified them because asserts on sizes is a fine thing.

The significance of putting it in the for loop is the idea that if one is wrong, there's a high probability that they are *all* wrong. So, an `EXPECT` in a for loop that fails will spew a mount of spam to the log.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeMwKQCZdP5dsegBoS:-MoexkAf6tUjv7_beGKF:bb71nyg) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1152)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What's wrong with just using this line and getting rid of the line with `itertools`?
</blockquote></details>

Oops
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeEFxV-9ODXAlybSYe:-MoexNvS-T-jJ01NNuzb:b1g9j38) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, VTK can handle heterogeneous collection of polygons just fine, right?
</blockquote></details>

OK

Yep. You'll notice the line `vtk_polys.InsertNextCell(vertex_count, poly_indices)` where for each "cell" (aka face) we explicitly declare the number of vertices it has.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[multibody/plant/test/contact_results_to_lcm_test.cc, line 697 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeBNuQ4WONFMtdDfm_:-MofANBo1C-h_nD8GO32:b-lt0lzb) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/multibody/plant/test/contact_results_to_lcm_test.cc#L697)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

I've unified them because asserts on sizes is a fine thing.

The significance of putting it in the for loop is the idea that if one is wrong, there's a high probability that they are *all* wrong. So, an `EXPECT` in a for loop that fails will spew a mount of spam to the log.
</blockquote></details>

I see, makes sense!
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoeEFxV-9ODXAlybSYe:-MofAldW2bVfKmMuEOzP:bzftu3a) ([raw file](https://github.com/robotlocomotion/drake/blob/6b7f5acb1e7e511006e7e0ef22e31c2ba113f7cb/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

OK

Yep. You'll notice the line `vtk_polys.InsertNextCell(vertex_count, poly_indices)` where for each "cell" (aka face) we explicitly declare the number of vertices it has.
</blockquote></details>

Sweet!
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MofASzX96BIrAJIHYU3:-MofASzX96BIrAJIHYU4:b9ivucj) ([raw file](https://github.com/robotlocomotion/drake/blob/374a42e2b1fee2cff5638e00ae89a9ebf070ea74/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L3)):*
> ```Python
> # Note that this script runs in the main context of drake-visualizer,
> # where many modules and variables already exist in the global scope.
> import itertools
> ```

nit, not needed anymore.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, with minor nit - nice!

> Reviewed 5 of 10 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102#-:-MoiuUd_By22bIljKqk3:b-ci61mt)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, line 50 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoisVo6-S2IdS5BfvMe:-MoisVo78kIM2IhB7uVf:b4f7fb5) ([raw file](https://github.com/robotlocomotion/drake/blob/a5aa604bd5b7d27b9e99acbf0800501e9ec626e6/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L50)):*
> ```
>   int32_t num_quadrature_points;
> 
>   // The quadrature point data. No assumptions are made about which points are
> ```

nit Sorry for being naive, but I don't understand why having no assumptions is a good thing.

Is the association stored elsewhere?
Or does it really need no association? I assume that this is case - if so, can you add this to your text?,e.g.
```
// No assumptions are made about which points are
// associated with which polygons, because no association is needed.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, line 50 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoisVo6-S2IdS5BfvMe:-Moiv88W6ubHQxyuyfol:bgu77ki) ([raw file](https://github.com/robotlocomotion/drake/blob/a5aa604bd5b7d27b9e99acbf0800501e9ec626e6/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Sorry for being naive, but I don't understand why having no assumptions is a good thing.

Is the association stored elsewhere?
Or does it really need no association? I assume that this is case - if so, can you add this to your text?,e.g.
```
// No assumptions are made about which points are
// associated with which polygons, because no association is needed.
```
</blockquote></details>

I can see why you'd request that, but I'm a bit wary. The current statement represents a fact and a minimum contract. No associations are promised. It seems providing a justification for that (not needed) makes it stricter without providing much benefit.

You are correct in your surmise that visualization doesn't require association (it just uses it to draw a bunch of vectors and doesn't care about the association -- the position of the vectors implicitly illustrates the actual association).

The true answer is, there is a correlation. The quadrature points are enumerated in sequence, ordered in the same order as the elements. But, generally, we can't provide a closed-form equation (e.g., j = 3 *i + 1) to define that relationship because, ultimately, the number of points per element *may be variable*.

So, rather than state the whys and whatfors, I just wanted to make it clear that people shouldn't rely on it.

Thoughts?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, line 50 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoisVo6-S2IdS5BfvMe:-Moj2G8P1yFsKNIWj0ry:b-oa4e2f) ([raw file](https://github.com/robotlocomotion/drake/blob/a5aa604bd5b7d27b9e99acbf0800501e9ec626e6/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L50)):*
I'm inclined to simply remove the sentence. Just a few lines up it says:

> There is no guaranteed pattern of correspondence between the ith quadrature point and the jth mesh face.

So, this sentence (used to replace a statement that was simply no longer true), can simply be excised. Removal would have been better than replacement.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, line 50 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MoisVo6-S2IdS5BfvMe:-Moj3_FJ5hDhkEutBxJv:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/a5aa604bd5b7d27b9e99acbf0800501e9ec626e6/lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm#L50)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm inclined to simply remove the sentence. Just a few lines up it says:

> There is no guaranteed pattern of correspondence between the ith quadrature point and the jth mesh face.

So, this sentence (used to replace a statement that was simply no longer true), can simply be excised. Removal would have been better than replacement.
</blockquote></details>

OK Sounds good!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16102)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @SeanCurtis-TRI)

**Comment by DamrongGuoy** [comment]
___
*[examples/scene_graph/simple_contact_surface_vis.cc, line 237 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16102#-MokIVC6BzVMwvMJ0Ifk:-MokIVC6BzVMwvMJ0Ifl:b-zci0xp) ([raw file](https://github.com/robotlocomotion/drake/blob/331b4d060261146b9f245c1f323cb50f16983cae/examples/scene_graph/simple_contact_surface_vis.cc#L237)):*
> ```cpp
>     message.hydroelastic_contacts.resize(num_surfaces);
>     for (int i = 0; i < num_surfaces; ++i) {
>         lcmt_hydroelastic_contact_surface_for_viz& surface_message =
> ```

Unfortunately, I've just looked at this PR after it's merged. This body of `for` loop introduced `4-space` indent instead of 2-space.

Please let me know if you'd like me to fix it.

**Pull request merged**
