### PR TITLE
Make soft half space/rigid mesh differentiable

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. Modifications to the underlying algorithm
   TODO: Elaborate
2. Addition to unit tests to assess the quality of the derivatives.

TODO:
 - Do the same for rigid half space and soft mesh.
 - Do the same for rigid/soft meshes
 - Fix the logic in hydroelastic callback to let them through.
 - Add characterization/support matrix in query_object.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
@hongkai, I'd appreciate it if you'd look at the *unit tests* in this to check my methodology. This is now "complete" and as I move to other components, I'm going to use this as a basis and I'd like to get feedback early. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836#-:-MWkqua113PyZkQBWIZm:brdbom8)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1058 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MWq8Ivw9cXpMpOeTtB_:-MWq8Ivw9cXpMpOeTtBa:b-fsa0us) ([raw file](https://github.com/robotlocomotion/drake/blob/ad0489f74bb3eeea20b623be72dc8816149f3134/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1058)):*
> ```cpp
>                                              double)>& evaluate_quantity,
>                                              bool diff_wrt_position = true) {
>     for (const double theta :
> ```

Better to document what "theta" is. I believe it is the angle between the mesh `abdc` and the outward normal `n`.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MWqAWPsDmZwHyqyDIq_:-MWqAWPsDmZwHyqyDIqa:b-zevqt0) ([raw file](https://github.com/robotlocomotion/drake/blob/ad0489f74bb3eeea20b623be72dc8816149f3134/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1136)):*
> ```cpp
>     for (VIndex i(0); i < mesh_W.num_vertices(); ++i) {
>       const Vector3<AutoDiffXd>& p_WV = mesh_W.vertex(i).r_MV();
>       if (p_WV.z().value() > -kEps) {
> ```

So the vertices `a` and `b` that are outside the halfspace will be characterized as surface point? Why not to check if the absolute value of p_WV.z().value() is less than eps?

**Review by SeanCurtis-TRI — COMMENTED** [review]
@hongkai-dai So, the big question is this:

I'm using some simple scenarios so that the derivatives are easy to reason about (simple mesh, doing work in, essentially, the half space's frame, only differentiating w.r.t. Ro or theta independently). Those tests all pass. So, what is the probability that given *those* passing tests, that uglier bugs are still hiding? 

Certainly, I believe you can call out anything obvious that I've missed (because I'm certainly willing to believe that I could miss something obvious). And there may also be something subtle. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836#-:-MWyLlmc87bEGYOHxe_p:b-12kweb)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MWqAWPsDmZwHyqyDIq_:-MWyLdxeAw5JWLUsFeQl:b-wxy3hz) ([raw file](https://github.com/robotlocomotion/drake/blob/ad0489f74bb3eeea20b623be72dc8816149f3134/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1136)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

So the vertices `a` and `b` that are outside the halfspace will be characterized as surface point? Why not to check if the absolute value of p_WV.z().value() is less than eps?
</blockquote></details>

By definition, points of the original mesh that are *outside* the half space cannot be part of the contact surface. That mesh gets clipped. Obviously, I should clarify the documentaiton.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1058 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MWq8Ivw9cXpMpOeTtB_:-MWyzDbg3-pyoPfIuBYU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad0489f74bb3eeea20b623be72dc8816149f3134/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1058)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Better to document what "theta" is. I believe it is the angle between the mesh `abdc` and the outward normal `n`.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MWqAWPsDmZwHyqyDIq_:-MX31jTMAaEOoTGUqk7I:b-rokd78) ([raw file](https://github.com/robotlocomotion/drake/blob/ad0489f74bb3eeea20b623be72dc8816149f3134/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1136)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

By definition, points of the original mesh that are *outside* the half space cannot be part of the contact surface. That mesh gets clipped. Obviously, I should clarify the documentaiton.
</blockquote></details>

I see, I didn't realize mesh_W only contains the vertices within the halfspace. I don't think documentation is needed here, as `mesh_W` is created from `contact_surface`.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX32YM7BnZmJdtHR3uk:-MX32YM8EbcAqk2sGgEo:bpl85ta) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1202)):*
> ```cpp
>    > 3 vertices, it becomes a (non-trivial) weighted combination of the
>          vertex positions. */
>   enum Category { kOriginal, kSurface, kCentroid };
> ```

I think the word `surface` is overloaded. Here it means the surface of the halfspace, but in the `CategorizeVertices` function, the first input argument is also named `surfaces`, but means the contact surface, i.e., the surface of the intersection region between the mesh and the halfspace. I would suggest to rename the variable `surfaces` as `contact_surfaces`.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX3DSNb-g3KbyidxtF5:-MX3DSNb-g3KbyidxtF6:b-5tuty4) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1209)):*
> ```cpp
>   struct VertexData {
>     Category category;
>     std::variant<int, Vector3<double>, std::set<SurfaceVertexIndex>> data;
> ```

Instead of using dummy int value, how about using `std::nullopt_t`?
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1291 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX3mPq71X2RM3AiWnDs:-MX3mPq71X2RM3AiWnDt:b-64eyyj) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1291)):*
> ```cpp
>      2. Surface vertices
>         - We'll examine ∂v/∂Ro component wise.
>           - ∂v/∂Ro.x = [1, 0, -p.x] (see Equation (1) below)
> ```

I am not entirely sure why the gradient of v.z w.r.t Ro.x is non-zero. As far as I can see, v.z is always zero (because v is on the surface of the halfspace), hence its gradient should also be 0.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX42UIf9oS-enH5iK5P:-MX42UIf9oS-enH5iK5Q:b4nd3mo) (no related file):*
@hongkai-dai Thanks for the comments on the small details. I'm going to put the big question in its own comment thread here so it doesn't get missed:

I'm using some simple scenarios so that the derivatives are easy to reason about (simple mesh, doing work in, essentially, the half space's frame, only differentiating w.r.t. Ro or theta independently). Those tests all pass. So, what is the probability that given those passing tests, that uglier bugs are still hiding?

Certainly, I believe you can call out anything obvious that I've missed (because I'm certainly willing to believe that I could miss something obvious). And there may also be something subtle.

---
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MWqAWPsDmZwHyqyDIq_:-MX42RIzA88nFBNNPS1I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad0489f74bb3eeea20b623be72dc8816149f3134/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1136)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, I didn't realize mesh_W only contains the vertices within the halfspace. I don't think documentation is needed here, as `mesh_W` is created from `contact_surface`.
</blockquote></details>

Done.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX32YM7BnZmJdtHR3uk:-MX42AMD30xXOGzglI5C:b-2k9eeu) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1202)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the word `surface` is overloaded. Here it means the surface of the halfspace, but in the `CategorizeVertices` function, the first input argument is also named `surfaces`, but means the contact surface, i.e., the surface of the intersection region between the mesh and the halfspace. I would suggest to rename the variable `surfaces` as `contact_surfaces`.
</blockquote></details>

Good point. I'll revisit this.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX3DSNb-g3KbyidxtF5:-MX425xD-PPks-vvsfIG:bfbqy49) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1209)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Instead of using dummy int value, how about using `std::nullopt_t`?
</blockquote></details>

I generally hate dummy values....I don't see one is particularly better than another.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1291 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX3mPq71X2RM3AiWnDs:-MX41ovg0wLwJiE7tW1_:b-xxlnnn) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1291)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not entirely sure why the gradient of v.z w.r.t Ro.x is non-zero. As far as I can see, v.z is always zero (because v is on the surface of the halfspace), hence its gradient should also be 0.
</blockquote></details>

oops. backwards notation. What this should be is:

`∂v.x/∂Ro`
`∂v.y/∂Ro`
`∂v.z/∂Ro`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @hongkai-dai and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX42UIf9oS-enH5iK5P:-MX4I71wEbQ1x4uwUX3k:b-kxdiow) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@hongkai-dai Thanks for the comments on the small details. I'm going to put the big question in its own comment thread here so it doesn't get missed:

I'm using some simple scenarios so that the derivatives are easy to reason about (simple mesh, doing work in, essentially, the half space's frame, only differentiating w.r.t. Ro or theta independently). Those tests all pass. So, what is the probability that given those passing tests, that uglier bugs are still hiding?

Certainly, I believe you can call out anything obvious that I've missed (because I'm certainly willing to believe that I could miss something obvious). And there may also be something subtle.
</blockquote></details>

As we discussed on slack, it might make sense to tilt the halfspace, such that it is not horizontal. Currently some of the gradient is zero (like the gradient of the surface vertex z height w.r.t the x/y position of the mesh). If we tilt the halfspace we should expect non-zero gradient.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 1202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14836#-MX32YM7BnZmJdtHR3uk:-MX4EDyf4G8_2r0T4zPJ:b-dajhv8) ([raw file](https://github.com/robotlocomotion/drake/blob/7573fbab36182a78240aa6fca9f61c8bf96cad10/geometry/proximity/test/mesh_half_space_intersection_test.cc#L1202)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Good point. I'll revisit this.
</blockquote></details>

I went with `kIntersection`.

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai as a formal annotation of the current, nominal reviewer (of just the tests?).  Feel free to add and/or reassign people as the PR evolves.

**Review by SeanCurtis-TRI — COMMENTED** [review]
No need. This PR has served its purpose. Confidence about the level of test coverage that is appropriate. I need to make sure this approach works in the larger context, so I'm going to close this for now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14836#-:-MXCc08WEDevpEi4Ptpo:b4wfm14)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Pull request closed without merging**
