### PR TITLE
Upgrade to Mosek 8.1.0.51

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jamiesnape for feature review please.
+@jwnimmer-tri for platform review please.
@drake-jenkins-bot @drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[solvers/test/quadratic_program_examples.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxQDfT-UnU1Yjbio4m:-LAxQDfT-UnU1Yjbio4n:bxel82r) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/solvers/test/quadratic_program_examples.cc#L122)):*
> ```cpp
>     tol = 1E-8;
>   } else if (solver_type == SolverType::kMosek) {
>     tol = 3E-5;
> ```

To reviewers: Mosek 8 has lower accuracy on this particular small optimization problem. I asked Mosek authors, and they confirmed it.

---

*[tools/workspace/mosek/repository.bzl, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxQRRMECTQuOxs6vw-:-LAxQRRMECTQuOxs6vw0:b-wjftvy) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/workspace/mosek/repository.bzl#L31)):*
> ```Python
>     mosek_minor_version = 1
>     mosek_patch_version = 0
>     mosek_idle_version = 51
> ```

To reviewer: how should I name the variable for `51` here? I thought a software release has major_version.minor_version.patch_version, but I am not sure what the final `51` is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673#-:-LAxQ5LJ5c6bQGX61lCV:bwry08m)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/workspace/mosek/repository.bzl, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxQRRMECTQuOxs6vw-:-LAxRvK36iq6ADYDXxEP:b-45sdst) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/workspace/mosek/repository.bzl#L31)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

To reviewer: how should I name the variable for `51` here? I thought a software release has major_version.minor_version.patch_version, but I am not sure what the final `51` is.
</blockquote></details>

"tweak" version.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/install/check_licenses.bzl, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxSLvB5vtkML_5PgHO:-LAxSLvB5vtkML_5PgHP:b-3wwi3n) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/install/check_licenses.bzl#L11)):*
> ```Python
>     "Copyright.txt",  # vtk
>     "EULA.pdf",  # gurobi
>     "mosek-eula.pdf",  # mosek
> ```

BTW alphabetize list

---

*[tools/workspace/mosek/repository.bzl, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxT1XjDD84Z0ualrX6:-LAxT1XjDD84Z0ualrX7:b9tmk5u) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/workspace/mosek/repository.bzl#L58)):*
> ```Python
> 
>         files = [
>             "bin/libscilkrts.5.dylib",
> ```

`bin/libcilkrts.5.dylib`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[doc/bazel.rst, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxTFvj-HMMLssCkrDR:-LAxTFvj-HMMLssCkrDS:brpbugh) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/doc/bazel.rst#L177)):*
> ```reStructuredText
> 
> MOSEK 8.1.0.51
> ---------
> ```

Extend underline (or just say 8.1 depending on how significant the tweak really is).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot @drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/bazel.rst, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxTFvj-HMMLssCkrDR:-LAxU9iC57v7le2gcHk0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/doc/bazel.rst#L177)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Extend underline (or just say 8.1 depending on how significant the tweak really is).
</blockquote></details>

Done.

---

*[tools/install/check_licenses.bzl, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxSLvB5vtkML_5PgHO:-LAxUJZY5sG0gSR12QC5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/install/check_licenses.bzl#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW alphabetize list
</blockquote></details>

Done.

---

*[tools/workspace/mosek/repository.bzl, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxQRRMECTQuOxs6vw-:-LAxUT2Y1YtmIuxLb9Yc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/workspace/mosek/repository.bzl#L31)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

"tweak" version.
</blockquote></details>

Done.

---

*[tools/workspace/mosek/repository.bzl, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxT1XjDD84Z0ualrX6:-LAxUX9A2D_pMP7rvQqf:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/tools/workspace/mosek/repository.bzl#L58)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`bin/libcilkrts.5.dylib`?
</blockquote></details>

Done. Oops!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673#-:-LAxVX0m-GoMeumA8E0x:bjezg61)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673#-:-LAxcfPi3eDJwazakorh:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tools/workspace/mosek/repository.bzl, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxl4USAw4ggFo_-XNv:-LAxl4USAw4ggFo_-XNw:b-s5aq7s) ([raw file](https://github.com/robotlocomotion/drake/blob/2396053f0c15dffda339346cd0e25a88982e190d/tools/workspace/mosek/repository.bzl#L60)):*
> ```Python
>         files = [
>             "bin/libcilkrts.5.dylib",
>             "bin/libiomp5.dylib",
> ```

No OpenMP anymore on Mac.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/mosek/repository.bzl, line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAylWw77PvbkqYmENzr:-LAylWw77PvbkqYmENzs:b-c4953x) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L86)):*
> ```Python
>         linkopts = [
>             "-L{}".format(bin_path),
>             "-liomp5",
> ```

Also need to remove this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/workspace/mosek/repository.bzl, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAyo8iU455EE8bGwvvo:-LAyo8iU455EE8bGwvvp:bemd7o4) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L91)):*
> ```Python
>     else:
>         files = [
>             "bin/libcilkrts.so.5",
> ```

Sorry, I am a bit slow on my email backlog.  It is not reasonable to install a solib that shadow's Ubuntu's built-in default library of the same soname.  Possibly we can do this PR as an interim step with a TODO and issue to resolve it properly later, but I'd rather prefer to dig into why Xenial's library doesn't work.  I will try to look into it more very soon.

What is the timeline / criticality of getting this PR onto master?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/mosek/repository.bzl, line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAylWw77PvbkqYmENzr:-LAyr1reDyzdeuYgE6XE:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L86)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Also need to remove this.
</blockquote></details>

Thanks!

---

*[tools/workspace/mosek/repository.bzl, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAyo8iU455EE8bGwvvo:-LAypmnp7GlFCzVT8GRH:b-9cmy8y) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sorry, I am a bit slow on my email backlog.  It is not reasonable to install a solib that shadow's Ubuntu's built-in default library of the same soname.  Possibly we can do this PR as an interim step with a TODO and issue to resolve it properly later, but I'd rather prefer to dig into why Xenial's library doesn't work.  I will try to look into it more very soon.

What is the timeline / criticality of getting this PR onto master?
</blockquote></details>

Thanks @jwnimmer-tri for looking into this problem!

I hope to bring this into Drake. Some code in my dev branch only works with Mosek 8, but not Mosek 7. These dev code is related to a paper, whose deadline is the end of May. Hopefully by then, we can have the code in master branch of drake.

Is it OK if we add the TODO here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
First pass complete.

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/test/quadratic_program_examples.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxQDfT-UnU1Yjbio4m:-LAyu5NlCEUraCUvEtif:btb9570) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/solvers/test/quadratic_program_examples.cc#L122)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

To reviewers: Mosek 8 has lower accuracy on this particular small optimization problem. I asked Mosek authors, and they confirmed it.
</blockquote></details>

I think that's worth adding as a comment here, so someone who comes later doesn't have to wonder why Mosek vs Gurobi are so at odds here.

---

*[tools/workspace/mosek/repository.bzl, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAyo8iU455EE8bGwvvo:-LAyuVRK8V5spaCF20Hz:b-kp7slh) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L91)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks @jwnimmer-tri for looking into this problem!

I hope to bring this into Drake. Some code in my dev branch only works with Mosek 8, but not Mosek 7. These dev code is related to a paper, whose deadline is the end of May. Hopefully by then, we can have the code in master branch of drake.

Is it OK if we add the TODO here?
</blockquote></details>

@jamiesnape can I ask for your thoughts here?

We have https://packages.ubuntu.com/xenial/amd64/libx32cilkrts5/filelist in Xenial which is the same as this, but for some reason Mosek gets SIGFPE when using Xenial's shared library.  Xenial's `libgcc-5-dev` depends on this library, which makes me especially hesitant to replace it.

Do we yet have or make binary packages that have Mosek enabled?  I assume not.  So I think the risks here are (1) for drake developers and (2) for drake users who build from source with Mosek enabled.

Maybe we should test runtime compatibility with some current Drake users' downstream test suites to see what risks there might be here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673#-:-LAyvuFW9X6QlY02npLp:bvb1a6z)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/test/quadratic_program_examples.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAxQDfT-UnU1Yjbio4m:-LAz75WAA8UpEPloL66q:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/7ce6738d97da4fced874ab5bf5ffaaf62d4c0810/solvers/test/quadratic_program_examples.cc#L122)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think that's worth adding as a comment here, so someone who comes later doesn't have to wonder why Mosek vs Gurobi are so at odds here.
</blockquote></details>

Done. Good call.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/mosek/repository.bzl, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAyo8iU455EE8bGwvvo:-LAzLP0Z8JxNKfhaSUQ5:b-xmkprh) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@jamiesnape can I ask for your thoughts here?

We have https://packages.ubuntu.com/xenial/amd64/libx32cilkrts5/filelist in Xenial which is the same as this, but for some reason Mosek gets SIGFPE when using Xenial's shared library.  Xenial's `libgcc-5-dev` depends on this library, which makes me especially hesitant to replace it.

Do we yet have or make binary packages that have Mosek enabled?  I assume not.  So I think the risks here are (1) for drake developers and (2) for drake users who build from source with Mosek enabled.

Maybe we should test runtime compatibility with some current Drake users' downstream test suites to see what risks there might be here?
</blockquote></details>

On further research, it looks like CILK is deprecated as of GCC 7, being removed as of GCC 8, and is not very widely used in general.  Furthermore, none of the Ubuntu software I currently have installed has any dependencies on libcilkrts.  So, I now think the risk here is rather low.  I am not even sure trying to debug it is worthwhile.

I am thinking that we instead somehow find a way to add a disclaimer somewhere warning users that we are shadowing Ubuntu's CILK (maybe as part of the install rule at runtime?) with MOSEK's copy, with appropriate comments in this file as well.

But I still want to hear @jamiesnape's opinion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/mosek/repository.bzl, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAyo8iU455EE8bGwvvo:-LB1AYUK7ZN2wwBCkvpS:bbb80bu) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L91)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I agree it is low risk.

One option is renaming `iomp5` and `cilkrts` libraries (do they really use both?) with a `drake_` prefix and patching the MOSEK library with `patchelf`, assuming the MOSEK EULA is not being violated (I doubt it). I would not block on that, however.

Cilk Plus is dead even according to Intel, removed from their compiler by 2020, so I am not too concerned about conflicts. `iomp5` could conflict the occasional LLVM and Intel compiler user, but chances are low there too (though increasing with respect to LLVM).
</blockquote></details>

Yes, I had also originally considered the rename, but given the new risk profile it seems not worth it.  Also, in the case where something else was using cilk with Drake, if both Ubuntu clik and Mosek cilk would still provide the same symbol names, seems like trading off one set of obscure runtime problems (incompatible solibs with identical sonames) for another (two distinct copies of the runtime loaded at once).

So I think for me to be satisfied here, I'll ask for a comment at this line, such as `# N.B. We are using and installing MOSEK's copy of libcilkrts.so.5, even though Ubuntu installs the same shared library by default on all systems already.  For some reason, Mosek fails when used with Ubuntu's shared library.  If Drake users have other third-party code that assumes use of Ubunut's libcilkrts, there could be runtime conflicts; however, this risk seems low.`.

---

*[tools/workspace/mosek/repository.bzl, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB1CcPEBAuOjGXqq5PT:-LB1CcPEBAuOjGXqq5PU:bgmhnn9) ([raw file](https://github.com/robotlocomotion/drake/blob/d44180133c9fa0dbb064e71ba80b6dc035fdcc7b/tools/workspace/mosek/repository.bzl#L135)):*
> ```Python
> install(
>    name = "install",
>    docs = ["mosek-eula.pdf"],
> ```

Hmm.  The libcilkrts license appears to be `"notice"`, but I don't see anywhere in the MOSEK tarball that is providing the notice (it does post the notice for zlib, but not the cilk runtime).  @jamiesnape Do you think its worth vendoring and then installing the Intel notice as part of this PR?  In practice since we don't do releases of this I think it doesn't matter, so maybe just a TODO reminder instead?  On the other hand, it wouldn't be difficult to add.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/mosek/repository.bzl, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LAyo8iU455EE8bGwvvo:-LB1tT0CDg35btLN7MCK:bnputky) ([raw file](https://github.com/robotlocomotion/drake/blob/2e3d9ebf88c75ff9a9531b61aa482084d8e7ebd3/tools/workspace/mosek/repository.bzl#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, I had also originally considered the rename, but given the new risk profile it seems not worth it.  Also, in the case where something else was using cilk with Drake, if both Ubuntu clik and Mosek cilk would still provide the same symbol names, seems like trading off one set of obscure runtime problems (incompatible solibs with identical sonames) for another (two distinct copies of the runtime loaded at once).

So I think for me to be satisfied here, I'll ask for a comment at this line, such as `# N.B. We are using and installing MOSEK's copy of libcilkrts.so.5, even though Ubuntu installs the same shared library by default on all systems already.  For some reason, Mosek fails when used with Ubuntu's shared library.  If Drake users have other third-party code that assumes use of Ubunut's libcilkrts, there could be runtime conflicts; however, this risk seems low.`.
</blockquote></details>

Done. Thanks

---

*[tools/workspace/mosek/repository.bzl, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB1CcPEBAuOjGXqq5PT:-LB1tUp492bz-GAPphYk:b-lnv8l7) ([raw file](https://github.com/robotlocomotion/drake/blob/d44180133c9fa0dbb064e71ba80b6dc035fdcc7b/tools/workspace/mosek/repository.bzl#L135)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> The OpenMP runtime has the same license.

Except start date is 1997.
</blockquote></details>

Sorry for being slow, but is there an example, on how to add the notice file, which is not included in tarball?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/mosek/repository.bzl, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB1CcPEBAuOjGXqq5PT:-LB1ulyH2jPvNlLWaK_L:b-esfnko) ([raw file](https://github.com/robotlocomotion/drake/blob/d44180133c9fa0dbb064e71ba80b6dc035fdcc7b/tools/workspace/mosek/repository.bzl#L135)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry for being slow, but is there an example, on how to add the notice file, which is not included in tarball?
</blockquote></details>

It looks like `tools/workspace/stx` is a good example.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB2-z-N1pkqjunOTyXG:-LB2-z-PCpNDuSChgYK9:bgvbmd9) (no related file):*
From local testing, we need this patch in order for the mosek install rule to operate correctly.
```patch
--- a/tools/workspace/mosek/BUILD.bazel
+++ b/tools/workspace/mosek/BUILD.bazel
@@ -5,4 +5,6 @@
 
 load("//tools/lint:lint.bzl", "add_lint_tests")
 
+exports_files(["cilkrts_notice", "openMP_notice"])
+
 add_lint_tests()
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/mosek/repository.bzl, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB1CcPEBAuOjGXqq5PT:-LB246EY8dszHGe7KFBg:bnti3q7) ([raw file](https://github.com/robotlocomotion/drake/blob/d44180133c9fa0dbb064e71ba80b6dc035fdcc7b/tools/workspace/mosek/repository.bzl#L135)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You may need to add a `doc_strip_prefix`. Are the files ending up in directly in `share/doc/mosek`? Also, looks like in similar circumstances we have called the files something like `share/doc/mosek/cilkplus/LICENSE` and `share/doc/mosek/openmp/LICENSE`.
</blockquote></details>

On Ubuntu, the install lookED like this, which seemed okay to me?
```
lib/libcilkrts.so.5
lib/libiomp5.so
lib/libmosek64.so.8.1
share/doc/mosek/mosek-eula.pdf
share/doc/mosek/cilkrts_notice
share/doc/mosek/openMP_notice
```
Or did you want them to end up in `share/doc/cilkplus` and such, Jamie?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/mosek/repository.bzl, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB1CcPEBAuOjGXqq5PT:-LB24mmT8R09JlIe-0CD:b-ek5ap) ([raw file](https://github.com/robotlocomotion/drake/blob/d44180133c9fa0dbb064e71ba80b6dc035fdcc7b/tools/workspace/mosek/repository.bzl#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On Ubuntu, the install lookED like this, which seemed okay to me?
```
lib/libcilkrts.so.5
lib/libiomp5.so
lib/libmosek64.so.8.1
share/doc/mosek/mosek-eula.pdf
share/doc/mosek/cilkrts_notice
share/doc/mosek/openMP_notice
```
Or did you want them to end up in `share/doc/cilkplus` and such, Jamie?
</blockquote></details>

If that is the case, it should be fine without the `doc_strip_prefix`. Maybe just rename the files LICENSE.{ClikPlus|OpenMP} or LICENSE_{ClikPlus|OpenMP} or similar and I will be happy (the original files in the source are called `LICENSE`, I think).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Oops, I forgot to :lgtm:.  I think this is ready, modulo small open discussions.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673#-:-LB2XesB3oy6UbCSR8Wk:b-ubatyr)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/mosek/repository.bzl, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8673#-LB1CcPEBAuOjGXqq5PT:-LB2YdDE23_oFbhTMXGP:bb30yak) ([raw file](https://github.com/robotlocomotion/drake/blob/d44180133c9fa0dbb064e71ba80b6dc035fdcc7b/tools/workspace/mosek/repository.bzl#L135)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

If that is the case, it should be fine without the `doc_strip_prefix`. Maybe just rename the files LICENSE.{ClikPlus|OpenMP} or LICENSE_{ClikPlus|OpenMP} or similar and I will be happy (the original files in the source are called `LICENSE`, I think).
</blockquote></details>

Done. Thanks for the help!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 6 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8673#-:-LB2qSDo-8jSOuIBpO4H:b-l70wzf)*

**Pull request merged**
