### PR TITLE
Fix some missing mathematicalprogram python bindings

### PR DESCRIPTION
**Pull request by rdeits**
~~Not ready for review yet; needs some more tests.~~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5389)

### CODE REVIEW

**Comment by rdeits** [comment]
+@hongkai-dai +@ggould-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-:-KeJfKCFjoqG8_rAMiO_:b-9xktg9)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-KeKNbIXVOx3K4qlDocL:-KeKNbIYzjxLyvO6sPEH:b-27e0d6) ([raw file](https://github.com/robotlocomotion/drake/blob/2997875b6428e53987db6a36e0cf077774645588/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L121)):*
> ```cpp
>          &MathematicalProgram::linear_equality_constraints)
>     .def("bounding_box_constraints",
>          &MathematicalProgram::bounding_box_constraints)
> ```

I don't see any test coverage of bounding box constraints below.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-KeKMZHtchpQmlZO8wfZ:-KeKMZHu18QDYNe1FFBf:bw8gk5f) ([raw file](https://github.com/robotlocomotion/drake/blob/2997875b6428e53987db6a36e0cf077774645588/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L169)):*
> ```cpp
>   // so we can use it in this file to indicate that the other constraint
>   // types inherit from it.
>   py::class_<Constraint, std::shared_ptr<Constraint> > constraint(
> ```

FYI the space between `>`s is no longer required in modern C++.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5389)*

**Comment by rdeits** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-KeKNbIXVOx3K4qlDocL:-KeKQ-UCznIuzo4txij7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2997875b6428e53987db6a36e0cf077774645588/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L121)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I don't see any test coverage of bounding box constraints below.
</blockquote></details>

Done.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-KeKMZHtchpQmlZO8wfZ:-KeKQ0HB6nvK6N-gg4NQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2997875b6428e53987db6a36e0cf077774645588/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L169)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI the space between `>`s is no longer required in modern C++.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5389)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-:-KeKS21gycoYXtLOWkD5:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5389#-:-KeKSc-2znRtZ2PR9ppB:bnfp4nl)*

**Pull request merged**
