### PR TITLE
Adds MBT/MBP support to the inverse dynamics controller.

### PR DESCRIPTION
**Pull request by edrumwri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9131)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I'm not 100% able to follow the above.  Do you to rename / deprecate / reuse both class InverseDynamics and class InverseDynamicsContoller, or just one of them?

In any case, you should be able to make a class with that name that offers the superset of both APIs, and then just calls the RBT or MBT code under the hood (each of which is in its own class).

**Comment by sherm1** [comment]
Ping -- what's the status on this PR? Is it ready for platform review?

**Comment by RussTedrake** [comment]
crap.  i thought this had landed already.  i guess we cannot avoid showing the class RBT/P.  
cc @pangtao22 .

**Comment by amcastro-tri** [comment]
do you need this for today? because @edrumwri was already working on this and all components should be in master already.

**Comment by RussTedrake** [comment]
if it came in today, we would use it.  that would be awesome.

**Comment by jwnimmer-tri** [comment]
___
*[systems/controllers/inverse_dynamics.h, line 65 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9131#-LLk-RZ339WkHWr5k7Tz:-LLk-RZ339WkHWr5k7U-:bxq9zyj) ([raw file](https://github.com/robotlocomotion/drake/blob/5f09b73a51c6269a20d7d0230224a601f5ce248f/systems/controllers/inverse_dynamics.h#L65)):*
> ```objc
>    * `true`).
>    */
>   InverseDynamics(const multibody::multibody_plant::MultibodyPlant<T>& plant,
> ```

BTW I'd prefer that objects that are aliased (i.e., where their lifetime must outlast this object), are pass by-pointer, not by-const-ref.  GSG specifically calls this out as allowed, though we haven't made it a 100% rule (defect) yet.

**Comment by jwnimmer-tri** [comment]
___
*[systems/controllers/inverse_dynamics.h, line 101 at r3](https://reviewable.io/reviews/robotlocomotion/drake/9131#-LLk0t5i87QeoyNiup0P:-LLk0t5i87QeoyNiup0Q:b-hf30l4) ([raw file](https://github.com/robotlocomotion/drake/blob/5f09b73a51c6269a20d7d0230224a601f5ce248f/systems/controllers/inverse_dynamics.h#L101)):*
> ```objc
> 
>   const RigidBodyTree<T>* rigid_body_tree_{nullptr};
>   const multibody::multibody_plant::MultibodyPlant<T>* multi_body_plant_{
> ```

nit `multibody` is one word by convention, not `multi_body`.

**Pull request merged**
