### PR TITLE
Python: Expose COM Jacobian and getRandomConfiguration

### PR DESCRIPTION
**Pull request by wxmerkt**
Exposes ``getRandomConfiguration`` and ``centerOfMassJacobian`` to Python

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3016)

### CODE REVIEW

**Comment by sherm1** [comment]
I don't know how to tell if these are working properly; by eyeball they look OK though. Have you verified that they do what you want them to do? Is it possible to add unit tests for functionality in Python-wrapped Drake?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-:-KO7OwXZlcp8vmIPW97D:5804360)*

**Comment by wxmerkt** [comment]
I'm using them actively and they return the results I'd expect (after all they simply expose the corresponding C++ functionality). Given that they just expose the C++ functionality without modifying input arguments, would a unit test still be advisable? Happy to add if so

**Comment by wxmerkt** [comment]
I've just noticed and fixed an issue with how I previously initialised the random seed (it was always drawing the same sample) -- PTAL

**Comment by sherm1** [comment]
I'm happy as long as you have verified that these are working. Because they just wrap existing functionality they seem unlikely to change in the future, so probably unit tests would never get a chance to protect us from any regressions. :lgtm:.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-:-KOC43gn8opDKsos7y3s:1669910539)*

**Comment by sherm1** [comment]
Should get a quick look from a feature reviewer, meaning someone familiar with the Python interface. @wxmerkt, you can just request one by commenting
```
Feature review +@particular_person, please.
```
Just pick someone who would be appropriate. The "plus at" syntax tells Reviewable to assign them as a reviewer.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-:-KOC4iiXk-JrUHzpB7yD:1090670634)*

**Comment by wxmerkt** [comment]
+@rdeits - could you feature review the SWIG/Python code please? Thanks!

**Comment by rdeits** [comment]
Code looks good, but I'd recommend adding a unit test, just to make sure nothing crazy is going on. I've opened a PR for your branch: https://github.com/wxmerkt/drake/pull/1

@sherm1 FYI it's easy to add unit tests for the python bindings: check out https://github.com/RobotLocomotion/drake/blob/master/drake/bindings/python/pydrake/test/testRBTCoM.py which uses the python builtin unittest module. The test actually gets added to CTest here: https://github.com/RobotLocomotion/drake/blob/master/drake/bindings/python/CMakeLists.txt#L19

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-:-KOFjrMn5B-JeDSZt_kX:-857108619)*

**Comment by wxmerkt** [comment]
Thanks Robin for the review and regression test, I've merged your PR and it's part of this PR.
 
@sherm1 Feature review done 

PS: I received an email from Reviewable after my comment above saying that I couldnt use the "+"-directives (i.e. it wouldn't be reflected in the online system) since I dont have push access - is this correct?

@drake-jenkins-bot: retest this please

**Comment by sherm1** [comment]
Thanks, @rdeits -- the unit test framework looks nice. 

I see the unit test here in this PR now, but I don't see the CMakeLists.txt change that Robin mentioned. Without that I don't think the test will get executed.

@wxmerkt: I'm surprised by Reviewable's complaint too. You might ask @david-german-tri about that.

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/bindings/python/pydrake/test/testRBTCoM.py, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-KOGGA6fK0_gXwT5xoC0:-KOGGA6fK0_gXwT5xoC1:493476565) ([raw file](https://github.com/robotlocomotion/drake/blob/299202e1b6fe266783a229480b19c61584dadfd5/drake/bindings/python/pydrake/test/testRBTCoM.py#L24)):*
> ```Python
>         q = r.getRandomConfiguration()
>         kinsol = r.doKinematics(q, np.zeros((7, 1)))
>         J = r.centerOfMassJacobian(kinsol)
> ```

I see this doesn't check whether the result is correct. Should it? If that's too difficult maybe it could at least check that the returned dimensions of J are right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-:-KOGEj3yBXJUGB9ipV92:812573127)*

**Comment by jwnimmer-tri** [comment]
@wxmerkt 

> I received an email from Reviewable after my comment above saying that I couldn't use the "+"-directives (i.e. it wouldn't be reflected in the online system) since I don't have push access - is this correct?

The effect of plus-at-username is just to set the github "Assignees" metatdata -- reviewable.io does not have separate metadata.  It looks like reviewable isn't funneling that through for you, so just clicking "Assignees" in the github sidebar will be required as a work-around.  Sorry!

**Comment by wxmerkt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/testRBTCoM.py, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-KOGGA6fK0_gXwT5xoC0:-KOGnl7OzmKrxsWL7p3o:239982453) ([raw file](https://github.com/robotlocomotion/drake/blob/299202e1b6fe266783a229480b19c61584dadfd5/drake/bindings/python/pydrake/test/testRBTCoM.py#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I see this doesn't check whether the result is correct. Should it? If that's too difficult maybe it could at least check that the returned dimensions of J are right?
</details>
PTAL - I've added checks for shape for the random configuration and also for values for a zero configuration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016)*

**Comment by wxmerkt** [comment]
@jwnimmer-tri Thanks for the explanation. I can't assign either.

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/testRBTCoM.py, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-KOGGA6fK0_gXwT5xoC0:-KOGx_qSGYiIzaYjc4lj:-524623518) ([raw file](https://github.com/robotlocomotion/drake/blob/299202e1b6fe266783a229480b19c61584dadfd5/drake/bindings/python/pydrake/test/testRBTCoM.py#L24)):*
<details><summary><i>Previously, wxmerkt (Wolfgang Merkt) wrote…</i></summary>
> PTAL - I've added checks for shape for the random configuration and also for values for a zero configuration
</details>
Looks good! 

Next question: is this actually getting executed? I don't see a change to `CMakeLists.txt` in this PR that I think is required to add the test to the test suite.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016)*

**Comment by wxmerkt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/testRBTCoM.py, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-KOGGA6fK0_gXwT5xoC0:-KOH-dNMZH6ZAFjKFEND:909207439) ([raw file](https://github.com/robotlocomotion/drake/blob/299202e1b6fe266783a229480b19c61584dadfd5/drake/bindings/python/pydrake/test/testRBTCoM.py#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Looks good! 
> 
> Next question: is this actually getting executed? I don't see a change to `CMakeLists.txt` in this PR that I think is required to add the test to the test suite.
</details>
Yes, the test is already in the ``CMakeLists.txt`` - it is an existing test (that tested only the CoM) that has now been expanded to test the ``getRandomConfiguration`` and ``centerOfMassJacobian``

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3016#-:-KOHJOsyUCVXG6GyaXUG:1417088721)*

**Pull request merged**
