### PR TITLE
Remove all remaining System1 code

### LINKED ISSUE #4305: Remove drake/multibody/rigid_body_system1
_Edit: When originally filed, this title read "Remove rigid_body_plant_system1_test".  Since then, the scope has expanded; see downthread._

Original task: Remove rigid_body_plant_system1_test.  Part of #3960.  We will purge System 1.0 code, so we can't rely on it for this unit test.  I guess we can keep this around until it's the last System 1.0 code remaining, but expect that within a month or so, we'll want to remove it.  So if we need a replacement unit test, perhaps time to write it sooner than later.

Discovered programs and tests; we need to consider if we can delete these or not yet:
- testMassSpringDamper - no value; immediately remove
- lidarTest - no value; immediately remove
- testAccelerometer - no value; immediately remove
- testGyroscope - no value; immediately remove
- testMagnetometer - no value; immediately remove
- compareAcrobotURDFtoSDF -- tracked as #5408
- comparePriusURDFtoSDF - irrelevant due to #4074
- load_model_test - no value; immediately remove
- drake_joint_test - no value; immediately remove
- rigid_body_system_test - no value; immediately remove
- rigidBodyLCMNode - no value; immediately remove

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #4305.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5409)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri and +@sherm1 for platform review, please.
+@david-german-tri and +@liangfok for feature review, please.

/CC @russtedrake in case you want to double-check anything.

Notes for reviewers:
- The most important thing to check for is deleting code (especially tests) that we shouldn't be deleting yet.  See the discussion in #4305 for my thoughts.
- Yes, the drakeRBSystem dependency fixups in CMakeLists are silly, but it didn't seem worth pruning them further in this PR.

---

Review status: 0 of 55 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-:-KePqSrRmTcFOA6k6Nr1:bigu3q)*

**Comment by RussTedrake** [comment]
:LGTM:

The only tests that might have value (if they haven't already been reproduced by @liangfok's recent work) are lidarTest, testAccelerometer, testGyroscope, testMagnetometer.  I *think* they've all been effectively ported now.  

---

Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-:-KeW9WC2cY9OWeAySNbT:bqcztqq)*

**Comment by jwnimmer-tri** [comment]
Yup, those are all on master except for the magnetometer, which is under PR at #5251.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-:-KeWCM1yjA8URVsPvgj9:bq2n22d)*

**Comment by liangfok** [comment]
:lgtm:

This PR will reduce unit test coverage for the parsers since `load_model_test.cc` calls `RigidbodySystem::AddModelInstanceFromFile()`, which in turn calls the actual SDF / URDF parser methods. I am OK with this temporary reduction since the parsers about to be replaced anyway per #4337, and the new parser will come with its own suite of unit tests.

---

Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-:-KeZHzCzc9tHqh4ulwQu:bnqi3h0)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 19 of 59 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/test/CMakeLists.txt, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-KeZNx-1QyRAibZpdl16:-KeZNx-2r7qHx1A_tcRB:bjju82u) ([raw file](https://github.com/robotlocomotion/drake/blob/562ea1a2b9d891c15f1a42942be843c8b23cc0ae/drake/systems/analysis/test/CMakeLists.txt#L33)):*
> ```CMake
>           Eigen3::Eigen
>           spruce
>           )          
> ```

BTW meta trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-:-KeZO75y7GN9Tm78CFha:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5409#-:-KeZgn2Ec31MF6R__3dr:bnfp4nl)*

**Pull request merged**
