### PR TITLE
skylark: Prefer `@drake//tools/skylark` over `//tools/skylark`

### LINKED ISSUE #8732: Use `load("@drake//tools/skylark:...` consistently
We should use `load("@drake//tools/skylark:...` consistently instead of sometimes doing `load("//tools/skylark:...`.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For more information, see:
- https://github.com/bazelbuild/bazel/issues/3115
- https://github.com/RobotLocomotion/drake/issues/8700

Resolves #8732

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9845)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I think it would make more sense to kick this to on-call review.  The point of me punting on it was to reduce my distractions.

**Comment by jamiesnape** [comment]
Do we (want to) have a Bazel style guide to start to document all these workarounds? I can't keep track of them all anymore.

**Comment by jwnimmer-tri** [comment]
I think some conventions probably deserve a styleguide, but for this (functional) rule I think a linter would be more effective.

**Comment by jamiesnape** [comment]
Certainly more effective, but it would nice for humans to have something to go by as well.

**Pull request merged**
