### PR TITLE
Fix sign-compare warnings in examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2877)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2877#-:-KNAP9I-1beqEetw1Bdp:1417088721)*

**Comment by jwnimmer-tri** [comment]
@liangfok for feature review please (one new change this morning).

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2877#-:-KNCgkusuv8vLFDNeIj4:-1868698381)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri for platform review and merge, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2877#-:-KNDA2o5zhI9q0_fxfAV:1417088721)*

**Pull request merged**
