### PR TITLE
[framework] Add DiagramBuilder::connection_map function

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16476.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @sherm1 FYI

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477#-:-MuqE7pO9BGYqLOmolEc:bb7ao1f)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[systems/framework/test/diagram_builder_test.cc, line 638 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MuqDVv_-vGg1zkhLiHv:-MuqDVv_-vGg1zkhLiHw:bdmiw23) ([raw file](https://github.com/robotlocomotion/drake/blob/ca6846d1b85dd74e4aa7c0761127f9cb021f911d/systems/framework/test/diagram_builder_test.cc#L638)):*
> ```cpp
>   }
>   {
>     const DiagramBuilder<double>::OutputPortLocator int1out1_output{
> ```

Tests the right thing, but `int1out`_output` looks like a typo. Perhaps `in1out1_output` instead?

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @rpoyner-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[systems/framework/test/diagram_builder_test.cc, line 638 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MuqDVv_-vGg1zkhLiHv:-MuqKxoD-tKIyuaOO3XO:b-16acol) ([raw file](https://github.com/robotlocomotion/drake/blob/ca6846d1b85dd74e4aa7c0761127f9cb021f911d/systems/framework/test/diagram_builder_test.cc#L638)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Tests the right thing, but `int1out`_output` looks like a typo. Perhaps `in1out1_output` instead?
</blockquote></details>

Right!  I make the `in => int` typo locally _all the time_.  This one escaped my notice.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few minor comments.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477#-:-MurtoTu2Ybc-WkdB4ej:bty5hbu)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram_builder.h, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MursJqk4-aJhsbJUza2:-MursJqk4-aJhsbJUza3:bj5oubn) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/systems/framework/diagram_builder.h#L262)):*
> ```objc
>   /// @warning The return value is only valid until the next call to any
>   /// non-const member function (e.g., `Connect`).
>   const std::map<InputPortLocator, OutputPortLocator>& connection_map() const;
> ```

minor: since this returns a reference to the actual data structure (rather than a copy) I don't understand why the value (a reference) doesn't continue being valid. Can you say more about what you mean?

I see the implementation doesn't allow this call if the diagram is already built but I'm (a) not sure why that restriction is there, (b) sure there should be some documentation about that here.
___
*[bindings/pydrake/systems/test/general_test.py, line 943 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MurtXj08AeRcYxaMw_h:-MurtXj08AeRcYxaMw_i:bieac2j) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/bindings/pydrake/systems/test/general_test.py#L943)):*
> ```Python
>             builder.ExportInput(adder1.get_input_port(1), "in1")
>             builder.ExportOutput(adder2.get_output_port(), "out")
>             self.assertEqual(len(builder.connection_map()), 1)
> ```

BTW since the python code is substantially more than a wrap, I'm wondering if this is a sufficient unit test for it. OK as is if you think that's enough.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @sherm1)

___
*[systems/framework/diagram_builder.h, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MursJqk4-aJhsbJUza2:-MuruFcn1qJvtYmJBDSV:bnc6kgv) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/systems/framework/diagram_builder.h#L262)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: since this returns a reference to the actual data structure (rather than a copy) I don't understand why the value (a reference) doesn't continue being valid. Can you say more about what you mean?

I see the implementation doesn't allow this call if the diagram is already built but I'm (a) not sure why that restriction is there, (b) sure there should be some documentation about that here.
</blockquote></details>

My main idea was that I didn't want to promise too much, in case we wanted to change the implementation later.  I suppose I'm having a difficult time imagining an implementation where we need to take advantage of this, though.  I should probably reword / retract the warning.

Relatedly, a call to `Build` or `BuildInto` would invalidate this reference.  Perhaps that's already covered by the class overview, though?  Do you think I should mention it specifically, here?  This is the only function that returns by-reference.
___
*[bindings/pydrake/systems/test/general_test.py, line 943 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MurtXj08AeRcYxaMw_h:-MurvZ--EJrNPOzNZSuM:blnq62m) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/bindings/pydrake/systems/test/general_test.py#L943)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW since the python code is substantially more than a wrap, I'm wondering if this is a sufficient unit test for it. OK as is if you think that's enough.
</blockquote></details>

Yeah, on second look, I did take a shortcut here.  I copy-pasted the bindings implementation from Diagram, so I'm relying on the two behaving identically.  That one is more thoroughly tested.

Probably I should note that testing strategy in a comment somewhere.

**Review by sherm1 — COMMENTED** [review]
+@xuchenhan-tri for platform shadow

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477#-:-MurxrVyBNe8OpRwWavS:b-gvua7w)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri (waiting on @jwnimmer-tri, @sherm1, and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477#-:-MusAkoi4oeRfUJTAmPC:bnfp4nl)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[systems/framework/diagram_builder.h, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MursJqk4-aJhsbJUza2:-MusAHIQE1-mR-_oGK66:b7v61j0) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/systems/framework/diagram_builder.h#L262)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My main idea was that I didn't want to promise too much, in case we wanted to change the implementation later.  I suppose I'm having a difficult time imagining an implementation where we need to take advantage of this, though.  I should probably reword / retract the warning.

Relatedly, a call to `Build` or `BuildInto` would invalidate this reference.  Perhaps that's already covered by the class overview, though?  Do you think I should mention it specifically, here?  This is the only function that returns by-reference.
</blockquote></details>

Should we also mention that this method throws if the builder has built?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform),xuchenhan-tri (waiting on @rpoyner-tri and @sherm1)

___
*[systems/framework/diagram_builder.h, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MursJqk4-aJhsbJUza2:-MusBCzP6yrmOmUmWNdw:b-cqr3w0) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/systems/framework/diagram_builder.h#L262)):*
> ... not sure why that restriction is there ...

Done (removed).

> Do you think I should mention [Build] specifically, here?

Done (added).

> Should we also mention that this method throws if the builder has built?

That's documented in the class overview.  (It holds true for all member functions of this class.)
___
*[bindings/pydrake/systems/test/general_test.py, line 943 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16477#-MurtXj08AeRcYxaMw_h:-MusB9VM8DWIxwMteiwe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c117570944c7010a73a25f775592f6a4aa279b31/bindings/pydrake/systems/test/general_test.py#L943)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, on second look, I did take a shortcut here.  I copy-pasted the bindings implementation from Diagram, so I'm relying on the two behaving identically.  That one is more thoroughly tested.

Probably I should note that testing strategy in a comment somewhere.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16477)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
