### PR TITLE
[workspace] Simplify Ipopt build rules with some abstractions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19928 and #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19930)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not merge) -(status: do not review) 

+@rpoyner-tri for feature review, please.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19930#-:-NawzrX99TGKnlAGiQJQ:bpj2iii)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge"

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19930#-:-Nb-tkSEA_z7rerJ4w-d:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/workspace/cmake_configure_file.py` line 184 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19930#-Nb-qowl8Jw5Ebw0jT7m:-Nb-qowl8Jw5Ebw0jT7n:b-q0i5uf) ([raw file](https://github.com/RobotLocomotion/drake/blob/98752a6ed7e26537d0e92b237ca4296981980038/tools/workspace/cmake_configure_file.py#L184)):*
> ```Python
>     parser.add_argument(
>         '--autoconf', action='store_true',
>         help='The input file is in autoconfig format, not cmake format.')
> ```

If you google `autoconfig`, you go down some Oracle business tools rathole. Consider just `autoconf` instead?



_Suggestion:_
```Python
autoconf
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19930)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/workspace/cmake_configure_file.py` line 184 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19930#-Nb-qowl8Jw5Ebw0jT7m:-Nb-vckr4jwKet1mpWLn:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/98752a6ed7e26537d0e92b237ca4296981980038/tools/workspace/cmake_configure_file.py#L184)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

If you google `autoconfig`, you go down some Oracle business tools rathole. Consider just `autoconf` instead?
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19930)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Heroic! Platform :lgtm:

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19930#-:-NbFqizZ9WqHz1xjOzsd:b-hkqu5b)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
