### PR TITLE
Remove deprecated code 2024-12

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22248)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews please, as a stakeholder on the MbP changes.

**Comment by cohnt** [comment]
Dropping by to say the geodesic convexity deprecation removals look good to me!

**Review by SeanCurtis-TRI — COMMENTED** [review]
One missed removal.

:LGTM: X2

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22248#-:-OD7sEfu6gHsRBFMYNhG:bwjurd2)* status: 1 unresolved discussion

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22248#-OD7rX3K7G3AmSA5O-24:-OD7rX3K7G3AmSA5O-25:b-1jkjnf) ([raw file](https://github.com/RobotLocomotion/drake/blob/73cb5d5174a3cba1a17d685fd5232f0ba77672d0/bindings/pydrake/multibody/test/plant_test.py#L1402)):*
> ```Python
>                 numpy_compare.to_float(v_WB_ref.translational()))
> 
>         # After 2024-12-01 deprecation is complete, we can remove this because
> ```

nit: You missed a `2024-12`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22248)* status: 1 unresolved discussion

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22248#-OD7rX3K7G3AmSA5O-24:-OD8NSB47opdhHz1ucYt:b6lzupi) ([raw file](https://github.com/RobotLocomotion/drake/blob/73cb5d5174a3cba1a17d685fd5232f0ba77672d0/bindings/pydrake/multibody/test/plant_test.py#L1402)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: You missed a `2024-12`.
</blockquote></details>

I went back and compared the test code to the pre-deprecation flavor, and reverted a bunch of stuff.  PTAL.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22248)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
