### PR TITLE
[DNM] Attempt at Sphinx 1.8.0 inclusion via source

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Gonna stop this for now; will resume later. Would be really nice to have pinned version.

Issues:
- Non-system PyPI deps for Xenial - only need ~3 deps, but I hate adding individual deps on super simple Python packages, and would prefer to archive them. (Also, platform-sensitive deps...)
- https://github.com/bazelbuild/bazel/issues/1653 - Worked around with `http_archive_python` hack, but yuck...

\cc @jamiesnape

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9654)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
What was wrong with the "Switch the `-documentation` on Bionic" counter-proposal?

**Comment by jamiesnape** [comment]
> What was wrong with the "Switch the -documentation builds to Bionic" counter-proposal?

Nothing to me, and it has actually been done.

**Comment by jwnimmer-tri** [comment]
In that case, I think "pinning" our Sphinx version to be "what Ubuntu 18.04 has" is fine.  In the unlikely event that they push a breaking change in a point release, we can deal with the problem then.

**Comment by jamiesnape** [comment]
Yes, personally I would punt on this indefinitely.

**Comment by EricCousineau-TRI** [comment]
If we don't get PIP packages in Drake, agreed. If we do, then supporting this will be relatively trivial.
Closing for now.

**Pull request closed without merging**
