### PR TITLE
fix an torque port port export bug in IiwaAndWsgPlantWithStateEstimator

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
cc @hongkai-dai @sammy-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7922)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for feature and platform review. i checked it on the pick and place demo. 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-:-L4GvTOKitqMKwYE_I3X:bmtdf8v)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_wsg_lcm.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-L4H2-bRLsMd3Yo87WRN:-L4H2-bSFZjJRrwN3RRr:bpwd0bq) ([raw file](https://github.com/robotlocomotion/drake/blob/5054eeb935b684d7d2b674b4224a740c3637f54d/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L204)):*
> ```cpp
> 
>   if (force) {
>     status.actual_force = force->GetAtIndex(0);
> ```

Should there be a minus sign here, as
```
status.actual_force = -force->GetAtIndex(0);
```
as we did for the `actual_position_mm`? Now when the object is grasped, the `actual force` is positive in the simulation, while on the real robot I think that number is negative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922)*

**Comment by siyuanfeng-tri** [comment]
*[manipulation/schunk_wsg/schunk_wsg_lcm.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-L4H2-bRLsMd3Yo87WRN:-L4H7Veu2AxkJM8pWo-q:b-9ytcjg) ([raw file](https://github.com/robotlocomotion/drake/blob/5054eeb935b684d7d2b674b4224a740c3637f54d/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L204)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should there be a minus sign here, as
```
status.actual_force = -force->GetAtIndex(0);
```
as we did for the `actual_position_mm`? Now when the object is grasped, the `actual force` is positive in the simulation, while on the real robot I think that number is negative.
</blockquote></details>

wait, i am almost 100% sure on the robot, it's positive. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_wsg_lcm.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-L4H2-bRLsMd3Yo87WRN:-L4H94AIJ59-01MMidV4:bgsvx77) ([raw file](https://github.com/robotlocomotion/drake/blob/5054eeb935b684d7d2b674b4224a740c3637f54d/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L204)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

wait, i am almost 100% sure on the robot, it's positive. 
</blockquote></details>

I just checked.  It's negative on the robot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922)*

**Comment by sammy-tri** [comment]
:lgtm: (pending the one open issue)

---

Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-:-L4H9hoyQCUP5v2ltq2M:b60c66z)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_wsg_lcm.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-L4H2-bRLsMd3Yo87WRN:-L4HK8jsj397XWjzTev3:b-227d0r) ([raw file](https://github.com/robotlocomotion/drake/blob/5054eeb935b684d7d2b674b4224a740c3637f54d/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L204)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I just checked.  It's negative on the robot.
</blockquote></details>

Here is a screenshot of the lcm reading on `actual_force` on the robot.

(Thanks @rcory for generating the plot).
These negative values are when the gripper holds the cup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922)*

**Comment by soonho-tri** [comment]
:lgtm: (pending the "positively negative" issue)

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-:-L4HQeYE8ZXnxFVgC6l6:b-325uz8)*

**Comment by siyuanfeng-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_wsg_lcm.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-L4H2-bRLsMd3Yo87WRN:-L4J-E7TBp07OnmoShro:b-c0zm6m) ([raw file](https://github.com/robotlocomotion/drake/blob/5054eeb935b684d7d2b674b4224a740c3637f54d/manipulation/schunk_wsg/schunk_wsg_lcm.cc#L204)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Here is a screenshot of the lcm reading on `actual_force` on the robot.

(Thanks @rcory for generating the plot).
These negative values are when the gripper holds the cup.
</blockquote></details>

ok you are right, i am getting out of touch.. the gripper code in iiwa_controller says it's negative as well. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922)*

**Comment by siyuanfeng-tri** [comment]
@sammy-tri can you resolve the circle at some point? thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922#-:-L4K8NGbrQ4dQTq6PwNe:b77oods)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7922)*

**Pull request merged**
