### PR TITLE
Set time recursively on Diagram subcontexts.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3299)

### CODE REVIEW

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review

**Comment by jwnimmer-tri** [comment]
:lgtm: with some thoughts.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/context_base.h, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNEK8A7-bzuAoBpbIV:-KQNEK8A7-bzuAoBpbIW:b-b7lq39) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/context_base.h#L35)):*
> ```objc
> 
>   /// Returns the current time in seconds.
>   const T& get_time() const { return get_step_info().time_sec; }
> ```

BTW Perhaps `get_time` should also become virtual, for parallelism with `set_time`, to give subclasses the opportunity to override both?

---

*[drake/systems/framework/diagram_context.h, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNEqiIPvibNRgHtWga:-KQNEqiIPvibNRgHtWgb:buwti5o) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/diagram_context.h#L210)):*
> ```objc
> 
>   /// Recursively sets the time on this context and all subcontexts.
>   void set_time(const T& time_sec) override {
> ```

BTW Given the looping, should this still be `snake_case`?

Perhaps having multiple copies of `StepInfo` is not what we want long-term?  Would a design where subsystem Contexts inherit time from their supersystem be superior?

---

*[drake/systems/framework/test/diagram_context_test.cc, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNFMTgCMOp8NnlsGbg:-KQNFMTgCMOp8NnlsGbh:b29ystr) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/test/diagram_context_test.cc#L82)):*
> ```cpp
> // until they are added as constituent systems.
> TEST_F(DiagramContextTest, AddAndRetrieveConstituents) {
>   EXPECT_EQ(nullptr, context_->GetSubsystemOutput(4));
> ```

BTW I think all of the `4`s in this test are really `kNumSystems`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-:-KQNGCtt6bcLyM4TN5re:bigbbtf)*

**Comment by amcastro-tri** [comment]
:lgtm:, just question. In my first attempt to fix this bug I implemented exactly the same solution however without the check for `nullptr`. That led me to an infinite loop. Would you know why?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/diagram_context.h, line 214 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNI_Pa8w8u3Jl_4ZGz:-KQNI_Pa8w8u3Jl_4ZH-:bxnui19) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/diagram_context.h#L214)):*
> ```objc
>     for (auto& kv : contexts_) {
>       ContextBase<T>* subcontext = kv.second.get();
>       if (subcontext != nullptr) {
> ```

in what case can `subcontext` be a `nullptr`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-:-KQNIvqdx8wYcxGLnoIu:bdhkahv)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/diagram_context.h, line 214 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNI_Pa8w8u3Jl_4ZGz:-KQNVrSt3HW4BFldJDac:bviihn0) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/diagram_context.h#L214)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> in what case can `subcontext` be a `nullptr`?
</details>
Actually I'm really curious also.  A few other class methods dereference `second` without the `nullptr` check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3299)*

**Comment by david-german-tri** [comment]
> In my first attempt to fix this bug I implemented exactly the same solution however without the check for nullptr. That led me to an infinite loop. Would you know why?

No idea!  The nullptr check surely isn't the root cause, though.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/context_base.h, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNEK8A7-bzuAoBpbIV:-KQNZj1FsqUomA6zy6BS:b-5bklg5) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/context_base.h#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Perhaps `get_time` should also become virtual, for parallelism with `set_time`, to give subclasses the opportunity to override both?
</details>
The `*Context` family is not intended to be open to user subclasses, so I think I'll leave this as is.

---

*[drake/systems/framework/diagram_context.h, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNEqiIPvibNRgHtWga:-KQN_JIIWfxG9jXGGx2_:b-iak14q) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/diagram_context.h#L210)):*
> Perhaps having multiple copies of StepInfo is not what we want long-term?  Would a design where subsystem Contexts inherit time from their supersystem be superior?

Given that we would need to propagate cache invalidation anyway, propagating the time itself seems cleaner conceptually.

---

*[drake/systems/framework/diagram_context.h, line 214 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNI_Pa8w8u3Jl_4ZGz:-KQNZsaf6_7aYYFGZux-:b-kxtqb2) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/diagram_context.h#L214)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Actually I'm really curious also.  A few other class methods dereference `second` without the `nullptr` check.
</details>
Right now, it can't.  This is futureproofing for a change @sherm1 requested to remove the `map` lookup.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNFMTgCMOp8NnlsGbg:-KQN_78jNRdLdwtVaSkM:b-m5hnhn) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/test/diagram_context_test.cc#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I think all of the `4`s in this test are really `kNumSystems`?
</details>
I feel a little weird about that, given that the number of systems changes in this test, so I'll leave it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-:-KQNZY4jhpG32WDHLtzs:btdwems)*

**Comment by sherm1** [comment]
*[drake/systems/framework/diagram_context.h, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3299#-KQNEqiIPvibNRgHtWga:-KQOcSBEvTXAyptArkfm:bqxj8ez) ([raw file](https://github.com/robotlocomotion/drake/blob/c66a574fb77f4daf914c99bf0f7a1188a72e9fdc/drake/systems/framework/diagram_context.h#L210)):*
>>Perhaps having multiple copies of StepInfo is not what we want long-term? Would a design where subsystem Contexts inherit time from their supersystem be superior?

>Given that we would need to propagate cache invalidation anyway, propagating the time itself seems cleaner conceptually.

There is only a single time (StepInfo) being managed by the simulator; as a value source it is like a state variable (always valid). I would like that to be reflected in the code by having a single object that can be referenced by those subsystems that need it. Conceptually time is just like another input port from the point of view of a time-sensitive subsystem. Then invalidation can occur by exactly the same mechanism (and code) that propagates changes to other inputs: When time changes, the top-level time object can notify the TimePorts that have registered with it; they can recursively deal with internal time dependencies. There should be no need to copy the StepInfo value around, just as we shouldn't be copying other values around -- pointers internal to the full context can point right at the needed values for instant access.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3299)*

**Pull request merged**
