### PR TITLE
[tools] Defer header_lint failures to lint-time, not build-time

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
+@rpoyner-tri for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16850)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16850#-:-Mys15NCEjIP6Cf1uS40:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review, please.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16850#-:-MysVT333B7xJuQrgnnv:bp8iotw)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[tools/install/libdrake/header_lint.bzl, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16850#-MysU2-e4fV0pYavn0B_:-MysU2-f1Di8qOnJKTyO:bs4shrw) ([raw file](https://github.com/robotlocomotion/drake/blob/90888140969b157eb3e013df2a17c9455ca2fc51/tools/install/libdrake/header_lint.bzl#L36)):*
> ```Starlark
>     "ignition_utils",
>     "ipopt",
>     "lcm",
> ```

BTW, lcm shows up in both the accepted externals and the defect externals.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16850)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16850)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[tools/install/libdrake/header_lint.bzl, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16850#-MysU2-e4fV0pYavn0B_:-Mys_YDmEbC7jaqTgFvm:bi6y7j2) ([raw file](https://github.com/robotlocomotion/drake/blob/90888140969b157eb3e013df2a17c9455ca2fc51/tools/install/libdrake/header_lint.bzl#L36)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, lcm shows up in both the accepted externals and the defect externals.
</blockquote></details>

Good catch.  I have another PR on the way to start fixing these header leaks, so I'll plan to roll it into there.

**Pull request merged**
