### PR TITLE
Write Bazel options used by CMake to a bazel.rc file

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #7835. FYI @RussTedrake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7849)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review (high priority).

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7849#-:-L3dKpXiYWz9XcqZfFab:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review (high priority).

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7849#-:-L3ddhRtB2Ud7Z_xwesf:bnfp4nl)*

**Pull request merged**
