### PR TITLE
Extend AddLinearConstraint to take a conjunction of symbolic formulas

### LINKED ISSUE #5536: Extend AddLinearConstraint(const symbolic::Formula& f) in mathematical program
1) [x] To take `Eigen::Array<Formula>`
2) [x] To take a conjunctive formula `f_1 && ... f_n`

/cc @hongkai-dai 
/cc @gizatt

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #5536

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5637)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-:-KgGzD-RAf0pP4xh6R_9:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 680 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMcbc5nGyKaMFuNziS:-KgMcbc5nGyKaMFuNziT:bn8l5gq) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/mathematical_program.cc#L680)):*
> ```cpp
>   // Decomposes a set of formulas into a 1D-vector of expressions, `v`, and two
>   // 1D-vector of double `lb` and `ub`.
>   Eigen::Matrix<symbolic::Expression, Eigen::Dynamic, 1> v{n};
> ```

use `VectorX<symbolic::Expression>`?

---

*[drake/solvers/mathematical_program.cc, line 681 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMcY8yJsTBqt8boEiD:-KgMcY8yJsTBqt8boEiE:btxuuk8) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/mathematical_program.cc#L681)):*
> ```cpp
>   // 1D-vector of double `lb` and `ub`.
>   Eigen::Matrix<symbolic::Expression, Eigen::Dynamic, 1> v{n};
>   Eigen::Matrix<double, Eigen::Dynamic, 1> lb{n};
> ```

use `Eigen::VectorXd`?

---

*[drake/solvers/mathematical_program.cc, line 684 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMcrhChsmx9etEZeka:-KgMcrhChsmx9etEZekb:bxy0gnm) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/mathematical_program.cc#L684)):*
> ```cpp
>   Eigen::Matrix<double, Eigen::Dynamic, 1> ub{n};
>   int i{0};  // index variable used in the loop
>   for (const symbolic::Formula& f : formulas) {
> ```

Can we add a boolean flag `are_all_formulae_equal`? If every `f` inside `formulas` is an equality constraint, then we should set this flag to `true`; otherwise to `false`. In the end of the function, if this flag is true, then we should call `AddLinearEqualityConstraint`, instead of `AddLinearConstraint`. The equality constraint can be useful in some cases. For example, in quadratic programming (quadratic cost with linear constraints). If all linear constraints are equality constraints, then the optimal solution can be computed analytically. Otherwise the solver might need to spend several iterations, to determine which inequality constraint should be treated as equality constraint. We can still return a `LinearConstraint`, as `LinearEqualityConstraint` is a sub-class of `LinearConstraint`.

---

*[drake/solvers/test/mathematical_program_test.cc, line 945 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMduq_ox0sn-xQOVWK:-KgMduq_ox0sn-xQOVWL:b-scouq5) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/test/mathematical_program_test.cc#L945)):*
> ```cpp
>   const auto constraint_ptr = binding.constraint();
>   EXPECT_EQ(constraint_ptr->num_constraints(), b.size());
>   const auto Ax = constraint_ptr->A() * var_vec;
> ```

So the order of the formula in the `set<symbolic::Formula>`, is the order in the matrix? Namely `Ax(0) -b(0)` is the first element of the `set<symbolic::Formula>`, and `Ax(1)-b(1)` is the second element?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 680 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMcbc5nGyKaMFuNziS:-KgNAIS74ojBGj4KxTO5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/mathematical_program.cc#L680)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

use `VectorX<symbolic::Expression>`?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 681 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMcY8yJsTBqt8boEiD:-KgNAItUvlGWS9H32b6n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/mathematical_program.cc#L681)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

use `Eigen::VectorXd`?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 684 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMcrhChsmx9etEZeka:-KgP9oUKfMeTkFawE1_0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/mathematical_program.cc#L684)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we add a boolean flag `are_all_formulae_equal`? If every `f` inside `formulas` is an equality constraint, then we should set this flag to `true`; otherwise to `false`. In the end of the function, if this flag is true, then we should call `AddLinearEqualityConstraint`, instead of `AddLinearConstraint`. The equality constraint can be useful in some cases. For example, in quadratic programming (quadratic cost with linear constraints). If all linear constraints are equality constraints, then the optimal solution can be computed analytically. Otherwise the solver might need to spend several iterations, to determine which inequality constraint should be treated as equality constraint. We can still return a `LinearConstraint`, as `LinearEqualityConstraint` is a sub-class of `LinearConstraint`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/solvers/test/mathematical_program_test.cc, line 945 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMduq_ox0sn-xQOVWK:-KgPBEwYwHH3c97rAy8B:bcl5hx6) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/test/mathematical_program_test.cc#L945)):*
> So the order of the formula in the set<symbolic::Formula>, is the order in the matrix?

It's not the case. `std::set<Formula>` is using `Formula::Less` function as a comparator.

For now, we use `std::set<Formula>` as internal representation of conjunctive (AND) and disjunctive (OR) formulas. It is chosen to avoid duplications in conjuncts/disjuncts. For example, we want to have a simplification `f1 /\ f2 /\ f1 => f1 /\ f2`.

**TODO1**) My understanding is that enforcing another property, "order-preserving", is not so much needed. I'll document the Formula-constructing operators (such as `Eigen::Matrix` == `Eigen::Matrix`) to emphasize that the ordering of formulas in the return value can be different from the ordering in inputs.

**TODO2**) I'll update the test functions to address the different ordering issue.

FYI, If we want to enforce 'order-preserving' in constructing a `symbolic::Formula` from matrix comparison, we need to use either A) a combination of `std::vector` and `std::set` or `boost::MultiIndex` inside of `symbolic::Formula` class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-:-KgPPQ4CyMd_-ZmVDQ04:bq323eq)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 945 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMduq_ox0sn-xQOVWK:-KgQ-yZVzM5e77yGPd2O:b-t3s8ej) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/test/mathematical_program_test.cc#L945)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> So the order of the formula in the set<symbolic::Formula>, is the order in the matrix?

It's not the case. `std::set<Formula>` is using `Formula::Less` function as a comparator.

For now, we use `std::set<Formula>` as internal representation of conjunctive (AND) and disjunctive (OR) formulas. It is chosen to avoid duplications in conjuncts/disjuncts. For example, we want to have a simplification `f1 /\ f2 /\ f1 => f1 /\ f2`.

**TODO1**) My understanding is that enforcing another property, "order-preserving", is not so much needed. I'll document the Formula-constructing operators (such as `Eigen::Matrix` == `Eigen::Matrix`) to emphasize that the ordering of formulas in the return value can be different from the ordering in inputs.

**TODO2**) I'll update the test functions to address the different ordering issue.

FYI, If we want to enforce 'order-preserving' in constructing a `symbolic::Formula` from matrix comparison, we need to use either A) a combination of `std::vector` and `std::set` or `boost::MultiIndex` inside of `symbolic::Formula` class.
</blockquote></details>

I think it is good to document the behavior, that order preserving is not guaranteed, and the duplicate constraints will be removed. The optimization problem should give the same answer, by shuffling the order of the constraints, and removing some duplicated constraints. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by soonho-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 945 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgMduq_ox0sn-xQOVWK:-KgQVmTvtv4yfsMkPiUz:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d477a1b1941bbd58f7ad0ae94a840636bd1dbd/drake/solvers/test/mathematical_program_test.cc#L945)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is good to document the behavior, that order preserving is not guaranteed, and the duplicate constraints will be removed. The optimization problem should give the same answer, by shuffling the order of the constraints, and removing some duplicated constraints. 
</blockquote></details>

Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 714 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgQapefXW0UMx69xxT-:-KgQapefXW0UMx69xxT0:b-ggb6tf) ([raw file](https://github.com/robotlocomotion/drake/blob/35aeaaab776784654d838ad054d3a82995a8d5e7/drake/common/symbolic_formula.h#L714)):*
> ```objc
> /// conjuncts as `std::set<Formula>` internally. This set is ordered by
> /// `Formula::Less` and this ordering can be *different* from the one in
> /// inputs. Please check the following example.
> ```

Could you also remind the user that the duplicated formula is removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-:-KgQayQb7mu4EJCRyyTs:b-68p82t)*

**Comment by soonho-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 714 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgQapefXW0UMx69xxT-:-KgQoPcras9g05op858B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35aeaaab776784654d838ad054d3a82995a8d5e7/drake/common/symbolic_formula.h#L714)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you also remind the user that the duplicated formula is removed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-:-KgRIFgrlk0oFVeecQir:b-yxxxd1)*

**Comment by sammy-tri** [comment]
:lgtm: (one minor comment nitpick)

---

Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1014 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgUkfDyNerp33P6gAwn:-KgUkfDzjrSMt_JqH5GN:bu0m6xf) ([raw file](https://github.com/robotlocomotion/drake/blob/96dddb93a4c5d7d5d4f7461e61bc0891624cced2/drake/solvers/test/mathematical_program_test.cc#L1014)):*
> ```cpp
>   //
>   // It includes relational formulas with strict inequalities (> and <). It will
>   // throw std::runtime.
> ```

BTW nit: why not spell out std::runtime_error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-:-KgUlEu3ne7ov9ENQoXq:b3vzovi)*

**Comment by soonho-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1014 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5637#-KgUkfDyNerp33P6gAwn:-KgUwHRKEIJI1wbjePNG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96dddb93a4c5d7d5d4f7461e61bc0891624cced2/drake/solvers/test/mathematical_program_test.cc#L1014)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW nit: why not spell out std::runtime_error?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5637)*

**Pull request merged**
