### PR TITLE
Controlled IIWA and IIWA World readme fix

### PR DESCRIPTION
**Pull request by naveenoid**
Fixes the text in the controlled_kuka README.md and adds a new one in the iiwa_world folder.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4620)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@liangfok for feature review. 
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-:-K_1PPI5TmLNE11DMs_v:b-pu9q93)*

**Comment by liangfok** [comment]
Competed feature review. PTAL. Mostly nits.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1f21qxbgJXV6zczpu:-K_1f21vFdTyS6_fBWn1:b-x077rq) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L5)):*
> ```Markdown
> ## About These Demos
> 
> These demos are of a simulation of the KUKA iiwa arm following simple IK
> ```

BTW, consider replacing "are of a simulation of" with "simulate".

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1UhQtCvSRkxzeegGU:-K_1UhQu8rxcDiqjtrzk:b-n02haf) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L9)):*
> ```Markdown
> position controller with gravity compensation.
> 
> The individual demos are :
> ```

Extraneous space before ":". (Same for below.)

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1VrSVqTDyo4AcoE9i:-K_1VrSVqTDyo4AcoE9j:b-qc3gzw) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L12)):*
> ```Markdown
> 1. controlled_kuka_demo : The KUKA iiwa follows an arbitrarily designed plan.
> 2. kuka_cartesian_waypoint_demo : The KUKA iiwa's end-effector follows a
> rectangle in Cartesian space.
> ```

BTW, consider describing the four points of the rectangle or otherwise providing a high level description of the rectangle size & orientation.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gzj5xVYyNMBbMRvV:-K_1gzj5xVYyNMBbMRvW:b-b63zla) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L19)):*
> ```Markdown
> 
>     $ cd drake-distro
>     $ ./build/install/bin/drake-visualizer
> ```

BTW, consider recommending that users only one terminal and using a "&" after the Drake Visualizer command:

```
$ cd drake-distro
$ ./build/install/bin/drake-visualizer &
$ ./build/drake/bin/[demo name]
```

(Same comment in the next file.)

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gQMlMM8C6NPH22Rc:-K_1gQMmBkhCzuxFkcRO:by3g6rp) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L6)):*
BTW, consider replacing:

> and cuboids etc.

with:

> , cuboids, etc.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gZC96rpdiheTfL_E:-K_1gZC96rpdiheTfL_F:b-n6zk96) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L8)):*
> ```Markdown
> with various objects such as tables, simple cylinders and cuboids etc.
> 
> For now, the demo presented is :
> ```

Extraneous space before ":".

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gf_l7UEt484APo0k:-K_1gf_mdpZKCuzKD7S0:bpdmq6o) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L9)):*
> ```Markdown
> 
> For now, the demo presented is :
> iiwa_world_demo : An uncontrolled The KUKA iiwa that is mounted on a table
> ```

BTW, consider adding "arm" after "iiwa".

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gk-DU-syv0T4eyNA:-K_1gk-DU-syv0T4eyNB:b-jucay5) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L9)):*
> ```Markdown
> 
> For now, the demo presented is :
> iiwa_world_demo : An uncontrolled The KUKA iiwa that is mounted on a table
> ```

Delete "The" and "that is".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-:-K_1hINiwp37A8EDVSGK:b-krr1qh)*

**Comment by naveenoid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1f21qxbgJXV6zczpu:-K_3B0t04zdHqUmeG4CO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "are of a simulation of" with "simulate".
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1UhQtCvSRkxzeegGU:-K_3B4F5cGKRMEO55qIL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Extraneous space before ":". (Same for below.)
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1VrSVqTDyo4AcoE9i:-K_3D4OJ6Ei0ghhRO7By:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L12)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider describing the four points of the rectangle or otherwise providing a high level description of the rectangle size & orientation.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gzj5xVYyNMBbMRvV:-K_3DOcE96iws4PSDfJz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider recommending that users only one terminal and using a "&" after the Drake Visualizer command:

```
$ cd drake-distro
$ ./build/install/bin/drake-visualizer &
$ ./build/drake/bin/[demo name]
```

(Same comment in the next file.)
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gQMlMM8C6NPH22Rc:-K_3DX6NtAsxebB4ERKe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing:

> and cuboids etc.

with:

> , cuboids, etc.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gZC96rpdiheTfL_E:-K_3Dy4CBlbQtLp5LNVG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L8)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Extraneous space before ":".
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gf_l7UEt484APo0k:-K_3DvL9Ql_OuZSK2Ksu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding "arm" after "iiwa".
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/README.md, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_1gk-DU-syv0T4eyNA:-K_3DvfZodL0tILZQjgR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a229cfd195bfa05082964130557446de0a91eb2f/drake/examples/kuka_iiwa_arm/iiwa_world/README.md#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Delete "The" and "that is".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620)*

**Comment by liangfok** [comment]
:lgtm: modulo a a couple minor comments.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_4c3Xcxhwhi-ASagqQ:-K_4c3Xcxhwhi-ASagqR:b-71i4ox) ([raw file](https://github.com/robotlocomotion/drake/blob/5750388fc717ae0d76555bc18c534e828de66f3c/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L5)):*
> ```Markdown
> ## About These Demos
> 
> These demos are simulate the KUKA iiwa arm following simple IK
> ```

BTW, delete "are".

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_4cKMyeUQlA7zrWbFG:-K_4cKMz5vmAvx80aFga:b-z3jc4i) ([raw file](https://github.com/robotlocomotion/drake/blob/5750388fc717ae0d76555bc18c534e828de66f3c/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L18)):*
> ```Markdown
> ## How To Run The Demos
> 
> Open the terminal. First, launch the Drake Visualizer and then start the demo
> ```

BTW, I believe that comma after "First" is not necessary. (Same comment below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-:-K_4cdLw4g2wAz6pah1x:b-yky92w)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_4d2AesSJIvjbn4dHo:-K_4d2AesSJIvjbn4dHp:b-sxfotx) ([raw file](https://github.com/robotlocomotion/drake/blob/5750388fc717ae0d76555bc18c534e828de66f3c/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L10)):*
> ```Markdown
> 
> The individual demos are:
> 1. controlled_kuka_demo: The KUKA iiwa follows an arbitrarily designed plan.
> ```

I just realized that this enumerated list doesn't render correctly here: 

https://github.com/naveenoid/drake/tree/dev/IIWAReadmeFix/drake/examples/kuka_iiwa_arm/controlled_kuka

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620)*

**Comment by naveenoid** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_4c3Xcxhwhi-ASagqQ:-K_4n0l_kyQwhjOJ-sPV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5750388fc717ae0d76555bc18c534e828de66f3c/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, delete "are".
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/README.md, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4620#-K_4d2AesSJIvjbn4dHo:-K_4nm3tglzlzAtWZR0x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5750388fc717ae0d76555bc18c534e828de66f3c/drake/examples/kuka_iiwa_arm/controlled_kuka/README.md#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I just realized that this enumerated list doesn't render correctly here: 

https://github.com/naveenoid/drake/tree/dev/IIWAReadmeFix/drake/examples/kuka_iiwa_arm/controlled_kuka
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4620)*

**Pull request merged**
