### PR TITLE
[render_vtk] Re-enable most macOS arm64 tests

### LINKED ISSUE #19424: [render_vtk] Unit test failure on Mac Ventura M1
Part of #18327.  For prior art see #17566.

We're not sure if this is our buggy code, or buggy graphics driver stack, or buggy CI hardware, or etc.

For now, I'm going to nerf the test to get CI passing.

---

```
[ RUN      ] RenderEngineVtkTest.BoxTest
geometry/render_vtk/test/internal_render_engine_vtk_test.cc:328: Failure
Value of: CompareColor(expected_outlier_color_, color, screen_coord)
  Actual: false (Expected: (0, 0, 0, 255) at (10, 10), tested: (254, 127, 0, 255) with tolerance: 1.0009999999999999)
Expected: true
Color at: (10, 10) for test: Box test - diffuse color
geometry/render_vtk/test/internal_render_engine_vtk_test.cc:331: Failure
Value of: IsExpectedDepth(depth, screen_coord, expected_outlier_depth_, kDepthTolerance)
  Actual: false (Expected depth at (10, 10) to be 3. Found inf. Difference inf is greater than tolerance 0.0010000000474974513)
Expected: true
Depth at: (10, 10) for test: Box test - diffuse color
geometry/render_vtk/test/internal_render_engine_vtk_test.cc:333: Failure
Expected equality of these values:
  label.at(x, y)[0]
    Which is: 32766
  expected_outlier_label_
    Which is: 32764
Label at: (10, 10) for test: Box test - diffuse color
geometry/render_vtk/test/internal_render_engine_vtk_test.cc:328: Failure
Value of: CompareColor(expected_outlier_color_, color, screen_coord)
  Actual: false (Expected: (0, 0, 0, 255) at (10, 469), tested: (254, 127, 0, 255) with tolerance: 1.0009999999999999)
Expected: true
Color at: (10, 469) for test: Box test - diffuse color
geometry/render_vtk/test/internal_render_engine_vtk_test.cc:331: Failure
Value of: IsExpectedDepth(depth, screen_coord, expected_outlier_depth_, kDepthTolerance)
  Actual: false (Expected depth at (10, 469) to be 3. Found inf. Difference inf is greater than tolerance 0.0010000000474974513)
Expected: true
Depth at: (10, 469) for test: Box test - diffuse color
geometry/render_vtk/test/internal_render_engine_vtk_test.cc:333: Failure
Expected equality of these values:
  label.at(x, y)[0]
    Which is: 32766
  expected_outlier_label_
    Which is: 32764
Label at: (10, 469) for test: Box test - diffuse color
[  FAILED  ] RenderEngineVtkTest.BoxTest (3880 ms)
```

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #19424

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20522)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20522)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

___
*[`geometry/render_vtk/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20522#-NivQjKtDvcvYxSzwF9T:-NivQjKtDvcvYxSzwF9U:b4dxla9) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d55aff3225da608d0fd5a64b8232b29e42ed580/geometry/render_vtk/BUILD.bazel#L123)):*
> ```Starlark
>         # trying to select the few that randomly happen to pass, we'll skip all
>         # of them. TODO(#19424) Re-enable the tests.
>         "@platforms//cpu:arm64": [
> ```

working,

- monterey build: https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/129/consoleFull
- ventura build: https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/3269/consoleFull

these are the primary targets of interest :eyes:

```
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.TerrainTest
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.HorizonTest
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.MultiMaterialObjects
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.FallbackLight
\[5:58:07 PM\]  
\[5:58:07 PM\]   4 FAILED TESTS
\[5:58:07 PM\]  ================================================================================
```

I think I need to have drake-ci upload `outputs.zip` somewhere

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20522)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

___
*[`geometry/render_vtk/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20522#-NivQjKtDvcvYxSzwF9T:-Njhb1LeCtM24c1nAuRr:b-97nxy5) ([raw file](https://github.com/RobotLocomotion/drake/blob/48608eccba1e3aa4470934c396edc1737a428b04/geometry/render_vtk/BUILD.bazel#L123)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working,

- monterey build: https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-experimental-release/129/consoleFull
- ventura build: https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/3269/consoleFull

these are the primary targets of interest :eyes:

```
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.TerrainTest
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.HorizonTest
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.MultiMaterialObjects
\[5:58:07 PM\]  \[  FAILED  \] RenderEngineVtkTest.FallbackLight
\[5:58:07 PM\]  
\[5:58:07 PM\]   4 FAILED TESTS
\[5:58:07 PM\]  ================================================================================
```

I think I need to have drake-ci upload `outputs.zip` somewhere
</blockquote></details>

working, now that mac arm64 CI has changed, harvesting new results to confirm failures are the same on sonoma


- https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/3414/
- https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/5/

as discussed in f2f, there may be an orka backend fix worth trying here, just collecting data right now

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20522)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/render_vtk/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20522#-NivQjKtDvcvYxSzwF9T:-NtKywC-DrfTOK5fl-0H:bvn7top) ([raw file](https://github.com/RobotLocomotion/drake/blob/48608eccba1e3aa4470934c396edc1737a428b04/geometry/render_vtk/BUILD.bazel#L123)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, now that mac arm64 CI has changed, harvesting new results to confirm failures are the same on sonoma


- https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/3414/
- https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/5/

as discussed in f2f, there may be an orka backend fix worth trying here, just collecting data right now
</blockquote></details>

huh, we now have different failures

```
[5:06:41 AM]  [  FAILED  ] RenderEngineVtkTest.MultiMaterialObjects
[5:06:41 AM]  [  FAILED  ] RenderEngineVtkTest.FallbackLight
[5:06:41 AM]  [  FAILED  ] RenderEngineVtkTest.WholeImageDefaultParams
```

https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5203/consoleFull

a couple look like tolerance fixes

also, https://github.com/RobotLocomotion/drake-ci/pull/269 and https://github.com/RobotLocomotion/drake/pull/20470 running in https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5204/consoleFull seems problematic, 

```
[5:12:12 AM]  [4,011 / 4,012] Testing //geometry/render_vtk:internal_render_engine_vtk_test; 709s local, remote-cache
[5:13:10 AM]  [4,011 / 4,012] Testing //geometry/render_vtk:internal_render_engine_vtk_test; 769s local, remote-cache
[5:13:52 AM]  Cannot contact ventura-nstl8: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
```

an IO too slow problem?  will need to come back and just look at the failing tests

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20522)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`geometry/render_vtk/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20522#-NivQjKtDvcvYxSzwF9T:-NtMGNqu-xHJNuZxq5tH:b-vppcqw) ([raw file](https://github.com/RobotLocomotion/drake/blob/48608eccba1e3aa4470934c396edc1737a428b04/geometry/render_vtk/BUILD.bazel#L123)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

huh, we now have different failures

```
[5:06:41 AM]  [  FAILED  ] RenderEngineVtkTest.MultiMaterialObjects
[5:06:41 AM]  [  FAILED  ] RenderEngineVtkTest.FallbackLight
[5:06:41 AM]  [  FAILED  ] RenderEngineVtkTest.WholeImageDefaultParams
```

https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5203/consoleFull

a couple look like tolerance fixes

also, https://github.com/RobotLocomotion/drake-ci/pull/269 and https://github.com/RobotLocomotion/drake/pull/20470 running in https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5204/consoleFull seems problematic, 

```
[5:12:12 AM]  [4,011 / 4,012] Testing //geometry/render_vtk:internal_render_engine_vtk_test; 709s local, remote-cache
[5:13:10 AM]  [4,011 / 4,012] Testing //geometry/render_vtk:internal_render_engine_vtk_test; 769s local, remote-cache
[5:13:52 AM]  Cannot contact ventura-nstl8: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
```

an IO too slow problem?  will need to come back and just look at the failing tests
</blockquote></details>

Re-run of job is here: https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5206/console

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please.

results should come back in a few hours after nightlies finish

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20522)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

___
*[`geometry/render_vtk/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20522#-NivQjKtDvcvYxSzwF9T:-NtQ1NeeBvGnQJTiTXNi:ba59x9d) ([raw file](https://github.com/RobotLocomotion/drake/blob/48608eccba1e3aa4470934c396edc1737a428b04/geometry/render_vtk/BUILD.bazel#L123)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Re-run of job is here: https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5206/console
</blockquote></details>

Running again without the images getting saved (I messed up the AWS upload part, but the tests failed in the same spot).  New jobs:

- https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/5223/consoleFull
- https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-release/34/consoleFull

See also https://github.com/RobotLocomotion/drake/issues/19424#issuecomment-2009044149

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please.

running unprovisioned and sonoma to try and get three data points as to whether this will work... re-enabling most seems like a slight improvement, the other tests do seem to be reliably passing now

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please.

trying again with the correct gtest filter

**Comment by svenevs** [comment]
Bummer, there is no determinism here it seems

```
[4:03:42 PM]  [  FAILED  ] RenderEngineVtkTest.MeshTest
```

was passing, until we disabled the others.  it worked on one of the jobs, not the other, meaning it will just continue to be sporadic.

**Pull request closed without merging**
