### PR TITLE
Split jacobian (hessian) functions into jacobian.h

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Rationale:
1. Many users who want the `autodiff.h` simple tools don't need `jacobian()`; separating the two concepts makes dependencies simpler.  I've been meaning to PR this for a while anyway.
2. In my GCC 4.8 backporting, `jacobian()` is the only real problem, because it uses `decltype(auto)`, so carving it out separately lets me omit it from the build.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3783)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
/CC @tkoolen if you have any opinions -- either drop a comment here, or feel free to self-assign for feature review if you prefer.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3783#-:-KTuE7iapjr90IY1nG8c:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm: assuming that the code in the new files is cut and paste from the prior location.  It seemed that way at first glance but I didn't verify it line-by-line.

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3783#-:-KTuGMUJwAeeHC5IseZk:bykm63k)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri Yes, the function doxygen, signatures, and bodies are identically moved.  Only the surrounding boilerplate (includes, namespaces, etc.) has been hand-reworked.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3783#-:-KTuJBrcQ0GzEUMz_vGX:b-7t0mp4)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3783)*

**Comment by tkoolen** [comment]
Extracting this functionality out into its own file: OK. I don't particularly like`jacobian.h` as the header name, especially since I'm planning to add a lower level `gradient` function that will be useful by itself and will be called by `jacobian`. But I don't know what would be a better name, so :lgtm: .

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3783#-:-KTuLVj87KXSmi7KFprT:b7zb122)*

**Comment by jwnimmer-tri** [comment]
@tkoolen Thanks!  I also struggled with the name for a while.  If you think of a better one, let me know and I'm happy to chug through another PR to fix it.

**Pull request merged**
