### PR TITLE
Fix all solvers/** sign-compare warnings

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all solvers/** sign-compare warnings, and re-enable the warning within that directory.
This another step for #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2654)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for the sole review.  It's okay if this sits for a few days before being reviewed; I think its worth waiting for the domain expert to get this done.

/cc @sammy-tri in case he is interested in making any comments.

**Comment by sammy-tri** [comment]
:lgtm: thanks for the cleanup!

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2654#-:-KLIoJ_It0t8XId7lZNZ:1745091307)*

**Comment by ggould-tri** [comment]
:lgtm: Good stuff all around.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/Constraint.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2654#-KLMCh1KRDPAJSPCTs4M:-KLMCh1KRDPAJSPCTs4N:1672642255) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecb7ebf4a3c6a492bfa5db9de91f02f9e07727a/drake/solvers/Constraint.h#L29)):*
> ```objc
>   void check(size_t num_constraints) {
>     static_cast<void>(num_constraints);
>     DRAKE_ASSERT(static_cast<size_t>(lower_bound_.size()) == num_constraints &&
> ```

There is in retrospect something offensive about a `size()` method that does not return `size_t`.  Nothing for it, though, I guess.  Blame eigen

---

*[drake/solvers/system_identification.cpp, line 270 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2654#-KLMDU5R42L2LUUH-a2a:-KLMDU5R42L2LUUH-a2b:-316612445) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecb7ebf4a3c6a492bfa5db9de91f02f9e07727a/drake/solvers/system_identification.cpp#L270)):*
> ```cpp
>   // Make sure we have as many data points as vars we are estimating, or else
>   // our solution will be meaningless.
>   DRAKE_ASSERT(num_data >= num_to_estimate);
> ```

oh hey, nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2654#-:-KLMD_ZOiK1WmBMyNqws:596106754)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/solvers/Constraint.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2654#-KLMCh1KRDPAJSPCTs4M:-KLMECwGhBmuaUs1MqML:-430254375) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecb7ebf4a3c6a492bfa5db9de91f02f9e07727a/drake/solvers/Constraint.h#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> There is in retrospect something offensive about a `size()` method that does not return `size_t`.  Nothing for it, though, I guess.  Blame eigen
</details>
FWIW, actually I disagree!   I think `size_t` is horrible and should never, ever be used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2654)*

**Pull request merged**
