### PR TITLE
Use cmake findmatlab add test

### PR DESCRIPTION
**Pull request by billhoffman**
This is a cleaned up version of the conversion to FindMatlab add_matlab_unit_test in drake.  Once this clears CI, I will put a PR in for the cmake repository, and when that is merged, I will update the repository and hash in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2097)

### CODE REVIEW

**Comment by billhoffman** [comment]
@drake-jenkins-bot retest this please

**Comment by billhoffman** [comment]
@RussTedrake can you take a look at this?  Or maybe try it out?  It should be passing all the tests with matlab now.  It uses the cmake FindMatlab test running code.

**Comment by billhoffman** [comment]
@drake-jenkins-bot retest this please

**Comment by billhoffman** [comment]
To move forward on this, the PR on cmake https://github.com/RobotLocomotion/cmake/pull/36 needs to be accepted.  Then I can update this PR to point to the correct hash for cmake.  Currently this PR points to the billhoffman cmake clone.

**Comment by billhoffman** [comment]
Windows build of this passes:  https://drake-cdash.csail.mit.edu/viewTest.php?onlypassed&buildid=9703

**Comment by RussTedrake** [comment]
The code here looks good.  I've accepted the cmake PR>

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2097#-:-KFduGDbgkoOU6SQjjAg:-1948722300)*

**Comment by billhoffman** [comment]
OK, I will update this PR to use the new hash from the cmake repository.

**Comment by billhoffman** [comment]
This passed all the tests and is using the correct hash for the cmake pod.  So, it should be ready to merge.  @RussTedrake

**Comment by RussTedrake** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2097)*

**Pull request merged**
