### PR TITLE
ReplaceBilinearTerms replace with an expression

### PR DESCRIPTION
**Pull request by hongkai-dai**
Previously we can only replace a bilinear product with another variable. Now we can replace the product with an expression.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7327)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-:-KxF3-ecsdrPnWZtwGII:bpno49v)*

**Comment by soonho-tri** [comment]
Checkpoint, PTAL.

---

Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/bilinear_product_util.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxIqnOTdH3yk1deePAs:-KxIqnOTdH3yk1deePAt:bnj5wjq) ([raw file](https://github.com/robotlocomotion/drake/blob/9a150f68ce88859f05b6022d9c1c200568bde7a7/drake/solvers/bilinear_product_util.cc#L115)):*
From the code, I can infer a precondition: 

> If W(i, j) is a composite expression (something more than a variable), it should not include an indeterminate.

Could you check if this is the case? Do you think this is OK or we want to handle the case where `W(i, j)` is a composite expression with indeterminates?
Either way, I think we need to explain it in the documentation (`.h` file).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-:-KxIsAgRvZSpMsEj7Fo1:biz4o9q)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/bilinear_product_util.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxIqnOTdH3yk1deePAs:-KxJUUb72OmPhkAgGOje:byk3bnr) ([raw file](https://github.com/robotlocomotion/drake/blob/9a150f68ce88859f05b6022d9c1c200568bde7a7/drake/solvers/bilinear_product_util.cc#L115)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

From the code, I can infer a precondition: 

> If W(i, j) is a composite expression (something more than a variable), it should not include an indeterminate.

Could you check if this is the case? Do you think this is OK or we want to handle the case where `W(i, j)` is a composite expression with indeterminates?
Either way, I think we need to explain it in the documentation (`.h` file).
</blockquote></details>

I do not think we have this pre-condition. The API of this function uses `symbolic::Expression` as the input, not a `symbolic::Polynomial`. The polynomial is only used internally.

You may check the test in https://github.com/hongkai-dai/drake/blob/bilinear_product_util_expression/drake/solvers/test/bilinear_product_util_test.cc#L200-L206. In this test `Z1` appears in both the expression `e`, and the term `W`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/bilinear_product_util.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxIqnOTdH3yk1deePAs:-KxJY0d19bXNwTFGa8Wa:b-1zgql0) ([raw file](https://github.com/robotlocomotion/drake/blob/9a150f68ce88859f05b6022d9c1c200568bde7a7/drake/solvers/bilinear_product_util.cc#L115)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I do not think we have this pre-condition. The API of this function uses `symbolic::Expression` as the input, not a `symbolic::Polynomial`. The polynomial is only used internally.

You may check the test in https://github.com/hongkai-dai/drake/blob/bilinear_product_util_expression/drake/solvers/test/bilinear_product_util_test.cc#L200-L206. In this test `Z1` appears in both the expression `e`, and the term `W`.
</blockquote></details>

Sorry, please ignore my previous comment. Yes we should require that `W` does not contain variables in either `x` or `y`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by soonho-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/bilinear_product_util.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxIqnOTdH3yk1deePAs:-KxJZZJwOnWk7ZZcat83:bcpql5q) ([raw file](https://github.com/robotlocomotion/drake/blob/9a150f68ce88859f05b6022d9c1c200568bde7a7/drake/solvers/bilinear_product_util.cc#L115)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, please ignore my previous comment. Yes we should require that `W` does not contain variables in either `x` or `y`.
</blockquote></details>

Not a problem. I'll wait for the new commits then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/bilinear_product_util.cc, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxIqnOTdH3yk1deePAs:-KxKBbisNTG0I8oZG_MV:bedsqp7) ([raw file](https://github.com/robotlocomotion/drake/blob/9a150f68ce88859f05b6022d9c1c200568bde7a7/drake/solvers/bilinear_product_util.cc#L115)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Not a problem. I'll wait for the new commits then.
</blockquote></details>

Done. Thanks for catching this bug!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by soonho-tri** [comment]
:lgtm:

@hongkai-dai , could you find a platform-reviewer for this PR? I happened to be today's platform-reviewer.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-:-KxO0nrUOjWfU3zOi7_q:b-jrtyeu)*

**Comment by hongkai-dai** [comment]
+@sherm1 Could you platform review this PR?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-:-KxOk4tr5NiX_xUVcV9U:bvq1yom)*

**Comment by sherm1** [comment]
:lgtm: (a few BTWs)

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/bilinear_product_util.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxTdAlqLcRKwEi_l_0f:-KxTdAlqLcRKwEi_l_0g:b-32aywi) ([raw file](https://github.com/robotlocomotion/drake/blob/1c46b41232f733dccf7c983500ee01f8db831360/drake/solvers/bilinear_product_util.cc#L102)):*
> ```cpp
>         throw runtime_error(oss.str());
>       }
>       // w_xy is the symbolic expression representing the bilinear term x * y.
> ```

BTW this comment seems off now - `w_xy_expr` is the expression and `w_xy` is the collection of variables in that expression?

---

*[drake/solvers/bilinear_product_util.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxTcjwXLQCiFIXyO26n:-KxTcjwXLQCiFIXyO26o:b3ewnz8) ([raw file](https://github.com/robotlocomotion/drake/blob/1c46b41232f733dccf7c983500ee01f8db831360/drake/solvers/bilinear_product_util.h#L23)):*
> ```objc
>  * entries.
>  * @param y The bilinear product between `x` and `y` will be replaced by the
>  * corresponding term in `W.Throws a runtime error if `y` contains duplicate
> ```

BTW missing back tick after W and missing space between sentences.

---

*[drake/solvers/test/bilinear_product_util_test.cc, line 178 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxTfwt37JjqZ9yTZZLc:-KxTfwt37JjqZ9yTZZLd:b-yifrfn) ([raw file](https://github.com/robotlocomotion/drake/blob/1c46b41232f733dccf7c983500ee01f8db831360/drake/solvers/test/bilinear_product_util_test.cc#L178)):*
> ```cpp
> }
> 
> TEST_F(BilinearProductTest, WIncludesXY) {
> ```

BTW per f2f please add a comment explaining what this test checks (as I understand it now it demonstrates that substitutions referencing the same variables are allowed as long as the expressions consist *only* of variables).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-:-KxTi1eAJRigmgSl-upZ:bj06pnf)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/bilinear_product_util.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxTdAlqLcRKwEi_l_0f:-KxTikLROFX-yf_2CLE-:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/1c46b41232f733dccf7c983500ee01f8db831360/drake/solvers/bilinear_product_util.cc#L102)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this comment seems off now - `w_xy_expr` is the expression and `w_xy` is the collection of variables in that expression?
</blockquote></details>

Done. Good catch.

---

*[drake/solvers/bilinear_product_util.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxTcjwXLQCiFIXyO26n:-KxTitub92g8SidRdMs7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c46b41232f733dccf7c983500ee01f8db831360/drake/solvers/bilinear_product_util.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW missing back tick after W and missing space between sentences.
</blockquote></details>

Done.

---

*[drake/solvers/test/bilinear_product_util_test.cc, line 178 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxTfwt37JjqZ9yTZZLc:-KxTjzrc10tHePzCbQ7K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c46b41232f733dccf7c983500ee01f8db831360/drake/solvers/test/bilinear_product_util_test.cc#L178)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f please add a comment explaining what this test checks (as I understand it now it demonstrates that substitutions referencing the same variables are allowed as long as the expressions consist *only* of variables).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/bilinear_product_util.cc, line 102 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxU8qpSCizLglM4bR6o:-KxU8qpSCizLglM4bR6p:blm195w) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc3b95015f3979e50d6ee59f4014dd2362ce086/drake/solvers/bilinear_product_util.cc#L102)):*
> ```cpp
>         throw runtime_error(oss.str());
>       }
>       // w_xy_expr is the symbolic expression representing the bilinear term x * y.
> ```

FYI, CI fails due to line >= 80 here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/bilinear_product_util.cc, line 102 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-KxU8qpSCizLglM4bR6o:-KxUOA-huNPGV5Yjl5jo:b-bn5n5z) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc3b95015f3979e50d6ee59f4014dd2362ce086/drake/solvers/bilinear_product_util.cc#L102)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, CI fails due to line >= 80 here.
</blockquote></details>

Done. Thanks for looking into it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7327#-:-KxUfIRVXffpSmWrYhaV:b-l70wzf)*

**Pull request merged**
