### PR TITLE
Port small examples to model-based port declarations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5431.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5515)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5515#-:-KfMNKlfqLZNRXbNQowW:b-83dehw)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Acrobot/acrobot_lcm.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5515#-KfMq2m-Vy3f8nmV4bGW:-KfMq2m-Vy3f8nmV4bGX:b2vev7y) ([raw file](https://github.com/robotlocomotion/drake/blob/539ff0c575677e8dcb7d8a6234a664851a8566c0/drake/examples/Acrobot/acrobot_lcm.cc#L76)):*
> ```cpp
> 
> AcrobotStateSender::AcrobotStateSender() {
>   this->DeclareInputPort(systems::kVectorValued, kNumJoints * 2);
> ```

BTW, do we have a plan to do a similar refactoring for this line in the future? For now we have two constants:
 - `kNumJoints (= 2)` in this file
 - `kNumCoordinates (= 4)` in `acrobot_state_vector.h`
and we rely on the fact that `kNumJoints * 2 == kNumCoordinates`. It seems that it's not so maintainable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5515)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a comment)

---

Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5515#-:-KfMqZj-wmP36WTu9Gfn:btfj096)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Acrobot/acrobot_lcm.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5515#-KfMq2m-Vy3f8nmV4bGW:-KfN8MglyTvtABgS0N2h:bfvtvbq) ([raw file](https://github.com/robotlocomotion/drake/blob/539ff0c575677e8dcb7d8a6234a664851a8566c0/drake/examples/Acrobot/acrobot_lcm.cc#L76)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, do we have a plan to do a similar refactoring for this line in the future? For now we have two constants:
 - `kNumJoints (= 2)` in this file
 - `kNumCoordinates (= 4)` in `acrobot_state_vector.h`
and we rely on the fact that `kNumJoints * 2 == kNumCoordinates`. It seems that it's not so maintainable.
</blockquote></details>

(1) I thought we had a `static_assert` to keep this sane, but I don't see it; that must have been in a different file.
(2) For an acrobot specifically, I think the number of joints is unlikely to change often enough to make the redundant numbers much of a maintenance burden in practice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5515)*

**Pull request merged**
