### PR TITLE
ScsSolver uses get_sparse_A from linear matrix.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in https://github.com/RobotLocomotion/drake/pull/16894#issue-1189204649

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

Previously the linear constraint is parsed row-by-row. Now because we return a column-major Eigen::SparseMatrix, we need to parse the constraint column by column. This change is non-trivial and error prone. @jwnimmer-tri could you validate that my change is correct? Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006#-:-N08b5UZ3S-oQxvr6Gav:b-f4wfz)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
FYI I have several time-consuming reviews already on my plate that I'll need to prioritize first.  If you'd like this reviewed this week, you might want to tag someone else (@aykut-tri ?) to work on checking the math here.  I'm happy to do it, but it would be next week.

**Comment by aykut-tri** [comment]
Sure, working on it.

**Review by aykut-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006)* status: 2 unresolved discussions, LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/scs_solver.cc, line 185 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CMxNz7Qw-b3R9SGi2:-N0CMxNz7Qw-b3R9SGi3:bo55y5n) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L185)):*
> ```cpp
>       if (!is_ub_finite && !is_lb_finite) {
>         // We use -1 to indicate that we won't add linear constraint when both
>         // bounds are infinity.
> ```

Minor: Do we really need this? Why not use the previous `if (is_ub_finite || is_lb_finite)` logic?



_Code quote:_
```cpp
      if (!is_ub_finite && !is_lb_finite) {
        // We use -1 to indicate that we won't add linear constraint when both
        // bounds are infinity.
        starting_row_indices[i] = -1;
      } else {
```
___
*[solvers/scs_solver.cc, line 189 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CNYQNAPlF8aGCBfYh:-N0CNYQNAPlF8aGCBfYi:b-n90mqh) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L189)):*
> ```cpp
>       } else {
>         starting_row_indices[i] = *A_row_count + num_linear_constraint_rows;
>         // I first add the constraint for lower bound, and then add the
> ```

BTW, do we use this narration in the code or prefer we/passive?



_Code quote:_
```cpp
I
```
___
*[solvers/scs_solver.cc, line 211 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CTcUl5U4a0pRjMIj_:-N0CTcUl5U4a0pRjMIja:b-a5jr16) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L211)):*
> ```cpp
>           // If lb != -∞, then the constraint -aᵀx + s = lb will be added to
>           // the matrix A, in the row lower_bound_row_index.
>           const int lower_bound_row_index = starting_row_indices[Ai_row_count];
> ```

Naive question: Is there a reason for not moving the `starting_row_indices` and `num_linear_constraint_rows` calculations into this loop?

I understand that we iterate over the linear constraints in the above loop (i.e., `for (int i = 0; i < linear_constraint.evaluator()->num_constraints(); ++i)`; however, seemingly, we assume that the matrix **A** is square, and we include all the constraints here when iterating over the columns.

**Review by aykut-tri — COMMENTED** [review]
The math and the implementation look accurate to me. I just left a few minor comments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006#-:-N0CWTIF7HZyVePTvfaW:bwwrpsq)* status: 2 unresolved discussions, LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Comment by aykut-tri** [comment]
*[solvers/scs_solver.cc, line 211 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CTcUl5U4a0pRjMIj_:-N0CY3n8C5a9TwCFoZ_h:b-d5hrd) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L211)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Naive question: Is there a reason for not moving the `starting_row_indices` and `num_linear_constraint_rows` calculations into this loop?

I understand that we iterate over the linear constraints in the above loop (i.e., `for (int i = 0; i < linear_constraint.evaluator()->num_constraints(); ++i)`; however, seemingly, we assume that the matrix **A** is square, and we include all the constraints here when iterating over the columns.
</blockquote></details>

Oh my bad, we neither have a square matrix assumption nor can do this without the first loop due to the sparsity, sorry.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with small BTW comments

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006#-:-N0Cn0xD8VMMkYPTUe1g:b3ysuo4)* status: 1 unresolved discussion, LGTM missing from assignee aykut-tri (waiting on @hongkai-dai)

___
*[solvers/scs_solver.cc, line 181 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0Cmjci1RBNIUkUyG8s:-N0CmjcjDLWyNMrqF_rW:b-hd4s15) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L181)):*
> ```cpp
>         linear_constraint.evaluator()->num_constraints());
>     for (int i = 0; i < linear_constraint.evaluator()->num_constraints(); ++i) {
>       const bool is_ub_finite{!std::isinf(ub(i))};
> ```

BTW Perhaps not important, but for `<cmath>`, "finite" may imply "not infinity" or "not NaN".

Consider being more direct in terms of this code: `needs_ub = !std::isinf(...), needs_lb = ...`
___
*[solvers/scs_solver.cc, line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CnffC91VaHqFWlvfC:-N0CnffC91VaHqFWlvfD:b-xjjccf) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L219)):*
> ```cpp
>           // matrix A, in the row upper_bound_row_index.
>           const int upper_bound_row_index =
>               is_lb_finite ? starting_row_indices[Ai_row_count] + 1
> ```

BTW Consider offsetting / incrementing index, rather than using nested `is finite` checks.

```
if (!is_lb_finite || !is_ub_finite) continue;  // If important for speed?
int row_index = starting_row_indices[Ai_row_count];
if (is_lb_finite) {
  A_triplets->emplace_back(row_index, xj_index, -it.value());
  ++row_index;
}
if (is_ub_finite) {
  A_triplets->emplace_back(row_index, xj_index, it.value());
}
```

**Comment by aykut-tri** [comment]
:lgtm:

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006)* status: 1 unresolved discussion (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[solvers/scs_solver.cc, line 185 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CMxNz7Qw-b3R9SGi2:-N0DkK8HDJOnEA6040UZ:b48bgko) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L185)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Minor: Do we really need this? Why not use the previous `if (is_ub_finite || is_lb_finite)` logic?
</blockquote></details>

We don't really needs this, but I want my `starting_row_indices` to always store a correct number, and if later I accidentally use starting_row_indices[i] when both lb[i] and ub[i] are infinity, then I should get an error with starting_row_indices[i] = -1, so this acts as a sanity check.
___
*[solvers/scs_solver.cc, line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CnffC91VaHqFWlvfC:-N0DlVt397L0Lgx_k4I3:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L219)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Consider offsetting / incrementing index, rather than using nested `is finite` checks.

```
if (!is_lb_finite || !is_ub_finite) continue;  // If important for speed?
int row_index = starting_row_indices[Ai_row_count];
if (is_lb_finite) {
  A_triplets->emplace_back(row_index, xj_index, -it.value());
  ++row_index;
}
if (is_ub_finite) {
  A_triplets->emplace_back(row_index, xj_index, it.value());
}
```
</blockquote></details>

Done, good call.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006)* status: 1 unresolved discussion (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[solvers/scs_solver.cc, line 211 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17006#-N0CTcUl5U4a0pRjMIj_:-N0Dm0RSCmDcZWPcniee:b-aej2qi) ([raw file](https://github.com/robotlocomotion/drake/blob/71e6021d935f87ddce10f2cda56b0dee4d4a8921/solvers/scs_solver.cc#L211)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Oh my bad, we neither have a square matrix assumption nor can do this without the first loop due to the sparsity, sorry.
</blockquote></details>

No worries, thanks for thinking hard and validate this code.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17006)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
