### PR TITLE
Generalized gain system to support a vector of gains containing different values.

### LINKED ISSUE #3743: System 2.0 PID Controller Needs to Support a Vector of Gains
System 2.0's PID controller currently assumes the same gain can be applied to every control signal. This will not work when the control signals are applied to very different systems like the steering angle and throttle speed of a car that require different gains.

Addressing this issue will require generalizing `gain.h`, and `pid_controller.h`, among others.

### PR DESCRIPTION
**Pull request by liangfok**
I also generalized the PID controller to make use of the generalized gain system.

Closes #3743.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3846)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please since I believe you're the original author of the gain system.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUU5CwjC5XdYMsVT181:b-8bz1xo)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/5934/ and is thus ready for review.

+@sammy-tri for platform review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUWMBVQSogZhGdYvi-E:bladwxd)*

**Comment by sammy-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUXrQJsFlFllleQA2IP:-KUXrQJsFlFllleQA2IQ:bxelmvb) ([raw file](https://github.com/robotlocomotion/drake/blob/5f019ffa3579028e4442366cfc3b5dcd629cd787/drake/systems/controllers/pid_controller.cc#L75)):*
> ```cpp
> bool PidController<T>::has_any_direct_feedthrough() const {
>   if (get_Kp() == VectorX<T>::Ones(get_Kp().size()) * 0 &&
>       get_Kd() == VectorX<T>::Ones(get_Kd().size()) * 0) {
> ```

VectorX<T>::Zero() might be slightly clearer here than multiplying Ones() times 0?

---

*[drake/systems/framework/primitives/gain.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUXpu9ySvtiPnVWI3fW:-KUXpu9ySvtiPnVWI3fX:b6d8i16) ([raw file](https://github.com/robotlocomotion/drake/blob/5f019ffa3579028e4442366cfc3b5dcd629cd787/drake/systems/framework/primitives/gain.h#L37)):*
> ```objc
>   Gain(const T& k, int size);
> 
>   /// Constructs a %Gain system the different gains can be applied to each input
> ```

The wording is slightly confusing...  should this read something like "where different gains can be applied to each input value"?

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUXqdMhB_YyEcSn0EA0:-KUXqdMhB_YyEcSn0EA1:bq3bbgp) ([raw file](https://github.com/robotlocomotion/drake/blob/5f019ffa3579028e4442366cfc3b5dcd629cd787/drake/systems/framework/primitives/test/gain_test.cc#L34)):*
> ```cpp
> 
>   // Verifies that Gain allocates no state variables in the context.
>   EXPECT_EQ(0, context->get_continuous_state()->size());
> ```

Should this be ASSERT_EQ?  Or would we want to keep running if this fails?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846)*

**Comment by liangfok** [comment]
@sammy-tri, I addressed your comments. PTAL. Thanks.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUXrQJsFlFllleQA2IP:-KUYjgASueEX64ITyenY:b2omo20) ([raw file](https://github.com/robotlocomotion/drake/blob/5f019ffa3579028e4442366cfc3b5dcd629cd787/drake/systems/controllers/pid_controller.cc#L75)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary>
> VectorX<T>::Zero() might be slightly clearer here than multiplying Ones() times 0?
</details>
Done. I didn't realize `Zero()` existed. Thanks.

---

*[drake/systems/framework/primitives/gain.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUXpu9ySvtiPnVWI3fW:-KUYjvbwpw3H3sJdD_bu:b-637xxp) ([raw file](https://github.com/robotlocomotion/drake/blob/5f019ffa3579028e4442366cfc3b5dcd629cd787/drake/systems/framework/primitives/gain.h#L37)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary>
> The wording is slightly confusing...  should this read something like "where different gains can be applied to each input value"?
</details>
Yes. Fixed. Thanks.

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUXqdMhB_YyEcSn0EA0:-KUYkXwTSFF3ZYYISDKU:bqh4snz) ([raw file](https://github.com/robotlocomotion/drake/blob/5f019ffa3579028e4442366cfc3b5dcd629cd787/drake/systems/framework/primitives/test/gain_test.cc#L34)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary>
> Should this be ASSERT_EQ?  Or would we want to keep running if this fails?
</details>
I think it's OK to keep it `EXPECT_EQ` since even if continuous state was accidentally allocated, the tests below should still pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUYlIZ5ezPtm9q9rdTV:blsyaaf)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUYo4u2NvQt357RyaTX:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Now waiting on @amcastro-tri's feature review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUYogDi8bxXBWLKjLWv:byxdm4a)*

**Comment by liangfok** [comment]
Numerous MATLAB-based unit tests segfaulted in https://drake-jenkins.csail.mit.edu/job/experimental/5967/compiler=gcc,label=linux_matlab,type=release/. I'm not sure why.

@drake-jenkins-bot retest this please.

**Comment by amcastro-tri** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/primitives/gain-inl.h, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUboUI2d1dE4nywAb76:-KUboUI2d1dE4nywAb77:b-4v4hbk) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1dac9dbf932e266fb36b2690e9afd306c3c935/drake/systems/framework/primitives/gain-inl.h#L55)):*
> ```objc
>   auto input_vector = this->EvalEigenVectorInput(context, 0);
>   System<T>::GetMutableOutputVector(output, 0) =
>       k_.array() * input_vector.array();
> ```

BTW, nice!

---

*[drake/systems/framework/primitives/gain.h, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbnOp6wZeclEFS9a2P:-KUbnOp6wZeclEFS9a2Q:b-egbqwm) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1dac9dbf932e266fb36b2690e9afd306c3c935/drake/systems/framework/primitives/gain.h#L40)):*
> ```objc
>   /// input value.
>   ///
>   /// @param[in] k the gain vector constants so that `y = k * u`.
> ```

BTW, maybe update to say something like "the gain vector constants so that y_i = k_i * u_i, with superscript i indicating the i-th component."

---

*[drake/systems/framework/primitives/gain.h, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbnmdgSUn0jA_VS01j:-KUbnmdgSUn0jA_VS01k:byoip16) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1dac9dbf932e266fb36b2690e9afd306c3c935/drake/systems/framework/primitives/gain.h#L44)):*
> ```objc
> 
>   /// Returns the gain constant.
>   const VectorX<T>& get_gain() const;
> ```

BTW, I'd still like to have the "scalar" constant behavior here when `k_.size() == 1`. What about having `const T& get_gain() const` (which would need to assert when `k_.size() != 1` and `const VectorX<T>& get_gains_vector() const`?

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 65 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUborS5cgP1BshytIBu:-KUborS5cgP1BshytIBv:baiyqsy) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1dac9dbf932e266fb36b2690e9afd306c3c935/drake/systems/framework/primitives/test/gain_test.cc#L65)):*
> ```cpp
>   const auto gain_system = make_unique<Gain<double>>(kGain, kSize);
>   const Eigen::Vector3d input_vector(1.0, 3.14, 2.18);
>   const Eigen::Vector3d expected_output(1.0 * kGain, 3.14 * kGain,
> ```

BTW, here you can also use multiplication by scalar to avoid repeating the same numbers like `expected_output = kGain * input_vector`

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbpD1LQT63wxVEOYm-:-KUbpD1LQT63wxVEOYm0:b-8bbuuc) ([raw file](https://github.com/robotlocomotion/drake/blob/6d1dac9dbf932e266fb36b2690e9afd306c3c935/drake/systems/framework/primitives/test/gain_test.cc#L76)):*
> ```cpp
>   const Eigen::Vector4d input_vector(9.81, 5.46, 16.24, 98.12);
>   const Eigen::Vector4d expected_output(
>       1.0 * 9.81, 2.0 * 5.46, 3.0 * 16.24, 4.0 * 98.12);
> ```

Also here, I would avoid writing this by hand. Why not the Eigen way `expected_output = gain_values.array() * input_vector.array()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846)*

**Comment by amcastro-tri** [comment]
Just a few minor comments. review pass done.

---

Reviewed 1 of 6 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUcleMOkPJ0yv_EE-Pn:-KUcleMOkPJ0yv_EE-Po:baxqjku) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L46)):*
> ```objc
>   PidController(const T& Kp, const T& Ki, const T& Kd, int size);
> 
>   /// Constructs a %PidController system where the gains can have more than one
> ```

BTW, "where the gains can have more than one value" maybe more like "where each gain can have a different value"?

---

*[drake/systems/controllers/pid_controller.h, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclna3yf2UgitaZoVy:-KUclna3yf2UgitaZoVz:b1rxd9h) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L49)):*
> ```objc
>   /// value.
>   ///
>   /// @param Kp the proportional vector constant.
> ```

The vector of proportional gain constants.

---

*[drake/systems/controllers/pid_controller.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclvhd0wGKtXflDDvv:-KUclvhd0wGKtXflDDvw:b-sefcc4) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L50)):*
> ```objc
>   ///
>   /// @param Kp the proportional vector constant.
>   /// @param Ki the integral vector constant.
> ```

The vector of integral gain constants.

---

*[drake/systems/controllers/pid_controller.h, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclsTiyYrj1kgn-V-Z:-KUclsTiyYrj1kgn-V-_:b-rebebs) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L51)):*
> ```objc
>   /// @param Kp the proportional vector constant.
>   /// @param Ki the integral vector constant.
>   /// @param Kd the derivative vector constant.
> ```

The vector of derivative constants.

---

*[drake/systems/controllers/pid_controller.h, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclz_8D4wcfeY_6GUC:-KUclz_8D4wcfeY_6GUD:b6uyjvs) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L58)):*
> ```objc
> 
>   /// Returns the proportional constant.
>   const VectorX<T>& get_Kp() const;
> ```

BTW, probably it'd be good to keep the "scalar" interface? and have a "get_Kp_vector()"? same comment here that I made in "gain.h"

---

*[drake/systems/controllers/pid_controller.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUcmBu6i7I4QJDmeK1z:-KUcmBu6i7I4QJDmeK2-:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L61)):*
> ```objc
> 
>   /// Returns the integral constant.
>   const VectorX<T>& get_Ki() const;
> ```

ditto

---

*[drake/systems/controllers/pid_controller.h, line 64 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUcmCjlTzXpn129lLmB:-KUcmCjlTzXpn129lLmC:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L64)):*
> ```objc
> 
>   /// Returns the derivative constant.
>   const VectorX<T>& get_Kd() const;
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUcnC7cbAuMp1GvY4jY:b-b9jgci)*

**Comment by liangfok** [comment]
@amcastro-tri I addressed your comments. PTAL. Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUcleMOkPJ0yv_EE-Pn:-KUcoFXlMLi5ugK9ToL8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L46)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, "where the gains can have more than one value" maybe more like "where each gain can have a different value"?
</details>
Done.

---

*[drake/systems/controllers/pid_controller.h, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclna3yf2UgitaZoVy:-KUcoMbFw9odvxrhg-7O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> The vector of proportional gain constants.
</details>
Done.

---

*[drake/systems/controllers/pid_controller.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclvhd0wGKtXflDDvv:-KUcoYPKZSpghDrSX0Y7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> The vector of integral gain constants.
</details>
Done.

---

*[drake/systems/controllers/pid_controller.h, line 51 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclsTiyYrj1kgn-V-Z:-KUco_K73MIXCqBkSCaV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L51)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> The vector of derivative constants.
</details>
Done.

---

*[drake/systems/controllers/pid_controller.h, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUclz_8D4wcfeY_6GUC:-KUd0ff3lJmdEr0uNDNs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L58)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, probably it'd be good to keep the "scalar" interface? and have a "get_Kp_vector()"? same comment here that I made in "gain.h"
</details>
Done.

---

*[drake/systems/controllers/pid_controller.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUcmBu6i7I4QJDmeK1z:-KUd0gR-CAILG3IYE28l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L61)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> ditto
</details>
Done.

---

*[drake/systems/controllers/pid_controller.h, line 64 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUcmCjlTzXpn129lLmB:-KUd0h7ig-vEhGJVEqu0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/controllers/pid_controller.h#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> ditto
</details>
Done.

---

*[drake/systems/framework/primitives/gain.h, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbnOp6wZeclEFS9a2P:-KUcoy2NKbtBGhyAwfYl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/framework/primitives/gain.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, maybe update to say something like "the gain vector constants so that y_i = k_i * u_i, with superscript i indicating the i-th component."
</details>
Done.

---

*[drake/systems/framework/primitives/gain.h, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbnmdgSUn0jA_VS01j:-KUcr8ldwXjFY2ebYUPj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/framework/primitives/gain.h#L44)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, I'd still like to have the "scalar" constant behavior here when `k_.size() == 1`. What about having `const T& get_gain() const` (which would need to assert when `k_.size() != 1` and `const VectorX<T>& get_gains_vector() const`?
</details>
Done.

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 65 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUborS5cgP1BshytIBu:-KUcz8LRVEw9I93hRUTo:b-i21bbo) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/framework/primitives/test/gain_test.cc#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, here you can also use multiplication by scalar to avoid repeating the same numbers like `expected_output = kGain * input_vector`
</details>
Thanks. Done.

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbpD1LQT63wxVEOYm-:-KUczInvayXAvlk9Beac:brg2bwt) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/framework/primitives/test/gain_test.cc#L76)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Also here, I would avoid writing this by hand. Why not the Eigen way `expected_output = gain_values.array() * input_vector.array()`?
</details>
An argument could be made that we want to avoid testing code against itself, but I agree in this case it's so simple might as well do it. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUd2_wgiZF4I-wTzu-n:b-28jvg9)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/6031/ and is thus ready for feature review.

---

Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUlJw9fXVETQX9KApWG:b4bptiw)*

**Comment by amcastro-tri** [comment]
Thank you @liangfok. Just a few more comments.

---

Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.cc, line 89 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqy8wWBaurI2-OUTtJ:-KUqy8wXIUXIRX2gir2Y:b-khxc63) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/controllers/pid_controller.cc#L89)):*
> ```cpp
> template <typename T>
> bool PidController<T>::has_any_direct_feedthrough() const {
>   if (get_Kp_vector() == VectorX<T>::Zero(get_Kp_vector().size()) &&
> ```

here you can say `get_Kp_vector().isZero()`

---

*[drake/systems/framework/primitives/gain-inl.h, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqxisEipPQVvRwqnno:-KUqxisEipPQVvRwqnnp:bsuefjy) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/framework/primitives/gain-inl.h#L35)):*
> ```objc
> template <typename T>
> const T& Gain<T>::get_gain() const {
>   T first_value = k_[0];
> ```

here you can use Eigen's one liner `k_.isConstant()`

---

*[drake/systems/framework/primitives/gain-inl.h, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqxAlkGTHf9xWnTHjs:-KUqxAlkGTHf9xWnTHjt:b-19q67e) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/framework/primitives/gain-inl.h#L40)):*
> ```objc
>   for (int i = 1; i < k_.size(); ++i) {
>     if (first_value != k_[i]) {
>       throw std::runtime_error("drake::systems::Gain::get_gain(): Error! The "
> ```

BTW, would DRAKE_ABORT_MSG be better? for the consistency of messages.

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbpD1LQT63wxVEOYm-:-KUqySQcBtulFRDLECw-:b-ld1wma) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/framework/primitives/test/gain_test.cc#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> An argument could be made that we want to avoid testing code against itself, but I agree in this case it's so simple might as well do it. Done.
</details>
I agree. Though I think this test is also valuable at testing the whole System 2.0 framework for this simple math.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUqykNqzH5_1-rTATXE:b-mamryp)*

**Comment by liangfok** [comment]
@amcastro-tri, I addressed your comments. PTAL. Thanks!

---

Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.cc, line 89 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqy8wWBaurI2-OUTtJ:-KUr02Hscjnr0prRWDiu:bo5nztk) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/controllers/pid_controller.cc#L89)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> here you can say `get_Kp_vector().isZero()`
</details>
Nice. Done.

---

*[drake/systems/framework/primitives/gain-inl.h, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqxisEipPQVvRwqnno:-KUr12VMAqii4r-SWGxr:bo5nztk) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/framework/primitives/gain-inl.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> here you can use Eigen's one liner `k_.isConstant()`
</details>
Nice. Done.

---

*[drake/systems/framework/primitives/gain-inl.h, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqxAlkGTHf9xWnTHjs:-KUr13_ZgskMEEE0mIzx:brgq1k0) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/framework/primitives/gain-inl.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, would DRAKE_ABORT_MSG be better? for the consistency of messages.
</details>
Sure. Done.

---

*[drake/systems/framework/primitives/test/gain_test.cc, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUbpD1LQT63wxVEOYm-:-KUr162gxR0-B4DTBbeF:b-81nlyc) ([raw file](https://github.com/robotlocomotion/drake/blob/9c41904efe8212387c92e3a879690be058ca1da5/drake/systems/framework/primitives/test/gain_test.cc#L76)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I agree. Though I think this test is also valuable at testing the whole System 2.0 framework for this simple math.
</details>
SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUrAeACUPlVE85gEmkF:b-rri6rn)*

**Comment by amcastro-tri** [comment]
Just one small comment left. 

---

Reviewed 1 of 5 files at r5.
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/gain-inl.h, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqxAlkGTHf9xWnTHjs:-KUrB4TsXAL8H15i6ww_:bwzjxa4) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/framework/primitives/gain-inl.h#L40)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Sure. Done.
</details>
DRAKE_ABORT_MSG already prints the file, line and function name. You would only need to provide the message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUrBKHhBRhdXU_nXEOv:b-v47vlw)*

**Comment by liangfok** [comment]
@amcastro-tri I addressed your comment. PTAL. Thanks!!

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/gain-inl.h, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-KUqxAlkGTHf9xWnTHjs:-KUrBbzm89ZTQ6m3LN_Z:b-qu6n94) ([raw file](https://github.com/robotlocomotion/drake/blob/564b1c513cf0c3e425ecac5a5fdb320929517585/drake/systems/framework/primitives/gain-inl.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> DRAKE_ABORT_MSG already prints the file, line and function name. You would only need to provide the message.
</details>
Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUrBea1rPDIpD11PYBM:b-rgi9bj)*

**Comment by amcastro-tri** [comment]
thanks! :lgtm: 

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3846#-:-KUrCAEZMljrLHjnTgX2:bmvgeyv)*

**Comment by liangfok** [comment]
Yay! Now waiting on CI to complete.

@drake-jenkins-bot retest this please.

**Pull request merged**
