### PR TITLE
[multibody] GeometryContactData takes over deformable caching

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21623 and therefore also #20545.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri this was as far as I got for today.  Some tests are failing, but I haven't investigated at all yet.  Possibly you could chase down the problems more quickly than me?  The PR is open for pushes if you like, or just ping a comment in Reviewable is good, too.  I'll probably work on landing a few other PRs before I cycle back to this one.

**Review by xuchenhan-tri — COMMENTED** [review]
Looking now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-:-O0GFFw-3K--Vzc3bTdI:bcc08gq)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2611 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0GKWPE0gJrMY55PJRy:-O0GKWPE0gJrMY55PJRz:b3nly9r) ([raw file](https://github.com/RobotLocomotion/drake/blob/3da55950ce51120a3646e2d15dc666e4dd6d3691/multibody/plant/multibody_plant.cc#L2611)):*
> ```cpp
>   result->point_pairs.clear();
>   result->surfaces.clear();
>   if (num_collision_geometries() == 0) {
> ```

I believe the issue is here. You can't short circuit the entire computation if `num_collision_geometries() == 0`. `DeformableContact` needs to be computed if there's at least one deformable geometry in the world, and deformable geometries is currently not counted towards `num_collision_geometries()`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge"

___
*[`multibody/plant/multibody_plant.cc` line 2611 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0GKWPE0gJrMY55PJRy:-O0GLxxJ2RjNtMyQZcBn:b-z6goyx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3da55950ce51120a3646e2d15dc666e4dd6d3691/multibody/plant/multibody_plant.cc#L2611)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I believe the issue is here. You can't short circuit the entire computation if `num_collision_geometries() == 0`. `DeformableContact` needs to be computed if there's at least one deformable geometry in the world, and deformable geometries is currently not counted towards `num_collision_geometries()`.
</blockquote></details>

Thank you!

I will circle back soon and poke at this more.

My initial reaction is that `num_collision_geometries()` should change to return non-zero when deformable has geometry that can collide with things, but I'll give it a closer look once I pull up this branch again.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2611 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0GKWPE0gJrMY55PJRy:-O0GNbMJ0Vdcwd4ya0Rn:bnm5fsl) ([raw file](https://github.com/RobotLocomotion/drake/blob/3da55950ce51120a3646e2d15dc666e4dd6d3691/multibody/plant/multibody_plant.cc#L2611)):*
> My initial reaction is that `num_collision_geometries()` should change to return non-zero when deformable has geometry that can collide with things...

That definitely makes sense to me, but you just know that something's gotta break if we make that change and it needs to be done carefully.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2611 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0GKWPE0gJrMY55PJRy:-O0GOZBSBJWqT2KoAtE2:bywmarg) ([raw file](https://github.com/RobotLocomotion/drake/blob/3da55950ce51120a3646e2d15dc666e4dd6d3691/multibody/plant/multibody_plant.cc#L2611)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> My initial reaction is that `num_collision_geometries()` should change to return non-zero when deformable has geometry that can collide with things...

That definitely makes sense to me, but you just know that something's gotta break if we make that change and it needs to be done carefully.
</blockquote></details>

I'll rebase this atop #21357 and do some experiments.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2611 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0GKWPE0gJrMY55PJRy:-O0GVBej9ciI5H8utcsL:bmnn0q1) ([raw file](https://github.com/RobotLocomotion/drake/blob/3da55950ce51120a3646e2d15dc666e4dd6d3691/multibody/plant/multibody_plant.cc#L2611)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll rebase this atop #21357 and do some experiments.
</blockquote></details>

I ran a subset of tests with that fix, and they all passed.  We'll see what full CI says.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 2611 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0GKWPE0gJrMY55PJRy:-O0KOSerEG2My1LwD6-q:br2sbr6) ([raw file](https://github.com/RobotLocomotion/drake/blob/3da55950ce51120a3646e2d15dc666e4dd6d3691/multibody/plant/multibody_plant.cc#L2611)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I ran a subset of tests with that fix, and they all passed.  We'll see what full CI says.
</blockquote></details>

Looking good!

**Review by jwnimmer-tri — COMMENTED** [review]
Okay, I think this is ready for an official feature review now.

> Reviewed 5 of 6 files at r4, 28 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-:-O0KmXCu48F_Fn6ShmEW:bk9suyi)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.h` line 4923 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0KlupjEmCJsceEjiAs:-O0KlupjEmCJsceEjiAt:bx0m07r) ([raw file](https://github.com/RobotLocomotion/drake/blob/a95b2b2be31c558757a342baeb2bd701f1a310f2/multibody/plant/multibody_plant.h#L4923)):*
> ```objc
>   int num_visual_geometries() const { return num_visual_geometries_; }
> 
>   /// Returns the number of geometries registered for contact modeling.
> ```

BTW I am not exactly sure whether or what to say here about deformables.  Suggestions welcome.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: feature
+@EricCousineau-TRI for platform review please.

> Reviewed 2 of 6 files at r4, 1 of 28 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-:-O0M-MM3AcFerr4Czfx5:b-q0jxdx)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/plant/multibody_plant.h` line 4923 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0KlupjEmCJsceEjiAs:-O0LzliU7aL4iBA2ypi6:b95n82b) ([raw file](https://github.com/RobotLocomotion/drake/blob/a95b2b2be31c558757a342baeb2bd701f1a310f2/multibody/plant/multibody_plant.h#L4923)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I am not exactly sure whether or what to say here about deformables.  Suggestions welcome.
</blockquote></details>

I think the current wording is fine. With the new logic though, the snake case is no longer styleguide compliant. Consider putting in a TODO.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/plant/multibody_plant.h` line 4923 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0KlupjEmCJsceEjiAs:-O0MEztG-w6DB_Aw6LYH:b-mcp16h) ([raw file](https://github.com/RobotLocomotion/drake/blob/a95b2b2be31c558757a342baeb2bd701f1a310f2/multibody/plant/multibody_plant.h#L4923)):*
> ... the snake case is no longer styleguide compliant.

Because of the "no more than 5 lines" part?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 3 of 6 files at r4, 28 of 28 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-:-O0MTgHu0gvXHhoGfeZO:bcpz082)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21619)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform)

___
*[`multibody/plant/multibody_plant.h` line 4923 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21619#-O0KlupjEmCJsceEjiAs:-O0PlOK71tOoPK1DUkO5:btuxnc5) ([raw file](https://github.com/RobotLocomotion/drake/blob/a95b2b2be31c558757a342baeb2bd701f1a310f2/multibody/plant/multibody_plant.h#L4923)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... the snake case is no longer styleguide compliant.

Because of the "no more than 5 lines" part?
</blockquote></details>

Yeah I guess it's pretty borderline.

**Pull request merged**
