### PR TITLE
Simplify several third-party inclusions

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Refactor how we import several third-party packages to follow the pattern (already in use elsewhere) where we externally declare the library directory, such that we can share the build rules across platforms. This reduces the total number of files that need to be maintained.

For the sake of simplicity and consistency, also use `-rpath` in more places. (Mostly this happens as a consequence of the simplification, as macOS needs it explicitly while it is potentially superfluous on Ubuntu.)

Last, fix some manylinux imports which were pulling system versions rather than the versions built as part of the wheel build.

+@jwnimmer-tri for feature review, please.

Towards #15958.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16752)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Could you hold off on the yaml changes for now?  My plan is to re-apply #16728 so that we'll always build yaml-cpp from source, which will render that portion of this change moot.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

I tested that even though some of the locally-built unit tests on Ubuntu (e.g., in `drake/systems/sensors/...`) have an extra runpath entry for `/usr/lib/x86_64-linux-gnu`, our runpaths in the `make install` targets are unchanged per the `linux_fix_rpaths` function in `installer.py`.

> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16752#-:-Mxku6_p-sGMwv6Ecinv:b5d2eq)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/workspace/double_conversion/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxkrKmi4TAEn36ICCAZ:-MxkrKmi4TAEn36ICCA_:b-p6yq39) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/double_conversion/repository.bzl#L12)):*
> ```Starlark
> 
>     if os_result.is_macos:
>         lib = "{}/opt/double-conversion/lib".format(os_result.homebrew_prefix)
> ```

nit Maybe call this `libdir` for improved clarity in this file and consistency with the name in `vars.bzl`?
___
*[tools/workspace/libjpeg/repository.bzl, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-Mxkqwr77lEpbPmwaSwn:-Mxkqwr77lEpbPmwaSwo:b-p6yq39) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/libjpeg/repository.bzl#L14)):*
> ```Starlark
> 
>     if os_result.is_macos:
>         lib = "{}/opt/jpeg/lib".format(os_result.homebrew_prefix)
> ```

nit Maybe call this `libdir` for improved clarity in this file and consistency with the name in `vars.bzl`?
___
*[tools/workspace/vtk/repository.bzl, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-Mxkpk1n-70KJ3i-THp5:-Mxkpk1oC1I6cMngUwIj:b-tcxydk) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/vtk/repository.bzl#L91)):*
> ```Starlark
>                 "-L{}".format(lib_dir),
>                 "-l{}-{}".format(name, VTK_MAJOR_MINOR_VERSION),
>                 "-Wl,-rpath,{}".format(lib_dir),
> ```

For manylinux we are statically linking, so I'm not sure why an rpath is coming into play here?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16752)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/workspace/double_conversion/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxkrKmi4TAEn36ICCAZ:-MxoNl-nEyx7YQ1guuWL:b1yyz9y) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/double_conversion/repository.bzl#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Maybe call this `libdir` for improved clarity in this file and consistency with the name in `vars.bzl`?
</blockquote></details>

Maybe. I was copying `suitesparse/repository.bzl`, which uses `lib`; probably that should change also.
___
*[tools/workspace/vtk/repository.bzl, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-Mxkpk1n-70KJ3i-THp5:-MxoO4IlElhLMBB__-Hz:bw0y48z) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/vtk/repository.bzl#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For manylinux we are statically linking, so I'm not sure why an rpath is coming into play here?
</blockquote></details>

Done. I was mostly trying to be consistent, but agreed it should be safe to omit here.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/workspace/double_conversion/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxkrKmi4TAEn36ICCAZ:-MxoOxH46c2d5kQjcJ8Z:bzhe1dd) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/double_conversion/repository.bzl#L12)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Maybe. I was copying `suitesparse/repository.bzl`, which uses `lib`; probably that should change also.
</blockquote></details>

Also, changing it is going to require a bunch of lines to get split that are currently one line...

**Comment by mwoehlke-kitware** [comment]
___
*[tools/workspace/double_conversion/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxkrKmi4TAEn36ICCAZ:-MxoPRQn0y1RADg6Tp2r:b-fxaq0g) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/double_conversion/repository.bzl#L12)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Also, changing it is going to require a bunch of lines to get split that are currently one line...
</blockquote></details>

(Okay, maybe just one...)

**Comment by mwoehlke-kitware** [comment]
___
*[tools/workspace/double_conversion/repository.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxkrKmi4TAEn36ICCAZ:-MxoPhVP0J-qM_xtwuW5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/12ad2d84f0ee428e09a3f885dd54252c11d14dca/tools/workspace/double_conversion/repository.bzl#L12)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

(Okay, maybe just one...)
</blockquote></details>

Done.

**Comment by mwoehlke-kitware** [comment]
> Could you hold off on the yaml changes for now?

The problem is I need to be able to account for the upcoming `macos_wheel` platform; essentially, all the changes here are to make it easier to add that platform. Right now, this has an "obvious" way to do that... although as noted in #16756, it looks like that approach will become wrong. It would be better if #16756 could properly transmute the `manylinux` path into a no-op stub which `macos_wheel` can then use without needing to make changes.

**Comment by mwoehlke-kitware** [comment]
(Resolved by changes to #16756; changes to `yaml_cpp` in this PR have been dropped.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: 

+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16752#-:-Mxp4TNa8s5YHpcfPPRM:bcy9wbl)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks! Just nit on lint.

> Reviewed 4 of 10 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16752#-:-MxpZHyABhEj0HnjIc4E:bovmyh3)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[tools/workspace/double_conversion/repository.bzl, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxpYyfd4TOcYZjFJOa5:-MxpYyfd4TOcYZjFJOa6:btouub4) ([raw file](https://github.com/robotlocomotion/drake/blob/7eed5b53eab378be4ce6de2b0856ac2fa251eebe/tools/workspace/double_conversion/repository.bzl#L1)):*
> ```Starlark
> # -*- python -*-
> ```

nit CI requires linting fixes.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16752)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[tools/workspace/double_conversion/repository.bzl, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16752#-MxpYyfd4TOcYZjFJOa5:-MxpyfyeB8wMRvwvC4gA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7eed5b53eab378be4ce6de2b0856ac2fa251eebe/tools/workspace/double_conversion/repository.bzl#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit CI requires linting fixes.
</blockquote></details>

Done.

**Pull request merged**
