### PR TITLE
[bindings] Remove C++ function point coverage report

### LINKED ISSUE #19143: Remove bindings coverage report
See #19140 and #19128 for a little background.

My hypothesis is that approximately nobody ever uses these reports.  I did use them a little bit a few years ago when checking on MbP bindings or something, but probably nobody has done so since.  In the meantime, they have caused build system & CI headaches as we need to keep maintaining them as conditions evolve.  Probably best to drop them at this point.

I would like to split up our documentation header into multiple headers to improve build throughput.  Doing that with these XML files still in play is likely to be more difficult.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19143.

Reverts large parts of #12040.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19147)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both code reviews, please.

+@EricCousineau-TRI for final approval to merge, as you were involved with the original feature.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: maybe a few stray comments to update.

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19147#-:-NSMiLHD6bx860evvr9t:bgmzznr)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19147#-NSMeSCTCBcBcr-eu73V:-NSMeSCTCBcBcr-eu73W:bmua1ly) (no related file):*
Found some places where perhaps code could also go away, or maybe just comments need updating:

https://github.com/jwnimmer-tri/drake/blob/82d8460973cd39defac2b6cee5d696a860237973/setup/ubuntu/source_distribution/install_prereqs.sh#L113

https://github.com/jwnimmer-tri/drake/blob/82d8460973cd39defac2b6cee5d696a860237973/bindings/pydrake/multibody/tree_py.cc#L100-L101

https://github.com/jwnimmer-tri/drake/blob/82d8460973cd39defac2b6cee5d696a860237973/multibody/tree/multibody_tree_indexes.h#L22-L23

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19147)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19147#-NSMeSCTCBcBcr-eu73V:-NSMipZv2weJhRGsRQej:b-f8olcy) (no related file):*
> install_prereqs.sh#L113

Done.

> tree_py.cc#L100-L101
> multibody_tree_indexes.h#L22-L23

These comments are not referring to the xml coverage report; they are referring to human eyeballs reasoning about the coverage.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19147)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI do you have time to take a look?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, thanks!

> Reviewed 22 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19147#-:-NTFV1xl65PBix49apNn:bpqxd5f)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Pull request merged**
