### PR TITLE
adding a MBT version of the differential inverse kinematics.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
cc @amcastro-tri for the MBT CalcRelativeTransform change.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8122)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@avalenzu for feature review. thanks! 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5swlrtJ_K_KS5HzFoj:b-1co1l7)*

**Comment by siyuanfeng-tri** [comment]
@amcastro-tri i think the previous version of CalcRelativeTransform is slightly bugged, as it omits the local transform from frame_A to it's attached body frame, and similarly for frame_B. I didn't attempt to go through the rest of the MBT code for similar failure modes though.  

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5swzUAxTZnIJendFWd:bxo16jr)*

**Comment by siyuanfeng-tri** [comment]
-@avalenzu  
+@hongkai-dai for feature review since andres is on vacation this week. thanks hongkai

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5tDIIR4bG53hZ7S9rW:bsgx8iv)*

**Comment by amcastro-tri** [comment]
Nice! very good catch! would you be able to add a unit test in `multibody_tree_test.cc`? A few small comments.

---

Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 244 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5t7UKuZZZ-whk0YS_C:-L5t7UKuZZZ-whk0YS_D:b-e4g1bp) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.cc#L244)):*
> ```cpp
>       dynamic_cast<const multibody::MultibodyTreeContext<double>&>(context);
>   return DoDifferentialInverseKinematics(mbt_context.get_positions(),
>                                          mbt_context.get_velocities(), X_WE,
> ```

no need for the `dynamic_cast`, you can ask `robot` the same question: `robot.get_num_positions()`, `robot.get_num_velocities()`.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 281 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDiLpl4heMseew1MI:-L5tDiLpl4heMseew1MJ:ba08k7v) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L281)):*
> ```objc
>  * that tracks frame E's spatial velocity.
>  * q_current and v_current are taken from @p context. V is computed by first
>  * transforming @p V_WE to V_WE_E, then taking the element-wise product between
> ```

just curious, why do the math with `V_WE_E` instead of `V_WE_W`?

---

*[manipulation/planner/differential_inverse_kinematics.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDMj_x8WGThoWDoYb:-L5tDMj_x8WGThoWDoYc:bk37wuy) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L282)):*
> ```objc
>  * q_current and v_current are taken from @p context. V is computed by first
>  * transforming @p V_WE to V_WE_E, then taking the element-wise product between
>  * V_WE_E and the gains in @p parameters, and only selecting the non zero
> ```

These "gains" seem more like relaxation factors? probably worth commenting on that? (so that users know how to choose them). Are they ideally equal to one but as things fail you start making them smaller?

---

*[manipulation/planner/differential_inverse_kinematics.h, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5t5w_jeboOX8kX3INF:-L5t5w_jeboOX8kX3ING:bn64rbp) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L306)):*
> ```objc
>  * q_current and v_current are taken from @p cache. V_WE is computed by
>  * ComputePoseDiffInCommonFrame(X_WE, X_WE_desired) / dt, where X_WE is computed
>  * from @p cache, and dt is taken from @p parameters.
> ```

cache --> context?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5t2rlbJhZ87lnfz9HJ:b-ljxa03)*

**Comment by amcastro-tri** [comment]
another thought. Maybe worth splitting the MBT API's and unit tests into different files? that way we could remove these RBT dependencies from now. It seems odd to see RBT and MBT dependencies in the BUILD files when (I believe?) not needed. It'd look like you did all the interesting math with plain matrices and you only call RBT/MBT methods from the higher API's. So it'd seem plausible to make the split.

---

Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5tEjb3m8zZM9btT0Do:b-2wl9za)*

**Comment by siyuanfeng-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 281 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDiLpl4heMseew1MI:-L5tHlhW3IadlZNPk2A_:btfxv9v) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L281)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

just curious, why do the math with `V_WE_E` instead of `V_WE_W`?
</blockquote></details>

oh, the gains are in the E frame. 

---

*[manipulation/planner/differential_inverse_kinematics.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDMj_x8WGThoWDoYb:-L5tHuOlUoHYX0DrGH1a:bt8k15q) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L282)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

These "gains" seem more like relaxation factors? probably worth commenting on that? (so that users know how to choose them). Are they ideally equal to one but as things fail you start making them smaller?
</blockquote></details>

its a mechanism for saying relative importance. setting it to zero means i don't care about that axis at all (becomes unconstrained)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 281 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDiLpl4heMseew1MI:-L5tO4hAt2T5vOnhdJxA:b-yymn2s) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L281)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

oh, the gains are in the E frame. 
</blockquote></details>

Ah! I see the reason now (like I want the gripper to move forward but not sideways, in the E frame, or things like that). Maybe worth documenting this fact (at least not obvious to me :-) )

---

*[manipulation/planner/test/differential_inverse_kinematics_test.cc, line 166 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tNxzt8dK7CWuVWywF:-L5tNxzt8dK7CWuVWywG:b-c8ywo1) ([raw file](https://github.com/robotlocomotion/drake/blob/6129e3b7a077af87df439372be6fabf1e2a889cd/manipulation/planner/test/differential_inverse_kinematics_test.cc#L166)):*
> ```cpp
>                                       *params_);
>   EXPECT_TRUE(CompareMatrices(rbt_result.joint_velocities.value(),
>                               mbt_result.joint_velocities.value(), 1e-8));
> ```

is this result with such a large tolerance expected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDMj_x8WGThoWDoYb:-L5tOS8jlGWuwVFj6YR7:b-f479hu) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L282)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

its a mechanism for saying relative importance. setting it to zero means i don't care about that axis at all (becomes unconstrained)
</blockquote></details>

gotcha. Probably worth documenting. On my first read I thought with "gains" you meant some sort of PD gain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 244 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5t7UKuZZZ-whk0YS_C:-L5tbR-z6JWdmRR2fIi5:b-sg6fwb) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.cc#L244)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

no need for the `dynamic_cast`, you can ask `robot` the same question: `robot.get_num_positions()`, `robot.get_num_velocities()`.
</blockquote></details>

i am trying to get q and v from context here. is there a preferred way without explicitly casting? 

---

*[manipulation/planner/differential_inverse_kinematics.h, line 281 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDiLpl4heMseew1MI:-L5thoqRpwmQvzb_bn9T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L281)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Ah! I see the reason now (like I want the gripper to move forward but not sideways, in the E frame, or things like that). Maybe worth documenting this fact (at least not obvious to me :-) )
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tDMj_x8WGThoWDoYb:-L5thp7oNpfP6iyy3wYj:b3uf02a) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L282)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

gotcha. Probably worth documenting. On my first read I thought with "gains" you meant some sort of PD gain.
</blockquote></details>

adding a bit doc in the parameters. 

---

*[manipulation/planner/differential_inverse_kinematics.h, line 306 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5t5w_jeboOX8kX3INF:-L5tndSRxHgSNzqb9-dA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.h#L306)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

cache --> context?
</blockquote></details>

Done.

---

*[manipulation/planner/test/differential_inverse_kinematics_test.cc, line 166 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tNxzt8dK7CWuVWywF:-L5tnf7Of1WTLAA4SsMV:b-jzwso6) ([raw file](https://github.com/robotlocomotion/drake/blob/6129e3b7a077af87df439372be6fabf1e2a889cd/manipulation/planner/test/differential_inverse_kinematics_test.cc#L166)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is this result with such a large tolerance expected?
</blockquote></details>

this seems to go away by switching to osqp. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 4 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 244 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5t7UKuZZZ-whk0YS_C:-L5tpORCa0ew-ueUiaQq:b1pxdes) ([raw file](https://github.com/robotlocomotion/drake/blob/67fc6925a5626ffc2f2035ea017f47521cafef7c/manipulation/planner/differential_inverse_kinematics.cc#L244)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i am trying to get q and v from context here. is there a preferred way without explicitly casting? 
</blockquote></details>

never mind, I misread. There is no better way currently. I can add an MBT method.

---

*[manipulation/planner/test/differential_inverse_kinematics_test.cc, line 166 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5tNxzt8dK7CWuVWywF:-L5tqyl5wuarOZmn0Rw3:bvcymmp) ([raw file](https://github.com/robotlocomotion/drake/blob/6129e3b7a077af87df439372be6fabf1e2a889cd/manipulation/planner/test/differential_inverse_kinematics_test.cc#L166)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

this seems to go away by switching to osqp. 
</blockquote></details>

Interesting, is our snopt solver flawed? or does it have some parameter to control this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Comment by hongkai-dai** [comment]
:lgtm: except a few minor comments

---

Reviewed 1 of 5 files at r1, 2 of 4 files at r3, 1 of 1 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 23 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ufwvUNfKEEnXxevJn:-L5ufwvUNfKEEnXxevJo:bdphljn) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L23)):*
> ```cpp
> 
>   // Rotate the velocity into E frame.
>   MatrixX<double> J_WE_E = R_EW * J_WE;
> ```

`MatrixX<double>` -> `const MatrixX<double>`

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ug1GKaiLPtLYxjfdl:-L5ug1GKaiLPtLYxjfdm:b-1s3nl9) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L25)):*
> ```cpp
>   MatrixX<double> J_WE_E = R_EW * J_WE;
> 
>   Vector6<double> V_WE_E = R_EW * V_WE_desired;
> ```

`Vector6<double>` -> `const Vector6<double>`

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 39 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ugMn-uYdijSCzIG3f:-L5ugMn-uYdijSCzIG3g:b-7s4sqq) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L39)):*
> ```cpp
>   }
> 
>   MatrixX<double> J = J_WE_E_scaled.topRows(num_cart_constraints);
> ```

const

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ugOJCqYUWv1aj684e:-L5ugOJCqYUWv1aj684f:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L40)):*
> ```cpp
> 
>   MatrixX<double> J = J_WE_E_scaled.topRows(num_cart_constraints);
>   VectorX<double> V = V_WE_E_scaled.head(num_cart_constraints);
> ```

ditto

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 100 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ugTTedi8DVzATd5SQ:-L5ugTTedi8DVzATd5SR:bll73ro) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L100)):*
> ```cpp
>   solvers::VectorXDecisionVariable v_next =
>       prog.NewContinuousVariables(num_velocities, "v_next");
>   solvers::VectorXDecisionVariable alpha =
> ```

BTW, we have `solvers::VectorDecisionVariable alpha = prog.NewContinuousVariables<1>("alpha");` to use static size vector rather than dynamic sized one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5uiveXBe3u6VynoZ-A:b-z4nkaq)*

**Comment by siyuanfeng-tri** [comment]
+@soonho-tri for platform review. 

---

Reviewed 1 of 5 files at r1, 2 of 4 files at r3, 1 of 1 files at r4, 1 of 2 files at r5.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 23 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ufwvUNfKEEnXxevJn:-L5xwg8H9A2Q30XQzezf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L23)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`MatrixX<double>` -> `const MatrixX<double>`
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 25 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ug1GKaiLPtLYxjfdl:-L5xwgQtLeXSzQI7bvgG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`Vector6<double>` -> `const Vector6<double>`
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 39 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ugMn-uYdijSCzIG3f:-L5xzJPKJtLOJOI_n5r5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L39)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 40 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ugOJCqYUWv1aj684e:-L5xzJgs07cXlx63h6ib:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L40)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 100 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-L5ugTTedi8DVzATd5SQ:-L5xzTM9YN-E2oAOYQa0:b-s4s58z) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d9bc5c34c81987cc9f6fec71d54b6aa53c06d1/manipulation/planner/differential_inverse_kinematics.cc#L100)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, we have `solvers::VectorDecisionVariable alpha = prog.NewContinuousVariables<1>("alpha");` to use static size vector rather than dynamic sized one.
</blockquote></details>

cool! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5y0Odtspc0_v7_MDN8:b-ephv9i)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Comment by soonho-tri** [comment]
FYI, `bazel test //manipulation/planner:differential_inverse_kinematics_test --config=everything` timed out (300 sec) on my mac.

---

Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5yUxLQGOQyECMK1b1z:b-irmuyl)*

**Comment by siyuanfeng-tri** [comment]
hmm, i suspect one of the test got stuck in a infinite loop. changed the termination condition. @soonho-tri can you try it locally on your mac? thanks much

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5yXBUPMjGjTSh2uRg1:b-3ceu4o)*

**Comment by soonho-tri** [comment]
`0.766` sec!

:lgtm: 

---

Reviewed 1 of 5 files at r1, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122#-:-L5yYm6xqkWdjPo55sOQ:bkrn9qe)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8122)*

**Pull request merged**
