### PR TITLE
Port SimpleCar's config to use Parameters

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5007)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.

The idea is to make SimpleCar more like other systems.  I don't necessarily expect us to use these Parameters for control design (though maybe we will), but rather just want this System to look more like our other Systems and to be a better example for others to cite.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-:-KbrKFmAkVDWBSqle6H1:bkkkxzb)*

**Comment by jadecastro** [comment]
Sounds good. Do we also want to add a .named_vector file and include these parameters in simple_car_gen.sh?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-:-Kbrv16-RWsgwdc7GXO-:b7w78q1)*

**Comment by jwnimmer-tri** [comment]
The Config is already code-gen'd (see https://github.com/RobotLocomotion/drake/blob/788acfa32b40a0a41b52531f997240596af4b9a5/drake/automotive/simple_car_gen.sh#L18), but without using a proto file.  In #5005, I've changed it to a proto file.

**Comment by jadecastro** [comment]
Ok I see now, thanks.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-:-KbtapLxmAyhSfMgbfWd:bu67yzi)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-:-KbtavCSGIiJOEz6JNFG:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-:-KbtbhKWlwglRx0xxN8-:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car.h, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-KbuB665-K7QDvzk_s4h:-KbuB666vDueB9vRKyd9:bbddexm) ([raw file](https://github.com/robotlocomotion/drake/blob/191195e5ea709df5f88c7c7aa64cc49968a2b5c3/drake/automotive/simple_car.h#L66)):*
> ```objc
> 
>   /// Sets `config` to contain the default parameters for SimpleCar.
>   static void SetDefaultParameters(SimpleCarConfig<T>* config);
> ```

BTW I worry that creating an overload which is a static function having the same name as an inherited/overriden member function could become confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5007#-:-KbuC-IN6c4hqmcMIUGv:bnfp4nl)*

**Pull request merged**
