### PR TITLE
Adding a sine wave primitive system.

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7538)

### CODE REVIEW

**Comment by rcory** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-9hKTcYwNZ-WxiZhLy:b-a98c4g)*

**Comment by edrumwri** [comment]
Looks really good. Main concern is about derivatives.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/primitives/sine-inl.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-AKqAzN2JbLsPU-Uhv:-L-AKqB-lSnhHb-Ul_d3:b6w7ckc) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine-inl.h#L29)):*
> ```objc
>               bool is_time_based)
>     : VectorSystem<T>(SystemTypeTag<systems::Sine>{},
>                       amplitudes.size() * !is_time_based,
> ```

This little statement packs a lot of heat- want to explain it with a comment?

---

*[drake/systems/primitives/sine-inl.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-AL6mW5xH85Pewrhd4:-L-AL6mW5xH85Pewrhd5:b-ao189l) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine-inl.h#L52)):*
> ```objc
> }
> 
> template <typename T>
> ```

This group of three functions is strange- why is it useful to have them? Why not just always return a vector?

---

*[drake/systems/primitives/sine.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-ALfUiZbmxP-PZX0PV:-L-ALfUiZbmxP-PZX0PW:b-gpl9ub) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine.h#L14)):*
> ```objc
> /// `p` the phase (radians), all of which are constant vectors provided at
> /// construction time. This system has one or zero input ports and a single
> /// vector valued output port. The user can specify whether to use simulation
> ```

It's common to up to two derivatives of Sine too- what do you think of including those as outputs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-DLKcitsnoheArNQLT:b-73tyh)*

**Comment by rcory** [comment]
Check point. Added derivatives. PTAL.

I still need to add corresponding unit tests for derivatives.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/primitives/sine-inl.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-AKqAzN2JbLsPU-Uhv:-L-JDW8kUhX8pb90gTlr:bepx1eg) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine-inl.h#L29)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This little statement packs a lot of heat- want to explain it with a comment?
</blockquote></details>

The heat has been unpacked and now appears as an if statement. Comments provided as well.

---

*[drake/systems/primitives/sine-inl.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-AL6mW5xH85Pewrhd4:-L-JE5lpC46UKWhPV9rl:b-adc1d6) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine-inl.h#L52)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This group of three functions is strange- why is it useful to have them? Why not just always return a vector?
</blockquote></details>

This is really just for convenience (and consistency). Instead of returning a vector of size `n` with the exact same value for every element, we just return the element itself. This is consistent with the way the first constructor creates a Sine system (where a set of scalars, not a a set of vectors, are provided).

It's easy enough to always return a vector, and let the user pull out the first element when a Sine system is created via the first constructor...just doesn't feel as clean. But I could go either way...

---

*[drake/systems/primitives/sine.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-ALfUiZbmxP-PZX0PV:-L-JGG_MkMOY_JQLGEy8:b7g3tnl) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine.h#L14)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It's common to up to two derivatives of Sine too- what do you think of including those as outputs?
</blockquote></details>

Yup! They've been added. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-JGRtOqJ4UvfPX6ziJ:b-151r7s)*

**Comment by rcory** [comment]
Also, in order to provide derivatives, I had to inherit directly from `LeafSystem` instead of `VectorSystem` (the latter only allows a single output port).

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-JH82rDtidarFeax-2:b-fmf7nc)*

**Comment by edrumwri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/sine-inl.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-AL6mW5xH85Pewrhd4:-L-JRUVEew4BBtWjC7qx:b2nhll9) ([raw file](https://github.com/robotlocomotion/drake/blob/4320a423381985db0466a392c1c91df7099230b4/drake/systems/primitives/sine-inl.h#L52)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

This is really just for convenience (and consistency). Instead of returning a vector of size `n` with the exact same value for every element, we just return the element itself. This is consistent with the way the first constructor creates a Sine system (where a set of scalars, not a a set of vectors, are provided).

It's easy enough to always return a vector, and let the user pull out the first element when a Sine system is created via the first constructor...just doesn't feel as clean. But I could go either way...
</blockquote></details>

Ok.

---

*[drake/systems/primitives/sine-inl.h, line 116 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-JSKgrVVwUM3bZux7r:-L-JSKgrVVwUM3bZux7s:baj1k0f) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd83401e7fbc6b2069a3ea7a0da946afa2c5db4/drake/systems/primitives/sine-inl.h#L116)):*
> ```objc
> void Sine<T>::CalcValueOutput(const Context<T>& context,
>                               BasicVector<T>* output) const {
>   VectorX<T> sine_arg;
> ```

It appears that you can pull a bunch of this code out and avoid the repetition (and rule of three).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538)*

**Comment by rcory** [comment]
PTAL. Added derivatives to unit tests, and cleaned up output port calc functions.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/sine-inl.h, line 116 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-JSKgrVVwUM3bZux7r:-L-sDLRt3y-AViDx3luw:b-jvpgmc) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd83401e7fbc6b2069a3ea7a0da946afa2c5db4/systems/primitives/sine-inl.h#L116)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It appears that you can pull a bunch of this code out and avoid the repetition (and rule of three).
</blockquote></details>

Yup, good call. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-sDToBaowTcrGeUtvV:bexhqji)*

**Comment by edrumwri** [comment]
:lgtm: but for one thing.

---

Reviewed 8 of 10 files at r4.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/primitives/test/sine_test.cc, line 65 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sKFDRQsOAURnHsfWb:-L-sKFDRQsOAURnHsfWc:bfeq0ej) ([raw file](https://github.com/robotlocomotion/drake/blob/7340abea20153ac72a4db216f9d080b0996b39d3/systems/primitives/test/sine_test.cc#L65)):*
> ```cpp
>       Eigen::VectorXd expected_first_deriv = expected_first_derivs.col(i);
>       Eigen::VectorXd expected_second_deriv = expected_second_derivs.col(i);
>       EXPECT_TRUE(expected_vector.isApprox(output_vector->get_value(), 1e-3));
> ```

BTW Please replace the 1e-3's here and below with a named tolerance value. Also, please explain why the tolerance is so loose (you're providing answers with four digits of precision).

---

*[systems/primitives/test/sine_test.cc, line 111 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sKQogJdWeZpW_yyim:-L-sKQogJdWeZpW_yyin:b-llxrx2) ([raw file](https://github.com/robotlocomotion/drake/blob/7340abea20153ac72a4db216f9d080b0996b39d3/systems/primitives/test/sine_test.cc#L111)):*
> ```cpp
>       Eigen::VectorXd expected_first_deriv = expected_first_derivs.col(i);
>       Eigen::VectorXd expected_second_deriv = expected_second_derivs.col(i);
>       EXPECT_TRUE(expected_output.isApprox(output_vector->get_value(), 1e-3));
> ```

BTW More magic 1e-3's.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-sKqWNdf2-WEpkOXnr:b-yfg1lt)*

**Comment by rcory** [comment]
+@sherm1 for platform review please.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/primitives/test/sine_test.cc, line 65 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sKFDRQsOAURnHsfWb:-L-simISMaXqOrEOC3cz:bg3ksrj) ([raw file](https://github.com/robotlocomotion/drake/blob/7340abea20153ac72a4db216f9d080b0996b39d3/systems/primitives/test/sine_test.cc#L65)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Please replace the 1e-3's here and below with a named tolerance value. Also, please explain why the tolerance is so loose (you're providing answers with four digits of precision).
</blockquote></details>

Glad you pointed this out. I'll update these to be more clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-sj2xyQQbOdwAAy553:b6vi582)*

**Comment by rcory** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/primitives/test/sine_test.cc, line 111 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sKQogJdWeZpW_yyim:-L-spYkVSeFnDi182kKD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7340abea20153ac72a4db216f9d080b0996b39d3/systems/primitives/test/sine_test.cc#L111)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW More magic 1e-3's.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538)*

**Comment by sherm1** [comment]
Platform pass done -- a few comments, ptal.

---

Reviewed 7 of 10 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[systems/primitives/sine-inl.h, line 29 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sv5nkXgg2qpkeObYE:-L-sv5nkXgg2qpkeObYF:b-83is8v) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L29)):*
> ```objc
>       : LeafSystem<T>(SystemTypeTag<systems::Sine>{}),
>       amplitude_(amplitudes), frequency_(frequencies), phase_(phases),
>       is_time_based_(is_time_based) {
> ```

BTW should DRAKE_DEMAND that the three VectorX's are the same size.

---

*[systems/primitives/sine-inl.h, line 59 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-svP7lleIYLSwwGfqV:-L-svP7lleIYLSwwGfqW:b-jiomzn) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L59)):*
> ```objc
> template <typename T>
> double Sine<T>::get_amplitude() const {
>   if (!amplitude_.isConstant(amplitude_[0])) {
> ```

This is an expensive check (because Eigen has to search the whole vector). If you want to do it even in Release builds, then this method is too expensive to use the lower-case name which is only for very cheap methods. It should be called `GetAmplitude()` in that case.

I suggest instead that you take one of these approaches:
- Precalculate at construction whether the given values are all the same (for all three Vectors) and save the result in a bool member. Then you can check it on the cheap here instead of calculating it. (Nicest since always checked and gives a nice error message even in Release builds) Or,
- Wrap this test and the error message in a private method, say `ThrowIfNonConstant()`, and invoke that as `DRAKE_ASSERT_VOID(ThrowIfNonConstant()`. That way it is only invoked in Debug builds and the method is very fast in Release. It would give a nice message in Debug but nothing in Release.
- Just use `DRAKE_ASSERT(amplitude_.isConstant(amplitude[0]));` here. Validates in Debug but never gives a pretty message.

Any of these would be acceptable.

---

*[systems/primitives/sine-inl.h, line 64 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sxU1ctoYzzB1M7yfr:-L-sxU1dsD7KC5PMdAWd:bo84r2i) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L64)):*
> ```objc
>       << "as a scalar value. Please use "
>       << "drake::systems::Sine::get_amplitude_vector() instead.";
>     throw std::runtime_error(s.str().c_str());
> ```

BTW we aren't too strict about this but technically this should be `std::logic_error`. That is for programming mistakes (like calling a method you shouldn't have called). `std::runtime_error` is for things you can't fix by better programming, like you read in a file and the format was bad.

---

*[systems/primitives/sine-inl.h, line 128 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-syEWEDlgeyLTMZ9Mi:-L-syEWEDlgeyLTMZ9Mj:bnhe37y) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L128)):*
> ```objc
> 
>   VectorX<T> cos_arg;
>   Sine::CalcSineArg(context, &cos_arg);
> ```

BTW this confused me. I suggest that you call this method `CalcArg()` rather than `CalcSineArg()` since it is agnostic about which function gets called.

---

*[systems/primitives/sine-inl.h, line 149 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-symqibjJqnxNMuoFQ:-L-symqibjJqnxNMuoFR:b-lue8cp) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L149)):*
> ```objc
> template <typename T>
> void Sine<T>::CalcSineArg(
>     const Context<T>& context, VectorX<T>* sine_arg) const {
> ```

BTW rename to `CalcArg()` and output to just `arg`? (See comment above)

---

*[systems/primitives/sine.h, line 87 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-stMHTAj7Qv5_I3yk2:-L-stMHTAj7Qv5_I3yk3:bnkjzkf) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine.h#L87)):*
> ```objc
>   /// vector is the same. It will abort if the phase cannot be represented as a
>   /// single scalar value.
>   double get_phase() const;
> ```

BTW (optional) -- consider dropping the `get_` in these names. The styleguide permits that for very simple accessors, and lately that style has been popular with Drake programmers. The methods then read `amplitude()`, `frequency()` etc.

Normally methods should begin with a verb -- this is just a special exemption for very-dumb const accessors.

---

*[systems/primitives/sine.h, line 101 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-suTBknq8xp6Tj57RU:-L-suTBknq8xp6Tj57RV:bohk1xv) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine.h#L101)):*
> ```objc
> 
>   /// Returns the phase vector constant.
>   const Eigen::VectorXd& get_phase_vector() const;
> ```

BTW (optional) would be OK to drop `get_` on these three also.

---

*[systems/primitives/test/sine_test.cc, line 287 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-szZrwqke9FJxvndEH:-L-szZrwqke9FJxvndEI:btkiica) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/test/sine_test.cc#L287)):*
> ```cpp
>   EXPECT_THROW(sine_system->get_frequency(), std::runtime_error);
>   EXPECT_THROW(sine_system->get_phase(), std::runtime_error);
> }
> ```

BTW please add a test that an error is thrown if the three arrays are not all the same size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L-sziOuALoRgpYvs7B3:b77u9c7)*

**Comment by rcory** [comment]
Review status: 2 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[systems/primitives/sine-inl.h, line 29 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sv5nkXgg2qpkeObYE:-L06aT-Ibmn3oDnvS69u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should DRAKE_DEMAND that the three VectorX's are the same size.
</blockquote></details>

Done.

---

*[systems/primitives/sine-inl.h, line 59 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-svP7lleIYLSwwGfqV:-L06kPAFPShhw5ruM-B4:bxvdzd3) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is an expensive check (because Eigen has to search the whole vector). If you want to do it even in Release builds, then this method is too expensive to use the lower-case name which is only for very cheap methods. It should be called `GetAmplitude()` in that case.

I suggest instead that you take one of these approaches:
- Precalculate at construction whether the given values are all the same (for all three Vectors) and save the result in a bool member. Then you can check it on the cheap here instead of calculating it. (Nicest since always checked and gives a nice error message even in Release builds) Or,
- Wrap this test and the error message in a private method, say `ThrowIfNonConstant()`, and invoke that as `DRAKE_ASSERT_VOID(ThrowIfNonConstant()`. That way it is only invoked in Debug builds and the method is very fast in Release. It would give a nice message in Debug but nothing in Release.
- Just use `DRAKE_ASSERT(amplitude_.isConstant(amplitude[0]));` here. Validates in Debug but never gives a pretty message.

Any of these would be acceptable.
</blockquote></details>

Great feedback! I implemented your first suggestion (pre-calculate at construction).

---

*[systems/primitives/sine-inl.h, line 64 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-sxU1ctoYzzB1M7yfr:-L06lGOvsc-QvcRsv-wS:bctpdcc) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW we aren't too strict about this but technically this should be `std::logic_error`. That is for programming mistakes (like calling a method you shouldn't have called). `std::runtime_error` is for things you can't fix by better programming, like you read in a file and the format was bad.
</blockquote></details>

Makes sense. Done.

---

*[systems/primitives/sine-inl.h, line 128 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-syEWEDlgeyLTMZ9Mi:-L06lZi31bXLD1ge-7xt:bpneuwk) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L128)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this confused me. I suggest that you call this method `CalcArg()` rather than `CalcSineArg()` since it is agnostic about which function gets called.
</blockquote></details>

Meant to fix that earlier, but missed it. Good catch. Done.

---

*[systems/primitives/sine-inl.h, line 149 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-symqibjJqnxNMuoFQ:-L06lxNvAsewE3hrkfDI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L149)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW rename to `CalcArg()` and output to just `arg`? (See comment above)
</blockquote></details>

Done.

---

*[systems/primitives/sine.h, line 87 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-stMHTAj7Qv5_I3yk2:-L06n54dJGQ00qpbUiKs:bctpdcc) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine.h#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW (optional) -- consider dropping the `get_` in these names. The styleguide permits that for very simple accessors, and lately that style has been popular with Drake programmers. The methods then read `amplitude()`, `frequency()` etc.

Normally methods should begin with a verb -- this is just a special exemption for very-dumb const accessors.
</blockquote></details>

Makes sense. Done.

---

*[systems/primitives/sine.h, line 101 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-suTBknq8xp6Tj57RU:-L06n40ERGrjUzHwM5jy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine.h#L101)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW (optional) would be OK to drop `get_` on these three also.
</blockquote></details>

Done.

---

*[systems/primitives/test/sine_test.cc, line 287 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-szZrwqke9FJxvndEH:-L06zmsnK6u54EYl984x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/test/sine_test.cc#L287)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please add a test that an error is thrown if the three arrays are not all the same size.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538)*

**Comment by sherm1** [comment]
Nice, thanks for the updates -- platform :lgtm: with a few minor BTWs.

---

Reviewed 3 of 10 files at r4, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[systems/primitives/sine-inl.h, line 59 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L-svP7lleIYLSwwGfqV:-L07R0n0bpGpVZWr67f7:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/70b4cfb29297f240357214520a9830dd3b5015d7/systems/primitives/sine-inl.h#L59)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Great feedback! I implemented your first suggestion (pre-calculate at construction).
</blockquote></details>

Nice!

---

*[systems/primitives/sine-inl.h, line 74 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L07RNeU_g89t-VPECmq:-L07RNeU_g89t-VPECmr:bgf6g6u) ([raw file](https://github.com/robotlocomotion/drake/blob/7b09e4a091a7eb95b2906b77e2c11343deb18bd5/systems/primitives/sine-inl.h#L74)):*
> ```objc
>       << "as a scalar value. Please use "
>       << "drake::systems::Sine::amplitude_vector() instead.";
>     throw std::logic_error(s.str().c_str());
> ```

BTW this constructor takes an std::string -- you don't need to convert to a c_str() when you call it. `std::logic_error(s.str())` will work. (Below also)

---

*[systems/primitives/sine.h, line 120 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-L07RsueWuwItn1eED9d:-L07RsueWuwItn1eED9e:botwmfm) ([raw file](https://github.com/robotlocomotion/drake/blob/7b09e4a091a7eb95b2906b77e2c11343deb18bd5/systems/primitives/sine.h#L120)):*
> ```objc
>   bool is_const_amplitude_;
>   bool is_const_frequency_;
>   bool is_const_phase_;
> ```

BTW [our styleguide](http://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization) requires initialization here for non-const built in types. You could write either `bool is_const_phase_{false}` or just `bool is_const_phase_{}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L07TB2c64EgKK2lMNG7:b-wrcw76)*

**Comment by sherm1** [comment]
(Also some build failures to resolve)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L07TN_RGeav4TEjQ6QR:b6s0k1f)*

**Comment by rcory** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538#-:-L0AenWNCKBJvPkmjpDW:b4pymce)*

**Comment by edrumwri** [comment]
Reviewed 2 of 10 files at r4, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7538)*

**Pull request merged**
