### PR TITLE
Add doxygen for DRAKE_ABORT_MSG

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3091)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Two-line doc change, so @david-german-tri for all reviews, please.

**Comment by jwnimmer-tri** [comment]
For the record, we (including me) missed this #3040's original implementation.

**Comment by david-german-tri** [comment]
I'm not sure I agree this qualifies as "missed", but anyway :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3091#-:-KOjrToFKgYJ6vfsNa9l:b-9gisrd)*

**Comment by jwnimmer-tri** [comment]
Windows builders are fragged.  I'm using override-merge because linux builds should be enough to prove out a doxygen-only change.

**Pull request merged**
