### PR TITLE
Re-introduce "Initial proposal for hybrid system API"

### PR DESCRIPTION
**Pull request by jadecastro**
Re-Introduce the PR [RobotLocomotion/drake#3552](https://github.com/RobotLocomotion/drake/pull/3552), which passed Experimental CI, but failed post-merge CI.

It was reverted here: [RobotLocomotion/drake#3595](https://github.com/RobotLocomotion/drake/pull/3595), due to compile time errors detected in the debug-mode builders. This PR resolves those issues.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3601)

### CODE REVIEW

**Comment by jadecastro** [comment]
+ @jwnimmer-tri for feature review please
+ @sammy-tri for platform review please

**Comment by jadecastro** [comment]
Note the most-recent commit (520ed76) contains the changes since the failed (reverted) PR.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-:-KSllJb9jUv7-FhyS4K-:b2gotxd)*

**Comment by sammy-tri** [comment]
Reviewed 26 of 27 files at r1.
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/bouncing_ball/bouncing_ball.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-KSltS0Aoz5be3sudqjv:-KSltS0BWvIuy60pqvvx:b-5886mb) ([raw file](https://github.com/robotlocomotion/drake/blob/520ed764d397ab2fb3c162c2310e5a6657a03d46/drake/examples/bouncing_ball/bouncing_ball.h#L48)):*
> ```objc
>   /// the system API, pending further discussions.
>   ///
>   /// Performs a reset mapping that occurs once a discrete mode if and only if a
> ```

Not clear on the meaning of "mapping that occurs once a discrete mode"

---

*[drake/examples/bouncing_ball/bouncing_ball.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-KSltd8kA6cJ28RiIxmh:-KSltd8lVUccV7PKguyB:b60kcg7) ([raw file](https://github.com/robotlocomotion/drake/blob/520ed764d397ab2fb3c162c2310e5a6657a03d46/drake/examples/bouncing_ball/bouncing_ball.h#L53)):*
> ```objc
>   void PerformReset(systems::Context<T>* context) const;
> 
>   /// Getter for the model coefficient.
> ```

Should what the "model coefficient" does be more clearly documented?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3601)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 27 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3601)*

**Comment by jadecastro** [comment]
Review status: 18 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/bouncing_ball/bouncing_ball.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-KSltS0Aoz5be3sudqjv:-KSm0UpVZ2mOu-_kZiyu:bxx4sdm) ([raw file](https://github.com/robotlocomotion/drake/blob/d799708bbc0d7cff5350ecdc9841c80174734a54/drake/examples/bouncing_ball/bouncing_ball.h#L48)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Not clear on the meaning of "mapping that occurs once a discrete mode"
</details>
Typo. Thanks for catching that - fixed now.

---

*[drake/examples/bouncing_ball/bouncing_ball.h, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-KSltd8kA6cJ28RiIxmh:-KSm0_UsKIY76rNk1QEN:b-7jkpug) ([raw file](https://github.com/robotlocomotion/drake/blob/d799708bbc0d7cff5350ecdc9841c80174734a54/drake/examples/bouncing_ball/bouncing_ball.h#L53)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Should what the "model coefficient" does be more clearly documented?
</details>
Agree. I've updated to be more specific.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3601)*

**Comment by sammy-tri** [comment]
:lgtm: pending @jwnimmer-tri feature review

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-:-KSmCHN9r3eIpOxVBtbb:b-6ordg9)*

**Comment by sammy-tri** [comment]
I don't think this actually got feature reviewed?  You may want to circle back with @jwnimmer-tri to see if he has any comments...

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3601#-:-KSm_nVKwVouRe_vlROU:b6ckvqm)*

**Pull request merged**
