### PR TITLE
Bind PoseBundle, FrameVelocity, PoseAggregator, SpatialVector, SpatialVelocity

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8282)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@ericcousineau-tri for feature review, please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L6yKJLUPFSQTWorWeqG:b-di4bjk)*

**Comment by EricCousineau-TRI** [comment]
First pass done, PTAL.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/rendering_py.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6ySCIsi8e_UpTOsgNQ:-L6ySCItGAT34AgloA0S:b-fky0bz) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/rendering_py.cc#L62)):*
> ```cpp
>   // N.B. We simplify the get/set signatures below to temporarily sidestep
>   // dependence on multibody.
>   // TODO(jadecastro) Revert this once the bindings for SpatialVelocity exist.
> ```

I'd prefer that we add `FrameVelocity` before this merges; a simple binding in `pydrake.multibody.multibody_tree.math` (jeepers that's a long path!) would suffice, along the lines of what is present for `Isometry3`.

Would it be possible to add that in this PR?

---

*[bindings/pydrake/systems/test/rendering_test.py, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6ySuEikWO9LtkDi_KL:-L6ySuEikWO9LtkDi_KM:bd7c79z) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/test/rendering_test.py#L29)):*
> ```Python
> 
> class TestRendering(unittest.TestCase):
>     def test_pose_bundle(self):
> ```

BTW Can you put this test underneath `test_pose_vector`?

---

*[bindings/pydrake/systems/test/rendering_test.py, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6yRs0Z9fw_6gm8tKcb:-L6yRs0_rLyEwvcerxDh:bq9i94k) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/test/rendering_test.py#L37)):*
> ```Python
>         self.assertTrue(isinstance(bundle.get_velocity(0), FrameVelocity))
>         # - - Value.
>         self.assertTrue(np.allclose(bundle.get_pose(0).translation(), 3 * [0]))
> ```

BTW I wouldn't say value tests are needed here if you're just testing API -- that being said, if you want a full check on values, you should probably check the full pose, `self.assertTrue((bundle.get_pose(0).matrix() == np.eye(4, 4)).all())`.

---

*[bindings/pydrake/systems/test/rendering_test.py, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6yTGSOdKTrkkqkWq9-:-L6yTGSOdKTrkkqkWq90:b1r5fpv) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/test/rendering_test.py#L125)):*
> ```Python
>         aggregator = PoseAggregator()
>         # - Set-up.
>         id1 = 5
> ```

Can you expand this to `instance_id1`?

Also, can I ask where these numbers come from? Can you add a comment if they're made-up?

---

*[bindings/pydrake/systems/test/rendering_test.py, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6yTaRBU314fX8_Gscv:-L6yTaRBU314fX8_Gscw:b-x9o0e4) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/test/rendering_test.py#L135)):*
> ```Python
>         num_poses = 1
>         port3 = aggregator.AddBundleInput("pose_bundle", num_poses)
>         self.assertEqual(port3.size(), 0)  # it's an abstract input.
> ```

Can you bind `InputPortDescriptor::get_data_type` and use that here, since we already have `PortDataType`?

---

*[bindings/pydrake/systems/test/rendering_test.py, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6yU84Y0t_Kg4gmhZ5T:-L6yU84Y0t_Kg4gmhZ5U:bww87d8) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/test/rendering_test.py#L141)):*
> ```Python
>         output = aggregator.AllocateOutput(context)
> 
>         p1 = [0, 1, 2]
> ```

BTW Would it make sense to make a constructor, `PoseVector(translation, quaternion)`?
It looks like this is possible in the C++ code, without any conflicts with symbolics.

---

*[bindings/pydrake/systems/test/rendering_test.py, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L6yTqyL4oUe5w4zAtCO:-L6yTqyMAzIEE_lMyzTc:bs6qs7s) ([raw file](https://github.com/robotlocomotion/drake/blob/25c0b72c23affed967bb48aba0634f9eb31d7185/bindings/pydrake/systems/test/rendering_test.py#L166)):*
> ```Python
>         value = output.get_data(0).get_value()
>         self.assertEqual(value.get_num_poses(), 3)
>         self.assertTrue(np.allclose(value.get_pose(0).translation(), p1))
> ```

BTW Rather than compare individual portions, why not something like this?
```
p1 = PoseVector()
...
self.assertTrue((value.get_pose(0).matrix() == p1.matrix()).all())
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L6yV1V67Qcjwv2VLWKv:b-v6sck1)*

**Comment by jadecastro** [comment]
Thanks! 
+@soonho-tri for platform review, please.

---

Review status: 11 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/multibody/multibody_tree/test/math_test.py, line 23 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-L730WnE-o427VbjWqYZ:-L74AU5mA9urmSLgx8Pe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/057b61a217c056f335e1e179762768015970fdd5/bindings/pydrake/multibody/multibody_tree/test/math_test.py#L23)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW When testing, can you also use the named parameters?
`SpatialVelocity(w=w, v=v)`?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/rendering_test.py, line 62 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-L730zBx4oG3EY0Z2vJO:-L74AS4B5QirC5eSk3mm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/057b61a217c056f335e1e179762768015970fdd5/bindings/pydrake/systems/test/rendering_test.py#L62)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Same thing here - can you use the named parameters?
</blockquote></details>

Done.

---

*[systems/rendering/pose_vector.cc, line 21 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-L731kCZ2LnvH8GqdajR:-L74AHQo5UDg0XB_mq2g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/057b61a217c056f335e1e179762768015970fdd5/systems/rendering/pose_vector.cc#L21)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Could you make this order `rotation, translation`, for congruence with `Isometry3`, `Transform`, `SpatialVelocity(w, v)`, etc.?

\cc @sherm1 Do you have any preferences aside from this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-:-L74ABS-A_JIn3pOe9TB:bl9r08g)*

**Comment by EricCousineau-TRI** [comment]
Looking at CI errors:
```
Multiple installation rules found for math.so.
```

It looks like `install` does not seem robust against having multiple shared libs that share the same name, i.e. `pydrake.math` and `pydrake.multibody.multibody_tree.math`?
(I'd think it wouldn't matter, since these are standalones...)

@jwnimmer-tri @fbudin69500 Can I ask if there's a way to instruct `install` to relax for pybind sharedlibs?

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-:-L751re33yT1qM0oCGq9:b8si7ri)*

**Comment by jwnimmer-tri** [comment]
Do you happen to know which `{src, dst}` this is for (maybe amend the error message to add more detail)?  Given the purpose of that stanza (fixing out how to repair paths, with the basename uniqueness coming from macOS ) it might not be possible to disambiguate that late in the process.  Maybe we could blacklist certain libraries?  Never fixup pybind so's, for example?

Aside -- in general, I'm sad that we have `*.so` files with the same name.  Even if we get the install working, it seems like asking for trouble.

**Comment by jadecastro** [comment]
Another option might be, for this one case, to flatten out the path so that `pydrake.multibody.multibody_tree.math` -> `pydrake.multibody.multibody_tree`?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-:-L75GGhZCdrlX4Mbyy-V:b-ic3dbg)*

**Comment by EricCousineau-TRI** [comment]
> Another option might be, for this one case, to flatten out the path [...]

True. Another option too is that we incorporate this submodule into a file called `multibody_tree_py.cc` for the time being:
http://pybind11.readthedocs.io/en/stable/reference.html#_CPPv2N6module13def_submoduleEPKcPKc

However, given the size of the codebase for `multibody_tree`, I'm not sure if this is entirely practical for long-term development; but then again, maybe it could be the means by which we separate out object code, but consolidate the number of shared libraries.
Main thing is, I'd like to not have to pay for the build time for components that I'm not testing, as I'm already paying a hefty cost for `libdrake.so` (which is felt more significantly on my laptop, less so on my workstation, of course).

> Aside -- in general, I'm sad that we have *.so files with the same name. Even if we get the install working, it seems like asking for trouble.

This shouldn't be an issue for Python libraries, in that each file's symbols are loaded separately, even if they share the same basename:
https://github.com/EricCousineau-TRI/repro/blob/master/python/pybind11/dup_check/test/testDup.py
(That being said, if/when we move to Python3, these extensions should get changed to reflect that they're Python-specific.)

Can I ask if there are other situations where this would become a problem?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-:-L75Wj6nD8sBdfVkYTDW:bjsoywu)*

**Comment by jadecastro** [comment]
Sounds like there's some plausible near/longer term solutions, but nothing dominating. @EricCousineau-TRI, let me know if perhaps you'd like the `multibody_tree_py.cc` stop-gap or see a way forward with blacklisting our pybind sharedlibs like Jeremy mentions.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8282#-:-L75tow70S73Ohrvs6Ov:bpajrmc)*

**Comment by soonho-tri** [comment]
-@soonho-tri. Please add an on-call reviewer when the CI issue is resolved.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L76r52OdmIH6Rgxf238:b2t4qsr)*

**Comment by EricCousineau-TRI** [comment]
Sorry for the delay! Let's do the stopgap, then I can figure out what to do about modularity later on.

I just tested this out on your branch, and `multibody_tree_test` works using the internal submodule:
https://github.com/EricCousineau-TRI/drake/commit/954c6af9ba26102900d7dd51edbc634ce90c7180
(I believe this would pass CI)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L77ZL6qMtVo28dgkLSY:b-qub7nd)*

**Comment by jadecastro** [comment]
Thanks! I've folded the `def-submodule` solution in and it looks like it works for me.
+@sherm1 for platform review, please. 

---

Review status: 11 of 15 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L79JJ9ukfo5qvi-60_D:b4xtun9)*

**Comment by sherm1** [comment]
BTW PR title mentions PoseBundle, FrameVelocity, PoseAggregator but not SpatialVector & SpatialVelocity -- update?
:lgtm:, pending a few minor BTWs.

---

Reviewed 5 of 19 files at r2, 6 of 11 files at r3, 6 of 9 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/multibody/multibody_tree_py.cc, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7Aipq93GMqTjK9Qxmg:-L7Aipq93GMqTjK9Qxmh:bbksn9n) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/multibody/multibody_tree_py.cc#L52)):*
> ```cpp
> 
> PYBIND11_MODULE(multibody_tree, m) {
>   m.doc() = "MultiBodyTree functionality.";
> ```

BTW "MultibodyTree" (no capital B)

---

*[bindings/pydrake/systems/rendering_py.cc, line 44 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AhcbZRWwlpGKdm84G:-L7AhcbZRWwlpGKdm84H:b-rd29a) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/systems/rendering_py.cc#L44)):*
> ```cpp
>   // N.B. We simplify the get/set signatures below to temporarily sidestep
>   // dependence on multibody.
>   // TODO(jadecastro) Revert this once the bindings for SpatialVelocity exist.
> ```

BTW I don't understand this TODO. This PR adds the bindings for SpatialVelocity. Should something be reverted here now?

---

*[bindings/pydrake/test/all_test.py, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AjR8wwUUuB-KMwkwP:-L7AjR8wwUUuB-KMwkwQ:b3g7cd1) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/test/all_test.py#L94)):*
> ```Python
>             "Isometry3",
>             "Quaternion",
>         )
> ```

BTW should the above list include PoseBundle, FrameVelocity, PoseAggregator ?

---

*[systems/rendering/frame_velocity.h, line 29 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7An_miJq3P7tHxzkSm:-L7An_miJq3P7tHxzkSn:b-96fmly) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/systems/rendering/frame_velocity.h#L29)):*
> ```objc
> 
>   /// Fully-parameterized constructor.
>   /// @param velocity the entire spatial velocity Xdot_WA.
> ```

BTW Xdot_WA -> V_WA.  Spatial velocity symbol is "V". It is not actually the time derivative of X_WA although Xdot and V are linearly related.

---

*[systems/rendering/pose_vector.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L731kCZ2LnvH8GqdajR:-L7AoF4jcamcalUXbFno:b9j9n43) ([raw file](https://github.com/robotlocomotion/drake/blob/057b61a217c056f335e1e179762768015970fdd5/systems/rendering/pose_vector.cc#L21)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good to me.

---

*[systems/rendering/pose_vector.h, line 27 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AoV0tVIxcK8E6GEgz:-L7AoV0tVIxcK8E6GEh-:bzfdlaf) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/systems/rendering/pose_vector.h#L27)):*
> ```objc
>   /// Fully-parameterized constructor.
>   /// @param rotation the rotation R_WA.
>   /// @param translation the translation p_WA.
> ```

BTW, to make this less tautological, consider something like
```
@param rotation the orientation R_WA of frame A in the world frame W.
@param translation the position vector p_WA giving A's origin measured from W's origin, expressed in W.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L7AixD-eQZVtugCK2-5:bq7mkv)*

**Comment by jadecastro** [comment]
Review status: 11 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[bindings/pydrake/multibody/multibody_tree_py.cc, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7Aipq93GMqTjK9Qxmg:-L7AqwnPXvVDsLyEDSW6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/multibody/multibody_tree_py.cc#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW "MultibodyTree" (no capital B)
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/rendering_py.cc, line 44 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AhcbZRWwlpGKdm84G:-L7AqyVMB8knH60Hu6YL:b-jd2tqe) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/systems/rendering_py.cc#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I don't understand this TODO. This PR adds the bindings for SpatialVelocity. Should something be reverted here now?
</blockquote></details>

Oops- forgot to zap that comment. Done.

---

*[bindings/pydrake/test/all_test.py, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AjR8wwUUuB-KMwkwP:-L7ArB66ICrGRPrS0FRZ:b-haciz6) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/test/all_test.py#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should the above list include PoseBundle, FrameVelocity, PoseAggregator ?
</blockquote></details>

As I understand, the test checks that a symbols can be accessed from every submodule promised by `pydrake.all`, which are referenced from `all.py` within each directory. So in our case, it's enough to check that one from the `rendering` can be accessed, in this case `PoseVector` does it. 

@EricCousineau-TRI, chime in if I'm off base here.

---

*[systems/rendering/frame_velocity.h, line 29 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7An_miJq3P7tHxzkSm:-L7AttyGJPUWmXDU09xE:btglzde) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/systems/rendering/frame_velocity.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Xdot_WA -> V_WA.  Spatial velocity symbol is "V". It is not actually the time derivative of X_WA although Xdot and V are linearly related.
</blockquote></details>

Thanks. I tried keeping notation consistent with the docstrings below, and it sounds like I should update those too, which I've done. PTAL. 

---

*[systems/rendering/pose_vector.h, line 27 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AoV0tVIxcK8E6GEgz:-L7Auagts0xobDJDe7vg:bqthia0) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/systems/rendering/pose_vector.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, to make this less tautological, consider something like
```
@param rotation the orientation R_WA of frame A in the world frame W.
@param translation the position vector p_WA giving A's origin measured from W's origin, expressed in W.
```
</blockquote></details>

SGTM. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by sherm1** [comment]
One "MultiBody" still there (-> Multibody).

---

Reviewed 1 of 9 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/multibody_tree_py.cc, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7Aipq93GMqTjK9Qxmg:-L7B3Drkg8yLmm7tqi2T:b9hyjvd) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/multibody/multibody_tree_py.cc#L52)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No change here?

---

*[systems/rendering/frame_velocity.h, line 29 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7An_miJq3P7tHxzkSm:-L7B3auHrcabyKBIAM2A:b-6mhyx0) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/systems/rendering/frame_velocity.h#L29)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Thanks. I tried keeping notation consistent with the docstrings below, and it sounds like I should update those too, which I've done. PTAL. 
</blockquote></details>

Great, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L7B3mjfXEjVoH_SbYfb:bq4ythr)*

**Comment by jadecastro** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/multibody/multibody_tree_py.cc, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7Aipq93GMqTjK9Qxmg:-L7B53qIOtuwrOLNlpfD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/multibody/multibody_tree_py.cc#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

No change here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by EricCousineau-TRI** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/test/all_test.py, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AjR8wwUUuB-KMwkwP:-L7B6GllDRvGAdaTggYk:b-5adps0) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/test/all_test.py#L94)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

As I understand, the test checks that a symbols can be accessed from every submodule promised by `pydrake.all`, which are referenced from `all.py` within each directory. So in our case, it's enough to check that one from the `rendering` can be accessed, in this case `PoseVector` does it. 

@EricCousineau-TRI, chime in if I'm off base here.
</blockquote></details>

Yup, it's just a subset of symbols for `test_symbols_subset`, just to ensure we touch one unique symbol per module (including submodules).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by sherm1** [comment]
Reviewed 1 of 9 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/test/all_test.py, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AjR8wwUUuB-KMwkwP:-L7B6jTiT0MFUkLbaWA2:b-puneei) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/test/all_test.py#L94)):*
From the test doc:
>        Tests a subset of symbols provided by `drake.all`. At least one
>        symbol per submodule should be included.

Should it be clarified?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 5 of 9 files at r4, 2 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/test/all_test.py, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-L7AjR8wwUUuB-KMwkwP:-L7BBoLxOaQlheFwIGia:bwr1v4w) ([raw file](https://github.com/robotlocomotion/drake/blob/62df224ab424d11aa0505c78cb75a3e049d9d31b/bindings/pydrake/test/all_test.py#L94)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

From the test doc:
>        Tests a subset of symbols provided by `drake.all`. At least one
>        symbol per submodule should be included.

Should it be clarified?
</blockquote></details>

Nope -- I just didn't see it because it wasn't in the green part!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282)*

**Comment by jadecastro** [comment]
Title updated; thanks!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8282#-:-L7BEcbf3Pegc2vUnIsm:b-m9fwd7)*

**Pull request merged**
