### PR TITLE
Simple Tree visualizer

### PR DESCRIPTION
**Pull request by naveenoid**
A tool for quickly visualizing a tree in a given configuration using drake-visualizer.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5854)

### CODE REVIEW

**Comment by naveenoid** [comment]
@hongkai-dai for feature review
Also tagging @liangfok since it is inspired by DrakeVisualizer

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-:-KhsDk1gTZPYQo6FuFbg:b-fcupkv)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhsH1_coFvoIQZi-c9A:-KhsH1_dOWyP7MznjfuS:b77tiql) ([raw file](https://github.com/robotlocomotion/drake/blob/f7b01b4858f51396a46cd412cc7e7a83c0b3f493/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc#L37)):*
> ```cpp
> void SimpleTreeVisualizer::visualize(const VectorX<double>& position_vector) {
>   DRAKE_DEMAND(position_vector.size() == tree_.get_num_positions());
>   Eigen::VectorXd q_qDot = Eigen::VectorXd::Zero(14);
> ```

The magic number 14 is specific to iiwa arm, consider to use `tree_.get_num_positions() + tree_.get_num_velocities()`? Also, consider to call it `state` instead of `q_qDot`. The state is not necessarilly `q + qdot`.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhsFvx8fOalav0w4jM5:-KhsFvx8fOalav0w4jM6:b3dlfsu) ([raw file](https://github.com/robotlocomotion/drake/blob/f7b01b4858f51396a46cd412cc7e7a83c0b3f493/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h#L28)):*
> ```objc
> 
>   /**
>    * Visualizes a gives state position configuration.
> ```

`given`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by naveenoid** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhsH1_coFvoIQZi-c9A:-Khux_f6RaSaC5o68fVC:b-t8w9s) ([raw file](https://github.com/robotlocomotion/drake/blob/f7b01b4858f51396a46cd412cc7e7a83c0b3f493/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc#L37)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The magic number 14 is specific to iiwa arm, consider to use `tree_.get_num_positions() + tree_.get_num_velocities()`? Also, consider to call it `state` instead of `q_qDot`. The state is not necessarilly `q + qdot`.
</blockquote></details>

Done. Yikes! that was from some debug code. Fixed elsewhere in this implementation too.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhsFvx8fOalav0w4jM5:-Khuxg0tuo4fclO9_hqV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f7b01b4858f51396a46cd412cc7e7a83c0b3f493/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h#L28)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`given`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by liangfok** [comment]
+@liangfok completed first pass.

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwZyZ9Qg60jMspQ8At:-KhwZyZ9Qg60jMspQ8Au:b-5tzd9x) (no related file):*
Instead of re-implementing `DrakeVisualizer`'s message transmission logic within `SimpleTreeVisualizer`, have you thought about making it instantiate a `DrakeVisualizer`, fix its input port to be the joint position state, and then calling `Publish()` on it?

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwW8ADfWbWMq7nn5w_:-KhwW8ADfWbWMq7nn5wa:b-m0houe) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L8)):*
> ```Python
>     "//tools:drake.bzl",
>     "drake_cc_library",
>     "drake_cc_binary",
> ```

BTW, alpha sort.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 22 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwWCIMWGbqXxF7ChOc:-KhwWCIMWGbqXxF7ChOd:b-m0houe) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L22)):*
> ```Python
>         "//drake/multibody/rigid_body_plant:drake_visualizer",
>         "//drake/multibody/rigid_body_plant:create_load_robot_message",
>         "//drake/lcmtypes:viewer",
> ```

BTW, alpha sort.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwXLpqGpPVG7yBeZOp:-KhwXLprh4LmCa-OXfc3:b-m0houe) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L39)):*
> ```Python
>         ":simple_tree_visualizer",
>         "//drake/common",
>         "@gflags//:gflags",
> ```

BTW, alpha sort.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwWHQ1aECLWwphvmHX:-KhwWHQ3vnatB1ucI3SU:b-la4t2w) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L42)):*
> ```Python
>         "//drake/lcm",
>         "//drake/systems/framework",
>         "//drake/multibody/parsers",        
> ```

BTW, trailing space. 

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwZB5WsRIwdCPBLrel:-KhwZB5WsRIwdCPBLrem:bf74mbw) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc#L23)):*
> ```cpp
>     : tree_(tree), state_dimension_(tree_.get_num_positions() +
>     tree_.get_num_velocities()), draw_message_translator_(tree_), lcm_(lcm) {
>   // loads the robot
> ```

BTW, cappunc per style guide.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwYeWc6uq8R6DRVxZG:-KhwYeWc6uq8R6DRVxZH:bldms2c) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h#L19)):*
> ```objc
>  public:
>   /**
>    * Constructs the `SimpleTreeVisualizer`
> ```

Missing period at end of sentence.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwYfnNKzc0rlv1xXh7:-KhwYfnNKzc0rlv1xXh8:bw8olal) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h#L19)):*
> ```objc
>  public:
>   /**
>    * Constructs the `SimpleTreeVisualizer`
> ```

Consider documenting the fact that this constructor also publishes the load robot message since such behavior is externally observable and important in the sense that the user must know to start `drake-visualizer` prior to calling this constructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-:-KhwamVsZ_XdD2K1bHeX:ba74cs7)*

**Comment by naveenoid** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwZyZ9Qg60jMspQ8At:-KhwmBuVNbEDkY6dMaVn:b-hc9rp5) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Instead of re-implementing `DrakeVisualizer`'s message transmission logic within `SimpleTreeVisualizer`, have you thought about making it instantiate a `DrakeVisualizer`, fix its input port to be the joint position state, and then calling `Publish()` on it?
</blockquote></details>

I strongly considered it but I figured this is a more straightfoward version, no need for contexts etc. Do you think thats a better implementation since its tested?

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwW8ADfWbWMq7nn5w_:-KhwtD1Eul6rQLzKULQ7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L8)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, alpha sort.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 22 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwWCIMWGbqXxF7ChOc:-KhwtV_YhkQG6udrG7BK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, alpha sort.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwXLpqGpPVG7yBeZOp:-KhwtcJcCquFF2I89Lfm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L39)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, alpha sort.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwWHQ1aECLWwphvmHX:-KhwtgOvAg0d4pNbSMll:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/BUILD#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, trailing space. 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwZB5WsRIwdCPBLrel:-Khwtkug4hFjqoq9LVv6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.cc#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, cappunc per style guide.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwYeWc6uq8R6DRVxZG:-KhwtpsTQIlPtrdxtIGD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Missing period at end of sentence.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwYfnNKzc0rlv1xXh7:-KhwuHAkxA5ULHIhl6qs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0f3760f76c1d6c2f8eb93e522a3f01318694af82/drake/examples/kuka_iiwa_arm/tools/simple_tree_visualizer.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Consider documenting the fact that this constructor also publishes the load robot message since such behavior is externally observable and important in the sense that the user must know to start `drake-visualizer` prior to calling this constructor.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by liangfok** [comment]
Reviewed 3 of 4 files at r4.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwZyZ9Qg60jMspQ8At:-Khx8-DLJuU1GdGn8EWF:b75665s) (no related file):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I strongly considered it but I figured this is a more straightfoward version, no need for contexts etc. Do you think thats a better implementation since its tested?
</blockquote></details>

I think reusing `DrakeVisualizer` is preferable since any changes to the communication protocol between Drake and `drake-visualizer` could be contained within a single class (see, for example #3421). How about placing the newly introduced `kuka_iiwa_arm/tools/` in `kuka_iiwa_arm/dev/tools/` with a TODO comment saying it should be updated to use `DrakeVisualizer` prior to being moved into a non-dev directory?

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Khx9fx4sRwEHgOQS3FJ:-Khx9fx54FFTzAULZC--:b-la4rf3) ([raw file](https://github.com/robotlocomotion/drake/blob/29b8977d5519fc4a825b52c190f2d7ca4d45547f/drake/examples/kuka_iiwa_arm/tools/BUILD#L19)):*
> ```Python
>         "//drake/common",
>         "//drake/lcm",
>         "//drake/lcmtypes:viewer",        
> ```

BTW, trailing spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by liangfok** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-KhwZyZ9Qg60jMspQ8At:-KhxBDg9f4fgwwX9fMuY:b1ruva4) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I think reusing `DrakeVisualizer` is preferable since any changes to the communication protocol between Drake and `drake-visualizer` could be contained within a single class (see, for example #3421). How about placing the newly introduced `kuka_iiwa_arm/tools/` in `kuka_iiwa_arm/dev/tools/` with a TODO comment saying it should be updated to use `DrakeVisualizer` prior to being moved into a non-dev directory?
</blockquote></details>

Very good suggestion. Will update accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-:-KhxH64PtKWt-GLOwbYj:bvi7gqa)*

**Comment by naveenoid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/tools/BUILD, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Khx9fx4sRwEHgOQS3FJ:-Ki-dz6Yy7xC3t-m1rM_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/29b8977d5519fc4a825b52c190f2d7ca4d45547f/drake/examples/kuka_iiwa_arm/tools/BUILD#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, trailing spaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by liangfok** [comment]
:lgtm: Thanks again!

---

Reviewed 9 of 12 files at r5.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h, line 10 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki07kOcb-rGLGipEOF3:-Ki07kOcb-rGLGipEOF4:b5i8f7c) ([raw file](https://github.com/robotlocomotion/drake/blob/3d85fca317111c3871dc5aa1224c30306f78220a/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h#L10)):*
> ```objc
> namespace kuka_iiwa_arm {
> namespace tools {
> // TODO(naveenoid) : Modify component to simply wrap DrakeVisualizer before
> ```

BTW, consider replacing "component" with "this class" for extra clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-:-Ki07ZjG18-NbjFjgMVX:b1m2fd)*

**Comment by liangfok** [comment]
Reviewed 2 of 12 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by naveenoid** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h, line 10 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki07kOcb-rGLGipEOF3:-Ki0LIUbUcxMmJl46btt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d85fca317111c3871dc5aa1224c30306f78220a/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "component" with "this class" for extra clarity.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by liangfok** [comment]
Reviewed 1 of 12 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-:-Ki0eseLe5eeoen-Vx88:b-t6qajt)*

**Comment by sammy-tri** [comment]
Reviewed 10 of 12 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h, line 17 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki0uCkEO-GmbHw-9wEc:-Ki0uCkFxBy3IZ2f9YTw:b-c5byjp) ([raw file](https://github.com/robotlocomotion/drake/blob/a6c4ad286058312e7c810d15d1c52cf076114ea9/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h#L17)):*
> ```objc
>  */
> class SimpleTreeVisualizer {
>  public:
> ```

FYI Consider declaring DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN from common/drake_copyable.h

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer_demo.cc, line 30 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki0uy05grxeEFhanavr:-Ki0uy06bi5ECMikeuqN:bcp0mcd) ([raw file](https://github.com/robotlocomotion/drake/blob/a6c4ad286058312e7c810d15d1c52cf076114ea9/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer_demo.cc#L30)):*
> ```cpp
>   // Adds a demo tree.
>   const std::string kModelPath =
>       "/manipulation/models/iiwa_description/urdf/"
> ```

Are you planning on adding a version in a future PR where the model and/or configuration can be specified on the command line?  (I think you might have told me something like this but can't remember.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by naveenoid** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h, line 17 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki0uCkEO-GmbHw-9wEc:-Ki5-6fI2Z5kUm82FqT-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6c4ad286058312e7c810d15d1c52cf076114ea9/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer.h#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

FYI Consider declaring DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN from common/drake_copyable.h
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer_demo.cc, line 30 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki0uy05grxeEFhanavr:-Ki5-Bo7BySSgx7eYxvg:bz86jl2) ([raw file](https://github.com/robotlocomotion/drake/blob/a6c4ad286058312e7c810d15d1c52cf076114ea9/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer_demo.cc#L30)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Are you planning on adding a version in a future PR where the model and/or configuration can be specified on the command line?  (I think you might have told me something like this but can't remember.)
</blockquote></details>

This was meant to be a lib to link but that would make it a standalone application as well no? Or maybe you want this lib to also link to gflags? Whats the best kind of TODO I can leave for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 12 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer_demo.cc, line 30 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-Ki0uy05grxeEFhanavr:-Ki5ZYsXxPA9fgYdSbHs:b-wx30fi) ([raw file](https://github.com/robotlocomotion/drake/blob/a6c4ad286058312e7c810d15d1c52cf076114ea9/drake/examples/kuka_iiwa_arm/dev/tools/simple_tree_visualizer_demo.cc#L30)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

This was meant to be a lib to link but that would make it a standalone application as well no? Or maybe you want this lib to also link to gflags? Whats the best kind of TODO I can leave for now?
</blockquote></details>

Upon further reflection it's fine for now.  if someone wants a more generic tool later they can use this to build it.  Sorry for the delay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5854#-:-Ki5ZnO6R6YEFkDzPVxJ:bnfp4nl)*

**Pull request merged**
