### PR TITLE
Use absolute paths in mac install scripts.

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8632)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-:-LATG6AD-5fqKwI5wom7:bg4w8lp)*

**Comment by jamiesnape** [comment]
BTW For completeness, there are a couple of `grep` commands in `install_prereqs_user_environment.sh`. It is not a shell builtin on macOS as far as I am aware.

:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-:-LATHKvC4orJ7DE2wOSm:b-ougbbt)*

**Comment by soonho-tri** [comment]
> BTW For completeness, there are a couple of grep commands in install_prereqs_user_environment.sh. It is not a shell builtin on macOS as far as I am aware.

Done.

@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-:-LATImTM9Cdb9inZeLof:b8o29pt)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[setup/mac/binary_distribution/install_prereqs.sh, line 14 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-LATJDkn48--P81QuIL-:-LATJDko0SYmlu3mHbic:bepsbkh) ([raw file](https://github.com/robotlocomotion/drake/blob/ade92965431f19d4b8e58094fbdde98186409d2d/setup/mac/binary_distribution/install_prereqs.sh#L14)):*
> ```Shell
> 
> if ! command -v /usr/local/bin/brew &>/dev/null; then
>   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
> ```

I missed `curl`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/binary_distribution/install_prereqs.sh, line 14 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-LATJDkn48--P81QuIL-:-LATLJbw3BTDD3vyE-iC:bb6tyiv) ([raw file](https://github.com/robotlocomotion/drake/blob/ade92965431f19d4b8e58094fbdde98186409d2d/setup/mac/binary_distribution/install_prereqs.sh#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I missed `curl`.
</blockquote></details>

DONE

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for platform-review, please (as I'm on-call today). Thank you. 

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-:-LATLS3G-EuNGwwlEGPr:b-96t44k)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-:-LATMF9g5DKL737Witdc:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632#-:-LATN6kO5sSZzbsSpfzO:b-uou2c5)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8632)*

**Comment by soonho-tri** [comment]
Do not merge until the unprovisioned builds pass.

**Pull request merged**
