### PR TITLE
Moves ZmpPlanner to planning directory and adds python bindings.

### PR DESCRIPTION
**Pull request by RussTedrake**
+@jwnimmer-tri for feature review, please (due to the relocation).  Or both reviews if you are ok with it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
First pass complete.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-:-NvYRTL52RIUlekHBaGH:bvb1a6z)* status: 7 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),calderpg-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYOe4O-hT7Y52SPFau:-NvYOe4P-DhmBM-xL7TG:b-1g168l) (no related file):*
I'll tag +@calderpg-tri to this thread to help review the high-level directory choice (not for detailed code review).

I am not sure using the top-level directory for this is the right place.  So far, the top-level directory is only for the fundamental lower-level tools used by all/most planning code, like the collision checkers and the robot diagram.  Specific planning algorithms live in subdirectories.  This code seems like a specific planning algorithm, not a lower-layer tool, so it should go in some subdir?

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYRdSP7qgsk2j7uFRj:-NvYRdSP7qgsk2j7uFRk:bw28lzp) (no related file):*
This needs deprecation shims for the old include path and old C++ namespace.  (Just for the planner itself, not for the test utility.)

Should I push the patch for that here, once everything else has settled down?

+(release notes: newly deprecated) 

___
___
*[`planning/BUILD.bazel` line 238 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYNggI0DnPICS8SfVl:-NvYNggI0DnPICS8SfVm:b-c2r6sd) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/planning/BUILD.bazel#L238)):*
> ```Starlark
>         ":zmp_planner",
>     ],
> )
> ```

nit Because this utility library is used by code outside of this package, it must live in the `test_utilities` subdirectory, not the `test` subdirectory.  (Code in `test` must be private visibility.)

Even if the zmp moves into a subdir, using `planning/test_utilities` for this code is still fine.
___
*[`bindings/pydrake/planning/planning_py_zmp_planner.cc` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYQ5GSD340nFJamiwA:-NvYQ5GSD340nFJamiwB:b-bvoli9) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/planning_py_zmp_planner.cc#L23)):*
> ```cpp
>             py::arg("Qy") = Eigen::Matrix2d::Identity(),
>             py::arg("R") = 0.1 * Eigen::Matrix2d::Identity(), cls_doc.ctor.doc)
>         .def("ComputeOptimalCoMdd", &Class::ComputeOptimalCoMdd,
> ```

Missing binding for `has_planned()`.
___
*[`bindings/pydrake/planning/planning_py_zmp_planner.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYQuTL0BkRgzEA2MJH:-NvYQuTL0BkRgzEA2MJI:b-imuekb) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/planning_py_zmp_planner.cc#L53)):*
> ```cpp
>         .def("get_desired_zmp",
>             overload_cast_explicit<
>                 const trajectories::PiecewisePolynomial<double>&>(
> ```

BTW There are no rvp annotations on these ones, so we are copying the PP instead of aliasing it.  Is that what we want?  It might be worth annotating `py_rvp::copy` to clarify, if so.  It's a little bit confusing as-is.
___
*[`bindings/pydrake/planning/planning_py_zmp_planner.cc` line 81 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYPyTG-sAzdgNreiMw:-NvYPyTG-sAzdgNreiMx:b-cg6z76) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/planning_py_zmp_planner.cc#L81)):*
> ```cpp
>                 &Class::get_Vx),
>             cls_doc.get_Vx.doc);
>   }
> ```

BTW The C++ class is copyable.  Should we bind the copy/deepcopy here too?  (If yes, note there is a C++ helper function to do it.)
___
*[`bindings/pydrake/planning/test/zmp_planner_test.py` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYRGenAv8CEBPpkqrO:-NvYRGeo-ecuvBJaKRYt:b-2drna4) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/test/zmp_planner_test.py#L37)):*
> ```Python
>             zmp_d.value(sample_time))
>         np.testing.assert_almost_equal(
>             planner.get_desired_zmp(time=sample_time).reshape((2, 1)),
> ```

nit I think this was supposed to test the zero-arg overload of get_desired_zmp, but instead it's just a copy of the prior assert with no changes.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305)* status: 7 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),calderpg-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYOe4O-hT7Y52SPFau:-NveON7CE4C5UQZIhANM:b-4xydgy) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll tag +@calderpg-tri to this thread to help review the high-level directory choice (not for detailed code review).

I am not sure using the top-level directory for this is the right place.  So far, the top-level directory is only for the fundamental lower-level tools used by all/most planning code, like the collision checkers and the robot diagram.  Specific planning algorithms live in subdirectories.  This code seems like a specific planning algorithm, not a lower-layer tool, so it should go in some subdir?
</blockquote></details>

I agree with Jeremy that this feels like a very specific planning algorithm that should go in a subdirectory. Perhaps `planning/zmp`?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305)* status: 7 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),calderpg-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYRdSP7qgsk2j7uFRj:-NvgqCsj0qiEjm5GbkkD:b-57bhu3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This needs deprecation shims for the old include path and old C++ namespace.  (Just for the planner itself, not for the test utility.)

Should I push the patch for that here, once everything else has settled down?

+(release notes: newly deprecated)
</blockquote></details>

Working

Per f2f, I will do this part of the PR, once the other parts are stabilized.

___

**Review by RussTedrake — COMMENTED** [review]
Comments addressed.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-:-Nw1CJe5DyntWUBTiu8z:bxdqe65)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),calderpg-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYOe4O-hT7Y52SPFau:-Nw0zC_rEeQ4962xTF0e:bv03j7b) (no related file):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

I agree with Jeremy that this feels like a very specific planning algorithm that should go in a subdirectory. Perhaps `planning/zmp`?
</blockquote></details>

Done. I've created `planning/locomotion`

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYRdSP7qgsk2j7uFRj:-Nw0zGxd95iWWwZOD4V3:bsv417u) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Per f2f, I will do this part of the PR, once the other parts are stabilized.
</blockquote></details>

thank you.

___
___
*[`planning/BUILD.bazel` line 238 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYNggI0DnPICS8SfVl:-Nw1-4ys9pJhEfnMzUg0:b-l7642v) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/planning/BUILD.bazel#L238)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Because this utility library is used by code outside of this package, it must live in the `test_utilities` subdirectory, not the `test` subdirectory.  (Code in `test` must be private visibility.)

Even if the zmp moves into a subdir, using `planning/test_utilities` for this code is still fine.
</blockquote></details>

Done.  (but i thought `planning/locomotion/test_utilities` seemed more correct?)
___
*[`bindings/pydrake/planning/planning_py_zmp_planner.cc` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYQ5GSD340nFJamiwA:-Nw1ASnU4VGrK_VQn6_9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/planning_py_zmp_planner.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing binding for `has_planned()`.
</blockquote></details>

Done.
___
*[`bindings/pydrake/planning/planning_py_zmp_planner.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYQuTL0BkRgzEA2MJH:-Nw1BR2e0KKIdue-BkAO:bmfxq1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/planning_py_zmp_planner.cc#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW There are no rvp annotations on these ones, so we are copying the PP instead of aliasing it.  Is that what we want?  It might be worth annotating `py_rvp::copy` to clarify, if so.  It's a little bit confusing as-is.
</blockquote></details>

Done.  
___
*[`bindings/pydrake/planning/planning_py_zmp_planner.cc` line 81 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYPyTG-sAzdgNreiMw:-Nw1B54o8-0dpl0xOElR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/planning_py_zmp_planner.cc#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The C++ class is copyable.  Should we bind the copy/deepcopy here too?  (If yes, note there is a C++ helper function to do it.)
</blockquote></details>

Done.
___
*[`bindings/pydrake/planning/test/zmp_planner_test.py` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYRGenAv8CEBPpkqrO:-Nw1CHGgEMdetwi2yLr3:bkz5ckv) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/bindings/pydrake/planning/test/zmp_planner_test.py#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think this was supposed to test the zero-arg overload of get_desired_zmp, but instead it's just a copy of the prior assert with no changes.
</blockquote></details>

Done.  Good catch.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 12 of 12 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305)* status: LGTM missing from assignees jwnimmer-tri(platform),calderpg-tri, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYRdSP7qgsk2j7uFRj:-Nw1PwZ-05LToQGhiCPJ:b-896fix) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

thank you.
</blockquote></details>

Done.

___
___
*[`planning/BUILD.bazel` line 238 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-NvYNggI0DnPICS8SfVl:-Nw1P0m11HytJf7UxuNa:b-sfjsrt) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bc559305264c3f5555dc4070e211076fd3abc53/planning/BUILD.bazel#L238)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (but i thought `planning/locomotion/test_utilities` seemed more correct?)
</blockquote></details>

OK I don't think the extra nesting adds value, but it's fine either way.

I pushed a fix that test_utilities must always be its own package.

**Comment by jwnimmer-tri** [comment]
:lgtm: feature.

+@rpoyner-tri for platform review per schedule (tomorrow), please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 14 files at r1, 9 of 12 files at r2, 5 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-:-NwBS_aH-bC4JdienGhJ:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri assign didn't take?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-:-NwBSgiY5dSoH_eRdbxS:b-5pfeya)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
I can do the squash for this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305#-:-NwBZBUnCqNMjb2zzutF:bhedvm8)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21305)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
