### PR TITLE
Update CLion+Bazel docs to reflect latest plugin release.

### PR DESCRIPTION
**Pull request by david-german-tri**
https://github.com/bazelbuild/intellij/pull/53 is awesome!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5120)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@lucy-tri for feature review.  It is well worth the update: just pull the latest plugin source, rebuild as documented, and reinstall.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by Lucy-tri** [comment]
Does this plugin still only work with CLion 2016.2.3? Sorry it's taken me a while to get to this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kcd62GdmxY0GWSjyuo6:b-aofgjp)*

**Comment by david-german-tri** [comment]
> Does this plugin still only work with CLion 2016.2.3? 

Yes.

> Sorry it's taken me a while to get to this.

Not really, and in any case no worries!

**Comment by Lucy-tri** [comment]
I seem to have built the plugin ok, from source. Then in CLion: settings; plugins; install plugin from disk:
"Plugin 'IntelliJ with Bazel' is incompatible with this installation"

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kcd8HSgZypSXDbITJOQ:blr5a2w)*

**Comment by david-german-tri** [comment]
The plugin should be called "CLion with Bazel", not "IntelliJ with Bazel".  Are you sure you built and loaded `clwb_bazel.jar`?

**Comment by Lucy-tri** [comment]
Assuming cl is for CLion : ok how do I build that? 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-KcdCQR81LehQmGe7pZL:bi8fyh5)*

**Comment by Lucy-tri** [comment]
I don't see a pre-built jar: I have to build it, right?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-KcdCjuhljeTzsossxuK:b-93xqx7)*

**Comment by david-german-tri** [comment]
Yep, you have to build it.  That part of the instructions is unchanged: http://drake.mit.edu/clion.html#installing-clion-and-the-bazel-plugin

**Comment by Lucy-tri** [comment]
Ok, got it. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-KcdGUhTpmBlhlH6PI0g:b3bwmjq)*

**Comment by Lucy-tri** [comment]
Getting this warning in CLion after a sync:
Warning:Sync was successful, but there were compilation errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Blaze > Expand Sync to Working Set' and try again.
Humor: I think they misspelled bazel (Blaze)?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-KcdOk09vcMw39ecQhYz:b4vz3vb)*

**Comment by Lucy-tri** [comment]
It can't seem to build ipopt from CLion, but the bazel build from the cmd line works.  I think ipopt isn't supported yet for bazel?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-KcdPUGotMMlcQ5lN7hK:b-jqit8a)*

**Comment by david-german-tri** [comment]
Addressed f2f: `ccache` on the path strikes again!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kct6eGvKCn0v9EryEr5:b8q23g)*

**Comment by Lucy-tri** [comment]
@david-german-tri, the only remaining question is whether we need a note for users who are switching from using CLion with a ccache compiler to using Bazel, to tell them they need to somehow do a Bazel clean for the CLion build, OR to remove ccache from their system. 
Maybe to add something like:
Note that Bazel is not compatible with ccache. To use Bazel, you must have a PATH that does not include ccache, and CLion may cache the path.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-KcsCWHLQEjBpareWK8U:b-qyya35)*

**Comment by david-german-tri** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kd1UI-Ga2Mc9pNLbZAT:b-896fix)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kd2-FmuDl81tpEYkyD7:bnfp4nl)*

**Comment by Lucy-tri** [comment]
+@sammy-tri  for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kd2-MPTElfntkooazeC:bgepo9b)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5120#-:-Kd25MEqu_xRsHlYqORI:bnfp4nl)*

**Pull request merged**
