### PR TITLE
Fix a bug in Accelerometer

### PR DESCRIPTION
**Pull request by yminchen**
The measured acceleration caused by gravity should point upward (to positive z axis).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11821)

### CODE REVIEW

**Comment by yminchen** [comment]
> Why shouldn't the acceleration caused by gravity point in the direction of gravity?
> 
> > _[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11821#-:-LkQlqL7AWJHmqKbwcBR:b-klxhnz)_ status: needs platform reviewer assigned, needs at least two assigned reviewers

It's a bit counterintuitive. Gravity pulls the mass inside the IMU downward which results in upward measured acceleration.
Two examples from wikipedia (frist paragraph): https://en.wikipedia.org/wiki/Accelerometer

**Comment by mposa** [comment]
Looks like there already is a test, but it's also got the wrong sign: https://github.com/RobotLocomotion/drake/blob/79f4c7a238491d96d98b151ff55297c6666dd14e/attic/systems/sensors/test/accelerometer_test/accelerometer_test.cc#L96

I'm guessing we'd see a failure here, but the CI servers seem to be hanging

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by yminchen** [comment]
Just added comments and updated the unit test.

**Comment by yminchen** [comment]
@sherm1 Got it! I just updated the code.

**Pull request merged**
