### PR TITLE
MeshDeformer updates mesh normal, area and centroid

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #18922. Pre-requisite for #20851.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review please.

+(priority: low) I'll be OOO until next Tuesday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-:-NpSGAki09JPQhMlWqCo:buzn5b8)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-:-NpV_PiRCtBwD2HtYb-G:b-te4kzy)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`geometry/proximity/polygon_surface_mesh.h` line 314 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVSF281c9Z8TThN5Mh:-NpVSF281c9Z8TThN5Mi:b-lavwtj) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/polygon_surface_mesh.h#L314)):*
> ```objc
>   /* Calculates and sets the area, normal, and centroid of all polygon faces.
>    Also computes and sets the centroid of the entire surface. */
>   void CalcAreasNormalsAndCentroid();
> ```

nit The function name is possibly alright. However, it bleeds a lot of implementation details without capturing the true *point* of the function. Volume mesh doesn't currently *store* any vertex-position -dependent quantities, but it could in the future (which might be to its benefit). Making all of them uniform would be good.

I realize that you copied this name from `TriangleSurfaceMesh` but now be the right time to make a broader change.

I'd recommend the following

1. Rename it to something like `ComputePositionDependentQuantities()` (feel free to come up with a better name).
2. Each mesh class could implement the a method with the same signature (`VolumeMesh`'s would currently be empty).
3. The deformer wouldn't have to make decisions based on mesh type. Knowing it updated vertex positions, it would simply invoke `ComputePositionDependentQuantities()` blindly, letting each mesh interpret what that means as appropriate.
___
*[`geometry/proximity/polygon_surface_mesh.h` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVVKMR98beER7E7AqI:-NpVVKMS70nb5InPXSg-:b-sdpagu) ([raw file](https://github.com/RobotLocomotion/drake/blob/17c13d6dc1076d71cdd0729aff52a6ffad54043b/geometry/proximity/polygon_surface_mesh.h#L341)):*
> ```objc
> 
>   /* The vertices referenced by the mesh's polygons. */
>   std::vector<Vector3<T>> vertices_M_;
> ```

BTW Why the elimination of the frame? That seems defective.  The vertex positions do depend on a frame, therefore the variable should carry that. Yes?
___
*[`geometry/proximity/polygon_surface_mesh.cc` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpV_I9V1En6LdVboUiH:-NpV_I9W2Vx_MaIOBa8F:b6fszm3) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/polygon_surface_mesh.cc#L69)):*
> ```cpp
> 
> template <class T>
> void PolygonSurfaceMesh<T>::CalcAreasNormalsAndCentroid() {
> ```

nit: This should be tested in `polygon_surface_mesh_test.cc`.
___
*[`geometry/proximity/test/mesh_deformer_test.cc` line 129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVXxhd1bBfsCoAJjTv:-NpVXxhd1bBfsCoAJjTw:bwf92s2) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/test/mesh_deformer_test.cc#L129)):*
> ```cpp
> }
> 
> // N.B. We can't use partial specialization on functions, so we create a factory
> ```

nit: This entire block of code can be simplified (no specialization tricks required):


```c++
// Makes a mesh consisting of a single triangle whose normal is *not* along the
// z-axis.
template <typename MeshType>
MeshType MakeSingleTriangle() {
  using T = typename MeshType::ScalarType;
  std::vector<Vector3<T>> vertices;
  vertices.emplace_back(0, 0, 0);
  vertices.emplace_back(0, 2, 0);
  vertices.emplace_back(0, 0, 2);
  // The mesh types only differ in how they describe faces.
  if constexpr (std::is_same_v<MeshType, TriangleSurfaceMesh<T>>) {
    std::vector<SurfaceTriangle> triangles;
    triangles.emplace_back(0, 1, 2);
    return TriangleSurfaceMesh(std::move(triangles), std::move(vertices));
  } else if constexpr (std::is_same_v<MeshType, PolygonSurfaceMesh<T>>) {
    std::vector<int> face_data{3, 0, 1, 2};
    return PolygonSurfaceMesh(std::move(face_data), std::move(vertices));
  } else {
    throw std::logic_error("Unimplemented");
  }
}
```

And the invocation on the constructor of `MeshDeformerDataTest` goes from:

```C++
mesh_(SingleTriangleMaker<T, MeshType>().make()),
```
to
```c++
mesh_(MakeSingleTriangle<MeshType<T>>())
```

(This also eliminates the style infractions of calling the function "make" instead of "Make" and changes the weird call to a static member.
___
*[`geometry/proximity/test/mesh_deformer_test.cc` line 166 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVYvnl5tVU6LDI1cjS:-NpVYvnm1HIBLx-g9vlR:bvrfkon) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/test/mesh_deformer_test.cc#L166)):*
> ```cpp
> 
> // Tests that for surface meshes, auxiliary quantities (face normal, face area,
> // and mesh centroid) are updated along with vertex position changes.
> ```

btw: I'd make the argument that you don't have to specifically test all of the quantities you're testing.

The mesh type has a method that should update quantities based on vertex positions. Those functions should be documented and tested in their own unit tests.

The deformer's only responsibility is to tell the mesh to update itself based on the fact that vertex positions have changed. Therefore, you only need evidence that it got invoked. Simply checking one dependent quantity would be enough (e.g., total area?)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`geometry/proximity/polygon_surface_mesh.h` line 314 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVSF281c9Z8TThN5Mh:-Npz_FKX4EoN7hFyj67X:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/polygon_surface_mesh.h#L314)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit The function name is possibly alright. However, it bleeds a lot of implementation details without capturing the true *point* of the function. Volume mesh doesn't currently *store* any vertex-position -dependent quantities, but it could in the future (which might be to its benefit). Making all of them uniform would be good.

I realize that you copied this name from `TriangleSurfaceMesh` but now be the right time to make a broader change.

I'd recommend the following

1. Rename it to something like `ComputePositionDependentQuantities()` (feel free to come up with a better name).
2. Each mesh class could implement the a method with the same signature (`VolumeMesh`'s would currently be empty).
3. The deformer wouldn't have to make decisions based on mesh type. Knowing it updated vertex positions, it would simply invoke `ComputePositionDependentQuantities()` blindly, letting each mesh interpret what that means as appropriate.
</blockquote></details>

Done
___
*[`geometry/proximity/polygon_surface_mesh.h` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVVKMR98beER7E7AqI:-NpzZ1nG7tKW_sSXXksb:buwld6z) ([raw file](https://github.com/RobotLocomotion/drake/blob/17c13d6dc1076d71cdd0729aff52a6ffad54043b/geometry/proximity/polygon_surface_mesh.h#L341)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Why the elimination of the frame? That seems defective.  The vertex positions do depend on a frame, therefore the variable should carry that. Yes?
</blockquote></details>

Right now, MeshDeformer reaches for the private data member of the mesh classes, so we need a consistent name for the vertex positions.

```cpp
  for (int v = 0, i = 0; v < mesh_.num_vertices(); ++v, i += 3) {
    mesh_.vertices_[v] = Vector3<T>(p_MVs[i], p_MVs[i + 1], p_MVs[i + 2]);
  }
```

The two alternatives are:
1. changing the name the other way (i.e. to `vertices_M_` for all meshes), and 
2. each mesh class provides a public function to set its own vertex positions.
___
*[`geometry/proximity/polygon_surface_mesh.cc` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpV_I9V1En6LdVboUiH:-Nq-HN1a4bryjHK5dGFF:b-fkkwem) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/polygon_surface_mesh.cc#L69)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This should be tested in `polygon_surface_mesh_test.cc`.
</blockquote></details>

Done , PTAL.
___
*[`geometry/proximity/test/mesh_deformer_test.cc` line 129 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVXxhd1bBfsCoAJjTv:-Npz_9SJCqjRy8zcQEDH:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/test/mesh_deformer_test.cc#L129)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This entire block of code can be simplified (no specialization tricks required):


```c++
// Makes a mesh consisting of a single triangle whose normal is *not* along the
// z-axis.
template <typename MeshType>
MeshType MakeSingleTriangle() {
  using T = typename MeshType::ScalarType;
  std::vector<Vector3<T>> vertices;
  vertices.emplace_back(0, 0, 0);
  vertices.emplace_back(0, 2, 0);
  vertices.emplace_back(0, 0, 2);
  // The mesh types only differ in how they describe faces.
  if constexpr (std::is_same_v<MeshType, TriangleSurfaceMesh<T>>) {
    std::vector<SurfaceTriangle> triangles;
    triangles.emplace_back(0, 1, 2);
    return TriangleSurfaceMesh(std::move(triangles), std::move(vertices));
  } else if constexpr (std::is_same_v<MeshType, PolygonSurfaceMesh<T>>) {
    std::vector<int> face_data{3, 0, 1, 2};
    return PolygonSurfaceMesh(std::move(face_data), std::move(vertices));
  } else {
    throw std::logic_error("Unimplemented");
  }
}
```

And the invocation on the constructor of `MeshDeformerDataTest` goes from:

```C++
mesh_(SingleTriangleMaker<T, MeshType>().make()),
```
to
```c++
mesh_(MakeSingleTriangle<MeshType<T>>())
```

(This also eliminates the style infractions of calling the function "make" instead of "Make" and changes the weird call to a static member.
</blockquote></details>

Done, thanks.
___
*[`geometry/proximity/test/mesh_deformer_test.cc` line 166 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVYvnl5tVU6LDI1cjS:-Nq-JaLr4o37rYAzLzNo:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b69ca2ce9685ac8462a3702b6a621beb407437ac/geometry/proximity/test/mesh_deformer_test.cc#L166)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: I'd make the argument that you don't have to specifically test all of the quantities you're testing.

The mesh type has a method that should update quantities based on vertex positions. Those functions should be documented and tested in their own unit tests.

The deformer's only responsibility is to tell the mesh to update itself based on the fact that vertex positions have changed. Therefore, you only need evidence that it got invoked. Simply checking one dependent quantity would be enough (e.g., total area?)
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@ggould-tri for platform review, please.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-:-Nq-UUeK2SRu9O_NZYO9:b-gf9ydc)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`geometry/proximity/polygon_surface_mesh.h` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVVKMR98beER7E7AqI:-Nq-S2Ou4XwOk7idrB0B:b3uljcb) ([raw file](https://github.com/RobotLocomotion/drake/blob/17c13d6dc1076d71cdd0729aff52a6ffad54043b/geometry/proximity/polygon_surface_mesh.h#L341)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Right now, MeshDeformer reaches for the private data member of the mesh classes, so we need a consistent name for the vertex positions.

```cpp
  for (int v = 0, i = 0; v < mesh_.num_vertices(); ++v, i += 3) {
    mesh_.vertices_[v] = Vector3<T>(p_MVs[i], p_MVs[i + 1], p_MVs[i + 2]);
  }
```

The two alternatives are:
1. changing the name the other way (i.e. to `vertices_M_` for all meshes), and 
2. each mesh class provides a public function to set its own vertex positions.
</blockquote></details>

Ah....you were making them match.  You can guess which of (1) and (2) I'd prefer.  :) It's especially nice because the M that would appear there would be the correct symbol. All of the mesh types use `M` to describe the mesh's frame, so it's consistent there as well. So, let's have `M`'s all around, please.
___
*[`geometry/proximity/volume_mesh.h` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq-Sm3y5qIKUsBUJK9H:-Nq-Sm3y5qIKUsBUJK9I:b-qh3tjj) ([raw file](https://github.com/RobotLocomotion/drake/blob/555862af4d670768e7a72f41f9152fb554f8b223/geometry/proximity/volume_mesh.h#L317)):*
nit: Let's push this comment a bit further:

> Currently, VolumeMesh doesn't have any position dependent quantities, but requires the method to maintain `MeshDeformer` compatibility with the other mesh types.
___
*[`geometry/proximity/test/polygon_surface_mesh_test.cc` line 449 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq-U5a3Dfi6i0nUT8-a:-Nq-U5a3Dfi6i0nUT8-b:b-td4gvj) ([raw file](https://github.com/RobotLocomotion/drake/blob/555862af4d670768e7a72f41f9152fb554f8b223/geometry/proximity/test/polygon_surface_mesh_test.cc#L449)):*
> ```cpp
>   ASSERT_EQ(mesh.num_faces(), expected_face_count);
> 
>   std::vector<Vector3<T>> vertices = {
> ```

nit `const`

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq3-1PI6c4b1G3dTVs4:-Nq3-1PI6c4b1G3dTVs5:bsyvt97) (no related file):*
This PR seems to introduce a risky design choice that I think need to be clarified.

`ComputePositionDependentQuantities` seems to introduce a validity invariant into all of the mesh classes, whereby any mutation of `mesh_.vertices_M_` must be followed by a call to `ComputePositionDependentQuantities`.  That's a problem because `vertices_M_` isn't effectively private (because of the use of `friend`) and so the mesh classes cannot enforce this invariant on their own validity.

Obviously any nontrivial use of `friend` is suspect ( https://drake.mit.edu/styleguide/cppguide.html#Friends ).  In this case, though, it's really unusually hazardous because there's this undocumented invariant ("Call CPDQ after touching vertices") that the friend must respect but that anyone writing code in the friend class won't see (because even if it were documented, which it isn't, it's not documented in a place that's clear from the friend).

A more sound approach would be to store the validity of the position dependent quantities and to have a method `GetMutableVertices` instead of direct access to `vertices_M_` which invalidates the position dependent quantities (ie borrows the logic circa polygon_surface_mesh.cc:76) so that `ComputePositionDependentQuantities` has to be called before they are next used.  With the "friend-ness" restricted to method calls rather than direct field access, you could then resolve the issue either by making `GetMutableVertices`/`ComputePositionDependentQuantities` public with an "internal use only" documentation remark (IMO the simpler answer), or by making them members of a superclass and restricting the friendness to that smaller API surface.

___

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`geometry/proximity/test/polygon_surface_mesh_test.cc` line 127 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq37Ji12Thf-mp3a915:-Nq37Ji12Thf-mp3a916:bots7gd) ([raw file](https://github.com/RobotLocomotion/drake/blob/6efba4fcea0abdb96a7f9364121337bb6dee1ce7/geometry/proximity/test/polygon_surface_mesh_test.cc#L127)):*
> ```cpp
>   void ComputePositionDependentQuantities(PolygonSurfaceMesh<T>* mesh) {
>     mesh->ComputePositionDependentQuantities();
>   }
> ```

I don't see how calling these two functions separately would ever be correct.  Why is this not one function?



_Suggestion:_
```cpp
  void SetVertices(const std::vector<Vector3<T>>& vertices,
                   PolygonSurfaceMesh<T>* mesh) {
    mesh->vertices_M_ = vertices;
    mesh->ComputePositionDependentQuantities();
  }
```
___
*[`geometry/proximity/test/polygon_surface_mesh_test.cc` line 469 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq373vpCG5Ph3oYf6qZ:-Nq373vpCG5Ph3oYf6q_:b-7j0in6) ([raw file](https://github.com/RobotLocomotion/drake/blob/6efba4fcea0abdb96a7f9364121337bb6dee1ce7/geometry/proximity/test/polygon_surface_mesh_test.cc#L469)):*
> ```cpp
>       expected_total_area;
> 
>   // Returns true if all vertex position dependent quantities are as expected.
> ```

This seems weird.  You called `SetVertices()` but not `ComputePositionDependentQuantities()` so why would you expect the position dependent quantities to be correct?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq3-1PI6c4b1G3dTVs4:-Nq4e7DZ1WqcsXIUBIW0:b-bobv1y) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is an excellent point.  Although, I'd disagree that the risk gets introduced here, merely exacerbated.

The whole `MeshDeformer` was born years ago of convenience and assumption, but not with long-term strategy in mind. As `MeshDeformer`'s scope has grown, the trade off deemed "acceptable" at that time may not scale well. At that time, there was the precept that the meshes are immutable. If we revisit that assumption, and allow meshes to be mutable, the logical conclusion is that the `SetAllPositions()` method of `MeshDeformer` moves over to each mesh and then each mesh can, in turn, do whatever maintenance is required to keep its state coherent after moving positions.

The warnings on `MeshDeformer` about the dangers of mutating a mesh apply to every object ever returned by reference -- the owner of the thing referred to can mutate it and mess with downstream objects. Nothing new about that.

So, I'd suggest this is the opportunity to take `MeshDeformer` out behind the barn and put it out of its misery.
</blockquote></details>

I took @SeanCurtis-TRI 's suggestion and removed `MeshDeformer`.

___
___
*[`geometry/proximity/polygon_surface_mesh.h` line 341 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NpVVKMR98beER7E7AqI:-Nq-y_XhDWx2PvXh5awU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/17c13d6dc1076d71cdd0729aff52a6ffad54043b/geometry/proximity/polygon_surface_mesh.h#L341)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ah....you were making them match.  You can guess which of (1) and (2) I'd prefer.  :) It's especially nice because the M that would appear there would be the correct symbol. All of the mesh types use `M` to describe the mesh's frame, so it's consistent there as well. So, let's have `M`'s all around, please.
</blockquote></details>

Done.
___
*[`geometry/proximity/volume_mesh.h` line 317 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq-Sm3y5qIKUsBUJK9H:-Nq-ynaB4hZ-aEeYs8GY:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/555862af4d670768e7a72f41f9152fb554f8b223/geometry/proximity/volume_mesh.h#L317)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Let's push this comment a bit further:

> Currently, VolumeMesh doesn't have any position dependent quantities, but requires the method to maintain `MeshDeformer` compatibility with the other mesh types.
</blockquote></details>

Done
___
*[`geometry/proximity/test/polygon_surface_mesh_test.cc` line 449 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq-U5a3Dfi6i0nUT8-a:-Nq-yhyeBRUwf0CDBPso:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/555862af4d670768e7a72f41f9152fb554f8b223/geometry/proximity/test/polygon_surface_mesh_test.cc#L449)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit `const`
</blockquote></details>

Done
___
*[`geometry/proximity/test/polygon_surface_mesh_test.cc` line 127 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq37Ji12Thf-mp3a915:-Nq4dzZR0KKJrP6tDHUp:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/6efba4fcea0abdb96a7f9364121337bb6dee1ce7/geometry/proximity/test/polygon_surface_mesh_test.cc#L127)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I don't see how calling these two functions separately would ever be correct.  Why is this not one function?
</blockquote></details>

Done
___
*[`geometry/proximity/test/polygon_surface_mesh_test.cc` line 469 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-Nq373vpCG5Ph3oYf6qZ:-Nq4e4RkDmSXD0lU7mLX:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/6efba4fcea0abdb96a7f9364121337bb6dee1ce7/geometry/proximity/test/polygon_surface_mesh_test.cc#L469)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems weird.  You called `SetVertices()` but not `ComputePositionDependentQuantities()` so why would you expect the position dependent quantities to be correct?
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@ggould-tri This is ready for another look.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-:-Nq9k1nG38XdV4fkeerM:b-mckscf)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(priority: low) +(priority: medium)  @ggould-tri the next PR (#20851) in queue is waiting on this one.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-:-NqTEW8OBTC8amUiAlh6:b-wvlxpy)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Comment by ggould-tri** [comment]
Sorry about the delay:  Anzu took my priorities.  Getting back to this now.

**Review by ggould-tri — COMMENTED** [review]
Oh, this is much nice.  Thank you.  :lgtm_strong: 

> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-:-NqU6u204nk-Eyhp4la8:b-9a2wjt)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`geometry/proximity/polygon_surface_mesh.cc` line 216 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NqU5zVD-WQJ-GwCCEM1:-NqU5zVD-WQJ-GwCCEM2:b-d2zl0i) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f555da432e3da0b9d0889da48d43c1071ee1043/geometry/proximity/polygon_surface_mesh.cc#L216)):*
> ```cpp
>     throw std::runtime_error(
>         fmt::format("SetAllPositions(): Attempting to deform a mesh with {} "
>                     "vertices with data for {} vertices",
> ```

nit:  This will be confusing, since AIUI the second number isn't a vertex count.



_Suggestion:_
```cpp
{} DoFs
```
___
*[`geometry/proximity/triangle_surface_mesh.cc` line 14 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NqU6f77AFCM2TbGqLAb:-NqU6f77AFCM2TbGqLAc:bcslyyh) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f555da432e3da0b9d0889da48d43c1071ee1043/geometry/proximity/triangle_surface_mesh.cc#L14)):*
> ```cpp
>     throw std::runtime_error(
>         fmt::format("SetAllPositions(): Attempting to deform a mesh with {} "
>                     "vertices with data for {} vertices",
> ```

nit:  As above.



_Suggestion:_
```cpp
{} DoFs
```
___
*[`geometry/proximity/volume_mesh.cc` line 23 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NqU6kGz2hAy4Xg8vBUu:-NqU6kH-7sSE22lZWRnM:bcslyyh) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f555da432e3da0b9d0889da48d43c1071ee1043/geometry/proximity/volume_mesh.cc#L23)):*
> ```cpp
>     throw std::runtime_error(
>         fmt::format("SetAllPositions(): Attempting to deform a mesh with {} "
>                     "vertices with data for {} vertices",
> ```

nit:  As above.



_Suggestion:_
```cpp
{} DoFs
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/proximity/polygon_surface_mesh.cc` line 216 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NqU5zVD-WQJ-GwCCEM1:-NqUAGGD8V0TLafTVsu6:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f555da432e3da0b9d0889da48d43c1071ee1043/geometry/proximity/polygon_surface_mesh.cc#L216)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  This will be confusing, since AIUI the second number isn't a vertex count.
</blockquote></details>

Done
___
*[`geometry/proximity/triangle_surface_mesh.cc` line 14 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NqU6f77AFCM2TbGqLAb:-NqUACejEDZiLwISuAHs:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f555da432e3da0b9d0889da48d43c1071ee1043/geometry/proximity/triangle_surface_mesh.cc#L14)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  As above.
</blockquote></details>

Done
___
*[`geometry/proximity/volume_mesh.cc` line 23 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20852#-NqU6kGz2hAy4Xg8vBUu:-NqUA9Pm3pKzCX2NUdYn:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f555da432e3da0b9d0889da48d43c1071ee1043/geometry/proximity/volume_mesh.cc#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  As above.
</blockquote></details>

Done

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20852)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
