### PR TITLE
[multibody] Remove unused MbP includes

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19212)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) +@jwnimmer-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19212#-:-NTF8Yz7E3yn2BTVBnHD:b2o169r)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19212)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19212#-NTFAYmN8IjaZ4Xsya0Z:-NTFAYmN8IjaZ4Xsya0_:b-3wgfxz) (no related file):*
We also have this which makes the change a no-op in terms of compile times:

```
./multibody_plant.h:27:#include "drake/multibody/plant/discrete_update_manager.h"
./discrete_update_manager.h:13:#include "drake/multibody/contact_solvers/contact_solver.h"
```

I could badge this as a readability improvement, but do you want to try to make further repairs here instead?

Here's a way to test locally:

```patch
--- a/multibody/contact_solvers/contact_solver.h
+++ b/multibody/contact_solvers/contact_solver.h
@@ -12,6 +12,8 @@
 #include "drake/multibody/contact_solvers/point_contact_data.h"
 #include "drake/multibody/contact_solvers/system_dynamics_data.h"
 
+#define NEEDLE 1
+
 namespace drake {
 namespace multibody {
 namespace contact_solvers {
--- a/multibody/plant/test/multibody_plant_config_functions_test.cc
+++ b/multibody/plant/test/multibody_plant_config_functions_test.cc
@@ -5,6 +5,10 @@
 #include "drake/common/test_utilities/expect_throws_message.h"
 #include "drake/common/yaml/yaml_io.h"
 
+#ifdef NEEDLE
+#error WHEE
+#endif
+
 namespace drake {
 namespace multibody {
 namespace internal {
```

___

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19212)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19212#-NTFAYmN8IjaZ4Xsya0Z:-NTFQb_c9cUQP4lCXOMN:be7ak5v) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We also have this which makes the change a no-op in terms of compile times:

```
./multibody_plant.h:27:#include "drake/multibody/plant/discrete_update_manager.h"
./discrete_update_manager.h:13:#include "drake/multibody/contact_solvers/contact_solver.h"
```

I could badge this as a readability improvement, but do you want to try to make further repairs here instead?

Here's a way to test locally:

```patch
--- a/multibody/contact_solvers/contact_solver.h
+++ b/multibody/contact_solvers/contact_solver.h
@@ -12,6 +12,8 @@
 #include "drake/multibody/contact_solvers/point_contact_data.h"
 #include "drake/multibody/contact_solvers/system_dynamics_data.h"
 
+#define NEEDLE 1
+
 namespace drake {
 namespace multibody {
 namespace contact_solvers {
--- a/multibody/plant/test/multibody_plant_config_functions_test.cc
+++ b/multibody/plant/test/multibody_plant_config_functions_test.cc
@@ -5,6 +5,10 @@
 #include "drake/common/test_utilities/expect_throws_message.h"
 #include "drake/common/yaml/yaml_io.h"
 
+#ifdef NEEDLE
+#error WHEE
+#endif
+
 namespace drake {
 namespace multibody {
 namespace internal {
```
</blockquote></details>

Working, thanks for the testing patch.

___

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19212)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19212#-NTFAYmN8IjaZ4Xsya0Z:-NTFW6cw6DH1H02HE9L8:b-ctbv29) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working, thanks for the testing patch.
</blockquote></details>

Done. BTW we should also consider removing the entire contact_solver.h/.cc and related files as no non-internal code depend on them anymore. cc @amcastro-tri 

___

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19212#-:-NTFucGo2pAHf2oHF4sK:b-85g6de)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19212#-NTFAYmN8IjaZ4Xsya0Z:-NTFupVZ7tUEfsOqXoLA:b-v6ymzu) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done. BTW we should also consider removing the entire contact_solver.h/.cc and related files as no non-internal code depend on them anymore. cc @amcastro-tri 
</blockquote></details>

What might make most sense is to use `internal = True` on every library in contact_solvers, if in fact they are all cc-file-internal only.

___

**Pull request merged**
