### PR TITLE
pydrake: Do not import a duplicate of pydrake, but use another moduleto load `libdrake.so`

### LINKED ISSUE #8810: Downstream `pydrake` consumption: Error "type "RandomDistribution" is already registered!"
Since we now have a type registered in `_common_py` (as of #8806), there is a collision with downstream projects when leveraging #8240, where the `typeid` for `RandomDistribution` has already been seen globally.

The quickest solution would be to move this registration to another module; a better long-term solution would be to make #8240 work without importing an additional copy of `pydrake`, perhaps by directly loading `libdrake.so`.

This will affect anyone who pulls the latest version of Drake master for their projects.

\cc @naveenoid @thduynguyen @avalenzu

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8810

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for both review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811#-:-LCUji4U7-iMmPUmuv2B:b-dn0wyl)*

**Comment by jwnimmer-tri** [comment]
*[bindings/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUkjH820yp3t3Ptusl:-LCUkjH820yp3t3Ptusm:b-3x49mv) ([raw file](https://github.com/robotlocomotion/drake/blob/c997f4165c935f767c40233243bb79ecd18d258c/bindings/BUILD.bazel#L1)):*
> ```Python
> # -*- python -*-
> ```

Unclear why this content lives in `//bindings` vs `//bindings/pydrake/...`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUkjH820yp3t3Ptusl:-LCUkydB2xPMeqDyE2tB:bp7c621) ([raw file](https://github.com/robotlocomotion/drake/blob/c997f4165c935f767c40233243bb79ecd18d258c/bindings/BUILD.bazel#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this content lives in `//bindings` vs `//bindings/pydrake/...`.
</blockquote></details>

OK Because if we place it in`//bindings/pydrake`, then it will still load `pydrake/__init__.py` and re-load the same symbols.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by jwnimmer-tri** [comment]
*[bindings/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUkjH820yp3t3Ptusl:-LCUl9rP0V7rURiLRCmW:b-5be0jo) ([raw file](https://github.com/robotlocomotion/drake/blob/c997f4165c935f767c40233243bb79ecd18d258c/bindings/BUILD.bazel#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Because if we place it in`//bindings/pydrake`, then it will still load `pydrake/__init__.py` and re-load the same symbols.
</blockquote></details>

Don't tell me.  Tell the next reader of this code, with a comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by jwnimmer-tri** [comment]
*[bindings/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUkjH820yp3t3Ptusl:-LCUlEI57HEqP_ToJPdL:b-7ymyt6) ([raw file](https://github.com/robotlocomotion/drake/blob/c997f4165c935f767c40233243bb79ecd18d258c/bindings/BUILD.bazel#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Don't tell me.  Tell the next reader of this code, with a comment.
</blockquote></details>

Ah... which is down below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@sammy-tri for platform review, please.

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUmGWi7XPgeD7eOMpu:-LCUmGWi7XPgeD7eOMpv:bktqirh) (no related file):*
I am going to test locally.

---

*[tools/skylark/pybind.bzl, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUl4VcBrAF4Z_P2awO:-LCUl4VcBrAF4Z_P2awP:b99si55) ([raw file](https://github.com/robotlocomotion/drake/blob/c997f4165c935f767c40233243bb79ecd18d258c/tools/skylark/pybind.bzl#L177)):*
> ```Python
> 
> def get_bazel_workaround_4549_libdrake_package_info():
>     """Only to be used by //bindings:bazel_workaround_4594_libdrake_py."""
> ```

Unclear why a helper called from one place, and only to be used by that one place, is defined in a shared location.  I see that is must be in a bzl file, but it seems like the bzl file could live in `//bindings` without a problem?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811#-:-LCUmERa9QpMRKPb77Gx:b-3v5mxt)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/pybind.bzl, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUl4VcBrAF4Z_P2awO:-LCUnM23BnTEOW1ZCEQv:b35wj23) ([raw file](https://github.com/robotlocomotion/drake/blob/c997f4165c935f767c40233243bb79ecd18d258c/tools/skylark/pybind.bzl#L177)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why a helper called from one place, and only to be used by that one place, is defined in a shared location.  I see that is must be in a bzl file, but it seems like the bzl file could live in `//bindings` without a problem?
</blockquote></details>

Done. Good point!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/BUILD.bazel, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUnObj5zKBZRpUxDGV:-LCUnObj5zKBZRpUxDGW:b4v1ggk) ([raw file](https://github.com/robotlocomotion/drake/blob/d240416e6482148d4cfdc0e2406065af00257e98/bindings/BUILD.bazel#L8)):*
> ```Python
>     "drake_pybind_library",
> )
> load(":bazel_workaround_4594_libdrake.bzl",
> ```

BTW newline

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/BUILD.bazel, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUnObj5zKBZRpUxDGV:-LCUnoaqAHuqmNpJm6ZG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d240416e6482148d4cfdc0e2406065af00257e98/bindings/BUILD.bazel#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCUmGWi7XPgeD7eOMpu:-LCUpZhSDZwHBOJ3YzV6:bfqh7t6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am going to test locally.
</blockquote></details>

For downstreams that do `import external.drake.bindings.pydrake as pydrake`, this PR doesn't solve the issue, but I guess the solution there is just "don't do that".  We will have to fix Anzu to use the shorter imports.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/bazel_workaround_4594_libdrake.bzl, line 3 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCVDzH_3OacOrk2iK47:-LCVDzH_3OacOrk2iK48:b-qz6y5g) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9384d8f8e6a28739223ff553d6b1be80bf709c/bindings/bazel_workaround_4594_libdrake.bzl#L3)):*
> ```Python
> # -*- python -*-
> 
> def get_bazel_workaround_4549_libdrake_package_info():
> ```

The issue number (presumably?) in the function name doesn't match the filename.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/bazel_workaround_4594_libdrake.bzl, line 3 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8811#-LCVDzH_3OacOrk2iK47:-LCVVA3NCaookaKqdTjF:b-r08yfo) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9384d8f8e6a28739223ff553d6b1be80bf709c/bindings/bazel_workaround_4594_libdrake.bzl#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The issue number (presumably?) in the function name doesn't match the filename.
</blockquote></details>

Done. D'oh!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8811#-:-LCZFbD66K9Z0_KXdgbS:bnfp4nl)*

**Pull request merged**
