### PR TITLE
pydrake: Add bindings for BsplineTrajectory and BsplineBasis

### LINKED ISSUE #14132: Add bindings for Bspline{Basis,Trajectory}

### PR DESCRIPTION
**Pull request by mpetersen94**
Closes #14132

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14201)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@avalenzu for feature review

**Review by avalenzu — COMMENTED** [review]
Awesome! Thanks, Mark! Review pass done.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14201#-:-MJXJYxW3ksgM8Dd0Fa6:bd9j07z)* status: 3 unresolved discussions, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mpetersen94)

___
*[bindings/pydrake/math_py.cc, line 487 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXHTUh-2ndJaDiDUnI:-MJXHTUh-2ndJaDiDUnJ:b-d59w29) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/math_py.cc#L487)):*
> ```cpp
>   py::module::import("pydrake.symbolic");
> 
>   DoScalarIndependentDefinitions(m);
> ```

Why did this need to move?
___
*[bindings/pydrake/trajectories_py.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXHZZp1Ucdyf73tLTk:-MJXHZZqBF6V1gWtapJQ:bjxgejh) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/trajectories_py.cc#L22)):*
> ```cpp
>   using namespace drake::trajectories;
>   constexpr auto& doc = pydrake_doc.drake.trajectories;
>   // py::module::import("pydrake.math");
> ```

nit: Remove commented code.
___
*[bindings/pydrake/trajectories_py.cc, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXIXWEBElrlvQkp7DB:-MJXIXWEBElrlvQkp7DC:b4tmsds) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/trajectories_py.cc#L57)):*
> ```cpp
>           doc.BsplineTrajectory.start_time.doc)
>       .def("end_time", &BsplineTrajectory<T>::end_time,
>           doc.BsplineTrajectory.end_time.doc)
> ```

I don't think you should need to bind `value`, `rows`, `cols`, `start_time`, or `end_time`. The `Trajectory` bindings should work in this case.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14201)* status: 2 unresolved discussions, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

___
*[bindings/pydrake/math_py.cc, line 487 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXHTUh-2ndJaDiDUnI:-MJXTQFG-KA-IMFdbuA3:b-ty4ukp) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/math_py.cc#L487)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Why did this need to move?
</blockquote></details>

The binding of `KnotVectorType` (which is scalar independent) had to come before the binding of the `BsplineBasis` constructor (which is scalar dependent) that has a default `KnotVectorType`.  If I maintain the old order the build crashes.
___
*[bindings/pydrake/trajectories_py.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXHZZp1Ucdyf73tLTk:-MJXUYrD2waEUZnPgajg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/trajectories_py.cc#L22)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Remove commented code.
</blockquote></details>

Done.
___
*[bindings/pydrake/trajectories_py.cc, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXIXWEBElrlvQkp7DB:-MJXTvjxCvusqI8ev9cw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/trajectories_py.cc#L57)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I don't think you should need to bind `value`, `rows`, `cols`, `start_time`, or `end_time`. The `Trajectory` bindings should work in this case.
</blockquote></details>

Done.

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@sherm1 for platform review.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14201#-:-MJYNjBF8t2oNQ9GYJ1D:bol08qe)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[bindings/pydrake/math_py.cc, line 487 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14201#-MJXHTUh-2ndJaDiDUnI:-MJYN_fh2UPuhHeHdf0K:b-jhyyta) ([raw file](https://github.com/robotlocomotion/drake/blob/7125e3802e2e7a5540179032000e309204b04d84/bindings/pydrake/math_py.cc#L487)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

The binding of `KnotVectorType` (which is scalar independent) had to come before the binding of the `BsplineBasis` constructor (which is scalar dependent) that has a default `KnotVectorType`.  If I maintain the old order the build crashes.
</blockquote></details>

Got it. Thanks!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14201#-:-MJYZkpW-t1SY2GFBVot:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14201)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,sherm1(platform)

**Pull request merged**
