### PR TITLE
A more fluent construction API for SpatialVector

### PR DESCRIPTION
**Pull request by amcastro-tri**
Per Slack discussion in the "#dynamics" channel, this PR introduces a construction API that allows saying:
```c++
SV{}.with_rotational(angular_velocity).with_translational(linear_velocity);
```
which explicitly sates the rotational and translational components.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6431)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for feature review please. Sorry for the delay on your request. Hopefully this helps?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-:-KnaGg89GTDEfabMa2Im:b-uspi02)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-KnaLuMHF9ypxzeRs33m:-KnaLuMHF9ypxzeRs33n:bt6m7q0) ([raw file](https://github.com/robotlocomotion/drake/blob/e44badd8a292f73b19a46e81b80660e72b65165a/drake/multibody/multibody_tree/math/spatial_vector.h#L71)):*
> ```objc
> 
>   /// Creates a copy of `this` spatial vector with its rotational component set
>   /// to `v`.
> ```

In the constructor, the rotational component is named `w`; why use `v` here?

(Or even consider writing out the full variable name `with_rotational(const Eigen::Ref<...>& rotational) const ...`.)

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-KnaLj0uZquyMlxMBINb:-KnaLj0uZquyMlxMBINc:b2gghfo) ([raw file](https://github.com/robotlocomotion/drake/blob/e44badd8a292f73b19a46e81b80660e72b65165a/drake/multibody/multibody_tree/math/spatial_vector.h#L77)):*
> ```objc
>     V.rotational() = v;
>     return V;
>   }
> ```

So we have variables `V`, `V_`, and `v` all in scope at once?  That's insane.

(Ditto below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-:-KnaMoJkRWvzXZo6VG3X:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Thanks @jwnimmer-tri. +@sherm1 for platform please.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-KnaLuMHF9ypxzeRs33m:-KnaQcJ2k55J2riSvmVv:b-bvi5m9) ([raw file](https://github.com/robotlocomotion/drake/blob/e44badd8a292f73b19a46e81b80660e72b65165a/drake/multibody/multibody_tree/math/spatial_vector.h#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In the constructor, the rotational component is named `w`; why use `v` here?

(Or even consider writing out the full variable name `with_rotational(const Eigen::Ref<...>& rotational) const ...`.)
</blockquote></details>

Fair enough. I renamed as suggested.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-KnaLj0uZquyMlxMBINb:-KnaQggsQ8pm7K9oG2ED:bq4xjq1) ([raw file](https://github.com/robotlocomotion/drake/blob/e44badd8a292f73b19a46e81b80660e72b65165a/drake/multibody/multibody_tree/math/spatial_vector.h#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So we have variables `V`, `V_`, and `v` all in scope at once?  That's insane.

(Ditto below.)
</blockquote></details>

Variables were renamed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-:-KnaPbFOp9w3kpTd0gB2:brmqso0)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by sherm1** [comment]
As written I don't think these methods can be used as intended -- see comments below.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 74 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7ZnAdaxDk_mvPxxh:-Knb7ZnAdaxDk_mvPxxi:b-ffb07i) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L74)):*
> ```objc
>   SpatialQuantity with_rotational(
>       const Eigen::Ref<const Vector3<T>>& rotational) const {
>     SpatialQuantity V_with_rotational(get_derived());
> ```

This line is copying uninitialized garbage (likely to trigger valgrind complaints) so should not be used for initialization as written.

You could modify these to work in-place rather than copying; in that case they could be used for initialization.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7uEb2xro45SzXZLC:-Knb7uEb2xro45SzXZLD:bnyfwmg) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L83)):*
> ```objc
>   SpatialQuantity with_translational(
>       const Eigen::Ref<const Vector3<T>>& translational) const {
>     SpatialQuantity V_with_translational(get_derived());
> ```

Same comment here.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 193 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7RBgf8QzXmGGZIpu:-Knb7RBgf8QzXmGGZIpv:brldx3l) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L193)):*
> ```objc
>   }
> 
>   CoeffsEigenType V_;
> ```

BTW this is uninitialized on purpose in Eigen (see comment above).

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-Knb61v-eLBLpMQhwP0U:by31dcl) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
> ```cpp
>   // A spatial quantity based off the above 3D vectors.
>   const SpatialQuantity V =
>       SpatialQuantity{}.with_rotational(w).with_translational(v);
> ```

I *think* the underlying Eigen default constructor leaves spatial quantities intentionally uninitialized. If that's correct, then the copies of `this` done in with_rotational() and with_translational() will be copying uninitialized memory prior to setting part of it. That is technically allowed, but valgrind will not like it (for generally good reason -- copying garbage is usually a mistake).

Either the spatial quantities must be initialized (likely a bad idea in Release builds for the same reason that Eigen doesn't do it), or these routines should be modified to work in place so they don't have to copy garbage around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-:-Knb7xhuRFdO6sX66Xjw:b-1h8b6d)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/multibody_tree/math/spatial_vector.h, line 74 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7ZnAdaxDk_mvPxxh:-Knb8mnv2OW2lndmsNnM:b8a7bfc) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L74)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This line is copying uninitialized garbage (likely to trigger valgrind complaints) so should not be used for initialization as written.

You could modify these to work in-place rather than copying; in that case they could be used for initialization.
</blockquote></details>

`get_derived()` is mostly just `*this`; so if `this` contains non-garbage, then `V_with_rotational` will be non-garbage, and even after an update of the `rotational()` elements, it's still non-garbage.

So I'm not sure how this method is defective?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-Knb9FADyMPWpcWJIzte:b7452qu) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I *think* the underlying Eigen default constructor leaves spatial quantities intentionally uninitialized. If that's correct, then the copies of `this` done in with_rotational() and with_translational() will be copying uninitialized memory prior to setting part of it. That is technically allowed, but valgrind will not like it (for generally good reason -- copying garbage is usually a mistake).

Either the spatial quantities must be initialized (likely a bad idea in Release builds for the same reason that Eigen doesn't do it), or these routines should be modified to work in place so they don't have to copy garbage around.
</blockquote></details>

Valgrind does not complain about copying garbage, only about computing with garbage.  It tracks the "uninitialized" condition through copies, and only objects when you compute using it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by jwnimmer-tri** [comment]
(Sorry for the multiple posts, struggling with reviewable on the train tonight.)

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 193 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7RBgf8QzXmGGZIpu:-Knb9aXHpBbfl2jtlrCQ:b-97jbpv) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L193)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is uninitialized on purpose in Eigen (see comment above).
</blockquote></details>

If this is garbage on purpose, then the code needs a comment about why its violating the code_style_guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-:-Knb9joPQ5SOiTfIS7FE:b-xzk515)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-KnbF5n5462-BjCa6_SD:bco6c9) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Valgrind does not complain about copying garbage, only about computing with garbage.  It tracks the "uninitialized" condition through copies, and only objects when you compute using it.
</blockquote></details>

And for the record: the entire purpose of this PR is to _not mutate `this`_, so "work in place" is a non-starter. 

_If_ the uninitialized values are a problem (they are not), then the solution is either to make the default constructor initialize to `NAN` always, or else to change this test to do `SpatialQuantity::make_nan().with_rotational(w).with_translational(v);` instead (adding a NAN factory method).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by sherm1** [comment]
I proposed a small mod below that avoids the copies and still achieves the goals here, assuming I understand them correctly - ptal.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 74 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7ZnAdaxDk_mvPxxh:-Knbpb4YMO7zT3TyZzka:bxiowrl) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`get_derived()` is mostly just `*this`; so if `this` contains non-garbage, then `V_with_rotational` will be non-garbage, and even after an update of the `rotational()` elements, it's still non-garbage.

So I'm not sure how this method is defective?
</blockquote></details>

Why not make these methods like assignments instead:
```c++
SpatialQuantity& set_rotational(
      const Eigen::Ref<const Vector3<T>>& rotational) {
  V_.head<3>() = rotational;
  return *this;
}
```
That still permits chaining like
```c++
SpatialVelocity V_AB = SpatialVelocity().set_rotational(w).set_translational(v);
// or
SpatialVelocity V_AB;
V_AB.set_rotational(w).set_translational(v);
```
but never reads uninitialized memory.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 193 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7RBgf8QzXmGGZIpu:-KnbsLWIiK3thxfj7DzF:bwmjcyw) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L193)):*
BTW it is not violating our style guide. The member initialization rule applies only to built-in types, and our style guide [Additional Rules](http://drake.mit.edu/code_style_guide.html#id20) section contains this quote:
> Note that fixed-size Eigen objects are intentionally left uninitialized; if you want yours zero-initialized you can member-initialize it by passing an appropriate Zero, for example: Eigen::Matrix3d mat_{Eigen::Matrix3d::Zero()};. 

It does seem like a good idea to mention that here though, but I don't think it has to be done every time we use an Eigen data structure.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-KnbtHSNLA4VUSk3zrNs:bf1dm4l) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
> the entire purpose of this PR is to not mutate this

I thought the purpose of this PR was to clarify which of two vectors was a rotation and which a translation? That would seem orthogonal to mutation of `this`. Making these assignment-like `set` methods would permit the original code to work here:
```c++
const SpatialQuantity V =
      SpatialQuantity{}.set_rotational(w).set_translational(v);
```
with no copying at all and no reference to uninitialized memory.

Whether valgrind actually complains or not, wouldn't the above be an improvement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-:-KnbuYg1bSZ2QjdQKFkA:b-ra9qgf)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 193 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb7RBgf8QzXmGGZIpu:-KndEykN_hz618kao5Bb:b-trg84e) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/spatial_vector.h#L193)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it is not violating our style guide. The member initialization rule applies only to built-in types, and our style guide [Additional Rules](http://drake.mit.edu/code_style_guide.html#id20) section contains this quote:
> Note that fixed-size Eigen objects are intentionally left uninitialized; if you want yours zero-initialized you can member-initialize it by passing an appropriate Zero, for example: Eigen::Matrix3d mat_{Eigen::Matrix3d::Zero()};. 

It does seem like a good idea to mention that here though, but I don't think it has to be done every time we use an Eigen data structure.
</blockquote></details>

Oops, I mis-remembered the rule.  Withdrawn.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-KndF6jmQWkQbhB5nPVk:brzxfxf) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

> the entire purpose of this PR is to not mutate this

I thought the purpose of this PR was to clarify which of two vectors was a rotation and which a translation? That would seem orthogonal to mutation of `this`. Making these assignment-like `set` methods would permit the original code to work here:
```c++
const SpatialQuantity V =
      SpatialQuantity{}.set_rotational(w).set_translational(v);
```
with no copying at all and no reference to uninitialized memory.

Whether valgrind actually complains or not, wouldn't the above be an improvement?
</blockquote></details>

I don't think so, no.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-KnefCDGtmCCVb83aSzV:bay9z24) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think so, no.
</blockquote></details>

I realize now that it seems like copying garbage is a bad thing even if Valgrind doesn't complain. @jwnimmer-tri, why is it that you don't like the `set_rotational()`/`set_translational()`  approach?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-KnefkzdoLHWpGClrKEX:bxfpacx) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I realize now that it seems like copying garbage is a bad thing even if Valgrind doesn't complain. @jwnimmer-tri, why is it that you don't like the `set_rotational()`/`set_translational()`  approach?
</blockquote></details>

Setters should not return `this`; it is confusing and can (rarely) lead to lifetime issues.  And you already have "setters" in the `.translational()` accessor anyway, so might as well just `foo.translational() = bar;` at that point.

And really guys, if garbage makes you uncomfortable, then initialize the member field.  I bet you $1000 you will never notice in any benchmark that matters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6431#-Knb61v-eLBLpMQhwP0T:-KnenzqXS_ejKn3bxxYf:b-z5vifd) ([raw file](https://github.com/robotlocomotion/drake/blob/5753214fd1e14cbd171a5e1e162f69beb06be2f6/drake/multibody/multibody_tree/math/test/spatial_algebra_tests.cc#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Setters should not return `this`; it is confusing and can (rarely) lead to lifetime issues.  And you already have "setters" in the `.translational()` accessor anyway, so might as well just `foo.translational() = bar;` at that point.

And really guys, if garbage makes you uncomfortable, then initialize the member field.  I bet you $1000 you will never notice in any benchmark that matters.
</blockquote></details>

Chained assignment is practically a sacrament in C++, sanctified in the definition of its assignment operators, io system "<<" operators, and countless named methods such as std::string's [`assign()`](http://en.cppreference.com/w/cpp/string/basic_string/assign) methods. Inline setters that return `*this` are conventional and harmless - if the return value isn't used it evaporates. Maybe use `assign_rotational()` here like std::string if that's less confusing?

I don't want to re-litigate the initialization of linear algebra data structures in Release builds -- best practice in the numerical linear algebra field as reflected in Eigen says don't do it.

In any case I've expressed my concerns with the code here and suggested an alternative, I'll leave this to the author to sort out. Marking myself satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6431)*

**Comment by jwnimmer-tri** [comment]
For what its worth Alejandro, this enhancement is not pressing for me at all.  My slack question related to it came up in the context of a throw-away demo, and I'm not going to be using multibody code anytime soon.  Might be worth finishing off the features and then subsequently taking requests for more sugar as a whole, done with a global view to the APIs.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri No reason to keep this in my dashboard for >2 weeks with no movement.  Feel free to reassign back to me if you need more discussion.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
@amcastro-tri If this PR isn't going be worked, please consider closing it until it becomes active again.

**Pull request closed without merging**
