### PR TITLE
Make Gurobi retry downloading license

### LINKED ISSUE #8563: Add lock and retry logic to license acquisition in GurobiSolver
Since it is common for the license to be obtained from a license server over a network, it is perfectly possible that license acquisition will fail on occasion.

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Closes #8563

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9126)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug please 
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-everything  please 
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please

**Comment by m-chaturvedi** [comment]
+@jwnimmer-tri for feature review, please.

**Comment by jamiesnape** [comment]
Note once this is merged we should remove ` --flaky_test_attempts=3` from [driver/configurations/bazel.cmake in drake-ci](https://github.com/RobotLocomotion/drake-ci/blob/52fc42b38efca58a63ccd335222860aebb2f3b91/driver/configurations/bazel.cmake#L103-L106).

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.h, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYOl_C5rXnDmzTkfOg:-LHi6mdP4OY2Qbm9vg7T:busyj2h) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.h#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Awesome.
</blockquote></details>

Added to `AcquireLicense()` to`no_gurobi.cc`

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 623 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYO31aBmjw-2rMcckF:-LHi6uECBBizhdPRdixc:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L623)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This whitespace initially confused me.  This initialization is part of the loop, but this whitespace makes it seem like a separate operation.
</blockquote></details>

Removed.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 633 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYOLBZ1RRL5jpY_UlY:-LHi7-Ak8QgaRZF9i7hI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L633)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was willing to tolerate spelling out the `GRBloadenv` call twice, but formatting the log message twice is just too brittle.  Please find a way to write this as a single loop, where `GRBloadenv` and `log()->info` each only appear once.  (I think its fine if the log doesn't say "retrying", though a single log statement could be customized to vary as much, if needed.)
</blockquote></details>

Done.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 644 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYQ3NAEcTrhc9gJom5:-LHi722a7xeqS-0WP6qu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L644)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

http://drake.mit.edu/styleguide/cppguide.html#Function_Names
</blockquote></details>

Done.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 666 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYNl2j9uYJntGmOIeY:-LHi777ZAz3yB4GmvjPX:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L666)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The above block seems redundant with the AcquireLicense call that immediately follows.
</blockquote></details>

Removed.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 671 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYPP1j87c4vdQKenrX:-LHi7C4o4nn5qWC1rHTf:b-deoj94) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L671)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

Added the test.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 650 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYOB3XEzv43-xpSx6E:-LHi7a-K5-R4tnlvBoSb:bwhglds) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L650)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yup, so just kNumRetries (or similar) seems wanted here now.
</blockquote></details>

Moved.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHYMzsu1lb1Bun3mtWG:-LHi7lqt1rBzYnCVHtOf:b-gk1pbx) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.h#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since a public method returns an instance of this type, we need API docs here.  The `MosekSolver::License` is a fine example.
</blockquote></details>

Added the comment.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 628 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHi87py7mJ1X3tygl0H:-LHiDGozBm_CnH2SZ6MI:bqsnq5r) ([raw file](https://github.com/robotlocomotion/drake/blob/b7992b624a09bd56c776fd1cfc3e4d5f587e224c/solvers/gurobi_solver.cc#L628)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

TBD Are we sure that, after failing to initialize `env_`, we can still pass it to `GRBgeterrormsg`?  Isn't the env invalid at this point, sill?
</blockquote></details>

It certainly seems that way to me: http://www.gurobi.com/documentation/8.0/refman/c_grbgeterrormsg.html
If we look at `gurobi800/linux64/examples/c/sudoku_c.c:198` we can see that that is how they are using it.
```
  error = GRBloadenv(&env, "sudoku.log");
  if (error) goto QUIT;
```
```
QUIT:

  /* Error reporting */

  if (error) {
    printf("ERROR: %s\n", GRBgeterrormsg(env));
    exit(1);
  }
```

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 627 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHi8-WrCV21zMR1rU1S:-LHiINwTCagofg4coHPa:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/b7992b624a09bd56c776fd1cfc3e4d5f587e224c/solvers/gurobi_solver.cc#L627)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Log statements should not add their own trailing newline; the framework does that already.
</blockquote></details>

Removed.

**Comment by m-chaturvedi** [comment]
___
*[solvers/test/gurobi_solver_test.cc, line 238 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHi9Iy06tYXNKt9XVS0:-LHiIXQtCpprTASHUEy-:bsj646i) ([raw file](https://github.com/robotlocomotion/drake/blob/b7992b624a09bd56c776fd1cfc3e4d5f587e224c/solvers/test/gurobi_solver_test.cc#L238)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Grammar `are share`
</blockquote></details>

Corrected.

**Comment by m-chaturvedi** [comment]
___
*[solvers/test/gurobi_solver_test.cc, line 244 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHi8WkV7eQCNYjuxa6T:-LHiIZaR4jPJSM1VeO2j:bsj646i) ([raw file](https://github.com/robotlocomotion/drake/blob/b7992b624a09bd56c776fd1cfc3e4d5f587e224c/solvers/test/gurobi_solver_test.cc#L244)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing punctuation for end of sentence.
</blockquote></details>

Corrected.

**Comment by m-chaturvedi** [comment]
___
*[solvers/test/gurobi_solver_test.cc, line 253 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHi8hfm2kW9PyWyKcQc:-LHiIawg1HGC4JngN1Ug:bu8u0a8) ([raw file](https://github.com/robotlocomotion/drake/blob/b7992b624a09bd56c776fd1cfc3e4d5f587e224c/solvers/test/gurobi_solver_test.cc#L253)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`auto` is too obscuring of the return type.
</blockquote></details>

Changed to `SolutionResult`.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 651 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHZ23NeBbdXaINY6A5N:-LHiOptd-5PYZPPgZg9V:b1n6kiz) ([raw file](https://github.com/robotlocomotion/drake/blob/84b4b8c5ee38446256e182261c013309a3c85fb3/solvers/gurobi_solver.cc#L651)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> I just mean that mosek_solver and gurobi_solver should be consistent.

I agree (and I would be inclined to make it `kNumRetries` in both per the other discussion).
</blockquote></details>

https://github.com/RobotLocomotion/drake/issues/9149

**Comment by m-chaturvedi** [comment]
___
*[solvers/test/gurobi_solver_test.cc, line 260 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHi8o2h5iIRUyJgXCu7:-LHijW4R48UmMtkk_9A7:bt80axk) ([raw file](https://github.com/robotlocomotion/drake/blob/b7992b624a09bd56c776fd1cfc3e4d5f587e224c/solvers/test/gurobi_solver_test.cc#L260)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I just changed the test in my branch https://github.com/hongkai-dai/drake/tree/gurobi_retry. Now the test takes longer time.
</blockquote></details>

I reset my branch's `HEAD` to point to your branch's.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

**Comment by m-chaturvedi** [comment]
___
*[solvers/gurobi_solver.cc, line 627 at r6](https://reviewable.io/reviews/robotlocomotion/drake/9126#-LHo07vOC8jA5C4Z82Dt:-LHoJi6K60q72U8kg2TG:bczdmg9) ([raw file](https://github.com/robotlocomotion/drake/blob/e77ed0e2b8a966a451eb85b8361db3f9617b3f3e/solvers/gurobi_solver.cc#L627)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> If we fail after all reties, then we should just have a single (total) diagnostic saying so.

That message is basically there just below this as  "Could not create Gurobi environment.". Making that more specific would seem like the best bet.
</blockquote></details>

I changed the runtime error message and removed the logs written on retries.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai we just need your LGTM.

**Pull request merged**
