### PR TITLE
Modified SDF parser method names to be style guide compliant and more meaningful

### PR DESCRIPTION
**Pull request by liangfok**
I also fixed some Doxygen bugs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3115)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this touches `RigidBody*`, which I believe can now be declared officially "owned" by the dynamics team:

+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-:-KOtTl3VaYpFKUgvv7uf:bt23kr3)*

**Comment by amcastro-tri** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 131 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-KOtq3xcLO-o0dyHH9sh:-KOtq3xcLO-o0dyHH9si:bwik7om) ([raw file](https://github.com/robotlocomotion/drake/blob/097d2ec929ac5fb4018cae212d7193d6740b5bb6/CHANGELOG.md#L131)):*
> ```Markdown
> [#3056]: https://github.com/RobotLocomotion/drake/issues/3056
> [#3078]: https://github.com/RobotLocomotion/drake/issues/3078
> [#3115]: https://github.com/RobotLocomotion/drake/issues/3115
> ```

missing end of line?

---

*[drake/systems/plants/parser_sdf.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-KOtp99jnZJJhgiiNolk:-KOtp99jnZJJhgiiNoll:b-mckboa) ([raw file](https://github.com/robotlocomotion/drake/blob/097d2ec929ac5fb4018cae212d7193d6740b5bb6/drake/systems/plants/parser_sdf.h#L18)):*
> ```objc
> 
> /**
>  * Adds the model or models defined within an SDF file to a rigid body system.
> ```

"... to a rigid body tree."

---

*[drake/systems/plants/parser_sdf.h, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-KOtpKwrtUMuVvnbRZN0:-KOtpKwrtUMuVvnbRZN1:b-mckboa) ([raw file](https://github.com/robotlocomotion/drake/blob/097d2ec929ac5fb4018cae212d7193d6740b5bb6/drake/systems/plants/parser_sdf.h#L43)):*
> ```objc
> 
> /**
>  * Adds the model or models defined within an SDF file to a rigid body system.
> ```

"... to a rigid body tree."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 131 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-KOtq3xcLO-o0dyHH9sh:-KOtsGqbiadC0T5mFmUt:b-d5q2ho) ([raw file](https://github.com/robotlocomotion/drake/blob/097d2ec929ac5fb4018cae212d7193d6740b5bb6/CHANGELOG.md#L131)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> missing end of line?
</details>
Fixed. Thanks.

---

*[drake/systems/plants/parser_sdf.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-KOtp99jnZJJhgiiNolk:-KOtsVm_ynEqrjW8iAyC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/097d2ec929ac5fb4018cae212d7193d6740b5bb6/drake/systems/plants/parser_sdf.h#L18)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "... to a rigid body tree."
</details>
Done.

---

*[drake/systems/plants/parser_sdf.h, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-KOtpKwrtUMuVvnbRZN0:-KOtsWPqAp8KwsSXd__2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/097d2ec929ac5fb4018cae212d7193d6740b5bb6/drake/systems/plants/parser_sdf.h#L43)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "... to a rigid body tree."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-:-KOtsXYFHdD66iKF4GAC:b-ujxhqu)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-:-KOtwKF7hy2ffIhb8qvB:bb329pf)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-:-KOx4dpg1QnX6AtbAOti:bhiddle)*

**Comment by liangfok** [comment]
Thanks. Now waiting on @amcastro-tri for a feature review.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-:-KOx5PR9p0Gtn4ODPCNk:b-12o11k)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3115#-:-KOzAJpot4waaf90t1vV:bnfp4nl)*

**Pull request merged**
