### PR TITLE
Added clarification to style guide regarding use of exceptions.

### LINKED ISSUE #3757: Document code_style_guide for (non-)use of exceptions
We should document in our `code_style_guide.rst` our policy on the (non-)use of exceptions.

I believe the current undocumented rule is that:
(1) any code can `throw`;
(2) unit tests can `EXPECT_THROW`, but only if the exception is documented in the API;
(3) non-test code cannot catch.

In any case, we should write some specific rule and its rationale for posterity.

See also #3504.

### PR DESCRIPTION
**Pull request by liangfok**
Closes #3757.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3759)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
LOL, I was just creating a branch to start work on this.  I will take a look, but after my pass we should definitely look in several others to ensure consensus.

**Comment by liangfok** [comment]
Heh, pretty quick huh? I'd be happy to iterate.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnmHagP-0OV2Bc-EG4:-KTnmHahwfh3ysQ7Kvlh:b-w5kow8) ([raw file](https://github.com/robotlocomotion/drake/blob/a35f5ac5253865cfa9ec5c737a73de4091f1051e/drake/doc/code_style_guide.rst#L108)):*
> ```reStructuredText
>   we clarify that a class member variable must be declared ``const`` if it
>   is not modified after the class is constructed.
> * For the `Exceptions
> ```

This part of this document already mentions exceptions:
https://github.com/RobotLocomotion/drake/blame/1e03cbc251db09fdc0ff4b774008c5a93baca88e/drake/doc/code_style_guide.rst#L43

I suspect it would be clearer to readers if that bullet and this bullet were adjacent, or perhaps even this one nested under that one.

---

*[drake/doc/code_style_guide.rst, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnmU-hQDT3ng1dwUqj:-KTnmU-hQDT3ng1dwUqk:bd551cr) ([raw file](https://github.com/robotlocomotion/drake/blob/a35f5ac5253865cfa9ec5c737a73de4091f1051e/drake/doc/code_style_guide.rst#L119)):*
> ```reStructuredText
> 
>   We allow exceptions to be thrown because it allows a more detailed description
>   of the error to be provided relative to an assert statement.
> ```

Please add a citation to this PR number (for background discussion), now that we have one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759)*

**Comment by jwnimmer-tri** [comment]
For the record, why we don't allow non-test code to catch exceptions: we don't want to take on the challenge of writing exception-safe code pervasively throughout our system.  In the future, we may decide to allow it in certain cases subject to additional inspection / testing / verfication (e.g., when using the visitor pattern, where error-handling is otherwise difficult, or as part of a catch-and-rethrow consensus from #3504).

**Comment by liangfok** [comment]
@jwnimmer-tri I addressed your comments. Should I also add a sentence after "Non-test code cannot catch" that explains why (basically a summary of your paragraph above)?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnmHagP-0OV2Bc-EG4:-KTnmzMOy2g32Nzf8bz2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a35f5ac5253865cfa9ec5c737a73de4091f1051e/drake/doc/code_style_guide.rst#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This part of this document already mentions exceptions:
> https://github.com/RobotLocomotion/drake/blame/1e03cbc251db09fdc0ff4b774008c5a93baca88e/drake/doc/code_style_guide.rst#L43
> 
> I suspect it would be clearer to readers if that bullet and this bullet were adjacent, or perhaps even this one nested under that one.
</details>
Done.

---

*[drake/doc/code_style_guide.rst, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnmU-hQDT3ng1dwUqj:-KTnnSaxcVwcZIJRXc3J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a35f5ac5253865cfa9ec5c737a73de4091f1051e/drake/doc/code_style_guide.rst#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Please add a citation to this PR number (for background discussion), now that we have one.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTnnlLgXm4yioNOItgU:b-w9w0dl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

I am okay leaving the rationale and discussion in the PR only (it's what we've often been doing).

Long-term, I actually want to fork `google-styleguide` and place our edits inline (with appropriate CSS to highlight Google vs Local style), including discussion.  For now, I think having it cited at all is good enough.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTnpGY5MbadtujeksJ1:b4r48xk)*

**Comment by liangfok** [comment]
OK SGTM. +@david-german-tri  for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTnpt_6lXptfbLd3smC:b-omlpry)*

**Comment by jwnimmer-tri** [comment]
Also +@ggould-tri and +@sammy-tri and +@sherm1 for platform.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTnqDHYgjFQXouNUBOd:b7aie0)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnr35xfZPdDNVDfZU3:-KTnr35yQQMZ2C9VGQSj:b-mubkl9) ([raw file](https://github.com/robotlocomotion/drake/blob/028497718f09ae5ad0ca973ab39291874a94e81b/drake/doc/code_style_guide.rst#L46)):*
> ```reStructuredText
>   safe.
> 
>   * For the `Exceptions
> ```

I would say this counts as an "Exception" (pun inevitable), not a "Clarification".

---

*[drake/doc/code_style_guide.rst, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnrEbjfSyPKBVGwjlJ:-KTnrEbjfSyPKBVGwjlK:b1sxti) ([raw file](https://github.com/robotlocomotion/drake/blob/028497718f09ae5ad0ca973ab39291874a94e81b/drake/doc/code_style_guide.rst#L46)):*
> ```reStructuredText
>   safe.
> 
>   * For the `Exceptions
> ```

BTW, proposed alternate text that I think states the same rule more concisely:  "Throwing exceptions is permitted.  Unit tests may catch exceptions using EXPECT_THROW, if the exception is documented in the API.  Otherwise, catching exceptions is forbidden."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnr35xfZPdDNVDfZU3:-KTnszyGWkx_KmWS_mnJ:b2ufnq9) ([raw file](https://github.com/robotlocomotion/drake/blob/028497718f09ae5ad0ca973ab39291874a94e81b/drake/doc/code_style_guide.rst#L46)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I would say this counts as an "Exception" (pun inevitable), not a "Clarification".
</details>
FYI I think the top-level split Clarifications / Exceptions / ... we have here is unhelpful (I would prefer to follow the cppguide sections in our ordering), and putting the two exception-related rules adjacent is better.  r1 actually had the text down below as you request, but I requested that it become adjacent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759)*

**Comment by ggould-tri** [comment]
:lgtm:

One small qualm about the long-term vision you describe above.  Google-styleguide is under almost daily revision; forking will be equivalent to version-pinning and we will need to have a process for pulling HEAD periodically.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnrEbjfSyPKBVGwjlJ:-KTnyRCyPrVVoKxiwkqS:b-mrh6wm) ([raw file](https://github.com/robotlocomotion/drake/blob/028497718f09ae5ad0ca973ab39291874a94e81b/drake/doc/code_style_guide.rst#L46)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, proposed alternate text that I think states the same rule more concisely:  "Throwing exceptions is permitted.  Unit tests may catch exceptions using EXPECT_THROW, if the exception is documented in the API.  Otherwise, catching exceptions is forbidden."
</details>
I like this proposed wording but not enough to make a blocking comment; lgtm either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTnyYEwgH9KxlYpJtMX:bb8dpkv)*

**Comment by jwnimmer-tri** [comment]
> ... we will need to have a process for pulling HEAD periodically.

Absolutely :100:.

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTo7foTAH-mZWqq1Fhr:bnfp4nl)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnr35xfZPdDNVDfZU3:-KTo9cZ09PtaE0O4uCgi:bk170i4) ([raw file](https://github.com/robotlocomotion/drake/blob/028497718f09ae5ad0ca973ab39291874a94e81b/drake/doc/code_style_guide.rst#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI I think the top-level split Clarifications / Exceptions / ... we have here is unhelpful (I would prefer to follow the cppguide sections in our ordering), and putting the two exception-related rules adjacent is better.  r1 actually had the text down below as you request, but I requested that it become adjacent.
</details>
I better integrated the next text with the old text. PTAL.

---

*[drake/doc/code_style_guide.rst, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KTnrEbjfSyPKBVGwjlJ:-KTo9g7Hb46_dzqibzC3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/028497718f09ae5ad0ca973ab39291874a94e81b/drake/doc/code_style_guide.rst#L46)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I like this proposed wording but not enough to make a blocking comment; lgtm either way.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTo9lJ_Rbb1Z3msAKyQ:bblnx7i)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KToDaFVjHWyTdQ29Q_x:-KToDaFVjHWyTdQ29Q_y:bfualzg) ([raw file](https://github.com/robotlocomotion/drake/blob/6e8025e83a668b93f9b1e81956e42414cb124f00/drake/doc/code_style_guide.rst#L45)):*
> ```reStructuredText
> * For the `Exceptions
>   <https://google.github.io/styleguide/cppguide.html#Exceptions>`_ style rule,
>   we clarify as follows. Use exceptions for error handling.  Essential control
> ```

Is the sentence "Essential control loops must be exception safe" still true?

---

*[drake/doc/code_style_guide.rst, line 48 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KToDnGxqc2l0kOK8lI7:-KToDnGxqc2l0kOK8lI8:b3pmkg2) ([raw file](https://github.com/robotlocomotion/drake/blob/6e8025e83a668b93f9b1e81956e42414cb124f00/drake/doc/code_style_guide.rst#L48)):*
> ```reStructuredText
>   loops must be exception safe.
> 
>   * Throwing exceptions is permitted. Unit tests may catch exceptions using
> ```

I'm confused by the bullet structure here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KToDaFVjHWyTdQ29Q_x:-KToH3evuWwdIPFDgXyU:bbtwn84) ([raw file](https://github.com/robotlocomotion/drake/blob/6e8025e83a668b93f9b1e81956e42414cb124f00/drake/doc/code_style_guide.rst#L45)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Is the sentence "Essential control loops must be exception safe" still true?
</details>
I suppose it's no longer true since we disallow control loops from catching exceptions. I've thus removed it.

---

*[drake/doc/code_style_guide.rst, line 48 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-KToDnGxqc2l0kOK8lI7:-KToHBbBNDwyOqfNxDCs:b2dplyt) ([raw file](https://github.com/robotlocomotion/drake/blob/6e8025e83a668b93f9b1e81956e42414cb124f00/drake/doc/code_style_guide.rst#L48)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I'm confused by the bullet structure here.
</details>
I moved most of the text into the parent bullet. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToHFtId9_y6hZQmL-q:bblnx7i)*

**Comment by jwnimmer-tri** [comment]
+@russtedrake also for review now, since this is removing a statement ("control loops must be exception-safe") that dates back to wiki times, and I think predates TRI.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToHLh4QkoXfpROvyBv:b-7pr3i9)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToNZF1enK2cXhxCzcn:bnfp4nl)*

**Comment by sherm1** [comment]
The complete prohibition on catching exceptions is too strict; it should be permitted in rare circumstances with sufficient justification. We will need it in at least one place I know of and possibly some other related uses. The one I know of for sure is speculative execution in variable-step integration. The integrator attempts to take large steps in an unknown (user written) landscape, and in doing so acquires information about what (smaller) step size it should have taken. Accuracy estimation is one source of such information, zero crossings is another, and abject failure to evaluate is another. In practice the latter is signaled either by derivatives that come back NaN, or by the user code throwing an exception due to finding itself in some impossible situation caused by an unreasonably large step. The best cure for that is to catch that exception, cut the step size in half, and retry. In most cases the underlying code will succeed at a smaller step size; if the exception is a real error that is reported when the step size reaches its allowed minimum, which doesn't take long.

Optimization may have similar needs. Global optimizers poke around widely in the solution landscape (using arbitrary user code) and are prone to hitting landmines. Possibly a catch-and-avoid strategy would be reasonable there too; I'm not as sure.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToJV9EnlpmTb_VHuW4:b-i9nh50)*

**Comment by liangfok** [comment]
@sherm1, thanks for the explanation of when exceptions are necessary. To make sure I understand, are you saying it's impossible to require that the user's code detect the impending failure and return a Boolean value telling Drake to try a smaller time step?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToO53vR4OmYHDzTvyg:bkzp5af)*

**Comment by jwnimmer-tri** [comment]
@sherm1 In general, code can ignore the style guide with a sufficiently good reason.  We don't have to add "unless special circumstances require it" text onto every single rule.  Is that enough let this PR go in as it stands?

Also, I am skeptical that we should admit one-off uses of exceptions like your "throw impossible_situation();` through loosely-coupled code.  That is tantamount to saying "all framework and systems code must be exception-safe", which is the opposite of this proposal.  Either we go all the way and allow exceptions throughout (with suitable rules and test coverage), or else catching exceptions remains verboten, and the "I can't do that" turns into an explicit portion of the API.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToNuB8Jeu6CjKUR05r:b-zex887)*

**Comment by david-german-tri** [comment]
> In general, code can ignore the style guide with a sufficiently good reason. We don't have to add "unless special circumstances require it" text onto every single rule.

:+1:

> Also, I am skeptical that we should admit one-off uses of exceptions like your "throw impossible_situation();` through loosely-coupled code. 

I also am skeptical - it sounds to me like we could meet this need more safely with error codes - but I don't understand in what situation derivatives would be un-evaluable, so I may be lacking some important intuition.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToOE3MMcKsEXsscY4z:b-c4squa)*

**Comment by sherm1** [comment]
I understand your skepticism but I have a lot of practical evidence that this is a robust strategy for variable-step numerical integration. It does not require any special treatment of user code (which is often heavily dependent on 3rd party libraries) and it is completely compatible with our current error-handling scheme, which permits thrown exceptions rather than bubbled-up status returns. Our requirement that all mutable state resides in the Context ensures that the integrator can preserve the state prior to a trial step and restore it after an unexpected disaster with no help from the failing code. Our attention to sanitary heap ownership ensures that a thrown exception won't leak.

For now I am just going to assert that this is a necessary aspect of variable step integration and insist that we leave the door open for it in the style guide. Given the strong opinions expressed above, I want a comment like "except under rare and carefully vetted circumstances where there is no other practical alternative" so I won't have to fight this battle later against pedantic "not allowed" arguments.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToQnw2uwF6ZST5as-W:b-l3zl7d)*

**Comment by liangfok** [comment]
OK. How about I go ahead and augment this PR with a new bullet in the "Exceptions" section stating that exceptions can be caught in the integrator for the purpose of allowing 3rd party code to throw exceptions when they fail when the given time step? We can augment this exception to include optimizers if and when the need arises.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToXLvi8vh1cgrgrIVd:btpqq9)*

**Comment by jwnimmer-tri** [comment]
@liangfok I don't think we should pre-agree to allow catching exceptions in a certain piece of code in the style guide.  If we need one-off adjustments, it should be through carefully-commented statements inline with the code doing the catching.

I still have to mull over if I think "catching is allowed, but only when it's okay" is a valid compromise.  I will update this thread later.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToY8ggjtyoz-pFt-JS:b-k3yts7)*

**Comment by david-german-tri** [comment]
> I want a comment like "except under rare and carefully vetted circumstances where there is no other practical alternative" so I won't have to fight this battle later against pedantic "not allowed" arguments.

I think you should have to fight this battle later, with specific code on the table.

> I don't think we should pre-agree to allow catching exceptions in a certain piece of code in the style guide. 

:+1:

> I still have to mull over if I think "catching is allowed, but only when it's okay" is a valid compromise.

If that's the compromise, then we should just drop this PR.  However, I don't think it's valid - `catch` imposes a requirement on all the code called from inside the `catch` block to be exception-safe, which will come as a surprise to the authors of that code.  Thus, if we're ever going to type `catch`, we need to carefully vet what goes in that block, and document the requirements imposed on it. 

Without code on the table, I offer no opinion on whether `catch` can be made safe in the specific use @sherm1 is contemplating, but it definitely needs case-by-case scrutiny.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KToY8MPvOnV_bIiHiav:b47vdhd)*

**Comment by ggould-tri** [comment]
I agree with David that allowing code to catch exceptions and call out to other methods is a landmine -- writing exception-safe code is hard and, while our code conventions and PR review process give us a solid start on it, we are nowhere near it yet.

I wonder if a compromise is available that code may catch only exceptions that it defines itself in its own namespace or class.  Presumably any external code it calls out to that throws that exception has done so with full knowledge of this fact, and the exception cannot come from some unexpected library or overload outside of the exception-safe region.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTp6Geyu6crkaUfqLOt:b5zkj0p)*

**Comment by jwnimmer-tri** [comment]
Like David, I don't think we should design solutions without a problem a hand and code on the table.  I would like to find a compromise wording that allows that discussion to happen in the future, while still merging the "only catch in unit tests" starting point that we have proposed here.

Sherm proposed "except under rare and carefully vetted circumstances where there is no other practical alternative" but I think that predisposes the resolution somewhat.

How about adding something like this to the PR instead: "Note: This is a work-in-progress rule, but captures our currently-in-effect style.  We are open to discussion on additional uses for exceptions if and when the need arises."

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpA8RcrNxFxcWpxYo2:bxpq7dw)*

**Comment by sherm1** [comment]
That wording is fine with me.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpEgKPtmp3M-SH1fcc:bltx3rc)*

**Comment by liangfok** [comment]
I updated this PR with the proposed text. PTAL. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpFqgR-G0zkdJVM-oz:b-ran0s6)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpO_oWtFAajbkf8dWi:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Now waiting on reviews from @sherm1 and @russtedrake .

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpP4V_76hqs0ROYWmV:b-9pyz7t)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpU8hxcDiN9zpTdoGG:bnfp4nl)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3759#-:-KTpYgiwJAMOvwdw-Sa-:bnfp4nl)*

**Pull request merged**
