### PR TITLE
[hydro] Eliminating representative triangle contact surface

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This simply eliminates the tentative API for producing a contact surface with fewer elements. It is being removed so that it doesn't interfere with introducing the polygon surface mesh version of the contact surface.

This means, there will temporarily be no "low resolution" contact surface in discrete mode until the PR train outlined in #15796 is completed.

Relates #15796.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@damrongguoy Here's a monster PR. It's mostly deletion, I wanted to get the review process going so you have time to work your way through it before I need it done.

This has already been validated against Anzu.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-MooQpSn40WR9vZl2xOQ:blipy43)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
I'll start the review now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-Mopd_w40nVOzCZOxH1x:b-x71vca)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
@jwnimmer-tri @rpoyner-tri  This PR would be a good challenging example to run `kcov` automatically and incrementally.  I can count 9 *test.cc files. With the current tools, I'll have to do it manually 9 times on my Puget.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-MopdrVjCqREbwoiyYGJ:b6cfaax)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Checkpoint.  I'm still early in the review.

It's thousands of lines to remove one parameter in this PR.  If, in the future, we want to make it flexible again, will we have to add thousands of lines back? I hope the new design will be more agile, so we don't have to add/remove thousands of lines every time the wind changes direction.

> Reviewed 11 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-MoqS126-1YC-3YoTUVz:b-jrlf5l)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[geometry/proximity/contact_surface_utility.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MopkHht6pDWN6R01E0E:-MopkHhuCtNRzRke41WO:brlzjzq) ([raw file](https://github.com/robotlocomotion/drake/blob/f3569d0720fd071dc44c446126fae6bd31913ff9/geometry/proximity/contact_surface_utility.cc#L45)):*
> ```cpp
>                                const std::vector<int>& polygon,
>                                const Vector3<T>& n_F,
>                                const std::vector<Vector3<T>>& vertices_F) {
> ```

@jwnimmer-tri @rpoyner-tri This is an interesting case for `kcov` related to `debug` build.

I have just realized that this function is called only in debug mode from a line like this:
```C++
  DRAKE_ASSERT_VOID(ThrowIfInvalidForCentroid("CalcPolygonCentroid", polygon,
                                              n_F, vertices_F));
```

I'll have to remind myself that a function might be called only in debug mode, so running `bazel test --config=kcov` may miss it.
___
*[geometry/proximity/contact_surface_utility.cc, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MoplWD075R9y065-2d6:-MoplWD075R9y065-2d7:b-mjqzhc) ([raw file](https://github.com/robotlocomotion/drake/blob/f3569d0720fd071dc44c446126fae6bd31913ff9/geometry/proximity/contact_surface_utility.cc#L327)):*
> ```cpp
>                                    const TriangleSurfaceMesh<T>& surface_M,
>                                    int tri_index,
>                                    const math::RotationMatrix<T>& R_FM) {
> ```

Could you add a TODO to unit test this function in `contact_surface_utility_test.cc`, please?

It's not a part of this PR, so a TODO is more than enough.
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MoqMrVd0c6b54hJTmKP:-MoqMrVd0c6b54hJTmKQ:bymwmf5) ([raw file](https://github.com/robotlocomotion/drake/blob/aa2f69e03fb27d718544e53f55ac32ba4b8ea29a/geometry/proximity/test/mesh_half_space_intersection_test.cc#L471)):*
> ```cpp
>     // --------> x
>     //
>     // The degenerate quad is formed by (b, c, d, e) which results in a
> ```

To help future developers, describe the quad more, please.   It took me quite a while to understand
what the picture want to say:
```C++
Expect the intersection to be a zero-area quadrilateral BCDE with two pairs of
duplicated vertices: p_WB==p_WE and p_WC==p_WD. The degenerate quad
results in a triangle fan around the centroid at p_WF.
```
The word `degenerate quad` can mean several things (there are quite a number of ways for the quad to degenerate). In the beginning, I even thought of the degenerate quad with no duplicate vertices like this: +---+---+---+.
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 556 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MoqG1qx-aZKuJWcYwMt:-MoqG1qy25eVPnFKRw_v:bc2m2cv) ([raw file](https://github.com/robotlocomotion/drake/blob/aa2f69e03fb27d718544e53f55ac32ba4b8ea29a/geometry/proximity/test/mesh_plane_intersection_test.cc#L556)):*
> ```cpp
>     CallSliceTetWithPlane(Plane<double>{Mz_F, p_FMax - offset_F}, X_FM,
>                           no_analysis);
>     EXPECT_TRUE(HasNFaces(3));
> ```

To help future developers, comment that they are very tiny triangles, please.
```C++
// They are very tiny triangles due to epsilon offset near the tetrahedron's apex.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
You'll note that the majority of the changes are in unit tests. When the hack was applied, testing wasn't applied in a targeted way, but in a big "copy-and-paste" kind of way. One thing that would help in the future is to make sure there is a cleaner separation of concerns such that things can be properly unit tested. The new version pushes hard in this direction.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-Mot82g1ANrq6KVDQNRB:b-fa2xy6)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[geometry/proximity/contact_surface_utility.cc, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MoplWD075R9y065-2d6:-Mot96zS1zPZOgl0080n:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f3569d0720fd071dc44c446126fae6bd31913ff9/geometry/proximity/contact_surface_utility.cc#L327)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Could you add a TODO to unit test this function in `contact_surface_utility_test.cc`, please?

It's not a part of this PR, so a TODO is more than enough.
</blockquote></details>

Done
___
*[geometry/proximity/test/mesh_half_space_intersection_test.cc, line 471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MoqMrVd0c6b54hJTmKP:-MotA7qK0YgOqsqml09r:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/aa2f69e03fb27d718544e53f55ac32ba4b8ea29a/geometry/proximity/test/mesh_half_space_intersection_test.cc#L471)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

To help future developers, describe the quad more, please.   It took me quite a while to understand
what the picture want to say:
```C++
Expect the intersection to be a zero-area quadrilateral BCDE with two pairs of
duplicated vertices: p_WB==p_WE and p_WC==p_WD. The degenerate quad
results in a triangle fan around the centroid at p_WF.
```
The word `degenerate quad` can mean several things (there are quite a number of ways for the quad to degenerate). In the beginning, I even thought of the degenerate quad with no duplicate vertices like this: +---+---+---+.
</blockquote></details>

Done
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 556 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MoqG1qx-aZKuJWcYwMt:-MotAmMD1JekQVZ6VGE2:b-pehtan) ([raw file](https://github.com/robotlocomotion/drake/blob/aa2f69e03fb27d718544e53f55ac32ba4b8ea29a/geometry/proximity/test/mesh_plane_intersection_test.cc#L556)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

To help future developers, comment that they are very tiny triangles, please.
```C++
// They are very tiny triangles due to epsilon offset near the tetrahedron's apex.
```
</blockquote></details>

I'm going to forego doing that. 

  - It feels quite inconsistent to do it only this one case (contrast with the case where the plane lies almost completely below the test).
  - The test is really about observing the boundaries of where we transition from intersection to separation. As such, zero and non-zero is all that really matters.

To that end, I've augmented the test documentation to helpfully alleviate the need in future developers minds of needing to understand those values.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotCZbE5UfHL_FtvS6f:-MotCZbE5UfHL_FtvS6g:but57c5) (no related file):*
+(status: do not merge) During review, this will go through various changes. After all changes have been applied and the code has been approved, we need to do one more run past Anzu before we can merge.

---

**Review by DamrongGuoy — COMMENTED** [review]
I agree that we need to separate the code for output format from the core computation. This way we test it independently and minimize the duplication next time we have a new output format (mixed-element meshes, high-order FEM, Discontinuous Galerkin FEM, polygon soups for GPU, weighted point clouds for particle-based sim, etc.)  Copy-and-paste thousands of lines were not productive.

Is the idea of callback still in the design?  Callers supply a callback function to select the output format. Callees only tests one representative callback. Sort of like testing calculation with `double` to say it will work for `AutoDiff`.

> Reviewed 15 of 26 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-MotG5GUAqBMhbmZYlGC:b-gsl9eo)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy and @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

I'm glad we removed many lines.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-MotIJaY14xqXKl0K1x8:b5z5s6u)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy and @SeanCurtis-TRI)

**Comment by DamrongGuoy** [comment]
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 521 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotJ14f8lDS2qHo3I_n:-MotJ14f8lDS2qHo3I_o:bb8xhdl) ([raw file](https://github.com/robotlocomotion/drake/blob/27b5868a302640c0752cf9530933b8360b0a68dd/geometry/proximity/test/mesh_plane_intersection_test.cc#L521)):*
> ```cpp
>  when separated and a non-zero number of faces when intersecting. The exact
>  value of that non-zero value is not important to the test -- merely that it is
>  non-zero, indicating intersection. */
> ```

Thank you!  That helps a lot!

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
You've got the idea exactly. The new interface uses a `MeshBuilder` concept. The intersecting code just knows that it has produced a polygon (and knows where it comes from), so it passes the polygon data to the `MeshBuilder` and, at the end of the day, when intersection is complete, asks the builder to create the mesh and field. It's not a callback, per se. It proved to be better as an object, but in principle, it's the same. Intersecting code doesn't know how any particular mesh type is constructed from polygons.

+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-MotRRie3-nVgVnk00dK:b-kc0em7)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @DamrongGuoy, @rpoyner-tri, and @SeanCurtis-TRI)

___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 521 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotJ14f8lDS2qHo3I_n:-MotRxIt7LmUkLqM7ID2:bxj8vg7) ([raw file](https://github.com/robotlocomotion/drake/blob/27b5868a302640c0752cf9530933b8360b0a68dd/geometry/proximity/test/mesh_plane_intersection_test.cc#L521)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thank you!  That helps a lot!
</blockquote></details>

I briefly toyed with reformulating the test as `EXPECT_TRUE(HasFaces())` or some such thing. But elaborating the documentation felt a cheaper way forward.  :)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 23 of 26 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotCZbE5UfHL_FtvS6f:-Mot_laO7diOuy5h3sRU:b-zf7i1u) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

+(status: do not merge) During review, this will go through various changes. After all changes have been applied and the code has been approved, we need to do one more run past Anzu before we can merge.
</blockquote></details>

:lgtm_strong: 

“Inside every large program is a small program struggling to get out.”
— Tony Hoare

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotXPst6uLLKGI_-gtl):*
BTW this verb form creates work for release notes editors.
___
*[geometry/proximity/contact_surface_utility.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MopkHht6pDWN6R01E0E:-MotXqvDE072GIZpXUGy:be7pnuh) ([raw file](https://github.com/robotlocomotion/drake/blob/f3569d0720fd071dc44c446126fae6bd31913ff9/geometry/proximity/contact_surface_utility.cc#L45)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@jwnimmer-tri @rpoyner-tri This is an interesting case for `kcov` related to `debug` build.

I have just realized that this function is called only in debug mode from a line like this:
```C++
  DRAKE_ASSERT_VOID(ThrowIfInvalidForCentroid("CalcPolygonCentroid", polygon,
                                              n_F, vertices_F));
```

I'll have to remind myself that a function might be called only in debug mode, so running `bazel test --config=kcov` may miss it.
</blockquote></details>

FWIW, I often let testing of error branches go in kcov analysis. In this case, a name like `ThrowIf...` is a pretty good clue. ;) Certainly authors are not prevented from covering error branches, but it's a judgement of authors and reviewers to decided if it's necessary.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-Mota3Uc3gwwWpPuEVIG:b-uwkowd)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120#-:-Motczih0sGpwbtizpYY:b-zcjvte)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotCZbE5UfHL_FtvS6f:-MotcnOEBEWaJaxcFFqh:by0hutr) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

:lgtm_strong: 

“Inside every large program is a small program struggling to get out.”
— Tony Hoare
</blockquote></details>

Running Anzu-master-Drake-PR/138/. I'll clear merge obstacles when that passes.

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotCZbE5UfHL_FtvS6f:-Moth7QL57Vrd5UC6U-h:b-c3uazw) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Running Anzu-master-Drake-PR/138/. I'll clear merge obstacles when that passes.
</blockquote></details>

Please set discussion state to `working`. 

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16120)* status: labeled "do not merge" (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16120#-MotCZbE5UfHL_FtvS6f:-MotppPfDiywTxUmTrrw:b-xeptj4) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Please set discussion state to `working`. 
</blockquote></details>

In this case, it's happy and done.
-(status: do not merge) 

---

**Pull request merged**
