### PR TITLE
Introduce a fix for the shadowing error on osx builder

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7354)

### CODE REVIEW

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please

**Comment by jadecastro** [comment]
+@soonho-tri for all reviews, please. Pending CI result.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7354#-:-KxU5RaI7ktl78xiPcQ-:b-s76up)*

**Comment by soonho-tri** [comment]
:lgtm: finger crossed for CI tests. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7354#-:-KxU5wVXitJWDh5vAylS:b-eeuzyf)*

**Comment by soonho-tri** [comment]
@jadecastro , just added `do not merge` label. Please feel free to remove it and merge this PR when `mac-elcapitan-clang-bazel-experimental` passes.

**Pull request merged**
