### PR TITLE
[multibody/fixed_fem/dev] Star refinement of boundary tetrahedra.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Dev code for star refinement of boundary tetrahedra for Deformables.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@xuchenhan-tri for single review please. It's all in `dev`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813#-:-MkNeZYU3Q_h5zMzOvBN:b-xo6lo5)* status: LGTM missing from assignee xuchenhan-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
First pass done. Mostly nits and BTW's with one API question. PTAL, thanks.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813#-:-MkOBuhR26vzJA5pHKLd:b-djinxw)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri (waiting on @DamrongGuoy)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkO9moB89L3iOHi1XYg:-MkO9moC1t9xaKMPSPMA:b-b8hmek) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.h#L102)):*
> ```objc
>  */
> template <typename T>
> std::unique_ptr<geometry::VolumeMesh<T>> StarRefineBoundaryTetrahedra(
> ```

Is it necessary to return a unique_ptr?  Could you simple return geometry::VolumeMesh<T>?
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNwlV7AJzdMSEzrDzo:-MkNwlV7AJzdMSEzrDzp:b-97alzd) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L27)):*
> ```cpp
> namespace {
> 
> bool IsBoundaryTetrahedron(
> ```

nit, even though this is in an unnamed namespace in a `.cc` file, a brief description of the method would be nice for those who don't want to read the code below. 
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNwXtJ6gJt1UJqQERm:-MkNwXtJ6gJt1UJqQERn:b97b8ch) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L30)):*
> ```cpp
>     const VolumeElement& tetrahedron,
>     const std::unordered_set<VolumeVertexIndex>& boundary_vertex_set) {
>   int num_boundary_vertices = 0;
> ```

BTW, this local counter is not necessary. You can return `false` as soon as you find an interior vertex.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNxFJ15tYjs2k1fH4s:-MkNxFJ15tYjs2k1fH4t:b-8lnwc7) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L40)):*
> ```cpp
> 
> template <typename T>
> void StarRefineTetrahedron(int e, std::vector<VolumeElement>* elements,
> ```

nit: again, a brief description of the method would be nice.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNy6K80GoVHMb5gWz4:-MkNy6K90a9_B02BfzdL:bt5ngvd) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L62)):*
> ```cpp
>                          (*vertices)[v2].r_MV() + (*vertices)[v3].r_MV()) /
>                         4.;
>   vertices->emplace_back(star);
> ```

BTW, why not move the `star` in the list of vertices since you already declared it as non-const?
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNypp7-iANv-8tRBUw:-MkNypp7-iANv-8tRBUx:b-lig4v7) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L98)):*
> ```cpp
>       boundary_vertices.begin(), boundary_vertices.end());
> 
>   const int num_tetrahedra = out_elements.size();
> ```

BTW, it'd be more intuitive (at least to me) to say
`num_tetrahedra = in.num_elements();`
since the final `out_elements`'s size would be different.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNzSMJAgVAOra7EZ6x:-MkNzSMK5vVn8MegefDJ:b-kn9hmg) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L100)):*
> ```cpp
>   const int num_tetrahedra = out_elements.size();
>   for (int i=0; i < num_tetrahedra; ++i) {
>     if (IsBoundaryTetrahedron(out_elements.at(i), boundary_vertex_set)) {
> ```

BTW, bound checking seems unnecessary here. operator [] should work just fine? 
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 228 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkOAu3a9foOZWJW53zq:-MkOAu3a9foOZWJW53zr:bmbn20m) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L228)):*
> ```cpp
>     //  The star-refinement is expected to create 4 x 6 = 24 tetrahedra.
>     EXPECT_EQ(refined_cube_mesh->num_elements(), 24);
>     EXPECT_EQ(refined_cube_mesh->num_vertices(), 14);
> ```

Perhaps also a comment on why 14 here? (8 + 6 = 14)
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkOBHGXAYi3hnJgaIYU:-MkOBHGXAYi3hnJgaIYV:bdjmalq) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L237)):*
> ```cpp
> // 2. bazel-bin/multibody/fixed_fem/dev/mesh_utilities_test to get *.vtk files.
> // 3. paraview, Load Data: *.vtk
> GTEST_TEST(MeshUtilitiesTest, VisuallyVerifyStarRefineBoundaryTetrahedra) {
> ```

FYI, not sure if this will survive the migration out of `dev` as it would be hard to consistently and systematically repeat this test. But since moving out of `dev` requires two additional reviews, I'm fine with pushing this to `dev` for now to give us some more confidence on the refinement.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/mesh_utilities.h, line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkO9moB89L3iOHi1XYg:-MkOc-lT-cfS8jCbSeBt:b-tj14xy) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.h#L102)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is it necessary to return a unique_ptr?  Could you simple return geometry::VolumeMesh<T>?
</blockquote></details>

Good point. I changed it to non-pointer type.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNwlV7AJzdMSEzrDzo:-MkOcXRR-uGNHPFZ5EDK:bg306hq) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, even though this is in an unnamed namespace in a `.cc` file, a brief description of the method would be nice for those who don't want to read the code below. 
</blockquote></details>

Done. Good question.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNwXtJ6gJt1UJqQERm:-MkOcl5Y-wY07uRkPXSP:bap7yvo) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L30)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this local counter is not necessary. You can return `false` as soon as you find an interior vertex.
</blockquote></details>

Good point. Thanks!
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNxFJ15tYjs2k1fH4s:-MkOds9A-pNnYZ01X292:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit: again, a brief description of the method would be nice.
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNy6K80GoVHMb5gWz4:-MkOe0TfEbMV9dG0Vhie:b-q0y5m4) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L62)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why not move the `star` in the list of vertices since you already declared it as non-const?
</blockquote></details>

That's a complaint from many people.  The `vertices` consists of `VolumeVertex<T>s`, while the `star` is a `Vector3<T>`.  It's one level of indirection that caused many complaints, and I think Sean has a plan to eliminate `VolumeVertex<T>` and use `Vector3<T>` directly.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 98 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNypp7-iANv-8tRBUw:-MkOfK96Esst16qzM7ky:b-fulf95) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L98)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, it'd be more intuitive (at least to me) to say
`num_tetrahedra = in.num_elements();`
since the final `out_elements`'s size would be different.
</blockquote></details>

Done.  I also changed the name to `num_input_tetrahedra`.

Please let me know if there's a way to make it easier to understand. I always go for it.
___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNzSMJAgVAOra7EZ6x:-MkOfkp-ApyfnRmFtRo7:bw9613x) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L100)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, bound checking seems unnecessary here. operator [] should work just fine? 
</blockquote></details>

Done. Changed to `[i]`.
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 228 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkOAu3a9foOZWJW53zq:-MkOgn3945tUGXOPdOCl:b-kw490w) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L228)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Perhaps also a comment on why 14 here? (8 + 6 = 14)
</blockquote></details>

Done. Thanks for asking.
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkOBHGXAYi3hnJgaIYU:-MkOgNBl0FMUu1ujx-0P:bvu2k33) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L237)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, not sure if this will survive the migration out of `dev` as it would be hard to consistently and systematically repeat this test. But since moving out of `dev` requires two additional reviews, I'm fine with pushing this to `dev` for now to give us some more confidence on the refinement.
</blockquote></details>

I agree.  I put a TODO to remind the next author to remove it before going out of `dev`.

**Review by DamrongGuoy — COMMENTED** [review]
Addressed all Reviewable questions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813#-:-MkOiUmK-AFlQ9Q-J7Eu:b-3k5l4y)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with one last thought.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813#-:-MkOu8zq9ddYnwzPDeTm:b1o2lcq)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri, exempt from platform review (waiting on @DamrongGuoy)

___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNy6K80GoVHMb5gWz4:-MkOteP1BbbPMGhgeSET:bdtd7nx) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L62)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

That's a complaint from many people.  The `vertices` consists of `VolumeVertex<T>s`, while the `star` is a `Vector3<T>`.  It's one level of indirection that caused many complaints, and I think Sean has a plan to eliminate `VolumeVertex<T>` and use `Vector3<T>` directly.
</blockquote></details>

Ah, I missed that point, sorry. In this case, might as well make `star` const (or directly construct `star` as a `VolumeVertex` and move it into `vertices`).

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri, exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNy6K80GoVHMb5gWz4:-MkP6tVKBCrpyjjnm5fY:b-92mq59) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L62)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ah, I missed that point, sorry. In this case, might as well make `star` const (or directly construct `star` as a `VolumeVertex` and move it into `vertices`).
</blockquote></details>

Done.  Is it better?  Please let me know.  I'd like to make it easy to understand.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15813)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri, exempt from platform review (waiting on @DamrongGuoy)

___
*[multibody/fixed_fem/dev/mesh_utilities.cc, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15813#-MkNy6K80GoVHMb5gWz4:-MkP92S7A4vXOeZGIGw2:blnsof7) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f5496c43cae996676f065b1188836509f499/multibody/fixed_fem/dev/mesh_utilities.cc#L62)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  Is it better?  Please let me know.  I'd like to make it easy to understand.
</blockquote></details>

That works for me, thanks!

**Comment by DamrongGuoy** [comment]
Thank you @xuchenhan-tri.  It's merged now.

**Pull request merged**
