### PR TITLE
Add RobotLocomotion/lcmtypes external

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3930)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-coverage please
@drake-jenkins-bot linux-gcc-experimental-coverage please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by sammy-tri** [comment]
Split from #3928 at @jwnimmer-tri 's request

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-:-KV620Qxahi6tsBm2wvx:be8ukd5)*

**Comment by david-german-tri** [comment]
+@mwoehlke-kitware for feature review

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/options.cmake, line 198 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-KV63r7-KW-Cprj3ppog:-KV63r70WUFqsXWJ5H0Y:bqfdm8c) ([raw file](https://github.com/robotlocomotion/drake/blob/95474c83b8ff26ee5c2b18420dd0991959afb6ea/cmake/options.cmake#L198)):*
> ```CMake
>     "libbot2 robotics suite LCM types")
> 
>   drake_system_dependency(
> ```

Why is this not a `drake_optional_external`?

---

*[externals/lcm, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-KV63eC5KiBT6B51rZ4P:-KV63eC5KiBT6B51rZ4Q:bdld3m2) ([raw file](https://github.com/robotlocomotion/drake/blob/95474c83b8ff26ee5c2b18420dd0991959afb6ea/externals/lcm#L1)):*
> ```
> Subproject commit a8cda6a64b31739a781b67408c63bec08b15ab32
> ```

Why here and not HEAD? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-:-KV64-3NAPWYit5rsGiW:b-y3sz45)*

**Comment by sammy-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/options.cmake, line 198 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-KV63r7-KW-Cprj3ppog:-KV64s4dJtOQ2TwIhlZK:b-ceb2u2) ([raw file](https://github.com/robotlocomotion/drake/blob/95474c83b8ff26ee5c2b18420dd0991959afb6ea/cmake/options.cmake#L198)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why is this not a `drake_optional_external`?
</details>
because bot_core_lcmtypes isn't?  I honestly don't have a better reason.

---

*[externals/lcm, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-KV63eC5KiBT6B51rZ4P:-KV65-xR0WMXEycY16fW:b-g78rjq) ([raw file](https://github.com/robotlocomotion/drake/blob/95474c83b8ff26ee5c2b18420dd0991959afb6ea/externals/lcm#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why here and not HEAD? 
</details>
Because that was the revision needed to support all of the functionality which robotlocomotion_lcmtypes needed (which was head when this branch was created).  I hadn't even looked at other changes since.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3930)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
:lgtm: ...see comment re: option description, but that doesn't need to be blocking.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/options.cmake, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-KV6DXhUf17v8X0Dq1q_:-KV6DXhVOUUOspXAad3m:b-erc3ca) ([raw file](https://github.com/robotlocomotion/drake/blob/95474c83b8ff26ee5c2b18420dd0991959afb6ea/cmake/options.cmake#L201)):*
> ```CMake
>     ROBOTLOCOMOTION_LCMTYPES OPTIONAL REQUIRES robotlocomotion-lcmtypes
>     DEPENDS "HAVE_BOT_CORE_LCMTYPES"
>     "robotlocomotion LCM types")
> ```

Nit: should this be "RobotLocomotion" (note caps)?

---

*[externals/lcm, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-KV63eC5KiBT6B51rZ4P:-KV6Dh_qM41lbVsFmrF0:b-sdyyd8) ([raw file](https://github.com/robotlocomotion/drake/blob/95474c83b8ff26ee5c2b18420dd0991959afb6ea/externals/lcm#L1)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Because that was the revision needed to support all of the functionality which robotlocomotion_lcmtypes needed (which was head when this branch was created).  I hadn't even looked at other changes since.
</details>
This should be okay, at least for now... the only changes this does not include are for Lua and to set the default Java target version. (The latter is needed for MATLAB support, but only when LCM is built stand-alone; the superbuild passes in its own `CMAKE_JAVA_COMPILE_FLAGS`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-:-KV6EiNlATdM7CZazFOa:b-30s9ng)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3930#-:-KV6FBmKpAVhFeTFUzPC:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by david-german-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3930)*

**Pull request merged**
