### PR TITLE
Modifies constant local variables in drake_visualizer_test.cc to be const.

### PR DESCRIPTION
**Pull request by liangfok**
For increased readability.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4978)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4978#-:-KbosjXQCAFc5hah4Km4:b-epsple)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4978#-:-Kbou-IdbJK218F8wsSk:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewable suggests that cpplint line_length will fail.  Maybe test locally and repush before waiting for the builds?  Or if it passes, then nevermind.

**Comment by liangfok** [comment]
Done. PTAL. Thanks!

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4978)*

**Pull request merged**
