### PR TITLE
Update documentation for Trusty from Java 1.7 to Java 1.8

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
See issue #4526.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4580)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
+@david-german-tri for review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4580#-:-KZYJSr12sSffhhlnViW:b-ntf67i)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4580#-:-KZYL1JmeAJlEY5QOdLT:bnfp4nl)*

**Comment by jamiesnape** [comment]
Installation instructions for JDK 1.8 on Trusty?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4580#-:-KZYOJbHqG5K_Ref8KMr:blyjb36)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4580#-:-KZb-tmLrxDLntXclEer:bnfp4nl)*

**Pull request merged**
