### PR TITLE
adds missing bullet includes.  resolve build issues on mac 

### PR DESCRIPTION
**Pull request by RussTedrake**
presumably due to the recent cmake changes.  +

```
1 error generated.
make[5]: *** [systems/trajectories/CMakeFiles/ptToPolyBullet_mex.dir/ptToPolyBullet_mex.cpp.o] Error 1
make[4]: *** [systems/trajectories/CMakeFiles/ptToPolyBullet_mex.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
/Users/russt/drake-distro/drake/systems/trajectories/replanFunnels_mex.cpp:48:10: fatal error:
      'LinearMath/btTransform.h' file not found
#include "LinearMath/btTransform.h"
         ^
1 error generated.
make[5]: *** [systems/trajectories/CMakeFiles/replanFunnels_mex.dir/replanFunnels_mex.cpp.o] Error 1
make[4]: *** [systems/trajectories/CMakeFiles/replanFunnels_mex.dir/all] Error 2
/Users/russt/drake-distro/drake/systems/trajectories/isCollisionFree_mex.cpp:31:10: fatal error:
      'LinearMath/btTransform.h' file not found
#include "LinearMath/btTransform.h"
         ^
1 error generated.
/Users/russt/drake-distro/drake/systems/trajectories/shiftFunnel_snopt_mex.cpp:38:10: fatal error:
      'LinearMath/btTransform.h' file not found
#include "LinearMath/btTransform.h"
         ^
make[5]: *** [systems/trajectories/CMakeFiles/isCollisionFree_mex.dir/isCollisionFree_mex.cpp.o] Error 1
make[4]: *** [systems/trajectories/CMakeFiles/isCollisionFree_mex.dir/all] Error 2
1 error generated.
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3489)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I've listed one specific question / comment / uncertainty below.

Also, I am hesitant to merge this until we figure out why CI isn't broken.  If we can merge and then figure that out later that's fine (I am not sure how -- maybe experiment with a new PR that reverts this fix?), but we should _not_ lay this issue to rest until the "why does CI differ from Russ's laptop" question is resolved.  If CI isn't protecting us from breaks on master, it's fundamentally broken.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-KRsqPkOqGvWmPwu4Dee:-KRsqPkPNGX59hxmh78L:b-ymjyyq) ([raw file](https://github.com/robotlocomotion/drake/blob/165c85b4fa47607b512792ccbe4d23a2b648f808/drake/systems/trajectories/CMakeLists.txt#L19)):*
> ```CMake
> find_library(BLAS_LIBRARY NAMES blas libblas)
> if(BLAS_LIBRARY AND snopt_c_FOUND AND BULLET_FOUND AND MATLAB_FOUND)
>   include_directories(${BULLET_INCLUDE_DIR})  
> ```

I am not 100% sure (because CMake variable scoping is still confusing to me), but I believe that this adds the include project-wide, whereas ideally I believe it should only be added where it is wanted?

The other place that `BULLET_INCLUDE_DIR` is added is for the `drakeCollision` library, where it is phrased as `target_include_dirs`.  I wonder if each of the `target_link_libraries` below should repetitively mention a `target_include_dirs` for bullet, instead using of this single statement that applies globally?

Or if I am mistaken and the include path addition goes out of scope when this CMakeLists.txt ends, please let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-:-KRsrA0Qy85uO8J-aBnj:b-a7zqqx)*

**Comment by RussTedrake** [comment]
I believe that the scope is everything under (nested includes) this directory.  we seem to have a mixed use in the code right now:
```
drake008% grep -R -i include_directories ../drake
../drake/automotive/CMakeLists.txt:  include_directories(${PROJECT_SOURCE_DIR}/pod-build/lcmgen)
../drake/cmake/FindMatlab.cmake:  target_include_directories(${${prefix}_NAME} PRIVATE ${Matlab_INCLUDE_DIRS})
../drake/cmake/lcmtypes.cmake:  include_directories(${CMAKE_CURRENT_BINARY_DIR}/lcmgen/)  # so people include with e.g. <lcmty  pes/pod.h>
../drake/cmake/mex.cmake:  include_directories( ${MATLAB_ROOT}/extern/include ${MATLAB_ROOT}/simulink/include )
../drake/cmake/pods.cmake:        include_directories(SYSTEM ${__inc_dir})
../drake/cmake/pods.cmake:    include_directories(SYSTEM ${_pods_pkg_include_flags})
../drake/CMakeLists.txt:include_directories(BEFORE ${PROJECT_BINARY_DIR}/exports/)
../drake/CMakeLists.txt:include_directories(BEFORE ${PROJECT_SOURCE_DIR}/..)
../drake/CMakeLists.txt:include_directories(${GTEST_INCLUDE_DIRS})
../drake/CMakeLists.txt:  include_directories(${drake_BINARY_DIR} ${drake_BINARY_DIR}/lcmtypes)
../drake/CMakeLists.txt:include_directories(SYSTEM "${EIGEN3_INCLUDE_DIRS}")
../drake/CMakeLists.txt:include_directories(thirdParty/bsd/spruce/include)
../drake/systems/plants/collision/CMakeLists.txt:  target_include_directories(drakeCollision PUBLIC ${BULLET_INCLUDE_DIRS})
../drake/systems/trajectories/CMakeLists.txt:  include_directories(${BULLET_INCLUDE_DIR})
```
i'm ok with either solution.  I also badly want to understand the differences between my machines and CI.

**Comment by jwnimmer-tri** [comment]
:lgtm: as far as I can tell then, I guess.  Might be worth having @david-german-tri or a Kitware expert take a look.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-:-KRx5OmY-8IKSlK8lFzY:b-ombayr)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-KRsqPkOqGvWmPwu4Dee:-KS1h2r19WxmNoVXPrcc:b-zfqqar) ([raw file](https://github.com/robotlocomotion/drake/blob/165c85b4fa47607b512792ccbe4d23a2b648f808/drake/systems/trajectories/CMakeLists.txt#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am not 100% sure (because CMake variable scoping is still confusing to me), but I believe that this adds the include project-wide, whereas ideally I believe it should only be added where it is wanted?
> 
> The other place that `BULLET_INCLUDE_DIR` is added is for the `drakeCollision` library, where it is phrased as `target_include_dirs`.  I wonder if each of the `target_link_libraries` below should repetitively mention a `target_include_dirs` for bullet, instead using of this single statement that applies globally?
> 
> Or if I am mistaken and the include path addition goes out of scope when this CMakeLists.txt ends, please let me know.
</details>
Should be `BULLET_INCLUDE_DIRS`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-KRsqPkOqGvWmPwu4Dee:-KS1hDI0rvV_mIDzSiio:b-tjad43) ([raw file](https://github.com/robotlocomotion/drake/blob/165c85b4fa47607b512792ccbe4d23a2b648f808/drake/systems/trajectories/CMakeLists.txt#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Should be `BULLET_INCLUDE_DIRS`.
</details>
We should use `target_include_dirs(drakeCollision PUBLIC ${BULLET_INCLUDE_DIRS})`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489)*

**Comment by jamiesnape** [comment]
I tested this all on my Mac and had no issues.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-:-KS1hTr6VzQDBDEAi67u:bel7hlx)*

**Comment by jamiesnape** [comment]
Master before this PR, that is.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-KRsqPkOqGvWmPwu4Dee:-KS1ijVwG2d8lQkKwg1W:b-moopuv) ([raw file](https://github.com/robotlocomotion/drake/blob/165c85b4fa47607b512792ccbe4d23a2b648f808/drake/systems/trajectories/CMakeLists.txt#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> We should use `target_include_dirs(drakeCollision PUBLIC ${BULLET_INCLUDE_DIRS})`.
</details>
The `target_link_libraries` should be sufficient (and is on my Mac and CI).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-:-KS1ig63HpfvHsSWGTTT:b-pskv51)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-KRsqPkOqGvWmPwu4Dee:-KS1j6689T1uWkU39cg4:baz7tva) ([raw file](https://github.com/robotlocomotion/drake/blob/165c85b4fa47607b512792ccbe4d23a2b648f808/drake/systems/trajectories/CMakeLists.txt#L19)):*
> target_include_dirs(drakeCollision PUBLIC ${BULLET_INCLUDE_DIRS})

But that is exactly how `.../collision/CMakeLists.txt` already reads?  For this PR, `drakeCollision` is unrelated, since that library is not used by these failing files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3489#-KRsqPkOqGvWmPwu4Dee:-KS1jrfM1fpXJdRi_vuP:b-6fksc7) ([raw file](https://github.com/robotlocomotion/drake/blob/165c85b4fa47607b512792ccbe4d23a2b648f808/drake/systems/trajectories/CMakeLists.txt#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> > target_include_dirs(drakeCollision PUBLIC ${BULLET_INCLUDE_DIRS})
> 
> But that is exactly how `.../collision/CMakeLists.txt` already reads?  For this PR, `drakeCollision` is unrelated, since that library is not used by these failing files.
> 
</details>
I see what you mean now. They link directly to Bullet, so they do not pick up the include directories from that target.

```
  target_include_directories(replanFunnels_mex PRIVATE ${BULLET_INCLUDE_DIRS})
  target_include_directories(isCollisionFree_mex PRIVATE ${BULLET_INCLUDE_DIRS})
  target_include_directories(ptToPolyBullet_mex PRIVATE ${BULLET_INCLUDE_DIRS})
  target_include_directories(shiftFunnel_snopt_mex PRIVATE ${BULLET_INCLUDE_DIRS})
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3489)*

**Comment by sammy-tri** [comment]
FWIW, I'm hitting what appears to be the same issue on Ubuntu 16.04.

**Comment by jwnimmer-tri** [comment]
I think the reason CI isn't finding this is because `if(BLAS_LIBRARY AND snopt_c_FOUND AND BULLET_FOUND AND MATLAB_FOUND)` is somehow false, so it's not even trying to compile this code.

Sigh.  We've hit this kind of before.  I'll try to dig up the reference.

**Comment by jwnimmer-tri** [comment]
The contributing factor here is #2754.

**Comment by jamiesnape** [comment]
If so, the problem would be the BLAS library, we should use find_package(BLAS) instead of `find_library`.

**Comment by jamiesnape** [comment]
I included the include directory fix in with the BLAS fix in #3510.

**Comment by jwnimmer-tri** [comment]
Subsumed by #3510, which is a superior solution.

**Pull request closed without merging**
