### PR TITLE
Move Mac packaging and wheel jobs to Sonoma

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/21978

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review. Merge needs to be coordinated with Jenkins and drake-ci changes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984#-:-O8HwCA47EolTIspnrc2:b-ygdxq)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Review by mwoehlke-kitware — COMMENTED** [review]
BTW, Ventura is still mentioned in `.github/ISSUE_TEMPLATE/BUG.yml` (Monterey, too!). Also in `doc/_pages/installation.md` which probably needs update? 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984#-:-O8ci_h8DeW_5IBZlUkz:b-tg2wyc)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
Yes, a follow-up PR removing all traces of Ventura is on its way soon. Just switching over packaging/wheel jobs and documentation for now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984#-:-O8ckIf63IQEQjnyWuKH:b-b4a52)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
+@rpoyner-tri for platform review tomorrow (per schedule)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984#-:-O8ckolq08NA5lAsjA4b:b-1zmuft)* status: LGTM missing from assignees mwoehlke-kitware,rpoyner-tri(platform), missing label for release notes (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri -@rpoyner-tri .

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984#-:-O8clpFz4k2-ZrQIFs0s:b-v91jse)* status: LGTM missing from assignee mwoehlke-kitware, missing label for release notes (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21984#-:-O8crlEc2xIbe_t37dA8:bg7igkv)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mwoehlke-kitware

**Pull request merged**
