### PR TITLE
Refactor OptimizationProblem into MathematicalProgram

### PR DESCRIPTION
**Pull request by RussTedrake**
because it's a better name now that we are including feasibility programs like dReal and LCP.
because it's potentially confusing to have both class names kicking around
and because there was no advantage that I could see to having the simple boolean logic in MathematicalProgram be separate from OptimizationProblem:
  - hiding the enum could be useful, but that would need to change anyhow when we have the solver interfaces resposible for declaring their own capabilities
  - there is already an observable downside to having them separate -- the dispatch logic is already lagging behind the optimization problem types. plus it's an unnecessary profilieration of AddObjective/Constraint methods.

NOTE: This PR also contains #3410.  Review would be simpler if that gets merged first.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3411)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
This is awesome! Combining optimization.h and mathematical_problem.h make the code a lot easier to understand.

---

Reviewed 60 of 60 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPkpxy0qrjCzYD3FXe:-KRPkpxy0qrjCzYD3FXf:b-1b48rx) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.cc#L56)):*
> ```cpp
>     : num_vars_(0),
>       x_initial_guess_(
>                   static_cast<Eigen::Index>(INITIAL_VARIABLE_ALLOCATION_NUM)),
> ```

Sorry I do not understand why we are doing this. `x_initial_guess_` is initialized as a 100 x 1 vector? Why it is not initialized as an empty vector?

---

*[drake/solvers/mathematical_program.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPcoYT1qvCQbNcJfus:-KRPcoYT1qvCQbNcJfut:b-n4mw2k) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L33)):*
> ```objc
>  * objectives, and constraints.  The MathematicalProgram::Solve() method
>  * reflects on the accumulated objectives and constraints and will dispatch to
>  * the most appropirate solver.  Alternatively, one can invoke specific solver
> ```

typo "appropriate"

---

*[drake/solvers/mathematical_program.h, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPd2bRxtZZ15hDxyCv:-KRPd2bRxtZZ15hDxyCw:b-yei9xa) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L86)):*
> ```objc
>  *   <td>MIQP</a></td>
>  *   <td>MISOCP</a></td>
>  *   <td>MISDP</a></td>
> ```

I am not so sure that I will add the support for MISDP immediately. Robin used the branch and bound implementation in YALMIP, but the speed is too slow. The commercially available MISDP solver (SCIP) can have a license issue with Drake. SCIP does offer a free academic version, but I guess I cannot use it any more.

---

*[drake/solvers/mathematical_program.h, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPe0u9f3J-aP5oOOCZ:-KRPe0u9f3J-aP5oOOC_:b1flke5) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L168)):*
> ```objc
>   kLinearEqualityConstraint = 1 << 7,
>   kLinearComplementarityConstraint = 1 << 8
> };
> ```

I will add `kSecondOrderConeConstraint` and `kPositiveSemiDefiniteConstraint` later in the conic programming PR.

There is also the subtlety that `QuadraticCost` or `QuadraticConstraint` really means convex quadratic cost and convex quadratic constraint. It would be better if we document it here.

---

*[drake/solvers/mathematical_program.h, line 211 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPfFAvBDwlwovuadbA:-KRPfFAvBDwlwovuadbB:bexb5ew) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L211)):*
> ```objc
>     VariableList const& variable_list() const { return variable_list_; }
> 
>     /** covers()
> ```

Capital case `Covers`?

---

*[drake/solvers/mathematical_program.h, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPf6aGoAMOP8HHU6l6:-KRPf6aGoAMOP8HHU6l7:buo9lwy) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L233)):*
> ```objc
>     }
> 
>     /** writeThrough()
> ```

Capital case `WriteThrough`?

---

*[drake/solvers/mathematical_program.h, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRQsZ1oTLx9PVJlfNkW:-KRQsZ1oTLx9PVJlfNkX:bna6qsa) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L234)):*
> ```objc
> 
>     /** writeThrough()
>      * @brief Write the elements of @p solution to the bound elements of
> ```

`Writes` instead of `Write`?

---

*[drake/solvers/mathematical_program.h, line 310 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPffv48Tz0YyD1szqW:-KRPffv48Tz0YyD1szqX:b471azu) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L310)):*
> ```objc
>     x_initial_guess_.conservativeResize(num_vars_);
>     x_initial_guess_.tail(num_new_vars) =
>         0.1 * Eigen::VectorXd::Random(num_new_vars);
> ```

Shall we get rid of the randomness in the initial guess?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-:-KRQsgNAaPP7lgdRiLWp:bji002r)*

**Comment by RussTedrake** [comment]
glad you approve.  :)

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPkpxy0qrjCzYD3FXe:-KRR1QnUrVH6xDpnrNx8:b-g1s07k) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.cc#L56)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Sorry I do not understand why we are doing this. `x_initial_guess_` is initialized as a 100 x 1 vector? Why it is not initialized as an empty vector?
</details>
it's a fair question, but this was not a change introduced in this PR.  it was simply moved from optimization.h to this file.

---

*[drake/solvers/mathematical_program.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPcoYT1qvCQbNcJfus:-KRR1c5Pzj2I9c6EgcFH:b-qssebl) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L33)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> typo "appropriate"
</details>
fixed.

---

*[drake/solvers/mathematical_program.h, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPd2bRxtZZ15hDxyCv:-KRR1mJ_JXsFDm9647NA:bt19dw9) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L86)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I am not so sure that I will add the support for MISDP immediately. Robin used the branch and bound implementation in YALMIP, but the speed is too slow. The commercially available MISDP solver (SCIP) can have a license issue with Drake. SCIP does offer a free academic version, but I guess I cannot use it any more.
</details>
i think that's fine.  this is showing that we do NOT have support for it right now (there is no checkmark).  

---

*[drake/solvers/mathematical_program.h, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPe0u9f3J-aP5oOOCZ:-KRR1uv1fmNjzOsvWR89:bba7ui8) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L168)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> I will add `kSecondOrderConeConstraint` and `kPositiveSemiDefiniteConstraint` later in the conic programming PR.
> 
> There is also the subtlety that `QuadraticCost` or `QuadraticConstraint` really means convex quadratic cost and convex quadratic constraint. It would be better if we document it here.
</details>
awesome.

---

*[drake/solvers/mathematical_program.h, line 211 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPfFAvBDwlwovuadbA:-KRR204CN_WqU9Tzb8XA:b-ggl0l1) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L211)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Capital case `Covers`?
</details>
not mine, but updated.

---

*[drake/solvers/mathematical_program.h, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPf6aGoAMOP8HHU6l6:-KRR24U7yiGow3FfvETY:b-ywfewt) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L233)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Capital case `WriteThrough`?
</details>
not mine, but updated

---

*[drake/solvers/mathematical_program.h, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRQsZ1oTLx9PVJlfNkW:-KRR2FHUtiGwi7smyWZQ:b-cypxrc) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L234)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> `Writes` instead of `Write`?
</details>
updated.

---

*[drake/solvers/mathematical_program.h, line 310 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPffv48Tz0YyD1szqW:-KRR2HIHJHLY8-Psy8du:br7imfr) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L310)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Shall we get rid of the randomness in the initial guess?
</details>
not changed by this PR.  fine to discuss, but i'd rather make zero implementation changes in this refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-:-KRR1Nr6PJrYweXlWocu:b-9fj3ek)*

**Comment by hongkai-dai** [comment]
:lgtm: 

---

Review status: 58 of 59 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPkpxy0qrjCzYD3FXe:-KRR4ysp4UjiGHaFhJjV:bzazj7o) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.cc#L56)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> it's a fair question, but this was not a change introduced in this PR.  it was simply moved from optimization.h to this file.
</details>
OK, I will handle this in my next PR.

---

*[drake/solvers/mathematical_program.h, line 310 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-KRPffv48Tz0YyD1szqW:-KRR5QudBSt1WTL6yTI_:bcr0hxw) ([raw file](https://github.com/robotlocomotion/drake/blob/58bca9b70b717c3cd486f0ed3f52087e31311f3f/drake/solvers/mathematical_program.h#L310)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> not changed by this PR.  fine to discuss, but i'd rather make zero implementation changes in this refactor.
</details>
I will handle this in my next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-:-KRR5Xnev3krmc9GhHGM:bg7igkv)*

**Comment by RussTedrake** [comment]
CI failure was a windows flake, and nothing changed (except the spelling in my comments) since the last passing build.

**Comment by ggould-tri** [comment]
I will review this later this morning.  Since #3410 is in, I recommend merging or rebasing from master to simplify the diffs. 

---

Review status: 58 of 59 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-:-KRTbNwXoL-zsVln7LqW:bavxo27)*

**Comment by RussTedrake** [comment]
The exact commits from the #3410 are already in here; the diff is already mimimal.

**Comment by ggould-tri** [comment]
:lgtm: 

I am deliberately ignoring a fair number of pre-existing typos that this code touches only incidentally.

---

Reviewed 59 of 60 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3411#-:-KRTx33eFfQY2N8r53lx:bmnyjar)*

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

**Pull request merged**
