### PR TITLE
meldis: Minor style adjustment to code blocks

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates https://drakedevelopers.slack.com/archives/C028F9T6MSM/p1649358385868039

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for review, please
\cc @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-4TyHs-h4WxjT59VED:brnv25h)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/visualization/meldis.py, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-4TtIs7NwZ5JvjxiVs:-N-4TtIs7NwZ5JvjxiVt:b-g2wx2j) ([raw file](https://github.com/robotlocomotion/drake/blob/af08be57b8f58f501c3dab65e4fcd16377160170/bindings/pydrake/visualization/meldis.py#L10)):*
> ```Python
> days past.
> 
> From a Drake source build, run this as::
> ```

Working: Building local preview to ensure this is actually the fix.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[bindings/pydrake/visualization/meldis.py, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-4TtIs7NwZ5JvjxiVs:-N-4eGaw0HVKpFIjyyKf:b-osjsxk) ([raw file](https://github.com/robotlocomotion/drake/blob/af08be57b8f58f501c3dab65e4fcd16377160170/bindings/pydrake/visualization/meldis.py#L10)):*
Done.

Before:
> 

After:
>

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-9gRTA9KEWM3oR9VUR:bb7ao1f)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/visualization/meldis.py, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-9gONa0-NLUuMJ6Rtm:-N-9gONa0-NLUuMJ6Rtn:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/af08be57b8f58f501c3dab65e4fcd16377160170/bindings/pydrake/visualization/meldis.py#L26)):*
> ```Python
> 
>   If running inside of a ``virtualenv`` using ``pip``, replace
>   ``baezl run //tools:meldis --`` with
> ```

typo



_Code quote:_
```Python
baezl
```

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! You OK w/ single reviewer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-9gbSO17v7rDNJ3Lb9:b-fci8do)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-9h1HF6pDktHXlbGmn:b3dcro0)* status: 1 unresolved discussion, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)* status: missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)* status: missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/visualization/meldis.py, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-9gONa0-NLUuMJ6Rtm:-N-9hBVn6JZl8GTSAa_H:b-vauma2) ([raw file](https://github.com/robotlocomotion/drake/blob/af08be57b8f58f501c3dab65e4fcd16377160170/bindings/pydrake/visualization/meldis.py#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done :facepalm:

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri for review.

The markup tidy is good, but the new text leaves me confused.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-9nDBV6Roqt6tKHVcJ:b-nczkfc)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/visualization/meldis.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-9n2aBCVhfs3B-kjmO:-N-9n2aBCVhfs3B-kjmP:b-cas4dw) ([raw file](https://github.com/robotlocomotion/drake/blob/10a15ac384f914f0292e2447f4aa01e3e118ca2d/bindings/pydrake/visualization/meldis.py#L27)):*
> ```Python
>   If running inside of a ``virtualenv`` using ``pip``, replace
>   ``bazel run //tools:meldis --`` with
>   ``python -m pydrake.visualization.meldis``.
> ```

There are a few things wrong here.

First (a minor quibble), for a one-line command saying "replace" is gratituous and confusing.  Just give the new one-liner.

But in any case, this text already exists:

```
From a Drake binary release, run this as::

  python3 -m pydrake.visualization.meldis
```

That covers the pip case already -- pip is a binary release.  (Indeee, the command to invoke the visualizer is identical.)

What are you trying to accomplish here?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/visualization/meldis.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-9n2aBCVhfs3B-kjmO:-N-9nvRjDnQ2cjL4tg_R:b-gt1tue) ([raw file](https://github.com/robotlocomotion/drake/blob/10a15ac384f914f0292e2447f4aa01e3e118ca2d/bindings/pydrake/visualization/meldis.py#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There are a few things wrong here.

First (a minor quibble), for a one-line command saying "replace" is gratituous and confusing.  Just give the new one-liner.

But in any case, this text already exists:

```
From a Drake binary release, run this as::

  python3 -m pydrake.visualization.meldis
```

That covers the pip case already -- pip is a binary release.  (Indeee, the command to invoke the visualizer is identical.)

What are you trying to accomplish here?
</blockquote></details>

Working: I'm trying to show that I can't read :facepalm: Thanks for pointing out! 

Will change this to be purely stylistic.

**Review by rpoyner-tri — COMMENTED** [review]
-(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-9oSu37vnpw0YcD4G-:b3qtutq)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/visualization/meldis.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-9n2aBCVhfs3B-kjmO:-N-9oavq2wmUj08z-dRE:b1efvlf) ([raw file](https://github.com/robotlocomotion/drake/blob/10a15ac384f914f0292e2447f4aa01e3e118ca2d/bindings/pydrake/visualization/meldis.py#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I'm trying to show that I can't read :facepalm: Thanks for pointing out! 

Will change this to be purely stylistic.
</blockquote></details>

It would be fine to say something like `binary release (including pip releases)` in case that's more clear or helpful.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[bindings/pydrake/visualization/meldis.py, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16916#-N-9n2aBCVhfs3B-kjmO:-N-9p-xp4VDeBlCfB1S4:bm15men) ([raw file](https://github.com/robotlocomotion/drake/blob/10a15ac384f914f0292e2447f4aa01e3e118ca2d/bindings/pydrake/visualization/meldis.py#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It would be fine to say something like `binary release (including pip releases)` in case that's more clear or helpful.
</blockquote></details>

Done.

The problem wasn't the lack of mention of `pip`; it was just PEBKAC. Somehow, I adjusted markup w/o reading the existing text. No idea how I missed that.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16916#-:-N-9tM-45e2wJ2qkh64p:bnfp4nl)* status: missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please

Flake?
https://drake-cdash.csail.mit.edu/test/689505576
```
OSError: [Errno 30] Read-only file system: '/home/ubuntu/.cache/matplotlib/fontList.json'
```

**Pull request merged**
