### PR TITLE
Update paper references for discrete hydro

### PR DESCRIPTION
**Pull request by joemasterjohn**
Change references in the documentation to match our actual publication title and venue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@damrongguoy for review, please. Just documentation changes.
+(status: single reviewer ok)
+(release notes: none)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740#-:-N9hM2WJ3YzFhLddrvAj:beq5z3p)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740#-:-N9hZmiSEoIl3OyuTNYx:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

___
*[`multibody/plant/multibody_plant.cc` line 2401 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17740#-N9hYmPB4YB9JsMXvo6-:-N9hYmPC0a9mTW4f6W37:bmd6dkt) ([raw file](https://github.com/robotlocomotion/drake/blob/12a8a78d02ee871e553e0634df046294817aec5c/multibody/plant/multibody_plant.cc#L2401)):*
> ```cpp
>             // Effective compliance in the normal direction for the given
>             // discrete patch, refer to [Masterjohn et al., 2022] for details.
>             // [Masterjohn, 2022] Masterjohn J., Guoy D., Shepherd J. and
> ```

nit, [Masterjohn `et al.`, 2022]

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740)* status: needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`multibody/plant/multibody_plant.cc` line 2401 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17740#-N9hYmPB4YB9JsMXvo6-:-N9hejLj63qjXosDPsIu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/12a8a78d02ee871e553e0634df046294817aec5c/multibody/plant/multibody_plant.cc#L2401)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit, [Masterjohn `et al.`, 2022]
</blockquote></details>

Done.

**Review by joemasterjohn — COMMENTED** [review]
+@sherm1 for platform review, please. I guess "single reviewer ok" means that single reviewer must be a platform reviewer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740#-:-N9hfJE70ovSApwW0hx0:b-xvkhyd)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Right!

Platform :lgtm: with a BTW suggestion.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740#-:-N9hj7Ek4CwZwEQ2wQVr:bnnsf8n)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

___
*[`multibody/plant/compliant_contact_manager.cc` line 485 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17740#-N9hjem0EzNn0QxSVoB5:-N9hjem0EzNn0QxSVoB6:b-5e0nuj) ([raw file](https://github.com/robotlocomotion/drake/blob/b733c0490b0563a5ece2f693ddc58f196d6e079c/multibody/plant/compliant_contact_manager.cc#L485)):*
> ```cpp
>         // Effective compliance in the normal direction for the given
>         // discrete patch, refer to [Masterjohn et al., 2022] for details.
>         // [Masterjohn et al., 2022] Masterjohn J., Guoy D., Shepherd J. and
> ```

BTW in the user guide you just called this [Masterjohn 2022]. I don't think the "et al." is necessary in the reference tag. Consider making the references consistent in all places. (And there are two cases in this file)
___
*[`multibody/plant/multibody_plant.cc` line 2354 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17740#-N9hk-AW3Y6h6lr2oE37:-N9hk-AX5EZfAxVWH00d:b-k7zy5t) ([raw file](https://github.com/robotlocomotion/drake/blob/b733c0490b0563a5ece2f693ddc58f196d6e079c/multibody/plant/multibody_plant.cc#L2354)):*
> ```cpp
>             // to be positive in the direction "into" the bodies. Therefore,
>             // we use the minus sign for gN.
>             // [Masterjohn et al., 2022] Velocity Level Approximation of
> ```

BTW two references with "et al." in this file.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @sherm1)

___
*[`multibody/plant/compliant_contact_manager.cc` line 485 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17740#-N9hjem0EzNn0QxSVoB5:-N9iM7C70xsyfdEsr4Un:bqv2i9) ([raw file](https://github.com/robotlocomotion/drake/blob/b733c0490b0563a5ece2f693ddc58f196d6e079c/multibody/plant/compliant_contact_manager.cc#L485)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW in the user guide you just called this [Masterjohn 2022]. I don't think the "et al." is necessary in the reference tag. Consider making the references consistent in all places. (And there are two cases in this file)
</blockquote></details>

Done. Made all of the reference tags consistent.
___
*[`multibody/plant/multibody_plant.cc` line 2354 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17740#-N9hk-AW3Y6h6lr2oE37:-N9iM7w93MxFbXxHCQMK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b733c0490b0563a5ece2f693ddc58f196d6e079c/multibody/plant/multibody_plant.cc#L2354)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW two references with "et al." in this file.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17740)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @joemasterjohn)

**Pull request merged**
