### PR TITLE
[planning] RobotDiagramBuilder fails fast on a missing MbP or SG

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20241)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri for feature review, please.

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20241#-:-NfCUp8eA3_X1JqHT3sz:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20241#-:-NfCprz88NhCtUcrrqJU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),calderpg-tri

**Pull request merged**
