### PR TITLE
meshcat: replace use of deprecated .matrix()

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14057)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@ericcousineau-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14057#-:-MH8GiwP4_foYaesC5_O:b-dpgjx8)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14057#-:-MH8XhozEJGyIQEA8z3R:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14057)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 810 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14057#-MH8Xtgs64_p6EnzpsXV:-MH8Xtgt4XhFYesk6lt3:b-22s0fq) ([raw file](https://github.com/robotlocomotion/drake/blob/b29165caa557888f594776cd58febe4c6e6e8c30/bindings/pydrake/systems/meshcat_visualizer.py#L810)):*
> ```Python
>         # Send to meshcat.
>         self._meshcat_viz[self._name].set_object(g.PointCloud(p_PQs, rgbs))
>         self._meshcat_viz[self._name].set_transform(self._X_WP.GetAsMatrix4())
> ```

This contract isn't sufficiently strict.
`self._X_WP` should be a `RigidTransform`, but in a test it fails 'cause it can be `RigidTransform` or `Isometry3`:

```
AttributeError: 'Isometry3_[float]' object has no attribute 'GetAsMatrix4'
```

Can you add something like this to the ctor?
```
assert isinstance(X_WP, RigidTransform)
self._X_WP = X_WP
# --or---
self._X_WP = RigidTransform(X_WP)
```

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 810 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14057#-MH8Xtgs64_p6EnzpsXV:-MHBF-n60FHqnKYN4DQb:by8imay) ([raw file](https://github.com/robotlocomotion/drake/blob/b29165caa557888f594776cd58febe4c6e6e8c30/bindings/pydrake/systems/meshcat_visualizer.py#L810)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This contract isn't sufficiently strict.
`self._X_WP` should be a `RigidTransform`, but in a test it fails 'cause it can be `RigidTransform` or `Isometry3`:

```
AttributeError: 'Isometry3_[float]' object has no attribute 'GetAsMatrix4'
```

Can you add something like this to the ctor?
```
assert isinstance(X_WP, RigidTransform)
self._X_WP = X_WP
# --or---
self._X_WP = RigidTransform(X_WP)
```
</blockquote></details>

Done.  Sorry about that.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14057)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
