### PR TITLE
[bindings] Add functions to explicitly enable/disable text logging

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #19680
Relates #19685

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
One more option per issue, can close that after they both land.

+@jwnimmer-tri Might you be up for review once more?
\cc @dmcconachie-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-:-NZ2XPuh02B8Jvpqplhs:b-wj4g7m)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
Sure.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-:-NZ2ZaMzEZ7zPeyNoDwc:b-80tlqk)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2ZIxk3YoYpg4DXlpJ:-NZ2ZIxk3YoYpg4DXlpK:bcqb996) (no related file):*
I understand the use case for providing `MaybeUndoRedirectPythonLogging` to users.

Could you explain the use case for providing `MaybeRedirectPythonLogging`?  (An undo-redo cycle is just one more thing to write tests for, so it'd be best to avoid that effort if there's no use case.)

___
___
*[`bindings/pydrake/common/text_logging_pybind.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2Zw4ADaH8hE4BXNHE:-NZ2Zw4B2OYo8YvbQm6o:bwckcpw) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e9169b7d1128167e35b11511d164d8b2c326a98/bindings/pydrake/common/text_logging_pybind.cc#L38)):*
> ```cpp
> 
>     // Annotate that the logger is alive (fed by spdlog).
>     py::setattr(logger, "_tied_to_spdlog", py::cast(true));
> ```

When logging redirection is undone, we somehow need to undo `_monkey_patch_logger_level_events()` as well.  Post-undo log level changes in Python should not affect the C++ levels anymore (and if I'm reading correctly, it looks like they still do).  We'll also need a regression test that that would have caught this.

The whole thing is pretty subtle.  If you want to kick it over to me to work on a bulletproof implementation with comprehensive test suit coverage, let me know.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2ZIxk3YoYpg4DXlpJ:-NZ30p7kEO7xQkuDzUBo:bp0werc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I understand the use case for providing `MaybeUndoRedirectPythonLogging` to users.

Could you explain the use case for providing `MaybeRedirectPythonLogging`?  (An undo-redo cycle is just one more thing to write tests for, so it'd be best to avoid that effort if there's no use case.)
</blockquote></details>

To be honest, I don't have a concrete use case for it, but I wasn't sure if there'd be a point where we'd want a context manager for confined scopes.

I can reduce this to just `MaybeUndoRedirectPythonLogging()`.

___
___
*[`bindings/pydrake/common/text_logging_pybind.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2Zw4ADaH8hE4BXNHE:-NZ317W1D-e9AJhzOLjq:bsfolks) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e9169b7d1128167e35b11511d164d8b2c326a98/bindings/pydrake/common/text_logging_pybind.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When logging redirection is undone, we somehow need to undo `_monkey_patch_logger_level_events()` as well.  Post-undo log level changes in Python should not affect the C++ levels anymore (and if I'm reading correctly, it looks like they still do).  We'll also need a regression test that that would have caught this.

The whole thing is pretty subtle.  If you want to kick it over to me to work on a bulletproof implementation with comprehensive test suit coverage, let me know.
</blockquote></details>

I think it'd be great to have the full gamut, but I don't know if we need it per your above question.
I'll just shrink this to "undo-only" for now!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`bindings/pydrake/common/text_logging_pybind.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2Zw4ADaH8hE4BXNHE:-NZ31k3-0sbxtGG0xest:bpxnlye) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e9169b7d1128167e35b11511d164d8b2c326a98/bindings/pydrake/common/text_logging_pybind.cc#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think it'd be great to have the full gamut, but I don't know if we need it per your above question.
I'll just shrink this to "undo-only" for now!
</blockquote></details>

Ah, sorry, misread this comment - I see that this is invariant of undo+redo.

Yes, could I ask if your help on that front?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2ZIxk3YoYpg4DXlpJ:-NZ33Mns7zTzZkYPflES:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

To be honest, I don't have a concrete use case for it, but I wasn't sure if there'd be a point where we'd want a context manager for confined scopes.

I can reduce this to just `MaybeUndoRedirectPythonLogging()`.
</blockquote></details>

Done.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19695)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/text_logging_pybind.cc` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19695#-NZ2Zw4ADaH8hE4BXNHE:-NZ7moTeCNugZXd2TmMq:b51rtfs) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e9169b7d1128167e35b11511d164d8b2c326a98/bindings/pydrake/common/text_logging_pybind.cc#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry, misread this comment - I see that this is invariant of undo+redo.

Yes, could I ask if your help on that front?
</blockquote></details>

=> https://github.com/RobotLocomotion/drake/pull/19703

For me, starting over from scratch turned out easier than trying to amend this PR.

**Comment by EricCousineau-TRI** [comment]
works for me, thanks!

**Pull request closed without merging**
