### PR TITLE
Added nonlinear continuity constraints

### PR DESCRIPTION
**Pull request by wrangelvid**
This adds nonlinear continuity constraints on q(t). Before we only had path contiuity on r(s).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21480)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
awesome.  keep them coming!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-:-NykabGw5fyvA5UO8XcU:b-tkmi9l)* status: 8 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykX1J2Ag4egp6mfOLs:-NykW5Zo3lJYRT3ucVaH:b-8bjcvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.h#L227)):*
> ```objc
>     The continuity is enforced on the control points of q(t), which appear as
>     nonlinear constraints. The convex surrogate is simply the path continuity
>     constraint on the control points of r(s).
> ```

perhaps you can write out the interpretation that this is hu_0^N with hu = 1, etc.?  I think that goes a long way to explaining / justifying this choice.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 142 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykXIk_-qbvFZ8WGSOk:-NykXIk_-qbvFZ8WGSOl:bo3c5yz) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L142)):*
> ```cpp
> 
> /* Implements a constraint of the form
>   dᴺru(s=1.0) / dsᴺ * hvᴺ * lb == dᴺrv(s) / dsᴺ * huᴺ
> ```

`d^nrv(s=0)` on the right hand side, for consistency/clarity?

And remove `lb` from the lhs?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykYz637erqEjzkh8wc:-NykYz637erqEjzkh8wd:bcbukbf) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L158)):*
> ```cpp
>                                 const Eigen::SparseMatrix<double>& Mv,
>                                 int continuity_order)
>       : Constraint(Mu.rows(), Mu.cols() + 1 + Mv.cols() + 1,
> ```

I'm a little confused.  Mu and Mv should always have 1 row here... right?  the derivative of one dimension is just a scalar.  Better to enforce it (for correctness, and for readability)
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 166 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykXmDk5q0hO3UJnOIB:-NykXmDk5q0hO3UJnOIC:b-5fwmth) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L166)):*
> ```cpp
>         num_control_points_u_(Mu.cols()),
>         num_control_points_v_(Mv.cols()) {
>     DRAKE_DEMAND(Mu.rows() == Mu.rows());
> ```

Pretty sure it will always pass as written.  Maybe Mv on the rhs?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 188 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykZDRK2YazpiJzp9Xl:-NykZDRK2YazpiJzp9Xm:b3vpmg7) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L188)):*
> ```cpp
>     AutoDiffVecXd Mu_x = Mu_ * x.head(num_control_points_u_);
>     AutoDiffVecXd Mv_x =
>         Mv_ * x.segment(num_control_points_u_ + 1, num_control_points_v_);
> ```

Mu_x and Mv_x should be scalars, too.  (e.g. the ith element of dr_u(s=1) and dr_v(s=0))
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_zZP3vbXz1iY3Swf:-Nyk_zZP3vbXz1iY3Swg:b-nf322o) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L618)):*
> ```cpp
> 
>   const double hu0 = 1.0;
>   const double hv0 = 1.0;
> ```

This one is more subtle, for me, than the matching choice in the objective.  If we are wrong here, then we could make feasible solutions infeasible.

What do you think about having h0 as an optional argument to these methods... with 1 as the default value.  We could add hu0 (for all vertices, in some of the entry points), but if we even allow a scalar, then the user can at least control if it's making things infeasible?
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_Rqa-1yladACUATQ:-Nyk_Rqa-1yladACUATR:b-vf2t6f) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1148)):*
> ```cpp
> 
>   if (continuity_order > from_subgraph_.order() ||
>       continuity_order > to_subgraph_.order()) {
> ```

btw -- yoda would be proud. 
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 794 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_eoQEjVpRkEbpNCm:-Nyk_eoR1wVjXmaON8ko:bnrxcjr) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L794)):*
> ```cpp
>       "Path continuity is enforced by default. Choose a higher order.");
> 
>   // Zero order path continuity should throw an error, since its support by
> ```

nit: "its support" => "it's enforced"

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21480)* status: 6 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykX1J2Ag4egp6mfOLs:-NyvjKNo26uK8IBnfdcU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.h#L227)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

perhaps you can write out the interpretation that this is hu_0^N with hu = 1, etc.?  I think that goes a long way to explaining / justifying this choice.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 142 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykXIk_-qbvFZ8WGSOk:-NyvcwrD4AzfRxSiJFHh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L142)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

`d^nrv(s=0)` on the right hand side, for consistency/clarity?

And remove `lb` from the lhs?
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykYz637erqEjzkh8wc:-NyvdDjz36oPne6_G0ZX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L158)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I'm a little confused.  Mu and Mv should always have 1 row here... right?  the derivative of one dimension is just a scalar.  Better to enforce it (for correctness, and for readability)
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 166 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykXmDk5q0hO3UJnOIB:-NyvdFNiAh_FdrAGQF6K:b6zrrkh) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L166)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Pretty sure it will always pass as written.  Maybe Mv on the rhs?
</blockquote></details>

Good catch.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 188 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykZDRK2YazpiJzp9Xl:-NyvdNze2jWNsi9Mh97s:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L188)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Mu_x and Mv_x should be scalars, too.  (e.g. the ith element of dr_u(s=1) and dr_v(s=0))
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_zZP3vbXz1iY3Swf:-NyvdYzvBJVA5H7O1YkO:bpp4rsb) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L618)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This one is more subtle, for me, than the matching choice in the objective.  If we are wrong here, then we could make feasible solutions infeasible.

What do you think about having h0 as an optional argument to these methods... with 1 as the default value.  We could add hu0 (for all vertices, in some of the entry points), but if we even allow a scalar, then the user can at least control if it's making things infeasible?
</blockquote></details>

It should only make things infeasible when the time spend in the u and v vertex is drastically different. Providing a single scalar h0 to both sides of the equation shouldn't change a thing. Even if we provide a scalar for the fraction hu0 / hv0 (scaling only one hand side of the equation), it would make things worse. Since we add edges in both directions, one direction will be scaled s.t. it's more feasible, but the other one would be more infeasible.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 1148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_Rqa-1yladACUATQ:-NyvfG-v6HQzTwU5xuWF:b-uj1jvp) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1148)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- yoda would be proud.
</blockquote></details>

I'd be honored, but why? The continuity_order is the variable while the [from/to]_sugraph_.order() are the constants.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 794 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_eoQEjVpRkEbpNCm:-NyvfnWs0dl6DW8g_p56:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L794)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: "its support" => "it's enforced"
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@ggould-tri for platform review, please.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-:-Nyw0la18AfBmGHZCqCU:b-uhaea0)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykX1J2Ag4egp6mfOLs:-Nyw-pGR6lP90_Y7BcJy:b-cst7qq) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.h#L227)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can we use rᵤ hᵤ rᵥ hᵥ to make it a bit more clear?  (i get these from https://www.unicodeit.net/) and maybe multiply the h's on both sides, since that's what you actually implement, and it would read more clearly here, too.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_zZP3vbXz1iY3Swf:-Nyw0V702ElYPH004HFb:b-g4fuqq) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L618)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

It should only make things infeasible when the time spend in the u and v vertex is drastically different. Providing a single scalar h0 to both sides of the equation shouldn't change a thing. Even if we provide a scalar for the fraction hu0 / hv0 (scaling only one hand side of the equation), it would make things worse. Since we add edges in both directions, one direction will be scaled s.t. it's more feasible, but the other one would be more infeasible.
</blockquote></details>

good point.  ok, i guess we can do it like this for now...

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21480)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-NykX1J2Ag4egp6mfOLs:-Nyw1h-7-BnCvd0D0o4h:bccpe83) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.h#L227)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can we use rᵤ hᵤ rᵥ hᵥ to make it a bit more clear?  (i get these from https://www.unicodeit.net/) and maybe multiply the h's on both sides, since that's what you actually implement, and it would read more clearly here, too.
</blockquote></details>

Awesome!
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_zZP3vbXz1iY3Swf:-Nyw1ib3A94RdJU8_F8U:b-1odbv9) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L618)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

good point.  ok, i guess we can do it like this for now...
</blockquote></details>

In the future, I would be in favor of adding an argument to the subgraphs that allows one specifying and modifying the characteristic times. If none is provided, it will use some heuristic that's constantly update. E.g. it could be based on the maximum distance and given the velocity, acceleration, ..., limits it could calculate the time spend in there.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21480)* status: LGTM missing from assignee ggould-tri(platform)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21480#-Nyk_zZP3vbXz1iY3Swf:-Nyw7sl24jmi5Q3QTPjf:bo2trj2) ([raw file](https://github.com/RobotLocomotion/drake/blob/1e8e560ea981e1775a23757fa2ad6a915316b4d2/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L618)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

In the future, I would be in favor of adding an argument to the subgraphs that allows one specifying and modifying the characteristic times. If none is provided, it will use some heuristic that's constantly update. E.g. it could be based on the maximum distance and given the velocity, acceleration, ..., limits it could calculate the time spend in there.
</blockquote></details>

agreed.  i think that would be the better place for it.  ok to defer.

**Pull request merged**
