### PR TITLE
Add comment that MotionGenesis auto-generated file was slightly edited.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18391)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
Platform review +@sherm1  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18391#-:-NIF5CkmDlzdKoPtEQFs:b7u17lg)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 pending one change

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18391#-:-NIFFv-B9ckVDk6WtTCf:b-aad76w)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18391#-NIFFJmf2W3lSUZuv4Kw:-NIFFJmf2W3lSUZuv4Kx:b87u1fp) ([raw file](https://github.com/robotlocomotion/drake/blob/54bdaad0b21c93a11a7ce35d2ecc9e7268bc20b0/multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc#L1)):*
> ```cpp
> // GENERATED FILE DO NOT EDIT
> ```

minor: better to remove this line now that you have the new one. This text is a magic formulation understood by Reviewable that prevents it from showing diffs under the assumption that it will be completely regenerated frequently. That doesn't really describe this file now -- I had to override Reviewable's default behavior in order to see your diff.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Question: given that the edits were made to allow CI to pass, would it be good to hint at what those changes were so that if, on the far off chance, this file were to ever be regenerated, there'd be some hint as to what should happen?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18391#-:-NIbashoAxZYAGktx6EF:b-m2ohxg)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sherm1)

**Review by mitiguy — COMMENTED** [review]
@seancurtis-tri   I am going to roll-the-dice that we may never need to do this again and if we do, it will be very obvious through a reviewable diff of any changes, e.g., the change of sprintf() to snprintf().

label +(status: squashing now) 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18391#-:-NIdEFT65auAwHS9NU8d:b-acio04)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
