### PR TITLE
[geometry] Style guide tidy-ups on shape_specification

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Initialize POD member fields.
- Only inline function definitions when they are used in inner loops.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17473)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
I believe there's one functional implication of this change. Can you confirm and address (or dismiss) as appropriate?

:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17473#-:-N5lJ2cE7o_9upbXZeSn:b-sfvz63)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`geometry/shape_specification.h` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17473#-N5lIpGv6g6lnDv1Qk3c:-N5lIpGv6g6lnDv1Qk3d:b-sctjpe) ([raw file](https://github.com/robotlocomotion/drake/blob/d60419e9e80b49462c479909ff177d434aec91b1/geometry/shape_specification.h#L81)):*
> ```objc
> 
>    The base class provides infrastructure for cloning and reification. To work
>    and to maintain sanity, we place the following requirements on derived
> ```

nit: Based on my comment in the .cc file:

1. Could you indicate that Drake shapes must be defined in this file?
2. Could you also fix 
   - the incorrect "and" at the end of bullet 2?
   - the erroneous capitalization at the beginning of 4?
___
*[`geometry/shape_specification.cc` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17473#-N5lIVfO4dwmXF7kNoMt:-N5lIVfO4dwmXF7kNoMu:b-o94qlj) ([raw file](https://github.com/robotlocomotion/drake/blob/d60419e9e80b49462c479909ff177d434aec91b1/geometry/shape_specification.cc#L23)):*
> ```cpp
> 
> template <typename S>
> Shape::Shape(ShapeTag<S>) {
> ```

BTW This requires that all Drake shapes be declared in `shape_specification.h`, right?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17473)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/shape_specification.h` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17473#-N5lIpGv6g6lnDv1Qk3c:-N5lSRbq8bCnpvaJwfmH:b-v770ll) ([raw file](https://github.com/robotlocomotion/drake/blob/d60419e9e80b49462c479909ff177d434aec91b1/geometry/shape_specification.h#L81)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Based on my comment in the .cc file:

1. Could you indicate that Drake shapes must be defined in this file?
2. Could you also fix 
   - the incorrect "and" at the end of bullet 2?
   - the erroneous capitalization at the beginning of 4?
</blockquote></details>

Yes, all shape descriptions must live in this one `cc_library` now.  (That was already more or less the case -- by virtue of the reifier interface listing out all shape subclasses as overloads.)

I'll work on the docs shortly.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17473)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/shape_specification.h` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17473#-N5lIpGv6g6lnDv1Qk3c:-N5lUOD86u5ewzG43c-s:b-q7kjz7) ([raw file](https://github.com/robotlocomotion/drake/blob/d60419e9e80b49462c479909ff177d434aec91b1/geometry/shape_specification.h#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, all shape descriptions must live in this one `cc_library` now.  (That was already more or less the case -- by virtue of the reifier interface listing out all shape subclasses as overloads.)

I'll work on the docs shortly.
</blockquote></details>

Yeah. I had the same thought. But this cast it in stark relief vis a vis the documentation for me.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17473)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
