### PR TITLE
[wheel builder] Add option to validate version against PEP 440

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
+@svenevs for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
:lgtm: thanks for adding this in, this will be very helpful for release managers testing staging releases:

```console
$ bazel run //tools/wheel:builder -- --pep440 1.13.0.rc1
INFO: Analyzed target //tools/wheel:builder (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools/wheel:builder up-to-date:
  bazel-bin/tools/wheel/builder
INFO: Elapsed time: 0.060s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tools/wheel/builder --pep440 1.13.0.rc1
Version '1.13.0.rc1' does not conform to PEP 440

$  echo $?
1

$ bazel run //tools/wheel:builder -- --pep440 1.13.0rc1
INFO: Analyzed target //tools/wheel:builder (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools/wheel:builder up-to-date:
  bazel-bin/tools/wheel/builder
INFO: Elapsed time: 0.048s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tools/wheel/builder --pep440 1.13.0rc1
Version '1.13.0rc1' conforms to PEP 440

$ echo $?
0
```

I am going to add some wheel builds for solidarity and then assign platform pending results.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-:-NOQQcSd4chCpQjZbLtw:brboi9r)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

___
*[`tools/wheel/wheel_builder/common.py` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-NOQQyC_-L5xRHWaauKp:-NOQQyC_-L5xRHWaauKq:b1rlc2s) ([raw file](https://github.com/RobotLocomotion/drake/blob/1579cccdd4c3f893bca4c967b1db2955d2e1417f/tools/wheel/wheel_builder/common.py#L132)):*
> ```Python
> 
>     if not _check_version(options.version):
>         die(f'Version \'{options.version}\' does not conform to PEP 440')
> ```

nit: can we make it obnoxious?  `does not conform` => `does *NOT* conform`

```diff
- not
+ *NOT*
```

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

___
*[`tools/wheel/wheel_builder/common.py` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-NOQQyC_-L5xRHWaauKp:-NPJVrO1DVjzBvxKuVxT:b-vq4cl5) ([raw file](https://github.com/RobotLocomotion/drake/blob/1579cccdd4c3f893bca4c967b1db2955d2e1417f/tools/wheel/wheel_builder/common.py#L132)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

nit: can we make it obnoxious?  `does not conform` => `does *NOT* conform`

```diff
- not
+ *NOT*
```
</blockquote></details>

I'm not super in love with such "formatting" in console output, but there's precedent for capitalizing (done). Is that sufficient, or do you feel strongly about the asterisks also?

**Review by svenevs — COMMENTED** [review]
```console
$ bazel run //tools/wheel:builder -- --pep440 1.13.0.rc1
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tools/wheel:builder (43 packages loaded, 312 targets configured).
INFO: Found 1 target...
Target //tools/wheel:builder up-to-date:
  bazel-bin/tools/wheel/builder
INFO: Elapsed time: 2.619s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tools/wheel/builder --pep440 1.13.0.rc1
Version '1.13.0.rc1' does NOT conform to PEP 440

$ bazel run //tools/wheel:builder -- --pep440 1.13.0rc1
INFO: Analyzed target //tools/wheel:builder (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools/wheel:builder up-to-date:
  bazel-bin/tools/wheel/builder
INFO: Elapsed time: 0.076s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tools/wheel/builder --pep440 1.13.0rc1
Version '1.13.0rc1' conforms to PEP 440
```

:lgtm_strong: Thanks @mwoehlke-kitware this will be really helpful for any future release managers who may need to stage a release candidate.

+@ggould-tri for platform review, please.  Context: we're going to be updating the YAML (see linked private PR from GitHub if interested), current staging builds have this uncomfortable description:



but Matthew noticed that it would be easy for us to just add a check to the wheel builder, so after this lands we'll update the jenkins description to encourage the new `--pep440` check.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-:-NPJY1vx2qj0umDbMzsm:b-z5hxz6)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`tools/wheel/wheel_builder/common.py` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-NOQQyC_-L5xRHWaauKp:-NPJXumu9JMSWnl9F4Nu:bxc3nmz) ([raw file](https://github.com/RobotLocomotion/drake/blob/1579cccdd4c3f893bca4c967b1db2955d2e1417f/tools/wheel/wheel_builder/common.py#L132)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm not super in love with such "formatting" in console output, but there's precedent for capitalizing (done). Is that sufficient, or do you feel strongly about the asterisks also?
</blockquote></details>

LGTM, the `NOT` works great / makes it easy to distinguish between success and failure.  Thanks!

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-:-NPJZ_XaDTIfeiXUJIhb:b-uwkowd)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-NPJ_LOx25v6urSgjX6y):*
minor:  It seems to me that this PR actually does two things -- it adds 440 validation and it adds the ability to run the script on otherwise unsupported platforms -- so the commit message should mention both.



_Suggestion:_
```
- 40fe330: [wheel builder] Add option to validate version against PEP440

 * PEP 440 Validation also works on platforms that do not otherwise support wheel builds.
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @mwoehlke-kitware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-NPJ_LOx25v6urSgjX6y):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It seems to me that this PR actually does two things -- it adds 440 validation and it adds the ability to run the script on otherwise unsupported platforms -- so the commit message should mention both.
</blockquote></details>

Done. Although IIRC, the way Drake "merges" PRs eats the original commit message(s), so this may only be visible if someone comes and looks at this PR.

**Review by svenevs — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @mwoehlke-kitware)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18784)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @mwoehlke-kitware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18784#-NPJ_LOx25v6urSgjX6y):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Done. Although IIRC, the way Drake "merges" PRs eats the original commit message(s), so this may only be visible if someone comes and looks at this PR.
</blockquote></details>

I believe that the message on the github PR page (https://github.com/RobotLocomotion/drake/pull/18784) is the one that ultimately wins, but I could be wrong about that -- I haven't tested in in recent memory.

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

**Comment by svenevs** [comment]
It depends on who merges and how, sometimes people accidentally choose the "Merge commit" option, but users should be choosing the "squash and merge".  Which should only add `(#PRNUMBER)` after the first sentence, and preserve the rest.

E.g., PR 123 with one commit messaged

```
[thing] Fix it all

The things are fixed in reverse sorted order.
```

should end up being via squash

```
[thing] Fix it all (#123)

The things are fixed in reverse sorted order.
```

**Pull request merged**
