### PR TITLE
Disable run_setpose_jaco_demo under memcheck

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7041)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please

**Comment by sammy-tri** [comment]
+@ericcousineau-tri for all review  (as background, this test is currently failing in the nightlies.  I enabled it in #7032, but it never should have had that dependency in the first place...   this changes the tag to `no_memcheck` instead of `snopt` in the pre-#7032 world to more reflect the fact that while it doesn't depend on snopt, it is broken under memcheck)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7041#-:-KuKwYWWkVenVqGnDGe1:bsppbyw)*

**Comment by sammy-tri** [comment]
Slight clarification from f2f: The rule at https://github.com/RobotLocomotion/drake/blob/master/tools/bazel.rc#L292 was causing `snopt` tagged tests to be skipped under memcheck which is what hid this behavior before.  `run_setpose_jaco_demo` doesn't actually use snopt or ipopt at all.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7041#-:-KuL5CA9jTDyoJP8xUOI:b-qj5mbc)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7041#-:-KuL46r_295048LLzJwb:bnfp4nl)*

**Pull request merged**
