### PR TITLE
pydrake: Add guidance for ambiguous const-vs-mutable overloads

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Encodes discussion from: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1626366534036100

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for review / discussion, please!
+(priority: low) 
\cc @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404#-:-MefyzPi72bLkyx0ZckY:b-1ld60x)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

My present case is most like the last example you present; methods where the const-ness of the return value has to be encoded into the name. I'll probably tag you into the PR to look at bindings anyway, but having this overview of the issues is great. Thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404#-:-Meg8Pkw7VcIx7MGKvjF:b-fswp1d)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15404#-Meg85hi8ki4YQHNZ5iI:-Meg85hjA9-CT4lKSU9L:b-smh67l) ([raw file](https://github.com/robotlocomotion/drake/blob/5bb0cec307cc37598b27b2178dfa9169dcc18609/bindings/pydrake/pydrake_doxygen.h#L461)):*
> ```
> Dismabiguating
> ```
typo

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404#-:-MegI4gO7DSpbkQDdsxy:btfqagw)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15404#-Meg85hi8ki4YQHNZ5iI:-MegI2Ur7qvOsTaXByLY:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/5bb0cec307cc37598b27b2178dfa9169dcc18609/bindings/pydrake/pydrake_doxygen.h#L461)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> Dismabiguating
> ```
typo
</blockquote></details>

Done. Oops!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform -@SeanCurtis-TRI .

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404#-:-MegPz1m4Z6IHBTZdOPZ:b-e19bza)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 443 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15404#-MegPZ_eBeX0Jy5TLX5z:-MegPZ_eBeX0Jy5TLX6-:bs1yhic) ([raw file](https://github.com/robotlocomotion/drake/blob/eb04c85e8e8af7a46363b8532d486afe5a9e053e/bindings/pydrake/pydrake_doxygen.h#L443)):*
> ```objc
> 
> For this reason, only bind `const` methods when there is *not* an identical
> mutable overload (e.g. same name and same arguments).
> ```

This phrasing is a bit awkward.  I _think_ all it's trying to say is "When a function is overloaded only by its const-ness, choose to bind the mutable overload, not the const overload."?
___
*[bindings/pydrake/pydrake_doxygen.h, line 458 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15404#-MegPs6ZElFRhrBy863a:-MegPs6ZElFRhrBy863b:b-955c81) ([raw file](https://github.com/robotlocomotion/drake/blob/eb04c85e8e8af7a46363b8532d486afe5a9e053e/bindings/pydrake/pydrake_doxygen.h#L458)):*
> ```objc
> void MyFunction(MyClass* mutable_value);
> // DO NOT BIND: Identical to above mutable overload, may constrain user. Do not
> // bind!
> ```

nit The second "Do not bind!" here seems redundant with the scream caps earlier in the line?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[bindings/pydrake/pydrake_doxygen.h, line 443 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15404#-MegPZ_eBeX0Jy5TLX5z:-Mf-OqKj0Czdsp2BLUcV:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/eb04c85e8e8af7a46363b8532d486afe5a9e053e/bindings/pydrake/pydrake_doxygen.h#L443)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This phrasing is a bit awkward.  I _think_ all it's trying to say is "When a function is overloaded only by its const-ness, choose to bind the mutable overload, not the const overload."?
</blockquote></details>

Done. Thanks!
___
*[bindings/pydrake/pydrake_doxygen.h, line 458 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15404#-MegPs6ZElFRhrBy863a:-Mf-Ozjz98AyyvoS3sWg:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/eb04c85e8e8af7a46363b8532d486afe5a9e053e/bindings/pydrake/pydrake_doxygen.h#L458)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The second "Do not bind!" here seems redundant with the scream caps earlier in the line?
</blockquote></details>

Done. Oops!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15404)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
