### PR TITLE
command line options for pick and place demo

### PR DESCRIPTION
**Pull request by naveenoid**
Expands the pick and place demo to have the object and the initial orientation settable on the command line.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5887)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@sammy-tri for feature review.

**Comment by sammy-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6K5c5ulcgG9eYzl_y:-Ki6K5c5ulcgG9eYzl_z:b-7rmps0) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.cc#L91)):*
> ```cpp
> 
>   DiagramBuilder<T> builder;
>   std::cout<<"Plant builder box ID :"<<chosen_box<<"\n";
> ```

Leftover debug code?  If we want this print there are whitespace issues and I might suggest using text_logging.h instead.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6Kpl71lHSf54AojBF:-Ki6Kpl8gw1LpZEC0PbI:b7lr81q) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L65)):*
> ```objc
> std::unique_ptr<systems::RigidBodyPlant<T>> BuildCombinedPlant(
>     ModelInstanceInfo<T>* iiwa_instance, ModelInstanceInfo<T>* wsg_instance,
>     ModelInstanceInfo<T>* box_instance, const int chosen_box = 1,
> ```

Does the choice of box actually not do anything in the PR?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6KyEuS1IVgTlprB2S:-Ki6KyEvr1w7r9qIBjv9:b-n5zv0c) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L65)):*
> ```objc
> std::unique_ptr<systems::RigidBodyPlant<T>> BuildCombinedPlant(
>     ModelInstanceInfo<T>* iiwa_instance, ModelInstanceInfo<T>* wsg_instance,
>     ModelInstanceInfo<T>* box_instance, const int chosen_box = 1,
> ```

Given that BuildCombinedPlant is only called from the constructor, we could avoid writing the default argument values twice by omitting them here.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6LSTEkjgkS_R3LHK3:-Ki6LSTF3W_uoLdLaYDN:b-h61v7t) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L68)):*
> ```objc
>     Eigen::Vector3d box_position = Vector3<double>(
>         1 + -0.43, -0.65, kTableTopZInWorld + 0.1),
>     Eigen::Vector3d box_orientation = Vector3<double>(0, 0, 1)) {
> ```

It seems this parameter, despite being documented, is unused and has no effect?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6LDmipUT_WtE_Ojuo:-Ki6LDmjEvN9xqhy07bb:b-xw22nu) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L100)):*
> ```objc
>   // the table top exactly, it may start colliding the table (which is
>   // not good, as it will likely shoot off into space).
>   const Eigen::Vector3d kBoxBase(1 + -0.43, -0.65, kTableTopZInWorld + 0.1);
> ```

Seems like we're ignoring box_position in favor of repeating the default value again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6K5c5ulcgG9eYzl_y:-Ki75TDw7zqjwE4jWN1G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.cc#L91)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Leftover debug code?  If we want this print there are whitespace issues and I might suggest using text_logging.h instead.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6Kpl71lHSf54AojBF:-Ki75UNhy7lvcRs8OtVn:b7o02tt) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L65)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does the choice of box actually not do anything in the PR?
</blockquote></details>

No..The box choice changes up the box used in the demo (1-small, 2-medium, 3-large). Or is there something wrong in the way I hav documented / set it up?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6KyEuS1IVgTlprB2S:-Ki777BuUEEFAU3sBM9u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L65)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Given that BuildCombinedPlant is only called from the constructor, we could avoid writing the default argument values twice by omitting them here.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6LSTEkjgkS_R3LHK3:-Ki9qBZseNYxviKsrLu-:bwb439u) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L68)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems this parameter, despite being documented, is unused and has no effect?
</blockquote></details>

Ok that was a chunk of code that disappeared during a bad rebase. The version Ive pushed uses this argument as well as the box_choice.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6LDmipUT_WtE_Ojuo:-Ki9qPVrNI1c_X1oTkPt:bbu0pgo) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L100)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Seems like we're ignoring box_position in favor of repeating the default value again?
</blockquote></details>

Corrected in the new version. Its no longer ignored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6Kpl71lHSf54AojBF:-KiAgV0CU7EfjSoLf9lx:b-6od0qq) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L65)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

No..The box choice changes up the box used in the demo (1-small, 2-medium, 3-large). Or is there something wrong in the way I hav documented / set it up?
</blockquote></details>

Ah, I see the code has appeared now.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 111 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgfspBqkCcVvQcdP8:-KiAgfsqPvC02OM1H9rT:b-7u1n95) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L111)):*
> ```objc
>       box_id = tree_builder->AddFloatingModelInstance("box_small", box_position,
>                                                       box_orientation);
>       *box_instance = tree_builder->get_model_info_for_instance(box_id);
> ```

BTW it looks like this line could occur once after the `switch` instead of being copied three times...  (assuming that there's not a no-box option I'm not noticing)

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgmwLwCRqPN7TrHp8:-KiAgmwLwCRqPN7TrHp9:b-p73pmz) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L123)):*
> ```objc
>       *box_instance = tree_builder->get_model_info_for_instance(box_id);
>       break;
>     default:
> ```

Should falling through to the default case be an error?  Or is this intended to be a way to (for some reason I can't think of) disable the box?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-:-KiAgFfqknealeBxAAuy:b-s794vx)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki6Kpl71lHSf54AojBF:-KiWsUEvfEpvuBG1pdUm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55cfa2b62a2049cd1950ec1b96498ad20002119a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L65)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ah, I see the code has appeared now.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 111 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgfspBqkCcVvQcdP8:-KiWtd-F4F8qJzLBHVsY:ba3348) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L111)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it looks like this line could occur once after the `switch` instead of being copied three times...  (assuming that there's not a no-box option I'm not noticing)
</blockquote></details>

Done. Also added Drake demand to take care of the no-box or >3 box choice.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgmwLwCRqPN7TrHp8:-KiWtym_L_yrt4Qni-HM:b-eblwax) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L123)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should falling through to the default case be an error?  Or is this intended to be a way to (for some reason I can't think of) disable the box?
</blockquote></details>

I left that hanging code in there and will sort it later to handle no-box. I added a DRAKE_DEMAND to take care of the default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 111 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgfspBqkCcVvQcdP8:-KiXAOiAmC1bSLJqmons:b88safw) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L111)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done. Also added Drake demand to take care of the no-box or >3 box choice.
</blockquote></details>

I don't see this update.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgmwLwCRqPN7TrHp8:-KiXARkSGd8txkIPatku:b88safw) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L123)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I left that hanging code in there and will sort it later to handle no-box. I added a DRAKE_DEMAND to take care of the default.
</blockquote></details>

I don't see this update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by naveenoid** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 111 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgfspBqkCcVvQcdP8:-KiXC5a71X7aD7dn5FKD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L111)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't see this update.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgmwLwCRqPN7TrHp8:-KiXC678OHiJfTR_KzOZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L123)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't see this update.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI

---

Reviewed 1 of 3 files at r3.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgmwLwCRqPN7TrHp8:-Ki_RK7h3Ckwq6u63XUG:b-410n5r) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L123)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not sure the code required to handle this would have been more characters than the TODO, but whatever.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki_R2DTr7zBrwSJOVvY:-Ki_R2DUyPhkJ-2XeiyT:b-mi7fgk) ([raw file](https://github.com/robotlocomotion/drake/blob/35c0becfdf04f15fae576ac5059ebcb9debb770a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L104)):*
> ```objc
> 
>   DRAKE_DEMAND(chosen_box < 4);
>   // Chooses and appropriate box.
> ```

possible typo "an appropriate"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-:-Ki_Rm2gsUTrr4UrBVbi:b3cfjge)*

**Comment by naveenoid** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-KiAgmwLwCRqPN7TrHp8:-KiahhCI88wEjdOapd6-:b-sylhf5) ([raw file](https://github.com/robotlocomotion/drake/blob/de6f8f9a8db2127d42341991cae9ad8bc5495406/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L123)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure the code required to handle this would have been more characters than the TODO, but whatever.
</blockquote></details>

Handled it now with a DRAKE_ABORT_MSG. 

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-Ki_R2DTr7zBrwSJOVvY:-KiaenIbGDUYmdRWTel6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35c0becfdf04f15fae576ac5059ebcb9debb770a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L104)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

possible typo "an appropriate"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 4 files at r4.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887)*

**Comment by naveenoid** [comment]
moving to squash and merge
-(status: curate commits before merging) 

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5887#-:-KieH4a1hKtMpgQHQH3P:b1xfmli)*

**Pull request merged**
