### PR TITLE
Set gradient sparsity pattern in LorentzConeConstraint and RotatedLorentzConeConstraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1730718062496299?thread_ts=1730511193.767279&cid=C3L92BM2Q

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22125)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@TobiaMarcucci for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22125#-:-OAtpjap7In1M_rgnSSL:b-i7m6vf)* status: LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by TobiaMarcucci — COMMENTED** [review]
Looks great to me. Thank you so much for adding this feature!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22125#-:-OAu3LhJ16uzInqJzRuF:b1fgoba)* status: LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by TobiaMarcucci — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22125#-:-OAu3g1t2YcJf8n7QG28:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22125#-:-OAxcqtX1cKYGc7iuZvL:b8asji7)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22125#-:-OAxkyjS-rjerIG3KRvf:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees TobiaMarcucci,rpoyner-tri(platform)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug retest this please.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug retest this please.

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please.

**Pull request merged**
