### PR TITLE
Do not start server just to check Bazel version from CMake

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8502)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8502#-:-L9AywwY1anynq47u9Xa:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for feature review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8502#-:-L9BbWMq-bU__odRUEYQ:bnfp4nl)*

**Pull request merged**
