### PR TITLE
Add capsule shape specification and enable visualization

### PR DESCRIPTION
**Pull request by tehbelinda**
Related to #10153

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12235)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@seancurtis-tri for feature review please

**Comment by tehbelinda** [comment]
+(status: do not merge) waiting on Anzu PR review

**Comment by jwnimmer-tri** [comment]
Eric is correct, and I think it's much more strong of an defect than "feel free to dismiss".  Flag day updates for adding new pure virtual methods should be avoided with prejudice.

The short-term fix is to make the new method here non-pure (throwing) with class comments to caution the user about forthcoming changes.

A future middle ground is to keep the interface pure, but offer an always-throws implementation that users may derive from, if they want to have runtime errors instead of build-time errors.  Then the user can choose which type of error they prefer for unsupported types of shapes.

**Comment by jwnimmer-tri** [comment]
Also, `static bool warning_dispatched = false;` is copy-pasta and not threadsafe.  See https://github.com/RobotLocomotion/drake/blob/575555d889a071f4870d0407f132c1dff6085c86/common/text_logging.h#L171-L192 for the suggested formulation.

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.h, line 340 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12235#-Lrui0SzArkRF2x2xLgR:-Lry_3vg2B3vpdqz3gmw:bjwa7hh) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d570afc9b5e15dbc33c1f4def654d2346f5b70/geometry/shape_specification.h#L340)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Good catch!
</blockquote></details>

:tada:

**Comment by tehbelinda** [comment]
-(status: do not merge)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.cc, line 139 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12235#-Ls2nT8s8Swo4Ms_BBqD:-LsItRho7JbU_WWP-Jp9:b-7ts0a) ([raw file](https://github.com/robotlocomotion/drake/blob/ee6da10245c737a877a23453801f20e4c58596d2/geometry/shape_specification.cc#L139)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Just to ping, is it still possible to add this in? I can push the change if you'd like.
</blockquote></details>

I've done it, sorry I just failed to update the PR properly the first time

**Pull request merged**
