### PR TITLE
Max clique

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@wernerpe for feature review.
+@sadraddini for Drake specific feature review.
Closes #20395 in favor of more direct implementation objectives in #20372

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-Nh7boB0-BHvPYXQ42Lb:bj70206)* status: 2 unresolved discussions, LGTM missing from assignees wernerpe,sadraddini, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`-- commits` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh7bF-b0hhU_AjweqiU):*
All these commits will get squashed out.
___
*[`planning/graph_algorithms/max_clique.cc` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh7bbSeAD07dCBXxx2m:-Nh7bbSeAD07dCBXxx2n:b-eovpid) ([raw file](https://github.com/RobotLocomotion/drake/blob/80ee17b7c13564c9dbab0fb514d4e18319f05949/planning/graph_algorithms/max_clique.cc#L46)):*
> ```cpp
>   // and so we only need to add constraints from the upper triangular part.
>   // Therefore, we need exactly num_zero_in_adjacency triplets.
>   A_constraint_triplets.reserve(num_zero_in_adjacency);
> ```

cc @RussTedrake for discussion about whether we need to add the lower triangular part too.

**Review by wernerpe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 3 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_clique.h` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh82FP2473lIlMm3PqS:-Nh82FP2473lIlMm3PqT:bt8amwp) ([raw file](https://github.com/RobotLocomotion/drake/blob/508647afb4c83533a6fca79dafc17553aead745e/planning/graph_algorithms/max_clique.h#L43)):*
> ```objc
>  * mixed-integer program.
>  *
>  * Note: This solver leverage convex optimization solvers (e.g. Gurobi and/or
> ```

leverages



_Code quote:_
```objc
leverage
```

**Review by wernerpe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 4 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_clique.h` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh82ZOR4DSkJLbYUime:-Nh82ZOR4DSkJLbYUimf:b-qv6xx2) ([raw file](https://github.com/RobotLocomotion/drake/blob/508647afb4c83533a6fca79dafc17553aead745e/planning/graph_algorithms/max_clique.h#L79)):*
> ```objc
>  * each pair of vertices is connected by an edge (i.e. a fully connected
>  * subgraph). This problem is known to be NP-complete, and so the choice of
>  * solvers in options determines whether the return of this function is the true
> ```

the options



_Code quote:_
```objc
 options
```

**Review by wernerpe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 5 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_clique.cc` line 70 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NhCWL6eAf7BPTjWHWLH:-NhCWL6eAf7BPTjWHWLI:bcprwwi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4fdf3174908c8b25514064690d8d480bc5db21f8/planning/graph_algorithms/max_clique.cc#L70)):*
> ```cpp
>       ->Solve(prog, std::nullopt, options_, &result);
> 
>   return result.GetSolution(x).cast<bool>();
> ```

I how robust is this casting? In python I occasionally needed to round gurobi outputs.

**Review by AlexandreAmice — COMMENTED** [review]
@wernerpe Sorry need you to take another pass, I changed a bit more of the interface.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-NhcgkAv4cDbYsiPhTna:b7myf24)* status: 4 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_clique.h` line 43 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh82FP2473lIlMm3PqS:-NhCI_xuExfOqBiXjCaA:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/508647afb4c83533a6fca79dafc17553aead745e/planning/graph_algorithms/max_clique.h#L43)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

leverages
</blockquote></details>

Done.
___
*[`planning/graph_algorithms/max_clique.h` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh82ZOR4DSkJLbYUime:-NhCIhjO1XZsHmwMrxn5:b8vgd9b) ([raw file](https://github.com/RobotLocomotion/drake/blob/508647afb4c83533a6fca79dafc17553aead745e/planning/graph_algorithms/max_clique.h#L79)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

the options
</blockquote></details>

Changed to @param options
___
*[`planning/graph_algorithms/max_clique.cc` line 70 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NhCWL6eAf7BPTjWHWLH:-NhTFPBOECEgTkBLWG5s:b63h68x) ([raw file](https://github.com/RobotLocomotion/drake/blob/4fdf3174908c8b25514064690d8d480bc5db21f8/planning/graph_algorithms/max_clique.cc#L70)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

I how robust is this casting? In python I occasionally needed to round gurobi outputs.
</blockquote></details>

Good call. I put a more robust cast in.

**Review by wernerpe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 5 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/graph_algorithms_internal.cc` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NhlXeXf8VJL2b7mSrBS:-NhlXeXf8VJL2b7mSrBT:b7qw2gh) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/graph_algorithms_internal.cc#L11)):*
> ```cpp
> // Given the adjacency matrix of a graph G, return the complement graph H. The
> // complement graph H has the same vertex set as G, with vertices (i,j) forming
> // an edge in H if and only if they do not form an edge in G.
> ```

I think you are missing a comment on self-adjacency here. This implementation specifically does not touch any self edges of the adjacency matrix.

**Review by wernerpe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 5 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/graph_algorithms_internal.cc` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NhlXeXf8VJL2b7mSrBS:-NhlXruQ11HM1n3zioYO:b-ucnpuw) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/graph_algorithms_internal.cc#L11)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

I think you are missing a comment on self-adjacency here. This implementation specifically does not touch any self edges of the adjacency matrix.
</blockquote></details>

Same for the comments in the header file.

**Review by wernerpe — COMMENTED** [review]
I think it looks good, modulo the tiny comment at the complement graph code snippet.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-NhlYWht-qFFDyjfQ7dc:bbk9jdw)* status: 2 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by sadraddini — COMMENTED** [review]
Very nice work! Left a few small comments. 
I liked those new graphs but I feel allocating multiple new files to define them is excessive. Maybe you could just have defined them in the test files? There are only two. You may use the Petersen graph only for the clique test (not the reverse test). 

> Reviewed 6 of 12 files at r1, 2 of 5 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-Ni_qev05T-WQbVJs1b4:b-2j2h7s)* status: 7 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_clique.h` line 94 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni__bbFDeWUnANCi1wP:-Ni__bbFDeWUnANCi1wQ:bdaozvu) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/max_clique.h#L94)):*
> ```objc
> 
> /**
>  * Given the adjacency matrix of an undirected graph, find the maximum clique
> ```

nit  The docs should state that if one passes an adjacency matrix that is not symmetric (and thus not from an undirected graph) then an exception will happen. 
___
*[`planning/graph_algorithms/max_clique.h` line 108 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni__QDA5rXSaeDQFDYP:-Ni__QDB6qMYeTd7yM-M:b-brvjcn) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/max_clique.h#L108)):*
> ```objc
>  * @throws based on the preconditions of the solver contained in @param options.
>  */
> VectorX<bool> MaxClique(const Eigen::SparseMatrix<bool>& adjacency_matrix,
> ```

nit  suggesting changing this to `CalcMaxClique`? 
___
*[`planning/graph_algorithms/max_clique.cc` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh7bbSeAD07dCBXxx2m:-Ni_qZHr7rXuvBUZwLJ2:bhi2lr1) ([raw file](https://github.com/RobotLocomotion/drake/blob/80ee17b7c13564c9dbab0fb514d4e18319f05949/planning/graph_algorithms/max_clique.cc#L46)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

cc @RussTedrake for discussion about whether we need to add the lower triangular part too.
</blockquote></details>

I'm curious on why you need those. 
___
*[`planning/graph_algorithms/max_clique.cc` line 84 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni_b_ys93udCo1qK6d0:-Ni_b_ys93udCo1qK6d1:b-gibwnm) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/max_clique.cc#L84)):*
> ```cpp
>         "them.");
>   }
>   solver->Solve(prog, initial_guess_, solver_options_, &result);
> ```

nit  you need to check if result is successful. I know it is very unlikely because the problem is bounded by definition but it can still happen due to numerical issues and timeout issues. 
___
*[`planning/graph_algorithms/test/common_graphs.h` line 9 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni_dqsi0NZEkEmW4mQl:-Ni_dqsi0NZEkEmW4mQm:b7g666n) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/test/common_graphs.h#L9)):*
> ```objc
> 
> // Complete graph on n vertices
> Eigen::SparseMatrix<bool> Kn(const int n);
> ```

nit name too short and vague. You may change name to `MakeCompleteGraph` 
___
*[`planning/graph_algorithms/test/graph_algorithms_internal_test.cc` line 113 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni_nmbLAKlsT61hELpQ:-Ni_nmbLAKlsT61hELpR:b-9xfsdu) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/test/graph_algorithms_internal_test.cc#L113)):*
> ```cpp
> }
> 
> GTEST_TEST(ComplemenatryGraph, PetersenGraph) {
> ```

nit What is the purpose of this test that the other two do not serve? You may want to remove it. I like to keep the Petersen matrix for clique cover though. 
Also see my generic comment on zapping these files and moving everything to test files.

**Review by AlexandreAmice — COMMENTED** [review]
There is only one file for these graphs. I like having them in an actual library, as if we introduce new graph algorithms it will be useful to have a growing list of testable graphs.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-NibRuG42hWThgo5A85y:b-si76t1)* status: 3 unresolved discussions, LGTM missing from assignees sadraddini,wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/graph_algorithms_internal.cc` line 11 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NhlXeXf8VJL2b7mSrBS:-NibP3a4DD7Oy0ByfPjC:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/graph_algorithms_internal.cc#L11)):*
<details><summary><i>Previously, wernerpe (Peter Werner) wrote…</i></summary><blockquote>

Same for the comments in the header file.
</blockquote></details>

Done.
___
*[`planning/graph_algorithms/max_clique.cc` line 46 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nh7bbSeAD07dCBXxx2m:-NibP5AFE8nfkKTF20r8:bws6urx) ([raw file](https://github.com/RobotLocomotion/drake/blob/80ee17b7c13564c9dbab0fb514d4e18319f05949/planning/graph_algorithms/max_clique.cc#L46)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

I'm curious on why you need those.
</blockquote></details>

I don't believe they are needed.
___
*[`planning/graph_algorithms/max_clique.cc` line 84 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni_b_ys93udCo1qK6d0:-NibR8M5EEo4ep5Adzic:b-cnh81b) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/max_clique.cc#L84)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit  you need to check if result is successful. I know it is very unlikely because the problem is bounded by definition but it can still happen due to numerical issues and timeout issues.
</blockquote></details>

I put an assert in there.
___
*[`planning/graph_algorithms/test/graph_algorithms_internal_test.cc` line 113 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Ni_nmbLAKlsT61hELpQ:-NibS4xn3WdOHlzsSzxL:bravw0c) ([raw file](https://github.com/RobotLocomotion/drake/blob/65e807c6f56b233c333019f97a397a8b78ed8dd8/planning/graph_algorithms/test/graph_algorithms_internal_test.cc#L113)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit What is the purpose of this test that the other two do not serve? You may want to remove it. I like to keep the Petersen matrix for clique cover though. 
Also see my generic comment on zapping these files and moving everything to test files.
</blockquote></details>

I like keeping the Peterson graph around. In this case, it is a simple graph that is neither perfect and has a gap between the independence number and clique number larger than 1.

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-NieLjxd8r1QxikuLl8H:bnfp4nl)* status: 3 unresolved discussions, LGTM missing from assignee wernerpe, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
@rpoyner-tri for s/feature/platform/ review (for my own later bookkeeping)

+(release notes: feature) 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> numerous minor things

> Reviewed 1 of 12 files at r1, 2 of 5 files at r2, 1 of 4 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-NifZbjl7C2wj2WUb6Cx:b-82p1me)* status: 12 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`-- commits` line 58 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-Nig_NWO6PJa0i0Pu9Ly):*
btw  We are starting to try to be more consistent with commit messages, to help git tooling, and release notes authors. I can squash the commits and use my understanding of the patch as a basis for the commit message. The only reason you (author) would need to take action is if the proposed message below is somehow wrong or incomplete.
Here is what I propose:
```
planning] Add max clique solver classes                                                                                                                                                      
                                                                                                                                                                                              
The patch adds an interface for solvers for max clique problems, and a                                                                                                                        
concrete class to solve them via mixed integer programming.  It also                                                                                                                          
introduces the new planning/graph_algorithms source code directory.    
```                                                                                                                                                                                       

If the above is good, just resolve this thread, Otherwise, let me know how to improve things.
___
*[`planning/graph_algorithms/max_clique.cc` line 86 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigX6_b8hkc34Navgb6:-NigX6_b8hkc34Navgb7:b767hle) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/max_clique.cc#L86)):*
> ```cpp
> 
>   // Manually cast the return to a boolean to avoid round off errors from the
>   // MIP solver
> ```

nit Sentence should end with a period (.).
___
*[`planning/graph_algorithms/test/graph_algorithms_internal_test.cc` line 51 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigWxuh6TWAXFuWckAk:-NigWxuh6TWAXFuWckAl:b767hle) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/graph_algorithms_internal_test.cc#L51)):*
> ```cpp
>         return true;
>       };
>   // Check if every element in entries appears in entries_expected
> ```

nit Sentence should end with a period (.).
___
*[`planning/graph_algorithms/test/graph_algorithms_internal_test.cc` line 56 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NiftCO9CfUuLII48Ae1:-NiftCOA9YQ8TFXqGo3H:b-8xs12r) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/graph_algorithms_internal_test.cc#L56)):*
> ```cpp
> }
> 
> GTEST_TEST(ComplemenatryGraph, CompleteGraph) {
> ```

typo. Several more below as well.



_Suggestion:_
```cpp
ComplementaryGraph
```
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 19 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigVcl4B8hS-FrqRmdU:-NigVcl56VSnHlrY1rCm:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L19)):*
> ```cpp
> using Eigen::Triplet;
> 
> // Test maximum clique solved via mip. Compare against the expected size of
> ```

typo



_Suggestion:_
```cpp
MIP
```
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 22 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigWM7E38y_ESfKC42c:-NigWM7E38y_ESfKC42d:bgzdcp3) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L22)):*
> ```cpp
> // the solution and ensure that the result is one of the true maximum cliques in
> // the graph.
> void TestMaxCliqueViaMIP(
> ```

Style guide says: "For names written in mixed case (also sometimes referred to as "[camel case](https://en.wikipedia.org/wiki/Camel_case)" or "[Pascal case](https://en.wiktionary.org/wiki/Pascal_case)"), in which the first letter of each word is capitalized, prefer to capitalize abbreviations as single words, e.g., `StartRpc()` rather than `StartRPC()`."  https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules



_Suggestion:_
```cpp
TestMaxCliqueViaMip
```
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 38 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigTWqgCUAZvsNEIHpO:-NigTWqgCUAZvsNEIHpP:bywp74l) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L38)):*
> ```cpp
>     bool solution_match_found = false;
>     for (const auto& possible_solution : possible_solutions) {
>       if (CompareMatrices(max_clique_inds, possible_solution)) {
> ```

`clang` is refusing to compile this line, because `CompareMatrices()` is using `abs()` internally on `bool` elements, and the compiler rightly points out that is a no-op.

Consider something like `.cast<int>()` on the arguments here.
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 69 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigWhsC6w2M--KL0XGn:-NigWhsC6w2M--KL0XGo:b767hle) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L69)):*
> ```cpp
> GTEST_TEST(MaxCliqueSolverViaMipTest, CompleteGraph) {
>   for (const auto n : {3, 8}) {
>     // The entire graph forms a clique
> ```

nit Sentence should end with a period (.).
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 79 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigWpIb34haXvy-AcyA:-NigWpIb34haXvy-AcyB:b767hle) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L79)):*
> ```cpp
> GTEST_TEST(MaxCliqueSolverViaMipTest, BullGraph) {
>   VectorX<bool> solution(5);
>   // The largest clique is (1,2,3)
> ```

nit Sentence should end with a period (.).
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 88 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigWqX8Dan0xidhTgZD:-NigWqX8Dan0xidhTgZE:b767hle) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L88)):*
> ```cpp
>   VectorX<bool> solution1(5);
>   VectorX<bool> solution2(5);
>   // The largest cliques are (0,1,2) and (2,3,4)
> ```

nit Sentence should end with a period (.).
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 97 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigZ0f76TMINW5vNWy8:-NigZ0f76TMINW5vNWy9:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L97)):*
> ```cpp
> 
> GTEST_TEST(MaxCliqueSolverViaMipTest, PetersenGraph) {
>   // The petersen graph has a clique number of size 2, so all edges are possible
> ```

typo



_Suggestion:_
```cpp
Petersen
```


<!-- Sent from Reviewable.io -->

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 22 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigWM7E38y_ESfKC42c:-NijizO_7qsWuLOzRZgK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L22)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Style guide says: "For names written in mixed case (also sometimes referred to as "[camel case](https://en.wikipedia.org/wiki/Camel_case)" or "[Pascal case](https://en.wiktionary.org/wiki/Pascal_case)"), in which the first letter of each word is capitalized, prefer to capitalize abbreviations as single words, e.g., `StartRpc()` rather than `StartRPC()`."  https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.
___
*[`planning/graph_algorithms/test/max_clique_test.cc` line 38 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-NigTWqgCUAZvsNEIHpO:-Nijiycg1GD0Zq7qeFf-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0c2db41b8511310fc2f15bce3ce5df2a567891b/planning/graph_algorithms/test/max_clique_test.cc#L38)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

`clang` is refusing to compile this line, because `CompareMatrices()` is using `abs()` internally on `bool` elements, and the compiler rightly points out that is a no-op.

Consider something like `.cast<int>()` on the arguments here.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Dismissed @wernerpe from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20401#-:-Nik04wH2sugxR_KZL_n:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sadraddini,wernerpe

**Pull request merged**
