### PR TITLE
pybind11 docs: Monkey patch sphinx to get custom sorted docs

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Resolves: https://github.com/RobotLocomotion/drake/issues/12604

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12787)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
+@EricCousineau-TRI for feature review, please.

**Comment by jwnimmer-tri** [comment]
I think if we are going to copy code from another project into Drake, we need to note and follow its license.

**Comment by m-chaturvedi** [comment]
*nonetheless

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/doc/pydrake_sphinx_extension.py, line 338 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12787#-M1dCknbAbPMOalV6M61:-M2ke9fG2g-JeVoYo-pe:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/d17c4a437dfa82b18e8f88345047332cba547120/bindings/pydrake/doc/pydrake_sphinx_extension.py#L338)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha! Can you add a comment, like:
```
# N.B. This follows suite with the following 3.x code: {url}
```
</blockquote></details>

OK

**Pull request merged**
