### PR TITLE
Implement FemModel::Clone()

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
In addition, widen the scalar support for some FEM classes.

See #21357 for the full picture. Towards #21355.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

I'm kicking off a PR train for pieces of #21357

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-:-NxEz3OT5i1GxNKnzsUM:bdpbujw)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
Thanks @xuchenhan-tri, it helps a lot having this in a separate PR.

Besides small comments, my only question here is why the support for `symbolic::Expression`. Is that realistic?

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-:-NxIeHwPEg9oQIzvjuvy:bwif3vw)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/fem/dirichlet_boundary_condition.h` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxIc8M36zJ3Y4CQKzLK:-NxIc8M36zJ3Y4CQKzLL:b-6jo2xd) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/dirichlet_boundary_condition.h#L109)):*
> ```objc
> }  // namespace drake
> 
> DRAKE_DECLARE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
> ```

ditto, do we want to support `symbolic::Expression`? is it reasonable?
___
*[`multibody/fem/fem_model.cc` line 116 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxIbZuQ0jn8yn_Glp19:-NxIbZuQ0jn8yn_Glp1A:bk214gg) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/fem_model.cc#L116)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
> ```

do we really want to support `symbolic::Expression`?
___
*[`multibody/fem/fem_model_impl.h` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxIdKNbEqPSKdARZJ6B:-NxIdKNbEqPSKdARZJ6C:b-5osefh) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/fem_model_impl.h#L75)):*
> ```objc
>   /** Copies all data members, except those modified in DeclareCacheEntries(),
>    from the `other` FemModelImpl to `this` FemModelImpl . */
>   void SetFrom(const FemModelImpl<Element>& other) {
> ```

You might be thinking this might do more in the future. But for now, I'd just call it something more specifici, like "CopyElementsFrom()".

fyi, if `FemModelImpl` was using standard CRTP, you'd know the type of the derived class and the implementation to `DoClone()` could live here without the need for this method.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/fem/fem_model.cc` line 116 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxIbZuQ0jn8yn_Glp19:-NxJ3pig7D-Q0uwToIuV:bgm01j9) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/fem_model.cc#L116)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we really want to support `symbolic::Expression`?
</blockquote></details>

I'm not planning on actually support `symbolic::Expression`. This explicit instantiation is only used to prevent undefined references for `DeforambleModel<symbolic::Expression>`.
___
*[`multibody/fem/fem_model_impl.h` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxIdKNbEqPSKdARZJ6B:-NxIwtT9DsBMbSpTHnqn:b-atchha) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/fem_model_impl.h#L75)):*
> You might be thinking this might do more in the future. But for now, I'd just call it something more specifici, like "CopyElementsFrom()".

Functionally this function copies the elements, but as documented in the contract of this function, it must copy *all* data members untouched by `DeclareCacheEntries`. The name `CopyElementsFrom` is technically correct but misleading.

> fyi, if `FemModelImpl` was using standard CRTP, you'd know the type of the derived class and the implementation to `DoClone()` could live here without the need for this method.

This is not a CRTP class.

**Review by amcastro-tri — COMMENTED** [review]
per f2f with @xuchenhan-tri, we won't support `symbolic::Expression` for the heavy FEM implementation internals. However, we do need to `DRAKE_DEFINE` this minium set of very light classes in order to support `DeformableModel<symbolic::Expression>`, as required in #21357.

:lgtm: 

+@rpoyner-tri for platform review please.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-:-NxJXus02AsDvkiBg2xo:b43yur4)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-:-NxJfLG50_5_PR7eaoRn:bnfp4nl)* status: 1 unresolved discussion

___
*[`multibody/fem/test/fem_model_test.cc` line 401 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxJf-xL4jUC_wcgkn6r:-NxJf-xMA2chp6V9f-ds:b-ys8txv) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/test/fem_model_test.cc#L401)):*
> ```cpp
>   builder.Build();
> 
>   /* Create a BC and add it to the model. */
> ```

nit prefer spelling out "boundary condition" here.



_Code quote:_
```cpp
BC
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21400)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri

___
*[`multibody/fem/test/fem_model_test.cc` line 401 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21400#-NxJf-xL4jUC_wcgkn6r:-NxKYLzpA7lE9RRUWsbO:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/28122801d53313c8a595e227c6ef3f747ae1c618/multibody/fem/test/fem_model_test.cc#L401)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit prefer spelling out "boundary condition" here.
</blockquote></details>

Done

**Pull request merged**
