### PR TITLE
Migrate VectorInterface::set_value to use Eigen::Ref.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for feature and platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2504)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I believe this was already conceptually discussed in the most recent System2 PR, and the experts seemed happy with it.

:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Migrate VectorInterface::set\_value to use Eigen::Ref\.
> 
> @jwnimmer-tri for feature and platform review
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2504#-:-KJHgjbwk5-sjznYSzOC:1146049963)*

**Comment by sherm1** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I believe this was already conceptually discussed in the most recent System2 PR, and the experts seemed happy with it.
> 
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2504#-:-KJHuwn8XQzQ7v1uJ9xR:1417088721)*

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

Mac glitch?

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
