### PR TITLE
Implements DiscreteTimeIntegrator primitive

### PR DESCRIPTION
**Pull request by RussTedrake**
Note: unfortunately, there is already an
multibody::fem::internal::DiscreteTimeIntegrator. My thinking is that, while not ideal, this is ok because that class in internal.

+@sherm1 for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
@RussTedrake looks like the main header and cc file didn't get pushed? I see the Python wrapping but not the thing to wrap.
CI isn't happy.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-:-NuRD3fz3OjzuD_r8SXd:bef39n5)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few minor comments, PTAL

> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-:-NuaFrgy2oL19eSYs0Ko:b1ygeji)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/primitives/discrete_time_integrator.h` line 17 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaAhxI6M7i3AmbFvLc:-NuaAhxI6M7i3AmbFvLd:b-n95h4l) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/discrete_time_integrator.h#L17)):*
> ```objc
> };
> 
> /// A discrete-time integrator for a vector input.
> ```

BTW please consider adding a few equations showing exactly what's computed here.  Both the discrete behavior and how that is mapped to continuous time (i.e. if someone asks for y(t) for some arbitrary t) are interesting and not totally obvious (to me anyway). Looks like there is a manually-settable initial condition also. If I set that and then immediately ask for y, do I see the new IC? Or only after a sample is taken?
___
*[`systems/primitives/discrete_time_integrator.h` line 34 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaAFUn5UtAP63Fkqzo:-NuaAFUn5UtAP63Fkqzp:bt7xgdr) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/discrete_time_integrator.h#L34)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(DiscreteTimeIntegrator)
> 
>   /// Constructs an %Integrator system.
> ```

nit "an %Integrator" -> "a %DiscreteTimeIntegrator"
___
*[`systems/primitives/test/discrete_time_integrator_test.cc` line 35 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaFdjY0pVogNoO-_BG:-NuaFdjY0pVogNoO-_BH:btsvrhp) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/test/discrete_time_integrator_test.cc#L35)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(
>       x + kTimeStep * u,
>       integrator.EvalUniquePeriodicDiscreteUpdate(*context).value(), 1e-14));
> ```

minor: should have a test that the output port shows the state properly, and responds as expected to set_integral_value().

**Review by sherm1 — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-:-NuaGB1z9rrQjv4m28Jf:bud92lo)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Looks good to me. I'll go over this again and stamp when the feature review comments are addressed.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-:-NubBJs6EpZS7IjsdiM4:b-tzu83p)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaHjUh8QlIdWWnuZ2s):*
oops, sorry!



_Code quote:_
```
multibody::fem::internal::DiscreteTimeIntegrator
```
___
*[`systems/primitives/discrete_time_integrator.h` line 17 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaAhxI6M7i3AmbFvLc:-Nub6zWoE7IL5LDAfhQb:b7i1kf5) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/discrete_time_integrator.h#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please consider adding a few equations showing exactly what's computed here.  Both the discrete behavior and how that is mapped to continuous time (i.e. if someone asks for y(t) for some arbitrary t) are interesting and not totally obvious (to me anyway). Looks like there is a manually-settable initial condition also. If I set that and then immediately ask for y, do I see the new IC? Or only after a sample is taken?
</blockquote></details>

FWIW it's not clear to me either what exactly the computation is just by looking at the doc. In particular, I wasn't 100% sure that u is the derivative until checking the impl.

We should also clarify the IC is zero by default.
___
*[`systems/primitives/discrete_time_integrator.h` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nub92Ke0mbsiLlhohj8:-Nub92Ke0mbsiLlhohj9:brjftxg) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/discrete_time_integrator.h#L38)):*
> ```objc
>   /// @param time_step the discrete time step.
>   /// @pre size > 0. time_step > 0.
>   explicit DiscreteTimeIntegrator(int size, double time_step,
> ```

BTW this is fine but the value of the explicit keyword is diminished with multiple arguments in the constructor

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 17 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaAhxI6M7i3AmbFvLc:-NucnF2qB7QA4mugrHvM:b-19xu5k) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/discrete_time_integrator.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FWIW it's not clear to me either what exactly the computation is just by looking at the doc. In particular, I wasn't 100% sure that u is the derivative until checking the impl.

We should also clarify the IC is zero by default.
</blockquote></details>

Done.  PTAL.
___
*[`systems/primitives/discrete_time_integrator.h` line 34 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaAFUn5UtAP63Fkqzo:-Nucj5PmElAIgpEOrXH3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/discrete_time_integrator.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit "an %Integrator" -> "a %DiscreteTimeIntegrator"
</blockquote></details>

Done.
___
*[`systems/primitives/test/discrete_time_integrator_test.cc` line 35 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-NuaFdjY0pVogNoO-_BG:-NucnrzY9kc0wDhCElNu:bmfxq1z) ([raw file](https://github.com/RobotLocomotion/drake/blob/af25c777270a42c1538dc8b6fb2f07afc5c82852/systems/primitives/test/discrete_time_integrator_test.cc#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should have a test that the output port shows the state properly, and responds as expected to set_integral_value().
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2Q-PCkFK3KJSocaQ:-Nue2Q-PCkFK3KJSocaR:bn6hb9t) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L22)):*
> ```objc
> name: DiscreteTimeIntegrator
> input_ports:
> - u
> ```

BTW, this is precluding multistep methods, right?

I also don't quite see how exactly this would work for something like backward Euler where `u` often needs to be function of `x_{n+1}`. Could you say something about what's your plan for those? Providing some context on what system this will be used towards would be helpful.
___
*[`systems/primitives/discrete_time_integrator.h` line 35 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue17013VPT0fFna-um:-Nue17023_d13e-N93L3:bq28io4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L35)):*
> ```objc
> ```
> where xᵢₙᵢₜ = 0 by default. Use set_integral_value() to set x_n in the context.
> The output at time `t` is `xₙ` where `n = floor(t/h)`.
> ```

I _think_ this is incorrect. See https://drake.mit.edu/doxygen_cxx/group__discrete__systems.html. According to the documentation there, this should be closer to `n = floor(t/h)` (though not quite exactly). I think we need a unit test to confirm what the correct behavior is in the middle of a step (e.g. t = 0.5 * h).



_Code quote:_
```objc
The output at time `t` is `xₙ` where `n = floor(t/h)`
```

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2OvxDZvxfkacZ4We:-Nue2OvxDZvxfkacZ4Wf:b-uag9kd) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L30)):*
> ```objc
> time step `h` using the integration method `kExplicitEuler` is:
> ```
> xₙ₊₁ = xₙ + h uₙ  // update
> ```

BTW I was expecting something like
```
          tₙ+h
xₙ₊₁ = xₙ + ∫  uₙ(t) dt
          tₙ
```
where it would make sense to consider different integration methods. But if uₙ is really considered to be a constant over the step, then the integral is always huₙ and explicit Euler is the only possibility.

Can you clarify that?
___
*[`systems/primitives/discrete_time_integrator.h` line 34 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue23Dy42_JLJuIqIgF:-Nue23Dy42_JLJuIqIgG:brttesd) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L34)):*
> ```objc
> x₀ = xᵢₙᵢₜ        // initialize
> ```
> where xᵢₙᵢₜ = 0 by default. Use set_integral_value() to set x_n in the context.
> ```

nit: x_n -> xₙ

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2Q-PCkFK3KJSocaQ:-NuxHNSEABAzghwJTaZO:bik5h4s) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this is precluding multistep methods, right?

I also don't quite see how exactly this would work for something like backward Euler where `u` often needs to be function of `x_{n+1}`. Could you say something about what's your plan for those? Providing some context on what system this will be used towards would be helpful.
</blockquote></details>

Really good question.  I debated this a bit myself, and would appreciate your thoughts.

Of course we can be implicit, etc, wrt to the integrator state.  The strangeness comes from the exogenous input.  

Implicit/backward Euler is normally written as x[n+1] = x[n] + h f(t[n+1], x[n+1]).  But if we have inputs, I think that the best we could do in a causal system's framework would be something like x[n+1] = x[n] + h f(t[n+1], x[n+1], u[n]) .  Would we call that implicit / backwards Euler?  would we ever want that?    (The same goes for a multi-step integrator)

Of course, in the integrator system f(t,x,u) = u.  So I don't think there is a meaningful distinction between forward and backward euler here.  Similarly, the multistep methods will all have the same derivatives at the intermediate steps, so I guess those don't make sense either.

So maybe I should just remove the enum, and admit that this system will only ever do explicit Euler integration?  
___
*[`systems/primitives/discrete_time_integrator.h` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2OvxDZvxfkacZ4We:-NuxKUvH8M4JiFa0uzkJ:bxjs1dp) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I was expecting something like
```
          tₙ+h
xₙ₊₁ = xₙ + ∫  uₙ(t) dt
          tₙ
```
where it would make sense to consider different integration methods. But if uₙ is really considered to be a constant over the step, then the integral is always huₙ and explicit Euler is the only possibility.

Can you clarify that?
</blockquote></details>

Great! This is exactly the same discussion as above. 
___
*[`systems/primitives/discrete_time_integrator.h` line 34 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue23Dy42_JLJuIqIgF:-NuxSLWzES3h5ZlB7j--:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: x_n -> xₙ
</blockquote></details>

Done.
___
*[`systems/primitives/discrete_time_integrator.h` line 35 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue17013VPT0fFna-um:-NuxKosxBQhcSmyyKEtj:bbrgtrm) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I _think_ this is incorrect. See https://drake.mit.edu/doxygen_cxx/group__discrete__systems.html. According to the documentation there, this should be closer to `n = floor(t/h)` (though not quite exactly). I think we need a unit test to confirm what the correct behavior is in the middle of a step (e.g. t = 0.5 * h).
</blockquote></details>

Done. Good catch. I had forgotten that subtlety; which is still jarring to me.  I believe you meant `ceil` even though you wrote `floor` (which is what I already had)?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2Q-PCkFK3KJSocaQ:-NuyBqWL8zNNv9nA6eO-:bpsygf3) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L22)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Really good question.  I debated this a bit myself, and would appreciate your thoughts.

Of course we can be implicit, etc, wrt to the integrator state.  The strangeness comes from the exogenous input.  

Implicit/backward Euler is normally written as x[n+1] = x[n] + h f(t[n+1], x[n+1]).  But if we have inputs, I think that the best we could do in a causal system's framework would be something like x[n+1] = x[n] + h f(t[n+1], x[n+1], u[n]) .  Would we call that implicit / backwards Euler?  would we ever want that?    (The same goes for a multi-step integrator)

Of course, in the integrator system f(t,x,u) = u.  So I don't think there is a meaningful distinction between forward and backward euler here.  Similarly, the multistep methods will all have the same derivatives at the intermediate steps, so I guess those don't make sense either.

So maybe I should just remove the enum, and admit that this system will only ever do explicit Euler integration?
</blockquote></details>

I'd be happy with the "just Euler" solution. We could add options later if we find a use case.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2Q-PCkFK3KJSocaQ:-NuyV4cP7ku5rywzlI7k:b83cvup) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L22)):*
> But if we have inputs, I think that the best we could do in a causal system's framework would be something like x\[n+1\] = x\[n\] + h f(t\[n+1\], x\[n+1\], u\[n\])

Agreed.

 > Would we ever want that?

It's hard for me to form an opinion here because I'm not sure what the intended use case of this class is. It's definitely is counter-intuitive and need to be well explained (e.g. by actually writing down the equation x\[n+1\] = x\[n\] + h f(t\[n+1\], x\[n+1\], u\[n\])

> So maybe I should just remove the enum, and admit that this system will only ever do explicit Euler integration?

I'm fine with this, but I'd like to see what the plan is for other integration schemes **if** there's the intention to extend this system in the future.
___
*[`systems/primitives/discrete_time_integrator.h` line 35 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue17013VPT0fFna-um:-NuyWJ-eDE8HdHk3kixC:b18i8qi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L35)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done. Good catch. I had forgotten that subtlety; which is still jarring to me.  I believe you meant `ceil` even though you wrote `floor` (which is what I already had)?
</blockquote></details>

Yeah I meant `ceil`. There's some subtlety at integer multiples of `dt` because of the double-valueness, but  referencing the discrete system page is good enough for me. Thanks.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/primitives/discrete_time_integrator.h` line 22 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2Q-PCkFK3KJSocaQ:-NuyrjJ-81rkm5TENJ8l:b1xh5kc) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> But if we have inputs, I think that the best we could do in a causal system's framework would be something like x\[n+1\] = x\[n\] + h f(t\[n+1\], x\[n+1\], u\[n\])

Agreed.

 > Would we ever want that?

It's hard for me to form an opinion here because I'm not sure what the intended use case of this class is. It's definitely is counter-intuitive and need to be well explained (e.g. by actually writing down the equation x\[n+1\] = x\[n\] + h f(t\[n+1\], x\[n+1\], u\[n\])

> So maybe I should just remove the enum, and admit that this system will only ever do explicit Euler integration?

I'm fine with this, but I'd like to see what the plan is for other integration schemes **if** there's the intention to extend this system in the future.
</blockquote></details>

Done.  The immediate use case (breaking up the DiffIKIntegrator system) only needs Euler integration.  I was just trying to provide an API that could be more general for the future.  I've removed it.
___
*[`systems/primitives/discrete_time_integrator.h` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue2OvxDZvxfkacZ4We:-NuyrxBt6v6rxsbqjAbq:b-yyn562) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L30)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Great! This is exactly the same discussion as above.
</blockquote></details>

Done.  Kept it simple, since we're forward Euler only.
___
*[`systems/primitives/discrete_time_integrator.h` line 35 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-Nue17013VPT0fFna-um:-Nuys-Xt7rTIstcNhHwm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c55141a794c3e90633dba6db4284d6a949efd0d8/systems/primitives/discrete_time_integrator.h#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yeah I meant `ceil`. There's some subtlety at integer multiples of `dt` because of the double-valueness, but  referencing the discrete system page is good enough for me. Thanks.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Everything looks good now, thanks!

> Reviewed 1 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-:-NuzUuWgAf7clW9fx6i9:b-8wfgub)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by RussTedrake — COMMENTED** [review]
I considered a more specific name, but I think for discoverability, DiscreteTimeIntegrator is a good choice.  It also matches https://www.mathworks.com/help/simulink/slref/discretetimeintegrator.html (which, coincidentally, does support backward euler, etc).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21222#-:-Nv-0IiqChjfeuXHYP1K:buj5uhk)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

**Pull request merged**
