### PR TITLE
Rewrite demo_multi_car in System 2.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3456)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

/CC @maddog-tri if you are interested.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3456#-:-KRiLxNoNtjoYCwRbH1N:b-y6hkye)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3456#-:-KRiRAcqsfBNr4_jhw3C:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@sammy-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3456#-:-KRj6kETbktwgIfMwX83:bq11ftp)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3456#-:-KRj97uJGRsqdtFxxQkM:bnfp4nl)*

**Pull request merged**
