### PR TITLE
Rod2d + implicit integrator

### PR DESCRIPTION
**Pull request by edrumwri**
Uses the new implicit integrator to simulate the 2D rod modeled using compliant contact.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6267)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-:-Klzqm--jXAmUunZhoFs:brbsdox)*

**Comment by amcastro-tri** [comment]
Beautiful!. I wonder Evan if you'd like to have one of these smoke tests for the implicit integrator case in the BUILD file. Now you have `rod2d_sim` with `add_test_rule = 1`. Maybe worth having a target `rod2d_sim_timestepping` and another target `rod2d_compliant` (`test_rule_args = [" --sim_duration=0.01", "--simulation_type 'compliant'"]` each with their own smoke test?

Besides this little comment :lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-:-Km23E_6x4pPbnFf1jCd:b-il2nel)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267)*

**Comment by edrumwri** [comment]
+@ggould-tri for platform review, per regular rotation please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-:-Km2ias8bccaf-OCJ7JY:b1nfowd)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/rod2d/rod2d_sim.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-Km2lP8g3x-8NFYlKWo6:-Km2lP8hN0OjDZlY9kzj:b1dwmjw) ([raw file](https://github.com/robotlocomotion/drake/blob/7217ad4d48fed218be462dff108ecfdf193de338/drake/examples/rod2d/rod2d_sim.cc#L137)):*
> ```cpp
>   Simulator<double> simulator(*diagram, std::move(context));
>   if (FLAGS_simulation_type == "compliant") {
>     auto context = simulator.get_mutable_context();
> ```

FYI Shadowing the name `context` here when the underlying `context` is in an undefined state (as opposed to a slightly different representation of the same context) is inviting confusion.

---

*[drake/examples/rod2d/rod2d_sim.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-Km2kOs3jo3U2lmQtHub:-Km2kOs3jo3U2lmQtHuc:bxdvspk) ([raw file](https://github.com/robotlocomotion/drake/blob/7217ad4d48fed218be462dff108ecfdf193de338/drake/examples/rod2d/rod2d_sim.cc#L142)):*
> ```cpp
>   } else {
>     simulator.reset_integrator<RungeKutta3Integrator<double>>(*diagram,
>                                                               context);
> ```

Using context after it was `std::move`d from.

Context seems to be a `std::unique_ptr`; the spec says that after a move a std object is in a "valid but unspecified" state, which I think means you are UBbing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267)*

**Comment by edrumwri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/rod2d/rod2d_sim.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-Km2lP8g3x-8NFYlKWo6:-Km2qauqBCZMXt0tkKZa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7217ad4d48fed218be462dff108ecfdf193de338/drake/examples/rod2d/rod2d_sim.cc#L137)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Shadowing the name `context` here when the underlying `context` is in an undefined state (as opposed to a slightly different representation of the same context) is inviting confusion.
</blockquote></details>

Done.

---

*[drake/examples/rod2d/rod2d_sim.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-Km2kOs3jo3U2lmQtHub:-Km2qbQ_1UrPYxKFBkMi:b7o1oz1) ([raw file](https://github.com/robotlocomotion/drake/blob/7217ad4d48fed218be462dff108ecfdf193de338/drake/examples/rod2d/rod2d_sim.cc#L142)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Using context after it was `std::move`d from.

Context seems to be a `std::unique_ptr`; the spec says that after a move a std object is in a "valid but unspecified" state, which I think means you are UBbing.
</blockquote></details>

Done. (CI failure caught this too, FYI, so good to know my tests are doing what they should be)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6267#-:-Km2uU8VvfIyZXW5QL9d:bnfp4nl)*

**Pull request merged**
