### PR TITLE
optitrack_pose_extractor: Improve error message. Add `GetPose` for non-systems queries

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
When tinkering with the optitrack setup, I found I wanted to know the ID of the object that couldn't be found. This fixes that.

Additionally, in Anzu, the current implementation of one of our demos does a lot of LCM shindiggery to get Optitrack information. This adds `GetPose`, to consolidate that functionality (given that the object ID and `X_WO` is already contained within `OptitrackPoseExtrator`).

\cc @naveenoid on the visibility of `PoseSmoother`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8312)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@avalenzu for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-:-L77tznF6S9jPJZXbv9v:b-dmiczy)*

**Comment by sherm1** [comment]
:lgtm: with one BTW question.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[manipulation/perception/test/optitrack_pose_extractor_test.cc, line 127 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-L7840qf2Myal45nTJxU:-L7840qf2Myal45nTJxV:b-ernnsf) ([raw file](https://github.com/robotlocomotion/drake/blob/a3c96f96dc2b2768025fb384e2d9af62d2a9ca9c/manipulation/perception/test/optitrack_pose_extractor_test.cc#L127)):*
> ```cpp
>   // Compare quaternions.
>   EXPECT_TRUE(CompareMatrices(extracted_pose.linear(), test_pose.linear(),
>                               1e-3, MatrixCompareType::absolute));
> ```

BTW this is a surprisingly loose tolerance. Why 1e-3 rather than 1e-14 ish? Where does the 11 orders of magnitude of accuracy go? If this is right can you add a comment saying why it has to be so loose?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-:-L784Uy_Ba2GaO7TFEFe:b-f9fzeg)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/perception/test/optitrack_pose_extractor_test.cc, line 127 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-L7840qf2Myal45nTJxU:-L78A6JE8KhUnLq_HXR0:bypa97k) ([raw file](https://github.com/robotlocomotion/drake/blob/a3c96f96dc2b2768025fb384e2d9af62d2a9ca9c/manipulation/perception/test/optitrack_pose_extractor_test.cc#L127)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is a surprisingly loose tolerance. Why 1e-3 rather than 1e-14 ish? Where does the 11 orders of magnitude of accuracy go? If this is right can you add a comment saying why it has to be so loose?
</blockquote></details>

Done. Not exactly sure, but I'm guessing it may be due to the messages using floats, lowering the effective epsilon? (wrote this way for now)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312)*

**Comment by avalenzu** [comment]
:lgtm: with one BTW on naming.

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/perception/optitrack_pose_extractor.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7AGxrWVvI6T5k-keqE:-L7AGxrXYzVwFIvNUdT_:brcnobc) ([raw file](https://github.com/robotlocomotion/drake/blob/e52a9d53a4412af9b2f5310b4335c748aafdb340/manipulation/perception/optitrack_pose_extractor.h#L42)):*
> ```objc
>    * containing the LCM message.
>    */
>   Isometry3<double> GetPose(const systems::AbstractValue& message) const;
> ```

BTW Maybe `ExtractPose()` or `GetPoseFromMessage()`? `GetPose()` makes me think that this is returning something stored in the object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-:-L7AHhzYuDB2AaU8S5F3:bfiwuw5)*

**Comment by EricCousineau-TRI** [comment]
Minor scope change: Revamped PR to incorporate some of +@sammy-tri 's work from this branch:
https://github.com/sammy-tri/drake/blob/8e02ab0/manipulation/perception/optitrack_pose_extractor.cc#L18
https://github.com/sammy-tri/drake/blob/8e02ab0/examples/kinova_jaco_arm/dev/pick_and_place/jaco_lcm_planner.cc#L129

Also, eliminated a redundant test.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/perception/optitrack_pose_extractor.h, line 42 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-L7AGxrWVvI6T5k-keqE:-L7AfcXSEXc76X15XeFu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e52a9d53a4412af9b2f5310b4335c748aafdb340/manipulation/perception/optitrack_pose_extractor.h#L42)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW Maybe `ExtractPose()` or `GetPoseFromMessage()`? `GetPose()` makes me think that this is returning something stored in the object.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-:-L7AfdIS0r44FZF3gXTZ:bbw082)*

**Comment by sammy-tri** [comment]
:lgtm: (with one more BTW)

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manipulation/perception/optitrack_pose_extractor.h, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7BHJR4-OslnIPg0m4S:-L7BHJR4-OslnIPg0m4T:b-99zg1y) ([raw file](https://github.com/robotlocomotion/drake/blob/6c183ae5c838cad287253932197a451d6c67f0c9/manipulation/perception/optitrack_pose_extractor.h#L30)):*
> ```objc
>  * @returns Mapping from object ID to pose.
>  */
> inline std::map<int, Isometry3<double>> ExtractOptitrackPoses(
> ```

BTW it feels a little weird to bother inlining this function but not the function called inside the loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-:-L7BI4gLIpEWs7CF8wmC:bgfano)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[manipulation/perception/optitrack_pose_extractor.h, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7BHJR4-OslnIPg0m4S:-L7BTc7gy-HN913sj46u:bg6ai9u) ([raw file](https://github.com/robotlocomotion/drake/blob/6c183ae5c838cad287253932197a451d6c67f0c9/manipulation/perception/optitrack_pose_extractor.h#L30)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it feels a little weird to bother inlining this function but not the function called inside the loop.
</blockquote></details>

Done. (Tried to get away with it :P )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8312)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8312)*

**Comment by avalenzu** [comment]
Still :lgtm:, with a few more BTW.

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[manipulation/perception/optitrack_pose_extractor.cc, line 32 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7Pc71vKPs8hKhmRwrA:-L7Pc71vKPs8hKhmRwrB:b-xzu4wq) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/optitrack_pose_extractor.cc#L32)):*
> ```cpp
>   X_OB.translation() =
>       Eigen::Vector3d(body.xyz[0], body.xyz[1], body.xyz[2]);
>   X_OB.makeAffine();
> ```

BTW, is this necessary? There are *a lot* of places where we don't do this. I guess it's a moot point as we switch over to `math::Transform`, though.

---

*[manipulation/perception/optitrack_pose_extractor.h, line 34 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7PcYiu5wYKQQ2NI3vF:-L7PcYiu5wYKQQ2NI3vG:b-wtlzc3) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/optitrack_pose_extractor.h#L34)):*
> ```objc
> 
> /**
>  * Gets the rigid body index given an object ID.
> ```

BTW, it looks like this returns the object, not an index.

---

*[manipulation/perception/test/optitrack_pose_extractor_test.cc, line 167 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7PcpCStGWLWHim64lo:-L7PcpCStGWLWHim64lp:buw0ese) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/test/optitrack_pose_extractor_test.cc#L167)):*
> ```cpp
> 
>   EXPECT_EQ(*FindOptitrackObjectId(message, "test"), 10);
>   EXPECT_FALSE(FindOptitrackObjectId(message, "blerg").has_value());
> ```

FYI, that's `blergh`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-:-L7Pcy3vZZSL1Qt-LCTX:b-ykyumo)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/perception/optitrack_pose_extractor.h, line 34 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-L7PcYiu5wYKQQ2NI3vF:-L7QWhfX0O282_ueAG83:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/optitrack_pose_extractor.h#L34)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, it looks like this returns the object, not an index.
</blockquote></details>

Done.

---

*[manipulation/perception/optitrack_pose_extractor.cc, line 32 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-L7Pc71vKPs8hKhmRwrA:-L7QWUtN-8-9Mmu0HDO0:bgc6l40) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/optitrack_pose_extractor.cc#L32)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, is this necessary? There are *a lot* of places where we don't do this. I guess it's a moot point as we switch over to `math::Transform`, though.
</blockquote></details>

OK Yup, it's necessary because I believe `Isometry3<>` gets initialized as zeros, so you either have to initialize with `Isometry3<T>::Identity()` or call `makeAffine` (rather silly).

---

*[manipulation/perception/test/optitrack_pose_extractor_test.cc, line 167 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312#-L7PcpCStGWLWHim64lo:-L7QWogg87bifO0RDysT:b-el33dd) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/test/optitrack_pose_extractor_test.cc#L167)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

FYI, that's `blergh`.
</blockquote></details>

Done. :P

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8312)*

**Comment by avalenzu** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[manipulation/perception/optitrack_pose_extractor.cc, line 32 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8312#-L7Pc71vKPs8hKhmRwrA:-L7QYmc9YloJk2jtv1Om:bbc7gdb) ([raw file](https://github.com/robotlocomotion/drake/blob/cabf1adfa2418e02d8a968c0530e8180f4dc4c13/manipulation/perception/optitrack_pose_extractor.cc#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup, it's necessary because I believe `Isometry3<>` gets initialized as zeros, so you either have to initialize with `Isometry3<T>::Identity()` or call `makeAffine` (rather silly).
</blockquote></details>

Ah, I see. The call sites I'm remembering initialize with `Isometry3<T>::Identity()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8312)*

**Pull request merged**
