### PR TITLE
[math] more helpful error message in DecomposePSDmatrixIntoXtransposeTimesX

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15365)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15365#-:-MeLHbaB7OyeQj3b3ZRj:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15365#-:-MeLNm9q6Mle4wmI_GD7:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[math/test/quadratic_form_test.cc, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15365#-MeLNXdR9B09rdGSMToD:-MeLNXdR9B09rdGSMToE:b2f7yxt) ([raw file](https://github.com/robotlocomotion/drake/blob/96b62d0c8da934f51a44620fc5365b96a0ac63da/math/test/quadratic_form_test.cc#L86)):*
> ```cpp
>       std::runtime_error,
>       "Y is not positive definite. It has an eigenvalue -1 that is more "
>       "negative than the tolerance 0.");
> ```

nit. 0 should be 0.0, -1 should be -1.0 to pass the CI.

**Comment by RussTedrake** [comment]
___
*[math/test/quadratic_form_test.cc, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15365#-MeLNXdR9B09rdGSMToD:-MeLPIzcAgGdITtDkEj4:b-w7od8b) ([raw file](https://github.com/robotlocomotion/drake/blob/96b62d0c8da934f51a44620fc5365b96a0ac63da/math/test/quadratic_form_test.cc#L86)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit. 0 should be 0.0, -1 should be -1.0 to pass the CI.
</blockquote></details>

unfortunately, it's -1 and 0 on mac.  I'll make the string check use regex.

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15365#-:-MeLoAiBEzAJmL6_ZPvB:btfqah9)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[math/test/quadratic_form_test.cc, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15365#-MeLNXdR9B09rdGSMToD:-MeLo8eZ2_xchxuOoX1y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96b62d0c8da934f51a44620fc5365b96a0ac63da/math/test/quadratic_form_test.cc#L86)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

unfortunately, it's -1 and 0 on mac.  I'll make the string check use regex.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@seancurtis-tri +@ggould-tri (platform review switcheroo).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15365#-:-MePpk727LM9qVdJl7sp:b-sbf15l)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15365#-:-MeQYhaw7f2ciPIv6avW:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
