### PR TITLE
[geometry] Denote the Meshcat worker thread's lifecycle with an enum

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #16670.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16695)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.  I do think an enum makes the code clearer.

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: I think this is very clear.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16695#-:-MxZph4gEHUxgNiqS6bh:bttus7z)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
-@sammy-tri +@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: doc complaint

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16695#-:-Mxf-EOQCaeJiZH8T1dc:b-s01hl8)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.cc, line 504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16695#-MxexJlCEzx8OK4g05Mg:-MxexJlCEzx8OK4g05Mh:butb72d) ([raw file](https://github.com/robotlocomotion/drake/blob/a112d312686b625889a62abea003f5420e6fec22/geometry/meshcat.cc#L504)):*
> ```cpp
>   // destructor will not be run.
>   //
>   // Otherwise, the postconditions are that:
> ```

Are the two clauses below alternatives, or cumulative descriptions of the same outcome? I can make some sense of this paragraph by reading everything else, but the text here should be more clear.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16695)* status: 1 unresolved discussion (waiting on @ggould-tri and @rpoyner-tri)

___
*[geometry/meshcat.cc, line 504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16695#-MxexJlCEzx8OK4g05Mg:-Mxf04TLApd1-fEtbEO6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a112d312686b625889a62abea003f5420e6fec22/geometry/meshcat.cc#L504)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Are the two clauses below alternatives, or cumulative descriptions of the same outcome? I can make some sense of this paragraph by reading everything else, but the text here should be more clear.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16695)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
