### PR TITLE
[multibody] Remove unnecessary MbP includes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21623 and therefore also #20545.

The primary upside here is that changes to `discrete_update_manager.h` only rebuild a dozen files in the plant folder, rather than everything in Drake.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21625)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21625)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21625#-O0GiVN9721TEcg-GKEn:-O0GiVN9721TEcg-GKEo:b-g4275b) ([raw file](https://github.com/RobotLocomotion/drake/blob/8137b051a709d1d3de1c7f22ae01f5b40a3d1dc1/multibody/plant/multibody_plant.h#L29)):*
> ```objc
> #include "drake/multibody/plant/physical_model.h"
> #include "drake/multibody/tree/force_element.h"
> #include "drake/multibody/tree/frame.h"
> ```

FYI These new four additions aren't really required (the are included by tree-inl.h already) but these types *are* mentioned by the MbP API in earnest, so IWYU would encourage us to add them.  (I found their loss when I tried to drop the use of inl.h, which wasn't possible yet.)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule (tomorrow), please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2. Needs a rebase.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21625#-:-O0KOoV_AYkgfp3b_Cb3:b-1sz3jn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21625)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Pull request merged**
