### PR TITLE
Revert "Add support for AbstractValue input and output in System2."

### PR DESCRIPTION
**Pull request by sammy-tri**
Dear @david-german-tri,

The on-call build cop, $BUILD_COP, believes that your PR $NUMBER may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous/job/mac-clang-continuous-debug/631/
https://drake-jenkins.csail.mit.edu/view/Continuous/job/mac-clang-continuous-debug/631/
https://drake-jenkins.csail.mit.edu/view/Continuous/job/mac-clang-continuous-release/600/
(and more)

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3236)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by david-german-tri** [comment]
It looks extremely likely that the PR being reverted is the culprit.  

I am perplexed that there is a difference between clang-on-Linux and clang-on-Mac, such that the dynamic_cast succeeds on Linux and fails on Mac.  I'm unlikely to solve this within the hour (no Mac on hand for debugging) so feel free to merge as soon as CI passes.  Sadness.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 43 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3236#-:-KPxF687Hb7KOHYdqQmZ:bnfp4nl)*

**Comment by david-german-tri** [comment]
I strongly suspect this is case 2 ("having a class marked hidden in one binary and default in another") in 

http://www.russellmcc.com/posts/2013-08-03-rtti.html

**Comment by david-german-tri** [comment]
Update: nope, that was wrong.  I now think it might be case 1: "using a hidden class from outside its home binary".  `nm -mo build/drake/bin/adder_test | c++filt` reports a non-external typeinfo for `VectorValue<double>`, as does `nm -mo build/drake/lib/libdrakeSystemFramework.dylib | c++filt`.

**Comment by sherm1** [comment]
> a non-external typeinfo for VectorValue<double>

Does it also report a non-external typeinfo for the parent of that, `Value<VectorBase<double>*>` (I think), or the grandparent `AbstractValue`?

**Comment by david-german-tri** [comment]
> Does it also report a non-external typeinfo for the parent of that, Value<VectorBase<double>*>

Yes.

> or the grandparent AbstractValue?

No, because AbstractValue is not a template.

#3247 is the revert-revert, with fix.

**Comment by mwoehlke-kitware** [comment]
Thanks for the context. Hmm, seems like it's just an issue of exporting things correctly? I can't say I'd be enthusiastic about turning off hidden visibility if that's the only issue; after all, ensuring that stuff gets exported properly is one of the points of using it in the first place.

Reading through that article, I wonder if it would be possible to create an automated test for these sorts of issues?

**Pull request merged**
