### PR TITLE
RotationMatrix::ToQuaternion supports symbolic

### LINKED ISSUE #5274: RotationMatrix::ToQuaternion isn't compatible with symbolic::Expression
[rotmat2quat](https://github.com/RobotLocomotion/drake/blob/5f9d6b5e51e43ef6ca4e627fe8b5f4913b9d8470/drake/math/rotation_matrix.h#L23) contains comparisons, and thus isn't friendly to `symbolic::Expression`.  I think this limitation was introduced in #3604, which of course fixed some other problems.

The same problem exists in Eigen's built-in conversion, see https://eigen.tuxfamily.org/dox-devel/Quaternion_8h_source.html at line 767.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #5274.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11226)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This is a rough draft for now.  I need to go and figure out better unit tests.

\CC @siyuanfeng-tri @sherm1 @mitiguy FYI

**Comment by jwnimmer-tri** [comment]
(p.s. I'd forgotten how bad Eigen::Quaternion was.  I am glad we have a Drake one instead.)

**Comment by jwnimmer-tri** [comment]
... and because I was curious, here is the symbolic quaternion:

(((if ((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))) < 0) then -1 else 1) / sqrt((pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(0, 1) + m(1, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 2) + m(2, 0)) else (if (m(1, 1) >= m(2, 2)) then (m(1, 2) + m(2, 1)) else (1 - m(0, 0) - m(1, 1) + m(2, 2))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (m(0, 2) - m(2, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 1) + m(1, 0)) else (if (m(1, 1) >= m(2, 2)) then (1 - m(0, 0) + m(1, 1) - m(2, 2)) else (m(1, 2) + m(2, 1))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (1 + m(0, 0) - m(1, 1) - m(2, 2)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 1) + m(1, 0)) else (m(0, 2) + m(2, 0))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))), 2)))) * (if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))))

(((if ((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))) < 0) then -1 else 1) / sqrt((pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(0, 1) + m(1, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 2) + m(2, 0)) else (if (m(1, 1) >= m(2, 2)) then (m(1, 2) + m(2, 1)) else (1 - m(0, 0) - m(1, 1) + m(2, 2))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (m(0, 2) - m(2, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 1) + m(1, 0)) else (if (m(1, 1) >= m(2, 2)) then (1 - m(0, 0) + m(1, 1) - m(2, 2)) else (m(1, 2) + m(2, 1))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (1 + m(0, 0) - m(1, 1) - m(2, 2)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 1) + m(1, 0)) else (m(0, 2) + m(2, 0))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))), 2)))) * (if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (1 + m(0, 0) - m(1, 1) - m(2, 2)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 1) + m(1, 0)) else (m(0, 2) + m(2, 0))))))

(((if ((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))) < 0) then -1 else 1) / sqrt((pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(0, 1) + m(1, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 2) + m(2, 0)) else (if (m(1, 1) >= m(2, 2)) then (m(1, 2) + m(2, 1)) else (1 - m(0, 0) - m(1, 1) + m(2, 2))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (m(0, 2) - m(2, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 1) + m(1, 0)) else (if (m(1, 1) >= m(2, 2)) then (1 - m(0, 0) + m(1, 1) - m(2, 2)) else (m(1, 2) + m(2, 1))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (1 + m(0, 0) - m(1, 1) - m(2, 2)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 1) + m(1, 0)) else (m(0, 2) + m(2, 0))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))), 2)))) * (if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (m(0, 2) - m(2, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 1) + m(1, 0)) else (if (m(1, 1) >= m(2, 2)) then (1 - m(0, 0) + m(1, 1) - m(2, 2)) else (m(1, 2) + m(2, 1))))))

(((if ((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))) < 0) then -1 else 1) / sqrt((pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(0, 1) + m(1, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 2) + m(2, 0)) else (if (m(1, 1) >= m(2, 2)) then (m(1, 2) + m(2, 1)) else (1 - m(0, 0) - m(1, 1) + m(2, 2))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (m(0, 2) - m(2, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 1) + m(1, 0)) else (if (m(1, 1) >= m(2, 2)) then (1 - m(0, 0) + m(1, 1) - m(2, 2)) else (m(1, 2) + m(2, 1))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (1 + m(0, 0) - m(1, 1) - m(2, 2)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 1) + m(1, 0)) else (m(0, 2) + m(2, 0))))), 2) + pow((if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then (1 + m(0, 0) + m(1, 1) + m(2, 2)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then ( - m(1, 2) + m(2, 1)) else (if (m(1, 1) >= m(2, 2)) then (m(0, 2) - m(2, 0)) else ( - m(0, 1) + m(1, 0))))), 2)))) * (if (((m(0, 0) + m(1, 1) + m(2, 2)) >= m(0, 0)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(1, 1)) and ((m(0, 0) + m(1, 1) + m(2, 2)) >= m(2, 2))) then ( - m(0, 1) + m(1, 0)) else (if ((m(0, 0) >= m(1, 1)) and (m(0, 0) >= m(2, 2))) then (m(0, 2) + m(2, 0)) else (if (m(1, 1) >= m(2, 2)) then (m(1, 2) + m(2, 1)) else (1 - m(0, 0) - m(1, 1) + m(2, 2))))))

**Comment by sherm1** [comment]
> I'd forgotten how bad `Eigen::Quaternion` was. I am glad we have a Drake one instead.

Sorry to disappoint but we actually _don't_ have our own `Quaternion` class :(
We do have an extremely nice `RotationMatrix` class though that understands the general awfulness of `Eigen::Quaternion`.

**Comment by sherm1** [comment]
> here is the symbolic quaternion

OMG that's awful! Could be a lot nicer if we had a way to extract common subexpressions in the expression. Attempts to post-simplify, say for code generation, are not likely to be very successful.

But at least it works!

**Comment by jwnimmer-tri** [comment]
> OMG that's awful! Could be a lot nicer if we had a way to extract common subexpressions in the expression.

FWIW the common subexpressions are already shared in memory, just in to_string form get blatted out.  I bet we could write a to_string that emitted registers / named placeholders for the common expressions.

> Attempts to post-simplify, say for code generation, are not likely to be very successful.

Actually, when playing with earlier versions of this PR, I fed them into clang-8 it seemed to handle the CSE elimination and even a bunch of branch folding out of the gate.  Still about 8 branches instead of 4 for the native code, but it was very competitive.

**Comment by siyuanfeng-tri** [comment]
@mitiguy it's 5274 not 5724 :)
I ran into this problem when I tried to set the rotation distribution for free bodies in MBP, which only takes a symbolic quaternion. Our anzu side app side code generates poses as RigidTransform, and this issue came when I do pose.rotation().ToQuaternion(), where pose is a RigidTransform<Symbolic>

**Comment by jwnimmer-tri** [comment]
I agree.  I'll merge now so we can start using the symbolic form in our domain randomization right away, and we can amend this later if we want to.

**Pull request merged**
