### PR TITLE
[workspace] Upgrade scs to latest release 3.2.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Broken out from #16675, since there are meaningful code / test changes required.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16686)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI @hongkai-dai something with the newer revision of SCS is causing problems.  I haven't tried to investigate this at all yet.  I'll plan to circle back here tomorrow.

**Comment by hongkai-dai** [comment]
It seems the CI failure is due to the new solver fails to satisfy the tolerance used for the previous version. I think if we increase the tolerance in these unit test we should be fine.

**Comment by jwnimmer-tri** [comment]
In #15886 we specifically configure a tolerance of 1E-5 so that solver behaves as expected, and then unit test to 3E-5.  Some of the violations exceed 10E-5 now.  That seems to merit some digging, rather than papering over it?

**Comment by jwnimmer-tri** [comment]
The failing programs are:
- LinearProblems::kLinearFeasibilityProgram2
- FindSpringEquilibriumProblem::kProblem0
- QuadraticProblems::kQuadraticProgram3

```
[  FAILED  ] SCSTest/LinearProgramTest.TestLP/3, where GetParam() = (CostForm::kNonSymbolic, ConstraintForm::kNonSymbolic, LinearProblems::kLinearFeasibilityProgram2)
[  FAILED  ] SCSTest/LinearProgramTest.TestLP/8, where GetParam() = (CostForm::kNonSymbolic, ConstraintForm::kSymbolic, LinearProblems::kLinearFeasibilityProgram2)
[  FAILED  ] SCSTest/LinearProgramTest.TestLP/18, where GetParam() = (CostForm::kSymbolic, ConstraintForm::kNonSymbolic, LinearProblems::kLinearFeasibilityProgram2)
[  FAILED  ] SCSTest/LinearProgramTest.TestLP/23, where GetParam() = (CostForm::kSymbolic, ConstraintForm::kSymbolic, LinearProblems::kLinearFeasibilityProgram2)
[  FAILED  ] SCSTest/TestFindSpringEquilibrium.TestSOCP/0, where GetParam() = FindSpringEquilibriumProblem::kProblem0
[  FAILED  ] ScsTest/QuadraticProgramTest.TestQP/3, where GetParam() = (CostForm::kNonSymbolic, ConstraintForm::kNonSymbolic, QuadraticProblems::kQuadraticProgram3)
[  FAILED  ] ScsTest/QuadraticProgramTest.TestQP/8, where GetParam() = (CostForm::kNonSymbolic, ConstraintForm::kSymbolic, QuadraticProblems::kQuadraticProgram3)
[  FAILED  ] ScsTest/QuadraticProgramTest.TestQP/13, where GetParam() = (CostForm::kNonSymbolic, ConstraintForm::kFormula, QuadraticProblems::kQuadraticProgram3)
```

**Comment by hongkai-dai** [comment]
Here is a summary on the failed tests
1. Some of the tests previously with a comparison tolerance of 3e-5, now the error is around 7e-5 in LinearProblems::kLinearFeasibilityProgram2, and 4.5E-5 in QuadraticProgram3
2. Some tests previously use a comparison tolerance of 1E-4, now the error is about 1.2E-4 in TestFindSpringEquilibrium

In both cases, although the solver becomes less accurate, it degrades only a bit.

> In https://github.com/RobotLocomotion/drake/pull/15886 we specifically configure a tolerance of 1E-5 so that solver behaves as expected, and then unit test to 3E-5. Some of the violations exceed 10E-5 now.

We actually use 1E-4 as the default tolerance, where the solver parameter `eps` is set to 1E-5. As explained in https://github.com/RobotLocomotion/drake/blob/1ae9f9355eb6ab48d39e5e0715db4be4580041c3/solvers/test/scs_solver_test.cc#L21-L23

That `eps=1E-5` means that the feasibility tolerance is 1E-5 (https://www.cvxgrp.org/scs/api/settings.html#settings), meaning that all the linear constraints are satisfied within an order of 1E-5 (a more detailed explanation is in https://www.cvxgrp.org/scs/algorithm/index.html#termination). This doesn't mean that the SCS solution (the value of the decision variables) is within `eps` to the true solution. It is very common for the solution of decision variables to have an error larger than eps. We choose 1E-4 in our test as the tolerance, but that tolerance is purely empirical.

Hence I propose to increase the tolerance in the test.

**Comment by jwnimmer-tri** [comment]
> Hence I propose to increase the tolerance in the test.

Is there any way we can reason about what the maximum valid tolerance would be and bump it up to that immediately, so we don't need to keep chasing our tail upon every upgrade?  Or reformulate the test to check against numbers that have a basis in the problem formulation, where we can reason more carefully about a tolerance, such as checking the constraint violations (vs the tolerance) instead of the decision variables themselves?

**Comment by hongkai-dai** [comment]
> Or reformulate the test to check against numbers that have a basis in the problem formulation, where we can reason more carefully about a tolerance, such as checking the constraint violations (vs the tolerance) instead of the decision variables themselves

I thought about this option before, and here is why I think it is very challenging to do
1. We need to check not only the constraint satisfaction, but also the optimality of the solution (there are infinitely many solution satisfying the constraint, but only one is optimal). Typically the optimality condition is to check the gap between the primal solution and the dual solution, which means I have to formulate the optimization problem in a different way (the dual formulation) and then compute the duality gap explicitly. Not saying this is impossible, but would require a huge amount of work in general (although it would be easier for linear programs, and maybe for quadratic programs as well).
2. We write this test for different solvers, and each solver has their own termination criteria. We will then have to check the termination condition for each solver.

> Is there any way we can reason about what the maximum valid tolerance would be and bump it up to that immediately, so we don't need to keep chasing our tail upon every upgrade?

Sorry, I am afraid I don't know a good tolerance

I can change the test to check the termination condition for the failed test LinearProblems::kLinearFeasibilityProgram2 (even this would take quite some efforts), but it would require huge amount of work if we make similar changes for all the tests.

**Comment by jwnimmer-tri** [comment]
Okay, thanks, I'll need to go study the details further (but not as part of this PR).  I'll see what I can do about tweaking the tolerances here.

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.  For the two tolerance definitions that the upgrade violated, I've increased them to the nearest power of ten.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  +@ggould-tri for Thursday's platform review.

Sorry for the belated feature review.

> Reviewed 1 of 2 files at r1, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16686#-:-MxC4_AB8BgIEM2qYYmj:bih8xc)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
(It's no problem.  The only reason we have a schedule for dependency upgrades is so that they don't linger indefinitely.  Taking a few days to look it over has been no trouble at all.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16686#-:-MxEu_2zCmwXUDRnWW32:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Pull request merged**
