### PR TITLE
[py trajectories] support passing matrix coefficients to ZeroOrderHold

### PR DESCRIPTION
**Pull request by RussTedrake**
Related to #15427

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433#-:-Mf2SXbs5WyTLg9iwprz:b-gw3fti)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433#-:-Mf3KkEC2qH-edLM9mxI:b-n37teh)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/trajectories_py.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3Je68AcpxC37CSB2N:-Mf3Je68AcpxC37CSB2O:b7l285u) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/trajectories_py.cc#L121)):*
> ```cpp
>                 breaks.size(), Eigen::VectorXd(samples.size()));
>             for (int row = 0; row < static_cast<int>(samples.size()); ++row) {
>               DRAKE_DEMAND(samples[row].size() == breaks.size());
> ```

nit In case the pydrake user passes in something other than a numpy, e.g., a list-of-lists-of-double, and happens to accidentally mismatch the list sizes, I think it would be kinder for them to receive a `RuntimeError` instead of a `SystemExit`, thus `DRAKE_THROW_UNLESS` seems better than `DRAKE_DEMAND`.
___
*[bindings/pydrake/trajectories_py.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3Kq0j9m_cw1GquWxp:-Mf3Kq0j9m_cw1GquWxq:bo2gne0) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/trajectories_py.cc#L126)):*
> ```cpp
>                 vec[col](row, 0) = samples[row][col];
>               }
>             }
> ```

nit It seems to me like several factory functions (FirstOrderHold, etc.) will all require the "row-major transpose" idiom used here.

In anticipation of that, and for greater clarity here, I suspect we should have a helper free function atop this file, like so:

```c++
// For bindings that want a `const Ref<MatrixX<T>>&` but are bound
// via a `const vector<vector<T>>&` for overloading priority,
// this function converts the input to a proper MatrixX.  The
// key point is that a numpy matrix is row-major, so a 2x3 samples
// numpy array (unfortunately) turns into a std::vector with 2
// elements, each a vector of 3 elements; we'll transpose that.
Eigen::MatrixXd MakeEigenFromRowMajorVectors(
    const std::vector<std::vector<T>>& in) {
  ...
}
```

In that case, the binding lambda is a much more obvious one-liner:
```c++
return PiecewisePolynomial<T>::ZeroOrderHold(
    breaks, MakeEigenFromRowMajorVectors(samples));
```
___
*[bindings/pydrake/test/trajectories_test.py, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3ISY_DNRXRa3h68xk:-Mf3ISY_DNRXRa3h68xl:bheijr9) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/test/trajectories_test.py#L77)):*
> ```Python
>         pp = PiecewisePolynomial([p1, p2], [0, 1, 2])
> 
>     def test_zero_order_hold(self):
> ```

nit Rename to `test_zero_order_hold_vector` to maintain parallel naming with the below twin?
___
*[bindings/pydrake/test/trajectories_test.py, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3IhJW3RpTkZ4Pp9yW:-Mf3IhJW3RpTkZ4Pp9yX:bs8op5o) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/test/trajectories_test.py#L90)):*
> ```Python
>         self.assertEqual(pp.get_number_of_segments(), 2)
>         self.assertEqual(pp.start_time(), 0.)
>         self.assertEqual(pp.end_time(), 2.)
> ```

nit In the below test, we explicitly check `rows()` and `cols()`, even though the shape of `value()` also indirectly checks the shape.  Should we also check them here, since the bindings lambda is non-trivial for this `doc_vector` overload, moreso that the other overload?
___
*[bindings/pydrake/test/trajectories_test.py, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3HQJ8-WMRNZQkF_er:-Mf3HQJ9DvNSoXhsLcjt:b-e2iseb) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/test/trajectories_test.py#L107)):*
> ```Python
>         self.assertEqual(pp.end_time(), 2.)
>         self.assertEqual(pp.rows(), 2)
>         self.assertEqual(pp.cols(), 2)
> ```

The shape of A is 2x2, but if I understand correctly, then in general it need not be square?  In the issue discussions it seemed like row-major vs column-major was of possible concern in the bindings, so perhaps this test case should use a non-square A, to be as general as possible?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/trajectories_py.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3Je68AcpxC37CSB2N:-Mf3pE8EBtlvSqOyHvKm:b-1anat2) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/trajectories_py.cc#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In case the pydrake user passes in something other than a numpy, e.g., a list-of-lists-of-double, and happens to accidentally mismatch the list sizes, I think it would be kinder for them to receive a `RuntimeError` instead of a `SystemExit`, thus `DRAKE_THROW_UNLESS` seems better than `DRAKE_DEMAND`.
</blockquote></details>

Done.  Nice.
___
*[bindings/pydrake/trajectories_py.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3Kq0j9m_cw1GquWxp:-Mf3r2i_D0XknZj253Hz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/trajectories_py.cc#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It seems to me like several factory functions (FirstOrderHold, etc.) will all require the "row-major transpose" idiom used here.

In anticipation of that, and for greater clarity here, I suspect we should have a helper free function atop this file, like so:

```c++
// For bindings that want a `const Ref<MatrixX<T>>&` but are bound
// via a `const vector<vector<T>>&` for overloading priority,
// this function converts the input to a proper MatrixX.  The
// key point is that a numpy matrix is row-major, so a 2x3 samples
// numpy array (unfortunately) turns into a std::vector with 2
// elements, each a vector of 3 elements; we'll transpose that.
Eigen::MatrixXd MakeEigenFromRowMajorVectors(
    const std::vector<std::vector<T>>& in) {
  ...
}
```

In that case, the binding lambda is a much more obvious one-liner:
```c++
return PiecewisePolynomial<T>::ZeroOrderHold(
    breaks, MakeEigenFromRowMajorVectors(samples));
```
</blockquote></details>

Done.
___
*[bindings/pydrake/test/trajectories_test.py, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3ISY_DNRXRa3h68xk:-Mf3rBY5AdSO4Adg2M4N:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/test/trajectories_test.py#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Rename to `test_zero_order_hold_vector` to maintain parallel naming with the below twin?
</blockquote></details>

Done.
___
*[bindings/pydrake/test/trajectories_test.py, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3IhJW3RpTkZ4Pp9yW:-Mf3rUdF1rwrjFo64cWt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/test/trajectories_test.py#L90)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In the below test, we explicitly check `rows()` and `cols()`, even though the shape of `value()` also indirectly checks the shape.  Should we also check them here, since the bindings lambda is non-trivial for this `doc_vector` overload, moreso that the other overload?
</blockquote></details>

Done.
___
*[bindings/pydrake/test/trajectories_test.py, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3HQJ8-WMRNZQkF_er:-Mf3rXoS5TZg0GeZX6Rc:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/4d29793b0ee0578b23c1a486223a00a964ddca90/bindings/pydrake/test/trajectories_test.py#L107)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The shape of A is 2x2, but if I understand correctly, then in general it need not be square?  In the issue discussions it seemed like row-major vs column-major was of possible concern in the bindings, so perhaps this test case should use a non-square A, to be as general as possible?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433#-:-Mf3tuRM0pR63yzfWHJz:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

___
*[bindings/pydrake/trajectories_py.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3t3kmE_zWh14qwSuu:-Mf3t3knBxMa2a6XgXCl:b-3ssttw) ([raw file](https://github.com/robotlocomotion/drake/blob/1adf138dc47463956f9bf036d5b59da44dd284fc/bindings/pydrake/trajectories_py.cc#L27)):*
> ```cpp
> std::vector<MatrixX<T>> MakeEigenFromRowMajorVectors(
>     const std::vector<std::vector<T>>& in) {
>   std::vector<MatrixX<T>> vec(in[0].size(), Eigen::VectorXd(in.size()));
> ```

nit Accessing `in[0]` is undefined when `in` is empty.  We need some kind of check here that preempts that situation.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433#-:-Mf4XuP11RCZmquHhnDF:b8qx53o)* status: 2 unresolved discussions (waiting on @RussTedrake)

___
*[bindings/pydrake/trajectories_py.cc, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf4WF3l-Qf70O6wr7Ud:-Mf4WF3m8eoq6iD7kdeS:b-dt4skp) ([raw file](https://github.com/robotlocomotion/drake/blob/1adf138dc47463956f9bf036d5b59da44dd284fc/bindings/pydrake/trajectories_py.cc#L135)):*
> ```cpp
>           // vector<vector<T>> then vector<MatrixX<T>> then MatrixX<T>.
>           [](const std::vector<T>& breaks,
>               const std::vector<std::vector<T>>& samples) {
> ```

nit: odd indent

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[bindings/pydrake/trajectories_py.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3t3kmE_zWh14qwSuu:-Mf4Ym5C8wsSa1d3lUwm:bxrh4a3) ([raw file](https://github.com/robotlocomotion/drake/blob/1adf138dc47463956f9bf036d5b59da44dd284fc/bindings/pydrake/trajectories_py.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Accessing `in[0]` is undefined when `in` is empty.  We need some kind of check here that preempts that situation.
</blockquote></details>

Returning an empty vector seems like the best answer here.  That would allow for the polynomial constructor to reject it with a superior error messages (mismatched breaks, or too few samples, etc).
___
*[bindings/pydrake/trajectories_py.cc, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf4WF3l-Qf70O6wr7Ud:-Mf4YMQu08WFstRH6kT1:btsae6p) ([raw file](https://github.com/robotlocomotion/drake/blob/1adf138dc47463956f9bf036d5b59da44dd284fc/bindings/pydrake/trajectories_py.cc#L135)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: odd indent
</blockquote></details>

Whitespace layout in pydrake C++ code comes from clang-format and is enforced by the linter.  We could insert inline comments to customize it, but I don't think that's warranted here.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[bindings/pydrake/trajectories_py.cc, line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf4WF3l-Qf70O6wr7Ud:-Mf4gjyi1fl0HExpVrbw:b-kp6z4d) ([raw file](https://github.com/robotlocomotion/drake/blob/1adf138dc47463956f9bf036d5b59da44dd284fc/bindings/pydrake/trajectories_py.cc#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Whitespace layout in pydrake C++ code comes from clang-format and is enforced by the linter.  We could insert inline comments to customize it, but I don't think that's warranted here.
</blockquote></details>

Retracted.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[bindings/pydrake/trajectories_py.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15433#-Mf3t3kmE_zWh14qwSuu:-Mf5VDVR3XWeavQ1UYFm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1adf138dc47463956f9bf036d5b59da44dd284fc/bindings/pydrake/trajectories_py.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Returning an empty vector seems like the best answer here.  That would allow for the polynomial constructor to reject it with a superior error messages (mismatched breaks, or too few samples, etc).
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15433)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @RussTedrake)

**Pull request merged**
