### PR TITLE
Adds Eigen versions of the Cubic polynomial generation methods.  

### PR DESCRIPTION
**Pull request by RussTedrake**
This is much easier to use from python, as the std::vector method would convert a 2d array into a std::vector<MatrixX<double>> with a single element and matrix coefficients, but I almost always wanted the vector coefficient version of the spline.  I've replaced the bindings to use the Eigen versions.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8380)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sammy-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-:-L7gUdFoLK0_LdVZX7TN:b-1h8soq)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/trajectories/piecewise_polynomial.cc, line 803 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8380#-L7j6Fgc5klJ7hRm815x:-L7j6Fgc5klJ7hRm815y:b-uvq9zb) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa03dd2ff1ea0876d968ee5f8e0670c2cc8f17f/common/trajectories/piecewise_polynomial.cc#L803)):*
> ```cpp
> // Copies each column of mat to an element of the returned std::vector.
> template <typename T>
> std::vector<MatrixX<T>> colsToStdVector(
> ```

BTW This function name doesn't agree with http://drake.mit.edu/styleguide/cppguide.html#Function_Names though in this file I think http://drake.mit.edu/styleguide/cppguide.html#Existing_Non-conformant_Code probably applies.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8380#-:-L7j7xFt9VmtH8RZrHSG:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@sherm1 for platform review, please.

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/trajectories/piecewise_polynomial.cc, line 803 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-L7j6Fgc5klJ7hRm815x:-L7kEbkIu-U3wJ2gPvNo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa03dd2ff1ea0876d968ee5f8e0670c2cc8f17f/common/trajectories/piecewise_polynomial.cc#L803)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW This function name doesn't agree with http://drake.mit.edu/styleguide/cppguide.html#Function_Names though in this file I think http://drake.mit.edu/styleguide/cppguide.html#Existing_Non-conformant_Code probably applies.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-:-L7kEcozTYKhA70-cFcw:bppyoqq)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380)*

**Comment by sherm1** [comment]
Reviewing (there are some CI problems that look real) ...

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-:-L7ksr1CB6rGAyUrwpVg:b-686mu0)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few BTWs, ptal.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[common/trajectories/piecewise_polynomial.cc, line 821 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-L7kzRumjizdMgRuAvIk:-L7kzRumjizdMgRuAvIl:bk05yti) ([raw file](https://github.com/robotlocomotion/drake/blob/6d9bb99a25b068ed3d4192aa1bd0cbfcfa4b7069/common/trajectories/piecewise_polynomial.cc#L821)):*
> ```cpp
>   std::vector<double> my_breaks(breaks.data(), breaks.data() + breaks.size());
>   return PiecewisePolynomial<T>::ZeroOrderHold(my_breaks,
>                                                colsToStdVector(knots));
> ```

BTW should be capital-C ColsToStdVector() ?

---

*[common/trajectories/test/piecewise_polynomial_generation_test.cc, line 506 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-L7kz2PJZ_yfaKAV7e5m:-L7kz2PJZ_yfaKAV7e5n:b-tpkvfw) ([raw file](https://github.com/robotlocomotion/drake/blob/6d9bb99a25b068ed3d4192aa1bd0cbfcfa4b7069/common/trajectories/test/piecewise_polynomial_generation_test.cc#L506)):*
> ```cpp
> }
> 
> GTEST_TEST(SplineTests, EigenTest) {
> ```

BTW a comment would be helpful here. Something like: "Test that the Eigen API methods return the same results as the already-tested std::vector versions."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-:-L7l-SMCSsvKuBdLdpsu:b-q9upmg)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[common/trajectories/piecewise_polynomial.cc, line 821 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-L7kzRumjizdMgRuAvIk:-L7l72dqz40-1PRHQ1Yo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d9bb99a25b068ed3d4192aa1bd0cbfcfa4b7069/common/trajectories/piecewise_polynomial.cc#L821)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should be capital-C ColsToStdVector() ?
</blockquote></details>

Done.

---

*[common/trajectories/test/piecewise_polynomial_generation_test.cc, line 506 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8380#-L7kz2PJZ_yfaKAV7e5m:-L7l73qhkjvb_IH7aRom:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d9bb99a25b068ed3d4192aa1bd0cbfcfa4b7069/common/trajectories/test/piecewise_polynomial_generation_test.cc#L506)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW a comment would be helpful here. Something like: "Test that the Eigen API methods return the same results as the already-tested std::vector versions."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8380)*

**Pull request merged**
