### PR TITLE
[doc] Update supported Xcode / python versions to match CI

### LINKED ISSUE #17000: update and/or document macOS Xcode versions
Related [slack discussion](https://drakedevelopers.slack.com/archives/C01CSPX85N3/p1650400866886749).

- Currently, we have:
    - Big Sur: Xcode 12.5.
    - Monterey (x86_64): Xcode 13.1, likely to be upgraded.
    - In development: Monterey (arm64): Xcode 13.4
- Docs need to update: https://drake.mit.edu/from_source.html

Ideally we would have all platforms running the same version of Xcode (13.3).  Timeline to finalize ~end of May 2022.

CC: @rpoyner-tri

### PR DESCRIPTION
**Pull request by svenevs**
Closes #17000.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805#-:-NAoAomT24nJoVMqO3II:bs3ynz8)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail and @svenevs)

___
*[`doc/_pages/from_source.md` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NAoAsad8AkVyazJ6ShX:-NAoAsad8AkVyazJ6ShY:bdoe0xg) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc9f68c245388d15317917527193621d84815b3/doc/_pages/from_source.md#L22)):*
> ```Markdown
> | macOS Big Sur (11)                 | x86_64 ⁽²⁾   | 3.10 ⁽³⁾ | 5.1   | 3.24  | Apple LLVM 12.0.5 (Xcode 12.5) | AdoptOpenJDK 16 (HotSpot JVM) |
> | macOS Monterey (12)                | x86_64 ⁽²⁾   | 3.10 ⁽³⁾ | 5.1   | 3.24  | Apple LLVM 13.0.0 (Xcode 13.1) | AdoptOpenJDK 16 (HotSpot JVM) |
> | macOS Monterey (12)                | arm64 ⁽²⁾    | 3.10 ⁽³⁾ | 5.1   | 3.24  | Apple LLVM 13.1.6 (Xcode 13.4) | AdoptOpenJDK 16 (HotSpot JVM) |
> ```

Working, CC @jwnimmer-tri. In the final row this superscript `(2)` is probably inappropriate.  Do we officially support m1 now?  This PR is just documenting the current versions used in CI.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NAoCOmk4bqRfb8IiOv4):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, there are missing updates on other docs pages (installation.html).
</blockquote></details>

OK, installation page updated.
___
*[`doc/_pages/from_source.md` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NAoAsad8AkVyazJ6ShX:-NAoGS4P8EXyW1Ul3g-5:b-n3itno) ([raw file](https://github.com/robotlocomotion/drake/blob/3fc9f68c245388d15317917527193621d84815b3/doc/_pages/from_source.md#L22)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, CC @jwnimmer-tri. In the final row this superscript `(2)` is probably inappropriate.  Do we officially support m1 now?  This PR is just documenting the current versions used in CI.
</blockquote></details>

OK, I don't think we officially support it until we start producing a nightly `.tar.gz`.  And I believe that is on hold until mosek 10.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

___
*[`doc/_pages/pip.md` line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NApG3iw59lbY5uEURG8:-NApG3iw59lbY5uEURG9:b2k8k3j) ([raw file](https://github.com/robotlocomotion/drake/blob/ad56eed5b762a029f875bf8cbe5233511a774bcb/doc/_pages/pip.md#L89)):*
> ```Markdown
> * [https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp38-cp38-manylinux_2_31_x86_64.whl](https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp38-cp38-manylinux_2_31_x86_64.whl)
> * [https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp39-cp39-manylinux_2_31_x86_64.whl](https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp39-cp39-manylinux_2_31_x86_64.whl)
> * [https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp310-cp310-macosx_11_0_x86_64.whl](https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp310-cp310-macosx_11_0_x86_64.whl)
> ```

FYI when we switched `brew` to python 3.10 these became `cp310`, we should make sure to update these links in lockstep next time.  Should we add a comment in the `Brewfile`?

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805#-:-NAyRLo11cxwVOAPCIFq:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@rpoyner-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805#-:-NBHmh9E-RbYUry4WslV:bl5eq21)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805#-:-NBIJ-c_EcA9PwMLeVFC:bnfp4nl)* status: 2 unresolved discussions, missing label for release notes (waiting on @svenevs)

___
*[`doc/_pages/pip.md` line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NApG3iw59lbY5uEURG8:-NBIITc16POxU4XQAv5Z:b-i2bt48) ([raw file](https://github.com/robotlocomotion/drake/blob/ad56eed5b762a029f875bf8cbe5233511a774bcb/doc/_pages/pip.md#L89)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI when we switched `brew` to python 3.10 these became `cp310`, we should make sure to update these links in lockstep next time.  Should we add a comment in the `Brewfile`?
</blockquote></details>

Yes, but I'd say a perhaps comment in `drake/tools/workspace/python/repository.bazel` near `_VERSION_SUPPORT_MATRIX` would probably be the most centralized place?
___
*[`doc/_pages/pip.md` line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NBIIrPWD8ElVN-M5CLq:-NBIIrPWD8ElVN-M5CLr:bt38x9x) ([raw file](https://github.com/robotlocomotion/drake/blob/ad56eed5b762a029f875bf8cbe5233511a774bcb/doc/_pages/pip.md#L92)):*
> ```Markdown
> 
> Older packages for specific dates are available by replacing ``latest`` with an
> 8-digit date, e.g., ``20220721`` for July 21st, 2022.  The version number to
> ```

nit For my taste at least, changing _all_ of the dates in this section to 20220831 would be the easiest to maintain, moving forward?

**Review by svenevs — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17805)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`doc/_pages/pip.md` line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NApG3iw59lbY5uEURG8:-NBIOqyv7NARVThzW8rE:b-svlj4t) ([raw file](https://github.com/robotlocomotion/drake/blob/ad56eed5b762a029f875bf8cbe5233511a774bcb/doc/_pages/pip.md#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, but I'd say a perhaps comment in `drake/tools/workspace/python/repository.bazel` near `_VERSION_SUPPORT_MATRIX` would probably be the most centralized place?
</blockquote></details>

OK yes that's the best location, comment added!
___
*[`doc/_pages/pip.md` line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17805#-NBIIrPWD8ElVN-M5CLq:-NBIOwnbAUi-50u-gxJA:bxlze1c) ([raw file](https://github.com/robotlocomotion/drake/blob/ad56eed5b762a029f875bf8cbe5233511a774bcb/doc/_pages/pip.md#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For my taste at least, changing _all_ of the dates in this section to 20220831 would be the easiest to maintain, moving forward?
</blockquote></details>

OK, yes I think that's a good policy -- just update them all together.

**Pull request merged**
