### PR TITLE
[examples] Use meshcat to visualize mass spring example

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #16216

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for both review please, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248#-:-MrA65evDpmTNyo5DPss:b-ndxe0c)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNOQjuAJyn0NpXqGAG:-MrNOQjuAJyn0NpXqGAH:bxnwi01) (no related file):*
The README still tells people to run `drake_visualizer`.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNPYgB4mdClXHhrt-Z:-MrNPYgB4mdClXHhrt-_:b-asfawc) (no related file):*
When I run this locally on Firefox, the visualization frame rate is like 100x slower than drake-visualizer, and makes Firefox janky and nearly unkillable.  What browser did you test with?

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNPYgB4mdClXHhrt-Z:-MrNkCTwAmq6sjsxc_of:b-vow3kc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When I run this locally on Firefox, the visualization frame rate is like 100x slower than drake-visualizer, and makes Firefox janky and nearly unkillable.  What browser did you test with?
</blockquote></details>

I tested with Chrome and it seemed fine. I was able to reproduce the jankiness with Firefox. I'll dig and see what I can find about that.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNOQjuAJyn0NpXqGAG:-MrNkWdp8S2ITJLEJLHI:b-a9q4c4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The README still tells people to run `drake_visualizer`.
</blockquote></details>

working

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNPYgB4mdClXHhrt-Z:-MrNuo6ABSMrILqh5Q6A:b-u81gxc) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I tested with Chrome and it seemed fine. I was able to reproduce the jankiness with Firefox. I'll dig and see what I can find about that.
</blockquote></details>

OK I don't think it needs to hold up _this_ PR, but we should probably try to open an issue to root cause this.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNOQjuAJyn0NpXqGAG:-MrO0oIT3aeNoIHRzwbD:bgq9rd5) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

working
</blockquote></details>

Done. PTAL, thanks.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16248#-MrNPYgB4mdClXHhrt-Z:-MrO0q4m6JWtgMbsrdG7:b-if63pr) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I don't think it needs to hold up _this_ PR, but we should probably try to open an issue to root cause this.
</blockquote></details>

I'll see what I can find out and post an issue.

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16248#-:-MrO1W9W-ZEorO2mA5S8:b-85g6de)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
