### PR TITLE
Add DRAKE_DEPRECATED macro

### PR DESCRIPTION
**Pull request by sherm1**
Add a portable macro for marking classes, functions, variables, etc. as deprecated.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2621)

### CODE REVIEW

**Comment by liangfok** [comment]
I'm going to assume for now that "status: do not review" implies "do not test" as well.

**Comment by sherm1** [comment]
Ready for review now. Feature: +@liangfok, platform: +@jwnimmer-tri please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-:-KKvSa-bO9XWmLtC0f-g:1864226006)*

**Comment by liangfok** [comment]
Awesome. Testing now.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-:-KKwdQynLk0bDlEm6Pw6:13897240)*

**Comment by liangfok** [comment]
I tested this and it works. However, can we add a SWIG scenario to the unit test? I was having issues with SWIG in https://github.com/robotlocomotion/drake/pull/2597.

FTR, using `ninja`, I had to scroll up really far to see the following (good) warnings:

```
[31/260] Building CXX object common/test/CMakeFiles/drake_deprecated_test.dir/drake_deprecated_test.cc.o
/Users/liang/dev/drake/drake/common/test/drake_deprecated_test.cc:26:3: warning: 'MyClass' is deprecated:
DRAKE DEPRECATED: use MyNewClass instead [-Wdeprecated-declarations]
  MyClass this_is_obsolete;
  ^
/Users/liang/dev/drake/drake/common/test/drake_deprecated_test.cc:14:50: note: 'MyClass' has been explicitly marked deprecated here
class DRAKE_DEPRECATED("use MyNewClass instead") MyClass {
                                                 ^
/Users/liang/dev/drake/drake/common/test/drake_deprecated_test.cc:33:18: warning: 'f' is deprecated:
DRAKE DEPRECATED: don't use this function; use g() instead [-Wdeprecated-declarations]
  int obsolete = f(1);
                 ^
/Users/liang/dev/drake/drake/common/test/drake_deprecated_test.cc:21:5: note: 'f' has been explicitly marked deprecated here
int f(int arg) { return arg; }
    ^
2 warnings generated.
```

I suspect using `make` will require scrolling up even more since it is by default more verbose. Since the warnings are so hard to find even manually, this may motivate learning how to modify the unit test to check for compile-time warnings.

---

Reviewed 2 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/common/drake_deprecated.h, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKweDghF9ysXiVd7HxM:-KKweDgi9tJdzG8Ts4u5:1509796633) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L9)):*
> ```objc
> #ifdef DRAKE_DOXYGEN_CXX
> /** Use `DRAKE_DEPRECATED("message")` to discourage use of particular
> classes, typedefs, variables, non-static data members, functions, arguments,
> ```

Wow. I did not realize the deprecated macro could be used for so many different things. The unit tests only include classes and functions. Should typedefs, variables, non-static data members, arguments, enumerations, and template specialization also be covered by the unit tests? 

---

*[drake/common/drake_deprecated.h, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwesO-emCxIhD7hhd8:-KKwesO-emCxIhD7hhd9:949267838) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L21)):*
> ```objc
>   // Attribute comes *before* declaration of a deprecated function or variable;
>   // no semicolon is allowed.
>   DRAKE_DEPRECATED("f() is slow; use g() instead")
> ```

Missing period at end of message.

---

*[drake/common/drake_deprecated.h, line 25 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwezPFUSTApKzQuhGX:-KKwezPFUSTApKzQuhGY:949267838) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L25)):*
> ```objc
> 
>   // Attribute comes *after* struct, class, enum keyword.
>   class DRAKE_DEPRECATED("use MyNewClass instead")
> ```

Missing period at end of message.

---

*[drake/common/drake_deprecated.h, line 41 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwfOrytM33E-DRL_bT:-KKwfOrzEtVMOJr6bfUp:95702124) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L41)):*
> ```objc
> #ifndef SWIG
>   /* Make sure warnings are enabled in VC++; it is a common Windows hack for
>   programmers to turn them off due to much inconvenient deprecation of useful
> ```

BTW, there seems to be a missing "too" in front of "much".

---

*[drake/common/test/drake_deprecated_test.cc, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwfymeUA-mFq2wAa0s:-KKwfymeUA-mFq2wAa0t:-192497365) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L10)):*
> ```cpp
> /* This test only verifies that the Drake build can still succeed if a 
> deprecated class or function is in use. I do not know how to test whether
> the desired warnings are actually issued except by inspection. */
> ```

BTW, I believe one way would be to have the unit test actually compile a small test program that calls a deprecated function and analyze the output of the compile process.

http://stackoverflow.com/questions/3803465/how-to-capture-stdout-stderr-with-googletest

@david-german-tri: Is this something we should try to do here for educational purposes? Is there a better way to use Google Test to evaluate compile-time output?

---

*[drake/common/test/drake_deprecated_test.cc, line 20 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwh4Dssv6GktsYZi-E:-KKwh4Dssv6GktsYZi-F:1284116310) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L20)):*
> ```cpp
> };
> 
> DRAKE_DEPRECATED("don't use this function; use g() instead")
> ```

Missing period at end of error message.

---

*[drake/common/test/drake_deprecated_test.cc, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwh5ncrR5zexvVzW3C:-KKwh5ncrR5zexvVzW3D:-1098644054) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L21)):*
> ```cpp
> 
> DRAKE_DEPRECATED("don't use this function; use g() instead")
> int f(int arg) { return arg; }
> ```

BTW, I recall there being some recommendation against using single character variables because they don't convey much in the way of semantics. Consider `non_deprecated_method()` and `deprecated_method()` or `new_method()` and `old_method()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-:-KKwhdvOB5kQS7-8mpc_:-2001028075)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/drake_deprecated.h, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx6HTcYAJm_0f4erh6:-KKx6HTcYAJm_0f4erh7:1455068650) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L51)):*
> ```objc
>     #define DRAKE_DEPRECATED(MSG) [[deprecated("\nDRAKE DEPRECATED: " MSG)]]
>   #elif _MSC_VER
>     /* VC++ just says warning C4996 so add "DEPRECATED" to the message. */
> ```

BTW all of the variants prefix "DRAKE DEPRECATED " in the now -- is this comment still what you want to say?

---

*[drake/common/test/drake_deprecated_test.cc, line 3 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx5NjMKJPu25FSbxp2:-KKx5NjNnCCpLpJLJ12o:-756975516) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L3)):*
> ```cpp
> #include "drake/common/drake_deprecated.h"
> 
> #include <string>
> ```

Unused?

---

*[drake/common/test/drake_deprecated_test.cc, line 4 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx5OSjvdNiRpMZA7v9:-KKx5OSkZ7S1L_SQe_yF:-756975516) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L4)):*
> ```cpp
> 
> #include <string>
> #include <vector>
> ```

Unused?

---

*[drake/common/test/drake_deprecated_test.cc, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwfymeUA-mFq2wAa0s:-KKx4eHJfdFmt8KSvbX3:2032500803) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I believe one way would be to have the unit test actually compile a small test program that calls a deprecated function and analyze the output of the compile process.
> 
> http://stackoverflow.com/questions/3803465/how-to-capture-stdout-stderr-with-googletest
> 
> @david-german-tri: Is this something we should try to do here for educational purposes? Is there a better way to use Google Test to evaluate compile-time output?
</details>
The `drake_assert_test_compile` is an example of how to unit test compiler failure via `CMakeLists.txt`.  If it seemed worth it, a similar tactic could be used for `DRAKE_DEPRECATED` -- when `-Werror=deprecated-declarations` is enabled, a program fails to compile; with that warning turned off, it passes.  Possible even `drake_deprecated_test.cc` could be the "doesn't compile anymore" target file.

---

*[drake/common/test/drake_deprecated_test.cc, line 32 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx5a7_b2iDwJ4bwpao:-KKx5a7_b2iDwJ4bwpap:-836858258) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L32)):*
> ```cpp
> }
> 
> GTEST_TEST(DrakeAssertDeathTest, FunctionTest) {
> ```

`DrakeAssertDeathTest` seems incorrect here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621)*

**Comment by sherm1** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/drake_deprecated.h, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKweDghF9ysXiVd7HxM:-KKy3GDpAi_NzNSvSYL7:1933038785) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Wow. I did not realize the deprecated macro could be used for so many different things. The unit tests only include classes and functions. Should typedefs, variables, non-static data members, arguments, enumerations, and template specialization also be covered by the unit tests? 
</details>
That would be a test of the compiler rather than the macro. I'm assuming the compilers implement the deprecated attribute correctly.

---

*[drake/common/drake_deprecated.h, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwesO-emCxIhD7hhd8:-KKy4JB86KusqqfF_GfH:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing period at end of message.
</details>
Done.

---

*[drake/common/drake_deprecated.h, line 25 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwezPFUSTApKzQuhGX:-KKy4Js-SHdBhA-U_6uL:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing period at end of message.
</details>
Done.

---

*[drake/common/drake_deprecated.h, line 41 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwfOrytM33E-DRL_bT:-KKy3uByo1gqx9S80dUe:-50182317) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L41)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, there seems to be a missing "too" in front of "much".
</details>
No, that's what I intended to say. No amount of "inconvenient deprecation" is good!

---

*[drake/common/drake_deprecated.h, line 51 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx6HTcYAJm_0f4erh6:-KKy4MMJKtgHsPyIkPJx:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/drake_deprecated.h#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW all of the variants prefix "DRAKE DEPRECATED " in the now -- is this comment still what you want to say?
</details>
Done.

---

*[drake/common/test/drake_deprecated_test.cc, line 3 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx5NjMKJPu25FSbxp2:-KKy4WGON_MsB7Uptvc9:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---

*[drake/common/test/drake_deprecated_test.cc, line 4 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx5OSjvdNiRpMZA7v9:-KKy4WcZMEcf0Ej7lz1t:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---

*[drake/common/test/drake_deprecated_test.cc, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwfymeUA-mFq2wAa0s:-KKy4au-XjHMoi8Y0g7J:-609057721) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `drake_assert_test_compile` is an example of how to unit test compiler failure via `CMakeLists.txt`.  If it seemed worth it, a similar tactic could be used for `DRAKE_DEPRECATED` -- when `-Werror=deprecated-declarations` is enabled, a program fails to compile; with that warning turned off, it passes.  Possible even `drake_deprecated_test.cc` could be the "doesn't compile anymore" target file.
</details>
That would be awesome but I'm going to declare this sufficiently tested and move on. I updated the comment in case someone wants to push it further, but stopped short of making it a TODO. I would welcome a PR with a more comprehensive test!

---

*[drake/common/test/drake_deprecated_test.cc, line 20 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwh4Dssv6GktsYZi-E:-KKy8Ee_2pI58wAjpNV_:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing period at end of error message.
</details>
Done.

---

*[drake/common/test/drake_deprecated_test.cc, line 21 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKwh5ncrR5zexvVzW3C:-KKy8G3FKlpEtdJMK3_o:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I recall there being some recommendation against using single character variables because they don't convey much in the way of semantics. Consider `non_deprecated_method()` and `deprecated_method()` or `new_method()` and `old_method()`.
</details>
Done.

---

*[drake/common/test/drake_deprecated_test.cc, line 32 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-KKx5a7_b2iDwJ4bwpao:-KKy8LC303PXnXMQgvxo:-1767785188) ([raw file](https://github.com/robotlocomotion/drake/blob/1ba3014b4b97b2e5fa6fa8db302aed8bbd3d6d04/drake/common/test/drake_deprecated_test.cc#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `DrakeAssertDeathTest` seems incorrect here.
</details>
Done. (I wonder where that came from :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621)*

**Comment by sherm1** [comment]
All reviewer comments addressed. PTAL.

---

Review status: 3 of 5 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-:-KKyAQzrYIOSsh7QRB5J:744087055)*

**Comment by liangfok** [comment]
:lgtm_strong: Especially since I have a workaround for the SWIG issue in #2597 .

---

Reviewed 1 of 2 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-:-KKyI-zd3D3ZSfaAVHAN:231449122)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2621#-:-KKyLLXAkQvmrKnpy6Dq:1417088721)*

**Pull request merged**
