### PR TITLE
Update externals to latest commits

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Per monthly hygiene.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9085)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review of the change to `multibody/**`, please.

**Comment by amcastro-tri** [comment]
Thanks for the additional cleanup. :lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9085#-:-LGQp9MtBQ6XexXiQPYE:b-891uox)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule (tomorrow), please.

---

Review status: all discussions resolved, platform LGTM missing, labeled "do not merge"

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9085#-:-LGRDGTZ2fAf-XfkRrJU:bb6f7xt)*

**Comment by sammy-tri** [comment]
:lgtm: with one btw.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all discussions resolved, platform LGTM from [sammy-tri], labeled "do not merge"

---

*[tools/workspace/sdformat/package.BUILD.bazel, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9085#-LGRTUdV-oPsD_ecnqM2:-LGRTUdV-oPsD_ecnqM3:becfi9c) ([raw file](https://github.com/robotlocomotion/drake/blob/d9c12cd101938c61efe3add8aad418ccc530d97e/tools/workspace/sdformat/package.BUILD.bazel#L87)):*
> ```
>     "include/sdf/Box.hh",
>     # TODO(jwnimmer-tri) Collision.hh isn't marked public in upstream sdformat,
>     # but it should be.
> ```

BTW I'm guessing this comment is to explain why it's in both `srcs` and `hdrs` for the `cc_library` rule?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9085#-:-LGRTeCGCUgGjUoAMPXI:b2d4pgu)*

**Comment by jwnimmer-tri** [comment]
Review status: all discussions resolved, platform LGTM from [sammy-tri], labeled "do not merge"

---

*[tools/workspace/sdformat/package.BUILD.bazel, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9085#-LGRTUdV-oPsD_ecnqM2:-LGRXgDt1Qf1cEup0VGp:bmwtcq4) ([raw file](https://github.com/robotlocomotion/drake/blob/d9c12cd101938c61efe3add8aad418ccc530d97e/tools/workspace/sdformat/package.BUILD.bazel#L87)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm guessing this comment is to explain why it's in both `srcs` and `hdrs` for the `cc_library` rule?
</blockquote></details>

That's correct.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9085)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, platform LGTM from [sammy-tri], labeled "do not merge"

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9085)*

**Pull request merged**
