### PR TITLE
Do not use Makefile wrapper when building signalscope

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4617)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-:-K_4zZfUKDQonJlM-5BL:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-:-K_4zrjajuqve_P6kxOf:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending open discussions, CI, etc.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-K_526frBKe0wG5FoAR7:-K_526frBKe0wG5FoAR8:b-z5yw14) (no related file):*
Can someone confirm for me that you've manually run `signal-scope` locally after a clean build, and it worked?

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-K_52JKuGYLW8DIp18Ev:-K_52JKuGYLW8DIp18Ew:bz1lvil) (no related file):*
The file `drake/examples/kuka_iiwa_arm/kuka_sim.pmd` references a binary path to signal-scope.  Does that demo still work (is that path still correct)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-:-K_525JNidQX__odXXww:b-i6mtcb)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-K_526frBKe0wG5FoAR7:-K_52mXEt_fNMHVcTo0t:b-7xt2ki) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can someone confirm for me that you've manually run `signal-scope` locally after a clean build, and it worked?
</blockquote></details>

Yes.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-K_52JKuGYLW8DIp18Ev:-K_538OpTUtB7Ms4MNw_:b-gcgnw2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The file `drake/examples/kuka_iiwa_arm/kuka_sim.pmd` references a binary path to signal-scope.  Does that demo still work (is that path still correct)?
</blockquote></details>

Yes, nothing has changed there. The Makefile really was just a wrapper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4617)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-K_52JKuGYLW8DIp18Ev:-K_53uQcMgaFvAQrUJCq:b-lpicjp) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, nothing has changed there. The Makefile really was just a wrapper.
</blockquote></details>

Yeah.  I thought in the past the de-pod changed the installed binary location, but maybe that was a one-time thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4617)*

**Comment by jamiesnape** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4617#-K_52JKuGYLW8DIp18Ev:-K_57cKA-rh48r65aKbQ:b-p8879p) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah.  I thought in the past the de-pod changed the installed binary location, but maybe that was a one-time thing.
</blockquote></details>

This was not a full de-pod. Here, the build location changes, but the install stays the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4617)*

**Pull request merged**
