### PR TITLE
[doc] Improve monogram notation examples for vectors

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-:-Nr8NeHS8S8HvcJuRm7m:b-2m4w50)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
For awareness +@xuchenhan-tri  and +@rcory 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-:-Nr8Nvwg3B9yFZ-Fd-Nb:b-ddk1ej)* status: LGTM missing from assignees sherm1(platform),xuchenhan-tri(platform),rcory

**Review by xuchenhan-tri — COMMENTED** [review]
FYI if you just want to grab someone's attention `@username` suffices. `+@username` assigns `username` as a reviewer and requires their "LGTM" for your PR to merge.

I assume the intention is for Rick and I to take a look instead of requesting our LGTMs. So I'll -@rcory . But I can stay as the platform reviewer.

Platform :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-:-Nr8SbQp5hhU_GY9jdIt:bv18zxf)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`multibody/multibody_doxygen.h` line 321 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-Nr8SHsS2wH1-jjNc_qB:-Nr8SHsS2wH1-jjNc_qC:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/19bdf8404012f3ac391016f887ed7a04a23ea8b2/multibody/multibody_doxygen.h#L321)):*
> ```objc
> Quantity                     |Symbol|     Typeset              | Monogram   | Meaningᵃ
> -----------------------------|:----:|:------------------------:|:----------:|----------------------------
> Generic vector v             |  v   |@f$[v]_E@f$               |`v_E`       |Vector v expresed in frame E.
> ```

typo



_Suggestion:_
```objc
expressed
```
___
*[`multibody/multibody_doxygen.h` line 349 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-Nr8RaPS50FTFso2DqsR:-Nr8RaPS50FTFso2DqsS:b-1zep0h) ([raw file](https://github.com/RobotLocomotion/drake/blob/19bdf8404012f3ac391016f887ed7a04a23ea8b2/multibody/multibody_doxygen.h#L349)):*
> ```objc
> Jacobian wrt v               | Jv   |@f$J_{v}^{{}^Bv^Q}@f$     |`Jv_v_BQ`   |%Point Q's translational velocity Jacobian in frame B wrt v
> Jacobian wrt v               | Jv   |@f$J_{v}^{{}^B\omega^C}@f$|`Jv_w_BC`   |%Frame C's angular velocity Jacobian in frame B wrt v
> Ez measure of vector v       |  v   |@f$[v]_{Ez}@f$            |`v_Ez`      |Ez scalar component of vector v, i.e., 𝐯 • 𝐄𝐳, where Ez is a unit vector of frame E.
> ```

BTW can we be more specific here? Ez is not just any unit vector of frame E, it's the unit vector along the z-direction in the E frame, right?



_Code quote:_
```objc
where Ez is a unit vector of frame E.
```

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending a few minor comments

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-:-NrBizeA24I5CjJX7GVD:b-esx498)* status: 3 unresolved discussions

___
*[`multibody/multibody_doxygen.h` line 349 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-NrBirPB6N5sOQfPs9CA:-NrBirPB6N5sOQfPs9CB:bt5cb7z) ([raw file](https://github.com/RobotLocomotion/drake/blob/19bdf8404012f3ac391016f887ed7a04a23ea8b2/multibody/multibody_doxygen.h#L349)):*
> ```objc
> Jacobian wrt v               | Jv   |@f$J_{v}^{{}^Bv^Q}@f$     |`Jv_v_BQ`   |%Point Q's translational velocity Jacobian in frame B wrt v
> Jacobian wrt v               | Jv   |@f$J_{v}^{{}^B\omega^C}@f$|`Jv_w_BC`   |%Frame C's angular velocity Jacobian in frame B wrt v
> Ez measure of vector v       |  v   |@f$[v]_{Ez}@f$            |`v_Ez`      |Ez scalar component of vector v, i.e., 𝐯 • 𝐄𝐳, where Ez is a unit vector of frame E.
> ```

minor: shouldn't introduce bold font here -- we don't use it anywhere else

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005)* status: 4 unresolved discussions

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-NrBk4Qg1EWhoMN_--YE):*
BTW



_Suggestion:_
```
[doc] Improve monogram notation examples for vectors
```

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-NrBk4Qg1EWhoMN_--YE):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW
</blockquote></details>

Yes -- I will use this as commit message.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21005#-:-NrC5tg41ndXJMj1PaoH:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

**Pull request merged**
