### PR TITLE
Fixed some more signed/unsigned compare warnings.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2399)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri can you do both the platform and feature review?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Fixed some more signed/unsigned compare warnings\.
</details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-:-KI80HY0gTP6w3bY7hwv:1721458756)*

**Comment by liangfok** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1731 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-KI80T0ddNVlSr3WZQ5S:-KI80T0ddNVlSr3WZQ5T:-1951190857) ([raw file](https://github.com/robotlocomotion/drake/blob/bbf8a8034303ead0a1e9ac0bcfd9af9bd17a38ea/drake/systems/plants/RigidBodyTree.cpp#L1731)):*
> ```cpp
>   size_t num_match = 0;
>   size_t ind_match = 0;
>   bool match_found = false;
> ```

Note this change. I think it's logically correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399)*

**Comment by jwnimmer-tri** [comment]
Yes.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri can you do both the platform and feature review?
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1647 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-KI89ibb2cNcnNEKIQF9:-KI89ibcBKPMkWJsC7Z1:-1463131997) ([raw file](https://github.com/robotlocomotion/drake/blob/bbf8a8034303ead0a1e9ac0bcfd9af9bd17a38ea/drake/systems/plants/RigidBodyTree.cpp#L1647)):*
> ```cpp
>           lower_model_name.compare(model_name) == 0) {  // it's the right robot
>         if (match < 0) {                                // it's the first match
>           match = i;
> ```

BTW This way of doing 'match' is just fine, too.  (A single integer representing the outcome, which is negative when unmatched and nonnegative when matched.)

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1731 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-KI80T0ddNVlSr3WZQ5S:-KI8ADAvDAdf06zsiHIX:-1529639232) ([raw file](https://github.com/robotlocomotion/drake/blob/bbf8a8034303ead0a1e9ac0bcfd9af9bd17a38ea/drake/systems/plants/RigidBodyTree.cpp#L1731)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Note this change. I think it's logically correct.
</details>
I see no reason why an extra boolean is needed here.  It seems identical to num_match, such that only one or the other should exist.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-:-KI8BCbvXCUIs9ZI8tjN:677251276)*

**Comment by liangfok** [comment]
Thanks. PTAL. Thanks!

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Yes.
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1731 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-KI80T0ddNVlSr3WZQ5S:-KI8Z5FQPczYP_KRT4oF:-2132873309) ([raw file](https://github.com/robotlocomotion/drake/blob/bbf8a8034303ead0a1e9ac0bcfd9af9bd17a38ea/drake/systems/plants/RigidBodyTree.cpp#L1731)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I see no reason why an extra boolean is needed here.  It seems identical to num_match, such that only one or the other should exist.
</details>
Once I switched `num_match` to be a `size_t`, it cannot be negative. So I added a boolean variable to capture the situation where not match was found.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-:-KI8ZEPZAExFRQnZK64B:-1142876745)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1731 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-KI80T0ddNVlSr3WZQ5S:-KI8b4yOyoMati2Wme9w:2079820001) ([raw file](https://github.com/robotlocomotion/drake/blob/bbf8a8034303ead0a1e9ac0bcfd9af9bd17a38ea/drake/systems/plants/RigidBodyTree.cpp#L1731)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Once I switched `num_match` to be a `size_t`, it cannot be negative. So I added a boolean variable to capture the situation where not match was found.
</details>
But now `num_match` is written to but never read from?  (Which is the defect I'm proposing.)

BTW I also see no reason that num_match or ind_match _should_ to be changed to `size_t`, though of course it's acceptable to do so (discretionary).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399)*

**Comment by liangfok** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1731 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-KI80T0ddNVlSr3WZQ5S:-KI8c0g_ahebuq74LBoC:-1338793033) ([raw file](https://github.com/robotlocomotion/drake/blob/bbf8a8034303ead0a1e9ac0bcfd9af9bd17a38ea/drake/systems/plants/RigidBodyTree.cpp#L1731)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> But now `num_match` is written to but never read from?  (Which is the defect I'm proposing.)
> 
> BTW I also see no reason that num_match or ind_match _should_ to be changed to `size_t`, though of course it's acceptable to do so (discretionary).
</details>
You're right. I deleted `num_match`. Good catch.

I decided to keep `match_found` because I think it requires less brain power to understand its use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks. PTAL. Thanks!
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2399#-:-KI8dByJ-Q28Vn6E6HCs:1417088721)*

**Comment by jwnimmer-tri** [comment]
Ready to merge iff jenkins passes.

**Comment by liangfok** [comment]
The Win32 failure in [CI build 1570](https://drake-jenkins.csail.mit.edu/job/experimental/1570/) looks like a network / cloud computing flake.

Does this failure warrant re-running the CI test suite?

**Comment by jamiesnape** [comment]
Check this build: https://drake-jenkins.csail.mit.edu/job/experimental/1574/

**Comment by jwnimmer-tri** [comment]
Seems like less than 30 minutes until 1574 will complete, so worth waiting -- on the off chance that 32/64 size_t is some kind of problem.  (This PR has never passed on msvc-32 yet due to jenkins flakes.)

**Comment by liangfok** [comment]
Just curious: Why does build 1574 not appear in the "Some checks were not successful" box below? How was it started?

**Comment by jwnimmer-tri** [comment]
Build 1574 passed up through and including the CTest stage, but then failed on some post-build steps.  That'll count as a success for me for msvc-32, and 1570 passed on all other pre-submit configurations.  I am going to count that all as a jenkins success.

Using override-merge due to out-of-date-with-master and jenkins-false-positive.

**Pull request merged**
