### PR TITLE
Build with -O1 for valgrind memcheck configuration

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6088)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
(memcheck jobs are all expected to fail as we still have defects)

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6088#-:-Kjy9ax50Kwu4WRNAjKC:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
Platform :lgtm:, one BTW, provided it is OK that the memcheck jobs fail.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/bazel.rc, line 183 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6088#-Kjyvv4JQRbT4WtlelBz:-Kjyvv4JQRbT4WtlelC-:b-k52bro) ([raw file](https://github.com/robotlocomotion/drake/blob/c316bef0cf8333a71c0f7bc29859a2d6087591e4/tools/bazel.rc#L183)):*
> ```
> # Slowdown factor can range from 5-100.
> # See http://valgrind.org/info/about.html
> test:memcheck --test_timeout=600,3000,10800,36000  # 10x
> ```

BTW not clear to me what "10x" means here? Looks doubled from the previous setting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6088#-:-Kjyw6zcFdmM-Z3dPgy8:b-ykqp20)*

**Pull request merged**
