### PR TITLE
Add a derivative() function to PiecewisePolynomial, Trajectory, and PP Trajectory

### PR DESCRIPTION
**Pull request by Lucy-tri**
This is part 1; part 2 is to output trajectory derivatives in TrajectorySource.
See https://github.com/RobotLocomotion/drake/issues/5172.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5215)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@siyuanfeng-tri for feature review.  Does this API look useful for what you want to do?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdD5P8hIgs1ZnfA90qF:b-3c7mh)*

**Comment by siyuanfeng-tri** [comment]
Hmm, this is one way of doing it. Although I think you are paying extra computational costs for taking the actual derivative part repetitively (not sure how high the cost is). I was thinking more along the directions of Trajectory derivative(int order) const; to avoid this. 

For PP, there is already a derivative function that does this. For my other use cases, I do 
PiecewisePolynomial original; 
PiecewisePolynomial original_dot = original.derivative(); 
PiecewisePolynomial original_ddot = original_dot.derivative();
... 
and return original_dot.value(t), original_ddot.value(t) ... for derivatives. 

I think you are paying O(N) cost as opposed to O(1), where N is the number of derivative evaluations. 

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/trajectories/piecewise_polynomial.h, line 245 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdDGCuT8zWpw3-76dNQ:-KdDGCuU7O0piNrjTWvG:b-xactke) ([raw file](https://github.com/robotlocomotion/drake/blob/11984a7a538e7220ff1c4108204cca06d7a01c5f/drake/common/trajectories/piecewise_polynomial.h#L245)):*
> ```objc
>   * @return The matrix of evaluated values.
>   */
>   drake::MatrixX<double> derivative(double t, int derivative_order = 1) const;
> ```

I am not sure about this. There is an existing method PiecewisePolynomial derivative(int derivative_order = 1) const, which returns the derivative of the entire PP. It also has default arguments. So if I just look at derivative(1), I can't distinguish them unless I also look at the return type. This can be very confusing. 
might change this to EvalDerivativeAtTime or something like at. 

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdDFUHi72k0KSdCl9Sn:-KdDFUHjFdBEWYX-fA-d:b-qkq131) ([raw file](https://github.com/robotlocomotion/drake/blob/11984a7a538e7220ff1c4108204cca06d7a01c5f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L54)):*
> ```cpp
>   EXPECT_EQ(kPpTrajFromVec.value(8.9)(0), y2.EvaluateUnivariate(8.9 - 7));
> 
>   // Test derivative()
> ```

these check for PP == PPTrajectory.
can you add another test that checks the derivatives are actually correct?
like kPpFromVec.derivative(1).value(1) equals some number? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdDD1JfboEyg4aeLUF-:b-bzaz11)*

**Comment by Lucy-tri** [comment]
Ah, ok, that is helpful.  I thought there was a desire to have derivative(t, order) return the value, but I see now how you plan to do it.  I will make some changes.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdDLH_kV5T9bCdVQczF:b5w4ftk)*

**Comment by siyuanfeng-tri** [comment]
I think this api is fine. I just want the ability to do derivatives for the
entire trajectory as a whole. Also clearly distinguish between those two
derivatives functions.

**Comment by Lucy-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/trajectories/piecewise_polynomial.h, line 245 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdDGCuT8zWpw3-76dNQ:-KdXSoXHthEYs4ITL1GD:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/1f008d04ebfd9f5dc3b703ac5a175b158f0bd8ba/drake/common/trajectories/piecewise_polynomial.h#L245)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I am not sure about this. There is an existing method PiecewisePolynomial derivative(int derivative_order = 1) const, which returns the derivative of the entire PP. It also has default arguments. So if I just look at derivative(1), I can't distinguish them unless I also look at the return type. This can be very confusing. 
might change this to EvalDerivativeAtTime or something like at. 

</blockquote></details>

Done. Removed.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdDFUHi72k0KSdCl9Sn:-KdXT8Jp2n57gz7HhXeW:b-z5a3r1) ([raw file](https://github.com/robotlocomotion/drake/blob/1f008d04ebfd9f5dc3b703ac5a175b158f0bd8ba/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L54)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

these check for PP == PPTrajectory.
can you add another test that checks the derivatives are actually correct?
like kPpFromVec.derivative(1).value(1) equals some number? 
</blockquote></details>

Done. See below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215)*

**Comment by Lucy-tri** [comment]
@siyuanfeng-tri  I've made some improvements and its ready for you again, thanks.
+@david-german-tri for platform review, please.
I am leaving for vacation in perhaps an hour :)  I might check into reviewable, but I won't be coding on vacation.
@sammy-tri  could you please take over  to get this PR in? Many thanks in advance. 

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdXVTx3rl9oB5auXuZh:ba4dmdj)*

**Comment by Lucy-tri** [comment]
+@sammy-tri 

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdXWTrhLdkbD2hfmBLT:bt5szf5)*

**Comment by david-german-tri** [comment]
+@soonho-tri platform review (shadow)

+(status: curate commits before merging) 

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdXYY0zKEHi_TFZgkC4:b-nlfmxm)*

**Comment by soonho-tri** [comment]
:lgtm: (aside two comments)

---

Reviewed 1 of 3 files at r2, 3 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdX_Kmdl8RijdKCvl8-:-KdX_Kmdl8RijdKCvl80:b-qwf928) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L6)):*
> ```cpp
> 
> #include "drake/common/eigen_matrix_compare.h"
> #include "drake/common/trajectories/piecewise_polynomial_trajectory.h"
> ```

I think it's better keep this `#include` atop this file?

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 90 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdXg3UByGhUDEl5OW6k:-KdXg3UByGhUDEl5OW6l:b-vlso8a) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L90)):*
> ```cpp
>   EXPECT_EQ(kPpTrajFromPpMatrix.derivative()->value(2.5)(2), 2);  // f' = 2 * 1.
>   EXPECT_EQ(kPpTrajFromPpMatrix.derivative()->value(2.5)(3), 5);  // f' = 2 * y.
> }
> ```

I think it's helpful to have a test covering a higher-order case (`n >= 2`). Something like:

```c++
  // Test derivative()
  EXPECT_TRUE(CompareMatrices(kPpFromMatrix.derivative(2).value(1),
                              kPpTrajFromPpMatrix.derivative(2)->value(1),
                              1e-10, MatrixCompareType::absolute));
  EXPECT_EQ(kPpTrajFromPpMatrix.derivative(2)->value(2.5)(1), 0);  // f'' = 0
  EXPECT_EQ(kPpTrajFromPpMatrix.derivative(2)->value(2.5)(2), 0);  // f'' = 0
  EXPECT_EQ(kPpTrajFromPpMatrix.derivative(2)->value(2.5)(3), 2);  // f'' = 2
```

It'd be better if the functions are more complicated so that `f''` are non-constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdXgODcGGc4hRJ9WHAJ:bo45u4g)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: minus higher order derivative test. thanks lucy!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 90 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdXg3UByGhUDEl5OW6k:-KdXhiPmgt5GsQw8Ij5Q:b-4j366p) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L90)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it's helpful to have a test covering a higher-order case (`n >= 2`). Something like:

```c++
  // Test derivative()
  EXPECT_TRUE(CompareMatrices(kPpFromMatrix.derivative(2).value(1),
                              kPpTrajFromPpMatrix.derivative(2)->value(1),
                              1e-10, MatrixCompareType::absolute));
  EXPECT_EQ(kPpTrajFromPpMatrix.derivative(2)->value(2.5)(1), 0);  // f'' = 0
  EXPECT_EQ(kPpTrajFromPpMatrix.derivative(2)->value(2.5)(2), 0);  // f'' = 0
  EXPECT_EQ(kPpTrajFromPpMatrix.derivative(2)->value(2.5)(3), 2);  // f'' = 2
```

It'd be better if the functions are more complicated so that `f''` are non-constant.

</blockquote></details>

agreed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdXhmANCVliQra74BtC:b-akwrg)*

**Comment by david-german-tri** [comment]
:lgtm: aside from comments

---

Reviewed 1 of 3 files at r2, 3 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdYAJh-BqH0Cq_-MnYk:-KdYAJh-BqH0Cq_-MnYl:b-ord5fm) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/piecewise_polynomial_trajectory.h#L29)):*
> ```objc
>    * Evaluate this PiecewisePolynomial at a particular time.
>    * @param t The time to evaluate.
>    * @return a CoefficientMatrix that is the value of the wrapped
> ```

This no longer seems accurate.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdX_Kmdl8RijdKCvl8-:-KdYAh71rQExGRNdcqEI:bw19cf9) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L6)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it's better keep this `#include` atop this file?
</blockquote></details>

Yes, the specific rule is https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 87 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdYBOyM1Ac3YRI_epsl:-KdYBOyM1Ac3YRI_epsm:b5ujv8n) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L87)):*
> ```cpp
>                               kPpTrajFromPpMatrix.derivative(1)->value(1),
>                               1e-10, MatrixCompareType::absolute));
>   EXPECT_EQ(kPpTrajFromPpMatrix.derivative()->value(2.5)(1), 1);  // f' = 1 * 1.
> ```

What about index 0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-KdYBgVd5owcd5EjJPpC:b-t5kwlp)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdYAJh-BqH0Cq_-MnYk:-KdbCMJSoMe_5NwYg45_:b-f1uef7) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/piecewise_polynomial_trajectory.h#L29)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This no longer seems accurate.
</blockquote></details>

I changed it to use a shorter (better) name for the same thing. So yeah, maybe the comment should be changed to "a Matrix" instead.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdX_Kmdl8RijdKCvl8-:-KdbCjO7Ya8UOXJiasMD:b6frfdi) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L6)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Yes, the specific rule is https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

Yup, I goofed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215)*

**Comment by Lucy-tri** [comment]
FYI:  I'm back from vacation and will be finishing this up (Sam didn't have time to work on it while I was away). Thanks everyone. 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-Ke4Nm4gOy7DxyLSOhW0:b-u4rrjk)*

**Comment by Lucy-tri** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdYAJh-BqH0Cq_-MnYk:-Ke5FBO_-6jLhHo9mdz5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/piecewise_polynomial_trajectory.h#L29)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

I changed it to use a shorter (better) name for the same thing. So yeah, maybe the comment should be changed to "a Matrix" instead.
</blockquote></details>

Done.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdX_Kmdl8RijdKCvl8-:-Ke5FD7mkiPu41b3hDAp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L6)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

Yup, I goofed.
</blockquote></details>

Done.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 87 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdYBOyM1Ac3YRI_epsl:-Ke5EzHMGo-tTTZbVQ09:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L87)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

What about index 0?
</blockquote></details>

Done.

---

*[drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc, line 90 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-KdXg3UByGhUDEl5OW6k:-Ke5F7lufL47dq_Baaon:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7921cdc0dbe31d9b57eff196c7770de747f67d7f/drake/common/trajectories/test/piecewise_polynomial_trajectory_test.cc#L90)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

agreed. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215)*

**Comment by Lucy-tri** [comment]
-@sammy-tri 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-Ke5ITsty06SzYXWoJpK:bxfid5b)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215)*

**Comment by Lucy-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-Ke5rT3hh42gsdVXFc4t:bzdwe9o)*

**Comment by Lucy-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-Ke66vOjwqJwQOfFQkRr:bvi7gpa)*

**Comment by Lucy-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-Ke6H26Xx0I3OUfzXF3e:bzdwe9o)*

**Comment by Lucy-tri** [comment]
-(status: curate commits before merging)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5215#-:-Ke6Tqx3t0q1PWn8rUA-:b-l70x01)*

**Pull request merged**
