### PR TITLE
Example of using the Lcm translator.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
1. example for Vector <=> HumanoidStatus.
2. example for robot_state_t msg <=> HumanoidStatus. 
3. robotlocomotion::pose_t msg <=> Isometry3d

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6390)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri you have seen most of this. thanks! +@sammy-tri for platform review. cc @kunimatsu-tri 

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-:-Kn5GOtXfIDL_lJuYLOM:bqvh6q6)*

**Comment by siyuanfeng-tri** [comment]
-@sammy-tri  +@ggould-tri for platform review. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-:-Kn5JkF2J8cGArokPtUn:b-7jfuxq)*

**Comment by ggould-tri** [comment]
+(status: curate commits before merging) (including commit messages -- I think you lost one in a rebase)

This is a long PR and is taking me a while; I'll checkpoint as I go.

---

Reviewed 7 of 21 files at r1.
Review status: 7 of 21 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-Kn9zQ-pmzamD1LovMKH:-Kn9zQ-pmzamD1LovMKI:bbkqk11) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc#L24)):*
> ```cpp
>   auto block = data->get_mutable_value();
>   block.head(robot.get_num_positions()) = msg.position();
>   block.head(robot.get_num_velocities()) = msg.velocity();
> ```

`head` here looks wrong to me.  Do you mean `tail`?

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-Kn9wjUtV7TNGogU5qlq:-Kn9wjUtV7TNGogU5qlr:btuj00z) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L50)):*
> ```objc
> 
>   /**
>    * @p time is used to update the timing in @p msg, and @p data is used to
> ```

No such parameter as `time`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-Kn9x-TmR2-XTEHzkQJ-:-Kn9x-TmR2-XTEHzkQJ0:btuj00z) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L59)):*
> ```objc
> 
>   /**
>    * @p time will be set to the time in @p msg. The state (q, v) are copied
> ```

No such parameter as `time`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-Kn9xkI3gEseWAmOLgri:-Kn9xkI3gEseWAmOLgrj:btuj00z) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L120)):*
> ```objc
> 
>   /**
>    * @p time and @p data cannot be nullptr.
> ```

No such parameter as `time`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-:-Kn9rPDPzYD4fUNaQb-N:bx9j6dk)*

**Comment by ggould-tri** [comment]
Reviewed 14 of 21 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_controller.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-KnA58NJuPzi_vEP34Og:-KnA58NJuPzi_vEP34Oh:byybe4b) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_controller.h#L76)):*
> ```objc
>     // lcm -> rs
>     builder.Connect(robot_state_subscriber_->get_output_port(0),
>                     msg_to_humanoid_status->get_input_port(0));
> ```

BTW -- is there a good reason for this change?  Replacing a readable name with a number seems like a clear loss of readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6390)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion comments. Thanks!

---

Reviewed 9 of 21 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-KnZqc4Qs5OlkLcPipho:-KnZqc4RwDjpj_ImKyGg:b-bb4bk1) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc#L13)):*
> ```cpp
>                robot.get_num_positions() + robot.get_num_velocities());
>   auto block = data.get_value();
>   msg->UpdateKinematics(0, block.head(robot.get_num_positions()),
> ```

Since `time` is directly related to what is stored, would it be possible to read this from the message?

(Please let me know if you want to whiteboard how we should start considering time-stamping.)

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-KnZnCWiok-fRgN1w8dv:-KnZnCWkACxHU6rzcwNz:b-ju5c3r) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc#L33)):*
> ```cpp
>   robot_state_translator_.EncodeMessageTorque(data.joint_torque(), msg);
> 
>   // TODO(siyuan): move this to translator.
> ```

BTW Would it be possible to add the text "move to foot wrench translator for composition" to the comment to clarify?

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-KnZneLLG23cqTvJRGEE:-KnZneLMYaFn_sTYfAuy:bszlv84) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L140)):*
> ```objc
> 
>   // Only used as temporary buffers for decoding.
>   mutable VectorX<double> tmp_position_;
> ```

This caching seems like it may be premature optimization - could you wrap these values in something like `Cache` / `Temporary`, which resizes according to a `RigidBodyTreed`, and instantiate this in each `Encode` / `Decode` call?

If we need performance, we should consider making `Encode` / `Decode` non-`const`, or leveraging the system framework caching when it comes in, and then use the `Cache` / `Temporary` class.

---

*[drake/lcm/robotlocomotion_translators/test/pose_t_translator_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-KnZplFKze2oav592Fp3:-KnZplFKze2oav592Fp4:b-k0eney) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/lcm/robotlocomotion_translators/test/pose_t_translator_test.cc#L38)):*
> ```cpp
> 
>   robotlocomotion::pose_t msg;
>   msg.position.x = 3;
> ```

nit Would it be possible to use different numbers between translation (say 5 6 7) and rotation (1 2 3 4), just for sanity?

---

*[drake/lcm/robotlocomotion_translators/test/pose_t_translator_test.cc, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-KnZp0M6Jo8JTDG0cExL:-KnZp0M6Jo8JTDG0cExM:b-amfavs) ([raw file](https://github.com/robotlocomotion/drake/blob/b9d70548a9677522eb69bce69667cf2035292c61/drake/lcm/robotlocomotion_translators/test/pose_t_translator_test.cc#L57)):*
> ```cpp
>   Quaternion<double> quat(data.linear());
> 
>   EXPECT_NEAR(std::abs(quat.dot(expected_quat)), 1., 1e-15);
> ```

Should `quat` be normalized / should there be a mention that `quat` is normalized by the translator to ensure that the dot product implies same magnitude and same direction (positive or negated)?
Also, should we add quaternion comparison in some sort of general comparison utility? (perhaps as a TODO?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-:-KnZqLUK42zllB1CNB3K:by5yjxk)*

**Comment by ggould-tri** [comment]
Looks like I forgot to update this; sorry.
￼:lgtm:, pending discussion comments. Thanks!

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6390#-:-Knie0gq3GSbeLpFPI-5:bajaxmx)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Pull request closed without merging**
