### PR TITLE
Support passing a MathematicalProgram to the DirectCollocation constructor

### PR DESCRIPTION
**Pull request by RussTedrake**
This enables adding multiple direct collocation programs into the same MathematicalProgram, which is important for enabling e.g. hybrid trajectory optimization. This has been a TODO, and was a major reason that we switched MultipleShooting to has-a prog (from is-a prog).

+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19156)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19156#-:-NSS621H08llZfWFWsmW:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`planning/trajectory_optimization/test/multiple_shooting_test.cc` line 197 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19156#-NSS5xDz57dLcTHYIDXM:-NSS5xDz57dLcTHYIDXN:b9mdqjn) ([raw file](https://github.com/RobotLocomotion/drake/blob/4eb91d061a3a459bf12389ad0c85b799cfcc2717/planning/trajectory_optimization/test/multiple_shooting_test.cc#L197)):*
> ```cpp
>                            kMaxTimeStep, &trajopt.prog());
>   EXPECT_EQ(trajopt.prog().num_vars(),
>             2 * (input.size() + state.size()) * kNumSampleTimes + 2);
> ```

BTW, document this `2` is time variable?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19156)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`planning/trajectory_optimization/test/multiple_shooting_test.cc` line 197 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19156#-NSS5xDz57dLcTHYIDXM:-NSV4jQuCdJHcA0ZulVh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4eb91d061a3a459bf12389ad0c85b799cfcc2717/planning/trajectory_optimization/test/multiple_shooting_test.cc#L197)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, document this `2` is time variable?
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19156#-:-NSWkbk82f3UxGYm0Hj2:b8qx53o)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19156#-:-NSWkk63CGXnKIPD7Ibv:buasbda)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
