### PR TITLE
simple spike test example on symbolic dynamics

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5995)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for both reviews please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-:-Kj4hRFjg3u9z8HAo2Me:b-2gceyk)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4qVERNJbJKRcmX8lY:-Kj4qVERNJbJKRcmX8lZ:b-b6o772) (no related file):*
Our convention is to also write CMakeLists support for new code when its easy, as it appears to be for this PR.

---

*[drake/examples/Pendulum/BUILD, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4qI1F-kzmh3M1dzQA:-Kj4qI1GViWoXtBKb54V:bxtso3p) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/BUILD#L122)):*
> ```Python
>         "//drake/common:symbolic",
>     ],
> )
> ```

I think wee need `add_test_rule=1` here, otherwise this code is untested.

---

*[drake/examples/Pendulum/pendulum_plant.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4pJ7nCXI4ly4YCCEV:-Kj4pJ7oOxbCK2Ma9t0r:b7nqdq1) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/pendulum_plant.cc#L73)):*
> ```cpp
> template class PendulumPlant<double>;
> template class PendulumPlant<AutoDiffXd>;
> template class PendulumPlant<symbolic::Expression>;
> ```

The class overview API comment lists the supported types, and is now lying about Symbolic not being one of them.

---

*[drake/examples/Pendulum/print_symbolic_dynamics.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4q8wrVr9021EhW1MH:-Kj4q8wrVr9021EhW1MI:b-nclwp2) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/print_symbolic_dynamics.cc#L28)):*
> ```cpp
>   system.CalcTimeDerivatives(*context, derivatives.get());
> 
>   std::cout << derivatives->CopyToVector() << std::endl;
> ```

FYI `endl` is unusual and `"\n"` is typical.

---

*[drake/examples/Pendulum/print_symbolic_dynamics.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4pPYhdF10oq4UEKET:-Kj4pPYhdF10oq4UEKEU:b-x8qlie) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/print_symbolic_dynamics.cc#L38)):*
> ```cpp
> }  // namespace drake
> 
> int main(int argc, char* argv[]) {
> ```

FYI Please omit `argc` and `argv` when they are not used.  Later this will be a compiler error (which I will fix at that time if it's still here).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-:-Kj4qfbSx9Wi7rw9dKwa:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4qVERNJbJKRcmX8lY:-Kj5iLEHKyYMfSxcRWWJ:b-wj38dp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Our convention is to also write CMakeLists support for new code when its easy, as it appears to be for this PR.
</blockquote></details>

it's true that it's easy (I have it stashed), but I did not include it for a simple reason:  I named the file without the pendulum_ prefix.  in bazel, i feel that this is justified, and far cleaner (because of both the bazel syntax and the install directory which contains the full path).  in cmake, it's still gross -- I get a make target called simply print_symboic_dynamics, and it is in danger of collidiing with a similarly named method somewhere else in drake.

---

*[drake/examples/Pendulum/BUILD, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4qI1F-kzmh3M1dzQA:-Kj5iugwNNlqb_ZNJk5R:b4f8iom) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/BUILD#L122)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think wee need `add_test_rule=1` here, otherwise this code is untested.
</blockquote></details>

Done.  But actually, even with this `bazel test :print_symbolic_dynamics` complains (Found 1 target, 0 test targets).  same for other binaries in this BUILD file. 

---

*[drake/examples/Pendulum/pendulum_plant.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4pJ7nCXI4ly4YCCEV:-Kj5j2vc3z0f55OC167t:bp9klfu) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/pendulum_plant.cc#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The class overview API comment lists the supported types, and is now lying about Symbolic not being one of them.
</blockquote></details>

wow.  good catch.  done.

---

*[drake/examples/Pendulum/print_symbolic_dynamics.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4q8wrVr9021EhW1MH:-Kj5jDx0cvqQ0EHS3Cv9:b-kvxqi6) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/print_symbolic_dynamics.cc#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `endl` is unusual and `"\n"` is typical.
</blockquote></details>

done.  but this is the only (and therefore last) print of the file... i would have thought flushing was appropriate?

---

*[drake/examples/Pendulum/print_symbolic_dynamics.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4pPYhdF10oq4UEKET:-Kj5kv4A4tuA4onIeox_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/print_symbolic_dynamics.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Please omit `argc` and `argv` when they are not used.  Later this will be a compiler error (which I will fix at that time if it's still here).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5995)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4qVERNJbJKRcmX8lY:-Kj5ptGOxUZaabT_kEn1:b9elww6) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it's true that it's easy (I have it stashed), but I did not include it for a simple reason:  I named the file without the pendulum_ prefix.  in bazel, i feel that this is justified, and far cleaner (because of both the bazel syntax and the install directory which contains the full path).  in cmake, it's still gross -- I get a make target called simply print_symboic_dynamics, and it is in danger of collidiing with a similarly named method somewhere else in drake.
</blockquote></details>

I thought in CMake the binary name could differ from the `.cc` filename though some keyword syntax.  Anyway, that is a fair point and probably counts as "not trivially easy" if you wish, so marking myself resolved.

---

*[drake/examples/Pendulum/BUILD, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4qI1F-kzmh3M1dzQA:-Kj5pC7ixw1UjyN3McGJ:beaq3kq) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/BUILD#L122)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  But actually, even with this `bazel test :print_symbolic_dynamics` complains (Found 1 target, 0 test targets).  same for other binaries in this BUILD file. 
</blockquote></details>

OK I think `//drake/examples/Pendulum/...` (or `...` in the current directory) would run it though.  By my read of`tools/drake.bzl`, I think the target would be named `:print_symbolic_dynamics _test` -- because the program itself is named `:print_symbolic_dynamics`, the test label has to be different.

---

*[drake/examples/Pendulum/print_symbolic_dynamics.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-Kj4q8wrVr9021EhW1MH:-Kj5pe6ot3U7Hv43hBud:b-yotgq2) ([raw file](https://github.com/robotlocomotion/drake/blob/9a89f701f0905fccf4fd22f5529a03dcc818d298/drake/examples/Pendulum/print_symbolic_dynamics.cc#L28)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

done.  but this is the only (and therefore last) print of the file... i would have thought flushing was appropriate?
</blockquote></details>

OK I believe that `cout` is always flushed except in the case of abnormal program termination.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5995)*

**Comment by RussTedrake** [comment]
gah.  fighting against the buildifier in clion (which keeps moving the gflags call) vs command line

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5995#-:-Kj5xyPGHYHDf1-RSF4Q:b-s794vx)*

**Pull request merged**
