### PR TITLE
rigid_body_plant_py: Bind DrakeVisualizer

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8291)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@avalenzu for feature review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8291#-:-L70RutQYWhjjTKXdDv0:blap6ad)*

**Comment by avalenzu** [comment]
:lgtm: +@soonho-tri for platform review.

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8291#-:-L75AV1pb5xBmy2Jr01N:b-sf1n7o)*

**Comment by avalenzu** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8291)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8291#-:-L75JMXM7vX5Nc9ooOVa:bnfp4nl)*

**Pull request merged**
