### PR TITLE
Add support for more sanitizers and coverage to bazel builds

### PR DESCRIPTION
**Pull request by jamiesnape**
This gives you most of what CI has. The open question I have is how to set 

```*SAN_OPTIONS=suppressions=/path/to/*san.supp```

In the initial form of this PR, you would need to set the environment variable beforehand.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4338)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4338#-:-KY-Eq5psU7MYhPxSmdF:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4338#-:-KY-FmZCnRYrY6VB_TBs:bnfp4nl)*

**Pull request merged**
