### PR TITLE
[common] Opt-in to clang-format for the expression package

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18904)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

\CC @hongkai-dai FYI.  Please let me know if you'd rather we not do this.

**Review by hongkai-dai — COMMENTED** [review]
I like to enforce clang-format for my code. Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18904#-:-NPOafkh-uKsZ2ySPvG3:b-1a5qzz)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
I'll keep this one, but it will slide into tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18904#-:-NPQ2g170a2j4fm_hT00:b49x21y)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18904#-:-NPT-fDkCWGIl_QtvcRy:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
