### PR TITLE
[C-IRIS] move cspace_free_polytope_test.cc out of dev folder.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also move several functions in dev/cspace_free_polytope.cc to out of dev.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18905)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

The code has been feature reviewed in the dev folder. Now I move them out of the dev folder, could you do a platform review? Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18905#-:-NPOe0ph7vnuLJ5uQ-or:bk2vl8o)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18905)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: one testing question

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18905#-:-NPP4mMW4GhBjBzG90dE:b-2rywf5)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18905#-NPP4fTXBghM7nMlLFAz:-NPP4fTXBghM7nMlLFB-:bcgl5rf) ([raw file](https://github.com/RobotLocomotion/drake/blob/26ec56fbd460e63f6c6956de7ce10a36cb56dfde/geometry/optimization/cspace_free_polytope.cc#L281)):*
> ```cpp
>                                               index - C.rows());
>     } else {
>       s_lower_redundant_indices->emplace_hint(s_lower_redundant_indices->end(),
> ```

nit This branch is not reached by unit tests. Should I worry?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18905)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/optimization/cspace_free_polytope.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18905#-NPP4fTXBghM7nMlLFAz:-NPPQIke3qL2tbBYFamW:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/26ec56fbd460e63f6c6956de7ce10a36cb56dfde/geometry/optimization/cspace_free_polytope.cc#L281)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit This branch is not reached by unit tests. Should I worry?
</blockquote></details>

Done. Good call.

**Pull request merged**
