### PR TITLE
[common] Introduce diagnostic policy module

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #16229

Co-authored-by: Jeremy Nimmer <jeremy.nimmer@tri.global>

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review.
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641#-:-MwSLtRq3zIHaq8tvFLR:b-58vfpk)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM pending discussions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641#-:-MwS_8vT4x_gfikJMlmE:b-bt1s5p)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/diagnostic_policy.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSXUAMEmO7dqhQkIdI:-MwSXUAN4zaDnntGGSFQ:bytbjqn) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.h#L19)):*
> ```objc
>   std::string message;
> 
>   std::string Format(const std::string& severity) const;
> ```

nit Can we have a (very brief) API comment for these functions?  Either one-by-one, or a single overall comment for all three should be fine too.
___
*[common/diagnostic_policy.h, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSYE6MD-31iK2ETlEp:-MwSYE6MD-31iK2ETlEq:b-kmdj1o) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.h#L39)):*
> ```objc
>   DiagnosticPolicy() = default;
> 
>   /* Trigger a warning. */
> ```

nit I got all of my verbs GSG-wrong, here and below.



_Suggestion:_
```objc
Triggers
```
___
*[common/diagnostic_policy.h, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSXrTV218eLdB3Od7S:-MwSXrTV218eLdB3Od7T:bbbddf2) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.h#L45)):*
> ```objc
>   void Error(std::string message) const;
> 
>   /* (Advanced.) Trigger a warning. */
> ```

nit My mistake, I sometimes forget how we do these.  In general we do `(Advanced)` not `(Advanced.)` because Doxygen likes it much better.  Even though this isn't Doxygenized, we should probably remove the landmine for anyone who cargo-cults this.

Ditto throughout.



_Suggestion:_
```objc
(Advanced)
```
___
*[common/diagnostic_policy.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSYL1j9ju-75-jMGqZ:-MwSYL1j9ju-75-jMGq_:botdwzb) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.h#L55)):*
> ```objc
> 
>   /* (Advanced.) Process an error using default behavior. */
>   static void ErrorDefaultAction(const DiagnosticDetail& detail);
> ```

nit I suppose we could mark this `[[noreturn]]` for clarity?
___
*[common/diagnostic_policy.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSYivQ0uEHLZXv9CaX:-MwSYivQ0uEHLZXv9CaY:b-nvoz3a) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.cc#L21)):*
> ```cpp
>     ss << " ";
>   }
>   ss << severity << ": ";
> ```

nit What should we do if `severity` is empty?  Is it a `@pre` that it be non-empty, or should we throw here, or should be inject a default value `"diagnostic: "`?
___
*[common/test/diagnostic_policy_test.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZRtk4Gc9NKRvK785:-MwSZRtlBEUk28R1GUFQ:br72dar) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L44)):*
> ```cpp
> 
>   //  Errors, by default, throw.
>   EXPECT_THROW(dut.ErrorDefaultAction(detail), std::exception);
> ```

I think the exception message text is important enough to the purpose of this class that we should use `DRAKE_EXPECT_THROWS_MESSAGE` here.
___
*[common/test/diagnostic_policy_test.cc, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZc5P2r4lFpuKq4Aw:-MwSZc5P2r4lFpuKq4Ax:b-sgg9xa) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L52)):*
> ```cpp
> 
>   int count{};
>   auto warning_action = [&count](const DiagnosticDetail&) { count++; };
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement

Ditto below.



_Suggestion:_
```cpp
++count
```
___
*[common/test/diagnostic_policy_test.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZt8bDC4Xyer-hooi:-MwSZt8bDC4Xyer-hooj:byip0fz) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L64)):*
> ```cpp
>   EXPECT_EQ(count, 1);
>   dut.Warning(detail);
>   EXPECT_EQ(count, 2);
> ```

I think the detail's record fields are important enough to the purpose of this class that we should check the contents of the two detail records here.
___
*[common/test/diagnostic_policy_test.cc, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwS_7Qb1l-KQx6fy_O0:-MwS_7Qb1l-KQx6fy_O1:byip0fz) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L85)):*
> ```cpp
>   EXPECT_EQ(count, 1);
>   dut.Error(detail);
>   EXPECT_EQ(count, 2);
> ```

I think the detail's record fields are important enough to the purpose of this class that we should check the contents of the two detail records here.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/diagnostic_policy.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSYivQ0uEHLZXv9CaX:-MwSz3vM1fZQOoKrSwWG:b-ig79qi) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.cc#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit What should we do if `severity` is empty?  Is it a `@pre` that it be non-empty, or should we throw here, or should be inject a default value `"diagnostic: "`?
</blockquote></details>

I suppose `@pre` is least effort, probably sufficient. Another possible move is to take Format() private, and just expose the ones that provide severity.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/diagnostic_policy.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSYivQ0uEHLZXv9CaX:-MwT5qF7BUjDlAU5e3HU:b-5zzspe) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/diagnostic_policy.cc#L21)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I suppose `@pre` is least effort, probably sufficient. Another possible move is to take Format() private, and just expose the ones that provide severity.
</blockquote></details>

Since this is internal-namespace code, I don't have much opinion on which answer is best.  My main concern is that we think about it and write something down to capture our current posture, as clarity for future maintainers.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[common/test/diagnostic_policy_test.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZRtk4Gc9NKRvK785:-MwT86ciEC5tDaLjXpO6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the exception message text is important enough to the purpose of this class that we should use `DRAKE_EXPECT_THROWS_MESSAGE` here.
</blockquote></details>

Done.
___
*[common/test/diagnostic_policy_test.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZt8bDC4Xyer-hooi:-MwT789_-nMVFAHu3EoF:blnsunr) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the detail's record fields are important enough to the purpose of this class that we should check the contents of the two detail records here.
</blockquote></details>

not sure what you have in mind here.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641#-:-MwT98Ok0qLpC_50kxNd:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/test/diagnostic_policy_test.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZt8bDC4Xyer-hooi:-MwT8jvk63sRanJrP_Ak:b-g0whpk) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L64)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

not sure what you have in mind here.
</blockquote></details>

For example, the callback could push the detail onto a vector (instead of just counting it), and then `EXPECT_EQ` on the fields of the details that end up in that vector.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/test/diagnostic_policy_test.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwSZt8bDC4Xyer-hooi:-MwTCbNU2bnHXFlH7Kv2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For example, the callback could push the detail onto a vector (instead of just counting it), and then `EXPECT_EQ` on the fields of the details that end up in that vector.
</blockquote></details>

Done.
___
*[common/test/diagnostic_policy_test.cc, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwS_7Qb1l-KQx6fy_O0:-MwTCc480VwxtdZ900Cd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4a8fa587153915fe1bb90144a27185cac545d9c/common/test/diagnostic_policy_test.cc#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the detail's record fields are important enough to the purpose of this class that we should check the contents of the two detail records here.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641#-:-MwTGM000_dcJMi9yd4G:bwjee3b)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Sorry, I've hit my limit for the day! I'm going to roll it over to next review, if that's OK!
-@ericcousineau-tri +@xuchenhan-tri for platform, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641#-:-MwTVm0r-LIBAJw5KVZ1:b-q8nw2t)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641#-:-MwU5xjk1nMSwYUmmAFE:bcpz082)* status: 2 unresolved discussions (waiting on @rpoyner-tri)

___
*[common/diagnostic_policy.h, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwU5_-06PWoWQFSa1Po:-MwU5_-06PWoWQFSa1Pp:b-qjgohx) ([raw file](https://github.com/robotlocomotion/drake/blob/0c05609f4ce8ec5396b168a5942673f2151807cc/common/diagnostic_policy.h#L18)):*
> ```objc
>   std::optional<int> line;
>   std::string message;
> ```

nit, unintended extra blank line?
___
*[common/diagnostic_policy.h, line 46 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwU2UPU8I-yYCd2v4PY:-MwU2UPU8I-yYCd2v4PZ:be46qm1) ([raw file](https://github.com/robotlocomotion/drake/blob/0c05609f4ce8ec5396b168a5942673f2151807cc/common/diagnostic_policy.h#L46)):*
> ```objc
> 
> Note in particular that the user's replacement error callback is not required
> to throw.  Code that calls policy.Error must be prepared to received control
> ```

nit, s/received/receive
___
*[common/test/diagnostic_policy_test.cc, line 76 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16641#-MwU5MFl17Wdq5g2QFnJ:-MwU5MFm8IHRS5kqxi6u:beq46ah) ([raw file](https://github.com/robotlocomotion/drake/blob/0c05609f4ce8ec5396b168a5942673f2151807cc/common/test/diagnostic_policy_test.cc#L76)):*
> ```cpp
>   EXPECT_EQ(*details.back().filename, "a.txt");
>   EXPECT_EQ(*details.back().line, 22);
>   EXPECT_EQ(details.back().message, "well");
> ```

BTW, worth testing that explicitly passing in a `nullptr` restores the default behavior? Ditto below.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16641)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
