### PR TITLE
Add ClarabelSolver.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #19449.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-:-NguJvDC9k2HCwHoHl4u:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
My vote would be do use "release notes: feature" and to update `mathematical_program_doxygen.h` to mention the new solver in the program classification tables.  We would just need a footnote explaining that it's an experimental feature that requires installing from source.  (We'd remove the footnote once it's not experimental anymore.)

**Review by hongkai-dai — COMMENTED** [review]
Done. I added the change in `mathematical_program_doxygen.h`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-:-NgutaPM5QDZzFqqC_11:b420kq8)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by AlexandreAmice — COMMENTED** [review]
Looks great. Mostly docstring clean up and some comment about the tolerance.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-:-NgysbvM-6zKycvH7YPr:b-sa91da)* status: 23 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/BUILD.bazel` line 1668 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgxkEs74viwRbaTg7n_:-NgxkEs74viwRbaTg7na:b-90q4q8) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/BUILD.bazel#L1668)):*
> ```Starlark
>         ":quadratic_program_examples",
>         ":second_order_cone_program_examples",
>         ":semidefinite_program_examples",
> ```

Maybe it's a footgun to add these dependencies before clarabel supports SDP?
___
*[`solvers/clarabel_solver.cc` line 16 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgxsTr9CUk33WZJmbUq:-NgxsTr9CUk33WZJmbUr:b-hcfhi) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L16)):*
> ```cpp
> namespace solvers {
> namespace {
> void ParseBoundingBoxConstraints(
> ```

Can you document the arguments here? Also why is this parse function special and needs to be included in the solver cc?
___
*[`solvers/clarabel_solver.cc` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngy8WdV4fLVPSuxhtim:-Ngy8WdV4fLVPSuxhtin:bp2sufc) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L36)):*
> ```cpp
>     bbcon_dual_indices->emplace_back(
>         prog.bounding_box_constraints()[i].variables().rows(),
>         std::pair<int, int>(-1, -1));
> ```

I don't understand this code. Why can the dual indices be negative?
___
*[`solvers/clarabel_solver.cc` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngy9Pmu0FSFDJkmTqof:-Ngy9Pmu0FSFDJkmTqog:baiollh) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L88)):*
> ```cpp
> }
> 
> std::string SolverStatusToString(const clarabel::SolverStatus status) {
> ```

Can you link to where these solver statuses are defined by clarabel?
___
*[`solvers/clarabel_solver.cc` line 183 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyivQa1AMZrsT-FHOQ:-NgyivQa1AMZrsT-FHOR:bulwe3z) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L183)):*
> ```cpp
>   // We need to construct a sparse matrix in Column Compressed Storage (CCS)
>   // format. On the other hand, we add the constraint row by row, instead of
>   // column by column, as preferred by CCS. As a result, we use Eigen sparse
> ```

This is just the default way to build sparse Eigen matrices no?



_Suggestion:_
```cpp
  // format. We use Eigen sparse
```
___
*[`solvers/clarabel_solver.cc` line 189 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyj6bEE_gR3fdmjva1:-Ngyj6bEE_gR3fdmjva2:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L189)):*
> ```cpp
>   // We need to construct a sparse matrix in Column Compressed Storage (CCS)
>   // format. Since we add an array of quadratic cost, each cost has its own
>   // associated variables, we use Eigen sparse matrix to aggregate the quadratic
> ```





_Suggestion:_
```cpp
.W
```
___
*[`solvers/clarabel_solver.cc` line 190 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyjCO2CaJtvaz3c8dF:-NgyjCO2CaJtvaz3c8dG:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L190)):*
> ```cpp
>   // format. Since we add an array of quadratic cost, each cost has its own
>   // associated variables, we use Eigen sparse matrix to aggregate the quadratic
>   // cost Hessian matrices. SCS only takes the upper triangular entries of the
> ```





_Suggestion:_
```cpp
Clarabel
```
___
*[`solvers/clarabel_solver.cc` line 203 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyjNcP3U5Qv5t87e-n:-NgyjNcP3U5Qv5t87e-o:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L203)):*
> ```cpp
>   std::vector<double> q(num_x, 0.0);
> 
>   // Our cost (LinearCost, QuadraticCost, etc) also allows a constant term, we
> ```





_Suggestion:_
```cpp
costs
```
___
*[`solvers/clarabel_solver.cc` line 216 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngykf7d3-Ouu8QkQBrw:-Ngykf7d3-Ouu8QkQBrx:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L216)):*
> ```cpp
>   // y[linear_eq_y_start_indices[i]:
>   // linear_eq_y_start_indices[i] +
>   // prog.linear_equality_constraints()[i].evaluator()->num_constraints] are the
> ```





_Suggestion:_
```cpp
num_constraints(
```
___
*[`solvers/clarabel_solver.cc` line 232 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgylLxY5qXvk4VfJwlX:-NgylLxY5qXvk4VfJwlY:b-4pb065) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L232)):*
> ```cpp
>   // variable for the lower/upper bound of the j'th row in the bounding box
>   // constraint prog.bounding_box_constraint()[i], we use -1 to indicate that
>   // the lower or upper bound is infinity.
> ```

FYI: the / in between numerical values make me think that you're dividing the two values. Ditto for the parse linear constraint on all changes.



_Suggestion:_
```cpp
  // Parse bounding box constraints.
  // bbcon_dual_indices[i][j][0] (resp. bbcon_dual_indices[i][j][1]) is the dual
  // variable for the lower (resp. upper) bound of the j'th row in the bounding box
  // constraint prog.bounding_box_constraint()[i]. Since the dual variables are constrained to be positive, we use -1 to indicate that
  // the lower is -∞ or the upper bound is +∞ respectively.
```
___
*[`solvers/clarabel_solver.cc` line 263 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngym3eP4eFEW5rzxqor:-Ngym3eP4eFEW5rzxqos:b-mqhynt) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L263)):*
> ```cpp
>     cones.push_back(clarabel::SecondOrderConeT<double>(soc_length));
>   }
> ```

Could you add a TODO here indicating that the PSD constraints **must** be added at this part of the code. I worry that in a future review, I won't see the docstring and so will forget to ensure that these are added in the correct order.
___
*[`solvers/clarabel_solver_common.cc` line 39 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyo1EY-ET_MD59V8au:-Ngyo1EY-ET_MD59V8av:b-e6ye9m) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver_common.cc#L39)):*
> ```cpp
>           ProgramAttribute::kRotatedLorentzConeConstraint,
>           ProgramAttribute::kExponentialConeConstraint,
>           ProgramAttribute::kLinearCost, ProgramAttribute::kQuadraticCost});
> ```

Do we need to check if the Quadratic Cost is PSD?
___
*[`solvers/mathematical_program_doxygen.h` line 166 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyofnb70O_N-OZIVKM:-Ngyofnb70O_N-OZIVKN:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/mathematical_program_doxygen.h#L166)):*
> ```objc
>  *
>  * ▣ Drake's support on Clarabel is experimental. Some Clarabel's features (such
>  * as positive semidfinite constraint) are not supported by Drake yet.
> ```





_Suggestion:_
```objc
constraints
```
___
*[`solvers/no_clarabel.cc` line 17 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyokol-NuHoCNwii0D:-Ngyokol-NuHoCNwii0E:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/no_clarabel.cc#L17)):*
> ```cpp
>                              MathematicalProgramResult*) const {
>   throw std::runtime_error(
>       "The Clarabel bindings were not compiled.  You'll need to use a "
> ```





_Suggestion:_
```cpp
The Clarabel bindings were not compiled. You'll need to use a
```
___
*[`solvers/test/clarabel_solver_test.cc` line 19 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyozCUBXJ3hVxqg2eG:-NgyozCUBXJ3hVxqg2eH:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L19)):*
> ```cpp
> namespace test {
> const double kTol = 1E-5;
> GTEST_TEST(LinearProgramTest, Test0) {
> ```





_Suggestion:_
```cpp
TestGeneralLP
```
___
*[`solvers/test/clarabel_solver_test.cc` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyp8693tW9RKg9T45-:-Ngyp8693tW9RKg9T450:bes0d4c) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L29)):*
> ```cpp
>   prog.AddLinearConstraint(x(0) + x(1) == 2);
>   ClarabelSolver solver;
>   if (solver.available()) {
> ```

I think it would be better to add a test tag filter rather than have to call this check every time. Ditto for rest of file
___
*[`solvers/test/clarabel_solver_test.cc` line 71 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgypkaK73H54mLGFft_:-NgypkaK73H54mLGFfta:b-2g9cpn) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L71)):*
> ```cpp
>   // The optimal cost is 11, the optimal solution is x = (2, 0)
>   prog.AddLinearCost(2 * x(0) - 3 * x(1) + 5);
>   prog.AddBoundingBoxConstraint(2, 6, x(0));
> ```

Why 6? Just so that we test a redundant constraint?



_Code quote:_
```cpp
6
```
___
*[`solvers/test/clarabel_solver_test.cc` line 82 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyp1Pw2vfFwTo8HXVI:-Ngyp1PxA95DIaWbJwwm:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L82)):*
> ```cpp
> }
> 
> GTEST_TEST(LinearProgramTest, Test1) {
> ```





_Suggestion:_
```cpp
TestInfeasibleEqualityOnlyLP
```
___
*[`solvers/test/clarabel_solver_test.cc` line 102 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyq-Sk9MtQKVSXYnwu:-Ngyq-Sk9MtQKVSXYnwv:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L102)):*
> ```cpp
> }
> 
> GTEST_TEST(LinearProgramTest, Test2) {
> ```





_Suggestion:_
```cpp
TestAllLPConstraintTypes
```
___
*[`solvers/test/clarabel_solver_test.cc` line 174 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyqqmH3e5aQy0ZVUBd:-NgyqqmH3e5aQy0ZVUBe:b-6vc9e7) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L174)):*
> ```cpp
>                     .array()
>                     .isFinite()
>                     .all());
> ```

Why do we still expect the result to give finite values for all the decision variables?



_Code quote:_
```cpp
    EXPECT_TRUE(result.GetSolution(prog_->decision_variables())
                    .array()
                    .isFinite()
                    .all());
```
___
*[`solvers/test/clarabel_solver_test.cc` line 250 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyrCZKB3uJusq56rA5:-NgyrCZKB3uJusq56rA6:b2jcl00) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L250)):*
> ```cpp
>     const auto result = solver.Solve(prob.prog(), {}, {});
>     // Practically I observe Clarabel requires looser tolerance for this test. I
>     // don't know why.
> ```

Is the return of this `AlmostSolved`? If so, maybe the unit test should capture that? The tolerance is already extremely loose at `1e-5` so I think this is a concern.



_Code quote:_
```cpp
    // Practically I observe Clarabel requires looser tolerance for this test. I
    // don't know why.
```
___
*[`solvers/test/clarabel_solver_test.cc` line 272 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgysKtc7sieah5DthRI:-NgysKtc7sieah5DthRJ:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L272)):*
> ```cpp
>   ClarabelSolver solver;
>   if (solver.available()) {
>     // Currently we don't support retrieving dual solution from SCS yet.
> ```





_Suggestion:_
```cpp
Currently we don't support retrieving dual solutions for exponential cone constraints from Clarabel yet.
```
___
*[`solvers/test/clarabel_solver_test.cc` line 18 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyrUmG3W-LfzMlvTxd:-NgyrUmH7Lc2FJ_q7sco:bfvu779) ([raw file](https://github.com/RobotLocomotion/drake/blob/b73b010b531a10fd268509b89328c3657ccdfc4b/solvers/test/clarabel_solver_test.cc#L18)):*
> ```cpp
> namespace solvers {
> namespace test {
> const double kTol = 1E-5;
> ```

This is fairly loose for an interior point solver no? According to the (Julia)[https://docs.juliahub.com/Clarabel/g676L/0.4.0/autodocs/] documentation, if we are running the solver in full accuracy mode (which I would expect), this should be either `1e-8` or `1e-7`



_Code quote:_
```cpp
const double kTol = 1E-5;
```
___
*[`solvers/test/optimization_examples.cc` line 157 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgysRza1rXvnP3Rpq65:-NgysRza1rXvnP3Rpq66:b-fmeukn) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/optimization_examples.cc#L157)):*
> ```cpp
>   }
>   if (solver_id == ClarabelSolver::id()) {
>     return 1E-5;
> ```

Ditto, according to the documentation this should be `1e-8` unless we are using the low-accuracy version.



_Code quote:_
```cpp
return 1E-5;
```

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-:-Nh34LTE3gywZHW5lzCD:bnfp4nl)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/clarabel_solver.cc` line 27 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh32rEP2yBkpwnkE9JF:-Nh32rEP2yBkpwnkE9JG:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/cfff45f3d769d6cff32d1750a31a322580bf2d70/solvers/clarabel_solver.cc#L27)):*
> ```cpp
> // @param[out] bbcon_dual_indices bbcon_dual_indices[i][j] are the indices of
> // the dual variable for the j'th row of prog.bounding_box_constraints()[i]. We
> // use -1 to indicate that this constraint is impossible to be active (for
> ```

nit



_Suggestion:_
```cpp
that it is impossible for this constraint to be active
```
___
*[`solvers/clarabel_solver.cc` line 28 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh32oIDBvdEjBjiHegE:-Nh32oIDBvdEjBjiHegF:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/cfff45f3d769d6cff32d1750a31a322580bf2d70/solvers/clarabel_solver.cc#L28)):*
> ```cpp
> // the dual variable for the j'th row of prog.bounding_box_constraints()[i]. We
> // use -1 to indicate that this constraint is impossible to be active (for
> // example, another BoundingBoxConstraint imposed a tighter bound on the same
> ```

nit



_Suggestion:_
```cpp
imposes
```
___
*[`solvers/clarabel_solver.cc` line 189 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh33q1zB0mnzLA3_qmq:-Nh33q1zB0mnzLA3_qmr:b-l8wrfd) ([raw file](https://github.com/RobotLocomotion/drake/blob/cfff45f3d769d6cff32d1750a31a322580bf2d70/solvers/clarabel_solver.cc#L189)):*
> ```cpp
>   // Exponential cone {x,y,z): y>0, y*exp(x/y) <= z}
>   // Power cone {(x, y, z): pow(x, α)*pow(y, 1-α) >= |z|, x>=0, y>=0} with α in
>   // (0, 1)
> ```

You mention in other parts of the review that the cones do not need to be in a specific order. In that case, we need to remove this section



_Code quote:_
```cpp
  // The cones have to be in this order
  // Zero cone {x | x = 0 }
  // Positive orthant {x | x ≥ 0 }
  // Second-order cone {(t, x) | |x|₂ ≤ t }
  // Positive semidefinite cone { X | min(eig(X)) ≥ 0, X = Xᵀ }
  // Exponential cone {x,y,z): y>0, y*exp(x/y) <= z}
  // Power cone {(x, y, z): pow(x, α)*pow(y, 1-α) >= |z|, x>=0, y>=0} with α in
  // (0, 1)
```
___
*[`solvers/test/clarabel_solver_test.cc` line 71 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgypkaK73H54mLGFft_:-Nh349uz6epdCAh5yWBp:b368vz1) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L71)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Exactly. We want to have a redundant constraint.
</blockquote></details>

Nit: add a comment to point that out.

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-:-Nh3UDW61kpANndnSRBU:b-3lhrgq)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`solvers/clarabel_solver.cc` line 183 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgyivQa1AMZrsT-FHOQ:-Nh3TweEBybAyMANno4G:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/clarabel_solver.cc#L183)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I changed the document. Clarabel doesn't need the matrix in the CCS format.
</blockquote></details>

Done.
___
*[`solvers/clarabel_solver.cc` line 189 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh33q1zB0mnzLA3_qmq:-Nh3TtlO6_9KM0AeMj0_:b-376vyb) ([raw file](https://github.com/RobotLocomotion/drake/blob/cfff45f3d769d6cff32d1750a31a322580bf2d70/solvers/clarabel_solver.cc#L189)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

You mention in other parts of the review that the cones do not need to be in a specific order. In that case, we need to remove this section
</blockquote></details>

Done. Good catch.
___
*[`solvers/test/clarabel_solver_test.cc` line 71 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-NgypkaK73H54mLGFft_:-Nh3U3-q2dcfPBN97Z5V:b4e8w92) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L71)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Nit: add a comment to point that out.
</blockquote></details>

It was added just after `6` in the line below.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 3 of 7 files at r1, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-:-Nh3u6qPASNC12oRG66e:b-cxwtpw)* status: 5 unresolved discussions

___
*[`solvers/clarabel_solver.h` line 17 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3h97fD1mnHbkVEjIa:-Nh3h97fD1mnHbkVEjIb:b-ppyrt9) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.h#L17)):*
> ```objc
>   int iterations;
> 
>   // The status from Clarabel.
> ```

BTW, is the `//` instead of `///` intentional?



_Code quote:_
```objc
// The status from Clarabel.
```
___
*[`solvers/clarabel_solver.cc` line 51 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3rcTCAoL0Z6FtlsYL:-Nh3rcTCAoL0Z6FtlsYM:b71twnl) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.cc#L51)):*
> ```cpp
>   // positive orthant cone.
>   // 3. If lb is finite, then we add the constraint -x + s = -lb with s in the
>   // positive orthant cone.
> ```

BTW, suggestion, feel free to ignore



_Suggestion:_
```cpp
  // 1. If lb == ub (and both are finite), then we add the constraint x + s = ub
  // with s in the zero cone.
  // 2. Otherwise, if ub is finite, then we add the constraint x + s = ub with s in the
  // positive orthant cone. If lb is finite, then we add the constraint -x + s = -lb with s in the
  // positive orthant cone.
```
___
*[`solvers/clarabel_solver.cc` line 54 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3lfazE0jYXeLUIAfZ:-Nh3lfb--5O44dJndZhn:b-ukgjbl) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.cc#L54)):*
> ```cpp
>   // Set the dual variable indices.
>   bbcon_dual_indices->reserve(std::ssize(prog.bounding_box_constraints()));
>   for (int i = 0; i < std::ssize(prog.bounding_box_constraints()); ++i) {
> ```

nit we should use drake's polyfill of ssize until c++20 is supported on all platforms. You'd need to include `drake/common/ssize.h"



_Suggestion:_
```cpp
for (int i = 0; i < ssize(prog.bounding_box_constraints()); ++i) {
```
___
*[`solvers/clarabel_solver.cc` line 84 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3rnc90c8QLJrbYS9V:-Nh3rncA5ODuCPgqmUqK:b-uxu2uo) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.cc#L84)):*
> ```cpp
>         (*bbcon_dual_indices)[i][j].second = *A_row_count;
>         cones->push_back(clarabel::ZeroConeT<double>(1));
>         (*A_row_count)++;
> ```

nit prefer preincrement



_Suggestion:_
```cpp
        ++(*A_row_count);
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)* status: 8 unresolved discussions

___
*[`solvers/clarabel_solver.h` line 11 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3v1zY4bZnSZucsBbD:-Nh3v1zY4bZnSZucsBbE:b-jivpe0) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.h#L11)):*
> ```objc
> namespace solvers {
> 
> struct ClarabelSolverDetails {
> ```

nit Missing class overview Doxygen.  (The SnoptSolverDetails is a good template.)
___
*[`solvers/clarabel_solver.h` line 15 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3upg31mT98nuYyknD:-Nh3upg31mT98nuYyknE:b200mih) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.h#L15)):*
> ```objc
>   double solve_time;
>   /// Number of iterations in Clarabel.
>   int iterations;
> ```

nit Here and above we need `{}` to initialize the POD struct fields.
___
*[`solvers/clarabel_solver.h` line 21 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3uuXH6C_S6uUZnr_S:-Nh3uuXH6C_S6uUZnr_T:b-vsvjtp) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.h#L21)):*
> ```objc
> };
> 
> class ClarabelSolver final : public SolverBase {
> ```

nit Missing class overview Doxygen.
___
*[`solvers/test/clarabel_solver_test.cc` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyp8693tW9RKg9T45-:-Nh3vCnj0Cv8XIErIELA:b-khix3o) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L29)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We do not have that test tag filter yet. @jwnimmer-tri should we add a test tag filter for enabling clarabel?
</blockquote></details>

When Clarabel is disabled, shouldn't we still be checking that the program setup code (adding constraints etc) doesn't crash?

This is the same pattern as _all_ of our solver tests use.  If we're going to change the pattern, we should do it universally for all tests in this folder -- and probably its a dedicated PR.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)* status: 1 unresolved discussion

___
*[`solvers/clarabel_solver.h` line 17 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh3h97fD1mnHbkVEjIa:-Nh3vkk2E2EALXqM8fcP:b-376vyb) ([raw file](https://github.com/RobotLocomotion/drake/blob/d37d9e0736c83a5314c7ca452780e0d3306b4fed/solvers/clarabel_solver.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is the `//` instead of `///` intentional?
</blockquote></details>

Done. Good catch.
___
*[`solvers/test/clarabel_solver_test.cc` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Ngyp8693tW9RKg9T45-:-Nh3wFQhDHU_F5ihaPpG:bu02plx) ([raw file](https://github.com/RobotLocomotion/drake/blob/13b38ca1a284500ea7d5f41363a44d54d6f28191/solvers/test/clarabel_solver_test.cc#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When Clarabel is disabled, shouldn't we still be checking that the program setup code (adding constraints etc) doesn't crash?

This is the same pattern as _all_ of our solver tests use.  If we're going to change the pattern, we should do it universally for all tests in this folder -- and probably its a dedicated PR.
</blockquote></details>

Got it. I think it makes sense to still check the program setup code.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)* status: 1 unresolved discussion

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  mac-arm-ventura-clang-bazel-experimental-everything-release please.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20375)* status: 1 unresolved discussion

___
*[`solvers/clarabel_solver.h` line 11 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20375#-Nh9VrTG7fMk_ltirJmH:-Nh9VrTG7fMk_ltirJmI:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/5ab12016b0cdc5ca6545aba43c3033525f5bbda7/solvers/clarabel_solver.h#L11)):*
> ```objc
> namespace solvers {
> 
> /// The Clarabel solver details after calling Solve() function. The user can
> ```

nit: typo



_Suggestion:_
```objc
the Solve()
```

**Pull request merged**
