### PR TITLE
Infrastructure for declaring MATLAB dependencies for ctest

### LINKED ISSUE #2384: WITH_IRIS option should depend on WITH_MOSEK option
```
Performing configure step for 'iris_project'
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/gcc-4.9
-- Check for working C compiler: /usr/bin/gcc-4.9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-4.9
-- Check for working CXX compiler: /usr/bin/g++-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found matlab
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Found eigen3
-- Checking for module 'mosek'
--   No package 'mosek' found
-- Configuring incomplete, errors occurred!
```
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=21741

### PR DESCRIPTION
**Pull request by jamiesnape**
Addresses in part #1997. Someone will need to go through all the MATLAB files and correlate the dependencies that are required for each `ctest` test. A limited number have been declared to test this PR and as an example. Also fixes #2384.

FYI @RussTedrake.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2463)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> #### Infrastructure for declaring MATLAB dependencies for ctest
> 
> Addresses in part #1997. Someone will need to go through all the MATLAB files and correlate the dependencies that are required for each `ctest` test. A limited number have been declared to test this PR and as an example. Also fixes #2384.
> 
> 
> 
> FYI @RussTedrake.
> 
> 
> 
> 
> 
> 
</details>


---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 163 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2463#-KJ6P47kxQLSS4MvSPSC:-KJ6P47kxQLSS4MvSPSD:-508453275) ([raw file](https://github.com/robotlocomotion/drake/blob/13bc0aa91c8c3b2c67401c44450fd349fcd8e385/drake/CMakeLists.txt#L163)):*
> ```CMake
>     foreach(require ${parsed_args_REQUIRES})
>       if(NOT EXISTS "${CMAKE_INSTALL_PREFIX}/matlab/addpath_${require}.m")
>         message(STATUS "Not running ${parsed_args_NAME} because ${require} was not installed.")
> ```

FYI future readers - this does not appear anywhere in the CI output for this PR: 

https://drake-jenkins.csail.mit.edu/job/experimental/1863/compiler=gcc,label=linux_matlab/console

---

*[drake/CMakeLists.txt, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2463#-KJ6A2nl_LYs9ChFMf92:-KJ6A2nl_LYs9ChFMf93:-595698865) ([raw file](https://github.com/robotlocomotion/drake/blob/13bc0aa91c8c3b2c67401c44450fd349fcd8e385/drake/CMakeLists.txt#L194)):*
> ```CMake
>   endif()
> 
> #  if(parsed_args_REQUIRES)
> ```

delete?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2463#-:-KJ6PGvhQ2GEhyOMQCt4:1417088721)*

**Comment by david-german-tri** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2463)*

**Comment by jamiesnape** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 163 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2463#-KJ6P47kxQLSS4MvSPSC:-KJ6S-O8fT3iRw06wMNf:1581769141) ([raw file](https://github.com/robotlocomotion/drake/blob/13bc0aa91c8c3b2c67401c44450fd349fcd8e385/drake/CMakeLists.txt#L163)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> FYI future readers - this does not appear anywhere in the CI output for this PR: 
> 
> https://drake-jenkins.csail.mit.edu/job/experimental/1863/compiler=gcc,label=linux_matlab/console
</details>
It should first make an appearance in the MATLAB / Open Source Only continuous builds.

---

*[drake/CMakeLists.txt, line 194 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2463#-KJ6A2nl_LYs9ChFMf92:-KJ6RzSAOIAmPEJV0Bzo:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/13bc0aa91c8c3b2c67401c44450fd349fcd8e385/drake/CMakeLists.txt#L194)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> delete?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2463)*

**Comment by RussTedrake** [comment]
sigh.  this went by without me having a chance to comment.  one fundamental problem is that cmake might not find all of the dependencies that matlab can find.  (e.g., matlab might find snopt because the user has installed it independently and added it to their matlab path, but cmake will simply disable that test).  i guess i'm ok with this living as is, since it disables the ctest but not the functionality; so people / build servers using the ctest scripts simply have to play by our rules.

**Comment by jamiesnape** [comment]
The solution with that is to ensure that cmake finds those dependencies. We can iterate on that. As you say, it only disables the ctest.

**Pull request merged**
