### PR TITLE
[WIP] Implements SpaceXYZFloatingJoint

### LINKED ISSUE #14949: Add a 6dof (free) RollPitchYaw joint
Currently for floating joint, we default to use quaternion to represent its orientation. There are cases when an Euler-angle representation (like roll-pitch-yaw) is preferred

1. In trajectory optimization, using quaternion requires adding the unit length constraint, and extra constraint on the integration scheme.
2. For some applications like planes, it is common to use Euler angles.

Hence I would like to request adding roll-pitch-yaw as another representation for floating base orientation.

cc @RussTedrake

### PR DESCRIPTION
**Pull request by amcastro-tri**
Closes #14949

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19065)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
For consistency, please consider a different name for this joint. Currently we have
quaternion_floating
ball_rpy (uses a space xyz Euler sequence)

"rpy" is the common robotics term and we've been using that everywhere.

So this joint should be "rpy_floating" or "floating_rpy".

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19065#-:-NSHQclsC6dlv6eEAhkq:b-ogpkwd)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by xuchenhan-tri — COMMENTED** [review]
I ran into #14949 in a review today and remembered about this PR. What's missing from this PR that's preventing it from reaching the finish line?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19065#-:-Nd1JEbN4PHJfU9mpWUv:b2298g2)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
IMO it would be good to split this into several pieces:
- add a floating_rpy_joint (and fix the naming of the underlying mobilizer, currently space_xyz_floating), with unit tests.
- add sdf/urdf parsing
- add the API for control over use of floating_quaternion vs floating_rpy

I need the first piece as a yak shave for the new MbP graphing stuff because the space_xyz_floating_mobilizer unit tests need to be reworked to mention only the joint (all the other mobilizer tests have been modified that way).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19065#-:-Nd1Vyts-3YB25q_CHT0:b9983sy)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @amcastro-tri)

**Comment by amcastro-tri** [comment]
> IMO it would be good to split this into several pieces

Sounds good. I'll push the mobilizer/joint and plant PRs separately.

I'll defer parsing to someone else though.

**Comment by jwnimmer-tri** [comment]
This PR overview says "Closes #14949" but that issue is already closed.  Is there anything left in this PR that we want to rescue?

Maybe the idea of a `default_floating_joint_type` that's part of the config struct?

**Comment by jwnimmer-tri** [comment]
Ah, I see now that's tracked by #20943 already.  Maybe we can just close this PR?  If we want to resurrect parts of it, we can use a new PR number for that?

**Pull request closed without merging**
