### PR TITLE
Update pycps version to fix typo in generated drake-config.cmake

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed by RobotLocomotion/drake-shambhala#8.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6602)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
LGTM

**Comment by jamiesnape** [comment]
+@ggould-tri and +@EricCousineau-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

Diff being referenced by version change: https://github.com/mwoehlke/pycps/commit/a6110cf2e769e9ff262a98ed18506ad565a14e89

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6602#-:-KpQbb9ZR-gEL2tL8lUS:br6t1kx)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6602#-:-KpQkcE85FtDFCa99RcN:bnfp4nl)*

**Pull request merged**
