### PR TITLE
demo code fix after lcm_driven_loop merge.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
re-enable the two examples based on lcm driven loop:
iiwa_controller.cc and valkyrie_balancing_controller_system.cc

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5787)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for feature review. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-:-KhP43g3bvvBXhrjiWKx:b-14wkhw)*

**Comment by sammy-tri** [comment]
Does this fix #5736?  (if it does, the ticket probably should probably be updated to something like "Make IiwaStateFeedbackPlanSource go away")

:lgtm: aside from issue below

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSYIekqccmimHYDLpc:-KhSYIemBBBYN_KAwCsX:b-88v4u1) ([raw file](https://github.com/robotlocomotion/drake/blob/81e0dd6a0ccdc6ff37a945c30357ac60ebc527ae/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L43)):*
> ```objc
>   /**
>    * Makes a plan to hold at the measured joint configuration @p q0 starting at
>    * @p plan_start_time. This function needs to be explicitly called, otherwise
> ```

Truncated comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-:-KhSZVV58U_10CF0p1ie:b-r9jhsa)*

**Comment by siyuanfeng-tri** [comment]
hmm, it does fix that. i totally forgot about it. i am leaving purging IiwaStateFeedbackPlanSource or not up to @naveenoid . 
naveen, the high level bit here is, if we merge this, you need to explicitly call Initialize before doing any simulation. that should be too problematic in your giant diagram. note that you can recursively get sub diagram's context from the top level context. so all you need is a ptr to this. 

+@sherm1 for platform review. thanks!

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSYIekqccmimHYDLpc:-KhSciWUiEM0Hyiy-2sa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81e0dd6a0ccdc6ff37a945c30357ac60ebc527ae/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L43)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Truncated comment?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-:-KhSbC8yE5MEKAljDTtY:be6jf38)*

**Comment by sherm1** [comment]
Platform :lgtm:, pending a few minor BTWs.

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSyZ1Mmm0ZpmXxa2ax:-KhSyZ1Mmm0ZpmXxa2ay:b-kzm3ep) ([raw file](https://github.com/robotlocomotion/drake/blob/b8aa99a8c138d00791dc51c5c7f6626fe8a55d71/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L64)):*
> ```cpp
>   const PlanData default_plan;
>   abstract_vals.push_back(systems::AbstractValue::Make<PlanData>(default_plan));
>   abstract_vals.push_back(systems::AbstractValue::Make<bool>(false));
> ```

BTW the meaning of this second abstract state variable is not clear. Please explain in a comment. Also note the connection between these two variables and the index constants you defined above.

Consider encapsulating access to these variables in a few small accessor functions that will hide the repeated access details, like `has_been_initialized(context)` `set_plan(context, plan)`, `get_plan(context)` etc.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSxNIn4O0aX4wkiKJg:-KhSxNIn4O0aX4wkiKJh:b8ghssw) ([raw file](https://github.com/robotlocomotion/drake/blob/b8aa99a8c138d00791dc51c5c7f6626fe8a55d71/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L46)):*
> ```objc
>    * simulation. Otherwise this aborts in CalcOutput().
>    */
>   void Initialize(const double plan_start_time, const VectorX<double>& q0,
> ```

BTW spurious `const` on by-value parameter `plan_start_time`. See style guide [clarifications](http://drake.mit.edu/code_style_guide.html), look for: "You must not use const in a function declaration where it adds no meaning." for more info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-:-KhSzt52kOjIISIEy8A3:bmm1b6l)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSyZ1Mmm0ZpmXxa2ax:-KhT4GA5nejnQzM0IrKY:b-n200ry) ([raw file](https://github.com/robotlocomotion/drake/blob/b8aa99a8c138d00791dc51c5c7f6626fe8a55d71/drake/examples/kuka_iiwa_arm/iiwa_plan_source.cc#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the meaning of this second abstract state variable is not clear. Please explain in a comment. Also note the connection between these two variables and the index constants you defined above.

Consider encapsulating access to these variables in a few small accessor functions that will hide the repeated access details, like `has_been_initialized(context)` `set_plan(context, plan)`, `get_plan(context)` etc.
</blockquote></details>

added comments. i am going to let the named accessor slip this time. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSxNIn4O0aX4wkiKJg:-KhT43WnzEBDu13-lMYp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8aa99a8c138d00791dc51c5c7f6626fe8a55d71/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L46)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW spurious `const` on by-value parameter `plan_start_time`. See style guide [clarifications](http://drake.mit.edu/code_style_guide.html), look for: "You must not use const in a function declaration where it adds no meaning." for more info.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/iiwa_plan_source.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5787#-KhSYIekqccmimHYDLpc:-KhTP7eDXBSvJhpl2Cpz:b-o9h30h) ([raw file](https://github.com/robotlocomotion/drake/blob/81e0dd6a0ccdc6ff37a945c30357ac60ebc527ae/drake/examples/kuka_iiwa_arm/iiwa_plan_source.h#L43)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@sammy-tri can you resolve this? thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5787)*

**Pull request merged**
