### PR TITLE
[C-IRIS] compute the distance from a halfspace to a collision geometry.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18475)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18475#-:-NJapYn5DMiCvlWtyij9:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: minus some typos

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18475#-:-NJbk66e0i3PdSf6nxZD:bfd1zfm)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 421 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18475#-NJbjjcIDAUoN4MEGceM:-NJbjjcIDAUoN4MEGceN:b9jom4i) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ebc11da8fe4e5da21d91d5ea6b2e15df2a433a/geometry/optimization/dev/test/collision_geometry_test.cc#L421)):*
> ```cpp
>   AddContactMaterial(0.1, 250.0, multibody::CoulombFriction<double>{0.9, 0.5},
>                      &proximity_properties);
>   // C-IRIS only considers robot kinematics, not dynamics. So we use an
> ```

Do we need these lines? Seems like copy-paste



_Code quote:_
```cpp
  ProximityProperties proximity_properties{};
  // C-IRIS doesn't care about robot dynamics. Use arbitrary material
  // properties.
  AddContactMaterial(0.1, 250.0, multibody::CoulombFriction<double>{0.9, 0.5},
                     &proximity_properties);
  // C-IRIS only considers robot kinematics, not dynamics. So we use an
  // arbitrary inertia.
  const multibody::SpatialInertia<double> spatial_inertia(
      1, Eigen::Vector3d::Zero(),
      multibody::UnitInertia<double>(0.01, 0.01, 0.01, 0, 0, 0));
```
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 516 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18475#-NJbk0Tv9iTfRqYNpxa8:-NJbk0Tv9iTfRqYNpxa9:bdxb9bv) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ebc11da8fe4e5da21d91d5ea6b2e15df2a433a/geometry/optimization/dev/test/collision_geometry_test.cc#L516)):*
> ```cpp
>     const double distance = DistanceToHalfspace(
>         box, a, b, expressed_body, PlaneSide::kNegative, *plant, plant_context);
>     // SceneGraphd doesn't support distance between box and halfspace yet.
> ```

nit: Typo in SceneGraph
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 545 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18475#-NJbk3l8-VN8cc-SZ1Wl:-NJbk3l8-VN8cc-SZ1Wm:blqn9qh) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ebc11da8fe4e5da21d91d5ea6b2e15df2a433a/geometry/optimization/dev/test/collision_geometry_test.cc#L545)):*
> ```cpp
>         DistanceToHalfspace(capsule, a, b, expressed_body, PlaneSide::kNegative,
>                             *plant, plant_context);
>     // SceneGraph doesn's support distance between capsule and halfspace yet.
> ```

nit: typo in doesn't

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18475)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 421 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18475#-NJbjjcIDAUoN4MEGceM:-NJcaxBq-rC9ZiJjA0kZ:b-9kx4v2) ([raw file](https://github.com/robotlocomotion/drake/blob/f2ebc11da8fe4e5da21d91d5ea6b2e15df2a433a/geometry/optimization/dev/test/collision_geometry_test.cc#L421)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Do we need these lines? Seems like copy-paste
</blockquote></details>

We do need to specify the contact materials and inertia property of the RigidBody, otherwise MultibodyPlant doesn't build.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18475#-:-NJeZhgU-ym0n-qkmj9d:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
