### PR TITLE
Update MATLAB code to support out-of-source builds.

### LINKED ISSUE #2808: Document the Locations of the "Build" and "Install" Directories
Prior to #2706, they were `drake-distro/pod-build` and `drake-distro/build`, respectively.

Post #2706, they are `drake-distro/build` and `drake-distro/build/install`, respectively.

### PR DESCRIPTION
**Pull request by david-german-tri**
Add search logic to the hand-coded addpath_drake.m for the common out-of-source build cases. This allows addpath_drake to work correctly from the source-tree side.  Update the generated addpath_drake wrapper to use the `CMAKE_INSTALL_PREFIX`.  Add regression test coverage.  Generalize other uses of the build directory throughout the MATLAB code base.

Resolves #2808.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2599)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Created this PR to launch CI.  Please don't review yet.

**Comment by Lucy-tri** [comment]
Thanks!  :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKnc7gzx6o_LOSEgddP:-279203903)*

**Comment by david-german-tri** [comment]
+@russtedrake for platform review.  I'm not 100% confident I'm preserving the intended semantics for the two `addpath_drake`s.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKnhtpHBZoY3jijQYkP:-1387176807)*

**Comment by RussTedrake** [comment]
this will break my current long-term workflow.  I've always started matlab in drake-distro/drake and called addpath_drake .  why the change?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKnuzdInaWuMu6rwQpp:-1232759871)*

**Comment by liangfok** [comment]
We are now supporting out-of-source builds: https://github.com/RobotLocomotion/drake/pull/2555
When building out of source, there's no longer a `pod-build` directory.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKnvOE_LTwU2SIoR1Y0:1974192200)*

**Comment by david-german-tri** [comment]
Thanks, @liangfok.  I'd phrase that a little more generally: the source tree and the build tree may be in arbitrary locations, so we can't have code in either tree that searches for the other.  We also have no way to record the location of the build tree in the source tree at compile time.  So, this PR takes the only remaining approach: record the location of the source tree in the build tree.

It would be better, long-term, not to reference the source tree at all.  We should copy all the MATLAB files into the build tree, and never run anything from `drake-distro`.  This is a step in that direction.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKnxxujmz1zgxpzeBKx:922893717)*

**Comment by RussTedrake** [comment]
We should NOT copy the matlab source files.  That option has been discussed many times and we have always agreed that it is fundamentally too prone to error.

**Comment by liangfok** [comment]
https://github.com/RobotLocomotion/drake/issues/2577 is related to this discussion. I just added a note in that issue indicating that MATLAB files should remain only in `drake-distro`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKo7_9-O85MdR3VegN0:1728224768)*

**Comment by david-german-tri** [comment]
Done.  @russtedrake, PTAL?  

Also +@liangfok for changes to documentation that you originally wrote.

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKsiIp8jqT5OSSKy9hY:1173766655)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKsk06QVTTulv0fZ6Nj:-1868698381)*

**Comment by Lucy-tri** [comment]
I have one comment but I won't hold this up. :lgtm: 

---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/addpath_drake.m, line 22 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KKt2-AMHI7Nih24HyfY:-KKt2-ANKKj08TuoGCbn:1939266477) ([raw file](https://github.com/robotlocomotion/drake/blob/7e7600e5c43710ebb0c9185573ee7ef28655ea4f/drake/addpath_drake.m#L22)):*
> ```objc
>       break;
>     end
>     out_of_source_path = fullfile(root, pfx, 'drake-build', 'drake', 'matlab');
> ```

I don't think you can count on the drake-build dir being named 'drake-build'.  People might create build1, build2, ....  At least add this assumption to the error message: that it's looking in drake-build for out of source builds. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKt4c9pqIGK0sFdUyTN:1780045340)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/addpath_drake.m, line 22 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KKt2-AMHI7Nih24HyfY:-KKt5Kv0n8eyQcwzHvow:-539699127) ([raw file](https://github.com/robotlocomotion/drake/blob/7e7600e5c43710ebb0c9185573ee7ef28655ea4f/drake/addpath_drake.m#L22)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> I don't think you can count on the drake-build dir being named 'drake-build'.  People might create build1, build2, ....  At least add this assumption to the error message: that it's looking in drake-build for out of source builds. 
</details>
I guess the best design would be to make the `drake-build` directory name be an optional input parameter into the `add path_drake()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KKxc-l7jMTOEWkbKvWG:1417088721)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/addpath_drake.m, line 22 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KKt2-AMHI7Nih24HyfY:-KKxh1tfAIVov9UvmpUC:99200087) ([raw file](https://github.com/robotlocomotion/drake/blob/7e7600e5c43710ebb0c9185573ee7ef28655ea4f/drake/addpath_drake.m#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I guess the best design would be to make the `drake-build` directory name be an optional input parameter into the `add path_drake()`.
</details>
https://github.com/RobotLocomotion/drake/issues/2627

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by david-german-tri** [comment]
@russtedrake, I think this is ready for another look from you.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/addpath_drake.m, line 22 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KKt2-AMHI7Nih24HyfY:-KKu49Pb5ug3XLPfGHEJ:729210010) ([raw file](https://github.com/robotlocomotion/drake/blob/7e7600e5c43710ebb0c9185573ee7ef28655ea4f/drake/addpath_drake.m#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I guess the best design would be to make the `drake-build` directory name be an optional input parameter into the `add path_drake()`.
</details>
Improved the error message, PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KLIkUTCoo6DuXGaRIal:885052192)*

**Comment by liangfok** [comment]
I left one non-blocking comment.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/addpath_drake.m, line 22 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KKt2-AMHI7Nih24HyfY:-KLImQyydjwxSz37Rypl:-1880230122) ([raw file](https://github.com/robotlocomotion/drake/blob/7e7600e5c43710ebb0c9185573ee7ef28655ea4f/drake/addpath_drake.m#L22)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Improved the error message, PTAL.
</details>
I left a minor comment.

---

*[drake/addpath_drake.m, line 37 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLImjLjTn2Q3jN4ljpq:-KLImjLjTn2Q3jN4ljpr:900841160) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L37)):*
> ```objc
>   error(['The Drake build outputs are not on the MATLAB path, and could ' ...
>          'not be auto-detected. Please add the build output directory ' ...
>          '"matlab" to the path, then re-run addpath_drake.']);
> ```

BTW, I'm not sure how to modify the MATLAB path, especially from within a terminal (no GUI). Should we include a link to this page?

http://www.mathworks.com/help/matlab/matlab_env/what-is-the-matlab-search-path.html

Do I set the MATLAB path by modifying `pathdef.m`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KLInAA5qsfCu79V71YE:-1488946973)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by sherm1** [comment]
Waiting for @RussTedrake's platform review.

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/addpath_drake.m, line 14 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVALNyjZtSrJtX46FK:-KLVALNzJLp8KV5gFrby:-1393014377) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L14)):*
> ```objc
> % already on the MATLAB path, so we need to find them first.
> % Search four directories up for the build directory. It will typically be
> % in ./build/matlab for in-source builds with Make, or 
> ```

should be ../build/matlab, and ../../drake-build/matlab, no?

---

*[drake/addpath_drake.m, line 37 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLImjLjTn2Q3jN4ljpq:-KLVAdV3EmmRQyQcaz0f:1830733048) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I'm not sure how to modify the MATLAB path, especially from within a terminal (no GUI). Should we include a link to this page?
> 
> http://www.mathworks.com/help/matlab/matlab_env/what-is-the-matlab-search-path.html
> 
> Do I set the MATLAB path by modifying `pathdef.m`?
</details>
i think people have multiple options for setting their matlab path, and we should not force any one of them.  (e.g. opening the pathtool gui and using the save button).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source.rst, line 100 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVrNTsqBmol4mffbIy:-KLVrNTtyUt1eeQiOjdl:-1412689561) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/doc/from_source.rst#L100)):*
> ```reStructuredText
> Drake uses `CMake <https://cmake.org/>`_ to generate Ninja files within an
> out-of-source build directory. You should name this directory ``drake-build``,
> and it should be a sibling of ``drake-distro``.
> ```

i actually really don't like this.  i'm willing to discuss, but i think that drake-distro/build is sufficiently out of source, and we should instruct people to make that directory instead.  that feels much cleaner to me, and has the additional advantage to being consistent with all of our current workflows (which other drake consumers depend on)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source.rst, line 100 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVrNTsqBmol4mffbIy:-KLVwK2jIarNOfage7Ob:1986304535) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/doc/from_source.rst#L100)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i actually really don't like this.  i'm willing to discuss, but i think that drake-distro/build is sufficiently out of source, and we should instruct people to make that directory instead.  that feels much cleaner to me, and has the additional advantage to being consistent with all of our current workflows (which other drake consumers depend on)
</details>
I will double check before updating the documentation but I believe this could be as simple as updating the build instructions:

```
$ cd drake-distro
$ mkdir build
$ cd build
$ ccmake ../ -G Ninja
$ ninja -j1
```

Eventually, we'll want to be able to completely delete all build artifacts by deleting the build directory wherever it may be located.

I created https://github.com/RobotLocomotion/drake/issues/2706 to track this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source.rst, line 100 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVrNTsqBmol4mffbIy:-KLWtyBdzF-_IQ3XZtgo:1472758442) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/doc/from_source.rst#L100)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I will double check before updating the documentation but I believe this could be as simple as updating the build instructions:
> 
> ```
> $ cd drake-distro
> $ mkdir build
> $ cd build
> $ ccmake ../ -G Ninja
> $ ninja -j1
> ```
> 
> Eventually, we'll want to be able to completely delete all build artifacts by deleting the build directory wherever it may be located.
> 
> I created https://github.com/RobotLocomotion/drake/issues/2706 to track this change.
</details>
I think this is a good recommendation but I hope it won't be a requirement. Because the build contents are ephemeral artifacts I usually keep mine far away for easy wiping and to simplify steering my backup software away from them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/from_source.rst, line 100 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVrNTsqBmol4mffbIy:-KLX5DoOpd402dQyDhre:-616677934) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/doc/from_source.rst#L100)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I think this is a good recommendation but I hope it won't be a requirement. Because the build contents are ephemeral artifacts I usually keep mine far away for easy wiping and to simplify steering my backup software away from them.
</details>
agreed on both.  (the logic david included will provide the notification if you put it in a non-recommended location).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by RussTedrake** [comment]
added my comments below

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KLYpm2FmI70Nyz_AwuE:-1233330636)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/addpath_drake.m, line 14 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVALNyjZtSrJtX46FK:-KMLxtTm5up2R3VqXFnn:1151769597) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L14)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> should be ../build/matlab, and ../../drake-build/matlab, no?
</details>
fwiw - i believe this was addressed in a separate PR by @liangfok 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/addpath_drake.m, line 14 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVALNyjZtSrJtX46FK:-KMPJ4l2VwfvVMFMrguV:1545888862) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L14)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> fwiw - i believe this was addressed in a separate PR by @liangfok 
</details>
[Officially](http://drake.mit.edu/from_source.html#build-with-make), all build artifacts should go in `drake-distro/build`. Thus, the above comment should be updated to state `drake-distro/build/drake/Matlab`. This should be true for both Make and Ninja-based builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KMPWEp-OPmqvkdT2Pw-:1417088721)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/addpath_drake.m, line 14 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVALNyjZtSrJtX46FK:-KMQiXGRwh4GVHFRC1rb:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> [Officially](http://drake.mit.edu/from_source.html#build-with-make), all build artifacts should go in `drake-distro/build`. Thus, the above comment should be updated to state `drake-distro/build/drake/Matlab`. This should be true for both Make and Ninja-based builds.
</details>
Done.

---

*[drake/addpath_drake.m, line 37 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLImjLjTn2Q3jN4ljpq:-KMPAQ44ND2DzzFKzg5L:-1442921832) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/addpath_drake.m#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i think people have multiple options for setting their matlab path, and we should not force any one of them.  (e.g. opening the pathtool gui and using the save button).
</details>
I agree with @russtedrake.  Closing this thread.

---

*[drake/doc/from_source.rst, line 100 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KLVrNTsqBmol4mffbIy:-KMQijb4PmxcRJ8tDAaG:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0324475cfb2d20a3fe38c99a1b19a923e76b2020/drake/doc/from_source.rst#L100)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> agreed on both.  (the logic david included will provide the notification if you put it in a non-recommended location).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 2 of 3 files at r5, 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KMQkFwxxt_dxxyCYQ56:-1868698381)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by david-german-tri** [comment]
@russtedrake, anything else needed here?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KMUCgHpAbcFNlmo_w7Y:-1344919201)*

**Comment by RussTedrake** [comment]
this does NOT work.  to see the failure, in matlab, cd into drake-distro/drake, then run
```
addpath_drake
addpath_spotless
```
the second line will fail.
we need to add build/install/matlab to the path, not build/drake/matlab

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KMi-6fTbChvM6sujqB8:-546955796)*

**Comment by RussTedrake** [comment]
note that util/getCMakeParam will also be broken now.  

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KMi3zKxuJ0Zjyse41Ow:754048220)*

**Comment by liangfok** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KMiFHSllPs1KG_k8N1o:502544406)*

**Comment by david-german-tri** [comment]
Fixed `addpath_spotless`, and added a regression test.  

I'll address `getCMakeParam` and other hardwired uses of pod-build in a separate PR.

**Comment by Lucy-tri** [comment]
Reviewed 2 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by david-german-tri** [comment]
Actually, I've moved the other MATLAB hardwired uses of `pod-build` into this PR.  They're closely related, and it's still a small change.

**Comment by Lucy-tri** [comment]
Reviewed 6 of 6 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r9, 6 of 6 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/addpath_drake.m, line 91 \[r10\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KMuSPLKWBW7U0_Th_Gc:-KMuSPLLXjJU-vgqoAyQ:-336183653) ([raw file](https://github.com/robotlocomotion/drake/blob/cd02b0d3d1f7849e4c46f459b189106bb6d08eac/drake/addpath_drake.m#L91)):*
> ```objc
> 
> if ispc
>   setenv('PATH',[getenv('PATH'),';',GetFullPath(pods_get_lib_path),';',fullfile(get_drake_binary_dir(),'lib','Release'),';',fullfile(get_drake_binary_dir(),'lib')]);
> ```

OK  .  not necessarily required on this PR, but we should improve this logic.  the 'Release' is only relevant for Release builds, and the lib (without an extension) is probably doing nothing (on PC) at this point.  adding a get_drake_lib_dir() might be the right solution?

---

*[drake/addpath_drake.m, line 91 \[r10\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KMuTJ3h3t1JJ-3LFho9:-KMuTJ3h3t1JJ-3LFhoA:1351669906) ([raw file](https://github.com/robotlocomotion/drake/blob/cd02b0d3d1f7849e4c46f459b189106bb6d08eac/drake/addpath_drake.m#L91)):*
> ```objc
> 
> if ispc
>   setenv('PATH',[getenv('PATH'),';',GetFullPath(pods_get_lib_path),';',fullfile(get_drake_binary_dir(),'lib','Release'),';',fullfile(get_drake_binary_dir(),'lib')]);
> ```

I think for this instance we might get away with (and be better served by) using install dir instead of binary dir?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by david-german-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/addpath_drake.m, line 91 \[r10\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-KMuTJ3h3t1JJ-3LFho9:-KMzTtGNiIYnRwcqYrNt:1991983475) ([raw file](https://github.com/robotlocomotion/drake/blob/cd02b0d3d1f7849e4c46f459b189106bb6d08eac/drake/addpath_drake.m#L91)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> I think for this instance we might get away with (and be better served by) using install dir instead of binary dir?
</details>
Done.  (`diff` suggests the two are fairly different, and I don't really know what this is used for, so I've launched a Windows MATLAB run in CI: https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-64-experimental-matlab/26/)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599)*

**Comment by RussTedrake** [comment]
can you create an issue for the hard-coded "Release" in addpath_drake if you haven't already?  :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2599#-:-KN7ESQegw-Jpb7azqPh:2025234279)*

**Comment by david-german-tri** [comment]
> can you create an issue for the hard-coded "Release" in addpath_drake if you haven't already?

#2850

**Comment by jamiesnape** [comment]
Looks like this broke Windows builds. Maybe OS X too, but less likely.

**Pull request merged**
