### PR TITLE
Adds a README for the kuka_iiwa_arm/controlled_kuka/ demo.

### PR DESCRIPTION
**Pull request by liangfok**
It's a best practice to include a README with each demo that's version controlled along with the demo.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3691)

### CODE REVIEW

**Comment by liangfok** [comment]
+@mrhebert for feature review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3691#-:-KTLOFwrrr7kTG3kni9F:brgarng)*

**Comment by mrhebert** [comment]
Instructions worked for me on fresh drake-distro. Good start. I will add to readme as I become more familiar with the demo.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3691#-:-KTLT2QTlCLxNhomG79f:b-xht0e1)*

**Comment by mrhebert** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3691#-:-KTLTUgPBVWS3oOwhkna:bnfp4nl)*

**Comment by liangfok** [comment]
@mrhebert: Thanks!

+@sammy-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3691#-:-KTLTWbl-viSmdpuod5y:b6wjpti)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3691#-:-KTLToKyqUP8UMtl7jSW:bnfp4nl)*

**Pull request merged**
