### PR TITLE
Make CalcCenterOfMassPositionInWorld() and CalcCenterOfMassTranslationalVelocityInWorld() consistent with CalcTotalMass().

### PR DESCRIPTION
**Pull request by mitiguy**
Resolve issue #14997.  Update CalcCenterOfMassPositionInWorld() and Make CalcCenterOfMassPositionInWorld() and CalcCenterOfMassTranslationalVelocityInWorld() so their calculations are consistent with the calculations in CalcTotalMass().

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@joemasterjohn 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054#-:-M_zqbPBBK-_yUlWIHXu:bd6d1k1)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a few small suggestions. +@sammy-tri for platform, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054#-:-Ma453DE5dAgFyjMoxFz:bgzyoqs)* status: 10 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn, @mitiguy, and @sammy-tri)

___
*[multibody/plant/test/multibody_plant_com_test.cc, line 243 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma0DwSk5DeJcKmL9EIr:-Ma0DwSk5DeJcKmL9EIs:b3jmx0k) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/plant/test/multibody_plant_com_test.cc#L243)):*
> ```cpp
>       "bodies specified. You must provide at least one selected body.");
> 
>   // Ensure an exception is thrown when a model instance has one world body.
> ```

nit: update this comment to something like "Ensure an exception is thrown when 
___
*[multibody/tree/multibody_tree.cc, line 1308 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma0EuXREOb61PLc2w1o:-Ma0EuXREOb61PLc2w1p:b-wwddo1) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1308)):*
> ```cpp
>   // Reminder: MultibodyTree always declares a world body and 2 model instances
>   // "world" and "default" so num_model_instances() should always be >= 2.
>   if (num_bodies() <= 1 || num_model_instances() <= 1) {
> ```

Per your comment above `num_model_instances() <= 1` is always false and shouldn't be a part of the condition.
Since the default model instance always exists (and thus bodies may exist as part of it), there is no way to tell by the number of model instances in the plant whether the plant has non-zero mass. 
___
*[multibody/tree/multibody_tree.cc, line 1310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma44o9S-c7Ea20bh6YA:-Ma44o9S-c7Ea20bh6YB:b-rxdg71) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1310)):*
> ```cpp
>   if (num_bodies() <= 1 || num_model_instances() <= 1) {
>     throw std::logic_error(
>         "CalcCenterOfMassPositionInWorld(): This MultibodyPlant contains "
> ```

nit: consider updating these error messages to use the nice `fmt::format` with `__func__` that you have in the error messages below.
___
*[multibody/tree/multibody_tree.cc, line 1318 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma0G_2AAoUpNoNgH84o:-Ma0G_2AAoUpNoNgH84p:b2e08v0) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1318)):*
> ```cpp
> 
>   // Sum over all the bodies that are in model_instances except for the 0th body
>   // (which is the world body).  It is a upstream user error for the same body
> ```

It is impossible for a body (or any `MultibodyElement`) to belong to multiple model instances. It's only model instance is the one returned by `Body::model_instance()`. The problem this loop avoids though is counting bodies from duplicate model instances passed in, because we aren't checking for that. We should update this comment accordingly.
___
*[multibody/tree/multibody_tree.cc, line 1341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma3z-ER8M2DyaIXJgmK:-Ma3z-ER8M2DyaIXJgmL:b-64o0ac) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1341)):*
> ```cpp
>     throw std::logic_error(
>         "CalcCenterOfMassPositionInWorld(): There were no bodies specified. "
>         "You must provide at least one selected body.");
> ```

nit: I think instead of "You must provide at least one selected body." we could be more specific and say "The set of all bodies belonging to the input model_instances must be non-empty."
___
*[multibody/tree/multibody_tree.cc, line 1346 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma3zXYP7wkTJgga8WmD:-Ma3zXYP7wkTJgga8WmE:byovze5) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1346)):*
> ```cpp
>   if (total_mass <= 0) {
>     throw std::logic_error("CalcCenterOfMassPositionInWorld(): The "
>                            "system's total mass must be greater than zero.");
> ```

nit: Probably just a copy paste error from the full system version. Here the system's mass may or may not be non-zero, but the mass of the subset of bodies belonging to model_instances definitely is zero. This error message might "lie" to the user ;)
___
*[multibody/tree/multibody_tree.cc, line 1387 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma4037G17-wTGV5aknz:-Ma4037G17-wTGV5ako-:bnfmzh3) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1387)):*
> ```cpp
>   // world frame W is calculated as v_WScm_W = ∑ (mᵢ vᵢ)  / mₛ, where mₛ = ∑ mᵢ,
>   // mᵢ is the mass of the  iᵗʰ body, and vᵢ is Bcm's velocity in world frame W
>   // (Bcm is the center of mass of the iᵗʰ body).
> ```

nit: This is a very nice comment, but it seems like it belongs in the method documentation rather than buried in the implementation.
___
*[multibody/tree/multibody_tree.cc, line 1397 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma40jCTCm2fXd69TUQK:-Ma40jCUDs3N6wAhgsxc:b-p9adw1) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1397)):*
> ```cpp
>   // Reminder: MultibodyTree always declares a world body and 2 model instances
>   // "world" and "default" so num_model_instances() should always be >= 2.
>   if (num_bodies() <= 1 || num_model_instances() <= 1) {
> ```

ditto here, nix the `num_model_instances() <= 1`
___
*[multibody/tree/multibody_tree.cc, line 1407 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma425CpAWJy3OtHRRxN:-Ma425CpAWJy3OtHRRxO:b6lcphm) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1407)):*
> ```cpp
> 
>   // Sum over all the bodies that are in model_instances except for the 0th body
>   // (which is the world body).  It is a upstream user error for the same body
> ```

ditto here with the comment about the body appearing in multiple model instances. 
___
*[multibody/tree/multibody_tree.cc, line 1410 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma42K7MARfKYALKyWGw:-Ma42K7MARfKYALKyWGx:bdle0w7) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1410)):*
> ```cpp
>   // to appear in multiple model_instances, so count each body only once.
>   int number_of_non_world_bodies_processed = 0;
>   for (BodyIndex body_index(1); body_index < num_bodies(); ++body_index) {
> ```

nit: you switch between using {} and () for these body indices. In this situation I don't think there are big implications from using either, but I would stick to one.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054)* status: 11 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/tree/multibody_tree.cc, line 1309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma53bKAE9j6wElz8O7f:-Ma53bKAE9j6wElz8O7g:b-dq1den) ([raw file](https://github.com/robotlocomotion/drake/blob/f369e75226b8135ad603ab4f42279e9969740fa8/multibody/tree/multibody_tree.cc#L1309)):*
> ```cpp
> Vector3<T> MultibodyTree<T>::CalcCenterOfMassPositionInWorld(
>     const systems::Context<T>& context,
>     const std::vector<BodyIndex>& body_indexes) const {
> ```

It looks like this PR deletes the overload which accepted `body_indexes`.  It should also be removed from `multibody_tree.h`.

**Review by sammy-tri — COMMENTED** [review]
No issues from me, waiting on feature review to confirm that the remaining issues are resolved.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054#-:-Ma9ddNr2GA_dZ0KSnPx:bw17m0n)* status: 10 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/tree/multibody_tree.cc, line 1309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma53bKAE9j6wElz8O7f:-Ma9dHYi5yudyDdk7zti:b9j8q79) ([raw file](https://github.com/robotlocomotion/drake/blob/f369e75226b8135ad603ab4f42279e9969740fa8/multibody/tree/multibody_tree.cc#L1309)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It looks like this PR deletes the overload which accepted `body_indexes`.  It should also be removed from `multibody_tree.h`.
</blockquote></details>

Ok, it looks like this is done now.

**Review by joemasterjohn — COMMENTED** [review]
All of my issues have been resolved with the last commit. Looks good on my end.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054#-:-Ma9itP11qzY9bD3xUYd:bgqqin2)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

___
*[multibody/plant/test/multibody_plant_com_test.cc, line 243 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma0DwSk5DeJcKmL9EIr:-Ma6olJ5ECwgDMlAUWq0:b52k3bq) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/plant/test/multibody_plant_com_test.cc#L243)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: update this comment to something like "Ensure an exception is thrown when 
</blockquote></details>

Joe -- Perhaps you had more to say here ?
___
*[multibody/tree/multibody_tree.cc, line 1308 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma0EuXREOb61PLc2w1o:-Ma6o_YC0yJzWr2M8Omu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1308)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Per your comment above `num_model_instances() <= 1` is always false and shouldn't be a part of the condition.
Since the default model instance always exists (and thus bodies may exist as part of it), there is no way to tell by the number of model instances in the plant whether the plant has non-zero mass. 
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 1309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma53bKAE9j6wElz8O7f:-Ma6oJYb13QJjy1fPmOD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f369e75226b8135ad603ab4f42279e9969740fa8/multibody/tree/multibody_tree.cc#L1309)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It looks like this PR deletes the overload which accepted `body_indexes`.  It should also be removed from `multibody_tree.h`.
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 1310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma44o9S-c7Ea20bh6YA:-Ma950W7EEirgLT_PZU0:b-hn96vl) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1310)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: consider updating these error messages to use the nice `fmt::format` with `__func__` that you have in the error messages below.
</blockquote></details>

Done.  Good catch Joe.
___
*[multibody/tree/multibody_tree.cc, line 1318 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma0G_2AAoUpNoNgH84o:-Ma98a4Q2W5L8ER_K6H1:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1318)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

It is impossible for a body (or any `MultibodyElement`) to belong to multiple model instances. It's only model instance is the one returned by `Body::model_instance()`. The problem this loop avoids though is counting bodies from duplicate model instances passed in, because we aren't checking for that. We should update this comment accordingly.
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 1341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma3z-ER8M2DyaIXJgmK:-Ma9B30X0FEjZZzeK0JQ:bgdwt7g) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1341)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I think instead of "You must provide at least one selected body." we could be more specific and say "The set of all bodies belonging to the input model_instances must be non-empty."
</blockquote></details>

Done, with slightly different wording.
___
*[multibody/tree/multibody_tree.cc, line 1346 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma3zXYP7wkTJgga8WmD:-Ma9BaEV1f_2_MQxFS0Z:bqp4uo2) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1346)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Probably just a copy paste error from the full system version. Here the system's mass may or may not be non-zero, but the mass of the subset of bodies belonging to model_instances definitely is zero. This error message might "lie" to the user ;)
</blockquote></details>

The word "system" is defined in the public API as the set of bodies contained in the input argument.  Hoping that this is not a "lie" -- a sub-system is a system.
___
*[multibody/tree/multibody_tree.cc, line 1387 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma4037G17-wTGV5aknz:-Ma9Lp0Z-goJNaieHcV9:b-xlugg2) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1387)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: This is a very nice comment, but it seems like it belongs in the method documentation rather than buried in the implementation.
</blockquote></details>

Done.  And updated documentation to make it more consistent.
___
*[multibody/tree/multibody_tree.cc, line 1397 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma40jCTCm2fXd69TUQK:-Ma9Lsl-7MV7yqngzcLs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1397)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

ditto here, nix the `num_model_instances() <= 1`
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 1407 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma425CpAWJy3OtHRRxN:-Ma9LyFa05oRD5MQxSVR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1407)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

ditto here with the comment about the body appearing in multiple model instances. 
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 1410 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15054#-Ma42K7MARfKYALKyWGw:-Ma9MYaWEX83PjEL5CH4:b9446bl) ([raw file](https://github.com/robotlocomotion/drake/blob/2bb509b59f9b9ddd8a53724f54166a8afa620152/multibody/tree/multibody_tree.cc#L1410)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: you switch between using {} and () for these body indices. In this situation I don't think there are big implications from using either, but I would stick to one.
</blockquote></details>

Done.  Made this self-consistent in related methods.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15054#-:-Ma9vKPVD7gXiA47vZFj:by1pdfu)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn (waiting on @mitiguy)

**Pull request merged**
