### PR TITLE
Prepare for Eigen 3.4

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
In Eigen 3.4, implicit conversion from TypeSafeIndex to int may fail.
When needed, use the int constructor explicitly.

Working towards #14968

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335#-:-Me1p9T83b0ivNDXnUUJ:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature from the perspective of the Eigen transition, and platform.

Let's also have +@SeanCurtis-TRI as second reviewer, as the subject matter expert for TypeSafeIndex.  The question here is whether we accept the new Eigen reality that we'll need to guide Eigen at our call sites when we use a TypeSafeIndex as a Matrix index, or whether we open a tracking issue to try to add more template magic so that implicit conversions will again start happen automatically.  My thought so far is that with the relatively low preponderance of tweaks needed as shown in this PR, it's sufficient to use the `int{}` work-around.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335#-:-Me1pf2K9v2jTFaL1sWu:b-9a49gx)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @BetsyMcPhail and @SeanCurtis-TRI)

___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15335#-Me1q29L2JZGrMArPYP5:-Me1q29L2JZGrMArPYP6:bx6zss8) ([raw file](https://github.com/robotlocomotion/drake/blob/d725d796d8c6f49a07cc088210d7be6129906410/multibody/fixed_fem/dev/test/stretch_test.cc#L104)):*
> ```cpp
>         bc->AddBoundaryCondition(y_dof_index,
>                                  Vector1<T>(
>                                    kStretchFactor * q(int{y_dof_index})));
> ```

nit Per GSG, the indentation is +4 for nested expressions, we need +2 more here.  If that pushes it >80, we'll need to reflow the argument(s) onto the next line.

https://drake.mit.edu/styleguide/cppguide.html#Function_Calls
___
*[multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15335#-Me1pq6CEp1Vrg3oEdf2:-Me1pq6CEp1Vrg3oEdf3:bdzn1el) ([raw file](https://github.com/robotlocomotion/drake/blob/d725d796d8c6f49a07cc088210d7be6129906410/multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc#L81)):*
> ```cpp
>     // The reconstructed posture should be within the user specified bound.
>     EXPECT_NEAR(q_global_ik(
>                 int{plant_->GetJointByName("iiwa_joint_2").index()}),
> ```

nit Per GSG nested expressions use +4 indentation when they span into a new line.  (Indent this line by +4).

**Comment by jwnimmer-tri** [comment]
Also I guess \CC @xuchenhan-tri for any input, since >50% of the changes are in `fixed_fem`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
My primary concern is the [documented intent](https://github.com/RobotLocomotion/drake/blob/master/common/type_safe_index.h#L39-L40) of the `TypeSafeIndex`:

By design, `TypeSafeIndex` is-a `int`. It seems very dissatisfying for that not be true. In an ideal world, these call sites should still work. If, however, we decide that it's an `int` for all purpose except for Eigen matrix indexing, then we should capture that in the documentation.

I would personally prefer to special case the implementation than special case the usage. The former affects a single developer and a small unit test, the latter affects everyone who attempts to combine `TypeSafeIndex` with `Eigen` (although, as @jwnimmer-tri has pointed out, so far that hasn't been many people).

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335#-:-Me5OJMJ9pUxVIpppMib:bkhu4ha)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI To confirm, then a viable work plan in your eye could be like so?

(1) Open an issue that tracks our follow up -- to dig into the templates or overloads and figure out what's wrong with Drake or Eigen; and then, once we find a better fix, to remind us to revert this patch (and any new siblings it spawned).  These should be easy enough to grep for.

(2) In this PR, improve the TypeSafeIndex API documentation to mention / demonstrate this work-around in light of Eigen 3.4.  Cite the issue.

(3) Land this PR.

**Review by SeanCurtis-TRI — COMMENTED** [review]
An excellent distillation. I'd sign off on all of that.

:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335#-:-Me5U_tO0-WVN5RggsMb:bos8958)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335)* status: 1 unresolved discussion (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15335#-Me5kHlb1BHl3vN4Ycam:-Me5kHlc9BmenhaqrpDt:b9pzz1p) (no related file):*
Per the main thread discussion, we need a change here to `type_safe_index.h` that explains this caveat.  Filing that as a blocking comment here for now, to prevent merge.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15335#-Me5kHlb1BHl3vN4Ycam:-MeB0Kp79JWJueW9wHBm:b-bum5ts) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Per the main thread discussion, we need a change here to `type_safe_index.h` that explains this caveat.  Filing that as a blocking comment here for now, to prevent merge.
</blockquote></details>

@SeanCurtis-TRI please take another look at the new Doxygen text.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15335)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Pull request merged**
