### PR TITLE
Use non-POD bullet

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3327.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3417)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Toward #3327.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
More `rpath` issues.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please

otherwise :lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3417#-:-KR_CPrjAyDpwML-JnrR:bxoj19y)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3417)*

**Comment by jamiesnape** [comment]
CDash upload failed on Windows. Build passed otherwise.

**Pull request merged**
