### PR TITLE
doc: Refactor main Jekyll site builder to use common code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14803. (That PR contains more example uses of the `defs.py` common helpers, as well as new [documentation_instructions](https://github.com/jwnimmer-tri/drake/blob/doc-mv-sphinx/doc/_pages/documentation_instructions.md) that show the overall UX goal.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/_config.yml, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWjTmZk6elZbgHWBCYJ:-MWjTmZl-cpTJ8pbSnmG:b2uz6mt) ([raw file](https://github.com/robotlocomotion/drake/blob/608bab0c0a37c0dcd7ee23e4a771206cf145de7b/doc/_config.yml#L88)):*
> ```YAML
>       layout: "release"
> 
> exclude:
> ```

FYI Given the new `symlink_input` sandboxing, we don't need to exclude stray files from Jekyll anymore.
___
*[doc/BUILD.bazel, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWjUAYr9byg3EgSazGd:-MWjUAYr9byg3EgSazGe:b-bzctiz) ([raw file](https://github.com/robotlocomotion/drake/blob/608bab0c0a37c0dcd7ee23e4a771206cf145de7b/doc/BUILD.bazel#L9)):*
> ```Starlark
>     "drake_py_binary",
>     "drake_py_library",
>     "drake_py_unittest",
> ```

FYI This is cleanup from prior changes -- unittest was already unused.
___
*[doc/BUILD.bazel, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWjU4Sw3h-L3HODYeZc:-MWjU4Sw3h-L3HODYeZd:b-ida0nn) ([raw file](https://github.com/robotlocomotion/drake/blob/608bab0c0a37c0dcd7ee23e4a771206cf145de7b/doc/BUILD.bazel#L172)):*
> ```Starlark
> 
> add_lint_tests(
>     python_lint_exclude = [
> ```

FYI This is cleanup from prior changes -- conf.py was already gone.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri could I ask you to feature review this (as someone who has worked with Jekyll pages for the website transition, but hasn't yet seen the reusable-main library)?  Low priority, if you have time this week.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833#-:-MWzO5S6DTjaUX7Ms7vo:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/pages.py, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWzNyVXEc39X5acN7w9:-MWzNyVXEc39X5acN7wA:b-wcnaz8) ([raw file](https://github.com/robotlocomotion/drake/blob/e4f1af6274a1c21ee7400d4ae47aa4dc50be2e72/doc/pages.py#L29)):*
> ```Python
>     ])
> 
>     # The nominal pages to offer for preview.
> ```

minor:  This is a somewhat baffling comment on an ignored return value.
___
*[doc/_pages/documentation_instructions.md, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWyhqsH00e2F2g1-Wuc:-MWyhqsH00e2F2g1-Wud:b-byt9t8) ([raw file](https://github.com/robotlocomotion/drake/blob/5019f101416a4519d1784b5d9ab23e91e675a63c/doc/_pages/documentation_instructions.md#L28)):*
> ```Markdown
> # Drake's main website
> 
> To preview changes locally at ``http://127.0.0.1:<n>``:
> ```

minor:  Why not just correct the port to 8000 rather than remove the URL?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[doc/pages.py, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWzNyVXEc39X5acN7w9:-MWzT1reA_mmcnU92zWt:bfhr86v) ([raw file](https://github.com/robotlocomotion/drake/blob/e4f1af6274a1c21ee7400d4ae47aa4dc50be2e72/doc/pages.py#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This is a somewhat baffling comment on an ignored return value.
</blockquote></details>

This value is not ignored, though?

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel run //doc:pages -- --serve
...
Generating documentation preview ...
The files have temporarily been generated into /tmp/doc_builder_preview_yk_o9qpg

Serving at the following URLs for local preview:

  http://127.0.0.1:8000/

Use Ctrl-C to exit.
```

If I change the `""` here to  `"index.html"`, for example, then console output looks like:

```console
  http://127.0.0.1:8000/index.html
```
___
*[doc/_pages/documentation_instructions.md, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWyhqsH00e2F2g1-Wuc:-MWzSo5n0Ijpny5TpFYT:byla7wq) ([raw file](https://github.com/robotlocomotion/drake/blob/5019f101416a4519d1784b5d9ab23e91e675a63c/doc/_pages/documentation_instructions.md#L28)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Why not just correct the port to 8000 rather than remove the URL?
</blockquote></details>

When run locally, the preview tool prints out the relevant URLs to the console, for the user to click on.  Repeating the information here seemed useless and brittle?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/pages.py, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWzNyVXEc39X5acN7w9:-MWzUzFe2z8cSUwCZ8_P:b-9l0l41) ([raw file](https://github.com/robotlocomotion/drake/blob/e4f1af6274a1c21ee7400d4ae47aa4dc50be2e72/doc/pages.py#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This value is not ignored, though?

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel run //doc:pages -- --serve
...
Generating documentation preview ...
The files have temporarily been generated into /tmp/doc_builder_preview_yk_o9qpg

Serving at the following URLs for local preview:

  http://127.0.0.1:8000/

Use Ctrl-C to exit.
```

If I change the `""` here to  `"index.html"`, for example, then console output looks like:

```console
  http://127.0.0.1:8000/index.html
```
</blockquote></details>

Ah, I misinterpreted the main call.  Quite right.
Still not sure what a nominal page is, but the behaviour is reasonable.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833)* status: needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[doc/pages.py, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MWzNyVXEc39X5acN7w9:-MWzr_jq92MbgXqlLZok:bkgrgvf) ([raw file](https://github.com/robotlocomotion/drake/blob/e4f1af6274a1c21ee7400d4ae47aa4dc50be2e72/doc/pages.py#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Ah, I misinterpreted the main call.  Quite right.
Still not sure what a nominal page is, but the behaviour is reasonable.
</blockquote></details>

OK I reworded the comment.  The idea was that the preview site has a few dozen pages, but we want to choose some nominal subset of starting point(s) here to present on the console.  (For example, we could add "developers.html" here so save a click in navigating from that page, instead of needing to use the hamburger menu.)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[doc/styleguide/build.py, line 58 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14833#-MX2CxEU5NRkHDihJ71f:-MX2CxEV2amDiswheyjM:bfrpc7d) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/doc/styleguide/build.py#L58)):*
> ```Python
>     ])
> 
>     # The nominal pages to offer for preview.
> ```

FYI:  Oh, *that's* where nominal was defined!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: (with much faith in the author and feature reviewer!)

> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14833#-:-MX3Le74-bwki6ygzBvN:bndie3i)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
