### PR TITLE
Update snopt submodule SHA

### PR DESCRIPTION
**Pull request by jamiesnape**
Integrates RobotLocomotion/snopt#11 which allows for calling `find_package(snopt)` to import both the `snopt_c` and `snopt_cpp` targets. For Drake, which only uses `snopt_c` at present, it has the primary advantage of fitting all the naming conventions and allowing `drake_find_package` to work without major editing of MATLAB code.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3941)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental  please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-cpplint-experimentalplease

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-cpplint-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-cdash-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
161 non-MATLAB tests, 517 MATLAB tests.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-KV__QysA-h2YRaARkPD:-KV__QywSPU7PEnPOlVr:b-2k8x3) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d285ff1b90a320e8a8ace3af545473387ea33c/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L15)):*
> ```CMake
>   # find a solution.  See
>   # https://github.com/RobotLocomotion/drake/issues/3710
>   if(snopt_FOUND OR ipopt_FOUND)
> ```

How is `snopt_FOUND` set in this context? I wonder if we should find it somewhere higher up rather than finding it many times?

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-KV__w8w5ihfS4cxpGqs:-KV__w8zQNMJAJ0Mhrrk:b-80wp0l) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d285ff1b90a320e8a8ace3af545473387ea33c/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
> ```CMake
>   drakeSide)
> 
> if(snopt_FOUND)
> ```

Same question

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3941)*

**Comment by jamiesnape** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-KV__QysA-h2YRaARkPD:-KV_b9eiR0gRgW17P7r2:b-3yzwxn) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d285ff1b90a320e8a8ace3af545473387ea33c/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L15)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> How is `snopt_FOUND` set in this context? I wonder if we should find it somewhere higher up rather than finding it many times?
</details>
Looks like the author of the example forgot to check, so yes, we probably should.

---

*[drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-KV__w8w5ihfS4cxpGqs:-KV_bwU5f0w1G8901sPg:b59ts3h) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d285ff1b90a320e8a8ace3af545473387ea33c/drake/examples/QPInverseDynamicsForHumanoids/CMakeLists.txt#L10)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Same question
</details>
Probably the same answer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3941)*

**Comment by david-german-tri** [comment]
Awaiting @mwoehlke-kitware's feature review on this one, though I assume we should clear up #3996 first.

---

Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-:-KVatW_hOUP13EPYaywL:b1im1rx)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-KV__QysA-h2YRaARkPD:-KVfxta0iWb9qcLGbWBQ:b-vp8dde) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d285ff1b90a320e8a8ace3af545473387ea33c/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L15)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Looks like the author of the example forgot to check, so yes, we probably should.
</details>
(FTR: this was fixed by #3996)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-:-KVfyFWvIj9K4GOTFsD-:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
:lgtm:  mac-ninja failure looks spurious, and we have mac Make coverage, so I'll go ahead and merge this

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3941#-:-KVgTE_HWv1-rvqbtiHe:b7dzub7)*

**Pull request merged**
