### PR TITLE
pydrake rbt: Add bindings for ChildOfJoint and QDotToV methods

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9014)

### CODE REVIEW

**Comment by mpetersen94** [comment]
+@EricCousineau-TRI for feature review, please. Let me know if the unit tests cover everything you want them to.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending two items. Thanks!

---

Reviewed 3 of 3 files at r1.
Review status: 2 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9WjjFEMrbAmgFyVMD:-LF9WjjFEMrbAmgFyVME:b-f3juuj) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L119)):*
> ```Python
>         self.assertEqual(qdot_to_v.shape, (num_v, num_q))
> 
>         v_map = tree.transformVelocityMappingToQDotMapping(kinsol,
> ```

Would you be able to test the `AutoDiff` variants of this method?

---

*[multibody/rigid_body_tree.cc, line 3724 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9Wmhn2rWqO8I0YpUE:-LF9Wmho6caHClZ9wUo8:b-3pryyk) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/multibody/rigid_body_tree.cc#L3724)):*
> ```cpp
> template pair<Vector3d, double> RigidBodyTree<double>::resolveCenterOfPressure<Vector3d, Vector3d>(KinematicsCache<double> const&, vector<ForceTorqueMeasurement, allocator<ForceTorqueMeasurement>> const&, Eigen::MatrixBase<Vector3d> const&, Eigen::MatrixBase<Vector3d> const&) const;  // NOLINT
> 
> // Explicit template instantiations for transformVelocityMappingToQDotMapping.
> ```

Would you be able to remove the extra spacing injected before the template parameters' closing `>`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9014#-:-LF9WyQJ2WCD4PDpOmjR:b7m3pig)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9X0i20hIL-edzb3RE:-LF9X0i20hIL-edzb3RF:b-j9lj1t) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/bindings/pydrake/multibody/rigid_body_tree_py.cc#L143)):*
> ```cpp
>     .def("FindChildBodyOfJoint", [](const RigidBodyTree<double>& self,
>                         const std::string& joint_name,
>                         int model_id = -1) {
> ```

Can you remove the default argument in the lambda? It's redundant in this circumstance.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9014)*

**Comment by mpetersen94** [comment]
Review status: 3 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9X0i20hIL-edzb3RE:-LF9ebP0CFExxqT8PKdp:bx88d0r) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/bindings/pydrake/multibody/rigid_body_tree_py.cc#L143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you remove the default argument in the lambda? It's redundant in this circumstance.
</blockquote></details>

So just remove `int model_id = -1`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9014)*

**Comment by mpetersen94** [comment]
Review status: 3 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 143 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9X0i20hIL-edzb3RE:-LF9iiei7CtTpIEXA3ez:be973ow) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/bindings/pydrake/multibody/rigid_body_tree_py.cc#L143)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

So just remove `int model_id = -1`?
</blockquote></details>

Done. Figured out what you meant after looking closer.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9WjjFEMrbAmgFyVMD:-LF9ioz05smWsNBAHpxo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would you be able to test the `AutoDiff` variants of this method?
</blockquote></details>

Done.

---

*[multibody/rigid_body_tree.cc, line 3724 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9Wmhn2rWqO8I0YpUE:-LF9iprFBWVvLLI_XLU8:b-nin7g) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/multibody/rigid_body_tree.cc#L3724)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would you be able to remove the extra spacing injected before the template parameters' closing `>`?
</blockquote></details>

Is this what you meant? I was trying to mirror the other template instantiations.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9014)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri]

---

*[multibody/rigid_body_tree.cc, line 3724 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9014#-LF9Wmhn2rWqO8I0YpUE:-LFF_k_h7cto8UzJW07-:b-2nchyi) ([raw file](https://github.com/robotlocomotion/drake/blob/3ad93f3ffedd4b25c9449a1a173ba84195edcc75/multibody/rigid_body_tree.cc#L3724)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Is this what you meant? I was trying to mirror the other template instantiations.
</blockquote></details>

OK Yup! And sorry, didn't realize that we did this in other parts of the code, yuck! (I can fix this in another PR)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9014)*

**Pull request merged**
