### PR TITLE
ClarabelSolver supports SDP.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also modify ParseSemidefiniteConstraints to handle using upper or lower triangular matrix.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-:-NjAxgSW49xQ-LVEJ2mt:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.cc` line 666 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjD79vVArkn04GAt1qv:-NjD79vVArkn04GAt1qw:b-2iquty) ([raw file](https://github.com/RobotLocomotion/drake/blob/164a00d0f09645d7f217f84fd7a42defaad25f24/solvers/aggregate_costs_constraints.cc#L666)):*
> ```cpp
>     const int X_rows = psd_constraint.evaluator()->matrix_rows();
>     int x_index_count = 0;
>     const VectorXDecisionVariable& flat_X = psd_constraint.variables();
> ```

I think this would help here.

Also, this might be a reason (not in this PR necessarily.) No move the `Flatten` code from `mathematical_program.cc` somewhere more accessible.



_Suggestion:_
```cpp
// The variables in the psd constraint are the stacked columns of the matrix X
const VectorXDecisionVariable& flat_X = psd_constraint.variables();
```
___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 768 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjDADGc30c3sR555Qh3:-NjDADGc30c3sR555Qh4:b-d47tgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/164a00d0f09645d7f217f84fd7a42defaad25f24/solvers/test/aggregate_costs_constraints_test.cc#L768)):*
> ```cpp
>       A_expected(A_row_count_old + 6, 6) = -1;
>       A_expected(A_row_count_old + 7, 7) = -sqrt2;
>       A_expected(A_row_count_old + 8, 8) = -1;
> ```

I am a little confused by the order here. I would have thought we are parsing the PSD for X first, leading to 
`<-1,-sqrt2, -sqrt2, -1, -sqrt2, -1>` 
Then parse Y giving
`<-1 -sqrt2, -1>`.

It seems like the X constraint got parse backwards?



_Code quote:_
```cpp
      A_expected(A_row_count_old + 0, 0) = -1;
      A_expected(A_row_count_old + 1, 1) = -sqrt2;
      A_expected(A_row_count_old + 2, 3) = -1;
      A_expected(A_row_count_old + 3, 2) = -sqrt2;
      A_expected(A_row_count_old + 4, 4) = -sqrt2;
      A_expected(A_row_count_old + 5, 5) = -1;
      A_expected(A_row_count_old + 6, 6) = -1;
      A_expected(A_row_count_old + 7, 7) = -sqrt2;
      A_expected(A_row_count_old + 8, 8) = -1;
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.cc` line 666 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjD79vVArkn04GAt1qv:-NjEKJHl165NQ0hyXHNc:b-44m27h) ([raw file](https://github.com/RobotLocomotion/drake/blob/164a00d0f09645d7f217f84fd7a42defaad25f24/solvers/aggregate_costs_constraints.cc#L666)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think this would help here.

Also, this might be a reason (not in this PR necessarily.) No move the `Flatten` code from `mathematical_program.cc` somewhere more accessible.
</blockquote></details>

Done.

I still have a TODO in the `Flatten` function. The current implementation requires copy and dynamic memory allocation, which I don't like a lot. If I can come up with a better implementation, I will move it out of mathematical_program.cc
___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 768 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjDADGc30c3sR555Qh3:-NjEKo5PCA6tsKzY7ZYb:bdcqmhw) ([raw file](https://github.com/RobotLocomotion/drake/blob/164a00d0f09645d7f217f84fd7a42defaad25f24/solvers/test/aggregate_costs_constraints_test.cc#L768)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am a little confused by the order here. I would have thought we are parsing the PSD for X first, leading to 
`<-1,-sqrt2, -sqrt2, -1, -sqrt2, -1>` 
Then parse Y giving
`<-1 -sqrt2, -1>`.

It seems like the X constraint got parse backwards?
</blockquote></details>

I wasn't clear. I added some documentation. Is it more clear now?

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-:-NjETirH9PvZP5Kv8O_H:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for platform review please, because he kindly agrees to review the PR before I leave for China tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-:-NjEeHaP4XZYS8OPuRZy:b-vvrs2c)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one real nit (and two passing thoughts).

> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-:-NjEvNDN8RQfuECZbHUo:b-eo9pht)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/scs_solver.cc` line 650 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjEgztU3fmlbfQj8vAo:-NjEgztVBkcDNx2uu-Nk:brhfnyq) ([raw file](https://github.com/RobotLocomotion/drake/blob/408a5c18673e25d2d6f3a3f4124e0e156d9b2313/solvers/scs_solver.cc#L650)):*
> ```cpp
>   std::vector<int> psd_cone_length;
>   internal::ParsePositiveSemidefiniteConstraints(
>       prog, false /* upper_triangular = false */, &A_triplets, &b, &A_row_count,
> ```

BTW I've seen this as a kind of nice way to do this:



_Suggestion:_
```cpp
/* upper_triangular = */ false
```
___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 740 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjEuZ5kEi2aSQgsptOT:-NjEuZ5kEi2aSQgsptOU:b-4nw79t) ([raw file](https://github.com/RobotLocomotion/drake/blob/408a5c18673e25d2d6f3a3f4124e0e156d9b2313/solvers/test/aggregate_costs_constraints_test.cc#L740)):*
> ```cpp
>   prog.AddPositiveSemidefiniteConstraint(Y);
> 
>   auto check_psd = [&prog](bool upper_triangular) {
> ```

BTW THis is just fine as is and requires no change. But I wanted to suggest another way to do this (just so you have it in mind):

```c++
for (bool upper_triangle : {true, false}) {
...
}
```
___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 741 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjEuspnDTrcddqJ6Cv4:-NjEuspnDTrcddqJ6Cv5:b-7r1y7w) ([raw file](https://github.com/RobotLocomotion/drake/blob/408a5c18673e25d2d6f3a3f4124e0e156d9b2313/solvers/test/aggregate_costs_constraints_test.cc#L741)):*
> ```cpp
> 
>   auto check_psd = [&prog](bool upper_triangular) {
>     std::vector<Eigen::Triplet<double>> A_triplets;
> ```

nit: You should add:

```c++
SCOPED_TRACE(fmt::format("upper_triangle = {}", upper_triangle);
```

If the test fails, it'll be nice to know which version fails. Same for the lmi test.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20536)* status: 1 unresolved discussion, missing label for release notes

___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 740 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjEuZ5kEi2aSQgsptOT:-NjEx-tY4__TSdZQCa1O:b-lyby71) ([raw file](https://github.com/RobotLocomotion/drake/blob/408a5c18673e25d2d6f3a3f4124e0e156d9b2313/solvers/test/aggregate_costs_constraints_test.cc#L740)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW THis is just fine as is and requires no change. But I wanted to suggest another way to do this (just so you have it in mind):

```c++
for (bool upper_triangle : {true, false}) {
...
}
```
</blockquote></details>

Thanks! I will try the for loop version next time.
___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 741 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20536#-NjEuspnDTrcddqJ6Cv4:-NjExMDu2NpGQGsHwlf8:b-ohdol) ([raw file](https://github.com/RobotLocomotion/drake/blob/408a5c18673e25d2d6f3a3f4124e0e156d9b2313/solvers/test/aggregate_costs_constraints_test.cc#L741)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: You should add:

```c++
SCOPED_TRACE(fmt::format("upper_triangle = {}", upper_triangle);
```

If the test fails, it'll be nice to know which version fails. Same for the lmi test.
</blockquote></details>

Done, good call!

**Pull request merged**
