### PR TITLE
Always use Unix Makefiles generator for Fortran projects

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #3431.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3432)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by david-german-tri** [comment]
Ha, OK.  :lgtm: pending CI.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3432#-:-KRZJYUO5HNqe_o7rIn6:b-t2fjv9)*

**Pull request merged**
