### PR TITLE
Add simple positive returns implementation for DART-esque articulated… [dev folder]

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses one of the steps in #6655 and adds a very simple ICP implementation, leveraging `RigidBodyTree` as a simple scene graph representation.

Note that downsampling, basic outlier rejection (maximum distance for correspondences), etc., will be handled outside of this interface, at least in its initial state.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6659)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
checkpoint.

---

Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpu_4yPvIUrJZszH-_M:-Kpu_4yPvIUrJZszH-_N:b-t603g6) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/articulated_icp.h#L25)):*
> ```objc
>   void resize(int num) {
>     errors_.resize(Eigen::NoChange, num);
>     J_errors_.resize(3 * num, num_var_);
> ```

After resizing, `errors_` and `J_errors_` are unintialized.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpu_lV2TEl05WNfAsis:-KpuZZ8My9HgXhvCEaWh:b-2qby7i) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/articulated_icp.h#L32)):*
> ```objc
>   }
>   Eigen::Ref<const Eigen::Matrix3Xd> J_error(int i) const {
>     return J_errors_.middleRows(3 * i, 3);
> ```

`return  J_errors_.middleRows<3>(3 * i>`? Prefer static sized matrix, rather than the dynamic ones. 

---

*[drake/perception/estimators/dev/scene.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpucGr_QsREhfpcb4NX:-KpucGr_QsREhfpcb4NY:b-ckip4a) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/scene.h#L26)):*
> ```objc
> class Scene {
>  public:
>   Scene(const RigidBodyTreed* tree, const FrameIndex frame_W,
> ```

change the name to `frame_world` and `frame_camera` for clarity? `C` can mean many things.

---

*[drake/perception/estimators/dev/scene.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpucebTe_1pw2AYB2ox:-KpucebTe_1pw2AYB2oy:bd2trl7) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/scene.h#L42)):*
> ```objc
> 
> /**
>  * Stored state of a scene.
> ```

Document what the `state` here means? I think you mean the configuration (generalized position) of the scene, but does not include the velocity?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-:-KpudA-k0yaR_MUJSBxd:b6o68ox)*

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review (thanks for jumping in on this!)

\cc @gizatt

---

Reviewed 2 of 3 files at r2.
Review status: 1 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpu_4yPvIUrJZszH-_M:-Kpuu30IUNHXAsOSdz6g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/articulated_icp.h#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

After resizing, `errors_` and `J_errors_` are unintialized.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpu_lV2TEl05WNfAsis:-Kpuu3kl4zk07qF80yRR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/articulated_icp.h#L32)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`return  J_errors_.middleRows<3>(3 * i>`? Prefer static sized matrix, rather than the dynamic ones. 
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/scene.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpucGr_QsREhfpcb4NX:-Kpuu4OlChthwilDq2Nl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/scene.h#L26)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

change the name to `frame_world` and `frame_camera` for clarity? `C` can mean many things.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/scene.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpucebTe_1pw2AYB2ox:-Kpuu6C-aS0-4o2awsM-:b-y71jf4) ([raw file](https://github.com/robotlocomotion/drake/blob/1f94085db96c5b31545c3452eab9bada9439d8ee/drake/perception/estimators/dev/scene.h#L42)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document what the `state` here means? I think you mean the configuration (generalized position) of the scene, but does not include the velocity?
</blockquote></details>

Done. May include velocity in the future. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-:-KputsmarMjTLx8DxSi1:bdnduqw)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please.
(Seems like a flake error.)

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r2, 1 of 8 files at r3.
Review status: 3 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 118 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpvdzGytrSXPv93ixvv:-KpvdzGytrSXPv93ixvw:b-fzpvhp) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L118)):*
> ```objc
>  * Accumulate the L2 norm of the linearized point-to-point errors (e) to be
>  * rendered into a QuadraticCost operating on variables `q`:
>  * | e + Je*q |^2
> ```

I am unclear about this documentation. `Q` is a matrix of size `nq x nq`, but it does not appear in the documentation.  Also, what is the dimensionality of `e` here? Is it a 3 x 1 vector, of a 3 x num_points matrix?

---

*[drake/perception/estimators/dev/articulated_icp.h, line 146 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpvfv7HrqqzTvG1yJsJ:-Kpvfv7HrqqzTvG1yJsK:bge4v4k) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L146)):*
> ```objc
>   Eigen::VectorXd b_;
>   double num_points_;
>   double c_;
> ```

I am unclear what `c` means here. From `cost` function, it seems to mean the total cost. But from the `UpdateCost` function, it means the constant term in the quadratic cost. Maybe some documentation here would help?

---

*[drake/perception/estimators/dev/articulated_icp.h, line 160 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpvculvyg1Cm5rm-gy2:-Kpvculvyg1Cm5rm-gy3:b-k6cwti) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L160)):*
> ```objc
>    * @param num_max Maximum number of points to be stored.
>    */
>   ArticulatedIcpBodyPoints(FrameIndex frame_Bi, int num_max)
> ```

There is no check if `num_actual` is larger than `num_max`, `num_max` is just used in initializing the size of `meas_pts_W` and `body_pts_W`.  I would suggest to add the check `num_actual <= num_max`, when calling `Add` function.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 183 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpvkL5myGlhCUdmC56D:-KpvkL5myGlhCUdmC56E:bdb7cqg) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L183)):*
> ```objc
>  private:
>   FrameIndex frame_Bi{-1};
>   Eigen::Matrix3Xd meas_pts_W;
> ```

Which frame is `meas_pts` expressed in? Is it in the camera frame?

---

*[drake/perception/estimators/dev/articulated_icp.h, line 184 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpv_J-NiHK0vAr8HjNf:-Kpv_J-NiHK0vAr8HjNg:badbkvw) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L184)):*
> ```objc
>   FrameIndex frame_Bi{-1};
>   Eigen::Matrix3Xd meas_pts_W;
>   Eigen::Matrix3Xd body_pts_W;
> ```

If this is the body points position in the world frame, not in the body frame, then we should document it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 118 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpvdzGytrSXPv93ixvv:-Kpzb2HJRl-HNGQzdh6A:b-us5hrt) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L118)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am unclear about this documentation. `Q` is a matrix of size `nq x nq`, but it does not appear in the documentation.  Also, what is the dimensionality of `e` here? Is it a 3 x 1 vector, of a 3 x num_points matrix?
</blockquote></details>

I've added documentation on `e` and `J`. Let me know if you'd like me to clarify dimensionality on the coefficients.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 146 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpvfv7HrqqzTvG1yJsJ:-KpzbI0UsTan_Gb7ts6u:b-l2jby5) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L146)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am unclear what `c` means here. From `cost` function, it seems to mean the total cost. But from the `UpdateCost` function, it means the constant term in the quadratic cost. Maybe some documentation here would help?
</blockquote></details>

Sorry, I had first formulated in terms of `delta_q`, but did not change it appropriately. Thanks for catching that!

---

*[drake/perception/estimators/dev/articulated_icp.h, line 160 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpvculvyg1Cm5rm-gy2:-Kpzbw28VAUAyGzS3plj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L160)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

There is no check if `num_actual` is larger than `num_max`, `num_max` is just used in initializing the size of `meas_pts_W` and `body_pts_W`.  I would suggest to add the check `num_actual <= num_max`, when calling `Add` function.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 183 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpvkL5myGlhCUdmC56D:-Kpzce3li_LwJIayr8GG:b-nrtvkw) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L183)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Which frame is `meas_pts` expressed in? Is it in the camera frame?
</blockquote></details>

Done. Yes.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 184 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kpv_J-NiHK0vAr8HjNf:-KpzccW_x4SpYN-uddWw:bt4ox15) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L184)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If this is the body points position in the world frame, not in the body frame, then we should document it.
</blockquote></details>

Done. Thanks for the suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 7 files at r1, 1 of 8 files at r3.
Review status: 4 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 118 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpvdzGytrSXPv93ixvv:-KpzkYCdCHbnFaeQYftg:beoaa3h) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L118)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I've added documentation on `e` and `J`. Let me know if you'd like me to clarify dimensionality on the coefficients.
</blockquote></details>

Thanks for the explanation, that is very clear.

One small thing. The total cost is `E = ∑ eᵢ'eᵢ`, but in the documentation of `cost()` function, it says `cost()` also returns the total cost, which is `c`, different from `E`. Could you clarify that?

---

*[drake/perception/estimators/dev/articulated_icp.h, line 212 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpzqzoevJaGcFkujJma:-KpzqzoevJaGcFkujJmb:b-7zfefk) ([raw file](https://github.com/robotlocomotion/drake/blob/9988d7f861c8fbe67ab3b44cdf101ec43245afed/drake/perception/estimators/dev/articulated_icp.h#L212)):*
> ```objc
>    * `W`. */
>   Eigen::Matrix3Xd meas_pts_W;
>   /* Points on the given body, `Bi`, expressed in the world frame, `W`. */
> ```

Also mention that the point is fixed to the body frame?

---

*[drake/perception/estimators/dev/articulated_icp.h, line 263 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpzpHxKpsQNVJe-lr32:-KpzpHxKpsQNVJe-lr33:b-ttb3lo) ([raw file](https://github.com/robotlocomotion/drake/blob/9988d7f861c8fbe67ab3b44cdf101ec43245afed/drake/perception/estimators/dev/articulated_icp.h#L263)):*
> ```objc
>  * Determines if a correspondence with a given body influences the optimization
>  * formulation (camera or body position).
>  */
> ```

It would help to explain in which case the correspondence does not influences the optimization formulation. I did not realize that the camera frame can be the same as the world frame, until I read the function definition. Also, the correspondence on one of the kinematics chain should not affect the optimization on the other chain, due to the sparsity of the Jacobian matrix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 118 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpvdzGytrSXPv93ixvv:-Kq40tYe7apOhRURz-Yk:b-uqzr15) ([raw file](https://github.com/robotlocomotion/drake/blob/4c3c0ad37eccecaaa43c551fbe969a96b253783a/drake/perception/estimators/dev/articulated_icp.h#L118)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks for the explanation, that is very clear.

One small thing. The total cost is `E = ∑ eᵢ'eᵢ`, but in the documentation of `cost()` function, it says `cost()` also returns the total cost, which is `c`, different from `E`. Could you clarify that?
</blockquote></details>

Sorry, I had made a mistake there as well. Fixed it to return `cost_`, and updated the unittest. Thanks!

---

*[drake/perception/estimators/dev/articulated_icp.h, line 212 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpzqzoevJaGcFkujJma:-Kq41-lJW2Hof_07d2F9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9988d7f861c8fbe67ab3b44cdf101ec43245afed/drake/perception/estimators/dev/articulated_icp.h#L212)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also mention that the point is fixed to the body frame?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/articulated_icp.h, line 263 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpzpHxKpsQNVJe-lr32:-Kq411rQBc3-pWQQZC15:b-cgh9yd) ([raw file](https://github.com/robotlocomotion/drake/blob/9988d7f861c8fbe67ab3b44cdf101ec43245afed/drake/perception/estimators/dev/articulated_icp.h#L263)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It would help to explain in which case the correspondence does not influences the optimization formulation. I did not realize that the camera frame can be the same as the world frame, until I read the function definition. Also, the correspondence on one of the kinematics chain should not affect the optimization on the other chain, due to the sparsity of the Jacobian matrix.
</blockquote></details>

Done.
The influence is meant for each body, but this structure is used for a "broad-phase" check to see if any points involving this body will affect the optimization as a whole (assuming that all bodies within the entire model are all being optimized in the same `MathematicalProgram`).

Does the current documentation suffice, or would you like me to add more clarification?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 7 files at r1.
Review status: 5 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/articulated_icp.cc, line 84 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq5E2Q411ruAstjv9n_:-Kq5E2Q411ruAstjv9na:bl8ni06) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/articulated_icp.cc#L84)):*
> ```cpp
> }
> 
> void ArticulatedIcpErrorNormCost::Add(const SceneState&,
> ```

Should this be called only when `finalized_ = false`?

---

*[drake/perception/estimators/dev/articulated_icp.h, line 263 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-KpzpHxKpsQNVJe-lr32:-Kq5Dh8y2w8nboSNCbXr:b-v6uret) ([raw file](https://github.com/robotlocomotion/drake/blob/9988d7f861c8fbe67ab3b44cdf101ec43245afed/drake/perception/estimators/dev/articulated_icp.h#L263)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
The influence is meant for each body, but this structure is used for a "broad-phase" check to see if any points involving this body will affect the optimization as a whole (assuming that all bodies within the entire model are all being optimized in the same `MathematicalProgram`).

Does the current documentation suffice, or would you like me to add more clarification?
</blockquote></details>

Yes, this looks great. Thanks for adding the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r5.
Review status: 7 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 47 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6QernHcD4Lb0GkGk_:-Kq6QernHcD4Lb0GkGka:ba8n8s5) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L47)):*
> ```cpp
>   Interval() {}
>   Interval(double min, double max)
>       : min(min), max(max) {}
> ```

Also check if `max >= min`?

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 77 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6RIjcOqSD7FcNrpD6:-Kq6RIjcOqSD7FcNrpD7:boz16tt) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L77)):*
> ```cpp
> };
> 
> Matrix2Xd GeneratePlane(double space, Interval x, Interval y) {
> ```

Maybe call this `Generate2DPlane`?

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 186 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6THjZ2uT7ADD0V31c:-Kq6THjZ2uT7ADD0V31d:b-8je3nf) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L186)):*
> ```cpp
>     string file_path = FindResourceOrThrow(
>         "drake/perception/estimators/dev/simple_cuboid.urdf");
>     auto floating_base_type = multibody::joints::kRollPitchYaw;
> ```

I am a bit concerned about using roll-pitch-yaw as the orientation. The Jacobian can be ill defined, when the pitch angle is close to pi / 2.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 277 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6TihBxNR4RGrFegUk:-Kq6TihBxNR4RGrFegUl:b51bwrk) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L277)):*
> ```cpp
> 
> TEST_F(ArticulatedIcpTest, PositiveReturnsIncreasingCost) {
>   // Start box at the given state, ensure that the cost increases as we
> ```

If it is for a simple cuboid, then we can actually solve a single body ICP, instead of articulated ICP. The single body ICP can be solved in the closed form (call SVD to compute the rotation), rather than using an optimization program. How about also write the single body ICP, and compare the result with articulated ICP in this test?

Projecting a matrix to SO(3) through SVD has already been implemented in https://github.com/RobotLocomotion/drake/blob/master/drake/math/rotation_matrix.h#L234-L252

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by hongkai-dai** [comment]
:lgtm: some more documentation in the `articulated_icp_test.cc` would be helpful. For example, the reader can benefit from the documentation on explaining `GeneratePlane`, etc. But since this is in the dev directory, I think we can work on these details in the future.

Thanks @ericcousineau-tri for the patience!

---

Review status: 7 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-:-KqABXNzYWhz9TwFJD6l:b-z3vg1k)*

**Comment by EricCousineau-TRI** [comment]
Thanks!

+@jwnimmer-tri for Monday platform review, please.

---

Review status: 6 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/perception/estimators/dev/articulated_icp.cc, line 84 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq5E2Q411ruAstjv9n_:-KqACDzNVLUmQLGIzXfN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/articulated_icp.cc#L84)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should this be called only when `finalized_ = false`?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 47 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6QernHcD4Lb0GkGk_:-KqACUWE3sEeTB1ZSQhj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also check if `max >= min`?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 77 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6RIjcOqSD7FcNrpD6:-KqACYxpl1xS7XQvwu6B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L77)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe call this `Generate2DPlane`?
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 186 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6THjZ2uT7ADD0V31c:-KqACc2NiQYmnZds9Stx:bd7a2rk) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L186)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am a bit concerned about using roll-pitch-yaw as the orientation. The Jacobian can be ill defined, when the pitch angle is close to pi / 2.
</blockquote></details>

Would it be OK with you if I addressed that in a future PR? (I have added a TODO.)

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 277 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6TihBxNR4RGrFegUk:-KqADOU5zt1r0r4iTzTM:b-4px0ir) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L277)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If it is for a simple cuboid, then we can actually solve a single body ICP, instead of articulated ICP. The single body ICP can be solved in the closed form (call SVD to compute the rotation), rather than using an optimization program. How about also write the single body ICP, and compare the result with articulated ICP in this test?

Projecting a matrix to SO(3) through SVD has already been implemented in https://github.com/RobotLocomotion/drake/blob/master/drake/math/rotation_matrix.h#L234-L252
</blockquote></details>

Will address in future PR. Added TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-:-KqE9-0Ov0scJcJQiXb_:b-992lr5)*

**Comment by hongkai-dai** [comment]
Review status: 6 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 186 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-Kq6THjZ2uT7ADD0V31c:-KqE_7_xOx_ckzMcAjGb:bil7lsi) ([raw file](https://github.com/robotlocomotion/drake/blob/560a2c22e52d851dbc2fe4948c4b36b868c7cd15/drake/perception/estimators/dev/test/articulated_icp_test.cc#L186)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be OK with you if I addressed that in a future PR? (I have added a TODO.)
</blockquote></details>

Sounds good. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659)*

**Comment by jwnimmer-tri** [comment]
:lgtm: on non-dev parts.

---

Reviewed 3 of 8 files at r3.
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6659#-:-KqFhsRxrYVOJF5TY8Xw:b-ca8sj9)*

**Pull request merged**
