### PR TITLE
framework_py: Ensure `LeafSystem<T>::DoPublish` is exposed and overridable.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per @RussTedrake's request.

~Pending merge of https://github.com/RobotLocomotion/pybind11/pull/8~ Merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7838)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jadecastro for feature review, please.
+@sammy-tri for platform review, please.

If you are able to prioritize this a bit, Russ was wondering if he could use this in the nightly off of `master`.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-:-L3Z5r4L72ZkkGjrLB69:b-e8v6cx)*

**Comment by jadecastro** [comment]
:lgtm: (modulo a couple minor comments)

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/test/custom_test_py.cc, line 0 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZQeeVorUhVvFLYDTK:-L3ZQeeVorUhVvFLYDTL:bg3hxbr) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/bindings/pydrake/systems/test/custom_test_py.cc#L0)):*
Is this file needed?

---

*[tools/workspace/pybind11/package.bzl, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZA40U_PBvSY149mXE:-L3ZA40U_PBvSY149mXF:b-wxuroa) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/tools/workspace/pybind11/package.bzl#L8)):*
> ```Python
>     github_archive(
>         name = name,
>         # TODO(eric.cousineau): Use RobotLocomotion.
> ```

BTW, is this pending https://github.com/RobotLocomotion/pybind11/pull/8? If so, perhaps state that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-:-L3Z9HTNxW0N5gF5F0iv:b9kvh8a)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/custom_test.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZewKljg5GCyPo2LMz:-L3ZewKmsQpREdwSZiRw:b-dap14s) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/bindings/pydrake/systems/test/custom_test.py#L35)):*
> ```Python
>             self._DeclareInputPort(PortDataType.kVectorValued, size)
>         self._DeclareVectorOutputPort(BasicVector(size), self._calc_sum)
>         self._DeclarePeriodicPublish(0.1)
> ```

I'm not sure what extra coverage is being added by declaring this publish here.  (comment perhaps?)

---

*[bindings/pydrake/systems/test/custom_test_py.cc, line  at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZQeeVorUhVvFLYDTK:-L3ZfLRTrgjNtkxkYJz5:b-rb6t5z) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/bindings/pydrake/systems/test/custom_test_py.cc#L)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Is this file needed?
</blockquote></details>

Excellent question...

---

*[tools/workspace/pybind11/package.bzl, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZA40U_PBvSY149mXE:-L3ZfWR19pa9M-sOepOX:b-kzoghl) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/tools/workspace/pybind11/package.bzl#L8)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, is this pending https://github.com/RobotLocomotion/pybind11/pull/8? If so, perhaps state that?
</blockquote></details>

Or state whatever is blocking using RobotLocomotion again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-:-L3ZfbZ3LCq4xuXx3Y00:bvb1a6z)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/custom_test.py, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZewKljg5GCyPo2LMz:-L3ZgsoTxrIFfrzZgBpm:b-hit5cg) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/bindings/pydrake/systems/test/custom_test.py#L35)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure what extra coverage is being added by declaring this publish here.  (comment perhaps?)
</blockquote></details>

Done. Sorry, had forgotten to remove that!

---

*[tools/workspace/pybind11/package.bzl, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZA40U_PBvSY149mXE:-L3ZgwzZS_BWe3hE9pEp:b-biwhic) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/tools/workspace/pybind11/package.bzl#L8)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Or state whatever is blocking using RobotLocomotion again.
</blockquote></details>

Done. Sorry, meant to mention that this PR would not go into until it merged, but it's done now.

---

*[bindings/pydrake/systems/test/custom_test_py.cc, line  at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-L3ZQeeVorUhVvFLYDTK:-L3Zh-YW_VCdx8e7gu_j:bdfszzr) ([raw file](https://github.com/robotlocomotion/drake/blob/80354c1f6c1d8353fd9584c326fdc98e515fd75b/bindings/pydrake/systems/test/custom_test_py.cc#L)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Excellent question...
</blockquote></details>

Done. Oops! Had left this in by mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7838)*

**Comment by jadecastro** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7838)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7838#-:-L3ZvewE8WJ7Y2FqPZCa:bnfp4nl)*

**Pull request merged**
