### PR TITLE
MBP acrobot with LQR controller example

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR adds the full continuous state output port to MBP and makes use of it in the example for the acrobot with LQR controller.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8365)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@naveenoid for feature review please.
+@seancurtis-tri for platform review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-:-L7_2JYbuyVkYrMUg4vd:b-ql75d8)*

**Comment by SeanCurtis-TRI** [comment]
I'll wait for @naveenoid to do feature review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-:-L7_JmpQH5KumYUB2OSC:bhc4im8)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/benchmarks/acrobot/make_acrobot_plant.h, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-L7eMjeCidGn4QjC0vwy:-L7eMjeCidGn4QjC0vwz:bih2ml8) ([raw file](https://github.com/robotlocomotion/drake/blob/dabdd0179d9bbf85f69be81406bb264f02c550bf/multibody/benchmarks/acrobot/make_acrobot_plant.h#L93)):*
> ```objc
>   // Radii of the cylinders used for visualization.
>   // We make the second link slightly fatter so that we can see the difference
>   // when they are aligned, even if using the same colors.
> ```

BTW: How about rephrasing to "The second link is made slightly thicker so that the difference between the links can be seen when aligned"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-:-L7eNXHVhGtqOHgeJ-0C:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Requires new merge with master and one BTW.

---

Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-L7jJJAhxLCZa5N1Dx-f:-L7jJJAhxLCZa5N1Dx-g:b8ex6yv) ([raw file](https://github.com/robotlocomotion/drake/blob/91cf850e1fe0298270e7069de50256d283419b5f/multibody/multibody_tree/multibody_plant/multibody_plant.h#L120)):*
> ```objc
> /// @endcond
> ///
> /// @cond
> ```

BTW Unclear why this is being removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-:-L7jK1hzPMxsUDQM2bjW:bcjldkr)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8365#-L7jJJAhxLCZa5N1Dx-f:-L7jc9YfmGuebAkAd_Wi:b-iqwrdr) ([raw file](https://github.com/robotlocomotion/drake/blob/91cf850e1fe0298270e7069de50256d283419b5f/multibody/multibody_tree/multibody_plant/multibody_plant.h#L120)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Unclear why this is being removed.
</blockquote></details>

BTW. Because it is not true anymore. The plant only provides a systems interface. If you want do compute an MBT quantity, say the mass matrix, you'll do `plant.model().CalcMassMatrix(context)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8365)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8365)*

**Pull request merged**
