### PR TITLE
multibody/parsing: Remove entire package of dead code

### LINKED ISSUE #9781: Determine if multibody/parsing is dead code
The code in `multibody/parsing` was initially written to get the ball rolling for the interaction with OSRC to help us with the SDF parser. The decision was to migrate features from that code directly into `sdformat` and it slowly decayed into disuse.

If nothing from this directory is useful (for instance the `frame_cache.h` code used to specify the pose of a frame in any other frame defined int the file), this code should be eliminated from Drake master.

@sammy-tri, @jwnimmer-tri, anything useful there you'd like to keep?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #9781.  Relates #9314.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9800)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review, please.

**Comment by jwnimmer-tri** [comment]
-@amcastro-tri +@sherm1 as the second reviewer, please.

**Comment by RussTedrake** [comment]
Confirmed that I'm not using it (the parsing nor the double_pendulum example).  Happy to see it disappear.

**Comment by jwnimmer-tri** [comment]
> This looks like a complete removal of any Drake dependence on OSRF's sdformat library - is that right?
> If so can we remove sdformat altogether as an external? If not, what's left that's using it?

The `./multibody/multibody_tree/parsing` folder -- the parsing code we intent to maintain and improve -- still uses libsdformat.

>  It is actually a very nice little example with a fancy README updated only last week by Luke Peterson. Should it be ported to an sdformat-free afterlife instead of nuked altogether?

That's up to you, as a reviewer.  If you like, I am happy to rework this PR to move this parsing code into the `examples/double_pendulum` folder, instead of removing it.  The most important goal here is that it disappear from the multibody folder.

**Comment by jwnimmer-tri** [comment]
Actually looking at the double pendulum demo in more detail now, is all RBT-coupled anyway.  While I think it is well done, basically none of its code would help us in a rewrite of it.  So I would lean toward removing it entirely now, but I'll let @sherm1 make the final call.  I'll rework the PR to keep it, if you like.

**Comment by jwnimmer-tri** [comment]
The best skeleton is a working example.  I'll move the parsing code into the example folder, so that it will still be runnable, etc.  Then Luke can rework it in place.

**Comment by jwnimmer-tri** [comment]
@sherm1 PTAL

**Pull request merged**
