### PR TITLE
Reduce inequalities doc change

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18321)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for review. I realized that this method actually does give a minimal description of the HPolyhedron with the code as written.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18321#-:-NGrhLvh2hhMQV1WSYpl:b2dxdt8)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
I am not entirely sure why this function gives the minimal description of the HPolyhedron.

What ReduceInequalities does is this
1. Start with `kept_indices` including every row of `A*x <= b`.
2. Loop through each row of `A*x <= b`. Within each iteration of the loop, check if the i'th row of `A*x<=b` is redudant, given `kept_indices - {i} ` rows of `A*x<=b`. If it is redundant, then remove `i` from `kept_indices`.

Could you explain why at the end of the loop, `kept_indices` gives the minimal description?

Also if we claim it does, then we need to add tests to guarantee our implementation really gives the minimal description.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18321#-:-NGwO9HSC91pUdl9WukU:b-tri9xb)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by AlexandreAmice — COMMENTED** [review]
First we can argue that the current implementation removes all (not just some) of the redundant inequalities. If the i_th constraint is tested as irredundant at step i, it cannot later become redundant in the loop.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18321#-:-NGwlOVy9KEU6YHg3DZS:bkiyzq)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
I buy that argument that we get the minimal description.

I would still argue for a unit test for the minimal description. The future maintainers can use that unit test to validate that the possible changes to the function implementation is correct.

One way to test the minimal description is this: say you have got the minimal description as `A * x <= b`. To make sure it is indeed minimal, you could test any row i of `A * x <= b` is redundant or not.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18321#-:-NGxFrmH3lkQ1WPVA6l2:b-gc5txm)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by AlexandreAmice — COMMENTED** [review]
Actually I will need to work harder to ensure this minimality property. Suppose `A * x <= b` contains two sets of inequalities of different sizes which define an empty set`A1 * x <= b1` and `A2 * x <= b2. Say `A1.rows() < A2.rows()` the current method does not guarantee that we end up with the rows of `A1`

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18321#-:-NHjVANj3MSJQ9EtU_wk:bb4xyhh)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Pull request closed without merging**
