### PR TITLE
workspace: Update optitrack_driver for skeleton support

### PR DESCRIPTION
**Pull request by sammy-tri**
This is a breaking change to the optitrack LCM types.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18330)

### CODE REVIEW

**Review by sammy-tri — COMMENTED** [review]
+@pangtao22 for feature review.  The main change is in https://github.com/RobotLocomotion/optitrack-driver/pull/14

If you need to preserve the old LCM types (for log playback, maybe?)  I can go and add compatibility types in `optitrack-driver`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18330#-:-NH0F8gfBsChEOTV9RRb:b-djud7v)* status: LGTM missing from assignee pangtao22, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @pangtao22)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: breaking change) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18330#-:-NH0Hw0t8IjhvAElKcya:bre1st4)* status: LGTM missing from assignee pangtao22, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @pangtao22)

**Review by pangtao22 — COMMENTED** [review]
:lgtm: 
Thanks Sammy! I took a quick look at the changes. It seems that the types for rigid bodies and marker sets have not changed? I do not have logs using the old `optitrack_frame` type, does it mean my current code that uses `optitrack_frame` should run without changes? 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18330#-:-NHD2nRB9p--SGhS0Zr_:b-v1ipe5)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by sammy-tri — COMMENTED** [review]
Existing code should work unchanged (and has in my testing here).  +@seancurtis-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18330#-:-NHytRlM3Xe-O5PucClo:bw2dwkl)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @pangtao22 and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18330#-:-NHywgXsBeSywcjVf9B8:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees pangtao22,SeanCurtis-TRI(platform) (waiting on @pangtao22)

**Pull request merged**
