### PR TITLE
SceneGraph SDF parsing

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements part of the inner workings of a `SceneGraph` SDF parser built on top of `sdformat`. These internals are not part of the user-facing API but live in a `detail::` namespace. The idea is to keep these internals as modular as possible to facilitate unit testing (thanks @SeanCurtis-TRI for the idea).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744#-:-LBXMCb91zhIWSOX78fM:b-4269ug)*

**Comment by amcastro-tri** [comment]
cc'ing @nkoenig

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

Some comments and questions, but largely cosmetic and curiosity.

+@soonho-tri for platform review

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/parsing/BUILD.bazel, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbJrH-8Rm481uGEvZv:-LBbJrH-8Rm481uGEvZw:bghob3e) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/BUILD.bazel#L37)):*
> ```Python
>         ":sdf_parser_common",
>         "//geometry:scene_graph",
>         "@sdformat",
> ```

FYI Not strictly necessary. It depends on `sdf_parser_common` so it inherits this.  Same for others. I don't have a strong sense for whether we prefer barebones or redundant. But whatever the answer is, it should apply to all of the libraries.

I've put in a question on the bazel channel and I'll see what comes up.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbH1jA1RJ9svw0wJuR:-LBbH1jA1RJ9svw0wJuS:b-2ovz7b) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L4)):*
> ```objc
> 
> #include <memory>
> #include <string>
> ```

BTW Unused?

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbHrnv9Jq5FIwExuSF:-LBbHrnv9Jq5FIwExuSG:b-7ukoo2) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L18)):*
> ```cpp
> using Eigen::Vector3d;
> using geometry::GeometryInstance;
> using geometry::HalfSpace;
> ```

BTW Strange this is the only alias -- and you didn't use it below (`geometry::HalfSpace`)

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbIAJp1hkH3BxG5Ogy:-LBbIAJp1hkH3BxG5Ogz:bcthv5u) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L25)):*
> ```cpp
>   switch (sdf_geometry.Type()) {
>     case sdf::GeometryType::CYLINDER: {
>       const sdf::Cylinder& shape = *sdf_geometry.CylinderShape();
> ```

FYI Is there *any* documentation that we can reference that promises that the sdf cylinder is oriented the same as the drake cylinder? [This](http://sdformat.org/spec?ver=1.6&elem=geometry#geometry_cylinder) doesn't. Is there doxygen on this API that does?

Same for plane (i.e., is it z-up?)

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbIn-01E5yrnaIYaVu:-LBbIn-01E5yrnaIYaVv:b-skfiwl) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L37)):*
> ```cpp
>       // canonical frame C. Therefore the normal information is used during
>       // the parsing of a GeometryInstance, which does contain the pose of the
>       // half space in the parent link frame.
> ```

FYI This makes me feel like I've created an awkward API. Would you wish for an API that didn't require you to jump through these hoops for the plane?

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbKu6lEaVjELSbxdXo:-LBbKu6lEaVjELSbxdXp:bnsxh6v) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L16)):*
> ```cpp
> namespace drake {
> 
> using Eigen::Isometry3d;
> ```

BTW Why did you pull all of this into the `drake` namespace?

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbL6qX1FDIhjIVQCbz:-LBbL6qX1FDIhjIVQCc-:b-run2m7) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L40)):*
> ```cpp
> // Helper to create an sdf::Geometry object from its SDF specification given
> // as a string. Example of what the string should contain:
> //   "<cylinder>"
> ```

FYI I'd forego the double quotes. Same below.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbLD5n7PpH4xczZ3K9:-LBbLD5n7PpH4xczZ3KA:bkxrwez) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L62)):*
> ```cpp
>   sdf::SDFPtr sdf_parsed(new sdf::SDF());
>   sdf::init(sdf_parsed);
>   sdf::readString(sdf_str, sdf_parsed);
> ```

BTW How about error checking? Or is the idea, if a new test is added with bad XML, they'll figure that out running the test and bad XML will never be committed to master?

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbMClWCM9adgHjhzY0:-LBbMClWCM9adgHjhzY1:bpr8emn) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L170)):*
> ```cpp
>   const double kTolerance = 10 * std::numeric_limits<double>::epsilon();
>   EXPECT_TRUE(CompareMatrices(X_LC.linear(), R_LC_expected,
>                               kTolerance, MatrixCompareType::relative));
> ```

FYI Given you know the scale of the problem in this case, why relative? Just my curiosity.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744#-:-LBbMq7lAFOvAgSfaEEJ:be3xtpo)*

**Comment by soonho-tri** [comment]
Checkpoint

---

Reviewed 5 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbYI2VAYmnTHC-58uB:-LBbYI2VAYmnTHC-58uC:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L4)):*
> ```objc
> 
> #include <memory>
> #include <string>
> ```

unused?

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbY2Ph4LWZ4AmnLB_Z:-LBbY2Ph4LWZ4AmnLB__:bof8lnj) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L16)):*
> ```objc
> 
> /// Given an sdf::Geometry object representing a <geometry> element from an SDF
> // file, this method makes a new drake::geometry::Shape object from this
> ```

FYI, there is a fight between `///` and `//` in this file.

---

*[multibody/multibody_tree/parsing/sdf_parser_common.h, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbX7CFEi_LCMTN_Oeh:-LBbX7CG57PzF3TG_aH_:b-k8wcai) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/sdf_parser_common.h#L3)):*
> ```objc
> #pragma once
> 
> #include <sdf/sdf.hh>
> ```

BTW, I guess `#include "ignition/math/Vector3.hh"` should be good enough here?

---

*[multibody/multibody_tree/parsing/sdf_parser_common.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbXQ5e2PblOV7xunAx:-LBbXQ5e2PblOV7xunAy:b-z5fu26) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/sdf_parser_common.h#L12)):*
> ```objc
> namespace detail {
> 
> // Helper function to express an ignition::math::Vector3d instance as
> ```

BTW, consider making them doxygen-comments (`///`) as they are not in an unnamed namespace anymore. 

---

*[multibody/multibody_tree/parsing/sdf_parser_common.cc, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbXq2l22azSQmckFK8:-LBbXq2l22azSQmckFK9:blkog0b) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/sdf_parser_common.cc#L3)):*
> ```cpp
> #include "drake/multibody/multibody_tree/parsing/sdf_parser_common.h"
> 
> #include <sdf/sdf.hh>
> ```

BTW, in general, this is not necessary as we already have the same include in the header file.

---

*[multibody/multibody_tree/parsing/sdf_parser_common.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbXdFo7hH5AjyeREnc:-LBbXdFo7hH5AjyeREnd:b-bayj97) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/sdf_parser_common.cc#L13)):*
> ```cpp
> using Eigen::Vector3d;
> 
> // Helper function to express an ignition::math::Vector3d instance as
> ```

BTW, those comments are not necessary as they are duplicates of the ones in the header.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744#-:-LBbYU_L3RidnegIBIKn:b13s2ul)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[multibody/multibody_tree/parsing/BUILD.bazel, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbJrH-8Rm481uGEvZv:-LBbVent5Xpakm3-l9lv:bnui7it) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/BUILD.bazel#L37)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Not strictly necessary. It depends on `sdf_parser_common` so it inherits this.  Same for others. I don't have a strong sense for whether we prefer barebones or redundant. But whatever the answer is, it should apply to all of the libraries.

I've put in a question on the bazel channel and I'll see what comes up.
</blockquote></details>

See related conversation: https://reviewable.io/reviews/robotlocomotion/drake/8298#-L9jcsbxC3489Z_ilYmx

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbYI2VAYmnTHC-58uB:-LBbYvPk3xcx2EtPl79-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L4)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.h, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbY2Ph4LWZ4AmnLB_Z:-LBbZ-tV56S4Awt3i5Lp:b-uye6z3) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.h#L16)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, there is a fight between `///` and `//` in this file.
</blockquote></details>

They are not fighting! they are happily coexisting together :-) 

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbHrnv9Jq5FIwExuSF:-LBbWHoS2mdPWVLk5ORi:bg9hnfe) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Strange this is the only alias -- and you didn't use it below (`geometry::HalfSpace`)
</blockquote></details>

BTW that's because I changed my mind mid way through. I prefer not aliasing since for instance, we have `sdf::Cylinder` and `geometry::Cylinder`. For consistency I'll remove all aliases on these primitives.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbIAJp1hkH3BxG5Ogy:-LBbWrq98FmbZENEO-0i:b-jbw5gz) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Is there *any* documentation that we can reference that promises that the sdf cylinder is oriented the same as the drake cylinder? [This](http://sdformat.org/spec?ver=1.6&elem=geometry#geometry_cylinder) doesn't. Is there doxygen on this API that does?

Same for plane (i.e., is it z-up?)
</blockquote></details>

No, there is none, not in the link to the official SDF's docs nor in the sdf::Cylinder API. I will add a TODO for now. Pinging @nkoenig to update this documentation.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbIn-01E5yrnaIYaVu:-LBbXVCi4YvzJVBBUS5R:b7yf5ra) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L37)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This makes me feel like I've created an awkward API. Would you wish for an API that didn't require you to jump through these hoops for the plane?
</blockquote></details>

It's fine for me. It's just two different ways to do it. Your's is consistent in that each geometry has a canonical frame `C`, so I guess I actually like yours better.

---

*[multibody/multibody_tree/parsing/sdf_parser_common.h, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbX7CFEi_LCMTN_Oeh:-LBbZWmd8EQAmL5n-Lnq:b6fh4v9) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/sdf_parser_common.h#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I guess `#include "ignition/math/Vector3.hh"` should be good enough here?
</blockquote></details>

BTW, I like it.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbLD5n7PpH4xczZ3K9:-LBbYMS01aeuchn8FD2o:b-uekqp2) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L62)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW How about error checking? Or is the idea, if a new test is added with bad XML, they'll figure that out running the test and bad XML will never be committed to master?
</blockquote></details>

BTW. Correct, that was my thought. This is not user facing API that I need to cleanup thoroughly. It is contained to these unit tests. 

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbMClWCM9adgHjhzY0:-LBbYcpRDwW13Up5PVBF:b-3abxfb) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L170)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Given you know the scale of the problem in this case, why relative? Just my curiosity.
</blockquote></details>

Because `X.linear()` has no units while `X.translation()` does. Therefore I can use the same dimensionless tolerance for both. You'll see in general that is my preference (unless I compare things close to zero).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)*

**Comment by amcastro-tri** [comment]
Thanks! back to you guys.

---

Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744#-:-LBb_1348eK487SV8EHm:bpwuiy4)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBbMClWCM9adgHjhzY0:-LBbkU9p09aonJyEDx16:bv8oiq6) ([raw file](https://github.com/robotlocomotion/drake/blob/525f0f30f53d83a9526b60ae8600cd14fb8ec426/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L170)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I don't follow the argument, but I accept it.
</blockquote></details>

Never mind, I thought I was comparing an entire pose, not only the rotation. In this case yes, it is just preference.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)*

**Comment by soonho-tri** [comment]
:lgtm: Thanks for the patience. :apple: tested as well.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBcFidC57QzABlc2xMY:-LBcFidC57QzABlc2xMZ:brzz01k) ([raw file](https://github.com/robotlocomotion/drake/blob/9260ee923269c9167a90a9f3998bbfc7536ce5e6/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L41)):*
> ```cpp
>       return make_unique<geometry::HalfSpace>();
>     }
>     default: {
> ```

BTW, since `sdf::GeometryType` is an enum class, consider explicitly enumerating all cases without using `default:`. I think you only need `EMPTY`, `BOX`, and `CYLINDER`.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBcJbHE9ZJajvag3K5z:-LBcJbHE9ZJajvag3K6-:btd02qm) ([raw file](https://github.com/robotlocomotion/drake/blob/9260ee923269c9167a90a9f3998bbfc7536ce5e6/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L45)):*
> ```cpp
> // and similarly for other SDF geometries.
> unique_ptr<sdf::Geometry> MakeSdfGeometryFromString(
>     const std::string geometry_spec) {
> ```

BTW, missing `&`? `const std::string&`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744#-:-LBcLyez6_OkE4Pr5YZL:b-eddcra)*

**Comment by amcastro-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBcFidC57QzABlc2xMY:-LBfHzCG64n846G7iUeF:b-itxv2h) ([raw file](https://github.com/robotlocomotion/drake/blob/9260ee923269c9167a90a9f3998bbfc7536ce5e6/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L41)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, since `sdf::GeometryType` is an enum class, consider explicitly enumerating all cases without using `default:`. I think you only need `EMPTY`, `BOX`, and `CYLINDER`.
</blockquote></details>

BTW, I believe I want the default in case someone decides to expand that enum? I did add TODO's to extend the current list and I also added the "empty" case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)*

**Comment by SeanCurtis-TRI** [comment]
A couple of new concerns with the expanded enum functionality in `MakeShapeFromSdfGeometry`.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfMyHi4llXC37bjs4h:-LBfMyHi4llXC37bjs4i:boo4g7y) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L24)):*
> ```cpp
>   switch (sdf_geometry.Type()) {
>     case sdf::GeometryType::EMPTY: {
>       return std::unique_ptr<geometry::Shape>(nullptr);
> ```

BTW I don't think this is a good solution. I think `SceneGraph` is going to get *really* angry if an empty geometry is passed. A geometry instance simply shouldn't be generated if the type is `EMPTY`. That's probably best handled by `MakeGeometryInstanceFromSdfVisual`. It should *also* return a `null` and the infrastructure calling *it* should detect the null and not try to register geometry.

So, ultimately, I guess what I'm saying is, this is fine. Just don't try to invoke `SceneGraph` on a `GeometryInstance` with a null geometry.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 105 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfNVNr0pa-O1ZI-4R_:-LBfNVNs0-DTA81ZcbGJ:b2oll0k) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L105)):*
> ```cpp
> // Verify MakeShapeFromSdfGeometry returns nullptr when we specify an <empty>
> // sdf::Geometry.
> GTEST_TEST(SceneGraphParserDetal, MakeEmptyFromSdfGeometry) {
> ```

BTW I just noticed the typo: s/Detal/Detail on all the tests.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 107 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfNpHADcGlbkQLZwZl:-LBfNpHADcGlbkQLZwZm:bpv6lri) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L107)):*
> ```cpp
> GTEST_TEST(SceneGraphParserDetal, MakeEmptyFromSdfGeometry) {
>   unique_ptr<sdf::Geometry> sdf_geometry =
>       MakeSdfGeometryFromString("<empty/>");
> ```

BTW I'm surprised that *this* is the mechanism to get an `EMPTY` tag. How about if you pass in an empty string here?

Also, what happens if you pass in a link that declares a `visual` tag without any geometry at all?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744#-:-LBfO2SmDf948GQAn_Gc:bydu5gz)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfMyHi4llXC37bjs4h:-LBfQuV02ztChDFx_77U:bp6elpx) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I don't think this is a good solution. I think `SceneGraph` is going to get *really* angry if an empty geometry is passed. A geometry instance simply shouldn't be generated if the type is `EMPTY`. That's probably best handled by `MakeGeometryInstanceFromSdfVisual`. It should *also* return a `null` and the infrastructure calling *it* should detect the null and not try to register geometry.

So, ultimately, I guess what I'm saying is, this is fine. Just don't try to invoke `SceneGraph` on a `GeometryInstance` with a null geometry.
</blockquote></details>

BTW. The user of this `detail::` method, the MBP parser (and the SG parser in some future), will check for the returned object to be `nullptr`, that is why it gets documented that way. 
Per your comment I implemented the creation of a null GeometryInstance and unit tested it as well.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 105 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfNVNr0pa-O1ZI-4R_:-LBfRPVyC-tUvceUJCr-:brdwe8d) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L105)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I just noticed the typo: s/Detal/Detail on all the tests.
</blockquote></details>

Thanks! those are so easy to miss. 

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 107 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfNpHADcGlbkQLZwZl:-LBfSFiND1tEfl7VKXex:b8maysm) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L107)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm surprised that *this* is the mechanism to get an `EMPTY` tag. How about if you pass in an empty string here?

Also, what happens if you pass in a link that declares a `visual` tag without any geometry at all?
</blockquote></details>

BTW, sdformat barks before I can even do anything. Those errors get collected by the MBP parser and then get thrown back to the user. Here I am not testing the sdformat library, just that these method do the right thing with a properly initialized `sdf::` object.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 61 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfTpfc8ISiKh_ib7mU:-LBfTpfc8ISiKh_ib7mV:b-rhltiw) ([raw file](https://github.com/robotlocomotion/drake/blob/e7ab5f415cfa4794e096fc923cfa8f462fe11ae5/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L61)):*
> ```cpp
>   // Nothing left to do, return nullptr signaling this is an empty visual.
>   if (sdf_geometry.Type() == sdf::GeometryType::EMPTY) {
>     return std::unique_ptr<GeometryInstance>(nullptr);
> ```

FYI I *believe* you can just return `nullptr`.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 107 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8744#-LBfNpHADcGlbkQLZwZl:-LBfTuFl5VybdZR-L5Cf:b-vvla80) ([raw file](https://github.com/robotlocomotion/drake/blob/6117875d0e52bf04111f8eba9e4ba46a6108b8c1/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L107)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, sdformat barks before I can even do anything. Those errors get collected by the MBP parser and then get thrown back to the user. Here I am not testing the sdformat library, just that these method do the right thing with a properly initialized `sdf::` object.
</blockquote></details>

Good enough.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8744)*

**Pull request merged**
