### PR TITLE
Add PidControlledSystem, and convert pendulum_run_swing_up to use it

### PR DESCRIPTION
**Pull request by sammy-tri**
It's come up in conversation a few times that creating a PidController and using it in System2 is a bit complicated.  This PR proposes one wrapped to make using PidController easier, and converts a pendulum example to use it.

It's of course possible that there might be a significantly better API/implementation than this which I didn't manage to come up with, feedback very much welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3742)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@liangfok for feature review

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTjPGi5O-O_lF3STCmg:b-ui3opy)*

**Comment by liangfok** [comment]
This is very nice. Just a few minor comments.

---

Reviewed 9 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQQMR7K3mqM__zrIW:-KTjQQMR7K3mqM__zrIX:b-s9c9n2) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L2)):*
> ```cpp
> 
> #include "drake/systems/framework/primitives/constant_vector_source.h"
> ```

Why is this header file at the very top?

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQZvNZ8LaR9j_NiaE:-KTjQZvNZ8LaR9j_NiaF:bpr9ky2) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L11)):*
> ```cpp
> #include "drake/common/eigen_matrix_compare.h"
> #include "drake/examples/Pendulum/pendulum_swing_up.h"
> #include "drake/examples/Pendulum/pendulum_system.h"
> ```

Nit: alpha sort this.

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQTgtCULvVVO5fGyN:-KTjQTgtCULvVVO5fGyO:b-bgabss) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L15)):*
> ```cpp
> #include "drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h"
> #include "drake/systems/analysis/simulator.h"
> #include "drake/systems/controllers//pid_controlled_system.h"
> ```

"//" should be "/".

---

*[drake/systems/controllers/pid_controlled_system.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjRm9zllQlCPe7-xUs:-KTjRm9zllQlCPe7-xUt:bym71t4) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L23)):*
> ```objc
> ///
> /// * The first input port must be all of the control inputs to the
> /// * system (size N)
> ```

BTW: nit: missing period at end of sentence.

---

*[drake/systems/controllers/pid_controlled_system.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjR_czCxEvoENPe_s5:-KTjR_czCxEvoENPe_s6:bm1vzd3) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L25)):*
> ```objc
> /// * system (size N)
> ///
> /// * The first output port must be of at least size N*2, where the
> ```

BTW: nit: missing spaces around "*".

---

*[drake/systems/controllers/pid_controlled_system.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSASk1OOTM-QXkHkW:-KTjSASk1OOTM-QXkHkX:b-cqg5bh) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L43)):*
> ```objc
>   /// @param[in] Kd the derivative constant.
>   PidControlledSystem(std::unique_ptr<System<T>> system,
>                       const T& Kp, const T& Ki, const T& Kd);
> ```

Can we generalize these gains to be vectors? I'm fairly sure we're going to encounter situations where each control signal will need to employ different gains.

Since `gain.h` and `pid_controller.h` both assume the gain is a constant, I've marked this comment as satisfied and filed #3743.

---

*[drake/systems/controllers/pid_controlled_system.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSRMGo1mdA8R8Q70Y:-KTjSRMGo1mdA8R8Q70Z:bym71t4) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L46)):*
> ```objc
>   ~PidControlledSystem() override;
> 
>   // System<T> overrides
> ```

BTW: nit: missing period at end of sentence.

---

*[drake/systems/controllers/pid_controlled_system.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSVROJ_2UTIrPpK59:-KTjSVROJ_2UTIrPpK5A:b-givcrv) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L49)):*
> ```objc
>   bool has_any_direct_feedthrough() const override;
> 
>   System<T>* system() { return system_; }
> ```

BTW: nit: would `get_system()` be more clear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTjUnI3MI1X9fPIdu23:b-q9h2z0)*

**Comment by sammy-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQQMR7K3mqM__zrIW:-KTjZ0T7dAptEiZcdYQk:b-umysj) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Why is this header file at the very top?
</details>
Done.  (it was unused, along with some other headers)

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQZvNZ8LaR9j_NiaE:-KTjZ5EGR3tmvA9T0o2v:bcoxic7) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L11)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Nit: alpha sort this.
</details>
Which part is out of order?  

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQTgtCULvVVO5fGyN:-KTjZCD6jHcf2ka0gZV4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "//" should be "/".
</details>
Done.

---

*[drake/systems/controllers/pid_controlled_system.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjRm9zllQlCPe7-xUs:-KTjZK7_nOYeOiNHdgY2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: missing period at end of sentence.
</details>
Done.

---

*[drake/systems/controllers/pid_controlled_system.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjR_czCxEvoENPe_s5:-KTjZKbGGD9uTW5fxhP4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: missing spaces around "*".
</details>
Done.

---

*[drake/systems/controllers/pid_controlled_system.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSRMGo1mdA8R8Q70Y:-KTjadzRZvQbYOYTJd7Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L46)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: missing period at end of sentence.
</details>
Done.

---

*[drake/systems/controllers/pid_controlled_system.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSVROJ_2UTIrPpK59:-KTjgZBIEqIOlZmpKzbV:bybriit) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L49)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: would `get_system()` be more clear?
</details>
I'm not sure...  We don't seem to be particularly consistent about accessor names and if get_ is preferred to just the variable name.  I'm having some difficulty finding any clarity from the style guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review

---

Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTjzc1p_vXbEWEe4Rcq:buasbda)*

**Comment by liangfok** [comment]
Just one last blocking comment.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Pendulum/pendulum_run_swing_up.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjQZvNZ8LaR9j_NiaE:-KTk1fIfFClTc65jq5dw:b-vr2agh) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/examples/Pendulum/pendulum_run_swing_up.cc#L11)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Which part is out of order?  
</details>
Sorry, my mistake. I was confused by a similar pair of includes in `pendulum_swing_up.cc` (see my new comment in that file).

---

*[drake/examples/Pendulum/pendulum_swing_up.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTk2U6ZRNem81DluNoZ:-KTk2U6ZRNem81DluNo_:b7gjl4x) ([raw file](https://github.com/robotlocomotion/drake/blob/63a2c6e4fcd8650d1bcfe3d7d4301824be4554a6/drake/examples/Pendulum/pendulum_swing_up.cc#L10)):*
> ```cpp
> #include "drake/examples/Pendulum/gen/pendulum_state_vector.h"
> #include "drake/examples/Pendulum/pendulum_system.h"
> #include "drake/examples/Pendulum/pendulum_swing_up.h"
> ```

Alpha sort this (`pendulum_system.h` goes after `pendulum_swing_up.h`.)

---

*[drake/systems/controllers/pid_controlled_system.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSVROJ_2UTIrPpK59:-KTk1uYA6WHaWLQ0jFjC:b-jg2zcb) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L49)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I'm not sure...  We don't seem to be particularly consistent about accessor names and if get_ is preferred to just the variable name.  I'm having some difficulty finding any clarity from the style guide.
</details>
I'll leave it to your discretion​ since I agree the style guide is unclear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTk2lvJzfOBBmthsisA:blx4jyx)*

**Comment by sammy-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/pendulum_swing_up.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTk2U6ZRNem81DluNoZ:-KTk32kVQPzCnu1QEa2h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63a2c6e4fcd8650d1bcfe3d7d4301824be4554a6/drake/examples/Pendulum/pendulum_swing_up.cc#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Alpha sort this (`pendulum_system.h` goes after `pendulum_swing_up.h`.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTkAtJqugq6ggHHd7_G:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSASk1OOTM-QXkHkW:-KTkaHerqIM0N_iu51-m:bxm7fwl) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Can we generalize these gains to be vectors? I'm fairly sure we're going to encounter situations where each control signal will need to employ different gains.
> 
> Since `gain.h` and `pid_controller.h` both assume the gain is a constant, I've marked this comment as satisfied and filed #3743.
</details>
I would update the comments to: the first input port is the feedforward torque, and the second input port is the desired state. The output port is the state of the system that is being controlled.
Another general question is why are we doing u = -k*(x - x_desired) rather than u = k*(x_desired - x)? The first one is probably what appears in the text book, but the second onee requires fewer blocks and is less confusing to read. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by sammy-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSASk1OOTM-QXkHkW:-KTkeLBLvz4O-jCQt8ZH:bjuwr40) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L43)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> I would update the comments to: the first input port is the feedforward torque, and the second input port is the desired state. The output port is the state of the system that is being controlled.
> Another general question is why are we doing u = -k*(x - x_desired) rather than u = k*(x_desired - x)? The first one is probably what appears in the text book, but the second onee requires fewer blocks and is less confusing to read. 
</details>
Updated class comments above, PTAL.

I don't actually know why we've chosen the internal formulation which is in used.  I copied it from controlled_spring_mass_system.cc and kuka_demo.cc.  (yeah, that's not a very good justification)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by sherm1** [comment]
Due to massive overload and my many character flaws, I'm punting to Tuesday's platform reviewer. +@david-german-tri -@sherm1

---

Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTm1NmGxgt61VCTAb6b:baajjcd)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/pid_controlled_system.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KTjSASk1OOTM-QXkHkW:-KToFEkFKwK8u5PG_qoD:bi7374o) ([raw file](https://github.com/robotlocomotion/drake/blob/64f8c89eeadb62f700dff182326b699d5cfcd0c5/drake/systems/controllers/pid_controlled_system.h#L43)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Updated class comments above, PTAL.
> 
> I don't actually know why we've chosen the internal formulation which is in used.  I copied it from controlled_spring_mass_system.cc and kuka_demo.cc.  (yeah, that's not a very good justification)
</details>
Let's punt this to: #3761.

---

*[drake/systems/controllers/pid_controlled_system.h, line 33 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToCYNOkP8F8yBA_7JB:-KToCYNOkP8F8yBA_7JC:b-pyicw) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L33)):*
> ```objc
> /// output port with the following properties:
> ///
> /// * The first input port is the control input to the system
> ```

To be consistent with the second bullet, consider replacing "control input to" with  "actual state of".

---

*[drake/systems/controllers/pid_controlled_system.h, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToCLGS_N5K-EY16VK1:-KToCLGT_WsWMDIbXgrk:b-3rhh5l) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L36)):*
> ```objc
> /// * (e.g. feedforward torque).
> ///
> /// * The second input port is is the desired state of the system.
> ```

"is is" should be "is".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by sammy-tri** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 33 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToCYNOkP8F8yBA_7JB:-KToK9wWJq44x6Vh3ILp:bbpthf8) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L33)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> To be consistent with the second bullet, consider replacing "control input to" with  "actual state of".
</details>
The first input isn't the actual state, it's the system input before any corrections from the PidController.  In the case of the example in pendulum_run_swing_up, the input is the calculated tau from trajectory optimization.

---

*[drake/systems/controllers/pid_controlled_system.h, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToCLGS_N5K-EY16VK1:-KToKXNQxKprrJgyScsk:bpfq9n8) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L36)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "is is" should be "is".
</details>
Done.  (it's like I need a custom local lint rule for this one)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by liangfok** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 33 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToCYNOkP8F8yBA_7JB:-KToMJA3teC0laAukLB-:b186dzo) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L33)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> The first input isn't the actual state, it's the system input before any corrections from the PidController.  In the case of the example in pendulum_run_swing_up, the input is the calculated tau from trajectory optimization.
</details>
Oh I see. In that case, can you add "feed forward" before "control"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by david-german-tri** [comment]
Reviewed 5 of 9 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHIY74b7SW0Ld_rku:-KToHIY74b7SW0Ld_rkv:b-jjm778) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L1)):*
> ```objc
> #pragma once
> ```

Please include some direct test coverage.

---

*[drake/systems/controllers/pid_controlled_system.h, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHDmcaiX3p0xDsMBc:-KToHDmdcV_UlCSfPJ7-:b-d08aql) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L60)):*
> ```objc
>   ~PidControlledSystem() override;
> 
>   // System<T> overrides.
> ```

Why are you overriding this?  Diagram should deduce it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHIY74b7SW0Ld_rku:-KTou0DWiIBsJMsXH1s_:bifkbso) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please include some direct test coverage.
</details>
Should I assume from your use of the word "direct" that converting another example (e.g. controlled_spring_mass_system and it's associated test would not be considered adequate to resolve this defect? 

---

*[drake/systems/controllers/pid_controlled_system.h, line 33 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToCYNOkP8F8yBA_7JB:-KTovDS9AwL8OZ3IQFlQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L33)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Oh I see. In that case, can you add "feed forward" before "control"?
</details>
Done.

---

*[drake/systems/controllers/pid_controlled_system.h, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHDmcaiX3p0xDsMBc:-KTosQq8bQ0zSvmVcB_R:b-m6sdz4) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L60)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why are you overriding this?  Diagram should deduce it.
</details>
Because PidControlledSpringMassSystem overrode it to false.  I'm starting to think some of our existing examples can be slightly misleading.  Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 33 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToyd41yIiXWNPf0_4v:-KToyd41yIiXWNPf0_4w:b4q5441) ([raw file](https://github.com/robotlocomotion/drake/blob/4882f37b9fccd72258da6ff1e71371bb0ace6bb0/drake/systems/controllers/pid_controlled_system.h#L33)):*
> ```objc
> /// output port with the following properties:
> ///
> /// * The first input port is the feed forward control input to the
> ```

BTW, I'm now wondering whether "portion of the" should go before "control" to make the sentence extra clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHDmcaiX3p0xDsMBc:-KTp-nOt4UWJTGAwBi6d:bt75ldb) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L60)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Because PidControlledSpringMassSystem overrode it to false.  I'm starting to think some of our existing examples can be slightly misleading.  Removed.
</details>
Ha!  Yes, I will take the TODO to make it `final` on Diagram.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHIY74b7SW0Ld_rku:-KTp06DK4O0aHEDKEAiI:b1y7ezv) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L1)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Should I assume from your use of the word "direct" that converting another example (e.g. controlled_spring_mass_system and it's associated test would not be considered adequate to resolve this defect? 
</details>
Yes, I'm afraid so.  It won't be obvious to someone modifying or deleting an example that they're damaging test coverage for a piece of shared infrastructure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHIY74b7SW0Ld_rku:-KTpAKSOKXl_-WZZ6UsP:b-z74xw1) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Yes, I'm afraid so.  It won't be obvious to someone modifying or deleting an example that they're damaging test coverage for a piece of shared infrastructure.
</details>
controlled_spring_mass_system (and test) lands in drake/systems/analysis/test after #3682, not examples, but I suppose I see your point.  I can probably construct a reasonably trivial system (maybe just a ConstantVectorSource feeding a PidControlled Gain?  I'll have to think about it) as a throwaway for this task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTpFb-bdZFOaIm4SR52:bg7igkv)*

**Comment by sammy-tri** [comment]
Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-KToHIY74b7SW0Ld_rku:-KTtR2OhqH4toTouvdG6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e818a8ac16549be930bb9a302d355538abfca0ea/drake/systems/controllers/pid_controlled_system.h#L1)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> controlled_spring_mass_system (and test) lands in drake/systems/analysis/test after #3682, not examples, but I suppose I see your point.  I can probably construct a reasonably trivial system (maybe just a ConstantVectorSource feeding a PidControlled Gain?  I'll have to think about it) as a throwaway for this task.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Comment by david-german-tri** [comment]
:lgtm: thanks!

---

Review status: 6 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742#-:-KTtr5K9wqXlIRdYNGn2:brfqlux)*

**Comment by liangfok** [comment]
Reviewed 5 of 5 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3742)*

**Pull request merged**
