### PR TITLE
Reintroduce the schunk_wsg_lift_test.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change should not merge until CI specifies `--test_flag_filters=-nodebug` for the debug-mode builds.  @jamiesnape @BetsyMcPhail 

@sammy-tri for feature and platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5108)

### CODE REVIEW

**Comment by david-german-tri** [comment]
https://github.com/RobotLocomotion/drake-ci/commit/705668d0e260f80a3da85a910cab43a918709c82 thanks @jamiesnape !

**Comment by david-german-tri** [comment]
Debug-mode build on CI: https://drake-jenkins.csail.mit.edu/view/Bazel/job/linux-gcc-bazel-experimental/1301/

**Comment by david-german-tri** [comment]
Huh:

```
18:22:46 Unrecognized option: --test_flag_filters=-nodebug
```

**Comment by david-german-tri** [comment]
Oh, it should be `--test_tag_filters`.  :man_facepalming: That'll break continuous.  I'll PR a fix.

**Comment by david-german-tri** [comment]
Take two, with https://github.com/RobotLocomotion/drake-ci/pull/79....

https://drake-jenkins.csail.mit.edu/view/Bazel/job/linux-xenial-gcc-bazel-experimental/1325/

**Comment by david-german-tri** [comment]
^ Failures are unrelated and preexisting (currently being discussed on Slack #buildcop)

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-:-KcYhehMiB7d9uFzfpod:bnfp4nl)*

**Comment by david-german-tri** [comment]
I'm reworking this so that the test will be disabled in `-c dbg`, even if one doesn't inject the `-nodebug` filter.

**Comment by david-german-tri** [comment]
Done.  +@jwnimmer-tri, please take a look per discussion in Slack?

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/schunk_wsg/BUILD, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-KcYtL_mhqqALS0uInQ4:-KcYtL_nXbGGfdZbf71V:b-flp573) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e4f6ddf3905d9e8469ffb73597d623a42d1f46/drake/examples/schunk_wsg/BUILD#L44)):*
> ```Python
>     ],
>     # This test is prohibitively slow with --compilation_mode=dbg.
>     nodebug = True,
> ```

BTW This option should be rare, so could we make the name ever more descriptive?  `disable_in_compilation_mode_dbg=True` or something?

---

*[tools/drake.bzl, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-KcYt8-NvN2Gg1VtmnCd:-KcYt8-NvN2Gg1VtmnCe:bch2wrd) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e4f6ddf3905d9e8469ffb73597d623a42d1f46/tools/drake.bzl#L77)):*
> ```Python
>     By default, sets name="test/${name}.cc" per Drake's filename convention.
> 
>     """
> ```

Please add API doc here for the new param.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-:-KcYtZL4hU8Usmq8_6qW:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/schunk_wsg/BUILD, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-KcYtL_mhqqALS0uInQ4:-KcZ6foTnm1npizjDafM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e4f6ddf3905d9e8469ffb73597d623a42d1f46/drake/examples/schunk_wsg/BUILD#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This option should be rare, so could we make the name ever more descriptive?  `disable_in_compilation_mode_dbg=True` or something?
</blockquote></details>

Done.

---

*[tools/drake.bzl, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-KcYt8-NvN2Gg1VtmnCd:-KcZ6e8LJWrJmt0I29aQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e4f6ddf3905d9e8469ffb73597d623a42d1f46/tools/drake.bzl#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add API doc here for the new param.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5108)*

**Comment by jwnimmer-tri** [comment]
:lgtm: :woohoo:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5108#-:-KcZ6sKZ31UpJXoHwPnn:b-q4beo2)*

**Comment by david-german-tri** [comment]
Take three, with RobotLocomotion/drake-ci#80

https://drake-jenkins.csail.mit.edu/view/Bazel/job/linux-xenial-gcc-bazel-experimental/1341

**Comment by david-german-tri** [comment]
...and it works!

@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
Bazel builds are passing.  A few other builds are wedged in Jenkins for some reason, but they don't matter.  Override-merging.

**Pull request merged**
