### PR TITLE
Adding SDF model of Transcendesk 55” standing desk.

### PR DESCRIPTION
**Pull request by Lucy-tri**
For use in PAL office.
+@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3311)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
@hongkai-dai this is the model of the desk for the "sweets".

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQS-_kwh9eXZ3oUg9II:bvv6xdl)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQS3Hu-XNVGo5vPl2ll:bnfp4nl)*

**Comment by Lucy-tri** [comment]
+@david-german-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQS3fPHMKJozXsuZj6E:bdph6cr)*

**Comment by Lucy-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQS8RfnoGwOxBDd1NrD:bvi7gpa)*

**Comment by Lucy-tri** [comment]
First build failed with this:
15:55:03 Extracting Ninja for Windows...
15:55:03 x ninja.exe
15:55:03 CMake Error: Problem with archive_write_header(): Can't unlink already-existing object
15:55:03 CMake Error: Current file: ninja.exe
15:55:03 CMake Error: Problem extracting tar: C:/Users/Administrator/workspace/experimental/0b4ef046/ninja-win.zip
15:55:03 
15:55:03 CMake Error at ci/ctest_driver_script.cmake:208 (message):
15:55:03   *** CTest Result: FAILURE BECAUSE EXTRACTING NINJA FOR WINDOWS WAS NOT
15:55:03   SUCCESSFUL

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQS948Is0-FLWAHfb7j:b-yj9okv)*

**Comment by liangfok** [comment]
Sounds like we need to fine a new "Mysterious CI Failure: Foo" issue.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQSAJTtYtL57PQHANrD:b21ro0p)*

**Comment by liangfok** [comment]
Can you post the URL to the console log showing the above error?  I'll create a new "Mysterious CI Failure" ticket to track it.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQSBRWS_M1iekaXVyuF:bh82qkb)*

**Comment by Lucy-tri** [comment]
This PR is to add a file that doesn't get compiled or used (yet), so it should not block on build failures, but I thought I'd retest anyway.
Console log showing error:
https://drake-jenkins.csail.mit.edu/job/experimental/compiler=msvc-ninja-32,label=windows,type=debug/lastFailedBuild/console 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQSBPieOCrKSya_Hiug:bed47tx)*

**Comment by liangfok** [comment]
Thanks: https://github.com/RobotLocomotion/drake/issues/3312

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQSBxvXW_jmFnbI-hnL:b-m3dxeq)*

**Comment by Lucy-tri** [comment]
Photos of the table in Slack: manipulation

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQSJuvKQ6Qqeo-BrDDI:bowjzpk)*

**Comment by david-german-tri** [comment]
There's nothing here to platform review, so auto- :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3311#-:-KQSRZ0knihBjPuDAVgD:b-vd2boq)*

**Pull request merged**
