### PR TITLE
Add Clarabel to preferred_solvers in MinimumUniformScalingToTouch

### PR DESCRIPTION
**Pull request by sadraddini**
Following up on https://github.com/RobotLocomotion/drake/pull/20663

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20677)

### CODE REVIEW

**Comment by sadraddini** [comment]
+@hongkai-dai for feature review please.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@EricCousineau-TRI for platform review please, thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20677#-:-NldB1If75ccmZqRwSxp:b-949s7v)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sadraddini)

**Comment by sadraddini** [comment]
I don't have permission for labels/directives

**Comment by sadraddini** [comment]
got it thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20677#-:-NldYZDX6OiZNPi7KOMc:bhm0jc2)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

**Pull request merged**
