### PR TITLE
Xenial setup

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Add a xenial dependency, and fix assorted script bugs and nits.

Some time Friday, the super-build of master (Xenial, no matlab, everything else default, clang, ninja) started failing, wanting libxmu-dev.

I went to add the package to the prereq script, and this PR happened ... ;)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3508)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
I don't expect CI to do anything for me, since this prereq script is 16.04 only and AFAIK we have no 16.04 CI yet.

**Comment by rpoyner-tri** [comment]
+@david-german-tri for feature review
+@sherm1 (today's on-call) for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3508#-:-KS2KsEex0Ly4NHDMqNh:b3mgxih)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3508#-:-KS2KxvSVc570hCvmdze:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: though FWIW, I liked the hair (made it easier to copy-paste the list to my terminal).

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3508#-:-KS2NJgnRIo4024yHSGY:b-pply3s)*

**Comment by rpoyner-tri** [comment]
-@sherm1 ; i think i'm pretty well covered with approvals shown above.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3508#-:-KS2OE1gBp8Zr2WNsHJ8:bxic7wb)*

**Pull request merged**
