### PR TITLE
Reduce tolerance on final position to fix open-source builds.

### PR DESCRIPTION
**Pull request by sammy-tri**
IPOPT and NLopt both require this.  oops.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3177)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3177#-:-KPPJ1TUnxK9STXrp0Wa:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3177#-:-KPPJ9-b0D-fjl3yOCVn:bnfp4nl)*

**Comment by sammy-tri** [comment]
thanks both!  Will merge once Jenkins gets through.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3177#-:-KPPJGDI4nr3mer-tiIq:b-9puplh)*

**Pull request merged**
