### PR TITLE
Renamed methods in depth_sensor for clarity.

### PR DESCRIPTION
**Pull request by nikos-tri**
Also updated occurrences in comments.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6165)

### CODE REVIEW

**Comment by liangfok** [comment]
+@liangfok for feature review. Completed first pass.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/depth_sensor.cc, line 182 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrQ16azqTUP7C_n_rq:-KkrQ16azqTUP7C_n_rr:b-85pqz4) ([raw file](https://github.com/robotlocomotion/drake/blob/a961e06c22a02782971fa35734cb58409afa894c/drake/systems/sensors/depth_sensor.cc#L182)):*
> ```cpp
>   // This is so users of this sensor can distinguish between an object at the
>   // maximum sensing distance and not detecting any object within the sensing
>   // range.
> ```

This comment should go with the method's declaration in the header file.

---

*[drake/systems/sensors/depth_sensor.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrOQMUkqClFXVSkoU5:-KkrOQMVSvFIqSSh0H3o:b-g95hvv) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L24)):*
> ```objc
> /// A simple model of an ideal depth sensor. Example real-world depth sensors
> /// include Lidar, IR, sonar, etc. The depth measurements are taken at evenly
> /// spaced pixel rows (pitch angles) and columns (yaw angles). Ray casting is
> ```

Since the methods are renamed, let's replace "pixel rows" with "pitch angles" and "columns" with "yaw angles".

---

*[drake/systems/sensors/depth_sensor.h, line 126 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrOpGgT2KrOHDwPxAb:-KkrOpGgT2KrOHDwPxAc:b-o6m2cg) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L126)):*
> ```objc
> 
>   /// Returns the number of pixel rows in the resulting depth sensor output.
>   /// This is equal to parameter `num_pitch_values` that's passed into the
> ```

`num_pitch_values` should be replaced with `DepthSensorSpecification::num_pitch_values()`.

---

*[drake/systems/sensors/depth_sensor.h, line 131 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrP2jYUAn_2dU9N4Zk:-KkrP2jYUAn_2dU9N4Zl:bdqf5z4) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L131)):*
> ```objc
> 
>   /// Returns the number of pixel columns in the resulting depth sensor output.
>   /// This is equal to parameter `num_yaw_values` that's passed into the
> ```

`num_yaw_values` should be replaced with `DepthSensorSpecification::num_yaw_values()`.

---

*[drake/systems/sensors/depth_sensor.h, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPwfT68U9kIagiB8g:-KkrPwfT68U9kIagiB8h:b4geqag) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L183)):*
The style guide specifies that this method must be named in camel case: `UpdateOutputs()`:

> The Function Names rule specifies that the names of “very cheap” methods may be all lower-case with underscores between words. It defines “very cheap” as a method that you wouldn’t hesitate calling from within a loop. We clarify that this method should have a time complexity of O(1) and be less than 5 lines long.

http://drake.mit.edu/code_style_guide.html#clarifications

---

*[drake/systems/sensors/depth_sensor.h, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPZYAzaRCf9CAwmMd:-KkrPZYAzaRCf9CAwmMe:b-kyitw5) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L185)):*
> ```objc
>   void update_outputs(SystemOutput<double> *output,
>                       const KinematicsCache<double> &kinematics_cache,
>                       const VectorX<double> &distances) const;
> ```

The style guide specifies that input parameters go first followed by output parameters:  https://google.github.io/styleguide/cppguide.html#Function_Parameter_Ordering

---

*[drake/systems/sensors/depth_sensor.h, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPDI8Ap6WzhF8cGlg:-KkrPDI8Ap6WzhF8cGlh:bruhhyn) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L186)):*
> ```objc
>                       const KinematicsCache<double> &kinematics_cache,
>                       const VectorX<double> &distances) const;
>   void apply_limits(VectorX<double>& distances) const;
> ```

Since `distances` is a mutable parameter, the style guide specifies that this parameter must be a pointer.

https://google.github.io/styleguide/cppguide.html#Reference_Arguments

---

*[drake/systems/sensors/depth_sensor.h, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPrbsats4vVJahjq0:-KkrPrbsats4vVJahjq1:b-73osf9) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L186)):*
The style guide specifies that this method must be named in camel case: `ApplyLimits()`:

> The Function Names rule specifies that the names of “very cheap” methods may be all lower-case with underscores between words. It defines “very cheap” as a method that you wouldn’t hesitate calling from within a loop. We clarify that this method should have a time complexity of O(1) and be less than 5 lines long.

http://drake.mit.edu/code_style_guide.html#clarifications

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-:-KkrPg3yAFtgIv3Vy8Te:b-aflg1g)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6165)*

**Comment by nikos-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/depth_sensor.cc, line 182 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrQ16azqTUP7C_n_rq:-KkrqFT1ejXTKXFQCV8_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a961e06c22a02782971fa35734cb58409afa894c/drake/systems/sensors/depth_sensor.cc#L182)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This comment should go with the method's declaration in the header file.
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrOQMUkqClFXVSkoU5:-KkrngmOZKRSrOGiXZ--:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Since the methods are renamed, let's replace "pixel rows" with "pitch angles" and "columns" with "yaw angles".
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 126 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrOpGgT2KrOHDwPxAb:-KkrnpSrPdpuGdj97vRE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L126)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

`num_pitch_values` should be replaced with `DepthSensorSpecification::num_pitch_values()`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 131 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrP2jYUAn_2dU9N4Zk:-Kkrnsi9LBd3xzj-UBEs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L131)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

`num_yaw_values` should be replaced with `DepthSensorSpecification::num_yaw_values()`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPwfT68U9kIagiB8g:-KkrnwD77MPCCY5tPkIm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L183)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The style guide specifies that this method must be named in camel case: `UpdateOutputs()`:

> The Function Names rule specifies that the names of “very cheap” methods may be all lower-case with underscores between words. It defines “very cheap” as a method that you wouldn’t hesitate calling from within a loop. We clarify that this method should have a time complexity of O(1) and be less than 5 lines long.

http://drake.mit.edu/code_style_guide.html#clarifications
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPZYAzaRCf9CAwmMd:-KkruitcT62SqTsL4sYp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L185)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The style guide specifies that input parameters go first followed by output parameters:  https://google.github.io/styleguide/cppguide.html#Function_Parameter_Ordering
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPDI8Ap6WzhF8cGlg:-Kkroxhf4lj31Mjg-Oe8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L186)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Since `distances` is a mutable parameter, the style guide specifies that this parameter must be a pointer.

https://google.github.io/styleguide/cppguide.html#Reference_Arguments


</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 186 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6165#-KkrPrbsats4vVJahjq0:-Kkrp2RsqRcqeAiG2UAf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d7bb9d056c965df9e0514809438e5caca9a5373/drake/systems/sensors/depth_sensor.h#L186)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The style guide specifies that this method must be named in camel case: `ApplyLimits()`:

> The Function Names rule specifies that the names of “very cheap” methods may be all lower-case with underscores between words. It defines “very cheap” as a method that you wouldn’t hesitate calling from within a loop. We clarify that this method should have a time complexity of O(1) and be less than 5 lines long.

http://drake.mit.edu/code_style_guide.html#clarifications
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6165)*

**Comment by liangfok** [comment]
I believe this PR was closed because it was replaced by #6176.

**Pull request closed without merging**
