### PR TITLE
[meshcat] Add `SetObject(TriangleSurfaceMesh)` and `SetTriangleMesh(...)`

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds support for sending triangle meshes directly to Meshcat
(e.g. without having to write them to an .obj file on disk).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077#-:-MoFBymADlJV2jXqJ9j9:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: assorted minor stuff

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077#-:-MoFZZJP4i4xlwOoPPIu:b-rhhfg9)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/meshcat.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFVPr26Vv_K4E7ywOT:-MoFVPr26Vv_K4E7ywOU:b-edwzof) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat.h#L341)):*
> ```objc
>   /** Sets a single named property of the object at the given path. For example,
>   @verbatim
>   meshcat.SetProperty("/Background", "top_color", [1.0, 0.0, 0.0]);
> ```

How is this change related to the rest of the PR?
___
*[geometry/meshcat.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFWNom7LvQFZnHK0vS:-MoFWNom7LvQFZnHK0vT:b94976m) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat.h#L341)):*
> ```
> [1.0, 0.0, 0.0]
> ```
In any case the square brackets aren't legal c++ AFAIK. Curly braces would work.
___
*[geometry/meshcat.cc, line 652 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFWxvC0wpX0O1Zl4ML:-MoFWxvC0wpX0O1Zl4MM:bl9r3a) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat.cc#L652)):*
> ```cpp
>       if (message.size() > kMaxBackPressure) {
>         drake::log()->warn(
>             "The message describing the object at {} is too large for the "
> ```

nit We now have 4 copies of this warning text (and actually the whole loop-defer block, but maybe that's harder?) -- time to refactor?
___
*[geometry/meshcat_types.h, line 468 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFT_fG0IAihaeFr6yK:-MoFT_fG0IAihaeFr6yL:b-q6f3d3) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat_types.h#L468)):*
> ```
> with int not
> ```
nit did you mean 'nor'?
___
*[geometry/test/meshcat_manual_test.cc, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFYGs7Cdfifxpd-JfD:-MoFYGs7Cdfifxpd-JfE:b-tlj8l3) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/test/meshcat_manual_test.cc#L97)):*
> ```cpp
>     for (int f = 0; f < 2; ++f) faces.emplace_back(face_data[f]);
>     const Eigen::Vector3d vertex_data[4] = {
>         {0., 0., 0.}, {0.5, 0., 0.}, {0.5, 0.5, 0.}, {0., 0.5, 0.5}};
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals says we're supposed to avoid radix points with a digit on only one side (never mind all the counterexamples everywhere in Drake).
AFAICT 0. is bad; 0 is ok.

More examples in the lines below (.9, -.25, etc.) probably need fixing.
___
*[geometry/test/meshcat_test.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFZ-zgANlDy6Az5TUB:-MoFZ-zgANlDy6Az5TUC:bxoybv1) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/test/meshcat_test.cc#L149)):*
> ```cpp
>   for (int f = 0; f < 2; ++f) faces.emplace_back(face_data[f]);
>   const Eigen::Vector3d vertex_data[4] = {
>       {0., 0., 0.}, {0.5, 0., 0.}, {0.5, 0.5, 0.}, {0., 0.5, 0.5}};
> ```

nit ditto the floating-point style defect from above.
___
*[bindings/pydrake/test/geometry_visualizers_test.py, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFZI-12abc5Xkshd0N:-MoFZI-12abc5Xkshd0O:bqltrzl) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/bindings/pydrake/test/geometry_visualizers_test.py#L111)):*
> ```Python
>             vertices=[[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1]])
>         meshcat.SetObject(path="/test/triangle_surface_mesh", mesh=mesh,
>                           rgba=mut.Rgba(.3, .3, .3), wireframe=True,
> ```

nit ditto the floating-point style defect from above. Also later in this file.

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077#-:-MoFd8eJ6NRFEH4u1EZj:b-ruv0ff)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[geometry/meshcat.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFVPr26Vv_K4E7ywOT:-MoF_pm293f8teYLVpBQ:bz8n8pk) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat.h#L341)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

How is this change related to the rest of the PR?
</blockquote></details>

Not directly... just a small documentation improvement since the code in manipulation that I've upgraded alongside this reminded me of this use case.  I was hesitant to use position as the example originally, since it's not really the recommended workflow, but at that time couldn't remember the better use case that I had.
___
*[geometry/meshcat.h, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFWNom7LvQFZnHK0vS:-MoFa6lzCpfy-Iqy64QT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat.h#L341)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> [1.0, 0.0, 0.0]
> ```
In any case the square brackets aren't legal c++ AFAIK. Curly braces would work.
</blockquote></details>

Done.
___
*[geometry/meshcat.cc, line 652 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFWxvC0wpX0O1Zl4ML:-MoFc_qPEruXNyfvB6VZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/meshcat.cc#L652)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit We now have 4 copies of this warning text (and actually the whole loop-defer block, but maybe that's harder?) -- time to refactor?
</blockquote></details>

Done.
___
*[geometry/test/meshcat_manual_test.cc, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFYGs7Cdfifxpd-JfD:-MoFaG2v6A2aytU8zETr:bsfhft7) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/test/meshcat_manual_test.cc#L97)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals says we're supposed to avoid radix points with a digit on only one side (never mind all the counterexamples everywhere in Drake).
AFAICT 0. is bad; 0 is ok.

More examples in the lines below (.9, -.25, etc.) probably need fixing.
</blockquote></details>

Done.  i know that came up before.  it's EVERYWHERE, and i don't know that I agree adding the extra zeros is always better.  i've changed the ones in this PR.

(to add to the irony, this example was copied from the triangle surface mesh code).
___
*[geometry/test/meshcat_test.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFZ-zgANlDy6Az5TUB:-MoFanub2F30fhqYiU3R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e9453f2724df787fa91f65f50deaba52a8a304d/geometry/test/meshcat_test.cc#L149)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit ditto the floating-point style defect from above.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077#-:-MoFvzJDDd0MDIw6IzdL:b-vtj4vo)* status: 4 unresolved discussions (waiting on @RussTedrake)

___
*[geometry/meshcat.cc, line 458 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFusXnCHqWQWJMz39o:-MoFusXo2wGYbzzD2hCO:b-82ob0w) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/meshcat.cc#L458)):*
> ```cpp
> 
> ```

nit These extra blank lines seem spurious.
___
*[geometry/test/meshcat_manual_test.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFr2FBDv0T_5JaKmdP:-MoFr2FD57rSGLcLTEZU:b-8o8y7u) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/test/meshcat_manual_test.cc#L100)):*
> ```cpp
>     std::vector<Eigen::Vector3d> vertices;
>     for (int v = 0; v < 4; ++v) vertices.emplace_back(vertex_data[v]);
>     TriangleSurfaceMesh<double> surface_mesh(move(faces), std::move(vertices));
> ```

nit Inconsistent `move` vs `std::move`.  Looks like the bare `move` is compiling due to ADL on the vector argument, which I'd encourage us to dis-prefer.
___
*[geometry/test/meshcat_test.cc, line 152 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFrc9i8urvJLXXPjv7:-MoFrc9jAlI4JoLHfnw8:bz9n6yx) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/test/meshcat_test.cc#L152)):*
> ```cpp
>   std::vector<Eigen::Vector3d> vertices;
>   for (int v = 0; v < 4; ++v) vertices.emplace_back(vertex_data[v]);
>   TriangleSurfaceMesh<double> surface_mesh(move(faces), std::move(vertices));
> ```

nit Inconsistent `move` vs `std::move`.  Looks like the bare `move` is compiling due to ADL on the vector argument, which I'd encourage us to disprefer.
___
*[geometry/test/meshcat_test.cc, line 157 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFrhrF6zm9ZszrQ-Ed:-MoFrhrG6T0ClMYuFizU:b5u42u6) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/test/meshcat_test.cc#L157)):*
> ```cpp
> 
>   meshcat.SetObject("triangle_mesh_wireframe", surface_mesh,
>                      Rgba(.9, 0, .9, 1.0), true, 5.0);
> ```

nit Bad indent (should be -1 space to align with `"`).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16077)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[geometry/meshcat.cc, line 458 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFusXnCHqWQWJMz39o:-MoG-TVy8DJKkcaUHB5U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/meshcat.cc#L458)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit These extra blank lines seem spurious.
</blockquote></details>

Done.
___
*[geometry/test/meshcat_manual_test.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFr2FBDv0T_5JaKmdP:-MoG-UW69bBnc9mjv5ei:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/test/meshcat_manual_test.cc#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Inconsistent `move` vs `std::move`.  Looks like the bare `move` is compiling due to ADL on the vector argument, which I'd encourage us to dis-prefer.
</blockquote></details>

Done.
___
*[geometry/test/meshcat_test.cc, line 152 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFrc9i8urvJLXXPjv7:-MoG-VYjAHg0J-i500UR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/test/meshcat_test.cc#L152)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Inconsistent `move` vs `std::move`.  Looks like the bare `move` is compiling due to ADL on the vector argument, which I'd encourage us to disprefer.
</blockquote></details>

Done.
___
*[geometry/test/meshcat_test.cc, line 157 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16077#-MoFrhrF6zm9ZszrQ-Ed:-MoG-bmZB5aMDnbn0fVZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/74f97c285e33f38d71ea7270e0657e4b0ad82366/geometry/test/meshcat_test.cc#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Bad indent (should be -1 space to align with `"`).
</blockquote></details>

Done.

**Pull request merged**
