### PR TITLE
python: document RandomGenerator use with numpy

### LINKED ISSUE #12632: python using RandomGenerator
Although we have bound `RandomGenerator` in python, we've never worked out the right way to use it if we are trying to generate random numbers in python.  But it's needed.I think the right solution is pretty natural, but the mechanics are a bit hairy.  

Right now, I can do
```
from pydrake.common import RandomGenerator
from numpy.random import RandomState

generator = RandomGenerator()
rs = RandomState(generator())

print(rs.uniform())  # etc.
```
But I think this is not sufficient, because it is creating a new `numpy.random.BitGenerator`, using the integer output of our c++ generator as the seed.  There is nothing to prevent the python random generator and the c++ generator to proceed in lock-step with each other, introducing unintended correlations.

I think the *right* solution is to do
```
from pydrake.common import RandomGenerator
from numpy.random import RandomState

generator = RandomGenerator()
rs = RandomState(generator)   #   <--- parens removed here 

print(rs.uniform())  # etc.
```
if we can make `drake.common.RandomGenerator` implement the `numpy.random.BitGenerator` interface.  This would allow `numpy.random.RandomState` (and eventually `numpy.random.Generator`, when we move to numpy 1.17) to actually use the c++ generator as it should.

I found a little about it [here](https://docs.scipy.org/doc/numpy/reference/random/extending.html#new-basic-rngs) and some of the referenced  [.pyx code here](https://github.com/numpy/numpy/blob/master/numpy/random/_mt19937.pyx#L128)

There is one more detail: in c++ we always use the default seed of RandomGenerator to produce deterministic outputs.  In python, the default behavior is that the random seed, if `None`, is [pulled from `/dev/urandom`](https://docs.scipy.org/doc/numpy/reference/random/legacy.html#numpy.random.mtrand.RandomState).  We should document this clearly.  And if users do want random runs, then give them a recommended workflow.  I'm using 
```
generator = RandomGenerator(int(time.time()))
```
for today, but the pseudo-random number people will laugh at me if they see that.  I'm sure there is a better way.

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #12632

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102#-:-MHig4_wCQW4hjzHocbP:b-qf68jg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@SeanCurtis-TRI for platform review per schedule, please.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102#-:-MHl4wNN5lv1-C009_uv:bxf7acb)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[bindings/pydrake/common/module_py.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl4_9VDTf6YoHqwdRe:-MHl4_9W3UdkEBWj2U09:b-35lit2) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L122)):*
> ```cpp
> deterministic given a single random seed.  This is accomplished by passing a
> RandomGenerator object.  To generate random numbers in numpy that are
> deterministic given the C++ random seed (see drake issue #12632 for the discussion), use e.g.
> ```

nit >80
___
*[bindings/pydrake/common/module_py.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl4hh_-ObexKfXY1A7:-MHl4hh_-ObexKfXY1A8:b30nr43) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L125)):*
> ```cpp
> 
> .. code-block:: python
>     
> ```

nit Do we need his trailing whitespace to make the docs render correctly?  If not, please remove here and 3 lines below.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: for the text (and in support of @jwnimmer-tri's comments). Surprised that the recommended pattern doesn't appear in tests.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102#-:-MHl7QS16Imyqz7DyXIz:b3a20nx)* status: 3 unresolved discussions (waiting on @RussTedrake)

___
*[bindings/pydrake/common/module_py.cc, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl7Jb75bBwXteQMkhF:-MHl7Jb89d2YFSu8O2fW:bwl3p18) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L129)):*
> ```cpp
>    random_state = numpy.random.RandomState(generator())
>    
>    my_random_value = random_state.uniform()
> ```

I'm surprised not to find this exercised anywhere in the code. Is this not under test?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/common/module_py.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl4_9VDTf6YoHqwdRe:-MIH4ZR-0qfD82OospoS:b-7rl0jd) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L122)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit >80
</blockquote></details>

done.
___
*[bindings/pydrake/common/module_py.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl4hh_-ObexKfXY1A7:-MIH4_GI8yG1LO6GxbdW:bm10wlv) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Do we need his trailing whitespace to make the docs render correctly?  If not, please remove here and 3 lines below.
</blockquote></details>

yes.  they are needed.   sphinx is obnoxious in this regard.
___
*[bindings/pydrake/common/module_py.cc, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl7Jb75bBwXteQMkhF:-MIH7trX6mvUyrRqqK6m:b6xmp1r) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L129)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm surprised not to find this exercised anywhere in the code. Is this not under test?
</blockquote></details>

I've added a test.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @RussTedrake)

___
*[bindings/pydrake/common/module_py.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl4hh_-ObexKfXY1A7:-MIJuPJ86ODYxE4An2Bq:bgtipuv) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L125)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

yes.  they are needed.   sphinx is obnoxious in this regard.
</blockquote></details>

For the record, I looked into existing instances of `.. code-block`.  `python_bindins.rst` has many instances. All of the `code-block` declarations are followed by an empty line. None of those empty lines have "trailing whitespace" (i.e., three space characters). So, that seems sufficient evidence that it *isn't* necessary and probably points to a miscommunication.
___
*[bindings/pydrake/common/module_py.cc, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MHl7Jb75bBwXteQMkhF:-MIJvd1w58v1Ae7JtdRE:b1rxsgm) ([raw file](https://github.com/robotlocomotion/drake/blob/60cedcce205c023982f7a131145c2ab9903c85da/bindings/pydrake/common/module_py.cc#L129)):*
Perhaps it's the fact that I haven't worked with the stochastic system. But the documentation says

> we aim to have computations that are fully deterministic given a single random seed.

And looking at the test, it isn't clear to me that "multiple numpy generators can be seeded from a single RandomGenerator without duplicating values" (as documented in the test) is equivalent.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102)* status: 2 unresolved discussions (waiting on @RussTedrake)

___
*[bindings/pydrake/common/test/module_test.py, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MIK20bE71OkptJC2yS7:-MIK20bE71OkptJC2yS8:brbicot) ([raw file](https://github.com/robotlocomotion/drake/blob/4af6e3ea41e3dd5c79214a160419fc7302ef514e/bindings/pydrake/common/test/module_test.py#L1)):*
> ```Python
> import numpy as np
> ```

nit `numpy` isn't in the standard library, so should go into a separate second group of imports.

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri you willing to help push this over the finish line as feature reviewer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102#-:-MWPayCe5A5emu0rcWbA:bpehqir)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
I am willing, but not sure how.

I can easily push a fix for the import order nit, but the blocking discussion is a question from you, and I don't entirely understand what you are getting at in that debate.

If you push a fix for that, I'll follow-up with the nit fix.  (Or, you could just as easily add the nit fix to your own fix, if you like too.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've marked the discussion question as resolved. Looking at it now, I'm content with what I see.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102#-:-MWUUsSpDpcMf4LeVpk5:bo4bis0)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[bindings/pydrake/common/test/module_test.py, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MIK20bE71OkptJC2yS7:-MWgRRVnDaJcqsg7mgiC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4af6e3ea41e3dd5c79214a160419fc7302ef514e/bindings/pydrake/common/test/module_test.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `numpy` isn't in the standard library, so should go into a separate second group of imports.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri as you were actively engaged in the discussion in #12632, I'd prefer leaving the squashing/merging to you as you will be better equipped to author the commit message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14102#-:-MWj0u-3-TIAt5COUKxJ:bxo3yei)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/common/module_py.cc, line 161 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MWyPTNU7S2oz42wKw6s:-MWyPTNU7S2oz42wKw6t:bj6fguf) ([raw file](https://github.com/robotlocomotion/drake/blob/68d02fa87f382745da92477603e1d7a7640cac29/bindings/pydrake/common/module_py.cc#L161)):*
> ```cpp
>     
>    generator = pydrake.common.RandomGenerator()
>    random_state = numpy.random.RandomState(generator())
> ```

Thank you both for pushing this through... i wasn't keeping up.  But one of the reasons it stalled was because i thought numpy has moved beyond `RandomState` already, no?  https://numpy.org/doc/stable/reference/random/index.html 

Do we need to update this already?

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/common/module_py.cc, line 161 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14102#-MWyPTNU7S2oz42wKw6s:-MWyhMo6Df9XITDZ6HBS:b-41wi0m) ([raw file](https://github.com/robotlocomotion/drake/blob/68d02fa87f382745da92477603e1d7a7640cac29/bindings/pydrake/common/module_py.cc#L161)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Thank you both for pushing this through... i wasn't keeping up.  But one of the reasons it stalled was because i thought numpy has moved beyond `RandomState` already, no?  https://numpy.org/doc/stable/reference/random/index.html 

Do we need to update this already?
</blockquote></details>

From a quick search, it look like numpy <= 1.16 is the last revision to prefer RandomState, with numpy >= 1.17 referring to it as the "legacy" API instead.  Ubuntu 18.04 uses numpy 1.13; Ubuntu 20.04 uses numpy 1.17; macOS tracks latest.  So this documentation is accurate for Ubuntu 18.04, i.e., most of the core drake developers, but not for other platforms.  I am fine with leaving it alone until we drop 18.04 support, but I also would not object to improving it.

**Pull request merged**
