### PR TITLE
resolves #2433

### LINKED ISSUE #2433: Error using copyfile in MATLAB
```
[[NON-XML-CHAR-0x8]Warning: RigidBodyManipulator: velocity limits are not supported yet][NON-XML-CHAR-0x8] 
[[NON-XML-CHAR-0x8]> In WarningManager/warnOnce (line 21)
  In RigidBodyManipulator/addRobotFromURDF>parseJoint (line 357)
  In RigidBodyManipulator/addRobotFromURDF>parseRobot (line 105)
  In RigidBodyManipulator/addRobotFromURDF (line 55)
  In RigidBodyManipulator (line 75)
  In runPassive (line 12)][NON-XML-CHAR-0x8] 
Constructing a new airfoil
Error using copyfile
The process cannot access the file because it is being used by another process.


Error in RigidBodyWing/onCompile (line 137)
          copyfile(which(profile),fullfile(tempdir,[filename,fileext]));

Error in RigidBodyManipulator/compile (line 720)
        [new_element, model] = model.force{i}.onCompile(model);

Error in RigidBodyManipulator/addRobotFromURDF (line 60)
model = compile(model);  % ideally this would happen on entry into any function...

Error in RigidBodyManipulator (line 75)
          obj = addRobotFromURDF(obj,filename,zeros(3,1),zeros(3,1),options);

Error in runPassive (line 12)
p = RigidBodyManipulator('Plane.URDF', options);

 

CMake Error at C:/projects/Agzs6sMa/drake/cmake/MatlabTestsRedirect.cmake:108 (message):
  [MATLAB] TEST FAILED Matlab returned 1

```
See, e.g., https://drake-cdash.csail.mit.edu/testDetails.php?test=727176&build=24472. Right now this is just on Windows.

### PR DESCRIPTION
**Pull request by RussTedrake**
@jonathan-owens -- ptal

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2449)

### CODE REVIEW

**Comment by jonathan-owens** [comment]
@RussTedrake :lgtm:, pending successful CI builds.

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jonathan-owens (Jonathan Owens) wrote…</i></summary>
> @RussTedrake :lgtm:, pending successful CI builds.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/@RigidBodyWing/RigidBodyWing.m, line 136 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2449#-KIcA2i3FG4gVJWbct22:-KIcA2i4xKqbGYeQ7tJ5:458537220) ([raw file](https://github.com/robotlocomotion/drake/blob/249381facc5e2b86b85c861959b290cd6a82b413/drake/systems/plants/@RigidBodyWing/RigidBodyWing.m#L136)):*
> ```objc
>           % copy the profile to the tmp directory and call that instead.
>           % yuck.
>           newname = [tempname,'.dat'];
> ```

(no action needed) For anyone else wondering why this isn't an error: `tempname` is a function, not a variable.  Gotta love MATLAB syntax.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2449#-:-KIcAFVIGV14mLW6_CFW:1417088721)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
