### PR TITLE
Add missing dependencies to drake.cps

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7329)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7329#-:-KxIzZZXZknn_sJKGoX9:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7329#-:-KxJRRX_MTdxnLFm_9J4:bmxilld)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7329)*

**Pull request merged**
