### PR TITLE
[tutorials] Update README.md to include deepnote/colab; add tutorial index

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #13683

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279#-:-MrXYcSa7jG8sFs8g6sW:b-bpi9p7)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Comment by RussTedrake** [comment]
I see @ericcousineau-tri appeared.  The new notebook is only a single markdown cell, but I know this will make you happy:
https://nbviewer.org/github/RussTedrake/drake/blob/deepnote_tutorials/tutorials/index.ipynb

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

@ericcousineau-tri From #13683 it looks like you are invested in the issue. Do you want to platform review it?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279#-:-MrYI1rC1HmzEp2ruTEG:bcyuct4)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[tutorials/index.ipynb, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYHjkg4iwI2bqvkFkt:-MrYHjkg4iwI2bqvkFku:b-b2zax) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/index.ipynb#L51)):*
> ```
>    ]
>   },
>   {
> ```

nit, is this empty cell necessary?
___
*[tutorials/README.md, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYCCqBE3txcb1TpMJG:-MrYCCqCD8sdipZBlvpF:bytf8sc) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L22)):*
> ```Markdown
> We currently support running the tutorials on a number of cloud notebook services:
> 
> [Deepnote](https://deepnote.com/project/Tutorials-K0_FCa7yQX2kDWBx3-2RmQ)
> ```

nit, perhaps a TODO to remind us to port this link to the `index` notebook?
___
*[tutorials/README.md, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYL-kdA0mFcGef6OC_:-MrYL-kdA0mFcGef6OCa:bglv7mk) ([raw file](https://github.com/robotlocomotion/drake/blob/8d21e1a13a14ab2651bc6ff8bc07bfda4f0e5031/tutorials/README.md#L47)):*
> ```Markdown
> it to provision a kernel and let you see the notebook.
> 
> **Warning**: `Meshcat` is not supported by Binder since port 7000 is not
> ```

nit, is this issue resolved already? I tried the `rendering_multibody_plant` tutorial on binder and it seems like MeshCat still attempts to use port 7000 with no success.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

___
*[tutorials/README.md, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYCCqBE3txcb1TpMJG:-MrYYmXgDIK-F5ztbAFV:brri2xt) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, perhaps a TODO to remind us to port this link to the `index` notebook?
</blockquote></details>

good catch.  actually, with deepnote i can go ahead and copy it up now... so have just added it.
___
*[tutorials/README.md, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYL-kdA0mFcGef6OC_:-MrYYvQ4DumR7NQtRMmV:b-wumae) ([raw file](https://github.com/robotlocomotion/drake/blob/8d21e1a13a14ab2651bc6ff8bc07bfda4f0e5031/tutorials/README.md#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, is this issue resolved already? I tried the `rendering_multibody_plant` tutorial on binder and it seems like MeshCat still attempts to use port 7000 with no success.
</blockquote></details>

You're right. I was tempted to resolve it, but stopped short for this PR.  I've restored the warning.

**Review by EricCousineau-TRI — COMMENTED** [review]
Yup, can do!
+@ericcousineau-tri for platform review

> I see @EricCousineau-TRI appeared. The new notebook is only a single markdown cell, but I know this will make you happy:

Thanks, looks good!

:lgtm: with some minor points (only one blocking)

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279#-:-MrYYJ3s5-Vo3vuU0gK3:b82gv27)* status: 5 unresolved discussions, missing label for release notes (waiting on @RussTedrake and @xuchenhan-tri)

___
*[tutorials/README.md, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYZ88x8QXNNW5OJDp4:-MrYZ88x8QXNNW5OJDp5:b4f33g1) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L79)):*
> ```Markdown
> ## For Developers
> 
> When you add a notebook, please make the first cell be a Markdown cell with the
> ```

Should this include instructions for devs to add their new notebook to `index.ipynb`?
___
*[tutorials/README.md, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrY_AMe4nblEQR6BAwL:-MrY_AMe4nblEQR6BAwM:b-x7tymc) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L87)):*
> ```Markdown
> Use this [maintainers
>   notebook](https://deepnote.com/project/Tutorials-K0_FCa7yQX2kDWBx3-2RmQ/%2F.for_maintainers.ipynb)
>   to update Deepnote once the PR has landed and the nightly binaries support
> ```

nit "support it" seems a bit ambiguous; once the PR lands, a pure-tutorial PR could be supported w/o new nightly release, thus may yield some confusion on when to update.

Consider something like "once the nightly binary includes the merged commit"?
___
*[tutorials/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYZtV43aete_rubsnq:-MrYZtV5-WOhFtCd818Z:b-tnewpj) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L88)):*
> ```Markdown
>   notebook](https://deepnote.com/project/Tutorials-K0_FCa7yQX2kDWBx3-2RmQ/%2F.for_maintainers.ipynb)
>   to update Deepnote once the PR has landed and the nightly binaries support
>   it.  Drake developers should request access through the deepnote interface if
> ```

nit They may also need to request elevated permissions, so perhaps "request access" => "request Edit access"?

For example, I do not believe I can change the default environment:


I did just request Edit access, though.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: 4 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[tutorials/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYZtV43aete_rubsnq:-MrYl2aY9HKn2zwUDlnJ:b-df46w9) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L88)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit They may also need to request elevated permissions, so perhaps "request access" => "request Edit access"?

For example, I do not believe I can change the default environment:


I did just request Edit access, though.
</blockquote></details>

I did too.
___
*[tutorials/README.md, line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYlAZx2uEPlNM7EAkt:-MrYlAZx2uEPlNM7EAku:b-uwey50) ([raw file](https://github.com/robotlocomotion/drake/blob/77f5e3bf4e47e724bb2c66e2d516d174d9cde83e/tutorials/README.md#L48)):*
> ```Markdown
> For now, users must manually add and run `!pip install drake pyngrok` in the top cell
> the notebook in order to install Drake and run the tutorial.
> 
> ```

nit, s/isnstall/install

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: 4 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: 2 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[tutorials/README.md, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYZ88x8QXNNW5OJDp4:-MrYlwiLBh_C8MJLw2e5:bc4sjck) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L79)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should this include instructions for devs to add their new notebook to `index.ipynb`?
</blockquote></details>

Done.  Good call.
___
*[tutorials/README.md, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrY_AMe4nblEQR6BAwL:-MrYm2bo6lpBG39Sr2S6:b-jcmcl) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L87)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "support it" seems a bit ambiguous; once the PR lands, a pure-tutorial PR could be supported w/o new nightly release, thus may yield some confusion on when to update.

Consider something like "once the nightly binary includes the merged commit"?
</blockquote></details>

But that is not correct.  I've tried to make it more clear.
___
*[tutorials/README.md, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrYZtV43aete_rubsnq:-MrYn-s05fHj6Pz_TJ38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L88)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I did too.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: missing label for release notes (waiting on @RussTedrake)

___
*[tutorials/README.md, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16279#-MrY_AMe4nblEQR6BAwL:-MrYr1SiBo7WHWWDJIsg:b-vhpohj) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf9c9486a7ac58534374a7d1c9ac1e308ff961e/tutorials/README.md#L87)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

But that is not correct.  I've tried to make it more clear.
</blockquote></details>

OK Looks better, thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: missing label for release notes (waiting on @RussTedrake)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279)* status: missing label for release notes (waiting on @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
Will mark as +(release notes: none) given that this is still part of the transition. We can include future PRs in release notes once the transition is more complete.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16279#-:-MrYyvapEQClztudtVqD:b-li4s2u)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
I posted a reminder about this README's policy change into our `#platform_review` slack, to increase awareness.

**Pull request merged**
