### PR TITLE
py serialize: Add mising .Finished() for no-doc case

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Minor bug when scanning code when doing #18204

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18207)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri You up for review?
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18207#-:-NFVDtYsEJHOQ6uqIh0I:be97dna)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Oops.

Yes, sure.

:lgtm: both +(release notes: fix).

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18207#-:-NFVFEBJDdyHV62RFvIy:bzcfnc)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/common/test/serialize_pybind_test.py` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18207#-NFVFUNeCS71F-VtUsKX:-NFVFUNeCS71F-VtUsKY:bs2m05o) ([raw file](https://github.com/robotlocomotion/drake/blob/f205cb763ff29a8e26f82f10197317fcf3e9fb0a/bindings/pydrake/common/test/serialize_pybind_test.py#L64)):*
> ```Python
>         self.assertSequenceEqual([(x.name, x.type) for x in fields], (
>             ("quux", float),
>         ))
> ```

Hmm, this is the **with**-docstrings test case.  Does this cover the bugfix?

Ah, yes it does because it's checking MyData1.  It's just in the wrong test function (should move up to L46 or so).

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18207)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/serialize_pybind_test.py` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18207#-NFVFUNeCS71F-VtUsKX:-NFVGVXm3o6EHmCl_EyA:b-r08yfo) ([raw file](https://github.com/robotlocomotion/drake/blob/f205cb763ff29a8e26f82f10197317fcf3e9fb0a/bindings/pydrake/common/test/serialize_pybind_test.py#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm, this is the **with**-docstrings test case.  Does this cover the bugfix?

Ah, yes it does because it's checking MyData1.  It's just in the wrong test function (should move up to L46 or so).
</blockquote></details>

Done. D'oh!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18207)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
