### PR TITLE
Update Xenial install script

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
See https://drake-jenkins.csail.mit.edu/job/linux-xenial-unprovisioned-clang-experimental/44/console
```
14:24:14 dpkg: dependency problems prevent configuration of bazel:
14:24:14  bazel depends on g++; however:
14:24:14   Package g++ is not installed.
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4782)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
Note that the setup script is currently failing due to #4748

**Comment by BetsyMcPhail** [comment]
PTAL +@jamiesnape 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-KaONuGyQ-LY5A6XUhED:b-nhvvhm)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-KaOOO883Ht741AKdRPi:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm_cancel: Actually, `clang-3.9`, `clang-format-3.9`, and `lldb-3.9` are also missing.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-KaOUh5ChxRcof0Q4qEt:b-9w5lro)*

**Comment by jamiesnape** [comment]
(remove the old `clang-format`)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-KaOVCJos50Fi6R6Q1D6:bs7jtej)*

**Comment by jamiesnape** [comment]
Also add `gfortran-5-multilib`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-KaOVW2MW5yhFaSkXXiO:b3r84l)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-KaOVkf821wUwsbUghvA:-KaOVkf821wUwsbUghvB:bsbacld) ([raw file](https://github.com/robotlocomotion/drake/blob/1b33a2dfb75bd193fa3dd4acefc7eda0418486c7/setup/ubuntu/16.04/install_prereqs.sh#L87)):*
> ```Shell
> libqt4-opengl-dev
> libqwt-dev
> libterm-readkey-perl
> ```

This can be removed now. We do not support the Gurobi interactive download anymore.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-KaOVsXv4cJQKy5tq5PY:-KaOVsXv4cJQKy5tq5PZ:b-o81tae) ([raw file](https://github.com/robotlocomotion/drake/blob/1b33a2dfb75bd193fa3dd4acefc7eda0418486c7/setup/ubuntu/16.04/install_prereqs.sh#L92)):*
> ```Shell
> libvtk5-dev
> libvtk5-qt4-dev
> libwww-perl
> ```

Also can be removed for the same reasons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782)*

**Comment by jamiesnape** [comment]
Sorry, I missed that `clang-3.9` is there.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-KaOWI_YKaxab5-GZICZ:b7v8m1z)*

**Comment by BetsyMcPhail** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-KaOVkf821wUwsbUghvA:-KaOgNdqEBC2DXnQIR4s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b33a2dfb75bd193fa3dd4acefc7eda0418486c7/setup/ubuntu/16.04/install_prereqs.sh#L87)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This can be removed now. We do not support the Gurobi interactive download anymore.
</blockquote></details>

Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-KaOVsXv4cJQKy5tq5PY:-KaOgORapsc8yIM9Z9YC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b33a2dfb75bd193fa3dd4acefc7eda0418486c7/setup/ubuntu/16.04/install_prereqs.sh#L92)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Also can be removed for the same reasons.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782)*

**Comment by jwnimmer-tri** [comment]
IIRC The bare clang-format was added on purpose.  Check the git history.

**Comment by jamiesnape** [comment]
@jwnimmer-tri Not seeing anything to suggest that here.
@liangfok What was the reason for adding `clang-format-3.8` over the 3.9 versions of all the other LLVM tools?

**Comment by jwnimmer-tri** [comment]
I meant 9ac920a7ccf6625b0237df345447461446ba0848.  It provides `clang-format` on the path, which is assumed by various other documentation.

**Comment by jamiesnape** [comment]
Ok, that is non-obvious from the history. @BetsyMcPhail Sorry, I guess it needs to be `clang-format` then.

**Comment by jwnimmer-tri** [comment]
(Agreed, sorry.  The "why" was never written down, even if the issue that the commit's PR closed.)

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4782#-:-Kah4iXtQMbYjfkJNiUW:bnfp4nl)*

**Pull request merged**
