### PR TITLE
[multibody] Reduce build time

### PR DESCRIPTION
**Pull request by rpoyner-tri**
The primary move here is to submerge scene_graph.h from
multibody_plant.h to the .cc file. The consequences are:

 * Several forward declarations in multibody_plant.h
 * Numerous .cc files needed to add include statements
 * AddMultibodyPlantSceneGraph:
   * Use overload instead of default arguments
   * Gives same API without compile errors about destructors

This branch cuts my Puget build time by about 13%.
~735s ==> ~645s.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
This patch is definitely more in the food for thought category than an actual recommended course of action. I hope it gives some concrete form to what might help speed up build times.

I spent some quality time with profile output of `bazel` (entire builds) and `clang` (worst critical-path compilation units). Some things I thought might help did not, but (in general) lowering include statements should help, if the cost isn't too high.

FYI @russtedrake @jwnimmer-tri @sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwD6DRJEH2Iw1F2A8T9:bx67pej)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
Ugh. Having trouble repeating previous experiment results. This will take awhile to sort through,

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwDQyfaAjAhUe_QACZJ:b-wht951)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16623#-MwDfMjOEO2kcE2ul48S:-MwDfMjOEO2kcE2ul48T:b-p66nb9) (no related file):*
Here is what i think is happening with timing experiments. It looks to me like the same source tree can have fairly different looking results from `bazel analyze-profile` and the flamegraph, based on how parallel scheduling of tasks shakes out. So far, I've seen two "modes". In one, the "critical path" from analyze profile is dominated by compiling bindings/pydrake/multibody/tree_py.cc and testing py/install_test. The other is dominated by  compiling some .c file from PETSc, and by the petsc_symmetric_block_sparse_matrix_test. These experiments were done like:

    $ bazel clean --expunge
    $ bazel test --profile=OUTFILE //...

I'm thinking to do some profile runs with `build` instead of `test` as the verb.

---

**Comment by jwnimmer-tri** [comment]
I'd say that for evaluating a physical dependency fixup to `multibody_plant.h`, cold builds of the full tree are an out-of-nominal use case.  Assuming our objective is to improve developer efficiency, then the latency of unit test responses within the current package is probably the most important metric.

Thus, my preferred metric here would be the latency of an incremental build of `bazel build //multibody/plant/...` in the presence of an object-code-affecting change to the plant header (e.g., adding a runtime `DRAKE_DEMAND` to an inline method).

**Review by rpoyner-tri — COMMENTED** [review]
Based on your preferred metric, I'm going to have to conclude this effort was a failure.

I used 3 commit hashes for comparison.
* master as of c966e648e66b094b2fceef2d05ff7a448525ca30 Call this `m` (master).
* this patch (r1), rebased to above master. Call this `o` (original).
* a further revision, putting back full includes for classes named in public API. Call this `c` ("climbdown").

It turns out the total time of an incremental build is dominated by compiling multibody_plant.cc, plus whatever happened to land on the same thread. Since the scheduling appears to have some randomness to it, the total time is meaningless as a measure. So we are reduced to looking only at the compile time for multibody_plant.cc.
* m:    68.052 s   98.26%   action 'Compiling multibody/plant/multibody_plant.cc'
* o:    69.110 s   98.25%   action 'Compiling multibody/plant/multibody_plant.cc' :shrug: 
* c:    78.223 s   98.44%   action 'Compiling multibody/plant/multibody_plant.cc' :scream: 

I haven't gone back through those results with either detailed code reading or clang profiling to try to understand things any further.

I still think it might be possible to reap benefits of fiddling with headers where there are small wins across multiple TUs, but I doubt I have the patience to do the experiments. Watching builds run all day is brutal. :)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwE3t2P1b8VJEi8l0XG:b-lys009)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by jwnimmer-tri** [comment]
Huh.  I'm initially surprised that it can chew through 30+ unit tests object files before finishing `multibody_plant.o`, but thinking more, I guess that's just life on a 40+ core machine.

**Comment by rpoyner-tri** [comment]
[bazel_profile-cddi.gz](https://github.com/RobotLocomotion/drake/files/8103089/bazel_profile-cddi.gz)
[bazel_profile-oddi.gz](https://github.com/RobotLocomotion/drake/files/8103090/bazel_profile-oddi.gz)
[bazel_profile-mddi.gz](https://github.com/RobotLocomotion/drake/files/8103091/bazel_profile-mddi.gz)

**Review by rpoyner-tri — COMMENTED** [review]
Yes. The long-pole nature is pretty obvious from the trace plots. I'll see about attaching some data files.

... could not drag-drop them through reviewable, but direct to github PR comment worked.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwJ2udw20Fu5MhHe4qJ:bpf2hfa)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
BTW, file `ddi` in the filenames stands for "DRAKE_DEMAND() incremental". Add a statement, then do an incremental build. The m, o, and c represent the patch sets as listed above. I'll try pushing the updated branch.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwJ3piM39ExnUlFxacP:b-lgmhz3)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
... here's the DRAKE_DEMAND() tweak used:

```
diff --git a/multibody/plant/multibody_plant.h b/multibody/plant/multibody_plant.h
index 7c41d8e24b..4b1411e9d3 100644
--- a/multibody/plant/multibody_plant.h
+++ b/multibody/plant/multibody_plant.h
@@ -880,6 +880,7 @@ class MultibodyPlant : public internal::MultibodyTreeSystem<T> {
   const RigidBody<T>& AddRigidBody(
       const std::string& name, ModelInstanceIndex model_instance,
       const SpatialInertia<double>& M_BBo_B) {
+    DRAKE_DEMAND(!name.empty());
     DRAKE_MBP_THROW_IF_FINALIZED();
     // Make note in the graph.
     multibody_graph_.AddBody(name, model_instance);
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwJD9Tl2MRSpcPQyeyd:bx1m0zj)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by rpoyner-tri — COMMENTED** [review]
The numbers make more sense to me now. Since all the above tests measure is the compile time of the multibody_plant TU itself, of course demoting any include statement wil have at-best no effect. The same code burden exists, because nothing was removed from the TU that matters. The only benefit this kind of patch could have is to TUs that include multibody_plant.h, but don't care about scene_graph.

I don't intend to work this any more now; will close.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16623#-:-MwbTtliA7GHm-kpk8uq:bfvwdq1)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Pull request closed without merging**
