### PR TITLE
Use yaml-cpp from system on Xenial and homebrew on MacOS.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
yaml-cpp is included in the setup scripts already.

Linux 🐧:
https://github.com/RobotLocomotion/drake/blob/f3569bbe1165322f0e1b66d63759d492e6c028a8/setup/ubuntu/16.04/install_prereqs.sh#L95

MacOS 🍎:
https://github.com/RobotLocomotion/drake/blob/f3569bbe1165322f0e1b66d63759d492e6c028a8/setup/mac/install_prereqs.sh#L61

Using the system version cuts down on the size of libdrake.so and improves linking compatibility when using Drake within systems that use the system yaml-cpp version.

This change was previously introduced in #7352 and later reverted (#7403) due to issues with the MacOS build. Other portions of that original pull request were reintroduced in #7453 

I'm opening the PR again now to check in against MacOS CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7602)

### CODE REVIEW

**Comment by clalancette** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by nuclearsandwich** [comment]
Retesting since the macos failures appear to be related to https://github.com/RobotLocomotion/drake/pull/7439 and were fixed in https://github.com/RobotLocomotion/drake/pull/7632

@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by nuclearsandwich** [comment]
+@jamiesnape for feature review

I think you probably have the best notion of whether or not this is ready to go back in at the moment. Thanks!

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
IIRC the failures were with the CMake builds, so we should check those.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 289 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7602#-L0kY1_BUD9GhgXJtKMy:-L0kY1_BUD9GhgXJtKMz:b-o0l0c5) ([raw file](https://github.com/robotlocomotion/drake/blob/d5015662a28dc9cf2b0789d1ce8d2bee9afce6ea/WORKSPACE#L289)):*
> ```Python
> 
> pkg_config_package(
>     name = "yaml_cpp",
> ```

BTW I don't it would too painful to rename this to `yaml-cpp` to match the convention of almost all our calls to `pkg_config_package`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7602#-:-L0kZ9mjphZbvl1CUbtT:baz22mg)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7602)*

**Comment by jamiesnape** [comment]
Looks like the `pkg-config` file for `yaml-cpp` is not correct.

**Comment by jamiesnape** [comment]
Create a target that has `@yaml-cpp` and `@boost` in its `deps`, link to that instead of `@yaml-cpp`, and upstream a fix to https://github.com/jbeder/yaml-cpp.

**Comment by jamiesnape** [comment]
Looks like maybe the Linux version does not use Boost, so you may need a `select`.

**Comment by jamiesnape** [comment]
`drake.cps` is also missing a call to `FindBoost.cmake`. I will PR that separately.

**Comment by nuclearsandwich** [comment]
@jamiesnape @jwnimmer-tri https://github.com/RobotLocomotion/drake/pull/7602/commits/0b07c6abf94adad73bbadb8e3a44535c09562e11 adds an attempt at the Option (3) we discussed [in Slack](https://drakedevelopers.slack.com/archives/C2PMBJVAN/p1515097720000003).

For reasons I don't understand, Bazel is trying to get the file from `external/tools/workspace/yaml-cpp` rather than `tools/workspace/yaml-cpp` and I'm not sure how to either correct this or make sure that the file is present in that directory within the build context.

```
steven@steven-workstation:~/o/d/drake ❯ bazel build //...                                                                                                                                                                                                              [123/761]
ERROR: /home/steven/osrf/draken/drake/automotive/maliput/multilane/BUILD.bazel:75:1: no such package '@yaml_cpp//': Traceback (most recent call last):
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/pkg_config.bzl", line 172
                setup_pkg_config_package(repo_ctx)
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/pkg_config.bzl", line 168, in setup_pkg_config_package
                _write_build(repo_ctx, cflags.value, linkopts.val...)
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/pkg_config.bzl", line 30, in _write_build
                write_build(repo_ctx, includes, defines, linkopts)
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/common.bzl", line 66, in write_build
                repo_template(repo_ctx, "BUILD", repo_ctx.attr.bui..., ...)
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/wrapped_ctx.bzl", line 38, in repo_template
                unwrap(ctx).template(repo_path(ctx, dest), repo_path(ct...), <2 more arguments>)
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/wrapped_ctx.bzl", line 39, in unwrap
                repo_path(ctx, template)
        File "/home/steven/.cache/bazel/_bazel_steven/52525b606833c44851a4e9a4771afd88/external/kythe/tools/build_rules/config/wrapped_ctx.bzl", line 32, in repo_path
                unwrap(ctx).path(name)
Not a regular file: /home/steven/osrf/draken/drake/external/tools/workspace/yaml-cpp/yaml-cpp.BUILD.tpl and referenced by '//automotive/maliput/multilane:loader'
ERROR: Analysis of target '//bindings/pydrake/systems:primitives_py' failed; build aborted
INFO: Elapsed time: 3.123s
FAILED: Build did NOT complete successfully (202 packages loaded)
```

**Comment by jamiesnape** [comment]
Try `@drake//tools/workspace/yaml-cpp/yaml-cpp.BUILD.tpl`.

**Comment by nuclearsandwich** [comment]
> Try @drake//tools/workspace/yaml-cpp/yaml-cpp.BUILD.tpl.

From the updated error message I was able to land on
```
build_file_template = "@drake//tools/workspace/yaml_cpp:yaml_cpp.BUILD.tpl
```

As an aside bazel would not allow the pkg_config_package name to be `yaml-cpp` and an error stating that python paths could not contain `-` popped up shortly after. I've resolved both with 43e5e76 and have an in-progress build.

**Comment by clalancette** [comment]
I fixed up the linter warnings.  It looks like the matlab build is failing because it can't successfully link to `yaml-cpp::yaml-cpp`, so that will need to be looked into.

**Comment by jamiesnape** [comment]
> It looks like the matlab build is failing because it can't successfully link to yaml-cpp::yaml-cpp, so that will need to be looked into.

Remove this line: https://github.com/osrf/drake/blob/3d13421be59e3ea516a2afe06170e6725d649652/tools/install/libdrake/drake.cps#L100

and the comma on the previous one (I hate JSON).

**Comment by nuclearsandwich** [comment]
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by nuclearsandwich** [comment]
@jamiesnape @jwnimmer-tri these latest changes are ready for review. (With thanks to @clalancette for grabbing the linter and other followup changes). The Mac CMake builds are passing now.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 4 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/yaml_cpp/yaml_cpp.BUILD.tpl, line 17 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/7602#-L2MtZXeIra4l9k5q_c8:-L2MtZXeIra4l9k5q_c9:b-w1oupm) ([raw file](https://github.com/robotlocomotion/drake/blob/025f23fca65ebb38cc40d7e1bafceea8b950502d/tools/workspace/yaml_cpp/yaml_cpp.BUILD.tpl#L17)):*
> ```Smarty
>     includes = ["%{includes}"],
>     linkopts = ["%{linkopts}"],
>     deps = [ "@boost//:boost_headers" ]
> ```

BTW Remove padding: `["@boost//:boost_headers"]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7602#-:-L2MtSNpPLGfo5HTrE-v:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 5 files at r4, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7602)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 3 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7602#-:-L2N-R69Qs1_EkPjQG6A:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Pull request merged**
