### PR TITLE
Fix most cpplint whitespace issues

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all issues, then stop suppressing most cpplint whitespace filters.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2036)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm: but there are merge conflicts

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2036#-:-KF4aAXoFGbLmKAWOBB7:36485507)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri Merge complete; it looks like reviewable wants you to check the ~5 files the merge touched.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2036#-:-KF4iOjIZyus6jaZAwGU:1417088721)*

**Comment by david-german-tri** [comment]
:lgtm_strong: <- the permanent kind of LGTM

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2036#-:-KF55C0Jpt9loAOtk93f:651788814)*

**Pull request merged**
