### PR TITLE
adde periodic unrestricted update.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
@david-german-tri for feature and platform review. thanks!

I think I can get away the no new tests because the underlying implementations are the same?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4818)

### CODE REVIEW

**Comment by sherm1** [comment]
@siyuanfeng-tri, @edrumwri would be a good choice for feature review also.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-:-KanX6yZiT0x3a2SZpFE:b-husuyc)*

**Comment by sherm1** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/leaf_system.h, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanY9Vy59NeAuuM7y-8:-KanY9Vz95ULU5xLf5jh:b-d338tu) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L253)):*
> ```objc
>   /// the discrete state. Clobbers any other periodic behaviors previously
>   /// declared.
>   void DeclareUpdatePeriodSec(const T& period_sec) {
> ```

Now that there are more variants, please rename to include "Discrete" like `DeclareDiscreteUpdatePeriod()` and `DeclarePeriodicDiscreteEvent()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818)*

**Comment by david-german-tri** [comment]
FYI, Reviewable ignores GitHub's new "reviewers" field, so this didn't show up in my Reviewable queue until I added myself to "assignees".  Taking a look now.

**Comment by david-german-tri** [comment]
:lgtm: aside from open threads.  Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 237 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanfsPESYiZ__HJMsng:-KanfsPFgGg0OeCcn9yt:bgfanqq) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L237)):*
> ```objc
>   /// The first tick will be at t = period_sec, and it will recur at every
>   /// period_sec thereafter. On the discrete tick, the system may perform
>   /// the given type of action. Clobbers any other periodic behaviors
> ```

The "Clobbers" sentence is not true (and isn't true below either, sorry about that)

---

*[drake/systems/framework/leaf_system.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanfwO3xoSiB464GM5U:-KanfwO3xoSiB464GM5V:bdfhuki) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L251)):*
> ```objc
>   /// The first tick will be at t = period_sec, and it will recur at every
>   /// period_sec thereafter. On the discrete tick, the system may update
>   /// the discrete state. Clobbers any other periodic behaviors previously
> ```

While you're here, could you delete this "Clobbers..." sentence?  It's out of date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-:-Kanfm1aMGVBGQnveXwj:b-dmqrt0)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 237 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanfsPESYiZ__HJMsng:-Kanpk-KTELI4Dfh9K3V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L237)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

The "Clobbers" sentence is not true (and isn't true below either, sorry about that)
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanfwO3xoSiB464GM5U:-Kanpl3vW2TfTBo1Zefh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L251)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

While you're here, could you delete this "Clobbers..." sentence?  It's out of date.
</blockquote></details>

Done.

---

*[drake/systems/framework/leaf_system.h, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanY9Vy59NeAuuM7y-8:-KanplqNMbjC8zrOQNCv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L253)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Now that there are more variants, please rename to include "Discrete" like `DeclareDiscreteUpdatePeriod()` and `DeclarePeriodicDiscreteEvent()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818)*

**Comment by david-german-tri** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818)*

**Comment by siyuanfeng-tri** [comment]
*[drake/systems/framework/leaf_system.h, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-KanY9Vy59NeAuuM7y-8:-KaoXRKgCKBy6K37ZD_y:b-aw4ka3) ([raw file](https://github.com/robotlocomotion/drake/blob/83a5b2f288c514b76dd1b409189ec626e1a748b9/drake/systems/framework/leaf_system.h#L253)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@sherm1 can you resolve this? thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4818#-:-KaopKIHL5L-ynCQ0VHi:bnfp4nl)*

**Pull request merged**
