### PR TITLE
[geometry] This PR prepare for next PR "Make Cylinder mesh with medial axis."

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Utility code for making Cylinder's tetrahedral mesh with medial axis.  I split the large PR #14335 into this prerequisite PR and another PR to come. Hopefully it will make the review process easier.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421#-:-MO-UN7m5f-nRWl8hIXX:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[geometry/proximity/meshing_utilities.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOYTtUjD9gDESnUCfjp:-MOYTtUjD9gDESnUCfjq:bl5ye1i) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/meshing_utilities.h#L12)):*
> ```objc
> 
> /* Subdivides a triangular prism into three tetrahedra such that they share the
>  diagonal v0v5 (see ordering below).
> ```

nit: maybe add a little explanation about how that choice fully determines the choice of diagonals for the two other rectangular faces. I had to prove it to myself in my head after staring at the figure for a little bit.
___
*[geometry/proximity/volume_mesh.h, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOY8w2u-Sfg263MVUVc:-MOY8w2u-Sfg263MVUVd:brjigou) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/volume_mesh.h#L107)):*
> ```objc
>    */
>   bool Equal(const VolumeElement& e) const {
>     return this->vertex_ == e.vertex_;
> ```

It seems defective to only consider two elements equal if they specify the vertices in the same order. In general, any permutation that preserves the handedness of the element describes the same element. Is there a reason for `Equal` being implemented as it is here?
___
*[geometry/proximity/volume_mesh.h, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOYS6OI4QaB_puR3hmA:-MOYS6OI4QaB_puR3hmB:bj4vr9e) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/volume_mesh.h#L117)):*
> ```objc
> inline bool operator==(const VolumeElement& e1, const VolumeElement& e2) {
>   return e1.Equal(e2);
> }
> ```

nit: I know you're just implementing this for std::find, but it might be useful to also add the != operator while you're at it. You can just express it as `!(e1 == e2)` in the != implementation.
___
*[geometry/proximity/test/meshing_utilities_test.cc, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOYUrUX2ulPdOtxFltg:-MOYUrUX2ulPdOtxFlth:bjire59) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/test/meshing_utilities_test.cc#L26)):*
> ```cpp
>   EXPECT_TRUE(tetrahedra.end() != std::find(tetrahedra.begin(),
>                                             tetrahedra.end(),
>                                             VolumeElement(v3, v4, v0, v5)));
> ```

nit: this ordering depends heavily on the ordering specified in the implementation. I think it's worth mentioning that in a comment here, unless you choose to change the implementation of `Equals`.

**Review by joemasterjohn — COMMENTED** [review]
First pass done, PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421#-:-MOYV9PdDSDUo96BNE8m:b-v6sck1)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[geometry/proximity/meshing_utilities.h, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOYTtUjD9gDESnUCfjp:-MOcVYyz0_zeDxkyg8io:b-2n5b8) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/meshing_utilities.h#L12)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe add a little explanation about how that choice fully determines the choice of diagonals for the two other rectangular faces. I had to prove it to myself in my head after staring at the figure for a little bit.
</blockquote></details>

Thanks!  I added the description here and also in the unit tests.
___
*[geometry/proximity/volume_mesh.h, line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOY8w2u-Sfg263MVUVc:-MOcZQ0m5F2ROM3kXk3X:b-5k463a) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/volume_mesh.h#L107)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

It seems defective to only consider two elements equal if they specify the vertices in the same order. In general, any permutation that preserves the handedness of the element describes the same element. Is there a reason for `Equal` being implemented as it is here?
</blockquote></details>

Thanks. I added explanation to be clearer.
___
*[geometry/proximity/volume_mesh.h, line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOYS6OI4QaB_puR3hmA:-MOca97n9f1_B-wX48gV:b-iwaoo0) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/volume_mesh.h#L117)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: I know you're just implementing this for std::find, but it might be useful to also add the != operator while you're at it. You can just express it as `!(e1 == e2)` in the != implementation.
</blockquote></details>

Done. Thanks for suggesting the implementation.
___
*[geometry/proximity/test/meshing_utilities_test.cc, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOYUrUX2ulPdOtxFltg:-MOcauAd7Mw9Ys9BiRuQ:bxy3b27) ([raw file](https://github.com/robotlocomotion/drake/blob/8e8fe0c68cc6bf040b6e69c51319a040e848b05c/geometry/proximity/test/meshing_utilities_test.cc#L26)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: this ordering depends heavily on the ordering specified in the implementation. I think it's worth mentioning that in a comment here, unless you choose to change the implementation of `Equals`.
</blockquote></details>

Done. Thanks. That's a good suggestion.

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421#-:-MOd2gNYCmRMqPPpkSB9:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
Thank you @joemasterjohn for feature review.

+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421#-:-MOdYRLY-qlCN8qcyvnT:bp0pdzy)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (with one formatting nit)

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421#-:-MOhD6jn6E4Ma3ooJLEs:b2qv4wg)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

___
*[geometry/proximity/meshing_utilities.cc, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOhCewu9CAgcXC311E6:-MOhCewu9CAgcXC311E7:bnr9whm) ([raw file](https://github.com/robotlocomotion/drake/blob/477a5ce4a1b6a2121f9f739029b698790e501271/geometry/proximity/meshing_utilities.cc#L20)):*
> ```cpp
>   for (const VolumeVertexIndex& next : {v4, v1, v2}) {
>       elements.emplace_back(previous, next, v0, v5);
>     previous = next;
> ```

nit: inconsistent indentation

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421)* status: 1 unresolved discussion (waiting on @joemasterjohn and @sammy-tri)

___
*[geometry/proximity/meshing_utilities.cc, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14421#-MOhCewu9CAgcXC311E6:-MOhJdgq3eykut9GiD1z:b4bc2wp) ([raw file](https://github.com/robotlocomotion/drake/blob/477a5ce4a1b6a2121f9f739029b698790e501271/geometry/proximity/meshing_utilities.cc#L20)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: inconsistent indentation
</blockquote></details>

Good catch! Thank you.  I should have `Clang Format` the whole file since it's a new file.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14421)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn

**Pull request merged**
