### PR TITLE
Export Drake version in drake-config.cmake

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Improve cmake_configure_file to recognize an `--atonly` option which replicates CMake's `@ONLY` mode, refactoring and simplifying the code in the process and also fixing a minor bug where e.g. `${var}}` would incorrectly consume both terminators. Modify CMake build to pass the version information into the Bazel build. Add logic to extract the version information (if provided) and to provide it in the generated `drake-config.cmake`. Use `${CMAKE_FIND_PACKAGE_NAME}` consistently in the same.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

Release note note: Drake now sets `DRAKE_VERSION` (and `DRAKE_VERSION_MAJOR`, etc.) for CMake consumers using `find_package(drake)`.

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint for now.  I'll need to circle back on the regex stuff when I have a bit more time.

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-:-NyMk8dS-Cx242-wfHKw:b7lqyqc)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tools/install/libdrake/BUILD.bazel` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMfWyg6gtxjyh2fOB7:-NyMfWyg6gtxjyh2fOB8:barukl2) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/BUILD.bazel#L51)):*
> ```Starlark
>     name = "drake_parse_version_stamp",
>     srcs = ["stamp_version.txt"],
>     outs = ["drake-version.cmake"],
> ```

BTW The name "drake-version.cmake" sounds suspiciously like something that might be installed alongside drake, or consumed by users, but really it's just an internal-only tempfile.  Could we rename it to be more clear (and/or add more comments)?

Maybe `stamp_version.cmake`, to underline that it's solely a transmogrification of the txt to cmake spelling of the data?
___
*[`tools/install/libdrake/parse_version.py` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMhATm1RXFRaA9jfNb:-NyMhATn3hT4RLr3Ul4A:bvhehti) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/parse_version.py#L27)):*
> ```Python
> 
>             # Check version format.
>             m = re.match(r'^[0-9.]+([+][^ ]+)?', version_full)
> ```

This is too strict.  Release candidates, for example, could easily have "rc" in the version number.

It's probably sufficient to reply on the other remaining checks (that the split above has ==3 pieces, and the split below has >= 3 pieces).  That's good enough to check "syntactically well-formed" which is all we care about here, not the semantics.
___
*[`tools/install/libdrake/parse_version.py` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMgjyD4TEi137ZU9Tp:-NyMgjyE0WeuxI-W8FBH:b-o3yepp) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/parse_version.py#L51)):*
> ```Python
>     else:
>         version_full = '.'.join(version_parts)
>         version_parts += [0]*4
> ```

This too me a while to grok.  I _think_ the intention is to pad with trailing zeros for missing parts?  That can be a lot more clear:

```py
if len(version_parts) < 4;
    # In the typical case where Drake does not have any TWEAK version,
    # default it to zero.
    version_parts.append(0)
```
___
*[`tools/workspace/cmake_configure_file.py` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMjwvxD81uar694n-Y:-NyMjwvxD81uar694n-Z:b-57pvbr) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/workspace/cmake_configure_file.py#L209)):*
> ```Python
>         '--strict', action='store_true')
>     parser.add_argument(
>         '--atonly', action='store_true')
> ```

I imagine that `--atonly` mode should be flagged as incompatible (fail-fast) with `--autoconf` mode?

**Review by mwoehlke-kitware — COMMENTED** [review]
Okay, I left a few replies inline, but won't be able to get back to this until at least Friday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-:-NyMw6-_0YVKzr--ijp9:b2faet6)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tools/install/libdrake/BUILD.bazel` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMfWyg6gtxjyh2fOB7:-NyMwFGu7xgpJUuxqZ2h:b-32w0iv) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/BUILD.bazel#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The name "drake-version.cmake" sounds suspiciously like something that might be installed alongside drake, or consumed by users, but really it's just an internal-only tempfile.  Could we rename it to be more clear (and/or add more comments)?

Maybe `stamp_version.cmake`, to underline that it's solely a transmogrification of the txt to cmake spelling of the data?
</blockquote></details>

Sounds reasonable.
___
*[`tools/install/libdrake/parse_version.py` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMhATm1RXFRaA9jfNb:-NyMv85Q2XvizLgRxsXI:b-zg2tnd) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/parse_version.py#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is too strict.  Release candidates, for example, could easily have "rc" in the version number.

It's probably sufficient to reply on the other remaining checks (that the split above has ==3 pieces, and the split below has >= 3 pieces).  That's good enough to check "syntactically well-formed" which is all we care about here, not the semantics.
</blockquote></details>

Hmm, possibly this should just reuse the PEP440 check. On that note, however, just splitting on `.` won't work because any `rc` component doesn't belong in any of `version_parts`. I think this needs to be reworked to return *both* the original string *and* a tuple of integer parts.
___
*[`tools/install/libdrake/parse_version.py` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMgjyD4TEi137ZU9Tp:-NyMvcuK3WtFOn_adNqn:bpfmpxk) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/parse_version.py#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This too me a while to grok.  I _think_ the intention is to pad with trailing zeros for missing parts?  That can be a lot more clear:

```py
if len(version_parts) < 4;
    # In the typical case where Drake does not have any TWEAK version,
    # default it to zero.
    version_parts.append(0)
```
</blockquote></details>

Right, but I'd want to write that as a `while`, not `if`. And that seems like an unnecessarily complicated way of writing it. But a comment would be reasonable.
___
*[`tools/workspace/cmake_configure_file.py` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMjwvxD81uar694n-Y:-NyMvw6j8y19pOe4-dmb:b-7chdx5) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/workspace/cmake_configure_file.py#L209)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I imagine that `--atonly` mode should be flagged as incompatible (fail-fast) with `--autoconf` mode?
</blockquote></details>

Okay, I forget how to do that offhand but pretty sure you can (and that's it's well documented, I just don't have time to look now).

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tools/install/libdrake/BUILD.bazel` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMfWyg6gtxjyh2fOB7:-Nyff1ce2nrslmZ0rito:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/BUILD.bazel#L51)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Sounds reasonable.
</blockquote></details>

Done.
___
*[`tools/install/libdrake/parse_version.py` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMhATm1RXFRaA9jfNb:-Nyfe7kfC4hsNpHiRcpa:b3rbe2q) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/parse_version.py#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I think this needs to be reworked to return _both_ the original string _and_ a tuple of integer parts.

Agreed.

And that point, we might as well always return a 4-tuple as a contract of this function, so that the logic needed to project the full_version string to the CMake 4-tuple is cohesive with the parsing.

> ... possibly this should just reuse the PEP440 check.

My gut feeling was that doing so would be overkill.

If the goal is to not have "rc" in any of the 4 individual parts, then the `r'^[0-9.]+'` regex is enough to split out that part.  We can ignore any junk that comes afterwards.
</blockquote></details>

...but it's consistent, it's only a few LOC, and I don't think having that check is a bad thing. But, yes, extracting the `r'^[0-9.]+'` match seems to be the right way to get the parts. Anyway, this has been reworked now.
___
*[`tools/install/libdrake/parse_version.py` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMgjyD4TEi137ZU9Tp:-NyffJb_D6XULyiDX3zC:b-4v98p8) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/install/libdrake/parse_version.py#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The main point is that `version_parts` should not have 7 or 8 elements, 3 or 4 of which are quietly discarded.
</blockquote></details>

Moved to `_parse_stamp`. I did end up using just an `if` because we're also asserting that at least three parts are present.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tools/workspace/cmake_configure_file.py` line 209 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-NyMjwvxD81uar694n-Y:-Nz-3zjZDJqkNsR5pxyh:b-idpnqa) ([raw file](https://github.com/RobotLocomotion/drake/blob/f391b22eaf393f151aec10ed0558ef189e2db6a1/tools/workspace/cmake_configure_file.py#L209)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'd be fine without argparse shenanigans that automate it, i.e., we could just do this ...

```py
if args.atonly and args.autoconf:
    parser.error("Can't do both ...")
```

... alongside the other checks immediately below.
</blockquote></details>

Missed this. Done, now.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-:-Nz-Wdd98tSsC_sg0GmD:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-VB3M5Omu0mnOXa5r):*
BTW Is this really true?

The old match was non-greedy, with a `}` after the `+?` so the `+?` would not consume too much stuff, would it?



_Code quote:_
```
  the process and also fixing a minor bug where e.g. '${var}}' would
  incorrectly consume both terminators. Modify CMake build to pass the
```
___
*[`tools/workspace/cmake_configure_file.py` line 40 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-WTMI9LW1vU9FYJG9:-Nz-WTMJAkw19or8A_CU:bipdixl) ([raw file](https://github.com/RobotLocomotion/drake/blob/299a952afc42172c8440ebcddbe378f94687f15d/tools/workspace/cmake_configure_file.py#L40)):*
> ```Python
>         match = pattern.match(line)
>         if not match:
>             break
> ```

BTW Shall we use modern python?



_Suggestion:_
```Python
    while (match := pattern.match(line)) is not None:
```
___
*[`tools/workspace/cmake_configure_file.py` line 120 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-Vsrz8Gn4ACVaMPk0:-Nz-Vss-6Hj_eU0ti0AS:b7d42qv) ([raw file](https://github.com/RobotLocomotion/drake/blob/299a952afc42172c8440ebcddbe378f94687f15d/tools/workspace/cmake_configure_file.py#L120)):*
> ```Python
> # Transform a source code line using autoconf format.
> # The 'definitions' provides variable values, just like _transform_cmake above.
> def _transform_autoconf(*, line, definitions, strict, atonly):
> ```

nit We should probably clarify the invariant here:



_Suggestion:_
```Python
def _transform_autoconf(*, line, definitions, strict, atonly):
    assert atonly == False
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/cmake_configure_file.py` line 40 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-WTMI9LW1vU9FYJG9:-Nz-q9ImDBvxirJkxteF:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/299a952afc42172c8440ebcddbe378f94687f15d/tools/workspace/cmake_configure_file.py#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Shall we use modern python?
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
This is looking in fair shape.  You can assign to on-call platform review once you're satisfied with it.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-:-Nz-vB0Z0-liDVUInvv-:b-3tg6ob)* status: 2 unresolved discussions, needs at least two assigned reviewers

**Review by mwoehlke-kitware — COMMENTED** [review]
+@EricCousineau-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-:-Nz3mfnz8EqFxvdVx-5b:b-r34yat)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-VB3M5Omu0mnOXa5r):*
Ew. Okay, I must have been testing with non-greedy matching (TIL: adding '?' makes a sub-expression non-greedy). However, the old expression still wasn't working right:

```python
>>> re.match(r'^(.*?)(@[^ ]+?@|\$\{[^ ]+?\})(.*)([\r\n]*)', 'foo ${x${bar}}').groups()
('foo ', '${x${bar}', '}', '')
```

This version uses greedy matching for the "prefix" (and also for the substitution, but the `[^} ]` ensures it can only pick up the inner-most `}`), which means it matches right-to-left instead of left-to-right, and inside-to-outside, so I _think_ it's bug-free. (Excluding the case of e.g. 'foo=${foo}', which a) I believe results in an infinite loop for both versions, b) is clearly pathological, and c) arguably results in an infinite loop as *"correct"* behavior.)
___
*[`tools/workspace/cmake_configure_file.py` line 120 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-Vsrz8Gn4ACVaMPk0:-Nz3nf6M4ieoKexJ9RRo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/299a952afc42172c8440ebcddbe378f94687f15d/tools/workspace/cmake_configure_file.py#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We should probably clarify the invariant here:
</blockquote></details>

Done.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/cmake_configure_file.py` line 120 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-Nz-Vsrz8Gn4ACVaMPk0:-Nz3qIIT-pyxYMTOX9dl:b-9ta538) ([raw file](https://github.com/RobotLocomotion/drake/blob/299a952afc42172c8440ebcddbe378f94687f15d/tools/workspace/cmake_configure_file.py#L120)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI, `pycodestyle` insists on `assert not atonly`. I'm not convinced that's actually superior in this case. Are you okay with it, or should we `# noqa` your original suggestion?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21450#-:-Nz4RNRf2q51PZ69Dffv:bcpz082)* status: 2 unresolved discussions

**Pull request merged**
