### PR TITLE
Move /drake/doc to /doc

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

This does not need `drake-ci` edits; there are compat shims intended to keep CI working in order to stagger the PRs.  After this merges, we can PR `drake-ci` with the new paths, and then revert the final commit of this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7273)

### CODE REVIEW

**Comment by jamiesnape** [comment]
BTW CI only runs nightly, so if you want to avoid the compatibility shims, it should be fine. (Also if there is a way to avoid the `html` subdirectory in Doxygen documentation while you are making changes, it would simplify the website generation, but that is not essential.)

---

Review status: 0 of 75 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-:-KwePZcYv2uBPKXd-HAA:bd3pcww)*

**Comment by jwnimmer-tri** [comment]
> CI only runs nightly, so if you want to avoid the compatibility shims, it should be fine.

Yeah, though I wanted to test pre-merge if I can.

> If there is a way to avoid the html subdirectory in Doxygen documentation while you are making changes, it would simplify the website generation, but that is not essential.

I think that could happen after this.  Possibly some of the `drake-ci` bash scripts to prepare the full set of staged documentation could move into the Drake tree?  Might be a better coupling / cohesion boundary.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
> I think that could happen after this. Possibly some of the drake-ci bash scripts to prepare the full set of staged documentation could move into the Drake tree? Might be a better coupling / cohesion boundary.

All sounds good to me.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review please?
+@sammy-tri for platform review please, per rotation.

**Comment by jwnimmer-tri** [comment]
Note that reviewable is set to "review each commit separately".  When viewing across all revisions, the `doxygen.py` changes show up as-new, but if you just look at the r2..r3 on its own, it will show you only the edits.

**Comment by soonho-tri** [comment]
FYI, we still have the files mentioning `drake/doc/bazel.rst` and `drake/doc/developers.rst` that are not changed by this PR. Do you want to handle them separately?

**Comment by jwnimmer-tri** [comment]
Yeah, the `drake/doc/bazel.rst` boilerplate I was just going to remove entirely.  I'll check about `developers.rst` soon.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 142 of 142 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/doxygen.py, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-Kwej8H2wCSkqJsaeL4w:-Kwej8H2wCSkqJsaeL4x:bpsg7w7) ([raw file](https://github.com/robotlocomotion/drake/blob/f96530c0a496702729bfcb8bc3bf5ee622003eb2/doc/doxygen.py#L30)):*
> ```Python
>     # Compute the definitions dict needed by Doxygen_CXX.in.
>     drake_distro = _get_drake_distro()
>     binary_dir = os.path.join(drake_distro, "build/drake/doc")
> ```

BTW, do you want to keep `build/drake/doc` as it is? (alternative,`build/doc`?)

---

*[drake/doc/doxygen.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-Kwek0E_7KDtD9ex1ffY:-Kwek0E_7KDtD9ex1ffZ:b-8e29i1) ([raw file](https://github.com/robotlocomotion/drake/blob/5870287eccb58512d30512913d4b5421750f9f0a/drake/doc/doxygen.py#L1)):*
> ```Python
> #!/bin/bash
> ```

`#!/usr/bin/env python`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-:-Kwejjo2xElTwtK59iRC:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-KwekbF3ZaIE9Bs_VmbG:-KwekbF3ZaIE9Bs_VmbH:b-u1nnho) (no related file):*
Need to check for lingering `drake/doc/*` citations in comments before merging.

---

*[doc/doxygen.py, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-Kwej8H2wCSkqJsaeL4w:-KwekM379yNMnQXsis8G:b-5zhx28) ([raw file](https://github.com/robotlocomotion/drake/blob/f96530c0a496702729bfcb8bc3bf5ee622003eb2/doc/doxygen.py#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, do you want to keep `build/drake/doc` as it is? (alternative,`build/doc`?)
</blockquote></details>

OK So I think its probably good as-is, but in any case should be changed outside of this PR, if ever.   It relates to the `drake-ci` bash scripts for doc publication, so needs to stay compatible for now.

---

*[drake/doc/doxygen.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-Kwek0E_7KDtD9ex1ffY:-KwekYSILxFS36ezP8dk:bebnyua) ([raw file](https://github.com/robotlocomotion/drake/blob/5870287eccb58512d30512913d4b5421750f9f0a/drake/doc/doxygen.py#L1)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`#!/usr/bin/env python`?
</blockquote></details>

OK It's a bash script, though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/doxygen.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-Kwek0E_7KDtD9ex1ffY:-Kwel5eZOaiqQrxQR06A:b-typlpu) ([raw file](https://github.com/robotlocomotion/drake/blob/5870287eccb58512d30512913d4b5421750f9f0a/drake/doc/doxygen.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK It's a bash script, though?
</blockquote></details>

OK (anyway we will remove it soon, right?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/doxygen.py, line 1 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-Kwek0E_7KDtD9ex1ffY:-Kwen9JaiZQdWrL9A9f2:bu41kxx) ([raw file](https://github.com/robotlocomotion/drake/blob/5870287eccb58512d30512913d4b5421750f9f0a/drake/doc/doxygen.py#L1)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK (anyway we will remove it soon, right?)
</blockquote></details>

We hope ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 142 of 142 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-:-KwevNM0_QANJY1kZKL_:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7273#-KwekbF3ZaIE9Bs_VmbG:-Kwf1wJw4UjluRavDiG0:b-hisza4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Need to check for lingering `drake/doc/*` citations in comments before merging.
</blockquote></details>

OK I'm satisfied that all of the lingering references are appropriate for a follow-up PR, where they are mostly removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-documentation please

**Comment by soonho-tri** [comment]
Reviewed 1 of 142 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7273)*

**Comment by jwnimmer-tri** [comment]
The `-debug` problem was another Maven glitch.  Everything else passed.  Using override-merge.

**Pull request merged**
