### PR TITLE
Cleans up direct collocation code

### PR DESCRIPTION
**Pull request by RussTedrake**
continuation of #6858.
cleans up the DirectCollocation API and implementation.  Adds proper unit test coverage of the DirectCollocation class.

after these changes, I think that all of the trajectory optimization code currently in master is very solid.  on to adding some new functionality with this more solid foundation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6874)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.
fyi @tarquasso

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-:-Krx0XzYu89_kkWlYZUY:bjf4f98)*

**Comment by hongkai-dai** [comment]
:lgtm: +@ericcousineau-tri for platform review please.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks01tA0UsGGdKKqsOd6:-Ks01tA0UsGGdKKqsOd7:bx8ltdu) ([raw file](https://github.com/robotlocomotion/drake/blob/77d63f20809893a4dc04705a49a861371ff2e058/drake/systems/trajectory_optimization/direct_collocation.cc#L122)):*
> ```cpp
>     AutoDiffVecXd xdot0;
>     dynamics(x0, u0, &xdot0);
>     Eigen::MatrixXd dxdot0 = math::autoDiffToGradientMatrix(xdot0);
> ```

BTW, `Eigen::MatrixXd` -> `const Eigen::MatrixXd`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-:-Ks08XMAOplOaeARPAet:b-puvytt)*

**Comment by RussTedrake** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks01tA0UsGGdKKqsOd6:-Ks0eQoxDYKFZcEd2M4w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/77d63f20809893a4dc04705a49a861371ff2e058/drake/systems/trajectory_optimization/direct_collocation.cc#L122)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, `Eigen::MatrixXd` -> `const Eigen::MatrixXd`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-:-Ks1fgFUiilCnLRi3umd:b-1hejgk)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks44Kn9zT1EwtwpAC14:-Ks4CKLqwLUytR-F8Wlo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/direct_collocation.cc#L146)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Minor nit - I've seen either `// namespace` or `// anonymous namespace`, but I'm not sure if I've seen this variant.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks44f94PxGLWuzW9mR7:-Ks4CSDucajR7cZbhRw2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/direct_collocation.h#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Slightly early linebreak.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks44uCOlavmS0O2yDFk:-Ks4CVPYHyST9xLuJWkl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/direct_collocation.h#L63)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should be `//` since this method is private.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks44xrpvuDerIVCnwZT:-Ks4CW3WvIbXxpH-87we:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/direct_collocation.h#L66)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should also be `//`
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/multiple_shooting.h, line 221 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks4AIdPg1dYtF0XypFj:-Ks4Cpp9FZ0PKRo6L3-i:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/multiple_shooting.h#L221)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Minor nit Comment should be descriptive rather than imperative
https://google.github.io/styleguide/cppguide.html#Function_Comments
</blockquote></details>

Done

---

*[drake/systems/trajectory_optimization/multiple_shooting.h, line 239 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks454sInqn6--o4N-NL:-Ks4DDUNhTm8zmljVhNq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/multiple_shooting.h#L239)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Minor nit on old code, "Constructs"
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks45b6nmRLbN_UFPJjr:-Ks4DU9yhuVSjO4BRxd3:bkz5ckv) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L19)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This comment does not appear to apply to this system.
</blockquote></details>

Done.  Good catch.

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks4AXjwH56PYXd39Y1R:-Ks4DLoNjKQdASQBr8z2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L32)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Grammar `codepath` -> `code path`
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_collocation_test.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks4Ab3fa8GRP1kRbm-D:-Ks4Dexv7x2oN9cgRf9S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/test/direct_collocation_test.cc#L34)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Return type is not immediately obvious from call site.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 117 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks4F18mHCRaQOomd5Vy:-Ks4F18na4SgvpEP0lf5:blf00wr) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/direct_collocation.cc#L117)):*
> ```cpp
>     const auto u1 = x.segment(1 + (2 * num_states_) + num_inputs_, num_inputs_);
> 
>     // TODO(sam.creasey): We should cache the dynamics outputs to avoid
> ```

BTW Talked to Sam about this portion - could this be briefly clarified that we want to cache dynamics between `{x1,u1}` for this constraint and `{x0,u0}` for the next constraint (possibly pending System caching)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874)*

**Comment by RussTedrake** [comment]
Review status: 12 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 117 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6874#-Ks4F18mHCRaQOomd5Vy:-Ks4Hntv4vM-4XedM9jd:b-elmvss) ([raw file](https://github.com/robotlocomotion/drake/blob/1016ded4d29a63a617b74d7cb9dfb09f5858765c/drake/systems/trajectory_optimization/direct_collocation.cc#L117)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Talked to Sam about this portion - could this be briefly clarified that we want to cache dynamics between `{x1,u1}` for this constraint and `{x0,u0}` for the next constraint (possibly pending System caching)?
</blockquote></details>

Done.  i thought it was clear enough.  :) .  but tried to clean it up.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6874)*

**Pull request merged**
