### PR TITLE
PoseAggregator's AddSinglePoseAndVelocityInput() returns a struct

### LINKED ISSUE #8331: PoseAggregator Python binding trying to move an InputPortDescriptor
After a merge with master I am now getting this CI failure in my caching branch:
```
ERROR: test_pose_aggregator (rendering_test.TestRendering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bindings/pydrake/systems/test/rendering_test.py", line 136, in test_pose_aggregator
    "pose_and_velocity", instance_id2)
RuntimeError: return_value_policy = move, but the object is neither movable nor copyable!
```
This binding was recently added in PR #8282, and is wrapping this method of PoseAggregator:
```c++
  std::pair<const InputPortDescriptor<T>&, const InputPortDescriptor<T>&>
  AddSinglePoseAndVelocityInput(const std::string& name, int model_instance_id);
```
That method creates a couple of input ports and returns references to them. I don't think it should be trying to move the InputPortDescriptors!

The reason this fails in the caching branch is that I removed the ability to move InputPortDescriptors, which is generally a bad thing to do.

@EricCousineau-TRI, @jadecastro does this actually make sense here?

### PR DESCRIPTION
**Pull request by jadecastro**
Resolves #8331.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8343)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@sherm1 for feature review.
+@jwnimmer-tri for platform review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8343#-:-L7QyW4EbHrlpY0YuUMm:bxqt0gz)*

**Comment by EricCousineau-TRI** [comment]
Sorry, just saw got to seeing this: Will suggest a less verbose alternative in https://github.com/RobotLocomotion/drake/issues/8331

**Comment by jwnimmer-tri** [comment]
I like the C++ readability improvement (c.f. `automotive_simulator.cc`).

I will hold off on pydrake changes review until Eric replies, in case it will end up changing.

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/rendering/pose_aggregator.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8343#-L7R0qVY8akCxxcWZZN7:-L7R0qVZoP-WjTHVLkK5:b-lnxj6a) ([raw file](https://github.com/robotlocomotion/drake/blob/7aa9630831635206194587761f6347753c6e5803/systems/rendering/pose_aggregator.h#L34)):*
> ```objc
>   const std::reference_wrapper<
>     const InputPortDescriptor<T>> velocity_descriptor;
> };
> ```

FYI I would have done it more KISS:
```c++
template <typename T>
struct PoseVelocityInputPortDescriptors {
  std::reference_wrapper<const InputPortDescriptor<T>> pose_descriptor;
  std::reference_wrapper<const InputPortDescriptor<T>> velocity_descriptor;
};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8343#-:-L7R13BA7-02RRdlDTew:b-bsdzmu)*

**Comment by EricCousineau-TRI** [comment]
I'd prefer we stick to `std::pair<>` as we'd have an example for other usages which return `std::pair` that contains references to non-copyable objects (or things that are intended to be references, rather than attempted copies.

However, if we stick to a custom struct, I guess I'd be fine with that too, as long as it's simple (in which case,  we could bind them as `def_readonly`, which I think we can still specify a RVP for).

---

Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/rendering/pose_aggregator.h, line 34 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8343#-L7R0qVY8akCxxcWZZN7:-L7R35lggYZVOLYJTgYH:bsonfhc) ([raw file](https://github.com/robotlocomotion/drake/blob/7aa9630831635206194587761f6347753c6e5803/systems/rendering/pose_aggregator.h#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I would have done it more KISS:
```c++
template <typename T>
struct PoseVelocityInputPortDescriptors {
  std::reference_wrapper<const InputPortDescriptor<T>> pose_descriptor;
  std::reference_wrapper<const InputPortDescriptor<T>> velocity_descriptor;
};
```
</blockquote></details>

BTW Can I ask what `reference_wrapper<const U>` buys us versus, just using `const U&`?
If they're going to be `const`, we don't really need any of the fanciness that `reference_wrapper` uses for re-assignment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8343#-:-L7R2SXDae8N13u9UnIA:b5duheo)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/rendering/pose_aggregator.h, line 34 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8343#-L7R0qVY8akCxxcWZZN7:-L7R3x_E8bxgQapHjMlQ:b-kwmvri) ([raw file](https://github.com/robotlocomotion/drake/blob/7aa9630831635206194587761f6347753c6e5803/systems/rendering/pose_aggregator.h#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can I ask what `reference_wrapper<const U>` buys us versus, just using `const U&`?
If they're going to be `const`, we don't really need any of the fanciness that `reference_wrapper` uses for re-assignment.
</blockquote></details>

(By `const`, I mean the references being `const`, not the values - we wouldn't want a user to be able to change these references, would we?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8343)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/rendering/pose_aggregator.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8343#-L7R0qVY8akCxxcWZZN7:-L7R4lbFHn_b0G3XOysV:b-1d5i9x) ([raw file](https://github.com/robotlocomotion/drake/blob/7aa9630831635206194587761f6347753c6e5803/systems/rendering/pose_aggregator.h#L34)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

(By `const`, I mean the references being `const`, not the values - we wouldn't want a user to be able to change these references, would we?)
</blockquote></details>

Good point, this is even simpler:
```c++
/// ... docs ...
template <typename T>
struct PoseVelocityInputPortDescriptors {
  const InputPortDescriptor<T>& pose_descriptor;
  const InputPortDescriptor<T>& velocity_descriptor;
};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8343)*

**Comment by jadecastro** [comment]
After a 1:1 with Eric, I'll close this for now, so that he can work on a more direct fix.
Perhaps later we can improve readability in the `automotive` codebase, but I won't conflate the two issues here.

**Comment by jwnimmer-tri** [comment]
:sadpanda: pairs suck and this was a nice improvement, even if only the C++ side merged.

**Comment by jadecastro** [comment]
After _further_ deliberation, we're re-opening this PR for business...

@EricCousineau-TRI I tried `def_readonly` but get the following:

```
ERROR: /Users/jond/TRI/drake-distro/bindings/pydrake/systems/BUILD.bazel:130:1: C++ compilation of rule '//bindings/pydrake/systems:rendering.so' failed (Exit 1)
bindings/pydrake/systems/rendering_py.cc:67:8: error: no matching member function for call to 'def_readonly'
      .def_readonly("pose_descriptor",
      ~^~~~~~~~~~~~
external/pybind11/include/pybind11/pybind11.h:1498:13: note: candidate template ignored: could not match 'const D C::*' against '(lambda at bindings/pydrake/systems/rendering_py.cc:68:21)'
    class_ &def_readonly(const char *name, const D C::*pm, const Extra& ...extra) {
            ^
1 error generated.
Target //bindings/pydrake/systems:_isolated/rendering_test failed to build
```

**Comment by jadecastro** [comment]
-> #8347

**Pull request closed without merging**
