### PR TITLE
workspace: Upgrade fcl to latest commit

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
(Pick up full support for half space-ellipsoid contact.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14620)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
+@soonho-tri for all reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14620#-:-MScH1fYEj4xGDo7UzeB:be0fyak)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14620#-:-MScJfo_87Fmyy_2rS9p:bnfp4nl)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14620#-MScKgMi8veN_77aABCG:-MScKgMi8veN_77aABCH:b-gxk0tu) (no related file):*
@seancurtis-tri , could you check the following CI results before merging this PR?

 - https://ci.appveyor.com/project/flexible-collision-library/fcl/builds/37589930
 - https://travis-ci.org/github/flexible-collision-library/fcl/builds/757395314

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14620)* status: 1 unresolved discussion (waiting on @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14620#-MScKgMi8veN_77aABCG:-MScTL9QCtylYeQYchtH:boqgmrn) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@seancurtis-tri , could you check the following CI results before merging this PR?

 - https://ci.appveyor.com/project/flexible-collision-library/fcl/builds/37589930
 - https://travis-ci.org/github/flexible-collision-library/fcl/builds/757395314

</blockquote></details>

You bet.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14620)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14620#-MScKgMi8veN_77aABCG:-MScmEYqApggsoZ_ljI7:b-iy5lzz) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You bet.
</blockquote></details>

All of FCL's CI has completed green. Now we're just waiting on our mac CI.

---

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14620)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14620#-MScKgMi8veN_77aABCG:-MSctAIa1mfa4Is4keEA:br9xua1) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

All of FCL's CI has completed green. Now we're just waiting on our mac CI.
</blockquote></details>

Great. Thanks for the check.

---

**Comment by soonho-tri** [comment]
I just added `do not merge` label. Please remove the label and merge this when the mac CI result is good.

**Comment by soonho-tri** [comment]
mac CI is happy with this PR: https://drake-jenkins.csail.mit.edu/job/mac-catalina-clang-bazel-experimental-everything-release/51

**Pull request merged**
