### PR TITLE
Add support of intersection and unbounded hyperrectangles

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@sadraddini for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-Nrpjbdh-FP0HJ_Nv81l:b7cgnxg)* status: LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hyperrectangle.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpkjiOCO2SdDptcK_w:-NrpkjiOCO2SdDptcK_x:bg9lhqa) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L39)):*
> ```objc
> 
>   /** Draws a uniform sample from the set. */
>   Eigen::VectorXd UniformSample(RandomGenerator* generator) const;
> ```

Many of the Hyperrectable member functions (such as this one) need updates to their specification, to explain what happens when the user tries to take a sample from, or find the center or, or etc on an infeasible set.

**Review by sadraddini — COMMENTED** [review]
I'm not still super convinced about this. As an example`MakeBox` in `HPolyhedron` does not allow lb>ub. See Jeremy's comment on center and uniform sample. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-NrpuzZY1oQeXAQxE0t_:b-vqenac)* status: 8 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hyperrectangle.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpuYOZ2n74ZDoQaAWL:-NrpuYOZ2n74ZDoQaAWM:b-lvj451) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L28)):*
> ```objc
>   /** Constructs a hyperrectangle from its lower and upper bounds.
>    @pre lb.size() == ub.size()
>    @pre lb and ub are not NaN*/
> ```

I suggest adding a sentence or two that we allow `lb>ub`. One can use `IsEmpty` to check if the hyperrectangle is not empty. 
___
*[`geometry/optimization/hyperrectangle.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpkjiOCO2SdDptcK_w:-NrppeDQ6k41yxez_Zbr:b-90yatq) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Many of the Hyperrectable member functions (such as this one) need updates to their specification, to explain what happens when the user tries to take a sample from, or find the center or, or etc on an infeasible set.
</blockquote></details>

Agreed. See my top comment.
___
*[`geometry/optimization/hyperrectangle.h` line 42 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrppVME7i1p6MqTSPLb:-NrppVME7i1p6MqTSPLc:b-uszs5v) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L42)):*
> ```objc
> 
>   /** Get the center of the hyperrectangle. */
>   Eigen::VectorXd Center() const;
> ```

Center would also be meaningless for an unbounded Hyperrectangle. 

Option1: do nothing. center can have infinity components.
Option 2: Throw if unbounded.
Option 3: API change. Change it to std::optional and `MaybeGetCenter()` (I don't like it). Unlike hyperellipsoid, hyperrectangles are not defined by their centers. 
___
*[`geometry/optimization/hyperrectangle.h` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-Nrptxsh2nK-LoPM8cUN:-Nrptxsh2nK-LoPM8cUO:b-wq0mza) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L48)):*
> ```objc
> 
>   /** Constructs the intersection of two Hyperrectangle by taking the pointwise
>    * maximum of the lower bounds and the pointwise minimums of the upper
> ```

nit fix the leading *
___
*[`geometry/optimization/hyperrectangle.h` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpuBWeCtvZPVMjksfn:-NrpuBWeCtvZPVMjksfo:b-401ae7) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L49)):*
> ```objc
>   /** Constructs the intersection of two Hyperrectangle by taking the pointwise
>    * maximum of the lower bounds and the pointwise minimums of the upper
>    * bounds.*/
> ```

You need a @pre condition that dimensions match between `this` and `other`. You also need a unit test that inconsistent dimensions indeed throws. 
___
*[`geometry/optimization/hyperrectangle.cc` line 191 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-Nrpu4w_DtNOE39Xj2Wj:-Nrpu4wa9grMPSHTdfs9:b-b3x7zk) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.cc#L191)):*
> ```cpp
> 
> Hyperrectangle Hyperrectangle::Intersection(const Hyperrectangle& other) const {
>   return Hyperrectangle(lb_.cwiseMax(other.lb_), ub_.cwiseMin(other.ub_));
> ```

You need to check if dimensions match and throw. See comment in the header. 
___
*[`geometry/optimization/test/hyperrectangle_test.cc` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpvhSr1hNqumGw5oCP:-NrpvhSr1hNqumGw5oCQ:b-9yycse) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/test/hyperrectangle_test.cc#L29)):*
> ```cpp
> namespace {
> const double kInf = std::numeric_limits<double>::infinity();
> }
> ```

Once we settle on the docs for `Center()`, Can you add this somewhere to `BasicTests`? It surprisingly passes on my machine.



_Code snippet:_
```cpp
  // Tests for a unbounded hyperrectangle.
  const Hyperrectangle unbounded_hyperrectangle(Vector3d{-kInf, -2, -3},
                                                Vector3d{3, kInf, 1});
  const auto unbounded_center = unbounded_hyperrectangle.Center();
  EXPECT_TRUE(unbounded_hyperrectangle.PointInSet(unbounded_center));
```
___
*[`geometry/optimization/test/hyperrectangle_test.cc` line 146 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-Nrpt_429v5QanI7CNck:-Nrpt_429v5QanI7CNcl:be8sho9) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/test/hyperrectangle_test.cc#L146)):*
> ```cpp
> }
> 
> GTEST_TEST(HyperrectangleTest, Intersection) {
> ```

nit  add comments for what is being tested in each of the 4 cases.

**Review by AlexandreAmice — COMMENTED** [review]
I rolled back to making everything finite and having intersection return an optional.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-Nrq1yBVE5aa55PvJb1D:b-tnjxfj)* status: 6 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`geometry/optimization/hyperrectangle.h` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpuBWeCtvZPVMjksfn:-Nrq1vRm16Q-b8DL9Pml:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L49)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

You need a @pre condition that dimensions match between `this` and `other`. You also need a unit test that inconsistent dimensions indeed throws.
</blockquote></details>

Done.
___
*[`geometry/optimization/hyperrectangle.cc` line 191 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-Nrpu4w_DtNOE39Xj2Wj:-Nrq1wbj7ZN75gY-_TOS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.cc#L191)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

You need to check if dimensions match and throw. See comment in the header.
</blockquote></details>

Done.
___
*[`geometry/optimization/test/hyperrectangle_test.cc` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpvhSr1hNqumGw5oCP:-Nrq1xF77TqnKu0tomMh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/test/hyperrectangle_test.cc#L29)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Once we settle on the docs for `Center()`, Can you add this somewhere to `BasicTests`? It surprisingly passes on my machine.
</blockquote></details>

Done.

**Review by sadraddini — COMMENTED** [review]
If we go with optional I think now you need to change the method name to `MaybeIntersection`. I know we like having the same API as HPolyhedron but also the classes are different. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-NrqLs6lDKyzSA9uQf3u:bb8wfz1)* status: 2 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hyperrectangle.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpuYOZ2n74ZDoQaAWL:-NsBrdnX90hWtOhKrDu4:b99x617) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L28)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

I suggest adding a sentence or two that we allow `lb>ub`. One can use `IsEmpty` to check if the hyperrectangle is not empty.
</blockquote></details>

Dismissing as support for empty and unbounded rectangles has been removed from this pr
___
*[`geometry/optimization/hyperrectangle.h` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrpkjiOCO2SdDptcK_w:-NsBrm8-BtZ3h9KFnrj0:b99x617) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L39)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Agreed. See my top comment.
</blockquote></details>

Dismissing as support for empty and unbounded rectangles has been removed from this pr
___
*[`geometry/optimization/hyperrectangle.h` line 42 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NrppVME7i1p6MqTSPLb:-NsBrmcz0_W5_neN3GLc:b99x617) ([raw file](https://github.com/RobotLocomotion/drake/blob/dfbd80cb8d156fc73361a4d6e4c01bb14743693c/geometry/optimization/hyperrectangle.h#L42)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Center would also be meaningless for an unbounded Hyperrectangle. 

Option1: do nothing. center can have infinity components.
Option 2: Throw if unbounded.
Option 3: API change. Change it to std::optional and `MaybeGetCenter()` (I don't like it). Unlike hyperellipsoid, hyperrectangles are not defined by their centers.
</blockquote></details>

Dismissing as support for empty and unbounded rectangles has been removed from this pr

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-NsM2-akD4Gfm0q0bKM_:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+@EricCousineau-TRI for platform per schedule. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-NsPgMgz3RCA1PYHyl5U:b-pnl5f5)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform w/ minor nits, thanks!

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-NsQ5YLV5lhwGn0MpvRo:bj5jb85)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/test/hyperrectangle_test.cc` line 167 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NsQ5LQiB9Daq4KgPPK6:-NsQ5LQiB9Daq4KgPPK7:bkwp0am) ([raw file](https://github.com/RobotLocomotion/drake/blob/c7496b63b65ef1c93ea51c2490f44e0a4a24bbd1/geometry/optimization/test/hyperrectangle_test.cc#L167)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(intersection12->ub(), intersection21->ub()));
> 
>   const Vector3d lb3{-30, -20, -10};
> ```

nit Consider commenting on the sub-case:
```
// No intersection yield nullopt.
```
___
*[`geometry/optimization/test/hyperrectangle_test.cc` line 176 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-NsQ596TCfJ55xweZVUY:-NsQ596TCfJ55xweZVUZ:b-rvhvve) ([raw file](https://github.com/RobotLocomotion/drake/blob/c7496b63b65ef1c93ea51c2490f44e0a4a24bbd1/geometry/optimization/test/hyperrectangle_test.cc#L176)):*
> ```cpp
>   EXPECT_FALSE(intersection13.has_value());
> 
>   const Vector2d lb4{-1, 2};
> ```

nit Consider commenting on the sub-case:
```
// Error: Mismatched ambient dimension.
```

**Review by AlexandreAmice — COMMENTED** [review]
+(release notes: feature) +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076#-:-NsTV1hp5RlMs_WxgYFS:b-1qggee)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sadraddini,EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21076)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sadraddini,EricCousineau-TRI(platform)

**Comment by EricCousineau-TRI** [comment]
@AlexandreAmice Is the PR title still correct? It mentions unbounded, but I don't think that's allowed here?

**Pull request merged**
