### PR TITLE
Updated version of xacro.py in Drake to be the one used by ROS Indigo

### LINKED ISSUE #3615: Drake/ROS CI Needs xacro To Be Installed
# Motivation

It is often useful to generate a URDF using [xacro](http://wiki.ros.org/xacro) since it enables small variations of a particular model to be kept in sync and reduces verbosity when a model consists of numerous similar parts (e.g., a left arm and a right arm, or all four wheels of a car).

PR #3609 includes a test that uses `xacro.py` (the main executable script in the `xacro` ROS package) to generate and load a URDF into the ROS parameter server. The apparent lack of `xacro.py` is causing that PR to fail CI testing.

# Action Item

Install `xacro.py` by executing the following command:

```
$ sudo apt-get install ros-indigo-xacro
```

# Additional Note

Drake has a copy of `xacro.py` here: `drake-distro/drake/thirdParty/bsd/xacro/xacro.py`. If we're unable to install the ROS Indigo version of `xacro.py`, I might be able to modify the aforementioned unit test to use the version that's in Drake. I'd prefer to use ROS Indigo's version since I believe it's more "official".

### PR DESCRIPTION
**Pull request by liangfok**
This is necessary for me to perform the "Additional Note" solution described here: https://github.com/RobotLocomotion/drake/issues/3615. The old version that this PR updates is buggy and fails to generate the URDF from `drake_prius_rviz.xacro` in #3609.

Since `xacro.py` is from ROS and is in Drake's `thirdParty` folder, I don't think the code itself needs to be reviewed for style guide compliance, etc.

If and when this PR is merged, I can modify https://github.com/RobotLocomotion/drake/pull/3609 to not block on #3615. Thus:

Closes #3615.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3621)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3621#-:-KSrBhxUtn3A55ihuiV6:bcv4nxl)*

**Comment by jwnimmer-tri** [comment]
What a funny little program that is!
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3621#-:-KSrCwk99YaOz8hsuzCA:b-1ttowy)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by liangfok** [comment]
Oops. Now that I study the new `xacro.py` more closely, I now realize I didn't copy the correct files. The `xacro.py` I copied simply imports a package called `xacro` and then calls `xacro.main()`. It worked on my machine because I happen to have ROS Indigo installed. I will now close this PR and submit a new one with the correct files. Apologies for the mistake.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3621#-:-KSrDDuVFj-k8mYMrNPY:b-smlawt)*

**Comment by liangfok** [comment]
From a F2F meeting with @jwnimmer-tri, I now think using the Debian package version of `xacro` is superior to using a version in Drake. I shall thus shift focus on resolving #3615.

**Pull request closed without merging**
