### PR TITLE
[tools] Enable Werror=literal-conversion with Clang

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16412)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews, please.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16412#-:-MttmOi07EHjgrKd1Tsq:b4xzgsb)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16412#-:-MttmUMp3wUxhway0Cvq:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
