### PR TITLE
Toward #2852: enforce -Werror=shadow in util/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove excuse from util/ cmake file.
 * Fix a bunch of constructors for classes with public/protected data.
   * It is madness to try to fix the public/protected fields, so:
     * Rename construct params with '_' prefixes.
     * Retire some 'this->' disambiguators.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2885)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Here is another whack at #2852.

**Comment by liangfok** [comment]
As long a leading underscore for parameter names is _not_ against the style guide rules, this :lgtm:.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2885#-:-KNEUKGA7de0v-qYZviX:1431413527)*

**Comment by rpoyner-tri** [comment]
I'll go ahead and claim that +@liangfok is my feature reviewer (was busy flipping a coin between Liang and Alejandro).
Thanks Liang!
Adding +@sammy-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2885#-:-KNEUqxjScOHLzGVa2kw:-375472255)*

**Comment by sherm1** [comment]
Sorry to be the bearer of bad news but leading underscores are a problem. A leading underscore followed by a capital letter is prohibited by the language standard, not just the style guide. So names like `_T_element_to_local` (see below) are not legal C++ code. [Here](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier) is a good summary of the rules. Personally I just don't use leading underscores at all to keep myself out of trouble.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2885#-:-KNEeCieiw2gdhUsIlVI:-2086151496)*

**Comment by rpoyner-tri** [comment]
Sweeet. :)

Well, I'm still not touching public/protected data names with a 10' pole, so I guess I'll go with the foo ==> foo_in convention.

Thanks @sherm1, good catch!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2885#-:-KNF77Y9Lb3BQhtES5dw:1656549701)*

**Comment by rpoyner-tri** [comment]
Addressed @sherm1's comments. PTAL.

---

Review status: 1 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2885#-:-KNFJ5uQakKDukbZYc22:1051310809)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2885#-:-KNFSFJJIlCwpDhQdmJL:1417088721)*

**Pull request merged**
