### PR TITLE
Make fingers visible in wsg_50.urdf.xacro.

### PR DESCRIPTION
**Pull request by avalenzu**
Also updates wsg_50_mesh_collision.urdf.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7135)

### CODE REVIEW

**Comment by avalenzu** [comment]
This was reported by Marc Toussaint. +@rcory for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7135#-:-KvD4N6TFIVklA2O0si1:bwltwhi)*

**Comment by rcory** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7135#-:-KvDRHX4r0koWlBMpinz:bnfp4nl)*

**Comment by rcory** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7135)*

**Comment by avalenzu** [comment]
+@sherm1 for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7135#-:-KvDtpIzt63paVNB3qrc:bfvx2sg)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7135#-:-KvEQ5sgytNa2uPnVQgY:bnfp4nl)*

**Pull request merged**
