### PR TITLE
[pydrake] Add more examples of memory leaks

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14387.

+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21986)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21986#-:-O8IxH3E-wnm8so1JVs1:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: Nice!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21986#-:-O8J8w-k-VklOSUciGoR:b-8gk8uj)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21986#-O8JJyVr38omt0QQwohk:-O8JJyVr38omt0QQwohl:b-61w276) (no related file):*
BTW, the amount of "blocks" do not grow linearly when I run the test. Is that expected/do you understand why it's not the case?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21986)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21986#-O8JJyVr38omt0QQwohk:-O8JLNqT0rwytXqzKtkm:b4fxm5) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, the amount of "blocks" do not grow linearly when I run the test. Is that expected/do you understand why it's not the case?
</blockquote></details>

No idea.  I know that `sys.getallocatedblocks()` returns a python object which uses a block, so will have some variation depending on whether the number is interned or not, but that would only be a 1-ish block difference, not the 3-10 block variation I see.

___

**Pull request merged**
