### PR TITLE
Use C/C++ snopt-interface instead of snopt f2c

### PR DESCRIPTION
**Pull request by hongkai-dai**
This PR builds on top of #9101

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9103)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
The PR is not ready to merge yet. We should merge #9101 before this PR.

TODOs in this PR

- [ ] Figure out why the accuracy of the solution gets worse. Previously the difference between the solver solution and the analytical solution is below 1E-8, now it gets to 1.5E-6. This could be caused by some parameter change in the optimality tolerance.
- [ ] Test and run multiple snopt_solver simultaneously, which is the main motivation why we want to get rid of f2c in the first place.

**Comment by jwnimmer-tri** [comment]
It seems like, with the revised github-reviewable integration, you can't post 'bot requests through reviewable anymore:

@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by hongkai-dai** [comment]
I am still trying to find out why the accuracy of the solution gets changed after switching to snopt-interface. I reported an issue https://github.com/snopt/snopt-interface/issues/19 to snopt author, and we are working on it.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by sherm1** [comment]
@hongkai-dai the stated prerequisite for this PR, #9101 did merge. Is this ready for review and merge?

**Comment by jwnimmer-tri** [comment]
Aha.  I believe that #9177 supersedes this PR, but I will let @hongkai-dai confirm and close this if so.

**Comment by hongkai-dai** [comment]
Close this PR as we have #9177

**Pull request closed without merging**
