### PR TITLE
Separate out dependencies related to documentation generation

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #12783 and #13168. In two minds about whether to add the `--without-doc-only` flag, but it is here in this PR will can be tested during the CMake and/or packaging builds.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13984)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Comment by jamiesnape** [comment]
Missed adding the new switch to the `install_prereqs.sh` in `setup/{mac,ubuntu}`. Will add now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13984#-:-MGFK_3aCNiLbiI5DHOG:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform)

**Comment by jwnimmer-tri** [comment]
@jamiesnape when going the "commits are properly curated" route, please apply the label first thing in the PR before assigning, so that reviews can measure if it's done correctly.  (Alternatively, add the label by posting a message instead of the silent GitHub UI.)  I did not notice that the label got added here.

**Pull request merged**
