### PR TITLE
Removes the current rod2d piecewise DAE simulation components.

### PR DESCRIPTION
**Pull request by edrumwri**
The current piecewise DAE components for the 2D rod are set up to permit computing the dynamics in any mode. Determining the transitions for even this exceedingly simple system was too challenging. A new, far simpler piecewise DAE system has been successfully built and has successfully already been used for simulation.

I'd like to remove this existing code before pushing in the new code since they can't easily coexist (they use different abstract state variables) and because the mass of existing code is actually making the class hard to edit.

This PR removes the old code. Since there were a number of tests that the old code used, it stubs them with TODOs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7883)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7883#-:-L3slsZwy_6g_LaVb_SP:b1tu4a9)*

**Comment by sherm1** [comment]
Per f2f with Evan: this is an intermediate step that just removes the piecewise-DAE functionality in preparation for replacing it with a new and improved reimplementation that is more like an active set model than an enumerate-every-mode model that can't scale. Many of the now-removed test cases (stubbed with TODOs) will be restored to the same tests as before, although all the code they are testing is new. Feature :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7883#-:-L41tNCwoa7zO1zAZ0SO:ba1rjyh)*

**Comment by edrumwri** [comment]
+@jwnimmer-tri for platform review please (per regular rotation)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7883#-:-L41xgpU0XNVl5_pl_xo:b-zhq3gz)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform +(status: curate commits before merging) .

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7883#-:-L41zanS8Bt3G4UlYLNK:bcfcbes)*

**Pull request merged**
