### PR TITLE
[tools] Bump C++17 to C++20 in various CMake places

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #20964.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21247)

### CODE REVIEW

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21247#-:-NuVvi4tENkon-MmUHiN:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: :tada: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21247#-:-NuX0EZ35GMPiURxMm9K:by6fmpn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees mwoehlke-kitware,xuchenhan-tri(platform)

**Pull request merged**
