### PR TITLE
geometry::optimization Adds HPolyhedron::ChebyshevCenter()

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
@avalenzu for feature review, please.
cc @tobiamarcucci 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355#-:-MeBSgs59OoJ2bPwQSXw:bmk7al8)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by avalenzu — COMMENTED** [review]
+@avalenzu reporting for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355#-:-MeBTyhS-RUWpiA1Zxeg:b7f1add)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355#-:-MeBVq336R0uexJg4q_i:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one FYI

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355#-:-MeGf_p0E1_3PNFRHfrJ:b-8gr1rm)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/optimization/hpolyhedron.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15355#-MeGeVWT5x4pygQcndx9:-MeGeVWT5x4pygQcndxA:b-2h33wh) ([raw file](https://github.com/robotlocomotion/drake/blob/f810d6b9346f3bf4a79874ec45bc7920cabf46d5/geometry/optimization/hpolyhedron.h#L84)):*
> ```objc
>     │                                  │
>     │   ────────────────────────────   │
>     │                                  │
> ```

FYI the rhs of this box didn't format well in Reviewable. Be sure to check that it formats as you want it in Doxygen.

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355#-:-MeGff4L8dMsh7qypHVR:buasbda)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15355)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,sherm1(platform) (waiting on @avalenzu and @sherm1)

___
*[geometry/optimization/hpolyhedron.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15355#-MeGeVWT5x4pygQcndx9:-MeIK8zJ65FP1xGLqgOA:b-bbuzn8) ([raw file](https://github.com/robotlocomotion/drake/blob/f810d6b9346f3bf4a79874ec45bc7920cabf46d5/geometry/optimization/hpolyhedron.h#L84)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI the rhs of this box didn't format well in Reviewable. Be sure to check that it formats as you want it in Doxygen.
</blockquote></details>

Doxygen looks stunningly good!

**Pull request merged**
