### PR TITLE
[workspace] Upgrade meshcat to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Manual testing for https://github.com/meshcat-dev/meshcat/pull/165.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20805)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20805#-:-Nor7ol65_VVprT_OIAd:bmxilld)* status: needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: assuming a correct fix to the `working` item below and the commented manual testing.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20805#-:-NorNgDN8rjoaF-A9iCY:bok305b)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20805)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20805#-NorRJTa-ZP3hSV123Rp:-NorRJTb4ZAfOarxjGly:b6jwemp) (no related file):*
@SeanCurtis-TRI as a cross-check to confirm you've run the manual test, could you dismiss this thread as a confirmation?  We can merge once this thread is gone (pending CI).

___

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20805)* status: 1 unresolved discussion

**Pull request merged**
