### PR TITLE
gurobi_solver misses one infeasible return

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4732)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for both review. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-:-Ka98iu9l3dskvfmn3gl:b-9k0igv)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 582 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDkc7xq3uOsDd_NWOD:-KaDkc7xq3uOsDd_NWOE:b-2nutkc) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L582)):*
> ```cpp
>   double sparseness_threshold = 1e-14;
>   error = AddCosts(model, prog, sparseness_threshold);
>   DRAKE_ASSERT(!error);
> ```

Do these errors represent genuine bugs which shouldn't ever happen?  Or are they a response to user input problems with the constraints/costs?

---

*[drake/solvers/gurobi_solver.cc, line 584 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDkToURii_nuNTN1Le:-KaDkToURii_nuNTN1Lf:bc12i72) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L584)):*
> ```cpp
>   DRAKE_ASSERT(!error);
> 
>   if (!error) {
> ```

Asserting !error above makes the if blocks feel kinda pointless.

---

*[drake/solvers/gurobi_solver.cc, line 611 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDk3IVj0bEEXlce6PC:-KaDk3IWZ3Q5X74lgNhS:b-lhslbf) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L611)):*
> ```cpp
>       error = GRBsetdblparam(env, it.first.c_str(), it.second);
>       DRAKE_ASSERT(!error);
>       if (error) {
> ```

This code is now unreachable?  Or are you looking to deliberately make Debug and Release builds behave differently?

---

*[drake/solvers/gurobi_solver.cc, line 620 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDk9Yv7nZjbGirAW4Q:-KaDk9Yv7nZjbGirAW4R:b-w1iagy) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L620)):*
> ```cpp
>       error = GRBsetintparam(env, it.first.c_str(), it.second);
>       DRAKE_ASSERT(!error);
>       if (error) {
> ```

Unreachable (see above).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 582 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDkc7xq3uOsDd_NWOD:-KaDyUKPjJrPhHH5rcHz:b-y56u2h) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L582)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Do these errors represent genuine bugs which shouldn't ever happen?  Or are they a response to user input problems with the constraints/costs?
</blockquote></details>

It represents user input problems with constraints/costs. For example, if user specify a constraint with duplicate variables, such as `x + x = 1`, it will incur this error.

---

*[drake/solvers/gurobi_solver.cc, line 584 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDkToURii_nuNTN1Le:-KaDykXhDEczhtRzGUkX:bz0c6w1) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L584)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Asserting !error above makes the if blocks feel kinda pointless.
</blockquote></details>

I was thinking the assert is in the debug mode, if the user wants to debug the input problem. Do you think it better to use `DRAKE_DEMAND(!error)`, and delete this if statement?

---

*[drake/solvers/gurobi_solver.cc, line 611 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDk3IVj0bEEXlce6PC:-KaDz1GI9DI2fjklKT2-:bt8s9sv) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L611)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This code is now unreachable?  Or are you looking to deliberately make Debug and Release builds behave differently?
</blockquote></details>

I am trying to differentiate between Debug and Release builds, but probably we also want the program to fail in the Release build?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 584 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDkToURii_nuNTN1Le:-KaE1GdmEKb31z_QzIAK:btysyt6) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L584)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I was thinking the assert is in the debug mode, if the user wants to debug the input problem. Do you think it better to use `DRAKE_DEMAND(!error)`, and delete this if statement?
</blockquote></details>

I think I misunderstood something by not reading enough code for context. No issue here.

---

*[drake/solvers/gurobi_solver.cc, line 611 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDk3IVj0bEEXlce6PC:-KaE1f1KLHYUihmimMoL:bn25rkj) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L611)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am trying to differentiate between Debug and Release builds, but probably we also want the program to fail in the Release build?
</blockquote></details>

It's a little strange to me to check for and carefully return an error in one mode and assert in another, but I'm not going to object here (particularly since this code already does that a lot).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-:-KaE21Vr0t1RyE7eUn6K:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/solvers/gurobi_solver.cc, line 611 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaDk3IVj0bEEXlce6PC:-KaFVfof9bOcB-a8KUIM:b-hv0ls6) ([raw file](https://github.com/robotlocomotion/drake/blob/e20c5afd2b3127fade9652c0ad751637855febf7/drake/solvers/gurobi_solver.cc#L611)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's a little strange to me to check for and carefully return an error in one mode and assert in another, but I'm not going to object here (particularly since this code already does that a lot).
</blockquote></details>

I changed to DRAKE_DEMAND(!error).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaIAEuwryn3g6-sOCdq:-KaIAEuxm6utDFSbcdxe:b-q9dfh3) ([raw file](https://github.com/robotlocomotion/drake/blob/80752a331feef3a589fe3ad1d80e98172c10472b/drake/solvers/gurobi_solver.cc#L576)):*
> ```cpp
>   // TODO(naveenoid) : Properly handle gurobi specific error.
>   // message.
>   if (error) {
> ```

This check for error now seems strange given the DRAKE_DEMAND above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaIAEuwryn3g6-sOCdq:-KaJEq-LtUjlh5QKzpjn:bwiqh7z) ([raw file](https://github.com/robotlocomotion/drake/blob/80752a331feef3a589fe3ad1d80e98172c10472b/drake/solvers/gurobi_solver.cc#L576)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This check for error now seems strange given the DRAKE_DEMAND above.
</blockquote></details>

I removed the `DRAKE_DEMAND(!error)` before this if block. So if there is an error, it can only come from calling `GRBoptimize(model)`, which I think is more appropriate. All other `DRAKE_DEMAND(!error)` mean there should not be an error when parsing the optimization problem. But when the `optimize` function throws an error, that probably means the problem is parsed correctly, but there is other thing going wrong during optimization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaIAEuwryn3g6-sOCdq:-KaJQZ2omlL-DScJ1dOB:b-a6rlko) ([raw file](https://github.com/robotlocomotion/drake/blob/80752a331feef3a589fe3ad1d80e98172c10472b/drake/solvers/gurobi_solver.cc#L576)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I removed the `DRAKE_DEMAND(!error)` before this if block. So if there is an error, it can only come from calling `GRBoptimize(model)`, which I think is more appropriate. All other `DRAKE_DEMAND(!error)` mean there should not be an error when parsing the optimization problem. But when the `optimize` function throws an error, that probably means the problem is parsed correctly, but there is other thing going wrong during optimization.
</blockquote></details>

That works for me, though the comment above for "if any error exists so far" is probably out of date now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/gurobi_solver.cc, line 576 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4732#-KaIAEuwryn3g6-sOCdq:-KaKJYOZgYsAC-4GCaB9:bvid5lz) ([raw file](https://github.com/robotlocomotion/drake/blob/80752a331feef3a589fe3ad1d80e98172c10472b/drake/solvers/gurobi_solver.cc#L576)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

That works for me, though the comment above for "if any error exists so far" is probably out of date now.
</blockquote></details>

Done. Fix the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4732)*

**Pull request merged**
