### PR TITLE
Fix MathematicalProgram bindings for EvaluatorBase, add overloads for `EvalBindingAtSolution`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses issue #6069.

Note that `EvaluatorBase::lower_bound()` and `upper_bound()` will be moved in the final parts of #5890.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6070)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please.
+@soonho-tri for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-Kjo395QwXsrNnesJ-Pw:bq4p0lu)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjrdOF_I4G6YxFblwFj:-KjrdOF_I4G6YxFblwFk:b-a83ds6) ([raw file](https://github.com/robotlocomotion/drake/blob/0a9e20ebb4172fa51f186f6475abf68d4e28990b/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L36)):*
> ```cpp
> template <typename C>
> auto RegisterBinding(py::handle scope,
>                      py::class_<MathematicalProgram>* pprog_cls,
> ```

What does `cls` stand for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjrdOF_I4G6YxFblwFj:-KjrklCRIQ8C77-APjuY:bf4wdsh) ([raw file](https://github.com/robotlocomotion/drake/blob/0a9e20ebb4172fa51f186f6475abf68d4e28990b/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L36)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

What does `cls` stand for?
</blockquote></details>

I'm sure that it stands for "class". 

http://stackoverflow.com/questions/4613000/what-is-the-cls-variable-used-in-python-classes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by hongkai-dai** [comment]
Almost :lgtm: Is there a unit test for the python binding with mathematical program, that calls `EvalBindingAtSolution`?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-KjrtnReBP8aOjZFuWJa:b-d4ywp1)*

**Comment by EricCousineau-TRI** [comment]
Yup! `testMathematicalProgram` has `test_eval_binding`. I have extended this to consume the available constraint types and test those.

Caveat is, at present, the tests are disabled due to #5862 and #5863.

@soonho-tri: I added in an additional feature, incorporating logical operators for conjunction and disjunction. Unfortunately, Python does not permit overloading logical operators, so I've overloaded the bitwise operators. Pain point here is that order-of-operations means you need to include parentheses.

Let me know if you'd like me to split this off into a separate PR.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjrdOF_I4G6YxFblwFj:-Kjs8t72t55SqcY-ytN6:b-uupt0m) ([raw file](https://github.com/robotlocomotion/drake/blob/0a9e20ebb4172fa51f186f6475abf68d4e28990b/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L36)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm sure that it stands for "class". 

http://stackoverflow.com/questions/4613000/what-is-the-cls-variable-used-in-python-classes
</blockquote></details>

Yup! Would you 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-Kjs9A-FD9Qwgu0u-lN5:b49zhi4)*

**Comment by EricCousineau-TRI** [comment]
*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjrdOF_I4G6YxFblwFj:-KjsheOBRASACM-XKi7t:b42hvyj) ([raw file](https://github.com/robotlocomotion/drake/blob/0a9e20ebb4172fa51f186f6475abf68d4e28990b/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yup! Would you 
</blockquote></details>

BTW Sorry, above I was going to ask if you wanted me to add in a comment, but I went ahead and did it, and forgot to change the text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-Kjt2dxM94qEFz6PV2S5:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjxmrRyokiUSUgX9FZ7:-KjxmrRyokiUSUgX9FZ8:b-ickrye) ([raw file](https://github.com/robotlocomotion/drake/blob/1fdcc542729a572e791f3a3b09fd1c69029dd3bc/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L42)):*
> ```cpp
>  */
> template <typename C>
> auto RegisterBinding(py::handle scope,
> ```

`py::handle scope` -> `const py::handle& scope`?

---

*[drake/bindings/pybind11/pydrake_symbolic.cc, line 229 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjxlXROE9pHVtm2Ar2X:-KjxlXROE9pHVtm2Ar2Y:b-4pbna8) ([raw file](https://github.com/robotlocomotion/drake/blob/1fdcc542729a572e791f3a3b09fd1c69029dd3bc/drake/bindings/pybind11/pydrake_symbolic.cc#L229)):*
> ```cpp
> 
>   // Cannot overload logical operators: http://stackoverflow.com/a/471561
>   // Can use the bitwise operators, __and__ (&) + __or__ (|):
> ```

Thanks for the checks. 

I'm not sure that using bitwise operators (`&` and `|`) is the right thing to do here. I'm inclined to provide functions `logic_and` and `logic_or` (or variants). I'm happy to hear what other people think on this (users of our python binding).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by soonho-tri** [comment]
First pass done. PTAL.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-KjxsMQ1jrJpFdpRAXqC:b-1tzs3z)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjxmrRyokiUSUgX9FZ7:-Kk7ijE5Bu4zXWktS5Ok:b-4f628z) ([raw file](https://github.com/robotlocomotion/drake/blob/1fdcc542729a572e791f3a3b09fd1c69029dd3bc/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L42)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`py::handle scope` -> `const py::handle& scope`?
</blockquote></details>

Done. `pybind11` is a little awkward for our style standards, in that `scope` is effectively a Python reference. For now, I've just changed it to a mutable pointer to make it clear. I can change it back to `const T&` as long as it's clear that it will mutate something transiently connected to the module.

---

*[drake/bindings/pybind11/pydrake_symbolic.cc, line 229 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-KjxlXROE9pHVtm2Ar2X:-Kk7hrE5gN3yXtYYXhsX:b-25xo9o) ([raw file](https://github.com/robotlocomotion/drake/blob/1fdcc542729a572e791f3a3b09fd1c69029dd3bc/drake/bindings/pybind11/pydrake_symbolic.cc#L229)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Thanks for the checks. 

I'm not sure that using bitwise operators (`&` and `|`) is the right thing to do here. I'm inclined to provide functions `logic_and` and `logic_or` (or variants). I'm happy to hear what other people think on this (users of our python binding).
</blockquote></details>

Done. Made `logical_and` and `logical_or` for the time being. Want me to make another issue for potentially changing this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 6 files at r3.
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/bindings/python/pydrake/symbolic.py, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-Kk8Wn5OgMNVhM3Rzbz0:-Kk8Wn5OgMNVhM3Rzbz1:bv9x127) ([raw file](https://github.com/robotlocomotion/drake/blob/a4794c562b000093327f558df71e5feacc31b528/drake/bindings/python/pydrake/symbolic.py#L8)):*
> ```Python
> from ._pydrake_symbolic import __logical_and, __logical_or
> 
> def logical_and(*formulas):
> ```

Need one more blank line above (because of python lint)?

---

*[drake/bindings/python/pydrake/symbolic.py, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-Kk8WndvhfK7aV0y8nUL:-Kk8WndvhfK7aV0y8nUM:bv9x127) ([raw file](https://github.com/robotlocomotion/drake/blob/a4794c562b000093327f558df71e5feacc31b528/drake/bindings/python/pydrake/symbolic.py#L12)):*
> ```Python
>     return reduce(__logical_and, formulas)
> 
> def logical_or(*formulas):
> ```

Need one more blank line above (because of python lint)?

---

*[drake/bindings/python/pydrake/test/testSymbolic.py, line 77 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-Kk8WgChVsZg3pnTn81t:-Kk8WgChVsZg3pnTn81u:bv9x127) ([raw file](https://github.com/robotlocomotion/drake/blob/a4794c562b000093327f558df71e5feacc31b528/drake/bindings/python/pydrake/test/testSymbolic.py#L77)):*
> ```Python
>         self.assertEqual(str(sym.logical_or(x >= 1, x <= 2, y == 2)),
>                          "((y = 2) or (x >= 1) or (x <= 2))")
> ```

Need one more blank line above (because of python lint)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/python/pydrake/symbolic.py, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-Kk8Wn5OgMNVhM3Rzbz0:-Kk8YraPYD8pS9etNq-y:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/a4794c562b000093327f558df71e5feacc31b528/drake/bindings/python/pydrake/symbolic.py#L8)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Need one more blank line above (because of python lint)?
</blockquote></details>

Done. Thanks!

---

*[drake/bindings/python/pydrake/symbolic.py, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-Kk8WndvhfK7aV0y8nUL:-Kk8Ys6P4kDOESumkN_r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4794c562b000093327f558df71e5feacc31b528/drake/bindings/python/pydrake/symbolic.py#L12)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Need one more blank line above (because of python lint)?
</blockquote></details>

Done.

---

*[drake/bindings/python/pydrake/test/testSymbolic.py, line 77 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-Kk8WgChVsZg3pnTn81t:-Kk8YsjPWl3BhqXeOP09:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4794c562b000093327f558df71e5feacc31b528/drake/bindings/python/pydrake/test/testSymbolic.py#L77)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Need one more blank line above (because of python lint)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by soonho-tri** [comment]
@ericcousineau-tri , we still have test failures in CI. Could you check?

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-KkBBR1eHc0cEugkzY3y:b-gqtbej)*

**Comment by EricCousineau-TRI** [comment]
I believe the latest push should fix it. Thanks for the heads up!

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070#-:-KkCCIWcXBtEs8O-S2Vt:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6070)*

**Pull request merged**
