### PR TITLE
[geometry/optimization] Fix corner case in HPolyhedron::UniformSample

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously, it was possible for the sampler to happily return points outside of the region, if the polytope was overspecified (points outside of the set where still inside some redudant half-planes). This provides the fix and adds a test.

+@mpetersen94 for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
:lgtm: Looks like you need to update the binding of Uniform Sample to match the new signature types.

 
+@rpoyner-tri for platform review

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982#-:-NCzCDTK6rOCMjqI5vRg:b6o2cjw)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

___
*[`geometry/optimization/hpolyhedron.cc` line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17982#-NCzXKNL9Divio6Al-aa:-NCzXKNM81sspZJRv3Ik:b-93iqq2) ([raw file](https://github.com/robotlocomotion/drake/blob/f14da56a03e4c63f02a987f51e56fc4ca6a90edc/geometry/optimization/hpolyhedron.cc#L249)):*
> ```cpp
>   }
>   if (std::isinf(theta_max) || std::isinf(theta_min) || theta_max < theta_min) {
>     throw std::invalid_argument(fmt::format(
> ```

I confirmed the hunch expressed below by adding assertion here. They are never reached under the unit test.


speculation: is this different on macos vs ubuntu? I will investigate.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 751 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17982#-NCzWRy9-9VWH6CmztJ3:-NCzWRy9-9VWH6CmztJ4:bw6d4w3) ([raw file](https://github.com/robotlocomotion/drake/blob/f14da56a03e4c63f02a987f51e56fc4ca6a90edc/geometry/optimization/test/hpolyhedron_test.cc#L751)):*
> ```cpp
>       EXPECT_TRUE(H.PointInSet(sample, 1e-12));
>     } catch (const std::exception& err) {
>       auto matcher = [](const char* s, const std::string& re) {
> ```

I have some doubts about test coverage, since my local fiddling led me to discover that the catch block of this test is never executed. Since the behavior change it represents appears to be the substance of the bug, probably need more/different inputs.

note: for whatever reason, `kcov` did not produce any data from running these tests. I supplemented with sprinklings of `DRAKE_DEMAND(false);`.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`geometry/optimization/hpolyhedron.cc` line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17982#-NCzXKNL9Divio6Al-aa:-NCzZd5Z0qS67Rxr-EG7:b-8suu2z) ([raw file](https://github.com/robotlocomotion/drake/blob/f14da56a03e4c63f02a987f51e56fc4ca6a90edc/geometry/optimization/hpolyhedron.cc#L249)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I confirmed the hunch expressed below by adding assertion here. They are never reached under the unit test.


speculation: is this different on macos vs ubuntu? I will investigate.
</blockquote></details>

Local experiments suggest that the macos build does not execute this branch either.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982#-:-ND-7D1Q4KcY30DHOJHA:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by mpetersen94 — COMMENTED** [review]
All looks good to me! Squash and merge away!

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17982#-:-ND-AfV0CAl35clZEMHw:b9qg9u2)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
