### PR TITLE
Differential inverse kinematics 

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7921)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@avalenzu for feature review. thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-:-L4OnD3VExWyWr0ksCaM:b-idgx2t)*

**Comment by avalenzu** [comment]
:lgtm: with a few BTWs. +@ericcousineau-tri  for platform review

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bkUOFgamuetW4YNSZ:-L4bkUOFgamuetW4YNS_:b-vclh70) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L81)):*
> ```cpp
>     prog.AddLinearEqualityConstraint(
>         A, VectorX<double>::Zero(num_cart_constraints), {v_next, alpha});
>     cart_cost = prog.AddQuadraticErrorCost(drake::Vector1<double>(100),
> ```

BTW could this `100` be a named variable?

---

*[manipulation/planner/differential_inverse_kinematics.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bksWm_pIc3RsWpy1m:-L4bksWm_pIc3RsWpy1n:bqsxqbn) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.h#L57)):*
> ```objc
>    * @p num_positions. Timestep is initialized to 1. The end effector gains are
>    * initialized to ones. All position and velocity gains are initialized to
>    * none.
> ```

BTW "none" should probably be "nullopt"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-:-L4blj_CmNofUEbvixVD:b-vb1hnw)*

**Comment by EricCousineau-TRI** [comment]
First pass done, PTAL. Concerned about the number of overloads. Otherwise, looks good.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bzsG1Hqa6N_ysE-gd:-L4bzsG2hil5HjC2GYym:b-s6ti0e) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L77)):*
> ```cpp
>     // and penalize magnitude difference from V_WE_E_mag.
>     MatrixX<double> A(num_cart_constraints, num_velocities + 1);
>     A.topLeftCorner(num_cart_constraints, num_velocities) = J;
> ```

This may have uninitialized junk in it.
Could you ensure that this is set to zero? And possibly run this through some addition *San checks, like ASan and UBSan?

`auto A = MatrixX<double>::Zero(...).eval()`?

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c-Gt0V75tps8snoe_:-L4c-Gt0V75tps8snoea:bjyovdr) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L89)):*
> ```cpp
> 
>     // Add constrained the unconstrained dof's velocity to be small, which is
>     // used
> ```

BTW Odd linewrap.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c-IwFT7C29DXCCVZF:-L4c-IwGrs6vdytY8H_W:breeb76) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L90)):*
> ```cpp
>     // Add constrained the unconstrained dof's velocity to be small, which is
>     // used
>     // to fullfil the regularization cost.
> ```

BTW Spelling, `fulfill`

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c-a7XR4lLWluiBCNj:-L4c-a7YC3Xh1YilNiNW:beldy6x) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L143)):*
> ```cpp
>     cart_cost->Eval(prog.GetSolution(alpha), cost);
>     // Not tracking the desired vel norm, and computed vel is small.
>     if (cost(0) > 5 && prog.GetSolution(alpha)[0] <= 1e-2) {
> ```

BTW Could these constants be named variables, `cost_max` and `alpha_min` or something, and could there be some indication of how they came about? (I guess through experimentation?)
Also, could the comment be moved inside the `if` statement, or reword the comment to "Check if it's not tracking ..."?

---

*[manipulation/planner/differential_inverse_kinematics.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c0aIyEL5bojQcVWho:-L4c0aIyEL5bojQcVWhp:b-r3l4t4) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.h#L205)):*
> ```objc
> };
> 
> DifferentialInverseKinematicsResult DoDifferentialInverseKinematics(
> ```

Could you add documentation to these functions? (cross-referencing other overloads, if you want.)
Also, is there a way to reduce the number of overloads present?

Perhaps keep just the "raw" version that takes the robot + cache and all that, and just one "sugar" version, which computes `V_WE_current` and `X_WE_desired` for you?
(Or even, perhaps make `optional<>` arguments, that are evaluated if `nullopt` is supplied?)

Additionally, only the "raw" overload seems to be tested - perhaps another reason to consider reducing the number of overloads?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-:-L4c1pjkzgXRxQe7h8rt:b-it427s)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bzsG1Hqa6N_ysE-gd:-L4d2_E-RYksOIk7Nxuw:b7kuys0) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L77)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This may have uninitialized junk in it.
Could you ensure that this is set to zero? And possibly run this through some addition *San checks, like ASan and UBSan?

`auto A = MatrixX<double>::Zero(...).eval()`?
</blockquote></details>

hmm, A should be fully set. it's num_cart by num_v + 1, and J is num_car by num_v, and V_dir is num_car by 1. Do I still need to init it to zero? 

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bkUOFgamuetW4YNSZ:-L4d3A6WPaa2uU62StQ6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L81)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW could this `100` be a named variable?
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c-Gt0V75tps8snoe_:-L4d3E1Bf2_T4cb-30N_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Odd linewrap.
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c-IwFT7C29DXCCVZF:-L4d3EJP3-gTfPVDCn0i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L90)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Spelling, `fulfill`
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c-a7XR4lLWluiBCNj:-L4d3iZYIhfy1YJNXRbu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Could these constants be named variables, `cost_max` and `alpha_min` or something, and could there be some indication of how they came about? (I guess through experimentation?)
Also, could the comment be moved inside the `if` statement, or reword the comment to "Check if it's not tracking ..."?
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bksWm_pIc3RsWpy1m:-L4d4MYtYX_KYiIF0kYF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.h#L57)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW "none" should probably be "nullopt"
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4c0aIyEL5bojQcVWho:-L4dIDproDdY5JyRYGY3:b1etaic) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.h#L205)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Could you add documentation to these functions? (cross-referencing other overloads, if you want.)
Also, is there a way to reduce the number of overloads present?

Perhaps keep just the "raw" version that takes the robot + cache and all that, and just one "sugar" version, which computes `V_WE_current` and `X_WE_desired` for you?
(Or even, perhaps make `optional<>` arguments, that are evaluated if `nullopt` is supplied?)

Additionally, only the "raw" overload seems to be tested - perhaps another reason to consider reducing the number of overloads?
</blockquote></details>

removed two overload. switched one of the test to use the X_WE version. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bzsG1Hqa6N_ysE-gd:-L4dJMQAtL9fmyXxt6WM:blrcq6g) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L77)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

hmm, A should be fully set. it's num_cart by num_v + 1, and J is num_car by num_v, and V_dir is num_car by 1. Do I still need to init it to zero? 
</blockquote></details>

OK D'oh, my bad. Was just looking at the method names, did not notice the names.

There's also `A.leftCols(num_velocities) = J` and `A.rightCols(1) = -V_dir`, which would be a little bit clearer, but functionally the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-:-L4dKGKnyXupVvoNIIq_:bnfp4nl)*

**Comment by avalenzu** [comment]
:lgtm_cancel: See comment on `nullptr` access.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 70 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/7921#-L4fO34E69wSLIM1HThT:-L4fO34E69wSLIM1HThU:b-b05kt) ([raw file](https://github.com/robotlocomotion/drake/blob/fa39d4726bbecaa21f1f03187849da4a18dac0d6/manipulation/planner/differential_inverse_kinematics.cc#L70)):*
> ```cpp
> 
>   if (num_cart_constraints > 0 &&
>       parameters.get_unconstrained_degrees_of_freedom_velocity_limit()) {
> ```

This can cause a SEGFAULT due to `cart_cost` being `nullptr`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7921#-:-L4fOV1y42MYABBeenfj:bylv83q)*

**Comment by avalenzu** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 70 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/7921#-L4fO34E69wSLIM1HThT:-L4fPFRmC8j_IQz1ERjs:b-gger1n) ([raw file](https://github.com/robotlocomotion/drake/blob/fa39d4726bbecaa21f1f03187849da4a18dac0d6/manipulation/planner/differential_inverse_kinematics.cc#L70)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

This can cause a SEGFAULT due to `cart_cost` being `nullptr`
</blockquote></details>

Sorry, this comment is in the wrong place. See the one further down for the SEGFAULT issue. However, I do wonder why we're checking `get_unconstrained_degrees_of_freedom_velocity_limit()` here. Shouldn't the presence or absence of that parameter only affect the constraints based on the SVD decomposition?

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 142 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/7921#-L4fOlDB1oXFswLD81r_:-L4fOJmrDe36pzVfgE3Z:bm1cpyb) ([raw file](https://github.com/robotlocomotion/drake/blob/fa39d4726bbecaa21f1f03187849da4a18dac0d6/manipulation/planner/differential_inverse_kinematics.cc#L142)):*
> ```cpp
>   if (num_cart_constraints) {
>     Eigen::VectorXd cost(1);
>     cart_cost->Eval(prog.GetSolution(alpha), cost);
> ```

`cart_cost` can be `nullptr` here if `unconstrained_degrees_of_freedom_velocity_limit` is `nullopt`. We need to either check for `nullptr` here, or (my preference) change the logic above so that `cart_cost` is non-null whenever `num_cart_constraints` is non-zero.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7921)*

**Comment by siyuanfeng-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4bzsG1Hqa6N_ysE-gd:-L4dL3YqPxrQFZDby9pX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0042c77f932f434864a0233bc6b8b8544da33823/manipulation/planner/differential_inverse_kinematics.cc#L77)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

OK D'oh, my bad. Was just looking at the method names, did not notice the names.

There's also `A.leftCols(num_velocities) = J` and `A.rightCols(1) = -V_dir`, which would be a little bit clearer, but functionally the same.
</blockquote></details>

Done.

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 70 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4fO34E69wSLIM1HThT:-L4fSp1hFugKHeIBP8xh:bvg4a1s) ([raw file](https://github.com/robotlocomotion/drake/blob/fa39d4726bbecaa21f1f03187849da4a18dac0d6/manipulation/planner/differential_inverse_kinematics.cc#L70)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Sorry, this comment is in the wrong place. See the one further down for the SEGFAULT issue. However, I do wonder why we're checking `get_unconstrained_degrees_of_freedom_velocity_limit()` here. Shouldn't the presence or absence of that parameter only affect the constraints based on the SVD decomposition?
</blockquote></details>

good catch. probably come from refactoring. see if this one makes more sense. 

---

*[manipulation/planner/differential_inverse_kinematics.cc, line 142 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-L4fOlDB1oXFswLD81r_:-L4fSwH7WfBdkhxXJHQZ:bdiaf4t) ([raw file](https://github.com/robotlocomotion/drake/blob/fa39d4726bbecaa21f1f03187849da4a18dac0d6/manipulation/planner/differential_inverse_kinematics.cc#L142)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

`cart_cost` can be `nullptr` here if `unconstrained_degrees_of_freedom_velocity_limit` is `nullopt`. We need to either check for `nullptr` here, or (my preference) change the logic above so that `cart_cost` is non-null whenever `num_cart_constraints` is non-zero.
</blockquote></details>

see above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921)*

**Comment by avalenzu** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7921#-:-L4k4gQLtV456Ia044k0:bnfp4nl)*

**Pull request merged**
