### PR TITLE
Do not double up on the stx subdir for header isntallation

### PR DESCRIPTION
**Pull request by stonier**
previously installing in include/stx/stx/optional.hpp

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7257)

### CODE REVIEW

**Comment by stonier** [comment]
+@jamiesnape for feature review

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7257#-:-KwMaolQ8jFw1Rt4g03_:b9itq1i)*

**Comment by jamiesnape** [comment]
This should be a no-op and it is desirable not to have `@prefix@/include` in the include path.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7257#-:-KwMbJbbcYc-rInbvCcO:b-ix3tuu)*

**Comment by jamiesnape** [comment]
The fix is to add `stx:stx` here: 

https://github.com/RobotLocomotion/drake/blob/331c2f5e17e17abc26b0ebf063527ed3d8e43ec6/tools/drake.cps#L101

Quite possibly other entries are missing from that list.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7257#-:-KwMcSpuFtddIAWYesY_:b-uj180b)*

**Comment by stonier** [comment]
1. It's header only, it shouldn't be in that dylib list right?
2. hdr_dest removed (you're right, include is default)
3. The `@prefix/include` should just be dropped? Many other dependencies are using that format (e.g. fcl)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7257#-:-KwMdTBlH21O6vRdIUMd:bgxope7)*

**Comment by jamiesnape** [comment]
I prefer what is in master to this. If other libraries are dumping headers straight into @prefix@/include, that should be fixed. It is not a list of dylibs, it is a list of CMake targets, so it must be included. This PR should just be the addition I suggested, nothing else.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7257#-:-KwMx1_mf1DDZoBzbd-J:bm19nzr)*

**Comment by jwnimmer-tri** [comment]
I agree with Jamie.  I was careful to examine the install tree in #7241 to make sure it matched our CMake install's best practices and the other modules, but I failed to remember to update `drake.cps` with the new dependency, so that one was my bad (sorry!).  I agree with his example one-line fix as the only thing needed.

**Comment by stonier** [comment]
Right, I'm up to speed with what cps is doing in drake.cps. 

However, I do not see any reason for the double directory in `include/stx/stx/optional.hpp`. It is not the library's [original intention](https://github.com/tcbrindle/cpp17_headers/blob/master/include/stx/optional.hpp) and doesn't follow the convention used by the other third party applications here. Either bundle them all in the same include directory as drake with appropriate relative paths (so someone with a build system other than CMake can just point at the `<prefix>/include` directory with non-surprising results), or shift all the third party headers to a different prefix, but again, without the double stx path.

**Comment by jamiesnape** [comment]
> so someone with a build system other than CMake can just point at the <prefix>/include directory with non-surprising results

The point is exactly the opposite. You should be correctly declaring the include directories, and by having everything thrown into one directory things will accidentally work and you will not spot errors like this PR is supposed to fix. CMake does not enforce best practice (compared to Bazel), but that does not mean you should avoid it.

**Comment by stonier** [comment]
I'm not really trying to make arguments for purity to the Nth degree or otherwise. If we're going to go one way or the other, why start here? There is no consistency in this - hence it will cause surprises.

**Comment by jamiesnape** [comment]
Most of the other packages follow what is in master for this particular package, and that was the original intention, hence if there is to be consistency, it should go in that direction. The other packages should be fixed rather than this one regressing.

**Comment by jwnimmer-tri** [comment]
I pushed the `drake.cps` fix in as #7265.  This PR can now focus on only the `#include`-path-related discussions.

**Pull request closed without merging**
