### PR TITLE
add lqr example to the acrobot

### PR DESCRIPTION
**Pull request by RussTedrake**
N.B. - I've changed both acrobot examples to run at realtime rates (which makes them actually useful as an example and for development).  But it means that, as tests, they will run slower.  Let's discuss.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4252)

### CODE REVIEW

**Comment by liangfok** [comment]
Perhaps allow the real time rate to be disabled via a command line parameter.

**Comment by RussTedrake** [comment]
good point @liangfok .  that's what we did in system 1.0.  will do.

**Comment by naveenoid** [comment]
Reviewed 2 of 6 files at r1, 2 of 3 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ2ibGfILNSipAE-hv:-KXQ2ibH2DBo73_6UPhK:b3lyor3) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_plant.cc#L123)):*
> ```cpp
>   // roughly address difference in units, using sqrt(g/l) as the time constant.
>   Eigen::Matrix4d Q = Eigen::Matrix4d::Identity();
>   Q(0, 0) = 10;
> ```

Perhaps the gain matrices need exposing in the API? Or perhaps in the arguments of this method?

---

*[drake/examples/Acrobot/acrobot_plant.h, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ2T3eCE9_56OetBnl:-KXQ2T3eCE9_56OetBnm:b258aa8) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_plant.h#L72)):*
> ```objc
>       g{9.81};    // Gravitational constant (m/s^2).
> };
> ```

BTW: Consider a doxygen / direct comment mentioning the purpose of this controller method.

---

*[drake/examples/Acrobot/acrobot_run_lqr.cc, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ1QlsCR4zfvAn7YuQ:-KXQ1QlsCR4zfvAn7YuR:bmrcydr) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_run_lqr.cc#L22)):*
> ```cpp
>               "Playback speed.  See documentation for "
>               "Simulator::set_target_realtime_rate() for details.");
> ```

BTW: Since this is one of those examples which also acts as a unit test, it might be really useful to have a comment here explaining whats being demo'd here.

---

*[drake/examples/Acrobot/acrobot_run_lqr.cc, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ1ro8-SRtn6Jyz662:-KXQ1ro8-SRtn6Jyz663:b-8bmif5) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_run_lqr.cc#L47)):*
> ```cpp
>   AcrobotStateVector<double>* x0 = dynamic_cast<AcrobotStateVector<double>*>(
>       acrobot_context->get_mutable_continuous_state_vector());
>   DRAKE_DEMAND(x0 != nullptr);
> ```

BTW: A comment here on this particular choice of initial condition might be useful..

---

*[drake/examples/Acrobot/acrobot_run_lqr.cc, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ1gkxlHfqJqQqVHSQ:-KXQ1gkxlHfqJqQqVHSR:bo21e9l) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_run_lqr.cc#L55)):*
> ```cpp
>   simulator.set_target_realtime_rate(FLAGS_realtime_factor);
>   simulator.Initialize();
>   simulator.StepTo(10);
> ```

BTW: Might be interesting from the unit-test viewpoint to have a DRAKE_DEMAND here on the terminal state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4252)*

**Comment by RussTedrake** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ2ibGfILNSipAE-hv:-KXQ6BvSqL926pIySZ3f:b-qcwokd) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_plant.cc#L123)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Perhaps the gain matrices need exposing in the API? Or perhaps in the arguments of this method?
</details>
i thought about it, but the whole point of this method existing is that it encodes a set of Q, R, x0, and u0 matrices which work (so that we can instantiate the balance controller quickly in lots of exes).  

---

*[drake/examples/Acrobot/acrobot_plant.h, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ2T3eCE9_56OetBnl:-KXQPW-tqAVxD2GSZ4sg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_plant.h#L72)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Consider a doxygen / direct comment mentioning the purpose of this controller method.
</details>
Done.

---

*[drake/examples/Acrobot/acrobot_run_lqr.cc, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ1QlsCR4zfvAn7YuQ:-KXQPsUdYeQVscBSDVgT:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_run_lqr.cc#L22)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Since this is one of those examples which also acts as a unit test, it might be really useful to have a comment here explaining whats being demo'd here.
</details>
Done. 

---

*[drake/examples/Acrobot/acrobot_run_lqr.cc, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ1ro8-SRtn6Jyz662:-KXQQ47A_84Go_spiCFj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_run_lqr.cc#L47)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: A comment here on this particular choice of initial condition might be useful..
</details>
Done.

---

*[drake/examples/Acrobot/acrobot_run_lqr.cc, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ1gkxlHfqJqQqVHSQ:-KXQQ6Hgr8aXIg8ogTJj:bo7wtgh) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_run_lqr.cc#L55)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Might be interesting from the unit-test viewpoint to have a DRAKE_DEMAND here on the terminal state.
</details>
Agreed, but it does not converge very close to zero in 10 seconds.  I could imagine confirming that the total energy of the system has decreased, but that would require implementing all of the energy logic (which we'll get for free from the RBT version later).   I can't think of a useful test to include here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4252)*

**Comment by naveenoid** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-KXQ2ibGfILNSipAE-hv:-KXQag8I3FT-Mb3In-_O:bq6uhab) ([raw file](https://github.com/robotlocomotion/drake/blob/ac4fa804175898c6c3b60b5f4718305c494781ed/drake/examples/Acrobot/acrobot_plant.cc#L123)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i thought about it, but the whole point of this method existing is that it encodes a set of Q, R, x0, and u0 matrices which work (so that we can instantiate the balance controller quickly in lots of exes).  
</details>
Ok. Now it makes sense especially considering your new doxygen comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4252)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-:-KXQb5Dw_Y-s5lG0Iddm:bnfp4nl)*

**Comment by sherm1** [comment]
Platform review: I ran both examples and they look great, as does the code. :lgtm:

---

Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4252#-:-KXYP0Xf1hrRwnotMi9U:b-t6jo6s)*

**Pull request merged**
