### PR TITLE
Tweaked the TOC placement of multibody dynamics constraints.

### PR DESCRIPTION
**Pull request by edrumwri**
Per @russtedrake's request.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8965)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please (Alejandro, the module ordering in multibody dynamics concepts is not what I prefer, but Doxygen does not appear to provide a means to change it- please let me know wha tyou think).

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8965#-:-LEeYYoq1jBUSgaWfU52:bbdf44l)*

**Comment by amcastro-tri** [comment]
I see what you are saying. Compiling the docs now shows:


And we'd like "Multibody dynamics constraints in Drake" to be the last section under "Multibody Dynamics Concepts"

---

Review status: all discussions resolved, LGTM missing from assignee amcastro-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8965#-:-LEj6Uc_CnQNDWqJjnFK:bod4nkv)*

**Comment by jwnimmer-tri** [comment]
@edrumwri Perhaps 9c27cc2410fd759b89d0bb9f5ae1a04b63705cb5 has already fixed this?  Can this PR be closed?

image

**Comment by edrumwri** [comment]
Yep, looks good.

**Pull request closed without merging**
