### PR TITLE
jupyter: Add interactive_update functions

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
From discussion in #14059

To run notebook for local testing:
```
$ bazel run //bindings/pydrake/common:jupyter_example
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzAzqEElfLQ10y3WE:-MHQzAzr-J_sXwgUqFeV:b5sgdws) (no related file):*
Working: Requires provisioning.

Unittests will fail atm.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzE6f6RmZEzDkV7Qd:-MHQzE6f6RmZEzDkV7Qe:bd8kcln) (no related file):*
Working: Should check if plots are affected on `ipywidgets<7.0.0`.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzIi5294DrmY74eLd:-MHQzIi5294DrmY74eLe:b-3qvoma) (no related file):*
Working: Should confirm that "dynamic" widget updating does indeed work with `ipywidgets>=7.0.0`.

(It worked in Anzu...)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for review / discussion.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082#-:-MHQzRT7B61NGFjjhFyD:b-ksuzf)* status: 5 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzToUCOSsTyMo_ai6:-MHQzToUCOSsTyMo_ai7:b-7imr1m) (no related file):*
Working: If this is deemed useful, I'll spiff up the notebook with slightly more text.

---
___
*[bindings/pydrake/common/jupyter.py, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzaGL-r2YbVuTmQp6:-MHQzaGL-r2YbVuTmQp7:b-4s56hi) ([raw file](https://github.com/robotlocomotion/drake/blob/43b86ab3dcb6fc2804e4270d987d2d9a876a1847/bindings/pydrake/common/jupyter.py#L102)):*
> ```Python
>     assert isinstance(out, widgets.Output), out
>     with out:
>         clear_output(wait=True)
> ```

Working: Errors are generally painful to handle when they get redirected.

Should add an option to just spew errors at the place of invocation, rather than in the output cell.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzIi5294DrmY74eLd:-MHR39SY7tzYOEswJxvJ:b-jzogmw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should confirm that "dynamic" widget updating does indeed work with `ipywidgets>=7.0.0`.

(It worked in Anzu...)
</blockquote></details>

OK Confirmed that the conditional section works as expected with this setup (see requirements and `tmp.md`):
7098b15881

(Not exactly sure if it's just `ipywidgets` that does this, but eh. I think it's a fair enough assessment for now.)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzE6f6RmZEzDkV7Qd:-MHR3x_jAMD8xatxfjpO:bxf76dc) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should check if plots are affected on `ipywidgets<7.0.0`.
</blockquote></details>

OK Confirmed that (for Bionic apt versions), the following does *not* redirect the plot to the output cell:
```
with interactive_update(out):
        plt.plot(0, 0)
```

As mentioned below, it *does* work for later versions.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[bindings/pydrake/common/jupyter.py, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14082#-MHQzaGL-r2YbVuTmQp6:-MHRBd11AeLcjrFWXKLv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43b86ab3dcb6fc2804e4270d987d2d9a876a1847/bindings/pydrake/common/jupyter.py#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Errors are generally painful to handle when they get redirected.

Should add an option to just spew errors at the place of invocation, rather than in the output cell.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI @RussTedrake we are approaching 6 months here without any updates.  Would you like to push this over the finish line, or close it to be resurrected when needed later on?

**Comment by EricCousineau-TRI** [comment]
I've found these to be useful when doing interactive things w/ rendered cameras, or wanting to do dynamic plots w/o actually having to think about matplotlib animation.

Will request add'l feature reviewer.

**Review by EricCousineau-TRI — COMMENTED** [review]
-@russtedrake +@avalenzu Would you be for reviewing this at the start of next Q?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082#-:-MVaze1R25Ostp4PHfJE:b7hmqww)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu and @EricCousineau-TRI)

**Review by avalenzu — COMMENTED** [review]
Sure. So you're OK with me not looking at this until April 1?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082#-:-MWZPlcJ7MBOlxv0zCEh:b-v37mmq)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu and @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Yup, that'd be awesome!!!

**Comment by EricCousineau-TRI** [comment]
@avalenzu Fixed bug for `capture_errors` (correct) vs. `redirect_errors` (wrong) :facepalm: 
I dunno why you're getting `Widget Javascript not detected. It may not be installed or enabled properly` tho...

Here's what I see on my machine:

https://user-images.githubusercontent.com/26719449/113624954-4417bb00-962e-11eb-8377-9b3cfc7d8174.mp4

**Comment by jwnimmer-tri** [comment]
@avalenzu would you still like to review this?

**Review by avalenzu — COMMENTED** [review]
@ericcousineau-tri, I just tested this again and still get `Widget Javascript not detected.  It may not be installed or enabled properly.` both on my workstation and laptop. The code looks fine to me, but I can't stamp it without confirming that the widgets actually work. I think you'll need to find a third party to see which of us has the strangely configured machine. -@avalenzu 

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082#-:-MekrFGw0ibB9rtRPWif:bspw53o)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu and @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Gotcha, thanks for trying again!

**Review by avalenzu — COMMENTED** [review]
-@avalenzu I'm gonna officially bow out of this one.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14082#-:-MjWaMMb2IxCaQAbCc5g:b-8tbd4b)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @avalenzu and @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Aye, completely understand - thanks for the update! (and ofc, sorry for delay)

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI what do you think about closing this as a Drake PR, and instead submit an Anzu PR with the code you want, where you will have many more users and iterative feedback.  If it reaches a stable point there, we could upstream it to Drake?

**Comment by EricCousineau-TRI** [comment]
Yup, sounds good! Code actually already exists in Anzu, but in a slightly less polished form; can update it there.

**Pull request closed without merging**
