### PR TITLE
[mesh_to_model] Warn about implausible scale

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Wavefront .obj files do not specify or store units for the vertex vectors, and different tools use different units.

It is impractical and imprecise to try to infer units from comments that might be in the input file (though some software tries): https://stackoverflow.com/questions/47995531/three-js-load-proper-model-scale-size

Instead, this patch checks the volume of the output against implausibly large and small volumes, and issues warnings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review.
FYI @mitiguy 

Inspired by the "neutron star" incident encountered by one of @RussTedrake's students, linked from https://github.com/RobotLocomotion/drake/issues/20730 .

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nqs5e7Q8vXkfKRqOtzA:bewxs6m)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
I will note that I did not provide any tests, but it's pretty easy to explore the warning space with an arbitrary mesh file and deliberate abuse of the `--scale` parameter.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nqs6FcA4zuj6wxEXfad:bttt67k)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/multibody/_mesh_model_maker.py` line 201 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-Nqs7t1x4wn_joAraARE:-Nqs7t1x4wn_joAraARF:b-a8tmto) ([raw file](https://github.com/RobotLocomotion/drake/blob/579f7c78ed58b04633b40991678ed273a6777fef/bindings/pydrake/multibody/_mesh_model_maker.py#L201)):*
> ```Python
>                      f"{p_BoBcm[2]}]")
> 
>         cubed = "\u00b3"  # Unicode superscript 3.
> ```

nit Not sure why we need a variable for this?

I expect we could just put it into the string directly:

```py
f"Mesh volume ({volume} m³) exceeds ..."
```

**Review by mitiguy — COMMENTED** [review]
Looks good to me.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nr0zu4u0gWZe6-5vVgi:b9j9n43)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one editorial request.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nr1Jpf8-2xorVQPo9g0:buply71)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`bindings/pydrake/multibody/_mesh_model_maker.py` line 169 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-Nr1Dh-i4QyTQFaeJx-R:-Nr1Dh-i4QyTQFaeJx-S:bwf06k) ([raw file](https://github.com/RobotLocomotion/drake/blob/2bcfc3187bb0666156cb4977550309fcf3b39795/bindings/pydrake/multibody/_mesh_model_maker.py#L169)):*
> ```Python
>             # mass.
>             M_GGo_G = CalcSpatialInertia(mesh=mesh_G, density=1.0)
>             volume = M_GGo_G.get_mass()
> ```

nit This line offends my sensibility. The units of volume are not the units of mass.

You should note that because you computed `M_GGo_G` with unit density, you can divide that density back out of its mass to get the volume.

**Review by SeanCurtis-TRI — COMMENTED** [review]
As I'm on-call platform reviewer, you might consider making @mitiguy the official feature reviewer so you can close this out today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nr1JvcP8_qvcpMiUjKn:bpxqn1h)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@mitiguy for feature review; @SeanCurtis-TRI swapped to platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nr1KrvNANvE1AbStEMc:bfy7vzb)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966)* status: LGTM missing from assignee mitiguy

**Review by mitiguy — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20966#-:-Nr2Ev_o7Qlwoi-tdQKu:bg7igkv)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees mitiguy,SeanCurtis-TRI(platform)

**Pull request merged**
