### PR TITLE
Improve NonLinearProgram warnings

### PR DESCRIPTION
**Pull request by eric-wieser**
Changes the warnings that used to be of the form:

```
Warning: The decision variables in linear equality constraint 31 are all fixed (due to equality
bounding box constraints on the decision variables). Consider either removing this constraint,
or relaxing the bounds on the decision variables.
The decision variables in linear equality constraint 37 are all fixed (due to equality bounding
box constraints on the decision variables). Consider either removing this constraint, or
relaxing the bounds on the decision variables.
The decision variables in linear equality constraint 39 are all fixed (due to equality bounding
box constraints on the decision variables). Consider either removing this constraint, or
relaxing the bounds on the decision variables.
The decision variables in linear equality constraint 41 are all fixed (due to equality bounding
box constraints on the decision variables). Consider either removing this constraint, or
relaxing the bounds on the decision variables.
```

To be of the form

```
Warning: The decision variables in linear equality constraint(s)
end_direction1 (#31), intermediate_direction1 (#37),
intermediate_direction1 (#39), intermediate_direction1 (#41) are all
fixed (due to equality bounding box constraints on the decision
variables). Consider either removing this constraint, or relaxing the
bounds on the decision variables.
```

Note that the names used are not as useful as they could be for `addConstraint(c, 1:N)`, but that's scope for further improvement.

`LinearConstraint.setName` was removed to let it fall through to `Constraint.setName`, which deals with a single name for matrix constraints.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Maybe shouldn't have whitespace-squelched that...

**Comment by eric-wieser** [comment]
Or would this be better as:
```
Warning: The decision variables in the following linear equality constraint(s) are all
fixed (due to equality bounding box constraints on the decision
variables):
  end_direction1 (#31)
  intermediate_direction1 (#37),
  intermediate_direction1 (#39),
  intermediate_direction1 (#41)
Consider either removing this constraint, or relaxing the
bounds on the decision variables.
```

**Comment by avalenzu** [comment]
I like the one constraint per line format in your most recent comment. Very readable.

**Comment by eric-wieser** [comment]
Hmmm. That failed because:

> The STRJOIN function was introduced in release R2013a and is not available in earlier releases.

Is R2012a the lowest version drake intends to support?

**Comment by RussTedrake** [comment]
yes.  until it becomes a burden, we're trying to support R2012a.

**Comment by eric-wieser** [comment]
Is adding `strjoin.m` somewhere in the tree an appropriate fix here? Is there a convention for polyfilling functions in old matlab versions without hiding the builtin function in newer versions?

**Comment by RussTedrake** [comment]
no.  that gets ugly.  better, i think, to leave the strjoin in as a comment, and simply use something like
```
str = sprintf('%s, ',parts{:}); str=str(1:end-2);
```

**Comment by eric-wieser** [comment]
Using the format in [this comment](https://github.com/RobotLocomotion/drake/pull/1486#issuecomment-162375440) makes `sprintf` a better solution anyway

**Comment by RussTedrake** [comment]
otherwise looks good to me.  will wait for the build servers.

**Comment by eric-wieser** [comment]
Do the buildservers run again on something you've already tagged?

**Comment by eric-wieser** [comment]
I'm now thinking that this error message needs rephrasing. Adding a constraint like this:

	prog = prog.addStateConstraint(...
		setName(LinearConstraint(A*x0, A*x0, A), 'canary'), 2:N-1);

Gives the message

> The decision variables in the following linear equality constraint(s) are all fixed

Isn't a better description that they are all unconstrained?

**Pull request merged**
