### PR TITLE
RNDF SplineLane::GetPositionToLane fix

### PR DESCRIPTION
**Pull request by agalbachicar**
A bug was introduced as part of #6349. `SplineLane::GetPositionToLane` is a private method and it's used by `SplineLane::do_driveable_bounds()`. 

When the Lane belongs to a Segment with multiple Lanes, we should compute the projected GeoPosition of the Lane over the Lanes at the lateral extents of the segment. This projection is done using the curvature radius. `SplineLane::GetPositionToLane` is in charge of that computation.

Further test coverage for this bug will be covered in a future PR which includes the Builder.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6690)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@liangfok for feature review please.

**Comment by liangfok** [comment]
+@liangfok for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-:-Kq845dlBCjjkk-YXG8t:b-m6pkmk)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-:-Kq8AF683Q1XvwUFcFyt:bnfp4nl)*

**Comment by sherm1** [comment]
+@sherm1 for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-:-Kq8bBJVqwJqaC7daRs9:buasbda)*

**Comment by sherm1** [comment]
The existence of this bug suggests that there is a missing unit test. Can you add one to this PR to verify that it is working now and to make sure no one messes this up in the future?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/rndf/spline_lane.cc, line 162 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-Kq8qMMToN1cz5TqKYOH:-Kq8qMMToN1cz5TqKYOI:b-ue7kwu) ([raw file](https://github.com/robotlocomotion/drake/blob/6f2cd5768e243ace756a90f556c1f38628af8836/drake/automotive/maliput/rndf/spline_lane.cc#L162)):*
> ```cpp
>   // Gets the beginning and ending of the other lane, and then computes the
>   // respective GeoPositions.
>   const SplineLane* other_lane = static_cast<const SplineLane*>(
> ```

This should be a `dynamic_cast` to verify that the Lane is actually a SplineLane.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-:-Kq8rkwXeugaGhwC1fRd:b-3uzlzv)*

**Comment by agalbachicar** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/rndf/spline_lane.cc, line 162 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-Kq8qMMToN1cz5TqKYOH:-Kq9K2IrvWz0WeGuBYHQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f2cd5768e243ace756a90f556c1f38628af8836/drake/automotive/maliput/rndf/spline_lane.cc#L162)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should be a `dynamic_cast` to verify that the Lane is actually a SplineLane.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/rndf/test/spline_lane_test.cc, line 320 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-Kq9K5EEtgFEF1ZxZF0w:-Kq9K5EEtgFEF1ZxZF0x:bz9e3ai) ([raw file](https://github.com/robotlocomotion/drake/blob/e2cc9510ce53043e1ac99e4e9972d449939762bf/drake/automotive/maliput/rndf/test/spline_lane_test.cc#L320)):*
> ```cpp
> }
> 
> // Performs geometric tests over the bounds of a pair of straight lanes.
> ```

The proposed test uses driveable_bounds() since that public call, when two or more lanes belong to the same segment, goes through the affected piece of code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6690)*

**Comment by agalbachicar** [comment]
I have addressed all the comments and added a test. PTAL.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6690#-:-Kq9W2PNU8mtOuOWiEEA:bku5qji)*

**Pull request merged**
