### PR TITLE
Switch nlopt download from github to drake mirrors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The https://github.com/stevengj user is all 404s right now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5955)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5955#-:-KikFoWYlYqRqJtdaB2C:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@soonho-tri 
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5955#-:-KikG0z32mLrvrJ4e6ML:b-9lipgw)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5955)*

**Comment by jwnimmer-tri** [comment]
At least one Bazel build passed.  Using override-merge due to emergency.

**Pull request merged**
