### PR TITLE
Allow multiple LcmInterfaceSystems on the same URL

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@ericcousineau-tri Does this address your team's needs?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-MhoUA5c6Yq913aR8FhM:b-tiospg)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
I think something like this should work!

FWIW This isn't necessarily for my team, more for Anzu in general (and also as a note about affecting downstream users).

**Review by ggould-tri — COMMENTED** [review]
Okay, adding +@seancurtis-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-Mhodu8p8wT0ODHKw6zt:b-oi1pz6)* status: LGTM missing from assignees EricCousineau-TRI(platform),SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-MhoeE4dA_Amo-f8aS8m:b-v6scke)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[systems/lcm/lcm_interface_system.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15653#-Mhoe-DN2VA6Cj6MiLyu:-Mhoe-DN2VA6Cj6MiLyv:b-jh5hg9) ([raw file](https://github.com/robotlocomotion/drake/blob/c96a29d778dfd49d0234f5c900a0d2b83ba0ca78/systems/lcm/lcm_interface_system.cc#L32)):*
> ```cpp
> LcmInterfaceSystem::LcmInterfaceSystem(DrakeLcmInterface* lcm)
>     : lcm_(lcm),
>       id_number_(next_unique_id++) {
> ```

nit Is this thread-safe?
___
*[systems/lcm/lcm_interface_system.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15653#-MhodpAt9vEjm9Q11r6M:-MhodpAt9vEjm9Q11r6N:b-yv3pim) ([raw file](https://github.com/robotlocomotion/drake/blob/c96a29d778dfd49d0234f5c900a0d2b83ba0ca78/systems/lcm/lcm_interface_system.cc#L37)):*
> ```cpp
>       // Include ID number as diagrams sometimes have multiple interfaces to
>       // the same URL and we don't want them to have name collisions.
>       "LcmInterfaceSystem(lcm_url={},id={})",
> ```

It's unclear to me the intent of `id`; should users really care about it?

If not, and this is purely sugar for diagrams, can we use simpler-to-generate UID?
(perhaps pointer, like standard name for systems?)

Then, if a user wants a prettier name, they can set it themselves?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[systems/lcm/lcm_interface_system.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15653#-MhodpAt9vEjm9Q11r6M:-Mhoeb3F0-Q6vk_2L4S6:b-m9n1z7) ([raw file](https://github.com/robotlocomotion/drake/blob/c96a29d778dfd49d0234f5c900a0d2b83ba0ca78/systems/lcm/lcm_interface_system.cc#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's unclear to me the intent of `id`; should users really care about it?

If not, and this is purely sugar for diagrams, can we use simpler-to-generate UID?
(perhaps pointer, like standard name for systems?)

Then, if a user wants a prettier name, they can set it themselves?
</blockquote></details>

(or perhaps keep the incrementing integer, but perhaps just same something like `unique_id={}`?)

**Comment by ggould-tri** [comment]
___
*[systems/lcm/lcm_interface_system.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15653#-MhodpAt9vEjm9Q11r6M:-Mhoj-9t4vArRtEiBZtM:b-v2r8tm) ([raw file](https://github.com/robotlocomotion/drake/blob/c96a29d778dfd49d0234f5c900a0d2b83ba0ca78/systems/lcm/lcm_interface_system.cc#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(or perhaps keep the incrementing integer, but perhaps just same something like `unique_id={}`?)
</blockquote></details>

Are you thinking of something like `System::GetMemoryObjectName`?  I guess since we're already doing that sort of witchcraft I can hardly find it objectionable at this stage.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with one more nit on formatting - thanks!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-MhomcCw1JUNz28q-WbN:bq6n9i6)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[systems/lcm/lcm_interface_system.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15653#-MhodpAt9vEjm9Q11r6M:-MhomG6hC9Wujvud-g0I:br1x1by) ([raw file](https://github.com/robotlocomotion/drake/blob/c96a29d778dfd49d0234f5c900a0d2b83ba0ca78/systems/lcm/lcm_interface_system.cc#L37)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Are you thinking of something like `System::GetMemoryObjectName`?  I guess since we're already doing that sort of witchcraft I can hardly find it objectionable at this stage.
</blockquote></details>

OK Yup - looks great!
___
*[systems/lcm/lcm_interface_system.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15653#-MhomKDrEHllzlprDTLb:-MhomKDrEHllzlprDTLc:b3v2b5) ([raw file](https://github.com/robotlocomotion/drake/blob/9cb25256fc9d8a22b02502814850ba1de438bb9d/systems/lcm/lcm_interface_system.cc#L32)):*
> ```cpp
>       // Include Unique ID as diagrams sometimes have multiple interfaces to
>       // the same URL and we don't want them to have name collisions.
>       "LcmInterfaceSystem(lcm_url={},uid={})",
> ```

nit `GetMemoryObjectName` looks like `{type}@{hex}`.

Consider using that format here, vs. introducing `uid` parameter? (sorry for suggesting that!)
`LcmInterfaceSystem(lcm_url={})@{hex}`

**Comment by jwnimmer-tri** [comment]
I almost defected this in the original review; seems like I should have.  In general, subclasses of LeafSystem should not set their own name; they should leave it to the code that instantiates them to set it.  To do otherwise risks the "systems within a Diagram must have unique names" invariant.  The three systems in the `lcm` folder seem to be the only exceptions to this rule.  Simply _removing_ the `set_name_` here seems like the best answer.

**Review by ggould-tri — COMMENTED** [review]
Um.  I will think on that and get back to this tomorrow morning.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-Mhop4sYBub_eehUFTyD:b-oq2f82)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
That'd work for me as well!

**Review by ggould-tri — COMMENTED** [review]
Nameless version is up and seems to work.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-MhsGXun2LObly0Rzm5k:b-ke1nm2)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks awesome! Given simplification, I'm happy to serve as single reviewer if that helps at all.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-MhsjxI8AgfT_3FEI6-L:b-mnh05l)* status: needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15653#-:-MhsrS_fEivDLlXKFEei:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @ggould-tri)

**Pull request merged**
