### PR TITLE
Rewrite pkg_config_repository from scratch

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This adds two new features:
- injecting `deps` directly, without having to fork the template;
- allowing wrapping without having to repeat the template label.

This also removes our dependency on `@kythe`, so we can remove that from our workspace as well.

This implementation should also be substantially easier to change over time as we grow new requirements, such as better aligning the install rules with the `pkg-config` results, managing shared vs static linking, etc.

Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7726)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
The macOS builds all passed.  I'll wait to rebase until the first review pass.

**Comment by soonho-tri** [comment]
Checkpoint.

---

Reviewed 20 of 21 files at r1.
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/lint/buildifier-tables.json, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-L2_mnybiMqwVJscBR4J:-L2_mnybiMqwVJscBR4K:bdxqmps) ([raw file](https://github.com/robotlocomotion/drake/blob/8cf709d904196c3a946ac2a6a880b2a8da2c9c79/tools/lint/buildifier-tables.json#L40)):*
> ```JSON
>     "new_local_repository.build_file_content":  360,
> 
>     "pkg_config_repository.atleast_version": 200,
> ```

Do we need to have an entry for `pkg_config_repository.build_file_template` here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-:-L2_nRHemR8hmkPRyin2:by96gdd)*

**Comment by soonho-tri** [comment]
:lgtm:
+@ericcousineau-tri for platform-review, please.

---

Reviewed 1 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/lint/buildifier-tables.json, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-L2_w-Fwv7Wa37_wY8Cp:-L2_w-Fx5ROxAL0ZV0Va:b-uee4fa) ([raw file](https://github.com/robotlocomotion/drake/blob/8cf709d904196c3a946ac2a6a880b2a8da2c9c79/tools/lint/buildifier-tables.json#L1)):*
> ```JSON
> {
> ```

Not related to this particular PR, but could you add a short paragraph explaining how this file is used (i.e. how the (key, value) is interpreted in `buildifier`)? I've tried to find a documentation but failed to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-:-L2_wOuBVndHrdcqtzch:b-uhbwpq)*

**Comment by jwnimmer-tri** [comment]
Review status: 19 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lint/buildifier-tables.json, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-L2_w-Fwv7Wa37_wY8Cp:-L2_zw0sK6-ARyTmPsI6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8cf709d904196c3a946ac2a6a880b2a8da2c9c79/tools/lint/buildifier-tables.json#L1)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Not related to this particular PR, but could you add a short paragraph explaining how this file is used (i.e. how the (key, value) is interpreted in `buildifier`)? I've tried to find a documentation but failed to do so.
</blockquote></details>

Done.

---

*[tools/lint/buildifier-tables.json, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-L2_mnybiMqwVJscBR4J:-L2_xsbnv10GaSXFfPwu:bw4tr57) ([raw file](https://github.com/robotlocomotion/drake/blob/8cf709d904196c3a946ac2a6a880b2a8da2c9c79/tools/lint/buildifier-tables.json#L40)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Do we need to have an entry for `pkg_config_repository.build_file_template` here? 
</blockquote></details>

OK If an attribute name is unlisted here it gets a default priority (it's not an error), and that seemed fine to me since basically nobody will specify that attribute in my estimation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor BTW. Thanks!

---

Reviewed 14 of 21 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.bzl, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-L2a7ixD1EwlbJQvkirP:-L2a7ixEjmtxqaKDZBeJ:b-ftdr2p) ([raw file](https://github.com/robotlocomotion/drake/blob/a14d593079ee52bc1b8f7359c5fbd6eac85783ab/tools/workspace/pkg_config.bzl#L16)):*
> ```Python
> def setup_pkg_config_repository(repository_ctx):
>     """This is the macro form of the pkg_config_repository() rule below.
>     Refer to that rule's API documentation for details.
> ```

BTW Could a comment be added here mentioning that other rules directly consume this macro impl due to platform checks?
(Implicit because it's public, but if those checks go away, then those rules could then just consume the rule, not the impl?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-:-L2a8wvglT3Gv05Wbl8L:bwvjhnk)*

**Comment by jwnimmer-tri** [comment]
Review status: 19 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.bzl, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7726#-L2a7ixD1EwlbJQvkirP:-L2aA3AeUWu4h5NTcV3f:b-bpeu8a) ([raw file](https://github.com/robotlocomotion/drake/blob/a14d593079ee52bc1b8f7359c5fbd6eac85783ab/tools/workspace/pkg_config.bzl#L16)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could a comment be added here mentioning that other rules directly consume this macro impl due to platform checks?
(Implicit because it's public, but if those checks go away, then those rules could then just consume the rule, not the impl?)
</blockquote></details>

Done.  Rather than trying to explain the wider world, I've added documentation explaining why a caller should prefer one or the other.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7726)*

**Comment by jwnimmer-tri** [comment]
All passed.  Merging.

**Pull request merged**
