### PR TITLE
[pydrake] Bind SystemVisitor and Diagram introspection methods

### PR DESCRIPTION
**Pull request by RussTedrake**
This should enable us to explore solutions to #1387 completely in python.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri  for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-Mt8Nui-AbFqLuGxd-T9:bd8nruu)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: question about issue number, and some cleanups requested.
+@xuchenhan-tri for shadow platform review.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-Mt9oewJ8REIXN-h7oS-:b5kplor)* status: 6 unresolved discussions, LGTM missing from assignee xuchenhan-tri (waiting on @RussTedrake and @xuchenhan-tri)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9lRcz1H_-NwOs8KD7):*
Is 1387 really the right issue number? Looks unrelated to me.
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9qk7i0mdMJJmnK8dz:-Mt9qk7i0mdMJJmnK8e-:b-5ux86s) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L289)):*
> ```cpp
>     // Trampoline virtual methods.
>     void VisitSystem(const System<T>& system) override {
>       PYBIND11_OVERLOAD_INT(void, SystemVisitor<T>, "VisitSystem", system);
> ```

Looks to me like the `PYBIND11_OVERLOAD_INT` is internal/unsupported, and that the public-API macro has been renamed `PYBIND11_OVERRIDE()`.

See the Warning box (scroll down some) in this page: https://pybind11.readthedocs.io/en/stable/advanced/classes.html
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 928 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9nqSa1aCkTmiw_HQQ:-Mt9nqSa1aCkTmiw_HQR:br5lbwo) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L928)):*
> ```cpp
>         .def("connection_map", &Diagram<T>::connection_map,
>             py_rvp::reference_internal, doc.Diagram.connection_map.doc)
>         .def("GetInputPortLocators", &Diagram<T>::GetInputPortLocators,
> ```

nit I think it's typical (required? I'm not sure) to name the parameters in python bindings. Here and also for `get_output_port_locator`.
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 956 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9lsWRCbdVsY4InN2m:-Mt9lsWRCbdVsY4InN2n:bf5ez8e) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L956)):*
> ```cpp
>             },
>             doc.Diagram.GetSystems.doc);
>     //        .def("get_output_port_locator", py::arg("port_index"));
> ```

Should this line get deleted? looks like cruft from development.
___
*[bindings/pydrake/systems/test/general_test.py, line 937 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9mWHH2N2u4HZokXei:-Mt9mWHH2N2u4HZokXej:bh9pre5) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L937)):*
> ```Python
>         in0_index = builder.ExportInput(adder1.get_input_port(0), "in0")
>         in1_index = builder.ExportInput(adder1.get_input_port(1), "in1")
>         out_index = builder.ExportOutput(adder2.get_output_port(), "out")
> ```

nit Looks to me like we export `adder2.get_output_port()` twice, once named "out" and once default-named. Is that intentional?
___
*[bindings/pydrake/systems/test/general_test.py, line 982 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9o83e0Cc6mOOl1dBg:-Mt9o83e0Cc6mOOl1dBh:bmazqmj) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L982)):*
> ```Python
> 
>         visitor = MyVisitor()
>         system.Accept(visitor)
> ```

For named parameters, we usually (required? I think so...) try to exercise the parameter name in the tests for the binding. So, `system.Accept(v=visitor)` somewhere, in addition to the existing line.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with some questions.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-MtAIuAo4Ytg8TzW_JxX:bnuj83m)* status: 8 unresolved discussions (waiting on @rpoyner-tri and @RussTedrake)

___
*[bindings/pydrake/systems/framework_py_systems.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9qk7i0mdMJJmnK8dz:-MtA7MBE4EkIb-jy3kOv:b98yei4) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L289)):*
> The macro PYBIND11_OVERRIDE_PURE should be used for pure virtual functions, and PYBIND11_OVERRIDE should be used for functions which have a default implementation. 

So perhaps the preferred spelling is `PYBIND_OVERRIDE_PURE`?
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 929 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtA8V2793FlgY676zZW:-MtA8V2793FlgY676zZX:bdjt2eb) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L929)):*
> ```cpp
>             py_rvp::reference_internal, doc.Diagram.connection_map.doc)
>         .def("GetInputPortLocators", &Diagram<T>::GetInputPortLocators,
>             py_rvp::reference_internal, doc.Diagram.GetInputPortLocators.doc)
> ```

Is `py_rvp::reference_internal` needed here? The c++ method being bound is not returning a reference.
___
*[bindings/pydrake/systems/test/general_test.py, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtA9kzZ9Ae6oY9vpGtN:-MtA9kzZ9Ae6oY9vpGtO:b-yme9q5) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L55)):*
> ```Python
>     Supervector, Supervector_,
>     System, System_,
>     SystemVisitor, SystemVisitor_,
> ```

This confuses me. Why is `SystemVisitor_` needed and where is it defined?
___
*[bindings/pydrake/systems/test/general_test.py, line 941 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtAI8e9EJJpglf8WEUU:-MtAI8e9EJJpglf8WEUV:b4c76az) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L941)):*
> ```Python
> 
>         connections = diagram.connection_map()
>         self.assertIn((adder2, in0_index), connections)
> ```

This test baffles me. 

I thought the connection map would look like (adder1, adder1.get_output_port().index()) -> (adder2, adder2.get_input_port().index()). Perhaps I'm not understanding what `connection_map()` is supposed to return? The documentation of the method simply says "Returns a reference to the map of connections between Systems.".

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)* status: 7 unresolved discussions (waiting on @rpoyner-tri and @RussTedrake)

___
*[bindings/pydrake/systems/test/general_test.py, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtA9kzZ9Ae6oY9vpGtN:-MtANuPp7Q4KAiMtRreA:b-3iaok0) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L55)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This confuses me. Why is `SystemVisitor_` needed and where is it defined?
</blockquote></details>

The `_` symbols are for classes scalar-type-templated in C++. In python, there is a form `MyClass_[float]` for `MyClass<double>`, with similar spellings for AutoDiffXd and Expression. Some doc for this idiom is [here](https://drake.mit.edu/python_bindings.html#differences-with-c-api).
___
*[bindings/pydrake/systems/test/general_test.py, line 941 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtAI8e9EJJpglf8WEUU:-MtAPhdbDFxOmMXB3VPv:b-6i34l2) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L941)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This test baffles me. 

I thought the connection map would look like (adder1, adder1.get_output_port().index()) -> (adder2, adder2.get_input_port().index()). Perhaps I'm not understanding what `connection_map()` is supposed to return? The documentation of the method simply says "Returns a reference to the map of connections between Systems.".
</blockquote></details>

Perhaps what is baffling is the meaning of `in` in Python. I think what is happening is that the `assertIn()` method is effectively only looking through the *keys* of a Python dictionary-like object (constructed/wrapped from c++? -- i don't know the binding details), so the call only is establishing that the `InputPortLocator` key is present. The other baffling thing about connection_map itself is that it points *upstream* -- it has InputLocator keys and OutputLocator values.

No doubt the connection_map() documentation could be better; its type signature does give a bit of insight.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)* status: 7 unresolved discussions (waiting on @RussTedrake and @xuchenhan-tri)

___
*[bindings/pydrake/systems/framework_py_systems.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9qk7i0mdMJJmnK8dz:-MtASUCc0Rn1qYTKBFoZ:bfkrywu) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L289)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> The macro PYBIND11_OVERRIDE_PURE should be used for pure virtual functions, and PYBIND11_OVERRIDE should be used for functions which have a default implementation. 

So perhaps the preferred spelling is `PYBIND_OVERRIDE_PURE`?
</blockquote></details>

to be fair, there are other uses of PYBIND11_OVERLOAD_INT around, but they are all within this file. Other current uses seem to have the spelling PYBIND11_OVERLOAD_PURE; I guess I'll have to look carefully at our RobotLocomotion vendored copy of pybind to see if the (apparently more modern) spelling is even supported.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)* status: 7 unresolved discussions (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/test/general_test.py, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtA9kzZ9Ae6oY9vpGtN:-MtAugol87CRPKT0Zlyo:b-jhyyta) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L55)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The `_` symbols are for classes scalar-type-templated in C++. In python, there is a form `MyClass_[float]` for `MyClass<double>`, with similar spellings for AutoDiffXd and Expression. Some doc for this idiom is [here](https://drake.mit.edu/python_bindings.html#differences-with-c-api).
</blockquote></details>

Got it. Thanks!
___
*[bindings/pydrake/systems/test/general_test.py, line 941 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtAI8e9EJJpglf8WEUU:-MtAv-y11d_j-TpupmO_:b-duyf3x) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L941)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Perhaps what is baffling is the meaning of `in` in Python. I think what is happening is that the `assertIn()` method is effectively only looking through the *keys* of a Python dictionary-like object (constructed/wrapped from c++? -- i don't know the binding details), so the call only is establishing that the `InputPortLocator` key is present. The other baffling thing about connection_map itself is that it points *upstream* -- it has InputLocator keys and OutputLocator values.

No doubt the connection_map() documentation could be better; its type signature does give a bit of insight.
</blockquote></details>

These two points were not my source of confusion.

I don't understand why (adder2, in0_index) is supposed to be the key -- Doesn't input port "in0" belong to adder1? I reversed the key/value in my previous comment but I was expecting the map to be 

(adder2, adder2.get_input_port().index()) -> (adder1, adder1.get_output_port().index())

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)* status: 7 unresolved discussions (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/test/general_test.py, line 941 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtAI8e9EJJpglf8WEUU:-MtBJrFECKos_QyQobzr:bt4j4mw) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L941)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

These two points were not my source of confusion.

I don't understand why (adder2, in0_index) is supposed to be the key -- Doesn't input port "in0" belong to adder1? I reversed the key/value in my previous comment but I was expecting the map to be 

(adder2, adder2.get_input_port().index()) -> (adder1, adder1.get_output_port().index())
</blockquote></details>

Oh yes you are right. I think this "works" because the vast majority of all port indices are 0. :/ I don't recall for certain, but I suspect any marginal safety given by TypeSafeIndex alias types for c++ is lost in python.

**Review by RussTedrake — COMMENTED** [review]
Sorry that I had tried to knock this one out too quickly (was trying to unblock a potential contributor).  PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-MtDUlKP3DnfBzq1GnRG:bjr3o45)* status: 5 unresolved discussions (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9lRcz1H_-NwOs8KD7):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Is 1387 really the right issue number? Looks unrelated to me.
</blockquote></details>

Oops.  I lost the trailing digit.  Fixed.
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9qk7i0mdMJJmnK8dz:-MtDEqwP6rCblB2MsRVB:b-4rijlj) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L289)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

to be fair, there are other uses of PYBIND11_OVERLOAD_INT around, but they are all within this file. Other current uses seem to have the spelling PYBIND11_OVERLOAD_PURE; I guess I'll have to look carefully at our RobotLocomotion vendored copy of pybind to see if the (apparently more modern) spelling is even supported.
</blockquote></details>

Done.  `PYBIND11_OVERLOAD_PURE` works.
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 928 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9nqSa1aCkTmiw_HQQ:-MtDGQPDBbLkkqw5hgei:b-rdmy35) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L928)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit I think it's typical (required? I'm not sure) to name the parameters in python bindings. Here and also for `get_output_port_locator`.
</blockquote></details>

Done.  That was an oversight.  
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 929 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtA8V2793FlgY676zZW:-MtDOGBOEZGi9Sy6DDAz:b6923z7) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L929)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is `py_rvp::reference_internal` needed here? The c++ method being bound is not returning a reference.
</blockquote></details>

I'm glad you asked.  I was putting the keep_alive on the list, and not the actual reference.  unfortunately, things got significantly more messy... 
___
*[bindings/pydrake/systems/framework_py_systems.cc, line 956 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9lsWRCbdVsY4InN2m:-MtDOipl0Y9P-MwCMqoW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/framework_py_systems.cc#L956)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Should this line get deleted? looks like cruft from development.
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/test/general_test.py, line 937 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9mWHH2N2u4HZokXei:-MtDTfhSAwe-2QRl1mkx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L937)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Looks to me like we export `adder2.get_output_port()` twice, once named "out" and once default-named. Is that intentional?
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/test/general_test.py, line 941 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtAI8e9EJJpglf8WEUU:-MtDUGU3DLDqJpxFetBG:bmkw2hp) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L941)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Oh yes you are right. I think this "works" because the vast majority of all port indices are 0. :/ I don't recall for certain, but I suspect any marginal safety given by TypeSafeIndex alias types for c++ is lost in python.
</blockquote></details>

Done.  You are right, that was a late find-and-replace mistake.  But it's resolved in the latest revision.  (I don't think TypeSafeIndex would have helped on this one?).
___
*[bindings/pydrake/systems/test/general_test.py, line 982 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-Mt9o83e0Cc6mOOl1dBg:-MtDUhVQ-ww6HqVrq1xR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L982)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

For named parameters, we usually (required? I think so...) try to exercise the parameter name in the tests for the binding. So, `system.Accept(v=visitor)` somewhere, in addition to the existing line.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: Thanks for the clean up and explanation.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-MtEcNOh9NZ1m8UwY-3k:bi5c1ni)* status: 4 unresolved discussions (waiting on @rpoyner-tri)

**Review by RussTedrake — COMMENTED** [review]
@rpoyner-tri -- waiting on your OK.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-MtI8fm84RfWaiXMTwqw:b-w6pd6r)* status: 4 unresolved discussions (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352#-:-MtJ6lXW0AQf0OaWQmE0:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/test/general_test.py, line 941 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16352#-MtAI8e9EJJpglf8WEUU:-MtJ6VOCERzhSsOgxTgL:bc3256l) ([raw file](https://github.com/robotlocomotion/drake/blob/e84b2b3eaf173dbbb139b8710012e30c603d560f/bindings/pydrake/systems/test/general_test.py#L941)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  You are right, that was a late find-and-replace mistake.  But it's resolved in the latest revision.  (I don't think TypeSafeIndex would have helped on this one?).
</blockquote></details>

No, TypeSafeIndex won't help in Python, but a similar slip in C++ should be caught, since InputPortIndex and OutputPortIndex are distinct.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16352)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @RussTedrake)

**Comment by EricCousineau-TRI** [comment]
> This should enable us to explore solutions to https://github.com/RobotLocomotion/drake/issues/1387 completely in python.

Hm... I think this might've been a different issue. Any chance you remember what the original issue?
Just trying to trace this back to see if there was a referenced solution w.r.t. https://stackoverflow.com/a/74802395/7829525 ([Drake Slack](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1671038784044819))

**Pull request merged**
