### PR TITLE
Add REQUIRES libbot where appropriate for MATLAB tests

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #1997. Extends #3094.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3264)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
Magic to look for in the Windows MATLAB builds is
```
Not running <test> because libbot was not installed.
```
Should not be present in Linux MATLAB builds

**Comment by jamiesnape** [comment]
@jwnimmer-tri or the next on-call platform reviewer for feature and platform review. As with #3094, it is all `grep` and `sed` of build output.

**Comment by jwnimmer-tri** [comment]
Sure, I will look at this.

**Comment by jwnimmer-tri** [comment]
FTR, this is adding more that just `REQUIRES libbot` in places; there are `REQUIRES lcm gurobi` additions as well (which seem fine).

:lgtm: 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3264#-:-KQ3HTgvkx249mkXm1H9:bem2z65)*

**Pull request merged**
