### PR TITLE
Rigid contact solver

### PR DESCRIPTION
**Pull request by edrumwri**
Adds an LCP-based mechanism for computing contact forces under the rigid contact model with Coulomb friction and stiction.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6508)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@siyuanfeng-tri for feature review please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KoJ4zZgbZnsCtLhxQKX:bgdoi2o)*

**Comment by edrumwri** [comment]
+@soonho-tri for platform review (per regular rotation) please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KoNXUXppm3Ou_lbjPzs:b-nyole2)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
+(status: curate commits before merging) 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KoNeQpmrsB5Dca2CjRF:bf34tsp)*

**Comment by soonho-tri** [comment]
Checkpoint. I'll hold it until @siyuanfeng-tri completes his first round.

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/rod2d/rod2d.h, line 494 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO3zAWndXFNFC1fanp:-KoO3zAWndXFNFC1fanq:ba0wp5) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/examples/rod2d/rod2d.h#L494)):*
> ```objc
>   /// @param[out] data the rigid contact problem data.
>   void CalcRigidContactProblemData(const systems::Context<T>& context,
>                                    const std::vector<Vector2<T>>& p,
> ```

BTW, `p` -> `points`? (or please change the documentation and the definition in `rod2d-inl.h`)

---

*[drake/examples/rod2d/rod2d.h, line 512 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO3giqf5vUr7At1Swa:-KoO3giqf5vUr7At1Swb:b-9xw3pi) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/examples/rod2d/rod2d.h#L512)):*
> ```objc
>   MatrixX<T> solve_inertia(const MatrixX<T>& B) const;
> 
>  private:
> ```

FYI, this is redundant.

---

*[drake/multibody/rigid_contact/BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO4EFVK8y77c6NazzA:-KoO4EFVK8y77c6NazzB:b-tdedoh) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/multibody/rigid_contact/BUILD#L15)):*
> ```Python
> 
> drake_cc_library(
>     name = "rigid_contact",
> ```

BTW, I think it's better to name this target to be `rigid_contact_solver`.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO4Rp93dMATbOXHBhT:-KoO4Rp93dMATbOXHBhU:b-o8qoxt) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/multibody/rigid_contact/rigid_contact_solver.h#L19)):*
> ```objc
> /// problem data corresponding to one or more rigid or multi-rigid bodies
> /// constrained unilaterally and acted upon by Coulomb friction, this class
> /// computes the contact forces.
> ```

FYI, consider adding the following comment:
```
/// Instantiated templates for the following kinds of T's are provided:
/// - double
```

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO4swi0--Rx9LhGmnL:-KoO4swi0--Rx9LhGmnM:b-i9w5w1) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/multibody/rigid_contact/rigid_contact_solver.h#L22)):*
> ```objc
> template <typename T>
> class RigidContactSolver {
>  public:
> ```

FYI, it's recommended to have : 
```c++
RigidContractSolver() = default;
DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(RigidContractSolver) // (or `NO_COPY`/`NO_MOVE`?)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KoOpptMyOb6cZLsazVZ:bey5wug)*

**Comment by edrumwri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/rod2d/rod2d.h, line 494 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO3zAWndXFNFC1fanp:-KoPdtkfdC2d3mkrVhwd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/examples/rod2d/rod2d.h#L494)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `p` -> `points`? (or please change the documentation and the definition in `rod2d-inl.h`)
</blockquote></details>

Done.

---

*[drake/examples/rod2d/rod2d.h, line 512 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO3giqf5vUr7At1Swa:-KoPdydFogwQIxfF6A-D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/examples/rod2d/rod2d.h#L512)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this is redundant.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO4EFVK8y77c6NazzA:-KoPeT-WsXDZi2RgpPh0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/multibody/rigid_contact/BUILD#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's better to name this target to be `rigid_contact_solver`.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO4Rp93dMATbOXHBhT:-KoPezemr72xowZmGHoj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/multibody/rigid_contact/rigid_contact_solver.h#L19)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, consider adding the following comment:
```
/// Instantiated templates for the following kinds of T's are provided:
/// - double
```
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoO4swi0--Rx9LhGmnL:-KoPfdutMSjAVJtMs-FL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/711ba8e942fc2838f68ffdca1c5e90dbe9da5add/drake/multibody/rigid_contact/rigid_contact_solver.h#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, it's recommended to have : 
```c++
RigidContractSolver() = default;
DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(RigidContractSolver) // (or `NO_COPY`/`NO_MOVE`?)
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/multibody/rigid_contact/BUILD, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSH0CU7ZPSfgS2W28u:-KoSH0CU7ZPSfgS2W28v:b-llksk1) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/BUILD#L32)):*
> ```Python
>     deps = [
>         "//drake/solvers:mathematical_program",
>         "rigid_contact",
> ```

BTW i suspect this needs a ":" and goes above, like what you did in rigid_contact_solver_test

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSK3JOQjxULvVHPZcZ:-KoSK3JOQjxULvVHPZc_:b-jrade7) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L51)):*
> ```objc
>   void SolveContactProblem(double cfm,
>       const RigidContactAccelProblemData<T>& problem_data,
>       VectorX<T>* cf) const;
> ```

I would suggest splitting cf into two parts, and maybe have the shear force event be a std::vector<VectorX<T>>*

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSKMnjp7UY2CvfnCFn:-KoSKMnjp7UY2CvfnCFo:bfoywaa) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L56)):*
> ```objc
>   void FormSustainedContactLCP(
>       const RigidContactAccelProblemData<T>& problem_data,
>       MatrixX<T>* MM, Eigen::Matrix<T, Eigen::Dynamic, 1>* qq) const;
> ```

BTW this is just VectorX<T> right?

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSLRq_N9_T3nGRBoJ_:-KoSLRq_N9_T3nGRBoJa:b-blo12h) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L110)):*
> ```objc
>   // NOTE: This LCP might not be solvable due to inconsistent configurations.
>   // Check the answer and throw a runtime error if it's no good.
>   if (!success || (zz.size() > 0 && (zz.minCoeff() < -10 * zero_tol ||
> ```

BTW might be easier for the reader if you write a one liner saying these are the constraints that z and w has to satisfy. also 10 / 100 seems like magical numbers to me.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSLz7TubbGuMswjAQU:-KoSLz7U2ty4W8gaVFZU:b-459plb) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L127)):*
> ```objc
> void RigidContactSolver<T>::FormSustainedContactLCP(
>     const RigidContactAccelProblemData<T>& problem_data,
>     MatrixX<T>* MM, Eigen::Matrix<T, Eigen::Dynamic, 1>* qq) const {
> ```

BTW VectorX<T>

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSowZYpAB0gIzswJgA:-KoSowZYpAB0gIzswJgB:bph2bbz) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L153)):*
> ```objc
>   // Construct a matrix similar to E in Anitscu and Potra 1997. This matrix
>   // will be used to specify the constraints 0 ≤ μ⋅fN - E⋅fF ⊥ λ ≥ 0 and
>   // 0 ≤ e⋅λ + F⋅dv/dt ⊥ fF ≥ 0.
> ```

BTW, consider reminding the reader what's lambda, also the second line is probably E lambda? 

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSoH96hPX8MZO02VGZ:-KoSoH96hPX8MZO02VG_:b-jqgeap) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L165)):*
> ```objc
>   // D⋅M⁻¹⋅Nᵀ          D⋅M⁻¹⋅Dᵀ  E
>   // μ                 -Eᵀ       0
>   // where D = [F -F]
> ```

I suspect D is [F; -F]

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSSLXWRAeVhHNC_8ZA:-KoSSLXWRAeVhHNC_8ZB:b-txb9es) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L127)):*
> ```cpp
>   solver_.SolveContactProblem(cfm_, data_, &cf);
> 
>   // Verify that the frictional forces equal the horizontal forces.
> ```

BTW this line might be more appropriate 2 lines below. 

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 130 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSRVasRqoHBM78mUu7:-KoSRVasRqoHBM78mUu8:b7tpc62) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L130)):*
> ```cpp
>   EXPECT_TRUE(data_.sliding_contacts.empty());
>   const int nc = data_.non_sliding_contacts.size();
>   EXPECT_NEAR(cf.segment(nc, cf.size() - nc).norm(), horz_f, eps_);
> ```

should this be lpNorm<1> as well? i guess since you have all friction force concentrated at one contact point, norm does give the right answer. 

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSSVHef1wkfy_lRBUr:-KoSSVHef1wkfy_lRBUs:b-3h9n99) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L145)):*
> ```cpp
>   solver_.SolveContactProblem(cfm_, data_, &cf);
> 
>   // Verify that there are no frictional forces.
> ```

BTW move down 2 line. 

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 175 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSTkbRmeZsMGvGEz2u:-KoSTkbRmeZsMGvGEz2v:bqojg3o) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L175)):*
> ```cpp
>   EXPECT_TRUE(data_.non_sliding_contacts.empty());
>   const int nc = data_.sliding_contacts.size();
>   EXPECT_LT(cf.segment(nc, cf.size() - nc).norm(), eps_);
> ```

BTW idk how meaningful it is to test this, because your cf only contains non-sliding friction, in this cases, there is none. so you are checking a 0 length vec's norm against zero.. 

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 187 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSUHEudJqXK23HsMTM:-KoSUHEudJqXK23HsMTN:bcthrzu) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L187)):*
> ```cpp
> TEST_F(RigidContact2DSolverTest, SinglePointSliding) {
>   // Set the state of the rod to resting on its side with horizontal velocity.
>   SetRodToRestingHorizontalConfig();
> ```

Vertical ?

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 202 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSULih0bkAMxWjGb0a:-KoSULih0bkAMxWjGb0b:b-ksieog) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L202)):*
> ```cpp
>   EXPECT_TRUE(data_.non_sliding_contacts.empty());
>   const int nc = data_.sliding_contacts.size();
>   EXPECT_LT(cf.segment(nc, cf.size() - nc).norm(), eps_);
> ```

BTW same complaint as above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508)*

**Comment by edrumwri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/multibody/rigid_contact/BUILD, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSH0CU7ZPSfgS2W28u:-KoU1wRkaWP40ynt-Mhb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/BUILD#L32)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i suspect this needs a ":" and goes above, like what you did in rigid_contact_solver_test
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSK3JOQjxULvVHPZcZ:-KoU2BObcaB_wEu1sqyD:b3ho0kp) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L51)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I would suggest splitting cf into two parts, and maybe have the shear force event be a std::vector<VectorX<T>>*
</blockquote></details>

I don't want to do this in this PR: As it stands, `cf` essentially represents the output of the LCP solver. I can instead output contact frame information, but didn't want to do that in this PR b/c it would make it significantly larger. I've considered and rejected several intermediate representations, like that you suggested. 

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSKMnjp7UY2CvfnCFn:-KoU9EQvPPpjzZoBcBSP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L56)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW this is just VectorX<T> right?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSLRq_N9_T3nGRBoJ_:-KoU6VroFBR41r1ax9Uw:b44h6g8) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L110)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW might be easier for the reader if you write a one liner saying these are the constraints that z and w has to satisfy. also 10 / 100 seems like magical numbers to me.
</blockquote></details>

Excellent points. Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSLz7TubbGuMswjAQU:-KoU6bCMnPRWPc4YuwGN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L127)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW VectorX<T>
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 153 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSowZYpAB0gIzswJgA:-KoU7FjG5lMAyzlHt0Pn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L153)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, consider reminding the reader what's lambda, also the second line is probably E lambda? 
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 165 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSoH96hPX8MZO02VGZ:-KoU7OlBpFuQpMaLzgCr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L165)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I suspect D is [F; -F]
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSSLXWRAeVhHNC_8ZA:-KoU7kZQVj2rTc9xfRwO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L127)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW this line might be more appropriate 2 lines below. 
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 130 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSRVasRqoHBM78mUu7:-KoU80Dk8zTcSMaGYNVO:bjed10t) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L130)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

should this be lpNorm<1> as well? i guess since you have all friction force concentrated at one contact point, norm does give the right answer. 
</blockquote></details>

Good catch- that was just waiting to break.

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSSVHef1wkfy_lRBUr:-KoU8LA3f1uG2MLm80d_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L145)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW move down 2 line. 
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 175 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSTkbRmeZsMGvGEz2u:-KoU8h4c3mCWhv2EpuJ7:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L175)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW idk how meaningful it is to test this, because your cf only contains non-sliding friction, in this cases, there is none. so you are checking a 0 length vec's norm against zero.. 
</blockquote></details>

Fixed.

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 187 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSUHEudJqXK23HsMTM:-KoU9BY_avtKD0CbvYD8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L187)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Vertical ?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc, line 202 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSULih0bkAMxWjGb0a:-KoU9CeIKjLoeVdBN8RQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/test/rigid_contact_solver_test.cc#L202)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW same complaint as above. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_contact/rigid_contact_solver.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-KoSK3JOQjxULvVHPZcZ:-KohV-87E0IMVHxbACeu:b-ph0g66) ([raw file](https://github.com/robotlocomotion/drake/blob/1b6cc97683afd9be27191786ff45f5bb96c4b16b/drake/multibody/rigid_contact/rigid_contact_solver.h#L51)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't want to do this in this PR: As it stands, `cf` essentially represents the output of the LCP solver. I can instead output contact frame information, but didn't want to do that in this PR b/c it would make it significantly larger. I've considered and rejected several intermediate representations, like that you suggested. 
</blockquote></details>

understood. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KohWMlKqJpo15gjb4-6:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KohY8slwtPs76Vw8rNf:bnfp4nl)*

**Comment by edrumwri** [comment]
Thanks for the great reviews, guys!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6508#-:-KohaKu2ohfcS0MD9rh2:b-zavu5n)*

**Pull request merged**
