### PR TITLE
Relocate DiagnosticPolicyTestBase to common/test_utilities

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. `DiagnosticPolicy` is in `common`.
2. As we recognize that parsing happens outside of multibody/parsing
   (e.g., reading OBJ files), the resource to test policy application needs
   to be more broadly available.

We relocate the header-only class and update references to it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for both reviews.

+(status: single reviewer ok) +(release notes: none) 

I conservatively submitted the PR with two commits (just to make sure there would be no confusion between move and edit). It seems to have worked (even if it was probably redundant). I'll be squashing prior to merging with the commit message being that of the second commit.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-:-NU2Ec6w6Lyew2H3Mm43:b3c9w9h)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW I did a quick once through and flagged a number of anachronisms which arose from copypasta. I'll fix them after you've had a chance to do a once over as well.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-:-NU2FI8u09wPKQnLHRwS:bgz3949)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`multibody/parsing/BUILD.bazel` line 504 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-NU2F5sv4_IKTyhF7Huo:-NU2F5sv4_IKTyhF7Hup:b-b5r2it) ([raw file](https://github.com/RobotLocomotion/drake/blob/0eeb731b4b7c51baeb157b8814e04b83b535deaa/multibody/parsing/BUILD.bazel#L504)):*
> ```Starlark
>         "//common:find_resource",
>         "//common/test_utilities",
>         "//common/test_utilities:diagnostic_policy_test_base",
> ```

nit: redundant.
___
*[`multibody/parsing/BUILD.bazel` line 534 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-NU2F8-H-7ofnWnwHWso:-NU2F8-H-7ofnWnwHWsp:b-9iwr1p) ([raw file](https://github.com/RobotLocomotion/drake/blob/0eeb731b4b7c51baeb157b8814e04b83b535deaa/multibody/parsing/BUILD.bazel#L534)):*
> ```Starlark
>         "//common:find_resource",
>         "//common/test_utilities",
>         "//common/test_utilities:diagnostic_policy_test_base",
> ```

nit: redundant
___
*[`multibody/parsing/BUILD.bazel` line 550 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-NU2F9DxE9VnJrzEGmd3:-NU2F9DxE9VnJrzEGmd4:b-9iwr1p) ([raw file](https://github.com/RobotLocomotion/drake/blob/0eeb731b4b7c51baeb157b8814e04b83b535deaa/multibody/parsing/BUILD.bazel#L550)):*
> ```Starlark
>         "//common:find_resource",
>         "//common/test_utilities",
>         "//common/test_utilities:diagnostic_policy_test_base",
> ```

nit: redundant
___
*[`multibody/parsing/BUILD.bazel` line 595 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-NU2FBSa3hXLm0kVQJ1P:-NU2FBSa3hXLm0kVQJ1Q:b-9iwr1p) ([raw file](https://github.com/RobotLocomotion/drake/blob/0eeb731b4b7c51baeb157b8814e04b83b535deaa/multibody/parsing/BUILD.bazel#L595)):*
> ```Starlark
>         "//common:find_resource",
>         "//common/test_utilities",
>         "//common/test_utilities:diagnostic_policy_test_base",
> ```

nit: redundant

**Review by rpoyner-tri — COMMENTED** [review]
Excellent idea, this patch. I had thought of it numerous times, but never sat down to write it. Thanks!

:lgtm: pending build rule cleanups you flagged.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-:-NU2GkW13W68jYDCvvCF:br7s5zk)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Clean ups cleaned up.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292#-:-NUMrFy49j63Lir4HwLy:b94y47)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19292)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
