### PR TITLE
setup: Install fmt and spdlog via homebrew

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Adding in anticipation of compiling against the host library, instead of our own separate copy.

Relates to #14429 for Ubuntu.

Towards #14427 and #14220.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14517)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14517#-:-MQoSqXvEBLkFDMj_4vu:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14517#-:-MQrCTbi9mDPIP5tMNq5:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jamiesnape

**Pull request merged**
