### PR TITLE
add AcceptConvexSolver

### PR DESCRIPTION
**Pull request by hongkai-dai**
As discussed in https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1665523153073139?thread_ts=1664323622.044599&cid=C3L92BM2Q

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18099)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@jwnimmer-tri I feel that I don't like this function very much
1. AcceptConvexSolver has a vague meaning. It could mean "this problem is convex and should be solved by a convex solver", or "this problem is actually non-convex (like a mixed-integer linear program), but it accepts a convex solver (like gurobi) which also happen to solve this problem.
2. I currently implement this function based on the program type, but there are so combinatorial number of program types (based on the combination of different costs/constraints) and we don't have an exhaustive list of all types of programs.
3. I think is_convex is mathematically well defined and has a clear meaning to the user.


The only reason why we didn't have "is_convex" is because we store individual cost, but we actually care about the summed-up cost.

So here is one proposal:
We don't store the individual linear costs and quadratic costs. Instead we store the summed-up linear and quadratic costs as
```
0.5 * x' * Q * x + b' * x + c
```
where `Q` and `b` are sparse matrices. Then it is easy to determine if the summed up cost is convex or not. Besides, for each solver, we actually need to sum up the cost to this form any way, as we did in GurobiSolver/MosekSolver/etc, so we might just store the summed-up cost in the MathematicalProgram.

WDYT?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18099#-:-NEEa6Jz3OV-n-e_sOIa:bk67rl3)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by jwnimmer-tri** [comment]
I agree that `AcceptConvexSolver` is not great.  For me the main takeaway from that slack is the idea of setting an option on the program to fail-fast in case it ended up not being convex.  Since the slack, I realized that could option actually be a SolverOptions setting -- `CommonSolverOption::kRequireConvex` or `CommonSolverOption::kRequireConvexSolver`.  That's probably more useful that a magic function like `MP::require_convex_solver(true)`.

There's a _separate_ question as to whether the invariant being checked is that the _program_ is convex or whether the _chosen solver method_ is convex.

I do agree that checking convexity of the composite Q would narrow the gap between the two questions, but I think that's somewhat separate from the question at hand.  I still think what users will actually care about is that the _solution method_ is convex, and so that's the invariant we should help them out with.  I don't think "the program is convex but the solution method will not be" is a particularly helpful form of "is convex" to focus on for sugar.

**Comment by hongkai-dai** [comment]
I think we have the problem that sometimes the problem is convex, but `ChooseBestSolver` doesn't select the convex solver. For example, when we have several quadratic costs with one of them being non-convex, while the summed-up cost is convex.

So when we choose the solver, I would like to compute the summed-up quadratic cost, and then check if the Hessian is positive semidefinite or not. If yes, then we call the convex solver.

But this create the problem that we would sum-up the quadratic costs for twice, once when we decide whether the problem is convex, and once inside the solver wrapper (like GurobiSolver, MosekSolver) to pass MathematicalProgram data to the actual solver. The function to sum up the quadratic costs is not a cheap operation, hence this creates redundant computation cost.

This is why I proposed in #18103 to store the summed-up cost in MathematicalProgram. As you mentioned, this is not a good idea. I wonder if there is a quick workaround. One ugly solution I thought of is to create a private field

```
class MathematicalProgram {
 private:
  Eigen::SparseMatrix<double> Q_;
}
```
This `Q_` is only set when we call `Solve` function, and only the solver wrappers, like GurobiSolver/MosekSolver can access this `Q_`. But this solution feels like a landmine.

What would be a better solution?

**Comment by jwnimmer-tri** [comment]
Given the discussions here and in #18103, it seems like we should close this PR?

**Pull request closed without merging**
