### PR TITLE
Parallelize the Pairwise Set Intersection Checking for GCS (with or without Continuous Revolute Joints)

### LINKED ISSUE #21351: Parallelize Intersection Checks in GcsTrajectoryOptimization
When adding a regions through GcsTrajectoryOptimization::AddRegions or edges through GcsTrajectoryOptimization::AddEdges, a lot of pairwise intersection checks are performed in series. These intersections checks can be moved into one single optimization problem which is then parallelized by the optimizer. However, since the checks habe been moved to [CalcPairwiseIntersections](https://github.com/RobotLocomotion/drake/blob/ee96c093c0b131c00d527cd053d74bc8465a1c14/geometry/optimization/geodesic_convexity.cc#L231), this may require more care.

### PR DESCRIPTION
**Pull request by cohnt**
Closes #21351. (Although once we have a `parallelism` option added to GCS, as is being discussed in #21965, we should make sure that gets plumbed through.)

Note that the parallelism here is used in two ways -- the computation of AABBs of the constituent sets is handled with a parallel for loop, and then the pairwise intersections themselves are checked with `SolveInParallel`.

This leads to significant speedups, especially on faster graphs. With 224 sets (resulting in 5928 edges), we have the following computation times:
```
Parallel? No AABB Preprocessing? No 	Runtime: 1.174356460571289
Parallel? No AABB Preprocessing? Yes 	Runtime: 1.1098930835723877
Parallel? Yes AABB Preprocessing? No 	Runtime: 0.2572915554046631
Parallel? Yes AABB Preprocessing? Yes 	Runtime: 0.2135148048400879
```
With 1120 sets (resulting in 152680 edges), we have the following computation times:
```
Parallel? No AABB Preprocessing? No 	Runtime: 26.704376697540283
Parallel? No AABB Preprocessing? Yes 	Runtime: 19.698741912841797
Parallel? Yes AABB Preprocessing? No 	Runtime: 4.901020050048828
Parallel? Yes AABB Preprocessing? Yes 	Runtime: 3.577193021774292
```
(This is on my personal computer, with 20 threads.)

+@sadraddini for feature review, if you have the time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142)

### CODE REVIEW

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-:-OBQqDqf1kxEsN3dcq6k:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
+@sammy-tri for platform review please

**Review by sammy-tri — COMMENTED** [review]
No objections, just waiting for resolution to a question in #21965

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-:-OBSIB76EjVtX-hIJNxC:bll9wbx)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1463 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-OBSMf7A8K1gnj08eVHK:-OBSSy_X-G38UnCI_dJY:b-domg0a) ([raw file](https://github.com/RobotLocomotion/drake/blob/5da565c2b0f7b2a4e560b1aba86e2df2b441cbc2/bindings/pydrake/geometry/geometry_py_optimization.cc#L1463)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

From discussion in #21957 I think these need `gil_scoped_release` now.
</blockquote></details>

Done.

We also need it for some methods in `GcsTrajectoryOptimization`, since those methods potentially call `ComputePairwiseIntersections`behind the scenes.

Note: I found that adding `gil_scoped_release` to the deprecated `CalcPairwiseIntersections` methods led to a segmentation fault, so I'm guessing we shouldn't include it for those?

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1463 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-OBSMf7A8K1gnj08eVHK:-OBSV3o548nzqYM8Xbmc:bmfm2dw) ([raw file](https://github.com/RobotLocomotion/drake/blob/5da565c2b0f7b2a4e560b1aba86e2df2b441cbc2/bindings/pydrake/geometry/geometry_py_optimization.cc#L1463)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Done.

We also need it for some methods in `GcsTrajectoryOptimization`, since those methods potentially call `ComputePairwiseIntersections`behind the scenes.

Note: I found that adding `gil_scoped_release` to the deprecated `CalcPairwiseIntersections` methods led to a segmentation fault, so I'm guessing we shouldn't include it for those?
</blockquote></details>

Ouch, I guess not.  cc  @calderpg-tri for a consult based on your comments in the other PR.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1463 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-OBSMf7A8K1gnj08eVHK:-OBWb7F54lgxuaoAqnUI:b-1cbsr8) ([raw file](https://github.com/RobotLocomotion/drake/blob/5da565c2b0f7b2a4e560b1aba86e2df2b441cbc2/bindings/pydrake/geometry/geometry_py_optimization.cc#L1463)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ouch, I guess not.  cc  @calderpg-tri for a consult based on your comments in the other PR.
</blockquote></details>

As a general rule, anything that takes a `Parallelism` and uses it to perform parallel operations should get a `py::gil_scoped_release` unless you are absolutely sure there's no way the parallelized operations will invoke Python code (remember, *any* `drake::log()` could result in log redirection through Python). I would expect all of these methods to need `py::gil_scoped_release`.

If you have a case where *adding* the `py::gil_scoped_release` to a binding leads to a segfault, my gut reaction is that the existing code wasn't correctly handling thread safety but the GIL was coincidentally hiding the bug.

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please
 @drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please
 @drake-jenkins-bot linux-jammy-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-address-sanitizer please

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1463 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-OBSMf7A8K1gnj08eVHK:-OBWuLl905SshvTsVbiJ:b-y47nrt) ([raw file](https://github.com/RobotLocomotion/drake/blob/5da565c2b0f7b2a4e560b1aba86e2df2b441cbc2/bindings/pydrake/geometry/geometry_py_optimization.cc#L1463)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

As a general rule, anything that takes a `Parallelism` and uses it to perform parallel operations should get a `py::gil_scoped_release` unless you are absolutely sure there's no way the parallelized operations will invoke Python code (remember, *any* `drake::log()` could result in log redirection through Python). I would expect all of these methods to need `py::gil_scoped_release`.

If you have a case where *adding* the `py::gil_scoped_release` to a binding leads to a segfault, my gut reaction is that the existing code wasn't correctly handling thread safety but the GIL was coincidentally hiding the bug.
</blockquote></details>

The deprecated `Calc` versions all use `Parallelism::None()` anyway so I don't think they'd need it.  I'm not sure why there would be a segfault though.

My intuition is to to go ahead with this PR as is since it seems correct but I'm a little spooked.  I'll throw some tsan and memcheck builds at it to see if anything pops up before merging.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-:-OBXWg5V4jWuyxhRPG4o:by1pdfu)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sadraddini

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1463 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-OBSMf7A8K1gnj08eVHK:-OBXVpL7DRYtiqi9IPqd:b-ou4zs9) ([raw file](https://github.com/RobotLocomotion/drake/blob/5da565c2b0f7b2a4e560b1aba86e2df2b441cbc2/bindings/pydrake/geometry/geometry_py_optimization.cc#L1463)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The deprecated `Calc` versions all use `Parallelism::None()` anyway so I don't think they'd need it.  I'm not sure why there would be a segfault though.

My intuition is to to go ahead with this PR as is since it seems correct but I'm a little spooked.  I'll throw some tsan and memcheck builds at it to see if anything pops up before merging.
</blockquote></details>

Ok, I did a little more digging on my side and I think I know what's going on.  For the `Calc*` *deprecated* overloads,  there is only one thread,  but there's a call into `WarnDeprecated` when the function is run, which tries to redirect the output through python with the GIL released, and there's our segfault. 

There's a bigger issue to be had if someone tries to deprecate a function which required `gil_scoped_release` but no need to hold up this PR for that.

**Comment by cohnt** [comment]
Thanks for tracking down the root cause! Should we document somewhere that this is a footgun one needs to worry about when deprecating (potentially) multithreaded code?

**Comment by jwnimmer-tri** [comment]
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1463 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22142#-OBSMf7A8K1gnj08eVHK:-OBlApcX8j5IO4Ajad3s:bbsydxy) ([raw file](https://github.com/RobotLocomotion/drake/blob/5da565c2b0f7b2a4e560b1aba86e2df2b441cbc2/bindings/pydrake/geometry/geometry_py_optimization.cc#L1463)):*
> > ... there's a call into `WarnDeprecated` when the function is run, which tries to redirect the output through python with the GIL released, and there's our segfault.
>
> Thanks for tracking down the root cause! Should we document somewhere that this is a footgun one needs to worry about when deprecating (potentially) multithreaded code?

It was a bug in the wrapper, so we'll fix the bug (and then no docs needed):

=> #22195

**Pull request merged**
