### PR TITLE
Rule-of-three the test utility PackValue.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fix up the Bazel build, and add a few cc_test rules for the tests that use PackValue.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3989)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@jwnimmer-tri for both levels of review (most of the churn is Bazel, the C++ change is trivial)

**Comment by jwnimmer-tri** [comment]
:lgtm: with some BTWs for your consideration.

---

Reviewed 6 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/analysis/BUILD, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTiErE4SKKHnoOnM8:-KVWTiEtY9b4S3nbc3wa:b-yo6h1j) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/analysis/BUILD#L7)):*
> ```Python
>     visibility = ["//visibility:public"],
>     deps = ["//drake/systems/framework"],
>     linkstatic = 1)
> ```

BTW Missing newline at EOF.

---

*[drake/systems/framework/BUILD, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTwbpOCj0GvDnCO49:-KVWTwbpOCj0GvDnCO4A:b584a29) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/BUILD#L7)):*
> ```Python
>     hdrs = glob(["*.h"]),
>     srcs = glob(["*.cc"]),
>     visibility = ["//visibility:public"],
> ```

BTW This was redundant in my version, and is also here (given the top-of-file statement).

---

*[drake/systems/framework/BUILD, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTkH5YstXtAilsbnc:-KVWTkH6RngetU74Jgqh:b-uwje0f) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/BUILD#L14)):*
> ```Python
>     ],
>     linkstatic=1)
>     
> ```

BTW Trailing whitespace and missing newline at EOF.

---

*[drake/systems/framework/test/BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWVHft9atNLxK6Sxlr:-KVWVHfuVozMLII4ROVw:bahbml6) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L6)):*
> ```Python
>     name = "leaf_context_test",
>     srcs = ["leaf_context_test.cc"],
>     visibility = ["//visibility:public"],
> ```

BTW META This is redundant with the top-of-file statement, I think?

---

*[drake/systems/framework/test/BUILD, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWVSQk4pklLi4rELGR:-KVWVSQk4pklLi4rELGS:b5x8gkf) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L8)):*
> ```Python
>     visibility = ["//visibility:public"],
>     deps = [
>         "//drake/common",
> ```

FYI I'm curious to hear the thought process behind listing this here, versus inheriting it from /systems/framework?

---

*[drake/systems/framework/test/BUILD, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTpVGAVmgFJoWM_2P:-KVWTpVGAVmgFJoWM_2Q:blbkju5) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L16)):*
> ```Python
>     linkstatic=1,
>     testonly=1)
>     
> ```

BTW Trailing whitespace.

---

*[drake/systems/framework/test/BUILD, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTrpAPGydbusZFrmR:-KVWTrpAPGydbusZFrmS:blbkju5) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L30)):*
> ```Python
>     linkstatic=1,
>     testonly=1)
>     
> ```

BTW Trailing whitespace.

---

*[drake/systems/framework/test/BUILD, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTqPuzkzb25SlV9y-:-KVWTqPuzkzb25SlV9y0:b-uwje0f) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L44)):*
> ```Python
>     linkstatic=1,
>     testonly=1)
>     
> ```

BTW Trailing whitespace and missing newline at EOF.

---

*[drake/systems/framework/test_utilities/BUILD, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWUXOhpCiMgFSp6BHZ:-KVWUXOij8KyLQPrXQZR:b-uwje0f) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test_utilities/BUILD#L13)):*
> ```Python
>     linkstatic=1,
>     testonly=1)
>     
> ```

BTW Trailing whitespace and missing newline at EOF.

---

*[drake/systems/framework/test_utilities/pack_value.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWV3juljp0479rijB9:-KVWV3jv35Njr2zpVWDS:b-kdtlrn) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test_utilities/pack_value.h#L9)):*
> ```objc
> 
> template <typename T>
> std::unique_ptr<AbstractValue> PackValue(T value) {
> ```

BTW It's _probably_ okay for none of these to have API comments (testonly, somewhat-obvious) but consider if there's anything useful to say in Doxygen for these.

---

*[drake/systems/framework/test_utilities/pack_value.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWUD0QQmO6nvk7L0u_:-KVWUD0Rd1KXg0y600AT:b-vo857k) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test_utilities/pack_value.h#L15)):*
> ```objc
> template <typename T>
> T UnpackValue(const AbstractValue& value) {
>   return dynamic_cast<const Value<T>*>(&value)->get_value();
> ```

BTW Add assertion or something on dynamic_cast success, for failure-clarity, since this is test code anyway?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-:-KVWVeFF4gCTTwdxTjJi:bwvbcqf)*

**Comment by david-german-tri** [comment]
Review status: 6 of 11 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/analysis/BUILD, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTiErE4SKKHnoOnM8:-KVW_oCy5z0p0iXQ8eoD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/analysis/BUILD#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Missing newline at EOF.
</details>
Done.

---

*[drake/systems/framework/BUILD, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTwbpOCj0GvDnCO49:-KVW_wL7_fjxp8LiCunF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/BUILD#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This was redundant in my version, and is also here (given the top-of-file statement).
</details>
Done.

---

*[drake/systems/framework/BUILD, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTkH5YstXtAilsbnc:-KVW_zfmqp4qwOpTegBz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/BUILD#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Trailing whitespace and missing newline at EOF.
</details>
Done.

---

*[drake/systems/framework/test/BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWVHft9atNLxK6Sxlr:-KVWa1o_cnGrjhUk8OPZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW META This is redundant with the top-of-file statement, I think?
</details>
Done.

---

*[drake/systems/framework/test/BUILD, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWVSQk4pklLi4rELGR:-KVWa3UGjQ71h6DiX2OY:bk4pz7r) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI I'm curious to hear the thought process behind listing this here, versus inheriting it from /systems/framework?
</details>
Transitive dependencies are a landmine whenever you want to remove a dependency.  (Though this one is probably inert.)

---

*[drake/systems/framework/test/BUILD, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTpVGAVmgFJoWM_2P:-KVWaLNk74fWjZEbYBlt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Trailing whitespace.
</details>
Done.

---

*[drake/systems/framework/test/BUILD, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTrpAPGydbusZFrmR:-KVWaLvPh5zTbCmcZ3aR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Trailing whitespace.
</details>
Done.

---

*[drake/systems/framework/test/BUILD, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWTqPuzkzb25SlV9y-:-KVWaUdc382w-S3585ia:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test/BUILD#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Trailing whitespace and missing newline at EOF.
</details>
Done.

---

*[drake/systems/framework/test_utilities/BUILD, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWUXOhpCiMgFSp6BHZ:-KVWaXIR2WGOl4Jop9sR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test_utilities/BUILD#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Trailing whitespace and missing newline at EOF.
</details>
Done.

---

*[drake/systems/framework/test_utilities/pack_value.h, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWV3juljp0479rijB9:-KVWbCi4BjEgpSHZRGC3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test_utilities/pack_value.h#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW It's _probably_ okay for none of these to have API comments (testonly, somewhat-obvious) but consider if there's anything useful to say in Doxygen for these.
</details>
Done.

---

*[drake/systems/framework/test_utilities/pack_value.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3989#-KVWUD0QQmO6nvk7L0u_:-KVWarXCiLljW8guIlXF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb3f2611deaf9ca7b9563bb40ce6e9f583f34f15/drake/systems/framework/test_utilities/pack_value.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Add assertion or something on dynamic_cast success, for failure-clarity, since this is test code anyway?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3989)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3989)*

**Pull request merged**
