### PR TITLE
Toward #2852: enforce -Werror=shadow in systems/trajectories/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove excuse from systems/trajectories/ cmake file.
 * Rename private members with '_' suffix per style guide.
 * Rename global static data with 'g_'.
 * Fix assorted white space issues:
   * indents.
   * remove trailing white space.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2892)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
another blob of #2852.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2892#-:-KNI0st0TcvpnSgcJQCY:1417088721)*

**Comment by rpoyner-tri** [comment]
+@ggould-tri for platform review; it's his day I hear.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2892#-:-KNI3of9-Ht5IijueTbw:1686847639)*

**Comment by ggould-tri** [comment]
Two 'considers' below.  :lgtm: regardless of  how you address them.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectories/test/testPiecewisePolynomial.cpp, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2892#-KNI7HORGnJxrfu_37G5:-KNI7HORGnJxrfu_37G6:-1512562294) ([raw file](https://github.com/robotlocomotion/drake/blob/470423da8c228679b1e8f8133864b24fdc31fe6e/drake/systems/trajectories/test/testPiecewisePolynomial.cpp#L23)):*
> ```cpp
> namespace {
> 
> default_random_engine g_generator;
> ```

FYI -- The `g_` prefix seems to be nonstandard, presumably because non-POD global variables like this are outright forbidden in our code conventions and so they do not formalize a naming convention for what is unclean.

I know this isn't of your creation, but please consider commenting or TODO'ing this violation of the code standards.

---

*[drake/systems/trajectories/test/testPiecewisePolynomial.cpp, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2892#-KNI7UoomBnAivuiL3vO:-KNI7UoomBnAivuiL3vP:-1238891457) ([raw file](https://github.com/robotlocomotion/drake/blob/470423da8c228679b1e8f8133864b24fdc31fe6e/drake/systems/trajectories/test/testPiecewisePolynomial.cpp#L24)):*
> ```cpp
> 
> default_random_engine g_generator;
> uniform_real_distribution<double> g_uniform;
> ```

FYI -- Possibly unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2892#-:-KNI7kXCXLeEng5Lw67y:402917032)*

**Pull request merged**
