### PR TITLE
Update and clean up SceneGraphInspector

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This PR is attempting something new.

The clean up of scene graph inspector includes *moving* a bunch of existing code in a well-principled way as well as adding code. In a single commit, it would be difficult to distinguish the various actions. As such, this PR has been decomposed into a number of commits. I'd recommend doing the initial review commit by commit.

The commits are as follows:
  1. Move existing code around inside their files. No change to the blocks moved, just reorganized.
  2. Removal of a redundant function (revealed by reorganizing the code) in `scene_graph_inspector.h`
  3. Consolidation of redundant documentation between `geometry_state` and `scene_graph_inspector`.h In this case, only doxygen should have changed with the detailed doxygen heading into the public API (`scene_graph_inspector`) and the internal implementation referencing it (`geometry_state.h`)
  4. Expose the introspection methods in `GeometryState` in `SceneGraphInspector`. Methods added to `SceneGraphInspector` and documentation reduced in `GeometryState`.
  5. Added a smoke unit test to confirm that `SceneGraphInspector` builds and runs.

Let me know if this decomposition helps at all.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10263)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
If you intent to merge the individual commits to master (i.e., not to squash-merged into one), then I don't think you get to play the game with the first few being thematic commits that can stand on their own, and then the last one being cleanup shrapnel that applies to the other commits all at once.  Each commit should (ideally) build & pass tests on its own, as if it were its own PR.

**Comment by soonho-tri** [comment]
>  Each commit should (ideally) pass all tests and code review on its own, as if it were its own PR.

FYI, one can check it by running `git rebase upstream/master --exec "bazel test //geometry/... -c dbg"`.

**Comment by jwnimmer-tri** [comment]
Makes sense now, thanks!

**Comment by soonho-tri** [comment]
Got it. Thanks!

**Pull request merged**
