### PR TITLE
Temporarily disable all tests that require Gurobi.

### PR DESCRIPTION
**Pull request by david-german-tri**
See #5862.

@jamiesnape for all review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5863)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5863#-:-KhwyWBWj8KRXAeI6ch9:bg7igkv)*

**Comment by david-german-tri** [comment]
Due to multiple stacked breakages, this will not fix everything, but it's a step forward and we'll merge it once CI passes.  I don't want to combine other fixes into this PR, because this one we will revert once we have Gurobi licenses in CI again.

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5863#-:-Khx-yXdYqGejDgFHRak:baohcag)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by RussTedrake** [comment]
N.B. - i would have thought it would be much better to disable CI's use of gurobi, rather than comment out the tests?  This means that local users (with gurobi license intact) also miss the tests.  I don't think it's worth changing right now, but would it have been harder than I think to take the other route?

**Comment by david-german-tri** [comment]
I'd argue the opposite - it's better for a developer's local experience to match CI as closely as possible, and for the "paper trail" to be clearly visible to the entire team.  In a perfect world CI would have no configuration knobs.  

I do wish we had a way to mark tests as disabled but still allow developers to run them on-demand.  Neither Bazel nor CMake appears to make that easy; all of the hacks I've been able to think up to add it to Bazel are probably worse than the status quo.

**Comment by david-german-tri** [comment]
> would it have been harder than I think to take the other route?

About equally easy, I think.  @jamiesnape actually did that for CMake in  https://github.com/RobotLocomotion/drake-ci/commit/c12d979914df3c860dbb5632c0bf7a0ae1b19625#diff-68f7e7ada24bc116b2a071ba18a58a41, and we would have set `--test_tag_filters=-gurobi` [here](https://github.com/RobotLocomotion/drake-ci/blob/master/driver/configurations/bazel.cmake#L59) for Bazel.

**Comment by RussTedrake** [comment]
I see your point about matching CI with local developers experience.  Hopefully we resolve this shortly in either case.  Thanks.

**Pull request merged**
