### PR TITLE
Replace drake/Path.h with drake/common/drake_path.h

### LINKED ISSUE #2174: Stop using Path.h.in
The drake/drake/core/Path.h.in implementation should be replaced, due to its many problems:
- Hard-coding the source tree path of Drake into its exported library.
- Putting generated code into a header file (`Path.h.in`).
- Having the header file live outside of the directory structure (in `drake/` instead of `drake/core/`).
- Using `std::string` for static constant (it is ~~non-POD~~ not Plain Old Data).

I am working on a PR with some fixes:
- ~~GetDrakePath will only be available to tests, and shall not be used by other non-test libraries.~~ _(Edited: This is now out-of-scope for this issue)_.
- GetDrakePath will use a generated `*.cc` file, not `*.h` file.
- The C++ code will obey the style guide.

Work in progress will be in my [getDrakePath-fixes branch](https://github.com/jwnimmer-tri/drake/tree/getDrakePath-fixes).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Replace `drake/Path.h` with `drake/common/drake_path.h`, and move the string constant to the `*.cc` file (and thus the `libdrakeCommon` library).

Notably, this does _not_ rename the free function to `GetDrakePath`, nor change its namespace.  Given that we need to replace this function with something better (generalized model-from-file-loading) anyway in the future, it didn't seem worth it to make all of downstream eat the API rename.

Closes #2174.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2997)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
@liangfok for feature review, please.
@sherm1 for platform review, please.

N.B. Many of the changes here are just perl pie, per the commit messages.

**Comment by liangfok** [comment]
Just two comments.

---

Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNtlaGRzDSJzrCxrMhr:-KNtlaGRzDSJzrCxrMhs:803059679) ([raw file](https://github.com/robotlocomotion/drake/blob/a1d62773fe3e7e181ee5f58a9d9b3fdea8fa685d/CHANGELOG.md#L26)):*
> ```Markdown
> ### Changed
> 
>  - [#2995][] Renamed drake/Path.h to drake/common/drake_path.h
> ```

I believe this should be 2997.

---

*[CHANGELOG.md, line 104 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNtleEllTx9b8a7QpJa:-KNtleEm515XzTPRS1-n:-517430443) ([raw file](https://github.com/robotlocomotion/drake/blob/a1d62773fe3e7e181ee5f58a9d9b3fdea8fa685d/CHANGELOG.md#L104)):*
> ```Markdown
> [#2963]: https://github.com/RobotLocomotion/drake/issues/2963
> [#2983]: https://github.com/RobotLocomotion/drake/issues/2983
> [#2995]: https://github.com/RobotLocomotion/drake/issues/2995
> ```

2997?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNtn3Yweao1nFjuRba8:1543564695)*

**Comment by jwnimmer-tri** [comment]
Review status: 42 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNtlaGRzDSJzrCxrMhr:-KNtoADIcz7UL_60SVjR:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a1d62773fe3e7e181ee5f58a9d9b3fdea8fa685d/CHANGELOG.md#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I believe this should be 2997.
</details>
Done.

---

*[CHANGELOG.md, line 104 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNtleEllTx9b8a7QpJa:-KNtoAa_U0nyUTM9lWGF:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a1d62773fe3e7e181ee5f58a9d9b3fdea8fa685d/CHANGELOG.md#L104)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> 2997?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNtp5X8_CHRs6jcql7V:1417088721)*

**Comment by sherm1** [comment]
I randomly sampled a few of the converted files and it seemed that many of them were not using `getDrakePath()` at all. It would be good not to include the header at all in that case; your discretion though since this is clearly an improvement. I suggest providing `GetDrakePath()` as an alternate spelling. Most of all it would be great NOT to embed the source file directory in the generated code at all! (But that's just a fantasy I have.)

---

Reviewed 42 of 43 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/drake_path.cc.in, line 9 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuXqQ1ht6caScMlms4:-KNuXqQ1ht6caScMlms5:-75854791) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/common/drake_path.cc.in#L9)):*
> ```
> std::string getDrakePath() {
>   return std::string("@PROJECT_SOURCE_DIR@");
> }
> ```

BTW, consider renaming to `GetDrakePath()` but including `std::string getDrakePath() {return GetDrakePath();}` also to avoid the downstream troubles you mentioned. That would allow conscientious programmers to use the right name.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuX_DCybqnn008lPxn:-KNuX_DCybqnn008lPxo:1963936230) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L4)):*
> ```cpp
> #include "drake/examples/kuka_iiwa_arm/iiwa_simulation.h"
> #include "drake/examples/kuka_iiwa_arm/iiwa_status.h"
> #include "drake/common/drake_path.h"
> ```

BTW, unused in this file?

---

*[drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuYwTP57lYNGSSOkl4:-KNuYwTP57lYNGSSOkl5:1963936230) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc#L3)):*
> ```cpp
> #include <iostream>
> 
> #include "drake/common/drake_path.h"
> ```

BTW, unused in this file?

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 7 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuZ5zgQauDkAxFy5Ev:-KNuZ5zgQauDkAxFy5Ew:1963936230) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L7)):*
> ```cpp
> #include "drake/examples/kuka_iiwa_arm/iiwa_simulation.h"
> #include "drake/examples/kuka_iiwa_arm/robot_state_tap.h"
> #include "drake/common/drake_path.h"
> ```

BTW, unused in this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNuZFZF57ZdSN9VlIwO:1699722457)*

**Comment by sherm1** [comment]
Oh, and :lgtm: !

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNu_6wG2XmciAVehjGF:-1401065624)*

**Comment by liangfok** [comment]
I added explanations on how those extraneous `#include` lines happened.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuX_DCybqnn008lPxn:-KNvQbQsxCuMQkmSbCbn:1542234653) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/examples/kuka_iiwa_arm/kuka_lcm_visualizer.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, unused in this file?
</details>
You're right! The path is actually used in `iiwa_simulation.cc`. This `#include` was leftover from before we created the "drakeKukaIiwaArm" library.

---

*[drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuYwTP57lYNGSSOkl4:-KNvQz5Wsc_HvbApjiG1:1542234653) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/examples/kuka_iiwa_arm/run_kuka_iiwa_arm_dynamics.cc#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, unused in this file?
</details>
You're right! The path is actually used in `iiwa_simulation.cc`. This `#include` was leftover from before we created the "drakeKukaIiwaArm" library.

---

*[drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc, line 7 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuZ5zgQauDkAxFy5Ev:-KNvR1tnUM3SHQTCsTSh:1542234653) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/examples/kuka_iiwa_arm/test/kuka_iiwa_arm_test.cc#L7)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, unused in this file?
</details>
You're right! The path is actually used in `iiwa_simulation.cc`. This `#include` was leftover from before we created the "drakeKukaIiwaArm" library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNvR46yglanXwVGW7ri:-1699599129)*

**Comment by jwnimmer-tri** [comment]
I've added `GetDrakePath` and deprecated `getDrakePath`.  I'm going to leave alone the stray includes though, since I don't have a great tool-based way to address them (yet).

---

Review status: 9 of 44 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/common/drake_path.cc.in, line 9 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-KNuXqQ1ht6caScMlms4:-KNvdTBCAdiN8X9aKIMl:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9bc368c65b955ff9850a93cbd86f2e3617b4c621/drake/common/drake_path.cc.in#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, consider renaming to `GetDrakePath()` but including `std::string getDrakePath() {return GetDrakePath();}` also to avoid the downstream troubles you mentioned. That would allow conscientious programmers to use the right name.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNvdG8il0-she-Khqsp:427644164)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3, 33 of 33 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2997#-:-KNw792ChCYXol2nLe0C:1417088721)*

**Pull request merged**
