### PR TITLE
Fix sign-compare warning in gurobi_solver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Alternative solution to #2878.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2879)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Test builds will be at (currently broken links until the build starts):
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental/62/
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-ninja-experimental/8/

**Comment by jwnimmer-tri** [comment]
@naveenoid for feature review.

**Comment by jwnimmer-tri** [comment]
The two test builds passed.

The default pre-merge PR checks had a Jenkins flake on linux-clang-ninja-debug, so I've fired up a one-off build of that here:
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-clang-ninja-experimental/8/

**Comment by jamiesnape** [comment]
LGTM. This needs to merged now.

**Comment by jwnimmer-tri** [comment]
The final test build just passed.  I guess I will override-merge to get things working again.

**Comment by naveenoid** [comment]
Thanks! Sorry for not looking at it earlier.

**Pull request merged**
