### PR TITLE
Support Gaussian initial conditions in Affine/Linear systems.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12637)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I think perhaps the configured values do not survive transmogrification?

FWIW another way to phrase this would be to declare x0 and sigma as Parameters, instead of members.  Then, these new methods would take a `Context*` pointer and operate on the parameters there.

**Comment by jwnimmer-tri** [comment]
> FWIW another way to phrase this would be to declare x0 and sigma as Parameters, ...

Hmm, actually -- state initialization can't (currently) depend on parameters.  So that's a no-go.

**Comment by jwnimmer-tri** [comment]
Hmm, I just noticed -- we have a general rule of thumb against placing T-valued scalars as member fields on a System.  When T-valued data are not part of a Context, they often end up being difficult to correctly establish derivative values, or set to the correct Variable expressions.

For example -- for the A/B/C/D matrices, `TimeVaryingAffineSystem` supports returning T-valued matrices, but `AffineSystem` only supports double-valued constructor values.

Could we demote the initial state value in this PR to be a `VectorXd` instead of `VectorX<T>` until we find and understand a use case that needs more?

That would also simplify the transmog ctor here, to not require ExtractDoubleOrThrow.  As it stands, it looks a user could not reasonably supply non-double default values to this System anyway, since they would be disrupted during transmogrification.

**Comment by RussTedrake** [comment]
I went through the same though process, also questioning the current implementation of the return values of `A()`, `B()`, etc.  I also almost switched to `VectorXd` this morning, rather than deal with the extra code.

But I think that the user *can* get value in this current form.  The only time information is lost is if someone converts FROM autodiff/symbolic TO double.  Otherwise, the interface is just as rich as every other example of transmogrification.  If I want derivatives relative to the default state, then I transmogrify, get a context, and set the gradients in that context (like always).

**Comment by jwnimmer-tri** [comment]
OK, good to see you've thought about it.  Given the tradeoffs, I don't think the current code is defective, and I'm OK to move forward as-is.

**Pull request merged**
