### PR TITLE
Added missing includes to RigidBodyFrame.h.

### PR DESCRIPTION
**Pull request by liangfok**
To conform to the [C++ style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes).

> You should include all the headers that define the symbols you rely upon, except in the unusual case of forward declaration. If you rely on symbols from bar.h, don't count on the fact that you included foo.h which (currently) includes bar.h: include bar.h yourself, unless foo.h explicitly demonstrates its intent to provide you the symbols of bar.h. However, any includes present in the related header do not need to be included again in the related cc (i.e., foo.cc can rely on foo.h's includes).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2060)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2060#-:-KF6-3lvxT1c_IRCqWn6:1417088721)*

**Comment by jwnimmer-tri** [comment]
I think there is a defect here.  I can look within the hour, but please wait to merge until I have a free moment to confirm for sure.

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/RigidBodyFrame.h, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2060#-KF63WVYZ8LEM6GkAeDJ:-KF63WVYZ8LEM6GkAeDK:-1549312410) ([raw file](https://github.com/robotlocomotion/drake/blob/7f2e9a07f272b468a2e63cfcde74e406f32aabcb/drake/systems/plants/RigidBodyFrame.h#L8)):*
This induces a direct #include cycle, and can break compilation.  This class is already forward-declared below, so need not be !included.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2060)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyFrame.h, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2060#-KF63WVYZ8LEM6GkAeDJ:-KF64LuvZoAwCSWASjjx:1091120207) ([raw file](https://github.com/robotlocomotion/drake/blob/7f2e9a07f272b468a2e63cfcde74e406f32aabcb/drake/systems/plants/RigidBodyFrame.h#L8)):*
Thanks. I've removed it. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2060)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/RigidBodyFrame.h, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2060#-KF65gpiRU8xhRFdjqT_:-KF65gpjv6CZWAgKnBGM:-1723893116) ([raw file](https://github.com/robotlocomotion/drake/blob/65eb15cb1b0719ce23267b972ca675c952d47200/drake/systems/plants/RigidBodyFrame.h#L6)):*
This "_export" include (and the Eigen include) are correct to the styleguide, but possibly not the direction we want to take Drake in.  I will discuss in a different forum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2060)*

**Comment by david-german-tri** [comment]
drake005/6 have been out to lunch for 10+ hours, and are showing output from an unrelated PR.  Merging anyway.

**Pull request merged**
