### PR TITLE
Converts Acrobot to System2.0 (and adds a test)

### PR DESCRIPTION
**Pull request by RussTedrake**
+@naveenoid for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4189)

### CODE REVIEW

**Comment by naveenoid** [comment]
Finished a pass. PTAL.

---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_plant.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5iGdCpZX0UmySYlXh:-KX5iGdDJMETuekyLmy8:b6l4798) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/acrobot_plant.h#L14)):*
> ```objc
> namespace acrobot {
> 
> /// A model of a simple pendulum
> ```

This comment block should be changed to talk about the Acrobot. 

---

*[drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5jkHtOMG-cQOLM7CP:-KX5jkHtOMG-cQOLM7CQ:b-ejbq4z) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc#L14)):*
> ```cpp
> namespace {
> 
> GTEST_TEST(UrdfDynamicsTest, AllTests) {
> ```

A short description of the purpose of this test would be useful.

---

*[drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5k_ZcyNTcKb5tPJmd:-KX5k_ZcyNTcKb5tPJme:bm5tdsk) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc#L33)):*
> ```cpp
> 
>   for (int i = 0; i < 100; ++i) {
>     x = Eigen::Vector4d::Random();
> ```

BTW: I thought we decided to avoid Random inputs in unit tests since they dont allow easy debugging when errors do happen. Consider having a hard-coded set of states / inputs to run this comparison. 

---

*[drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5l-t8XArxRYBwoOuu:-KX5l-t9nOMTRiu1wz9I:b-ij8cau) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc#L47)):*
> ```cpp
>     EXPECT_TRUE(CompareMatrices(xdot_rbp->CopyToVector(),
>                                 xdot_p->CopyToVector(), 1e-8,
>                                 MatrixCompareType::absolute));
> ```

BTW: perhaps a token test on Outputs would also be useful? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-:-KX5lJUkSCzjYBY0FxhT:b-efw43w)*

**Comment by RussTedrake** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_plant.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5iGdCpZX0UmySYlXh:-KX8ZD-LxjBKcqyrCPzO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/acrobot_plant.h#L14)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> This comment block should be changed to talk about the Acrobot. 
</details>
Done.

---

*[drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5jkHtOMG-cQOLM7CP:-KX8ZT2SaK_9P0UGi_Su:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc#L14)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> A short description of the purpose of this test would be useful.
</details>
Done.

---

*[drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5k_ZcyNTcKb5tPJmd:-KX8_leWR41EnNUDjqEG:b9h7i3l) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc#L33)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: I thought we decided to avoid Random inputs in unit tests since they dont allow easy debugging when errors do happen. Consider having a hard-coded set of states / inputs to run this comparison. 
</details>
added an explicit randomization seed immediately above.  i think this is the most efficient way to generate useful inputs.

---

*[drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX5l-t8XArxRYBwoOuu:-KX8_19EJHc0bBUHuTsf:b-62hi00) ([raw file](https://github.com/robotlocomotion/drake/blob/47e74abb8df07360971e453e1e407d64ae7daffb/drake/examples/Acrobot/test/acrobot_urdf_dynamics_test.cc#L47)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: perhaps a token test on Outputs would also be useful? 
</details>
good suggestion.  done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189)*

**Comment by RussTedrake** [comment]
+@sherm1 for a late in the day platform review.

---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-:-KX8aCI6wlGIaeWtdkTf:b3uhxwz)*

**Comment by sherm1** [comment]
Platform review: a few minor comments, PTAL. Then, :lgtm:.

---

Reviewed 11 of 14 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9W6Sqtw3_vAiDsWfH:-KX9W6SrJzN9rktDJPxp:b9lkbcs) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L6)):*
> ```cpp
> 
> #include "drake/common/drake_throw.h"
> #include "drake/common/eigen_autodiff_types.h"
> ```

BTW, collect these four headers together and alphabetize.
Also, should `#include <cmath>` for sin,cos below (when T==double).

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9Wbfdm0uyolaFja60:-KX9Wbfdm0uyolaFja61:b-9ktkfu) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L40)):*
> ```cpp
>     systems::ContinuousState<T>* derivatives) const {
>   DRAKE_ASSERT_VOID(systems::System<T>::CheckValidContext(context));
> ```

For ADL safety, should add `using std::sin; using std::cos;` here.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9Wy8iCa4yDjiucyJv:-KX9Wy8iCa4yDjiucyJw:blnlq9i) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L43)):*
> ```cpp
>   const AcrobotStateVector<T>& x = dynamic_cast<const AcrobotStateVector<T>&>(
>       context.get_continuous_state_vector());
>   T tau = this->EvalVectorInput(context, 0)->GetAtIndex(0);
> ```

BTW, could make this `const T tau` (and other T-locals below).

---

*[drake/examples/Acrobot/acrobot_plant.h, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9XWbyxxSIuuxLXtWQ:-KX9XWbyxxSIuuxLXtWR:b-khm5xh) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.h#L38)):*
> ```objc
>       systems::ContinuousState<T>* derivatives) const override;
> 
>  protected:
> ```

BTW, these overrides can (and should) be private unless you want doxygen to pick them up (need doxycomments in that case), or you want them visible to further-derived classes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-:-KX9XxdYIWoTH5ayn0F_:btpv7jk)*

**Comment by naveenoid** [comment]
Reviewed 1 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9W6Sqtw3_vAiDsWfH:-KXAa852IXk---x7_jA2:b-vh2nlz) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, collect these four headers together and alphabetize.
> Also, should `#include <cmath>` for sin,cos below (when T==double).
</details>
done.  but i believe the style-guide says that the acrobot_plant.h should be the first line (and a separate group).  I actually noticed that you changed that on your realtime PR.  will comment.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9Wbfdm0uyolaFja60:-KXAaU3D26HN6fehBcYo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L40)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> For ADL safety, should add `using std::sin; using std::cos;` here.
</details>
Done.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9Wy8iCa4yDjiucyJv:-KXAadLxr77Ye4hyONqt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, could make this `const T tau` (and other T-locals below).
</details>
Done.

---

*[drake/examples/Acrobot/acrobot_plant.h, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9XWbyxxSIuuxLXtWQ:-KXAb2LC-z0rz_XC0zcu:bfyqipt) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.h#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, these overrides can (and should) be private unless you want doxygen to pick them up (need doxycomments in that case), or you want them visible to further-derived classes.
</details>
Done.  fwiw, I think the pendulum_plant class needs a round of cleanup when all is said and done.  this is not the first improvement i've done on code that descended from that source.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189)*

**Comment by naveenoid** [comment]
oops forgot :lgtm: :)

---

Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-:-KXB1Jp6xD93nUMqJyQf:bphpyfg)*

**Comment by sherm1** [comment]
*[drake/examples/Acrobot/acrobot_plant.cc, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4189#-KX9W6Sqtw3_vAiDsWfH:-KXBnRV46kTfdrKCFiPN:beuyz0g) ([raw file](https://github.com/robotlocomotion/drake/blob/ac470f710ca63a7ff72aab3ac754f9df6aedc88b/drake/examples/Acrobot/acrobot_plant.cc#L6)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> done.  but i believe the style-guide says that the acrobot_plant.h should be the first line (and a separate group).  I actually noticed that you changed that on your realtime PR.  will comment.
</details>
You're right, sorry -- I was thinking that's just for test cases but the style guide mandates it for implementation files also. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4189)*

**Pull request merged**
