### PR TITLE
Repair the assertions added in #2523.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #2531.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2532)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Repair the assertions added in \#2523\.
> 
> Fixes #2531.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2532#-:-KJqM7Ngh8Ol-hStOoG_:1417088721)*

**Comment by jwnimmer-tri** [comment]
Test build under debug, since the error doesn't show up in pre-merge jenkins:
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-clang-ninja-experimental/7/

**Comment by jwnimmer-tri** [comment]
The one-off debug jenkins build passed.  The pre-merge jenkins builds are done except for linux-matlab; the OS X error there was flake #2385.

**Comment by jwnimmer-tri** [comment]
Given that this PR doesn't touch matlab all, going to use override-merge now.

**Pull request merged**
