### PR TITLE
SceneGraph: Update doxygen block diagram

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #9496

Also, remove some stale references to LCM stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +(priority: low) +@RussTedrake for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202#-:-MqWPFzNBVtz6FUU0md0:b-53jbcg)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202#-:-MrSeDKJ6fQIVmtt4jMp:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/scene_graph.h, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16202#-MrSdmk53XUE5qGZwJKU:-MrSdmk53XUE5qGZwJKV:b2z0wq8) ([raw file](https://github.com/robotlocomotion/drake/blob/292e65321790c9734cd082bf13ea9a6c7e1903ad/geometry/scene_graph.h#L43)):*
> ```objc
> 
> The ports whose names begin with <em style="color:gray">(source name)</em>
> represent groups of ports, one for each of the registered "geometry sources".
> ```

nit: This language confused me at first (there is only only port, and it's not there is no real concept of a group of ports).  How about just saying something simpler: we have one input port for each registered geometry source.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/scene_graph.h, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16202#-MrSdmk53XUE5qGZwJKU:-MrSs0QZ32sRMrvqQS1X:bgzg4wa) ([raw file](https://github.com/robotlocomotion/drake/blob/292e65321790c9734cd082bf13ea9a6c7e1903ad/geometry/scene_graph.h#L43)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: This language confused me at first (there is only only port, and it's not there is no real concept of a group of ports).  How about just saying something simpler: we have one input port for each registered geometry source.
</blockquote></details>

I'll invoke Gould's rule: if your reviewer is confused by something, it is objectively confusing. :) Will fix.

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platfrom review, or punt to tomorrow's if you like.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202#-:-MrU4Yub9s2lTh1cWj7Y:b-x38ikv)* status: LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16202#-:-MrUGzfm3vCwCCpArZxm:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @rpoyner-tri)

**Pull request merged**
