### PR TITLE
Remove MATLAB mathematical_program_test and dead MATLAB code

### LINKED ISSUE #7482: Remove MATLAB mathematical_program_test
Basically the calling of C++ through Python through MATLAB is proving more and more troublesome and harder and harder to debug as we add more system dependencies, such as in #7323 (especially as most of the developers doing the porting do not have MATLAB licenses). It also adds an extra way that #7440 needs to be fixed and limits our ability to isolate conflicting dependencies from MATLAB if they are also used by Python. I would like to propose that we remove the test completely and concentrate efforts on the either the Protobuf way of interfacing with MATLAB or some pure C++ way of doing so.

FYI @stonier.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7482. FYI @RussTedrake @jwnimmer-tri.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8215)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[matlab/addpath_drake.m, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8215#-L6Xw69cEUuwohISeTrS:-L6Xw69cEUuwohISeTrT:bj11s6a) ([raw file](https://github.com/robotlocomotion/drake/blob/c9adb9f4603f137231f8fc1e01f4ca57664e0694/matlab/addpath_drake.m#L3)):*
> ```objc
> function [] = addpath_drake()
> 
> addpath(mfilename('fullpath'));
> ```

Is `fileparts` missing for getting the dir name?
`addpath(fileparts(mfilename('fullpath')));`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8215#-:-L6Xw_qD5Mmt3GalDPTY:bpqxd5f)*

**Comment by jamiesnape** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[matlab/addpath_drake.m, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8215#-L6Xw69cEUuwohISeTrS:-L6Xxgr-QO3JkUHfkpyL:bjcs5dc) ([raw file](https://github.com/robotlocomotion/drake/blob/c9adb9f4603f137231f8fc1e01f4ca57664e0694/matlab/addpath_drake.m#L3)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is `fileparts` missing for getting the dir name?
`addpath(fileparts(mfilename('fullpath')));`
</blockquote></details>

Indeed. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8215)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8215)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

+(status: do not merge) to wait for the mac CI.

---

Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8215#-:-L6Y-D63Z5rcTaKmh4WJ:bdqncjc)*

**Comment by jamiesnape** [comment]
Mac CI already finished and passed. The update to the PR was minor.

**Pull request merged**
