### PR TITLE
Revert "Enforces checks on HBounds' and RBounds' setters."

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Reverts RobotLocomotion/drake#7239

Dear @agalbachicar ,

The on-call build cop, @m-chaturvedi, believes that your PR 7239 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
[1](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-elcapitan-clang-bazel-continuous-everything-release/32/), [2](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-elcapitan-clang-bazel-continuous-release/35/)

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7248)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@agalbachicar , FYI, the problem is that macOS 10.11's clang compiler complains not to have `{}` in the initialization of `const T`:
```
11:03:50 drake/automotive/maliput/api/test/lane_data_test.cc:238:17: error: default initialization of an object of const type 'const drake::maliput::api::RBounds' without a user-provided default constructor
11:03:50   const RBounds dut;
11:03:50                 ^
11:03:50                    {}
11:03:50 drake/automotive/maliput/api/test/lane_data_test.cc:271:17: error: default initialization of an object of const type 'const drake::maliput::api::HBounds' without a user-provided default constructor
11:03:50   const HBounds dut;
11:03:50                 ^
11:03:50                    {}
```

I think it's better to have a quick fix than reverting the whole PR.

**Comment by agalbachicar** [comment]
@m-chaturvedi, @soonho-tri  since the necessary changes are simple, would a new PR do the trick?

**Comment by m-chaturvedi** [comment]
Yes.  You want us to create the PR?

**Comment by soonho-tri** [comment]
@agalbachicar , I think so. Please mention the original PR #7239 and this PR #7248 in the new PR.

**Comment by agalbachicar** [comment]
I'm writing it now. It will be posted in some minutes.

**Comment by agalbachicar** [comment]
@soonho-tri who should be the feature reviewer?

**Comment by soonho-tri** [comment]
I'll do the all reviews. Please trigger the failed El-Capitan builds in CI.

**Comment by soonho-tri** [comment]
Fixed by #7249 . Closing this one.

**Pull request closed without merging**
