### PR TITLE
Clean up the DiscreteValues accessors.

### LINKED ISSUE #4184: requests/questions about discrete time systems syntax
following #4183, there are a bunch of small issues/questions/requests that I have about the discrete time logic in system2.0

- [x] can we make DifferenceState -> DiscreteState everywhere?  and of course get_difference_state(), etc to get_discrete_state()? while I appreciate that modal state is also discrete in a sense, I think that the current naming is inconsistent with the continuous time versions.  I believe the context should have time, continuous state, discrete state, modal state, and parameters.  
- [x] EvalDifferenceUpdate and DoEvalDifferenceUpdate is inconsistent with EvalTimeDerivatives workflow.  i believe I should implement the EvalDifferenceUpdate method in my subclass.

why is ContinuousState a single BasicVector and DifferenceState a list of BasicVectors?
this has the following consequences:
- [ ] DifferenceState is missing get_vector() and get_mutable_vector()
- [ ] DifferenceState is missing operator[]. 
- [ ] Context is missing get_difference_state_vector() and get_mutable_difference_state_vector()

also related:
 - [x] OutputPort GetMutableData / GetMutableVectorData is inconsistent w/ get_mutable_data, etc from the state classes.

### PR DESCRIPTION
**Pull request by david-german-tri**
Remove obsolete references to "state", and add sugar for DiscreteValues with just one group.

@sherm1 for feature review.  cc @RussTedrake 

Fixes #4184.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5879)

### CODE REVIEW

**Comment by sherm1** [comment]
Nice! Lots of code shrinkage and a definite readability upgrade. Thanks for doing this, David. One BTW suggestion below, then :lgtm:.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/discrete_values.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki2CxDfh0FnUjM4PoiY:-Ki2CxDgMTtyXvlwwMqV:b-n50m7a) ([raw file](https://github.com/robotlocomotion/drake/blob/3c528e6043f658e33cd689ba2852955a8773c302/drake/systems/framework/discrete_values.h#L65)):*
> ```objc
>   /// @name Convenience accessors for DiscreteValues with just one group.
>   ///
>   // @{
> ```

BTW `//@{` to match the closing brace.

---

*[drake/systems/framework/discrete_values.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki2DHQK0a6cx2G__Ne3:-Ki2DHQK0a6cx2G__Ne4:b-mi2pa7) ([raw file](https://github.com/robotlocomotion/drake/blob/3c528e6043f658e33cd689ba2852955a8773c302/drake/systems/framework/discrete_values.h#L101)):*
> ```objc
>   }
> 
>   BasicVector<T>* get_mutable_value(int index) {
> ```

BTW Consider making these two methods overloads of `get_vector()` and `get_mutable_vector()`. That will make it more clear that these return the identical types, but the no-arg form insists there is just one group. (Or you could call the no-arg ones `get_value()` and `get_mutable_value()` for less renaming, but I like the new names better.)

---

*[drake/systems/framework/siso_vector_system.h, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki2ELcq_SaDualjONQn:-Ki2ELcq_SaDualjONQo:b-bnit66) ([raw file](https://github.com/robotlocomotion/drake/blob/3c528e6043f658e33cd689ba2852955a8773c302/drake/systems/framework/siso_vector_system.h#L141)):*
> ```objc
>     DRAKE_ASSERT(discrete_state != nullptr);
>     BasicVector<T>* const discrete_update_vector =
>         discrete_state->get_mutable_value(0);
> ```

BTW safe to use the new one-group method here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-:-Ki2FMOC4JLIHZh9A0oS:b-yyt9y3)*

**Comment by david-german-tri** [comment]
+@ggould-tri for platform review

---

Review status: 6 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/discrete_values.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki2CxDfh0FnUjM4PoiY:-Ki5jyNdYGYz0KpOMvZo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c528e6043f658e33cd689ba2852955a8773c302/drake/systems/framework/discrete_values.h#L65)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `//@{` to match the closing brace.
</blockquote></details>

Done.

---

*[drake/systems/framework/discrete_values.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki2DHQK0a6cx2G__Ne3:-Ki5lQ3WUf87VZwXUto1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c528e6043f658e33cd689ba2852955a8773c302/drake/systems/framework/discrete_values.h#L101)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Consider making these two methods overloads of `get_vector()` and `get_mutable_vector()`. That will make it more clear that these return the identical types, but the no-arg form insists there is just one group. (Or you could call the no-arg ones `get_value()` and `get_mutable_value()` for less renaming, but I like the new names better.)
</blockquote></details>

Done.

---

*[drake/systems/framework/siso_vector_system.h, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki2ELcq_SaDualjONQn:-Ki5lP-v5XL83ApGIBJr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c528e6043f658e33cd689ba2852955a8773c302/drake/systems/framework/siso_vector_system.h#L141)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW safe to use the new one-group method here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-:-Ki60yIrvn2tASmRu8MF:b-gbk9vg)*

**Comment by sherm1** [comment]
Reviewed 21 of 21 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5879)*

**Comment by ggould-tri** [comment]
:lgtm: pending one nit below.  This is awesome!

---

Reviewed 6 of 27 files at r1, 21 of 21 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/discrete_values.h, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki67RIienPjEL4_FEwD:-Ki67RIjygFsDfucGrgg:b-30wxrc) ([raw file](https://github.com/robotlocomotion/drake/blob/faa6e0f2d0c5429e3f1897bfe0a7d01bd1e68b14/drake/systems/framework/discrete_values.h#L36)):*
> ```objc
>   DiscreteValues() {}
> 
>   /// Constructs a discrete values that does not own the underlying @p data.
> ```

Here and below, the singular/plural agreement is bogus ("a values", "the values had... its").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-:-Ki68VX-04HBzcEkOGhF:bugf4ug)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/discrete_values.h, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5879#-Ki67RIienPjEL4_FEwD:-Ki69Ybi5No__rUqiJab:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/faa6e0f2d0c5429e3f1897bfe0a7d01bd1e68b14/drake/systems/framework/discrete_values.h#L36)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Here and below, the singular/plural agreement is bogus ("a values", "the values had... its").
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5879)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5879)*

**Pull request merged**
