### PR TITLE
Set WITH_DREAL to OFF by default

### LINKED ISSUE #3505: Consider not building dReal by default (i.e., setting WITH_DREAL to false by default)
This is just a suggestion, feel free to share your thoughts. 

My main reason for suggesting this is that building dReal adds quite a bit to build time, while only a small (albeit hopefully growing) subset of users will use its functionality. Of course, there would still be CI builds that include dReal, to make sure there's no bit rot. Perhaps another option would be to get dReal from a precompiled tarball.

cc: @soonho-tri as the main stakeholder, what do you think?

### PR DESCRIPTION
**Pull request by soonho-tri**
It will be back to ON when the integration is done.

Close #3505

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3522)

### CODE REVIEW

**Comment by tkoolen** [comment]
Thanks! :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3522#-:-KS7COrS37PORhon8zgb:b6duv8n)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
@soonho-tri You need to solicit platform review, it doesn't happen automatically.

**Comment by soonho-tri** [comment]
@david-german-tri , could you do the platform review on this PR?

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3522#-:-KSgc98IjWi4T3tVykHD:bnfp4nl)*

**Pull request merged**
