### PR TITLE
Removes village and merging demos from README and BUILD since they are not in automotive_demo.cc.

### PR DESCRIPTION
**Pull request by liangfok**
I believe this is now necessary post #5235.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5240)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

\cc: @maddog-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5240#-:-KdVTC1H-e0vFKPIz8Rm:bjih38v)*

**Comment by jwnimmer-tri** [comment]
Please explain more about this?  They still run just fine.

**Comment by liangfok** [comment]
Sorry I was confused. To avoid future confusion, maybe we should instead remove the following code from `automotive_demo.py` and replace it with an explicit flag? Otherwise, the user may not know which executable is being executed.

```
   # TODO(jwnimmer-tri) Remove this magic once dev_demo is gone.
    if '-road_path' in tail:
        demo_path = "drake/automotive/dev_demo"
```

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5240#-:-KdVV-bnStfQVyTYd1Eg:bolqekp)*

**Comment by jwnimmer-tri** [comment]
If you want to PR that (something like `--demo=path=$(location :dev_demo)` in `BUILD`, I guess?) that's fine by me, but at this point about 50% of the folks who we need to know have become aware via this PR.  Remember that code is dying ASAP.

**Comment by liangfok** [comment]
Alright, since the code is dying and just about everyone knows what's going on, I'll leave it as is. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5240#-:-KdVYYPgv_J8P3bBh_G9:b-2eox5l)*

**Pull request closed without merging**
