### PR TITLE
[tools] Add test to flag hazardous exported symbols

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

___
*[`tools/install/libdrake/test/exported_symbols_test.py` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20279#-NfqqZw_1Rd9JQgWdvgS:-NfqqZwa5YVsRGK_kupQ:b-ffpfni) ([raw file](https://github.com/RobotLocomotion/drake/blob/88ef4f1e93693654cd1e5c6158fc84ddf1956ac6/tools/install/libdrake/test/exported_symbols_test.py#L7)):*
> ```Python
> import unittest
> 
> # Any symbols whose name starts with one of these strings are okay.
> ```

nit Might be worth documenting why we include/exclude symbols by mangled match, rather than demangled match.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279#-:-Nfr0QWQ3FXtCNkC_0S6:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.  (Waiting until Thursday is fine.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279#-:-NfrBQQs3ZlJeSy2yjK5:bz42ul3)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20279#-:-Nfvxxlr0gAe_EwzrbRd:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
