### PR TITLE
Advance fcl for new box-sphere contact results

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This picks up the new changes to improve sphere-box collision results.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9202)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
For all changes to `workspace` externals, remember to launch a macOS build on Sierra and High Sierra.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm: for both reviews, once CI has passed.

**Comment by SeanCurtis-TRI** [comment]
Thanks for the mac reminders.

**Pull request merged**
