### PR TITLE
Add pandas as a source dependency

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Bionic: https://pandas.pydata.org/pandas-docs/stable/install.html#installing-using-your-linux-distribution-s-package-manager

OSX: https://pandas.pydata.org/pandas-docs/stable/install.html#installing-from-pypi

We want it for #12040

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12328)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Why is this a runtime (installed) dependency, and not just a build-time dependency?

**Comment by m-chaturvedi** [comment]
That was a mistake.  Thanks!

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by m-chaturvedi** [comment]
@EricCousineau-TRI for feature review, please.

**Pull request merged**
