### PR TITLE
Restore PlaybackTrajectory() for state trajectories.

### LINKED ISSUE #8697: DrakeVisualizer::PlaybackTrajectory() broken for state trajectory input
#8683 exposed a hole in our test coverage for `DrakeVisualizer`. I'll submit a fix for this shortly.

### PR DESCRIPTION
**Pull request by avalenzu**
Adds a change that was inadvertently ommitted in #8683. Also adds a unit
test that would have caught #8697. Fixes #8697.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8698)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@jwnimmer-tri for feature review.
+@soonho-tri  for platform review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8698#-:-LB3OOjKEt6FNE80k1zD:b-pmcsun)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8698#-:-LB5ydzfD5bfRqekXdVR:bnfp4nl)*

**Comment by avalenzu** [comment]
-@soonho-tri +@sammy-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8698#-:-LB6K-0b7RzYUaCYiHDT:b-574lvq)*

**Comment by avalenzu** [comment]
-@sammy-tri +@soonho-tri  for platform review. (Sorry for the churn)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8698#-:-LB6KNcU3_2RBJyR3Hhd:b-2csw32)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8698#-:-LB6JwSaAcKeW2I1ghLl:bnfp4nl)*

**Pull request merged**
