### PR TITLE
Fix error warnings

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Refactor and fix error/warning flags so as to not break the build for users (e.g. me) with additional warnings turned on (e.g. `-Wsign-conversion`), and to have less duplication between GCC and Clang. Also, fix `-Wreorder` violations (#2372).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2441) &emsp; Multiple assignees:&emsp;@jonathan-owens&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jonathan-owens">jonathan-owens</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Yup, sorry I didn't know about `-Werror=all` when I added `-Werror`, but I quickly learned.  Note that my pending fixup for that (#2437) is likely to cause a conflict here.

**Comment by jonathan-owens** [comment]
@mwoehlke-kitware LGTM

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware I am going to assume you'd like a "platform review" and merge of this PR, even though that hasn't been mentioned yet.  I will take a look today or early tomorrow and post here when done.  If you'd rather I not review, that's fine too, just let me know.

+@jwnimmer-tri tentatively for platform review

<details><summary><i>Previously, jonathan-owens (Jonathan Owens) wrote…</i></summary>
> @mwoehlke-kitware LGTM
</details>


---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-:-KIdP-seRZyuMicHAmiN:61799188)*

**Comment by mwoehlke-kitware** [comment]
> @mwoehlke-kitware I am going to assume you'd like a "platform review" and merge of this PR

Yes, thanks... sorry for not being on the ball procedurally; been poking at the long-suffering FCL branch.

**Comment by sherm1** [comment]
> been poking at the long-suffering FCL branch.

Your FCL sacrifice is much appreciated, Matthew!

**Comment by jwnimmer-tri** [comment]
No problem.

(And wow, some of those initializer lists are challenging.  It took me a good bit of squinting to convince myself that members are being set correctly prior to their potential use later in the list.)

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> > been poking at the long-suffering FCL branch.
> 
> 
> 
> Your FCL sacrifice is much appreciated, Matthew!
</details>


---

Reviewed 10 of 11 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 71 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdTmSJtUCIdoOec-pU:-KIdTmSKSLhMs4KIxAd3:324927701) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L71)):*
> ```CMake
> 
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=all")
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=uninitialized")
> ```

On both GCC and Clang, I believe that -Wuninitialized is implied by -Wall.  If so, why list it here explicitly?

---

*[drake/CMakeLists.txt, line 75 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdU1vPZou8XFZ9tMd4:-KIdU1vQObwH9wB9GC8M:-1328411928) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L75)):*
> ```CMake
>   # TODO(#2372) These are warnings that we can't handle yet.
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-sign-compare")
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-local-typedefs")
> ```

BTW GCC nominally spells this `unused-local-typedefs` and Clang nominally spells this `unused-local-typedef`.  With this PR, we're using the GCC spelling for both compilers.  Jenkins seems to be happy with that, so I guess it doesn't matter.  If we end up caring, perhaps we'll just fix the warnings so we don't have to suppress it anymore :smile:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-:-KIdQWEmRL0run6MwQk4:-2127226839)*

**Comment by mwoehlke-kitware** [comment]
Heh. I didn't pay attention, I just blindly reordered them to match execution order. If that resulted in fishy constructs, well, that's why `-Wreorder` exists in the first place :wink:. Seems like a good argument to have it turned on...

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> No problem.
> 
> (And wow, some of those initializer lists are challenging.  It took me a good bit of squinting to convince myself that members are being set correctly prior to their potential use later in the list.)
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 71 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdTmSJtUCIdoOec-pU:-KIhVoH0w3yRfStKOExc:-546854958) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> On both GCC and Clang, I believe that -Wuninitialized is implied by -Wall.  If so, why list it here explicitly?
</details>
Are you sure? Usually, the documentation states if a warning is included with `-Wall`. I didn't see that (GCC) for `-Wuninitialized`, so I left it in. At worst, it's superfluous :smile:.

---

*[drake/CMakeLists.txt, line 75 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdU1vPZou8XFZ9tMd4:-KIhWEnUpcDI3WWhGQ-u:1669526979) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW GCC nominally spells this `unused-local-typedefs` and Clang nominally spells this `unused-local-typedef`.  With this PR, we're using the GCC spelling for both compilers.  Jenkins seems to be happy with that, so I guess it doesn't matter.  If we end up caring, perhaps we'll just fix the warnings so we don't have to suppress it anymore :smile:.
</details>
Sounds good... I could fix it, but I see you already have a PR to deal with it, which is probably better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-:-KIhWLyJMsu6L88_xvn5:1615728470)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 71 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdTmSJtUCIdoOec-pU:-KIha46nunW4bd3CB1HU:571769259) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L71)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Are you sure? Usually, the documentation states if a warning is included with `-Wall`. I didn't see that (GCC) for `-Wuninitialized`, so I left it in. At worst, it's superfluous :smile:.
</details>
https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/Warning-Options.html#index-Wall-282

The Wall docs say Wuninitilized is included.  (But you're right, oddly the Wuninitialized doesn't cite Wall like they usually do.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441)*

**Comment by mwoehlke-kitware** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CMakeLists.txt, line 71 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdTmSJtUCIdoOec-pU:-KIiIU7rU6JewF9dXAwp:-1778786046) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/Warning-Options.html#index-Wall-282
> 
> The Wall docs say Wuninitilized is included.  (But you're right, oddly the Wuninitialized doesn't cite Wall like they usually do.)
</details>
I verified with a simple test program. The latest version removes it also (as a result, only `-W[error=]all` is being added; the other flags are all disabling warnings).

Actually... the intent is to (eventually) fix the various currently-disabled warnings? Should they be *only* demoted from errors (`-Wno-error=...`) rather than disabled entirely?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/CMakeLists.txt, line 71 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-KIdTmSJtUCIdoOec-pU:-KIiL6nAYBjy30svGqWf:-1870689267) ([raw file](https://github.com/robotlocomotion/drake/blob/565557d77d191ff2e527b94152276239b2aae657/drake/CMakeLists.txt#L71)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I verified with a simple test program. The latest version removes it also (as a result, only `-W[error=]all` is being added; the other flags are all disabling warnings).
> 
> Actually... the intent is to (eventually) fix the various currently-disabled warnings? Should they be *only* demoted from errors (`-Wno-error=...`) rather than disabled entirely?
</details>
Yes, my (and others') intent is to fix these warnings.

On the question of demoted vs disabled -- personally, I think warnings that aren't errors are completely pointless and should never be turned on.  However, with my platform reviewer hat on, I'd certainly sign off on PRs that add demoted warnings while we're in the process of fixing them.

But this PR is fine as-is, so I'll plan to merge it once jenkins finishes enough of the builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Heh. I didn't pay attention, I just blindly reordered them to match execution order. If that resulted in fishy constructs, well, that's why `-Wreorder` exists in the first place :wink:. Seems like a good argument to have it turned on...
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2441#-:-KIiPrrA4VGSNvNhrP0S:1417088721)*

**Comment by jwnimmer-tri** [comment]
Using override-merge to get around:
- jenkins not done (still waiting on 64 ninjas)
- out-of-odate-with-master

**Pull request merged**
