### PR TITLE
[parsing] Implements basic material and mesh support in MuJoCo parser

### PR DESCRIPTION
**Pull request by RussTedrake**
This contains #18312 as its first commit.
- All files under `drake/geometry` belong to #18312 
- All files under `drake/multibody` belong solely to this PR and need review.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for expedited platform review.

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGqzJZU1nTZ76IbuKpf:b393upz)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 603 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGqx5S51cLWUqh2cwRE:-NGqx5S51cLWUqh2cwRF:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/928ea55f875e9cf7b64a4fab5104e1dd696ffc4b/multibody/parsing/detail_mujoco_parser.cc#L603)):*
> ```cpp
>       }
>     }
>     // rgba takes precidence over materials, so must be parsed after.
> ```

typo



_Suggestion:_
```cpp
precedence
```
___
*[`multibody/parsing/test/detail_mujoco_parser_test.cc` line 603 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGqwF7j3LmqC1TPESXi:-NGqwF7j3LmqC1TPESXj:b-m0updy) ([raw file](https://github.com/robotlocomotion/drake/blob/928ea55f875e9cf7b64a4fab5104e1dd696ffc4b/multibody/parsing/test/detail_mujoco_parser_test.cc#L603)):*
> ```cpp
>   };
> 
>   auto CheckBodySpatial = [&plant, &context](
> ```

nit This PR didn't start the fire, but this lambda variable name runs against the majority of lambda names in Drake, which follow https://drake.mit.edu/styleguide/cppguide.html#Variable_Names.

Feel free to punt if need be.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: small stuff. I did not work through the math or compare to mujoco documentation.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGr16DW6voHPYlE3aOn:b-p67rxw)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) -(component: multibody parsing) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGrHh_f4pglGE7YHW8t:b-p0cchx)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
> @rpoyner-tri for expedited platform review.

Did you mean to say "feature review" instead of "platform review", perhaps?  It's fine either way, but it seemed like it might be a typo.

**Review by rpoyner-tri — COMMENTED** [review]
I meant to say platform review, at Russ' request. He requested @joemasterjohn for feature review, but I suspect there are others who could also do it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGsaSQBCeAiIqcDUcUn:b-u3z0sh)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
FYI -- #18312 has landed and I've rebased this branch.  I'm still trying to recruit a feature reviewer. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGv_gR20dkbhsNWKAyp:bdsuibu)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 
Not an expert on mujoco file formats, but I looked at this pretty closely, so hopefully this is a good enough review. Do feel free to get a second opinion though,

> Reviewed 2 of 4 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGwUE0AAckAa6hkH-zk:b9dj903)* status: 7 unresolved discussions (waiting on @RussTedrake)

___
*[`multibody/parsing/BUILD.bazel` line 184 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwFke3-k8fYbUOZfsY:-NGwFke3-k8fYbUOZfsZ:byum0hq) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/BUILD.bazel#L184)):*
> ```Starlark
>         ":detail_parsing_workspace",
>         ":scoped_names",
>         "//geometry:drake_visualizer",
> ```

nit needed?
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 546 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwL5LQ7SfGaewny07w:-NGwL5LQ7SfGaewny07x:b-tdhom9) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L546)):*
> ```cpp
>           // the vertices".
>           const geometry::TriangleSurfaceMesh<double>& surface_mesh =
>               surface_mesh_.at(mesh);
> ```

nit, can it be that `surface_mesh_.find(mesh) == surface_mesh_.end()`? If it's an invariant that `mesh_` and `surface_mesh_` always come in pairs, we should probably make that more explicit.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 561 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwN2uj81tIqYlJUv9k:-NGwN2uj81tIqYlJUv9l:bfa5f0m) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L561)):*
> ```cpp
>         }
>       } else {
>         log()->warn("geom {} specified unknown mesh {} and will be ignored",
> ```

BTW question, why do we not use the `DiagnosticPolicy` structure that we use for other parsers?
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 574 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwLvYv7ofT54guyEbM:-NGwLvYv7ofT54guyEbN:b2xublo) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L574)):*
> ```cpp
>     }
> 
>     if (type != "mesh") {
> ```

BTW, I'm confused by this predicate. How could this ever be false? We already processed mesh before.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 643 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwKv2l-CPF27EpkNge:-NGwKv2m1CHEizdh4mj5:b-gh0aol) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L643)):*
> ```cpp
>         if (type == "mesh") {
>           mass = density *
>                  geometry::internal::CalcEnclosedVolume(surface_mesh_.at(mesh));
> ```

nit, can it be that `surface_mesh_.find(mesh) == surface_mesh_.end()`?
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 942 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwO2ZO5t2PoK0aagUm:-NGwO2ZO5t2PoK0aagUn:bkoz169) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L942)):*
> ```cpp
>               "load {}, but that file does not exist. If you have "
>               "built Drake from source, running\n\n bazel run "
>               "//manipulation/utils/stl2obj -- {} {}\n\nonce will resolve "
> ```

nit this warn message is a bit misleading if the file extension neither obj or stl.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1063 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwQJq5D4Y1o1ofTie_:-NGwQJq5D4Y1o1ofTiea:bvl6eth) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L1063)):*
> ```cpp
>                            const std::optional<std::string>& parent_model_name,
>                            XMLDocument* xml_doc,
>                            const std::filesystem::path& path) {
> ```

The lack of documentation here and about `main_mjcf_path_` left me wondering what `path` is this. Is this the path for a particular model asset or is this the path to the spec being parse?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317)* status: 6 unresolved discussions (waiting on @RussTedrake)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 561 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwN2uj81tIqYlJUv9k:-NGx8BmQBgHC2EcNIyLN:bo5vnov) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L561)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW question, why do we not use the `DiagnosticPolicy` structure that we use for other parsers?
</blockquote></details>

It's a known deficit; I will get around to the policy port soon.

**Review by RussTedrake — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317#-:-NGyAnCM3CTNWuuBkTWU:b-9755fn)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 546 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwL5LQ7SfGaewny07w:-NGxy9ji-W4VNsyhH_10:b-c0y5ae) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L546)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, can it be that `surface_mesh_.find(mesh) == surface_mesh_.end()`? If it's an invariant that `mesh_` and `surface_mesh_` always come in pairs, we should probably make that more explicit.
</blockquote></details>

Added at least an assert.  Things might be more interesting if/when we support vtk (might have a surface mesh or a volume mesh).
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 574 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwLvYv7ofT54guyEbM:-NGxyM0y3e94ThFv_j81:bva3spu) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L574)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm confused by this predicate. How could this ever be false? We already processed mesh before.
</blockquote></details>

I mentioned this on slack also included the relevant doc below.  It's possible to say `<geom type="box" mesh="mymesh"/>`, which would say "fit a box to the  mesh mymesh".
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 643 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwKv2l-CPF27EpkNge:-NGxzOp29zugPd7SzDaV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L643)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, can it be that `surface_mesh_.find(mesh) == surface_mesh_.end()`?
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 942 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwO2ZO5t2PoK0aagUm:-NGy7QJMBF30vOiwUNUI:b-bwgo0s) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L942)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit this warn message is a bit misleading if the file extension neither obj or stl.
</blockquote></details>

Done. Made it stl specific.



_Code quote:_
```cpp
              "load {}, but that file does not exist. If you have "
              "built Drake from source, running\n\n bazel run "
              "//manipulation/utils/stl2obj -- {} {}\n\nonce will resolve "
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1063 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwQJq5D4Y1o1ofTie_:-NGy8Gnj2vo2oDaFheGl:b-v8jgtf) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L1063)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The lack of documentation here and about `main_mjcf_path_` left me wondering what `path` is this. Is this the path for a particular model asset or is this the path to the spec being parse?
</blockquote></details>

Done. Added a doc string.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18317)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @RussTedrake)

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 574 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18317#-NGwLvYv7ofT54guyEbM:-NGyF7L11IgMZcTJtwxX:b-kufkxf) ([raw file](https://github.com/robotlocomotion/drake/blob/841a2707adc5b0a0a4073a156797836452a28e66/multibody/parsing/detail_mujoco_parser.cc#L574)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I mentioned this on slack also included the relevant doc below.  It's possible to say `<geom type="box" mesh="mymesh"/>`, which would say "fit a box to the  mesh mymesh".
</blockquote></details>

I see, thanks!

**Pull request merged**
