### PR TITLE
Revert "Add caching to MultibodyTree"

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Reverts RobotLocomotion/drake#9489
Dear @sherm1,

The on-call build cop, @rpoyner-tri , believes that your PR #9489 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan-everything/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9561)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
attempted to launch build https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-xenial-clang-bazel-experimental-memcheck-ubsan/47/ -- it is pending in jenkins

**Comment by sherm1** [comment]
I see the problem ... working on a fix asap.

**Comment by sherm1** [comment]
Rico, PR #9562 should fix this and allow moving forward. Can we try that before reverting?
I'm headed for the airport right now so will be offline for a few hours -- please merge 9562 if CI is green.

**Comment by rpoyner-tri** [comment]
Fix-forward of a nightly breakage works for me.

**Pull request closed without merging**
