### PR TITLE
Scs sdp solver

### PR DESCRIPTION
**Pull request by hongkai-dai**
Enable SCS to solve semidefinite programming problem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7555)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-:-L-XS5A9QmQZoDgfnDTF:bll7v0f)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-:-L023ouAyF75uQJ2_Clx:b-t8d7jl)*

**Comment by avalenzu** [comment]
:lgtm: +@sherm1 for platform review.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[solvers/scs_solver.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0Pq1NXrDbmwbNOoLWY:-L0Pq1NXrDbmwbNOoLWZ:bkua80x) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/scs_solver.cc#L356)):*
> ```cpp
>     // [-√2 -√2  -1 ... -√2]
>     // [    ...            ]
>     // [-√2 -√2 -√2 ...  -1]
> ```

BTW Might I suggest the following unicode alternative? Github/Reviewable add extra space between lines - in an editor the brackets are continuous.

     // ⎡ -1 -√2 -√2 ... -√2⎤
     // ⎢-√2  -1 -√2 ... -√2⎥
     // ⎢-√2 -√2  -1 ... -√2⎥
     // ⎢    ...            ⎥
     // ⎣-√2 -√2 -√2 ...  -1⎦

---

*[solvers/scs_solver.cc, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0PvQIQy7_fgPUAGGlH:-L0PvQIQy7_fgPUAGGlI:b-lbrw4u) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/scs_solver.cc#L401)):*
> ```cpp
>     //              ...
>     //          [  F₀(m, m)]
>     // x = [x₁; x₂; ... ; xₙ]
> ```

  BTW These comments are so great I can't resist making them prettier:

    // where
    //              ⎡  F₁(0, 0)   F₂(0, 0) ...   Fₙ(0, 0)⎤
    //              ⎢√2F₁(1, 0) √2F₂(1, 0) ... √2Fₙ(1, 0)⎥
    //   A_cone = - ⎢√2F₁(2, 0) √2F₂(2, 0) ... √2Fₙ(2, 0)⎥,
    //              ⎢            ...                     ⎥
    //              ⎣  F₁(m, m)   F₂(m, m) ...   Fₙ(m, m)⎦
    //
    //              ⎡  F₀(0, 0)⎤
    //              ⎢√2F₀(1, 0)⎥
    //   b_cone =   ⎢√2F₀(2, 0)⎥,
    //              ⎢   ...    ⎥
    //              ⎣  F₀(m, m)⎦
    // and
    //   x = [x₁; x₂; ... ; xₙ].

---

*[solvers/test/semidefinite_program_examples.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0Q-rxkGFzQKERpQ9u3:-L0Q-rxkGFzQKERpQ9u4:bvun3k9) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/test/semidefinite_program_examples.h#L47)):*
> ```objc
>  *     [si*biᵀ - cᵀ      1 - si]
>  *     P is p.s.d
>  */
> ```

BTW Slight re-wording plus unicode prettiness:
 
   /*
     * Given some ellipsoids ℰᵢ : xᵀQᵢx + 2 bᵢᵀx ≤ 1, i = 1, 2, ..., n, find an
     * ellipsoid xᵀPx + 2cᵀx ≤ 1 as an outer approximation for the union of
     * ellipsoids ℰᵢ.
     *
     * Using s-lemma, the ellipsoid xᵀPx + 2cᵀx ≤ 1 contains the ellipsoid ℰᵢ, 
     * if and only if there exists a scalar sᵢ ≥ 0 such that 
     *
     *   (1 - xᵀPx - cᵀx) - sᵢ(1 - xᵀQᵢx - bᵢᵀx) ≥ 0 ∀x.
     *
     * This is equivalent to requiring that the matrix
     *
     *   ⎡ sᵢQᵢ - P     sᵢbᵢ - c⎤
     *   ⎣sᵢbᵢᵀ - cᵀ      1 - sᵢ⎦
     *
     * is positive semidefinite.
     *
     * In order to find a tight outer approximation, we choose to minimize the
     * trace of P. The optimiation problem becomes
     *
     *   min_{P, c, si} -trace(P)
     *   s.t ⎡ sᵢQᵢ - P     sᵢbᵢ - c⎤ is p.s.d
     *       ⎣sᵢbᵢᵀ - cᵀ      1 - sᵢ⎦
     *       P is p.s.d
     */

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-:-L0Q0RLKjHvVUwCYQnSs:bol08qe)*

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by sherm1** [comment]
Platform :lgtm: with a minor BTW and pending CI (I restarted the one failed run). Love the fancy Unicode comments!

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/scs_solver.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0Pq1NXrDbmwbNOoLWY:-L0QAfCZIGVD8AD-GcVz:bmugehw) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/scs_solver.cc#L356)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW Might I suggest the following unicode alternative? Github/Reviewable add extra space between lines - in an editor the brackets are continuous.

     // ⎡ -1 -√2 -√2 ... -√2⎤
     // ⎢-√2  -1 -√2 ... -√2⎥
     // ⎢-√2 -√2  -1 ... -√2⎥
     // ⎢    ...            ⎥
     // ⎣-√2 -√2 -√2 ...  -1⎦

</blockquote></details>

BTW nice!

---

*[solvers/test/semidefinite_program_examples.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0Q-rxkGFzQKERpQ9u3:-L0Q87VJ_Ni44ywAkBJu:b-zm2ur) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/test/semidefinite_program_examples.h#L47)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW Slight re-wording plus unicode prettiness:
 
   /*
     * Given some ellipsoids ℰᵢ : xᵀQᵢx + 2 bᵢᵀx ≤ 1, i = 1, 2, ..., n, find an
     * ellipsoid xᵀPx + 2cᵀx ≤ 1 as an outer approximation for the union of
     * ellipsoids ℰᵢ.
     *
     * Using s-lemma, the ellipsoid xᵀPx + 2cᵀx ≤ 1 contains the ellipsoid ℰᵢ, 
     * if and only if there exists a scalar sᵢ ≥ 0 such that 
     *
     *   (1 - xᵀPx - cᵀx) - sᵢ(1 - xᵀQᵢx - bᵢᵀx) ≥ 0 ∀x.
     *
     * This is equivalent to requiring that the matrix
     *
     *   ⎡ sᵢQᵢ - P     sᵢbᵢ - c⎤
     *   ⎣sᵢbᵢᵀ - cᵀ      1 - sᵢ⎦
     *
     * is positive semidefinite.
     *
     * In order to find a tight outer approximation, we choose to minimize the
     * trace of P. The optimiation problem becomes
     *
     *   min_{P, c, si} -trace(P)
     *   s.t ⎡ sᵢQᵢ - P     sᵢbᵢ - c⎤ is p.s.d
     *       ⎣sᵢbᵢᵀ - cᵀ      1 - sᵢ⎦
     *       P is p.s.d
     */


</blockquote></details>

BTW minimizing -trace() looks like maximizing trace() to this naive reviewer. Please clarify why this is right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-:-L0QEC91fSdnETvu-qQe:bglu6jo)*

**Comment by hongkai-dai** [comment]
Thank @avalenzu and @sherm1 for the review! Sorry I was attending the conference and also travelling around these days, so my reply is delayed.

---

Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/scs_solver.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0Pq1NXrDbmwbNOoLWY:-L0g1rZMwK6dyPO0yEdp:b-4safkc) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/scs_solver.cc#L356)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW nice!
</blockquote></details>

Wow, this is great, thanks @avalenzu 

---

*[solvers/scs_solver.cc, line 401 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0PvQIQy7_fgPUAGGlH:-L0g2DoeRsUt9R7t0pf8:b4li4rz) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/scs_solver.cc#L401)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

  BTW These comments are so great I can't resist making them prettier:

    // where
    //              ⎡  F₁(0, 0)   F₂(0, 0) ...   Fₙ(0, 0)⎤
    //              ⎢√2F₁(1, 0) √2F₂(1, 0) ... √2Fₙ(1, 0)⎥
    //   A_cone = - ⎢√2F₁(2, 0) √2F₂(2, 0) ... √2Fₙ(2, 0)⎥,
    //              ⎢            ...                     ⎥
    //              ⎣  F₁(m, m)   F₂(m, m) ...   Fₙ(m, m)⎦
    //
    //              ⎡  F₀(0, 0)⎤
    //              ⎢√2F₀(1, 0)⎥
    //   b_cone =   ⎢√2F₀(2, 0)⎥,
    //              ⎢   ...    ⎥
    //              ⎣  F₀(m, m)⎦
    // and
    //   x = [x₁; x₂; ... ; xₙ].

</blockquote></details>

Done. Thanks! Love these continuous brackets!

---

*[solvers/test/semidefinite_program_examples.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-L0Q-rxkGFzQKERpQ9u3:-L0g2zCld3ools9x_u8A:b-xdzbuo) ([raw file](https://github.com/robotlocomotion/drake/blob/51d1a165973436413c5162954bb9784e79f869bc/solvers/test/semidefinite_program_examples.h#L47)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW minimizing -trace() looks like maximizing trace() to this naive reviewer. Please clarify why this is right.
</blockquote></details>

Thanks @avalenzu . @sherm1 you are exactly right, it should be maximizing trace() instead of minimizing, I changed it in the updated documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7555#-:-L0g3MqfiDg36OzTRlEf:b-hp8mfe)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7555)*

**Pull request merged**
