### PR TITLE
Adding Deps for libdrake.so

### PR DESCRIPTION
**Pull request by m-chaturvedi**
The added libraries are the sorted output of:
`bazel query 'kind("cc_library", visible("//drake:libdrake.so", "//drake/..."))
except("//drake/examples/...")
except(attr("testonly", "1", "//drake/..."))'`

To check the necessary condition, I successfully ran `bazel run install <PATH>` on my machine.

This is a diff (rev 1 and rev 2 ) to indicate what all this query removed: 
https://gist.github.com/m-chaturvedi/78660c80e7dba24846128aa86a126862/revisions

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6452)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-:-KnjgAdC-OckHibDVsEd:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by m-chaturvedi** [comment]
@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
+@jwnimmer-tri to get some bazel expertise eyeballs on this.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-:-KnjwuF7A8pxF61RYYFt:b65e7m7)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.  I have one question open in #dynamics slack before I LGTM.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-KnkBkQ12IMxTwutciAu:-KnkBkQ12IMxTwutciAv:bzih7h3) (no related file):*
FYI Here's some nice-to-haves that don't need to block this PR:
- When e.g. `//drake/systems/framework:framework` exists (as a rollup of everything in the folder), we should only list that, instead of writing out every individual component.
- We should add more folder rollup libraries (possibly some of them should only be visible to this install target), so that more folders use the above simplification.
- We should make the "update to a new list of exported targets" more automated, such as relocating the "here's the `bazel query()` you should run" code from a comment into a script that emits a `.bzl` file that gets `load()`ed here.  (Writing it in python would allow us to easily capture our heuristics like the folder-rollup suggestions above, or other exceptional cases.)  A regression test could confirm that the script's output matched the checked-in version.
- We should install `drake/thirdParty` libraries via `WORKSPACE` not here.

---

*[drake/BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-Knk9vOgzaLVh1ZJ5Iz6:-Knk9vOgzaLVh1ZJ5Iz7:b36olne) ([raw file](https://github.com/robotlocomotion/drake/blob/add9fb27995b9a15ed5b769d956a2012c10f765a/drake/BUILD#L11)):*
> ```Python
> # This list is obviously incomplete.
> # TODO(david-german-tri, jamiesnape): Add everything Director needs, and
> # eventually everything any consumer of Drake would need.
> ```

I think the prior three lines are wrong now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-:-KnkEs9fjP7Lv36vtaaW:b1wxbsw)*

**Comment by sherm1** [comment]
Responded in Slack -- tl;dr: multibody/benchmarks should be installed. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-:-KnkHO1Cy2XO1jayZVW3:b88z36f)*

**Comment by m-chaturvedi** [comment]
*[drake/BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-Knk9vOgzaLVh1ZJ5Iz6:-Knk_e9VshQHy0ywlhyu:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/add9fb27995b9a15ed5b769d956a2012c10f765a/drake/BUILD#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the prior three lines are wrong now?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6452)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6452#-:-Knk_u3Ac_VRBh40bCS0:bnfp4nl)*

**Pull request merged**
