### PR TITLE
[Bazel] Use pkg-config to find glib, instead of hard-coding a path.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This seems like the easiest way to support Ubuntu and OSX from the same WORKSPACE.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4300)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri and +@david-german-tri for review, please.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4300#-:-KXm0sNDrjuvQI4T6VNa:bnfp4nl)*

**Comment by david-german-tri** [comment]
Works for me on Trusty and OS X.  Didn't review the vendored stuff.  Here's hoping it moves into Bazel proper at some point in the future.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4300#-:-KXmJclgFGCLeg3ELoBS:bnn8nkf)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4300#-:-KXmJiPb-OH5mri3uMg7:bnfp4nl)*

**Comment by david-german-tri** [comment]
merging despite cpplint

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4300#-:-KXmJkaD4OBWEnH2FWzt:bcwuwdu)*

**Pull request merged**
