### PR TITLE
Add demo program for hardware simulation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We'll also want to have a Python version of this program in the future, but for now we'll stick with C++ since that's what we have in Anzu (and so, the code will be easier to move).

Towards #17112.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.
+@rpoyner-tri for platform review, please.

\CC @zachfang @sammy-tri FYI

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a typo and some bigger picture questions.

> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615#-:-N7qT67fDACsMk62-Yu3:b-olitfm)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`examples/hardware_sim/README.md` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qPCSv4ZqDgrN1wMrd:-N7qPCSv4ZqDgrN1wMre:b-1izalf) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/README.md#L11)):*
> ```Markdown
> $ bazel run //examples/hardware_sim:homecart
> 
> At the moment, the capabilities demonstread by the example are somewhat limited.
> ```

nit s/ demonstread/demonstrated
___
*[`examples/hardware_sim/hardware_sim.cc` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qHp5O5ppCGMtVoUyZ:-N7qHp5PAZ7Yi59r7dyU:b-9jflej) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/hardware_sim.cc#L24)):*
> ```cpp
> #include "drake/systems/lcm/lcm_config_functions.h"
> 
> DEFINE_string(scenario_file, "", "Scenario filename");
> ```

BTW As a newbie to this file, the semantics of these three parameters aren't clear to me. I realize that full clarity may depend on other pieces landing before discussion would make sense. Where do you anticipate that education will happen?
___
*[`examples/hardware_sim/hardware_sim.cc` line 46 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qNqPdEghvdRZwried:-N7qNqPdEghvdRZwriee:b-u0ftu5) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/hardware_sim.cc#L46)):*
> ```cpp
> class Simulation {
>  public:
>   explicit Simulation(const Scenario& scenario)
> ```

Is there a reason to pass by ref instead of value? Obviously, in your `main()`, use of a `const Scenario` precludes leveraging move semantics. But our style guide encourages value here.
___
*[`examples/hardware_sim/scenario.h` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qPhKv7LXpvu0FqLr4:-N7qPhKv7LXpvu0FqLr5:b-io1ea6) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/scenario.h#L15)):*
> ```objc
> #include "drake/systems/analysis/simulator_config.h"
> 
> namespace drake {
> ```

BTW Is this the final destination for this file? Obviously, we have other config files distributed close to what they configure. Is it simply the case, that this is just so high level, there is no natural subdirectory for it to belong to and/or so coupled to hardware sim that it can't meaningfully be elsewhere?

It means that someone who wants to follow this pattern must either depend on an example or copy it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`examples/hardware_sim/scenario.h` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qPhKv7LXpvu0FqLr4:-N7qTyy-8kyRrlRTMO5L:b1ljgi7) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/scenario.h#L15)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is this the final destination for this file? Obviously, we have other config files distributed close to what they configure. Is it simply the case, that this is just so high level, there is no natural subdirectory for it to belong to and/or so coupled to hardware sim that it can't meaningfully be elsewhere?

It means that someone who wants to follow this pattern must either depend on an example or copy it.
</blockquote></details>

The design intention is that users should maintain their own forks of this file (as well as the main program).  Anzu will do so.

The user's schema will almost always differ from this one, either by removing support for things they don't need, or adding support new custom things that aren't here.

I'll make that more clear in the documentation.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`examples/hardware_sim/hardware_sim.cc` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qHp5O5ppCGMtVoUyZ:-N7r5eiu4d-C7TFboKjU:b-wec7vv) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/hardware_sim.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As a newbie to this file, the semantics of these three parameters aren't clear to me. I realize that full clarity may depend on other pieces landing before discussion would make sense. Where do you anticipate that education will happen?
</blockquote></details>

Done (added more descriptive text to the `--help`).
___
*[`examples/hardware_sim/hardware_sim.cc` line 46 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qNqPdEghvdRZwried:-N7r4AR07APVlcudDTWT:b-plkoxw) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/hardware_sim.cc#L46)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Is there a reason to pass by ref instead of value? Obviously, in your `main()`, use of a `const Scenario` precludes leveraging move semantics. But our style guide encourages value here.
</blockquote></details>

OK I guess I didn't consider this to be performance-sensitive enough for it to matter, and the GSG language says "consider" not "encourage".  (We encourage it in cases where the performance might make a difference.)
___
*[`examples/hardware_sim/scenario.h` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7qPhKv7LXpvu0FqLr4:-N7r6JGZ5XNuqfr5mZo_:bfke1v2) ([raw file](https://github.com/robotlocomotion/drake/blob/d1b0141d1fa64b534b2a11f8b120f30bd6b7a079/examples/hardware_sim/scenario.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The design intention is that users should maintain their own forks of this file (as well as the main program).  Anzu will do so.

The user's schema will almost always differ from this one, either by removing support for things they don't need, or adding support new custom things that aren't here.

I'll make that more clear in the documentation.
</blockquote></details>

Done (in the README).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 14 of 16 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615#-:-N7v7AXJAcazPCPljlDX:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`examples/hardware_sim/scenario.h` line 58 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7v63_hDcHVxX2gRpF3:-N7v63_hDcHVxX2gRpF4:b-vzhnw8) ([raw file](https://github.com/robotlocomotion/drake/blob/da51b0521543e19b73b5d9c9541567f6eab6539c/examples/hardware_sim/scenario.h#L58)):*
> ```objc
> 
> /* Returns a C++ representation of the given YAML scenario.
> @param scenario_text amends/updates the scenario with additional YAML schema. */
> ```

BTW I found this a bit terse on first read. Maybe borrow some text from help messages in the main file?



_Code quote:_
```objc
additional YAML schema.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`examples/hardware_sim/scenario.h` line 58 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7v63_hDcHVxX2gRpF3:-N7vGgfZAfL4L1URi1ii:b-ry3pg2) ([raw file](https://github.com/robotlocomotion/drake/blob/da51b0521543e19b73b5d9c9541567f6eab6539c/examples/hardware_sim/scenario.h#L58)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW I found this a bit terse on first read. Maybe borrow some text from help messages in the main file?
</blockquote></details>

Working

Please don't use the "Informing" disposition for discussions that might require action.  It defeats the reviewable workflow.  If you want to start with BTW for actionable discussions, you need to manually toggle the disposition to "Discussing".  The other option is to open with "minor" or "nit" instead.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`examples/hardware_sim/scenario.h` line 58 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17615#-N7v63_hDcHVxX2gRpF3:-N7vqVM2B8niDCpvzNHz:b-1bdr8m) ([raw file](https://github.com/robotlocomotion/drake/blob/da51b0521543e19b73b5d9c9541567f6eab6539c/examples/hardware_sim/scenario.h#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Please don't use the "Informing" disposition for discussions that might require action.  It defeats the reviewable workflow.  If you want to start with BTW for actionable discussions, you need to manually toggle the disposition to "Discussing".  The other option is to open with "minor" or "nit" instead.
</blockquote></details>

OK Resolved by citing the main program's help string.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17615)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
