### PR TITLE
Move AngleAxis functionality to RotationMatrix class

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8468)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review: +@hongkai-dai 
Platform review +@seancurtis-tri 

What this PR does:
a. Enhance RotationMatrix class functionality.
b.  Remove most of old Vect4 axis-angle representation which is easily confused with Eigen::AngleAxis.

1. New RotationMatrix constructor  added -- its one argument is an Eigen::AngleAxis.
    Old  axis2rotmat()  removed from math/axis_angle.h.
    Call site to  axis2rotmat()  in  random_rotation.h  has been updated.

2.  New RotationMatrix method ToAngleAxis  added.
     Old  rotmat2axis()  removed from math/rotation_matrix_deprecated.h
    Call site to  rotmat2axis()  in  ControlUtil.cp   has been updated;

3.  Old tests removed.  New tests added.
     Minor documentation improvements.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-:-L8iLkXnDt0pQHj5OXss:bee87nc)*

**Comment by hongkai-dai** [comment]
:lgtm: with minor comments 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/test/rotation_matrix_test.cc, line 510 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8magIaCBDLYu6mWwBI:-L8magIaCBDLYu6mWwBJ:b1m2ac7) ([raw file](https://github.com/robotlocomotion/drake/blob/dca9b8fc2e8cd9e31915f2b0c395938ddc52948c/math/test/rotation_matrix_test.cc#L510)):*
> ```cpp
> 
>     // Check that can invert this operation, i.e., calculate the angle-axis from
>     // the rotation matrix that correspond to the same orientation.
> ```

`correspond` -> `corresponds`

---

*[math/test/rotation_matrix_test.cc, line 515 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8mau5T8eXAeq2jOHdt:-L8mau5T8eXAeq2jOHdu:bf9nkjv) ([raw file](https://github.com/robotlocomotion/drake/blob/dca9b8fc2e8cd9e31915f2b0c395938ddc52948c/math/test/rotation_matrix_test.cc#L515)):*
> ```cpp
>     // angle-axis has singularities for angles near 0 and 180 degree.
>     Eigen::AngleAxis<double> inverse_angle_axis;
>     inverse_angle_axis.fromRotationMatrix(R_expected.matrix());
> ```

Should we check that the angle in `inverse_angle_axis` is within [0, PI)?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-:-L8mb9257GXcsbZ6ssyn:b-68qyy2)*

**Comment by mitiguy** [comment]
@drake-jenkins-bot    linux-xenial-clang-bazel-experimental-everything-release-bazel   please

**Comment by soonho-tri** [comment]
-@soonho-tri , punting it to @sherm1 (I'm on leave today).

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-:-L8q7OT6DNWq6VWSz_xz:bfwa9dy)*

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-release-bazel please

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by sherm1** [comment]
Reviewed 3 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[math/axis_angle.h, line 2 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sitNi8mq4PRP10lx3:-L8sitNi8mq4PRP10lx4:b-53iohy) ([raw file](https://github.com/robotlocomotion/drake/blob/54dde2c6ac232941ad3164032aa7e2bf5d4d99e8/math/axis_angle.h#L2)):*
> ```objc
> /// @file
> /// Utilities for arithmetic on axis-angle rotations.
> ```

BTW per f2f add TODO to get rid of this file?

---

*[math/random_rotation.h, line 24 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sgz2c9dz6O3l3iIgC:-L8sgz2c9dz6O3l3iIgD:bwo610p) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/random_rotation.h#L24)):*
> ```objc
> template <class Generator>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> Eigen::Vector4d UniformlyRandomAxisAngle(Generator& generator) {
> ```

BTW this should be replaced with a method that returns Eigen::AxisAngle (add a TODO).

---

*[math/random_rotation.h, line 40 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sh4n4BMniHKCohO4V:-L8sh4n4BMniHKCohO4W:b380j7t) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/random_rotation.h#L40)):*
> ```objc
> template <class Generator>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> Eigen::Vector4d UniformlyRandomQuat(Generator& generator) {
> ```

BTW this should be replaced with a method that returns Eigen::Quaternion (add a TODO).

---

*[math/random_rotation.h, line 49 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sh9M339ucCWYv1moG:-L8sh9M339ucCWYv1moH:b3eoold) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/random_rotation.h#L49)):*
> ```objc
> template <class Generator>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> Eigen::Matrix3d UniformlyRandomRotmat(Generator& generator) {
> ```

BTW this should be replaced with a method that returns a RotationMatrix (add a TODO).

---

*[math/random_rotation.h, line 63 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8shETC7CT0Z2gcVPN_:-L8shETC7CT0Z2gcVPNa:b-7jkusk) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/random_rotation.h#L63)):*
> ```objc
> template <class Generator>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> Eigen::Vector3d UniformlyRandomRPY(Generator& generator) {
> ```

FYI this one is OK!

---

*[math/rotation_matrix.h, line 56 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8shJuHEOmcGFfo6L5d:-L8shJuHEOmcGFfo6L5e:b-6ofngj) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/rotation_matrix.h#L56)):*
> ```objc
>   }
> 
>   /// Constructs a %RotationMatrix from a Eigen::Quaternion.
> ```

BTW a -> an

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468)*

**Comment by sherm1** [comment]
Platform pass 1 -- an assortment of BTWs ...

---

Reviewed 3 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[math/rotation_matrix.h, line 61 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8snegaBzgRasZyV3fA:-L8snegaBzgRasZyV3fB:b-mgwqsz) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/rotation_matrix.h#L61)):*
> ```objc
>   /// @throws exception std::logic_error in debug builds if the rotation matrix
>   /// R that is built from `quaternion` fails IsValid(R).  For example, an
>   /// exception is thrown if `quaternion` is zero or contains a NAN or infinity.
> ```

BTW correct spelling is `NaN` rather than `NAN` (elsewhere here also).

---

*[math/rotation_matrix.h, line 65 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8smuW35DFILVuqy5er:-L8smuW4-kHCRZgjKfFe:b-k1q75g) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/rotation_matrix.h#L65)):*
> ```objc
>   /// without the inefficiency of the square-root associated with normalization.
>   // TODO(mitiguy) Consider adding an optional second argument if quaternion is
>   // known to be normalized apriori or calling site does not want normalization.
> ```

BTW this TODO seems to contradict the @note just above it.

---

*[math/rotation_matrix.h, line 76 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sn6aG32xqYjGlyiN8:-L8sn6aG32xqYjGlyiN9:b-tmo9ra) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/rotation_matrix.h#L76)):*
> ```objc
> #ifdef DRAKE_ASSERT_IS_ARMED
>     ThrowIfNotValid(R_AB_);
> #endif
> ```

BTW this should be:
```
DRAKE_ASSERT_VOID(ThrowIfNotValid(R_AB_));
```
which does the same thing without ifdefs (also below).

---

*[math/rotation_matrix.h, line 92 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8soSJl49Aik-2RB3ob:-L8soSJl49Aik-2RB3oc:bflcjr8) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/rotation_matrix.h#L92)):*
> ```objc
>     const T norm = lambda.norm();
>     const T& theta = theta_lambda.angle();
>     R_AB_ = Eigen::AngleAxis<T>(theta, lambda / norm).toRotationMatrix();
> ```

BTW consider instead converting to an unnormalized quaternion then calling your nice quaternion-to-rotation matrix method (or you could forward this constructor to that one). That would avoid the square root here, and you wouldn't have to depend on whatever ugly things are going on in Eigen's conversion.

---

*[math/test/rotation_matrix_test.cc, line 485 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8spmCW0okEH1tGxM-K:-L8spmCW0okEH1tGxM-L:bt6v627) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/test/rotation_matrix_test.cc#L485)):*
> ```cpp
>   EXPECT_THROW(const RotationMatrix<double> R_bad(q_zero), std::logic_error);
> 
>   // A quaternion containing a NAN throw an exception.
> ```

BTW NAN->NaN

---

*[math/test/rotation_matrix_test.cc, line 494 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sqEY222GBgKVfJjKm:-L8sqEY222GBgKVfJjKn:b-ngtn8b) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/test/rotation_matrix_test.cc#L494)):*
> ```cpp
> TEST_F(RotationMatrixConversionTests, AngleAxisToRotationMatrix) {
>   for (const Eigen::Quaterniond& qi : quaternion_test_cases_) {
>     // Compute the rotation matrix R using Eigen's quaterion.toRotationMatrix().
> ```

BTW I think this comment is wrong -- you have your own conversion method, right? If you actually want to compare with Eigen results, you should invoke Eigen directly in this test rather than assume you know how these other methods are implemented since those could change in the future even if they are using Eigen now.

---

*[math/test/rotation_matrix_test.cc, line 528 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sqyAKDjgw6Cb3x4Ri:-L8sqyAKDjgw6Cb3x4Rj:bt6v627) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/test/rotation_matrix_test.cc#L528)):*
> ```cpp
>   EXPECT_THROW(const RotationMatrix<double> R_zero(aa_zero), std::logic_error);
> 
>   // An AngleAxis containing a NAN should throw an exception.
> ```

BTW NAN->NaN

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-:-L8srBqJ8r6-4Bg_HUi1:bfh71uk)*

**Comment by mitiguy** [comment]
Reviewed 2 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[math/rotation_matrix.h, line 92 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8soSJl49Aik-2RB3ob:-L8tRvqe3Ie8V4DjFNs4:blds8v3) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/rotation_matrix.h#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider instead converting to an unnormalized quaternion then calling your nice quaternion-to-rotation matrix method (or you could forward this constructor to that one). That would avoid the square root here, and you wouldn't have to depend on whatever ugly things are going on in Eigen's conversion.
</blockquote></details>

 Done.  Per f2f conversation, comment added to clarify.

---

*[math/test/rotation_matrix_test.cc, line 494 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8sqEY222GBgKVfJjKm:-L8tUYZN-3d-VYpHUw5s:b-odwqp9) ([raw file](https://github.com/robotlocomotion/drake/blob/dc9f84b0dafdf0b9aee0c8ef0035991cd9388af0/math/test/rotation_matrix_test.cc#L494)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I think this comment is wrong -- you have your own conversion method, right? If you actually want to compare with Eigen results, you should invoke Eigen directly in this test rather than assume you know how these other methods are implemented since those could change in the future even if they are using Eigen now.
</blockquote></details>

OK  Rework to streamline/clean up this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468)*

**Comment by hongkai-dai** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468)*

**Comment by sherm1** [comment]
Platform :lgtm: w/one BTW.

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/rotation_matrix.h, line 88 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-L8ucE2L6LqPcPVHR0VI:-L8ucE2L6LqPcPVHR0VJ:b-1jb231) ([raw file](https://github.com/robotlocomotion/drake/blob/9b4cf6731a131c50f9aabcb821db49356142a584/math/rotation_matrix.h#L88)):*
> ```objc
>   /// `lambda` to this method is different than the %RotationMatrix produced by
>   /// converting `lambda` to an un-normalized quaternion and calling the
>   /// %RotationMatrix constructor (above) with that un-normalized quaternion.
> ```

BTW not sure this makes sense as a doxygen comment? Is this meaningful to the caller or just to developers (like me) who might be tempted to user the quaternion constructor here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8468#-:-L8ucdMiErXy_L14c3X7:b-pc2py1)*

**Pull request merged**
