### PR TITLE
Updates schung wsg lift test

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1) Classifes test as a LARGE test
2) Modifies gripper to include contact points.
3) Update test to:
   a) Visualize contact forces
   b) Stricter definition of "passing"

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5292)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@sammy-tri for feature review (with particular attention to modifications of `schunk_wsg_50.sdf` -- should there be a unique file?)  +@jwnimmer-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KdgunhN24vt09Y0AR7_:bc0yaxf)*

**Comment by SeanCurtis-TRI** [comment]
Temporarily putting review on hold.  Previously, the test wasn't being built by bazel.  Now it is.  In order for it to build in bazel, it's waiting on PR #5293.

**Comment by siyuanfeng-tri** [comment]
ur, i'd like a separate gripper. 
it seems like you got rid of the finger geometry entirely. if i grab a cylinder (or a super small thing, or at the finger tip) and miss the balls, bad things happen? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-Kdh-dzRKUoLMrOPXl9D:b-aqaszw)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri 

Please re-assign for platform review once its ready (e.g., it builds, feature review and Siyuan agree with these changes, etc.).

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-Kdh1TqdSyVntZkNpK1O:b-7rs57r)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeFw23aD2Oycjh5TMcv:b-nikqms)*

**Comment by SeanCurtis-TRI** [comment]
@siyuanfeng-tri and @sammy-tri, this is ready for review again.

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 278 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeH4WmtNnNuEhdJJjKg:-KeH4WmtNnNuEhdJJjKh:b-pyhuej) ([raw file](https://github.com/robotlocomotion/drake/blob/68b5fe19dee51b5b9d823d84c022dc45e04c3aba/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L278)):*
> ```cpp
>   const int box_index = tree.FindBodyIndex("box");
>   Vector3<double> final_pos = kinematics_results2.get_body_position(box_index);
>   EXPECT_GT(final_pos(2), kExpectedHeight);
> ```

you are going to hate this..

can you add a check on orientation..? also vel6? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 98 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeH3lX5T45Xz7cKtZku:-KeH3lX5T45Xz7cKtZkv:b-4gt1v6) ([raw file](https://github.com/robotlocomotion/drake/blob/68b5fe19dee51b5b9d823d84c022dc45e04c3aba/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L98)):*
> ```cpp
> 
>   // Arbitrary contact parameters.
>   const double kStiffness = 10000;
> ```

BTW, these are default magic numbers, right? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292)*

**Comment by siyuanfeng-tri** [comment]
FYI, sammy is out till monday. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeH4nEACK-2wbd7jBM3:btbvd9b)*

**Comment by SeanCurtis-TRI** [comment]
Good to know (re: Sammy); not the end of the world.  Comments (to varying degrees) addressed.  PTAL.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 98 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeH3lX5T45Xz7cKtZku:-KeJqPo2F2JfDus2F8rB:b5xunvh) ([raw file](https://github.com/robotlocomotion/drake/blob/68b5fe19dee51b5b9d823d84c022dc45e04c3aba/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L98)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, these are default magic numbers, right? 
</blockquote></details>

Yep.  When I add the more general documentation of the contact model, I'll go into them more.  For example, the stiffness should increase with the mass of the object (1e5 is insufficient for the car simulation; the car drops right through the ground.)  Similarly, `kVStictionTolerance` should scale with the size of the interaction.  0.01 is probably too large for this scenario if you have a reasonable expectation for *actual* stiction.  However, this test needs to run in some tractable time frame.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 278 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeH4WmtNnNuEhdJJjKg:-KeJqu8ATWOp9qS7chqE:b1ei8dl) ([raw file](https://github.com/robotlocomotion/drake/blob/68b5fe19dee51b5b9d823d84c022dc45e04c3aba/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L278)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

you are going to hate this..

can you add a check on orientation..? also vel6? 
</blockquote></details>

I don't hate it.  :)  On the surface, they *seem* reasonable requests, but I'd argue against them for the following reasons:

1) I have no well-reasoned basis for what a "correct" change in orientation is.  It's conceivable that it could be computed, but it's a *mountain* of work.
2) Similarly, the spatial velocity has similar woes.  By bounding the vertical slip, we are at least bounding the *average* vertical velocity (and given the only non-gripper force at play is gravity, it seems reasonable.)  That said, it's in some sense conceivable that the overall displacement of the center of mass (divided by the simulation time) might represent a higher slip speed than is expected.

Ultimately, the purpose of this test is two-fold: implicitly define some sort of "minimum" acceptable behavior baseline for the contact model and stiction and provide an automated mechanism that will detect if something changes *somewhere* that means we no longer satisfy minimum acceptability.  

Given your request, I've modified the documentation in the file and made the test more reflective of this.  Let me know what you think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeJqLe-9NDhQY5_pEVf:bw2o6rm)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 278 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeH4WmtNnNuEhdJJjKg:-KeKmbFabrXxMbsHJCMS:b-dpnwa3) ([raw file](https://github.com/robotlocomotion/drake/blob/68b5fe19dee51b5b9d823d84c022dc45e04c3aba/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L278)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I don't hate it.  :)  On the surface, they *seem* reasonable requests, but I'd argue against them for the following reasons:

1) I have no well-reasoned basis for what a "correct" change in orientation is.  It's conceivable that it could be computed, but it's a *mountain* of work.
2) Similarly, the spatial velocity has similar woes.  By bounding the vertical slip, we are at least bounding the *average* vertical velocity (and given the only non-gripper force at play is gravity, it seems reasonable.)  That said, it's in some sense conceivable that the overall displacement of the center of mass (divided by the simulation time) might represent a higher slip speed than is expected.

Ultimately, the purpose of this test is two-fold: implicitly define some sort of "minimum" acceptable behavior baseline for the contact model and stiction and provide an automated mechanism that will detect if something changes *somewhere* that means we no longer satisfy minimum acceptability.  

Given your request, I've modified the documentation in the file and made the test more reflective of this.  Let me know what you think.
</blockquote></details>

fair arguments. 
now you are still going to hate this
can you add a new test (in a new pr) that have a block sitting on some surface with no actuation for a while. and essentially test for stationary? i think current drake fails that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeKmv-2I0KmRI_mshsA:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Thanks @siyuanfeng-tri 

+@ggould-tri  More contact demo fun for platform review.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 278 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeH4WmtNnNuEhdJJjKg:-KeKtcZMv2Yi-a6n_Dxw:b5a9c10) ([raw file](https://github.com/robotlocomotion/drake/blob/68b5fe19dee51b5b9d823d84c022dc45e04c3aba/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L278)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

fair arguments. 
now you are still going to hate this
can you add a new test (in a new pr) that have a block sitting on some surface with no actuation for a while. and essentially test for stationary? i think current drake fails that. 
</blockquote></details>

You mentioned this at the tale end of last week.  My absence at the beginning of the week merely delayed my investigation into this.  I think adding a test is a (probably) a great idea.  (You'll have to work a lot hard to awaken my ire let alone my hatred.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeKtuHUY_xeIxFGrOtE:b-j1itpb)*

**Comment by ggould-tri** [comment]
Will not get to this until Monday.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeKx-mLyh-9Yw96DtMv:b-3s1kjl)*

**Comment by ggould-tri** [comment]
Three comment text nits below.  :lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 271 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeYxas8MEZsBGrv92-T:-KeYxas8MEZsBGrv92-U:bch59qe) ([raw file](https://github.com/robotlocomotion/drake/blob/b95ce4e1c16f5bb1522e2e349485e28bd1a0a1db/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L271)):*
> ```cpp
>   // consider to be "acceptable" stiction behavior.
>   //
>   // The box starts resting on the ground; it's center is at the position
> ```

FYI typo -- "it's" should be "its".

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 306 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeYyLhS9xNP6Gh9OR0x:-KeYyLhS9xNP6Gh9OR0y:b2eqtyx) ([raw file](https://github.com/robotlocomotion/drake/blob/b95ce4e1c16f5bb1522e2e349485e28bd1a0a1db/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L306)):*
> ```cpp
>   //     whose scale is on the same order of magnitude.  This is a testing
>   //     expediency to allow for timely execution.  This does not *prove* that
>   //     the behavior is correct smaller thresholds (and the corresponding
> ```

FYI -- typo?  I wonder if you meant to have a preposition between 'correct' and 'smaller'?

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 307 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeYy9660SziKPGxYbH6:-KeYy9660SziKPGxYbH7:b-x57p9d) ([raw file](https://github.com/robotlocomotion/drake/blob/b95ce4e1c16f5bb1522e2e349485e28bd1a0a1db/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L307)):*
> ```cpp
>   //     expediency to allow for timely execution.  This does not *prove* that
>   //     the behavior is correct smaller thresholds (and the corresponding
>   //     more precise integrator settings.
> ```

FYI -- typo, neither of the open-parens in the previous paragraph have close-parens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeYyu3bXPw3SnG2PYnO:b-tbfdwc)*

**Comment by sammy-tri** [comment]
:lgtm: pending nits noted above

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeZLGxg86-9vyGEqYLJ:b-jso7bz)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292)*

**Comment by SeanCurtis-TRI** [comment]
Updated; awaiting CI.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 271 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeYxas8MEZsBGrv92-T:-KeZNgFOVzINB8HWjfFv:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b95ce4e1c16f5bb1522e2e349485e28bd1a0a1db/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L271)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo -- "it's" should be "its".
</blockquote></details>

Done

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 306 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeYyLhS9xNP6Gh9OR0x:-KeZP5VTTrNRxoKGylMW:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b95ce4e1c16f5bb1522e2e349485e28bd1a0a1db/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L306)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- typo?  I wonder if you meant to have a preposition between 'correct' and 'smaller'?
</blockquote></details>

Done

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 307 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeYy9660SziKPGxYbH6:-KeZOk1gRcZJLa6liKJd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b95ce4e1c16f5bb1522e2e349485e28bd1a0a1db/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L307)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- typo, neither of the open-parens in the previous paragraph have close-parens.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-:-KeZP7Joce69qiwqXnOJ:bxzg5f3)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 201 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeZRYcYLKhdHu5k-C2F:-KeZRYcYLKhdHu5k-C2G:b-1te6yf) ([raw file](https://github.com/robotlocomotion/drake/blob/6e73c1eaeab57005a684b00dd1a07b7c0868f87f/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L201)):*
> ```cpp
>   // Expose the RBPlant kinematics results as a diagram output for body state
>   // validation.
>   const int kinematrics_results_index = builder.ExportOutput(plant->get_output_port(
> ```

FYI Long line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc, line 201 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5292#-KeZRYcYLKhdHu5k-C2F:-KeZTxjQjvdRa6gLVIwT:b2k4p7) ([raw file](https://github.com/robotlocomotion/drake/blob/6e73c1eaeab57005a684b00dd1a07b7c0868f87f/drake/examples/schunk_wsg/test/schunk_wsg_lift_test.cc#L201)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Long line
</blockquote></details>

D'oh-ne.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5292)*

**Pull request merged**
