### PR TITLE
[multibody] Some minor documentation tweaks and internal cleanup

### PR DESCRIPTION
**Pull request by sherm1**
Fixes a few minor things I bumped into while poking around in the multibody guts:
- Clarifies that the mass matrix M includes the reflected inertia term
- Renamed BodyNodeWeld to BodyNodeWorld to reflect its actual use
- Minor doc fixes here and there

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18427)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@amcastro-tri for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18427#-:-NIo8PYW1IfbmeFv6g9D:bkta03b)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18427#-:-NJ6mZ2U6r1pAyjYLxMs:bg7igkv)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @sherm1)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18427#-NJ6mU1CDdbsiJoObIZp):*
btw, Might want to copy notes from the PR itself

> Clarifies that the mass matrix M includes the reflected inertia term
> Renamed BodyNodeWeld to BodyNodeWorld to reflect its actual use
> Minor doc fixes here and there
___
*[`multibody/plant/multibody_plant.h` line 3229 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18427#-NJ6lfBX2LZOThc8nZ4v:-NJ6lfBX2LZOThc8nZ4w:b-fjvj7j) ([raw file](https://github.com/robotlocomotion/drake/blob/4f5407e1e8467676aef73383c1a34239e3935d34/multibody/plant/multibody_plant.h#L3229)):*
> ```objc
>   /// @{
> 
>   /// Computes the mass matrix `M(q)` of the model using slow method (inverse
> ```

minor, using **a** slow method
___
*[`multibody/tree/body_node_world.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18427#-NJ6mEFx5SNwCnQuTdZ_:-NJ6mEFx5SNwCnQuTdZa:bl160l0) ([raw file](https://github.com/robotlocomotion/drake/blob/4f5407e1e8467676aef73383c1a34239e3935d34/multibody/tree/body_node_world.h#L10)):*
> ```objc
> 
> // TODO(sherm1) Can we just get rid of this class and use a 0-dof BodyNodeImpl
> // instead?
> ```

btw, maybe? I remember this causing trouble in the past (long long ago). As the removed comment states, there was something with Eigen barking about zero-sized matrices.

**Review by amcastro-tri — COMMENTED** [review]
+@seancurtis-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18427#-:-NJ6me0p9uTw2Fhyzfpv:b-tnzbcp)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18427)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @amcastro-tri and @SeanCurtis-TRI)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18427#-NJ6mU1CDdbsiJoObIZp):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, Might want to copy notes from the PR itself

> Clarifies that the mass matrix M includes the reflected inertia term
> Renamed BodyNodeWeld to BodyNodeWorld to reflect its actual use
> Minor doc fixes here and there

</blockquote></details>

Done
___
*[`multibody/plant/multibody_plant.h` line 3229 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18427#-NJ6lfBX2LZOThc8nZ4v:-NJ6pF2D--OESPFnFlQj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f5407e1e8467676aef73383c1a34239e3935d34/multibody/plant/multibody_plant.h#L3229)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, using **a** slow method
</blockquote></details>

Done.
___
*[`multibody/tree/body_node_world.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18427#-NJ6mEFx5SNwCnQuTdZ_:-NJ6pHaxBlz6vKsDwWN4:b3rjsyv) ([raw file](https://github.com/robotlocomotion/drake/blob/4f5407e1e8467676aef73383c1a34239e3935d34/multibody/tree/body_node_world.h#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, maybe? I remember this causing trouble in the past (long long ago). As the removed comment states, there was something with Eigen barking about zero-sized matrices.
</blockquote></details>

Thanks, will leave as a TODO for now. The 0-sized matrix problem might not exist any more -- a 0-sized instantiation is currently used for Welds.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18427#-:-NJ7QYgF1JWYgLcPNyVJ:bjw1nd)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,SeanCurtis-TRI(platform) (waiting on @sherm1)

**Pull request merged**
