### PR TITLE
add a plan eval instance that moves manipulator end effector in cartesian space.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
adds the first concrete example in the plan eval stack. it does end effector cartesian tracking for a manipulator.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5789)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for feature review. i am in no rush. hopefully this isnt be too bad. 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-:-KhQQ0cjj4Ab4EKoAjkq:b-gu7tyb)*

**Comment by sammy-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/BUILD, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhS_rKZ7aAZ5URY3bnx:-KhS_rK_4WWnp3huGJvT:b-9ehm6e) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/BUILD#L50)):*
> ```Python
>         "//drake/util:lcm_util",
>         "@bot_core_lcmtypes//:lib",
>         "@robotlocomotion_lcmtypes//:lib",
> ```

Does this actually depend on robotlocomotion_lcmtypes?

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhSdM8a3559JBJaPoPk:-KhSdM8buuPWyaHKSJV3:b3nbyov) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L40)):*
> ```cpp
>   DRAKE_DEMAND(consumed == message_length);
> 
>   DRAKE_DEMAND(static_cast<size_t>(msg.num_steps) == msg.utimes.size() &&
> ```

BTW I'm not a huge fan of crashing on malformed network input instead of logging and continuing, but that might just be personal preference.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhSaAu2ySjaMrWM_r2v:-KhSaAu2ySjaMrWM_r2w:b-v43wfa) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L14)):*
> ```objc
>  * A concrete plan that sets up a Cartesian tracking objective for the end
>  * effector assuming no contacts. The joint space tracking objective is set
>  * to track the joint position when this plan is first initialized to.
> ```

"first initialized to" is a strange way to end a sentence.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhSbeo3eSRUB6Y-mCTR:-KhSbeo3eSRUB6Y-mCTS:b-wdn7de) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L61)):*
> ```objc
>       const void* message_bytes, int message_length);
> 
>  private:
> ```

It's not clear to me why some of these derived methods are protected and some are private.  Also I think we're missing an override or final keyword in some places.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhScjhbKjVAU5StppmX:-KhScjhcrjdFt9MWBD89:bb2ja10) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc#L7)):*
> ```cpp
> #include "drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/test_common.h"
> #include "drake/multibody/joints/floating_base_types.h"
> #include "drake/multibody/parsers/urdf_parser.h"
> ```

Is this unused now?  (possibly also floating_base_types.h?)

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/test_common.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhScDDxbs-TIIFCO-Th:-KhScDDyXEubb7Kodchl:b-ji3rlc) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/test_common.h#L24)):*
> ```objc
>   // Allocates robot_, alias_groups_, params_, and robot_status_. dut_ should
>   // be allocated in individual tests depending on which plan is under test.
>   void AllocateRescourse(const std::string& robot_path,
> ```

Is "Rescourse" a typo here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789)*

**Comment by siyuanfeng-tri** [comment]
Review status: 1 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/BUILD, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhS_rKZ7aAZ5URY3bnx:-KhSg_1zlR_sjYaIhLFL:b-x2578w) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/BUILD#L50)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this actually depend on robotlocomotion_lcmtypes?
</blockquote></details>

it was.. but i took it out because of the size of the pr. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhSdM8a3559JBJaPoPk:-KhSgv-Sr9eNrNa9ecnN:b4gwvth) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L40)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm not a huge fan of crashing on malformed network input instead of logging and continuing, but that might just be personal preference.
</blockquote></details>

yeah. i am not going to bother with error handling for now. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhSaAu2ySjaMrWM_r2v:-KhShZ3n7gbb0sYzEz5H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"first initialized to" is a strange way to end a sentence.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhSbeo3eSRUB6Y-mCTR:-KhShvOlQU1NdbSQq9KX:b-a8meuw) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L61)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's not clear to me why some of these derived methods are protected and some are private.  Also I think we're missing an override or final keyword in some places.
</blockquote></details>

so i wanted to have them all private, but i need protected to get doxygen to work correctly.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhScjhbKjVAU5StppmX:-KhSqxH2C6kh1ql1jY78:bb7s9mg) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc#L7)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this unused now?  (possibly also floating_base_types.h?)
</blockquote></details>

yeah

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/test_common.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhScDDxbs-TIIFCO-Th:-KhSrTEzNGP6qZJeE57k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7124a0e9e6182b4fc81513476895d8cd9466aa/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/test_common.h#L24)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is "Rescourse" a typo here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: pending CI and platform review

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-:-KhT9H9d57DOTXLEsvtL:bz6nsxo)*

**Comment by siyuanfeng-tri** [comment]
+@ggould-tri for platform.review, thank! i am working on the ci and comment. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-:-KhY1tINy_ImxQzKbKPT:bhf5px1)*

**Comment by ggould-tri** [comment]
I am a little bit disappointed to see code with a nice `vector<uint8_t>` in hand converting it to a much more dangerous `void*`/`int` pair and passing those.  But no defect, as it is required by a superclass not included in this PR.

:lgtm: pending minor items below.

---

Reviewed 1 of 8 files at r1, 5 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYRYQxnsJoSeSG2puV:-KhYRYQxnsJoSeSG2puW:b-w2rpy6) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L56)):*
> ```cpp
>   // If the first keyframe does not start immediately (its time > 0), we start
>   // from the current desired pose.
>   if (msg.utimes.front() != 0) {
> ```

FYI You just commented this as `> 0` rather than `!= 0`.  They should agree.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYUCYkZefu4a7mRGXY:-KhYUCYkZefu4a7mRGXZ:bn2i78l) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L49)):*
> ```objc
>    * pose and velocity. This introduces a discontinuity in the interpolated
>    * desired position and velocity when interpolating, which can cause large
>    * discontinuity in output and instability on robot.
> ```

FYI grammar -- "cause large discontinuity" needs an "a" or a plural.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/manipulator_plan_test.cc, line 121 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYWMUA7GmPwtG6myRd:-KhYWMUA7GmPwtG6myRe:b51gmii) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/manipulator_plan_test.cc#L121)):*
> ```cpp
> 
>     EXPECT_TRUE(drake::CompareMatrices(Vector6<double>::Zero(),
>                                        ee_traj.get_acceleration(time), 1e-12,
> ```

Well past rule-of-three on this pattern.

Consider extracting `1e-12` into a named epsilon constant.

Better, consider also closing a helper function or lambda around `EXPECT_TRUE(drake::CompareMatrices(..., 1e-12, drake::MatrixCompareType::absolute))` which would also let you print the results in the case of an error.

If you choose to use a helper function, it could apply to some of the cases in other methods here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-:-KhYHcuIkvVQ_XpMs7UQ:b-bmx1ht)*

**Comment by siyuanfeng-tri** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYRYQxnsJoSeSG2puV:-KhZ8v_NhKw9SNbMsbq9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L56)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI You just commented this as `> 0` rather than `!= 0`.  They should agree.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYUCYkZefu4a7mRGXY:-KhZ979S_kQQQ_4COfUZ:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L49)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI grammar -- "cause large discontinuity" needs an "a" or a plural.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/manipulator_plan_test.cc, line 121 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYWMUA7GmPwtG6myRd:-KhZBHkCradjSLtDGX4-:b-aoxagz) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/manipulator_plan_test.cc#L121)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Well past rule-of-three on this pattern.

Consider extracting `1e-12` into a named epsilon constant.

Better, consider also closing a helper function or lambda around `EXPECT_TRUE(drake::CompareMatrices(..., 1e-12, drake::MatrixCompareType::absolute))` which would also let you print the results in the case of an error.

If you choose to use a helper function, it could apply to some of the cases in other methods here as well.
</blockquote></details>

i made them constexpr, didn't feel like doing extra. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/manipulator_plan_test.cc, line 121 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-KhYWMUA7GmPwtG6myRd:-KhbP1QWurUdXaFrfJ4Y:b-7bpmig) ([raw file](https://github.com/robotlocomotion/drake/blob/54ded0c16f4b76cde88b95aae1ebe9aa12c96785/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/manipulator_plan_test.cc#L121)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i made them constexpr, didn't feel like doing extra. 
</blockquote></details>

@ggould-tri can you take a look at this when you have a chance, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789)*

**Comment by ggould-tri** [comment]
Cool.  :shipit:

---

Reviewed 5 of 5 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5789#-:-KhbQqM7PqDjNBEumtGu:bn295q1)*

**Pull request merged**
