### PR TITLE
Fix outdated doxygen comments and some typos

### LINKED ISSUE #19089: Cleanup Doxygen formatting for RenderEngine implementations
Per #18877, we moved several classes to the `internal` namespace. We should have a follow-up PR to fix the Doxygen formatting of the now-internal classes.

### PR DESCRIPTION
**Pull request by zachfang**
Close #19089

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19750)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for (maybe both) review. Thanks!

This came up when I was reorganizing the namespaces, and I also bundled two small documentation fixes when I read through them a while back.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-:-N_-ZGLD8m7H3lzAWIaE:b-2fokgd)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`geometry/render_gl/internal_opengl_includes.h` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-YzcpDzSj9kar7ZO6:-N_-YzcpDzSj9kar7ZO7:b-fpcz8s) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_gl/internal_opengl_includes.h#L1)):*
> ```objc
> /* @file
> ```

Working. I am also unsure if it's more involved for this file (other than `/**` to `/*`).



_Code quote:_
```objc
/* @file
```
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-YP_91eQxwxC_yH3G:-N_-YP_91eQxwxC_yH3H:b-wujjej) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_vtk/internal_render_engine_vtk.h#L28)):*
> ```objc
> #include "drake/geometry/render_vtk/render_engine_vtk_params.h"
> 
> #ifndef DRAKE_DOXYGEN_CXX
> ```

Working. I think I should also update these preprocessing flags (and for RenderEngineGl) but not sure what's the right way to proceed.



_Code quote:_
```objc
#ifndef DRAKE_DOXYGEN_CXX
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok).

+(release notes: none) 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-:-N_-alN66IflorkshIfd:bx4bd6f)* status: 5 unresolved discussions

___
*[`geometry/render_gl/internal_opengl_includes.h` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-YzcpDzSj9kar7ZO6:-N_-arPwD9h1JkZXgynn:bxfzpcw) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_gl/internal_opengl_includes.h#L1)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Working. I am also unsure if it's more involved for this file (other than `/**` to `/*`).
</blockquote></details>

This is OK by me.

When we're in `/* */` mode (i.e., non-Doxygen) any directives like `@file` are not processed by any of our tools.  Thus, the only audience for the directives are programmers.

Thus the question becomes -- is this directive useful when a programmer is reading the source file?  I think it might be useful; it helps clarify that the following paragraph is describing the entire file, rather than something more narrow.
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 103 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-bHn8C8nS7TV4p1TA:-N_-bHn8C8nS7TV4p1TB:bjmbeub) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_gl/internal_render_engine_gl.h#L103)):*
> ```objc
>   //@}}
> 
>   /* Construct an instance of the render engine with the given `params`.  */
> ```

BTW If you like, there's more typo preening possible.



_Suggestion:_
```objc
Constructs
```
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-YP_91eQxwxC_yH3G:-N_-bjK1648mNoRrG4P8:b62bfdp) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_vtk/internal_render_engine_vtk.h#L28)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Working. I think I should also update these preprocessing flags (and for RenderEngineGl) but not sure what's the right way to proceed.
</blockquote></details>

I didn't look at all uses of DRAKE_DOXYGEN_CXX, but for this one at least I think it should stay in place.  This file is still being _parsed_ by Doxygen, even if everything inside it is `namespace internal` code.  We don't want this shady VTK macro to confuse the Doxygen parser.
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-c65Z3ZzjEDW75hQ0:-N_-c65Z3ZzjEDW75hQ1:b-1fufft) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_vtk/internal_render_engine_vtk.h#L44)):*
> ```objc
>     VTK_AUTOINIT_CONSTRUCT(vtkRenderingOpenGL2)
>   }
> };
> ```

nit The DRAKE_DOXYGEN_CXX could be closed here, instead of down below.

We want to cull the shady VTK_AUTOINIT_CONSTRUCT macro vs the Doxygen parser, but we don't need to cull the `ShaderCallback` etc which are just vanilla C++ code.
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 99 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-cLbS3P_05dMccuy6:-N_-cLbS3P_05dMccuy7:b-v0zhta) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_vtk/internal_render_engine_vtk.h#L99)):*
> ```objc
>   // Note: the copy constructor operator is actually protected to serve as the
>   // basis for implementing the DoClone() method.
>   RenderEngineVtk(const RenderEngineVtk&) = delete;
> ```

nit Remove this line of dead code.  (And the associated DRAKE_DOXYGEN_CXX ifdef).

The comment can stay around in some form, as you like.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19750)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 103 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19750#-N_-bHn8C8nS7TV4p1TA:-N_-ofWy48cWPow3sxmJ:b-1z8hdu) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a2bcc8ab43e5068888e2fa67560c95039ff78ec/geometry/render_gl/internal_render_engine_gl.h#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you like, there's more typo preening possible.
</blockquote></details>

Done. I read through the doc, and the rest seems good.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19750)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
