### PR TITLE
[visualization] Enhance model_visualizer command line

### LINKED ISSUE #18977: ModelVisualizer.AddModelsFromUrl()
Now that we are recommending that people use packages to identify their files, I *believe* we should provide `ModelVisualizer.AddModelsFromUrl()` in addition to `AddModels()`.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18977.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19131)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @trowell-tri

**Review by trowell-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19131)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19131#-:-NSILPoS0Y_5kyKJ78YD:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 233 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19131#-NSIL85LBVblHJZ85FTV:-NSIL85LBVblHJZ85FTW:bpmvn6j) ([raw file](https://github.com/RobotLocomotion/drake/blob/e0375fef4c8cb6bfbf5a44cc7b46d7711e7864b2/bindings/pydrake/visualization/_model_visualizer.py#L233)):*
> ```Python
>         self._builder.parser().AddModels(**kwargs)
>         if self._model_filenames is not None:
>             self._model_filenames.append(kwargs)
> ```

nit  consider renaming this member field, since we do now have a distinction between filenames and other source paths via url. Maybe `_model_paths` ?

**Review by jwnimmer-tri — COMMENTED** [review]
Maybe +@xuchenhan-tri you can take this platform too?  Or else kick to Grant on Monday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19131#-:-NSIkk9n7AJMKFL65s4y:b-jt4onq)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @rpoyner-tri, @trowell-tri, and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19131#-:-NSJ18FTE8fuDzX-K9Y2:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
