### PR TITLE
[geometry/optimization] Allow IrisInConfigurationSpace to optionally consider configuration space obstacles

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@russtedrake for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136#-:-NEg31reAy6zMpNsBgH8:b-nden6u)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
PTAL

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136#-:-NEmYOfOBm7QMVbwp5yI:bb71pro)* status: 6 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

___
*[`geometry/optimization/iris.h` line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmWa0qDXGQgEtrt3cN:-NEmWa0qDXGQgEtrt3cO:b-o0yqeq) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/iris.h#L169)):*
> ```objc
>     const systems::Context<double>& context,
>     const IrisOptions& options = IrisOptions(),
>     const std::optional<ConvexSets>& configuration_obstacles = std::nullopt);
> ```

btw -- did you consider putting this into the IrisOptions?  It would seem a natural place for it...
___
*[`geometry/optimization/iris.cc` line 778 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmWnCp8GGqbRuA6Kc_:-NEmWnCp8GGqbRuA6Kca:b-3a6ft9) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/iris.cc#L778)):*
> ```cpp
>     // Find separating hyperplanes
> 
>     // Add constraints from configuration space obstacles to reduce domain for
> ```

nit: reduce the domain
___
*[`geometry/optimization/iris.cc` line 797 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmXFSj1tgt3CAMdOS7:-NEmXFSj1tgt3CAMdOS8:b-2sd9eq) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/iris.cc#L797)):*
> ```cpp
>                 .IntersectsWith(*obstacles[scaling[i].second])) {
>           // Add the tangent to the (scaled) ellipsoid at this point as a
>           // constraint.
> ```

nit: why not call the existing AddTangentToPolytope? (with backoff of zero)?
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmXxwiAmo_iU0Fvotx:-NEmXxwiAmo_iU0Fvoty:b-yvru72) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/test/iris_in_configuration_space_test.cc#L129)):*
> ```cpp
>   IrisOptions options;
> 
>   // Configutation space obstacles less restrictive than task space obstacle.
> ```

nit: spelling "Configuration"
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmY7hI8CXK2pio1V4_:-NEmY7hI8CXK2pio1V4a:bnhsmho) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/test/iris_in_configuration_space_test.cc#L145)):*
> ```cpp
>   }
> 
>   // Configuration space obstacle more restirctive than task space obstacles.
> ```

nit: spelling "restrictive"
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmYDk-4nswf3fKjvrn:-NEmYDk-4nswf3fKjvro:b6zzob8) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/test/iris_in_configuration_space_test.cc#L160)):*
> ```cpp
>   }
> 
>   // Configutation space obstacles align with task space obstacle.
> ```

nit: spelling

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.h` line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmWa0qDXGQgEtrt3cN:-NEw7Rhn0JxB1RNaLu58:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/iris.h#L169)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- did you consider putting this into the IrisOptions?  It would seem a natural place for it...
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 778 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmWnCp8GGqbRuA6Kc_:-NEvU1AV6BybXu6bAiik:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/iris.cc#L778)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: reduce the domain
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 797 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmXFSj1tgt3CAMdOS7:-NEw4TGWBVFZH-0wrgWG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/iris.cc#L797)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: why not call the existing AddTangentToPolytope? (with backoff of zero)?
</blockquote></details>

Done.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmXxwiAmo_iU0Fvotx:-NEvUBTe9YMuB6hUcsRJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/test/iris_in_configuration_space_test.cc#L129)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: spelling "Configuration"
</blockquote></details>

Done.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmY7hI8CXK2pio1V4_:-NEvUK8z0WujXN05_HRL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/test/iris_in_configuration_space_test.cc#L145)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: spelling "restrictive"
</blockquote></details>

Done.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NEmYDk-4nswf3fKjvrn:-NEvUL5GDSHsHE74tmxE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2dd1bfbc46a4a6b1c5aa54a752029ab1ce19b241/geometry/optimization/test/iris_in_configuration_space_test.cc#L160)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: spelling
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

___
*[`geometry/optimization/iris.cc` line 616 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFIyORZ5g-G-QCUaKBh:-NFIyORZ5g-G-QCUaKBi:btw0i4t) ([raw file](https://github.com/robotlocomotion/drake/blob/a1465038d377838e5d41242cd6fde4b97d838d16/geometry/optimization/iris.cc#L616)):*
> ```cpp
>   DRAKE_DEMAND(plant.GetPositionUpperLimits().array().isFinite().all());
>   DRAKE_DEMAND(options.num_collision_infeasible_samples >= 0);
>   if (options.configuration_obstacles.size() > 0) {
> ```

this if statement is not needed.
___
*[`bindings/pydrake/geometry_py_optimization.cc` line 302 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFIzA8ICqLQcJz_Jb8g:-NFIzA8J3E0wyQpWc73_:b-b6ceje) ([raw file](https://github.com/robotlocomotion/drake/blob/a1465038d377838e5d41242cd6fde4b97d838d16/bindings/pydrake/geometry_py_optimization.cc#L302)):*
> ```cpp
>         .def_readwrite("configuration_obstacles",
>             &IrisOptions::configuration_obstacles,
>             cls_doc.configuration_obstacles.doc)
> ```

i think we lost prog_with_additional_constraints??

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.cc` line 616 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFIyORZ5g-G-QCUaKBh:-NFKe5Jk-_TZNloxWfZ3:b-iqoskt) ([raw file](https://github.com/robotlocomotion/drake/blob/a1465038d377838e5d41242cd6fde4b97d838d16/geometry/optimization/iris.cc#L616)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this if statement is not needed.
</blockquote></details>

Done. I think the other one (on line 774) is not strictly needed but it short circuits some checks that aren't needed so I'm leaving it.
___
*[`bindings/pydrake/geometry_py_optimization.cc` line 302 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFIzA8ICqLQcJz_Jb8g:-NFKeTIZC5WSBW1KGICP:bth05xf) ([raw file](https://github.com/robotlocomotion/drake/blob/a1465038d377838e5d41242cd6fde4b97d838d16/bindings/pydrake/geometry_py_optimization.cc#L302)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think we lost prog_with_additional_constraints??
</blockquote></details>

Nope. Moved it down (line 334) to bind a different way that handles the pointer better.  The old binding didn't protect the program from being garbage collected after being set in the options struct.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136#-:-NFKi0mBBIPKK_o9h9Wo:b-6xsumq)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @mpetersen94 and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a nit

> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136#-:-NFKxGpT60RYJpEsEaS7:bnzh7ut)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94)

___
*[`geometry/optimization/iris.cc` line 610 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFKutIM2PbB7lGFqiS8:-NFKutIM2PbB7lGFqiS9:brrxsg8) ([raw file](https://github.com/robotlocomotion/drake/blob/c39ceb6a91f46601166b55fd90b31f7f42972210/geometry/optimization/iris.cc#L610)):*
> ```cpp
>   const int nq = plant.num_positions();
>   const Eigen::VectorXd sample = plant.GetPositions(context);
>   const int Nc = static_cast<int>(options.configuration_obstacles.size());
> ```

nit: per styleguide this should start with a lower case letter. `nc` would be fine
___
*[`geometry/optimization/iris.cc` line 653 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFKvFYB38ZiTAb4kpaO:-NFKvFYCDdU5RHEJ3wyc:b-2n1tn1) ([raw file](https://github.com/robotlocomotion/drake/blob/c39ceb6a91f46601166b55fd90b31f7f42972210/geometry/optimization/iris.cc#L653)):*
> ```cpp
> 
>   auto pairs = inspector.GetCollisionCandidates();
>   const int N = static_cast<int>(pairs.size());
> ```

BTW this should be "n" but you don't have to change it since it is already in. But if you want to, please feel free!

**Review by mpetersen94 — COMMENTED** [review]
Added a check and a test to catch the case that the sample point is in a configuration_obstacles.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136#-:-NFPBgtn98mPjQsYPWnq:b-fdia6i)* status: missing label for release notes (waiting on @RussTedrake and @sherm1)

___
*[`geometry/optimization/iris.cc` line 610 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFKutIM2PbB7lGFqiS8:-NFP8Ii50t_-Y2P5weGP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c39ceb6a91f46601166b55fd90b31f7f42972210/geometry/optimization/iris.cc#L610)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per styleguide this should start with a lower case letter. `nc` would be fine
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 653 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18136#-NFKvFYB38ZiTAb4kpaO:-NFP8V9H2F8U-f9G_pZy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c39ceb6a91f46601166b55fd90b31f7f42972210/geometry/optimization/iris.cc#L653)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this should be "n" but you don't have to change it since it is already in. But if you want to, please feel free!
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18136)* status: missing label for release notes (waiting on @mpetersen94)

**Pull request merged**
