### PR TITLE
Add comments in symbolic_{expression,formula} noting exceptions to the style guide regarding hash-related operators.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
(Pending #6937, will remove *do not merge* once it has merged.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6992)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-:-KtYCsQ_J2a5bbQmbT65:blbs4su)*

**Comment by sherm1** [comment]
I'm glad you are adding these notes, @ericcousineau-tri, and platform :lgtm: for a clear improvement. But why does the symbolic code break this sensible rule? That seems like a recipe for future disaster.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-:-KtYGfOcw8ZVzhsyxFlO:b-6lsexg)*

**Comment by EricCousineau-TRI** [comment]
I think the main motivation is to provide syntax sugar for symbolic formulas via infix logical operators - which I think would be a pretty good case for an exception for usability.

Should we do some more work to figure out if / when these future disasters might happen? (e.g. trying to find when `operator==` would be used instead of `std::equal_to`, or `operator<` rather than `std::less`?)

If the disasters are avoidable with minimal workarounds, maybe it'd be better to keep them?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-:-KtYKw6mKV6LnpSQPgje:b-4c2yug)*

**Comment by sherm1** [comment]
Oh, that does seems like a nice feature. I think if `operator==` etc. have a non-bool return type, then using one where `std::equal_to` etc. should have been used would just cause a compilation failure and not a run time problem (which is what I meant by "disaster".) So I think this is OK. Thanks for the explanation.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-:-KtYXKfEqySsadvwVgCc:b-yydjs5)*

**Comment by soonho-tri** [comment]
:lgtm: @ericcousineau-tri , thanks a lot!!

@sherm1 : In most of the cases, both of `operator==` and `std::eqaul_to` should check structural equality. But in the case of `symbolic::Expression`, we want to use `operator==` to form `symbolic::Formula`, not just `bool`, as @ericcousineau-tri explained above.

`std::equal_to<Expression>` still checks structural equality because it's mostly used by C++ STL and that's what they expect. For example, `std::unordered_map<Expression>` should use structural equality for its members.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-:-KtaNvr4DO88W8TUiswk:b-7wg68h)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Comment by soonho-tri** [comment]
@EricCousineau-TRI , could you rebase this PR? The hash-append proposal was merged and I think this one is ready to go.

**Comment by EricCousineau-TRI** [comment]
Done - thanks for pointing that out!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-:-L26IfCemrkIu_CgIXw7:biuu2xs)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/symbolic_expression.h, line 171 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6992#-L26Jsa_PqscGAliU3Al:-L26Jsa_PqscGAliU3Am:bk7dakc) ([raw file](https://github.com/robotlocomotion/drake/blob/0a68d1ab2186c66d74481c38d94be512ea870a99/common/symbolic_expression.h#L171)):*
> ```objc
> Expression::Less (called by std::less<Expression>) are provided.
> 
> @note This is an exception to the style guide, which states that hash-related
> ```

"... hash-related operations should perform compatible comparison ..." part was in the Maddog 's original proposal but not included in the current guide, http://drake.mit.edu/styleguide/cppguide.html#std_hash. I think it's good enough to close this PR unless you want to update the Drake C++ guide. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6992)*

**Comment by EricCousineau-TRI** [comment]
True. Will go ahead and close this out. Thanks!

**Pull request closed without merging**
