### PR TITLE
Move into tools/lint our linter support 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  The full WIP branch is https://github.com/jwnimmer-tri/drake/tree/build-drake-folder-6996.

See commit message for details.  Note that the first commit is human-written, and the second commit is perl pie.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7210)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review per rotation, please.  (If you think we should also feature review separately, just ping me.)

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 25 files at r1.
Review status: 1 of 122 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 396 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7210#-KvnIY_kmBOKcvfBMKbv:-KvnIY_kmBOKcvfBMKbw:b-q7ll20) ([raw file](https://github.com/robotlocomotion/drake/blob/82221ee44abd5cfc864b1ef947a652da2249ed54/drake/doc/clion.rst#L396)):*
> ```reStructuredText
>   :Description: ``Apply drake lint to the current file``
>   :Program: ``bazel``
>   :Parameters: ``run //tools:drakelint -- $FilePath$``
> ```

FYI I can always rely on you to catch the final detail. Thanks for including this. :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7210)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 25 of 25 files at r1.
Review status: 17 of 122 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lint.bzl, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7210#-KvnITjcVWEBBc26mH3u:-KvnITjcVWEBBc26mH3v:b-d0i8kw) ([raw file](https://github.com/robotlocomotion/drake/blob/adca792922d8e112781d24aad1a95401d6883807/tools/lint.bzl#L3)):*
> ```Python
> # -*- python -*-
> 
> # This file is a compatibility shim, to easy porting to our new filename.
> ```

FYI typo "to easy"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7210#-:-KvnIopibiCf2aUOy460:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 105 of 105 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7210)*

**Comment by jwnimmer-tri** [comment]
I'll self-approve the :car: review, since it was entirely perl pie.

**Pull request merged**
