### PR TITLE
pydrake rbt: Add bindings for positionConstraints and centerOfMassJacobianDotTimesV methods

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9026)

### CODE REVIEW

**Comment by mpetersen94** [comment]
+@EricCousineau-TRI for feature review, please.

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor requests on styling / esoteric ordering.

---

Reviewed 3 of 3 files at r1.
Review status: 5 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 179 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPZN4V3p_kQtGg0Tms:-LFPZN4V3p_kQtGg0Tmt:b-wpy3gl) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L179)):*
> ```cpp
>     .def("__copy__", &RigidBodyTree<double>::Clone);
> 
>   // This lambda defines RigidBodyTree methods which are defined for a given
> ```

FYI This (admittedly esoteric) comment defines the order in which things should be defined here for consistency, since we're trying to sync up explicit template instantiations with Python bindings.

(No call to action in this discussion; the following comments point out what to actually change.)

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPZtQB1s6JkKa8bKHp:-LFPZtQC-K7tYvaVR62Z:b-9spx9i) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L247)):*
> ```cpp
>              RigidBodyTreeConstants::default_model_instance_id_set,
>            py::arg("in_terms_of_qdot") = false)
>       .def("centerOfMassJacobianDotTimesV",
> ```

Would you be able to move this back below `geometricJacobianDotTimesV`? (just so it follows the instantiation ordering in `rigid_body_tree.cc`)

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 256 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPZBvo7dFvwLerGhhw:-LFPZBvpAWnTGsaWXy1A:b-8uz4yc) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L256)):*
> ```cpp
>       // geometricJacobianDotTimesV
>       // centroidalMomentumMatrixDotTimesV
>       .def("addDistanceConstraint",
> ```

`addDistanceConstraint` appears to be a type (b) binding (see my esoteric comment above about type (a) vs. type (b) methods).

Could you place it in that section?

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 273 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPYcDs9S6XSQ6phyBT:-LFPYcDs9S6XSQ6phyBU:b-9b274r) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L273)):*
> ```cpp
>            &RigidBodyTree<double>::positionConstraintsJacDotTimesV<T>,
>            py::arg("cache"))
>       .def("getNumPositionConstraints",
> ```

`getNumPositionConstraints` does not seem like a scalar-type dependent method - would you be able to move this below something like `FindBaseBodies`? (no defined order there)

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFP_j-R74nFFQBFlJAD:-LFP_j-T7Q8uWXl2B7vz:blkg7ku) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L184)):*
> ```Python
>         kinsol_ad = tree.doKinematics(q_ad, v_ad)
> 
>         self.assertEqual(tree.getNumPositionConstraints(), num_con-1)
> ```

Can you insert spaces into `num_con - 1`?
https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFP_8cw1rmidpaaaWHW:-LFP_8cw1rmidpaaaWHX:b-199rxx) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L195)):*
> ```Python
>         JdotV_ad = tree.positionConstraintsJacDotTimesV(kinsol_ad)
> 
>         self.assertEqual(constraint.shape, (num_con, ))
> ```

Would you be OK with removing the trailing space for this and other single-item tuples? `(x, )` -> `(x,)`
https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9026#-:-LFP_qS5EBSsBhiNSUAL:b-3i637m)*

**Comment by mpetersen94** [comment]
Review status: 5 unresolved discussions, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPZtQB1s6JkKa8bKHp:-LFPwJoqCTAy4fSOpe_i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L247)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would you be able to move this back below `geometricJacobianDotTimesV`? (just so it follows the instantiation ordering in `rigid_body_tree.cc`)
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 256 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPZBvo7dFvwLerGhhw:-LFPwKnr2QVgzdsY3W3A:bnrsc6z) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L256)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`addDistanceConstraint` appears to be a type (b) binding (see my esoteric comment above about type (a) vs. type (b) methods).

Could you place it in that section?
</blockquote></details>

Actually reading the comment, I don't think it is a type (a) or (b) binding.  I've moved it up with `getNumPositionConstraints`.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 273 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFPYcDs9S6XSQ6phyBT:-LFPwYm-6qLFACnGNIe9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/rigid_body_tree_py.cc#L273)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`getNumPositionConstraints` does not seem like a scalar-type dependent method - would you be able to move this below something like `FindBaseBodies`? (no defined order there)
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFP_j-R74nFFQBFlJAD:-LFPweXt78hlUZLg8zwH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L184)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you insert spaces into `num_con - 1`?
https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFP_8cw1rmidpaaaWHW:-LFPwfN40zTefeCZCLfh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9cc1c51b247e8a7e56bebef9080b40355d82588e/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L195)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would you be OK with removing the trailing space for this and other single-item tuples? `(x, )` -> `(x,)`
https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9026)*

**Comment by EricCousineau-TRI** [comment]
Thanks!

+@sammy-tri for platform review, please.

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9026#-:-LFScXAx6Jj3qpN0JXiM:blktcsh)*

**Comment by mpetersen94** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, platform LGTM from [ericcousineau-tri]

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 271 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9026#-LFT7KvE-R6ktkFjhGOF:-LFTjCeB-Z0CZgyB-SC0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/910e03869efd0530f2357c7eb73d0f2551a73038/bindings/pydrake/multibody/rigid_body_tree_py.cc#L271)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This is the opposite of the default value for `in_terms_of_qdot` in `rigid_body_tree.h`.  I'm concerned this could produce confusing behavior for code which looks the same in python and c++?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9026)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri, sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9026#-:-LFTwI270bAtIZx224DQ:bnfp4nl)*

**Pull request merged**
