### PR TITLE
Add tolerance to rotation_constraint_test TestRpyLimits

### LINKED ISSUE #17915: macOS m1 CI failure in solvers/rotation_constraint_test
Relates #17869, CC @jwnimmer-tri and via blame @RussTedrake 

https://github.com/RobotLocomotion/drake/blob/7cf6c542f0779eadd72eb2b608143d0b3a057323/solvers/test/rotation_constraint_test.cc#L90

```
[12:17:02 PM]  [ RUN      ] RotationTest/TestRpyLimitsFixture.TestRpyLimits/3
[12:17:02 PM]  solvers/test/rotation_constraint_test.cc:90: Failure
[12:17:02 PM]  Expected: (x(i)) <= (ub(i)), actual: 1 vs 1
[12:17:02 PM]  solvers/test/rotation_constraint_test.cc:90: Failure
[12:17:02 PM]  Expected: (x(i)) <= (ub(i)), actual: 1 vs 1
[12:17:02 PM]  solvers/test/rotation_constraint_test.cc:90: Failure
[12:17:02 PM]  Expected: (x(i)) <= (ub(i)), actual: 1 vs 1
[12:17:02 PM]  solvers/test/rotation_constraint_test.cc:90: Failure
[12:17:02 PM]  Expected: (x(i)) <= (ub(i)), actual: 1 vs 1
[12:17:02 PM]  [  FAILED  ] RotationTest/TestRpyLimitsFixture.TestRpyLimits/3, where GetParam() = 8 (12 ms)
```

Full [build log here](https://drake-jenkins.csail.mit.edu/job/mac-m1-monterey-provisioned-clang-bazel-experimental-everything-debug/2/consoleFull), nothing obvious sticks out to me but this is preventing `@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-everything-debug please.` from success.  1 vs 1 not satisfying less than or equal is ... strange.

### PR DESCRIPTION
**Pull request by svenevs**
Fixes #17915.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17998)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-everything-debug please.

**Review by svenevs — COMMENTED** [review]
+@jwnimmer-tri for feature review or delegation please.  This indeed completes the m1 `everything-debug` builds :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17998#-:-ND9Z-883zZik_5CrM6N:b1fridv)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) +(release notes: none) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17998#-:-ND9wFY_ARJ6xv9Z9eYR:b4kzx7q)* status: 1 unresolved discussion (waiting on @svenevs)

___
*[`solvers/test/rotation_constraint_test.cc` line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17998#-ND9w1VsDSTbrysjSlbJ:-ND9w1Vt85-_g5Ff4kFN:b-y1oxln) ([raw file](https://github.com/robotlocomotion/drake/blob/483e6a025a033d317dadccf80ac8cb5abd1a578c/solvers/test/rotation_constraint_test.cc#L91)):*
> ```cpp
>               constexpr double threshold = 1e-15;
>               EXPECT_GE(x(i) + threshold, lb(i));
>               EXPECT_LE(x(i) - threshold, ub(i));
> ```

nit To my eye at least, the tolerance makes more sense applied to the limit than to the measured value.  WDYT?



_Suggestion:_
```cpp
              constexpr double threshold = 1e-15;
              EXPECT_GE(x(i), lb(i) - threshold);
              EXPECT_LE(x(i), ub(i) + threshold);
```

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-everything-debug please.

For good measure and lack of urgency.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17998)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`solvers/test/rotation_constraint_test.cc` line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17998#-ND9w1VsDSTbrysjSlbJ:-NDACmtf7_GWxi2uAEXt:b-ui3kz5) ([raw file](https://github.com/robotlocomotion/drake/blob/483e6a025a033d317dadccf80ac8cb5abd1a578c/solvers/test/rotation_constraint_test.cc#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit To my eye at least, the tolerance makes more sense applied to the limit than to the measured value.  WDYT?
</blockquote></details>

OK, works for me -- fixed!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17998)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @svenevs)

**Pull request merged**
