### PR TITLE
pydrake: Replace "System YAML" with proper ".. pydrake_system::" directive

### LINKED ISSUE #12590: implement system diagrams for pydrake documentation
The nice html diagrams that we have for doxygen result in a totally scare mess for pydrake users.  
For example:
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html
vs 
https://drake.mit.edu/pydrake/pydrake.multibody.plant.html#pydrake.multibody.plant.MultibodyPlant_

The doxygen code for this is just a very simple set of (recursive) aliases here:
https://github.com/RobotLocomotion/drake/blob/master/doc/Doxyfile_CXX.in#L43

Presumably we could write a simple script that does this work somewhere around `generate_pybind_documentation_header`?

Also, note that we occasionally use html tags in our doxygen (including the multibodyplant example above) which, left unrendered, is not only messy but makes it impossible to parse ideas like "the green output ports do X".  Is there a better way for sphinx to handle those html tags?

Note: we regularly receive feedback (e.g. from students) that the pydrake documentation needs a lot of work.  I'll try to open some issues for ideas of possible "low hanging fruit" that might go a long way to improving that experience.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #12590

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14915)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for both reviews, please!

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14915#-:-MYV5pMfCMislL5X1AM-:b-iiiifa)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Comment by EricCousineau-TRI** [comment]
Pics or it didn't happen!
```
$ git log -n 1 --oneline --no-decorate
11b7e16928 pydrake: Replace "System YAML" with proper ".. pydrake_system::" directive
$ bazel run //doc/pydrake:build -- --serve pydrake.manipulation.simple_ui
$ firefox http://127.0.0.1:8000/pydrake/pydrake.manipulation.simple_ui.html
```
> image

**Review by RussTedrake — COMMENTED** [review]
THanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14915#-:-MYVFjAW5jTS2F9dMmoK:bpj8kpf)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14915#-:-MYVFkuu2mGWYjAMP6aY:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Pull request merged**
