### PR TITLE
Add cylinder to geometry world

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Adds the cylinder shape to the set of supported shapes.

Adds cylinders to `solar_system.cc` to illustrate the usage.

```
Category            added  modified  removed  
----------------------------------------------
code                70     11        1        
comments            20     3         1        
blank               10     0         0        
----------------------------------------------
TOTAL               100    14        2  
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7163)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@amcastro-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-:-KvTsEImhn3Fsjhzf1wM:b5xll3r)*

**Comment by amcastro-tri** [comment]
Excellent, just a few BTW and questions. :lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/geometry_world/solar_system.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXSgiG87C_8GvHL8Ss:-KvXSgiG87C_8GvHL8St:b-nrszh5) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/examples/geometry_world/solar_system.cc#L96)):*
> ```cpp
> //   x = 0                │
> //   ↓                    │ height
> //   ─────────────────────┘          ← z = 0
> ```

BTW, you would need to add a little sphere at the corners to "smooth them out", :-)

---

*[drake/geometry/geometry_visualization.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXXABlOfNTnUXRV5f8:-KvXXABlOfNTnUXRV5f9:bx1dh9y) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/geometry_visualization.cc#L44)):*
> ```cpp
>     position = X_PG_.translation().cast<float>();
>     // LCM quaternion must be w, x, y, z.
>     Eigen::Quaternion<double> q(X_PG_.rotation());
> ```

It must be `.linear()`

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvXVG1p3jrhuMQpEMTO:b-hqjaab) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
> ```cpp
> 
> Cylinder::Cylinder(double radius, double length)
>     : Shape(static_cast<Cylinder*>(nullptr)),
> ```

if this is only used to simulate some sort of runtime CRTP, why not to pass `*this` (and thus no ugly `static_cast`) or even use a mechanism like the `SystemTypeTag`? you could have in `shape_specification.h` your own little struct `GeometryTypeTag`. 

---

*[drake/geometry/shape_specification.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXT_0SSqYoWsC7tFzl:-KvXT_0TV15EEm5ANEWq:burwirn) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.h#L45)):*
> ```objc
> 
>   /** Constructor available for derived class construction. A derived class
>    should provide invoke this in its initialization list, passing a `nullptr`
> ```

BTW, provide/invoke, choose one.

---

*[drake/geometry/shape_specification.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXU4CecIue2qZJc7TV:-KvXU4CecIue2qZJc7TW:b-vnmz0x) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.h#L64)):*
> ```objc
>      3. their constructors must invoke the parent constructor with a nullptr
>         cast as their type (as noted above), and
>      4. The ShapeReifier class must be extended to include a an invocation of
> ```

BTW, a an --> an

---

*[drake/geometry/shape_specification.h, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXT2i9rUSX3f6pyN-S:-KvXT2i9rUSX3f6pyN-T:b-vxurz2) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.h#L96)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Cylinder)
> 
>   explicit Cylinder(double radius, double length);
> ```

BTW, `explicit` not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-:-KvXYQKCqseG3BJMxJRb:b-bwpdg1)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for catching my copy pasta

---

Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/geometry_world/solar_system.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXSgiG87C_8GvHL8Ss:-KvXfD15vySku9nfelk5:b-qo188d) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/examples/geometry_world/solar_system.cc#L96)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, you would need to add a little sphere at the corners to "smooth them out", :-)
</blockquote></details>

OK Left as an exercise for the reader. :)

---

*[drake/geometry/geometry_visualization.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXXABlOfNTnUXRV5f8:-KvXfUjFuRzY5YExFceg:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/geometry_visualization.cc#L44)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It must be `.linear()`
</blockquote></details>

Done

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvXfpJk6lUaI5blDduZ:b-51hjt1) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

if this is only used to simulate some sort of runtime CRTP, why not to pass `*this` (and thus no ugly `static_cast`) or even use a mechanism like the `SystemTypeTag`? you could have in `shape_specification.h` your own little struct `GeometryTypeTag`. 
</blockquote></details>

Your instinct is correct. And your argument is persuasive. I've added the `ShapeTag` to facilitate the fun and games.

(BTW You can't pass `*this`, because it doesn't exist yet.)

---

*[drake/geometry/shape_specification.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXT_0SSqYoWsC7tFzl:-KvXgLdapjq-tufkbNTw:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.h#L45)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, provide/invoke, choose one.
</blockquote></details>

Done

---

*[drake/geometry/shape_specification.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXU4CecIue2qZJc7TV:-KvXgPvoqskPVIbTX_d7:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.h#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, a an --> an
</blockquote></details>

Done

---

*[drake/geometry/shape_specification.h, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXT2i9rUSX3f6pyN-S:-KvXgS9C3irmU4QZC_Xe:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.h#L96)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, `explicit` not needed
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-:-KvXgU-ezlasaxAI-3jZ:b-tt7254)*

**Comment by amcastro-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvXsensaNYIl7zSutBF:b1vhg9m) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
>  because it doesn't exist yet

wow, I didn't know that. I knew it was not entirely formed yet (like for instance calling a virtual method during construction is a really bad idea!), but I thought `this` existed already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvXuTHnDL4HmCErl54x:b-prj75b) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

>  because it doesn't exist yet

wow, I didn't know that. I knew it was not entirely formed yet (like for instance calling a virtual method during construction is a really bad idea!), but I thought `this` existed already.
</blockquote></details>

Another point of trivia: try doing a `static_assert` inside the constructor on a property of the *type* of the class.  You can't do that either; the class doesn't exist, either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by amcastro-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvY4Gj7YBjRuixZZ4Pa:b-5c9gu0) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Another point of trivia: try doing a `static_assert` inside the constructor on a property of the *type* of the class.  You can't do that either; the class doesn't exist, either.
</blockquote></details>

Good to know. Good thing the compiler doesn't even let you mess with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by sherm1** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvY50WJtpg9gXOot21c:bpljcl) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Good to know. Good thing the compiler doesn't even let you mess with that.
</blockquote></details>

FYI per f2f w/Sean: you can actually use `this` in an initializer list (don't look inside it though!). But in this case what Sean needs is the type. `decltype(*this)` is one way to get that that doesn't involve run time dependence on the not-yet-constructed object (since decltype doesn't evaluate its expression).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvY5qSGJVQhYxZWdAgs:b-3d5yi0) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI per f2f w/Sean: you can actually use `this` in an initializer list (don't look inside it though!). But in this case what Sean needs is the type. `decltype(*this)` is one way to get that that doesn't involve run time dependence on the not-yet-constructed object (since decltype doesn't evaluate its expression).
</blockquote></details>

Yep. I retract my statement, entirely. The pointer is *definitely* available.

So, one alternative would be:

```C++
Cylinder::Cylinder(double radius, double length) : Shape<decltype(*this)>() {}
```

I believe no further qualifier manipulation would be required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by SeanCurtis-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-:-KvYqQAWkumOM3TPra8r:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm: with a couple small comment nits

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/geometry_world/solar_system.cc, line 91 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvYv2td3Ixr98N9retT:-KvYv2teZ7r2oG0gFRwP:bc7c932) ([raw file](https://github.com/robotlocomotion/drake/blob/19db5c1e30864f66bf3f290f2cc5938851ec5106/drake/examples/geometry_world/solar_system.cc#L91)):*
> ```cpp
> }
> 
> // Registers geometry to form an L-shaped arm onto the given frame. The arm is
> ```

Dangling comment test "the arm is"?

---

*[drake/examples/geometry_world/solar_system.cc, line 107 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvYvBZwz-OSqttZiTxB:-KvYvBZwz-OSqttZiTxC:b8v9o8r) ([raw file](https://github.com/robotlocomotion/drake/blob/19db5c1e30864f66bf3f290f2cc5938851ec5106/drake/examples/geometry_world/solar_system.cc#L107)):*
> ```cpp
>              double height, double radius,
>              GeometrySystem<double>* geometry_system) {
>   // The posts for the orrery a horizontal post and a vertical post.
> ```

Is this sentence missing a verb?

---

*[drake/geometry/shape_specification.h, line 108 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvYtLkCB8dudWBgVxEf:-KvYtLkCB8dudWBgVxEg:baio6zy) ([raw file](https://github.com/robotlocomotion/drake/blob/19db5c1e30864f66bf3f290f2cc5938851ec5106/drake/geometry/shape_specification.h#L108)):*
> ```objc
> 
>  private:
>   double radius_{};
> ```

BTW Would it be more informative to mark these `const`?  Or do we imagine a situation where the dimensions might change after construction? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-:-KvYvgAbTvOaB3l-MF85:b-taej5i)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/geometry/shape_specification.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvXVG1p3jrhuMQpEMTN:-KvYybRq_IacsN_UvrZQ:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/c815aecef778b55868438a61c31aaa046e6c3cf0/drake/geometry/shape_specification.cc#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Yep. I retract my statement, entirely. The pointer is *definitely* available.

So, one alternative would be:

```C++
Cylinder::Cylinder(double radius, double length) : Shape<decltype(*this)>() {}
```

I believe no further qualifier manipulation would be required.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Comment by SeanCurtis-TRI** [comment]
@sherm1 I believe you're blocking on this PR.

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-:-KvYyoPY8xQT43GUCi0S:bl0xzk3)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/geometry/shape_specification.h, line 108 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7163#-KvYtLkCB8dudWBgVxEf:-KvYyn2IYKisjeNGnd0W:bm1zzbu) ([raw file](https://github.com/robotlocomotion/drake/blob/19db5c1e30864f66bf3f290f2cc5938851ec5106/drake/geometry/shape_specification.h#L108)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The problem is that I can no longer use `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN`. And if I want it copyable, I can't use `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`. So, I have two options; 1) explicitly handle them all myself (deleting everything except the copy constructor), or 2) this.

Preference?
</blockquote></details>

This is better than the alternative.  Thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7163)*

**Pull request merged**
