### PR TITLE
Tidy up a few Cars nits

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3386)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
DNR until Jenkins decides is win32 is a good idea or not.

**Comment by jwnimmer-tri** [comment]
Well, I can't get windows dll hocus-pocus correct, so I'm going to rebase back into the nerfed build again.  Hello again my old friend #2501.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for both reviews, please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3386#-:-KR9OX8r7s9UT257sGGQ:bnfp4nl)*

**Pull request merged**
