### PR TITLE
Report "buildifier is needed" errors more directly

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This got broken when we upgraded our buildifier version in #7200.

Relates #7271.  I will leave that issue open until we have a regression test, though.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7272)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7272#-:-Kwbk4dysXWqj1muvYhz:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm: (tested locally on an :apple: )

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7272#-:-KwbmU6qHvnEbxYS8X8Z:b-u70fcd)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per rotation, please.

**Comment by soonho-tri** [comment]
Is the CI failure expected one?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7272#-:-KweejvZmEgq64rRSXVt:b-8ih0jz)*

**Comment by jwnimmer-tri** [comment]
The CI error is a Maven download flake.  I'm going to wait for any new review feedback before worrying about it.

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7272#-:-KwetgPdUaqfadBOJgkL:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Using override-merge for maven flake.

**Pull request merged**
