### PR TITLE
[yaml] Update performance test to use internal nodes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Refer to #12830 for overall background on this test program.

The parsing change in this PR captures the intended usage pattern going forward (where we parse the document data ourselves, instead of having the user hand us a jbeder/yaml-cpp node that has already been parsed).

Towards #15868.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16050)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16050)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[common/yaml/test/yaml_performance_test.cc, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16050#-Mnko2xL-1EeU9Atzye6:-Mnko2xL-1EeU9Atzye7:bgq2hrj) ([raw file](https://github.com/robotlocomotion/drake/blob/256eb982529621309752206621e1410c3d0fc54c/common/yaml/test/yaml_performance_test.cc#L10)):*
> ```cpp
> #include "drake/common/test_utilities/limit_malloc.h"
> #include "drake/common/yaml/yaml_io.h"
> #include "drake/common/yaml/yaml_read_archive.h"
> ```

Isn't this the source of YamlReadArchive, which is still used?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16050)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[common/yaml/test/yaml_performance_test.cc, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16050#-Mnko2xL-1EeU9Atzye6:-MnlBSVi3v-fFHqtgenZ:b9mj9sd) ([raw file](https://github.com/robotlocomotion/drake/blob/256eb982529621309752206621e1410c3d0fc54c/common/yaml/test/yaml_performance_test.cc#L10)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Isn't this the source of YamlReadArchive, which is still used?
</blockquote></details>

Right.  I had been thinking of yaml_io as a module header and that nobody should use the fine-grained includes anymore (and it's not a GSG defect to omit them).  However, for the module's unit tests the fine-grained includes probably still make sense.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16050#-:-MnlMgpl5KYzl2W9PVqq:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
