### PR TITLE
adds a test method for checking matrix equality up to a permutation

### PR DESCRIPTION
**Pull request by RussTedrake**
(which I've found myself needing when checking symmetry of a mesh, and in a number of test files).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4788)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sherm1 for platform and feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-:-KaZyT5bSWpbhAD7pXWB:bqk2zc1)*

**Comment by RussTedrake** [comment]
fyi - the failed test looks like a CI flake (is certainly unrelated to this change).

**Comment by sherm1** [comment]
:lgtm: after a few documentation changes.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/is_approx_equal_abstol.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacDkYMWFU_q8L3F_iV:-KacDkYMWFU_q8L3F_iW:b-u6h7pc) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/is_approx_equal_abstol.h#L26)):*
> ```objc
> /// Returns true if and only if the two matrices are equal to within a certain
> /// absolute elementwise @p tolerance, given a permutation of the columns, e.g.
> /// there exists a P such that
> ```

BTW, this statement seems too strong. In marginal cases (with similar but not identical columns) I believe this algorithm can fail to find a permutation P even if it exists because it accepts the first column match (m1(i),m2(j)) and removes m2(j) from the pool. It is possible that other columns of m2 would also match m1(i) but that m2(j) is the only match possible for a later column of m1. 

I suggest changing the comment rather than the code because I think it is likely very useful as-is and that a complete fix would be very expensive.

---

*[drake/common/is_approx_equal_abstol.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacCJLIQy5-aR4mzpQT:-KacCJLIQy5-aR4mzpQU:b-wbps8q) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/is_approx_equal_abstol.h#L32)):*
> ```objc
> ///       P(i,j)={0,1}, sum_i P(i,j)=1, sum_j P(i,j)=1.
> /// </pre>
> /// Note: The current implementation is O(N^2) in the number of columns.
> ```

BTW, consider whether non-conformant matrices should be considered an error rather than simply not equal -- I'm guessing that's likely to be a user error. Either way the method comment should say how those are treated.

---

*[drake/common/is_approx_equal_abstol.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacDOJQ6JJFkBH3aXs6:-KacDOJQ6JJFkBH3aXs7:bwtdkz4) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/is_approx_equal_abstol.h#L43)):*
> ```objc
> 
>   for (int i = 0; i < m1.cols(); i++) {
>     bool found_unique_match = false;
> ```

BTW, this doesn't seem to be unique. Consider just `found _match`.

---

*[drake/common/test/is_approx_equal_abstol_test.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacHhDqWsDoSrGcKx_f:-KacHhDqWsDoSrGcKx_g:bns26ub) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/test/is_approx_equal_abstol_test.cc#L62)):*
> ```cpp
> GTEST_TEST(IsApproxEqualAbstolPermutationTest, PermutationTest) {
>   MatrixXd test(2, 3);
>   test << 1, 2, 3, 4, 5, 6;
> ```

BTW, consider formatting these like
```c++
test << 1, 2, 3,
        4, 5, 6;
```
for easier interpretation by harried reviewers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-:-KacIjxZyiK88XArM5Qy:b-xyhrp)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/is_approx_equal_abstol.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacDkYMWFU_q8L3F_iV:-KadA0mTfD56KIgPcAzg:byyvgic) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/is_approx_equal_abstol.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this statement seems too strong. In marginal cases (with similar but not identical columns) I believe this algorithm can fail to find a permutation P even if it exists because it accepts the first column match (m1(i),m2(j)) and removes m2(j) from the pool. It is possible that other columns of m2 would also match m1(i) but that m2(j) is the only match possible for a later column of m1. 

I suggest changing the comment rather than the code because I think it is likely very useful as-is and that a complete fix would be very expensive.
</blockquote></details>

Wow.  Nice catch.  I've updated the comment.

---

*[drake/common/is_approx_equal_abstol.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacCJLIQy5-aR4mzpQT:-KadKJL_4CF9MqMH3PEZ:bszcm0q) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/is_approx_equal_abstol.h#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, consider whether non-conformant matrices should be considered an error rather than simply not equal -- I'm guessing that's likely to be a user error. Either way the method comment should say how those are treated.
</blockquote></details>

I prefer to match the implementation of the non-permutation above. Added to the doc.

---

*[drake/common/is_approx_equal_abstol.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacDOJQ6JJFkBH3aXs6:-KadKHmFUNWr4zmf4XRL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/is_approx_equal_abstol.h#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this doesn't seem to be unique. Consider just `found _match`.
</blockquote></details>

Done.

---

*[drake/common/test/is_approx_equal_abstol_test.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacHhDqWsDoSrGcKx_f:-KadAAI0hl6gM3hhX1FJ:b233m1h) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/test/is_approx_equal_abstol_test.cc#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, consider formatting these like
```c++
test << 1, 2, 3,
        4, 5, 6;
```
for easier interpretation by harried reviewers.
</blockquote></details>

it was.  clang-format put it back.  :)  will win the fight.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4788)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4788)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/test/is_approx_equal_abstol_test.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4788#-KacHhDqWsDoSrGcKx_f:-Kadc7yhJsc77XtqWvuy:b60xd9b) ([raw file](https://github.com/robotlocomotion/drake/blob/43c08176a20bc49c88851fbf34927b3ba5de88ee/drake/common/test/is_approx_equal_abstol_test.cc#L62)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it was.  clang-format put it back.  :)  will win the fight.
</blockquote></details>

FYI We are working documenting an allowance for just saying `// BR` at end-of-line on the first line here, for single-line fixups like this; its less mouthy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4788)*

**Pull request merged**
