### PR TITLE
Add floor/ceil to symbolic::Expression

### LINKED ISSUE #6554: Add ceil/floor in symbolic::Expression
/cc @jwnimmer-tri

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #6554.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6564)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , feature-review please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-:-Kou7ptIlCvmsMKY3-6q:b8y8nlm)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 1755 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-Kow3Nt_fmd8_VNY_vU5:-Kow3Nt_fmd8_VNY_vU6:bm6xing) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e0f86d0cc60744b49ce3636fa3025226bc4470/drake/common/symbolic_expression_cell.cc#L1755)):*
> ```cpp
>   if (GetVariables().include(x)) {
>     ostringstream oss;
>     Display(oss) << "is not differentiable with respect to " << x << ".";
> ```

BTW Missing (printed) whitespace before "is".

Ditto above.

---

*[drake/common/symbolic_expression_cell.h, line 707 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-Kow24mSuhjQQo3ZtoJa:-Kow24mTnPDjBTOrnxmZ:b-4m8b8y) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e0f86d0cc60744b49ce3636fa3025226bc4470/drake/common/symbolic_expression_cell.h#L707)):*
> ```objc
> 
> /** Symbolic expression representing ceil function. */
> class ExpressionCeil : public UnaryExpressionCell {
> ```

OK This is clearly the correct classname, but `ExpressionCell` vs `ExpressionCeil` similarity is unfortunate.

---

*[drake/common/test/symbolic_expression_test.cc, line 1676 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-Kow0AxE2NtVaScb0eVC:-Kow0AxFAW8P7GtHXBd2:bic5xi7) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e0f86d0cc60744b49ce3636fa3025226bc4470/drake/common/test/symbolic_expression_test.cc#L1676)):*
> ```cpp
> 
> TEST_F(SymbolicExpressionTest, Ceil) {
>   EXPECT_DOUBLE_EQ(ceil(pi_).Evaluate(), std::ceil(3.141592));
> ```

FYI It's slightly weird to me as a reader here that the value of `pi_` is not `M_PI` but rather some small-digit approximation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-:-KowEgOYbDk3ttBwpl4q:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 1755 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-Kow3Nt_fmd8_VNY_vU5:-KowLv_gpf6HkYX5PwK-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e0f86d0cc60744b49ce3636fa3025226bc4470/drake/common/symbolic_expression_cell.cc#L1755)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Missing (printed) whitespace before "is".

Ditto above.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.h, line 707 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-Kow24mSuhjQQo3ZtoJa:-KowLxBnHG175k6hevok:bq774e0) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e0f86d0cc60744b49ce3636fa3025226bc4470/drake/common/symbolic_expression_cell.h#L707)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK This is clearly the correct classname, but `ExpressionCell` vs `ExpressionCeil` similarity is unfortunate.
</blockquote></details>

Done. (Changed to `ExpressionCeiling`)

---

*[drake/common/test/symbolic_expression_test.cc, line 1676 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-Kow0AxE2NtVaScb0eVC:-KowM_DHWfrN_1ICh0W-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e0f86d0cc60744b49ce3636fa3025226bc4470/drake/common/test/symbolic_expression_test.cc#L1676)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It's slightly weird to me as a reader here that the value of `pi_` is not `M_PI` but rather some small-digit approximation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-KowVB3uQndrnuQ4mavq:-KowVB3uQndrnuQ4mavr:b-e8rvdi) (no related file):*
Needs a second reviewer assigned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564)*

**Comment by soonho-tri** [comment]
+@nikos-tri , could you feature-review it? CAM people are busy this week.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-:-KowWJocMJdqe2jlyzjS:bs36nck)*

**Comment by nikos-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-:-Kowl_YS86fbtDZ4oopt:bnfp4nl)*

**Comment by soonho-tri** [comment]
Thanks for all the reviews!!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6564#-:-KowqR59BCup8_3UhuQO:b-kfx2gs)*

**Pull request merged**
