### PR TITLE
Compute a polynomial from monomial basis and the lower triangular of the Gram.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is useful in Sum-of-Squares optimization.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429#-:-NIuTeNBAKJPNK9RMpon:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
-@jwnimmer-tri for review, I forgot you are on vacation.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429#-:-NIx05N90909t_lWtPtr:b-8q11yt)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic/polynomial.h` line 586 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NIx1gTlCRCfzNeSWpcg:-NIx1gTlCRCfzNeSWpch:bhzo6kv) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5385c1189c3660068c7d5f4031dffa1254b144/common/symbolic/polynomial.h#L586)):*
> ```objc
> 
> /**
>  Compute the polynomial as m(x)ᵀ * Q * m(x), where m(x) is the monomial basis,
> ```

How about "Returns the polynomial m(x)^T Q m(x).."
___
*[`common/symbolic/polynomial.h` line 589 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NIx1Qw4AeEbjnDDoW-g:-NIx1Qw4AeEbjnDDoW-h:bg0br4h) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5385c1189c3660068c7d5f4031dffa1254b144/common/symbolic/polynomial.h#L589)):*
> ```objc
>  and Q is the Gram matrix.
>  @param monomial_basis m(x) in the documentation. A vector of monomials
>  @pagram gram_lower Stacking each column of the lower triangular entries in Q
> ```

stacking is a verb.  perhaps you can clean up the grammar here? 

maybe "the lower triangular entries in Q, stacked columnwise into a vector"?
___
*[`common/symbolic/polynomial.h` line 602 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NIx22pD4FakbVwkYLP2:-NIx22pD4FakbVwkYLP3:b-vp2h71) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5385c1189c3660068c7d5f4031dffa1254b144/common/symbolic/polynomial.h#L602)):*
> ```objc
>                          const Eigen::MatrixBase<Derived2>& gram_lower) {
>   DRAKE_DEMAND(monomial_basis.rows() * (monomial_basis.rows() + 1) / 2 ==
>                gram_lower.rows());
> ```

demand that cols==1 for both arguments?  (or even cleaner to static assert, since it seems like you'd only ever want vectors passed in)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`common/symbolic/polynomial.h` line 586 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NIx1gTlCRCfzNeSWpcg:-NIxBHzc742hZQMlxl9T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5385c1189c3660068c7d5f4031dffa1254b144/common/symbolic/polynomial.h#L586)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

How about "Returns the polynomial m(x)^T Q m(x).."
</blockquote></details>

Done.
___
*[`common/symbolic/polynomial.h` line 589 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NIx1Qw4AeEbjnDDoW-g:-NIxBDiL3a88P9vGy9kN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5385c1189c3660068c7d5f4031dffa1254b144/common/symbolic/polynomial.h#L589)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

stacking is a verb.  perhaps you can clean up the grammar here? 

maybe "the lower triangular entries in Q, stacked columnwise into a vector"?
</blockquote></details>

Done.
___
*[`common/symbolic/polynomial.h` line 602 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NIx22pD4FakbVwkYLP2:-NIxBIbZ1UbJsU1SA1an:b2h33f7) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5385c1189c3660068c7d5f4031dffa1254b144/common/symbolic/polynomial.h#L602)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

demand that cols==1 for both arguments?  (or even cleaner to static assert, since it seems like you'd only ever want vectors passed in)
</blockquote></details>

I used SFINAE with `std::enable_if` in the top, that requires both monomial_basis and gram_lower to be a column vector at compile time. Do you think we still need to demand cols == 1 here?

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429#-:-NJ1gVNh76aXEQbnr9I1:b4xbtza)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: math checks out 

> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429#-:-NJ1mhG11o__p3w-ESLG:byzctxa)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`common/symbolic/polynomial.h` line 589 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NJ1hQuLB9DhNSEp9lFq:-NJ1hQuLB9DhNSEp9lFr:besm4ul) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ec11d77f4838996964083e62d3e91090e9b83c/common/symbolic/polynomial.h#L589)):*
> ```objc
>  and Q is the Gram matrix.
>  @param monomial_basis m(x) in the documentation. A vector of monomials.
>  @pagram gram_lower The lower triangular entries in Q, stacked columnwise
> ```

typo: `@param` not `@pagram`
___
*[`common/symbolic/polynomial.h` line 599 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NJ1kgsNDWbYV5OTUMsS:-NJ1kgsNDWbYV5OTUMsT:b-kczy7b) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ec11d77f4838996964083e62d3e91090e9b83c/common/symbolic/polynomial.h#L599)):*
> ```objc
>          is_eigen_vector_of<Derived2, symbolic::Expression>::value),
>     symbolic::Polynomial>::type
> CalcPolynomialWGramLower(const Eigen::MatrixBase<Derived1>& monomial_basis,
> ```

I am a little uncomfortable with the notion of calling this a Gram matrix as Gram matrices are typically required to be PSD, but this is not enforced (and shouldn't be) by this function. 

IU think a more accurate name for this would be `CalcSymmetricQuadraticWithLowerTriangularPart` or something similar.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`common/symbolic/polynomial.h` line 599 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NJ1kgsNDWbYV5OTUMsS:-NJ3v2GMDv3ntlEdHl9t:b-rbovki) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ec11d77f4838996964083e62d3e91090e9b83c/common/symbolic/polynomial.h#L599)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am a little uncomfortable with the notion of calling this a Gram matrix as Gram matrices are typically required to be PSD, but this is not enforced (and shouldn't be) by this function. 

IU think a more accurate name for this would be `CalcSymmetricQuadraticWithLowerTriangularPart` or something similar.
</blockquote></details>

I renamed the function to`CalcPolynomialWLowerTriangular`. I think I want to mention "Polynomial" in the function name as that is what we compute. I removed "Quadratic" because the reader might think this is a quadratic polynomial but actually it is not. What do you think?

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic/polynomial.h` line 599 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NJ1kgsNDWbYV5OTUMsS:-NJ5grwe2oCXXVPeqckM:bl0k5n5) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ec11d77f4838996964083e62d3e91090e9b83c/common/symbolic/polynomial.h#L599)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I renamed the function to`CalcPolynomialWLowerTriangular`. I think I want to mention "Polynomial" in the function name as that is what we compute. I removed "Quadratic" because the reader might think this is a quadratic polynomial but actually it is not. What do you think?
</blockquote></details>

I would say `CalcPolynomialFromLowerTriangularPart` it is more cumbersome, but keeping "part" prevents the confusion that `Q` is lower triangular

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18429)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice and @RussTedrake)

___
*[`common/symbolic/polynomial.h` line 599 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18429#-NJ1kgsNDWbYV5OTUMsS:-NJ6UZDB-dpuYgzpdhYI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4ec11d77f4838996964083e62d3e91090e9b83c/common/symbolic/polynomial.h#L599)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would say `CalcPolynomialFromLowerTriangularPart` it is more cumbersome, but keeping "part" prevents the confusion that `Q` is lower triangular
</blockquote></details>

Done.

**Pull request merged**
