### PR TITLE
In internal namespace in .h files, change /// and /** to // and /* to resolve issue #13738.

### PR DESCRIPTION
**Pull request by mitiguy**
In .h files in multibody and math directories/subdirectories, when /// or /** appear within internal namespace, change them to // and /* to resolve issue #13738.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14474)

### CODE REVIEW

**Comment by mitiguy** [comment]
In .h files in multibody and math directories/subdirectories, when /// or /** appear within internal namespace, change them to // and /* to resolve issue #13738.

**Review by mitiguy — COMMENTED** [review]
Feature review and platform review +@sherm1  

> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14474#-:-MOqqJ7N2vRvSongFWfj:b-yp2new)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
A huge paydown of technical debt -- thanks, Paul!
:lgtm: pending a few nits

> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14474#-:-MOs8-Ur7-_IqGPRZcWA:b-3vfrk8)* status: 5 unresolved discussions (waiting on @mitiguy)

___
*[multibody/hydroelastics/hydroelastic_field.h, line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14474#-MOs5rzeBir4cqgaLQmy:-MOs5rzeBir4cqgaLQmz:b-lttg6j) ([raw file](https://github.com/robotlocomotion/drake/blob/746d78051b5b90672f9d5b9890c576b636f1a3e2/multibody/hydroelastics/hydroelastic_field.h#L56)):*
> ```objc
>   std::unique_ptr<geometry::VolumeMeshFieldLinear<T, T>> e_m_;
>   /** Represents the vector field ∇eₘ on the surface mesh, expressed in M's
>     frame */
> ```

nit: the above comments for private methods should be `/*` rather than `/**`.
___
*[multibody/parsing/detail_scene_graph.h, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14474#-MOs6ivE9_iZcAEPc3vs:-MOs6ivE9_iZcAEPc3vt:b-ksvxch) ([raw file](https://github.com/robotlocomotion/drake/blob/746d78051b5b90672f9d5b9890c576b636f1a3e2/multibody/parsing/detail_scene_graph.h#L177)):*
> ```objc
>         const sdf::Collision& sdf_collision);
> 
> /** Parses friction coefficients from `sdf_collision`.
> ```

nit: missed this one
___
*[multibody/plant/hydroelastic_traction_calculator.h, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14474#-MOs72pvAMYp-ESPQT0f:-MOs72pvAMYp-ESPQT0g:b-ksvxch) ([raw file](https://github.com/robotlocomotion/drake/blob/746d78051b5b90672f9d5b9890c576b636f1a3e2/multibody/plant/hydroelastic_traction_calculator.h#L81)):*
> ```objc
>       : vslip_regularizer_(vslip_regularizer) {}
> 
>   /**
> ```

nit: missed this one
___
*[multibody/plant/hydroelastic_traction_calculator.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14474#-MOs75AG97ivjvXbC7rj:-MOs75AG97ivjvXbC7rk:b-ksvxch) ([raw file](https://github.com/robotlocomotion/drake/blob/746d78051b5b90672f9d5b9890c576b636f1a3e2/multibody/plant/hydroelastic_traction_calculator.h#L88)):*
> ```objc
>   double regularization_scalar() const { return vslip_regularizer_; }
> 
>   /**
> ```

nit: missed this one
___
*[multibody/plant/hydroelastic_traction_calculator.h, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14474#-MOs75u-DwtevJijUqVr:-MOs75u-DwtevJijUqVs:b-ksvxch) ([raw file](https://github.com/robotlocomotion/drake/blob/746d78051b5b90672f9d5b9890c576b636f1a3e2/multibody/plant/hydroelastic_traction_calculator.h#L111)):*
> ```objc
>       multibody::SpatialForce<T>* F_Ac_W) const;
> 
>   /**
> ```

nit: missed this one

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14474)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by mitiguy — COMMENTED** [review]
label +(status: squashing now) 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14474#-:-MOsWGyfDzoQzXw8o0PO:br1597u)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
