### PR TITLE
Retrieve dual solution from CLP solver.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820#-:-MWb_59cBQmhdNa1Yx1P:b-uss1yj)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@seancurtis-tri for platform review.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820#-:-MXYZUG93azxh6t0F7C1:b362zgh)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Just one question on the clarity and intent behind some control flow logic.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820#-:-MXYyDqn-QVb-MOaLFQG:b-y86hvb)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

___
*[solvers/clp_solver.cc, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14820#-MXYx0XgD9BP5V9NOz3z:-MXYx0XgD9BP5V9NOz4-:b-y8fo6h) ([raw file](https://github.com/robotlocomotion/drake/blob/50ccadb691d776f68af2f5ae8ead29958259cc14/solvers/clp_solver.cc#L129)):*
> ```cpp
>     const std::vector<int>& upper_dual_indices = dual_var_indices.second;
>     for (int k = 0; k < bb_con.evaluator()->num_constraints(); ++k) {
>       if (lower_dual_indices[k] != -1 &&
> ```

This code is interesting. Two disparate if statements means if they are both true, the second will *always* win. That kind of code usually looks like an error. If that is correct behavior, than doing an `if-else` with the higher priority outcome coming first would be a stronger way of encoding that. Also, perhaps a comment explaining this protocol would go a long way to clarify for future readers.

If, in fact, the two states are mutually exclusive, the the if-else would imply that as well.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[solvers/clp_solver.cc, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14820#-MXYx0XgD9BP5V9NOz3z:-MXZ27AJ2CbecJhrhOnQ:bz5mp2o) ([raw file](https://github.com/robotlocomotion/drake/blob/50ccadb691d776f68af2f5ae8ead29958259cc14/solvers/clp_solver.cc#L129)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This code is interesting. Two disparate if statements means if they are both true, the second will *always* win. That kind of code usually looks like an error. If that is correct behavior, than doing an `if-else` with the higher priority outcome coming first would be a stronger way of encoding that. Also, perhaps a comment explaining this protocol would go a long way to clarify for future readers.

If, in fact, the two states are mutually exclusive, the the if-else would imply that as well.
</blockquote></details>

Done. I changed to `if-else`. They are mutually exclusive, as column_dual_sol(upper_dual_indices[k]) cannot be both <0 and > 0.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @avalenzu and @SeanCurtis-TRI)

___
*[solvers/clp_solver.cc, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14820#-MXYx0XgD9BP5V9NOz3z:-MXZ4hWr0z4utyzsaEV3:b343w46) ([raw file](https://github.com/robotlocomotion/drake/blob/50ccadb691d776f68af2f5ae8ead29958259cc14/solvers/clp_solver.cc#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I changed to `if-else`. They are mutually exclusive, as column_dual_sol(upper_dual_indices[k]) cannot be both <0 and > 0.
</blockquote></details>

I added documentation to explain these these two branches should be exclusive.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14820#-:-MXZJA3UDe0OLLnYd0Ke:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),avalenzu (waiting on @hongkai-dai)

**Pull request merged**
