### PR TITLE
Construct EvaluatorCost as a linear transformation of another evaluator

### LINKED ISSUE #17989: Scaling for EvaluatorCost
See (`class EvaluatorCost`)[https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_evaluator_cost.html].

I think it might be nice to extend it with the capability to apply an `a` vector and `b` offset to the wrapped evaluator's outputs.

Right now, it can only wrap an evaluator with `num_outputs==1`.  We could allow for any number of outputs from the wrapped evaluator if we had `y_cost = a.dot(y_inner) + b`.  We just need to require that `a.rows() == inner_evaluator.num_outputs()`.

Relatedly, we should also bind this class into `pydrake`.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #17989

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030#-:-NDWOcX28lJ9YQSr1BaU:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030#-:-NDYLGSLEcN2glXe4ItS:b-n37teh)* status: 8 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYKl-EDp7dHWBJverv:-NDYKl-EDp7dHWBJverw:bfm9j3z) (no related file):*
nit Should we have a TODO or issue somewhere that `MP::AddCost(EvaluatorCost(LinearConstraint(...)))` should recognize the functional form (e.g., linear)?  It seems like that might eventually become important.

___
___
*[`solvers/cost.h` line 478 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYKfoyBsXKSfxYKR3J:-NDYKfoyBsXKSfxYKR3K:b-b31vw4) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/cost.h#L478)):*
> ```objc
> 
>   template <typename T, typename S>
>   void DoEvalGeneric(const Eigen::Ref<const VectorX<T>>& x,
> ```

nit DoEvalGeneric should be private (not protected) to keep it hidden from Doxygen, etc.
___
*[`solvers/cost.h` line 483 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYJuJY56OSoFEOJNWy:-NDYJuJZD2nSyq8eq5nB:bskpd0v) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/cost.h#L483)):*
> ```objc
>       VectorX<S> y_inner;
>       evaluator_->Eval(x, &y_inner);
>       y->resize(1);
> ```

nit This (allocation + exception handling up cleanup) has probably pushed us over the limit for what should be inline in a header file.

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

For the easiest solution, probably all four `DoEval` function bodies should move into the cc file, like we have with LinearCost, etc.
___
*[`solvers/cost.h` line 507 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYIyNP32APqxDTxTH3:-NDYIyNP32APqxDTxTH4:b-okteh6) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/cost.h#L507)):*
> ```objc
>   std::shared_ptr<EvaluatorType> evaluator_;
>   std::optional<Eigen::VectorXd> a_;
>   double b_;
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization

Here we need either `{}` or `const`.



_Suggestion:_
```objc
const double b_;
```
___
*[`solvers/test/cost_test.cc` line 651 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYLsgS-nbUwrcmqGDh:-NDYLsgS-nbUwrcmqGDi:b-c84vrk) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/test/cost_test.cc#L651)):*
> ```cpp
> }
> 
> class Evaluator1 : public EvaluatorBase {
> ```

nit It's find as-is, but I wonder if naming these after the input-output counts would be even more clear.

Maybe `Evaluator21` and `Evaluator32`?
Or maybe `Evaluator2in1out` and `Evaluator3in2out`?
___
*[`solvers/test/cost_test.cc` line 666 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYLeLz8EmREU2J17D4:-NDYLeLz8EmREU2J17D5:b-wdrwqg) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/test/cost_test.cc#L666)):*
> ```cpp
>   }
> 
>   void DoEval(const Eigen::Ref<const Eigen::VectorXd>& x, VectorXd* y) const {
> ```

nit Missing `override` on these three.
___
*[`solvers/test/cost_test.cc` line 714 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYMJy7AYMqckVQgxIP:-NDYMJy89hS_IfoyMpvv:b-qrhwwq) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/test/cost_test.cc#L714)):*
> ```cpp
> 
> GTEST_TEST(EvaluatorCost, Eval) {
>   // Test with a single-output evaluator
> ```

nit punc



_Suggestion:_
```cpp
// Test with a single-output evaluator.
```
___
*[`solvers/test/cost_test.cc` line 734 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYMZvW-r-TeJDip4NL:-NDYMZvW-r-TeJDip4NM:b1tlxlz) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/test/cost_test.cc#L734)):*
> ```cpp
>   Eigen::VectorXd evaluator2_y;
>   evaluator2->Eval(x2, &evaluator2_y);
>   EXPECT_EQ(y2.rows(), 1);
> ```

nit We should preempt any segfault on next line.



_Suggestion:_
```cpp
ASSERT_EQ
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYKl-EDp7dHWBJverv:-NDYvFFFCMg3ZmKCCb4S:b-rcnzid) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Should we have a TODO or issue somewhere that `MP::AddCost(EvaluatorCost(LinearConstraint(...)))` should recognize the functional form (e.g., linear)?  It seems like that might eventually become important.
</blockquote></details>

I see, so the proposal is that `MP::AddCost(EvaluatorCost(LinearConstraint(...)))` should recognize that it is a linear cost, and hence appends `prog.linear_costs()` and returns a LinearCost object? I think this is a great idea. I added TODO

___
___
*[`solvers/cost.h` line 483 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYJuJY56OSoFEOJNWy:-NDYvltH5kU_Wap23tKp:b-t7h197) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/cost.h#L483)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This (allocation + exception handling up cleanup) has probably pushed us over the limit for what should be inline in a header file.

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

For the easiest solution, probably all four `DoEval` function bodies should move into the cc file, like we have with LinearCost, etc.
</blockquote></details>

This class `EvaluatorCost<EvaluatorType>` is a templated class, I thought that I should put its implementation in the header file for the templated class?

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030#-:-NDZBQ1rDyXWh2HOVnuG:bfqkacy)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYKl-EDp7dHWBJverv:-NDZBzo1ByRmOFXvI0iX:byrf9jm) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, so the proposal is that `MP::AddCost(EvaluatorCost(LinearConstraint(...)))` should recognize that it is a linear cost, and hence appends `prog.linear_costs()` and returns a LinearCost object? I think this is a great idea. I added TODO
</blockquote></details>

Something like that yes.  The important point being that EvaluatorCost doesn't always force us into a nonlinear solver.  If the underlying math is still of a more specific functional form, we should be able to recognize that and dispatch to a more efficient solver.  That _probably_ means adding it to `linear_costs()`, but there are other ways to achieve it as well.

___
___
*[`solvers/cost.h` line 483 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDYJuJY56OSoFEOJNWy:-NDZAR8H203c8_d7iZMy:b418rub) ([raw file](https://github.com/robotlocomotion/drake/blob/24ee82a74e7b18f2fe024efa30d30d611aedd7bf/solvers/cost.h#L483)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This class `EvaluatorCost<EvaluatorType>` is a templated class, I thought that I should put its implementation in the header file for the templated class?
</blockquote></details>

You make a good point, I forgot it was templated.  (This class _shouldn't_ be templated, but that's a fixup for another day.)

Withdrawn.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030#-:-NDZFkrh3aDvR3FHyf62:b-cxwtpw)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/cost.h` line 462 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18030#-NDZEtLE2ys4bvd_r7IQ:-NDZEtLE2ys4bvd_r7IR:b245ha8) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ba1cb00941f2949907c488d2457d892621d1ea/solvers/cost.h#L462)):*
> ```objc
>       : Cost(evaluator->num_vars()),
>         evaluator_(evaluator),
>         a_{std::nullopt},
> ```

nit, is there a reason to switch from () to {} here? Ditto below.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18030)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
