### PR TITLE
[solvers] Add tolerance for clp_solver_test

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19378)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please.

**Review by svenevs — COMMENTED** [review]
+@hongkai-dai via #14894 please, see also https://github.com/RobotLocomotion/drake/issues/18327#issuecomment-1535537588

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19378#-:-NUoD4sn1Nu5eOJo5Tvk:b-cxd89z)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @svenevs)

___
*[`solvers/test/clp_solver_test.cc` line 190 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19378#-NUoCtYQDw8P_UuOMexA:-NUoCtYQDw8P_UuOMexB:b-wi89uq) ([raw file](https://github.com/RobotLocomotion/drake/blob/09da4fdb90c85a6b10bcea01f4bb86cf3f97f3ee/solvers/test/clp_solver_test.cc#L190)):*
> ```cpp
>   // This QP has non-zero dual solution for the bounding box constraint.
>   ClpSolver solver;
>   TestQPDualSolution3(solver, 0.0, 1.0e-4);
> ```

working, this is a pretty big error bound?  success criteria is this test passes in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //solvers:clp_solver_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //solvers:clp_solver_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
FAIL: //solvers:clp_solver_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/solvers/clp_solver_test/test.log)
INFO: From Testing //solvers:clp_solver_test:
==================== Test output for //solvers:clp_solver_test:
Using drake_cc_googletest_main.cc

[==========] Running 78 tests from 8 test suites.
[----------] Global test environment set-up.
[----------] 1 test from InfeasibleLinearProgramTest0
[ RUN      ] InfeasibleLinearProgramTest0.TestInfeasible
[       OK ] InfeasibleLinearProgramTest0.TestInfeasible (0 ms)
[----------] 1 test from InfeasibleLinearProgramTest0 (0 ms total)

[----------] 1 test from UnboundedLinearProgramTest0
[ RUN      ] UnboundedLinearProgramTest0.TestUnbounded
[       OK ] UnboundedLinearProgramTest0.TestUnbounded (0 ms)
[----------] 1 test from UnboundedLinearProgramTest0 (0 ms total)

[----------] 1 test from DuplicatedVariableLinearProgramTest1
[ RUN      ] DuplicatedVariableLinearProgramTest1.Test
[       OK ] DuplicatedVariableLinearProgramTest1.Test (0 ms)
[----------] 1 test from DuplicatedVariableLinearProgramTest1 (0 ms total)

[----------] 3 tests from TestDual
[ RUN      ] TestDual.DualSolution1
[       OK ] TestDual.DualSolution1 (0 ms)
[ RUN      ] TestDual.DualSolution2
[       OK ] TestDual.DualSolution2 (0 ms)
[ RUN      ] TestDual.DualSolution3
[       OK ] TestDual.DualSolution3 (0 ms)
[----------] 3 tests from TestDual (0 ms total)

[----------] 3 tests from QPtest
[ RUN      ] QPtest.TestUnconstrainedQP
[2023-05-07 03:16:32.800] [console] [warning] Currently CLP solver has a memory issue when solving a QP. The user should be aware of this risk.
[       OK ] QPtest.TestUnconstrainedQP (0 ms)
[ RUN      ] QPtest.TestUnitBallExample
[       OK ] QPtest.TestUnitBallExample (1 ms)
[ RUN      ] QPtest.TestInfeasible
[       OK ] QPtest.TestInfeasible (0 ms)
[----------] 3 tests from QPtest (1 ms total)

[----------] 9 tests from ClpSolverTest
[ RUN      ] ClpSolverTest.Version
[       OK ] ClpSolverTest.Version (0 ms)
[ RUN      ] ClpSolverTest.DualSolution1
[       OK ] ClpSolverTest.DualSolution1 (0 ms)
[ RUN      ] ClpSolverTest.DualSolution2
[       OK ] ClpSolverTest.DualSolution2 (0 ms)
[ RUN      ] ClpSolverTest.DualSolution3
solvers/test/quadratic_program_examples.cc:629: Failure
The difference between (result4.get_optimal_cost() - result.get_optimal_cost()) / delta and 6 is 2.0000129778985354e-05, which exceeds sensitivity_tol, where
(result4.get_optimal_cost() - result.get_optimal_cost()) / delta evaluates to 6.000020000129779,
6 evaluates to 6, and
sensitivity_tol evaluates to 2.0000000000000002e-05.
[  FAILED  ] ClpSolverTest.DualSolution3 (0 ms)
[ RUN      ] ClpSolverTest.EqualityConstrainedQPDualSolution1
[       OK ] ClpSolverTest.EqualityConstrainedQPDualSolution1 (0 ms)
[ RUN      ] ClpSolverTest.EqualityConstrainedQPDualSolution2
[       OK ] ClpSolverTest.EqualityConstrainedQPDualSolution2 (0 ms)
[ RUN      ] ClpSolverTest.TestNonconvexQP
[       OK ] ClpSolverTest.TestNonconvexQP (0 ms)
[ RUN      ] ClpSolverTest.TestVerbosity
Clp1001I Initial range of elements is 1 to 2
Clp1004I Not bothering to scale as good enough
Clp0022I Absolute values of scaled rhs range from 1 to 4, minimum gap 1e+100
Clp0020I Absolute values of scaled objective range from 1 to 2
Clp0021I Absolute values of scaled bounds range from 2 to 2, minimum gap 1e+100
Clp0006I 0  Obj 6 Primal inf 0.9999999 (1) Dual inf 1e+10 (1)
Clp0006I 1  Obj 8
Clp0017I Looking optimal with tolerance of 1e-07
Clp0000I Optimal - objective value 8
[       OK ] ClpSolverTest.TestVerbosity (0 ms)
[ RUN      ] ClpSolverTest.TestNumericalScaling
[       OK ] ClpSolverTest.TestNumericalScaling (0 ms)
[----------] 9 tests from ClpSolverTest (1 ms total)

[----------] 30 tests from ClpTest/LinearProgramTest
[ RUN      ] ClpTest/LinearProgramTest.TestLP/0
[       OK ] ClpTest/LinearProgramTest.TestLP/0 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/1
[       OK ] ClpTest/LinearProgramTest.TestLP/1 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/2
[       OK ] ClpTest/LinearProgramTest.TestLP/2 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/3
[       OK ] ClpTest/LinearProgramTest.TestLP/3 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/4
[       OK ] ClpTest/LinearProgramTest.TestLP/4 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/5
[       OK ] ClpTest/LinearProgramTest.TestLP/5 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/6
[       OK ] ClpTest/LinearProgramTest.TestLP/6 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/7
[       OK ] ClpTest/LinearProgramTest.TestLP/7 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/8
[       OK ] ClpTest/LinearProgramTest.TestLP/8 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/9
[       OK ] ClpTest/LinearProgramTest.TestLP/9 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/10
[       OK ] ClpTest/LinearProgramTest.TestLP/10 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/11
[       OK ] ClpTest/LinearProgramTest.TestLP/11 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/12
[       OK ] ClpTest/LinearProgramTest.TestLP/12 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/13
[       OK ] ClpTest/LinearProgramTest.TestLP/13 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/14
[       OK ] ClpTest/LinearProgramTest.TestLP/14 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/15
[       OK ] ClpTest/LinearProgramTest.TestLP/15 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/16
[       OK ] ClpTest/LinearProgramTest.TestLP/16 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/17
[       OK ] ClpTest/LinearProgramTest.TestLP/17 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/18
[       OK ] ClpTest/LinearProgramTest.TestLP/18 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/19
[       OK ] ClpTest/LinearProgramTest.TestLP/19 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/20
[       OK ] ClpTest/LinearProgramTest.TestLP/20 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/21
[       OK ] ClpTest/LinearProgramTest.TestLP/21 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/22
[       OK ] ClpTest/LinearProgramTest.TestLP/22 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/23
[       OK ] ClpTest/LinearProgramTest.TestLP/23 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/24
[       OK ] ClpTest/LinearProgramTest.TestLP/24 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/25
[       OK ] ClpTest/LinearProgramTest.TestLP/25 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/26
[       OK ] ClpTest/LinearProgramTest.TestLP/26 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/27
[       OK ] ClpTest/LinearProgramTest.TestLP/27 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/28
[       OK ] ClpTest/LinearProgramTest.TestLP/28 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/29
[       OK ] ClpTest/LinearProgramTest.TestLP/29 (0 ms)
[----------] 30 tests from ClpTest/LinearProgramTest (1 ms total)

[----------] 30 tests from ClpTest/QuadraticProgramTest
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/0
[       OK ] ClpTest/QuadraticProgramTest.TestQP/0 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/1
[       OK ] ClpTest/QuadraticProgramTest.TestQP/1 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/2
[       OK ] ClpTest/QuadraticProgramTest.TestQP/2 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/3
[       OK ] ClpTest/QuadraticProgramTest.TestQP/3 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/4
[       OK ] ClpTest/QuadraticProgramTest.TestQP/4 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/5
[       OK ] ClpTest/QuadraticProgramTest.TestQP/5 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/6
[       OK ] ClpTest/QuadraticProgramTest.TestQP/6 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/7
[       OK ] ClpTest/QuadraticProgramTest.TestQP/7 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/8
[       OK ] ClpTest/QuadraticProgramTest.TestQP/8 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/9
[       OK ] ClpTest/QuadraticProgramTest.TestQP/9 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/10
[       OK ] ClpTest/QuadraticProgramTest.TestQP/10 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/11
[       OK ] ClpTest/QuadraticProgramTest.TestQP/11 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/12
[       OK ] ClpTest/QuadraticProgramTest.TestQP/12 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/13
[       OK ] ClpTest/QuadraticProgramTest.TestQP/13 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/14
[       OK ] ClpTest/QuadraticProgramTest.TestQP/14 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/15
[       OK ] ClpTest/QuadraticProgramTest.TestQP/15 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/16
[       OK ] ClpTest/QuadraticProgramTest.TestQP/16 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/17
[       OK ] ClpTest/QuadraticProgramTest.TestQP/17 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/18
[       OK ] ClpTest/QuadraticProgramTest.TestQP/18 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/19
[       OK ] ClpTest/QuadraticProgramTest.TestQP/19 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/20
[       OK ] ClpTest/QuadraticProgramTest.TestQP/20 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/21
[       OK ] ClpTest/QuadraticProgramTest.TestQP/21 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/22
[       OK ] ClpTest/QuadraticProgramTest.TestQP/22 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/23
[       OK ] ClpTest/QuadraticProgramTest.TestQP/23 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/24
[       OK ] ClpTest/QuadraticProgramTest.TestQP/24 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/25
[       OK ] ClpTest/QuadraticProgramTest.TestQP/25 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/26
[       OK ] ClpTest/QuadraticProgramTest.TestQP/26 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/27
[       OK ] ClpTest/QuadraticProgramTest.TestQP/27 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/28
[       OK ] ClpTest/QuadraticProgramTest.TestQP/28 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/29
[       OK ] ClpTest/QuadraticProgramTest.TestQP/29 (0 ms)
[----------] 30 tests from ClpTest/QuadraticProgramTest (1 ms total)

[----------] Global test environment tear-down
[==========] 78 tests from 8 test suites ran. (6 ms total)
[  PASSED  ] 77 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ClpSolverTest.DualSolution3

 1 FAILED TEST
================================================================================
Target //solvers:clp_solver_test up-to-date:
  bazel-bin/solvers/clp_solver_test
INFO: Elapsed time: 0.204s, Critical Path: 0.05s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//solvers:clp_solver_test                                                FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.

```

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19378#-:-NUrE0rH-kBh55vE2qzc:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri.

> Reviewed 1 of 1 files at r1, all commit messages.
> Dismissed @svenevs from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19378#-:-NUrSPxxDtOnIpb3uKgf:b-udyqyg)* status: 1 unresolved discussion

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19378#-NUrSZNN4DY_bKwkbbRs):*
nit Remove issue number when merging.
___
*[`solvers/test/clp_solver_test.cc` line 190 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19378#-NUoCtYQDw8P_UuOMexA:-NUrSUz89IGbxsnIy1Ri:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/09da4fdb90c85a6b10bcea01f4bb86cf3f97f3ee/solvers/test/clp_solver_test.cc#L190)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, this is a pretty big error bound?  success criteria is this test passes in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //solvers:clp_solver_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //solvers:clp_solver_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
FAIL: //solvers:clp_solver_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/solvers/clp_solver_test/test.log)
INFO: From Testing //solvers:clp_solver_test:
==================== Test output for //solvers:clp_solver_test:
Using drake_cc_googletest_main.cc

[==========] Running 78 tests from 8 test suites.
[----------] Global test environment set-up.
[----------] 1 test from InfeasibleLinearProgramTest0
[ RUN      ] InfeasibleLinearProgramTest0.TestInfeasible
[       OK ] InfeasibleLinearProgramTest0.TestInfeasible (0 ms)
[----------] 1 test from InfeasibleLinearProgramTest0 (0 ms total)

[----------] 1 test from UnboundedLinearProgramTest0
[ RUN      ] UnboundedLinearProgramTest0.TestUnbounded
[       OK ] UnboundedLinearProgramTest0.TestUnbounded (0 ms)
[----------] 1 test from UnboundedLinearProgramTest0 (0 ms total)

[----------] 1 test from DuplicatedVariableLinearProgramTest1
[ RUN      ] DuplicatedVariableLinearProgramTest1.Test
[       OK ] DuplicatedVariableLinearProgramTest1.Test (0 ms)
[----------] 1 test from DuplicatedVariableLinearProgramTest1 (0 ms total)

[----------] 3 tests from TestDual
[ RUN      ] TestDual.DualSolution1
[       OK ] TestDual.DualSolution1 (0 ms)
[ RUN      ] TestDual.DualSolution2
[       OK ] TestDual.DualSolution2 (0 ms)
[ RUN      ] TestDual.DualSolution3
[       OK ] TestDual.DualSolution3 (0 ms)
[----------] 3 tests from TestDual (0 ms total)

[----------] 3 tests from QPtest
[ RUN      ] QPtest.TestUnconstrainedQP
[2023-05-07 03:16:32.800] [console] [warning] Currently CLP solver has a memory issue when solving a QP. The user should be aware of this risk.
[       OK ] QPtest.TestUnconstrainedQP (0 ms)
[ RUN      ] QPtest.TestUnitBallExample
[       OK ] QPtest.TestUnitBallExample (1 ms)
[ RUN      ] QPtest.TestInfeasible
[       OK ] QPtest.TestInfeasible (0 ms)
[----------] 3 tests from QPtest (1 ms total)

[----------] 9 tests from ClpSolverTest
[ RUN      ] ClpSolverTest.Version
[       OK ] ClpSolverTest.Version (0 ms)
[ RUN      ] ClpSolverTest.DualSolution1
[       OK ] ClpSolverTest.DualSolution1 (0 ms)
[ RUN      ] ClpSolverTest.DualSolution2
[       OK ] ClpSolverTest.DualSolution2 (0 ms)
[ RUN      ] ClpSolverTest.DualSolution3
solvers/test/quadratic_program_examples.cc:629: Failure
The difference between (result4.get_optimal_cost() - result.get_optimal_cost()) / delta and 6 is 2.0000129778985354e-05, which exceeds sensitivity_tol, where
(result4.get_optimal_cost() - result.get_optimal_cost()) / delta evaluates to 6.000020000129779,
6 evaluates to 6, and
sensitivity_tol evaluates to 2.0000000000000002e-05.
[  FAILED  ] ClpSolverTest.DualSolution3 (0 ms)
[ RUN      ] ClpSolverTest.EqualityConstrainedQPDualSolution1
[       OK ] ClpSolverTest.EqualityConstrainedQPDualSolution1 (0 ms)
[ RUN      ] ClpSolverTest.EqualityConstrainedQPDualSolution2
[       OK ] ClpSolverTest.EqualityConstrainedQPDualSolution2 (0 ms)
[ RUN      ] ClpSolverTest.TestNonconvexQP
[       OK ] ClpSolverTest.TestNonconvexQP (0 ms)
[ RUN      ] ClpSolverTest.TestVerbosity
Clp1001I Initial range of elements is 1 to 2
Clp1004I Not bothering to scale as good enough
Clp0022I Absolute values of scaled rhs range from 1 to 4, minimum gap 1e+100
Clp0020I Absolute values of scaled objective range from 1 to 2
Clp0021I Absolute values of scaled bounds range from 2 to 2, minimum gap 1e+100
Clp0006I 0  Obj 6 Primal inf 0.9999999 (1) Dual inf 1e+10 (1)
Clp0006I 1  Obj 8
Clp0017I Looking optimal with tolerance of 1e-07
Clp0000I Optimal - objective value 8
[       OK ] ClpSolverTest.TestVerbosity (0 ms)
[ RUN      ] ClpSolverTest.TestNumericalScaling
[       OK ] ClpSolverTest.TestNumericalScaling (0 ms)
[----------] 9 tests from ClpSolverTest (1 ms total)

[----------] 30 tests from ClpTest/LinearProgramTest
[ RUN      ] ClpTest/LinearProgramTest.TestLP/0
[       OK ] ClpTest/LinearProgramTest.TestLP/0 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/1
[       OK ] ClpTest/LinearProgramTest.TestLP/1 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/2
[       OK ] ClpTest/LinearProgramTest.TestLP/2 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/3
[       OK ] ClpTest/LinearProgramTest.TestLP/3 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/4
[       OK ] ClpTest/LinearProgramTest.TestLP/4 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/5
[       OK ] ClpTest/LinearProgramTest.TestLP/5 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/6
[       OK ] ClpTest/LinearProgramTest.TestLP/6 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/7
[       OK ] ClpTest/LinearProgramTest.TestLP/7 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/8
[       OK ] ClpTest/LinearProgramTest.TestLP/8 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/9
[       OK ] ClpTest/LinearProgramTest.TestLP/9 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/10
[       OK ] ClpTest/LinearProgramTest.TestLP/10 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/11
[       OK ] ClpTest/LinearProgramTest.TestLP/11 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/12
[       OK ] ClpTest/LinearProgramTest.TestLP/12 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/13
[       OK ] ClpTest/LinearProgramTest.TestLP/13 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/14
[       OK ] ClpTest/LinearProgramTest.TestLP/14 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/15
[       OK ] ClpTest/LinearProgramTest.TestLP/15 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/16
[       OK ] ClpTest/LinearProgramTest.TestLP/16 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/17
[       OK ] ClpTest/LinearProgramTest.TestLP/17 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/18
[       OK ] ClpTest/LinearProgramTest.TestLP/18 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/19
[       OK ] ClpTest/LinearProgramTest.TestLP/19 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/20
[       OK ] ClpTest/LinearProgramTest.TestLP/20 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/21
[       OK ] ClpTest/LinearProgramTest.TestLP/21 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/22
[       OK ] ClpTest/LinearProgramTest.TestLP/22 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/23
[       OK ] ClpTest/LinearProgramTest.TestLP/23 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/24
[       OK ] ClpTest/LinearProgramTest.TestLP/24 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/25
[       OK ] ClpTest/LinearProgramTest.TestLP/25 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/26
[       OK ] ClpTest/LinearProgramTest.TestLP/26 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/27
[       OK ] ClpTest/LinearProgramTest.TestLP/27 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/28
[       OK ] ClpTest/LinearProgramTest.TestLP/28 (0 ms)
[ RUN      ] ClpTest/LinearProgramTest.TestLP/29
[       OK ] ClpTest/LinearProgramTest.TestLP/29 (0 ms)
[----------] 30 tests from ClpTest/LinearProgramTest (1 ms total)

[----------] 30 tests from ClpTest/QuadraticProgramTest
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/0
[       OK ] ClpTest/QuadraticProgramTest.TestQP/0 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/1
[       OK ] ClpTest/QuadraticProgramTest.TestQP/1 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/2
[       OK ] ClpTest/QuadraticProgramTest.TestQP/2 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/3
[       OK ] ClpTest/QuadraticProgramTest.TestQP/3 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/4
[       OK ] ClpTest/QuadraticProgramTest.TestQP/4 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/5
[       OK ] ClpTest/QuadraticProgramTest.TestQP/5 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/6
[       OK ] ClpTest/QuadraticProgramTest.TestQP/6 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/7
[       OK ] ClpTest/QuadraticProgramTest.TestQP/7 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/8
[       OK ] ClpTest/QuadraticProgramTest.TestQP/8 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/9
[       OK ] ClpTest/QuadraticProgramTest.TestQP/9 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/10
[       OK ] ClpTest/QuadraticProgramTest.TestQP/10 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/11
[       OK ] ClpTest/QuadraticProgramTest.TestQP/11 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/12
[       OK ] ClpTest/QuadraticProgramTest.TestQP/12 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/13
[       OK ] ClpTest/QuadraticProgramTest.TestQP/13 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/14
[       OK ] ClpTest/QuadraticProgramTest.TestQP/14 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/15
[       OK ] ClpTest/QuadraticProgramTest.TestQP/15 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/16
[       OK ] ClpTest/QuadraticProgramTest.TestQP/16 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/17
[       OK ] ClpTest/QuadraticProgramTest.TestQP/17 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/18
[       OK ] ClpTest/QuadraticProgramTest.TestQP/18 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/19
[       OK ] ClpTest/QuadraticProgramTest.TestQP/19 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/20
[       OK ] ClpTest/QuadraticProgramTest.TestQP/20 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/21
[       OK ] ClpTest/QuadraticProgramTest.TestQP/21 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/22
[       OK ] ClpTest/QuadraticProgramTest.TestQP/22 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/23
[       OK ] ClpTest/QuadraticProgramTest.TestQP/23 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/24
[       OK ] ClpTest/QuadraticProgramTest.TestQP/24 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/25
[       OK ] ClpTest/QuadraticProgramTest.TestQP/25 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/26
[       OK ] ClpTest/QuadraticProgramTest.TestQP/26 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/27
[       OK ] ClpTest/QuadraticProgramTest.TestQP/27 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/28
[       OK ] ClpTest/QuadraticProgramTest.TestQP/28 (0 ms)
[ RUN      ] ClpTest/QuadraticProgramTest.TestQP/29
[       OK ] ClpTest/QuadraticProgramTest.TestQP/29 (0 ms)
[----------] 30 tests from ClpTest/QuadraticProgramTest (1 ms total)

[----------] Global test environment tear-down
[==========] 78 tests from 8 test suites ran. (6 ms total)
[  PASSED  ] 77 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ClpSolverTest.DualSolution3

 1 FAILED TEST
================================================================================
Target //solvers:clp_solver_test up-to-date:
  bazel-bin/solvers/clp_solver_test
INFO: Elapsed time: 0.204s, Critical Path: 0.05s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//solvers:clp_solver_test                                                FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.

```
</blockquote></details>

Done

**Pull request merged**
