### PR TITLE
[workspace] Upgrade meshcat to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is auto-generated commit from `new_release`.

+@SeanCurtis-TRI for both reviews (and meshcat_manual_test), please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
I don't have a gamepad at home, but everything else checked out (and I have no particular reason to assume that it's been broken). I'm assuming you tested this as well and you've got a gamepad with you, right?

:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-:-NhhbOF6DuOe4iQsczT2:bl0bzrn)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
I had not run it myself.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-:-NhhdrD518Q63vpjpv47:bsf62xg)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-NhhduIZ7zUXRK-lNEfl:-NhhduI_-vZTUhqg6-Hb:bb2nvaw) (no related file):*
@SeanCurtis-TRI In firefox at least, the scene lighting looks a lot worse with this new sha.  Both the mustard bottle and the iiwa are a lot dimmer.  I can post screenshots, if you can't repro.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-Nhhe9yW-9vyfSQaXZ3s:-Nhhe9yX2CnK5virA8KW:bstlglv) (no related file):*
Working

The gamepad is being finicky (sometimes not detectged).  That's not unusual for me, but I'll try to take some more time to figure out if its a regression here or not.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-Nhhe9yW-9vyfSQaXZ3s:-NhhgiGL5tzsxGtFOY-e:butstr6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

The gamepad is being finicky (sometimes not detectged).  That's not unusual for me, but I'll try to take some more time to figure out if its a regression here or not.
</blockquote></details>

OK Gamepad is fine.  Apparently I need to unplug & re-plug it each time I run the meshcat manual test.

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@SeanCurtis-TRI In firefox at least, the scene lighting looks a lot worse with this new sha.  Both the mustard bottle and the iiwa are a lot dimmer.  I can post screenshots, if you can't repro.
</blockquote></details>

I'll take a look.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-NhhduIZ7zUXRK-lNEfl:-Nhhj7r67LRefRX1RESG:bnh25u2) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'll take a look.
</blockquote></details>

Yep. There's a distinct visual difference on both Chrome and Firefox.

 - The default background is obviously different.
 - The objects are less saturated.

I need to investigate.

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Yep. There's a distinct visual difference on both Chrome and Firefox.

 - The default background is obviously different.
 - The objects are less saturated.

I need to investigate.
</blockquote></details>

The same can be observed local to meshcat (without Drake involved at all). Let me see what I can do about diagnosing and correcting. Stay tuned.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-NhhduIZ7zUXRK-lNEfl:-NhhlXKFE4Sp3J-Gp9vE:bunv9ov) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The same can be observed local to meshcat (without Drake involved at all). Let me see what I can do about diagnosing and correcting. Stay tuned.
</blockquote></details>

(In the likely event that this requires a fix to `meshcat-dev/meshcat` upstream, our plan should be to close this pull request and let you open a corrected one.)

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(In the likely event that this requires a fix to `meshcat-dev/meshcat` upstream, our plan should be to close this pull request and let you open a corrected one.)
</blockquote></details>

It seems it's attributable to upgrading three.js. So, something has changed in some three.js default between the versions.

We should probably close this and I'll figure out what three.js changed.

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It seems it's attributable to upgrading three.js. So, something has changed in some three.js default between the versions.

We should probably close this and I'll figure out what three.js changed.
</blockquote></details>

https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733

I'm betting this is it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20437)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20437#-NhhduIZ7zUXRK-lNEfl:-NhhmVAk0O73zOXKiHMk:b-ba7jcz) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733

I'm betting this is it.
</blockquote></details>

Sounds good to me.

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

Ok, so we can temporarily turn the default lighting back on. But we'll eventually have to bite the bullet and break lighting. I'll also look at retuning the default lights to see if I can't get an appreciably similar outcome with new values.

**Pull request closed without merging**
