### PR TITLE
Add BUILD macros for brevity

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This proposes some BUILD macros, ~and also removes uses of the `DEPS = ...` pattern~.  I think both would be helpful improvements before bringing Bazel to the masses pre-merge.

@david-german-tri and @rpoyner-tri (and anyone), I am looking for general design feedback on this.  I've tagged it DNR because I don't want a detailed line-by-line review, but rather a skim and then discussion (possibly in-person)?  But I wanted to put code on the table first.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4480)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Looks good; passes my sniff test for don't-use-skylark-to-hide-things-done-wrong. Might be helpful to have some related documentation in developer docs somewhere. Also somewhere (perhaps the .bzl file) should record justifications for the defaults, even if some of them are just boilerplate-reduction.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-:-KYpQGKCSToDeuUG-yIk:byabzq9)*

**Comment by jwnimmer-tri** [comment]
Agreed.  I've added specific defects for those and will revisit after getting more feedback.

---

Review status: 0 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-KYq4yrMjxqgE8R3-NcQ:-KYq4yrMjxqgE8R3-NcR:bldb740) (no related file):*
TODO Add related documentation to `bazel.rst`, likely as part of the "Updating BUILD files" from #4477.

---

*[tools/drake.bzl, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-KYq5FzxrORYqE-2ZNFj:-KYq5Fzy27U-XjqQwZFF:b-nvrgh) ([raw file](https://github.com/robotlocomotion/drake/blob/5bda88b1607f03f308e2cfa8d940c0d3377bbdd5/tools/drake.bzl#L18)):*
> ```Python
>     only components as srcs=[].)
> 
>     By default, the component is marked linkstatic=1.
> ```

TODO Justify this as the default here.

---

*[tools/drake.bzl, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-KYq5KG23Wq1NafwXo_g:-KYq5KG23Wq1NafwXo_h:bcfk62z) ([raw file](https://github.com/robotlocomotion/drake/blob/5bda88b1607f03f308e2cfa8d940c0d3377bbdd5/tools/drake.bzl#L45)):*
> ```Python
> 
>     By default, sets name="test/${name}.cc" per Drake's filename convention.
>     By default, sets size="small" because that indicates a unit test.
> ```

TODO Justify these as the defaults here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-:-KYq5SFDOOqw8I_vGsEu:b-51pqy1)*

**Comment by david-german-tri** [comment]
Removing the `DEPS` pattern is great.  Thoughts on macros below.

---

Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/drake.bzl, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-KYsu_mW4aFuDjnOwK4D:-KYsu_mXoq5b7PqBF8uV:bu5mdc) ([raw file](https://github.com/robotlocomotion/drake/blob/5bda88b1607f03f308e2cfa8d940c0d3377bbdd5/tools/drake.bzl#L4)):*
> ```Python
> # This file contains macros for Bazel; see drake/doc/bazel.rst.
> 
> def cc_component(
> ```

I can live with this, especially since it mimics our existing CMake macros, and doesn't diverge too much from standard Bazel phraseology.

However, I'd prefer not to do it, for two reasons.  (1) It does diverge a little bit, forcing anyone who reads our project to learn our Bazel macro dialect.  (2) It makes less explicit, from inspection of the BUILD file, which particular source files feed into a target.  Concrete example: if your build is failing because of a missing dep, and you grep the project to find the target containing that file, you will fail unless you remember to leave off the extensions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4480#-:-KYsu-dKRnfOg7eoo9gG:bpi14q7)*

**Comment by jwnimmer-tri** [comment]
This PR will not survive in this form.  Stay tuned.

**Pull request closed without merging**
