### PR TITLE
[doc] Explain the work-around for a kcov build error

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16371)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for both(!!:smile:!!) reviews, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: both!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16371#-:-MtJWeMUDD4BK0c-opfR:b-85g6dr)* status: 1 unresolved discussion, needs platform reviewer assigned, missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[doc/_pages/bazel.md, line 272 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16371#-MtJWg46E_DXW0wNCtxO:-MtJWg46E_DXW0wNCtxP:b-cwg7gk) ([raw file](https://github.com/robotlocomotion/drake/blob/6f1ac6a5c43b6bea2c40e165ecf8c2d19a125da2/doc/_pages/bazel.md#L272)):*
> ```Markdown
> script does not install kcov, and passing a ``--with-kcov`` option is an error.
> 
> In some cases, running kcov builds and regular builds from the same source
> ```

BTW, from the slack conversation, looks like we don't know the cause of the issue, only the fix, right?
___
*[doc/_pages/bazel.md, line 274 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16371#-MtJXQsu53mTyHbLIUsi:-MtJXQsu53mTyHbLIUsj:b-n9xfmo) ([raw file](https://github.com/robotlocomotion/drake/blob/6f1ac6a5c43b6bea2c40e165ecf8c2d19a125da2/doc/_pages/bazel.md#L274)):*
> ```Markdown
> In some cases, running kcov builds and regular builds from the same source
> tree will lead to Bazel error messages like "this rule is missing dependency
> declarations".  To resolve that problem, either running the kcov build from
> ```

nit, should the correct grammar here be "run the kcov build ..." instead of "running the kcov build"?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16371)* status: needs platform reviewer assigned (waiting on @xuchenhan-tri)

___
*[doc/_pages/bazel.md, line 272 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16371#-MtJWg46E_DXW0wNCtxO:-MtJaT_O3b_BGwgKo2Lu:b40sv40) ([raw file](https://github.com/robotlocomotion/drake/blob/6f1ac6a5c43b6bea2c40e165ecf8c2d19a125da2/doc/_pages/bazel.md#L272)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, from the slack conversation, looks like we don't know the cause of the issue, only the fix, right?
</blockquote></details>

Well, it's some bug in Bazel that has to do with us turning on and off the Bazel sandboxing within the same workspace.  It's pretty finicky to isolate and repro, so I haven't bothered to try to report to upstream.
___
*[doc/_pages/bazel.md, line 274 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16371#-MtJXQsu53mTyHbLIUsi:-MtJaSoWBWPFAepb3GBT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f1ac6a5c43b6bea2c40e165ecf8c2d19a125da2/doc/_pages/bazel.md#L274)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, should the correct grammar here be "run the kcov build ..." instead of "running the kcov build"?
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16371)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
