### PR TITLE
Remove PointPair lint.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/1930)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+1

**Comment by david-german-tri** [comment]
retest this please

**Comment by RussTedrake** [comment]
@jamiesnape -- do you know why the jenkins msvc64 build reported failure?  (all of the tests passed)

**Comment by david-german-tri** [comment]
Divided the file rename and the content changes into two separate commits, as requested by @jwnimmer-tri.

**Comment by RussTedrake** [comment]
fwiw - the drake006 failures were because the gurobi license expired.  i've just updated it.

**Pull request merged**
