### PR TITLE
py autodiff: Add autodiff_equal_to

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per Slack convo: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1619004863032400

Dunno what better naming should be, though.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!
+@russtedrake for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937#-:-MYtusToBnz21nPiI5pE:b-7h3j2f)* status: LGTM missing from assignees hongkai-dai,RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937#-:-MYuORVt8jFaoDnRdFX9:bg7igkv)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuNqLMBGbj0lbd30sg:b-6i1jtv) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
> ```Python
>     assert isinstance(a, AutoDiffXd), type(a)
>     assert isinstance(b, AutoDiffXd), type(b)
>     if a.value() == b.value():
> ```

BTW, could you document what happens if both a and b carries no gradient (for example, if `a` is constructed as AutoDiffXd(0.5)). I suppose in that case you only compare the value, but not the derivative? It might be helpful to add a unit test on this special case also.

The subtlety is that if `a` carries no gradient, but `b` carries gradient vector of all zero, then this function would return False. Which I think is the correct behavior, but it would be nice to document it.

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuPA2O1SUEETSqIs0m:b-opoh1f) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, could you document what happens if both a and b carries no gradient (for example, if `a` is constructed as AutoDiffXd(0.5)). I suppose in that case you only compare the value, but not the derivative? It might be helpful to add a unit test on this special case also.

The subtlety is that if `a` carries no gradient, but `b` carries gradient vector of all zero, then this function would return False. Which I think is the correct behavior, but it would be nice to document it.
</blockquote></details>

Semantically, an empty derivatives vector and and all-zero derivatives vector are identical.  My instinct is that code that requires fixed-size derivatives vectors (and so, needs zero-padding) should not rely on this routine to guard that, but rather should separately assert that the derivative sizes match its dimensionality expectations.  I would expect that a generally-named "autodiff_equal_to" function would treat empty and all-zero as equal.  (So, I think returning False in that case, as in r1 here, is a defect.)  If others come to the table with different default expectations I would like to hear about it, but that's at least how I see it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuR4Cy5Ky2HH0Xg7eJ:b-hw3twl) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
> Semantically, an empty derivatives vector and and all-zero derivatives vector are identical

Sorry but I think they are different.  An empty derivative vector means that its gradient could be an vector with arbitrary size and 0 value. OTOH, an AutoDiffXd with gradient as Vector4d::Zero() is fixed to a size-4 vector. So they have different meanings.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuRilX2-jDSsQKn5v_:bn6ba95) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> Semantically, an empty derivatives vector and and all-zero derivatives vector are identical

Sorry but I think they are different.  An empty derivative vector means that its gradient could be an vector with arbitrary size and 0 value. OTOH, an AutoDiffXd with gradient as Vector4d::Zero() is fixed to a size-4 vector. So they have different meanings.
</blockquote></details>

OK It was easy to implement both options. I personally don't care what default is for `semantic` hehe

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuSJVU2XWBWQH9hMmU:b-uf8lyt) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK It was easy to implement both options. I personally don't care what default is for `semantic` hehe
</blockquote></details>

FYI I think this PR is fine now.

We had this debate when writing the drake/automotive code years back.  It's impractical to ensure that every constant (a value without any derivatives) is padded with the exact number of zeros, since different problems will have different derivative sizes, and there is no easy way to feed the "problem size" into all of the nooks and crannies that need it.  Code that receives autodiff values must be robust against the derivatives being empty, instead of n-sized.  Usually this works automatically because AutoDiffXd does the right thing, but when users manually call `.derivatives()` and use it, they need to handle empty => n-zero promotion unless they can locally reason why it's impossible to b empty.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuTwdk0jvrfhtzoG2w:b-i7jpw1) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think this PR is fine now.

We had this debate when writing the drake/automotive code years back.  It's impractical to ensure that every constant (a value without any derivatives) is padded with the exact number of zeros, since different problems will have different derivative sizes, and there is no easy way to feed the "problem size" into all of the nooks and crannies that need it.  Code that receives autodiff values must be robust against the derivatives being empty, instead of n-sized.  Usually this works automatically because AutoDiffXd does the right thing, but when users manually call `.derivatives()` and use it, they need to handle empty => n-zero promotion unless they can locally reason why it's impossible to b empty.
</blockquote></details>

OK Ooh, from Jeremy's comment, updated n- vs. m-zero promotion. Accommodated as valid use case in contract + tests.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuUT3C8zbAgcEXwrg0:b-980l4k) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ooh, from Jeremy's comment, updated n- vs. m-zero promotion. Accommodated as valid use case in contract + tests.
</blockquote></details>

Er, also based on a connection of transitive / commutative / triangle whatever the formal word is for this relationship lol

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuUh-e9Ev5-OC34GUQ:bh5llwz) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er, also based on a connection of transitive / commutative / triangle whatever the formal word is for this relationship lol
</blockquote></details>

When semantic is True:
- empty cmp n-zero => True
- m-zero cmp n-zero => False

That's because, if you have one AutoDiffXd with n-zero and one with m-zero, any binops on them will fail at runtime.

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuV5Q1C0KPdA2BLPQp:b387d4m) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When semantic is True:
- empty cmp n-zero => True
- m-zero cmp n-zero => False

That's because, if you have one AutoDiffXd with n-zero and one with m-zero, any binops on them will fail at runtime.
</blockquote></details>

Hmm, actually, let me think again if I buy that.  One moment.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuVikvDyTVWVCHGVOl:bczqfpa) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's tricky, because what you want for unit test code is one thing, vs production code is another thing.  This function is clearly documented and does what it says on the tin, so I think its fine for now.
</blockquote></details>

I actually disagree that m-zero cmp n-zero => True. I think that is unexpected behavior. I would think if `a` carries a m-zero gradient while `b` carries n-zero gradient, they  take gradient w.r.t different variables, so they should not be the same.

I think the previous revision r2 works better, that m-zero cmp n-zero => False and empty cmp n-zero => True.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @EricCousineau-TRI, @hongkai-dai, and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuWGZG9xevDpHygQWC:b-lc2xoc) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I actually disagree that m-zero cmp n-zero => True. I think that is unexpected behavior. I would think if `a` carries a m-zero gradient while `b` carries n-zero gradient, they  take gradient w.r.t different variables, so they should not be the same.

I think the previous revision r2 works better, that m-zero cmp n-zero => False and empty cmp n-zero => True.
</blockquote></details>

Working: SGTM. Also, the prev version is more conservative, so it's easier to admit less-conservative behavior later than take it away.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MYuNqLMBGbj0lbd30sf:-MYuX-U82JFFt5EVu4EE:buqe3os) ([raw file](https://github.com/robotlocomotion/drake/blob/8c49ace018f164c65a07be63df2ecb9ad69615e0/bindings/pydrake/_autodiffutils_extra.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: SGTM. Also, the prev version is more conservative, so it's easier to admit less-conservative behavior later than take it away.
</blockquote></details>

Done. Reverted, added note.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14937#-:-MZ0hfwW38YrSWdrpO-y:btapcqv)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,RussTedrake(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 42 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14937#-MZ0gzHX91qPTpggE_2E:-MZ0gzHYCvYC_LadbnY_:b-ulqu30) ([raw file](https://github.com/robotlocomotion/drake/blob/4b956e0e5654df86d7a821eaee7d766e2b849e4f/bindings/pydrake/_autodiffutils_extra.py#L42)):*
> ```Python
> 
> @np.vectorize
> def autodiff_equal_to(a, b, *, semantic=False):
> ```

btw, i'm not a fan of our occasional use of * like this.  (it's also super difficult to google to find out what it means), and I tend to forget the details between reviewing your PRs..  ;-) 
https://stackoverflow.com/questions/2965271/forced-naming-of-parameters-in-python/14298976#14298976

**Comment by EricCousineau-TRI** [comment]
> btw, i'm not a fan of our occasional use of * like this

I *love* this feature, and wish C++ had something akin to it ;) Lemme know if there's a better to socialize this feature!

**Comment by sherm1** [comment]
Googling to try to figure out what `*` means I saw something that said conventionally it is written `*args` (apparently the name is ignored?). Maybe that would make it clearer for the uninitiated that it is vacuuming up arguments?

**Comment by EricCousineau-TRI** [comment]
Do these two sections help (4.7.3 at 4.7.4)?
- https://docs.python.org/3.6/tutorial/controlflow.html#special-parameters
- https://docs.python.org/3.6/tutorial/controlflow.html#arbitrary-argument-lists

(first party refs FTW!)

**Pull request merged**
