### PR TITLE
Disable spurious required MATLAB dependency not found warnings

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3374)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
Could you provide a little more context, please?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-:-KR50nBZDi5Q5UCYmbCv:b9vgthy)*

**Comment by jamiesnape** [comment]
For example,
```
Cannot find required pod snopt.
```
even when SNOPT is optional. You ran into it yesterday morning on the #buildcop Slack channel.

**Comment by jamiesnape** [comment]
For example,
```
Cannot find required pod snopt.
```
even when SNOPT is optional. You ran into it yesterday morning on the #buildcop Slack channel.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-:-KR51gOqX12B1Wd5Rj4I:bmtmhtv)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/util/checkDependency.m, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5aW5qMv7A1zSf_cWj:-KR5aW5qMv7A1zSf_cWk:bdeplee) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L3)):*
> ```objc
> function ok = checkDependency(dep,command)
> % Drake code which depends on an external library or program should
> % check that dependency by calling this function.
> ```

Could you please update this comment to explain the `nargout` behavior a little more explicitly?

---

*[drake/util/checkDependency.m, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5_mF-RMYW1jhv5z-b:-KR5_mF-RMYW1jhv5z-c:bs1se4k) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L101)):*
> ```objc
>     case 'lcmgl'
>       if nargout<1
>         checkDependency('lcm');
> ```

Oh, good grief, is this really how it works?  Let's not try to make this sane, but I think a comment is called for:

```
% If no outputs are being captured, the caller wants a console warning, so we don't
% capture any outputs on the recursive call either.
```

Edit for truthiness as needed, of course.

---

*[drake/util/checkDependency.m, line 104 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5aC47HiYKXqFTwKvv:-KR5aC48G6mkfxeFHjEk:b-7rxha6) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L104)):*
> ```objc
>         lcm_enabled = true;
>       else
>         % suppress warning
> ```

```
% If outputs are being captured, the caller does not want a console warning, so
% we capture outputs on the recursive call as well to suppress the warning.
```

---

*[drake/util/checkDependency.m, line 148 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5b1XmjaHcZhAqA7Tb:-KR5b1XmjaHcZhAqA7Tc:b-z626ur) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L148)):*
> ```objc
>       [conf.snopt_enabled,conf.studentsnopt_enabled] = snoptEnabled();
>       if (~conf.snopt_enabled && ~conf.studentsnopt_enabled)
>         conf.snopt_enabled = pod_pkg_config('snopt');
> ```

Are you sure this is equivalent?  It seems like it would be safer to emulate what you did above with the `lcm_enabled` variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3374)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/util/checkDependency.m, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5aW5qMv7A1zSf_cWj:-KR5iU1fKNTx-atk85LY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Could you please update this comment to explain the `nargout` behavior a little more explicitly?
</details>
Done.

---

*[drake/util/checkDependency.m, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5_mF-RMYW1jhv5z-b:-KR5iU_ocDIfyTx8gtAm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L101)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Oh, good grief, is this really how it works?  Let's not try to make this sane, but I think a comment is called for:
> 
> ```
> % If no outputs are being captured, the caller wants a console warning, so we don't
> % capture any outputs on the recursive call either.
> ```
> 
> Edit for truthiness as needed, of course.
</details>
Done.

---

*[drake/util/checkDependency.m, line 104 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5aC47HiYKXqFTwKvv:-KR5iV2pQXVI0hhxHZEc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L104)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> ```
> % If outputs are being captured, the caller does not want a console warning, so
> % we capture outputs on the recursive call as well to suppress the warning.
> ```
</details>
Done.

---

*[drake/util/checkDependency.m, line 148 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5b1XmjaHcZhAqA7Tb:-KR5iWTMkxb2EVnEnOVR:b-mgl2ie) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L148)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Are you sure this is equivalent?  It seems like it would be safer to emulate what you did above with the `lcm_enabled` variable.
</details>
Pretty sure, but I have no problem with keeping the extra snoptEnabled() call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3374)*

**Comment by jamiesnape** [comment]
PTAL @david-german-tri.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/util/checkDependency.m, line 148 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-KR5b1XmjaHcZhAqA7Tb:-KR99UpKZ62y3NPJM4-L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca172d39be2e60123afb63358b8794c45b3f23/drake/util/checkDependency.m#L148)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Pretty sure, but I have no problem with keeping the extra snoptEnabled() call.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-:-KR99Y1Ac3Q8o-hK0few:b5ioucd)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3374#-:-KREEIfV4BgHZCiYOoaA:bnfp4nl)*

**Pull request merged**
