### PR TITLE
Polished kuka_simulation Some More

### PR DESCRIPTION
**Pull request by liangfok**
I'm in the midst of writing a class that is nearly identical to `SimulatedKuka` but for another robot. I figured I might as well try to apply the changes I'm making in my other class to `SimulatedKuka`. Hopefully, by keeping them similar, common code can be extracted into a shared source file. Maybe in the future, the shared class can be called `SimulatedTorqueControlledRobotUsingPid`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4083)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sammy-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-:-KW4RP04QCZ1fQRlP6XC:bjquaum)*

**Comment by sammy-tri** [comment]
:lgtm: (pending platform review)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-KW4aXq6GccHB4cO_khB:-KW4aXq6GccHB4cO_khC:bui5bjm) ([raw file](https://github.com/robotlocomotion/drake/blob/477bc5c3620508480d32e9bdd449254a755d6b3e/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L192)):*
> ```cpp
>     }
>     DRAKE_DEMAND(controller_ != nullptr);
>     const RigidBodyTreed& tree = plant_->get_rigid_body_tree();
> ```

BTW Even though there's no scoping/shadowing issue, I'm not sure how I feel about reusing the tree variable name outside the block above (particularly since the comment calls out "tree" as being a special variable).  Might be excessively nitpick-y of me though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-:-KW4b4RyNHcQZ1xxMTpr:b43qcdi)*

**Comment by liangfok** [comment]
+@david-german-tri for platform review per rotation schedule.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-KW4aXq6GccHB4cO_khB:-KW4j-HysHgj33tPXEXe:b-qkeok6) ([raw file](https://github.com/robotlocomotion/drake/blob/477bc5c3620508480d32e9bdd449254a755d6b3e/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L192)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW Even though there's no scoping/shadowing issue, I'm not sure how I feel about reusing the tree variable name outside the block above (particularly since the comment calls out "tree" as being a special variable).  Might be excessively nitpick-y of me though.
</details>
Done. I renamed the variable "rigid_body_tree" to avoid confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-:-KW4j20bYWwdeG7HYeys:b-yjen0t)*

**Comment by liangfok** [comment]
I'm going to label this "Do no review" until after the merge conflicts are resolved.

**Comment by liangfok** [comment]
This PR passed pre-merge CI and is thus ready for platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-:-KWArD_38y9ZB_MounMj:b-xypaa1)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4083#-:-KWDbVjUVZlWUVCV4IOm:bnfp4nl)*

**Pull request merged**
