### PR TITLE
[doc] Refresh hydroelastic guide instructions for visualization

### LINKED ISSUE #18913: Hydroelastic user guide features is out of date
## Visualization
The user guide was written when `drake_visualizer` was still supported (and represented the "premium" hydro visualization mechanism). Those days are gone and it we should no longer feature that in the user guide. The discussion and images should be updated to reflect the current set of tools and visualization capabilities.

In addition to visual quality that hasn't currently been reproduced, we go so far as to show `drake_visualizer`-only visualizer configuration. E.g.: 

image

See the guide's current treatment on [Visualizing hydroelastic contact](https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html#hug_visualizing).

## Compliant meshes

There's no mention of introducing compliant meshes (as vtk file). This is obviously something that would likewise be worthwhile to note in the user guide.

### Version

v1.13.0

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In support of that, update the `ball_plate` demo to use Meldis.

Closes #18913.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

\CC @joemasterjohn @rpoyner-tri FYI

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with a few minor requests.  Thank you!

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-:-NeB6anD4mmd36f0Rpwt:b-l73x6j)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`examples/hydroelastic/ball_plate/README.md` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeB5Smi3eerV78Fi1jz:-NeB5Smi3eerV78Fi1k-:b-8vruez) ([raw file](https://github.com/RobotLocomotion/drake/blob/acec3ca844393b944f5882ea946e3e03658af65f/examples/hydroelastic/ball_plate/README.md#L13)):*
> ```Markdown
> In the source code, this example shows how to set up bodies by loading SDFormat
> files and also calling C++ APIs.
> ```

Question.  Is it easy to use image from a different directory in README.md?  If so, could we use `multibody/hydroelastics/images/drake-vis-01.png` here?

Please feel free to skip this request.
___
*[`examples/hydroelastic/ball_plate/README.md` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeAu6nD4vtVzCEA019v:-NeAu6nE7sk0O6qb0eeT:b-14d7n8) ([raw file](https://github.com/RobotLocomotion/drake/blob/acec3ca844393b944f5882ea946e3e03658af65f/examples/hydroelastic/ball_plate/README.md#L63)):*
> ```Markdown
> -- --simulator_target_realtime_rate=0.01 \
> --contact_surface_representation=triangle
> ```
> ```

Switching between polygons and triangles, we cannot draw mesh wireframes to clearly distinguish them (related #17681). I wonder whether we can remove this section from README (the code is still available for advanced users to try).

It's fine with me to keep it too.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 344 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeB08mt6nTI7611Ub8B:-NeB08mu7hWZaPo5YiNN:b-ph7jah) ([raw file](https://github.com/RobotLocomotion/drake/blob/acec3ca844393b944f5882ea946e3e03658af65f/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L344)):*
> ```objc
> 
> In the above picture, we see two red force vectors acting at the centroids of
> the two contact surfaces and also the blue moment vector. One contact surface
> ```

nit: "the **two** blue moment vector**s**"



_Suggestion:_
```objc
the two contact surfaces and also the two blue moment vectors. One contact surface
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 358 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeB3Te7BzaKX4CwK_rS:-NeB3Te7BzaKX4CwK_rT:b-7m6t46) ([raw file](https://github.com/RobotLocomotion/drake/blob/acec3ca844393b944f5882ea946e3e03658af65f/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L358)):*
> ```objc
> When viewing collisions, note that red contact arrows indicate a hydroelastic
> collision, with an associated collision patch. Green contact arrows indicate
> point contact collision, which does not have any contact patch.
> ```

nit: 



_Suggestion:_
```objc
When viewing collisions, note that red arrows indicate a hydroelastic
contact, with an associated contact patch. Green arrows indicate
point contact, which does not have any contact patch.
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-:-NeBkT2j4rh953yBAGyu:bybe5xg)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`examples/hydroelastic/ball_plate/README.md` line 13 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeB5Smi3eerV78Fi1jz:-NeBkKJ41tRZ4GcvC047:bg1oi1m) ([raw file](https://github.com/RobotLocomotion/drake/blob/acec3ca844393b944f5882ea946e3e03658af65f/examples/hydroelastic/ball_plate/README.md#L13)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Question.  Is it easy to use image from a different directory in README.md?  If so, could we use `multibody/hydroelastics/images/drake-vis-01.png` here?

Please feel free to skip this request.
</blockquote></details>

Seems like yes:

https://github.com/jwnimmer-tri/drake/tree/doc-hug-visualization/examples/hydroelastic/ball_plate
___
*[`examples/hydroelastic/ball_plate/README.md` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeAu6nD4vtVzCEA019v:-NeBk4aj-c4nWoVJI_CO:b3pmsfp) ([raw file](https://github.com/RobotLocomotion/drake/blob/acec3ca844393b944f5882ea946e3e03658af65f/examples/hydroelastic/ball_plate/README.md#L63)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Switching between polygons and triangles, we cannot draw mesh wireframes to clearly distinguish them (related #17681). I wonder whether we can remove this section from README (the code is still available for advanced users to try).

It's fine with me to keep it too.
</blockquote></details>

I can see a difference even with the current visualization tooling.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175)* status: LGTM missing from assignee sherm1(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-:-NeEPs0m0j9ysmsDKXN9:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc` line 132 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeECoE88B3tfBJ6_CQ1:-NeECoE88B3tfBJ6_CQ2:b91zj09) ([raw file](https://github.com/RobotLocomotion/drake/blob/6ab00f22b5f35b2ce439503ecc60c1d55dd528a7/examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc#L132)):*
> ```cpp
> This is an example of using the hydroelastic contact model with a non-convex
> collision geometry loaded from an SDFormat file of a dinner plate. The ball,
> the plate, and the floor are compliant, rigid, and compliant hydroelastic.
> ```

nit give reader an additional clue



_Suggestion:_
```cpp
and compliant hydroelastic respectively.
```
___
*[`examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc` line 133 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-NeED6Jn780DJSJaoczr:-NeED6JoD36DEeCI45RB:bolhmnb) ([raw file](https://github.com/RobotLocomotion/drake/blob/6ab00f22b5f35b2ce439503ecc60c1d55dd528a7/examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc#L133)):*
> ```cpp
> collision geometry loaded from an SDFormat file of a dinner plate. The ball,
> the plate, and the floor are compliant, rigid, and compliant hydroelastic.
> The plate-ball, ball-floor, and plate-floor contacts are rigid-compliant,
> ```

nit more flow clues



_Suggestion:_
```cpp
Hence, the plate-ball
```

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175#-:-NeESYef5lKEH02H5ox8:b8qx53o)* status: 2 unresolved discussions

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20175)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy

**Pull request merged**
