### PR TITLE
Gurobi7

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6332)

### CODE REVIEW

**Comment by soonho-tri** [comment]
I've tested it on my local macs and it worked well with Gurobi-7.0.2.

META: `7.02` -> `7.0.2`.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmY5LzJqC7V5r3ZMK4X:b-b088tw)*

**Comment by jamiesnape** [comment]
We will need to coordinate merging this with reverting https://github.com/RobotLocomotion/drake-ci/commit/6ca905511e880cee56911b004919334e20c3d3ea.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@linux-clang-bazel-experimental-everything please
@linux-gcc-bazel-experimental-everything please
@linux-xenial-clang-bazel-experimental-everything please
@linux-xenial-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
All CI images have been updated with Gurobi 7.0.2

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
Interesting. Fractionally outside the epsilons on a small number of tests.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-experimental please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmcUpDY4W_Xe7NJjwsc:bosc1ce)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmcwJL6hOZPj2Nyd0A3:bxgq5xs)*

**Comment by soonho-tri** [comment]
FYI, `mac-clang-experimental` build failed. It seems that `drake/multibody/multibody_tree/test/double_pendulum_test.cc` needs an update:

```
3509 [ RUN      ] PendulumKinematicTests.CalcPositionKinematics
3510 drake/multibody/multibody_tree/test/double_pendulum_test.cc:496: Failure
3511 Value of: X_WL.matrix().isApprox(X_WL_expected.matrix(), kEpsilon)
3512   Actual: false
3513 Expected: true
3514 drake/multibody/multibody_tree/test/double_pendulum_test.cc:496: Failure
3515 Value of: X_WL.matrix().isApprox(X_WL_expected.matrix(), kEpsilon)
3516   Actual: false
3517 Expected: true
```

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-Kmevc5tYbjddQV0XSYp:bd7ljxl)*

**Comment by hongkai-dai** [comment]
This error is really strange to me. I added a break point inside `gurobi_solver`, but that break point is never triggered, when I run this test. 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmlviFb1QfUYnwgu4GC:bxv51f6)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmlwnOF5apMdV9lY99B:bosc1ce)*

**Comment by soonho-tri** [comment]
I can't reproduce the error on my local macs. I also do not understand why the test is related to gurobi.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-Kmm0_Ki_QzYxcnnDHuV:b14vfza)*

**Comment by soonho-tri** [comment]
+@soonho-tri 
:lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmmcFFkL-XUm3_uS3LQ:b-denpm8)*

**Comment by soonho-tri** [comment]
+@jamiesnape , feature-review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmmcOjHIHB4N6n5cu-O:bgwxwsk)*

**Comment by jamiesnape** [comment]
:lgtm:

(Leave the "do not merge". I will merge on Monday when it quieter.)

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6332#-:-KmmeM7-b1Ro_ulrGJGk:bmsjuiy)*

**Comment by jwnimmer-tri** [comment]
This PR failed to update the installation documentation to refer to Gurobi 7 (`drake/doc/from_source.rst` and `drake/doc/bazel.rst`).  @jamiesnape or @soonho-tri or @hongkai-dai could you fix it?

**Comment by soonho-tri** [comment]
@jwnimmer-tri , I'm working on it.

**Pull request merged**
