### PR TITLE
Make MemoryFile and Sha256 pickleable

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
+@jwnimmer-tri 
+(release notes: feature)  (this should be rolled into the release notes on the introduction of MemoryFile).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6X9EirAuDv0ax2AS7d:bj8wn8w)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`bindings/pydrake/common/module_py.cc` line 188 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6X9ToNBGVy-Oir5Fq2:-O6X9ToNBGVy-Oir5Fq3:b-oyukih) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8be4c632688f3d6949880898060250910e1ad55/bindings/pydrake/common/module_py.cc#L188)):*
> ```cpp
>         .def(py::pickle(
>             [](const MemoryFile& self) {
>               // TODO(SeanCurtis-TRI): Should we be including the sha256 as we
> ```

Should I be pickling the sha value in any form given that I can't unpickle the value and *set* it in a `MemoryFile`? I'll be recomputing it.

Although, it's a nice way to confirm that the unpickled memory file is what was pickled. 

Thoughts?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

Pickling is hairy enough that we should use the regular sets of eyes, so -(status: single reviewer ok).

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6XYd8u88Z_ZI2eRJug:b2k0gn2)* status: 4 unresolved discussions

___
*[`bindings/pydrake/common/module_py.cc` line 188 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6X9ToNBGVy-Oir5Fq2:-O6XTMir8kJHz-8zMJ4a:b56k82) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8be4c632688f3d6949880898060250910e1ad55/bindings/pydrake/common/module_py.cc#L188)):*
> Should I be pickling the sha value in any form ...

I would lean towards "no".

Also, I would suggest a different approach entirely: I think `__getstate__` should return a `dict` such that the job of `__setstate__` is just to call the (python) constructor with that unpicked dict as the `**kwargs`.  That will be much more durable over time than a tuple, as the scope of (and names for) what's being pickled evolves.  So in this case `contents` and `extension` and `filename_hint` would be dict keys.

> Although, it's a nice way to confirm that the unpickled memory file is what was pickled.

I don't think it's necessary to cross-check that python's built-in pickler I/O is sound.
___
*[`bindings/pydrake/common/module_py.cc` line 160 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6XT9Q24ecf2kZYwVjK:-O6XT9Q24ecf2kZYwVjL:b-2a3snm) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f54ce245e1cc0dfb584ca7a69b1a11ee767c868/bindings/pydrake/common/module_py.cc#L160)):*
> ```cpp
>             [](const std::string& ascii_hash) {
>               std::optional<Sha256> sha_maybe = Sha256::Parse(ascii_hash);
>               DRAKE_DEMAND(sha_maybe.has_value());
> ```

nit Bad data on disk should be something like RuntimeError, not SystemExit.



_Suggestion:_
```cpp
DRAKE_THROW_UNLESS
```
___
*[`bindings/pydrake/common/test/module_test.py` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6XWd2O4tRRMzcLQyuq:-O6XWd2O4tRRMzcLQyur:bixk5h9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f54ce245e1cc0dfb584ca7a69b1a11ee767c868/bindings/pydrake/common/test/module_test.py#L63)):*
> ```Python
> 
>         assert_pickle(self, file, lambda f: [f.contents(), f.extension(),
>                                              f.sha256(), f.filename_hint()])
> ```

This comparison tactic is somewhat susceptible to bitrot.  If we were to add a new attribute to the class, we might forget to add it here also?

WDYT about using `assert_pickle(self, file, repr)` instead?
___
*[`bindings/pydrake/common/test/module_test.py` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6XXGoI60HY2MwsKe_l:-O6XXGoI60HY2MwsKe_m:b3d022c) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f54ce245e1cc0dfb584ca7a69b1a11ee767c868/bindings/pydrake/common/test/module_test.py#L63)):*
> ```Python
> 
>         assert_pickle(self, file, lambda f: [f.contents(), f.extension(),
>                                              f.sha256(), f.filename_hint()])
> ```

One hazard to think about with pickling is backwards compatibility.

For example, if at some point we decide to rename `contents` to `content` in the constructor kwarg, getter function, etc. it's easy to imagine that we touch on all of the normal places for deprecation (overload the constructor and deprecated the older overload, deprecate the old getter and add a new one, etc.) but forget to consider what happens when the user tries to load a pkl file from older pydrake into a more modern pydrake.

To help guard against that, sometimes we write regression tests that start from a `bytes` array literal (akin to a pkl on disk), only do the unpickle step, and then check that the new object was rehydrated correctly.  See for example `def test_legacy_unpickle_tree_module` in `plant_test.py`.

I am not sure if we should _require_ that on all new pickling code, but it seems like plausibly a good idea so maybe we should discuss.

**Review by SeanCurtis-TRI — COMMENTED** [review]
FYI In retrospect, we can defer this a bit. Ultimately, `Shape`s are currently pickleable. So, before I make the `MeshSource` the storage for `Mesh` and `Convex` we'll have four classes that need to be pickleable (`MemoryFile`, `FileSource`, `InMemoryMesh`, `MeshSource`). I figured if this was straight forward, I could get this figured out on the class that already merged to master and then apply the solution to the other classes. However, as long as it gets resolved (in some way) soon, we're good.

For context "soon" is defined by the fact that adding `MeshSource` and `Mesh` and `Convex` is (one of) the PR(s) that will follow up #21890.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6Xldxq1TohwGdQ5rzM:b-eb4hvm)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/module_py.cc` line 188 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6X9ToNBGVy-Oir5Fq2:-O6XmnLa1jUF2P16CA9U:b-bsbte0) ([raw file](https://github.com/RobotLocomotion/drake/blob/c8be4c632688f3d6949880898060250910e1ad55/bindings/pydrake/common/module_py.cc#L188)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Should I be pickling the sha value in any form ...

I would lean towards "no".

Also, I would suggest a different approach entirely: I think `__getstate__` should return a `dict` such that the job of `__setstate__` is just to call the (python) constructor with that unpicked dict as the `**kwargs`.  That will be much more durable over time than a tuple, as the scope of (and names for) what's being pickled evolves.  So in this case `contents` and `extension` and `filename_hint` would be dict keys.

> Although, it's a nice way to confirm that the unpickled memory file is what was pickled.

I don't think it's necessary to cross-check that python's built-in pickler I/O is sound.
</blockquote></details>

There were more traps in getting to this final point than I'd expected. Tragic considering how simple the final solution was.
___
*[`bindings/pydrake/common/test/module_test.py` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6XWd2O4tRRMzcLQyuq:-O6XwlARC5iw58ajjsEF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f54ce245e1cc0dfb584ca7a69b1a11ee767c868/bindings/pydrake/common/test/module_test.py#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comparison tactic is somewhat susceptible to bitrot.  If we were to add a new attribute to the class, we might forget to add it here also?

WDYT about using `assert_pickle(self, file, repr)` instead?
</blockquote></details>

Done.
___
*[`bindings/pydrake/common/test/module_test.py` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6XXGoI60HY2MwsKe_l:-O6Xz2Z5CSW13nR48Jy2:b-cfiwxg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f54ce245e1cc0dfb584ca7a69b1a11ee767c868/bindings/pydrake/common/test/module_test.py#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One hazard to think about with pickling is backwards compatibility.

For example, if at some point we decide to rename `contents` to `content` in the constructor kwarg, getter function, etc. it's easy to imagine that we touch on all of the normal places for deprecation (overload the constructor and deprecated the older overload, deprecate the old getter and add a new one, etc.) but forget to consider what happens when the user tries to load a pkl file from older pydrake into a more modern pydrake.

To help guard against that, sometimes we write regression tests that start from a `bytes` array literal (akin to a pkl on disk), only do the unpickle step, and then check that the new object was rehydrated correctly.  See for example `def test_legacy_unpickle_tree_module` in `plant_test.py`.

I am not sure if we should _require_ that on all new pickling code, but it seems like plausibly a good idea so maybe we should discuss.
</blockquote></details>

Would it make sense to include a version number in the state and unpickle based on the version number? That would maintain backwards compatibility. And, in the case of choosing to deprecate an old version, we can place a deprecation warning within the __setstate__. I imagined a tuple of `(version_number, kwarg_dict)` as the result of `__getstate__`.

This would be, of course, in conjunction with the regression test you mention above.

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks, that makes sense, I just hadn't perceived it.

We'll need to carefully add more `Mesh` and `Convex` pickling regression tests, before we start changing those pickling implementations.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6YDrPvBePY3Muw4YSB:b-h6yauj)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/test/module_test.py` line 63 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6XXGoI60HY2MwsKe_l:-O6YCrsN3CwxVhTimhhW:bl8s1re) ([raw file](https://github.com/RobotLocomotion/drake/blob/4f54ce245e1cc0dfb584ca7a69b1a11ee767c868/bindings/pydrake/common/test/module_test.py#L63)):*
My gut feeling is that "let the data speak for itself" is the most durable approach.  Epoch-like version numbers have problems with linearity (e.g., if a person forks drake, or we ever start making patch releases).

At such a time as we need to preserve backcompat, the code can look at which fields are present in the dict, and adapt accordingly.  Adding a number beside the attributes is, in a sense, redundant and violates "don't repeat yourself".  The situation where more details would be important is when we change the semantics without changing the name.  But even there, I think something like "y_up: False" in the dict is better than some number.

> ... we can place a deprecation warning within the `__setstate__` ...

This is probably wrong.  Generally, we will never deprecate the ability to load old data.  Or at least, not without a very very long fuse (much longer than the 3-month window on code API deprecation), as well as a file conversion tool that auto-upgrades people's pkls on disk across the boundary.
___
*[`bindings/pydrake/common/test/module_test.py` line 66 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-O6YCeZg7AeUwQKZgzjG:-O6YCeZg7AeUwQKZgzjH:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/94334d390650a514320b0c96396b15719c6f9be9/bindings/pydrake/common/test/module_test.py#L66)):*
> ```Python
> 
>         # Check that data pickled as MemoryFile in Drake v1.33.0 can be
>         # unpickeled in newer versions. The data should produce a MemoryFile
> ```

typo



_Suggestion:_
```Python
unpickled
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6YH0HHCG6FfDDZNeSv:bppyoqq)* status: LGTM missing from assignee sherm1(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Slick! Platform :lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6YbDByDDFWgo7fWrFt:bz1d6rr)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
However ... this failed to build on Noble in CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21895#-:-O6Ybh0DA3_8FH2hrLT2:b-s3vopl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Comment by jwnimmer-tri** [comment]
I don't understand that error.  Let's try it again?

@drake-jenkins-bot linux-noble-gcc-bazel-experimental-release please

**Pull request merged**
