### PR TITLE
[WIP] Add DRAKE_ASSERT, DRAKE_FAIL, and DRAKE_FAIL_UNLESS capability

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add `DRAKE_...` assertion-like macros as a step towards #1935.  This does not yet offer CMake options to force Drake assertions on or off, nor other exception-throwing or string-formatting tools.

This PR will serve to provide platform-matrix build coverage during development.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2536)

### CODE REVIEW

**Comment by liangfok** [comment]
Very nice!

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### \[WIP\] Add DRAKE\_ASSERT, DRAKE\_FAIL, and DRAKE\_FAIL\_UNLESS capability
> 
> Add `DRAKE_...` assertion-like macros as a step towards #1935.  This does not yet offer CMake options to force Drake assertions on or off, nor other exception-throwing or string-formatting tools.
> 
> 
> 
> This PR will serve to provide platform-matrix build coverage during development.
> 
> 
> 
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/common/drake_assert.cc, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJs5m9wPVF_ahesD2dV:-KJs5m9wPVF_ahesD2dW:1313293324) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.cc#L9)):*
> ```cpp
> 
> void Fail(const char* condition, const char* func, const char* file, int line) {
>   std::cerr << "error: Fail at " << file << ":" << line << " in " << func;
> ```

To make errors more easily findable in a giant log file, can "error:" be something more unique like "DRAKE_ERROR:"?

---

*[drake/common/drake_assert.h, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJs6iVWFX7t1FNz8f1L:-KJs6iVX4XAypb1HAISB:25775119) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L8)):*
> ```objc
> /// @file
> /// Provides Drake's assertion implementation.  This is intended to be
> /// used both within Drake and by other software.
> ```

Can "other software" be more specific? Like maybe "other software that treats Drake as a dependency"?

---

*[drake/common/drake_assert.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsD2LXliytqRmO32Ik:-KJsD2LXliytqRmO32Il:-2116714523) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L26)):*
> ```objc
> /// @p condition within @p DRAKE_ASSERT is always syntax-checked, even if
> /// Drake's assertions are disarmed.  This means that @p DRAKE_ASSERT may only
> /// be used at block scope (not as an expression), and that it must always be
> ```

If one attempts to use `DRAKE_ASSERT` as an expression, will it result in a compile-time error?

---

*[drake/common/drake_assert.h, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsDDL2v_QLIker6kBE:-KJsDDL2v_QLIker6kBF:-1100685673) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L27)):*
> ```objc
> /// Drake's assertions are disarmed.  This means that @p DRAKE_ASSERT may only
> /// be used at block scope (not as an expression), and that it must always be
> /// followed by a semicolon.
> ```

Why not include the semicolon within the macro?

---

*[drake/common/drake_assert.h, line 57 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsFJ-KmwDcAv2541Hv:-KJsFJ-KmwDcAv2541Hw:116635005) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L57)):*
> ```objc
> 
> #define DRAKE_FAIL_UNLESS(condition)                            \
>   (!!(condition) ?                                              \
> ```

BTW, it might be a good idea to add a short comment why `!!` is necessary.

---

*[drake/common/drake_assert.h, line 58 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsFZikrYvlAMxM92wL:-KJsFZikrYvlAMxM92wM:-1877436889) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L58)):*
> ```objc
> #define DRAKE_FAIL_UNLESS(condition)                            \
>   (!!(condition) ?                                              \
>    static_cast<void>(0) :                                       \
> ```

Is the above equal to a no-op?

---

*[drake/common/drake_assert.h, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsFglh82nsWAiDT2-9:-KJsFglh82nsWAiDT2-A:1292687508) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L65)):*
> ```objc
> #define DRAKE_ASSERT(condition) static_assert(                  \
>       std::is_convertible<decltype(condition), bool>::value,    \
>       "Assertion condition should be bool-convertible")
> ```

Missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-:-KJsFqXQleBHrUYRjE__:-1161853985)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/drake_assert.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsD2LXliytqRmO32Ik:-KJuRXMpvIn-RUByD4Yi:-747539741) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> If one attempts to use `DRAKE_ASSERT` as an expression, will it result in a compile-time error?
</details>
In r1, it sometimes did, depending on the arming status.  In r2 now, it always does.

---

*[drake/common/drake_assert.h, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsDDL2v_QLIker6kBE:-KJuPDinsrvOzaNVjG3w:133499274) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Why not include the semicolon within the macro?
</details>
Standard C practice is to omit the semicolon.

---

*[drake/common/drake_assert.h, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsFglh82nsWAiDT2-9:-KJuPw8g6wTehbmk3Gra:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L65)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing period at end of sentence.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
:lgtm_strong: 

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Very nice!
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/drake_assert.h, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJsDDL2v_QLIker6kBE:-KJuemdEWAcVhWuRuLyE:-1839971143) ([raw file](https://github.com/robotlocomotion/drake/blob/5fe89bfd256753dd610397d103a0642a7f5eda72/drake/common/drake_assert.h#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Standard C practice is to omit the semicolon.
</details>
Ah, I see that there are also [control flow motivations](https://www.securecoding.cert.org/confluence/display/c/PRE11-C.+Do+not+conclude+macro+definitions+with+a+semicolon) for not including a semicolon within the macro. TIL

---

*[drake/common/drake_assert.h, line 63 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJufKhNgQ-BulD1hWVl:-KJufKhNgQ-BulD1hWVm:-60082279) ([raw file](https://github.com/robotlocomotion/drake/blob/a7c8df38bfb858cdefc858153d3f6017a823853b/drake/common/drake_assert.h#L63)):*
> ```objc
>     }                                                           \
>   } while (0)
> ```

BTW, this is a lot clearer now. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-:-KJufRTAuWrMPOZxm5pt:-1868698381)*

**Comment by sherm1** [comment]
Well, I was taking the "do not review" tag seriously but I see I'm behind now! I like this a lot. I think the "FAIL" term is too soft though -- that sounds too much like an ordinary error. I suggest `DRAKE_ABORT_UNLESS` or something equally violent.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :lgtm_strong: 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-:-KJvF95dOs3PC-l70Ua7:-1296259370)*

**Comment by sherm1** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/drake_assert.cc, line 8 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJvFeSaGHSBgnqzXdBl:-KJvFeSaGHSBgnqzXdBm:1086998817) ([raw file](https://github.com/robotlocomotion/drake/blob/a7c8df38bfb858cdefc858153d3f6017a823853b/drake/common/drake_assert.cc#L8)):*
> ```cpp
> namespace drake {
> 
> void Fail(const char* condition, const char* func, const char* file, int line) {
> ```

Call this `drake::Abort()`

---

*[drake/common/drake_assert.h, line 11 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJvFurDVrwCN4FvQe5p:-KJvFurDVrwCN4FvQe5q:-156093762) ([raw file](https://github.com/robotlocomotion/drake/blob/a7c8df38bfb858cdefc858153d3f6017a823853b/drake/common/drake_assert.h#L11)):*
> ```objc
> 
> #ifdef DRAKE_DOXYGEN_CXX
> /// @p DRAKE_ASSERT(condition) is similar to the built-in @p assert(condition)
> ```

BTW, consider using back-tics for literals rather than `@p`, which is supposed to mean "parameter", though doesn't actually do anything more than highlight (which highlighting doesn't even match displayed parameters) and probably won't highlight past punctuation. Doxygen supports Markdown, so you can use 
```
`DRAKE_ASSERT(condition)`
```
which will come out in a monospaced code-looking font.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_assert.cc, line 8 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJvFeSaGHSBgnqzXdBl:-KJwi0TmD200MiSNGYBz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a7c8df38bfb858cdefc858153d3f6017a823853b/drake/common/drake_assert.cc#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Call this `drake::Abort()`
</details>
Done.

---

*[drake/common/drake_assert.h, line 11 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-KJvFurDVrwCN4FvQe5p:-KJwihpIz82mLZvUiZp3:-187884595) ([raw file](https://github.com/robotlocomotion/drake/blob/a7c8df38bfb858cdefc858153d3f6017a823853b/drake/common/drake_assert.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, consider using back-tics for literals rather than `@p`, which is supposed to mean "parameter", though doesn't actually do anything more than highlight (which highlighting doesn't even match displayed parameters) and probably won't highlight past punctuation. Doxygen supports Markdown, so you can use 
> ```
> `DRAKE_ASSERT(condition)`
> ```
> which will come out in a monospaced code-looking font.
</details>
My primary use case for doxygen is browsing code in emacs, for which doxymacs mode knows about `@p` but not markdown (https://github.com/pniedzielski/doxymacs/issues/2); so this format is superior for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536)*

**Comment by sherm1** [comment]
:lgtm:

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Well, I was taking the "do not review" tag seriously but I see I'm behind now! I like this a lot. I think the "FAIL" term is too soft though -- that sounds too much like an ordinary error. I suggest `DRAKE_ABORT_UNLESS` or something equally violent.
</details>


---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536#-:-KJwtqxOVc1gUe3_qkZK:1417088721)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2536)*

**Comment by jwnimmer-tri** [comment]
Will resurrect under a new PR.

**Pull request closed without merging**
