### PR TITLE
add RigidBodyTree python constructor using FloatingBaseType enum

### PR DESCRIPTION
**Pull request by rdeits**
and deprecate the string joint_type argument

ref #4950

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5159)

### CODE REVIEW

**Comment by rdeits** [comment]
This is blocked by https://github.com/RobotLocomotion/drake/pull/5158

**Comment by rdeits** [comment]
Unlocked, but needs tests run again

**Comment by rdeits** [comment]
@drake-jenkins-bot retest this please

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by rdeits** [comment]
+@mwoehlke-kitware +@sammy-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5159#-:-Kd1ktdPBQg7ZY0wLvrK:b-8pa1rm)*

**Comment by rdeits** [comment]
@mwoehlke-kitware this addresses your request from #4949 to pass the FloatingBaseType as an enum rather than a string.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5159#-:-Kd1o7qq8-LwMgWsTFM_:bnfp4nl)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/testRBTTransformPoints.py, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5159#-Kd24WFtDTvE1uHJLeaf:-Kd24WFuV2caKSAIitEj:b-26hfwf) ([raw file](https://github.com/robotlocomotion/drake/blob/911255d995aa3d2c6a394d966cbfd9c32e63eacf/drake/bindings/python/pydrake/test/testRBTTransformPoints.py#L24)):*
> ```Python
>     def test_gradient(self):
>         r = pydrake.rbtree.RigidBodyTree(
>             os.path.join(pydrake.getDrakePath(), "examples/Pendulum/Pendulum.urdf"),
> ```

BTW this wasn't a long line until it got moved up by this change...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5159#-:-Kd242UVqYRJgo1DNIZO:bsf2vkf)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5159)*

**Comment by rdeits** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/testRBTTransformPoints.py, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5159#-Kd24WFtDTvE1uHJLeaf:-Kd2RIrfIHHYgFt-VPN-:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/911255d995aa3d2c6a394d966cbfd9c32e63eacf/drake/bindings/python/pydrake/test/testRBTTransformPoints.py#L24)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this wasn't a long line until it got moved up by this change...
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5159)*

**Pull request merged**
