### PR TITLE
[geometry] Fix MeshcatVisualizer initialization of alpha slider

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #19287.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19813)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please, if you have time.  Otherwise we can pass it over to @trowell-tri for feature review once he has bandwidth again (next week).

**Comment by jwnimmer-tri** [comment]
I suppose @rpoyner-tri has some skin in the same for the sliders code, also feel free to jump in as a reviewer if you have time.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19813#-:-N_kxf2L9JiI9y1mUl82:bmxilld)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/meshcat_visualizer.cc` line 207 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19813#-N_kuhcnE1GlCOjqnHWc:-N_kuhcnE1GlCOjqnHWd:bvz8d33) ([raw file](https://github.com/RobotLocomotion/drake/blob/88b434d7d898cd1f7a27b3481fdcc7f9b42e5c3a/geometry/meshcat_visualizer.cc#L207)):*
> ```cpp
>       const std::string path =
>           fmt::format("{}/{}", frame_path, geom_id.get_value());
>       const Rgba rgba = properties.GetPropertyOrDefault("phong", "diffuse",
> ```

BTW As a sneak preview of an issue I'll be opening today, this line fights mightily with `Mesh`es that have material properties (.objs or .gltfs). Stay tuned for more.
___
*[`geometry/test/meshcat_visualizer_test.cc` line 565 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19813#-N_kxGDaCc76-EMge4AR:-N_kxGDaCc76-EMge4AS:b-ry8fts) ([raw file](https://github.com/RobotLocomotion/drake/blob/88b434d7d898cd1f7a27b3481fdcc7f9b42e5c3a/geometry/test/meshcat_visualizer_test.cc#L565)):*
> ```cpp
>         fmt::format("visualizer/box/box/{}", geom_id.get_value());
>     diagram->ForcedPublish(*context);
> ```

BTW It seems to me that you have to eliminate the null-hypothesis. The color property should *not* have been updated at this point.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19813)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/test/meshcat_visualizer_test.cc` line 565 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19813#-N_kxGDaCc76-EMge4AR:-N_l22ZI7SrGjBsuzuS8:b76v6ga) ([raw file](https://github.com/RobotLocomotion/drake/blob/88b434d7d898cd1f7a27b3481fdcc7f9b42e5c3a/geometry/test/meshcat_visualizer_test.cc#L565)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It seems to me that you have to eliminate the null-hypothesis. The color property should *not* have been updated at this point. 
</blockquote></details>

Yeah, I suppose its clearer if I do so.  PTAL.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19813#-:-N_lK2t3EaD0ZS2dcpCo:bmxilld)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19813#-:-N_oGzfR8t5BXlPDTiQ7:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
