### PR TITLE
Model directives fail to load deep nested weld tests

### PR DESCRIPTION
**Pull request by marcoag**
As suggested by VC regarding the changes in https://github.com/RobotLocomotion/drake/pull/17223.

This PR adds a test that serves as an example that Model Directives currently fails to load welds with a deep nested child and welds to a frame with a deep nested base frame.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090)

### CODE REVIEW

**Comment by sherm1** [comment]
@drake-jenkins-bot ok to test

**Comment by sherm1** [comment]
What is the status of this PR? Should it be reviewed and merged or does it have to wait for something to get fixed?

**Comment by marcoag** [comment]
@EricCousineau-TRI can probably confirm this, but I don't think this is waiting for any fix. AFAIK the intention of this PR is just to create these tests as examples of current failing cases for model directives that might be improved in the future but won't be fixed at this point.

**Review by rpoyner-tri — COMMENTED** [review]
Good day, @marcoag . I’m assigning +@EricCousineau-TRI  as the most relevant team member to assist with this pull request. If you already had a different team member in mind, please let us know. To @EricCousineau-TRI , feel free to delegate in case there is someone else more suitable.

Another option is to label this `do not merge`, if it is not destined for merging.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-:-NRmnJfG6hjugIIHGKVE:bsmvc37)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Sorry for delay, but :lgtm: with request to relax upstream error condition - let me know if you'd like me to make the change

+@sherm1 for platform review, please!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-:-NV6mnynBzEKY9Qigfb9:b-am95p4)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @marcoag and @sherm1)

___
*[`multibody/parsing/test/process_model_directives_test.cc` line 382 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-NV6mdjHB0p7OLL2QvTh:-NV6mdjHB0p7OLL2QvTi:br8emua) ([raw file](https://github.com/RobotLocomotion/drake/blob/13a6073513576a2d35c3e6eec6ce354cde819ba9/multibody/parsing/test/process_model_directives_test.cc#L382)):*
> ```cpp
> 
>   EXPECT_EXIT(
>       ProcessModelDirectives(directives, &plant, nullptr,
> ```

We should not be failing via `SIGABRT` here.

Can you change error condition to throw an exception?
(I assume it would involve replacing `DRAKE_DEMAND` with `DRAKE_THROW_UNLESS`)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending resolution of Eric's request to change the existing error condition.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-:-NV6tKW1CzNxEm1H8g-f:b-kjnzim)* status: 1 unresolved discussion, missing label for release notes (waiting on @marcoag)

**Review by sherm1 — COMMENTED** [review]
@EricCousineau-TRI I'm out tomorrow so please feel free to merge this when you are satisfied.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-:-NV6tZsL1WtluAvHtUPQ:bciwn4g)* status: 1 unresolved discussion, missing label for release notes (waiting on @marcoag)

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @marcoag)

___
*[`multibody/parsing/test/process_model_directives_test.cc` line 382 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-NV6mdjHB0p7OLL2QvTh:-NVEPbyy1yyXECc4K1rQ:b-k97m89) ([raw file](https://github.com/RobotLocomotion/drake/blob/13a6073513576a2d35c3e6eec6ce354cde819ba9/multibody/parsing/test/process_model_directives_test.cc#L382)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

We should not be failing via `SIGABRT` here.

Can you change error condition to throw an exception?
(I assume it would involve replacing `DRAKE_DEMAND` with `DRAKE_THROW_UNLESS`)
</blockquote></details>

Changed the weld found condition check to `DRAKE_THROW_UNLESS` in https://github.com/RobotLocomotion/drake/pull/19090/commits/0a4f30a01e1417c21d3d669e6379ed58242af243.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19090)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @marcoag)

___
*[`multibody/parsing/test/process_model_directives_test.cc` line 382 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19090#-NV6mdjHB0p7OLL2QvTh:-NVFxU-q-sWgGv7bSUIU:b556ppi) ([raw file](https://github.com/RobotLocomotion/drake/blob/13a6073513576a2d35c3e6eec6ce354cde819ba9/multibody/parsing/test/process_model_directives_test.cc#L382)):*
<details><summary><i>Previously, marcoag (Marco A. Gutierrez) wrote…</i></summary><blockquote>

Changed the weld found condition check to `DRAKE_THROW_UNLESS` in https://github.com/RobotLocomotion/drake/pull/19090/commits/0a4f30a01e1417c21d3d669e6379ed58242af243.
</blockquote></details>

Awesome, thanks!

**Pull request merged**
