### PR TITLE
Added instructions on how to identify the build system and switch build systems.

### PR DESCRIPTION
**Pull request by liangfok**
I added this because I frequently find my self wondering which build system I used for a particular `drake-distro`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2833)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-:-KN2RRvqAX5Gu6HHuMOx:327914258)*

**Comment by amcastro-tri** [comment]
Thanks for documenting this. Besides a small comment :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 226 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-KN2nYhr6Xdx1vZuWEWl:-KN2nYhr6Xdx1vZuWEWm:222710212) ([raw file](https://github.com/robotlocomotion/drake/blob/4021dbb3099d34bc167648a0df1588cd8d2ddb0b/drake/doc/from_source.rst#L226)):*
> ```reStructuredText
> .. _identifying_build_system_used:
> 
> Identifying Which Build System Is Being Used and Switching Build Systems
> ```

I would remove "Being". IMO it makes the sentence structure more complex than what it should. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-:-KN2r6oKXjsYouJoSO9s:9436866)*

**Comment by liangfok** [comment]
+@david-german-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 226 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-KN2nYhr6Xdx1vZuWEWl:-KN2v81aP2pbDTnwefc5:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4021dbb3099d34bc167648a0df1588cd8d2ddb0b/drake/doc/from_source.rst#L226)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would remove "Being". IMO it makes the sentence structure more complex than what it should. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-:-KN2vA_D9Pf9xP9b4b77:-716099543)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 101 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-KN2yQG25NM4WaZCGpTb:-KN2yQG3lTvIkkYifNh_:1352636636) ([raw file](https://github.com/robotlocomotion/drake/blob/c454d96eb2f405c672c8a8da01e492967c193689/drake/doc/from_source.rst#L101)):*
> ```reStructuredText
> Because the Drake build is not entirely out-of-source, you must pick one build
> system and stick to it. Switching build systems within the same working tree
> will produce CMake errors. For instructions on how to switch build systems, see
> ```

I think you can now delete the previous two sentences.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-:-KN2yX6P3RY5ni3eSfhu:1417088721)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 101 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-KN2yQG25NM4WaZCGpTb:-KN30cZG2fpOlsGHJmtq:-1620626842) ([raw file](https://github.com/robotlocomotion/drake/blob/c454d96eb2f405c672c8a8da01e492967c193689/drake/doc/from_source.rst#L101)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I think you can now delete the previous two sentences.
</details>
Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 226 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-KN2nYhr6Xdx1vZuWEWl:-KN30kuniOunLaevrx2W:51923509) ([raw file](https://github.com/robotlocomotion/drake/blob/4021dbb3099d34bc167648a0df1588cd8d2ddb0b/drake/doc/from_source.rst#L226)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
Waiting on @amcastro-tri to ack this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833)*

**Comment by amcastro-tri** [comment]
Discussion resolved.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2833#-:-KN35mj-UtdpQ2AbcS2x:1318887907)*

**Pull request merged**
