### PR TITLE
Multibody ik

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in #9341. This PR implemtns some constraints for MultibodyTree kinematic constraints, together with a class `InverseKinematics` for `MultibodyTree`.

I will add the python API in a separate PR.

cc @RussTedrake @pangtao22

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9372)

### CODE REVIEW

**Comment by avalenzu** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9372#-LL_-AjjBBfaTDoURvZ5:-LL_-AjjBBfaTDoURvZ6:b-jp3x9m) (no related file):*
High-level concern: Do we really want the interface for the `InverseKinematics` and `*Constraint` classes to be so closely wedded to `MultibodyTree<AutodiffXd>`? Using `MultibodyTree<AutodiffXd>` certainly seems like the easiest way to _implement_  this, but I think it locks us out of potentially much more efficient implementations using `MutltibodyTree<double>` and dedicated Jacobian methods. cc @amcastro-tri, @russtedrake 

---

**Comment by jwnimmer-tri** [comment]
The complaint isn't that we must implement analytical Jacobians by next week, but rather that the new APIs proposed here should take `MultibodyTree<double>`  (or plant) and then internally call `treeToAutodiffXd()`, so that _when_ we add the analytical mechanisms, the user will have have change their calling code.

**Comment by jwnimmer-tri** [comment]
Understood.  Maybe leaving that one alone is fine (I'll leave it to the experts / other reviews).

**Comment by jwnimmer-tri** [comment]
@amcastro-tri You can transmogrify a System, but you can't transmogrify a Context (doing so doesn't make any sense).  Instead, you can do `Context<AutoDiffXd>::SetTimeStateAndParametersFrom(const Context<double&)`.  However, on a very quick glance, it seemed to me like that would not be good enough for this case.

**Comment by avalenzu** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9372#-LL_-AjjBBfaTDoURvZ5:-LL_ZYOQ3_pfihBLAaFB:b-32fwjl) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We currently do NOT have a method to compute the analytical Jacobian in MultibodyTree<double>. As far as I see, the analytical Jacobian is computed by AutoDiffXd. We do have dedicated methods to compute geometric Jacobian. @amcastro-tri could you confirm this?
</blockquote></details>

I think the r2 addresses my concern w.r.t `InverseKinematics`. Can you move the constraint classes into an `internal` namespace to make it clear that they're not part of the public API?

---

**Comment by ggould-tri** [comment]
There is no way that I am going to get a 1600 line PR reviewed with the time I have available this week.  I can grind through this over the next few days if you like, but this PR is large enough that I suggest finding a platform reviewer who is on the project team assigned to working this feature.

**Pull request merged**
