### PR TITLE
[geometry] Add Rgba::update to selectively change values

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Modernize several Rgba-related call sites to avoid syntax vomit.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19237)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review, please.

\CC @trowell-tri FYI

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19237#-:-NTUPjd5BRWZAfdYX0XQ:b-dnsw7x)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat_visualizer.cc` line 264 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19237#-NTUP0MVEflfdJLl7XLk:-NTUP0MW203VRqtFIDN8:b7i2hob) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f9707a408cdaa308fddc73198dde6bbc7ffdc1/geometry/meshcat_visualizer.cc#L264)):*
> ```cpp
>     color.set(color.r(), color.g(), color.b(), alpha_value_ * color.a());
>     meshcat_->SetProperty(path, "color",
>       {color.r(), color.g(), color.b(), alpha_value_ * color.a()});
> ```

@rpoyner-tri please check me here.

I'm pretty sure that were applying alpha² here by mistake.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19237)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@EricCousineau-TRI for platform, please.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19237#-:-NTURrDZ5AHiEpzoqDOJ:b-tq1ggv)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`geometry/meshcat_visualizer.cc` line 264 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19237#-NTUP0MVEflfdJLl7XLk:-NTURZ5lEXXkYu4aga52:bichi4u) ([raw file](https://github.com/RobotLocomotion/drake/blob/84f9707a408cdaa308fddc73198dde6bbc7ffdc1/geometry/meshcat_visualizer.cc#L264)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

That's what I thought when I saw that, too. (I fixed it in my still-in-flight PR.)
</blockquote></details>

Looks that way to me as well.
___
*[`geometry/test/rgba_test.cc` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19237#-NTUQpNz9vpErp5iuPOt:-NTUQpNz9vpErp5iuPOu:b95hz2w) ([raw file](https://github.com/RobotLocomotion/drake/blob/95e1eb2a67fe70c8ed4d40dc38e4c41454410682/geometry/test/rgba_test.cc#L56)):*
> ```cpp
>   color.update();
>   EXPECT_EQ(color.rgba(), Vector4d(0.1, 0.2, 0.3, 0.4));
>   color.update({0.6}, {}, {}, {});
> ```

BTW What's the motivation behind the unnecessary `{}` around the actual values? It doesn't strike me as an example we'd particularly want to give.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19237)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @SeanCurtis-TRI, and @trowell-tri)

___
*[`geometry/test/rgba_test.cc` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19237#-NTUQpNz9vpErp5iuPOt:-NTUSZv3-gZHcAsqyZwp:bmh7g88) ([raw file](https://github.com/RobotLocomotion/drake/blob/95e1eb2a67fe70c8ed4d40dc38e4c41454410682/geometry/test/rgba_test.cc#L56)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW What's the motivation behind the unnecessary `{}` around the actual values? It doesn't strike me as an example we'd particularly want to give.
</blockquote></details>

Updated to be more representative.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19237)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
