### PR TITLE
Add doxygen group for our suite of integrators

### PR DESCRIPTION
**Pull request by RussTedrake**
It's an impressive list!

image

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12900)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
... with the caveat that `simulator_gflags.h` is only usable within Drake, downstream cannot use it.

**Comment by jwnimmer-tri** [comment]
> However, is there any substantive reason they couldn't be used downstream?

Yes, from an installation and distribution perspective, linking gflags into downstreams is kind of a nightmare.  We had an eensy bit of it a few months ago and purged even that much because it was troublesome.

> They seem very useful ...

The best we can probably do is to factor out the non-gflags functions into helpers that we can ship.  So instead of an internal-only function that we have now ...

```c++
IntegratorBase<double>& ResetIntegratorFromGflags(Simulator<double>* simulator);
```

... we _also_ would offer a new function like this ...

```c++
IntegratorBase<double>& ResetIntegratorByName(const std::string& integrator_name, Simulator<double>* simulator);
```

The new reset-by-string function would also play much nicer with pydrake (argparse) that the gflags stuff.

Basically, just tease apart how the flags are scraped from argv (gflags) from the actions to take based upon the provided strings (these new functions).  Then the `simulator_gflags.h` becomes just a tiny bit of sugar that wires the two concepts together.

This is what we've already done with `set_log_level()` from `common/text_logging.h` (public) vs `common/add_text_logging_gflags.cc` (internal).

**Comment by sherm1** [comment]
That sounds good. 
@RussTedrake: in that case for _this_ PR I would suggest un-marking those two methods so as to avoid making them more prominent. I will capture @jwnimmer-tri's comments in a separate issue.

**Comment by sherm1** [comment]
Issue #12903.

**Comment by RussTedrake** [comment]
fwiw -- the new look:
image

**Comment by amcastro-tri** [comment]
@RussTedrake, is [this change](https://github.com/RussTedrake/drake/blob/cf1bc2786a654a5f2c812fbec2a3512b1ef98f03/systems/analysis/integrator_base.h#L905) you pushed in the last revision intentional?

**Comment by jwnimmer-tri** [comment]
That change was not part of this PR: https://github.com/RobotLocomotion/drake/blame/master/systems/analysis/integrator_base.h#L905

**Comment by amcastro-tri** [comment]
interesting, Reviewable showed it to me as part of the latest revision.

**Comment by amcastro-tri** [comment]
FTR, this is what I see in Reviewable right now:

image

**Comment by jwnimmer-tri** [comment]
Reviewable is not 100% precise in folding away all base commit changes.

**Pull request merged**
