### PR TITLE
[geometry/optimization] Support generic constraints in IrisInConfigurationSpace

### PR DESCRIPTION
**Pull request by RussTedrake**
Many users want to have additional constraints, like position and/or
orientation constraints on the end effector, as constraints on the
IRIS regions.  This PR makes that possible, and gives tests
demonstrating InverseKinematics constraints being certified via IRIS.

+@mpetersen94 for feature review, please.
fyi @sadraddini, @hongkai-dai , @AlexandreAmice

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703)

### CODE REVIEW

**Comment by RussTedrake** [comment]
I've been unable to reproduce the CI failures locally.  Apparently my ability to read those command line flags is insufficient.  Might anybody know how I can repro?  @jwnimmer-tri ?

**Comment by jwnimmer-tri** [comment]
These all show the failure for me locally:

```
bazel test --config=gcc --compilation_mode=dbg //geometry/optimization:iris_in_configuration_space_test
bazel test --config=clang --compilation_mode=opt //geometry/optimization:iris_in_configuration_space_test
bazel test --config=clang --compilation_mode=dbg --config=lsan //geometry/optimization:iris_in_configuration_space_test
```

**Comment by RussTedrake** [comment]
I was able to reproduce it with those.  Thanks @jwnimmer-tri .  (I also had to disable SNOPT, but I knew about that).
I had tried `bazel test -c dbg //geometry/optimization:iris_in_configuration_space_test` on ubuntu, because I thought gcc was the default.  So I'm not sure why the `--config=gcc` does any work?  (but it definitely causes bazel to rebuild everything).

**Comment by jwnimmer-tri** [comment]
I also think that GCC would have been the default _shrug_.  But in any case, when trying to repro a CI failure just scroll to the bottom of the CI output and copy-paste the command it prints.  That's all I did here.

**Review by mpetersen94 — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703#-:-N93kPiyCWhtErnJFRX9:bg7igkv)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`bindings/pydrake/geometry_py_optimization.cc` line 292 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93kGE7AamNUCJBBhCa:-N93kGE7AamNUCJBBhCb:b-32m4x9) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/bindings/pydrake/geometry_py_optimization.cc#L292)):*
> ```cpp
>       .def_readwrite("num_additional_constraint_infeasible_samples",
>           &IrisOptions::num_additional_constraint_infeasible_samples,
>           doc.IrisOptions.num_additional_constraint_infeasible_samples.doc)
> ```

nit: Consider binding the random seed as well
___
*[`geometry/optimization/iris.h` line 123 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93VDOqC6JB2qMgNwnh:-N93VDOqC6JB2qMgNwni:b-oj7jbo) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.h#L123)):*
> ```objc
>                    const IrisOptions& options = IrisOptions());
> 
>   /** Constructs ConvexSet representations of obstacles for IRIS in 3D using the
> ```

nit: Not sure the reason for the white-space changes here and below.
___
*[`geometry/optimization/iris.cc` line 527 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93gGADB8vzWTbryJS3:-N93gGAE1KUOiUJKXh-g:b-4mlef8) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.cc#L527)):*
> ```cpp
>   (*b)[*num_constraints] =
>       A->row(*num_constraints) * point - configuration_space_margin;
>   if (A->row(*num_constraints)*E.center() > (*b)[*num_constraints]) {
> ```

I'm assuming you added this because you were seeing `IrisInConfigurationSpace` kick back when the seed fell outside the region on the first iteration.  If so, I was seeing similar behavior when using seeds that had one direction that was very close to contact and other directions where there was plenty of room to move. I like the warning for now, but finding a way to handle this better would be nice.
___
*[`geometry/optimization/iris.cc` line 722 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93iqM_6WoEI0XjOC8N:-N93iqM_6WoEI0XjOC8O:blxh7xh) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.cc#L722)):*
> ```cpp
>     if (options.prog_with_additional_constraints) {
>       VectorXd guess = P.UniformSample(&generator);
>       for (const auto& binding : additional_constraint_bindings) {
> ```

Will this also search for counter examples to the bounding box/linear constraints that have already been handled above?  If so, that seems like an easy thing to skip.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 471 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93joDp6OuC2f5FidBB:-N93joDp6OuC2f5FidBC:byo2f4h) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/test/iris_in_configuration_space_test.cc#L471)):*
> ```cpp
> // This double pendulum doesn't have any collision geometry, but we'll add
> // this end-effector position constraint via an InverseKinematics problem:
> //    [-inf, 0, -inf] <= p_WE <= [inf, 0, -1]
> ```

nit: This comment does not match what is actually implemented.

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703#-:-N96tqAT17ueEJUQH3Dt:b223nro)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[`bindings/pydrake/geometry_py_optimization.cc` line 292 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93kGE7AamNUCJBBhCa:-N96_9z8D8oF8ziziRt1:bc4sjck) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/bindings/pydrake/geometry_py_optimization.cc#L292)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

nit: Consider binding the random seed as well
</blockquote></details>

Done.  Good call.
___
*[`geometry/optimization/iris.h` line 123 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93VDOqC6JB2qMgNwnh:-N96_YKd3qQ0iIBNGf_M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.h#L123)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

nit: Not sure the reason for the white-space changes here and below.
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 527 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93gGADB8vzWTbryJS3:-N96_kLV0bSWt4wMEW3h:b3tamr0) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.cc#L527)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I'm assuming you added this because you were seeing `IrisInConfigurationSpace` kick back when the seed fell outside the region on the first iteration.  If so, I was seeing similar behavior when using seeds that had one direction that was very close to contact and other directions where there was plenty of room to move. I like the warning for now, but finding a way to handle this better would be nice.
</blockquote></details>

I actually saw this when the constraint sets had no interior, in the case of equality constraints.  I think throwing here is a strict improvement (the results are incorrect if we don't).  You might have a case, which I haven't quite seen, that we can handle better?
___
*[`geometry/optimization/iris.cc` line 722 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93iqM_6WoEI0XjOC8N:-N96aLLVAhJtSs5Ddx9a:b-1zn2cb) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.cc#L722)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Will this also search for counter examples to the bounding box/linear constraints that have already been handled above?  If so, that seems like an easy thing to skip.
</blockquote></details>

No.  In the handle of bbox/linear constraints above, I call 
`additional_constraint_bindings.erase(...);` The additional_constraints list only has the constraints I need here.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 471 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93joDp6OuC2f5FidBB:-N96aWZF84JN9qBAFV-g:b-7xqdv3) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/test/iris_in_configuration_space_test.cc#L471)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

nit: This comment does not match what is actually implemented.
</blockquote></details>

Done.  (It's what I wanted!  as you saw in my comment below)

**Review by mpetersen94 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/iris.cc` line 527 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93gGADB8vzWTbryJS3:-N97ZOoN6vyiiYyXdVGH:bm30wjv) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.cc#L527)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I actually saw this when the constraint sets had no interior, in the case of equality constraints.  I think throwing here is a strict improvement (the results are incorrect if we don't).  You might have a case, which I haven't quite seen, that we can handle better?
</blockquote></details>

Got it! I think my use case might trigger this error as well (I'd have to try it) but I agree this error is better than not having anything for the issue of equality constraints. Fixing my issue should be a separate PR.
___
*[`geometry/optimization/iris.cc` line 722 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N93iqM_6WoEI0XjOC8N:-N97ZoHZBCDRzaeZd6lW:b-j6g5x) ([raw file](https://github.com/robotlocomotion/drake/blob/47819779be4bd77adad9a7ffdb6f7697222f92d6/geometry/optimization/iris.cc#L722)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

No.  In the handle of bbox/linear constraints above, I call 
`additional_constraint_bindings.erase(...);` The additional_constraints list only has the constraints I need here.
</blockquote></details>

Somehow I missed that. Looks good then!

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with a few nits and random questions.

> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703#-:-N97ozNWCTcZmZt2riS5:b-3i7zz0)* status: 10 unresolved discussions (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.cc` line 403 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97B56i0tGgNrpgOij0:-N97B56j4h9NfULrJR0z:b5vq4he) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L403)):*
> ```cpp
>   // TODO(russt): We need a more robust way to get this from the solver. This
>   // value works for SNOPT and is reasonable for most solvers.
>   static constexpr double kSolverConstraintTolerance{1e-6};
> ```

nit, this public static variable deserves some documentation. It's unclear to me why this is static and why an additional 1e-14 tolerance is needed a few lines below.
___
*[`geometry/optimization/iris.cc` line 416 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97Bbo9BYGiNmwTSAUU:-N97Bbo9BYGiNmwTSAUV:bihibzj) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L416)):*
> ```cpp
> 
>   // The Constraint Binding must remain valid for the lifetime of this object
>   // (or until a new Constraint Binding is set).
> ```

nit this doc should mention something about the semantic of the function. IIUC, on repeated call to this function, the previous constraint binding will be ignored?
___
*[`geometry/optimization/iris.cc` line 423 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97C5A-9AtxkksbhmT9:-N97C5A-9AtxkksbhmTA:b-sc0guz) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L423)):*
> ```cpp
>     const int N =
>         binding_with_constraint_to_be_falsified->evaluator()->num_constraints();
>     DRAKE_DEMAND(index_ >= 0 && index_ < N);
> ```

nit, I'm confused by this line. Do you by any chance mean



_Suggestion:_
```cpp
 DRAKE_DEMAND(index >= 0 && index < N);
```
___
*[`geometry/optimization/iris.cc` line 565 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97F_NmBOy4ygoHr0qW:-N97F_NmBOy4ygoHr0qX:b2v9na3) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L565)):*
> ```cpp
>   DRAKE_DEMAND(plant.GetPositionUpperLimits().array().isFinite().all());
> 
>   // We don't yet support Ibex when the user has defined additional constraints.
> ```

nit should this comment be moved to the IrisOptions struct or is this specific to this function?
___
*[`geometry/optimization/iris.cc` line 644 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ZFAu6WfhpoKZpXN8:-N97ZFAu6WfhpoKZpXN9:b9g88b5) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L644)):*
> ```cpp
>       while (num_initial_constraints + new_A.rows() >= A.rows()) {
>         // Increase pre-allocated polytope size.
>         A.conservativeResize(A.rows() * 2, A.cols());
> ```

nit, could you comment on why this pattern of resizing (instead of directly resizing A once)? My best guess is that we are running this over multiple constraint bindings and it may be beneficial to be generous each time we allocate. But do we worry about uninitialized values here?
___
*[`geometry/optimization/iris.cc` line 655 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97Zi4F-w3gF2FPXe9G:-N97Zi4F-w3gF2FPXe9H:b-kqms1y) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L655)):*
> ```cpp
>             A(num_initial_constraints, index) = new_A(i, j);
>           }
>           b[num_initial_constraints++] = new_b[i];
> ```

nit, reusing `num_intial_constraints` for current row index confused me for a second. Consider using a separate variable for more clarity.
___
*[`geometry/optimization/iris.cc` line 729 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97apCI12RFeIuCpR0W:-N97apCI12RFeIuCpR0X:b-afq27m) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L729)):*
> ```cpp
>             if (falsify_lower_bound &&
>                 std::isinf(binding.evaluator()->lower_bound()[index]))
>               continue;
> ```

Per GSG, we need curly braces around `continue;`.

https://drake.mit.edu/styleguide/cppguide.html#Conditionals



_Code snippet:_
```cpp
// Bad - IF statement is too long to omit braces
if (condition1 &&
      condition2)
    DoSomething();
```
___
*[`geometry/optimization/iris.cc` line 749 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ct268Wm6Io5urZ8i:-N97ct268Wm6Io5urZ8j:b-ahm159) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L749)):*
> ```cpp
>                       A.row(num_constraints - 1) * sample <=
>                       b(num_constraints - 1);
>                   if (!sample_point_requirement) break;
> ```

BTW, according to the documentation of "require_sample_point_is_contained", it seems to me that the outer for loop should terminate instead of just this inner while loop.

It could be my misunderstanding, but just want to bring it to your attention for double checking.
___
*[`geometry/optimization/iris.cc` line 753 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97bspW1TeQLPNQ3iLg:-N97bspW1TeQLPNQ3iLh:b-4qh3ob) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L753)):*
> ```cpp
>                 consecutive_failures = 0;
>               } else {
>                 consecutive_failures++;
> ```

nit use preincrement per gsg.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 440 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97jkROCWbp1jMzLBHu:-N97jkROCWbp1jMzLBHv:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/test/iris_in_configuration_space_test.cc#L440)):*
> ```cpp
> 
> // Three boxes.  Two on the outside are fixed.  One in the middle on a prismatic
> // joint.  Additional constraints are added via options.prog:
> ```

nit



_Suggestion:_
```cpp
Additional constraints are added via options.prog_with_additional_constraints:
```
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 569 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97og979F4Ubu9E10xO:-N97og979F4Ubu9E10xP:b-7395d4) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/test/iris_in_configuration_space_test.cc#L569)):*
> ```cpp
>           -std::acos(1 - std::cos(theta1s[i])) - theta1s[i];
>     }
>     meshcat->SetLine("True CFree", points, 2.0, Rgba(0, 0, 1));
> ```

nit, not sure what this means. Is this short for "True Collision Free?"



_Code quote:_
```cpp
True CFree
```
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 577 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ooHp2XzHsTqbMdxx:-N97ooHp2XzHsTqbMdxy:b-sqnmaw) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/test/iris_in_configuration_space_test.cc#L577)):*
> ```cpp
>     meshcat->SetLine("IRIS Region", points, 2.0, Rgba(0, 1, 0));
> 
>     meshcat->SetObject("Test point (max)", Sphere(0.01), Rgba(1, 0, 0));
> ```

FYI, the visualization is cool, but the test point is way a bit too small to spot.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703)* status: 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/iris.cc` line 403 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97B56i0tGgNrpgOij0:-N9BDm_L4ByykWket72J:b-h9zrwx) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L403)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this public static variable deserves some documentation. It's unclear to me why this is static and why an additional 1e-14 tolerance is needed a few lines below.
</blockquote></details>

Done. 
- Added the comment explaining the value and the static.
- Changed it to private.
___
*[`geometry/optimization/iris.cc` line 416 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97Bbo9BYGiNmwTSAUU:-N9BEwun8PqFu4PE2Lfe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L416)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit this doc should mention something about the semantic of the function. IIUC, on repeated call to this function, the previous constraint binding will be ignored?
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 423 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97C5A-9AtxkksbhmT9:-N9BF1TGA5jUHibm1Wrc:b-ubccg3) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L423)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, I'm confused by this line. Do you by any chance mean
</blockquote></details>

Yes.  Thanks.  Good catch.
___
*[`geometry/optimization/iris.cc` line 565 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97F_NmBOy4ygoHr0qW:-N9BFwqL3DslDgXxfWOG:b9cu65p) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L565)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit should this comment be moved to the IrisOptions struct or is this specific to this function?
</blockquote></details>

done.  good call.  i mentioned it in the IrisOptions struct.
___
*[`geometry/optimization/iris.cc` line 644 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ZFAu6WfhpoKZpXN8:-N9BGNGX9eJTB9iMgnBx:b-frd21y) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L644)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, could you comment on why this pattern of resizing (instead of directly resizing A once)? My best guess is that we are running this over multiple constraint bindings and it may be beneficial to be generous each time we allocate. But do we worry about uninitialized values here?
</blockquote></details>

This pattern is already established below (where it is more readily justified), because we cannot know the size of A before each iteration of the algorithm; it depends on how many counter-examples are uncovered and can change on each major iteration.  I simple used the same pattern here.

We don't worry about uninitialized values, because I maintain a count of the number of initialized rows (here using `num_initial_constraints`).
___
*[`geometry/optimization/iris.cc` line 655 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97Zi4F-w3gF2FPXe9G:-N9BH2g_4jPxsswLj_jQ:b-tylkaz) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L655)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, reusing `num_intial_constraints` for current row index confused me for a second. Consider using a separate variable for more clarity.
</blockquote></details>

perhaps the comment above clarified this.  i think `num_initial_constriants` is the right variable here...?
___
*[`geometry/optimization/iris.cc` line 749 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ct268Wm6Io5urZ8i:-N9BHRdoDQaGLrnwNAe2:be49znn) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L749)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, according to the documentation of "require_sample_point_is_contained", it seems to me that the outer for loop should terminate instead of just this inner while loop.

It could be my misunderstanding, but just want to bring it to your attention for double checking.
</blockquote></details>

there is another     
```
if (!sample_point_requirement) {
      break;
}
```
in the outer-loop below.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 569 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97og979F4Ubu9E10xO:-N9BHtnP5BAceXu1VOVM:b-z6p8bs) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/test/iris_in_configuration_space_test.cc#L569)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, not sure what this means. Is this short for "True Collision Free?"
</blockquote></details>

C_space and C_free are very common notaiton (and this is just a label in the iris debugging visaulization).  It's the collision-free configuration space.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 577 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ooHp2XzHsTqbMdxx:-N9BIHkx8LZ1QRyQqz1l:bfmfdrd) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/test/iris_in_configuration_space_test.cc#L577)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, the visualization is cool, but the test point is way a bit too small to spot.
</blockquote></details>

Done.  Made it a bit bigger.

**Comment by RussTedrake** [comment]
I forgot to post the test visualization.  This is a double pendulum with an end-effector position constraint added via an inverse kinematics problem:
Screen Shot 2022-08-11 at 5 49 52 AM

The blue line is the boundardy of the true region, C_free, the green is the IRIS region -- ideally an inner approximation.  The red points are some test points that I certify to be just outside the verified region.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17703)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.cc` line 644 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ZFAu6WfhpoKZpXN8:-N9CgMEx0tlB3N86C_y2:b-a7jufr) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L644)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This pattern is already established below (where it is more readily justified), because we cannot know the size of A before each iteration of the algorithm; it depends on how many counter-examples are uncovered and can change on each major iteration.  I simple used the same pattern here.

We don't worry about uninitialized values, because I maintain a count of the number of initialized rows (here using `num_initial_constraints`).
</blockquote></details>

I see. Thanks for the explanation.
___
*[`geometry/optimization/iris.cc` line 749 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97ct268Wm6Io5urZ8i:-N9CgbOQ89O4PkwKYPCv:blvw3hf) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/iris.cc#L749)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

there is another     
```
if (!sample_point_requirement) {
      break;
}
```
in the outer-loop below.
</blockquote></details>

I missed that. Thanks.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 569 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17703#-N97og979F4Ubu9E10xO:-N9CghKI3kK50Gsei2ir:bgzdldr) ([raw file](https://github.com/robotlocomotion/drake/blob/8f708cc9f7c89cb182e3bac6221906b720b15116/geometry/optimization/test/iris_in_configuration_space_test.cc#L569)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

C_space and C_free are very common notaiton (and this is just a label in the iris debugging visaulization).  It's the collision-free configuration space.
</blockquote></details>

Good to know, thanks.

**Pull request merged**
