### PR TITLE
Make sure to use full-precision when printing symbolic expression

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue: #6727

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6735)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , feature-review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-:-KqTSH4HixLHZU23-Wnl:b8y8nlm)*

**Comment by jwnimmer-tri** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 508 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-KqTmWGC3iy2zIHBTBJg:-KqTmWGDAcCbAayCM-Ut:b-xdhr42) ([raw file](https://github.com/robotlocomotion/drake/blob/3ccb482798899ae20d10547d8bc1df57194abfe6/drake/common/symbolic_expression.cc#L508)):*
> ```cpp
> class PrecisionGuard {
>  public:
>   PrecisionGuard(ostream& os, const streamsize& new_precision)
> ```

GSG forbids non-const references.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-:-KqTn9RJboLdnrrHOGKE:b-uwkowd)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 508 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-KqTmWGC3iy2zIHBTBJg:-KqTobwQXJ8uXzIzQSq1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ccb482798899ae20d10547d8bc1df57194abfe6/drake/common/symbolic_expression.cc#L508)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

GSG forbids non-const references.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/common/symbolic_expression.cc, line 510 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-KqTocy3GeGXSaBv-b7P:-KqTocy4rrl7QpHLgxU7:b-74mho9) ([raw file](https://github.com/robotlocomotion/drake/blob/63a7d1b23a289e6de908147f9644879fabc6111d/drake/common/symbolic_expression.cc#L510)):*
> ```cpp
>   PrecisionGuard(ostream* const os, const streamsize& new_precision)
>       : os_{os}, original_precision_{os->precision()} {
>     DRAKE_DEMAND(os != nullptr);
> ```

FYI This is slightly silly, since we already dereferenced it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 510 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-KqTocy3GeGXSaBv-b7P:-KqTol5cSyWuvyWmRyUV:b-c1i9d5) ([raw file](https://github.com/robotlocomotion/drake/blob/63a7d1b23a289e6de908147f9644879fabc6111d/drake/common/symbolic_expression.cc#L510)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This is slightly silly, since we already dereferenced it.
</blockquote></details>

ah.. right. will be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/common/symbolic_expression.cc, line 510 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-KqTocy3GeGXSaBv-b7P:-KqTp4DcE2eKfEuVpktV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63a7d1b23a289e6de908147f9644879fabc6111d/drake/common/symbolic_expression.cc#L510)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

ah.. right. will be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735)*

**Comment by soonho-tri** [comment]
+@sammy-tri, platform-review please. Thank you!

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-:-KqTpEGNFWHYTc9ONClV:b-4sl6fv)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6735#-:-KqU6psWZWSlm5zT44UM:bnfp4nl)*

**Pull request merged**
