### PR TITLE
Add drake_optional

### LINKED ISSUE #5526: Introduce `optional<T>.` functionality
The C++17 specification includes the `std::optional<T>` class.  It allows functions return values that sometimes have values and sometimes don't.  This is of definite use.  We can't wait on having a compliant compiler so we need to introduce this ourselves.

The simplest way is to draw from this repo: https://github.com/akrzemi1/Optional

It should be added to `drake/thirdParty/boost` (as it uses a boost license).  The first person to hit the point where they need this should add it.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #5526.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5593)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri +@seancurtis-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-:-KfrkdwmV9KoKeXAxw4u:bqow2qv)*

**Comment by amcastro-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_optional.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-KfrnQlIc-JT51gGm3KT:-KfrnQlIc-JT51gGm3KU:bvenelx) ([raw file](https://github.com/robotlocomotion/drake/blob/2bba5705fb96d35d32851594fb956dc570072050/drake/common/drake_optional.h#L14)):*
> ```objc
> 
> template <typename T>
> using optional = std::experimental::optional<T>;
> ```

I thought this feature was not available in all compilers? (at least as stated in #5526) are there any specific requirements that should at least get documented in this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593)*

**Comment by SeanCurtis-TRI** [comment]
It hadn't even occurred to me to assume there was an `experimental` space in our current compilers.  And the wrapping in the `drake::optional` will make migrating to C++17 quite painless.  :LGTM:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_optional.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-KfrnQlIc-JT51gGm3KT:-Kfron0wKdD0I894odgd:b-c4y9mr) ([raw file](https://github.com/robotlocomotion/drake/blob/2bba5705fb96d35d32851594fb956dc570072050/drake/common/drake_optional.h#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I thought this feature was not available in all compilers? (at least as stated in #5526) are there any specific requirements that should at least get documented in this file?
</blockquote></details>

This likewise surprised me.  That said, if this works, it looks good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-:-Kfrp2TWrRJBhulqAbNW:b97tpcj)*

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-:-Kfrqshz-UJ2fzMVaJKr:b-v3eqt6)*

**Comment by soonho-tri** [comment]
Fantastic! :lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-:-KfrqvP_OjRVJCzK9gRJ:bkj6hvn)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593)*

**Comment by jwnimmer-tri** [comment]
CI has tested on our supported platforms, and I tested by hand with Trusty GCC 4.8.  The only caveat is that not _all_ of the C++17 sugar on `optional` is implemented everywhere (e.g., `has_value`) but that is easily enough worked around (and CI will check it for us anyway).

**Comment by SeanCurtis-TRI** [comment]
Looking at the unit test, it had all the functionality *I* hope to use. :)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-:-KfrrsDO7Akh3FhaPJWm:b-klv2tv)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/common/drake_optional.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-KfrnQlIc-JT51gGm3KT:-KfrwbvuaO9KoNos7Osj:bivs5ec) ([raw file](https://github.com/robotlocomotion/drake/blob/2bba5705fb96d35d32851594fb956dc570072050/drake/common/drake_optional.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@amcastro-tri the `std::optional` is not available in most of our platforms, but `std::experimental::optional` turns out to be.
</blockquote></details>

It looks good to me also, just wondering if @jwnimmer-tri had something he would've liked to document here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-:-KfrwmkA1C0l-QWGH0Nq:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/drake_optional.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5593#-KfrnQlIc-JT51gGm3KT:-KfrxPn0L90BNrYjDORs:b-hr3cb0) ([raw file](https://github.com/robotlocomotion/drake/blob/2bba5705fb96d35d32851594fb956dc570072050/drake/common/drake_optional.h#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It looks good to me also, just wondering if @jwnimmer-tri had something he would've liked to document here. 
</blockquote></details>

Good point.  In response, I thought about adding a comment "This file works for our currently supported platforms but may have to get smarter in the future." but that seemed like a bit of a tautology, so I thinl its okay for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5593)*

**Comment by amcastro-tri** [comment]
Yeah, I had the same thought also. Worst case scenario we can always roll our own version.

**Pull request merged**
