### PR TITLE
Adds bindings for Hyperrectangle.

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20690)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@sadraddini for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20690#-:-Nm26I8j5GIgEFztoc1i:b-kdutzu)* status: LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by sadraddini — COMMENTED** [review]
:lgtm: Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20690#-:-Nm2QoavAYVtxdbLQba0:b-pt8m11)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+@rpoyner-tri for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20690#-:-Nm2VRjOCoI4tUIUk1GU:b-4ggvzz)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20690#-:-Nm3EZ0K30edNsalQjf9:bnfp4nl)* status: missing label for release notes (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20690#-:-Nm3IiLq8eT3M7j1ybmV:b-l8xbmn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sadraddini

**Pull request merged**
