### PR TITLE
Removes value_or(999) hacks previously necessary for OS X builds to succeed.

### PR DESCRIPTION
**Pull request by edrumwri**
Addresses issue #6277.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7661)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature and platform review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7661#-:-L0zNh3chz1G_xlq7y63:b-r2roxd)*

**Comment by sherm1** [comment]
Yay! Feature and platform :lgtm: pending CI.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7661#-:-L0zOYOBA1l-z99cmffk:b-rfos92)*

**Comment by soonho-tri** [comment]
FYI, I'm running `bazel test //systems/analysis/... //systems/framework/... -c dbg` on my local macs (both `10.12` and `10.13`).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7661#-:-L0zPD2F5lJWt4rPHq6A:bsaf20g)*

**Comment by soonho-tri** [comment]
:lgtm: (:apple: tested)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7661#-:-L0zQCZS6n_tbfaenqWk:bbnp09l)*

**Comment by sherm1** [comment]
Thanks, @soonho-tri! 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7661#-:-L0zX6j6ZckIUQuDHeac:b-mjwqlf)*

**Pull request merged**
