### PR TITLE
Socp times socp relaxation

### PR DESCRIPTION
**Pull request by AlexandreAmice**
Begin the implementation of more complex product constraints in MakeSemidefiniteRelaxation

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
Towards #20777. The changes required are big enough that I thought breaking it up into pieces would help. This implements Theorem 3 of our shared overleaf doc. Please let me konw if there is a better way to document.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-NpwIN4zDmO9vUGlqOWm:b-masv51)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by ggould-tri — COMMENTED** [review]
@AlexandreAmice do you have a feature reviewer in mind?  I'd normally assign @hongkai-dai but he is on leave this week.
Alternatively, if this is not yet ready for review, you can apply the 'do not review' tag.
+(component: mathematical program) +(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-Npym1ZY7RMyYvuRyyM4:bg27mbs)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
I will assign +@bernhardpg for feature review temporarily and ask around the lab to see if anyone else wants to take a look. There is no rush on this one getting through.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-NpytxBb4Ckx6FYfq3Ta:b-3vfn2f)* status: LGTM missing from assignee bernhardpg, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

Jenkins restarted in the middle and your jobs were not reconnecting.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888)* status: LGTM missing from assignee bernhardpg, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/semidefinite_relaxation_internal.h` line 59 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6Ftn87NjTVyzxyI3H:-Nr6Ftn87NjTVyzxyI3I:b-p6qhp0) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L59)):*
> ```objc
> // TODO(Alexandre.Amice) Move this to mathematical_program.h
> void AddMatrixIsLorentzSeparableConstraint(
>     const Eigen::Ref<const Eigen::MatrixX<symbolic::Variable>>& X,
> ```

FYI, this is your build failure.  The `MatrixX<T>` helper template is a Drake affordance, not part of Eigen.



_Suggestion:_
```objc
const drake::MatrixX<symbolic::Variable>>
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888)* status: LGTM missing from assignee bernhardpg, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/semidefinite_relaxation_internal.h` line 59 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6Ftn87NjTVyzxyI3H:-Nr6YVis9tpwtrIb3pb8:b46bru4) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L59)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI, this is your build failure.  The `MatrixX<T>` helper template is a Drake affordance, not part of Eigen.
</blockquote></details>

FYI Once we finish ditching Focal in the next few days, Eigen _will_ have `MatrixX` defined.

ps. Don't say `drake::MatrixX` just say `MatrixX`.

**Review by bernhardpg — COMMENTED** [review]
@AlexandreAmice  I left some non-important comments. I will leave it up to you to decide to fix them or not. I will trust you on the math in the implementation. Otherwise :lgtm: !

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-Nr6xVYT87QtYHR49OAd:b-8nuzpc)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/semidefinite_relaxation_internal.h` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6RVx3BJAFiKQkvgVW:-Nr6RVx3BJAFiKQkvgVX:bflce88) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L12)):*
> ```objc
> // Take the sparse Kronecker product of A and B.
> Eigen::SparseMatrix<double> SparseKroneckerProduct(
>     const Eigen::SparseMatrix<double>& A, const Eigen::SparseMatrix<double>& B);
> ```

Why do we want this to be only available internally? Is the Kronecker product not something that would be useful to expose to all users? (I suppose that this could be a separate PR)
___
*[`solvers/semidefinite_relaxation_internal.h` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6SeqTAvggfo1NgLnQ:-Nr6SeqTAvggfo1NgLnR:b-z112hq) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L14)):*
> ```objc
>     const Eigen::SparseMatrix<double>& A, const Eigen::SparseMatrix<double>& B);
> 
> // Get the matrix for the map Y -> [tr(Y), y00 - ∑ᵢ₌₁ʳ⁻¹yᵢᵢ, 2y_{0i-1} when
> ```

I would suggest something like "Get the matrix representation for the map...". Also there is a missing square bracket.



_Suggestion:_
```objc
[tr(Y), y00 - ∑ᵢ₌₁ʳ⁻¹yᵢᵢ, 2y_{0i-1}]
```
___
*[`solvers/semidefinite_relaxation_internal.h` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6TCS6-UqNm4-uazJ_:-Nr6TCS6-UqNm4-uazJa:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L20)):*
> ```objc
> 
> // Given a vector expressing an element of Sⁿ ⊗ Sᵐ, return the symmetric matrix
> // of size Sⁿᵐ which it corresponds to.
> ```





_Suggestion:_
```objc
// Given a vector expressing an element of Sⁿ ⊗ Sᵐ, return the corresponding symmetric matrix
// of size Sⁿᵐ.
```
___
*[`solvers/semidefinite_relaxation_internal.h` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6TVM09k6EP_CFF8qM:-Nr6TVM09k6EP_CFF8qN:b4jazci) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L23)):*
> ```objc
> template <typename Derived>
> drake::MatrixX<typename Derived::Scalar> ToSymmetricMatrixFromTensorVector(
>     const Eigen::MatrixBase<Derived>& tensor_vector, int n, int m) {
> ```

Is there one standard way to represents an element of Sⁿ ⊗ Sᵐ with a vector? If not, I would specify how it is represented, or change the API to take in the two matrices and convert to the vector representation internally.

Edit: I assume it uses the same form as `ToLowerTriangularColumnsFromMatrix`. I don't know if this is assumed throughout Drake or if this should be specified. I'll leave it up to you!
___
*[`solvers/test/semidefinite_relaxation_internal_test.cc` line 41 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6V4orARAv4W3CBriN:-Nr6V4os8dqda-Gam54h:bqzslzf) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/test/semidefinite_relaxation_internal_test.cc#L41)):*
> ```cpp
>   auto TestKron = [](const Eigen::SparseMatrix<double>& A_test,
>                      const Eigen::SparseMatrix<double>& B_test) {
>     // AXB = (B.T ⊗ A)vec(X) so we compute this as a numerical sanity check.
> ```

Is it worth adding a reference to i.e. https://en.wikipedia.org/wiki/Kronecker_product#Matrix_equations here?

In general I don't know Drake's policy on putting URLs to external references in comments.
___
*[`solvers/test/semidefinite_relaxation_internal_test.cc` line 180 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6v18l1Eqsxp42bIYZ:-Nr6v18l1Eqsxp42bIY_:bath9ph) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/test/semidefinite_relaxation_internal_test.cc#L180)):*
> ```cpp
>   EXPECT_EQ(psd_constraint.evaluator()->matrix_rows(), (m - 1) * (n - 1));
> 
>   Eigen::VectorXd xm_lorentz(m);
> ```

Suggestion: Add the comment `// xm_lorentz and xn_lorentz are in the Lorentz cones of size m and n, respectively.`
___
*[`solvers/test/semidefinite_relaxation_internal_test.cc` line 197 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6vUkMEJp0_yIHeTG_:-Nr6vUkMEJp0_yIHeTGa:b6gn8lz) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/test/semidefinite_relaxation_internal_test.cc#L197)):*
> ```cpp
>   Eigen::VectorXd yn_lorentz(n);
>   yn_lorentz << 2, -0.1, 0.5, -0.3;
>   Eigen::MatrixXd Y_tensor_lorentz = 2 * xm_lorentz * xn_lorentz.transpose() +
> ```

I would add a comment explaining this. Suggestion:
`\\ The tensor product of cones is another cone. Hence, a conic combination of two elements in the cone of Lorentz separable matrices must also be Lorentz separable.`

**Review by AlexandreAmice — COMMENTED** [review]
+@sammy-tri for platform review per schedule. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-Nrmp59q9LePkDr4tJbS:bmxjkdl)* status: 8 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/semidefinite_relaxation_internal.h` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6RVx3BJAFiKQkvgVW:-Nr7b2NC-7f0u-m-Qzoa:bj58386) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L12)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

Why do we want this to be only available internally? Is the Kronecker product not something that would be useful to expose to all users? (I suppose that this could be a separate PR)
</blockquote></details>

Moving it to public would require additional testing. This is fine here for now.
___
*[`solvers/semidefinite_relaxation_internal.h` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-NqnTW9VAGQqjmynMMuX:-NqnTW9VAGQqjmynMMuY:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L14)):*
> ```objc
>     const Eigen::SparseMatrix<double>& A, const Eigen::SparseMatrix<double>& B);
> 
> // Get the matrix for the map Y -> [tr(Y), y00 - ∑ᵢ₌₁ʳ⁻¹yᵢᵢ, 2y_{0i-1} when
> ```

nit: typo



_Suggestion:_
```objc
Y -> [tr(Y), y00 - ∑ᵢ₌₁ʳ⁻¹yᵢᵢ, 2y_{0i-1}]
```
___
*[`solvers/semidefinite_relaxation_internal.h` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6SeqTAvggfo1NgLnQ:-NrmnXQ_3Bi8lZ_Ub92S:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L14)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

I would suggest something like "Get the matrix representation for the map...". Also there is a missing square bracket.
</blockquote></details>

Done.
___
*[`solvers/semidefinite_relaxation_internal.h` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6TCS6-UqNm4-uazJ_:-NrmoKn3CbyZ2OgUrQEF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L20)):*
> ```objc
> 
> // Given a vector expressing an element of Sⁿ ⊗ Sᵐ, return the symmetric matrix
> // of size Sⁿᵐ which it corresponds to.
> ```

Done.
___
*[`solvers/semidefinite_relaxation_internal.h` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6TVM09k6EP_CFF8qM:-NrmoRKc2oyU_c0_zrpa:b-t32a6x) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/semidefinite_relaxation_internal.h#L23)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

Is there one standard way to represents an element of Sⁿ ⊗ Sᵐ with a vector? If not, I would specify how it is represented, or change the API to take in the two matrices and convert to the vector representation internally.

Edit: I assume it uses the same form as `ToLowerTriangularColumnsFromMatrix`. I don't know if this is assumed throughout Drake or if this should be specified. I'll leave it up to you!
</blockquote></details>

Technically, I assume that the vector is expressed in the standard basis. Not sure what extra documentation would be helpful.
___
*[`solvers/test/semidefinite_relaxation_internal_test.cc` line 41 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6V4orARAv4W3CBriN:-Nrmohr9Dc42QXZClW_R:b-wrdkvl) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/test/semidefinite_relaxation_internal_test.cc#L41)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

Is it worth adding a reference to i.e. https://en.wikipedia.org/wiki/Kronecker_product#Matrix_equations here?

In general I don't know Drake's policy on putting URLs to external references in comments.
</blockquote></details>

I think this is a well known identity?
___
*[`solvers/test/semidefinite_relaxation_internal_test.cc` line 180 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6v18l1Eqsxp42bIYZ:-NrmoySV3rk5KrXmRAVh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/test/semidefinite_relaxation_internal_test.cc#L180)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

Suggestion: Add the comment `// xm_lorentz and xn_lorentz are in the Lorentz cones of size m and n, respectively.`
</blockquote></details>

Done.
___
*[`solvers/test/semidefinite_relaxation_internal_test.cc` line 197 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-Nr6vUkMEJp0_yIHeTG_:-Nrmp4DuBK2-kbK3j0H3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49e0b274e3f6eccb61ce3b156020cc29b012aaad/solvers/test/semidefinite_relaxation_internal_test.cc#L197)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

I would add a comment explaining this. Suggestion:
`\\ The tensor product of cones is another cone. Hence, a conic combination of two elements in the cone of Lorentz separable matrices must also be Lorentz separable.`
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
Just some small nits from me.  Waiting on feature review comment resolution.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-NrqWOAh-RkFgCLqNFgX:bqx06ld)* status: 9 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/BUILD.bazel` line 1038 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-NrqNb6H90cp9LmlNSUY:-NrqNb6H90cp9LmlNSUZ:by0l8u3) ([raw file](https://github.com/RobotLocomotion/drake/blob/740a1997ace939e7ff0174b58386f5bb8dbcb618/solvers/BUILD.bazel#L1038)):*
> ```Starlark
>         "//math:matrix_util",
>     ],
>     deps = [":semidefinite_relaxation_internal"],
> ```

Should we wait to add this dependency until it actually exists?
___
*[`solvers/semidefinite_relaxation_internal.cc` line 85 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-NrqUiOj9iWz7qrS_kcd:-NrqUiOj9iWz7qrS_kce:baxk4a9) ([raw file](https://github.com/RobotLocomotion/drake/blob/740a1997ace939e7ff0174b58386f5bb8dbcb618/solvers/semidefinite_relaxation_internal.cc#L85)):*
> ```cpp
>     AddMatrixIsLorentzSeparableConstraintSimplicialCase(X, prog);
>     return;
>   } else {
> ```

BTW this doesn't really need to be indented into an `else` block since we have a `return` in the previous case, but I'm not sure that strictly qualifies as a defect in our style guide.

**Review by bernhardpg — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/semidefinite_relaxation_internal.h` line 20 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-NrvhHY63CcJ7615r0EM:-NrvhHY63CcJ7615r0EN:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/740a1997ace939e7ff0174b58386f5bb8dbcb618/solvers/semidefinite_relaxation_internal.h#L20)):*
> ```objc
> 
> // Given a vector expressing an element of Sⁿ ⊗ Sᵐ, return the corresponding
> // symmetric matrix of size Sⁿᵐ which it corresponds to. Note that Sⁿ ⊗ Sᵐ is a
> ```





_Suggestion:_
```objc
// Given a vector expressing an element of Sⁿ ⊗ Sᵐ, return the corresponding
// symmetric matrix of size Sⁿᵐ. Note that Sⁿ ⊗ Sᵐ is a
```

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`solvers/BUILD.bazel` line 1038 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-NrqNb6H90cp9LmlNSUY:-NsBoJAK8B4w-pWfyGQJ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/740a1997ace939e7ff0174b58386f5bb8dbcb618/solvers/BUILD.bazel#L1038)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should we wait to add this dependency until it actually exists?
</blockquote></details>

Done.
___
*[`solvers/semidefinite_relaxation_internal.h` line 20 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-NrvhHY63CcJ7615r0EM:-NsBoQjHDokd4uBTI7Jl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/740a1997ace939e7ff0174b58386f5bb8dbcb618/solvers/semidefinite_relaxation_internal.h#L20)):*
> ```objc
> 
> // Given a vector expressing an element of Sⁿ ⊗ Sᵐ, return the corresponding
> // symmetric matrix of size Sⁿᵐ which it corresponds to. Note that Sⁿ ⊗ Sᵐ is a
> ```

Done.

**Review by bernhardpg — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20888#-:-NsFphB87QanhUlJoWsD:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Pull request merged**
