### PR TITLE
Resolves issue #17246 by fixing order of state in quadrotor_dynamics_test.cc

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17254)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature reivew +@russtedrake 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17254#-:-N2nOC3MCtV9NsXfgDuX:b-p24bnp)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
Thanks Paul.  I had another test (where I compared with MBP, but using a manually constructed floating base with three prismatic and three revolute joints) that was failing more dramatically than 1e-5.  Let me check that test tonight to make sure things work out here.

**Review by RussTedrake — COMMENTED** [review]
I've resolved my other issue, and these changes :LGTM:.   Thanks!
+@jwnimmer-tri for platform review, please.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17254#-:-N2s25u08wQEY61OsmbC:b3ku8v8)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule; timed out for today.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm_strong: with a couple of nits -- thanks, Paul!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17254#-:-N2w5nlOCwHm-rPMZD1w:b15crhy)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`examples/quadrotor/test/quadrotor_dynamics_test.cc` line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17254#-N2w3IU-2YmuN337hEtt:-N2w3IU-2YmuN337hEtu:b-xwogoj) ([raw file](https://github.com/robotlocomotion/drake/blob/f73bcbb1d2722b6ccacfb84a1febf395fdc7ce39/examples/quadrotor/test/quadrotor_dynamics_test.cc#L69)):*
> ```cpp
>   }
> 
>   // @param[in] context a mutable Context to be set from the state vector x.
> ```

nit: this should be `@param[in,out]` since it gets modified
___
*[`examples/quadrotor/test/quadrotor_dynamics_test.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17254#-N2w4AbmATg2cQxq0kkD:-N2w4AbmATg2cQxq0kkE:bk75d3m) ([raw file](https://github.com/robotlocomotion/drake/blob/f73bcbb1d2722b6ccacfb84a1febf395fdc7ce39/examples/quadrotor/test/quadrotor_dynamics_test.cc#L122)):*
> ```cpp
>   }
> 
>   // @param[in] context a mutable Context to be set from the state vector x.
> ```

nit: `@param[in,out]`

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17254#-:-N31Smaw-jvLaqhr8mKp:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @RussTedrake and @sherm1)

___
*[`examples/quadrotor/test/quadrotor_dynamics_test.cc` line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17254#-N2w3IU-2YmuN337hEtt:-N31IFMW1mS5mIeEBUbd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f73bcbb1d2722b6ccacfb84a1febf395fdc7ce39/examples/quadrotor/test/quadrotor_dynamics_test.cc#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this should be `@param[in,out]` since it gets modified
</blockquote></details>

Done.
___
*[`examples/quadrotor/test/quadrotor_dynamics_test.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17254#-N2w4AbmATg2cQxq0kkD:-N31IMsY2_UaPjQsz-GV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f73bcbb1d2722b6ccacfb84a1febf395fdc7ce39/examples/quadrotor/test/quadrotor_dynamics_test.cc#L122)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: `@param[in,out]`
</blockquote></details>

Done.

**Pull request merged**
