### PR TITLE
Add Monomial::{Substitute,Evaluate}

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5398)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Close #5046, #5047

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-:-KeKwwvXTbkCCctLYUd_:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Beautiful code as always. :lgtm: except minor comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLJItHJm81C3AcdGrS:-KeLJItHJm81C3AcdGrT:b6bdsgl) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/monomial.h#L78)):*
> ```objc
>    * Example 1. Substitution with a fully-specified environment
>    *     (x^3*y^2).Substitute({{ID_x, 2}, {ID_y, 3}})
>    *   = (2^3 * 3^2 = * 8 * 9 = 72, Monomial{} = 1).
> ```

`* 8 * 9` -> `8 * 9`
What does `Monomial{} = 1` mean?

---

*[drake/common/test/monomial_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLM9EylqKHObW03K9_:-KeLM9EylqKHObW03K9a:b-fj4apd) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/test/monomial_test.cc#L80)):*
> ```cpp
>   unordered_map<Variable::Id, double> ExtractIdToDoubleMap(
>       const Environment& env) {
>     unordered_map<Variable::Id, double> map;
> ```

Does it help if we reserve size for `map`, by `map.reserve(env.size())`?

---

*[drake/common/test/monomial_test.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLMNCZYySPj2zz2IsN:-KeLMNCZYySPj2zz2IsO:b6nts3g) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/test/monomial_test.cc#L105)):*
> ```cpp
>   //                      ||                      ||
>   //                      \/                      \/
>   //                double (result2)   ==   double (result1)
> ```

Wow! Great picture.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-:-KeLNGn91llul_02yY-A:b-vwf0tw)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLJItHJm81C3AcdGrS:-KeLNcbaB6j6fjUwPwZy:b-gcu4vq) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/monomial.h#L78)):*
> * 8 * 9 -> 8 * 9

Done. Good catch!

> What does Monomial{} = 1 mean?

In this case, we have a fully-specified environment and we end up with nothing on the Monomial part in the return value (= `pair(72, Monomial{})`). Just wanted to emphasize the fact that `Monomial{}` represents  `1`.

---

*[drake/common/test/monomial_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLM9EylqKHObW03K9_:-KeLPTgdbkWQo2H4PGD_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/test/monomial_test.cc#L80)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Does it help if we reserve size for `map`, by `map.reserve(env.size())`?
</blockquote></details>

Done.

---

*[drake/common/test/monomial_test.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLMNCZYySPj2zz2IsN:-KeLPVHxP1LWAiOeSFrK:b2nh4j5) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/test/monomial_test.cc#L105)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Wow! Great picture.
</blockquote></details>

:-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , platform-review please.

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-:-KeLPYy2EiPvR_nTct1R:bq8ci7j)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLJItHJm81C3AcdGrS:-KeLS39-miz5CDdBm_K7:b-ujncmj) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/monomial.h#L78)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> * 8 * 9 -> 8 * 9

Done. Good catch!

> What does Monomial{} = 1 mean?

In this case, we have a fully-specified environment and we end up with nothing on the Monomial part in the return value (= `pair(72, Monomial{})`). Just wanted to emphasize the fact that `Monomial{}` represents  `1`.
</blockquote></details>

I see. 

It is not related to this PR, but I think we almost get everything to replace `Polynomial` class with symbolic expressions. We can create a `Polynomial` class, which is just a wrapper over `MonomialToCoeffMap`, and a `Term` class, which wraps `pair<double, Monomial>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

*[drake/common/monomial.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLJItHJm81C3AcdGrS:-KeLSifp1Zb7Lo-z6gj9:b-dkmah5) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/monomial.h#L78)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see. 

It is not related to this PR, but I think we almost get everything to replace `Polynomial` class with symbolic expressions. We can create a `Polynomial` class, which is just a wrapper over `MonomialToCoeffMap`, and a `Term` class, which wraps `pair<double, Monomial>`.
</blockquote></details>

Sounds good to me. Let's open an issue and work on it! BTW, I will be there next week as you know. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeLJItHJm81C3AcdGrS:-KeLttfHEI0CqrCWe6p0:bnonu09) ([raw file](https://github.com/robotlocomotion/drake/blob/64ebc8ac4db13573bd51c1ab6dad13a85aceca48/drake/common/monomial.h#L78)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Sounds good to me. Let's open an issue and work on it! BTW, I will be there next week as you know. 
</blockquote></details>

Awesome, let's work on that next week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.cc, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeOoNHAQ33CKrqWp6gn:-KeOoNHBXqz0EjZe6Zgn:b-tldwby) ([raw file](https://github.com/robotlocomotion/drake/blob/d8facf53e250c3b5ff12798d57670882a30f1f1b/drake/common/monomial.cc#L105)):*
> ```cpp
>       coeff *= std::pow(base, exponent);
>     } else {
>       new_powers.insert(p);
> ```

BTW Consider `new_powers.insert(it, p)` to hint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-:-KeOpTJGYKeMX_uTv8Pa:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.cc, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5398#-KeOoNHAQ33CKrqWp6gn:-KeP4rUKshWwMSVKt8Q5:bggj4kd) ([raw file](https://github.com/robotlocomotion/drake/blob/d8facf53e250c3b5ff12798d57670882a30f1f1b/drake/common/monomial.cc#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider `new_powers.insert(it, p)` to hint?
</blockquote></details>

`new_powers.insert(it, p)` doesn't compile because `it` is an iterator of `env` while we need one for `new_powers`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5398)*

**Pull request merged**
