### PR TITLE
Add SpatialInertial::HollowSphereWithDensity()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/18865 is work to helping resolve part of issue https://github.com/RobotLocomotion/drake/issues/18416.

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-:-NP0CNfTDl3K3DJfO724:bnt5bmm)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a minor suggestion
+@ggould-tri for platform review per rotation, please

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-:-NPIvOuX9Tihsf-5XFCT:b-bswwlj)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 196 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-NPIuRpF0s0Qypyo376C:-NPIuRpF0s0Qypyo376D:bmnhth1) ([raw file](https://github.com/RobotLocomotion/drake/blob/14654ddd123ad8b19e27c50b19dff76297b4f742/multibody/tree/spatial_inertia.h#L196)):*
> ```objc
>   /// Creates a spatial inertia for a uniform density thin hollow sphere B about
>   /// its geometric center Bo (which is coincident with B's center of mass Bcm).
>   /// @param[in] density mass per unit area (kg/m²).
> ```

BTW in most cases we measure density in kg/m³ rather than kg/m². Consider whether we ought to use a different parameter name for 2d density. Maybe `areal_density`?
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 252 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-NPIv2m55aGwN5rFynJ6:-NPIv2m55aGwN5rFynJ7:bly4kch) ([raw file](https://github.com/RobotLocomotion/drake/blob/14654ddd123ad8b19e27c50b19dff76297b4f742/multibody/tree/test/spatial_inertia_test.cc#L252)):*
> ```cpp
> // Tests the static method for the spatial inertia of a thin hollow sphere.
> GTEST_TEST(SpatialInertia, HollowSphereWithDensity) {
>   const double density = 80;  // density per unit area is 80 kg/m².
> ```

BTW `areal_density` to avoid confusion?

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-:-NPJ3ZLcAkd2kUA5_6fH:bnfp4nl)* status: 2 unresolved discussions (waiting on @mitiguy and @sherm1)

___
*[`multibody/tree/spatial_inertia.h` line 196 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-NPIuRpF0s0Qypyo376C:-NPJ2jn2Bu4UkHvuUy_T:b-wgvrzl) ([raw file](https://github.com/RobotLocomotion/drake/blob/14654ddd123ad8b19e27c50b19dff76297b4f742/multibody/tree/spatial_inertia.h#L196)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW in most cases we measure density in kg/m³ rather than kg/m². Consider whether we ought to use a different parameter name for 2d density. Maybe `areal_density`?
</blockquote></details>

wikipedia suggests "area density" https://en.wikipedia.org/wiki/Area_density

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release  please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-:-NPKA3AUEZNvc80wxIqR:b-be3ffi)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 196 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-NPIuRpF0s0Qypyo376C:-NPJww9v8K3HNhtt1GFF:b-xh3l7c) ([raw file](https://github.com/RobotLocomotion/drake/blob/14654ddd123ad8b19e27c50b19dff76297b4f742/multibody/tree/spatial_inertia.h#L196)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

wikipedia suggests "area density" https://en.wikipedia.org/wiki/Area_density
</blockquote></details>

Done.  Replaced with area density.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 252 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-NPIv2m55aGwN5rFynJ6:-NPJzoFm1AKibUolsZum:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/14654ddd123ad8b19e27c50b19dff76297b4f742/multibody/tree/test/spatial_inertia_test.cc#L252)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `areal_density` to avoid confusion?
</blockquote></details>

Done.

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release  please.

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-leak-sanitizer  please.

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18865#-:-NPKoSnwEe-TioBi3XoH:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @sherm1)

**Pull request merged**
