### PR TITLE
Print warning and do not fail if MATLAB version cannot be determined

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8250)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8250#-:-L6vOjMXDg9jtdQEJ1dT:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by jamiesnape** [comment]
Increasing priority since this is causing persistent flakes.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8250#-:-L6wJrh-bbXcoPuH37a4:bnfp4nl)*

**Pull request merged**
