### PR TITLE
ExtractPrincipalSubmatrix and ToLowerTriangularColumnsFromMatrix

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-:-Nl9PTH0AANVMfuhbHz9:bggbbet)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 206 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9QUBR2FbGewDuWCkf:-Nl9V1DO-ZSz12ML8sWv:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d98166b16026784102f38462164ea3ea3ce90a40/math/matrix_util.h#L206)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Public documentation should use `///` or `/*`, not the two backslash.
</blockquote></details>

Done.
___
*[`math/matrix_util.h` line 211 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9Qu1uDKoxgBtqQM5T:-Nl9URND0Gig0-GvCxgc:bdkv5pi) ([raw file](https://github.com/RobotLocomotion/drake/blob/d98166b16026784102f38462164ea3ea3ce90a40/math/matrix_util.h#L211)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I wonder if it is better to use `std::vector<int>` instead of `std::set<int>` as the type of `indices`.  Using `std::vector<int>` allows the user to specify the order of the indices, which is more flexible than the `indices`. And we can throw an error if there are duplicated indices.
</blockquote></details>

My preference is to make the user manually permute later. The use of `std::set` makes this both safer to code with, and also enables more efficient code so that we can stride through contiguous blocks of memory in the big matrix. I think this later point could be very important for minors of large matrices.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 211 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9Qu1uDKoxgBtqQM5T:-Nl9W86aDZQYI6hqmDDS:b-tfj331) ([raw file](https://github.com/RobotLocomotion/drake/blob/d98166b16026784102f38462164ea3ea3ce90a40/math/matrix_util.h#L211)):*
That makes sense.

> and also enables more efficient code so that we can stride through contiguous blocks of memory in the big matrix.

This is not always true. Eigen::MatrixBase<Derived> can capture the matrix that doesn't occupy contiguous block of memory. Eigen::Matrix has a `stride` parameter which allows it to occupy non-contiguous memory.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 211 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9Qu1uDKoxgBtqQM5T:-Nl9Yf5VEWe5XJqXtKcH:b8hc86f) ([raw file](https://github.com/RobotLocomotion/drake/blob/d98166b16026784102f38462164ea3ea3ce90a40/math/matrix_util.h#L211)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

That makes sense.

> and also enables more efficient code so that we can stride through contiguous blocks of memory in the big matrix.

This is not always true. Eigen::MatrixBase<Derived> can capture the matrix that doesn't occupy contiguous block of memory. Eigen::Matrix has a `stride` parameter which allows it to occupy non-contiguous memory.
</blockquote></details>

Fair. My assumption is that copying the matrix using the block operations when possible will be faster than directly looping and copying. But I don't have a benchmark for this.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 211 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9Qu1uDKoxgBtqQM5T:-Nl9__y55iBTFm28PHRk:b-skp0c2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d98166b16026784102f38462164ea3ea3ce90a40/math/matrix_util.h#L211)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Fair. My assumption is that copying the matrix using the block operations when possible will be faster than directly looping and copying. But I don't have a benchmark for this.
</blockquote></details>

Sounds good. I mark myself satisfied.
___
*[`math/matrix_util.h` line 213 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9_eku0zCJAhVYDeQ_:-Nl9_ekv8_FeNB79mMIG:b20crtu) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2cf5806ac129bbcbcb75acbe50fdae8f1bfb5c1/math/matrix_util.h#L213)):*
> ```objc
> MatrixX<typename Derived::Scalar> ExtractPrincipalSubmatrix(
>     const Eigen::MatrixBase<Derived>& mat, const std::set<int>& indices) {
>   {
> ```

This open brace is redundant?
___
*[`math/matrix_util.h` line 218 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9_7AG7zIGGv3TpuGW:-Nl9_7AG7zIGGv3TpuGX:ba2xgmu) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2cf5806ac129bbcbcb75acbe50fdae8f1bfb5c1/math/matrix_util.h#L218)):*
> ```objc
>     // [intervals[i][0], intervals[i][1]).
>     std::vector<std::pair<int, int>> intervals;
>     int interval_start{0};
> ```

Why `interval_start` is initialized to 0? If I have `indices = {2, 3, 4}`, then `intervals` would be {(0, 5)}? I would think that interval_start should be initialized to `*(indices.begin())`.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 213 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9_eku0zCJAhVYDeQ_:-NlA2sZa6a82iiwAS1bt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2cf5806ac129bbcbcb75acbe50fdae8f1bfb5c1/math/matrix_util.h#L213)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This open brace is redundant?
</blockquote></details>

Done.
___
*[`math/matrix_util.h` line 218 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-Nl9_7AG7zIGGv3TpuGW:-NlA2rjJ7o2HY_kxdWDa:b-yh10tr) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2cf5806ac129bbcbcb75acbe50fdae8f1bfb5c1/math/matrix_util.h#L218)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why `interval_start` is initialized to 0? If I have `indices = {2, 3, 4}`, then `intervals` would be {(0, 5)}? I would think that interval_start should be initialized to `*(indices.begin())`.
</blockquote></details>

Done. Good catch

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/test/matrix_util_test.cc` line 140 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlAdrLF6cECQzSaaoaC:-NlAdrLF6cECQzSaaoaD:b-6zntsy) ([raw file](https://github.com/RobotLocomotion/drake/blob/2dc080acad1003f2dddcca99d6971deb81392d78/math/test/matrix_util_test.cc#L140)):*
> ```cpp
>   }
>   // A non-contiguous set of indices
>   std::set<int> submatrix_indices{0, 1, 3, 4, 5, 7};
> ```

Could you add a new test that the indices doesn't start from 0? This test doesn't capture the error we saw before.
___
*[`bindings/pydrake/math/test/math_test.py` line 536 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlB-tzzDboilMEThjFa:-NlB-tzzDboilMEThjFb:bndpnc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/2dc080acad1003f2dddcca99d6971deb81392d78/bindings/pydrake/math/test/math_test.py#L536)):*
> ```Python
> 
>         lower_triangular2 = mut.ToLowerTriangularColumnsFromMatrix(
>             symmetric_mat)
> ```

Use named argument `matrix =symmetric_mat`.
___
*[`bindings/pydrake/math/test/math_test.py` line 542 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlB-zBvBDPBFfmaqCyQ:-NlB-zBvBDPBFfmaqCyR:b47z5mg) ([raw file](https://github.com/RobotLocomotion/drake/blob/2dc080acad1003f2dddcca99d6971deb81392d78/bindings/pydrake/math/test/math_test.py#L542)):*
> ```Python
>         minor = mut.ExtractPrincipalSubmatrix(symmetric_mat, minor_indices)
>         np.testing.assert_array_equal(
>             minor, minor_indices[np.ix_(minor_indices, minor_indices)])
> ```

Ditto, use named argument.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/test/matrix_util_test.cc` line 140 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlAdrLF6cECQzSaaoaC:-NlOaPzJEY1x3HdjRHRR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2dc080acad1003f2dddcca99d6971deb81392d78/math/test/matrix_util_test.cc#L140)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you add a new test that the indices doesn't start from 0? This test doesn't capture the error we saw before.
</blockquote></details>

Done.
___
*[`bindings/pydrake/math/test/math_test.py` line 536 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlB-tzzDboilMEThjFa:-NlP9BBI17fJlw3AyBiE:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2dc080acad1003f2dddcca99d6971deb81392d78/bindings/pydrake/math/test/math_test.py#L536)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Use named argument `matrix =symmetric_mat`.
</blockquote></details>

Done.
___
*[`bindings/pydrake/math/test/math_test.py` line 542 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlB-zBvBDPBFfmaqCyQ:-NlP9B0KD52g18cowCde:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2dc080acad1003f2dddcca99d6971deb81392d78/bindings/pydrake/math/test/math_test.py#L542)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto, use named argument.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:  With a couple of small things.

> Reviewed 1 of 3 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-:-NlQ0ob30cyDgIfkUcYk:bk601b3)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 209 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlQ-gJPCwJRreXeB_7m:-NlQ-gJPCwJRreXeB_7n:by0i2v2) ([raw file](https://github.com/RobotLocomotion/drake/blob/5230d6bd34ca6f7023e693177dc4c72f8b5bcf59/math/matrix_util.h#L209)):*
> ```objc
> /// indices must be in monotonically increasing order. This method makes
> /// no assumptions about the symmetry of the matrix, nor that the matrix is
> /// square.
> ```

nit: "...nor that the matrix is square. However, all indices must be valid for both rows and columns."
___
*[`math/matrix_util.h` line 220 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlQ01vV6r0GM2HbWtwN:-NlQ01vV6r0GM2HbWtwO:b-7d4ww7) ([raw file](https://github.com/RobotLocomotion/drake/blob/5230d6bd34ca6f7023e693177dc4c72f8b5bcf59/math/matrix_util.h#L220)):*
> ```objc
>   int last_idx{*indices.begin()};
>   DRAKE_ASSERT(last_idx >= 0);
>   for (const auto& i : indices) {
> ```

nit In this case, you save one character by typing `const int&` instead of `const auto&`.  In this case, using `auto` is clearly a loss of clarity without *any* gain.
___
*[`math/test/matrix_util_test.cc` line 88 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-NlQ0SPY0cLjEDDIboWL:-NlQ0SPY0cLjEDDIboWM:b-iqhccp) ([raw file](https://github.com/RobotLocomotion/drake/blob/5230d6bd34ca6f7023e693177dc4c72f8b5bcf59/math/test/matrix_util_test.cc#L88)):*
> ```cpp
>   Eigen::Matrix3d X2;
>   // clang-format off
>   X2 << 1, 2, 3,
> ```

BTW If you made this asymmetric (putting 7, 8, 9 in the upper triangle), this test would provide additional evidence that the right part of the matrix is being read. As it is now, it could be reading the wrong part and the test would still pass.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-:-NlTY-66ChIVjj75n-dv:b-l8xbmn)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20646#-:-NlUPte0CspaVXYUG0WY:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai

**Pull request merged**
