### PR TITLE
[yaml] Add sugar to write serialized files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #15868.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one real question about definition and a few cosmetic thoughts.

> Reviewed 2 of 8 files at r1, 2 of 3 files at r3, 4 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000#-:-MnRSWd8CNmkYUlWo2LR:b-mrzb1s)* status: 5 unresolved discussions (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.h, line 39 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRGRwqEnDzz3SE5Ysv:-MnRGRwqEnDzz3SE5Ysw:b6aw9y7) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_io.h#L39)):*
> ```objc
>     const std::optional<Serializable>& defaults = std::nullopt);
> 
> /** Saves data as a YAML-formatted string.
> ```

BTW Have you tried grouping these? It' s a shame that they document *exactly* the same thing (but for where the serialization goes). But all the semantics are identical. It seems to work (as shown here https://drake.mit.edu/doxygen_cxx/group__visualization.html under "Visualizing contact results"). It's a *bit* muddy just because all of the methods get hoisted out of the file, away from the class, and into a doxygen group. But it does seem to save on bits.
___
*[common/yaml/yaml_write_archive.h, line 25 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRHWH4BWPce04A5Y7r:-MnRHWH565aoD65qx1wo:bv2i7w6) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L25)):*
> ```objc
> namespace yaml {
> 
> /// (Advanced) A helper class for @ref yaml_serialization "YAML Serialization"
> ```

BTW Everything about this class is labeled as "advanced" or "internal use only". Why not just put it in an `internal::` namespace?
___
*[common/yaml/yaml_write_archive.h, line 85 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRKC0O5e_Th586iJjx:-MnRKC0O5e_Th586iJjy:b-3wjyix) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L85)):*
> ```objc
> 
>   /// (Internal use only.)
>   static void WriteFile(const std::string& filename, const std::string& data);
> ```

Given this is static and only called by `SaveYamlFile` in `yaml_io.h`, why is this defined here instead of there?
___
*[common/yaml/yaml_write_archive.cc, line 184 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRJxuN2RltQ9DwmuYa:-MnRJxuN2RltQ9DwmuYb:b4zg83i) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.cc#L184)):*
> ```cpp
> }
> 
> // N.B. This is unit tested via yaml_io_test, not yaml_write_archive_test.
> ```

If you continue with keeping this here, it's probably worth indicating that this is tested *indirectly* in `yaml_io_test` via calls to `SaveYamlFile()`.

(Also, only the first failure condition is tested. I'm not entirely sure how to orchestrate a test that would trigger the second....but it is untested.)
___
*[common/yaml/test/yaml_io_test.cc, line 11 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRI8ktE0GjJxgDpCPF:-MnRI8ktE0GjJxgDpCPG:bj51xi3) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/test/yaml_io_test.cc#L11)):*
> ```cpp
> #include "drake/common/yaml/test/example_structs.h"
> 
> // This unit test only covers the basics of the helper functions in yaml_io.
> ```

BTW The word "only" is ambiguous. I infer that it applies to "the basics" (i.e., the tests aren't exhaustive). But it can also be interpreted to mean, only testing things in `yaml_io`. But we know it tests things in `yaml_write_archive.cc` (i.e., the new `WriteFile()` method). Some clarification of the scope of this file would be helpful.

---- 

Follow up.

This comment completely disappears if the file logic moves to `yaml_io.h`.
___
*[common/yaml/test/yaml_io_test.cc, line 66 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRJcXZEf7E53Bqoiy8:-MnRJcXZEf7E53Bqoiy9:b9jfgdm) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/test/yaml_io_test.cc#L66)):*
> ```cpp
> }
> 
> GTEST_TEST(YamlIoTest, SaveFile4) {
> ```

BTW Is this number "4" an anachronism? It seems to invite the reader to look for 2 & 3.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)* status: 5 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[common/yaml/yaml_write_archive.h, line 85 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRKC0O5e_Th586iJjx:-MnRTrf5Ck5jWDOU66iB:bet3zcz) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L85)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Given this is static and only called by `SaveYamlFile` in `yaml_io.h`, why is this defined here instead of there?
</blockquote></details>

I had the same question but then I assumed the intention is that everything `yaml_io.h` is user-facing sugar and this method is for internal use only as the comments suggests. 

Though looking at it again, the combination of doxygen comment `///` and "internal use only" is causing some dissonance in my mind.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)* status: 5 unresolved discussions (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[common/yaml/yaml_write_archive.h, line 85 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRKC0O5e_Th586iJjx:-MnRZ9pa7L9ksu9bCEET:b-td5f40) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L85)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I had the same question but then I assumed the intention is that everything `yaml_io.h` is user-facing sugar and this method is for internal use only as the comments suggests. 

Though looking at it again, the combination of doxygen comment `///` and "internal use only" is causing some dissonance in my mind.
</blockquote></details>

I wasn't thinking the *function* would go here. I was thinking the function's implementation would go inside `SaveYamlFile()` (or whatever it is). As it is, `SaveYamlFile()`'s entire body is to call this method. My best assumption is that there's a larger ecosystem that we haven't seen yet in which multiple public APIs provide a mechanism that eventually would call `WriteFile()`.

**Comment by jwnimmer-tri** [comment]
___
*[common/yaml/yaml_write_archive.h, line 85 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRKC0O5e_Th586iJjx:-MnR_50QCDkaxDugJLYq:b-dov1ve) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L85)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I wasn't thinking the *function* would go here. I was thinking the function's implementation would go inside `SaveYamlFile()` (or whatever it is). As it is, `SaveYamlFile()`'s entire body is to call this method. My best assumption is that there's a larger ecosystem that we haven't seen yet in which multiple public APIs provide a mechanism that eventually would call `WriteFile()`.
</blockquote></details>

Working

The goal was just to keep function definitions (bodies) out of header files, i.e., don't put the code here into the templated save function(s).

I can make a internal-namespace free function in `yaml_io.h` instead, which is probably better.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[common/yaml/yaml_io.h, line 39 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRGRwqEnDzz3SE5Ysv:-MnRyAajD5J1maWfYh27:b-q5nklo) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_io.h#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Have you tried grouping these? It' s a shame that they document *exactly* the same thing (but for where the serialization goes). But all the semantics are identical. It seems to work (as shown here https://drake.mit.edu/doxygen_cxx/group__visualization.html under "Visualizing contact results"). It's a *bit* muddy just because all of the methods get hoisted out of the file, away from the class, and into a doxygen group. But it does seem to save on bits.
</blockquote></details>

OK The `namespace yaml` page in Doxygen is pretty small, so they're effectively in a group already.  I'm going to save most of the Doxygen polishing until the PR that rewrites the introductory text.
___
*[common/yaml/yaml_write_archive.h, line 25 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRHWH4BWPce04A5Y7r:-MnRwMOk5NrrAeb7mbrJ:b-w11h4j) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Everything about this class is labeled as "advanced" or "internal use only". Why not just put it in an `internal::` namespace?
</blockquote></details>

Eventually I might do that (once we've proven that the non-advanced API can meet 100% of the use cases), but I don't want to do that deprecation yet, in part because I'm not sure yet whether the new APIs are going to be sufficient for all cases.
___
*[common/yaml/yaml_write_archive.h, line 85 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRKC0O5e_Th586iJjx:-MnRyOK76lZybCCHo7tA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.h#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

The goal was just to keep function definitions (bodies) out of header files, i.e., don't put the code here into the templated save function(s).

I can make a internal-namespace free function in `yaml_io.h` instead, which is probably better.
</blockquote></details>

Done.
___
*[common/yaml/test/yaml_io_test.cc, line 11 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRI8ktE0GjJxgDpCPF:-MnRxWdE09RCbM_KqAIo:b-kv3ltj) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/test/yaml_io_test.cc#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The word "only" is ambiguous. I infer that it applies to "the basics" (i.e., the tests aren't exhaustive). But it can also be interpreted to mean, only testing things in `yaml_io`. But we know it tests things in `yaml_write_archive.cc` (i.e., the new `WriteFile()` method). Some clarification of the scope of this file would be helpful.

---- 

Follow up.

This comment completely disappears if the file logic moves to `yaml_io.h`.
</blockquote></details>

Done (moved).
___
*[common/yaml/test/yaml_io_test.cc, line 66 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRJcXZEf7E53Bqoiy8:-MnRx_dC3GNBx0vuA0Jf:b-41be0g) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/test/yaml_io_test.cc#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is this number "4" an anachronism? It seems to invite the reader to look for 2 & 3.
</blockquote></details>

Done.

(I was trying to indicate the function arity, but that wasn't clear.)
___
*[common/yaml/yaml_write_archive.cc, line 184 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnRJxuN2RltQ9DwmuYa:-MnRxKNHEXzPmS8Yl3q3:b-rkv8yh) ([raw file](https://github.com/robotlocomotion/drake/blob/94a00ae3fb4e6c7e14f918d41b0d1ce21807d761/common/yaml/yaml_write_archive.cc#L184)):*
> If you continue with keeping this here, ...

Done (moved).

> (Also, only the first failure condition is tested. I'm not entirely sure how to orchestrate a test that would trigger the second....but it is untested.)

I agree.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.cc, line 10 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnS0FuJ91iSA5Keumjf:-MnS0FuJ91iSA5Keumjg:b-1d7pkm) ([raw file](https://github.com/robotlocomotion/drake/blob/a9bd662336b93cbb477f9663be562271e0c54c6d/common/yaml/yaml_io.cc#L10)):*
> ```cpp
> 
> void WriteFile(
>     const std::string& filename, const std::string& data) {
> ```

BTW Probably still worth preserving the note that it is tested *indirectly* in yaml_io_test.cc. Or a note there that says it serves as the test for this function. Just so we maintain the same sense of, "we understand our test coverage".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.cc, line 10 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnS0FuJ91iSA5Keumjf:-MnS1_4uEvyouhy-sd6f:b-223yxn) ([raw file](https://github.com/robotlocomotion/drake/blob/a9bd662336b93cbb477f9663be562271e0c54c6d/common/yaml/yaml_io.cc#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Probably still worth preserving the note that it is tested *indirectly* in yaml_io_test.cc. Or a note there that says it serves as the test for this function. Just so we maintain the same sense of, "we understand our test coverage".
</blockquote></details>

OK To me, it's not unusual for a unit test to call only the public API, and thus any helper functions are only covered indirectly.  I don't think we're at any notable risk of a future developer misunderstanding how `yaml_io` and `yaml_io_test` interact.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16000)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

___
*[common/yaml/yaml_io.cc, line 10 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16000#-MnS0FuJ91iSA5Keumjf:-MnS2RRmCTwwx5xpIO5g:bdqutqp) ([raw file](https://github.com/robotlocomotion/drake/blob/a9bd662336b93cbb477f9663be562271e0c54c6d/common/yaml/yaml_io.cc#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK To me, it's not unusual for a unit test to call only the public API, and thus any helper functions are only covered indirectly.  I don't think we're at any notable risk of a future developer misunderstanding how `yaml_io` and `yaml_io_test` interact.
</blockquote></details>

I buy that.

**Pull request merged**
