### PR TITLE
[parsing] Implement parent model name for Sdformat

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This is part of a long campaign to modernize Parser APIs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18550)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18550#-:-NL8BBJR2DUJmkVBETmn:b-safpmt)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri or delegate for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18550#-:-NL8BFPM0BDo1hRUBt67:baf5qp0)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
From a very quick skim, I saw only unit tests not any example of how this is used in reality.  Could you help point me to how this will end up being used?  Will it ever make its way to an end-user entry point, or is only to be used from internal calls like the model directives engine?

**Review by rpoyner-tri — COMMENTED** [review]
See the newly updated #18157 for context. The parent_model_name will be used to implement the Parser("prefix", plant) constructor.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18550#-:-NL8Cjqq4tX1D1BWwcRY:bz12m6l)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18550#-:-NLBv5it2qN8VjvqYKKy:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_sdf_parser.h` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18550#-NLBrSSX8gvPNqIFrP1F:-NLBrSSX8gvPNqIFrP1G:b-gc9hlz) ([raw file](https://github.com/robotlocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/detail_sdf_parser.h#L35)):*
> ```objc
> // @param parent_model_name
> //   Optional name of parent model. If set, this will be prefixed with the model
> //   name (either `model_name` or from the "name" attribute) using the SDFormat
> ```

nit I like that the full name will be `{parent_model_name}::{model_name}`; this is as I'd expect.

However, in the comment here the phrasing "[the parent model name] will be **prefixed with** the model name" seems to imply the opposite, i.e., `{model_name}::{parent_model_name}`.

Ditto below.
___
*[`multibody/parsing/detail_sdf_parser.cc` line 1331 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18550#-NLBtO-b50-waSSyKgOu:-NLBtO-b50-waSSyKgOv:b4fd0hr) ([raw file](https://github.com/robotlocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/detail_sdf_parser.cc#L1331)):*
> ```cpp
>       const RigidTransformd X_LcM = ResolveRigidTransform(
>           diagnostic, model.SemanticPose(),
>           sdf::JoinName(model.Name(), canonical_link_name));
> ```

It seems to me like possibly this should be `model_name` instead of `model.Name()`.  Can you walk me though the reasoning one way or the other?  Or point to unit test(s) that demonstrate?
___
*[`multibody/parsing/test/detail_sdf_parser_test.cc` line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18550#-NLBuuQoCOISAYTXs4Q8:-NLBuuQoCOISAYTXs4Q9:bmno8qa) ([raw file](https://github.com/robotlocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/test/detail_sdf_parser_test.cc#L121)):*
> ```cpp
>   void ParseTestString(
>       const std::string& inner,
>       const std::string& sdf_version = "1.6",
> ```

nit The call sites would be less brittle if we used `optional<>` here and `value_or("1.6")` in the body below.  As it stands, we need to copy-paste "1.6" to the new call sites, which will get out of date as we evolve our default version.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLBtO-b50-waSSyKgOu:-NLXqC5jDfNVULcp9t-S:b-8c7l7t) ([raw file](https://github.com/RobotLocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/detail_sdf_parser.cc#L1331)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me like possibly this should be `model_name` instead of `model.Name()`.  Can you walk me though the reasoning one way or the other?  Or point to unit test(s) that demonstrate?
</blockquote></details>

I tried your proposed edit. Interestingly, it breaks not only parsing tests, but also scoped_names_test and some processor directives tests.

The name constructed here is only used to pass to sdf::SemanticPose::Resolve(), which fails to resolve under the swap of `model.Name()` to `model_name`. I haven't yet read all the implementation details of sdf::, but I don't think it will change my conclusion that the current version of the code is correct.

**Review by rpoyner-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review, Thursday schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-:-NLY7QAD4MV63GL1DslM:b-ymbecm)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 1 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-:-NLb4i8J5TKTj1_Y-eN3:bhm0jc2)* status: 3 unresolved discussions (waiting on @azeey and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLb4_HG1wt54OnI6hdM:-NLb4_HG1wt54OnI6hdN:bapzs8a) (no related file):*
BTW Just confirm, this portion of "compaign modernize Parser APIs" is perhaps captured best by https://github.com/RobotLocomotion/drake/issues/18059, per linked PR and project board?

___
___
*[`multibody/parsing/detail_sdf_parser.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLBtO-b50-waSSyKgOu:-NLb3snLA9BNzRopvXyd:bwkn56m) ([raw file](https://github.com/RobotLocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/detail_sdf_parser.cc#L1331)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I tried your proposed edit. Interestingly, it breaks not only parsing tests, but also scoped_names_test and some processor directives tests.

The name constructed here is only used to pass to sdf::SemanticPose::Resolve(), which fails to resolve under the swap of `model.Name()` to `model_name`. I haven't yet read all the implementation details of sdf::, but I don't think it will change my conclusion that the current version of the code is correct.
</blockquote></details>

FYI Unfortunately, I have nothing useful to contribute here, but \cc @azeey just in case you might know.
___
*[`multibody/parsing/test/detail_sdf_parser_test.cc` line 268 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLb4vDG2qbU17gYLdgT:-NLb4vDH30fkQkNRy7Vf:bmeybka) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee6c843dec0658e427517a73ade491a724e706e3/multibody/parsing/test/detail_sdf_parser_test.cc#L268)):*
> ```cpp
>       AddModelFromSdfFile(acrobot_sdf_name, "", "3");
>   ModelInstanceIndex acrobot4 =
>       AddModelsFromSdfFile(acrobot_sdf_name, "4").at(0);
> ```

BTW No direct usage of non-empty model name + parent model name. Consider adding case.

**Comment by azeey** [comment]
*[`multibody/parsing/detail_sdf_parser.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLBtO-b50-waSSyKgOu:-NLb63URBUtjW6CBHWvR:bt2wehv) ([raw file](https://github.com/RobotLocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/detail_sdf_parser.cc#L1331)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Unfortunately, I have nothing useful to contribute here, but \cc @azeey just in case you might know.
</blockquote></details>

The `model_name` parameter is the fully qualified/scoped name of the model whereas `model.Name()` is always just the local name. It is passed into `AddModelFromSpecification` as it is called recursively to create nested models. `model_name` should probably be named `full_model_name` or something similar.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLb4_HG1wt54OnI6hdM:-NLb8-gR4ywlwdYsxG6h:btqqu5l) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Just confirm, this portion of "compaign modernize Parser APIs" is perhaps captured best by https://github.com/RobotLocomotion/drake/issues/18059, per linked PR and project board?
</blockquote></details>

Correct.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLBtO-b50-waSSyKgOu:-NLb8TNX0tlqON2IWxIb:b-t90qg9) ([raw file](https://github.com/RobotLocomotion/drake/blob/38c730a5e773f9410193da1b9ec57c3add8c56a9/multibody/parsing/detail_sdf_parser.cc#L1331)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

The `model_name` parameter is the fully qualified/scoped name of the model whereas `model.Name()` is always just the local name. It is passed into `AddModelFromSpecification` as it is called recursively to create nested models. `model_name` should probably be named `full_model_name` or something similar.
</blockquote></details>

Ah.  I think what I was missing was that `canonical_link_name` is already an absolute anchor, so tacking on only the local name what we want.  I was worried about accidentally using a local (only) name when resolving.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18550)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18550#-NLb4_HG1wt54OnI6hdM:-NLbF1EB9051uTbLSkqL:b-ucfknh) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Correct.
</blockquote></details>

Thanks!

___

**Pull request merged**
