### PR TITLE
Add .png schematic to show Parent/Child bodies and joint M/F frames.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961)

### CODE REVIEW

**Comment by sherm1** [comment]
Per f2f with @mitiguy: we're agreed on needing to distinguish the parent/child joint frames from the inboard/outboard mobilizer frames we call F and M. The Jp Jc names are awkward though -- besides the Jacobian-ish look (which we can deal with) it's not obvious how to extend that to multiple children. Does that matter? Paul thought it would make more sense if these started with the body name, like Pj and Cj which for multiple joints could be P₁/C₁, P₂/C₂, etc. The mobilizer F and M frames work fine that way also (F₁/M₁ etc.). OTOH we rarely need to talk about multiple joints at the same time.

BTW (just an aside) the "joint" concept is more general than the "mobilizer" concept -- the sdf diagram is showing the simplest kind of joint that connects two bodies. There are joints that can involve more -- Russ proposed a "gripper joint" the other day that make two fingers move by the same amount (i.e. relating three bodies: palm, finger1, finger2). A human knee joint relates tibia, femur, and patella (shoulders are even worse). OTOH a mobilizer always relates two bodies.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGFInDh0PRmx5f2HhmP:bnfp4nl)* status: 4 unresolved discussions, LGTM missing from assignee mitiguy, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/plant/images/BodyParentChildJointFM.png, line  at r1](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MG4-Ds_9cif25BapIgn:-MGFH3_WBYednU_YFfB7:b-opkvj8) ([raw file](https://github.com/robotlocomotion/drake/blob/40241522d31f7b8d4c4df8f07352b66624d69e8d/multibody/plant/images/BodyParentChildJointFM.png#L)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

No - I removed the .svg from my commit.
I reverted to the .png as it is better.
If all the reviewers agree, I am OK with adding an additional .svg -- but that is not my preference.   I imagine that they may quickly become outdated and different than the .png 
</blockquote></details>

I agree with other discussions that this PR is definitely a strict improvement, so I'll mark myself as satisfied, and just make small, ignorable comments below this line.

---

I think adding both is better than adding one.
Then there would be a uber brief README stating how to generate the PNG from SVG (e.g. `convert ...` or `inkscape --without-gui ...`)

FWIW I'm still a bit confused as to why the SVG renders poorly - can you push a separate commit so that we can see to confirm? ("trust but verify"?)
Especially since this SVG renders perfectly fine as-is?
https://raw.githubusercontent.com/osrf/sdf_tutorials/master/spec_model_kinematics/joint_frames.svg

As an additional bikeshed, I still prefer the style of Ale's image, but both versions are now legible, so I'm good either way.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961)* status: 4 unresolved discussions, LGTM missing from assignee mitiguy, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/plant/images/BodyParentChildJointFM.png, line  at r1](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MG4-Ds_9cif25BapIgn:-MGFVoBz3bS5SzEO34Bu:bysj8lc) ([raw file](https://github.com/robotlocomotion/drake/blob/40241522d31f7b8d4c4df8f07352b66624d69e8d/multibody/plant/images/BodyParentChildJointFM.png#L)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I agree with other discussions that this PR is definitely a strict improvement, so I'll mark myself as satisfied, and just make small, ignorable comments below this line.

---

I think adding both is better than adding one.
Then there would be a uber brief README stating how to generate the PNG from SVG (e.g. `convert ...` or `inkscape --without-gui ...`)

FWIW I'm still a bit confused as to why the SVG renders poorly - can you push a separate commit so that we can see to confirm? ("trust but verify"?)
Especially since this SVG renders perfectly fine as-is?
https://raw.githubusercontent.com/osrf/sdf_tutorials/master/spec_model_kinematics/joint_frames.svg

As an additional bikeshed, I still prefer the style of Ale's image, but both versions are now legible, so I'm good either way.
</blockquote></details>

@ericcousineau-tri   I sent you a detailed email to respond to your comments and hopefully alleviate some of your concerns.  I tried to include my comments here, but was only able to upload the .png file.  The .svg file failed to load here (I do not know why).   Instead Reviewable gave the error:

"Failed to upload BodyParentChildJointWithCM.svg: Uploads of image/svg+xml files not supported."

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGFaKf12qA7XB_m7-nE:bm9o57a)* status: 4 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
Oops -- there are still unresolved comments @sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGFaXjsD8YssnOdLRVj:b-l7n8sh)* status: 4 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Wait, the picture is still showing F & M frames. Didn't we agree to switch to Jp and Jc? There is an extended discussion about that above. I'll :lgtm_cancel: until we resolve that to avoid confusion.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGG0LT_8OiAlLvXufsN:by0n79p)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
@sherm1  From looking at comments from @amcastro-tri, I thought we had partial agreement that the goal of this PR was to add a simple picture into the documentation and make some minor non-contentious improvements (Alejandro to confirm his understanding/intent).   I embarked on this PR for Kaizen, gain some ground.  The changes needed to fix the M and F frames are (in my opinion) much more involved.  I think we can address those changes (which seem also related to issues #12789 and #13040) -- but not in this PR.    This PR hopes to be a small step in a helpful direction.  I am fine with thinking about switching to Jp and Jc -- but not in this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGGEGYL-ilQj2zoPS_4:bju8qfb)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
To me it seems like a step in the _wrong_ direction if it adds more weight to the wrong choice of naming. So in that sense it is anti-Kaizen. OTOH the addition of a picture would be very nice, but not if it cements deprecated terminology in a user-visible API.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGHGVoo5XmjEJs89Yal:bnx2k7x)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
> From looking at comments from @amcastro-tri, I thought we had partial agreement that the goal of this PR was to add a simple picture into the documentation

Yes, but with the Drake globally accepted convention Jp/Jc. As an aside, I still like the pic in the link Eric posted in that provides the information that Drake users must understand to create models, and it doesn't look cluttered at all IMO. The transforms IMO do convey information that is a must to understand. I failed to document this properly before, but it'd seem this PRs intention was to help with that?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGIuxYI8YqRfIE0ySLD:b-yc4n26)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
@sherm1  @amcastro-tri 
* If the new picture is a show-stopper, I will link to the other picture.
* If any picture is a show-stopper, I will remove the link to the pictures so this PR just improves the current text.
* If the goal for this PR is different, than I am concerned about this becoming more of an epic.
Some data for occurences of a specific text search:
grep -r "frame M" ./multibody | wc -l
160
grep -r "frame F" ./multibody | wc -l
261

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGK7k6o0aUKOsdRChCu:beokfjq)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
Perhaps helpful to provide more data:
grep -r "frame M" ./multibody | wc -l                  160
grep -r "frame F" ./multibody | wc -l                   261
grep -r "frame F" ./multibody/plant | wc -l          23
grep -r "frame M" ./multibody/plant | wc -l        12
grep -r "frame M" ./multibody/tree | wc -l        142
grep -r "frame F" ./multibody/tree | wc -l         216

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGKl79iEMjC6d21cn6V:byg6pyy)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
Per f2f with Sherm, we thought we should push the updated text and add information (text) adjacent to the picture indicating that Jp and Jc are used by .sdf  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGM9JzzA4wx_hJx1kfc:by8xpsq)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
From Paul and Sherm Catch-up Meeting Topics/Notes:

We discussed joint notation PR. Plan: check in a png with the F/M figure but including some text on the figure that says sdf Jp==F and Jc==M. Add a TODO suggesting that we convert to sdf notation in MBPlant, referencing the issue. Also include the text improvements.

Paul surveyed Drake and discovered lots of references to F and M and also some in various examples. So the conversion will be some work. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGMAvpCDnwNynXYw13O:bnxbnxv)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
> Paul surveyed Drake and discovered lots of references to F and M and also some in various examples. So the conversion will be some work.

Those numbers are misleading. There is nothing in that search that confines it to either "mobilizer" uses and/or "joint" uses (and I don't think you can).

I don't understand why the resistance to change to Jp/Jc, it seems like an super quick change. At this point, after so much discussion, I'd flag it as a defect.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGP0fZ3-4_be6hEFjXs:b-oknrxq)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
Here is my plan:
1.  I'll add the figure with frame M and frame F with accompanying text of Jp and Jc.
2.  I'll add a TODO that I will update to Jp and Jc.
4.  Hopefully, that will merge into master -- marked with a TODO and a plan to fix the defect.
3.  If it merges into master very soon, I am happy to start a new PR to address the defect (as early as today/Friday).
4.  If this plan for merging the PR is faulty,  please let me know ASAP.  I am open to updating with Jp and Jc within this PR -- and hope that the review process occurs quickly without much more conflicting commentary.
5.  Otherwise, I'll leave this PR for now and move along to other work, revisiting if/when there is an easier path forward.  I had hoped this PR was small, helpful, and non-contentious.  Unfortunately, it opened Pandora's box on graphics file formats and frame name conventions -- all which is worthy of discussion.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGPBbCXE7whCJNva5j1:be22cx6)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I'm happy with anything that lets us move on! The time invested in discussing this is way out of proportion with the small change. Paul's plan above sounds fine to me -- we should do that or abandon this PR. It isn't worth any further investment of time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGPJr4v4JBANA3EEkii:b2blfy8)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
@sherm1   As discussed during our Tuesday Dynamic meeting, I added a text file to show how the image file was created.  Other than the text in it, I think this is near ready to merge.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGuiCD3EM_JWmHj84bo:b-mwjxr9)* status: 5 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @EricCousineau-TRI, @mitiguy, and @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961)* status: 9 unresolved discussions, LGTM missing from assignees mitiguy,sherm1(platform) (waiting on @EricCousineau-TRI, @mitiguy, and @sherm1)

___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxpO1WCRIPm_CTZE6w:-MGxpO1XDTm08wsGmCjs:bxydu8k) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L1)):*
> ```vimhelp
> The graphics file BodyParentChildJointCM.png was created by Canvas X (technical illustration program package Canvas X.
> ```

OK Awesome, thanks for documenting this!
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 2 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxprK1AXxqoaTZAzYG:-MGxprK1AXxqoaTZAzYH:bi4mpd2) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L2)):*
> ```vimhelp
> The graphics file BodyParentChildJointCM.png was created by Canvas X (technical illustration program package Canvas X.
> Canvas X is a technical illustration program  has tools for vector object and raster images, and imports more than 72 file formats.
> ```

nit This line is redundant / unnecessary. Readers should refer to the website.

Can you remove this line?
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 3 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxp_vDDuQka8xxYNjG:-MGxp_vDDuQka8xxYNjH:b-3r4n43) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L3)):*
> ```vimhelp
> The graphics file BodyParentChildJointCM.png was created by Canvas X (technical illustration program package Canvas X.
> Canvas X is a technical illustration program  has tools for vector object and raster images, and imports more than 72 file formats.
> Canvas X is available at https://www.canvasgfx.com/en/products/canvas-x/
> ```

nit Can you mention that this is a commercially licensed product?
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxpQiqDTA3wALAUOwN:-MGxpQirAHRU7AxN5WFv:b-bwlxnj) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L4)):*
> ```vimhelp
> Canvas X is a technical illustration program  has tools for vector object and raster images, and imports more than 72 file formats.
> Canvas X is available at https://www.canvasgfx.com/en/products/canvas-x/
> Note: This graphic file can be easily reproduced using other drawing tools (e.g., Adobe Illustrator).
> ```

BTW You may want to mention that we don't store an SVG b/c the conversion process ruins the fonts?
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxpzbEDoY9_1VhhmOv:-MGxpzbEDoY9_1VhhmOw:bc1ajmp) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L4)):*
> ```vimhelp
> Canvas X is a technical illustration program  has tools for vector object and raster images, and imports more than 72 file formats.
> Canvas X is available at https://www.canvasgfx.com/en/products/canvas-x/
> Note: This graphic file can be easily reproduced using other drawing tools (e.g., Adobe Illustrator).
> ```

nit I'm not sure what we gain with this line. Can you remove it?

**Review by sherm1 — COMMENTED** [review]
Thanks for the updates, Paul -- looks great now pending simplifying the .txt files. Platform :lgtm:

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGybJe68aXBhjDrwHLH:b4yak48)* status: 6 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @mitiguy)

___
*[multibody/plant/images/BodyParentChildJoint.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGyaJ7J41ZQsSfBE4PU:-MGyaJ7J41ZQsSfBE4PV:b7a4wq5) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJoint.txt#L4)):*
> ```vimhelp
> Canvas X is a technical illustration program  has tools for vector object and raster images, and imports more than 72 file formats.
> Canvas X is available at https://www.canvasgfx.com/en/products/canvas-x/
> Note: This graphics file can be easily reproduced using other drawing tools (e.g., Adobe Illustrator).
> ```

minor: I think all we need here is just the first sentence. Maybe make it:
`The graphics file BodyParentChildJoint.png was created by Canvas X (a commercial technical illustration program).`
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGyb9X2BDSX-QvpQL26:-MGyb9X2BDSX-QvpQL27:bq1076f) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L4)):*
> ```vimhelp
> Canvas X is a technical illustration program  has tools for vector object and raster images, and imports more than 72 file formats.
> Canvas X is available at https://www.canvasgfx.com/en/products/canvas-x/
> Note: This graphic file can be easily reproduced using other drawing tools (e.g., Adobe Illustrator).
> ```

minor: I think all we need here is just the first sentence. Maybe make it:
`The graphics file BodyParentChildJointCM.png was created by Canvas X (a commercial technical illustration program).`

**Review by mitiguy — COMMENTED** [review]
Changes made to the text files.  Reduced to two sentences with one sentence addressing the choice of PNG vs SVG (per Eric's request).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGyrM9sBzabWguaWy7M:bpzy544)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @EricCousineau-TRI and @sherm1)

___
*[multibody/plant/images/BodyParentChildJoint.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGyaJ7J41ZQsSfBE4PU:-MGyoAhiB1KzGQ9WVjY0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJoint.txt#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think all we need here is just the first sentence. Maybe make it:
`The graphics file BodyParentChildJoint.png was created by Canvas X (a commercial technical illustration program).`
</blockquote></details>

Done.
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxpO1WCRIPm_CTZE6w:-MGyE3ba9ygz2W2YTKGg:bk8i83x) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Awesome, thanks for documenting this!
</blockquote></details>

Thanks Eric -- I think this is a step in the right direction.  Thanks for joining our meeting earlier this week.
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 3 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxp_vDDuQka8xxYNjG:-MGycXef2gHLe2r-HD6l:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you mention that this is a commercially licensed product?
</blockquote></details>

Done. 
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxpQiqDTA3wALAUOwN:-MGyoGMn0f_2htghw61n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW You may want to mention that we don't store an SVG b/c the conversion process ruins the fonts?
</blockquote></details>

Done.
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGxpzbEDoY9_1VhhmOv:-MGyoK0_AEQNmFhu3sAd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I'm not sure what we gain with this line. Can you remove it?
</blockquote></details>

Done.
___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGyb9X2BDSX-QvpQL26:-MGyphHR0rQSQ31TOkcV:b-7b15d4) ([raw file](https://github.com/robotlocomotion/drake/blob/e4361d82ce920a60d4282ee10c41bafb50f70481/multibody/plant/images/BodyParentChildJointCM.txt#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think all we need here is just the first sentence. Maybe make it:
`The graphics file BodyParentChildJointCM.png was created by Canvas X (a commercial technical illustration program).`
</blockquote></details>

Mostly done.  I added the second sentence per Eric's suggestion.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @EricCousineau-TRI and @mitiguy)

___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 3 at r5](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGyvPBO6SwFew3YpQd7:-MGyvPBP-r8XLKkVnQOI:b-m4jeyr) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbca42389459da7597ae2bc5b46d9574569d95b/multibody/plant/images/BodyParentChildJointCM.txt#L3)):*
> ```vimhelp
> The graphics file BodyParentChildJointCM.png was created by Canvas X
> (commercial PC/Windows technical illustration program).  Raster graphics (PNG)
> was chosen over vector graphics (SVG) because it better rendered the fonts.
> ```

nit: final newline missing at end of file

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @EricCousineau-TRI and @mitiguy)

**Review by sherm1 — COMMENTED** [review]
-@mitiguy (for some reason you were assigned as a reviewer of your own PR!)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGz4-Go18_VXH42c_r1:bw55xvf)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI and @mitiguy)

**Review by sherm1 — COMMENTED** [review]
> Dismissed @EricCousineau-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
This is ready to merge -- just needs a squash with a cleaned-up commit message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGz4nSjEAJbHepY4DQj:b-amdl63)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

**Review by mitiguy — COMMENTED** [review]
status: squashing now 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13961#-:-MGz8bc957p_K5CliHrZ:b-ksyq1o)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[multibody/plant/images/BodyParentChildJointCM.txt, line 3 at r5](https://reviewable.io/reviews/robotlocomotion/drake/13961#-MGyvPBO6SwFew3YpQd7:-MGz-JgR9dP1T8v76faQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbca42389459da7597ae2bc5b46d9574569d95b/multibody/plant/images/BodyParentChildJointCM.txt#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: final newline missing at end of file
</blockquote></details>

Done.

**Pull request merged**
