### PR TITLE
Add ZeroOrderHold::DoToSymbolic.

### PR DESCRIPTION
**Pull request by david-german-tri**
Remove spurious and unused support for scalar-type discrete periods.

@jadecastro for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5312)

### CODE REVIEW

**Comment by david-german-tri** [comment]
-@jadecastro +@soonho-tri 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-:-Ke0JrJVheRwPXtPVdC4:b5hmkzb)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-Ke0Qnh3O6SJhAWdjJkG:-Ke0Qnh3O6SJhAWdjJkH:b-m4mbe3) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4391418f4e305984b2c57ce6e2dd52632613db/drake/systems/framework/leaf_system.h#L333)):*
> ```objc
>   /// period_sec thereafter. On the discrete tick, the system may perform
>   /// the given type of action.
>   void DeclarePeriodicAction(const double period_sec, const double offset_sec,
> ```

META : Should I recommend to use `double` instead of `const double`?

Source: http://drake.mit.edu/code_style_guide.html#clarifications

---

*[drake/systems/primitives/zero_order_hold.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-Ke0Q42PozlffvtX1Sdt:-Ke0Q42PozlffvtX1Sdu:bw97mzd) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4391418f4e305984b2c57ce6e2dd52632613db/drake/systems/primitives/zero_order_hold.h#L27)):*
> ```objc
> 
>  protected:
>   // System<T> override.  Returns an ZeroOrderHold<symbolic::Expression> with
> ```

FYI, typo `an` -> `a`?

---

*[drake/systems/primitives/zero_order_hold.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-Ke0Q9XzWtN_V6d3Ir35:-Ke0Q9Y-jRmwgIYikv-j:b-mn6t1v) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4391418f4e305984b2c57ce6e2dd52632613db/drake/systems/primitives/zero_order_hold.h#L47)):*
> ```objc
> 
>  private:
>   const double period_sec_;
> ```

Missing value-initialization `{}` on POD.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-Ke0Qnh3O6SJhAWdjJkG:-Ke0VPBSvQ5NCrHYewSS:bhatwt4) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4391418f4e305984b2c57ce6e2dd52632613db/drake/systems/framework/leaf_system.h#L333)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META : Should I recommend to use `double` instead of `const double`?

Source: http://drake.mit.edu/code_style_guide.html#clarifications
</blockquote></details>

Done.  (Yes, you should!  My mistake.)

---

*[drake/systems/primitives/zero_order_hold.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-Ke0Q42PozlffvtX1Sdt:-Ke0VV0L_TcSMnCVImml:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4391418f4e305984b2c57ce6e2dd52632613db/drake/systems/primitives/zero_order_hold.h#L27)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, typo `an` -> `a`?
</blockquote></details>

Done.

---

*[drake/systems/primitives/zero_order_hold.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-Ke0Q9XzWtN_V6d3Ir35:-Ke0VWSXwtAkN23nw-At:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d4391418f4e305984b2c57ce6e2dd52632613db/drake/systems/primitives/zero_order_hold.h#L47)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Missing value-initialization `{}` on POD.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-:-Ke0WUcTZB7wuWhXUt9n:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@sammy-tri for platform review due to unusual schedule this week

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-:-Ke0WpOO-C9BE-7Nh0aN:b8pzlru)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-:-Ke12C6DZtyv-kR_K7kx:bnfp4nl)*

**Comment by david-german-tri** [comment]
The `linux-clang-experimental-debug` failure is a timeout in a Director test, which is pretty clearly unrelated.  Override-merging.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5312#-:-Ke4gMoRS-MAsa2lt9BI:b-7t6bn2)*

**Pull request merged**
