### PR TITLE
[visualization] Add sliders for geometry alpha in MeshcatVisualizer

### PR DESCRIPTION
**Pull request by trowell-tri**
Adds sliders to control geometry alpha to MeshcatVisualizer, as well as a config option to disable them.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)

### CODE REVIEW

**Review by trowell-tri — COMMENTED** [review]
Completes #17688 (Enhance MeshcatVisualizer to offer collision geometry checkbox)

+(release notes: feature)
Adds the alpha sliders as well as a config flag to enable them (which is on by default).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454#-:-NJGI-tn8NhUBmtZseSM:b6vcvnn)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by trowell-tri — COMMENTED** [review]
FYI @jshep-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454#-:-NJGIESjDSJaVQ2TRjAg:bhiyc4p)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @trowell-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGPZaM7ZHuuCf_LlTk:-NJGPZaM7ZHuuCf_LlTl:b-lc0xim) (no related file):*
lots of exceptions in CI tests re: `RuntimeError: Meshcat already has a slider named <blah>.`

___

**Review by trowell-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGPZaM7ZHuuCf_LlTk:-NJGRnn34RcUFp4MacbT:b-26f7xe) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

lots of exceptions in CI tests re: `RuntimeError: Meshcat already has a slider named <blah>.`
</blockquote></details>

Looking

___

**Review by trowell-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGPZaM7ZHuuCf_LlTk:-NJGXeGB-DdF3Q5EUQEr:beo4jf5) (no related file):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

Looking
</blockquote></details>

That test is noisy for me and admittedly don't run it as often as I should, but I missed those prints. I *think* these errors are artifacts of the way the test suite is built and fixed the issues that way rather than change the underlying code to either look for an existing slider and ignore, or attempt to clear out controls (and I'm not sure when that should happen anyway). Happy to discuss and learn if you have other ideas.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @trowell-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGPZaM7ZHuuCf_LlTk:-NJGhYVO96zPehlOCIf4:b-9my6bq) (no related file):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

That test is noisy for me and admittedly don't run it as often as I should, but I missed those prints. I *think* these errors are artifacts of the way the test suite is built and fixed the issues that way rather than change the underlying code to either look for an existing slider and ignore, or attempt to clear out controls (and I'm not sure when that should happen anyway). Happy to discuss and learn if you have other ideas.
</blockquote></details>

Yeah, the whole name collision thing is gross. I'll see if I have any thoughts on closer fiddling.

___

**Review by trowell-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`geometry/meshcat_visualizer.cc` line 109 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGgX6x3b2-yXSI9UyH:-NJGj6Hf6vEkADNg-Qko:b-qk6wma) ([raw file](https://github.com/robotlocomotion/drake/blob/11156a4e6f75c3ec5ce7a3ae961efd2e0ee52c69/geometry/meshcat_visualizer.cc#L109)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This branch ( and the new function below) are not reached by the unit tests. Should I worry?

coverage measurement:
```
$ bazel test --config kcov //geometry/... //visualization/...
$ ./tools/dynamic_analysis/kcov_tool merge [SOME-NEW-DIRECTORY]
$ see [SOME-NEW-DIRECTORY]/index.html & disown
# click through to the "[merged]" report page, probably use ctrl-f search to find relevant files
```
</blockquote></details>

It's manually testable but I couldn't think of a way to unit test it … and now I see `SetSliderValue`. I should have dug deeper. Lemme try that.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @trowell-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @trowell-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+@xuchenhan-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454#-:-NJGuasA9FqVGuzkTVbA:b-1sceey)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 6 of 6 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454#-:-NJHVkSCCKb4vtc_jh6_:bzus18)* status: 1 unresolved discussion (waiting on @trowell-tri)

___
*[`geometry/meshcat_visualizer.cc` line 207 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGxFks97JGgmM3lD6X:-NJGxFks97JGgmM3lD6Y:b-aoawfu) ([raw file](https://github.com/robotlocomotion/drake/blob/9100478a5a3ec3685982492c3fd715eedcd3905f/geometry/meshcat_visualizer.cc#L207)):*
> ```cpp
>   for (const auto& [geom_id, path] : geometries_) {
>     Rgba color = colors_[geom_id];
>     color.set(color.r(), color.g(), color.b(), alpha_value_ * color.a());
> ```

BTW, this seems like a "alpha_value_multiplier" instead of the actual alpha value of the geometry. Is that true?

For example, if the prescribed alpha of the geometry is already zero, then moving the slider shouldn't have any effect?

Consider clarifying.

**Review by trowell-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`geometry/meshcat_visualizer.cc` line 207 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGxFks97JGgmM3lD6X:-NJHX7wF9HUml0fHOkh3:btckb34) ([raw file](https://github.com/robotlocomotion/drake/blob/9100478a5a3ec3685982492c3fd715eedcd3905f/geometry/meshcat_visualizer.cc#L207)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

That's correct, and if intrinsic alpha is zero then the slider won't change that.

But I'm not sure how to clarify. "<geometry> α multiplier" may not fit into the button width, and Meldis already uses "<geometry> α" so I wanted to match that for the button. Not to mention that sliding the control makes it pretty obvious what is happening. Is there somewhere else or some other way I can clarify?
</blockquote></details>

Whoops, my comment above got mangled by the markdown parser.

The second sentence should be:

 "_channel_ α multiplier" may not fit into the button width, and Meldis already uses "_channel_ α" so I wanted to match that for the button.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18454)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @trowell-tri)

___
*[`geometry/meshcat_visualizer.cc` line 207 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJGxFks97JGgmM3lD6X:-NJHed0QE3T4jtMN1cBD:brgyh93) ([raw file](https://github.com/robotlocomotion/drake/blob/9100478a5a3ec3685982492c3fd715eedcd3905f/geometry/meshcat_visualizer.cc#L207)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

Whoops, my comment above got mangled by the markdown parser.

The second sentence should be:

 "_channel_ α multiplier" may not fit into the button width, and Meldis already uses "_channel_ α" so I wanted to match that for the button.
</blockquote></details>

Hmm, I see. Consistency with Meldis is probably best. Comment retracted.

**Comment by RussTedrake** [comment]
FYI -- this was a breaking change.  (It broke my course notes repositories).  Previously, repeated instantiations of MeshcatVisualizer were fine.  Now they fail with `RuntimeError: Meshcat already has a slider named visualizer α.`

**Comment by RussTedrake** [comment]
Actually, it was covered by tests, but clearly not explicitly enough.  The extra additions that this PR added to the existing tests (setting `params.enable_alpha_sliders=false` and adding a `DeleteAddedControls()`) are evidence of the breaking aspect of the change.

**Comment by RussTedrake** [comment]
*[`geometry/meshcat_visualizer.h` line 232 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18454#-NJKeGri2opsfeb_cmqX:-NJKeGri2opsfeb_cmqY:b-tj602f) ([raw file](https://github.com/robotlocomotion/drake/blob/764b3253e03a7026b0a4b0d1f831075842ab7a85/geometry/meshcat_visualizer.h#L232)):*
> ```objc
> 
>   /* The last alpha value applied to geometry. */
>   mutable double alpha_value_{1.0};
> ```

this should not be mutable.  it should be stored in the Context.

**Comment by trowell-tri** [comment]
> FYI -- this was a breaking change. (It broke my course notes repositories). Previously, repeated instantiations of MeshcatVisualizer against a single meshcat instance, which happens commonly in a jupyter notebook workflow, were fine. Now they fail with `RuntimeError: Meshcat already has a slider named visualizer α.`
> 
> It even broke my "hello world" notebook here: https://deepnote.com/workspace/Manipulation-ac8201a1-470a-4c77-afd0-2cc45bc229ff/project/01-Introduction-6e32ce10-e406-4026-abfb-00be78c478cb/%2Fintro.ipynb. (to be clear, the deepnote version still works because i am pegged to the older revision, but it breaks if i run against this morning nightlies)
> 
> I think we need to repair the old behavior (and add a test covering this workflow!)
> 
> Thankfully, it looks like it did not quite land in time for the v1.11.0 release.

Agreed to repairing the behavior, and I think I understand the new test you want.

I justified the test changes to myself by rationalizing that the tests were doing slightly unusual things, but didn't realize that repeated instantiations of a MeshcatVisualizer against the same Meshcat was a common workflow; my short-term experience led me to believe they'd have different prefixes when that happened.

As a quick repair we could revert, or we could default the sliders to being disabled; either of those should stop the breakage. I'm not sure what the right long-term fix is but am open to suggestions.

I'll take a look at using the Context; I didn't know it had this kind of facility.

**Comment by trowell-tri** [comment]
Another idea I've come up with that would solve this issue would be to change the default prefix name from "visualization" to instead reflect the actual geometry role. Or just turn the alpha sliders off by default, but have `ApplyVisualizationConfig` turn them on, since in some ways this was (I think) meant to be an enhancement to that feature as much as it is to `MeshcatVisualizer`.

I'm minded to do both, since changing the alpha only makes sense when there are multiple overlapping geometries being displayed, and users who add several `MeshcatVisualizer`s to a meshcat can still turn the sliders on if they choose and will then get something more reasonable-looking.

**Comment by rpoyner-tri** [comment]
revert is posted: https://github.com/RobotLocomotion/drake/pull/18463

**Comment by jwnimmer-tri** [comment]
The primary problem is that `MeshcatVisualizer::Delete` should have deleted the sliders it added, solving 95% of the problem.  Once we have that, adding in the checks for "don't accidentally add a duplicated slider" should be easy to get the last 5%.

**Comment by RussTedrake** [comment]
I'm not sure.  I don't think `MeshcatVisualizer::Delete()` gets called very often (and should not). For instance, it is not called from the destructor.  It would be annoying if your robot disappeared out of the visualizer each time the simulation finished (and the `simulator` object fell out of scope).  We want to be able to scrub through recordings, etc after the fact.

I think deleting the slider in the MeshcatVisualizer _destructor_ might be reasonable, and might address many of the concerns.

**Comment by trowell-tri** [comment]
I didn't realize it was common to repeatedly add visualizers with the same prefix — I thought the user would clear things out or use different roles — so that idea won't work. And I didn't see `MeshcatVisualizer::Delete` being used and its comment suggests it was intended for geometry, so I didn't do that. I'll look at the destructor and see how that helps.

Disabling the sliders by default in the `MeshcatVisualizerParams` still seems like a potential improvement to me, and then having `VisualizationConfig` turn them on by default would make the new `ApplyVisualizationConfig` add sliders when it adds both geometries which feels like it gets to the core of this "feature". Am I mistaken or missing something?

**Comment by RussTedrake** [comment]
My preference would be to PR the "off by default" immediately, and revert the changes to the _preexisting_ tests (in cc and in python).  If those all pass without modification, then I think we can avoid the feature revert.

Then we could look at what it would take to turn the feature back on by default in a follow-up PR.  I think removing the slider in the destructor is only good.  If that resolves all of our issues, it might be enough.  I think the existing tests in drake should be strong enough to cover my course notes, but I'm happy to run my course notes bazel against a draft PR when you have it, just in case.

**Pull request merged**
