### PR TITLE
update BUILD files to build and install kuka_plan_runner executable

### PR DESCRIPTION
**Pull request by fbudin69500**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7120)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4KhXbKt1Up5yMkZ0n:beo6w71) (no related file):*
I don't think we should install this as part of `bazel run :install`, at least not without more discussion first about what our default install should contain.  If we want to offer a buried install target that Spartan can opt into in this PR, that's fine by me.

Would changing only the kuka_iiwa_arm/BUILD file be enough for now?

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4LA_ojmPt26V9EcWG:-Kv4LA_ojmPt26V9EcWH:b4t67rp) ([raw file](https://github.com/robotlocomotion/drake/blob/4448d4f9a3b16385067d5f0315bc87859d3d9fd2/drake/examples/kuka_iiwa_arm/BUILD#L177)):*
> ```Python
> )
> 
> install(
> ```

This should have a comment about why we're offering this one-off install target (mentioning Spartan).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by fbudin69500** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4MJTJOl0gynnLRbxL:bme489f) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think we should install this as part of `bazel run :install`, at least not without more discussion first about what our default install should contain.  If we want to offer a buried install target that Spartan can opt into in this PR, that's fine by me.

Would changing only the kuka_iiwa_arm/BUILD file be enough for now?
</blockquote></details>

Yes, I can update this PR to have this install be optional. I just assumed that all the examples would eventually be installed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by manuelli** [comment]
A one-off target would be fine with me. I can use the spartan environment variables to find it.

**Comment by jamiesnape** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4N9HmZUuLoKpCXMUq:b1n3ea6) (no related file):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

Yes, I can update this PR to have this install be optional. I just assumed that all the examples would eventually be installed.
</blockquote></details>

https://github.com/RobotLocomotion/drake/issues/4224

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4NQw4qaKjO6rdc2B_:b-wtm2ju) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

https://github.com/RobotLocomotion/drake/issues/4224
</blockquote></details>

Also https://github.com/RobotLocomotion/drake/issues/1766#issuecomment-259733691, per @RussTedrake, the examples are to be installed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4O6KrDrFzpds8xcBg:bvt5f6q) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Also https://github.com/RobotLocomotion/drake/issues/1766#issuecomment-259733691, per @RussTedrake, the examples are to be installed.
</blockquote></details>

After reviewing these issues, it seems that users are interested in the examples. Should I leave it in the main `:install` or make it optional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4OeKwyV87sai9O3_h:b-95ow8c) (no related file):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

After reviewing these issues, it seems that users are interested in the examples. Should I leave it in the main `:install` or make it optional?
</blockquote></details>

Personally, I don't think we should be going down the road of "optional" installs beyond supporting the two commercial solvers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 5 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4KhXaC5fuuZI4PbfE:-Kv4XAnnpDqgBJJmQe3V:b-f4q77a) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Personally, I don't think we should be going down the road of "optional" installs beyond supporting the two commercial solvers.
</blockquote></details>

So yes, we will want to install some examples.  But it would be a bad idea to install everything that lives under `//drake/examples/...`.  So the questions is what's in and what's out, and how to draw the line.  After reading more background now, I think its clear that this one program would be in.

I'm still a little hesitant to lay the top-level framework for installing examples without having that line drawn, but if you want put this back into the top-level `//:install` rule I withdraw the defect -- if so then perhaps just add a TODO + those issue numbers in `/drake/examples/BUILD` to go figure out what else should be installed.

---

*[tools/install/kuka_plan_runner/kuka_plan_runner.sh, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4YgMfoSROfbW_N-rX:-Kv4YgMfoSROfbW_N-rY:b-pitrep) ([raw file](https://github.com/robotlocomotion/drake/blob/467cabb0d75a5503d1ffafc80b2f9b54c1ec1909/tools/install/kuka_plan_runner/kuka_plan_runner.sh#L7)):*
> ```Shell
> 
> export DRAKE_RESOURCE_ROOT=${prefix}/share/drake
> exec ${prefix}/bin/kuka_plan_runner
> ```

You'll want `"$@"` tacked on the end here, in case it has or ever gains command-line arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by fbudin69500** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4LA_ojmPt26V9EcWG:-Kv4YSOABH_CbXE1iw8I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4448d4f9a3b16385067d5f0315bc87859d3d9fd2/drake/examples/kuka_iiwa_arm/BUILD#L177)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This should have a comment about why we're offering this one-off install target (mentioning Spartan).
</blockquote></details>

Done.

---

*[tools/install/kuka_plan_runner/kuka_plan_runner.sh, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv4YgMfoSROfbW_N-rX:-Kv7Zg8eKjNrxkAzAFpY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/467cabb0d75a5503d1ffafc80b2f9b54c1ec1909/tools/install/kuka_plan_runner/kuka_plan_runner.sh#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You'll want `"$@"` tacked on the end here, in case it has or ever gains command-line arguments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by jwnimmer-tri** [comment]
Platform :lgtm:.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv7eJI5Bcw2dijiGNcy:-Kv7eJI664Da88803sdN:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/e0d41231a14707200aa98472609c13f00d640ce5/drake/examples/kuka_iiwa_arm/BUILD#L9)):*
> ```Python
>     "drake_cc_binary",
>     "drake_cc_googletest",
>     "drake_generate_file",
> ```

Unused?

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 178 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv7ebwGzGfKl_s-C0R-:-Kv7ebwHPa4hOjO-YVcH:bmlpnng) ([raw file](https://github.com/robotlocomotion/drake/blob/e0d41231a14707200aa98472609c13f00d640ce5/drake/examples/kuka_iiwa_arm/BUILD#L178)):*
> ```Python
> )
> 
> filegroup(
> ```

FYI If you end up doing another push, consider adding a TODO here or in the sh file itself, to remove this wrapper once FindResource supports the install directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-:-Kv7embf7HqMsRYfvbRk:b-cxwtpi)*

**Comment by jamiesnape** [comment]
:lgtm: (pending fixing CI)

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-:-Kv7j65Xo1tIjhnV-6C5:bbhswsy)*

**Comment by fbudin69500** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv7eJI5Bcw2dijiGNcy:-Kv7sZLp9HBVVjRXsN4f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0d41231a14707200aa98472609c13f00d640ce5/drake/examples/kuka_iiwa_arm/BUILD#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 178 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7120#-Kv7ebwGzGfKl_s-C0R-:-Kv7sVbt8wV5FX5Xw__C:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/e0d41231a14707200aa98472609c13f00d640ce5/drake/examples/kuka_iiwa_arm/BUILD#L178)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If you end up doing another push, consider adding a TODO here or in the sh file itself, to remove this wrapper once FindResource supports the install directory.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7120)*

**Pull request merged**
