### PR TITLE
add model dependencies to iiwa examples, and add iiwa_world_demo to BUILD

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5223)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for review.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-KdHnDhdfq0y4M3lD4eJ:-KdHnDheB7WKwXQZMSVU:br9r45e) ([raw file](https://github.com/robotlocomotion/drake/blob/103a339fb2c1a796a4ce068b0968cfeb7642c89a/drake/examples/kuka_iiwa_arm/BUILD#L34)):*
> ```Python
>         "iiwa_common.h",
>     ],
>     data = ["//drake/examples/kuka_iiwa_arm:models"],
> ```

These data files don't appear to be referenced by the `iiwa_common` component at all; the component merely provides a hook to load _any_ model.  This `data` line should appear in targets that hard-code the URDF filenames strings, such as `iiwa_world_demo`.

I guess we could choose to list the models here so that they are indirectly inherited everywhere to save having to repeat this elsewhere, but that is weird and I would discourage it -- BUILD files should be boilerplate without magic.  However, if that is the intent, at least it should be commented as such here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-KdHmn3M24lf_a2ir6Wu:-KdHmn3M24lf_a2ir6Wv:b-b5usuv) ([raw file](https://github.com/robotlocomotion/drake/blob/103a339fb2c1a796a4ce068b0968cfeb7642c89a/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L52)):*
> ```Python
>         ":world_sim_tree_builder",
>         "//drake/common",
>         "//drake/examples/kuka_iiwa_arm:iiwa_common",
> ```

This isn't directly used by the `iiwa_world_demo` (only within the implementation of the `world_sim_diagram_factory`) , so I don't think should (or needs to) appear here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-:-KdHp3bGM5GKzwfEjj3W:b-atfqb8)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-KdHnDhdfq0y4M3lD4eJ:-KdHrU6_8UzA9lpNGj_Q:bd3odez) ([raw file](https://github.com/robotlocomotion/drake/blob/103a339fb2c1a796a4ce068b0968cfeb7642c89a/drake/examples/kuka_iiwa_arm/BUILD#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These data files don't appear to be referenced by the `iiwa_common` component at all; the component merely provides a hook to load _any_ model.  This `data` line should appear in targets that hard-code the URDF filenames strings, such as `iiwa_world_demo`.

I guess we could choose to list the models here so that they are indirectly inherited everywhere to save having to repeat this elsewhere, but that is weird and I would discourage it -- BUILD files should be boilerplate without magic.  However, if that is the intent, at least it should be commented as such here.
</blockquote></details>

it's true.  but this entire directory needs some TLC, and it's a matter of how picky we are going to be.  are we ok with the glob in the models target?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5223)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/kuka_iiwa_arm/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-KdHnDhdfq0y4M3lD4eJ:-KdHvVWY-YUcHWICuTfL:b-ww60kz) ([raw file](https://github.com/robotlocomotion/drake/blob/103a339fb2c1a796a4ce068b0968cfeb7642c89a/drake/examples/kuka_iiwa_arm/BUILD#L34)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it's true.  but this entire directory needs some TLC, and it's a matter of how picky we are going to be.  are we ok with the glob in the models target?
</blockquote></details>

I think globbing model is fine (and many examples and tests do it), because unlike source code, the impact on build times should be low.  That seems unrelated to the fact that `iiwa_common.cc` doesn't actually mention _any_ model files, though?

I think within `drake/systems/*` somewhere this `data =` line would not stand, but I'm happy to let the iiwa folks decide how straightforward they want to be in their `BUILD` files to be.  In other words, this line is fine if its preceded by something like:
```
# N.B. iiwa_common doesn't actually use any models, but it is
# the most specific common ancestor of all of the demos that
# do use models, so we've chosen to list the data dependency
# here instead of every individual program.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5223)*

**Comment by RussTedrake** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-KdHnDhdfq0y4M3lD4eJ:-KdINtD4N5gDGmNmW1Jx:bd8xy0n) ([raw file](https://github.com/robotlocomotion/drake/blob/103a339fb2c1a796a4ce068b0968cfeb7642c89a/drake/examples/kuka_iiwa_arm/BUILD#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think globbing model is fine (and many examples and tests do it), because unlike source code, the impact on build times should be low.  That seems unrelated to the fact that `iiwa_common.cc` doesn't actually mention _any_ model files, though?

I think within `drake/systems/*` somewhere this `data =` line would not stand, but I'm happy to let the iiwa folks decide how straightforward they want to be in their `BUILD` files to be.  In other words, this line is fine if its preceded by something like:
```
# N.B. iiwa_common doesn't actually use any models, but it is
# the most specific common ancestor of all of the demos that
# do use models, so we've chosen to list the data dependency
# here instead of every individual program.
```
</blockquote></details>

i've removed this and added it to the specific executables.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-KdHmn3M24lf_a2ir6Wu:-KdINsWq81ryZveWmCsW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/103a339fb2c1a796a4ce068b0968cfeb7642c89a/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This isn't directly used by the `iiwa_world_demo` (only within the implementation of the `world_sim_diagram_factory`) , so I don't think should (or needs to) appear here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5223)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5223#-:-KdITALVlcOFm090OTnx:bnfp4nl)*

**Pull request merged**
