### PR TITLE
Added DrakeJoint::is_fixed() and unit tests.

### PR DESCRIPTION
**Pull request by liangfok**
This PR was broken out of #3103.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3399)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please. Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-:-KRCLJUzoA5Y7zSJGsB2:b-esv3jy)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/joints/DrakeJoint.h, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJdyWHK3lbEeO0xS7k:-KRJdyWHK3lbEeO0xS7l:bhsnvk0) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/DrakeJoint.h#L81)):*
> ```objc
> 
>   /**
>    * Returns whether this joint is fixed.
> ```

"Returns `true` if this joint is a FixedJoint"

---

*[drake/systems/plants/joints/test/joint_test.cc, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJcipcx8l11d6JovAl:-KRJcipcx8l11d6JovAm:b7joie2) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/test/joint_test.cc#L17)):*
> ```cpp
> 
> // Note that in the tests below, "dut" stands for "Device Under Test".
> ```

Why not to use a test fixture here instead so that you can reuse `axis` and constants such as `pitch`? Then in a single fixture test you'd have a bunch of `EXPECT_TRUE/FALSE` for each joint in the fixture, much shorter.

---

*[drake/systems/plants/joints/test/joint_test.cc, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJd3fEaDGBpbDQLLVn:-KRJd3fEaDGBpbDQLLVo:b-ed0p55) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/test/joint_test.cc#L19)):*
> ```cpp
> 
> GTEST_TEST(DrakeJointTests, TestFixedJoint) {
>   FixedJoint dut("foo", Eigen::Isometry3d::Identity());
> ```

`dut` doesn't seem to apply nicely here like say in one of those simple car tests. Why not just joint? or in the case of a fixture test, `fixed_joint`, `helical_joint`, `quat_joint`, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399)*

**Comment by amcastro-tri** [comment]
+@sherm1 for platform please. 

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-:-KRJncujWlOqlXshv6UX:bw7ap5e)*

**Comment by liangfok** [comment]
@amcastro-tri, I addressed your comments. PTAL. Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/joints/DrakeJoint.h, line 81 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJdyWHK3lbEeO0xS7k:-KRJp1Cx5Y-oXZY2cYZl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/DrakeJoint.h#L81)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "Returns `true` if this joint is a FixedJoint"
</details>
Done.

---

*[drake/systems/plants/joints/test/joint_test.cc, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJcipcx8l11d6JovAl:-KRJqqqhmbB0QrFZjjqR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/test/joint_test.cc#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Why not to use a test fixture here instead so that you can reuse `axis` and constants such as `pitch`? Then in a single fixture test you'd have a bunch of `EXPECT_TRUE/FALSE` for each joint in the fixture, much shorter.
</details>
Done.

---

*[drake/systems/plants/joints/test/joint_test.cc, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJd3fEaDGBpbDQLLVn:-KRJyGdl9Iw4TWBnVhPB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/test/joint_test.cc#L19)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> `dut` doesn't seem to apply nicely here like say in one of those simple car tests. Why not just joint? or in the case of a fixture test, `fixed_joint`, `helical_joint`, `quat_joint`, etc.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-:-KRJyKCmpcpTqyEdb3bn:b-rri6ra)*

**Comment by sherm1** [comment]
Platform :lgtm:.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-:-KRKMdb3tI7hIpy9nfYz:b-cxwtpi)*

**Comment by liangfok** [comment]
@sherm1, thanks! Just waiting on @amcastro-tri now.

CI Win32 suffered the known client disconnection flake.

@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
Yet another Win32 "Unexpected termination of the channel" flake.

@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/4489/ and is thus ready for @amcastro-tri's review.

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/joints/DrakeJoint.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJdyWHK3lbEeO0xS7k:-KRUG65IK1OxpvAoJ75C:by9z3lc) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/DrakeJoint.h#L81)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
"Returns `true` if....". Back single quotes for `true`

---

*[drake/systems/plants/joints/test/joint_test.cc, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRUGTH1KEQ-eLtN90Lg:-KRUGTH1KEQ-eLtN90Lh:b-1n7tou) ([raw file](https://github.com/robotlocomotion/drake/blob/128d51b806af84d2e4f49f34c894c14d6e67fc0b/drake/systems/plants/joints/test/joint_test.cc#L31)):*
> ```cpp
>     // Instantiates one of each type of joint.
>     fixed_joint_.reset(
>         new FixedJoint(name, transform_to_parent_body));
> ```

you can do `fixed_joint_ = make_unique<FixedJoint>(...)` and avoid using `new`. Her and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/joints/DrakeJoint.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJdyWHK3lbEeO0xS7k:-KRUHqZDFkGFt5csD60a:b8qqvwh) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/DrakeJoint.h#L81)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "Returns `true` if....". Back single quotes for `true`
</details>
The phrasing clarification was a valid defect (the original was ambiguous).  I think, though, that non-use of fancy doxygen syntax is a "BTW Consider", not a defect -- what rule is it violating to leave off the backticks?  It seems clear enough without them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/joints/DrakeJoint.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJdyWHK3lbEeO0xS7k:-KRUIvcXfRGPMWz9FxC3:b-drf2a) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/DrakeJoint.h#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The phrasing clarification was a valid defect (the original was ambiguous).  I think, though, that non-use of fancy doxygen syntax is a "BTW Consider", not a defect -- what rule is it violating to leave off the backticks?  It seems clear enough without them.
</details>
Done. I agree that this should be a BTW consider.

---

*[drake/systems/plants/joints/test/joint_test.cc, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRUGTH1KEQ-eLtN90Lg:-KRUJPOBTwJMPxCP-6Ts:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/128d51b806af84d2e4f49f34c894c14d6e67fc0b/drake/systems/plants/joints/test/joint_test.cc#L31)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> you can do `fixed_joint_ = make_unique<FixedJoint>(...)` and avoid using `new`. Her and below
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399)*

**Comment by amcastro-tri** [comment]
Excellent. :lgtm_strong: 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/plants/joints/DrakeJoint.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-KRJdyWHK3lbEeO0xS7k:-KRUXMkIgRPBKdNU0D3p:bqs23b5) ([raw file](https://github.com/robotlocomotion/drake/blob/a39597463c6d405e55f48f83dc7e89cef3dec52d/drake/systems/plants/joints/DrakeJoint.h#L81)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I agree that this should be a BTW consider.
</details>
BTW, I didn't put a BTW  but notice I did mark myself satisfied, so same effect I guess though maybe it wasn't obvious to you, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-:-KRUXlgVWfzzyMXfaMvu:baqfhqp)*

**Comment by liangfok** [comment]
@amcastro-tri: Thanks! Now waiting on CI to pass.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3399#-:-KRUZnmfDpDbvbtjlMca:b904tq5)*

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
