### PR TITLE
Add opengl context and X11 dependency for use in render engine gl

### PR DESCRIPTION
**Pull request by tehbelinda**
This has been split up from render-gl-port to keep PR size down

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12862)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@seancurtis-tri for review please

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12862#-M2K_ogg9-FYQ9gQIN2x:-M2KyUg3-Febn8JsmHgB:bfrjtul) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What you're saying makes perfect sense. Perhaps this was the wrong slice to extract from the monster port PR. Either way, an existence proof that this satisfies its need would go a long way.

@bel How about the following. Add the `opengl-context` to this PR and have a test that attempts to instantiate an OpenGL context?
</blockquote></details>

Sure, I'll try that out first, I'd rather that than add back to the monster PR :sweat_smile: 

---

**Comment by tehbelinda** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by tehbelinda** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by tehbelinda** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by tehbelinda** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by tehbelinda** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by tehbelinda** [comment]
+@jwnimmer-tri could you continue platform review now that CI is resolved? (with the new unprovisioned build)

**Comment by jwnimmer-tri** [comment]
Will do.

**Comment by jwnimmer-tri** [comment]
I will still start review, but before I platform-approve this is looks to me like it still needs feature review as well -- I think the revision that @SeanCurtis-TRI badged was eons ago and there is a lot more code now?

**Comment by tehbelinda** [comment]
(it's probably easiest to look at this across all revisions and ignore the glut/glew stuff in the middle)

**Comment by jamiesnape** [comment]
Can we close #12936?

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_context.cc, line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12862#-M3Lk1zR04_BW8Y195fI:-M3NP-nU-qFFN_XNZtxa:btjfrjg) ([raw file](https://github.com/robotlocomotion/drake/blob/f25d59fda484a05d41186cb68f13df3d4663b5c5/geometry/render/gl_renderer/opengl_context.cc#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I feel that anyone who plays with OpenGl for a living would know about the architectural review board. I'd definitely advocate a link so that other drake developers have a springboard to learn about the byzantine ways of OpenGl.

And, similarly, `GLX` -> `Glx` for the same style guide.
</blockquote></details>

I was thinking of keeping `GL` both uppercase, since many of the types from GL come that way, e.g. `GLuint`, `GLenum`, etc. Given that, does `GLx` look okay to you? I'm not too fussed about the `x` but I think keeping `GL` consistent would be nice

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_context.cc, line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12862#-M3Lk1zR04_BW8Y195fI:-M3NPZibEV6zY4M0r0Aw:b-7nauh5) ([raw file](https://github.com/robotlocomotion/drake/blob/f25d59fda484a05d41186cb68f13df3d4663b5c5/geometry/render/gl_renderer/opengl_context.cc#L27)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

I was thinking of keeping `GL` both uppercase, since many of the types from GL come that way, e.g. `GLuint`, `GLenum`, etc. Given that, does `GLx` look okay to you? I'm not too fussed about the `x` but I think keeping `GL` consistent would be nice
</blockquote></details>

Similarly all the `...ARB` functions from the GL library are like that, e.g. `glXGetProcAddressARB`. I guess if we're going to change that, then we should also change GL->Gl for consistency in our own naming and ignore how the library functions are named.
I would still suggest we at least go with `GlX` since the `gl` and `X` are treated separately

**Comment by tehbelinda** [comment]
___
*[tools/workspace/x11/repository.bzl, line 16 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12862#-M3MmEOVBcmWZ8BxUaTh:-M3NfN_48LWdQWRDrss4:bhf8xmz) ([raw file](https://github.com/robotlocomotion/drake/blob/f25d59fda484a05d41186cb68f13df3d4663b5c5/tools/workspace/x11/repository.bzl#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Preference for `os_result.error is not None` to avoid any potential collision with overloading `__ne__()`?
</blockquote></details>

apparently `is` is not supported!
```
ERROR: /home/belindateh/drake/tools/workspace/x11/repository.bzl:16:24: 'is' not supported, use '==' instead
ERROR: /home/belindateh/drake/tools/workspace/x11/repository.bzl:16:24: syntax error at 'is': expected :
ERROR: /home/belindateh/drake/tools/workspace/x11/repository.bzl:26:9: Trailing comma is allowed only in parenthesized tuples.
ERROR: /home/belindateh/drake/tools/workspace/x11/repository.bzl:32:5: Trailing comma is allowed only in parenthesized tuples.
ERROR: /home/belindateh/drake/tools/workspace/x11/repository.bzl:35:1: Trailing comma is allowed only in parenthesized tuples.
```

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_includes.h, line 4 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12862#-M3Ml8Br6kBufq7QSPm4:-M3OFJVWBRHwPnKfgCfG:b-qs49kz) ([raw file](https://github.com/robotlocomotion/drake/blob/f25d59fda484a05d41186cb68f13df3d4663b5c5/geometry/render/gl_renderer/opengl_includes.h#L4)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm still balking at the language. It doesn't "distinguish" because there's only a single set of data. There's no "either/or". It's just one blob of includes. How about:

> By design, this includes only the baseline OpenGl headers. If code requires more elaborate libraries, it is responsible for pulling them in directly.

That said, I'm going to mark myself satisfied and leave it up to you. All of this is dancing around "We're not including glx.h here because we want to keep it isolated."
</blockquote></details>

I think the other aspect of this is the ordering - e.g. GL/gl.h has to be first

**Comment by tehbelinda** [comment]
___
*[geometry/render/gl_renderer/opengl_context.h, line 30 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12862#-M3M_t0v7RudolTV2Apo:-M3OFowM89FoNzjpKdMj:bnbt3gu) ([raw file](https://github.com/robotlocomotion/drake/blob/f25d59fda484a05d41186cb68f13df3d4663b5c5/geometry/render/gl_renderer/opengl_context.h#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

At the very least, we should communicate if it's due to the user misusing the API or if it's beyond the scope of the program.

https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXMakeCurrent.xml

This suggests that misuse of the API is possible under several conditions:
  - The context is made current in multiple contexts simultaneously.
  - If we attempt to call this inside a `glBegin()` `glEnd()` block.
  - If the state is `GLX_FEEDBACK` or `GLX_SELECT` (I'm not sure about this; I know `GL_SELECT` and `GL_FEEDBACK` but am unsure of what the `GLX` variant is -- just aliases perhaps?
  - The current context has GL commands that cannot be flushed because the old context's drawable has been destroyed. This seems highly unlikely as our display has static storage duration.

Things beyond control:
  - We run out of resources.

There are a surprising number of ways for a user to mess this up. Even if not overly likely.

Thoughts?
</blockquote></details>

Would it be simpler to just link to https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXMakeCurrent.xml?

**Comment by jwnimmer-tri** [comment]
`[7:59:54 PM]  abort: Failure at geometry/render/gl_renderer/opengl_context.cc:82 in Impl(): condition 'fb_count == 1' failed.` ;)

**Comment by tehbelinda** [comment]
I guess there can be more than one! 
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXChooseFBConfig.xml

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Pull request merged**
