### PR TITLE
[geometry] Add MakeDeformableMesh

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@damrongguoy for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998#-:-N03B67h25_u1Qn41GO2:b3ljvfd)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with unblocking comments and questions.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998#-:-N07_Jgo1gmxT22BTZIJ:b-wqqrch)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07VolK33wVi85mp4Wh:-N07VolLAzvkHxiK_UM0:b-7q9hjo) (no related file):*
The contents of the files look good to me; however, I wonder why they are in the directory `drake/geometry` instead of `drake/geometry/proximity`?

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07WblMAAnD8iQI7QOz:-N07WblMAAnD8iQI7QP-:b3dv9oo) (no related file):*
I have naming questions.  The name of the function `MakeDeformableMesh()` sounds to me like it would return something like a [DeformableGeometry](https://github.com/RobotLocomotion/drake/blob/6ff4c9630bf90f2b1eb5f67c32c08fcacb9a4293/geometry/proximity/deformable_contact_geometries.h#L83) or a [DeformableVolumeMesh](https://github.com/RobotLocomotion/drake/blob/6ff4c9630bf90f2b1eb5f67c32c08fcacb9a4293/geometry/proximity/deformable_volume_mesh.h#L23). Actually it returns a `VolumeMesh` that can be used to create a `DeformableGeometry` or a `DeformableVolumeMesh`.

I wonder whether an alternative name `MakeMeshForDeformable()` would sound better? Or does it sound the same to you?

---
___
*[geometry/make_deformable_mesh.h, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07OAg09KE7GAzaBv_T:-N07OAg09KE7GAzaBv_U:b-eh9m68) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.h#L3)):*
> ```objc
> #pragma once
> 
> #include <memory>
> ```

Unused `#include <memory>`?
___
*[geometry/make_deformable_mesh.h, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07OiyAEf0SCYSZ90YV:-N07OiyAEf0SCYSZ90YW:b-m6zqy5) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.h#L16)):*
> ```objc
>  seperate function for each concrete shape derived from Shape.
>  @pre resolution_hint > 0.
>  @throws std::exception if `shape` doesn't support a mesh discretization. */
> ```

Optional.

This doc applies to all the 9 overloads of `MakeDormableMesh()` below. Should we do grouping (`//@{ ... //@}`); something like this?
```C++
/*
 @anchor MakeDeformableMesh
 @name    Make meshes for deformables.

 Returns a volume mesh suitable for deformable body simulation that
 discretizes the shape with the resolution provided at construction. There is a
 seperate function for each concrete shape derived from Shape.
 @pre resolution_hint > 0.
 @throws std::exception if `shape` doesn't support a mesh discretization.  */
//@{
```
Then, 18 lines below we close the group with:
```C++
//@}
```

On the other hand, this is `internal`, so it won't go to Doxygen, and we can't tell how it will look. That's why this request is optional.
___
*[geometry/make_deformable_mesh.cc, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07S50b5okpYvlM3MFC:-N07S50b5okpYvlM3MFD:b-op9qj3) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.cc#L3)):*
> ```cpp
> #include "drake/geometry/make_deformable_mesh.h"
> 
> #include <utility>
> ```

Unused `#include <utility>` ?
___
*[geometry/make_deformable_mesh.cc, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07Rq288o7m4B_eZJCI:-N07Rq288o7m4B_eZJCJ:b-rk93z5) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.cc#L5)):*
> ```cpp
> #include <utility>
> 
> #include "drake/geometry/proximity/make_sphere_mesh.h"
> ```

Optional.  `#include "drake/common/drake_assert.h` for DRAKE_DEMAND ?
```
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07VolK33wVi85mp4Wh:-N07qTorC7FCe2ugp3aR:biacqan) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

The contents of the files look good to me; however, I wonder why they are in the directory `drake/geometry` instead of `drake/geometry/proximity`?
</blockquote></details>

My reasoning is that these meshes are going to be used for more than proximity purposes (i.e. they live in GeometryState instead of ProximityEngine). I could be convinced otherwise if there's a prevailing convention.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07WblMAAnD8iQI7QOz:-N07rjrC3AVKMonvdLtQ:b-dtkds3) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I have naming questions.  The name of the function `MakeDeformableMesh()` sounds to me like it would return something like a [DeformableGeometry](https://github.com/RobotLocomotion/drake/blob/6ff4c9630bf90f2b1eb5f67c32c08fcacb9a4293/geometry/proximity/deformable_contact_geometries.h#L83) or a [DeformableVolumeMesh](https://github.com/RobotLocomotion/drake/blob/6ff4c9630bf90f2b1eb5f67c32c08fcacb9a4293/geometry/proximity/deformable_volume_mesh.h#L23). Actually it returns a `VolumeMesh` that can be used to create a `DeformableGeometry` or a `DeformableVolumeMesh`.

I wonder whether an alternative name `MakeMeshForDeformable()` would sound better? Or does it sound the same to you?
</blockquote></details>

Done, thanks!

---
___
*[geometry/make_deformable_mesh.h, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07OAg09KE7GAzaBv_T:-N07rOvS8RxoKCNqMzvm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.h#L3)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Unused `#include <memory>`?
</blockquote></details>

Done.
___
*[geometry/make_deformable_mesh.h, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07OiyAEf0SCYSZ90YV:-N07r5kw4TNS0A88jk9m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.h#L16)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.

This doc applies to all the 9 overloads of `MakeDormableMesh()` below. Should we do grouping (`//@{ ... //@}`); something like this?
```C++
/*
 @anchor MakeDeformableMesh
 @name    Make meshes for deformables.

 Returns a volume mesh suitable for deformable body simulation that
 discretizes the shape with the resolution provided at construction. There is a
 seperate function for each concrete shape derived from Shape.
 @pre resolution_hint > 0.
 @throws std::exception if `shape` doesn't support a mesh discretization.  */
//@{
```
Then, 18 lines below we close the group with:
```C++
//@}
```

On the other hand, this is `internal`, so it won't go to Doxygen, and we can't tell how it will look. That's why this request is optional.

</blockquote></details>

Done.
___
*[geometry/make_deformable_mesh.cc, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07S50b5okpYvlM3MFC:-N07rPy9E9xl-yDadjrD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.cc#L3)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Unused `#include <utility>` ?
</blockquote></details>

Done.
___
*[geometry/make_deformable_mesh.cc, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16998#-N07Rq288o7m4B_eZJCI:-N07riKA2ucpX9TyyIJL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11286f2d15283ac1e3260d899f12cd23686dc6b1/geometry/make_deformable_mesh.cc#L5)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Optional.  `#include "drake/common/drake_assert.h` for DRAKE_DEMAND ?
```
```

</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review per rotation please, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998#-:-N083YwY8XrL1ar4MLE7:bgesp2r)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16998#-:-N0C6XJb8Lff3lGw2sw6:b-vtj4w1)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),DamrongGuoy (waiting on @xuchenhan-tri)

**Pull request merged**
