### PR TITLE
Update Mac install instructions for removed dependencies and Homebrew changes

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6609)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review.

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/mac.rst, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6609#-KpW4jTMooYEnfAWxZGM:-KpW4jTMooYEnfAWxZGN:bgp1nwv) ([raw file](https://github.com/robotlocomotion/drake/blob/968147587be4c3007958170899c22326d685a189/drake/doc/mac.rst#L40)):*
> ```reStructuredText
>        gcc \
>        glib \
>        libpng \
> ```

BTW, does `graphviz` not required to generate doxygen? (i.e. skipping call-graph generation if graphviz is not available?)

---

*[drake/doc/mac.rst, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6609#-KpW4Zmt8Yz2h-qoO2O5:-KpW4Zmt8Yz2h-qoO2O6:b-ggmjjb) ([raw file](https://github.com/robotlocomotion/drake/blob/968147587be4c3007958170899c22326d685a189/drake/doc/mac.rst#L54)):*
> ```reStructuredText
> in C++ code. Valgrind is available from Homebrew with ``brew install valgrind``,
> but homebrew may encounter problems when installing ``valgrind`` on macOS 10.12
> (Sierra) or higher. See `this issue <https://github.com/Homebrew/homebrew-core/issues/4841#issuecomment-254217338>`_
> ```

FYI, `valgrind` is available in macOS 10.12. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6609)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/mac.rst, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6609#-KpW4jTMooYEnfAWxZGM:-KpW6qGraKghPhYk2Ar_:bxwrqcq) ([raw file](https://github.com/robotlocomotion/drake/blob/968147587be4c3007958170899c22326d685a189/drake/doc/mac.rst#L40)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, does `graphviz` not required to generate doxygen? (i.e. skipping call-graph generation if graphviz is not available?)
</blockquote></details>

You would also need to build `doxygen --with-graphviz`, which would not use the bottle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6609)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/mac.rst, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6609#-KpW4jTMooYEnfAWxZGM:-KpW79ECQeVaqgCswlp_:b-avps6k) ([raw file](https://github.com/robotlocomotion/drake/blob/968147587be4c3007958170899c22326d685a189/drake/doc/mac.rst#L40)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You would also need to build `doxygen --with-graphviz`, which would not use the bottle.
</blockquote></details>

I see. I'm fine as long as it doesn't complain about missing `dot`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6609)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6609#-:-KpW9e6OA8avHsK4Iren:bnfp4nl)*

**Pull request merged**
