### PR TITLE
Add relational operators overloading for symbolic matrices

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue: https://github.com/RobotLocomotion/drake/issues/5650, https://github.com/RobotLocomotion/drake/issues/5645.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5692)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-:-KgbiJUYZ6CqO9TArIPR:b-utjvo1)*

**Comment by soonho-tri** [comment]
Please note that I simply moved array-testing functions from `symbolic_expression_matrix_test.cc` to `symbolic_expression_array_test.cc`. No real changes there.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-:-KgbiMw-semYKBaD0OWm:bj1dh16)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review please.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 769 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgecM35hoEzE5Q3R9J1:-KgecM35hoEzE5Q3R9J2:bpvcait) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L769)):*
> ```objc
> /// -----------------+----------------+--------------+-------------
> /// | EM<double>     | Formula        | Formula      | bool       |
> /// +-------------------------------------------------------------+
> ```

Super clear documentation! Thanks

---

*[drake/common/symbolic_formula.h, line 796 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgegXMhPJcU_vAKfiBt:-KgegXMhPJcU_vAKfiBu:boqti9b) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L796)):*
> ```objc
> /// matrices @p m1 and @p m2 using less-than (<) operator.
> ///
> /// The following table describes the return type of @p m1 != @p m2.
> ```

change `!=` to `<`?

---

*[drake/common/symbolic_formula.h, line 827 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgehJwwsmE5-VxwXw94:-KgehJwwsmE5-VxwXw95:boqti9b) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L827)):*
> ```objc
> /// matrices @p m1 and @p m2 using less-than-or-equal operator (<=).
> ///
> /// The following table describes the return type of @p m1 != @p m2.
> ```

change `!=` to `<`?

---

*[drake/common/symbolic_formula.h, line 858 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgehUmXul6mBu1gYLGk:-KgehUmXul6mBu1gYLGl:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L858)):*
> ```objc
> /// matrices @p m1 and @p m2 using greater-than operator (>).
> ///
> /// The following table describes the return type of @p m1 != @p m2.
> ```

Ditto

---

*[drake/common/symbolic_formula.h, line 889 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgehbXsq8LLr5l1lyOf:-KgehbXsq8LLr5l1lyOg:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L889)):*
> ```objc
> /// matrices @p m1 and @p m2 using greater-than-or-equal operator (>=).
> ///
> /// The following table describes the return type of @p m1 != @p m2.
> ```

Ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-:-Kgehx40PBU5UZSSh9Ba:b-os5xp3)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 769 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgecM35hoEzE5Q3R9J1:-KgesS4oXHnq-3cg0TLi:b-6ki3tm) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L769)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Super clear documentation! Thanks
</blockquote></details>

BTW, this table and the other tables in this file do not render well in Doxygen:



Consider surrounding it with `<pre>...</pre>` or using Markdown or HTML syntax:

https://www.stack.nl/~dimitri/doxygen/manual/tables.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692)*

**Comment by jwnimmer-tri** [comment]
> Please note that I simply moved array-testing functions from symbolic_expression_matrix_test.cc to symbolic_expression_array_test.cc. No real changes there.

Could you please submit this non-functional change (code move) as a separate PR now, first?  Blending the two together makes it difficult to do a thorough review on either half.  You can tag me for all review on it, and then once its merged rebase this atop it.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-:-KgfGSbK1wMj0yvcDqmk:b-budsru)*

**Comment by soonho-tri** [comment]
I'll rebase it when https://reviewable.io/reviews/robotlocomotion/drake/5696#- is merged.

---

Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 769 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgecM35hoEzE5Q3R9J1:-KgfNrcUI_6KVUtQXsE4:bdkh7b2) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L769)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this table and the other tables in this file do not render well in Doxygen:



Consider surrounding it with `<pre>...</pre>` or using Markdown or HTML syntax:

https://www.stack.nl/~dimitri/doxygen/manual/tables.html
</blockquote></details>

Fixed.



---

*[drake/common/symbolic_formula.h, line 796 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgegXMhPJcU_vAKfiBt:-KgfAFK5YvRdje0kFb2E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L796)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

change `!=` to `<`?
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula.h, line 827 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgehJwwsmE5-VxwXw94:-KgfAFzGexCjvtpije-t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L827)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

change `!=` to `<`?
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula.h, line 858 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgehUmXul6mBu1gYLGk:-KgfAGahXKjRgOy6l8t3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L858)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

---

*[drake/common/symbolic_formula.h, line 889 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-KgehbXsq8LLr5l1lyOf:-KgfAHDX_UqXfQRvZV4_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eeec87f117ba89795bbecb06da717b462e12f127/drake/common/symbolic_formula.h#L889)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-:-KgfNvuXaQ9mzbp5xPN6:b-hualjy)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5692#-:-KgflUOT98iQq5J-d28r:bnfp4nl)*

**Pull request merged**
