### PR TITLE
[cmake] Set same bazel minimum version as WORKSPACE

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18637)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
Extracted from https://github.com/RobotLocomotion/drake/pull/18545#pullrequestreview-1265735435

+@jwnimmer-tri for feature review please.  If you build with 5.3.0 on mac you get crazy errors:

```
ERROR: /Users/stephen.mcdowell/Desktop/drake/lcmtypes/BUILD.bazel:75:21: Action lcmtypes/drake/lcmt_call_python.hpp failed: (Aborted): lcm-gen failed: error executing command bazel-out/host/bin/external/lcm/lcm-gen --cpp --use-quotes-for-includes '--cpp-std=c++11' '--cpp-hpath=bazel-out/darwin_arm64-opt/bin/lcmtypes' lcmtypes/lcmt_call_python.lcm ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
dyld[33891]: Library not loaded: 'bazel-out/host/bin/external/lcm/libdrake_lcm.so'
  Referenced from: '/private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/host/bin/external/lcm/lcm-gen'
  Reason: tried: 'bazel-out/host/bin/external/lcm/libdrake_lcm.so' (no such file), '/usr/local/lib/libdrake_lcm.so' (no such file), '/usr/lib/libdrake_lcm.so' (no such file), '/private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/sandbox/darwin-sandbox/21/execroot/drake/bazel-out/host/bin/external/lcm/libdrake_lcm.so' (no such file), '/usr/local/lib/libdrake_lcm.so' (no such file), '/usr/lib/libdrake_lcm.so' (no such file)
ERROR: /Users/stephen.mcdowell/Desktop/drake/lcmtypes/BUILD.bazel:84:21: Action lcmtypes/drake/lcmt_contact_results_for_viz.hpp failed: (Aborted): lcm-gen failed: error executing command bazel-out/host/bin/external/lcm/lcm-gen --cpp --use-quotes-for-includes '--cpp-std=c++11' '--cpp-hpath=bazel-out/darwin_arm64-opt/bin/lcmtypes' lcmtypes/lcmt_contact_results_for_viz.lcm
```

This stumped us for a little while until we realized we were re-checking against 5.3.0 and should have been doing 5.3.1.

If this isn't enough to warrant bumping the versions changed here then I'll just set to 4.0 in a new commit to unify them and be done with it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18637#-:-NMUCShW2kq0BTCKpMtY:b-mg4rh3)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Is that just a bug in bazel 5.3.0, though, that was fixed in the patch revision?  Do 5.2.0 and/or 5.4.0 still work?

**Review by svenevs — COMMENTED** [review]
5.2.0 works it seems.  Changed the PR to just unify the CMakeLists.txt and WORKSPACE.  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18637#-:-NMUElJe3LTAB3I4SIdD:b4qld28)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18637)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @svenevs)

**Comment by jwnimmer-tri** [comment]
FYI upon merge, I updated the commit title to be more release-note worthy.

**Pull request merged**
