### PR TITLE
[primitives] Add (optional) gradients to MultilayerPerceptron::BatchOutput

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16572)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
PTAL.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16572#-:-Mvag5sT0SFwvUNwORKG:b-83330m)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.h, line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16572#-MvabzLP-SFKDIUQmrIM:-MvabzLQA2J2p9veQsg4:beljde0) ([raw file](https://github.com/robotlocomotion/drake/blob/8879bfe255a885e50d9be062a72a63d44d8c60cd/systems/primitives/multilayer_perceptron.h#L219)):*
> ```objc
>    nullptr`, then `dYdX` is populated with the batch gradients of the scalar
>    output `Y` relative to the input `X`: the (i,j)th element represents the
>    gradient dY(0,j) / dX(i,j).
> ```

If the output layer has size more than 1 and dYdx != nullptr, will the code throw an error? By reading the implementation, `dYdX` is not changed in that case. I suggest we document this behavior.
___
*[systems/primitives/multilayer_perceptron.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16572#-Mvaf-Hg8u4nqx-OB_4X:-Mvaf-Hg8u4nqx-OB_4Y:bohamsy) ([raw file](https://github.com/robotlocomotion/drake/blob/8879bfe255a885e50d9be062a72a63d44d8c60cd/systems/primitives/multilayer_perceptron.cc#L54)):*
> ```cpp
>         Wx_plus_b(n),
>         Xn(n),
>         dXn(n),
> ```

I am not sure if `dXn` is a very good name, all other gradient variable name has `dOutput_dInput` structure. I think here we mean dXn_dWx_plus_b? If this name is too long, maybe we could call it dActivation? Since the activation function input/output is very clear we probably can ignore the input/output name.
___
*[systems/primitives/multilayer_perceptron.cc, line 356 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16572#-MvacpUf15u1EcXJIJvS:-MvacpUf15u1EcXJIJvT:b-q9rj2r) ([raw file](https://github.com/robotlocomotion/drake/blob/8879bfe255a885e50d9be062a72a63d44d8c60cd/systems/primitives/multilayer_perceptron.cc#L356)):*
> ```cpp
>   DRAKE_DEMAND(Y->rows() == layers_[num_weights_]);
>   DRAKE_DEMAND(Y->cols() == X.cols());
>   bool gradients = layers_[num_weights_] == 1 && dYdX != nullptr;
> ```

nit. const bool

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16572)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[systems/primitives/multilayer_perceptron.h, line 219 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16572#-MvabzLP-SFKDIUQmrIM:-MvhODPL7nLf0q_K0tGi:b-gska0p) ([raw file](https://github.com/robotlocomotion/drake/blob/8879bfe255a885e50d9be062a72a63d44d8c60cd/systems/primitives/multilayer_perceptron.h#L219)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If the output layer has size more than 1 and dYdx != nullptr, will the code throw an error? By reading the implementation, `dYdX` is not changed in that case. I suggest we document this behavior.
</blockquote></details>

Done. You're right.  I think it's better to throw an error in this case.  I've changed (and documented) that behavior.
___
*[systems/primitives/multilayer_perceptron.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16572#-Mvaf-Hg8u4nqx-OB_4X:-MvhOaoC135qHzhaSRLO:bkiyft9) ([raw file](https://github.com/robotlocomotion/drake/blob/8879bfe255a885e50d9be062a72a63d44d8c60cd/systems/primitives/multilayer_perceptron.cc#L54)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure if `dXn` is a very good name, all other gradient variable name has `dOutput_dInput` structure. I think here we mean dXn_dWx_plus_b? If this name is too long, maybe we could call it dActivation? Since the activation function input/output is very clear we probably can ignore the input/output name.
</blockquote></details>

Done.  You're right.  I should spell it out even though it's verbose.
___
*[systems/primitives/multilayer_perceptron.cc, line 356 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16572#-MvacpUf15u1EcXJIJvS:-MvhOeM07OR3EgLDndYj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8879bfe255a885e50d9be062a72a63d44d8c60cd/systems/primitives/multilayer_perceptron.cc#L356)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit. const bool
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16572#-:-MvieVXICz_LFq36GQ94:b-vtj4vo)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai (waiting on @hongkai-dai and @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.h, line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16572#-MvifcbpCbAPkb5EaoBU:-Mvifcbq3GP-i26UZZZB:b-ndyvah) ([raw file](https://github.com/robotlocomotion/drake/blob/2e068e4910d28f3a50f56bc6cde648a32f33fbe8/systems/primitives/multilayer_perceptron.h#L22)):*
> ```objc
> 
> template <typename T>
> struct CalcLayersData;
> ```

FYI When I first reviewed this PR, I was about to suggest moving this back inside the system as a forward-declared, nested class, which is valid C++.  Then, I remembered that the TypeHasher from AbstractValue will yell a warning into the console if we do that.

I wonder if we should have a comment here (or in the cc file) reminding future reader of that hazard?  I kind of hate to spam a comment like that in every System class that uses intermediate cache entries, but on the other hand, I _did_ forget when reading this time.
___
*[systems/primitives/multilayer_perceptron.cc, line 358 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16572#-Mvic4F22bGAA-hdq2YU:-Mvic4F37aELdiwgzKUa:b-7ilvfu) ([raw file](https://github.com/robotlocomotion/drake/blob/2e068e4910d28f3a50f56bc6cde648a32f33fbe8/systems/primitives/multilayer_perceptron.cc#L358)):*
> ```cpp
>   if (gradients && layers_[num_weights_] != 1) {
>     throw std::logic_error(
>         "BatchOutput: dYdX != nullptr, but BatchOutput only support gradients "
> ```

typo?



_Suggestion:_
```cpp
supports
```
___
*[bindings/pydrake/systems/test/primitives_test.py, line 576 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16572#-MvieEVNCr4xZO0yUgsa:-MvieEVNCr4xZO0yUgsb:b5e4bue) ([raw file](https://github.com/robotlocomotion/drake/blob/2e068e4910d28f3a50f56bc6cde648a32f33fbe8/bindings/pydrake/systems/test/primitives_test.py#L576)):*
> ```Python
>         self.assertEqual(mlp2.activation_type(1),
>                          PerceptronActivationType.kTanh)
>         Y = np.asfortranarray(np.zeros((1, 3)))
> ```

By initializing Y to zeros here, the assertion below that Y is still zero after the call isn't really testing the matrix plumbing in the bindings.  The call could be ignoring `Y` and we'd never notice.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16572#-:-MvigTWH2T2LP4EdyL1k:bg7igkv)* status: 2 unresolved discussions (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16572)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
