### PR TITLE
Removing global_inverse_kinematics_feasible_posture_test From ASan

### PR DESCRIPTION
**Pull request by m-chaturvedi**
[Failing Build](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-bazel-continuous-memcheck-asan-everything/311/)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7211)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please

**Comment by jwnimmer-tri** [comment]
:lgtm: feature and platform.

FYI I suspect `buildifier` lint is going to complain at you.  (As long as CI is happy, I'm happy, though.)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7211#-:-KvnGDTasDDEUJxIAw2s:b-mlvk18)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7211)*

**Pull request merged**
