### PR TITLE
[geometry] Make soft half space/rigid mesh hydroelastic differentiable

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This work is about 5% tweaking the implementation and 95% testing.

1. Modifications to the underlying algorithm
   - making sure use of scalars is consistent.
   - Guaranteeing that even with `T = AutoDiffXd`, BVH usage still works.
   - deleting the "AutoDiff throws" implementation.
2. Modifications to unit tests
   - Incidental renaming of test fixture to to `...ValueTest` to have a clearer relationship to the new test.
   - Elimination of "Autodiff throws" unit test.
   - Introduction of tests on the derivatives of various quantities:
     - Area, vertex position, normal direction, pressure.

relates #14136

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14998)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
This is a redux of  #14943. There was an asan and mac problem post merge. Due to platform review duties and some extra noise in the mac builds, I opted to simply revert that PR (#14995). This brings it back with some simple patches.

Revision 1 is the original PR approved in #14943. Revision 2 contains the patches. They've been separated for your reviewing convenience.

+@sherm1 for both reviews.
+(status: single reviewer ok) 
cc @hongkai-dai 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14998#-:-MZoLUv_5lprsipvPmVW:byxq8k0)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Update -- sorry, due to user error, revisions 2 __*and 3*__ contain the small updates.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14998#-:-MZoMKFn7tkBvLayb2p4:bvd4llt)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14998#-:-MZoVTKJEX7N11WUSvTe:b4xzgsb)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14998#-:-MZrQoCY0WBz4aU38ktC:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
