### PR TITLE
Removed the superfluous l-value generator

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
In solving another SFINAE problem, I realized that these tests are overly complex in their structure. We've introduced the `GenerateLValue` struct that isn't actually necessary; `std::declval` provides all the functionality we need.

1) In two cases (index and identifier tests) r-values are fine (`declval<T>()` has type `T&&`).
2) In the inertia tests, we do require l-values, becase we're doing in-place operations (e.g., `*=`). However, `declval<T&>()` has type `T& &&` which collapses to `T&`.  In short, the rvalue reference of an lvalue reference *is* an lvalue reference.  

So, we simplify the voodoo using fewer arbitrary constructs and rely more directly on built-in C++ functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5749)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@sherm1 for feature review, +@david-german-tri for platform review.  Thanks in advance.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-:-Kh33lU6n7y8XoStWVRw:bl92t81)*

**Comment by sherm1** [comment]
This is great -- thanks, Sean! A few minor BTWs and an :lgtm:.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/type_safe_index_test.cc, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-Kh39uwCNtQtgvM5m3Zy:-Kh39uwCNtQtgvM5m3Zz:bus9etl) ([raw file](https://github.com/robotlocomotion/drake/blob/240ff2dc3a8359a9d774769edd57e2a77b9a2a69/drake/common/test/type_safe_index_test.cc#L208)):*
> ```cpp
> #define BINARY_TEST(OP, OP_NAME) \
> template <typename T, typename U, \
>     typename = decltype(std::declval<T>() OP std::declval<U>())> \
> ```

BTW, `std::declval` is in header `<utility>` which is not explicitly included above. (Probably getting sucked in by something else but better not to depend on that.)

---

*[drake/geometry/test/identifier_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-Kh3Ax6wxJ7QJJ6Y8usP:-Kh3Ax6wxJ7QJJ6Y8usQ:b-y2b7fj) ([raw file](https://github.com/robotlocomotion/drake/blob/240ff2dc3a8359a9d774769edd57e2a77b9a2a69/drake/geometry/test/identifier_test.cc#L5)):*
> ```cpp
> #include <sstream>
> #include <unordered_map>
> #include <unordered_set>
> ```

BTW, `#include <utility>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-:-Kh3B7viXcVxZpEPF_hO:b7j4dop)*

**Comment by david-german-tri** [comment]
:lgtm: cool!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-:-Kh3EHe3i_SaSV1MUqUR:b-84whef)*

**Comment by SeanCurtis-TRI** [comment]
THe include situation has been cleaned up.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/type_safe_index_test.cc, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-Kh39uwCNtQtgvM5m3Zy:-Kh3IHGckIdh-sxjG0dp:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/240ff2dc3a8359a9d774769edd57e2a77b9a2a69/drake/common/test/type_safe_index_test.cc#L208)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, `std::declval` is in header `<utility>` which is not explicitly included above. (Probably getting sucked in by something else but better not to depend on that.)
</blockquote></details>

Done

---

*[drake/geometry/test/identifier_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-Kh3Ax6wxJ7QJJ6Y8usP:-Kh3II5nvOo5qX7Dbulo:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/240ff2dc3a8359a9d774769edd57e2a77b9a2a69/drake/geometry/test/identifier_test.cc#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, `#include <utility>`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-:-Kh3IJEFCh4hY2EZSISU:bg8az97)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-:-Kh3JhBb1NHy5lM4cn6k:bsf2vkf)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5749#-:-Kh3TivYGWwkCN6sRUtA:b-l70wzf)*

**Pull request merged**
