### PR TITLE
Update to use lcm CMake Pod from RobotLocomotion/lcm-pod#16

### PR DESCRIPTION
**Pull request by jhoare**
Updates lcm-pod tag.

### CODE REVIEW

**Comment by RussTedrake** [comment]
why do this instead of pointing directly to RobotLocomotion/lcm when it's ready? or is that still the plan?

**Comment by jhoare** [comment]
My understanding is that the plan is to get RobotLocomtion/lcm to be a fork of lcm with our patches added to it, without any use of the pods environment/cmake files. This could then later be used as a vector to upstream all or some of our patches. 

Once that is ready, we could again modify the lcm-pods to check out our fork as an external project, or make the drake super-build just checkout our lcm fork directly as an external project, removing the "podsification" of lcm altogether.

**Comment by jhoare** [comment]
@RussTedrake It looks like drake006 is out of disk space.

**Comment by jhoare** [comment]
retest this please

**Comment by RussTedrake** [comment]
Just cleared some space (possibly destroying the current build).

**Comment by jhoare** [comment]
retest this please

**Comment by jhoare** [comment]
Please don't merge this yet, @mwoehlke-kitware found a issue with the lcm-pod cmakelists.txt and he is going to provide a pull request. Once that is accepted I'll update this tag to reflect it.

**Comment by mwoehlke-kitware** [comment]
> @mwoehlke-kitware found a issue with the lcm-pod cmakelists.txt and he is going to provide a pull request. Once that is accepted I'll update this tag to reflect it.

Specifically, this should be updated to include RobotLocomotion/lcm-pod#17. (Mentioning mainly so github will link the two items...)

**Comment by jhoare** [comment]
Whoops looks like bullet needs some additional work for Apple. I'll make this pull request lcm only and fix bullet in a later one.

**Comment by jhoare** [comment]
Looks like drake006 is hung. I think this is good to go though.

**Pull request merged**
