### PR TITLE
Add Methods to solve mathematical programs in parallel

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review please! Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-:-NR8s_nl5yUQaNWpVWZR:b-atfp80)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
The code you copied this idiom from was written prior to OpenMP support in Drake.  I think it's probable that we should not land this implementation but instead rewrite using OpenMP instead.  Or possibly a veneer over OpenMP so that it also works on macOS.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`solvers/solve.h` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NR9Akl-AaMho8RncIgN:-NR9JIOB-QQ1kMOimsqZ:b-8sg80j) ([raw file](https://github.com/RobotLocomotion/drake/blob/859e1d6329538b4a6b7e1723a77d140118868756/solvers/solve.h#L85)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We want to leave the optional-eigen so that the user can specify initial guesses for some, but not all the optimization programs.
</blockquote></details>

Right.  My proposal is to lose the outermost optional, but keep the inner one.
___
*[`solvers/solve.h` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NR9BxTi5iz61kZkKe1y:-NR9JNHiAJ7ZlVj3CHHG:b1o3vb6) ([raw file](https://github.com/RobotLocomotion/drake/blob/859e1d6329538b4a6b7e1723a77d140118868756/solvers/solve.h#L89)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Yes we can. I was following the pattern already established for `Solve` in this file. Do you know why the `Solve` method doesn't do this optional argument as well.
</blockquote></details>

I think a long time ago we had more overloads, and the defaulted arguments were confusing the compiler. (Possibly it was even long enough ago that we didn't have std::optional yet either!)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`solvers/solve.h` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NR9AGLHCeJbaQ0EyYcn:-NR9JhmZ818jTB-FlxJ7:bba04xr) ([raw file](https://github.com/RobotLocomotion/drake/blob/859e1d6329538b4a6b7e1723a77d140118868756/solvers/solve.h#L83)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

That is likely why I was having trouble binding these methods in pydrake. I don't think that passing a vector of `MathematicalProgram&` would fix this problem for pydrake correct?
</blockquote></details>

I'm not 100% sure about the right fix.

Passing `vector<const Program*>` might be one way, with some kind of sugar for C++ users who already have `vector<Program>` already created.

Really, it should be a `std::ranges::range` but we haven't quite tried to bite that off yet.

I can try a few spellings locally and get back to you.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`solvers/solve.h` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NR9AGLHCeJbaQ0EyYcn:-NRJ-0aK2jIhhL5ARad-:b-nlftkz) ([raw file](https://github.com/RobotLocomotion/drake/blob/859e1d6329538b4a6b7e1723a77d140118868756/solvers/solve.h#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not 100% sure about the right fix.

Passing `vector<const Program*>` might be one way, with some kind of sugar for C++ users who already have `vector<Program>` already created.

Really, it should be a `std::ranges::range` but we haven't quite tried to bite that off yet.

I can try a few spellings locally and get back to you.
</blockquote></details>

Have a look at the top commit here and see what you think:

https://github.com/jwnimmer-tri/drake/commits/parallel_mp_solve

That's my best guess for the API of the core function (that actually performs the solving). I think it will be easier to pybind (and call from Python) than the current API. If it seems like its on the right track and you like it, you could merge it into this branch and we keep going from there.

What it lacks is nice C++ sugar.  I wasn't exactly sure what the typical C++ call site would look like.  Is the common case to provide:
* N programs, with
* either 0 or N initial guesses?
* either 0 or 1 solver options?

I am actually thinking that for C++ instead of using a pile of arguments, we would use a helper struct or class, so that there is less declaration syntax overhead at the call sites.  Stay tuned.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRKgTDb82po09wEWSm7:b-cyjimv) (no related file):*
Also can you clarify the bigger-picture goal here?

If we only need to solve-in-parallel within some Drake algorithm (like a GCS thing), then there is probably a much, much simpler way to do this.

Or if the goal is to provide this feature to users, especially Python users, then we need to do even more that my WIP so far, for the same reason as we did for MonteCarlo:

https://github.com/RobotLocomotion/drake/blob/41f0cbcae7b8ee0a4d499ca6f4ec6a591c11edd8/bindings/pydrake/systems/analysis_py.cc#L349-L351

___

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRKiuAb5lwU6GjpRNCb:b-g9vfw8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Also can you clarify the bigger-picture goal here?

If we only need to solve-in-parallel within some Drake algorithm (like a GCS thing), then there is probably a much, much simpler way to do this.

Or if the goal is to provide this feature to users, especially Python users, then we need to do even more that my WIP so far, for the same reason as we did for MonteCarlo:

https://github.com/RobotLocomotion/drake/blob/41f0cbcae7b8ee0a4d499ca6f4ec6a591c11edd8/bindings/pydrake/systems/analysis_py.cc#L349-L351


</blockquote></details>

The primary objective is to enable parallel solving of MathematicalPrograms for Python users. Several members of my lab have asked for this and it seems easier to provide this functionality on the C++ side than make MathematicalProgram pickleable so it can be used in Python multiprocessing code.

I hope to look at your push soon.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRKk87p7_ow75yTh2I4:b-j9o3ih) (no related file):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The primary objective is to enable parallel solving of MathematicalPrograms for Python users. Several members of my lab have asked for this and it seems easier to provide this functionality on the C++ side than make MathematicalProgram pickleable so it can be used in Python multiprocessing code.

I hope to look at your push soon.
</blockquote></details>

Ah, okay.  I will need to give it more thought in that case.  In general, a Python call into this function with `num_threads_actual > 1` risks crashing.

See also https://github.com/RobotLocomotion/drake/issues/10320 where certain programs (certain constraints) cannot be solved in parallel either.

___

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRPrMP_4EtAImHWyD0g:bfi4qj5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, okay.  I will need to give it more thought in that case.  In general, a Python call into this function with `num_threads_actual > 1` risks crashing.

See also https://github.com/RobotLocomotion/drake/issues/10320 where certain programs (certain constraints) cannot be solved in parallel either.
</blockquote></details>

This is showing my lack of understanding of how parallelism works. Why would a Python call into C++ function that has multiple threads risk crashing? Also, why would the thread safety of the constraints matter in this situation? Here each program is being solved in its own thread and so should not be cross talking to any other programs.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRQyLUQ02XOSO_Ca5M-:bu4dx1h) (no related file):*
> Why would a Python call into C++ function that has multiple threads risk crashing?

Sometimes, costs or constraints are Python functions:
https://drake.mit.edu/pydrake/pydrake.solvers.html#pydrake.solvers.PyFunctionConstraint

When Python code (e.g., a constraint eval) is running, it needs to hold the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock) or else things go very badly.  Ensuring that the GIL is locked exactly when needed (but not too much, or else we have a deadlock), is difficult.

> Also, why would the thread safety of the constraints matter in this situation?

The same Constraint object might have been added to multiple MathematicalPrograms.

___

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRi1sOLEUmO34rScIiS:b-mo1w8n) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Why would a Python call into C++ function that has multiple threads risk crashing?

Sometimes, costs or constraints are Python functions:
https://drake.mit.edu/pydrake/pydrake.solvers.html#pydrake.solvers.PyFunctionConstraint

When Python code (e.g., a constraint eval) is running, it needs to hold the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock) or else things go very badly.  Ensuring that the GIL is locked exactly when needed (but not too much, or else we have a deadlock), is difficult.

> Also, why would the thread safety of the constraints matter in this situation?

The same Constraint object might have been added to multiple MathematicalPrograms.
</blockquote></details>

I see. Will this also be a problem when we move forward with binding the method in `cspace_free_polytope` such as this method? https://github.com/RobotLocomotion/drake/blob/0300d225f3fc201101f5bf4f7b2db09b29eaaa57/geometry/optimization/cspace_free_polytope.cc#L658

___

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRi7WDe2BgseJ57ziZq:bbchtj4) (no related file):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I see. Will this also be a problem when we move forward with binding the method in `cspace_free_polytope` such as this method? https://github.com/RobotLocomotion/drake/blob/0300d225f3fc201101f5bf4f7b2db09b29eaaa57/geometry/optimization/cspace_free_polytope.cc#L658
</blockquote></details>

Since the users cannot add PyFunctionConstraint to the generated MathematicalProgram (the MathematicalProgram is buried inside this FindSeparationCertificateGivenPolytope function that the user cannot access), I think it should be fine?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NRk4xD84RnEEGHRZbL9:btjvnhu) (no related file):*
> Since the users cannot add PyFunctionConstraint to the generated MathematicalProgram (the MathematicalProgram is buried inside this FindSeparationCertificateGivenPolytope function that the user cannot access), I think it should be fine?

Correct.  However, also note that you are very nearby something that would be a hazard.  The `CspaceFreePolytope` has a member field `const geometry::SceneGraph<double>& scene_graph_` which is used within `FindSeparationCertificateGivenPolytope`.  If the use were inside of the worker thread, it would be invalid (since the SceneGraph could be Python-involved).  However, it's only use is after the worker threads are finished.

> The same Constraint object might have been added to multiple MathematicalPrograms.

See https://github.com/RobotLocomotion/drake/issues/10320 where we've talked about tagging evaluators with whether or not its safe to call a `const` method from multiple threads.  That feature would be a prerequisite of landing this PR.

___

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19052)* status: 5 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19052#-NRKgTDb82po09wEWSm6:-NS1YcPCCyrQwN_K9Qb-:b-i6lzac) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Since the users cannot add PyFunctionConstraint to the generated MathematicalProgram (the MathematicalProgram is buried inside this FindSeparationCertificateGivenPolytope function that the user cannot access), I think it should be fine?

Correct.  However, also note that you are very nearby something that would be a hazard.  The `CspaceFreePolytope` has a member field `const geometry::SceneGraph<double>& scene_graph_` which is used within `FindSeparationCertificateGivenPolytope`.  If the use were inside of the worker thread, it would be invalid (since the SceneGraph could be Python-involved).  However, it's only use is after the worker threads are finished.

> The same Constraint object might have been added to multiple MathematicalPrograms.

See https://github.com/RobotLocomotion/drake/issues/10320 where we've talked about tagging evaluators with whether or not its safe to call a `const` method from multiple threads.  That feature would be a prerequisite of landing this PR.
</blockquote></details>

I think I will move this to a feature request on Github and close this PR. I think there is a lot of value to being able to solve Mathematical Programs in parallel, especially for Python users who are limited by the GIL, but there appears to be much more work to do before we actually are able to support this.

___

**Pull request closed without merging**
