### PR TITLE
In from_source, recommend Xenial

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
... as well as other related tune-ups in preparation for recommending Bazel.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5695)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@russtedrake for feature review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-Kgf3URDy4BMVIGjmC5z:b-dmufd6)*

**Comment by liangfok** [comment]
+@liangfok :lgtm: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_binary.rst, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KggiUVtkobSkVCpygV9:-KggiUVtkobSkVCpygVA:b-716kl) ([raw file](https://github.com/robotlocomotion/drake/blob/65318e1dd6208652c63bd39bbfea82d2cde91365/drake/doc/from_binary.rst#L18)):*
> ```reStructuredText
> In the meantime, we suggest you :ref:`build from source <build_from_source>`
> instead.
>      
> ```

BTW, three extra spaces.

---

*[drake/doc/models.rst, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kggj2iLZUZzQjLrDBcH:-Kggj2iLZUZzQjLrDBcI:b8gassh) ([raw file](https://github.com/robotlocomotion/drake/blob/65318e1dd6208652c63bd39bbfea82d2cde91365/drake/doc/models.rst#L4)):*
> ```reStructuredText
> 
> *************************
> Geometric Models in Drake
> ```

BTW: @lucy-tri FYI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-KggjCqFNdu6Ms9f-eqL:bkgbgk3)*

**Comment by RussTedrake** [comment]
Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_binary.rst, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KgiVkenXoJaaS1xT4h1:-KgiVkeoUXTehePIM7Hu:bo1qp8) ([raw file](https://github.com/robotlocomotion/drake/blob/65318e1dd6208652c63bd39bbfea82d2cde91365/drake/doc/from_binary.rst#L14)):*
> ```reStructuredText
> We are actively working on a binary release of the new software, but are not
> quite finished.  See https://github.com/RobotLocomotion/drake/issues/1766 for
> details.
> ```

BTW, thanks for updating this, too.

---

*[drake/doc/ubuntu_trusty.rst, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KgiVz3S0lpFkjHYsHN1:-KgiVz3S0lpFkjHYsHN2:b-dwvzv1) ([raw file](https://github.com/robotlocomotion/drake/blob/65318e1dd6208652c63bd39bbfea82d2cde91365/drake/doc/ubuntu_trusty.rst#L67)):*
> ```reStructuredText
> 
> Bazel is required.  Install Bazel using the instructions at
> https://bazel.build/versions/master/docs/install-ubuntu.html.
> ```

This is more painful than the other build instructions on this page.  Can we not just summarize it with `sudo apt-get install bazel` or something similar (if we need to peg the revision)?  

I personally know that when I'm installing a new machine (just did 4 ubuntu VMs on four different laptops this week), I just want to cut and paste the sudo's after I've verified for myself the first time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by RussTedrake** [comment]
btw, i did build the docs to verify locally.  looks great apart from my one request below.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-KgiWP_o64TYop3hJFiy:b-vruv1b)*

**Comment by RussTedrake** [comment]
also, can you recommend which is preferred: xenial vs trusty.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-KgiZnutTUtoX4Dne-f0:bxhfxke)*

**Comment by jwnimmer-tri** [comment]
Personally, I hope we drop Trusty before the year is out -- I think new users should be starting from Xenial.  However, I didn't want to update the docs to dissuade people from Trusty until we get more consensus on #5012.  If you agree that Xenial should at least be preferred, I'll update this PR with that also.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-Kgi_aslwqlcTJLkYK_v:b-tza0rw)*

**Comment by jwnimmer-tri** [comment]
I pushed some language preferring Xenial.

---

Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KgigSQJbWHsS_d0D3TL:-KgigSQJbWHsS_d0D3TM:bbrm9kz) (no related file):*
Can someone please re-test locally that the Trusty setup instructions work correctly, and then post back to this discussion?  Thanks!

---

*[drake/doc/from_binary.rst, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KggiUVtkobSkVCpygV9:-KgiYG_oXiZTcEZZ_TYl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65318e1dd6208652c63bd39bbfea82d2cde91365/drake/doc/from_binary.rst#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, three extra spaces.
</blockquote></details>

Done.

---

*[drake/doc/ubuntu_trusty.rst, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KgiVz3S0lpFkjHYsHN1:-KgiYXo9vDAOvhEoCQ9w:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/65318e1dd6208652c63bd39bbfea82d2cde91365/drake/doc/ubuntu_trusty.rst#L67)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This is more painful than the other build instructions on this page.  Can we not just summarize it with `sudo apt-get install bazel` or something similar (if we need to peg the revision)?  

I personally know that when I'm installing a new machine (just did 4 ubuntu VMs on four different laptops this week), I just want to cut and paste the sudo's after I've verified for myself the first time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-KgigOOAu_jg_AWvJMKT:bbvibfm)*

**Comment by RussTedrake** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-KgigSQJbWHsS_d0D3TL:-KgihUQzI7-SOR2Zq88V:bl8f41c) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can someone please re-test locally that the Trusty setup instructions work correctly, and then post back to this discussion?  Thanks!
</blockquote></details>

agreed.  thanks.  i think that if most of the developers are using xenial, then it makes sense to document that fact.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by liangfok** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-:-KgjVN_jQUoH6zCPziEc:bnfp4nl)*

**Comment by liangfok** [comment]
I will test this on Trusty and post results.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/ubuntu_trusty.rst, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kgkd5JVcnL7r2otrUfJ:-Kgkd5JVcnL7r2otrUfK:bxf7u06) ([raw file](https://github.com/robotlocomotion/drake/blob/31bd2abce05ad5213cfbce0d28a1d36af7aacc3c/drake/doc/ubuntu_trusty.rst#L76)):*
> ```reStructuredText
>     echo "0cd6592ac2c5548d566fa9f874a386737e76029f5aabe1f04f8320173a05280d  bazel_0.4.3-linux-x86_64.deb" > bazel_0.4.3-linux-x86_64.deb.sha256
>     sha256sum --check bazel_0.4.3-linux-x86_64.deb.sha256 && sudo dpkg -i bazel_0.4.3-linux-x86_64.deb
> ```

On my trusty machine, I have Bazel 0.4.4 installed:

```
$ dpkg -l | grep bazel
ii  bazel                                                 0.4.4                                               amd64        Bazel is a tool that automates software builds and tests.
```
These instructions are for Bazel 0.4.3. Is this correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/ubuntu_trusty.rst, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kgkd5JVcnL7r2otrUfJ:-KgkhiW_GFJCyXXKkDVd:b45t4dm) ([raw file](https://github.com/robotlocomotion/drake/blob/31bd2abce05ad5213cfbce0d28a1d36af7aacc3c/drake/doc/ubuntu_trusty.rst#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

On my trusty machine, I have Bazel 0.4.4 installed:

```
$ dpkg -l | grep bazel
ii  bazel                                                 0.4.4                                               amd64        Bazel is a tool that automates software builds and tests.
```
These instructions are for Bazel 0.4.3. Is this correct?
</blockquote></details>

Yes, the instructions are for Bazel 0.4.3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kgl66fzT-qp28hXimOM:-Kgl66g-lMqAGwhykAmj:b-wqxckc) ([raw file](https://github.com/robotlocomotion/drake/blob/31bd2abce05ad5213cfbce0d28a1d36af7aacc3c/drake/doc/from_source.rst#L81)):*
> ```reStructuredText
> first choice if you intend to stay up-to-date with the latest changes,
> contribute new features, or experiment directly with Drake.  It is also the
> least complex choice to get started.
> ```

I guess this is not the entire story.  We should add a note here saying that they might still have to use make or ninja if they want to build director.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by jwnimmer-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kgl66fzT-qp28hXimOM:-KglS2YeGE9j7DW08h1B:bov0958) ([raw file](https://github.com/robotlocomotion/drake/blob/31bd2abce05ad5213cfbce0d28a1d36af7aacc3c/drake/doc/from_source.rst#L81)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I guess this is not the entire story.  We should add a note here saying that they might still have to use make or ninja if they want to build director.  
</blockquote></details>

Done.

This discussion pointed out that we shouldn't be putting Bazel atop the list until #5621 is resolved.  I've removed this one patch from this PR and set it aside for later.

So for now, the only change to this file is to recommend Xenial.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by RussTedrake** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kgl66fzT-qp28hXimOM:-KglTiZyVVX8a0bi6SuA:b1pkn4) ([raw file](https://github.com/robotlocomotion/drake/blob/31bd2abce05ad5213cfbce0d28a1d36af7aacc3c/drake/doc/from_source.rst#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

This discussion pointed out that we shouldn't be putting Bazel atop the list until #5621 is resolved.  I've removed this one patch from this PR and set it aside for later.

So for now, the only change to this file is to recommend Xenial.
</blockquote></details>

Sigh.  OK.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by liangfok** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/ubuntu_trusty.rst, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5695#-Kgkd5JVcnL7r2otrUfJ:-KglLyO_ySK_7v79_QwA:bx9hamt) ([raw file](https://github.com/robotlocomotion/drake/blob/31bd2abce05ad5213cfbce0d28a1d36af7aacc3c/drake/doc/ubuntu_trusty.rst#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, the instructions are for Bazel 0.4.3.
</blockquote></details>

I confirm that the above recipe works on an Ubuntu Trusty machine. Below are some stats from my test-machine, which has 16 GB of RAM but an older Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz. It took 1.8 hours to build.

```
$ bazel build ...
Extracting Bazel installation...
..........
WARNING: /home/liang/dev/drake-distro-5/drake/util/BUILD:63:1: target '//drake/util:app_util' is deprecated: Please use gflags instead of drakeAppUtil.h.
WARNING: /home/liang/.cache/bazel/_bazel_liang/c879694f3a73605ddca427b79a105bfa/external/drake_visualizer/BUILD:2:48: soft_failure.bzl: @drake_visualizer//:drake-visualizer does not work because /home/liang/dev/drake-distro-5/build/install/bin/drake-visualizer was missing.
INFO: Found 2333 targets...
INFO: From Executing genrule //drake/automotive:speed_bump_genrule:
[2017-04-02 23:00:47.833] [console] [info] Loading road geometry.
[2017-04-02 23:00:47.834] [console] [info] Generating OBJ.
INFO: Elapsed time: 6593.061s, Critical Path: 3153.29s
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5695)*

**Pull request merged**
