### PR TITLE
Speed up affine hull computation.

### PR DESCRIPTION
**Pull request by cohnt**
I've rewritten the code used to compute affine hulls of convex sets. It is now much quicker, and the number of LPs solved is equal to the ambient dimension. (Previously, it could be as many as the square of the ambient dimension.)

Thew new methodology is to incrementally construct a basis of the affine hull _and_ its orthogonal complement. At each iteration, we take a vector which is orthogonal to both the affine hull basis and the orthogonal complement basis, and try to maximize the displacement of a line segment contained in the convex set along that direction. If we can exceed a user-designated tolerance, we treat that as a feasible direction, and add it to the basis. Otherwise, we add it to the orthogonal complement basis.

If you have time, +@alexandreamice for feature review.

cc @rhjiang @shaoyuancc

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
Thanks for doing this. I just sent you a PR that avoids the matrix factorizations every loop that should be even faster.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-:-Nzdb2O22vVIsdC5CskS:btw23lp)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
Merged in your changes. I changed the naming convention a bit (since it's now a spanning set, not a basis) and added a couple of comments, but nothing else.

Are you still able to do the feature review, or do we need a third party?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-:-NzdgC5cE6M3QCzTWAT4:b5up4hb)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525)* status: 4 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/affine_subspace.cc` line 99 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-NzdhVJx275WxJdelazR:-NzdhVJx275WxJdelazS:bk5get1) ([raw file](https://github.com/RobotLocomotion/drake/blob/99eca5d2feb7532c9f639c3798e500046f5c2d8a/geometry/optimization/affine_subspace.cc#L99)):*
> ```cpp
>   // the invariant that at the start of each iteration, any two column vectors
>   // taken from distinct matrices {basis.leftCols(affine_dimension),
>   // spanning_unknown.leftCols(complement_dimension)} are orthogonal, and that each
> ```

this should be `basis_orth`



_Code quote:_
```cpp
 spanning_unknown
```

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

___
*[`geometry/optimization/affine_subspace.cc` line 100 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-Nzdg0n-D-z1JqGWb1Qh:-NzdyH_wBY_HGQLWTFge:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/38fa35e2e157d8d6d11a552c7637dd3d9cee364e/geometry/optimization/affine_subspace.cc#L100)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: sorry forgot to change these to
</blockquote></details>

Done.
___
*[`geometry/optimization/affine_subspace.cc` line 103 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-NzdgDskA0FjOEy84KRt:-Nzdy4xD2iZ36uRwgVrR:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/38fa35e2e157d8d6d11a552c7637dd3d9cee364e/geometry/optimization/affine_subspace.cc#L103)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`geometry/optimization/affine_subspace.cc` line 118 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-NzdgLbwArmdw3oJqUZD:-NzdyAgG-yZ66DKadu2d:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/38fa35e2e157d8d6d11a552c7637dd3d9cee364e/geometry/optimization/affine_subspace.cc#L118)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: Sorry I put a small lie in that comment. This is more precise.
</blockquote></details>

Done.
___
*[`geometry/optimization/affine_subspace.cc` line 96 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-Nzdk1Gl-edPndtSqXHQ:-NzdxHIn46qPQr9baLT7:b-6ivcpx) ([raw file](https://github.com/RobotLocomotion/drake/blob/99eca5d2feb7532c9f639c3798e500046f5c2d8a/geometry/optimization/affine_subspace.cc#L96)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Yep, it was a typo. Fixed!
___
*[`geometry/optimization/affine_subspace.cc` line 99 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-NzdhVJx275WxJdelazR:-NzdxtCx4yptoISfjW78:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/99eca5d2feb7532c9f639c3798e500046f5c2d8a/geometry/optimization/affine_subspace.cc#L99)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

this should be `basis_orth`
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
What should this be tagged as for the release notes? And the commits can be squashed once it passes CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-:-Nze0-PkE8-u048-1Sfo:btpw2au)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

**Review by AlexandreAmice — COMMENTED** [review]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-release please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-:-Nze9lsHCa43jmPO5xYL:b-taz7jm)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @cohnt)

**Review by ggould-tri — COMMENTED** [review]
+(status: squashing now) +(release notes: feature) 
And it's not obvious to me what the CI failure is -- it doesn't repro locally for me, so it might be noise.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21525#-:-Nze9BCy2TslceY9qYZQ:bxqj4qb)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Comment by jwnimmer-tri** [comment]
The `libomp` thing looks like known flake #20344.  I'm not sure why it's turning up here.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-release please

**Pull request merged**
