### PR TITLE
Work around PETSc 1180

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Work around an undefined-behavior sanitizer runtime failure in PETSc, "applying zero offset to null pointer", by adjusting the logic for the case when no bytes are allocated.

Reported as https://gitlab.com/petsc/petsc/-/issues/1180.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
It seems like this is ready for a feature reviewer, maybe +@svenevs?

**Review by xuchenhan-tri — COMMENTED** [review]
I already reviewed this. Can serve as either platform or feature.
+@xuchenhan-tri :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102#-:-N1KOqgxBx3UGrV1Cbho:bh84s7c)* status: LGTM missing from assignee svenevs, missing label for release notes (waiting on @svenevs)

___
*[`tools/workspace/petsc/patches/mal.patch` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1KPWhF-hLRYS4og95Y:-N1KPWhF-hLRYS4og95Z:b-ihil16) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d35bed6d1dd9af0b6c3a9dfa8ad2183cd7e28c/tools/workspace/petsc/patches/mal.patch#L14)):*
> ```Diff
> +    if (p == NULL) {
> +      for (i=0; i<n; i++) {
> +        *ptr[i] = NULL;
> ```

BTW, I believe the implicit assumption here is bytes[i] == 0? Maybe we should check that?

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
*[`tools/workspace/petsc/patches/mal.patch` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1KPWhF-hLRYS4og95Y:-N1KVIJa1H3cyIcf5N7r:bfvdg0) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d35bed6d1dd9af0b6c3a9dfa8ad2183cd7e28c/tools/workspace/petsc/patches/mal.patch#L14)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I believe the implicit assumption here is bytes[i] == 0? Maybe we should check that?
</blockquote></details>

I would say it's safe to skip.  `PetscMallocAlign` registers an error in case `malloc()` fails.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/petsc/patches/mal.patch` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1KPWhF-hLRYS4og95Y:-N1K_vsE6oNe-QDqZa-X:bxizni6) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d35bed6d1dd9af0b6c3a9dfa8ad2183cd7e28c/tools/workspace/petsc/patches/mal.patch#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I would say it's safe to skip.  `PetscMallocAlign` registers an error in case `malloc()` fails.
</blockquote></details>

Right. Not only `bytes[i] == 0` but also `sumbytes == 0` (i.e. the former, for *all* `i`) should be the only cases where `p == NULL` but `PetscTrMalloc` did not error.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1KyP-097bFVCAe2GGa:-N1KyP-097bFVCAe2GGb:b-qvyguv) (no related file):*
This doesn't actually apply the patch.  You need to mention it in repository.bzl to have any effect.

```patch
--- a/tools/workspace/petsc/repository.bzl
+++ b/tools/workspace/petsc/repository.bzl
@@ -22,5 +22,7 @@ def petsc_repository(
             "@drake//tools/workspace/petsc:patches/pname.patch",
             "@drake//tools/workspace/petsc:patches/remove_packages.patch",
             "@drake//tools/workspace/petsc:patches/tagm.patch",
+            # Cherry-picked from upstream.
+            "@drake//tools/workspace/petsc:patches/mal.patch",
         ],
     )
```

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1KyP-097bFVCAe2GGa:-N1L7xct1SUap1ETa-21:b-vttivq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This doesn't actually apply the patch.  You need to mention it in repository.bzl to have any effect.

```patch
--- a/tools/workspace/petsc/repository.bzl
+++ b/tools/workspace/petsc/repository.bzl
@@ -22,5 +22,7 @@ def petsc_repository(
             "@drake//tools/workspace/petsc:patches/pname.patch",
             "@drake//tools/workspace/petsc:patches/remove_packages.patch",
             "@drake//tools/workspace/petsc:patches/tagm.patch",
+            # Cherry-picked from upstream.
+            "@drake//tools/workspace/petsc:patches/mal.patch",
         ],
     )
```
</blockquote></details>

Oops I missed that. Sorry and thanks.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform for the patch, pending application on the patch (Jeremy's "meta" patch)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102#-:-N1OmqDa4hKVKgRhBO-P:b7o1ja5)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)* status: 2 unresolved discussions, missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1OnIZE3RToQJHHUPXI:-N1OnIZE3RToQJHHUPXJ:b-c9lxtl) (no related file):*
nit In overview, #1180 doesn't seem like the correct issue.

Perhaps #16937?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)* status: 2 unresolved discussions, missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1OnIZE3RToQJHHUPXI:-N1OpXz3-loOZM6oadYA:ba24kdl) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit In overview, #1180 doesn't seem like the correct issue.

Perhaps #16937?
</blockquote></details>

It's the PETSc issue number https://gitlab.com/petsc/petsc/-/issues/1180.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1OnIZE3RToQJHHUPXI:-N1Oq3pX6vPnzhW5JRc-:bncs2wj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's the PETSc issue number https://gitlab.com/petsc/petsc/-/issues/1180.
</blockquote></details>

OK Ah, yeah, that's the URL. Now I'm wondering what I clicked on to get there :facepalm: 

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17102)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17102#-N1KyP-097bFVCAe2GGa:-N1QPCAlEA7xalUrnMmk:b-896fix) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Oops I missed that. Sorry and thanks.
</blockquote></details>

Done.

---

**Pull request merged**
