### PR TITLE
Deprecate and remove all uses of DRAKE_ABORT

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We want to remove `DRAKE_ABORT`, because all errors should have a useful message.

Many uses are replaced by a new `DRAKE_UNREACHABLE` macro.

(We may also end up removing "abort" entirely from Drake, since it is inappropriate for library code.  But that's still future work and up for debate.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10545)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This PR is incomplete, but posted for early feedback.

**Comment by jwnimmer-tri** [comment]
Ready for review now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-python3-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please

**Comment by jwnimmer-tri** [comment]
@soonho-tri PTAL when you have time.

**Pull request merged**
