### PR TITLE
Install optitrack_driver

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6344)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm: I guess...

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[WORKSPACE, line 178 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgCR_9xyZ0rBa0xeap:-KmgCR_AL_xZDptTRJpT:b-w12fao) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/WORKSPACE#L178)):*
> ```Python
> github_archive(
>     name = "optitrack_driver",
>     repository = "RobotLocomotion/optitrack-driver",
> ```

Does this need to be build-able by itself, or should we just make it directly installable?

---

*[tools/install/optitrack_driver/BUILD, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgCdxhZIUOqnJqcf3K:-KmgCdxhZIUOqnJqcf3L:b-ly5rf8) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/BUILD#L19)):*
> ```Python
> OPTITRACK_TARGETS = [
>     "@optitrack_driver//lcmtypes:lcmtypes_optitrack",
>     "@optitrack_driver//lcmtypes:optitrack_lcmtypes",
> ```

BTW, geez, this pair of names isn't confusing at all... has anyone thought about renaming the targets in this repo to be more consistent with other lcmtypes packages?

---

*[tools/install/optitrack_driver/optitrack.cps, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgDfE-s_9pg7cK-8fe:-KmgDfE0QPWbTj96ch1P:bj6ane0) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/optitrack.cps#L4)):*
> ```delphi
>   "Cps-Version": "0.8.0",
>   "Name": "optitrack",
>   "Description": "Translates data streamed from the Optitrack Motive software (aka NatNet) into LCM messages",
> ```

BTW, "a.k.a."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-:-KmgDqc6Oth3ZxYbZlk6:b-yec2zn)*

**Comment by jamiesnape** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 178 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgCR_9xyZ0rBa0xeap:-KmgP8Pfn60iDHe37qeP:b-aqte3u) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/WORKSPACE#L178)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Does this need to be build-able by itself, or should we just make it directly installable?
</blockquote></details>

Install rules are going to stay in drake for now.

---

*[tools/install/optitrack_driver/optitrack.cps, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgDfE-s_9pg7cK-8fe:-KmgPE_7aUW4f9PDj5uW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/optitrack.cps#L4)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, "a.k.a."?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6344)*

**Comment by sammy-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/optitrack_driver/BUILD, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgCdxhZIUOqnJqcf3K:-KmgO3MNpo6RfGdlr4wg:bqx0jhy) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/BUILD#L19)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, geez, this pair of names isn't confusing at all... has anyone thought about renaming the targets in this repo to be more consistent with other lcmtypes packages?
</blockquote></details>

BTW "lcmtypes_optitrack" is a terrible name, I'll admit.  It all started with my frustration at not being able to get bazel to emit a java lcmtypes library in a useful fashion...

If you take a look at build/install/share/java in a CMake build of drake, there are a bunch of jar files called lcmtypes_foo.jar.  bot-spy (see install/bin/bot-spy) uses the lcmtypes_ prefix to find lcm descriptions to load, which is how the rule name came about...  Of course, this doesn't actually generate a library with the right name, which is how the install script for the optitrack driver used in spartan wound up just renaming the jar anyway:   https://github.com/RobotLocomotion/optitrack-driver/blob/master/install-optitrack.sh#L21

Which is all to say that the stupid rule name was an attempt to do something that didn't work (create a jar starting with lcmtypes_) and I probably should have renamed the rule when I realized I wasn't going to get what I wanted from bazel.

As one nitpick though, if you install a thing called liblcmtypes_optitrack.jar it's not actually going to be usefully found with bot-spy so maybe just leaving it out is no worse than including it?

(apologies if the text above is actually just a rant which makes no sense)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6344)*

**Comment by jamiesnape** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/optitrack_driver/BUILD, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgCdxhZIUOqnJqcf3K:-KmgQJkG6IeHN5nprqwm:b-gl5di1) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/BUILD#L19)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW "lcmtypes_optitrack" is a terrible name, I'll admit.  It all started with my frustration at not being able to get bazel to emit a java lcmtypes library in a useful fashion...

If you take a look at build/install/share/java in a CMake build of drake, there are a bunch of jar files called lcmtypes_foo.jar.  bot-spy (see install/bin/bot-spy) uses the lcmtypes_ prefix to find lcm descriptions to load, which is how the rule name came about...  Of course, this doesn't actually generate a library with the right name, which is how the install script for the optitrack driver used in spartan wound up just renaming the jar anyway:   https://github.com/RobotLocomotion/optitrack-driver/blob/master/install-optitrack.sh#L21

Which is all to say that the stupid rule name was an attempt to do something that didn't work (create a jar starting with lcmtypes_) and I probably should have renamed the rule when I realized I wasn't going to get what I wanted from bazel.

As one nitpick though, if you install a thing called liblcmtypes_optitrack.jar it's not actually going to be usefully found with bot-spy so maybe just leaving it out is no worse than including it?

(apologies if the text above is actually just a rant which makes no sense)
</blockquote></details>

BTW Makes sense. I am going to have to cleanup all the jar names that are installed, probably.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6344)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review (or whoever happens to be available).

**Comment by mwoehlke-kitware** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/lcm-create-cps.py, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgXHFLTdQ8VGvYI52U:-KmgXHFM4e6a56DT4P4C:b1buta9) ([raw file](https://github.com/robotlocomotion/drake/blob/948be588ccf3658c38d6f526798a76cdcbefe86c/tools/lcm-create-cps.py#L31)):*
> ```Python
>     "lcm-java": {
>       "Type": "jar",
>       "Location": "@prefix@/share/java/liblcm-java.jar"
> ```

BTW, I guess this is okay, but if we're adding support for renaming, it is just going to get reverted later... ("fix" until it works is reasonable, though.)

---

*[tools/install/optitrack_driver/BUILD, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgCdxhZIUOqnJqcf3K:-KmgWns1ZwAqya6QuSRD:bg66aua) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/BUILD#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Makes sense. I am going to have to cleanup all the jar names that are installed, probably.
</blockquote></details>

ACK. We probably want to add an ability somehow to rename files being installed. (I think every jar installed, anywhere, will want to use this...)

---

*[tools/install/optitrack_driver/optitrack.cps, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-KmgDfE-s_9pg7cK-8fe:-KmgX8thCfBO6qTJna5Z:b8ta2nu) ([raw file](https://github.com/robotlocomotion/drake/blob/2d841c9df4f99cee8c265582e9a6a34c345c22bd/tools/install/optitrack_driver/optitrack.cps#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6344)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
-@soonho-tri +@jwnimmer-tri stealing platform.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6344#-:-KmlIAAq2D0bNYYPbNZp:bnfp4nl)*

**Pull request merged**
