### PR TITLE
remove the non-licensed arrow3D function

### LINKED ISSUE #2788: arrow3D and ode4 are unlicensed
Drake distributes the files `drake/thirdParty/nonfree/arrow3D.m` and `drake/thirdParty/nonfree/ode4.m`, but neither file appears to come with a license grant.  Unless we can obtain a such a license, we will have to stop using these two files.

arrow3D is used here:
- examples/grasping/forceClosure/ForceClosureContacts.m:138
- examples/grasping/forceClosure/ForceClosureContactsFixedFaces.m:94
- ~~solvers/trajectoryOptimization/ContactWrenchVisualizer.m:138~~ _(edit: retracted)_
- ~~systems/robotInterfaces/FootstepPlan.m:120~~ _(edit: retracted)_

ode4 is used here:
- examples/ZMP/LinearInvertedPendulum.m:291
- examples/dev/SpringFlamingo/SpringFlamingoPlant.m:7
- examples/dev/SpringFlamingo/SpringFlamingoPlant.m:48

arrow3D appears to be sourced from here, but note that this post has no license granted:
http://www.mathworks.com/matlabcentral/fileexchange/12274-3d-arrow-with-many-color-parameter-options/content/arrow3D_pub/arrow3D.m

ode4 appears to be sourced from here, but I can't find any copyright or license information:
http://www.nt.ntnu.no/users/skoge/diplom/diplom12/hansen/OLGA_Model_Simulations/ode4.m

### PR DESCRIPTION
**Pull request by hongkai-dai**
Replace it with BSD licensed `arrow3d` function.  Part of the #2788 fix.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2792)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@jwnimmer-tri , PTAL

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2792#-:-KMVb0ZcjziItAprNFJv:1417088721)*

**Comment by jwnimmer-tri** [comment]
To +@david-german-tri for final review and merge.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Jenkins experienced an error, so @drake-jenkins-bot retest this please.

**Comment by david-german-tri** [comment]
This stuff surely has no unit test coverage, right?  :lgtm: assuming you've tested it manually.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2792#-:-KMZKmif8iixO0Jg2hRg:-506777628)*

**Comment by hongkai-dai** [comment]
We call the `arrow3d` function in `ForceClosureContacts.m`, to draw the contact force as an arrow. Then in `testSynthesizeGrasp` function, we test the visualization of force closure contacts, and call the `arrow3d` function in this test.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2792#-:-KM_AtYLmBdteATV44Hp:1795866975)*

**Pull request merged**
