### PR TITLE
Modified AutomotiveSimulator to only send one lcmt_viewer_load_robot message.

### LINKED ISSUE #5694: AutomotiveSimulator Terrain Visualization is Broken
# Problem

When `automotive_simulator` is configured to load a terrain like a dragway, the terrain does not show up in `drake-visualizer`. The vehicles, however, do appear.

# Primary Suspects

1. No lcmt_viewer_draw message is being transmitted for the terrain.

2. The `robot_num` of the links that constitute the terrain conflicts with the `robot_num` of a vehicle instance.

# Initial Analysis
I believe this regression arose with the merge of #5664 since that's when the load / draw messages for the terrain became separated from the load / draw messages of the vehicles. It was undetected because there's currently no unit test that verifies the expected visualization within `drake-visualizer`.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5694.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5697)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please.

**Comment by liangfok** [comment]
+@soonho-tri for feature review please.
+@jwnimmer-tri for platform and car reviews please.

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5697#-:-KggtNGCZvBo6gxg5DKF:b-l01g25)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5697#-:-Kgh0FvV20shFeC9Y7sU:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5697#-:-KgicAGrdbaK5VWZ0DcW:bnfp4nl)*

**Pull request merged**
