### PR TITLE
Logarithmic coding of special ordered set 2 constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6337)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-KmcJi2BzYN_jOCUUa0K:biagjkq)*

**Comment by hongkai-dai** [comment]
This code was initially implemented by @gizatt , adapted from https://github.com/joehuchette/PiecewiseLinearOpt.jl/blob/master/src/jump.jl

The goal is to encode sos2 constraint with logarithmic number of binary variables and constraints.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-KmcK1n1g43acyDBOe85:b-njvk0i)*

**Comment by gizatt** [comment]
This is great! Nice find on the Vielma paper, I found it a lot easier to follow (as I think it treats this particular problem more specifically?). I don't have anything huge... I spent a while getting my head properly around the formulation and working it out on paper, and I'm behind what you have here (minus the one thing about putting sum(\lambda)=1 in the SOS2 constraint).

---

Reviewed 4 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcNRxDNMshrWpk8s_W:-KmcNRxDNMshrWpk8s_X:b8jinjg) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.cc#L39)):*
> ```cpp
>   const int num_lambda = lambda.rows();
>   for (int i = 0; i < num_lambda; ++i) {
>     prog->AddLinearConstraint(lambda(i) >= 0);
> ```

Bounding box constraint? Up to you, but it seems more in line with what you mean.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcSA5GQnXoncXeIV1U:-KmcSA5GQnXoncXeIV1V:b7ce9is) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L16)):*
> ```objc
>  */
> constexpr int CeilLog2(int n) {
>   return n == 1? 0 : 1 + CeilLog2((n + 1) / 2);
> ```

nit: space missing in `1 ? 0`, I think

---

*[drake/solvers/mixed_integer_optimization_util.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcTFkWS7RJQetrXdzL:-KmcTFkWS7RJQetrXdzM:bahf7rs) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L25)):*
> ```objc
>  * Return the k-digit reflected Gray codes.
>  * @param k The number of digits in the Gray code.
>  * @retval m m.row(i) is the Gray code for integer i.
> ```

Maybe worth specifying for the reader that this will return a 2^k x k matrix (for positive k).

---

*[drake/solvers/mixed_integer_optimization_util.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcTbsnJ1WTffqDq_TL:-KmcTbsola-AAZhoSkEt:bpbxyib) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L36)):*
> ```objc
>  * (1, 0) -> 3
>  * @param grey_code
>  * @return
> ```

Not finished here?

---

*[drake/solvers/mixed_integer_optimization_util.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcTw8_GJv66ZHMRVqp:-KmcTw8_GJv66ZHMRVqq:bkynlbq) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L55)):*
> ```objc
>  * have to be adjacent.
>  * @return y The newly added binary variables. The inactivation of the binary
>  * variable y implies the inactivation of the expression λ.
> ```

I think this expression is misleading and maybe incomplete -- inactivation of the ith binary variables indicates something about the lambdas indicated (and not indicated) by the active elements of the ith gray code. Activation of  binary variables in accordance with the Mth gray code corresponds to \lambda(M) and \lambda(M+1) being active, which I think you're getting at below.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmchMYrsyUpG82ckjac:-KmchMYsLu60PmPKCeEW:b2flhji) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/test/mixed_integer_optimization_util_test.cc#L20)):*
> ```cpp
>   EXPECT_EQ(0, CeilLog2(1));
>   for (int i = 0; i < kMaxExponent; ++i) {
>     for (int j = two_to_exponent[i] + 1; j <= two_to_exponent[i]; ++j) {
> ```

j starts at x+1 and increments, but terminates when >x... am I misreading this or does this never iterate?

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmciGGHwqTfsMmeEtb0:-KmciGGIJroZ6M3OXy9p:bvl1ky4) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/test/mixed_integer_optimization_util_test.cc#L76)):*
> ```cpp
>   MathematicalProgram prog;
>   auto lambda = prog.NewContinuousVariables(num_lambda, "lambda");
>   prog.AddLinearConstraint(lambda.cast<symbolic::Expression>().sum() == 1);
> ```

Shouldn't this be part of the SOS2 constraint implementation, and not supplied out here? I don't think the SOS2 constraint works without it (from an example worked out on paper).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-KmciZ7W9_RRQOKxnGLF:b-wx6fpc)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcNRxDNMshrWpk8s_W:-KmcptWFfLwY3R0AIWwo:b-2fwje2) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.cc#L39)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Bounding box constraint? Up to you, but it seems more in line with what you mean.
</blockquote></details>

`lambda` is a symbolic expression here. If it were `symbolic::Variable` we should put the BoundingBoxConstraint.

Do you think `lambda` should be symbolic::Variable? I copied your implementation which uses `symbolic::Expression`.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcSA5GQnXoncXeIV1U:-KmcqCWGhC4mVkTsbHHu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L16)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

nit: space missing in `1 ? 0`, I think
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcTFkWS7RJQetrXdzL:-KmcqY1De9VLPRwQAPob:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L25)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Maybe worth specifying for the reader that this will return a 2^k x k matrix (for positive k).
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcTbsnJ1WTffqDq_TL:-KmcqeXrY1Zj59xWGEvi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L36)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Not finished here?
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmcTw8_GJv66ZHMRVqp:-KmcqtID4zKjS3vaDQAQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/mixed_integer_optimization_util.h#L55)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I think this expression is misleading and maybe incomplete -- inactivation of the ith binary variables indicates something about the lambdas indicated (and not indicated) by the active elements of the ith gray code. Activation of  binary variables in accordance with the Mth gray code corresponds to \lambda(M) and \lambda(M+1) being active, which I think you're getting at below.
</blockquote></details>

Done.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmchMYrsyUpG82ckjac:-KmcrySsSOn1o0RVWAe4:b-v2kcf8) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/test/mixed_integer_optimization_util_test.cc#L20)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

j starts at x+1 and increments, but terminates when >x... am I misreading this or does this never iterate?
</blockquote></details>

I added some documentations, hopefully it is more clear.

---

*[drake/solvers/test/mixed_integer_optimization_util_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KmciGGHwqTfsMmeEtb0:-Kmcs2xAnUYVA5nO4DDV:b-tkbxfs) ([raw file](https://github.com/robotlocomotion/drake/blob/d40e8675e227cf6a8fd8169609840f2405e4c924/drake/solvers/test/mixed_integer_optimization_util_test.cc#L76)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Shouldn't this be part of the SOS2 constraint implementation, and not supplied out here? I don't think the SOS2 constraint works without it (from an example worked out on paper).
</blockquote></details>

Done. You are right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-KmdYDpUZtgIzE4sX3Mb:b-vt9vbo)*

**Comment by soonho-tri** [comment]
Checkpoint. Thanks for the patience!

---

Reviewed 8 of 12 files at r3.
Review status: 8 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/math/gray_code.h, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZkDTADySEqE_vDWxP:-KnZkDTADySEqE_vDWxQ:b-q00whm) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L8)):*
> ```objc
> namespace math {
> template<int NumDigits>
> struct GrayCodesMatrix {
> ```

BTW, better to have a short documentation for the type-trait?

---

*[drake/math/gray_code.h, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZgsvHuJ6FCYbGuj-X:-KnZgsvHuJ6FCYbGuj-Y:b-xzt6ov) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L9)):*
> ```objc
> template<int NumDigits>
> struct GrayCodesMatrix {
>   typedef typename Eigen::Matrix<int, NumDigits == 0 ? 0 : 1 << NumDigits,
> ```

FYI, `1 << NumDigits` works as expected only if `1 <= NumDigits <= 30` holds (assuming `sizeof(int) = 4`). Can we add `static_assert` to enforce the precondition?

---

*[drake/math/gray_code.h, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZlGvHVA20auwKybq0:-KnZlGvHVA20auwKybq1:biklchy) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L28)):*
> ```objc
> template<int NumDigits = Eigen::Dynamic>
> typename GrayCodesMatrix<NumDigits>::type
> CalculateReflectedGrayCodes(int num_digits = NumDigits) {
> ```

FYI, having default arguments for both of `NumDigits` and `num_digits` allows a user to write `CalculateReflectedGrayCodes()` which causes a run-time error. Probably worth adding `DRAKE_DEMAND(num_digits >= 0)`?

---

*[drake/math/gray_code.h, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZk472FXB843K0dYmV:-KnZk472FXB843K0dYmW:bxb5imf) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L31)):*
> ```objc
>   int num_codes = num_digits <= 0 ? 0 : 1 << num_digits;
>   typename GrayCodesMatrix<NumDigits>::type gray_codes(num_codes, num_digits);
>   gray_codes.setZero();
> ```

BTW, this is not necessary since all elements will be overwritten below.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-Kmf0Sf87jIl43O7XEng:-Kmf0Sf87jIl43O7XEnh:b-ejcyj3) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e4e9862aa9be4891a801929deb4c491e7044af/drake/solvers/mixed_integer_optimization_util.h#L10)):*
> ```objc
> namespace solvers {
> /**
>  * Return ⌈log(n)⌉, namely the minimal integer no smaller than log2(n), with
> ```

BTW, nit, `⌈log(n)⌉` -> `⌈log₂(n)⌉`?

---

*[drake/solvers/mixed_integer_optimization_util.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-Kmf0Dbs5_Yqmhwjy9d8:-Kmf0Dbs5_Yqmhwjy9d9:bbgbog9) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e4e9862aa9be4891a801929deb4c491e7044af/drake/solvers/mixed_integer_optimization_util.h#L25)):*
> ```objc
>  * Return the k-digit reflected Gray codes.
>  * @param k The number of digits in the Gray code.
>  * @retval m m is a matrix of size 2ᵏ x k. m.row(i) is the Gray code for integer
> ```

BTW, nit, how about?
```
@retval m 2ᵏ x k integer matrix where m.row(i) is the Gray code for integer.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-KnZnxSB2FfDIbmtklgW:bnishpu)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 12 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZwJA_pJCgAP3XQ68U:-KnZwJA_pJCgAP3XQ68V:b-vgmumc) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/solvers/mixed_integer_optimization_util.h#L15)):*
> ```objc
>  * @return The minimal integer no smaller than log₂(n).
>  */
> constexpr int CeilLog2(int n) {
> ```

BTW, need `DRAKE_DEMAND(n > 0)`.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 34 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZtVd3mc_moMcMPJcK:-KnZtVd3mc_moMcMPJcL:bg8qnfy) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/solvers/mixed_integer_optimization_util.h#L34)):*
> ```objc
>  * @return y The newly added binary variables. The assignment of the binary
>  * variable y implies which two λ can be strictly positive.
>  * With an binary assignment on y, and suppose the integer M corresponds to
> ```

BTW, nit, `With an binary...` -> `With a binary...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-Kn_8K-Rf9-WwRw2q-ur:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/math/gray_code.h, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZkDTADySEqE_vDWxP:-KngEgJsREr5C59Sz8Tp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L8)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, better to have a short documentation for the type-trait?
</blockquote></details>

Done.

---

*[drake/math/gray_code.h, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZgsvHuJ6FCYbGuj-X:-KngExsej3bKuQO2r5gE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L9)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `1 << NumDigits` works as expected only if `1 <= NumDigits <= 30` holds (assuming `sizeof(int) = 4`). Can we add `static_assert` to enforce the precondition?
</blockquote></details>

Done.

---

*[drake/math/gray_code.h, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZlGvHVA20auwKybq0:-KngFqHXdpBY_wMWQ7so:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, having default arguments for both of `NumDigits` and `num_digits` allows a user to write `CalculateReflectedGrayCodes()` which causes a run-time error. Probably worth adding `DRAKE_DEMAND(num_digits >= 0)`?
</blockquote></details>

Done. 

---

*[drake/math/gray_code.h, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZk472FXB843K0dYmV:-KngG-Oi_DsbQ07Lgryz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/math/gray_code.h#L31)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this is not necessary since all elements will be overwritten below.
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZwJA_pJCgAP3XQ68U:-KngG5-KdSBnmIXJ1tA1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/solvers/mixed_integer_optimization_util.h#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, need `DRAKE_DEMAND(n > 0)`.
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 34 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZtVd3mc_moMcMPJcK:-KngG8Pn-HTzaIH-FSu7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/solvers/mixed_integer_optimization_util.h#L34)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, `With an binary...` -> `With a binary...`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-:-KngHb3lLFc_OEaYDs5M:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6337#-KnZwJA_pJCgAP3XQ68U:-KngNDes2Fwec3_5-T02:b41wg30) ([raw file](https://github.com/robotlocomotion/drake/blob/4426ab9322986d98cb2eacd1152a172bee318e8c/drake/solvers/mixed_integer_optimization_util.h#L15)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`constexpr` does not allow us adding `DRAKE_DEMAND` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6337)*

**Pull request merged**
