### PR TITLE
pydrake solvers: Add bindings for IbexSolver

### PR DESCRIPTION
**Pull request by mpetersen94**
Adds bindings for IbexSolver as well as some other changes to make it a more fleshed out SolverInterface.  Ibex still doesn't set solver details in MathematicalProgramResult.

Toward #15573 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@soonhokong for feature review

**Review by soonhokong — COMMENTED** [review]
+@soonhokong . Sorry for the delay. I plan to complete the first round by this evening (PDT).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793#-:-Mk8iCEu2rM1nPRqUTMl:b4c44tq)* status: LGTM missing from assignee soonhokong, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonhokong)

**Review by mpetersen94 — COMMENTED** [review]
No worries!  I just wanted to make sure I tagged the right account!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793#-:-Mk8lbMXEcI251w44uJM:bca7jva)* status: LGTM missing from assignee soonhokong, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonhokong)

**Review by soonhokong — COMMENTED** [review]
:lgtm: I think this is ready for platform-review.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793#-:-MkAjOaF0eAje4uU11nj:b-49d3e0)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mpetersen94)

___
*[tools/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkAiMBO6fbq9-cloE3U:-MkAiMBO6fbq9-cloE3V:b-vpprii) ([raw file](https://github.com/robotlocomotion/drake/blob/eca3b5892ba66e42b14d701d78908fcfb99516af/tools/BUILD.bazel#L96)):*
> ```Starlark
> )
> 
> # Ibex is an open-source solver, and is included in the Drake build by
> ```

Since ibex is a required dependency of dReal, in theory we should not allow the combination, `NO_IBEX=ON` + `NO_DREAL=OFF`. That is, `NO_IBEX=On` should imply `NO_DREAL=ON`. 

Also I think you need to update `tools/workspace/BUILD.bazel` file?

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonhokong)

___
*[tools/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkAiMBO6fbq9-cloE3U:-MkF37tn7QIbdEjt0YnI:buxn06t) ([raw file](https://github.com/robotlocomotion/drake/blob/eca3b5892ba66e42b14d701d78908fcfb99516af/tools/BUILD.bazel#L96)):*
<details><summary><i>Previously, soonhokong (Soonho Kong) wrote…</i></summary><blockquote>

Since ibex is a required dependency of dReal, in theory we should not allow the combination, `NO_IBEX=ON` + `NO_DREAL=OFF`. That is, `NO_IBEX=On` should imply `NO_DREAL=ON`. 

Also I think you need to update `tools/workspace/BUILD.bazel` file?
</blockquote></details>

So you need Ibex to have dReal, but is there ever a case where you would want Ibex but not dReal (i.e. `NO_IBEX=OFF` + `NO_DREAL=ON`)?  If not, I think I can eliminate `NO_IBEX` and have `NO_DREAL` toggle both.

**Review by soonhokong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mpetersen94)

___
*[tools/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkAiMBO6fbq9-cloE3U:-MkF5BGK6YuGgBp6JwR3:b-c5o44j) ([raw file](https://github.com/robotlocomotion/drake/blob/eca3b5892ba66e42b14d701d78908fcfb99516af/tools/BUILD.bazel#L96)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

So you need Ibex to have dReal, but is there ever a case where you would want Ibex but not dReal (i.e. `NO_IBEX=OFF` + `NO_DREAL=ON`)?  If not, I think I can eliminate `NO_IBEX` and have `NO_DREAL` toggle both.
</blockquote></details>

IbexSolver itself is an example of the case, and we want to use it in IRIS, https://github.com/RobotLocomotion/drake/blob/master/geometry/optimization/iris.h.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonhokong)

___
*[tools/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkAiMBO6fbq9-cloE3U:-MkFZX5M8lmx7HOqBGfL:b8mliyn) ([raw file](https://github.com/robotlocomotion/drake/blob/eca3b5892ba66e42b14d701d78908fcfb99516af/tools/BUILD.bazel#L96)):*
<details><summary><i>Previously, soonhokong (Soonho Kong) wrote…</i></summary><blockquote>

IbexSolver itself is an example of the case, and we want to use it in IRIS, https://github.com/RobotLocomotion/drake/blob/master/geometry/optimization/iris.h.
</blockquote></details>

Given the comment here: https://github.com/RobotLocomotion/drake/blob/master/solvers/BUILD.bazel#L735-L737 I've removed the `NO_IBEX` flag and have `NO_DREAL` control both. Done.

**Review by soonhokong — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mpetersen94)

**Comment by mpetersen94** [comment]
+@EricCousineau-TRI for platform review

**Review by jwnimmer-tri — COMMENTED** [review]
I'm already here checking on the build system integration, so might as well do platform review as well.

-@EricCousineau-TRI +@jwnimmer-tri for platform.

> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793#-:-MkI6phT20v3j6-iVYjy:b-bj2j9o)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @mpetersen94)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793#-:-MkI822L3ocHzzTSPh_b:b-vtj4vo)* status: 2 unresolved discussions (waiting on @mpetersen94)

___
*[bindings/pydrake/solvers/ibex_py.cc, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkI7DeD9KmraS3jl7Lh:-MkI7DeD9KmraS3jl7Li:b-2uxu87) ([raw file](https://github.com/robotlocomotion/drake/blob/35857b46048b9b753207ade06b63a11eeb4a3f02/bindings/pydrake/solvers/ibex_py.cc#L4)):*
> ```cpp
> #include "pybind11/pybind11.h"
> 
> #include "drake/bindings/pydrake/common/value_pybind.h"
> ```

nit Since we don't have `AddValueInstantiation<IbexSolverDetails>(m)` below, I don't think we need either `value_pybind.h` here, nor `import("pydrake.common.value")` below, nor ` "//bindings/pydrake/common:value_pybind"` nor `"//bindings/pydrake/common:value_py"` in the BUILD file?
___
*[bindings/pydrake/solvers/test/ibex_solver_test.py, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkI7Ufz3uaSLsJmIczA:-MkI7Ufz3uaSLsJmIczB:bbqmuw1) ([raw file](https://github.com/robotlocomotion/drake/blob/35857b46048b9b753207ade06b63a11eeb4a3f02/bindings/pydrake/solvers/test/ibex_solver_test.py#L11)):*
> ```Python
> 
> class TestIbexSolver(unittest.TestCase):
>     def test_scs_solver(self):
> ```

nit Typo `scs`.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonhokong (waiting on @jwnimmer-tri and @soonhokong)

___
*[bindings/pydrake/solvers/ibex_py.cc, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkI7DeD9KmraS3jl7Lh:-MkIAeeO9GmaaRAaxC7U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35857b46048b9b753207ade06b63a11eeb4a3f02/bindings/pydrake/solvers/ibex_py.cc#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Since we don't have `AddValueInstantiation<IbexSolverDetails>(m)` below, I don't think we need either `value_pybind.h` here, nor `import("pydrake.common.value")` below, nor ` "//bindings/pydrake/common:value_pybind"` nor `"//bindings/pydrake/common:value_py"` in the BUILD file?
</blockquote></details>

Done.
___
*[bindings/pydrake/solvers/test/ibex_solver_test.py, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15793#-MkI7Ufz3uaSLsJmIczA:-MkIAsG6EujlsKUp3ygN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35857b46048b9b753207ade06b63a11eeb4a3f02/bindings/pydrake/solvers/test/ibex_solver_test.py#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Typo `scs`.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15793)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonhokong (waiting on @mpetersen94)

**Pull request merged**
