### PR TITLE
Renamed AddRobotFromURDF* to be AddModelInstanceFromURDF*.

### PR DESCRIPTION
**Pull request by liangfok**
Per discussion with @sherm1, @amcastro-tri, and @david-german-tri yesterday, we are going with "Model Instance". I thus renamed some methods to reflect this new convention.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3049)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review (you're the only non-platform reviewer who attended yesterday's meeting)
+@sherm1 for platform review (it's not Monday but you have direct knowledge of yesterday's meeting)

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOGlWUdRt5gzUDvwDrM:1805021823)*

**Comment by sherm1** [comment]
:lgtm:. One suggested documentation clarification.

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/parser_urdf.h, line 41 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOGnQ5XBwsd3uw1XwcB:-KOGnQ5XBwsd3uw1XwcC:1372023484) ([raw file](https://github.com/robotlocomotion/drake/blob/96e9f2c0d3f6b1211986d6cf4adc2cf8303faa69/drake/systems/plants/parser_urdf.h#L41)):*
> ```objc
>     const tinyxml2::XMLElement* pose, const std::string& name);
> 
> /// Adds a URDF model to a rigid body system. The model is connected to the
> ```

BTW, perhaps clarify here that we read a single model from URDF and create a single model instance from it. (And in comments below too.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOGnfPl_FoYYnKNOYry:-1767369462)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.Thanks!

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/parser_urdf.h, line 41 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOGnQ5XBwsd3uw1XwcB:-KOHEJGat0LQKjCDlip3:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/96e9f2c0d3f6b1211986d6cf4adc2cf8303faa69/drake/systems/plants/parser_urdf.h#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, perhaps clarify here that we read a single model from URDF and create a single model instance from it. (And in comments below too.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOHEL4IVKbXXjVYqiCA:-277715022)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOIaS7-1dEOTExRoMEW:-696383545)*

**Comment by amcastro-tri** [comment]
A small comment. 

---

Reviewed 8 of 11 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/parser_urdf.h, line 53 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOKVHl72KJhjwGH2MGs:-KOKVHl72KJhjwGH2MGt:829510843) ([raw file](https://github.com/robotlocomotion/drake/blob/9f902ae5268eb8a6a1d50d22aabe82074dce49c6/drake/systems/plants/parser_urdf.h#L53)):*
> ```objc
> DRAKERBM_EXPORT
> void AddModelInstanceFromURDFString(
>     const std::string& urdf_string,
> ```

`urdf_string`? the name of this argument is not very descriptive. What about something like `model_name`? or just `model`?

---

*[drake/systems/plants/parser_urdf.h, line 72 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOKVSN4thova-MSwqK9:-KOKVSN4thova-MSwqKA:38259794) ([raw file](https://github.com/robotlocomotion/drake/blob/9f902ae5268eb8a6a1d50d22aabe82074dce49c6/drake/systems/plants/parser_urdf.h#L72)):*
> ```objc
> DRAKERBM_EXPORT
> void AddModelInstanceFromURDFString(
>     const std::string& urdf_string,
> ```

same comment about `urdf_string`, and in the methods below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOKWtJiJr8Exrt3KDMV:-1545124812)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 53 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOKVHl72KJhjwGH2MGs:-KOKv6A1tA4jLa38fasn:70259628) ([raw file](https://github.com/robotlocomotion/drake/blob/9f902ae5268eb8a6a1d50d22aabe82074dce49c6/drake/systems/plants/parser_urdf.h#L53)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> `urdf_string`? the name of this argument is not very descriptive. What about something like `model_name`? or just `model`?
</details>
This is the actual URDF text. I've updated the documentation to clarify this fact.

---

*[drake/systems/plants/parser_urdf.h, line 72 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOKVSN4thova-MSwqK9:-KOKw-E6S2YF_INF8jjd:70259628) ([raw file](https://github.com/robotlocomotion/drake/blob/9f902ae5268eb8a6a1d50d22aabe82074dce49c6/drake/systems/plants/parser_urdf.h#L72)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> same comment about `urdf_string`, and in the methods below.
</details>
This is the actual URDF text. I've updated the documentation to clarify this fact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOKw0c3X1TnvoY7ThAT:701515998)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/parser_urdf.h, line 53 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOKVHl72KJhjwGH2MGs:-KOL3wM2OuYGpF8n4ItG:-944384348) ([raw file](https://github.com/robotlocomotion/drake/blob/9f902ae5268eb8a6a1d50d22aabe82074dce49c6/drake/systems/plants/parser_urdf.h#L53)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This is the actual URDF text. I've updated the documentation to clarify this fact.
</details>
my bad, I see. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOL41mYnPIKxVTCrAsV:1417088721)*

**Comment by liangfok** [comment]
Thanks. I updated the URDF Doxygen comments for consistency. Just waiting on CI now before merge.

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/parser_urdf.h, line 53 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-KOKVHl72KJhjwGH2MGs:-KOL5vOU0g2yMgFRUsUl:-1919080311) ([raw file](https://github.com/robotlocomotion/drake/blob/9f902ae5268eb8a6a1d50d22aabe82074dce49c6/drake/systems/plants/parser_urdf.h#L53)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> my bad, I see. 
</details>
No worries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3049#-:-KOL5pjQgZHpNuZpNSbA:1896335814)*

**Pull request merged**
