### PR TITLE
[workspace] Upgrade crate_universe to latest

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20814)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/crate_universe/lock/archives.bzl` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20814#-NoxTiglDKR2qUDaHyyK:-NoxTiglDKR2qUDaHyyL:b-jgkdtg) ([raw file](https://github.com/RobotLocomotion/drake/blob/a56a933887140f6647be2458b3b3630c762fc46c/tools/workspace/crate_universe/lock/archives.bzl#L2)):*
> ```Starlark
> # This file is automatically generated by upgrade.sh.
> ARCHIVES = [,
> ```

@jwnimmer-tri, looks like the inscrutable perl script that generated this file botched something. I... am not even sure how this file is generated; it *looks* from the script like it should be based on `details/defs.bzl`, but the contents bear no resemblance to that. Nor do I see where this text might originate. Thoughts?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20814)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/crate_universe/lock/archives.bzl` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20814#-NoxTiglDKR2qUDaHyyK:-Noy8BL9DMjkymTfOhl-:blm2kx3) ([raw file](https://github.com/RobotLocomotion/drake/blob/a56a933887140f6647be2458b3b3630c762fc46c/tools/workspace/crate_universe/lock/archives.bzl#L2)):*
I pushed a fix to the perl script.

The the perl continues to tip over during future upgrades, I'll need to rewrite it in a real parser like tree-sitter or something.

> ... it _looks_ from the script like it should be based on `details/defs.bzl`, but the contents bear no resemblance to that.

The crate repin generates a `defs.bzl` which we fork into `archives.bzl`, and then we in-place edit _both_ the `defs.bzl` and the `archives.bzl` to de-duplicate them.

**Comment by jwnimmer-tri** [comment]
:lgtm: as co-feature / co-author.

+@EricCousineau-TRI for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20814)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/crate_universe/lock/archives.bzl` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20814#-NoxTiglDKR2qUDaHyyK:-Noy9_tm5ouL_OhoKaYT:b-c8o593) ([raw file](https://github.com/RobotLocomotion/drake/blob/a56a933887140f6647be2458b3b3630c762fc46c/tools/workspace/crate_universe/lock/archives.bzl#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I pushed a fix to the perl script.

The the perl continues to tip over during future upgrades, I'll need to rewrite it in a real parser like tree-sitter or something.

> ... it _looks_ from the script like it should be based on `details/defs.bzl`, but the contents bear no resemblance to that.

The crate repin generates a `defs.bzl` which we fork into `archives.bzl`, and then we in-place edit _both_ the `defs.bzl` and the `archives.bzl` to de-duplicate them.
</blockquote></details>

typo -- I meant to say: _If*_ the perl continues to...

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: feature (Jeremy's fixes), waiting on Eric...

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20814#-:-Np151-v9Cf3jRIfJyri:b-jnlzr6)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/crate_universe/lock/archives.bzl` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20814#-NoxTiglDKR2qUDaHyyK:-Np14bTq9gzondskU1tJ:b9y4ebq) ([raw file](https://github.com/RobotLocomotion/drake/blob/a56a933887140f6647be2458b3b3630c762fc46c/tools/workspace/crate_universe/lock/archives.bzl#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo -- I meant to say: _If*_ the perl continues to...
</blockquote></details>

Ah, I missed that `details/defs.bzl` *also* gets carved up...

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 35 of 36 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20814#-:-Np1UclW1BqMBH0fWKRJ:bcpz082)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Pull request merged**
