### PR TITLE
Add SOS to MathematicalProgram

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6586)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

+@fischergundlach , could you also feature-review it? Esp, please check the documentation part.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-:-KpHe3vetISwhsQWHsLg:b-23jrm0)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 599 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHgxjgE1qPxjWx4VCa:-KpHgxjgE1qPxjWx4VCb:b-kgq1le) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.cc#L599)):*
> ```cpp
> MathematicalProgram::AddSosConstraint(const symbolic::Polynomial& p) {
>   const symbolic::Variables indeterminates{p.indeterminates()};
>   const auto pair = NewSosPolynomial(indeterminates, p.TotalDegree());
> ```

With the current implementation, I think we should use `std::Ceil(p.TotalDegree() / 2)` instead of `p.TotalDegree()`;

---

*[drake/solvers/mathematical_program.h, line 516 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHf2pR29icDPbBhq-z:-KpHf2pSv3W_ZFRbso0a:b-nuaclp) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.h#L516)):*
> ```objc
>    * of @p degree. For example, `NewSosPolynomial({x}, 2)` returns a pair of a
>    * polynomial p = Q₍₀,₀₎x⁴ + 2Q₍₁,₀₎ x³ + (2Q₍₂,₀₎ + Q₍₁,₁₎)x² + 2Q₍₂,₁₎x +
>    * Q₍₂,₂₎ and a PSD constraint over Q.
> ```

We should say what `degree` means here. I think here you mean if `degree = d`, then the returned polynomial has highest degree as `2d`. I actually think that it makes more sense to say that `degree` is the highest degree of the returned polynomial. So `degree` should be a positive even integer, and we will throw a runtime error if it is not.

---

*[drake/solvers/test/sos_constraint_test.cc, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHhSmvFG77d4c__jQp:-KpHhSmvFG77d4c__jQq:b-xaz1lu) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L183)):*
> ```cpp
>                          pow(x0, 2) * pow(x1, 2) + 5 * pow(x1, 4));
>   const auto result = prog_.Solve();
>   EXPECT_EQ(result, SolutionResult::kSolutionFound);
> ```

Extract the value of the psd matrix `Q`, and then check that matrix has all eigen values as non-negatives? Otherwise even if `AddSosConstraint` does nothing, this test still passes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by FischerGundlach** [comment]
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 599 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHgxjgE1qPxjWx4VCa:-KpKxyGn7GFdjyta0a7k:bb2im99) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.cc#L599)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

With the current implementation, I think we should use `std::Ceil(p.TotalDegree() / 2)` instead of `p.TotalDegree()`;
</blockquote></details>

I do think, we should cut the degree into half BUT I think we should use `floor`. The idea is, if the degree is odd it can't be an SOS anyway, thus we do lose feasible solutions, but move the problem from the solver (which will say it is infeasible) to the parsing step of equating the polynomial. This gives us the ability to intervene and give a warning/error instead of the ambiguous "infeasible problem" report by the solver.  

ps: it's not my idea, but what is used in spot. 

---

*[drake/solvers/mathematical_program.h, line 516 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHf2pR29icDPbBhq-z:-KpL2iLXQj3LntC1EtpD:bb6mt9b) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.h#L516)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We should say what `degree` means here. I think here you mean if `degree = d`, then the returned polynomial has highest degree as `2d`. I actually think that it makes more sense to say that `degree` is the highest degree of the returned polynomial. So `degree` should be a positive even integer, and we will throw a runtime error if it is not.
</blockquote></details>

:+1:

---

*[drake/solvers/mathematical_program.h, line 1790 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpL4F6cw5I-oU_Fey_t:-KpL4F6dro4K5d6OutSp:bbpzpz7) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.h#L1790)):*
> ```objc
>    * constraint bindings expressing:
>    *  - The coefficient matrix Q is PSD (positive semidefinite).
>    *  - The coefficient matching conditions in linear equality constraint.
> ```

coefficientS

---

*[drake/solvers/test/sos_constraint_test.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpLB4ltT8XtkhGBmQAJ:-KpLB4luCNkkEzIxDH6V:bb23j6w) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L53)):*
> ```cpp
>     const drake::VectorX<symbolic::Monomial> monomial_basis{
>         symbolic::MonomialBasis(indeterminates, degree)};
>     EXPECT_EQ(p.TotalDegree(), degree * 2);
> ```

If we change the parameter `degree` in `NewSosPolynoial`, this test needs to be adapted accordingly. 

---

*[drake/solvers/test/sos_constraint_test.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpL8uaVrn-Y30ortfZk:-KpL8uaWylMeWV8jKjIm:bkn3llo) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L63)):*
> SetUp
this function appears to be unused. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 599 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHgxjgE1qPxjWx4VCa:-KpLTxcBogVxipwLvXKN:b-xxrgid) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.cc#L599)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

I do think, we should cut the degree into half BUT I think we should use `floor`. The idea is, if the degree is odd it can't be an SOS anyway, thus we do lose feasible solutions, but move the problem from the solver (which will say it is infeasible) to the parsing step of equating the polynomial. This gives us the ability to intervene and give a warning/error instead of the ambiguous "infeasible problem" report by the solver.  

ps: it's not my idea, but what is used in spot. 
</blockquote></details>

Yes you are right, we should use floor instead of ceil.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 599 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHgxjgE1qPxjWx4VCa:-KpLay0cTdAUR5qKksid:b-ke0rgu) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.cc#L599)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes you are right, we should use floor instead of ceil.
</blockquote></details>

With the changes in `NewSosPolynomial`, I think we can keep this line as it is.

---

*[drake/solvers/mathematical_program.h, line 516 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHf2pR29icDPbBhq-z:-KpKDbRIepcNlW4Wt7FV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.h#L516)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We should say what `degree` means here. I think here you mean if `degree = d`, then the returned polynomial has highest degree as `2d`. I actually think that it makes more sense to say that `degree` is the highest degree of the returned polynomial. So `degree` should be a positive even integer, and we will throw a runtime error if it is not.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1790 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpL4F6cw5I-oU_Fey_t:-KpLblVDTf3veBXABDJQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/mathematical_program.h#L1790)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

coefficientS
</blockquote></details>

Done.

---

*[drake/solvers/test/sos_constraint_test.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpLB4ltT8XtkhGBmQAJ:-KpLbojtrjaLMG9la4Xa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L53)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

If we change the parameter `degree` in `NewSosPolynoial`, this test needs to be adapted accordingly. 
</blockquote></details>

Done.

---

*[drake/solvers/test/sos_constraint_test.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpL8uaVrn-Y30ortfZk:-KpLbqI_-iTtqrvpIpqs:b-uusfbo) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L63)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

> SetUp
this function appears to be unused. 
</blockquote></details>

`SetUp` function is invoked by gtest internally. For more information, please check https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#test-fixtures-using-the-same-data-configuration-for-multiple-tests.

---

*[drake/solvers/test/sos_constraint_test.cc, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHhSmvFG77d4c__jQp:-KpLbpVPDLcGLI7juLsG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L183)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Extract the value of the psd matrix `Q`, and then check that matrix has all eigen values as non-negatives? Otherwise even if `AddSosConstraint` does nothing, this test still passes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/sos_constraint_test.cc, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHhSmvFG77d4c__jQp:-KpLckNdhrgRLMWCuHXU:bjb71sk) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L183)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI, I've added the eigen-value test in `CheckNewSosPolynomial` function above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/sos_constraint_test.cc, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-KpHhSmvFG77d4c__jQp:-KpLp_dGzlsmoQ5uqEXP:bmb3vq6) ([raw file](https://github.com/robotlocomotion/drake/blob/3e72f1dd6737b4f8ccde603c60e848d4adc0a290/drake/solvers/test/sos_constraint_test.cc#L183)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, I've added the eigen-value test in `CheckNewSosPolynomial` function above. 
</blockquote></details>

Added in `AddSosConstraint*` tests as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-:-KpLsgPFlFeY2y7o8rEK:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586)*

**Comment by FischerGundlach** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-:-KpLtB5jCc7PRBZiste7:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sammy-tri, platform-review please! Thank you.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-:-KpLtszxczm8dUoo4slv:b-wjo5nl)*

**Comment by sammy-tri** [comment]
:lgtm: (with much thanks for an extra feature review!)

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6586#-:-KpMeVd-fb4R32IB9DuB:bddngb5)*

**Pull request merged**
