### PR TITLE
Always use shared liblcm library

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6464.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7423)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This passes some local testing and visual install inspection, but still fails some bindings tests.  I want to get some CI while I also fix that.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for platform review per schedule and apple testing, please.

**Comment by soonho-tri** [comment]
:lgtm:

> and apple testing, please.

It works as expected on a mac: `libdrake.so` includes an entry `@loader_path/liblcm.so` and there is `lib/liblcm.so` in the install location.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/lcm/lcm.BUILD.bazel, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7423#-KyVTpXqJn82aLhd3o1b:-KyVTpXqJn82aLhd3o1c:b6fvyom) ([raw file](https://github.com/robotlocomotion/drake/blob/566946f72a32b0b236515068bff8c4ade199ef54/tools/workspace/lcm/lcm.BUILD.bazel#L90)):*
Could you explain why we need `linkstatic = 1` for my education? It seems to contradict the following sentence (in the comment section above):
>  ... because its LGPL-licensed and thus should never be linked statically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7423#-:-KyVY9F_93iDiz_q84NT:b9awwt9)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/lcm/lcm.BUILD.bazel, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7423#-KyVTpXqJn82aLhd3o1b:-KyVbGutNCMKMdLsrctq:b-bj9mio) ([raw file](https://github.com/robotlocomotion/drake/blob/566946f72a32b0b236515068bff8c4ade199ef54/tools/workspace/lcm/lcm.BUILD.bazel#L90)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you explain why we need `linkstatic = 1` for my education? It seems to contradict the following sentence (in the comment section above):
>  ... because its LGPL-licensed and thus should never be linked statically.
</blockquote></details>

OK See https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary description of `linkshared` attribute.  When creating a shared library, linkstatic says whether or not our non-system `deps` libraries are linked in statically or dynamically.  Since we don't have any non-system deps here, it's probably confusing to set this.  Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7423)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/lcm/lcm.BUILD.bazel, line 256 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7423#-KyVsPwjBuUz58R2dbID:-KyVsPwjBuUz58R2dbIE:b-6fvogj) ([raw file](https://github.com/robotlocomotion/drake/blob/53e6414cb26abc12b0722cdd789e4ff6f745b9c7/tools/workspace/lcm/lcm.BUILD.bazel#L256)):*
> ```
>     name = "install",
>     targets = [
>         ":liblcm.so",
> ```

BTW Alphabetize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7423#-:-KyVsY6Zv1EjwBxpc4Ei:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7423)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7423#-KyWOeSR3tO9-nsWtWYO:-KyWOeSSiNcHPobNMu3e:bdnicx9) (no related file):*
Do not merge.  We will let #7419 go in first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7423)*

**Pull request merged**
