### PR TITLE
Rotation matrix project with axis

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5686)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-:-KgbsSkNTdVzcukYz2Rf:b-sriflu)*

**Comment by RussTedrake** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/math/rotation_matrix.h, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzM_CHN7fnqlw-zIpi:-KhzM_CHN7fnqlw-zIpj:b-1awr31) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L255)):*
> ```objc
> 
> /**
>  * Projects a 3 x 3 matrix `M` onto so(3), the projected rotation matrix `R`
> ```

caps: SO(3)

period (and new sentence) after SO(3)?

---

*[drake/math/rotation_matrix.h, line 271 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzMsB58ndoobJbGT7g:-KhzMsB58ndoobJbGT7h:batpr2e) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L271)):*
> ```objc
>  * </pre>
>  * Equation (1) is the Rodriguez Formula, to compute the rotation matrix from
>  * the rotation anxis `a` and the rotation angle θ. For more details, refer to
> ```

type: axis

---

*[drake/math/rotation_matrix.h, line 277 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzMzrNY16MdaGUE3q2:-KhzMzrNY16MdaGUE3q3:b-7wuzq0) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L277)):*
> ```objc
>  *   max_θ trace(Rᵀ * M + Mᵀ * R)
>  * </pre>
>  * By substituting the matrix `R` with the angle-axis representation, the
> ```

axis-angle (instead of angle-axis)?

---

*[drake/math/rotation_matrix.h, line 286 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzOTNqXC-ApIiWbZS9:-KhzOTNqXC-ApIiWbZSA:b193mwh) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L286)):*
> ```objc
>  * optimal θ as
>  * <pre>
>  * θ = π/2 - α, if angle_lb <= π/2 - α <= angle_ub
> ```

i see, but you have to check this at - 5pi/2 and 5pi/2 also.  and even -9pi/2, 9pi/2?

---

*[drake/math/rotation_matrix.h, line 299 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzNDMKFscu_maE-HlL:-KhzNDMKFscu_maE-HlM:b1ars3m) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L299)):*
> ```objc
>  * @pre angle_lb >= -2π, angle_ub <= 2π. angle_ub >= angle_lb.
>  * Throw std::runtime_error if these bounds are violated.
>  */
> ```

The math seems clear enough.  But I don't understand yet why I would want this?  Why constrain the axis, and search only for angle?

Ah! (after reading to the end).  The example in global IK now makes it very clear.  Perhaps it's worth mentioning that here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/math/rotation_matrix.h, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzM_CHN7fnqlw-zIpi:-Khzfj94L9D_KfEjRbuh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L255)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

caps: SO(3)

period (and new sentence) after SO(3)?
</blockquote></details>

Done.

---

*[drake/math/rotation_matrix.h, line 271 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzMsB58ndoobJbGT7g:-KhzfmULZeGy94fPLC0p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L271)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

type: axis
</blockquote></details>

Done.

---

*[drake/math/rotation_matrix.h, line 277 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzMzrNY16MdaGUE3q2:-Khzfr5nkMycH-Zl6qI0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L277)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

axis-angle (instead of angle-axis)?
</blockquote></details>

Done.

---

*[drake/math/rotation_matrix.h, line 286 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzOTNqXC-ApIiWbZS9:-KhzftMSy17xK4-whHgE:bvi5765) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L286)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i see, but you have to check this at - 5pi/2 and 5pi/2 also.  and even -9pi/2, 9pi/2?
</blockquote></details>

Done. We actually checked -1.5pi and 2.5pi in the code. Add it to the documentation.

---

*[drake/math/rotation_matrix.h, line 299 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzNDMKFscu_maE-HlL:-KhzgEJe42prh4Up1Lb5:bmheyek) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L299)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The math seems clear enough.  But I don't understand yet why I would want this?  Why constrain the axis, and search only for angle?

Ah! (after reading to the end).  The example in global IK now makes it very clear.  Perhaps it's worth mentioning that here?
</blockquote></details>

Done. Add it to the documentation on the top.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/rotation_matrix.h, line 286 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-KhzOTNqXC-ApIiWbZS9:-Ki-UGLzIx4a27vkqbxU:be4880e) ([raw file](https://github.com/robotlocomotion/drake/blob/a6e1ed3ed069d8de53c6cefab94f7fb4ff836de8/drake/math/rotation_matrix.h#L286)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. We actually checked -1.5pi and 2.5pi in the code. Add it to the documentation.
</blockquote></details>

i think you check 4 numbers (i=-2:1 inclusive?) in the code... so -3.5pi, -1.5pi, 0.5pi, 2.5pi.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-:-Ki-UyKtWwBuvN3cXSIM:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-:-Ki0ei0kq8zkh2u2rZgF:b-1zm1j3)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

:lgtm: (pending outstanding issues, and with a lot of faith in the feature review)

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/rotation_matrix.h, line 258 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-Ki0yytEIVyMMvPFNftQ:-Ki0yytFo9pIZS1XsE6z:b7fpjy1) ([raw file](https://github.com/robotlocomotion/drake/blob/02235297c978bd5231869ad250d4d006bd1b06da/drake/math/rotation_matrix.h#L258)):*
> ```objc
>  * has a given rotation axis `a`, and its rotation angle θ is bounded as
>  * angle_lb <= θ <= angle_ub. One use case for this function is to reconstruct
>  * the rotation matrix for a revolute joint of with joint limits.
> ```

"of with joint limits" is an odd construction

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-:-Ki0x98S9aFc3ri3ppa2:b5n9zi1)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/rotation_matrix.h, line 258 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-Ki0yytEIVyMMvPFNftQ:-Ki11e-_4iIkEkhwJrIu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/02235297c978bd5231869ad250d4d006bd1b06da/drake/math/rotation_matrix.h#L258)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"of with joint limits" is an odd construction
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5686#-:-Ki1K60P_xH-mbnJeDoT:b-l70wzf)*

**Pull request merged**
