### PR TITLE
DirectTranscription class supports continuous-time MultibodyPlant

### PR DESCRIPTION
**Pull request by RussTedrake**
It turns out that it actually DID support it already, but there were some old DRAKE_DEMANDs that were erroneously blocking the execution.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14840)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14840#-:-MWzzz_36qXf9kmkYzu9:b-n689ep)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  +@ericcousineau-tri for platform review please (although it has passed 5pm at Eastern time).

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14840#-:-MX-JNJn8o2BnAGnOHnw:b-gs6ry1)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14840#-:-MX-yxmi9GEtsTiBLXkM:b-v6scke)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @RussTedrake)

___
*[systems/trajectory_optimization/direct_transcription.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14840#-MX-yH2v9gdONM6WIbmO:-MX-yH2wAjN9y_vv7Dp1:b4lzdmz) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/systems/trajectory_optimization/direct_transcription.cc#L210)):*
> ```cpp
>       discrete_time_system_(false) {
>   DRAKE_DEMAND(context.has_only_continuous_state());
>   DRAKE_DEMAND(system->num_input_ports() <= 1);
> ```

This change seems outside the scope of this PR ("supports continuous time"), and I'm not sure if I see test coverage which shows that `num_input_ports() >= 2` works.
(I guess I don't know if discrete -> continuous introduces ports?)

Is it possible to either add that test and update the commit message?
Or could you restore this line?

**Comment by EricCousineau-TRI** [comment]
___
*[systems/trajectory_optimization/direct_transcription.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14840#-MX-yH2v9gdONM6WIbmO:-MX0-0Fg2Kfh6AWrxyS8:bnn0izf) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/systems/trajectory_optimization/direct_transcription.cc#L210)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This change seems outside the scope of this PR ("supports continuous time"), and I'm not sure if I see test coverage which shows that `num_input_ports() >= 2` works.
(I guess I don't know if discrete -> continuous introduces ports?)

Is it possible to either add that test and update the commit message?
Or could you restore this line?
</blockquote></details>

Confirmed that the unittest still passes as is if I restore this line:
```
$ git log -n 1 --oneline --no-decorate
c2ee8ec51f DirectTranscription class supports continuous-time MultibodyPlant
$ git diff
diff --git a/systems/trajectory_optimization/direct_transcription.cc b/systems/trajectory_optimization/direct_transcription.cc
index 04593853f4..68ac82561b 100644
--- a/systems/trajectory_optimization/direct_transcription.cc
+++ b/systems/trajectory_optimization/direct_transcription.cc
@@ -207,6 +207,7 @@ DirectTranscription::DirectTranscription(
                        fixed_timestep.value),
       discrete_time_system_(false) {
   DRAKE_DEMAND(context.has_only_continuous_state());
+  DRAKE_DEMAND(system->num_input_ports() <= 1);
   DRAKE_DEMAND(fixed_timestep.value > 0.0);
   if (context.num_input_ports() > 0) {
     DRAKE_DEMAND(num_inputs() == get_input_port_size(system, input_port_index));
$ bazel run //systems/trajectory_optimization:direct_transcription_test
...
[  PASSED  ] 9 tests.
```

**Comment by EricCousineau-TRI** [comment]
You want me to make the adjustment (e.g. reset the line for `num_input_ports()`)? Or hack out a quick test which shows it works?
(I'm also fine if you'd like for me to lessen my review strictness)

**Comment by RussTedrake** [comment]
___
*[systems/trajectory_optimization/direct_transcription.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14840#-MX-yH2v9gdONM6WIbmO:-MX9kjOF-BhrSIGsfBqn:b-hm6cpj) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/systems/trajectory_optimization/direct_transcription.cc#L210)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I don't understand.  MultibodyPlant has >1 input port.  The test should definitely cover this case.
</blockquote></details>

I've added the line back in and confirmed that my test fails.  Not sure what your git lines are doing, but either I don't understand your complaint or your testing isn't doing what you think?

**Comment by RussTedrake** [comment]
___
*[systems/trajectory_optimization/direct_transcription.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14840#-MX-yH2v9gdONM6WIbmO:-MX9lXVtAf5K4anWJnQO:bjefz8w) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/systems/trajectory_optimization/direct_transcription.cc#L210)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I've added the line back in and confirmed that my test fails.  Not sure what your git lines are doing, but either I don't understand your complaint or your testing isn't doing what you think?
</blockquote></details>

your git diff suggests that you don't have the change to direct_transcription_test locally?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14840#-:-MX9n5ou6DrSP4ya7bob:bnfp4nl)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[systems/trajectory_optimization/direct_transcription.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14840#-MX-yH2v9gdONM6WIbmO:-MX9lxFmDm9hFhJcBs5B:b-ev0xnu) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/systems/trajectory_optimization/direct_transcription.cc#L210)):*
I thought this would indicate that I do have the changes?
```
$ git log -n 1 --oneline --no-decorate
c2ee8ec51f DirectTranscription class supports continuous-time MultibodyPlant
```
(can point to branch if you want)

> I've added the line back in and confirmed that my test fails. Not sure what your git lines are doing, but either I don't understand your complaint or your testing isn't doing what you think?

Huh... I don't get that.

The reason I'm confused is that the existing test already used MultibodyPlant, so MBP isn't a new factor? (it's only the fact that you're using discrete time?)

My concern still stands as-is, but but I def. won't block.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14840)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @RussTedrake)

___
*[systems/trajectory_optimization/direct_transcription.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14840#-MX-yH2v9gdONM6WIbmO:-MX9njEjCN000UgI7Qju:b-mj378f) ([raw file](https://github.com/robotlocomotion/drake/blob/e7cbc86885e2f20e43bb8c336583ef66c95c2976/systems/trajectory_optimization/direct_transcription.cc#L210)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I thought this would indicate that I do have the changes?
```
$ git log -n 1 --oneline --no-decorate
c2ee8ec51f DirectTranscription class supports continuous-time MultibodyPlant
```
(can point to branch if you want)

> I've added the line back in and confirmed that my test fails. Not sure what your git lines are doing, but either I don't understand your complaint or your testing isn't doing what you think?

Huh... I don't get that.

The reason I'm confused is that the existing test already used MultibodyPlant, so MBP isn't a new factor? (it's only the fact that you're using discrete time?)

My concern still stands as-is, but but I def. won't block.
</blockquote></details>

OK Ah. Snopt :facepalm: Redacting my statement, sorry!

**Comment by EricCousineau-TRI** [comment]
FTR I should've added `--config=snopt` to my `bazel test` command (or looked up in the source file). Then I would've repro'd the error.

**Pull request merged**
