### PR TITLE
Add qhull submodule

### PR DESCRIPTION
**Pull request by hongkai-dai**
This PR is actually done by @jamiesnape , thanks Jamie.

It does not have a bazel build yet, will add it in a separate PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5336)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/modules/FindQhull.cmake, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5336#-Ke020SQLX4hLJPoXorB:-Ke020SQLX4hLJPoXorC:bhkiryi) ([raw file](https://github.com/robotlocomotion/drake/blob/5bd64871ef4d390570d1e85935f4aa0084f1f437/cmake/modules/FindQhull.cmake#L140)):*
> ```CMake
>     set_target_properties(Qhull::qhullcpp PROPERTIES
>       IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
>       INTERFACE_INCLUDE_DIRECTORIES "${QHULLCPP_INCLUDE_DIR}")
> ```

```
INTERFACE_INCLUDE_DIRECTORIES "${QHULLCPP_INCLUDE_DIR}"
INTERFACE_LINK_LIBRARIES Qhull::qhull)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5336)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/modules/FindQhull.cmake, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5336#-Ke020SQLX4hLJPoXorB:-Ke04hu8YZ6CLKHKbOb4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5bd64871ef4d390570d1e85935f4aa0084f1f437/cmake/modules/FindQhull.cmake#L140)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

```
INTERFACE_INCLUDE_DIRECTORIES "${QHULLCPP_INCLUDE_DIR}"
INTERFACE_LINK_LIBRARIES Qhull::qhull)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5336)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@hongkai-dai This PR proposed to add CMakeLists support for a new library.  That does not seem relevant anymore.  Can this be closed?

**Pull request closed without merging**
