### PR TITLE
Remove linkstatic boilerplate.

### LINKED ISSUE #5104: Bazel "linkstatic" should be de-boilerplated
We should zap `linkstatic = 1` throughout Drake, then add back the ones that are actually necessary, with explanatory comments.

### PR DESCRIPTION
**Pull request by david-german-tri**
Follows up on #5155.

Fixes #5104.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5157)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 16 of 39 files at r1.
Review status: 16 of 39 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-KctHQZVQQmJCuJYOWqY:-KctHQZVQQmJCuJYOWqZ:bw1vpip) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ddcfec594e472d9e468e991c17940ff69543c0/drake/lcmtypes/BUILD#L12)):*
> ```Python
>     lcm_package = "drake",
>     lcm_srcs = ["lcmt_body_acceleration.lcm"],
>     linkstatic = 1,
> ```

_Meta_ the lcm_cc_library does not use `drake_cc_library` so is missing the new default.  I think that's the correct call graph (because we don't want Drake warnings in generated code), but this PR ends up removing `linkstatic = 1` on these libraries, which is perhaps not intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by jwnimmer-tri** [comment]
Reviewed 23 of 39 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by david-german-tri** [comment]
Review status: 39 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-KctHQZVQQmJCuJYOWqY:-KctJB4QFOu2Gs881bhU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ddcfec594e472d9e468e991c17940ff69543c0/drake/lcmtypes/BUILD#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ the lcm_cc_library does not use `drake_cc_library` so is missing the new default.  I think that's the correct call graph (because we don't want Drake warnings in generated code), but this PR ends up removing `linkstatic = 1` on these libraries, which is perhaps not intended?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/lcmtypes/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-KctHQZVQQmJCuJYOWqY:-KctJbhn-CSpH49m-VGO:bqa26gv) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ddcfec594e472d9e468e991c17940ff69543c0/drake/lcmtypes/BUILD#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, should `tools/bot_core_lcmtypes.BUILD` should drop its `linkstatic = 1` now, since its just repeating the default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/lcmtypes/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-KctHQZVQQmJCuJYOWqY:-KctJl37_WotmmVf0Gqf:b-lg5wwt) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ddcfec594e472d9e468e991c17940ff69543c0/drake/lcmtypes/BUILD#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm, should `tools/bot_core_lcmtypes.BUILD` should drop its `linkstatic = 1` now, since its just repeating the default?
</blockquote></details>

Ditto for `tools/robotlocomotion_lcmtypes.BUILD`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-:-KctJqN_KVqMZOSiruTb:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-KctHQZVQQmJCuJYOWqY:-KctK0eMDuiL1auRCyl9:b-ufi5nn) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ddcfec594e472d9e468e991c17940ff69543c0/drake/lcmtypes/BUILD#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto for `tools/robotlocomotion_lcmtypes.BUILD`.
</blockquote></details>

Maybe.  That boilerplate is far less contagious, so I'm inclined to leave it for a followup (if at all).  I think it's a good thing this PR doesn't touch `tools/` at all, since many of the `linkstatic` in there remain necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/lcmtypes/BUILD, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5157#-KctHQZVQQmJCuJYOWqY:-KctKVBpK9Ip2qh6WxUQ:b-ltjseu) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ddcfec594e472d9e468e991c17940ff69543c0/drake/lcmtypes/BUILD#L12)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Maybe.  That boilerplate is far less contagious, so I'm inclined to leave it for a followup (if at all).  I think it's a good thing this PR doesn't touch `tools/` at all, since many of the `linkstatic` in there remain necessary.
</blockquote></details>

Find by me.  If we ever change lcm.bzl to choose a different library type, we'll have to correct those two files also, but we'll probably remember and/or catch it in PR review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5157)*

**Pull request merged**
