### PR TITLE
Allow System2 LCM translators to specify output vector subclasses

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In a future PR, this will be used by the `Cars` vector classes, so that LCM message inputs such as `DrivingCommand` can be used by `SimpleCar` using `get_steering_angle` instead of `GetAtIndex(0)`.

See commit history for details of the edits.  In particular, the first two commits are functionality-neutral.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3301)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.
+@david-german-tri for platform review, please.

**Comment by liangfok** [comment]
Checking in a partial review here. I'll look at it in more detail tomorrow morning.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQOQ7NHVZxjFvrsj8fN:-KQOQ7NIlAG7BJR5bZWw:b-3b28er) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L82)):*
> ```objc
>  protected:
>   std::unique_ptr<VectorBase<double>> AllocateOutputVector(
>       const SystemPortDescriptor<double>& descriptor) const override;
> ```

Add documentation here stating that `descriptor.get_index()` must equal zero.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-:-KQOR08IDIKBwmK_Nifa:bcm7sv)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/lcm/lcm_subscriber_system.h, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQOQ7NHVZxjFvrsj8fN:-KQQDcRTgjjPa_Dmp-dL:b6ci02b) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L82)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Add documentation here stating that `descriptor.get_index()` must equal zero.
</details>
To me, that's implied by the `LeafSystem` contact, though not actually written down.

Instead of commenting here, what if I add a comment on the `LeafSystem` base declaration for this method: that only descriptors given to to`DeclareOutputPort` will ever appear here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by liangfok** [comment]
Done with first pass of feature review. PTAL.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQcSuX_-2ZgEtU5z8L:-KQQcSuX_-2ZgEtU5z8M:bqyzlsp) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_and_vector_base_translator.h#L37)):*
> ```objc
>    * Allocates the vector storage for an output port of our LCM message type,
>    * in case special storage is needed.  If the result is nullptr, a default
>    * BasicVector will be used.
> ```

This comment is a bit unclear w.r.t _who_ will create and use the `BasicVector`when the return value is `nullptr`. Perhaps clarify that it is the `LcmSubscriberSystem` that will allocate and use a `BasicVector`?

Or, even better, make this method _not_ virtual and have it call a protected virtual`AllocateOutputVectorImpl()`method that returns `nullptr`. Subclasses can override this method to return non-`nullptr` values.

The, the logic for checking for a `nullptr` return value and creating a `BasicVector` object can be in this method's implementation instead of within `LcmSubscriberSystem`.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQfUWafayXfc2RoNi6:-KQQfUWafayXfc2RoNi7:bpp6bsw) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L73)):*
> ```objc
>    * values for `EvalOutput`.  However, if `LCM` is not providing any message
>    * data (e.g., in a unit test, or if the channel is not being published
>    * during a simulation), this method can be used to provide a value.
> ```

BTW: nit: Replace "provide a value" to "force a particular EvalOutput value".

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQOQ7NHVZxjFvrsj8fN:-KQQfrDbLNUgOhjGvF8e:bitlab5) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> To me, that's implied by the `LeafSystem` contact, though not actually written down.
> 
> Instead of commenting here, what if I add a comment on the `LeafSystem` base declaration for this method: that only descriptors given to to`DeclareOutputPort` will ever appear here?
</details>
:thumbsup: for adding this note to `LeafSystem`'s documentation.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQge5kiNi-VWXQymS-:-KQQge5kiNi-VWXQymS0:b-o9k5s3) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L43)):*
> ```cpp
>     if (!stop_) {
>       // This can happen if the test case raises an unexpected exception.
>       // We need to join the thread here, or else the thread dtor explodes.
> ```

BTW: nit: replace "dtor" with "destructor" since not everyone knows what "dtor" stands for.

http://www.merriam-webster.com/dictionary/suggestions/dtor

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQQhEPD-LrFFrE7OBLj:b-fd36gj) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
> ```cpp
> class CustomDrakeSignalTranslator : public LcmAndVectorBaseTranslator {
>  public:
>   class CustomVector : public BasicStateAndOutputVector<double> {
> ```

To me, it's odd for class `CustomVector` to be an inner class of `CustomDrakesignalTranslator`. Can it be made _not_ an inner class?

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 213 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhmnHyoZ9trhvhj4y:-KQQhmnHyoZ9trhvhj4z:b-8lklr4) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L213)):*
> ```cpp
>    public:
>     CustomVector() : BasicStateAndOutputVector<double>(kDim) {}
>     void SetName(int index, std::string name) { names_.at(index) = name; }
> ```

Should this method take as an input parameter a `const std::string& name`?

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 214 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhiHCerI821fHESqH:-KQQhiHCerI821fHESqI:b-8j9p31) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L214)):*
> ```cpp
>     CustomVector() : BasicStateAndOutputVector<double>(kDim) {}
>     void SetName(int index, std::string name) { names_.at(index) = name; }
>     std::string GetName(int index) const { return names_.at(index); }
> ```

Should this method return `const std::string&`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-:-KQQi4lL-9xlSGl7ZGlz:bxc6u5c)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQcSuX_-2ZgEtU5z8L:-KQQiw7zWcMXSNu11Nus:bazas7m) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_and_vector_base_translator.h#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This comment is a bit unclear w.r.t _who_ will create and use the `BasicVector`when the return value is `nullptr`. Perhaps clarify that it is the `LcmSubscriberSystem` that will allocate and use a `BasicVector`?
> 
> Or, even better, make this method _not_ virtual and have it call a protected virtual`AllocateOutputVectorImpl()`method that returns `nullptr`. Subclasses can override this method to return non-`nullptr` values.
> 
> The, the logic for checking for a `nullptr` return value and creating a `BasicVector` object can be in this method's implementation instead of within `LcmSubscriberSystem`.
</details>
I agree the comment is nebulous.  I was re-reading after I submitted this, and also want to clarify the responsibilities in the doc.  Will fix.

But creating the `BasicVector` in this base class is not the answer -- note that the `LcmSubscriberSystem` is not even directly doing it.  It's the `LeafSystem` that contains such logic, and we should not duplicate it here or anywhere else.  I think the fix should be clarifying that `nullptr` means `use the framework default`, and a hint for where to look to discover what that means.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQQjr3BWVX8DBtt9crY:bce8xuz) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> To me, it's odd for class `CustomVector` to be an inner class of `CustomDrakesignalTranslator`. Can it be made _not_ an inner class?
</details>
Yes, it can go anywhere.  To me, it's useful to collect all of the test infrastructure in one place -- and reasonable to have the operational type of the translator be nested within it.  The translator is the important piece here; the specific vector class is tertiary.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 213 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhmnHyoZ9trhvhj4y:-KQQkBBc_oTuOyVhNnwh:byvmmi6) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L213)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this method take as an input parameter a `const std::string& name`?
</details>
I think this spelling is fine (in C++11 in general, and especially in a test stub).

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 214 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhiHCerI821fHESqH:-KQQkWVPwz1A4Ft_DSgp:b-p2pwiz) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L214)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this method return `const std::string&`?
</details>
An extra copy here is irrelevant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQOQ7NHVZxjFvrsj8fN:-KQQlkCtAikeom8BPjzL:b-bqivcu) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L82)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :thumbsup: for adding this note to `LeafSystem`'s documentation.
</details>
Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQcSuX_-2ZgEtU5z8L:-KQQw0eS_AiKDkIuA0ML:b-2pkf7a) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_and_vector_base_translator.h#L37)):*
OK for adding documentation saying that a return value of `nullptr` here means "use the framework's default vector type". Just be sure to define what is the framework's default type. Maybe it can be as simple as:

> The framework's default type is determined by the system that uses this translator.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQQvdKDKmocoNxlIlpP:bl4od92) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Yes, it can go anywhere.  To me, it's useful to collect all of the test infrastructure in one place -- and reasonable to have the operational type of the translator be nested within it.  The translator is the important piece here; the specific vector class is tertiary.
</details>
Then can you add a comment above this class declaration saying this is just an arbitrary vector class that has named indices, which is used for testing purposes. Actually, don't you think such a vector would be of general use and thus should be provided by the System 2.0 framework?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQR0C7MXt-DUN-8JdJP:bt0v8pe) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
> Then can you add a comment above this class declaration saying this is just an arbitrary vector class that has named indices, which is used for testing purposes.

What is the proposed defect such a change would be aiming to address?  I would like to fix it, but I don't understand.  All code defined in test files is for testing purposes.  This seems like a clarity defect -- what element of the PR code is unclear, and how?

> Actually, don't you think such a vector would be of general use and thus should be provided by the System 2.0 framework?

I think all ports and signals should have intrinsic names in all cases, so offering this class to provide names should not be generalized / extracted.  The name should be a core attribute in the framework that subclasses can implement however they want.  In any case, that discussion is out of scope for this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQR1P1gccnYtG8SHsqb:b-yzw789) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
Here is the sentence from the style guide:

> Every non-obvious class declaration should have an accompanying comment that describes what it is for and how it should be used.

It's not obvious to me what this class is for, especially since it's hidden inside a _translator_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQR2A16nvjhMfemCfkU:b-iwx1az) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Here is the sentence from the style guide:
> 
> > Every non-obvious class declaration should have an accompanying comment that describes what it is for and how it should be used.
> 
> It's not obvious to me what this class is for, especially since it's hidden inside a _translator_.
> 
> 
</details>
How about `// An output vector type that tests that subscribers permit non-default types.`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQSCLnPqFthVMODUokp:b-euvz2g) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> How about `// An output vector type that tests that subscribers permit non-default types.`?
</details>
:thumbsup:  Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by sherm1** [comment]
A few comments. I'm not blocking but PTAL.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 78 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSC8mDz9ufG2IcmOJb:-KQSC8mEYvui4Vk5A7CR:byhzgj1) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L78)):*
> ```objc
>    * recent update wins.
>    */
>   void SetMessage(std::vector<uint8_t> message_bytes);
> ```

BTW, did you want `const std::vector<uint8_t>&` here?

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSColp9ZFlMj_41_I6:-KQSColp9ZFlMj_41_I7:b-sjthsq) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L45)):*
> ```cpp
>       // We need to join the thread here, or else the thread dtor explodes.
>       Stop();
>       EXPECT_TRUE(was_stopped);
> ```

BTW, I don't get the logic here -- possible race? If `stop_` can be false then local `was_stopped` can be false. After the call to `Stop()` returns, the local would still be false and the test would fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-:-KQSDhXkkRrqv_75f7OR:b-s8elyz)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 78 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSC8mDz9ufG2IcmOJb:-KQSJprBxwF2rkgrZOLD:b-n4k8ic) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L78)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, did you want `const std::vector<uint8_t>&` here?
</details>
Nope, not with C++11, since I am going to keep the bytes.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSColp9ZFlMj_41_I6:-KQSKWQ0f7mCdTQRi79h:b-beacgq) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I don't get the logic here -- possible race? If `stop_` can be false then local `was_stopped` can be false. After the call to `Stop()` returns, the local would still be false and the test would fail.
</details>
The `EXPECT_TRUE` will always fail; that was my intent.  (Test code should always explicitly call `Stop`).  I will add `  // Always fails.` to clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by david-german-tri** [comment]
:lgtm: aside from open threads

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 78 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSSwrQ05Ir2UGyB1u3:-KQSSwrQ05Ir2UGyB1u4:bdij6oa) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L78)):*
> ```objc
>    * recent update wins.
>    */
>   void SetMessage(std::vector<uint8_t> message_bytes);
> ```

It's too bad we have to mock out the RPC layer in every single class that uses it, but such is the current state of tooling for LCM, I guess.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQSTYszB6qwFEyt6fKB:b953ixl) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :thumbsup:  Thanks.
</details>
Yes, thank you for not making this part of the framework.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-:-KQSUghemV6udH0XnIOc:b-9zavfy)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/lcm/lcm_subscriber_system.h, line 78 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSSwrQ05Ir2UGyB1u3:-KQSnL9rhTEZepJrEqT2:bd8mw06) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L78)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> It's too bad we have to mock out the RPC layer in every single class that uses it, but such is the current state of tooling for LCM, I guess.
</details>
Yeah.  I read every header file it offered, and none seemed to offer mocking.  The best I found were some "here be dragons do not touch" implementation details where you could retrieve the list of C callbacks (not C++) and then invoke them yourself.  This seemed better :smile:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQcSuX_-2ZgEtU5z8L:-KQTAf6PnxA4t6Q9HNGB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_and_vector_base_translator.h#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK for adding documentation saying that a return value of `nullptr` here means "use the framework's default vector type". Just be sure to define what is the framework's default type. Maybe it can be as simple as:
> 
> > The framework's default type is determined by the system that uses this translator.
</details>
Done.

---

*[drake/systems/lcm/lcm_subscriber_system.h, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQOQ7NHVZxjFvrsj8fN:-KQTB1Jzq80okgWejQAM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/lcm_subscriber_system.h#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Will fix.
</details>
Done.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQSColp9ZFlMj_41_I6:-KQTDncm50gTVpFQVe-o:b40ddoa) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `EXPECT_TRUE` will always fail; that was my intent.  (Test code should always explicitly call `Stop`).  I will add `  // Always fails.` to clarify.
</details>
Done.

@sherm1 Rewritten for clarity; PTAL.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 210 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQQhEPCFUkFMQB5or6r:-KQTEJB7DKvkQVdEKDWY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bb169975475f9292fb60df10e86effc082920c1/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L210)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Yes, thank you for not making this part of the framework.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 36 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-KQTGGTlCDyEXvlGGvTk:-KQTGGTmvpu46bxn_naa:bsrv6e9) ([raw file](https://github.com/robotlocomotion/drake/blob/cc467386dd57e34f8aa69f4ef44c4792ee67b279/drake/systems/lcm/lcm_and_vector_base_translator.h#L36)):*
> ```objc
>   /**
>    * Allocates the vector storage for an output port of our LCM message type,
>    * in case special storage is needed.  A result of nullptr indicates that no
> ```

BTW: nit: optional: surround `nullptr` with back ticks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3301#-:-KQTGwuqxV6BELBya4TY:bnfp4nl)*

**Pull request merged**
