### PR TITLE
[lcm] Deprecate DrakeMockLcm

### LINKED ISSUE #14606: DrakeVisualizer unit tests should not use DrakeMockLcm
`DrakeMockLcm`'s last commit indicated that we want to remove usage of this implementation. As it is simply an alias for `DrakeLcm("memq://")`, it would be better to have that be explicit. Furthermore, in a bazel testing context, that is the default URL for simply creating `DrakeLcm lcm;`.

So, we simply need to swap the usages of the soon-to-be deprecated `DrakeMockLcm` in favor of `DrakeLcm` spelling.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #14606.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16078)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews, please.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16078)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/lcm_py.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16078#-MoFLfZs0G0Y28N5k38p:-MoFLfZs0G0Y28N5k38q:b-gfeba5) ([raw file](https://github.com/robotlocomotion/drake/blob/98856102701a21244c16aec826a03a6e7946ac98/bindings/pydrake/lcm_py.cc#L77)):*
> ```cpp
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>   {
>     // XXX
> ```

Is this comment supposed to be there?  Or leftover?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16078)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[bindings/pydrake/lcm_py.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16078#-MoFLfZs0G0Y28N5k38p:-MoFMcUCDW5jisvjJdYN:bn8gi1y) ([raw file](https://github.com/robotlocomotion/drake/blob/98856102701a21244c16aec826a03a6e7946ac98/bindings/pydrake/lcm_py.cc#L77)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this comment supposed to be there?  Or leftover?
</blockquote></details>

Oops.  Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16078#-:-MoFNJr553-0riZZIDk0:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
