### PR TITLE
Add UpdateBound for PYFunctionConstraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MNfOjYw3nqMykOqkM4F:bhdb3rc) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
> ```cpp
>         autodiff_func_(Wrap<AutoDiffXd, AutoDiffFunc>(func)) {}
> 
>   using Constraint::set_bounds;
> ```

@ericcousineau-tri may I ask you how to add the python binding for PyFunctionConstraint::set_bounds? I can now call it in C++, but I don't know how to call it in python.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MNj35ac7v2ttHfrQS9A:b-2pcr33) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@ericcousineau-tri may I ask you how to add the python binding for PyFunctionConstraint::set_bounds? I can now call it in C++, but I don't know how to call it in python.
</blockquote></details>

Ahhh, I see that it's presently only bound for `LinearConstraint:

Bound here:
https://github.com/RobotLocomotion/drake/blob/78faa373656528a1e923bd9be1f5f36252f2678b/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1284-L1302

Tested here, but kinda duplicitously "generic" when really it's only testing the linear cost.
https://github.com/RobotLocomotion/drake/blob/78faa373656528a1e923bd9be1f5f36252f2678b/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L301-L309

The fix would be to hoist that binding (all three flavors) to the `Constraint` base class; then it will be exposed for all classes.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNj3nIREgFhsRZTEWYk:-MNj3nISErJz6lVGlyJD:baiscrm) (no related file):*
Working (minor): Will try and trace back to see why this was only bound for `LinearConstraint`.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNj3nIREgFhsRZTEWYk:-MNj47N2AVvMfjT0gmYg:b-6fwcqx) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working (minor): Will try and trace back to see why this was only bound for `LinearConstraint`.
</blockquote></details>

It was me :( I'm a bad person:
https://github.com/RobotLocomotion/drake/pull/8917

I'll PR against your PR right quick.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MNj4Sl8EdZrMjijXCD5:b-uobmnf) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ahhh, I see that it's presently only bound for `LinearConstraint:

Bound here:
https://github.com/RobotLocomotion/drake/blob/78faa373656528a1e923bd9be1f5f36252f2678b/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1284-L1302

Tested here, but kinda duplicitously "generic" when really it's only testing the linear cost.
https://github.com/RobotLocomotion/drake/blob/78faa373656528a1e923bd9be1f5f36252f2678b/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L301-L309

The fix would be to hoist that binding (all three flavors) to the `Constraint` base class; then it will be exposed for all classes.
</blockquote></details>

OK, nevermind on hoisting to base `Constraint` base class. I reviewed the docs, and I see that we conditionally seal them.

Hm... This is a really fuzzy one...

Three options:

(1) Keep as-is, and do the following
 -  We hoist all bounds mutators to public for all constraints
  - We bind the bounds mutators on `Constraint` itself

(2) Bind `PyFunctionConstraint` and expose it to Python explicitly. Then expose the bound mutators on this (copying from `LinearConstraint`).

(3) Fix this TODO:
https://github.com/RobotLocomotion/drake/blob/78faa373656528a1e923bd9be1f5f36252f2678b/bindings/pydrake/solvers/mathematicalprogram_py.cc#L195-L196
And then do a flavor of (2).

---

My gut says we probably just want (1). It's easy, and if people want foot guns, let them have it?

Let me know if you would like to VC about this on Monday.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNj3nIREgFhsRZTEWYk:-MNjR-sn8dmGyVxXkfBu:b-wtqnjx) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It was me :( I'm a bad person:
https://github.com/RobotLocomotion/drake/pull/8917

I'll PR against your PR right quick.
</blockquote></details>

OK Nvm. See comment below.

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNj3nIREgFhsRZTEWYk:-MNkUWyLEJ9Yv3BCmMFa:bzicx2t) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Nvm. See comment below.
</blockquote></details>

Actually, we intentionally make `set_bounds()` to be a protected method in `Constraint` class in C++. The reason is that some constraints shouldn't support `set_bounds()`. For example, `LorentzConstraint` should always encode `x - sqrt(y' * y) >= 0`, so its bounds should always be [0, inf]. The workflow was that in C++ code, if a derived constraint want to support `set_bounds()`, then we add `using Constraint::set_bounds;` in the C++ code.

In `PyFunctionConstraint`, we added the C++ code `using Constraint::set_bounds`, now I need to add the python binding for this function.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNj3nIREgFhsRZTEWYk:-MNx7y_8-L8DwjlzrDOW:b-97v3wy) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Actually, we intentionally make `set_bounds()` to be a protected method in `Constraint` class in C++. The reason is that some constraints shouldn't support `set_bounds()`. For example, `LorentzConstraint` should always encode `x - sqrt(y' * y) >= 0`, so its bounds should always be [0, inf]. The workflow was that in C++ code, if a derived constraint want to support `set_bounds()`, then we add `using Constraint::set_bounds;` in the C++ code.

In `PyFunctionConstraint`, we added the C++ code `using Constraint::set_bounds`, now I need to add the python binding for this function.
</blockquote></details>

Yup, I'm aware of that intent. However, it may be overly conservative, hence the "foot guns" statement below.

Can you review the options I posted below and tell me which one you prefer?

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MO-tbbaEaXtXQzh4iTc:bjhyy67) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK, nevermind on hoisting to base `Constraint` base class. I reviewed the docs, and I see that we conditionally seal them.

Hm... This is a really fuzzy one...

Three options:

(1) Keep as-is, and do the following
 -  We hoist all bounds mutators to public for all constraints
  - We bind the bounds mutators on `Constraint` itself

(2) Bind `PyFunctionConstraint` and expose it to Python explicitly. Then expose the bound mutators on this (copying from `LinearConstraint`).

(3) Fix this TODO:
https://github.com/RobotLocomotion/drake/blob/78faa373656528a1e923bd9be1f5f36252f2678b/bindings/pydrake/solvers/mathematicalprogram_py.cc#L195-L196
And then do a flavor of (2).

---

My gut says we probably just want (1). It's easy, and if people want foot guns, let them have it?

Let me know if you would like to VC about this on Monday.
</blockquote></details>

Sorry for my belated reply. I feel like I don't want to do (1). All inherited class should be able to do what the parent class can do. If the parent class claims that the public user can mutate the bounds, then the inherited class should be able to mutate the bounds also. I feel I would like to do either (2) or (3). Which one do you think is easier?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MO1cs_DAnfd7mLYwaAa:b-510alq) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry for my belated reply. I feel like I don't want to do (1). All inherited class should be able to do what the parent class can do. If the parent class claims that the public user can mutate the bounds, then the inherited class should be able to mutate the bounds also. I feel I would like to do either (2) or (3). Which one do you think is easier?
</blockquote></details>

No worries! (2) would be the easiest (given that (3) is a superset of (2)).

All you need to do is define the bindings for `PyFunctionConstraint` (like you do for `LinearConstraint`, etc.), and add the bindings for them, and you should be good.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MO2L9oVCY32BQeS1ayc:br7nfxo) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

No worries! (2) would be the easiest (given that (3) is a superset of (2)).

All you need to do is define the bindings for `PyFunctionConstraint` (like you do for `LinearConstraint`, etc.), and add the bindings for them, and you should be good.
</blockquote></details>

Done, I did option 2. Thanks for the suggestion!

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410#-:-MO2LFZE2F8xysulzpCk:bhru7xi)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with some minor modifications requested

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410#-:-MO2Zm2lCPgDY0MoXaYp:b2m0gb9)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MNfOjYw3nqMykOqkM4E:-MO2ZX4w1X-Sbb6DwEgn:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/43a71e09b723a9dc40252541deec563838cfb922/bindings/pydrake/solvers/mathematicalprogram_py.cc#L210)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done, I did option 2. Thanks for the suggestion!
</blockquote></details>

OK Sweet!
___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1279 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MO2ZYx-3cRHyTTzrl2n:-MO2ZYx-3cRHyTTzrl2o:b-lqgc28) ([raw file](https://github.com/robotlocomotion/drake/blob/7637c6ccd447609effc65c59ca561b546b916929/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1279)):*
> ```cpp
>       .def("set_bounds", &PyFunctionConstraint::set_bounds,
>           py::arg("lower_bound"), py::arg("upper_bound"),
>           "set both the lower and upper bounds of the constraint.");
> ```

nit "set" should be capitalized.
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 592 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MO2Zf9CBaZ8hQZCQmyr:-MO2Zf9CBaZ8hQZCQmys:brxemup) ([raw file](https://github.com/robotlocomotion/drake/blob/7637c6ccd447609effc65c59ca561b546b916929/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L592)):*
> ```Python
>             binding.evaluator().upper_bound(), np.array([1.]))
>         # Test UpdateLowerBound()
>         binding.evaluator().UpdateLowerBound(new_lb=[-1.])
> ```

Can you add a check for `PyFunctionConstraint`?

e.g.
```
self.assertIsInstance(binding.evaluator(), PyFunctionConstraint)
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 592 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14410#-MO2Zf9CBaZ8hQZCQmyr:-MO2gRlT0-BYVpimue_b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7637c6ccd447609effc65c59ca561b546b916929/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L592)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you add a check for `PyFunctionConstraint`?

e.g.
```
self.assertIsInstance(binding.evaluator(), PyFunctionConstraint)
```
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14410)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Comment by EricCousineau-TRI** [comment]
Skipping slow builds

**Pull request merged**
