### PR TITLE
Traffic light aware controller

### PR DESCRIPTION
**Pull request by nikos-tri**
Experimental prototype of a car controller that can be used in cascade with another controller, and overrides when the car should stop at a traffic signal.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7112)

### CODE REVIEW

**Comment by nikos-tri** [comment]
+@liangfok feature review please

**Comment by liangfok** [comment]
Checkpoint.

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/automotive/dev/BUILD, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TnJdwtGDbX2q59Gl:-Kv0TnJdwtGDbX2q59Gm:bsfi7ny) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L9)):*
> ```Python
>     "drake_cc_googletest",
>     "drake_cc_library",
>     "drake_cc_binary",
> ```

Unused?

(If it is used, it should be alpha sorted.)

---

*[drake/automotive/dev/BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0Toekt4l4DYTlHnXi:-Kv0Toekt4l4DYTlHnXj:b-o7y2v9) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L11)):*
> ```Python
>     "drake_cc_binary",
> )
> load("//tools:python_lint.bzl", "python_lint")
> ```

This change should be reverted since the original was correct.

---

*[drake/automotive/dev/BUILD, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0U5r1rlh70SCLRZng:-Kv0U5r1rlh70SCLRZnh:b-4h0rp3) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L38)):*
> ```Python
>   deps = [
>           "//drake/systems/framework",
>           "//drake/automotive:generated_vectors",
> ```

Alpha sort.

---

*[drake/automotive/dev/BUILD, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TqeGZ7G7m0NVGhoa:-Kv0TqeGZ7G7m0NVGhob:b-436pxy) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L59)):*
> ```Python
>   ],
> )
> ```

This BUILD file should still have `add_lint_tests()`.

---

*[drake/automotive/dev/traffic_light.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TgIBuw8tX9EX6iZ0:-Kv0TgICTIw51DSoF_t-:b-o7y2v9) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light.h#L21)):*
> ```objc
> /// for the other half.
> ///
> /// At this time, the only supported value of T is double
> ```

This change should be reverted since the original was correct.

---

*[drake/automotive/dev/traffic_light.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0Th5vCwe0xlaOxfTq:-Kv0Th5vCwe0xlaOxfTr:b-o7y2v9) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light.h#L22)):*
> ```objc
> ///
> /// At this time, the only supported value of T is double
> // TODO(nikos-tri): Support AutoDiffXd and Symbolic
> ```

This change should be reverted since the original was correct.

---

*[drake/automotive/dev/traffic_light.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TTHwRYZToMyFMC8S:-Kv0TTHwRYZToMyFMC8T:b-o7y2v9) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light.h#L50)):*
> ```objc
> 
> }  // namespace drake
> }  // namespace automotive
> ```

This change should be reverted since the original was correct.

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0VQpCUsS6Lsg4Kv6R:-Kv0VQpCUsS6Lsg4Kv6S:b-htucln) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L3)):*
> ```objc
> #pragma once
> 
> #include <math.h>
> ```

This should be `#include <cmath>`.

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0UI8RlOwZf5z7Yw3-:-Kv0UI8RlOwZf5z7Yw30:bpn5pv1) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L16)):*
> ```objc
> namespace automotive {
> 
> /// This controller takes as input an acceleration from another controller,
> ```

BTW, consider replacing "from another controller" with "command". From this system's perspective, it doesn't matter where the command came from right?

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0UR6QzPrhleKp50O4:-Kv0UR6QzPrhleKp50O5:b-y8dbae) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L19)):*
> ```objc
> /// and also looks at the traffic light. If the traffic light is "open",
> /// this controller simply forwards the acceleration command from the other
> /// controller; otherwise it overrides the acceleration with a braking
> ```

BTW, consider deleting "from the other controller" or replacing it with a description of how the command is forwarded. For example, is the command forwarded by being placed in an output port?

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0V0kU-FtaseXlOBjz:-Kv0V0kV9i7Da6pCsUrg:bvxvve4) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L22)):*
> ```objc
> /// command.
> ///
> /// Currently, supported value of T is double.
> ```

BTW, missing "the only" before "supported".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-:-Kv0Vr-IVekP5vxS6gUn:by96gdd)*

**Comment by nikos-tri** [comment]
For some reason when I rebased onto the changes in traffic_light a lot of the previous changes were lost :-/ probably I did the rebase incorrectly. Things should be fixed now.

---

Review status: 0 of 86 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/automotive/dev/BUILD, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TnJdwtGDbX2q59Gl:-Kv3AyD8mHCssR1WA_Jt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Unused?

(If it is used, it should be alpha sorted.)
</blockquote></details>

Done.

---

*[drake/automotive/dev/BUILD, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0Toekt4l4DYTlHnXi:-Kv3BDDOdwK3fJNIRO2h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L11)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This change should be reverted since the original was correct.
</blockquote></details>

Done.

---

*[drake/automotive/dev/BUILD, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0U5r1rlh70SCLRZng:-Kv3DX0SA8VtHVCriO8F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L38)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Alpha sort.
</blockquote></details>

Done.

---

*[drake/automotive/dev/BUILD, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TqeGZ7G7m0NVGhoa:-Kv3DXwDCLQ0X1H3Ulaf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/BUILD#L59)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This BUILD file should still have `add_lint_tests()`.
</blockquote></details>

Done.

---

*[drake/automotive/dev/traffic_light.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TgIBuw8tX9EX6iZ0:-Kv3DZuzrDcezFjzhZu_:b-mg8w87) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light.h#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This change should be reverted since the original was correct.
</blockquote></details>

Done. Only difference I see is adding a period.

---

*[drake/automotive/dev/traffic_light.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0Th5vCwe0xlaOxfTq:-Kv3Dg_kKO1D0w5eCggF:b-mg8w87) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This change should be reverted since the original was correct.
</blockquote></details>

Done. Only difference I see is adding a period.

---

*[drake/automotive/dev/traffic_light.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0TTHwRYZToMyFMC8S:-Kv3HlLMwnmsgXN-GZmH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light.h#L50)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This change should be reverted since the original was correct.
</blockquote></details>

Done.

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0VQpCUsS6Lsg4Kv6R:-Kv3Doqs2-SqzHGtATna:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This should be `#include <cmath>`.
</blockquote></details>

Done.

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0UI8RlOwZf5z7Yw3-:-Kv3E-YCvouqf2ykGKag:b-b5cz09) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L16)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "from another controller" with "command". From this system's perspective, it doesn't matter where the command came from right?
</blockquote></details>

True. Done.

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0UR6QzPrhleKp50O4:-Kv3Eck0J3CW-GfPenu7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "from the other controller" or replacing it with a description of how the command is forwarded. For example, is the command forwarded by being placed in an output port?
</blockquote></details>

Done.

---

*[drake/automotive/dev/traffic_light_aware_controller.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv0V0kU-FtaseXlOBjz:-Kv3Ed54YLPK9D79Gf6w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f5efbe2c7545b461e6f7231cc011f5011a34da1/drake/automotive/dev/traffic_light_aware_controller.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing "the only" before "supported".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-:-Kv3BMG6d5o4OmHGmEgH:b-cgatoa)*

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv89Wxu_RskXrq5e4v7:-Kv89Wxu_RskXrq5e4v8:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L4)):*
> ```cpp
> 
> namespace drake {
> using std::cout;
> ```

Unused.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv89ZJqALb34qvlkSFI:-Kv89ZJqALb34qvlkSFJ:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L5)):*
> ```cpp
> namespace drake {
> using std::cout;
> using std::endl;
> ```

Unused.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv89d0IThAdhZlLk_KY:-Kv89d0IThAdhZlLk_KZ:b303nn8) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L51)):*
> ```cpp
> template <typename T>
> void TrafficLightAwareController<T>::DoCalcOutput(
>     const systems::Context<T>& context, systems::BasicVector<T>* output) const {
> ```

BTW, you can remove both instances of `systems::` given the `using` statements above.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8A8buG4ovYiCar6R6:-Kv8A8buG4ovYiCar6R7:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L52)):*
> ```cpp
> void TrafficLightAwareController<T>::DoCalcOutput(
>     const systems::Context<T>& context, systems::BasicVector<T>* output) const {
>   VectorX<T> car_state = ReadInput(context, car_state_input_index_);
> ```

BTW, `const`?

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8ABB3A9NGIMtkWezG:-Kv8ABB3A9NGIMtkWezH:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L53)):*
> ```cpp
>     const systems::Context<T>& context, systems::BasicVector<T>* output) const {
>   VectorX<T> car_state = ReadInput(context, car_state_input_index_);
>   VectorX<T> other_acceleration = ReadInput(context, acceleration_input_index_);
> ```

BTW, `const`?

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8As3uADPoLl8419zo:-Kv8As3uADPoLl8419zp:bg7na75) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L53)):*
> ```cpp
>     const systems::Context<T>& context, systems::BasicVector<T>* output) const {
>   VectorX<T> car_state = ReadInput(context, car_state_input_index_);
>   VectorX<T> other_acceleration = ReadInput(context, acceleration_input_index_);
> ```

BTW, consider naming this `input_command`.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 54 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8AEFjJqBgFdMh_lyk:-Kv8AEFjJqBgFdMh_lyl:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L54)):*
> ```cpp
>   VectorX<T> car_state = ReadInput(context, car_state_input_index_);
>   VectorX<T> other_acceleration = ReadInput(context, acceleration_input_index_);
>   VectorX<T> traffic_light_signal =
> ```

BTW, `const`?

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8AJG6XE-hMyx26Foz:-Kv8AJG6XE-hMyx26Fp-:b-6gtv0q) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L61)):*
> ```cpp
>   T signal_x = traffic_light_signal(0);
>   T signal_y = traffic_light_signal(1);
>   T signal_radius = traffic_light_signal(2);
> ```

BTW, all of the above can be `const`.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8APSgFfndmu2qNnSo:-Kv8APSgFfndmu2qNnSp:b-uj7ipt) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L63)):*
> ```cpp
>   T signal_radius = traffic_light_signal(2);
> 
>   if ((traffic_light_signal(3) == 0) ||
> ```

BTW, consider using a named constant for `3`.

---

*[drake/automotive/dev/traffic_light_aware_controller.cc, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8AzwqQ6K--Cmm0Is_:-Kv8AzwqQ6K--Cmm0Isa:b-tr9tbx) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/traffic_light_aware_controller.cc#L72)):*
> ```cpp
>     DrivingCommand<T> braking_command;
>     braking_command.set_steering_angle(other_acceleration(0));
>     // TODO(nikos-tri) Replace this with a more sophisticated braking controller
> ```

BTW, missing period at end of sentence.

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8BA3h4UOhG3qGYWkQ:-Kv8BA3h4UOhG3qGYWkR:bqo6zxs) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L3)):*
> ```cpp
> #include "drake/automotive/dev/traffic_light_aware_controller.h"
> 
> #include <stdlib.h>
> ```

This should be `<cstdlib>`.

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8BIQasMxBii1OjnJJ:-Kv8BIQasMxBii1OjnJK:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L14)):*
> ```cpp
> 
> namespace drake {
> using std::abs;
> ```

Unused.

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8BNNg4RnWKKJ_vs-l:-Kv8BNNg4RnWKKJ_vs-m:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L19)):*
> ```cpp
> using Eigen::VectorXd;
> 
> using systems::BasicVector;
> ```

Unused.

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8BWVZKjh5qoWG3ENL:-Kv8BWVZKjh5qoWG3ENM:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L26)):*
> ```cpp
> namespace automotive {
> namespace {
> using systems::LeafSystem;
> ```

Unused.

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8C85Y1yh9IxOfXCIc:-Kv8C85Y1yh9IxOfXCId:b9v6tax) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L60)):*
> ```cpp
>   EXPECT_EQ(controller_output, go);
> 
>   // Feed it a signal closed, and car the car is near so it should slam on the
> ```

"car the car" should be "the car".

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8CH_Lp0JzPHLQlyUz:-Kv8CH_Lp0JzPHLQlyV-:bb64e1a) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L69)):*
> ```cpp
>   EXPECT_EQ(controller_output, stop);
> 
>   // Feed it a signal open
> ```

Missing period.

---

*[drake/automotive/dev/test/traffic_light_aware_controller_test.cc, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-Kv8BkEY_VBXUMBuwu0H:-Kv8BkEY_VBXUMBuwu0I:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/0616c110f78ef441493e992b1e2540b912546778/drake/automotive/dev/test/traffic_light_aware_controller_test.cc#L80)):*
> ```cpp
> VectorXd ReadOutput(const TrafficLightAwareController<double>& my_system,
>                     const SystemOutput<double>& output_port) {
>   VectorXd out_data =
> ```

BTW, `const`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7112#-:-Kv8CMt4flJNEtVCaXWV:bl4rucz)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

**Pull request closed without merging**
