### PR TITLE
Port SimpleCar to System2

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Port SimpleCar to System2.  Rewrite the unit test, instead of needing to call Simulate2.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3252)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by rpoyner-tri** [comment]
I still need to convince myself of the need for all the dynamic_cast<>'s everywhere, but that is not the brief of this PR.
:lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/simple_car-inl.h, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-KPzVqpQC5v2BMQwAlT6:-KPzVqpRxHrKbmfNyBSV:bs0fn5i) ([raw file](https://github.com/robotlocomotion/drake/blob/150b1a3e179d0ca2c9e4a9b6f7d3a27dcf9985c7/drake/examples/Cars/simple_car-inl.h#L93)):*
> ```objc
> 
>   // Convert the input into System1 data.
>   // TODO(jwnimmer-tri) Why does this return a pointer instead of ref?
> ```

BTW agreed.

---

*[drake/examples/Cars/test/simple_car_test.cc, line 58 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-KPz_Y28JeRJl3tuD-tX:-KPz_Y28JeRJl3tuD-tY:b5rsac6) ([raw file](https://github.com/robotlocomotion/drake/blob/150b1a3e179d0ca2c9e4a9b6f7d3a27dcf9985c7/drake/examples/Cars/test/simple_car_test.cc#L58)):*
> ```cpp
>   EXPECT_EQ(systems::kVectorValued, output_descriptor.get_data_type());
>   EXPECT_EQ(systems::kOutputPort, output_descriptor.get_face());
>   EXPECT_EQ(SimpleCarStateIndices::kNumCoordinates,
> ```

BTW, best diff algorithm failure ever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-:-KPzbGWVClFbPAw122Me:bjoeqj9)*

**Comment by jwnimmer-tri** [comment]
I am platform reviewer of the day, so need a volunteer to self-assign this one.  @david-german-tri would you like to take a look?

**Comment by david-german-tri** [comment]
+@david-german-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-:-KQ0j3do6jPPTw6OUA3N:bqmdn1l)*

**Comment by david-german-tri** [comment]
:lgtm: :+1: for the rewritten tests!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/simple_car-inl.h, line 86 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-KQ0j_dTSoxe6WxayHJX:-KQ0j_dTSoxe6WxayHJY:bhjyypv) ([raw file](https://github.com/robotlocomotion/drake/blob/150b1a3e179d0ca2c9e4a9b6f7d3a27dcf9985c7/drake/examples/Cars/simple_car-inl.h#L86)):*
> ```objc
>   // Convert the state into System1 data.
>   const systems::StateVector<T>& context_state =
>       context.get_state().continuous_state->get_state();
> ```

FYI, I think I will add some convenience accessors for this line and the next.  We're typing it in too many places.

---

*[drake/examples/Cars/simple_car-inl.h, line 93 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-KQ0k4zzbEviPLX2A4kG:-KQ0k5--YhwHY0JqP5WI:bvumfvo) ([raw file](https://github.com/robotlocomotion/drake/blob/150b1a3e179d0ca2c9e4a9b6f7d3a27dcf9985c7/drake/examples/Cars/simple_car-inl.h#L93)):*
> ```objc
> 
>   // Convert the input into System1 data.
>   // TODO(jwnimmer-tri) Why does this return a pointer instead of ref?
> ```

FYI, it intentionally returns nullptr in certain circumstances: https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/context_base.h#L53

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3252#-:-KQ1ZUl88zOvojb-RMKN:bdanqk9)*

**Pull request merged**
