### PR TITLE
Add documentation for simple_car_config

### LINKED ISSUE #5097: Document SimpleCarConfig parameter meanings and units
The `doc` elements in [simple_car_config.named_vector](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/simple_car_config.named_vector) should become meaningful.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #5097.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5111)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-:-KcYFkChwZSLDwUTVOhE:bltds52)*

**Comment by liangfok** [comment]
:lgtm: Just a couple BTW comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car_config.named_vector, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYMooFE0D2B5kZQAjk:-KcYMooGE-UbWbRJJEsU:beis9eu) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L15)):*
> ```
> element {
>     name: "max_velocity"
>     doc: "A limit on the car's forward velocity, in meters per second; this element must be positive."
> ```

BTW, is there a separate limit on the car's reverse velocity?

The word "velocity" inherently implies a direction. Thus, "forward velocity" and "reverse velocity" might be redundant. Consider changing this element's name to be "max_forward_speed".

---

*[drake/automotive/simple_car_config.named_vector, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYPUh8G1omoeNssyXI:-KcYPUh8G1omoeNssyXJ:b-dd7rxx) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L23)):*
> ```
> element {
>     name: "velocity_lookahead_time"
>     doc: "Smoothing constant for velocity changes, in seconds; this element must be positive.  This is deprecated and will eventually be removed."
> ```

BTW, to be consistent with the previous descriptions, consider starting this sentence with "A smoothing...".

(Same comment below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-:-KcYQzoIjug4OsPYeZ09:b5uu0df)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car_config.named_vector, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYMooFE0D2B5kZQAjk:-KcYRW6kAB7m4saGwLNq:b-7cpcc2) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is there a separate limit on the car's reverse velocity?

The word "velocity" inherently implies a direction. Thus, "forward velocity" and "reverse velocity" might be redundant. Consider changing this element's name to be "max_forward_speed".
</blockquote></details>

(1) The car has no transmission, and cannot not move backwards.

(2) Done.

---

*[drake/automotive/simple_car_config.named_vector, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYPUh8G1omoeNssyXI:-KcYS1cfEJRYqC4WHfXC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, to be consistent with the previous descriptions, consider starting this sentence with "A smoothing...".

(Same comment below.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-:-KcYS9Ve5K7EdRVoLnAv:bcav8r0)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-:-KcYT1UuX444f-AovzdT:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/automotive/simple_car_config.named_vector, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYMooFE0D2B5kZQAjk:-KcYU2H_Zr5y6dSj4UA2:b-d7xupa) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(1) The car has no transmission, and cannot not move backwards.

(2) Done.
</blockquote></details>

BTW, is the fact that the simple car cannot go backwards documented somewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/simple_car_config.named_vector, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYMooFE0D2B5kZQAjk:-KcYWOc9M_v4puOJbbyy:bl1jus8) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is the fact that the simple car cannot go backwards documented somewhere?
</blockquote></details>

I guess only insofar as nowhere in its overview does it tell you how to shift into reverse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111)*

**Comment by liangfok** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/automotive/simple_car_config.named_vector, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5111#-KcYMooFE0D2B5kZQAjk:-KcYnKdqhjf84ry2NBaH:b-9kcp1m) ([raw file](https://github.com/robotlocomotion/drake/blob/e62adc11431bb7c5358bda992e1349a0a6c3ce58/drake/automotive/simple_car_config.named_vector#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess only insofar as nowhere in its overview does it tell you how to shift into reverse.
</blockquote></details>

Done: #5117.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5111)*

**Pull request merged**
