### PR TITLE
Ubuntu-14 Specific Valgrind Supressions

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Ubuntu-14 memory leaks.  Testing on CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5877)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-nightly-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/valgrind-cmake.supp, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFxbI04SrmAEo_IBU_:-KiFxbI04SrmAEo_IBUa:brxmmik) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L163)):*
> _ZNSs4_Rep9_S_createEmmRKSaIcE

Maybe just mention that this is `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)` instead of beating around the bush to that effect?

---

*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiFy8OlWm97J_DJaUaM:bjlxs6c) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
> ```
>     fun:_ZNSs12_S_constructIPKcEEPcT_S3_RKSaIcESt20forward_iterator_tag
>     fun:_ZNSsC1EPKcRKSaIcE
>  	...
> ```

What's with the mixed indentation (tabs vs. spaces)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFxbI04SrmAEo_IBU_:-KiFyxk_myI1FGQVrcRf:b-iu2pb2) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L163)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

> _ZNSs4_Rep9_S_createEmmRKSaIcE

Maybe just mention that this is `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)` instead of beating around the bush to that effect?

</blockquote></details>

:D, sure, but there are three things we need to mention in addition to what you said .  
1. They don't happen in Xenial.  
2. Most of them go away on removing EXPECT_DEATH.
3. ProtoBuf is leaking.
4. There is a leak in the log parser which is being suppressed.
I can however paraphrase so that it doesn't read like I'm beating around the bush.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiFzwDBWKT7aMNl8VA0:b2au034) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What's with the mixed indentation (tabs vs. spaces)?
</blockquote></details>

Yeah, so the thing is when Valgrind produces the suppressions it has three spaces indentation, put I guess Jamie used 4 spaced indentation.  I think we should keep the 3 space because it's what is default and cpplint is not checking the suppressions file.  I can change the suppressions for the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiG-bhJHxa41ifibDCg:b-7rxs64) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
<details><summary><i>Previously, m-chaturvedi wrote…</i></summary><blockquote>

Yeah, so the thing is when Valgrind produces the suppressions it has three spaces indentation, put I guess Jamie used 4 spaced indentation.  I think we should keep the 3 space because it's what is default and cpplint is not checking the suppressions file.  I can change the suppressions for the file.
</blockquote></details>

*change the indentations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/valgrind-cmake.supp, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFxbI04SrmAEo_IBU_:-KiG-pMkXOkzdQCGIO6Z:b1bxw15) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L163)):*
<details><summary><i>Previously, m-chaturvedi wrote…</i></summary><blockquote>

:D, sure, but there are three things we need to mention in addition to what you said .  
1. They don't happen in Xenial.  
2. Most of them go away on removing EXPECT_DEATH.
3. ProtoBuf is leaking.
4. There is a leak in the log parser which is being suppressed.
I can however paraphrase so that it doesn't read like I'm beating around the bush.

</blockquote></details>

Right; I was referring (only) to the text "which is a basic_string.h function, in particular _S_create function". This could be replaced with "i.e. *\<full signature\>*". (Also, breaking the previous line before `fun:...` is probably superfluous.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiG28oxZLcpiGG7ygXF:b-c7m76z) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
<details><summary><i>Previously, m-chaturvedi wrote…</i></summary><blockquote>

*change the indentations
</blockquote></details>

I changed these indentation, tab was not 4 spaces in my Trusty box.
Do you think 3 spaced is better than 4 spaced as far as the whole file is concerned?  Or we keep the 4 spaces?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiG61J8JEqgLctDT_pr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
<details><summary><i>Previously, m-chaturvedi wrote…</i></summary><blockquote>

I changed these indentation, tab was not 4 spaces in my Trusty box.
Do you think 3 spaced is better than 4 spaced as far as the whole file is concerned?  Or we keep the 4 spaces?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFxbI04SrmAEo_IBU_:-KiG63fRkumW2riXM69v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L163)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Right; I was referring (only) to the text "which is a basic_string.h function, in particular _S_create function". This could be replaced with "i.e. *\<full signature\>*". (Also, breaking the previous line before `fun:...` is probably superfluous.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by mwoehlke-kitware** [comment]
:lgtm: I guess; haven't thought *too* deeply as to what is actually being suppressed...

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiGAcNZAZh5i2lbW_jc:b9w3txz) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
> Do you think 3 spaced is better than 4 spaced

Whichever is most prevalent in our suppressions files, I guess. I don't care so much about how *many* spaces to indent. I was commenting mainly on the mix of some lines indented with spaces and some with tabs, which is never good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-:-KiGB2ojHASZ6zQIR7j9:b-57wt26)*

**Comment by m-chaturvedi** [comment]
*[tools/valgrind-cmake.supp, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-KiFy8OlWm97J_DJaUaL:-KiGBigGfORSZLU-01Wa:b3orv5r) ([raw file](https://github.com/robotlocomotion/drake/blob/a50cf0dd3d3f1181addd3080048515b12a1deafd/tools/valgrind-cmake.supp#L191)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

> Do you think 3 spaced is better than 4 spaced

Whichever is most prevalent in our suppressions files, I guess. I don't care so much about how *many* spaces to indent. I was commenting mainly on the mix of some lines indented with spaces and some with tabs, which is never good.
</blockquote></details>

I kept the 4 spaces for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877)*

**Comment by david-german-tri** [comment]
-@david-german-tri +@stonier 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5877#-:-KiGo0tQa_eJThAbpCg_:bzcpane)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-valgrind-open-source please

**Comment by stonier** [comment]
@jwnimmer-tri do you want to make a decision to drop this effort for Trusty (with the expectation that we'll move on in Q3 with driving) so we can invest it elsewhere? Are there items here which are especially worrying enough to root cause regardless?

**Comment by jwnimmer-tri** [comment]
My opinion is that bringing up analysis tools on Trusty is of very small benefit.  Our focus should be on Xenial, no matter what any downstream is doing.  It is the platform we will have for another 2+ years, and its analysis tools are better (newer) to begin with.

**Comment by stonier** [comment]
Closing this PR in favour of focusing effort on Xenial.

**Pull request closed without merging**
