### PR TITLE
py mbp: Bind MultibodyPlant.GetBodiesWeldedTo

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For use w/ Anzu stuff

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14345)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@siyuanfeng-tri for both reviews, plz
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14345#-:-MMJKW0pD_DivXUWUahz:b-p8eju9)* status: LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned (waiting on @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14345#-:-MMJMdz63web05w1IpdZ:bg7igkv)* status: needs platform reviewer assigned (waiting on @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14345)* status: needs platform reviewer assigned (waiting on @siyuanfeng-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
Er, platform!
+@rpoyner-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14345#-:-MMJWIhOCYALveG982La:b-8fbomd)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @siyuanfeng-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14345#-:-MMMdRKG57Z-HCZHAujU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),siyuanfeng-tri

**Pull request merged**
