### PR TITLE
[workspace] No need to install spdlog CMake files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We only build spdlog from source in wheel builds, which don't care about this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17287)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review, please.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17287#-:-N3KaQop-3s__imdYNbU:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17287)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
