### PR TITLE
Upgrade Convex definition and use

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The two largest obvious new features:
  - A compliant `Mesh` using an obj can be declared (we'll use its convex hull).
  - A `Convex` referencing a volume .vtk file can be declared (we'll use its convex hull).

Under the hood:
  - This will improve the reliability and performance of the convex hull representation of `Convex` and `Mesh` within fcl.

This entails various changes:

- Convex hull is acquired from a `Mesh` or `Convex` directly.
  - `Convex` and `Mesh` get a deferred evaluation `convex_hull()` method. The corresponding infrastructure has been removed from `InternalGeometry` and the `GeometryState` implementation has been updated accordingly.
- `ProximityEngine` reifies `Mesh` and `Convex` using convex hull.
  - they currently share a common implementation until non-convex `Mesh` is finally supported.
  - Unit test changes
    - The assumption that a compliant `Convex` can't be constructed from .vtk is no longer true; we can compute its convex
      hull, so we can use it.
    - We've replaced the old cumbersome mechanism for confirming a `fcl::Convexd` representation with some introspection tools that allow us to look directly, simplifying the tests.
      - delete the .vtk and .obj files that supported the old test.
- `hydroelastic_internal` now uses the convex hull where available.
- Update shape documentation
  - Updated use of .vtk as a valid `Convex`.
  - `Convex` is now clarified as definitely using the convex hull for proximity allowing non-convex inputs.
  - spurious exception documentation removed.

- Incidental changes
  - `render_engine` had an erroneous dependency on `VolumeMesh`.
    - Changing the declarations of `shape_specification` dependencies has exposed that dependency.
  - Opportunistic correction of various typos near the changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.cc` line 96 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-Nt217Yq4fYq9W5RgHjk:-Nt217Yq4fYq9W5RgHjl:bslkukn) ([raw file](https://github.com/RobotLocomotion/drake/blob/910f7f1a4da89b4c558a065363f9c584487081a9/geometry/shape_specification.cc#L96)):*
> ```cpp
> const PolygonSurfaceMesh<double>& Convex::convex_hull() const {
>   if (hull_ == nullptr) {
>     hull_ = std::make_shared<PolygonSurfaceMesh<double>>(
> ```

BTW This assignment (and the ditto below) are data races.  Assigning to a shared_ptr is not intrinsically atomic.

(Posting now to save you time debugging any CI complaints that might trace back to here.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.cc` line 96 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-Nt217Yq4fYq9W5RgHjk:-NtHKbr2DCuWFbKJIdj6:ba2g3t8) ([raw file](https://github.com/RobotLocomotion/drake/blob/910f7f1a4da89b4c558a065363f9c584487081a9/geometry/shape_specification.cc#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This assignment (and the ditto below) are data races.  Assigning to a shared_ptr is not intrinsically atomic.

(Posting now to save you time debugging any CI complaints that might trace back to here.)
</blockquote></details>

D'oh!

If you wouldn't mind, I'd like you to take a glance at my solution. Also, do we need tester greater than reviewer inspection? It's a hard thing to test at the best of times.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.cc` line 96 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-Nt217Yq4fYq9W5RgHjk:-NtJ4g5y1uuITo7e9uiF:bn9buti) ([raw file](https://github.com/RobotLocomotion/drake/blob/910f7f1a4da89b4c558a065363f9c584487081a9/geometry/shape_specification.cc#L96)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

D'oh!

If you wouldn't mind, I'd like you to take a glance at my solution. Also, do we need tester greater than reviewer inspection? It's a hard thing to test at the best of times.
</blockquote></details>

I would expect shared_ptr atomic operations to be more natural and performant:

https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic

Something like: atomic load to see if we have it already; if yes, then just return it.  If not, make the hull and then do atomic cmpexchg to set the member field.
___
*[`geometry/shape_specification.cc` line 41 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtJ4s_w-ciDVCFgJ_B2:-NtJ4s_w-ciDVCFgJ_B3:biscc2p) ([raw file](https://github.com/RobotLocomotion/drake/blob/3335847400a97fe09ece032e62da6c337d7c6a93/geometry/shape_specification.cc#L41)):*
> ```cpp
> // ever becomes a need, we can make this an instance member by writing our
> // own copy-assignment and move semantics.
> std::mutex hull_mutex;
> ```

nit We don't need a global; it can be a function-local static at the worst.

https://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@DamrongGuoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-:-NtMvUpV2GsoTlzQVYWF:b-feiw5h)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 18 of 22 files at r2, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-:-NtNs0nBAe-ikozyLT4J:bnfp4nl)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/geometry_state.cc` line 716 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNMcaR8UqRdEZz8TcN:-NtNMcaR8UqRdEZz8TcO:b-9aj7d7) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/geometry_state.cc#L716)):*
> ```cpp
>   HullExtractor extractor;
>   geometry.shape().Reify(&extractor);
>   return extractor.convex_hull();
> ```

Does the returned value become a dangling pointer after `extractor` gets out of scope?



_Code quote:_
```cpp
  return extractor.convex_hull();
```
___
*[`geometry/geometry_state.cc` line 1106 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNbAgh9ArTZG2YgnB3:-NtNbAgh9ArTZG2YgnB4:b-kthrlj) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/geometry_state.cc#L1106)):*
> ```cpp
> 
>   // TODO(SeanCurtis-TRI): if RoleAssign == kReplace I *may* not need to
>   // regenerate a convex hull. However, for now, we'll do it blindly.
> ```

Should we remove this TODO?
___
*[`geometry/proximity_engine.cc` line 884 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNdVjJ2hqGwyqhWDKs:-NtNdVjJ2hqGwyqhWDKt:b-ha5itr) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/proximity_engine.cc#L884)):*
> ```cpp
>     //  (kHydroGroup, kRezHint). We should make exception for Mesh and Convex
>     //  since they don't need resolution hint.
>     ProcessGeometriesForDeformableContact(mesh, user_data);
> ```

Should we remove the extra call to `ProcessGeometriesForDeformableContact(mesh, user_data);`?



_Suggestion:_
```cpp
    ProcessGeometriesForDeformableContact(mesh, user_data);
```
___
*[`geometry/shape_specification.h` line 209 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNfZnE5w06GCGLlx8G:-NtNfZnE5w06GCGLlx8H:b6emi9h) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/shape_specification.h#L209)):*
> ```objc
>    given file path. Optionally uniformly scaled by the given scale factor.
> 
>    The mesh file referenced can be an .obj or a volume mesh in a .vtk.
> ```

BTW, please add "tetrahedral" to be precise. VTK files may have other kinds of volume meshes too (hexahedra, polyhedra, prisms, etc.).



_Suggestion:_
```objc
   The mesh file referenced can be an .obj or a tetrahedral volume mesh in a .vtk.
```
___
*[`geometry/shape_specification.h` line 367 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNq_pQ1J0RJemOOKee:-NtNq_pR2JTBgIHYbi9P:b-bec666) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/shape_specification.h#L367)):*
> ```objc
> // TODO(DamrongGuoy): Update documentation when mesh is fully supported (i.e.,
> // doesn't require equivocation here).
> /** Definition of a general (possibly non-convex) triangular surface mesh.
> ```

BTW, compliant hydroelastics and deformables use tetrahedral meshes.



_Suggestion:_
```objc
/** Definition of a general (possibly non-convex) triangular surface mesh
or tetrahedral volume mesh.
```
___
*[`geometry/shape_specification.h` line 373 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNhivk4cFcaMGD-9_-:-NtNhivk4cFcaMGD-9_0:bj84bi6) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/shape_specification.h#L373)):*
> ```objc
>  QueryObject's proximity queries for more details. The one notable exception is
>  for a Mesh specified as rigid hydroelastic; in that case, the general mesh is
>  used directly. This convex-hull substitution is a regrettable stop-gap solution
> ```

In addition to the exception for rigid hydroelastic, please add these exceptions too:

1. compliant hydroelastic with VTK tetrahedral mesh
2. deformable with VTK tetrahedral mesh



_Suggestion:_
```objc
 QueryObject's proximity queries for more details. The notable exceptions are
 for a Mesh specified as
   - rigid hydroelastic
   - compliant hydroelastic with VTK file of a tetrahedral mesh
   - deformable geometry with VTK file of a tetrahedral mesh
 in those cases, the general mesh is
 used directly. The convex-hull substitution is a regrettable stop-gap solution
```
___
*[`geometry/test/proximity_engine_test.cc` line 268 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtNmfVfDs2xDY7Row8c:-NtNmfVfDs2xDY7Row8d:b-p7l121) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf88e95f47b71fddf78de483d35af60fa34e19e9/geometry/test/proximity_engine_test.cc#L268)):*
> ```cpp
>     engine.AddDynamicGeometry(convex, {}, convex_id, soft_properties);
>     EXPECT_EQ(ProximityEngineTester::hydroelastic_type(convex_id, engine),
>               HydroelasticType::kSoft);
> ```

According to https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity_properties.h#L90, we should write `kCompliant` instead of `kSoft`.
```C++
  // Legacy alias. TODO(#17147) Remove this alias.
  kSoft = kCompliant,
```



_Suggestion:_
```cpp
              HydroelasticType::kCompliant);
```

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/geometry_file_formats_doxygen.h` line 34 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtRWL9R5I2b-M48X08B:-NtSDKqX7_297bFdBu31:b-4a2sg5) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@DamrongGuoy your comments inspired me to also visit *this* file and update its text. PTAL

The one controversial question is this assertion about `Convex`. The assertion that the `Convex` *always* uses a convex hull everywhere won't be true until the *next* PR.

So, should I bump *this* change to the follow-up PR? Or are you comfortable with it being a lie (briefly)?
</blockquote></details>

This is fine.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/geometry_file_formats_doxygen.h` line 34 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtRWL9R5I2b-M48X08B:-NtSEZFI9qc3Fi02DLtZ:b-ucfkn4) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L34)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

This is fine.
</blockquote></details>

Thanks.

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: feature) Platform :lgtm: with some questions.

> Reviewed 15 of 22 files at r2, 11 of 12 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-:-NtTVIwzDEtm2MBgJktv:bhk1mj)* status: 6 unresolved discussions

___
*[`geometry/geometry_file_formats_doxygen.h` line 68 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtSQNt-9BB8LlJIwGBZ:-NtSQNt-9BB8LlJIwGB_:b-vrse1s) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L68)):*
> ```objc
>   - @ref QueryObject::ComputePointPairPenetration "Point contact"
>   - @ref QueryObject::ComputeContactSurfaces "Hydroelastic contact" where the
>     mesh has been declared "compliant".
> ```

Is this accurate? If a `Mesh` geometry is declared as "compliant" and it contains a path to a vtk file, then the geometry is used as-is instead of convex-hulled, right? What am I missing here?



_Code quote:_
```objc
  - @ref QueryObject::ComputeContactSurfaces "Hydroelastic contact" where the
    mesh has been declared "compliant".
```
___
*[`geometry/geometry_file_formats_doxygen.h` line 211 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtSRmlD2sYqIw3tNxpm:-NtSRmlD2sYqIw3tNxpn:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L211)):*
> ```objc
> 
>  - Proximity role
>     - .gltf files *can* be used with the Convex shape type (ad indicated
> ```

typo



_Suggestion:_
```objc
as
```
___
*[`geometry/geometry_file_formats_doxygen.h` line 264 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtSnUPVB9nwdkOxjAOV:-NtSnUPW2wq8N7G1Qk9N:bupx3fv) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L264)):*
> ```objc
>     - When specified as Mesh without hydroelastic properties, it is treated as
>       a non-convex surface mesh; its convex hull is used as documented above.
>

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-:-NtWUbe10u6vPH4RmFRj:b-zcjvte)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees DamrongGuoy,xuchenhan-tri(platform)

___
*[`geometry/geometry_file_formats_doxygen.h` line 68 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtSQNt-9BB8LlJIwGBZ:-NtWScBuDjKUi_evNiy-:bsj646i) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L68)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is this accurate? If a `Mesh` geometry is declared as "compliant" and it contains a path to a vtk file, then the geometry is used as-is instead of convex-hulled, right? What am I missing here?
</blockquote></details>

Corrected.
___
*[`geometry/geometry_file_formats_doxygen.h` line 264 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtSnUPVB9nwdkOxjAOV:-NtWS0jPB5oTZHeQxfzy:bkpkp66) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/geometry_file_formats_doxygen.h#L264)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit can you use `xuchenhan-tri` for easier grepping?
</blockquote></details>

That was me being stupidly lazy. I should've just searched around. Sorry about that -- I'm glad you coincidentally ended up as reviewer.  :)
___
*[`geometry/proximity_engine.cc` line 864 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtSqeoi7eDJjAnVjJVT:-NtWRcNWEkms8SbYEF2Y:b7nfmkn) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/proximity_engine.cc#L864)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, the name of the function tripped me up for a second. I thought this function is 100% about convex hull of things, but instead it also makes potentially non-convex meshes for hydro meshes and deformable meshes. Consider adding a note about what this function does.
</blockquote></details>

Done (I've also massaged the name.)
___
*[`geometry/proximity/test/hydroelastic_internal_test.cc` line 764 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21147#-NtTRqCME9IeLoXHo0ss:-NtWQxx-933lfLM20EaN:bivd47z) ([raw file](https://github.com/RobotLocomotion/drake/blob/498697021e9eb5d70fb948cb63af7e868a07876c/geometry/proximity/test/hydroelastic_internal_test.cc#L764)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, do we need a test on rigid convex from vtk file?
</blockquote></details>

I've elaborated the TODO for why the answer, at best, is probably "maybe?".

**Pull request merged**
