### PR TITLE
Fix -Wunused-private-field warnings

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is portion of #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2604)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I have fired up a one-off `mac-clang-experimental-matlab` build of this PR, to ensure there are no lurking warnings post-merge.  Results [will appear here](https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-experimental-matlab/39/).

**Comment by jwnimmer-tri** [comment]
All builds have passed, so I'll open this up for review and merge now.

+@david-german-tri for feature and platform review.

/cc @sammy-tri and @RussTedrake in case you'd like to double check that these member fields are in fact unwanted.

**Comment by RussTedrake** [comment]
Lgtm

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2604#-:-KKoJpeueIS-jQcrDwWE:1417088721)*

**Pull request merged**
