### PR TITLE
Modified car simulation to support both SDF and URDF-based world models 

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2319

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2576)

### CODE REVIEW

**Comment by liangfok** [comment]
I'm going to add a unit test to lock in this change.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKT8WdCmhK8wOnGpHtN:-818788402)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2126/ and is thus ready for review.
+@rpoyner-tri for feature review since he originally discovered the broken demo.
+@sherm1 for platform review since the next work day is Monday.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKVmeKrslLx7hr2K6Dv:592541986)*

**Comment by rpoyner-tri** [comment]
glad to see this getting resolved! nits only...

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-KKa36EDNDdg1ufe5eu1:-KKa36EEJZkBv5yoS2s7:-1189092463) ([raw file](https://github.com/robotlocomotion/drake/blob/f48e0b56b8e7f40a08973e77598842b3d230eecd/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L22)):*
> ```cpp
>   std::unique_ptr<RigidBodySystem> rigid_body_sys(new RigidBodySystem());
> 
>   // Adds the same SDF to the rigid body system twice. Both models are connected
> ```

This comment appears stale versus the code it accompanies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKa3u_bYPFCqdgwfw2e:679971346)*

**Comment by liangfok** [comment]
Thanks for the review. PTAL.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-KKa36EDNDdg1ufe5eu1:-KKaT55WwaAGJgSLycMv:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/f48e0b56b8e7f40a08973e77598842b3d230eecd/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L22)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> This comment appears stale versus the code it accompanies.
</details>
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKaT6czmuhSekqHh0Gs:-1216480099)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKaixm7uXgKm2j93p4F:1417088721)*

**Comment by liangfok** [comment]
Since `clang-mac` CI failure is clearly a flake, this PR is ready for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKaqq0x-7TaKdGinsoY:1207358679)*

**Comment by sherm1** [comment]
One nit, otherwise :lgtm: (platform).

---

Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/world.urdf, line 131 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-KKffgD8AaiBZdSB2HJa:-KKffgD8AaiBZdSB2HJb:-413658508) ([raw file](https://github.com/robotlocomotion/drake/blob/d293903c77e7303280994bc72cb0ffafb292352e/drake/systems/plants/test/rigid_body_system/world.urdf#L131)):*
> ```XML
>     <origin xyz="57 0 0"/>
>   </joint>
> </robot>
> ```

Missing newline at eof.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKffm9SJbSsbjXzBib5:1973112038)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/world.urdf, line 131 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-KKffgD8AaiBZdSB2HJa:-KKfjSi_VcLhXnavfdps:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d293903c77e7303280994bc72cb0ffafb292352e/drake/systems/plants/test/rigid_body_system/world.urdf#L131)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Missing newline at eof.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKfjV5HXgbn1gq3GIqI:701515998)*

**Comment by sherm1** [comment]
All good; waiting for CI.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKfqeDDRhChekLUxNoy:1247770136)*

**Comment by liangfok** [comment]
CI passed. With two :lgtm:, I'm going to merge!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2576#-:-KKiQyE3IYzGOlru722K:996727424)*

**Pull request merged**
