### PR TITLE
Implement elevation bounds in `monolane` maliput backend.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6225)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@jadecastro for feature review, please.  (The most substantive changes are in the ToLanePosition() code and its unit tests.)

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-:-KlZhE2SvakXCqBeOl4I:b-ig1vgz)*

**Comment by jadecastro** [comment]
Looks good, with a few comments below.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/monolane/ring.yaml, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klv43eKcgDPXL9lN23T:-Klv43eLqg4QHfkLAZxM:b-bgbgpa) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/ring.yaml#L10)):*
> ```YAML
>   elevation_bounds: [0, 5]
>   position_precision: .01
>   elevation_bounds: [0, 5]
> ```

Is this duplicate intentional? 

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klx2UbgaaCWd7mUePkx:-Klx2UbgaaCWd7mUePky:b-hochor) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L38)):*
> ```cpp
> GTEST_TEST(MonolaneLanesTest, FlatLineLane) {
>   CubicPolynomial zp {0., 0., 0., 0.};
>   const double half_width = 10.;
> ```

BTW, you might fix `half_width` to be either `kHalfWidth` or `kDriveableBounds`.

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 284 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klx381AP8DpVUA03OwK:-Klx381AP8DpVUA03OwL:bi5pzaw) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L284)):*
> ```cpp
>       {"l2_with_z"},
>       center, radius, theta0, d_theta,
>       {-5., 5.}, {-half_width, half_width}, {0., 5.},
> ```

BTW, `5.` --> `kMaxHeight`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-:-Klx5W1m7Yw2Y6yADwjV:bom2uju)*

**Comment by maddog-tri** [comment]
Comments addressed, please take a look.

Summoning +@sammy-tri for platform review, since confidence is high.  (FYI, the root of the changes here is the implementation of the `do_elevation_bounds(...)` method declared in `monolane/lane.h`.  Everything else is a result of that.)

---

Review status: 25 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/monolane/ring.yaml, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klv43eKcgDPXL9lN23T:-KlxrIuEVNHZKCSZDapl:b-4ltbcu) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/ring.yaml#L10)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Is this duplicate intentional? 
</blockquote></details>

Done. (No, not intentional... ?)

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klx2UbgaaCWd7mUePkx:-Klxs-mIjmS-xo8WWBw0:bbuim6p) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L38)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, you might fix `half_width` to be either `kHalfWidth` or `kDriveableBounds`.
</blockquote></details>

Done.  (Yay, `kHalfWidth` is the same number of characters as `half_width`!)

---

*[drake/automotive/maliput/monolane/test/monolane_lanes_test.cc, line 284 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klx381AP8DpVUA03OwK:-KlxsZhQlA8VK2eZjM9o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/test/monolane_lanes_test.cc#L284)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, `5.` --> `kMaxHeight`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-:-Klxtnq49Xo54fOySXra:baa2gk0)*

**Comment by jadecastro** [comment]
Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/monolane/ring.yaml, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klv43eKcgDPXL9lN23T:-Klxvb3eDx7PU7S2rSyY:b-cir2ln) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/ring.yaml#L10)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done. (No, not intentional... ?)
</blockquote></details>

(I hadn't delved into the `.yaml` files too deeply before now - making sure I wasn't missing anything!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-:-KlxvsWp3Uow--riyRk3:bnfp4nl)*

**Comment by jadecastro** [comment]
Reviewed 1 of 2 files at r2.
Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 25 of 27 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-:-Kly50rLxp1iruMo3PJB:bnfp4nl)*

**Comment by maddog-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/monolane/ring.yaml, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klv43eKcgDPXL9lN23T:-Kly7zkO6021lv4SXSUJ:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/ring.yaml#L10)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

(I hadn't delved into the `.yaml` files too deeply before now - making sure I wasn't missing anything!)
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225)*

**Comment by maddog-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/monolane/ring.yaml, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6225#-Klv43eKcgDPXL9lN23T:-Kly82uvnn4bUXSfVKrT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c78edc22dd5873406377d12d8b24e232acacdf72/drake/automotive/maliput/monolane/ring.yaml#L10)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6225)*

**Pull request merged**
