### PR TITLE
Add a DISABLE_MATLAB option.

### LINKED ISSUE #2080: Add USE_MATLAB build option, to force-disable matlab
Per the discussion in #1860, starting at [this comment](https://github.com/RobotLocomotion/drake/issues/1860#issuecomment-204397872).

As with other optional prerequisites of Drake, we should have the ability to run a build and test while excluding matlab from the picture, even if it happens to be installed on the system.

### PR DESCRIPTION
**Pull request by david-german-tri**
This option does not thwart other externals that want to look for MATLAB, but it does disable MATLAB in drake itself.

@jwnimmer-tri @sherm1 is this what you wanted?

Resolves #2080

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2109) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@jonathan-owens&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jonathan-owens">jonathan-owens</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by sammy-tri** [comment]
It's certainly the behavior I personally want. :)  I'm holding off on claiming I've reviewed it since I don't know the build well enough for it to be obviously right to me by inspection and I haven't installed matlab yet to test...

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFQ85BOLujCFNlyxIYB:-1791211898)*

**Comment by jamiesnape** [comment]
Note that this has also disabled MATLAB in the `linux_matlab` build.

**Comment by david-german-tri** [comment]
@jamiesnape Good catch.  I flipped the semantics to DISABLE_MATLAB, which I think will fix it...

**Comment by billhoffman** [comment]
This will also conflict with the new cmake based matlab test PR (https://github.com/RobotLocomotion/drake/pull/2097)  

I think to maintain the feature that if matlab is in the PATH then turn it on, it should be something like:
find_program(matlab matlab)
set(default_use_matlab OFF)
if(matlab)
 set(default_use_matlab ON)
endif()
option(USE_MATLAB "enable matlab" ${default_use_matlab})

**Comment by david-german-tri** [comment]
@billhoffman I'm not sure I see the conflict.  If we wrap `mex_setup()` in a conditional, doesn't the rest of your #2097 work just as if MATLAB were absent?  `MATLAB_FOUND` will be false, and `add_matlab_test` will just return.  What am I missing?

**Comment by billhoffman** [comment]
No big deal, just some of the same lines of code touched so it might conflict.  Should be OK.

**Comment by david-german-tri** [comment]
Confirmed that linux-matlab works with the revised PR.  Kitware folks, any further comments?  If not, I'll hand it off to someone from TRI for second review.

**Comment by david-german-tri** [comment]
+@liangfok 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFdjGkw58xT6RmMGrnR:-1026123679)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 84 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-KFdlv2SsrWuPTbJjVqU:-KFdlv2SsrWuPTbJjVqV:2088265463) ([raw file](https://github.com/robotlocomotion/drake/blob/778b967e757f0f039c669a9bde51539c52ae616e/CMakeLists.txt#L84)):*
I think there is a subtle bug here. If I run `make options` and then set `DISABLE_MATLAB` to be `ON`, option`WITH_SPOTLESS` is still present and is by default `ON`.  In this case, I believe Spotless will still be downloaded even if Matlab is disabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 84 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-KFdlv2SsrWuPTbJjVqU:-KFeZTMJMDzkQ4Smyqg8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/778b967e757f0f039c669a9bde51539c52ae616e/CMakeLists.txt#L84)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109)*

**Comment by liangfok** [comment]
Found a possible bug with the fix. PTAL.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CMakeLists.txt, line 84 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-KFdlv2SsrWuPTbJjVqU:-KFeaqOGq0-NUeiPjbWA:-473122223) ([raw file](https://github.com/robotlocomotion/drake/blob/778b967e757f0f039c669a9bde51539c52ae616e/CMakeLists.txt#L84)):*
I believe there's still a problem, though I'm not sure if the following sequence of actions is legal:

1. Run `make options` and change `DISABLE_MATLAB` to be `ON`
2. Type `c` to configure the build system. At this point, the `WITH_SPOTLESS` option disappears as expected.
3. Change `DISABLE_MATLAB` back to `OFF`.
4. Type `c` to reconfigure the build system. At this point, the `WITH_SPOTLESS` option does not return. I believe it should return now that `DISABLE_MATLAB` is `ON`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFebTxjT1fvqW1Fy1GX:-1652443544)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CMakeLists.txt, line 84 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-KFdlv2SsrWuPTbJjVqU:-KFec2nyE4DYdCrAXByA:399010899) ([raw file](https://github.com/robotlocomotion/drake/blob/778b967e757f0f039c669a9bde51539c52ae616e/CMakeLists.txt#L84)):*
Nevermind. it shows up at the very top (unsorted). LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109)*

**Comment by david-german-tri** [comment]
+@sherm1 could you please take a look for platform review?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFedvV3aifFGv2ReZJ3:114318672)*

**Comment by liangfok** [comment]
Sorry. I just noticed that even after I set `DISABLE_MATLAB` to be `ON` Spotless was still being downloaded (at least the directory `[drake distro]/externals/spotless/` was being created). Let me try replicating this result now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFeergzmLgcHIUffz5b:565713976)*

**Comment by liangfok** [comment]
I confirm that when `DISABLE_MATLAB` being set to `ON`, the directory `[drake distro]/externals/spotless` is still being created. However, the directory and its subdirectories are empty, so I think it is OK.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFegEgN1b24hxosVSou:1368384571)*

**Comment by david-german-tri** [comment]
Yeah, I'm seeing that too.  I agree it's probably not a big deal, but I'll try to work out why.  Thanks for catching it!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFeinUmuaRne1gh-gQh:-596728629)*

**Comment by sherm1** [comment]
> +@sherm1 could you please take a look for platform review?

will do.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFemW1RXnoYiFzS5iHS:-35320921)*

**Comment by david-german-tri** [comment]
@liangfok I think the `externals/spotless/pod-build` directory is getting created during the `configure` step of `make options`, not during `make` itself.

**Comment by liangfok** [comment]
Yes. I can confirm that `externals/spotless/pod-build` is created immediately upon executing `make options`. I guess this problem is not worth fixing at this time.

**Comment by sherm1** [comment]
Sweet! Looks great @david-german-tri. I tried this in Windows with Matlab installed (though nonfunctional). I chose `DISABLE_MATLAB`, verified that the right message came out, and saw that spotless wasn't built either. All 33 C++-only tests passed.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFfpVMi6bxSauR-fOsD:1082785467)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2109#-:-KFfqDE--vCIvWNW33Wb:1417088721)*

**Comment by sherm1** [comment]
@david-german-tri, this is ready to merge but needs an update to the current master branch first.

**Pull request merged**
