### PR TITLE
Revert "Double pendulum SDFormat demo (#6496)"

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This reverts commit 46b4b829560d1a1ddc493d3a5d9a1f0b63e5c90d.
Dear @hidmic,

The on-call build cop, @m-chaturvedi, believes that your PR 6496 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-tsan/15/consoleText
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-tsan-everything/15/consoleText

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6629)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-cdash-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Comment by fbudin69500** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6629#-:-Kpa4xijW3mSTDDZgvJ6:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@SeanCurtis-TRI for platform review, please.

**Comment by m-chaturvedi** [comment]
-@SeanCurtis-TRI [ because we're dropping this revert and going ahead with removing the test, https://github.com/RobotLocomotion/drake/pull/6632 ]

**Pull request closed without merging**
