### PR TITLE
geometry/proximity: Remove name from MeshFieldLinear

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #15616.

Instead of having all users of MeshFieldLinear guess an appropriate
name, defer the naming decision to the writing of a vtk file. The name
was not used elsewhere in Drake, and no constraints were ever enforced
on it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@damrongguoy for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkmTzBT9-A7FuYttJi0:bh9uixl)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Thank you!  I'll review it later today.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-Mkma7U1Cbl1fEJT26u5:b-8xfvyl)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
@xuchenhan-tri These changes break the build of ` multibody/fixed_fem/dev`.  Do you have an objection? Or you can adapt to the API change?  (Actually it might be my code in fixed_fem/dev, so I'm ok with this API change.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkmaiguADPXseXl_ddV:b-xfl2n0)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by xuchenhan-tri — COMMENTED** [review]
I'm fine with the changes. I scanned over the CI failures and it should be a easy fix.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkmgMai62j2kAOljv-Y:b-1txfrj)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
I'll fix the CI failures and post a new rev.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-Mkn-abS7xvvK4Xsdl9D:b-cuj5ub)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by xuchenhan-tri — COMMENTED** [review]
The dev changes LGTM.

> Reviewed 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MknWVtI4ciL8tGa0P5T:b5i7ztq)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with optional cosmetic requests.

> Reviewed 17 of 17 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkoDqniCyPvLagqiKxn:b5hcn1q)* status: 13 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/proximity/mesh_half_space_intersection.cc, line 473 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-MknfCEe5Dcg4yLGuehb:-MknfCEe5Dcg4yLGuehc:b-9jqh7b) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/mesh_half_space_intersection.cc#L473)):*
> ```cpp
>   auto field_W = std::make_unique<SurfaceMeshFieldLinear<T, T>>(
>       std::move(vertex_pressures), mesh_W.get(),
>       false /* calc_gradient */);
> ```

Clang-format like this (one less line)?
```
  auto field_W = std::make_unique<SurfaceMeshFieldLinear<T, T>>(
      std::move(vertex_pressures), mesh_W.get(), false /* calc_gradient */);
```
___
*[geometry/proximity/mesh_plane_intersection.cc, line 212 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-MkngQFTDP6EwIds9Wk-:-MkngQFTDP6EwIds9Wk0:bhpc41l) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/mesh_plane_intersection.cc#L212)):*
> ```cpp
>   auto field_W = std::make_unique<SurfaceMeshFieldLinear<T, T>>(
>       std::move(surface_e), mesh_W.get(),
>       false /* calculate_gradient */);
> ```

Clang-format like this (one less line)?
```C++
  auto field_W = std::make_unique<SurfaceMeshFieldLinear<T, T>>(
      std::move(surface_e), mesh_W.get(), false /* calculate_gradient */);
```
___
*[geometry/proximity/test/contact_surface_test.cc, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-MknuNt0-z5DTx6TamQi:-MknuNt0-z5DTx6TamQj:byswdsd) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/contact_surface_test.cc#L118)):*
> ```cpp
>   vector<T> e_values = {e0, e1, e2, e3};
>   auto e_field = make_unique<SurfaceMeshFieldLinear<T, T>>(
>       move(e_values), surface_mesh.get());
> ```

Clang-format?
```C++
  auto e_field = make_unique<SurfaceMeshFieldLinear<T, T>>(move(e_values),
                                                           surface_mesh.get());
```
___
*[geometry/proximity/test/contact_surface_test.cc, line 311 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mknv4Rh2A94HTQF94Hw:-Mknv4Rh2A94HTQF94Hx:b2n4bj6) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/contact_surface_test.cc#L311)):*
> ```cpp
>   field2_values.at(0) += 2.0;
>   auto field2 = make_unique<SurfaceMeshFieldLinear<double, double>>(
>                     move(field2_values), mesh2.get());
> ```

Clang-format?
```C++
  auto field2 = make_unique<SurfaceMeshFieldLinear<double, double>>(
      move(field2_values), mesh2.get());
```
___
*[geometry/proximity/test/contact_surface_test.cc, line 337 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-MknvK985lgNiujPCvEV:-MknvK985lgNiujPCvEW:bmmrne0) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/contact_surface_test.cc#L337)):*
> ```cpp
>       id_M, id_N, move(mesh),
>       make_unique<SurfaceMeshFieldLinear<double, double>>(
>           move(e_MN_values), mesh_pointer));
> ```

Clang-format?
```C++
  ContactSurface<double> dut(
      id_M, id_N, move(mesh),
      make_unique<SurfaceMeshFieldLinear<double, double>>(move(e_MN_values),
                                                          mesh_pointer));
```
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 1288 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko1QkV4DIAFBANbwMd:-Mko1QkV4DIAFBANbwMe:bk5vg7p) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/mesh_plane_intersection_test.cc#L1288)):*
> ```cpp
>     const VolumeMesh<double> dupe_mesh_F = TrivialVolumeMesh(X_FM_, false);
>     VolumeMeshFieldLinear<double, double> dupe_field_F{
>       vector<double>{0, 0, 0, 1, 0, 0, 0, -1}, &dupe_mesh_F};
> ```

Clang-format?
```C++
    VolumeMeshFieldLinear<double, double> dupe_field_F{
        vector<double>{0, 0, 0, 1, 0, 0, 0, -1}, &dupe_mesh_F};
```
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 1472 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko1cv16oOw2QFo5jfH:-Mko1cv16oOw2QFo5jfI:bhc0svo) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/mesh_plane_intersection_test.cc#L1472)):*
> ```cpp
>   const VolumeMesh<double> mesh_F = TrivialVolumeMesh(RigidTransformd{});
>   const VolumeMeshFieldLinear<double, double> field_F{
>     vector<double>{0.25, 0.5, 0.75, 1, -1}, &mesh_F};
> ```

Clang-format?
```C++
  const VolumeMeshFieldLinear<double, double> field_F{
      vector<double>{0.25, 0.5, 0.75, 1, -1}, &mesh_F};
```
___
*[geometry/proximity/test/mesh_to_vtk_test.cc, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko23rL8_I5DsR4lKG9:-Mko23rL8_I5DsR4lKGA:bmnhrkp) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/mesh_to_vtk_test.cc#L55)):*
> ```cpp
>   WriteVolumeMeshFieldLinearToVtk(
>       temp_directory() + "/" + "box_tet_pressure.vtk ",
>       "pressure", pressure,
> ```

If you don't mind, could we have `"Pressure[Pa]"` (capitalized with Pascal unit and no space), please?  I understand it might not be a part of this PR, so this request is completely optional.

FYI, the [VTK format](https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf) specification, Page 5, says:
```
This is a character string (without embedded whitespace) used to identify a particular data.
```
, and the code (mesh_to_vtk.cc) will silently change `<space>` to `_`.
___
*[geometry/proximity/test/mesh_to_vtk_test.cc, line 95 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko2jw_5oz7pgjfrNjG:-Mko2jw_5oz7pgjfrNjH:b-aepuos) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/mesh_to_vtk_test.cc#L95)):*
> ```cpp
>   WriteSurfaceMeshFieldLinearToVtk(
>       temp_directory() + "/" + "box_rigid_soft_contact_pressure.vtk",
>       "pressure", *contact_pressure,
> ```

I've the same comment as the call to `WriteVolumeMeshFieldLinearToVtk()` above (`"Pressure[Pa]"`).
___
*[multibody/plant/test/hydroelastic_traction_test.cc, line 677 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko58_IAPrMzCBEqmxm:-Mko58_J0TO2kR5K6QDh:bbpkjcq) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/multibody/plant/test/hydroelastic_traction_test.cc#L677)):*
> ```cpp
>   auto field = std::make_unique<
>       geometry::SurfaceMeshFieldLinear<AutoDiffXd, AutoDiffXd>>(
>           std::move(values), mesh_W.get(), false);
> ```

Clang-format?
```C++
  auto field = std::make_unique<
      geometry::SurfaceMeshFieldLinear<AutoDiffXd, AutoDiffXd>>(
      std::move(values), mesh_W.get(), false);
```
___
*[multibody/plant/test/hydroelastic_traction_test.cc, line 804 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko5RUe6Eg905R-GJii:-Mko5RUe6Eg905R-GJij:b-p74dmc) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/multibody/plant/test/hydroelastic_traction_test.cc#L804)):*
> ```cpp
>       null_id, null_id, std::move(mesh),
>       std::make_unique<MeshFieldLinear<double, SurfaceMesh<double>>>(
>           std::move(e_MN), mesh_pointer));
> ```

Clang-format?
```C++
    contact_surface_ = std::make_unique<ContactSurface<double>>(
        null_id, null_id, std::move(mesh),
        std::make_unique<MeshFieldLinear<double, SurfaceMesh<double>>>(
            std::move(e_MN), mesh_pointer));
```
___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 254 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko7GwQDBI8S8XHGEvl:-Mko7GwU49tOSG2xiQ_t:bmxbmus) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L254)):*
> ```cpp
>     const std::string file_name("box_signed_distance.vtk");
>     geometry::internal::WriteVolumeMeshFieldLinearToVtk(
>         file_name, "signed distance", box_geometry.signed_distance(),
> ```

`"Approximated signed distance"` please.  That's what `mesh_utilities.cc` specified before this PR.  (Or even better, `"Approximated signed distance [meter]"`)

```C++
    geometry::internal::WriteVolumeMeshFieldLinearToVtk(
        file_name, "Approximated signed distance [meter]",
        box_geometry.signed_distance(),
        "Signed distance function in " + file_name);
```

It will look like this in Paraview (notice the legend):

___
*[multibody/fixed_fem/dev/test/mesh_utilities_test.cc, line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mko8WLQACZbfgVfgkKR:-Mko8WLU9TowyGB5kJUx:b-1zvanu) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/multibody/fixed_fem/dev/test/mesh_utilities_test.cc#L270)):*
> ```cpp
>     const std::string file_name("refined_box_positive_distance.vtk");
>     geometry::internal::WriteVolumeMeshFieldLinearToVtk(
>         file_name, "positive distance function",
> ```

`"Positive distance [meter]"` please.

**Review by DamrongGuoy — COMMENTED** [review]
@rpoyner-tri How did you do all these changes so quickly?  Is there any tip on how to change a few lines in so many files? Just go one by one?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkoECRJ5Kr9j442XvPY:b1plxo4)* status: 13 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
http://bit-builder.blogspot.com/2012/06/lean-on-compiler.html -- that, and learning to recognize patterns in c++ compiler error storms :)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-Mkr6-_EAY-WiEx5qGA6:btrgtxe)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkrBnT91tt5GIv-SRxs:b-trzqz1)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @DamrongGuoy, @jwnimmer-tri, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 9 of 17 files at r1, 4 of 7 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15847#-Mkr_QBgAR3ezmZE0osk:-Mkr_QBh3cThvH6Bx31t:bd5imly) (no related file):*
I wrote up https://github.com/rpoyner-tri/drake/pull/2 so we have deprecation instead of a breaking change.

I timed it on my stopwatch at 5m01s of effort.  When deprecation is easy, and downstream impact is unknown, we should prefer to deprecated instead of breaking change.

+(release notes: newly deprecated) 

---
___
*[geometry/proximity/test/contact_surface_test.cc, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15847#-MknuNt0-z5DTx6TamQi:-MkrXN4t1H4iiPK222rH:b-4brc1k) ([raw file](https://github.com/robotlocomotion/drake/blob/4fd90c33fb0db08289fda02d3b9a5b94de121c57/geometry/proximity/test/contact_surface_test.cc#L118)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Clang-format?
```C++
  auto e_field = make_unique<SurfaceMeshFieldLinear<T, T>>(move(e_values),
                                                           surface_mesh.get());
```
</blockquote></details>

FYI That is a very poorly worded defect.  Yes, the clang-format chooses a formatting different than what is here, but why is that remarkable?  Was there something wrong with what was here?  If so, say what is wrong.  Is the suggestion better in some way, even though the prior format was wrong?  If so, then say why it's better.

If your defect is "I am the notional owner of this file I personally prefer to have 59 characters of leading whitespace before each function argument, so they are off flying in never-never land", then just say that.  There is _no de jure_ defect that code must be consistent with what clang-format suggests.

If you want certain folders to have clang-format enforced by the linter, then you should enable that in the BUILD file.  Otherwise, let us keep moving faster and save us the hassle.  Posting piles of review comments for manual transcription for things that are _not actually defects_ is a waste of everyone's time.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15847#-:-MkrcQ8VClk6TJGJ8B47:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Pull request merged**
