### PR TITLE
Marked a couple things const and moved member variable in AutomotiveSimulator.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5483)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for all three levels of review please.

\CC: @maddog-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5483#-:-Kf9SHNvKg51Gf5Fq4Mt:b6so14p)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.h, line 266 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5483#-Kf9TTJxaqe4ETkM0IGG:-Kf9TTJxaqe4ETkM0IGH:b-nvwgec) ([raw file](https://github.com/robotlocomotion/drake/blob/7bc8b186962ba92ef387d57e03aab9a10a530c74/drake/automotive/automotive_simulator.h#L266)):*
> ```objc
>   // initialize the simulation's diagram's state and to connect the
>   // EndlessRoadCars to the EndlessRoadOracle sensor.
>   std::map<EndlessRoadCar<T>*, EndlessRoadCarState<T>> endless_road_cars_;
> ```

BTW If this PR's intent is to forward-port defect fixes from railcar PR back into endless, then this map key should also be `const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5483#-:-Kf9TFn_4ABwt5ETz2Rx:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.h, line 266 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5483#-Kf9TTJxaqe4ETkM0IGG:-Kf9UBcpgVpodx8wNCRz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7bc8b186962ba92ef387d57e03aab9a10a530c74/drake/automotive/automotive_simulator.h#L266)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If this PR's intent is to forward-port defect fixes from railcar PR back into endless, then this map key should also be `const`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5483)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5483#-:-Kf9UMz4gGenWN-IH0Ty:b-s794vx)*

**Pull request merged**
