### PR TITLE
[geometry] Add Rgba::Serialize support

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
`Rgba` serializes as an array-like value. The contents must have either three or four values and must all lie in the range [0, 1].

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

+@ggould-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762#-:-NAAE2IPCULo3_Ya52hc:bdebex)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`geometry/BUILD.bazel` line 396 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAEVo2179ABNdRadN3:-NAAEVo3EowVOX5cLUC-:bbrjj9x) ([raw file](https://github.com/robotlocomotion/drake/blob/39ad7174bca7eb633d6950cb6e41d25c0ac1b997/geometry/BUILD.bazel#L396)):*
> ```Starlark
>         "//common:essential",
>         "//common:name_value",
>         "//common/yaml:yaml_io",
> ```

nit `yaml_io` is used by the unit test, not the library itself.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762#-:-NAAbt8A5-1pM60Z6Pxq:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[`visualization/visualization_config.h` line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAafS3AWywSqeI8VUI:-NAAafS3AWywSqeI8VUJ:b1ycipq) ([raw file](https://github.com/robotlocomotion/drake/blob/39ad7174bca7eb633d6950cb6e41d25c0ac1b997/visualization/visualization_config.h#L30)):*
> ```objc
>     a->Visit(DRAKE_NVP(publish_illustration));
>     // N.B. See Rgba::Serialize() for explanation of the spellings for
>     // `default_illustration_color_rgba` and `default_illustration_color_rgba`.
> ```

nit: typo??



_Suggestion:_
```objc
proximity
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/rgba.h` line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAdKeg2FEfmnUo7Jry:-NAAdKehDthA2RSoddox:b-mck5gc) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8273e66dd99ca459d22707ddcae9a3d2553ae8/geometry/rgba.h#L92)):*
> ```objc
>    no fourth value is provided, alpha is defined a 1.0.
> 
>    When serializing a struct with an %Rgba member, it should *not* simply
> ```

nit This is a little bit stronger of a rule than I agree with.

I think if a schema designer wants an extra level of nesting, it's OK to allow them to do that?

```yaml
depth_to_color:
  too_near:
    rgba: [0.9, 0.9, 0]
  too_far:
    rgba: [0.9, 0, 0]
```

I do buy that the class overview should explain the bonus argument to Serialize, but I don't think we need to forbid using the default value.  (If the default value is wrong, we shouldn't even provide it.)



_Code quote:_
```objc
should *not*
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/rgba.h` line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAdKeg2FEfmnUo7Jry:-NAAem3DB5AMJn0qgppz:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8273e66dd99ca459d22707ddcae9a3d2553ae8/geometry/rgba.h#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is a little bit stronger of a rule than I agree with.

I think if a schema designer wants an extra level of nesting, it's OK to allow them to do that?

```yaml
depth_to_color:
  too_near:
    rgba: [0.9, 0.9, 0]
  too_far:
    rgba: [0.9, 0, 0]
```

I do buy that the class overview should explain the bonus argument to Serialize, but I don't think we need to forbid using the default value.  (If the default value is wrong, we shouldn't even provide it.)

</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`bindings/pydrake/geometry_py_common.cc` line 319 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAg1W9BJ8VFXRbn7Gj:-NAAg1WA0lSntt9ZmJHM:b8sie39) ([raw file](https://github.com/robotlocomotion/drake/blob/d33057c4f4ac690edf097d498ee94f8df8dad923/bindings/pydrake/geometry_py_common.cc#L319)):*
> ```cpp
>     constexpr auto& cls_doc = doc.Rgba;
>     py::class_<Class> cls(m, "Rgba", cls_doc.doc);
>     cls  // BR
> ```

nit (Optional) It would be a kindness to bind the default constructor here immediately.  It's the kind of thing we'll easily forget to cycle back to later.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762#-:-NAAiogGDaeFQBxt0XIj:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
(LGTM now, as co-conspirator.)

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762#-:-NAAj3osDJLN-fu88sJC:b-a713mj)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending whatever is wrong with bindings in CI.

> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762#-:-NAAsRXS0pXYp9OgxNEv:b-jolfrs)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[`geometry/rgba.h` line 20 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAArAqR-UAoufcButQF:-NAArAqR-UAoufcButQG:bl4ficw) ([raw file](https://github.com/robotlocomotion/drake/blob/b9fd886bf54e2028a3b83e4fe32849a19b31c819/geometry/rgba.h#L20)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Rgba);
> 
>   /** Default constructor produces fully opaque, white. */
> ```

nit Drop the comma here?



_Code quote:_
```objc
,
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 2 unresolved discussions (waiting on @ggould-tri, @rpoyner-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAyhjY861C-GHT4uYe:-NAAEIGj6s3E2fzMzKVx:b-47e870) (no related file):*
@jwnimmer-tri Regarding CI woes.

This approach interferes with the `DefAttributesUsingSerialize()` method for defining the attributes of a struct. The key is that, ultimately, the archive expects that the property being visited must be contained within the class being visited. With this implementation, the `VectorXd` on the stack obviously doesn't satisfy that requirement.

I did a quick test to confirm this is the cause. I hacked it so that the `VectorXd` is a member of `Rgba`. That resolved the issue.

I propose the following:

 - Leave the added private member to `Rgba` so that this can go through and not fight our binding infrastructure.
 - Post an issue about this for future resolution.

THoughts?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAyhjY861C-GHT4uYe:-NAB4BPx90qbPB7c_5RH:b-chtepj) (no related file):*
> Leave the added private member to Rgba so that this can go through and not fight our binding infrastructure.

If `DefAttributesUsingSerialize` visits the VectorXd then it will bind `config.default_illustration_color` to return a numpy instead of a `class Rgba`.

Perhaps the best solution here is just to change the syntax to:

```yaml
visualization:
  default_illustration_color:
      rgba: [0.8, 0.8, 0.8]
```

... and remove all of the tricks.

The other option would be keep the member field as `VectorXd` and promote the `ToRgba` helper function to public and use it everywhere.

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Leave the added private member to Rgba so that this can go through and not fight our binding infrastructure.

If `DefAttributesUsingSerialize` visits the VectorXd then it will bind `config.default_illustration_color` to return a numpy instead of a `class Rgba`.

Perhaps the best solution here is just to change the syntax to:

```yaml
visualization:
  default_illustration_color:
      rgba: [0.8, 0.8, 0.8]
```

... and remove all of the tricks.

The other option would be keep the member field as `VectorXd` and promote the `ToRgba` helper function to public and use it everywhere.
</blockquote></details>

I don't think this will work. removing "all of the tricks" would produce:


```yaml
 visualization:
    default_illustration_color:
        r: 0.8
        g: 0.8
        b: 0.8
        a: 0.8
```

The *ability* to turn four independent fields into an array is surely the trick that will most mystify the binder, yes? Or am I missing something?

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAyhjY861C-GHT4uYe:-NABQW8V8ukYqQQwLhpy:b2650km) (no related file):*
I wrote "all of the tricks", but that wasn't a good summary of what I meant.

Here's what I had in mind: https://github.com/RobotLocomotion/drake/commit/1c08e2cc42095f44d1ea82611555e36ffa48e6e2

It passes all tests for me.

> The ability to turn four independent fields into an array is surely the trick that will most mystify the binder, yes?

The `DefAttributesUsingSerialize` is not recursive.  If only binds the first tier of fields.  If we tried to use `DefAttributesUsingSerialize` on `class Rgba` directly it would fail, but it works fine on the vanilla `VisualizationConfig`.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 1 unresolved discussion (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NAAyhjY861C-GHT4uYe:-NABYafjAOrVely3swqO:b-inxrgh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I wrote "all of the tricks", but that wasn't a good summary of what I meant.

Here's what I had in mind: https://github.com/RobotLocomotion/drake/commit/1c08e2cc42095f44d1ea82611555e36ffa48e6e2

It passes all tests for me.

> The ability to turn four independent fields into an array is surely the trick that will most mystify the binder, yes?

The `DefAttributesUsingSerialize` is not recursive.  If only binds the first tier of fields.  If we tried to use `DefAttributesUsingSerialize` on `class Rgba` directly it would fail, but it works fine on the vanilla `VisualizationConfig`.
</blockquote></details>

Oh. Right. Dur. Thanks.  :)

In addition to your changes, I also scaled back on the `Rgba` API.  It didn't seem to make sense to provide an API whose *purpose* fundamentally interfered with easily using it in other bound structs. I likewise scaled back the recommendations on how it should be used.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17762#-NABdz4T-BZrwZLRprM-:-NABdz4T-BZrwZLRprM0:bl3m8fi) (no related file):*
FYI Historically, we have a number of structs that implemented `Serialize()` but couldn't actually be (de)serialized to YAML strings (the implementations were sufficient to serialize in bindings). It's one of the reasons I went out of my way to add tests to make sure that (de)serialization happened. Now, most of the structs (that I can currently think of) that suffered from that problem can now be serialized (`Rgba` was their blocker). Is the lack of test showing successful (de)serialization a defect on those other structs?

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 6 of 7 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17762)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
