### PR TITLE
Add symbolic::Polynomial::{Differentiate,Jacobian}

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6675)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-:-Kq-DpD_hPKFlhVhtiSH:b-utjvo1)*

**Comment by hongkai-dai** [comment]
checkpoint.

---

Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 278 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-ZpCf-TfbGiJA-ZHh:-Kq-ZpCf-TfbGiJA-ZHi:b-fvla8n) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.cc#L278)):*
> ```cpp
> // Differentiates a monomial `m` with respect to a variable `x`. This is a
> // helper function to implement Polynomial::Differentiate method. It returns a
> // pair `(n, m₁ * xⁿ⁻¹ * m₂)` where `d/dx (m₁ * xⁿ * m₂) = m₁ * xⁿ⁻¹ * m₂`
> ```

`d/dx (m₁ * xⁿ * m₂) = m₁ * xⁿ⁻¹ * m₂` - > '`d/dx (m₁ * xⁿ * m₂) = n * m₁ * xⁿ⁻¹ * m₂`

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq-WAkhghTbgrz8XwsU:bi87z0b) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
> ```objc
>   Expression ToExpression() const;
> 
>   /** Differentiates this polynomial with respect to the variable @p var. */
> ```

`@p var` -> `@p x`? Does this require that `x` is an indeterminate of the variable? If so, we should add that @pre x is an indeterminate to the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-:-Kq-Zvbo5M_pO-L8Wjaj:b6o68ox)*

**Comment by soonho-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq-_8FpLHLJA_4yFHuS:b382rre) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`@p var` -> `@p x`? Does this require that `x` is an indeterminate of the variable? If so, we should add that @pre x is an indeterminate to the documentation.
</blockquote></details>

Actually, it doesn't. A question is 'should we impose the restriction?'. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by soonho-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 278 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-ZpCf-TfbGiJA-ZHh:-Kq-_tu3UpM7QfFfc7MY:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.cc#L278)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`d/dx (m₁ * xⁿ * m₂) = m₁ * xⁿ⁻¹ * m₂` - > '`d/dx (m₁ * xⁿ * m₂) = n * m₁ * xⁿ⁻¹ * m₂`
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by hongkai-dai** [comment]
:lgtm: with minor comments on the implementation. +@seancurtis-tri for platform review please.

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq03NxKGyGjGxkuuQbS:brreqcx) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Actually, it doesn't. A question is 'should we impose the restriction?'. 
</blockquote></details>

I don't think we need to impose the restriction, but it would be clearer if in the documentation, we say explicitly that `var` can be either indeterminate, or coefficient.

---

*[drake/common/test/symbolic_polynomial_test.cc, line 495 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq0484eV12S2kUVS-DK:-Kq0484eV12S2kUVS-DL:b-69ofqu) ([raw file](https://github.com/robotlocomotion/drake/blob/06249bac448b5575acc4f54768c9859e044b7632/drake/common/test/symbolic_polynomial_test.cc#L495)):*
> ```cpp
>   Eigen::Matrix<Variable, 2, 1> vars_xy;
>   vars_xy << var_x_, var_y_;
>   const Eigen::Matrix<Polynomial, 1, 2> J_xy{p.Jacobian(vars_xy)};
> ```

also check if the size of `J_xy` is static at compile time?
```C++
const auto J_xy{p.Jacobian(vars_xy)};
static_assert(std::is_same<decltype(J_xy), Eigen::Matrix<Polynomial, 1, 2>>::value, "Incorrect type");
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-:-Kq05CNqLIy0HZh5VhzM:b-hu6t34)*

**Comment by soonho-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq07-6j6j0vMQh1_z77:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think we need to impose the restriction, but it would be clearer if in the documentation, we say explicitly that `var` can be either indeterminate, or coefficient.
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_polynomial_test.cc, line 495 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq0484eV12S2kUVS-DK:-Kq09oo0-NmGJqvf0bO-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/06249bac448b5575acc4f54768c9859e044b7632/drake/common/test/symbolic_polynomial_test.cc#L495)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

also check if the size of `J_xy` is static at compile time?
```C++
const auto J_xy{p.Jacobian(vars_xy)};
static_assert(std::is_same<decltype(J_xy), Eigen::Matrix<Polynomial, 1, 2>>::value, "Incorrect type");
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq19DtsjMsATm6fDbXW:bh3rmoh) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, I think `symbolic::Polynomial` does not have the notion of `decision variable`, there is distinction on `coefficient` and `monomial`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by soonho-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq1JLnfgub8ImeOvwFH:bbc86s4) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I think `symbolic::Polynomial` does not have the notion of `decision variable`, there is distinction on `coefficient` and `monomial`.
</blockquote></details>

We mention decision variables/indeterminates in the documentation of the `symbolic::Polynomial` class. For example, we have the following methods:
```c++
  /// Returns the indeterminates of this polynomial.
  Variables indeterminates() const;
 
  /// Returns the decision variables of this polynomial.
  Variables decision_variables() const;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq-WAkhghTbgrz8XwsT:-Kq1OU2yv23mYylxAjCC:bu4fc1b) ([raw file](https://github.com/robotlocomotion/drake/blob/0c6febe1c3837da782a7a64f606149ad4f8c9764/drake/common/symbolic_polynomial.h#L77)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We mention decision variables/indeterminates in the documentation of the `symbolic::Polynomial` class. For example, we have the following methods:
```c++
  /// Returns the indeterminates of this polynomial.
  Variables indeterminates() const;
 
  /// Returns the decision variables of this polynomial.
  Variables decision_variables() const;
```
</blockquote></details>

I say, thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with just some BTWs.

---

Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 277 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3IUTDduVYQYF-3j-v:-Kq3IUTDduVYQYF-3j-w:b-28gf8j) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/symbolic_polynomial.cc#L277)):*
> ```cpp
> namespace {
> // Differentiates a monomial `m` with respect to a variable `x`. This is a
> // helper function to implement Polynomial::Differentiate method. It returns a
> ```

BTW nit: Typically, function references end with a "()".

---

*[drake/common/symbolic_polynomial.cc, line 283 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3JJ9wLtNQwIPChwOJ:-Kq3JJ9x0sySInqN1tba:b-xrugss) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/symbolic_polynomial.cc#L283)):*
> ```cpp
> pair<int, Monomial> DifferentiateMonomial(const Monomial& m,
>                                           const Variable& x) {
>   if (m.get_powers().count(x) == 0) {
> ```

BTW This feels like redundant work. Counting the `x`'s here and then iterating them down below. If `x` is present, you're doing the work twice.

---

*[drake/common/test/symbolic_polynomial_test.cc, line 466 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3MZ2iybZZKjH51JCH:-Kq3MZ2iybZZKjH51JCI:brsp7ku) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/test/symbolic_polynomial_test.cc#L466)):*
> ```cpp
>   // p = 2a²bx² + 3bc²x + 7ac.
>   const Polynomial p{
>       2 * a_ * a_ * b_ * x_ * x_ + 3 * b_ * c_ * c_ * x_ + 7 * a_ * c_,
> ```

BTW Is there a reason for `a_ * a_` instead of `pow(a_, 2)`?  It seems it would be easier to look at these expressions and say, "Yeah, that's the same math."

Certainly for doubles in release code, I would never advocate something like `pow(x, 2)`. But for test code and, what I assume is a nicely efficient operator on `Monomial`s, it might make sense here.

---

*[drake/common/test/symbolic_test_util.h, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3LnJqvE-xtopQDqpo:-Kq3LnJr_8AQlAj2RE7n:bauitr0) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/test/symbolic_test_util.h#L44)):*
> ```objc
> }
> 
> inline bool PolyEqual(const Polynomial& p1, const Polynomial& p2) {
> ```

BTW If someone on the outside simply looked at this file, they might be surprised to see a bunch of one-line functions and ask, "Why?" I'd like to see a single comment at the top that says, "These provide binary predicates for use with gtest in order to facilitate intelligible failure messages." (Or some such thing.)

Given the length of this file, I'm weighing in quite late; which is why it's  a BTW. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-:-Kq3NK6iF339GfuRf82p:be7dw71)*

**Comment by soonho-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 277 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3IUTDduVYQYF-3j-v:-Kq4CdQOHp9bgprgO80T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/symbolic_polynomial.cc#L277)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW nit: Typically, function references end with a "()".
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.cc, line 283 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3JJ9wLtNQwIPChwOJ:-Kq4CgoHCZU2eTGptgyb:b-fivb8k) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/symbolic_polynomial.cc#L283)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This feels like redundant work. Counting the `x`'s here and then iterating them down below. If `x` is present, you're doing the work twice.
</blockquote></details>

The following code should be doing the same operations without checking `x` twice in the map:
```c++
  map<Variable, int> powers{m.get_powers()};   // <-----
  auto it = powers.find(x);
  if (it == powers.end()) {
    // x does not appear in m. Returns (0, 1).
    return make_pair(0, Monomial{});
  }
  DRAKE_ASSERT(it->second >= 1);
  const int n{it->second--};
  if (it->second == 0) {
    powers.erase(it);
  }
  return make_pair(n, Monomial{powers});
```

But then we make a copy of `m.get_powers()` which we don't use if `x` does not appear in it. I wrote the current code to avoid it.

---

*[drake/common/test/symbolic_polynomial_test.cc, line 466 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3MZ2iybZZKjH51JCH:-Kq4EY-e7eEFYU7ScnsB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/test/symbolic_polynomial_test.cc#L466)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is there a reason for `a_ * a_` instead of `pow(a_, 2)`?  It seems it would be easier to look at these expressions and say, "Yeah, that's the same math."

Certainly for doubles in release code, I would never advocate something like `pow(x, 2)`. But for test code and, what I assume is a nicely efficient operator on `Monomial`s, it might make sense here.
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_test_util.h, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3LnJqvE-xtopQDqpo:-Kq4eb8NJeDv49PDdJQL:b-wpmbpn) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/test/symbolic_test_util.h#L44)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW If someone on the outside simply looked at this file, they might be surprised to see a bunch of one-line functions and ask, "Why?" I'd like to see a single comment at the top that says, "These provide binary predicates for use with gtest in order to facilitate intelligible failure messages." (Or some such thing.)

Given the length of this file, I'm weighing in quite late; which is why it's  a BTW. :)
</blockquote></details>

Done. Thanks for the suggestion. PTAL the comment atop this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675)*

**Comment by SeanCurtis-TRI** [comment]
Marvelous.

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 283 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq3JJ9wLtNQwIPChwOJ:-Kq4jbmdwzaGw7AbIL-H:bka4pgd) ([raw file](https://github.com/robotlocomotion/drake/blob/6d11c883183785335a14c6df11d5fa7573339813/drake/common/symbolic_polynomial.cc#L283)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

The following code should be doing the same operations without checking `x` twice in the map:
```c++
  map<Variable, int> powers{m.get_powers()};   // <-----
  auto it = powers.find(x);
  if (it == powers.end()) {
    // x does not appear in m. Returns (0, 1).
    return make_pair(0, Monomial{});
  }
  DRAKE_ASSERT(it->second >= 1);
  const int n{it->second--};
  if (it->second == 0) {
    powers.erase(it);
  }
  return make_pair(n, Monomial{powers});
```

But then we make a copy of `m.get_powers()` which we don't use if `x` does not appear in it. I wrote the current code to avoid it.
</blockquote></details>

I had something like this in mind:

```c++
map<Variable, int> powers;
const auto& m_powers = m.get_powers();
for (auto it = m_powers.begin(); it != m_powers.end(); ++it) {
   if (it->first == x) {
      if (it->second > 1) powers[x] = it->second - 1;
   } else {
      powers.emplace(it);
   }
}
return powers;
```

In this case, we replace the two O(lg(n) + n) operations with one O(n lg n).  So, yours definitely wins.  :)  Your original definitely wins. O(lg n) in the cheapest case and O(n) in the most expensive.

---

*[drake/common/test/symbolic_test_util.h, line 23 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-Kq4l8gnQHL5t0pIwDuc:-Kq4l8gnQHL5t0pIwDud:b-gaqjyk) ([raw file](https://github.com/robotlocomotion/drake/blob/4dc5c798b47bf01125f148acad864e8ba7704f7b/drake/common/test/symbolic_test_util.h#L23)):*
> ```objc
> /// // which should help debugging.
> /// ASSERT_PRED2(ExprEqual, e1, e2);
> /// @endcode
> ```

BTW This is beautiful. Thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-:-Kq4lXgDw90jeCUFzcU1:b-nul6zf)*

**Comment by soonho-tri** [comment]
:lgtm: to finalize @seancurtis-tri 's platform review.
 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6675#-:-Kq4ouLgnjnQfMB38l3F:b-vt2uda)*

**Pull request merged**
