### PR TITLE
June 2022 upgrades

### LINKED ISSUE #17321: Upgrade common_robotics_utilities to latest - June 2022
Towards #17306.

Discussion copied from [slack thread](https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1654196174676199):

As part of the monthly external upgrades ([#17306](https://github.com/RobotLocomotion/drake/issues/17306)), [common_robotics_utilities](https://github.com/ToyotaResearchInstitute/common_robotics_utilities) needs to be upgraded to the latest commit. Recently, maybe_test was added ([relevant commit](https://github.com/ToyotaResearchInstitute/common_robotics_utilities/commit/79ee44d40e1dd22212939c821053bfad33426ef2)). Per the instructions in [common_robotics_utilities/repository.bzl](https://github.com/RobotLocomotion/drake/blob/9c9e57540876545172baf70ac955bdb497171227/tools/workspace/common_robotics_utilities/repository.bzl#L15), new unit tests should also be added to drake. That seems straightforward, however I noticed only a subset of tests are currently in [common_robotics_utilities/BUILD.bazel](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/common_robotics_utilities/BUILD.bazel). I'm wondering if this is intentional or an upgrading oversight? Specifically for the upgrade process, should new tests always be added?

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #17306
Closes  #17321

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17322)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
`maybe_test` was added to `common_robotics_utilities` following discussion in #17321

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17322#-:-N3_zJk3DxHtW-cYvIRb:bf1y5bn)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@sammy-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17322#-:-N3a5_lEAf2F6v8aBly7:bk55eui)* status: LGTM missing from assignee sammy-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17322)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 17 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17322#-N3aDy1X3jGpIRMvHusB:-N3aDy1X3jGpIRMvHusC:b-7ukuou) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7d870900aa330e96bd4524b732598da6c90b71/tools/workspace/voxelized_geometry_tools/repository.bzl#L17)):*
> ```Starlark
>         # When updating, ensure that any new unit tests are reflected in
>         # package.BUILD.bazel and BUILD.bazel in drake.
>         commit = "ebd71490406ec74ea6db0b63237890559170f169",
> ```

This commit doesn't build without the matching change to `common_robotics_utilities`.  Perhaps they should be reordered or squashed into the same commit?

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17322)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 17 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17322#-N3aDy1X3jGpIRMvHusB:-N3aMU_BBq73B62qWTu8:bhd1gv8) ([raw file](https://github.com/robotlocomotion/drake/blob/ad7d870900aa330e96bd4524b732598da6c90b71/tools/workspace/voxelized_geometry_tools/repository.bzl#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This commit doesn't build without the matching change to `common_robotics_utilities`.  Perhaps they should be reordered or squashed into the same commit?
</blockquote></details>

Good suggestion - let's go with squashing into one commit for reverting ease (hopefully won't be needed!)

**Pull request merged**
