### PR TITLE
[release] mkdir and chkdir after checking URLs

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Without this, running without wheels built doesn't do any work, but still creates a directory that needs to be deleted before running.

Negative test case:
```
# Run once. Let it fail.
$ bazel run //tools/release_engineering:download_release_candidate -- --timestamp 20380101 --version v10.0.0
# Run it again. On master, complains about directory existing. This PR, it will try again.
$ bazel run //tools/release_engineering:download_release_candidate -- --timestamp 20380101 --version v10.0.0
````

Positive test cases (from docstring)
```
$ bazel run //tools/release_engineering:download_release_candidate -- \
      --timestamp 20230315 --find-git-sha
$ bazel run //tools/release_engineering:download_release_candidate -- \
      --timestamp 20230315 --version v1.14.0
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19221)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for review please! +(status: single reviewer ok) 
if you don't think it's worth the change, I can close the PR - either way from my perspective

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19221#-:-NTKkNE63bMQkYH4ykOW:b53axnl)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19221)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`tools/release_engineering/download_release_candidate.py` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19221#-NTKkhbhDyKsvVbgKP0n:-NTKkhbhDyKsvVbgKP0o:b-4hnbnn) ([raw file](https://github.com/RobotLocomotion/drake/blob/93df47090fbc370b721b820d68e00b58707d0ee5/tools/release_engineering/download_release_candidate.py#L14)):*
> ```Python
> Here's an example of how download the release artifacts:
> 
>   bazel run //tools/release_engineering:download_release_candidate -- \
> ```

BTW Ah, this doesn't work for old releases period 'cause staging?

**Review by jwnimmer-tri — COMMENTED** [review]
I am fine to merge this if you like it as an improvement.  (For myself, I do `rm /tmp/thing` if I made any typos and need to recover.)

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19221#-:-NTL2r4O8YclzeH3CfNv:b-xwq90k)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`tools/release_engineering/download_release_candidate.py` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19221#-NTKkhbhDyKsvVbgKP0n:-NTL1Y6Z132JeHaAWk8p:bb7867z) ([raw file](https://github.com/RobotLocomotion/drake/blob/93df47090fbc370b721b820d68e00b58707d0ee5/tools/release_engineering/download_release_candidate.py#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Ah, this doesn't work for old releases period 'cause staging?
</blockquote></details>

Yup.
___
*[`tools/release_engineering/download_release_candidate.py` line 112 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19221#-NTL2JT_4nzICYXtOpw9:-NTL2JT_4nzICYXtOpwA:babl470) ([raw file](https://github.com/RobotLocomotion/drake/blob/a6ec4bd62faeb8e421d97c65edd081c918ee7298/tools/release_engineering/download_release_candidate.py#L112)):*
> ```Python
> def _generate_and_check_download_urls(*, timestamp, staging, version):
>     """Generates URLs for the binaries as specified, and
>     (relative)paths.
> ```

The new return type shape and its data format is not sufficiently well-explained.  We'd probably want a type hint (for the shape) and examples (of what it contains).

On the other hand, we probably don't need to pass `base_url_filename_pairs` around.  If we passed around the `binaries` dict instead, I think it would suffice for what the code needs, and be easier to explain here in terms of a return value.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both, modulo discussions.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19221#-:-NURww7O2ICp4BXsQHCS:b55ufd5)* status: 1 unresolved discussion, missing label for release notes (waiting on @EricCousineau-TRI)

**Pull request closed without merging**
