### PR TITLE
[doc] Add release notes v1.8.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @sherm1 @xuchenhan-tri @SeanCurtis-TRI @rpoyner-tri the release notes are up-to-date and ready for any suggestions now, if you'd like to take a look.

ETA for release is mid/late next week.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853#-:-NBTDH1T1Cof_XdvG66-:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853#-:-NBTEMie1amXv7eISDM7:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review of the `installation` and `pip` changes, please.

**Review by svenevs — COMMENTED** [review]
:lgtm: with one nit about jammy `apt` packages being installed.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853#-:-NBwzibm8Eavv_Lu5BbG:b4lze12)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_pages/pip.md` line 70 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17853#-NBwyYfTEBwheqQzehLi:-NBwyYfTEBwheqQzehLj:bxnwh0k) ([raw file](https://github.com/robotlocomotion/drake/blob/47b322335b08fa5115599cd0227d4ea59a1f76a2/doc/_pages/pip.md#L70)):*
> ```Markdown
> ```bash
> sudo apt-get install --no-install-recommends \
>   libx11-6 libsm6 libglib2.0-0
> ```

Minor, this should have `libpython3.10` correct?  Why is `libxt6` removed for jammy?

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_pages/pip.md` line 70 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17853#-NBwyYfTEBwheqQzehLi:-NBx88_pEzTvQOpUVXwS:b-bswk0k) ([raw file](https://github.com/robotlocomotion/drake/blob/47b322335b08fa5115599cd0227d4ea59a1f76a2/doc/_pages/pip.md#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I removed those because I ran this in docker (using the last night's wheel) and it passed `import pydrake.all` without them.  Do you have a testing recipe that shows it would be needed?

(We're actually shipping a vendored libxt in drake.libs already, so it was probably spurious for Focal as well?)
</blockquote></details>

OK, I can replicate on jammy too and it works with the current instructions.  I cannot replicate in focal (`drake-0.0.20220914-cp38-cp38-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.`) but possible user error -- either way, I think these docs can stay as is.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r6, 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853#-:-NCLDMRBA-hgnOO_87N2:bnfp4nl)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @svenevs)

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17853)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
