### PR TITLE
Visual test (only) of motion for uniform-density block on inclined plane.

### PR DESCRIPTION
**Pull request by mitiguy**
@amcastro-tri  There is an external user who was trying a simple block-on-inclined-plane problem with occasional odd results. This PR has a fairly straightforward visual test.  It gives visually reasonable results for all the situations that I have tried lately except one.  If the block starts penetrated into the half-plane with the settings below, it seems overdamped if penetration_allowance is too small.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10933)

### CODE REVIEW

**Comment by mitiguy** [comment]
To the reviewer:  I would prefer that we move this example along ASAP.
So, please review this with the intent of pushing this into master without
necessarily fixing problems with an initially penetrated block.
There are things to explore, but we can redo these in a later PR.
I have included them here for your edification and as a record
of what I found thus far.

Case 1:  penetration_allowance=1.0E-7 seems to quickly push block out of inclined-plane.

bazel run examples/multibody/inclined_plane_with_block:inclined_plane_with_block -- --time_step=1.0E-4 --penetration_allowance=1.0E-3 --muS_block=0.4 --muK_block=0.4 --slope_degrees=45 --is_inclined_plane_half_space=true --is_block_with_4Spheres=true --target_realtime_rate=0.1

Case 2:  penetration_allowance=1.0E-7 seems to slowly push block out of inclined-plane.

bazel run examples/multibody/inclined_plane_with_block:inclined_plane_with_block -- --time_step=1.0E-4 --penetration_allowance=1.0E-7 --muS_block=0.4 --muK_block=0.4 --slope_degrees=45 --is_inclined_plane_half_space=true --is_block_with_4Spheres=true --target_realtime_rate=0.1

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 61 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10933#-LavHnoW0Zj1EvjsavCy:-LavHnoW0Zj1EvjsavCz:bj830p3) ([raw file](https://github.com/robotlocomotion/drake/blob/bfa30d8ce7c5c186bfd749430d7105cc850062a2/examples/multibody/inclined_plane_with_body/README.md#L61)):*
> ```Markdown
> #### Optional: How do I build then run with command-line arguments?  
> ```
> bazel run examples/multibody/inclined_plane_with_body:inclined_plane_with_body -- -slope_degrees=30 -bodyB_type='block_with_4Spheres'
> ```

nit _Meta_ `bazel run` does confusing things.  We should _not_ recommend it in READMEs, period.  Same goes for `bazel run` higher up in this file.  Use `bazel-bin/examples/mul...etc` directly.

**Comment by jwnimmer-tri** [comment]
___
*[tools/install/libdrake/build_components.bzl, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10933#-La_sj8H31_nyCW2vRoU:-LavINb8558WNeKKuDLq:b3aeoss) ([raw file](https://github.com/robotlocomotion/drake/blob/6c7f3f4d2b4f79da659babc2e5d34bae35a52b78/tools/install/libdrake/build_components.bzl#L89)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Alejandro -- I do not understand your question.
I autogenerated this file by following the instructions at the top of this file, which are: 

# Should include everything any consumer of Drake would ever need.
# Do not update this list by hand; instead, run build_components_refresh.py.
</blockquote></details>

You need to merge (or rebase) to latest master before running the command.  I'll fix the docs to say that.  (You should always merge PRs to master anyway, any time you touch them.  Otherwise you are locally testing stale code.)

**Comment by jwnimmer-tri** [comment]
___
*[tools/install/libdrake/build_components.bzl, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10933#-La_sj8H31_nyCW2vRoU:-LavO7NQDO23CMriYQxG:bj64xlp) ([raw file](https://github.com/robotlocomotion/drake/blob/6c7f3f4d2b4f79da659babc2e5d34bae35a52b78/tools/install/libdrake/build_components.bzl#L89)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

or maybe I forgot myself to add this?
</blockquote></details>

It's not "unpackaged" anymore (it was a few weeks ago).  The problem is that Paul has an old master base.

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 17 at r6](https://reviewable.io/reviews/robotlocomotion/drake/10933#-Law-c517kvhjgDSs6Mj:-LawPJwp-9_mTTjI5ky9:b35f4rb) ([raw file](https://github.com/robotlocomotion/drake/blob/7e9c0e82579bd4ec43dfd2c12772ab4eecff78ff/examples/multibody/inclined_plane_with_body/README.md#L17)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

OK.  Good suggestion. 
I like your idea of including a link to the general instructions:
https://drake.mit.edu/bazel.html#using-bazel 

Note: This is in a short optional section (easy to skip).
For those who have not built the visualizer (and have bazel installed), 
this one-line helps them get the job done without reading general instructions.
My response to your next comment may help shed light on what I intend for this example. 
</blockquote></details>

@sherm1 The logical conclusion of that argument is that we should copy this identical text into our 30+ examples; that is a recipe for bitrot.  Indeed, if you like I can point your to PRs that did thus in the past, and then we had to go and janitor it all later.  Copypasta in docs is _worse_ than copypasta in code.  In code at least, we might have a unit test.  Documentation is not tested, so rots more quickly.  This README is over the top.  It could be much more concise and still be just as easy for an onramp.

**Comment by EricCousineau-TRI** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 17 at r6](https://reviewable.io/reviews/robotlocomotion/drake/10933#-Law-c517kvhjgDSs6Mj:-LawPiAl2czQnSDodfw5:bx3jiz5) ([raw file](https://github.com/robotlocomotion/drake/blob/7e9c0e82579bd4ec43dfd2c12772ab4eecff78ff/examples/multibody/inclined_plane_with_body/README.md#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 The logical conclusion of that argument is that we should copy this identical text into our 30+ examples; that is a recipe for bitrot.  Indeed, if you like I can point your to PRs that did thus in the past, and then we had to go and janitor it all later.  Copypasta in docs is _worse_ than copypasta in code.  In code at least, we might have a unit test.  Documentation is not tested, so rots more quickly.  This README is over the top.  It could be much more concise and still be just as easy for an onramp.
</blockquote></details>

I think that having the beginner steps for an explicit beginner tutorial is extremely great; however, as things stand, it's unclear where this falls in terms of other tutorials. (Along what Jeremy said.)

I'd prefer that we wait on this level of (redundant) detail until we nail down how we want to formulate our tutorials and step users through all content; Paul, if you want to send the external user instructions, great, but I'm not fond of them living here and potentially getting stale or redundant.

**Comment by jwnimmer-tri** [comment]
The "commands to run" instructions in both kuka_iiwa_arm and simple_gripper README are much more terse that this PR's README.  The README here still needs more editing.  If you want to get this merged, then just nuke the README from this PR and submit it later.  Being in a hurry is no reason to commit junk to master.

**Comment by jwnimmer-tri** [comment]
(The first and last 10 lines of the README are useful though; it _would_ be nice to keep them.  Since this still has platform review not even started, we have time to make the README acceptable, also.)

**Comment by jwnimmer-tri** [comment]
@sherm1 Drake is a shared sandbox.  By committing code to master, we agree to jointly maintain it.  Thus, we have code review and standards to coordinate and agree on the burden of that shared maintenance.  Having a README that serves your user is important, but having `master` remain a shared resource with rules an regulations is also important.

Would it help if I just pushed a commit (or opened a PR to `mitiguy/drake`) that edits / removes the objectionable parts?  Well, I'll make the PR anyway, and they we can argue about code on the table instead of policies.

**Comment by jwnimmer-tri** [comment]
Proposed at https://github.com/mitiguy/drake/pull/3.  I could live with something like that, until we consolidate all of the examples even further in a follow-up.

We should also, separately, talk about why we are asking naive users to compile from source instead of using the nightly binary release, which has examples ready-to-go off the shelf.

**Comment by jwnimmer-tri** [comment]
___
*[tools/install/libdrake/build_components.bzl, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10933#-La_sj8H31_nyCW2vRoU:-LawpBGF1vdCuEAldtsV:bbbosj1) ([raw file](https://github.com/robotlocomotion/drake/blob/6c7f3f4d2b4f79da659babc2e5d34bae35a52b78/tools/install/libdrake/build_components.bzl#L89)):*
> Interestingly, I found that the master of build_components.bzl included the line: ": "//multibody/plant:implicit_stribeck_solver_results", # unpackaged"

No it doesn't.  You did something wrong.
https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/build_components.bzl

If you are having trouble with the script, then you can just remove this line manually for now.  In short, this PR should not contain any changes to this file.

I'll PR an update to the top-of-file comment to provide the full pathname, and resolve the confusing "consumer" language.

**Comment by EricCousineau-TRI** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 44 at r6](https://reviewable.io/reviews/robotlocomotion/drake/10933#-Law-jhU-fueqDQ9a5Zp:-Lb-bA3lArmhXF_LFYJ8:bdys2um) ([raw file](https://github.com/robotlocomotion/drake/blob/7e9c0e82579bd4ec43dfd2c12772ab4eecff78ff/examples/multibody/inclined_plane_with_body/README.md#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

That all makes excellent sense if these instructions are to be seen as a standalone, but I'm not sure if this should be considered a standalone (per above discussion about consistency).

These instructions are still great, and I think if you sent them directly to the user(s) who asked about this, this level of detail would be *extremely* valuable.
However, I'm not yet convinced they should live in the `drake` tree to be maintained (esp. given that we have so many other things to clean!)
</blockquote></details>

From doing another pass over the other examples, we still have stuff that I'd like to cleanup.

To continue moving this forward, I'm fine with taking that burden on myself (decimating non-standalone docs and use cross-referencing).

Lemme know if that's what you want, and I'll file an issue and execute it sometime within the next week.

**Comment by EricCousineau-TRI** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 44 at r6](https://reviewable.io/reviews/robotlocomotion/drake/10933#-Law-jhU-fueqDQ9a5Zp:-Lb-bSm_0QMHrPJbSCC2:b-dzst6s) ([raw file](https://github.com/robotlocomotion/drake/blob/7e9c0e82579bd4ec43dfd2c12772ab4eecff78ff/examples/multibody/inclined_plane_with_body/README.md#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From doing another pass over the other examples, we still have stuff that I'd like to cleanup.

To continue moving this forward, I'm fine with taking that burden on myself (decimating non-standalone docs and use cross-referencing).

Lemme know if that's what you want, and I'll file an issue and execute it sometime within the next week.
</blockquote></details>

Er - I meant "decimating standalone docs in a non-standalone context"

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 44 at r6](https://reviewable.io/reviews/robotlocomotion/drake/10933#-Law-jhU-fueqDQ9a5Zp:-Lb-ye-b-g5plPIsrZ1x:bol4ort) ([raw file](https://github.com/robotlocomotion/drake/blob/7e9c0e82579bd4ec43dfd2c12772ab4eecff78ff/examples/multibody/inclined_plane_with_body/README.md#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er - I meant "decimating standalone docs in a non-standalone context"
</blockquote></details>

Eric, did you look at my PR against mitiguy/drake yet?  I proposed a cleanup.  We probably shouldn't nitpick this text more until that's merged (possibly with adjustments) first?

**Comment by EricCousineau-TRI** [comment]
___
*[examples/multibody/inclined_plane_with_body/README.md, line 44 at r6](https://reviewable.io/reviews/robotlocomotion/drake/10933#-Law-jhU-fueqDQ9a5Zp:-Lb-zhxG2vg78Cxdwveq:b-y1k6ma) ([raw file](https://github.com/robotlocomotion/drake/blob/7e9c0e82579bd4ec43dfd2c12772ab4eecff78ff/examples/multibody/inclined_plane_with_body/README.md#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Eric, did you look at my PR against mitiguy/drake yet?  I proposed a cleanup.  We probably shouldn't nitpick this text more until that's merged (possibly with adjustments) first?
</blockquote></details>

Ah, had not! But I like those suggested edits!

**Comment by sherm1** [comment]
Woo hoo! :clap:

**Pull request merged**
