### PR TITLE
symbolic_py: Bind and test symbolic::Monomial

### PR DESCRIPTION
**Pull request by soonho-tri**
Part of #8098

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8111)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@ericcousineau-tri for feature-review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-:-L5oD_0yKixwOo92bgGE:b-v5eaz3)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a few minor BTWs.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-L5oSDVePa2yg-bWPxa8:-L5oSDVePa2yg-bWPxa9:bq7cwgc) ([raw file](https://github.com/robotlocomotion/drake/blob/e48b03a9e55e826dd957f274d68129f36f5b24a1/bindings/pydrake/symbolic_py.cc#L16)):*
> ```cpp
> 
> PYBIND11_MODULE(_symbolic_py, m) {
>   using drake::symbolic::Expression;
> ```

BTW Could would you be OK with using the following instead?
```
// NOLINTNEXTLINE(build/namespaces): Emulate placement in namespace.
  using namespace drake::symbolic;
```

It is used in other places, namely `pydrake.systems`.

---

*[bindings/pydrake/test/symbolic_monomial_test.py, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-L5oRQXwSoW9YjrdPar1:-L5oRQXx6YCBNbFcsU2L:b-rra2i4) ([raw file](https://github.com/robotlocomotion/drake/blob/e48b03a9e55e826dd957f274d68129f36f5b24a1/bindings/pydrake/test/symbolic_monomial_test.py#L2)):*
> ```Python
> # -*- coding: utf-8 -*-
> from __future__ import absolute_import, division, print_function
> ```

FYI These tests seem to test API and (comprehensive) functionality. They could be reduced a little bit to just test API, but I don't think it's too much of an issue at this point.

---

*[bindings/pydrake/test/symbolic_monomial_test.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-L5oREJxCbkPRuAS53Uc:-L5oREJxCbkPRuAS53Ud:bc103aa) ([raw file](https://github.com/robotlocomotion/drake/blob/e48b03a9e55e826dd957f274d68129f36f5b24a1/bindings/pydrake/test/symbolic_monomial_test.py#L15)):*
> ```Python
> 
> class TestSymbolicMonomial(unittest.TestCase):
>     def testConstructorVariable(self):
> ```

BTW Can you make these methods `snake_case`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-:-L5oSP1BEMkSjF-fOMaN:b-mdk8o7)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-L5oSDVePa2yg-bWPxa8:-L5oTi3iEmQVWwGiJj4g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e48b03a9e55e826dd957f274d68129f36f5b24a1/bindings/pydrake/symbolic_py.cc#L16)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could would you be OK with using the following instead?
```
// NOLINTNEXTLINE(build/namespaces): Emulate placement in namespace.
  using namespace drake::symbolic;
```

It is used in other places, namely `pydrake.systems`.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/symbolic_monomial_test.py, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-L5oRQXwSoW9YjrdPar1:-L5oUwUjj_THcpzCFEcP:b-i6hjq) ([raw file](https://github.com/robotlocomotion/drake/blob/e48b03a9e55e826dd957f274d68129f36f5b24a1/bindings/pydrake/test/symbolic_monomial_test.py#L2)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

FYI These tests seem to test API and (comprehensive) functionality. They could be reduced a little bit to just test API, but I don't think it's too much of an issue at this point.
</blockquote></details>

I see. I'll try to minimize tests in the future PRs.

---

*[bindings/pydrake/test/symbolic_monomial_test.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-L5oREJxCbkPRuAS53Uc:-L5oUApK7tCkyC5V2CY-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e48b03a9e55e826dd957f274d68129f36f5b24a1/bindings/pydrake/test/symbolic_monomial_test.py#L15)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you make these methods `snake_case`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-:-L5oUClm-cI2JXafd_fz:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8111#-:-L5oY0GUzwYGGhpPSqM8:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8111)*

**Pull request merged**
