### PR TITLE
[plant] MbP throws exceptions on NaN input port values

### LINKED ISSUE #15720: Not particularly useful MbP error on reaction forces computation
`abort: Failure at multibody/plant/tamsi_solver.cc:217 in SolveQuadraticForTheSmallestPositiveRoot(): condition 'Delta > 0' failed`

I don't have any public code I can share to reproduce this, but it happens on https://github.com/RobotLocomotion/drake/commit/3d8c50818cce30c735d60bb56de91724ab5437f6 when the actuation input port has a NaN value and I request the reaction forces from the appropriate MBP output port.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Fixes #15720.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature review please thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1tZL8g8LdMshfFwcE3:bx7wbyu)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one request: since this adds a substantial amount of runtime checking at every MbP computation, please try some representative robot application both with and without this check to assess whether the performance reduction is noticeable, and post the result here. I suspect not, but it is hard to tell.

+@sammy-tri for platform review per rotation, please

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1tzue_3WKFIvaREKYQ:b-34g2y6)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@sherm1 Do you have suggestions on what applications to run on? The only one I'm thinking of right now is `drake/examples`. Perhaps also a few anzu demos?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1u0QfC83mhblQ5f7Jy:b-1d1476)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: do not merge) for now while I run those experiments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1u8cE2-cqO1TxnLNsa:b-axia8i)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
No issues from me currently, waiting on resolution of the runtime cost question.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1uQwaL8ntxrNDQqG0h:b-2wzqnh)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
I ran a couple of sims from Anzu over 10 runs (with high enough target real time rate) and took the average for before and after on my P53. Both sims use the actuation input ports. In case they are sensitive, I omit the names of the sims.

Sim1: Simulated time 10seconds. Run time: 3561ms(before) vs 3620ms(after). 
Sim2: Simulated time 6.5seconds. Run time: 7868ms(before) vs 8029.25ms(after).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1ucN5y9p1wD4ZqRfd4:b70maz6)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Thanks, Xuchen! Looks like maybe 2% slower. That seems tolerable. WDYT @sammy-tri @amcastro-tri ?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N1ue_WR5v3eFzs_OuPD:b-84da88)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
This looks great. One question; should we use `allFinite()` instead of `hasNanN()` to also detect infinity values? 

Regarding the slower runtime. TBH, it does worry me. 2% does not seem a lot, but it accumulates quickly. That is, 5 of these small performance hits accumulate to a significant 10%. Whenever I profile sims, and I did this just last week, there is always this 10-15% that I have no idea where it goes. Using kcachegrind in the past showed essentially an accumulation of very small things that are difficult to fix. 
However, I do like this feature. Could it somehow be a `MultibodyPlangConfig` option? or some other mechanism to quickly turn off these checks and having a mechanism to discover them quickly when we do care?

Thoughts?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2DAw446bd48N858cIM:bnujmp0)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> One question; should we use allFinite() instead of hasNanN() to also detect infinity values?

Is there any scenario where one might have a valid infinite value on this port? I would think no? Working.

MbPConfig doesn't seem like the right place for something like this to me. What would the default be? Presumably it would be not checking for these values. Then the user is faced with a perplexing error message as described in the issue. It doesn't seem like the first course of remedy that comes to mind in that situation is to tweak a flag in MbPConfig.

Perhaps make it a debug only check? It's plausible that people would run things in debug mode if something blows up.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2DCUPwDSOTjI_j3R2n:b-dljuq4)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
In general I would stick with NaN since Inf can be legitimate (e.g. we use it for upper/lower bounds when there aren't any). For something that is supposed to be a force, infinity does seem a little excessive! OTOH so does 1e30.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2DEU_t2XMu_Y5HeJ3s:bwqox9h)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Comment by sherm1** [comment]
Could be a compile time option -- default "check for NaNs" but a build time option to disable the check? I'm skeptical that enough users would run a Debug build that we should tie this to Debug/Release (except that it should definitely be on in Debug!)

**Comment by sherm1** [comment]
`-DDRAKE_FAST_BUT_DANGEROUS`

**Comment by jwnimmer-tri** [comment]
Users can already toggle assertions separately from compilation mode (optimization level).  If you want this under a preprocessor flag, use either `DRAKE_ASSERT(...)` or `if (kDrakeAssertIsArmed) { ... }`.  We should not grow a whole farm of bespoke build options.  Nobody will use them.

I would also say, try to confirm the 2% number before worrying anymore here.  It doesn't not seem plausible that this change makes things so slow.  I suspect a benchmarking procedural error.

**Review by xuchenhan-tri — COMMENTED** [review]
`if (kDrakeAssertIsArmed) { ... }` is the one I had in mind.

Re benchmarking procedure: it was a very crude "benchmark". I ran the sims in Anzu with the `time` command for 10 runs and took the average. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2Df7t54nh_pnAIYmfK:bxwn7lx)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
Very good point form Jeremy. I also was surprised with the impact on performance given the small change introduced by this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2DgGAu2FYXfjT2BXTv:b-nr571b)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
You think a NaN check on 14 should lead to a 2% degradation of a 200 Hz controller?

**Comment by sherm1** [comment]
I only saw the code change, not the benchmark. The code change required O(n) scanning of several input ports including the external forces port which consists of a bunch of structs per body. If the whole computation is O(n) the extra O(n) pass through the ports (presumably with memory faults) could be 2% of the total. 

Why did you mention the 200Hz control rate? If that means that computation of a single dynamics evaluation takes 5ms then I agree 2% for a little check would be excessive!

**Comment by jwnimmer-tri** [comment]
My understanding is that most Anzu simulations use only the actuation input port (1 double per robot dof), and that the other input ports are always empty.  I believe both the MbP dynamics timestep and controller timestep are typically around 200 Hz.

If you're scanning the inputs any time they are used, rather than any time they change, well, that's silly.

**Comment by sherm1** [comment]
Continuous input ports are always changing. Discrete ones _should_ be sampled so that the NaN check is done just once. Unfortunately we don't sample, even when MbP is in discrete mode -- see issue [#12786](https://github.com/RobotLocomotion/drake/issues/12786).

FYI Xuchen told me did three independent 10X runs since he thought the 2% seemed high. Each produced roughly the same result.

**Review by amcastro-tri — COMMENTED** [review]
Would it be easier to discuss f2f? We can use some of the SoftSim meeting today  (9:00 PST/12:00 EST) if you guys are available. Xuchen and I will be there.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2HGpv60jFozhu1X0__:b-94ez0t)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Conflict resolved and moved the NaN check to behind `DRAKE_ASSERT_IS_ARMED` flag. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2Iznm06EEnJ_NJgjMQ:b-c7dzzi)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri, @sammy-tri, and @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
Excellent! does the 2% impact on performance disappear with this update?
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2J9pEo1wtfrzG4udpc:b-46p2tf)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2N-_4h89lQSo9Buf8U:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
(not merging now since there seems to be some conversation left, but I have no objections.  merge at will)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2N-bxR1yV8-v8p78R5:b5ug55z)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: do not merge) Let me verify the 2% is gone.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2N-qPc6uZSWggBFe8T:b909mbw)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Seems likely to be measurement noise since one got slower and the other faster and the change itself should be nothing if ASSERT is not ARMED.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2SYkZm6aUGKKP4MBVb:bnuld60)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
Is this "noise" reproducible? because it is also within 2% as before...

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2Sa91l9qLhdsWUarkQ:b-he19sr)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
2% is definitely in the range where you need to be putting your CPUs into constant-performance mode in order for comparisons to be meaningful.

https://github.com/RobotLocomotion/drake/blob/0fe243f379d7f75cc6e7fe9c6c22aa9f822e79af/tools/performance/benchmark_tool.py#L70-L71

**Review by xuchenhan-tri — COMMENTED** [review]
> because it is also within 2% as before...

That's my concern too. The 2% from before could also be noise.
Thanks for the tool reference @jwnimmer-tri. Didn't know before. I'll try it and report back.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2SanYO1SIY_fN8Qwxe:b-jjcnvk)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
New data points with cpu regulations.
Sim1: Simulated time 10seconds. Run time: 5637ms(baseline) vs 5704ms(check with debug guard) vs 5642ms(check without debug guard).
Sim2: Simulated time 6.5seconds. Run time: 11857ms(baseline) vs 11804ms(check with debug guard) vs 11858ms(check without debug guard).
With this, it seems reasonable to just remove the debug guard.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2mYqlPCmCYq_LM7WO7:b-132j8z)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Yay!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2maK03CMvtDByknN4d:bb77rlh)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17174#-:-N2mjM0G8ttt_RZxiS0f:b-b9fcpn)* status: labeled "do not merge" (waiting on @amcastro-tri and @sammy-tri)

**Pull request merged**
