### PR TITLE
ChaoticBabyboot - unit test for accuracy of numerical integration.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7010)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@edrumwri 
Platform review +@sherm1 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-:-KtsWQuAKEz71Q3Efwoe:b-a8o0i9)*

**Comment by edrumwri** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtviDLCPqkuJPNg3r-J:-KtviDLCPqkuJPNg3r-K:b-wbfole) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L16)):*
> ```cpp
> namespace {
> 
> using Vector7d = Eigen::Matrix<double, 7, 1>;
> ```

Do you use Vector7d anywhere?

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtsYxALc4zBkIBuM56h:-KtsYxALc4zBkIBuM56i:b-82l3jr) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L28)):*
> ```cpp
> // energy_expected    |  Sum of kinetic plus potential energy.
> void CompareExpectedSolutionVsActualSolution(
>   const double qA_expected,
> ```

I recall @sherm1 noting an issue wth passing const PoD parameters to a function. I couldn't recall the exact reasoning and didn't find a justification on the internets. Still, what you think of passing in a MG_chaotic_babyboot structure, for which the fields are all named? The problem with the current setup is that I could imagine it being accidentally called as (qA_expected, qADt_expected, qADDt_expected, qB_expected, qBDt_expected, ...).

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Kts_EdVthleyEJ2zSWQ:-Kts_EdVthleyEJ2zSWR:byng249) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L46)):*
> ```cpp
>   const double energy = MG_chaotic_babyboot.Energy;
> 
>   // Calculate the absolute value of the difference in results.
> ```

This comment is wrong.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Kts_PFJke_vvLEd6dWx:-Kts_PFJke_vvLEd6dWy:bdzoyrg) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L59)):*
> ```cpp
>   // Allowable error is scaled for individual quantities.
>   const double absError = MG_chaotic_babyboot.absError;
>   EXPECT_TRUE(std::abs(qA_difference) <= 1E2 * absError);
> ```

Please change 1E2, 5E2, 1E3, and 0.01 to named constants so that they are easy to change in one place and not susceptible to transcription errors.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Ktvhh6dTNa4tb38-wez:-Ktvhh6e-kh8p2K4RLlq:b-z283my) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L71)):*
> ```cpp
> // Test accuracy of calculations for chaotic babyboot's angles qA and qB and
> // their time-derivatives.  Compare to expected solution that was created by
> // running two very high accuracy simulation with MotionGenesis - both kept the
> ```

BTW simulation -> simulations

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtvhmcTD1g2bm_z0IS-:-KtvhmcTD1g2bm_z0IS0:bmm0bgu) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L74)):*
> ```cpp
> // absolute value of energy variation to less than 6.0E-14 (theoretical is 0.0).
> // For the given initial values, the babyboot is chaotic, so it is difficult
> // (perhaps impossible) to create a perfect test that integrator works.
> ```

BTW that -> that the

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtvhzgqEqVKFJGyOTVZ:-KtvhzgqEqVKFJGyOTV_:bkd0ecu) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L78)):*
> ```cpp
>   const double degree_to_radian =  0.0174532925199432957692369;
>   const double qA_expected = -61.312983761859 * degree_to_radian;
>   // Other simulation:       -61.312983517329;
> ```

Paul, what do these "Other simulation" comments mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010)*

**Comment by sherm1** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtsYxALc4zBkIBuM56h:-KtvwjuRC7SZovqcSMGg:b-wrwez4) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L28)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I recall @sherm1 noting an issue wth passing const PoD parameters to a function. I couldn't recall the exact reasoning and didn't find a justification on the internets. Still, what you think of passing in a MG_chaotic_babyboot structure, for which the fields are all named? The problem with the current setup is that I could imagine it being accidentally called as (qA_expected, qADt_expected, qADDt_expected, qB_expected, qBDt_expected, ...).
</blockquote></details>

BTW yes @edrumwri , there is a rule about that in the Drake style guide [clarifications](http://drake.mit.edu/code_style_guide.html#id18) section (look for "Use of const"). However that applies to function *declarations*, it is OK to use const in a function *definition*. Since this is a definition in a test case, with no visible API declaration in which the const could be misleading, it is OK here. The real problem here is the dangerous expectation that the caller will somehow be able to correctly order 7 identical `(double,double,double,double,double,double,double)` arguments. This should be a struct instead to prevent the obvious error condition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010)*

**Comment by mitiguy** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtviDLCPqkuJPNg3r-J:-Ktx0LKbCX0wFMWF8Hp2:bja1yyh) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L16)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Do you use Vector7d anywhere?
</blockquote></details>

Done.  Removed

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtsYxALc4zBkIBuM56h:-Ktx3TvThos6TFfj4pKz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW yes @edrumwri , there is a rule about that in the Drake style guide [clarifications](http://drake.mit.edu/code_style_guide.html#id18) section (look for "Use of const"). However that applies to function *declarations*, it is OK to use const in a function *definition*. Since this is a definition in a test case, with no visible API declaration in which the const could be misleading, it is OK here. The real problem here is the dangerous expectation that the caller will somehow be able to correctly order 7 identical `(double,double,double,double,double,double,double)` arguments. This should be a struct instead to prevent the obvious error condition.
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Kts_EdVthleyEJ2zSWQ:-Ktx3V-F13HPOv4wCkPZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L46)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This comment is wrong.
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Kts_PFJke_vvLEd6dWx:-KtxGMuyVEKDw3HHn04B:b-mr1yv5) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L59)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please change 1E2, 5E2, 1E3, and 0.01 to named constants so that they are easy to change in one place and not susceptible to transcription errors.
</blockquote></details>

As we discussed, these values are fences around the results that were sized by multiple simulations.
I would prefer to leave these unnamed as they are somewhat too arbitrary for names.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtvhzgqEqVKFJGyOTVZ:-KtxI1eWCmO2tirQ6vKH:br3w353) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L78)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Paul, what do these "Other simulation" comments mean?
</blockquote></details>

Done.  Fixed comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010)*

**Comment by edrumwri** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010)*

**Comment by sherm1** [comment]
Platform pass: per f2f it is unclear what this is testing. This needs a comprehensive explanation and justification for the test being here, and how it fits into future plans.

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Kts_PFJke_vvLEd6dWx:-KtxkB-plbOBiMS3ojhG:b5li4dk) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L59)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

As we discussed, these values are fences around the results that were sized by multiple simulations.
I would prefer to leave these unnamed as they are somewhat too arbitrary for names.
</blockquote></details>

BTW should add a comment to that effect so we know where these came from.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtxjYC-z12YkmiNbYw1:-KtxjYC-z12YkmiNbYw2:b-3g1suy) ([raw file](https://github.com/robotlocomotion/drake/blob/5f7f8683d22dab2608a1efbfef505ffee1d169dd/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L13)):*
> ```cpp
> namespace benchmarks {
> namespace chaotic_babyboot {
> namespace MG {
> ```

BTW Per f2f remove MG namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-:-KtxmKYdo7yN8Knsa-kH:b-3wc3p3)*

**Comment by mitiguy** [comment]
@drake-jenkins-bot  linux-clang-experimental-debug  please

**Comment by mitiguy** [comment]
@sherm1 @edrumwri   Ready for review again.

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-:-Ku2AWS7-DUHu4WvI-MO:bwwl19i)*

**Comment by edrumwri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtvhzgqEqVKFJGyOTVZ:-Ku4r943LJwyE6C0ZP_7:b9ghg4) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L78)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Done.  Fixed comments.
</blockquote></details>

Since you constructed your "fencing values" above, why not run three tests: one with the outputs from each of these three simulations? 

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Ku4q5nA9mb3REb9zGUl:-Ku4q5nA9mb3REb9zGUm:brbmhyt) ([raw file](https://github.com/robotlocomotion/drake/blob/6c47c45de346b17b15b10276fdac5134e82d9c33/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L20)):*
> ```cpp
> // qB      |  Chaotic babyboot's plate angle (rigid body B).
> // qADt    |  1st-time-derivative of angle qA (a.k.a. qAdot).
> // qADt    |  1st-time-derivative of angle qB (a.k.a. qBdot).
> ```

qADt -> qBDt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a few comment changes, PTAL.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 90 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Ku6gJuc3K_AE5_yC1Ig:-Ku6gJuc3K_AE5_yC1Ih:b126ai2) ([raw file](https://github.com/robotlocomotion/drake/blob/6c47c45de346b17b15b10276fdac5134e82d9c33/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L90)):*
> ```cpp
> // BUILD file: copts = ["-Wno-unused-parameter"] to account for unused arguments
> // in MotionGenesis auto-generated code.  Problems encountered with dealing
> // with auto-generated code also motivated fixes to the build system.
> ```

BTW the above would be a reason to have done this once, but what is the reason for reason for incorporating this into Drake and running it repeatedly? I think the first sentence above captures part of that, but that certainly isn't the *only* reason. I don't think there is any reason to include the details above. Maybe just one sentence like "This test verifies that an MG-generated model can be properly integrated into Drake." (That has to be continually re-verified since code changes might break it.)

I think the other reason for this test is to establish some baseline results with the intent that we are going to use these to validate some aspects of Drake. That needs a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-:-Ku6i9E3aetiV0PEvHOU:b-dk303f)*

**Comment by mitiguy** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-KtvhzgqEqVKFJGyOTVZ:-KuQTcRLDYMzgs0f9X5z:b-xj4ktd) ([raw file](https://github.com/robotlocomotion/drake/blob/213706f37ea9c0d096974447edd5ef69362f8674/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L78)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Since you constructed your "fencing values" above, why not run three tests: one with the outputs from each of these three simulations? 
</blockquote></details>

I prefer to leave this test as is -- it has served its immediate purpose.
I do not want the replicate the MATLAB ODE45 integrator.
I added a TODO(@mitiguy) to address comparing this with Drake results.

---

*[drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-Ku4q5nA9mb3REb9zGUl:-KuQOcqsSdCrCm0kwG4z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6c47c45de346b17b15b10276fdac5134e82d9c33/drake/multibody/benchmarks/chaotic_babyboot/MG/test/MG_chaotic_babyboot_test.cc#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

qADt -> qBDt
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010)*

**Comment by mitiguy** [comment]
@edrumwri  -- see if you like the update.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-:-KuQoUJIHF1VUNpwIGYU:bc40de)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7010#-:-KuQosyNPzgrcCYE7haO:bnfp4nl)*

**Pull request merged**
