### PR TITLE
Update snopt submodule SHA to fix MATLAB-Xcode builds

### PR DESCRIPTION
**Pull request by jamiesnape**
Brings in RobotLocomotion/snopt#15.  FYI @RussTedrake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4622)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Only failure due to issue fixed by #4618.

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@jwnimmer-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4622#-:-K_4zu7SLRZxF3g2bgZ-:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-xcode-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4622#-:-K_5-afbdKmKpc7ronoo:bnfp4nl)*

**Pull request merged**
