### PR TITLE
Automotive simulator support for TrajectoryCar

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3540)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Note that the first two commits are based on #3520 and should not be reviewed.

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri (self-assign) for when this is cooked.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSCExZQQI2nWwlUNPkS:be5tiek)*

**Comment by liangfok** [comment]
+@liangfok 

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSCGwQ_DWEabBT2XX0f:b-gyxe3j)*

**Comment by jwnimmer-tri** [comment]
Ready for review.  Note that a big chunk of this is a relocated helper function (`MakeCurve`), which will be deleted sooner rather than later.  The `CreateTrajectoryParams` will also be deleted.  But the other parts of code here are intended to a bit more permanent.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSClXsx-wnTAt04IOvR:bgy1k3p)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSCnWN8ZTVDZmSE_LUW:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSCtWSyebxTKoZFVxzA:bdph6cr)*

**Comment by liangfok** [comment]
Done with first pass. Just one question.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-KSCuZLSofJrF1LT7kPk:-KSCuZLSofJrF1LT7kPl:b5ovadb) ([raw file](https://github.com/robotlocomotion/drake/blob/3978a5b8e94f591f436d00c9981348cb4cdc9718/drake/automotive/test/automotive_simulator_test.cc#L76)):*
> ```cpp
>   auto simulator = std::make_unique<AutomotiveSimulator<double>>();
>   simulator->AddTrajectoryCar(curve, 1.0, 0.0);
>   simulator->AddTrajectoryCar(curve, 1.0, 10.0);
> ```

I see that the second car is added at time = 10 seconds. However, the code below appears to only run for 100 * 0.01 = 1 second. Thus, does the second car actually start moving in this unit test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSCv5P67kjDP4lfdK9d:b1mvitq)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/test/automotive_simulator_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-KSCuZLSofJrF1LT7kPk:-KSCxROh898UIeCvJZ_F:bm61fer) ([raw file](https://github.com/robotlocomotion/drake/blob/3978a5b8e94f591f436d00c9981348cb4cdc9718/drake/automotive/test/automotive_simulator_test.cc#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I see that the second car is added at time = 10 seconds. However, the code below appears to only run for 100 * 0.01 = 1 second. Thus, does the second car actually start moving in this unit test?
</details>
Correct, it would stay at the origin, but would still exercise many of the code paths (the point at which the "not moving yet" has effect is deep within Curve2).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-KSCuZLSofJrF1LT7kPk:-KSCxy8KzeAehpy_7aQ2:b-jufc4y) ([raw file](https://github.com/robotlocomotion/drake/blob/3978a5b8e94f591f436d00c9981348cb4cdc9718/drake/automotive/test/automotive_simulator_test.cc#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Correct, it would stay at the origin, but would still exercise many of the code paths (the point at which the "not moving yet" has effect is deep within Curve2).
</details>
OK. SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSCxzV-JupJM5ZjPxlA:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3540#-:-KSDk9qODeV0z37rT2wD:bnfp4nl)*

**Pull request merged**
