### PR TITLE
Move RigidBody::adjacentTo into the cc file.

### PR DESCRIPTION
**Pull request by david-german-tri**
Also add some missing includes.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2615)

### CODE REVIEW

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBody.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2615#-KKsrcW9pI01HHFcRdEl:-KKsrcWAWwsOaNnH_ESB:2026455970) ([raw file](https://github.com/robotlocomotion/drake/blob/20b223be028f57ccfa2fd27a4181448e76140cce/drake/systems/plants/RigidBody.h#L14)):*
> ```objc
> #include "drake/systems/plants/collision/DrakeCollision.h"
> #include "drake/systems/plants/joints/DrakeJoint.h"
> #include "drake/util/drakeGeometryUtil.h"
> ```

Why does moving the method body of `RigidBody::adjacentTo()` to the `.cpp` file result in the need to add this `#include` line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2615)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBody.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2615#-KKsrcW9pI01HHFcRdEl:-KKt2MAXJxfisX1vwc48:-1685968432) ([raw file](https://github.com/robotlocomotion/drake/blob/20b223be028f57ccfa2fd27a4181448e76140cce/drake/systems/plants/RigidBody.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Why does moving the method body of `RigidBody::adjacentTo()` to the `.cpp` file result in the need to add this `#include` line?
</details>
It doesn't.  This was unrelated cleanup in the same file.  Updated PR description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2615)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2615#-:-KKt2Wf_eMuj9zu5o9tY:-1868698381)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2615#-:-KKt3FhnY3n_8nkwCJmp:1417088721)*

**Pull request merged**
