### PR TITLE
Updates pendulum passive simulation to use MBP

### PR DESCRIPTION
**Pull request by amcastro-tri**
Use MBP for the passive simulation example. The same pendulum factory will be used for linearization unit tests in an upcoming PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8292)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please.
+@ggould-tri for platform review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8292#-:-L70WeYxkg4chu-GMHZO:bvzka7c)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/benchmarks/pendulum/make_pendulum_plant.cc, line 69 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8292#-L70d7_x5xBhwa5dqQEz:-L70d7_x5xBhwa5dqQF-:b-ki05s1) ([raw file](https://github.com/robotlocomotion/drake/blob/770213661468768ee32bc775077f18ea64a8f42a/multibody/benchmarks/pendulum/make_pendulum_plant.cc#L69)):*
> ```cpp
>   const RevoluteJoint<double>& pin = plant->AddJoint<RevoluteJoint>(
>       params.pin_joint_name(),
>       /* Shoulder inboard frame IS the the world frame W. */
> ```

FYI typo 'the the'

---

*[multibody/benchmarks/pendulum/make_pendulum_plant.cc, line 73 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8292#-L70dAwd5sA4YtFYstyy:-L70dAwd5sA4YtFYstyz:b-16mfvz) ([raw file](https://github.com/robotlocomotion/drake/blob/770213661468768ee32bc775077f18ea64a8f42a/multibody/benchmarks/pendulum/make_pendulum_plant.cc#L73)):*
> ```cpp
>       /* Pin joint outboard frame IS the body frame B. */
>       point_mass, {},
>       Vector3d::UnitY()); /* pendulum oscillates in the x-z plane. */
> ```

FYI please capitalize complete sentence.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8292#-:-L70dPML6OZ8CD5Ytk2U:bnfp4nl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/benchmarks/pendulum/make_pendulum_plant.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8292#-L71dJ7J9Yp4Qk7Wo83P:-L71dJ7Kee9hDnj_AzuV:b-xm11zq) ([raw file](https://github.com/robotlocomotion/drake/blob/770213661468768ee32bc775077f18ea64a8f42a/multibody/benchmarks/pendulum/make_pendulum_plant.cc#L75)):*
> ```cpp
>       Vector3d::UnitY()); /* pendulum oscillates in the x-z plane. */
> 
>   // Add acrobot's actuator at the elbow joint.
> ```

`acrobot`->`pendulum`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8292#-:-L71dSrj1dBOwZcFkPor:bnfp4nl)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/benchmarks/pendulum/make_pendulum_plant.cc, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8292#-L71dJ7J9Yp4Qk7Wo83P:-L71gSAmGP5d5jOck28b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/770213661468768ee32bc775077f18ea64a8f42a/multibody/benchmarks/pendulum/make_pendulum_plant.cc#L75)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`acrobot`->`pendulum`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8292)*

**Pull request merged**
