### PR TITLE
[ad] Add support for arithmetic operations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17492.

More operations are on the way after this, e.g., #17636.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: 

With a suggestion and a question.

> Reviewed 26 of 32 files at r2, 6 of 6 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622#-:-N81F8g5D19BlwDcVs77:brfoiem)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/test/autodiffxd_multiplication_test.cc` line 4 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N81EWac2Wh_97Sku-Zr:-N81EWac2Wh_97Sku-Zs:bdmjf8z) ([raw file](https://github.com/robotlocomotion/drake/blob/5e36cf59d4936a48f906af705bc57b11fad453a0/common/test/autodiffxd_multiplication_test.cc#L4)):*
> ```cpp
> #include "drake/common/autodiff.h"
> #include "drake/common/ad/test/standard_operations_test.h"
> /* clang-format on */
> ```

I was trying to figure out why this file still exists (it and the other tests that have been implemented in `standard_operations***`. There are two significant differences:

1. This file is responsible for including the form of autodiff that should be declared as a directive.
2. In some cases, the `AutoDiffXd` variant is a subset of the `standard_operation` variant (e.g., unary addition and subtraction).

Can you elaborate?
___
*[`common/ad/test/standard_operations_test.h` line 17 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N81B59yCrJq2t0838Gh:-N81B59z-hHKGXGxQ5WY:b5oy21j) ([raw file](https://github.com/robotlocomotion/drake/blob/5e36cf59d4936a48f906af705bc57b11fad453a0/common/ad/test/standard_operations_test.h#L17)):*
nit: If I were to run this test, I would have no idea what valid strings to pass. Furthermore, it sounds like instructions to the reader. In reality, it coordinates with the build system to run the same tests on the old and new autodiff implementations.

Presumably, this will go away when there is only a single AutoDiff type, yes? In the interim, it might be worth providing a bit more context (e.g., calling out the possible values or point to the corresponding bazel files, suggest the duration of this particular mechanism, etc.)

Something more like:

> While we are transitioning between the old and new auto diff implementations, this preprocessor macro allows us to use the same infrastructure to test both kinds. It is defined in common/BUILD.bazel and common/ad/BUILD.bazel as "drake::AutoDiffXd" and "drake::ad::AutoDiff" for the old and new implementations, respectively.

(I think that hits all my notes.)

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622#-:-N81SQg7AR67L0rrfDe5:b2xa7ij)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`common/test/autodiffxd_multiplication_test.cc` line 4 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N81EWac2Wh_97Sku-Zr:-N81PnlI-ATJWMgWyKxh:b-7egk5) ([raw file](https://github.com/robotlocomotion/drake/blob/5e36cf59d4936a48f906af705bc57b11fad453a0/common/test/autodiffxd_multiplication_test.cc#L4)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was trying to figure out why this file still exists (it and the other tests that have been implemented in `standard_operations***`. There are two significant differences:

1. This file is responsible for including the form of autodiff that should be declared as a directive.
2. In some cases, the `AutoDiffXd` variant is a subset of the `standard_operation` variant (e.g., unary addition and subtraction).

Can you elaborate?
</blockquote></details>

My basic premise is that I want to leave the existing unit tests for `autodiffxd.h` completely unaltered during this rewrite.  In many cases, as you've noted, I'll be adding _more_ kinds of test cases for the new implementation.
___
*[`common/ad/test/standard_operations_test.h` line 17 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N81B59yCrJq2t0838Gh:-N81S3vs4Czn2lq8o_7r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5e36cf59d4936a48f906af705bc57b11fad453a0/common/ad/test/standard_operations_test.h#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: If I were to run this test, I would have no idea what valid strings to pass. Furthermore, it sounds like instructions to the reader. In reality, it coordinates with the build system to run the same tests on the old and new autodiff implementations.

Presumably, this will go away when there is only a single AutoDiff type, yes? In the interim, it might be worth providing a bit more context (e.g., calling out the possible values or point to the corresponding bazel files, suggest the duration of this particular mechanism, etc.)

Something more like:

> While we are transitioning between the old and new auto diff implementations, this preprocessor macro allows us to use the same infrastructure to test both kinds. It is defined in common/BUILD.bazel and common/ad/BUILD.bazel as "drake::AutoDiffXd" and "drake::ad::AutoDiff" for the old and new implementations, respectively.

(I think that hits all my notes.)
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Oh, just saw those timing numbers, awesome!

:lgtm:
With a question and a suggestion.

> Reviewed 26 of 32 files at r2, 6 of 6 files at r3, 5 of 7 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622#-:-N85Ic6s-VCcnn3lQwY_:b-pdih0r)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`common/ad/test/standard_operations_dec_test.cc` line 11 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N85I5ti0rCfFMnnmGE1:-N85I5tj600BmX982_E8:b4crtuh) ([raw file](https://github.com/robotlocomotion/drake/blob/cdcf4af052c1a662cfdc5d468f058851f68198eb/common/ad/test/standard_operations_dec_test.cc#L11)):*
> ```cpp
> 
> TEST_F(StandardOperationsTest, Postdecrement) {
>   AutoDiffDut x{0.25, 10, 0};
> ```

nit Motivation for `size=10` unclear, esp. given those values are not explicit tested. (here, below, and in other files)

Consider `size=2`, checking both non-zero and zero values?
___
*[`common/ad/test/standard_operations_stream_test.cc` line 11 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N85IkZk5mgZXe8lEUIF:-N85IkZk5mgZXe8lEUIG:b-vg6qb5) ([raw file](https://github.com/robotlocomotion/drake/blob/cdcf4af052c1a662cfdc5d468f058851f68198eb/common/ad/test/standard_operations_stream_test.cc#L11)):*
> ```cpp
> 
> TEST_F(StandardOperationsTest, Stream) {
>   const AutoDiffDut x{0.25, 10, 0};
> ```

nit Same as before.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17622)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`common/ad/test/standard_operations_dec_test.cc` line 11 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17622#-N85I5ti0rCfFMnnmGE1:-N85KCU37L1cs2I0p4Dr:bgzzcdm) ([raw file](https://github.com/robotlocomotion/drake/blob/cdcf4af052c1a662cfdc5d468f058851f68198eb/common/ad/test/standard_operations_dec_test.cc#L11)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Motivation for `size=10` unclear, esp. given those values are not explicit tested. (here, below, and in other files)

Consider `size=2`, checking both non-zero and zero values?
</blockquote></details>

OK fair point.  I've switched all of the "10" to "3" now, to align with the derivatives size in the AutoDiffDut test fixture.

There's ~4 more "standard operations" PRs on the way soon.  In those, I'll pay attention in case the "3" magic grows and pull it out into a fixture kConstant.

**Pull request merged**
