### PR TITLE
[geometry] Don't spuriously test for exception subtypes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See https://drake.mit.edu/styleguide/cppguide.html#Exceptions.

Towards #16514.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16510)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
+@xuchenhan-tri

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16510#-:-Mv4wPlG0zznhYA_YTWz:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16510#-Mv4w2xq-i9gmQdBSREt:-Mv4w2xq-i9gmQdBSREu:bh3s6v9) (no related file):*
Looks like this fix is a result of grepping `DRAKE_EXPECT_THROWS_MESSAGE`? There are a few `EXPECT_THROW` that still tests for subtypes. Do you want to fix those as well?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16510)* status: 1 unresolved discussion, needs platform reviewer assigned (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16510#-Mv4w2xq-i9gmQdBSREt:-Mv4x_Fk4xVr9fhh3bwm:b-r5lfki) (no related file):*
> Looks like this fix is a result of grepping `DRAKE_EXPECT_THROWS_MESSAGE`?

It's a result of chasing down the compiler errors from the #16514 deprecation.

> There are a few `EXPECT_THROW` that still tests for subtypes. Do you want to fix those as well?

With `DRAKE_EXPECT_THROWS_MESSAGE`, we can be fairly sure that the exception subtype was irrelevant to the specificity of the test case -- the message is what localizes the fault condition, not the type.  With `EXPECT_THROW`, it's possible that the subtype implies which control flow path was taken inside the device under test, so we can't blindly demote all of those to `std::exception`.  I'm content to leave `EXPECT_THROW` for another day.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16510)* status: 1 unresolved discussion, needs platform reviewer assigned (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16510#-Mv4w2xq-i9gmQdBSREt:-Mv4yRk16oQQ3xkNlsSo:b-yavjij) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Looks like this fix is a result of grepping `DRAKE_EXPECT_THROWS_MESSAGE`?

It's a result of chasing down the compiler errors from the #16514 deprecation.

> There are a few `EXPECT_THROW` that still tests for subtypes. Do you want to fix those as well?

With `DRAKE_EXPECT_THROWS_MESSAGE`, we can be fairly sure that the exception subtype was irrelevant to the specificity of the test case -- the message is what localizes the fault condition, not the type.  With `EXPECT_THROW`, it's possible that the subtype implies which control flow path was taken inside the device under test, so we can't blindly demote all of those to `std::exception`.  I'm content to leave `EXPECT_THROW` for another day.
</blockquote></details>

Makes sense, thanks!

This PR is ready for the platform rubber stamp.

---

**Pull request merged**
