### PR TITLE
Add jaco lcm time input/output ports

### PR DESCRIPTION
**Pull request by sammy-tri**
Also updates the names on some iiwa ports.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220)

### CODE REVIEW

**Review by sammy-tri — COMMENTED** [review]
+@mpetersen94 for feature review if you have time (relates to #18167).  Let me know if you're not going to be able to get to it and I'll reassign.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220#-:-NFjvYIxDID9Fkp9gaBn:ba0moo9)* status: LGTM missing from assignee mpetersen94, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
Looks great! Had a few nits about comments. Thanks for doing this!

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220#-:-NFkOGqi9rLG9v1LHdAr:buhiss4)* status: 4 unresolved discussions, LGTM missing from assignee mpetersen94, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @sammy-tri)

___
*[`manipulation/kinova_jaco/jaco_command_receiver.h` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkJO2t-2meCZp5jIUY:-NFkJO2t-2meCZp5jIUZ:b9ax9yq) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kinova_jaco/jaco_command_receiver.h#L50)):*
> ```objc
> /// available to achieve the same effect without using events.
> /// @par
> /// The "time" output will always be a vector of zeros.
> ```

nit: I don't understand this comment. I feel like the intention is to say that the time outputs a vector of 1 zero before receiving a message. However, a quick reading makes me think it will always output a vector of zeros (of unspecified length). If the intention is the one I mentioned, could you integrate this comment into the above comment and specify the output is a vector of a single zero (or something similar)?
___
*[`manipulation/kinova_jaco/jaco_command_sender.h` line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkKTaI2zaj2bhXO6By:-NFkKTaI2zaj2bhXO6Bz:b-d4ldfo) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kinova_jaco/jaco_command_sender.h#L53)):*
> ```objc
> 
>   /// Gets the optional input port for the message time.  If this port is not
>   /// connected, the context time will be used.
> ```

nit: The second sentence in this comment might be better in the documentation of the class.
___
*[`manipulation/kinova_jaco/jaco_status_receiver.h` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkLZag3JJlhHdzBZQf:-NFkLZag3JJlhHdzBZQg:b-ayjttj) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kinova_jaco/jaco_status_receiver.h#L35)):*
> ```objc
> /// - lcmt_jaco_status
> /// output_ports:
> /// - time_measured
> ```

Consider listing this port last to match the underlying port ordering as you did elsewhere (although given that port ordering is not stable, I'm a little ambivalent).
___
*[`manipulation/kinova_jaco/jaco_status_receiver.h` line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkLI079W8Y6UZSeVGR:-NFkLI079W8Y6UZSeVGS:bw7hpkm) ([raw file](https://github.com/robotlocomotion/drake/blob/958e225dc505501bea065f9217a5574be87e8ab7/manipulation/kinova_jaco/jaco_status_receiver.h#L68)):*
> ```objc
> 
>  private:
>   void CalcStateOutput(const systems::Context<double>&,
> ```

Thanks for this cleanup!
___
*[`manipulation/kuka_iiwa/iiwa_command_receiver.h` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkMNFtCYO_81qIrxok:-NFkMNFtCYO_81qIrxol:bni6w50) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kuka_iiwa/iiwa_command_receiver.h#L21)):*
> ```objc
> ///
> /// It has three output ports: one for the commanded position for each joint,
> /// one one for commanded additional feedforward joint torque, and one for the
> ```

Double "one"
___
*[`manipulation/kuka_iiwa/iiwa_command_receiver.h` line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkMpDz5G_Hi1jM0OAU:-NFkMpDz5G_Hi1jM0OAV:bpnv1tf) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kuka_iiwa/iiwa_command_receiver.h#L44)):*
> ```objc
> /// available to achieve the same effect without using events.
> /// @par
> /// The "torque" and "time" outputs will always be a vector of zeros.
> ```

See comment above about similar issue. I don't think this accurately describes the behavior of either port.

**Review by sammy-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220#-:-NFt7t7h5wt-9tMK__qg:bsrwoh2)* status: 3 unresolved discussions, LGTM missing from assignees mpetersen94,xuchenhan-tri(platform) (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[`manipulation/kinova_jaco/jaco_command_receiver.h` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkJO2t-2meCZp5jIUY:-NFt4EKkCtfsTtWQo8Q4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kinova_jaco/jaco_command_receiver.h#L50)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

nit: I don't understand this comment. I feel like the intention is to say that the time outputs a vector of 1 zero before receiving a message. However, a quick reading makes me think it will always output a vector of zeros (of unspecified length). If the intention is the one I mentioned, could you integrate this comment into the above comment and specify the output is a vector of a single zero (or something similar)?
</blockquote></details>

Done.
___
*[`manipulation/kinova_jaco/jaco_command_sender.h` line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkKTaI2zaj2bhXO6By:-NFt4RP3ALdGNn2LBoyU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kinova_jaco/jaco_command_sender.h#L53)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

nit: The second sentence in this comment might be better in the documentation of the class.
</blockquote></details>

Done.
___
*[`manipulation/kinova_jaco/jaco_status_receiver.h` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkLZag3JJlhHdzBZQf:-NFt53ARCqCriNSdDmQJ:bejmnjk) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kinova_jaco/jaco_status_receiver.h#L35)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Consider listing this port last to match the underlying port ordering as you did elsewhere (although given that port ordering is not stable, I'm a little ambivalent).
</blockquote></details>

Done.  I'd originally copied the order from `IiwaStatusReceiver`, but then I realized it did change it's port ordering.
___
*[`manipulation/kuka_iiwa/iiwa_command_receiver.h` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkMNFtCYO_81qIrxok:-NFt4asT4KAyZ19zzRd5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kuka_iiwa/iiwa_command_receiver.h#L21)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Double "one"
</blockquote></details>

Done.
___
*[`manipulation/kuka_iiwa/iiwa_command_receiver.h` line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFkMpDz5G_Hi1jM0OAU:-NFt4r5u5LHzn1eeXT8k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b74753fadc64cc9a14e7f1f10f1566d279b26145/manipulation/kuka_iiwa/iiwa_command_receiver.h#L44)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

See comment above about similar issue. I don't think this accurately describes the behavior of either port.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220)* status: 4 unresolved discussions, LGTM missing from assignee mpetersen94 (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[`manipulation/kuka_iiwa/iiwa_command_sender.h` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFtMTzS03ENTHzMctGD:-NFtYOH1EQ2WCyOWZamg:bjcn0lv) ([raw file](https://github.com/robotlocomotion/drake/blob/202fc3d80382eaeb40457d6f6bfa35f1939ba395/manipulation/kuka_iiwa/iiwa_command_sender.h#L48)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, is this a breaking change?
</blockquote></details>

It shouldn't be, the previous spelling was only introduced in #18167 and there hasn't been a release since then.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220)* status: 3 unresolved discussions, LGTM missing from assignee mpetersen94 (waiting on @mpetersen94)

___
*[`manipulation/kuka_iiwa/iiwa_command_sender.h` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFtMTzS03ENTHzMctGD:-NFtm-sK9M3n9RGSAZfA:bhxjq5r) ([raw file](https://github.com/robotlocomotion/drake/blob/202fc3d80382eaeb40457d6f6bfa35f1939ba395/manipulation/kuka_iiwa/iiwa_command_sender.h#L48)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It shouldn't be, the previous spelling was only introduced in #18167 and there hasn't been a release since then.
</blockquote></details>

I see. Thanks!

**Review by mpetersen94 — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18220#-:-NFuVxcG2yV5Q8D53Q1m:bg7igkv)* status: 1 unresolved discussion (waiting on @sammy-tri)

___
*[`manipulation/kuka_iiwa/iiwa_command_receiver.h` line 43 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18220#-NFuW23J8nzU5moLq3Ul:-NFuW23J8nzU5moLq3Um:bvt3elc) ([raw file](https://github.com/robotlocomotion/drake/blob/c36714e62099a64d0ee05ed11a346e6af741a65c/manipulation/kuka_iiwa/iiwa_command_receiver.h#L43)):*
> ```objc
> /// the "position" input.  Alternatively, the LatchInitialPosition() method is
> /// available to achieve the same effect without using events.  The "torque"
> /// and output will be a vector of zeros, and the "time" output will be a
> ```

Unneeded "and"

**Pull request merged**
