### PR TITLE
primitives: Remove templates from RandomSource APIs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Templates are stupid and make compilation times long and error messages bad.

This also might make it easier to extract the state of a RandomSource (#11676).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11670)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake please check the random_source.h changes to see if you approve?  I can seek a whole-PR feature reviewer after that.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.  (No hurry; I won't get back to this until Monday.)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Comment by jamiesnape** [comment]
This looks to have triggered a variation of https://github.com/RobotLocomotion/drake/issues/11424, unfortunately.

**Pull request merged**
