### PR TITLE
[solvers] IpoptSolver doesn't hard-code the linear solver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21476.  This will simplify the work of changing which linear solver(s) the build system provides.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22275)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for (low priority) feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: question

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22275#-:-ODO50Wq2n9n0nvM2ilW:bxgtfmd)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`solvers/ipopt_solver.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22275#-ODO4nZ7-P09ukKOTU2q:-ODO4nZ7-P09ukKOTU2r:blum6hb) ([raw file](https://github.com/RobotLocomotion/drake/blob/eccba50318da5c0bcf09e1fbc77c8892a70c59b5/solvers/ipopt_solver.cc#L157)):*
> ```cpp
>   const std::vector<std::string_view> linear_solvers =
>       internal::GetSupportedIpoptLinearSolvers();
>   if (!linear_solvers.empty()) {
> ```

nit is empty string a legal value for default_linear_solver_ ? If so, cool. If not, shouldn't there be an `else` ?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22275)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`solvers/ipopt_solver.cc` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22275#-ODO4nZ7-P09ukKOTU2q:-ODO6bQe04fVOUIstG7t:b-raql3s) ([raw file](https://github.com/RobotLocomotion/drake/blob/eccba50318da5c0bcf09e1fbc77c8892a70c59b5/solvers/ipopt_solver.cc#L157)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit is empty string a legal value for default_linear_solver_ ? If so, cool. If not, shouldn't there be an `else` ?
</blockquote></details>

Yes, empty is a legal value.  When empty, these lines earlier in this file ...

```c++
  if (!default_linear_solver.empty()) {
    set_string_option("linear_solver", default_linear_solver);
  }
```

... will not try to set any Drake-specific default, instead allowing IPOPT's built-in upstream default to remain unchanged.

This could happen if the user is building Drake as a Bazel external and has replaced our build of `@ipopt` with their own customized build.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22275#-:-ODgKPrq9VwAwF8TAS3M:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
