### PR TITLE
Add Jaco lcmtypes and send/receive systems

### PR DESCRIPTION
**Pull request by sammy-tri**
I'm slowly working on committing the Jaco related stuff I've already done to master.  I don't think this will necessarily get us to a completely working jaco stack with tested IK like we have for the iiwa, but I don't see any good reason to let stuff I've already done rot on a branch.

I've got another PR to drake after this which adds a simple controller, and then a sample director app and a driver which I need to decide what to do with.

This PR is past the 500 line limit (including whitespace), but a lot of it is either comments or boilerplate, so I hope that's OK.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7267)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@rcory for feature review (If you don't mind I'll probably tag you for the controller PR too)

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-Kw_hs0__wbNRcxAqoRz:bioqu87)*

**Comment by rcory** [comment]
I'm a bit surprised at how bad the state reporting from the Jaco seems to be. These conversion factors seem arbitrary, and I'm wondering if they're reporting data in non-standard units or some other measurement that is not at the joint (e.g., lead screw for the fingers etc.). 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/BUILD.bazel, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwqRX3cnN0Z-u3JBrJ2:-KwqRX3cnN0Z-u3JBrJ3:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/BUILD.bazel#L118)):*
> ```
>     deps = [
>         ":jaco_lcm",
>         "//drake/common/test_utilities:eigen_matrix_compare",
> ```

unused?

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwqSD5Oq4isNQWMWj_k:-KwqSD5Oq4isNQWMWj_l:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L16)):*
> ```cpp
> using systems::Context;
> using systems::DiscreteValues;
> using systems::State;
> ```

unused?

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwqSEXfsYmUWJ36yJCo:-KwqSEXfsYmUWJ36yJCp:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L17)):*
> ```cpp
> using systems::DiscreteValues;
> using systems::State;
> using systems::SystemOutput;
> ```

unused?

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kwq-3-GpDv5H0dSatEk:-Kwq-3-GpDv5H0dSatEl:b-oyk083) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L27)):*
> ```cpp
> namespace {
> // Kinova's JACO urdf's have a 0-114 degree (0-2 radian) range for the
> // finger joints, but the SDK's position values range from 0-6800
> ```

BTW, maybe these are motor encoder counts? This number seems awfully large to represent joint rotation in degrees.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kwq4MxlhfRJFQVwKKft:-Kwq4MxlhfRJFQVwKKfu:b5d0ktw) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L160)):*
> ```cpp
>     // It seems like the Jaco reports half of the actual angular
>     // velocity.  Fix that up here.  Note bug-for-bug compatibility
>     // implemented in JacoStatusSender.
> ```

BTW, totally weird. I wonder if there's something funky going on with the units they are reporting in (vs being an actual bug, although I wouldn't doubt it). 

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwqOqgoQz1z1Pam3MY1:-KwqOqgoQz1z1Pam3MY2:b-r0ozyk) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L220)):*
> ```cpp
>     // It seems like the Jaco reports half of the actual angular
>     // velocity.  Simulate that here.  Note this is also handled in
>     // JacoStatusReceiver.
> ```

BTW, the state reporting from the Jaco seems to be a total mess. Might be worth sending an email to tech support? I asked Ron here at HQ and he hasn't yet looked at or used velocities, so I wasn't able to confirm the same behavior. 

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpYqv09rYJxk_EywaC:-KwpYqv09rYJxk_EywaD:b-aquva) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.h#L23)):*
> ```objc
> namespace kinova_jaco_arm {
> 
> constexpr int kJacoDefaultArmNumJoints = 7;
> ```

BTW I initially saw this and wasn't sure this would support the 6-dof Jaco (then saw the constructor). Perhaps add a comment in the header stating this can support any(?) Jaco model?

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwphbnNITVmdIHlVy0S:-KwphbnNITVmdIHlVy0T:buyxcy4) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.h#L95)):*
> ```objc
> ///
> /// All ports will continue to output their initial state (typically
> /// zero) until a message is received.
> ```

BTW nit I like the doxy blocks for the sender classes, but receiver class doxy blocks seem to get a little less love.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpafyEtEKA2OyRGGyI:-KwpafyEtEKA2OyRGGyJ:b1qhywa) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/jaco_lcm.h#L127)):*
> ```objc
> /// a systems::lcm::LcmPublisherSystem that accepts a
> /// systems::Value object templated on type `lcmt_jaco_status`. For an example
> /// of this, see jaco_wsg_simulation.cc.
> ```

Hmm, I don't see `jaco_wsg_simulation.cc`. Is it in another PR?

---

*[drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwqRc4nh9Rk6DdXS3aT:-KwqRc4nh9Rk6DdXS3aU:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc#L6)):*
> ```cpp
> #include <gtest/gtest.h>
> 
> #include "drake/common/test_utilities/eigen_matrix_compare.h"
> ```

unused?

---

*[drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpkVaXihDHJOxkU7jX:-KwpkVaXihDHJOxkU7jY:bpu57yt) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc#L23)):*
> ```cpp
>   auto command_sender = builder.AddSystem<JacoCommandSender>();
>   auto command_receiver = builder.AddSystem<JacoCommandReceiver>();
>   builder.Connect(command_receiver->get_output_port(0),
> ```

BTW, this was a little confusing to me at first. I was expecting the connection to be from command_sender output port to command receiver input port (I think this is how they would be used in practice?). But the ordering for the test probably(?) doesn't matter, so long as the results pass through unchanged. Same comment for the `JacoStatusPassthroughTest`.

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpogQbU3dAyWB1oF3P:-KwpogQbU3dAyWB1oF3Q:b-t43g63) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/lcmtypes/lcmt_jaco_status.lcm#L14)):*
> ```
>   double joint_position[num_joints];
>   double joint_velocity[num_joints];
>   double joint_force[num_joints];
> ```

BTW, assuming this is joint torque measured at the joint via a torque sensor, and not just motor current scaled by a torque constant? Maybe a note about that here?

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpTkM28MirIUYwJGS7:-KwpTkM28MirIUYwJGS8:bvbdfu9) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/lcmtypes/lcmt_jaco_status.lcm#L20)):*
> ```
>   double finger_position[num_fingers];
>   double finger_velocity[num_fingers];
>   double finger_force[num_fingers];
> ```

BTW should `joint_force` and `finger_force` instead be `joint_torque` and `finger_torque`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-KwqT5xH7VLmom75webt:bdvfus)*

**Comment by rcory** [comment]
Wow. 10800 deg/s == 30 revolutions/sec is insanely fast (table saw fast?). I just poked Ron and saw that the spec sheet shows "actuator speed". Since the fingers are the only ones that seem to go through a lead screw, I'm wondering if the 10800 deg/s is actually the motor speed and not the speed at the output of the lead screw (i.e., at the actual finger joints).  Then the numbers start to make more sense, I think.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpogQbU3dAyWB1oF3P:-KwvYXt7um6mdJ7fRH8a:b-qtimvp) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/lcmtypes/lcmt_jaco_status.lcm#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The API docs aren't explicit about how the value is generated.  I could look elsewhere if you think it's worth researching.
</blockquote></details>

OK. Thanks for checking. Good for now.

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpTkM28MirIUYwJGS7:-KwvZ9doeRcBEdy8FeP8:b8hjldh) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/lcmtypes/lcmt_jaco_status.lcm#L20)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The Kinova API docs use the term "angular force" but then go on to say "This function returns the torque of each actuator. Unit is Newton meter [N * m]. "  I'm happy to switch to whichever seems clearer.
</blockquote></details>

"angular force" just sounds odd. I quickly checked with the dynamics folks and got the same reaction. "torque" seems clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-KwvmRfJ_UNctOOSFoDE:b8cppq6)*

**Comment by rcory** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-Kwvm_uzx2WOB_Gl13JE:bnfp4nl)*

**Comment by rcory** [comment]
+@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-KwvnAro9PjOq8ur417e:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a few minor BTWs, ptal.

---

Reviewed 2 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5YNCLiHXzJ1sHrxWW:-Kx5YNCLiHXzJ1sHrxWX:b-4xvur0) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L26)):*
> ```cpp
> // Kinova's JACO urdf's have a 0-114 degree (0-2 radian) range for the
> // finger joints, but the SDK's position values range from 0-6800
> // degrees (0-118.68 radian).  Convert these as appropriate here.  I
> ```

BTW hard to believe those are actually degrees. Consider instead something like "position values range from 0-6800 units, which we have to map to the 0-2 radian finger joint range". But apparently someone has already scaled the 0-6800 to 0-188.68? Would it make sense just to leave the original units and do a direct conversion from sdk units to radians via 2/6800 and 6800/2 here instead?

Please feel free to ignore this if you have already wrestled it to the ground.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5SeTudX5TJ5p46QqW:-Kx5SeTudX5TJ5p46QqX:bq8cyyf) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L3)):*
> ```objc
> #pragma once
> 
> /// @file This file contains classes dealing with sending/receiving
> ```

BTW `/// @file` should be its own line -- anything following `@file` is treated as the file name being documented (with the default being the containing file).

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5VTjUE4hxrL35KNsI:-Kx5VTjUE4hxrL35KNsJ:biyd545) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L29)):*
> ```objc
> constexpr int kJacoDefaultArmNumFingers = 3;
> 
> extern const double kJacoLcmStatusPeriod;
> ```

BTW could this be a constexpr like the previous two?

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5Wq2xaLR9JyVv22L_:-Kx5Wq2xaLR9JyVv22La:b-pmm4kb) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L42)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(JacoCommandReceiver)
> 
>   explicit JacoCommandReceiver(int num_joints = kJacoDefaultArmNumJoints,
> ```

BTW needs a brief doxygen comment explaining the parameters.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5XBcdOsSofQak8FhW:-Kx5XBce2d606InSFooy:b-pmm4kb) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L85)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(JacoCommandSender)
> 
>   explicit JacoCommandSender(int num_joints = kJacoDefaultArmNumJoints,
> ```

BTW needs a brief doxygen comment explaining the parameters.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5XnIyvK3Vo4XFGxuy:-Kx5XnIyvK3Vo4XFGxuz:b6uu5xd) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L110)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(JacoStatusReceiver)
> 
>   explicit JacoStatusReceiver(int num_joints = kJacoDefaultArmNumJoints,
> ```

BTW needs doxygen

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5XrYYqtRKh_bbcts5:-Kx5XrYYqtRKh_bbcts6:b6uu5xd) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L141)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(JacoStatusSender)
> 
>   explicit JacoStatusSender(int num_joints = kJacoDefaultArmNumJoints,
> ```

BTW needs doxygen

---

*[drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5a9Bjrzq6tiMdTKN9:-Kx5a9Bjrzq6tiMdTKNA:b-ys2drw) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc#L70)):*
> ```cpp
> }
> 
> GTEST_TEST(JacoLcmTest, JacoStatusPassthroughTest) {
> ```

BTW a short comment here explaining what this test is doing would be helpful.

---

*[drake/lcmtypes/lcmt_jaco_command.lcm, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5SUBZ6lU2vf56iCIm:-Kx5SUBZ6lU2vf56iCIn:b-z0z9ul) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/lcmtypes/lcmt_jaco_command.lcm#L4)):*
> ```
> 
> // Commands a single set of joint states for the arm.  All angular
> // positions/velocities are expressed in radians.
> ```

BTW ... radians *and radians/second* (assuming that's right). Worth mentioning especially since the first mentioned time unit below is microseconds. 

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5S7KWHBzpGBW7D7ya:-Kx5S7KWHBzpGBW7D7yb:b-z0z9ul) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/lcmtypes/lcmt_jaco_status.lcm#L4)):*
> ```
> 
> // The current status of a Kinova Jaco arm.  All angular
> // positions/velocites are expressed in radians.
> ```

BTW ... radians *and radians/second* (assuming that's right). Worth mentioning especially since the first mentioned time unit below is microseconds. 

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5Rrw0xJoWhwjnFfNW:-Kx5Rrw0xJoWhwjnFfNX:b-i5wy2x) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/lcmtypes/lcmt_jaco_status.lcm#L7)):*
> ```
> struct lcmt_jaco_status
> {
>   // The timestamp in microseconds.
> ```

BTW can you say what the origin of this time stamp is (i.e., microseconds from when)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-Kx5aSTHAWFwQVGUbgp9:b-xn3a5m)*

**Comment by sammy-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5YNCLiHXzJ1sHrxWW:-Kx8lDl4QF64_at4aQcP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.cc#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW hard to believe those are actually degrees. Consider instead something like "position values range from 0-6800 units, which we have to map to the 0-2 radian finger joint range". But apparently someone has already scaled the 0-6800 to 0-188.68? Would it make sense just to leave the original units and do a direct conversion from sdk units to radians via 2/6800 and 6800/2 here instead?

Please feel free to ignore this if you have already wrestled it to the ground.
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5SeTudX5TJ5p46QqW:-Kx8lJ2TteVjnvLhua3u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `/// @file` should be its own line -- anything following `@file` is treated as the file name being documented (with the default being the containing file).
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5VTjUE4hxrL35KNsI:-Kx8mKInpA5SMG49qFs7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could this be a constexpr like the previous two?
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5Wq2xaLR9JyVv22L_:-Kx8o4RlF9jd29qrTI65:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW needs a brief doxygen comment explaining the parameters.
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5XBcdOsSofQak8FhW:-Kx8o5G4zYDWD7Q5eF17:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L85)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW needs a brief doxygen comment explaining the parameters.
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5XnIyvK3Vo4XFGxuy:-Kx8o5kUR8pF8wLgCWtc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L110)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW needs doxygen
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_lcm.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5XrYYqtRKh_bbcts5:-Kx8o6doQMGuEKWMs0KB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/jaco_lcm.h#L141)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW needs doxygen
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5a9Bjrzq6tiMdTKN9:-Kx8oDnQZFnF4O2ujW4C:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/examples/kinova_jaco_arm/test/jaco_lcm_test.cc#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW a short comment here explaining what this test is doing would be helpful.
</blockquote></details>

Done.

---

*[drake/lcmtypes/lcmt_jaco_command.lcm, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5SUBZ6lU2vf56iCIm:-Kx8oZxlEV02_xGClqFl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/lcmtypes/lcmt_jaco_command.lcm#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW ... radians *and radians/second* (assuming that's right). Worth mentioning especially since the first mentioned time unit below is microseconds. 
</blockquote></details>

Done.

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-KwpTkM28MirIUYwJGS7:-Kx8qAJOQbK3kGc36FzJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a66de9c6953ead098a50e396df08d5268a9072c9/drake/lcmtypes/lcmt_jaco_status.lcm#L20)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

"angular force" just sounds odd. I quickly checked with the dynamics folks and got the same reaction. "torque" seems clearer.
</blockquote></details>

Done.

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5S7KWHBzpGBW7D7ya:-Kx8qDSHe6_vps7bKwZy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/lcmtypes/lcmt_jaco_status.lcm#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW ... radians *and radians/second* (assuming that's right). Worth mentioning especially since the first mentioned time unit below is microseconds. 
</blockquote></details>

Done.

---

*[drake/lcmtypes/lcmt_jaco_status.lcm, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-Kx5Rrw0xJoWhwjnFfNW:-Kx8pHa71ryODlgbczCt:bqbual4) ([raw file](https://github.com/robotlocomotion/drake/blob/38ad3c3a393c5504636d133ea18e38e040415491/drake/lcmtypes/lcmt_jaco_status.lcm#L7)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can you say what the origin of this time stamp is (i.e., microseconds from when)?
</blockquote></details>

Done.  (some git grep work across various lcmtypes directories indicates that this has possibly never been documented before)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267)*

**Comment by sherm1** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7267#-:-Kx97XI6dJbGymFQ344p:b-d7d91y)*

**Pull request merged**
