### PR TITLE
[planning and control] Fix typo in documentation of LinearQuadraticRegulator

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Doc typo of a parameter name.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17751)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@hongkai-dai for feature review, please.

CC: @allenzren 

+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17751#-:-N9n2deg8RCqgN68MNHQ:b-ylg5uo)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17751#-:-N9tadev9WSPPwts-4ZW:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by DamrongGuoy — COMMENTED** [review]
+@seancurtis-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17751#-:-NA53bAM1AhNUbVKErAG:btfqah9)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17751#-:-NA56d5m6LSdzTfz16mk:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @hongkai-dai)

**Pull request merged**
