### PR TITLE
Add Bazel support for Gurobi on OS X

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5518)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by RussTedrake** [comment]
Saw the "do not review" label, but I'm eager for this so I just took it for a spin.  At first, I tried without setting GUROBI_PATH, and unfortunately did not get a helpful message:
```
ERROR: /Users/russt/drake-distro/drake/solvers/BUILD:215:1: no such package '@gurobi//': attribute error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /private/var/tmp/_bazel_russt/3e477aa1673e9c80e91d410bb65d1970/external/gurobi/gurobi-distro/lib/libgurobi60.so (No such file or directory)
: Could NOT change shared library identification name and referenced by '//drake/solvers:gurobi_solver'.
ERROR: Analysis of target '//drake/solvers:linear_complementary_problem_test_dsym' failed; build aborted.
```

Also, I think that this PR will also need to update the instructions in `drake/doc/bazel.rst`.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-clang-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot  mac-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
+@jamiesnape and +@david-german-tri this is ready for review!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5518#-:-KhbWwEo5EEPryc3mCbb:b-o9ytqf)*

**Comment by david-german-tri** [comment]
Looks reasonable to me.  Local test in progress.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5518#-:-Khc__aSaeI4FqVZ9irU:b-y7aiw3)*

**Comment by david-german-tri** [comment]
success!  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5518#-:-KhcjSGmKzQhFybPRPKI:bj9n95b)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5518#-:-Khcje_o0bT3TgdW19MO:bnfp4nl)*

**Pull request merged**
