### PR TITLE
Remove ROS from within Drake

### LINKED ISSUE #3418: ROS CI Servers not reporting to Drake-ROS CDash
Reported in #3409 the ROS CI have not been successfully updating to CDASH.

Some testing has narrowed it down to this change in the CI scripts: https://github.com/RobotLocomotion/drake-ci/commit/c1e545a455241d6df60621fc22abcd0ef099cf83

### LINKED ISSUE #3429: ROS CI Unable to Log and Test Results Directories Due to Insufficient Permissions
# Problem Definition

The error below was taken from: https://drake-jenkins.csail.mit.edu/job/linux-clang-experimental-ros/62/console

```
10:41:51 2: WARNING: cannot create log directory [/home/ubuntu/workspace/linux-clang-experimental-ros/log]. Please set ROS_LOG_DIR to a writable location.
10:41:52 2: Traceback (most recent call last):
10:41:52 2:   File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
10:41:52 2:     rostestmain()
10:41:52 2:   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
10:41:52 2:     _main()
10:41:52 2:   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
10:41:52 2:     results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
10:41:52 2:   File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
10:41:52 2:     raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
10:41:52 2: IOError: cannot create test results directory [/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test]. Please check permissions.
```

The following error was taken from: https://drake-cdash.csail.mit.edu/testDetails.php?test=2652303&build=109867

```
WARNING: cannot create log directory [/home/ubuntu/workspace/linux-clang-experimental-ros/log]. Please set ROS_LOG_DIR to a writable location.
Traceback (most recent call last):
  File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
IOError: cannot create test results directory [/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test]. Please check permissions.
Cannot find results, writing failure results to '/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test/MISSING-rostest-test_simulation_abort_function_test.xml'
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ubuntu/workspace/linux-clang-experimental-ros/src/drake_ros_integration/drake_ros_common_test --package=drake_ros_common_test --results-filename test_simulation_abort_function_test.xml --results-base-dir "/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results" /home/ubuntu/workspace/linux-clang-experimental-ros/src/drake_ros_integration/drake_ros_common_test/test/simulation_abort_function_test.test 
-- run_tests.py: verify result "/home/ubuntu/workspace/linux-clang-experimental-ros/build/drake_ros_common_test/test_results/drake_ros_common_test/rostest-test_simulation_abort_function_test.xml"

```
# Question

Should environment variable `ROS_LOG_DIR` be set to a different location?

### LINKED ISSUE #4711: Need to Restrict Drake Build To Use Super-build Versions of Octomap and FCL
# Problem Definition

When building Drake using ROS Indigo's `catkin`, the build will fail if ROS packages `ros-indigo-fcl` and `ros-indigo-octomap` are installed. Here is the error, which was first reported in #3814:

```
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/src/narrowphase/continuous_collision.cpp:38:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/continuous_collision-inl.h:47:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision.h:68:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision-inl.h:43:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix.h:86:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix-inl.h:73:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/traversal/octree/collision/mesh_octree_collision_traversal_node.h:46:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree.h:48:
In file included from /opt/ros/indigo/include/octomap/octomap.h:37:
In file included from /opt/ros/indigo/include/octomap/OcTree.h:38:
In file included from /opt/ros/indigo/include/octomap/OccupancyOcTreeBase.h:44:
/opt/ros/indigo/include/octomap/OcTreeBaseImpl.h:262:11: warning: class member cannot be redeclared [-Wredeclared-class-member]
    class leaf_iterator;
          ^
/opt/ros/indigo/include/octomap/OcTreeIterator.hxx:260:11: note: previous declaration is here
    class leaf_iterator : public iterator_base {
          ^
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/src/narrowphase/continuous_collision.cpp:38:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/continuous_collision-inl.h:47:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision.h:68:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision-inl.h:43:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix.h:86:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix-inl.h:73:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/traversal/octree/collision/mesh_octree_collision_traversal_node.h:46:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree.h:48:
In file included from /opt/ros/indigo/include/octomap/octomap.h:37:
In file included from /opt/ros/indigo/include/octomap/OcTree.h:38:
In file included from /opt/ros/indigo/include/octomap/OccupancyOcTreeBase.h:44:
/opt/ros/indigo/include/octomap/OcTreeBaseImpl.h:263:11: warning: class member cannot be redeclared [-Wredeclared-class-member]
    class tree_iterator;
          ^
/opt/ros/indigo/include/octomap/OcTreeIterator.hxx:206:11: note: previous declaration is here
    class tree_iterator : public iterator_base {
          ^
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/src/narrowphase/continuous_collision.cpp:38:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/continuous_collision-inl.h:47:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision.h:68:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision-inl.h:43:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix.h:86:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix-inl.h:73:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/traversal/octree/collision/mesh_octree_collision_traversal_node.h:46:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree.h:48:
In file included from /opt/ros/indigo/include/octomap/octomap.h:37:
In file included from /opt/ros/indigo/include/octomap/OcTree.h:38:
In file included from /opt/ros/indigo/include/octomap/OccupancyOcTreeBase.h:44:
/opt/ros/indigo/include/octomap/OcTreeBaseImpl.h:264:11: warning: class member cannot be redeclared [-Wredeclared-class-member]
    class leaf_bbx_iterator;
          ^
/opt/ros/indigo/include/octomap/OcTreeIterator.hxx:331:11: note: previous declaration is here
    class leaf_bbx_iterator : public iterator_base {
          ^
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/src/narrowphase/continuous_collision.cpp:38:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/continuous_collision-inl.h:47:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision.h:68:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/collision-inl.h:43:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix.h:86:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/collision_func_matrix-inl.h:73:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/narrowphase/detail/traversal/octree/collision/mesh_octree_collision_traversal_node.h:46:
In file included from /home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree.h:145:
/home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree-inl.h:179:16: error: no member named 'getNodeChild' in 'octomap::OcTree'
  return tree->getNodeChild(node, childIdx);
         ~~~~  ^
/home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree-inl.h:191:16: error: no member named 'getNodeChild' in 'octomap::OcTree'
  return tree->getNodeChild(node, childIdx);
         ~~~~  ^
/home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree-inl.h:203:16: error: no member named 'nodeChildExists' in 'octomap::OcTree'
  return tree->nodeChildExists(node, childIdx);
         ~~~~  ^
/home/liang/dev/drake_catkin_workspace/src/drake/externals/fcl/include/fcl/geometry/octree/octree-inl.h:214:16: error: no member named 'nodeHasChildren' in 'octomap::OcTree'
  return tree->nodeHasChildren(node);
         ~~~~  ^
3 warnings and 4 errors generated.
```

The problem appears to be that Drake's build system is finding ROS Indigo's version of `octomap`, which is located in `/opt/ros/indigo/include/octomap/` instead of its own version of octomap, which is located in `drake_catkin-workspace/install/share/octomap/`.

In #4709, the installation instructions were updated to remove `ros-indigo-fcl` and `ros-indigo-octomap`, to force Drake to use its own versions of these two libraries. This is sub-optimal since many other ROS packages like MoveIt! depend on these two packages. To allow both to co-exist, we should modify Drake's build system to prioritize its versions of FCL and Octomap over ROS Indigo's versions.

# Possible Course Of Action

@jamiesnape mentions that the solution will be something like adding the following to Drake's `CMakeLists.txt#:224`:

```
-Dfcl_DIR:PATH=${CMAKE_INSTALL_PREFIX}/lib/cmake/fcl
```

### LINKED ISSUE #5579: Installation issue with ros_common_test: undefined reference to testing::internal::EqFailure(..)
I am currently trying to install drake on my PC following the instructions on [http://drake.mit.edu/from_source.html](url) trying to build it as a ROS catkin Package. My PC runs Ubuntu 14.04 and has ROS Indigo installed. 

"catkin build" gives me the following error:

> Errors     << drake_ros_common_test:make /home/user/drake_catkin_workspace/logs/drake_ros_common_test/build.make.001.log           
CMakeFiles/parameter_server_test.dir/test/parameter_server_test.cc.o: In function CmpHelperEQFailure<bool, bool>':
/home/user/drake_catkin_workspace/install/include/gtest/gtest.h:1382: undefined reference to testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
CMakeFiles/parameter_server_test.dir/test/parameter_server_test.cc.o: In function __static_initialization_and_destruction_0':

and:

> Errors drake_ros_systems:make /home/user/drake_catkin_workspace/logs/drake_ros_systems/build.make.001.log                                                                                                                      
CMakeFiles/ros_test.dir/test/ros_test.cc.o: In function __static_initialization_and_destruction_0:
/home/user/drake_catkin_workspace/src/drake_ros_integration/drake_ros_systems/test/ros_test.cc:10: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
collect2: error: ld returned 1 exit status

Here is a screenshot of the same issue:

drakeissue

These are other details that relate to my computer environment:
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release: 14.04
Codename: trusty

MATLAB 9.0.0.341360 (R2016a)
ROS: Indigo
CMake: 3.7.2

gcc: 4.9.4
g++: 4.9.4
gfortran: 4.9.4

Thanks in advance for your help.

### LINKED ISSUE #6674: Emancipate ROS from inside Drake
The long term goal over the next two quarters is to shift the ROS development on top of Drake over into the arena of developers who are better equipped with the use cases, interest and skills to do so. In light of that, we're hoping to provide Drake as an installable c++/python package on Xenial/MacOSX with minimal dependency constraints. This will enable ROS/Catkin developers to use Drake as a regular c++ library in their normal development workflow and flexibly satisfy their own use case requirements.

The proposal here is to drop the current [drake/ros](https://github.com/RobotLocomotion/drake/tree/master/ros) folder. This will avoid a lengthy CI support upgrade to cover it for Xenial/Kinetic (right now it's only on Trusty) and CMake->Bazel shift (quite likely impossible and thus requiring some modified custom build recipe still).

**Are there any current users right now?** If you know of any, please reach out to them or respond for them in kind here (and what platform is being used). If we have to, we'll find a workaround that will satisfy needs until the slightly longer term build and release engineering is finished.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #3418, closes #3429, closes #4711, closes #5579, and closes #6674.

Relates in part to #5012.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6783)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@stonier for feature review.

**Comment by stonier** [comment]
Need to also remove in the docs:

* `index.rst` :  ` and preliminary ROS support`
* `code_style_guide.rst` : the section on `package.xml`

If those are done, :lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6783#-:-Kr_hBPqAca8tY1mhLz9:b-kzc5q8)*

**Comment by jwnimmer-tri** [comment]
The style guide section needs to stay in place, at least in part.  It reads:
> Note that ``package.xml`` files are necessary even if you're *not* using Drake
with ROS because the model files used by Drake (e.g., URDF and SDF), frequently
refer to resources like mesh files via a ``package://`` syntax, whose full paths
are resolved by the ``package.xml`` files.

.. and we'll continue to use `package.xml` to find resources for the foreseeable future, with or without ROS.

**Comment by stonier** [comment]
Ach, thanks for catching. Awkward setup.

**Comment by jamiesnape** [comment]
`and preliminary ROS support` has been removed.

---

Review status: 0 of 35 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6783#-:-Kra6PSkLVZSrz_zf7iR:bbjlsrp)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@sammy-tri for final platform review

---

Reviewed 34 of 34 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6783#-:-KraIq8WLxJNV_k-UeZc:b-fwnpmf)*

**Comment by sammy-tri** [comment]
Didn't actually look at the diffs of the deleted files in `ros/`  :lgtm: based on the rest

---

Reviewed 10 of 34 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6783#-:-KrbHsofVA1Cbu9B-mlq:b-8kg2cw)*

**Pull request merged**
