### PR TITLE
bazel: Current fixes for --all_incompatible_changes

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #10154

\cc @jwnimmer-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10463)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
The following runs passed on my machine:
```
bazel test --all_incompatible_changes //...
bazel test --config=everything --all_incompatible_changes //...
```

**Comment by jamiesnape** [comment]
We should probably set up an advisory job in CI soon since I think this is the first time in living memory we have a clean `--all_incompatible_changes`...

**Comment by EricCousineau-TRI** [comment]
I'd be fine with that, but perhaps we should focus that discussion in a separate issue / Slack? Would you be up for starting that discussion?

**Comment by jamiesnape** [comment]
> I'd be fine with that, but perhaps we should focus that discussion in a separate issue / Slack? Would you be up for starting that discussion?

Definitely a separate issue.

**Pull request merged**
