### PR TITLE
Add an output for density in LinearTransformDensity.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189#-:-McBjvIc8cWxd4zSa6LZ:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189#-:-McBsKKf6y0BOID8IHP7:b-n37teh)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[systems/primitives/test/linear_transform_density_test.cc, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15189#-McBs-G31pVhI6EOjKLF:-McBs-G452xEQFVNqE1U:b-ewa385) ([raw file](https://github.com/robotlocomotion/drake/blob/b66aab7fd86645054deac7715ffbccc684ab51bc/systems/primitives/test/linear_transform_density_test.cc#L115)):*
> ```cpp
>   dut.get_input_port_w_in().FixValue(context.get(), w_in);
> 
>   // Test when port b is not connected.
> ```

nit Since the port's Calc implementation is a single line with no branching, it would be fine to condense this unit test down to a single case (either with a `b`, or without one).  The unit test for the direct function call already covers the branching.

Fine either way.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/primitives/test/linear_transform_density_test.cc, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15189#-McBs-G31pVhI6EOjKLF:-McD-cna3SMCMNBuUrv8:b-wwh0u2) ([raw file](https://github.com/robotlocomotion/drake/blob/b66aab7fd86645054deac7715ffbccc684ab51bc/systems/primitives/test/linear_transform_density_test.cc#L115)):*
> The unit test for the direct function call already covers the branching.

Would that imply we know the underlying implementation is just call `CalcDensity` function? I would think testing both with and without connecting `b` is more robust than testing one case?

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189#-:-McD03G2C5pei00R2kDa:b8asji7)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[systems/primitives/test/linear_transform_density_test.cc, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15189#-McBs-G31pVhI6EOjKLF:-McEnicY34fpvF83eU0U:b-8ne3yy) ([raw file](https://github.com/robotlocomotion/drake/blob/b66aab7fd86645054deac7715ffbccc684ab51bc/systems/primitives/test/linear_transform_density_test.cc#L115)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> The unit test for the direct function call already covers the branching.

Would that imply we know the underlying implementation is just call `CalcDensity` function? I would think testing both with and without connecting `b` is more robust than testing one case?
</blockquote></details>

There is the idea of "glass box" testing.  See [Glass-box Testing](https://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/testing/glassbox.html), and for context the page before it [Black-box Testing](https://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/testing/blackbox.html).

In a unit test, it's a valid tactic to assume that the branching paths / boundary cases exist as currently implemented, and that if a future developer adds more paths, then they will also realize that they might need to adjust the tests and do so accordingly.

Of course, it's a matter of judgement to trade off the future risk of bugs not being caught vs the present cost of test verbosity to maintain.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189#-:-McG-c_B--4wNbFLc_mX:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15189)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[systems/primitives/test/linear_transform_density_test.cc, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15189#-McBs-G31pVhI6EOjKLF:-McGPk8BEf0XmnwWUzJt:bm89jvo) ([raw file](https://github.com/robotlocomotion/drake/blob/b66aab7fd86645054deac7715ffbccc684ab51bc/systems/primitives/test/linear_transform_density_test.cc#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is the idea of "glass box" testing.  See [Glass-box Testing](https://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/testing/glassbox.html), and for context the page before it [Black-box Testing](https://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/testing/blackbox.html).

In a unit test, it's a valid tactic to assume that the branching paths / boundary cases exist as currently implemented, and that if a future developer adds more paths, then they will also realize that they might need to adjust the tests and do so accordingly.

Of course, it's a matter of judgement to trade off the future risk of bugs not being caught vs the present cost of test verbosity to maintain.
</blockquote></details>

@hongkai-dai I think you can just merge this if you mark yourself satisfied in this discussion.

**Comment by rpoyner-tri** [comment]
___
*[systems/primitives/test/linear_transform_density_test.cc, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15189#-McBs-G31pVhI6EOjKLF:-McGQ0Hn25P-liS7HlMR:bcq8975) ([raw file](https://github.com/robotlocomotion/drake/blob/b66aab7fd86645054deac7715ffbccc684ab51bc/systems/primitives/test/linear_transform_density_test.cc#L115)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@hongkai-dai I think you can just merge this if you mark yourself satisfied in this discussion.
</blockquote></details>

Hm, reviewable surprised me -- my Satisfied state cleared this, so I merged.

**Pull request merged**
