### PR TITLE
Collect our own list of transitive headers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

Use our own list instead of the built-in `cc` provider so that we can adjust and filter what is going to be installed, versus everything that is required to compile.  This lets us move the current yaml and vtk exclusions to their point of declaration.

This mechanism will also become important for #6996, where we have to be very careful about include paths while compiling pydrake `*.so`s.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7458)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@EricCousineau-TRI for feature and platform review per schedule, please.

**Comment by jamiesnape** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/skylark/drake_cc.bzl, line 247 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-KypbO6Q6C4u397x70CN:-KypbO6Q6C4u397x70CO:b-9ghr2x) ([raw file](https://github.com/robotlocomotion/drake/blob/9d66e9cd805e610052c6ac1e3141ed01cddd5152/tools/skylark/drake_cc.bzl#L247)):*
> ```Python
>     drake_installed_headers(
>         name = name + ".installed_headers",
>         hdrs = hdrs + private_hdrs,
> ```

So this causes private headers to be installed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-:-KyplNDEwK4As9YjLfHf:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
First pass done with a minor design question. PTAL when you have a chance. Thanks!

---

Reviewed 3 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq7NfpRzBwZkLKb7Hp:-Kyq7NfqpAyWuIQeDmoV:bltmxu) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L133)):*
> ```Python
>     if type(deps) == "select":
>         # We can't handle select() yet.
>         return []
> ```

BTW Can we print a warning or throw an error here?
Or is this presently being used, and ignored?

---

*[tools/skylark/drake_cc.bzl, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq8bsciT4i7bw-j47h:-Kyq8bsdPzUlL0y0cPxL:brquwwi) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L255)):*
> ```Python
>         hdrs = hdrs + private_hdrs,
>         hdrs_exclude = install_hdrs_exclude,
>         deps = installed_headers_for_drake_deps(deps),
> ```

Sorry, my custom-provider foo is a bit behind - does this mean that `drake_cc_library` can only consume `deps` of type `DrakeCc`?

What happens if a user includes a `native.cc_library` in `deps` that does not have its corresponding installed-headers rule?

(If this does not work, is there a way to get `native.existing_rule` to work for inter-package rules, not just intra-package rules, possibly before the native extensibility feature comes into play?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-:-KyqBX2dtSg3m07jvxXj:bsogpij)*

**Comment by jwnimmer-tri** [comment]
*[tools/skylark/drake_cc.bzl, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq8bsciT4i7bw-j47h:-KyqDbB1BApJBTP807AN:brd5nwz) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L255)):*
> Sorry, my custom-provider foo is a bit behind - does this mean that drake_cc_library can only consume deps of type DrakeCc?

What this means is that the `deps` of a `drake_cc_library` must either (1) be another `drake_cc_library`, or (2) must be named `@something//etc` and not `//etc`.  (This is what the "filter" part of `installed_headers_for_drake_deps` is for.)

Note that a future PR #7462 also makes an exemption in this rule for Drake's lcmtypes, since lcmtypes are bespokely weird.

> What happens if a user includes a native.cc_library in deps that does not have its corresponding installed-headers rule?

If the native.cc_library label were within Drake, Bazel would report a loading-phase error.  If the label were from an external, it would be OK.

> (If this does not work, is there a way to get native.existing_rule to work for inter-package rules, not just intra-package rules, possibly before the native extensibility feature comes into play?)

I wasn't able to understand what you mean here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458)*

**Comment by jwnimmer-tri** [comment]
*[tools/skylark/drake_cc.bzl, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq7NfpRzBwZkLKb7Hp:-KyqFRHac_ZgANvJlYDD:b-axo3vf) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L133)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can we print a warning or throw an error here?
Or is this presently being used, and ignored?
</blockquote></details>

OK Using `select()` on sources is used ~10 times in the code, mostly in `//drake/solvers` were we use `foo_solver.cc` vs `no_foo.cc`.  I think to get a useful interlock here, we'd need to add `srcs_select_noheaders` arg to drake_cc_library, and change solvers (etc.) to use that.  My intuition is to leave it alone, but if you prefer, I am happy to try that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458)*

**Comment by EricCousineau-TRI** [comment]
Just a few more questions comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 251 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-KyqIigJzi2ZkmRNFN5B:-KyqIigKleVdO5MpwNQ9:b-vf1wrw) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L251)):*
> ```Python
>     # its cc_library, but we also need to install all of its child headers that
>     # it includes, such as common/symbolic_expression.h.
>     drake_installed_headers(
> ```

BTW Could this be changed to ignore this code path if this is a `testonly` library?

Or should there be a `no_install` parameter which skips this logic (e.g. when a developer is testing something on their machine, not to be installed)?

---

*[tools/skylark/drake_cc.bzl, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq8bsciT4i7bw-j47h:-KyqI-fPULSDjUExEnLL:bp861lb) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L255)):*
> If the native.cc_library label were within Drake, Bazel would report a loading-phase error. If the label were from an external, it would be OK.

Gotcha, thanks for the explanation! Can this behavior be captured in the method documentation?

> I wasn't able to understand what you mean here.

Sorry, I meant that the filtering operation above could be augmented to check if a the installed-header target exists, and only include it if it does exist (or maybe throw a more informative error than some internally made target name).
I had tried this in a toy project a week ago, and you can do this with `native.existing_rule` for intra-package rules, but not for inter-package targets...

At a minimum, documentation stating that only `drake_cc_library` rules, or external libraries, can be `deps` of `drake_cc_library` (at least a non-test, to-be-installed library) would be helpful.
Additionally, maybe a mention of how to declare `drake_installed_headers` for users who may need to include a non-`drake_cc_library` target? (If this is incorporated, could `drake_installed_headers` be changed to have `lib_name`, and append the suffix automatically, rather than having it specified manually?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-:-KyqJadbRYTC0U9YdVpo:b-ulp83y)*

**Comment by jwnimmer-tri** [comment]
FYI I've reconfirmed locally that the list of installed files is unchanged from this PR vs master.

---

Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 251 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-KyqIigJzi2ZkmRNFN5B:-KyqMemgwUpwns3eR1Ug:bax9vt0) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L251)):*

> Or should there be a no_install parameter which skips this logic (e.g. when a developer is testing something on their machine, not to be installed)?

There is `install_hdrs_exclude` to blacklist certain headers.  I'm not sure what use case that doesn't cover?  Merely creating the provider doesn't install anything; the label has to be referenced from some install rule in order for anything to actually get copied into the install tree.

> Could this be changed to ignore this code path if this is a testonly library?

I don't think in general we should forbid `test_utility` code from being installed, even though we don't do it yet.  It might come in handy for Drake-using code to have some test stubs or mocks available in the same way that Drake does.  What's the thought process behind this request?

---

*[tools/skylark/drake_cc.bzl, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq8bsciT4i7bw-j47h:-KyqLjpx1trPF6p42afo:b2m05q8) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L255)):*
> At a minimum, documentation stating that only drake_cc_library rules, or external libraries, can be deps of drake_cc_library (at least a non-test, to-be-installed library) would be helpful.
> ...
>  Can this behavior be captured in the method documentation?

Good point.  Done.

> Sorry, I meant that the filtering operation above could be augmented to check if a the installed-header target exists, and only include it if it does exist ...

I don't see why we'd want this?  The drake_cc_library is what all code in Drake should use, and code outside of Drake should never use this macro.  Or at least, that's how I see it now.  If we come up with some different story, we could update the macro to become more flexible once we know what that is.

> Additionally, maybe a mention of how to declare drake_installed_headers for users who may need to include a non-drake_cc_library target? (If this is incorporated, could drake_installed_headers be changed to have lib_name, and append the suffix automatically, rather than having it specified manually?)

I don't see why "non-drake_cc_library target" would come up, and I would prefer not to make those label suffixes part of the build system API.  (I would not be surprised if their implementation evolved substantially over time.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-:-KyqOnP3q2ydu-23FAJp:b-fg7gua)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor remaining comments. Thanks!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/skylark/drake_cc.bzl, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq7NfpRzBwZkLKb7Hp:-KyqW7iobYXkf3-v-rUI:brm25jh) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L133)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Using `select()` on sources is used ~10 times in the code, mostly in `//drake/solvers` were we use `foo_solver.cc` vs `no_foo.cc`.  I think to get a useful interlock here, we'd need to add `srcs_select_noheaders` arg to drake_cc_library, and change solvers (etc.) to use that.  My intuition is to leave it alone, but if you prefer, I am happy to try that.
</blockquote></details>

I would prefer there be some sort of indication that behavior is not going to change according to `--config` options, but I'm fine with that being deferred to a later point.
Could this be promoted to a `TODO` in that case?

---

*[tools/skylark/drake_cc.bzl, line 251 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-KyqIigJzi2ZkmRNFN5B:-KyqVPY1RoE_Q8xiMzAj:b-59fzrb) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L251)):*
> There is install_hdrs_exclude to blacklist certain headers. I'm not sure what use case that doesn't cover?

It was related to the points below (e.g. if I make a non-Drake `cc_library` or what not and don't want to try and trudge through generating the correct glue / "butter" rules), but given that I have no concrete use cases / workflows that this needs, I'll go ahead and resolve my discussion.

>  It might come in handy for Drake-using code to have some test stubs or mocks available in the same way that Drake does. What's the thought process behind this request?

The thought process was that Bazel is for development and `install` is for deployment of production `drake`, but I realize that is relatively narrowly scoped; that's a good point!

---

*[tools/skylark/drake_cc.bzl, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq8bsciT4i7bw-j47h:-KyqVDJeMUoK6V3Ov954:b-y5euvc) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L255)):*
> Or at least, that's how I see it now. If we come up with some different story, we could update the macro to become more flexible once we know what that is.

OK That sounds good! (and much simpler)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-:-KyqXCeZBPtQIwEkWARV:b-rnv394)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-Kyq7NfpRzBwZkLKb7Hp:-KyqcduLn8zQenjMBI4_:b-aubslx) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L133)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I would prefer there be some sort of indication that behavior is not going to change according to `--config` options, but I'm fine with that being deferred to a later point.
Could this be promoted to a `TODO` in that case?
</blockquote></details>

Done (added TODO).  I actually don't think anything changes with config options -- if there is a select, we completely ignore all deps for purposes of header search, no matter what config is selected.

(I actually just had an idea about how to make selects work (everywhere in drake_cc.bzl), but I'll PR that separately.)

---

*[tools/skylark/drake_cc.bzl, line 251 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7458#-KyqIigJzi2ZkmRNFN5B:-Kyqa5LDVU7FWah3LOBo:bxeec4j) ([raw file](https://github.com/robotlocomotion/drake/blob/da095d7f425d15589c425a1bc5045ce198e15ce5/tools/skylark/drake_cc.bzl#L251)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

> There is install_hdrs_exclude to blacklist certain headers. I'm not sure what use case that doesn't cover?

It was related to the points below (e.g. if I make a non-Drake `cc_library` or what not and don't want to try and trudge through generating the correct glue / "butter" rules), but given that I have no concrete use cases / workflows that this needs, I'll go ahead and resolve my discussion.

>  It might come in handy for Drake-using code to have some test stubs or mocks available in the same way that Drake does. What's the thought process behind this request?

The thought process was that Bazel is for development and `install` is for deployment of production `drake`, but I realize that is relatively narrowly scoped; that's a good point!
</blockquote></details>

OK Probably another part of the picture here that would help to know is that with #6996, if you don't use `drake_cc_header` within Drake, then nothing at all will work ever, because of include paths.  So I'm not too worried about stray non-Drake `cc_library`s hanging around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7458)*

**Pull request merged**
