### PR TITLE
Add godotengine as an external

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This also has a dummy main program to demonstrate that the library builds, and has somewhat reasonable link flags.

This uses a slightly older commit that godot master (because master is broken for our platform).  We can PR fixes for that upstream and then bump to their master.

Do not merge until:
- [x] tested on macOS builds.
- [x] retested after rebased onto latest master.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7817)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

From a prior push, we have [build failure](https://drake-jenkins.csail.mit.edu/job/mac-sierra-clang-bazel-experimental/90/) on macOS, so I've disabled Godot on there for now.  We'll re-enable it in a separate PR (probably once we have a better Ubuntu example ready to prove its working correctly).

**Comment by jwnimmer-tri** [comment]
+@thduynguyen and +@SeanCurtis-TRI for all review, please.

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 13 files at r2.
Review status: 2 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/godot_renderer/dev/BUILD.bazel, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbDIl4omsSoOPqU1F:-L3nbDIl4omsSoOPqU1G:b-gfzl4n) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/BUILD.bazel#L15)):*
> ```Python
>     name = "maybe_godotengine",
>     deps = select({
>         "//conditions:default": ["@godotengine"],
> ```

FYI Slick

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7817)*

**Comment by SeanCurtis-TRI** [comment]
It builds like it should. But it doesn't segfault as advertised (see note below). Otherwise, :LGTM:

---

Reviewed 1 of 11 files at r1, 10 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[systems/sensors/godot_renderer/dev/dummy_ubuntu.cc, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbQkKrL48V1POjoey:-L3nbQkKrL48V1POjoez:b-itgggc) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/dummy_ubuntu.cc#L1)):*
> ```cpp
> #include <core/register_core_types.h>
> ```

BTW Is there no slick way to have these pre-pended with some kind of `godot` path?

---

*[systems/sensors/godot_renderer/dev/dummy_ubuntu.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbe6OfBKvUIplcdoL:-L3nbe6Ph2SKHHSkwZcf:b-16z6du) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/dummy_ubuntu.cc#L11)):*
> ```cpp
> // This is some small sample code that uses a few things from Godot, to show
> // that we can link without errors.  Once we have more real code using Godot,
> // we should remove this dummy program.  (Note that this program more or less
> ```

BTW Is this still true? It didn't segfault on my machine:

`bazel run systems/sensors/godot_renderer/dev:dummy`

---

*[tools/workspace/godotengine/package.BUILD.bazel, line 105 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nf10dMQPom-kbSd9X:-L3nf10dMQPom-kbSd9Y:b-d6032f) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/tools/workspace/godotengine/package.BUILD.bazel#L105)):*
> ```
> ]
> 
> # Compile a library with everything form Godot that we need.
> ```

BTW s/form/from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-:-L3nfDeMynJ4Co3UJD9A:b17w6o1)*

**Comment by jwnimmer-tri** [comment]
For the record, the most recent macOS build has passed: https://drake-jenkins.csail.mit.edu/job/mac-sierra-clang-bazel-experimental/91/

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/sensors/godot_renderer/dev/dummy_ubuntu.cc, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbQkKrL48V1POjoey:-L3nvN20-aE-pvRw4Qo4:b-6ata27) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/dummy_ubuntu.cc#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is there no slick way to have these pre-pended with some kind of `godot` path?
</blockquote></details>

The easy thing (`include_prefix`) doesn't work , because Godot is all over the place about how the internally spell their includes.  Some are fully-qualified, some assume that relative works, some are halfway inbetween.

We could fix that by adjusting the `package.BUILD.bazel` to have two lists of headers and includes (one for internal, one for Drake), but since we need to firewall godot into cc files here anyway, I figured this would be OK.  We can add some partition + comments in the groups of include statements if mixing vs system or other third_party headers starts to become confusing.

---

*[systems/sensors/godot_renderer/dev/dummy_ubuntu.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbe6OfBKvUIplcdoL:-L3nwCgyzqq_CjuEh_tW:b-qi2nlu) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/dummy_ubuntu.cc#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is this still true? It didn't segfault on my machine:

`bazel run systems/sensors/godot_renderer/dev:dummy`
</blockquote></details>

Maybe its faulting but not emitting a message?

```console
jwnimmer@call-cc:~/jwnimmer-tri/drake$ bazel run systems/sensors/godot_renderer/dev:dummy; echo $?
...
INFO: Running command line: bazel-bin/systems/sensors/godot_renderer/dev/dummy
8
jwnimmer@call-cc:~/jwnimmer-tri/drake$ bazel-bin/systems/sensors/godot_renderer/dev/dummy; echo $?
Segmentation fault (core dumped)
139
```
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/ExitCode.java#L47

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7817)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/godot_renderer/dev/dummy_ubuntu.cc, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbQkKrL48V1POjoey:-L3oCeBLx-3QGQG8YEbV:b-1w8hrh) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/dummy_ubuntu.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The easy thing (`include_prefix`) doesn't work , because Godot is all over the place about how the internally spell their includes.  Some are fully-qualified, some assume that relative works, some are halfway inbetween.

We could fix that by adjusting the `package.BUILD.bazel` to have two lists of headers and includes (one for internal, one for Drake), but since we need to firewall godot into cc files here anyway, I figured this would be OK.  We can add some partition + comments in the groups of include statements if mixing vs system or other third_party headers starts to become confusing.
</blockquote></details>

I like the idea of partition + comments (even if it's not 100% styleguide compliant). But the documentation would satisfy the spirit.

---

*[systems/sensors/godot_renderer/dev/dummy_ubuntu.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-L3nbe6OfBKvUIplcdoL:-L3oD3BqZSBB3cHtDjLT:b-mwdq0w) ([raw file](https://github.com/robotlocomotion/drake/blob/2951f680e8d5e00e213d173eb34cd6e6f98a6f59/systems/sensors/godot_renderer/dev/dummy_ubuntu.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe its faulting but not emitting a message?

```console
jwnimmer@call-cc:~/jwnimmer-tri/drake$ bazel run systems/sensors/godot_renderer/dev:dummy; echo $?
...
INFO: Running command line: bazel-bin/systems/sensors/godot_renderer/dev/dummy
8
jwnimmer@call-cc:~/jwnimmer-tri/drake$ bazel-bin/systems/sensors/godot_renderer/dev/dummy; echo $?
Segmentation fault (core dumped)
139
```
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/ExitCode.java#L47
</blockquote></details>

Ah...when I run it direct from `bazel-bin`, I get the seg fault. THanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7817)*

**Comment by jwnimmer-tri** [comment]
-@thduynguyen as reviewer (busy).  Per email with Sean, he will count as feature reviewer.  So +@EricCousineau-TRI as platform review per schedule, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1, 11 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7817#-:-L4c38qXpTbhe2pi49Kk:bnfp4nl)*

**Pull request merged**
