### PR TITLE
Adjust termination conditions for IRIS-NP on focal

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19844)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-release please.

**Comment by RussTedrake** [comment]
Attempt 2.

@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-release please.

**Comment by RussTedrake** [comment]
Attempt 4.

@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-release please.

**Comment by RussTedrake** [comment]
Attempt 5.

@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-release please.

**Review by svenevs — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.  There is a [slack discussion](https://drakedevelopers.slack.com/archives/C270MN28G/p1690287953296649) about what is going on here.  TL;DR: we could only get the test to pass on focal with `num_collision_infeasible_samples = 150` :scream_cat:  Russ would like to just skip this test, as buildcop I'm satisfied with these nice green check marks.  But it is not clear to me if this is the right decision (we are ideally avoiding a revert, but now this test does not run on _any_ platform).

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19844#-:-NaCPWY0Dx4JRDpMfZhv:bsojnyt)* status: LGTM missing from assignees svenevs,xuchenhan-tri(platform)

**Review by svenevs — COMMENTED** [review]
For reference #19835 is the original PR that had issues with nightlies last night.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19844#-:-NaCQTp35lj5_qpCoLOs:b-exvvez)* status: LGTM missing from assignees svenevs,xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19844#-:-NaCuDi-59z83bhuv9gI:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees svenevs,xuchenhan-tri(platform)

**Pull request merged**
