### PR TITLE
Repair typos.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
These were found with `codespell`:
    
 $ apt install codespell
 $ codespell -wi3
    
A few false positives (binary files, identifiers that look like words) were
skipped.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
I don't know why there are two commits here; that is clearly wrong. Investigating.
+(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063#-:-Ma9qaZg1wKGgidHDE95:bcyhx7u)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
Fixed -(status: do not review) 
+(status: single reviewer ok) 
+@sammy-tri for both reviews.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063#-:-Ma9tJGT5dBtxAl9TqJJ:b2rvhgt)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri)

___
*[third_party/com_github_finetjul_bender/vtkCapsuleSource.h, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15063#-MaAWSOP6Lymh2H7kF5k:-MaAWSOP6Lymh2H7kF5l:b-uq7zz0) ([raw file](https://github.com/robotlocomotion/drake/blob/90af8622fd0a4f67b4f1bc9d0e2543b55cb6dd20/third_party/com_github_finetjul_bender/vtkCapsuleSource.h#L73)):*
> ```objc
> 
>   // Description:
>   // Set the number of points used in the lattitude direction
> ```

I'm inclined to say we should probably leave `third_party` alone unless we have some particular reason to modify it.  Thoughs?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri)

___
*[third_party/com_github_finetjul_bender/vtkCapsuleSource.h, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15063#-MaAWSOP6Lymh2H7kF5k:-MaAX-RCE9xqu8YwHmMP:bfv3b4q) ([raw file](https://github.com/robotlocomotion/drake/blob/90af8622fd0a4f67b4f1bc9d0e2543b55cb6dd20/third_party/com_github_finetjul_bender/vtkCapsuleSource.h#L73)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm inclined to say we should probably leave `third_party` alone unless we have some particular reason to modify it.  Thoughs?
</blockquote></details>

Oops, good catch.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[third_party/com_github_finetjul_bender/vtkCapsuleSource.h, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15063#-MaAWSOP6Lymh2H7kF5k:-MaAXYTs7AFlqfTZMv_J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90af8622fd0a4f67b4f1bc9d0e2543b55cb6dd20/third_party/com_github_finetjul_bender/vtkCapsuleSource.h#L73)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Oops, good catch.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15063#-:-MaAx6n71sX0RfapdKhY:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
