### PR TITLE
Fixed the mesh message in BotVisualizer.

### PR DESCRIPTION
**Pull request by liangfok**
This was brought to my attention by +@maddog-tri.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3036)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review.
+@sammy-tri for platform review.

FYI @jwnimmer-tri since you reviewed #2260.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3036#-:-KOFHTquhq7RIcX5E7H6:1493361183)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3036#-:-KOFI2PLp-w5ZzK2cQrp:-1384038213)*

**Comment by liangfok** [comment]
-@sammy-tri for platform review
+@jwnimmer-tri for platform review (happy Wednesday)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3036#-:-KOFjaEVFH0s9p_zWCHJ:1916134940)*

**Comment by jwnimmer-tri** [comment]
I'm not sure that a 1-bit patch needs platform review, but happy to do it anyway.  :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3036#-:-KOFlRtYyyWr2tJSaDFd:1112630480)*

**Comment by maddog-tri** [comment]
Well... you missed this in the platform review of the original PR, so this was your chance to redeem yourself. (And, :LGTM:, with the caveat that my only knowledge of both the protocol and the expectations of the receiver comes from reading the names of the message fields.)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3036#-:-KOGGYgIecsDth7vy0vu:-164479910)*

**Pull request merged**
