### PR TITLE
Formally deprecate the AllocateOutput() signature that takes a Context

### PR DESCRIPTION
**Pull request by sherm1**
System::AllocateOutput(Context) has been ignoring the Context argument for a long time. This formally deprecates that signature and removes the argument from all the calls in Drake.

I also removed the Python binding for the deprecated signature rather than deprecating it; would be OK with deprecating that instead if that seems worth doing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051)

### CODE REVIEW

**Comment by sherm1** [comment]
@ericcousineau-tri for feature and platform per rotation -- lots of files but only tiny cosmetic changes.
Please let me know if you think I should deprecate the Python binding rather that deleting it as I've done. If so, please point me to an example if there is one.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFj5uiz9kBaWu7-2OW5:b-u8db0z)*

**Comment by sherm1** [comment]
Er, +@ericcousineau-tri for both reviews please, I meant.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFj6cY21Zxnl2Q0YhbP:b-1gdd5l)*

**Comment by EricCousineau-TRI** [comment]
First pass done, will submit a patch for Python stuff.

---

Reviewed 94 of 94 files at r1.
Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 281 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFswHTv3tAGG_Xr7Got:-LFswHTv3tAGG_Xr7Gou:bj1v0gr) ([raw file](https://github.com/robotlocomotion/drake/blob/1c74378318264d5e9587e87b8eb833e9cd905c44/bindings/pydrake/systems/framework_py_systems.cc#L281)):*
> ```cpp
>                  &System<T>::AllocateOutput))
>         // TODO(sherm1) Deprecate this next signature (context unused).
>         .def("AllocateOutput",
> ```

I'd prefer deprecation, but I'm not sure if I have an example. I will post a patch shortly of how to deprecate this in `pydrake`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFsx6gFEB1r8ynP2Qq6:blv1epy)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 281 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFswHTv3tAGG_Xr7Got:-LFsxjGy3_l6E31v7zKh:bk4zexg) ([raw file](https://github.com/robotlocomotion/drake/blob/1c74378318264d5e9587e87b8eb833e9cd905c44/bindings/pydrake/systems/framework_py_systems.cc#L281)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'd prefer deprecation, but I'm not sure if I have an example. I will post a patch shortly of how to deprecate this in `pydrake`.
</blockquote></details>

Hup, forgot that I had deprecated `constraint`, but it's a bit heavy. Will make a helper function and add it in:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/solvers/mathematicalprogram_py.cc#L87

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051)*

**Comment by jwnimmer-tri** [comment]
Another options is to have this PR leave the pydrake alone (undo that diff, such that the deprecated binding remains), and then let @EricCousineau-TRI PR the deprecation annotation addition to pydrake separately.

**Comment by sherm1** [comment]
That's very reasonable also -- do you want me to restore the AllocateOutput(context) binding in Python Eric? I think it would have to invoke the no-context signature though so that it doesn't produce a warning when compiled.

---

Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFsztSKBs8797ptY35M:bbjem9u)*

**Comment by jwnimmer-tri** [comment]
Yup.  Either that, or else its trivial to turn off the compiler warning (pragma push, Wno-deprecated, pop).

**Comment by jwnimmer-tri** [comment]
I can review it with due non-on-call priority, which means by EOD tomorrow if filed today.

**Comment by EricCousineau-TRI** [comment]
Review status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 281 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFswHTv3tAGG_Xr7Got:-LFt43YiCbZ_C5zs19Qn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c74378318264d5e9587e87b8eb833e9cd905c44/bindings/pydrake/systems/framework_py_systems.cc#L281)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hup, forgot that I had deprecated `constraint`, but it's a bit heavy. Will make a helper function and add it in:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/solvers/mathematicalprogram_py.cc#L87
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051)*

**Comment by jwnimmer-tri** [comment]
The "Author:" metadata on the second commit is wrong now.

**Comment by sherm1** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 286 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFt5EoJ4jUUF03_789n:-LFt5EoJ4jUUF03_789o:buld23q) ([raw file](https://github.com/robotlocomotion/drake/blob/7eaa491a94805b810443603ee64974c8e9498960/bindings/pydrake/systems/framework_py_systems.cc#L286)):*
> ```cpp
>                WarnDeprecated(
>                   "`System.AllocateOutput(self, Context)` is deprecated. "
>                   "Please use `System.AllocateOutput(self) instead.");
> ```

Nit: missing backtick on second line (attn: @ericcousineau-tri)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051)*

**Comment by EricCousineau-TRI** [comment]
Fixed authorship.
+@jwnimmer-tri for review on `deprecation_pybind` and related changes.

---

Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFt5oCm2NktZZIha94F:b-y3swoq)*

**Comment by EricCousineau-TRI** [comment]
Review status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[bindings/pydrake/systems/framework_py_systems.cc, line 286 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFt5EoJ4jUUF03_789n:-LFt6Y3x0GUuw_HCv9KR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46ef1efb066f1b4902cb8d1a39b7047bbf3d0e63/bindings/pydrake/systems/framework_py_systems.cc#L286)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Nit: missing backtick on second line (attn: @ericcousineau-tri)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051)*

**Comment by jwnimmer-tri** [comment]
I've reviewed the `pydrake/**` changes.

Jenkins is reporting unit test failures.

---

Reviewed 4 of 8 files at r2, 1 of 96 files at r3, 9 of 95 files at r4.
Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[bindings/pydrake/util/deprecation.py, line 95 at r4](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFw2VDh6oJZ2whwRZMv:-LFw2VDh6oJZ2whwRZMw:bljkgmh) ([raw file](https://github.com/robotlocomotion/drake/blob/a2c9058f83d87bba0549f734278f5a94edbc7d15/bindings/pydrake/util/deprecation.py#L95)):*
> ```Python
> 
> def _warn_deprecated(message, stacklevel=2):
>     # Consolidate call so that C++ has an easy point to call this.
> ```

The comment makes sense when viewed within the patches of this PR, but would be confusing when browsing this code post-merge.  Maybe something like this?
```python
# Logs a deprecation warning message.  Also used by deprecation_pybind.h
in addition to this file.
```

---

*[bindings/pydrake/util/deprecation_pybind.h, line 36 at r4](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFw4iRb0LBUlXpuFxTT:-LFw4iRc8ER1DCbMRrYI:b769n4l) ([raw file](https://github.com/robotlocomotion/drake/blob/a2c9058f83d87bba0549f734278f5a94edbc7d15/bindings/pydrake/util/deprecation_pybind.h#L36)):*
> ```objc
> 
> }  // namespace pydrake
> }  // namespace drake
> ```

My read of this PR is that these two methods each have one acceptance test, but do not have any unit tests.  In a few months when we remove those two deprecated methods, we will no longer have any test coverage for these two items.

At minimum, please take a deferred follow-up action to add unit tests here within a couple weeks; ideally, the commit with these new methods would also have direct unit testing when it goes in.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFw3sUG3maJXxqfzSxe:b87ey0x)*

**Comment by sherm1** [comment]
I believe this is just waiting for a repair from @ericcousineau-tri ?

---

Review status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LFzMas618sbuGn3PiZv:b-k2iik)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 99 files at r5.
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee ericcousineau-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LG0ofIX38EV8rzethuK:-LG0ofIX38EV8rzethuL:b-xm3rcd) (no related file):*
Added test case exercising `deprecation_pybind`

---

*[bindings/pydrake/util/deprecation.py, line 95 at r4](https://reviewable.io/reviews/robotlocomotion/drake/9051#-LFw2VDh6oJZ2whwRZMv:-LG0oUxl0kjlEXgR0fZL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a2c9058f83d87bba0549f734278f5a94edbc7d15/bindings/pydrake/util/deprecation.py#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The comment makes sense when viewed within the patches of this PR, but would be confusing when browsing this code post-merge.  Maybe something like this?
```python
# Logs a deprecation warning message.  Also used by deprecation_pybind.h
in addition to this file.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 99 files at r5, 9 of 95 files at r6.
Dismissed @EricCousineau-TRI from a discussion.
Review status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LG0sYVM7edz-spfka8y:bnfp4nl)*

**Comment by sherm1** [comment]
CI is clean, just waiting for your LGTM now @ericcousineau-tri.

---

Review status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LG1JmdV3kNAsiZwUdmI:b-q6r2fy)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, ericcousineau-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9051#-:-LG1N4h5EH_nyTVybFgB:bnfp4nl)*

**Comment by sherm1** [comment]
Thanks @EricCousineau-TRI for the Python wizardry!

**Pull request merged**
