### PR TITLE
Fixed namespace and updated to not use deprecated method.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3443)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

CC: @amcastro-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRaZaHVoTwG8JEzjnE4:b-mvf0zb)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRa_7r-ibf1vookWc4Z:-KRa_7r-ibf1vookWc4_:be5k3wo) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L27)):*
> ```cpp
> namespace systems {
> namespace plants {
> namespace rigid_body_plant {
> ```

BTW This amount of namespacing is pointless (but I guess allowed).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRa_FYoj_atf4t1j6hW:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRa_7r-ibf1vookWc4Z:-KRa_V_s2bspR9X_qjkh:b-rp71vq) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This amount of namespacing is pointless (but I guess allowed).
</details>
Hahaha! Let's clean it up in a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by jwnimmer-tri** [comment]
On second thought, let's quickly run it by @amcastro-tri for a sanity check, in case there was a different plan for either of these edits.

**Comment by liangfok** [comment]
OK SGTM.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRakKT39NtVj3uTls7q:bl00cea)*

**Comment by liangfok** [comment]
+@amcastro-tri for feature review.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRakaH0eFng2yPIWerH:b-dsacsr)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRdgaoXSYzcXGdCSPsp:-KRdgaoY5OHvYU7VqrR7:bv7ju5w) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L180)):*
> ```cpp
>   {
>     for (auto const& b : tree_->bodies) {
>       if (!b->has_mobilizer_joint()) continue;
> ```

To be honest I don't agree with this nomenclature in RBT. I would prefer here to just refactor `hasParent` to `has_parent()`.
There is no concept of mobilizer in RBT so I think this method just adds confusion. I would prefer this PR just doing the suggested refactor if you agree. 
When I clean up RBT to be System 2.0 compliant I will do so in a way architected from the very beginning to incorporate these concepts in a way transparent to the user but clearly useful for the developer. 

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRdhaUfrcImKSHp1QNm:-KRdhaUfrcImKSHp1QNn:b-e8k4l3) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L27)):*
> ```cpp
> namespace systems {
> namespace plants {
> namespace rigid_body_plant {
> ```

Ah! thank you for fixing this!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRdgaoXSYzcXGdCSPsp:-KRdhzKU7IO0dLbifpgT:b-4phdxw) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L180)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> To be honest I don't agree with this nomenclature in RBT. I would prefer here to just refactor `hasParent` to `has_parent()`.
> There is no concept of mobilizer in RBT so I think this method just adds confusion. I would prefer this PR just doing the suggested refactor if you agree. 
> When I clean up RBT to be System 2.0 compliant I will do so in a way architected from the very beginning to incorporate these concepts in a way transparent to the user but clearly useful for the developer. 
</details>
That's fine -- but if hasParent is the best method to use at the moment, then we should remove its `DRAKE_DEPRECATED` marking.  It would be nice to get this build warning removed, one way or another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRdgaoXSYzcXGdCSPsp:-KRdiAX76OqYDYsUypkj:byi6hqa) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> That's fine -- but if hasParent is the best method to use at the moment, then we should remove its `DRAKE_DEPRECATED` marking.  It would be nice to get this build warning removed, one way or another.
</details>
The suggested refactor is currently the following:

```
/home/liang/dev/drake_catkin_workspace/src/drake/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc:180:25: warning: ‘bool RigidBody::hasParent() const’ is deprecated (declared at /home/liang/dev/drake_catkin_workspace/src/drake/drake/../drake/systems/plants/RigidBody.h:128): 
DRAKE DEPRECATED: Please use has_mobilizer_joint(). [-Wdeprecated-declarations]
       if (!b->hasParent()) continue;
```

Are you saying we should ignore the above deprecation message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/rigid_body_plant/rigid_body_plant.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRdgaoXSYzcXGdCSPsp:-KRdmIuIyC8zW_Ba8Nng:b-2wdrgu) ([raw file](https://github.com/robotlocomotion/drake/blob/1fe29459a82cc949070cf1658ddd8ff71dccc850/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc#L180)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> The suggested refactor is currently the following:
> 
> ```
> /home/liang/dev/drake_catkin_workspace/src/drake/drake/systems/plants/rigid_body_plant/rigid_body_plant.cc:180:25: warning: ‘bool RigidBody::hasParent() const’ is deprecated (declared at /home/liang/dev/drake_catkin_workspace/src/drake/drake/../drake/systems/plants/RigidBody.h:128): 
> DRAKE DEPRECATED: Please use has_mobilizer_joint(). [-Wdeprecated-declarations]
>        if (!b->hasParent()) continue;
> ```
> 
> Are you saying we should ignore the above deprecation message?
</details>
FTR, based on a conversation with @amcastro-tri, I shall update this PR with the addition of `RigidBody::has_parent()` and deprecation of `RigidBody::hasParent()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please.

---

Review status: 1 of 17 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRduiFGSB3rZNRtBG9b:b-4m07ez)*

**Comment by amcastro-tri** [comment]
Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/RigidBody.cpp, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRduW2jBUCF2zVwtLtL:-KRduW2jBUCF2zVwtLtM:b-9fespj) ([raw file](https://github.com/robotlocomotion/drake/blob/adad1c56270bb81f7ec0695323b9579b47467cfc/drake/systems/plants/RigidBody.cpp#L59)):*
> ```cpp
> 
> // TODO(liang.fok): Remove this deprecated method prior to Release 1.0.
> bool RigidBody::has_mobilizer_joint() const { return has_parent_body(); }
> ```

I would remove `has_mobilizer_joint` in this PR. I don't think any externals users had the chance to start using this.

---

*[drake/systems/plants/RigidBody.h, line 128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRduq4MyG5SMUvR33Lr:-KRduq4MyG5SMUvR33Ls:bwu1caa) ([raw file](https://github.com/robotlocomotion/drake/blob/adad1c56270bb81f7ec0695323b9579b47467cfc/drake/systems/plants/RigidBody.h#L128)):*
> ```objc
>   DRAKE_DEPRECATED("Please use has_parent_body().")
> #endif
>   bool has_mobilizer_joint() const;
> ```

Please remove this `has_mobilizer_joint()` and deprecation all together in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by liangfok** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.cpp, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRduW2jBUCF2zVwtLtL:-KRdvMujtgb5pw90d0na:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adad1c56270bb81f7ec0695323b9579b47467cfc/drake/systems/plants/RigidBody.cpp#L59)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would remove `has_mobilizer_joint` in this PR. I don't think any externals users had the chance to start using this.
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-KRduq4MyG5SMUvR33Lr:-KRdvNhyM9NnySp1HHRE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/adad1c56270bb81f7ec0695323b9579b47467cfc/drake/systems/plants/RigidBody.h#L128)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Please remove this `has_mobilizer_joint()` and deprecation all together in this PR.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please.

**Comment by amcastro-tri** [comment]
:lgtm:, thanks @liangfok  

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRdwCHKVqkU0Bowg-vB:b-3x7tm5)*

**Comment by jwnimmer-tri** [comment]
Do we need to check with @sherm1 per #3246, so that we don't have _another_ rename after this PR merges?

---

Reviewed 14 of 16 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRdwPRVtAFwEOfkRQ_X:b-x0f7fc)*

**Comment by liangfok** [comment]
Ideally, yes. +@sherm1 for a second platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRdwzLVKmUISK7JUrWq:bpl2c34)*

**Comment by sherm1** [comment]
I'm OK with this milder rename from `hasParent()` to `has_parent_body()`. What I really want to see is something much more direct, like `!is_world()` if that is what this really means. But :lgtm:.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3443#-:-KRgBixeDoj5IqVfkJuz:b-mf5dx3)*

**Comment by RussTedrake** [comment]
fwiw — i’m very happy that we went w/ has_parent_body over has_mobilizer_joint

**Pull request merged**
