### PR TITLE
[deformable] Zero out jacobian columns for dofs under bc

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18371)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please. This is a follow up to #18290.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18371#-:-NI-w2UJDiP7_DD5qa-v:bl33x2)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Good stuff!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18371#-:-NIDB4Ur4G0faHE0ptqm:beuyiaz)* status: 9 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.cc` line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID5fMn-y78bNYWViLa:-NID5fMn-y78bNYWViLb:ba3xb96) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/deformable_driver.cc#L327)):*
> ```cpp
>     const DirichletBoundaryCondition<T>& bc =
>         fem_model.dirichlet_boundary_condition();
>     std::unordered_set<int> vertices_under_bc;
> ```

nit, I tend to be old fashioned, sorry.
Consider a `std::vector<bool>` (or `<int>`) of size num_vertices with all values initialized to `false` and setting here to `true` the ones with bcs. Then below you do not need a `count()` operation in the loop, but really just cheap vector access.

As a side effect, if you used `std::vector<int>` initialized with all zeros, below you could count how many bc's were applied to `vertex_index`. If different from zero or three, then you'd know the assumption below is not true. 
___
*[`multibody/plant/deformable_driver.cc` line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID771kAKJnmRIZ7_77:-NID771kAKJnmRIZ7_78:b-cyzg75) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/deformable_driver.cc#L334)):*
> ```cpp
>       const int dof_index = it.first;
>       const int vertex_index = dof_index / 3;
>       vertices_under_bc.emplace(vertex_index);
> ```

DEMAND that `it.second.y()` and `it.second.z()` are both zero? as assumed below?

The `DeformableModel::SetWallBoundaryCondition()` API right now imposes this. However, new APIs could break this assumption and this code would never bark.
___
*[`multibody/plant/deformable_driver.cc` line 365 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID5NIbAdRrfWs1hMKc:-NID5NIbAdRrfWs1hMKd:b-5oid95) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/deformable_driver.cc#L365)):*
> ```cpp
>            zero velocities. Otherwise, the kinematic relationship between dofs
>            and contact velocities will also contain a bias term. */
>           Jv_v_WAc_W.template middleCols<3>(3 * participating_vertices(v))
> ```

nit, if you skip this is already zero?
It might be you want to say it explicitly for clarity though, in which case I am ok.
Now, probably you want to use the equation below `v_WAc = (b₀ * v₀ + b₁ * v₁ + b₂ * v₂ + b₃ * v₃)` to justify vertex `v` is not contributing since its velocity is assumed to be zero.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID8I_b25-nkIJJcRhq:-NID8I_b25-nkIJJcRhr:b8qctfx) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L43)):*
> ```cpp
> 
> /* Registers a deformable octrahedron with the given `name` and pose in the
>  world to the given `model`. */
> ```

could you define frame F here? that is, where is its origin Fo located in the octahedron? how are the axes aligned with respect to the octahdron. In other words, how do we draw this octahdron in frame F?
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID8vfi9qFz5wFRk5Bh:-NID8vfi9qFz5wFRk5Bi:b-6k4ols) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L309)):*
> ```cpp
>                                     geometry::internal::kRezHint, 1.0);
> 
>   const RigidTransformd X_WR(Vector3<double>(0, 0, -0.75));
> ```

minor, say more about the choice `-0.75`? is it arbitrary? It just surprised me that it is not either zero (box with center at Wo) or `-0.5` box with upper plane going through Wo.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 333 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID9pNI-fFlSFQIbVvu:-NID9pNI-fFlSFQIbVvv:b-h2eivx) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L333)):*
> ```cpp
>   std::vector<ContactPairKinematics<double>> contact_kinematics;
>   driver->AppendContactKinematics(plant_context, &contact_kinematics);
>   EXPECT_GT(contact_kinematics.size(), 0);
> ```

don't we know the exact number for this case?
It might be nicer to test that as a way to also document the expectation.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 350 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID8cvNAIWdqys40J3w:-NID8cvNAIWdqys40J3x:buunfw4) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L350)):*
> ```cpp
>                /   |
>              +X    |
>                   -Z
> ```

maybe move this doc into RegisterDeformableOctahedron() to answer my question there and then here make reference to those docs?
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 356 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NIDAo5aDbZcT0v82c9h:-NIDAo5aDbZcT0v82c9i:b-b2ddhe) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L356)):*
> ```cpp
>     const ContactPairKinematics<double>& contact_kinematic =
>         contact_kinematics[i];
>     const Matrix3X<double>& J = contact_kinematic.jacobian[0].J;
> ```

nit, document the expectation that the first entry corresponds to the deformable body clique contribution.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 358 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NIDAzDkCIficzroA2rx:-NIDAzDkCIficzroA2ry:boib002) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L358)):*
> ```cpp
>     const Matrix3X<double>& J = contact_kinematic.jacobian[0].J;
>     /* The jacobian isn't completely zero. */
>     EXPECT_FALSE(CompareMatrices(J, MatrixXd::Zero(J.rows(), J.cols()), 0.01));
> ```

minor, consider `EXPECT_GT(J.norm(), 0.01)`?

**Review by xuchenhan-tri — COMMENTED** [review]
Comments addressed, PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18371#-:-NIFWRkx7baB8spq6zh5:b-4l0k23)* status: 7 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/plant/deformable_driver.cc` line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID5fMn-y78bNYWViLa:-NIFTvvO-cO6noeAZc2K:b-ylf67) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/deformable_driver.cc#L327)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I tend to be old fashioned, sorry.
Consider a `std::vector<bool>` (or `<int>`) of size num_vertices with all values initialized to `false` and setting here to `true` the ones with bcs. Then below you do not need a `count()` operation in the loop, but really just cheap vector access.

As a side effect, if you used `std::vector<int>` initialized with all zeros, below you could count how many bc's were applied to `vertex_index`. If different from zero or three, then you'd know the assumption below is not true. 
</blockquote></details>

That's very nice, thanks! Done.
___
*[`multibody/plant/deformable_driver.cc` line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID771kAKJnmRIZ7_77:-NIFTyed58B5XvV-v9pX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/deformable_driver.cc#L334)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

DEMAND that `it.second.y()` and `it.second.z()` are both zero? as assumed below?

The `DeformableModel::SetWallBoundaryCondition()` API right now imposes this. However, new APIs could break this assumption and this code would never bark.
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 365 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID5NIbAdRrfWs1hMKc:-NIFUHuK145bHcSpLXBM:bdmimm) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/deformable_driver.cc#L365)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, if you skip this is already zero?
It might be you want to say it explicitly for clarity though, in which case I am ok.
Now, probably you want to use the equation below `v_WAc = (b₀ * v₀ + b₁ * v₁ + b₂ * v₂ + b₃ * v₃)` to justify vertex `v` is not contributing since its velocity is assumed to be zero.
</blockquote></details>

I removed the other branch, PTAL.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID8I_b25-nkIJJcRhq:-NIFWPID7zQQtfHNK27Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L43)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you define frame F here? that is, where is its origin Fo located in the octahedron? how are the axes aligned with respect to the octahdron. In other words, how do we draw this octahdron in frame F?
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID8vfi9qFz5wFRk5Bh:-NIFUu911un9H4SYB-Vr:b-sbf2ja) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L309)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, say more about the choice `-0.75`? is it arbitrary? It just surprised me that it is not either zero (box with center at Wo) or `-0.5` box with upper plane going through Wo.
</blockquote></details>

I added a comment.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 333 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID9pNI-fFlSFQIbVvu:-NIFVAxC2RM3gc57DSSw:b-us6w4k) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L333)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

don't we know the exact number for this case?
It might be nicer to test that as a way to also document the expectation.
</blockquote></details>

The exact number depends on how contact points are sampled in geometry query, and I find that not too illuminating to include. TBH, I don't know the geometry query that well to know how many points are sampled in this case off the top of my head.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 350 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID8cvNAIWdqys40J3w:-NIFW93p74aqgNOYoEia:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L350)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

maybe move this doc into RegisterDeformableOctahedron() to answer my question there and then here make reference to those docs?
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 356 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NIDAo5aDbZcT0v82c9h:-NIFVei99k3YHE3-x247:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L356)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, document the expectation that the first entry corresponds to the deformable body clique contribution.
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 358 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NIDAzDkCIficzroA2rx:-NIFVjzZ2I_-ElgDzxVW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L358)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, consider `EXPECT_GT(J.norm(), 0.01)`?
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
Thanks @xuchenhan-tri. :lgtm: 

+@sammy-tri for platform review please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18371#-:-NIYwAIjB_QifNVYKBcK:b-5ljk3m)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[`multibody/plant/test/deformable_driver_contact_kinematics_test.cc` line 333 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18371#-NID9pNI-fFlSFQIbVvu:-NIYw2MACpCPzoGOSMqN:bb7g23t) ([raw file](https://github.com/robotlocomotion/drake/blob/34a4e7625a72acd42adf5402db43438c5abcbdc6/multibody/plant/test/deformable_driver_contact_kinematics_test.cc#L333)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The exact number depends on how contact points are sampled in geometry query, and I find that not too illuminating to include. TBH, I don't know the geometry query that well to know how many points are sampled in this case off the top of my head.
</blockquote></details>

fair

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18371#-:-NIZGnur7A5-JsnWUkhb:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
