### PR TITLE
Remove unused RBT include

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
... but add in back in a dozen other places that failed at IWYU.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4215)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
A bunch of targets failed because they didn't IWYU, but they are code that I can't test-compile on my machine.  I will wait until tomorrow to play the CI-whackamole game to fix this.

**Comment by jwnimmer-tri** [comment]
Huh.  A matlab test failed at runtime?  Hopefully spurious.
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Finally jenkins passes!  +@david-german-tri on call for all review, please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4215#-:-KXBtsehxArEfrNT6irb:b53j44p)*

**Comment by david-german-tri** [comment]
:lgtm: nice!  I've been looking forward to this little milestone for a while

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4215#-:-KXCYpTlNVWh8xfwlOB0:b-n2qsc4)*

**Pull request merged**
