### PR TITLE
Remove libbot

### PR DESCRIPTION
**Pull request by fbudin69500**
`libbot` is not used by `drake`. Projects that use `drake` that require libbot
can build `libbot` independently, using `lcm` that is built with `drake`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7698)

### CODE REVIEW

**Comment by fbudin69500** [comment]
This work is related to making libbot2 compatible with CMake (see [here](https://github.com/RobotLocomotion/libbot2/pull/6))

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7698#-:-L23DGbxYNtZTnkE--z6:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
I will find some time to look at this today.

(I seem to recall during the Bazel transition that I tried to prune dependencies such as this, and got push-back.  I'll need to go refresh my memory on what those discussions were about, and see if it still applies.)

**Comment by jamiesnape** [comment]
> (I seem to recall during the Bazel transition that I tried to prune dependencies such as this, and got push-back. I'll need to go refresh my memory on what those discussions were about, and see if it still applies.)

Yes, we have an alternative now. Spartan and Director are going to use the CMake version and we will have Homebrew and Apt packages up shortly.

**Comment by jwnimmer-tri** [comment]
:lgtm_strong: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7698#-:-L25oOUMLsgT1LBKvBOA:b-uwkowd)*

**Comment by peteflorence** [comment]
Hey guys, would have helped to have a heads up on this, this breaks the Spartan build

**Comment by jamiesnape** [comment]
My understanding was that you were pinned to a specific version of Drake. @fbudin69500 will PR the CMake version to Spartan shortly.

**Comment by peteflorence** [comment]
Okay awesome, thanks Jamie, yes you're right we are pinned typically, we were just a bit unlucky with the timing because we pulled on master to get https://github.com/RobotLocomotion/drake/pull/7696

**Comment by jwnimmer-tri** [comment]
For future reference, the [Drake Apt Site ](https://github.com/RobotLocomotion/drake/blob/0d27fec0519dcf464a5897adf7ad6c94052de9d0/setup/ubuntu/16.04/source_distribution/install_prereqs.sh#L24-L25) hosts a `libbot2` binary package with relatively recent build(s) of `libbot2`.

**Pull request merged**
