### PR TITLE
templatize constraint.h

### PR DESCRIPTION
**Pull request by hongkai-dai**
As requested by @JoshPetersen-TRI, when we use `const Eigen::Ref<const Eigen::VectorXd>`, we incur one extra copy, which is slightly more expensive than using templated function.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8816)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8816#-:-LCZrA_tDTDkUoKICXtx:bvhsv4m)*

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Could you give examples of calling code that incur an extra copy prior to this PR, but are solved by this PR?  For `CheckSatisfied` at least, I don't understand yet, since the implementations there turn around and call another method with `Eigen::Ref<const ...>`  anyway.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri yes you are right that it does not matter for `CheckSatisfied`. I think in `UpdatLowerbound` and `UpdateUpperBound`function it does matter.

I can revert the change on `CheckSatisfied` if you think it is preferable. I made that change in the first place, to use as many template as possible. But I did not change `DoCheckSatisfied`, since they are virtual functions? Should I change `DoCheckSatisfied` to template functions as well?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8816#-:-LCZzWexAQOzn6KwHsr-:ba0q2n8)*

**Comment by jwnimmer-tri** [comment]
If adding more template mumble serves no purpose, don't do it.  Also, you can't have templatized virtual functions so you can't (easily) change `DoCheckSatisfied` anyway.

Can you give an example of an `UpdateLowerBound` caller that is better off with this change?  I do agree that the method should be optimized for fast-path use, but I don't yet understand what kind of call site is improved with this change.

**Comment by hongkai-dai** [comment]
One example is that when we do online optimization. In every control tick, we want to solve an inverse kinematics problem f(x) = a. The function `f(x)` is unchanged in every control tick, but the bound `a` is changed. The code could look like
```C++
Eigen::Vector3d a(0, 0, 0);
LinearEqualityConstraint constraint(A, a);
for (int time = 0; time < 1000; ++time) {
  a << SOME_ARBITRARY NUMBER;
  constraint.UpdateBounds(a);
}
```
In this case `a` is a fixed size vector. It seems to me that it is better to use a templated `UpdateBounds` functions here, rather than `UpdateBounds(const Eigen::Ref<const VectorXd>&)`

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8816#-:-LC_16NR25zhyiAIcZQg:b-qjjxec)*

**Comment by jwnimmer-tri** [comment]
The implication would be that the `Vector3d` is copied to the heap as part of the call?  I don't think that's how it works?  Sure, a `Ref` temporary is formed, but if the claim is that _a small stack temporary_ is hosing us, then I'll need to see a benchmark to be convinced.  Do you have an example, possibly with `EIGEN_NO_MALLOC`, that shows a performance improvement, or lack of malloc?

**Comment by EricCousineau-TRI** [comment]
> when we use `const Eigen::Ref<const Eigen::VectorXd>` [...]

Yeah, I had asked about this a while back, but had not taken any action on it because it wasn't yet a problem:
https://forum.kde.org/viewtopic.php?f=74&t=141703#p381604

We can use this to check at compile-time to see what is upstream of this copy, and see if this can be better solved.
Alternatively, we can use dynamic striding with `Eigen::Ref` to avoid needing to copy as well; `pybind11` has a good example / explanation of it:
http://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html#storage-orders

But I would say these actions should be considered once we see where the performance bottleneck is and we have a comparison.

(My preference is also to avoid templating; if dynamic striding is a possible answer, I say we should try that out first before resorting to heavy templating.)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8816#-:-LC_lpYWEjVmvx7wj8CB:b-5ql6mg)*

**Comment by jwnimmer-tri** [comment]
For the `bound` stuff at least, my impression is that because they are only vectors (not full matrices), the stride doesn't come into play.

**Comment by hongkai-dai** [comment]
I think this templating these functions seem to be premature optimization, so I will close this PR.

**Pull request closed without merging**
