### PR TITLE
Remove deprecated package.xml files 2022-03

### LINKED ISSUE #10531: models: Fix resource URIs + file layout
At present, URDFs / SDFs in Drake specify things using relative paths, rather than proper URIs. For compatibility with tools like ROS, we should make them specify package paths.

In addition, we shouldn't provide packages with generic descriptions (like `iiwa_description`) in Drake, as it can shadow other non-Drake packages. Possible alternatives are:
- Ensure that all resource URIs use `package://drake/` (I prefer this one, as it's less awkward, and requires fewer awkward package paths to be added)
- Prefix all folders with `drake_`

Relates #9500 - see design doc.

\cc @calderpg-tri

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #10531.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16674)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16674#-Mwm2bB31RKSR-6EODCp:-Mwm2bB31RKSR-6EODCq:b-5o6oem) (no related file):*
Working

Do not merge until 2022-03-01.

---

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for both reviews, please?

\CC @cottsay FYI

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16674#-:-Mwm6thx-lc363kkis-k:b-yn0w5u)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2, sweet!

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16674#-:-MwmTtwm1O8NfcP0ki0z:b-hu9jfk)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16674)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16674#-Mwm2bB31RKSR-6EODCp:-Mx1lrFy8OtvFW-EmqAS:b-mgnqr5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Do not merge until 2022-03-01.
</blockquote></details>

OK
```
jwnimmer@call-cps:~$ date -u -R
Tue, 01 Mar 2022 00:00:27 +0000
```

---

**Comment by RussTedrake** [comment]
This broke my manipulation course repo.  I have many tests that depended on the package file:
```
RuntimeError: Sought 'drake/manipulation/models/wsg_50_description/package.xml' in runfiles directory '/private/var/tmp/_bazel_runner/7b4dc6001ecdbeb1b5ef1e14edba8c37/sandbox/darwin-sandbox/297/execroot/manipulation/bazel-out/darwin-fastbuild/bin/manipulation_station.runfiles' but the file does not exist at that location nor is it on the manifest; perhaps a 'data = []' dependency is missing.
```

Two questions: 
1) In what way were they deprecated?  This feels like a breaking change to me.
2) What is the recommended fix?

**Comment by jwnimmer-tri** [comment]
> In what way were they deprecated?

See annoucement in https://drake.mit.edu/release_notes/v0.36.0.html#newly-deprecated-configurations; the code changes in #15947 should have caused deprecation warnings to be printed during parsing for any uses of the old package name.  It's possible that finding the package but not using it would not have printed anything.

> What is the recommended fix?

There is only one Drake package now.  References to `package://wsg_50_description/foo` for example should say `package://drake/manipulation/models/wsg_50_description/foo` instead.

The `drake::multibody::Parser` class always has `package://drake` pre-loaded by default; no `AddPackageXml` is needed beforehand.

**Comment by RussTedrake** [comment]
Thanks. I was indeed manually adding the package to the parser (by locating the package.xml files, which have been removed).  As you say, I think the effect was that I was adding those packages to the path, but since the sdf / urdf wasn't using them, I never received a deprecation warning. (my code just broke when the package.xml files were removed).

**Comment by RussTedrake** [comment]
Actually, I did have one direct use of `<uri>package://wsg_50_description/meshes/wsg_body.obj</uri>`, etc which also failed to trip my deprecations.

**Comment by jwnimmer-tri** [comment]
> Actually, I did have one direct use ... which also failed to trip my deprecations.

Did it fail to print a warning message, or did it print a warning but the CI didn't elevate that to an error?

Not all of our C++ code's deprecation messages end up as formal Python deprecation warnings, sometimes they are just spdlog warnings.

**Comment by RussTedrake** [comment]
Using the drake revision immediately before this merged, the following code
```
from pydrake.all import AddMultibodyPlantSceneGraph, DiagramBuilder, SceneGraph, Parser, FindResourceOrThrow
from manipulation import FindResource

builder = DiagramBuilder()
plant, scenegraph = AddMultibodyPlantSceneGraph(builder, 0.0)
parser = Parser(plant)
parser.package_map().Add("wsg_50_description", os.path.dirname(FindResourceOrThrow("drake/manipulation/models/wsg_50_description/package.xml")))
parser.AddModelFromFile(FindResource("models/schunk_wsg_50_welded_fingers.sdf"))
```
loads without any visible logger warnings in the console despite https://github.com/RussTedrake/manipulation/blob/c7bbd820a1f9d82b6100c9fc19b72c9d78c423f8/manipulation/models/schunk_wsg_50_welded_fingers.sdf#L24 .  That is how I was using it.

I've confirmed that if I had used
```
parser.package_map().AddPackageXml(FindResourceOrThrow("drake/manipulation/models/wsg_50_description/package.xml"))
```
instead, then I would have gotten a logged warning (which I still wouldn't have picked up in my CI).  Not sure why I had the first, but perhaps I started using PackageMap before it was fully functional.

**Comment by jwnimmer-tri** [comment]
That makes sense.  That code wasn't loading the `package.xml` file, so the deprecation warning within that file never came into effect.

**Pull request merged**
