### PR TITLE
 pydrake deprecation: Add `deprecated` decorator 

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Addresses discussion in https://github.com/robotlocomotion/drake/pull/8257

This is a relatively simple implementation which relies on the `warnings` module.

This differs from the implementation in https://stackoverflow.com/questions/2536307/how-do-i-deprecate-python-functions, in that it is triggered upon access to the function, not when the function is called.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8272)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.

I couldn't think of a nice place to put `warnings.simplefilter('default', ...)` in the actual code. I'd like to not turn this on for everyone, but I don't want deprecation warnings to go unnoticed...

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-:-L6xH7ybvHz2PTsE0Y1F:b-hd61af)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xtNz2TVBRDRwAgcJ6:-L6xtNz2TVBRDRwAgcJ7:b8ua4wx) (no related file):*
What do you think about making class DrakeDeprecationWarning that extends DeprecationWarning, and force-enabling only that one by default (not all deprecations).  I think that would end up with:
- if users do nothing, they see deprecation warnings printed for our code (our filter is added at front, so wins for our subclass matches);
- if users do `simplefilter("someaction", DeprecationWarning)` then we'd obey it, be it "ignore" or "error".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272)*

**Comment by jwnimmer-tri** [comment]
LGTM modulo discussions.

---

Reviewed 8 of 12 files at r1, 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xwfT_yV9M72q3jBQR:-L6xwfTa-bxKFBF8F1Uz:bfe7r9t) (no related file):*
> This differs from the implementation in https://stackoverflow.com/questions/2536307/how-do-i-deprecate-python-functions, in that it is triggered upon access to the function, not when the function is called.

Something along these lines (triggered on access) seems worth putting in the pydoc for the deprecation helper.

---

*[bindings/pydrake/util/deprecation.py, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xuTRCMM8jcebTPAOj:-L6xuTRDxP1RvkW970up:bb5oozx) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L10)):*
> ```Python
> 
> class ModuleShim(object):
>     """
> ```

BTW PEP-0257 doesn't want a linebreak here; summary immediately follows the triplequote, without interstitial whitespace.

---

*[bindings/pydrake/util/deprecation.py, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xurfXQwy2GdwT_oah:-L6xurfYle2CerF1cabX:b-2s3qa3) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L52)):*
> ```Python
>         sub = traceback.extract_stack()[-3:-1]
>         assert sub[1][2] == "__getattr__"
>         if sub[0][3] is None:
> ```

The second index argument is too obscure.  Reading the traceback docs it looks like the tuple is `(filename, line number, function name*, text)`; I suggest using tuple unpacking something like `(_, _, _, text) = sub[0]` or a namedtuple or similar for clarity.  Or at minimum `traceback_text = sub[0][3]` or similar.

---

*[bindings/pydrake/util/deprecation.py, line 111 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xw1vk1Wr8ciBDQ502:-L6xw1vk1Wr8ciBDQ503:bf3lg7u) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L111)):*
> ```Python
> 
> def deprecated(message):
>     """Decorator which deprecates a member of a class.
> ```

BTW s/which/that/

---

*[bindings/pydrake/util/deprecation.py, line 114 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xw989IWtTjRPaKtNX:-L6xw989IWtTjRPaKtNY:bn4wln6) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L114)):*
> ```Python
>     @param callback
>         Callback to be invoked the first time the deprecated member
>     is accessed.
> ```

I don't think there's a callback param anywhere.  Maybe this is stale?  Or else I'm confused.

---

*[bindings/pydrake/util/deprecation.py, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xvJs8G96r8pE-zxiD:-L6xvJs8G96r8pE-zxiE:bdztkw6) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L124)):*
> ```Python
> 
> # TODO(eric.cousineau): Find a better place to put this, such that we won't
> # have side effects.
> ```

This seems important enough to fix prior to merging.

---

*[bindings/pydrake/util/test/deprecation_test.py, line 78 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xxKZXjVdiJ0ptj2d2:-L6xxKZYK_LJxNwKM5sX:b-482tya) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/test/deprecation_test.py#L78)):*
> ```Python
>             # warn once per unique line of source code.
>             # - Method.
>             for i in range(3):
> ```

BTW `for _ in range()` is more pythonic, I think?

---

*[bindings/pydrake/util/test/deprecation_test.py, line 88 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xxiA2SQl41oakLILC:-L6xxiA2SQl41oakLILD:bwh2mnv) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/test/deprecation_test.py#L88)):*
> ```Python
>                 extra = ExampleClass.deprecated_2
>             self.assertEquals(member.__doc__, ExampleClass.doc_2)
>             self.assertEquals(member.__get__(obj), 2)
> ```

This leaves me wondering whether `self.assertEquals(obj.deprecated_2, 2)` works (i.e., the direct call, instead of dunder-get).  Same for the method.  I wonder if (possibly in another warnings-ignore context, though really it doesn't matter for a unit test -- its muted anyway) we could just make the usual vanilla method calls or property access and confirm they still work.

---

*[bindings/pydrake/util/test/deprecation_test.py, line 96 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xxc4hI8tRtW1qYw7I:-L6xxc4hI8tRtW1qYw7J:bipn6qo) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/test/deprecation_test.py#L96)):*
> ```Python
>             self._check_warning(w[3], ExampleClass.message_2)
> 
>         # Uncomment this to manually inspect the warnings.
> ```

BTW s/Uncomment/Edit/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-:-L6xyMXDpsJ8vXeOPTxc:b436ime)*

**Comment by EricCousineau-TRI** [comment]
Review status: 6 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xtNz2TVBRDRwAgcJ6:-L6y2bLKXe3msdm-nQsc:b-13hihv) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What do you think about making class DrakeDeprecationWarning that extends DeprecationWarning, and force-enabling only that one by default (not all deprecations).  I think that would end up with:
- if users do nothing, they see deprecation warnings printed for our code (our filter is added at front, so wins for our subclass matches);
- if users do `simplefilter("someaction", DeprecationWarning)` then we'd obey it, be it "ignore" or "error".
</blockquote></details>

Done. I like it!

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xwfT_yV9M72q3jBQR:-L6y4NNseZxoVqHktrYE:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> This differs from the implementation in https://stackoverflow.com/questions/2536307/how-do-i-deprecate-python-functions, in that it is triggered upon access to the function, not when the function is called.

Something along these lines (triggered on access) seems worth putting in the pydoc for the deprecation helper.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/deprecation.py, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xuTRCMM8jcebTPAOj:-L6y2GwBhT_0-TZJdFbG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW PEP-0257 doesn't want a linebreak here; summary immediately follows the triplequote, without interstitial whitespace.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/deprecation.py, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xurfXQwy2GdwT_oah:-L6y2HZs-mRZhD7My9kY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The second index argument is too obscure.  Reading the traceback docs it looks like the tuple is `(filename, line number, function name*, text)`; I suggest using tuple unpacking something like `(_, _, _, text) = sub[0]` or a namedtuple or similar for clarity.  Or at minimum `traceback_text = sub[0][3]` or similar.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/deprecation.py, line 111 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xw1vk1Wr8ciBDQ502:-L6y2IPsbh1GTumZtJG4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L111)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW s/which/that/
</blockquote></details>

Done.

---

*[bindings/pydrake/util/deprecation.py, line 114 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xw989IWtTjRPaKtNX:-L6y2JYPqH3-yKsUEPia:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think there's a callback param anywhere.  Maybe this is stale?  Or else I'm confused.
</blockquote></details>

Done. Oops!

---

*[bindings/pydrake/util/deprecation.py, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xvJs8G96r8pE-zxiD:-L6y2KVS0QR8As-M5CS5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/deprecation.py#L124)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems important enough to fix prior to merging.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/test/deprecation_test.py, line 78 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xxKZXjVdiJ0ptj2d2:-L6y2TbU3R_4FiAEvEs8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/test/deprecation_test.py#L78)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `for _ in range()` is more pythonic, I think?
</blockquote></details>

Done.

---

*[bindings/pydrake/util/test/deprecation_test.py, line 88 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xxiA2SQl41oakLILC:-L6y2UFecRot-vtKWM4d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/test/deprecation_test.py#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This leaves me wondering whether `self.assertEquals(obj.deprecated_2, 2)` works (i.e., the direct call, instead of dunder-get).  Same for the method.  I wonder if (possibly in another warnings-ignore context, though really it doesn't matter for a unit test -- its muted anyway) we could just make the usual vanilla method calls or property access and confirm they still work.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/test/deprecation_test.py, line 96 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6xxc4hI8tRtW1qYw7I:-L6y2VW97N_kDukQmRnD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d1f3b530a74d667edc811b2bed557611c3580b2a/bindings/pydrake/util/test/deprecation_test.py#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW s/Uncomment/Edit/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272)*

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri for platform review, please.

---

Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-:-L6y55VIbtZshVd8gx3t:bcav8r0)*

**Comment by jwnimmer-tri** [comment]
LGTM code; I guess I should experiment a bit locally before the emoji.

---

Reviewed 3 of 12 files at r1, 3 of 3 files at r5.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-:-L6y5VapPgBdPbGBotK1:b-y2puw8)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 12 files at r1, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272)*

**Comment by EricCousineau-TRI** [comment]
(Er, the separate commits view here just went to crap; switched to revision-based viewing.)

---

Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-:-L6y7JjmQMbSeW97TLuW:b-sfcdky)*

**Comment by jwnimmer-tri** [comment]
(Yeah; "review each commit separately" is unlikely to do what we want.)

:lgtm: tested locally, though see notes below.

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/util/deprecation.py, line 1 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6yIRv-E76LMqjVNlrw:-L6yIRv0EQr466Wzf9EQ:b-w4k0sy) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L1)):*
> ```Python
> import sys
> ```

FYI I wonder if the deprecation warning message should always point users at`help(pydrake.util.deprecation)`, and then we add a pydoc module-level string with some advice, such as how to silence the warning, or that giddyup the deprecated stuff won't survive for long, or etc?

---

*[bindings/pydrake/util/deprecation.py, line 134 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6yFKbe5l2VsS85Vu__:-L6yFKbe5l2VsS85Vu_a:bv9ovr) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L134)):*
> ```Python
> 
> 
> warnings.simplefilter('default', DrakeDeprecationWarning)
> ```

Since we are stepping away from the Pythonic default of `'ignore'`, after some local testing here I'm thinking that `'once'` is actually what we want?  A single mention of each deprecated Drake API is the least-intrusive change that we could add that gets a message to the user.

---

*[bindings/pydrake/util/deprecation.py, line 134 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L6yHaLbmyMgHv3M9CZU:-L6yHaLbmyMgHv3M9CZV:blnyilo) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L134)):*
> ```Python
> 
> 
> warnings.simplefilter('default', DrakeDeprecationWarning)
> ```

For clarity as users explore why Drake is yelling, its probably worth documenting here (and/or in the module-level pydoc) that this line overrides anything on the command-line `-W` setting.  Only `warnings.simplefilter()` or some similar post-import call could change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-:-L6y7tPocDwQ-YE6tstI:b8du21g)*

**Comment by ggould-tri** [comment]
:lgtm:; I am very happy with this change.

---

Reviewed 5 of 14 files at r1, 2 of 6 files at r2, 2 of 6 files at r5, 1 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/util/deprecation.py, line 134 at r6](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-L6yFKbe5l2VsS85Vu__:-L7-peRlC02NyZ8HNYUe:bdghwmc) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L134)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since we are stepping away from the Pythonic default of `'ignore'`, after some local testing here I'm thinking that `'once'` is actually what we want?  A single mention of each deprecated Drake API is the least-intrusive change that we could add that gets a message to the user.
</blockquote></details>

I concur.  If the user is seeing messages at all, once is enough; if the user is ignoring warnings, spam will only reinforce that decision.

---

*[bindings/pydrake/util/deprecation.py, line 93 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-L7-ohuj8B_nA_UD8-Kc:-L7-ohuj8B_nA_UD8-Kd:b-6ksx43) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c1c6fcdea14413e67a3a61c7de71aa4f2ad16/bindings/pydrake/util/deprecation.py#L93)):*
> ```Python
> 
> class _DeprecatedDescriptor(object):
>     """Wraps a descriptor to deprecate the value upon access."""
> ```

FYI, IMO:  While delightfully correct, this use of "deprecate" in the sense of "speak ill of" is a bit surprising.  "Warn that the value is deprecated any time it is accessed" would be clearer.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-:-L7-qCyC5UMGNFR6p0SB:b-h0y45p)*

**Comment by EricCousineau-TRI** [comment]
Review status: 7 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/util/deprecation.py, line 1 at r6](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-L6yIRv-E76LMqjVNlrw:-L7Quo8n4R3uCMJONArU:b-4a9w6m) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I wonder if the deprecation warning message should always point users at`help(pydrake.util.deprecation)`, and then we add a pydoc module-level string with some advice, such as how to silence the warning, or that giddyup the deprecated stuff won't survive for long, or etc?
</blockquote></details>

Done. I'd prefer to make each individual deprecation state its own lifetime, and would rather not redefine what deprecation is?

---

*[bindings/pydrake/util/deprecation.py, line 134 at r6](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-L6yFKbe5l2VsS85Vu__:-L7Quymy2uI3wf4NUvh4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L134)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I concur.  If the user is seeing messages at all, once is enough; if the user is ignoring warnings, spam will only reinforce that decision.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/deprecation.py, line 134 at r6](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-L6yHaLbmyMgHv3M9CZU:-L7Quz5eBZe0S_9YTk6X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/376314ff936455114bc7fc3d8e684af78b2983cc/bindings/pydrake/util/deprecation.py#L134)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For clarity as users explore why Drake is yelling, its probably worth documenting here (and/or in the module-level pydoc) that this line overrides anything on the command-line `-W` setting.  Only `warnings.simplefilter()` or some similar post-import call could change it.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/deprecation.py, line 93 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272#-L7-ohuj8B_nA_UD8-Kc:-L7QuxsqECFYHyPV_Cdu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d26c1c6fcdea14413e67a3a61c7de71aa4f2ad16/bindings/pydrake/util/deprecation.py#L93)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI, IMO:  While delightfully correct, this use of "deprecate" in the sense of "speak ill of" is a bit surprising.  "Warn that the value is deprecated any time it is accessed" would be clearer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L7QwPF_FJqIh1-m9REc:-L7QwPF_FJqIh1-m9REd:bguvu2n) (no related file):*
DNM: This PR had more-than-trivial changes since my LGTM; I'll close this discussion once I've re-reviewed the files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 12 files at r1, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/util/test/deprecation_test.py, line 112 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L7QygqnLB1qiSwxswz2:-L7QygqnLB1qiSwxswz3:bn9a8xd) ([raw file](https://github.com/robotlocomotion/drake/blob/755632ffe96d117180bdec6cff8ae2053db4be16/bindings/pydrake/util/test/deprecation_test.py#L112)):*
> ```Python
>         # change the filter to test behavior. `reload`ing `warnings` and/or
>         # `_warnings` also does not work.
>         # See caveat here with`catch_warnings`:
> ```

BTW Needs whitespace within `with 'catch`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L7QwPF_FJqIh1-m9REc:-L7SBi-rOLnrxZFqugMp:b-dwo5bh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

DNM: This PR had more-than-trivial changes since my LGTM; I'll close this discussion once I've re-reviewed the files.
</blockquote></details>

Let me know if you'd like me to split the commits touching `rbtree` and `parsers` off into a separate PR to limit this one's scope. (Sorry for the runaway)

---

*[bindings/pydrake/util/test/deprecation_test.py, line 112 at r8](https://reviewable.io:443/reviews/robotlocomotion/drake/8272#-L7QygqnLB1qiSwxswz2:-L7SBpKVCtHbFhzffajv:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/755632ffe96d117180bdec6cff8ae2053db4be16/bindings/pydrake/util/test/deprecation_test.py#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Needs whitespace within `with 'catch`.
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8272)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 6 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8272)*

**Pull request merged**
