### PR TITLE
Adding Continuous-time algebraic Riccati equation Unit Test 

### PR DESCRIPTION
**Pull request by jyopari**
I based this unit test of the Discrete-Time Algebraic Riccati Equation unit test, but the solution is obviously different, and so it the test matrices. I only added one test, but I will definitely add more, to make this unit test more robust. Feel free to give any feedback in ways to improve this! I wouldn't be surprised if I made some mistakes. To avoid any confusions, I believe this is an issue that has been assigned last year but the person who it was assigned to never did it, so Mr.Tedrakes said I should work on this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6351)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jamiesnape** [comment]
@drake-jenkins-bot test this please

**Comment by RussTedrake** [comment]
+@siyuanfeng-tri  for feature review, please?
hopefully fixes #4402
note: just realized the filename added in https://github.com/RobotLocomotion/drake/pull/4360/files#diff-0bcd0d5f3bcf0a7f5418fc34ae489a1a spells riccati incorrectly.  we should rename it, too.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-:-Ko-aFWJvVr9UfIUtGKK:bsa2y4w)*

**Comment by siyuanfeng-tri** [comment]
@jyopari thanks for contributing! 
how ever I am pretty sure that this test is not actually being compiled. 
you need to edit drake/math/test/CMakeLists.txt and drake/math/BUILD to add this test to the Cmake build and bazel build :)  

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/math/test/continous_algebraic_riccati_equation.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-Ko0HyMZVyJFsq7lt-9Y:-Ko0HyM__KqcPVT9K9K-:b7r2hvt) ([raw file](https://github.com/robotlocomotion/drake/blob/a73c483099908ebe6c8da5ecd8e5398d198bafb8/drake/math/test/continous_algebraic_riccati_equation.cc#L21)):*
> ```cpp
>     int n = X.rows();
>     Eigen::SelfAdjointEigenSolver<MatrixXd> es(X);
>     for (int i = 0; i < n; i++) {
> ```

BTW could just do X.rows() here, or make n const int. 

---

*[drake/math/test/continous_algebraic_riccati_equation.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-Ko0Ij6G-mvcfuU8Z9q5:-Ko0Ij6G-mvcfuU8Z9q6:b-i5vzrt) ([raw file](https://github.com/robotlocomotion/drake/blob/a73c483099908ebe6c8da5ecd8e5398d198bafb8/drake/math/test/continous_algebraic_riccati_equation.cc#L27)):*
> ```cpp
>   MatrixXd Y = (A.transpose*X)+
>                      (X*A)-(X*B*R.inverse*B.transpose)+
>                      (C.transpose*C); // Solving the Continous-Time AR Equation using A^T*X+X*A-XBR^-1+C^T*c = 0 
> ```

what's C?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-:-Ko0J56ZVoeyEZpnGoqm:b-vvspj2)*

**Comment by siyuanfeng-tri** [comment]
you may also want to run clang-format on your .cc file. http://drake.mit.edu/code_style_tools.html?highlight=clang%20format 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-:-Ko0KTu8mq_cyLVRGX6X:bjp33qa)*

**Comment by jyopari** [comment]
So my C++ knowledge isn't really good (I do python) , I had to learn it to write this test. Can you help me out with this?

**Comment by jyopari** [comment]
I updated some issues. @siyuanfeng-tri can you check it out now?

**Comment by siyuanfeng-tri** [comment]
add 
drake_add_cc_test(continuous_algebraic_riccati_equation_test)
target_link_libraries(continuous_algebraic_riccati_equation_test drakeCommon drakeMath)
to drake/math/test/CMakeLists.txt

and add
drake_cc_googletest(
    name = "continuous_algebraic_riccati_equation_test",
    deps = [ 
        ":continuous_algebraic_ricatti_equation",
        "//drake/common:eigen_matrix_compare",
    ],  
)
to drake/math/BUILD

Then try the cmake build and bazel build. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-:-KohuolM2b8TSr_tElum:bq5fxql)*

**Comment by jyopari** [comment]
Good to go @siyuanfeng-tri

**Comment by jyopari** [comment]
@siyuanfeng-tri Is it ready?

**Comment by siyuanfeng-tri** [comment]
Hey, if you click into reviewable (the web UI we use for code reviews), and on the top, look for "checks", you will notice that there are a bunch of builds that failed. You can click into one of them and look for "View Superbuild in CDash", it will tell you where the build failed. 
In your case, I think it's better for you to build them locally on your machine, instead of pushing to the continuous integration servers. 

you can find more information about how to build from source here, http://drake.mit.edu/from_source.html. If you want to visit TRI, I can also help you go through it, might be easier. Just let me know. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-:-KpQ3PZ-ng58X_vFDey0:bqju6uh)*

**Comment by jyopari** [comment]
Ok, I could use some help.

**Comment by jyopari** [comment]
@siyuanfeng-tri Can u help me out.

**Comment by siyuanfeng-tri** [comment]
@jyopari you around MIT? how about you visit tri next week? I just send an email to your gmail.

**Comment by siyuanfeng-tri** [comment]
try change your continuous_algebraic_riccati_equation.cc to continuous_algebraic_riccati_equation_test.cc, your build system is complaining that it can't find the source. 
Also you can try to compile these locally to avoid pushing to continuous integration all the time. 

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6351#-:-Kr1bBZ1fu6JYvVvNpi7:buvg3el)*

**Pull request closed without merging**
