### PR TITLE
Revert "[build] Start to modernize bazel sanitizer configs"

### PR DESCRIPTION
**Pull request by svenevs**
- Revert "[build] Start to modernize bazel sanitizer configs (#17405)"
    
    This reverts commit 892e15df1a5b12035c06a605ab09e3a0333399dd.

- Revert "[geometry] Improve KinematicsVector (#17394)"
    
    This reverts commit 5c86fd443b7cbc07ac13411373a73df74648ec46.

See discussion in #17268, opening now to be able to launch jobs to run CI against and see if we have any missing failures.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17422)

### CODE REVIEW

**Comment by svenevs** [comment]
Adding all jobs that seem possibly relevant, skipping "regular" clang builds since adding "everything" clang builds (non-solver types):

@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please.

**Comment by jwnimmer-tri** [comment]
The TSan linker errors indicate that we also need to revert #17394.  (Probably a two-commit curated PR, with kinematic vector revert first, and the rcfile revert second.)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-address-sanitizer please

Seems like the OOM flake.  Trying again.

**Pull request merged**
