### PR TITLE
multibody: Add doxygen block diagrams

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #9496

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16200)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +(priority: low) +@RussTedrake for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16200#-:-MqW1jGQ3CmDO9258AnS:b-53jbcg)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16200#-MqW1l6a5mX9Tiph66Mm:-MqW1l6a5mX9Tiph66Mn:btxp9dr) (no related file):*
From my scan, there was only one class in all of multibody/ that was missing a diagram and could actually benefit at all. MultibodyTreeSystem doesn't define any ports, so I skipped it.

---

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16200#-:-MrSdWK2Buv7hBNxEFZK:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16200#-:-MrTI3xZ6HwnI_MTR0Dl:b-azei6o)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16200#-:-MrTPIe38gGdb6IK57EN:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @rpoyner-tri)

**Pull request merged**
