### PR TITLE
[fem] Fix 3x3 block Cholesky in PETSc

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Prevent 3x3 block Cholesky for PETSc SBAIJ matrix from going out of bound.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16328)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16328#-MslRNfr4jNP34RNAjq7:-MslRNfr4jNP34RNAjq8:b-s5dh3q) (no related file):*
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please

---

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16328#-:-MslkwhT7SjD5wjUh4An:b-51ktqu)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

It's good to land this patch into Drake immediately, but you should also submit it upstream, so that eventually we'll be able to drop it from here and so that upstream provides any feedback in case there is a problem with this fix.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16328#-:-Msm-c2t9wlEqW0wfpC3:b-zg8ciu)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This fix is only supposed to be a temporary band-aid as it only fixes a particular block size that deformable solver currently uses (aka block_size == 3). Other special sizes (1-7) is not fixed and the general case is not fixed. Filed issue upstream here: https://gitlab.com/petsc/petsc/-/issues/1082

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16328#-:-Msm5tIv8ZAdEZskKdpX:b-mza7qz)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Pull request merged**
