### PR TITLE
Teach LeafSystem about named_vector declared inequality constraints

### LINKED ISSUE #7037: Generated BasicVector subclasses should automatically generate SystemConstraints
Generated BasicVector subclasses such as [PendulumParams](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/pendulum/gen/pendulum_params.h) should automatically generate [SystemConstraint](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system_constraint.html) instances when they are declared as State, Params, etc. of a System.

This should happen automatically (the DeclareFoo methods should inspect the type to see if constraints are available), but perhaps should offer an opt-out in case someone doesn't want the magic behavior.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7037.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7057)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.  If your time is tight, I'd minimally need a review of the leaf_system.h API changes and the new leaf_system_test.cc cases, and then I could kick a full feature review over to someone else.

**Comment by RussTedrake** [comment]
:lgtm:  despite my lack of comments, I actually did do a feature review pass.  

is there any other code path, besides the DeclareContinuousState, DeclareVectorInput, DeclareParams.... that you've covered, where folks might use a typed vector and expect to have the constraints enforced but not get that?

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7057#-:-KuUD41jI9Un1QCyHz_d:bwtf4hw)*

**Comment by jwnimmer-tri** [comment]
Good question.  I'd done a survey when getting started on this, but I will double-check again to see if I missed anything.

+@ggould-tri for platform review per rotation, please.

**Comment by jwnimmer-tri** [comment]
I think the biggest question is for LeafSystem::DeclareVectorOutputPort.  You can pass a model_vector in there, but I'd decided not to add constraints on the _output_ of a System.  My intuition was that only the Context (directly) should inform constraints, not the System + Context pair via CalcOutput.  Also, if the connected input was also subtyped, then the receiving System would have declared the constraints.  What do you think?

Separately, a possible confusion is if a user overrides one of the Allocate methods on LeafSystem (AllocateInputVector, AllocateContinuousState, AllocateParameters, etc.) instead of using Declare with a model_vector.  In that case, the constraints would not be added.  This seems like a reasonable distinction to me.

Note that right now DeclareDiscreteState does not support a model_vector, so does not offer a way to add type-discrete-state-intrinsic constraints.  When we offer a model_vector Declare for that, it should auto-add the constraints.

**Comment by ggould-tri** [comment]
:lgtm: on the content.

The semantics you describe above sound right to me, but like you I have a small qualm about the lack of constraints on output.  If we intend users to be able to treat System blocks as reusable legos, output constraints seem like they would be part of the API contract of a block.

However I think treating contract-constrained outputs as description and documentation, and potentially enforcing with assertions as needed during simulation stepping, is probably cleaner than extending the solver-constrained enforcement to them.  Solver constraints are not a great fit for API boundaries anyway.

So I think this is all fine, although time and usage may prove us wrong just as a matter of ergonomics.

---

Reviewed 15 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7057#-:-KuUPWdo0eGszq-oGuJK:bc3r1s6)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7057)*

**Comment by RussTedrake** [comment]
I was worried about the allocate override, but you're right... the name is probably sufficiently clear on that point.  Perhaps a comment near those methods could be a cheap guard?

Can we make an issue on DeclareDiscreteState with a model vector?  That feels like a bigger gap.

**Comment by jwnimmer-tri** [comment]
@RussTedrake any thoughts on outputs having constraints?  Though I guess that could easily be a future PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7057#-:-KuUVzHY7KzIkJi1FfuZ:b-val62m)*

**Comment by jwnimmer-tri** [comment]
> Can we make an issue on DeclareDiscreteState with a model vector?

Filed as #7058.

**Comment by RussTedrake** [comment]
Re output constraints:  that's a great question.  they are much less trivial to enforce, but the concept is still meaningful.  i think we should support them (in a future PR is ok for me).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7057#-:-KuVhq5T73HkCD8YWFUv:b-s5k43e)*

**Pull request merged**
