### PR TITLE
Remove deprecated methods (2019-04)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The `GeometrySet::geometries` deadline is extended for another month; we are still using it within TRI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11067)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews of the `//geometry/**` stuff, please.  (If you want to do the whole PR that's fine too.)  Note the "priority: backlog".  This won't merge until Monday.

**Comment by SeanCurtis-TRI** [comment]
I'll take a gander on Friday.

**Comment by calderpg-tri** [comment]
Since `GeometrySet` can contain both geometries and frames:

- It is not iterable

- It is not standalone queryable (`GeometrySet::contains()` cannot be complete without access to the SceneGraph)

A collection type that the user can create but not safely query feels pretty dirty. Right now, there are cases where the user needs to collect geometries for consumption by `SceneGraph` and their own use, and requiring separate types for the same purpose is unnecessary.

I would propose a couple options for discussion:

1. Remove `GeometrySet` from the public API entirely and make users provide containers (`vector<GeometryId>`, `unordered_set<GeometryId>`), (`vector<FrameId>`, `unordered_set<FrameId>`) for geometries and frames.

2. In the public API, separate geometry and frames into `GeometrySet` and `FrameSet` so that geometry/frame mismatch can't occur, and thus either `GeometrySet` and `FrameSet` are safely queryable and iterable. A combined wrapper in the internal API is fine.

**Comment by jwnimmer-tri** [comment]
> I would propose a couple options for discussion ...

Maybe that discussion should not happen here?  This is just monthly janitor work, and should be boring.

I know for sure I can't remove the `geometries()` method today, so I marked it 2019-05-01 instead.  Other options for this PR are to push out all of GeometrySet deprecations to 2019-05-01, or to un-deprecate that method only, or un-deprecate all of those methods.  Basically some boring version of "Make deprecation dates on master not be in the past".

It's great to talk about feature requests and the correct API, but this boring PR should not be that place, I think?

**Comment by SeanCurtis-TRI** [comment]
New place created for this discussion: see #11072.

**Comment by calderpg-tri** [comment]
FYI, I have removed the deprecated uses from Anzu, so you can remove them for now.

**Pull request merged**
