### PR TITLE
NewSosPolynomial detects uninitialized enum values

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review.

For context, in some code I managed to pass an unitialized `NonnegativePolynomial` type to this function which silently misses all of the cases. I am not sure why the compiler doesn't catch this unitialized variable, but regardless I think it is probably a good idea to add this default case.

On the other hand, I am having some trouble testing this addition since the compiler manages to catch all of the ways I attempt to pass an unitialized type to this function.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754#-:-N9qRmHR5Glpj0Bo2CrZ:bdopclh)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Hmm I didn't realize that the value of enum class can fall out of its enumeration value. Here NonnegativePolynomial class has only three values `kSos, kSdsos, kDsos` https://github.com/RobotLocomotion/drake/blob/7abea0556ede980a5077fe1a8cfbae59b57c7c27/solvers/mathematical_program.h#L467-L471

@jwnimmer-tri could you confirm that an Enum class can have an undefined value? I know that with plain `enum` I can have unlisted value, but I didn't realize this could also happen to `enum class`. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754#-:-N9tanvNBaq4XCvyjx2p:bp8xn3y)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`solvers/mathematical_program.cc` line 271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17754#-N9tdHjsAOYf9TYgFU7V:-N9tdHjsAOYf9TYgFU7W:b2fval2) ([raw file](https://github.com/robotlocomotion/drake/blob/29f5e0198fed429e0e3866bcbed13f782f7659ed/solvers/mathematical_program.cc#L271)):*
> ```cpp
>       throw std::runtime_error(
>           "Passed NonnegativePolynomial type that is either unsupported or "
>           "unitialized");
> ```

typo, should be `uninitialized`.

**Comment by jwnimmer-tri** [comment]
See https://en.cppreference.com/w/cpp/language/static_cast item 8a.

> A value of [integer] type can be converted to any complete enumeration type... the behavior is undefined if the value of expression is out of range (the range is all values possible for the smallest bit field large enough to hold all enumerators of the target enumeration).

Since the current enum assigns the values 0..2, the bitfield is 2 bits wide.  Therefore, passing anything other than 0..3 as the enum is undefined behavior.

That means we _could_ test the code by passing 3 for the enum value, like this:

```c++
  CheckNewSosPolynomial(static_cast<MathematicalProgram::NonnegativePolynomial>(
      static_cast<int>(MathematicalProgram::NonnegativePolynomial::kDsos) + 1));
```

However, I advise _against_ doing this.  If we ever added a fourth item to the enum, then it would be impossible to preserve this test -- all four defined values would be valid (the bitfield is still 2 bits wide), so the switch-case would cover all tests.  We would need to delete this test case.  In short, such the test is very brittle.

---

Also, _never_ add a default to a switch.  It defeats the compiler error message that reminds us when we forget to mention a newly-added enum value.

If you want to catch unmatched values, then we need to do that by having code _after_ the switch statement that handles it.

One way to do that is with a `bool matched;` which starts false and is set to true in every case.  But in this code, it's actually easier to just return in each case rather than use a bool:

```patch
--- a/solvers/mathematical_program.cc
+++ b/solvers/mathematical_program.cc
@@ -254,19 +254,19 @@ symbolic::Polynomial MathematicalProgram::NewSosPolynomial(
   switch (type) {
     case MathematicalProgram::NonnegativePolynomial::kSos: {
       AddPositiveSemidefiniteConstraint(gramian);
-      break;
+      return p;
     }
     case MathematicalProgram::NonnegativePolynomial::kSdsos: {
       AddScaledDiagonallyDominantMatrixConstraint(gramian);
-      break;
+      return p;
     }
     case MathematicalProgram::NonnegativePolynomial::kDsos: {
       AddPositiveDiagonallyDominantMatrixConstraint(
           gramian.cast<symbolic::Expression>());
-      break;
+      return p;
     }
   }
-  return p;
+  DRAKE_UNREACHABLE();
 }
 
 pair<symbolic::Polynomial, MatrixXDecisionVariable>
```

**Comment by jwnimmer-tri** [comment]
I had another idea.  If we changed the `kSos` definition to `kSos = 1` so that the values were 1..3, then we could unit test using `static_cast<MathematicalProgram::NonnegativePolynomial>(0)` as input, and it would be defined behavior.

**Review by AlexandreAmice — COMMENTED** [review]
Thanks for the advice! I am curious as to why we want `DRAKE_UNREACHABLE()` rather than the error message I added in?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754#-:-NA4lkLxAaNSF0KAXbym:b-ehm7l2)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754#-:-NAKqSgD3GZ-eDzGH8az:bnfp4nl)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 468 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKq8Lr0vzZZKpyEPJi:-NAKq8Lr0vzZZKpyEPJj:b1k0c6i) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.h#L468)):*
> ```objc
>    */
>   enum class NonnegativePolynomial {
>     kSos = 1,    ///< A sum-of-squares polynomial.
> ```

nit Missing explanation (clarity) for why we're skipping zero.
___
*[`solvers/mathematical_program.h` line 469 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKqBV_CumFFM0c02Mz:-NAKqBV_CumFFM0c02N-:b7ks633) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.h#L469)):*
> ```objc
>   enum class NonnegativePolynomial {
>     kSos = 1,    ///< A sum-of-squares polynomial.
>     kSdsos = 2,  ///< A scaled-diagonally dominant sum-of-squares polynomial.
> ```

nit By default, enums count up by one every time.  Writing out all of the values is brittle; we only need the first `= 1` in order to skip zero.
___
*[`solvers/mathematical_program.cc` line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKqJqO3KCv0zj94KXw:-NAKqJqO3KCv0zj94KXx:beu2cio) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.cc#L270)):*
> ```cpp
>   }
>   throw std::runtime_error(
>           "Passed NonnegativePolynomial type that is either unsupported or "
> ```

nit +4 indentation on new line when wrapping an expression, not +8.
___
*[`solvers/mathematical_program.cc` line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKqNWT2e1aCahTZfKk:-NAKqNWT2e1aCahTZfKl:b-f10sbx) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.cc#L270)):*
> ```cpp
>   }
>   throw std::runtime_error(
>           "Passed NonnegativePolynomial type that is either unsupported or "
> ```

nit All values are supported; saying "unsupported" here is misleading.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 468 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKq8Lr0vzZZKpyEPJi:-NAKqThq3UBcr9zAa6DR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.h#L468)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing explanation (clarity) for why we're skipping zero.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 469 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKqBV_CumFFM0c02Mz:-NAKqU6t0IebZUA0v_q9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.h#L469)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit By default, enums count up by one every time.  Writing out all of the values is brittle; we only need the first `= 1` in order to skip zero.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKqJqO3KCv0zj94KXw:-NAKqUnd0u9pjN5HTzG_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.cc#L270)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit +4 indentation on new line when wrapping an expression, not +8.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17754#-NAKqNWT2e1aCahTZfKk:-NAKqVFi-_-evW55XjyY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d001776f69572a1cf5cc15be12d35d7f96c492b9/solvers/mathematical_program.cc#L270)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit All values are supported; saying "unsupported" here is misleading.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17754)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Pull request merged**
