### PR TITLE
[common] Adjust FindResource on installed Drake to chase symlinks

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In case the user had set up any symlinks to help load Drake's runtime libraries, the logic to find the neighboring `$prefix/share` would fail to find the neighbor. Here we add a second attempt to find the `share` tree after resolving all symlinks in the library path. This should only add new capability, not break anything that is already working properly.

This is required for https://github.com/RobotLocomotion/drake-external-examples/pull/286 to work.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21092)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21092#-:-NsEE_OO0d6rnz_WYS_a:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`common/test/resource_tool_installed_test.py` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21092#-NsEEKbBAwsBbFnlEXDT:-NsEEKbBAwsBbFnlEXDU:bo66o6v) ([raw file](https://github.com/RobotLocomotion/drake/blob/2c9635983b5451cc2e938d2ffdf4deb6e7fc6a71/common/test/resource_tool_installed_test.py#L53)):*
> ```Python
>             env=env, stderr=subprocess.STDOUT).strip()
>         self.assertTrue(Path(absolute_path).is_file(),
>                         f"Path does not exist: {absolute_path}")        
> ```

nit trailing white space

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21092#-:-NsEGSo00JBG102InaJC:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21092#-:-NsEQ1ON37xzMHAMRg4J:bnfp4nl)* status: 1 unresolved discussion

___
*[`common/test/resource_tool_installed_test.py` line 40 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21092#-NsEP0Q-CAwRjRm3TvGW:-NsEP0Q-CAwRjRm3TvGX:b-pusbr) ([raw file](https://github.com/RobotLocomotion/drake/blob/510d660f6498ca16d45863360fa6e782fbe9c773/common/test/resource_tool_installed_test.py#L40)):*
> ```Python
>                         f"Path does not exist: {absolute_path}")
> 
>     @unittest.skipIf(sys.platform == "darwin", "Ubuntu only")
> ```

minor:  I don't see why this test is ubuntu-only, since it seems like the feature should work equally well on mac; does this need a comment (here or in the feature source)?

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21092)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Pull request merged**
