### PR TITLE
sphinx: Allow sphinx-build to be missing during fetch

### LINKED ISSUE #14527: Mirror to s3 job fails without Sphinx
Failing job: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-gcc-bazel-continuous-mirror-to-s3/1844/

Sphinx was removed from the provisioned images, see [Slack conversation](https://drakedevelopers.slack.com/archives/C270MN28G/p1610478253294000)

To fix the error immediately, this job needs to move to the unprovisioned images but it should not need the documentation prerequisites.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This allows for `bazel query` to still succeed, even though trying `bazel build` would fail.

Closes #14527.

Also removes a vestigial macOS path for `sphinx-build`.  Since weeks ago, we no longer support sphinx on macOS.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14528)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mirror-to-s3 please

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14528#-:-MQxdmZE8JaDdeALGo-_:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14528#-:-MR082px4rhCegGYIYvT:bnfp4nl)* status: needs at least two assigned reviewers

___
*[tools/workspace/which.bzl, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14528#-MR07u2B5OMTPQ1YEAcs:-MR07u2B5OMTPQ1YEAct:b7qlr1j) ([raw file](https://github.com/robotlocomotion/drake/blob/37ec47934e9951460baec902d233514ef4a8670a/tools/workspace/which.bzl#L21)):*
> ```Starlark
>                 "echo 'ERROR: {}' 1>&2".format(error_message),
>                 "false",
>             ]), executable = True)
> ```

BTW:  This is really slick; I like it.

**Review by ggould-tri — COMMENTED** [review]
+@betsymcphail to make reviewable happy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14528#-:-MR0LCeBDk1PdhZsvena:b-yby33s)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),BetsyMcPhail (waiting on @BetsyMcPhail)

**Pull request merged**
