### PR TITLE
[multibody] Make point contact results store correct geometry data.

### PR DESCRIPTION
**Pull request by joemasterjohn**
Fix for a bug in point contact results introduced by #19349, and noted during review of #20274.

Previously contact results assumed that each `PenetrationAsPointPair` from geometry collision data mapped to a corresponding `DiscreteContactPair` and subsequently a corresponding `PointPairContactInfo` all sharing the same index. When #19349 introduced multibody contact data and results filtering, this assumption was violated. This fix makes the discrete pair store the correct index of its corresponding `PenetrationAsPointPair` so the contact results can reference the correct corresponding geometry collision data. A regression test is added to `joint_locking_test` that checks point contact results keep a correct reference to its corresponding geometry collision data.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@amcastro-tri for feature review, please. r1 contains the contents of #20274 and can be ignored. I will rebase this PR once that merges. All meaningful changes are in r2.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Ngylp_04ss54T115J5-:b3lweta)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Ngym9beEFHypJ-Gy3nO:-Ngym9beEFHypJ-Gy3nP:bs30ici) (no related file):*
Blocking comment to rebase once #20274 merges.

___

**Review by amcastro-tri — COMMENTED** [review]
This is ready to be rebased now that #20274 merged

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Nh71VIT6F2l8phwbjxv:byuixgd)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
Ok, rebased off of master now, PTAL at your convenience.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Nh73Uh07NDtSQBAeVXv:b-urffwn)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
Looking good

> Reviewed 2 of 3 files at r2, 2 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Nh7NwmLD42JiKgPwH0J:bcbvren)* status: 9 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/discrete_contact_pair.h` line 59 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7MqeV7uRwIgE123GX:-Nh7MqeV7uRwIgE123GY:bwfxtyl) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/discrete_contact_pair.h#L59)):*
> ```objc
>    * pair corresponds to. No value if the pair does not correspond to point
>    * contact. */
>   std::optional<int> point_pair_index{};
> ```

unit test this gets properly setup?
___
*[`multibody/plant/discrete_update_manager.cc` line 529 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7NASX5r8BlFHh9pdA:-Nh7NASX5r8BlFHh9pdB:b-804hm9) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/discrete_update_manager.cc#L529)):*
> ```cpp
>     const auto& discrete_pair = discrete_pairs[icontact];
>     const auto& point_pair =
>         point_pairs[discrete_pair.point_pair_index.value()];
> ```

should we at least DRAKE_DEMAND that this index indeed has value?
___
*[`multibody/plant/test/joint_locking_test.cc` line 548 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7L09M-Yhl-YkkBs2x:-Nh7L09N2efxFZa9-SzW:bmq1ckf) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L548)):*
> ```cpp
> // Test that contact results are properly reported. MultibodyPlant will not
> // report contact results between bodies that are either anchored or with all of
> // their dofs locked. However, geometry queries for collision are not filtered.
> ```

I don't understand what you are trying to say with this sentence



_Code quote:_
```cpp
 However, geometry queries for collision are not filtered
```
___
*[`multibody/plant/test/joint_locking_test.cc` line 549 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7L6vO960nEvwJMAlQ:-Nh7L6vO960nEvwJMAlR:bl1h59e) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L549)):*
> ```cpp
> // report contact results between bodies that are either anchored or with all of
> // their dofs locked. However, geometry queries for collision are not filtered.
> // Previously contact results assumed that each point pair collision data mapped
> ```

Rewrite to avoid saying "Previously" and make the text solely focus on the feature or behavior you want to test. There is no point on keeping comments on things we could not do at some point back in the past.



_Code quote:_
```cpp
Previously contact results 
```
___
*[`multibody/plant/test/joint_locking_test.cc` line 577 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7LYBs2PvLyF8IOhlB:-Nh7LYBs2PvLyF8IOhlC:bwhxbaq) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L577)):*
> ```cpp
>       // `PenetrationAsPointPair` from geometry queries.
>       for (int i = 0; i < results.num_point_pair_contacts(); ++i) {
>         auto info = results.point_pair_contact_info(i);
> ```

nit, `const auto&` or better, spell out the type
___
*[`multibody/plant/test/joint_locking_test.cc` line 582 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7LeYD5jLWU_0ymtUm:-Nh7LeYD5jLWU_0ymtUn:b-re3sjx) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L582)):*
> ```cpp
>         const BodyIndex body_B = MultibodyPlantTester::FindBodyByGeometryId(
>             *plant_, info.point_pair().id_B);
>         EXPECT_EQ(body_A, info.bodyA_index());
> ```

is there a documented invariant that'd allow us to expect body to be in this order? I think to make the test robust you'd need to check you have the correct pair, in no particular order.
___
*[`multibody/plant/test/joint_locking_test.cc` line 588 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7Lwhg24gdABuhFuq2:-Nh7Lwhg24gdABuhFuq3:b-k412sb) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L588)):*
> ```cpp
>     } else {
>       EXPECT_EQ(results.num_point_pair_contacts(), 0);
>       EXPECT_EQ(results.num_hydroelastic_contacts(), 2);
> ```

wouldn't we like to test here also that we have the correct pair? as you did with the point contact case?
___
*[`multibody/plant/test/joint_locking_test.cc` line 613 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7MMGpCOa020CvqkZc:-Nh7MMGpCOa020CvqkZd:b-f29lrx) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L613)):*
> ```cpp
>             *plant_, info.point_pair().id_B);
>         EXPECT_EQ(body_A, info.bodyA_index());
>         EXPECT_EQ(body_B, info.bodyB_index());
> ```

ditto comments for the "all unlocked" bodies.
___
*[`multibody/plant/test/joint_locking_test.cc` line 622 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7MT0B66P8yNkbXy_i:-Nh7MT0B66P8yNkbXy_j:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L622)):*
> ```cpp
>   }
> 
>   // Twop spheres locked, expect only one contact result.
> ```

typo



_Suggestion:_
```cpp
Two
```

**Review by joemasterjohn — COMMENTED** [review]
Comments addressed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Nhga16G7g47M5q0fzU3:b-idmig1)* status: 7 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/discrete_contact_pair.h` line 59 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7MqeV7uRwIgE123GX:-NhcpM9TA0xJJDrbSUKK:b-ejx84m) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/discrete_contact_pair.h#L59)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

unit test this gets properly setup?
</blockquote></details>

Done. I added the checks in `compliant_contact_manager_test` where the other members of this struct are checked for correctness.
___
*[`multibody/plant/discrete_update_manager.cc` line 529 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7NASX5r8BlFHh9pdA:-NhcmSJdEf1d_6FGHVOd:bskob22) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/discrete_update_manager.cc#L529)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

should we at least DRAKE_DEMAND that this index indeed has value?
</blockquote></details>

Done. I also added it for the other optional members that should only have value when the discrete pair comes from hydroelastic collision.
___
*[`multibody/plant/test/joint_locking_test.cc` line 548 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7L09M-Yhl-YkkBs2x:-NhcpuBz2Bk6dPpslH78:bh2uyqg) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L548)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't understand what you are trying to say with this sentence
</blockquote></details>

Trying to say that scene graph generates point contact and hydro contact data that multibody plant ignores when considering collision and reporting contact data. We had an assumption before adding the filtering for locked trees that geometry data and contact results were in one-to-one correspondence (the source of the bug this PR fixes). So I'm emphasizing that the discrete pairs / contact results have to store info on which geometry data it was built from. I reworded, so PTAL. 
___
*[`multibody/plant/test/joint_locking_test.cc` line 549 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7L6vO960nEvwJMAlQ:-NhcthToDp5gIBVzcdCs:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L549)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Rewrite to avoid saying "Previously" and make the text solely focus on the feature or behavior you want to test. There is no point on keeping comments on things we could not do at some point back in the past.
</blockquote></details>

Done.
___
*[`multibody/plant/test/joint_locking_test.cc` line 577 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7LYBs2PvLyF8IOhlB:-NhcuLZ-CRJE7Iv9ULG6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L577)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, `const auto&` or better, spell out the type
</blockquote></details>

Done.
___
*[`multibody/plant/test/joint_locking_test.cc` line 582 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7LeYD5jLWU_0ymtUm:-NhcuMOH5qL3qoxGAEeo:b-juywvz) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L582)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is there a documented invariant that'd allow us to expect body to be in this order? I think to make the test robust you'd need to check you have the correct pair, in no particular order.
</blockquote></details>

I don't think it is documented, but it all happens in the `DiscreteUpdateManager`. The `DiscretePair` is created from a `PenetrationAsPointPair` with matching bodyA and bodyB indices. Then the contact result is constructed from the `DiscretePair` also matching bodyA and bodyB indices. So it is invariant for TAMSI and SAP. Continuous contact results are built directly from the point pairs themselves, so it is also invariant there.

I would advocate for just documenting this as an invariant, because having them out of order between the point pair and discrete pair seems more like a defect to me.
___
*[`multibody/plant/test/joint_locking_test.cc` line 588 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7Lwhg24gdABuhFuq2:-NhgUYYq8BkhtI7NQLhC:bhp21xc) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L588)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

wouldn't we like to test here also that we have the correct pair? as you did with the point contact case?
</blockquote></details>

Well the point contact results are storing the `PenetrationAsPointPair` that the result came from, not the `DiscreteContactPair` (I assume that's what you were thinking here). Hydro contact results also don't reference the `DiscreteContactPair`s. Each `DiscreteContactPair` that came from hydro contact generates a `HydroelasticQuadraturePointData` for the result corresponding to the surface it originally came from. And the `HydroelasticQuadraturePointData` just store a face index, so no way to back reference the hydro surface.
___
*[`multibody/plant/test/joint_locking_test.cc` line 613 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7MMGpCOa020CvqkZc:-Nhg_wWJEMI-dykfNweh:b437f5k) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L613)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto comments for the "all unlocked" bodies.
</blockquote></details>

See my comment above and let me know what you think.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 209 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-NhhCb0h2dnhKAQEzzx8:-NhhCb0h2dnhKAQEzzx9:b161h9v) ([raw file](https://github.com/RobotLocomotion/drake/blob/f4bb71762dce708d0926b82bb3eae24e90318944/multibody/plant/test/compliant_contact_manager_test.cc#L209)):*
> ```cpp
> 
>         // Check the optional parameters are set correctly for point contact.
>         EXPECT_TRUE(point_pair.point_pair_index.has_value());
> ```

should we check the actual value as well?



_Code quote:_
```cpp
.point_pair_index.has_value());
```
___
*[`multibody/plant/test/joint_locking_test.cc` line 548 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7L09M-Yhl-YkkBs2x:-NhhBA9L40nUV6ot4C8w:b-msy2wj) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L548)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Trying to say that scene graph generates point contact and hydro contact data that multibody plant ignores when considering collision and reporting contact data. We had an assumption before adding the filtering for locked trees that geometry data and contact results were in one-to-one correspondence (the source of the bug this PR fixes). So I'm emphasizing that the discrete pairs / contact results have to store info on which geometry data it was built from. I reworded, so PTAL.
</blockquote></details>

ah, my problem was the overload of "filtering", which makes me think of scene graph collision filtering. The re-write is clear now. Thanks
___
*[`multibody/plant/test/joint_locking_test.cc` line 582 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7LeYD5jLWU_0ymtUm:-NhhBoq6CFjPywpYIFeJ:besasrx) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L582)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I don't think it is documented, but it all happens in the `DiscreteUpdateManager`. The `DiscretePair` is created from a `PenetrationAsPointPair` with matching bodyA and bodyB indices. Then the contact result is constructed from the `DiscretePair` also matching bodyA and bodyB indices. So it is invariant for TAMSI and SAP. Continuous contact results are built directly from the point pairs themselves, so it is also invariant there.

I would advocate for just documenting this as an invariant, because having them out of order between the point pair and discrete pair seems more like a defect to me.
</blockquote></details>

I see, I agree with you. 
___
*[`multibody/plant/test/joint_locking_test.cc` line 588 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7Lwhg24gdABuhFuq2:-NhhC3zn6Gp4Od5f9Ceo:b-s622lo) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L588)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Well the point contact results are storing the `PenetrationAsPointPair` that the result came from, not the `DiscreteContactPair` (I assume that's what you were thinking here). Hydro contact results also don't reference the `DiscreteContactPair`s. Each `DiscreteContactPair` that came from hydro contact generates a `HydroelasticQuadraturePointData` for the result corresponding to the surface it originally came from. And the `HydroelasticQuadraturePointData` just store a face index, so no way to back reference the hydro surface.
</blockquote></details>

I see, thanks
___
*[`multibody/plant/test/joint_locking_test.cc` line 564 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-NhhBYYN24CrNaIDaIhu:-NhhBYYN24CrNaIDaIhv:b-nhn7ok) ([raw file](https://github.com/RobotLocomotion/drake/blob/f4bb71762dce708d0926b82bb3eae24e90318944/multibody/plant/test/joint_locking_test.cc#L564)):*
> ```cpp
>   FilteredContactResultsConfig config = GetParam();
> 
>   // All spheres unlocked, expect a two contact results.
> ```

minor,



_Suggestion:_
```cpp
 expect two contact results.
```
___
*[`multibody/plant/test/joint_locking_test.cc` line 593 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-NhhC7O7DQvwagiBoXiq:-NhhC7O7DQvwagiBoXir:b-hvv2d8) ([raw file](https://github.com/RobotLocomotion/drake/blob/f4bb71762dce708d0926b82bb3eae24e90318944/multibody/plant/test/joint_locking_test.cc#L593)):*
> ```cpp
>   }
> 
>   // One body locked, still expect a two contact results.
> ```

minor, 



_Suggestion:_
```cpp
expect two contact results.
```

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

+@sammy-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-NhhCmmK-fiJpDBtmR_E:bdj049j)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
No issues from platform review, waiting on final updates.

> Reviewed 1 of 3 files at r2, 12 of 14 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-NhhH2Pv2agliP-XBW6k:by2gtnx)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 209 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-NhhCb0h2dnhKAQEzzx8:-NhhKjXf8bNfYjN09Hxo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f4bb71762dce708d0926b82bb3eae24e90318944/multibody/plant/test/compliant_contact_manager_test.cc#L209)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

should we check the actual value as well?
</blockquote></details>

Done.
___
*[`multibody/plant/test/joint_locking_test.cc` line 582 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-Nh7LeYD5jLWU_0ymtUm:-NhhOBbP9vvQqCQllSjR:bsnil7k) ([raw file](https://github.com/RobotLocomotion/drake/blob/67f13d98df0bc225b935bad6bc021eb91cb450c9/multibody/plant/test/joint_locking_test.cc#L582)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see, I agree with you.
</blockquote></details>

Ok, I added some documentation to both `DiscreteContactPair` and `PointPairContactInfo` to note the invariant.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 11 of 14 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378)* status: LGTM missing from assignee sammy-tri(platform)

**Review by joemasterjohn — COMMENTED** [review]
All comments addressed, PTAL at your convenience @sammy-tri. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Ni01b7_2kZym9JoRZKo:bt8jl92)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20378#-:-Ni17kKB4TOmtWeR6Wnu:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri

**Pull request merged**
