### PR TITLE
Remove 2023-03 deprecations

### LINKED ISSUE #18915: Deprecation removals 2023-03 [systems]
The deprecation removals for #18106 have come due.  This is a tracking ticket to finish the work.

If you would be so kind, please also roll the tiny #18319 removal into the same PR.

### LINKED ISSUE #18916: Deprecation removals 2023-03 [multibody]
The deprecation removals for #18198 and #18170 have come due.  This is a tracking ticket to finish the work.

### PR DESCRIPTION
**Pull request by sherm1**
Removes all the 2023-03 deprecations I can find.

Resolves #18915
Resolves #18916

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sammy-tri for both reviews per rotation, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-:-NPYTAqyEVe_MV4kjGyr:b-1z3b8l)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
No issues, waiting on final approval until I test the port name deprecations locally.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-:-NPYzFwTDbM6BKbQnbbV:bk0mdai)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I missed an undated chunk of test code :(
Fixed and restarted CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-:-NPZE7Ic7_u2djo8QCe_:bpub0fn)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-NPZG_lf-tb503UDipHc:-NPZG_lf-tb503UDipHd:b1v665b) (no related file):*
@sammy-tri Maybe this is what you meant by your note, but see Anzu-master-Drake-PR build 187.  Anzu is sill using the deprecated port name.  We need someone on deck to push that fix now, before we merge this PR. Would you like to give it a spin?

I see you opened a PR also.  So you'll see what I mean ;)

___

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-NPZG_lf-tb503UDipHc:-NPZINNTCvL0DboEHpTj:bgn0ctn) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sammy-tri Maybe this is what you meant by your note, but see Anzu-master-Drake-PR build 187.  Anzu is sill using the deprecated port name.  We need someone on deck to push that fix now, before we merge this PR. Would you like to give it a spin?

I see you opened a PR also.  So you'll see what I mean ;)
</blockquote></details>

I believe I'm close to turning my "test" PR into a "fix" PR, so yes I'll work on that.

___

**Review by sherm1 — COMMENTED** [review]
Yay! CI is finally green.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-:-NPZdUAY9t3OymwuHo65:bp3apsf)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-NPZG_lf-tb503UDipHc:-NPcCVNJD4ndh90A2oPV:bqr5o9k) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I believe I'm close to turning my "test" PR into a "fix" PR, so yes I'll work on that.
</blockquote></details>

Anzu is ready now.

___

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18927#-:-NPrVciJ3N9x19Z9A0e3:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sherm1)

**Pull request merged**
