### PR TITLE
Made RigidBody::com and RigidBody::I Private

### PR DESCRIPTION
**Pull request by liangfok**
Added accessors for this member variable.
Builds upon #2912.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2913)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

**Comment by liangfok** [comment]
This PR passed all CI checks. Thus +@amcastro-tri for feature review and +@sammy-tri for platform review.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOKKDk8RM-roYlYo0zZ:-1631081700)*

**Comment by amcastro-tri** [comment]
a few comments.

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 281 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKYA0PaIZmPQQYgYUX:-KOKYA0PaIZmPQQYgYUY:-1389275092) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L281)):*
> ```objc
> 
>   /**
>    * Sets the spatial rigid body inertia of this rigid body.
> ```

Too many `rigid body`'s here. Consider "Sets the spatial inertia of this rigid body."

---

*[drake/systems/plants/RigidBody.h, line 283 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXsc8MA3sj4HkcseD:-KOKXsc8MA3sj4HkcseE:-1344839198) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L283)):*
> ```objc
>    * Sets the spatial rigid body inertia of this rigid body.
>    */
>   void set_inertia_matrix(const drake::SquareTwistMatrix<double>&
> ```

I would call this `set_spatial_inertia`, which of course is a matrix.

---

*[drake/systems/plants/RigidBody.h, line 287 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKYIy5q3p_Rro7ztaS:-KOKYIy5q3p_Rro7ztaT:-1389275092) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L287)):*
> ```objc
> 
>   /**
>    * Returns the spatial rigid body inertia of this rigid body.
> ```

Too many `rigid body`'s here. Consider "Sets the spatial inertia of this rigid body."

---

*[drake/systems/plants/RigidBody.h, line 289 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKY3_20Z48ivebq6-H:-KOKY3_3BBKp-m9inapm:-937542045) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L289)):*
> ```objc
>    * Returns the spatial rigid body inertia of this rigid body.
>    */
>   const drake::SquareTwistMatrix<double>& get_inertia_matrix()
> ```

I would call this `get_spatial_inertia`

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOKXMaBdJAD0EzWAk_1:549437361) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
> ```objc
> 
>   // The spatial rigid body inertia of this rigid body.
>   drake::SquareTwistMatrix<double> I_;
> ```

Didn't we agree that for mathematical objects like inertia, which we would naturally call `I`, we don't necessarily need the trailing `_`? if so, I'd prefer not having those for math objects. Maybe to have something more `descriptive` we could call it `spatial_inertia`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOKYLY_ggejghnBumCX:513083662)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 281 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKYA0PaIZmPQQYgYUX:-KOKnilAStzmsrad_6xM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L281)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Too many `rigid body`'s here. Consider "Sets the spatial inertia of this rigid body."
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 283 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXsc8MA3sj4HkcseD:-KOKnNeuU9rLNRe2XoHR:1706342915) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L283)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would call this `set_spatial_inertia`, which of course is a matrix.
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 287 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKYIy5q3p_Rro7ztaS:-KOKnfPaxhyxXAnYBNrZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L287)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Too many `rigid body`'s here. Consider "Sets the spatial inertia of this rigid body."
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 289 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKY3_20Z48ivebq6-H:-KOKnp5BTVRvlXUyPzKQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L289)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would call this `get_spatial_inertia`
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOKoCIU_aX9ZIsGo0Fx:2075000043) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Didn't we agree that for mathematical objects like inertia, which we would naturally call `I`, we don't necessarily need the trailing `_`? if so, I'd prefer not having those for math objects. Maybe to have something more `descriptive` we could call it `spatial_inertia`?
</details>
Done. I renamed it to be `spatial_inertia_`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOKoEy0o2VVKJ35sMg0:-1847460630)*

**Comment by sammy-tri** [comment]
:lgtm:  Not merging yet since feature LGTM is still outstanding (as is Jenkins)

---

Reviewed 1 of 7 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOL2qzGUr_8AiPHsEzw:1917248042)*

**Comment by liangfok** [comment]
The Win32 CI failure is due to a network flake. Not rescheduling until after @amcastro-tri provides a feature review.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOL4A_3lEXVa1aK9Bd1:-443322705)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOL560h-LnTu3vqdIEY:-630083634) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I renamed it to be `spatial_inertia_`.
</details>
What I meant is, are we going to trail with '_' all of our mathematical objects?  I would prefer not to.
i.e.:

spatial_inertia_  --> spatial_inertia
center_of_mass_ --> center_of_mass

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOL6dSgF_Gb7zyqjKFQ:518695076) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> What I meant is, are we going to trail with '_' all of our mathematical objects?  I would prefer not to.
> i.e.:
> 
> spatial_inertia_  --> spatial_inertia
> center_of_mass_ --> center_of_mass
</details>
I checked http://drake.mit.edu/code_style_guide.html#clarifications and didn't see any exception to the [all member variable names must end with an underscore](https://google.github.io/styleguide/cppguide.html#Variable_Names) rule.  I created https://github.com/RobotLocomotion/drake/issues/3060 to stimulate discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOL7ZNhDafe9FJ-Sbcu:676863353) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I checked http://drake.mit.edu/code_style_guide.html#clarifications and didn't see any exception to the [all member variable names must end with an underscore](https://google.github.io/styleguide/cppguide.html#Variable_Names) rule.  I created https://github.com/RobotLocomotion/drake/issues/3060 to stimulate discussion.
</details>
I personally would have defected this if the trailing _ were missing.  As Liang says, there's no exception, and I've come to rely on the _ to indicate when I'm seeing a member variable vs. something locally scoped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOL98JL3Gm7OAGnBtMs:377167961) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I personally would have defected this if the trailing _ were missing.  As Liang says, there's no exception, and I've come to rely on the _ to indicate when I'm seeing a member variable vs. something locally scoped.
</details>
I like that @sammy-tri. I just thought we had this discussion for, in particular, mathematical objects like these ones. I thought we had agreed on not having `_` for those. But of course I might be wrong. I'll unblock this anyways since I am not super strong about it. Maybe a good discussion topic for tomorrow's meeting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOL9_rwb2XcZDEaujNQ:1417088721)*

**Comment by liangfok** [comment]
Thanks. @sammy-tri can you override / merge? The Windows CI failure was a network flake.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/systems/plants/RigidBody.h, line 364 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0:-KOLAJZOlnUGxNu6tJp-:2111523796) ([raw file](https://github.com/robotlocomotion/drake/blob/fb37b4dd6ee84073c5c18be3c362064f5fd5ef36/drake/systems/plants/RigidBody.h#L364)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I like that @sammy-tri. I just thought we had this discussion for, in particular, mathematical objects like these ones. I thought we had agreed on not having `_` for those. But of course I might be wrong. I'll unblock this anyways since I am not super strong about it. Maybe a good discussion topic for tomorrow's meeting?
</details>
Done. I've added it to the meeting topics doc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOLANWJwo8owXDJaLhq:1233025257)*

**Comment by sammy-tri** [comment]
I do not appear to have override merge bits.  (I think it's not 100% accurate to say that all platform reviewers are owners as it does in https://github.com/RobotLocomotion/drake/blob/master/drake/doc/developers.rst#code-review )

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOLRvKXRUqe8MSAJu0g:-2015764783)*

**Comment by liangfok** [comment]
OK no problem.

@drake-jenkins-bot retest this please.
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2913#-:-KOLTJ7-BS7Dcxr5e3iS:-1618737574)*

**Pull request merged**
