### PR TITLE
Make generate_obj_test easier to maintain

### PR DESCRIPTION
**Pull request by maddog-tri**
Make generate_obj_test easier to maintain, by moving expected OBJ/MTL results
out of the .cc (as enormous string literals) and into individual `test/data/` files.

It's easier to maintain because one can validate new files generated by the test
(by a viewer, or diff against the original expected result files), and copy new over
old if the differences are acceptable.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6091)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@jwnimmer-tri for feature review please.  This PR is in advance of some PR's which modify the behavior of `maliput::utility::GenerateObjFile()`.

(Thankfully, only bazel tries to build `generate_obj_test`.  Ha!)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-:-Kjz6KvdmaB5kf6wc5kn:b2mf1q9)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-Kjzc1DeH5ECEQdNHTyD:-Kjzc1Df8dFWh2r332JC:b7ltaeq) ([raw file](https://github.com/robotlocomotion/drake/blob/98680ca02e335b2f05e6291bbeefd30679f3b442/drake/automotive/maliput/utility/BUILD#L47)):*
> ```Python
>     name = "test_data",
>     srcs = glob(["test/data/*"]),
> )
> ```

Please add `testonly=1` at an attribute here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-:-Kjzd3EpjMLUtwpiVWZH:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@sherm1 for platform review, please, because a platform reviewer's day is never done.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-Kjzc1DeH5ECEQdNHTyD:-KjzdyujPB9uRa7r5gnp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/98680ca02e335b2f05e6291bbeefd30679f3b442/drake/automotive/maliput/utility/BUILD#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add `testonly=1` at an attribute here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-:-KjzeYPIXZttwGprQv5Z:b6uxm1t)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6091)*

**Comment by jwnimmer-tri** [comment]
@maddog I think its okay to merge this with only my review.  A second review could plausibly still improve the quality, but its a feature-neutral test-only refactor, so the upside can only go so high.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-:-KkEOoo4o3xSoBh4smOg:bflz9js)*

**Comment by maddog-tri** [comment]
Works for me --- I will -@sherm1 but happily roll any latent sherm-feedback into a future PR.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6091#-:-KkEzdqyPSV1VnCMl_pn:b-jgonwb)*

**Pull request merged**
