### PR TITLE
Install Eigen3

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Implement Bazel installation for Eigen3. Fix some bugs in the install framework. Add `--clean` option to install scripts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6144)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
I *think* this is ready, but I am labeling it "do not merge" as I haven't tried actually consuming the installed Eigen yet. However, please feel free to start reviewing.

Actually installing Eigen is fairly straight-forward, and looks a lot like installing LCM. A good chunk of the patch is fixing up little things from #6072 or adding new features (e.g. `--clean` to the install scripts).

FYI, the changes in 5a504588f71d0 are pedantic: they don't produce any observable behavior change, but they're technically more correct. (_More_ pedantically, `LCM_LIBRARIES` was wrong, but no one actually uses that.)

**Comment by jwnimmer-tri** [comment]
Full pass done.  Looks good, but I'll wait on LGTM in case there are more changes from your testing.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/eigen-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTKP_uc6ff2TpSjCUi:-KkTKP_vtsQ3MQ7-wYFT:bgp8zti) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen-create-cps.py#L22)):*
> ```Python
>   "License": ["MPL-2.0", "LGPL-2.1+", "BSD-3-Clause"],
>   "Version": "%(WORLD_VERSION)s.%(MAJOR_VERSION)s.%(MINOR_VERSION)s",
>   "Compat-Version": "%(WORLD_VERSION)s.0.0",
> ```

BTW If this implies that "3.x.y" are interchangeable, then its wrong.  The MAJOR_VERSION changes mean API breaks.

---

*[tools/eigen.BUILD, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTLOIs-Rw5ze-9aoT7:-KkTLOItir9L7n0W_-dl:boyynbu) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen.BUILD#L66)):*
> ```
>         "Eigen3ConfigVersion.cmake",
>     ],
> )
> ```

BTW The prior five rules are relatively similar between LCM and Eigen.  They could probably turn into a shared macro -- though its fine to wait on that until we one or two more examples, to get the shape of it all.

---

*[tools/eigen.BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTLkpH7OLUDxc5lmk4:-KkTLkpH7OLUDxc5lmk5:bf7reug) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen.BUILD#L76)):*
> ```
>     hdr_dest = "include/eigen3",
>     deps = ["install_cmake"],
> )
> ```

OK This phrasing is neat!

---

*[tools/install.py.in, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMIWpkWQ8ckygnjOr:-KkTMIWq4fCbUSWrbMF2:bqx7yxm) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L56)):*
> ```
> 
> 
> def clean(path, parents=[]):
> ```

BTW Unlike skylark, mutable list as argument is often sketchy in vanilla python; I think the code here is correct anyway, but consider `=()` for safety?

---

*[tools/install.py.in, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMezdt7etP9e6QMvs:-KkTMezdt7etP9e6QMvt:bjs1h89) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L85)):*
> ```
>     parser = argparse.ArgumentParser()
>     parser.add_argument('prefix', type=str, help='Install prefix')
>     parser.add_argument('--clean', dest='clean', action='store_true',
> ```

This is a slightly dangerous option; if the use PEBKAC's their homedir into the first positional argument, poof!  Is there some way to make that hazard less likely or impossible?  Perhaps just listing the stale files instead of removing them (and then user can `xargs rm`)?  Or just list them and then ask for a single confirmation before removing?

Possibly the name "clean" is misleading too -- its not going to clean my builddir, its going to remove from my prefix anything it doesn't know about.  Perhaps a longer and more descriptive name would be better, since it should be rarely used anyway (manually, at least)?  Like `--remove-unknown-files-from-prefix`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-:-KkTNPnUL0PAGRgOXn2E:b-jypv09)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/eigen-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTKP_uc6ff2TpSjCUi:-KkVsfS8HP4_HRflCDUs:b-2f71dz) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen-create-cps.py#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If this implies that "3.x.y" are interchangeable, then its wrong.  The MAJOR_VERSION changes mean API breaks.
</blockquote></details>

I copied what the existing `Eigen3ConfigVersion.cmake` does (AFAICT). Are you saying this is wrong? (I could believe that it is...)

IOW, if I "want" 3.1.x, I'd better not try to use 3.2.y?

---

*[tools/eigen.BUILD, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTLOIs-Rw5ze-9aoT7:-KkVswt1FZ0RftQlNsY3:b-3bvqph) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen.BUILD#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The prior five rules are relatively similar between LCM and Eigen.  They could probably turn into a shared macro -- though its fine to wait on that until we one or two more examples, to get the shape of it all.
</blockquote></details>

Hmm... I guess we could have something like:

```
NAME_TBD(
  package = "Eigen3",
  script = "@//tools:eigen-create-cps.py",
  version_file = "Eigen/src/Core/util/Macros.h",
  dest = "lib/cmake/eigen3",
)
```
...?

---

*[tools/install.py.in, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMIWpkWQ8ckygnjOr:-KkVtt7kjiYKJjEkR9Dx:bqlkxgj) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Unlike skylark, mutable list as argument is often sketchy in vanilla python; I think the code here is correct anyway, but consider `=()` for safety?
</blockquote></details>

The argument usually receives a list (e.g. when called recursively); the default is mainly for the convenience of the non-recursive caller. Are you suggesting to also explicitly cast the lists to tuples when this calls itself? (I don't think I've ever written Python code like that, but...)

---

*[tools/install.py.in, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMezdt7etP9e6QMvs:-KkVubs4JEAkqe1MMT-V:b-wbvkrz) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is a slightly dangerous option; if the use PEBKAC's their homedir into the first positional argument, poof!  Is there some way to make that hazard less likely or impossible?  Perhaps just listing the stale files instead of removing them (and then user can `xargs rm`)?  Or just list them and then ask for a single confirmation before removing?

Possibly the name "clean" is misleading too -- its not going to clean my builddir, its going to remove from my prefix anything it doesn't know about.  Perhaps a longer and more descriptive name would be better, since it should be rarely used anyway (manually, at least)?  Like `--remove-unknown-files-from-prefix`?
</blockquote></details>

It's meant as an improvement over `rm -rf $PREFIX; bazel run install -- $PREFIX`, which is something I otherwise do frequently. I think I'd like to think about this more. Since it isn't needed for the other changes (indeed, it's not really *needed*, period), for now I'll pull this commit back out of the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/eigen-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTKP_uc6ff2TpSjCUi:-KkVy50mK1WRMmspirhx:ba6r1qj) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen-create-cps.py#L22)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I copied what the existing `Eigen3ConfigVersion.cmake` does (AFAICT). Are you saying this is wrong? (I could believe that it is...)

IOW, if I "want" 3.1.x, I'd better not try to use 3.2.y?
</blockquote></details>

OK Ah.  Well, I would rather match upstream (even if they are wrong), than to try to "fix" it here.  Withdrawn. 

But FYI: http://eigen.tuxfamily.org/index.php?title=3.3 shows how Eigen 3.3 broke Eigen 3.2's semantics.

---

*[tools/eigen.BUILD, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTLOIs-Rw5ze-9aoT7:-KkVyVePpBcHJbYrlGb5:bu18tma) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen.BUILD#L66)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Hmm... I guess we could have something like:

```
NAME_TBD(
  package = "Eigen3",
  script = "@//tools:eigen-create-cps.py",
  version_file = "Eigen/src/Core/util/Macros.h",
  dest = "lib/cmake/eigen3",
)
```
...?
</blockquote></details>

Yeah.  The structure of the five rules seems to always be the same, but certain parameters vary from library to library.  Passing the novel parameters and then exploding into rules seems like a nice refactor.  But I'm okay to wait if we're not sure whether or the exploded rules are as boilerplate as they seem.

---

*[tools/install.py.in, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMIWpkWQ8ckygnjOr:-KkVxUmu3AqjZmi_YLqp:bmxt2mt) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L56)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

The argument usually receives a list (e.g. when called recursively); the default is mainly for the convenience of the non-recursive caller. Are you suggesting to also explicitly cast the lists to tuples when this calls itself? (I don't think I've ever written Python code like that, but...)
</blockquote></details>

OK Withdrawn (the code got pulled).

http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/#mutable-default-arguments

No, not asking for tuples anywhere else.  But default arguments of list type are aliases, not different values, so if the body of the method ever wrote into it, that would persist for all future calls into the function forever.  By making it a tuple, its immutable so would avoid that hazard.

---

*[tools/install.py.in, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMezdt7etP9e6QMvs:-KkVxIFArpEDgvPKyYDc:b-lx6x77) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L85)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

It's meant as an improvement over `rm -rf $PREFIX; bazel run install -- $PREFIX`, which is something I otherwise do frequently. I think I'd like to think about this more. Since it isn't needed for the other changes (indeed, it's not really *needed*, period), for now I'll pull this commit back out of the PR.
</blockquote></details>

OK Yup, I can definitely appreciate the purpose of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by mwoehlke-kitware** [comment]
Tested with Spartan, seems to work okay!

**Comment by mwoehlke-kitware** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/eigen-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTKP_uc6ff2TpSjCUi:-KkWKSDFt6-1UvL7mOtu:b-n0dee6) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen-create-cps.py#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Ah.  Well, I would rather match upstream (even if they are wrong), than to try to "fix" it here.  Withdrawn. 

But FYI: http://eigen.tuxfamily.org/index.php?title=3.3 shows how Eigen 3.3 broke Eigen 3.2's semantics.
</blockquote></details>

OK. FWIW, I'm fine either way; the upstream behavior is presumably a bug... In fact, I may file an issue against upstream asking for clarification.

---

*[tools/eigen.BUILD, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTLOIs-Rw5ze-9aoT7:-KkWKj8sN9qdDnrtppZb:b-yfbkfw) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen.BUILD#L66)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah.  The structure of the five rules seems to always be the same, but certain parameters vary from library to library.  Passing the novel parameters and then exploding into rules seems like a nice refactor.  But I'm okay to wait if we're not sure whether or the exploded rules are as boilerplate as they seem.
</blockquote></details>

Okay... I think let's hold off on this for the moment; if the next external seems to be following the same pattern, that will be a good time to revisit. (If not, refactoring for only two use cases may be overkill.)

---

*[tools/install.py.in, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTMIWpkWQ8ckygnjOr:-KkWLH8ZA6KFuH-mUa1D:bplqo6v) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/install.py.in#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Withdrawn (the code got pulled).

http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/#mutable-default-arguments

No, not asking for tuples anywhere else.  But default arguments of list type are aliases, not different values, so if the body of the method ever wrote into it, that would persist for all future calls into the function forever.  By making it a tuple, its immutable so would avoid that hazard.
</blockquote></details>

Arf... that's a gotcha all right...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by jamiesnape** [comment]
One minor request, otherwise :lgtm:.

---

Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/eigen.BUILD, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkWLRvblthyZ4bLQJ8h:-KkWLRvblthyZ4bLQJ8i:bs85ekp) ([raw file](https://github.com/robotlocomotion/drake/blob/1627a1b799456bebfeb35e33f4f85f9defbd004a/tools/eigen.BUILD#L4)):*
> ```
> 
> load("@//tools:install.bzl", "install", "install_files")
> load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")
> ```

Add the python_lint function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-:-KkWLbq6RXzhhzG36w_N:b-uj9ner)*

**Comment by jamiesnape** [comment]
Reviewed 6 of 8 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/eigen-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTKP_uc6ff2TpSjCUi:-KkWLqb1jjwsnJIEkNYT:bhxvgix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen-create-cps.py#L22)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

OK. FWIW, I'm fine either way; the upstream behavior is presumably a bug... In fact, I may file an issue against upstream asking for clarification.
</blockquote></details>

Looking at that page, it isn't obvious that 3.3. is *intended* to be source-incompatible with code previously written against 3.2? (Other than the dropped Eigen2 support, anyway...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by mwoehlke-kitware** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/eigen.BUILD, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkWLRvblthyZ4bLQJ8h:-KkWOmrmCPx6fSnKwSBr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1627a1b799456bebfeb35e33f4f85f9defbd004a/tools/eigen.BUILD#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Add the python_lint function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by jwnimmer-tri** [comment]
*[tools/eigen-create-cps.py, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-KkTKP_uc6ff2TpSjCUi:-KkWhzlKz86fcdNFbrHp:b1cnehs) ([raw file](https://github.com/robotlocomotion/drake/blob/a4aceba6989524dad6f4ecf56735e06b8b4aab12/tools/eigen-create-cps.py#L22)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Looking at that page, it isn't obvious that 3.3. is *intended* to be source-incompatible with code previously written against 3.2? (Other than the dropped Eigen2 support, anyway...)
</blockquote></details>

OK Huh, you may be right.  The text with strikethrough there didn't (TTBOMK) used to be strikethrough.  The norm-nan-zero problem actually broke some code, but I could go along with not calling that an API break.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144)*

**Comment by jwnimmer-tri** [comment]
:lgtm:  (Sorry, I thought I'd already posted that.)

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-:-KkWiL_BqHHnQLnfTfPi:b3fnc2x)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6144#-:-KkXMSgVmbmyc3hdIm1c:bnfp4nl)*

**Pull request merged**
