### PR TITLE
Parallelize the GCS Preprocessing Stage

### PR DESCRIPTION
**Pull request by cohnt**
Building off of #21957. Waiting for that to merge, then I'll update and clean this PR up.

One question to think about -- is building all of the programs in memory at once prohibitive? I personally think it is not, based on my experience solving a GCS problem with ~200 sets and ~4000 edges. But if others think of cases where it would be a problem, I can look into some sort of batching, so not all programs are held in memory for the whole time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965)

### CODE REVIEW

**Comment by cohnt** [comment]
This is _almost_ ready for feature review! Just waiting for #22077 to get brought in.

**Comment by cohnt** [comment]
Alright, this one is ready to go! +@russtedrake for feature review or delegation?

I've decided to use batching for now, since I am worried about the cost of constructing a large linear program for every edge in the graph and holding them all in memory at the same time. Even with the overhead this introduces of spinning up threads multiple times, we still get a massive speedup (~10 minutes to ~6 minutes on the aforementioned instances), so I think it's worth adding this version now. Later on, I can come back and implement the for-loop. (I've included a TODO for this.)

**Review by RussTedrake — COMMENTED** [review]
So, I think that once we land #21341, then all of this will go away again. Unless I'm mistaken, the facial reduction LP is a single LP for the entire graph?  Should we consider just waiting for that, instead of adding this complexity?  @AlexandreAmice ? @bernhardpg ?

> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OAxWOnr0DF7herApgkl:bq2f1ve)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
I'm unfamiliar with facial reduction, so I'll defer to their judgement. If that's the case, maybe it's still worth adding this feature for now, and replacing with the single LP later? Unless we're anticipating that feature being ready soon.

**Comment by bernhardpg** [comment]
In [my formulation](https://github.com/bernhardpg/gcs_facial_reduction/blob/main/notebooks/fr_graphs.ipynb), facial reduction amounts to solving a sequence of LPs (which have to be solved sequentially). My implementation is just taking FR in its general conic form and applying it to the LP case. Pablo believed that it should be possible to formulate FR for the LP case as a single program, I haven't looked more into how and if this is indeed possible.

I am not sure of the status of the current FR project, but if this PR is ready to go I'd say to get this in in the meantime.

**Review by AlexandreAmice — COMMENTED** [review]
I think the FR project is going to take a while to get into master and so this could be a good quality of life improvement. That being said, I think we should be sure that we are not introducing API which could change later. I would advocate that this PR only publically introduce `GraphOfConvexSetsOptions::parallelism` so that we can choose to use how much parallelism we want to use at every point in the algorithm. No options related specifically to preprocessing should be added to avoid needing to deprecate anything in the future.

> Reviewed 2 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OB1SQlxCrlOL9wxMjRf:b-r9ojza)* status: 6 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`-- commits` line 55 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1NyCyBLnrYtKLQJgR):*
it might help `Reviewable` if you squashed these.



_Code quote:_
```
New commits in r1 on 10/25/2024 at 5:49 PM:

- 888c8d7 by amice (AlexandreAmice):
  wip

- eb2434f by amice (AlexandreAmice):
  finalize interface

- c5991b0 by cohnt:
  Temporarily disable the parallelism for debugging.

- 29fd3d0 by cohnt:
  Fix a segfault when initial_guesses is unset.

- 7c7032e by cohnt:
  First pass at parallelizing PreprocessShortestPath.

- b2b2b02 by cohnt:
  Update this test to reflect the new error message.

- 04587de by cohnt:
  Bring back the parallelization, revealing the segfault.

- 9d0dd8b by cohnt:
  Fix another segfault.

- 551b607 by cohnt:
  lint

- afd71a3 by cohnt:
  wip

- ee61d65 by cohnt:
  Use the preprocessing solver options even if a specific preprocessing solver is not specified.

- d53642d by cohnt:
  Merge in preprocessing solver options behavior from branch.

- d326546 by cohnt:
  Merge up-to-date version of SolveInParallel.

- bb7f25c by cohnt:
  Move the construction of the preprocessing program to a separate function for better portability.

- cdb81ec by cohnt:
  Hold a limited number of programs in memory at one time.

- 404586a by cohnt:
  Fix bug when inadvertantly trying to preprocess edges into the start and goal vertex.

New commits in r2 on 10/30/2024 at 4:50 PM:

- 2758511: Drop a TODO.

- 439488f: Merge master.
```
___
*[`geometry/optimization/BUILD.bazel` line 205 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OA9B9I4x02vqEeMx:-OB1OA9B9I4x02vqEeMy:b-yxn9bh) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/BUILD.bazel#L205)):*
> ```Starlark
>         "//solvers:solver_interface",
>     ],
> )
> ```

We should take the opportunity to clean this up into interface dependencies (i.e. files included in the header) vs implementation dependencies (i.e. files included in the cc file).



_Suggestion:_
```Starlark
drake_cc_library(
    name = "graph_of_convex_sets",
    srcs = ["graph_of_convex_sets.cc"],
    hdrs = ["graph_of_convex_sets.h"],
    deps = [
        ":convex_set",
        "//common/symbolic:expression",
        "//common:parallelism",
        "//solvers:choose_best_solver",
        "//solvers:create_cost",
        "//solvers:get_program_type",
        "//solvers:mathematical_program_result",
        "//solvers:solver_interface",
    ],
    implementation_deps = [
        "//solvers:mosek_solver",
        "//solvers:solve",
    ]
)
```
___
*[`geometry/optimization/graph_of_convex_sets.h` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OjOh7dULS-h2DgN5:-OB1OjOh7dULS-h2DgN6:b-z61m6v) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L135)):*
> ```objc
>   /** Set the maximum number of preprocessing programs that are constructed in
>    * memory at once. */
>   int preprocessing_parallel_batch_size{1000};
> ```

Specifying when/where parallelism is used in the options is a little too specific about the internal implementation. I'd recommend doing something along the lines.

I wouldn't put in the `preprocessing_parallel_batch_size` as an argument because we will need to deprecate it if/when we do the facial preprocessing `lp`. I think its okay to use a hard-coded value. Again this argument reveals too much about the implementation details.



_Suggestion:_
```objc
  /** Some steps in GCS can be parallelized. This is the maximum number of cores used in all places in the algorithm. */
  Parallelism parallelism{Parallelism::Max()};
```
___
*[`geometry/optimization/graph_of_convex_sets.h` line 857 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1PtBL0lX6VnxZI-tj:-OB1PtBL0lX6VnxZI-tk:b-rtl9ew) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L857)):*
> ```objc
> 
>       const std::map<VertexId, std::vector<int>>& outgoing_edges,
>       VertexId source_id, VertexId target_id) const;
> ```

why copyable unique pointer? Also `prog` is not an input argument so there is no modification happening.

I think you want



_Suggestion:_
```objc
  // Construc the preprocessing program for a given edge.
  solvers::MathematicalProgram
  ConstructPreprocessingProgram(
      EdgeId edge_id,
      const std::map<VertexId, std::vector<int>>& incoming_edges,

      const std::map<VertexId, std::vector<int>>& outgoing_edges,
      VertexId source_id, VertexId target_id) const;
```
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 824 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1Rx4fC_kp_vlxCZjt:-OB1Rx4g6SEtkxBdpsYt:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.cc#L824)):*
> ```cpp
>         (batch_idx + 1) * options.preprocessing_parallel_batch_size, nE);
>     // TODO(cohnt): No longer use pointers here.
>     std::vector<copyable_unique_ptr<MathematicalProgram>> progs;
> ```





_Suggestion:_
```cpp
std::vector<std::unique_ptr<MathematicalProgram> progs;
```
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 838 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1S-Zl69e_yj4G6ipd:-OB1S-Zl69e_yj4G6ipe:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.cc#L838)):*
> ```cpp
>       EdgeId edge_id = idx_to_edge_id.at(i);
>       progs.emplace_back(ConstructPreprocessingProgram(
>           edge_id, incoming_edges, outgoing_edges, source_id, target_id));
> ```





_Suggestion:_
```cpp
      progs.push_back(std::make_unique<MathematicalProgram>(ConstructPreprocessingProgram(
          edge_id, incoming_edges, outgoing_edges, source_id, target_id));
```

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please

I've managed to shoot myself in the foot by not running this test before, so let's try it to be safe.

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please

Also this one

**Review by cohnt — COMMENTED** [review]
-@RussTedrake for feature review
+@AlexandreAmice for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OB6NshiD0JeDw26v0y_:b-5jyb0h)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`-- commits` line 55 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1NyCyBLnrYtKLQJgR):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

it might help `Reviewable` if you squashed these.
</blockquote></details>

I usually prefer to wait and squash the commits at the end, in case I need to go back to test an earlier version. Not sure why Reviewable thought a bunch of changes already on master were from this branch, but I think I've gotten it fixed now.
___
*[`geometry/optimization/BUILD.bazel` line 205 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OA9B9I4x02vqEeMx:-OB6PYzv-rGXdF_He5Yg:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/BUILD.bazel#L205)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We should take the opportunity to clean this up into interface dependencies (i.e. files included in the header) vs implementation dependencies (i.e. files included in the cc file).
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OjOh7dULS-h2DgN5:-OB6Rk-242kk8TjyrJYm:b-5uy31h) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L135)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Specifying when/where parallelism is used in the options is a little too specific about the internal implementation. I'd recommend doing something along the lines.

I wouldn't put in the `preprocessing_parallel_batch_size` as an argument because we will need to deprecate it if/when we do the facial preprocessing `lp`. I think its okay to use a hard-coded value. Again this argument reveals too much about the implementation details.
</blockquote></details>

Sounds good to me! Note that we don't forward this down to the solvers themselves (except when setting kMaxThreads to 1 in SolveInParallel), so I added a note that users need to set kMaxThreads themselves in solver_options if they want that behavior.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 857 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1PtBL0lX6VnxZI-tj:-OB6Ugcl3mdJRD27qFk6:b3jstab) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L857)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

why copyable unique pointer? Also `prog` is not an input argument so there is no modification happening.

I think you want
</blockquote></details>

You can't directly return a MathematicalProgram. I made it a `std::unique_ptr`, which is probably better.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 824 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1Rx4fC_kp_vlxCZjt:-OB6VXtyAYGifKNZWYEG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.cc#L824)):*
> ```cpp
>         (batch_idx + 1) * options.preprocessing_parallel_batch_size, nE);
>     // TODO(cohnt): No longer use pointers here.
>     std::vector<copyable_unique_ptr<MathematicalProgram>> progs;
> ```

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 838 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1S-Zl69e_yj4G6ipd:-OB6VYtw1mpjWArpJZsY:b-qsm11z) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.cc#L838)):*
> ```cpp
>       EdgeId edge_id = idx_to_edge_id.at(i);
>       progs.emplace_back(ConstructPreprocessingProgram(
>           edge_id, incoming_edges, outgoing_edges, source_id, target_id));
> ```

Since ConstructPreprocessingProgram is already returning a `unique_ptr`, this ended up being a little different.

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please

**Review by AlexandreAmice — COMMENTED** [review]
I'd like to get Russ'/other GCS users opinion on this design. I only chimed in since I am familiar with the parallelism code path you wanted to use. 

> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OB6pqZ22pqGzOckq8Dv:b-et5lzx)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OjOh7dULS-h2DgN5:-OB6pVXqAPWw7yJjVLMy:bv23r7l) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L135)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Sounds good to me! Note that we don't forward this down to the solvers themselves (except when setting kMaxThreads to 1 in SolveInParallel), so I added a note that users need to set kMaxThreads themselves in solver_options if they want that behavior.
</blockquote></details>

cc @jwnimmer-tri what do you think? If we have one `Parallelism` option here is it too confusing for it to control only parallelism not related to the solvers?
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 842 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB6pkLH0j084yLwtEtM:-OB6pkLH0j084yLwtEtN:bt1y9rq) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ca64b696d822e03ab19a88621e5e26666f530bd/geometry/optimization/graph_of_convex_sets.cc#L842)):*
> ```cpp
>     int this_batch_end =
>         std::min((batch_idx + 1) * preprocessing_parallel_batch_size, nE);
>     // TODO(cohnt): No longer use pointers here.
> ```

What is this TODO?

**Review by cohnt — COMMENTED** [review]
My bad! -@AlexandreAmice for feature review

Russ, do you want to take this one? Or is there someone else you'd rather have do the review?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OB6umnL0x4HnSYmqypz:b-f9xlhx)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OjOh7dULS-h2DgN5:-OB6uuyMEJ4JX0LPNo_T:b-yz3cxl) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L135)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

cc @jwnimmer-tri what do you think? If we have one `Parallelism` option here is it too confusing for it to control only parallelism not related to the solvers?
</blockquote></details>

Just to provide some additional context that might help, here's what I anticipate the standard use case being:

1. User sets up the program. Set intersections, preprocessing, etc. can all be parallelized by us.
2. User solves the convex relaxation. This is a single, big optimization problem, and we want to let the solver choose how to leverage parallelization and the number of threads to use.
3. User solves many convex restriction problems. The user will likely want to control the level of parallelism here.

Steps 2 and 3 can also be replaced with the mixed-integer optimization, which is another single big optimization problem, where we should let the solver choose how to leverage parallelism.

So my instinct is that we should be leaving parallelism on the individual solvers alone for the most part, except when explicitly using multithreading that we've implemented. But I'm open to hearing other opinions.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 842 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB6pkLH0j084yLwtEtM:-OB707-i5FTJZS7UfHvZ:bjw15rb) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ca64b696d822e03ab19a88621e5e26666f530bd/geometry/optimization/graph_of_convex_sets.cc#L842)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

What is this TODO?
</blockquote></details>

I don't remember, so I've removed it.

**Review by RussTedrake — COMMENTED** [review]
it seems like we still need c++ tests?

> Reviewed 1 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBA_jvyDGEqu-RXBWo5:bg3a971)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OjOh7dULS-h2DgN5:-OB9vlKP5BNsTgdihDBa:bsteb2s) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L135)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Just to provide some additional context that might help, here's what I anticipate the standard use case being:

1. User sets up the program. Set intersections, preprocessing, etc. can all be parallelized by us.
2. User solves the convex relaxation. This is a single, big optimization problem, and we want to let the solver choose how to leverage parallelization and the number of threads to use.
3. User solves many convex restriction problems. The user will likely want to control the level of parallelism here.

Steps 2 and 3 can also be replaced with the mixed-integer optimization, which is another single big optimization problem, where we should let the solver choose how to leverage parallelism.

So my instinct is that we should be leaving parallelism on the individual solvers alone for the most part, except when explicitly using multithreading that we've implemented. But I'm open to hearing other opinions.
</blockquote></details>

imo, I like the currently proposed version.  I like having a single option to set the max number of threads which gets reused, as appropriate, for the different potentially parallizable steps.  
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 744 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBAYOWK5Me9NNzH3H9Z:-OBAYOWK5Me9NNzH3H9_:bjj0s7x) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7b975ae5e6faf03ee70d8127d7f0defb053cbce/geometry/optimization/graph_of_convex_sets.cc#L744)):*
> ```cpp
>   for (const auto& [vertex_id, v] : vertices_) {
>     std::vector<int> Ev_in = incoming_edges[vertex_id];
>     std::vector<int> Ev_out = outgoing_edges[vertex_id];
> ```

was this a bug?  or did the preconditions for this call change so you have to add the find?
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 792 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBAZb248zDmp0BCMlMv:-OBAZb248zDmp0BCMlMw:b-q5n365) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d15682068816f30b72e13b47ada7e82d9b233a8/geometry/optimization/graph_of_convex_sets.cc#L792)):*
> ```cpp
>     VertexId source_id, VertexId target_id,
>     const GraphOfConvexSetsOptions& options) const {
>   if (vertices_.find(source_id) == vertices_.end()) {
> ```

btw -- you can use vertices_.contains(source_id) now; it's up to your preference.

**Review by cohnt — COMMENTED** [review]
Modified a test case to split compare two levels of parallelism.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBCHn4j6ztDN2hjJ6N-:b-gyznu7)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 744 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBAYOWK5Me9NNzH3H9Z:-OBCKRam2TnSQCDGQjkB:b-8hiv9c) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7b975ae5e6faf03ee70d8127d7f0defb053cbce/geometry/optimization/graph_of_convex_sets.cc#L744)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

was this a bug?  or did the preconditions for this call change so you have to add the find?
</blockquote></details>

We can't use `operator[]` because the `std::map` is passed as a const-reference. If we're inspecting a vertex that has no incoming edges, then the map doesn't have an entry for it. Before, an entry would be created and default-initialized as an empty vector. But because it's const, we can't modify it, so instead we keep the map unchanged and manually give an empty vector.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 792 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBAZb248zDmp0BCMlMv:-OBCLJi9ACeFT-6ehNi5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d15682068816f30b72e13b47ada7e82d9b233a8/geometry/optimization/graph_of_convex_sets.cc#L792)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- you can use vertices_.contains(source_id) now; it's up to your preference.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBCYX6zBiLR75wdC6pE:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 744 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBAYOWK5Me9NNzH3H9Z:-OBCYG8E3BCudwIYDCzM:b-amhnel) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7b975ae5e6faf03ee70d8127d7f0defb053cbce/geometry/optimization/graph_of_convex_sets.cc#L744)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

We can't use `operator[]` because the `std::map` is passed as a const-reference. If we're inspecting a vertex that has no incoming edges, then the map doesn't have an entry for it. Before, an entry would be created and default-initialized as an empty vector. But because it's const, we can't modify it, so instead we keep the map unchanged and manually give an empty vector.
</blockquote></details>

Ty.  SGTM.

**Review by cohnt — COMMENTED** [review]
+@RussTedrake for feature review, since reviewable seems unhappy.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBCfKYd-YOE1nm25XQD:b-beuvx4)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 799 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBS96RN3_O1XlbvBblx:-OBS96RN3_O1XlbvBbly:bhu9tk2) ([raw file](https://github.com/RobotLocomotion/drake/blob/51e596b87edea090b4e7ff39b6ebf21f1c5c4d81/bindings/pydrake/geometry/test/optimization_test.py#L799)):*
> ```Python
>         options.preprocessing_solver_options.SetOption(
>             ClpSolver.id(), "log_level", 3)
>         options.parallelism = True
> ```

Does this need a `num_threads` in `BUILD.bazel` to actually test parallelism under python?  Or is this purely a binding-is-valid test so it doesn't matter?

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OB1OjOh7dULS-h2DgN5:-OBSEtsE3emL0zThcINJ:brap9dh) ([raw file](https://github.com/RobotLocomotion/drake/blob/439488f545a344831abab595bbd01e5f980d4d4e/geometry/optimization/graph_of_convex_sets.h#L135)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

imo, I like the currently proposed version.  I like having a single option to set the max number of threads which gets reused, as appropriate, for the different potentially parallizable steps.
</blockquote></details>

Do we have a consensus to go with the current version, then?
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 799 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBS96RN3_O1XlbvBblx:-OBSEWof-rBpRAjGE2vz:bizl862) ([raw file](https://github.com/RobotLocomotion/drake/blob/51e596b87edea090b4e7ff39b6ebf21f1c5c4d81/bindings/pydrake/geometry/test/optimization_test.py#L799)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this need a `num_threads` in `BUILD.bazel` to actually test parallelism under python?  Or is this purely a binding-is-valid test so it doesn't matter?
</blockquote></details>

My understanding is that we just need to check that the bindings are valid in the python tests. I'm not sure how we could programmatically verify that parallelism is being used here.
___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1058 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBSJPLsAPIrXV-0vURS:-OBSJPLt677nbmlytQVt:b-irqunv) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d47174786982986fe7b17c044354e99f5d47a92/bindings/pydrake/geometry/geometry_py_optimization.cc#L1058)):*
> ```cpp
>             cls_doc.SolveShortestPath.doc,
>             // Parallelism may be used when solving, so we must release the GIL.
>             py::call_guard<py::gil_scoped_release>())
> ```

I'm pretty sure we're supposed to do this if a python binding could run multithreaded code behind the scenes?

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 1058 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-OBSJPLsAPIrXV-0vURS:-OBSLUMHES4t1pR7-wEy:b-rm2bhv) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d47174786982986fe7b17c044354e99f5d47a92/bindings/pydrake/geometry/geometry_py_optimization.cc#L1058)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I'm pretty sure we're supposed to do this if a python binding could run multithreaded code behind the scenes?
</blockquote></details>

I believe it's desirable anyway because we could have a long running function.  I'm not an expert, but I think this is probably the right thing to do based on other usage in `pydrake` and some skimming of the docs.  #21957 seems to say the same thing.

I don't think this PR creates any new entry points that need this beyond the ones that you've identified.

**Review by sammy-tri — COMMENTED** [review]
I cleared the last unresolved issue.  Will retest to see if the other parallelism commit affected this somehow.

> Dismissed @AlexandreAmice from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBXX8l1-MnA0wycSJkG:b-13q1s9)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Review by cohnt — COMMENTED** [review]
Looks like no issues from the other parallelism commit?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBa9Joi4SldAX-B7_SX:bjsv6su)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21965#-:-OBaYvttEz8YNMUpiiB4:b1pnxgs)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform)

**Pull request merged**
