### PR TITLE
[workspace] Remove scipy dependency

### LINKED ISSUE #14691: Remove scipy dependency
It is barely used and the code that uses it really should be able to avoid doing so without too much more complexity. We are very disk space constrained on GitHub Actions so every megabyte counts with large dependencies, and Google Colab prefers certain versions of certain dependencies that may or may not align with an Ubuntu provided version.

FYI @RussTedrake @jwnimmer-tri.

### PR DESCRIPTION
**Pull request by svenevs**
Closes #14691.

I cannot re-open #16836 after having force pushed first apparently, hence new PR.

Depends:

- [x] #17570

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-cmake-experimental-release please.

Unprovisioned builds to confirm.

**Review by svenevs — COMMENTED** [review]
+@jwnimmer-tri for feature review please, scipy deprecation window is closed now.  See checklist in #16836, the unresolved being https://github.com/RobotLocomotion/drake/issues/14691#issuecomment-1074213247 -- I don't think it's a problem but worth resurfacing before this is finalized.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559#-:-N6roPVI-PkNvnXGm2Zn:bku0ebm)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by svenevs** [comment]
EEP: `[workspace] Remove scipy dependency.` <-- erroneous period, we discussed that in the past but I didn't notice this one.  PR title updated, squash merge should not have it.

**Review by jwnimmer-tri — COMMENTED** [review]
CI is sad.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559#-:-N6sb1oW73LoKCFd0yU3:bo1kcih)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17559#-N6sb2c6BIZZ1oxY_xeI:-N6sb2c6BIZZ1oxY_xeJ:b-l2veq6) (no related file):*
nit the `//bindings/pydrake/systems:py/trajectory_optimization_test` failure is probably easily solved, by adding `//bindings/pydrake/common/test_utilities:scipy_stub_py` to the deps of that unit test.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17559#-N6sb9DX3d8M4z0MghRN:-N6sb9DX3d8M4z0MghRO:b-k31nvh) (no related file):*
The `//tutorials:py/updating_costs_and_constraints_test` failure is more interesting.  We can probably get the test passing by adding the stub dependency, but that only defers the problem to crashing in the online notebook deployment.

I suspect we'll need to add scipy to our Deepnote setup.  I can circle back here and help with that a bit later on.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17559#-N6sb9DX3d8M4z0MghRN:-N6tQ30Q2R1ZZRHe8Agq:b-3ldy08) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `//tutorials:py/updating_costs_and_constraints_test` failure is more interesting.  We can probably get the test passing by adding the stub dependency, but that only defers the problem to crashing in the online notebook deployment.

I suspect we'll need to add scipy to our Deepnote setup.  I can circle back here and help with that a bit later on.
</blockquote></details>

Actually its even worse than this.  The tutorial isn't doing anything with scipy.sparse on purpose.  Our scipy-ectomy of pydrake.solvers was incomplete.  Stay tuned.

___

**Review by jwnimmer-tri — COMMENTED** [review]
Please rebase atop #17570 and re-launch the unprovisioned test jobs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559#-:-N7b4tFyBkWJIt37N5Qg:b-ouvw6k)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-cmake-experimental-release please.

**Comment by svenevs** [comment]
FWIW #17570 appears to be doing what is desired -- all unprovisioned tests were happy (linux and mac x86_64)!

**Comment by jwnimmer-tri** [comment]
Ready for a rebase.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-cmake-experimental-release please.

For solidarity.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 6 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559#-:-N84hQAODWarhT4Hoirc:b-adicrb)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17559#-:-N84t1f4AJVt9Je0g-Rm:b-uwkowd)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @svenevs)

**Pull request merged**
