### PR TITLE
Rename LeastSquares to Linear System and Add EqualityConstrainedQPSolver

### PR DESCRIPTION
**Pull request by gizatt**
- Splits out the LeastSquaresSolver into its own file (for consistency) and renames  to LinearSystem, as discussed at meeting earlier this week. No significant functionality of that solver was changed.
- Adds a few asserts to the optimization tests to ensure that that solver dispatch works correctly
- Adds an EqualityConstrainedQPSolver to handle Equality-Constrained QPs by transforming them into linear systems and solving with a similar pipeline. (This could, in theory, be part of the LinearSystem solver... but I feel like that muddles the design unnecessarily.)
- Adds a few test cases testing the dispatch and correctness of that EqualityConstrainedQPSolver.

@naveenoid I really hope I'm not clobbering stuff you're doing here -- would love it if you'd help take a look. Same for anyone else who's interested.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2727)

### CODE REVIEW

**Comment by naveenoid** [comment]
@gizatt glad to take a look..although platform review may take a few days due to the long weekend. Meanwhile perhaps you can look into the Jenkins failures? 

Platform (tentative): +@ggould-tri 
Feature :  + (self) -> Cant link my own name so add "+@naveenoid" in your post to let reviewable know.

**Comment by RussTedrake** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/CMakeLists.txt, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfp1PzN8fTOiLEx4aK:-KLfp1Q-kKCWM8-ndJ5a:-1134613720) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/CMakeLists.txt#L34)):*
> ```CMake
> list(APPEND optimization_files MathematicalProgram.cpp MobyLCP.cpp 
>             system_identification.cpp LinearSystemSolver.cpp 
>             EqualityConstrainedQPSolver.cpp)
> ```

i think according to the style guide, these should be linear_system_solver.cc and equality_constrained_QP_solver.cc .  But I'm surprised that the other recently added cpp files don't comply there.  @ggould-tri -- what's your stance?

---

*[drake/solvers/Constraint.h, line 106 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfquIkiA1dr7XWjIHn:-KLfquIljlp0zlpJXGMe:-1491886675) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/Constraint.h#L106)):*
> ```objc
>   virtual Eigen::SparseMatrix<double> GetSparseB() const {
>     return b_.sparseView();
>   }
> ```

I don't see any uses (nor test coverage) for these yet.  Remove them til their needed/used?
I definitely want to think through the SparseMatrix use cases asap.  Not sure if giving back a sparse view of a matrix that's stored as dense is going to be the right way to go, or if we'll want to have a separate sparse constraint type.  This approach might be a great solution since we often aren't worried about the memory, but are worried about the solve times, and if this lets us optimize faster then it's great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727)*

**Comment by naveenoid** [comment]
I will LGTM after all comments are addressed. Jenkins issues seem spurious.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/solvers/Constraint.h, line 103 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfvwR37JrhIHjTojvr:-KLfvwR37JrhIHjTojvs:1449693802) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/Constraint.h#L103)):*
> ```objc
>   virtual Eigen::SparseMatrix<double> GetSparseQ() const {
>     return Q_.sparseView();
>   }
> ```

Echoing the comment below..remove until ready to use.

---

*[drake/solvers/EqualityConstrainedQPSolver.cpp, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfwXSpiG_M_IR4TnKm:-KLfwXSpiG_M_IR4TnKn:824126936) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/EqualityConstrainedQPSolver.cpp#L25)):*
> ```cpp
>   // (see https://www.math.uh.edu/~rohop/fall_06/Chapter3.pdf)
> 
>   // todo: this needs to be tested with sums of quadratic costs
> ```

nit : https://google.github.io/styleguide/cppguide.html#TODO_Comments

---

*[drake/solvers/EqualityConstrainedQPSolver.cpp, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfxEKc-ikg7Xwv-s20:-KLfxEKc-ikg7Xwv-s21:-859568691) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/EqualityConstrainedQPSolver.cpp#L29)):*
> ```cpp
>   // views and don't cover the complete Q matrix together (to see
>   // how this responds to underdetermined situations)
> ```

Perhaps you want to use a DRAKE_ASSERT here to verify only linear equality constraints exist?

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 84 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfz2BHseICG8Lup2C2:-KLfz2BHseICG8Lup2C3:-644978478) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/test/testOptimizationProblem.cpp#L84)):*
> ```cpp
> 
> void CheckSolverType(OptimizationProblem& prog,
>                      std::string desired_solver_name){
> ```

nit : space after argument closing parentheses https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 765 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfzzEZibrb1pk7lnDY:-KLfzzEZibrb1pk7lnDZ:2042534265) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/test/testOptimizationProblem.cpp#L765)):*
> ```cpp
> }
> 
> /** Test how an unconstrained QP is dispatched and solved */
> ```

This test needs documentation. i.e of the equations. 

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 834 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLg-Efutv1e4iUHFMwX:-KLg-Efutv1e4iUHFMwY:-2056396035) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/test/testOptimizationProblem.cpp#L834)):*
> ```cpp
>   // in the unconstrained case, the min is at (1, 1)
>   // but now we're restricted on the line x1 + x2 = 1
>   // so min will be at 0.5, 0.5 instead
> ```

It will help to document this at the start of the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KLg0p5T4GRdrangFc67:1425207900)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by gizatt** [comment]
Comments addressed! Looks like linking our own name worked, but +@naveenoid anyway.

---

Review status: 5 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/CMakeLists.txt, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfp1PzN8fTOiLEx4aK:-KLwDzur6ac_mmZ3-sKc:-12382045) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/CMakeLists.txt#L34)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i think according to the style guide, these should be linear_system_solver.cc and equality_constrained_QP_solver.cc .  But I'm surprised that the other recently added cpp files don't comply there.  @ggould-tri -- what's your stance?
</details>
Waiting on @ggould-tri, might be easier to keep this in line with the existing files and then make a pass to rename things?

---

*[drake/solvers/EqualityConstrainedQPSolver.cpp, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfwXSpiG_M_IR4TnKm:-KLw5jXJEHwfZYiCMjwl:774817358) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/EqualityConstrainedQPSolver.cpp#L25)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> nit : https://google.github.io/styleguide/cppguide.html#TODO_Comments
</details>
Since this todo was out of date anyway, replaced with comment clarifying that the solver doesn't handle underdetermined cases.

---

*[drake/solvers/EqualityConstrainedQPSolver.cpp, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfxEKc-ikg7Xwv-s20:-KLw9HujYQyLGT2ArHIK:890826198) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/EqualityConstrainedQPSolver.cpp#L29)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Perhaps you want to use a DRAKE_ASSERT here to verify only linear equality constraints exist?
</details>
I've added these asserts to both the LinearSystemSolver and EqualityConstrainedQPSolver in line with how it was implemented in MobyLCP (and maybe other solves) -- not an ideal solution, though, as listed in a TODO comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KLwEVA9_SJq_cgzTXzA:-1476783915)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KLzSD8MCu-L4SYsNIim:1417088721)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/CMakeLists.txt, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfp1PzN8fTOiLEx4aK:-KM-gR9Qrz4DZyOT7M2F:5173665) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/CMakeLists.txt#L34)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary>
> Waiting on @ggould-tri, might be easier to keep this in line with the existing files and then make a pass to rename things?
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727)*

**Comment by gizatt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/solvers/Constraint.h, line 103 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfvwR37JrhIHjTojvr:-KM-rgzWp0JsoJ0W7RSo:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/Constraint.h#L103)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Echoing the comment below..remove until ready to use.
</details>
Done.

---

*[drake/solvers/Constraint.h, line 106 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfquIkiA1dr7XWjIHn:-KM-rgJYYpEYVpGounex:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/Constraint.h#L106)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> I don't see any uses (nor test coverage) for these yet.  Remove them til their needed/used?
> I definitely want to think through the SparseMatrix use cases asap.  Not sure if giving back a sparse view of a matrix that's stored as dense is going to be the right way to go, or if we'll want to have a separate sparse constraint type.  This approach might be a great solution since we often aren't worried about the memory, but are worried about the solve times, and if this lets us optimize faster then it's great.
</details>
Done.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 84 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfz2BHseICG8Lup2C2:-KM-rb2d-NQ4UN6xVvDb:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/test/testOptimizationProblem.cpp#L84)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> nit : space after argument closing parentheses https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions
</details>
Done.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 765 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfzzEZibrb1pk7lnDY:-KM-rdPNXMygJwPZ_CvU:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/test/testOptimizationProblem.cpp#L765)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> This test needs documentation. i.e of the equations. 
</details>
Done.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 834 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLg-Efutv1e4iUHFMwX:-KM-reRDUOnNDkY_tyi4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/test/testOptimizationProblem.cpp#L834)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> It will help to document this at the start of the test.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727)*

**Comment by ggould-tri** [comment]
A few stylistic nits.  Otherwise looks excellent; I am eager to see it in.

---

Reviewed 4 of 10 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[drake/solvers/CMakeLists.txt, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfp1PzN8fTOiLEx4aK:-KM-snXInSAwxYqFXlS9:-813444494) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/CMakeLists.txt#L34)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> OK
</details>
New code should adhere to the style guide.  There will at some point be a flag-day conversion of old code, but that is sufficiently expensive that we have been reluctant to commit to it so far.

Some files -- particularly those added early in the simulation group (`MobyLCP` e.g.) -- preferred consistency to correctness.  This was an error and need not be repeated.

---

*[drake/solvers/EqualityConstrainedQPSolver.cpp, line 50 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KM0396Q85sWjaNk6k50:-KM0396Q85sWjaNk6k51:1022488183) ([raw file](https://github.com/robotlocomotion/drake/blob/733647e2d5d450bb3a7b1ca05dcf64dcb84f3a78/drake/solvers/EqualityConstrainedQPSolver.cpp#L50)):*
> ```cpp
> 
>   // assemble the A and b matrices -- first by summing over
>   //   quadratic costs
> ```

BTW, the whitespace here is a bit odd.

---

*[drake/solvers/MathematicalProgram.cpp, line 5 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KM04JpvmPQo9xRLLrUA:-KM04JpvmPQo9xRLLrUB:914017032) ([raw file](https://github.com/robotlocomotion/drake/blob/733647e2d5d450bb3a7b1ca05dcf64dcb84f3a78/drake/solvers/MathematicalProgram.cpp#L5)):*
> ```cpp
> #include "IpoptSolver.h"
> #include "LinearSystemSolver.h"
> #include "EqualityConstrainedQPSolver.h"
> ```

Code conventions prefer alphabetical order here.

---

*[drake/solvers/MathematicalProgram.cpp, line 34 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KM04R5TfSjFhoKexmJ_:-KM04R5TfSjFhoKexmJa:342602144) ([raw file](https://github.com/robotlocomotion/drake/blob/733647e2d5d450bb3a7b1ca05dcf64dcb84f3a78/drake/solvers/MathematicalProgram.cpp#L34)):*
> ```cpp
> 
> // Solver for simple linear systems of equalities
> AttributesSet kLinearSystemSolverCapabilities = kLinearEqualityConstraint;
> ```

Yay!  This makes much more sense.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 800 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KM04tyKBAZMwR_4Wedj:-KM04tyKBAZMwR_4Wedk:-1021263993) ([raw file](https://github.com/robotlocomotion/drake/blob/733647e2d5d450bb3a7b1ca05dcf64dcb84f3a78/drake/solvers/test/testOptimizationProblem.cpp#L800)):*
> ```cpp
>   CheckSolverType(prog, "Equality Constrained QP Solver");
> 
>   // And one more variable and constrain a view into them
> ```

The grammar here is unclear (possibly you wanted 'add' instead of 'and'?).

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 860 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KM055pzryySgjcm2hdr:-KM055pzryySgjcm2hds:-890082102) ([raw file](https://github.com/robotlocomotion/drake/blob/733647e2d5d450bb3a7b1ca05dcf64dcb84f3a78/drake/solvers/test/testOptimizationProblem.cpp#L860)):*
> ```cpp
>                     MatrixCompareType::absolute));
> 
>   // this is an Equality Constrained QP
> ```

Complete sentence; capitalize and punctuate.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 863 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KM05CnH4GVeYnOJIzqg:-KM05CnH4GVeYnOJIzqh:-1021263993) ([raw file](https://github.com/robotlocomotion/drake/blob/733647e2d5d450bb3a7b1ca05dcf64dcb84f3a78/drake/solvers/test/testOptimizationProblem.cpp#L863)):*
> ```cpp
>   CheckSolverType(prog, "Equality Constrained QP Solver");
> 
>   // And one more variable and constrain it in a different way
> ```

The grammar here is unclear (possibly you wanted 'add' instead of 'and'?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KM05QZIM-NG-l3LaiCH:976073164)*

**Comment by gizatt** [comment]
Review status: 3 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/solvers/CMakeLists.txt, line 34 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-KLfp1PzN8fTOiLEx4aK:-KM0CoSgw1NVoTNpAo36:1296549563) ([raw file](https://github.com/robotlocomotion/drake/blob/5c0c25c3ba34077367b94e6ad04e8ed1065c2d8d/drake/solvers/CMakeLists.txt#L34)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> New code should adhere to the style guide.  There will at some point be a flag-day conversion of old code, but that is sufficiently expensive that we have been reluctant to commit to it so far.
> 
> Some files -- particularly those added early in the simulation group (`MobyLCP` e.g.) -- preferred consistency to correctness.  This was an error and need not be repeated.
</details>
Good point. Renamed introduced files, but have left the other files for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727)*

**Comment by gizatt** [comment]
Oh, and other edits acted on. Thanks!

---

Review status: 3 of 10 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KM0IVTh5Yt09keE3ynM:156638390)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KM0MAKfTAVZ5v8PubX2:1417088721)*

**Comment by naveenoid** [comment]
Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2727#-:-KM5wJGi6lVAliSV8qX-:1417088721)*

**Pull request merged**
