### PR TITLE
Adds ability for user to disable launching of steering_command_gui in automotive_demo.py.

### LINKED ISSUE #5291: Need to Update automotive_demo.py with --no-steering-command-driver Option
When launching a simulation with more than one `SimpleCar`, the automatically-launched `steering_command driver.py` does not work because the LCM channel topic on which the `SimpleCar` vehicles are listening is not what the `steering_command_driver.py` expects. Instead of executing multiple `steering_command_driver.py` instances, once for each `SimpleCar`, I think it would make more sense to allow the user to launch them manually. That would allow the user to bind different `steering_command_driver.py` to different keyboards and/or joysticks.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5291.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5304)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

\CC: @rpoyner-tri since this modifies your code.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-:-KdkiGf2bE96ygXxLelt:b-wp320a)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

This would have been a good training PR for the user that wanted it.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdkinULgZG64QsvPXg8:-KdkinULgZG64QsvPXg9:bj2t8k5) ([raw file](https://github.com/robotlocomotion/drake/blob/889a5b2edb88f893b8451d2902a5c6c63d858b7d/drake/automotive/automotive_demo.py#L201)):*
> ```Python
>                         default=True, help="launch drake-visualizer (default)")
>     parser.add_argument("--no_steering_command_gui", action='store_false',
>                         dest='launch_steering_gui', default=True,
> ```

To keep developers sane, the argument name and dest name should be identical (modulo the `no_`) prefix.  So for example `dest=steering_command_gui`, or `--no_launch_steering_gui`, or etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-:-KdkjG3Zs2O8P2fAqYeL:b-3vgzeo)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdkinULgZG64QsvPXg8:-Kdkk15um4P-wnGGwh9i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/889a5b2edb88f893b8451d2902a5c6c63d858b7d/drake/automotive/automotive_demo.py#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To keep developers sane, the argument name and dest name should be identical (modulo the `no_`) prefix.  So for example `dest=steering_command_gui`, or `--no_launch_steering_gui`, or etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdkknsjvaMOqAyUQowd:-KdkknsjvaMOqAyUQowe:b-umjl45) (no related file):*
Actually there are a few things wrong here, so I'm going to back-burner trying to write them all up.  This PR is not a priority, and I am not on-call, so it will get kicked into mid-next-weel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdkknsjvaMOqAyUQowd:-Kdl--BP-3OTO5E_H2ea:b4c9lyr) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually there are a few things wrong here, so I'm going to back-burner trying to write them all up.  This PR is not a priority, and I am not on-call, so it will get kicked into mid-next-weel.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304)*

**Comment by rpoyner-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdlGpU6j92EQtTODcyG:-KdlGpU6j92EQtTODcyH:b-rgceb8) ([raw file](https://github.com/robotlocomotion/drake/blob/e7b268100257589f2a24df8e58593f3ddec2ee03/drake/automotive/automotive_demo.py#L200)):*
> ```Python
>                         dest='launch_visualizer',
>                         default=True, help="launch drake-visualizer (default)")
>     parser.add_argument("--no_steering_command_driver", action='store_false',
> ```

the multi-word separator should be dash, not underscore to maintain consistency with --no-visualizer.

---

*[drake/automotive/automotive_demo.py, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdlHCkStkeyHJrvenq2:-KdlHCkT8DzBL6xDAiCI:bkpnqrt) ([raw file](https://github.com/robotlocomotion/drake/blob/e7b268100257589f2a24df8e58593f3ddec2ee03/drake/automotive/automotive_demo.py#L200)):*
> ```Python
>                         dest='launch_visualizer',
>                         default=True, help="launch drake-visualizer (default)")
>     parser.add_argument("--no_steering_command_driver", action='store_false',
> ```

it's irritating that the new code lexically splits the related --visualizer and --no-visualizer arguments.

---

*[drake/automotive/automotive_demo.py, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdlIBXlzRQZkiK4vROF:-KdlIBXlzRQZkiK4vROG:b-dqi04d) ([raw file](https://github.com/robotlocomotion/drake/blob/e7b268100257589f2a24df8e58593f3ddec2ee03/drake/automotive/automotive_demo.py#L200)):*
> ```Python
>                         dest='launch_visualizer',
>                         default=True, help="launch drake-visualizer (default)")
>     parser.add_argument("--no_steering_command_driver", action='store_false',
> ```

Really, this PR should probably just fully mimic the existing --visualizer/--no-visualizer pattern fully for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304)*

**Comment by jwnimmer-tri** [comment]
Let's require +@rpoyner-tri sign-off on this.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-:-KdlTx3U6K_GkOF3S5Ou:bqcpe7n)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri My LGTM is already posted; once Rick's is satisfied an posts an LGTM this can merge.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-:-Ke0n3_cmUxw1ZOVDM6x:bohgbyg)*

**Comment by liangfok** [comment]
@rpoyner-tri I addressed your comments. PTAL. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdlGpU6j92EQtTODcyG:-Ke1XYckjhLvTRUKsR3z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7b268100257589f2a24df8e58593f3ddec2ee03/drake/automotive/automotive_demo.py#L200)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

the multi-word separator should be dash, not underscore to maintain consistency with --no-visualizer.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_demo.py, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdlHCkStkeyHJrvenq2:-Ke1XZMh0ZQDL0_n_w3n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7b268100257589f2a24df8e58593f3ddec2ee03/drake/automotive/automotive_demo.py#L200)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

it's irritating that the new code lexically splits the related --visualizer and --no-visualizer arguments.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_demo.py, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-KdlIBXlzRQZkiK4vROF:-Ke1X_COBHwaZkm4292O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7b268100257589f2a24df8e58593f3ddec2ee03/drake/automotive/automotive_demo.py#L200)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Really, this PR should probably just fully mimic the existing --visualizer/--no-visualizer pattern fully for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-:-Ke1Xk1H8qYQTVbPwX_D:b-o4rb9q)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5304#-:-Ke3jfzilNnPtQufYDOt:bnfp4nl)*

**Pull request merged**
