### PR TITLE
Update and re-enable drake-visualizer for macOS

### LINKED ISSUE #14650: Explore re-enabling Drake Visualizer on macOS
Drake Visualizer is disabled for at least as long as it takes to transition Drake and VTK 8.2 to Python 3.9 or some alternative solution is found.

Note that getting a Python version and a VTK version that works for Drake Visualizer and coexist with an a VTK version that works for Drake using Python 3.9 is not going to be easy if VTK 8.2 with Python 3.9 does not work. There are not any unit tests of note that make it easy to test that Drake Visualizer is fully functional, and the two Drake-based tests actually make things worse since they currently tie Drake Visualizer to whatever version of Python that Drake is using.

If we do not have a solution by Drake release version 0.28.0, I would suggest not even downloading installing Drake Visualizer.

Relates #14243 and #14605.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #14650.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review and local testing.

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri :lgtm: platform.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769#-:-MVWj_Yb0doTNiShLwG2:b-cy5i)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @jamiesnape and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14769#-MVWjYq6-ICwHzPI00ap:-MVWjYq6-ICwHzPI00aq:b-migtxl) (no related file):*
nit Also needs the two tests un-nerfed at some point:

https://github.com/RobotLocomotion/drake/blob/9f85fdaf4b86f6b11f55b1afcd3897c454691c60/tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py#L12-L15

https://github.com/RobotLocomotion/drake/blob/9f85fdaf4b86f6b11f55b1afcd3897c454691c60/tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py#L13-L16

---

**Comment by jamiesnape** [comment]
Forgot about those. I guess I was really thorough in disabling it... (probably says something about how much I like patching drake-visualizer).

**Review by soonho-tri — COMMENTED** [review]
:lgtm: 

`bazel run //tools:drake_visualizer` works as expected on my mac.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769#-:-MVWte1U31XixmM129Sx:b-rlv11f)* status: 1 unresolved discussion (waiting on @jamiesnape and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769)* status: 1 unresolved discussion (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
I also checked the installed version and that is fine too.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769#-:-MVXA0YtCQYJYihl9aIv:b-4r2cpl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jwnimmer-tri and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14769#-MVWjYq6-ICwHzPI00ap:-MVXA4WABTpNPT4xiFNO:b-tag4pm) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Also needs the two tests un-nerfed at some point:

https://github.com/RobotLocomotion/drake/blob/9f85fdaf4b86f6b11f55b1afcd3897c454691c60/tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py#L12-L15

https://github.com/RobotLocomotion/drake/blob/9f85fdaf4b86f6b11f55b1afcd3897c454691c60/tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py#L13-L16
</blockquote></details>

Done. They pass locally.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape)

**Comment by jamiesnape** [comment]
I think we have time for CI, so

@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14769)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape)

**Comment by jwnimmer-tri** [comment]
The build is still chugging on other tests, but one we care about has already failed: `drake-visualizer --help died with <Signals.SIGABRT: 6>`.

**Comment by jamiesnape** [comment]
That is very strange.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
I suspect CI is outdated with respect to Qt 5. Same version but different formula name (`qt@5`).

**Comment by jwnimmer-tri** [comment]
I think you're right.  The unprovisioned build passed, so it looks like we just need an image update.

**Comment by jamiesnape** [comment]
I just finished updating.

@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Hah!   `//bindings/pydrake:py/geometry_test FAILED` in `test_unimplemented_rendering` is back.  But the visualizer is fine.

**Pull request merged**
