### PR TITLE
Revert "Generalize sysid / PolynomialConstraint to vectors"

### PR DESCRIPTION
**Pull request by jonathan-owens**
Reverts RobotLocomotion/drake#2469

Dear @ggould-tri,

The oncall build cop, @jonathan-owens, believes that your #2469 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration on presubmit, because additional
platforms and tests are built in postsubmit.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/job/linux-clang-continuous-debug/271/changes
https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-continuous-debug/43/changes
https://drake-jenkins.csail.mit.edu/job/mac-clang-continuous-debug/255/changes

Therefore, the build cop has created this revert PR and started a complete
postsubmit build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2492)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
To @sammy-tri for triage.

**Comment by jwnimmer-tri** [comment]
For the record, it looks to me like #1935 would have prevented this from slipping through the pre-submit builders.

**Comment by sammy-tri** [comment]
I have a patch to fix this...  Can we stop this PR from being reverted so I can open one for the fix?

**Comment by jonathan-owens** [comment]
@sammy-tri OK, I will close the PR for now and you can submit your PR.

**Comment by sammy-tri** [comment]
New PR in #2493

**Pull request closed without merging**
