### PR TITLE
Adds documentation to Pendulum.urdf.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5156)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5156#-:-KctF4IN1kFr7oq1W-3g:b-esv3kb)*

**Comment by RussTedrake** [comment]
i don't think that the first part of the documentation adds useful information, and it adds redundancy.  i worry that it is doomed to get out of sync with the source below.  for example, we typically don't document the value of constants.

**Comment by liangfok** [comment]
I see. Here is the thread that served as the original motivation for creating this PR:

https://reviewable.io/reviews/robotlocomotion/drake/4958#-KcruAXuE_LqGfb50JVE

Maybe now that @amcastro-tri agrees that the COM is at Z=-0.5, we don't necessarily need to document it?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5156#-:-KctFIieHNtSOhfoOm5N:bhovb56)*

**Comment by amcastro-tri** [comment]
> I don't think that the first part of the documentation adds useful information, and it adds redundancy. 

I need to agree here. The model is so simple that a quick look tells you what's in there. The confusion was because I apparently didn't care to read the URDF specification carefully. Now that I know exactly what the `<origin>` tag within a `<joint>` actually specifies it is very easy for me to tell what this urdf describes.

The second part describing a limitation of this urdf when computing the center of mass with `RigidBodyTree::centerOfMass()` will undoubtedly go out of sync.

Up to you @liangfok. If you really feel strong about documenting this urdf I would recommend:
 1. Remove this "problem" with "centerOfMass()". It will go out of sync.
 2. Make the description more accurate. With that alone I cannot reproduce in my head what the setup is about. For instance, in what plane is the pendulum swinging? , where is it located?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5156#-:-Kcx0X0uj4A54utPIVJf:b4sgwgp)*

**Comment by liangfok** [comment]
Alright, since the the confusion about what the URDF describes is resolved and questions were raised about the usefulness of both the first and second half of the proposed documentation, I will close this PR.

**Pull request closed without merging**
