### PR TITLE
[gcs] Use pointers for optional arguments

### PR DESCRIPTION
**Pull request by cohnt**
Per a discussion with @xuchenhan-tri in #21723 (and a similar one with @SeanCurtis-TRI in the Drake Developers Slack), we should use pointers instead of `std::optional` for optional arguments when we want to avoid data copying. This PR overhauls several methods of GcsTrajectoryOptimization (and one method of GraphOfConvexSets) where potentially large objects were being copied to use pointers.

Note that Pybind11 does not allow None arguments to be used for arguments of type `std::vector<T>*`, so I think we're stuck using `std::optional` for Python users? Alternatively, I could add additional function overloads?

I've tagged this as a breaking change since the argument types have changed (at least for C++ users).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform review.

Did you want a GCS-adjacent person to also hop on here for feature review, or are you happy with just platform review?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-:-O2zUUXNAbDMNKEjjwnt:b-8p7vj5)* status: 7 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O2zV1_T0DcZrJg2uyGk:bo9dhmb) (no related file):*
> I've tagged this as a breaking change since the argument types have changed ...

The `GraphOfConvexSets` is marked `@experimental`, so in fact there is no breaking change there.  We can do anything we want to that class.

However, `GcsTrajectoryOptimization` **is** Stable API so yes the label is accurate in terms of that class.  On the other hand, see https://drake.mit.edu/stable.html#stable-api: _"On very rare occasions it is impractical, too expensive, or logically unsound to meet the full three month deprecation window. In these cases the change will be announced in the “Breaking changes” section of the release notes."_

Did you investigate what it would take to deprecate the `GcsTrajectoryOptimization` changes?  Is it impractical or expensive?  At first glance, I imagine that keeping the `optional<>` overloads around on GcsTrajOpt, with deprecation markers, forwarding to the pointer-taking functions, would only be ~100 lines of code.

___
___
*[`geometry/optimization/graph_of_convex_sets.h` line 680 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zPcvmAE3ZDgAtHeE_:-O2zPcvnE9YdpiNfn2un:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/geometry/optimization/graph_of_convex_sets.h#L680)):*
> ```objc
> 
>   /** Returns a Graphviz string describing the graph vertices and edges. If
>   `results` is supplied, then the graph will be annotated with the solution
> ```

typo



_Suggestion:_
```objc
`result`
```
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 475 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zQbkXEj1tPhJMRWe8:-O2zQbkXEj1tPhJMRWe9:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L475)):*
> ```objc
> 
>   /** Returns a Graphviz string describing the graph vertices and edges.  If
>   `results` is supplied, then the graph will be annotated with the solution
> ```

typo



_Suggestion:_
```objc
`result`
```
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 477 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zQgHECqaBhWqZ1tbE:-O2zQgHECqaBhWqZ1tbF:bo2gb5n) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L477)):*
> ```objc
>   `results` is supplied, then the graph will be annotated with the solution
>   values.
>   @param show_slacks determines whether the values of the intermediate
> ```

BTW All of these `@param` details seems stale (no longer exist); there is only the `options` struct as the only parameter.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 751 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zSQVnCV8m313rJG7Y:-O2zSQVnCV8m313rJG7Z:b-httsst) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L751)):*
> ```cpp
>          ++edge_idx) {
>       int i = std::get<0>(edges_between_regions->at(edge_idx));
>       int j = std::get<1>(edges_between_regions->at(edge_idx));
> ```

BTW This is a purposeful change from the non-bounds-checked `operator[]` to the bounds-checked `at()`?

The spelling `(*edges_between_regions)[edge_idx]` is available if you wanted to keep the unchecked access.
___
*[`bindings/pydrake/planning/planning_py_trajectory_optimization.cc` line 472 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zTrRx6i9tqTl_XONU:-O2zTrRx6i9tqTl_XONV:basqup8) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/bindings/pydrake/planning/planning_py_trajectory_optimization.cc#L472)):*
> ```cpp
>                 const std::vector<std::pair<int, int>>& edges_between_regions,
>                 int order, double h_min, double h_max, std::string name,
>                 const std::optional<std::vector<Eigen::VectorXd>> edge_offsets)
> ```

nit The newly-added `const` on `edge_offsets` here is inconsistent with everything else pass by-value (e.g., `int order` is not const).
___
*[`bindings/pydrake/planning/planning_py_trajectory_optimization.cc` line 519 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zU9FI2QJh5YcqoB-o:-O2zU9FI2QJh5YcqoB-p:b-3bgjnr) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/bindings/pydrake/planning/planning_py_trajectory_optimization.cc#L519)):*
> ```cpp
>             py_rvp::reference_internal, py::arg("from_subgraph"),
>             py::arg("to_subgraph"), py::arg("subspace") = py::none(),
>             py::arg("edges_between_regions") = nullptr,
> ```

nit Here and the next line, using `nullptr` is inconsistent with both the above where we used `py::none()` and the argument type which is `std::optional<>`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O3--AIOEeJUXwMyFK2B:b-g9rke7) (no related file):*
> I would think `GraphOfConvexSets` would become stable before something that uses it downstream.

I agree that it seems odd.  If y'all want to retroactively add `@experimental` to GcsTrajOpt now, then you could drop the deprecation changes here.  Adding that tag would be a "breaking change", but if it was always _supposed_ to be the case but just never written down, it's fine to write it down now and announce as much in the next release notes.

The deprecation changes seem largely fine, but I'm going to pause reviewing them in case you want to ping people about "experimental" or not first.

___
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 477 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zQgHECqaBhWqZ1tbE:-O3--_6O7_5ikEmiG1dL:b-gxztsp) ([raw file](https://github.com/RobotLocomotion/drake/blob/021baddb7968796d55a2081a0e43b30e6132b75f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L477)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Yeah, it definitely looks like it. I'm not very familiar with what those parameters used to do, so I'm wary of deleting the documentation without understanding it.
</blockquote></details>

Fair enough.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O33gC1sCEMLKGZ09-cP:b5ay2bz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I would think `GraphOfConvexSets` would become stable before something that uses it downstream.

I agree that it seems odd.  If y'all want to retroactively add `@experimental` to GcsTrajOpt now, then you could drop the deprecation changes here.  Adding that tag would be a "breaking change", but if it was always _supposed_ to be the case but just never written down, it's fine to write it down now and announce as much in the next release notes.

The deprecation changes seem largely fine, but I'm going to pause reviewing them in case you want to ping people about "experimental" or not first.
</blockquote></details>

Russ has indicated he definitely would consider GcsTrajectoryOptimization to be experimental, but we ought to mark it more explicitly. Where to I put `@experimental` in the documentation to indicate it as such?

Regardless, I'm completely happy to leave the deprecation warnings in for a couple months, in case it does throw anyone off. Unless there's a rule that we *can't* do deprecation warnings for something tagged as `@experimental`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O33k4Vx-nI1yOipIlo9:bbwyst3) (no related file):*
> Unless there's a rule ...

It's always fine to add the shims.

> Where to I put `@experimental` in the documentation to indicate it as such?

Usually the class overview Doxygen; see e.g. the third paragraph of the GCS class overview Doxygen.

If you want to add it into this PR, that would be fine (and probably better).  Then, it will be okay here that the deprecation shims here cover only 90% of the cases.

___

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O33ogfmDdRpQRwo6_1G:b-y640ka) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Unless there's a rule ...

It's always fine to add the shims.

> Where to I put `@experimental` in the documentation to indicate it as such?

Usually the class overview Doxygen; see e.g. the third paragraph of the GCS class overview Doxygen.

If you want to add it into this PR, that would be fine (and probably better).  Then, it will be okay here that the deprecation shims here cover only 90% of the cases.
</blockquote></details>

Went ahead and added `@experimental` to the class overview Doxygen.

I thought I had gotten everything covered with deprecation warnings -- was there something I had missed? If so, I'd like to go back and add it in.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O33qPjSBm20KCM5n0Mc:bo9tzl1) (no related file):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Went ahead and added `@experimental` to the class overview Doxygen.

I thought I had gotten everything covered with deprecation warnings -- was there something I had missed? If so, I'd like to go back and add it in.
</blockquote></details>

My impression on a quick skim was that C++ call sites that explicitly pass `std::nullopt` or `{}` would fail to compile now.  I'll take a more careful look later tonight.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O2zV1_T0DcZrJg2uyGj:-O34jOL5B5XmCGyrSErs:b-oozcxe) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My impression on a quick skim was that C++ call sites that explicitly pass `std::nullopt` or `{}` would fail to compile now.  I'll take a more careful look later tonight.
</blockquote></details>

Actually it seems fine, I must have misread it earlier.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34j8lHCOSbXI0-Te3N:-O34j8lIC90WbRvrxwgC:bn67nkg) (no related file):*
All of the deprecated C++ overloads need unit tests (in C++).

The new test code will need this stanza around the deprecated call to mute the compilation error:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
...
#pragma GCC diagnostic pop
```

Hopefully the BTWs below can help reduce the total number of new deprecated function bodies, so it's less to test.

___
___
*[`geometry/optimization/graph_of_convex_sets.h` line 714 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34hYma5o6bxG0krAnB:-O34hYma5o6bxG0krAnC:b-kvppvn) ([raw file](https://github.com/RobotLocomotion/drake/blob/b23412c4c9d4fb8f186e4c2aaab4e84b8e93e19f/geometry/optimization/graph_of_convex_sets.h#L714)):*
> ```objc
>       "2024-10-01",
>       "result should be of type const solvers::MathematicalProgramResult*.");
>   std::string GetGraphvizString(
> ```

BTW If you change this overload to have default arguments for each argument except for the first one, I think you can drop the two other prior deprecated overloads.  (The error you saw was probably from defaulting all three, which _would_ be ambiguous versus the non-deprecated code.  But once we have the first `optional<>` in the non-defaulted arguments, that's enough to unique-ify all of the overloads.)
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 505 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34iGeMBa6DcZHkAn01:-O34iGeN2ZqbSxEXrY88:b-eja2z8) ([raw file](https://github.com/RobotLocomotion/drake/blob/b23412c4c9d4fb8f186e4c2aaab4e84b8e93e19f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L505)):*
> ```objc
>   std::string GetGraphvizString(
>       const std::optional<solvers::MathematicalProgramResult>& result,
>       const geometry::optimization::GcsGraphvizOptions& options) const {
> ```

BTW If you change this overload to have default for the second argument, I think you can drop the other deprecated overload.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 650 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34ioOr9M57-YusZ5VI:-O34ioOr9M57-YusZ5VJ:b54ul9x) ([raw file](https://github.com/RobotLocomotion/drake/blob/b23412c4c9d4fb8f186e4c2aaab4e84b8e93e19f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L650)):*
> ```objc
>                    "std::vector<std::pair<int, int>>*, and edge_offsets should "
>                    "be of type const std::vector<Eigen::VectorXd>*.");
>   EdgesBetweenSubgraphs& AddEdges(
> ```

BTW If you change this overload to have default value for the final argument, I think you can drop the prior deprecated overload.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34j8lHCOSbXI0-Te3N:-O39cpPS9KHnJSAgLDp1:b-l6w284) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

All of the deprecated C++ overloads need unit tests (in C++).

The new test code will need this stanza around the deprecated call to mute the compilation error:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
...
#pragma GCC diagnostic pop
```

Hopefully the BTWs below can help reduce the total number of new deprecated function bodies, so it's less to test.
</blockquote></details>

I confess I'm not sure what test cases for the deprecated code should look like. Do we run each method call twice -- once with the original (now-deprecated) version, and once with the new version? Do we just check that deprecation warnings are indeed logged properly?

If you've got a nice example of a PR that added tests for deprecations, that would be super helpful.

___
___
*[`geometry/optimization/graph_of_convex_sets.h` line 714 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34hYma5o6bxG0krAnB:-O39cWYQ1HFxYN1q7TrX:b6zrrk4) ([raw file](https://github.com/RobotLocomotion/drake/blob/b23412c4c9d4fb8f186e4c2aaab4e84b8e93e19f/geometry/optimization/graph_of_convex_sets.h#L714)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you change this overload to have default arguments for each argument except for the first one, I think you can drop the two other prior deprecated overloads.  (The error you saw was probably from defaulting all three, which _would_ be ambiguous versus the non-deprecated code.  But once we have the first `optional<>` in the non-defaulted arguments, that's enough to unique-ify all of the overloads.)
</blockquote></details>

Good catch!
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 505 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34iGeMBa6DcZHkAn01:-O39btvY5ge7QaRSB27S:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b23412c4c9d4fb8f186e4c2aaab4e84b8e93e19f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L505)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you change this overload to have default for the second argument, I think you can drop the other deprecated overload.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 650 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34ioOr9M57-YusZ5VI:-O39eIluDjDkibvFFwp4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b23412c4c9d4fb8f186e4c2aaab4e84b8e93e19f/planning/trajectory_optimization/gcs_trajectory_optimization.h#L650)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If you change this overload to have default value for the final argument, I think you can drop the prior deprecated overload.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34j8lHCOSbXI0-Te3N:-O39imrD2MX1_bEWmfy9:bo29ghd) (no related file):*
Here's an example of the inverse (removing the tests of deprecated code):

https://github.com/RobotLocomotion/drake/pull/21757/files#diff-accbb5f92589abac8417df3ec3be074c054ce9637685b3fea5a9343a809aa0e4

> Do we just check that deprecation warnings are indeed logged properly?

Not really that (nothing will be logged).  The goal is to test that -- at minimum -- the function doesn't crash (and successfully compiles).  Really it's like any other test -- there is a function, and we want to make sure it does its job correctly.  If the function is really trivial, the test can be really thin.  If the deprecation implementation is more complicated, we want to test the complexity.  As platform reviewer, I would be OK with even a 1-line test for each, showing that the code doesn't crash.  These are simple enough that it's unlikely there could be bugs which that test would miss.

___

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O34j8lHCOSbXI0-Te3N:-O39mMoE8LbgIFh5Io2o:b18ovl9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here's an example of the inverse (removing the tests of deprecated code):

https://github.com/RobotLocomotion/drake/pull/21757/files#diff-accbb5f92589abac8417df3ec3be074c054ce9637685b3fea5a9343a809aa0e4

> Do we just check that deprecation warnings are indeed logged properly?

Not really that (nothing will be logged).  The goal is to test that -- at minimum -- the function doesn't crash (and successfully compiles).  Really it's like any other test -- there is a function, and we want to make sure it does its job correctly.  If the function is really trivial, the test can be really thin.  If the deprecation implementation is more complicated, we want to test the complexity.  As platform reviewer, I would be OK with even a 1-line test for each, showing that the code doesn't crash.  These are simple enough that it's unlikely there could be bugs which that test would miss.
</blockquote></details>

Got it. I've added test cases for all the deprecated functions.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
+@russtedrake for feature review, or to indicate that a single reviewer is okay for this PR.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 2 of 5 files at r2, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-:-O3I8-Z3D3KemZuqM_O3:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 255 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O3I76d_Ba2jwlpeMBze:-O3I76d_Ba2jwlpeMBzf:bcsiopf) ([raw file](https://github.com/RobotLocomotion/drake/blob/849fd3c5194d1021582a6e7b7447f5874b1e85e0/planning/trajectory_optimization/gcs_trajectory_optimization.h#L255)):*
> ```objc
>              int order, double h_min, double h_max, std::string name,
>              GcsTrajectoryOptimization* traj_opt,
>              const std::vector<Eigen::VectorXd>* edge_offsets);
> ```

nit: i think, by the style guide, technically the const * should come before the mutable traj_opt pointer?

since this is a private method, we can fix the order of the arguments without deprecation.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 255 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21749#-O3I76d_Ba2jwlpeMBze:-O3IhwtbCaDUh8hDHI-P:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/849fd3c5194d1021582a6e7b7447f5874b1e85e0/planning/trajectory_optimization/gcs_trajectory_optimization.h#L255)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: i think, by the style guide, technically the const * should come before the mutable traj_opt pointer?

since this is a private method, we can fix the order of the arguments without deprecation.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21749)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
