### PR TITLE
adds luenberger observer system + unit test.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4254)

### CODE REVIEW

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/luenberger_observer.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXPydNvkzzeHOYMV-p_:-KXPydNwHldUShgkFhcv:bbizdsw) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L34)):*
> ```objc
>   ///
>   /// Note: Takes ownership of the unique_ptrs to the observed_system and the
>   /// observed_system_context (use std::move when calling this method).
> ```

Doesn't the constructor to this system call std::move in itself? Do we need this replicated on the caller's side?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXQ-bTg9MexK6eFsN1W:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/luenberger_observer.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXPydNvkzzeHOYMV-p_:-KXQRLruWziXhjE1pzaO:bk371ih) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L34)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Doesn't the constructor to this system call std::move in itself? Do we need this replicated on the caller's side?
</details>
I think both are required (somehow the caller has to explicitly confer that he/she is giving up the pointer).  e.g. http://stackoverflow.com/questions/8114276/how-do-i-pass-a-unique-ptr-argument-to-a-constructor-or-a-function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by RussTedrake** [comment]
+@sherm1 for platform review, please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXgeNX2LF1kthZu-g55:bwwp0j0)*

**Comment by RussTedrake** [comment]
-@sherm1 and +@david-german-tri for feature review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXjalP_y2VRW92kmoJu:b-3yoh5a)*

**Comment by liangfok** [comment]
Reviewed 3 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjuM4_XnUCVhJuPUm_:-KXjuM4_XnUCVhJuPUma:bldms2c) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L29)):*
> ```cpp
>   // generalize it).
>   auto x = observed_system_context_->get_continuous_state();
>   DRAKE_DEMAND(x->size() > 0);  // Otherwise there is nothing to estimate
> ```

Missing period at end of sentence.

---

*[drake/systems/estimators/luenberger_observer.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjxjUFQOySTBF4H5sp:-KXjxjUFQOySTBF4H5sq:bha0cz5) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L41)):*
> ```cpp
>   // Output port is the (estimated) state of the observed system.
>   this->DeclareOutputPort(systems::kVectorValued, x->size(),
>                           systems::kContinuousSampling);
> ```

Should there be a second output port that outputs the original output of the observed system (if it exists)? I'm thinking such an output port would be useful for integrating this observer into a `Diagram`.

---

*[drake/systems/estimators/luenberger_observer.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjwUOS0DavDvABJi83:-KXjwUOS0DavDvABJi84:bn6z6zz) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L26)):*
> ```objc
> class LuenbergerObserver : public systems::LeafSystem<T> {
>  public:
>   /// @param observed_system  The forward model for the observer.
> ```

Should document that the observed system must have a maximum of one input port and exactly one output port.

---

*[drake/systems/estimators/luenberger_observer.h, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjvKJLtIfI8NoLEWAN:-KXjvKJMAeeVebXyIsfW:b3n2sz8) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L30)):*
> ```objc
>   /// which we need to evaluate the system.
>   /// @param observer_gain A m-by-n matrix where m is the number of state
>   /// variables in the observed_system, and n is the number of outputs of the
> ```

BTW, for clarity, consider replacing "the observed_system" with "@p observed_system".

(Same for the second instance of "the observed_system" in this sentence.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by david-german-tri** [comment]
Reviewed 10 of 11 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkYrZ-qEpNI_Cksfv2:-KXkYrZ-qEpNI_Cksfv3:bapu7t4) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L17)):*
> ```cpp
>       observer_gain_(observer_gain),
>       observed_system_context_(std::move(observed_system_context)),
>       observed_system_output_(std::move(
> ```

BTW I think this `std::move` is redundant

---

*[drake/systems/estimators/luenberger_observer.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkZTUl-44PRAelsI2u:-KXkZTUl-44PRAelsI2v:bvx2tmt) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L26)):*
> ```cpp
> 
>   // Check that the system is a continuous-time system (only).
>   // TODO(russt): Move this functionality to the System interface (and
> ```

BTW this is #4262, right?  Added a question there.

---

*[drake/systems/estimators/luenberger_observer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkZKUrhWMaZKYc4FKp:-KXkZKUrhWMaZKYc4FKq:b-abw7k5) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L30)):*
> ```cpp
>   auto x = observed_system_context_->get_continuous_state();
>   DRAKE_DEMAND(x->size() > 0);  // Otherwise there is nothing to estimate
>   // TODO(russt/david-german): Need the methods below to exist.
> ```

BTW yes, that's definitely a gap!

---

*[drake/systems/estimators/luenberger_observer.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkaYEqaorCOnWDgM0D:-KXkaYEqaorCOnWDgM0E:bog75wp) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L72)):*
> ```cpp
> 
> template <typename T>
> void LuenbergerObserver<T>::EvalTimeDerivatives(
> ```

I've convinced myself that no hidden state is being used in EvalTimeDerivatives, but it's kind of subtle.  Consider pointing out in a comment that the only data this method reads from `observed_system_*` is data it wrote there, which was computed solely from the `LuenbergerObserver`'s own state and inputs.

---

*[drake/systems/estimators/luenberger_observer.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkY4kw8SIBr7KNNU5f:-KXkY4kxKiTQLz4wswJg:bexbgof) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L33)):*
> ```objc
>   /// observed_system.
>   ///
>   /// Note: Takes ownership of the unique_ptrs to the observed_system and the
> ```

BTW I think this comment goes without saying.  We haven't documented this on the many framework functions that take a `unique_ptr`.

---

*[drake/systems/estimators/luenberger_observer.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkYX4Z3HFD-Dh0JBRu:-KXkYX4_z_R4uHy5V_O8:b-4mqzcj) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L37)):*
> ```objc
>   LuenbergerObserver(
>       std::unique_ptr<systems::System<T>> observed_system,
>       std::unique_ptr<systems::Context<T>> observed_system_context,
> ```

Is this necessary?  Seems like you could just allocate it in the constructor.  Including it as an argument implies that the contents passed in at construction time mean something.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXkbuJMwXAgnmL4aKVE:b-3vc18s) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
> ```cpp
>     //  y = xhat
> 
>     Eigen::Vector3d xhat = Eigen::Vector3d::Random();
> ```

IMO, it would be better form to have one handwritten set of xhat/u/y than ten random ones.  It provides as much test coverage and more clarity, because the test could assert particular constants that were checked outside of Drake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXkfZqr3eq5C1QM6D4m:bpzabxw) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

IMO, it would be better form to have one handwritten set of xhat/u/y than ten random ones.  It provides as much test coverage and more clarity, because the test could assert particular constants that were checked outside of Drake.
</blockquote></details>

Related issue / previous discussion: #2130.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXkjkPrfoDb8CvCCda3:b-g7bhdz) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Related issue / previous discussion: #2130.
</blockquote></details>

@liangfok, the RNG is seeded in this test, so it's at least deterministic, unlike the ones you mention in #2130.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXkk4m44xylMgIiIIle:b-zhikew) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

@liangfok, the RNG is seeded in this test, so it's at least deterministic, unlike the ones you mention in #2130.
</blockquote></details>

Oh great. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkYrZ-qEpNI_Cksfv2:-KXlYdABX8GcF_6hK4_t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L17)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW I think this `std::move` is redundant
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkZTUl-44PRAelsI2u:-KXmwfJnp6Ymj5-ImFc-:b-n05lll) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L26)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW this is #4262, right?  Added a question there.
</blockquote></details>

yup.  discussed in person.  thanks.

---

*[drake/systems/estimators/luenberger_observer.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjuM4_XnUCVhJuPUm_:-KXmxRVy6DEA1RIFmSNo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Missing period at end of sentence.
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkZKUrhWMaZKYc4FKp:-KXn4zCTHYWDqRazH0tc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L30)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW yes, that's definitely a gap!
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjxjUFQOySTBF4H5sp:-KXn-BHTBc7XARI-k3cl:bihmu3r) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L41)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should there be a second output port that outputs the original output of the observed system (if it exists)? I'm thinking such an output port would be useful for integrating this observer into a `Diagram`.
</blockquote></details>

definitely no.  these are the canonical inputs and outputs for an observer.  and it's easy enough to wire up the outputs of the original system to extra blocks in a Diagram.  

---

*[drake/systems/estimators/luenberger_observer.cc, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkaYEqaorCOnWDgM0D:-KXn-k2Oc45AfbfwSV0n:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L72)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I've convinced myself that no hidden state is being used in EvalTimeDerivatives, but it's kind of subtle.  Consider pointing out in a comment that the only data this method reads from `observed_system_*` is data it wrote there, which was computed solely from the `LuenbergerObserver`'s own state and inputs.
</blockquote></details>

Done.  

---

*[drake/systems/estimators/luenberger_observer.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjwUOS0DavDvABJi83:-KXn22DUhQAZsiUfmL-K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should document that the observed system must have a maximum of one input port and exactly one output port.
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.h, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjvKJLtIfI8NoLEWAN:-KXn2KKrL1IoS-LtYqtg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L30)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, for clarity, consider replacing "the observed_system" with "@p observed_system".

(Same for the second instance of "the observed_system" in this sentence.)
</blockquote></details>

Done.

---

*[drake/systems/estimators/luenberger_observer.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkY4kw8SIBr7KNNU5f:-KXn2pFU43cqA5yHq-gi:b-3jkgjq) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L33)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW I think this comment goes without saying.  We haven't documented this on the many framework functions that take a `unique_ptr`.
</blockquote></details>

abbreviated.

---

*[drake/systems/estimators/luenberger_observer.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkYX4Z3HFD-Dh0JBRu:-KXn2t9OCBxbHqR4ibeB:brm0a3a) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L37)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Is this necessary?  Seems like you could just allocate it in the constructor.  Including it as an argument implies that the contents passed in at construction time mean something.
</blockquote></details>

i think it is necessary.  what if the observed system has parameters?

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXn4-UJ38WHh7rMc1B5:b-hesxvm) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Oh great. Thanks.
</blockquote></details>

I'm not sure that I agree, but I've made the change.  Admittedly, we had actually random tests before (which I understand is bad form), but we had a number of hard to find bugs appear by virtue of the build servers hammering on them with random numbers day after day.  Things like (most of) the quaternion conversion corner cases, for instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by liangfok** [comment]
I left a command and two questions.

---

Reviewed 1 of 11 files at r1, 1 of 3 files at r2.
Review status: 9 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjxjUFQOySTBF4H5sp:-KXnDW0iQqwU4rvBfxRK:b-gej9vc) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L41)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

definitely no.  these are the canonical inputs and outputs for an observer.  and it's easy enough to wire up the outputs of the original system to extra blocks in a Diagram.  
</blockquote></details>

I see. I'm concerned because the `LuenbergerObserver` takes ownership of the observed system meaning when the `LuenbergerObserver` is added to a `DiagramBuilder`, the `DiagramBuilder` doesn't actually know that the observed system exists (it's hidden within the `LuenbergerObserver`). Thus, `DiagramBuilder::Connect()` will not work with the observed system. Can the observed system be simultaneously added to both the `DiagramBuilder` and a `LuenbergObserver`? I scanned the unit test and didn't see this coverage for this scenario.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXnCHlnLgP-uRVCzzf2:bvgcxj2) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I'm not sure that I agree, but I've made the change.  Admittedly, we had actually random tests before (which I understand is bad form), but we had a number of hard to find bugs appear by virtue of the build servers hammering on them with random numbers day after day.  Things like (most of) the quaternion conversion corner cases, for instance.
</blockquote></details>

I agree introducing randomness in tests may be a good thing. Maybe the best strategy is to have both deterministic tests and random tests. Deterministic​ tests  _must_ pass pre-merge. Random tests are not necessarily run pre-merge. Instead, they run continuously in the background and automatically file issues when they encounter an error state.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXnEMGXhjdJfhgs8UQE:-KXnEMGXhjdJfhgs8UQF:b-6o8g1q) ([raw file](https://github.com/robotlocomotion/drake/blob/81d1078f3413d8c6366708cb371fb7e40c127521/drake/systems/estimators/test/luenberger_observer_test.cc#L11)):*
> ```cpp
> #include "drake/common/eigen_types.h"
> #include "drake/systems/framework/diagram.h"
> #include "drake/systems/framework/diagram_builder.h"
> ```

BTW, is this used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXnFLkQ2XqGMh5DkKs5:b-iipunl)*

**Comment by liangfok** [comment]
Oops. I meant "comment", not "command". :smile: 

---

Review status: 9 of 11 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXnFSLdhKOLUgIGxjyq:bm8e27v)*

**Comment by liangfok** [comment]
Reviewed 4 of 11 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/sensors/rotary_encoders.h, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXnFlUZAhl7MzFxrwvb:-KXnFlUZAhl7MzFxrwvc:bk44k5v) ([raw file](https://github.com/robotlocomotion/drake/blob/81d1078f3413d8c6366708cb371fb7e40c127521/drake/systems/sensors/rotary_encoders.h#L40)):*
> ```objc
>                  const std::vector<int>& ticks_per_revolution);
> 
>   /// Non-copyable.
> ```

BTW, I don't think this should be a Doxygen comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjxjUFQOySTBF4H5sp:-KXnGXLR-cFdj1tvAY45:b4jyxpd) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L41)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I see. I'm concerned because the `LuenbergerObserver` takes ownership of the observed system meaning when the `LuenbergerObserver` is added to a `DiagramBuilder`, the `DiagramBuilder` doesn't actually know that the observed system exists (it's hidden within the `LuenbergerObserver`). Thus, `DiagramBuilder::Connect()` will not work with the observed system. Can the observed system be simultaneously added to both the `DiagramBuilder` and a `LuenbergObserver`? I scanned the unit test and didn't see this coverage for this scenario.
</blockquote></details>

No.  I have a more complete example in my acrobot PR.  you need to instantiate the plant twice -- once for simulation and once for the observer.  i think that's philosophically the right thing to do (in fact, in many cases our observer model might be different than the model we actually want to simulate, just like the real world will be different).

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXnHC76VJ14JmSxAaPy:b-1n9p3s) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I agree introducing randomness in tests may be a good thing. Maybe the best strategy is to have both deterministic tests and random tests. Deterministic​ tests  _must_ pass pre-merge. Random tests are not necessarily run pre-merge. Instead, they run continuously in the background and automatically file issues when they encounter an error state.
</blockquote></details>

would be a good discussion to have (perhaps at a sim team lunch)

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXnEMGXhjdJfhgs8UQE:-KXnH3DFYzyz8uH88T5M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81d1078f3413d8c6366708cb371fb7e40c127521/drake/systems/estimators/test/luenberger_observer_test.cc#L11)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is this used?
</blockquote></details>

Done.

---

*[drake/systems/sensors/rotary_encoders.h, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXnFlUZAhl7MzFxrwvb:-KXnHNf8EAJRS4Vri16A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81d1078f3413d8c6366708cb371fb7e40c127521/drake/systems/sensors/rotary_encoders.h#L40)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I don't think this should be a Doxygen comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by liangfok** [comment]
:lgtm: pending other open threads and CI.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXjxjUFQOySTBF4H5sp:-KXnIDReZQgO28QvO-z4:b-l45d73) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L41)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

No.  I have a more complete example in my acrobot PR.  you need to instantiate the plant twice -- once for simulation and once for the observer.  i think that's philosophically the right thing to do (in fact, in many cases our observer model might be different than the model we actually want to simulate, just like the real world will be different).
</blockquote></details>

Aha. I see. Thanks!

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXnIPJcPCIGChZdmGJl:b3oe459) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

would be a good discussion to have (perhaps at a sim team lunch)
</blockquote></details>

Great. I've added it to the proposed topic list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXnJGT7aXT0KtaPRqQA:bpavcd6)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXnJPog8GnOHDvF4oKq:-KXnJPog8GnOHDvF4oKr:bts4f67) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L92)):*
> ```cpp
>   observed_system_->EvalTimeDerivatives(*observed_system_context_, derivatives);
> 
>   // Get the measurements
> ```

BTW Missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/estimators/luenberger_observer.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXnJPog8GnOHDvF4oKq:-KXp0l0zwSbnEP9zXQ69:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.cc#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW Missing period at end of sentence.
</blockquote></details>

Done.

---

*[drake/systems/estimators/test/luenberger_observer_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkbuJMwXAgnmL4aKVD:-KXp0jW42UMK4t332Aas:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/test/luenberger_observer_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Great. I've added it to the proposed topic list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/luenberger_observer.h, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-KXkYX4Z3HFD-Dh0JBRu:-KXpbO4tBFeX50Aew_zk:b2mbi9s) ([raw file](https://github.com/robotlocomotion/drake/blob/5f6314a22ed979b35fafc33769386f69c2467610/drake/systems/estimators/luenberger_observer.h#L37)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think it is necessary.  what if the observed system has parameters?
</blockquote></details>

Ah good point!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4254#-:-KXpbiJg0lVYv5aNWIMV:bnfp4nl)*

**Pull request merged**
