### PR TITLE
Factor out AVX2/FMA composition functions

### PR DESCRIPTION
**Pull request by calderpg-tri**
Preparatory step for #17530, factors out AVX2/FMA compositions functions to a separate target.

+@ggould-tri for review, thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752#-:-NA4cpG5-6QPRHgSHoft:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA4bJb74sBoCM8YM9aA:-NA4bJb74sBoCM8YM9aB:be8heip) ([raw file](https://github.com/robotlocomotion/drake/blob/9a6cebdf744e5a3e080880258f8e505a7f090aef/math/fast_pose_composition_functions_avx2_fma.h#L9)):*
> ```objc
> straightforward portable fallback. */
> 
> /* N.B. Do not include code from drake/common here because this file will be
> ```

minor:  I think this statement needs to be a little bit stronger, since any transitive eigen include might invite trouble.

The same probably applies to at least one other header comment of this sort.



_Suggestion:_
```objc
 any other drake headers
```

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @ggould-tri)

___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA4bJb74sBoCM8YM9aA:-NA54Bft6hmOJrSB5pc6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a6cebdf744e5a3e080880258f8e505a7f090aef/math/fast_pose_composition_functions_avx2_fma.h#L9)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  I think this statement needs to be a little bit stronger, since any transitive eigen include might invite trouble.

The same probably applies to at least one other header comment of this sort.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Comment by calderpg-tri** [comment]
+@SeanCurtis-TRI for platform review, thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
Mostly some editorial things -- moving code has changed the context of some of the documentation, creating some false references.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752#-:-NA5GGQw0145_cjLCSH-:bomy4bd)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`math/BUILD.bazel` line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5BX8tCl48HFQlSCSj:-NA5BX8tCl48HFQlSCSk:b1jkm5v) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/BUILD.bazel#L290)):*
> ```Starlark
>         "//tools/cc_toolchain:apple": [],
>         "//conditions:default": [
>             "-DDRAKE_ENABLE_AVX2_FMA",
> ```

BTW I'm hazy on this macro.

The terms "enable" and "disable" sound like it's *possible* to do something, we just choose not to. However, I get the sense that this isn't about choosing to "enable" these instructions, it's really about whether they are *available*.

The distinction strikes me as *particularly* important as the end goal is to build a binary that determines whether it's *enabled* at run time. So, it might be helpful if we don't use the term "enable" for both build time as well as run time.

If this understanding is correct, I'd recommend renaming `DRAKE_ENABLE_AVX2_FMA` to `DRAKE_AVAILABLE_AVX2_FMA` (or some such thing.
___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5CQ7DEl3ziYeVN7f1:-NA5CQ7DEl3ziYeVN7f2:b-w0tc6a) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.h#L6)):*
> ```objc
> Declarations for fast, low-level functions for handling objects stored in small
> matrices with known memory layouts. Ideally these are implemented using
> platform-specific SIMD instructions for speed; however, we always provide a
> ```

nit; Probably worth noting that the portable fallbacks aren't "provided" in *this* file.
___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5D44m3-Rz2K6XkhON:-NA5D44m3-Rz2K6XkhOO:b-db9pvt) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.h#L33)):*
> ```objc
> namespace internal {
> 
> /* Composes two drake::math::RotationMatrix<double> objects as quickly as
> ```

BTW Given that this code is *in* the `drake::math::` namespace, you can probably get away with omitting the full namespaces from the names of `RotationMatrix` and `RigidTransform` from all of this documentation.
___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5DZ_PBFpVoGQIbBfm:-NA5DZ_PBFpVoGQIbBfn:b-6hujex) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.h#L49)):*
> ```objc
> possible, resulting in a new RotationMatrix.
> 
> @note A valid RotationMatrix is orthonormal, and the inverse of an orthonormal
> ```

BTW I'm confused why this is part of header documentation. It seems to be an implementation detail that shouldn't affect anyone using this function. Am I missing something?
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5E63X3Q_OPYozisZ-:-NA5E63X3Q_OPYozisZ0:blnjcpc) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.cc#L22)):*
> ```cpp
> namespace {
> /* Reinterpret user-friendly class names to raw arrays of double. See note above
> as to why these reinterpret_casts are safe. */
> ```

nit: We've lost the "note above" as to cast safety.

I realize the "note", as it is, is in the header file (`fast_pose_composition_functions.h`) and the justification is indirect. It's the one about assuming the structure of `RotationMatrix` and `RigidTransform`.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 373 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5Eanw2hAzdZrDgvl_:-NA5Eanx26LPptyvAE36:bvg1yzo) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.cc#L373)):*
> ```cpp
> }  // namespace
> 
> // See note above as to why these reinterpret_casts are safe.
> ```

nit: Same note here about cross reference to casting safety.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 405 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5F2tYCYb4obdBT5dj:-NA5F2tYCYb4obdBT5dk:b-dr9ado) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.cc#L405)):*
> ```cpp
> namespace {
> void AbortNotEnabledInBuild(const char* func) {
>   std::cerr << "abort: " << func << " is not enabled in build" << std::endl;
> ```

BTW If you buy the argument about the "enable" vs "available" in the macro name, that distinction should probably appear here as well.

**Comment by SeanCurtis-TRI** [comment]
*[`math/BUILD.bazel` line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5BX8tCl48HFQlSCSj:-NA5Kzit8-anyHKLFIZy:b-dnzsye) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/BUILD.bazel#L290)):*
> In the context of this PR...

Does that mean it'll change names in future PRs?

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri and @SeanCurtis-TRI)

___
*[`math/BUILD.bazel` line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5BX8tCl48HFQlSCSj:-NA5MUGu49QDkmfXoTI9:bgptpyv) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/BUILD.bazel#L290)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

> In the context of this PR...

Does that mean it'll change names in future PRs?
</blockquote></details>

The follow-up PR that adds runtime detection can probably remove the Drake define entirely and return to using the built-in `__AVX2__` and `__FMA__` defines since they will only be used inside `fast_pose_composition_functions_avx2_fma.cc` and not be used in two separate targets with different build options.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`math/BUILD.bazel` line 290 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5BX8tCl48HFQlSCSj:-NA5O8M4C1CthQ1RPOgd:bclehqg) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/BUILD.bazel#L290)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

The follow-up PR that adds runtime detection can probably remove the Drake define entirely and return to using the built-in `__AVX2__` and `__FMA__` defines since they will only be used inside `fast_pose_composition_functions_avx2_fma.cc` and not be used in two separate targets with different build options.
</blockquote></details>

That sounds sufficient.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 405 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5F2tYCYb4obdBT5dj:-NA5OXDD14t1KpWRHk1L:b-rkaxrf) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.cc#L405)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW If you buy the argument about the "enable" vs "available" in the macro name, that distinction should probably appear here as well.
</blockquote></details>

Removing as the judgment above indicates a) "enable" is fine for the scope of this PR, b) it will probably be unnecessary going forward.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5CQ7DEl3ziYeVN7f1:-NA5UgPaBe6BtCKpS_wA:b9a9zdq) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.h#L6)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit; Probably worth noting that the portable fallbacks aren't "provided" in *this* file.
</blockquote></details>

Updated to clarify purpose of this file.
___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5D44m3-Rz2K6XkhON:-NA5SFGy6WqOzLO_zDrS:b75egma) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.h#L33)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given that this code is *in* the `drake::math::` namespace, you can probably get away with omitting the full namespaces from the names of `RotationMatrix` and `RigidTransform` from all of this documentation.
</blockquote></details>

This was copied directly from what `fast_pose_composition_functions.h` has, I'd like to keep the two the same.
___
*[`math/fast_pose_composition_functions_avx2_fma.h` line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5DZ_PBFpVoGQIbBfm:-NA5SSPq5rdcIlkjhudD:bdblzdv) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.h#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm confused why this is part of header documentation. It seems to be an implementation detail that shouldn't affect anyone using this function. Am I missing something?
</blockquote></details>

This was copied directly from the equivalent note in `fast_pose_composition_functions.h`.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5E63X3Q_OPYozisZ-:-NA5USKo2GnPBDggMXFj:b-xp2fvc) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.cc#L22)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: We've lost the "note above" as to cast safety.

I realize the "note", as it is, is in the header file (`fast_pose_composition_functions.h`) and the justification is indirect. It's the one about assuming the structure of `RotationMatrix` and `RigidTransform`.
</blockquote></details>

Added the relevant section of the comments in `fast_pose_composition_functions.cc` here.
___
*[`math/fast_pose_composition_functions_avx2_fma.cc` line 373 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17752#-NA5Eanw2hAzdZrDgvl_:-NA5UbIm0zzEErMkycO6:b-q64pkt) ([raw file](https://github.com/robotlocomotion/drake/blob/5bea9b7746a8648487386e7c299238fa2a13decc/math/fast_pose_composition_functions_avx2_fma.cc#L373)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Same note here about cross reference to casting safety.
</blockquote></details>

See above.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: 5 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752#-:-NA5hWDm5nNEXK8kzKYU:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

I'm going to let you squash and massage the commit message.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17752#-:-NA5hajYDx8FS6I3TU8-:b245w8r)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
