### PR TITLE
Use NumTraits::Literal rather than ::Real

### LINKED ISSUE #4427: Simulator<AutoDiffXd>::StepTo assertion
In #4422, we discovered that `Simulator<AutoDiffXd>::StepTo` fails an assertion.  We should enhance the `Simulator<AutoDiffXd>` unit testing to call StepTo, observe that the assertion trips, and then repair the code to work (and possibly adding addition tests).

### PR DESCRIPTION
**Pull request by sherm1**
Replaces two uses of `Eigen::NumTraits<T>::Real with `NumTraits<T>::Literal` where the intention was to get the underlying floating point type. `::Real` actually means "real part" (vs. "imaginary part"). There are several other uses of `::Real` in Drake that appear to be using it correctly.

Enables the AutoDiff test that failed in PR #4422. Upgrades the assertion that failed to a demand. 

Fixes #4427.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4431)

### CODE REVIEW

**Comment by sherm1** [comment]
+@david-german-tri for feature review, please.
+@jwnimmer-tri for platform review per rotation (almost) and because you found the bug.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-:-KYVYyiHqFifdTT_IbZp:bhtx6ef)*

**Comment by sherm1** [comment]
BTW, this is a *tiny* PR!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-:-KYV_sdMpcwH_lx0x4vS:bd1kf6u)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-KYVbHjQEU-XhYhvc7EJ:-KYVbHjQEU-XhYhvc7EK:bg34jxq) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf8ac9cf4009e95df0ddb40ccd5d5978618d9bf/drake/systems/framework/basic_vector.h#L32)):*
> ```objc
>       : values_(VectorX<T>::Constant(
>             size, std::numeric_limits<
>                       typename Eigen::NumTraits<T>::Literal>::quiet_NaN())) {}
> ```

BTW I think the unit test burden for framework code should be the highest in our tree.  Does this deserve unit test coverage?

---

*[drake/systems/framework/leaf_system.h, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-KYVbRSmKFhw3ohygYZl:-KYVbRSmKFhw3ohygYZm:b-51aaqd) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf8ac9cf4009e95df0ddb40ccd5d5978618d9bf/drake/systems/framework/leaf_system.h#L293)):*
> ```objc
>       const Context<T1>& context, UpdateActions<T1>* actions) const {
>     T1 min_time =
>         std::numeric_limits<typename Eigen::NumTraits<T1>::Literal>::infinity();
> ```

BTW I think the unit test burden for framework code should be the highest in our tree.  Does this deserve more specific unit test coverage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-:-KYVbYIhIeUKPGE3_OW1:bnfp4nl)*

**Comment by sherm1** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-KYVbHjQEU-XhYhvc7EJ:-KYVp_XXS4YimwYEhOIg:btyon10) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf8ac9cf4009e95df0ddb40ccd5d5978618d9bf/drake/systems/framework/basic_vector.h#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think the unit test burden for framework code should be the highest in our tree.  Does this deserve unit test coverage?
</blockquote></details>

Done. Not sure if this is what you were thinking of, Jeremy but I think the specific risk here is decoding Eigen's obscure runes. I added a compile-time sanity check that at least serves as better documentation for Literal and formalizes our dependence on that behavior. 

---

*[drake/systems/framework/leaf_system.h, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-KYVbRSmKFhw3ohygYZl:-KYVqxSX2rCs7LaHm0Ta:b-j1dqed) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf8ac9cf4009e95df0ddb40ccd5d5978618d9bf/drake/systems/framework/leaf_system.h#L293)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think the unit test burden for framework code should be the highest in our tree.  Does this deserve more specific unit test coverage?
</blockquote></details>

Done. (See above comment.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4431)*

**Comment by david-german-tri** [comment]
BTW, I tried to work out from #4427 and #4422 which test actually failed and how, but I think the information is lost to the sands of rebasing.  In principle it would be nice to add a test for whatever-that-was, but I don't want to hold up this PR on it, especially since I don't know what I'm asking for.  :lgtm: again, merge at will

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-:-KYVulnRs0ykZTbqCWie:b5jsnfk)*

**Comment by jwnimmer-tri** [comment]
> BTW, I tried to work out from #4427 and #4422 which test actually failed and how ...

It was the `StepTo` call that got added back here to `simulator_test.cc`, and it failed with an assertion in debug mode, which is the assertion promoted to `DEMAND` in this PR.

**Comment by david-german-tri** [comment]
So, `AutoDiffXd::Real` is `AutoDiffXd`, which doesn't have an `infinity`, which screws up calculating the next sample time.  Got it.   That does seem worth a unit test, but I'm more familiar with the relevant LeafSystem tests than anyone else, so I'm happy to take that in a follow-up PR.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4431#-:-KYVxSfsUMCPU8_ADqm1:bi9rurj)*

**Pull request merged**
