### PR TITLE
Adds support for discrete time linear/affine systems.

### PR DESCRIPTION
**Pull request by RussTedrake**
(This is in preparation for implementing linear MPC).

@naveenoid for feature review.
@sammy-tri for platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4401)

### CODE REVIEW

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-:-KYOxfD6B-IhvWrNCYQd:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 4 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-:-KYP3WAV-CFrDdnxL_Uq:bnfp4nl)*

**Comment by sherm1** [comment]
A few BTWs. :lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/linear_system.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-KYP7l227JqDALCBp2cp:-KYP7l231MtNRKw9VsE5:b-8mtn8u) ([raw file](https://github.com/robotlocomotion/drake/blob/f16d8887faf0d1dd1d1c3fa38e9cb1afb74ce217/drake/systems/framework/primitives/linear_system.h#L10)):*
> ```objc
> /// A discrete OR continuous linear system.
> ///
> /// If time_period>0.0, then the affine system will have the following discrete-
> ```

BTW, affine->linear (and below)

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-KYP8aZd45OSueqJJGOH:-KYP8aZd2hUPag3x22tV:b19dga6) ([raw file](https://github.com/robotlocomotion/drake/blob/f16d8887faf0d1dd1d1c3fa38e9cb1afb74ce217/drake/systems/framework/primitives/test/affine_system_test.cc#L164)):*
> ```cpp
> 
>   auto update = system.AllocateDifferenceVariables();
>   system.DoEvalDifferenceUpdates(*context, update.get());
> ```

BTW prefer public interface `EvalDifferenceUpdates()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-:-KYP8su0-gIfN2Psi70x:bjbwqmw)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/linear_system.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-KYP7l227JqDALCBp2cp:-KYQ3WOZ6PNBEncrmNlA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f16d8887faf0d1dd1d1c3fa38e9cb1afb74ce217/drake/systems/framework/primitives/linear_system.h#L10)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, affine->linear (and below)
</blockquote></details>

Done.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4401#-KYP8aZd45OSueqJJGOH:-KYQ3enz7hi6_8HpDkBB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f16d8887faf0d1dd1d1c3fa38e9cb1afb74ce217/drake/systems/framework/primitives/test/affine_system_test.cc#L164)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW prefer public interface `EvalDifferenceUpdates()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4401)*

**Comment by sherm1** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4401)*

**Pull request merged**
