### PR TITLE
add updateConvex method to TSRBM

### PR DESCRIPTION
**Pull request by muherng**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2540)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot: ok to test

(but I have no context for this PR, and am definitely not the right person to review it)

**Comment by amcastro-tri** [comment]
My two cents since I am not that familiar with the Matlab implementation. It seems like this PR introduced a new boolean flag and a method that are never used?

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> @drake-jenkins-bot: ok to test
> 
> 
> 
> (but I have no context for this PR, and am definitely not the right person to review it)
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3k8SXZL9XL3OTweH7:-KK3k8SXZL9XL3OTweH8:2027582872) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L23)):*
> ```objc
>     gurobi_present = false;
>     % convex stuff below
>     update_convex = true;
> ```

where is this new flag used?

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3j1tqLIntvtjPyNts:-KK3j1tqLIntvtjPyNtt:1566304880) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L24)):*
> ```objc
>     % convex stuff below
>     update_convex = true;
>     phi_max = 0.1; % m, max contact force distance
> ```

I don't really know what the intention of this constant is but what I do know is that having hard coded tolerances "with units" is generally a bad idea. Could this be a percentage of some of the robot's reference scale (for instance from the size of the robot's bounding box)

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3jVYdzNNFnZvpJV1P:-KK3jVYdzNNFnZvpJV1Q:1933055599) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L25)):*
> ```objc
>     update_convex = true;
>     phi_max = 0.1; % m, max contact force distance
>     active_threshold = 0.1; % height below which contact forces are calculated
> ```

Does this have units also?

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 211 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3jb0L1qjLSx3TCiQY:-KK3jb0L1qjLSx3TCiQZ:1850344685) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L211)):*
> ```objc
> 
>     
>     function [phiC,normal,V,n,xA,xB,idxA,idxB] = getContactTerms(obj,q,kinsol)
> ```

Where is this new method used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-:-KK3kCqcFHJJwhKAPNdc:-414494407)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test
Welcome to Jenkins 2.0!

**Comment by jamiesnape** [comment]
Ignore the "default" and "continuous-integration/jenkins/pr/mac" builds.

**Comment by jwnimmer-tri** [comment]
@jamiesnape Perhaps you can fix the bot.

**Comment by jamiesnape** [comment]
Looking into it now.

**Comment by jamiesnape** [comment]
Looks like it is happening every time I enable a new job.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please

**Comment by jwnimmer-tri** [comment]
I am going to tag this PR do-not-merge and do-not-review, because it does not pass Jenkins.  Please feel free to remove those labels once that problem is solved.

**Comment by RussTedrake** [comment]
sorry that I didn't see this PR until now, and that it didn't get our proper attention.  i think it's a great addition, and hope you'll come back and help us push it in.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3k8SXZL9XL3OTweH7:-KRFurM-azlRJLM0zGpJ:b-1x9cbv) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> where is this new flag used?
</details>
it is used at the bottom of the changes in TSRBM.m

but it does seem like we can come up with a better name for it.  perhaps use_mujoco_contact_update or use_todorov_contact_update? 

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3jVYdzNNFnZvpJV1P:-KRFv3KLTFfr36oXVNGJ:bjg1ase) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Does this have units also?
</details>
presumably also meters

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 211 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KK3jb0L1qjLSx3TCiQY:-KRFvWdcAxfEj8TBM0Zf:b-wjl6gj) ([raw file](https://github.com/robotlocomotion/drake/blob/45992cc327b0d30a6719319ca192b48ac665cfc2/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L211)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Where is this new method used?
</details>
it's used in the method immediately below. 

---

*[drake/systems/plants/TimeSteppingRigidBodyManipulator.m, line 242 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-KRFw8tmEf_LPP1-bOfL:-KRFw8tnaB_FCDgaiwKq:b-4mqaql) ([raw file](https://github.com/robotlocomotion/drake/blob/59efc207312dfe9941d40f35fccbbe8c3b5523a5/drake/systems/plants/TimeSteppingRigidBodyManipulator.m#L242)):*
> ```objc
>    
>     function [xdn,df] = updateConvex(obj,h,x,u,w)
>       % this function implement an update based on Todorov 2011, where
> ```

could we add a slightly more complete reference?  
i believe it's this paper: https://pdfs.semanticscholar.org/3e67/7b1fa07d66f539f8086046779190694327eb.pdf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2540#-:-KRFwoYONldgNU5OVo-e:b7i00z8)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2540)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jwnimmer-tri** [comment]
I'm adding the "do not review" label because this PR hasn't passed jenkins recently or received any updates recently.  Please feel free to remove the label if and when work resumes on this PR.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by RussTedrake** [comment]
@kuindersma -- will close this until/unless we see some action from your side.  :(

**Comment by kuindersma** [comment]
No problem. I don't have time to revise it now, so it's fine to close.

**Pull request closed without merging**
