### PR TITLE
[multibody] Move all benchmarks into one place

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
These were all written prior to our guidance to add benchmarks using a certain folder structure.

See https://github.com/jwnimmer-tri/drake/blob/mv-cassie/multibody/benchmarking/README.md for markup preview.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17526)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17526)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/benchmarking/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17526#-N6Tb1qs1trVM4jlJh_i:-N6Tb1qs1trVM4jlJh_j:b-1d481n) ([raw file](https://github.com/robotlocomotion/drake/blob/9a4f3290a61cdd66898b742a8ce27026ae9422d1/multibody/benchmarking/BUILD.bazel#L1)):*
> ```Starlark
> # -*- python -*-
> ```

I don't see any test rules. What's the proposal to stave off bitrot?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17526)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[`multibody/benchmarking/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17526#-N6Tb1qs1trVM4jlJh_i:-N6TcCnsCfCSjGUDc-hT:b-hj6bcn) ([raw file](https://github.com/robotlocomotion/drake/blob/9a4f3290a61cdd66898b742a8ce27026ae9422d1/multibody/benchmarking/BUILD.bazel#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I don't see any test rules. What's the proposal to stave off bitrot?
</blockquote></details>

The `drake_cc_googlebench_binary` macro unconditionally adds a smoke test.

Maybe we should change the macro to have an argument `add_test_rule = True` so that it's clear here at the call site what's going on?

(The macro would fail-fast for any value other than "True".  It's only goal would be for force the clarity syntax here.)

WDYT?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17526)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/benchmarking/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17526#-N6Tb1qs1trVM4jlJh_i:-N6Tck5C8bjiahJBE_bn:b-e5hu0h) ([raw file](https://github.com/robotlocomotion/drake/blob/9a4f3290a61cdd66898b742a8ce27026ae9422d1/multibody/benchmarking/BUILD.bazel#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `drake_cc_googlebench_binary` macro unconditionally adds a smoke test.

Maybe we should change the macro to have an argument `add_test_rule = True` so that it's clear here at the call site what's going on?

(The macro would fail-fast for any value other than "True".  It's only goal would be for force the clarity syntax here.)

WDYT?
</blockquote></details>

Fine as is, I guess. Have to get used to drake_ bazel rules being full of magic.

**Pull request merged**
