### PR TITLE
[workspace] Update pybind11 to include python@3.11 patches

### PR DESCRIPTION
**Pull request by svenevs**
Relates: https://github.com/RobotLocomotion/pybind11/pull/60, #18262.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18297)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@jwnimmer-tri for review please (part of the other two PRs).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18297#-:-NGXnhQf0CgDjw_9sV7h:b-bm47e1)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
The CI testing choice looks correct.  Once it passes, you can merge the pybind11 PR and then refresh the details here.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) +(release notes: none) pending sha fixup.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18297#-:-NGYCfOx-3BFRZNi_pPU:b-kx74xr)* status: 2 unresolved discussions (waiting on @svenevs)

___
*[`tools/workspace/pybind11/repository.bzl` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18297#-NGYCc1BDhXI86Xm0ga_:-NGYCc1C9mffrXzhibyc:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/d430cdf2dc7a1343d424e5584ae93a9297c2140e/tools/workspace/pybind11/repository.bzl#L7)):*
> ```Starlark
> 
> # Using the `drake` branch of this repository.
> _REPOSITORY = "svenevs/pybind11"
> ```





_Suggestion:_
```Starlark
RobotLocomotion
```
___
*[`tools/workspace/pybind11/repository.bzl` line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18297#-NGYCZmQ-f0cU1MEnvo8:-NGYCZmQ-f0cU1MEnvo9:b45h) ([raw file](https://github.com/robotlocomotion/drake/blob/d430cdf2dc7a1343d424e5584ae93a9297c2140e/tools/workspace/pybind11/repository.bzl#L13)):*
> ```Starlark
> # and if it has changed, then update the version number in the two
> # pybind11-*.cmake files in the current directory to match.
> _COMMIT = "3d90c7d32ea615148e7ec1ac609f773f5580f478"
> ```





_Suggestion:_
```Starlark
36695db542e1c34f6db7ca3ebb0415de30762395
```

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by svenevs — COMMENTED** [review]
Should be good to merge once CI passes (one final sanity check, worth it).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18297#-:-NGYMUyN2JhqlIGWsu1K:b-j5g5db)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/pybind11/repository.bzl` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18297#-NGYCc1BDhXI86Xm0ga_:-NGYMRdRDVfE4raCKINm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d430cdf2dc7a1343d424e5584ae93a9297c2140e/tools/workspace/pybind11/repository.bzl#L7)):*
> ```Starlark
> 
> # Using the `drake` branch of this repository.
> _REPOSITORY = "svenevs/pybind11"
> ```

Done.
___
*[`tools/workspace/pybind11/repository.bzl` line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18297#-NGYCZmQ-f0cU1MEnvo8:-NGYMTHq6yjDF6mlpW38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d430cdf2dc7a1343d424e5584ae93a9297c2140e/tools/workspace/pybind11/repository.bzl#L13)):*
> ```Starlark
> # and if it has changed, then update the version number in the two
> # pybind11-*.cmake files in the current directory to match.
> _COMMIT = "3d90c7d32ea615148e7ec1ac609f773f5580f478"
> ```

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18297)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @svenevs)

**Pull request merged**
