### PR TITLE
Upgrade SCS to 2.0

### PR DESCRIPTION
**Pull request by hongkai-dai**
SCS 2.0 is a lot more accurate than 1.0, the tolerance on our test improves from 1E-1 to 3E-5.

@siyuanfeng-tri and @rdeits , could you try your QP problem with this SCS in this PR? I am still working on adding OSQP to drake, and it might take some time to resolve its build issue.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8046)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jamiesnape for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-:-L5B1Gczx6asvzc6wOzK:ba3u7wa)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/scs_solver.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5C3TKdC3P4C1_MKLkS:-L5C3TKdC3P4C1_MKLkT:b154pwf) ([raw file](https://github.com/robotlocomotion/drake/blob/217d5bbe9f4fcadf5923382aa994736aa58b1ad4/solvers/scs_solver.cc#L9)):*
> ```cpp
> // scs_float, scs_int, etc, defined in scs.h
> #include <scs.h>
> #include "include/cones.h"
> ```

Does simply `<cones.h>` work (same for the two below) since `include` is listed in `includes`?

---

*[solvers/scs_solver.cc, line 518 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5C4CFSWO_FqR-Q5CsB:-L5C4CFSWO_FqR-Q5CsC:b-locw96) ([raw file](https://github.com/robotlocomotion/drake/blob/217d5bbe9f4fcadf5923382aa994736aa58b1ad4/solvers/scs_solver.cc#L518)):*
> ```cpp
>   scs_problem_data->stgs =
>       static_cast<ScsSettings*>(scs_calloc(1, sizeof(ScsSettings)));
>   SCS(set_default_settings)(scs_problem_data);
> ```

BTW I wonder if `scs_*` would be clearer than `SCS(*)` everywhere it is used.

---

*[solvers/test/scs_solver_test.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5C4UtTClfre7qq3Yvv:-L5C4UtTClfre7qq3Yvw:b-m684ol) ([raw file](https://github.com/robotlocomotion/drake/blob/217d5bbe9f4fcadf5923382aa994736aa58b1ad4/solvers/test/scs_solver_test.cc#L43)):*
> ```cpp
>   }
> 
>   // The accuracy of SCS is not high, so we choose 1E-2 here, 10x the
> ```

Comment is no longer (entirely) true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-:-L5C3Iv8jlt5rPLz4D27:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review please.

---

Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/scs_solver.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5C3TKdC3P4C1_MKLkS:-L5ChpY7pHJzcrW_5sfv:bsda42t) ([raw file](https://github.com/robotlocomotion/drake/blob/217d5bbe9f4fcadf5923382aa994736aa58b1ad4/solvers/scs_solver.cc#L9)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Does simply `<cones.h>` work (same for the two below) since `include` is listed in `includes`?
</blockquote></details>

Done. Yes! Using <cones.h> works.

---

*[solvers/scs_solver.cc, line 518 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5C4CFSWO_FqR-Q5CsB:-L5CgNtaSu2bAOIvNOdG:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/217d5bbe9f4fcadf5923382aa994736aa58b1ad4/solvers/scs_solver.cc#L518)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I wonder if `scs_*` would be clearer than `SCS(*)` everywhere it is used.
</blockquote></details>

Done. Good call.

---

*[solvers/test/scs_solver_test.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5C4UtTClfre7qq3Yvv:-L5ChmuFIIfEzvhDjkBa:b-yh10tr) ([raw file](https://github.com/robotlocomotion/drake/blob/217d5bbe9f4fcadf5923382aa994736aa58b1ad4/solvers/test/scs_solver_test.cc#L43)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Comment is no longer (entirely) true.
</blockquote></details>

Done. Good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-:-L5Chupp8btZku6Vh7ku:b-1zm1j3)*

**Comment by siyuanfeng-tri** [comment]
i tried it briefly, ignored box constraints as before for the diff ik tests. :(

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: with one BTW

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/test/optimization_examples.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5EmyuxVhxfT2UEX8M8:-L5EmyuxVhxfT2UEX8M9:bcqjuhg) ([raw file](https://github.com/robotlocomotion/drake/blob/88dcd3affb6a047fc354c2f0b1274eb42803ddcc/solvers/test/optimization_examples.cc#L92)):*
> ```cpp
>     }
>     case SolverType::kScs : {
>       return 3E-5;  // Scs is not very accurate.
> ```

BTW we've removed the "not very accurate" comment in a lot of other places, should it still be here?  (perhaps it should, it's still lower than the others)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-:-L5Emk0ohvV-571dJfNW:b-8wbyce)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/test/optimization_examples.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5EmyuxVhxfT2UEX8M8:-L5EufPfyjc5cIWXXea-:b-4zkvsp) ([raw file](https://github.com/robotlocomotion/drake/blob/88dcd3affb6a047fc354c2f0b1274eb42803ddcc/solvers/test/optimization_examples.cc#L92)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW we've removed the "not very accurate" comment in a lot of other places, should it still be here?  (perhaps it should, it's still lower than the others)
</blockquote></details>

Yes, the SCS default epsilon is 1E-5. But here it cannot reach 1E-5.  One step in SCS fails, so it only achieves 3E-5.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/test/optimization_examples.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-L5EmyuxVhxfT2UEX8M8:-L5Euz9RXC1Y0tTYi95h:b7rlm7r) ([raw file](https://github.com/robotlocomotion/drake/blob/88dcd3affb6a047fc354c2f0b1274eb42803ddcc/solvers/test/optimization_examples.cc#L92)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, the SCS default epsilon is 1E-5. But here it cannot reach 1E-5.  One step in SCS fails, so it only achieves 3E-5.
</blockquote></details>

SCS is still significantly less accurate than the other convex solvers, such as Gurobi or Mosek, which can achieve 1E-10.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8046#-:-L5FDgwEevYHNLhwYBwo:b-l70wzf)*

**Pull request merged**
