### PR TITLE
Add a pd + feedforward controller for the valkyrie simulation

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
@tkoolen for feature review. Twan, can you take a quick look at the rest of the sim stuff as well. thanks

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4193)

### CODE REVIEW

**Comment by tkoolen** [comment]
Looks good to me. Two minor comments about naming, feel free to ignore.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/examples/Valkyrie/valkyrie_pd_ff_controller.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6_znoSuWe8HBJCkOf:-KX6_znoSuWe8HBJCkOg:b-tryifb) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_pd_ff_controller.h#L10)):*
> ```objc
> namespace systems {
> 
> class ValkyriePDFFController : public systems::LeafSystem<double> {
> ```

`ValkyriePdAndFeedForwardController`?

---

*[drake/examples/Valkyrie/valkyrie_pd_ff_controller.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6_bWddrKntiT8eVNV:-KX6_bWe7yf6avfLGD-E:b-t7m0um) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_pd_ff_controller.h#L48)):*
> ```objc
>   VectorX<double> trq_ff_;
>   VectorX<double> Kp_;
>   VectorX<double> Kd_;
> ```

I'm in favor of using more descriptive field names here (with the possible exception of Kp_ and Kd_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-:-KX6agjYAm9p7NEVRdPl:bljb95c)*

**Comment by tkoolen** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4193)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/Valkyrie/valkyrie_constants.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6cRp9mf2mS6qso6pN:-KX6cRp9mf2mS6qso6pO:b-bqdtwu) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_constants.cc#L19)):*
> ```cpp
> VectorX<double> RPYValkyrieFixedPointTorque() {
>   VectorX<double> ff_torque(kRPYValkyrieDoF);
>   ff_torque << 0, 0, 0, 0, 0, 0, -4.789887276e-21, 54.07374714, -1.16973414,
> ```

Is the e-21 term important here? Does it affect our controller if we just set it zero? We can probably return a fixed-size vector also, instead of using VectorX.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4193)*

**Comment by siyuanfeng-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Valkyrie/valkyrie_constants.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6cRp9mf2mS6qso6pN:-KX6eRALIuBdic5uAfG8:b2epu7s) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_constants.cc#L19)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Is the e-21 term important here? Does it affect our controller if we just set it zero? We can probably return a fixed-size vector also, instead of using VectorX.
</details>
most likely not, this is the back yaw joint. 

---

*[drake/examples/Valkyrie/valkyrie_pd_ff_controller.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6_znoSuWe8HBJCkOf:-KX6h5lGyZ2XtdiZORO6:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_pd_ff_controller.h#L10)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> `ValkyriePdAndFeedForwardController`?
</details>
done

---

*[drake/examples/Valkyrie/valkyrie_pd_ff_controller.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6_bWddrKntiT8eVNV:-KX6hSPzJbvV_GYERqHc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_pd_ff_controller.h#L48)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I'm in favor of using more descriptive field names here (with the possible exception of Kp_ and Kd_.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4193)*

**Comment by tkoolen** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-:-KX7BCZaIgEF9Ew8V_xl:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Valkyrie/valkyrie_constants.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4193#-KX6cRp9mf2mS6qso6pN:-KX7I1g0GlSiTX87LZhk:bebpwvf) ([raw file](https://github.com/robotlocomotion/drake/blob/59419047ce3b0b63c4a53e083c461bd424e7ab22/drake/examples/Valkyrie/valkyrie_constants.cc#L19)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary>
> most likely not, this is the back yaw joint. 
</details>
How about returning a fixed-size vector?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4193)*

**Pull request merged**
