### PR TITLE
parse affine expressions in Mosek

### PR DESCRIPTION
**Pull request by hongkai-dai**
This factored function `ParseLinearExpression` will be used in imposing affine cone constraint in my next PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please.

Some background on this PR. Mosek recently upgraded to version 10, which supports affine cone constraint, namely the affine expression `F * x + g` is in a cone (like second order cone, exponential cone, etc). Previously it only supports `a vector of variables in a cone`. So I am updating our MosekSolver API to support this new feature.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085#-:-NE9_sAF8Gx5eboUNiMe:b-9d3v4o)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085)* status: 1 unresolved discussion, LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @aykut-tri)

___
*[`solvers/BUILD.bazel` line 1491 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEDO3-B8ADzKQXP4jO_:-NEDO3-CCYCA_5w3bvWb:b-9taav6) ([raw file](https://github.com/robotlocomotion/drake/blob/0a4ad451f54d5a51e0f27783e168b93642dc0e4f/solvers/BUILD.bazel#L1491)):*
> ```Starlark
>     name = "mosek_solver_internal_test",
>     opt_in_condition = "//tools:with_mosek",
>     #use_default_main = False,
> ```

@jwnimmer-tri , if I uncomment this line, then when I build with mosek disabled
```
$ bazel build //solvers:mosek_solver_internal_test
```
I got this error
```
ERROR: /home/hongkaidai/drake/solvers/BUILD.bazel:1488:29: Linking solvers/mosek_solver_internal_test failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/solvers/mosek_solver_internal_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
```
may I ask why? What happens if mosek is disabled for this `drake_cc_optional_googletest`? I thought it just skips building the target, but it seems that bazel still tries to build it somehow?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085)* status: 2 unresolved discussions, LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @aykut-tri)

___
*[`solvers/BUILD.bazel` line 1488 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEDP9GtAdRpYcqOyvye:-NEDP9GtAdRpYcqOyvyf:b-ya70cg) ([raw file](https://github.com/robotlocomotion/drake/blob/0a4ad451f54d5a51e0f27783e168b93642dc0e4f/solvers/BUILD.bazel#L1488)):*
> ```Starlark
> )
> 
> drake_cc_optional_googletest(
> ```

@jwnimmer-tri I used `drake_cc_optional_googletest` here to address the linking error discussed in https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1665609727611069, but based on the documentation of `drake_cc_optional_googletest`, it should only be used for `drake_cc_optional_library`, not `drake_cc_variant_library`. Our mosek_solver_internal is a drake_cc_variant_library. How would you recommend to solve this problem?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085)* status: 2 unresolved discussions, LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @aykut-tri and @hongkai-dai)

___
*[`solvers/BUILD.bazel` line 1488 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEDP9GtAdRpYcqOyvye:-NEDmYwBBo28BqJdYvQ1:bco1d1f) ([raw file](https://github.com/robotlocomotion/drake/blob/0a4ad451f54d5a51e0f27783e168b93642dc0e4f/solvers/BUILD.bazel#L1488)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@jwnimmer-tri I used `drake_cc_optional_googletest` here to address the linking error discussed in https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1665609727611069, but based on the documentation of `drake_cc_optional_googletest`, it should only be used for `drake_cc_optional_library`, not `drake_cc_variant_library`. Our mosek_solver_internal is a drake_cc_variant_library. How would you recommend to solve this problem?
</blockquote></details>

Oops.

Well, we probably could still keep it this way even though the documentation says not to.

But the real story is that I forgot `drake_cc_optional_library` exists, and we should have been using it all along:

```patch
--- a/solvers/BUILD.bazel
+++ b/solvers/BUILD.bazel
@@ -883,18 +883,13 @@ drake_cc_variant_library(
 # If --config mosek is used, this target builds object code constructs internal
 # functions used in mosek_solver. Otherwise, this target builds no object
 # code.
-drake_cc_variant_library(
+drake_cc_optional_library(
     name = "mosek_solver_internal",
     opt_in_condition = "//tools:with_mosek",
-    srcs_always = [],
-    srcs_enabled = ["mosek_solver_internal.cc"],
-    srcs_disabled = [],
+    srcs = ["mosek_solver_internal.cc"],
     hdrs = ["mosek_solver_internal.h"],
-    internal = True,
-    visibility = ["//visibility:private"],
     interface_deps = [":mathematical_program_result"],
-    deps_always = [],
-    deps_enabled = [
+    deps = [
         ":aggregate_costs_constraints",
         ":mathematical_program",
         "//math:quadratic_form",
```
___
*[`solvers/BUILD.bazel` line 1491 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEDO3-B8ADzKQXP4jO_:-NEDkCQt0xHQxQI5vlF3:b-8t909x) ([raw file](https://github.com/robotlocomotion/drake/blob/0a4ad451f54d5a51e0f27783e168b93642dc0e4f/solvers/BUILD.bazel#L1491)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@jwnimmer-tri , if I uncomment this line, then when I build with mosek disabled
```
$ bazel build //solvers:mosek_solver_internal_test
```
I got this error
```
ERROR: /home/hongkaidai/drake/solvers/BUILD.bazel:1488:29: Linking solvers/mosek_solver_internal_test failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/solvers/mosek_solver_internal_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
```
may I ask why? What happens if mosek is disabled for this `drake_cc_optional_googletest`? I thought it just skips building the target, but it seems that bazel still tries to build it somehow?
</blockquote></details>

The edits to wire through `use_default_main` were incomplete:

```patch
--- a/solvers/defs.bzl
+++ b/solvers/defs.bzl
@@ -185,6 +185,12 @@ def drake_cc_optional_googletest(
         opt_out_condition,
     )
     srcs = ["test/{}.cc".format(name)]
+    if use_default_main:
+        opt_out_deps = []
+    else:
+        # The `srcs` provide a main() function, but in the opt_out case we
+        # won't be linking them; to cope, we'll fall back to the default main.
+        opt_out_deps = ["//common/test_utilities:drake_cc_googletest_main"]
     drake_cc_googletest(
         name = name,
         srcs = select({
@@ -194,7 +200,7 @@ def drake_cc_optional_googletest(
         tags = tags,
         deps = select({
             opt_in_condition: deps,
-            opt_out_condition: [],
+            opt_out_condition: opt_out_deps,
         }),
         use_default_main = use_default_main,
     )
```

For tests, we do _not_ simply omit the test program in the disabled case.  Rather, we link an _empty_ test program with no tests cases.  That's why it still wanted a `main()` program.

Having targets that evaporate depending on the build configuration tend to cause headaches.  Having a test program with zero tests is much easier to cope with.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @aykut-tri)

___
*[`solvers/BUILD.bazel` line 1488 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEDP9GtAdRpYcqOyvye:-NEE87bc1EcSnOmWcIJd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0a4ad451f54d5a51e0f27783e168b93642dc0e4f/solvers/BUILD.bazel#L1488)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.

Well, we probably could still keep it this way even though the documentation says not to.

But the real story is that I forgot `drake_cc_optional_library` exists, and we should have been using it all along:

```patch
--- a/solvers/BUILD.bazel
+++ b/solvers/BUILD.bazel
@@ -883,18 +883,13 @@ drake_cc_variant_library(
 # If --config mosek is used, this target builds object code constructs internal
 # functions used in mosek_solver. Otherwise, this target builds no object
 # code.
-drake_cc_variant_library(
+drake_cc_optional_library(
     name = "mosek_solver_internal",
     opt_in_condition = "//tools:with_mosek",
-    srcs_always = [],
-    srcs_enabled = ["mosek_solver_internal.cc"],
-    srcs_disabled = [],
+    srcs = ["mosek_solver_internal.cc"],
     hdrs = ["mosek_solver_internal.h"],
-    internal = True,
-    visibility = ["//visibility:private"],
     interface_deps = [":mathematical_program_result"],
-    deps_always = [],
-    deps_enabled = [
+    deps = [
         ":aggregate_costs_constraints",
         ":mathematical_program",
         "//math:quadratic_form",
```
</blockquote></details>

Done.
___
*[`solvers/BUILD.bazel` line 1491 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEDO3-B8ADzKQXP4jO_:-NEEGGJK7usp-qJ_16oo:bo0c705) ([raw file](https://github.com/robotlocomotion/drake/blob/0a4ad451f54d5a51e0f27783e168b93642dc0e4f/solvers/BUILD.bazel#L1491)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The edits to wire through `use_default_main` were incomplete:

```patch
--- a/solvers/defs.bzl
+++ b/solvers/defs.bzl
@@ -185,6 +185,12 @@ def drake_cc_optional_googletest(
         opt_out_condition,
     )
     srcs = ["test/{}.cc".format(name)]
+    if use_default_main:
+        opt_out_deps = []
+    else:
+        # The `srcs` provide a main() function, but in the opt_out case we
+        # won't be linking them; to cope, we'll fall back to the default main.
+        opt_out_deps = ["//common/test_utilities:drake_cc_googletest_main"]
     drake_cc_googletest(
         name = name,
         srcs = select({
@@ -194,7 +200,7 @@ def drake_cc_optional_googletest(
         tags = tags,
         deps = select({
             opt_in_condition: deps,
-            opt_out_condition: [],
+            opt_out_condition: opt_out_deps,
         }),
         use_default_main = use_default_main,
     )
```

For tests, we do _not_ simply omit the test program in the disabled case.  Rather, we link an _empty_ test program with no tests cases.  That's why it still wanted a `main()` program.

Having targets that evaporate depending on the build configuration tend to cause headaches.  Having a test program with zero tests is much easier to cope with.
</blockquote></details>

Thanks Jeremy!

**Review by aykut-tri — COMMENTED** [review]
Excellent, thanks for the explanation. :lgtm_strong: with a super tiny nit.

+@sammy-tri for platform review, please.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085#-:-NEI3BUk5oWz--NI-FL-:b-7n6xay)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @sammy-tri)

___
*[`solvers/test/mosek_solver_internal_test.cc` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18085#-NEI2_Es5sA7HbnOuq6a:-NEI2_Es5sA7HbnOuq6b:bxx53in) ([raw file](https://github.com/robotlocomotion/drake/blob/7bc61c1ce59cf44af4ee2c5d3c916b266512d5bb/solvers/test/mosek_solver_internal_test.cc#L11)):*
> ```cpp
> namespace solvers {
> namespace internal {
> using BarFType = std::vector<std::unordered_map<
> ```

nit, is there a reason for the extra line in between?



_Code quote:_
```cpp
using BarFType = std::vector<std::unordered_map<

    MSKint64t, std::pair<std::vector<MSKint64t>, std::vector<MSKrealt>>>>;
```

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18085#-:-NEISDiM4zix4QmZx_rY:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Pull request merged**
