### PR TITLE
[pydrake] Add conversion to/from SymPy

### LINKED ISSUE #20076: Conversion between SymPy and pydrake.symbolic.Expression
**Is your feature request related to a problem? Please describe.**

Drake uses a custom [symbolic expression](https://drake.mit.edu/pydrake/pydrake.symbolic.html#pydrake.symbolic.Expression) module to support inter-operation between our C++ and Python code.  However, for users who need more complicated symbolic manipulation in Python, sometimes the features of our Expression class fall short (e.g., #8515, etc.).

[SymPy](https://www.sympy.org/en/index.html) is a very nice symbolic math package which can often provide the necessary additional features.

To help users leverage both libraries to their advantage, Drake should offer functions to convert from our own custom symbolic expressions into SymPy, and vice versa.

**Describe the solution you'd like**

An optional pure-Python module under `pydrake` that (when imported) offers some kind of Python API to copy a Drake Expression (or matrix of expressions) into SymPy object(s), and vice versa.

This module would require the user to bring their own `SymPy`.  Drake wheels would not depend on SymPy.

**Describe alternatives you've considered**

Users could write their own converters using [Unapply](https://drake.mit.edu/pydrake/pydrake.symbolic.html#pydrake.symbolic.Expression.Unapply) but its probably subtle and boring.  Providing a first-party solution would be easier and more robust.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #20076.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 7 files at r3, 4 of 10 files at r5, 7 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.  No rush.

**Review by ggould-tri — COMMENTED** [review]
A few notes below.

I would like to see at least a trivial test case that evaluating the expressions gives the same answer, if only as an example to anyone trying to use this feature.  Unfortunately I wasn't able to finish writing such a test in the time I allocated to this, but I left my attempt below if you care (I don't think quite so general a test is required, though -- the complexity verges on being silly).

I'll come back to this later; I'm out of timebox for today.

> Reviewed 3 of 7 files at r3, 3 of 10 files at r5, 5 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-:-Ngz6IJH3f5nGtT5qXEN:b-k7ngmi)* status: 6 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/_symbolic_extra.py` line 28 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyneko7EZcUH5eEyNB:-Ngyneko7EZcUH5eEyNC:b-l7st4k) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/_symbolic_extra.py#L28)):*
> ```Python
> 
> # Drake's SymPy support is loaded lazily (on demand), so that Drake does not
> # directly depend on SymPy. The implementation lives in `_symbolic_sympy.py`.
> ```

Not directly depending on sympy means that we don't directly express an opinion on supported versions of sympy.  A supported sympy version(s) should be documented somewhere.
___
*[`bindings/pydrake/_symbolic_extra.py` line 35 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-NgyFTiq6CjnMbfpQItt:-NgyFTir451XeATOthTB:bs5z09q) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/_symbolic_extra.py#L35)):*
> ```Python
>              *,
>              memo: typing.Dict = None) -> typing.Union[
>                  float, bool, 'sympy.Expr']:
> ```

BTW:  I assume that the ugly mess above is required by some vengeful linter, but if not, putting both argument and output type information on the same line in a multiline contract, and splitting the return type over two lines is bad readability; something like the below would IMO be more readable.

The same applies to the next function as well, and to `_symbolic_sympy.py`:121,223.



_Suggestion:_
```Python
def to_sympy(x: typing.Union[float, bool, Variable, Expression, Formula],
             *, memo: typing.Dict = None
             ) -> typing.Union[float, bool, 'sympy.Expr']:
```
___
*[`bindings/pydrake/_symbolic_extra.py` line 35 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-NgyFpjh11FKVIsG3RfU:-NgyFpjh11FKVIsG3RfV:bpzreh8) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/_symbolic_extra.py#L35)):*
> ```Python
>              *,
>              memo: typing.Dict = None) -> typing.Union[
>                  float, bool, 'sympy.Expr']:
> ```

BTW:  Consider at author's discretion a type alias for your two union types `typing.Union[float, bool, 'sympy.Expr']`.  I don't know how it would read in practice, or if it would regress the documentation, though.
___
*[`bindings/pydrake/test/sympy_test.py` line 43 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyse3518_BvZloju2Q:-Ngyse36Asio7akwR95Z:b-oewkyv) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L43)):*
> ```Python
>             x - y,
>             x / y,
>             x - y / z,
> ```

minor:  Consider also including:
```
x ** y,
q and r,
r or q,
```
(All of these pass)
___
*[`bindings/pydrake/test/sympy_test.py` line 92 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngz5y0F0V2a9MZ9Y5La:-Ngz5y0G3f2YZ6YGuk8A:bw5hvyf) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L92)):*
> ```Python
>             with self.subTest(item=item):
>                 self._test_one_round_trip(item)
> ```

BTW:  I blew a short timebox trying to check if the expressions evaluated to the same value.  In case it's of interest to you, here's as far as I got:

```
    def _test_one_eval(self, item):
        x, y, z, q, r = self.xyzqr
        drake_env={x: 1.1, y: 2.2, z: 3.3, q: True, r: False}
        drake_value = (
            item if type(item) in {float, bool} else
            drake_env[item] if type(item) == Variable else
            item.Evaluate(env=drake_env))
        memo = dict()
        sympy_expr = mut.to_sympy(item, memo=memo)
        sympy_env = {}
        for sympy_var, drake_var in memo.items():
            if type(drake_var) == Variable:
                sympy_env[sympy_var] = drake_env[drake_var]
        sympy_value = (
            True if type(sympy_expr) == sympy.logic.boolalg.BooleanTrue else
            False if type(sympy_expr) == sympy.logic.boolalg.BooleanFalse else
            sympy_expr if type(sympy_expr) in {float, bool} else
            sympy_expr.evalf(subs=sympy_env))
        self.assertEqual(drake_value, sympy_value)
```
___
*[`bindings/pydrake/test/sympy_test.py` line 114 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyx5_G5xb2lXmLDJHv:-Ngyx5_H0fITeQa9X4ZP:bwt46tx) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L114)):*
> ```Python
>             pass
>         self.fail(f"Incomparable {item_str} with "
>                   f"{readback_str} (from {converted_str})")
> ```

minor:  This pass-fail idiom seems verbose and obscure ('except`...`pass` reads like an ignored error).  It might be smoother rewritten to drop the explicit return/pass control flow elements:



_Suggestion:_
```Python
        try:
            self.assertTrue(item.EqualTo(readback),
                            msg=f"Got {readback_str} (from {converted_str})")
        except TypeError as e:
            self.fail(f"Incomparable {item_str} with "
                      f"{readback_str} (from {converted_str})")
```

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)* status: 7 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/_symbolic_sympy.py` line 120 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-NgzI88l0rsxVfHrNAOE:-NgzI88m87pIyu9B48-0:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/_symbolic_sympy.py#L120)):*
> ```Python
> 
>     At the moment, the *only* supported conversion is to look up the variable
>     in `memo`, i.e., the user my pre-define the mapping.
> ```

typo



_Suggestion:_
```Python
may
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`bindings/pydrake/_symbolic_extra.py` line 35 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-NgyFTiq6CjnMbfpQItt:-Nh-0jXGEn7TaCEr1Y5b:b-9jtqvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/_symbolic_extra.py#L35)):*
> I assume that the ugly mess above is required by some vengeful linter, ...

No linter demands it, no. It's documentation for the user (and our developers!) about which kinds of things we can intake, and what we might output as a result.

I asked https://pypi.org/project/black/ for advice and it suggested putting the close-paren at tab stop zero, with the return type afterward.
___
*[`bindings/pydrake/_symbolic_extra.py` line 35 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-NgyFpjh11FKVIsG3RfU:-Nh-12L61NhJMJflEvik:bacwo7m) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/_symbolic_extra.py#L35)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  Consider at author's discretion a type alias for your two union types `typing.Union[float, bool, 'sympy.Expr']`.  I don't know how it would read in practice, or if it would regress the documentation, though.
</blockquote></details>

In general, I do not necessarily expect those two lists of types to always be the same, so I don't think typedefs will ultimately be helpful.
___
*[`bindings/pydrake/test/sympy_test.py` line 43 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyse3518_BvZloju2Q:-Nh--Gmi0XQpBGaYni1r:bpue1oc) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L43)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider also including:
```
x ** y,
q and r,
r or q,
```
(All of these pass)
</blockquote></details>

Done for exponentiation.  But there are a lot of "cannot overload relational operators" voodoo comments in the code, so I'm not going to add the last two.  I suspect they are a trap.
___
*[`bindings/pydrake/test/sympy_test.py` line 92 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngz5y0F0V2a9MZ9Y5La:-Nh-KeXxAXarGPhByJYl:b-3r1mm) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L92)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  I blew a short timebox trying to check if the expressions evaluated to the same value.  In case it's of interest to you, here's as far as I got:

```
    def _test_one_eval(self, item):
        x, y, z, q, r = self.xyzqr
        drake_env={x: 1.1, y: 2.2, z: 3.3, q: True, r: False}
        drake_value = (
            item if type(item) in {float, bool} else
            drake_env[item] if type(item) == Variable else
            item.Evaluate(env=drake_env))
        memo = dict()
        sympy_expr = mut.to_sympy(item, memo=memo)
        sympy_env = {}
        for sympy_var, drake_var in memo.items():
            if type(drake_var) == Variable:
                sympy_env[sympy_var] = drake_env[drake_var]
        sympy_value = (
            True if type(sympy_expr) == sympy.logic.boolalg.BooleanTrue else
            False if type(sympy_expr) == sympy.logic.boolalg.BooleanFalse else
            sympy_expr if type(sympy_expr) in {float, bool} else
            sympy_expr.evalf(subs=sympy_env))
        self.assertEqual(drake_value, sympy_value)
```
</blockquote></details>

Done, thanks for the bootstrap.
___
*[`bindings/pydrake/test/sympy_test.py` line 114 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyx5_G5xb2lXmLDJHv:-Nh-03ey8qeXYpwpseQJ:b-ws2bbx) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L114)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This pass-fail idiom seems verbose and obscure ('except`...`pass` reads like an ignored error).  It might be smoother rewritten to drop the explicit return/pass control flow elements:
</blockquote></details>

Done (via comment).

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
FYI @ggould-tri still needs your LGTM emoji when you're ready.

**Review by jwnimmer-tri — COMMENTED** [review]
Ugh, reviewable didn't track the `_symbolic_extra.py` diffs across the rebase.  Oh well.

> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-:-Nh3GHAo8pCQrakpWWOB:b-p3sekl)* status: LGTM missing from assignees ggould-tri(platform),xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 3 of 7 files at r3, 3 of 10 files at r5, 3 of 7 files at r6, 1 of 5 files at r8, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-:-Nh4-Ca_7eUbq_Zq-DCv:b-cxwtpw)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform)

___
*[`bindings/pydrake/symbolic/_symbolic_extra.py` line 40 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Nh3w4ZBDR_MdRgMe5dg:-Nh3w4ZBDR_MdRgMe5dh:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/0f55967bbd6949fda6c59d1e80ae788058ce8e68/bindings/pydrake/symbolic/_symbolic_extra.py#L40)):*
> ```Python
> 
>     Certain expressions are not supported and will raise NotImplementedError.
>     (Most actutely, note that `int` is not yet supported.)
> ```

typo



_Suggestion:_
```Python
(Most acutely, note that `int` is not yet supported.)
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by ggould-tri** [comment]
Rereading now.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r8, 5 of 6 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-:-Nh7RRA50wh1ib3-TZ9f:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/test/sympy_test.py` line 43 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyse3518_BvZloju2Q:-Nh7QcPM-B91_1w4Qlmq:btt15ze) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done for exponentiation.  But there are a lot of "cannot overload relational operators" voodoo comments in the code, so I'm not going to add the last two.  I suspect they are a trap.
</blockquote></details>

Marking resolved, but if they are a trap then possibly we should in the future overload symbolics' `__and__` and `__or__` to give the user some appropriate warning.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20117)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/test/sympy_test.py` line 43 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20117#-Ngyse3518_BvZloju2Q:-Nh7S2ZYEIAwVt8NOVLq:b-dew3s9) ([raw file](https://github.com/RobotLocomotion/drake/blob/dff6eb63062477091072016fbf1e793a60f15a8f/bindings/pydrake/test/sympy_test.py#L43)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Marking resolved, but if they are a trap then possibly we should in the future overload symbolics' `__and__` and `__or__` to give the user some appropriate warning.
</blockquote></details>

Impossible: http://stackoverflow.com/a/471561.  The `__and__` operator is for bitwise `&`, not logical `and`.

**Pull request merged**
