### PR TITLE
[solvers] Add missing unit tests for options handling

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In preparation for #21345.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21939)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21939)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/test/mosek_solver_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21939#-O7PtgLV1KzdCCfzTGnP:-O7PtgLV1KzdCCfzTGnQ:bw9vuql) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7e7dfd398c66eabb378129bfad780c4b3e602ca/solvers/test/mosek_solver_test.cc#L300)):*
> ```cpp
>                            bas_file);
>   solver.Solve(prog, {}, solver_options, &result);
>   EXPECT_TRUE(std::filesystem::exists({log_file}));
> ```

Should we check the existence of the `bas_file`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21939)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/test/mosek_solver_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21939#-O7PtgLV1KzdCCfzTGnP:-O7Q0gAj-3pFhkahF0g_:b-jcl8ih) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7e7dfd398c66eabb378129bfad780c4b3e602ca/solvers/test/mosek_solver_test.cc#L300)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we check the existence of the `bas_file`?
</blockquote></details>

Yes, I forgot to check that.  However, I can't get MOSEK to write to that file, or any other string-option file for that matter.

Can you think of any https://docs.mosek.com/10.1/capi/parameters.html#doc-sparam-list options that we could set and see some effect from, either in a file or a change to the solution result?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21939)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/test/mosek_solver_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21939#-O7PtgLV1KzdCCfzTGnP:-O7f0hm21eHDuPPkxkEF:bcwpntj) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7e7dfd398c66eabb378129bfad780c4b3e602ca/solvers/test/mosek_solver_test.cc#L300)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, I forgot to check that.  However, I can't get MOSEK to write to that file, or any other string-option file for that matter.

Can you think of any https://docs.mosek.com/10.1/capi/parameters.html#doc-sparam-list options that we could set and see some effect from, either in a file or a change to the solution result?
</blockquote></details>

I tried a half dozen string options, and none of them wrote anything.  AA couldn't think of an option to test, either.  So instead, I've rewritten the test code to clarify that all we are doing is smoke testing lack of crashes, on purpose.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21939#-:-O7j2ing6a3DMS6tbtD1:bg7igkv)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`solvers/test/mosek_solver_test.cc` line 300 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21939#-O7PtgLV1KzdCCfzTGnP:-O7j2_v45vR-d-ZoIGGo:b-p7y2dn) ([raw file](https://github.com/RobotLocomotion/drake/blob/b7e7dfd398c66eabb378129bfad780c4b3e602ca/solvers/test/mosek_solver_test.cc#L300)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I tried a half dozen string options, and none of them wrote anything.  AA couldn't think of an option to test, either.  So instead, I've rewritten the test code to clarify that all we are doing is smoke testing lack of crashes, on purpose.
</blockquote></details>

Sorry I somehow missed this PR. Thanks for the change.

**Pull request merged**
