### PR TITLE
Remove deprecated code 2024-02

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Most of the removals are the past 3-4 months, but some MbT stuff dates back to 2020 but was overlooked previously.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20846)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@hongkai-dai for feature review of changes to `inverse_kinematics` and `solvers` and their python bindings, please.

+@sherm1 for feature review of the balance and platform review overall, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20846#-:-NpPZ-Qk9N8aaQ-ey32C:bwpq5u4)* status: 1 unresolved discussion, LGTM missing from assignees hongkai-dai,sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20846#-NpPYwrQ1FeNdSGFUTl1:-NpPYwrR3LtqP22Yr6ju:blt453f) (no related file):*
Working

Do not merge until 2024-02-01 UTC.

___

**Review by sherm1 — COMMENTED** [review]
Wow! That's got to be record for amount of deprecated code nuked. RIP event dispatcher override! Great to see that finally history -- what a horror show.

Platform :lgtm: and feature :lgtm: for all but the inverse_kinematics and solver removals pending @hongkai-dai review.

> Reviewed 83 of 83 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20846#-:-NpQSUvG2REzztuHZBx0:b-bzxhl9)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai

**Comment by jwnimmer-tri** [comment]
@hongkai-dai will you have time to look over this?

**Comment by jwnimmer-tri** [comment]
(Re-pushed to avoid a merge conflict with #20872.)

**Review by jwnimmer-tri — COMMENTED** [review]
-@hongkai-dai won't have time for this.  @sherm1 are you okay as single reviewer?

I took another careful look over the solvers and IK changes, and pushed one fix.  I think it's ready to merge.

> Reviewed 15 of 83 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20846#-:-NpotxFq9yb0kSEaag5w:b-e69kum)* status: needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 
I looked at inverse_kinematics & solver removals, :lgtm:

> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20846#-:-NppGxUm0V_6ymd03Zxh:bvlbtrn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
