### PR TITLE
Lcm matlab updates

### PR DESCRIPTION
**Pull request by RussTedrake**
Extracts only the lcm_call_matlab changes from #4653.

Took the time to resolve almost all of the issues from #4653.  The matlab client is much higher performance and much more robust now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4727)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@david-german-tri for platform review
+@hongkai-dai for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-:-Ka63Qr3SS407rBmQFg-:b-z88bof)*

**Comment by hongkai-dai** [comment]
Checkpoint.

---

Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-:-Ka6i7ecIOhXkdFNYrBv:by96gdd)*

**Comment by liangfok** [comment]
I left some minor comments after a quick skim.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/lcm/lcm_call_matlab.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka6zKhP6X_zEjSVp1e3:-Ka6zKhP6X_zEjSVp1e4:b-fs41ct) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.cc#L9)):*
> ```cpp
> #include "lcm/lcm-cpp.hpp"
> 
> #include "drake/common/drake_assert.h"
> ```

BTW: unused?

---

*[drake/lcm/lcm_call_matlab.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka6zYGv3LQSawm3uNkq:-Ka6zYGv3LQSawm3uNkr:bc9t7lw) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.cc#L17)):*
BTW, the "g" is likely a style guide violation:

> Names should be descriptive; avoid abbreviation.

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

Consider `globally_unique_id`.

(Same comment below about `uid_` being `unique_id_`.)

---

*[drake/lcm/lcm_call_matlab.h, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka70OPEaf8TDXXr3aJZ:-Ka70OPEaf8TDXXr3aJ_:bcos181) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L68)):*
> ```objc
> 
> // Simple wrapper to prevent the outside world from needing to worry about
> // creating an lcm::LCM object.
> ```

BTW, consider making the above a Doxygen comment block.

---

*[drake/lcm/lcm_call_matlab.h, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7-VnzJos3siqce0Wp:-Ka7-VnzJos3siqce0Wq:b77m121) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L80)):*
> ```objc
>     const std::string& function_name, Types... args);
> 
> /// Holds a reference to a return variable stored on the matlab client, which
> ```

BTW, consider deleting "return".

---

*[drake/lcm/lcm_call_matlab.h, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7-fAzLnWc_3KBp719:-Ka7-fAzLnWc_3KBp71A:bqly633) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L90)):*
> ```objc
>   int64_t uid() const { return uid_; }
> 
>   /// Create a new remote variable that contains the data at the prescribed
> ```

BTW, "Create" should be "Creates" per style guide.

---

*[drake/lcm/lcm_call_matlab.h, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka74_7qa31ULKYWsInm:-Ka74_7qa31ULKYWsInn:b-o15mqv) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L92)):*
> ```objc
>   /// Create a new remote variable that contains the data at the prescribed
>   /// index.  Supported calls are, for instance:
>   ///   var(1)      // Access the first element.
> ```

BTW, this will not render correctly in Doxygen. One solution is to surround it with `<pre> </pre>`.

---

*[drake/lcm/lcm_call_matlab.h, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka70VIzGjn_Uce7UK-g:-Ka70VIzGjn_Uce7UK-h:bqly633) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L109)):*
> ```objc
>   }
> 
>   /// Create a new remote variable that contains the data at the prescribed
> ```

BTW, "Create" should be "Creates" per style guide.

---

*[drake/lcm/lcm_call_matlab.h, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka74j6khUAGOrp3-v0C:-Ka74j6khUAGOrp3-v0D:b-o15mqv) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L112)):*
> ```objc
>   /// index.  Supported calls are, for instance:
>   ///   var.subsasgn(val,1)               // Set the first element to val.
>   ///   var.subsasgn(val,1,2)             // Set row 1, column 2.
> ```

BTW, this will not render correctly in Doxygen. One solution is to surround it with `<pre> </pre>`.

---

*[drake/lcm/lcm_call_matlab.h, line 221 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka70eDJq3hSiywdzWK1:-Ka70eDJq3hSiywdzWK2:bt2chou) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L221)):*
> ```objc
> }
> 
> /// Special case the call with one output.
> ```

BTW, "case" should be "cases" per style guide.

Consider adding "method" after "call".

---

*[drake/matlab/util/drakeMexUtil.cpp, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka717gIzBu995VPkCHu:-Ka717gIzBu995VPkCHv:byssp5z) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/drakeMexUtil.cpp#L2)):*
> ```cpp
> #include <stdexcept>
> #include "drake/matlab/util/drakeMexUtil.h"
> ```

BTW, Drake header includes should be grouped together. 

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka72iM5OEklEFVXetH7:-Ka72iM5OEklEFVXetH8:bhw8il8) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L94)):*
> ```cpp
>       int error_code = errno;
>       if (status == -1 && error_code != EINTR) {
>         std::cout << "select() returned error: " << error_code << std::endl;
> ```

BTW, consider using:

```
drake::log()->error("select() returned error: {}", error_code);
```

which is available in `drake/common/text_logging.h`.

(Same comments to print statements below.)

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka71voaQS6Oi4KgfWcs:-Ka71voaQS6Oi4KgfWct:bf66qqf) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L133)):*
> ```cpp
> };
> 
> }  // end namespace
> ```

BTW, delete "end" per style guide.

https://google.github.io/styleguide/cppguide.html#Unnamed_Namespaces_and_Static_Variables

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 173 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka73OI5Dr99iiUoIYNZ:-Ka73OI5Dr99iiUoIYN_:b44w20p) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L173)):*
> ```cpp
>   stop = false;
>   while (!stop) {
>     message_mutex.lock();
> ```

BTW, @ggould-tri once defected me for using `lock()` since it is not robust against exceptions. Can this code be restructured to use `std::lock_guard<std::mutex> lock(message_mutex);`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-:-Ka73iLK9QXIMzH1DuPz:b34j1wq)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7wr_6levRhU2hOaSd:-Ka7wr_6levRhU2hOaSe:b-hx4c2f) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L73)):*
> ```cpp
> class LCMLoop {
>  public:
>   explicit LCMLoop(lcm::LCM& lcm) : lcm_(lcm), stop_(false) {}
> ```

https://google.github.io/styleguide/cppguide.html#Reference_Arguments

(should be a pointer)

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 173 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka73OI5Dr99iiUoIYNZ:-Ka7xSmn_fU3MHu5OrKt:b-zadfmg) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L173)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, @ggould-tri once defected me for using `lock()` since it is not robust against exceptions. Can this code be restructured to use `std::lock_guard<std::mutex> lock(message_mutex);`?
</blockquote></details>

BTW, I don't think exception robustness is an important reason to make that change, but it would also be more readable IMO.  Possible phrasing:

```
{lock scope: pop-msg-or-nullptr}; 
if (msg == nullptr) ... else ...;
```

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 184 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7yXIt7JFR8wP86Ifw:-Ka7yXIt7JFR8wP86Ifx:b-xushgj) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L184)):*
> ```cpp
>       message_mutex.unlock();
> 
>       int i;
> ```

BTW consider putting all of this message parsing in a helper function just to cut down on the conditional depth.  (Took me a minute or two to figure out how the closing brackets aligned.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-:-Ka7yw_zua5Zp2leevl1:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka72iM5OEklEFVXetH7:-Ka7z1IoJZm59j-K5IpT:bt3l6dy) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L94)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider using:

```
drake::log()->error("select() returned error: {}", error_code);
```

which is available in `drake/common/text_logging.h`.

(Same comments to print statements below.)
</blockquote></details>

BTW, in most situations I would +1 this, but I don't really know what the effect of invoking spdlog inside a mex file would be.  Might be better to keep it simple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/lcm/lcm_call_matlab.cc, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka6zKhP6X_zEjSVp1e3:-Ka7zccSNJCCzcLryBBS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.cc#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: unused?
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka6zYGv3LQSawm3uNkq:-Ka7zsoM3UoEoX8aUiBF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.cc#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, the "g" is likely a style guide violation:

> Names should be descriptive; avoid abbreviation.

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

Consider `globally_unique_id`.

(Same comment below about `uid_` being `unique_id_`.)
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka70OPEaf8TDXXr3aJZ:-Ka8-5_kpn0ALLfrI8cS:b-143vul) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider making the above a Doxygen comment block.
</blockquote></details>

i intentionally did not since this is inside the ::internal namespace.

---

*[drake/lcm/lcm_call_matlab.h, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7-VnzJos3siqce0Wp:-Ka8-LsHlp3ADfyuEu2c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L80)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "return".
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7-fAzLnWc_3KBp719:-Ka8-ONJbwZAI1pcZWsN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L90)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "Create" should be "Creates" per style guide.
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka74_7qa31ULKYWsInm:-Ka8-Tmxrj4yXRPg3dsq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this will not render correctly in Doxygen. One solution is to surround it with `<pre> </pre>`.
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka70VIzGjn_Uce7UK-g:-Ka8-m7ew2i21ngtWgED:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L109)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "Create" should be "Creates" per style guide.
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka74j6khUAGOrp3-v0C:-Ka8-z8SmAi_1RiIxszl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L112)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this will not render correctly in Doxygen. One solution is to surround it with `<pre> </pre>`.
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 221 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka70eDJq3hSiywdzWK1:-Ka801kJse-AhG1edIur:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/lcm/lcm_call_matlab.h#L221)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "case" should be "cases" per style guide.

Consider adding "method" after "call".
</blockquote></details>

Done.

---

*[drake/matlab/util/drakeMexUtil.cpp, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka717gIzBu995VPkCHu:-Ka808IJdFutBJyjiJp1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/drakeMexUtil.cpp#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, Drake header includes should be grouped together. 
</blockquote></details>

Done.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7wr_6levRhU2hOaSd:-Ka80arA3WkHNjvomPiM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L73)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Reference_Arguments

(should be a pointer)
</blockquote></details>

Done.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka72iM5OEklEFVXetH7:-Ka80lhgEBlSKZvDB64q:bgnlbcx) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L94)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, in most situations I would +1 this, but I don't really know what the effect of invoking spdlog inside a mex file would be.  Might be better to keep it simple.
</blockquote></details>

i agree w/ david.  in fact, i changed the line BACK to std::cout from the text logging version I copied this from.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka71voaQS6Oi4KgfWcs:-Ka810UxrcU0cK7aFDzA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L133)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, delete "end" per style guide.

https://google.github.io/styleguide/cppguide.html#Unnamed_Namespaces_and_Static_Variables
</blockquote></details>

Done.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 173 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka73OI5Dr99iiUoIYNZ:-Ka831WzG7jTXrKQJJgP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L173)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, I don't think exception robustness is an important reason to make that change, but it would also be more readable IMO.  Possible phrasing:

```
{lock scope: pop-msg-or-nullptr}; 
if (msg == nullptr) ... else ...;
```
</blockquote></details>

Done.

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 184 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka7yXIt7JFR8wP86Ifw:-Ka83L5Jr6ILLDvGiTkO:ba9opjh) ([raw file](https://github.com/robotlocomotion/drake/blob/ecc5540a51cf4ce95002049b17c6fde97f8d1081/drake/matlab/util/lcm_call_matlab_client.cc#L184)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW consider putting all of this message parsing in a helper function just to cut down on the conditional depth.  (Took me a minute or two to figure out how the closing brackets aligned.)
</blockquote></details>

going to pass on this one.  i would have to pass many variable pointers to that function, and it looks messier to me than the current form.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-:-Ka86M4vcicE4Uwu41MT:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/lcm/lcm_call_matlab.h, line 107 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-Ka8KxUSMbJV2PJf32Cz:-Ka8KxUSMbJV2PJf32D-:b-dejfwx) ([raw file](https://github.com/robotlocomotion/drake/blob/9c31a6e573d12cfff44da75bbb34a2fecaaf376a/drake/lcm/lcm_call_matlab.h#L107)):*
> ```objc
>   ///   var(Eigen::VectorXd::LinSpaced(10,1,10))  // Access elements 1:10.
>   /// <pre>
>   /// Note: yes, vector indices in Matlab are doubles.
> ```

Maybe also put a note that MATLAB matrix/vector are 1-indexed, while in C++ and Eigen, they are 0-indexed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4727#-:-Ka8WD3Znjo2TGBd-UY5:bnfp4nl)*

**Pull request merged**
