### PR TITLE
Remove redundant default mass in body.h in favor of default mass in rigid_body.h.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17472)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Nice cleanup, thanks! Feature :lgtm: with one minor request.
+@xuchenhan-tri for platform review per rotation, please

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17472#-:-N5kmEoH0Ff08Jsf5eJY:bza8f8y)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @xuchenhan-tri)

___
*[`multibody/tree/rigid_body.h` line 116 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17472#-N5klOV78gQFxKdR02V5:-N5klOV78gQFxKdR02V6:bued2ol) ([raw file](https://github.com/robotlocomotion/drake/blob/c228d56f4bd4217e05174f526b26b3b1208af107/multibody/tree/rigid_body.h#L116)):*
> ```objc
>     return default_mass();  // Returns the mass stored in `this` RigidBody.
>   }
> #endif
> ```

minor: better to put this implementation in the `private` section rather than put it here in doxygen guards. A call to RigidBody::get_default_mass() will still work because it will invoke the base class method. But hopefully if anyone actually has a RigidBody object they will call default_mass().

Also I don't think the comment about Kaizen etc adds anything here. If we do rename the base class method it will be obvious what needs to be done here.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with one nit.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17472#-:-N5lH7ID6W9z6wUR-TAf:blpvlj1)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rigid_body.h` line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17472#-N5kyc7VETiH_50cs8HR:-N5kyc7VETiH_50cs8HS:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/c228d56f4bd4217e05174f526b26b3b1208af107/multibody/tree/rigid_body.h#L96)):*
> ```objc
>   int get_num_flexible_velocities() const final { return 0; }
> 
>   /// Returns this rigid body's default mass, which is is initially supplied at
> ```

nit



_Suggestion:_
```objc
/// Returns this rigid body's default mass, which is initially supplied at
```

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17472)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/tree/rigid_body.h` line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17472#-N5kyc7VETiH_50cs8HR:-N5latCJ7IDAyadJKQ4k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c228d56f4bd4217e05174f526b26b3b1208af107/multibody/tree/rigid_body.h#L96)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`multibody/tree/rigid_body.h` line 116 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17472#-N5klOV78gQFxKdR02V5:-N5lm6qR4R1z8L8MMv4F:bw2x3xd) ([raw file](https://github.com/robotlocomotion/drake/blob/c228d56f4bd4217e05174f526b26b3b1208af107/multibody/tree/rigid_body.h#L116)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: better to put this implementation in the `private` section rather than put it here in doxygen guards. A call to RigidBody::get_default_mass() will still work because it will invoke the base class method. But hopefully if anyone actually has a RigidBody object they will call default_mass().

Also I don't think the comment about Kaizen etc adds anything here. If we do rename the base class method it will be obvious what needs to be done here.
</blockquote></details>

Done.  Required cleanup in various other files.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17472)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rigid_body.h` line 116 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17472#-N5klOV78gQFxKdR02V5:-N5mBL9tAfOF4XSVRxe-:b843tm3) ([raw file](https://github.com/robotlocomotion/drake/blob/c228d56f4bd4217e05174f526b26b3b1208af107/multibody/tree/rigid_body.h#L116)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.  Required cleanup in various other files.
</blockquote></details>

Per f2f, I'm not a huge fan of this pattern. But this is code is going away soon anyway, I don't care as much.

**Review by mitiguy — COMMENTED** [review]
label +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17472#-:-N5mE4AQ4kjplQtPCcXF:br1597u)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

**Pull request merged**
