### PR TITLE
[plant] Add publish_period option to LCM contact results

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix a related warning message to be correctly actionable.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15848)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Still pending, I intent to audit Drake for ongoing mis-uses of this API, so that our examples never print warnings.  I'll push that later on.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platformb

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15848#-:-MkmyzZ1DlSMgozJPZ76:b-vtj4u8)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one passing thought.

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15848#-:-MknAwur-8Z15PED1e3P:b-dz9wpj)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 2000 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15848#-MknAdQu07UEly694rco:-MknAdQu07UEly694rcp:b-9o0p2) ([raw file](https://github.com/robotlocomotion/drake/blob/63a5e3369bf7b6e87351d1f0fa4b95c6300f6796/bindings/pydrake/multibody/test/plant_test.py#L2000)):*
> ```Python
>                     0)
> 
>                 if use_custom_names:
> ```

BTW A passing thought. While this successfully tests that the parameter "keywords" are as expected, it doesn't test at all about whether they are defaulted as per expectation. It seems to me that if we go out of our way to declare default values, it behooves us to test that. That said, I recognize the problem isn't new to this PR (nor, I assume, unique to this test.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15848)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 2000 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15848#-MknAdQu07UEly694rco:-MknTT2R1d6ZXd3QcJfW:b-u1x2y8) ([raw file](https://github.com/robotlocomotion/drake/blob/63a5e3369bf7b6e87351d1f0fa4b95c6300f6796/bindings/pydrake/multibody/test/plant_test.py#L2000)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW A passing thought. While this successfully tests that the parameter "keywords" are as expected, it doesn't test at all about whether they are defaulted as per expectation. It seems to me that if we go out of our way to declare default values, it behooves us to test that. That said, I recognize the problem isn't new to this PR (nor, I assume, unique to this test.)
</blockquote></details>

Working

I'll take a swing at this.  I hadn't realized that the test code was already iterating over present/absent arguments for the other ones.  I'll rewrite it to be more pythonic, and add in this new kwarg as well.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15848)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 2000 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15848#-MknAdQu07UEly694rco:-MknV06h0OPXO_YRaZ-e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/63a5e3369bf7b6e87351d1f0fa4b95c6300f6796/bindings/pydrake/multibody/test/plant_test.py#L2000)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll take a swing at this.  I hadn't realized that the test code was already iterating over present/absent arguments for the other ones.  I'll rewrite it to be more pythonic, and add in this new kwarg as well.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15848)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
