### PR TITLE
[doc] Add release notes v1.3.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Goal is to cut release on morning of 2022-05-16.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.3.0.md` line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVXkm69zk0VL30Pe2:-N1iVXkn6hlL1BITR3gw:bcdedmh) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L8)):*
> ```Markdown
> # Announcements
> 
> * TBD
> ```

@rpoyner-tri Would you be up for crafting notes about improved parser reporting?
___
*[`doc/_release-notes/v1.3.0.md` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVL1YEdDNWIzpC8jw:-N1iVL1YEdDNWIzpC8jx:bp1gtnu) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L34)):*
> ```Markdown
> * TBD
> 
> ## Mathematical Program
> ```

@hongkai-dai Would you be up for polishing release notes for MP?
___
*[`doc/_release-notes/v1.3.0.md` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iV2JX-41tZ8SISv-j:-N1iV2JX-41tZ8SISv-k:b-9x0tet) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L58)):*
> ```Markdown
> * TBD
> 
> ## Multibody Dynamics and Geometry
> ```

@xuchenhan-tri Would you be up for polishing release notes for MbP / geometry?
___
*[`doc/_release-notes/v1.3.0.md` line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVPLXDiPVQKfeiYOW:-N1iVPLXDiPVQKfeiYOX:b49ktjv) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L135)):*
> ```Markdown
> * TBD
> 
> ## Build system
> ```

@jwnimmer-tri Would you be up for polishing relnotes for build system?
___
*[`doc/_release-notes/v1.3.0.md` line 164 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVSzNBy6DKkf9m9Jb:-N1iVSzNBy6DKkf9m9Jc:bcui0qg) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L164)):*
> ```Markdown
> * TBD
> 
> ## Newly-deprecated APIs
> ```

Working: Will expand.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`doc/_release-notes/v1.3.0.md` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1icODD88pLIZBfHA-j:-N1icODE1Vd4KLpABGfQ:b8615ys) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L48)):*
> ```Markdown
> * TBD [solvers] Fix UB in Gurobi bindings ([#17133][_#17133])  # In the GurobiTest.TestCallbacks the cbget function was a no-op for some reason, leaving the double value uninitialized.
> * TBD Allow the user to specify the print out name of the Gram matrix ([#17114][_#17114])  # When adding SOS polynomial constraint, set the name of the Gram matrix. This is useful for debugging SOS.
> * TBD [solvers,math] AddQuadraticAsRotatedLorentzConeConstraint takes optinal psd_tol ([#17125][_#17125])  # When the minimal eigen value of Q is smaller than -psd_tol, then we throw an error. This helps when Q is computed numerically and being marginally psd.
> ```

I made a typo in the commit message.

 s/optinal/optional

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @hongkai-dai, and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVPLXDiPVQKfeiYOW:-N1iuMeJ79bGuv13r8C9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L135)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@jwnimmer-tri Would you be up for polishing relnotes for build system?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @hongkai-dai, and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVL1YEdDNWIzpC8jw:-N1iwxNR2FezFtg4JdxB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@hongkai-dai Would you be up for polishing release notes for MP?
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.3.0.md` line 104 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1ixAmaAuaBtfZzqmZc:-N1ixAmaAuaBtfZzqmZd:b-4wf148) ([raw file](https://github.com/robotlocomotion/drake/blob/8e27298a3e8d7c4b4fa7cd5a7f21f205df98658c/doc/_release-notes/v1.3.0.md#L104)):*
> ```Markdown
> * Return reference in operator+= and operator-= of symbolic::Variables ([#17018][_#17018])  # This avoid unnecessary copy when we return the result.
> * Determine if a polynomial is even or odd ([#17021][_#17021])
> * Polynomial evaluates a batch of indeterminates ([#17065][_#17065])
> ```

nit For here and the above (in "common"), we typically home changes to Expression under `Mathematical Program` not `Miscellaneous`.  The auto-categorization here was incorrect; someone should move this up into MP section.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @hongkai-dai, and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 104 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1ixAmaAuaBtfZzqmZc:-N1jfIIRBqCYBQjtgHM1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e27298a3e8d7c4b4fa7cd5a7f21f205df98658c/doc/_release-notes/v1.3.0.md#L104)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For here and the above (in "common"), we typically home changes to Expression under `Mathematical Program` not `Miscellaneous`.  The auto-categorization here was incorrect; someone should move this up into MP section.
</blockquote></details>

Done.

**Comment by xuchenhan-tri** [comment]
*[`doc/_release-notes/v1.3.0.md` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iV2JX-41tZ8SISv-j:-N1k2Gqs00vvQEA-bs9e:bh9d6cs) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@xuchenhan-tri Would you be up for polishing release notes for MbP / geometry?
</blockquote></details>

Working

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iV2JX-41tZ8SISv-j:-N1kADBN-2ZjBPv8gWJ8:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done. PTAL.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVL1YEdDNWIzpC8jw:-N1twizF-q30rJfdRMoo:bthbwj7) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L34)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Check the preview locally (`bazel run //doc:pages -- --serve`).

The bullet points should fall under either "New Features" or "Fixes"; bullet should not appear under the heading directly.

Also, it would help if you could group related ideas nearby, and/or compact some lines, and/or put more important bullets before less important ones.  We don't need to preserve the sorting order of PR numbers, we want to tell a story to our users about what they might be interested in.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVXkm69zk0VL30Pe2:-N1uCDAxA3eESdZwZgFC:bs7wup1) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@rpoyner-tri Would you be up for crafting notes about improved parser reporting?
</blockquote></details>

Done.l

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.3.0.md` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVL1YEdDNWIzpC8jw:-N1y2GxP5tAKWYNb6pyS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Check the preview locally (`bazel run //doc:pages -- --serve`).

The bullet points should fall under either "New Features" or "Fixes"; bullet should not appear under the heading directly.

Also, it would help if you could group related ideas nearby, and/or compact some lines, and/or put more important bullets before less important ones.  We don't need to preserve the sorting order of PR numbers, we want to tell a story to our users about what they might be interested in.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.3.0.md` line 164 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVSzNBy6DKkf9m9Jb:-N1y2O4I69wIvOcVL0iB:b7y1vi) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L164)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will expand.
</blockquote></details>

Done (accurate as of today, at least).
___
*[`doc/_release-notes/v1.3.0.md` line 84 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1y4UtFDB_0RnnJhfB9:-N1y4UtGBhCZK7h4xedl:bmsk49g) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L84)):*
> ```Markdown
> * Add ``Joint`` API to retrieve viscous damping ([#17019][_#17019])
> * Implement a ``Wing`` class to provide basic aerodynamics ([#17027][_#17027])
> * Move ``DifferentiableNorm`` to ``math`` and use it in ``Wing`` ([#17127][_#17127])
> ```

nit The new feature is "Add math::DifferentiableNorm".  The changes to Wing in this PR are not user-visible.
___
*[`doc/_release-notes/v1.3.0.md` line 94 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1y4jEG221UW68sL9BS:-N1y4jEHCzraSC2cSxlc:bw45uf4) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L94)):*
> ```Markdown
> * Change actuation port in MultibodyPlant not associated with any model instance to refer to all actuation ports instead of the only actation port ([#17059][_#17059], [#17107][_#17107])
> * Emit errors for invalid SDFormat syntax instead of warnings ([#17060][_#17060])
> * Warn about unsupported SDFormat features and modify installed example files to remove unsupported elements that provoke warnings ([#17101][_#17101]) 
> ```

nit I think this section would be easier to comprehend if the parsing-related line items were not inter-mingled with other feature areas.  I suggest re-ordering the list items to keep like with like.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.3.0.md` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1iVL1YEdDNWIzpC8jw:-N1ydWkx5Qeo2LT9uxvM:bxfakk3) ([raw file](https://github.com/robotlocomotion/drake/blob/938a38a57f24a2a60ed3d9221e46c94d539425b4/doc/_release-notes/v1.3.0.md#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks Jeremy, sorry I somehow missed your comment yesterday and just saw this.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.3.0.md` line 17 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2CRjK72lhL105EBut9:-N2CRjK72lhL105EButA:bgki8l8) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L17)):*
> ```Markdown
>   * In SDFormat, some syntax problems which used to warn now issue errors.
>   * In addition, parser warnings can be optionally promoted to errors; see
>     ``Parser::SetStrictParsing``.
> ```

BTW (here and elsewhere) Double backticks should only be necessary for reST. This is markdown, so single backticks are doing the right thing.

**Comment by jwnimmer-tri** [comment]
*[`doc/_release-notes/v1.3.0.md` line 84 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1y4UtFDB_0RnnJhfB9:-N2CZPO3032dkRGL8WcS:bgm2b1r) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The new feature is "Add math::DifferentiableNorm".  The changes to Wing in this PR are not user-visible.
</blockquote></details>

Actually, that's not accurate.  The "added a new math function" is notable, but this PR _also_ fixes Wing to report valid derivatives at zero.  So, two release note bullets.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @xuchenhan-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 84 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1y4UtFDB_0RnnJhfB9:-N2D-qWHEL_j-HfuTI1j:b-a9q4c4) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually, that's not accurate.  The "added a new math function" is notable, but this PR _also_ fixes Wing to report valid derivatives at zero.  So, two release note bullets.
</blockquote></details>

working
___
*[`doc/_release-notes/v1.3.0.md` line 94 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1y4jEG221UW68sL9BS:-N2D-pun-IpuA8PmQCTn:b-a9q4c4) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L94)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think this section would be easier to comprehend if the parsing-related line items were not inter-mingled with other feature areas.  I suggest re-ordering the list items to keep like with like.
</blockquote></details>

working

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.3.0.md` line 84 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N1y4UtFDB_0RnnJhfB9:-N2D52p-Dmd76Q6Ymbuc:bknw6lp) ([raw file](https://github.com/robotlocomotion/drake/blob/2f6d4326ae283971d9ece17ca540afcf69a54ba2/doc/_release-notes/v1.3.0.md#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Oops, I gave bad advice again.  I've pushed a fix.

Since the "Wing" class is new as-of this release, we don't need to itemize fixes to it, since nobody could have been using it already.  We can list both PR numbers on the same line "Implement a Wing class.." for completeness, but that's not strictly necessary.
</blockquote></details>

Got it. That makes sense. Thanks for the fix up.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.3.0.md` line 113 at r12](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2CUSAl98w3KNJxUWuj:-N2EAKQsAtC1WpztgQSr:b-c892uq) ([raw file](https://github.com/robotlocomotion/drake/blob/490fe55c74106d8c17acbbe460545c8a67e41eb2/doc/_release-notes/v1.3.0.md#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you for letting me know that the program in 17141 is not a part of the release.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 137 at r16](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H4Y327SNeue-z-BfR:-N2H4Y327SNeue-z-BfS:bqh6lo4) ([raw file](https://github.com/robotlocomotion/drake/blob/334db8498904cf676ba6be337d88b4389242a037/doc/_release-notes/v1.3.0.md#L137)):*
> ```Markdown
> Newly bound
> 
> * Add Python binding for Parser::SetStrictParsing ([#17181][_#17181])
> ```

Working: IIRC, we used to spell out out bound API (in Python). Checking previous release notes...

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 137 at r16](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H4Y327SNeue-z-BfR:-N2H53eMA7Hb5jqSdiPo:b-39ys1r) ([raw file](https://github.com/robotlocomotion/drake/blob/334db8498904cf676ba6be337d88b4389242a037/doc/_release-notes/v1.3.0.md#L137)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: IIRC, we used to spell out out bound API (in Python). Checking previous release notes...
</blockquote></details>

Yup, most recent release w/ non-empty "Newly bound" is done this way: https://drake.mit.edu/release_notes/v1.1.0.html

Reflecting changes here...

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`tmp_commands.md` line 9 at r16](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H4iu73VxuF0PjDXmC:-N2H6z584Mmuzs6YpP6R:b47e655) ([raw file](https://github.com/robotlocomotion/drake/blob/334db8498904cf676ba6be337d88b4389242a037/tmp_commands.md#L9)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: This morning's release (2022-05-17) seems good to go. Polishing release notes a bit more, then pending assignment + approval, will cut release.
</blockquote></details>

(will also remove this file)
___
*[`doc/_release-notes/v1.3.0.md` line 10 at r12](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2CagxV3ggYfhTchTKb:-N2H6wpD7CzGaiVJIm-a:b-jo8pp6) ([raw file](https://github.com/robotlocomotion/drake/blob/490fe55c74106d8c17acbbe460545c8a67e41eb2/doc/_release-notes/v1.3.0.md#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

thank you @zachfang for this!
</blockquote></details>

+1000 !
___
*[`doc/_release-notes/v1.3.0.md` line 137 at r16](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H4Y327SNeue-z-BfR:-N2H6wBMAKu5377IfXa0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/334db8498904cf676ba6be337d88b4389242a037/doc/_release-notes/v1.3.0.md#L137)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup, most recent release w/ non-empty "Newly bound" is done this way: https://drake.mit.edu/release_notes/v1.1.0.html

Reflecting changes here...
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
@jwnimmer-tri Can I get your LGTM on this, when you have a chance?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143#-:-N2H8FDF9XfYi88o81R3:bw4ximi)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 100 at r17](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H8Rk71PbQG86SXSQS:-N2H8Rk71PbQG86SXSQT:b8301mk) ([raw file](https://github.com/robotlocomotion/drake/blob/c367281a857d7247d090b8c5fc6250006fb4b4bf/doc/_release-notes/v1.3.0.md#L100)):*
> ```Markdown
> * Route package deprecations into the diagnostic channel ([#17047][_#17047])
> * Prefer math::LinearSolver to plain eigen solvers when using autodiff ([#17038][_#17038], [#17057][_#17057])
> * Fix GetSolution for `x_v` in GraphOfConvexSets ([#17199][_#17199])
> ```

Working: Per playbook, belongs in Mathematical Program above.
___
*[`doc/_release-notes/v1.3.0.md` line 131 at r17](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H8fgZ5nSdVR3yaY2s:-N2H8fgZ5nSdVR3yaY2t:b-708alm) ([raw file](https://github.com/robotlocomotion/drake/blob/c367281a857d7247d090b8c5fc6250006fb4b4bf/doc/_release-notes/v1.3.0.md#L131)):*
> ```Markdown
> Fixes
> 
> * Add missing `py::return_value_policy::copy` on a various bound attributes ([#17126][_#17126])
> ```

nit grammar, remove "a"
___
*[`doc/_release-notes/v1.3.0.md` line 190 at r17](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H8m-32kpUdxb1TqaK:-N2H8m-32kpUdxb1TqaL:b99la3w) ([raw file](https://github.com/robotlocomotion/drake/blob/c367281a857d7247d090b8c5fc6250006fb4b4bf/doc/_release-notes/v1.3.0.md#L190)):*
> ```Markdown
> * pydrake.systems.meshcat_visualizer.MeshcatPointCloudVisualizer ([#17194][_#17194])
>   * Use pydrake.geometry.MeshcatPointCloudVisualizer instead.
> ```

nit Rogue newline.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17143)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.3.0.md` line 100 at r17](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H8Rk71PbQG86SXSQS:-N2H9QYdCakTwyifxoyj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c367281a857d7247d090b8c5fc6250006fb4b4bf/doc/_release-notes/v1.3.0.md#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Per playbook, belongs in Mathematical Program above.
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.3.0.md` line 131 at r17](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H8fgZ5nSdVR3yaY2s:-N2H9RBB9SqNzZSo0g6U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c367281a857d7247d090b8c5fc6250006fb4b4bf/doc/_release-notes/v1.3.0.md#L131)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar, remove "a"
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.3.0.md` line 190 at r17](https://reviewable.io/reviews/robotlocomotion/drake/17143#-N2H8m-32kpUdxb1TqaK:-N2H9R__3hsTE2AWkg1G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c367281a857d7247d090b8c5fc6250006fb4b4bf/doc/_release-notes/v1.3.0.md#L190)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rogue newline.
</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
Remaining steps:

- [ ] Build docs: https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-focal-unprovisioned-gcc-bazel-nightly-documentation/472/
- [ ] GitHub release draft:
- [ ] Publish release; ping people
- Post-release:
  - [ ] Workspace deps - tagging
  - [ ] Tutorials
  - [ ] Pip

**Comment by EricCousineau-TRI** [comment]
@BetsyMcPhail Release has been made: https://github.com/RobotLocomotion/drake/releases/tag/v1.3.0

Commit: 7fcdd44b8a48c2ae5b99ab60db31740f8192acc8
Tag: v1.3.0
Date: 20220517

**Comment by BetsyMcPhail** [comment]
Apt, Docker and S3 (tar) have all been created.

**Pull request merged**
