### PR TITLE
Remove extra "octomap" from installed license path

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8688)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8688#-:-LB2WvOd9SR2Qvk5IFbO:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8688#-:-LB2XZJj-tIPle72Rs1p:bnfp4nl)*

**Pull request merged**
