### PR TITLE
[workspace] Deprecate public use of several externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add a `@suitesparse_internal` repository to rebuild (the AMD part of) SuiteSparse from source, with hidden visibility.

Deprecate the public (host) `@suitesparse` external. Remove suitesparse from our OS dependencies.

Rename OSQP, QDLDL, SCS to use the `_internal` suffix and deprecate their non-internal spellings. (They are all C libraries that already use hidden visibility, so they don't need any C++ vendoring changes to their BUILD.)

Towards #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18690)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18690#-:-NN7kXFv49YDToyZxwc1:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18690)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/workspace/suitesparse_internal/package.BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18690#-NN7wMXl8Khg7KFMgroe:-NN7wMXl8Khg7KFMgrof:b-3f736j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee9ed6069f09bb0f05a1a8a897bc96ffbfbf1ae9/tools/workspace/suitesparse_internal/package.BUILD.bazel#L14)):*
> ```
> cc_library(
>     name = "config",
>     srcs = ["SuiteSparse_config/SuiteSparse_config.c"],
> ```

Working

I missed the `hidden` here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18690)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[`tools/workspace/suitesparse_internal/package.BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18690#-NN7wMXl8Khg7KFMgroe:-NN80Xrb9axllqeN-spS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee9ed6069f09bb0f05a1a8a897bc96ffbfbf1ae9/tools/workspace/suitesparse_internal/package.BUILD.bazel#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I missed the `hidden` here.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18690)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
