### PR TITLE
Pick and place model files

### PR DESCRIPTION
**Pull request by avalenzu**
This PR adds new models for use in Kuka demos, and also moves the origin of the `extra_heavy_duty_table` to bottom center.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7339)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@sammy-tri  for feature review.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-:-KxLTvr662j_LrDSfp5t:b-bsdnga)*

**Comment by sammy-tri** [comment]
:lgtm:  +@soonho-tri for platform review

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/models/objects/big_robot_toy.urdf, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-KxOEhjcyTsQmRldwIeT:-KxOEhjcyTsQmRldwIeU:buz6bdx) ([raw file](https://github.com/robotlocomotion/drake/blob/23652b509a55229eb4690759522dbcbb4bdba28d/drake/examples/kuka_iiwa_arm/models/objects/big_robot_toy.urdf#L13)):*
> ```XML
>       <origin xyz="0 0 0" rpy="0 0 0" />
>       <geometry>
>         <box size="0.1 0.035 0.18" />
> ```

BTW Alex should have something suitable for conversion to a mesh which actually looks like the toy (not a requirement for this PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-:-KxOFKoeb-psr7w8-42l:b-n45yuk)*

**Comment by avalenzu** [comment]
+(status: do not merge) Adding mesh file, because it will look awesome

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/models/objects/big_robot_toy.urdf, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-KxOEhjcyTsQmRldwIeT:-KxON6sznsvpWhxZ6ccO:b-jsats2) ([raw file](https://github.com/robotlocomotion/drake/blob/23652b509a55229eb4690759522dbcbb4bdba28d/drake/examples/kuka_iiwa_arm/models/objects/big_robot_toy.urdf#L13)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Alex should have something suitable for conversion to a mesh which actually looks like the toy (not a requirement for this PR)
</blockquote></details>

Yes, I actually have it, I just haven't gotten around to adding it.x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-:-KxO_DA2-J7TKn8m_24S:b4ryhi8)*

**Comment by soonho-tri** [comment]
:lgtm:

@avalenzu , do we still need do_not_merge label here? If not, please feel free to remove it and merge the PR.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-:-KxOduUszDEAZzS8xCOt:b-gbsud3)*

**Comment by avalenzu** [comment]
-(status: do not merge) Mesh file added (700 KB).

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7339#-:-KxOjT1_SSh1VSVLQlRf:b8rwahj)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7339)*

**Pull request merged**
