### PR TITLE
Return dual solution for PSD constraint in SCS and Clarabel.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Include dual for both PositiveSemidefiniteConstraint and LinearMatrixInequalityConstraint.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBDT4pb119O1RIBmKIG:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBXPp6M18WO1ZL_Yenk:bnfp4nl)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/scs_solver.cc` line 530 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBXOHpe8zFROGVB2Dw4:-OBXOHpe8zFROGVB2Dw5:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/6196e390f081568b81d05dcc8a7d0103f6de5090/solvers/scs_solver.cc#L530)):*
> ```cpp
>   // Note that when psd_cone_length[i] = -1 or lmi_cone_length[i] = -1, that
>   // constraint will not be parsed as PSD cone in SCS. So we should filter out
>   // these entries with value -1.
> ```

nit: grammar



_Suggestion:_
```cpp
  // Note that when psd_cone_length[i] = -1 or lmi_cone_length[i] = -1, the
  // constraint will not be parsed as PSD cone in SCS. So we should filter out
  // these entries with value -1.
```
___
*[`solvers/aggregate_costs_constraints.h` line 358 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBXLXBu4bquK9hg7nLW:-OBXLXBu4bquK9hg7nLX:brm3w53) ([raw file](https://github.com/RobotLocomotion/drake/blob/6196e390f081568b81d05dcc8a7d0103f6de5090/solvers/aggregate_costs_constraints.h#L358)):*
> ```objc
> // prog.linear_matrix_inequality_constraints()[i]. If
> // prog.linear_matrix_inequality_constraints()[i] is not parsed as a PSD cone
> // constraint in the solver, then lmi_y_start_indices[i] is -1.
> ```

Design question. Would it be better to make `psd_cone_length[i] = std::nullopt` instead of `-1`? My fear is that one might use something like `sum(psd_cone_length)` to query the size of the PSD cone and get the wrong result.



_Code quote:_
```objc
// @param[out] psd_cone_length psd_cone_length[i] is the length of the psd cones
// from prog.positive_semidefinite_constraints()[i]. If this
// PositiveSemidefiniteConstraint is not parsed as a psd cone constraint in the
// solver (for example, it is parsed as a linear constraint or second order cone
// constraint), then psd_cone_length[i] = -1.
// @param[out] lmi_cone_length lmi_cone_length[i] is the length of the psd cones
// from prog.linear_matrix_inequality_constraints()[i]. If this
// LinearMatrixInequalityConstraint is not parsed as a psd cone constraint in
// the solver (for example, it is parsed as a linear constraint or second order
// cone constraint), then lmi_cone_length[i] = -1.
// @param[out] psd_y_start_indices y[psd_y_start_indices[i]:
// psd_y_start_indices[i] + psd_cone_length[i]] are the dual variable for
// prog.positive_semidefinite_constraints()[i]. If
// prog.positive_semidefinite_constraints()[i] is not parsed as a PSD cone
// constraint in the solver, then psd_y_start_indices[i] is -1.
// @param[out] lmi_y_start_indices y[lmi_y_start_indices[i]:
// lmi_y_start_indices[i] + lmi_cone_length[i]] are the dual variable for
// prog.linear_matrix_inequality_constraints()[i]. If
// prog.linear_matrix_inequality_constraints()[i] is not parsed as a PSD cone
// constraint in the solver, then lmi_y_start_indices[i] is -1.
```
___
*[`solvers/scs_clarabel_common.cc` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBXMTFx-8Lzzy-gRgBE:-OBXMTFx-8Lzzy-gRgBF:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/6196e390f081568b81d05dcc8a7d0103f6de5090/solvers/scs_clarabel_common.cc#L16)):*
> ```cpp
> 
> // SCS and Clarabel takes the upper (or lower) triangular part of a symmetric
> // matrix, scale the off-diagonal term by sqrt(2), and then return the flattened
> ```

nit: grammar



_Suggestion:_
```cpp
 matrix, scales the off-diagonal term by sqrt(2), and then returns the flattened
```
___
*[`solvers/scs_clarabel_common.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBXNvlZ5ny3OBu2ZqDp:-OBXNvl_07pr3D3Yu0HC:b-1hxoew) ([raw file](https://github.com/RobotLocomotion/drake/blob/6196e390f081568b81d05dcc8a7d0103f6de5090/solvers/scs_clarabel_common.cc#L53)):*
> ```cpp
>     for (int i = 0; i < dual->rows(); ++i) {
>       (*dual)(i) = dual_lower_triangular(i);
>     }
> ```

every entry of `dual` should only be revisited once in this reordering. Is this copy necessary or could you just write directly into `dual`?



_Code quote:_
```cpp
    // Copy dual_lower_triangular to dual
    for (int i = 0; i < dual->rows(); ++i) {
      (*dual)(i) = dual_lower_triangular(i);
    }
```

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBY-TZ29b7LZBLvlf7C:b-3lhrgq)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes

___
*[`solvers/aggregate_costs_constraints.h` line 358 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBXLXBu4bquK9hg7nLW:-OBY-S9UECGuxnrXdr_G:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/6196e390f081568b81d05dcc8a7d0103f6de5090/solvers/aggregate_costs_constraints.h#L358)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Design question. Would it be better to make `psd_cone_length[i] = std::nullopt` instead of `-1`? My fear is that one might use something like `sum(psd_cone_length)` to query the size of the PSD cone and get the wrong result.
</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform review pass done. I'll stamp when CI passes.

@hongkai-dai could you add release notes tag for this one? Looks to me like all changes are in the internal namespace so it shouldn't be in the release notes, thoughts?

> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBaZAgcDThRKvCuSnWP:bxzsb7b)* status: 11 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaTHrj25MqPc-Aetdv:-OBaTHrj25MqPc-Aetdw:b-5vut2j) (no related file):*
nit, CI is unhappy with a few missing `#include` and a few failed, newly-added tests.
___
*[`solvers/aggregate_costs_constraints.h` line 358 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaTnIfCyux--_tTSmH:-OBaTnIfCyux--_tTSmI:bttvx8r) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/aggregate_costs_constraints.h#L358)):*
> ```objc
> // prog.linear_matrix_inequality_constraints()[i]. If
> // prog.linear_matrix_inequality_constraints()[i] is not parsed as a PSD cone
> // constraint in the solver, then lmi_y_start_indices[i] is std::nullopt.
> ```

nit a few minor edits



_Suggestion:_
```objc
// @param[out] psd_cone_length psd_cone_length[i] is the length of the psd cones
// from prog.positive_semidefinite_constraints()[i]. If this
// PositiveSemidefiniteConstraint is not parsed as a PSD cone constraint in the
// solver (for example, it is parsed as a linear constraint or second order cone
// constraint), then psd_cone_length[i] = std::nullopt.
// @param[out] lmi_cone_length lmi_cone_length[i] is the length of the psd cones
// from prog.linear_matrix_inequality_constraints()[i]. If this
// LinearMatrixInequalityConstraint is not parsed as a PSD cone constraint in
// the solver (for example, it is parsed as a linear constraint or second order
// cone constraint), then lmi_cone_length[i] = std::nullopt.
// @param[out] psd_y_start_indices y[psd_y_start_indices[i]:
// psd_y_start_indices[i] + psd_cone_length[i]] are the dual variables for
// prog.positive_semidefinite_constraints()[i]. If
// prog.positive_semidefinite_constraints()[i] is not parsed as a PSD cone
// constraint in the solver, then psd_y_start_indices[i] is std::nullopt.
// @param[out] lmi_y_start_indices y[lmi_y_start_indices[i]:
// lmi_y_start_indices[i] + lmi_cone_length[i]] are the dual variables for
// prog.linear_matrix_inequality_constraints()[i]. If
// prog.linear_matrix_inequality_constraints()[i] is not parsed as a PSD cone
// constraint in the solver, then lmi_y_start_indices[i] is std::nullopt.
```
___
*[`solvers/scs_clarabel_common.cc` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaX0voBR0P6utmCR1r:-OBaX0voBR0P6utmCR1s:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L10)):*
> ```cpp
> namespace {
> // Return the index of S(i, j) in the flattened vector consisting of upper
> // triangular part os matrix S (using column major).
> ```

nit



_Suggestion:_
```cpp
// Returns the index of S(i, j) in the flattened vector consisting of upper
// triangular part of matrix S (using column major).
```
___
*[`solvers/scs_clarabel_common.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaXZLO3dMU5NqgLrKW:-OBaXZLP0_gA1dd56A0l:b2mfra1) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L23)):*
> ```cpp
> void ScalePsdConeDualVariable(int matrix_rows, bool upper_triangular_psd,
>                               Eigen::VectorXd* dual) {
>   DRAKE_ASSERT(dual->rows() == matrix_rows * (matrix_rows + 1) / 2);
> ```

nit ditto on DRAKE_DEMAND vs DRAKE_ASSERT and documentation. BTW, probably easier to just resize the `dual` to ensure it always has the right size?



_Code quote:_
```cpp
DRAKE_ASSERT(dual->rows() == matrix_rows * (matrix_rows + 1) / 2);
```
___
*[`solvers/scs_clarabel_common.cc` line 32 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaXTVE9xHLrkqbTa5R:-OBaXTVE9xHLrkqbTa5S:b-uxu2uo) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L32)):*
> ```cpp
>         (*dual)(count) /= sqrt2;
>       }
>       count++;
> ```

nit prefer preincrement



_Code quote:_
```cpp
count++;
```
___
*[`solvers/scs_clarabel_common.cc` line 151 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaY0pe524IW86pzkel:-OBaY0pe524IW86pzkem:b-69tk9j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L151)):*
> ```cpp
>         prog.positive_semidefinite_constraints()[i].evaluator()->matrix_rows();
>     if (psd_y_start_indices[i].has_value()) {
>       Eigen::VectorXd psd_dual = dual.segment(
> ```

BTW, I believe you can prevent a copy here by using 

auto psd_dual = dual.segment(...)

and change the signature of `ScalePsdConeDualVariable` to take an `EigenPtr`. Although if you do that, you can't change the size of the input like I suggested above.
___
*[`solvers/scs_solver.cc` line 534 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaYs_L682jlvIjPymx:-OBaYs_L682jlvIjPymy:bzaoba6) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_solver.cc#L534)):*
> ```cpp
>   for (const auto& length : psd_cone_length) {
>     if (length.has_value()) {
>       cone->ssize++;
> ```

nit prefer preincrement.
___
*[`solvers/aggregate_costs_constraints.cc` line 699 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaVGSg5mwZeT9o1VD-:-OBaVGSg5mwZeT9o1VD0:b9ihe2r) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/aggregate_costs_constraints.cc#L699)):*
> ```cpp
>   }
>   DRAKE_ASSERT(psd_cone_length->empty());
>   DRAKE_ASSERT(lmi_cone_length->empty());
> ```

BTW, consider doing the following:
1. document this requirement in the header, and
2. Use DRAKE_DEMAND if this isn't in a very tight inner loop.

**Comment by xuchenhan-tri** [comment]
*[`solvers/scs_clarabel_common.cc` line 151 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaY0pe524IW86pzkel:-OBbReouEf_breoLsMxs:b-e81njf) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L151)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I believe you can prevent a copy here by using 

auto psd_dual = dual.segment(...)

and change the signature of `ScalePsdConeDualVariable` to take an `EigenPtr`. Although if you do that, you can't change the size of the input like I suggested above.
</blockquote></details>

Looking more closely at this, there are some constness violation here. `SetDualSolution` has `dual` passed in as a const eigen ref, but somehow its being modified in `ScalePsdConeDualVariable`

**Review by hongkai-dai — COMMENTED** [review]
The changes in scs_solver.cc and clarabel_solver.cc are not in the internal space, and expose the new feature to the users.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBbVbBD43gwvT5YfzIA:b-hjt5p4)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.cc` line 699 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaVGSg5mwZeT9o1VD-:-OBbEOkM4srRj7YUcCjn:b-6z96qw) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/aggregate_costs_constraints.cc#L699)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, consider doing the following:
1. document this requirement in the header, and
2. Use DRAKE_DEMAND if this isn't in a very tight inner loop.
</blockquote></details>

I added the documentation.

I think `DRAKE_ASSERT` is better than `DRAKE_DEMAND` here. This is in the internal namespace, so only the developers should call this function, and we do have CI running in the debug mode.
___
*[`solvers/scs_clarabel_common.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBXNvlZ5ny3OBu2ZqDp:-OBbNcfl9Kfcp_z9vMjY:b-sc96xd) ([raw file](https://github.com/RobotLocomotion/drake/blob/6196e390f081568b81d05dcc8a7d0103f6de5090/solvers/scs_clarabel_common.cc#L53)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

every entry of `dual` should only be revisited once in this reordering. Is this copy necessary or could you just write directly into `dual`?
</blockquote></details>

I am not completely sure if I can do this without the copying. I added a TODO here for future investigation.
___
*[`solvers/scs_clarabel_common.cc` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaXZLO3dMU5NqgLrKW:-OBbITfv8YfYPPZpuAmE:bppn5zj) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit ditto on DRAKE_DEMAND vs DRAKE_ASSERT and documentation. BTW, probably easier to just resize the `dual` to ensure it always has the right size?
</blockquote></details>

I actually think it is more appropriate to use DRAKE_ASSERT here, as this is in the anonymous namespace, so only the developer can access this function, and the developer should have taken the size of the vector (if not, the CI in debug mode will catch the error).
___
*[`solvers/scs_clarabel_common.cc` line 151 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBaY0pe524IW86pzkel:-OBbO1do-aVwhgiF6xXs:b21h23r) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f15b71e9fc2b88b8e11da79ccc73a23f803cd9/solvers/scs_clarabel_common.cc#L151)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Looking more closely at this, there are some constness violation here. `SetDualSolution` has `dual` passed in as a const eigen ref, but somehow its being modified in `ScalePsdConeDualVariable`
</blockquote></details>

I see. 

I do want to maintain that constness. I will create a new copy of Eigen::VectorXd psd_dual.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: feature) :lgtm: platform

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBbXU5xCSNsnUIjO1Vk:b-coonei)* status: 1 unresolved discussion

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-:-OBbYPtj4uA5i6UnVo9M:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees AlexandreAmice,xuchenhan-tri(platform)

**Comment by xuchenhan-tri** [comment]
CI is still failing with both linter errors and what appears to be actual failures.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147)* status: 1 unresolved discussion

___
*[`solvers/test/aggregate_costs_constraints_test.cc` line 864 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22147#-OBc1_moC4U5wIiw4lc7:-OBc1_moC4U5wIiw4lc8:bgyjau) ([raw file](https://github.com/RobotLocomotion/drake/blob/a92b5d3698945e9b29433208ac42258b78c3200c/solvers/test/aggregate_costs_constraints_test.cc#L864)):*
> ```cpp
>     EXPECT_EQ(psd_cone_length,
>               std::vector<std::optional<int>>(
>                   {std::optional<int>(3), std::optional<int>(2)}));
> ```

BTW, the following should also work (and is less verbose).



_Suggestion:_
```cpp
    EXPECT_EQ(psd_cone_length, std::vector<std::optional<int>>({{3}, {2}}));
```

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22147)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees AlexandreAmice,xuchenhan-tri(platform)

**Pull request merged**
