### PR TITLE
RenderEngineGl supports multiple meshes from OBJ

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
- `RenderEngineGl` modified to support the multiple `RenderMesh`es
  - It introduces the same notion as `Prop` and `Part` as found in `RenderEnginveVtk`.
  - Mesh handling maps multiple possible `RenderMesh`es to multiple parts.
  - Tests updated.
    - Introduce the .obj equivalent of `rainbox_box.gltf`.

This is the third PR in a train ~relating to https://github.com/RobotLocomotion/drake/issues/17266~ (#17266 has been clarified to be just about *proximity* geometry). This has more to do with #20152. The full PR train can be seen in https://github.com/RobotLocomotion/drake/pull/20235. This PR corresponds to the first commit in that PR (note: "commit" not "revision" -- the PR has been losing commits as previous PRs have merged).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 
+@zachfang for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-:-NfNoOJfEDzHww7sQs1M:b29kf4l)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by SeanCurtis-TRI** [comment]
+(status: do not review) The previous PR is causing problems.

**Comment by zachfang** [comment]
Sounds good. I am following that thread closely, and let me know if I can help with debugging or reproduction.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks. I hope to have it figured out quickly. And I know the importance of running Anzu CI against whatever putative fix I propose.  :)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-:-NfWQJW38RoBlGdzHRVJ:b7qjo23)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) Ok, we're back. The previous PR has been repaired.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-:-Nfksrx34Q99-bCZdobI:b-wskg5u)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by zachfang — COMMENTED** [review]
Checkpoint. Reviewed in full but I will come back to `lgtm` it with a second pass.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-:-NfnZpjT64W1Hp5flSg3:b9zzn7d)* status: 7 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 222 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnDBQ2DZGZjhxgNSBs:-NfnDBQ31ftJCm3dGzGh:b56osp7) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.h#L222)):*
> ```objc
>   // defined in the file.
>   // If the filename represents an unsupported file type, no geometry is added,
>   // data->accepted is set to false, and the return value is empty.
> ```

nit. (Or similar.)



_Suggestion:_
```objc
returned vector
```
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 378 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnRoJZ0hmkS3z9q-oY:-NfnRoJZ0hmkS3z9q-oZ:b-ef1vk9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.h#L378)):*
> ```objc
>     // Index into geometries_ containing the instance for a RenderMesh.
>     int mesh_index{};
>     geometry::internal::UvState uv_state{geometry::internal::UvState::kFull};
> ```

BTW. Should we usually default to the conservative option, i.e., kNone,  so it would error out sooner?



_Code quote:_
```objc
geometry::internal::UvState uv_state{geometry::internal::UvState::kFull
```
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 407 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnFxbV7cb0tFz4H4XH:-NfnFxbV7cb0tFz4H4XI:by1fb2f) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.h#L407)):*
> ```objc
>   // geometry's world pose X_WG is simply: T_WN = X_WG * T_GN.
>   // While T_GN isn't relative for mesh files like .obj, files like .glTF can
>   // contain poses relative to the file.
> ```

nit. Can you elaborate what does this sentence mean? T_GN is related to the Geometry and that's not equivalent to the file?



_Code quote:_
```objc
  // While T_GN isn't relative for mesh files like .obj, files like .glTF can
  // contain poses relative to the file.
```
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 892 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnOEoYAsaRW-0aYGro:-NfnOEoYAsaRW-0aYGrp:bxy7c84) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.cc#L892)):*
> ```cpp
>   for (auto& part : visuals_.at(id).parts) {
>     if (part.T_GN.has_value()) {
>       part.instance.X_WG = X_WG * (*part.T_GN);
> ```

nit. Maybe I missed something, is `*` for dereferencing? But none of them is a pointer, right? :thinking: 



_Code quote:_
```cpp
*
```
___
*[`geometry/render_gl/test/internal_render_engine_gl_test.cc` line 73 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnT22dEdBmWWBRDBoQ:-NfnT22dEdBmWWBRDBoR:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/test/internal_render_engine_gl_test.cc#L73)):*
> ```cpp
>     if (!data.accepted) {
>       throw std::runtime_error(
>           "GetSingleMesh() returned a mesh index, but claims its not "
> ```

nit.



_Suggestion:_
```cpp
it's
```
___
*[`geometry/render_gl/test/internal_render_engine_gl_test.cc` line 1026 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnXlIc95D5OTYf9aBb:-NfnXlId6g-2qvtNw0if:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/test/internal_render_engine_gl_test.cc#L1026)):*
> ```cpp
> //  1. Multiple objects.
> //  2. Multiple materials.
> //  3. Some materials used diffuse color, some use map.
> ```

nit.



_Suggestion:_
```cpp
Some materials use diffuse color, some use maps.
```
___
*[`geometry/render_gl/test/internal_render_engine_gl_test.cc` line 1049 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnYF1c3akom5pS7l_Z:-NfnYF1d6sC8WwymIbEE:bfj6ot7) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/test/internal_render_engine_gl_test.cc#L1049)):*
> ```cpp
>   Mesh mesh(filename);
>   expected_label_ = RenderLabel(3);
>   // Note: Passing diffuse color or texture to a glTF spawns a warning.
> ```

nit. (Or `a mesh file` to be more general.)



_Suggestion:_
```cpp
an obj
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-:-NfqNDFZ8RuKZn3qdArr:b-ruv0ff)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-Nfq107x7NJB9Kdom3l7:-NfqNKZ3-CT-PgOt3wUW:br1l4nd) (no related file):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW.  (Probably not for this PR, and I am happy to help with that to check if I understand it correctly.)

You mentioned that RenderEngineGl uses the concepts of `OpenGlGeometry` and `OpenGlInstance` when I updated `RenderMaterial` last time. That helped me follow the code much easier. I wonder if we should capture that somewhere.

From this PR, we also introduce more layers of hierarchy, for example, `OpenGlGeometry` ->`RenderGlMesh`->meshes_ or `OpenGlInstance`->Part->Prop->visual_. I think having a high-level explanation would be beneficial.
</blockquote></details>

I'm glad you said that. It's been preying on my mind. I've put in a TODO for now. If you want to take a stab at it, you certainly may. Otherwise, I'll probably tackle it today or tomorrow.

___
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 378 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnRoJZ0hmkS3z9q-oY:-NfqM6gs-XK62cFtuaRq:bwexk32) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.h#L378)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Should we usually default to the conservative option, i.e., kNone,  so it would error out sooner?
</blockquote></details>

It won't error out, you'll just get a different material. Maybe the real problem is calling out any value at all. In usage, it is only instantiated by setting the value from the `RenderMesh`.

I've gone ahead and let it be default initialized so it doesn't look as strategic as it does not.
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 407 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnFxbV7cb0tFz4H4XH:-NfqLdHV-JTFN3PMVYlo:blk3ezx) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.h#L407)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Can you elaborate what does this sentence mean? T_GN is related to the Geometry and that's not equivalent to the file?
</blockquote></details>

I took another pass at it. Let me know if that helps. (The old version had a stupid typo using the word "relative" when I *meant* "relevant".)
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-Nfpylm3A9y3S_Vk_2Mh:-NfqMqmz0dkARLJXK5Th:b-6p98yi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.cc#L11)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Is this used for the new changes?
</blockquote></details>

Oops...that was used at one point, but I forgot to yank it. It's what you use when you're going to print an `Eigen` quantity using `fmt::format` or some such API.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfpyyvvCU_dzy2rQYjx:-NfqMlOH2DP_29gzJGZI:bp6uzpz) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.cc#L39)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. We have using-declarations for most of the std objects in this file and there are some redundant `std::` in the code. (And most of them are not relevant to this PR.)
</blockquote></details>

Fortunately, just the one. I mostly tried to clean them out. :)
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 892 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnOEoYAsaRW-0aYGro:-NfqM_ax1EzEXvfv5pxz:b68wj88) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.cc#L892)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Maybe I missed something, is `*` for dereferencing? But none of them is a pointer, right? :thinking:
</blockquote></details>

`T_GN` is `std::optional<...>` and you can dereference it to get its value. However, it's probably more obvious to call `T_GN.value()`.

**Review by zachfang — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 407 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnFxbV7cb0tFz4H4XH:-NfqVXc0AoEyRmx8VIMU:b-7nbn1n) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.h#L407)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I took another pass at it. Let me know if that helps. (The old version had a stupid typo using the word "relative" when I *meant* "relevant".)
</blockquote></details>

lgtm.
___
*[`geometry/render_gl/internal_render_engine_gl.h` line 371 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfqVf1uDp5pClsQ5oZH:-NfqVf1v7PYrgR4tu0ee:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/d062d98648b9c6c032778581c6dd03900f135f4e/geometry/render_gl/internal_render_engine_gl.h#L371)):*
> ```objc
> 
>   // TODO(SeanCurtis-TRI): The relationships between OpenGlInstance,
>   // OpenGlGeometry, RenderGlMesh, Part, and Prop is probably overly opaque.
> ```

nit.



_Suggestion:_
```objc
are probably overly opaque.
```
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 892 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfnOEoYAsaRW-0aYGro:-NfqUa_11e21ADw14uRx:b-nvr5un) ([raw file](https://github.com/RobotLocomotion/drake/blob/4dc5f4e56ac040e1611eeca4cf96d4a83693c76c/geometry/render_gl/internal_render_engine_gl.cc#L892)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

`T_GN` is `std::optional<...>` and you can dereference it to get its value. However, it's probably more obvious to call `T_GN.value()`.
</blockquote></details>

Ah, good to know.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-:-NfqgOdt0cXAYL0RL4gL:bnfp4nl)* status: 4 unresolved discussions

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 420 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfqdSQfBS93mv6BcqDV:-NfqdSQfBS93mv6BcqDW:b-amlt0d) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.h#L420)):*
> ```objc
>   struct Part {
>     OpenGlInstance instance;
>     // This will have to become Matrix4 along with the value in OpenGlInstance.
> ```

BTW Because I've been around this block before, I know that this comment is intended as a TODO, but I doubt that would be clear to a first-time reader.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 856 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfqeCw24a04gngdqBvh:-NfqeCw24a04gngdqBvi:bdd94dt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L856)):*
> ```cpp
>   const RegistrationData& data = *static_cast<RegistrationData*>(user_data);
>   const std::string file_key = GetPathKey(filename);
>   for (const auto& gl_mesh : meshes_[file_key]) {
> ```

BTW Probably we should fail-fast when the key did not exist, instead of inserting an empty one?



_Suggestion:_
```cpp
meshes_.at(file_key)
```
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 903 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-Nfqekmf9nPHuy3V07rf:-Nfqekmf9nPHuy3V07rg:bdzsbs8) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L903)):*
> ```cpp
>     // Multiple parts may have the same shader. We don't want to attempt
>     // removing the geometry id from the corresponding family redundantly.
>     set<ShaderId> visited_families;
> ```

nit Given that this only user for lookup (not iteration), the type should be `unordered_set` for clarity.

(Actually since the collection has at most three elements, an inlined_vector with linear search would be faster, though possibly less clear.)
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1222 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfqfZVbC4y99f0AWF7h:-NfqfZVc0yaKqy4lOSbD:by931v9) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L1222)):*
> ```cpp
>         drake::internal::DiagnosticPolicy());
>     vector<RenderGlMesh> file_meshes;
>     for (const auto& mesh_data : meshes) {
> ```

nit This variable name is fairly generic.  Paired with `auto`, I think we're blurring a lot more than necessary.  Rule of thumb with `auto` is that the type name must either be on the rhs, or the variable name is the (snake spelling of the) type name.



_Suggestion:_
```cpp
render_mesh
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272)* status: 1 unresolved discussion

___
*[`geometry/render_gl/internal_render_engine_gl.h` line 420 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfqdSQfBS93mv6BcqDV:-NfqnvAnDfb3NVWimlvQ:bx3ciqx) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.h#L420)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Because I've been around this block before, I know that this comment is intended as a TODO, but I doubt that would be clear to a first-time reader.
</blockquote></details>

Marked as TODO.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 903 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-Nfqekmf9nPHuy3V07rf:-NfqpLdX1Cp4Goygt04M:b-yvnrvl) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L903)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Given that this only user for lookup (not iteration), the type should be `unordered_set` for clarity.

(Actually since the collection has at most three elements, an inlined_vector with linear search would be faster, though possibly less clear.)
</blockquote></details>

re: vector. I agree. However, removal of geometries is such a rare occurrence that can't happen within a simulation loop that I'm not worried about squeezing this to the tiniest runtime.

re: set vs unordered_set. While I'm fully on board with the argument that `set` is necessary for consistent iteration, I'm not on board with the argument that `unordered_set` is necessary in the absence of iteration. But I don't care enough to resist.
___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 1222 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-NfqfZVbC4y99f0AWF7h:-NfqoRGJD0jHTEbt8Lrs:bxjm4av) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L1222)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This variable name is fairly generic.  Paired with `auto`, I think we're blurring a lot more than necessary.  Rule of thumb with `auto` is that the type name must either be on the rhs, or the variable name is the (snake spelling of the) type name.
</blockquote></details>

Done -- for consistency I updated the names of all of the `RenderMesh` instances likewise.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 903 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-Nfqekmf9nPHuy3V07rf:-NfqsO8s0pBoGDA6DbBK:b-nte6hi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L903)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

re: vector. I agree. However, removal of geometries is such a rare occurrence that can't happen within a simulation loop that I'm not worried about squeezing this to the tiniest runtime.

re: set vs unordered_set. While I'm fully on board with the argument that `set` is necessary for consistent iteration, I'm not on board with the argument that `unordered_set` is necessary in the absence of iteration. But I don't care enough to resist.
</blockquote></details>

The principle is one of clarity (not performance) -- "have a reason to choose a particular container, and make sure the next reader knows the reason".  Using `set<>` would be fine if it had a comment explaining the thought process (e.g. `N.B. Using set<> here is not necessary, but we're doing it because ...`).  Using `set<>` without a comment forces me try to discern why the key order matters, eventually deciding that it doesn't.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20272)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 903 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20272#-Nfqekmf9nPHuy3V07rf:-Nfr9E-12BBdcmE_46_H:bov69nh) ([raw file](https://github.com/RobotLocomotion/drake/blob/c83e5c8140033ca764eb75ffe61edbc093c99b13/geometry/render_gl/internal_render_engine_gl.cc#L903)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The principle is one of clarity (not performance) -- "have a reason to choose a particular container, and make sure the next reader knows the reason".  Using `set<>` would be fine if it had a comment explaining the thought process (e.g. `N.B. Using set<> here is not necessary, but we're doing it because ...`).  Using `set<>` without a comment forces me try to discern why the key order matters, eventually deciding that it doesn't.
</blockquote></details>

I see where you're coming from. I find it interesting. When you see `set` vs `unordered_set` you're thinking "ordering". When I see that, I think "hash table overhead" and "cost of construction vs look ups".

My take away is that there is probably enough ambiguity in some of those types that it is worth noting something. Even for these local throw aways with small data sets.

**Pull request merged**
