### PR TITLE
[planner] Add a keep_going option to ConstraintRelaxingIk

### LINKED ISSUE #17189: Parametrizing `ConstraintRelaxingIk` to specify max num / add timeout logic
Context: 
- I'm using `ConstraintRelaxingIk` when planning online during robot operation in a context where speed is important. 
- The current implementation has [a few hardcoded parameters](https://github.com/RobotLocomotion/drake/blob/88fea982f7e7c10d1a809cf73c1c90a14719b8ba/manipulation/planner/constraint_relaxing_ik.cc#L58-L64) including `kMaxNumConstraintRelax`.
- IK calls which fail to find a solution take a much longer time to return vs. a successful IK call.

I'm looking into rewriting the class in a way that would:
- load the linked parameters above instead of hardcoding, and/or 
- allow a timeout value to be specified for the computation (regardless of whether or not the IK call succeeds)

Wondering if anyone has looked into this problem already, and/or has thoughts on the best way to structure the above.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17189.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17224)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri for feature review, please.

\CC @5yler @rpoyner-tri @siyuanfeng-tri FYI.

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17224#-:-N2OXIH83yImttwWJ6wH:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17224#-:-N2PaSbnClo5-atC7SPK:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),calderpg-tri (waiting on @jwnimmer-tri)

**Pull request merged**
