### PR TITLE
Build cop process.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2285) &emsp; Multiple assignees:&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/buildcop.rst, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2285#-KH2HP7A2qAJ3nZ0qyqp:-KH2HP7A2qAJ3nZ0qyqq:405497002) ([raw file](https://github.com/robotlocomotion/drake/blob/642b05019bb0353629f3bceb3c997cd4adb55271/drake/doc/buildcop.rst#L17)):*
I would keep the schedule itself out of the repo and put a link to a wiki page, or somewhere else that can be more easily updated since we are bound to have to make last minute changes at some point due to other work conflicts, illness, etc.

---

*[drake/doc/buildcop.rst, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2285#-KH2IP3ExSj5CVwyDblk:-KH2IP3ExSj5CVwyDbll:1466684903) ([raw file](https://github.com/robotlocomotion/drake/blob/642b05019bb0353629f3bceb3c997cd4adb55271/drake/doc/buildcop.rst#L30)):*
Will these render as `mailto:` links? I forget what Sphinx does here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2285)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/buildcop.rst, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2285#-KH2HP7A2qAJ3nZ0qyqp:-KH6lzvsGF1zzhRCk7fy:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/642b05019bb0353629f3bceb3c997cd4adb55271/drake/doc/buildcop.rst#L17)):*
Done.

---

*[drake/doc/buildcop.rst, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2285#-KH2IP3ExSj5CVwyDblk:-KH6WBW45k4QVOUFBXWD:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/642b05019bb0353629f3bceb3c997cd4adb55271/drake/doc/buildcop.rst#L30)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2285)*

**Comment by jamiesnape** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Build cop process\.
> 
> 
> 
> 
> </details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2285#-:-KHKx9kdGnmYWdhQoCD1:1417088721)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> +@jwnimmer-tri for platform review</details>


---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2285#-:-KHLIZVX0TGfghG58E0e:1417088721)*

**Comment by jwnimmer-tri** [comment]
The msvc-64 build is still running, but that doesn't matter for doc edits.  Using override-merge.

**Pull request merged**
