### PR TITLE
Use system nlopt for manylinux

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
_Edit: Towards #15757._

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15807)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for feature review.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15807#-:-MkIjIYt17jZNbc1XDY3:b-adicrb)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @mwoehlke-kitware)

___
*[tools/workspace/nlopt/repository.bzl, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15807#-MkIjDRbD8h5iQ4cEhOv:-MkIjDRbD8h5iQ4cEhOw:b-556jr9) ([raw file](https://github.com/robotlocomotion/drake/blob/9cecbd1399131d189ef09d1e6069159e6ac2cd46/tools/workspace/nlopt/repository.bzl#L26)):*
> ```Starlark
>         repository_ctx.symlink("/usr/include/nlopt.hpp", "include/nlopt.hpp")
>     elif os_result.is_manylinux:
>         # We expect that "manylinux" is based on Ubuntu 18.04
> ```

nit Missing period at end of sentence.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15807)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15807#-:-MkJ0NJT7zRqdES0Jpdd:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
