### PR TITLE
show_frame: Use workaround `updateFrame` pending upstream merge

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Upstream PR:
https://github.com/RobotLocomotion/director/pull/621

For issue, see Slack discussion:
https://drakedevelopers.slack.com/archives/C43KX47A9/p1554239704004700

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11134)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
SGTM. I think we should up the priority if another user runs into it, but I'm fine with this otherwise chilling pending upstream updates.

**Comment by EricCousineau-TRI** [comment]
(Or closing this for the time being, as long as it's easy to refer back to.)

**Comment by jwnimmer-tri** [comment]
Sure.  They would be in a good position to test it, in that case.

**Comment by EricCousineau-TRI** [comment]
Aye. Closing, and will post a tracer-comment in `#visualization` Slack channel.

**Pull request closed without merging**
