### PR TITLE
Add drake_cc_package_library for some more packages

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Builds on #8664. Relates #6464.

The goal here is to use `drake_cc_package_library` more widely, which will in the future ease maintenance of the install rules.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Comment by amcastro-tri** [comment]
Reviewed 3 of 16 files at r1.
Review status: 3 of 16 files reviewed at latest revision, all discussions resolved.

---

*[multibody/benchmarks/acrobot/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4GZao7mckPUf4sy4P:-LC4GZao7mckPUf4sy4Q:b-6vs2m6) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/acrobot/BUILD.bazel#L23)):*
> ```Python
>     name = "oracle",
>     srcs = ["acrobot.cc"],
>     hdrs = ["acrobot.h"],
> ```

I'd much ratter rename this to `acrobot_benchmark` (and probably the files as well).

---

*[tools/install/libdrake/build_components.bzl, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4IEyGC825Fc4Sw6RA:-LC4IEyGC825Fc4Sw6RB:b-2yt7in) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/install/libdrake/build_components.bzl#L5)):*
> ```Python
> # Should include everything any consumer of Drake would ever need.
> #
> # Do not update this list by hand; instead, run build_components_refresh.py.
> ```

for this PR, was this file auto-generated with `build_components_refresh.py` or did you edit it by hand?

---

*[tools/install/libdrake/build_components.bzl, line 164 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4Gy2zBxZYFG8OoCuf:-LC4Gy2zBxZYFG8OoCug:b2u1iys) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/install/libdrake/build_components.bzl#L164)):*
> ```Python
>     "//multibody/benchmarks/acrobot:acrobot",
>     "//multibody/benchmarks/acrobot:make_acrobot_plant",
>     "//multibody/benchmarks/acrobot:oracle",
> ```

Do we need to list these three `acrobot` libraries separately? I thought the point was just to list the package only? (i.e. `acrobot`).

---

*[tools/install/libdrake/build_components.bzl, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4HtGsC7WBvGTttlEm:-LC4HtGsC7WBvGTttlEn:b-olqe9d) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/install/libdrake/build_components.bzl#L172)):*
> ```Python
>     "//multibody/collision:collision",
>     "//multibody/collision:collision_api",
>     "//multibody/collision:model",
> ```

would we like to remove `model` and `collision_api` from here since `collision` is the package?

---

*[tools/skylark/drake_cc.bzl, line 358 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4F4cm9OTs-QJZsP-N:-LC4F4cn7NM_3D_2-jzk:b-vo68n0) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/skylark/drake_cc.bzl#L358)):*
> ```Python
>         visibility = ["//visibility:public"]):
>     """Creates a rule to declare a C++ "package" library -- a library whose
>     name matches the current Bazel package name (i.e., directory name) and
> ```

Does this bark at us if the package name does not match the directory name? should it?
Should `drake_cc_libary` bark at us if we provide a library name with the same name of the current directory?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/install/libdrake/build_components.bzl, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4IEyGC825Fc4Sw6RA:-LC4JFyi4uMgOGWQenNQ:b-1ig80e) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/install/libdrake/build_components.bzl#L5)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for this PR, was this file auto-generated with `build_components_refresh.py` or did you edit it by hand?
</blockquote></details>

I did it a while ago, I don't remember for sure at this point.

---

*[tools/install/libdrake/build_components.bzl, line 164 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4Gy2zBxZYFG8OoCuf:-LC4Ix994wakf62JyPYX:b-g4qhzk) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/install/libdrake/build_components.bzl#L164)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Do we need to list these three `acrobot` libraries separately? I thought the point was just to list the package only? (i.e. `acrobot`).
</blockquote></details>

That is future work.  First, I want to get all of the packages ported to the new scheme, then as a second pass I'll teach the regen tool how to omit things here.  You can preview that work at https://github.com/jwnimmer-tri/drake/commits/build-libdrake-all-stash.

---

*[tools/install/libdrake/build_components.bzl, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4HtGsC7WBvGTttlEm:-LC4J7Tq-G-lATBqLqWc:bjev98p) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/install/libdrake/build_components.bzl#L172)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

would we like to remove `model` and `collision_api` from here since `collision` is the package?
</blockquote></details>

Ditto.  Future work.

---

*[tools/skylark/drake_cc.bzl, line 358 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4F4cm9OTs-QJZsP-N:-LC4J9cB9WFgUIoDab3L:b-qfgnh7) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/tools/skylark/drake_cc.bzl#L358)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Does this bark at us if the package name does not match the directory name? should it?
Should `drake_cc_libary` bark at us if we provide a library name with the same name of the current directory?
</blockquote></details>

(1) Yes.

(2) Yes.

(3) Yes, though this is implemented in tools/lint/library_lint.bzl not drake_cc.bzl.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Comment by amcastro-tri** [comment]
Feature review complete, thanks for the patience. Just a few minor comments and :lgtm: 

---

Reviewed 13 of 16 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/benchmarks/inclined_plane/BUILD.bazel, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4NQo30EnWpyNfJPNG:-LC4NQo30EnWpyNfJPNH:bj2u8ee) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/inclined_plane/BUILD.bazel#L10)):*
> ```Python
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> package(default_visibility = ["//visibility:public"])
> ```

can packages be private? so, is this line needed or could it be private by default?

---

*[multibody/benchmarks/inclined_plane/BUILD.bazel, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4NIea1hmprMStP_gw:-LC4NIea1hmprMStP_gx:ba68zsf) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/inclined_plane/BUILD.bazel#L20)):*
> ```Python
> 
> drake_cc_library(
>     name = "everything",
> ```

I'd leave the original name here, i.e. `make_inclined_plane`

---

*[multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4NcbB5_df9YIqm_H5:-LC4NcbB5_df9YIqm_H6:b-i86aj) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel#L13)):*
> ```Python
> drake_cc_package_library(
>     name = "kuka_iiwa_robot",
>     visibility = ["//visibility:public"],
> ```

ditto, is this needed?

---

*[multibody/benchmarks/mass_damper_spring/BUILD.bazel, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4O5mD3Bks-DGUoYK0:-LC4O5mD3Bks-DGUoYK1:bd7r6v8) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/mass_damper_spring/BUILD.bazel#L20)):*
> ```Python
> 
> drake_cc_library(
>     name = "everything",
> ```

ditto library name change to "everything". Is that a term of art? 

---

*[multibody/benchmarks/pendulum/BUILD.bazel, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4Nulh2_5z-2DXEN-M:-LC4Nulh2_5z-2DXEN-N:b-t7vou2) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/pendulum/BUILD.bazel#L20)):*
> ```Python
> 
> drake_cc_library(
>     name = "everything",
> ```

I'd leave the `make_pendulum_plant` name as before

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC4OkTq1F9wqVuVHTDm:bz3mnm3)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 16 files reviewed at latest revision, 10 unresolved discussions.

---

*[multibody/benchmarks/acrobot/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4GZao7mckPUf4sy4P:-LC96k6d0qqVq9DtMAX_:b-ssydla) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/acrobot/BUILD.bazel#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd much ratter rename this to `acrobot_benchmark` (and probably the files as well).
</blockquote></details>

The files should definitely track the classname, so should not rename (unless you want me to rename the class also?).

I don't love ":acrobot_benckmark" library name because I feel it doesn't distinguish itself enough from "make_acrobot_plant" neighbor, which is a completely different beast, and the anyway directory is already called "benchmarks/acrobot" so "benchmarks/acrobot:acrobot_benchmark" doesn't really add anything new.

Any other ideas on the name?  ":equations" or ":analytical_solution" or something?

---

*[multibody/benchmarks/inclined_plane/BUILD.bazel, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4NQo30EnWpyNfJPNG:-LC4Stf32nRfQ6X21sJj:b-yaeq2t) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/inclined_plane/BUILD.bazel#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

can packages be private? so, is this line needed or could it be private by default?
</blockquote></details>

OK resolved f2f.  Drake tends to (for better or worse) make everything public by default, so we keep that pattern here.  (Also, this PR didn't add this line.)

---

*[multibody/benchmarks/inclined_plane/BUILD.bazel, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4NIea1hmprMStP_gw:-LC965p_-SQ-Vc6JROtA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/inclined_plane/BUILD.bazel#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd leave the original name here, i.e. `make_inclined_plane`
</blockquote></details>

Done.

---

*[multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4NcbB5_df9YIqm_H5:-LC969AK3KEByPc4y9XN:b-xmzt6s) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel#L13)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, is this needed?
</blockquote></details>

Yes.  Now, instead of make_kuka_iiwa_model being public, it is private and the make_iiwa_robot library wrapper for it is public.

---

*[multibody/benchmarks/mass_damper_spring/BUILD.bazel, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4O5mD3Bks-DGUoYK0:-LC96HDWDRPopPVMs2Hq:b-dtoom3) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/mass_damper_spring/BUILD.bazel#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto library name change to "everything". Is that a term of art? 
</blockquote></details>

Done.

Its just a question of taste.  With a library named "everything", you guys could keep adding small source files into the same cc_library and have less hoopla as you add small bits of new code.  If you name the cc_library after the filename, then you have to add a new cc_library for every new small utility.

I am fine either way though, so I've put back the original names.

---

*[multibody/benchmarks/pendulum/BUILD.bazel, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4Nulh2_5z-2DXEN-M:-LC96epKETaW5PB8qsu9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/pendulum/BUILD.bazel#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd leave the `make_pendulum_plant` name as before
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.  There is still one unsolved discussion from feature review, but should be okay otherwise.

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri I hadn't paid too much attention on this infrastructure change in previous PRs. One part I don't completely follow is the visibility. In some of these BUILD.bazel files, the package seems to be the only public part. In others, the libraries are public as well. Is the branch you referenced below the best source for seeing what the whole design is?

---

Reviewed 12 of 16 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9MW6w9KoV30Xv2UxN:b-ev16k4)*

**Comment by jwnimmer-tri** [comment]
The visibility changes are intended to be locally understandable, not part of some over-arching larger design.  Sometimes, the pre-existing visibility markings within the package make understanding the changes here more difficult, but hopefully not too bad.

I guess the only global design invariant I'm working on here is that there should not be two labels for the same thing, because we want our using-code to be consistent about how they spell things.  So for example we want ` "//multibody/benchmarks/inclined_plane"` not ` "//multibody/benchmarks/inclined_plane:make_inclined_plane_plant"` as what users say.

**Comment by SeanCurtis-TRI** [comment]
I guess I don't understand how this package library infrastructure lends "consistency". In the contrasting example, one is definitely more compact than the other, but how is that consistent? Or, generally, is the goal to minimize the number of library references in dependency lists? That it would be more consistent if dependencies were lists of packages?

Ultimately, this seems to limit the granularity of my declared dependencies (at least in those cases where the libraries visibility has been reduced).

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9OUgeCX-8E83H9Fng:b-ismjrg)*

**Comment by SeanCurtis-TRI** [comment]
Oh, and orthogonal to this discussion: :LGTM:

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9P8At4cX7UUFQFRNC:b-er9fnh)*

**Comment by jwnimmer-tri** [comment]
> I guess I don't understand how this package library infrastructure lends "consistency". In the contrasting example, one is definitely more compact than the other, but how is that consistent? Or, generally, is the goal to minimize the number of library references in dependency lists? That it would be more consistent if dependencies were lists of packages?

The overall motivation is #6464 so that we have https://github.com/jwnimmer-tri/drake/blob/build-libdrake-all-stash/tools/install/libdrake/build_components.bzl.new as our install list, instead of every individual component.

As part of that, we want to have drake_cc_package_library in every (non-example) package.  And in cases where developers want to, it means that they can use `//foo/mypackage` shorthand and pull in everything conveniently.  For most packages, the fine-grained components are also still available.

> Ultimately, this seems to limit the granularity of my declared dependencies (at least in those cases where the libraries visibility has been reduced).

Yes, and I think that's a good thing _for the benchmarks subfolders_.  We don't need to carve out 100-character long deps names for what are in essence simple test fixtures used in only a few places, since the benchmarks packages are already so fine-grained.  I would not advocate, and this PR does not propose, limiting visibility of the components within, say, the `//systems/framework` package.

Let me take another crack at the benchmarks folders again though, to see if there is any more clarification I can do there.

**Comment by SeanCurtis-TRI** [comment]
You don't need to take any further steps. That answer quite satisfies me.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9Ry3i1mDCqDDjO6Kz:b-1h4w59)*

**Comment by jwnimmer-tri** [comment]
I think the new revision should be clearer, and easier for others to co-maintain.  PTAL.

-(status: do not merge) 

---

Review status: 12 of 17 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9c1q87SCvc2r6l9io:b-h3fedk)*

**Comment by SeanCurtis-TRI** [comment]
I generally like this resolution. It is predicated on people understanding that `drake_cc_package_library` defaults to public visibility which overrides the "default visibility". Other than looking in `drake_cc.bzl`, what's the expectation for developers understanding that?

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9eGXrByaroaO2tYpD:bk1cx7i)*

**Comment by jwnimmer-tri** [comment]
For myself, I am content with RTFM as the answer.

**Comment by SeanCurtis-TRI** [comment]
sgtm

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733#-:-LC9ibcMCRPKOxkXeIfk:bb7ohn6)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/benchmarks/acrobot/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC4GZao7mckPUf4sy4P:-LC9ptU08MBSJTNZlY_h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ed7ba2ad50904552aa996f4ccfb59c5d736e5d/multibody/benchmarks/acrobot/BUILD.bazel#L23)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW yeah, maybe ":analytical_acrobot" or ":handwritten_acrobot" are good names.
</blockquote></details>

Done.

---

*[multibody/benchmarks/inclined_plane/BUILD.bazel, line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC9nWMt1O57M6WX5IPJ:-LC9pTkI0xaZeNx3p6Yw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2919e1c3b23a163712369efb039bc098af69107d/multibody/benchmarks/inclined_plane/BUILD.bazel#L10)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW typo, components
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Comment by amcastro-tri** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[tools/install/libdrake/build_components.bzl, line 164 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8733#-LC9s2048PR0YtwnH-YR:-LC9s2048PR0YtwnH-YS:b-4vlzpb) ([raw file](https://github.com/robotlocomotion/drake/blob/d69cc1e5996d514ac8122f5531bfd26fcc739aba/tools/install/libdrake/build_components.bzl#L164)):*
> ```Python
>     "//multibody/benchmarks/acrobot:acrobot",
>     "//multibody/benchmarks/acrobot:make_acrobot_plant",
>     "//multibody/benchmarks/acrobot:analytical_acrobot",
> ```

BTW alphabetize

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8733)*

**Pull request merged**
