### PR TITLE
[multibody] Minimum SAP solver infrastructure

### PR DESCRIPTION
**Pull request by amcastro-tri**
Bare bones SAP so that we can commit boilerplate separately for smaller reviews.
Refer to #16080 for more context.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165#-:-MpriP7R7EMrtLjUcpuy:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a bunch of nits.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165#-:-MpsCoUe31xWKN1wiEGn:b-al099n)* status: 13 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap_solver.h, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps6lf49ZjTL7sTq8hH:-Mps6lf49ZjTL7sTq8hI:b-wztwnz) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L3)):*
> ```objc
> #pragma once
> 
> #include <memory>
> ```

nit, unused includes.
___
*[multibody/contact_solvers/sap_solver.h, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps1mbe10n2RvqNJerY:-Mps1mbe10n2RvqNJerZ:b60vq78) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L6)):*
> ```objc
> #include <vector>
> 
> #include <Eigen/SparseCore>
> ```

nit, not needed.
___
*[multibody/contact_solvers/sap_solver.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps1IzqAF341T-hZUJ6:-Mps1IzqAF341T-hZUJ7:b4syau2) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L27)):*
> ```objc
> // time step. In addition, SAP uses regularization to model physical compliance
> // rather than to introduce constraint stabilization as previously done by
> // [Todorov, 2014]. Please refere to [Castro et al., 2021] for details.
> ```

nit, s/refere/refer
___
*[multibody/contact_solvers/sap_solver.h, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps2NleAKuyNtmz-alr:-Mps2NleAKuyNtmz-als:b9ptzjl) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L42)):*
> ```objc
> // TODO(amcastro-tri): enable AutoDiffXd support, if only for dense matrices so
> // that we can test the long term performant solution.
> // @tparam_nonsymbolic_scalar
> ```

nit, the TODO seems to be contradicting `@tparam_nonsymbolic_scalar`. Perhaps it's then more accurate to say this class is double only?
___
*[multibody/contact_solvers/sap_solver.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps2sZB5IfFMWU08UBM:-Mps2sZB5IfFMWU08UBN:b-g1yn5h) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L49)):*
> ```objc
> 
>   SapSolver() = default;
>   virtual ~SapSolver() = default;
> ```

nit,  virtual -> final?
___
*[multibody/contact_solvers/sap_solver.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps2ioC-dkUHig37H7M:-Mps2ioC-dkUHig37H7N:b-wmr0mb) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L53)):*
> ```objc
>   // Solve the contact problem specified by the input data. See
>   // ContactSolver::SolveWithGuess() for details. Currently, only `T = double`
>   // is supported. An exception is thrown if `T != double`.
> ```

FYI, I plan to do the same with deformable free motion solves.
___
*[multibody/contact_solvers/sap_solver.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3AxT04JRtt4XNCe-:-Mps3AxT04JRtt4XNCe0:bgrcfrl) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L66)):*
> ```objc
>   // mathematical quantities, we attempt follow the notation introduced in
>   // [Castro et al., 2021] as best as we can, though with ASCII and Unicode
>   // symbols.
> ```

BTW, are there exceptions (e.g. where ASCII and Unicode is not enough to represent the symbol)?
___
*[multibody/contact_solvers/sap_solver.h, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3PQ-3HySmFB3q_JX:-Mps3PQ-3HySmFB3q_JY:b-bdnnwp) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L83)):*
> ```objc
> 
>     T time_step;                  // Discrete time step used by the solver.
>     int nv;                       // Numver of generalized velocities.
> ```

nit, s/Numver/Number
___
*[multibody/contact_solvers/sap_solver.h, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3oJI9bShVpUecfK4:-Mps3oJI9bShVpUecfK5:bu4h9is) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L83)):*
> ```objc
> 
>     T time_step;                  // Discrete time step used by the solver.
>     int nv;                       // Numver of generalized velocities.
> ```

nit, default initialize built-in types. 
BTW, why isn't `time_step` also set in the constructor?
___
*[multibody/contact_solvers/sap_solver.h, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3YaL3g_J1dOT1BOo:-Mps3YaL3g_J1dOT1BOp:b-3vfr8y) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L85)):*
> ```objc
>     int nv;                       // Numver of generalized velocities.
>     int nc;                       // Numver of contacts.
>     BlockSparseMatrix<T> Jblock;  // Jacobian as block-sparse matrix.
> ```

BTW, are we ever going to need Jacobian in another format? Perhaps just `J` or `jacobian`?
___
*[multibody/contact_solvers/sap_solver.h, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps4NqK72appygXohmU:-Mps4NqK72appygXohmV:bw56wv3) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L90)):*
> ```objc
>   // Pack solution into ContactSolverResults.
>   static void PackContactResults(const PreProcessedData& data,
>                                  const VectorX<T>& v, const VectorX<T>& vc,
> ```

nit, it may be worthwhile to document what `vc` and `gamma` are locally here (so that reader doesn't have to go all the way to the paper to know what these are).
___
*[multibody/contact_solvers/sap_solver.cc, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps6cQT-rbQlqnetKU6:-Mps6cQT-rbQlqnetKU7:b-wztwnz) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.cc#L3)):*
> ```cpp
> #include "drake/multibody/contact_solvers/sap_solver.h"
> 
> #include <algorithm>
> ```

nit, unused includes.
___
*[multibody/contact_solvers/sap_solver.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps4uP_3yY7NN05Cfzj:-Mps4uP_3yY7NN05Cfzk:bvty1kl) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.cc#L18)):*
> ```cpp
> namespace internal {
> 
> using Eigen::Matrix3d;
> ```

nit, unused `using`s.
___
*[multibody/contact_solvers/sap_solver.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps51Uv63tvKa04uUwP:-Mps51Uv63tvKa04uUwQ:bjst6tk) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.cc#L41)):*
> ```cpp
>                                       const VectorX<T>& gamma,
>                                       ContactSolverResults<T>* results) {
>   results->Resize(data.nv, data.nc);
> ```

nit, check non-null first?
___
*[multibody/contact_solvers/sap_solver.cc, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps5ZTj3C4YZEV3NCBO:-Mps5ZTj3C4YZEV3NCBP:bg175yv) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.cc#L51)):*
> ```cpp
>   results->fn /= data.time_step;
>   results->ft /= data.time_step;
>   const auto& Jop = data.Jblock;
> ```

nit, the naming here is counter-intuitive. `Jblock` is not an operator yet we named it `Jop`.
___
*[multibody/contact_solvers/sap_solver.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps6LouEBz5XrtEfIiG:-Mps6LouEBz5XrtEfIiH:b-8pw9xk) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.cc#L53)):*
> ```cpp
>   const auto& Jop = data.Jblock;
>   Jop.MultiplyByTranspose(gamma, &results->tau_contact);
>   results->tau_contact /= data.time_step;
> ```

BTW, we used `tau` to denote non-contact forces in the paper. This could potentially be a source of confusion for some readers.
___
*[multibody/contact_solvers/test/sap_solver_test.cc, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps6uPb6IgGiVdZd6C7:-Mps6uPb6IgGiVdZd6C8:b-asgc64) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/test/sap_solver_test.cc#L3)):*
> ```cpp
> #include "drake/multibody/contact_solvers/sap_solver.h"
> 
> #include <memory>
> ```

nit unused include.
___
*[multibody/contact_solvers/test/sap_solver_test.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps7A-k2fidsSdGp0Ws:-Mps7A-l1l-VVX2tipTw:b-vzf1rz) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/test/sap_solver_test.cc#L21)):*
> ```cpp
> class SapSolverTester {
>  public:
>   typedef SapSolver<double>::PreProcessedData PreProcessedData;
> ```

GSG: "In new code, using is preferable to typedef, because it provides a more consistent syntax with the rest of C++ and works with templates."
___
*[multibody/contact_solvers/test/sap_solver_test.cc, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps7osOAsxtKiQ4GlLk:-Mps7osOAsxtKiQ4GlLl:b-f3wuce) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/test/sap_solver_test.cc#L59)):*
> ```cpp
>   EXPECT_EQ(results_vc, vc);
>   const VectorXd tauc_expected = Jdense.transpose() * gamma / data.time_step;
>   EXPECT_EQ(results.tau_contact, tauc_expected);
> ```

BTW, should we worry about round-off errors here (e.g. on mac)?

**Review by amcastro-tri — COMMENTED** [review]
Thanks @xuchenhan-tri. 
+@sherm1 for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165#-:-MpsIRY3DLTrowdDK9b8:b-bdkdmd)* status: 13 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @amcastro-tri and @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
Thanks for the prompt review @xuchenhan-tri. I addressed you comments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165#-:-MpsNP8g0EXgTvCZLXh7:b-gj9prd)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @amcastro-tri and @sherm1)

___
*[multibody/contact_solvers/sap_solver.h, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps2NleAKuyNtmz-alr:-MpsJwCH05D7hp0jS6fP:b-3apwqi) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L42)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the TODO seems to be contradicting `@tparam_nonsymbolic_scalar`. Perhaps it's then more accurate to say this class is double only?
</blockquote></details>

I like that. 
___
*[multibody/contact_solvers/sap_solver.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps2ioC-dkUHig37H7M:-MpsK78m7RyRS34AVh-g:b-d9lht0) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, I plan to do the same with deformable free motion solves.
</blockquote></details>

I think that's good for now. We'll figure out a better architecture as we provide more support for automatic differentiation.
___
*[multibody/contact_solvers/sap_solver.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3AxT04JRtt4XNCe-:-MpsKJTy1l8H-uVkVW34:bahfmlw) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L66)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, are there exceptions (e.g. where ASCII and Unicode is not enough to represent the symbol)?
</blockquote></details>

Lots of them I imagine. All I can do is to match as much as possible to the notation in the paper using ASCII and Unicode. Hopefully the accompanying docs are enough to disambiguate.
___
*[multibody/contact_solvers/sap_solver.h, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3oJI9bShVpUecfK4:-MpsL6yU5VZejEalDYUe:bp1y8u8) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L83)):*
> why isn't time_step also set in the constructor?

Why would that be better?
___
*[multibody/contact_solvers/sap_solver.cc, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps6LouEBz5XrtEfIiG:-MpsMJ3z4CTGIrM0Du4m:b3icpca) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.cc#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, we used `tau` to denote non-contact forces in the paper. This could potentially be a source of confusion for some readers.
</blockquote></details>

even though it has a big trailing `_contact`? Worst case scenario, the documentation in ContactSolverResults::tau_contact should suffice.
Also, this code is only meant for those fully familiar with the paper. If not, they should go read the paper first. So personally I am not worried with symbols for as long you, I and anyone else who read the paper is satisfied with the symbols we came up with (in Latex and in ASCII).
___
*[multibody/contact_solvers/test/sap_solver_test.cc, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps7osOAsxtKiQ4GlLk:-MpsN6isB2GIvo6noW33:b-kilf5l) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/test/sap_solver_test.cc#L59)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, should we worry about round-off errors here (e.g. on mac)?
</blockquote></details>

Blocking. I'll make sure mas CI passes before merging.
This is how I personally go about these; if the computation is exactly the same, bitwise, then I expect an exact comparison. Though yeah, mac is known for tripping weird errors.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @amcastro-tri and @sherm1)

___
*[multibody/contact_solvers/sap_solver.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3AxT04JRtt4XNCe-:-MpsQTQX2ohodFz8eHRx:bareqsx) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L66)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Lots of them I imagine. All I can do is to match as much as possible to the notation in the paper using ASCII and Unicode. Hopefully the accompanying docs are enough to disambiguate.
</blockquote></details>

One alternative is to provide a comment with latex notation at where the symbol is defined when ASCII and Unicode is lacking so we have complete correspondence between code and paper.
___
*[multibody/contact_solvers/sap_solver.h, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3oJI9bShVpUecfK4:-MpsRVeQ7tEUQu3Jp0gq:b-vg4fmt) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L83)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> why isn't time_step also set in the constructor?

Why would that be better?
</blockquote></details>

Not saying one is better than the other now that you default initialized. Just curious. Seems natural to me.

**Review by sherm1 — COMMENTED** [review]
Nice to see these small "lemma" PRs before the big one!
Platform :lgtm: with a few minor comments.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165#-:-MpskEShEnepHgHms8kL:b-8vi8of)* status: 5 unresolved discussions, missing label for release notes (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap_solver.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3AxT04JRtt4XNCe-:-MpsgYDk-oGOEPVbYzgh:bkpqg8r) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L66)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

One alternative is to provide a comment with latex notation at where the symbol is defined when ASCII and Unicode is lacking so we have complete correspondence between code and paper.
</blockquote></details>

Full LaTeX notation is hard to read in the header files -- best to avoid if possible unless it is very simple.
___
*[multibody/contact_solvers/sap_solver.h, line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16165#-MpsfsO-9FHkTjJKBBQw:-MpsfsO-9FHkTjJKBBQx:bl01daq) ([raw file](https://github.com/robotlocomotion/drake/blob/59056874f4bb97f93a9b664dd6be3a07a8357884/multibody/contact_solvers/sap_solver.h#L31)):*
> ```objc
> // - [Todorov, 2014] Todorov, E., 2014, May. Convex and analytically-invertible
> //   dynamics with contacts and constraints: Theory and implementation in
> //   mujoco. In 2014 IEEE International Conference on Robotics and Automation
> ```

nit: MuJoCo is the proper spelling
___
*[multibody/contact_solvers/sap_solver.h, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16165#-MpsgN5W9zG4gY9tPnbh:-MpsgN5W9zG4gY9tPnbi:b-ow445g) ([raw file](https://github.com/robotlocomotion/drake/blob/59056874f4bb97f93a9b664dd6be3a07a8357884/multibody/contact_solvers/sap_solver.h#L58)):*
> ```objc
> 
>   // Structure used to store input data pre-processed for computation. For
>   // mathematical quantities, we attempt follow the notation introduced in
> ```

nit: follow -> to follow
___
*[multibody/contact_solvers/sap_solver.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mpsh0-5AM0jDZZg48DJ:-Mpsh0-5AM0jDZZg48DK:b-ehawzi) ([raw file](https://github.com/robotlocomotion/drake/blob/59056874f4bb97f93a9b664dd6be3a07a8357884/multibody/contact_solvers/sap_solver.h#L70)):*
> ```objc
> 
>     // @param nv Number of generalized velocities.
>     // @param nc Number of contact constraints.
> ```

BTW the @param names here don't match the actual parameter names. I realize this isn't real doxygen which is why I made this a BTW. But it seems ... odd.
___
*[multibody/contact_solvers/sap_solver.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mpshj_36cERpcmwknsx:-Mpshj_36cERpcmwknsy:b-c86ux7) ([raw file](https://github.com/robotlocomotion/drake/blob/59056874f4bb97f93a9b664dd6be3a07a8357884/multibody/contact_solvers/sap_solver.cc#L18)):*
> ```cpp
>                                                  const VectorX<T>&,
>                                                  ContactSolverResults<T>*) {
>   throw std::runtime_error("This method must be implemented.");
> ```

BTW 
- can you use the ThrowIfNotImplemented() helper that you used elsewhere?
- this is a logic_error, not a runtime_error (that is, some programmer screwed up)
___
*[multibody/contact_solvers/test/sap_solver_test.cc, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps7osOAsxtKiQ4GlLk:-MpsjH-h5CbFJCLuXhb0:b717001) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/test/sap_solver_test.cc#L59)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Blocking. I'll make sure mas CI passes before merging.
This is how I personally go about these; if the computation is exactly the same, bitwise, then I expect an exact comparison. Though yeah, mac is known for tripping weird errors.
</blockquote></details>

BTW I would do this comparison to a tolerance (the others are just rearrangements so should be exact). Even though the source code looks like the same calculation, there is no requirement that an optimizer generate the exact same instruction sequence in both locations. For example, there might be more unused registers available in a smaller function than are available here in this long test code. And even if today's compiler happens to generate the same sequence a later upgrade might change that. So we really don't expect bitwise equality here -- IMO the test should reflect what we expect, that is, match to a very tight tolerance like 1e-15 but not 0.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16165)* status: missing label for release notes (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/contact_solvers/sap_solver.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3AxT04JRtt4XNCe-:-MpvVAx772_KPMsl0uDX:b-310d3t) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L66)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Full LaTeX notation is hard to read in the header files -- best to avoid if possible unless it is very simple.
</blockquote></details>

I think we can treat these on a case by case basis. If when we introduce a new symbol during review it happens to create a lot of a headache, we can consider whether documentation plus/or Latex symbols is what we need.
___
*[multibody/contact_solvers/sap_solver.h, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps3oJI9bShVpUecfK4:-MpvVeSL9-ytTAOjnzP_:b-rlfbrw) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/sap_solver.h#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Not saying one is better than the other now that you default initialized. Just curious. Seems natural to me.
</blockquote></details>

ok, I added initialization at construction.
___
*[multibody/contact_solvers/sap_solver.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mpshj_36cERpcmwknsx:-MpvWgN2C3WxLyRuFEfb:bywrjth) ([raw file](https://github.com/robotlocomotion/drake/blob/59056874f4bb97f93a9b664dd6be3a07a8357884/multibody/contact_solvers/sap_solver.cc#L18)):*
> can you use the ThrowIfNotImplemented() helper 

no, that's a helper in the `LinearOperator` class.
___
*[multibody/contact_solvers/test/sap_solver_test.cc, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16165#-Mps7osOAsxtKiQ4GlLk:-MpvXiC_0D-yTiNi1-h6:b-3ggo2t) ([raw file](https://github.com/robotlocomotion/drake/blob/6e9d11ff5599454cb11b2bfd5e605c7949c99c77/multibody/contact_solvers/test/sap_solver_test.cc#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I would do this comparison to a tolerance (the others are just rearrangements so should be exact). Even though the source code looks like the same calculation, there is no requirement that an optimizer generate the exact same instruction sequence in both locations. For example, there might be more unused registers available in a smaller function than are available here in this long test code. And even if today's compiler happens to generate the same sequence a later upgrade might change that. So we really don't expect bitwise equality here -- IMO the test should reflect what we expect, that is, match to a very tight tolerance like 1e-15 but not 0.
</blockquote></details>

I see, that makes sense. Thanks for the explanation.

**Pull request merged**
