### PR TITLE
Use Python 3 by default on supported platforms

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #10606

Requires:
- [x] #11731
- [x] CI prep

This is leveraging the existing hacks for branching between Python 2 + 3. Also did a real dumb hack job on the CMake bits; please lemme know if there's a better way.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11733)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
It's up to you. It's probably only 2-3 hours of work. No technical reason why we could not switch today or tomorrow, for instance.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Can you resolve the conflicts?

**Comment by EricCousineau-TRI** [comment]
Done.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-debug please

**Comment by EricCousineau-TRI** [comment]
Hm... Yeah, I think I force-pushed from a different computer... Oops!

**Pull request merged**
