### PR TITLE
Add ability to install Drake built with Bazel

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify `package_drake.sh` script to be able to both generate a tarball or install to a specified prefix. This is also a rewrite and general tidying of the script to hopefully make it more robust and easier to read.

Supersedes #5797.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5941)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@ericcousineau-tri for review

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-Kiahlj2ay2kjosXejYY:b7dr7wo)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/package_drake.sh, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiakSdaQPuQBm4RPfUU:-KiakSdbS8I-SAw5RT0j:b-kn1awk) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L7)):*
> ```Shell
> 
> # If any command in the script exits non-zero, stop.
> set -e
> ```

BTW Would it be possible to add `-u` as well, to error on undefined variables?

---

*[tools/package_drake.sh, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiam0YLZwSn8C88BBut:-Kiam0YLZwSn8C88BBuu:b-myx1ql) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L13)):*
> ```Shell
> function canonicalize
> {
>   perl -MCwd -le 'print Cwd::abs_path(shift)' "$1"
> ```

Would it possible to use the simpler idiom, `$(cd "$1" && pwd)`? If there is a reason that we must use `perl` (e.g., if the directory does not exist), could that be mentioned in a comment?

---

*[tools/package_drake.sh, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiamK_9yYGI9hpkc_Wj:-KiamK_AD1jegyQKuix7:b-bdvldg) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L20)):*
> ```Shell
> function copy_source_artifacts
> {
>   cp tools/drake-config.cmake "$1/lib/cmake/drake/"
> ```

Can we place these variables at the top for quick context and modification (for packaging Python bindings in the future), and possibly if Bazel users outside of Drake wish to use this?
```
PACKAGE=drake
TARGETS="
    //drake:libdrake_so
    //drake:libdrake_headers
    //drake:external_headers
    "
ARTIFACTS_LIB=libdrake.so
```
or something like that...

---

*[tools/package_drake.sh, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiakx_qT-aE4Jmlnurg:-Kiakx_qT-aE4Jmlnurh:b-6rtmxb) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L34)):*
> ```Shell
> # Extract headers to specified install prefix.
> function extract_headers
> (
> ```

BTW Not sure if it's style-specific, but would it be possible to still use curly brackets? e.g.
```
function my_function
{ (
...
) }
```
to keep the syntax consistent, and draw more attention to the fact that this is a sub-shell.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by EricCousineau-TRI** [comment]
*[tools/package_drake.sh, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiam0YLZwSn8C88BBut:-KicN5mPpJeJ5AZqgKOe:b864l52) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L13)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it possible to use the simpler idiom, `$(cd "$1" && pwd)`? If there is a reason that we must use `perl` (e.g., if the directory does not exist), could that be mentioned in a comment?
</blockquote></details>

Additionally, is there a way to have this canonicalize on the initial `$PWD` (maybe via an optional `${2-$PWD}` or something, such that you could do `canonicalize $install_dir $start_dir`)?
I had tried out the script, specifying `-d build/install`, and it installed the directory relative to `drake` rather than my current directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/package_drake.sh, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiakSdaQPuQBm4RPfUU:-KieL3PxLB5BxIrtm5uH:b-3q11v6) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L7)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Would it be possible to add `-u` as well, to error on undefined variables?
</blockquote></details>

Aaaaaack... sure, except then I have to fix the places I was intentionally dereferencing a (potentially) unset variable :stuck_out_tongue_winking_eye:. (Wasn't there in the original script, but since you mention it, it seems like a sensible addition.)

---

*[tools/package_drake.sh, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiam0YLZwSn8C88BBut:-KieLQ9jUZRrCUImYcKm:b-zeehd1) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L13)):*
> Would it possible to use the simpler idiom?

This approach is robust against symlinks. Particularly, this allows the script to still work if invoked through a symlink. Using `perl` is the most portable way to do that (at least, without a *lot* of additional shell code). I'll add a comment.

> Is there a way to have this canonicalize on the initial `$PWD`? I had tried out the script, specifying `-d build/install`, and it installed the directory relative to drake rather than my current directory.

Ack, yes, that's a bug. The inputs should be canonicalized before the script changes its working directory. (I was waiting because `canonicalize` fails if the part of the directory doesn't exist, so it needs to be `mkdir`d first. I'll just move all that logic up...

---

*[tools/package_drake.sh, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiamK_9yYGI9hpkc_Wj:-KieOOd8ocfs5nkkT2tL:b-9n882e) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can we place these variables at the top for quick context and modification (for packaging Python bindings in the future), and possibly if Bazel users outside of Drake wish to use this?
```
PACKAGE=drake
TARGETS="
    //drake:libdrake_so
    //drake:libdrake_headers
    //drake:external_headers
    "
ARTIFACTS_LIB=libdrake.so
```
or something like that...
</blockquote></details>

I'd sort of rather not. This entire approach, honestly, is a monstrous hack to try to work around the fact that Bazel cannot perform one of the most basic build tool functions. I'd prefer to not go out of the way to make this any less ugly as an incentive to fix Bazel. (And I ***ABSOLUTELY*** do not want to encourage proliferation of this script.)

Also, it's not just Python bindings, it's also LCM, libbot, robotlocomotion_lcmtypes, and possibly others. Trying to maintain a list of install artifacts separate from the build system is a terrible design that's just begging to be constantly drifting out of sync. This ***belongs*** in the build system.

---

*[tools/package_drake.sh, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiakx_qT-aE4Jmlnurg:-KieOjMKEmk6zwNxRw4S:b-uyg9b5) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L34)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Not sure if it's style-specific, but would it be possible to still use curly brackets? e.g.
```
function my_function
{ (
...
) }
```
to keep the syntax consistent, and draw more attention to the fact that this is a sub-shell.
</blockquote></details>

Sure; I was considering doing that anyway...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by EricCousineau-TRI** [comment]
:LGTM:
Thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/package_drake.sh, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiamK_9yYGI9hpkc_Wj:-KieiuJwL5JpmsX2Ccyq:b-1hppy8) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'd sort of rather not. This entire approach, honestly, is a monstrous hack to try to work around the fact that Bazel cannot perform one of the most basic build tool functions. I'd prefer to not go out of the way to make this any less ugly as an incentive to fix Bazel. (And I ***ABSOLUTELY*** do not want to encourage proliferation of this script.)

Also, it's not just Python bindings, it's also LCM, libbot, robotlocomotion_lcmtypes, and possibly others. Trying to maintain a list of install artifacts separate from the build system is a terrible design that's just begging to be constantly drifting out of sync. This ***belongs*** in the build system.
</blockquote></details>

BTW, I agree that it's a hack, and I do see your point, but my concern is that install-ability won't be addressed by Bazel any time in the near future, so I think it would benefit others who would have to end up doing effectively the same hack. However, if some poor soul does have to do so and they find this, they at least have some starting point.

And gotcha, was not thinking about that per the list synchronization. Good point!

---

*[tools/package_drake.sh, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiav6nPQZ0Qcekds4fe:-Kiav6nROnBBxhabfBUK:b-tquwsl) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L57)):*
> ```Shell
> (
>   cd "$1/include/external"
>   tar -xzf "$workspace/bazel-bin/drake/external_licenses.tar.gz"
> ```

BTW I'll create another issue to see if we can modify Bazel to create a directory tree directly, rather than needing to take the route of untar -> merge -> tar. My guess is that generating a debug version of drake may create rather large artifacts, and some (possibly minimal) time will be spent compressing / decompressing it.

---

*[tools/package_drake.sh, line 170 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiekMf4tby_F6b46yNr:-KiekMf5-0jmHzueEykZ:b-amgxty) ([raw file](https://github.com/robotlocomotion/drake/blob/be913cdd6cb2ef2c77f6994bb4590bac3fb8b683/tools/package_drake.sh#L170)):*
> ```Shell
> 
> # Find the bazel workspace root and set as working directory.
> cd "$(dirname "$(canonicalize "$0")")"
> ```

BTW Not critical, but might it be possible to resolve this in the above hunk, and add an comment about using `canonicalize` now that the directory has changed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-KiekAH6AcI6N-iX0AWe:b-5fqkv5)*

**Comment by ggould-tri** [comment]
+@ggould-tri as on-call platform reviewer.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-Kif7BYIRMGvYEaBOdIT:b2x0ndg)*

**Comment by ggould-tri** [comment]
:lgtm:; one typo noted below.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/package_drake.sh, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KifF06pKKQO_LXKT--L:-KifF06qe1tJbA9sLN0I:b2h0fs5) ([raw file](https://github.com/robotlocomotion/drake/blob/be913cdd6cb2ef2c77f6994bb4590bac3fb8b683/tools/package_drake.sh#L9)):*
> ```Shell
> set -e
> 
> # If any unset variable is references, stop.
> ```

FYI typo "references"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-KifGCqH32saI9uDAyra:bcj45ef)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by jwnimmer-tri** [comment]
For installation / distribution changes (also for third-party library changes, though those aren't in this PR), remember to test on OSX also, whether in CI or locally.

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by soonho-tri** [comment]
+@soonho-tri : I'll test it on macs, sometime this evening or tomorrow morning.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-Kikn9dxXFCF4-2f6-hC:b-wqquld)*

**Comment by mwoehlke-kitware** [comment]
I was able to test (briefly; it didn't explode, and the tar and install tree seem to have reasonable-looking files) on our local macbook, thanks to @soonho-tri's help resolving my Bazel problems. However, it wouldn't hurt to have a few more eyes.

p.s. I'm about to be gone until Monday, if someone else wants to merge before then...

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/package_drake.sh, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-Kiav6nPQZ0Qcekds4fe:-KikoPxm6p-WTQcz7z44:bqaak6w) ([raw file](https://github.com/robotlocomotion/drake/blob/e2e1b49b91bd66382e10edc975669a78914e6e23/tools/package_drake.sh#L57)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I'll create another issue to see if we can modify Bazel to create a directory tree directly, rather than needing to take the route of untar -> merge -> tar. My guess is that generating a debug version of drake may create rather large artifacts, and some (possibly minimal) time will be spent compressing / decompressing it.
</blockquote></details>

BTW FWIW, I'd rather we worked on getting Bazel to install things more directly...

---

*[tools/package_drake.sh, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KifF06pKKQO_LXKT--L:-KikoNFYyV0vhVpRC_Ck:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/be913cdd6cb2ef2c77f6994bb4590bac3fb8b683/tools/package_drake.sh#L9)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "references"
</blockquote></details>

Fixed.

---

*[tools/package_drake.sh, line 170 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiekMf4tby_F6b46yNr:-Kikobo-kHVKT0kU2R9d:bp03bmh) ([raw file](https://github.com/robotlocomotion/drake/blob/be913cdd6cb2ef2c77f6994bb4590bac3fb8b683/tools/package_drake.sh#L170)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Not critical, but might it be possible to resolve this in the above hunk, and add an comment about using `canonicalize` now that the directory has changed?
</blockquote></details>

BTW Not sure I follow?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-Kiko06icX0BPUFMAG9k:bmyarx7)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/package_drake.sh, line 170 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiekMf4tby_F6b46yNr:-KilCpkdL7I8p-R7Lorw:b-mz1q41) ([raw file](https://github.com/robotlocomotion/drake/blob/be913cdd6cb2ef2c77f6994bb4590bac3fb8b683/tools/package_drake.sh#L170)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW Not sure I follow?
</blockquote></details>

Sorry, meant to ask if you could resolve the value of `canonicalize "$0"` as a variable, say `cur_dir`, in the above section, `# Resolve output paths...`.
Then, in the following line, make a quick note that `canonicalize` will be using the new `pwd`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by soonho-tri** [comment]
It worked on my mac as well.
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-:-KiopAFlPoz1TkMUxetV:b-ga6ps)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/package_drake.sh, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiqG4YuO9mT_oqpRwPb:-KiqG4YuO9mT_oqpRwPc:b-c82f66) ([raw file](https://github.com/robotlocomotion/drake/blob/a97e37454abd95c9a621167507d4382598cf4dd5/tools/package_drake.sh#L19)):*
> ```Shell
>   # most portable way to do this, since `readlink -f` is a GNU extension that
>   # isn't available on BSD derived platforms (e.g. MacOS).
>   perl -MCwd -le 'print Cwd::abs_path(shift)' "$1"
> ```

`readlink -f` works on my Mac (installed to `/usr/bin/readlink`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/package_drake.sh, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiqG4YuO9mT_oqpRwPb:-KiqGaF2Ren6NfgrBg-3:bq16h59) ([raw file](https://github.com/robotlocomotion/drake/blob/a97e37454abd95c9a621167507d4382598cf4dd5/tools/package_drake.sh#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`readlink -f` works on my Mac (installed to `/usr/bin/readlink`)
</blockquote></details>

Ignore that, you meant `readlink -f`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/package_drake.sh, line 170 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5941#-KiekMf4tby_F6b46yNr:-Kj8yQFS0wnH0sAemMnu:b-n35kmy) ([raw file](https://github.com/robotlocomotion/drake/blob/be913cdd6cb2ef2c77f6994bb4590bac3fb8b683/tools/package_drake.sh#L170)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Sorry, meant to ask if you could resolve the value of `canonicalize "$0"` as a variable, say `cur_dir`, in the above section, `# Resolve output paths...`.
Then, in the following line, make a quick note that `canonicalize` will be using the new `pwd`.


</blockquote></details>

OK. (Shoulda put BTW to prevent this from holding the review the process - sorry about that!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5941)*

**Pull request merged**
