### PR TITLE
Simple planar two degree-of-freedom test for CalcBiasAcceleration().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13406)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/plant/test/multibody_plant_jacobians_test.cc, line 341 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13406#-M9L1_273who5zqVCk0d:-M9OIeHQDbPxLyjTsRSS:bhestug) ([raw file](https://github.com/robotlocomotion/drake/blob/23b9095a47251a7696e6d1ff3e809a3f443df054/multibody/plant/test/multibody_plant_jacobians_test.cc#L341)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

Got you!
</blockquote></details>

Howdy @mitiguy!
I'm totes fine with being ignored on a nit, but I do like to hear why I'm ignored when possible.

Can you explain here?

My issue is that the current text just describes arbitrary frames more or less; can you describe the purpose of selecting these frames? (center-of-gravity, geometry center, generally arbitrary ...?)

**Comment by mitiguy** [comment]
Hi @ericcousineau-tri 

Thank you for letting me know that I had missed responding.  
I did not mean to ignore you and will update this part of this test with better documentation in my next upcoming PR (I'll @ you).

Some terminology that Sherm likes and Alejandro and I use.
A "Mobilizer" (which for this problem maps to a "joint") has two frames.
One is inboard which frequently is called the "F" frame (fixed to the inboard body).
One is outboard which frequently is called the "M" frame (fixed to the outboard body).
In addition to better defining  frames "F" and "M" in this example, I'll provide a better definition of all the frames.  I prefer to be explicit and I appreciate that you like it too.

**Comment by sherm1** [comment]
BTW the F and M frames are documented in the doxygen for [Joint](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_joint.html). Would be better with a picture like the one from Simbody [here](https://simbody.github.io/simbody-3.6-doxygen/api/classSimTK_1_1MobilizedBody.html#details).

**Comment by EricCousineau-TRI** [comment]
Thanks! However, my issue is not with consistency of frame names (name 'em whatever, as long as it's documented). And I'm aware of mobilizer and those frame conventions, we've used a slightly different version in the [SDFormat docs](http://sdformat.org/tutorials?tut=spec_model_kinematics&cat=specification&#joint) - though admittedly less succinct ;)

In this case, though, I still don't know *why* I care about *the physical location* of frames `F` and `M` in *this specific context*, for the specific model. It was called out in documentation, but I don't understand *why*.

Really, I just wanna know why the poses were chosen.

Were the poses of F and M chosen to be geometric center?
Were they chosen to be the center of mass?
Were they chosen arbitrarily, 'cause it's easy to define a double-pendulum that way?
Were those frames, F and M, already described *specific to this model* somewhere else?
... ?

**Comment by huihuaTRI** [comment]
I trying to understand Eric's point. After a second look at the code, it seems to me that the frames `X_AW_`, `X_AF_` and `X_BM_` are irrelevant to the test. What I mean is that they are not required when creating the joints. When computing the bias spatial acceleration, the body frames are used anyway. Is this correct?

**Comment by EricCousineau-TRI** [comment]
Ohh, going off of @huihuaTRI's comment, reading the code, it looks like those three rigid transforms are used *only* for creating the joint, not anywhere else.

So maybe my suggested fix is: Move that to just the `AddJoint` calls, possibly in the form of `RigidTransform`, and delete all of the comments regarding them? (b/c they're obvious from the code, and people should learn about monogram and rotations themselves?)

**Comment by mitiguy** [comment]
Yes - I agree.  It would have been ideal if I had done a better job updating that old test.  I'll ensure improvements are made and you get visibility on the update -- I look forward to more of your feedback.  Also, I talked to Sherm and as he mentioned above it would be helpful to have a picture of the "F" and "M" frame somewhere in Drake (as was done for Simbody).  Those frame names are used in many parts of the multibody code without much comment.

**Comment by EricCousineau-TRI** [comment]
Gotcha; something like this? (@amcastro-tri's pic, which we cribbed for SDFormat docs)
> image

**Pull request merged**
