### PR TITLE
simulator_test: Move LimitMalloc test; skip separate test on --config=asan

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Workaround due to #14901

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14902)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for both reviews, please!
\cc @soonho-tri
+(status: single reviewer ok) +(priority: emergency)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14902#-:-MYFWSOx5jGe3rJx7HCz:b4x4kaj)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Review by soonho-tri — COMMENTED** [review]
FYI, I was able to run `CC=clang-9 CXX=clang++-9 btd //systems/analysis/... --config=asan` on my puget.

+@soonho-tri 

:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14902#-:-MYFWrMS4Qtg_WJiVi03:b-73rl57)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14902)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14902#-MYFvEzrE_RaC-JsvU_m:-MYFvEzrE_RaC-JsvU_n:b7dtdeo) (no related file):*
This will certainly stop the bleeding. Looks like some mitigations I did before are not broad enough:

https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/limit_malloc.h#L23-L26

https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/limit_malloc.h#L23-L26

---

**Comment by jwnimmer-tri** [comment]
CI fires aside, I wholly support putting the heap tests into a separate program.  The `simulator_test` is already very large, and the nature of these tests is fairly distinct from the existing functional tests; I imagine it would be very common for a developer to want to run only the functional tests, or only the heap tests, independently.

**Review by EricCousineau-TRI — COMMENTED** [review]
Sweet! Onwards!
-@rpoyner-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14902#-:-MYG3t1iEBAI5bUDb08P:b-r63l53)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
