### PR TITLE
geometry::optimization Replace ConvexSets class with a typedef.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
@jwnimmer-tri -- this checks all of the boxes but one: the ability construct the list of sets in python.  I'm sure that's surmountable, too... but I might need some help teaching pybind how to convert python iterables into lists of copyable_unique_ptrs.   I've opened this PR so you can see what I have.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345#-:-Me5bkhF2xaCOYiGWp92:bdwj9r8)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @RussTedrake)

___
*[geometry/optimization/convex_set.h, line 191 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15345#-Me5cBuB69NOk-gzvnHS:-Me5cBuB69NOk-gzvnHT:b-1l6md3) ([raw file](https://github.com/robotlocomotion/drake/blob/292d891c6bfaf4c160a1a4d70150b49be9448d6a/geometry/optimization/convex_set.h#L191)):*
> ```objc
> 
> // TODO(russt): Use std::vector<copyable_unique_ptr<ConvexSet>> pending #15344.
> /** Provides the recommended container for passing a collection of ConvexSet
> ```

btw -- hilarious diff.

**Review by RussTedrake — COMMENTED** [review]
I went ahead and worked through the pybind implicit conversions.  And merged in the copyable_unique_ptr upgrades.  This should now be ready to go!
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345#-:-MeA4gDFCHlzFPKExN4a:b-m3jq2k)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 7 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345#-:-MeAwKEL3vMPgElxozgD:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/geometry_py.cc, line 1340 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeAvckc-us0YkWRHdZH:-MeAvckc-us0YkWRHdZI:bay1fa2) ([raw file](https://github.com/robotlocomotion/drake/blob/55d5da77f481b6feadd20f64608a767db0907e7d/bindings/pydrake/geometry_py.cc#L1340)):*
> ```cpp
>     py::class_<copyable_unique_ptr<ConvexSet>>(m, "CopyableUniquePtrConvexSet")
>         .def(py::init([](const ConvexSet& e) {
>           return copyable_unique_ptr<ConvexSet>(e);
> ```

nit As I understand it, the fundamental reason why all of these pieces play nicely together in pydrake is that here we accept a reference and _always_ clone it, so that the new object is never an alias to the old.  It's probably worth adding a comment here to remind the reader of that idea, so that in the future nobody accidentally binds one of the other constructor overloads, which might be disastrous.
___
*[geometry/optimization/test/convex_set_test.cc, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeAtkeZ5-vKCDzJ_eyp:-MeAtke_D56sSwHSI312:bw4ilrx) ([raw file](https://github.com/robotlocomotion/drake/blob/55d5da77f481b6feadd20f64608a767db0907e7d/geometry/optimization/test/convex_set_test.cc#L80)):*
> ```cpp
>   const ConvexSets& const_sets = sets;
>   static_assert(
>       std::is_const_v<std::remove_reference<decltype(*const_sets[0])>::type>);
> ```

nit We generally prefer `std::remove_reference_t` (not `::type`) to use the shorter, C++17 sugar.

Or, perhaps another way to write this would be `is_same_v<const ConvexSex&, ...>` which more clearly shows const as well as the exact type.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/geometry_py.cc, line 1340 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeAvckc-us0YkWRHdZH:-MeBDxPVBcmnaGJ5r9BK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55d5da77f481b6feadd20f64608a767db0907e7d/bindings/pydrake/geometry_py.cc#L1340)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit As I understand it, the fundamental reason why all of these pieces play nicely together in pydrake is that here we accept a reference and _always_ clone it, so that the new object is never an alias to the old.  It's probably worth adding a comment here to remind the reader of that idea, so that in the future nobody accidentally binds one of the other constructor overloads, which might be disastrous.
</blockquote></details>

Done.
___
*[geometry/optimization/test/convex_set_test.cc, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeAtkeZ5-vKCDzJ_eyp:-MeBEePq04RRZGLX7Wg6:bjskgde) ([raw file](https://github.com/robotlocomotion/drake/blob/55d5da77f481b6feadd20f64608a767db0907e7d/geometry/optimization/test/convex_set_test.cc#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We generally prefer `std::remove_reference_t` (not `::type`) to use the shorter, C++17 sugar.

Or, perhaps another way to write this would be `is_same_v<const ConvexSex&, ...>` which more clearly shows const as well as the exact type.
</blockquote></details>

Done.  thought i went with ConvexSet instead of ConvexSex.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)* status: needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one minor issue in the tests.

> Reviewed 1 of 7 files at r1, 2 of 6 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345#-:-MeGdnUn76niJk4yUwyd:b-ievgq2)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/optimization/convex_set.h, line 191 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15345#-Me5cBuB69NOk-gzvnHS:-MeGcfSR6FL_x-DlTgqE:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/292d891c6bfaf4c160a1a4d70150b49be9448d6a/geometry/optimization/convex_set.h#L191)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- hilarious diff.
</blockquote></details>

Nice!
___
*[geometry/optimization/test/convex_set_test.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeGdSaN20cCGdRxiXVR:-MeGdSaN20cCGdRxiXVS:b-hngz2i) ([raw file](https://github.com/robotlocomotion/drake/blob/b4faa289e82a192b3f220bde33bf79b6a2049ec3/geometry/optimization/test/convex_set_test.cc#L81)):*
> ```cpp
>   static_assert(std::is_same_v<const ConvexSet&, decltype(*const_sets[0])>);
> 
>   // Confirm that I can move sets without copying the underlying data.
> ```

minor: I'm not seeing how the test below validates that the data was not copied. I expected to see something checking the addresses of the moved objects and maybe something verifying that the source object `sets` is now empty?

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345#-:-MeGfmS843JondjAPe5M:buasbda)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[geometry/optimization/test/convex_set_test.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeGdSaN20cCGdRxiXVR:-MeIHTK9BL_VtWiYM5DN:b-mk3k3z) ([raw file](https://github.com/robotlocomotion/drake/blob/b4faa289e82a192b3f220bde33bf79b6a2049ec3/geometry/optimization/test/convex_set_test.cc#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I'm not seeing how the test below validates that the data was not copied. I expected to see something checking the addresses of the moved objects and maybe something verifying that the source object `sets` is now empty?
</blockquote></details>

b_pointer was a raw pointer pointing to the original data.  The unique_ptr pointing to that data was moved away.  but I confirm that changing b_pointer still changes the object pointed to by moved[1]?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)* status: 1 unresolved discussion (waiting on @RussTedrake and @sherm1)

___
*[geometry/optimization/test/convex_set_test.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeGdSaN20cCGdRxiXVR:-MeIJF3WEK64vrDCHNQs:b-9x9f9g) ([raw file](https://github.com/robotlocomotion/drake/blob/b4faa289e82a192b3f220bde33bf79b6a2049ec3/geometry/optimization/test/convex_set_test.cc#L81)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

b_pointer was a raw pointer pointing to the original data.  The unique_ptr pointing to that data was moved away.  but I confirm that changing b_pointer still changes the object pointed to by moved[1]?
</blockquote></details>

The test proves that there is no aliasing, but if the value was copied instead of moved, I believe it would still pass.

**Comment by RussTedrake** [comment]
___
*[geometry/optimization/test/convex_set_test.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeGdSaN20cCGdRxiXVR:-MeIKZdq-yWASltGl1Pt:biq2gwz) ([raw file](https://github.com/robotlocomotion/drake/blob/b4faa289e82a192b3f220bde33bf79b6a2049ec3/geometry/optimization/test/convex_set_test.cc#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The test proves that there is no aliasing, but if the value was copied instead of moved, I believe it would still pass.
</blockquote></details>

Changing 
```
ConvexSets moved = std::move(sets);
```
to 
```
ConvexSets moved = sets;
```
results in 
```
[ RUN      ] ConvexSetsTest.BasicTest
geometry/optimization/test/convex_set_test.cc:94: Failure
Value of: moved[1]->PointInSet(new_point)
  Actual: false
Expected: true
[  FAILED  ] ConvexSetsTest.BasicTest (0 ms)
```

I don't mind changing it if there is a better way?  (This was the exact case you, Jeremy, warned me about -- someone holding a raw pointer to the original data).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15345)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @RussTedrake)

___
*[geometry/optimization/test/convex_set_test.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15345#-MeGdSaN20cCGdRxiXVR:-MeJ5F9K9KuI1pjZn6Jt:b-4mjumh) ([raw file](https://github.com/robotlocomotion/drake/blob/b4faa289e82a192b3f220bde33bf79b6a2049ec3/geometry/optimization/test/convex_set_test.cc#L81)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Changing 
```
ConvexSets moved = std::move(sets);
```
to 
```
ConvexSets moved = sets;
```
results in 
```
[ RUN      ] ConvexSetsTest.BasicTest
geometry/optimization/test/convex_set_test.cc:94: Failure
Value of: moved[1]->PointInSet(new_point)
  Actual: false
Expected: true
[  FAILED  ] ConvexSetsTest.BasicTest (0 ms)
```

I don't mind changing it if there is a better way?  (This was the exact case you, Jeremy, warned me about -- someone holding a raw pointer to the original data).
</blockquote></details>

OK I understand better now.  I suppose this still leaves open the door that the `sets` retains a (new) copy but the original was still moved into `moved`.

In any case, functional unit tests for a typedef are not particularly interesting (and should probably be removed entirely, in any case), so I'm not going to bikeshed.

I'm still LGTM with this PR as an improvement, even though I think there's still further to go.

**Pull request merged**
