### PR TITLE
[doc] Guidance to review tutorials

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19506)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform
-(status: single reviewer ok) +@jwnimmer-tri for feature review as I'm not familiar with advice we give for reviewing tutorials.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-:-NWmgr_J4JZ37cU3CDZz:b-qhvl1c)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
@jwnimmer-tri is OOO this week, and so does @EricCousineau-TRI. +@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-:-NWpMG0o9i2ZlHyIgx0w:b-r5xtfl)* status: LGTM missing from assignees jwnimmer-tri(platform),rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature -@rpoyner-tri.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-:-NWrQMzk3b58RAa4rGpr:bqfxfex)* status: 2 unresolved discussions

___
*[`tutorials/_developers.md` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-NWrP7mm9SmJ9PaaRJm8:-NWrP7mnDGmSiud0HLQc:bcmy5sd) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b1dbaf8811a212fac4284cbcf7bace4484d48db/tutorials/_developers.md#L25)):*
> ```Markdown
> not the json storage format of a notebook.
> Discuss changes in Reviewable; however,
> the "json code" in Reviewable is less relevant.
> ```

BTW Is there a particular reason the above text is line-wrapped like a poem instead of a paragraph?
___
*[`tutorials/_developers.md` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-NWrPe-A9RVpOsTpim0g:-NWrPe-A9RVpOsTpim0h:b-3hqxbh) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b1dbaf8811a212fac4284cbcf7bace4484d48db/tutorials/_developers.md#L35)):*
> ```Markdown
> ```
> git fetch upstream pull/99999/head && git checkout FETCH_HEAD
> git switch -c peek_at_PR_99999
> ```

BTW I never name the branch when previewing tutorials during a code review.  To me, this advice adds (detrimental) clutter to the set of local branch names (e.g., for tab completion) with no upside.  It is important that this second line be par of the canon?

If this line is removed, we could also cull the next two sentences, which also helps this whole section be more precise.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19506)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform)

___
*[`tutorials/_developers.md` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-NWrP7mm9SmJ9PaaRJm8:-NWre5WB00Nf2Hv0PAcQ:b-t3u2i6) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b1dbaf8811a212fac4284cbcf7bace4484d48db/tutorials/_developers.md#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there a particular reason the above text is line-wrapped like a poem instead of a paragraph?
</blockquote></details>

It's just my poetic habbit :smile: . I found that it's easier to maintain.  When I need to change some words, it stays in one line, like one programming statement.
___
*[`tutorials/_developers.md` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19506#-NWrPe-A9RVpOsTpim0g:-NWrfjJK6K-OQ7gBXnOG:b-x5z1iu) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b1dbaf8811a212fac4284cbcf7bace4484d48db/tutorials/_developers.md#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I never name the branch when previewing tutorials during a code review.  To me, this advice adds (detrimental) clutter to the set of local branch names (e.g., for tab completion) with no upside.  It is important that this second line be par of the canon?

If this line is removed, we could also cull the next two sentences, which also helps this whole section be more precise.
</blockquote></details>

Done. Removed `git switch` and the next two sentences.

I like to name branches because it lets me switch back and forth to other branches if needed. Here I remove `git switch`, so readers can decide themselves whether to name it or not.

**Pull request merged**
