### PR TITLE
Replace cc_library and cc_binary with Drake-specific wrappers.

### PR DESCRIPTION
**Pull request by david-german-tri**
This is a no-op.  It is a first step towards specifying Drake-specific compiler flags in the BUILD files instead of the CROSSTOOL, as recommended by the Bazel team at https://github.com/bazelbuild/bazel/issues/2444.

@jwnimmer-tri for both levels of review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4991)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq6nHjtBQI1lZrvWrM:-Kbq6nHkDl_tkMObp3tA:b-udmza5) (no related file):*
The `tools/cpplint.bzl` I wrote does a brittle thing and asks `if rule["kind"].startswith("cc_"):` which this PR will defeat.  Maybe band-aid it for now (allow `drake_cc_` as another prefix with a TODO) and I can fix in a follow-up PR?

---

*[drake/automotive/BUILD, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq5ci1oOH41VvIqLYn:-Kbq5ci2kLgkBDhJkqFO:b-wrhohn) ([raw file](https://github.com/robotlocomotion/drake/blob/16045426fa754dc96bc9fc4fa855969638843445/drake/automotive/BUILD#L7)):*
> ```Python
> load(
>     "//tools:drake.bzl",
>     "cc_googletest",
> ```

_Meta_ Should we call this `drake_cc_googletest` for consistency now?

---

*[drake/automotive/maliput/utility/BUILD, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq5vujWnwf2Y_iDDHH:-Kbq5vujWnwf2Y_iDDHI:b5h6pm5) ([raw file](https://github.com/robotlocomotion/drake/blob/16045426fa754dc96bc9fc4fa855969638843445/drake/automotive/maliput/utility/BUILD#L46)):*
> ```Python
> # === test/ ===
> 
> cc_test(
> ```

Shouldn't these be `drake_cc_test` for the same reason as the other renames?

---

*[drake/examples/QPInverseDynamicsForHumanoids/BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq6DrvbThfxLtTEdiW:-Kbq6DrvbThfxLtTEdiX:b-tu93mo) ([raw file](https://github.com/robotlocomotion/drake/blob/16045426fa754dc96bc9fc4fa855969638843445/drake/examples/QPInverseDynamicsForHumanoids/BUILD#L5)):*
> ```Python
> 
> load("//tools:cpplint.bzl", "cpplint")
> load("//tools:drake.bzl", "cc_googletest", "drake_cc_library")
> ```

BTW cc_googletest is unused (also true for a few of the other BUILD files in this PR)?  Or _Meta_ should we just use a standard `load` calls across all BUILD files with the common set, and not cull the unused ones?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4991)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq6nHjtBQI1lZrvWrM:-KbqLuXQC5knk4AJyJkp:bwkiqu5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `tools/cpplint.bzl` I wrote does a brittle thing and asks `if rule["kind"].startswith("cc_"):` which this PR will defeat.  Maybe band-aid it for now (allow `drake_cc_` as another prefix with a TODO) and I can fix in a follow-up PR?
</blockquote></details>

Done.

The updated commit stack is hand-crafted.

---

*[drake/automotive/BUILD, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq5ci1oOH41VvIqLYn:-KbqJt1KwRWaS7ueexRc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16045426fa754dc96bc9fc4fa855969638843445/drake/automotive/BUILD#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Should we call this `drake_cc_googletest` for consistency now?
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/BUILD, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq5vujWnwf2Y_iDDHH:-KbqKRq5WYk84v0FbNaw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16045426fa754dc96bc9fc4fa855969638843445/drake/automotive/maliput/utility/BUILD#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Shouldn't these be `drake_cc_test` for the same reason as the other renames?
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-Kbq6DrvbThfxLtTEdiW:-KbqLtjb3En1nFH_uQ6V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16045426fa754dc96bc9fc4fa855969638843445/drake/examples/QPInverseDynamicsForHumanoids/BUILD#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW cc_googletest is unused (also true for a few of the other BUILD files in this PR)?  Or _Meta_ should we just use a standard `load` calls across all BUILD files with the common set, and not cull the unused ones?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4991)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 38 of 38 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/cpplint.bzl, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-KbqN8JcSZkwHiz4Hx02:-KbqN8JcSZkwHiz4Hx03:b4jyxm1) ([raw file](https://github.com/robotlocomotion/drake/blob/c11390bbd70ebd83ec276012e73171432bad25d8/tools/cpplint.bzl#L36)):*
> ```Python
>       if label.endswith(extension):
>         return True
> ```

I think you still want a `return False` here if none matched?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-:-KbqNJ5Pe9TDbz3kRQzT:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/cpplint.bzl, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-KbqN8JcSZkwHiz4Hx02:-KbqOosKmPP48zjB1731:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c11390bbd70ebd83ec276012e73171432bad25d8/tools/cpplint.bzl#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think you still want a `return False` here if none matched?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4991)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4991)*

**Comment by david-german-tri** [comment]
Bazel builds passed.  Merging.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4991#-:-KbqV6hKmnI2rEI2bAx9:b-ihigf5)*

**Pull request merged**
