### PR TITLE
LCM struct initialization cleanup

### PR DESCRIPTION
**Pull request by naveenoid**
only for the optitrack translator LCM tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6720)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm: as an improvement.

I didn't check if this found all of the problems in the whole tree, but FYI it looks like at least a few other places have this problem as well:
- `drake/manipulation/util/test/robot_state_msg_translator_test.cc`
- `drake/perception/estimators/dev/test/articulated_icp_test.cc`

FYI my grep is `find . -type f -print0 | xargs -0 grep -n -e '_t [A-Za-z_]*;'`.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6720#-:-KqOy5XP0gh0wFmeFMBl:b-cv0pea)*

**Comment by naveenoid** [comment]
Good catch. I will go ahead and fix those as well within this PR.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6720#-:-KqP79_NWg3SetLiAqb_:brhfvet)*

**Comment by jwnimmer-tri** [comment]
:lgtm_cancel: assuming a new push will be forthcoming.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6720#-:-KqP7dLy1iw-OXm8JuOf:b-vuhfqz)*

**Comment by naveenoid** [comment]
done. PTAL.

---

Review status: 1 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6720#-:-KqTRnjDIFKRzXJKdUNq:bgn86me)*

**Comment by jwnimmer-tri** [comment]
:lgtm: +(status: curate commits before merging) 

I believe this PR and #6734 now overlap.  You win.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6720#-:-KqTSQGsUsA50i_VrGnt:b-rj4hfk)*

**Comment by naveenoid** [comment]
Woot!
squash and merging : -(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6720#-:-KqTWzhI6Kv8btyXlag0:b98yxy2)*

**Pull request merged**
