### PR TITLE
Add geometry::optimization::MakeConvexSets

### PR DESCRIPTION
**Pull request by RussTedrake**
This is a simple method to help initialize lists of ConvexSets.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19207)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for feature review, please?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19207#-:-NTEdCkv6Cl2ZMQXJGIg:b-qf68iz)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by RussTedrake — COMMENTED** [review]
Thank you.  The C++17 spelling isn't beautiful, but I'm glad to see the recursion disappear!
+@SeanCurtis-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19207#-:-NTFpJxACea20VIJkNFI:b-5frcjn)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19207#-:-NTFpYg5-CY1qV1dUVZk:bnfp4nl)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

The bindings will be fun.  :)

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19207#-:-NTG17HV0LfFhTv_dsVz:b1zmb0f)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19207#-:-NTG1cQK7ChmsMTlM6fM:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
There will be no bindings for this.  The obvious Python spelling works already.  Only the C++ implicit conversions need this extra love.

**Pull request merged**
