### PR TITLE
Use more logic from upstream FindMatlab in mex_setup()

### LINKED ISSUE #3382: Mysterious CI Failure - Certain Text in PR's Description Results in Failure to Identify MATLAB Root
In #3358, I encountered the following [mysterious pre-merge CI failure](https://drake-jenkins.csail.mit.edu/job/experimental/4407/compiler=gcc,label=linux_matlab,type=release/) in configuration `gcc_linux_matlab`:

```
CMake Error at /home/ubuntu/workspace/experimental/c5b85b52/cmake/mex.cmake:102 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:143 (mex_setup)


SWIG_EXECUTABLE: /home/ubuntu/workspace/experimental/c5b85b52/build/install/bin/swig
Checking if Swig has Matlab support... yes
Found Swig with Matlab support
CMake Error at /home/ubuntu/workspace/experimental/c5b85b52/build/install/share/cmake/SwigMatlab.cmake:43 (message):
  Please run 'mex_setup(REQUIRED)' which is provided by mex.cmake in
  https://github.com/RobotLocomotion/cmake before using this macro.
Call Stack (most recent call first):
  bindings/swig/CMakeLists.txt:55 (add_swig_matlab_module)
```

To debug this, I [instrumented](https://github.com/RobotLocomotion/drake/pull/3358/commits/b767d4ba06e97a3b98a9b3ef27e8e9c4ca428bfd) `mex.cmake` with a debug print statement. This resulted in the following being logged:

```
18:35:00 -- ************************** MATLAB ROOT: _matlab_root=This change was shown to decrease build times by
```

Since `_matlab_root` appeared to get part of the PR's description, I removed the following text from the description:

> Using an HP z640 workstation with an Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz, 40GB of Buffered DDR4 1866 MHz RAM, and commit 6d1f32d1c351e4c646009c3ee6e3e906bb2a4395, the build time and memory footprint without dReal is ~14 minutes and 5.1GB:
> 
> ```
> $ cd drake-distro
> $ rm -rf build; externals
> $ git reset --hard HEAD
> $ mkdir build; cd build
> $ cmake .. -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DDISABLE_MATLAB=TRUE -DWITH_DREAL=FALSE -DWITH_SNOPT=FALSE 
> $ /usr/bin/time --format=%E,%U,%M make -j12
> 13:55.23,4906.59,5097528
> ```

This resulted in the PR's pre-merge CI tests to pass: https://drake-jenkins.csail.mit.edu/job/experimental/4412/.

Thus, I believe there is a bug in `mex.cmake` that arises when the PR's description contains certain text.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #3382. Removes any use of `grep` which really was not necessary anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3391)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@david-german-tri for feature and platform review.

**Comment by liangfok** [comment]
BTW, this PR fixed #3384.

**Comment by david-german-tri** [comment]
:lgtm: Woohoo!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3391#-:-KRU7nbAa1IOrseIhWqr:bvhtf9d)*

**Pull request merged**
