### PR TITLE
Remove unary minus (-E) in symbolic::Expression

### PR DESCRIPTION
**Pull request by soonho-tri**
* `-E` is represented as a multiplication expression `-1 * E`. For example, `-x` becomes `-1 * x ^ 1` (as a multiplication expression).
 * Motivation: fewer syntactic kinds -> fewer pattern-matching in application code. (see `mathematical_program.cc`)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5024)

### CODE REVIEW

**Comment by soonho-tri** [comment]
There is a test failure. @hongkai-dai , please don't review it yet..

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-:-Kc-9y3w7CpPoCUv4Bto:bez2x05)*

**Comment by soonho-tri** [comment]
@hongkai-dai , it's good to go now.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-:-Kc-La8FGqHFdzYog2HL:b832pmq)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 6 files at r1, 2 of 3 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 250 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MNa2BR9gZK7gfaED:-Kc-MNa2BR9gZK7gfaEE:bkkh31p) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L250)):*
> ```cpp
> }
> 
> // Unary minus case: -(E)
> ```

This documentation should be gone?

---

*[drake/common/symbolic_expression.cc, line 296 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MqDoLXoUtFRx11ea:-Kc-MqDoLXoUtFRx11eb:b-242k8t) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L296)):*
> ```cpp
>     return lhs;
>   }
>   if (is_neg_one(lhs)) {
> ```

If `lhs` is -1, but `rhs` is neither addition nor multiplication, like `x` or `x**2` or division, does it still make sense to simplify it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by soonho-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 250 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MNa2BR9gZK7gfaED:-Kc-OMCT24pk0lsE828E:b-7dyr7t) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L250)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This documentation should be gone?
</blockquote></details>

It's about the `operator-` which we still allow users to use, while we eliminate the internal representation `ExpressionNeg`. 

---

*[drake/common/symbolic_expression.cc, line 296 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MqDoLXoUtFRx11ea:-Kc-OeWgbD5f8vj0XhHg:b-d9lt1r) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L296)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If `lhs` is -1, but `rhs` is neither addition nor multiplication, like `x` or `x**2` or division, does it still make sense to simplify it?
</blockquote></details>

 - I think we can simplify `-1 * x` or `-1 * x^2` any further.
 - For the division, we have `- (x / y)` -> `-1 * (x / y)`. I don't think `(-1 * x) / y` is strictly better than `-1 * (x / y)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by soonho-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 250 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MNa2BR9gZK7gfaED:-Kc-PjFfwBDXK6cWpZZb:b-7txfgr) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L250)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It's about the `operator-` which we still allow users to use, while we eliminate the internal representation `ExpressionNeg`. 
</blockquote></details>

Probably better to put `operator-`? I will do something soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 250 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MNa2BR9gZK7gfaED:-Kc-Q5DwFgo_iDKLWqJ8:b-7bufeb) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L250)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Probably better to put `operator-`? I will do something soon.
</blockquote></details>

Yes, I think "Unary minus" is not as clear as "operator-".

---

*[drake/common/symbolic_expression.cc, line 296 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MqDoLXoUtFRx11ea:-Kc-QxeWaI2sJNW-pd1p:b-kufkxf) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L296)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

 - I think we can simplify `-1 * x` or `-1 * x^2` any further.
 - For the division, we have `- (x / y)` -> `-1 * (x / y)`. I don't think `(-1 * x) / y` is strictly better than `-1 * (x / y)`.
</blockquote></details>

I see, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by soonho-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 250 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-MNa2BR9gZK7gfaED:-Kc-RplVxswOiBAd94j7:b-5mzarj) ([raw file](https://github.com/robotlocomotion/drake/blob/9244a1e40fe05735e87f2adedd7766d31499beef/drake/common/symbolic_expression.cc#L250)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, I think "Unary minus" is not as clear as "operator-".
</blockquote></details>

Done. (just deleted the comment since it's `.cc` file it's not required.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by hongkai-dai** [comment]
:lgtm: +@david-german-tri for platform review.

---

Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-:-Kc-SvFN-6JztX84Y7ar:b-qy0nfl)*

**Comment by david-german-tri** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 340 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-kB9VyFBx6jLneLWo:-Kc-kB9WqlJ-oCfNHSPu:b21bso7) ([raw file](https://github.com/robotlocomotion/drake/blob/57f62a640344aeea9778b83a2d8bf07384e084ff/drake/common/symbolic_expression.cc#L340)):*
> ```cpp
>   }
> 
>   if (is_neg_one(rhs)) {
> ```

Is this dead code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by david-german-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 340 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-kB9VyFBx6jLneLWo:-Kc-kuFh9wYJX4v5TE4Y:bj0nlgz) ([raw file](https://github.com/robotlocomotion/drake/blob/57f62a640344aeea9778b83a2d8bf07384e084ff/drake/common/symbolic_expression.cc#L340)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Is this dead code?
</blockquote></details>

Ooops.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by soonho-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.cc, line 340 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-Kc-kB9VyFBx6jLneLWo:-Kc-lPVzCs-0NMfi-T14:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/57f62a640344aeea9778b83a2d8bf07384e084ff/drake/common/symbolic_expression.cc#L340)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Ooops.. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5024#-:-Kc-m7gKIuu6ndxcfj-5:bnfp4nl)*

**Pull request merged**
