### PR TITLE
Add TaylorExpand

### LINKED ISSUE #9064: Taylor expansion for a given expression
Can we have the taylor expansion module built for some given expressions of nonlinear equations? Up to 3rd order would be great. Thanks!

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #9064

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@hongkai-dai , could you feature-review this one? 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGD-z82DDx5hNHKcdRX:b-cxk5qf)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGGqk6O4u8Smthtamvz:bl5ccwd)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r1.
Review status: 8 unresolved discussions, LGTM missing from assignee hongkai-dai, platform LGTM missing

---

*[common/symbolic_expression.h, line 932 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGGqxuZENWS8ijBIU7o:-LGGqxuZENWS8ijBIU7p:bch9iid) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.h#L932)):*
> ```objc
>                              const Eigen::Ref<const VectorX<Variable>>& vars);
> 
> /// Returns the Taylor series expansion of `f` around `a` of order `order`.
> ```

Document the input parameter `a` and `order`?

Specifically I think we should explain what happens if `a` does not contain all the variables appeared in `f`. For example, if we have `f(x, y)`, and `a` only contains the mapping `x:1`, then the returned taylor expansion only expands `f` about `x =1`.

---

*[common/symbolic_expression.cc, line 886 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQggaz8vojSf0JzBM7:-LGQggaz8vojSf0JzBM8:b-e29hlp) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L886)):*
> ```cpp
> using MultiIndex = vector<int>;
> 
> // Generates multi-indices of order `order` whose size is `num_vars` and add to
> ```

`add to vec` can be confusing with the numerically summing two vectors, element by element. Maybe change it to `append to vec`?

---

*[common/symbolic_expression.cc, line 887 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGHEvFz1WC3WS2bALLd:-LGHEvFz1WC3WS2bALLe:b420vmb) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L887)):*
> ```cpp
> 
> // Generates multi-indices of order `order` whose size is `num_vars` and add to
> // `vec`. It generates the indices by increase the elements of the given
> ```

`increase` -> `increasing`

---

*[common/symbolic_expression.cc, line 889 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQiWMA-YHRv88VIA9C:-LGQVFNu11fKhPTInqpK:b-u2c1vr) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L889)):*
> ```cpp
> // `vec`. It generates the indices by increase the elements of the given
> // `base`. It only changes the i-th dimension which is greater than or equal to
> // `j` to avoid duplicates.
> ```

There is no `j` in the input parameters, do you mean `start_dim`?

---

*[common/symbolic_expression.cc, line 891 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQhM5_6zT7Epsf2lMV:-LGQhM5_6zT7Epsf2lMW:b1r7jqs) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L891)):*
> ```cpp
> // `j` to avoid duplicates.
> void DoEnumerateMultiIndex(const int order, const int num_vars,
>                            const int start_dim, const MultiIndex& base,
> ```

Should there be any requirement on the length of `base`? Should I expect that `base.size() == num_vars`?

---

*[common/symbolic_expression.cc, line 921 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGHF1_Q86_mjenvDp1X:-LGHF1_Q86_mjenvDp1Y:bo4johz) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L921)):*
> ```cpp
> 
> // Computes the factorial of n.
> int Fact(int n) {
> ```

Rename the function to `Factorial`? `Fact` is a English word with a different meaning.

---

*[common/symbolic_expression.cc, line 980 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQpTfAER-JsXCwdm5_:-LGQpTfAER-JsXCwdm5a:bja3lcs) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L980)):*
> ```cpp
>   ExpressionAddFactory factory;
>   factory.AddExpression(f.Evaluate(a));
>   const int num_vars = f.GetVariables().size();
> ```

Should `num_vars` be the number of variables in the intersection of `f.Getariables()` and `a.key`?

---

*[common/test/symbolic_expression_test.cc, line 1960 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQpmE2BeZq-CCio-VE:-LGQpmE2BeZq-CCio-VF:bqbt07u) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/test/symbolic_expression_test.cc#L1960)):*
> ```cpp
> 
> TEST_F(SymbolicExpressionTest, TaylorExpand3) {
>   // Test TaylorExpand(sin(-x² - y²) + cos(z), 3)
> ```

Also add the env in the documentation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)*

**Comment by soonho-tri** [comment]
Comments are addressed. I've also added `DRAKE_ASSERT`s in the code. Thanks for the review, PTAL.

---

Review status: 8 unresolved discussions, LGTM missing from assignee hongkai-dai, platform LGTM missing

---

*[common/symbolic_expression.h, line 932 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGGqxuZENWS8ijBIU7o:-LGQvk977kGjaGvPe-bo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.h#L932)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document the input parameter `a` and `order`?

Specifically I think we should explain what happens if `a` does not contain all the variables appeared in `f`. For example, if we have `f(x, y)`, and `a` only contains the mapping `x:1`, then the returned taylor expansion only expands `f` about `x =1`.

</blockquote></details>

Done.

---

*[common/symbolic_expression.cc, line 886 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQggaz8vojSf0JzBM7:-LGQw7Pa-yo_A3FSJDFL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L886)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`add to vec` can be confusing with the numerically summing two vectors, element by element. Maybe change it to `append to vec`?
</blockquote></details>

Done.

---

*[common/symbolic_expression.cc, line 887 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGHEvFz1WC3WS2bALLd:-LGQwAGL3z2RiOR4mIuy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L887)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`increase` -> `increasing`
</blockquote></details>

Done.

---

*[common/symbolic_expression.cc, line 889 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQiWMA-YHRv88VIA9C:-LGQwD0FAcNnw2_j6-_F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L889)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

There is no `j` in the input parameters, do you mean `start_dim`?
</blockquote></details>

Done.

---

*[common/symbolic_expression.cc, line 891 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQhM5_6zT7Epsf2lMV:-LGQwR0b5Rmi6V6xtJ4U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L891)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should there be any requirement on the length of `base`? Should I expect that `base.size() == num_vars`?
</blockquote></details>

Done.

---

*[common/symbolic_expression.cc, line 921 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGHF1_Q86_mjenvDp1X:-LGQxLYHD6GQtkzTrpSV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L921)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Rename the function to `Factorial`? `Fact` is a English word with a different meaning.
</blockquote></details>

Done.

---

*[common/symbolic_expression.cc, line 980 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQpTfAER-JsXCwdm5_:-LGQxkJ9Bc8k5ibo-PJg:b-ys1my0) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/symbolic_expression.cc#L980)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should `num_vars` be the number of variables in the intersection of `f.Getariables()` and `a.key`?
</blockquote></details>

I think the current code should be good as it is. The environment `a` should provide assignments for all the variables appeared in `f` Otherwise, it throws (from `f.Evaluate(a)` above). 

---

*[common/test/symbolic_expression_test.cc, line 1960 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGQpmE2BeZq-CCio-VE:-LGQxjEy21zXq4oTZMFb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4130362f9e809aaab85d43965f21c12bd1b02a31/common/test/symbolic_expression_test.cc#L1960)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also add the env in the documentation?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGRDDwO7qW7HFGdwxox:b-xxde3y)*

**Comment by soonho-tri** [comment]
Review status: 9 unresolved discussions, LGTM missing from assignee hongkai-dai, platform LGTM missing

---

*[common/symbolic_expression.h, line 943 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGRDxt474AyRKPCGeUb:-LGRDxt474AyRKPCGeUc:b381n0k) ([raw file](https://github.com/robotlocomotion/drake/blob/4545372a866ead182c0d5f66c04bfea202df8c92/common/symbolic_expression.h#L943)):*
> ```objc
> /// @note The approximation point `a` should provide full assignments over the
> /// free variables in `f`. Otherwise, this function throws an exception.
> Expression TaylorExpand(const Expression& f, const Environment& a, int order);
> ```

@hongkai-dai , BTW, the semantics of `order` in our implementation is different from Matlab's `taylor` function which generates a polynomial of order `N-1` given `order = N`. Please let me know if it's clearer for us to match the semantics of Matlab's `taylor` function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)*

**Comment by hongkai-dai** [comment]
:lgtm: Thanks @soonho-tri for working this out so quickly.

+@sammy-tri for platform review please.

---

Reviewed 2 of 3 files at r2.
Review status: 1 unresolved discussion, platform LGTM missing

---

*[common/symbolic_expression.h, line 943 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGRDxt474AyRKPCGeUb:-LGRzT7RDe7bZStAPAG5:b-eo6uzi) ([raw file](https://github.com/robotlocomotion/drake/blob/4545372a866ead182c0d5f66c04bfea202df8c92/common/symbolic_expression.h#L943)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@hongkai-dai , BTW, the semantics of `order` in our implementation is different from Matlab's `taylor` function which generates a polynomial of order `N-1` given `order = N`. Please let me know if it's clearer for us to match the semantics of Matlab's `taylor` function.
</blockquote></details>

I think what we have is better than matlab's implementation. I like it!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGRzzHR2JU2OzOUaCEB:b-d9ku30)*

**Comment by soonho-tri** [comment]
BTW, @joycezyu and I checked that it works for her example (Pendulum + LQR + SOS).

---

Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGS7S89A12VThApTOHc:bjfkef6)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r2.
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)*

**Comment by sammy-tri** [comment]
One style question.

---

Reviewed 3 of 3 files at r2.
Review status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, platform LGTM missing

---

*[common/symbolic_expression.cc, line 892 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGVpuVLCaK3KFo3Q0XR:-LGVpuVM2dAfN3KWfCHG:b-fi6vd9) ([raw file](https://github.com/robotlocomotion/drake/blob/4545372a866ead182c0d5f66c04bfea202df8c92/common/symbolic_expression.cc#L892)):*
> ```cpp
> void DoEnumerateMultiIndex(const int order, const int num_vars,
>                            const int start_dim, const MultiIndex& base,
>                            vector<MultiIndex>* const vec) {
> ```

Ok, this one took me some grappling with http://drake.mit.edu/styleguide/cppguide.html#Use_of_const but I think it's in violation.

Use of `const` in this location for a pointer argument seems to prevent modifying the value of the pointer itself (e.g making it point to a different region of memory locally) but allows modifying the memory pointed to.  I think this violates the rule "You must not use const in a function declaration where it adds no meaning. That occurs in pass-by-value parameter declarations" since the thing being `const` here is the pointer which is passed by value and not the reference.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGWB90sC2FP_G4PZIeu:blqvuje)*

**Comment by jwnimmer-tri** [comment]
*[common/symbolic_expression.cc, line 892 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGVpuVLCaK3KFo3Q0XR:-LGWBd6j3NCdjHl6SVxi:b2lcktf) ([raw file](https://github.com/robotlocomotion/drake/blob/4545372a866ead182c0d5f66c04bfea202df8c92/common/symbolic_expression.cc#L892)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ok, this one took me some grappling with http://drake.mit.edu/styleguide/cppguide.html#Use_of_const but I think it's in violation.

Use of `const` in this location for a pointer argument seems to prevent modifying the value of the pointer itself (e.g making it point to a different region of memory locally) but allows modifying the memory pointed to.  I think this violates the rule "You must not use const in a function declaration where it adds no meaning. That occurs in pass-by-value parameter declarations" since the thing being `const` here is the pointer which is passed by value and not the reference.
</blockquote></details>

Since this is a function _definition_, not only a _declaration_, the "in a function declaration" clause does not apply.  The const here is not picked up by Doxygen, and does prevent reassignment of `vec`, so I think is okay?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)*

**Comment by soonho-tri** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, platform LGTM missing

---

*[common/symbolic_expression.cc, line 892 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGVpuVLCaK3KFo3Q0XR:-LGWCKYM3qTPbzro5A2l:bkm1sgq) ([raw file](https://github.com/robotlocomotion/drake/blob/4545372a866ead182c0d5f66c04bfea202df8c92/common/symbolic_expression.cc#L892)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since this is a function _definition_, not only a _declaration_, the "in a function declaration" clause does not apply.  The const here is not picked up by Doxygen, and does prevent reassignment of `vec`, so I think is okay?
</blockquote></details>

I agree with Jeremy. This is 1) a definition inside of `.cc` file and 2) it does add a meaning (do not change `vec` in the function body). Because of the same reason, I use `const int` (instead of `int`).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)*

**Comment by sammy-tri** [comment]
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM missing

---

*[common/symbolic_expression.cc, line 892 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9082#-LGVpuVLCaK3KFo3Q0XR:-LGWDSOZ51aoGBr74ksu:b-vidpgs) ([raw file](https://github.com/robotlocomotion/drake/blob/4545372a866ead182c0d5f66c04bfea202df8c92/common/symbolic_expression.cc#L892)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I agree with Jeremy. This is 1) a definition inside of `.cc` file and 2) it does add a meaning (do not change `vec` in the function body). Because of the same reason, I use `const int` (instead of `int`).
</blockquote></details>

I suppose I'd agree it does have meaning (and furthermore that I've spent too much energy thinking about it already).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9082#-:-LGWDpMT1ru2dBsw5eEq:bnfp4nl)*

**Pull request merged**
