### PR TITLE
mexification of the rest of contactConstraints

### LINKED ISSUE #535: move contactConstraints mex from control util over so all manipulators use it
currently, the atlas controller is using it, but even the atlas dynamics is not.

### PR DESCRIPTION
**Pull request by psiorx**
Includes mexification of the remaining unmexed parts of contactConstraints (first and second derivatives of the contact distances and surface tangent basis vectors).  Profiling is showing this to be about 10-20 times faster than the MATLAB implementation.  

However, since about 50% of the time spent in contactConstraints is in collisionDetect, the theoretical speedup for contactConstraints as a whole should be around a factor of 2, which is also consistent with profiler results.

For now, the bulk of the logic remains in the mex file to avoid having to restart MATLAB on every test iteration(for sanity purposes).  This will be moved into RBM proper when we're happy with it. Resolves #535

### CODE REVIEW

**Comment by RussTedrake** [comment]
This looks great.  But I think we absolutely have to have a unit test to keep these two versions in sync.  Could you add one? 

I also definitely agree about calling surfaceTangents from C instead of from Matlab.  Aok if you want to do that on a future pull.

**Comment by psiorx** [comment]
Absolutely.  Working on the unit test now.

**Comment by psiorx** [comment]
@RussTedrake Unit test is in.  I also refactored the derivative portion of contactConstraints out into its own file to make it more readable and easier to test/compare.

**Comment by RussTedrake** [comment]
very nice.  will just wait for the build servers.

**Comment by psiorx** [comment]
@RussTedrake Looks like the unit test is failing in windows before it even gets to this code.  It's complaining that "normal" is empty but that comes from collisionDetect upstream.  Is bullet collision detection known to be broken on windows?

**Comment by avalenzu** [comment]
I don't think we've had bullet working on Windows, have we?

**Comment by RussTedrake** [comment]
No bullet support on windows yet.  The code has to be robust to the possible non-existence of bullet

- Russ

**Comment by psiorx** [comment]
@avalenzu , 
I see.  It should be agnostic to the presence of bullet since that is handled by collisionDetectmex upstream.  

@RussTedrake ,
We should probably just add this unit test as a known issue on windows.

**Comment by RussTedrake** [comment]
No.  The protocol is to error with the missing dependency exception for a test that is expected to fail for that reason.

- Russ

**Comment by psiorx** [comment]
Dependency check is in and looks to be working for windows.  Anything else holding this back?

**Comment by RussTedrake** [comment]
i'm happy with this.  just have to merge it in manually.  since it will also conflict with my other active pull request, maybe i'll wait and see if that goes through quickly (just so I only have to manually merge once).

**Comment by psiorx** [comment]
@RussTedrake Sounds good.  I'll wait for the merge before pulling in surfaceTangents  (which should be easier now that its all in one file now).

**Comment by psiorx** [comment]
Does this still need a manual merge?

**Comment by RussTedrake** [comment]
yes, or you can rebase master in your pull request branch.

**Comment by psiorx** [comment]
Just to make sure my rebase went OK I ran the Atlas benchmark designed for rigidBodyManipulatormex.cpp on this branch.  Here's how it stacks up: 

Average over 10 samples for runtime (in seconds) of runAtlasWalking.m
mex_entry:
112.8081

master:
106.6510

jc-contactConstraintsmex:
98.5730

**Pull request merged**
