### PR TITLE
Update monogram notation for spatial velocity/acceleration.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
feature review: +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397#-:-MNV3Kg16bccIPpXwAaR:b-5w6zzc)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @mitiguy)

___
*[multibody/multibody_doxygen.h, line 277 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNVHMGb1Hpn_u9hBsX2:-MNVHMGb1Hpn_u9hBsX3:bu5po7d) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5e135a692508cdec28750a0295d179c177390c/multibody/multibody_doxygen.h#L277)):*
> ```objc
> _reference_ and _target_, either of which may be a frame, basis, or point, that
> specify how the quantity is defined. In computation, vector quantities are
> _expressed_ in a particular basis (or frame) that associates direction with each
> ```

This isn't clear  to me. Did you mean "associates a direction"?
___
*[multibody/multibody_doxygen.h, line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNVH9IK0xprHxfvlLv5:-MNVH9IK0xprHxfvlLv6:b-z7asf8) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5e135a692508cdec28750a0295d179c177390c/multibody/multibody_doxygen.h#L323)):*
> ```objc
> Acceleration         |  a   |@f$^Ba^Q@f$               |`a_BQ`      |%Point Q's translational acceleration in B
> Spatial acceleration |  A   |@f$^BA^{C}@f$             |`A_BC`      |Frame C's spatial acceleration in frame B (for point Co)
> Spatial acceleration |  A   |@f$^BA^{C}@f$             |`A_BCp`     |Frame C's spatial acceleration in frame B (for point Cp)
> ```

Why point Cp here but point Ccm above? The two quantities should be documented similarly. As written this doesn't achieve the goal of disambiguating Bo and Bcm. Maybe a footnote, for example "(for point Co¹)" ¹Note that the body origin is not necessarily the center of mass. ?

**Review by mitiguy — COMMENTED** [review]
Intention: Less words, more clarity.  Improve documentation on bodies and frames (shorter/more detailed), with information that disambiguates Bcm from Bo for translational and spatial velocities of a body.  Cross references from multibody notation table.  Inserted some non-breaking half-spaces to avoid weird line breaks before footnote markers.  Also improved ordering and appearance of footnote markers.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397#-:-MNaKBxABA7e-bOmSe_f:b-xlnwe9)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/multibody_doxygen.h, line 277 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNVHMGb1Hpn_u9hBsX2:-MNeHfEh-ikh08PGSc27:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5e135a692508cdec28750a0295d179c177390c/multibody/multibody_doxygen.h#L277)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This isn't clear  to me. Did you mean "associates a direction"?
</blockquote></details>

Done.
___
*[multibody/multibody_doxygen.h, line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNVH9IK0xprHxfvlLv5:-MNeHgW2D5Snulp9v0ly:b-u54mcn) ([raw file](https://github.com/robotlocomotion/drake/blob/6d5e135a692508cdec28750a0295d179c177390c/multibody/multibody_doxygen.h#L323)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Why point Cp here but point Ccm above? The two quantities should be documented similarly. As written this doesn't achieve the goal of disambiguating Bo and Bcm. Maybe a footnote, for example "(for point Co¹)" ¹Note that the body origin is not necessarily the center of mass. ?
</blockquote></details>

Done.  Also made footnote markers ordered and more extensible.
†ᵃ    †ᵇ    †ᶜ    †ᵈ  ...
___
*[multibody/multibody_doxygen.h, line 326 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNeXMlU2gN7o-uIVcAH:-MNeXMlVBeovYF8WvRvC:bkqmbei) ([raw file](https://github.com/robotlocomotion/drake/blob/cd7e7d018b3cc87f81677c7273676e95dadd977c/multibody/multibody_doxygen.h#L326)):*
> ```objc
> Jacobian wrt q̇       | Jqdot|@f$J_{q̇}^{{}^Bv^Q}@f$     |`Jqdot_v_BQ`|Q's translational velocity Jacobian in B wrt q̇
> Jacobian wrt v       | Jv   |@f$J_{v}^{{}^Bv^Q}@f$     |`Jv_v_BQ`   |Q's translational velocity Jacobian in B wrt v
> Jacobian wrt v       | Jv   |@f$J_{v}^{{}^B\omega^C}@f$|`Jv_w_BC`   |C's angular velocity Jacobian in B wrt v
> ```

nit  Some non-breaking half-spaces were added here to avoid weird breaks in the visual documentation (particularly to avoid footnote markers that appear on a separate line) .    You may find it difficult to see the differences.

**Review by mitiguy — COMMENTED** [review]
In PR# 14382, the following was my suggested comment that appears 9 times in various locations for a  body's spatial velocity/acceleration.  My suggested comment starts with @note.

  /// Returns the spatial velocity `V_WB` of this body B in the world frame W
  /// as a function of the state of the model stored in `context`.
  /// @note The returned spatial velocity's translational part is v_WBo_W,
  /// the velocity of Bo (body B's origin) in world W, expressed in W.
  /// In general, Bo differs from Bcm (body B's center of mass).

Perhaps something like this would be shorter/better.
  /// @retval `V_WB`, body B's spatial velocity in the world frame W, 
  /// expressed in world frame W (for point Bo, the body_frame's origin).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397#-:-MNetkPd3epG4wnw43Py:b-egzvfo)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm_strong: x 2 with a few nits. 
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397#-:-MNjsuCX2MsmFVUPtkZs:b-6ivo1b)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/multibody_doxygen.h, line 193 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNf-DjM6RJ03dm_FO05:-MNf-DjM6RJ03dm_FO06:b1zz0gt) ([raw file](https://github.com/robotlocomotion/drake/blob/cd7e7d018b3cc87f81677c7273676e95dadd977c/multibody/multibody_doxygen.h#L193)):*
> ```objc
>      |   /            Frame F with origin point Fo
>      |  /             and right-handed orthogonal
>      | /              unit vectors Fx, Fy, Fz.
> ```

Per f2f -- nice, needs cross product still.
___
*[multibody/multibody_doxygen.h, line 209 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjnlG32kjd319IuPQF:-MNjnlG32kjd319IuPQG:br2ifbf) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L209)):*
> ```objc
> unit vectors `Ax, Ay, Az`). Similarly, `w_AB` denotes frame B's angular velocity
> in frame A, expressed in frame A.  `V_AB` denotes frame B's spatial velocity
> in frame A, expressed in frame A.
> ```

BTW consider saying a little more here about the spatial velocity to connect it with the previous discussion, e.g. "That includes B's angular velocity and Bo's translational velocity, both in frame A."
___
*[multibody/multibody_doxygen.h, line 213 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjogGb0yfr89vFuRdN:-MNjogGb0yfr89vFuRdO:bugdoas) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L213)):*
> ```objc
> 
> Each _body_ contains a _body frame_  and we use the same symbol `B` for both a
> _body_ `B` and its _body frame_. Body B's location is defined via `Bo` (the
> ```

nit: should only italicize body and body frame the first time they are mentioned. 
___
*[multibody/multibody_doxygen.h, line 304 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjqUjc3sKvmGalZEQr:-MNjqUjd5oDtFx21ZuXp:bs39go6) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L304)):*
> ```objc
> ---------------------|:----:|:------------------------:|:----------:|----------------------------
> Rotation matrix      |  R   |@f$^BR^C@f$               |`R_BC`      |Frame C's orientation in frame B
> Position vector      |  p   |@f$^Pp^Q@f$               |`p_PQ`      |Position from point P to point Q
> ```

nit: "Position from" -> "Position vector from".
___
*[multibody/multibody_doxygen.h, line 342 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjrWWj8quGdfm6FL8C:-MNjrWWj8quGdfm6FL8D:b-k5us20) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L342)):*
> ```objc
> body D's translational and spatial velocity are for point Do (the origin of
> D's _body frame_), not for Dcm (D's center of mass).  See
> @ref multibody_frames_and_bodies for more information about frames and bodies.
> ```

nit: redundant when formatted in Doxygen since the section name comes out "Frames and Bodies". Can just end with "for more information."

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/multibody_doxygen.h, line 193 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNf-DjM6RJ03dm_FO05:-MNkWz-R3ivFS3qBpLOl:bhommrf) ([raw file](https://github.com/robotlocomotion/drake/blob/cd7e7d018b3cc87f81677c7273676e95dadd977c/multibody/multibody_doxygen.h#L193)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Per f2f -- nice, needs cross product still.
</blockquote></details>

Done (I think).  Let me know if the text to the right of the figure is sufficient as it contains the comment about Fz = Fx x Fy.
___
*[multibody/multibody_doxygen.h, line 209 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjnlG32kjd319IuPQF:-MNkexmSEI4XIyJOy3sh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L209)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider saying a little more here about the spatial velocity to connect it with the previous discussion, e.g. "That includes B's angular velocity and Bo's translational velocity, both in frame A."
</blockquote></details>

Done.
___
*[multibody/multibody_doxygen.h, line 213 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjogGb0yfr89vFuRdN:-MNkZHTb9Hq8GJyEjZDY:b-1gx5s8) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L213)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: should only italicize body and body frame the first time they are mentioned. 
</blockquote></details>

Done (updated here and related places for this PR).
___
*[multibody/multibody_doxygen.h, line 304 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjqUjc3sKvmGalZEQr:-MNkZU1O2pRl1C67kMgl:b-5e2iy8) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L304)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "Position from" -> "Position vector from".
</blockquote></details>

Done  (here and one other place in the file).
___
*[multibody/multibody_doxygen.h, line 342 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNjrWWj8quGdfm6FL8C:-MNk_EQK7KyOKB6y-FY1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1220e5218a14200079211a5af4ef350b963f414/multibody/multibody_doxygen.h#L342)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: redundant when formatted in Doxygen since the section name comes out "Frames and Bodies". Can just end with "for more information."
</blockquote></details>

Done.

**Review by mitiguy — COMMENTED** [review]
label +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397#-:-MNyQP8tE6zE3A2iDtAT:br1597u)* status: 1 unresolved discussion (waiting on @sherm1)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[multibody/multibody_doxygen.h, line 193 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14397#-MNf-DjM6RJ03dm_FO05:-MO--cnG0zetZ9JOFFIg:bajqtey) ([raw file](https://github.com/robotlocomotion/drake/blob/cd7e7d018b3cc87f81677c7273676e95dadd977c/multibody/multibody_doxygen.h#L193)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done (I think).  Let me know if the text to the right of the figure is sufficient as it contains the comment about Fz = Fx x Fy.
</blockquote></details>

@sherm1  -- PTAL.  Perhaps this is ready to merge ?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14397)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Comment by sherm1** [comment]
Ready to squash-merge, @mitiguy -- please revise the commit message down to something meaningful when you squash.

**Comment by EricCousineau-TRI** [comment]
*[`multibody/multibody_doxygen.h` line 199 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14397#-NnQdtmC44aSrPpMAdIo:-NnQdtmC44aSrPpMAdIp:bk3a0xb) ([raw file](https://github.com/robotlocomotion/drake/blob/981f20f715d6a83a691147a61e59a20e302af543/multibody/multibody_doxygen.h#L199)):*
> ```objc
> frame", herein called the _World_ frame W (also called _Ground_ frame G or
> _Newtonian Frame_ N).  Any frame with fixed pose in W is also an inertial frame.
> Drake supports _Model_ frames (inertial frames fixed in W) so a simulation can
> ```

I do not believe this is correct. `__model__` frames are attached to the "canonical link" of a model, and thus are not always inertial:
http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&#canonical-link-and-model-frame
I will PR a simple deletion of this statement.

**Pull request merged**
