### PR TITLE
Renamed "contact" to "constraint" to prepare for time stepping.

### PR DESCRIPTION
**Pull request by edrumwri**
Time stepping RigidBodyPlant will account for rigid contact _and_ joint limit constraints in this quarter, and this rename anticipates that change.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6786)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-KqxnR0dqVF_h2oPWhzZ:brbsdox)*

**Comment by amcastro-tri** [comment]
Why instead of `RigidConstraint` not `ContactConstraint`? what about this code is specific to rigid contact? On a quick look I can see how I could do soft contact as well. :lgtm: 

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_constraint/rigid_constraint_solver.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kqy1IxcM7VGJcs1DC_D:-Kqy1IxcM7VGJcs1DC_E:b-z5othf) ([raw file](https://github.com/robotlocomotion/drake/blob/a867f738cfc8dce863ed0777901dc45192e066e1/drake/multibody/rigid_constraint/rigid_constraint_solver.h#L17)):*
> ```objc
> namespace rigid_constraint {
> 
> /// Solves rigid constraint problems for constraint forces. Specifically, given
> ```

BTW, I dont think this first sentence reads nicely anymore. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kqy3miEtobwkSbg8FEc:bcxxk99)*

**Comment by edrumwri** [comment]
+@sherm1 for feature review please (per regular rotation)

---

Review status: 6 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr0_jVsqEPZwHtTS0Eg:b-2mdm7p)*

**Comment by edrumwri** [comment]
@amcastro-tri: these associated classes are moving from the ability to model "only" rigid contact to all rigid constraints, so I want to remove the specificity of the word "contact". To answer your second question, which I'll rephrase as "what about this code is specific to rigid _constraints_?": all constraints are modeled in such a way that they are enforced using the Lagrange-D'Alembert principle, practically meaning that constraint forces must be solved for. The philosophically opposite approach would be to enforce all constraints using strictly penalty forces.

---

Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_constraint/rigid_constraint_solver.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kqy1IxcM7VGJcs1DC_D:-Kr0aBBnoxnNWQaVwLjM:bquj29a) ([raw file](https://github.com/robotlocomotion/drake/blob/a867f738cfc8dce863ed0777901dc45192e066e1/drake/multibody/rigid_constraint/rigid_constraint_solver.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I dont think this first sentence reads nicely anymore. 
</blockquote></details>

BTW :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr0aHjlw29Dd_li3qB2:b-rfi7x6)*

**Comment by amcastro-tri** [comment]
I guess I just don't know what the term "rigid constraint" means. To me, there are just either bilateral or unilateral constraints. For instance, for the model of a soft ball on say a table, I can enforce the non-penetration constraint with the same unilateral constraints I use for rigid problems, AFAIK (in the continuum mechanics world they call them Signorini problem, but when discretized they look exactly the same).

---

Reviewed 1 of 14 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/BUILD, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0d_Xk9U_vCLuNTtqc:-Kr0d_Xk9U_vCLuNTtqd:b-yoh59g) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/BUILD#L146)):*
> ```Python
>     "//drake/multibody:rigid_body_tree",
>     "//drake/multibody:rigid_body_tree_construction",
>     "//drake/multibody/rigid_constraint:rigid_constraint",
> ```

BTW, isn't having `rigid_constraint:rigid_constraint` redundant? 

---

*[drake/examples/rod2d/rod2d.h, line 523 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0bw1gGvO3cCP16yUa:-Kr0bw1gGvO3cCP16yUb:b-4tkrif) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/examples/rod2d/rod2d.h#L523)):*
> ```objc
>   /// @param points a vector of contact points, expressed in the world frame.
>   /// @param[out] data the rigid impact problem data.
>   void CalcRigidImpactProblemData(const systems::Context<T>& context,
> ```

BTW, I think you can format this better. Maybe the `context` and `points` arguments on a same line followed by the `data` argument. I'm just surprised clang-format allows this. 

---

*[drake/examples/rod2d/test/rod2d_test.cc, line 202 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0cPhXQTs4OOUWycSf:-Kr0cPhXQTs4OOUWycSg:bsz68w9) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/examples/rod2d/test/rod2d_test.cc#L202)):*
> ```cpp
>     // Compute the problem data.
>     dut_->CalcRigidConstraintProblemData(*context_, contacts, tangent_vels,
>         data);
> ```

BTW, indentation looks strange. Maybe move all arguments to the next line?

---

*[drake/multibody/rigid_constraint/rigid_constraint_solver.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0ccpJUiT4TF6yjVgv:-Kr0ccpJUiT4TF6yjVgw:bhqnrc9) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/multibody/rigid_constraint/rigid_constraint_solver.cc#L7)):*
> ```cpp
> namespace rigid_constraint {
> 
> template class RigidConstraintSolver<double>;
> ```

BTW, I assume this doesn't work on `AutodiffScalarXd`? what portions doesn't compile? maybe a comment stating where this fails?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr0d3_zT2hj7trL8nPz:b-wt9o5j)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr19Uuup7c_z7exV_Sr:-Kr19Uuv5Bu1q98c5CnA:bgzx2k7) (no related file):*
Per VC, a possible name could be `HardConstraintSolver` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/BUILD, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0d_Xk9U_vCLuNTtqc:-Kr1QXS3tQxTUzeGetT6:b-v6rq5u) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/BUILD#L146)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, isn't having `rigid_constraint:rigid_constraint` redundant? 
</blockquote></details>

BTW It might be, but I didn't set this up- only renamed it.

---

*[drake/examples/rod2d/rod2d.h, line 523 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0bw1gGvO3cCP16yUa:-Kr1QeGVHAILl3WLjCBu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/examples/rod2d/rod2d.h#L523)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I think you can format this better. Maybe the `context` and `points` arguments on a same line followed by the `data` argument. I'm just surprised clang-format allows this. 
</blockquote></details>

Done.

---

*[drake/examples/rod2d/test/rod2d_test.cc, line 202 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0cPhXQTs4OOUWycSf:-Kr1QtSVA8CtjdDgrRHX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/examples/rod2d/test/rod2d_test.cc#L202)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, indentation looks strange. Maybe move all arguments to the next line?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_constraint/rigid_constraint_solver.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr0ccpJUiT4TF6yjVgv:-Kr1Siu5UgMVvdy90MTM:bobzy39) ([raw file](https://github.com/robotlocomotion/drake/blob/b6a443ef96380797e8033d14a5c9fb4b0212eb55/drake/multibody/rigid_constraint/rigid_constraint_solver.cc#L7)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, I assume this doesn't work on `AutodiffScalarXd`? what portions doesn't compile? maybe a comment stating where this fails?
</blockquote></details>

BTW It currently compiles but is not tested, so I didn't want to support the type (yet).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786)*

**Comment by edrumwri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr19Uuup7c_z7exV_Sr:-Kr23cMrsQvkJRn0Q2q6:b-fvboav) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Per VC, a possible name could be `HardConstraintSolver` instead.
</blockquote></details>

I'm going with this suggestion since "Rigid" indicates true rigidity, and "Hard" can indicate either rigidity or something near it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786)*

**Comment by amcastro-tri** [comment]
Reviewed 5 of 19 files at r1, 15 of 15 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr19Uuup7c_z7exV_Sr:-Kr2X0HZuSmlFIg3sREv:b-vgs4ru) (no related file):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I'm going with this suggestion since "Rigid" indicates true rigidity, and "Hard" can indicate either rigidity or something near it.
</blockquote></details>

One last suggestion since might as well speak up now or forever hold my peace, what about `HardConstraintsSolver`? i.e. plural instead since in general this solver would solve for several constraints?

---

*[drake/examples/rod2d/rod2d.h, line 422 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr2WHqdRySB7YBViWBt:-Kr2WHqeEjVJsblFz5s5:b-qs79r8) ([raw file](https://github.com/robotlocomotion/drake/blob/196043ec8479f87de8d2e96b2444bfaeb17ba510/drake/examples/rod2d/rod2d.h#L422)):*
> ```objc
>   ///      Assertion failure is triggered if the rod is in a ballistic mode.
>   T CalcNormalAccelWithoutContactForces(
>       const systems::Context<T>& context) const;
> ```

BTW, does it fit in a single line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr19Uuup7c_z7exV_Sr:-Kr2ZXRUtr8Q8LLAZv9f:b-pwm8am) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

One last suggestion since might as well speak up now or forever hold my peace, what about `HardConstraintsSolver`? i.e. plural instead since in general this solver would solve for several constraints?
</blockquote></details>

Eh, true, but diminishing returns, I'd say. A quick look shows that it does multiple constraints. 

---

*[drake/examples/rod2d/rod2d.h, line 422 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-Kr2WHqdRySB7YBViWBt:-Kr2_B83KKPdX28BP_i-:bdrwa1z) ([raw file](https://github.com/robotlocomotion/drake/blob/196043ec8479f87de8d2e96b2444bfaeb17ba510/drake/examples/rod2d/rod2d.h#L422)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, does it fit in a single line?
</blockquote></details>

It does, but I try not to change one little thing in the context of a different PR (particularly a moderately sized PR).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786)*

**Comment by sherm1** [comment]
Follow up per f2f: Evan pointed out that unilateral constraint conditions are often force-based, even if the resulting bilateral constraints are kinematic (for example, λ > 0 for the otherwise-holonomic contact normal constraint). So "kinematic" is really too restrictive. Verdict: just call them "constraints". They are in the multibody namespace so are clearly multibody constraints. Also worth mentioning that a single logical *constraint*, like "frictional contact", will generate multiple *constraint equations*, each of which comes with an unknown scalar λ. (cc @mitiguy) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr6fUQiJ0oFDKWMw3hw:bb54gvk)*

**Comment by edrumwri** [comment]
Whew- that rename was tougher than expected!

---

Review status: 0 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr3YCMYjSlWr8Gd-fqW:b-1ptorn)*

**Comment by sherm1** [comment]
CI fail.

---

Reviewed 1 of 40 files at r5.
Review status: 1 of 30 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr7EfyOFxKB8rKbxM9v:b187icb)*

**Comment by sherm1** [comment]
Name change :lgtm:. But I notice that one subdirectory is named "kinematic_constraint" which name got rejected in the earlier discussion. All the code uses "constraint" though. Just pointing this out to make sure it is what you wanted -- could just call that subdirectory "constraint"? 

---

Reviewed 5 of 24 files at r1, 5 of 20 files at r4, 39 of 40 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-Kr7GsD65kw1iuw9lv6u:b7pfsk1)*

**Comment by sherm1** [comment]
There are still two CMake files under `multibody/kinematic_constraint/` here. Did you mean to nuke those?

---

Reviewed 4 of 44 files at r5, 27 of 27 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6786#-:-KrBn99VKVdt4rJ2tn45:b-x36t0a)*

**Pull request merged**
