### PR TITLE
Set visibility to hidden for libf2c

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8136)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8136#-:-L5unfiZ1ZeJofcoum6n:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

I don't know if macOS is at risk of a problem here.  Feel free to merge without waiting if you wish.

**Comment by jwnimmer-tri** [comment]
macOS build passed.

**Pull request merged**
