### PR TITLE
simulator: resolved mismatch of simulator integrator defaults

### PR DESCRIPTION
**Pull request by dmcconachie-tri**
Towards #12903 

- Removed duplication of integrator defaults.
- Updated test to check if SimulatorConfig defaults are congruent with
integrator defaults.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)

### CODE REVIEW

**Review by dmcconachie-tri — COMMENTED** [review]
+@sherm1 for feature review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150#-:-MIZm-MQ0J3153y9IEqU:b1tu4a9)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @dmcconachie-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MIZtZoU693Fa7Al2kPQ:-MIZtZoU693Fa7Al2kPR:b-m5b21k) (no related file):*
For any Anzu programs that are impacted by these changes to defaults, we need to first land an Anzu PR that reaffirms the current (prior) defaults explicitly for those programs, before we merge this Drake PR that changes the defaults.

---

**Review by sherm1 — COMMENTED** [review]
Thanks, @dmcconachie-tri. Feature :lgtm: with one nit.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150#-:-MI_9i1a5GUhNICW67ho:b-pj1awl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_9HFm8Db9yNrXA-94:-MI_9HFn0gImoIEhdskP:b-giiout) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L31)):*
> ```objc
> // Default integrator used by a Simulator.
> // N.B. Keep this in sync with the Simulator constructor in `simulator.cc`.
> const char* const kDefaultIntegratorName = "runge_kutta3";
> ```

nit: this and realtime rate should also be static constexpr for consistency:
```c++
static constexpr double kDefaultTargetRealtimeRate = 0.0;
static constexpr const char* kDefaultIntegratorName = "runge_kutta3";
```
(I wasn't sure about the syntax for the string but that seems to work.)

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review since I'm on-call today and here anyway.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150#-:-MI_HHcp3sC3ATV1c0yr:b-vtj4vo)* status: 5 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_ExIg7hzfyYfapL3Y:-MI_ExIg7hzfyYfapL3Z:b3u4i7s) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L30)):*
> ```objc
> 
> // Default integrator used by a Simulator.
> // N.B. Keep this in sync with the Simulator constructor in `simulator.cc`.
> ```

nit If there's an easy way to replace this comment (and the matching cc file comment) with a unit test instead, that would probably be superior?

Actually looking now, the new test code seems to cover this already, so we could purge these comments now already?
___
*[systems/analysis/simulator.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_FVC7AezgBK87mFdL:-MI_FVC8CAKKAEFuC89k:bbegu36) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L37)):*
> ```objc
> 
> // Default initial step size used by the integrator.
> static constexpr double kDefaultInitialStepSizeAttempt = 1e-4;
> ```

nit Unclear why "attempt" is suffixed onto the noun phrase "initial step size" in this case but not elsewhere.  What is special going on here?
___
*[systems/analysis/simulator_gflags.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_GO0n9IDTvcy4ASHI:-MI_GO0n9IDTvcy4ASHJ:b8r9xvj) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator_gflags.cc#L54)):*
> ```cpp
>               "step size integrators with error control.");
> 
> DEFINE_bool(simulator_use_error_control, true,
> ```

This `true` seems like a copy of a default value that isn't checked by unit tests.  Replacing it with `SimulatorConfig{}.use_error_control` would be a fine fix.

As an aside -- in general, all of the `internal::kDefault` names probably could disappear, and we'd just use the (public) SimulatorConfig defaults everywhere instead.  That's more of a judgement call, though.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 5 unresolved discussions (waiting on @dmcconachie-tri and @jwnimmer-tri)

___
*[systems/analysis/simulator.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_FVC7AezgBK87mFdL:-MI_Qu2RAtDNjSPhAxmB:b5l9c8q) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unclear why "attempt" is suffixed onto the noun phrase "initial step size" in this case but not elsewhere.  What is special going on here?
</blockquote></details>

That's because the integrator's convergence and error control determines the actual initial step size taken. This really does tell the integrator what to try first but can't dictate the actual size of the initial step which may turn out to be smaller.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 5 unresolved discussions (waiting on @dmcconachie-tri and @sherm1)

___
*[systems/analysis/simulator.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_FVC7AezgBK87mFdL:-MI_Sp2b354znw8taD_D:b6lpccr) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That's because the integrator's convergence and error control determines the actual initial step size taken. This really does tell the integrator what to try first but can't dictate the actual size of the initial step which may turn out to be smaller.
</blockquote></details>

The methods https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_integrator_base.html#ac19919024e6d4d17453e610f57e53eba and https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_integrator_base.html#aaa818a52a133131208f51b1c0a3a906c do not use the word "attempt" though -- they say "target" -- but seem to have the same purpose. Why two different phrasings for the same concept?  Things that are the same should be named the same everywhere.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 5 unresolved discussions (waiting on @dmcconachie-tri and @jwnimmer-tri)

___
*[systems/analysis/simulator.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_FVC7AezgBK87mFdL:-MI_V8n1CdzlhEEh8qom:bsttou) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The methods https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_integrator_base.html#ac19919024e6d4d17453e610f57e53eba and https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_integrator_base.html#aaa818a52a133131208f51b1c0a3a906c do not use the word "attempt" though -- they say "target" -- but seem to have the same purpose. Why two different phrasings for the same concept?  Things that are the same should be named the same everywhere.
</blockquote></details>

You're right -- this constant should be named kDefaultInitialStepSizeTarget for consistency.

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 3 unresolved discussions (waiting on @dmcconachie-tri, @jwnimmer-tri, and @sherm1)

___
*[systems/analysis/simulator.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_ExIg7hzfyYfapL3Y:-MI_ZBosBe-VKy7__XCR:bivqmsw) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If there's an easy way to replace this comment (and the matching cc file comment) with a unit test instead, that would probably be superior?

Actually looking now, the new test code seems to cover this already, so we could purge these comments now already?
</blockquote></details>

How about something like
```C++
DRAKE_DEMAND(std::strcmp(internal::kDefaultIntegratorName, "runge_kutta3") == 0);
```
in the `cc` file as a way to convert  the assertion via comment to an enforced assertion? It also puts error trapping closer to the code that it's designed to check.
___
*[systems/analysis/simulator.h, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_9HFm8Db9yNrXA-94:-MI_Zg0EDyaaXJD1Z1Lp:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this and realtime rate should also be static constexpr for consistency:
```c++
static constexpr double kDefaultTargetRealtimeRate = 0.0;
static constexpr const char* kDefaultIntegratorName = "runge_kutta3";
```
(I wasn't sure about the syntax for the string but that seems to work.)
</blockquote></details>

Done
___
*[systems/analysis/simulator.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_FVC7AezgBK87mFdL:-MI_ZqWPBoXtsYhc-HHf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You're right -- this constant should be named kDefaultInitialStepSizeTarget for consistency.
</blockquote></details>

Done.
___
*[systems/analysis/simulator_gflags.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_GO0n9IDTvcy4ASHI:-MI_agjKD_ljr4fkRsi_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator_gflags.cc#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This `true` seems like a copy of a default value that isn't checked by unit tests.  Replacing it with `SimulatorConfig{}.use_error_control` would be a fine fix.

As an aside -- in general, all of the `internal::kDefault` names probably could disappear, and we'd just use the (public) SimulatorConfig defaults everywhere instead.  That's more of a judgement call, though.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
___
*[systems/analysis/simulator.h, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_ExIg7hzfyYfapL3Y:-MI_jp4G7EHAUKxZMbY1:b-81nlyc) ([raw file](https://github.com/robotlocomotion/drake/blob/9a2fec631a9bb4fb7d2ddbbb634ddd0526ca7f59/systems/analysis/simulator.h#L30)):*
<details><summary><i>Previously, dmcconachie-tri wrote…</i></summary><blockquote>

How about something like
```C++
DRAKE_DEMAND(std::strcmp(internal::kDefaultIntegratorName, "runge_kutta3") == 0);
```
in the `cc` file as a way to convert  the assertion via comment to an enforced assertion? It also puts error trapping closer to the code that it's designed to check.
</blockquote></details>

SGTM.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 4 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_jxrr2vNY3aR18u9f:-MI_jxrr2vNY3aR18u9g:b-b06wo1) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
> ```objc
> namespace internal {
> // Default value of target_realtime_rate_.
> static constexpr double kDefaultTargetRealtimeRate = 0.0;
> ```

nit Sorry I didn't realize it before, but none of these should be `static`.  When they were class members we needed `static`, but here it means something different (and undesirable).
___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_kUsp7Z-RZIGrbj3H:-MI_kUsqA7lCod86eLIW:b-woac0x) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
> ```objc
> namespace internal {
> // Default value of target_realtime_rate_.
> static constexpr double kDefaultTargetRealtimeRate = 0.0;
> ```

nit It's possible that each of these internal kConstants are only ever used in a single place, at which point there are a bit pointless at global scope (I think?) and should probably just moved to their point-of-use in the cc file (either retaining their names, or even just inlined with no variable name).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 2 unresolved discussions (waiting on @dmcconachie-tri)

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 2 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_jxrr2vNY3aR18u9f:-MI_sO4l4czMWWsKYLfC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Sorry I didn't realize it before, but none of these should be `static`.  When they were class members we needed `static`, but here it means something different (and undesirable).
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 2 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_jxrr2vNY3aR18u9f:-MI_sfG_-Y5URPhpt_01:b-bw3f6) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
<details><summary><i>Previously, dmcconachie-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still trying to grapple with `constexpr`'s interaction with other keywords, but I _think_ the right thing here is to use `inline constexpr` which guarantees one definition. Are you more clear on that than I am, Jeremy?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 3 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.cc, line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_uE9tCsJwMUkrSp__:-MI_uE9tCsJwMUkrSp_a:bbkv6sx) ([raw file](https://github.com/robotlocomotion/drake/blob/73b6d5d007e474296f14a888f32180a028c8145b/systems/analysis/simulator.cc#L34)):*
> ```cpp
>   // Create a default integrator and initialize it.
>   DRAKE_DEMAND(
>       std::strcmp(internal::kDefaultIntegratorName, "runge_kutta3") == 0);
> ```

Why put this here as a runtime check rather than with the unit tests?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 3 unresolved discussions (waiting on @dmcconachie-tri and @sherm1)

___
*[systems/analysis/simulator.cc, line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_uE9tCsJwMUkrSp__:-MI_w917EjY9ZoPIHlr_:b-loolfj) ([raw file](https://github.com/robotlocomotion/drake/blob/73b6d5d007e474296f14a888f32180a028c8145b/systems/analysis/simulator.cc#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Why put this here as a runtime check rather than with the unit tests?
</blockquote></details>

It's a sanity check on the line immediately below it (so has superior locality to a unit test), and is cheap relative to the existing cost of creating a simulator.

**Review by sherm1 — COMMENTED** [review]
Pending question that might have gotten resolved accidentally: `constexpr` vs `inline constexpr` for the global constants. I _think_ the latter is the preferred incantation but I'm not certain.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150#-:-MIaFsbr46etkeBxQAhP:b-ph045n)* status: 2 unresolved discussions (waiting on @dmcconachie-tri)

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 2 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_jxrr2vNY3aR18u9f:-MIaWDPVAWw1hx2Z0Fgs:b-4ixcrf) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm still trying to grapple with `constexpr`'s interaction with other keywords, but I _think_ the right thing here is to use `inline constexpr` which guarantees one definition. Are you more clear on that than I am, Jeremy?
</blockquote></details>

According to [this](https://www.learncpp.com/cpp-tutorial/global-constants-and-inline-variables/) `inline constexpr` is the way to go. Alternatively, we could take Jeremy's second point and do something else entirely. For example in `simulator.cc`, we could include `simulator_config.h` and then use `SimulatorConfig{}.field` to access the defaults. This has the benefit of putting all the defaults in a single file, but I don't know how common this pattern is in Drake (or if it's frowned on in this context).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 2 unresolved discussions (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_jxrr2vNY3aR18u9f:-MIaXY9pAeLhLw41Y2HY:beqaann) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
<details><summary><i>Previously, dmcconachie-tri wrote…</i></summary><blockquote>

According to [this](https://www.learncpp.com/cpp-tutorial/global-constants-and-inline-variables/) `inline constexpr` is the way to go. Alternatively, we could take Jeremy's second point and do something else entirely. For example in `simulator.cc`, we could include `simulator_config.h` and then use `SimulatorConfig{}.field` to access the defaults. This has the benefit of putting all the defaults in a single file, but I don't know how common this pattern is in Drake (or if it's frowned on in this context).
</blockquote></details>

If they are only used by the cc file, then in any case its a defect to splat them into the header file in an internal namespace, so the constants' linker spelling here is moot.  At minimum, they should move to the cc file, at which point they are no longer inline.

Whether we replace them with a callout to the config.h or not, I don't mind one way or another.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 1 unresolved discussion (waiting on @dmcconachie-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MIZtZoU693Fa7Al2kPQ:-MIaZDnk576Jib3LrF1L:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For any Anzu programs that are impacted by these changes to defaults, we need to first land an Anzu PR that reaffirms the current (prior) defaults explicitly for those programs, before we merge this Drake PR that changes the defaults.
</blockquote></details>

Done.

---

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/analysis/simulator.h, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MI_kUsp7Z-RZIGrbj3H:-MIadq7S14dqDMi7xqyM:brue4ra) ([raw file](https://github.com/robotlocomotion/drake/blob/7612dde7445a4d88b534cb989ab4804690a606f2/systems/analysis/simulator.h#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It's possible that each of these internal kConstants are only ever used in a single place, at which point there are a bit pointless at global scope (I think?) and should probably just moved to their point-of-use in the cc file (either retaining their names, or even just inlined with no variable name).
</blockquote></details>

After removing the references from `gflags.cc`, a first pass indicates these are no longer used elsewhere. I'm in the process of confirming now.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @dmcconachie-tri)

___
*[systems/analysis/simulator_config.h, line 14 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MIaviFHEupCUWtXsM_k:-MIaviFHEupCUWtXsM_l:bgh8znc) ([raw file](https://github.com/robotlocomotion/drake/blob/b5ddca6f05b1720822ace9d59579dca7df35f0df/systems/analysis/simulator_config.h#L14)):*
> ```objc
> // drake::systems::internal::kDefaultIntegratorName is "runge_kutta3".
> // TODO(dale.mcconachie) Ensure that the default SimulatorConfig remains
> // congruent with a default initialized Simulator.
> ```

nit Oops, I just realized that the above comments are out of date now.

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[systems/analysis/simulator_config.h, line 14 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14150#-MIaviFHEupCUWtXsM_k:-MIawspF3RYmQa1rN1eH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5ddca6f05b1720822ace9d59579dca7df35f0df/systems/analysis/simulator_config.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Oops, I just realized that the above comments are out of date now.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Review by dmcconachie-tri — COMMENTED** [review]
@sherm1 Just want to make sure you're okay with the resolution of the location for the default values.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150#-:-MIazFhj6R5dX2KB-deX:b-ajbc5d)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Yes, I like it. Thanks for checking with me, Dale.

> Reviewed 4 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14150#-:-MIeSBJE2Age6Dy0DElW:b-vw8hz1)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Pull request merged**
