### PR TITLE
cassie_bench: Update malloc tracking

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This patch better models collection of malloc stats from multiple invocations
of each benchmark body. The google bench framework typically invokes the
benchmark case code multiple times even in normal operation, and uses the same
storage to capture user-defined metrics. The prior arrangement of the tracker
allowed later invocations' data to overwrite earlier. This version collects
data across all invocations.

The change doesn't matter much now, but it will make it easier to follow the
evolution of malloc counts across invocations with storage pool optimizations.

The effect of this patch on results is negligible, since the changes are
outside of the magic state loop.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14296)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@joemasterjohn for feature review (a bit of a random choice I admit, but this is just code reorg).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14296#-:-MLPjGOqEnv1z9tcYqZe:b-mtk6w4)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14296#-:-MLhjGjL7Z-9GiVe01AH:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
+@ericcousineau-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14296#-:-MLhjbSk3x5BVP-q1dHi:bvtjo57)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14296#-:-MLi5y8n926SC3G-kkgO:b-uwkowd)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

**Pull request merged**
