### PR TITLE
[math] Move MakeFromOneUnitVector from header to .cc

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Simply moves the long definition into the .cc file.

Since the initial submission, this has been extended to include a hotfix for the unit test of `MakeFromOneVector` in the mac -- the string matching was too specific.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15011)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
+@sammy-tri for platform review, please.

cc @jwnimmer-tri, @mitiguy 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15011#-:-MZxCMokD13pPQo-NCtD:bw0kzw7)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

(Note: the hotfix has been tested on macsim.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15011#-:-MZxiDVMB_DwKOxkHzJX:b8ciz1u)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sherm1 — COMMENTED** [review]
Thanks, @seancurtis-tri! Drive-by :lgtm: in case that's useful.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15011#-:-MZxoqHR04oCk7wgHUw0:b32jh52)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
TIL `[^]+`is like `.*` except it also matches newlines.

**Pull request merged**
