### PR TITLE
[C-IRIS] construct polytope search program.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Given the Lagrangian, find the C-space polytope {s | C*s<=d}.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497#-:-NKL8H_a0KiHoh7EhNcf:b4xbtza)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
I still need to review the tests, but wanted to get this out to you sooner. There is a CI issue and a couple of notes on naming things, but overall looks good.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497#-:-NKLP1IKEkfjbCfM23Fl:bbx320l)* status: 14 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 196 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLGcZm4t-UXJZgvRQ1:-NKLGcZm4t-UXJZgvRQ2:b-p4zobr) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6cd7b7aa85a6de51b4495f84aefafcac363908/geometry/optimization/dev/cspace_free_polytope.h#L196)):*
> ```objc
>     int plane_index;
>     Eigen::MatrixXd C;
>     Eigen::VectorXd d;
> ```

Why did we remove this?
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 383 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLHL74Ef2a4Chl2VXt:-NKLHL74Ef2a4Chl2VXu:b-6fobwq) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L383)):*
> ```objc
>   // @param polytope_lagrangians If this is not std::nullopt, then we set λ₁(y,
>   // s) to be polytope_lagrangians, and don't need to impose the constraint
>   // λ₁(y, s) is sos. Use this polytope_lagrangians when we search for C and d
> ```

nit: Adjust the wording of the last sentence to "We use this option when we search for C and d, keeping the polytope Lagrangians fixed."
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 385 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLHUPK2wMUrzP9CB7C:-NKLHUPK2wMUrzP9CB7D:bz3q9hf) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L385)):*
> ```objc
>   // λ₁(y, s) is sos. Use this polytope_lagrangians when we search for C and d
>   // and fix polytope_lagrangians to certain values.
>   UnitLengthLagrangians AddUnitLengthConstraint(
> ```

did you mean to drop the `[[nodiscard]]` here?
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLHuj81lfmfo9qg0wl:-NKLHuj81lfmfo9qg0wm:b-iwv1f6) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L427)):*
> ```objc
>    Constructs a program to search for the C-space polytope {s | C*s<=d,
>    s_lower<=s<=s_upper} such that this polytope is collision free.
>    This program takes C and d as decision variables, and search for the
> ```

nit: grammar "and search**es**
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 432 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIHreCiy431q-oyzb:-NKLIHreCiy431q-oyzc:bf844aw) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L432)):*
> ```objc
>    @param certificates_vec The return of
>    FindSeparationCertificateGivenPolytope().
>    @param gram_total_size The return of GetGramVarSizeForolytopeSearchProgram().
> ```

nit: typo in `GetGramVarSizeForolytopeSearchProgram()`
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 435 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIjl06LszaC4O4ut9:-NKLIjl06LszaC4O4utA:b-8k6i4m) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L435)):*
> ```objc
>    */
>   [[nodiscard]] std::unique_ptr<solvers::MathematicalProgram>
>   ConstructPolytopeSearchProgram(
> ```

If this doesn't fully construct the polytope search program, it may be better to name it `InitializePolytopeSearchProgram`
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 449 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIYtg78Qg6bD9T21R:-NKLIYtg78Qg6bD9T21S:b-7udjli) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L449)):*
> ```objc
>      Note that this function does NOT add the constraint δ>=0
>    */
>   void AddOuterPolytope(
> ```

I would change this name to `AddEllipsoidContainmentConstraint`
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 477 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLItiyD9S49SEDCNy4:-NKLItiyD9S49SEDCNy5:b-qauqok) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L477)):*
> ```objc
> 
>   /** Gets the H-polyhedron {s | C*s<=d, s_lower<=s<=s_upper}.
>    */
> ```

nit: you may not need this newline character.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 478 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLJ0DK6rxzPPrl8wRV:-NKLJ0DK6rxzPPrl8wRW:b-ryw8bt) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L478)):*
> ```objc
>   /** Gets the H-polyhedron {s | C*s<=d, s_lower<=s<=s_upper}.
>    */
>   HPolyhedron GetPolyhedron(const Eigen::MatrixXd& C,
> ```

I would rename this `GetPolyhedronWithJointLimits`
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1051 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLKvqs1Hq6iEpEFMxO:-NKLKvqt9qi-v6ofMwyT:b-wyc0sw) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1051)):*
> ```cpp
>   // plane_to_certificate_map maps the plane index to the index of certificate
>   // in certificates_vec. Namely
>   // certificates_vec[plane_to_certificate_map[i]]->plane_index = i
> ```

I think your bracket is in the wrong spot. This should read:
`certificates_vec[plane_to_certificate_map[i]->plane_index] = i`
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1077 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLLWWA-cmYvfH1-E3V:-NKLLWWA-cmYvfH1-E3W:b-xw24jf) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1077)):*
> ```cpp
>     MatrixX<symbolic::Variable> gram_mat(monomial_basis.rows(),
>                                          monomial_basis.rows());
>     for (int i = 0; i < static_cast<int>(rationals.size()); ++i) {
> ```

Can you add a comment here saying `// add lagrangians for joint limits`
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLNST03jRuE3qQT74e:-NKLNST03jRuE3qQT74f:b-6uwwu) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1154)):*
> ```cpp
>     A_lorentz1.setZero();
>     A_lorentz1(0, C.cols()) = 1;
>     A_lorentz1(0, C.cols() + 1) = -1;
> ```

Could you reorder these to:
```
A_lorentz1.block(0, 0, 1, C.cols()) = -s0.transpose();
A_lorentz1(0, C.cols()) = 1;
 A_lorentz1(0, C.cols() + 1) = -1;
```
that way it reads sequentially



_Code quote:_
```cpp
    A_lorentz1(0, C.cols()) = 1;
    A_lorentz1(0, C.cols() + 1) = -1;
    A_lorentz1.block(0, 0, 1, C.cols()) = -s0.transpose();
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLOOoa475yoTK9Z9tH:-NKLOOoa475yoTK9Z9tI:b-i2tw7b) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1186)):*
> ```cpp
>   VectorX<symbolic::Variable> vars(A.cols());
>   for (int i = 0; i < C.rows(); ++i) {
>     A.block(i * s_inner_pts.cols(), i * (s_inner_pts.rows() + 1),
> ```

BTW: is there no support for Kronecker Products in Eigen?



_Code quote:_
```cpp
  for (int i = 0; i < C.rows(); ++i) {
    A.block(i * s_inner_pts.cols(), i * (s_inner_pts.rows() + 1),
            s_inner_pts.cols(), s_inner_pts.rows()) = s_inner_pts.transpose();
    A.block(i * s_inner_pts.cols(),
            i * (s_inner_pts.rows() + 1) + s_inner_pts.rows(),
            s_inner_pts.cols(), 1) = -Eigen::VectorXd::Ones(s_inner_pts.cols());
    vars.segment((s_inner_pts.rows() + 1) * i, s_inner_pts.rows()) =
        C.row(i).transpose();
    vars((s_inner_pts.rows() + 1) * i + s_inner_pts.rows()) = d(i);
  }
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLOiAw0d7nLiVcx_eS:-NKLOiAw0d7nLiVcx_eT:bkyo868) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1232)):*
> ```cpp
>           (options.s_inner_pts->col(i).array() >= s_lower_.array()).all());
>     }
>     // Add the constraint C * s <= d
> ```

I would name the `s` here something else as `s` is an indeterminate of the program.

**Review by hongkai-dai — COMMENTED** [review]
Thanks a lot for the review!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497#-:-NKLaDd-9m3-O2CK89fo:bx4sb0j)* status: 11 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 196 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLGcZm4t-UXJZgvRQ1:-NKLUToa3k7Gmb9TFTDM:b-smpd6t) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6cd7b7aa85a6de51b4495f84aefafcac363908/geometry/optimization/dev/cspace_free_polytope.h#L196)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Why did we remove this?
</blockquote></details>

This struct is used in the function `FindSeparationCertificateGivenPolytope`, which already takes in `C` and `d` as inputs. We just directly copy `C` and `d` into this struct. This copying seems redundant to me, since the user already know `C` and `d` values as input arguments, not as an output.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 385 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLHUPK2wMUrzP9CB7C:-NKLY2oC0LCu4wpZGJX-:b26k60e) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L385)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

did you mean to drop the `[[nodiscard]]` here?
</blockquote></details>

Yes, this is intentional.

We call AddUnitLengthConstraint in two places, one is when we have `{s |C*s<=d, s_lower<=s<=s_upper}`, and we search for the Lagrangian multiplier. In this case we do want to return the Lagrangians as it will be used in the bilinear alternation. The other place is when we are given the Lagrangian multipliers and search for `C` and `d`. In this case we don't need to return the Lagrangian (returning it will incur unnecessary copying).
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 435 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIjl06LszaC4O4ut9:-NKLYkoG1pw6yID3PbQi:b-jo0ybq) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L435)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

If this doesn't fully construct the polytope search program, it may be better to name it `InitializePolytopeSearchProgram`
</blockquote></details>

By "this doesn't fully construct the polytope search program,", do you mean that it doesn't include every constraints/costs in the program? This function constructs the program, and add the constraint that the rationals need to be positive in the C-space polytope, and |a|<=1 in the C-space polytope. It then returns the constructed program.

What it doesn't include is the cost function to maximize the margin between the ellipsoid and the C-space polytope.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 449 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIYtg78Qg6bD9T21R:-NKLZd3N8-hpgxjEvihs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L449)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would change this name to `AddEllipsoidContainmentConstraint`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 478 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLJ0DK6rxzPPrl8wRV:-NKLZsYzDuNvmFZBrMZG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L478)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would rename this `GetPolyhedronWithJointLimits`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1051 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLKvqs1Hq6iEpEFMxO:-NKLZz5s2NHLK5lEsZOC:bv44d3z) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1051)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think your bracket is in the wrong spot. This should read:
`certificates_vec[plane_to_certificate_map[i]->plane_index] = i`
</blockquote></details>

I think the bracket is right.

plane_to_certificate_map maps a plane index to the index to certificates_vec. `certificates_vec[plane_to_certificate_map[i]]` is a `SeparationCertificateResult` object, which has a property `plane_index`.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1077 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLLWWA-cmYvfH1-E3V:-NKL_RgC5n92IQEotbvn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1077)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can you add a comment here saying `// add lagrangians for joint limits`
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLNST03jRuE3qQT74e:-NKL_p0bDCTu5Pv3CA2y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1154)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you reorder these to:
```
A_lorentz1.block(0, 0, 1, C.cols()) = -s0.transpose();
A_lorentz1(0, C.cols()) = 1;
 A_lorentz1(0, C.cols() + 1) = -1;
```
that way it reads sequentially
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLOOoa475yoTK9Z9tH:-NKL_wlF5jUwxb1vZg4-:b-t86hil) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1186)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

BTW: is there no support for Kronecker Products in Eigen?
</blockquote></details>

Eigen's Kronecker product is in "experimental" package https://eigen.tuxfamily.org/dox/unsupported/group__KroneckerProduct__Module.html, (see Eigen-unsupported at the top of the page). I think it is better not to use an experimental package.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLOiAw0d7nLiVcx_eS:-NKLaC9H3meiabLnT9oH:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.cc#L1232)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would name the `s` here something else as `s` is an indeterminate of the program.
</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 435 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIjl06LszaC4O4ut9:-NKM3I-k4rwKN6egWELW:b-bnjf1t) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L435)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

By "this doesn't fully construct the polytope search program,", do you mean that it doesn't include every constraints/costs in the program? This function constructs the program, and add the constraint that the rationals need to be positive in the C-space polytope, and |a|<=1 in the C-space polytope. It then returns the constructed program.

What it doesn't include is the cost function to maximize the margin between the ellipsoid and the C-space polytope.


</blockquote></details>

It doesn't include the cost, the ellipsoidal containment constraints, or the polytope containing the sample points constraints. In this sense, I don't believe it is accurate to say that this method constructs the polytope search program as it isn't quite a complete construction. This method initializes the program with the constraints that the new polytope still be collision-free. I feel that the name is somewhat of a misnomer given that it doesn't do the entire construction.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1103 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM4jji0rPWPmHosx6k:-NKM4jji0rPWPmHosx6l:bov8gu5) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1103)):*
> ```cpp
> 
>   Eigen::Matrix3d Q;
>   // Use arbitrary Q and s0
> ```

This `Q` isn't symmetric and has complex eigenvalues. I agree that it is likely too expensive to check that `Q` is PSD in `AddEllipsoidContainmentConstraint`, but perhaps we should still only test this method with `Q` PSD.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1109 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM5MHj6TRgGj2T6--r:-NKM5MHj6TRgGj2T6--s:b7saftx) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1109)):*
> ```cpp
>        2, -1, 3;
>   // clang-format on
>   const Eigen::Vector3d s0(1, 5, 10);
> ```

This s0 is outside the plant's joint limits. Are we okay with supporting this?
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1132 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM66z0EZJE48AvVMCk:-NKM66z0EZJE48AvVMCl:b-d0cl9d) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1132)):*
> ```cpp
>   Eigen::Matrix<double, 3, 4> s_inner_pts;
>   // clang-format off
>   s_inner_pts << 1, 2, 0, 3,
> ```

These s_inner_points are outside the plant's joint limits. Are we okay supporting this?
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1190 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM6ihTBvSnCuABIfs8:-NKM6ihTBvSnCuABIfs9:biowxx1) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1190)):*
> ```cpp
>   CspaceFreePolytope::FindSeparationCertificateGivenPolytopeOptions options;
>   options.verbose = true;
>   solvers::MosekSolver solver;
> ```

Do we need to add a flag to this test to check if the mosek solver is available?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 435 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKLIjl06LszaC4O4ut9:-NKMB0rA7xYLbZWespCv:bp8dovo) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b27915229243ebe3a9dae7c505b356240ac686/geometry/optimization/dev/cspace_free_polytope.h#L435)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

It doesn't include the cost, the ellipsoidal containment constraints, or the polytope containing the sample points constraints. In this sense, I don't believe it is accurate to say that this method constructs the polytope search program as it isn't quite a complete construction. This method initializes the program with the constraints that the new polytope still be collision-free. I feel that the name is somewhat of a misnomer given that it doesn't do the entire construction.
</blockquote></details>

Done. Makes sense.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1103 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM4jji0rPWPmHosx6k:-NKMB3z-50lAOSwIL6PD:b-c3w8ml) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1103)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This `Q` isn't symmetric and has complex eigenvalues. I agree that it is likely too expensive to check that `Q` is PSD in `AddEllipsoidContainmentConstraint`, but perhaps we should still only test this method with `Q` PSD.
</blockquote></details>

Our inner ellipsoid is `{ Qu + s0 | |u| <= 1}` which doesn't require `Q` to be symmetric or PSD.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1109 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM5MHj6TRgGj2T6--r:-NKMBRf915Po8Mzqu1ws:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1109)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This s0 is outside the plant's joint limits. Are we okay with supporting this?
</blockquote></details>

Done. Good call.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1132 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM66z0EZJE48AvVMCk:-NKMBXE9-3pgw-Bj5-Pr:b-4gscy3) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1132)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

These s_inner_points are outside the plant's joint limits. Are we okay supporting this?
</blockquote></details>

Done. Good call. I added a check that s_inner_points should be within the input limits.

The function AddCspaePolytopeContainment doesn't impose s_lower <= s <= s_upper, so even without projecting s_inner_points within the joint limits, the code still works. But as you pointed out, it is better to enforce this constraint.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1190 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM6ihTBvSnCuABIfs8:-NKMDIbQ05Lh6pjwcyK5:bavpba7) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1190)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Do we need to add a flag to this test to check if the mosek solver is available?
</blockquote></details>

It is checked three lines below.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18497#-:-NKOSD3vDvqgjn8suZo3:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 1103 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18497#-NKM4jji0rPWPmHosx6k:-NKOS-oC6PfU23zY5lth:b-4wqkaj) ([raw file](https://github.com/robotlocomotion/drake/blob/123b31a5c8ba3d36895c30333a64535a99b18ed7/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L1103)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Our inner ellipsoid is `{ Qu + s0 | |u| <= 1}` which doesn't require `Q` to be symmetric or PSD.
</blockquote></details>

You are correct sorry about that

**Pull request merged**
