### PR TITLE
jupyter: Add support for running / testing notebooks

### LINKED ISSUE #9650: bazel support for jupyter notebooks in drake
Can we have a version of jupyter_py.bzl (e.g. from anzu) for drake, please?

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #9650

Requires:
- [x] #11970
- [x] Provisioning

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11960)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Yes.

**Comment by hongkai-dai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11960)_ status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)
> 
> _[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/11960#-LnJoRJu81nXn0l2iGT8:-LnJoRJu81nXn0l2iGT9:b-tl5e2i) (no related file):_
> @hongkai-dai When you have a chance, can you try rebasing your MathematicalProgram PR on top of this one, and following the instructions to have your notebook be tested?

I rebased my PR on this PR, and the test passed. Thanks @EricCousineau-TRI !

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by EricCousineau-TRI** [comment]
BTW Seems like the CDash summary status is stale? (not a big deal, though)

**Comment by jamiesnape** [comment]
Processing is asynchronous (and CDash does not have the concept of an in-progress build).

**Comment by jamiesnape** [comment]
Should be. Run a Mac build, though.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Merging; not going to wait for debug / LSan.

**Pull request merged**
