### PR TITLE
Updates path to iiwa model in kuka_plan_runner.cc and kuka_ik_demo.cc.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5360)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sammy-tri and +@soonho-tri for both levels of review please. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5360#-:-Ke9krb3KpQd4MckSmIJ:b-xglx6l)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5360#-:-KeA0oQaI1qaX6bPB9wp:bnfp4nl)*

**Comment by sammy-tri** [comment]
-@soonho-tri so I can merge quickly  (sorry!)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5360#-:-KeA0t-U9HhYa8OQ8HnT:b912zbg)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5360#-:-KeA115_dvvj-XQmQ9Ea:bnfp4nl)*

**Pull request merged**
