### PR TITLE
Polishes documentation in multibody/collision/model.h.

### PR DESCRIPTION
**Pull request by liangfok**
For increased readability and understanding.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4887)

### CODE REVIEW

**Comment by liangfok** [comment]
+@seancurtis-tri for feature review please since you're looking into collision modeling.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KbH02XXCp55omJ54jzU:bgroo21)*

**Comment by SeanCurtis-TRI** [comment]
Several thoughts:

1) Generally, this may be considered as "polishing the rock".  This file will disappear when `GeometryWorld` is up and running.
2) While I recognize that this was largely just about updating the doxygen syntax (consistent flower boxing, removing `\brief`, and swapping `\` for `@`, I felt there was enough technical debt in some of the documentation that it *might* be worth dealing with both.  So, I've got numerous BTWs addressing those kinds of things.  It's worth noting, that my comments only cover the portion of the file encapsulated in these changes.  Even if all of my comments were unambiguously correct, and you implemented them, there would probably still be documentation inaccuracies in other portions of the file.  So, you can weigh that as you decide what you want to do with the BTWs.
3) Stylistically, there still seems to be inconsistencies in final punctuation and capitalization (I've highlighted some examples below, but made no effort to make an exhaustive list.)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/multibody/collision/model.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcY_5rMkK3ixCGG2uMA:-KcY_5rNJ_FAsvxOQiUe:b8ug7yt) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L77)):*
> ```objc
>    @param T_local_to_world the new value for the element-to-world
>    transform */
>   virtual bool updateElementWorldTransform(
> ```

BTW As long as we're playing with code documentation, we should probably correct this at the same time we're dealing with formatting and the like.  Specifically, the documentation for `T_local_to_world` provides little information about the semantics of this transform.

We are updating the *stored* transformation from element canonical space to world space (`X_WE`), where `X_WE = X_WL * X_LE`.  `X_LE` is the transform that maps the element to its parent body's space, referred to as "local". `X_WL`) maps the body/local space to the world.  The input parameter is this latter transform, `X_WL`, and reflects the current world pose of the parent body in a given context.

---

*[drake/multibody/collision/model.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYbRNOWsPusitJ3f8S:-KcYbRNOWsPusitJ3f8T:b7qtsp3) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L151)):*
> ```objc
>    model utilizing Bullet's collision detection code.
> 
>    @param points a matrix of points from which to computing distances
> ```

Two issues:
1) (optional) A "matrix" of points is kind of meaningless.  Mathematically, "matrix of points" literally means nothing.  From a software engineering perspective it is redundant because it just echoes the declared type.  Finally, this tells me nothing about the semantics of the data (and its relationship to the output.
2) (error) There's still a grammar problem.  :)  Can't use a verb clause using "to" and the gerund "computing".

That said, I'd recommend the following:

```
/** ...
 @param points an ordered list of N points represented column-wise by a 3XN Matrix.
 @param[out] closest_points a vector of N PointPair instances such that the ith instance reports the query result for the ith input point.
```

---

*[drake/multibody/collision/model.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYeq5WYVCtLCSaUE4H:-KcYeq5WYVCtLCSaUE4I:bqy2tkv) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L167)):*
> ```objc
>    approach, but may also include additional points that are "close" to being
>    in contact. This can be useful when simulating scenarios in which two
>    collision elements have more than one contact point.
> ```

BTW This could use a TODO.  The definition of "eligible" is lacking and the definition of "additional" points is incredibly hand wavy.  And that doesn't even address what "potential" means.  However, I don't have these answers ready to go, so I can't provide an alternative right now.  :)  So, I'd say a TODO.  This method documentation should *not* be copied verbatim into new incarnations even if the functionality is.  Feel free to put my  name on that TODO. 

---

*[drake/multibody/collision/model.h, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYfuruVZanFpRVFOvl:-KcYfuruVZanFpRVFOvm:b-jkx2mq) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L180)):*
> ```objc
>   in the model.
> 
>   In other words, this method tests if a sphere of radius `collision_threshold`
> ```

BTW I have two somewhat contradictory thoughts on this:

1) I'd suggest a rephrasing of this paragraph:

The index `i` is included in the returned vector of indices iff a sphere of radius `collision_threshold`, located at `input_points[i]` collides with any collision element in the model.

2) This *feels* like an implementation detail.  And if it is merely intended to be a clarifying analogy, I don't think the concept of "within a specified distance" is sufficiently confusing to require one.  As such, it doesn't belong in the header documentation.

The same thought applies to the next method.

---

*[drake/multibody/collision/model.h, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYgR5stGRhA-RDkiuP:-KcYgR5tJt1INjjGZTQt:bq7rbbm) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L195)):*
> ```objc
>   collide with the model within the specified threshold.
> 
>   @see drake/matlab/systems/plants/test/collidingPointsTest.m for a MATLAB
> ```

BTW Probably need a TODO on this to replace the matlab test with a C++ test.

---

*[drake/multibody/collision/model.h, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYgmNS1UHKTurrfkIR:-KcYgmNS1UHKTurrfkIS:b-wx58j8) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L202)):*
> ```objc
> 
>   /** Tests if any of the points supplied in `input_points` collides with any
>   part of the model within a given `collision_threshold`.
> ```

BTW I'd suggest that this sentence should parallel the previous method's documentation: e.g.:

Given a vector of points in the world coordinate frame, reports if *any* of those points lie within a specified distance of any collision geometry in the model.

I feel this allows for better comparison and contrast with the previous method.

---

*[drake/multibody/collision/model.h, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYhuc-Mul12-jzxDSk:-KcYhuc-Mul12-jzxDSl:b5uer9k) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L213)):*
> ```objc
>   model.
> 
>   @param collision_threshold The radius of a control sphere around each point
> ```

BTW We're some what erratic on whether we capitalize the first word following the the parameter name.  My preference is some white space *and* capitalization, but that isn't the style that is generally used in this file.

---

*[drake/multibody/collision/model.h, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYkDsGz0cNCXsymInR:-KcYkDsGz0cNCXsymInS:b-5zp1dv) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L222)):*
> ```objc
>       double collision_threshold) = 0;
> 
>   /** Performs raycast collision detection (like a LIDAR / laser range finder).
> ```

BTW My pet peeve is calling "raycasting" "collision detection".  Ray casting is inherently an *intersection* test.  (Else why cast the ray?)  Where as collision detection is something else.  But this small rant is outside the scope of this PR.  Thank you for your patient forbearance.

---

*[drake/multibody/collision/model.h, line 226 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYjKd_Ogs8n8bQi_kX:-KcYjKd_Ogs8n8bQi_kY:bcuy1kz) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L226)):*
> ```objc
>    @param origin a 3 x N matrix where each column specifies the position of a
>    ray's origin in the world coordinate frame.  If `origin` has dimensions of
>    3 x 1, the same origin is used for all raycasts
> ```

BTW "...used for all rays."

Also, this method has almost no terminal punctuation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KcYb1zov77sZbw_qSws:b8euog4)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-cpplint-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please

**Comment by liangfok** [comment]
@seancurtis-tri, thanks for the review. I've addressed your comments. PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/multibody/collision/model.h, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcY_5rMkK3ixCGG2uMA:-KccWdbU88tpStg6IOX7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L77)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As long as we're playing with code documentation, we should probably correct this at the same time we're dealing with formatting and the like.  Specifically, the documentation for `T_local_to_world` provides little information about the semantics of this transform.

We are updating the *stored* transformation from element canonical space to world space (`X_WE`), where `X_WE = X_WL * X_LE`.  `X_LE` is the transform that maps the element to its parent body's space, referred to as "local". `X_WL`) maps the body/local space to the world.  The input parameter is this latter transform, `X_WL`, and reflects the current world pose of the parent body in a given context.


</blockquote></details>

Done.

---

*[drake/multibody/collision/model.h, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYbRNOWsPusitJ3f8S:-KccXbpCPASLaEOgV58O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L151)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Two issues:
1) (optional) A "matrix" of points is kind of meaningless.  Mathematically, "matrix of points" literally means nothing.  From a software engineering perspective it is redundant because it just echoes the declared type.  Finally, this tells me nothing about the semantics of the data (and its relationship to the output.
2) (error) There's still a grammar problem.  :)  Can't use a verb clause using "to" and the gerund "computing".

That said, I'd recommend the following:

```
/** ...
 @param points an ordered list of N points represented column-wise by a 3XN Matrix.
 @param[out] closest_points a vector of N PointPair instances such that the ith instance reports the query result for the ith input point.
```
</blockquote></details>

Done.

---

*[drake/multibody/collision/model.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYeq5WYVCtLCSaUE4H:-KcdvBLiiBKWjFfSjqZE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L167)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This could use a TODO.  The definition of "eligible" is lacking and the definition of "additional" points is incredibly hand wavy.  And that doesn't even address what "potential" means.  However, I don't have these answers ready to go, so I can't provide an alternative right now.  :)  So, I'd say a TODO.  This method documentation should *not* be copied verbatim into new incarnations even if the functionality is.  Feel free to put my  name on that TODO. 
</blockquote></details>

Done.

---

*[drake/multibody/collision/model.h, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYfuruVZanFpRVFOvl:-KcdwSWRL0NVRcLb0Eb1:b-esk9d0) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L180)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I have two somewhat contradictory thoughts on this:

1) I'd suggest a rephrasing of this paragraph:

The index `i` is included in the returned vector of indices iff a sphere of radius `collision_threshold`, located at `input_points[i]` collides with any collision element in the model.

2) This *feels* like an implementation detail.  And if it is merely intended to be a clarifying analogy, I don't think the concept of "within a specified distance" is sufficiently confusing to require one.  As such, it doesn't belong in the header documentation.

The same thought applies to the next method.
</blockquote></details>

Done. I also replaced "within a specified distance" with "within the provided `collision_threshold` distance".

---

*[drake/multibody/collision/model.h, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYgR5stGRhA-RDkiuP:-KcdvpqeGfVNo_tv-ijh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L195)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Probably need a TODO on this to replace the matlab test with a C++ test.
</blockquote></details>

Done.

---

*[drake/multibody/collision/model.h, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYgmNS1UHKTurrfkIR:-Kcdw8gQXiIvziETSMJS:b-ho5wpv) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L202)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd suggest that this sentence should parallel the previous method's documentation: e.g.:

Given a vector of points in the world coordinate frame, reports if *any* of those points lie within a specified distance of any collision geometry in the model.

I feel this allows for better comparison and contrast with the previous method.
</blockquote></details>

Agreed. Done.

---

*[drake/multibody/collision/model.h, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYhuc-Mul12-jzxDSk:-KcdxCX-dcvZi96mXE7M:b-4yscgu) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L213)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW We're some what erratic on whether we capitalize the first word following the the parameter name.  My preference is some white space *and* capitalization, but that isn't the style that is generally used in this file.
</blockquote></details>

I updated the documentation in this class to consistently use full sentences for parameter descriptions.

---

*[drake/multibody/collision/model.h, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYkDsGz0cNCXsymInR:-KcdypOne3uDSsqt8beD:b-j54kkf) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L222)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW My pet peeve is calling "raycasting" "collision detection".  Ray casting is inherently an *intersection* test.  (Else why cast the ray?)  Where as collision detection is something else.  But this small rant is outside the scope of this PR.  Thank you for your patient forbearance.
</blockquote></details>

Done. I went ahead and switch to "intersection​ test".

---

*[drake/multibody/collision/model.h, line 226 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcYjKd_Ogs8n8bQi_kX:-Kcdz1POOjJRK_D7e7DA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69c01da9ff61d65d9547dd9c59bb375f84652bed/drake/multibody/collision/model.h#L226)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "...used for all rays."

Also, this method has almost no terminal punctuation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KcdzC52tN49D42N67dY:b3yvacv)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-Kcs5q2C-tgLGHRQlWZ0:bmxilld)*

**Comment by liangfok** [comment]
Thanks. +@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KcsAItv8mT0VRiXJgC4:b8z1tcd)*

**Comment by sherm1** [comment]
Platform: :lgtm:, one minor BTW.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/collision/model.h, line 183 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcsJDm4Ku77tx4FuSAa:-KcsJDm4Ku77tx4FuSAb:b-4131ad) ([raw file](https://github.com/robotlocomotion/drake/blob/c821fcaffcd52214c89ec7f97f841a76bf9670af/drake/multibody/collision/model.h#L183)):*
> ```objc
> 
>    @return A vector of PointPair objects containing the potential collision
>    points **/
> ```

BTW, periods missing from above sentences.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KcsJfR3K5jxnEztgOo3:bcdgtak)*

**Comment by liangfok** [comment]
Thanks. Now waiting on CI.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/collision/model.h, line 183 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-KcsJDm4Ku77tx4FuSAa:-KcsKwgAo8QgACKfOTWL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c821fcaffcd52214c89ec7f97f841a76bf9670af/drake/multibody/collision/model.h#L183)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, periods missing from above sentences.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KcsKydiMbyF2QR1xyfT:b-mta4n0)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4887#-:-KcszXiv1uzTeMJC-nxP:b-yxxxc1)*

**Pull request merged**
