### PR TITLE
python: Document experimental Python3 support for Bionic

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves next-to-last item in #8352

This is the initial proposal. Putting WIP to indicate that this is not yet an agreed-upon interface.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10257)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
___
*[doc/developers.rst, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10257#-LTwUBdkC_dyR9F7qc3m:-LTxOat323KClnxux1wV:bhmrfgt) ([raw file](https://github.com/robotlocomotion/drake/blob/c473554644754e8a56db7ca26596fd26dc0ad54d/doc/developers.rst#L96)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

don't run that executable.
</blockquote></details>

Er, just to check, which executable?

**Comment by EricCousineau-TRI** [comment]
___
*[setup/user_configure, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10257#-LTy6Hv-EQRiYqn9Egq_:-LTy7b-O-li5Xi5rztTL:b-s3ng4h) ([raw file](https://github.com/robotlocomotion/drake/blob/46d785f8ae5a4cc0d0b0771e04ac48e56977aa41/setup/user_configure#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Not going to work on CI. We should not be writing user.bazelrc anyway. It is for users to manage.
</blockquote></details>

It should? Can you also review the requirements in this file?

**Comment by EricCousineau-TRI** [comment]
___
*[setup/user_configure, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10257#-LTy6Hv-EQRiYqn9Egq_:-LTy7gex39RJo79e52VL:broci5k) ([raw file](https://github.com/robotlocomotion/drake/blob/46d785f8ae5a4cc0d0b0771e04ac48e56977aa41/setup/user_configure#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It should? Can you also review the requirements in this file?
</blockquote></details>

Sorry, can I ask what exactly in CI will fail?

**Comment by EricCousineau-TRI** [comment]
___
*[setup/user_configure, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10257#-LTy6Hv-EQRiYqn9Egq_:-LTyHbWH9q1xdmaM45T4:bs66eie) ([raw file](https://github.com/robotlocomotion/drake/blob/46d785f8ae5a4cc0d0b0771e04ac48e56977aa41/setup/user_configure#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> And requiring that Mac run some form of this script is much more preferable than our current hijacking of ~/.bazelrc.

We did not have much choice when that was implemented. We have `try-import` now.

Maybe @jwnimmer-tri would like to update this review with his rationale rather than we have a stealth second review contradicting the assigned reviewer.

</blockquote></details>

Aye, will wait for Jeremy to chime in.

**Comment by jamiesnape** [comment]
So the failure is in python_bin_test on Mac?

**Comment by EricCousineau-TRI** [comment]
> So the failure is in python_bin_test on Mac?

Sorry, the failure on Mac CI is conjecture on my part.
Rather, my question is, if I've stripped out the update to `~/.bazelrc` in `mac/.../install_prereqs_user_environment`, will `drake-ci` fail?
Looking at it, perhaps not?
https://github.com/RobotLocomotion/drake-ci/blob/91372728baa068977e82a406b0c7032d3bc9824f/driver/configurations/cmake.cmake#L105-L106

**Comment by EricCousineau-TRI** [comment]
That being said:
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/python/repository.bzl, line 87 at r10](https://reviewable.io/reviews/robotlocomotion/drake/10257#-LU2WwoaC__sj5TCMSN5:-LU2_F110tN9jMjGLG2g:b-c43fpf) ([raw file](https://github.com/robotlocomotion/drake/blob/d8430f76514358bca122685655f9e17890535eec/tools/workspace/python/repository.bzl#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure what this line is doing.  Isn't `python_path` already a str?
</blockquote></details>

OK Nay, it's a `path` object that has to be converted to be used as a `str`.

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/python/repository.bzl, line 75 at r10](https://reviewable.io/reviews/robotlocomotion/drake/10257#-LU3PHBpDcU7ygMI_O1t:-LU6MuTa42OUUsj9poXi:b-sjexlp) ([raw file](https://github.com/robotlocomotion/drake/blob/d8430f76514358bca122685655f9e17890535eec/tools/workspace/python/repository.bzl#L75)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm just thinking of edge cases, but Jeremy is right in that the existing configurations will not have an issue, so it's fair to say that we just move forward.
I'll draft up a separate PR to make a build-time variant of `python_bin_test`.

(The `fail` cases will only trigger if (a) the user supplies a `DRAKE_PYTHON_BIN_PATH` that's not absolute or (b) it cannot find a neighboring `python-config` binary. I believe neither of these would be triggered if `/usr/bin/python` snuck in there on Mac.)
</blockquote></details>

Sorry - meant to say y'all are both right. (Jamie pointed out much the samem.)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Unprovisioned Ubuntu build passed:
https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-clang-bazel-experimental-release/5/
https://drake-jenkins.csail.mit.edu/job/linux-xenial-unprovisioned-clang-bazel-experimental-release/6/

Gonna push updates now.

**Comment by EricCousineau-TRI** [comment]
Added 2 bullet points in #8352 to capture shambhala and build time shindigs.

**Pull request merged**
