### PR TITLE
Add SOURCE_SUBDIR support to externals

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Import the latest ExternalProject from CMake upstream, which [adds `SOURCE_SUBDIR` support to `ExternalProject.cmake`](https://gitlab.kitware.com/cmake/cmake/merge_requests/63). Use this to build director as a CMake external and to get rid of the ugly `BUILD_COMMAND_DIR` hack.

This also establishes the pattern for importing other modules, as we may want to do in the future.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3174)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Some of the new files say "`(To distribute this file outside of CMake, substitute the full License text for the above reference.)`"; please be sure to do that.

**Comment by mwoehlke-kitware** [comment]
> Some of the new files say "`(To distribute this file outside of CMake, substitute the full License text for the above reference.)`"; please be sure to do that.

Bah, too much work... dd79caf :smile:.

**Comment by mwoehlke-kitware** [comment]
FYI: @soonho-tri is possibly waiting on this, and also the next round of "superbuild refactor" (the options refactor) would like for it to land first (in order to leverage the 'set up our module paths' stuff).

**Comment by soonho-tri** [comment]
@mwoehlke-kitware, thank you!

**Comment by bradking** [comment]
The approach :lgtm:, though some CI builds failed.

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-:-KPP9bMdLz8BvDVRt4tP:byvt0qt)*

**Comment by mwoehlke-kitware** [comment]
> some CI builds failed

Arf, director doesn't have an `install` target... the `Makefile` didn't care, but building it as a CMake project does... easily fixed though...

**Comment by david-german-tri** [comment]
Approach looks reasonable to me.  Will test locally once CI passes.

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 226 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-KPPEcTbGswxlFGZz_Qz:-KPPEcTbGswxlFGZz_R-:b-qeqm4r) ([raw file](https://github.com/robotlocomotion/drake/blob/ca83edb70a079329b9c39049e8235aa6d8a9a452/CMakeLists.txt#L226)):*
> ```CMake
>   SOURCE_SUBDIR distro/superbuild
>   CMAKE_ARGS
>     -DUSE_LCM=ON # TODO: predicate on whether we have LCM enabled?
> ```

Where did these come from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-:-KPPGAea3-muAQdmYvRQ:bhyk0k8)*

**Comment by mwoehlke-kitware** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 226 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-KPPEcTbGswxlFGZz_Qz:-KPPIAo1lZgBgrUBPpyn:b-euwse8) ([raw file](https://github.com/robotlocomotion/drake/blob/ca83edb70a079329b9c39049e8235aa6d8a9a452/CMakeLists.txt#L226)):*
> Where did these come from?

https://github.com/RobotLocomotion/director/blob/master/distro/pods/drake-distro/Makefile#L38-L41

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3174)*

**Comment by mwoehlke-kitware** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 226 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-KPPEcTbGswxlFGZz_Qz:-KPPJ0-cymWOVkd64HrM:bxqq5dg) ([raw file](https://github.com/robotlocomotion/drake/blob/ca83edb70a079329b9c39049e8235aa6d8a9a452/CMakeLists.txt#L226)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> > Where did these come from?
> 
> https://github.com/RobotLocomotion/director/blob/master/distro/pods/drake-distro/Makefile#L38-L41
</details>
...and I added the TODO because IIRC trying to build director without LCM ends badly, and we want to support building without LCM. Being able to change these may help with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3174)*

**Comment by david-german-tri** [comment]
:lgtm:.  I assume we can delete the `cmake/modules/3.7` stuff once we up the required version to 3.7?

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-:-KPT0Wo8u1XP7G6Y8Dzp:b-78d10k)*

**Comment by mwoehlke-kitware** [comment]
> I assume we can delete the `cmake/modules/3.7` stuff once we up the required version to 3.7?

Yes.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3174#-:-KPT16yORKWFstG_oXxH:b-e43037)*

**Pull request merged**
