### PR TITLE
[visualization] Add missing unit test for publish period config

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #19590.

+@DamrongGuoy for feature review, please.
+@EricCousineau-TRI for platform review per schedule, please.

@trowell-tri FYI

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy

___
*[`visualization/test/visualization_config_functions_test.cc` line 291 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-NXzdEvdB0LHI6tRSJ9z:-NXzdEvdB0LHI6tRSJA-:btshmea) ([raw file](https://github.com/RobotLocomotion/drake/blob/dc174456cd568de096baa81d0d5ac72574dfaea8/visualization/test/visualization_config_functions_test.cc#L291)):*
> ```cpp
>   auto context = diagram->CreateDefaultContext();
>   context->SetTime(0.001);
>   std::unique_ptr<CompositeEventCollection<double>> events =
> ```

Working

Oops.  I got confused by the framework.  I think there's a shorter way to check this.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606)* status: LGTM missing from assignee DamrongGuoy

___
*[`visualization/test/visualization_config_functions_test.cc` line 291 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-NXzdEvdB0LHI6tRSJ9z:-NXzduZT7r-_4vlAeQiP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/dc174456cd568de096baa81d0d5ac72574dfaea8/visualization/test/visualization_config_functions_test.cc#L291)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Oops.  I got confused by the framework.  I think there's a shorter way to check this.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606)* status: LGTM missing from assignee DamrongGuoy

___
*[`visualization/test/visualization_config_functions_test.cc` line 291 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-NXzdEvdB0LHI6tRSJ9z:-NXzdyhcB_9tWK2vIgrz:b-o41d5q) ([raw file](https://github.com/RobotLocomotion/drake/blob/dc174456cd568de096baa81d0d5ac72574dfaea8/visualization/test/visualization_config_functions_test.cc#L291)):*
> Despite the name [CalcNextUpdateTime], the returned events includes both state-updating events and publish events.

-- https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html#a164afe3c1db737b93696b8808bb2c942

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606)* status: LGTM missing from assignee DamrongGuoy

**Review by trowell-tri — COMMENTED** [review]
Yeah, same, you'd think after working on tests for so long I would have thought of that. Also :lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-:-NXzlYUr5BWk5j5F0JPe:bj7yi0c)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy

___
*[`visualization/test/visualization_config_functions_test.cc` line 275 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-NXzlleQD0goF6KXWWBy:-NXzlleQD0goF6KXWWBz:b-xw0wkj) ([raw file](https://github.com/RobotLocomotion/drake/blob/526aef5f70b12881413226f5775c6f2ba16d7334/visualization/test/visualization_config_functions_test.cc#L275)):*
> ```cpp
> GTEST_TEST(VisualizationConfigFunctionsTest, UpdatePeriod) {
>   VisualizationConfig config;
>   // Set a gratitously long time between publish events.
> ```

gratuitously



_Code quote:_
```cpp
gratitously
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> Dismissed @trowell-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606)* status: LGTM missing from assignee DamrongGuoy

___
*[`visualization/test/visualization_config_functions_test.cc` line 275 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-NXzlleQD0goF6KXWWBy:-NXzsDOb5EaQRTehuqrf:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/526aef5f70b12881413226f5775c6f2ba16d7334/visualization/test/visualization_config_functions_test.cc#L275)):*
<details><summary><i>Previously, trowell-tri (Todd Rowell) wrote…</i></summary><blockquote>

gratuitously
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

Thanks for showing me the system framework (context->SetTime(); diagram->AllocateCompositeEventCollection();  diagram->CalcNextUpdateTime();  events->HasPublishEvents()).

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19606#-:-NY-2tmfE3M20O3ukJ19:b-artx5n)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),DamrongGuoy

**Pull request merged**
