### PR TITLE
Add Functions for adding DD and SDD dual cone constraints

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Feel free to pass off if you think someone else is better.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-:-Ng0-Gw35rXcsY7tgVPp:bvpek9j)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
FYI: @RussTedrake towards MakeDiagonallyDominantOuterApproximation and MakeScaledDiagonallyDominantOuterApproximation for a PSD program

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-:-Ng00QKo99rBspNVng4s:b-pd8yjm)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
FYI: @Bernhardpg

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-:-Ng01c-s1ZZRu-x2DLqA:bgyvf9m)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2564 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-Ng6MJA00ZqbtplbT2Jk:-Ng6MJA00ZqbtplbT2Jl:b-xksasi) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d1791591754a09986c1e7a8e0ab797550fe75c7/solvers/mathematical_program.h#L2564)):*
> ```objc
>    * Adds the constraint that a symmetric matrix is in the dual cone of the
>    * diagonally dominant matrices which is denoted DD*. The set DD* is an outer
>    * approximation to the PSD cone since DD ⊆ PSD = PSD* ⊆ DD*
> ```

Maybe we can be more explicit here?

Since DD ⊆ PSD, we know that PSD* ⊆ DD*. Also because a PSD cone is self-dual, we know that PSD* ⊆ DD*
___
*[`solvers/mathematical_program.h` line 2676 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR2Ydo5wmqAS_aNEfU:-NgR2Ydo5wmqAS_aNEfV:b-hetsl0) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2676)):*
> ```objc
>    * where Vᵢⱼ is an n x 2 matrix where each column contains exactly one
>    * non-zero element equal to 1. There are n choose 2 of these matrices
>    * producing unique products, namely those such that i ≥ j. This can be
> ```

Maybe be more specific here to explain why we only need to consider i >= j
```
Vᵢⱼ is the n x 2 matrix such that Vᵢⱼ(i, 0) = 1, V(j, 1) = 1, namely Vᵢⱼ = [eᵢ eⱼ]. We also know that 

VᵢⱼᵀXVᵢⱼ = ⌈ Xᵢᵢ Xᵢⱼ⌉
           ⌊ Xⱼᵢ Xⱼⱼ⌋

If we flip the order of i, j and consider 
VⱼᵢᵀXVⱼᵢ =⌈ Xⱼⱼ Xⱼᵢ ⌉
          ⌊ Xᵢⱼ Xᵢᵢ ⌋
It is obvious that VᵢⱼᵀXVᵢⱼ is psd iff VⱼᵢᵀXVⱼᵢ is psd, as VᵢⱼᵀXVᵢⱼ is similar to VⱼᵢᵀXVⱼᵢ
```
___
*[`solvers/mathematical_program.h` line 2677 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR4tfq9ywPgKyf6nwu:-NgR4tfq9ywPgKyf6nwv:b7xlp7a) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2677)):*
> ```objc
>    * non-zero element equal to 1. There are n choose 2 of these matrices
>    * producing unique products, namely those such that i ≥ j. This can be
>    * encoded using 1/2 * n * (n-3) RotateLorentzCone constraints which we return
> ```

Why it is not 1/2 * n * (n-1)? I would think that for each i > j we need a rotated Lorentz cone constraint?

Also mention that when i = j, then we don't need to impose RotatedLorentzConstraint, but instead just the linear constraint Xᵢᵢ >= 0. 
___
*[`solvers/mathematical_program.cc` line 1178 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR5Rkg23qcKHEmoXyb:-NgR5Rkg23qcKHEmoXyc:b-dq9dum) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.cc#L1178)):*
> ```cpp
> 
> std::tuple<Eigen::MatrixXd, Eigen::VectorXd, Eigen::VectorXd>
> ConstructPositiveDiagonallyDominantDualConeConstraintMatricesForN(const int n) {
> ```

Document this function? What are the output?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2564 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-Ng6MJA00ZqbtplbT2Jk:-NgREUfR1B0WmDZunQgD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9d1791591754a09986c1e7a8e0ab797550fe75c7/solvers/mathematical_program.h#L2564)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe we can be more explicit here?

Since DD ⊆ PSD, we know that PSD* ⊆ DD*. Also because a PSD cone is self-dual, we know that PSD* ⊆ DD*
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 2676 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR2Ydo5wmqAS_aNEfU:-NgRETjdAl3W0dGcnaP4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2676)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe be more specific here to explain why we only need to consider i >= j
```
Vᵢⱼ is the n x 2 matrix such that Vᵢⱼ(i, 0) = 1, V(j, 1) = 1, namely Vᵢⱼ = [eᵢ eⱼ]. We also know that 

VᵢⱼᵀXVᵢⱼ = ⌈ Xᵢᵢ Xᵢⱼ⌉
           ⌊ Xⱼᵢ Xⱼⱼ⌋

If we flip the order of i, j and consider 
VⱼᵢᵀXVⱼᵢ =⌈ Xⱼⱼ Xⱼᵢ ⌉
          ⌊ Xᵢⱼ Xᵢᵢ ⌋
It is obvious that VᵢⱼᵀXVᵢⱼ is psd iff VⱼᵢᵀXVⱼᵢ is psd, as VᵢⱼᵀXVᵢⱼ is similar to VⱼᵢᵀXVⱼᵢ
```
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 2677 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR4tfq9ywPgKyf6nwu:-NgRESwc6U9hQf8_569z:b7wic69) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2677)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why it is not 1/2 * n * (n-1)? I would think that for each i > j we need a rotated Lorentz cone constraint?

Also mention that when i = j, then we don't need to impose RotatedLorentzConstraint, but instead just the linear constraint Xᵢᵢ >= 0.
</blockquote></details>

I added more documentation explaining why we only need i > j
___
*[`solvers/mathematical_program.cc` line 1178 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR5Rkg23qcKHEmoXyb:-NgRF0qr8UKMQ0sRQNwP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.cc#L1178)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Document this function? What are the output?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2677 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR4tfq9ywPgKyf6nwu:-NgRcT-ICYvlirp-3q-o:b-sakn5u) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2677)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I added more documentation explaining why we only need i > j
</blockquote></details>

My question is actually more about why it is not 1/2 * n * (n-1) rotated Lorentz cone constraint. If we choose the pair (i, j) with i > j, I think there should be 1/2 * n * (n-1) pairs?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2677 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR4tfq9ywPgKyf6nwu:-NgTtGeh2RptQD7bJa2A:b-2h35qa) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2677)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

My question is actually more about why it is not 1/2 * n * (n-1) rotated Lorentz cone constraint. If we choose the pair (i, j) with i > j, I think there should be 1/2 * n * (n-1) pairs?
</blockquote></details>

Yes you are correct, I subtracted the number of diagonal elements twice. There are indeed n choose 2 = 1/2 * n * (n-1) constraints

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`solvers/mathematical_program.h` line 2677 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgR4tfq9ywPgKyf6nwu:-NgVOkgwCq3OZn-u8nw4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/87447ba2c8ed08a1165c14dc72dfcc5591c9da8d/solvers/mathematical_program.h#L2677)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not changed yet? I still see 1/2 * n * (n-3)
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 2690 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-NgUQK76EyXiTMA8z77J:-NgVPJuYB8izcHmjlsmc:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e491930a39b11e049e8f6d841e22deca1662d3d0/solvers/mathematical_program.h#L2690)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe also mention that this SDD dual constraint is equivalent of relaxing `X is psd` to `all 2 x 2 principal minors of X are psd`.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sammy-tri for platform review please, thanks!

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-:-NgZzQDr2CQF6XbZ1UNb:bptxe99)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with a minor formatting nit

+(release notes: feature) 

> Reviewed 1 of 7 files at r1, 1 of 3 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-:-Ng_cWUBDFfXxHgGTgtL:bnwwotr)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2562 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-Ng__wmf-lpilLA70wJO:-Ng__wmf-lpilLA70wJP:bz8lpaf) ([raw file](https://github.com/RobotLocomotion/drake/blob/1282a89037bef10c6e8edaf45b594122ec34cb21/solvers/mathematical_program.h#L2562)):*
> ```objc
>   /**
>    * @anchor add_dd_dual
>    * @name diagonally dominant dual cone constraint
> ```

nit: for consistency with the rest of the documentation in this file, please capitalize the first letter of the first word of the section names

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`solvers/mathematical_program.h` line 2562 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-Ng__wmf-lpilLA70wJO:-Ng_vOvhCt9HTth4rejc:bjpgwm6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1282a89037bef10c6e8edaf45b594122ec34cb21/solvers/mathematical_program.h#L2562)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: for consistency with the rest of the documentation in this file, please capitalize the first letter of the first word of the section names
</blockquote></details>

Sorry I am not sure I understand

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2562 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-Ng__wmf-lpilLA70wJO:-Ng_zZO99iiEoYbFHMNH:bl6zqot) ([raw file](https://github.com/RobotLocomotion/drake/blob/1282a89037bef10c6e8edaf45b594122ec34cb21/solvers/mathematical_program.h#L2562)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Sorry I am not sure I understand
</blockquote></details>

The documentation looks odd.  There's already an unusual entry from "scaled diagonally dominant matrix constraint" which is lower case when the surrounding sections are capitalized.   Here's a screenshot of various sections of the documentation from https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mathematical_program.html

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20317#-:-NgaOpxfADwUvOc8BMrX:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai

**Pull request merged**
