### PR TITLE
Fix Wunused-parameter in Valkyrie

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6031)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.  This repairs unused parameters using the guidelines in [drake::unused's documentation](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0).

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6031#-:-KjLejV3_b2S4HiaL5ui:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6031#-:-KjOIzXrNzgbE8imZosd:bnfp4nl)*

**Pull request merged**
