### PR TITLE
Pr/new plan eval generic plan

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
adds an interface for plan eval.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5626)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. thanks

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-KgF6aM8BVwfSbOjT-1u:b-54729d)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by naveenoid** [comment]
Can we f2f on this PR? I need to understand better how it is to be used..Im mostly ok with the PR itself though. 

---

Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgUOlcZ2iUowgrGD6V0:-KgUOlc_OmNM-EFopHRK:b-7i9b5i) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L30)):*
> ```objc
>  * until the hand touches something", which requires little computation but
>  * high rate feedback.
>  * Here is a concrete example, an . Suppose the robot is a position and
> ```

nit: Typo "an"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-KgUc5qbejVxGSISG2uU:bfx4gm6)*

**Comment by naveenoid** [comment]
Thanks for the patience! First round completed. PTAL.

---

Reviewed 2 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeMK0IWgG_smqnkMzW:-KgeMK0Jr4F-HuxRO0DO:b-7sist5) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.cc#L55)):*
> ```cpp
>   // Runs derived class' plan.
>   ExecutePlanGenericPlanDerived(robot_status, paramset, alias_groups);
> }
> ```

Is there a need to retain a base class version of HandlePlanMessage of ExecutePlan when they dont really do anything common for all derived classes? Why not make this pure virtual to begin with?

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgUqJcwZ8MCVZYEam11:-KgUqJcwZ8MCVZYEam12:b-myneph) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L48)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(GenericPlan)
> 
>  public:
> ```

BTW: maybe a comment or two about why this is a dummy constructor and all the action must happen in the derived class constructors.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgUqCWOyMpahBR-wMEC:-KgUqCWOyMpahBR-wMED:b-k0o5c8) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L81)):*
> ```objc
>    * @param robot_status Current status of the robot.
>    * @param paramset Parameters.
>    * @param alias_groups Topological information of the robot.
> ```

BTW: Perhaps ModifyPlan is a better name.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeI_UFa5C9doJT0gDq:-KgeI_UFa5C9doJT0gDr:b-ggimt3) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L104)):*
> ```objc
>       const param_parsers::ParamSet& paramset,
>       const param_parsers::RigidBodyTreeAliasGroups<T>& alias_groups,
>       const void* message_bytes, int message_length);
> ```

BTW: Is there no other safe method to pass in messages other than this void pointer?

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeJAi25uL5gK_kRWNf:-KgeJAi3CLhon7xQ0VWx:b-67gu09) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L139)):*
> ```objc
>    * Returns the current planned contact state.
>    */
>   const ContactState& get_contact_state() const { return contact_state_; }
> ```

BTW: How about renaming this to "get_planned_contact_state"

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeNB0B9PCHGVzPgXb0:-KgeNB0CRcMjXt7h3uuz:b-p6irg1) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc#L112)):*
> ```cpp
> }
> 
> // Tests the cloned fields are the same as the original.
> ```

nit: "Tests *if* the..."

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeNREuR4T1nluUYLWV:-KgeNREuR4T1nluUYLWW:b-rvtzkd) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc#L138)):*
> ```cpp
>   v_d.setZero();
> 
>   // Changes the current state.
> ```

BTW: How about a comment here saying that this choice of position and velocity for the test is arbitrary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-KgeNzQeobY6OshbK7IV:b-4rr7kk)*

**Comment by naveenoid** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626)*

**Comment by siyuanfeng-tri** [comment]
Review status: 5 of 8 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeMK0IWgG_smqnkMzW:-Kgr5UTuPx095Vh14nNb:b4dzx5o) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.cc#L55)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Is there a need to retain a base class version of HandlePlanMessage of ExecutePlan when they dont really do anything common for all derived classes? Why not make this pure virtual to begin with?
</blockquote></details>

i am attempt to follow a paradigm called nvi https://en.wikipedia.org/wiki/Non-virtual_interface_pattern

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgUOlcZ2iUowgrGD6V0:-Kgr6Fx7SrJC_8JzPjYn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L30)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

nit: Typo "an"?
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgUqJcwZ8MCVZYEam11:-KgrATpTSxTdmPvOIVMX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L48)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: maybe a comment or two about why this is a dummy constructor and all the action must happen in the derived class constructors.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgUqCWOyMpahBR-wMEC:-Kgr6dB6TeunVMNZFvfo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L81)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Perhaps ModifyPlan is a better name.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeI_UFa5C9doJT0gDq:-Kgr6f3g7PJdqa_khEVQ:b-y6yq2p) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L104)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Is there no other safe method to pass in messages other than this void pointer?
</blockquote></details>

because lcm message doesn't have a shared base class. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeJAi25uL5gK_kRWNf:-Kgr6rj9a4L8tjfQG3Hm:b-etnlwc) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L139)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: How about renaming this to "get_planned_contact_state"
</blockquote></details>

good point. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeNB0B9PCHGVzPgXb0:-Kgr7aZfG3p-UASwrfOp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc#L112)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

nit: "Tests *if* the..."
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgeNREuR4T1nluUYLWV:-Kgr7jVdDIhnbgVCnKJB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/706d8f38e6db7a8a31cb047b1f6bc83487d09810/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/test/generic_plan_test.cc#L138)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: How about a comment here saying that this choice of position and velocity for the test is arbitrary?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-Kgs4vtjEwJgqpWgVzZk:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for platform review, thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-KgtI1MoArsSARZ4MvYq:bks4ngn)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 3 of 8 files at r1, 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgtvNTI1XbokMFLw38f:-KgtvNTI1XbokMFLw38g:bpcmw0m) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L53)):*
> ```objc
>    * to implement CloneGenericPlanDerived() to copy custom internal fields.
>    */
>   std::unique_ptr<GenericPlan<T>> Clone() const;
> ```

It seems weird to have a custom Clone() function and to have a default copy constructors and assignment operators.  If default assignment will do the right thing, why have Clone()? 

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/manipulator_inverse_dynamics_controller_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-Kgtzuk0nqp_AIY-__U8:-Kgtzuk0nqp_AIY-__U9:b-508wzh) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/system/test/manipulator_inverse_dynamics_controller_test.cc#L14)):*
> ```cpp
> #include "drake/systems/primitives/constant_vector_source.h"
> 
> #include "gtest/gtest.h"
> ```

This seems like the opposite of what clang-format-includes would do...  Why the change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-KgtugwKclilDVU1Pj4M:b-s794vx)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgtvNTI1XbokMFLw38f:-Kgz3jwz9-GpVgVqFwgy:b-5tw780) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L53)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems weird to have a custom Clone() function and to have a default copy constructors and assignment operators.  If default assignment will do the right thing, why have Clone()? 
</blockquote></details>

ah, so the grand plan is to hide all the assignment shit as protected, so the derived class can have a easier life of cloning. if i do copy / cloning member fields by hand, it's hard to maintain, and i am likely to miss one in the future. pointers could make stuff harder, but i will worry about it later. 
i am also thinking about making assignment / copy public for the final derived class as well. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/manipulator_inverse_dynamics_controller_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-Kgtzuk0nqp_AIY-__U8:-Kgz4_iffzYXlWuNNIFB:b-jeetrt) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/system/test/manipulator_inverse_dynamics_controller_test.cc#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This seems like the opposite of what clang-format-includes would do...  Why the change?
</blockquote></details>

hmm probably some merging / rebasing fail. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgtvNTI1XbokMFLw38f:-KgzIY50RqW8C9bgBExs:b-bkd7vm) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L53)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

ah, so the grand plan is to hide all the assignment shit as protected, so the derived class can have a easier life of cloning. if i do copy / cloning member fields by hand, it's hard to maintain, and i am likely to miss one in the future. pointers could make stuff harder, but i will worry about it later. 
i am also thinking about making assignment / copy public for the final derived class as well. 
</blockquote></details>

Ok.  Can we make the copy protected on this class and document that?

Alternately, I'm not sure how an operator makes things easier for the derived class...  They can call their parent's Clone() and then handle the rest of the member fields in the derived class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgtvNTI1XbokMFLw38f:-Kh3AYKJ_iVPRQeDt2fL:bv1g8mc) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L53)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ok.  Can we make the copy protected on this class and document that?

Alternately, I'm not sure how an operator makes things easier for the derived class...  They can call their parent's Clone() and then handle the rest of the member fields in the derived class.
</blockquote></details>

because the derived will also have default assignment and all that, and the would automatically calling the parents' without me explicitly doing it. 

i did make the  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(GenericPlan) in the protected secton

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-KgtvNTI1XbokMFLw38f:-Kh3DcPdMOjYQAti4iyC:b-8b8kz8) ([raw file](https://github.com/robotlocomotion/drake/blob/62d4db0e788dfc112b3f125b61f88dafe4aa262c/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L53)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

because the derived will also have default assignment and all that, and the would automatically calling the parents' without me explicitly doing it. 

i did make the  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(GenericPlan) in the protected secton
</blockquote></details>

OK.  (though protected, then public, then protected, then private is a little weird according to https://google.github.io/styleguide/cppguide.html#Declaration_Order though that just says "usually")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5626#-:-Kh3Ds9iI1IuPECHcRXT:bnfp4nl)*

**Pull request merged**
