### PR TITLE
Trigpoly feature parity reapply

### PR DESCRIPTION
**Pull request by ggould-tri**
Reapply #2345 now that offending tests have been nerfed in #2432 

This change has already been fully reviewed, as it is a conflict-free cherry-pick of #2345 onto current master.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2440) &emsp; Multiple assignees:&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@sammy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sammy-tri">sammy-tri</a>

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@david-german-tri (on-call platform reviewer)
+@sammy-tri (feature)
All changes before 8dce630 are previously reviewed; the only new changes are:
 * 8dce630: Incorporate changes implied by #2431
 * fa5dbb8: Nerf another probable #2342 instance

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> #### Trigpoly feature parity reapply
> 
> Reapply #2345 now that offending tests have been nerfed in #2432 
> 
> 
> 
> This change has already been fully reviewed, as it is a conflict-free cherry-pick of #2345 onto current master.
> 
> 
> 
</details>


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2440#-:-KIYtkt503_BLvQagv28:421900925)*

**Comment by david-german-tri** [comment]
Rubberstamping on the word of @ggould-tri that this is fully reviewed.  You might want to consider manually running the postsubmit CI that failed last time before merging this.  (Yes, I owe instructions on how to do that.  Coming soon, I hope.)

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> +@david-german-tri (on-call platform reviewer)
> +@sammy-tri (feature)
> All changes before 8dce630 are previously reviewed; the only new changes are:
>  * 8dce630: Incorporate changes implied by #2431
>  * fa5dbb8: Nerf another probable #2342 instance
> 
</details>


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2440#-:-KIZ-J84HsHCmBWXcI-j:-851705579)*

**Comment by sammy-tri** [comment]
:lgtm:  (which I'd expect since IIRC I already reviewed it once before)

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Rubberstamping on the word of @ggould-tri that this is fully reviewed.  You might want to consider manually running the postsubmit CI that failed last time before merging this.  (Yes, I owe instructions on how to do that.  Coming soon, I hope.)
</details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2440#-:-KIcyHMbVvvZmd04vWjU:-1931323924)*

**Comment by ggould-tri** [comment]
@david-german-tri can you either lgtm this or send me the retest info?

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> :lgtm:  (which I'd expect since IIRC I already reviewed it once before)
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2440#-:-KIhEIOY1pGNOgUJ0epH:-28260742)*

**Comment by david-german-tri** [comment]
:lgtm: (apologies, I intended to do that above but apparently I forgot to type it.)

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> @david-german-tri can you either lgtm this or send me the retest info?
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2440#-:-KIhHLBoz1eRnDHticHC:1897431694)*

**Pull request merged**
