### PR TITLE
Templatize MassSpringDamper class

### PR DESCRIPTION
**Pull request by mitiguy**
Templatize MassSpringDamper class so it works more seamlessly to
check results for Evan.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6353)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@edrumwri 
Platform review +@sherm1 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-:-KmiVmFo4jzK8uPm2ILo:b-a8o0i9)*

**Comment by sherm1** [comment]
Platform :lgtm:, with a few BTWs to fix.
-@edrumwri is out, so +@amcastro-tri for feature review please. 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmi_B8sjDfY-s1ENRXX:-Kmi_B8sjDfY-s1ENRXY:b-al6hrs) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L22)):*
> ```objc
> /// and ẋ is the time-derivative of x.
> ///
> /// @note This class has instantiated templates for type double and AutoDiffXd.
> ```

BTW we have standard boilerplate for this. Better to use it here. Example:
```
/// @tparam T The vector element type, which must be a valid Eigen scalar.
///
/// Instantiated templates for the following kinds of T's are provided and
/// available to link against in the containing library:
/// - double
/// - AutoDiffXd
```

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmi_rtMsGGO0Qvpg2R6:-Kmi_rtMsGGO0Qvpg2R7:bil5ixz) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L194)):*
> ```cpp
>     const double derivative_MG = partial_derivatives_with_respect_to_m(i);
>     derivative_difference = derivative_MG - derivative_plant;
>     is_derivative_close = std::abs(derivative_difference) < 5000 * epsilon;
> ```

BTW please add a comment about the choice of tolerance values (here and above).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-:-Kmi_yBR0bWzq0S_YnMN:b-npm4a7)*

**Comment by amcastro-tri** [comment]
Just a number of small comments. Once resolved :lgtm: 

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj260-IcRePEAOFcLc:-Kmj260-IcRePEAOFcLd:bl2uwvr) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L55)):*
> ```objc
> 
>   /// Returns x (Nx measure of Q's position from No) at time t.
>   T get_x(const T& t)  { return CalculateOutput(t)(0); }
> ```

BTW, this method could/probably should be marked `const`

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj2AZG6HMxTNos-dWo:-Kmj2AZHNRA-h9pXz63C:be6ltkj) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L58)):*
> ```objc
> 
>   /// Returns ẋ (Nx measure of Q's velocity in N) at time t.
>   T get_xDt(const T& t)  { return CalculateOutput(t)(1); }
> ```

BTW, this method could/probably should be marked `const`

---

*[drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj2CajBG95PK8ShEEW:-Kmj2CajBG95PK8ShEEX:bl2uwvr) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/mass_damper_spring_analytical_solution.h#L61)):*
> ```objc
> 
>   /// Returns ẍ (Nx measure of Q's acceleration in N) at time t.
>   T get_xDtDt(const T& t)  { return CalculateOutput(t)(2); }
> ```

BTW, this method could/probably should be marked `const`

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj3SyEQsD9gBd9hnBv:-Kmj3SyEQsD9gBd9hnBw:b-t4v77) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L157)):*
> ```cpp
>   // Expected special-case solution is x(t) = x0*cos(wn*t).
>   using std::sqrt;
>   const AutoDiffXd wn = sqrt(k / m);
> ```

BTW, if you instantiate `plant` before this calculation you could do `plant.CalculateNaturalFrequency()`

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 177 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj3tMi24WZq4puRsm2:-Kmj3tMi24WZq4puRsm3:bsrhzku) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L177)):*
> ```cpp
>   // Compare the analytical solution with the expected results.
>   Eigen::Vector3d values_expected, derivatives_expected;
>   for (int i = 0; i < 3; i++) {
> ```

BTW, not that matters a lot here, but we tend to use `++i` in all of our Drake loops.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj4VCiVHJYvJ0k9bwG:-Kmj4VCiVHJYvJ0k9bwH:bob5obb) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L181)):*
> ```cpp
>     const double value_plant = x_xDt_xDtDt(i).value();
>     const double value_difference = value_expected - value_plant;
>     const bool is_value_close = std::abs(value_difference) < 4 * epsilon;
> ```

is `epsilon` a constant? if so per style guide I think we should name it `kEpsilon`.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 182 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj44FNcwFiNJfUwKH-:-Kmj44FOqWPIbaMM9HOo:b-2cy078) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L182)):*
> ```cpp
>     const double value_difference = value_expected - value_plant;
>     const bool is_value_close = std::abs(value_difference) < 4 * epsilon;
>     EXPECT_TRUE(is_value_close);
> ```

BTW, we would typically use  `EXPECT_NEAR(value_plant, value_expected, 4 * epsilon)`, which would give you a much verbose message if the test fails. Also you would not need `value_difference` nor `is_value_close`.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj4cbAkdiXhm0IV5re:-Kmj4cbAkdiXhm0IV5rf:b-wd7xm3) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L189)):*
> ```cpp
>     double derivative_difference = derivative_expected - derivative_plant;
>     bool is_derivative_close = std::abs(derivative_difference) < 4 * epsilon;
>     EXPECT_TRUE(is_derivative_close);
> ```

ditto, EXPECT_NEAR

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmi_rtMsGGO0Qvpg2R6:-Kmj5HG9-4lpmrHRc3rg:boxot1l) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L194)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please add a comment about the choice of tolerance values (here and above).
</blockquote></details>

ditto, I wonder why if the other results where within 4 epsilon why these should be so much further apart.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj5NTdGMUaRhhnQoPn:-Kmj5NTdGMUaRhhnQoPo:b-jdlcqu) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L195)):*
> ```cpp
>     derivative_difference = derivative_MG - derivative_plant;
>     is_derivative_close = std::abs(derivative_difference) < 5000 * epsilon;
>     EXPECT_TRUE(is_derivative_close);
> ```

BTW, EXPECT_NEAR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-:-Kmj5QH3Ce3VVOrY5bGo:b-4vqs2c)*

**Comment by mitiguy** [comment]
@amcastro-tri  PTAL - blocking comments.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj4VCiVHJYvJ0k9bwG:-KmmBPacUgEnxSgm0Ya7:b-8y3rxf) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L181)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is `epsilon` a constant? if so per style guide I think we should name it `kEpsilon`.
</blockquote></details>

Done.  Changed to kEpsilon.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmj4cbAkdiXhm0IV5re:-KmnA3A1YXyX5nJNgtQr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L189)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, EXPECT_NEAR
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-Kmi_rtMsGGO0Qvpg2R6:-KmnA55Yd62rWM9gsy7K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/587c33fa8006f6bc202a2850b013bc12ca0c6b25/drake/multibody/benchmarks/mass_damper_spring/test/mass_damper_spring_analytical_solution_test.cc#L194)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, I wonder why if the other results where within 4 epsilon why these should be so much further apart.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6353#-:-KmnAq__KTNUQLU8pOHI:b-me6b2m)*

**Pull request merged**
