### PR TITLE
Tidy up some nits

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3802)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3802#-:-KU2Lx602fNjbpbTvvNH:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri
+@rpoyner-tri feature retroactively.
+@ggould-tri platform.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3802#-:-KU2TPRjAZNUHIviQuUd:b6s1fry)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3802#-KU2VTiE2uiDMw790bCe:-KU2VTiE2uiDMw790bCf:b-ydbbod) ([raw file](https://github.com/robotlocomotion/drake/blob/a08411ae6a3ac21744489397d691908064a1ed6c/drake/systems/analysis/simulator.cc#L10)):*
> ```cpp
> 
> template class DRAKE_EXPORT Simulator<double>;
> template class DRAKE_EXPORT Simulator<AutoDiffXd>;
> ```

I am not clear why this is right.  It seems to me it would be more appropriate to clean up the compiler-specific block in `simulator.h` and keep exporting the template instantiation in the cc file per our conventions ( http://drake.mit.edu/cxx_inl.html#id3 ).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3802)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.cc, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3802#-KU2VTiE2uiDMw790bCe:-KU2ZW67EtQhsIBMWbt7:b-wavlq7) ([raw file](https://github.com/robotlocomotion/drake/blob/a08411ae6a3ac21744489397d691908064a1ed6c/drake/systems/analysis/simulator.cc#L10)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I am not clear why this is right.  It seems to me it would be more appropriate to clean up the compiler-specific block in `simulator.h` and keep exporting the template instantiation in the cc file per our conventions ( http://drake.mit.edu/cxx_inl.html#id3 ).
</details>
Good point, thank you.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3802)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3802#-:-KU2aRAI55Fl_vCIARpr:bnfp4nl)*

**Pull request merged**
