### PR TITLE
Defer collision element registration with the collision engine

### LINKED ISSUE #2481: Review logic for CollisionElement::isStatic
Method `CollisionElement::isStatic` is only used once in `BulletModel::addElement`. It is a virtual method that never gets overriden and by default it returns false (even when a terrain clearly is static). 

Could this be a cause of faulty collision detection? (see #2004) or a cause of performance issues?
In any case it is a piece of dead code that needs to be revisited.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Summary
-------------

This PR is the first of three for bringing the current system up to spec vis a vis collision filtering; In #4204 it is labeled as "The Plan"'s 2.i.  This defers registration of geometry with the underlying collision engine until *after* the tree has been constructed (see #2661). It also addresses issues with anchored geometry definitions #4348.

Details
---------

Deferring the geometry has several advantages:

- Previously, collision filtering wasn't correct.  The initial conditions weren't correct and, although there was a possibility of the collision filters correcting themselves w.r.t. time, there were no guarantees. (see #4204).  Now, we can guarantee the filtering logic is in place *before* the collision engine is engaged.
- It allows us to properly classify anchored geometry.  Anchored geometry doesn't move during the simulation (see #4348) and the collision engine can apply nice optimizations to it.
- It removes the short-term hack as part of #4204 The Plan 1. Now that collision filters are properly implemented, the collision results no longer need to be post-filtered.

Implications
----------------

- When users explicitly add geometry to a `RigidBodyTree` (like when defining a "ground" plane), they are obliged to call `RigidBodyTree::compile` to finalize it.
- There is now no guaranteed correlation between the *order* in which collision elements are added to the `RigidBodyTree` and their order in the `PointPair` instance generated by collision detection; in other words, don't assume you know what `elementA` and `elementB` are based on tree construction.
- Previously, bodies (and their corresponding collision elements) that should have been considered "anchored" (formerly known as static, see #4348), were not actually properly classified.  If the collision geometry was a mesh, that mesh would silently be turned into a *convex hull*.  Now it will be a proper triangle mesh.  However, this requires that the mesh in question be properly triangulated.  Otherwise, it will default back to a default mesh (see #4397).
   - This will also be related to #3220. The meshes intended to be anchored, will be recognized as such.
   - Should help with the performance of #2644.
   - Probably resolves #2481.  There are still some open questions vis a vis mass properties.  But they may be orthogonal to this issue.
- In testing, collision elements should *not* be added directly to `RigidBody` instances.  They only get properly defined (with collision filter data and "anchored" status) by going through `RigidBodyTree::AddCollisionElement` follows by a subsequent call to 'RigidBodyTree::compile`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4409)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@sammy-tri for platform review and @amcastro-tri for feature review.

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4409#-:-KYPJp2oBAkhfzSbCyUJ:bo81wj2)*

**Comment by SeanCurtis-TRI** [comment]
Between original submission and now, master has changed leading to conflicts.  There are also some test failures that don't appear on my machine.  So, hold off on review until I have them figured out.

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4409#-:-KYPxPgoAsAK-amBTM2M:b-s794vx)*

**Comment by SeanCurtis-TRI** [comment]
CI Issues revealed a number of downstream issues...the details of the PR have changed enough that *this* PR is being closed and a *new* PR will replace it.

**Pull request closed without merging**
