### PR TITLE
Allow to overestimate the capacity for block sparse matrices

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15162)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15162#-:-MbmR8dV0hHJSfATVAI5:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with two nits.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15162#-:-MbmUA6c8I6qwA5ILVx-:b-oy2utn)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/block_sparse_matrix.h, line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15162#-MbmTHsNEcSBRql487I-:-MbmTHsNEcSBRql487I0:becmuhl) ([raw file](https://github.com/robotlocomotion/drake/blob/90766821f269a0f04dc49004529670f00e94ed1b/multibody/contact_solvers/block_sparse_matrix.h#L176)):*
> ```objc
>   //   here requested.
>   //   Since we do not allow empty rows or columns nonzero_blocks_capacity must
>   //   be larger than both block_rows and block_cols.
> ```

nit: technically outside the scope of this PR, but should this be larger than *or equal to*?
___
*[multibody/contact_solvers/test/block_sparse_matrix_test.cc, line 154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15162#-MbmSh0BCQn-a4O9fR8v:-MbmSh0BCQn-a4O9fR8w:bko26o9) ([raw file](https://github.com/robotlocomotion/drake/blob/90766821f269a0f04dc49004529670f00e94ed1b/multibody/contact_solvers/test/block_sparse_matrix_test.cc#L154)):*
> ```cpp
>   builder.PushBlock(0, 2, J_.block(0, 3, 3, 2));
>   builder.PushBlock(1, 2, J_.block(3, 3, 4, 2));
>   builder.PushBlock(2, 1, J_.block(7, 2, 3, 1));  // 4th block omitted.
> ```

nit: extraneous comment from copypasta.

**Review by amcastro-tri — COMMENTED** [review]
+@sherm1 for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15162#-:-Mbmq-VU6B04xlJaKb0q:b6vi582)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15162)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15162#-:-Mbmx3CP4ssncHfedgOd:b8qx53o)* status: 1 unresolved discussion (waiting on @amcastro-tri)

**Pull request merged**
