### PR TITLE
[visualization] Add frame (aka triad) visualization function

### LINKED ISSUE #17170: geometry: Should expose public API for `add_triad` for frame visualization
Per https://github.com/robotlocomotion/drake/pull/17141#issuecomment-1121847796

@JoseBarreiros-TRI is this something you'd be up for? (at low priority)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17170.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 532 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNSEQI3mgt4r_Nx0yi:-NSNSEQI3mgt4r_Nx0yj:bjn4pac) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L532)):*
> ```Python
> ):
>     """
>     Adds illustration geometry representing the given coordinate frame, with
> ```

FYI  It seems the word "coordinate" is unnecessary.  In the context of Drake, it is unclear how a coordinate frame differs from a frame.   Consider removing it.
___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 547 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNRhdsEqst9LqYOx44:-NSNRhdsEqst9LqYOx45:b-i7mm9p) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L547)):*
> ```Python
>       radius: the radius of each axis in meters.
>       opacity: the opacity each axes, between 0.0 and 1.0.
>       X_FT: the pose of the triad frame T in the frame_id frame F.
> ```

FYI consider:

```
X_FT: rigid transform relating frame T and frame F.
```
___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 548 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNT6oaEg9Ju2f6BA2r:-NSNT6obCeKH8_PVjHI4:bkojq7q) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L548)):*
> ```Python
>       opacity: the opacity each axes, between 0.0 and 1.0.
>       X_FT: the pose of the triad frame T in the frame_id frame F.
>       name: the added geometries will have names "{name} x-axis", etc.
> ```

FYI   Wondering if x-axis associates with a line or a unit vector (a direction) -- or if there is sufficient context that it is irrelevant?  If the x-axis is a unit vector and the body name is B, I typically use names such as Bx, By, Bz for the associated unit vectors -- or if enough unicode bandwidth 𝗕x 𝗕y 𝗕ᴢ.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @mitiguy)

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 564 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNjKDZ3obn1HmQd25g:-NSNjKDZ3obn1HmQd25h:b-exancf) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L564)):*
> ```Python
>         geom_name = f"{name} {char}-axis"
>         p_TG = 0.5 * length * eye[i]
>         R_TG = AngleAxis(angle=np.pi/2, axis=eye[1-i])
> ```

BTW am I interpreting `eye[1-i]` correctly: it maps x->y, y->x and z to itself? And is that the intent?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy and @sherm1)

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 564 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNjKDZ3obn1HmQd25g:-NSNkCg4DPxZq-ySs8NI:b-jyxprp) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L564)):*
> Am I interpreting eye[1-i] correctly: it maps x->y, y->x and z to itself

Yes!

> And is that the intent?

Yes.  R_TG rotates a cylinder aligned with the z axis to instead align with the ith axis.  When i == 2, it spins the cylinder around the z axis, but this is a no-op (for a uniformly textured cylinder).

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @mitiguy)

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 564 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNjKDZ3obn1HmQd25g:-NSOCWMI5KrY6fqdO5dY:b-8fx2u7) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L564)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Am I interpreting eye[1-i] correctly: it maps x->y, y->x and z to itself

Yes!

> And is that the intent?

Yes.  R_TG rotates a cylinder aligned with the z axis to instead align with the ith axis.  When i == 2, it spins the cylinder around the z axis, but this is a no-op (for a uniformly textured cylinder).
</blockquote></details>

:+1:

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy and @sherm1)

___
*[`bindings/pydrake/visualization/_model_visualizer.py` line 548 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSNT6oaEg9Ju2f6BA2r:-NSQxzceAyv__xpVPmw1:bva0wqa) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9a4757f140e46427c030bd2960c896c9c001048/bindings/pydrake/visualization/_model_visualizer.py#L548)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

FYI   Wondering if x-axis associates with a line or a unit vector (a direction) -- or if there is sufficient context that it is irrelevant?  If the x-axis is a unit vector and the body name is B, I typically use names such as Bx, By, Bz for the associated unit vectors -- or if enough unicode bandwidth 𝗕x 𝗕y 𝗕ᴢ.
</blockquote></details>

The illustration geometry is not really a unit vector.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri feature.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-:-NSRGjsJ7zfzCDx8wuVy:b5v0m1t)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSRHA4M6kIXzI0GvHHC:-NSRHA4M6kIXzI0GvHHD:b-hwbu5m) (no related file):*
Are there any recommended manual tests for visuals?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSRHA4M6kIXzI0GvHHC:-NSRItp14tmWi6YqDTLC:b-kf0b8q) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Are there any recommended manual tests for visuals?
</blockquote></details>

My nominal manual test is always just to run the model file given in the help string, in this case with triads turned on:

`bazel run //tools:model_visualizer -- package://drake/manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf --visualize_frames`

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nittery

> Reviewed 1 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-:-NSRaWkk9jHiL5jx3mUk:bb62doi)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSRHA4M6kIXzI0GvHHC:-NSRa7_I2FyGLUoAfyqH:b-wv6pi) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My nominal manual test is always just to run the model file given in the help string, in this case with triads turned on:

`bazel run //tools:model_visualizer -- package://drake/manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf --visualize_frames`
</blockquote></details>

Looks good. I pondered whether there was a way with current on-screen controls to conveniently turn the frames on/off as a layer or even individually, but didn't really succeed in finding one. Maybe can be addressed in follow-up work?

___
___
*[`bindings/pydrake/visualization/_triad.py` line 26 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSR_oJ39zUPPrBfB4Tq:-NSR_oJ43cHrQHbSZFKc:b-d8n4iz) ([raw file](https://github.com/RobotLocomotion/drake/blob/73718c8d3178cc0940b89f61e0997dfb4e9ceea5/bindings/pydrake/visualization/_triad.py#L26)):*
> ```Python
>     radius: float = 0.005,
>     opacity: float = 0.9,
>     X_FT: RigidTransform = RigidTransform(),
> ```

nit recall that the default values are global lifetime and mutable. I can't see a problem with the current implementation here (no modifications of X_FT), but I will confess a shiver goes down my spine.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSRHA4M6kIXzI0GvHHC:-NSRnGAI5hhg6wQu3K21:b-ucva0m) (no related file):*
> Maybe can be addressed in follow-up work?

Yup.  We could do it the same way that we are going to do the inertia visualization.  It requires one new capability from MeshcatVisualizer so I'm going to wait for inertia to land first.

___
___
*[`bindings/pydrake/visualization/_triad.py` line 26 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-NSR_oJ39zUPPrBfB4Tq:-NSRo2Qh2bWZOP2lqud3:b476oo5) ([raw file](https://github.com/RobotLocomotion/drake/blob/73718c8d3178cc0940b89f61e0997dfb4e9ceea5/bindings/pydrake/visualization/_triad.py#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit recall that the default values are global lifetime and mutable. I can't see a problem with the current implementation here (no modifications of X_FT), but I will confess a shiver goes down my spine.
</blockquote></details>

I had actually thought about that, but somehow misremembered that RigidTransform was immutable so dismissed it out of hand.  Oops.

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for Monday platform review.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-:-NSSGdHKBm3fi_dfrVr0:bvjn1bs)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19152#-:-NSfXTHJ81Myg6_h08fD:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
