### PR TITLE
added DeclareAbstractState in LeafSystem

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
resolving this 
https://github.com/RobotLocomotion/drake/issues/5805

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5819)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@jwnimmer-tri for feature review. thanks 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-:-KhccX1tgKs4_tyjHfgK:b-tfynyf)*

**Comment by siyuanfeng-tri** [comment]
+@david-german-tri for feature review. thanks!
-@jwnimmer-tri is on vacation. 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-:-KhcxD_KbNiqcJjlK_Kn:bx3t1se)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-:-Khd6mfUw7iocC0V08AM:b-s794vx)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-:-KhdWrH60JKVAd-ctEEF:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
+@soonho-tri for platform review. thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-:-Khgb6msTW7G77QLp74q:buvypxa)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a BTW)

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-KhhUA8mzsudUS1PaQYa:-KhhUA8nIxPFn7zuQ3hh:b-j7d88d) ([raw file](https://github.com/robotlocomotion/drake/blob/a60347f3b965a6569d47d2ae3c01207a8b6c8b93/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc#L31)):*
> ```cpp
>     const std::string& alias_groups_file_name,
>     const std::string& param_file_name, double dt)
>     : PlanEvalBaseSystem(robot, alias_groups_file_name, param_file_name, dt) {
> ```

BTW, (META) you can keep `abs_state_index_plan_` `const` by using member initializer list:
```c++
HumanoidPlanEvalSystem::HumanoidPlanEvalSystem(
    const RigidBodyTree<double>& robot,
    const std::string& alias_groups_file_name,
    const std::string& param_file_name, double dt)
    : PlanEvalBaseSystem(robot, alias_groups_file_name, param_file_name, dt),
      abs_state_index_plan_{
          DeclareAbstractState(systems::AbstractValue::Make<SimpleStandingPlan>(
              SimpleStandingPlan()))} {
  set_name("HumanoidPlanEval");
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-:-KhhWeO3zJhJ8xjE3kNR:b-i8gkkc)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5819#-KhhUA8mzsudUS1PaQYa:-KhhcgiuZnabgnNRJSqZ:b-d4x25o) ([raw file](https://github.com/robotlocomotion/drake/blob/ecf0548120c3aa492d82e3b7b8c2ea1f10ae2a19/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc#L31)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, (META) you can keep `abs_state_index_plan_` `const` by using member initializer list:
```c++
HumanoidPlanEvalSystem::HumanoidPlanEvalSystem(
    const RigidBodyTree<double>& robot,
    const std::string& alias_groups_file_name,
    const std::string& param_file_name, double dt)
    : PlanEvalBaseSystem(robot, alias_groups_file_name, param_file_name, dt),
      abs_state_index_plan_{
          DeclareAbstractState(systems::AbstractValue::Make<SimpleStandingPlan>(
              SimpleStandingPlan()))} {
  set_name("HumanoidPlanEval");
}
```
</blockquote></details>

i prefer it outside since it's a bit more readable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5819)*

**Pull request merged**
