### PR TITLE
Implement Diagram<T>::MapVelocityToConfigurationDerivatives.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3695)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Revives #3394.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-:-KTLadvyUa0T03Pgn-qC:bv121g7)*

**Comment by david-german-tri** [comment]
+@sherm1 for feature review.  I think the Eigen-based approach we just discussed f2f works pretty well.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-:-KTM15YI5uJ2fSZ-_-oc:bvaldy6)*

**Comment by sherm1** [comment]
:lgtm_strong: -- sweet. Sorry it took me so long to get to it. A few minor comments, PTAL.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 328 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm48kIYWzVaTdz2cnb:-KTm48kIYWzVaTdz2cnc:b-3s7dem) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram.h#L328)):*
> ```objc
>   }
> 
>   /// The @p generalized_velocity vector must have the same size and order as
> ```

BTW, I had to read this several times to realize that "order" meant "ordering"; I think ordering would be more clear. (I was thinking it meant some measure of complexity like "second order" or some measure of its structure.)

---

*[drake/systems/framework/diagram.h, line 339 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm2ef34doQRKyuevKM:-KTm2ef4WuaMLtvymsVO:b6rgh2s) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram.h#L339)):*
> ```objc
>     // derivatives.
>     const ContinuousState<T>* xc = context.get_continuous_state();
>     DRAKE_DEMAND(xc != nullptr);
> ```

BTW, should there always be a non-null continuous state even if there are 0 continuous state variables? It would be nice just to be able to call this method with zero-length vectors and have it properly no-op rather than die.

---

*[drake/systems/framework/diagram.h, line 373 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm3xuZ3KX3aZcK99QK:-KTm3xuZ3KX3aZcK99QL:b-t8lnux) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram.h#L373)):*
> ```objc
>       // Delegate the actual mapping to subsystem i itself.
>       sorted_systems_[i]->MapVelocityToConfigurationDerivatives(
>           *subcontext, v_slice, &dq_slice);
> ```

BTW, this is really nice!

---

*[drake/systems/framework/diagram_context.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm4aYPGdIW4Guq9VzM:-KTm4aYPGdIW4Guq9VzN:b3a66nz) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram_context.h#L33)):*
> ```objc
>   ///
>   /// The DiagramContinuousState vector xc = [q v z] will have the same
>   /// order as the @p substates parameter, which should be the sort order of
> ```

BTW, order->ordering

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-:-KTm6D-jOH_9CblYlhhR:b-il6vuy)*

**Comment by david-german-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 328 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm48kIYWzVaTdz2cnb:-KTp3cz8klSIWStwYyRp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram.h#L328)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I had to read this several times to realize that "order" meant "ordering"; I think ordering would be more clear. (I was thinking it meant some measure of complexity like "second order" or some measure of its structure.)
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 339 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm2ef34doQRKyuevKM:-KTp43tA2-dHeXn9TAle:b2t2w7i) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram.h#L339)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, should there always be a non-null continuous state even if there are 0 continuous state variables? It would be nice just to be able to call this method with zero-length vectors and have it properly no-op rather than die.
</details>
Yeah, I've been drifting that way myself in recent weeks.  Opened #3765.

---

*[drake/systems/framework/diagram_context.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3695#-KTm4aYPGdIW4Guq9VzM:-KTp4XTBtGCwVDK0KAoc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2c30f32f33a6f71b4f12f094b7ef1a5507061ed/drake/systems/framework/diagram_context.h#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, order->ordering
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3695)*

**Comment by sherm1** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3695)*

**Pull request merged**
