### PR TITLE
Provide better diagnostics when buildifier complains

### LINKED ISSUE #7121: Make "buildifier failed" lint output easier to understand
The output of our "buildifier failed" tests is very obscure.  It should clearly describe the problem, and provide a recipe and/or hyperlink for instructions to fix it.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7121.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7124)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI are you interested in feature review (does CLion matter here)?
+@soonho-tri for platform review per rotation, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: (feature review)
In this case, CLion is largely unaffected. In the current version of the bazel plugin, this *shouldn't* be an issue because it buildifies the files (and, generally, seems to be doing the right thing).

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7124#-:-Kv7lIRmC91g0JqYzV5T:by8lmgd)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7124#-:-Kv88pywDCHLcVXfrdOP:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7124)*

**Comment by jwnimmer-tri** [comment]
The `-lsan` build went out to lunch, but we don't care for buildifier-only PR.  Using override-merge.

**Pull request merged**
