### PR TITLE
[FEM] Implement CorotatedModel and math helpers

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
- Implement the fixed corotated model from Stomakhin, Alexey, et al.
 "Energetically consistent  invertible elasticity." Proceedings of the
 11th ACM SIGGRAPH/Eurographics conference on Computer Animation. 2012.

- Implement a few matrix calculation helpers to facilitate
 CorotatedModel.

- Refactor LinearConstitutiveModelTest to test for both
LinearConstitutiveModel and CorotatedModel.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@joemasterjohn for feature review please, thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599#-:-MSRMka28WFx1Fph-yd1:b2bbf9s)* status: LGTM missing from assignee joemasterjohn, labeled "do not merge" (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
Checkpoint. Moving on to tests now.

> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599#-:-MTNWb0RBMcub6oqmVCr:bgb3wz2)* status: 11 unresolved discussions, LGTM missing from assignee joemasterjohn (waiting on @joemasterjohn and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/corotated_model.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNHr_E3SQPs1XE4VHA:-MTNHr_E3SQPs1XE4VHB:bpuj7e0) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L58)):*
> ```objc
>   CorotatedModel(const T& youngs_modulus, const T& poisson_ratio)
>       : E_(youngs_modulus), nu_(poisson_ratio) {
>     const std::pair<T, T> lame_parameters =
> ```

nit: you can replace this with:
```
std::tie(lambda_, mu_) = internal::CalcLameParameters(E_, nu_);
```
___
*[multibody/fixed_fem/dev/corotated_model.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNIlCU2HsPe_CuHRVw:-MTNIlCU2HsPe_CuHRVx:b-ditvc) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L66)):*
> ```objc
>   ~CorotatedModel() = default;
> 
>   T youngs_modulus() const { return E_; }
> ```

should return `const T&` instead of `T`
___
*[multibody/fixed_fem/dev/corotated_model.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNItQ23ixfb3L26Gc2:-MTNItQ23ixfb3L26Gc3:b-ditvc) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L68)):*
> ```objc
>   T youngs_modulus() const { return E_; }
> 
>   T poisson_ratio() const { return nu_; }
> ```

should return `const T&` instead of `T`
___
*[multibody/fixed_fem/dev/corotated_model.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNIu0K7Hb99cmmnyRp:-MTNIu0K7Hb99cmmnyRq:b-ditvc) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L70)):*
> ```objc
>   T poisson_ratio() const { return nu_; }
> 
>   T shear_modulus() const { return mu_; }
> ```

should return `const T&` instead of `T`
___
*[multibody/fixed_fem/dev/corotated_model.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNIuUz-vaICqow81Lu:-MTNIuUz-vaICqow81Lv:b-ditvc) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L72)):*
> ```objc
>   T shear_modulus() const { return mu_; }
> 
>   T lame_first_parameter() const { return lambda_; }
> ```

should return `const T&` instead of `T`
___
*[multibody/fixed_fem/dev/linear_constitutive_model.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNMY9r8q3YDjvsyOZL:-MTNMY9r8q3YDjvsyOZM:b-sd4ki9) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/linear_constitutive_model.h#L58)):*
> ```objc
>   LinearConstitutiveModel(const T& youngs_modulus, const T& poisson_ratio)
>       : E_(youngs_modulus), nu_(poisson_ratio) {
>     const std::pair<T, T> lame_parameters =
> ```

nit: ditto here using `std::tie`
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNNXSp9gL1uimJmdgL:-MTNNXSq97mCEFj_mC7_:bgb85st) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L9)):*
> ```objc
> namespace fixed_fem {
> namespace internal {
> /* Some of the following methods involves calculations about 4th order tensor
> ```

nit: should be involve (singular) and "about a 4th order tensor"
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNO4E76NEG7yooyc1-:-MTNO4E76NEG7yooyc10:b-s447b1) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L11)):*
> ```objc
> /* Some of the following methods involves calculations about 4th order tensor
> (call it A) of dimension 3*3*3*3. We follow the following convention to flatten
> the 4th order tensor into 9*9 matrices that are organized as following
> ```

nit: "organized as follows:"
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNOR6A5xud23QENfUX:-MTNOR6A5xud23QENfUY:b-dhuuuc) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L27)):*
> ```objc
>               |           |           |           |
>               -------------------------------------
> Namely the ik-th entry in the jl-th block corresponds to the value Aᵢⱼₖₗ. */
> ```

BTW very helpful diagram!
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNSGrz7HtgfAWWqXPz:-MTNSGrz7HtgfAWWqXQ-:bksjt90) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L29)):*
> ```objc
> Namely the ik-th entry in the jl-th block corresponds to the value Aᵢⱼₖₗ. */
> 
> /* Calculates the unique polar decomposition of a 3-by-3 matrix F = RS where R
> ```

Is `F` guaranteed to be non-singular? I think the uniqueness of the decomposition depends on that. Also it would affect which singular value you choose to negate, if the last one happens to be 0.
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNV43xDoMq9qc_f2hW:-MTNV43xDoMq9qc_f2hX:b-yk7r62) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L92)):*
> ```objc
>   A.diagonal().array() += S.trace();
>   const T J = A.determinant();
>   DRAKE_ASSERT(J != 0);
> ```

I think `DRAKE_DEMAND` might be more appropriate here. `DRAKE_ASSERT` will only check in debug mode.
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNTLmv6qnB_USwSUyp:-MTNTLmw1ebLcvOcTjCH:b-b3cjzw) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L97)):*
> ```objc
>   const auto sRA = scale_over_J * RA;
>   const auto sRART = sRA * R.transpose();
>   for (int a = 0; a < 3; a++) {
> ```

Styleguide dictates always using pre-increment:
https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement

**Review by DamrongGuoy — COMMENTED** [review]
May I please suggest that from now on the PR title of FEM should start with `FEM:` ?  For example, this PR title should be:
```
[FEM] Implement CorotatedModel and math helpers
```

The reason is that when I (as a build cop this week) see the list of merged PRs in CI like in [this link](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-address-sanitizer/3089/), I'll know right away who likely owns it.  Sometimes I see a long list of PRs in the Nightly CI like [this link](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-bionic-clang-bazel-nightly-address-sanitizer/817/), and it helps to get a rough idea who are contributors and which parts of the code are involved. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599#-:-MTO_y8W9V4W4NHxLBqz:b-3fe7ox)* status: 11 unresolved discussions, LGTM missing from assignee joemasterjohn (waiting on @joemasterjohn and @xuchenhan-tri)

**Review by joemasterjohn — COMMENTED** [review]
Ok finished my first pass. PTAL.

> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599#-:-MTbEazdBiF1w32hNhKC:b4lw7jb)* status: 15 unresolved discussions, LGTM missing from assignee joemasterjohn (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTbD-4t3XpFus1iJDrl:-MTbD-4t3XpFus1iJDrm:bc4q6g6) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc#L19)):*
> ```cpp
> // Creates a vector of arbitrary deformation gradients.
> std::array<Matrix3<AutoDiffXd>, kNumQuads> MakeDeformationGradients() {
>   // Create random AutoDiffXd deformation.
> ```

nit: random -> arbitrary
___
*[multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTbDGPQ2i6Pbp6I_7lY:-MTbDGPQ2i6Pbp6I_7lZ:bs8gd1k) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc#L52)):*
> ```cpp
>   EXPECT_EQ(model.shear_modulus(), mu);
>   EXPECT_EQ(model.lame_first_parameter(), lambda);
> ```

Maybe just one `DRAKE_EXPECT_NO_THROW` here with valid parameters to show it works.
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTb8zBy9PuhqgrC1tfl:-MTb8zBy9PuhqgrC1tfm:bfq5hc) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L32)):*
> ```cpp
> }
> 
> const double kTol = 2e-14;
> ```

You might want to determine the tolerance at runtime based on the condition number of the matrix in question. For instance if I make the arbitrary matrix nearly singular:
```
A << 1.2, 2.4, 3.4,
     4.5, 9.0, 6.7,
     7.8, 15.5, 9.0;
```
Your test will fail with the current tolerance. I could also trigger the same tolerance failure by just scaling the matrix by 10.
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTb5Vj29fPBMPWj_HbS:-MTb5Vj29fPBMPWj_HbT:b-mi19s8) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L63)):*
> ```cpp
>       }
>       EXPECT_TRUE(
>           CompareMatrices(scale * Eigen::Map<const Matrix3<double>>(
> ```

Maybe just a few small comments at the top of these tests to explain how exactly you're conducting them for someone who might not be able to immediately figure it out. Something like "tests that the handcrafted derivative matches that produced by automatic differentiation."

**Review by xuchenhan-tri — COMMENTED** [review]
@damrongguoy  Thanks for the suggestion. I will do that in my future PRs. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599#-:-MTbEzNb9imj21RsmK2M:b-f00gly)* status: 11 unresolved discussions, LGTM missing from assignee joemasterjohn, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

___
*[multibody/fixed_fem/dev/corotated_model.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNHr_E3SQPs1XE4VHA:-MTbFBR7B9BUKa70zzrE:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L58)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: you can replace this with:
```
std::tie(lambda_, mu_) = internal::CalcLameParameters(E_, nu_);
```
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/corotated_model.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNIlCU2HsPe_CuHRVw:-MTbFGoUECsFIhdRiE4s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L66)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

should return `const T&` instead of `T`
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/corotated_model.h, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNItQ23ixfb3L26Gc2:-MTbFHK53c_R3kqRMgNn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L68)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

should return `const T&` instead of `T`
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/corotated_model.h, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNIu0K7Hb99cmmnyRp:-MTbFHb0DX96kMAShPL5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L70)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

should return `const T&` instead of `T`
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/corotated_model.h, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNIuUz-vaICqow81Lu:-MTbFHrREWEpa7PqT7Fl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/corotated_model.h#L72)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

should return `const T&` instead of `T`
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/linear_constitutive_model.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNMY9r8q3YDjvsyOZL:-MTbFQgzBSeKhpLr3ze5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/linear_constitutive_model.h#L58)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: ditto here using `std::tie`
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNNXSp9gL1uimJmdgL:-MTbFavH9sZfHWGFhsRq:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L9)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: should be involve (singular) and "about a 4th order tensor"
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNO4E76NEG7yooyc1-:-MTbFe8D2PSzRVRBm16i:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L11)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: "organized as follows:"
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNSGrz7HtgfAWWqXPz:-MTbG--dAKWciAMHXzVh:b-rj5npo) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L29)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Is `F` guaranteed to be non-singular? I think the uniqueness of the decomposition depends on that. Also it would affect which singular value you choose to negate, if the last one happens to be 0.
</blockquote></details>

Usually `F` should be a rotation away from a positive definite matrix. If `F` is singular, the sim is probably already in a bad state. I modified the comment to be more accurate about uniqueness.

I don't quite see how it affects which singular value I negate though. Could you say more about why?
Eigen svd sorts the singular values in decreasing order and I would always negate the one with the smallest magnitude (if I need to). 
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNV43xDoMq9qc_f2hW:-MTbHiWU3oxGDAWHJqxu:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L92)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I think `DRAKE_DEMAND` might be more appropriate here. `DRAKE_ASSERT` will only check in debug mode.
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNTLmv6qnB_USwSUyp:-MTbHtbs7F1V4BWh6Lv5:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L97)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Styleguide dictates always using pre-increment:
https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTbD-4t3XpFus1iJDrl:-MTbIEf68iwrHX0F395e:bkgf9x4) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc#L19)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: random -> arbitrary
</blockquote></details>

Not the first time I made this mistake... Thanks!
___
*[multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTbDGPQ2i6Pbp6I_7lY:-MTbIiHR3cB8JiNvlULY:bby4pnv) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc#L52)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Maybe just one `DRAKE_EXPECT_NO_THROW` here with valid parameters to show it works.
</blockquote></details>

The 4 `EXPECT_EQ` tests seem to imply that construction of `model` is successful. Another `DRAKE_EXPECT_NO_THROW` here seems a bit redundant. Would you agree?
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTb8zBy9PuhqgrC1tfl:-MTbPTJB3K6u6_v8P9OA:b32jr6r) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L32)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

You might want to determine the tolerance at runtime based on the condition number of the matrix in question. For instance if I make the arbitrary matrix nearly singular:
```
A << 1.2, 2.4, 3.4,
     4.5, 9.0, 6.7,
     7.8, 15.5, 9.0;
```
Your test will fail with the current tolerance. I could also trigger the same tolerance failure by just scaling the matrix by 10.
</blockquote></details>

Good point. I have modified the test accordindly, PTAL, thank you.
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTb5Vj29fPBMPWj_HbS:-MTbKvVyDp0lXS0q-ilw:b-id2v10) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L63)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Maybe just a few small comments at the top of these tests to explain how exactly you're conducting them for someone who might not be able to immediately figure it out. Something like "tests that the handcrafted derivative matches that produced by automatic differentiation."
</blockquote></details>

Good point! Done, thank you.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: thanks for your patience with me getting the review started!

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599#-:-MTc00dUDgtcFxvEuvaE:b12gtbi)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNSGrz7HtgfAWWqXPz:-MTbvIU26bMzi_nixWZj:buraei5) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Usually `F` should be a rotation away from a positive definite matrix. If `F` is singular, the sim is probably already in a bad state. I modified the comment to be more accurate about uniqueness.

I don't quite see how it affects which singular value I negate though. Could you say more about why?
Eigen svd sorts the singular values in decreasing order and I would always negate the one with the smallest magnitude (if I need to). 
</blockquote></details>

I think my concern was if the smallest magnitude singular value was 0 and you negated it (and the corresponding column), would that mess up the `F = RS` identity. But walking through it in my head, I don't think it does because `U * Σ` would still be effectively the same (but with its third column being -0 instead of 0).
___
*[multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTbD-4t3XpFus1iJDrl:-MTby4Bu60zgEredZG7H:btpe6b3) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Not the first time I made this mistake... Thanks!
</blockquote></details>

I do the same thing all the time.
___
*[multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTbDGPQ2i6Pbp6I_7lY:-MTbyNdg8-A8hWQGemM7:bhbeweh) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc#L52)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The 4 `EXPECT_EQ` tests seem to imply that construction of `model` is successful. Another `DRAKE_EXPECT_NO_THROW` here seems a bit redundant. Would you agree?
</blockquote></details>

Ah yeah, sorry brain fart.
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTb8zBy9PuhqgrC1tfl:-MTbyzGZ8zg2EBZm8Fi1:b-fdjv8c) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L32)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Good point. I have modified the test accordindly, PTAL, thank you.
</blockquote></details>

Looks good! I saw you put it in `hyperelastic_constitutive_model_test`, but did you want to add it to `matrix_utilities_test` too? Either way, I'm setting to resolved.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14599)* status: :shipit: complete! all discussions resolved, LGTM from assignee joemasterjohn, exempt from platform review (waiting on @joemasterjohn)

___
*[multibody/fixed_fem/dev/matrix_utilities.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTNSGrz7HtgfAWWqXPz:-MTc6EPnEUFR8Laq_MMh:b-pbdqzg) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/matrix_utilities.h#L29)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I think my concern was if the smallest magnitude singular value was 0 and you negated it (and the corresponding column), would that mess up the `F = RS` identity. But walking through it in my head, I don't think it does because `U * Σ` would still be effectively the same (but with its third column being -0 instead of 0).
</blockquote></details>

Agreed!
___
*[multibody/fixed_fem/dev/test/matrix_utilities_test.cc, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14599#-MTb8zBy9PuhqgrC1tfl:-MTc9nVU-0NVkqOp_y87:bk8hs05) ([raw file](https://github.com/robotlocomotion/drake/blob/775fd14e2c5e6f8de3f14e7e41bd1ffbf6b064ba/multibody/fixed_fem/dev/test/matrix_utilities_test.cc#L32)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Looks good! I saw you put it in `hyperelastic_constitutive_model_test`, but did you want to add it to `matrix_utilities_test` too? Either way, I'm setting to resolved.
</blockquote></details>

Ah sorry, not sure how that happened. I have modified both tests now.

**Pull request merged**
