### PR TITLE
pydrake: Fix type bug in BasicVector::set_value for non-float types

### LINKED ISSUE #14341: pydrake: InputPort<Expression>.FixValue() expects np.ndarrays of float, but should expect object
Per discussion with @hongkai-dai, this is related to https://stackoverflow.com/questions/64617377/typeerror-set-value-incompatible-function-arguments ... where apparently the OP was actually trying to use `AutoDiffXd` (which explains why the repro in `float` didn't help us).

Here is my simple repro:
```
import pydrake.all

plant = pydrake.multibody.plant.MultibodyPlant(0)
file_name = pydrake.common.FindResourceOrThrow(
    "drake/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf")
pydrake.multibody.parsing.Parser(plant).AddModelFromFile(file_name)
plant.WeldFrames(plant.world_frame(), plant.GetFrameByName("iiwa_link_0"))
plant.Finalize()

def MakeVectorVariables(name, dim):
    return np.array([pydrake.symbolic.Variable(f"{name}{i}") for i in range(dim)])

sym_plant = plant.ToSymbolic()
tau = MakeVectorVariables("u", 7)
sym_context = sym_plant.CreateDefaultContext()
sym_plant.get_actuation_input_port().FixValue(sym_context, tau)

```
which results in 
```
TypeError                                 Traceback (most recent call last)
<ipython-input-28-d061bffd6d13> in <module>()
     15 tau = MakeVectorVariables("u", 7)
     16 sym_context = sym_plant.CreateDefaultContext()
---> 17 sym_plant.get_actuation_input_port().FixValue(sym_context, tau)
     18 q = MakeVectorVariables("q", 7)
     19 sym_plant.SetPositions(sym_context, q)

TypeError: set_value(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.common.value.Value[BasicVector_[Expression]], arg0: pydrake.systems.framework.BasicVector_[Expression]) -> None
    2. (self: pydrake.common.value.Value[BasicVector_[Expression]], value: pydrake.symbolic.Expression) -> None
    3. (self: pydrake.common.value.Value[BasicVector_[Expression]], value: numpy.ndarray[numpy.float64[m, 1]]) -> None

Invoked with: <pydrake.common.value.Value[BasicVector_[Expression]] object at 0x7f3575f48530>, array([Variable('u0', Continuous), Variable('u1', Continuous),
       Variable('u2', Continuous), Variable('u3', Continuous),
       Variable('u4', Continuous), Variable('u5', Continuous),
       Variable('u6', Continuous)], dtype=object)
```

I think 3 should read `value: numpy.ndarray[object[m, 1]]`, not `float`.

By contrast, using 
```
sym_plant.get_actuation_input_port().FixValue(sym_context, pydrake.systems.framework.BasicVector_[pydrake.symbolic.Expression](tau))
```
works.  This also works:
```
q = MakeVectorVariables("q", 7)
sym_plant.SetPositions(sym_context, q)
```
And if I inspect the `SetPositions` variant, I see
```
TypeError: SetPositions(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.multibody.plant.MultibodyPlant_[Expression], context: pydrake.systems.framework.Context_[Expression], q: numpy.ndarray[object[m, 1]]) -> None
    2. (self: pydrake.multibody.plant.MultibodyPlant_[Expression], context: pydrake.systems.framework.Context_[Expression], model_instance: pydrake.multibody.tree.ModelInstanceIndex, q: numpy.ndarray[object[m, 1]]) -> None
```

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #14341

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14343)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please
+@jwnimmer-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14343#-:-MMInPEkDyUcfcBIb8YA:b-3ggkht)* status: LGTM missing from assignees hongkai-dai,jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14343#-:-MMIoj_dCWGlEoC5d_P8:bg7igkv)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14343#-:-MMIouqZ9sU3AE3s69xf:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

**Comment by EricCousineau-TRI** [comment]
Er, CDash is the one holding up this check?
> image
> image

It's blocking on this build that already passed:
https://drake-jenkins.csail.mit.edu/job/linux-bionic-gcc-bazel-experimental-release/7382/

FYI @jamiesnape (low priority)

Gonna merge now anywho

**Comment by jwnimmer-tri** [comment]
CDash doesn't say `[Required]`, and so is not blocking.  No special bits are required to merge when in that state.

**Comment by jamiesnape** [comment]
Looks like something went awry with one of the results. Processing is asynchronous, but it is still not processed. FYI @zackgalbreath.

**Pull request merged**
