### PR TITLE
[geometry] Fix documenation issue 15743 (resolution hint)

### LINKED ISSUE #15743: Improve the documentation on resolution_hint
As discussed on slack https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1631143826024000

Currently in `AddRigidHydroelasticProperties` and `AddSoftHydroelasticProperties`, it explains `resolution_hint` as
```
If the geometry is to be tessellated, it is the parameter that guides the level of mesh refinement. See MODULE_NOT_WRITTEN_YET. This will be ignored for geometry types that don't require tessellation.
```
This documentation is not clear enough. Initially I thought the resolution here means the number of tetrahedrons on the mesh, as the screen resolution means the number of pixels on the screen. But this `resolution_hint` actually means the size of the tetrahedron. We should at least mention that the unit of `resolution_hint` is meters.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Partially fix issue #15743. After this PR merges, we'll still keep that issue open.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767)

### CODE REVIEW

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by DamrongGuoy — COMMENTED** [review]
I have followed the steps in https://drake.mit.edu/documentation_instructions.html 
The `bazel test //doc/... //doc:manual_tests` passed on my computer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjRoBKRB06X9UcB1fli:b-f37trn)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
+@hongkai-dai for feature review, please.

You can do `bazel run //doc/doxygen_cxx:build -- --serve --quick drake.geometry` for a quick check on your computer.  

This is how it looks on my computer:



> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjRoZr8Ds2VftPffT1y:b-vfb8x8)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by DamrongGuoy — COMMENTED** [review]
For the record, the `documentation` CI `@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation` passed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjTju489LAzg5Kk2FEC:b-u0082h)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd suggest that this *not* close the related issue. While units is helpful, this still doesn't actually document resolution hint. I'd like to leave the issue open to make sure that this facet of Drake-functionality is documented in a discoverable way.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjULte9-7tD0eDPWnjG:btb1iae)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @hongkai-dai)

___
*[geometry/proximity_properties.h, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15767#-MjUmP_V9UoCaVu55Jf5:-MjUmP_W2Zr7_LIlU0es:bt3dhsq) ([raw file](https://github.com/robotlocomotion/drake/blob/09c6cb79c63459976c04646c5740cbcddabcf48c/geometry/proximity_properties.h#L142)):*
> ```objc
>  @param resolution_hint       If the geometry is to be tessellated, it is the
>                               parameter that guides the level of mesh
>                               refinement. Its unit is meters.
> ```

BTW Consider being more explicit about how this affects tesselation. Something like: "That is, a smaller value results in a denser mesh."
If this is accurate you could also say something like "This has length units (in meters) and roughly corresponds to a typical edge length in the resulting mesh."

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @sherm1)

___
*[geometry/proximity_properties.h, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15767#-MjUmP_V9UoCaVu55Jf5:-MjVo0z14QUULwUw4Jab:btcdy29) ([raw file](https://github.com/robotlocomotion/drake/blob/09c6cb79c63459976c04646c5740cbcddabcf48c/geometry/proximity_properties.h#L142)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

In the spirit of same, it's worth noting that small tweaks probably won't make a big difference, but doubling and halving the value is the quickest way to observe differences.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjfuWAy6HzMdylJ4eLf:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @sherm1)

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[geometry/proximity_properties.h, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15767#-MjUmP_V9UoCaVu55Jf5:-Mjg9uvnDyo2GhNd-wS0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09c6cb79c63459976c04646c5740cbcddabcf48c/geometry/proximity_properties.h#L142)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the spirit of same, it's worth noting that small tweaks probably won't make a big difference, but doubling and halving the value is the quickest way to observe differences.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for platform review, please, per tomorrow (Thursday) schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjgACaS29PY6VnoHDMJ:b-nakupj)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767#-:-MjgBDu59d67ytYHoNbj:b-vtj4vo)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15767#-MjgAe19CCVgg8jOvX1v):*
nit Nobody will know what "issue 15743" means until they open their browser and look it up.  Don't put issue numbers in commit subject lines, just say what the change is.

https://chris.beams.io/posts/git-commit/ has some tips

For example:

```
[geometry] Clarify documentation of resolution_hint
```

... would be sufficient here.

Then, in the pull request overview, you can say "Closes #15743" to provide a citation hyperlink to the issue.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15767)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15767#-MjgAe19CCVgg8jOvX1v):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Nobody will know what "issue 15743" means until they open their browser and look it up.  Don't put issue numbers in commit subject lines, just say what the change is.

https://chris.beams.io/posts/git-commit/ has some tips

For example:

```
[geometry] Clarify documentation of resolution_hint
```

... would be sufficient here.

Then, in the pull request overview, you can say "Closes #15743" to provide a citation hyperlink to the issue.
</blockquote></details>

Thank you!  I have printed and will read Chris Beams's article.  It's very useful.

Git Question: how do I change the commit message after I push already?

**Comment by DamrongGuoy** [comment]
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15767#-MjgAe19CCVgg8jOvX1v):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thank you!  I have printed and will read Chris Beams's article.  It's very useful.

Git Question: how do I change the commit message after I push already?
</blockquote></details>

I have finished reading the article. I open my eyes!  It also has a link to [Pro Git book](https://git-scm.com/book/en/v2).
Thank you again, @jwnimmer-tri .

**Pull request merged**
