### PR TITLE
Add some missing exports_files declarations.

### PR DESCRIPTION
**Pull request by david-german-tri**
@siyuanfeng-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5864)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5864#-:-Khx0ibS7c2xEra-Bo_n:bnfp4nl)*

**Comment by david-german-tri** [comment]
Override-merging since this is coupled with other failures.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5864#-:-Khx2Q-ji89bvUgQXGOS:b-lwlc8)*

**Comment by david-german-tri** [comment]
From f2f with @siyuanfeng-tri: We think the data dependencies on these files within `QPInverseDynamicsForHumanoids/BUILD` is functioning as an implicit `exports_files`.  #5863, by removing those data dependencies, made the files disappear from Bazel's cognizance, and dependencies outside the package started breaking.  This is probably a Bazel bug.

**Comment by david-german-tri** [comment]
See https://drake-jenkins.csail.mit.edu/job/linux-gcc-bazel-experimental/3839/consoleFull from #5863:

```
13:46:46 ERROR: /home/ubuntu/workspace/linux-gcc-bazel-experimental/src/drake/examples/QPInverseDynamicsForHumanoids/system/BUILD:104:1: no such target '//drake/examples/QPInverseDynamicsForHumanoids:config/valkyrie.id_controller_config': target 'config/valkyrie.id_controller_config' not declared in package 'drake/examples/QPInverseDynamicsForHumanoids'; however, a source file of this name exists.  (Perhaps add 'exports_files(["config/valkyrie.id_controller_config"])' to drake/examples/QPInverseDynamicsForHumanoids/BUILD?) defined by /home/ubuntu/workspace/linux-gcc-bazel-experimental/src/drake/examples/QPInverseDynamicsForHumanoids/BUILD and referenced by '//drake/examples/QPInverseDynamicsForHumanoids/system:valkyrie_balancing_controller_system'.
```

**Pull request merged**
