### PR TITLE
Fix various issues with the NLopt and SNOPT solvers

### PR DESCRIPTION
**Pull request by sammy-tri**
Also includes a fix for #2176

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2243)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot test this please

**Comment by ggould-tri** [comment]
A few notes below.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/solvers/NloptSolver.cpp, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGquahfHnoAvPgqZd8D:-KGquahfHnoAvPgqZd8E:1495778414) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/NloptSolver.cpp#L102)):*
It is not at all clear to me how the logic below implements this comment.  I don't doubt that it does, but I surely don't see it.  Is it possible to clarify this at all?

---

*[drake/solvers/NloptSolver.cpp, line 171 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGqvDNEOP0QOKJzOKJm:-KGqvDNEOP0QOKJzOKJn:-900035010) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/NloptSolver.cpp#L171)):*
memset on a passed-in pointer is a bad smell, and I am slightly horrified that nlopt can't be troubled to calloc their own damn array.  Pyromaniacs, the lot of them.

Can you clarify with a comment?  At least noting explicitly that nlopt has guaranteed that whatever grad is pointing to is allocated to at least m * n * 4 but not zeroed.

---

*[drake/solvers/NloptSolver.cpp, line 258 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGqskk7-rX_HFlPATfl:-KGqskk7-rX_HFlPATfm:295445704) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/NloptSolver.cpp#L258)):*
Should this comment be a TODO?  It seems like a place where we deviate from the stated API with only implementation-level documentation, which seems sketchy.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 288 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGqyBdXOR_Q5_abMhnW:-KGqyBdYdF92xHvE4Ml6:-179634698) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/test/testOptimizationProblem.cpp#L288)):*
I believe that c4 is now unused.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 293 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGqtSHOnO9QO0Wf5bbd:-KGqtSHPuaVPYOIeWwvd:-619188995) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/test/testOptimizationProblem.cpp#L293)):*
Not really your bug, but this file is waaay past rule-of-three on `std::numeric_limits<double>::infinity()`
Feel free to wontfix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-:-KGqu0owi_nrBAliYLE8:544795560)*

**Comment by sammy-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/NloptSolver.cpp, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGquahfHnoAvPgqZd8D:-KGr1oySFev-ymQJr0Ui:675051317) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/NloptSolver.cpp#L102)):*
Attempted to clarify a bit...  realized I'm not sure how to phrase this well.

---

*[drake/solvers/NloptSolver.cpp, line 171 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGqvDNEOP0QOKJzOKJm:-KGr1n_C0VjyeJhAxGCW:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/NloptSolver.cpp#L171)):*
Done.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 288 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGqyBdXOR_Q5_abMhnW:-KGr1lcK13v3fDQ6QmdZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/test/testOptimizationProblem.cpp#L288)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2243)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/NloptSolver.cpp, line 102 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-KGquahfHnoAvPgqZd8D:-KGr2MP9WFtg9yawSW3N:-1465202614) ([raw file](https://github.com/robotlocomotion/drake/blob/47d2f6891674de178af929ce1a589e503129304c/drake/solvers/NloptSolver.cpp#L102)):*
This text is at least somewhat clearer.  If you don't have any better ideas, I think we may as well call it good enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2243#-:-KGr2Y4yJFBSR8um2-_W:1417088721)*

**Comment by jwnimmer-tri** [comment]
Ignoring drake005, as usual.  Using override-merge.

**Pull request merged**
