### PR TITLE
Fix all cpplint errors associated with runtime/string filter

### PR DESCRIPTION
**Pull request by jadecastro**
+@rpoyner-tri for feature review
+@david-german-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2789)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/CPPLINT.cfg, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-KMVOMev0yqIyEP4X3Ut:-KMVOMewEY39yWEBFsJZ:-429128092) ([raw file](https://github.com/robotlocomotion/drake/blob/eeb1ac1d13fcde8e13abf17021bebd4f2425a2d2/drake/CPPLINT.cfg#L50)):*
> ```INI
> # TODO(#2274) Fix this.
> filter=-runtime/references
> ```

nit: this blank line could also go.

---

*[drake/systems/plants/test/compareRigidBodySystems.cpp, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-KMVOcroI2Ogqo2SsBYo:-KMVOcrpBkp1NbB4FCxO:-1020632114) ([raw file](https://github.com/robotlocomotion/drake/blob/eeb1ac1d13fcde8e13abf17021bebd4f2425a2d2/drake/systems/plants/test/compareRigidBodySystems.cpp#L20)):*
> ```cpp
> namespace plants {
> namespace {
> char* model_file_1;
> ```

these should be initialized to nullptr .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
the corresponding issue is #2367.

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789)*

**Comment by liangfok** [comment]
Should the magic "Resolves #2367" be added to this PR's description?

https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by rpoyner-tri** [comment]
Looks like you just did? Anyway, :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-:-KMVxaHfP-OVz-R1GgHa:477716120)*

**Comment by jadecastro** [comment]
+@jwnimmer-tri for platform review
resolves #2367

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-:-KMVyBelsEseURNSHQEL:2085993819)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/core/functional_form.cc, line 278 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-KMVzviy4ifaFQBokTNq:-KMVzviy4ifaFQBokTNr:1248776251) ([raw file](https://github.com/robotlocomotion/drake/blob/b48056ab1514bce839181883989356054b5967ab/drake/core/functional_form.cc#L278)):*
> ```cpp
> }
> 
> static char* const kFunctionalFormNames[] = {
> ```

I think this is missing the `const` that comes before the `char*` (both are required) -- the pointers are unwritable, as are the character strings.

---

*[drake/systems/plants/test/compareRigidBodySystems.cpp, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-KMW-lENYhRoIPXkviLD:-KMW-lEOFT70HvXfXclK:-1824607581) ([raw file](https://github.com/robotlocomotion/drake/blob/b48056ab1514bce839181883989356054b5967ab/drake/systems/plants/test/compareRigidBodySystems.cpp#L20)):*
> ```cpp
> namespace plants {
> namespace {
> char* model_file_1 = nullptr;
> ```

BTW I am surprised that googlestyle dropped the rule that non-const globals must be named like `g_foo`, but I don't see that rule in the guide anymore.

---

*[drake/systems/plants/test/compareRigidBodySystems.cpp, line 77 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-KMW-I1WnXEzodH8VfKr:-KMW-I1WnXEzodH8VfKs:-1410933733) ([raw file](https://github.com/robotlocomotion/drake/blob/b48056ab1514bce839181883989356054b5967ab/drake/systems/plants/test/compareRigidBodySystems.cpp#L77)):*
> ```cpp
> }  // namespace drake
> 
> int main(int argc, char** argv) {
> ```

BTW A huge _sigh_ to non-const argv, but not your problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789)*

**Comment by jadecastro** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/core/functional_form.cc, line 278 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-KMVzviy4ifaFQBokTNq:-KMZtB0uo18x4ge2C2ji:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/64e0ac51cb7074b458b47e6008ddde9cca43a600/drake/core/functional_form.cc#L278)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I think this is missing the `const` that comes before the `char*` (both are required) -- the pointers are unwritable, as are the character strings.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2789#-:-KMZtEdB8koMF_dhGrth:1417088721)*

**Pull request merged**
