### PR TITLE
Add optional visualization debugging to IrisInConfigurationSpace

### PR DESCRIPTION
**Pull request by RussTedrake**
Also adds a more detailed explaination for the adversarial test case in ConvexConfigurationSpace. It's truly devious!

+@rhjiang for feature review (and a serious look).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19847)

### CODE REVIEW

**Review by rhjiang — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19847)* status: LGTM missing from assignee rhjiang, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Comment by rhjiang** [comment]
:LGTM:

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19847#-:-NaEaa6oAt5xkSz4DTil:b223nro)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @RussTedrake)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19847#-:-NaEhk2i3g4tabvRbAap:bzus18)* status: :shipit: complete! all discussions resolved, LGTM from assignees rhjiang,xuchenhan-tri(platform)

**Pull request merged**
