### PR TITLE
doc: Platform reviewers should merge PRs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also add checklist item for macOS on third-party version bumps.

(Both as discussed at the most recent platform review meeting.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12692)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri as on-call reviewer to begin review.  Once that's done, we'll add to the whole platform review team for review.

**Comment by jamiesnape** [comment]
FYI Running both a Catalina job and a Mojave job tends to be redundant.  They are out of sync once  though human error, but using precious resources because of one instance is not a great idea (Mac flakiness and build speed is proportional to number of builds). Maybe ping me when making suggestions about CI?

**Comment by jwnimmer-tri** [comment]
I've been running both since forever, every time I bump our workspace externals.  Is it not the case that builds can fail on one version and pass on the other?  That's often true for Ubuntu 16.04 and Ubuntu 18.04.  I guess I haven't seen them differ recently on macOS, although I thought a year or two ago they tended to diverge more.

Are the homebrew and xcode tools identical on both platforms?  So we're using almost nothing from apple except bash and the like?

**Comment by jamiesnape** [comment]
> Are the homebrew and xcode tools identical on both platforms? 

Yes, except (literally) for C++17 filesystem support (for strange historical reasons). Compilers are identical, Homebrew dependencies are all identical. Mojave even labels its SDK as 10.15 It's why we only build one set of macOS packages.

> So we're using almost nothing from apple except bash and the like?

bash and zlib technically. Being Apple, they are old versions and neither change much.

**Comment by jwnimmer-tri** [comment]
Ok -- so in the particular case of catalina and mojave they are identical within epsilon, but in general the SDK could differ.  So for now we should advise just one, and ask you when we upgrade if we'll need just one or both?

**Comment by jamiesnape** [comment]
Yes, exactly.

**Pull request merged**
