### PR TITLE
Tidy up tools files' commenting and docs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4671)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri feature, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-:-K_deTQEgAE_euRicnoh:bcrgn7)*

**Comment by rpoyner-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/fcl.BUILD, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-K_dwd619zUcegVSA0Ed:-K_dwd619zUcegVSA0Ee:b-vcknsi) ([raw file](https://github.com/robotlocomotion/drake/blob/583cf14559d9da30fa7bbe5d43d407dc2c5e1791/tools/fcl.BUILD#L54)):*
> ```
>         "echo '$(SRCS)' | tr ' ' '\\n' | " +
>         "sed 's|.*include/\(.*\)|#include \\\"\\1\\\"|g'"
>     ) + ") > '$@'",
> ```

BTW, curious what the rationale was for this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671)*

**Comment by jwnimmer-tri** [comment]
*[tools/fcl.BUILD, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-K_dwd619zUcegVSA0Ed:-K_dxDYPt9tkAleBY80K:b66wvln) ([raw file](https://github.com/robotlocomotion/drake/blob/583cf14559d9da30fa7bbe5d43d407dc2c5e1791/tools/fcl.BUILD#L54)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, curious what the rationale was for this change.
</blockquote></details>

Buildifier is the One True God, and it doesn't preserve raw strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-:-K_e-vPdO6mt4pu8TUPE:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri platform, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-:-K_e181itdjXJ3vNxp7x:b-iukek4)*

**Comment by jwnimmer-tri** [comment]
-@sammy-tri +@ggould-tri platform.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-:-K_e6wEIgMHONkD4T7jB:b-sebcbp)*

**Comment by ggould-tri** [comment]
:lgtm:, with sadness.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/fcl.BUILD, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-K_dwd619zUcegVSA0Ed:-K_eFORwOJKwUj_VnQm2:blx6w51) ([raw file](https://github.com/robotlocomotion/drake/blob/583cf14559d9da30fa7bbe5d43d407dc2c5e1791/tools/fcl.BUILD#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Buildifier is the One True God, and it doesn't preserve raw strings.
</blockquote></details>

Ugh.  If ever there was a case for raw strings, this is it.  Leaning-toothpick syndrome galore.  Is this expected to be fixed in the future?

Leaving as "satisfied" because I don't think this is quite offensive enough to be defective.  But gosh do I hate it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-:-K_eFsMv5oukST-K33e5:b-f5m6ga)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tools/fcl.BUILD, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4671#-K_dwd619zUcegVSA0Ed:-K_eGiIVVna7Z5oEB2I0:b5n5fow) ([raw file](https://github.com/robotlocomotion/drake/blob/583cf14559d9da30fa7bbe5d43d407dc2c5e1791/tools/fcl.BUILD#L54)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Ugh.  If ever there was a case for raw strings, this is it.  Leaning-toothpick syndrome galore.  Is this expected to be fixed in the future?

Leaving as "satisfied" because I don't think this is quite offensive enough to be defective.  But gosh do I hate it.
</blockquote></details>

No idea.  I will file an issue upstream.  It's open-source and we have CLA blessing, so we could also fix it ourselves.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4671)*

**Comment by jwnimmer-tri** [comment]
Filed as bazelbuild/buildifier#33.

**Pull request merged**
