### PR TITLE
Port more files to use drake_add_cc_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Following up on the work in #3634 and #3633.

This one contains a few more boilerplate fixes that I'd missed earlier, as well as three renames (so that the source basename matches the target name).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3651)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3651#-:-KTAD2woaxuANwrE97Q4:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@david-german-tri (platform)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3651#-:-KTADM0a5a_zSeIEKI2O:bqt3m3b)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3651#-:-KTADdTxNutLCtZUyktC:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Just waiting on matlab now.  This should merged once it's green (blue).

**Pull request merged**
