### PR TITLE
Implement DrealSolver::Solve()

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916)

### CODE REVIEW

**Comment by soonho-tri** [comment]
FYI,

1. The contents of `Extract*Constraint` and `Extract*Cost` functions will be taken out and used to implement the symbolic `Eval` functions in `Constraint` and `Cost` class.

2. `DrealSolver::Solve` does not support the following cases:
 - `PSD` constraint
 - `LMI` constraint
 - Multiple cost functions
 - `GenericConstraint` which is not of `ExpressionConstraint`
 - `GenericCost`

+@hongkai-dai for feature-review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916#-:-LDweffPAMhwpXShiQkg:b-9q9p9j)*

**Comment by soonho-tri** [comment]
> In MathematicalProgram, we should add the call to dReal::Solve in https://github.com/RobotLocomotion/drake/blob/master/solvers/mathematical_program.cc#L853~L904

Sure, I'll do that in another PR.

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/dreal_solver.cc, line 691 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAfVbyBypcs2GD1z-a:-LEAnk2s-0fDaDZES156:bo75xm8) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L691)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

So if I have two quadratic costs, `c1 = 0.5x'Q1x + b1'x` and `c2 = 0.5 x'Q2x + b2'x`, the summation of `c1` and `c2` is still a quadratic cost, but we will not handle it here? In `MathematicalProgram`, the `cost` is treated as the summation of each individual cost, there is not priority between different cost objects.
</blockquote></details>

This is something I wanted to clarify. In general, if we have `N` cost functions, `c_1`, ... `c_n`, what is our current interpretation of them? Is it we minimize `\Sum c_i`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916#-:-LEAnTic3PHJhf-pJaKM:b-9kvasc)*

**Comment by hongkai-dai** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/dreal_solver.cc, line 691 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAfVbyBypcs2GD1z-a:-LEAr3u22NXWmIly2W6n:b-tb361h) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L691)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

This is something I wanted to clarify. In general, if we have `N` cost functions, `c_1`, ... `c_n`, what is our current interpretation of them? Is it we minimize `\Sum c_i`?
</blockquote></details>

Yes, that is exactly right, it is treated as `sum c_i`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916)*

**Comment by jwnimmer-tri** [comment]
LGTM so far.

> ... Sure, I'll do that in another PR.

FYI When you do so, you will also need to add the ability to disable dReal in the Bazel build (see IPOPT, NLOPT, etc.).  Note that this is slightly difficult right now because `solvers/dreal_solver.h` includes the `Interval` type directly in its header.  (Most `solvers/foo_solver.h` hide all implementation details from their users.)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/BUILD.bazel, line 908 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAyMMd19VVHoRQJsG3:-LEAyMMd19VVHoRQJsG4:b-286u5k) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/BUILD.bazel#L908)):*
> ```Python
>         ":generic_trivial_constraint",
>         ":generic_trivial_cost",
>         ":mathematical_program",
> ```

If your goal is to add `:dreal_solver` as a dependency of `:mathematical_program`, then this is going to have to be just `:mathematical_program_api` instead of the full component.

---

*[solvers/constraint.h, line 809 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAvmqG0h5JnQ-9kxn8:-LEAvmqG0h5JnQ-9kxn9:b8itdku) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/constraint.h#L809)):*
> ```objc
>   const VectorX<symbolic::Expression>& expressions() const {
>     return expressions_;
>   }
> ```

This probably deserves a unit test; `testExpressionConstraint` seems to only look at the numerical gradients, as opposed to the correctness of the symbolic form?

---

*[solvers/dreal_solver.h, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAuqar-tHB8N1c2U-2:-LEAuqar-tHB8N1c2U-3:b92qbvy) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.h#L59)):*
> ```objc
>                                         const symbolic::Formula& constraint,
>                                         double delta,
>                                         bool use_local_optimization);
> ```

FYI Boolean configuration options quickly get stale and confusing at call sites.  Consider a named class enum instead, as a kindness to readers of this methods' call sites.  (A struct with named fields is another possible solution, and would lend itself to a "ParseAllOptions" helper that converted MP string options to a single uniform struct with all options.)

---

*[solvers/dreal_solver.cc, line 561 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEB-vui6xSHEbjKcgSg:-LEB-vui6xSHEbjKcgSh:beji0af) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L561)):*
> ```cpp
>     f = f && (z(0) >= 0) && (z(1) >= 0);
>     // z₀ * z₁ ≥ ∑ zᵢ² (for i ∈ [2, n-1])
>     symbolic::Expression squaredNorm;
> ```

What is this variable for?

---

*[solvers/dreal_solver.cc, line 688 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEB1Gbp7t6m5hrmMKqq:-LEB1Gbp7t6m5hrmMKqr:btlszxs) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L688)):*
> ```cpp
>   if (costs.size() == 0) {
>     // No cost functions in the problem. Call Checksatisfiability.
>     result = CheckSatisfiability(constraints, precision /* Read it from MP */);
> ```

Unclear what `Read it from MP` is trying to tell me.

---

*[solvers/dreal_solver.cc, line 708 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEB1kUyBGKiRR0_jg4A:-LEB1kUyBGKiRR0_jg4B:b4czau0) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L708)):*
> ```cpp
>       const symbolic::Variable& var{item.first};
>       const double v{item.second.mid()};
>       solution_vector(prog.FindDecisionVariableIndex(var)) = v;
> ```

BTW Prefer `[]` for Eigen array accesses?  This stumped me for a while.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916#-:-LEAuC3x6aIMjGklPToC:b-3zvn0d)*

**Comment by soonho-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[solvers/BUILD.bazel, line 908 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAyMMd19VVHoRQJsG3:-LEJ1zlm9w3leipI0WDK:b-3zqzvu) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/BUILD.bazel#L908)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If your goal is to add `:dreal_solver` as a dependency of `:mathematical_program`, then this is going to have to be just `:mathematical_program_api` instead of the full component.
</blockquote></details>

FYI, this is a part of `dreal_solver_test` target.

`dreal_solver` target does only have `:mathematical_program_api` dependency instead of the full `:mathematical_program`:

```python
drake_cc_library(
    name = "dreal_solver",
    srcs = [
        "dreal_solver.cc",
        "dreal_solver_common.cc",
    ],
    hdrs = ["dreal_solver.h"],
    deps = [
        ":mathematical_program_api",
        "//common:essential",
        "@dreal",
    ],
)
```

I think this is good as it is?

---

*[solvers/constraint.h, line 806 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LDxOS1b8_2NBTKPoJRF:-LEJ28_0CvzziqE1AykX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/constraint.h#L806)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this only returns the symbolic expression, but not the constraint? Namely
`x(1) + x(2) <= 2` is a  constraint, but this function only returns `x(1) + x(2)`.
</blockquote></details>

Done.

---

*[solvers/constraint.h, line 809 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAvmqG0h5JnQ-9kxn8:-LEJ3ASJ7hC3Ain_ZtYV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/constraint.h#L809)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This probably deserves a unit test; `testExpressionConstraint` seems to only look at the numerical gradients, as opposed to the correctness of the symbolic form?
</blockquote></details>

Done.

---

*[solvers/dreal_solver.h, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAuqar-tHB8N1c2U-2:-LELfPDn5kp9P6Qy-g7H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.h#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Boolean configuration options quickly get stale and confusing at call sites.  Consider a named class enum instead, as a kindness to readers of this methods' call sites.  (A struct with named fields is another possible solution, and would lend itself to a "ParseAllOptions" helper that converted MP string options to a single uniform struct with all options.)
</blockquote></details>

Done.

---

*[solvers/dreal_solver.cc, line 425 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LDxQfLN4OJcfnqt9-Bf:-LEKu1f-2oA7xBuehgKp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L425)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is `precision` the only double option we need in dReal? If in the future we need more options, I think we should refactor this method to
```C++
double GetDoubleOption(MathematicalProgram* const prog, const std::string& option_name, const double option_default_value);
```
</blockquote></details>

Done.

---

*[solvers/dreal_solver.cc, line 561 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEB-vui6xSHEbjKcgSg:-LEJ3PRz0xfs7oeLmq1F:b2ar3so) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L561)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What is this variable for?
</blockquote></details>

Done. (removed)

---

*[solvers/dreal_solver.cc, line 688 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEB1Gbp7t6m5hrmMKqq:-LEJ3VeODFko0ImDD4YE:b2ar3so) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L688)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear what `Read it from MP` is trying to tell me.
</blockquote></details>

Done. (removed)

---

*[solvers/dreal_solver.cc, line 691 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEAfVbyBypcs2GD1z-a:-LEKt1qz5uwcsgATOSE-:b-nxu5sk) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L691)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, that is exactly right, it is treated as `sum c_i`
</blockquote></details>

Done. (test is updated!)

---

*[solvers/dreal_solver.cc, line 708 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LEB1kUyBGKiRR0_jg4A:-LEJ3k540r3e8b7BQanb:b2ar3so) ([raw file](https://github.com/robotlocomotion/drake/blob/64f5b716ccea61e996bb13b762094c6b06839afd/solvers/dreal_solver.cc#L708)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Prefer `[]` for Eigen array accesses?  This stumped me for a while.
</blockquote></details>

Done. (removed)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/dreal_solver.cc, line 686 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LELhmp-94kFUd4S7UFx:-LELhmp0166fqirDi2ML:bparo3) ([raw file](https://github.com/robotlocomotion/drake/blob/2a42adfd6718da54ae1b22ef4f81da63e7a166df/solvers/dreal_solver.cc#L686)):*
> ```cpp
>       GetDoubleOption(&prog, "precision", 0.001 /* default */)};
>   const LocalOptimization local_optimization{
>       GetIntOption(&prog, "use_local_optimization", 1.0 /* default */) > 0
> ```

Should the default be `1.0` or `1`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916#-:-LELhsTbA8nWJSDfEPOe:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/dreal_solver.cc, line 686 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8916#-LELhmp-94kFUd4S7UFx:-LELiLWeA0bW1Upi_bja:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a42adfd6718da54ae1b22ef4f81da63e7a166df/solvers/dreal_solver.cc#L686)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should the default be `1.0` or `1`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8916)*

**Pull request merged**
