### PR TITLE
Add abstract parameter methods to LeafSystem.

### PR DESCRIPTION
**Pull request by avalenzu**
This PR adds methods analogous to those already present for numeric parameters.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7810)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@jwnimmer-tri for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-:-L3EZX3UpbiMgT448u-i:b-1tks9q)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/framework/leaf_system.h, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-L3F2aCPunlStH61lFIm:-L3F2aCPunlStH61lFIn:b8xiju4) ([raw file](https://github.com/robotlocomotion/drake/blob/a8e08ed87b6038907e6ba8bf6e7f7078f3183ab0/systems/framework/leaf_system.h#L185)):*
> ```objc
>   /// given to DeclareNumericParameter, or else if no model was provided sets
>   /// the numeric parameter to one.  It makes no attempt to set abstract
>   /// parameter values.  Overrides must not change the number of parameters.
> ```

Should this be resetting the abstract parameters?

---

*[systems/framework/leaf_system.h, line 574 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-L3F2fSdJ6TbwhLoHgSo:-L3F2fSeJMkTPM4WfdnI:b-aawuvv) ([raw file](https://github.com/robotlocomotion/drake/blob/a8e08ed87b6038907e6ba8bf6e7f7078f3183ab0/systems/framework/leaf_system.h#L574)):*
> ... the default implementation of SetDefaultParameters() will reset parameters to their model values ...

This doesn't seem to be true.  Either the discussion ~L191 should be resolved by resetting abstract, or this comment should be changed (to explicitly say that they are _not_ reset defaults).

---

*[systems/framework/leaf_system.h, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-L3F3QvYG7LvNN2ZvZNx:-L3F3QvYG7LvNN2ZvZNy:bsevjot) ([raw file](https://github.com/robotlocomotion/drake/blob/a8e08ed87b6038907e6ba8bf6e7f7078f3183ab0/systems/framework/leaf_system.h#L583)):*
> ```objc
>   /// Extracts the abstract parameter from the @p context at @p index.  Asserts
>   /// if the context is not a LeafContext, or if it does not have an
>   /// abstract-valued parameter @p index.
> ```

BTW "Asserts" is not exactly precise (the cast will throw, not assert).   I guess I'm not sure if it matters, though.

---

*[systems/framework/leaf_system.h, line 587 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-L3F3qSwd7yTcB08PxQa:-L3F3qSwd7yTcB08PxQb:b-1i8av1) ([raw file](https://github.com/robotlocomotion/drake/blob/a8e08ed87b6038907e6ba8bf6e7f7078f3183ab0/systems/framework/leaf_system.h#L587)):*
> ```objc
>                                             int index) const {
>     const auto& leaf_context =
>         dynamic_cast<const systems::LeafContext<T>&>(context);
> ```

The LeafSystem downcasts are residue from when _only_ leaf contexts had parameters; now that Context itself has (virtual methods for) parameters, probably we can lose the cast?  (Here, and other related places in this file.)

(Possibly these methods are not useful in that case, anyway, and should be dropped?  They seem a bit indirect for no gain.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7810)*

**Comment by jwnimmer-tri** [comment]
First pass complete.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[systems/framework/test/leaf_system_test.cc, line 338 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-L3FDuD-mJizYaG3PlY8:-L3FDuD-mJizYaG3PlY9:b-bn956a) ([raw file](https://github.com/robotlocomotion/drake/blob/a8e08ed87b6038907e6ba8bf6e7f7078f3183ab0/systems/framework/test/leaf_system_test.cc#L338)):*
> ```cpp
>           .GetMutableValueOrThrow<std::string>();
>   mutable_param = "modified parameter value";
>   EXPECT_EQ("modified parameter value", mutable_param);
> ```

BTW Shouldn't this test that `param` has the new value, not `mutable_param`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-:-L3FE3IJz5IckOLi4VtX:bvb1a6z)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@EricCousineau-TRI for platform review please.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-:-L3UGU8pzcHApVFPlY7U:b-fbtslv)*

**Comment by EricCousineau-TRI** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7810#-:-L3UISBdW99BpXC_j-qO:b-uwkowd)*

**Pull request merged**
