### PR TITLE
Modify diagram builder error message on algebraic loops

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Changes the error message broadcast when detecting an algebraic loop. The loop is now described.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7564)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@ggould-tri  for feature review, please

Resolves #7557

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-bpTzpYNr-8a5Rrq8b:b-nzwgfd)*

**Comment by ggould-tri** [comment]
:lgtm:, one nit below.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/diagram_builder.h, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-L-c5orOk34SOmPtjvvc:-L-c5orOk34SOmPtjvvd:b-y298d6) ([raw file](https://github.com/robotlocomotion/drake/blob/a4a8b81a2b15320607b1449d6cad6dc52db9fe32/drake/systems/framework/diagram_builder.h#L224)):*
> ```objc
>     visited->insert(n);
> 
>     auto IsInStack = [](const auto& vector, const auto& value) {
> ```

Why not just use std::find?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-c69lMEtMYOFgvRR0d:b-8s5gvx)*

**Comment by SeanCurtis-TRI** [comment]
Done

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram_builder.h, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-L-c5orOk34SOmPtjvvc:-L-cLXyBf7_PbskhHPBV:bhxqf0i) ([raw file](https://github.com/robotlocomotion/drake/blob/a4a8b81a2b15320607b1449d6cad6dc52db9fe32/drake/systems/framework/diagram_builder.h#L224)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Why not just use std::find?
</blockquote></details>

Done Foolish obstinacy against long lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-cLWYxehqsaS3FJR1i:bb6un1j)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything  please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-d8EuWKzOLSCV47Tgb:bqgbao5)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-d8lXWd-9eGPfBiyF-:b-trwh5h)*

**Comment by SeanCurtis-TRI** [comment]
Copy and pasted introduced an error.  Siiiigh. This time for real.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-dGLY4zi-ENGVfxysl:b-8hxc68)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564)*

**Comment by SeanCurtis-TRI** [comment]
@ggould-tri Would you be content for this to be feature and platform review?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-dPbnUjjIC9GenL2LM:b-lyr79b)*

**Comment by ggould-tri** [comment]
:shipit:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7564#-:-L-jJ6jRQEEW5GK6yaB_:bizlbik)*

**Pull request merged**
