### PR TITLE
Add DeformableContactInfo to ContactResults

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #20274

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NfrdFN8DM3wmVCJ4LTL:brbsdox)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by xuchenhan-tri — COMMENTED** [review]
+(priority: medium) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NfvVO8d6ln9eUm6LNRj:bchicoo)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-Ng0nhus1NW9_uRPbv2W:bg7igkv)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/contact_results.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0l9Kf8d96swG3zAPC:-Ng0l9Kf8d96swG3zAPD:b2kx0v5) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/contact_results.h#L57)):*
> ```objc
>   /** Retrieves the ith PointPairContactInfo instance. The input index i
>    must be in the range [0, `num_point_pair_contacts()`) or this method
>    aborts. */
> ```

this and method below now throw per your changes in the cc file.



_Suggestion:_
```objc
   must be in the range [0, `num_point_pair_contacts()`) or this method
   throws. */
```
___
*[`multibody/plant/deformable_contact_info.h` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0lMt_7NLf0L-M9dGD:-Ng0lMt_7NLf0L-M9dGE:bb7lc54) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L17)):*
> ```objc
> 
> /** A class containing information regarding contact and contact response
>  between two geometries belonging to a pair of bodies with at least one of which
> ```

nit,



_Suggestion:_
```objc
one of them
```
___
*[`multibody/plant/deformable_contact_info.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0lv4o4p7hYtzYilfE:-Ng0lv4p2T5aCrI-NbSp:b-itj0x9) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L37)):*
> ```objc
> 
>   /** Constructs a %DeformableContactInfo.
>    @param[in] id_A The geometry id of the geometry A.
> ```

question, is it required for id_A to correspond to a deformable geometry? or are these swaped at construciton if A is rigid and B is deformable?
___
*[`multibody/plant/deformable_contact_info.h` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0lhSE9mBjZnl7Z_K_:-Ng0lhSE9mBjZnl7Z_Ka:b-9ecf74) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L49)):*
> ```objc
>       geometry::GeometryId id_A, geometry::GeometryId id_B,
>       geometry::PolygonSurfaceMesh<T> contact_mesh_W,
>       const SpatialForce<T>& F_Ac_W,
> ```

nit, might as well pass by copy F_Ac_W?
___
*[`multibody/plant/deformable_contact_info.h` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0m94M0NkP28Pqt65B:-Ng0m94M0NkP28Pqt65C:bx7bvbv) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L70)):*
> ```objc
> 
>   /** Gets the contact point data, including tractions and slip velocities, at
>    each contact point. Ordered the same way as the faces of contact_mesh()`. */
> ```

so there is a point per contact face? at the centroid? maybe add this to these docs?
___
*[`multibody/plant/deformable_contact_info.cc` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0mRNRDRbIBjRq5kpt:-Ng0mRNRDRbIBjRq5kpu:b-1oi7ep) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.cc#L14)):*
> ```cpp
>     const SpatialForce<T>& F_Ac_W,
>     std::vector<DeformableContactPointData<T>> contact_point_data)
>     : id_A_(id_A),
> ```

not sure who enforces the invariant that A always correspond to the deformable gometry?
SHould this be a precondition in the constructor or somehow be checked?

**Review by xuchenhan-tri — COMMENTED** [review]
Comments addressed. PTAL, thanks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgMWKguCzJSsoyYhlTg:b-pr0h6k)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/plant/contact_results.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0l9Kf8d96swG3zAPC:-NgMVQKH09bn6yQ0gBx2:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/contact_results.h#L57)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this and method below now throw per your changes in the cc file.
</blockquote></details>

Done
___
*[`multibody/plant/deformable_contact_info.h` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0lMt_7NLf0L-M9dGD:-NgMVUGz8XIp_eYj-Ope:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit,
</blockquote></details>

Done
___
*[`multibody/plant/deformable_contact_info.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0lv4o4p7hYtzYilfE:-NgMVvDW1nXLMCprq7LO:b-ni2wx7) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L37)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

question, is it required for id_A to correspond to a deformable geometry? or are these swaped at construciton if A is rigid and B is deformable?
</blockquote></details>

Yes, A is required to be deformable. This class has no way of enforcing that pre-condition.
___
*[`multibody/plant/deformable_contact_info.h` line 49 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0lhSE9mBjZnl7Z_K_:-NgMVzYBDWEiMfAA74JU:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, might as well pass by copy F_Ac_W?
</blockquote></details>

Done
___
*[`multibody/plant/deformable_contact_info.h` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0m94M0NkP28Pqt65B:-NgMWCCg9LP_rKUyTeCW:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.h#L70)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

so there is a point per contact face? at the centroid? maybe add this to these docs?
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_contact_info.cc` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-Ng0mRNRDRbIBjRq5kpt:-NgMWFJ15hIMu223QMOw:bsz8kce) ([raw file](https://github.com/RobotLocomotion/drake/blob/b312f9c26c5a7ddec0f92f8da606cc2249b6abcf/multibody/plant/deformable_contact_info.cc#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not sure who enforces the invariant that A always correspond to the deformable gometry?
SHould this be a precondition in the constructor or somehow be checked?
</blockquote></details>

Done, added a precondition in the constructor

**Review by amcastro-tri — COMMENTED** [review]
+@rpoyner-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgQCuE_5nsOZyw48hut:bl5eq21)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: none) +(release notes: feature) Looks to me like this *adds* public api at the very least. Still pondering whether there might be breaking changes.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgQUnoc9BxFLPOwi3AV:bszu7ck)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
I'm not sure if the newly added public api falls under the umbrella for not mentioning deformable in the release notes, but I'm happy to yield to the release manager.

I don't see the breaking change though. Could you elaborate?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgQVIJe2MWtjL-Ay0qI:b-b1n0oj)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
I had forgotten about the escape clause for deformable, so that covers some of it. What concerned me (and perhaps is fine) was the changes to documentation to other methods in contact_results.h. If that is just updating documentation that was already stale, or some such, then fine. I'll change the relnotes tag back if I am satisified with the 'none' designation.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgQgJGTAZqIhGp3MvFV:bmn5mzo)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
Re-read and agree with -(release notes: feature) +(release notes: none) .

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgQh2SK6jWphraTDcHT:b-hqkuk0)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20301#-:-NgQljhP7HNQFw3cyyrJ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri

**Pull request merged**
