### PR TITLE
Remove expensive findElement + dynamic_cast from RBT collision methods

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR takes some basic proposals from PR #2299 (which was reverted after some Atlas tests with Gurobi failing). The objective are:

- To avoid calls to [`Model::readElement`](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/collision/Model.cpp#L20) (O(N) worst case).
- As [commented in this PR review](https://reviewable.io/reviews/robotlocomotion/drake/2596#-KKjkvhxchyPGL32YKo1), eliminate unnecessarily expensive `dynamic_cast`'s used within `RigidBodyTree`, see [here for instance](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBodyTree.cpp#L486).

To accomplish this this PR essentially:

- Adds `Element*` members to `PointPair` so that they are available to avoid the `readElement` calls.
- Moves `RigidBody::CollisionElement::body` to `DrakeCollision::Element::body_` (as previously done in the reverted PR #2299, this solution had been accepted). In this way `dynamic_cast`'s are eliminated.

I assigned high priority to this since PR #2596 depends on this and these are needed to have concave dispatch working.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2607)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@david-german-tri for platform review.
+@sherm1 for feature review.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKnnkhlZZR6TH8lH63w:1458147505)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 217 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKnnwfNg9Fg6Vv031jC:-KKnnwfNg9Fg6Vv031jD:-669387322) ([raw file](https://github.com/robotlocomotion/drake/blob/0d14a0438eb432a070ecfd58c9b3f6237385afe7/drake/systems/plants/RigidBody.h#L217)):*
> ```objc
> 
>    private:
>     const RigidBody* const body;
> ```

This member is now moved to `DrakeCollision::Element`.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 411 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKnoPwhgbJL0gR5raFP:-KKnoPwiyjNI8BauPnDE:-847256479) ([raw file](https://github.com/robotlocomotion/drake/blob/815146873f8193cf12438482d25f6dfd2869ed8d/drake/systems/plants/RigidBodyTree.cpp#L411)):*
> ```cpp
>     normal.col(i) = n;
>     phi[i] = distance;
>     const DrakeCollision::Element* elementB = closest_points[i].get_elementB();
> ```

Notice how previous `dynamic_cast` + `readElement` get simplified to a one-liner.

---

*[drake/systems/plants/collision/bullet_model.cc, line 323 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKnobgZqs_sucpQSkuk:-KKnobgZqs_sucpQSkul:10065039) ([raw file](https://github.com/robotlocomotion/drake/blob/815146873f8193cf12438482d25f6dfd2869ed8d/drake/systems/plants/collision/bullet_model.cc#L323)):*
> ```cpp
> 
>       point_pairs.push_back(
>           PointPair(elements[idA].get(), elements[idB].get(),
> ```

`PointPair` now holds pointers to the participating `Element`'s in addition to just an (integer) id.

---

*[drake/systems/plants/collision/Element.h, line 65 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKno3jEY2DuX252UHOP:-KKno3jEY2DuX252UHOQ:1620434583) ([raw file](https://github.com/robotlocomotion/drake/blob/815146873f8193cf12438482d25f6dfd2869ed8d/drake/systems/plants/collision/Element.h#L65)):*
> ```objc
>   ElementId id;
>   const RigidBody* body_{};
> ```

This was removed from `RigidBody::CollisionElement` into here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by amcastro-tri** [comment]
retest this please

**Comment by sherm1** [comment]
Feature review: A few minor comments.

---

Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/collision/bullet_model.cc, line 323 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKodZ9uD5TAh3mqF7eG:-KKodZ9uD5TAh3mqF7eH:-630154607) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/bullet_model.cc#L323)):*
> ```cpp
> 
>       point_pairs.push_back(
>           PointPair(elements[idA].get(), elements[idB].get(),
> ```

Should use emplace_back here to avoid copy:
`point_pairs.emplace_back(elements[idA].get(),elements[idB].get() ...`

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKoe62PFcnA5aWNW3uQ:-KKoe62PFcnA5aWNW3uR:1467753446) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/Element.cpp#L22)):*
> ```cpp
> Element::Element(const Element& other)
>     : DrakeShapes::Element(other),
>       id((ElementId) this),
> ```

This should be a `reinterpret_cast`.

---

*[drake/systems/plants/collision/point_pair.h, line 69 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKof8oxtuSADoPe1NLc:-KKof8oxtuSADoPe1NLd:2141895038) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/point_pair.h#L69)):*
> ```objc
>   Eigen::Vector3d ptB_;
>   Eigen::Vector3d normal_;
>   double distance_;
> ```

needs member initialization

---

*[drake/systems/plants/collision/ResultCollector.h, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKofgWc7K25lk6yGPCf:-KKofgWc7K25lk6yGPCg:-961838772) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/ResultCollector.h#L17)):*
> ```objc
>                        const Eigen::Vector3d& normal,
>                        const double distance) {
>     pts.push_back(PointPair(elementA, elementB, ptA, ptB, normal, distance));
> ```

emplace_back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKofsQtBR1MRZC2oHXE:586162107)*

**Comment by amcastro-tri** [comment]
Addressed reviews. PTAL

---

Review status: 5 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/collision/bullet_model.cc, line 323 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKodZ9uD5TAh3mqF7eG:-KKsOw7GBz6X7KonJnby:-375229993) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/bullet_model.cc#L323)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should use emplace_back here to avoid copy:
> `point_pairs.emplace_back(elements[idA].get(),elements[idB].get() ...`
</details>
there is a `void push_back (value_type&& val)`. How much different do you think the performance would be in a case like this? do you think RVO won't be smart enough in this case?
I did however change to emplace_back. I just want to understand in what cases I should expect RVO not to do a good job.

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKoe62PFcnA5aWNW3uQ:-KKsQqcaM84ix6oAiNRf:197359225) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/Element.cpp#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This should be a `reinterpret_cast`.
</details>
Done. I should get rid of these id.... or at least this way of initializing them

---

*[drake/systems/plants/collision/point_pair.h, line 69 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKof8oxtuSADoPe1NLc:-KKsR5ubyvRZSfhse8I4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/point_pair.h#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> needs member initialization
</details>
Done.

---

*[drake/systems/plants/collision/ResultCollector.h, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKofgWc7K25lk6yGPCf:-KKsRICL2l68o1sKjQtk:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/ResultCollector.h#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> emplace_back
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKsSQc85CQGNGc3MDpl:1927942442)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/collision/bullet_model.cc, line 323 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKodZ9uD5TAh3mqF7eG:-KKsm3zXB9vowjLAWEKX:-590356034) ([raw file](https://github.com/robotlocomotion/drake/blob/fe2237a989af19af163f90bf2e45b844523e7be3/drake/systems/plants/collision/bullet_model.cc#L323)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> there is a `void push_back (value_type&& val)`. How much different do you think the performance would be in a case like this? do you think RVO won't be smart enough in this case?
> I did however change to emplace_back. I just want to understand in what cases I should expect RVO not to do a good job.
</details>
OK, I think you're right that this won't have a performance cost since presumably PointPair's move constructor is inline so will get optimized away. This isn't a return value though, so RVO doesn't apply -- if the move constructor is logically being called it would have to actually get called here if it had any side effects. I think it is a good habit to use `emplace_back` to avoid potential expense but it should be author's choice here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKsnNjeqqmcMont406p:1417088721)*

**Comment by sherm1** [comment]
This PR has conflicts that need to be resolved. Also, @amcastro-tri I think some of your own Reviewable comments are preventing completion.

**Comment by amcastro-tri** [comment]
Reviewed 1 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r1, 4 of 5 files at r3, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKtTl8iI9s5j1_rLeU6:1417088721)*

**Comment by sherm1** [comment]
This still needs a platform review.

**Comment by david-german-tri** [comment]
Looking now.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r1, 3 of 5 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/collision/bullet_model.cc, line 273 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtv_8vX428mhRhWoS7:-KKtv_8vX428mhRhWoS8:1267178228) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/bullet_model.cc#L273)):*
> ```cpp
>   bt_world.bt_collision_configuration.setPlaneConvexMultipointIterations(
>       kPerturbationIterations, kMinimumPointsPerturbationThreshold);
>   std::vector<PointPair> point_pairs;
> ```

BTW, is BulletResultCollector now dead code?  If so, :+1: - please delete it in this PR or a followup!

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtrFNCbEyC1EBPPA6g:-KKtrFNCbEyC1EBPPA6h:-1360839277) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.cpp#L22)):*
> ```cpp
> Element::Element(const Element& other)
>     : DrakeShapes::Element(other),
>       id(reinterpret_cast<ElementId>(this)),
> ```

BTW, is this PR a step towards deleting `ElementId` altogether?  That would be great!

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtu2nOyw23hWlBKzff:-KKtu2nPHs3yd6EUPxHl:-449355371) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.cpp#L22)):*
> ```cpp
> Element::Element(const Element& other)
>     : DrakeShapes::Element(other),
>       id(reinterpret_cast<ElementId>(this)),
> ```

does `static_cast` not suffice?

---

*[drake/systems/plants/collision/Element.h, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpzuAn7yxMWK0R5RT:-KKtpzuAn7yxMWK0R5RU:1746732774) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L17)):*
> ```objc
> // It is however useful for the concept of having a CollisionElement attached
> // to a Body.
> class RigidBody;
> ```

BTW, the style guide discourages but does not prohibit forward declarations.  I think this particular one is OK - in fact, I'm working towards fwd-decl of `RigidBody` in a bunch of other places to cut compilation time.  But in general, you should `#include` even if you're not using the interface.

https://google.github.io/styleguide/cppguide.html#Forward_Declarations

You might want to consider deleting the comment.  Up to you.

---

*[drake/systems/plants/collision/Element.h, line 48 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpiZsQWuvXd6IsyeS:-KKtpiZsQWuvXd6IsyeT:1479020185) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L48)):*
> ```objc
>   /** Returns a pointer to the const RigidBody to which this CollisionElement
>   is attached. **/
>   const RigidBody* const get_body() const;
> ```

The second of the three `const`s here is superfluous, and I think will actually fail to compile post https://github.com/RobotLocomotion/drake/pull/2618.

---

*[drake/systems/plants/collision/Element.h, line 50 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpTtaOKW_EzilNF3F:-KKtpTtaOKW_EzilNF3G:199988405) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L50)):*
> ```objc
>   const RigidBody* const get_body() const;
> 
>   /** Set the rigid body this collision element is attached to. **/
> ```

BTW: "Sets"

---

*[drake/systems/plants/collision/Element.h, line 51 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtsO6f4oRVCbyY-GLp:-KKtsO6f4oRVCbyY-GLq:-750388622) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L51)):*
> ```objc
> 
>   /** Set the rigid body this collision element is attached to. **/
>   void set_rigid_body(const RigidBody* body);
> ```

Does it make sense for this to change after construction time?  If not, consider getting rid of this setter, and making the RigidBody* a constructor argument.

---

*[drake/systems/plants/collision/Element.h, line 64 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtsd0GQhUcxWFwBMDR:-KKtsd0GQhUcxWFwBMDS:1344435956) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L64)):*
> ```objc
>  private:
>   ElementId id;
>   const RigidBody* body_{};
> ```

In the same vein, consider making this `const RigidBody* const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKtw_dcZ2pSM8D7oIzR:1417088721)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/collision/Element.h, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpzuAn7yxMWK0R5RT:-KKtzozOqXQp1KXkoAg3:-29347951) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L17)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, the style guide discourages but does not prohibit forward declarations.  I think this particular one is OK - in fact, I'm working towards fwd-decl of `RigidBody` in a bunch of other places to cut compilation time.  But in general, you should `#include` even if you're not using the interface.
> 
> https://google.github.io/styleguide/cppguide.html#Forward_Declarations
> 
> You might want to consider deleting the comment.  Up to you.
</details>
I looked at this line when the PR was first filed.  It is here to break what would otherwise be an `#include` dependency cycle.  By adding ornamental data (the `RigidBody`) into the collision `Element`, we've violated layering except insofar as nothing in `collision` ever uses the `RigidBody`.  So in fact adding the include, or any non-ornamental use of the `RigidBody` would be a defect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/Element.h, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpzuAn7yxMWK0R5RT:-KKu1bdNLQ1fPL0ua5MZ:-1734312579) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I looked at this line when the PR was first filed.  It is here to break what would otherwise be an `#include` dependency cycle.  By adding ornamental data (the `RigidBody`) into the collision `Element`, we've violated layering except insofar as nothing in `collision` ever uses the `RigidBody`.  So in fact adding the include, or any non-ornamental use of the `RigidBody` would be a defect.
</details>
Oh, sure enough, the pointers are bidirectional.  In that case, I'd suggest making the comment slightly more explicit about the need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by amcastro-tri** [comment]
Review status: 5 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/bullet_model.cc, line 273 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtv_8vX428mhRhWoS7:-KKu1rL3IQ8YeB4lUEqQ:177521284) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/bullet_model.cc#L273)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, is BulletResultCollector now dead code?  If so, :+1: - please delete it in this PR or a followup!
</details>
very nice @david-german-tri! I was going to push it as a separate PR. But since you noticed, I'll just go ahead and do it here.

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtrFNCbEyC1EBPPA6g:-KKu249Co18-27Y3DTYU:-915813724) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.cpp#L22)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, is this PR a step towards deleting `ElementId` altogether?  That would be great!
</details>
There is a bit of that though that'd require a lot more of work (I tried already in one dead branch I have in my laptop, not trivial and we have more important things on the plate).

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtu2nOyw23hWlBKzff:-KKu2lDymXihVCqtCeCK:-78009174) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.cpp#L22)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> does `static_cast` not suffice?
</details>
I think that would do it. Personally (I don't know if @sherm1 agrees) I prefer `reinterpret_cast` since to us human programmers reads exactly as what it is doing: completely changing the interpretation of bits. 

---

*[drake/systems/plants/collision/Element.h, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpzuAn7yxMWK0R5RT:-KKu52bEananClM7owj9:1451771573) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L17)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Oh, sure enough, the pointers are bidirectional.  In that case, I'd suggest making the comment slightly more explicit about the need.
</details>
I couldn't've explained it better @jwnimmer-tri. I did try to expand on this in the comment. PTAL

---

*[drake/systems/plants/collision/Element.h, line 48 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpiZsQWuvXd6IsyeS:-KKu5LkHRTnSAf1tDY41:-1796779425) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L48)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> The second of the three `const`s here is superfluous, and I think will actually fail to compile post https://github.com/RobotLocomotion/drake/pull/2618.
</details>
you are absolutely right! removed.

---

*[drake/systems/plants/collision/Element.h, line 50 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpTtaOKW_EzilNF3F:-KKu6EX4BgTOD-DMADXt:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L50)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW: "Sets"
</details>
Done.

---

*[drake/systems/plants/collision/Element.h, line 51 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtsO6f4oRVCbyY-GLp:-KKu6L_JFLWi4IVhJU1J:-1609729177) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L51)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Does it make sense for this to change after construction time?  If not, consider getting rid of this setter, and making the RigidBody* a constructor argument.
</details>
It does. The rigid body pointer is used only by the physics engine. When using the collision engine stand alone (like in model_test.cc) the body pointer is not used at all. 

---

*[drake/systems/plants/collision/Element.h, line 64 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtsd0GQhUcxWFwBMDR:-KKu6oNmpT9mhWgf_eS_:-1958047132) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L64)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> In the same vein, consider making this `const RigidBody* const`.
</details>
If I do so I cannot set it later (via `set_body`). That is why it is made private and only accessible through setters/getters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 5 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtu2nOyw23hWlBKzff:-KKuDrKXEcZCVOy5Av4t:-1758626932) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.cpp#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I think that would do it. Personally (I don't know if @sherm1 agrees) I prefer `reinterpret_cast` since to us human programmers reads exactly as what it is doing: completely changing the interpretation of bits. 
</details>
LGTM, the style guide tolerates this: https://google.github.io/styleguide/cppguide.html#Casting

---

*[drake/systems/plants/collision/Element.h, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpzuAn7yxMWK0R5RT:-KKuDyA2hsn9KoPUWvda:-346451710) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I couldn't've explained it better @jwnimmer-tri. I did try to expand on this in the comment. PTAL
</details>
LGTM, though I'd drop the last sentence (it's not an alternative - it doesn't work!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKuE8oR72wvALZ5whad:1417088721)*

**Comment by sherm1** [comment]
Review status: 5 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/collision/Element.cpp, line 22 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtu2nOyw23hWlBKzff:-KKuS0estoqcHnk1mXUS:1893622283) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.cpp#L22)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> LGTM, the style guide tolerates this: https://google.github.io/styleguide/cppguide.html#Casting
</details>
LGTM too -- hopefully static_cast would fail here, but even if it works reinterpret_cast is more appropriate due to the horrifying use of a pointer's bit pattern as an integer id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by sherm1** [comment]
The build is failing now since the merge due to a spurious `const` in `PointPair` (recently enforced).

**Comment by david-german-tri** [comment]
I think the only thing blocking merge is your own unresolved comments!

---

Review status: 2 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/plants/collision/Element.h, line 17 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-KKtpzuAn7yxMWK0R5RT:-KKxpamhx6eXDhtd4FbN:676834233) ([raw file](https://github.com/robotlocomotion/drake/blob/92429ed64b616c2d9e185272c5a6f872a8036cd3/drake/systems/plants/collision/Element.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I agree. removed the bad "alternative".
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKxplKRWdLB_-W4g-K4:-1412533931)*

**Comment by sherm1** [comment]
:+1: :lgtm: again.

---

Reviewed 6 of 8 files at r5, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KKxpzYPMX-1-zAi6827:-1400669407)*

**Comment by sherm1** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Comment by amcastro-tri** [comment]
All discussions have been solved and CI passed and therefore this PR is ready to be merged. 

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KL2ZWoOR5cVCegxv2rr:-1579297921)*

**Comment by david-german-tri** [comment]
@amcastro-tri - If you go through and set your status on the six open comment threads to "satisfied", you should be able to merge this PR yourself.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607#-:-KL2pFxu8gJHH3pWz5os:1470449)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 5 files at r3, 1 of 3 files at r4, 6 of 8 files at r5, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2607)*

**Pull request merged**
