### PR TITLE
CMake: Update gurobi install directory on Mac

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16803)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
Example of a failing build before this change: https://drake-jenkins.csail.mit.edu/job/mac-monterey-clang-cmake-weekly-everything-debug/9/console

+@jwnimmer-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16803#-:-MyF9IzQ2K8udibOESJn:bceidh6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-monterey-clang-cmake-experimental-everything-debug please.

**Comment by jwnimmer-tri** [comment]
:lgtm: both rubber stamp.  I don't have access to any macs to test this, but I'm happy to just go with your testing.

**Review by BetsyMcPhail — COMMENTED** [review]
The relevant Mac CI job has made it past the provisioning portion so I think we can safely call it good.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16803#-:-MyF9iwqBmnM4N6GzjGW:b-rhml77)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by BetsyMcPhail — COMMENTED** [review]
Sorry, I was looking at the wrong job - I'm interested in https://drake-jenkins.csail.mit.edu/job/mac-monterey-clang-cmake-experimental-everything-debug/2/, which hasn't started yet

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16803#-:-MyFB-CQ8rJV3IXYqGfM:bc87oyw)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16803)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
In that second job, it looks OK now:
```
[6:11:45 PM]  -- Found Gurobi: /Library/gurobi951/macos_universal2/include (found suitable exact version "9.5.1") 
```

**Pull request merged**
