### PR TITLE
Add FooVector::IsValid to generated BasicVectors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For now, this only covers NaN-ness, which is the default.  But, it gets the big-diff changes out of the way, which will make the next step of schema-defined limits more clear.

Also tidies a doxygen TODO from previously.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5391)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

Not sure about feature review; TBD.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri Please give the _design_ a quick once-over... my proposal is that generated BasicVector subclasses have an `IsValid() const` method that checks the _intrinsic_ limits on the scalar elements.  A follow-on PR will add the ability to add more limits, e.g., non-negative, to certain elements.

**Comment by ggould-tri** [comment]
This makes some sense for NaN but I'm not sure I understand this elsewhere.  Where do you imagine that `IsValid` would be checked?  What would it mean for dynamics to give a non-`IsValid` result?  Or is this meant only to apply to inputs?

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeJgFl0m909TfmTrSa7:bg6qar6)*

**Comment by jwnimmer-tri** [comment]
The major use case will be numeric Parameters, which when grouped are often represented in a Vector, and Parameters definitely have some intrinsic limits.  Similarly, Inputs could have intrinsic limits -- like normalized acceleration or power in `[-1..1]` or `[0..1]` depending on your transmission model.

**Comment by ggould-tri** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJkWD9ufuV-8ss26xD:-KeJkWD9ufuV-8ss26xE:bgaqo8z) ([raw file](https://github.com/robotlocomotion/drake/blob/04f128fec9ea07880bd00a2000370dadf4cee487/drake/tools/lcm_vector_gen.py#L149)):*
> ```Python
>         context.update(field=field['name'])
>         context.update(kname=to_kname(field['name']))
>         context.update(doc=field['doc'])
> ```

FYI -- Unused. Other methods here that don't use their `doc` don't set it, and it's hard to see how an is_valid method could use per-field docs anyway.

However also note that the setting name and kname block is rule-of-three; consider factoring "set context all everything from field" into a method, or even the entire for loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by jwnimmer-tri** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJkWD9ufuV-8ss26xD:-KeJnJKfdg6zP0v5mrwk:bloe0xt) ([raw file](https://github.com/robotlocomotion/drake/blob/04f128fec9ea07880bd00a2000370dadf4cee487/drake/tools/lcm_vector_gen.py#L149)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Unused. Other methods here that don't use their `doc` don't set it, and it's hard to see how an is_valid method could use per-field docs anyway.

However also note that the setting name and kname block is rule-of-three; consider factoring "set context all everything from field" into a method, or even the entire for loop.
</blockquote></details>

Done (plus a TODO).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by ggould-tri** [comment]
:lgtm: pending design opinions from @david-german-tri .  I don't think I have enough context on the vector overhaul to anticipate that :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJkWD9ufuV-8ss26xD:-KeJsApx87oXKXdE-n1K:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/04f128fec9ea07880bd00a2000370dadf4cee487/drake/tools/lcm_vector_gen.py#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done (plus a TODO).
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeJsDx9BBD_wtBjY7vT:bewgmd3)*

**Comment by david-german-tri** [comment]
Do you envision this becoming part of the `BasicVector` or even `VectorBase` contract?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/tools/test/sample_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJrllTSHNDKtzZe-7r:-KeJrllU-ylJHp3zZcCW:bsjc3yx) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/sample_test.cc#L37)):*
> ```cpp
>   EXPECT_EQ(cloned->GetAtIndex(1), 22.0);
> 
>   // IsValid.
> ```

Could you add test coverage for at least `T = symbolic::Expression`?

---

*[drake/tools/test/sample_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJuojWO6i20ucrdQWi:-KeJuojWO6i20ucrdQWj:bz5l0we) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/sample_test.cc#L37)):*
> ```cpp
>   EXPECT_EQ(cloned->GetAtIndex(1), 22.0);
> 
>   // IsValid.
> ```

BTW the omnibus-test is kind of an antipattern IMO.

---

*[drake/tools/test/gen/sample.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJvXUoC8akJuZlJcK4:-KeJvXUoC8akJuZlJcK5:b-xza1pb) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/gen/sample.h#L62)):*
> ```objc
>   decltype(T() < T()) IsValid() const {
>     using std::isnan;
>     auto result = (T(0) == T(0));
> ```

If this is false, I claim `T` itself is defective.  Do you agree?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeJvInC2r_aD0APiw6N:b8cee0m)*

**Comment by jwnimmer-tri** [comment]
I would be open to that, but didn't have a story for exactly how that takes shape.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/tools/test/gen/sample.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJvXUoC8akJuZlJcK4:-KeK0q29fIRTCtairXho:b97gh4e) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/gen/sample.h#L62)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

If this is false, I claim `T` itself is defective.  Do you agree?
</blockquote></details>

Yes.  Is the idea that I could `DRAKE_ASSERT(result)l`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeK0dbYRcuY4MsbARdk:b-sq1b5q)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/tools/test/gen/sample.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJvXUoC8akJuZlJcK4:-KeKLep9jUstngX2p6au:b-niqtr) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/gen/sample.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  Is the idea that I could `DRAKE_ASSERT(result)l`?
</blockquote></details>

From f2f: no change needed here, except possibly a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by jwnimmer-tri** [comment]
+(status: do not merge) +(status: do not review)

In looking at unit tests, I file a pile of yaks waiting for me.  Oops.  Sorry!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeKvKxhUSVduUBiOOCJ:b-nyg3jv)*

**Comment by jwnimmer-tri** [comment]
Tests added; PTAL.

Note that the `symbolic_formula.h` flavor of `isnan` is temporary; Soonho will PR a correct implementation next week.

---

Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/tools/test/sample_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJuojWO6i20ucrdQWi:-KeQvk5JhdU6m7cQpJ-Q:b-kmaq9g) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/sample_test.cc#L37)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW the omnibus-test is kind of an antipattern IMO.
</blockquote></details>

Done (somewhat).

---

*[drake/tools/test/sample_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeJrllTSHNDKtzZe-7r:-KeQvlP9aTeHBPTovPcI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4411ac6b35ae02fc164ec1641f803dc58c579de3/drake/tools/test/sample_test.cc#L37)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Could you add test coverage for at least `T = symbolic::Expression`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeQvV79V0x-b9ILSHlV:b-8hobth)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 203 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeZ18atMI2iD9pYBAdB:-KeZ18atMI2iD9pYBAdC:b-58zyo2) ([raw file](https://github.com/robotlocomotion/drake/blob/22680c6b1dfadcd746b0c85a606d04b9b28a7f9f/drake/common/symbolic_formula.h#L203)):*
> ```objc
> 
> /** Returns a NaN check predicate on @p e. */
> // TODO(soonho-tri) This implementation is broken.
> ```

"Broken" is not actionably descriptive.  If @soonho-tri doesn't get around to fixing this instantly, it will be unclear to future readers what is broken.  Consider explaining further or file an issue.

(I assume that the actual issue is that recursive descent for nans and nan-like conditions is required, or possibly a test evaluation.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_formula.h, line 203 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeZ18atMI2iD9pYBAdB:-KeZ3tSQbRCvA3OkScBJ:b5pcsxx) ([raw file](https://github.com/robotlocomotion/drake/blob/22680c6b1dfadcd746b0c85a606d04b9b28a7f9f/drake/common/symbolic_formula.h#L203)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

"Broken" is not actionably descriptive.  If @soonho-tri doesn't get around to fixing this instantly, it will be unclear to future readers what is broken.  Consider explaining further or file an issue.

(I assume that the actual issue is that recursive descent for nans and nan-like conditions is required, or possibly a test evaluation.)
</blockquote></details>

The PR to fix it is imminent.  Given the unlikely nature of this TODO hanging around for very long, I think the downside of "someone has to ask soonho-tri what 'broken' means" is reasonable.

Here's a sketch, though, for anyone following along...

Because `symbolic::Expression` will admit `NaN`s in an expression tree, but will throw at runtime if you try to compute with them, we shouldn't use `op==` here (nor should we similarly use a `double`-typed `NaN` with`op==` to test for `NaN`s in non-symbolic C++ code).  Instead, `isnan` will turn into a first-class unary predicate in `symbolic::Formula`.  (Similarly for `isfinite`, etc.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 203 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeZ18atMI2iD9pYBAdB:-KeZCs6i9K4dt8nkXiXI:bpj57gj) ([raw file](https://github.com/robotlocomotion/drake/blob/22680c6b1dfadcd746b0c85a606d04b9b28a7f9f/drake/common/symbolic_formula.h#L203)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The PR to fix it is imminent.  Given the unlikely nature of this TODO hanging around for very long, I think the downside of "someone has to ask soonho-tri what 'broken' means" is reasonable.

Here's a sketch, though, for anyone following along...

Because `symbolic::Expression` will admit `NaN`s in an expression tree, but will throw at runtime if you try to compute with them, we shouldn't use `op==` here (nor should we similarly use a `double`-typed `NaN` with`op==` to test for `NaN`s in non-symbolic C++ code).  Instead, `isnan` will turn into a first-class unary predicate in `symbolic::Formula`.  (Similarly for `isfinite`, etc.)
</blockquote></details>

OK, giving faith to your "imminent" reassurance.

And that fix scheme sounds right to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 203 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-KeZ18atMI2iD9pYBAdB:-KeZEJfYNktRSUs0xvKD:b38chfy) ([raw file](https://github.com/robotlocomotion/drake/blob/22680c6b1dfadcd746b0c85a606d04b9b28a7f9f/drake/common/symbolic_formula.h#L203)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

OK, giving faith to your "imminent" reassurance.

And that fix scheme sounds right to me.
</blockquote></details>

I also filed #5414 to be sure, but won't rev the TODO here until/unless another push becomes necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391)*

**Comment by ggould-tri** [comment]
FYI @jwnimmer-tri, this is waiting  _inter alia_ on automotive LGTM from you.  You may have to lgtm yourself.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeZM_p3cQNbaVJfPCfk:brgrllh)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5391#-:-KeZMrh-oDMygq0iP6Wy:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: automotive

**Pull request merged**
