### PR TITLE
Update to Bazel 0.25.2 recommended

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11444)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature and platform review.

**Comment by jamiesnape** [comment]
0.25.2 is out...

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python3-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python3-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@BetsyMcPhail Go ahead and update the Linux images, but wait to deploy them for the moment, since we should probably get a review here first.

**Comment by BetsyMcPhail** [comment]
> @BetsyMcPhail Go ahead and update the Linux images, but wait to deploy them for the moment, since we should probably get a review here first.

Linux images are updated and deployed on Jenkins.

**Pull request merged**
