### PR TITLE
Add eigen include directories to individual targets

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4515)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-open-source please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-open-source please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/swig/CMakeLists.txt, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-KZ3-eM0hrhaPhPQ9c2S:-KZ3-eM0hrhaPhPQ9c2T:b-kr4wgt) ([raw file](https://github.com/robotlocomotion/drake/blob/9845f95d1a34f74f13653d32627132d973c1a4fb/drake/bindings/swig/CMakeLists.txt#L40)):*
> ```CMake
>   add_swig_python_module(autodiffPython autodiffutils.i
>     CPLUSPLUS
>     INCLUDE_DIRS ${EIGEN3_INCLUDE_DIRS}
> ```

Why do only two of these have `INCLUDE_DIRS ${EIGEN3_INCLUDE_DIRS}`?

---

*[drake/system1/CMakeLists.txt, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-KZ30dDFV-fBB-PzWsXQ:-KZ30dDFV-fBB-PzWsXR:b83ifoy) ([raw file](https://github.com/robotlocomotion/drake/blob/9845f95d1a34f74f13653d32627132d973c1a4fb/drake/system1/CMakeLists.txt#L14)):*
> ```CMake
>   trajectory_logger.h
>   robot_state_tap.h)
> add_library(drakeSystem1 INTERFACE)
> ```

Where is this used?

---

*[drake/util/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-KZ30UkzA8LbXQwuFJpW:-KZ30UkzA8LbXQwuFJpX:b-r3lrdh) ([raw file](https://github.com/robotlocomotion/drake/blob/9845f95d1a34f74f13653d32627132d973c1a4fb/drake/util/CMakeLists.txt#L2)):*
> ```CMake
> add_library(drakeUtil OBJECT drakeUtil.cpp)
> target_include_directories(drakeUtil PRIVATE ${EIGEN3_INCLUDE_DIRS})
> ```

Why not `target_link_libraries`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4515)*

**Comment by jamiesnape** [comment]
Review status: 0 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/swig/CMakeLists.txt, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-KZ3-eM0hrhaPhPQ9c2S:-KZ30rNDkUDQdgtH0bC7:b1tqptm) ([raw file](https://github.com/robotlocomotion/drake/blob/9845f95d1a34f74f13653d32627132d973c1a4fb/drake/bindings/swig/CMakeLists.txt#L40)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Why do only two of these have `INCLUDE_DIRS ${EIGEN3_INCLUDE_DIRS}`?
</blockquote></details>

Because of an issue wth autodiff.i.

---

*[drake/system1/CMakeLists.txt, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-KZ30dDFV-fBB-PzWsXQ:-KZ313CWC7hJGNS9O0cb:b-8hdozl) ([raw file](https://github.com/robotlocomotion/drake/blob/9845f95d1a34f74f13653d32627132d973c1a4fb/drake/system1/CMakeLists.txt#L14)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

It is for external use.

---

*[drake/util/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-KZ30UkzA8LbXQwuFJpW:-KZ3105M7hbX_gwmeWER:b-97ye12) ([raw file](https://github.com/robotlocomotion/drake/blob/9845f95d1a34f74f13653d32627132d973c1a4fb/drake/util/CMakeLists.txt#L2)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Why not `target_link_libraries`?
</blockquote></details>

Cannot be used with OBJECT libraries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4515)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-:-KZ359x2DlbgeLKZFuUc:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
It's great how all our pkg-config files are wrong.  :lgtm:

---

Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-:-KZ3zoNgcwN0KJiiWH05:b-ctvw3f)*

**Comment by david-german-tri** [comment]
-@jamiesnape 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4515#-:-KZ3zsrZBF4wQCY_GMmQ:b4m7a73)*

**Pull request merged**
