### PR TITLE
Don't use GTK POD wrapper

### LINKED ISSUE #3330: Use non-POD version of GTK+ wrapper
Yes: http://win32builder.gnome.org/gtk+-bundle_3.6.4-20130921_win32.zip
Yes: http://win32builder.gnome.org/gtk+-bundle_3.6.4-20131201_win64.zip
No: https://github.com/RobotLocomotion/gtk-pod

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Teach `drake_add_external` to support externals downloaded from packages, and hash checking of same, in addition to submodules. Leverage this to directly download and unpack GTK rather than using the "POD" wrapper.

Fixes #3330.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3392)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@jamiesnape for feature review or please reassign. Slack says @jwnimmer-tri is on platform review duty :smile:, but same comment. (@david-german-tri might also be interested?)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jwnimmer-tri** [comment]
Per offline chat, I'm kicking this over to +@david-german-tri (-@jwinmmer-tri) to get this done a bit more efficiently.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3392#-:-KRASn0KM7zz3WURWpsI:blqm09x)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3392#-:-KRASv3y2cK4R8u1aMk8:b-ms9u78)*

**Comment by mwoehlke-kitware** [comment]
My read of the logs is that something is somehow still insisting that `externals/gtk` is a submodule. I suspect it works with `AUTO_UPDATE_EXTERNALS=OFF` (at least, it did on my local machine); I'm not sure offhand what's breaking on CI and haven't yet dug deeply. (Maybe @bradking has ideas?)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by bradking** [comment]
@mwoehlke-kitware I think you forgot to `git rm externals/gtk`to get rid of the actual submodule link from the tree.

**Comment by david-german-tri** [comment]
Decided offline to close this PR.

**Pull request closed without merging**
