### PR TITLE
Bind a constructor for symbolic::Monomial

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14222)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for both reviews please.

I am surprised that `bindings/pydrake/test/symbolic_monomial_test.py` doesn't have a bazel target, and it is not run on CI. Moreover, we have a test in `bindings/pydrake/test/symbolic_test.py` https://github.com/RobotLocomotion/drake/blob/6ebb094cada05f4fa868554f83a08c2fa51650be/bindings/pydrake/test/symbolic_test.py#L697-L847 that largely overlap with `symbolic_monomial_test.py`.  Shall we remove one of the test? Which one would you prefer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14222#-:-MJobS0U-UYwo7TxmZ5i:b-3k7mvs)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Ooh! Good catch! Looks like it was introduced back in #8111 (and it was tested back then), and then it was deleted in #8247 to roll it into the larger test - I didn't catch @soonho-tri's mistake, oops!

Can you delete `symbolic_monomial_test`, and keep it in the larger test since that was the intent 2 years ago? (and luckily, no real changes were made?)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14222)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/BUILD.bazel, line 535 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14222#-MK2bwBr05ff_dRaQuTM:-MK2bwBs3rpQimGXVVB6:b-1oo84) ([raw file](https://github.com/robotlocomotion/drake/blob/cc08f59c8f1c1eeea2bf730075d78869360dc66f/bindings/pydrake/BUILD.bazel#L535)):*
> ```Starlark
> 
> drake_py_unittest(
>     name = "symbolic_monomial_test",
> ```

(Blocking) Per comment, should put new code in `symbolic_test`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14222)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/BUILD.bazel, line 535 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14222#-MK2bwBr05ff_dRaQuTM:-MK5gIWc5aynKMkwugez:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc08f59c8f1c1eeea2bf730075d78869360dc66f/bindings/pydrake/BUILD.bazel#L535)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Blocking) Per comment, should put new code in `symbolic_test`
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: thanks!

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14222#-:-MK6eFUn-16c6rfqGUr5:brfqlux)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
