### PR TITLE
A few small fixes to signal logger, lcm call matlab, and the simple examples.

### PR DESCRIPTION
**Pull request by RussTedrake**
These are mostly trivial.  @jwnimmer-tri for both levels of review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4349)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/lcm/lcm_call_matlab.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4349#-KY107qmOs1tlUNzlZo8:-KY107qmOs1tlUNzlZo9:b7g0jdl) ([raw file](https://github.com/robotlocomotion/drake/blob/c68d453ef2e9877da933da414f796f16907f201a/drake/lcm/lcm_call_matlab.h#L40)):*
> ```objc
>   //  deletion
> 
>   int64_t uid_;
> ```

Required `{}` or similar per code_style_guide, e,g,, `int64_t uid_{};`.

---

*[drake/lcm/lcm_call_matlab.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4349#-KY11NMGEOSCKZHnPk2P:-KY11NMGEOSCKZHnPk2Q:b-urdzl6) ([raw file](https://github.com/robotlocomotion/drake/blob/c68d453ef2e9877da933da414f796f16907f201a/drake/lcm/lcm_call_matlab.h#L40)):*
> ```objc
>   //  deletion
> 
>   int64_t uid_;
> ```

BTW Is this to make the LcmMatlabRemoteVariable copyable?  In that case cppguide says "Remember ... to document that your class is copyable and/or cheaply movable if that's an API guarantee.".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4349#-:-KY11_DC3p5LWVCzTR8K:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/lcm_call_matlab.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4349#-KY107qmOs1tlUNzlZo8:-KY1BcrdnZDOvGxnARJ-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c68d453ef2e9877da933da414f796f16907f201a/drake/lcm/lcm_call_matlab.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Required `{}` or similar per code_style_guide, e,g,, `int64_t uid_{};`.
</blockquote></details>

Done.

---

*[drake/lcm/lcm_call_matlab.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4349#-KY11NMGEOSCKZHnPk2P:-KY1BWkdGX0ZCEe1-3or:bq8j3zm) ([raw file](https://github.com/robotlocomotion/drake/blob/c68d453ef2e9877da933da414f796f16907f201a/drake/lcm/lcm_call_matlab.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this to make the LcmMatlabRemoteVariable copyable?  In that case cppguide says "Remember ... to document that your class is copyable and/or cheaply movable if that's an API guarantee.".
</blockquote></details>

reverted this change for now.  i didn't end up needing it, and think a better long-term solution is to return a shared pointer to that object, and allow for the future possibility of an intelligent destructor.

thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4349)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4349)*

**Comment by jwnimmer-tri** [comment]
Oops.  I should have +curate tag'd this, to get a squash-and-merge.  Oh well.

**Comment by RussTedrake** [comment]
I was careful to have three separate commits, one for each module that got fixed

**Comment by jwnimmer-tri** [comment]
You're right; retracted.  I misread when looking at the global history.

**Pull request merged**
