### PR TITLE
Add VectorInterface::Clone().

### PR DESCRIPTION
**Pull request by david-german-tri**
Prerequisite for making copied Contexts no longer require pointers to their input.

@sherm1 for feature and platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2593)

### CODE REVIEW

**Comment by sherm1** [comment]
Review pass done. I think a uniform Clone/DoClone NVI interface would be better. You may feel that violates the "Interface" in "VectorInterface"; if so I think it would be better to give up the "interface" idea there since this doesn't appear to be a provision for multiple inheritance.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/basic_vector.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiU8l-hsNDEQ1NcL4O:-KKiU8l0lKFxMUXk8AtL:-983550315) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L54)):*
> ```objc
>   /// Uses the Non-Virtual Interface idiom because smart pointers do not have
>   /// type covariance.
>   std::unique_ptr<VectorInterface<T>> Clone() const override {
> ```

See my comment in VectorInterface. If the base class also used NVI, this could indeed be a covariant Clone() that returns `unique_ptr<BasicVector<T>>`. And there would be no need for two virtual methods here. As implemented, I think this method should be marked `final` rather than `override`. However, I feel that use of `final` usually means something is wrong in the design.

---

*[drake/systems/framework/named_value_vector.h, line 86 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiV033b1oIrdz1P8as:-KKiV033b1oIrdz1P8at:1194558430) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/named_value_vector.h#L86)):*
> ```objc
>   }
> 
>   std::unique_ptr<VectorInterface<T>> Clone() const override {
> ```

It seems odd that the implementation here is not parallel to `BasicVector`. I don't think we can know now that this class won't be extended and if so that should be done with a covariant DoClone().

---

*[drake/systems/framework/vector_interface.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiR7edxdhNFeLGribB:-KKiR7edxdhNFeLGribC:-1296003165) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L37)):*
> ```objc
> 
>   /// Returns a column vector containing the entire value of the signal.
>   virtual const Eigen::VectorBlock<const VectorX<T>> get_value() const = 0;
> ```

The first `const` here is spurious.

---

*[drake/systems/framework/vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiRRhQ7rAQp9yYLzXS:-KKiRRhQ7rAQp9yYLzXT:405748678) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L45)):*
> ```objc
>   /// Copies the entire vector to a new VectorInterface, with the same concrete
>   /// implementation type.
>   virtual std::unique_ptr<VectorInterface<T>> Clone() const = 0;
> ```

Consider using NVI here (Clone/DoClone). That would permit (a) instrumentation and breakpoints upon cloning, and (b) "covariant" Clone() methods in the derived classes that avoid the need for `dynamic_cast` when the caller knows the type. To be specific, above method would invoke protected `DoClone()` that returns a raw `VectorInterface<T>*`. BasicVector (e.g.) would implement a private covariant DoClone() override that returns a raw `BasicVector<T>*` and a public Clone() method (non-virtual that hides `VectorInterface::Clone()`) that returns `unique_ptr<BasicVector<T>>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKiVNjvmfS_Gemh8GBp:-118184759)*

**Comment by david-german-tri** [comment]
Actually, I think we should not to close the door to a class that implements both `VectorInterface` and `StateVectorInterface` (contiguous state).  So, I'd like to keep `VectorInterface` purely abstract.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/basic_vector.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiU8l-hsNDEQ1NcL4O:-KKjDEIeRz9-leXoF1sJ:-1205669495) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> See my comment in VectorInterface. If the base class also used NVI, this could indeed be a covariant Clone() that returns `unique_ptr<BasicVector<T>>`. And there would be no need for two virtual methods here. As implemented, I think this method should be marked `final` rather than `override`. However, I feel that use of `final` usually means something is wrong in the design.
</details>
`BasicVector` is intended to be subclassed: for example, `SpringMassOutputVector` is a child of `BasicVector`.  I have no objection to authors adding a covariant `Clone()` to its children where useful.

---

*[drake/systems/framework/named_value_vector.h, line 86 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiV033b1oIrdz1P8as:-KKjDmQ-oUx0Z13tJLSm:-1467870891) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/named_value_vector.h#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> It seems odd that the implementation here is not parallel to `BasicVector`. I don't think we can know now that this class won't be extended and if so that should be done with a covariant DoClone().
</details>
Why do you think this class might be extended?

---

*[drake/systems/framework/vector_interface.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiR7edxdhNFeLGribB:-KKjEtgleHYpXMhoECir:-2065430687) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> The first `const` here is spurious.
</details>
Maybe?  I'm just following the example in the Eigen documentation here: https://eigen.tuxfamily.org/dox/classEigen_1_1VectorBlock.html

In any case, seems out of scope for this PR.

---

*[drake/systems/framework/vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiRRhQ7rAQp9yYLzXS:-KKjF5kj-0yY_gtqm2C9:202356442) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Consider using NVI here (Clone/DoClone). That would permit (a) instrumentation and breakpoints upon cloning, and (b) "covariant" Clone() methods in the derived classes that avoid the need for `dynamic_cast` when the caller knows the type. To be specific, above method would invoke protected `DoClone()` that returns a raw `VectorInterface<T>*`. BasicVector (e.g.) would implement a private covariant DoClone() override that returns a raw `BasicVector<T>*` and a public Clone() method (non-virtual that hides `VectorInterface::Clone()`) that returns `unique_ptr<BasicVector<T>>`.
</details>
See above - I want this to remain an `Interface`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKjCfquyRL8V2sgmsPB:1100672297)*

**Comment by sherm1** [comment]
Review pass done. I think either (a) we should make a standards exception allowing in an Interface NVI-pattern inline methods that invoke a `protected` pure virtual, or (b) we shouldn't use Interface classes except when we are forced to use multiple inheritance. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/basic_vector.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiU8l-hsNDEQ1NcL4O:-KKjoG3pYcqfoxfVGDT_:-1323336479) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L54)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> `BasicVector` is intended to be subclassed: for example, `SpringMassOutputVector` is a child of `BasicVector`.  I have no objection to authors adding a covariant `Clone()` to its children where useful.
</details>
Are you saying `BasicVector` *must* be subclassed? If it can be used as-is, then it is lacking a public `Clone()` method that returns a `unique_ptr<BasicVector<T>>` and that method can't be added. So if I clone a BasicVector I'll have to downcast to make the clone be a BasicVector, yet classes *derived* from BasicVector can have such a "covariant" Clone(). Why is it good to prevent that here?

---

*[drake/systems/framework/basic_vector.h, line 62 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKjnzCfReXfJ130QElu:-KKjnzCfReXfJ130QElv:-1378218180) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L62)):*
> ```objc
>   /// Subclasses of BasicVector must override DoClone to return their covariant
>   /// type.
>   virtual BasicVector<T>* DoClone() const {
> ```

Shouldn't have a doxygen comment on a private method. But, I think the doxygen comment is good here and the method should be protected so it will be part of the API for people who are extending this class.

---

*[drake/systems/framework/named_value_vector.h, line 86 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiV033b1oIrdz1P8as:-KKjpHCZvkoRAzjhGkNk:-501143140) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/named_value_vector.h#L86)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why do you think this class might be extended?
</details>
Because you didn't mark it final. Why shouldn't someone be able to extend this class? I believe that is the default answer for any class unless you have a good reason to prevent later extension. Inability to think up a reason now that someone might want to extend the class isn't evidence that it shouldn't be extensible!

---

*[drake/systems/framework/vector_interface.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiR7edxdhNFeLGribB:-KKjqYAWridFdWE7kawv:-676872586) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L37)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Maybe?  I'm just following the example in the Eigen documentation here: https://eigen.tuxfamily.org/dox/classEigen_1_1VectorBlock.html
> 
> In any case, seems out of scope for this PR.
</details>
The Eigen example has a spurious const; no reason to copy that. And I saw this while reviewing this PR and will likely never see it again so this seems like the right time to comment on it.

---

*[drake/systems/framework/vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiRRhQ7rAQp9yYLzXS:-KKjqovaaACqB7_BP8pL:1962585410) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L45)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> See above - I want this to remain an `Interface`.
</details>
I think you should leave it an interface *and* use an NVI Clone/DoClone pair. It is annoying to me that the strict Google rule for interfaces forces this substandard behavior for no gain. It makes sense to avoid data members in interfaces (due to the creepy address-shifting casts that induces) but adding NVI here costs nothing. And we're losing covariant Clones now for a hypothetical future use of multiple inheritance for which we currently have no use case. (The test cases you wrote are already dynamic_casting the Clone return which they shouldn't have to do.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKjtKVtMg21NgdI42Ce:510747323)*

**Comment by david-german-tri** [comment]
Leaving unresolved for now pending #2603.

---

Review status: 5 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 62 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKjnzCfReXfJ130QElu:-KKjzVcSKUf90azk-hsn:283259827) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L62)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Shouldn't have a doxygen comment on a private method. But, I think the doxygen comment is good here and the method should be protected so it will be part of the API for people who are extending this class.
</details>
As with the StateVector hierarchy, children should never need to call this, and I'm unwilling to let the doxygen tail wag the dog.  So, converted to a non-doxygen comment.

---

*[drake/systems/framework/named_value_vector.h, line 86 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiV033b1oIrdz1P8as:-KKjzkhKt2_DDht5NTos:-1911115900) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/named_value_vector.h#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Because you didn't mark it final. Why shouldn't someone be able to extend this class? I believe that is the default answer for any class unless you have a good reason to prevent later extension. Inability to think up a reason now that someone might want to extend the class isn't evidence that it shouldn't be extensible!
</details>
With this conversation, I think the maintenance cost of this class has exceeded its value (which was small at best and negative at worst), so I've deleted it.  We can always fish it out of the history later if someone needs it.

---

*[drake/systems/framework/vector_interface.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiR7edxdhNFeLGribB:-KKk2KWfwdMDl6gyViye:-474067261) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> The Eigen example has a spurious const; no reason to copy that. And I saw this while reviewing this PR and will likely never see it again so this seems like the right time to comment on it.
</details>
Since this is CRTP, I'll take your word that the `const`ness of the template parameter type makes the entire return type effectively `const`.  Even so, it's not a defect to be explicit about it, for the benefit of readers who haven't looked at the implementation of `VectorBlock`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKkBhLkH51Qjua_WT8d:2090581484)*

**Comment by david-german-tri** [comment]
Actually let me rethink that: while discussion on #2603 is of course welcome, I don't believe it should block this PR.  If at some point in the future the usage you're proposing there is permitted, we can revise this code.

---

Review status: 5 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiU8l-hsNDEQ1NcL4O:-KKkItwc5tC-0jn-z5W6:770512025) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Are you saying `BasicVector` *must* be subclassed? If it can be used as-is, then it is lacking a public `Clone()` method that returns a `unique_ptr<BasicVector<T>>` and that method can't be added. So if I clone a BasicVector I'll have to downcast to make the clone be a BasicVector, yet classes *derived* from BasicVector can have such a "covariant" Clone(). Why is it good to prevent that here?
</details>
Oh, I see what you're saying.  Yes, this should be `final`.  Done.

---

*[drake/systems/framework/vector_interface.h, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiRRhQ7rAQp9yYLzXS:-KKkJ5XlUymGTBfO3wdC:-169092977) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I think you should leave it an interface *and* use an NVI Clone/DoClone pair. It is annoying to me that the strict Google rule for interfaces forces this substandard behavior for no gain. It makes sense to avoid data members in interfaces (due to the creepy address-shifting casts that induces) but adding NVI here costs nothing. And we're losing covariant Clones now for a hypothetical future use of multiple inheritance for which we currently have no use case. (The test cases you wrote are already dynamic_casting the Clone return which they shouldn't have to do.)
</details>
Considered, see above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKkJ8Qta3zM5v-mEebf:1285256409)*

**Comment by sherm1** [comment]
Agreed. I made "OK" comments to unblock, PTAL. There is one spurious const I still want gone; further argument made below.

---

Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/systems/framework/basic_vector.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiU8l-hsNDEQ1NcL4O:-KKlPQ5DBq2QTUvoAfmi:365968848) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L54)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Oh, I see what you're saying.  Yes, this should be `final`.  Done.
</details>
OK, that helps slightly but wasn't really my complaint. I am sad that `BasicVector::Clone()` doesn't return a `unique_ptr<BasicVector>` which would seem to be exactly what it ought to return! 

---

*[drake/systems/framework/basic_vector.h, line 62 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKjnzCfReXfJ130QElu:-KKlLWzS3zpIY6w6SFXY:1739763088) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/basic_vector.h#L62)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> As with the StateVector hierarchy, children should never need to call this, and I'm unwilling to let the doxygen tail wag the dog.  So, converted to a non-doxygen comment.
</details>
OK, but I don't understand why you consider API documentation the "tail". What a user sees is the most important part of any API. The doxygen docs (imperfect as they may be) are often how users first encounter an API and should be taken very seriously IMO. It is definitely worth making the occasional bow to Doxygen's quirks to get it to crank out some useful user docs.

---

*[drake/systems/framework/named_value_vector.h, line 86 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiV033b1oIrdz1P8as:-KKlMPNqIzhpU2Y8vcDf:1163693509) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/named_value_vector.h#L86)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> With this conversation, I think the maintenance cost of this class has exceeded its value (which was small at best and negative at worst), so I've deleted it.  We can always fish it out of the history later if someone needs it.
</details>
OK, :cry:. I yakked it to death.

---

*[drake/systems/framework/vector_interface.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiR7edxdhNFeLGribB:-KKlMv8t1RQSx_kWZJ7d:326279481) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L37)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Since this is CRTP, I'll take your word that the `const`ness of the template parameter type makes the entire return type effectively `const`.  Even so, it's not a defect to be explicit about it, for the benefit of readers who haven't looked at the implementation of `VectorBlock`.
</details>
It's not being explicit -- it is completely spurious in the sense that the meaning is unchanged with or without it. It would be easier to see like this:
```c++
const int get_value() const;
int get_value() const; // identical
```
Since the return is by value it is returning a temp object; it's not a reference. In the case of VectorBlock the template type controls whether the block permits mutable access to the Vector *it* references; the VectorBlock itself is a temp.

P.S. This isn't CRTP because VectorX doesn't derive from VectorBlock<VectorX>. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKlQJTlbBYQEMvtNHxB:-1880404094)*

**Comment by sherm1** [comment]
@david-german-tri, PTAL at the 32-bit Windows build: https://drake-jenkins.csail.mit.edu/job/experimental/2170/
It reported some new warnings in the System 2 code, like improper conversion of int64_t to size_t that wouldn't be noticed anywhere else. (It also failed miserably but I suspect that is unrelated.)

**Comment by david-german-tri** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/vector_interface.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-KKiR7edxdhNFeLGribB:-KKp2-xivuRmYtDZVVEE:-948696905) ([raw file](https://github.com/robotlocomotion/drake/blob/d47f49751dec2bdef73152050d67f2ac022d17b3/drake/systems/framework/vector_interface.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> It's not being explicit -- it is completely spurious in the sense that the meaning is unchanged with or without it. It would be easier to see like this:
> ```c++
> const int get_value() const;
> int get_value() const; // identical
> ```
> Since the return is by value it is returning a temp object; it's not a reference. In the case of VectorBlock the template type controls whether the block permits mutable access to the Vector *it* references; the VectorBlock itself is a temp.
> 
> P.S. This isn't CRTP because VectorX doesn't derive from VectorBlock<VectorX>. 
</details>
OK, I concede.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593)*

**Comment by david-german-tri** [comment]
Regarding the warnings: good catch!  I owe an integer type cleanup on all of `systems/framework` - the rules have shifted a few times since we started, and the result is bad stuff like that.

---

Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKp4zLxwzmRl5Zkpv2o:-1042571192)*

**Comment by david-german-tri** [comment]
jenkins: retest this please

**Comment by david-german-tri** [comment]
@sherm1 friendly ping - anything else needed here?

---

Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKxpO-sQFoWTW-hafsI:-918381480)*

**Comment by sherm1** [comment]
:lgtm: Please open an issue for the mismatched integers so they won't get forgotten -- I know we have lots of those but I'd rather not see new ones accumulate.

---

Reviewed 1 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2593#-:-KKxtXE-5tszalCTC4Y1:-261117314)*

**Pull request merged**
