### PR TITLE
upgrade mosek to mosek 9.2

### PR DESCRIPTION
**Pull request by hongkai-dai**
Drake currently supports mosek 9.0, which has a bug in pre-solve the problem to get the dual variable solutions (as shown in our PR #14383. I contacted with Mosek developer and confirmed that Mosek 9.2 resolves this bug.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14484)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by hongkai-dai — COMMENTED** [review]
+@jamiesnape for feature review please,  thanks

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14484#-:-MQDJ204AfbVUsuTQJ-Q:b-4ttby7)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14484#-:-MQDNbR_7yieX4zS0AYY:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[solvers/test/quadratic_program_examples.cc, line 435 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14484#-MQDNYVj9rWlkI5GFlhX:-MQDNYVk7_FdzhrEepPI:bin2w9g) ([raw file](https://github.com/robotlocomotion/drake/blob/6ffafb26054cdb773aee056ba07fba1c075624f8/solvers/test/quadratic_program_examples.cc#L435)):*
> ```cpp
>     double tol = 1E-4;
>     if (solver_type == SolverType::kMosek) {
>       // Regression from MOSEK 8.1 to MOSEK 9.2.
> ```

BTW This is still the case?

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14484#-:-MQDa4HC2b2u03bjJSXA:b8asji7)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[solvers/test/quadratic_program_examples.cc, line 435 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14484#-MQDNYVj9rWlkI5GFlhX:-MQD_y5r9NopI4QKhTZW:b-gsdx5j) ([raw file](https://github.com/robotlocomotion/drake/blob/6ffafb26054cdb773aee056ba07fba1c075624f8/solvers/test/quadratic_program_examples.cc#L435)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW This is still the case?
</blockquote></details>

Yes it is. I tested locally on my machine and Mosek9.2 still requires a larger tolerance.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14484)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14484#-:-MQDk1exDbRZTnrtCH7_:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jamiesnape

**Pull request merged**
