### PR TITLE
guard against dynamic allocation in main acrobot_plant dynamics and output loops.

### PR DESCRIPTION
**Pull request by RussTedrake**
This is an exercise that we should do throughout the code:
http://eigen.tuxfamily.org/index.php?title=FAQ#Where_in_my_program_are_temporary_objects_created.3F

It was interesting to do it just in the AcrobotPlant code.  In this (non-critical) code, I think it makes sense to leave the guards in.

N.B. - I think excessive Eigen dynamic allocation is one of the major risks in System2.0 (if we find it painful later, it could force an API change).  This was a baby spike test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4265)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4265#-KXcqNoPxI1eXlsPq2q7:-KXcqNoPxI1eXlsPq2q8:b-c5t0eg) (no related file):*
Consider using an RAII phrasing of this checking.  That (1) seems to me more idiomatic, and (2) opens the door for push/pop semantics where e.g. our pull-based control flow would otherwise cause systems to fight with each other about whether this global is set one way or another, depending on exactly what was rippling when.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4265)*

**Comment by RussTedrake** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4265#-KXcqNoPxI1eXlsPq2q7:-KXcuXIKrcqaiYPZ2gpk:bu4546z) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Consider using an RAII phrasing of this checking.  That (1) seems to me more idiomatic, and (2) opens the door for push/pop semantics where e.g. our pull-based control flow would otherwise cause systems to fight with each other about whether this global is set one way or another, depending on exactly what was rippling when.
</blockquote></details>

When I started, I expect to write something like that (precisely to obtain the push/pop).  But eigen's method was convenient enough to start with.  Agreed that we need better semantics if we're going to do this sort of thing everywhere.  perhaps a todo is sufficient for this first instance to get in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4265)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4265#-KXcqNoPxI1eXlsPq2q7:-KXfdOXUAC0VfL85lbAy:bfttn65) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

When I started, I expect to write something like that (precisely to obtain the push/pop).  But eigen's method was convenient enough to start with.  Agreed that we need better semantics if we're going to do this sort of thing everywhere.  perhaps a todo is sufficient for this first instance to get in?
</blockquote></details>

-> #4269.  This is a nifty trick for local testing, but given the ABI and thread safety problems, I'm uneasy about merging this PR even with a TODO.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4265#-KXferGe93CGHT2YcrmW:-KXferGfuuCq9ghRixvq:b4j4wr8) ([raw file](https://github.com/robotlocomotion/drake/blob/b1b48a0cec5993320b394fa7a19cf926287b5bfd/drake/examples/Acrobot/acrobot_plant.cc#L1)):*
> ```cpp
> #define EIGEN_RUNTIME_NO_MALLOC
> ```

@jwnimmer-tri points out that this may mess with the ABI of Eigen itself.

---

*[drake/examples/Acrobot/acrobot_plant.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4265#-KXff1u8hqVofZMsQgeY:-KXff1u8hqVofZMsQgeZ:b3jrmnz) ([raw file](https://github.com/robotlocomotion/drake/blob/b1b48a0cec5993320b394fa7a19cf926287b5bfd/drake/examples/Acrobot/acrobot_plant.cc#L31)):*
> ```cpp
> void AcrobotPlant<T>::EvalOutput(const systems::Context<T>& context,
>                                  systems::SystemOutput<T>* output) const {
>   Eigen::internal::set_is_malloc_allowed(!std::is_same<T, double>::value);
> ```

This (and below) is not thread-safe; it modifies a static bool.  Even adding a wrapper with a lock and a stack would not make it thread-safe in a practical sense, since another thread could change the behavior mid-Eval.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4265)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4265)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4265#-KXcqNoPxI1eXlsPq2q7:-KXgf66I8SWo1VxdbD-3:bpmp5wa) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

-> #4269.  This is a nifty trick for local testing, but given the ABI and thread safety problems, I'm uneasy about merging this PR even with a TODO.
</blockquote></details>

ok.  will close it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4265)*

**Pull request closed without merging**
