### PR TITLE
[workspace] Upgrade usockets and uwebsockets

### LINKED ISSUE #17910: usockets and uwebsockets needs update to latest
uwebsockets needs to be updated to the latest release. The build is failing:
```
external/uwebsockets/src/App.h:90:62: error: static assertion failed: Mismatching uSockets/uWebSockets ABI
   90 |     static_assert(sizeof(struct us_socket_context_options_t) == sizeof(SocketContextOptions), "Mismatching uSockets/uWebSockets ABI");
```

It looks like the latest µWebSockets may depend on an unreleased µSockets? (The latest µSockets release is Sept 2021. There should perhaps also be a note that these packages should update in tandem in the relevant `repository.bzl`(s)?)

Note also that `new_release.py` is not currently working on usockets due to sigmavirus24/github3.py#1105.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17910.

See also https://github.com/uNetworking/uWebSockets/issues/1512.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18259)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: with one issue.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18259#-:-NGIVZaq5KVQsTlY-lhm:b2tsmgq)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/workspace/uwebsockets/repository.bzl` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18259#-NGIVuHj7EibWTSJ3Wlk:-NGIVuHkBCiBWUtXcsgJ:b2c3bcl) ([raw file](https://github.com/robotlocomotion/drake/blob/b488aef036fcd0a10d7a89fbc10ce32d9625f980/tools/workspace/uwebsockets/repository.bzl#L11)):*
> ```Starlark
>         name = name,
>         repository = "uNetworking/uWebSockets",
>         # TODO(jwnimmer-tri) Switch back to numbered releases as of > v20.29.0.
> ```

This is confusing and, I think, unnecessary, as the commit below is tagged as `v20.30.0` and listed with that number of the releases page. 
 https://github.com/uNetworking/uWebSockets/releases/tag/v20.30.0

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18259)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`tools/workspace/uwebsockets/repository.bzl` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18259#-NGIVuHj7EibWTSJ3Wlk:-NGIXhz87ZngOD8YWsek:bcri3d4) ([raw file](https://github.com/robotlocomotion/drake/blob/b488aef036fcd0a10d7a89fbc10ce32d9625f980/tools/workspace/uwebsockets/repository.bzl#L11)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is confusing and, I think, unnecessary, as the commit below is tagged as `v20.30.0` and listed with that number of the releases page. 
 https://github.com/uNetworking/uWebSockets/releases/tag/v20.30.0
</blockquote></details>

Huh, I guess they tagged it after I'd pushed this PR.  Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18259)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
