### PR TITLE
Fixes inconsistency with the default values of basic vectors vs named (basic) vectors.

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds helper that initializes the vector to vector of Variable with the known variable names.  (this makes using named vectors with Expression so much nicer).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8538)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-:-L9aFXd37bRWiPkNAtrT:b-vawmhb)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9eT7jm1YJH-ZsApiZD:b-s2ss4j) (no related file):*
> Default values of named vectors should use dummy_value... they were simply being set to zero.

Why?

> This was inconsistent with the behavior of every other BasicVector.

With BasicVector, the constructor has no idea what a good default value is.  With named_vector, we always know -- its whatever the user said in the named_vector declaration.  As we can see by the "0.0" all over this PR, the user wanting 0.0 as a sensible default is quite common.  If we want to avoid an implicit default value of 0.0 for some reason, then we should make the named_vector default_value field required, not change the default to NAN, so the intent of the author is always clear.

If there is some rare case where 0.0 is a poor choice as a constructor default, then the user can do "default_value: NAN" in the schema.  (If NAN doesn't work in the named_vector tooling, we should file and issue / fix it.)

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT_836anjlVFZpHdP:-L9eT_836anjlVFZpHdQ:b1u4x7r) (no related file):*
> Now named vectors get initialized to a Variable with the known variable name (this makes using named vectors with Expression so much nicer).

I am skeptical.  As I understand it, no other computational elements do this.  For things like State in the Context, we don't auto-assign `xc[0]`..., do we?  Instead, we have a helper that the user can call _if_ they want fresh variables populated into the storage.  My intuition is that the generated named vector should offer such a method as an option (a setter and/or a factory method -- probably both for convenience), not as its default constructor behavior.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9h3fb80kRpCQThkWju:bos3ppm) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Default values of named vectors should use dummy_value... they were simply being set to zero.

Why?

> This was inconsistent with the behavior of every other BasicVector.

With BasicVector, the constructor has no idea what a good default value is.  With named_vector, we always know -- its whatever the user said in the named_vector declaration.  As we can see by the "0.0" all over this PR, the user wanting 0.0 as a sensible default is quite common.  If we want to avoid an implicit default value of 0.0 for some reason, then we should make the named_vector default_value field required, not change the default to NAN, so the intent of the author is always clear.

If there is some rare case where 0.0 is a poor choice as a constructor default, then the user can do "default_value: NAN" in the schema.  (If NAN doesn't work in the named_vector tooling, we should file and issue / fix it.)
</blockquote></details>

In the case where the user does not specify a default_value, why is it ok to assume 0.0 for named vector, but not to assume 0.0 for BasicVector?  I don't see any reasonable distinction between those two cases, and the fact that the behavior is different (and undocumented) is bad.  

I would also be ok with making the default_value required, but I think this is an improvement.  

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT_836anjlVFZpHdP:-L9h4CDYBNa0v78-WKZR:b-olo0sz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Now named vectors get initialized to a Variable with the known variable name (this makes using named vectors with Expression so much nicer).

I am skeptical.  As I understand it, no other computational elements do this.  For things like State in the Context, we don't auto-assign `xc[0]`..., do we?  Instead, we have a helper that the user can call _if_ they want fresh variables populated into the storage.  My intuition is that the generated named vector should offer such a method as an option (a setter and/or a factory method -- probably both for convenience), not as its default constructor behavior.
</blockquote></details>

in fact, I had already changed the code to do exactly that.  i thought I had updated the commit comment, too... but will make sure.  

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT_836anjlVFZpHdP:-L9h4SE90ZmWdeHTTDTA:b-oadoe1) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

in fact, I had already changed the code to do exactly that.  i thought I had updated the commit comment, too... but will make sure.  
</blockquote></details>

confirmed that the git commit was indeed correct.  (only github's copy was not updated)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by jwnimmer-tri** [comment]
The `Variable` stuff LGTM.

---

Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/vector_gen/lcm_vector_gen.py, line 119 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9h9GpE6G-8Nq1B_pgd:-L9h9GpE6G-8Nq1B_pge:b59yyiv) ([raw file](https://github.com/robotlocomotion/drake/blob/e2490f9f5bb9c9966677460e07adf195ed52285c/tools/vector_gen/lcm_vector_gen.py#L119)):*
> ```Python
> 
> 
> # Default constructor.
> ```

FYI I think punting the special case zero-ctor code is a benefit, no matter the other discussions.

---

*[tools/vector_gen/test/goal/sample.h, line 15 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9h7xJU7t0Dwjg6j53z:-L9h7xJU7t0Dwjg6j54-:b-lz50u2) ([raw file](https://github.com/robotlocomotion/drake/blob/e2490f9f5bb9c9966677460e07adf195ed52285c/tools/vector_gen/test/goal/sample.h#L15)):*
> ```objc
> #include "drake/common/drake_bool.h"
> #include "drake/common/never_destroyed.h"
> #include "drake/common/symbolic.h"
> ```

In `tools/vector_gen/vector_gen.bzl`, the `drake_cc_vector_gen_library` macro should add a `deps` for `//common:symbolic` now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-:-L9h9Zel4BxxQSXDzljS:b-dq1p4q)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9h8y0r3Oa-2r0mveSg:b-u6ojrp) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The distinction is that named vectors are imbued with semantics (including a name, units, documentation, etc.), but basic vectors are not.  Because named vectors have semantics, it's more likely to be possible (and I'd argue, preferred) to provide a sensible default_value.  Since 0.0 seemed like the most common default for the default_value attribute, that's what the codegen tool does.

In any case, if the two of us disagree, or if you were surprised, its likely that others will also disagree or at least be surprised, even if we end up with a consensus vote between the two of us on a "best" default.

Thus, I'd say the appropriate answer is to make the default_value attribute required, and ask the author of each named_vector to have to write down what they think the defaults should be.

I would be OK if that turned into a separate PR, or done here alongside the other change also.  I think for any current named_vector's that we are changing to use NANs now, we should make sure an appropriate feature reviewer signs off on the change for that vector.
</blockquote></details>

0.0 is often reasonable when it is not it is quite dangerous.  for nominal state variables, ok, but when parameters like mass, etc, simply disappear from consideration (i was particularly surprised to see this in the symbolic::Expression version, where the expressions were initialized to 0.0 and therefore simplified into non-existence) then it's no good.

aok with having the default_value required... (and I agree it could be a follow-on PR).  

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/vector_gen/lcm_vector_gen.py, line 119 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9h9GpE6G-8Nq1B_pgd:-L9h9pXRC0josbEJLAhH:bimhrw7) ([raw file](https://github.com/robotlocomotion/drake/blob/e2490f9f5bb9c9966677460e07adf195ed52285c/tools/vector_gen/lcm_vector_gen.py#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think punting the special case zero-ctor code is a benefit, no matter the other discussions.
</blockquote></details>

it would have never gotten hit in my version.  (unless they typed "dummy.." into python!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by RussTedrake** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9hG7NH7CbaJrRjR8ZS:b8abt1x) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

0.0 is often reasonable when it is not it is quite dangerous.  for nominal state variables, ok, but when parameters like mass, etc, simply disappear from consideration (i was particularly surprised to see this in the symbolic::Expression version, where the expressions were initialized to 0.0 and therefore simplified into non-existence) then it's no good.

aok with having the default_value required... (and I agree it could be a follow-on PR).  
</blockquote></details>

FYI to the following authors of named_vectors without defaults:
@edrumwri for rod2d
@seancurtis-tri for geometry_world::bouncing_ball
myself for acrobot input.  (doh)
@jwnimmer-tri for bicycle_car_state and maliput_railcar_state simple_car_state and trajectory_car_state . 

---

*[tools/vector_gen/test/goal/sample.h, line 15 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9h7xJU7t0Dwjg6j53z:-L9hCRCl6TALv6w4H02X:byaib4t) ([raw file](https://github.com/robotlocomotion/drake/blob/e2490f9f5bb9c9966677460e07adf195ed52285c/tools/vector_gen/test/goal/sample.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In `tools/vector_gen/vector_gen.bzl`, the `drake_cc_vector_gen_library` macro should add a `deps` for `//common:symbolic` now.
</blockquote></details>

Done.  (please confirm I added it where you meant)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9hJncO5DNrLAOSr2Zk:bbsonke) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

FYI to the following authors of named_vectors without defaults:
@edrumwri for rod2d
@seancurtis-tri for geometry_world::bouncing_ball
myself for acrobot input.  (doh)
@jwnimmer-tri for bicycle_car_state and maliput_railcar_state simple_car_state and trajectory_car_state . 
</blockquote></details>

Ah, I see my possible confusing communication.  By "separate PR" I meant that this PR only does the symbolic-related changes, and _all_ changes related to default values are cut out to a future PR.  If this PR has changes to defaults, then I think the "make it a required attribute" needs to be added here also.  In other words, changing the implicit default to NAN doesn't sit will with me.  (Maybe this was all clear, but re-iterating just in case.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9hKZ3uDFYJru4V_435:bwswfxf) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, I see my possible confusing communication.  By "separate PR" I meant that this PR only does the symbolic-related changes, and _all_ changes related to default values are cut out to a future PR.  If this PR has changes to defaults, then I think the "make it a required attribute" needs to be added here also.  In other words, changing the implicit default to NAN doesn't sit will with me.  (Maybe this was all clear, but re-iterating just in case.)
</blockquote></details>

I see, that wasn't how I interpreted "I think for any current named_vector's that we are changing to use NANs now, we should make sure an appropriate feature reviewer signs off on the change for that vector.".  ;-)

can pull it out, but I consider the current implementation a defect and might not have the cycles to implement your solution before my trip.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9hNYt30Tq17Rcuxs93:b1823mv) (no related file):*
To me the only defect is clarity ("what should a user expect the default is?").  If a symbolic Parameter is constant-NaN, that's not really any better than constant-0.0 -- the problem is you forgot to install symbolic variables, the problem is not that the expression got simplified because it had no variables.

> we should make sure an appropriate feature reviewer signs off on the change for that vector

Right, so I meant that they should review a line of code that says "default_value: NAN", not to generally bless an invisible line of code.  Then we can debate those specific lines.  (I think probably all of the automotive state vectors should remain zero-default, instead of NAN-default, for example.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by RussTedrake** [comment]
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-L9eT7jm1YJH-ZsApiZC:-L9iuGxz0Qe08ghADXjN:bdrujbd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To me the only defect is clarity ("what should a user expect the default is?").  If a symbolic Parameter is constant-NaN, that's not really any better than constant-0.0 -- the problem is you forgot to install symbolic variables, the problem is not that the expression got simplified because it had no variables.

> we should make sure an appropriate feature reviewer signs off on the change for that vector

Right, so I meant that they should review a line of code that says "default_value: NAN", not to generally bless an invisible line of code.  Then we can debate those specific lines.  (I think probably all of the automotive state vectors should remain zero-default, instead of NAN-default, for example.)
</blockquote></details>

I've removed the default behavior and made this PR only about the new method for symbolic (and updated the commit message / github comment).   I've opened #8560 for the default values.  

I did leave the few default values that I had explicitly set when the original author was either me or the reviewers of this PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8538#-:-L9jJEp_17Fo0f2Akfoi:bnfp4nl)*

**Pull request merged**
