### PR TITLE
Add support for IPOPT on Mac by auto-detecting libgfortran.

### PR DESCRIPTION
**Pull request by david-german-tri**
Supersedes #4970.  @soonho-tri for feature review, and @jwnimmer-tri for platform review.

Gosh, this is so much better and easier than everything else I tried.  Kudos @jwnimmer-tri for pointing me in the right direction.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4983)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/solvers/BUILD, line 344 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpNF0YvqQ3Qy3UGoSi:-KbpNF0ZBsNKsX_JKACO:b500e0h) ([raw file](https://github.com/robotlocomotion/drake/blob/07f26a33258328882ce589ad40b89049f23bfb80/drake/solvers/BUILD#L344)):*
> ```Python
>     "gurobi_solver.h",
>     "no_gurobi.cc",
> ])
> ```

If you rebase to master, you'll see that I added ipopt stuff to `extra_srcs` here, which should now be removed since the `select` is gone.

---

*[tools/gfortran.bzl, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpNlQwdBf0L_8g0zLu:-KbpNlQwdBf0L_8g0zLv:b-aa5a4k) ([raw file](https://github.com/robotlocomotion/drake/blob/07f26a33258328882ce589ad40b89049f23bfb80/tools/gfortran.bzl#L17)):*
> ```Python
>         path = result.stdout.strip()
>         if path:
>             print(path)
> ```

Bazel turns this print into warning, I think?

---

*[tools/gfortran.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpOY3QqeqVsbDgbywY:-KbpOY3QqeqVsbDgbywZ:b-b3284m) ([raw file](https://github.com/robotlocomotion/drake/blob/07f26a33258328882ce589ad40b89049f23bfb80/tools/gfortran.bzl#L34)):*
> ```Python
>     else:
>         warning = "gfortran.bzl: " + warning_detail
>         BUILD = "print(\"{warning}\")\n".format(warning=warning)
> ```

Would it be desirable to `fail()` at repository_rule time instead of build-time?  The build seems doomed either way, and earlier seems better?  It might clean up the warning printing code a bit too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983)*

**Comment by david-german-tri** [comment]
Looking into the CI failures (which aren't happening locally)

**Comment by soonho-tri** [comment]
Testing on my macs...

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpQ7c_pveob2kyUt-2:b-u278hq)*

**Comment by soonho-tri** [comment]
```
ERROR: /Users/soonhok/work/drake/drake/solvers/BUILD:273:1: Linking of rule '//drake/solvers:mathematical_program_test' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_soonhok/a9a9c5be1fd1cb3f2dee812ac07be937/bazel-sandbox/903517f3-b9d6-499c-898d-ff7d0df5786c-484/sandbox.sb ... (remaining 31 argument(s) skipped).
```

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpSqFw9xPEWeJjTndl:bz06nh1)*

**Comment by david-german-tri** [comment]
Possibly fixed - can I stop by to see what happens in more detail?

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/BUILD, line 344 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpNF0YvqQ3Qy3UGoSi:-KbpPbNI-_nqcg2wbMp_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07f26a33258328882ce589ad40b89049f23bfb80/drake/solvers/BUILD#L344)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you rebase to master, you'll see that I added ipopt stuff to `extra_srcs` here, which should now be removed since the `select` is gone.
</blockquote></details>

Done.

---

*[tools/gfortran.bzl, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpNlQwdBf0L_8g0zLu:-KbpPcTrq_Q2TM8SyTtP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07f26a33258328882ce589ad40b89049f23bfb80/tools/gfortran.bzl#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Bazel turns this print into warning, I think?
</blockquote></details>

Done.

---

*[tools/gfortran.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpOY3QqeqVsbDgbywY:-KbpPcll5lW_qm58N7gD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07f26a33258328882ce589ad40b89049f23bfb80/tools/gfortran.bzl#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Would it be desirable to `fail()` at repository_rule time instead of build-time?  The build seems doomed either way, and earlier seems better?  It might clean up the warning printing code a bit too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpW-RzitFgeEOt6y59:bj3e2wu)*

**Comment by soonho-tri** [comment]
Sure.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpXC-waP0yfW_p4e5g:b-80tlqk)*

**Comment by soonho-tri** [comment]
FWIW, I can reproduce it on our `macsim` machine.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpXDVG3qV-Sv5kXJvo:bw6mqal)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ipopt.BUILD, line 128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpZJkm09g-M2bFeciI:-KbpZJknT_8nhgmMc7Nq:b-ya2m0j) ([raw file](https://github.com/robotlocomotion/drake/blob/afaf1e1376bf4fa5b6bf7d0a5d5e94fbf8dfea16/tools/ipopt.BUILD#L128)):*
> ```
>         "-lgfortran",
>         "-ldl",
>         "-lquadmath",
> ```

Is there any way to get this via our `deps` on @gfortran?  It seems like all gfortran consumers should use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpZTgmMDIExsaTs65w:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ipopt.BUILD, line 128 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-KbpZJkm09g-M2bFeciI:-KbpdQmy_aEFb7qJ0Joq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/afaf1e1376bf4fa5b6bf7d0a5d5e94fbf8dfea16/tools/ipopt.BUILD#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is there any way to get this via our `deps` on @gfortran?  It seems like all gfortran consumers should use it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
:lgtm:

 - build check
 - test check

---

Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-KbpgITp3myf2UqRhKAE:b-gq85u1)*

**Comment by jwnimmer-tri** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4983#-:-Kbph_CI-T-lij-XtufY:b-uwkowd)*

**Pull request merged**
