### PR TITLE
register py::function as a (generic) cost function and/or (generic) constraint

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8373)

### CODE REVIEW

**Comment by RussTedrake** [comment]
super excited to have this capability.
+@ericcousineau-tri for feature review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-:-L7bPdmb-MMZJCzMrjBf:b-794opc)*

**Comment by EricCousineau-TRI** [comment]
Nice! First pass done on a minor consolidation, PTAL.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eG9lz2CrebAtG1AAY:-L7eG9m-tLQZV2wBAumS:be3p1ri) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L97)):*
> ```cpp
> }
> 
> class PyCost : public Cost {
> ```

Would it be possible to generalize this a bit (to minimize copy-pasta) by using `EvaluatorBase`?

Example:
```
class PyFunctionEvaluator : public EvaluatorBase {
  ...
};

...
      .def("AddConstraint", [](
          MathematicalProgram* self, py::function func, ...) {
        return self->AddConstraint(
           make_shared<ConstraintEvaluator<>>(
              make_shared<PyFunctionEvaluator>(lb.rows(), vars.size(), lb, ub, description), vars);
      }
      .def("AddCost", [](
          MathematicalProgram* self, py::function func, ...) {
        return self->AddCost(
           make_shared<CostEvaluator<>>(
              make_shared<PyFunctionEvaluator>(1, vars.size(), lb, ub, description), vars);
      }
```

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eHbaF4M4PqOkXJLvF:-L7eHbaGIBtekjN3nR7k:b-ljj0tk) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L97)):*
> ```cpp
> }
> 
> class PyCost : public Cost {
> ```

If the separate Cost and Constraint flavors are to remain, would it be possible to rename this to `PyFunctionCost` / `PyFunctionConstraint`, to distinguish it from `PyCost` if / when overriding these classes is possible in Python?

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eGJ0TbUoHcr4UUbJ9:-L7eGJ0TbUoHcr4UUbJA:b-sxt70w) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L163)):*
> ```cpp
>   py::object formula =
>     py::module::import("pydrake.symbolic").attr("Formula");
>   py::module::import("pydrake.autodiffutils");
> ```

BTW Could this ordering be made alphabetical?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-:-L7eHzugS6rDQ0WWQeyt:bihuwqy)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eG9lz2CrebAtG1AAY:-L7eIuviTYV6vDP8349D:b-lmbhu) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L97)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be possible to generalize this a bit (to minimize copy-pasta) by using `EvaluatorBase`?

Example:
```
class PyFunctionEvaluator : public EvaluatorBase {
  ...
};

...
      .def("AddConstraint", [](
          MathematicalProgram* self, py::function func, ...) {
        return self->AddConstraint(
           make_shared<ConstraintEvaluator<>>(
              make_shared<PyFunctionEvaluator>(lb.rows(), vars.size(), lb, ub, description), vars);
      }
      .def("AddCost", [](
          MathematicalProgram* self, py::function func, ...) {
        return self->AddCost(
           make_shared<CostEvaluator<>>(
              make_shared<PyFunctionEvaluator>(1, vars.size(), lb, ub, description), vars);
      }
```
</blockquote></details>

i thought about that, but notice that I chose to ask for a scalar return value in the cost case (not an Eigen::Vector<T>) because I think it's much cleaner.  As a result, almost every line is subtly different.  

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eHbaF4M4PqOkXJLvF:-L7eKEogU_BUFFtpLbnT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L97)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

If the separate Cost and Constraint flavors are to remain, would it be possible to rename this to `PyFunctionCost` / `PyFunctionConstraint`, to distinguish it from `PyCost` if / when overriding these classes is possible in Python?
</blockquote></details>

Done.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eGJ0TbUoHcr4UUbJ9:-L7eLbYsdVM7e3QZOUfd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L163)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could this ordering be made alphabetical?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eG9lz2CrebAtG1AAY:-L7ePsnF8VzLNi8OZMJa:b-kurfct) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L97)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i thought about that, but notice that I chose to ask for a scalar return value in the cost case (not an Eigen::Vector<T>) because I think it's much cleaner.  As a result, almost every line is subtly different.  
</blockquote></details>

Ah, I see, just tested out, and `pybind11` does not promote a scalar to a NumPy array, forgot about that! (was in MATLAB mode)

How would you feel about the following? (which passed for me)
https://github.com/EricCousineau-TRI/drake/commit/54f3e5991ce31de0544f7018f256818aaf943760

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eQ79WSncS0DPAJi8b:-L7eQ79WSncS0DPAJi8c:b-vwqp63) ([raw file](https://github.com/robotlocomotion/drake/blob/ed88ca7428dfc9f33525c41d9aed0b6c9f5bd0c9/bindings/pydrake/solvers/mathematicalprogram_py.cc#L103)):*
> ```cpp
>       : Cost(num_vars, description),
>         double_func_(
>             py::cast<std::function<double(const Eigen::VectorXd&)>>(func)),
> ```

BTW Can these function signatures be `typedef`d? `DoubleFunc`, `AutoDiffFunc`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373)*

**Comment by RussTedrake** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eG9lz2CrebAtG1AAY:-L7eWBzt9841rTAG4OR0:b1kishy) ([raw file](https://github.com/robotlocomotion/drake/blob/7d4405ad9aa7f790b98b1bc7f2a4ac4aa75c57e3/bindings/pydrake/solvers/mathematicalprogram_py.cc#L97)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Ah, I see, just tested out, and `pybind11` does not promote a scalar to a NumPy array, forgot about that! (was in MATLAB mode)

How would you feel about the following? (which passed for me)
https://github.com/EricCousineau-TRI/drake/commit/54f3e5991ce31de0544f7018f256818aaf943760
</blockquote></details>

sorry to admit it, but i actually like it less.  :-(   it's much harder to read (and accomplishes the same?). 

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7eQ79WSncS0DPAJi8b:-L7eWkMDKQN40pcaoMG8:b-jr4ppt) ([raw file](https://github.com/robotlocomotion/drake/blob/ed88ca7428dfc9f33525c41d9aed0b6c9f5bd0c9/bindings/pydrake/solvers/mathematicalprogram_py.cc#L103)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can these function signatures be `typedef`d? `DoubleFunc`, `AutoDiffFunc`?
</blockquote></details>

had considered that, too, but since there are only two uses of it, I passed.  I'm ok either way, and have made the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-:-L7ebkLFVxsGFsKEIYUx:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review, please.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-:-L7erhnw-qKvSL72yP8s:bxwr5c8)*

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for platform review, please.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-:-L7erhrYsIc4j1V3pcSK:bxwr5c8)*

**Comment by soonho-tri** [comment]
:lgtm: with a few BTW/FYIs.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 102 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7f_eUMgnINiPEd5TpI:-L7f_eUMgnINiPEd5TpJ:b-hnuhqf) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L102)):*
> ```cpp
>   using AutoDiffFunc = std::function<AutoDiffXd(const VectorX<AutoDiffXd>&)>;
> 
>   PyFunctionCost(int num_vars, py::function func,
> ```

BTW, META, `py::function` -> `const py::function&` in this file?

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 120 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7f_ns9Mcsi5uMgqAeV:-L7f_ns9Mcsi5uMgqAeW:bhgvyec) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L120)):*
> ```cpp
> 
>  private:
>   DoubleFunc double_func_;
> ```

BTW, can mark them as `const`

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 149 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7fa31KTjxKYyieSnbH:-L7fa31LVXovqz-zVs-Q:btcpap6) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L149)):*
> ```cpp
> 
>  private:
>   std::function<Eigen::VectorXd(const Eigen::VectorXd&)> double_func_;
> ```

BTW, for better readability, use the following?
```c++
  const DoubleFunc double_func_;
  const AutoDiffFunc autodiff_func_;
```

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 271 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-L7faK663OQxqVqEVVW-:-L7faK663OQxqVqEVVW0:bgwehcw) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L271)):*
> ```cpp
>             std::make_shared<PyFunctionConstraint>(vars.size(), func,
>                                                    lb, ub,
>                                          description),
> ```

BTW, here is a better indentation (it's sad that `clang-format` fights with `cpplint` in the file):
```c++
             return self->AddConstraint(
                 std::make_shared<PyFunctionConstraint>(vars.size(), func, lb,
                                                        ub, description),
                 vars);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8373#-:-L7faemApoVsICOKMT2Z:bt9u379)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 102 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373#-L7f_eUMgnINiPEd5TpI:-L7g2rnuAEC8uUZC9UuL:b-xujskt) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L102)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, META, `py::function` -> `const py::function&` in this file?
</blockquote></details>

OK `py::function` is actually a relatively lightweight class, memory-wise: it's simply a wrapper around `py::object` / `py::handle`, which basically just contains `PyObject*`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 102 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373#-L7f_eUMgnINiPEd5TpI:-L7g3CZQ4tTwmcHqJAfo:bb1qfyj) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK `py::function` is actually a relatively lightweight class, memory-wise: it's simply a wrapper around `py::object` / `py::handle`, which basically just contains `PyObject*`.
</blockquote></details>

OK. Feel free to keep it as it is.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 102 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373#-L7f_eUMgnINiPEd5TpI:-L7gCD8_5kXJ0ItM20Ri:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L102)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK. Feel free to keep it as it is.
</blockquote></details>

Done.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 120 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373#-L7f_ns9Mcsi5uMgqAeV:-L7gCFFTATNTeDB-Z8Ik:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L120)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, can mark them as `const`
</blockquote></details>

Done.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 149 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373#-L7fa31KTjxKYyieSnbH:-L7gCGZy1apbiHTw4As6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L149)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, for better readability, use the following?
```c++
  const DoubleFunc double_func_;
  const AutoDiffFunc autodiff_func_;
```
</blockquote></details>

Done.

---

*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 271 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373#-L7faK663OQxqVqEVVW-:-L7gCT0TDunRbBvBC-ki:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13b7636c57ea2dd0a85105008637b7c74f5ae533/bindings/pydrake/solvers/mathematicalprogram_py.cc#L271)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, here is a better indentation (it's sad that `clang-format` fights with `cpplint` in the file):
```c++
             return self->AddConstraint(
                 std::make_shared<PyFunctionConstraint>(vars.size(), func, lb,
                                                        ub, description),
                 vars);
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8373)*

**Pull request merged**
