### PR TITLE
[SAP] CompliantContactManager implements implicit joint damping

### PR DESCRIPTION
**Pull request by amcastro-tri**
Joint damping is one of the first things that will cause instabilities in a simulation. It must be treated implicitly in order to have a stable model.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@sherm1 for feature review please, this makes use of the ABA PR you reviewed last week.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077#-:-N1-bCsc5pDu0VI80Hks:bx16aox)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:
+@xuchenhan-tri for platform review per rotation, please

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077#-:-N15Af3l5ZI2xmHDB7SD:bghaael)* status: 12 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 569 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N14gobT-RsqyzreoEFW:-N152wIy-tj4wTecm9jH:bdni94k) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/compliant_contact_manager.cc#L569)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this doesn't look right. Shouldn't be a "v" on the rhs
</blockquote></details>

Should be:
` (M + dt⋅D)⋅(v−v₀)/dt = k₁(x₀) − D⋅v₀ = k(x₀)`
___
*[`multibody/plant/compliant_contact_manager.cc` line 626 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N1570yiErXFyCy9sBD1:-N1570yiErXFyCy9sBD2:b73o8cd) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/compliant_contact_manager.cc#L626)):*
> ```cpp
>   // implement a MultibodyPlant method to compute the per-tree mass matrices.
>   MatrixX<T> M(nv, nv);
>   plant().CalcMassMatrix(context, &M);
> ```

BTW it feels like a waste to calculate the full n² mass matrix only to extract the few meaningful blocks from it below. I presume there would be a reasonable way to just calculate the non-zero blocks directly. Worth a TODO here?
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 899 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N157yXA0lTrr0y__npj:-N157yXA0lTrr0y__npk:b-4sxtx6) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L899)):*
> ```cpp
>   SapSolver<double> sap;
>   // N.B. Here we keep in sync with the same parameters set by the contact
>   // manager. Updates of these parameters in the manager might require updating
> ```

minor: can you an EXPECT_EQ() check that the parameters here match the ones in the contact manager? If not, consider adding a comment where the manager's parameters are set noting that changes there must be reflected in the unit test.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 900 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N157q_0CHTFYIUQPwku:-N157q_0CHTFYIUQPwkv:b-3ysh8q) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L900)):*
> ```cpp
>   // N.B. Here we keep in sync with the same parameters set by the contact
>   // manager. Updates of these parameters in the manager might require updating
>   // the paremeters here.
> ```

typo: paremeters -> parameters
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N158fxSEP4GGRdjDBkE:-N158fxSEP4GGRdjDBkF:b-rqql2r) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L1112)):*
> ```cpp
>   }
> 
>   // Fixes all input ports to have zero actuation.
> ```

minor: this comment seems wrong -- values aren't zero below
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N158mM4AD8dNoK0vlPc:-N158mM4AD8dNoK0vlPd:bqsbfd8) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L1125)):*
> ```cpp
> 
>   // The manager solves free motion velocities using a discrete scheme with
>   // implicit joint dissipation. That is, it solves the momentum valance:
> ```

typo: valance -> balance
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N1598UJBq2_yn41Nrkc:-N1598UJBq2_yn41Nrkd:b-7q7qs5) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L1146)):*
> ```cpp
>         // For this model we expect 1 DOF revolute and prismatic joints only.
>         // ASSERT_EQ(joint_damping.size(), 1);
>         // ASSERT_EQ(joint.num_velocities(), 1);
> ```

BTW why commented out?
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1208 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N159_-F-v5h4PODdPeu:-N159_-F-v5h4PODdPev:bazik0y) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L1208)):*
> ```cpp
>         prismatic_joint.set_translation(context, 0.5 * joint_index);
>         prismatic_joint.set_translation_rate(context, 0.5 * joint_index);
>       }
> ```

BTW consider adding a final "else" here that throws to catch future model modifications where someone might stick in an unexpected joint type

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 626 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N1570yiErXFyCy9sBD1:-N15DWG40VWPeY-gqoZs:bivsf0t) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/compliant_contact_manager.cc#L626)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it feels like a waste to calculate the full n² mass matrix only to extract the few meaningful blocks from it below. I presume there would be a reasonable way to just calculate the non-zero blocks directly. Worth a TODO here?
</blockquote></details>

I agree of course.
yes, the TODO is right there above the call to CalcMassMatrix.

N.B. The computation still is `O(num_nonzero_entries)`, even though we use a dense storage for it. Still I agree, computing a `std::vector<MatrixX>` is the right thing to do.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 899 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N157yXA0lTrr0y__npj:-N15G4OC8-iN5oK14uTN:b-mysbm4) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/test/compliant_contact_manager_test.cc#L899)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: can you an EXPECT_EQ() check that the parameters here match the ones in the contact manager? If not, consider adding a comment where the manager's parameters are set noting that changes there must be reflected in the unit test.
</blockquote></details>

I made sure both use the same parameters. PTAL.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 626 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N1570yiErXFyCy9sBD1:-N15S0W5AzGejPw2d59f:b37gdgg) ([raw file](https://github.com/robotlocomotion/drake/blob/50ac001bb0cc46691383e915f5943bc021be53f3/multibody/plant/compliant_contact_manager.cc#L626)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I agree of course.
yes, the TODO is right there above the call to CalcMassMatrix.

N.B. The computation still is `O(num_nonzero_entries)`, even though we use a dense storage for it. Still I agree, computing a `std::vector<MatrixX>` is the right thing to do.
</blockquote></details>

Oh, yes I see the TODO now -- Reviewable didn't show it to me since it hadn't changed.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077#-:-N15rVjr7_Rr-_nMRzxX:bzus18)* status: 6 unresolved discussions (waiting on @amcastro-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15hDC91vLZw1WX6FWb:-N15hDC91vLZw1WX6FWc:b-jmxt04) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/compliant_contact_manager.cc#L59)):*
> ```cpp
>   // overrelaxation of Newton's method in regions where the cost is quadratic,
>   // or close to quadratic.
>   sap_parameters_.ls_alpha_max = 1.0 / sap_parameters_.ls_rho;
> ```

nit, would it be better just to default to this in SapParameters?
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 377 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15SZ18CfpFO-Snn_a1:-N15SZ197HdocUkHgqDD:b-oq8bh1) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L377)):*
> ```cpp
> 
>   // In the functions below we use CompliantContactManagerTest to provide access
>   // to private functions for unit testing.
> ```

nit, the second function in the list doesn't fit this description in the comment.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1091 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15rHDNBGCIz7QpjjMa:-N15rHDO3BgUb9mKLiHo:b-ug756f) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1091)):*
> ```cpp
> // Fixture to set up a Kuka iiwa arm model with a Schunk wsg gripper and welded
> // to the world at the base link.
> class KukaIiwaArmTests : public ::testing::Test {
> ```

nit, it'd be nice to document what this test does. i.e. it is used to verify implicit damping is done correctly.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15TyTYD6pfxDpxoZhA:-N15TyTYD6pfxDpxoZhB:b-rbyq75) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1113)):*
> ```cpp
> 
>   // Fixes all input ports to have non-zero actuation.
>   void SetArbitraryNonZeroActuation(const MultibodyPlant<double>& plant,
> ```

BTW, this can be private along with the rest of the helpers.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15UK_C2sZuK6kvgRfU:-N15UK_C2sZuK6kvgRfV:b-q76ac2) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1130)):*
> ```cpp
>   // external actuation, evaluated at the previous state x₀.
>   // The dynamics matrix is defined as:
>   //   A = ∂m/∂v = (M + dt⋅D)
> ```

nit, this line is inaccurate. We defined  `m(v) = (M + dt⋅D)⋅(v-v₀)/dt`m so  `A = ∂m/∂v = (M + dt⋅D) / dt`

  
 
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1210 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15dnfr43vF40CT2JVh:-N15dnfs94r4o3vudTwN:b-rygj5d) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1210)):*
> ```cpp
>       } else {
>         if (joint.num_velocities() > 0)  // skip weld joints.
>           std::runtime_error("Unexpected joint type.");
> ```

nit, we'd want to `throw` the exception, right?
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1223 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15fIbQ1bNxztFHrm9Y:-N15fIbQ1bNxztFHrm9Z:b3jinwy) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1223)):*
> ```cpp
>   CompliantContactManager<double>* manager_{nullptr};
>   std::unique_ptr<Context<double>> context_;
>   ModelInstanceIndex arm_model;
> ```

nit, missing trailing underscore.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1228 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15fmy3-7JUb15WA9dM:-N15fmy3-7JUb15WA9dN:blbhfbb) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1228)):*
> ```cpp
> 
> TEST_F(KukaIiwaArmTests, CalcLinearDynamicsMatrix) {
>   EXPECT_EQ(plant_.num_velocities(), kNumJoints);
> ```

BTW, this can be moved to the end of `SetUp`.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15hDC91vLZw1WX6FWb:-N19dz4G1ksCBzJzcgI0:bqtb2qt) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/compliant_contact_manager.cc#L59)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, would it be better just to default to this in SapParameters?
</blockquote></details>

good idea. Done.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1091 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15rHDNBGCIz7QpjjMa:-N19f6ks4_lY-orDW1ax:btqz5ns) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1091)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, it'd be nice to document what this test does. i.e. it is used to verify implicit damping is done correctly.
</blockquote></details>

I added specific comments in the instantiations below. The fixture itself is for kuka arms. In particular, I'll use it next to also verify joint limits.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15UK_C2sZuK6kvgRfU:-N19fmCA09BEa5uu4Oet:b-3c1xcn) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1130)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this line is inaccurate. We defined  `m(v) = (M + dt⋅D)⋅(v-v₀)/dt`m so  `A = ∂m/∂v = (M + dt⋅D) / dt`

  
 

</blockquote></details>

The typo is in m(v) really, not A. Fixed. Thanks.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1210 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15dnfr43vF40CT2JVh:-N19g0kH03EoChDyzDbF:baubr4p) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1210)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, we'd want to `throw` the exception, right?
</blockquote></details>

ha! good catch.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1228 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15fmy3-7JUb15WA9dM:-N19gOdFC-ObqVYvFPeM:bshjdi) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1228)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this can be moved to the end of `SetUp`.
</blockquote></details>

removed. Just a leftover of me prototyping efforts. (I usually compile with a dummy test to make sure I got the boilerplate right before moving on)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17077)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1091 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17077#-N15rHDNBGCIz7QpjjMa:-N19nvy-179f9qnXFz84:b-egt4g5) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec2ef43f2428491ddd591de0d9c21274ee111e0/multibody/plant/test/compliant_contact_manager_test.cc#L1091)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I added specific comments in the instantiations below. The fixture itself is for kuka arms. In particular, I'll use it next to also verify joint limits.
</blockquote></details>

I think it'd still be nice to describe what the test fixture does in the class description. In this case, you could say that the fixture provide test coverage on joint damping and limits. Non-blocking for this PR but please consider for the next one.

When going through MbP tests (which is a huge file), I often have a hard time telling what kind of test coverage a 300-line fixture provides without looking at the details. A comment at a central location could help with that.

**Comment by amcastro-tri** [comment]
I'll update test fixture comment in #17083

**Pull request merged**
