### PR TITLE
Revert "Ported car_sim_lcm to System 2.0"

### PR DESCRIPTION
**Pull request by liangfok**
Reverts RobotLocomotion/drake#3886

The error is:

```
12:53:47 /home/ubuntu/workspace/linux-clang-continuous-debug/drake/../drake/automotive/automotive_common.h:26:28: error: unknown type name 'RigidBodyTree'; did you mean 'RigidBodyTreed'?
12:53:47 void AddFlatTerrainToWorld(RigidBodyTree* tree,
12:53:47                            ^~~~~~~~~~~~~
12:53:47                            RigidBodyTreed
12:53:47 /home/ubuntu/workspace/linux-clang-continuous-debug/drake/../drake/systems/plants/RigidBodyTree.h:1206:31: note: 'RigidBodyTreed' declared here
12:53:47 typedef RigidBodyTree<double> RigidBodyTreed;
12:53:47                               ^
12:53:47 /home/ubuntu/workspace/linux-clang-continuous-debug/drake/automotive/automotive_common.cc:6:28: error: unknown type name 'RigidBodyTree'; did you mean 'RigidBodyTreed'?
12:53:47 void AddFlatTerrainToWorld(RigidBodyTree* tree, double box_size,
12:53:47                            ^~~~~~~~~~~~~
12:53:47                            RigidBodyTreed
12:53:47 /home/ubuntu/workspace/linux-clang-continuous-debug/drake/../drake/systems/plants/RigidBodyTree.h:1206:31: note: 'RigidBodyTreed' declared here
12:53:47 typedef RigidBodyTree<double> RigidBodyTreed;
12:53:47                               ^
12:53:47 2 errors generated.
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4015)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4015#-:-KVf6CoznlZKgZ8PHzO0:bnfp4nl)*

**Comment by liangfok** [comment]
FTR, this failure was caused by me not rebasing my PR with master prior to merging into master. It was not required because it was a no-conflict merge.

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4015#-:-KVf71xJ2_JL4ozu9gvB:b-qxjhdt)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Pull request merged**
