### PR TITLE
Set RPATH for "installed" binaries

### LINKED ISSUE #4840: Drake's version of `lcm-logger` fails with missing shared library
On OSX and Ubuntu 14.04, when attempting to run the version of `lcm-logger` that Drake installs, I get errors with missing `liblcm` shared libraries:

(Ubuntu 14.04):

```
 error while loading shared libraries: liblcm.so.1: cannot open shared object file: No such file or directory
```

(OSX):

```
dyld: Library not loaded: @rpath/liblcm.1.dylib
```

Both of these are on Drake master (from today).

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Set variables to tell CMake to set RPATH's in installed binaries. Propagate these to external projects.

Fixes #4840.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4883)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@rdeits, since my machine apparently RPATH's the installed `lcm-logger` no matter what, can you please verify that this actually fixes the issue for you?

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-KbGqkkbjwQ_aiEwmN-Z:-KbGqkkbjwQ_aiEwmN-_:b-g0gv6m) ([raw file](https://github.com/robotlocomotion/drake/blob/021aa6525b6e5595a8c702b98cec4e706781dff1/cmake/config.cmake#L255)):*
> ```CMake
>   set(CMAKE_INSTALL_RPATH
>     ${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}
>     ${CMAKE_INSTALL_PREFIX}/lib)
> ```

You are theoretically missing externals that use `GNUInstallDirs`. Add `DRAKE_INSTALL_LIBRARY_DIR`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 255 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-KbGqkkbjwQ_aiEwmN-Z:-KbGv1c8eYENq-wD9ttL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/021aa6525b6e5595a8c702b98cec4e706781dff1/cmake/config.cmake#L255)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You are theoretically missing externals that use `GNUInstallDirs`. Add `DRAKE_INSTALL_LIBRARY_DIR`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883)*

**Comment by jamiesnape** [comment]
:lgtm: if it fixes the problem for @rdeits.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-:-KbGxib27sHGJN6F1hcD:bxsw9we)*

**Comment by david-german-tri** [comment]
I'll await input from @rdeits before reviewing.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-:-KbHMSW8_Y9e-20H2EY5:btg5mf5)*

**Comment by rdeits** [comment]
Thanks! I'm building and testing this now. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-:-KbHUgiTG-4eLsKu58tn:b-wwt4vn)*

**Comment by rdeits** [comment]
:lgtm: Yup, this fixes the issue on Ubuntu. Thanks! 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-:-KbHVAYRfg5ltLJ8Re3Q:b1rw5pi)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4883#-:-KbHcg7o46lqQ4iDaTr-:bnfp4nl)*

**Comment by rdeits** [comment]
BTW, I also confirmed that this fixes the issue on OSX. Thanks again!

**Pull request merged**
