### PR TITLE
Add the ToSymbolic API, and implement it in Integrator.

### PR DESCRIPTION
**Pull request by david-german-tri**
@soonho-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4945)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbj03BTnEqC33oZaYo9:-Kbj03BUFoYAvQXy2bh_:b3dp1u7) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e890e9891c255546a2c083d30be15dba8c59f0/drake/systems/framework/diagram.h#L16)):*
> ```objc
> #include "drake/common/drake_copyable.h"
> #include "drake/common/number_traits.h"
> #include "drake/common/text_logging.h"
> ```

missing header `#include "drake/common/symbolic_expression.h`?

---

*[drake/systems/primitives/integrator.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbj0z1X0eWoHGWDDQ-I:-Kbj0z1YTqmAlazPaVRN:bga2b1k) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e890e9891c255546a2c083d30be15dba8c59f0/drake/systems/primitives/integrator.h#L5)):*
> ```objc
> #include <cstdint>
> #include <memory>
> ```

missing header "drake/common/symbolic_expression.h"?

---

*[drake/systems/primitives/integrator.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbj13t6odrj7AjrBRne:-Kbj13t6odrj7AjrBRnf:b-50mcgv) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e890e9891c255546a2c083d30be15dba8c59f0/drake/systems/primitives/integrator.h#L20)):*
> ```objc
> /// - double
> /// - AutoDiffXd
> ///
> ```

 `- symbolic::Expression`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbj03BTnEqC33oZaYo9:-KbkcGxpLXkxhZlw--Y2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e890e9891c255546a2c083d30be15dba8c59f0/drake/systems/framework/diagram.h#L16)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

missing header `#include "drake/common/symbolic_expression.h`?
</blockquote></details>

Done.

---

*[drake/systems/primitives/integrator.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbj0z1X0eWoHGWDDQ-I:-KbkcGBizPSMvJ7VCgz5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e890e9891c255546a2c083d30be15dba8c59f0/drake/systems/primitives/integrator.h#L5)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

missing header "drake/common/symbolic_expression.h"?
</blockquote></details>

Done.

---

*[drake/systems/primitives/integrator.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbj13t6odrj7AjrBRne:-KbkcGTBA_vUIvRHheKG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e890e9891c255546a2c083d30be15dba8c59f0/drake/systems/primitives/integrator.h#L20)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

 `- symbolic::Expression`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945)*

**Comment by david-german-tri** [comment]
+@sherm1 for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-:-KbkrWmeLMQRy2fwPnMK:buasbda)*

**Comment by sherm1** [comment]
Nice -- needs one comment glitch fixed, then :lgtm:.

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 722 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbll8qVpqqgZDOgWtIM:-Kbll8qVpqqgZDOgWtIN:b-9oihaf) ([raw file](https://github.com/robotlocomotion/drake/blob/3c870b811f2a820935c9bb27a6db813936d307b0/drake/systems/framework/system.h#L722)):*
> ```objc
>   ///   MySystem<double> plant;
>   ///   std::unique_ptr<MySystem<AutoDiffXd>> ad_plant =
>   ///       systems::System<double>::ToAutoDiffXd<MySystem>(plant);
> ```

BTW, copy/paste historical artifact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-:-KblmR56b7XzgC89sYkb:b-9nva9w)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/framework/system.h, line 722 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4945#-Kbll8qVpqqgZDOgWtIM:-KblqcrbNiXaP3mOvdbN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c870b811f2a820935c9bb27a6db813936d307b0/drake/systems/framework/system.h#L722)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, copy/paste historical artifact.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4945)*

**Pull request merged**
