### PR TITLE
Configure camera position from Meshcat

### LINKED ISSUE #19885: Support "SetCameraTarget" in Meshcat
[Meshcat supports a `set_target`](https://github.com/rdeits/meshcat/blob/master/Readme.md) command for setting "the target of the 3D camera, around which it rotates."  We should add this support to Drake's Meshcat c++.

Requested by @pathammer .

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
- Add `Meshcat::SetCameraTarget()` for positioning a perspective camera's target point. The camera orients to face that target.
- Add `Meshcat::SetCameraPose()` for placing the target and camera at the same time.
  - This provides unique benefit in posing them both in Drake's z-up world. (and not three.js's y-up world).
- incidental clean up
    - typos 
    - removing unnecessary use of `unused`.
    - Updates the green cube used in meshcat_manual_test.cc to make environment illumination more apparent.

closes #19885

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@RussTedrake for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-NbO3y3e1B0EeB1Hlsh-:b-cb1jey)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by RussTedrake — COMMENTED** [review]
Woohoo!  Thanks @SeanCurtis-TRI .  This looks great.  Comments below.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-NbxoSFC7Gs5NaEq4VTq:b-f1kg4p)* status: 8 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.h` line 453 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxkpR9BlDesMQAjB4e:-NbxkpR9BlDesMQAjB4f:bttnrti) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L453)):*
> ```objc
> 
>   /** A convenience function for positioning the camera and its view target
>    in the world frame.
> ```

Obviously the single vector doesn't fully specify the pose... presumably the last free rotation DOF is chosen to make camera up point towards z up?  Could you document the choice that's being made?
___
*[`geometry/meshcat.h` line 465 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-Nbxjlrt2bVLzfN9Qljt:-Nbxjlrt2bVLzfN9Qlju:bujusw3) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L465)):*
> ```objc
>    @param target_in_world the position of the target point T in Drake's z-up
>                world frame (p_WT). */
>   void PoseCamera(const Eigen::Vector3d& camera_in_world,
> ```

Perhaps `SetCameraPose`?
___
*[`geometry/meshcat.h` line 467 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxksWR7dhJCviARdFz:-NbxksWR7dhJCviARdG-:bq61fdm) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L467)):*
> ```objc
>   void PoseCamera(const Eigen::Vector3d& camera_in_world,
>                   const Eigen::Vector3d& target_in_world);
> ```

It it worth also providing a variant SetCameraPose(RigidTransform X_WC)?
___
*[`geometry/meshcat.cc` line 1070 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxlIb_5hWy37U8lu5Q:-NbxlIb_5hWy37U8lu5R:b-xgh7y9) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.cc#L1070)):*
> ```cpp
>     data.path = std::move(path);
>     data.object.object = std::move(camera);
>     SetCameraTarget({0, 0, 0});
> ```

why this?  and why before setting the camera?
___
*[`geometry/test/meshcat_manual_test.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-Nbxmpx-86VVIhy2hkZB:-Nbxmpx0-Zh2hg4lMJre:b-om8zbk) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L50)):*
> ```cpp
> 
>   // For animation, we'll aim the camera between the cylinder and ellipsoid.
>   const Vector3d animation_target{x + 0.5, 0, 0};
> ```

add this to the text instructions/description?
___
*[`geometry/test/meshcat_manual_test.cc` line 251 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxnXyT1cHMIbMRTSdI:-NbxnXyT1cHMIbMRTSdJ:b4m0c5v) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L251)):*
> ```cpp
>   std::cout << "- The scene should have switched to 2D rendering mode.\n";
>   std::cout << "[Press RETURN to continue]." << std::endl;
>   std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
> ```

for some reason, i'm seeing
```
- The scene should have switched to 2D rendering mode.
[Press RETURN to continue].
[Press RETURN to continue].

- Now 2D rendering along the +x axis (red sphere in front).
```
(two return to continue messages here)
___
*[`geometry/test/meshcat_manual_test.cc` line 267 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxnlkRDI1JeF4iq5Zd:-NbxnlkRDI1JeF4iq5Ze:b-ys4s0y) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L267)):*
> ```cpp
>   meshcat->PoseCamera(Vector3d{2, 2, 2}, Vector3d::Zero());
>   std::cout << "- Now we have an isometric 3/4 view. The camera is no longer "
>                "locked.\n";
> ```

i didn't know that the camera was locked?  
___
*[`geometry/test/meshcat_manual_test.cc` line 439 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxoFnZ5L7KWSmWFJzi:-NbxoFnZ5L7KWSmWFJzj:b-sgcv56) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L439)):*
> ```cpp
>   std::cout << "A standalone HTML file capturing this scene (including the "
>                "animation, environment map, and camera targeted at the contact "
>                "point) has been written to:\n"
> ```

the environment map is there in the video, but not in my main meshcat window that's running the text.  i expected to see them visually identical.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968)* status: 8 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/test/meshcat_manual_test.cc` line 439 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxoFnZ5L7KWSmWFJzi:-NbyvxlBAtuOR4a1W7dr:bmo3vl2) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L439)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the environment map is there in the video, but not in my main meshcat window that's running the text.  i expected to see them visually identical.
</blockquote></details>

This also tripped me up the first time.  (We should improve the text.)

My browser window didn't show the environment map until I panned it with my mouse.  Some kind of redraw glitch.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've addressed your comments. But my solutions may still bear examination and discussion.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-Nc06Y5K2jqXn2ID77sS:bdylng8)* status: 8 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.h` line 453 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxkpR9BlDesMQAjB4e:-Nc-oTvaB3b6wwFM21TU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L453)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Obviously the single vector doesn't fully specify the pose... presumably the last free rotation DOF is chosen to make camera up point towards z up?  Could you document the choice that's being made?
</blockquote></details>

Done.
___
*[`geometry/meshcat.h` line 465 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-Nbxjlrt2bVLzfN9Qljt:-Nc-ouNIEWBF43EBuoa8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L465)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Perhaps `SetCameraPose`?
</blockquote></details>

Done.
___
*[`geometry/meshcat.h` line 467 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxksWR7dhJCviARdFz:-Nc-necI9Ve2Nv1ICqYb:b-k4o8c) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L467)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

It it worth also providing a variant SetCameraPose(RigidTransform X_WC)?
</blockquote></details>

I'd considered that one but rejected it. Because of the nature of the orbital camera control, we have to define a point around which we orbit. Otherwise, you may get a very meaningful initial camera pose, but interacting with the scene becomes madness.

That said, I *could* see a variant that takes a `RigidTransform` *and* a distance (i.e., how far in front of the camera does the pivot point lie). 

Thoughts?
___
*[`geometry/meshcat.cc` line 1070 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxlIb_5hWy37U8lu5Q:-Nc-sB5v3ekeZAaP05kY:bddd9eh) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.cc#L1070)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why this?  and why before setting the camera?
</blockquote></details>

With the ability to set the camera target, it seemed to be saner to make sure that the target was reset every time we set the camera. I wrote this 8 days ago now, so I can't remember the exact symptom this was in response to, but the principle seems clear in my mind.
___
*[`geometry/test/meshcat_manual_test.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-Nbxmpx-86VVIhy2hkZB:-Nc0-p-c8lPZ33pY83v3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L50)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

add this to the text instructions/description?
</blockquote></details>

Done.
___
*[`geometry/test/meshcat_manual_test.cc` line 251 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxnXyT1cHMIbMRTSdI:-Nc-vWIs34VwTR7uApcW:b-db27f0) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L251)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

for some reason, i'm seeing
```
- The scene should have switched to 2D rendering mode.
[Press RETURN to continue].
[Press RETURN to continue].

- Now 2D rendering along the +x axis (red sphere in front).
```
(two return to continue messages here)
</blockquote></details>

That seems to be a leftover relic from #19971. It replaced the "Press RETURN" boilerplate with the new method `MaybePauseForUser()`. I've updated things locally to clean it up.
___
*[`geometry/test/meshcat_manual_test.cc` line 267 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxnlkRDI1JeF4iq5Zd:-Nc-whmx6Jq--ACrmRy3:b7ursua) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L267)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i didn't know that the camera was locked?
</blockquote></details>

I'm running master now, and the original behavior was not as simple as "locked".

1. In the first 2D mode, you can pan and zoom, but *not* rotate. In asserting it being "locked", I guess I only tried rotating.
2. The second 2D view has stranger behavior. You can zoom, but only rotate around the world's z-axis and *not* pan.

The PR hadn't changed that initial behavior.

From reading the code for `Set2dRenderMode`, it's clear that the *intention* was to lock the orbit controls. In the case of the second 2D view, that didn't quite work.

In the next revision, I've tweaked it so things *aren't* locked in 2D view. That has the advantage of making all the views behave the same (more or less). But its flaw is that as you pan and rotate, the apparent pivot point doesn't quite work the same way with an orthographic camera as it does with a perspective camera. Furthermore, it implies there's a bandaid that needs to be applied after `Set2DRenderMode()` is called. We need to do more groundwork to figure out what's happening. Probably a topic for a different PR.

So, we have two options:

1. We can go with the newest revision that applies a band-aid to leave the orthographic views unlocked, or
2. I can restore the behavior in master and just indicate that in the 3/4 view, all camera manipulation dofs are available.
___
*[`geometry/test/meshcat_manual_test.cc` line 439 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxoFnZ5L7KWSmWFJzi:-Nc-scw-EasrHL4h-x8H:b9bnbsq) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L439)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This also tripped me up the first time.  (We should improve the text.)

My browser window didn't show the environment map until I panned it with my mouse.  Some kind of redraw glitch.
</blockquote></details>

Right. The fact that the map is added for static html export, but not appreciably in the main window. I hope I've updated the text sufficiently to account for it.

It's worth emphasizing, that in this *particular* instance, I had no expectation that a user would see the environment map nor camera movement.

That said, I have seen an occasional redraw glitch. Every once in a while setting the environment map doesn't trigger the redraw like it should. It's never consistent, however.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.h` line 467 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxksWR7dhJCviARdFz:-Nc232qO6_oD1pmbqYgS:b54pzt4) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L467)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd considered that one but rejected it. Because of the nature of the orbital camera control, we have to define a point around which we orbit. Otherwise, you may get a very meaningful initial camera pose, but interacting with the scene becomes madness.

That said, I *could* see a variant that takes a `RigidTransform` *and* a distance (i.e., how far in front of the camera does the pivot point lie). 

Thoughts?
</blockquote></details>

I hadn't considered that subtlety.  A RigidTransform and a distance could be nice; there might even be reasonable defaults for the distance (e.g. 1m?).

Even a TODO capturing that idea would be great.
___
*[`geometry/test/meshcat_manual_test.cc` line 267 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxnlkRDI1JeF4iq5Zd:-Nc25foT3-F3gWW8LnKJ:bb2r8wi) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L267)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm running master now, and the original behavior was not as simple as "locked".

1. In the first 2D mode, you can pan and zoom, but *not* rotate. In asserting it being "locked", I guess I only tried rotating.
2. The second 2D view has stranger behavior. You can zoom, but only rotate around the world's z-axis and *not* pan.

The PR hadn't changed that initial behavior.

From reading the code for `Set2dRenderMode`, it's clear that the *intention* was to lock the orbit controls. In the case of the second 2D view, that didn't quite work.

In the next revision, I've tweaked it so things *aren't* locked in 2D view. That has the advantage of making all the views behave the same (more or less). But its flaw is that as you pan and rotate, the apparent pivot point doesn't quite work the same way with an orthographic camera as it does with a perspective camera. Furthermore, it implies there's a bandaid that needs to be applied after `Set2DRenderMode()` is called. We need to do more groundwork to figure out what's happening. Probably a topic for a different PR.

So, we have two options:

1. We can go with the newest revision that applies a band-aid to leave the orthographic views unlocked, or
2. I can restore the behavior in master and just indicate that in the 3/4 view, all camera manipulation dofs are available.
</blockquote></details>

Urgh.  I agree that the second 2D render mode camera controls are broken.  But (as evidenced by the fact that I hadn't noticed that), I almost always use the first view... and use that heavily.  I would strongly prefer to restore the master branch behavior for now until we can fix it properly.  Can you open an issue to track it?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.h` line 464 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-Nc2G2eU-r-CKEb9xdhq:-Nc2G2eU-r-CKEb9xdhr:b-aow925) ([raw file](https://github.com/RobotLocomotion/drake/blob/64743e82587de3510cde7af2d3018cf68ce6cddb/geometry/meshcat.h#L464)):*
> ```objc
> 
>    @note This is Drake's z-up world frame and not the three.js world frame
>    you'd have to use if you set the "position" on the camera directly.
> ```

btw -- i can imagine a follow-up user request to support animation of the camera position.  You could pass through the `time_in_recording` to SetTransform and SetProperty easily enough. It looks like the SetCameraTarget portion would require a touch-up on the meshcat side?

It *might* be worth considering adding the `time_in_recording` now and just documenting that the camera target is not updated in the animation, because it's not supported by meshcat yet.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri 
@RussTedrake, this will need your tag as well.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-Nc5W4YV8OZB4QqIDgX5:b-bmeat0)* status: 1 unresolved discussion, LGTM missing from assignees RussTedrake(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.h` line 467 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxksWR7dhJCviARdFz:-Nc5OAAE74A-roVqR8Hc:bu2cvge) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/meshcat.h#L467)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I hadn't considered that subtlety.  A RigidTransform and a distance could be nice; there might even be reasonable defaults for the distance (e.g. 1m?).

Even a TODO capturing that idea would be great.
</blockquote></details>

I came across that subtlety by my earlier efforts and setting the camera pose via setting the camera's transform. Kind of works, but leads to interactive madness.

I'll go with a TODO for now. I worry about getting into fights with the orbit controller.
___
*[`geometry/meshcat.h` line 464 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-Nc2G2eU-r-CKEb9xdhq:-Nc5NnD-1VvHBf6eWeYK:b5r37ye) ([raw file](https://github.com/RobotLocomotion/drake/blob/64743e82587de3510cde7af2d3018cf68ce6cddb/geometry/meshcat.h#L464)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i can imagine a follow-up user request to support animation of the camera position.  You could pass through the `time_in_recording` to SetTransform and SetProperty easily enough. It looks like the SetCameraTarget portion would require a touch-up on the meshcat side?

It *might* be worth considering adding the `time_in_recording` now and just documenting that the camera target is not updated in the animation, because it's not supported by meshcat yet.
</blockquote></details>

For now, I'm inclined towards a TODO.

It seems regrettable to offer up an API that will be fundamentally broken. Ultimately, the *right* API to make animatable will be the one that simply takes a `RigidTransform` for camera pose.

I tried it and while you can animate the camera's *position*, you can't animate its orientation. The camera moves, but the target remains stationary and and as the camera moves, it stays focused on the target.
___
*[`geometry/test/meshcat_manual_test.cc` line 267 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NbxnlkRDI1JeF4iq5Zd:-Nc5Vwen5jPuMUkFreAy:b-wk5vq0) ([raw file](https://github.com/RobotLocomotion/drake/blob/abe4504076dff0f36ce0e7085820fc77b05b891d/geometry/test/meshcat_manual_test.cc#L267)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Urgh.  I agree that the second 2D render mode camera controls are broken.  But (as evidenced by the fact that I hadn't noticed that), I almost always use the first view... and use that heavily.  I would strongly prefer to restore the master branch behavior for now until we can fix it properly.  Can you open an issue to track it?
</blockquote></details>

Restored and issued. #20020

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-Nc7kMWU011rdK1sAB2W:bnfp4nl)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 
+(release notes: feature) 

> Reviewed 1 of 8 files at r1, 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-NcOOmI56A67Tbvum0Mm:bgy94m2)* status: 4 unresolved discussions

___
*[`geometry/meshcat.h` line 451 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcOFa7F2GCZnIwhSgxU:-NcOFa7F2GCZnIwhSgxV:b-8yqfu1) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/meshcat.h#L451)):*
> ```objc
>    position will cause the camera orientation to return to its default
>    orientation (looking along the +Wy axis with +Wz up) and lock the camera so
>    that it can't be rotated, panned, or zoomed.
> ```

BTW, my take-away from this warning is: "you probably don't want to do this". Is that correct?
Also, I don't understand why this would happen. Could you explain?



_Code quote:_
```objc
   @warning Setting the target position to be coincident with the camera
   position will cause the camera orientation to return to its default
   orientation (looking along the +Wy axis with +Wz up) and lock the camera so
   that it can't be rotated, panned, or zoomed.
```
___
*[`geometry/meshcat.cc` line 1286 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcOJNtkEuUfTQIfL8NQ:-NcOJNtkEuUfTQIfL8NR:bj5vzex) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/meshcat.cc#L1286)):*
> ```cpp
> 
>     internal::SetCameraTargetData data;
>     // The pose is given in Drake's z-up world. We need to rotate it to a
> ```

nit, do we simply need to transform to **a**  y-up world or do we need **this specific** y-up world? If the latter, consider moving this transform to a helper for documentation and reuse (the same transform is used in the SetCameraPose() below).
___
*[`geometry/test/meshcat_manual_test.cc` line 302 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcONNJmAnXPclkMGBC1:-NcONNJmAnXPclkMGBC2:bygtqus) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/test/meshcat_manual_test.cc#L302)):*
> ```cpp
> 
>   std::cout << "- The Cornell box has been replaced by a room with brick walls "
>             << "loaded from a jpg.\n";
> ```

BTW, likely unrelated to this PR: this didn't happen for me until I interact with the viewer.



_Code quote:_
```cpp
  std::cout << "- The Cornell box has been replaced by a room with brick walls "
            << "loaded from a jpg.\n";
```
___
*[`geometry/test/meshcat_manual_test.cc` line 308 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcONgLbCesj-MhKf5j_:-NcONgLbCesj-MhKf5ja:b-tvjyh8) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/test/meshcat_manual_test.cc#L308)):*
> ```cpp
>   meshcat->SetCameraTarget(Vector3d::Zero());
>   meshcat->Delete();
>   std::cout << "- Everything else should have disappeared." << std::endl;
> ```

BTW, not sure what "else" is referring to.



_Suggestion:_
```cpp
std::cout << "- Everything should have disappeared." << std::endl;
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968)* status: 5 unresolved discussions

___
*[`geometry/meshcat.h` line 473 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcOGkdr9-WA91fb2yhy:-NcOGkdr9-WA91fb2yhz:bx5d5j0) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/meshcat.h#L473)):*
> ```objc
>    @param target_in_world the position of the target point T in Drake's z-up
>                world frame (p_WT). */
>   void SetCameraPose(const Eigen::Vector3d& camera_in_world,
> ```

BTW I wonder what happens if `camera_in_world == target_in_world`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-NcPsOxw7a3kdOB1lXvj:b-ucfknh)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

___
*[`geometry/meshcat.h` line 451 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcOFa7F2GCZnIwhSgxU:-NcPpAoZAwMf71w4UHBj:bt7ib8d) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/meshcat.h#L451)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, my take-away from this warning is: "you probably don't want to do this". Is that correct?
Also, I don't understand why this would happen. Could you explain?
</blockquote></details>

I don't fully understand. Its explanation rests in bowels of three.js's OrbitController. I haven't delved into that yet.

However, based on your other comment, I've decided to make the language a vaguer scary warning. It leads to undefined behavior.
___
*[`geometry/meshcat.cc` line 1286 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcOJNtkEuUfTQIfL8NQ:-NcPr8KfCY7B6Nr6t9gg:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/meshcat.cc#L1286)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, do we simply need to transform to **a**  y-up world or do we need **this specific** y-up world? If the latter, consider moving this transform to a helper for documentation and reuse (the same transform is used in the SetCameraPose() below).
</blockquote></details>

Done
___
*[`geometry/test/meshcat_manual_test.cc` line 302 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-NcONNJmAnXPclkMGBC1:-NcPrG_uDqh21jh2P442:bakeo5g) ([raw file](https://github.com/RobotLocomotion/drake/blob/b6b4401f44eef75cd2c77d37b2dfbe20459f2163/geometry/test/meshcat_manual_test.cc#L302)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, likely unrelated to this PR: this didn't happen for me until I interact with the viewer.
</blockquote></details>

It's intermittent. I bet if you ran it several times, most times it would world. I'm not sure where the erratic behavior comes from.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968#-:-NcQaYc18sSR2KOsPeuP:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19968)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

**Comment by Vinggui** [comment]
Nice PR!
Just one more question: Do we have something like `SetCameraPosition(...)` (in case I don't want to change my target)? It seems like the `SetCameraPose()` could be just a combo of target and position.
Thoughts?

**Comment by SeanCurtis-TRI** [comment]
The incantation for doing that now (without guarantees as to robustness) is:

```c++
  const Vector3d p_WC{x, y, z};
  // Setting the camera position directly must be expressed in three.js's y-up
  // world. The rotation from Drake to three.js is a 90° rotation around Wx.
  meshcat->SetProperty("/Cameras/default/rotated/<object>", "position",
                       std::vector<double>{p_WC.x(), p_WC.z(), -p_WC.y()});
```

That said, if we make `p_WT` optional, then we can probably give you that functionality (and bury the rotation between drake and three.js). We probably can't detect incipient problems, but that's no worse than where you are today in that regard. It seems relatively harmless. If I create a quick PR, would you be willing to take it for a test drive?

**Comment by Vinggui** [comment]
> The incantation for doing that now (without guarantees as to robustness) is:
> 
> ```c++
>   const Vector3d p_WC{x, y, z};
>   // Setting the camera position directly must be expressed in three.js's y-up
>   // world. The rotation from Drake to three.js is a 90° rotation around Wx.
>   meshcat->SetProperty("/Cameras/default/rotated/<object>", "position",
>                        std::vector<double>{p_WC.x(), p_WC.z(), -p_WC.y()});
> ```
> 
> That said, if we make `p_WT` optional, then we can probably give you that functionality (and bury the rotation between drake and three.js). We probably can't detect incipient problems, but that's no worse than where you are today in that regard. It seems relatively harmless. If I create a quick PR, would you be willing to take it for a test drive?

I can give it a try, for sure. I believe it would work too and give us even more flexibility.

**Pull request merged**
