### PR TITLE
Revert "restore mathematical program test (using the python bindings)…"

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Dear @RussTedrake ,

The on-call build cop, @SeanCurtis-TRI, believes that your PR #6706  may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-continuous-matlab-release/16/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6716)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
If I am reading the build logs correctly, when #6705 merged the build failure noted here went away.  I don't understand why yet, but at least that means that this PR probably doesn't need to merge.

**Comment by jwnimmer-tri** [comment]
Post-#6705, this test reports as:
```
226: {Undefined function or variable 'javaaddpathProtectGlobals'.
226: 
226: Error in addpath_drake>javaaddpathIfNew (line 82)
226:    javaaddpathProtectGlobals(p);
226: 
226: Error in addpath_drake (line 68)
226:  javaaddpathIfNew(jarfiledir);
226: 
226: Error in addpath_drake (line 8)
226:   addpath_drake();
226: } 
226: Matlab test  output:
226: 
226:                             < M A T L A B (R) >
226:                   Copyright 1984-2017 The MathWorks, Inc.
226:                    R2017a (9.2.0.556344) 64-bit (glnxa64)
226:                                March 27, 2017
226: 
226:  
226: To get started, type one of these: helpwin, helpdesk, or demo.
226: For product information, visit www.mathworks.com.
226:  
226: [Warning: Name is nonexistent or not a directory:
226: /home/ubuntu/workspace/linux-xenial-gcc-continuous-matlab-release/drake/matlab/util/geometry] 
226: [> In path (line 109)
226:   In addpath (line 88)
226:   In addpath_drake (line 31)
226:   In addpath_drake (line 8)] 
226: [Warning: Name is nonexistent or not a directory:
226: /home/ubuntu/workspace/linux-xenial-gcc-continuous-matlab-release/drake/matlab/util/visualization] 
226: [> In path (line 109)
226:   In addpath (line 88)
226:   In addpath_drake (line 32)
226:   In addpath_drake (line 8)] 
226: {Undefined function or variable 'javaaddpathProtectGlobals'.
226: 
226: Error in addpath_drake>javaaddpathIfNew (line 82)
226:    javaaddpathProtectGlobals(p);
226: 
226: Error in addpath_drake (line 68)
226:  javaaddpathIfNew(jarfiledir);
226: 
226: Error in addpath_drake (line 8)
226:   addpath_drake();
226: } 
226: 

Test #226: matlab/solvers/test/testMathematicalProgram .......   Passed    6.62 sec
```

**Comment by jwnimmer-tri** [comment]
So the next steps here are for someone to fix the MATLAB tests to report an error when they crash, and then fix `addpath_drake` to not crash, and then to fix `testMathematicalProgram.m` for whatever was going wrong before it got disabled.

**Comment by RussTedrake** [comment]
agreed.  thanks @jwnimmer-tri .  fwiw -- i think that `addpath_drake.m`, is the only `.m` file that needs to remain in the `drake/matlab` directory; the rest can go.  And `addpath_drake` can be reduced to something as simple a few calls to `addpath`; we aren't using the lcm.jar, etc that required the more substantial logic in the current addpath.  But agreed that we need to fix the test handling first.

cc @jamiesnape

**Comment by RussTedrake** [comment]
i'll PR my proposal for `addpath_drake`.

**Comment by SeanCurtis-TRI** [comment]
I'm closing this as no longer relevant.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6716#-:-KqdHTGyzNgavdG9pvzm:b-cey184)*

**Pull request closed without merging**
