### PR TITLE
[doc] Add process for release notes PR tags

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As requested by @EricCousineau-TRI while preparing the most recent release (v0.31.0).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15339)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri to begin review, please -- you are next on deck for the next release in a week or two.  (Once we have consensus on the policy, I can help upgrade the tool to automate this.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: This language is excellent.
FYI, I was planning to take a first pass at running the release notes tool today to get a sense of where we are.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15339#-:-Me51GQv0QlGExaESuqh:b4e6zpo)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
FYI my plan for `relnotes.py` was that it will only check the label when scraping the commit for the first time.  For this coming release, would you like us to try to get the tool working so you can have it help automate your draft from the get-go?  We can probably share a feature branch and get it done in a couple hours.

The alternative is to keep doing the manual process, possibly made easier by manually filtering the https://github.com/RobotLocomotion/drake/pulls by the label and nixing those quickly by hand.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15339#-:-Me5t3B6AIqxOlh_70LW:bmxilld)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Pull request merged**
