### PR TITLE
Polished doxygen comments for RigidBody's member variables.

### PR DESCRIPTION
**Pull request by liangfok**
I left off documentation for the collision-related variables since I believe @amcastro-tri is redoing that anyway.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2687)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review
@david-german-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-:-KLNgg6yuAyJPDHsOn9X:300502490)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-:-KLNlExyselLYsn_RMly:1417088721)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNlgJtHyiAVLR_w72z:-KLNlgJtHyiAVLR_w73-:-743601316) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L165)):*
> ```objc
> 
>   /// The starting index of this rigid body's joint's position value(s) within
>   /// the output of a RigidBodySystem.
> ```

Consider: 
"The starting index of this rigid body's joint's position value(s) within the parent tree's state vector."

In principle, RBT is an independent module from RBS. That is why I am trying to avoid mentioning RBS here.

---

*[drake/systems/plants/RigidBody.h, line 170 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNlyzf8LdB_6Vwp9E4:-KLNlyzgtcLYNjkSF323:-869701161) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L170)):*
> ```objc
>   /// The starting index of this rigid body's joint's velocity value(s) within
>   /// the output of a RigidBodySystem.
>   int velocity_num_start;
> ```

Consider:
"The starting index of this rigid body's joint's velocity value(s) within the parent tree's state vector."

---

*[drake/systems/plants/RigidBody.h, line 172 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNmhIRngQstbr8FQn5:-KLNmhIRngQstbr8FQn6:-1678440069) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L172)):*
> ```objc
>   int velocity_num_start;
> 
>   /// The visualization of this rigid body.
> ```

"List of visual elements for this RigidBody".

---

*[drake/systems/plants/RigidBody.h, line 187 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNoiLlZsueqAmsSdSX:-KLNoiLmwrAmKS5C-txr:610283390) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L187)):*
> ```objc
>   Eigen::Vector3d com;
> 
>   /// The inertia matrix of this rigid body.
> ```

"Spatial rigid body inertia."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2687)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNlgJtHyiAVLR_w72z:-KLOBeKLm-EpML179MZY:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider: 
> "The starting index of this rigid body's joint's position value(s) within the parent tree's state vector."
> 
> In principle, RBT is an independent module from RBS. That is why I am trying to avoid mentioning RBS here.
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 170 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNlyzf8LdB_6Vwp9E4:-KLOBe-RAT9tsEq05ptE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L170)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider:
> "The starting index of this rigid body's joint's velocity value(s) within the parent tree's state vector."
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 172 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNmhIRngQstbr8FQn5:-KLOBcgJoNADYUpFSgm8:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "List of visual elements for this RigidBody".
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 187 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-KLNoiLlZsueqAmsSdSX:-KLOBoNrZBwOCeAB9bHm:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f9876daca30c814bb3245cac2f93387b60d1c183/drake/systems/plants/RigidBody.h#L187)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> "Spatial rigid body inertia."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-:-KLOBp_ZBHcPM_TcWqQ-:-84625242)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2382/ and is thus ready for another round of review.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-:-KLQQCD0K1wn0faE-Ihm:1733019059)*

**Comment by amcastro-tri** [comment]
Thanks for adding those comment @liangfok, :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2687#-:-KLRAiQhLIGqGWRHP-N6:-1848508485)*

**Pull request merged**
