### PR TITLE
Partially revert "Replace `"${var[@]:-}"` with `"${var[@]}"`"

### PR DESCRIPTION
**Pull request by svenevs**
Reverts RobotLocomotion/drake#16666

Dear @EricCousineau-TRI 

 The on-call build cop, @svenevs , believes that your PR #16666 may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failures under investigation are:

- https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-packaging/1233/consoleFull
- `/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-packaging/src/setup/mac/install_prereqs.sh: line 40: binary_distribution_args[@]: unbound variable`
- Alternative to reverting could be to guarantee this variable is at least created as an empty array?  macOS bash is 3.x.  In potential future or alternative fixes, add a mac unprovisioned build to verify the change.

 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16672)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-packaging please.

**Comment by EricCousineau-TRI** [comment]
I can also file the separate PR if you like.

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-packaging please.

**Review by svenevs — COMMENTED** [review]
Modified the revert to just the macOS section, expected reason is antiquated `bash` running the `setup` script (mac cannot ship bash 4, why they switched to `zsh`).

:lgtm: provided the [mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-packaging](https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-packaging/4/) build succeeds.

+@ericcousineau-tri for review once that is complete :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16672#-:-MwloJ3u8lQLsUJWDSLi:bp5blt3)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16672#-:-MwlrQ076DerxQucyesY:bpqxd5f)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @svenevs)

___
*[setup/mac/install_prereqs.sh, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16672#-MwlrS8CE5MYb17OVf1x:-MwlrS8CE5MYb17OVf1y:bxtuytk) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b112550d168c9c8b18d31bfdc0ba832c4b68e8/setup/mac/install_prereqs.sh#L41)):*
> ```Shell
> 
> source "${BASH_SOURCE%/*}/binary_distribution/install_prereqs.sh" \
>   "${binary_distribution_args[@]:-}"
> ```

BTW Consider mentioning that we keep `${var:-}` here to quell mac's old version of bash?

e.g.
```
# N.B. We need `${var:-}` here because mac's older version of bash does
# not seem to be able to cope with an empty array.
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16672)* status: 1 unresolved discussion (waiting on @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16672#-Mwlri7-AlkODzXzh-Y3:-Mwlri707PIdabuL5C-V:b-c06t3l) (no related file):*
(non-blocking, but prevents merge) Should ensure build job completes
https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-packaging/4/

---

**Review by svenevs — COMMENTED** [review]
Since the build was in progress I got a little anxious about force pushing, this PR needs to be squashed as it currently stands.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16672#-:-MwltZLG5KzIH7IDgTG9:b-bhu1jx)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @svenevs)

___
*[setup/mac/install_prereqs.sh, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16672#-MwlrS8CE5MYb17OVf1x:-MwltSCs3BtByKEFqyWf:b-ohdol) ([raw file](https://github.com/robotlocomotion/drake/blob/d7b112550d168c9c8b18d31bfdc0ba832c4b68e8/setup/mac/install_prereqs.sh#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Consider mentioning that we keep `${var:-}` here to quell mac's old version of bash?

e.g.
```
# N.B. We need `${var:-}` here because mac's older version of bash does
# not seem to be able to cope with an empty array.
```
</blockquote></details>

Done, good call!

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-snopt-packaging please.

My apologies, the job is getting re-run now since the push disabled that from being in the merge checks ... commits are good.

**Comment by jwnimmer-tri** [comment]
We shouldn't need to wait for the super-long CI for this, we can just run the script locally to confirm it doesn't bomb out.  I can do that on my mac, if it helps.

**Comment by svenevs** [comment]
@jwnimmer-tri if you can that would be very helpful, we are currently experiencing unrelated connectivity issues to the mac we can test this on...

**Comment by jwnimmer-tri** [comment]
LGTM:

```console
macsim:drake jwnimmer$ git log -1
commit b621758df29b20664ce566b7a9889d0a213fe257 (HEAD -> master, upstream/master)
Merge: 85fc5467b6 e5e6eafc69
Author: Jeremy Nimmer <jeremy.nimmer@tri.global>
Date:   Fri Feb 25 09:05:42 2022 -0800

    Merge pull request #16625 from alesgenova/eigenptr-type-caster
    
    Implement a pybind11 type_caster for drake::EigenPtr

macsim:drake jwnimmer$ ./setup/mac/install_prereqs.sh 
+ binary_distribution_args=()
+ source_distribution_args=()
+ '[' '' '!=' '' ']'
./setup/mac/install_prereqs.sh: line 40: binary_distribution_args[@]: unbound variable

macsim:drake jwnimmer$ git fetch upstream pull/16672/head && git checkout FETCH_HEAD
...
HEAD is now at bc20ac1913 Partial revert "[setup] Replace `"${var[@]:-}"` with `"${var[@]}"` (#16666)"

macsim:drake jwnimmer$ ./setup/mac/install_prereqs.sh 
+ binary_distribution_args=()
+ source_distribution_args=()
+ '[' '' '!=' '' ']'
+ source ./setup/mac/binary_distribution/install_prereqs.sh ''
++ set -euxo pipefail
++ with_update=1
++ '[' '' '!=' '' ']'
++ [[ 504 -eq 0 ]]
++ command -v conda
++ command -v brew
++ [[ -z '' ]]
++ export HOMEBREW_NO_AUTO_UPDATE=1
++ HOMEBREW_NO_AUTO_UPDATE=1
++ export HOMEBREW_NO_INSTALL_CLEANUP=1
++ HOMEBREW_NO_INSTALL_CLEANUP=1
++ binary_distribution_called_update=0
++ [[ 1 -eq 1 ]]
++ brew update
...
```

**Review by svenevs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16672#-:-MwmFSwX9F5vJSrqxTQP:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
