### PR TITLE
pydrake doc: Add mention about binding dependencies on public API

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Part of this is specific to pydrake bindings, but can still be helpful
for pybind11 in general.

Motivation: @dmcconachie-tri is doing some bindings in Anzu; I mentioned this, and found it'd prolly be good to document this. Not immediately necessary for his purpose, but will most likely come up.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@dmcconachie-tri for feature review, please!

To preview:
```
# Terminal 1
cd drake
bazel run //doc/doxygen_cxx:build -- --serve --quick drake.bindings
# Terminal 2
firefox http://127.0.0.1:8000/doxygen_cxx/group__python__bindings.html#PydrakeModuleDefinitions
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100#-:-Mak3buA7Yl3C56sc6kz:b-v823na)* status: LGTM missing from assignee dmcconachie-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @dmcconachie-tri)

**Review by dmcconachie-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100#-:-MbCiAlq8_zRy49pap0x:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks!

+@sammy-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100#-:-MbCiTQ30Qh7tQtbfLzE:blktcs4)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[bindings/pydrake/pydrake_doxygen.h, line 229 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15100#-MbCiYI-CZvq7mh2lVyU:-MbCiYI-CZvq7mh2lVyV:bu1nhnl) ([raw file](https://github.com/robotlocomotion/drake/blob/660682050aabac90e4c2d99832529e0e692009d5/bindings/pydrake/pydrake_doxygen.h#L229)):*
> ```objc
>         # bindings/.../my_method_py.cc
>         PYBIND_MODULE(my_method, m) {
>           py::module::import("pydrake.s");
> ```

Working: Er, this should've had some actual text. Will fix.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @dmcconachie-tri and @sammy-tri)

___
*[bindings/pydrake/pydrake_doxygen.h, line 229 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15100#-MbCiYI-CZvq7mh2lVyU:-MbCipE622q4OFcS2QwQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/660682050aabac90e4c2d99832529e0e692009d5/bindings/pydrake/pydrake_doxygen.h#L229)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Er, this should've had some actual text. Will fix.
</blockquote></details>

Done.

**Review by dmcconachie-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15100#-:-MbDWYT4EF84b2PfrXOt:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),dmcconachie-tri (waiting on @EricCousineau-TRI)

**Pull request merged**
