### PR TITLE
Add pypi_archive macro to workspace

### PR DESCRIPTION
**Pull request by jamiesnape**
FYI @mwoehlke-kitware.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6017)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/pypi.bzl, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEd82uGh1cpDwUrkfG:-KjEd82uGh1cpDwUrkfH:b-nausg) ([raw file](https://github.com/robotlocomotion/drake/blob/d29db06248b284f03d2e0d2ab7a938102bda6431/tools/pypi.bzl#L15)):*
> ```Python
>     Downloads and unpacks a PyPI package archive and adds it to the WORKSPACE
>     as an external. Additional keyword arguments (except "urls" and
>     "strip_prefix") will be passed through to the native call of
> ```

Please support `strip_prefix`:

```
if strip_prefix == None:
  strip_prefix = "{0}-{1}/{2}".format(package, version, strip_prefix)
else:
  strip_prefix = "{0}-{1}".format(package, version)
```

BTW, why `"{0}{1}".format(a,b)` instead of `"%s%s" % (a,b)`?

---

*[tools/pypi.bzl, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEcqq3TrzwLT2GaO39:-KjEcqq4IQyEpeGFsOuJ:bn439kx) ([raw file](https://github.com/robotlocomotion/drake/blob/d29db06248b284f03d2e0d2ab7a938102bda6431/tools/pypi.bzl#L77)):*
> ```Python
> 
>     urls = [
>         "https://files.pythonhosted.org/source/s/{0}/{0}-{1}.tar.gz".format(
> ```

I wonder if this should use https://pypi.io/packages/source/a/aaaa/aaaa-v.tar.gz instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/pypi.bzl, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEin30iZ8A0KdBJA7C:-KjEin31ar1ZtcGDF3AG:b-f5rnk1) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L78)):*
> ```Python
>         sha256 = "0" * 64
> 
>     if strip_prefix:
> ```

TY! :tada:

---

*[tools/pypi.bzl, line 86 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEjGaAxfclohRMh52E:-KjEjGaB71m8G6kqa5YM:bex0uaj) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L86)):*
> ```Python
>     urls = [
>         "https://files.pythonhosted.org/source/{0}/{1}/{1}-{2}.tar.gz".format(
>             package[:1], package, version),
> ```

Ack... I was wondering about that, but I also didn't spot the problem at first viewing... and of course, it would work just fine until someone adds a PyPI package that doesn't start with "s" :innocent:. (#6014 still wouldn't have noticed... "semantic_version" is still "s"!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by mwoehlke-kitware** [comment]
:lgtm: but presumably should get @jwnimmer-tri's approval yet also...

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-:-KjEkGkKW6XOWyfmVThA:b-pg3mxe)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by stonier** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/pypi.bzl, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEd82uGh1cpDwUrkfG:-KjF9phYhIgekBTjMUsU:b-hqf3s0) ([raw file](https://github.com/robotlocomotion/drake/blob/d29db06248b284f03d2e0d2ab7a938102bda6431/tools/pypi.bzl#L15)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Please support `strip_prefix`:

```
if strip_prefix == None:
  strip_prefix = "{0}-{1}/{2}".format(package, version, strip_prefix)
else:
  strip_prefix = "{0}-{1}".format(package, version)
```

BTW, why `"{0}{1}".format(a,b)` instead of `"%s%s" % (a,b)`?
</blockquote></details>

New vs old style python string formatting ([comparison](https://pyformat.info/)). The older one will eventually deprecate, but isn't marked yet.

---

*[tools/pypi.bzl, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFAbiQhC6m5Zwd95EE:-KjFAbiQhC6m5Zwd95EF:b-ene7qw) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L31)):*
> ```Python
>                 name = "foo",
>                 srcs = ["foo.py"],
>             )
> ```

Seeing as it's pypi, it would be more useful to show here how to expose it as a package with it's `__init__.py` as that is the 99% use case. i.e. does `srcs = glob(["foo/*.py"])` do the trick? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/pypi.bzl, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFm3UXuMohc34Kf75i:-KjFm3UY7zdmHY13ZFde:b-k0dpe7) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L24)):*
> ```Python
>                 version = "1.2.3",
>                 build_file = "foo.BUILD",
>                 sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
> ```

FYI Maybe listing out a samplefull  sha256 isn't useful (and its long)?  Just `sha256 = "0123...",` might suit?

---

*[tools/pypi.bzl, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFAbiQhC6m5Zwd95EE:-KjFnKJbEZvz3FwBJsEt:b-2ivj2f) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L31)):*
<details><summary><i>Previously, stonier (Daniel Stonier) wrote…</i></summary><blockquote>

Seeing as it's pypi, it would be more useful to show here how to expose it as a package with it's `__init__.py` as that is the 99% use case. i.e. does `srcs = glob(["foo/*.py"])` do the trick? 
</blockquote></details>

OK That's fine, but this PR has at least one example, and future PRs can do better.  The `foo.BUILD` files for pypi archives in our `WORKSPACE` will also serve as examples to cargo cult from.  I'm not sure this should be a blocking defect for this PR.  When someone needs more, they can figure it out and then document it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-:-KjFnbN3nTyImYdAu-b1:bnfp4nl)*

**Comment by stonier** [comment]
*[tools/pypi.bzl, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFAbiQhC6m5Zwd95EE:-KjGJ8Ampj60Uxj0b2sX:b-ynwd43) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK That's fine, but this PR has at least one example, and future PRs can do better.  The `foo.BUILD` files for pypi archives in our `WORKSPACE` will also serve as examples to cargo cult from.  I'm not sure this should be a blocking defect for this PR.  When someone needs more, they can figure it out and then document it.
</blockquote></details>

This PR doesn't actually have an example of this. It is trivially exposing just a module, not a package. It was the first thing that leapt to mind when seeing this (one of those too simple examples to be practically useful) and @mwoehlke-kitware is already trying to expose a full package with semantic_version over in #6014,. However, that is using an additional `drake_generate_file` which is either superfluous or necessary for some odd reason. Hence the question/request here. 

Anyway, not important enough to be a blocker if you don't wish it to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/pypi.bzl, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEd82uGh1cpDwUrkfG:-KjIaVxJrdK65317q9Bn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d29db06248b284f03d2e0d2ab7a938102bda6431/tools/pypi.bzl#L15)):*
<details><summary><i>Previously, stonier (Daniel Stonier) wrote…</i></summary><blockquote>

New vs old style python string formatting ([comparison](https://pyformat.info/)). The older one will eventually deprecate, but isn't marked yet.
</blockquote></details>

Done.

---

*[tools/pypi.bzl, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjEcqq3TrzwLT2GaO39:-KjEeu5EEm9K5Y78O2sO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d29db06248b284f03d2e0d2ab7a938102bda6431/tools/pypi.bzl#L77)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I wonder if this should use https://pypi.io/packages/source/a/aaaa/aaaa-v.tar.gz instead?
</blockquote></details>

Done.

---

*[tools/pypi.bzl, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFm3UXuMohc34Kf75i:-KjIaWtw4sd-tD6EU8Tc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Maybe listing out a samplefull  sha256 isn't useful (and its long)?  Just `sha256 = "0123...",` might suit?
</blockquote></details>

Done.

---

*[tools/pypi.bzl, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFAbiQhC6m5Zwd95EE:-KjIaYw1Pvbkx_Mnboj7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L31)):*
<details><summary><i>Previously, stonier (Daniel Stonier) wrote…</i></summary><blockquote>

This PR doesn't actually have an example of this. It is trivially exposing just a module, not a package. It was the first thing that leapt to mind when seeing this (one of those too simple examples to be practically useful) and @mwoehlke-kitware is already trying to expose a full package with semantic_version over in #6014,. However, that is using an additional `drake_generate_file` which is either superfluous or necessary for some odd reason. Hence the question/request here. 

Anyway, not important enough to be a blocker if you don't wish it to be.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[tools/pypi.bzl, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6017#-KjFAbiQhC6m5Zwd95EE:-KjInyrYNrfdZ1QJCraF:b4cij2a) ([raw file](https://github.com/robotlocomotion/drake/blob/f37b9845aaff074e28e5f8125284aba8cb4abbe1/tools/pypi.bzl#L31)):*
> @mwoehlke-kitware is already trying to expose a full package with semantic_version over in #6014,. However, that is using an additional `drake_generate_file` which is either superfluous or necessary for some odd reason.

AFAICT, six was just missing the `strip_prefix` for the root package. semantic_version is a somewhat stranger case in that the actual python code is in a subdirectory of the repository root. Naïvely adding the sources results in a final hierarchy like:

```
path/to/external/semantic_version/
  __init__.py # generated by Bazel; empty
  semantic_version/
    ...actual Python code...
```

...so that `import semantic_version` results in an empty module, because the actual code is "in" `semantic_version.semantic_version.*` rather than `semantic_version.*`, and the empty `__init__.py` seems to "hide" it so that I was having trouble accessing it *at all*. Generating an `__init__.py` with `from semantic_version import *` "hoists" everything in the subdirectory up into the top level where it's supposed to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6017)*

**Comment by jamiesnape** [comment]
https://bazel.build/versions/master/docs/be/python.html#py_library.imports does not work for that?

**Comment by mwoehlke-kitware** [comment]
No, or at least, not based on my best guess from the lousy documentation what it wants for that attribute. In fact, I can't tell where that attribute even does anything.

**Comment by jamiesnape** [comment]
Looking at the `semantic_version` tarball, all you should need is `imports = ["."],` on the `py_library` and no extra `strip_prefix` on the workspace rule.

**Comment by mwoehlke-kitware** [comment]
> Looking at the `semantic_version tarball`, all you should need is `imports = ["."]`, on the `py_library` and no extra `strip_prefix` on the workspace rule.

Nope... and I don't know why you'd even expect that to work...

**Pull request merged**
