### PR TITLE
New internal function SpatialInertia::MakeTestCube() for creating spatial inertia.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17219)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1  
Please ignore message in the commit history as it is spurious (I branched from a larger branch to make this PR smaller).

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17219#-:-N2Jo_9F7kK9sTNxXJed:b-q585th)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with minor comments
+@xuchenhan-tri for platform review per rotation, please

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17219#-:-N2OQ2Pe4KTQHji71h7z:ba9vxp0)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @xuchenhan-tri)

___
*[`multibody/tree/test/spatial_inertia_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OOEppBwjt8HZG4MVw:-N2OOEppBwjt8HZG4MVx:b-jtc2rf) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/test/spatial_inertia_test.cc#L83)):*
> ```cpp
>   const Vector3<double> M1_unit_products = M1.get_unit_inertia().get_products();
>   const double I1 = length_2 * length_2 / 6.0;      // Expected Ixx unit moment.
>   const double J1 = I1 + (length_2 / 2)* (length_2 / 2);   // Expected Iyy, Izz.
> ```

nit: unbalanced spacing around `*`
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OPD9S2v8ymayVztWO:-N2OPD9S2v8ymayVztWP:b-jtc2rf) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/test/spatial_inertia_test.cc#L99)):*
> ```cpp
>   const Vector3<double> M2_unit_products = M2.get_unit_inertia().get_products();
>   const double I2 = default_length * default_length / 6.0;
>   const double J2 = I2 + (default_length / 2)* (default_length / 2);
> ```

nit: unbalanced spacing around `*`
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OPhSqAr1QtMDtySBp:-N2OPhSqAr1QtMDtySBq:b-hnlgkj) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/test/spatial_inertia_test.cc#L106)):*
> ```cpp
>   // Ensure an exception is thrown if a mass or length is negative.
>   EXPECT_THROW(SpatialInertia<double>::MakeTestCube(
>       -mass_1, length_2), std::exception);
> ```

minor: should check that the "negative mass" message was issured rather than the "negative length" message

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17219)* status: 5 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @xuchenhan-tri)

___
*[`multibody/tree/spatial_inertia.h` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OR4HT4NWaqypvAYoH:-N2OR4HT4NWaqypvAYoI:b-7sps93) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/spatial_inertia.h#L135)):*
> ```objc
>   /// @note The default parameters mass = 2 and length = 3 correspond to a mass
>   /// moment of inertia of 3 for any line that pass through Bcm.
>   static SpatialInertia MakeTestCube(T mass = T(2), T length = T(3)) {
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

It seems unlikely that unit-test-only code is performance-sensitive.
___
*[`multibody/tree/unit_inertia.h` line 266 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OQzy22JoVFp510rQS:-N2OQzy37ZPBkJ7vZjXE:b-g97jyp) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/unit_inertia.h#L266)):*
> ```objc
>       const std::string msg = "A length argument to UnitInertia::SolidBox() "
>                               "is negative.";
>       throw std::logic_error(msg);
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

Throwing is too big for inline.

**Review by xuchenhan-tri — COMMENTED** [review]
Linter is upsetting CI.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17219#-:-N2ThkSF5EY1hj9dsHKn:b-b257m6)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/test/spatial_inertia_test.cc` line 107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2ThQmH5g2AcYoE9rDG:-N2ThQmH5g2AcYoE9rDH:blrsizy) ([raw file](https://github.com/robotlocomotion/drake/blob/c7dfbfdb91fb54d0e2c4d10c71b938823d91ba6e/multibody/tree/test/spatial_inertia_test.cc#L107)):*
> ```cpp
>    const std::string expected_mass_msg =
>       "Spatial inertia fails SpatialInertia::IsPhysicallyValid\\(\\).\n"
>       "mass = -1(\\.0)? is negative.\n";
> ```

FYI you could just do `"Spatial inertia fails SpatialInertia::IsPhysicallyValid.*mass.*is negative"` which is clearer IMO

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17219#-:-N2U4FWR9wwnaP-Mbmkw:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/tree/spatial_inertia.h` line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OR4HT4NWaqypvAYoH:-N2T5T54DLrFBUGegxGE:bmyux0g) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/spatial_inertia.h#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

It seems unlikely that unit-test-only code is performance-sensitive.
</blockquote></details>

Done.  Moved to spatial_inertia.cc
___
*[`multibody/tree/unit_inertia.h` line 266 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OQzy22JoVFp510rQS:-N2T5wx82Clmrbl97HMW:b-tkut5u) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/unit_inertia.h#L266)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

Throwing is too big for inline.
</blockquote></details>

Done.  Moved to unit_inertia.cc
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OOEppBwjt8HZG4MVw:-N2T6I8p29CwB6bK1cw-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/test/spatial_inertia_test.cc#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: unbalanced spacing around `*`
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OPD9S2v8ymayVztWO:-N2T6J1e2d_OO9clWZ6Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/test/spatial_inertia_test.cc#L99)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: unbalanced spacing around `*`
</blockquote></details>

Done.
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17219#-N2OPhSqAr1QtMDtySBp:-N2TXdal59wpfy8lpzzd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8ef8c7a54fa2f3def5a8b4cefddf455d8d24fb7a/multibody/tree/test/spatial_inertia_test.cc#L106)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should check that the "negative mass" message was issured rather than the "negative length" message
</blockquote></details>

Done.

**Pull request merged**
