### PR TITLE
pick-and-place demo readme

### PR DESCRIPTION
**Pull request by naveenoid**
Describes the command line options.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5958)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@SeanCurtis-TRI for feature review since you need to tell me if this rudimentary readme is sufficient for you.

**Comment by naveenoid** [comment]
@seancurtis-tri - friendly ping : this is a super simple PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-:-Kiq07QCr51pZiDBM9GU:bhvnglu)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With a fleeting BTW

Sorry for the delay; somehow this slipped past my attention despite my email filters.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-Kiq6-kp2hsSMs5WMI5b:-Kiq6-kp2hsSMs5WMI5c:b-v0f8a) ([raw file](https://github.com/robotlocomotion/drake/blob/a3f6dee6720c3fa8225826f5316308c2987b5c9a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L10)):*
> ```Markdown
> 
> Command line arguments can be passed for : ```box_choice``` an integer between 1 and 3 (corresponding to small, medium and large boxes as manipulation targets),
> and for ```orientation``` - a decimal value for the yaw orientation on the table in radians.
> ```

BTW just a few nits:

1. You probably want to  still adhere to the 80-column restrictions.
2. Missing new line.
3. I don't think you need triple backticks. I believe a single backtick is enough for inline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-:-Kiq5iw24osDsouP383r:b-xxojro)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958)*

**Comment by naveenoid** [comment]
+@sherm1 for - Le Review du Platform

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-:-Kiq9v7iuADr7LyS3Wnc:bphfm47)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-Kiq6-kp2hsSMs5WMI5b:-KiqR3_4C2k-k7N2iTPF:bojxm1j) ([raw file](https://github.com/robotlocomotion/drake/blob/a3f6dee6720c3fa8225826f5316308c2987b5c9a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L10)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW Except for the 80-column thing, apparently.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958)*

**Comment by sherm1** [comment]
Platform :lgtm:, one BTW.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-KirUFs5HQRCdpFozU8Z:-KirUFs5HQRCdpFozU8_:bgsqgoj) ([raw file](https://github.com/robotlocomotion/drake/blob/ebd6979683d23ce3f6a7fd2d1449398db164958c/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L11)):*
> ```Markdown
> 
> Command line arguments can be passed for : `box_choice` an integer between 1 and 3 (corresponding to small, medium and
> large boxes as manipulation targets),and for `orientation` - a decimal value for the yaw orientation on the table in
> ```

BTW please consider keeping lines to 80 characters here when possible. (Not a defect, just good hygiene.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-:-KirUTV6Fzx5TopKExcg:bmsxcp7)*

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-Kiq6-kp2hsSMs5WMI5b:-Kj35dhv7-5R7Z1zp4WQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a3f6dee6720c3fa8225826f5316308c2987b5c9a/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Except for the 80-column thing, apparently.  :)
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5958#-KirUFs5HQRCdpFozU8Z:-Kj35dvRWEJMZiwZKoE5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ebd6979683d23ce3f6a7fd2d1449398db164958c/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please consider keeping lines to 80 characters here when possible. (Not a defect, just good hygiene.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5958)*

**Pull request merged**
