### PR TITLE
[math] Remove unnecessary textual_hdrs line

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Huh.  This passed for me locally in a few build configs, and in Anzu CI, and seems like all of the other CIs here will be happy.  I guess we don't need the line?

@rpoyner-tri @SeanCurtis-TRI feel free to stamp and merge, once CI is happy.

**Review by rpoyner-tri — COMMENTED** [review]
I suspect it got cargo-culted somehow from `highway`'s own BUILD file, which I think really does need it. I don't think end-user cc files need it. 

+@rpoyner-tri :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-:-O2WakWc-2xszBhTpO_1:bml8lme)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-O2Wb4mZ700Odx9rzPCe:-O2Wb4mZ700Odx9rzPCf:b-fqkgdn) (no related file):*
minor I think the one in common/BUILD.bazel can go as well.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739)* status: 1 unresolved discussion

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-:-O2WeMKyDkjPSrEn9-aS:bmxilld)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-O2WeFzx9O6eBX0yhss8:-O2WeFzx9O6eBX0yhss9:b730pur) (no related file):*
Do we want to undo the changes in drake_cc.bzl from #21626 for textural_hdrs as well?

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-:-O2WeNo06FAmbQ0aWQtA:b-a74z6d)* status: 2 unresolved discussions

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-O2WeFzx9O6eBX0yhss8:-O2WevCA424Av-7EuzZw:b-1z27eg) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Do we want to undo the changes in drake_cc.bzl from #21626 for textural_hdrs as well?
</blockquote></details>

my .02: I think passing through the flag is ok, even if we don't currently need to use it. But, I could be swayed.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-O2WeFzx9O6eBX0yhss8:-O2WfKCq2DAjINDDOFjR:bkmlb7t) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

my .02: I think passing through the flag is ok, even if we don't currently need to use it. But, I could be swayed.
</blockquote></details>

I know what you mean. Its presence isn't *wrong*, per se. But its presence, specifically in `drake_cc.bzl` implies necessity. Otherwise, why would it be there? In centuries, cultural anthropologists will be debating the evolutionary advantage of `textural_hdrs`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @SeanCurtis-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21739)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21739#-O2WeFzx9O6eBX0yhss8:-O2XLmFI4aYbTu1hQGoS:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I know what you mean. Its presence isn't *wrong*, per se. But its presence, specifically in `drake_cc.bzl` implies necessity. Otherwise, why would it be there? In centuries, cultural anthropologists will be debating the evolutionary advantage of `textural_hdrs`.
</blockquote></details>

Done.

___

**Pull request merged**
