### PR TITLE
Add utility code to automotive/maliput.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4694)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@rpoyner-tri for feature review, please.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_oR1Db0IN6BYxIdcus:blnrywe)*

**Comment by maddog-tri** [comment]
+@sammy-tri for platform review, please.  

I'm going to try to do something new on this PR, to avoid "infinite thread death spiral":  I'm not going to look at any of this again until someone says either "ok, I have finished my review" or "I have a blocking issue that prevents me from reviewing the rest of the PR until I get a response from you".

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_oSE3VyJx8tKcOhCbO:b-r40d2o)*

**Comment by maddog-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-coverage please

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_oTlV4DmHFukgtqxxa:b-ilveoz)*

**Comment by maddog-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-coverage please

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_olXTR0hh_MRkETrAL:b-8l57oz)*

**Comment by sammy-tri** [comment]
checkpoint

---

Reviewed 14 of 17 files at r1.
Review status: 14 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 560 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p6j4qYdgqrgjac620:-K_p6j4qYdgqrgjac621:bncaurw) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/generate_obj.cc#L560)):*
> ```cpp
>     for (int si = 0; si < junction->num_segments(); ++si) {
>       const api::Segment* segment = junction->segment(si);
>       // Lane 0 should be as good as any other for driveable-bounds.
> ```

BTW I don't understand this comment, but that might be OK due to a lack of domain knowledge.

---

*[drake/automotive/maliput/utility/generate_obj.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p37YzcqoZn1iYc4Ym:-K_p37Z-DQALHTH4a-Mo:b-ojoby7) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/generate_obj.h#L26)):*
> ```objc
>   /// Draw highlighting swath with lane_bounds() of each lane?
>   bool draw_lane_haze{true};
>   /// Absolute width of stripes
> ```

What units are the absolute quantities in?

---

*[drake/automotive/maliput/utility/test/generate_urdf_test.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p7Iulwd27BNxIgMZY:-K_p7Iulwd27BNxIgMZZ:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/generate_urdf_test.cc#L13)):*
> ```cpp
> 
> #include <cmath>
> #include <iostream>
> ```

unused?

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p82GwPaxRvQR-_JcO:-K_p82GxHuocj77FufMy:b4jk7ln) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L27)):*
> ```Python
> 
>         yaml_files = glob.glob(os.path.join(yaml_dir, '*.yaml'))
>         blacklist = []
> ```

I'm guessing something is planned to be blacklisted in the future?  Maybe it's worth a comment to explain why there's code here which doesn't accomplish anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_p8Mey-aiHwiWi846l:b-vv2shf)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 17 files at r1.
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by maddog-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-coverage please

---

Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_pJSHPn-VjnFiP6uwJ:b-8l57oz)*

**Comment by sammy-tri** [comment]
:lgtm: pending feature review (I was a little out of my element on this one in terms of feature functionality)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-K_pRekOASX3rWTiw5WL:b-9yopnw)*

**Comment by rpoyner-tri** [comment]
Reviewed 15 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-K_psrydAuShNuGQrtOb:b-fz2h8g) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
> ```cpp
>      << "    </visual>\n"
>      << "  </link>\n"
>      << "</robot>\n";
> ```

BTW, consider using a C++ raw string literal to write this in a more text-template style, with less backslash noise.

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p82GwPaxRvQR-_JcO:-K_pfbIprlNOjhd6Ywso:b-gh26s3) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L27)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm guessing something is planned to be blacklisted in the future?  Maybe it's worth a comment to explain why there's code here which doesn't accomplish anything.
</blockquote></details>

IIRC, the blacklist was born non-empty because of bugs or incomplete implementations .w.r.t. data files that were already checked in. Now that it is empty, it could probably go away.

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_pgZiBNQIGWdE7yUgC:-K_pgZiBNQIGWdE7yUgD:bjl9hla) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L17)):*
> ```Python
> _THIS_DIR = os.path.dirname(_THIS_FILE)
> 
> class TestYamlObjing(unittest.TestCase):
> ```

TestYamlObjing is a funny name. Is that on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by maddog-tri** [comment]
Review status: 14 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 560 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p6j4qYdgqrgjac620:-K_xFk_76pap9H9qXHtl:b-luo7j3) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/generate_obj.cc#L560)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I don't understand this comment, but that might be OK due to a lack of domain knowledge.
</blockquote></details>

("Driveable bounds" is supposed to be the extent of the pavement for the entire segment.  Each lane has its own reference line, and thus its own expression of driveable-bounds relative to that line --- but they should all cover the same amount of surface.)

---

*[drake/automotive/maliput/utility/generate_obj.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p37YzcqoZn1iYc4Ym:-K_xHNMtpPwY3C75SMog:b-hr3jz2) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/generate_obj.h#L26)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

What units are the absolute quantities in?
</blockquote></details>

I've been working under the "distances are meters unless otherwise noted" rule (same for time=seconds, angles=radians).

---

*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-K_zSxsOBruU230eGJfU:b-r5jhvc) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, consider using a C++ raw string literal to write this in a more text-template style, with less backslash noise.
</blockquote></details>

Hmm... tried it out... by itself, it was a wash --- but then I realized I could use the `fmt` formatting library (already available through the `spdlog` logging lib) to do concise variable substitutions without having to break into/out-of raw-string mode.  I've done the same trick in GenerateObj() --- see how it looks.
Number one remaining problem is that my emacs is confused by all the double-quotes and does not fontify it correctly.

---

*[drake/automotive/maliput/utility/test/generate_urdf_test.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p7Iulwd27BNxIgMZY:-K_xIFBMvFuZF0vDKrEi:b-jfl15j) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/generate_urdf_test.cc#L13)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.  (Indeed, it was.)

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p82GwPaxRvQR-_JcO:-K_xJ1cXQPvyed688UWz:b-ka181j) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

IIRC, the blacklist was born non-empty because of bugs or incomplete implementations .w.r.t. data files that were already checked in. Now that it is empty, it could probably go away.
</blockquote></details>

Yes, there were blacklisted files at some point, but when they went away I kept the code around lest they return.  That was the rationale at the time, at least.

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_pgZiBNQIGWdE7yUgC:-K_xIY8gJvb435G-1x-T:b-yvie2x) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

TestYamlObjing is a funny name. Is that on purpose?
</blockquote></details>

`load_yaml` gets `TestYamlLoading`, and `yaml_to_obj` gets `TestYamlObjing`.  ('cause anything can be verbed in English.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by maddog-tri** [comment]
Review status: 14 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-K_zzx0G3pcEQsMVblje:b-wlx4st) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Hmm... tried it out... by itself, it was a wash --- but then I realized I could use the `fmt` formatting library (already available through the `spdlog` logging lib) to do concise variable substitutions without having to break into/out-of raw-string mode.  I've done the same trick in GenerateObj() --- see how it looks.
Number one remaining problem is that my emacs is confused by all the double-quotes and does not fontify it correctly.
</blockquote></details>

(Man, reviewable's diff algorithm could use a little work on the "consolidate blocks" aspect....)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-Ka-1ZJ481zFZHVA22jC:b6yie8r) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

(Man, reviewable's diff algorithm could use a little work on the "consolidate blocks" aspect....)
</blockquote></details>

Yikes!  In `driving`, I have `spdlog` disabled, because we don't want to use it as a logger when there already is one.  If we really love `fmt` then I can swap things around so that we have it, but if its only a minor improvement then possibly its not worth the bother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by liangfok** [comment]
Reviewed 6 of 17 files at r1, 1 of 3 files at r3.
Review status: 15 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-26rFRJ5V1ipEnTvr:-Ka-26rFRJ5V1ipEnTvs:bnt0ul1) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L20)):*
> ```cpp
> #include "drake/common/drake_assert.h"
> 
> #include "spdlog/fmt/ostr.h"
> ```

BTW, this should be moved above Drake's header files per style guide.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-2IypUzTIfrWaOMAp:-Ka-2IypUzTIfrWaOMAq:b-ahzhzh) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L28)):*
> ```cpp
> namespace {
> 
> // A container for a set of unique objects of which keeps track of the original
> ```

BTW, "of which" sounds odd. Consider "that".

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-2VfhWY_Pp4geu0AM:-Ka-2VfhWY_Pp4geu0AN:bnmioy0) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L42)):*
> ```cpp
>   UniqueIndexer() {}
> 
>   // Pushes @p thing onto the back of the container, and returns the unique
> ```

BTW, should "the container" be "this container"?

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 201 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-CTCwjya96Cv7oHIE:-Ka-CTCwjya96Cv7oHIF:bfxaibj) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L201)):*
> ```cpp
>   }
> 
>   // Emits the mesh as a Wavefront OBJ elements to @p os.  @p material is the
> ```

BTW, the "a" and "elements" appear to conflict (singular vs. plural).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by maddog-tri** [comment]
Review status: 15 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-Ka-iENsY8P356QifwWq:b-e7yzip) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
>   In driving, I have spdlog disabled,

How does that work?  Oh, is that what the no-op stubs are for in `common/text_logging.h` are for?  Do you actually somehow provide op's for them, or is drake logging just completely no-op'ed in `driving` compiles?  (If you do provide op's... how do you parse the `fmt` format strings?)

`fmt` seems like it would actually be nice to have.  It claims to be superior to `boost::format` in runtime, compile-time, and code-size... and it's not `boost`.  And, the API is a lot friendlier than `the << usual << ostream << business`.

Anyhow.... I can back out this change altogether, or I can do some kind of "formally introduce `fmt` to drake" PR first, or I can do such a PR after squash/merging this, or...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-Ka2Trzz8TfG-5i1Kh8M:b-qav1ct) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

>   In driving, I have spdlog disabled,

How does that work?  Oh, is that what the no-op stubs are for in `common/text_logging.h` are for?  Do you actually somehow provide op's for them, or is drake logging just completely no-op'ed in `driving` compiles?  (If you do provide op's... how do you parse the `fmt` format strings?)

`fmt` seems like it would actually be nice to have.  It claims to be superior to `boost::format` in runtime, compile-time, and code-size... and it's not `boost`.  And, the API is a lot friendlier than `the << usual << ostream << business`.

Anyhow.... I can back out this change altogether, or I can do some kind of "formally introduce `fmt` to drake" PR first, or I can do such a PR after squash/merging this, or...
</blockquote></details>

Yes, those stubs.  No, text logging from Drake in `driving` is completely muted.

Alright, go ahead and use `fmt` here, I'll make sure it works later when we need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p82GwPaxRvQR-_JcO:-Ka2s4L_BqHJ_2YAmvPp:bq0miwh) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L27)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Yes, there were blacklisted files at some point, but when they went away I kept the code around lest they return.  That was the rationale at the time, at least.
</blockquote></details>

I'm OK with leaving it in, but I still think that if we do so a comment would help future readers understand the presence of does-nothing code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-Ka3av-AWqPjwO-HTtLw:b93awyz) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, those stubs.  No, text logging from Drake in `driving` is completely muted.

Alright, go ahead and use `fmt` here, I'll make sure it works later when we need it.
</blockquote></details>

I like this rev better, sorry about the run-around with fmt. One last BTW: consider popping out the format string to something like "char urdf_stuff[] = R"X(blah!)X" at file scope, and probably wrapped in an unnamed namespace? Who knows, emacs might even like it better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by maddog-tri** [comment]
Review status: 14 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-26rFRJ5V1ipEnTvr:-Ka5KyY28ahDhFltGr5Q:b-gqtfxm) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this should be moved above Drake's header files per style guide.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

Indeed it does.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-2IypUzTIfrWaOMAp:-Ka5LEvwpbgfgDxS5kcl:bozequ0) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "of which" sounds odd. Consider "that".
</blockquote></details>

Yep... errant "of".

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 42 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-2VfhWY_Pp4geu0AM:-Ka5LoYljP1ZslPymdHl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should "the container" be "this container"?
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 201 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-Ka-CTCwjya96Cv7oHIE:-Ka5NlvCmUfuANCq7B-K:bvc75x3) ([raw file](https://github.com/robotlocomotion/drake/blob/50869f0f2e542e2c25d8ec23b427a29e4f37eb35/drake/automotive/maliput/utility/generate_obj.cc#L201)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, the "a" and "elements" appear to conflict (singular vs. plural).
</blockquote></details>

Yah, errant "a" (and, "ascribe" was the wrong verb, too).

---

*[drake/automotive/maliput/utility/generate_urdf.cc, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_psrydAuShNuGQrtOa:-Ka5NsNE0hDjJ31eOJw5:bv2mcke) ([raw file](https://github.com/robotlocomotion/drake/blob/1c5f9006702dc8dbdcda8d0b05f8bb29810732a8/drake/automotive/maliput/utility/generate_urdf.cc#L42)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I like this rev better, sorry about the run-around with fmt. One last BTW: consider popping out the format string to something like "char urdf_stuff[] = R"X(blah!)X" at file scope, and probably wrapped in an unnamed namespace? Who knows, emacs might even like it better.
</blockquote></details>

Ok, good, leaving it as is.  (PS:  emacs doesn't care, and the string is short enough that I would rather keep it inline and closely associated with the parameters getting substituted into it.)

---

*[drake/automotive/maliput/utility/test/yaml_to_obj_test.py, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-K_p82GwPaxRvQR-_JcO:-Ka5Ohp9Pgvj6NGmSE1p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67fa76e46883b33d39d5d87112dd67ba961505f0/drake/automotive/maliput/utility/test/yaml_to_obj_test.py#L27)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm OK with leaving it in, but I still think that if we do so a comment would help future readers understand the presence of does-nothing code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by liangfok** [comment]
Reviewed 1 of 3 files at r4.
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-Ka5TG0VGBRFvEw9CQvp:bnfp4nl)*

**Comment by maddog-tri** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694#-:-Ka5i9zlgiE0dFQv13lE:b-l70wzf)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4694)*

**Comment by david-german-tri** [comment]
Minor, belated gripe: The Bazel docs say that "a successful genrule should be silent"

https://bazel.build/versions/master/docs/be/general.html#genrule

**Pull request merged**
