### PR TITLE
Add comments throughout file.

### PR DESCRIPTION
**Pull request by Lucy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2480)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@sammy-tri (feature reviewer)
+@david-german-tri (platform reviewer)

<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> #### Add comments throughout file\.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ66ENZ0k5kOosmjKwp:-1255196456)*

**Comment by Lucy-tri** [comment]
+@russtedrake would be great to have your review of this documentation, especially since Grant on vacation. 

<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> +@sammy-tri (feature reviewer)
> +@david-german-tri (platform reviewer)
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ6BAXkZ5VajNRyuOqj:1747711488)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6KaBkDuowRhUkJGp3:-KJ6KaBkDuowRhUkJGp4:-2054760152) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L24)):*
> ```objc
>      }
>  *   else return x;
>  * }
> ```

Code won't format correctly in Doxygen unless you surround it with `@code` and `@endcode`. You should build the doxygen documentation and take a look at how it comes out -- there are lots of ways for it to go wrong!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480)*

**Comment by liangfok** [comment]
I left a few minor comments. 

<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> +@russtedrake would be great to have your review of this documentation, especially since Grant on vacation. 
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6cbOmI2B4wehb0fCI:-KJ6cbOnbOT7HMSpkg8y:-873983777) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L27)):*
> ```objc
>  *
>  * PiecewisePolynomials can be added, subtracted, and multiplied.
>  * They cannot be divided.
> ```

BTW, can you expand upon the above sentence by explaining _why_ piecewise polynomials cannot be divided?

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6dLs_V848rQHJc4zU:-KJ6dLs_V848rQHJc4zV:392111209) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L73)):*
> ```objc
>    * function.
>    *
>    * If derivative_order is given, takes the nth derivative of this
> ```

BTW, consider adding `\p` in front of "derivative_order" to denote that it is a parameter.

https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 84 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6doz_E2jTlkrCx1xd:-KJ6doz_E2jTlkrCx1xe:-1846626699) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L84)):*
> ```objc
>    * function.
>    *
>    * If value_at_start_time is given, it does the following only for the first
> ```

BTW, consider adding `\p` in front of "value_at_start_time" to denote that it is a parameter.

https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6dtpxQPjf1cCclSAt:-KJ6dtpxQPjf1cCclSAu:-1846626699) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L96)):*
> ```objc
>    * function.
>    *
>    * If value_at_start_time is given, it does the following only for the first
> ```

BTW, consider adding `\p` in front of "value_at_start_time" to denote that it is a parameter.

https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 142 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6dz5FVIg1t8orw3Cp:-KJ6dz5FVIg1t8orw3Cq:-22937730) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L142)):*
> ```objc
>   /// Checks if a PiecewisePolynomial is approximately equal to this one.
>   /**
>    * Checks that every coefficient of other is within tol of the
> ```

BTW, consider adding `\p` in front of "tol" to denote that it is a parameter.

https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 159 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6e8aowfA1dXPtFk7M:-KJ6e8aowfA1dXPtFk7N:-1958273827) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L159)):*
> ```objc
>   /// Obtains a random PiecewisePolynomial of the specified size.
>   /**
>    * Obtains a PiecewisePolynomial with the given segment times. Each segment
> ```

BTW, should "segment times" be "time segments"?

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 160 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6eFuM8H4kcp2SbARx:-KJ6eFuM8H4kcp2SbARy:-736563720) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L160)):*
> ```objc
>   /**
>    * Obtains a PiecewisePolynomial with the given segment times. Each segment
>    * will have a matrix of random Polynomials of the specified size.
> ```

Does "specified size" equal `num_coefficients_per_polynomial`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ6eVBwWhf2arOv6E5b:662625237)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 24 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6KaBkDuowRhUkJGp3:-KJ7-IkKwweFu9NgfjwJ:255542303) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Code won't format correctly in Doxygen unless you surround it with `@code` and `@endcode`. You should build the doxygen documentation and take a look at how it comes out -- there are lots of ways for it to go wrong!
</details>
Thanks! Done.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6cbOmI2B4wehb0fCI:-KJ7-NWvVmWE6yc5pwlx:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, can you expand upon the above sentence by explaining _why_ piecewise polynomials cannot be divided?
</details>
Done.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 73 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6dLs_V848rQHJc4zU:-KJ7-PikY9otj327urFA:483086068) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider adding `\p` in front of "derivative_order" to denote that it is a parameter.
> 
> https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp
</details>
Good to know: done.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 84 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6doz_E2jTlkrCx1xd:-KJ7-RtcT8xdrLmoijJR:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L84)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider adding `\p` in front of "value_at_start_time" to denote that it is a parameter.
> 
> https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp
</details>
Done.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6dtpxQPjf1cCclSAt:-KJ7-U8hKMU-4Tjnv5YH:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L96)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider adding `\p` in front of "value_at_start_time" to denote that it is a parameter.
> 
> https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp
</details>
Done.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 142 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6dz5FVIg1t8orw3Cp:-KJ7-XC_AaG2GvQ_lru0:1371863758) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L142)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider adding `\p` in front of "tol" to denote that it is a parameter.
> 
> https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdp
</details>
did "other" and "tol" params

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 159 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ6e8aowfA1dXPtFk7M:-KJ7-_wNEYqrfIcl1NjH:-2121020552) ([raw file](https://github.com/robotlocomotion/drake/blob/7265bdb588a7366f24d01c3e6d173ef76a8a5914/drake/systems/trajectories/PiecewisePolynomial.h#L159)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should "segment times" be "time segments"?
</details>
It's actually the times of the segments, and it's a param, so I added /p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480)*

**Comment by liangfok** [comment]
:lgtm: 

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I left a few minor comments. 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ726nS_lfH28SMFzVS:980077423)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480)*

**Comment by david-german-tri** [comment]
FYI, I'm waiting for @sammy-tri's review unless instructed otherwise.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> :lgtm: 
</details>


---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ73or6w55bxErtoJyt:535285840)*

**Comment by sammy-tri** [comment]
:lgtm: (thanks to everyone else who got here before me, I think you took care of any concerns I had (and more))

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> FYI, I'm waiting for @sammy-tri's review unless instructed otherwise.
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ7FoyLTUCtbiuziiWS:-1515804910)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> :lgtm: (thanks to everyone else who got here before me, I think you took care of any concerns I had (and more))
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 147 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ8253uehEK4MQFYia6:-KJ8253uehEK4MQFYia7:-1396999551) ([raw file](https://github.com/robotlocomotion/drake/blob/36bd07241a608b05c1a4fb5e4bf2457984ae5780/drake/systems/trajectories/PiecewisePolynomial.h#L147)):*
> ```objc
>    * Checks that every coefficient of \p other is within \p tol of the
>    * corresponding coefficient of this PiecewisePolynomial.
>    * Any rules or limitations of Polynomial::integral also apply to this
> ```

Is this sentence accidental copy/paste?  If not, consider elaborating.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-:-KJ82EW-HiU40qu_-OJW:1417088721)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 147 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ8253uehEK4MQFYia6:-KJC8VyRr89Kuvyvy1Va:-1112208525) ([raw file](https://github.com/robotlocomotion/drake/blob/c2ae1f527d569bb3cfa5bb1b6f0b50d1dba58f31/drake/systems/trajectories/PiecewisePolynomial.h#L147)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Is this sentence accidental copy/paste?  If not, consider elaborating.
</details>
Good catch: replaced incorrect comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 147 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ8253uehEK4MQFYia6:-KJC924ceYtSgdQTr1xF:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c2ae1f527d569bb3cfa5bb1b6f0b50d1dba58f31/drake/systems/trajectories/PiecewisePolynomial.h#L147)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Good catch: replaced incorrect comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/PiecewisePolynomial.h, line 147 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2480#-KJ8253uehEK4MQFYia6:-KJC985cbbZvV6zWUn6d:676834233) ([raw file](https://github.com/robotlocomotion/drake/blob/c2ae1f527d569bb3cfa5bb1b6f0b50d1dba58f31/drake/systems/trajectories/PiecewisePolynomial.h#L147)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Good catch: replaced incorrect comment.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2480)*

**Pull request merged**
