### PR TITLE
PidControlledSystem takes in user specified plant input port.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@siyuanfeng-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490#-:-MQEwB5y3XacN4hpqDvw:b-nuqiv0)* status: LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490#-:-MQFXFY58wdym0D-xSbo:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490#-:-MQFfxySDeYsyEWSwGz-:buer3go)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one nit.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490#-:-MQFl6Jm1qcOhzsrjBBu:bwp6ahw)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[systems/controllers/pid_controlled_system.h, line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14490#-MQFk8qw-7d8ca7vAm6R:-MQFk8qw-7d8ca7vAm6S:bjlxijg) ([raw file](https://github.com/robotlocomotion/drake/blob/d802a81a83bacce262b69f33dd0612d55793268f/systems/controllers/pid_controlled_system.h#L135)):*
> ```objc
>   /// plant that contains the (full) state information.
>   /// @param[in] plant_input_port_index identifies the plant input port that
>   /// the controller output is fed to.
> ```

nit: should use the same comment as for the previous three constructors unless there is a real difference in meaning here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490)* status: :shipit: complete! all discussions resolved, LGTM from assignees siyuanfeng-tri,sherm1(platform) (waiting on @sherm1 and @siyuanfeng-tri)

___
*[systems/controllers/pid_controlled_system.h, line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14490#-MQFk8qw-7d8ca7vAm6R:-MQFoLpV7lxkvfthfxD7:b-l2tt7p) ([raw file](https://github.com/robotlocomotion/drake/blob/d802a81a83bacce262b69f33dd0612d55793268f/systems/controllers/pid_controlled_system.h#L135)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: should use the same comment as for the previous three constructors unless there is a real difference in meaning here.
</blockquote></details>

Done, good catch.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14490)* status: :shipit: complete! all discussions resolved, LGTM from assignees siyuanfeng-tri,sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
