### PR TITLE
Resolves #4964.

### LINKED ISSUE #4964: errors in running LinearInvertedPendulum.m
Hi, my name is Bryan from University of Waterloo, Canada. I am learning LinearInvertedPendulum.m in directory `drake-distro/drake/examples/ZMP`. But I got some complains when I run like bellow,

When I tried to run `LinearInvertedPendulum.runPassive`, Matlab command showed,

```
>> LinearInvertedPendulum.runPassive
Error using MultiCoordinateFrame/findTransform (line 155)
Could not find any transform between LIMPState+ZMP and CartTablePosition

Error in PPTrajectory/inFrame (line 91)
        tf =
        findTransform(obj.getOutputFrame,frame,struct('throw_error_if_fail',true));
        
Error in PPTrajectory/subsref (line 506)
        [varargout{:}] = builtin('subsref',a,s);

Error in Visualizer/playback (line 85)
        xtraj = xtraj.inFrame(obj.getInputFrame);  % try to convert it

Error in LinearInvertedPendulum.runPassive (line 398)
      v.playback(ytraj);
 
```

When I tried to run ` LinearInvertedPendulum.ZMPtrackingDemo`, Matlab command showed,

```
>> LinearInvertedPendulum.ZMPtrackingDemo
 Calling addpath_spotless
Warning: Block diagram 'MIMOFeedback_2451469' contains 1 algebraic loop(s). To see
more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2451469') </a> or the command line Simulink
debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2451469') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModel (line 25)
  In DynamicalSystem/mimoFeedback (line 215)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 423) 
Found algebraic loop containing:
'MIMOFeedback_2451469/system2/DrakeSys'

'MIMOFeedback_2451469/tf2/DrakeSys'

'MIMOFeedback_2451469/system1/DrakeSys'

'MIMOFeedback_2451469/tf1/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2451469' contains 1 algebraic loop(s). To see
more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2451469') </a> or the command line Simulink
debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2451469') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModelHandle/feval (line 125)
  In SimulinkModel (line 43)
  In DynamicalSystem/mimoFeedback (line 215)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 423) 
Found algebraic loop containing:
'MIMOFeedback_2451469/system2/DrakeSys'

'MIMOFeedback_2451469/tf2/DrakeSys'

'MIMOFeedback_2451469/system1/DrakeSys'

'MIMOFeedback_2451469/tf1/DrakeSys' (algebraic variable)

Warning: NARGCHK will be removed in a future release. Use NARGINCHK or
NARGOUTCHK instead. 
> In catstruct (line 46)
  In DynamicalSystem/mimoFeedback (line 229)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 423) 
Warning: Block diagram 'MIMOFeedback_2451469' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2451469') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2451469') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In getInitialState
  In sl (line 15)
  In Simulink.BlockDiagram/getInitialState
  In getSimulinkStateStructure (line 13)
  In DynamicalSystem/stateVectorToStructure (line 657)
  In DynamicalSystem/simulate (line 39)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 427) 
Found algebraic loop containing:
'MIMOFeedback_2451469/system2/DrakeSys'

'MIMOFeedback_2451469/tf2/DrakeSys'

'MIMOFeedback_2451469/system1/DrakeSys'

'MIMOFeedback_2451469/tf1/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2451469' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2451469') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2451469') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModel/getSampleTime (line 64)
  In DynamicalSystem/isCT (line 394)
  In DynamicalSystem/simulate (line 75)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 427) 
Found algebraic loop containing:
'MIMOFeedback_2451469/system2/DrakeSys'

'MIMOFeedback_2451469/tf2/DrakeSys'

'MIMOFeedback_2451469/system1/DrakeSys'

'MIMOFeedback_2451469/tf1/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2451469' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2451469') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2451469') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModel/getSampleTime (line 64)
  In DynamicalSystem/simulate (line 104)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 427) 
Found algebraic loop containing:
'MIMOFeedback_2451469/system2/DrakeSys'

'MIMOFeedback_2451469/tf2/DrakeSys'

'MIMOFeedback_2451469/system1/DrakeSys'

'MIMOFeedback_2451469/tf1/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2451469' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2451469') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2451469') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModelHandle/sim (line 112)
  In DynamicalSystem/simulate (line 120)
  In LinearInvertedPendulum.ZMPtrackingDemo (line 427) 
Found algebraic loop containing:
'MIMOFeedback_2451469/system2/DrakeSys'

'MIMOFeedback_2451469/tf2/DrakeSys'

'MIMOFeedback_2451469/system1/DrakeSys'

'MIMOFeedback_2451469/tf1/DrakeSys' (algebraic variable)

Error using MultiCoordinateFrame/findTransform (line 155)
Could not find any transform between CartTablePosition+CartTableVelocity and
CartTablePosition

Error in CoordinateFrame/findTransform (line 283)
            [tf,options] = findTransform(a.frame,target,options);

Error in PPTrajectory/inFrame (line 91)
        tf =
        findTransform(obj.getOutputFrame,frame,struct('throw_error_if_fail',true));
        
Error in PPTrajectory/subsref (line 506)
        [varargout{:}] = builtin('subsref',a,s);

Error in Visualizer/playback (line 85)
        xtraj = xtraj.inFrame(obj.getInputFrame);  % try to convert it

Error in LinearInvertedPendulum.ZMPtrackingDemo (line 428)
      v.playback(ytraj);

```

When I tried to run ` LinearInvertedPendulum.runLQR`, Matlab command showed,
```
>> LinearInvertedPendulum.runLQR
Warning: Block diagram 'MIMOFeedback_2729993' contains 1 algebraic loop(s). To see
more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2729993') </a> or the command line Simulink
debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2729993') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModel (line 25)
  In DynamicalSystem/mimoFeedback (line 215)
  In LinearInvertedPendulum.runLQR (line 406) 
Found algebraic loop containing:
'MIMOFeedback_2729993/system1/DrakeSys'

'MIMOFeedback_2729993/system2/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2729993' contains 1 algebraic loop(s). To see
more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2729993') </a> or the command line Simulink
debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2729993') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModelHandle/feval (line 125)
  In SimulinkModel (line 43)
  In DynamicalSystem/mimoFeedback (line 215)
  In LinearInvertedPendulum.runLQR (line 406) 
Found algebraic loop containing:
'MIMOFeedback_2729993/system1/DrakeSys'

'MIMOFeedback_2729993/system2/DrakeSys' (algebraic variable)

Warning: NARGCHK will be removed in a future release. Use NARGINCHK or
NARGOUTCHK instead. 
> In catstruct (line 46)
  In DynamicalSystem/mimoFeedback (line 229)
  In LinearInvertedPendulum.runLQR (line 406) 
Warning: Block diagram 'MIMOFeedback_2729993' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2729993') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2729993') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In getInitialState
  In sl (line 15)
  In Simulink.BlockDiagram/getInitialState
  In getSimulinkStateStructure (line 13)
  In DynamicalSystem/stateVectorToStructure (line 657)
  In DynamicalSystem/simulate (line 39)
  In LinearInvertedPendulum.runLQR (line 411) 
Found algebraic loop containing:
'MIMOFeedback_2729993/system1/DrakeSys'

'MIMOFeedback_2729993/system2/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2729993' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2729993') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2729993') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModel/getSampleTime (line 64)
  In DynamicalSystem/isCT (line 394)
  In DynamicalSystem/simulate (line 75)
  In LinearInvertedPendulum.runLQR (line 411) 
Found algebraic loop containing:
'MIMOFeedback_2729993/system1/DrakeSys'

'MIMOFeedback_2729993/system2/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2729993' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2729993') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2729993') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModel/getSampleTime (line 64)
  In DynamicalSystem/simulate (line 104)
  In LinearInvertedPendulum.runLQR (line 411) 
Found algebraic loop containing:
'MIMOFeedback_2729993/system1/DrakeSys'

'MIMOFeedback_2729993/system2/DrakeSys' (algebraic variable)

Warning: Block diagram 'MIMOFeedback_2729993' contains 1 algebraic loop(s). To
see more details about the loops use the command
<a href="matlab:Simulink.BlockDiagram.getAlgebraicLoops(bdroot);">Simulink.BlockDiagram.getAlgebraicLoops('MIMOFeedback_2729993') </a> or the command line
Simulink debugger by typing <a href="matlab:sldebug(bdroot);">sldebug('MIMOFeedback_2729993') </a> in the MATLAB command
window. To eliminate this message, set the Algebraic loop option in the
Diagnostics page of the Configuration Parameters Dialog to "None". 
> In SimulinkModelHandle/sim (line 112)
  In DynamicalSystem/simulate (line 120)
  In LinearInvertedPendulum.runLQR (line 411) 
Found algebraic loop containing:
'MIMOFeedback_2729993/system1/DrakeSys'

'MIMOFeedback_2729993/system2/DrakeSys' (algebraic variable)

Error using MultiCoordinateFrame/findTransform (line 155)
Could not find any transform between CartTablePosition+CartTableVelocity and
CartTablePosition

Error in CoordinateFrame/findTransform (line 283)
            [tf,options] = findTransform(a.frame,target,options);

Error in PPTrajectory/inFrame (line 91)
        tf =
        findTransform(obj.getOutputFrame,frame,struct('throw_error_if_fail',true));
        
Error in PPTrajectory/subsref (line 506)
        [varargout{:}] = builtin('subsref',a,s);

Error in Visualizer/playback (line 85)
        xtraj = xtraj.inFrame(obj.getInputFrame);  % try to convert it

Error in LinearInvertedPendulum.runLQR (line 412)
        v.playback(ytraj);
 
```

Could anyone tell me how to fix this?

Thank you!

### PR DESCRIPTION
**Pull request by RussTedrake**
This one was a one-liner.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4974)

### CODE REVIEW

**Comment by RussTedrake** [comment]
sigh.  turned out not to be a one liner.  but i had it paged in...

**Comment by sherm1** [comment]
I can't adequately review this, Russ.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4974#-:-Kbn5Hfu7BCaMjR_qFaJ:b1aknnd)*

**Comment by RussTedrake** [comment]
+@siyuanfeng-tri for feature review.  
I think that's probably enough, since our platform reviewers aren't worried about protecting the platform with this one.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4974#-:-KboNkLuWN5fprU6u_aP:b-ccmtih)*

**Comment by siyuanfeng-tri** [comment]
I am not that familiar with the matlab code base, but everything seems to be minor 
:lgtm: 

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4974#-:-KbontJkwpJskW4bAEms:bwiq14r)*

**Comment by jwnimmer-tri** [comment]
:lgtm: insofar as I agree it only needs a feature review.

**Pull request merged**
