### PR TITLE
Add a new frame Abar to specify the PositionConstraint bound.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@calderpg-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873#-:-Mz1PnGw7u_u6E-ygZup:b-g27em7)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri and @hongkai-dai)

___
*[multibody/inverse_kinematics/inverse_kinematics.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16873#-MzpsE9V-B9FFLtBQWGF:-MzpsE9V-B9FFLtBQWGG:b-40b227) ([raw file](https://github.com/robotlocomotion/drake/blob/873d59121c1ceab473aec4047a928cf64c1c4f4a/multibody/inverse_kinematics/inverse_kinematics.h#L124)):*
> ```objc
>       const Eigen::Ref<const Eigen::Vector3d>& p_BQ,
>       const Frame<double>& frameAbar,
>       const std::optional<math::RigidTransformd>& X_AAbar,
> ```

Wouldn't it make more sense for this to be `X_AbarA`?

If there are going to be two `AddPositionConstraint` methods, does this still need to be optional?
___
*[multibody/inverse_kinematics/position_constraint.h, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16873#-MzpslEC0yQy0VO1O5y-:-MzpslEC0yQy0VO1O5y0:b-c2phk0) ([raw file](https://github.com/robotlocomotion/drake/blob/873d59121c1ceab473aec4047a928cf64c1c4f4a/multibody/inverse_kinematics/position_constraint.h#L92)):*
> ```objc
>   PositionConstraint(const MultibodyPlant<double>* plant,
>                      const Frame<double>& frameAbar,
>                      const std::optional<math::RigidTransformd>& X_AAbar,
> ```

Same questions about this being `X_AbarA` and if the optional is necessary

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri and @hongkai-dai)

___
*[multibody/inverse_kinematics/inverse_kinematics.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16873#-MzpsE9V-B9FFLtBQWGF:-Mzq7IbE3ZrmLfwL12Xh:b-ldqitq) ([raw file](https://github.com/robotlocomotion/drake/blob/873d59121c1ceab473aec4047a928cf64c1c4f4a/multibody/inverse_kinematics/inverse_kinematics.h#L124)):*
> Wouldn't it make more sense for this to be X_AbarA

I would think that say I have a frame already defined in the sdf file as `A`, for example the robot end-effector frame, and then temporarily I might use some new frame Abar defined relative to A (for example the grasped spatula tip frame, whic his defined relative to the robot end-effector). Could you give me an example of your ideal use case?

> If there are going to be two AddPositionConstraint methods, does this still need to be optional?

I was thinking to deprecate the old AddPositionConstraint in another PR. Would you like to keep both functions around?

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri and @hongkai-dai)

___
*[multibody/inverse_kinematics/inverse_kinematics.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16873#-MzpsE9V-B9FFLtBQWGF:-MzumJ_9A8yR-ougyYPi:b4qd6l2) ([raw file](https://github.com/robotlocomotion/drake/blob/873d59121c1ceab473aec4047a928cf64c1c4f4a/multibody/inverse_kinematics/inverse_kinematics.h#L124)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> Wouldn't it make more sense for this to be X_AbarA

I would think that say I have a frame already defined in the sdf file as `A`, for example the robot end-effector frame, and then temporarily I might use some new frame Abar defined relative to A (for example the grasped spatula tip frame, whic his defined relative to the robot end-effector). Could you give me an example of your ideal use case?

> If there are going to be two AddPositionConstraint methods, does this still need to be optional?

I was thinking to deprecate the old AddPositionConstraint in another PR. Would you like to keep both functions around?
</blockquote></details>

The use case I have in mind is roughly
```
AddPositionConstraint(tool_frame, p_ToolQ, table_frame, X_TablePushFrame, push_frame_lower, push_frame_upper)
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[multibody/inverse_kinematics/inverse_kinematics.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16873#-MzpsE9V-B9FFLtBQWGF:-MzvakMy-p93hSE5ZIRG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/873d59121c1ceab473aec4047a928cf64c1c4f4a/multibody/inverse_kinematics/inverse_kinematics.h#L124)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

The use case I have in mind is roughly
```
AddPositionConstraint(tool_frame, p_ToolQ, table_frame, X_TablePushFrame, push_frame_lower, push_frame_upper)
```
</blockquote></details>

Done.
___
*[multibody/inverse_kinematics/position_constraint.h, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16873#-MzpslEC0yQy0VO1O5y-:-Mzvako40iyJm8FHhooj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/873d59121c1ceab473aec4047a928cf64c1c4f4a/multibody/inverse_kinematics/position_constraint.h#L92)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Same questions about this being `X_AbarA` and if the optional is necessary
</blockquote></details>

Done.

**Review by calderpg-tri — COMMENTED** [review]
Thanks! Testing this out in the push behavior.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873#-:-MzwM3UE-NMB_ILN_5u4:by79dyh)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
:lgtm: feature

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873#-:-N--dc1820AiDEHyMfMz:bxmhyuf)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873#-:-N--ecrcCVlcU9QkekMn:b-3lhrgq)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873#-:-N--yHS89-OafLV-Q3m4:bzus18)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[multibody/inverse_kinematics/position_constraint.h, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--v4Gw8kZxk1rAOuwN:-N--v4Gw8kZxk1rAOuwO:b-ucenxj) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.h#L87)):*
> ```objc
>    * @pre `frameA` and `frameB` must belong to `plant`.
>    * @pre p_AQ_lower(i) <= p_AQ_upper(i) for i = 1, 2, 3.
>    * @throws std::exception if `plant` is nullptr.
> ```

nit, this appears to be a lie.
___
*[multibody/inverse_kinematics/position_constraint.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--uhpE2B4taJZkvLNI:-N--uhpE2B4taJZkvLNJ:boo352k) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.cc#L21)):*
> ```cpp
> 
> PositionConstraint::PositionConstraint(
>     const MultibodyPlant<double>* const plant, const Frame<double>& frameAbar,
> ```

nit, the second const (in front of `plant`) is unnecessary.

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const
___
*[multibody/inverse_kinematics/position_constraint.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--uAuTA5mKL_lmJXWJ:-N--uAuTA5mKL_lmJXWK:bodwckf) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.cc#L67)):*
> ```cpp
> 
> PositionConstraint::PositionConstraint(
>     const MultibodyPlant<AutoDiffXd>* const plant,
> ```

nit, the second const is unnecessary.

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const
___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--wfk51k9LJQTvMokV:-N--wfk51k9LJQTvMokW:b-aizujr) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/bindings/pydrake/multibody/inverse_kinematics_py.cc#L83)):*
> ```cpp
>                   frameB, p_BQ, frameAbar, X_AbarA, p_AQ_lower, p_AQ_upper);
>             },
>             py::arg("frameB"), py::arg("p_BQ"), py::arg("frameAbar"),
> ```

BTW, this seems to be a deviation from the naming convention that Paul is pushing for. @mitiguy for awareness.

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873#-:-N--yK2g6tJZjmK-E-cR:b-c7f1bi)* status: 3 unresolved discussions (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[multibody/inverse_kinematics/position_constraint.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--uhpE2B4taJZkvLNI:-N-01-a08vqAQHTnRbsK:bufeqfx) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.cc#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the second const (in front of `plant`) is unnecessary.

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const
</blockquote></details>

Actually, this is A-ok in implementation. Retracted.
___
*[multibody/inverse_kinematics/position_constraint.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--uAuTA5mKL_lmJXWJ:-N-0149Q7hT46jIWyeSX:bufeqfx) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.cc#L67)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the second const is unnecessary.

https://drake.mit.edu/styleguide/cppguide.html#Use_of_const
</blockquote></details>

Actually, this is A-ok in implementation. Retracted.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/inverse_kinematics/position_constraint.h, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--v4Gw8kZxk1rAOuwN:-N-024UzDCbZA88_KEV6:b-yl9auu) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.h#L87)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this appears to be a lie.
</blockquote></details>

I think it does throw an exception as in https://github.com/RobotLocomotion/drake/blob/19e8d821a113a3b7382dc5ac75c9eb44487a192b/multibody/inverse_kinematics/position_constraint.cc#L47-L49.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[multibody/inverse_kinematics/position_constraint.h, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--v4Gw8kZxk1rAOuwN:-N-02Y2F67Qm0eA6ftuA:b-xzztdv) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.h#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it does throw an exception as in https://github.com/RobotLocomotion/drake/blob/19e8d821a113a3b7382dc5ac75c9eb44487a192b/multibody/inverse_kinematics/position_constraint.cc#L47-L49.
</blockquote></details>

The quoted code guards against `plant_context`, not `plant`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: :shipit: complete! all discussions resolved, LGTM from assignees calderpg-tri,xuchenhan-tri(platform) (waiting on @calderpg-tri and @xuchenhan-tri)

___
*[multibody/inverse_kinematics/position_constraint.h, line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--v4Gw8kZxk1rAOuwN:-N-0D5e31cKes8nkeqsk:b-nvftkw) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/multibody/inverse_kinematics/position_constraint.h#L87)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The quoted code guards against `plant_context`, not `plant`.
</blockquote></details>

Done for real.
___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--wfk51k9LJQTvMokV:-N-0D1CR4bVZX0petbgN:b-5x2qh1) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/bindings/pydrake/multibody/inverse_kinematics_py.cc#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this seems to be a deviation from the naming convention that Paul is pushing for. @mitiguy for awareness.
</blockquote></details>

Would you suggest an alternative name?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16873)* status: :shipit: complete! all discussions resolved, LGTM from assignees calderpg-tri,xuchenhan-tri(platform) (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16873#-N--wfk51k9LJQTvMokV:-N-0HVzS4tVhCERPt4ba:b-z2tg0d) ([raw file](https://github.com/robotlocomotion/drake/blob/f35753152411cadd4b225171c58b6a3316ce6773/bindings/pydrake/multibody/inverse_kinematics_py.cc#L83)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Would you suggest an alternative name?
</blockquote></details>

I don't think I can offer anything useful here. Even if we come up with more python friendly names right away, there should be a separate PR that addresses this for the entire file.

This comment only meant to put this issue on Paul's radar.

**Comment by mitiguy** [comment]
@xuchenhan-tri   Thanks for putting this on the radar.
@hongkai-dai  I have just started making Python-friendly names for some of the functions in SpatialVelocity, SpatialAcceleration, SpatialForce, SpatialMomentum, and Frame.  As it becomes more standardized, we will learn more about a good way to provide names, and this multi-argument command will be a good challenge for us.

**Pull request merged**
