### PR TITLE
Import slightly modified FindMatlab from upstream and remove cmake submodule

### PR DESCRIPTION
**Pull request by jamiesnape**
The background to the partial rollback from upstream CMake to the previous version used in Drake is that upstream also required some C++ changes to CMake. Functionally, they should be the same overall.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3586)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@billhoffman Please test with CMake 3.7.

**Comment by jamiesnape** [comment]
@billhoffman for feature review and @david-german-tri for platform review. High priority since various people are running into MEX-related bugs.

**Comment by billhoffman** [comment]
:lgtm: I removed FindMatlab and the Matlab test .cmake file from drake/cmake/modules and ran with cmake master and all the tests passed.  

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-:-KSqVNXkDJgi-9YZr_xv:bhf607c)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/modules/3.7/FindMatlab.cmake, line 0 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-KSqW8UbRy5saK38ZvDB:-KSqW8UbRy5saK38ZvDC:bh0lo3a) ([raw file](https://github.com/robotlocomotion/drake/blob/022ea30c96043c4cf7b7f76b2197616d6322c314/cmake/modules/3.7/FindMatlab.cmake#L0)):*
Is this identical to a version in CMake upstream between 3.6.x and 3.7.0? If not (IIRC this is the case), can we please add a comment to the top of the file explaining why, to avoid someone wandering off on a wild goose chase trying to match this file to something in upstream?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3586)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/modules/3.7/FindMatlab.cmake, line  at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-KSqW8UbRy5saK38ZvDB:-KSqctDqFhbEw_a02XWO:bvv8adi) ([raw file](https://github.com/robotlocomotion/drake/blob/022ea30c96043c4cf7b7f76b2197616d6322c314/cmake/modules/3.7/FindMatlab.cmake#L)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Is this identical to a version in CMake upstream between 3.6.x and 3.7.0? If not (IIRC this is the case), can we please add a comment to the top of the file explaining why, to avoid someone wandering off on a wild goose chase trying to match this file to something in upstream?
</details>
I will add the comment just before I merge to save the GitHub links to Jenkins for the benefit of @david-german-tri.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3586)*

**Comment by david-german-tri** [comment]
I have no idea what this is doing or why, but clearly it works, so :lgtm: I guess?  If you could update the PR description that would be appreciated.

---

Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/modules/3.7/FindMatlab.cmake, line  at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-KSqW8UbRy5saK38ZvDB:-KSqgDi7hDE29LzxeB-Q:b-9g07e1) ([raw file](https://github.com/robotlocomotion/drake/blob/022ea30c96043c4cf7b7f76b2197616d6322c314/cmake/modules/3.7/FindMatlab.cmake#L)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> I will add the comment just before I merge to save the GitHub links to Jenkins for the benefit of @david-german-tri.
</details>
Can you tell me what it's going to say?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-:-KSqgWinAWjAx4a_RqNN:b-ww6wdp)*

**Comment by jamiesnape** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/modules/3.7/FindMatlab.cmake, line  at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-KSqW8UbRy5saK38ZvDB:-KSqjFNO_V5p_6A2yU8D:blts7tp) ([raw file](https://github.com/robotlocomotion/drake/blob/022ea30c96043c4cf7b7f76b2197616d6322c314/cmake/modules/3.7/FindMatlab.cmake#L)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Can you tell me what it's going to say?  
</details>
Something like `Upstream FindMatlab required changes to the CMake C++ source code. This script has been modified to replicate the functionality in pure CMake.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3586)*

**Comment by mwoehlke-kitware** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/modules/3.7/FindMatlab.cmake, line  at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3586#-KSqW8UbRy5saK38ZvDB:-KSqkXm8MyZvf1OH173l:bmv8y19) ([raw file](https://github.com/robotlocomotion/drake/blob/022ea30c96043c4cf7b7f76b2197616d6322c314/cmake/modules/3.7/FindMatlab.cmake#L)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Something like `Upstream FindMatlab required changes to the CMake C++ source code. This script has been modified to replicate the functionality in pure CMake.`
</details>
May I suggest...

```cmake
# NOTICE: This file is not an exact copy of FindMatlab.cmake from upstream.
#
# Improvements made in upstream version depend on changes to the CMake C++
# source code. This copy has been modified to incorporate similar improvements
# without depending on the newer version of CMake.
```

...?

Feel free to wordsmith, especially the last sentence; my phrasing is maybe not the best. The main points of the suggestion are a) the use of `NOTICE:` and b) the "what" ('this file is not identical to upstream') precedes the "why".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3586)*

**Pull request merged**
