### PR TITLE
[common] Add polynomial matrix multiplication overloads

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a subset of the the code in #20057, plus a few fixes and more tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@AlexandreAmice for a quick sanity check / feature review, please.  This is 80% from your PR, plus a few cleanups, and the fix for `ndarray[Monomial] @ ndarray[Monomial]`.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: Thanks for doing this.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-:-NdB1Fwc7RdTllnPESOQ:b-pt8m0o)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/symbolic/polynomial.h` line 653 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB-a7z4yluERLHZweg:-NdB-a8-Cv4RTJfUKmhP:bw2tfar) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/polynomial.h#L653)):*
> ```objc
> 
> // Informs Eigen that Variable op Monomial gets Polynomial
> // where op ∈ {+, -, *, conj_product}.
> ```

I just checked, and noticed that `Variable op Monomial` and `Expression op Monomial` are not currently defined. I believe they should be, and that the return type of `Polynomial` (or `Monomial`) and `Expression` respectively are sensible. Not sure if we should go ahead and define them in this PR for consistency, or bind them later.
___
*[`common/symbolic/expression/expression.h` line 1371 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB05nR4UEu3EUMLtxJ:-NdB05nR4UEu3EUMLtxK:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/expression/expression.h#L1371)):*
> ```objc
>   static void CalcDV(const MatrixRef<double>& D, const MatrixRef<Variable>& V,
>                      EigenPtr<MatrixX<Expression>> result);
>   // Matrix product for Variabe, Variable.
> ```

nit: typo



_Suggestion:_
```objc
Variable
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB0aUr1ITouQERcCwn:-NdB0aUr1ITouQERcCwo:biykfpi) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/test/polynomial_matrix_test.cc#L71)):*
> ```cpp
>                          5.0, -9.0;   // [ 5.0  -9.0]
> 
>     // [0        cos(x + y)]
> ```

Comment doesn't match the expression



_Suggestion:_
```cpp
x
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 77 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB0eDTCaKoAtk9cf9y:-NdB0eDTCaKoAtk9cf9z:biykfpi) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/test/polynomial_matrix_test.cc#L77)):*
> ```cpp
>                              symbolic::sin(2 + var_x_ * var_y_),
>                              Expression{var_z_};
>     // [0        cos(x + y)]
> ```

Comment doesn't match the expression



_Suggestion:_
```cpp
x
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/symbolic/polynomial.h` line 653 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB-a7z4yluERLHZweg:-NdB5gZO1ZR0BMT6NmfO:bpuj3me) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/polynomial.h#L653)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I just checked, and noticed that `Variable op Monomial` and `Expression op Monomial` are not currently defined. I believe they should be, and that the return type of `Polynomial` (or `Monomial`) and `Expression` respectively are sensible. Not sure if we should go ahead and define them in this PR for consistency, or bind them later.
</blockquote></details>

Working on it...
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB0aUr1ITouQERcCwn:-NdB1yGR0O6MTZ3GeK80:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/test/polynomial_matrix_test.cc#L71)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Comment doesn't match the expression
</blockquote></details>

Done.
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 77 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdB0eDTCaKoAtk9cf9y:-NdB1yTs0q4daLhgKa-Q:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9a22305c1b1e65c74ec48e03edf828970b30f1ed/common/symbolic/test/polynomial_matrix_test.cc#L77)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Comment doesn't match the expression
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

@AlexandreAmice please check the new tests (and the open discussion), when you have time again.

> Dismissed @AlexandreAmice from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-:-NdbqO0SBSx_OY5PpQA1:b-wle4xe)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-:-NdgYChx95y9zUcM2aT1:bcpz082)* status: 11 unresolved discussions

___
*[`common/symbolic/expression/expression.h` line 1400 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdfQYs90jJ_yKhiGm3t:-NdfQYs90jJ_yKhiGm3u:b-c0dcxa) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/expression/expression.h#L1400)):*
> ```objc
> class ExpressionInnerProduct
>     : public Expression,
>       public Eigen::Map<Eigen::Matrix<Expression, 1, 1>> {
> ```

BTW, what's the rational behind this change? Why is multiple inheritance preferred here over conversion?
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 167 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgW6ICDNNmfyB3i-Sn:-NdgW6ICDNNmfyB3i-So:bwk7vvy) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L167)):*
> ```cpp
> 
> template <typename Vector1, typename Vector2>
> bool CheckDotProductResPoly(const Vector1& v1, const Vector2& v2) {
> ```

nit, I had a hard time understanding the difference between this function and the one immediately below. Consider adding a clarifying comment.
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 197 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXxa-Es2YMpFbX-sl:-NdgXxa-Es2YMpFbX-sm:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L197)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResExpr(v_expression_static_, v_poly_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 225 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXvTOAeXkt0oDGfl_:-NdgXvTOAeXkt0oDGfla:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L225)):*
> ```cpp
>       CheckDotProductResExpr(v_expression_static_, v_monomial_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 252 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXsxI-Ngw5IxvLsaJ:-NdgXsxI-Ngw5IxvLsaK:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L252)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_poly_static_, v_poly_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 278 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXqZ24if_oyDCKICb:-NdgXqZ24if_oyDCKICc:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L278)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_poly_static_, v_monomial_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 304 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXohd4nQYYep_5Cff:-NdgXohd4nQYYep_5Cfg:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L304)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_poly_static_, v_double_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 330 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgY0eo1bmbq7_ZQ-Kx:-NdgY0eo1bmbq7_ZQ-Ky:b3ksv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L330)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_poly_static_, v_variable_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

t



_Code quote:_
```cpp
{+, -, *}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 382 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXm0LBHCRdYfrav40:-NdgXm0LBHCRdYfrav41:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L382)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_monomial_static_, v_poly_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 408 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgXgKy1wG7Rai83NZX:-NdgXgKy1wG7Rai83NZY:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L408)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_monomial_static_, v_monomial_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 434 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgY5LK8oEPLZ8bz8IC:-NdgY5LK8oEPLZ8bz8ID:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L434)):*
> ```cpp
>   EXPECT_TRUE(CheckDotProductResPoly(v_monomial_static_, v_variable_dynamic_));
> 
>   // Checks Dynamic op Static where op = {+, -, *}.
> ```

nit



_Suggestion:_
```cpp
{+, -, * ·}
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099)* status: 2 unresolved discussions

___
*[`common/symbolic/expression/expression.h` line 1400 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdfQYs90jJ_yKhiGm3t:-NdhQZGkDsPB4k4r6hHV:bsy1e10) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/expression/expression.h#L1400)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, what's the rational behind this change? Why is multiple inheritance preferred here over conversion?
</blockquote></details>

When this class is reverted to its current implementation on master, there are call sites in Drake that no longer compile (because they were using the inner product of two `VectorN<Variable>` vectors.  Some of those call sites _must_ have an `Expression` and reject the Eigen decorator.  Some of those call sites _must_ have a `Vector1<Expression>` and reject the bare `Expression`.  I couldn't discover any other way to keep all existing calling-code intact, other than this.
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 167 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgW6ICDNNmfyB3i-Sn:-NdhQ4UlDXUQBU2EMbyA:b-c1zc9t) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L167)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, I had a hard time understanding the difference between this function and the one immediately below. Consider adding a clarifying comment.
</blockquote></details>

You're right, it's tricky.  I even struggled to write the comment.  Did it turn out okay?

**Comment by jwnimmer-tri** [comment]
@xuchenhan-tri any final thoughts?

**Review by xuchenhan-tri — COMMENTED** [review]
Sorry this one fell off my radar. :lgtm: 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-:-Ndq7bKz3qpOodMwqZ9w:b-b9qg0e)* status: 2 unresolved discussions

___
*[`common/symbolic/expression/expression.h` line 1400 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdfQYs90jJ_yKhiGm3t:-Ndq732N42T28C3308S4:b6zavw0) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/expression/expression.h#L1400)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When this class is reverted to its current implementation on master, there are call sites in Drake that no longer compile (because they were using the inner product of two `VectorN<Variable>` vectors.  Some of those call sites _must_ have an `Expression` and reject the Eigen decorator.  Some of those call sites _must_ have a `Vector1<Expression>` and reject the bare `Expression`.  I couldn't discover any other way to keep all existing calling-code intact, other than this.
</blockquote></details>

Makes sense, thanks for the explanation.
___
*[`common/symbolic/test/polynomial_matrix_test.cc` line 167 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20099#-NdgW6ICDNNmfyB3i-Sn:-Ndq7SDdDCQM9yh49-i7:b-5vdwyv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6f8602973a6a51648f09ed2ed2d20068147a43f5/common/symbolic/test/polynomial_matrix_test.cc#L167)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You're right, it's tricky.  I even struggled to write the comment.  Did it turn out okay?
</blockquote></details>

It's helpful, thanks.

**Pull request merged**
