### PR TITLE
[doc] Add release notes v1.36.0

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@hongkai-dai for review of breaking changes and mathematical program sections.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281#-:-ODgShyoC2wV8MIocd9M:brzl56x)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281#-:-ODh9Vd32HUa71-cdYbX:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

I pushed my final changes.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281#-:-ODwtdphCAm3tUaH9PJ7:bje6iy)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.36.0.md` line 86 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22281#-ODwt6Ti7LrywhxRU6JK:-ODwt6Ti7LrywhxRU6JL:b-vhqzu3) ([raw file](https://github.com/RobotLocomotion/drake/blob/a73824332e5c1a7c550b88c4254f2f90ddb811dc/doc/_release-notes/v1.36.0.md#L86)):*
> ```Markdown
> * Don't compute inertia of a HalfSpace when parsing mujoco files ([#22290][_#22290])
> * Fix bug with geometries in marginal contact ([#22153][_#22153])
> * Fix error spew in sdf parsing ([#22301][_#22301])
> ```

nit I think 22301 was a hotfix for a regression from 22013 (new in this release), so doesn't need its own release note?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`doc/_release-notes/v1.36.0.md` line 88 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/22281#-ODyPi5cE54732fqVJxD:-ODyPi5cE54732fqVJxE:byfm608) ([raw file](https://github.com/RobotLocomotion/drake/blob/c716beb19efa7e934edf5e6439a3660e729cd9de/doc/_release-notes/v1.36.0.md#L88)):*
> ```Markdown
> * Fix a `RenderEngineVtk` bug with handling phong materials in cloned instances ([#22170][_#22170])
> * Update and document `MultibodyPlant`'s default proximity values ([#21463][_#21463])
> * Add poisson disk sampling ([#22243][_#22243])
> ```

nit, this isn't really a new feature or a fix. The only reason that it's part of the release notes is that it adds a new dependency (poisson_disk_sampling_internal)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22281#-:-OE0dLSo92OG2fs_rYgk:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

**Pull request merged**
