### PR TITLE
limit_malloc: Avoid ASAN heap hazard

### LINKED ISSUE #14901: systems: LimitMalloc + Asan may not play nicely together?
See Slack: https://drakedevelopers.slack.com/archives/C270MN28G/p1618400443116900

Failure: https://drake-cdash.csail.mit.edu/test/171454211
```
+ git log -n 1 --oneline --no-decorate
a005c4081e simulator: Add test to track heap hygiene (#14900)
+ export CC=clang-9 CXX=clang++-9
+ bazel run --config=asan //systems/analysis:simulator_test
...
[ RUN      ] SimulatorTest.MonitorFunctionAndStatusReturn
munmap_chunk(): invalid pointer
{runfiles}/drake/tools/dynamic_analysis/asan: line 10: 47562 Aborted                 (core dumped) "$@"
```

Shallow investigation, post #14900, testing on a005c4081e
(1) Commenting out only `LimitMalloc` line allows it to pass.
(2) Commenting out everything in new test *except* for `LimitMalloc` causes the same issue.

Theory: `LimitMalloc` and `asan` checking do not want to play nicely together.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes #14901.

ASAN instrumentation hooks more heap-returning API than just the basic
set. strdup() is one; there may be others. The returned heap blocks come
from a private heap and can't be returned by libc's free(). Avoid the
potential crashes by removing hooks completely when ASAN is detected at
compile time.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jamiesnape for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905#-:-MYLC7Z75HsL8UJabA-1:bb357fc)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Review by rpoyner-tri — COMMENTED** [review]
FYI @ericcousineau-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905#-:-MYLCDIeDxtfr9czdNd0:b-lhcquo)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Comment by jamiesnape** [comment]
`LimitMallocTest.AvoidAsanTest` is unhappy.

**Comment by jamiesnape** [comment]
Once it is fixed, let's run:
```bash
linux-bionic-gcc-bazel-experimental-address-sanitizer
linux-bionic-clang-bazel-experimental-address-sanitizer
linux-focal-gcc-bazel-experimental-address-sanitizer
linux-focal-clang-bazel-experimental-address-sanitizer
mac-big-sur-clang-bazel-experimental-address-sanitizer
```

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905#-:-MYLaB3Q3fiSwsfBic7s:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905#-:-MYLrIQz1GUyaA_jQGWm:b-vtj4vo)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[common/test_utilities/test/limit_malloc_test.cc, line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14905#-MYLrsZJCcBDP8vmH-oa:-MYLrsZJCcBDP8vmH-ob:bqg3egd) ([raw file](https://github.com/robotlocomotion/drake/blob/a0f2a1fdcc713ee63f38140d71ddc0fe29aeb366/common/test_utilities/test/limit_malloc_test.cc#L134)):*
> ```cpp
> 
> TEST_P(LimitMallocTest, AvoidAsanTest) {
>   // ASAN instrumentation hooks strdup() and returns storage from a separate
> ```

nit "ASan"

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905)* status: 2 unresolved discussions (waiting on @rpoyner-tri)

___
*[common/test_utilities/limit_malloc.cc, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14905#-MYLsfZNCp3B2wMmbXsq:-MYLsfZNCp3B2wMmbXsr:b-l4870s) ([raw file](https://github.com/robotlocomotion/drake/blob/a0f2a1fdcc713ee63f38140d71ddc0fe29aeb366/common/test_utilities/limit_malloc.cc#L16)):*
> ```cpp
> 
> // Analyze the cases where heap hooks should be compiled and linked. Avoid
> // Apple platforms; also avoid ASAN builds (spelled various ways for different
> ```

nit "ASan" is the traditional capitalization.  Ditto throughout, below.  ("SAN" is not an acronym.)

(Aside: I thought I posted this during my first pass but either it got lost, or I accidentally deleted it.)

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks for indulging my nitpick.  Sometime I'll tell you about my good friend, MbP -- the bitter enemy of MBP.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14905#-:-MYLy7165XQ4qo_40GSO:bzezld)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),jamiesnape (waiting on @rpoyner-tri)

**Pull request merged**
