### PR TITLE
Fixed grammar in RgbdCamera description.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6377)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ggould-tri for all review please.

/cc: @kunimatsu-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6377#-:-KmtNogYyBksmTqYFr28:biusbjg)*

**Comment by kunimatsu-tri** [comment]
Oh, thanks for catching this @liangfok!

:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6377#-:-KmtR--Cca6gJLrQZf42:b-2i9qr7)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6377#-:-Kmud5MgRYX4qGCf3bW9:bnfp4nl)*

**Comment by liangfok** [comment]
-@ggould-tri

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6377#-:-Kmv6cq5cwA3PEA-bp-1:b-88goz0)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please.

**Pull request merged**
