### PR TITLE
Revert "[tools] Add empty file to allow CI wheel builds on Focal"

### LINKED ISSUE #21007: Fix wheel AMIs and/or setup to enable docker on Jammy
Lower priority outcropping of #20954, relates: https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/113

There's no actual ticket for this right now.  Will let us close #20954 without this blocking, it seems likely it's just an AMI fix but we need to discover and document it somewhere.

CC FYI @jwnimmer-tri @BetsyMcPhail @mwoehlke-kitware

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Reverts RobotLocomotion/drake#21020

Closes #21007

Wheels are building on Jammy, the Focal workaround can be removed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21069)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@sammy-tri for both reviews tomorrow please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21069#-:-NrmcFqN-5cm-BUKUjH4:b-rxr6yf)* status: LGTM missing from assignee sammy-tri(platform)

**Comment by jwnimmer-tri** [comment]
There's one more CI link we might as well fix up in the same PR?

https://github.com/RobotLocomotion/drake/blob/d421e3b9a35cefb39a137e8dc12b36d29d09f55a/doc/_pages/release_playbook.md#L130

Or I guess a separate PR is fine too, _shrug_.

**Comment by jwnimmer-tri** [comment]
Actually `buildcop.md` and `jenkins.md` have some links, too.

**Review by BetsyMcPhail — COMMENTED** [review]
Good catch, I'll clean those up in this PR

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21069#-:-NrmciPJ1kwLcsybzWxG:bz8srkj)* status: LGTM missing from assignee sammy-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +@jwnimmer-tri -@sammy-tri.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21069#-:-Nrmd07HAVkOY9ZTN7EB:b-klxzhc)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Pull request merged**
