### PR TITLE
[fem] Add Dirichlet BC to FemModel

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/fem/fem_model.h, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16889#-MzzAKNH1H8sGnjctol-:-MzzlQFqDi1GyARV9rl_:b-bvjcto) ([raw file](https://github.com/robotlocomotion/drake/blob/e789c4035430eda622eb40afbe00fb3e80d47db6/multibody/fem/fem_model.h#L186)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw. I personally the BC object would be nice to expose as part of the API. Not sure if you have other plans to resolve this TODO.
</blockquote></details>

Yes, I plan to expose it after a while.
___
*[multibody/fem/fem_model.cc, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16889#-Mzz9R3lEeIDpTobozfw:-Mzzmxx823pGtJhoRiGK:b5tc0ln) ([raw file](https://github.com/robotlocomotion/drake/blob/e789c4035430eda622eb40afbe00fb3e80d47db6/multibody/fem/fem_model.cc#L36)):*
> Compute the actual residual. That is, the state value minus the specified BC value.

The state value minus the specified BC value is *not* the actual residual. The residual has unit N while the state value as unit m, m/s, and m/s^2.

A useful thing to return would be the unprojected residual, which tells us the force being applied at BC. But for now, I'm content with a documentation.
___
*[multibody/fem/test/fem_model_test.cc, line 247 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16889#-MzzBT_M9gXLjR7GOcpY:-MzzqKeE0bDcDBhztyND:b-iai6zw) ([raw file](https://github.com/robotlocomotion/drake/blob/e789c4035430eda622eb40afbe00fb3e80d47db6/multibody/fem/test/fem_model_test.cc#L247)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, const
</blockquote></details>

I modify this matrix later on.
___
*[multibody/fem/test/fem_model_test.cc, line 251 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16889#-MzzBUHaBgxXwLAm11Ey:-MzzqS_XCZoPmTH0MLB6:b-gkagbu) ([raw file](https://github.com/robotlocomotion/drake/blob/e789c4035430eda622eb40afbe00fb3e80d47db6/multibody/fem/test/fem_model_test.cc#L251)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, const
</blockquote></details>

This matrix is being assigned to.

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review per rotation please thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889#-:-Mzzs0km4LcCexokSmo0:b-4xxft6)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[multibody/fem/fem_model.h, line 138 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16889#-N-3P5Jx4DlcQ1PCy-BS:-N-3P5Jx4DlcQ1PCy-BT:b5y83bw) ([raw file](https://github.com/robotlocomotion/drake/blob/8b61c00d95b2f2e21888ea8fb3419a26536cb5fd/multibody/fem/fem_model.h#L138)):*
> ```objc
>    given FEM state. Degrees of freedom under Dirichlet boundary condition are
>    not considered as part of the model when calculating the residual, and their
>    correspnding values are set to zero.
> ```

nit, typo

also, "are not considered" is not quite true? what about "The residual for degrees of freedom with Dirichlet boundary conditions is set to zero. Therefore their residual should not be used as a metric for the error on the boundary condition."



_Code quote:_
```objc
correspnding
```
___
*[multibody/fem/fem_model.h, line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16889#-N-3PkvrCN7Yj0F-TDHT:-N-3PkvrCN7Yj0F-TDHU:b4q8vk4) ([raw file](https://github.com/robotlocomotion/drake/blob/8b61c00d95b2f2e21888ea8fb3419a26536cb5fd/multibody/fem/fem_model.h#L147)):*
> Degrees of freedom under Dirichlet boundary condition are not considered as
   part of the model when calculating the tangent matrix. 

I'd remove that, since the model actually does include those DOFs in the system of equations.

Probably modify next line to state: "The corresponding row and column for a degree of freedom with Dirichlet boundary condition in the tangent matrix is set to zero..."

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889#-:-N-3qhgM7ZVg2Q4_VAEs:bhm0jc2)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fem/fem_model.h, line 147 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16889#-N-3PkvrCN7Yj0F-TDHT:-N-42MPxEBSuk_Hecsid:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b61c00d95b2f2e21888ea8fb3419a26536cb5fd/multibody/fem/fem_model.h#L147)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> Degrees of freedom under Dirichlet boundary condition are not considered as
   part of the model when calculating the tangent matrix. 

I'd remove that, since the model actually does include those DOFs in the system of equations.

Probably modify next line to state: "The corresponding row and column for a degree of freedom with Dirichlet boundary condition in the tangent matrix is set to zero..."
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16889)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
