### PR TITLE
Add MathematicalProgram::AddLinearConstraint taking symbolic::Formula

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4972)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-:-KblsUL1M71DCXs3GJpg:b-utjvo1)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-clang-experimental please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/convex_optimization_test.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-KbpWb1MR1_fQARPXKjy:-KbpWb1MR1_fQARPXKjz:b9fxj8b) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/test/convex_optimization_test.cc#L215)):*
> ```cpp
> 
>   // Add constraints.
>   prog.AddLinearConstraint(x(0) + x(1) >= 11);
> ```

Could you add a check here that the number of LinearConstraint stored in `prog` is incremented by 1?  We can check that by
```C++
int num_linear_cnstr = prog.linear_constraint().size();
prog.AddLinearConstraint(x(0) + x(1) >= 11);
EXPECT_EQ(num_linear_cnstr + 1, prog.linear_constraint().size());
```

We should also add this check for equality constraint `x(2) - x(0) - x(1) == 0`, that the number of linear constraints is unchanged, but the number of linear equality constraint is incremented. Same for the bounding box constraint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-:-KbpXLSYBluYi2wndLKD:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-:-KbpXSeqriXErIo0o-EW:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbp_-fklH6zr_AvSFct:-Kbp_-fl7eVNbWgkWRmp:b-wfw9pn) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/mathematical_program.h#L1110)):*
> ```objc
>    *
>    *  1. e1  <=  e2 , which is -oo <= e1 - e2 <= 0
>    *  2. e1  >=  e2 , which is   0 <= e2 - e1 <= +oo
> ```

The "which is" clause appears to be inconsistent with the earlier expression?

---

*[drake/solvers/test/convex_optimization_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbpajl45_9QariDkVTQ:-Kbpajl5P40-XhkuPuVW:b865exo) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/test/convex_optimization_test.cc#L223)):*
> ```cpp
>   prog.AddLinearConstraint(+x(2) >= 0);
> 
>   if (solver.SolverName() == "SNOPT") {
> ```

This `"SNOPT"` seems quite magic & brittle, and should be a kConstant or somehow otherwise programmatically set such as using `SnoptSolver().SolverName()`.  Someone might rename the string to "Snopt" for aesthetics and then all of the tests are wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-:-KbpbCagzNjvA5nx3Vny:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/convex_optimization_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbpajl45_9QariDkVTQ:-KbpbZX4bRtL5_t6yAzs:bhtk555) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/test/convex_optimization_test.cc#L223)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This `"SNOPT"` seems quite magic & brittle, and should be a kConstant or somehow otherwise programmatically set such as using `SnoptSolver().SolverName()`.  Someone might rename the string to "Snopt" for aesthetics and then all of the tests are wrong.
</blockquote></details>

That is a good point, let me fix it in my PR, I will add a static method `SolverName()` to all derived class of `MathematicalProgramSolverInterface`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/convex_optimization_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbpajl45_9QariDkVTQ:-KbpbylpPBQH2m2n5ihd:bbqzdu9) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/test/convex_optimization_test.cc#L223)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

That is a good point, let me fix it in my PR, I will add a static method `SolverName()` to all derived class of `MathematicalProgramSolverInterface`.
</blockquote></details>

@hongkai-dai , great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbp_-fklH6zr_AvSFct:-KbpcCp_il7Ae8DakA7H:bo6q7mh) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/mathematical_program.h#L1110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The "which is" clause appears to be inconsistent with the earlier expression?
</blockquote></details>

Thanks!!!

Done.

---

*[drake/solvers/test/convex_optimization_test.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-KbpWb1MR1_fQARPXKjy:-KbpeNeRRoVsvaoNiL6Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/test/convex_optimization_test.cc#L215)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you add a check here that the number of LinearConstraint stored in `prog` is incremented by 1?  We can check that by
```C++
int num_linear_cnstr = prog.linear_constraint().size();
prog.AddLinearConstraint(x(0) + x(1) >= 11);
EXPECT_EQ(num_linear_cnstr + 1, prog.linear_constraint().size());
```

We should also add this check for equality constraint `x(2) - x(0) - x(1) == 0`, that the number of linear constraints is unchanged, but the number of linear equality constraint is incremented. Same for the bounding box constraint.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by sherm1** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 1109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbpg2ViMKgGBTRGF7RL:-Kbpg2ViMKgGBTRGF7RM:b-jfrvfc) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/mathematical_program.h#L1109)):*
> ```objc
>    * program. The input formula @p f can be of the following forms:
>    *
>    *  1. e1  <=  e2 , which is -oo <= e1 - e2 <= 0
> ```

BTW, while `oo` gets the job done, we do allow use of Unicode `∞` in comments in case you feel compelled to use the real infinity symbol.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbpg2ViMKgGBTRGF7RL:-KbphPYQafOhvPhrkeD9:bq5tko3) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/mathematical_program.h#L1109)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, while `oo` gets the job done, we do allow use of Unicode `∞` in comments in case you feel compelled to use the real infinity symbol.
</blockquote></details>

BTW, even in source code, Unicode is great and should be encouraged.  (For instance, console messages.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/solvers/mathematical_program.h, line 1109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4972#-Kbpg2ViMKgGBTRGF7RL:-KbpiscUrJ_XEgMFfGlR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8dce532ae6034790d35b33aa18de0b7ba139778b/drake/solvers/mathematical_program.h#L1109)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, even in source code, Unicode is great and should be encouraged.  (For instance, console messages.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4972)*

**Pull request merged**
