### PR TITLE
Stop suppressing -Wunused-but-set-variable

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Toward #2372.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2475)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/testMobyLCP.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2475#-KJ6l_SxZOq2bTZffhiB:-KJ6l_SxZOq2bTZffhiC:1466652690) ([raw file](https://github.com/robotlocomotion/drake/blob/f926d588faa3c7cc94aa4644b148bc0d5b06f8c7/drake/solvers/test/testMobyLCP.cpp#L46)):*
> ```cpp
>   Eigen::VectorXd fast_z;
>   bool result = l.SolveLcpFast(M, q, &fast_z);
>   (void)(result);  // TODO(sammy-tri) Either use, or remove.
> ```

I'd be fine with just removing it if you're so inclined...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2475)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/testMobyLCP.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2475#-KJ6l_SxZOq2bTZffhiB:-KJ8TJke8DQiTXubJuwk:-1939730842) ([raw file](https://github.com/robotlocomotion/drake/blob/f926d588faa3c7cc94aa4644b148bc0d5b06f8c7/drake/solvers/test/testMobyLCP.cpp#L46)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I'd be fine with just removing it if you're so inclined...
</details>
I wasn't sure if the result was vestigial, or it was a missing test.  It's returned but unused here, and in the three spots below.  Nuke them all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2475)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for both reviews (low priority).

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Stop suppressing \-Wunused\-but\-set\-variable
> 
> Toward #2372.
> 
> 
> 
> 
> 
> 
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2475#-:-KJBBB-HELynadjw_dVq:-2085492103)*

**Comment by sammy-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/testMobyLCP.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2475#-KJ6l_SxZOq2bTZffhiB:-KJBP2ecm9I0lyavoxPh:477027376) ([raw file](https://github.com/robotlocomotion/drake/blob/f926d588faa3c7cc94aa4644b148bc0d5b06f8c7/drake/solvers/test/testMobyLCP.cpp#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I wasn't sure if the result was vestigial, or it was a missing test.  It's returned but unused here, and in the three spots below.  Nuke them all?
</details>
Sigh, it probably is (technically, since the other tests wouldn't pass anyway) a missing test.  Go ahead and TODO it to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2475)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@david-german-tri for both reviews (low priority).
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2475#-KJBaGRZ_CpMCIy9H-ds:-KJBaGR_rudOrK3qJF4t:-781474602) ([raw file](https://github.com/robotlocomotion/drake/blob/fdc00cf14465b8450426e36e268b916e7099e432/drake/systems/plants/test/testIKtraj.cpp#L21)):*
> ```cpp
>   Vector2d tspan;
>   tspan << 0, 1;
>   int l_hand{};
> ```

I guess one hand is sufficient to demonstrate that the IK works?  Even if this is a missing test, I don't know who should get the TODO, so whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2475#-:-KJBaYKLXFgLmdbFbipJ:1417088721)*

**Pull request merged**
