### PR TITLE
Port drake/systems to FindResource

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5893.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6238)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Update: I think I finally have all of the prereq's landed in order to make this work.  Will update after some more local testing.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by kunimatsu-tri** [comment]
+@kunimatsu-tri 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-:-Kna6GTmQX91KpuhJPlU:bx6nh9b)*

**Comment by kunimatsu-tri** [comment]
In `drake/systems/estimators/BUILD`, `"//drake/common:drake_path"` should be replaced with `"//drake/common:find_resource"`.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-:-KnaEMXnmRwUCz1LV0hh:b-vhl6vy)*

**Comment by kunimatsu-tri** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/BUILD, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-KnaDYVIuoGoxBurJWD_:-KnaDYVIuoGoxBurJWDa:b-7c2qxc) ([raw file](https://github.com/robotlocomotion/drake/blob/14dea8117e66deb46ddc84554b0a1ce2d348c042/drake/systems/controllers/BUILD#L144)):*
> ```Python
>         ":qp_common",
>         "//drake/common",
>         "//drake/common:drake_path",
> ```

This should be replaced with `"//drake/common:find_resource"`.

---

*[drake/systems/sensors/BUILD, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-KnaCGpmGtL_UvTOdwQI:-KnaCGpmGtL_UvTOdwQJ:bw8hiwl) ([raw file](https://github.com/robotlocomotion/drake/blob/14dea8117e66deb46ddc84554b0a1ce2d348c042/drake/systems/sensors/BUILD#L143)):*
> ```Python
>     ],
>     deps = [
>         "//drake/common:find_resource",
> ```

This seems unnecessary dependency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6238)*

**Comment by jwnimmer-tri** [comment]
Done.

---

Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/BUILD, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-KnaDYVIuoGoxBurJWD_:-KnaKAqt20bq8iqmKnye:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14dea8117e66deb46ddc84554b0a1ce2d348c042/drake/systems/controllers/BUILD#L144)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

This should be replaced with `"//drake/common:find_resource"`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/BUILD, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-KnaCGpmGtL_UvTOdwQI:-KnaKLLGnCHRS6jb9J1P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/14dea8117e66deb46ddc84554b0a1ce2d348c042/drake/systems/sensors/BUILD#L143)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

This seems unnecessary dependency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-:-KnaK6Xzv44uf0u5m9La:b-896fix)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-:-KnaLIAIGuX-NHN2_Yjx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 17 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6238#-:-Knb4LEC8GCDkXjMY-KE:bnfp4nl)*

**Pull request merged**
