### PR TITLE
Add header guards to drake/core/Vector.h

### PR DESCRIPTION
**Pull request by david-german-tri**

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Any chance we can migrate to using c++11 #pragma once instead? Maybe that's beyond the scope of your current PR.

**Comment by david-german-tri** [comment]
@rpoyner-tri I don't think `#pragma once` was included in C++11, so I would hesitate to use it.  I assume this is also the reason the style guide [mandates](https://google.github.io/styleguide/cppguide.html#The__define_Guard) the `#ifndef` approach.

If I'm wrong, citations welcome!

**Comment by rpoyner-tri** [comment]
Right. I stand corrected that #pragma once is not standard. However, it has broad support among current compilers, and the difficulties cited with its use (sym-links, hard links) seem unlikely to arise in a project that supports Windows/Mac/Linux portable development.

A (less than confidence-inspiring) reference: https://en.wikipedia.org/wiki/Pragma_once#Portability

**Comment by david-german-tri** [comment]
My opinion: the benefits are too small to merit a style guide exception, especially an exception in the direction of a nonstandard feature (however well supported it may be).

**Comment by jpieper-tri** [comment]
For what it is worth, more than once I have seen inexplicable compilation errors that were ultimately caused by someone forgetting to update the #ifndef at the top of a header they copied.  Thus I believe the benefits of #pragma once to be non-zero, and superior to that of many other style conventions.

**Comment by david-german-tri** [comment]
Static analysis should save us from such hassles.  The sooner we can get our cpplint noise to a manageable level, the better.

**Pull request merged**
