### PR TITLE
Add preliminary Python bindings and examples for systems framework.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is the initial binding of a small portion of the Systems framework in Python.

Introduces:
* Simplified diagram similar to that in `ExampleDiagram` (`//systems/framework:diagram_test`)
* Simple example to plot the graphviz image of a system, if `pydot` is installed.
* Simple example of implementing a custom system, and simulating said system
* Unittest indicating lifetime limitations using `unique_ptr` (to concretely track capabilities, if/when we decide to switch to `shared_ptr`s)

Caveats at present:
* This only introduces a small subset of the Systems framework (only `VectorBase`, no `AbstractValue`s, a small subset of primitives).
* This uses code off of my personal fork to enable passing `unique_ptr`s back and forth; I need to minimize the changes made (as pybind/pybind11#1146 is still in flight, and may end up being broken up, if it is able to land).

Tasks:
- [x] Merge a portion of pybind/pybind11#1146 into RobotLocomotion/pybind11.
    * See RobotLocomotion/pybind11#2 and RobotLocomotion/pybind11#3. Will remove "do not merge" ~if/when this lands~ once Mac tests pass.
- [x] Enable TravisCI or CircleCI for our fork of `pybind11`, if possible.
    * Was already enabled.
- [x] Add a test with different scoping (to see if ownership / `keep_alive` semantics are upheld)
- ~Add a test / example with an IPython notebook~ - slated

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7590)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jadecastro for feature review (if you're comfortable reviewing the Python bindings)
+@ggould-tri for platform review, please.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-:-L0m511VUQqUL9jwuszP:bq91vv6)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by ggould-tri** [comment]
:lgtm: pending notes below.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/systems/BUILD.bazel, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ocBvN3VitBWG6g2fI:-L0ocBvN3VitBWG6g2fJ:b-58d8qu) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/BUILD.bazel#L29)):*
> ```Python
>         "//drake/bindings/pydrake:common_py",
>         # TODO(eric.cousineau): This does NOT include direct dependencies to
>         # submodule. This is to preserve C++-like namespaces.
> ```

BTW It is not clear to me what this means or what remains to do here.

---

*[bindings/pydrake/systems/drawing.py, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0od2uwTWAyQWdT3yYi:-L0od2uwTWAyQWdT3yYj:bl95lt3) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L4)):*
> ```Python
> # Provides general visualization utilities. This is NOT related to `rendering`.
> # @note This is an optional module, dependent on `pydot` and `matplotlib` being
> # installed.
> ```

Is this a special pybind11 style of docstring?  Some sort of passthrough to doxygen? 
 I don't quite understand this.

---

*[bindings/pydrake/systems/framework_py.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0odvVpD8PVq7kCCg9H:-L0odvVpD8PVq7kCCg9I:bkt0rxy) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/framework_py.cc#L60)):*
> ```cpp
>     using Base = py::wrapper<System<T>>;
>     using Base::Base;
>     // Expose protected methods.
> ```

This seems dangerous.  Do we document anywhere the pitfalls that this might create?  Alternatively, if we are happy with DeclareInputPort being public here, why not also in the superclass?

Maybe it would make sense to export it with a _-prefixed name as is conventional in python for access-restricted fields.  This might at least force non-subclass users to fight the linter.

---

*[bindings/pydrake/systems/primitives_py.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ogFlxy170JI5e8FPo:-L0ogFlxy170JI5e8FPp:bu8zupp) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/primitives_py.cc#L35)):*
> ```cpp
>   py::class_<ZeroOrderHold<T>, LeafSystem<T>>(m, "ZeroOrderHold")
>     .def(py::init<double, int>());
> }
> ```

Why only these?  I suspect at least that anyone trying to use this will find themselves needing Multiplexer or Gain.  You should at least TODO that some systems are missing here so people will know whether or not it is intentional and whether they should just add anything they need.

---

*[bindings/pydrake/systems/test/custom_test.py, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ohAmNI5OAblhm_Npa:-L0ohAmNI5OAblhm_Npb:b2voofn) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/test/custom_test.py#L41)):*
> ```Python
>             sum += input_vector.get_value()
>         # TODO(eric.cousineau): Remove this when we ensure that we can mutate
>         # vectors. Not sure why this isn't working.
> ```

FYI -- This sounds like an issue that should have a bug number; consider filing it as a bug.

---

*[bindings/pydrake/systems/test/general_test.py, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ohRPKl7c-x5BzMbOf:-L0ohRPKl7c-x5BzMbOg:b-skwgdi) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/test/general_test.py#L75)):*
> ```Python
>         diagram = builder.Build()
>         # TODO(eric.cousineau): Figure out simple unicode handling, if
>         # necessary. (Restore the snowman.)
> ```

FYI nobody is going to know what you mean by this, including probably you if you get back to this a year later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-:-L0ohl7R7j57ETw5iegx:b-64us3w)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/systems/BUILD.bazel, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ocBvN3VitBWG6g2fI:-L0poKjEkfemN0hsMqUE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/BUILD.bazel#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW It is not clear to me what this means or what remains to do here.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/drawing.py, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0od2uwTWAyQWdT3yYi:-L0poMjjbKEQx1fp4ztA:b-k6i7kv) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L4)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Is this a special pybind11 style of docstring?  Some sort of passthrough to doxygen? 
 I don't quite understand this.
</blockquote></details>

Done. Nope, just me thinking in Bash mode.

---

*[bindings/pydrake/systems/framework_py.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0odvVpD8PVq7kCCg9H:-L0poS4TqTvf7icHS2jn:b4yeqw1) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/framework_py.cc#L60)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems dangerous.  Do we document anywhere the pitfalls that this might create?  Alternatively, if we are happy with DeclareInputPort being public here, why not also in the superclass?

Maybe it would make sense to export it with a _-prefixed name as is conventional in python for access-restricted fields.  This might at least force non-subclass users to fight the linter.
</blockquote></details>

Done. Following PEP8 - thanks for catching that!

---

*[bindings/pydrake/systems/primitives_py.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ogFlxy170JI5e8FPo:-L0pogAmWlO3rHrcFDFb:b-gmbzbk) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/primitives_py.cc#L35)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Why only these?  I suspect at least that anyone trying to use this will find themselves needing Multiplexer or Gain.  You should at least TODO that some systems are missing here so people will know whether or not it is intentional and whether they should just add anything they need.
</blockquote></details>

Done. (Added TODO.)

---

*[bindings/pydrake/systems/test/custom_test.py, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ohAmNI5OAblhm_Npa:-L0poldZL9WJdoRsHwwO:bk6o7hs) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/test/custom_test.py#L41)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- This sounds like an issue that should have a bug number; consider filing it as a bug.
</blockquote></details>

Done. (Just hadn't returned the right thing.)

---

*[bindings/pydrake/systems/test/general_test.py, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0ohRPKl7c-x5BzMbOf:-L0pomROsXqkJSXBM8La:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/test/general_test.py#L75)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI nobody is going to know what you mean by this, including probably you if you get back to this a year later.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590)*

**Comment by ggould-tri** [comment]
Nice; I like the new test especially.

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-:-L0prjDgmBMvPMG-2kq7:bzh38u1)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590)*

**Comment by jadecastro** [comment]
Pass complete.

---

Reviewed 15 of 16 files at r1, 4 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/drawing.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0oozZtspzML_UYL5wH:-L0oozZtspzML_UYL5wI:b-pk518l) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L1)):*
BTW, missing header?
> #!/usr/bin/env python

---

*[bindings/pydrake/systems/drawing.py, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0pNiL76xFP_6ADM79s:-L0pNiL76xFP_6ADM79t:b2ll5q1) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L25)):*
> ```Python
>     g = pydot.graph_from_dot_data(dot_text)
>     if isinstance(g, list):
>         # @see Ioannis's follow-up comment.
> ```

BTW, rather than this, you may as well consider just summarizing the gist of this comment, specific to what's in the code below. 

---

*[bindings/pydrake/systems/framework_py.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0t7ZpIDhOo2KEE9pDr:-L0t7ZpIDhOo2KEE9pDs:bwa22zt) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8d72ca2afb0557b22aaf9a4cca3410b9a72503/bindings/pydrake/systems/framework_py.cc#L7)):*
> ```cpp
> #include <pybind11/stl.h>
> 
> #include "drake/common/nice_type_name.h"
> ```

BTW, Is this unused?

---

*[bindings/pydrake/systems/test/custom_test.py, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0tciga7xzEebhTW0OB:-L0tciga7xzEebhTW0OC:b58jxag) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8d72ca2afb0557b22aaf9a4cca3410b9a72503/bindings/pydrake/systems/test/custom_test.py#L81)):*
> ```Python
>         simulator.StepTo(1)
>         # Ensure that we have the outputs we want.
>         state = diagram.GetMutableSubsystemState(zoh, context)
> ```

Since Simulator does not own the Diagram context, does it now share it?  If so, shall a test be added to test the equivalent of `simulator.get_mutable_context()`?

---

*[bindings/pydrake/systems/test/graphviz_example.py, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0opdx5-dwl116cZrWW:-L0opdx5-dwl116cZrWX:b5lbdpo) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/test/graphviz_example.py#L25)):*
> ```Python
> 
> plot_system_graphviz(diagram)
> plt.show()
> ```

BTW, Is there any tests to be checked here? Or is this purely for tutorial value? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-:-L0teleKwECHL20frPNz:bilrup7)*

**Comment by ggould-tri** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[bindings/pydrake/systems/drawing.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0oozZtspzML_UYL5wH:-L0tzMlzxWN-BG0sKbfN:bcyd2ak) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L1)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, missing header?
> #!/usr/bin/env python
</blockquote></details>

That doesn't seem right to me.  There's no main in here, so it's not executable and a shebang line would just confuse matters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/systems/drawing.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0oozZtspzML_UYL5wH:-L0tzpf9plZ7vbmSeofX:bhxjq64) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

That doesn't seem right to me.  There's no main in here, so it's not executable and a shebang line would just confuse matters.
</blockquote></details>

I see. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
Review status: 17 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[bindings/pydrake/systems/drawing.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0oozZtspzML_UYL5wH:-L0uwxDkr_aFO0ox5bEN:brb7rgd) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L1)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

I see. Thanks.
</blockquote></details>

BTW Would you be able to mark yourself as satisfied?

---

*[bindings/pydrake/systems/drawing.py, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0pNiL76xFP_6ADM79s:-L0twaeuZcsWa-fiNli2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/drawing.py#L25)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, rather than this, you may as well consider just summarizing the gist of this comment, specific to what's in the code below. 
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/framework_py.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0t7ZpIDhOo2KEE9pDr:-L0twbeffFT4-AsFj-5q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8d72ca2afb0557b22aaf9a4cca3410b9a72503/bindings/pydrake/systems/framework_py.cc#L7)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, Is this unused?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/custom_test.py, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0tciga7xzEebhTW0OB:-L0twcYJAjcYeXNTqYpi:b-k64fxb) ([raw file](https://github.com/robotlocomotion/drake/blob/1d8d72ca2afb0557b22aaf9a4cca3410b9a72503/bindings/pydrake/systems/test/custom_test.py#L81)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Since Simulator does not own the Diagram context, does it now share it?  If so, shall a test be added to test the equivalent of `simulator.get_mutable_context()`?
</blockquote></details>

Done. Added this into `general_test`.
And actually, the simulator *does* own the context, at this point.

---

*[bindings/pydrake/systems/test/graphviz_example.py, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-L0opdx5-dwl116cZrWW:-L0ttJLBdZOyh_6R8GuM:btcf8f0) ([raw file](https://github.com/robotlocomotion/drake/blob/798474c0b2cfd31850b7d08e33c7d4247d63f993/bindings/pydrake/systems/test/graphviz_example.py#L25)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, Is there any tests to be checked here? Or is this purely for tutorial value? 
</blockquote></details>

It's just for tutorial value. I've added a TODO in `BUILD.bazel` to have this be tested.
(I'm meta-testing plotting with `matplotlib` on CI with #7657).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7590#-:-L0v2zyDKbFaJkpToxFd:bnfp4nl)*

**Pull request merged**
