### PR TITLE
Add BasicVector leaf type support to ConstantVectorSource.

### LINKED ISSUE #3797: ConstantVectorSource should support typed outputs
Using `Clone()`.

### PR DESCRIPTION
**Pull request by david-german-tri**
@sherm1 for all review.   Fixes #3797.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5824)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm: pending two comment BTWs.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/constant_vector_source.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5824#-Khd7Le0QcHQVht5LrHY:-Khd7Le0QcHQVht5LrHZ:bra0h0w) ([raw file](https://github.com/robotlocomotion/drake/blob/6b6fd44fc3908e74e019ed7b0b1ed55f97e45e2b/drake/systems/primitives/constant_vector_source.h#L42)):*
> ```objc
> 
>   /// Constructs a system with a vector output that is constant, has the type of
>   /// the @p source_value, and equals the @p source_value at all times.
> ```

BTW, likely misleading to say it has the "type of the source_value". It actually strips away the type and just keeps the underlying Eigen vector. So if someone had derived a custom BasicVector subclass and passed it in here, they might think they would get that custom class as output.

---

*[drake/systems/primitives/test/constant_vector_source_test.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5824#-Khd8O_9sUmbRu4gHsBk:-Khd8O_9sUmbRu4gHsBl:b56q4lx) ([raw file](https://github.com/robotlocomotion/drake/blob/6b6fd44fc3908e74e019ed7b0b1ed55f97e45e2b/drake/systems/primitives/test/constant_vector_source_test.cc#L58)):*
> ```cpp
> 
> // Tests that the output of the ConstantVectorSource is correct with a
> // BasicVector model of AutoDiffXd.
> ```

BTW says "AutoDiffXd" but I'm seeing double?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5824#-:-Khd8kONei8bVb3MatMr:bd9cj1v)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/constant_vector_source.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5824#-Khd7Le0QcHQVht5LrHY:-Khd9EH7LdTqbKAfsm2r:bmb2lxd) ([raw file](https://github.com/robotlocomotion/drake/blob/6b6fd44fc3908e74e019ed7b0b1ed55f97e45e2b/drake/systems/primitives/constant_vector_source.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, likely misleading to say it has the "type of the source_value". It actually strips away the type and just keeps the underlying Eigen vector. So if someone had derived a custom BasicVector subclass and passed it in here, they might think they would get that custom class as output.
</blockquote></details>

Oh, sorry -- I think I misunderstood. Looks like the parent class correctly hangs on to the type and then paints it back on the saved Eigen vector. If that's right I retract my comment!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5824)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/constant_vector_source.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5824#-Khd7Le0QcHQVht5LrHY:-KhdXFLZWVWA2ZiHqBb5:b-zh4az5) ([raw file](https://github.com/robotlocomotion/drake/blob/6b6fd44fc3908e74e019ed7b0b1ed55f97e45e2b/drake/systems/primitives/constant_vector_source.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Oh, sorry -- I think I misunderstood. Looks like the parent class correctly hangs on to the type and then paints it back on the saved Eigen vector. If that's right I retract my comment!
</blockquote></details>

Yep, that's correct (and indeed, the point!)

---

*[drake/systems/primitives/test/constant_vector_source_test.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5824#-Khd8O_9sUmbRu4gHsBk:-KhdXSXelQ6h27dzNiEI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6b6fd44fc3908e74e019ed7b0b1ed55f97e45e2b/drake/systems/primitives/test/constant_vector_source_test.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW says "AutoDiffXd" but I'm seeing double?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5824)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5824)*

**Pull request merged**
