### PR TITLE
Remove support for Ubuntu 14.04 (Trusty)

### LINKED ISSUE #4913: Drake's build of Ipopt should not use Metis
Drake's build and use of Ipopt should not use Metis, due to licensing.  See #4045 for the citation to the non-EPL parts of Ipopt.

I recommend re-doing https://github.com/RobotLocomotion/ipopt-mirror/blob/master/get_ipopt_source.sh to disable even putting Metis into our repository, which then I think the configure code within Ipopt will see its absence and invoke the work-around.

Alternatively, it looks like Ipopt has the ability to set configure switches to disable using Metis even when the source is present.  That could possibly be an earlier first spiral.

### LINKED ISSUE #6853: divide_allowing_by_zero warning on GCC 4.8
When building with GCC 4.8, we see this ...
```
In file included from
external/drake/drake/systems/analysis/implicit_euler_integrator.cc:2:0:
external/drake/drake/systems/analysis/implicit_euler_integrator-inl.h:411:49:
warning: 'no_sanitize_undefined' attribute directive ignored [-Wattributes]
T divide_allowing_by_zero(const T& n, const T& d) {
```
... because that attribute is new as of GCC 4.9.

While Drake doesn't support GCC 4.8 officially in CI, we are keeping it clean on Trusty's GCC 4.8 for a short while longer, internally at TRI.  Please update the preprocessor guards on this line so that the attribute is only enabled for GCC >= 4.9.

/CC @stonier

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #5012. Closes #4913. Closes #6853.

For CI testing at the moment. I will open a release branch for Trusty before this is merged.

(Failures are expected for Trusty builds, for obvious reasons.)

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7158)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[WORKSPACE, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7158#-KvSv2WcybSAYTaFoJbe:-KvSv2WcybSAYTaFoJbf:b-a59tfy) ([raw file](https://github.com/robotlocomotion/drake/blob/d81cb74cea636338956789f51bb799224e3e117f/WORKSPACE#L221)):*
> ```Python
>     commit = "aecf5abd3913eebf1b99167c0edd4e65a6b414bc",
>     sha256 = "d88ea1b6b34c5678ef32ced22a6e9cb00f76a490f233d0b2d56270609eb94e3e",  # noqa
>     build_file = "tools/ipopt.BUILD",
> ```

The `ipopt.BUILD` file (and its helpers) are dead code now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158#-:-KvSwAa8xBX6qK4bEh1Q:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[WORKSPACE, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7158#-KvSv2WcybSAYTaFoJbe:-KvTg6qBDBH328FKCrFi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d81cb74cea636338956789f51bb799224e3e117f/WORKSPACE#L221)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `ipopt.BUILD` file (and its helpers) are dead code now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158)*

**Comment by EricCousineau-TRI** [comment]
:lgtm_strong: 

---

Reviewed 33 of 34 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158#-:-KvTut2E9i8vHpxRQW0s:b-uwkowd)*

**Comment by EricCousineau-TRI** [comment]
Seems that `drake-ci` is out of sync with this update - will this be force-merged?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158#-:-KvTv1PnCTI2cgHsM4tj:b-jhtgv5)*

**Comment by jamiesnape** [comment]
Have to do various reconfiguration. The Trusty builds will be switched off on PR's before this merges.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7158#-:-KvU2gZyoO3P4pdEzzaT:bjkwlkq)*

**Pull request merged**
