### PR TITLE
Added instructions on how to run long running unit tests.

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2078

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2386) &emsp; Multiple assignees:&emsp;@Lucy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/Lucy-tri">Lucy-tri</a>,&emsp;@amcastro-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/amcastro-tri">amcastro-tri</a>,&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@sammy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sammy-tri">sammy-tri</a>

### CODE REVIEW

**Comment by liangfok** [comment]
+@sammy-tri  for feature review please.
+@david-german-tri for platform review please

+@lucy-tri - I'm tagging you b/c you may be interested in this.
+@amcastro-tri - I'm tagging you b/c this modifies your previous PR https://github.com/RobotLocomotion/drake/pull/2186.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added instructions on how to run log running unit tests\.
> 
> Closes https://github.com/RobotLocomotion/drake/issues/2078
> 
> 
> </details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-:-KI-RHt511G5pKRfYZze:-1575910253)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@sammy-tri  for feature review please.
> +@david-german-tri for platform review please
> 
> +@lucy-tri - I'm tagging you b/c you may be interested in this.
> +@amcastro-tri - I'm tagging you b/c this modifies your previous PR https://github.com/RobotLocomotion/drake/pull/2186.</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/developers.rst, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-KI-ckXT-OJC_dsPlzqD:-KI-ckXT-OJC_dsPlzqE:-679461945) ([raw file](https://github.com/robotlocomotion/drake/blob/91f979d94c2a8acf7a25f5ea714f91d125547c02/drake/doc/developers.rst#L14)):*
> ```reStructuredText
> via the Github website. Your code will then undergo an interactive review
> process before it is merged into Drake's primary repository. Please read on for
> more information on testing, supported platforms, code review, required code
> ```

Optional: I think we could just drop this sentence.

---

*[drake/doc/unit_testing_instructions.rst, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-KI-cDOLGuG1SEie8Xbi:-KI-cDOLGuG1SEie8Xbj:-264490489) ([raw file](https://github.com/robotlocomotion/drake/blob/91f979d94c2a8acf7a25f5ea714f91d125547c02/drake/doc/unit_testing_instructions.rst#L48)):*
> ```reStructuredText
> ================================
> 
> Drake by default disables a number of long running unit tests to avoid
> ```

This isn't quite accurate.  How about:

`Drake disables a number of long-running unit tests by default.  To reduce continuous integration turnaround time, these tests run on the build servers post-submit, but not pre-submit. To run these tests locally, execute:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-:-KI-crZJW2dD_f0kir_W:1417088721)*

**Comment by liangfok** [comment]
Thanks for the review. I've addressed your comments.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 1 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-KI-ckXT-OJC_dsPlzqD:-KI-dkItwwzZxcTBGa12:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/91f979d94c2a8acf7a25f5ea714f91d125547c02/drake/doc/developers.rst#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Optional: I think we could just drop this sentence.</details>
Done.

---

*[drake/doc/unit_testing_instructions.rst, line 48 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-KI-cDOLGuG1SEie8Xbi:-KI-dxkdHJUnTo-FtQvM:-795674652) ([raw file](https://github.com/robotlocomotion/drake/blob/91f979d94c2a8acf7a25f5ea714f91d125547c02/drake/doc/unit_testing_instructions.rst#L48)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This isn't quite accurate.  How about:
> 
> `Drake disables a number of long-running unit tests by default.  To reduce continuous integration turnaround time, these tests run on the build servers post-submit, but not pre-submit. To run these tests locally, execute:"</details>
Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-:-KI-e4aKDqSS4DnaVVGQ:1472278411)*

**Comment by amcastro-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks for the review. I've addressed your comments.</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-:-KI-lspk_MlWmH8WrZmM:1417088721)*

**Comment by liangfok** [comment]
Oops. I accidentally updated this PR with some more changes to the wiki. PTAL.

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-:-KI2syBjKKrG9SfD8zjy:1952494614)*

**Comment by Lucy-tri** [comment]
Its great to see this spelled out more, with better definitions, etc. :lgtm: 

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Oops. I accidentally updated this PR with some more changes to the wiki. PTAL.
</details>


---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2386#-:-KI3BS3FJ1wJ8-uZrhTw:-756335752)*

**Pull request merged**
