### PR TITLE
Simplify adding externals that use Autotools

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4095)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm: functionally with style nits and a point on naming

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/externals.cmake, line 320 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDztOR0p9NYU3z76RQ:-KWDztOR0p9NYU3z76RR:b-6mbt2h) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L320)):*
> ```CMake
> #   PUBLIC - External is public
> #   CMAKE  - External uses CMake
> #   AUTOTOOLS  - External uses Autotools
> ```

Please add spaces to keep `-`s aligned. (Also, only one space before a `-` except when aligning. Since this is a block with aligned `-`s, it's okay if you're trying to make the aligned `-`s be in a specific column.)

---

*[cmake/externals.cmake, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDzyttfhQlLxEE3N34:-KWDzytu_cx0NGR4rkv2:b80eybg) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L356)):*
> ```CMake
> #       Additional environment variables to be passed to the Autotools
> #       external's configure command.
> #   AUTOTOOLS_ARGS <args...>
> ```

Maybe `AUTOCONF_ARGS` (or even `CONFIGURE_ARGS`) to make clear these apply to the configure step? Also, nit: blank line between different options with multi-line descriptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-:-KWE0GiODIRnxRfB149z:b5adoz7)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/externals.cmake, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDzyttfhQlLxEE3N34:-KWE28VbEeq7nP_GF2V4:b-azdm8d) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L356)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Maybe `AUTOCONF_ARGS` (or even `CONFIGURE_ARGS`) to make clear these apply to the configure step? Also, nit: blank line between different options with multi-line descriptions.
</details>
I would assume `AUTOCONF_ARGS` would be args to `autoconf`, which would already have been run by now. `CONFIGURE_ARGS` would probably be better. `AUTOTOOLS_CONFIGURE_ARGS` would be unambiguous, but long.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/externals.cmake, line 320 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDztOR0p9NYU3z76RQ:-KWE5WZ88c6Xpl0w67jb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L320)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Please add spaces to keep `-`s aligned. (Also, only one space before a `-` except when aligning. Since this is a block with aligned `-`s, it's okay if you're trying to make the aligned `-`s be in a specific column.)
</details>
Done.

---

*[cmake/externals.cmake, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDzyttfhQlLxEE3N34:-KWE5Y2KUa18OWAwBIAq:b-i8k150) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L356)):*
> AUTOTOOLS_CONFIGURE_ARGS

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDzyttfhQlLxEE3N34:-KWE67qeyLNwW_liDUa5:brgqbjl) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L356)):*
>> Also, nit: blank line between different options with multi-line descriptions.

...not done :wink:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDzyttfhQlLxEE3N34:-KWE9CO2V5OHy_nF7qrY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L356)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> >> Also, nit: blank line between different options with multi-line descriptions.
> 
> ...not done :wink:.
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWDzyttfhQlLxEE3N34:-KWE9VdOP7XZjC3Kd9Y0:bpqrvh1) ([raw file](https://github.com/robotlocomotion/drake/blob/c1cc3987f1a6246aa99a0c245f89c89015ca6c7b/cmake/externals.cmake#L356)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Done.
</details>
:+1: :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095)*

**Comment by david-german-tri** [comment]
Looks like maybe the MATLAB tests disappeared?  https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-matlab/691/

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 239 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWEQB_r1T8yqqK4DEb_:-KWEQB_r1T8yqqK4DEba:b7iwsd0) ([raw file](https://github.com/robotlocomotion/drake/blob/7f3c01f05529dec18bb93ffac9e1b69e6f71c72d/cmake/externals.cmake#L239)):*
> ```CMake
>     ${_ext_AUTOTOOLS_ENV})
> 
>   if(NOT DEFINED _ext_CONFIGURE_COMMAND)
> ```

is `_ext_CONFIGURE_COMMAND` ever defined?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-:-KWEQeIi5Fk16U3bnIPL:boe08r3)*

**Comment by jamiesnape** [comment]
No, just CMake choking on XML file. They are all there.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/externals.cmake, line 239 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-KWEQB_r1T8yqqK4DEb_:-KWERAFopWvOqKoh3yup:b4pjqbf) ([raw file](https://github.com/robotlocomotion/drake/blob/7f3c01f05529dec18bb93ffac9e1b69e6f71c72d/cmake/externals.cmake#L239)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> is `_ext_CONFIGURE_COMMAND` ever defined?  
</details>
Not in current usage, but it could be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-:-KWERH1CbeV-r_z3Jlqv:b5mhy2l)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4095#-:-KWETNJS-3FDrmTIo2cT:bnfp4nl)*

**Pull request merged**
