### PR TITLE
[tools] Add drake_lcm_cc_library opt-in for new lcm_gen

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This offers a build-system toggle on a per-rule basis for which C++ message code generator to use.

Towards #20761.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20903)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20903#-:-Nq4ije75zqJcMrOrI3c:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20903#-:-Nq4wT3U8Ff_4r7iyIuh:bg7igkv)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
