### PR TITLE
[py yaml] Add yaml_dump_typed to complement yaml_load_typed

### LINKED ISSUE #19597: Add yaml_dump_typed
We already have https://drake.mit.edu/pydrake/pydrake.common.yaml.html#pydrake.common.yaml.yaml_load_typed for loading using a typed schema.

We'd like to offer the complementary operation (saving aka dumping), using types.  At the moment, we only offer untyped dumping https://drake.mit.edu/pydrake/pydrake.common.yaml.html#pydrake.common.yaml.yaml_dump.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19597.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@EricCousineau-TRI for feature, :lgtm_strong: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-:-Nn6Pq0O7JUVtqbDkq-d:b5sy4w8)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 744 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6RfTJ-2H1ZP2WwTOH:-Nn6RfTJ-2H1ZP2WwTOI:b-whu382) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/test/yaml_typed_test.py#L744)):*
> ```Python
>             ),
>         ]
>         schema = typing.Dict[str, float]
> ```

Working: Unclear if we support this in `yaml_load_typed`.
___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 744 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6Rjlr2bHgSWEuAraU:-Nn6Rjlr2bHgSWEuAraV:b-5n88hl) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/test/yaml_typed_test.py#L744)):*
> ```Python
>             ),
>         ]
>         schema = typing.Dict[str, float]
> ```

Working: (pre-existing) Unclear what `yaml_load_typed` and `yaml_dump_typed` looks like for things like `list[T]`, `Optional[T]`, etc.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/yaml.py` line 455 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6Sm-p6Yy3olHnLR82:-Nn6Sm-q10au1yaBx-Op:bg4p8gl) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/yaml.py#L455)):*
> ```Python
> 
>     This mimics the C++ function ``drake::common::yaml::LoadYamlFile``.
>     This is the complementary operation to ``yaml_dump_typed``.
> ```

nit This is not entirely accurate.

`yaml_dump_typed` does not require that `schema` be a `dataclass`, while this function does (at least per its docstring).
Is it possible to relax that constraint, and allow `yaml_load_typed` to accept non-`dataclass` types?
___
*[`bindings/pydrake/common/yaml.py` line 458 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6T83g3rhD-fkAgGgK:-Nn6T83g3rhD-fkAgGgL:b-1ho71w) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/yaml.py#L458)):*
> ```Python
> 
>     Args:
>         schema: The type to load. Must be a ``dataclass``. (Adding support for
> ```

nit I did not see a test for the constraint of "must be a `dataclass`".

Did I miss that test?
___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 744 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6RfTJ-2H1ZP2WwTOH:-Nn6T1id5T9NjC-KZaUY:bog9bvq) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/test/yaml_typed_test.py#L744)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Unclear if we support this in `yaml_load_typed`.
</blockquote></details>

Done. See above - per documented contract, though.

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

^^^ has nothing to do with this PR, testing integrations still work is all

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 744 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6Rjlr2bHgSWEuAraU:-Nn7H8D57SQ28fMb3Nm2:b-616pad) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/test/yaml_typed_test.py#L744)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: (pre-existing) Unclear what `yaml_load_typed` and `yaml_dump_typed` looks like for things like `list[T]`, `Optional[T]`, etc.
</blockquote></details>

The following two test cases fail with non-user-friendly error cases:
https://github.com/RobotLocomotion/drake/commit/110f6c6f5dd66ed348a0135683f459ecd92490f4

Worth adding tests for some form of this, perhaps just capturing current behavior?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: needs at least two assigned reviewers

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 744 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6Rjlr2bHgSWEuAraU:-Nn9tvlZDkz8QzYpQh9j:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/test/yaml_typed_test.py#L744)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The following two test cases fail with non-user-friendly error cases:
https://github.com/RobotLocomotion/drake/commit/110f6c6f5dd66ed348a0135683f459ecd92490f4

Worth adding tests for some form of this, perhaps just capturing current behavior?
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: questions

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-:-NnApUNo9l6ASr-E27Ba:b-rzcdaa)* status: 2 unresolved discussions

___
*[`bindings/pydrake/common/yaml.py` line 551 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-NnAp5g6Ahyf4vuP7yA3:-NnAp5g6Ahyf4vuP7yA4:b-eggd96) ([raw file](https://github.com/RobotLocomotion/drake/blob/467028295b57396aa56f044ce8e19ec442b6f465/bindings/pydrake/common/yaml.py#L551)):*
> ```Python
>         (key_schema, value_schema) = generic_args
>         if key_schema != str:
>             raise RuntimeError(f"Dict keys must be strings, not {key_schema}")
> ```

minor: I see that this restriction is a mirror of the assertion in `*load_typed*`, but I haven't been able to find where the restriction arises from  originally. Worth some documentation maybe?
___
*[`bindings/pydrake/common/yaml.py` line 632 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-NnAizNt3TarI8c5fwXz:-NnAizNt3TarI8c5fwY-:bfx1brl) ([raw file](https://github.com/RobotLocomotion/drake/blob/467028295b57396aa56f044ce8e19ec442b6f465/bindings/pydrake/common/yaml.py#L632)):*
> ```Python
>         sub_node = node[key]
>         sub_defaults = defaults[key]
>         if sub_node is sub_defaults or sub_node == sub_defaults:
> ```

BTW, why do we try both `is` and `==` here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: 1 unresolved discussion

___
*[`bindings/pydrake/common/yaml.py` line 455 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20722#-Nn6Sm-p6Yy3olHnLR82:-NnAucoU-VjTPTz8calU:b-83330m) ([raw file](https://github.com/RobotLocomotion/drake/blob/d752535a0e4963d06787f281fad00fa85a8e988e/bindings/pydrake/common/yaml.py#L455)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is not entirely accurate.

`yaml_dump_typed` does not require that `schema` be a `dataclass`, while this function does (at least per its docstring).
Is it possible to relax that constraint, and allow `yaml_load_typed` to accept non-`dataclass` types?
</blockquote></details>

PTAL.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: 1 unresolved discussion

**Comment by jwnimmer-tri** [comment]
Sigh.  Python 3.8 is _so annoying_.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: 1 unresolved discussion

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20722)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
