### PR TITLE
Adds loopback support to DrakeMockLcm.

### PR DESCRIPTION
**Pull request by liangfok**
This was extracted from #4682, where it was found that the ability to fake a LCM message loopback is useful to allow a unit test to avoid touching the real network stack.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4855)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for feature review since you asked about the existence​ of this feature here: https://reviewable.io/reviews/robotlocomotion/drake/3643#-KTQp3OspLbFiI8Uweil

+@sherm1 for platform review since the next work day is Monday.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-:-Kb6NGWcJ1mUWYO4cdrt:bnq7akc)*

**Comment by liangfok** [comment]
This PR passed all pre-merge CI checks and is thus ready for review.

**Comment by sherm1** [comment]
Platform: :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-:-Kb6tD0JVeY9OLz7lBNt:b-nxaeye)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/drake_mock_lcm.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-KbAr_NwotaR_CBsdcOK:-KbAr_NwotaR_CBsdcOL:b6yf9nn) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c587a8d36cfb420a7dccd558478ae13f52da9/drake/lcm/drake_mock_lcm.h#L14)):*
> ```objc
> namespace lcm {
> 
> enum LoopbackSwitch { kWithoutLoopback = 0, kWithLoopback = 1 };
> ```

BTW Do you really want kWith(out)Loopback as namespace-level constants?  To me, they only make sense in the context of the `DrakeMockLcm` class, not anything `drake::lcm`-related.

---

*[drake/lcm/drake_mock_lcm.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-KbArkWMAJuNWM7eJaOT:-KbArkWMAJuNWM7eJaOU:b-v0djwk) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4c587a8d36cfb420a7dccd558478ae13f52da9/drake/lcm/drake_mock_lcm.h#L34)):*
> ```objc
>    * functions being called.
>    */
>   explicit DrakeMockLcm(LoopbackSwitch loop_back_switch);
> ```

BTW Would making this a setter instead of ctor keep the unit testing simpler?  This PR has no example uses, so I can't tell is the ctor is strictly required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4855)*

**Comment by david-german-tri** [comment]
:lgtm:, though I agree with both the open BTWs

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-:-KbB13ySS-xOO3hiO8CA:b-7gtat7)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/drake_mock_lcm.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-KbAr_NwotaR_CBsdcOK:-KbB6WoehVsUraxO7Mfe:b-6raxma) ([raw file](https://github.com/robotlocomotion/drake/blob/bbd6f237f1b9d70480e365b79bfdbab8ed0db9d9/drake/lcm/drake_mock_lcm.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do you really want kWith(out)Loopback as namespace-level constants?  To me, they only make sense in the context of the `DrakeMockLcm` class, not anything `drake::lcm`-related.
</blockquote></details>

Done. I removed the enum.

---

*[drake/lcm/drake_mock_lcm.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-KbArkWMAJuNWM7eJaOT:-KbB7uQRetbY1Yzs4n21:bvzvjap) ([raw file](https://github.com/robotlocomotion/drake/blob/bbd6f237f1b9d70480e365b79bfdbab8ed0db9d9/drake/lcm/drake_mock_lcm.h#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Would making this a setter instead of ctor keep the unit testing simpler?  This PR has no example uses, so I can't tell is the ctor is strictly required.
</blockquote></details>

Here is an example use case:

https://github.com/liangfok/drake/blob/eca4f8d4d4426a6c7ae23bcd77b896484605b68c/drake/systems/sensors/test/accelerometer_test/accelerometer_test.cc#L120

It is not strictly necessary. I could replace the one line:

```
::drake::lcm::DrakeMockLcm lcm(::drake::lcm::LoopbackSwitch::kWithLoopback);
```

With two lines:

```
::drake::lcm::DrakeMockLcm lcm;
lcm.EnableLoopBack();
```
Which I did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-:-KbBI6QRzcSb7iRvR_81:bblnx7i)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4855#-:-KbBXOeUrRaBxjYpfPKO:bnfp4nl)*

**Pull request merged**
