### PR TITLE
Add OS X related Valgrind suppressions

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3034)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Could you please provide a link to the errors this will suppress?  (I can't find Mac valgrind in CDash, so I assume this is preparatory.)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3034#-:-KOG873ZJAMh58H-VwiU:1847377780)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-memcheck-valgrind please

**Comment by jamiesnape** [comment]
`/usr/local/bin/python` suppressions are exactly the same as the `/usr/bin/python2.7` ones. `_ZN4dyld4loadEPKcRKNS_11LoadContextE` is the dynamic library loader.

**Comment by jamiesnape** [comment]
https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=69113

**Comment by jamiesnape** [comment]
Note that the Valgrind builds have been failing for some time. This PR does not affect that either way.

**Comment by jamiesnape** [comment]
@david-german-tri Is this good to merge? You can compare the above build with the first nightly on the dashboard now to see the difference.

**Comment by david-german-tri** [comment]
I don't entirely understand what I'm looking at.  Let's talk through it at our sync this morning.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3034#-:-KOKwDfa0_EcDDwoOVhC:-4912244)*

**Comment by jamiesnape** [comment]
Suppressed are mostly ones like this:
```
 ==61060== Conditional jump or move depends on uninitialised value(s)
==61060==    at 0x7FFF5FC23DC7: bcmp (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC11AF4: ImageLoaderMachO::validateFirstPages(linkedit_data_command const*, int, unsigned char const*, unsigned long, long long, ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC16D6A: ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, encryption_info_command const*, ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC10C5E: ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC038C2: dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC085BF: dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC082DF: dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC08044: dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC07799: dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC0347A: dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC0315E: dyld::load(char const*, dyld::LoadContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC088F9: dyld::libraryLocator(char const*, bool, char const*, ImageLoader::RPathChain const*) (in /usr/lib/dyld)
==61060== 
UMR ==61060== Use of uninitialised value of size 8
==61060==    at 0x7FFF5FC23DDF: bcmp (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC11AF4: ImageLoaderMachO::validateFirstPages(linkedit_data_command const*, int, unsigned char const*, unsigned long, long long, ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC16D6A: ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, encryption_info_command const*, ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC10C5E: ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC038C2: dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC085BF: dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC082DF: dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC08044: dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC07799: dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC0347A: dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, std::__1::vector >*) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC0315E: dyld::load(char const*, dyld::LoadContext const&) (in /usr/lib/dyld)
==61060==    by 0x7FFF5FC088F9: dyld::libraryLocator(char const*, bool, char const*, ImageLoader::RPathChain const*) (in /usr/lib/dyld)
```

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3034#-:-KOKygYCzXanPfh-C34-:1417088721)*

**Pull request merged**
