### PR TITLE
Support for external dependencies in bitbucket

### PR DESCRIPTION
**Pull request by caguero**
This PR is the first one of a set for integrating an RNDF importer. It provides some infrastructure to download external dependencies from bitbucket. In particular, I added [Ignition Math](https://bitbucket.org/ignitionrobotics/ign-math) as a new dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5659)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot add to whitelist

**Comment by jwnimmer-tri** [comment]
:lgtm: feature and one platform pass.

+(status: do not merge) until we test on OSX.  I will help do that once review edits are done.

+@soonho-tri for second platform review.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/rndf/BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVCex4BMCWgj38zpOG:-KgVCex4BMCWgj38zpOH:bxvo333) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/drake/automotive/maliput/rndf/BUILD#L5)):*
> ```Python
> 
> load("//tools:cpplint.bzl", "cpplint")
> load("//tools:drake.bzl", "drake_cc_binary", "drake_cc_googletest", "drake_cc_library")
> ```

BTW Please wrap to 80 columns (find an example in related subdirs).

---

*[drake/automotive/maliput/rndf/BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVCtVhO4Q3H1eshNbb:-KgVCtVhO4Q3H1eshNbc:b-9nwjoy) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/drake/automotive/maliput/rndf/BUILD#L13)):*
> ```Python
> drake_cc_googletest(
>     name = "ignition_math_test",
>     size = "small",
> ```

FYI `"small"` is default, so you may omit this.

---

*[tools/bitbucket.bzl, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVI8Cx1qPVEr8rMIhE:-KgVI8Cx1qPVEr8rMIhF:blq6ubm) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/tools/bitbucket.bzl#L9)):*
> ```Python
>         sha256 = None,
>         build_file = None,
>         strip_prefix = None,
> ```

Please add doc for this param to the docstring below.

---

*[tools/ignition_math.BUILD, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVFnfrjMYX9xwbLAA4:-KgVFnfrjMYX9xwbLAA5:b-jlddto) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/tools/ignition_math.BUILD#L10)):*
> ```
>     ),
>     hdrs = glob([
>         "include/**/**/*.hh",
> ```

FYI I think `**` matches any number of directories, so `**/**` is redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-:-KgVKX2Q0F_kyDaHfrhu:b-rslup4)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/bitbucket.bzl, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVh3470uxZVucd3A2M:-KgVh3470uxZVucd3A2N:b-v2gdwd) ([raw file](https://github.com/robotlocomotion/drake/blob/064f4147a26e469ef2ebda141420872c9d83bc5c/tools/bitbucket.bzl#L58)):*
> ```Python
>             **kwargs)
>     else:
>         native.new_http_archive(
> ```

non-blocking question: is it possible to use `native.new_http_archive` for both cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-:-KgVhIFFcVcD5slu5VE5:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[tools/bitbucket.bzl, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVh3470uxZVucd3A2M:-KgVxsuTK3Kq4lGjPf6z:b-h2ceyb) ([raw file](https://github.com/robotlocomotion/drake/blob/064f4147a26e469ef2ebda141420872c9d83bc5c/tools/bitbucket.bzl#L58)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

non-blocking question: is it possible to use `native.new_http_archive` for both cases?
</blockquote></details>

No.

_"Either build_file or build_file_content must be specified."_ -- https://bazel.build/versions/master/docs/be/workspace.html#new_http_archive.  In the prior if-case, we have no BUILD file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/bitbucket.bzl, line 58 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVh3470uxZVucd3A2M:-KgVz-a4dtEBNyx9tPWd:b-qmuiya) ([raw file](https://github.com/robotlocomotion/drake/blob/064f4147a26e469ef2ebda141420872c9d83bc5c/tools/bitbucket.bzl#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No.

_"Either build_file or build_file_content must be specified."_ -- https://bazel.build/versions/master/docs/be/workspace.html#new_http_archive.  In the prior if-case, we have no BUILD file.
</blockquote></details>

I see. Thank you @jwnimmer-tri!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659)*

**Comment by caguero** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/rndf/BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVCex4BMCWgj38zpOG:-KgVcrjEQbTGbdgGhGcD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/drake/automotive/maliput/rndf/BUILD#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Please wrap to 80 columns (find an example in related subdirs).
</blockquote></details>

Done.

---

*[drake/automotive/maliput/rndf/BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVCtVhO4Q3H1eshNbb:-KgVcscs83Wfs5Hl_C9-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/drake/automotive/maliput/rndf/BUILD#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `"small"` is default, so you may omit this.
</blockquote></details>

Done.

---

*[tools/bitbucket.bzl, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVI8Cx1qPVEr8rMIhE:-KgVctUC7e45_vygCswr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/tools/bitbucket.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add doc for this param to the docstring below.
</blockquote></details>

Done.

---

*[tools/ignition_math.BUILD, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-KgVFnfrjMYX9xwbLAA4:-KgVcuTialUdH2rBdQEt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e74beca57bc876286d3f8b78e4f41f1e6d4512ad/tools/ignition_math.BUILD#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think `**` matches any number of directories, so `**/**` is redundant.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-:-KgW6iEIOlw7SPgj1n9a:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

The mac build will take around four hours, if I recall correctly.  If it passes, we can remove both labels and then push the "Squash And Merge" button.

**Comment by soonho-tri** [comment]
> then push the "Squash And Merge" button.

@caguero , please do so.

**Comment by caguero** [comment]
I don't have write access.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5659#-:-KgWofiFL8dMHT-t5m4Y:bbkbb0d)*

**Comment by david-german-tri** [comment]
@caguero, several months ago I sent you an invite to join the RobotLocomotion org.  It looks like you never accepted.  If you find that in your email and accept it, it will grant write access, and silence the Jenkins bot spam.

**Comment by caguero** [comment]
Thanks @david-german-tri . Done.

**Pull request merged**
