### PR TITLE
Iiwa14 acceleration limits

### PR DESCRIPTION
**Pull request by marcoag**
Addresses the second task of https://github.com/RobotLocomotion/drake/issues/15613.

Provides an estimation of acceleration joint limits for the KUKA IWA14 models. Includes unit tests consistency checks and `README.md` updates.

Acceleration joint limit estimations have been derived from experimental results listed in Table 4 (page 50) of the following Master's thesis:

https://odr.chalmers.se/bitstream/20.500.12380/256658/1/256658.pdf

@EricCousineau-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review

FYI @calderpg-tri @sammy-tri 

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377#-:-MtOvCgx-QTuNssjlA4h:b4n118z)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16377#-MtOsqKe7MCpps0N-GfD:-MtOsqKf4sX9gGbr2svT:bahwyiy) (no related file):*
Working: Needs testing on Anzu.

---
___
*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16377#-MtOuhoRBtMo3SMcL8of:-MtOuhoRBtMo3SMcL8og:b3grdmb) ([raw file](https://github.com/robotlocomotion/drake/blob/d92946d8172facb0d5a01252d9a903fdb1f689ca/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L80)):*
> ```
>           <effort>320</effort>
>           <velocity>1.4835298641951802</velocity>
>           <drake:acceleration>8.57</drake:acceleration>
> ```

nit Significant figures here are inconsistent w/ other limits, and is a bit confusing.

Could you either convert degrees to radians and use full precision or mention in README that acceleration limits are taken according rounded acceleration?

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot ok to test

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: pending nit

+@sherm1 for platform review on Tuesday, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377#-:-MtP587Q8AuPtK_t_-M8:b-5lbbr3)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @marcoag and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16377#-MtOsqKe7MCpps0N-GfD:-MtP4xND0bzfd-gBLvPw:b-kk9sk0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Needs testing on Anzu.
</blockquote></details>

Done (Anzu PR 8273).

---

**Comment by jwnimmer-tri** [comment]
For release notes here, is this "breaking change" or just the plain "yes"?

**Comment by EricCousineau-TRI** [comment]
Most conservative to say "breaking change: yes" - thanks for the reminder!

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sherm1)

___
*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16377#-MtOuhoRBtMo3SMcL8of:-MtgghDD9un55R3rcXJm:b-9z5m3e) ([raw file](https://github.com/robotlocomotion/drake/blob/d92946d8172facb0d5a01252d9a903fdb1f689ca/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L80)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Significant figures here are inconsistent w/ other limits, and is a bit confusing.

Could you either convert degrees to radians and use full precision or mention in README that acceleration limits are taken according rounded acceleration?
</blockquote></details>

Just mentioned the rounding on the README in https://github.com/RobotLocomotion/drake/pull/16377/commits/6074e0b7c83be5f8f13850641f337afdc3aeb16e. Let me know if you still think it would be beneficial to add more precision to the rounded values.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag and @sherm1)

___
*[manipulation/models/iiwa_description/README.md, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16377#-Mtiu-DUE9lSlLVyw8Vb:-Mtiu-DVEuxxItj9v2g8:bthk8kv) ([raw file](https://github.com/robotlocomotion/drake/blob/6074e0b7c83be5f8f13850641f337afdc3aeb16e/manipulation/models/iiwa_description/README.md#L67)):*
> ```Markdown
> on 2022-01-15)
> 
> The average acceleration limits are used, and rounded to second decimal
> ```

nit Should qualify that these are "rounded to second decimal place *for radians*".
___
*[manipulation/models/iiwa_description/README.md, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16377#-Mtiu4kF49HoPbOYe6wX:-Mtiu4kF49HoPbOYe6wY:btsu0jt) ([raw file](https://github.com/robotlocomotion/drake/blob/6074e0b7c83be5f8f13850641f337afdc3aeb16e/manipulation/models/iiwa_description/README.md#L70)):*
> ```Markdown
> place.
> 
> For the record, te rounded average acceleration limits:
> ```

nit Spelling "te => the"
___
*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16377#-MtOuhoRBtMo3SMcL8of:-MtituW-BoA0fPiX2qSs:b-jxromg) ([raw file](https://github.com/robotlocomotion/drake/blob/d92946d8172facb0d5a01252d9a903fdb1f689ca/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L80)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Just mentioned the rounding on the README in https://github.com/RobotLocomotion/drake/pull/16377/commits/6074e0b7c83be5f8f13850641f337afdc3aeb16e. Let me know if you still think it would be beneficial to add more precision to the rounded values.
</blockquote></details>

OK Better! Will comment more in place.

**Review by marcoag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sherm1)

___
*[manipulation/models/iiwa_description/README.md, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16377#-Mtiu-DUE9lSlLVyw8Vb:-MtjBYb_C_O2GScIwjtc:b1hcdw) ([raw file](https://github.com/robotlocomotion/drake/blob/6074e0b7c83be5f8f13850641f337afdc3aeb16e/manipulation/models/iiwa_description/README.md#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should qualify that these are "rounded to second decimal place *for radians*".
</blockquote></details>

Addressed in https://github.com/RobotLocomotion/drake/pull/16377/commits/635b07298d4167ba16c1031dfff8017f3447ba4d.
___
*[manipulation/models/iiwa_description/README.md, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16377#-Mtiu4kF49HoPbOYe6wX:-MtjBscH2mEfQ2Wtk15p:b4fclxh) ([raw file](https://github.com/robotlocomotion/drake/blob/6074e0b7c83be5f8f13850641f337afdc3aeb16e/manipulation/models/iiwa_description/README.md#L70)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Spelling "te => the"
</blockquote></details>

Thanks for the catch, fixed in https://github.com/RobotLocomotion/drake/pull/16377/commits/635b07298d4167ba16c1031dfff8017f3447ba4d.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377#-:-MtkTWP5Ey1-5g0jp6J5:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @marcoag)

**Review by sherm1 — COMMENTED** [review]
(Platform)
+(status: squashing now)  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16377#-:-MtkTf-Y-_YpW4D51wdL:b-qst1k4)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform) (waiting on @marcoag)

**Pull request merged**
