### PR TITLE
Added introductory tutorial for AutoDiff.

### PR DESCRIPTION
**Pull request by edrumwri**
Since Drake relies so heavily upon AutoDiff, some documentation for this unsupported library is necessary. This documentation attempts to provide an introductory-level tutorial for AutoDiff and covers computing first and second-derivatives and computing gradient vectors.

Addresses issue #4971.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5254)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review (per request) and +@david-german-tri for platform review (per regular rotation please)

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5254#-:-KdYSzr6N_cD9ZQpwgNM:b-muqusp)*

**Comment by RussTedrake** [comment]
@edrumwri -- documentation is of course great, but i think this is actually NOT the recommended usage in drake.  we have wrappers that simplify the use, and are going to be required as we shift to chunking-based autodiff, which is already on the roadmap #2619.

**Comment by edrumwri** [comment]
I was trying to impart some basic understanding rather than a comprehensive
guide to AutoDiff. Happy to modify or remove this documentation PR if it's
subpar or too elementary or if AutoDiff can be made sufficiently friendly
through wrappers.


--------------------------------
Evan Drumwright
Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Comment by edrumwri** [comment]
Closing this PR following @RussTedrake's feedback.

**Comment by david-german-tri** [comment]
FWIW, I think this is very useful.  Even if it's not recommended Drake usage in the long term, it will help maintainers understand how the Drake wrappers work.  My bigger concern is managing a new documentation technology.  

I guess it's a moot point since @edrumwri has closed, though.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/autodiff_intro/autodiff.tex, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5254#-KdaWeWEhPTrxEs1pA62:-KdaWeWFzH8QttJ1Z2r3:b8kzgae) ([raw file](https://github.com/robotlocomotion/drake/blob/bbc944fec87f7dac13169c65c961db29906435fb/drake/doc/autodiff_intro/autodiff.tex#L153)):*
> ```TeX
> \begin{description}
>  \item [\textbf{Line 7} ]\quad This statement may be necessary for your compiler to distinguish between the AutoDiff'd \texttt{sin} function and the C++ standard library version.
>  \item [\textbf{Line 14} ]\quad This sets the value of the independent variable, $x$, \emph{at the point at which the derivative is to be evaluated}.
> ```

I think your line numbers are off-by-one.  14 should be 13, and 15 should be 14.

---

*[drake/doc/autodiff_intro/autodiff.tex, line 154 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5254#-KdaXRoZvAkH27CimfRb:-KdaXRoZvAkH27CimfRc:b-217ga1) ([raw file](https://github.com/robotlocomotion/drake/blob/bbc944fec87f7dac13169c65c961db29906435fb/drake/doc/autodiff_intro/autodiff.tex#L154)):*
> ```TeX
>  \item [\textbf{Line 7} ]\quad This statement may be necessary for your compiler to distinguish between the AutoDiff'd \texttt{sin} function and the C++ standard library version.
>  \item [\textbf{Line 14} ]\quad This sets the value of the independent variable, $x$, \emph{at the point at which the derivative is to be evaluated}.
>  \item [\textbf{Line 15}\ ]\quad This line is necessary to obtain the derivative of \texttt{sin} with respect to \texttt{x} on return from \texttt{sin\_T}. I'll discuss below why it needs to be set to this seemingly arbitrary value.
> ```

The subsequent explanation is great, but I think it would also be worth saying here that it's the initial value for the partial, i.e. ∂/dx (x).

---

*[drake/doc/autodiff_intro/autodiff.tex, line 360 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5254#-Kda_UzVl8Wlx-iDzqUg:-Kda_UzWoIV0fBPqi88V:bo2he6w) ([raw file](https://github.com/robotlocomotion/drake/blob/bbc944fec87f7dac13169c65c961db29906435fb/drake/doc/autodiff_intro/autodiff.tex#L360)):*
> ```TeX
> \end{tabular}
> \end{center}
> \textbf{Note that the zero input setting for \texttt{a.derivatives()(0).derivatives()} is not a misprint}. We now consider \texttt{b} and \texttt{f(b)}:
> ```

Because ∂^2 / dx^2 (x) = ∂/dx (1) = 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5254#-:-KdaaFZz-ixZCjLWc_9u:b-biy1v)*

**Comment by edrumwri** [comment]
Thanks for your feedback, David- I'll incorporate it into the document and
keep it around internally for those that care.


--------------------------------
Evan Drumwright
Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Comment by jwnimmer-tri** [comment]
While I don't necessarily think PR #4959 needed an extra side document explaining AutoDiff as issue #4971 claims as motivation (though maybe it did), I do think that by the time we're gotten to the AutoDiff use seen in PR #5133, extra side documentation would very likely be helpful.  I haven't read this PR draft to know if it meets that need, but it is probably worth a step back to see where the difficulties or confusions come from and how to tidy that up, be it through better docs and/or API changes or wrappers and/or etc.

**Pull request closed without merging**
