### PR TITLE
Move deprecated math/cylindrical to matlab/util

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3937)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3937#-:-KV84yWiUi7mfa-2e7SQ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai just did feature, thanks!
+@ggould-tri for platform, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3937#-:-KV85RV7rWPfxPwipF8g:b-cv06ey)*

**Comment by ggould-tri** [comment]
I am surprised not to see `cylindrical.h` in the CMakeList.  Is it not needed there?

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3937#-:-KVAjmhDT1Fxr7THCzgs:bqyvxd)*

**Comment by jwnimmer-tri** [comment]
Its only needed if drake-as-a-library users need the header; since its a private component only used by mex modules, drake-as-a-library doesn't need it.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3937#-:-KVAlnAJTGexb2Opi3jR:bv14dfz)*

**Comment by ggould-tri** [comment]
That makes sense.  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3937#-:-KVAmIihXRvVrXDE1TCU:ba1847v)*

**Comment by jwnimmer-tri** [comment]
(Technically, Visual Studio also wants it listed as "source file", but meh.)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3937#-:-KVAmTPSIpZmLrqyf4hg:b-jy3j4s)*

**Pull request merged**
