### PR TITLE
parsing: Remove implicit frames created for nested models

### PR DESCRIPTION
**Pull request by azeey**
This removes additional implicit model frames created for nested models that were missed in #15099.

/cc @EricCousineau-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15208)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot retest this please

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15208#-:-MckYWHr5mUus6jLJpZw:b7kye1q)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Sorry for delay, and looks good! Though needs downstream testing.

As this is a small change, I'm fine with serving as platform as well if there are no downstream issues.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15208#-:-McpVF7HCnHRSOEbake2:bgst6pz)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15208#-McpV8x6EIe5HO4KVdOU:-McpV8x6EIe5HO4KVdOV:b-quicz5) (no related file):*
Working: Testing on Anzu CI.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
:lgtm: x 2 given that we have not broken Anzu CI - thanks!!!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15208#-:-Mcpby668yXmstopqtSw:bo13wi9)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15208#-McpV8x6EIe5HO4KVdOU:-McpbugtEywYvkbWBDjj:b-r9wepx) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Testing on Anzu CI.
</blockquote></details>

Done. Anzu CI just passed; PR 7180, job 1. Sweet!

---

**Comment by EricCousineau-TRI** [comment]
CI failure seems like a flake: https://drake-jenkins.csail.mit.edu/job/linux-bionic-gcc-bazel-experimental-release/9964/consoleFull
```
[5:00:38 PM]  INFO: From Testing //manipulation/util:py/show_model_test:
...
[5:00:38 PM]  FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.cache/matplotlib/fontList.json'
...
[5:00:38 PM]  OSError: [Errno 30] Read-only file system: '/home/ubuntu/.cache/matplotlib/fontList.json'
```

Retesting:
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Yup, just a flake: https://drake-jenkins.csail.mit.edu/job/linux-bionic-gcc-bazel-experimental-release/9965/console

**Pull request merged**
