### PR TITLE
doxygen: add @ingroup tags to schunk wsg systems

### PR DESCRIPTION
**Pull request by RussTedrake**
This at least makes sure that all of our schunk wsg variants appear in the same places in doxygen.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14412)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14412#-:-MNq6icmDWkcdcFLgSBe:b-3q8wn7)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2
One suggestion: the heading for the manipulation_systems group reads "Systems implementations that specifically support dexterous manipulation capabilities in robotics." Consider modifying that to "Systems implementation and related functions ..." since you are now including free functions in the list.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14412#-:-MNvZoht7Mnos6MEMr0W:bh1mgzo)* status: needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14412#-:-MNv_KhY-z28XhE6Lk5w:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Review by RussTedrake — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14412#-:-MPoMWy0966Sdxl7b4ek:b-896fix)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14412)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @RussTedrake)

**Pull request merged**
