### PR TITLE
Eigen alignment test

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR is just a test of an alignment issue when using `AutoDiffScalar` on Windows. 

Discussion opened in Eigen's forum [here](https://forum.kde.org/viewtopic.php?f=74&t=135413).
Consider opening a bug issue on Eigen's [bug tracker](http://eigen.tuxfamily.org/bz/).

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3145)

### CODE REVIEW

**Comment by tkoolen** [comment]
I ran into similar issues a couple of months ago and reported them to the Eigen maintainers. See http://eigen.tuxfamily.org/bz/show_bug.cgi?id=96. The problem occurs when the scalar type of an Eigen matrix is itself fixed-size vectorizable (so not `a` itself in your example, but the scalar type of `a`). What happens is that the constructor of `UnaryOp` is passed a `typename XprType::Scalar` *by value* instead of by reference. Passing stuff that needs to be aligned by value results in the error you got on MSVC 32 bit.

**Comment by amcastro-tri** [comment]
I will go ahead and report this as a bug in Eigen. Unless you know of a solution @tkoolen?

**Comment by tkoolen** [comment]
No, go ahead. Actually, wait just 10 minutes so I can make sure that what I just said is completely correct.

**Comment by amcastro-tri** [comment]
Great, thank you.

**Comment by tkoolen** [comment]
See updated comment above.

**Comment by amcastro-tri** [comment]
Thank you @tkoolen. I just filed a bug here: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1279

**Comment by tkoolen** [comment]
Taking a closer look, it's actually exactly the same bug as I reported, and should be fixed by https://bitbucket.org/eigen/eigen/commits/f2e6b911501d/. Sorry I didn't notice that before. You can close the Eigen issue.

Simply updating https://github.com/RobotLocomotion/eigen-pod to Eigen 3.3 beta 2 should do the trick. I think that should also allow us to get rid of the `GeneralBlockPanelKernel.h` patch.

**Comment by amcastro-tri** [comment]
Thank you @tkoolen!. I created #3211 with your suggestion.

**Comment by amcastro-tri** [comment]
The last [test failing on Windows is here](https://drake-jenkins.csail.mit.edu/job/experimental/3657/).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Thank you for your interest in contributing to Drake!  This PR has seen no updates in over one month, so I am going to close it.  Please feel free to re-open (or open a fresh PR) if there are new updates to consider.

**Pull request closed without merging**
