### PR TITLE
Fix python urdf parser

### PR DESCRIPTION
**Pull request by patmarion**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4420)

### CODE REVIEW

**Comment by patmarion** [comment]
+@liangfok for feature review, please.

**Comment by patmarion** [comment]
@liangfok your recent change to remove parser methods from RigidBodyTree broke Director's python IK which used those methods.  This PR adds wrapping for the urdf parser so that Director can work again.

Since director tests are still not enabled on drake-ci, I'm afraid that breaks like this are unavoidable for now.

**Comment by patmarion** [comment]
fyi @rdeits in case you're interested.

**Comment by liangfok** [comment]
Looks like this PR has some compilation errors:

```
17:53:00 /home/ubuntu/workspace/linux-clang-experimental-debug/drake/multibody/parser_urdf.cc:1145:21: error: use of class template 'RigidBodyFrame' requires template arguments
17:53:00     std::shared_ptr<RigidBodyFrame> weld_to_frame,
```

The above is due to #4406.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-KYQVRkM4-uB5JnGuRj1:-KYQVRkM8dV-EsaYRKWI:b83ntpa) ([raw file](https://github.com/robotlocomotion/drake/blob/c71a520b3120c267e028b5a7f37f12801f6e37c0/drake/bindings/python/pydrake/test/testPR2IK.py#L9)):*
> ```Python
>     """
>     This function demonstrates how to pass a complete
>     set of arguments to the drake urdf parser.  It is
> ```

BTW: nit: Consider replacing "the drake URDF" with "Drake's URDF".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-:-KYQWEDg0f8pMhXIVsDV:bcmt60b)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri I will be happy to platform review once the builds are passing.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-:-KYQeUDv9TtYXETDoVyt:ba5o44d)*

**Comment by patmarion** [comment]
thanks!  I rebased and fixed the compile error, will see how it goes.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parser_urdf.cc, line 1151 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-KYQogdARpXfY4a0_9Kq:-KYQogdARpXfY4a0_9Kr:b-jy426r) ([raw file](https://github.com/robotlocomotion/drake/blob/209de7f2a05667716a4e01da1d605d129c420eb9/drake/multibody/parser_urdf.cc#L1151)):*
> ```cpp
>       urdf_string, ros_package_map, root_dir, floating_base_type,
>       weld_to_frame, tree);
> }
> ```

FYI Embarrassing that we missed this in earlier PRs (and no test coverage).  But I guess it's deprecated and will go away eventually, so no need to add tests now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-:-KYQorocdLgUMZ6RjTkE:b593vm9)*

**Comment by jwnimmer-tri** [comment]
Just waiting for @liangfok for LGTM.  Then please use the squash-and-merge button when merging.

**Comment by patmarion** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-KYQVRkM4-uB5JnGuRj1:-KYQtP_A-g4yfA-qfWYL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c71a520b3120c267e028b5a7f37f12801f6e37c0/drake/bindings/python/pydrake/test/testPR2IK.py#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: Consider replacing "the drake URDF" with "Drake's URDF".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4420)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4420#-:-KYQwMCMCChzNI9hOYfr:bnfp4nl)*

**Pull request merged**
