### PR TITLE
Add accelerometer sensor

### PR DESCRIPTION
**Pull request by mposa**
Adds an accelerometer sensor and unit test. 

Still needs a second unit test where the accelerometer is rotated w.r.t. the world.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13501)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Yes; the h and cc filename will have to change.  We can't use the current `systems/sensors/accelerometer` name until after Sept 1st when the attic gets removed.  We can rename it back to this name after that point, if we wish.

**Comment by jwnimmer-tri** [comment]
Yes, the timeline for renaming the attic out of the way would be longer than the 9/1 removal date anyway.  So just choose a different name for the MbP flavor in this PR.

**Comment by jwnimmer-tri** [comment]
Another option: `class Accelerometer` in file `drake/systems/sensors/accelerometer2.h`.  Then later we just deprecate and rename the include statement, leaving the rest of the C++ code (and all of pydrake) unchanged.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
___
*[systems/sensors/accelerometer.cc, line 3 at r5](https://reviewable.io/reviews/robotlocomotion/drake/13501#-MAbxNSl0vLS_BL-qy_h:-MAc-mkdAM5DR35CxwXV:b-22b6bb) ([raw file](https://github.com/robotlocomotion/drake/blob/ea5be64142f4e93bc729b3d1b0d3074afc31b50a/systems/sensors/accelerometer.cc#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: I think the include being implemented should come first according to https://drake.mit.edu/styleguide/cppguide.html#Names_and_Order_of_Includes   (or does the linter get annoyed when you do that because of the name mismatch?)
</blockquote></details>

For how to tame the linter, one example to copy would be:
https://github.com/RobotLocomotion/drake/blob/4bd63e3ee53252414b6b0aab15cc6a1711748839/solvers/mosek_solver_common.cc#L1-L3

**Pull request merged**
