### PR TITLE
Python bindings for MathematicalProgram

### LINKED ISSUE #4771: Python bindings for MathematicalProgram
I was investigating today what it would take to make `MathematicalProgram` usable from Python/Matlab. So far, I haven't been able to wrap `decision_variable.h` because of its use of alias-`using` directives (like `template <int rows>
using VectorDecisionVariable = MatrixDecisionVariable<rows, 1>;`). 

Mainline SWIG added support for these directives in 3.0.11, which came out in December 2016, but the SWIG + matlab fork we're using doesn't have those changes. 

It might be possible to pull in the changes from mainline SWIG and get this working. 

Of course, this is all moot if the SWIG code is going to be thrown away soon. What's the status of that?

### PR DESCRIPTION
**Pull request by rdeits**
~~This is waiting on #4949 which is blocked by the clang issues on CI. This PR includes the changes from that branch as well, so it will have to wait until #4949 is merged. However, given that I'm attempting to use it in my work, I thought it would be good to get the PR rolling.~~

This introduces python bindings for MathematicalProgram, including use of the symbolic Variable, Expression, and Formula classes. Currently, only linear constraints and linear & quadratic objectives are supported, but more features can be added easily. 

Resolves #4771

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5023)

### CODE REVIEW

**Comment by rdeits** [comment]
@hongkai-dai here are some of the cool things we can do now: https://github.com/RobotLocomotion/drake/pull/5023/files#diff-001fa3c1b2193bfe8f6eef95640bc5d6

**Comment by hongkai-dai** [comment]
This is fantastic! It is great that Python binding works, and now you can use `MathematicalProgram` for your problem in Python.

**Comment by rdeits** [comment]
+@hongkai-dai for feature review, please 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KcsQjEV6sw42cl7lujH:b-81zjvj)*

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by hongkai-dai** [comment]
Reviewed 5 of 10 files at r2.
Review status: 4 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_gurobi.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcskHHXsyMsGdyU1yKD:-KcskHH_29uqZUd7U9AH:b4ezqf) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_gurobi.cc#L16)):*
> ```cpp
>     .def(py::init<>())
>     .def("available", &GurobiSolver::available)
>     .def("SolverName", &GurobiSolver::SolverName)
> ```

Do you want to support `solver_type`? Does pybind support the enum class in C++?

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslDjS7G5CcMH0HZlk:-KcslDjS7G5CcMH0HZll:b-3940o0) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L24)):*
> ```cpp
>   using drake::solvers::MathematicalProgram;
>   using drake::solvers::Constraint;
>   using drake::solvers::LinearConstraint;
> ```

How about LinearEqualityConstraint and BoundingBoxConstraint?

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslaH9u7RulgTd7e4A:-KcslaH9u7RulgTd7e4B:b-hjzb30) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L26)):*
> ```cpp
>   using drake::solvers::LinearConstraint;
>   using drake::solvers::QuadraticConstraint;
>   using drake::solvers::QuadraticConstraint;
> ```

duplicate QuadraticConstraint?

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 129 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslmKH41Q14IXbMqjJ:-KcslmKH41Q14IXbMqjK:b96kqta) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L129)):*
> ```cpp
>          &MathematicalProgram::SetSolverOption)
>     .def("SetSolverOption", (void(MathematicalProgram::*)(
>          const std::string&, const std::string&, const std::string&))
> ```

I think I changed the first `std::string` to `SolverType` in https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/mathematical_program.h#L1956

---

*[drake/bindings/python/pydrake/test/testGurobiSolver.py, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcsma4ztRSMvvTkTUZe:-Kcsma5-Lu45cAiiUww3:b-64ukww) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/python/pydrake/test/testGurobiSolver.py#L18)):*
> ```Python
>         solver = GurobiSolver()
>         self.assertTrue(solver.available())
>         self.assertEqual(solver.SolverName(), "Gurobi")
> ```

It is more robust to use solver.solver_type()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by hongkai-dai** [comment]
@soonho-tri , I think you will be interested to see that the symbolic computation is also supported in Python!

---

Review status: 4 of 9 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KcsnMq85h_M9rf-P7n2:blp6exz)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcsoGT21iHpH1CxMdwV:-KcsoGT21iHpH1CxMdwW:b4p0mhu) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L139)):*
> ```cpp
>     .value("kUnknownError", SolutionResult::kUnknownError);
> 
>   py::class_<Variable>(m, "Variable")
> ```

I think it is more clear, if we move the pybind of `Variable`, `Expression`, `Formula` to a separate file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by soonho-tri** [comment]
@rdeits , @hongkai-dai , nice!!

---

Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KcsrXuB4vVZsdYMK8s0:b-l6ds9x)*

**Comment by rdeits** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_gurobi.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcskHHXsyMsGdyU1yKD:-Kcstj1PP6_R1_ZJIg0g:bmvr22n) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_gurobi.cc#L16)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you want to support `solver_type`? Does pybind support the enum class in C++?
</blockquote></details>

Yeah, definitely. I'll add that. 

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslDjS7G5CcMH0HZlk:-KctKpSmElXMtqAqhExA:b5tq0hl) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L24)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

How about LinearEqualityConstraint and BoundingBoxConstraint?
</blockquote></details>

I haven't added those yet because I wasn't sure what the right symbolic interface would be. Do we want a user to be able to do:

```
prog.AddLinearConstraint(x + y == 5)
```
?

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslaH9u7RulgTd7e4A:-KctDS5Cj0-EBsUokNhe:bk8932j) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L26)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

duplicate QuadraticConstraint?
</blockquote></details>

Oops, thanks. Done. 

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 129 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslmKH41Q14IXbMqjJ:-KctD_cxUw3BkWeY_j1W:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think I changed the first `std::string` to `SolverType` in https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/mathematical_program.h#L1956
</blockquote></details>

Done. 

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcsoGT21iHpH1CxMdwV:-KctKyJY9mbZzCucHvEL:b-2gx34q) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L139)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is more clear, if we move the pybind of `Variable`, `Expression`, `Formula` to a separate file.
</blockquote></details>

Good idea. I've created the new `pydrake.symbolic` module and moved the definitions there. 

---

*[drake/bindings/python/pydrake/test/testGurobiSolver.py, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcsma4ztRSMvvTkTUZe:-KctL2TMTrcXMr8eUlh8:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/python/pydrake/test/testGurobiSolver.py#L18)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is more robust to use solver.solver_type()
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by rdeits** [comment]
Review status: 1 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcsoGT21iHpH1CxMdwV:-KctLMzYCUwIE5jZtbJl:b-ggp7xn) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L139)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

Good idea. I've created the new `pydrake.symbolic` module and moved the definitions there. 
</blockquote></details>

See the new `testSymbolic.py` file for some examples of using the symbolic variables outside of MathematicalProgram. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by rdeits** [comment]
This is blocked by the fact that the `FindNumpy.cmake` which pybind11 installs is not actually found by Drake, leading to the python bindings never being built.

**Comment by hongkai-dai** [comment]
Reviewed 1 of 10 files at r2, 3 of 12 files at r3.
Review status: 4 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslDjS7G5CcMH0HZlk:-KctMzbx8m3ff-cB0PLn:b-v547jg) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L24)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

I haven't added those yet because I wasn't sure what the right symbolic interface would be. Do we want a user to be able to do:

```
prog.AddLinearConstraint(x + y == 5)
```
?
</blockquote></details>

I think it is good to allow the user to be able to do 
`prog.AddLinearConstraint(x + y == 5)`

There are two types of symbolic constraint interfaces for bounding box constraint (or linear equality constraint). For a single row of bounding box constraint (or linear equality constraint), you can do
```
prog.AddLinearConstraint(x>= 1)
prog.AddLinearConstraint(x+y == 5)
```
But for multiple rows of constraints, the interface is different. It seems to me the current python interface does not allow the user to do 
```
prog.AddBoundingBoxConstraint(np.array([0, 0]), np.array([1, 2]), np.array([x, y]))
```
For the bounding box constraint on a vector of variables, there is not a symbolic interface. The symbolic interface for linear equality constraint is
```
MathematicalProgram::AddLinearConstraint(expr == eq)
```
for a SINGLE linear equality constraint, and
```
MathematicalProgram::AddLinearEqualityConstraint(exprs, eq)
```
for an `Eigen::Vector` of symbolic linear expressions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by hongkai-dai** [comment]
Reviewed 9 of 12 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by rdeits** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslDjS7G5CcMH0HZlk:-KctPcOjpQctGfgzr_Lf:bn218my) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L24)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is good to allow the user to be able to do 
`prog.AddLinearConstraint(x + y == 5)`

There are two types of symbolic constraint interfaces for bounding box constraint (or linear equality constraint). For a single row of bounding box constraint (or linear equality constraint), you can do
```
prog.AddLinearConstraint(x>= 1)
prog.AddLinearConstraint(x+y == 5)
```
But for multiple rows of constraints, the interface is different. It seems to me the current python interface does not allow the user to do 
```
prog.AddBoundingBoxConstraint(np.array([0, 0]), np.array([1, 2]), np.array([x, y]))
```
For the bounding box constraint on a vector of variables, there is not a symbolic interface. The symbolic interface for linear equality constraint is
```
MathematicalProgram::AddLinearConstraint(expr == eq)
```
for a SINGLE linear equality constraint, and
```
MathematicalProgram::AddLinearEqualityConstraint(exprs, eq)
```
for an `Eigen::Vector` of symbolic linear expressions.
</blockquote></details>

Ah, I see. Is it OK if we leave this for future work? I'd like to try to figure out what the nicest way to handle vectors of constraints in python first. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by rdeits** [comment]
Blocked waiting for https://github.com/RobotLocomotion/drake/pull/5158

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-KcslDjS7G5CcMH0HZlk:-KcttznpSm7m-EXA7yF6:b-jrt1rz) ([raw file](https://github.com/robotlocomotion/drake/blob/739cb897c91ba4697bf70b58fa3a0095fc787762/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L24)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

Ah, I see. Is it OK if we leave this for future work? I'd like to try to figure out what the nicest way to handle vectors of constraints in python first. 
</blockquote></details>

Sounds good to me. I should also think about how to add a vector of formulas in the C++ interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KctuD3JnTXurEMHPESF:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KctvVgcuN_nhIUWgmB6:bfvx2sg)*

**Comment by sherm1** [comment]
Platform: :lgtm: with a few minor BTWs. In several places I suggested moving the drake headers to the top of the file, before the pybind11 ones. I *think* that is more in keeping with Google's advice [here](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) but it doesn't apply exactly so I leave it to Robin's discretion.

---

Reviewed 2 of 10 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_gurobi.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu3MPacjHn7F4N05Fv:-Kcu3MPacjHn7F4N05Fw:b-mwk38b) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_gurobi.cc#L4)):*
> ```cpp
> 
> 
> #include "drake/solvers/gurobi_solver.h"
> ```

BTW, consider putting this header first.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu2xubsyD2-QZ7oD2f:-Kcu2xubsyD2-QZ7oD2g:b-bizax1) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L6)):*
> ```cpp
> 
> #include "drake/bindings/pybind11/pydrake_symbolic_types.h"
> #include "drake/solvers/mathematical_program.h"
> ```

BTW, these two headers should come first to make sure they are independent of any pybind11 goodies.

---

*[drake/bindings/pybind11/pydrake_mosek.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu2NQ3heN9-dNg1xtQ:-Kcu2NQ3heN9-dNg1xtR:byr75cc) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_mosek.cc#L4)):*
> ```cpp
> 
> 
> #include "drake/solvers/mosek_solver.h"
> ```

BTW, this header should probably come first, followed by the pybind11 ones.

---

*[drake/bindings/pybind11/pydrake_symbolic.cc, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu1yHELdZFl5OJ9-iM:-Kcu1yHELdZFl5OJ9-iN:b-tfrib2) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_symbolic.cc#L5)):*
> ```cpp
> #include <pybind11/operators.h>
> 
> #include "drake/bindings/pybind11/pydrake_symbolic_types.h"
> ```

BTW, per style guide this most-relevant header should come first, then a blank line, then the pybind11 headers in alphabetical order.

---

*[drake/bindings/python/pydrake/test/testGurobiSolver.py, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu1-sRR45-Ba-36cBF:-Kcu1-sRR45-Ba-36cBG:bl3ia63) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/python/pydrake/test/testGurobiSolver.py#L26)):*
> ```Python
> 
> if __name__ == '__main__':
>     unittest.main()
> ```

BTW, needs final newline.

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.py, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu16kOzF1gosnxzZ0V:-Kcu16kOzF1gosnxzZ0W:b-uptv2o) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/python/pydrake/test/testMathematicalProgram.py#L60)):*
> ```Python
>             print("constraint", constraint)
>             print("variables", binding.variables())
>             self.assertTrue((prog.FindDecisionVariableIndex(binding.variables()[0]) ==
> ```

BTW, line length.

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.py, line 83 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu1AaDeIB9f0L11n97:-Kcu1AaDeIB9f0L11n98:b-uptv2o) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/python/pydrake/test/testMathematicalProgram.py#L83)):*
> ```Python
>         self.assertTrue(np.allclose(prog.GetSolution(x), x_expected))
>         for constraint in constraints:
>             self.assertTrue(np.isclose(prog.EvalBindingAtSolution(constraint), 1))
> ```

BTW, line length.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-Kcu3VN0gatWJP4RIVtA:b-l37fkk)*

**Comment by rdeits** [comment]
@sherm1 you're probably right about the headers. I was thinking of them as "your project's header" but they're really more "related header". 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_gurobi.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu3MPacjHn7F4N05Fv:-KcuJMLx9k0ebaB_oAJu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_gurobi.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, consider putting this header first.
</blockquote></details>

Done.

---

*[drake/bindings/pybind11/pydrake_mathematicalprogram.cc, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu2xubsyD2-QZ7oD2f:-KcuJYUuRdGDeMnl6Dpg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_mathematicalprogram.cc#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, these two headers should come first to make sure they are independent of any pybind11 goodies.
</blockquote></details>

Done.

---

*[drake/bindings/pybind11/pydrake_mosek.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu2NQ3heN9-dNg1xtQ:-KcuJXhn9LPX24FwBf8o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_mosek.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this header should probably come first, followed by the pybind11 ones.
</blockquote></details>

Done.

---

*[drake/bindings/pybind11/pydrake_symbolic.cc, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu1yHELdZFl5OJ9-iM:-KcuJbMu1HN_UpVFUyob:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/pybind11/pydrake_symbolic.cc#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, per style guide this most-relevant header should come first, then a blank line, then the pybind11 headers in alphabetical order.
</blockquote></details>

Done.

---

*[drake/bindings/python/pydrake/test/testGurobiSolver.py, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu1-sRR45-Ba-36cBF:-KcuJf9u2qyYdElbiFx-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/python/pydrake/test/testGurobiSolver.py#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, needs final newline.
</blockquote></details>

Done.

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.py, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu16kOzF1gosnxzZ0V:-KcuJv3MeYVxG3lt_o19:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/python/pydrake/test/testMathematicalProgram.py#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, line length.
</blockquote></details>

Done.

---

*[drake/bindings/python/pydrake/test/testMathematicalProgram.py, line 83 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-Kcu1AaDeIB9f0L11n97:-KcuJw4-7i_vR3QhuE0U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e06d224f3951b07fb0c5e8ab6da53bbb0eeb938b/drake/bindings/python/pydrake/test/testMathematicalProgram.py#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, line length.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KcuIm-KeUigE08382WT:bk71epc)*

**Comment by sherm1** [comment]
All good -- just needs a squash merge, @rdeits (remove curate commits tag first).

---

Reviewed 1 of 10 files at r2, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5023#-:-KcusJqSgGjauiBxiGGl:bhhvst8)*

**Comment by rdeits** [comment]
(adding "do not merge" because this is still blocked by #5158 )

**Comment by rdeits** [comment]
@drake-jenkins-bot retest this please

**Comment by rdeits** [comment]
Unblocked

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by rdeits** [comment]
This is good to go as soon as the mac-clang-experimental build passes

**Pull request merged**
