### PR TITLE
Time stepping rigid body plant (without constraints)

### PR DESCRIPTION
**Pull request by edrumwri**
Adds time stepping version of rigid body plant (under "dev") *without incorporating constraints*.

Skeleton for functions necessary to incorporate constraints has been put into place.

Time stepping rigid body plant (discrete state) is tested against rigid body plant (continuous state, integrated under the semi-explicit integration scheme) to verify that identical results are returned.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7066)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@siyuanfeng-tri for feature review please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-KuWM3Hn10R9Dgfhz6yA:bgdoi2o)*

**Comment by siyuanfeng-tri** [comment]
checkpoint

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_FMXeB56OQHuDOv7D:-Ku_FMXeB56OQHuDOv7E:b-vlcki8) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L52)):*
> ```cpp
>     double*,
>     double*) const {
>   DRAKE_DEMAND("CalcContactStiffnessAndDamping() not yet implemented.");
> ```

BTW, I actually doesn't know what this does.. DRAKE_DEMAND(string), is this always true? you just want to have some obvious message here? 

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_Dv4_u7ObzUTfqTW3:-Ku_Dv4_u7ObzUTfqTW4:b-a8lqbg) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L129)):*
> ```cpp
>   using std::abs;
> 
>   static_assert(std::is_same<double, T>::value,
> ```

BTW might want to move this to somewhere a bit more obvious, but I am fine with it as is. 

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 217 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_MMqsWc9eNr6H9SR6:-Ku_MMqsWc9eNr6H9SR7:b-u1414s) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L217)):*
> ```cpp
>   for (int i = 0; i < static_cast<int>(contacts.size()); ++i) {
>     double stiffness, damping;
>     CalcContactStiffnessAndDamping(contacts[i], &stiffness, &damping);
> ```

BTW, do you need a todo here? 

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 238 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_MljBLQ0rzDSdRLhO:-Ku_MljBLQ0rzDSdRLhP:b-ao18lz) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L238)):*
> ```cpp
>   vnew += data.v;
> 
>   // qn = q + h*qdot.
> ```

BTW can you change to qdot * dt? 

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_58FVCSP22l8mCjDe:-Ku_58FVCSP22l8mCjDf:bdolilt) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L19)):*
> ```objc
> namespace systems {
> 
> /// This class provides a System interface around a multibody dynamics model
> ```

This part probably needs a bit more documentation..

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_6CxOzi50829dvTJH:-Ku_6CxOzi50829dvTJI:b-bnnts7) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L34)):*
> ```objc
>   /// @param[in] tree the dynamic model to use with this plant.
>   /// @param[in] timestep a strictly positive, floating point value specifying
>   /// the update period of the model (in seconds).
> ```

can you add a @throws when timestep <= 0

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5JecNBvaFSnDXgzq:-Ku_5JecNBvaFSnDXgzr:b-ohc69o) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L39)):*
> ```objc
> 
>   /// The default Coulomb friction coefficient.
>   double mu_{0.1};
> ```

probably should be private?

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_Ea7iRCJzoeKJKewa:-Ku_Ea7iRCJzoeKJKewb:b-gjxzye) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L47)):*
> ```objc
>   /// Sets the CFM parameter. Aborts if negative. Default value is 1e-12.
>   void set_cfm(double cfm) { DRAKE_DEMAND(cfm >= 0); cfm_ = cfm; }
> ```

BTW do you want people to be able to set half_cone_edges_?

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-Ku_5W-H57OP3uYfnSh0:b7qj0kd) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
> ```objc
> 
>  protected:
>   void DoCalcDiscreteVariableUpdates(const Context<T>& context,
> ```

BTW why are these protected? do you foresee other derived classes?

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_GMXdnp0WB8oqr_0U:-Ku_GMXdnp0WB8oqr_0V:b-hoyqkq) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L67)):*
> ```objc
>       const KinematicsCache<T>& kcache, int body_a_index, int body_b_index,
>       const Vector3<T>& p, const Vector3<T>& f, VectorX<T>* gf) const;
>   VectorX<T> N_mult(
> ```

BTW, I haven't really thought this through, would it be faster if you pass in cache instead of q? (I am guessing you might need to compute cache from q again.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-Ku_Mrqu4iN_lsx9JERW:b-vv2shf)*

**Comment by edrumwri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_FMXeB56OQHuDOv7D:-KuapCWRTdTkGhVXA98O:b2cbmeu) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L52)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I actually doesn't know what this does.. DRAKE_DEMAND(string), is this always true? you just want to have some obvious message here? 
</blockquote></details>

Done. (Doh!)

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_Dv4_u7ObzUTfqTW3:-KuapPospNX_n0JYONUU:b-j98h4c) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L129)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW might want to move this to somewhere a bit more obvious, but I am fine with it as is. 
</blockquote></details>

Done. (It's actually replicated code from RigidBodyPlant- why it was in that location...)

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 217 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_MMqsWc9eNr6H9SR6:-KuapfHKVpDMIGU3pIIY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L217)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, do you need a todo here? 
</blockquote></details>

Done.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 238 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_MljBLQ0rzDSdRLhO:-Kuapi5kGUGKoEGAiZ1g:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L238)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW can you change to qdot * dt? 
</blockquote></details>

Done.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_58FVCSP22l8mCjDe:-KuapkKDALp-IYxxmZov:b-twekkp) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L19)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

This part probably needs a bit more documentation..
</blockquote></details>

PTAL- Could we avoid more than I've provided, given that this class is expected to have a limited lifespan and the documentation is nearly identical to RigidBodyPlant?

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_6CxOzi50829dvTJH:-KuaqP82iavMro5XOzUp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L34)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you add a @throws when timestep <= 0
</blockquote></details>

Done.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5JecNBvaFSnDXgzq:-KuaqPgVp7VNvk6l4Jcm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L39)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

probably should be private?
</blockquote></details>

Done.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_Ea7iRCJzoeKJKewa:-KuaqQFr3RmeX8cCYFX7:bqu0lkb) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L47)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW do you want people to be able to set half_cone_edges_?
</blockquote></details>

BTW Probably not, although I've put a TODO in place: given the limitations of time stepping approaches, I don't think a more representative friction cone will buy you much.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-Kuae2VCy7-v_dqOh-U7:b22fdw9) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW why are these protected? do you foresee other derived classes?
</blockquote></details>

They're protected in the super classes and, according to @jwnimmer-tri, trying to promote them to "private" is an anti-pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by siyuanfeng-tri** [comment]
first pass done. 

---

Reviewed 1 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_Ea7iRCJzoeKJKewa:-KuarWDZDuQ0apvcNaMD:b-gicmsf) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L47)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Probably not, although I've put a TODO in place: given the limitations of time stepping approaches, I don't think a more representative friction cone will buy you much.
</blockquote></details>

reasonable, I don't really know anyone how uses > 2 anyway. 

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-Kuardb5SJwK28GzBR2H:b-avqbh4) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

They're protected in the super classes and, according to @jwnimmer-tri, trying to promote them to "private" is an anti-pattern.
</blockquote></details>

hmmmmmmmm. good to know.. I tend to make them private in derived classes.. 

---

*[drake/multibody/dev/test/quadrotor_test.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuapMWWZpgcfxmlvN74:-KuapMWWZpgcfxmlvN75:b-bwbn3s) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/test/quadrotor_test.cc#L4)):*
> ```cpp
> ///
> /// This demo sets up a passive Quadrotor plant in a world described by the
> /// warehouse model. The robot simply rests on the floor within the walls
> ```

BTW i have no idea what's the warehouse model.. 

---

*[drake/multibody/dev/test/quadrotor_test.cc, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuaromZSrOZ8KM5d8ts:-KuaromZSrOZ8KM5d8tt:bfserup) ([raw file](https://github.com/robotlocomotion/drake/blob/62cbf9fdceb15fc0282d0dd2e6da04d472f41edb/drake/multibody/dev/test/quadrotor_test.cc#L49)):*
> ```cpp
> 
>     auto tree = std::make_unique<RigidBodyTree<T>>();
>     ModelInstanceIdTable model_id_table = AddModelInstanceFromUrdfFileToWorld(
> ```

BTW, I am wondering why you picked this particular plant. and you need to make it public in BUILD as well. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-Kuas1rRTdQJehZoMpGT:bi4m18u)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_GMXdnp0WB8oqr_0U:-KuaseMJ1Gh2CRkcT71c:b-tlezbq) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L67)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I haven't really thought this through, would it be faster if you pass in cache instead of q? (I am guessing you might need to compute cache from q again.)
</blockquote></details>

Done. (Rookie mistake!)

---

*[drake/multibody/dev/test/quadrotor_test.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuapMWWZpgcfxmlvN74:-KuauJWCHGumEqvhc2eK:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/test/quadrotor_test.cc#L4)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i have no idea what's the warehouse model.. 
</blockquote></details>

PTAL.

---

*[drake/multibody/dev/test/quadrotor_test.cc, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuaromZSrOZ8KM5d8ts:-KuashyFS9CKn7v5bySg:b-cdbu5g) ([raw file](https://github.com/robotlocomotion/drake/blob/62cbf9fdceb15fc0282d0dd2e6da04d472f41edb/drake/multibody/dev/test/quadrotor_test.cc#L49)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I am wondering why you picked this particular plant. and you need to make it public in BUILD as well. 
</blockquote></details>

BTW I wanted a plant that did more than just a "simple" double pendulum. It should already be public in BUILD via the modifications in PR; is there some indication that I didn't?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by sherm1** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-KuazhzCDY07LOAu33z_:b1aez3v) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

hmmmmmmmm. good to know.. I tend to make them private in derived classes.. 
</blockquote></details>

BTW I agree with @siyuanfeng-tri. Unless you want them callable by your derived classes, they should be private. @jwnimmer-tri, if your position is accurately represented here, why do you think these should be protected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 3 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/dev/test/quadrotor_test.cc, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuaromZSrOZ8KM5d8ts:-Kub06np0t9pZOyNicMT:bkb547o) ([raw file](https://github.com/robotlocomotion/drake/blob/62cbf9fdceb15fc0282d0dd2e6da04d472f41edb/drake/multibody/dev/test/quadrotor_test.cc#L49)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW I wanted a plant that did more than just a "simple" double pendulum. It should already be public in BUILD via the modifications in PR; is there some indication that I didn't?
</blockquote></details>

nah, i was just curious. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-Kub0PVW5p6j3bJFbtg3:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-Kub1X77DVEzudC_-Gg5:b26csbx) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I agree with @siyuanfeng-tri. Unless you want them callable by your derived classes, they should be private. @jwnimmer-tri, if your position is accurately represented here, why do you think these should be protected?
</blockquote></details>

It is a complex discussion.  In this case, since the class is not final, why would you want to prevent subclasses from overriding this method?  If the intent is to prevent overriding, then mark the method (or class) `final`.  Similarly, why would you want to prevent subclasses from conveniently calling this?  (They can always call it via upcasting, so you're not fundamentally preventing them, just making it more annoying.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by edrumwri** [comment]
Thanks Siyuan!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-Kub1xCPpX-ABunF0RFO:bg1znf4)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-Kub7dUFmQERmAAHSxkC:bbtq2vx) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is a complex discussion.  In this case, since the class is not final, why would you want to prevent subclasses from overriding this method?  If the intent is to prevent overriding, then mark the method (or class) `final`.  Similarly, why would you want to prevent subclasses from conveniently calling this?  (They can always call it via upcasting, so you're not fundamentally preventing them, just making it more annoying.)
</blockquote></details>

A private `override` doesn't prevent further overrides; derived classes are always overriding the original virtual function in the base class. `final` is required to prevent overriding. But a private override does (1) indicate that the method should not be called, (2) remove the method from doxygen, and (3) make it so derived classes can't call the method without upcasting to the base. 

So it isn't an ironclad guarantee that the function won't be called, but it does require jumping through a lot of hoops to do so. That seems unequivocally better than putting a method in `protected` when you don't intend for it to be called. For a similar agrument, see Herb Sutter's [Guidelines #2 and 3](http://www.gotw.ca/publications/mill18.htm). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by edrumwri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Ku_5W-H57OP3uYfnSh-:-KueTQYWkougbygLEx4T:bcvtczo) ([raw file](https://github.com/robotlocomotion/drake/blob/7ee8b372d206264d701033d2d9a97a3b2f65efbf/drake/multibody/dev/time_stepping_rigid_body_plant.h#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

A private `override` doesn't prevent further overrides; derived classes are always overriding the original virtual function in the base class. `final` is required to prevent overriding. But a private override does (1) indicate that the method should not be called, (2) remove the method from doxygen, and (3) make it so derived classes can't call the method without upcasting to the base. 

So it isn't an ironclad guarantee that the function won't be called, but it does require jumping through a lot of hoops to do so. That seems unequivocally better than putting a method in `protected` when you don't intend for it to be called. For a similar agrument, see Herb Sutter's [Guidelines #2 and 3](http://www.gotw.ca/publications/mill18.htm). 
</blockquote></details>

Done. (Mark me convinced)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by edrumwri** [comment]
+@sherm1 for platform review please (should only require review of non-dev files).

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-KueTcXf9uh-3qThBwhI:bjbvulm)*

**Comment by sherm1** [comment]
Glanced at the dev stuff -- cool! :lgtm: with some ignorable BTWs.

---

Reviewed 3 of 6 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 164 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuegtHRZCW1HUX8F0ti:-KuegtHRZCW1HUX8F0tj:b1de9hr) ([raw file](https://github.com/robotlocomotion/drake/blob/9b7f02ed205a3bbd2195decce8dcdbf36efa3b80/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L164)):*
> ```cpp
> 
>   // Set the inertia matrix solver.
>   data.solve_inertia = [this, &ldlt](const MatrixX<T>& m) {
> ```

BTW `this` not needed here?

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 99 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Kueg9r0nU6uzNYj9cR8:-Kueg9r0nU6uzNYj9cR9:bjcjhvt) ([raw file](https://github.com/robotlocomotion/drake/blob/9b7f02ed205a3bbd2195decce8dcdbf36efa3b80/drake/multibody/dev/time_stepping_rigid_body_plant.h#L99)):*
> ```objc
>   // Since Lacoursiere's constraint stabilization process assumes that the
>   // constraint function is approximately linear in position, values of ERP
>   // smaller than unity are generally recommended. A generally safe value of 0.1
> ```

BTW says "recommended" here but "invalid" a few lines earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-:-KuehTTbCSJ8Yqlg7b6K:b-pt94rz)*

**Comment by edrumwri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.cc, line 164 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-KuegtHRZCW1HUX8F0ti:-KufDB-nwq1yfkyxF5IB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b7f02ed205a3bbd2195decce8dcdbf36efa3b80/drake/multibody/dev/time_stepping_rigid_body_plant.cc#L164)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `this` not needed here?
</blockquote></details>

Done.

---

*[drake/multibody/dev/time_stepping_rigid_body_plant.h, line 99 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7066#-Kueg9r0nU6uzNYj9cR8:-KufDTsUIC_PYyNIPByc:bqbv41n) ([raw file](https://github.com/robotlocomotion/drake/blob/9b7f02ed205a3bbd2195decce8dcdbf36efa3b80/drake/multibody/dev/time_stepping_rigid_body_plant.h#L99)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW says "recommended" here but "invalid" a few lines earlier.
</blockquote></details>

Done. (The way I had worded this confused me on a second look as well).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7066)*

**Comment by RussTedrake** [comment]
@edrumwri -- fyi, you know that I had done this already once, too (and it's in master; you reviewed it ;-).  See #5226.  I'm ok if you zap my version, but the result should be one consistent API, please.

**Comment by edrumwri** [comment]
@RussTedrake I based my version off of yours. Note that I'm having to make certain arrangements since my version is in /dev. However, mine is a drop-in replacement for RigidBodyPlant.

**Comment by RussTedrake** [comment]
Rockin’.  Thanks

**Pull request merged**
