### PR TITLE
Add pybinds for mbp::AddDistanceConstraint and mbp::AddBallConstraint

### PR DESCRIPTION
**Pull request by yu-fz**
This PR adds python bindings for `MultibodyPlant::AddDistanceConstraint()` and `MultibodyPlant::AddBallConstraint()`

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot ok to test

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot test this please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @yu-fz)

___
*[`examples/BUILD.bazel` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-NR-ruRO8IR_vf36K-9F:-NR-ruRPAMo-R5Nv7SKJ:bqek4z8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e601ced1e4db1c4602cafc11b0555436a50ef024/examples/BUILD.bazel#L48)):*
> ```Starlark
>     "//examples/pr2",
>     "//examples/quadrotor",
>     "//examples/multibody/four_bar",
> ```

The python unit test has no cause to use this model file.  The bindings test should be simplicity itself.  Loading a model file is overkill.

**Comment by jwnimmer-tri** [comment]
@yu-fz I'll work with @amcastro-tri offline to help update the code to meet our standards.  We don't expect first-time contributors to be able to get it perfect the first time.

**Review by amcastro-tri — COMMENTED** [review]
The reality is that your unit test is doing way more than what it should, simply check the bindings are correct. That is, you don't need to check the MultibdoyPlant code is correct (for which we have c++ unit test), but only that the bindings do what they are supposed to.

:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-:-NR-tmqs8Iscd2FT1srU:b-4609t)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @yu-fz)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026)* status: 8 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @yu-fz)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2147 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-NR-uke73a7-Aps3u-dp:-NR-uke73a7-Aps3u-dq:b-9jahca) ([raw file](https://github.com/RobotLocomotion/drake/blob/e601ced1e4db1c4602cafc11b0555436a50ef024/bindings/pydrake/multibody/test/plant_test.py#L2147)):*
> ```Python
> 
>     @numpy_compare.check_all_types
>     def test_coupler_constraint_api(self, T):
> ```

A better testing strategy here would be implemented in its own file, say `plant_constraints_test.py`
The test would simply make sure we can all the APIs correctly and test publicly exposed invariants (eg. indexes increase as constraints are added). Something akin of:

```Python

plant = MultibodyPlant(0.01)

# Since we won't be performing dynamics computations, a garbage inertia is ok for this test.
body= plant.AddRigidBody(name="body_a",
         M_BBo_B=SpatialInertia())

constraint_index = plant.AddDistanceConstraint(body_A=plant.world_body(), p_AP=[1, 2, 3], body_B=body, p_BP=[4, 5, 6], distance=0.01)

self.assertEqual(plant.num_constraints(), 1)
self.assertEqual(constraint_index, ConstraintIndex(0))

```

a very short test that it's only focused on the new functionality. Significantly simpler than what you originally had here, and without the need to even modify BUILD files to make models we don't need public.

**Review by amcastro-tri — COMMENTED** [review]
Per conversation above, I only left a single unresolved comment regarding the expected structure of the unit test. All other comments are not longer applicable after the requested changes and therefore I retracted them to reduce noise.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-:-NR3OSBHDHljJL0mDbiL:b-b193ub)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @yu-fz)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2147 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-NR-uke73a7-Aps3u-dp:-NR3NmIz0nt9SbMNs13z:bc3sza9) ([raw file](https://github.com/RobotLocomotion/drake/blob/e601ced1e4db1c4602cafc11b0555436a50ef024/bindings/pydrake/multibody/test/plant_test.py#L2147)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

A better testing strategy here would be implemented in its own file, say `plant_constraints_test.py`
The test would simply make sure we can all the APIs correctly and test publicly exposed invariants (eg. indexes increase as constraints are added). Something akin of:

```Python

plant = MultibodyPlant(0.01)

# Since we won't be performing dynamics computations, a garbage inertia is ok for this test.
body= plant.AddRigidBody(name="body_a",
         M_BBo_B=SpatialInertia())

constraint_index = plant.AddDistanceConstraint(body_A=plant.world_body(), p_AP=[1, 2, 3], body_B=body, p_BP=[4, 5, 6], distance=0.01)

self.assertEqual(plant.num_constraints(), 1)
self.assertEqual(constraint_index, ConstraintIndex(0))

```

a very short test that it's only focused on the new functionality. Significantly simpler than what you originally had here, and without the need to even modify BUILD files to make models we don't need public. 
</blockquote></details>

per discussion with @jwnimmer-tri, this unit test should stay in `plant_test.py`  since the code is in `plant_py.cc.`

**Comment by jwnimmer-tri** [comment]
Thanks for your patience!

I've provided the suggested changes here:
https://github.com/yu-fz/drake-pybind-multibody-constraints/pull/1

If you like, have a look at those suggestions and use the "Merge" button to add them into this PR.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review and platform review (per tomorrow's schedule), please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 2147 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-NR-uke73a7-Aps3u-dp:-NRAloOHEXNrBbRAZ7O-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e601ced1e4db1c4602cafc11b0555436a50ef024/bindings/pydrake/multibody/test/plant_test.py#L2147)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per discussion with @jwnimmer-tri, this unit test should stay in `plant_test.py`  since the code is in `plant_py.cc.`
</blockquote></details>

Done.

**Comment by yu-fz** [comment]
> Thanks for your patience!
> 
> I've provided the suggested changes here: [yu-fz#1](https://github.com/yu-fz/drake-pybind-multibody-constraints/pull/1)
> 
> If you like, have a look at those suggestions and use the "Merge" button to add them into this PR.

Thank you for supporting my contribution, and all the helpful advice regarding unit testing!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2, thank you!

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19026#-:-NRE6Wq39WE95Z32POgG:b-dwn1hn)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @yu-fz)

**Pull request merged**
