### PR TITLE
Updates maliput_railcar's Method of Computing the PoseVector Quaternion.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5446)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR is blocked on #5443.

**Comment by liangfok** [comment]
+@jwnimmer-tri for all three levels of review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5446#-:-KehvUPu2cIuRIrK5-EG:b-6hnkpt)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5446#-Kei_V1QNcJYe9vgvPoJ:-Kei_V1QNcJYe9vgvPoK:b8lsaag) ([raw file](https://github.com/robotlocomotion/drake/blob/6702bd59f488c573483148f52efff3f0c7ed99c4/drake/automotive/maliput_railcar.cc#L11)):*
> ```cpp
> #include "drake/automotive/maliput/api/lane.h"
> #include "drake/common/drake_assert.h"
> #include "drake/math/roll_pitch_yaw_not_using_quaternion.h"
> ```

BTW This is unused now, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5446#-:-Kei_cZWyIIFyoLpF98p:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5446#-Kei_V1QNcJYe9vgvPoJ:-KeieL76B-Ba71EIDVAs:b-376vyo) ([raw file](https://github.com/robotlocomotion/drake/blob/6702bd59f488c573483148f52efff3f0c7ed99c4/drake/automotive/maliput_railcar.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This is unused now, I think?
</blockquote></details>

Done. Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5446)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5446)*

**Pull request merged**
