### PR TITLE
Avoiding accessing a null pointer in RBT::collisionDetectFromPoints

### PR DESCRIPTION
**Pull request by gizatt**
I ran into this case during development a while back; it required some special circumstances to cause it to happen (the collision engine needs to find no other objects to check distance against), but it seemed worth guarding anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6522)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
Several thoughts:

1. As I understand it, this would only happen if all of the meshes are anchored *and* represented by meshes (and not primitives).  Is there some other case?
2. Do the call sites of this method account for a -1 index?
3. The documentation should be updated to indicate that an element index may come back as invalid.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoP-UzoC_Yx2mjZQP0C:b-w5u21m)*

**Comment by gizatt** [comment]
1) I'm not sure about bullet's internals, so that certainly could be true! It also looks like it could happen if there are no bodies in the collision world (would that happen if a URDF contained only visual geometry?).
2) Tests seem to indicate no concerns within Drake, and my uses certainly do! Moving forward, folks should, because of 3. I suspect that anyone whose code would have issue in the old arrangement would have segfaulted in the old arrangement anyway?
3) Done!

Would you be willing to officially take over feature review? If not, any suggestions on someone else I should ask?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoPBlRQIlS-ko-ZUZro:b-8zsthv)*

**Comment by SeanCurtis-TRI** [comment]
+@seancurtis-tri for feature review

1. An excellent point.
2. Remember that not *all* the tests run as part of the PR process. There is a possibility that something gets burned in the full nightly tests (although, performing this test when there are no collision elements or only anchored elements seems unlikely).
3. Thanks. And I applaud going the extra mile for full documentation.

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 825 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJoTTbkFklwYRaNXX:-KoSJoTTbkFklwYRaNXY:bgfb99m) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.cc#L825)):*
> ```cpp
>       body_idx.push_back(elementB->get_body()->get_body_index());
>     } else {
>       body_idx.push_back(-1);
> ```

Given the comments, you could simply exclude this branch and leave the index value "undefined". Or you could change the comment. Either way would be fine.

---

*[drake/multibody/rigid_body_tree.h, line 966 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSIMCLddZJdZ0BSSJF:-KoSIMCLddZJdZ0BSSJG:b-fkodqo) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L966)):*
> ```objc
>    * the RigidBodyTree.
>    *
>    * @param cache[in] a KinematicsCache constructed by RigidBodyTree::doKinematics
> ```

1. [in] in the wrong place: i.e., `@param[in] cache a ...`
2. Line too long.

---

*[drake/multibody/rigid_body_tree.h, line 968 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSIslnNVRF4N6Du84H:-KoSIslnNVRF4N6Du84I:b-setjy0) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L968)):*
> ```objc
>    * @param cache[in] a KinematicsCache constructed by RigidBodyTree::doKinematics
>    * given `q` and `v`.
>    *
> ```

BTW nit: extraneous vertical whitespace (here and after `points`.

---

*[drake/multibody/rigid_body_tree.h, line 976 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJIpIVI15a-Nwmjxx:-KoSJIpJTf-p9hGo5qC_:b-zhhoms) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L976)):*
> ```objc
>    * was found, all other output parameters are undefined.
>    * @param[out] normal Resized to 3xN elements and filled with mesh normals,
>    * in world frame, at the closest point on the mesh to each point in
> ```

BTW: meta - "mesh" isn't the right word. It would be "collision element" because this encapsulates all of the geometric primitives (spheres, cylinders, etc.)

---

*[drake/multibody/rigid_body_tree.h, line 983 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJZ9wS506X0xZ9J_m:-KoSJZ9xFGdrNAX0RAvR:b13wf79) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L983)):*
> ```objc
>    * points in body frame of the closest body, to each point in `points`.
>    * @param[out] body_idx Resized to N elements and filled with the body idx
>    * of the closest body to each point in `points`. Beware: will be set to -1
> ```

BTW This is contradicted by the note for `phi` ("If no closest point was found, all other output parameters are undefined.")

---

*[drake/multibody/rigid_body_tree.h, line 987 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJiQDhZqw1aXrZpYA:-KoSJiQDhZqw1aXrZpYB:b-706tlu) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L987)):*
> ```objc
>    * @param[in] use_margins Whether to pad each collision body with a narrow
>    * (see bullet_model) margin to improve stability of normal estimation at
>    * the  cost of the accuracy of closest points calculations.
> ```

extraneous space between "the" and "cost".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoSI38R98ch0n18pjPe:bvpcit1)*

**Comment by gizatt** [comment]
Thanks! Corresponding tweaks made.

---

Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 825 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJoTTbkFklwYRaNXX:-KoSkQBWlp2XoiOW_Sqx:b-mes4n1) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.cc#L825)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Given the comments, you could simply exclude this branch and leave the index value "undefined". Or you could change the comment. Either way would be fine.
</blockquote></details>

Went for the clarify-documentation route.

---

*[drake/multibody/rigid_body_tree.h, line 966 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSIMCLddZJdZ0BSSJF:-KoSkP48WGksQTaqHD3s:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L966)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

1. [in] in the wrong place: i.e., `@param[in] cache a ...`
2. Line too long.
</blockquote></details>

Fixed.

---

*[drake/multibody/rigid_body_tree.h, line 968 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSIslnNVRF4N6Du84H:-KoSkfqdTHCDi7qwgCjF:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L968)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW nit: extraneous vertical whitespace (here and after `points`.
</blockquote></details>

Removed.

---

*[drake/multibody/rigid_body_tree.h, line 976 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJIpIVI15a-Nwmjxx:-KoSkyLaL87-o0V-51j5:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L976)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW: meta - "mesh" isn't the right word. It would be "collision element" because this encapsulates all of the geometric primitives (spheres, cylinders, etc.)
</blockquote></details>

Fixed.

---

*[drake/multibody/rigid_body_tree.h, line 983 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJZ9wS506X0xZ9J_m:-KoSl6pi7Dr2RMiAMa5H:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L983)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This is contradicted by the note for `phi` ("If no closest point was found, all other output parameters are undefined.")
</blockquote></details>

Fixed.

---

*[drake/multibody/rigid_body_tree.h, line 987 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSJiQDhZqw1aXrZpYA:-KoSlEmq1TCppquDmCoe:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/7701625695f9018caf274ae78c0579360e0db96b/drake/multibody/rigid_body_tree.h#L987)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

extraneous space between "the" and "cost".
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoSnJX5Xgv0OwzhGmbN:bqx43q2)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoSoCcHLSqJVizKAtEY:bjw1nz)*

**Comment by SeanCurtis-TRI** [comment]
+@sammy-tri for platform review
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoSoIp658hFIvaokYmq:b-t4yczp)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_tree.cc, line 820 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSvJjCRNxMHvCAoffd:-KoSvJjEMzPSQjotyU-V:b2h0n6h) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7554a37d9f9cdbd3921d005ad18bad230ca6ef/drake/multibody/rigid_body_tree.cc#L820)):*
> ```cpp
>     phi[i] = closest_points[i].distance;
>     const DrakeCollision::Element* elementB = closest_points[i].elementB;
>     // In the case of not closest points, elementB can come back
> ```

"In the case of not closest points" sounds a bit awkward...   Would this still be correct if it said "In the case of no closest point"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522)*

**Comment by gizatt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_tree.cc, line 820 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-KoSvJjCRNxMHvCAoffd:-KoTiIW9Ah9YjFNUCw9F:b-w9xecw) ([raw file](https://github.com/robotlocomotion/drake/blob/bb7554a37d9f9cdbd3921d005ad18bad230ca6ef/drake/multibody/rigid_body_tree.cc#L820)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"In the case of not closest points" sounds a bit awkward...   Would this still be correct if it said "In the case of no closest point"?
</blockquote></details>

Indeed, typo clarified / fixed. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6522#-:-KoTitY-yLn2shiP75Bl:bnfp4nl)*

**Pull request merged**
