### PR TITLE
setup: Upgrade to Bazel 0.22

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I'm upgrading Anzu to Python 3, and am in need of this commit (contained by 0.22):
https://github.com/bazelbuild/bazel/commit/5b5f67946615a49eac7b2a4a2bcf0e6d88086527

\cc @jwnimmer-tri 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10690)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Needs updates to the support matrix too. You can take the opportunity to drop the patch version, 0.22 is plenty of precision.

**Comment by jamiesnape** [comment]
I think we can just use `do not merge` for blocking. We are all adults here...

**Comment by BetsyMcPhail** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/10690#-LYhOYeK3h2knghfl0rA:-LYhgTBx2bUwD2hQHZwH:bf6sfvf) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@betsymcphail Would it be possible to update the Ubuntu images with this newer version of Bazel?
</blockquote></details>

Ubuntu images & Jenkins have been updated. As always, it's going to take Jenkins awhile to cycle through to using the new images. 

---

**Pull request merged**
