### PR TITLE
Fix warning emitted during MOSEK install causing errors during CMake builds

### PR DESCRIPTION
**Pull request by jamiesnape**
Addresses failures including:
* https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-cmake-continuous-mosek-debug/596/
* https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-cmake-continuous-mosek-release/593/
* https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-cmake-continuous-matlab-mosek-release/569/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8693)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-mosek please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-mosek please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review (or any other passing platform reviewer).

**Comment by hongkai-dai** [comment]
Thanks for fixing this! I should have tested the cmake build in my PR.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8693#-:-LB30TbX4a2YktLSryZN:bjoby4d)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8693#-:-LB30_lz8dXCpIT_XLiP:bnfp4nl)*

**Pull request merged**
