### PR TITLE
Add a bit more Bazel documentation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4234)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok and +@soonho-tri for feature review of `drake/doc/bazel.rst`, please.  (Please try running it!)
+@david-german-tri for platform review, please.

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-:-KXDd3pFWleTWuQ2acC_:bkh4mpa)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDhw3aCZ-vNc3_Bvw_:-KXDhw3aCZ-vNc3_Bvwa:b-vxebga) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L39)):*
> ```reStructuredText
> 
> To build or test Drake, run **bazel build** or **bazel test** with the desired
> target label.
> ```

Where are we supposed to run the following bazel commands? at `drake-distro` or `drake-distro/build`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDi4fpluJJiBExzDoL:-KXDi4fpluJJiBExzDoM:b-wk01jo) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L47)):*
> ```reStructuredText
> Build only the systems (sub)directories::
> 
>   bazel build drake/systems/...
> ```

When I ran this command at `drake-distro`, it seemed to trigger a build properly. But I have the OSX issue (`glib.h`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/bazel.rst, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDhw3aCZ-vNc3_Bvw_:-KXDi77Y02d1yXUo2SrR:b2a4dj5) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> Where are we supposed to run the following bazel commands? at `drake-distro` or `drake-distro/build`?
</details>
At drake-distro (the `build` directory is a CMake-ism).  I'll update the instructions to clarify that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDiK8AfIdDm3wI7rll:-KXDiK8AfIdDm3wI7rlm:be0bcl) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L43)):*
> ```reStructuredText
> Build the entire project::
> 
>   bazel build ...
> ```

I ran this at `drake-distro`, but I have
```
$ bazel build ...
ERROR: Bad target pattern '../..': package name component contains only '.' characters.
INFO: Elapsed time: 0.170s
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDiVXtBo_AM938Vm4q:-KXDiVXtBo_AM938Vm4r:boit3jx) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L51)):*
> ```reStructuredText
> Build and test the entire project::
> 
>   bazel test ...
> ```

Similar problem (working dir = `drake-distro`)

```
$ bazel test ...
ERROR: Bad target pattern '../..': package name component contains only '.' characters.
INFO: Elapsed time: 0.158s
ERROR: Couldn't start the build. Unable to run tests.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDid0YXFuGH9Ha7yxI:-KXDid0YXFuGH9Ha7yxJ:b-dtdzrf) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L55)):*
> ```reStructuredText
> Run one specific test::
> 
>   bazel test drake/systems/framework/test/diagram_test
> ```

FYI, this one is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/bazel.rst, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDiK8AfIdDm3wI7rll:-KXDj_1-_Xk5hlpf9X95:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L43)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> I ran this at `drake-distro`, but I have
> ```
> $ bazel build ...
> ERROR: Bad target pattern '../..': package name component contains only '.' characters.
> INFO: Elapsed time: 0.170s
> ```
</details>
Done.

---

*[drake/doc/bazel.rst, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDiVXtBo_AM938Vm4q:-KXDjiFoT5g-jrd7ejAD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6fe7d8fb7769e478ce1e1bcaa30c076dd1f0f2b9/drake/doc/bazel.rst#L51)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> Similar problem (working dir = `drake-distro`)
> 
> ```
> $ bazel test ...
> ERROR: Bad target pattern '../..': package name component contains only '.' characters.
> INFO: Elapsed time: 0.158s
> ERROR: Couldn't start the build. Unable to run tests.
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDkLtBW6Vh5wwf67y5:-KXDkLtBW6Vh5wwf67y6:brr4rhp) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L70)):*
> ```reStructuredText
>   bazel-bin/drake/systems/framework/test/diagram_test
>   
> For more reading about target patters, see:
> ```

patters => patterns?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
Reviewed 20 of 21 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by jwnimmer-tri** [comment]
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXDkLtBW6Vh5wwf67y5:-KXE9V3qFDI0_NiWiBbu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L70)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> patters => patterns?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-:-KXF9dQsjrKjtZbu_J9q:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 7 of 21 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZOKsIsbdIHcN5AqAF:-KXZOKsIsbdIHcN5AqAG:bx3upcx) (no related file):*
BTW, I ran into the following problem:

```
$ bazel build //...
Extracting Bazel installation...
.
ERROR: /Users/liang/dev/drake-distro-5/tools/lcm.bzl:56:19: Traceback (most recent call last):
	File "/Users/liang/dev/drake-distro-5/tools/lcm.bzl", line 51
		rule(implementation = _lcmhpp_impl, att...()}, ...)
	File "/Users/liang/dev/drake-distro-5/tools/lcm.bzl", line 56, in rule
		attr.label(cfg = "host", executable = True, def..."))
expected ConfigurationTransition or NoneType for 'cfg' while calling label but got string instead: host.
ERROR: package contains errors: drake/lcmtypes.
ERROR: error loading package 'drake/lcmtypes': Extension file 'tools/lcm.bzl' has errors.
INFO: Elapsed time: 2.512s
```

However, this might be because I'm using OSX and Bazel 0.3.0. I'll try again using Ubuntu Xenial and Bazel 0.3.1 as stated in `bazel.rst`.

---

*[drake/doc/bazel.rst, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZNuVOXIr40STVU948:-KXZNuVOXIr40STVU949:b-ir8e4c) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L11)):*
> ```reStructuredText
>  * https://github.com/RobotLocomotion/drake/issues/3129
> 
> Bazel Installation
> ```

BTW, consider adding named anchors before headings. For example:

```
.. _bazel_installation:

Bazel Installation
==================
```

---

*[drake/doc/bazel.rst, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZN42_h8qaa8DH5P2h:-KXZN42_h8qaa8DH5P2i:b-54x5xf) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L42)):*
> ```reStructuredText
> 
> All of the below commands should be run from the **drake-distro** working
> directory, i.e., at the root directory of the git clone.
> ```

BTW, does Bazel support build options that, for example, disable certain features because of proprietary dependencies?

---

*[drake/doc/bazel.rst, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMcVQ1UXdKey4hlyP:-KXZMcVR_ZamacN0fG4Z:b56ip5e) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L67)):*
> ```reStructuredText
> Run one of the compiled programs manually, from the build outputs directory
> (note that ``bazel-bin`` is a directory name here)::
>     
> ```

BTW, nit: extraneous spaces.

---

*[drake/doc/bazel.rst, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMepqEplbP_RCYGgb:-KXZMepqEplbP_RCYGgc:b56ip5e) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L69)):*
> ```reStructuredText
>     
>   bazel-bin/drake/systems/framework/test/diagram_test
>   
> ```

BTW, nit: extraneous spaces.

---

*[drake/doc/bazel.rst, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMiVKsf4SVZPsd9lm:-KXZMiVKsf4SVZPsd9ln:b-4r614t) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L70)):*
> ```reStructuredText
>   bazel-bin/drake/systems/framework/test/diagram_test
>   
> For more reading about target patters, see:
> ```

Typo: "patters" → "patterns".

---

*[drake/doc/bazel.rst, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMKlfVaNMYEnhJDKZ:-KXZMKlfVaNMYEnhJDK_:b-3pksq6) ([raw file](https://github.com/robotlocomotion/drake/blob/dfd1c09dce08cafc845e6885ddf8811cd77f51af/drake/doc/bazel.rst#L44)):*
> ```reStructuredText
> directory, i.e., at the root directory of the git clone.
> 
> Build the entire project::
> ```

BTW, does this build Drake in _all_ modes (Debug, Release, etc.)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by liangfok** [comment]
Reviewed 13 of 21 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/bazel.rst, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMcVQ1UXdKey4hlyP:-KXa8tfj5u5oZOfR8OXi:b-6rymto) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L67)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, nit: extraneous spaces.
</details>
Even in the latest revision?

---

*[drake/doc/bazel.rst, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMiVKsf4SVZPsd9lm:-KXa9--4DEpVKIsUkKc7:b-6rymto) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L70)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Typo: "patters" → "patterns".
</details>
Even in the latest revision?

---

*[drake/doc/bazel.rst, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMKlfVaNMYEnhJDKZ:-KXa8kqxsxSYOhJ7-WfL:b-msh4pb) ([raw file](https://github.com/robotlocomotion/drake/blob/dfd1c09dce08cafc845e6885ddf8811cd77f51af/drake/doc/bazel.rst#L44)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, does this build Drake in _all_ modes (Debug, Release, etc.)?
</details>
Only the default mode, which is `opt` right now.
https://github.com/RobotLocomotion/drake/blob/63d3436148b6c16cb256682f842279203d513bdd/tools/bazel.rc#L2-L3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZOKsIsbdIHcN5AqAF:-KXaNiDw2ygNxUjMBeAe:b-byof4i) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, I ran into the following problem:
> 
> ```
> $ bazel build //...
> Extracting Bazel installation...
> .
> ERROR: /Users/liang/dev/drake-distro-5/tools/lcm.bzl:56:19: Traceback (most recent call last):
> 	File "/Users/liang/dev/drake-distro-5/tools/lcm.bzl", line 51
> 		rule(implementation = _lcmhpp_impl, att...()}, ...)
> 	File "/Users/liang/dev/drake-distro-5/tools/lcm.bzl", line 56, in rule
> 		attr.label(cfg = "host", executable = True, def..."))
> expected ConfigurationTransition or NoneType for 'cfg' while calling label but got string instead: host.
> ERROR: package contains errors: drake/lcmtypes.
> ERROR: error loading package 'drake/lcmtypes': Extension file 'tools/lcm.bzl' has errors.
> INFO: Elapsed time: 2.512s
> ```
> 
> However, this might be because I'm using OSX and Bazel 0.3.0. I'll try again using Ubuntu Xenial and Bazel 0.3.1 as stated in `bazel.rst`.
</details>
@liangfok , 
1) How did you install `bazel` on your mac? I installed it via `homebrew`, and I got `0.4.0`.
2) Unfortunately, there is an issue with `libglib` on OSX which causes problems using `bazel`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZOKsIsbdIHcN5AqAF:-KXaS4wyWnRmajD13yH8:bpe6g5x) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> @liangfok , 
> 1) How did you install `bazel` on your mac? I installed it via `homebrew`, and I got `0.4.0`.
> 2) Unfortunately, there is an issue with `libglib` on OSX which causes problems using `bazel`.
</details>
Last night I installed `bazel 0.3.0` using homebrew:

```
brew install bazel
```

This morning I upgraded to `bazel 0.4.0` by executing the following:

```
brew update
brew upgrade bazel
```

I'm happy to report that I'm now encountering the aforementioned `libglib` error:

```
$ bazel build //...
Extracting Bazel installation...
........
INFO: Found 118 targets...
ERROR: /private/var/tmp/_bazel_liang/af2684a1477710fe5b8178eba233f9d1/external/lcm/BUILD:20:1: C++ compilation of rule '@lcm//:lcm' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_liang/af2684a1477710fe5b8178eba233f9d1/bazel-sandbox/63aec4e6-464c-440f-bc9e-2c6c07d6d52c-10/sandbox.sb external/local_config_cc/cc_wrapper.sh ... (remaining 58 argument(s) skipped).
In file included from external/lcm/lcm/lcm_tcpq.c:20:
external/lcm/lcm/lcm_internal.h:4:10: fatal error: 'glib.h' file not found
#include <glib.h>
         ^
1 error generated.
INFO: Elapsed time: 11.816s, Critical Path: 0.38s
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMcVQ1UXdKey4hlyP:-KXapFsQ1nKDctt3GBNr:bw2axgv) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L67)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Even in the latest revision?
</details>
Nope. Oops,  I guess I was looking at an older version.

---

*[drake/doc/bazel.rst, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMiVKsf4SVZPsd9lm:-KXapNpxc-eYHELZo1fG:bw2axgv) ([raw file](https://github.com/robotlocomotion/drake/blob/1a87a82c7c32755bcd0e465964c4b8519da4703b/drake/doc/bazel.rst#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Even in the latest revision?
</details>
Nope. Oops,  I guess I was looking at an older version.

---

*[drake/doc/bazel.rst, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMKlfVaNMYEnhJDKZ:-KXap6icMxbItLvNnU0r:b1z914k) ([raw file](https://github.com/robotlocomotion/drake/blob/dfd1c09dce08cafc845e6885ddf8811cd77f51af/drake/doc/bazel.rst#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Only the default mode, which is `opt` right now.
> https://github.com/RobotLocomotion/drake/blob/63d3436148b6c16cb256682f842279203d513bdd/tools/bazel.rc#L2-L3
</details>
Thanks. The instructions below mention executing a test in debug mode using `-c dbg`. How was the software compiled in debug mode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-:-KXapY14aU7zS5vNzAXl:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/bazel.rst, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMKlfVaNMYEnhJDKZ:-KXawoWKCWIS2CN8nE4I:b-dz76el) ([raw file](https://github.com/robotlocomotion/drake/blob/dfd1c09dce08cafc845e6885ddf8811cd77f51af/drake/doc/bazel.rst#L44)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks. The instructions below mention executing a test in debug mode using `-c dbg`. How was the software compiled in debug mode?
</details>
Exactly how the example says -- if you want to run a test in debug mode, just key in that command and the program will be recompiled iff necessary, and then run.  The build doesn't have a "sticky" build flavor that's set up-front -- just ask for what you want, and you get it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/bazel.rst, line 44 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-KXZMKlfVaNMYEnhJDKZ:-KXd-pK4v1vLpma_CiDo:b-v6rzh8) ([raw file](https://github.com/robotlocomotion/drake/blob/dfd1c09dce08cafc845e6885ddf8811cd77f51af/drake/doc/bazel.rst#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Exactly how the example says -- if you want to run a test in debug mode, just key in that command and the program will be recompiled iff necessary, and then run.  The build doesn't have a "sticky" build flavor that's set up-front -- just ask for what you want, and you get it.
</blockquote></details>

Nice! Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 20 of 21 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4234#-:-KXf_WI3RNMUH7YGfCGJ:bnfp4nl)*

**Pull request merged**
