### PR TITLE
reduce tolerance for IPOPT

### PR DESCRIPTION
**Pull request by RussTedrake**
post-merge CI tested this for me.
disappointed to have to do this... but it looks like IPOPT requires it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3712)

### CODE REVIEW

**Comment by RussTedrake** [comment]
this should resolve this:

Jenkins build became unstable: linux-gcc-continuous-matlab-open-source #804
https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-matlab-open-source/804/

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-continuous-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-continuous-matlab-open-source please

**Comment by rpoyner-tri** [comment]
so it is. :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3712#-:-KTRxxSpJJJZvw8jeewZ:b-5oryhq)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-continuous-matlab-open-source please

**Comment by RussTedrake** [comment]
good call @tkoolen.  you inspired me to look into it.  
http://www.coin-or.org/Ipopt/documentation/node42.html#SECTION000112070000000000000 says the default constraint satisfaction tolerance is set to 1e-2!  
snopt's default is 1e-6. 

first thing to try is to set IPOPT's acceptable_constr_viol_tol to 1e-6.  will have a go.
(unfortunately, not having IPOPT on mac is a pain point here)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by sammy-tri** [comment]
IIRC IPOPT should be usable on Mac if MATLAB is disabled...  Though it was a long time ago that I tested that in CI.

**Comment by RussTedrake** [comment]
note: sadly, based on a quick test this did not resolve #3128 .

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by RussTedrake** [comment]
CI is failing to compile on the energy shaping examples.  Is this a known problem with master?

**Comment by liangfok** [comment]
It is not. What's happening here is this PR's branch is being merged with the latest on master, which has a new LCM mocking framework. The mocking framework's namespace is conflicting with LCM's namespace, resulting in the compiler error. The compiler error should be fixed by rebasing this PR's branch with master and resolving the merge conflicts.

**Comment by RussTedrake** [comment]
thanks @liangfok .  was just trying that.  :)

**Comment by liangfok** [comment]
Actually, sorry, I take it back. Apparently #3643 broke [continuous production](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/)! I'm looking into it now.

**Comment by liangfok** [comment]
Aha! I don't think it was #3643 that broken continuos production, but rather the merging of #3696. Apparently, #3696 was merged without first rebasing with master.

screen shot 2016-10-08 at 8 45 21 am

I am attempting to fix-forward.

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by liangfok** [comment]
:lgtm:  Just one BTW comment.

---

Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/ipopt_solver.cc, line 453 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3712#-KT_0DtWvPYsh_N2CCUY:-KT_-6SmG86LpBdz83pC:b-erp5a4) ([raw file](https://github.com/robotlocomotion/drake/blob/9d8c3b13e2b9c6d71e14d4279d623647b443187c/drake/solvers/ipopt_solver.cc#L453)):*
BTW: nits:
* "note" should be "Note".
* Missing period at end of sentence.
* Can you add a brief explanation on why IPOPT requires an even tighter tolerance than SNOPT? I notice the following comment above that might be why:

> Retrospective justification:  the compare matrices tolerance should be sqrt ( constr_tolerance ), since the constraint tolerance is presumably being computed in a euclidean sense.

Adding an explanation as a comment in the source code will prevent such insights from getting lost as margin notes of a PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3712#-:-KT_1i3Q0NuG5vj0Fv0J:b9vaz47)*

**Comment by RussTedrake** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/ipopt_solver.cc, line 453 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3712#-KT_0DtWvPYsh_N2CCUY:-KT_5vgzOQuU1qvwGjpd:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/9d8c3b13e2b9c6d71e14d4279d623647b443187c/drake/solvers/ipopt_solver.cc#L453)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nits:
> * "note" should be "Note".
> * Missing period at end of sentence.
> * Can you add a brief explanation on why IPOPT requires an even tighter tolerance than SNOPT? I notice the following comment above that might be why:
> 
> > Retrospective justification:  the compare matrices tolerance should be sqrt ( constr_tolerance ), since the constraint tolerance is presumably being computed in a euclidean sense.
> 
> Adding an explanation as a comment in the source code will prevent such insights from getting lost as margin notes of a PR.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3712)*

**Pull request merged**
