### PR TITLE
Remove BasicState.*Vector.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #3208.

+@amcastro-tri for feature review (system2), +@jwnimmer-tri for feature review (cars) and platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3366)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/gen/driving_command.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3366#-KR00-UnFE4KpSjDahI6:-KR00-Uomq7VizrYKyeZ:bcjjk7p) ([raw file](https://github.com/robotlocomotion/drake/blob/409289026ae38c94609bb12891126cd2594dd917/drake/examples/Cars/gen/driving_command.h#L12)):*
> ```objc
> 
> #include "lcmtypes/drake/lcmt_driving_command_t.hpp"
> #include "drake/drakeCars_export.h"
> ```

BTW, should there be a blank line separating the LCM type include and the drake includes? Otherwise, it looks like it's not properly alpha sorted.

(Same comment for all the other instances in this PR.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366)*

**Comment by david-german-tri** [comment]
Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/gen/driving_command.h, line 12 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3366#-KR00-UnFE4KpSjDahI6:-KR021XeSt1TaOXzFaAU:b3t3xvg) ([raw file](https://github.com/robotlocomotion/drake/blob/409289026ae38c94609bb12891126cd2594dd917/drake/examples/Cars/gen/driving_command.h#L12)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should there be a blank line separating the LCM type include and the drake includes? Otherwise, it looks like it's not properly alpha sorted.
> 
> (Same comment for all the other instances in this PR.)
</details>
Well, it definitely isn't alpha sorted.  I've fixed the generator (and consequently this and all the other generated files).  Not sure why it worked previously.  Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366)*

**Comment by jwnimmer-tri** [comment]
Looks good on first pass.  I will want to double-check a few things on a second pass, which I will do a bit later this evening.

Be sure to opt-in to the ROS build before merging.

---

Reviewed 20 of 25 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366#-:-KR05m6JMpT3qwBDiuPr:b-easyui)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366)*

**Comment by amcastro-tri** [comment]
Great!, thank you. :lgtm: 

---

Reviewed 20 of 25 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366#-:-KR0EZKGHzHQQiQCR_SS:b8jjvfq)*

**Comment by jwnimmer-tri** [comment]
:lgtm: to keep things moving.  I didn't get a second pass yet, but I'll just do that later and follow-up PR with any issues (seems unlikely).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366#-:-KR0GVxJlEOkPHBvaxlw:bu6szur)*

**Comment by jwnimmer-tri** [comment]
:lgtm_strong:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3366#-:-KR0mNQjIZHqAamq6WZq:b-jbsf8z)*

**Pull request merged**
