### PR TITLE
Remove log cursor management from DrakeLcmInterface

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8421)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.

**Comment by siyuanfeng-tri** [comment]
looks clean and great. 
but.. I think the original intention is to completely avoid changing the diagram's topology when switching to a lcm log. I think the for this PR, you need to inject a separate system somewhere in the big diagram. It is a one line change on the application / diagram building site, but this is quite subtle, and can catch people off guard. Sort of like calling lcm interface start listener thread. 
I am neutral to this change. But if we go forward with this. I'd like to somehow make this change more obvious. 
maybe loop in more users? @naveenoid @russtedrake @ericcousineau-tri and more? 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-:-L89AQyFqQ8tVlWr3_b6:b-jventz)*

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri +@rcory +@hongkai-dai 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-:-L89D2MEUiDsF1Q-GRci:beq2nc4)*

**Comment by jwnimmer-tri** [comment]
I guess it would help me to have an example of code that's using this.  As far as I could find, nobody anywhere is using log-replay to feed inputs to a simulation.

**Comment by siyuanfeng-tri** [comment]
you are correct there is no real user at this point. the intended use case is:
you take any of the big simulation in examples/kuka_iiwa_arm, replace the real lcm interface with a lcm log, and all the rest stays the same. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-:-L89ESFQmtZIbdwcWasa:b-ubl1gx)*

**Comment by jwnimmer-tri** [comment]
So you replay your sensor inputs, but the robot pose messages will not obey your (new) control commands?  Anyway, if you are recompiling or changing a commang-line flag to use a log instead of live, it should be trivial to also add the time-governer into the simulation as well.  It doesn't have to be in the same Diagram as everything else, you could re-wrap it again.

**Comment by jwnimmer-tri** [comment]
For myself, I anyway would have written the log-replay code to `for-each-message` over the input log, and then `StepTo(GetNextMessageTime())` in the simulation; i.e., have the log own time, instead of the simulator owning time.

**Comment by siyuanfeng-tri** [comment]
For your first question. yeah, it looks weird. I suppose the right thing to do in that case would be having the publishers and subscribers have different lcm handles. 
I like the changes. I propose we let the others think about this for a bit. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-:-L89JRz6mhfCv2Ik1LeW:b9wmb16)*

**Comment by jwnimmer-tri** [comment]
Sounds good, thanks!  We'll let other folks offer thoughts too.

**Comment by sammy-tri** [comment]
I'm on board with this implementation.  :lgtm: with a couple questions inline.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/lcm/lcm_log_playback_system.cc, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8421#-L8D1NLx06GR46N_jAdN:-L8D1NLy3SNwAp9mOUHk:bsxuiwj) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d13f87b67a8e65b60c4e3b7d252ddf62e5fdaa/systems/lcm/lcm_log_playback_system.cc#L25)):*
> ```cpp
>   const double message_time = log_->GetNextMessageTime();
>   if (std::isinf(message_time)) {
>     LeafSystem<double>::DoCalcNextUpdateTime(context, events, time);
> ```

It feels weird to me (also see below) that the base class implementation is only appropriate to call in the case where there's not a next message.  It feels like either the content of `LeafSystem`'s `periodic_events_` is always relevant or it's never relevant.  (also in `LcmSubscriberSystem` below)

---

*[systems/lcm/lcm_log_playback_system.cc, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8421#-L8D2yn4BlrFeRziR-um:-L8D2yn4BlrFeRziR-un:b-3uakda) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d13f87b67a8e65b60c4e3b7d252ddf62e5fdaa/systems/lcm/lcm_log_playback_system.cc#L41)):*
> ```cpp
>   DRAKE_DEMAND(std::isfinite(message_time));
>   DRAKE_DEMAND(message_time > context.get_time());
>   *time = message_time;
> ```

BTW am I reading this correctly that this system could conceivably, if the log data were dense enough, drive the integrator/simulator all the way down to 1e-6 duration time steps?  (the old code would have done it too so probably doesn't need to be fixed here even if I'm correct)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8421#-:-L8D3ZMq7TVpazQ-w4QS:b9liahi)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/lcm/lcm_log_playback_system.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-L8D2yn4BlrFeRziR-um:-L8D96oTsFa71VlmMRAo:b-ebuzvz) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d13f87b67a8e65b60c4e3b7d252ddf62e5fdaa/systems/lcm/lcm_log_playback_system.cc#L41)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW am I reading this correctly that this system could conceivably, if the log data were dense enough, drive the integrator/simulator all the way down to 1e-6 duration time steps?  (the old code would have done it too so probably doesn't need to be fixed here even if I'm correct)
</blockquote></details>

OK Yes, you're right.  That's another good reason why time governance during log replay should not be part of the Diagram!  For now I would propose leaving this as-is, in order to keep the behavior the same for anyone who wanted what this does / used to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/lcm/lcm_log_playback_system.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-L8D1NLx06GR46N_jAdN:-L8DTbtef1GhngpuIolj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b0d13f87b67a8e65b60c4e3b7d252ddf62e5fdaa/systems/lcm/lcm_log_playback_system.cc#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It feels weird to me (also see below) that the base class implementation is only appropriate to call in the case where there's not a next message.  It feels like either the content of `LeafSystem`'s `periodic_events_` is always relevant or it's never relevant.  (also in `LcmSubscriberSystem` below)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421)*

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421)*

**Comment by jwnimmer-tri** [comment]
@rcory and @hongkai-dai -- if you have any thoughts, could you please post them here?  If you are indifferent, you could de-assign yourself to let the other folks decide.

**Comment by hongkai-dai** [comment]
Sorry for being late. :lgtm: 

---

Reviewed 4 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-:-L8JWemaDQsofzaaxrRy:bdcazng)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8421#-:-L8JYmJfXXngFKnyIewa:bnfp4nl)*

**Pull request merged**
