### PR TITLE
ScsSolver returns the dual solution for linear equality constraints.

### PR DESCRIPTION
**Pull request by hongkai-dai**
A step towards #13285

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18388)

### CODE REVIEW

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18388)* status: 2 unresolved discussions, LGTM missing from assignee pangtao22, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/scs_solver.cc` line 727 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18388#-NIWAfyq1ZFwjiB_SoMs:-NIWAfyq1ZFwjiB_SoMt:bjy6yvh) ([raw file](https://github.com/robotlocomotion/drake/blob/426a8c18d9b6b95dd60636bd1ad26065d1b19dd1/solvers/scs_solver.cc#L727)):*
> ```cpp
>     const std::vector<std::vector<std::pair<int, int>>>&
>         linear_constraint_dual_indices,
>     const std::vector<int>& linear_eq_constraint_dual_indices,
> ```

Consider renaming this to `linear_eq_constraint_y_start_indices`, since this is used in the same way as `lorentz_cone_y_start_indices` and `rotated_orentz_cone_y_start_indices`?
___
*[`solvers/scs_solver.cc` line 927 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18388#-NIWBTrcCVWGJEomEqBv:-NIWBTrcCVWGJEomEqBw:b-qd5kbj) ([raw file](https://github.com/robotlocomotion/drake/blob/426a8c18d9b6b95dd60636bd1ad26065d1b19dd1/solvers/scs_solver.cc#L927)):*
> ```cpp
>   std::vector<int> linear_eq_constraint_dual_indices;
>   ParseLinearEqualityConstraint(prog, &A_triplets, &b, &A_row_count, cone,
>                                 &linear_eq_constraint_dual_indices);
> ```

Ditto for renaming.

**Review by pangtao22 — COMMENTED** [review]
:lgtm: with a minor suggestion on renaming a variable.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18388#-:-NIWBfJpApUet6vJ16If:bbpsh6w)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18388#-:-NIWGGbT26F5XA6qyN7J:b-c9pjop)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @pangtao22 and @sammy-tri)

___
*[`solvers/scs_solver.cc` line 727 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18388#-NIWAfyq1ZFwjiB_SoMs:-NIWFtnT7QSA8eynrjn1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/426a8c18d9b6b95dd60636bd1ad26065d1b19dd1/solvers/scs_solver.cc#L727)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Consider renaming this to `linear_eq_constraint_y_start_indices`, since this is used in the same way as `lorentz_cone_y_start_indices` and `rotated_orentz_cone_y_start_indices`?
</blockquote></details>

Done.
___
*[`solvers/scs_solver.cc` line 927 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18388#-NIWBTrcCVWGJEomEqBv:-NIWFv0qCPdgbfa6-7WU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/426a8c18d9b6b95dd60636bd1ad26065d1b19dd1/solvers/scs_solver.cc#L927)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Ditto for renaming.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18388#-:-NIYzZss12CxaxkgSddC:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
