### PR TITLE
[examples] Remove obsolete examples built on loop_joint

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #1713

Per discussion in the issue, data files do not require deprecation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+none +(status: single reviewer ok) +@sammy-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951#-:-N-Z0lxi3Pzb23D4Gb-5:b-tl5ay8)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Should we be deleting the entire directory?  The SDF doesn't load in drake either because it contains a closed kinematic loop.  People interested in four bar linkages in drake should presumably consult `examples/multibody/four_bar` anyway.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951#-:-N-ZWX2_-qqDdLwX2y95:b-6cda8a)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
I like that. Will update.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951#-:-N-ZcdBL89S7rvslLeJK:b-wfgvj7)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by sammy-tri — COMMENTED** [review]
I think the remaining reference to this needs to be removed from `examples/BUILD.bazel`.  Marking :lgtm: so you can merge once you've gotten CI to pass.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951#-:-N-ZzQEZ5HR3E-hQzuoO:bws7bid)* status: missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: removal of deprecated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951#-:-N-nesxh3ucJaUAu6TnX:b-bk6sdp)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: removal of deprecated)  +(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16951#-:-N-nexCt7LqdTwuLe_bP:burpkep)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
+(release notes: yes) -- even though this is not a breaking change, it's still a user-visible change.

**Pull request merged**
