### PR TITLE
Incorporates the Implicit Stribeck solver in MBP

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR incorporates the `ImplicitStribeck` solver in the time stepping MultibodyPlant. 
Unit test tested on an inclined plane case where it shows to be more accurate than the continuous plant.
The simple gripper is updated to use this solver (cc'ing @rcory about this one).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please.

---

Review status: all discussions resolved, platform LGTM missing, commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043#-:-LFZ2bNmDLQj6KwBelbz:bltox9h)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
Review status: 3 unresolved discussions, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1308 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZCZhpEI4gLtOxwFz7:-LFZCZhpEI4gLtOxwFz8:b-x2xibr) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1308)):*
> ```objc
>   // The solver used when the plant is modeled as a discrete system.
>   std::unique_ptr<implicit_stribeck::ImplicitStribeckSolver<T>>
>       implicit_stribeck_solver_;
> ```

Set it to `nullptr`?

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZEtsX3AmIpcvFL8of:-LFZEtsX3AmIpcvFL8og:b-qlfbgr) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L61)):*
> ```cpp
> 
>  protected:
>   double time_step;
> ```

I thought class variables have trailing underscores.

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZFCXZ4i4j1Kju5YYd:-LFZFCXZ4i4j1Kju5YYe:b-hd2hhu) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L165)):*
> ```cpp
>   // integrator's accuracy was set to a relatively small value.
>   EXPECT_TRUE(
>       std::abs(ke_WB - ke_WB_expected) / ke_WB < 2 * relative_tolerance);
> ```

I do not understand why we need to multiply a factor of 2 here, maybe you could add some documentation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043#-:-LFZFpjF1r0Pp5ksLAfs:bozh2sc)*

**Comment by amcastro-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1308 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZCZhpEI4gLtOxwFz7:-LFZIlkX9umloeh8QyXK:b3kqe9y) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1308)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Set it to `nullptr`?
</blockquote></details>

From [GSG](http://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization) "Class objects are responsible for their own intialization", it applies here since this is a `unique_ptr`. It'd be different if I had a raw pointer.

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZEtsX3AmIpcvFL8of:-LFZL9-MEqmCakhvsGpc:b1mch4n) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L61)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I thought class variables have trailing underscores.
</blockquote></details>

you are right!

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZFCXZ4i4j1Kju5YYd:-LFZLBEL3XtxoM9vk_ZR:b-7zz0w) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L165)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I do not understand why we need to multiply a factor of 2 here, maybe you could add some documentation?
</blockquote></details>

Error propagation, as you'd do in a real experiment. Since these tolerances are tightly chosen, we need the factor of two for these tests to pass. Added comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 6 files at r3, 2 of 5 files at r4.
Review status: 1 unresolved discussion, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZFCXZ4i4j1Kju5YYd:-LFZMdoKBgXSz-zAsaAt:by24bp7) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L165)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Error propagation, as you'd do in a real experiment. Since these tolerances are tightly chosen, we need the factor of two for these tests to pass. Added comment.
</blockquote></details>

Thanks for the explanation. That is very clear.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043)*

**Comment by amcastro-tri** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFZFCXZ4i4j1Kju5YYd:-LFbj309E9uhcxg8rNkB:bzfzt1u) ([raw file](https://github.com/robotlocomotion/drake/blob/2cf580bd92241680fd920ba17041f7d174be51ed/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L165)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks for the explanation. That is very clear.
</blockquote></details>

I'm glad it's better now, good question. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043)*

**Comment by amcastro-tri** [comment]
Review status: 2 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 947 at r5](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFcCwsL-362piFwGsnB:-LFcO8Iy3RGhEJXF5Rig:b-j2f7t6) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa98abee776908d0c6c368d702d04514cecf718/multibody/multibody_tree/multibody_plant/multibody_plant.h#L947)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This sets _all_ the solver parameters, not just the stiction tolerance. I think you should first copy all the existing parameters before modifying v_stiction ?
</blockquote></details>

Good catch. thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r6.
Review status: 3 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 734 at r5](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFcE9GL1TLtI_5_j6nt:-LFcQhok4U5B02uZlLMW:bszn258) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa98abee776908d0c6c368d702d04514cecf718/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L734)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Minor: this method has grown to 130+ lines long. Please break it up into a few logical chunks. 
</blockquote></details>

This comment got lost somehow.

---

*[multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc, line 168 at r6](https://reviewable.io/reviews/robotlocomotion/drake/9043#-LFcQIM627oFUbhk9Ram:-LFcQIM627oFUbhk9Ran:b9si036) ([raw file](https://github.com/robotlocomotion/drake/blob/fc73ed9da9cc931ee1d2cf8a97e07ede0ba87c31/multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc#L168)):*
> ```cpp
>   // allowance and stiction tolerance.
>   // Notice that given the kinematic relationship between linear and angular
>   // velocity v_WBcm = radius * W_WB at rolling, relative errors
> ```

Nit: lower case "w" for angular velocity.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043)*

**Comment by sherm1** [comment]
Platform :lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: 1 unresolved discussion, platform LGTM from [sherm1], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9043#-:-LFcTOSvDof1TC95y8gL:b8qx53o)*

**Pull request merged**
