### PR TITLE
Make sure the Hessian in the QuadraticConstraint is symmetric

### LINKED ISSUE #6791: QuadraticConstraint should store symmetric Q

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #6791

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6820)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-:-KrD4f_RkzDkG0rIWU6P:b-a98c4g)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-:-KrDJemPPL3ml0lWYnFH:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-:-KrDLFIHHqH4kzfQkvXF:b72l57d)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, modulo minor nits.
+@sherm1 for follow-up platform review, please.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/constraint.h, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrGgi3yxwL7XJ3to-I7:-KrGgi3zxDucyX-lhhEN:bio4qob) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L215)):*
> ```objc
> 
> /**
>  * lb <= .5 x'Qx + b'x <= ub
> ```

BTW Can you move the below comment about the symmetric `Q` up to the class description, and then just make a brief mention of symmetric-ness in the accessor?

---

*[drake/solvers/constraint.h, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrGp6YiIn2_glWOegUK:-KrGp6YiIn2_glWOegUL:bo4p00) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L221)):*
> NO_MOVE_NO_ASSIGN(QuadraticConstraint)
>  

---

*[drake/solvers/constraint.h, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrGguE7-z4a6K00F7gj:-KrGguE7-z4a6K00F7gk:b6o1qfv) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L224)):*
> ```objc
> 
>   template <typename DerivedQ, typename Derivedb>
>   QuadraticConstraint(const Eigen::MatrixBase<DerivedQ>& Q,
> ```

nit Can we delineate between the potentially non-symmetric `Q_0` / `Q_in` and the symmetric `Q` in the constructor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-:-KrGoxjs8ZC1k6uG0WUO:b-1e5wja)*

**Comment by EricCousineau-TRI** [comment]
*[drake/solvers/constraint.h, line 221 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrGp6YiIn2_glWOegUK:-KrGpEMeAWX4wUzMzkvy:b-n9z421) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L221)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

> NO_MOVE_NO_ASSIGN(QuadraticConstraint)
>  

</blockquote></details>

Er, sorry, This was a rogue comment. Will try to remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820)*

**Comment by sherm1** [comment]
Platform backup :lgtm: with one BTW, ptal.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/constraint.h, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrH06SlsYmUq6Z5hJat:-KrH06SlsYmUq6Z5hJau:b-lv0kmg) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L240)):*
> ```objc
>    * Notice that if the user constructs the constraint with a non-symmetric Q₀,
>    * then we return the symmetric matrix Q = (Q₀ + Q₀ᵀ) / 2, since
>    * xᵀQ₀x = xᵀQ₀ᵀx = xᵀ*(Q₀+Q₀ᵀ)/2 *x. The first equality holds because the
> ```

BTW That's a very cool and (to me) surprising result!

---

*[drake/solvers/test/constraint_test.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrH0Q3WY-pUlISAOB_R:-KrH0Q3WY-pUlISAOB_S:b-2pyt7r) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/test/constraint_test.cc#L22)):*
> ```cpp
>   Eigen::Matrix2d Q;
>   Eigen::Vector2d b;
>   Q << 1, 0, 0, 1;
> ```

BTW Consider formatting this:
```c++
Q << 1, 0,
     0, 1;
```
for clarity (and below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-:-KrH0pPIsW32VlWwLrjb:b-8rartw)*

**Comment by sherm1** [comment]
And there are still a couple of unresolved comments from @ericcousineau-tri.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-:-KrH1-Z9UtjJNiNwtNmZ:b-lm00ra)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/constraint.h, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrGgi3yxwL7XJ3to-I7:-KrILPoQuFhpFXvTq-xY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L215)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you move the below comment about the symmetric `Q` up to the class description, and then just make a brief mention of symmetric-ness in the accessor?
</blockquote></details>

Done.

---

*[drake/solvers/constraint.h, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrGguE7-z4a6K00F7gj:-KrILScYvoBRLM65vqog:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/constraint.h#L224)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Can we delineate between the potentially non-symmetric `Q_0` / `Q_in` and the symmetric `Q` in the constructor?
</blockquote></details>

Done.

---

*[drake/solvers/test/constraint_test.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6820#-KrH0Q3WY-pUlISAOB_R:-KrILdR2uBT7cxVzhGO8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e93ad15937df7e661b9569df5f864a913dae650a/drake/solvers/test/constraint_test.cc#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Consider formatting this:
```c++
Q << 1, 0,
     0, 1;
```
for clarity (and below).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6820)*

**Pull request merged**
