### PR TITLE
Fix a memory leak in gurobi_solver_internal_test

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21270)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@BetsyMcPhail for feature review. +@jwnimmer-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21270#-:-NujDg077zFUQnMtqJzi:bvjdlu0)* status: LGTM missing from assignees BetsyMcPhail,jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-continuous-everything-address-sanitizer please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: (pending CI results)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21270#-:-NujEnst1cfu2xFzbYMZ:b3f290r)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none) :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21270#-:-NujGUaO3yU-7nfUpf5U:ba9fj5z)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),BetsyMcPhail

**Pull request merged**
