### PR TITLE
Has value bugfix

### PR DESCRIPTION
**Pull request by edrumwri**
Addresses #14601

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701#-:-MUP42dW-M9_Nn2C7d-P:b-f384lj)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
@edrumwri somehow this has 13 commits with seemingly-unrelated descriptions. Can you tidy that up with a rebase to current master?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701#-:-MUP4ERcEqLhczB_Ju0g:b-mjzldw)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
@sherm1 As with any other PR, we can squash it into a good commit message as we merge it at the end.  I don't think reviewers generally should push back on the details of commit messages.  It's not like "Respond to Sherm's review comments" is a commit message that makes it to master, which is seen frequently in other PRs.

**Comment by sherm1** [comment]
My issue with this isn't the stylistic merit of the commits but their unrelated content -- I'm confused by that and it worries me. I don't have your confidence that I can deal with them on merge and would like to push that back to the author instead.

**Comment by jwnimmer-tri** [comment]
> ... I don't have your confidence that I can deal with them on merge ...

Let me reassure you that the "Squash and merge" feature always works, and always merges exactly the overall patch as shown in reviewable and github.

**Review by sherm1 — COMMENTED** [review]
BTW CI is failing -- looks like a linting problem.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701#-:-MUPM8d977lIWTKmp-AR:b-j50j18)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending CI and a minor comment.

+@ggould-tri for platform review per rotation, please

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701#-:-MUPROAzC_u18zgdrZtN:b3fy5hu)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri and @ggould-tri)

___
*[systems/framework/system_base.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPQF2T4G5-fVNUhTAD:-MUPQF2T4G5-fVNUhTAE:b-pq9ev9) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/system_base.cc#L192)):*
> ```cpp
>   if (get_parent_service() == nullptr) return nullptr;
> 
>   // If this is the root Context, our parent can't evaluate it.
> ```

nit: "the" -> "a"
___
*[systems/framework/test/input_port_test.cc, line 309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPMhVTCkBSHCE6UScV:-MUPMhVTCkBSHCE6UScW:b33zcyx) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L309)):*
> ```cpp
> }
> 
> // Tests that a system's input ports embedded in a Diagram can be queried and values fixed.
> ```

minor: this comment doesn't seem to capture what's really being tested here. How about something like "For a subsystem embedded in a diagram, test that we can query, fix, and evaluate that subsystem's input ports using only a Context for that subsystem (rather than the whole Diagram context)." ?
___
*[systems/framework/test/input_port_test.cc, line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPNJwI4UoqktrVP7ll:-MUPNJwJBj255shJbQwZ:b-muyuy1) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L334)):*
> ```cpp
>   system->int_port.FixValue(&*context, kIntValue);
>   system->double_port.FixValue(&*context, kDoubleValue);
>   system->string_port.FixValue(&*context, kStringValue);
> ```

BTW personally I _like_ the `&*` syntax for unique_ptr output arguments since we're using the Google-style "&-means-output" rule. However, in practice I found that our colleagues here find it horrifying and are very sad if I use it so I agreed to `context.get()` here instead, in the interest of diplomacy. I leave it to you and platform review to resolve.

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri, @ggould-tri, and @sherm1)

___
*[systems/framework/system_base.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPQF2T4G5-fVNUhTAD:-MUPUtI8EfXivYC47vJl:bk7s1nn) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/system_base.cc#L192)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "the" -> "a"
</blockquote></details>

There's only one, no?
___
*[systems/framework/test/input_port_test.cc, line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPNJwI4UoqktrVP7ll:-MUPUzse5YAbRwVn2drC:bvqucr7) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L334)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW personally I _like_ the `&*` syntax for unique_ptr output arguments since we're using the Google-style "&-means-output" rule. However, in practice I found that our colleagues here find it horrifying and are very sad if I use it so I agreed to `context.get()` here instead, in the interest of diplomacy. I leave it to you and platform review to resolve.
</blockquote></details>

Ok. I like it too. But will leave up to platform.

**Comment by ggould-tri** [comment]
___
*[systems/framework/test/input_port_test.cc, line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPNJwI4UoqktrVP7ll:-MUPTium4wR7FRrj1SvW:bmreptf) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L334)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Ok. I like it too. But will leave up to platform.
</blockquote></details>

The anonymity is a bit harsh:  As written this is something like (pseudocodish) `&(typeof(System::CreateDefaultContext())::operator*())` which is obscure (and even that is assuming that I know that the `*` is the place that operator overloading happens). 

I'd be okay with `&*` if the argument were a `unique_ptr`.  As it is an `auto`, however, I am at least in theory going to have to look up the documentation of of `System::CreateDefaultContext` to figure out why that isn't a no-op, which seems a bit much.  My inclination is to say, either say `unique_ptr` or say `get`, don't make the reader guess that someone somewhere is overloading `operator*`.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri)

___
*[systems/framework/system_base.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPQF2T4G5-fVNUhTAD:-MUPc2lSEbifgRmET8kN:biizdry) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/system_base.cc#L192)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

There's only one, no?
</blockquote></details>

No, you can have many Context objects for the same Diagram.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: but note my (non-binding, highly subjective) preference on the `&*` issue.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701#-:-MUPivv72vzhlCb9_zfo:bwxofy7)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @edrumwri and @sherm1)

___
*[systems/framework/test/input_port_test.cc, line 309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPMhVTCkBSHCE6UScV:-MUPimJb9iEACuAzuEiL:b9mltpx) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L309)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this comment doesn't seem to capture what's really being tested here. How about something like "For a subsystem embedded in a diagram, test that we can query, fix, and evaluate that subsystem's input ports using only a Context for that subsystem (rather than the whole Diagram context)." ?
</blockquote></details>

(also it is a long-line violation)

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[systems/framework/system_base.cc, line 192 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPQF2T4G5-fVNUhTAD:-MUPhgvb0tP1IDQyIgMV:blqlxci) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/system_base.cc#L192)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

No, you can have many Context objects for the same Diagram.
</blockquote></details>

Yes, but only one in a Context "tree". I find your wording confusing, like there are multiple within the same tree.
___
*[systems/framework/test/input_port_test.cc, line 309 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPMhVTCkBSHCE6UScV:-MUPmxL61xpbWC6XLs_N:b-ft0nnb) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L309)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

(also it is a long-line violation)
</blockquote></details>

Done. My VS Code decided to stop clang formatting a couple of folders. This is one of those. Works great in another one. Sigh. 
___
*[systems/framework/test/input_port_test.cc, line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14701#-MUPNJwI4UoqktrVP7ll:-MUPnADs5lZwsVp8CoJ3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc34fa9ba041adaa93f780ffe3dd9f4c4abb10ab/systems/framework/test/input_port_test.cc#L334)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The anonymity is a bit harsh:  As written this is something like (pseudocodish) `&(typeof(System::CreateDefaultContext())::operator*())` which is obscure (and even that is assuming that I know that the `*` is the place that operator overloading happens). 

I'd be okay with `&*` if the argument were a `unique_ptr`.  As it is an `auto`, however, I am at least in theory going to have to look up the documentation of of `System::CreateDefaultContext` to figure out why that isn't a no-op, which seems a bit much.  My inclination is to say, either say `unique_ptr` or say `get`, don't make the reader guess that someone somewhere is overloading `operator*`.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14701)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by sherm1** [comment]
Thanks for the fix, @edrumwri !

**Pull request merged**
