### PR TITLE
[workspace] Upgrade curl_internal to latest release curl-8_9_1

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #21759

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri could I ask you to take a look at this please, and push fix(es) for the build problems?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-O3Zy3cQ9Aj0EEZpzEMC:-O3Zy3cQ9Aj0EEZpzEMD:bwnk8g0) (no related file):*
So far, I can get `curl` to build, but tests fail:
```
rico@PUGET-255560:~/checkout/drake$ DISPLAY=:1 bazel test //...
INFO: Analyzed 12273 targets (1 packages loaded, 948 targets configured).
FAIL: //geometry/render_gltf_client:internal_http_service_curl_test (see /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/geometry/render_gltf_client/internal_http_service_curl_test/test.log)
INFO: From Testing //geometry/render_gltf_client:internal_http_service_curl_test:
==================== Test output for //geometry/render_gltf_client:internal_http_service_curl_test:
Using drake_cc_googletest_main.cc

[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HttpServiceCurlTest
[ RUN      ] HttpServiceCurlTest.PostForm
geometry/render_gltf_client/test/internal_http_service_curl_test.cc:64: Failure
Expected equality of these values:
  res_1.service_error_message.value()
    Which is: "Could not resolve hostname"
  "Couldn't resolve host name"

geometry/render_gltf_client/test/internal_http_service_curl_test.cc:90: Failure
Expected equality of these values:
  res_2.service_error_message.value()
    Which is: "Could not resolve hostname"
  "Couldn't resolve host name"

[  FAILED  ] HttpServiceCurlTest.PostForm (8 ms)
[----------] 1 test from HttpServiceCurlTest (8 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (8 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] HttpServiceCurlTest.PostForm

 1 FAILED TEST
================================================================================
INFO: Found 4427 targets and 7846 test targets...
INFO: Elapsed time: 1.245s, Critical Path: 0.46s
INFO: 92 processes: 92 linux-sandbox, 1 local.
INFO: Build completed, 1 test FAILED, 92 total actions
//geometry/render_gltf_client:internal_http_service_curl_test            FAILED in 0.0s
  /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/geometry/render_gltf_client/internal_http_service_curl_test/test.log

Executed 4 out of 7846 tests: 7845 tests pass and 1 fails locally.
```
Still investigating.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-O3Zy3cQ9Aj0EEZpzEMC:-O3_DUNR87JnQKCNxVNU:b-vsea3j) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So far, I can get `curl` to build, but tests fail:
```
rico@PUGET-255560:~/checkout/drake$ DISPLAY=:1 bazel test //...
INFO: Analyzed 12273 targets (1 packages loaded, 948 targets configured).
FAIL: //geometry/render_gltf_client:internal_http_service_curl_test (see /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/geometry/render_gltf_client/internal_http_service_curl_test/test.log)
INFO: From Testing //geometry/render_gltf_client:internal_http_service_curl_test:
==================== Test output for //geometry/render_gltf_client:internal_http_service_curl_test:
Using drake_cc_googletest_main.cc

[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HttpServiceCurlTest
[ RUN      ] HttpServiceCurlTest.PostForm
geometry/render_gltf_client/test/internal_http_service_curl_test.cc:64: Failure
Expected equality of these values:
  res_1.service_error_message.value()
    Which is: "Could not resolve hostname"
  "Couldn't resolve host name"

geometry/render_gltf_client/test/internal_http_service_curl_test.cc:90: Failure
Expected equality of these values:
  res_2.service_error_message.value()
    Which is: "Could not resolve hostname"
  "Couldn't resolve host name"

[  FAILED  ] HttpServiceCurlTest.PostForm (8 ms)
[----------] 1 test from HttpServiceCurlTest (8 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (8 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] HttpServiceCurlTest.PostForm

 1 FAILED TEST
================================================================================
INFO: Found 4427 targets and 7846 test targets...
INFO: Elapsed time: 1.245s, Critical Path: 0.46s
INFO: 92 processes: 92 linux-sandbox, 1 local.
INFO: Build completed, 1 test FAILED, 92 total actions
//geometry/render_gltf_client:internal_http_service_curl_test            FAILED in 0.0s
  /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/geometry/render_gltf_client/internal_http_service_curl_test/test.log

Executed 4 out of 7846 tests: 7845 tests pass and 1 fails locally.
```
Still investigating.
</blockquote></details>

BTW That just looks like the error message spelling changed, so the unit test could be updated to use the new goalpost?

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-O3Zy3cQ9Aj0EEZpzEMC:-O3bzUc00gY_N3GU7yJ_:b1mqwuj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW That just looks like the error message spelling changed, so the unit test could be updated to use the new goalpost?
</blockquote></details>

Ah, good. By the time I got the build working, I had timed out. Will push the fix and double check macos.

___

**Comment by mwoehlke-kitware** [comment]
*[`geometry/render_gltf_client/test/internal_http_service_curl_test.cc` line 66 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-O3c_WADAo_KarZK8so9:-O3c_WADAo_KarZK8soA:b-7l6v9y) ([raw file](https://github.com/RobotLocomotion/drake/blob/2f418f37ed96574dabb69542293ab6d46f487daa/geometry/render_gltf_client/test/internal_http_service_curl_test.cc#L66)):*
> ```cpp
>     EXPECT_TRUE(res_1.service_error_message.has_value());
>     EXPECT_THAT(res_1.service_error_message.value(),
>                 testing::ContainsRegex("Could.?n.t resolve host.?name"));
> ```

Shouldn't this use `MatchesRegex`? (Likewise for other instances.)



_Suggestion:_
```cpp
                testing::MatchesRegex("Could.?n.t resolve host.?name"));
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[`geometry/render_gltf_client/test/internal_http_service_curl_test.cc` line 66 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-O3c_WADAo_KarZK8so9:-O3ccEXMDVfJMBQUlZr4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2f418f37ed96574dabb69542293ab6d46f487daa/geometry/render_gltf_client/test/internal_http_service_curl_test.cc#L66)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Shouldn't this use `MatchesRegex`? (Likewise for other instances.)
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+@ggould-tri for platform review, by schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-:-O3ckzbg5WoYPCTSyEU3:b-80ao6c)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-:-O3csb3_AXZtsiV5wdbt:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> Dismissed @mwoehlke-kitware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21767#-:-O3cvsjw4fThdIQJhXLZ:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Pull request merged**
