### PR TITLE
clean up kalman documentation

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6963)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@naveenoid for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-:-KtEOlEelC7nQS7aMThq:b-6l9dhs)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/kalman_filter.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-KtMyj1GEXY61f9FUyUD:-KtMyj1GEXY61f9FUyUE:brswlf3) ([raw file](https://github.com/robotlocomotion/drake/blob/27bc7715b2abe9432a19b4099bda600ccbf89ead/drake/systems/estimators/kalman_filter.h#L65)):*
> ```objc
> ///
> /// Assuming @p system has the (continuous-time) dynamics:
> ///   dx/dṫ = f(x,u),g
> ```

BTW: Why is there a dot above the t? Seems like some sort of copy past artifact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-:-KtMywHs5TC1se3N7frw:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/kalman_filter.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-KtMyj1GEXY61f9FUyUD:-KtOmMCfw-jU1kAKzwea:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/27bc7715b2abe9432a19b4099bda600ccbf89ead/drake/systems/estimators/kalman_filter.h#L65)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Why is there a dot above the t? Seems like some sort of copy past artifact.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-:-KtOmaS-kVgQYNlPe-lC:b-ik3l1s)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/kalman_filter.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-KtPaMiqi_DIQtIIOET_:-KtPaMiqi_DIQtIIOETa:bksto9b) ([raw file](https://github.com/robotlocomotion/drake/blob/27bc7715b2abe9432a19b4099bda600ccbf89ead/drake/systems/estimators/kalman_filter.h#L65)):*
> ```objc
> ///
> /// Assuming @p system has the (continuous-time) dynamics:
> ///   dx/dṫ = f(x,u),g
> ```

BTW, I think the last `g` is a typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-:-KtPaukUy0lcBNTPrwAV:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/kalman_filter.h, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6963#-KtPaMiqi_DIQtIIOET_:-KtQWT8UPTK6HfxUJfcC:b59boa5) ([raw file](https://github.com/robotlocomotion/drake/blob/27bc7715b2abe9432a19b4099bda600ccbf89ead/drake/systems/estimators/kalman_filter.h#L65)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think the last `g` is a typo?
</blockquote></details>

:man_facepalming: Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6963)*

**Pull request merged**
