### PR TITLE
Updated Names of Model-Adding Methods

### PR DESCRIPTION
**Pull request by liangfok**
This builds upon #3043. It renames all of the methods that add models to the `RigidBodySystem` and its `RigidBodyTree`. It also adds a bunch of Doxygen comments.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3056)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KOIuO7m6PEYGcXSxv3Z:670272675)*

**Comment by liangfok** [comment]
All CI checks passed. Now waiting on #3043 to be merged before submitting this PR for review.

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KOLkHt9-MRQl7I5XzB_:-880011534)*

**Comment by liangfok** [comment]
+@amcastro-tri for feature review (you're the only non-platform reviewer who attended last Tuesday's meeting)
+@sherm1 for platform review (it's not Monday but you have direct knowledge of last Tuesday's meeting)

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KORDTMm7bx1mPiB2qqh:b-k8yp23)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KORILXiGx_bMD36coRk:670272675)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 15 of 25 files at r3, 2 of 4 files at r4, 1 of 11 files at r5, 1 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KORRuTQIpM0uQSkwwXG:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. I'm now waiting for @amcastro-tri's feature review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KORTrpnGCoXrz3P452M:b-o0nx53)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 15 of 25 files at r3, 2 of 4 files at r4, 1 of 11 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KOeKS3WE60_-ruQXi4z:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Just waiting on CI now. It's pretty silly we need to re-run the entire pre-merge CI build just due to a CHANGELOG.md conflict.

---

Review status: 18 of 19 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3056#-:-KOeQn3jpHPG64rFKv5B:bwdv24z)*

**Pull request merged**
