### PR TITLE
In automotive demo, fail-fast when processes die quickly or when vis hangs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4710)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-:-Ka2LrfomU3NumKkEPPZ:blnrywe)*

**Comment by liangfok** [comment]
I assume you mean "Fail-Fast" instead of "Fast-Fast"?

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka2jL5dGzZj5uNIZHkE:-Ka2jL5eE4bg-OzNhH4E:b-bbqsiv) ([raw file](https://github.com/robotlocomotion/drake/blob/56e4a83b413513bec41bc546eb42f7660a5c25cb/drake/automotive/automotive_demo.py#L80)):*
> ```Python
>         self.children.append(TrackedProcess(label, process))
> 
>         # Fail-fast on infant mortaility.
> ```

BTW: typo: "mortality".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka2jL5dGzZj5uNIZHkE:-Ka2jpm05tBu4Bhy7CYh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/56e4a83b413513bec41bc546eb42f7660a5c25cb/drake/automotive/automotive_demo.py#L80)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: typo: "mortality".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-:-Ka2n1WKlyiZBjWbY1zW:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka3JrXi_ApeWpxGd_45:-Ka3JrXi_ApeWpxGd_46:b-x1ld5z) ([raw file](https://github.com/robotlocomotion/drake/blob/56e4a83b413513bec41bc546eb42f7660a5c25cb/drake/automotive/automotive_demo.py#L175)):*
> ```Python
>         while True:
>             if time.time() - start_time > 10.:
>                 raise RuntimeError("Timeout waiting for viewer")
> ```

BTW, This message, while not exactly wrong, assumes much more than the spec. of the function does.

consider instead something like:

 "Timeout waiting for message on channel %s" % channel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka3JrXi_ApeWpxGd_45:-Ka3MgCNfAcizkV2rspT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/56e4a83b413513bec41bc546eb42f7660a5c25cb/drake/automotive/automotive_demo.py#L175)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, This message, while not exactly wrong, assumes much more than the spec. of the function does.

consider instead something like:

 "Timeout waiting for message on channel %s" % channel
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka3RAETYIW6DFc6xOuy:-Ka3RAEUP1cSifNZ01jt:b-o0xrm) ([raw file](https://github.com/robotlocomotion/drake/blob/00e16b3953ae0d1c46b9f6f8be96ea3fc5fe7fe9/drake/automotive/automotive_demo.py#L176)):*
> ```Python
>             if time.time() - start_time > 10.:
>                 raise RuntimeError(
>                     "Timeout waiting for on channel %s" % channel)
> ```

confusing/confused grammar "for on"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/automotive_demo.py, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka3RAETYIW6DFc6xOuy:-Ka3SZE_Up6_wQW556wL:b9nhx0h) ([raw file](https://github.com/robotlocomotion/drake/blob/00e16b3953ae0d1c46b9f6f8be96ea3fc5fe7fe9/drake/automotive/automotive_demo.py#L176)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

confusing/confused grammar "for on"
</blockquote></details>

Yeah, sorry!  Just noticed the same thing a moment ago while rebasing.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-:-Ka3Wh-SLpuyvgLxPOvu:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-:-Ka3YfX8raH-d9aAqFWi:bppyoqq)*

**Comment by sherm1** [comment]
Platform: :lgtm:, with a couple of ignorable BTWs.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 81 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka47YF64UWzs48sTwE-:-Ka47YF64UWzs48sTwE0:bz6o4j8) ([raw file](https://github.com/robotlocomotion/drake/blob/40914ca21938f3e46a5f4d050c17c3aca13a205b/drake/automotive/automotive_demo.py#L81)):*
> ```Python
> 
>         # Fail-fast on infant mortality.
>         time.sleep(0.05)
> ```

BTW, there are three hard-coded times here: 50ms allotted for infant mortality, 10s timeout, and 100ms select interval. I'm OK with that in a demo but please consider whether these ought to be symbolic constants instead.

---

*[drake/automotive/automotive_demo.py, line 176 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka483RB4iYdl7k19B3f:-Ka483RB4iYdl7k19B3g:b-jwinfb) ([raw file](https://github.com/robotlocomotion/drake/blob/40914ca21938f3e46a5f4d050c17c3aca13a205b/drake/automotive/automotive_demo.py#L176)):*
> ```Python
>             if time.time() - start_time > 10.:
>                 raise RuntimeError(
>                     "Timeout waiting for channel %s" % channel)
> ```

BTW, consider including the timeout length in the message, "10s timeout waiting for channel ..." -- avoids the hunt to see whether the timeout was simply set too short.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-:-Ka48QK9RmFFOr5lNFLO:b-mxocc7)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 81 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka47YF64UWzs48sTwE-:-Ka4jELOAdELgYIr84su:b-gta54s) ([raw file](https://github.com/robotlocomotion/drake/blob/40914ca21938f3e46a5f4d050c17c3aca13a205b/drake/automotive/automotive_demo.py#L81)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, there are three hard-coded times here: 50ms allotted for infant mortality, 10s timeout, and 100ms select interval. I'm OK with that in a demo but please consider whether these ought to be symbolic constants instead.
</blockquote></details>

Is this more along the lines of you're wondering if they have invariants between them?  Or that their meanings are too obscure?  I don't think users would (or should) tune them, if that's what you meant.

It's okay if the mortality check doesn't find the problem 100% of the time, we'll still get a diagnostic output saying "failure to launch" and we'll give up waiting after 10 seconds.

---

*[drake/automotive/automotive_demo.py, line 176 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka483RB4iYdl7k19B3f:-Ka4jdBgqeXPNl4jcmcD:bk4jlth) ([raw file](https://github.com/robotlocomotion/drake/blob/40914ca21938f3e46a5f4d050c17c3aca13a205b/drake/automotive/automotive_demo.py#L176)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, consider including the timeout length in the message, "10s timeout waiting for channel ..." -- avoids the hunt to see whether the timeout was simply set too short.
</blockquote></details>

Having worked with this demo for a while over the months, to me at least its pretty clear to a user what's happening here.  The 10s guard is about an order of magnitude over what the visualizer typically needs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 81 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4710#-Ka47YF64UWzs48sTwE-:-Ka5dS7sYHI3eXdMpm0z:b-hnepef) ([raw file](https://github.com/robotlocomotion/drake/blob/40914ca21938f3e46a5f4d050c17c3aca13a205b/drake/automotive/automotive_demo.py#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is this more along the lines of you're wondering if they have invariants between them?  Or that their meanings are too obscure?  I don't think users would (or should) tune them, if that's what you meant.

It's okay if the mortality check doesn't find the problem 100% of the time, we'll still get a diagnostic output saying "failure to launch" and we'll give up waiting after 10 seconds.
</blockquote></details>

My comment didn't have any hidden profundity -- I was just pointing out that there are magic constants sprinkled around here to make sure you had thought about them. I'm satisfied if you have.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4710)*

**Pull request merged**
