### PR TITLE
Zapped "using" statement from RBM header

### PR DESCRIPTION
**Pull request by psiorx**
It's generally a bad idea to put using namespace statements in header files.  

This removes the 'using namespace Eigen' line from RigidBodyManipulator.h and fixes the comical number of places that relied on it being there.

This should also fix the problems @rdeits was having with SWIG having trouble with it.

### CODE REVIEW

**Comment by rdeits** [comment]
:+1: awesome :smile:

**Comment by psiorx** [comment]
The windows build failed before it even got to Drake.  Looks like it's having trouble getting through LCM.

**Comment by psiorx** [comment]
@rdeits just pointed out that there's one file (QPCommon.h) that should have broken with these changes but neither I nor drake006 caught it.  For me, it was because I was compiling without gurobi enabled.  

Does that mean drake006 is also compiling without gurobi?

**Comment by rdeits** [comment]
From the drake006 output, it looks like a lot of dependencies are no longer present: 

```
66 cancelled (with missing dependencies  SDPSolver:10, SNOPT:5, avl:4, gloptipoly3:3, gurobi:15, iris:10, mosek:11, octomap:2, sedumi:3, snopt:1, yalmip:2)
```

**Comment by RussTedrake** [comment]
crap.  i’m sure that’s my fault.  just pushed the updated course notes, but will look at this in the morning.

**Comment by RussTedrake** [comment]
i've fixed the "not-all-externals" logic.  pull request coming.  the is_public logic was not quite correct.

**Pull request merged**
