### PR TITLE
Make make_arm_controller_model externally accessible

### PR DESCRIPTION
**Pull request by zachfang**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17984)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review. Thanks!

From the discussion in Anzu 9323, `make_arm_controller_model()` needs to be accessible (even though `internal`) before we replace it with something else. Let me know if otherwise.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17984#-:-ND-S7FD-kz8C9JIFOCB:b-apjth4)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok).

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17984#-:-ND3U6Hf-riCsPRReq0J:b-fl40af)* status: 2 unresolved discussions (waiting on @zachfang)

___
*[`bindings/pydrake/manipulation/kuka_iiwa_py.cc` line 153 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17984#-ND3V0A1C7agAGndc0r1:-ND3V0A23MLj-xqhHO4A:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/1eb0f59cbfa9b6309dadc73150893463d388d140/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L153)):*
> ```cpp
>         py::arg("builder"), py::arg("ext_joint_filter_tau") = 0.01,
>         py::arg("desired_iiwa_kp_gains") = std::nullopt,
>         // Keep alive, ownership: `builder` keeps `controller_plant` alive.
> ```

typo



_Suggestion:_
```cpp
reference
```
___
*[`bindings/pydrake/manipulation/kuka_iiwa_py.cc` line 154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17984#-ND3UzT94eUAguAXYd4B:-ND3UzTA8UKZY1CZEpIp:b-vrwv6y) ([raw file](https://github.com/robotlocomotion/drake/blob/1eb0f59cbfa9b6309dadc73150893463d388d140/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L154)):*
> ```cpp
>         py::arg("desired_iiwa_kp_gains") = std::nullopt,
>         // Keep alive, ownership: `builder` keeps `controller_plant` alive.
>         py::keep_alive<5, 3>(), doc.BuildIiwaControl.doc);
> ```

Yikes!  The unusual reference lifetime _definitely_ needs to be mentioned in the API docs for `BuildIiwaControl()`, like it is for `InverseDynamicsController`.

Here's how the `InverseDynamicsController` explains it (their `plant` is our `controller_plant` in this case):

```
   * The %InverseDynamicsController holds an internal, non-owned reference to
   * the MultibodyPlant object so you must ensure that `plant` has a longer
   * lifetime than `this` %InverseDynamicsController.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17984)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`manipulation/kuka_iiwa/build_iiwa_control.h` line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17984#-ND465xQ2VCA5X3Kh0UO:-ND465xR2qzrLUvjPawp:b-bpv145) ([raw file](https://github.com/robotlocomotion/drake/blob/758b89078df965dcf3e30941a5b4a2f5e9731f42/manipulation/kuka_iiwa/build_iiwa_control.h#L50)):*
> ```objc
> /// Note: This function constructs an InverseDynamicsController that holds an
> /// internal, non-owned reference to `controller_plant`, so you must ensure that
> /// `controller_plant` has a longer lifetime than the InverseDynamicsController.
> ```

The user probably won't know what the lifetime of the IDC means to them.  At minimum, we should use the suggestion below (i.e., the lifetime they _know_ about is that of the diagram, not the controller).

Or, here's a completely different phrasing if you prefer it:

_"Note for C++ users: The Diagram will maintain an internal reference to `controller_plant`, so you must ensure that `controller_plant` has a longer lifetime than the Diagram."_



_Suggestion:_
```objc
diagram
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17984)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`manipulation/kuka_iiwa/build_iiwa_control.h` line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17984#-ND465xQ2VCA5X3Kh0UO:-ND48Nm02vTupNp8ssyM:b-lzsrj7) ([raw file](https://github.com/robotlocomotion/drake/blob/758b89078df965dcf3e30941a5b4a2f5e9731f42/manipulation/kuka_iiwa/build_iiwa_control.h#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The user probably won't know what the lifetime of the IDC means to them.  At minimum, we should use the suggestion below (i.e., the lifetime they _know_ about is that of the diagram, not the controller).

Or, here's a completely different phrasing if you prefer it:

_"Note for C++ users: The Diagram will maintain an internal reference to `controller_plant`, so you must ensure that `controller_plant` has a longer lifetime than the Diagram."_

</blockquote></details>

Done. Thanks, I was searching a better wording.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17984)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @zachfang)

**Pull request merged**
