### PR TITLE
[pydrake] StartMeshcat uses NginX when on Deepnote

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Refactor ngrok support into its own helper function.
Display the URL using a clickable link.

Towards #13683.

Requires:
- [x] #16804

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16805)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @RussTedrake in case you'd like to look.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16805#-:-MyJC2pUAwk4CLuAOAH8:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16805#-:-MyJWBkf9cCrbSLtXsQo:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/_geometry_extra.py, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16805#-MymBJc14v1W8-_hDer3:-MymBJc25wOgv0MJqG0A:bgg8h1i) ([raw file](https://github.com/robotlocomotion/drake/blob/0577a5f62f79a3248a7159a351f55649f75bdf8b/bindings/pydrake/_geometry_extra.py#L98)):*
> ```Python
>     meshcat = Meshcat()
>     url = meshcat.web_url()
>     print("Meshcat URL: {url}")
> ```

This line is broken.  (you forgot to make it an f-string).  currently it just prints ```Meshcat URL: {url}``` to the screen.

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/_geometry_extra.py, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16805#-MymBJc14v1W8-_hDer3:-MymCT4ZCa_44HsypFST:b-vvobsb) ([raw file](https://github.com/robotlocomotion/drake/blob/0577a5f62f79a3248a7159a351f55649f75bdf8b/bindings/pydrake/_geometry_extra.py#L98)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This line is broken.  (you forgot to make it an f-string).  currently it just prints ```Meshcat URL: {url}``` to the screen.
</blockquote></details>

More accurately, it currently prints
```
INFO:drake:Meshcat listening for connections at http://localhost:7000
Meshcat URL: {url}
```
Previously, the new URL was only printed to the screen when needed, and in that case, the log message was suppressed.  This PR broke that flow, too.

**Pull request merged**
