### PR TITLE
framework: Ports should be self-service

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a WIP prototyping branch for now.  Pushing to Drake for visibility / discussion.

This was motivated by my recent work with IIWA examples, in the systems framework.  The boilerplate is still too much.  I suspect that this will be one useful improvement.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10592)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This my new proposed API for InputPort::Eval and OutputPort::Eval.

No more EvalAbstract, EvalEigen, EvalAbstractInput, EvalEigenVectorInput, EvalInputValue, etc., etc.  No more asking a System to Eval something -- you can only ask the Port object to do an Eval, for both inputs and outputs.

By default the Eval() gives you an Eigen reference.  If you do `Eval<Thing>` you get a Thing instead (where Thing is the port type) -- and that works automatically for both in case of abstract `Value<Thing>` or vector `Thing : public BasicVector` subclass.

Eval on a disconnected input is an error message (from the framework) -- use InputPort::EvalOptional if you want to handle the nulls yourself.  Output ports can't have nulls.

In pydrake, when you call Eval you just get whatever Thing was in the port, without mentioning any template argument.  If it was a vector port, you get a numpy.

---

image
image

**Comment by sherm1** [comment]
I like this a lot. One comment:
> Eval on a disconnected input is an error message (from the framework) -- use InputPort::EvalOptional if you want to handle the nulls yourself. Output ports can't have nulls.

Rather than have this parallel API to Eval(), I would prefer a single API like `input_port.has_value()` that a user could call to determine whether they dare call Eval().

**Comment by jwnimmer-tri** [comment]
Yes, that's probably better.  It's used so rarely that we don't need it to be elegant.  I will give it a spin in the entirety of using-code and see the net result.

**Comment by jwnimmer-tri** [comment]
> I would prefer a single API like `input_port.has_value()` ...

Done.  Indeed, that is much better, thanks.

I had to do `HasValue()` though -- plumbing through an O(1) has_value check that leaves connected-but-stale values intact seemed too much to take on here.  My guess is that anyone asking HasValue is about to call Eval anyway, so CamelCase isn't a big deal.

**Comment by SeanCurtis-TRI** [comment]
I'm with everyone else, it's nice to see this simplification.

What do the errors look like if: a) I've got an abstract-valued port that I forget to specify the type on my call to `Eval` and b) if I specify the wrong abstract type? More particularly, how well will these errors point to the actual location of the error? (i.e., at the `Eval()` call site instead of at the `AbstratValue::Get()` site?)

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI I've been working on writing up all the unit tests -- just pushed the latest.  It has some examples of errors for vector-valued ports.  Short answer is yes, errors are very clear (showing the expected vs actual types, port name, system name, etc.) and that their backtrace would flow through the Port::Eval that was misphrased.

**Comment by jwnimmer-tri** [comment]
+@sherm1 to start feature review, please.  For now, please review `//systems/**` only -- there are still a few minor adjustments pending on the Python stuff.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review of _some files_ please -- can you take the files that do **not** start with `//systems/...`?  So review bindings/..., examples/..., etc.

**Comment by EricCousineau-TRI** [comment]
FYI I actually ran into a case where I'd like this feature - thanks!
(Would like to not have to wire up a diagram for every camera that I want to tinker with; would be nice to just isolate in its own little block and mock the inputs in, so that I don't have to reconstruct the upstream plant and everything else.)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule (tomorrow), please.

**Pull request merged**
