### PR TITLE
Fix installed names of jars

### PR DESCRIPTION
**Pull request by jamiesnape**
Among other things, convention is to name lcmtypes libraries with a prefix `lcmtypes_`, and a few tools rely on this (especially with respect to jars).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6397)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm-create-cps.py, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6397#-KnAIinWbrRo5OvAaDYS:-KnAIinWbrRo5OvAaDYT:bdqvwp9) ([raw file](https://github.com/robotlocomotion/drake/blob/820bb5f948f15930aa8af4cbb6958e33e5eb5422/tools/lcm-create-cps.py#L31)):*
> ```Python
>     "lcm-java": {
>       "Type": "jar",
>       "Location": "@prefix@/share/java/lcm.jar"
> ```

:champagne: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6397#-:-KnAJHgggEdzP9muo5AH:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6397#-:-KnAj-4SuRs2OfdbGbCc:bnfp4nl)*

**Pull request merged**
