### PR TITLE
Remove linkstatic boilerplate.

### LINKED ISSUE #5104: Bazel "linkstatic" should be de-boilerplated
We should zap `linkstatic = 1` throughout Drake, then add back the ones that are actually necessary, with explanatory comments.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #5104.

@jwnimmer-tri for both levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5153)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5153#-Kct91-VuBsd_E3Emju1:-Kct91-YvxBWwnWpJRjC:b-9vw4mp) (no related file):*
This PR removes `linkstatic = 1` from call sites, but adds `linkstatic = 1` only for `cc_binary`.  I think most binary call sites did _not_ already use `linkstatic = 1`, but most library call sites _did_ use `linkstatic =  1` but this PR undoes that.

I am curious to hear if those changes an intentional or an oversight?

Depending on that answer, I would also likely slightly prefer a first PR that just de-duplicates the logic but keeps the effective build rules (mostly) unchanged, and then a second PR that flips the defaults.

---

*[tools/drake.bzl, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5153#-Kct9bIAsczro4sIWD97:-Kct9bIAsczro4sIWD98:bmy9bv4) ([raw file](https://github.com/robotlocomotion/drake/blob/88d170112b9152a58a3bc6bdc2152efe516458dc/tools/drake.bzl#L56)):*
> ```Python
>         linkstatic=1,
>         **kwargs):
>     """Creates a rule to declare a C++ binary."""
> ```

Probably the docs should explain the linker default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5153)*

**Comment by david-german-tri** [comment]
Review status: 0 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5153#-Kct91-VuBsd_E3Emju1:-KctAljJ_zlz4bmMW_R4:brsev77) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR removes `linkstatic = 1` from call sites, but adds `linkstatic = 1` only for `cc_binary`.  I think most binary call sites did _not_ already use `linkstatic = 1`, but most library call sites _did_ use `linkstatic =  1` but this PR undoes that.

I am curious to hear if those changes an intentional or an oversight?

Depending on that answer, I would also likely slightly prefer a first PR that just de-duplicates the logic but keeps the effective build rules (mostly) unchanged, and then a second PR that flips the defaults.
</blockquote></details>

No, that's a mistake, and explains the CI failure.  Will close this and start over.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5153)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5153#-Kct91-VuBsd_E3Emju1:-KctAwVZFGOJB1BWTSQe:br69az3) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

No, that's a mistake, and explains the CI failure.  Will close this and start over.
</blockquote></details>

This one is fairly close to being feature-neutral.  Just needs some`drake.bzl` edits, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5153)*

**Pull request closed without merging**
