### PR TITLE
Add LorentzCone constraint using non-symbolic form in HPolyhedron.

### PR DESCRIPTION
**Pull request by hongkai-dai**
We have fixed the duplicated variable issue in the solvers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502#-:-NKVMF_XEf9NkxxOJsNb:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
*[`geometry/optimization/hpolyhedron.cc` line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18502#-NKooqFv5f5t1R4S6gwu:-NKooqFw8hcuSAz_kGDK:bhla1w7) ([raw file](https://github.com/robotlocomotion/drake/blob/79eed6bc37998e782ca729d8e906b24b6e2cffbe/geometry/optimization/hpolyhedron.cc#L186)):*
> ```cpp
>   for (int i = 0; i < b_.size(); ++i) {
>     A_lorentz.setZero();
>     b_lorentz.setZero();
> ```

this one is unnecessary.

**Review by RussTedrake — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502#-:-NKopjdJ1eUm2FydvU4c:bg7igkv)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`geometry/optimization/hpolyhedron.cc` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18502#-NKopBIH-kqz4fmcxDom:-NKopBIH-kqz4fmcxDon:b-1ctclw) ([raw file](https://github.com/robotlocomotion/drake/blob/79eed6bc37998e782ca729d8e906b24b6e2cffbe/geometry/optimization/hpolyhedron.cc#L187)):*
> ```cpp
>     A_lorentz.setZero();
>     b_lorentz.setZero();
>     A_lorentz.block(0, 0, 1, C.cols()) = -A_.row(i);
> ```

nit: it would be clearer (at least to me) to use d.rows() instead of C.cols() here even though they must be equivalent. or at least comment that C.cols() == d.rows(), since you do use that fact in the for loop below.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/optimization/hpolyhedron.cc` line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18502#-NKooqFv5f5t1R4S6gwu:-NKp351b13E6PuuRO6uZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/79eed6bc37998e782ca729d8e906b24b6e2cffbe/geometry/optimization/hpolyhedron.cc#L186)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this one is unnecessary.
</blockquote></details>

Done.
___
*[`geometry/optimization/hpolyhedron.cc` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18502#-NKopBIH-kqz4fmcxDom:-NKp3Imy1v0g24gqaFMS:bqm93du) ([raw file](https://github.com/robotlocomotion/drake/blob/79eed6bc37998e782ca729d8e906b24b6e2cffbe/geometry/optimization/hpolyhedron.cc#L187)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: it would be clearer (at least to me) to use d.rows() instead of C.cols() here even though they must be equivalent. or at least comment that C.cols() == d.rows(), since you do use that fact in the for loop below.
</blockquote></details>

I changed it to `A_.cols()` as the right hand side of the assignment is `-A_.row(i)` with size A_.cols().

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`geometry/optimization/hpolyhedron.cc` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18502#-NKopBIH-kqz4fmcxDom:-NKp3rf65qgOM3Umdu1W:b-dgwfu0) ([raw file](https://github.com/robotlocomotion/drake/blob/79eed6bc37998e782ca729d8e906b24b6e2cffbe/geometry/optimization/hpolyhedron.cc#L187)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I changed it to `A_.cols()` as the right hand side of the assignment is `-A_.row(i)` with size A_.cols().
</blockquote></details>

that looks good.  can you do that in the loop below, too?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`geometry/optimization/hpolyhedron.cc` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18502#-NKopBIH-kqz4fmcxDom:-NKp86APAl5NBS5oniGy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/79eed6bc37998e782ca729d8e906b24b6e2cffbe/geometry/optimization/hpolyhedron.cc#L187)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that looks good.  can you do that in the loop below, too?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502#-:-NKsVB7s49NUnyvPODhl:b8asji7)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18502#-:-NKsgFwY2xVEHyUFUYv-:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
