### PR TITLE
fix a param parsing bug.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5168)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please

**Comment by BetsyMcPhail** [comment]
:lgtm: (assuming bazel-experimental-everything passes)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5168#-:-Kcy4uZgpKyKXGwoPwpk:b47i6k9)*

**Comment by BetsyMcPhail** [comment]
+@david-german-tri for platform review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5168#-:-Kcy4SfXk3ItvaEdhTXz:b-buchyz)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5168#-:-Kcy9Ou2Od8bZFthxXL8:bnfp4nl)*

**Pull request merged**
