### PR TITLE
Changes the constraints interface for "cfm" ...

### PR DESCRIPTION
**Pull request by edrumwri**
...by removing the "cfm" parameter, modifying the constraint equations instead.

The status quo in the constraint solver has been to require the cfm parameter at the start of the solution process, which has been a metaphorical ax in place of a scalpel. This PR changes the framework by permitting unilateral constraints to be softened with individualized stiffness and damping parameters.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7187)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please (updates are identical to those in #7055)

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-:-KvcYBo2EwD8fihOesMB:ble6s7q)*

**Comment by sherm1** [comment]
Some minor BTWs, then :lgtm:.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/constraint/constraint_problem_data.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjCoQ8vO6mRsNWeTz:-KvcjCoR77KOKbgbWCEn:by0fn2u) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L210)):*
> ```objc
> 
>   // TODO(edrumwri): define this quantity properly (documentation forthcoming).
>   /// This ℝᴺ vector represents the diagonal matrix γᴺ.
> ```

BTW copypasta (should be E)

---

*[drake/multibody/constraint/constraint_problem_data.h, line 256 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjNFweVtjnJDm2lne:-KvcjNFweVtjnJDm2lnf:b-gdgukt) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L256)):*
> ```objc
> 
>   // TODO(edrumwri): define this quantity properly (documentation forthcoming).
>   /// This ℝˢ vector represents the diagonal matrix γˢ.
> ```

BTW is "s" right here (was expecting L)?

---

*[drake/multibody/constraint/constraint_problem_data.h, line 436 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjUwxfNoM3Xey4iul:-KvcjUwxfNoM3Xey4ium:bmbrw49) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L436)):*
> ```objc
> 
>   // TODO(edrumwri): define this quantity properly (documentation forthcoming).
>   /// This ℝᴺ vector represents the diagonal matrix γᴺ.
> ```

BTW N->E?

---

*[drake/multibody/constraint/constraint_problem_data.h, line 482 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjYG83Ado1yeI_-vY:-KvcjYG83Ado1yeI_-vZ:b4yv67a) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L482)):*
> ```objc
> 
>   // TODO(edrumwri): define this quantity properly (documentation forthcoming).
>   /// This ℝˢ vector represents the diagonal matrix γˢ.
> ```

BTW is s right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-:-KvcmsnqPMy_VVxxSkUQ:b5gp1hv)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/constraint/constraint_problem_data.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjCoQ8vO6mRsNWeTz:-Kvct3svuesyqIYYHDNX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L210)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW copypasta (should be E)
</blockquote></details>

Done.

---

*[drake/multibody/constraint/constraint_problem_data.h, line 256 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjNFweVtjnJDm2lne:-KvctI44-s0DP0d9SRy8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L256)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is "s" right here (was expecting L)?
</blockquote></details>

Done.

---

*[drake/multibody/constraint/constraint_problem_data.h, line 436 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjUwxfNoM3Xey4iul:-KvctKEI66weMXKIUOKE:bh3s0ql) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L436)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW N->E?
</blockquote></details>

BTW You caught some copypasta, but it should be "y" (the number of non-sliding contacts).

---

*[drake/multibody/constraint/constraint_problem_data.h, line 482 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-KvcjYG83Ado1yeI_-vY:-KvctbO4qVgX3t56Mo6t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a0eb8e89460c6ab35c12dea81dac00a4a3fc4f75/drake/multibody/constraint/constraint_problem_data.h#L482)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is s right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187)*

**Comment by edrumwri** [comment]
+@ggould-tri for platform review please

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-:-KvcwK56uElCBZHp0GnT:bffmgsm)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187)*

**Comment by ggould-tri** [comment]
This looks conceptually correct to me.  I have a couple of concerns before I lgtm it.

First, I am bothered by the loss of the nonnegative check.  I would expect that every element of each gamma should be nonnegative (or possibly strictly positive?).  Is there a reason not to assert this?  Alternatively if you mean to support negative elements in gammas then perhaps test that case.

Second, I am also unsure that the test coverage here gets to the meat of the change.  Is it testing cases where the members of gamma are different?  If so I have failed to see it.

Can you reassure me here?

---

Reviewed 2 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-:-Kvd6wKlJhe6s0LKe9k3:bg62wpc)*

**Comment by edrumwri** [comment]
Grant, I have added a non-negativity check.

It is indeed using the various members of gamma, but if you mean setting coefficients differently for different constraints- no, it is not. If the current tests pass *but wouldn't if the coefficients were (markedly) different*, what would that imply? We haven't yet established the theory for me to be able to say: we have yet to ever test this capability on any systems for which data is recorded, and I'm unaware of anyone who has tried this approach so that I could ask how they tested it.

The new capability, which sets all of these values to a single constant ("cfm") on our example problems, is identical to the current capability, which simply uses that single constant in place of the vectors. So we shouldn't have a change in functionality, and I hope you'll agree that the current tests reflect that.

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-:-KvdO1WOEXOvLYwPwytj:b-7wumb5)*

**Comment by ggould-tri** [comment]
Ah, I hadn't cottoned to the fact that setting the members of gamma differently wasn't possible through this api.  Quite right!  :lgtm: 

---

Reviewed 1 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7187#-:-KvgbPQk0k6s-Hnwj2Wa:b-qe9t6j)*

**Pull request merged**
