### PR TITLE
[solvers] print MathematicalProgram

### PR DESCRIPTION
**Pull request by RussTedrake**
I found this quite useful when I was debugging my programs.  I thought I would contribute it, rather than let it get lost in a branch.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370#-:-MeM2MwH8hCTwUXLqywg:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: thanks for adding this feature!

+@seancurtis-tri for platform review please, thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370#-:-MeO39zB2urtmGo-fEnL:bck4d2d)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[solvers/mathematical_program.h, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15370#-MeO2K5C4mBkyk-x-2tR:-MeO2K5C4mBkyk-x-2tS:b9xb8cg) ([raw file](https://github.com/robotlocomotion/drake/blob/7329c416d23396a67d6879975ddbb207bcf03556/solvers/mathematical_program.h#L175)):*
> ```objc
>   /**
>    * Returns string representation of this program, listing the decision
>    * variables, costs, and constraints.
> ```

Could you document here that we don't guarantee that each variable has a unique name? It is the user's responsibility to make sure that when he/she specifies the variable name, he/she gives them unique names. If the users specify different variables with the same name, and that can be confusing in the print out.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[solvers/mathematical_program.h, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15370#-MeO2K5C4mBkyk-x-2tR:-MePYflJ2jIg0ptRnx-0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7329c416d23396a67d6879975ddbb207bcf03556/solvers/mathematical_program.h#L175)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document here that we don't guarantee that each variable has a unique name? It is the user's responsibility to make sure that when he/she specifies the variable name, he/she gives them unique names. If the users specify different variables with the same name, and that can be confusing in the print out.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@seancurtis-tri +@ggould-tri (platform review switcheroo).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370#-:-MePpvnN0grYuaQ0KXvF:b-sbf15l)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: and thank you -- we have a version of this in anzu and I look forward to figuring out how to get them into agreement.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370#-:-MeQXo9_-qYNjWKeG_uL:b-38ouwl)* status: 2 unresolved discussions (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/test/mathematical_program_test.cc, line 3343 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15370#-MeQXGzl5iGGys6Z2nBC:-MeQXGzm53zsh91OPKEs:bdrwqiv) ([raw file](https://github.com/robotlocomotion/drake/blob/508679853526a785c2ba292afa49e6d117b73393/solvers/test/mathematical_program_test.cc#L3343)):*
> ```cpp
>   EXPECT_THAT(s, testing::HasSubstr("Indeterminates"));
>   EXPECT_THAT(s, testing::HasSubstr("Cost"));
>   EXPECT_THAT(s, testing::HasSubstr("Constraint"));
> ```

minor:  A caller would probably expect the output to contain "x", "y", "2", and "3" as well, ie, strings that should passing through to `prog` rather than generic to all programs.

**Review by RussTedrake — COMMENTED** [review]
Great.  This version is unquestionably remedial.  But I hope that now that it exists, it can get more beautiful / informative relatively easily.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370#-:-MeQt_JK8pC_KxImHzJT:b-tflnmt)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @ggould-tri and @hongkai-dai)

___
*[solvers/test/mathematical_program_test.cc, line 3343 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15370#-MeQXGzl5iGGys6Z2nBC:-MeQtO4DDaYbv7r6UAu8:bcgnaiz) ([raw file](https://github.com/robotlocomotion/drake/blob/508679853526a785c2ba292afa49e6d117b73393/solvers/test/mathematical_program_test.cc#L3343)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  A caller would probably expect the output to contain "x", "y", "2", and "3" as well, ie, strings that should passing through to `prog` rather than generic to all programs.
</blockquote></details>

Done.  (quite literally).  I like that.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15370)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
