### PR TITLE
Templatizes on <T> the Kuka benchmark

### PR DESCRIPTION
**Pull request by amcastro-tri**
No new features in this PR. I simply templatize the Kuka arm benchmark so I can AutoDiffXd in future PR's.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7495)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
@ericcousineau-tri for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-:-Kz62UDMiRL5bVPKvEmO:bstduwn)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-Kz62Y31IwfYkblCEq4X:-Kz62Y31IwfYkblCEq4Y:bix03xi) (no related file):*
cc'ing @mitiguy 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495)*

**Comment by amcastro-tri** [comment]
+@ericcousineau-tri for feature review please (I forgot the + above)

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-:-Kz62zOuZTFDSoJ-Xzlp:b-4xpo5m)*

**Comment by amcastro-tri** [comment]
+@sherm1 for platform review please per regular rotation (it's 6pm here already and Sammy would hate me if I have this to him :-) ). 

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-:-Kz633lWHOLEY3icVOB9:baozp0u)*

**Comment by sherm1** [comment]
Platform :lgtm: with one BTW. You can count that as a feature review also if you want.

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-KzAF8eBTutJpDcB_laz:-KzAF8eBTutJpDcB_lb-:b634umd) ([raw file](https://github.com/robotlocomotion/drake/blob/93087727463f2111ae8395257e0792246d00e81d/drake/multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h#L82)):*
> ```objc
>   /// to this constructor, it means the gravity vector is directed opposite the
>   /// world upward z-unit vector (which is correct -- gravity is downward).
>   explicit DrakeKukaIIwaRobot(double gravity) {
> ```

BTW I see gravity is still double. Would it be better to templatize this also so you can AutoDiff with respect to gravity? Not too relevant for Earth-based objects but possibly an easy test case for AutoDiff'ed results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-:-KzAFZfr-xewhyep43eV:b2wo6ii)*

**Comment by sherm1** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-KzAF8eBTutJpDcB_laz:-KzAG4dyZBpIFcMHlQKm:b-ra1b5h) ([raw file](https://github.com/robotlocomotion/drake/blob/93087727463f2111ae8395257e0792246d00e81d/drake/multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h#L82)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I see gravity is still double. Would it be better to templatize this also so you can AutoDiff with respect to gravity? Not too relevant for Earth-based objects but possibly an easy test case for AutoDiff'ed results.
</blockquote></details>

BTW good idea, however right now we don't have an MBT parameter for it so I'll just keep it as a `double`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7495#-:-KzAbIjNRaCFW6bLOMCF:bnfp4nl)*

**Pull request merged**
