### PR TITLE
Bump minimum C++ version to C++14

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Bump minimum C++ version to C++14 and use make_unique.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2691)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@david-german-tri This passed pre-merge testing.  Would you like to platform review?

If anyone has suggestions for post-merge builds that are relevant, I'm all ears.

**Comment by jwnimmer-tri** [comment]
I think this fixes #2689.

**Comment by david-german-tri** [comment]
Well, that was vastly more straightforward than I expected.  Thanks for trying it!  :lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2691#-:-KLOBFkc9vcVpWo9PF0i:117717493)*

**Comment by jwnimmer-tri** [comment]
Yeah.  The C++14 support in GCC 4.9 is incomplete, but the portion that works we can use.
Once we have Ubuntu 16.04 up and running, we can re-evaluate whether GCC 4.9 is still holding us back.

I will merge this now, to get some feedback from the nightly builds.

**Comment by sherm1** [comment]
*[drake/systems/framework/value.h, line 101 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2691#-KLOCXQco3jYUJSNgbse:-KLOCXQco3jYUJSNgbsf:-931127132) ([raw file](https://github.com/robotlocomotion/drake/blob/dba30b30d09e7fd98441570fecc4fa7852a03e3b/drake/systems/framework/value.h#L101)):*
> ```objc
> 
>   std::unique_ptr<AbstractValue> Clone() const override {
>     return std::make_unique<Value<T>>(*this);
> ```

BTW: Ah, that's lovely! (comparatively anyway). Thanks, @jwnimmer-tri.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2691)*

**Pull request merged**
