### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Twin PR: https://github.com/RobotLocomotion/models/pull/51

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21227)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
(Holding off stamp until we update the sha and resolve CI.)

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21227#-:-NuPQT3x7jNdlGc_Uarm:b1tqh7a)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21227#-NuPQPlH5PG0Co6yk9EG:-NuPQPlH5PG0Co6yk9EH:b4j3nxc) (no related file):*
Good luck with CI...I hate those tests.

___
___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21227#-NuPO6kD86hgdX3ULUpl:-NuPQ0x81Fpa4_tdYJfh:b-nu6yx6) ([raw file](https://github.com/RobotLocomotion/drake/blob/a839c4c420a007e10c1e9fbb3bb7df5cf7c0f1d4/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs real sha
</blockquote></details>

We're ready for it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21227)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
Ready now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21227#-:-NuPWO9gB1Aqb4XEQ7Yh:bhurqze)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21227#-:-NuPZ0bN9qOWxX_ycwnv:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
