### PR TITLE
 pybind: Update to fix #8620 

### LINKED ISSUE #8620: pybind: Fix shape mismatch for `MatrixX<Variable>` vs. `MatrixX<double>`
@gizatt ran into this issue in https://github.com/RobotLocomotion/drake/pull/8615

When given a NumPy 1D vector of size N, `pybind11/eigen.h` will translate it to a Nx1 column vector for `dtype=float`, but will translate it to a 1xN row vector for `dtype=object`.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8620

Requires:
- [x] #8615 (will rebase when it lands)
- [x] https://github.com/RobotLocomotion/pybind11/pull/16

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8621)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@gizatt for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-:-LAKq_Fy2k1Q7LAno18r:b-e4ru6b)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tools/workspace/pybind11/repository.bzl, line 8 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-LAO-foe8-KX-OEhMlwv:-LAO-fof1ajpi8u9giSV:bnrvat) ([raw file](https://github.com/robotlocomotion/drake/blob/3574e91e4140b19469d5cda905e455e617c2d759/tools/workspace/pybind11/repository.bzl#L8)):*
> ```Python
> _REPOSITORY = "RobotLocomotion/pybind11"
> 
> # PR DRAFT(eric.cousineau): Update this when RobotLocomotion/pybind11#16 lands.
> ```

@ericcousineau-tri , FYI, I just lgtm-ed RobotLocomotion/pybind11#16.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 305 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-LAO05IuA0SI9EKNTUaV:-LAO05IuA0SI9EKNTUaW:b-kpg2it) ([raw file](https://github.com/robotlocomotion/drake/blob/3574e91e4140b19469d5cda905e455e617c2d759/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L305)):*
> ```Python
>         # 1d and 2d np arrays.
>         x0 = np.arange(6)
>         prog.SetInitialGuess(x, x0)
> ```

BTW, I understand that in general it's sufficient to check Python APIs by merely calling them. But since we have had this unexpected problem, I think it's worth using `GetInitialGuess` here to check things are set as expected. What do you think?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 305 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-LAO05IuA0SI9EKNTUaV:-LAOO7xT0S3J-UMXj7Qk:b-3xorhb) ([raw file](https://github.com/robotlocomotion/drake/blob/3574e91e4140b19469d5cda905e455e617c2d759/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L305)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I understand that in general it's sufficient to check Python APIs by merely calling them. But since we have had this unexpected problem, I think it's worth using `GetInitialGuess` here to check things are set as expected. What do you think?
</blockquote></details>

Done. Sounds good!

---

*[tools/workspace/pybind11/repository.bzl, line 8 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-LAO-foe8-KX-OEhMlwv:-LAOOBi36QwyOU77Jw8C:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/3574e91e4140b19469d5cda905e455e617c2d759/tools/workspace/pybind11/repository.bzl#L8)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@ericcousineau-tri , FYI, I just lgtm-ed RobotLocomotion/pybind11#16.
</blockquote></details>

OK Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621)*

**Comment by EricCousineau-TRI** [comment]
Rebased and all that jazz.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-:-LAOpGmQ-_anv8VQhqB8:bnfp4nl)*

**Comment by gizatt** [comment]
:lgtm:!

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8621#-:-LAP04lo3Jznff7tU4PX:bg7igkw)*

**Pull request merged**
