### PR TITLE
Refactor qp test

### PR DESCRIPTION
**Pull request by hongkai-dai**
There are a lot of code change in this PR, but most of it is just move the code from one place `convex_optimization_test.cc` to `quadratic_program_examples.h/cc`. I also add the cost/constraints in different forms (non-symbolic, symbolic, formula).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5273)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for both reviews please

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5273#-:-Kdfsm671noKs60wflGh:bdfe4li)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/convex_optimization_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5273#-KdgP6AHYkMnqwtqmQxB:-KdgP6AHYkMnqwtqmQxC:b1opnar) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1616146c88693a8a56f32e63092bfe9643c2df/drake/solvers/test/convex_optimization_test.cc#L28)):*
> ```cpp
>   AddSolverIfAvailable(SolverType::kGurobi, solvers);
>   AddSolverIfAvailable(SolverType::kMosek, solvers);
>   AddSolverIfAvailable(SolverType::kSnopt, solvers);
> ```

Did we lose coverage of QP with SNOPT in this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5273#-:-KdgJLAbKgkWe6WHD-fY:b-s794vx)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/convex_optimization_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5273#-KdgP6AHYkMnqwtqmQxB:-Ke6Owh1C5FmHax_dJLO:bhf1zgi) ([raw file](https://github.com/robotlocomotion/drake/blob/1a1616146c88693a8a56f32e63092bfe9643c2df/drake/solvers/test/convex_optimization_test.cc#L28)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Did we lose coverage of QP with SNOPT in this change?
</blockquote></details>

Done. Add the test for snopt and ipopt. When I tested with nlopt, it throws a runtime error. I will look into the Nlopt issue in a separate PR, this PR is already large enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5273)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5273#-:-KeAM3XZRb1UtK45VU_U:b-l70wzf)*

**Pull request merged**
