### PR TITLE
Use OptimizationProblem for inverseKinBackend (except trajectories)

### PR DESCRIPTION
**Pull request by sammy-tri**
Switch to using the generic OptimizationProblem frontend instead of the custom SNOPT wrapper.

Some types of constraints cause issues when using NLopt, but the existing implementation doesn't work at all without SNOPT anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2261) &emsp; Multiple assignees:&emsp;@Lucy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/Lucy-tri">Lucy-tri</a>,&emsp;@ggould-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/ggould-tri">ggould-tri</a>

### CODE REVIEW

**Comment by ggould-tri** [comment]
Note:  At @sammy-tri 's request I will do initial review and then shepherd this PR while he is on vacation.

+@ggould-tri platform (and implementing review fixes)
+@lucy-tri feature

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-:-KH5XKX1m9js23O9SgUl:-201222323)*

**Comment by ggould-tri** [comment]
win64 failure is #2257 and can be ignored.  CI here is actually green despite its apparent redness.

**Comment by ggould-tri** [comment]
platform :lgtm:

---

Reviewed 6 of 9 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-:-KH6j08j5FMZYWehTspr:1525963316)*

**Comment by sammy-tri** [comment]
Much thanks to ggould for first round of fixes.  I'll take over anything which comes up in @lucy-tri's review.

<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> platform :lgtm:</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-:-KHLbVv9QQZOKkL5vIqu:858440375)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by Lucy-tri** [comment]
Reviewed 4 of 9 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/ConstraintWrappers.h, line 1 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQ9IH-NuYj64Ayot_3:-KHQ9IH-NuYj64Ayot_4:-1392863004) ([raw file](https://github.com/robotlocomotion/drake/blob/eaed4345a5a3d79f09bd2b6b3b6e32747f6fff6e/drake/systems/plants/ConstraintWrappers.h#L1)):*
> ```objc
> #ifndef DRAKE_SYSTEMS_PLANTS_CONSTRAINTWRAPPERS_H_
> ```

I thought we were doing #pragma once?

---

*[drake/systems/plants/ConstraintWrappers.h, line 46 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQFMh7iCLYl_143-9Z:-KHQFMh7iCLYl_143-9_:1681090907) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/ConstraintWrappers.h#L46)):*
> ```objc
> };
> 
> class SingleTimeKinematicConstraintWrapper : public Constraint {
> ```

Is the name "SingleTime" trying to indicate that this constraint is just used once?  It isn't now if it's being cached.  So the name is no longer pertinent.  Am I confusing apples and oranges?

---

*[drake/systems/plants/ConstraintWrappers.h, line 59 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQGipNlt5M4Ws1eBCd:-KHQGipNlt5M4Ws1eBCe:461224464) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/ConstraintWrappers.h#L59)):*
> ```objc
>   }
> 
>   // Don't take partial ownership of the constraint, instead alias it
> ```

Could you give more guidance in the comments about when to use each of these 2 different constructors?  When would I use each?  Could you please go into more detail in the comments about how you use pointer aliasing here, and a reference in the other constructor - I guess I still don't understand how that prevents the user from doing anything different. 

---

*[drake/systems/plants/ConstraintWrappers.h, line 98 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQIGuONzES1STYP-uM:-KHQIGuONzES1STYP-uN:-1432098012) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/ConstraintWrappers.h#L98)):*
> ```objc
> class QuasiStaticConstraintWrapper : public Constraint {
>  public:
>   // Don't take partial ownership of the constraint, instead alias it
> ```

See my comments above re: alias.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 35 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQMGAhccnZzOQNBfIx:-KHQMGAhccnZzOQNBfIy:253979895) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/inverseKinBackend.cpp#L35)):*
> ```cpp
> namespace {
> 
> class Mode1Objective : public Constraint {
> ```

How about add a comment about what mode1 is.  Is it a placeholder for future modes?  What is a mode in this context? Consider a more descriptive name for Mode.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 38 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQLoWQCZjd5HgChP54:-KHQLoWQCZjd5HgChP55:-1367103883) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/inverseKinBackend.cpp#L38)):*
> ```cpp
>  public:
>   // All references are aliased for the life of the objective.  It
>   // should be short.
> ```

Could you make this comment more explicit, maybe say (if this is correct): Use pointer aliasing for the life of the objective, which should have a short lifetime.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 61 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQNKq3AfO3xYpnVjFr:-KHQNKq4YHvmxnHAQBYf:424900407) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/inverseKinBackend.cpp#L61)):*
> ```cpp
>   }
> 
>   void set_q_nom(const VectorXd& q_nom_i) {
> ```

Does something bad happen if you don't set q_nom?  Runtime error?

---

*[drake/systems/plants/inverseKinBackend.cpp, line 148 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQP0D6HgMqMF1RIWQP:-KHQP0D6HgMqMF1RIWQQ:-528197912) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/inverseKinBackend.cpp#L148)):*
> ```cpp
>             static_cast<SingleTimeKinematicConstraint*>(constraint);
>         if (!stc->isTimeValid(&t[t_index])) { continue; }
>         auto wrapper = std::make_shared<SingleTimeKinematicConstraintWrapper>(
> ```

wrapper could be const?

---

*[drake/systems/plants/inverseKinBackend.cpp, line 228 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQPIewxe3XA6PIId2t:-KHQPIewxe3XA6PIId2u:359356897) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/inverseKinBackend.cpp#L228)):*
> ```cpp
>     }
> 
>     // Add a bounding box constraint from them model.
> ```

them -> the

---

*[drake/systems/plants/test/testIKpointwise.cpp, line 29 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQQetOGRAWlx9THgp4:-KHQQetOGRAWlx9THgp5:2132292212) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/test/testIKpointwise.cpp#L29)):*
> ```cpp
>   Vector3d com_des = Vector3d::Zero();
>   com_des(2) = std::numeric_limits<double>::quiet_NaN();
>   // TODO(sammy-tri) stop allocating on heap?
> ```

Is this comment obsolete?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2261)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/plants/ConstraintWrappers.h, line 46 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQFMh7iCLYl_143-9Z:-KHQUbLpDgcx8XixcA5K:746325498) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/ConstraintWrappers.h#L46)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Is the name "SingleTime" trying to indicate that this constraint is just used once?  It isn't now if it's being cached.  So the name is no longer pertinent.  Am I confusing apples and oranges?</details>
RigidBodyConstraint.h defines SingleTimeKinematicConstraint as "An abstract class that constrain the kinematics of the robot at individual time," which isn't all that helpful...   I think the name was mostly chosen do distinguish from "MultipleTimeKinematicConstraint", which (AFAICT) is only used during inverse kinematics trajectory stuff (which this PR makes no attempt to implement)

---

*[drake/systems/plants/ConstraintWrappers.h, line 59 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQGipNlt5M4Ws1eBCd:-KHQWz_brgyrIN9XyIr_:-1963464092) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/ConstraintWrappers.h#L59)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Could you give more guidance in the comments about when to use each of these 2 different constructors?  When would I use each?  Could you please go into more detail in the comments about how you use pointer aliasing here, and a reference in the other constructor - I guess I still don't understand how that prevents the user from doing anything different. </details>
Eliminated the shared_ptr version of the constructor entirely.  It was only used from RigidBodySystem::getInitialState(), and I agree having two versions was confusing.

---

*[drake/systems/plants/inverseKinBackend.cpp, line 148 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQP0D6HgMqMF1RIWQP:-KHQTyiyRa-cqYyV2wnw:-1023686012) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/inverseKinBackend.cpp#L148)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> wrapper could be const?</details>
AddGenericConstraint takes a non-const argument where we pass in wrapper (which makes some sense, as it's a shared_ptr and the reference count needs to be able to change)

---

*[drake/systems/plants/test/testIKpointwise.cpp, line 29 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-KHQQetOGRAWlx9THgp4:-KHQUK-s-dIaZ6dK9Twp:2022366916) ([raw file](https://github.com/robotlocomotion/drake/blob/59ae3c5cc710fe8ffaf6067c0b920d4b597c1c87/drake/systems/plants/test/testIKpointwise.cpp#L29)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Is this comment obsolete?</details>
yes, it was.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2261)*

**Comment by Lucy-tri** [comment]
:lgtm:

<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> @drake-jenkins-bot retest this please</details>


---

Reviewed 1 of 1 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2261#-:-KHR6Cg0vottDKwf0qSy:1417088721)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
