### PR TITLE
Replaced template type with double for integrator accuracy settings

### PR DESCRIPTION
**Pull request by edrumwri**
Addresses issue #3829.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4035)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review, +@ggould-tri for platform review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4035#-:-KVlrIrQCJB2YQcll0ay:b-j8gg2q)*

**Comment by jwnimmer-tri** [comment]
-@ggould-tri +@jwnimmer-tri for platform.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 383 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4035#-KVlsg9Pu8zUwn-Gbb57:-KVlsg9QnpWrE_Ur9pJf:bfci7sz) ([raw file](https://github.com/robotlocomotion/drake/blob/90131d15c5b476ad3e8437017f9e149c3b12f57c/drake/systems/analysis/integrator_base.h#L383)):*
> ```objc
>   }
> 
>   double target_accuracy_{nan()};        // means "unspecified, use default"
> ```

BTW The comment is now misaligned with the below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4035#-:-KVlsbSXk2oUjN7bh_8P:bir3z1g)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 383 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4035#-KVlsg9Pu8zUwn-Gbb57:-KVlx-O4chbTG8oU-1HZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90131d15c5b476ad3e8437017f9e149c3b12f57c/drake/systems/analysis/integrator_base.h#L383)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW The comment is now misaligned with the below.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4035)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4035)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4035#-:-KW-hAATQTKBOXLMtaJx:bnfp4nl)*

**Pull request merged**
