### PR TITLE
framework_py: Expose `AbstractValue` and `Value<>` instantiations.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Partially addresses the `AbstractValues` bullet point of #7660. Next step is to implement unrestricted updates.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7933)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jadecastro for feature review, please.
+@sherm1 for platform review, please.

\cc @jwnimmer-tri Regarding the potential lifetime issues with `Value<>::set_value` for non-copyable types, can I ask if you have a suggestion on how to address this? (see comments in `systems_pybind.h`)

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-:-L4KXTJndbO0_VeVsPnh:b-vqdbf4)*

**Comment by EricCousineau-TRI** [comment]
Follow up: Just thinking about it more, this caveat (deleting memory in C++ due to `unique_ptr<>::reset()` which is still reference in Python) is something that we will face in other areas, aside from just usage of `unique_ptr<>`, such as passing `Eigen::Ref<>` to Python. The memory is valid unless you resize the original matrix, in which case the pre-resize memory is not guaranteed to be valid.

In this case, I'll add some `__doc__` to the accessor / mutator methods with a warning, telling users to avoid storing direct references when possible, and just call `get_value()` if they want to access values.

**Comment by sherm1** [comment]
I'd like to wait until at least a round of feature review before platforming.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7933#-:-L4O5U7v8tWtipUKGPJg:b-mn7os8)*

**Comment by jadecastro** [comment]
Pass complete.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py.cc, line 434 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4OMAufauMlNDrJNY3W:-L4OMAufauMlNDrJNY3X:b-xxqiks) ([raw file](https://github.com/robotlocomotion/drake/blob/34d09039950cd3aca87fbb96e5c1dcadb48a9178/bindings/pydrake/systems/framework_py.cc#L434)):*
> ```cpp
>     .def("__copy__", &AbstractValue::Clone)
>     // Use only exception variant.
>     .def("SetFrom", &AbstractValue::SetFromOrThrow)
> ```

BTW, here the spelling binding name is different from the class name.

---

*[bindings/pydrake/systems/systems_pybind.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4OGA3pOdjn2GIabS2H:-L4OGA3qAf5-Wh36vPg7:btnm7ka) ([raw file](https://github.com/robotlocomotion/drake/blob/34d09039950cd3aca87fbb96e5c1dcadb48a9178/bindings/pydrake/systems/systems_pybind.h#L18)):*
> ```objc
> /// @param scope Parent scope.
> /// @tparam T Inner parameter of `Value<T>`.
> /// @tparam Class Class to be bound. By default, `Value<T>` is used.
> ```

BTW, It seems like this binding is designed to wrap classes like `Value` and `BasicVector`, but not others. Could this be documented more explicitly?

---

*[bindings/pydrake/systems/systems_pybind.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4OBR7MbfNzJkpeJThK:-L4OBR7MbfNzJkpeJThL:byuw1gt) ([raw file](https://github.com/robotlocomotion/drake/blob/34d09039950cd3aca87fbb96e5c1dcadb48a9178/bindings/pydrake/systems/systems_pybind.h#L38)):*
> ```objc
>     // dangling Python reference, since the `unique_ptr` will be reset
>     // internally.
>     // TODO(eric.cousineau): Resolve this, either by (a) using a snowflake
> ```

BTW, I'm not following what you mean in option (a). Consider rephrasing this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-:-L4OInf2ffvrJlq4Nnut:bilrup7)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py.cc, line 434 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4OMAufauMlNDrJNY3W:-L4Oe2nkObP0x3V2c_-v:b-6aknl) ([raw file](https://github.com/robotlocomotion/drake/blob/34d09039950cd3aca87fbb96e5c1dcadb48a9178/bindings/pydrake/systems/framework_py.cc#L434)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, here the spelling binding name is different from the class name.
</blockquote></details>

Done. (Added rationale for why this was done.)

---

*[bindings/pydrake/systems/systems_pybind.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4OGA3pOdjn2GIabS2H:-L4Oe7S_qbJq6BmJSLhT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34d09039950cd3aca87fbb96e5c1dcadb48a9178/bindings/pydrake/systems/systems_pybind.h#L18)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, It seems like this binding is designed to wrap classes like `Value` and `BasicVector`, but not others. Could this be documented more explicitly?
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/systems_pybind.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4OBR7MbfNzJkpeJThK:-L4Oe9koMgktXS6b-EU7:b-rgez1r) ([raw file](https://github.com/robotlocomotion/drake/blob/34d09039950cd3aca87fbb96e5c1dcadb48a9178/bindings/pydrake/systems/systems_pybind.h#L38)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, I'm not following what you mean in option (a). Consider rephrasing this.
</blockquote></details>

Done. Given the comment I made at the top, I've bubbled this up as a user-visible docstring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few BTWs.

---

Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/BUILD.bazel, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4PGrCTOs3Ao7tpilRl:-L4PGrCUSCwr2NPvi44e:b-rdtaz8) ([raw file](https://github.com/robotlocomotion/drake/blob/071c6bd4d8a8d485f4db1de1c6c5439b0d5a3710/bindings/pydrake/systems/BUILD.bazel#L72)):*
> ```Python
>     py_deps = [
>         ":module_py",
>     ] + systems_pybind_py,
> ```

BTW I hadn't seen this before -- is that just to avoid repeating the long name?

---

*[bindings/pydrake/systems/framework_py.cc, line 453 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4PJZ2Tq7sxh582_QvQ:-L4PJZ2Tq7sxh582_QvR:b-i93qun) ([raw file](https://github.com/robotlocomotion/drake/blob/071c6bd4d8a8d485f4db1de1c6c5439b0d5a3710/bindings/pydrake/systems/framework_py.cc#L453)):*
> ```cpp
>     // Override `Value<py::object>::Clone()` to perform a shallow copy on the
>     // object.
>     std::unique_ptr<AbstractValue> Clone() const override {
> ```

BTW just want to make sure this is what you intended. `Value<T>` always does a deep copy in C++ Drake but here it is being made shallow. Can you explain why?

---

*[bindings/pydrake/systems/test/value_test.py, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4PIOHF33lglC3Zc4hF:-L4PIOHF33lglC3Zc4hG:b-lb0mjl) ([raw file](https://github.com/robotlocomotion/drake/blob/071c6bd4d8a8d485f4db1de1c6c5439b0d5a3710/bindings/pydrake/systems/test/value_test.py#L79)):*
> ```Python
>     def test_abstract_value_move_only(self):
>         obj = MoveOnlyType(10)
>         # This *always* copies the object.
> ```

BTW unclear which object -- presumably the move-only object can't be copied?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-:-L4PKAvSqIcHKEHqelD8:bv2dux7)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-:-L4QdgxH302KAmA-UJZn:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Added a generalization of the emplace constructor.

---

Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/BUILD.bazel, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4PGrCTOs3Ao7tpilRl:-L4bVzpFE1iiiFzTv9WW:b4jmfyw) ([raw file](https://github.com/robotlocomotion/drake/blob/071c6bd4d8a8d485f4db1de1c6c5439b0d5a3710/bindings/pydrake/systems/BUILD.bazel#L72)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I hadn't seen this before -- is that just to avoid repeating the long name?
</blockquote></details>

Done. This was more of a way to try and bundle transient dependencies of mixed types - I haven't tried out a way to try and make a provider which can provide both Python and C++ dependencies (e.g. `cpp_template_py` and `cpp_template_pybind`).

For now, just removed the alias, and used the target.
TBH, I could remove `cpp_template_py` from `test_util_py`, but I'll defer that to some later point.

---

*[bindings/pydrake/systems/framework_py.cc, line 453 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4PJZ2Tq7sxh582_QvQ:-L4bXSAvy0Q13fsb6fJK:b-x759om) ([raw file](https://github.com/robotlocomotion/drake/blob/071c6bd4d8a8d485f4db1de1c6c5439b0d5a3710/bindings/pydrake/systems/framework_py.cc#L453)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW just want to make sure this is what you intended. `Value<T>` always does a deep copy in C++ Drake but here it is being made shallow. Can you explain why?
</blockquote></details>

Done.
No other reason other than I was being hesitant on committing to `deepcopy` for fear of cycles; but after reading the documentation for `__deepcopy__`, and seeing the `memo` dictionary, it looks like that's a moot point.

---

*[bindings/pydrake/systems/test/value_test.py, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-L4PIOHF33lglC3Zc4hF:-L4bXkjHhLl1S2QZ-8lL:b9ez7zl) ([raw file](https://github.com/robotlocomotion/drake/blob/071c6bd4d8a8d485f4db1de1c6c5439b0d5a3710/bindings/pydrake/systems/test/value_test.py#L79)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW unclear which object -- presumably the move-only object can't be copied?
</blockquote></details>

Done. Clarified both the action, cloning rather than copying, and `obj` rather than `the object`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933#-:-L4bXqS7-DGPHcb-GkCc:bnaplzh)*

**Comment by jadecastro** [comment]
Reviewed 6 of 6 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7933)*

**Pull request merged**
