### PR TITLE
FixedSizeQuadrature.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
I took a look at the Traits code and made some comments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMWYYID73qunnE-gs2C:b-h8hy6n)* status: 7 unresolved discussions, needs at least one assigned reviewer (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_quadrature.h, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWSXtg3lhF5l0rhsQ0:-MMWSXtg3lhF5l0rhsQ1:b-bsd2ud) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L16)):*
> ```objc
> class FixedSizeSimplexGaussianQuadrature;
> 
> template <class...>
> ```

The "..." here indicates that the struct is templatized by a list of classes. Looks like there should be just one -- something like `template <class QuadratureType>`? (But see below -- this might be the wrong parameterization.)
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWTOXB4jaGxBLvbImZ:-MMWTOXB4jaGxBLvbIm_:b-t5uxmf) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L17)):*
> ```objc
> 
> template <class...>
> struct QuadratureTraits {};
> ```

Consider documenting the requirements for specialization of this class. Looks to me like the specialization must provide a constant (kNumQuadratureLocations) and three types (VectorD, QuadratureLocationsType, WeightsType) with particular names and meanings.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWTxmtE9yAFwqRCecJ:-MMWTxmtE9yAFwqRCecK:b25l5qb) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L26)):*
> ```objc
>   using VectorD = Eigen::Matrix<T, NaturalDimensions, 1>;
>   using QuadratureLocationsType = std::array<VectorD, kNumQuadratureLocations>;
>   using WeightsType = std::array<T, kNumQuadratureLocations>;
> ```

It doesn't appear to me that the QuadratureTraits depends on the actual quadrature type but rather just T, NaturalDimensions, and Order (or something like that). If that's the case, QuadratureTraits should be templatized by those parameters. That would require far fewer specializations.

OTOH, if the QuadratureType actually is relevant, then the four defined members should be set from that type, e.g.
```
static constexpr int kNumQuadratureLocations =
  QuadratureType::num_quadrature_locations();
```
or something like that.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWVtkkE_14T3O6UkXi:-MMWVtklDTRQIEogBZP-:bmu6ina) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L63)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(FixedSizeQuadrature);
> 
>   using VectorD = Eigen::Matrix<T, NaturalDimension, 1>;
> ```

This is duplicating the traits declarations -- the Traits class should be providing these declarations.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWW9mgAVlkZsjJxEil:-MMWW9mgAVlkZsjJxEim:b-itoxza) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L99)):*
> ```objc
>  private:
>   std::array<VectorD, NumQuadratureLocations> points_;
>   std::array<T, NumQuadratureLocations> weights_;
> ```

Traits should be providing these types.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWWRKQ0TDX_TLZqQCI:-MMWWRKQ0TDX_TLZqQCJ:b-57rcvf) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L121)):*
> ```objc
>           T, NaturalDimension,
>           QuadratureTraits<FixedSizeSimplexGaussianQuadrature<
>               T, NaturalDimension, QuadratureOrder>>::kNumQuadratureLocations> {
> ```

This is unnecessarily twisted. The definition of FixedSizeSimplexGaussianQuadrature should not depend on traits templatized on itself. Consider templatizing FixedSizeQuadrature on T, NaturalDimension (N), and QuadratureOrder (O). Then it can use `QuadratureTraits<T, N, O>` itself and use it for all the dimensions and types.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWYU-x3IIUJPFb39Hs:-MMWYU-x3IIUJPFb39Ht:b-gfpoij) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L127)):*
> ```objc
>   static constexpr int kNumQuadratureLocations =
>       Traits::kNumQuadratureLocations;
>   using VectorD = Eigen::Matrix<T, NaturalDimension, 1>;
> ```

This should be coming from Traits.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the feedback.  I addressed some of them but still have some lingering questions. I listed my sources of confusion in the individual threads below. To summarize them here:

1. How to combat repetition in trait class?
2. What's the purpose of the generic trait class?
3. Where should types be declared? The trait class or the quadrature class?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMWkWJ2254FtpTed2Vu:b-85215)* status: 7 unresolved discussions, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_quadrature.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWTOXB4jaGxBLvbImZ:-MMWu66_6kK83LHV7RPB:bqgeveo) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L17)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Consider documenting the requirements for specialization of this class. Looks to me like the specialization must provide a constant (kNumQuadratureLocations) and three types (VectorD, QuadratureLocationsType, WeightsType) with particular names and meanings.
</blockquote></details>

I added some documentation. From the documentation it's clear that LocationsType and WeightsType should be the same for all specialization. Is there some way to avoid the repetition?
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWTxmtE9yAFwqRCecJ:-MMWg_ydAPQxOqHOR62m:bzba7rg) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

It doesn't appear to me that the QuadratureTraits depends on the actual quadrature type but rather just T, NaturalDimensions, and Order (or something like that). If that's the case, QuadratureTraits should be templatized by those parameters. That would require far fewer specializations.

OTOH, if the QuadratureType actually is relevant, then the four defined members should be set from that type, e.g.
```
static constexpr int kNumQuadratureLocations =
  QuadratureType::num_quadrature_locations();
```
or something like that.
</blockquote></details>

QuadratureType is relevant here. Consider, for example, a quadrature class for quadrilateral elements. In that case, the number of quadrature locations would be different from that of simplex elements even if T, NaturalDimensions, and Order are all the same.

One source of confusion for me is: what is the point of the generic templated trait? i.e.
```
template <class QuadratureType>
struct QuadratureTraits;
```

It seems like all the traits that are actually used are the specialized trait, e.g. 
```
template <typename T, int NaturalDim, int Order>
QuadratureTraits<FixedSizeSimplexGaussianQuadrature<T, NaturalDim, Order>>
```

Another source of confusion is: in the generic templated trait, the typedef comes from the quadrature class, e.g.
```
static constexpr int kNumQuadratureLocations =
  QuadratureType::num_quadrature_locations();
```

But in the specialized trait, the typedef (it sounds like) should come from the trait class, not the quadrature class. Why is that the case?
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWVtkkE_14T3O6UkXi:-MMWlIMA184L_DNNc6A1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is duplicating the traits declarations -- the Traits class should be providing these declarations.
</blockquote></details>

Done.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWW9mgAVlkZsjJxEil:-MMWlIDn0HwI2CPzF_vk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L99)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Traits should be providing these types.
</blockquote></details>

Done.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWWRKQ0TDX_TLZqQCI:-MMWkG0iCrBxVVlGvF0f:b-rhxodz) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is unnecessarily twisted. The definition of FixedSizeSimplexGaussianQuadrature should not depend on traits templatized on itself. Consider templatizing FixedSizeQuadrature on T, NaturalDimension (N), and QuadratureOrder (O). Then it can use `QuadratureTraits<T, N, O>` itself and use it for all the dimensions and types.
</blockquote></details>

The obstacle I ran into here is that there is no formula that maps QuadratureOrder to NumQuadratureLocations (which I need in the quadrature class).
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWYU-x3IIUJPFb39Hs:-MMWlJd10w7Sq5LLZzFf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L127)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should be coming from Traits.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Let's discuss f2f.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMX2YgE2Bsb6MYcemw0:b-yatr66)* status: 3 unresolved discussions, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_quadrature.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMWTOXB4jaGxBLvbImZ:-MMX1eRt31v3qcMTNm5V:bt013xv) ([raw file](https://github.com/robotlocomotion/drake/blob/8607f6402511db00c9938e49b4d42f76eb93f1a0/multibody/fem/dev/fixed_size_quadrature.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I added some documentation. From the documentation it's clear that LocationsType and WeightsType should be the same for all specialization. Is there some way to avoid the repetition?
</blockquote></details>

They don't look the same to me -- one is an array of VectorD's, the other is an array of T's. They are the same length, is that what you mean?

**Review by xuchenhan-tri — COMMENTED** [review]
@sherm1 Thanks for the suggestions. It has become more or less what I want it to look like. 
Not going to try to merge this PR as it is though because I want to remove the old quadrature class and replace it with the new one.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMXXK4nDG5kaJ0fQs-0:b-cc4h2)* status: 3 unresolved discussions, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Much nicer!

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMXlLS1BQOtA3FrJJ--:b4dlvei)* status: 2 unresolved discussions, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_quadrature.h, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMXimec76dnZmpcC7PA:-MMXimec76dnZmpcC7PB:b-o13t60) ([raw file](https://github.com/robotlocomotion/drake/blob/a160f7712d4a39924345f50af3ec7cfe3a1b14f6/multibody/fem/dev/fixed_size_quadrature.h#L45)):*
> ```objc
>   const VectorD& get_point(int q) const {
>     DRAKE_ASSERT(q >= 0);
>     DRAKE_ASSERT(q < NumLocations);
> ```

BTW you could also write this
```
DRAKE_ASSERT(0 <= q && q < NumLocations);
```
I find that easier to grasp at a glance because it _almost_ looks like `0 ≤ q < N` which is what I wish we could write!
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 107 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMXkFcR040rVyns9FV-:-MMXkFcR040rVyns9FV0:bfo2fvm) ([raw file](https://github.com/robotlocomotion/drake/blob/a160f7712d4a39924345f50af3ec7cfe3a1b14f6/multibody/fem/dev/fixed_size_quadrature.h#L107)):*
> ```objc
>       "Only linear, quadratic and cubic quadrature rules are supported.");
> 
>   static constexpr int num_quadrature_points() {
> ```

This should be available already through the base class by inheritance -- no need to reimplement here. If you're trying to get rid of the need to write `this->num_quadrature_points()` you can do that by upgrading the base class method via `using Base::num_quadrature_points();`.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMXlDCu4eusjJumxUQS:-MMXlDCu4eusjJumxUQT:b-v0d6y7) ([raw file](https://github.com/robotlocomotion/drake/blob/a160f7712d4a39924345f50af3ec7cfe3a1b14f6/multibody/fem/dev/fixed_size_quadrature.h#L120)):*
> ```objc
> 
>   FixedSizeSimplexGaussianQuadrature()
>       : FixedSizeQuadrature<T, NaturalDimension, num_quadrature_points()>(
> ```

Can you use `Base` here to make this tidier?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367)* status: needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/fem/dev/fixed_size_quadrature.h, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMXimec76dnZmpcC7PA:-MMXrkKUDlT7u0QH69Cu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a160f7712d4a39924345f50af3ec7cfe3a1b14f6/multibody/fem/dev/fixed_size_quadrature.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW you could also write this
```
DRAKE_ASSERT(0 <= q && q < NumLocations);
```
I find that easier to grasp at a glance because it _almost_ looks like `0 ≤ q < N` which is what I wish we could write!
</blockquote></details>

Done.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 107 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMXkFcR040rVyns9FV-:-MMXrWz-22ZHPxg3QzUP:bymgs7t) ([raw file](https://github.com/robotlocomotion/drake/blob/a160f7712d4a39924345f50af3ec7cfe3a1b14f6/multibody/fem/dev/fixed_size_quadrature.h#L107)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should be available already through the base class by inheritance -- no need to reimplement here. If you're trying to get rid of the need to write `this->num_quadrature_points()` you can do that by upgrading the base class method via `using Base::num_quadrature_points();`.
</blockquote></details>

Turns out with all the typedefs, I don't even need that.
___
*[multibody/fem/dev/fixed_size_quadrature.h, line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14367#-MMXlDCu4eusjJumxUQS:-MMXrWEO2Wo-_F7pBmri:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a160f7712d4a39924345f50af3ec7cfe3a1b14f6/multibody/fem/dev/fixed_size_quadrature.h#L120)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Can you use `Base` here to make this tidier?
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367)* status: needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
+@sherm1 appears to be looking at this.  If review is not desired, you can un-assign and apply the "do not review" label.

> Not going to try to merge this PR as it is though ...

+(status: do not merge)

**Review by xuchenhan-tri — COMMENTED** [review]
@jwnimmer-tri, the review was requested, but merely as a way for me to get some early feedback as opposed to trying to merge the PR. I'll make sure to add the "do not merge" label in the future. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMY7Ep10fb1_6Luo7Uj:bp3t6ry)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
Sounds good.  It was showing up in the "unassigned reviews" alarm for platform reviewers, so simply having Sherm be formally assigned is all I need.

**Review by xuchenhan-tri — COMMENTED** [review]
Got it. I'll keep this PR alive then. I'll modify it into mergable form when the other pieces are ready, and ask Sherm to review the rest at that time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14367#-:-MMYAtVW1RT9KloD8ytA:b-1d33ey)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Pull request closed without merging**
