### PR TITLE
Updated monolithic demo readme to mention precompiled drake-visualizer

### PR DESCRIPTION
**Pull request by naveenoid**
Addresses #6354

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6362)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@russtedrake for feature and platform review. (Its a straightforward fix).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-KmmR_FtsCF63Wg9I4eR:b-w5qpe6)*

**Comment by RussTedrake** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmyP2w-aGlKrIry9jk:-KmmyP2w-aGlKrIry9jl:b-mxfioi) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L19)):*
> ```Markdown
> ```
> $ cd drake-distro
> $ bazel build //tools:drake_visualizer && bazel-build //drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place:monolithic_pick_and_place_demo
> ```

bazel-build?

perhaps just 
bazel build //tools:drake_visualizer //drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place:monolithic_pick_and_place_demo

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmxoGdcCd_nlL2vppC:-KmmxoGdcCd_nlL2vppD:b7yppd3) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L28)):*
> ```Markdown
> 
> ```
> $ bazel-bin/tools/drake-visualizer&
> ```

that doesn't work for me (on mac)

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmybHqIzqN-k5qmQi4:-KmmybHqIzqN-k5qmQi5:bw6z3cj) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L36)):*
> ```Markdown
> 
> ```
> $ ./bazel-bin/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/
> ```

or should we prefer recommending `bazel run`?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmxoGdcCd_nlL2vppC:-Kmn0jDKN0QpaNJoKhEO:b5sl0do) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L28)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that doesn't work for me (on mac)
</blockquote></details>

FYI Mac still lacks some version of the #6319 fix that happened on linux.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by naveenoid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmyP2w-aGlKrIry9jk:-Kn1o1HpTRdj9SWquuEg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L19)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

bazel-build?

perhaps just 
bazel build //tools:drake_visualizer //drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place:monolithic_pick_and_place_demo

</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmxoGdcCd_nlL2vppC:-Kn1rRB3CfjBluPupDlq:bcyq5e3) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L28)):*
> #6319
Added a comment about it not working on mac.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmybHqIzqN-k5qmQi4:-KnLCx3K7JHirpqiHfcA:b-xade5c) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L36)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

or should we prefer recommending `bazel run`?  
</blockquote></details>

Done. Swapped the recommendations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by RussTedrake** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmyP2w-aGlKrIry9jk:-KndMOuX_p2kyYhHlTbI:b-klluu6) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L19)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done?  you don't need the `&& bazel build` ... bazel can take multiple targets as multiple arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KmmyP2w-aGlKrIry9jk:-KnnwYD_K-I4TM6zCqkd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99473eb5aaa982b403505128093248208dc05169/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L19)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

not done?  you don't need the `&& bazel build` ... bazel can take multiple targets as multiple arguments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-Knp3uknxsxEhd0it-dE:bnfp4nl)*

**Comment by naveenoid** [comment]
+@soonho-tri for platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-KnpA2_vcdcYoEwWKmt2:bxw8cpy)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-KnpISGd5-D-crNRkp-X:bp1laq6)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KnpQ-02O6ldOAvEDbIV:-KnpQ-02O6ldOAvEDbIW:b-aqjv4c) ([raw file](https://github.com/robotlocomotion/drake/blob/dd738a4bc65e13782c2c7f5cb23d2ed9813beea2/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L28)):*
>  bazel-bin/tools/drake-visualizer

It should be `drake-visualizer` => `drake_visualizer`.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KnpS9zDo91Cdd2M2N-s:-KnpS9zDo91Cdd2M2N-t:bnduu9) ([raw file](https://github.com/robotlocomotion/drake/blob/dd738a4bc65e13782c2c7f5cb23d2ed9813beea2/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L42)):*
> ```Markdown
> 
> ```
> bazel run :monolithic_pick_and_place_demo --config snopt -- --box_choice=1
> ```

Is `--box_choice` option still valid? I've rebased this PR over the current `master` and follow the instructions, but I get:

```
ERROR: unknown command line flag 'box_choice'
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by jwnimmer-tri** [comment]
This is in `dev`, you don't need platform review, eh?

**Comment by naveenoid** [comment]
Right! But good catch by soonho anyways. I will wait for his LGTM nonetheless.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KnpQ-02O6ldOAvEDbIV:-KnpX8CL0KxM8zszLIwo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dd738a4bc65e13782c2c7f5cb23d2ed9813beea2/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

>  bazel-bin/tools/drake-visualizer

It should be `drake-visualizer` => `drake_visualizer`.

</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KnpS9zDo91Cdd2M2N-s:-KnpWnocPCH5fn85j4Pb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dd738a4bc65e13782c2c7f5cb23d2ed9813beea2/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L42)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is `--box_choice` option still valid? I've rebased this PR over the current `master` and follow the instructions, but I get:

```
ERROR: unknown command line flag 'box_choice'
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-KnpWhOGmLkSuFO_UEn5:b-t0jbqj)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a BTW)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KnpYA0LddAU05InzmJf:-KnpYA0LddAU05InzmJg:b-d7cs2d) ([raw file](https://github.com/robotlocomotion/drake/blob/97e803a309a5fa8010e2ecd736d0133305403801/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L55)):*
> ```Markdown
> ```
> 
> Command line arguments can be passed for : `box_choice` an integer between 1
> ```

BTW, we still have `box_choice` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-KnpYDiEie3W52-inelg:b-i8gkkc)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-KnpYA0LddAU05InzmJf:-Knp_PQyyWPJZtJst04q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97e803a309a5fa8010e2ecd736d0133305403801/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md#L55)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, we still have `box_choice` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362#-:-KnqG98lzPlfnnTm0NHk:bp1laq6)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6362)*

**Pull request merged**
