### PR TITLE
[tools] Improve single point of control for Python interpreter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Lean into the `@python` repository rule to be the single point of control for which Python interpreter we should be using, defining the `py_toolchain` in terms of that rule's output.

Remove various other work-arounds for not having a single point.

Towards #20294.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review from the Bazel perspective, please.
+@mwoehlke-kitware for feature review from the CMake + Wheel perspective, please.
+@EricCousineau-TRI for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform),mwoehlke-kitware

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-NfwnePP7Qa0qiDb0EEV:-NfwnePP7Qa0qiDb0EEW:bgadj8e) (no related file):*
Working

Drake Jenkins wheel tests are underway.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-NfwnfY85CMQkAQNbir1:-NfwnfY96xhaPyqmKgoL:b3uawwu) (no related file):*
Working

I'll fire off some Anzu tests.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-Ng-SEwf0awNdIP3d9Au:-Ng-SEwg6y98uMmRMQnM:bt41cm3) (no related file):*
Working

I'll manually do some drake-external-examples testing, too.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform),mwoehlke-kitware

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-NfwnePP7Qa0qiDb0EEV:-Ng-kMLDDm2L6FRA58cB:b8gh8ow) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Drake Jenkins wheel tests are underway.
</blockquote></details>

OK all passed.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-NfwnfY85CMQkAQNbir1:-Ng-kNgh0jb2ZhbWUjVO:b-uoqj7v) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll fire off some Anzu tests.
</blockquote></details>

OK passed (build 229).

___

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, nice!

> Reviewed 10 of 13 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-:-Ng-xj86AJ4H8K3NbjFR:bb368ni)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),mwoehlke-kitware

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311)* status: LGTM missing from assignees rpoyner-tri(platform),mwoehlke-kitware

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-Ng-SEwf0awNdIP3d9Au:-Ng-w08K9iuq-g-iVzxO:b-q1vkix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll manually do some drake-external-examples testing, too.
</blockquote></details>

d_b_e passed:

```console
drake-external-examples/drake_bazel_external$ env EXAMPLES_LOCAL_DRAKE_PATH=/path/to/drake bazel test //...
...
Executed 6 out of 6 tests: 6 tests pass.
```

---

d_b_i passed:

```patch
--- a/drake_bazel_installed/WORKSPACE
+++ b/drake_bazel_installed/WORKSPACE
@@ -18,7 +18,7 @@
 
 # To use a local unpacked Drake binary release instead of an http download, set
 # this variable to the correct path, e.g., "/opt/drake".
-INSTALLED_DRAKE_DIR = None
+INSTALLED_DRAKE_DIR = "/home/jwnimmer/tmp/install"
 
 # This is only relevant when INSTALLED_DRAKE_DIR is set.
 new_local_repository(
```

```console
Executed 5 out of 5 tests: 5 tests pass.
```

---

d_c_e passed:

```patch
--- a/drake_cmake_external/CMakeLists.txt
+++ b/drake_cmake_external/CMakeLists.txt
@@ -108,11 +108,7 @@ set(DRAKE_PREFIX "${PROJECT_BINARY_DIR}/drake-prefix")
 
 ExternalProject_Add(drake
   DEPENDS eigen fmt spdlog
-  URL https://github.com/RobotLocomotion/drake/archive/master.tar.gz
-  # Or from a commit (download and use "shashum -a 256 'xxx.tar.gz'" on it to
-  # get the URL_HASH.
-  # URL https://github.com/RobotLocomotion/drake/archive/65c4366ea2b63278a286b1e22b8d464d50fbe365.tar.gz
-  # URL_HASH SHA256=899d98485522a7cd5251e50a7a6b8a64e40aff2a3af4951a3f0857fd938cafca
+  URL https://github.com/RobotLocomotion/drake/archive/cbc36244825596075887c72c184a0f32a5fc865d.tar.gz
   TLS_VERIFY ON
   CMAKE_ARGS
     -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
```

```console
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_external$ mkdir build
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_external$ cd build
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_external/build$ cmake ..
...
[100%] Built target drake_external_examples
```

---

d_c_i passed:

```console
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_installed$ mkdir build
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_installed$ cd build
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_installed/build$ cmake -DCMAKE_PREFIX_PATH=/home/jwnimmer/tmp/install ..
...
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_installed/build$ make
...
[100%] Built target simple_continuous_time_system
jwnimmer@call-cps:~/jwnimmer-tri/x-drake-external-examples/drake_cmake_installed/build$ make test
...
100% tests passed, 0 tests failed out of 6
```

___

**Review by mwoehlke-kitware — COMMENTED** [review]
Wheel stuff seems okay. I don't claim to understand the Bazel parts. :slightly_smiling_face: 

> Reviewed 4 of 13 files at r1, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-:-Ng0Dkyy-ephmYatRKf5:bud7imk)* status: LGTM missing from assignees rpoyner-tri(platform),mwoehlke-kitware

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 13 files at r1, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-:-Ng0bJNC9PdZwEzal8cm:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware

___
*[`tools/workspace/default.bzl` line 408 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-Ng0auYmELRpiCi9rDH1:-Ng0auYmELRpiCi9rDH2:b76icsx) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e313cb1802c8e2e0910943ca597fc8efb522413/tools/workspace/default.bzl#L408)):*
> ```Starlark
>     if "py" not in excludes:
>         # The Python debug toolchain on Linux is not loaded automatically, but
>         # may be used by specifying the command line option
> ```

This comment may be stale now? The referred-to "command line option" has gone away.

**Review by jwnimmer-tri — COMMENTED** [review]
> Wheel stuff seems okay.

Thanks!  I'll take that as `:lgtm:` and so -@mwoehlke-kitware to tell reviewable to unblock it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-:-Ng0okN9AOlgBYFxKJNW:b-yyrff)* status: 1 unresolved discussion

___
*[`tools/workspace/default.bzl` line 408 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20311#-Ng0auYmELRpiCi9rDH1:-Ng0oie00XludrTVx_tX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e313cb1802c8e2e0910943ca597fc8efb522413/tools/workspace/default.bzl#L408)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This comment may be stale now? The referred-to "command line option" has gone away.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20311)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
