### PR TITLE
Bring iris up to date

### PR DESCRIPTION
**Pull request by rdeits**
This also adds support for arbitrary additional arguments for each external project in the `${proj}_EXTERNAL_ARGS` variable. I'm using it here to ensure that IRIS does not try to build its own versions of eigen or mosek by passing a custom PATCH_COMMAND.

### CODE REVIEW

**Comment by RussTedrake** [comment]
You should pass that in for the other external add cases at the same level, too.  

Also the name external args is not clear about whether that will be sent to the download/update and/or the build rule.

**Comment by rdeits** [comment]
ok, renamed it to `${proj}_ADDITIONAL_BUILD_ARGS` and added it to both `ExternalProject_Add` calls.

**Comment by rdeits** [comment]
I'm working on updating the IRIS build to make cython optional; I'll reopen this shortly.

**Comment by RussTedrake** [comment]
oops.  mosek has to come before iris in the foreach statement in cmakelists.txt

**Comment by rdeits** [comment]
done

On Wed, Aug 5, 2015 at 12:10 PM, Russ Tedrake <notifications@github.com>
wrote:

> oops. mosek has to come before iris in the foreach statement in
> cmakelists.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RobotLocomotion/drake/pull/1223#issuecomment-128053216>
> .
>



-- 
Robin L. H. Deits
Robot Locomotion Group @CSAIL
Massachusetts Institute of Technology

**Comment by rdeits** [comment]
Hm, looks like IRIS isn't being built with c++11?

**Comment by RussTedrake** [comment]
i do set some c++11 flags at the top of drake/drake/CMakeLists.txt

**Comment by rdeits** [comment]
It looks like I was doing something that only worked in c++11 (with gcc
4.8) but not in c++0x (with gcc 4.6). I'm fixing it to be more compatible
now.

On Wed, Aug 5, 2015 at 5:06 PM, Russ Tedrake <notifications@github.com>
wrote:

> i do set some c++11 flags at the top of drake/drake/CMakeLists.txt
> > On Aug 5, 2015, at 4:42 PM, Robin Deits <notifications@github.com>
> wrote:
> >
> > Hm, looks like IRIS isn't being built with c++11?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/RobotLocomotion/drake/pull/1223#issuecomment-128142004
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RobotLocomotion/drake/pull/1223#issuecomment-128148538>
> .
>



-- 
Robin L. H. Deits
Robot Locomotion Group @CSAIL
Massachusetts Institute of Technology

**Comment by rdeits** [comment]
conflicts fixed, trying again

**Comment by rdeits** [comment]
Looks like there's a bug in the new github integration:

```
                            < M A T L A B (R) >
                  Copyright 1984-2012 The MathWorks, Inc.
                    R2012b (8.0.0.783) 64-bit (glnxa64)
                              August 22, 2012

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 

response =

{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Status",
      "code": "custom",
      "field": "state",
      "message": "state is not included in the list"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/statuses/#create-a-status"
}
```

**Comment by rdeits** [comment]
pulled in some fixes (and, incidentally, the changes from #1231 )

This is also waiting on https://github.com/RobotLocomotion/cmake/pull/18

**Comment by rdeits** [comment]
Looks like this is breaking some of the more fragile atlas walking planning tests. I've slightly altered some tolerances inside IRIS, which is probably the root of the problem. This is going to require some more work.

**Comment by rdeits** [comment]
Ok, I've got 3 failures on this pull request. The first is a crash inside yalmip in testMISOSTrajecotry. I can't reproduce it on my machine, but I reproduced it *once* on drake006. It then worked many times in a row, regardless of whether I did `megaclear` and/or `yalmip('clear')`. There's no randomness in that test, so I'm not sure what's going on. 

The second and third seem to be new ways for the non-deterministic raycast terrain map tests to fail. I'll investigate, but I think the answer's just going to be to mark them as known issues.

**Comment by rdeits** [comment]
Yeah, that's consistent. On drake006, `testMISOSTrajectory` fails exactly once per startup of matlab, then works every time thereafter (I can't reproduce that behavior locally)

**Comment by rdeits** [comment]
The `testMISOSTrajectory` failure is a problem of global state being screwed up by manipulation of the java path (see #1239)

**Comment by RussTedrake** [comment]
as I said above, I believe these commits are covered in #1254.  will close this (trying to clear the queue).  reopen if i'm wrong.

**Comment by rdeits** [comment]
Yup, you're correct. Sorry for the duplicate

**Pull request closed without merging**
