### PR TITLE
[performance] Rewrite benchmark_tool infrastructure

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #15421.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please -- low priority.  I think this will start to become useful as we work on new performance experiments (after the current set of tickets conclude).

**Review by rpoyner-tri — COMMENTED** [review]
so far, so good. I tried some things I was accustomed to doing. Some worked, some not (for reasons outside this patch).
* pass through extra_args: `[blah...] -- --benchmark_repetitions=30`
*  compare: `bazel-drake/external/googlebenchmark/tools/compare.py  --help  # fails for lack of scipy.stats` 

I'll come back and do a detailed read of the code on a later pass.

> Reviewed 5 of 12 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490#-:-Mw3eHdB0TqDe2EF5Otk:byylp47)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor stuff

> Reviewed 2 of 12 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490#-:-Mw4mmP1DpbB8tVoVB3z:bo23mka)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15490#-Mw4l-9g7WfhrZYe2XRe:-Mw4l-9g7WfhrZYe2XRf:br0eh1f) (no related file):*
Do you want to also pay a visit to geometry/benchmarking? The programs there are a bit different (non-standard CLI, I think), but otherwise might eventually fit into this scheme.

Could also punt to a later PR.

---
___
*[tools/performance/README.md, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15490#-Mw4m_C122ZuhS2DWPV0:-Mw4m_C122ZuhS2DWPV1:be5kh57) ([raw file](https://github.com/robotlocomotion/drake/blob/176ad8aadc1825179268e564f8a4cb86a27de983/tools/performance/README.md#L8)):*
> ```Markdown
> Fully worked examples that integrate this tooling are available at:
> - drake/examples/multibody/cassie_benchmark
> - drake/systems/benchmarking
> ```

and acrobot-autodiff, ... and maybe geometry/benchmarking?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15490#-Mw4l-9g7WfhrZYe2XRe:-Mw5BU7kAF_uJe2yPcSx:b-j3fr4k) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do you want to also pay a visit to geometry/benchmarking? The programs there are a bit different (non-standard CLI, I think), but otherwise might eventually fit into this scheme.

Could also punt to a later PR.
</blockquote></details>

Done (via TODO).

---
___
*[tools/performance/README.md, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15490#-Mw4m_C122ZuhS2DWPV0:-Mw5Bp8B-t6ZLE5R5ESs:b-j3fr4k) ([raw file](https://github.com/robotlocomotion/drake/blob/176ad8aadc1825179268e564f8a4cb86a27de983/tools/performance/README.md#L8)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

and acrobot-autodiff, ... and maybe geometry/benchmarking?
</blockquote></details>

Done (via TODO).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with small nit and BTWs

> Reviewed 7 of 12 files at r1, 6 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490#-:-MwRhb3gDO48_wF2cDZz:bc3evzn)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/performance/benchmark_tool.py, line 58 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15490#-MwRghid7Wg419VXPXP8:-MwRghid7Wg419VXPXP9:bu3s5ci) ([raw file](https://github.com/robotlocomotion/drake/blob/eacd781e763b2afadaa90ee49b467e2a57e4e1f2/tools/performance/benchmark_tool.py#L58)):*
> ```Python
>     """Run sudo, passing all args to it."""
>     new_args = ["sudo"] + list(args)
>     print('Running: ', ' '.join([shlex.quote(x) for x in new_args]))
> ```

BTW If this only runs on 20.04 / Python 3.8, then you can use `shlex.join(new_args)`
___
*[tools/performance/defs.bzl, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15490#-MwRhCve-mV1DyvFsRWb:-MwRhCve-mV1DyvFsRWc:b-ew6d7r) ([raw file](https://github.com/robotlocomotion/drake/blob/eacd781e763b2afadaa90ee49b467e2a57e4e1f2/tools/performance/defs.bzl#L61)):*
> ```Starlark
>         fail("googlebench_binary must be local to this package")
>     dut = "drake/{}/{}".format(native.package_name(), googlebench_binary[1:])
>     _TEMPLATE = """
> ```

nit Unclear why this is `_GLOBAL_CONSTANT` casing.

Consider hoisting, or demoting casing to simply `template`?
___
*[tools/performance/defs.bzl, line 71 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15490#-MwRhMM8E9rgwfg5X8TQ:-MwRhMM8E9rgwfg5X8TR:bpufo72) ([raw file](https://github.com/robotlocomotion/drake/blob/eacd781e763b2afadaa90ee49b467e2a57e4e1f2/tools/performance/defs.bzl#L71)):*
> ```Starlark
>     env.update(runfiles.EnvVars())
>     os.execve(tool, [tool, "--binary", dut] + sys.argv[1:], env=env)
>     """.replace("\n    ", "\n")
> ```

BTW Consider adding comment, `# Poor man's dedent()`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[tools/performance/benchmark_tool.py, line 58 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15490#-MwRghid7Wg419VXPXP8:-MwRo73y17ZqZlziNTpD:blklisg) ([raw file](https://github.com/robotlocomotion/drake/blob/eacd781e763b2afadaa90ee49b467e2a57e4e1f2/tools/performance/benchmark_tool.py#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW If this only runs on 20.04 / Python 3.8, then you can use `shlex.join(new_args)`
</blockquote></details>

Done.

Though on second thought, I suppose it might be inadvertently tested in CI for 18.04.  I guess we'll see what Jenkins says.
___
*[tools/performance/defs.bzl, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15490#-MwRhCve-mV1DyvFsRWb:-MwRnflsCenYysh7ll8T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eacd781e763b2afadaa90ee49b467e2a57e4e1f2/tools/performance/defs.bzl#L61)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why this is `_GLOBAL_CONSTANT` casing.

Consider hoisting, or demoting casing to simply `template`?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15490)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
