### PR TITLE
Do not use pkg-config to find libjpeg and yaml-cpp

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #13309. I imagine there is some refactoring to support the general case of #13309, but this is in earlier to support #13102.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13335)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by jamiesnape** [comment]
Looks like `//solvers:dreal_solver_test` passes so maybe this is good enough for now pending #13219.

**Comment by jwnimmer-tri** [comment]
> It looks like the failure on focal is unrelated?

Yup, [Focal continuous](https://drake-jenkins.csail.mit.edu/view/Linux%20Focal%20Unprovisioned/job/linux-focal-unprovisioned-gcc-bazel-continuous-release/) isn't passing yet in general.  Jamie is close to getting it working, though, as part of this PR train.

**Pull request merged**
