### PR TITLE
Update to RobotLocomotion/director cfc770 to fix VERBOSE=1 in superbuild

### LINKED ISSUE #2136: VERBOSE=1 builds are broken
On a clean clone of drake, Ubuntu 14.04:
```
env PATH=/usr/lib/ccache:$PATH CXX=g++-4.9 CC=gcc-4.9 make options   # c, e, c, e, g
env PATH=/usr/lib/ccache:$PATH CXX=g++-4.9 CC=gcc-4.9 make VERBOSE=true
...
[ 41%] Performing build step for 'director'
cd /home/jwnimmer/jwnimmer-tri/drake/externals/director/distro/pods/drake-distro && make BUILD_PREFIX=/home/jwnimmer/jwnimmer-tri/drake/build BUILD_TYPE=Release
make[4]: Entering directory `/home/jwnimmer/jwnimmer-tri/drake/externals/director/distro/pods/drake-distro'
make -C pod-build true.SILENT
make: Entering an unknown directory
make: *** pod-build: No such file or directory.  Stop.
```

### PR DESCRIPTION
**Pull request by david-german-tri**
Closes #2136 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2180)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2180#-:-KGEH9eFOntZiCd3fjmH:-1868698381)*

**Comment by jwnimmer-tri** [comment]
Confirmed that the hash is the one that contains the fix.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2180#-:-KGEM9dEfHJZCp7RYzlT:-266880929)*

**Comment by jwnimmer-tri** [comment]
Ready to merge, depending on what jenkins has to say.

**Comment by david-german-tri** [comment]
Merging despite winRM flake and pre-existing #2154 failures.

**Pull request merged**
