### PR TITLE
mkdoc: switch to libclang-9-dev on Ubuntu

### LINKED ISSUE #13426: Switch to libclang-9-dev on Linux
There are various bugs related to using older clang versions with newer libstdc++ versions, e.g., https://bugs.llvm.org/show_bug.cgi?id=31852, https://bugs.llvm.org/show_bug.cgi?id=33222, which impact Focal. In particular, we see issues with `std::optional` when using `libclang-6.0.so` to extract the C++ Doxygen comments in order to create the Python documentation. `libclang-9.so` is the most recent version of the clang library available on Bionic and we already use `clang-format-9`.

Relates #13102. CC @jwnimmer-tri.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #13426. Relates #13102.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13437)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Comment by jamiesnape** [comment]
(failed focal build is expected, fixed by #13449)

**Comment by jamiesnape** [comment]
> I recall elsewhere you might have mentioned that the clang doc-gen targets were producing errors but not generating build failures? Was that accurate, and if so should we resolve that (better failure detection) before switching the library version here?

That is true, I will look into that before we merge this.

**Comment by jamiesnape** [comment]
> That is true, I will look into that before we merge this.

https://github.com/RobotLocomotion/drake/pull/13451

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Pull request merged**
