### PR TITLE
[workspace] Update and swap Gym dependencies

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19831.  Closes #19777.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19909)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.

Compared to #19831, the only changes to this subset are to a few comments here and there.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  Thank you so much for breaking this out from #19381 and for all of your help there.

+@sherm1 for platform review per rotation

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19909#-:-NaqeZmGALtLoY6pT8FK:bxwz3c0)* status: LGTM missing from assignee sherm1(platform)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19909)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one question

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19909#-:-NarW01PCWQ3dNJV_Cm3:b-ed7442)* status: 1 unresolved discussion

___
*[`tools/workspace/gym_py/package.BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19909#-NarUwvk2awZmMbpMBWA:-NarUwvl-881ZAyevCt_:b-vdn9rw) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd0364aa31b3ec2de6ab8e9687b685445ca545cb/tools/workspace/gym_py/package.BUILD.bazel#L11)):*
> ```
>     srcs = glob(["gym/**/*.py"]),
>     imports = ["gym"],
>     deprecation = ["The @gym_py external is deprecated and will be removed from Drake's WORKSPACE on or after 2023-12-01."],  # noqa
> ```

BTW should the deprecation method mention gymnasium_py ? (meta)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19909)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

___
*[`tools/workspace/gym_py/package.BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19909#-NarUwvk2awZmMbpMBWA:-NarcxjA4yx3za_6W8WM:brz334p) ([raw file](https://github.com/RobotLocomotion/drake/blob/bd0364aa31b3ec2de6ab8e9687b685445ca545cb/tools/workspace/gym_py/package.BUILD.bazel#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should the deprecation method mention gymnasium_py ? (meta)
</blockquote></details>

Great point, thanks.

**Pull request merged**
