### PR TITLE
[common] Add and use MatrixLikewise sugar typedef

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17497)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

\CC @hongkai-dai FYI

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending clarity on handing the `Derived::Options` and substantive changes to options in use.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17497#-:-N6JNeziBpCPA5GjkDRx:b-3kq09f)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/eigen_types.h` line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JHwqo0P5Rg942Jsvm:-N6JHwqo0P5Rg942Jsvn:brnk18b) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/eigen_types.h#L144)):*
> ```objc
>     Derived::RowsAtCompileTime, Derived::ColsAtCompileTime,
>     Derived::IsRowMajor ? Eigen::RowMajor : Eigen::ColMajor,
>     Derived::MaxRowsAtCompileTime, Derived::MaxColsAtCompileTime>;
> ```

minor: This doesn't necessarily capture the original `options` since there can be other ones besides storage order. (see [flags](https://eigen.tuxfamily.org/dox/group__flags.html)) I don't know when those matter; maybe they do for sparse matrices? It appears that anything derived from PlainObjectBase can provide `Derived::Options`; that might be useful here.

If you don't want to capture all the options, please just document that only storage order is preserved.
___
*[`common/extract_double.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JM4h234wHzehSP0lP:-N6JM4h234wHzehSP0lQ:b956hum) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/extract_double.h#L16)):*
> ```objc
> typename std::enable_if_t<
>     std::is_same_v<typename Derived::Scalar, double>,
>     MatrixLikewise<double, Derived>>
> ```

minor: as written, this is potentially capturing fewer options than before. Is that intentional? I have no objection but the change should be noted.
___
*[`common/symbolic_polynomial.h` line 548 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JMSEb6HmCCwakZVQC:-N6JMSEb6HmCCwakZVQD:b4mhvuo) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/symbolic_polynomial.h#L548)):*
> ```objc
> [[nodiscard]] std::enable_if_t<
>     std::is_same_v<typename Derived::Scalar, Polynomial>,
>     MatrixLikewise<double, Derived>>
> ```

minor: previously the returned matrix was always in column order; now it preserves the input order. If that's intentional the change should be noted. (Similarly for most of the other changes.)

There have been occasions when I wanted to create a column-ordered result even though the input was row ordered (generally because column ordered is the default so more "normal"). It's hard to tell if the original author intended that here.
___
*[`common/symbolic/expression/expression.h` line 1471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JNERXDG_KUIhJp2D7:-N6JNERXDG_KUIhJp2D8:b-kcfqtv) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/symbolic/expression/expression.h#L1471)):*
> ```objc
> typename std::enable_if_t<
>     std::is_same_v<typename Derived::Scalar, symbolic::Expression>,
>     MatrixLikewise<double, Derived>>
> ```

minor: loss of Derived::Options here

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17497)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

___
*[`common/eigen_types.h` line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JHwqo0P5Rg942Jsvm:-N6Jnja28jC1Fdyx0xCv:b-7lrczu) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/eigen_types.h#L144)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: This doesn't necessarily capture the original `options` since there can be other ones besides storage order. (see [flags](https://eigen.tuxfamily.org/dox/group__flags.html)) I don't know when those matter; maybe they do for sparse matrices? It appears that anything derived from PlainObjectBase can provide `Derived::Options`; that might be useful here.

If you don't want to capture all the options, please just document that only storage order is preserved.
</blockquote></details>

I've clarified in the docs that this type always chooses the default alignment.

See [Matrix docs](https://eigen.tuxfamily.org/dox/classEigen_1_1Matrix.html) and [SparseMatrix](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html).  The only Options for a Matrix or are row/col-major and alignment, and the only Options for a SparseMatrix are row/col-major. The flags you linked are not Matrix Options, they are bits for the xpr tooling in `Eigen::internal::traits<>::Flags` and do not make sense in the context of the Options template argument to a Matrix.
___
*[`common/extract_double.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JM4h234wHzehSP0lP:-N6JuHh34-SDg1fDqOpL:b-i8c1yh) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/extract_double.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: as written, this is potentially capturing fewer options than before. Is that intentional? I have no objection but the change should be noted.
</blockquote></details>

OK I've added a mention of the behavior change in the commit message.
___
*[`common/symbolic_polynomial.h` line 548 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JMSEb6HmCCwakZVQC:-N6JumPJ5j2H_4y6zwqG:b-lxbu4b) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/symbolic_polynomial.h#L548)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: previously the returned matrix was always in column order; now it preserves the input order. If that's intentional the change should be noted. (Similarly for most of the other changes.)

There have been occasions when I wanted to create a column-ordered result even though the input was row ordered (generally because column ordered is the default so more "normal"). It's hard to tell if the original author intended that here.
</blockquote></details>

Working

I've asked on `#optimization` slack to see which choice people prefer.

I've give it a day for people to weigh in.  (Waiting for tomorrow's on-call platform in any case.)
___
*[`common/symbolic/expression/expression.h` line 1471 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JNERXDG_KUIhJp2D7:-N6JqQ0A8VLVE2ijYwFd:bcm5tpt) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/symbolic/expression/expression.h#L1471)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: loss of Derived::Options here
</blockquote></details>

I don't think propagating DontAlign would be useful?  Aligning the double-valued Matrix result seems like an improvement.

I've added a mention of the behavior change in the commit message.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17497)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17497#-:-N6KShZ09h6WeVmSjZfA:b-z0s7k5)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[`common/symbolic_polynomial.h` line 548 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17497#-N6JMSEb6HmCCwakZVQC:-N6KS_qIDxW3bt9_nk3M:b-42o0mr) ([raw file](https://github.com/robotlocomotion/drake/blob/a02301c6c7fe24c5aacb8855e5b283b14bc7d82b/common/symbolic_polynomial.h#L548)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I've asked on `#optimization` slack to see which choice people prefer.

I've give it a day for people to weigh in.  (Waiting for tomorrow's on-call platform in any case.)
</blockquote></details>

OK The current choice in this PR had enough upvotes in slack that I'm satisfied with this as-is. 

(This little helper is just sugar after all.  If a user wants a more particular behavior, they can still write their own little helper that does something more specific.)

**Pull request merged**
