### PR TITLE
Moves iiwa model into models directory, updates folder name to match model name.

### PR DESCRIPTION
**Pull request by liangfok**
Towards #5317. This directory structure better conforms to the [Model Database Structure](http://gazebosim.org/tutorials?tut=model_structure&cat=build_robot.%3C/p%3E#ModelDatabaseStructure).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5329)

### CODE REVIEW

**Comment by sherm1** [comment]
I love those commit comments!

**Comment by liangfok** [comment]
Heh. :) This is a situation where I am unable to run some tests due to the lack of a solver so I am using CI to test. I will squash these bogus commits once it works.

**Comment by sammy-tri** [comment]
I had somehow missed (or forgotten) the existence of the model database structure.  Informative!

**Comment by liangfok** [comment]
+@naveenoid for feature review please. Thanks!

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke1cOmPeS88MEcv-5Fl:b6vf9m8)*

**Comment by naveenoid** [comment]
Thanks for this! BTW: Just for completeness, perhaps you want to leave a README in the models folder briefly mentioning the models (and features) located within? Like a simple list..

Also, between this PR and @siyuanfeng-tri 's #5321 and #5339 there needs to be an agreement on who gets to do the rebase since those two might land soon (especially #5321).

Otherwise, :lgtm: 

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke3Hc0v2NK6MDJVJe8s:bist3by)*

**Comment by naveenoid** [comment]
Reviewed 56 of 56 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329)*

**Comment by liangfok** [comment]
@naveenoid, I addressed your comment by adding a README. PTAL. @siyuanfeng-tri feel free to merge first.

---

Review status: 31 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke3q8W5JptgUjikcexc:bq2w25a)*

**Comment by siyuanfeng-tri** [comment]
@liangfok cool, hopefully i will merge 5321 first. will keep you updated. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke42_YTYu4cStm_1wuA:b-gv4xlc)*

**Comment by sherm1** [comment]
:lgtm: pending one BTW, ptal.

---

Reviewed 53 of 56 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/models/README.md, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-Ke5EWGKV7rPvJFpb0s_:-Ke5EWGKV7rPvJFpb0sa:bh9jr92) ([raw file](https://github.com/robotlocomotion/drake/blob/6009f0af072dfafda254ca7b158f02ea1f27a8eb/drake/examples/kuka_iiwa_arm/models/README.md#L4)):*
> ```Markdown
> the KUKA iiwa arm. For more details, see the `model.config` files within their
> subdirectories. This directory is organized according to the
> [model database structure](http://gazebosim.org/tutorials?tut=model_structure&cat=build_robot.%3C/p%3E#ModelDatabaseStructure).
> ```

BTW, it would be more accurate to say something like "this directory is organized similarly to the Model Database". It is missing some things and contains urdf and obj files while the Gazebo structure only talks about sdf files with stl & collada. Would be helpful to say in what way our organization here *differs* from theirs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke5VMu1JMxsjH0ByGMC:b-1jj0h4)*

**Comment by liangfok** [comment]
Review status: 33 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/models/README.md, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-Ke5EWGKV7rPvJFpb0s_:-Ke5zRcFUHhJ4S5Sz5NF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6009f0af072dfafda254ca7b158f02ea1f27a8eb/drake/examples/kuka_iiwa_arm/models/README.md#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, it would be more accurate to say something like "this directory is organized similarly to the Model Database". It is missing some things and contains urdf and obj files while the Gazebo structure only talks about sdf files with stl & collada. Would be helpful to say in what way our organization here *differs* from theirs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329)*

**Comment by liangfok** [comment]
This PR is now blocked on #5321.

---

Review status: 33 of 34 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke5zYMDGP497dAfXvys:br2ynmk)*

**Comment by siyuanfeng-tri** [comment]
ci hates me today.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke65EhNkpXBs1RngOH8:buuujex)*

**Comment by liangfok** [comment]
:sob: 

---

Review status: 33 of 34 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329#-:-Ke6BCsBLQCN4ywAj4c1:bnjoe47)*

**Comment by siyuanfeng-tri** [comment]
merged!

**Comment by liangfok** [comment]
Yay! I'll update this PR ASAP.

**Comment by siyuanfeng-tri** [comment]
thanks!

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5329)*

**Pull request merged**
