### PR TITLE
Fix reported WSG finger velocity

### PR DESCRIPTION
**Pull request by sammy-tri**
Use the correct constants for the position and velocity offsets in the WSG state

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7865)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@hongkai-dai for testing / feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865#-:-L3jGuTx3N1ivNpTv3NA:bl2u5b6)*

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865#-:-L3jItoxqI3CYe_o50I8:b-mkkz8q)*

**Comment by soonho-tri** [comment]
FYI,
```
17:02:54 examples/kuka_iiwa_arm/dev/pick_and_place/lcm_plant.cc:289:9: 
error: 'kSchunkWsgPositionIndex' is not a member of 'drake::manipulation::schunk_wsg'
17:02:54          manipulation::schunk_wsg::kSchunkWsgPositionIndex,
17:02:54          ^
17:02:54 examples/kuka_iiwa_arm/dev/pick_and_place/lcm_plant.cc:290:9: 
error: 'kSchunkWsgVelocityIndex' is not a member of 'drake::manipulation::schunk_wsg'
17:02:54          manipulation::schunk_wsg::kSchunkWsgVelocityIndex);
```

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865#-:-L3jP2GLhoz0gZ0jDV1x:b-qhipb2)*

**Comment by hongkai-dai** [comment]
I added `#include "drake/manipulation/schunk_wsg/schunk_wsg_constants.h"` and then it works.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865#-:-L3jRamTkoqY2hrsLSGM:b-5ae8p7)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865)*

**Comment by sammy-tri** [comment]
Whoops, fix pushed.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865#-:-L3jSmwc28dDQrvzo2fS:b19apel)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7865#-:-L3jTI6x_zVzE0VSLi2r:bnfp4nl)*

**Pull request merged**
