### PR TITLE
Add Automatic Differentiated Jacobians to Velocity-Implicit Euler Integrator, fourth PR of #12528

### PR DESCRIPTION
**Pull request by antequ**
Add Automatic Differentiated Jacobians to Velocity-Implicit Euler Integrator, fourth PR of #12528

This commit:
1. Adds automatic differentiation as a velocity-Jacobian computation scheme for the velocity-implicit Euler integrator, by following the model of ImplicitIntegrator<T>::ComputeAutoDiffJacobian().
2. Refactors ComputeLOfY() based on the templated <U> IntegratorBase<T>::EvalTimeDerivatives() to enable this computation.
3. Fixes the tests so that they reset integrators between testing the different Jacobian computation schemes, to force Jacobian recomputations.
4. Removes the boolean flags that skip tests that require AutoDiff'd Jacobians.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12967)

### CODE REVIEW

**Comment by antequ** [comment]
___
*[systems/analysis/velocity_implicit_euler_integrator.cc, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12967#-M3hQeoN8cciwVc182aU:-M3hUpwwD2hV1o_4NvQm:b-vl9u77) ([raw file](https://github.com/robotlocomotion/drake/blob/da39a5313de6285de225fd53baa78dcb2f88f3f1/systems/analysis/velocity_implicit_euler_integrator.cc#L186)):*
<details><summary><i>Previously, antequ (Ante Qu) wrote…</i></summary><blockquote>

Perhaps these should be DRAKE_ASSERTs (or removed)? this only needs to be sanity checked in debug runs.
</blockquote></details>

(I'm not certain on the policy for DRAKE_DEMAND vs DRAKE_ASSERT)

**Comment by jwnimmer-tri** [comment]
@amcastro-tri Do you actually want platform review now, before the other PRs lands first?

**Comment by antequ** [comment]
___
*[systems/analysis/velocity_implicit_euler_integrator.cc, line 153 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12967#-M4o5xsl93E0rm7ShmZo:-M4oNoK56BHFaKt6ph8Q:b-u7t3f5) ([raw file](https://github.com/robotlocomotion/drake/blob/d9e75992c686f22c7055f2254ff16d0ff63244a2/systems/analysis/velocity_implicit_euler_integrator.cc#L153)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

maybe it makes more sense to place these one time allocastions in `DoInitialize()`?
</blockquote></details>

These are not needed if the user does not want to calculate an Autodiff Jacobian. For example, if a system can’t be converted to autodiff, if I put this in doInitialize, then the user would not be able to run Numerically differentiated jacobians. I placed them here because I didn’t want this operation to occur for systems that are not autodiff able.

**Comment by jwnimmer-tri** [comment]
> @amcastro-tri Do you actually want platform review now, before the other PRs lands first?

Retracted.

**Pull request merged**
