### PR TITLE
Refactor install prerequisites scripts

### LINKED ISSUE #7786: Mac install_prereqs.sh upgrades everything
I was surprised to see just how long `install_prereqs.sh` takes on mac until I noticed that it runs `brew upgrade`, which upgrades every single homebrew package on the system, including those not used by Drake. This seems like a somewhat unfriendly thing to do without warning, as it could be the source of lots of other subtle versioning issues for packages entirely outside the Drake ecosystem.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #7786 among other things. Linux changes are pretty superficial at present. I need to factor out the `apt` packages into a separate file to help with `.deb` packaging, but that will follow later.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8081)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for Mac feature review and +@jwnimmer-tri for Linux feature review. Please test the installed version too.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
> I need to factor out the apt packages into a separate file to help with .deb packaging, ...

Yay!

> Please test the installed version too.

With the Ubuntu side just a rename, do you think a visual inspection of the installed-version diffs would be good enough?

**Comment by jamiesnape** [comment]
> With the Ubuntu side just a rename, do you think a visual inspection of the installed-version diffs would be good enough?

Yes.

**Comment by jwnimmer-tri** [comment]
LGTM on read-through, not yet tried locally.

---

Reviewed 4 of 11 files at r1.
Review status: 3 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8081#-:-L5PXUzIWXopMtjmwqzO:b42v6p9)*

**Comment by jwnimmer-tri** [comment]
:lgtm: ubuntu

---

Review status: 3 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8081#-:-L5PYXZeUM4Ev0ojDl74:b-usv0mi)*

**Comment by soonho-tri** [comment]
:lgtm: tested on :apple:

BTW (not the scope of this PR), is `pcl` package something safe to install? I've found that I need it to test Drake installation via `drake-shambhala/drake_cmake_installed`.

---

Reviewed 8 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8081#-:-L5PY8YyERyZX1M2a8Wc:bcja72x)*

**Pull request merged**
