### PR TITLE
mbp, geometry: Show non-determinism for discrete mbp + contact

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
From Anzu issue

Issues this reproduces (I think?):
- #13507
- #13506

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13505)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
BTW @SeanCurtis-TRI and @DamrongGuoy Thanks for y'all's help in debugging this!
Sorry I couldn't distill it much more than this...

**Comment by amcastro-tri** [comment]
TL;DR, but I wonder if related to #12786

**Comment by EricCousineau-TRI** [comment]
> (Although I really wish it were in C++ so I didn't have to build all of drake just to get to it....:D) [...]

Of course I do not wish it were C++ - nor do I want to put in the effort to translate it, and I think this would've taken me about 10x longer to explore in C++!
But agreed on the build time! I wish that I didn't have to build the attic, examples, etc., just to get MBP + Systems.

FTR, though, I've been doing `pydrake` development and usage of `pydrake` in Anzu on my P51 laptop. So compile times aren't really *that* bad - just a good time to snag coffee ;)

Relates #6760, #7294

If you do find that you *avoid* using `pydrake` purely for this reason, might you be able to post on these issues?

**Comment by sherm1** [comment]
I ran a couple of quick tests using this nice program. Some observations:

- Repeated runs of the test framework don't produce exactly the same result, even with no code changes. For example, here is a diff from two consecutive runs:
```
31c31
<       recreate: BAD  (num_unique = 4)
---
>       recreate: BAD  (num_unique = 3)
36c36
<       recreate: BAD  (num_unique = 4)
---
>       recreate: BAD  (num_unique = 3)
55c55
<       recreate: BAD  (num_unique = 3)
---
>       recreate: BAD  (num_unique = 4)
```

- I bound DisableCaching() and used it wherever I saw a context allocated. That had suprisingly little effect on the results and was also not completely repeatable.
- Also note that we are getting indeterminism when _recreating_, which should be repeatable under any sensible set of bugs!

Taken together the above makes me think of uninitialized memory being used somewhere.

**Comment by jwnimmer-tri** [comment]
Bringing forward one of my (baseless) hypothesis from the Anzu issues on the #13507 (geometry) front...

Something like ASLR can change the run-to-run values of pointer addresses, and so anything that iterates over, e.g., `unordered_map<Foo*, Bar>` or even `std::set<Foo*>` will have a different iteration order from one run to the next.  This can be a common cause of non-determinism, and it looked to me (in the far past, IIRC) that FCL had such collections that used pointer order to govern iteration order.

**Comment by jwnimmer-tri** [comment]
But that does remind me -- we should ensure that all of the tests are clean under ubasn and valgrind, before we start to debug the program logic.  That's the low-hanging fruit.

**Comment by EricCousineau-TRI** [comment]
@sherm1 Could you PR your changes for the `DisableCaching` stuff against my branch? I'd like to merge it in! (and also, more importantly, PR the bindings for `DisableCaching` separately)

> Repeated runs of the test framework don't produce exactly the same result, [...]

Yuppers. That was actually the point of `meta_trials`, but I didn't really capture that in the overview stuff. Will add that in.

**Comment by sherm1** [comment]
> @sherm1 Could you PR your changes for the DisableCaching stuff against my branch? 

@EricCousineau-TRI The only reason I didn't do that is I don't know how to find my way around in the bindings. DisableCaching is a method of ContextBase rather than Context. I was able to stumble around until I landed on bindings for Context, which is mysteriously located in `framework_py_semantics.cc`. I hadn't lucked onto ContextBase so I just added the DisableCaching binding to Context to run my experiment. (Obviously not good enough to check into Drake.)

Is there a magic trick that would allow me to locate bindings for a particular class within pydrake? Searching for the class name produces _many_ false positives to wade through. One thought I had was that there weren't currently any ContextBase bindings but I don't know how I could know that for sure.

I'm sure I can answer these questions myself after thrashing around long enough. That seems like an unreasonable effort for tiny additions to pydrake though. Suggestions?

**Comment by EricCousineau-TRI** [comment]
Good questions, but I think belongs in a separate thread! You OK with opening a new issue?
If not, I'm happy to open that issue!

**Comment by EricCousineau-TRI** [comment]
Sorry - we should def. open a separate thread on the part where you were thrashing.

To answer the acute question: Yeah, just add them `Context<T>` for now, in `framework_py_semantics.cc`

**Comment by sherm1** [comment]
cc @rpoyner-tri

**Comment by sherm1** [comment]
@EricCousineau-TRI looks like #12055 might already be the other thread. I'll add my comments there.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Changed dispositions - sorry about that!

**Pull request closed without merging**
