### PR TITLE
Adds ability to clone a RigidBody.

### PR DESCRIPTION
**Pull request by liangfok**
This was extracted out of #4958.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4987)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-:-KbqBDogfkzGr1FhcTq-:b-57wv7n)*

**Comment by amcastro-tri** [comment]
Just a few BTW's. :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVIDwPWroNVAkuu0u:-KbvVIDwPWroNVAkuu0v:bv5c1z) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.cc#L27)):*
> ```cpp
> }
> 
> // TODO(liang.fok) For an explanation of why these SWIG preprocessor commands
> ```

BTW. Maybe remove TODO?

---

*[drake/multibody/rigid_body.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVbtqm_YSJhvNfA1U:-KbvVbtqm_YSJhvNfA1V:b-pizpzz) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.cc#L78)):*
> ```cpp
>     return false;
>   }
>   if (other.has_parent_body()) {
> ```

BTW, this is not a comparison right? remove?

---

*[drake/multibody/rigid_body.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVBr9B4LTaVVn8EMe:-KbvVBrANqO8qXC63MFs:baba8xo) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.h#L24)):*
> ```objc
>   RigidBody();
> 
>   // TODO(liang.fok) The following preprocessor condition is necessary because
> ```

BTW. So, is this a TODO? or just a comment. Maybe remove TODO?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-:-KbvWg6_t6EvswKFukBi:b-le9lp5)*

**Comment by amcastro-tri** [comment]
+@sammy-tri for platform please.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-:-KbvWkA1Gk3hnwezamfs:b-qyiu9)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVIDwPWroNVAkuu0u:-KbvXQCq498wBMHYZsY8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.cc#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW. Maybe remove TODO?
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVbtqm_YSJhvNfA1U:-KbvXScpVykfDcv5VD7g:b-347xhn) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.cc#L78)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, this is not a comparison right? remove?
</blockquote></details>

`RigidBody::Clone()` is documented to _not_ clone the parent. This checks to verify that the parent is in fact not set in the cloned `RigidBody`.

---

*[drake/multibody/rigid_body.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVBr9B4LTaVVn8EMe:-KbvXwW7HIG4YVqRrYVa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.h#L24)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW. So, is this a TODO? or just a comment. Maybe remove TODO?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987)*

**Comment by amcastro-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVbtqm_YSJhvNfA1U:-KbvYg1piXNaxPFTgkB0:b-k0s170) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.cc#L78)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

`RigidBody::Clone()` is documented to _not_ clone the parent. This checks to verify that the parent is in fact not set in the cloned `RigidBody`.
</blockquote></details>

yes, but this method is called `CompareToClone()` not `VerifyTheResultOfTheCloneMethod()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987)*

**Comment by liangfok** [comment]
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

*[drake/multibody/rigid_body.cc, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-KbvVbtqm_YSJhvNfA1U:-KbvZ7wA6tsKOG19y040:b-qu6n94) ([raw file](https://github.com/robotlocomotion/drake/blob/f59ff2621d7720556979a6a708a7621372ff5797/drake/multibody/rigid_body.cc#L78)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

yes, but this method is called `CompareToClone()` not `VerifyTheResultOfTheCloneMethod()`.
</blockquote></details>

Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4987#-:-KbzHdQVeDqHOMXt_prs:bnfp4nl)*

**Pull request merged**
