### PR TITLE
[fem] Move constitutive model test utils out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16562)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16562#-:-MvW1iQH55berDQw47ri:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16562#-MvW1TDS7wpVZz8bkxx1:-MvW1TDS7wpVZz8bkxx2:b25hr9q) ([raw file](https://github.com/robotlocomotion/drake/blob/1c1a25344a75d9fcbd52ba1369bcb166cb5c5d3a/multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc#L170)):*
> ```cpp
> }
> 
> template void TestParameters<LinearConstitutiveModel<double, 1>>();
> ```

FYI, the instantiations are removed here since `LinearConstitutiveModel` and `CorotatedModel` are still in dev. Once the models are moved out of dev, the instantiations and the corresponding tests will be re-enabled.

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: , with a question

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16562#-:-Mvcs10k79LalgKz5CFK:b-nd0204)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16562#-MvcroI87y7PR11F0vef:-MvcroI87y7PR11F0veg:b-9yv9e3) ([raw file](https://github.com/robotlocomotion/drake/blob/b901345fdf3fd18329ca2e10ccd24272b64d5e7e/multibody/fem/test/constitutive_model_test_utilities.cc#L62)):*
> ```cpp
> 
>   DRAKE_EXPECT_THROWS_MESSAGE((Model(-1.0, 0.25)),
>                               "Young's modulus must .**");
> ```

Why these changes (here and below) in the messages? don't we want the more specific tests?

**Review by xuchenhan-tri — COMMENTED** [review]
+@ggould-tri for platform review on Monday per rotation please.
Only non-dev files needs review. Those non-dev files are coming out of dev, so they require a full review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16562#-:-MvdvKFY0aqQ2qvdXoxP:b-cb0hai)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @amcastro-tri and @ggould-tri)

___
*[multibody/fem/test/constitutive_model_test_utilities.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16562#-MvcroI87y7PR11F0vef:-MvduoyS811oS2_TOZEy:b-d7ufkg) ([raw file](https://github.com/robotlocomotion/drake/blob/b901345fdf3fd18329ca2e10ccd24272b64d5e7e/multibody/fem/test/constitutive_model_test_utilities.cc#L62)):*
> nit I'm not sure that matching against the full floating point suggestion is adding any value to the test, and will cause unnecessary test churn if you ever decide to improve the message.

Quote from platform reviewer in a PR where the same exception is tested. I'm ok either way since this is only testing code path. I'm happy to comply if you have a strong reason.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16562#-:-MvskbDnBm9GvIu0FQZp:bnfp4nl)* status: 2 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/test/constitutive_model_test_utilities.h, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16562#-MvsdoVA-z0tMFuztJPG:-MvsdoVA-z0tMFuztJPH:b-otrbil) ([raw file](https://github.com/robotlocomotion/drake/blob/873e8714d25cf11aeb316c1e917f9b7c2d94da6d/multibody/fem/test/constitutive_model_test_utilities.h#L4)):*
> ```objc
> 
> /** @file
>  This file provides utilities that facilitates testing the subclasses of
> ```

typo: plural/singular mismatch.



_Suggestion:_
```objc
utilities that facilitate
```

**Pull request merged**
