### PR TITLE
[doc] Improve code block formatting in API docs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For my sense of style, this presentation layout is still a bit rough, but it seems like enough of an improvement to land now, and let others improve upon over time.  At least this solves the tricky build system parts; the rest is just html & css fu.

---

C++ sample:

---

Python sample:

---

Towards #12591.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20083)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20083)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@sammy-tri for platform, please.

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20083#-:-Nd_y4CRC-dt-oiZ8sXp:b-ifbuaf)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`doc/doxygen_cxx/build.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20083#-Nd_u6tGEzzigkc6iZTh:-Nd_u6tH1TRZLZ94iT-i:bqnut84) ([raw file](https://github.com/RobotLocomotion/drake/blob/09f15f6d163d6d8097bb6c9cf5e7c1826a807071/doc/doxygen_cxx/build.py#L256)):*
BTW I had a hard time parsing this paragraph. Over various reads, it sometimes struck me as a TODO missing its prefix. Now that I've read through the whole PR, I think I better understand the intent of what's here.

As I cobbled an alternative phrasing together, I recognized that the current text covers all the facts and is correct. At best, my proposed text tries to mitigate some subtle nuances arising from information bias. I'm leaving this as a BTW because I can't make the argument that it is worth the change. The most important part of this discussion is that the significance of what was written in this code only became clear to me via multiple re-reads and cross referencing. If you have thoughts of your own to clarify it for a reader that isn't reading it from a perspective of someone who fought the battle you've fought, that would be helpful.

So, here's a possible alternative:

> Replace the temporary <span> tags with <details> in @python_details_{begin, end}. <details> provides the desired functionality, but our current version of Doxygen doesn't support the tag. So, we use <span> in the doxygen configuration and then upgrade it to <details> here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20083)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`doc/doxygen_cxx/build.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20083#-Nd_u6tGEzzigkc6iZTh:-NdaFMnt-uq26uWIDzkG:botv9kk) ([raw file](https://github.com/RobotLocomotion/drake/blob/09f15f6d163d6d8097bb6c9cf5e7c1826a807071/doc/doxygen_cxx/build.py#L256)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Reviewable ate your HTML in a hilarious way.  Anyway, I've pushed what I hope is an improvement.
</blockquote></details>

Oh, yeah, that is pretty funny.

The new comment is perfect. Thanks.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20083#-:-NdbJ6rP9xE9LCIM-vc6:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
