### PR TITLE
Implements a class to track rigid body poses and velocities.

### PR DESCRIPTION
**Pull request by rcory**
Moving FramePoseTracker to its own PR to satisfy PR size limit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7291)

### CODE REVIEW

**Comment by rcory** [comment]
+@naveenoid for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-:-KwkM00Dghvd5gZMQM9D:b-jlfufc)*

**Comment by naveenoid** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/BUILD.bazel, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkUeqCcIqcI6LoxnhT:-KwkUeqCcIqcI6LoxnhU:b-df9tsr) ([raw file](https://github.com/robotlocomotion/drake/blob/6bb365b5083c2118966d3ea393b8cdc7e4ddb65d/drake/manipulation/util/BUILD.bazel#L118)):*
> ```
>         "//drake/systems/rendering:frame_velocity",
>         "//drake/systems/rendering:pose_bundle",
>         "@optitrack_driver//lcmtypes:optitrack_lcmtypes",
> ```

I think this dep is unnecessary.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkTf3C0nbHmlD0GQvv:-KwkTf3C0nbHmlD0GQvw:b-ou9bmj) ([raw file](https://github.com/robotlocomotion/drake/blob/6bb365b5083c2118966d3ea393b8cdc7e4ddb65d/drake/manipulation/util/frame_pose_tracker.cc#L28)):*
> ```cpp
>   if (frames == nullptr) {
>     throw std::runtime_error("FramePoseTracker::FramePoseTracker: ERROR: "
>                                  "found nullptr to frames vector.");
> ```

BTW: This error message sounds a bit funny. How about "frames vector is a nullptr".

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkTrbC-RaYDYcOAmzN:-KwkTrbC-RaYDYcOAmzO:b-h9wqrt) ([raw file](https://github.com/robotlocomotion/drake/blob/6bb365b5083c2118966d3ea393b8cdc7e4ddb65d/drake/manipulation/util/frame_pose_tracker.cc#L31)):*
> ```cpp
>   } else if (frames->size() == 0) {
>     throw std::runtime_error("FramePoseTracker::FramePoseTracker: ERROR: "
>                                  "found nullptr to frames vector.");
> ```

BTW: This error message sounds a bit funny. How about "frames vector is of 0 size".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291)*

**Comment by naveenoid** [comment]
Just couple of minor things. :lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-:-KwkUv41LIOKOyyW0x50:b-omm3l2)*

**Comment by rcory** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/BUILD.bazel, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkUeqCcIqcI6LoxnhT:-KwkYCDUhLgn3jdu5fAh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6bb365b5083c2118966d3ea393b8cdc7e4ddb65d/drake/manipulation/util/BUILD.bazel#L118)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I think this dep is unnecessary.
</blockquote></details>

Done.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkTf3C0nbHmlD0GQvv:-KwkYWsq88vyn9dELNdC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6bb365b5083c2118966d3ea393b8cdc7e4ddb65d/drake/manipulation/util/frame_pose_tracker.cc#L28)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: This error message sounds a bit funny. How about "frames vector is a nullptr".
</blockquote></details>

Done.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkTrbC-RaYDYcOAmzN:-KwkYidj4-7KBq-p6WG3:butqcof) ([raw file](https://github.com/robotlocomotion/drake/blob/6bb365b5083c2118966d3ea393b8cdc7e4ddb65d/drake/manipulation/util/frame_pose_tracker.cc#L31)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: This error message sounds a bit funny. How about "frames vector is of 0 size".
</blockquote></details>

Copy paste bug. Good catch. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291)*

**Comment by rcory** [comment]
+@ggould-tri for platform review please.

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-:-Kwka_aQHdu8DNZI7_WN:b-irfx5k)*

**Comment by ggould-tri** [comment]
Thanks for the factoring!

I've noted a pile of very minor syntactic and stylistic nits below.  The feature overall is quite nice; :lgtm:.

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwktpuTjP0RlTP3TOOL:-KwktpuTjP0RlTP3TOOM:bam0243) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.cc#L35)):*
> ```cpp
> 
>   // Confirm all rigid bodies and frame names are valid.
>   for (auto it = frames->begin(); it != frames->end(); ++it) {
> ```

FYI this might be clearer as a range-based for loop, `for (auto frame : frames)`.  Author's discretion.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkzU01HJugtp29nWpi:-KwkzU01HJugtp29nWpj:b-hlrosb) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.cc#L71)):*
> ```cpp
>   // map key for @p frame_info ensures that frame names coming in are unique.
>   auto m_it = frame_info.begin();
>   auto v_it = frame_poses.begin();
> ```

FYI "m" and "v" don't have any obvious meaning here; can you give these more informative names?

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkv5S6HrAm2a0nOJO6:-Kwkv5S6HrAm2a0nOJO7:b71gwku) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.cc#L102)):*
> ```cpp
> 
> void FramePoseTracker::OutputStatus(const systems::Context<double>& context,
>                                         PoseBundle<double>* output) const {
> ```

FYI --
(1) The indentation here is surprising; check if you editor or formatter likes it.
(2) The names "kres", "fvel", and "svel" here are unnecessarily abbreviated.  It would be more readable if you expanded them out as you have most of the other variable names in this file.

---

*[drake/manipulation/util/frame_pose_tracker.h, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkwUiT9Qmbe6nRf6IR:-KwkwUiT9Qmbe6nRf6IS:b-24rte0) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.h#L50)):*
> ```objc
>    *        vector should have a name that is unique, i.e., the std::string
>    *        returned by RigidBodyFrame::get_name() should not match any other
>    *        frame name.
> ```

FYI -- Since your intention is to transfer ownership, it might be clearer to pass `frames` by rvalue reference than by pointer (ie, `std::vector<...>&& frames`, requiring the caller to `std::move` away the vector they are giving up and relieving you of having to clear it to prevent misuse).

Your version is reasonable, so do whichever seems clearer to you.

---

*[drake/manipulation/util/frame_pose_tracker.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkq3RsnPZtWbQQS9bS:-Kwkq3RsnPZtWbQQS9bT:btixx7c) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.h#L52)):*
> ```objc
>    *        frame name.
>    * @throws std::runtime_error if any frame has a non-unique name or the frame
>    *         is not attached to a RigidBody (i.e., it's RigidBody pointer is
> ```

FYI:
(1) typo "it's" should be "its".
(2) `std::runtime_error` is also thrown in frames is null or empty.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkxtkz5f0aO7uBdyU2:-Kwkxtkz5f0aO7uBdyU3:b9wdpa) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L57)):*
> ```cpp
>     // the pose offset.
>     for (auto it = frame_info_.begin();
>          it != frame_info_.end(); ++it) {
> ```

FYI a range-based for loop might be clearer here.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 122 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkyQDg9qFec3khokKD:-KwkyQDg9qFec3khokKE:b-nipl16) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L122)):*
> ```cpp
> TEST_F(FramePoseTrackerTest, InvalidFrameNameTest) {
>   EXPECT_EQ(frames_.size(), 3);
>   frames_[2]->set_name("iiwa_frame_0");  // repeat first frame name
> ```

FYI complete sentence in comment requires capitalization and punctuation.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 132 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkyUseEwRpBjN41gHr:-KwkyUseEwRpBjN41gHs:b-nipl16) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L132)):*
> ```cpp
>   // Update the input, calculate the output, and compare it with expected pose.
>   KinematicsResults<double> kres(tree_.get());
>   VectorX<double> q(7), v(7);  // sets iiwa positions and velocities
> ```

FYI complete sentence in comment requires capitalization and punctuation.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkyVR_pwDsyUwTuTVB:-KwkyVR_pwDsyUwTuTVC:b-nipl16) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L133)):*
> ```cpp
>   KinematicsResults<double> kres(tree_.get());
>   VectorX<double> q(7), v(7);  // sets iiwa positions and velocities
>   q << 0.3, 0.3, 0.3, 0, 0, 0, 0;  // pick an arbitrary iiwa pose
> ```

FYI complete sentence in comment requires capitalization and punctuation.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkya1_LwMro46Z7t7O:-Kwkya1aeHPyj-J1NcoN:b9wdpa) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L145)):*
> ```cpp
>   }
> 
>   for (auto it = frames_.begin(); it != frames_.end(); ++it) {
> ```

FYI a range-based for loop might be clearer here.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 167 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkycnuU4YAlxiTGIfI:-KwkycnuU4YAlxiTGIfJ:b-nipl16) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L167)):*
> ```cpp
>   // Update the input, calculate the output, and compare it with expected pose.
>   KinematicsResults<double> kres(tree_.get());
>   VectorX<double> q(7), v(7);  // sets iiwa positions and velocities
> ```

FYI complete sentence in comment requires capitalization and punctuation.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 168 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkydD4m5zyCKjieYsp:-KwkydD4m5zyCKjieYsq:b-nipl16) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L168)):*
> ```cpp
>   KinematicsResults<double> kres(tree_.get());
>   VectorX<double> q(7), v(7);  // sets iiwa positions and velocities
>   q << 0.3, 0.3, 0.3, 0, 0, 0, 0;  // pick an arbitrary iiwa pose
> ```

FYI complete sentence in comment requires capitalization and punctuation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-:-Kwkp40_vWJmjop93hTO:b-qcylyi)*

**Comment by rcory** [comment]
Review status: 1 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwktpuTjP0RlTP3TOOL:-KwlYzOldBORaJtfTj44:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.cc#L35)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI this might be clearer as a range-based for loop, `for (auto frame : frames)`.  Author's discretion.
</blockquote></details>

Done.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 71 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkzU01HJugtp29nWpi:-KwlcUVe1FLMlBLnjK2P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.cc#L71)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI "m" and "v" don't have any obvious meaning here; can you give these more informative names?
</blockquote></details>

Done.

---

*[drake/manipulation/util/frame_pose_tracker.cc, line 102 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkv5S6HrAm2a0nOJO6:-Kwld_wa5DTTMHtr8xYa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.cc#L102)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI --
(1) The indentation here is surprising; check if you editor or formatter likes it.
(2) The names "kres", "fvel", and "svel" here are unnecessarily abbreviated.  It would be more readable if you expanded them out as you have most of the other variable names in this file.
</blockquote></details>

Done.

---

*[drake/manipulation/util/frame_pose_tracker.h, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkwUiT9Qmbe6nRf6IR:-KwldcKVm9VR2nkrv-Pf:b-apgu1r) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.h#L50)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Since your intention is to transfer ownership, it might be clearer to pass `frames` by rvalue reference than by pointer (ie, `std::vector<...>&& frames`, requiring the caller to `std::move` away the vector they are giving up and relieving you of having to clear it to prevent misuse).

Your version is reasonable, so do whichever seems clearer to you.
</blockquote></details>

Interesting. Didn't know about rvalue references. I looked into it and I think the existing version is a little clearer for me. But thanks for the suggestion. I learned something!

---

*[drake/manipulation/util/frame_pose_tracker.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkq3RsnPZtWbQQS9bS:-KwlnR08MaefVO-kn7H7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/frame_pose_tracker.h#L52)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI:
(1) typo "it's" should be "its".
(2) `std::runtime_error` is also thrown in frames is null or empty.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkxtkz5f0aO7uBdyU2:-KwloWEmp4Kdkg7YA4kr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L57)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI a range-based for loop might be clearer here.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 122 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkyQDg9qFec3khokKD:-KwlobcLrxlZsl4cSwEa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L122)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI complete sentence in comment requires capitalization and punctuation.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 132 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkyUseEwRpBjN41gHr:-Kwltl4IbmnmAhk6bhCS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L132)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI complete sentence in comment requires capitalization and punctuation.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 133 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkyVR_pwDsyUwTuTVB:-KwlonoxO9bSLofPWOoE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L133)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI complete sentence in comment requires capitalization and punctuation.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-Kwkya1_LwMro46Z7t7O:-KwlqC5lbGuhN7XYwntr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L145)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI a range-based for loop might be clearer here.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 167 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkycnuU4YAlxiTGIfI:-KwlqGUzEfV6p7mKrefm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L167)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI complete sentence in comment requires capitalization and punctuation.
</blockquote></details>

Done.

---

*[drake/manipulation/util/test/frame_pose_tracker_test.cc, line 168 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-KwkydD4m5zyCKjieYsp:-KwlqHd3vf9-7Vf2AvzA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfc8be81cfa73672fb4b0786d2d388338db648ec/drake/manipulation/util/test/frame_pose_tracker_test.cc#L168)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI complete sentence in comment requires capitalization and punctuation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291)*

**Comment by rcory** [comment]
+(status: curate commits before merging) 

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-:-KwlubP6x2HrloFDNs83:b-s794vx)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291)*

**Comment by rcory** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7291#-:-KwpPtl30JDI31aTLpmP:b-l70wzf)*

**Pull request merged**
