### PR TITLE
Moving qp_inverse_dynamics from examples to systems/controllers/

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Lots of git move and namespace changes. 

The only significant big change is that I split HumanoidStatus into a base class that only has the kinematics related data (RobotKinematicState). 

first step to #6712

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6712)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
Reviewed 70 of 89 files at r1, 21 of 21 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by siyuanfeng-tri** [comment]
+@hongkai-dai for feature review. thanks much! (hopefully won't take too long, mostly just pattern matching checks)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-:-KqO84gVSSMFU0ZFdwLr:b-s9084j)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Reviewed 62 of 89 files at r1, 21 of 21 files at r2, 3 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h, line 88 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqPnp29pI63Aj4B0C3n:-KqPnp29pI63Aj4B0C3o:b-5qck7f) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h#L88)):*
> ```objc
>           double> {
>  protected:
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(HumanoidStatus)
> ```

Also overrides the base class destructor?
```C++
~HumanoidStatus() override {};
```

---

*[drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h, line 114 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqPoNRkOh5EushMpZku:-KqPoNRkOh5EushMpZkv:bfmsnbn) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h#L114)):*
> ```objc
>   // Inertial matrix
>   MatrixX<T> M_;
>   // Bias term: M * vd + h = tau + J^T * lambda
> ```

Also explain that the `bias_term_` is `h` in the documentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-:-KqPqCi2emUsE5uaevbJ:b-t6qajt)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

Partial pass completed.  Taking a break for a bit but should get to the rest of this today.

---

Reviewed 38 of 89 files at r1, 6 of 21 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/test/rigid_body_tree_alias_groups_test.cc, line 10 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTGbdtihN-rnPU2s2Z:-KqTGbdussmWCdZD-efU:b-6qzht2) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/multibody/test/rigid_body_tree_alias_groups_test.cc#L10)):*
> ```cpp
> namespace drake {
> namespace examples {
> namespace qp_inverse_dynamics {
> ```

Do we still want these namespaces here?

---

*[drake/multibody/test/rigid_body_tree_alias_groups_test.cc, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTGxQnlCDKGhhn9Q5t:-KqTGxQnlCDKGhhn9Q5u:bhqb6tq) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/multibody/test/rigid_body_tree_alias_groups_test.cc#L13)):*
> ```cpp
> namespace param_parsers {
> 
> // body_group {
> ```

It seems brittle to duplicate the body of the test file here (as evidenced by the fact that it got out of sync once).  Consider deleting it?

---

*[drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc, line 73 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTLagSTsLv70u8OveK:-KqTLagSTsLv70u8OveL:b-5ieelp) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc#L73)):*
> ```cpp
> 
> void QpInverseDynamics::ResizeQP(const RigidBodyTree<double>& robot,
>                             const QpInput& input) {
> ```

Odd indentation

---

*[drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc, line 335 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTLcfod_iaC9qe-jK1:-KqTLcfod_iaC9qe-jK2:b-5ieelp) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc#L335)):*
> ```cpp
> 
> int QpInverseDynamics::Control(const RobotKinematicState<double>& rs,
>                           const QpInput& input, QpOutput* output) {
> ```

Odd indentation

---

*[drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h, line 17 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTHcmGnDLjH9_z2Okd:-KqTHcmGnDLjH9_z2Oke:b-cwqnkd) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h#L17)):*
> ```objc
>  * A wrapper class around KinematicsCache and several useful matrices such as
>  * the inertia matrix, etc. This class serves mainly as a explicit cache to
>  * avoid repeated computation. This class can be replaced with System's cache
> ```

"with System's cache is ready" sounds kinda awkward

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-:-KqT3IMI6JmMXbSlgHy2:b-rwiyrj)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 89 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h, line 88 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqPnp29pI63Aj4B0C3n:-KqT2GBpn6PDLpEfjAT3:boadq1q) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also overrides the base class destructor?
```C++
~HumanoidStatus() override {};
```
</blockquote></details>

should i?

---

*[drake/multibody/test/rigid_body_tree_alias_groups_test.cc, line 10 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTGbdtihN-rnPU2s2Z:-KqTYGnl1SbsXGUglwS4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/multibody/test/rigid_body_tree_alias_groups_test.cc#L10)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Do we still want these namespaces here?
</blockquote></details>

Done.

---

*[drake/multibody/test/rigid_body_tree_alias_groups_test.cc, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTGxQnlCDKGhhn9Q5t:-KqTYMS3b7r9cvxq4qRJ:bmln0e7) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/multibody/test/rigid_body_tree_alias_groups_test.cc#L13)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems brittle to duplicate the body of the test file here (as evidenced by the fact that it got out of sync once).  Consider deleting it?
</blockquote></details>

you are right, the file location should be obvious enough. 

---

*[drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc, line 73 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTLagSTsLv70u8OveK:-KqTYdziiioV9jTg117R:b4lw1i8) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc#L73)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Odd indentation
</blockquote></details>

run clang format

---

*[drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc, line 335 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTLcfod_iaC9qe-jK1:-KqTYfKllyC8-Naxp6jZ:b4lw1i8) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc#L335)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Odd indentation
</blockquote></details>

run clang format

---

*[drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h, line 114 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqPoNRkOh5EushMpZku:-KqT2uTwdENQDik-t6Ul:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h#L114)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also explain that the `bias_term_` is `h` in the documentation?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by hongkai-dai** [comment]
Review status: 62 of 65 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h, line 88 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqPnp29pI63Aj4B0C3n:-KqTZ8viey4k8ltYAGQ5:be96iwc) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h#L88)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

should i?
</blockquote></details>

Never mind, please ignore my comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by sammy-tri** [comment]
Reviewed 21 of 89 files at r1, 12 of 21 files at r2, 3 of 3 files at r3, 2 of 3 files at r4, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/qp_inverse_dynamics/test/iiwa_inverse_dynamics_test.cc, line 31 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTjN7YO_e484mgpUFl:-KqTjN7YO_e484mgpUFm:b-i773uz) ([raw file](https://github.com/robotlocomotion/drake/blob/6df55a3a693a6e20e8509d4a0392fb409f219217/drake/systems/controllers/qp_inverse_dynamics/test/iiwa_inverse_dynamics_test.cc#L31)):*
> ```cpp
>       "iiwa.alias_groups");
>   std::string controller_config = FindResourceOrThrow(
>       "drake/systems/controllers/qp_inverse_dynamics/test/"
> ```

Are the alias group and controller config files duplicated in the tree now?  I don't see a diff for the deletion of the versions in the prior location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 5 of 89 files at r1, 3 of 21 files at r2, 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-:-KqTmRJQ-AQzgXlYdT-z:bvb1a6z)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 89 files at r1, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h, line 88 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqPnp29pI63Aj4B0C3n:-KqTs15vqas2C3ioKjkq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status.h#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Never mind, please ignore my comment.
</blockquote></details>

Done.

---

*[drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h, line 17 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTHcmGnDLjH9_z2Okd:-KqTrh6kTjwLmAmvCQv8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/db95965db24236e3dcf0332b7d57d944f307d092/drake/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"with System's cache is ready" sounds kinda awkward
</blockquote></details>

Done.

---

*[drake/systems/controllers/qp_inverse_dynamics/test/iiwa_inverse_dynamics_test.cc, line 31 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqTjN7YO_e484mgpUFl:-KqTrpeQr4xfoDOmQOhs:b-5uu2at) ([raw file](https://github.com/robotlocomotion/drake/blob/6df55a3a693a6e20e8509d4a0392fb409f219217/drake/systems/controllers/qp_inverse_dynamics/test/iiwa_inverse_dynamics_test.cc#L31)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Are the alias group and controller config files duplicated in the tree now?  I don't see a diff for the deletion of the versions in the prior location.
</blockquote></details>

yes. I think it's better to keep the test configs in the test folder. These configs will change drastically depending on what we want to do. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/qp_inverse_dynamics/BUILD, line 4 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqU5b1_uuuUvhCET14g:-KqU5b1bJ2qXEVRkKQ3b:b-t2tz7o) ([raw file](https://github.com/robotlocomotion/drake/blob/6df55a3a693a6e20e8509d4a0392fb409f219217/drake/systems/controllers/qp_inverse_dynamics/BUILD#L4)):*
> ```Python
> # This file contains rules for Bazel; see drake/doc/bazel.rst.
> 
> load("//tools:cpplint.bzl", "cpplint")
> ```

BTW This should probably be using `lint.bzl` (see #6724 )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-:-KqU5GqdQxez-dTEe4L8:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Review status: 59 of 65 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/qp_inverse_dynamics/BUILD, line 4 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqU5b1_uuuUvhCET14g:-KqUZhKEKjca0-ZUf89b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6df55a3a693a6e20e8509d4a0392fb409f219217/drake/systems/controllers/qp_inverse_dynamics/BUILD#L4)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW This should probably be using `lint.bzl` (see #6724 )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by sammy-tri** [comment]
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/controllers/qp_inverse_dynamics/BUILD, line 4 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqU5b1_uuuUvhCET14g:-KqV-fFj43daG84GTiF0:bgh7arq) ([raw file](https://github.com/robotlocomotion/drake/blob/6df55a3a693a6e20e8509d4a0392fb409f219217/drake/systems/controllers/qp_inverse_dynamics/BUILD#L4)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like `add_lint_tests()` isn't ever called?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by siyuanfeng-tri** [comment]
Review status: 61 of 66 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/qp_inverse_dynamics/BUILD, line 4 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6712#-KqU5b1_uuuUvhCET14g:-KqVd74Nbg06Oqxc8McX:btptmy9) ([raw file](https://github.com/robotlocomotion/drake/blob/6df55a3a693a6e20e8509d4a0392fb409f219217/drake/systems/controllers/qp_inverse_dynamics/BUILD#L4)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It looks like `add_lint_tests()` isn't ever called?
</blockquote></details>

fixed.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 6 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6712)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
