### PR TITLE
Port simple_car_demo to Simulator 2.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3408)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by liangfok** [comment]
+@liangfok since knowing this PR will be useful when I port Drake/ROS car demos to System 2.0.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/simple_car_demo.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHE55XILdH-Sez2Yzg:-KRHE55_CpWz9uHgoT22:b-sl8e2w) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L96)):*
> ```cpp
> };
> 
> int do_main(int argc, const char* argv[]) {
> ```

Per style guide, shouldn't this be `DoMain()`?

---

*[drake/examples/Cars/simple_car_demo.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHGBf9SQN34TFDiTr6:-KRHGBfARoiAl_KeW9jU:b69lgks) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L96)):*
> ```cpp
> };
> 
> int do_main(int argc, const char* argv[]) {
> ```

BTW, the code in this method does not appear to be covered under a unit test. Is this intentional?

---

*[drake/examples/Cars/simple_car_demo.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHF3pFewYtP4TI62oZ:-KRHF3pFewYtP4TI62o_:b9bslv3) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L97)):*
> ```cpp
> 
> int do_main(int argc, const char* argv[]) {
>   auto lcm = std::make_unique<lcm::LCM>();
> ```

BTW, why not allocate this on the stack?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-:-KRTvmGlWVr0ACqK7UW5:b-rfkj9d)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/simple_car_demo.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHE55XILdH-Sez2Yzg:-KRU1eMxRIdOoOJFH9cE:b-kv12e) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L96)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Per style guide, shouldn't this be `DoMain()`?
</details>
I think that https://google.github.io/styleguide/cppguide.html#Exceptions_to_Naming_Rules applies.  The clarity of "this is like main, but in a namespace" is perhaps a win?

---

*[drake/examples/Cars/simple_car_demo.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHGBf9SQN34TFDiTr6:-KRU1tQT9VyGSU9GjOU3:b-9kvvms) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L96)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, the code in this method does not appear to be covered under a unit test. Is this intentional?
</details>
I have some plans to bring this code under test, but it involves even more rewriting.  (We don't want to test `main`, we want to test APIs that can create and run automotive simulations, for which `main` is a trivial wrapper.)  My hope was to port from System 1.0 -> System 2.0 first for all examples with whatever testing we already had, and then start in on refactoring and brining it under test.  I am open to discussion if there's thing that seem more urgent to get coverage on up-front here.

---

*[drake/examples/Cars/simple_car_demo.cc, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHF3pFewYtP4TI62oZ:-KRU2SMmKlZAxSyU3LCd:b2iej49) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L97)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, why not allocate this on the stack?
</details>
(1) I think having everything as `auto / unique_ptr` makes it a bit more consistent and less syntaxy as the APIs and/or lifecycle requirements for this program evolve, and (2) valgrind has more visibility into heap-allocated classes than it does stack-allocated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by liangfok** [comment]
Just a few more comments.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/simple_car_demo.cc, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU3Zq2M-xCUkm5cu5Z:-KRU3Zq2M-xCUkm5cu5_:bsswbva) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L15)):*
> ```cpp
> #include "drake/systems/lcm/lcm_publisher_system.h"
> #include "drake/systems/lcm/lcm_subscriber_system.h"
> #include "lcmtypes/drake/lcmt_viewer_load_robot.hpp"
> ```

Should `lcmtypes/` be considered a Drake dependency meaning it should be located before the `drake/` includes?

---

*[drake/examples/Cars/simple_car_demo.cc, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU3kJsi-PurEwHG6XE:-KRU3kJsi-PurEwHG6XF:ba9692z) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L22)):*
> ```cpp
> namespace {
> 
> /// Publish hand-crafted BotVisualizer LCM messages so we can see this demo.
> ```

This class is not part of the public API and thus should not be a Doxygen code block. (Use `//` instead of `///`.)

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRU4i-AxclrMlt3J95I:bw3y5dr) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
> ```cpp
>   void DoPublish(const systems::Context<double>& context) const override {
>     if (needs_load_robot_) {
>       PublishLoadRobot();
> ```

Why not call this in the constructor?

@david-german-tri, assuming this cannot be done in the constructor, we may need an `init()` method in `System` for this type of application.

---

*[drake/examples/Cars/simple_car_demo.cc, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHE55XILdH-Sez2Yzg:-KRU31k8mqLK6toADkiE:b5pbxgp) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I think that https://google.github.io/styleguide/cppguide.html#Exceptions_to_Naming_Rules applies.  The clarity of "this is like main, but in a namespace" is perhaps a win?
</details>
I see. OK.

---

*[drake/examples/Cars/simple_car_demo.cc, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHGBf9SQN34TFDiTr6:-KRU3B8fY9dylufP_mxx:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I have some plans to bring this code under test, but it involves even more rewriting.  (We don't want to test `main`, we want to test APIs that can create and run automotive simulations, for which `main` is a trivial wrapper.)  My hope was to port from System 1.0 -> System 2.0 first for all examples with whatever testing we already had, and then start in on refactoring and brining it under test.  I am open to discussion if there's thing that seem more urgent to get coverage on up-front here.
</details>
OK.

---

*[drake/examples/Cars/simple_car_demo.cc, line 97 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRHF3pFewYtP4TI62oZ:-KRU3FFy-Xq6NtB5wxxm:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L97)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> (1) I think having everything as `auto / unique_ptr` makes it a bit more consistent and less syntaxy as the APIs and/or lifecycle requirements for this program evolve, and (2) valgrind has more visibility into heap-allocated classes than it does stack-allocated.
</details>
OK.

---

*[drake/examples/Cars/simple_car_to_euler_floating_joint.h, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU6KPyuY6ZIf8R1Kvo:-KRU6KPz2euLU_EpFkZ9:bfvp9ii) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_to_euler_floating_joint.h#L10)):*
> ```objc
> namespace cars {
> 
> /// Convert SimpleCarState to a full 6-DOF EulerFloatingJointState.
> ```

"Convert" should be "Converts".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-:-KRU71037MuR_VN-uZWE:b-h3i9vf)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/simple_car_demo.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU3Zq2M-xCUkm5cu5Z:-KRU7QOZrodtZv2McYg1:b-wo80xj) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should `lcmtypes/` be considered a Drake dependency meaning it should be located before the `drake/` includes?
</details>
TTBOMK that file is emitted by Drake as part of its build process, so should probably be phrased like this.  However, the whole thing is covered in bees; see #3351.  I would prefer to leave the spellings alone until the swarm has left.

---

*[drake/examples/Cars/simple_car_demo.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU3kJsi-PurEwHG6XE:-KRU7isVJ_-SLWNTHLUI:b1gla11) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This class is not part of the public API and thus should not be a Doxygen code block. (Use `//` instead of `///`.)
</details>
Done.

(I always forget this rule!  My subconscious still thinks `///` means "API comment" and `//` means "implementation comment".  I am still kind of sad I gave up on that debate.)

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRU8GN7OS1qCJbWdtTy:bwa9dnk) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*

> Why not call this in the constructor?

It just seemed weird to send messages during construction, rather than simulation.

> ... we may need an init() method in System for this type of application.

I think sending two messages during Publish, instead of just the one, is totally reasonable and doesn't require new APIs.  In the extreme, we'd declare this as an explicit event at `t=0`, but I don't think that's worth it here.

---

*[drake/examples/Cars/simple_car_to_euler_floating_joint.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU6KPyuY6ZIf8R1Kvo:-KRU8jg0-5nehwcW5rAd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_to_euler_floating_joint.h#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "Convert" should be "Converts".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUFlcB8WXLty1kq2Ab:b-yfy2al) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> 
> > Why not call this in the constructor?
> 
> It just seemed weird to send messages during construction, rather than simulation.
> 
> > ... we may need an init() method in System for this type of application.
> 
> I think sending two messages during Publish, instead of just the one, is totally reasonable and doesn't require new APIs.  In the extreme, we'd declare this as an explicit event at `t=0`, but I don't think that's worth it here.
</details>
OK. We'll hold off on an explicit `init()` phase for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-:-KRUGI0td01Igpd0AAkC:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-:-KRUGTegrizBgRbvFZWX:bppyoqq)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRU7xGzOMsUiyP-OuJ_:b-x44rvh) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK. We'll hold off on an explicit `init()` phase for now.
</details>
I share @liangfok's discomfort at the hidden mutable bit for a one-time state transition.  I'm willing to tolerate it because it's only used in `DoPublish`, and we don't have a better approach in the framework, but I think we should all feel a little bad about it.  Please flag this with a comment as a particularly hacky thing that should not be emulated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUKRgxZUHWJO2EBaLp:b1tjx0y) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I share @liangfok's discomfort at the hidden mutable bit for a one-time state transition.  I'm willing to tolerate it because it's only used in `DoPublish`, and we don't have a better approach in the framework, but I think we should all feel a little bad about it.  Please flag this with a comment as a particularly hacky thing that should not be emulated.
</details>
Sure, I will add a caveat the code to warn about not cargo-culting it into other domains.

But anything that touches LCM-on-the-wire is not a deterministic simulation.  Message publication to the wire is a side-effect we can't get around.  It won't be idempotent or reversible or amenable to verification or anything, whether its LoadRobot or even just the Draw here.  I fully agree that in a simulation block this would be an anti-pattern, but for visualization-on-the-wire I'm not sure why we care.  The meme we want in this case is "Send LoadRobot every time its contents would be different", which I guess I could capture explicitly as non-continuous-time system state, but in what case would that be worth it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUOw21VKUPlNglHYgM:b-m4tgu9) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Sure, I will add a caveat the code to warn about not cargo-culting it into other domains.
> 
> But anything that touches LCM-on-the-wire is not a deterministic simulation.  Message publication to the wire is a side-effect we can't get around.  It won't be idempotent or reversible or amenable to verification or anything, whether its LoadRobot or even just the Draw here.  I fully agree that in a simulation block this would be an anti-pattern, but for visualization-on-the-wire I'm not sure why we care.  The meme we want in this case is "Send LoadRobot every time its contents would be different", which I guess I could capture explicitly as non-continuous-time system state, but in what case would that be worth it?
</details>
Until Drake has a parameter server, I believe the meme should be "periodically send the `LoadRobot` message just in case the previous message failed to be delivered."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUOX3naBFjYaibj1sJ:b1frdkm) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Until Drake has a parameter server, I believe the meme should be "periodically send the `LoadRobot` message just in case the previous message failed to be delivered."
</details>
I think we agree.  I just don't want any reader to get the idea that typing `mutable` to get around the `const` restriction on `System<T>` methods is a pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUPQQNm38zI_p4eods:ba89cn2) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I think we agree.  I just don't want any reader to get the idea that typing `mutable` to get around the `const` restriction on `System<T>` methods is a pattern.
</details>
LoadRobot has semantics that are really not compatible with periodic re-send (been there, done that, got the bloodbath). It deletes all of drake-visualizer's prior state and rebuilds it from scratch. This  operation is quite expensive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUQ1pE9i4CU7zfi6lj:b4ecfjo) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> LoadRobot has semantics that are really not compatible with periodic re-send (been there, done that, got the bloodbath). It deletes all of drake-visualizer's prior state and rebuilds it from scratch. This  operation is quite expensive.
</details>
@rpoyner-tri: Wow.  https://github.com/RobotLocomotion/drake/issues/3421

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRURoXIH8-RFRVTIHaI:bfs2bwm) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> @rpoyner-tri: Wow.  https://github.com/RobotLocomotion/drake/issues/3421
</details>
BTW, we do need a `System::Initialize()` method or equivalent that is invoked by the Simulator once at simulation start. I'll add one soon.

Also, could context.get_time()==0 be used here in place of the ill-advised hidden state variable `needs_load_robot_`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUUv8dX4StpS9aeJhg:b2w5whx) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, we do need a `System::Initialize()` method or equivalent that is invoked by the Simulator once at simulation start. I'll add one soon.
> 
> Also, could context.get_time()==0 be used here in place of the ill-advised hidden state variable `needs_load_robot_`?
</details>
Done (now uses get_time, and has a suitable warning on the mutable).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUVJuzj6De0OTXe6Eb:bd1mfg7) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Done (now uses get_time, and has a suitable warning on the mutable).
</details>
BTW do we have a contract guaranteeing that `context.get_time()` _will_ return zero the very first time `DoPublish()` is called?

It's not documented here:

http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html#a4389a6d724f9e463244d2b8a30e6ebe0

Or here:

http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_context.html#a82203eb50c0d1a0b3177955e01d0e336

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUWHwvqSRzQaavTBnK:b-goldlz) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW do we have a contract guaranteeing that `context.get_time()` _will_ return zero the very first time `DoPublish()` is called?
> 
> It's not documented here:
> 
> http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html#a4389a6d724f9e463244d2b8a30e6ebe0
> 
> Or here:
> 
> http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_context.html#a82203eb50c0d1a0b3177955e01d0e336
> 
</details>
I believe it's covered by _"By default Publish() will be called at the start of each continuous integration step..."_ since I've set up my simulation to start at t=0.0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRUXbDpDFYytE3eeTvX:bgv9331) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
OK. I found the following sentence, which I think covers it:

> Publish() will always be called at the start of the first step of a simulation (after initialization) ...

The previous sentence contained the phrase "By default", which weakened the contract.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRU_NGoQjQL54g1u_1J:b-vaizox) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK. I found the following sentence, which I think covers it:
> 
> > Publish() will always be called at the start of the first step of a simulation (after initialization) ...
> 
> The previous sentence contained the phrase "By default", which weakened the contract.
</details>
Right.  I was happy enough to ride with it for now (and fail-fast if it didn't).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please
The windows executor failed.

**Comment by jwnimmer-tri** [comment]
The only jenkins error was the CDash upload.

**Comment by sherm1** [comment]
:lgtm: and a BTW.

---

Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRWoriDcR9389HsSVH2:b-e71oov) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Right.  I was happy enough to ride with it for now (and fail-fast if it didn't).
</details>
BTW, there actually won't be a guarantee about Publish() time=0 because there will shortly be a sample rate for Publish(), and that isn't required to start at 0. However,   it is guaranteed at the moment and the change will be accompanied by a guaranteed-to-succeed initialization call (there will be an integer step count and an Initialize() method). A TODO here would be good noting that this will need a change later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-:-KRWqTmn-iHh7xJWPion:b-glbj0g)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/simple_car_demo.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3408#-KRU4i-92Vn8ZuBlBGwr:-KRYFudpS1mph2AiiJZA:b-j2af85) ([raw file](https://github.com/robotlocomotion/drake/blob/cac5c606d3b7a7ad6b8d7a94f42ea6c4da50ae23/drake/examples/Cars/simple_car_demo.cc#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, there actually won't be a guarantee about Publish() time=0 because there will shortly be a sample rate for Publish(), and that isn't required to start at 0. However,   it is guaranteed at the moment and the change will be accompanied by a guaranteed-to-succeed initialization call (there will be an integer step count and an Initialize() method). A TODO here would be good noting that this will need a change later.
</details>
Need @david-german-tri's ack here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3408)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to windows CDash flake.

**Pull request merged**
