### PR TITLE
Hybrid merge

### PR DESCRIPTION
**Pull request by RoboEngineer**
Try to study it.
Not going to modify anything here.

### CODE REVIEW

**Comment by mposa** [comment]
This looks like a pull request from one of my branches--but I don't think this should all be brought back into master. Is there a reason for the pull request?

**Comment by RoboEngineer** [comment]
Sorry. I would like to download and study those codes. But not sure that I
did the right thing....




On Tue, Mar 8, 2016 at 4:47 PM, Michael Posa <notifications@github.com>
wrote:

> This looks like a pull request from one of my branches--but I don't think
> this should all be brought back into master. Is there a reason for the pull
> request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RobotLocomotion/drake/pull/1832#issuecomment-193981766>
> .
>



-- 
Ye Ding

**Comment by mposa** [comment]
Ah, ok. You need to add my github fork https://github.com/mposa/drake as a remote, fetch from the remote, and then checkout the appropriate branch.

**Comment by RoboEngineer** [comment]
I see. Thanks a lot Michael.

On Tue, Mar 8, 2016 at 5:11 PM, Michael Posa <notifications@github.com>
wrote:

> Ah, ok. You need to add my github fork https://github.com/mposa/drake as
> a remote, fetch from the remote, and then checkout the appropriate branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RobotLocomotion/drake/pull/1832#issuecomment-193988866>
> .
>



-- 
Ye Ding

**Comment by mposa** [comment]
Closing the pull request now. Feel free to follow up via email.

**Pull request closed without merging**
