### PR TITLE
[doc] Remove Doxygen tabs header and "generated by" footer

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The tabs ("Main Page", "Related Pages", ...) are redundant with the tree view that's already on the left side.
The use of tabs also prevents the easy customization of the search box.

The footer ("Generated by DOXYGEN" in the lower right) is just extra churn with no real value.

Towards #7559.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16480)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Before:

image

After:

image

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16480#-:-Muoy03U8DPGg6rrd3Aa:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by amcastro-tri — COMMENTED** [review]
I personally like it better, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16480#-:-Muq31yr2m2q4UI-ZtPR:b-cvursj)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16480)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/Doxyfile_CXX.in, line 206 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16480#-MuqJuaRDRRm9AxCZs2Z:-MuqP6WL4dKIGVXojm7N:bx8zly3) ([raw file](https://github.com/robotlocomotion/drake/blob/b593f9d6f603936e5b720b4f058ba6bdf043f0d1/doc/doxygen_cxx/Doxyfile_CXX.in#L206)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW obscure that "DISABLE_INDEX" would get rid of the (non-index) tabs. I checked and it actually _doesn't_ get rid of the Class Index! 
Please consider adding a comment here so that no innocent party will undo this thinking they are going to get an index.
</blockquote></details>

In my view, there are are no innocents in the land of Doxygen config files.  But I added the comment anyway.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Pull request merged**
