### PR TITLE
Switch to upstream bullet

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6409)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/bullet.BUILD, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6409#-KnFZxT592FPIIsJRYg4:-KnFZxT6EMRcHVxwlStG:b-csqh5p) ([raw file](https://github.com/robotlocomotion/drake/blob/36217bf7cbadf6e195f873c519e5abcd03ca0cdc/tools/bullet.BUILD#L52)):*
> ```
> )
> 
> install_cmake_config(package = "Bullet")  # Creates rule :install_cmake_config.
> ```

BTW, not sure we want to remove this comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6409#-:-KnF_7tcocg17-b3ALsN:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6409#-:-KnF__c8j8uT3h0t-zuE:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6409#-:-KnFa_iizOP8riiL-oco:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/systems/trajectories/CMakeLists.txt, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6409#-KnFn9vwKxtMUlh7Ijo2:-KnFn9vwKxtMUlh7Ijo3:bnftvil) ([raw file](https://github.com/robotlocomotion/drake/blob/2e8d7215b339b76fdc2530f2f625131975a5f54b/drake/matlab/systems/trajectories/CMakeLists.txt#L9)):*
> ```CMake
> 
> if(Bullet_FOUND AND Matlab_FOUND)
>   # TODO(jamiesnape): Create imported target for Bullet.
> ```

FYI I'll probably PR this entire directory's deletion within about 1 week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6409)*

**Comment by jamiesnape** [comment]
Put this on hold until the MATLAB disappears.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab  please

**Pull request merged**
