### PR TITLE
Nuke macOS instructions for setting up CLion that break the build

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11329)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature and platform review.

**Comment by jwnimmer-tri** [comment]
Is the bottom line that `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` used to result in a working build, but on more recent versions of bazel (due to cc_toolchain changes?), not a single thing works anymore on macOS when that variable is set?

**Comment by jamiesnape** [comment]
The toolchain is broken for any C files, which is probably unsurprising given the variable's name.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review.

**Pull request merged**
