### PR TITLE
Change ManipulationStation clutter clearing objects to YCB objects

### PR DESCRIPTION
**Pull request by kmuhlrad**
Rebased and revised version of: https://github.com/RobotLocomotion/drake/pull/10703

Adds a new SetupClutterClearingStation method to specify the list of objects, their poses, and the pose of a camera. The default objects are the YCB objects used by DOPE.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10748)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Hup, looks like you have a few more deprecation errors to fix :(

https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-bionic-gcc-bazel-experimental-python3-release-677&field2=buildstarttime&compare2=84&value2=now
```
DRAKE DEPRECATED: DRAKE_ABORT() and DRAKE_ABORT_MSG() are deprecated; use 'throw' instead; this macro will be removed on 2019-06-01. [-Werror=deprecated-declarations]
   ::drake::detail::DeprecatedAbort(msg, __func__, __FILE__, __LINE__)
                    ^
examples/manipulation_station/proof_of_life.cc:53:5: note: in expansion of macro 'DRAKE_ABORT_MSG'
     DRAKE_ABORT_MSG(
```

**Comment by EricCousineau-TRI** [comment]
Just one more error... :(
https://drake-cdash.csail.mit.edu/testDetails.php?test=26492451&build=1128179
```
examples/manipulation_station/end_effector_teleop_sliders.py:34:1: E302 expected 2 blank lines, found 1
```

**Comment by EricCousineau-TRI** [comment]
Ah, we need LGTMs.

Y'all ready to dish those out? I'd be happy to serve as platform.

**Comment by SeanCurtis-TRI** [comment]
___
*[examples/manipulation_station/manipulation_station.cc, line 220 at r10](https://reviewable.io/reviews/robotlocomotion/drake/10748#-MLxaYZeAA8HhuH3T-p2:-MLxaYZeAA8HhuH3T-p3:bdbuezh) ([raw file](https://github.com/robotlocomotion/drake/blob/8fe278e658ad3e765ef881bce1e21ee5261d5586/examples/manipulation_station/manipulation_station.cc#L220)):*
> ```cpp
>     // moment.
>     // RGB:
>     // - w: 848, h: 480, fx: 616.285, fy: 615.778, ppx: 405.418, ppy: 232.864
> ```

@kmuhlrad @ericcousineau-tri When this was done (two years ago now), did we also have ready access to the pose of the sensor centers relative to the body? (E.g., X_BC and X_BD)? I'm currently refactoring this to support the full intrinsics and I thought it would be nice to also include those poses.

**Comment by EricCousineau-TRI** [comment]
We don't have a good sense of the frame `X_BC`, and by relation, `X_BD`.

But I can give ya `X_CD` that's queried from the camera (which we tend to trust); here's (xyz, rpy_deg) for 3 diff. cameras:
```
(xyz=[ 0.01489362, -0.00018772, -0.00010425], rpy_deg=[-0.19008628, -0.0157807 , -0.03049699])
(xyz=[1.48671474e-02,  -5.19740315e-05,  -1.71622014e-06], rpy_deg=[ 0.10439932,  0.15632116, -0.05957033])
(xyz=[  1.51533075e-02,  -5.47632699e-05,  -3.46990710e-04]), rpy_deg=[-0.10824212,  0.36450694,  0.02524215])
```

Then we usually just assume `X_BC` is identity, and add the necessary padding for collision filtering.

**Comment by SeanCurtis-TRI** [comment]
I need a *bit* more hand holding. 

1. Presumably, the values included in the code for the intrinsic matrix also has some variability from camera to camera (but some "representative" set of values were selected and hard-coded). Do you want me to arbitrarily select one of the three samples you've given? Average it? Any preference at all?
2. To be perfectly clear, you'd define `X_BC = I` and `X_BD = X_CD`? (as opposed to, say, splitting the difference around a common "center"?)

>  add the necessary padding for collision filtering.

What does this mean?

**Comment by EricCousineau-TRI** [comment]
> 1. [...] Do you want me to arbitrarily select one of the three samples you've given? Average it? Any preference at all?

I dunno TBH. My suggestion is average, and then just take 2 sig. figures?

> 2. To be perfectly clear, you'd define `X_BC = I` and `X_BD = X_CD`? (as opposed to, say, splitting the difference around a common "center"?)

Nope! I'd recommend still giving an offset for`X_BC` / `X_BD`. I don't think this has any secret sauce, so cowboy-sharing mode:
Here's our d415 model from Anzu.
https://gist.github.com/EricCousineau-TRI/8776775291ac824ddb0310c5bc1c56e0

Note in particular the frame `"rgb"` and its pose defining `X_BC`.

> >  add the necessary padding for collision filtering.
>
> What does this mean?

Ah, nuts. Sorry, I shouldn't have added the word "filtering", my bad!
In the SDFormat file, we "pad" the collision use a collision box (30cm x 10cm x 10cm) that is quite large and conservative.

**Comment by EricCousineau-TRI** [comment]
There's also the official RealSense2 model:
https://github.com/IntelRealSense/realsense-ros/blob/bc57ca591e3a9e9684ff7e6e4f50d693eb1d5ff7/realsense2_description/urdf/_d415.urdf.xacro

The dimensions are buried in Xacro, and I can't easily posit the origin / coordinate frames, but this'll probably have better measurements somewhere?

**Comment by SeanCurtis-TRI** [comment]
> Nope! I'd recommend still giving an offset for X_BC / X_BD 

Sorry, I wasn't recommending eliminating the parameter `X_BC`, generally. The question is if I were to have a hard-coded D415 (as manipulation station kind of does), would we want the color sensor to be exactly located at the camera origin and the depth offset from it? Or would we want both color and depth offset from the camera origin a symmetric amount? 

I'm simply going to define `X_BC = I` and `X_BD = X_CD` in `ManipulationStation` and people can change it in the future as much as they like.

**Comment by EricCousineau-TRI** [comment]
Yup, sounds good to me!
People are prolly posturing cameras w/ calibration based on the color frame, so using `X_BC = I` will yield "better" results than injecting an offset.

(Unless, @RussTedrake, y'all are posturing the cameras based on CAD measurements, where it could be more related to the physical frame base?)

**Comment by RussTedrake** [comment]
btw -- that's aok to me.  I wasn't the one that set those numbers in the first place, and we're bound to have to set them again if/when we get back into the teaching lab!

**Pull request merged**
