### PR TITLE
Add bindings for math/quaternion.h

### PR DESCRIPTION
**Pull request by RussTedrake**
Includes some fix-ups to support all scalar types.

+@hongkai-dai for feature review, please?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19208)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@SeanCurtis-TRI for platform review please, thanks!

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-:-NTFZ38D4E_dtIIpci4r:btc9pyf)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some cosmetic things.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-:-NTFeVIo5upcQ0ikqjYJ:b8olqzd)* status: 3 unresolved discussions (waiting on @RussTedrake)

___
*[`math/quaternion.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-NTFdSEG6UcEwOai4-VB:-NTFdSEG6UcEwOai4-VC:b-ic9k8x) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f297781dd77c6a851f3751fba56a1a5b0228ab0/math/quaternion.h#L29)):*
> ```objc
> 
> /**
>  * Returns a unit quaternion that represents the same orientation as `q1`,
> ```

nit `q0` and `q1` need to be updated in the documentation as well.
___
*[`math/quaternion.h` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-NTFdhNB93-pp2-2T-ZJ:-NTFdhNB93-pp2-2T-ZK:bzzuji) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f297781dd77c6a851f3751fba56a1a5b0228ab0/math/quaternion.h#L43)):*
> ```objc
> 
> template <typename Derived>
> Vector4<typename Derived::Scalar> quatConjugate(
> ```

BTW `quatConjugate` and `quatProduct` aren't bound and aren't referenced in the list of things to eventually bind. Should the reason be clear?
___
*[`math/quaternion.h` line 323 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-NTFeC0t6BMHhOpv4jNa:-NTFeC0t6BMHhOpv4jNb:b-6ck2m8) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f297781dd77c6a851f3751fba56a1a5b0228ab0/math/quaternion.h#L323)):*
> ```objc
> 
> 
> /** This function tests if a quaternion and a quaternions time-derivative
> ```

BTW As long as you're here, there are a couple of typos.



_Suggestion:_
```objc
and a quaternion's time derivative
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19208)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @RussTedrake)

___
*[`math/quaternion.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-NTFdSEG6UcEwOai4-VB:-NTFqJup-M6iqCF9i-Ry:b-6luv3l) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f297781dd77c6a851f3751fba56a1a5b0228ab0/math/quaternion.h#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit `q0` and `q1` need to be updated in the documentation as well.
</blockquote></details>

Done.  good catch.
___
*[`math/quaternion.h` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-NTFdhNB93-pp2-2T-ZJ:-NTFq3tZ9xFczg7eGZtZ:bs7wumx) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f297781dd77c6a851f3751fba56a1a5b0228ab0/math/quaternion.h#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW `quatConjugate` and `quatProduct` aren't bound and aren't referenced in the list of things to eventually bind. Should the reason be clear?
</blockquote></details>

Done. 
___
*[`math/quaternion.h` line 323 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19208#-NTFeC0t6BMHhOpv4jNa:-NTFqE4a0bKMOMzScrjx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f297781dd77c6a851f3751fba56a1a5b0228ab0/math/quaternion.h#L323)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As long as you're here, there are a couple of typos.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19208)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
