### PR TITLE
Implement Diagram::Publish.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@jwnimmer-tri for both levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3343)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/test/diagram_test.cc, line 392 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQap7Kefu3ytCEMNMTo:-KQap7Kefu3ytCEMNMTp:b-ukf15i) ([raw file](https://github.com/robotlocomotion/drake/blob/67b704a903213234547070432d8f53a40703f191/drake/systems/framework/test/diagram_test.cc#L392)):*
> ```cpp
> 
> // PublishingSystem has an input port for a single int. It publishes that int
> // to a function provided in the constructor.
> ```

The input port is typed as a double, not an int.

---

*[drake/systems/framework/test/diagram_test.cc, line 403 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQaorUKU8djyZvdkwK9:-KQaorUKU8djyZvdkwKA:b-huc8p0) ([raw file](https://github.com/robotlocomotion/drake/blob/67b704a903213234547070432d8f53a40703f191/drake/systems/framework/test/diagram_test.cc#L403)):*
> ```cpp
>                   SystemOutput<double>* output) const override {}
> 
>   void DoPublish(const ContextBase<double>& context) const override {
> ```

BTW Should this be `protected:`, for consistency with the base class?

---

*[drake/systems/framework/test/diagram_test.cc, line 436 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQaqB02L_TkBJZtTJep:-KQaqB03mWhsA6SMyBSq:b-d9tq8x) ([raw file](https://github.com/robotlocomotion/drake/blob/67b704a903213234547070432d8f53a40703f191/drake/systems/framework/test/diagram_test.cc#L436)):*
> ```cpp
> 
> GTEST_TEST(DiagramPublishTest, Publish) {
>   PublishIntDiagram publishing_diagram(42.0);
> ```

Passing `double` literal argument into `int` parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3343)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/test/diagram_test.cc, line 392 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQap7Kefu3ytCEMNMTo:-KQatCTCnAFWK_PlRo1_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67b704a903213234547070432d8f53a40703f191/drake/systems/framework/test/diagram_test.cc#L392)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The input port is typed as a double, not an int.
</details>
Done.

---

*[drake/systems/framework/test/diagram_test.cc, line 403 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQaorUKU8djyZvdkwK9:-KQatEZTV2NVQRgUlnyU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67b704a903213234547070432d8f53a40703f191/drake/systems/framework/test/diagram_test.cc#L403)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Should this be `protected:`, for consistency with the base class?
</details>
Done.

---

*[drake/systems/framework/test/diagram_test.cc, line 436 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQaqB02L_TkBJZtTJep:-KQatSt61i5Urca22BnL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67b704a903213234547070432d8f53a40703f191/drake/systems/framework/test/diagram_test.cc#L436)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Passing `double` literal argument into `int` parameter.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3343)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 426 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQauRszR85NLBET8hmb:-KQauRszR85NLBET8hmc:b-11wcne) ([raw file](https://github.com/robotlocomotion/drake/blob/4c60b85b09c6d08973256f22f8d786dbf951b0ac/drake/systems/framework/test/diagram_test.cc#L426)):*
> ```cpp
>   }
> 
>   double  get() const { return published_value_; }
> ```

BTW I think there's extra whitespace here `double..get`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-:-KQauh4CfqJrfiWZGPnY:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 426 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-KQauRszR85NLBET8hmb:-KQauvFij9uGGVYRYRC_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4c60b85b09c6d08973256f22f8d786dbf951b0ac/drake/systems/framework/test/diagram_test.cc#L426)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I think there's extra whitespace here `double..get`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3343)*

**Comment by jwnimmer-tri** [comment]
:squirrel: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3343#-:-KQavqPu5AwTFaTxZMxt:b-sgzodo)*

**Pull request merged**
