### PR TITLE
Adds simple tutorial on the systems framework

### PR DESCRIPTION
**Pull request by RussTedrake**
ported (and updated) from the underactuated notes appendix.

also adds a few missing python bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12009)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@jamiesnape -- any idea what this error is?
https://drake-cdash.csail.mit.edu/testDetails.php?test=34010592&build=1217993
(perhaps it's just because I pushed this rev with some of the metadata still in the notebook?)

**Comment by jamiesnape** [comment]
Looks like the message you would get if it were choking on a non-ASCII character, but I don't immediately see one in the diff.

**Comment by RussTedrake** [comment]
@hongkai -- i've added some references to multiple inputs, and switched the LQR to a PID controller (which is cleaner and has multiple inputs).  Also renamed to dynamical_systems.ipynb. 

something seems wrong with the PID bindings; i'm still investigating.

**Comment by SeanCurtis-TRI** [comment]
+@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please

(Testing to see if the test timeout was a fluke...)

**Comment by jwnimmer-tri** [comment]
___
*[tutorials/README.md, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12009#-LoVpZ_Q48VVvTDkEBXn:-LoVxW1p50QMMIJlhy9D:b48n4pw) ([raw file](https://github.com/robotlocomotion/drake/blob/447bc4c2c9cc322699ab48873afe6b56bfcab537/tutorials/README.md#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I pulled the branch and attempted to run this notebook. I failed with the error:

```
Running notebook interactively
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
```

Obviously, it's not part of our prereqs (as I've never run jupyter notebooks but have run install_prereqs.sh). Some kind of guidance for the total novice wouldn't go amiss.
</blockquote></details>

An inability to run locally is a blocking defect.

We _do_ have Jupyter in Drake prereqs.  Did you only text on Xenial, per chance?  It only works on Bionic.  Maybe the README should mention that.

**Comment by jwnimmer-tri** [comment]
___
*[tutorials/README.md, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12009#-LoVpZ_Q48VVvTDkEBXn:-LoWOhDb2060_Ll65GMz:b-29rdsz) ([raw file](https://github.com/robotlocomotion/drake/blob/447bc4c2c9cc322699ab48873afe6b56bfcab537/tutorials/README.md#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I feel I represent the user that has never run jupyter notebooks. What do I need to do to actually consume this tutorial?
</blockquote></details>

The prereqs + this command should be all that's necessary.  We can debug on slack, maybe.  Perhaps you have `--config python2` in your dotfiles, or did some `sudo pip install` monster, or etc.

**Comment by jwnimmer-tri** [comment]
___
*[tutorials/README.md, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12009#-LoVpZ_Q48VVvTDkEBXn:-LoXCloA9fCYtKfaGiWV:b-cnr4kt) ([raw file](https://github.com/robotlocomotion/drake/blob/447bc4c2c9cc322699ab48873afe6b56bfcab537/tutorials/README.md#L8)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This seems like a real issue, but it's in the devops... and not related to this PR.  I assume that you have the same problem when you try to run the mathematical program tutorials?
</blockquote></details>

=> `#build` channel on drakedevelopers slack

**Comment by EricCousineau-TRI** [comment]
I'll submit a separate PR to fix #12042; that will require reprovisioning.

**Pull request merged**
