### PR TITLE
 pybind11 docs: Fix sphinx patch for versions > 1.6.7

### LINKED ISSUE #12604: pydrake doc: Class constructors (__init__) have weird ordering?
EDIT(eric): Re-scoping to just `__init__` ordering

---

Related to #11954.

I've noticed that the documentation for the class and the constructor of ManipulationStation is missing:
https://drake.mit.edu/pydrake/pydrake.examples.manipulation_station.html?highlight=manipulationstation#pydrake.examples.manipulation_station.ManipulationStation

By contrast, the Adder system looks good:
https://drake.mit.edu/pydrake/pydrake.systems.primitives.html?highlight=adder#pydrake.systems.primitives.Adder_

Is this inconsistency still expected, given that #11954 is closed?

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards: https://github.com/RobotLocomotion/drake/issues/12604

PR #12787 was reverted (#12910), due to failures on Mac.
This PR fixes them.

The Mac failures can be reproduced on Linux by:
- `apt-get remove python3-sphinx`.
- `python3.6 -m pip  install sphinx sphinx_rtd_theme`
- `bazel test --test_output=all --nocache_test_results //bindings/pydrake/doc:gen_sphinx_test`

The first commit `652aa39`, has already been reviewed in #12787 .
Please review the  the second one.

Closes #12604 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12921)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please.

**Comment by jwnimmer-tri** [comment]
Though its a bit "the cat was already out of the bag", this probably should have been squashed -- the first commit does not build (on macOS).

**Comment by EricCousineau-TRI** [comment]
Sorry about that!

**Comment by m-chaturvedi** [comment]
Sorry about that.  I had tried to follow these instructions:
https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

> Revert the revert of your originally-merged PR to get your changes back.

I thought it meant we'd like to keep the original commit intact.
I'll keep in mind that we want to make sure our code builds at every commit.

**Comment by jwnimmer-tri** [comment]
I think having the original commit around during review is helpful, we should just squash it before / when we're done.

**Pull request merged**
