### PR TITLE
bsplines: Add Serialize() for Bspline{Basis,Trajectory}<double>

### PR DESCRIPTION
**Pull request by avalenzu**
This allows parsing of these objects from YAML.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106)

### CODE REVIEW

**Review by avalenzu — COMMENTED** [review]
+@jwnimmer-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHq22tl3FI-84hrCdc5:b-1tks9q)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by avalenzu — COMMENTED** [review]
... Investigating CI failures ...

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHq53r11GmxTS48nZ0t:bb2kbxy)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by avalenzu — COMMENTED** [review]
I'm able to reproduce with clang locally. It doesn't like my use of `enable_if_t`:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/type_traits:2476:44: error: no type named 'type' in 'std::enable_if<false, void>'; 'enable_if' cannot be used to disable this declaration
    using enable_if_t = typename enable_if<_Cond, _Tp>::type;
                                           ^~~~~
bazel-out/k8-opt/bin/math/_virtual_includes/bspline_basis/drake/math/bspline_basis.h:192:8: note: in instantiation of template type alias 'enable_if_t' requested here
  std::enable_if_t<std::is_same_v<T, double>, void> Serialize(Archive* a) {
```
Is there something obvious that I'm doing wrong there?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHq5c7w4QzUJonvhy3D:b-26y0kd)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

___
*[common/trajectories/bspline_trajectory.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq4dgb4hxaR0zbtHsN:-MHq4dgb4hxaR0zbtHsO:btkwjit) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/common/trajectories/bspline_trajectory.h#L24)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(BsplineTrajectory);
> 
>   BsplineTrajectory() = default;
> ```

nit It took me a short while to convince myself that the default constructor obeys the invariants.  We could help facilitate that for future readers by having this constructor delegate to the other one explicitly (so the checks are run in Debug mode).  I don't feel strongly on that point, though.
___
*[common/trajectories/test/bspline_trajectory_test.cc, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq4U8f6nAlSsEOr9mR:-MHq4U8f6nAlSsEOr9mS:b-uplzzh) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/common/trajectories/test/bspline_trajectory_test.cc#L296)):*
> ```cpp
> }
> 
> const char* good = R"""(
> ```

nit Missing second `const` on globals, throughout:

```
const char* const good = ...
```
___
*[math/bspline_basis.h, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq4y9lDSTTEen_gGzj:-MHq4y9lDSTTEen_gGzk:btkwjit) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/bspline_basis.h#L38)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(BsplineBasis);
> 
>   BsplineBasis() = default;
> ```

nit It took me a short while to convince myself that the default constructor obeys the invariants.  We could help facilitate that for future readers by having this constructor delegate to the other one explicitly (so the checks are run in Debug mode).  I don't feel strongly on that point, though.
___
*[math/bspline_basis.h, line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq3NUT0Z6WYx8eyvNa:-MHq3NUT0Z6WYx8eyvNb:b-apqnut) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/bspline_basis.h#L190)):*
> ```objc
>   boolean<T> operator!=(const BsplineBasis& other) const;
> ```

nit No need for two vertical whitespace lines?
___
*[math/test/bspline_basis_test.cc, line 313 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq3uf10lwW_yxUTNPq:-MHq3uf10lwW_yxUTNPr:b-uplzzh) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/test/bspline_basis_test.cc#L313)):*
> ```cpp
> }
> 
> const char* good = R"""(
> ```

nit Missing second `const` on globals, throughout:

```
const char* const good = ...
```
___
*[math/test/bspline_basis_test.cc, line 333 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq439g4WlMhZNVMBKi:-MHq439h7MT_pN80B_SH:b-n9rx3w) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/test/bspline_basis_test.cc#L333)):*
> ```cpp
>   BsplineBasis<double> dut{};
>   EXPECT_THROW(YamlReadArchive(YAML::Load(not_enough_knots)).Accept(&dut),
>                std::runtime_error);
> ```

nit If there were a typo in the YAML data here, we might end up with an exception other than the invariants check.  To help convince the test is sound, it's probably worth checking the exception message for correctness (using Drake's testing macro).  The message isn't particularly helpful, but perhaps just confirm ".*CheckInvariants.*" appears in it?

Ditto below.

**Comment by jwnimmer-tri** [comment]
> I'm able to reproduce with clang locally.

I'll take a look.  We might need to ensure that `Archive` is part of the conditional expression, or else use template specialization instead of SFINAE.

**Review by avalenzu — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHq781sAX9YpBibQR7h:b-ucfknh)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

**Comment by jwnimmer-tri** [comment]
Here's a working fix for `math`; you can replicate to `trajectories`.

```c++
  /** Passes this object to an Archive; see @ref serialize_tips for background.
  This method is only available when T = double. */
  template <typename Archive>
#ifdef DRAKE_DOXYGEN_CXX
  void
#else
  // Restrict this method to T = double only; we must mix "Archive" into the
  // conditional type for SFINAE to work, so we just check it against void.
  std::enable_if_t<std::is_same_v<T, double> && !std::is_void<Archive>::value>
#endif
  Serialize(Archive* a) {
    a->Visit(MakeNameValue("order", &order_));
    a->Visit(MakeNameValue("knots", &knots_));
    DRAKE_THROW_UNLESS(CheckInvariants());
  }
```

**Comment by avalenzu** [comment]
Will do. Thanks!

**Review by avalenzu — COMMENTED** [review]
Review comments addressed. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHqMzWSAxwl83ZkoSy6:b-1ciy65)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[common/trajectories/bspline_trajectory.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq4dgb4hxaR0zbtHsN:-MHqK90b4-IjevW3vLWC:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/common/trajectories/bspline_trajectory.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It took me a short while to convince myself that the default constructor obeys the invariants.  We could help facilitate that for future readers by having this constructor delegate to the other one explicitly (so the checks are run in Debug mode).  I don't feel strongly on that point, though.
</blockquote></details>

Done.
___
*[common/trajectories/test/bspline_trajectory_test.cc, line 296 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq4U8f6nAlSsEOr9mR:-MHqKNkx1npczpmdfJPV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/common/trajectories/test/bspline_trajectory_test.cc#L296)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing second `const` on globals, throughout:

```
const char* const good = ...
```
</blockquote></details>

Done.
___
*[math/bspline_basis.h, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq4y9lDSTTEen_gGzj:-MHqKOzG1DDws76zCwBg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/bspline_basis.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It took me a short while to convince myself that the default constructor obeys the invariants.  We could help facilitate that for future readers by having this constructor delegate to the other one explicitly (so the checks are run in Debug mode).  I don't feel strongly on that point, though.
</blockquote></details>

Done.
___
*[math/bspline_basis.h, line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq3NUT0Z6WYx8eyvNa:-MHqKXvhE2CCI1E1L8eG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/bspline_basis.h#L190)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit No need for two vertical whitespace lines?
</blockquote></details>

Done.
___
*[math/test/bspline_basis_test.cc, line 313 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq3uf10lwW_yxUTNPq:-MHqL44V8peKbEe8R_Bl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/test/bspline_basis_test.cc#L313)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing second `const` on globals, throughout:

```
const char* const good = ...
```
</blockquote></details>

Done.
___
*[math/test/bspline_basis_test.cc, line 333 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14106#-MHq439g4WlMhZNVMBKi:-MHqMtyo3R77ASLuch69:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d813cdaf29a4c6d0d2a5279b6028ee66aee5816e/math/test/bspline_basis_test.cc#L333)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If there were a typo in the YAML data here, we might end up with an exception other than the invariants check.  To help convince the test is sound, it's probably worth checking the exception message for correctness (using Drake's testing macro).  The message isn't particularly helpful, but perhaps just confirm ".*CheckInvariants.*" appears in it?

Ditto below.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@rpoyner-tri for platform review per schedule, please.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHqO9Ra-Ib4V7A6U2Fl:b-gb4g9z)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14106#-:-MHqZAEVBNcZqDtRlKtp:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
