### PR TITLE
Add mixing_steps to IrisOptions

### LINKED ISSUE #20036: Poor performance of HPolyhedron::UniformSample
### What happened?

The hit-and-run algorithm only converges to the uniform distribution after a warmup period, aka mixing time. The paper "HIT-AND-RUN FROM A CORNER by Lovasz and Vempala" prove a convergence result (Corollary 1.2) which shows the dependence on the number of steps taken, and closeness to the uniform distribution. 

image

As it stands, HPolyhedron::UniformSample uses only a single iteration over a previous sample to return the next sample. If my understanding is correct, there needs to be an inner loop that runs many times, in order for the result to be close to uniformly distributed.

This is apparent if you imagine sampling from a very long, very thin, rod, in very high ambient dimension. For many samples, hit and run will not progress, since it must be very lucky to sample the into the long dimension of the rod. For this case, it's clear that consecutive samples are extremely correlated.

For standalone usage, this is not a big problem, since users can just manually warm up the function. But UniformSample is also used internally in IrisInConfigurationSpace during the counter-example search. For long and thin configuration spaces, I believe this will lead to extremely correlated starting seeds.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20036.

+@alexandreamice for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/iris.h` line 159 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr0xzXa0v0B20RJO9EH:-Nr0xzXa0v0B20RJO9EI:b-qjj341) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/iris.h#L159)):*
> ```objc
>   control the total number of hit-and-run steps taken for each new random
>   sample. */
>   int mixing_steps{10};
> ```

Would it make sense to leave this as an optional so that if we change `mixing_steps` default in `HPolyhedron` it also changes the default here.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/iris.h` line 159 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr0xzXa0v0B20RJO9EH:-Nr3SWBxC4GoB4rqGSBD:b5jliac) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/iris.h#L159)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Would it make sense to leave this as an optional so that if we change `mixing_steps` default in `HPolyhedron` it also changes the default here.
</blockquote></details>

I don't think so.  That's precisely the reason that it's better to define it explicitly here.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

+@ggould-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-:-Nr3bzZz4USZhSvDGszA:b-8c7m68)* status: LGTM missing from assignee ggould-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform)

___
*[`geometry/optimization/iris.h` line 36 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr3iSWzAq1hturgRzl3:-Nr3iSX01nSQ4oeUMhUK:bmz97ez) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/iris.h#L36)):*
> ```objc
>     a->Visit(DRAKE_NVP(num_collision_infeasible_samples));
>     a->Visit(DRAKE_NVP(num_additional_constraint_infeasible_samples));
>     a->Visit(DRAKE_NVP(random_seed));
> ```

nit Remember to the new field to `Serialize()` here.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: 3 unresolved discussions

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 919 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr5zHbC3bPJWLeJvF5O:-Nr621MP3sIRVHi_nh01:bi7zwrk) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/test/iris_in_configuration_space_test.cc#L919)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  Because the underlying paper is paywalled, I don't understand the effect of lower-quality sampling on IRIS.  It seems like the effect of only one mixing step is that the the chosen sample will be more likely to be central than extreme?  But I'm not clear why that would result in a smaller inscribed ellipsoid, in any deterministic way.
I'm going to take your word for it that this is sensible, but I don't have a mathematical intuition for the effect of sample quality on ellipsoid size.
</blockquote></details>

Lower mixing would lead to a less less uniform samples. This has the effect of clustering all the Iris counter-examples together. If sufficient counter-examples are found to ensure that the Iris region is truly collision-free, then one would expect that we could only find a sub-optimal region if we are not sampling the counter-examples uniformly, hence a smaller final ellipse. This is the case in this low dimensional example.

On the other hand, if Iris exits due to a work limit, then it is very likely that the final Iris region would not be collision-free and therefore our suboptimality is likely to give us a **larger** region. Some lab members have observed this latter behavior.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: 3 unresolved discussions

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 919 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr5zHbC3bPJWLeJvF5O:-Nr6AMBl0gtwAg0WhCKS:b-kywcx9) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/test/iris_in_configuration_space_test.cc#L919)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Lower mixing would lead to a less less uniform samples. This has the effect of clustering all the Iris counter-examples together. If sufficient counter-examples are found to ensure that the Iris region is truly collision-free, then one would expect that we could only find a sub-optimal region if we are not sampling the counter-examples uniformly, hence a smaller final ellipse. This is the case in this low dimensional example.

On the other hand, if Iris exits due to a work limit, then it is very likely that the final Iris region would not be collision-free and therefore our suboptimality is likely to give us a **larger** region. Some lab members have observed this latter behavior.
</blockquote></details>

Okay; I think the right answer then is to make the comment a bit more explicit; I've recommended some text.
If it's possible to assert that IRIS didn't hit a work limit you should do that as well to prove that you are in the expected regime and not just testing for random noise.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 919 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr6AUiU6mL6Qi6Zi9ir:-Nr6AUiU6mL6Qi6Zi9is:b3hylr8) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/test/iris_in_configuration_space_test.cc#L919)):*
> ```cpp
> 
>   // Confirm that mixing_steps has a tangible effect (this example is
>   // particularly sensitive to the sampling).
> ```

minor:  Suggested rewording based on other discussion.



_Suggestion:_
```cpp
  // Confirm that mixing_steps has a tangible effect; this example is
  // particularly sensitive to the sampling, obtaining a smaller
  // ellipsoid volume due to nonuniform sampling (and it does not
  // reach the IRIS work limit).
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

___
*[`geometry/optimization/iris.h` line 36 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr3iSWzAq1hturgRzl3:-NrAkRHR05zWRnc10SXq:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/iris.h#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Remember to the new field to `Serialize()` here.
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.h` line 159 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr60dw-Aye1lA9GwTSd:-NrAkS-7-P0OwKefitdJ:bk8fyab) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/iris.h#L159)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Minor, author's discretion, if the intent is to copy the default value from `HPolyhedron::UniformSample`, consider extracting it to a named constexpr in that file rather than copy-pasting it here?
</blockquote></details>

Alex asked me that, too.  I feel they are better as separate defaults, but don't feel strongly about it.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 919 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20974#-Nr6AUiU6mL6Qi6Zi9ir:-NrAl8XkAvmU8OpQAYcG:bs7wumx) ([raw file](https://github.com/RobotLocomotion/drake/blob/5181907ff1b3a9038fbaa87024a277f10eec785d/geometry/optimization/test/iris_in_configuration_space_test.cc#L919)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Suggested rewording based on other discussion.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20974)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Pull request merged**
