### PR TITLE
rename DirectTrajectoryOptimization to MultipleShooting

### PR DESCRIPTION
**Pull request by RussTedrake**
systems::DirectTrajectoryOptimization => systems::trajectory_optimization::MultipleShooting
systems::DircolTrajectoryOptimization => systems::trajectory_optimization::DirectCollocation 
No functional changes.
Part of #6858 
fyi @avalenzu , @hongkai-dai , @tarquasso

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6871)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for both levels of review please.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6871#-:-KrmKET3eITaMhEQHtql:b-j5somi)*

**Comment by avalenzu** [comment]
Now that I've thought about this some more, I'm concerned that `MultipleShooting` is going to be a confusing name for the abstract class because multiple shooting is a well-known concrete approach to solving trajectory optimization problems. If/when we implement a concrete multiple shooting approach, what will we call it?

What, if anything, in the class currently called `DirectTrajectoryOptimization` would prevent it from being the base class for a direct single shooting implementation? If the answer is "nothing", then I've come full-circle on this and think we should keep the current name: if a class can serve as the base for both direct collocation and direct single shooting, `DirectTrajectoryOptimization` is the right name for it. If there is something that would prevent that, we should talk about whether it needs to be in the base class.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6871#-:-KrpUylpZqyQBxzec_hm:but9v8y)*

**Comment by RussTedrake** [comment]
@avalenzu - i disagree (with today's andres, but agree with wednesday's).  :)

MultipleShooting, i think, means almost exactly what the base class provides.  For instance, we could have a concrete implementation for DirectMultipleShooting, or Indir ctMS

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6871#-:-KrpiHy92h64G1eixDIi:b-thx1xs)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6871#-:-KrpkQq8LbIIZ31jXT2P:bnfp4nl)*

**Comment by soonho-tri** [comment]
@russtedrake , I've added `do not merge` label in case you and @avalenzu want to continue the discussion. Please feel free to remove the label and merge the PR when you think it's good to go.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6871#-:-Krpkp62l0Ib3MhLIz-S:bj6vs9z)*

**Comment by avalenzu** [comment]
Russ and I had a f2f over lunch, and he convinced me to agree with Wednesday's Andrés :). -(status: do not merge) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6871#-:-Krq6WhF81brSRBzEfBz:bedv1pe)*

**Pull request merged**
