### PR TITLE
Add model_instances to CalcBiasCenterOfMassTranslationalAcceleration() 

### PR DESCRIPTION
**Pull request by mitiguy**
Work towards issue #21711 

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@joemasterjohn 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O2bmENT3ojPl_b_oIKG:bd6d1k1)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
Feature review -@joemasterjohn 
Feature review +@sherm1  

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O3-dIlB2tWt9t9SU_2Z:b-39wtg2)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
First pass done. Looks great, with a few minor things to take care of:
- needs some de-duplication for big comment blocks
- check that all the error conditions have a matching unit test
- after the requested changes, please generate the doxygen and verify that it formats the way you wanted it to. I saw some suspicious-looking Doxygen

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O30233sEMjG_5ZnO-UK:b-th4zlc)* status: 8 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/multibody_plant.h` line 4402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-wgR448o75dY6DEWP:-O3-wLza-vCXEtqMFFO1:bgjhc6y) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4402)):*
> ```objc
>   /// a𝑠Bias_AScm_E, Scm's translational acceleration bias in frame A with
>   /// respect to "speeds" 𝑠, expressed in frame E, where Scm is the center of
>   /// mass of S and 𝑠 is either q̇ (time-derivatives of generalized positions)
> ```

nit: not clear what the actual symbol name should be here since we can't literally put "q̇" in a variable name. Would it be aqBias_AScm_E ? Or aqdotBias_AScm_E?
___
*[`multibody/plant/multibody_plant.h` line 4405 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-xF1C5oW2K8EV-VGe:-O3-xF1C5oW2K8EV-VGf:b-hob985) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4405)):*
> ```objc
>   /// or v (generalized velocities). a𝑠Bias_AScm is the term in a_AScm (Scm's
>   /// translational acceleration in A) that does not include 𝑠̇, i.e.,
>   /// a𝑠Bias_AScm is Scm's translational acceleration in A when 𝑠̇ = 0. <pre>
> ```

minor: this seems like a very complicated way to say "the bias depends only on velocities". Saying what it _doesn't_ depend on is awkward. Please at least include the simple description.
___
*[`multibody/plant/multibody_plant.h` line 4415 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-xtDf-wb8fgEK0699:-O3-xtDf-wb8fgEK069A:bxzphxt) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4415)):*
> ```objc
>   /// JacobianWrtVariable::kV, indicating whether the spatial accceleration bias
>   /// is with respect to 𝑠 = q̇ or 𝑠 = v.
>   /// @param[in] frame_A The frame that measures a𝑠Bias_AScm.
> ```

minor: frames don't measure things. This change of wording seems wrong. What was wrong with A being "the frame in which the bias is measured"?
___
*[`multibody/plant/multibody_plant.h` line 4416 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-yE8wBtFD_s8pLbZV:-O3-yE8wBtFD_s8pLbZW:b-xbf8l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4416)):*
> ```objc
>   /// is with respect to 𝑠 = q̇ or 𝑠 = v.
>   /// @param[in] frame_A The frame that measures a𝑠Bias_AScm.
>   /// Currently, an exception is thrown if frame_A is not the World frame.
> ```

BTW is there a TODO for this?

(Later) I didn't see where this is actually done. Is it really still a limitation?
___
*[`multibody/plant/multibody_plant.h` line 4429 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-zB7-5ILnCCMkXdXF:-O3-zB7-5ILnCCMkXdXG:b-ksp38t) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4429)):*
> ```objc
>   /// @throws std::exception if `this` has no body except world_body().
>   /// @throws std::exception if mₛ ≤ 0, where mₛ is the mass of system S.
>   /// @note The world_body() is ignored. asBias_AScm_E = ∑ (mᵢ aᵢ) / mₛ, where
> ```

minor: this `@note` is stuck in the middle of the `@throws` -- better to group the exceptions together

Also, this is missing an `@throws` for frame A not being World as mentioned above.
___
*[`multibody/plant/multibody_plant.h` line 4437 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-z_j037W8OsRZqOTz:-O3-z_j037W8OsRZqOU-:b7grq4u) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4437)):*
> ```objc
>       const systems::Context<T>& context, JacobianWrtVariable with_respect_to,
>       const Frame<T>& frame_A, const Frame<T>& frame_E) const {
>     // TODO(Mitiguy) Allow with_respect_to to be JacobianWrtVariable::kQDot.
> ```

BTW TODO for Frame A != World?
___
*[`multibody/plant/multibody_plant.h` line 4443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-zlw23fe3u5bIcgRJ:-O3-zlw23fe3u5bIcgRK:bs8dplb) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4443)):*
> ```objc
>   }
> 
>   /// For the system S containing the selected model instances, calculates
> ```

minor: this section mostly duplicates the non-model-instance one. That's way too much duplication for something this complicated to discuss. This should be said only once and reference for both functions, with just the differences documented here. You could do that by documenting one of them and referring to the docs in the other, or (better I think) group these in a Doxygen `@name` group.
___
*[`multibody/plant/test/multibody_plant_jacobians_test.cc` line 640 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O301pkE-UrvFHV0Fryl:-O301pkE-UrvFHV0Frym:b-a3kz3p) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/test/multibody_plant_jacobians_test.cc#L640)):*
> ```cpp
>           *context_, model_instances, JacobianWrtVariable::kV, frame_A,
>           frame_W);
>   EXPECT_TRUE(CompareMatrices(aBias_AScm_W, aBias_AScm_W_model2, kTolerance));
> ```

minor: needs a test that makes sure adding duplicate model instances to the list doesn't affect the result

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`multibody/plant/multibody_plant.h` line 4402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-wgR448o75dY6DEWP:-O34xfWUBhN0ZDch4one:b399cyh) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4402)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: not clear what the actual symbol name should be here since we can't literally put "q̇" in a variable name. Would it be aqBias_AScm_E ? Or aqdotBias_AScm_E?
</blockquote></details>

Done.  Specific names not needed yet.  Based on monogram notation for Jacobians, the parallel names are aqdotBias\_AScm\_E and avBias\_AScm\_E
___
*[`multibody/plant/multibody_plant.h` line 4405 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-xF1C5oW2K8EV-VGe:-O34-Dff6utw-EyHeY0Z:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4405)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this seems like a very complicated way to say "the bias depends only on velocities". Saying what it _doesn't_ depend on is awkward. Please at least include the simple description.
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.h` line 4415 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-xtDf-wb8fgEK0699:-O340B5z6J4w5J68tCYR:b-dgwvvl) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4415)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: frames don't measure things. This change of wording seems wrong. What was wrong with A being "the frame in which the bias is measured"?
</blockquote></details>

Done. Here and elsewhere, with wording to parallel the subsequent line:
/// @param[in] frame_E The frame in which a𝑠Bias_AScm is expressed on output.
___
*[`multibody/plant/multibody_plant.h` line 4416 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-yE8wBtFD_s8pLbZV:-O340D6i6wpeDGIa6aaG:bpiiyuh) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4416)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is there a TODO for this?

(Later) I didn't see where this is actually done. Is it really still a limitation?
</blockquote></details>

Done.  No need for a TODO as this limitation was removed.
These limitations were removed both here and in related CalcBiasAcceleration() functions.

Note: This PR also adds tests for frame_A != World frame in
File: multibody_plant_jacobians_test.cc
TEST_F(TwoDOFPlanarPendulumTest,
       CalcJacobianVelocityAndBiasAccelerationEtcOfSystemCenterOfMass) 

Note: For related CalcBiasAcceleration() functions, there were already tests for a frame_A != World frame in
File:  multibody_plant_jacobians_test.cc
TEST_F(SatelliteTrackerTest, CalcBiasAccelerations) 
___
*[`multibody/plant/multibody_plant.h` line 4429 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-zB7-5ILnCCMkXdXF:-O34Q2g2Eq2UQHyPLjH1:b29mpln) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4429)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this `@note` is stuck in the middle of the `@throws` -- better to group the exceptions together

Also, this is missing an `@throws` for frame A not being World as mentioned above.
</blockquote></details>

Done.  @note moved.  No need to @throws for frame_A != World.
___
*[`multibody/plant/multibody_plant.h` line 4437 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-z_j037W8OsRZqOTz:-O34QeWxCoGE5z3V5suY:boey268) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4437)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW TODO for Frame A != World?
</blockquote></details>

Done.  No need.
___
*[`multibody/plant/multibody_plant.h` line 4443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3-zlw23fe3u5bIcgRJ:-O34xUfW3ceB4Gwv6CuK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/multibody_plant.h#L4443)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this section mostly duplicates the non-model-instance one. That's way too much duplication for something this complicated to discuss. This should be said only once and reference for both functions, with just the differences documented here. You could do that by documenting one of them and referring to the docs in the other, or (better I think) group these in a Doxygen `@name` group.
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_jacobians_test.cc` line 640 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O301pkE-UrvFHV0Fryl:-O34xWO67p2jt4QVPYbm:bizlqzz) ([raw file](https://github.com/RobotLocomotion/drake/blob/b64c64afc9c31b26dcdbf81c2d14cd75ad6f1266/multibody/plant/test/multibody_plant_jacobians_test.cc#L640)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: needs a test that makes sure adding duplicate model instances to the list doesn't affect the result
</blockquote></details>

Done.  Test added for this and related Jacobian function.

**Review by sherm1 — COMMENTED** [review]
Very nice! Feature :lgtm: pending a few minor comments

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O38oG5o0sDa57vcvSeb:b-gzs9yg)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/multibody_plant.h` line 4396 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O38mMzM7-BKAC0COVSz:-O38mMzNCHcDhrRBmBQv:b-tus5vt) ([raw file](https://github.com/RobotLocomotion/drake/blob/e37d5797a9cb690580811118cfa5b57ddff2616d/multibody/plant/multibody_plant.h#L4396)):*
> ```objc
> 
>   /// @anchor bias_acceleration_functions
>   /// @name Bias acceleration functions
> ```

minor: this grouping helps a lot! There are several other "bias acceleration" functions that should be in this group but are still in the "System matrix computations" group above.

They are: CalcBiasTerm(), CalBiasTranslationalAcceleration(), and CalcBiasSpatialAcceleration().

Having the new "bias acceleration" group but not having all the bias acceleration methods there could cause users to be unable to find the mis-grouped functions (they could reasonably assume this group has all the bias acceleration functions we have). Consider just moving them all into the new group now, even if you don't update their docs here.
___
*[`multibody/plant/multibody_plant.h` line 4434 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O38o00i63jNl5KnnO_x:-O38o00jAk-zrG9PmT7R:b-kn397g) ([raw file](https://github.com/RobotLocomotion/drake/blob/e37d5797a9cb690580811118cfa5b57ddff2616d/multibody/plant/multibody_plant.h#L4434)):*
> ```objc
>   /// @throws std::exception if `this` has no body except world_body().
>   /// @throws std::exception if mₛ ≤ 0, where mₛ is the mass of system S.
>   /// @throws std::exception if with_respect_to is not JacobianWrtVariable::kV
> ```

minor: this is an obscure way to express that kQdot is unimplemented. That should also get mentioned earlier in the function description. (Same for the other function)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`multibody/plant/multibody_plant.h` line 4396 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O38mMzM7-BKAC0COVSz:-O39fKRf-OaMkWM5IEgu:bnnp89e) ([raw file](https://github.com/RobotLocomotion/drake/blob/e37d5797a9cb690580811118cfa5b57ddff2616d/multibody/plant/multibody_plant.h#L4396)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this grouping helps a lot! There are several other "bias acceleration" functions that should be in this group but are still in the "System matrix computations" group above.

They are: CalcBiasTerm(), CalBiasTranslationalAcceleration(), and CalcBiasSpatialAcceleration().

Having the new "bias acceleration" group but not having all the bias acceleration methods there could cause users to be unable to find the mis-grouped functions (they could reasonably assume this group has all the bias acceleration functions we have). Consider just moving them all into the new group now, even if you don't update their docs here.
</blockquote></details>

As discussed: filed issue #21761 to do a follow-up PR ASAP to group the documentation for the related bias functions.
___
*[`multibody/plant/multibody_plant.h` line 4434 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O38o00i63jNl5KnnO_x:-O39iijQ96VtOyRgbsIx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e37d5797a9cb690580811118cfa5b57ddff2616d/multibody/plant/multibody_plant.h#L4434)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this is an obscure way to express that kQdot is unimplemented. That should also get mentioned earlier in the function description. (Same for the other function)
</blockquote></details>

Done.

**Review by mitiguy — COMMENTED** [review]
Platform review +@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O3AXnT87yxOFYsIxPB5:bfhin2l)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: Platform

> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O3E66bP0T9ByeEzqMB7:bdsgjya)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/multibody_plant.h` line 4408 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3E62IGDAZMLFYY3ALj:-O3E62IGDAZMLFYY3ALk:bwypsy1) ([raw file](https://github.com/RobotLocomotion/drake/blob/60329d00df5c9da8a8b16de2f5027654b2688b9f/multibody/plant/multibody_plant.h#L4408)):*
> ```objc
>   /// translational velocity Jacobian in frame A for s).  <pre>
>   ///   v_AP = J𝑠_v_AP ⋅ 𝑠         which upon vector differentiation in A gives
>   ///   a_AP = Ĵ𝑠_v_AP ⋅ 𝑠  +  J𝑠_v_AP ⋅ 𝑠̇                 𝑠etting 𝑠̇ = 0, gives
> ```

typo (font)



_Suggestion:_
```objc
  ///   a_AP = Ĵ𝑠_v_AP ⋅ 𝑠  +  J𝑠_v_AP ⋅ 𝑠̇                 setting 𝑠̇ = 0, gives
```

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-:-O3_KHDTBRdIDdpYZkno:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

___
*[`multibody/plant/multibody_plant.h` line 4408 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21740#-O3E62IGDAZMLFYY3ALj:-O3_6ivk5DacumAt0U-I:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/60329d00df5c9da8a8b16de2f5027654b2688b9f/multibody/plant/multibody_plant.h#L4408)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo (font)
</blockquote></details>

Done.

**Pull request merged**
