### PR TITLE
fix an off by one error in ExtractPrincipalMinor and add tests

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Sorry for the bug. Got too fancy.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-:-NlYZpMl44NobtU0BK44:b-6vo2mp)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  Sorry I didn't catch the bug in the previous PR either.

+@xuchenhan-tri for platform review please, thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-:-NlZRZP05nJBhp1gZg7V:b-intuyw)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with a couple of comments
+(release notes: fix) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-:-Nl_6A0a3loHpkwk46pv:bwxqywr)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 212 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-Nl_1qSi1FjQIgADaKdQ:-Nl_1qSi1FjQIgADaKdR:b4u3kbs) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4d9d895e84fc40e470ba3ac17610399aef2df52/math/matrix_util.h#L212)):*
> ```objc
> template <typename Derived>
> MatrixX<typename Derived::Scalar> ExtractPrincipalSubmatrix(
>     const Eigen::MatrixBase<Derived>& mat, const std::set<int>& indices) {
> ```

Looks like there's an implicit requirement on `indices` that it's non-empty. It should be documented and verified.
___
*[`math/matrix_util.h` line 220 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-Nl_3DuW4YhFR3HPkm8B:-Nl_3DuX8eu5UoL4Swwn:b-aealfx) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4d9d895e84fc40e470ba3ac17610399aef2df52/math/matrix_util.h#L220)):*
> ```objc
>   int interval_start{*it};
>   int interval_end{*it};
>   DRAKE_ASSERT(interval_start >= 0);
> ```

With this being a user-facing API, I don't think you want a `DRAKE_ASSERT` here. Consider `DRAKE_THROW_UNLESS` instead. Ditto below.
___
*[`math/matrix_util.h` line 233 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-Nl_54Fz3wTHGzOxreVa:-Nl_54G-9nQT-Ykx0wYA:b-h7cx5g) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4d9d895e84fc40e470ba3ac17610399aef2df52/math/matrix_util.h#L233)):*
> ```objc
>     }
>   }
>   intervals.emplace_back(interval_start, interval_end + 1);
> ```

BTW, you can avoid duplicating `interval_end = *it` if you so choose.



_Suggestion:_
```objc
for (++it; it != indices.end(); ++it) {
    if (*it != interval_end + 1) {
        intervals.emplace_back(interval_start, interval_end + 1);
        interval_start = *it;
    }
    interval_end = *it;
}
intervals.emplace_back(interval_start, interval_end + 1);
```

**Review by AlexandreAmice — COMMENTED** [review]
Thanks for the review. Could you check the new tests?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-:-NlcgRAT54V9GQx0jFBo:b-73j57d)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`math/matrix_util.h` line 212 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-Nl_1qSi1FjQIgADaKdQ:-Nl_Y6b19Zvlj7rtkK97:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4d9d895e84fc40e470ba3ac17610399aef2df52/math/matrix_util.h#L212)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Looks like there's an implicit requirement on `indices` that it's non-empty. It should be documented and verified.
</blockquote></details>

Done.
___
*[`math/matrix_util.h` line 220 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-Nl_3DuW4YhFR3HPkm8B:-Nl_Y7TnDERpdsyu3tc3:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4d9d895e84fc40e470ba3ac17610399aef2df52/math/matrix_util.h#L220)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With this being a user-facing API, I don't think you want a `DRAKE_ASSERT` here. Consider `DRAKE_THROW_UNLESS` instead. Ditto below.
</blockquote></details>

Done.
___
*[`math/matrix_util.h` line 233 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-Nl_54Fz3wTHGzOxreVa:-NlcgOBw8uCJ5M87vqV5:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4d9d895e84fc40e470ba3ac17610399aef2df52/math/matrix_util.h#L233)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, you can avoid duplicating `interval_end = *it` if you so choose.
</blockquote></details>

Thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20670#-:-Nld_3lW4SFARF7VkAiD:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees hongkai-dai,xuchenhan-tri(platform)

**Pull request merged**
