### PR TITLE
First pass of trajectory optimization classes cleanup (with symbolic support)

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds a new interface for accessing the time indexed decision variables, and dramatically simplifies the pendulum swing-up example.  Note especially the new AddRunningCost change.

Adds a few new simple trajectory optimization tests to provide (admittedly modest) coverage of the interface. 

Fixes the RunningCost to use trapezoidal integration -- the existing version was not doing proper integration -- with a big TODO due to the missing support for AddCost of > quadratic expressions.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5624)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review and +@soonho-tri for platform review (not his turn, but he's been involved with this).
n.b. - I will squash merge the three commits.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-:-KgCKhwHnvI16JDe_vpE:b-r616a7)*

**Comment by hongkai-dai** [comment]
checkpoint.

---

Reviewed 2 of 9 files at r1.
Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgDSdOO2q05UkbJaoUm:-KgDSdOO2q05UkbJaoUn:b-ek6fai) ([raw file](https://github.com/robotlocomotion/drake/blob/d096a3d7c4983946479e315ecfd3dc7d43b9d1e9/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L239)):*
> ```cpp
> 
>   // time(i) is the sum of h intervals 0...(i-1)
>   symbolic::Expression time =
> ```

Declare `time` as `const symbolic::Expression`?

I think it is better to use
```C++
const symbolic::Expression time = h_vars_.head(interval_index).cast<symbolic::Expression>().sum();
```
as the code is more readable, and do not need to create the dynamic sized vector `Eigen::RowVectorXd::Ones(interval_index)`.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgDUsuaBQIOahTLRiGL:-KgDUsubso_b-VWkeFBA:b-d0imqr) ([raw file](https://github.com/robotlocomotion/drake/blob/d096a3d7c4983946479e315ecfd3dc7d43b9d1e9/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L123)):*
> ```objc
>   ///    using DirectTrajectoryOptimization::AddRunningCost;
>   /// to "unhide" this method.
>   virtual void AddRunningCost(
> ```

Why this function needs to be virtual? If the derived classes will not change the implementation of this function, I think it is better to declare this function as non-virtual?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-:-KgDU69MHZGJgUlTKhy9:b6o68ox)*

**Comment by RussTedrake** [comment]
Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgDSdOO2q05UkbJaoUm:-KgEK6QmJiZXvZVNTGbV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d096a3d7c4983946479e315ecfd3dc7d43b9d1e9/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L239)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Declare `time` as `const symbolic::Expression`?

I think it is better to use
```C++
const symbolic::Expression time = h_vars_.head(interval_index).cast<symbolic::Expression>().sum();
```
as the code is more readable, and do not need to create the dynamic sized vector `Eigen::RowVectorXd::Ones(interval_index)`.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgDUsuaBQIOahTLRiGL:-KgEJHKA7gHn8u9L0Hnl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d096a3d7c4983946479e315ecfd3dc7d43b9d1e9/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L123)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why this function needs to be virtual? If the derived classes will not change the implementation of this function, I think it is better to declare this function as non-virtual?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by soonho-tri** [comment]
checkpoint

---

Reviewed 5 of 9 files at r1, 2 of 3 files at r2.
Review status: 7 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 243 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgEzrxljNdW6kzigZLV:-KgEzrxljNdW6kzigZLW:b-jgsfkf) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L243)):*
> ```cpp
> 
>   sub.insert(std::pair<symbolic::Variable, symbolic::Expression>(
>       placeholder_t_var_(0), time));
> ```

FYI, this line can be simplified into 
```c++
sub.emplace(placeholder_t_var_(0), time);
```

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgF-73wndDDCHLk9Pxy:-KgF-73wndDDCHLk9Pxz:bed1s4h) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L245)):*
> ```cpp
>       placeholder_t_var_(0), time));
>   for (int i = 0; i < num_states_; i++)
>     sub.insert(std::pair<symbolic::Variable, symbolic::Expression>(
> ```

FYI, this line can be simplified into
```c++
sub.emplace(placeholder_x_vars_(i), x_vars_(interval_index * num_states_ + i));
```

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 248 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgF-EBdNgYdqXS-SFHN:-KgF-EBdNgYdqXS-SFHO:b-9qe7zy) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L248)):*
> ```cpp
>         placeholder_x_vars_(i), x_vars_(interval_index * num_states_ + i)));
>   for (int i = 0; i < num_inputs_; i++)
>     sub.insert(std::pair<symbolic::Variable, symbolic::Expression>(
> ```

FYI, this line can be simplified into
```c++
sub.emplace(placeholder_u_vars_(i), u_vars_(interval_index * num_inputs_ + i));
```

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgExfovIQ8311ldzWAs:-KgExfow8WIHdDlBd7_A:b-cym8bw) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L121)):*
> ```objc
>   /// common output of most symbolic linear algebra operations.
>   /// Note: Derived classes will need to type
>   ///    using DirectTrajectoryOptimization::AddRunningCost;
> ```

An idea for a future PR to avoid this requirement:
 - Have a non-virtual `void AddRunningCost` defined in `DirectTrajectoryOptimization` class.
 - Have `virtual void DoAddRunningCost`. A derived class such as `DircolTrajectoryOptimization` is required to implement them.
 - `AddRunningCost` functions simply call `DoAddRunningCost`.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 353 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgEz31wbTLhO9iNwJit:-KgEz31wbTLhO9iNwJiu:b-dp4flg) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L353)):*
> ```objc
> 
>   /**
>    * Replace e.g. placeholder_x_var_ with x_vars_ at time interval
> ```

FYI, nit: `Replace` -> `Replaces`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-:-KgF2U1QXw5pKregMKpq:b-vv2shf)*

**Comment by soonho-tri** [comment]
Review status: 7 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFG_bnsY8Ofx4BcgUi:-KgFG_bnsY8Ofx4BcgUj:b-5q5cj8) (no related file):*
@russtedrake and @hongkai-dai : This morning, I wrote a symbolic/functional version of `AddRunningCost`. With this, we can write:
```c++
  dircol->AddRunningCost([](const symbolic::Expression& time,
                            const solvers::VectorXDecisionVariable& state,
                            const solvers::VectorXDecisionVariable& input) {
    return (10 * input * input)(0);
  });
```

The code is at https://github.com/soonho-tri/drake/commit/544df554635acf53a553a34950db211087c91d96. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by hongkai-dai** [comment]
Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 116 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFsiJOl15Tnhk7OajQ:-KgFsiJPZopJUqcMKEVj:b6km1q) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_collocation.cc#L116)):*
> ```cpp
>   // Trapezoidal integration:
>   //    sum_{i=0...N-2} h_i/2.0 * (g_i + g_{i+1}), or
>   // g_0*h_0/2.0 + [sum_{i=1...N-1} g_i (h_{i-1} + h_i)/2.0] + g_N*h_{N-1}/2.0.
> ```

Add a `*` between `g_i` and `(h_{i-1} + h_i)`?

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFtyJvMpmVk2hfUT0o:-KgFtyJvMpmVk2hfUT0p:b-mwfs2g) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_collocation.cc#L119)):*
> ```cpp
> 
>   // TODO(russt): Insert h(i) terms.  Currently not supported because it's
>   // no longer a quadratic constraint.
> ```

I filed an issue https://github.com/RobotLocomotion/drake/issues/5632 for this.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgExfovIQ8311ldzWAs:-KgFuLgj_e6DTojehYYf:b13xtdr) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L121)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

An idea for a future PR to avoid this requirement:
 - Have a non-virtual `void AddRunningCost` defined in `DirectTrajectoryOptimization` class.
 - Have `virtual void DoAddRunningCost`. A derived class such as `DircolTrajectoryOptimization` is required to implement them.
 - `AddRunningCost` functions simply call `DoAddRunningCost`.
</blockquote></details>

I like the NVI scheme! Can we require that the virtual `DoAddRunningCost` function be a private function?

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFqdAIu0-oOas1SLzl:-KgFqdAIu0-oOas1SLzm:b-ghsnc8) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L124)):*
> ```objc
>   /// to "unhide" this method.
>   void AddRunningCost(
>       const Eigen::Ref<const MatrixX<symbolic::Expression>>& g) {
> ```

Is the motivation of this function to handle the test case 
```C++
dircol->AddRunningCost((R * u) * u);
```
If so, I think we can write the test case as
```C++
dircol->AddRunningCost((R * u).dot(u));
```
which can call the function `AddRunningCost(const symbolic::Expression& g)` directly, instead of the matrix version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgExfovIQ8311ldzWAs:-KgG2YndgkSaOZRmx8pg:b-i1ek1n) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L121)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I like the NVI scheme! Can we require that the virtual `DoAddRunningCost` function be a private function?
</blockquote></details>

Sure. I'll open another PR after this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFG_bnsY8Ofx4BcgUi:-KgGMD1yGq-h0XyuLjtW:b10habf) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@soonho-tri , that looks great. How does it works with autodiff? We would want to take differentiation for the running cost in the general form (I think here it is in a quadratic form so we know how to differentiate it).
</blockquote></details>

For the record, had f2f with @hongkai-dai.

 - To support a generic/symbolic constraint, we need to introduce a new constraint class,`SymbolicArbitraryConstraint`, which includes a `symbolic::Expression` and implement `Eval` method.
 - This requires to make `Expression::Evaluate` a template function so that we can pass an environment with `AutoDiffScalar` not just `double`.

I'll work on the two items. However, we agree that this task has a low priority.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by RussTedrake** [comment]
Review status: 6 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFG_bnsY8Ofx4BcgUi:-KgHGrgQCE4XjGpTpqws:bbv0awy) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

For the record, had f2f with @hongkai-dai.

 - To support a generic/symbolic constraint, we need to introduce a new constraint class,`SymbolicArbitraryConstraint`, which includes a `symbolic::Expression` and implement `Eval` method.
 - This requires to make `Expression::Evaluate` a template function so that we can pass an environment with `AutoDiffScalar` not just `double`.

I'll work on the two items. However, we agree that this task has a low priority.
</blockquote></details>

Great.  But I'm afraid I think that SymbolicArbitraryConstraint might have high priority for me.  It is blocking the "correct" implementation of the integration in the objective function.  My objective function is not quadratic, `sum(h*u'*R*u)`, and I've set h=1 for now until we have > quadratic objectives.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 116 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFsiJOl15Tnhk7OajQ:-KgHHsVfiFYRS8px3dae:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_collocation.cc#L116)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add a `*` between `g_i` and `(h_{i-1} + h_i)`?
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFtyJvMpmVk2hfUT0o:-KgHHumVVHmCkVSiXj0d:b-1bjfvk) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_collocation.cc#L119)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I filed an issue https://github.com/RobotLocomotion/drake/issues/5632 for this.
</blockquote></details>

thanks.  

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 243 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgEzrxljNdW6kzigZLV:-KgHIFrMVGKTd4mUuLjX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L243)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this line can be simplified into 
```c++
sub.emplace(placeholder_t_var_(0), time);
```
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgF-73wndDDCHLk9Pxy:-KgHIFQKxacUI1FLDNEI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L245)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this line can be simplified into
```c++
sub.emplace(placeholder_x_vars_(i), x_vars_(interval_index * num_states_ + i));
```
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.cc, line 248 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgF-EBdNgYdqXS-SFHN:-KgHIEz45_b-JI833MK7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.cc#L248)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this line can be simplified into
```c++
sub.emplace(placeholder_u_vars_(i), u_vars_(interval_index * num_inputs_ + i));
```
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgExfovIQ8311ldzWAs:-KgHIJJ02ByRgdWS4Q0C:bd5l6mr) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L121)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Sure. I'll open another PR after this one.
</blockquote></details>

thanks!

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 124 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFqdAIu0-oOas1SLzl:-KgHITCqRJDQXS7PDs_W:b-d6aaob) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L124)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is the motivation of this function to handle the test case 
```C++
dircol->AddRunningCost((R * u) * u);
```
If so, I think we can write the test case as
```C++
dircol->AddRunningCost((R * u).dot(u));
```
which can call the function `AddRunningCost(const symbolic::Expression& g)` directly, instead of the matrix version.
</blockquote></details>

Yes -- that was the motivation.  I like your solution, but I'm not sure if I like requiring all users to know it?  

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 353 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgEz31wbTLhO9iNwJit:-KgHIjWhqq3zpiiL4Adz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dfb61bbae97c45469ff90e55d8e67b2d1acdba09/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L353)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, nit: `Replace` -> `Replaces`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-KgFG_bnsY8Ofx4BcgUi:-KgHaBb_h7ItfOakWi2w:b-kuhgkv) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Great.  But I'm afraid I think that SymbolicArbitraryConstraint might have high priority for me.  It is blocking the "correct" implementation of the integration in the objective function.  My objective function is not quadratic, `sum(h*u'*R*u)`, and I've set h=1 for now until we have > quadratic objectives.
</blockquote></details>

I see. I'll work on them this week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-:-KgHaAR2lKqrVPlkMa-U:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5624#-:-KgIDudmIZs8NYdIIl_H:bnfp4nl)*

**Pull request merged**
