### PR TITLE
py eigen_geometry: Remove all check semantics

### LINKED ISSUE #8960: pydrake eigen: Remove check semantics to more accurately reflect C++
Per comment:
https://github.com/robotlocomotion/drake/pull/8956#issuecomment-395849867

@SeanCurtis-TRI : To answer your question: I had started it out this way in wanting to have the Python functionality be a little more robust, but it does create awkward asymmetries, in that you can pass a non-unit / orthonormal `Eigen/Geometry` element from C++ to Python, and it won't know any better.

Ideally, the geometric entities in `drake/math/...` could be used to be better leverage checking for rotation matrices. For quaternions and angle-axes, I'm not sure what would be used in its place, but perhaps an overloaded function in Python such as `IsUnit()`.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This provides more parity with C++ API. Most importantly, it simplifies
the workflow of using Quaternion to get valid rotation matrices using
pydrake.math.

Resolves #8960

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14799)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@siyuanfeng-tri for feature review, please!
+@seancurtis-tri for platform review, please!

This fully removes *all* check semantics.
If this is too concerning, I can file a PR which removes them just for `Quaternion`.

\cc @mpetersen94 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14799#-:-MW6FJisDu-Wt_MqRK01:bpqr2fz)* status: LGTM missing from assignees siyuanfeng-tri,SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
what's causing pain right now? i don't fully get the motivation. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14799#-:-MW7EI798goQQGBnV9xr:b3i4bik)* status: LGTM missing from assignees siyuanfeng-tri,SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @siyuanfeng-tri)

**Comment by EricCousineau-TRI** [comment]
> what's causing pain right now? i don't fully get the motivation.

There's an asymmetry between what C++ and Python can express when using Eigen geometry types.

Example workflow in C++:
- I have a slightly shitty rotation matrix that's not within the ball of R^(3x3) surrounding SO(3) (tolerance check) that we want.
- I can do the suggested workflow of projecting that to SO(3) using `ProjectToRotationMatrix()` or just using `RotationMatrix<T>(ToQuaternion(your_Matrix3))`
- I'm happy.

Example workflow in Python:
-  I have slightly shitty rotation matrix (same as above)
- I try the `ToQuaternion` approach, but then I get this stupid error about having a bad rotation matrix... er... that's the whole point?
- I'm frustrated, so I do the `ProjectToRotationMatrix()`.
- It works, but really, what the ef?

**Comment by EricCousineau-TRI** [comment]
I committed an error :(

Originally when reading docs, I though `ToQuaternion(rot)` should've been `Quaternion(rot)`. But upon filing #14801, if it is using `RotationMatrix.ToQuaternion(rot)`, then this shouldn't be an issue.

@mpetersen94 Can you describe your pain points in a concrete workflow?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd be interested in the elaboration as well.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14799#-:-MWPKNCz0RDPeX3ec2kY:b2v40d5)* status: LGTM missing from assignees siyuanfeng-tri,SeanCurtis-TRI(platform) (waiting on @siyuanfeng-tri)

**Comment by EricCousineau-TRI** [comment]
Ah, seems like the pain point was here (I just didn't read closely):
https://github.com/RobotLocomotion/drake/issues/8960#issuecomment-802292181

> I've run into this problem repeatedly in my code as I try to do calculations based on the quaternion I get out of a MBP Simulator.  I keep having to write something similar to 
> ```
> x = mbp.GetPositions(context)
> quat = Quaternion(x[:4] / np.linalg.norm(x[:4]))
> ```
> 
> Is the solution to just delete [this function](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/common/eigen_geometry_py.cc#L62-L68) and all the places it is called in the bindings?  Or is there a better solution?

Seems like @sherm1's posting of #14800 is a much better path to solve this.

In this case, I will close this PR. I will also close the upstream issue w/ explanation.
Thanks, and sorry for the noise!

**Pull request closed without merging**
