### PR TITLE
Add meshcat visualizer via python bindings

### PR DESCRIPTION
**Pull request by RussTedrake**
The functionality (and the unit test I've provided) requires 
```
sudo pip install meshcat
```
Can we add that to `install_prerequisites.sh` ?  (I don't see any pip entries in there now)
Or can/should we make the test run only conditionally.... if the prereq exists?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9833)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@jamiesnape -- appreciate your thoughts.

**Comment by jwnimmer-tri** [comment]
On macOS, we already use pip: https://github.com/RobotLocomotion/drake/blob/master/setup/mac/binary_distribution/requirements.txt.

On Ubuntu, with only a quick peek, it looks like Bionic already has almost all of the prereqs of meshcat available as debs, so it should be easy to declare meshcat as a pure-python3 external. The only dependency not available on Bionic is a slightly too-old revision of ZMQ (16 vs 17).  As usual, our first preference should be to use the existing OS's typical mechanisms to intake dependencies, or at least the mechanisms we're already using.

I suggest that you try to get meshcat working on Bionic using `apt`.

For something on the periphery like meshcat support, I would personally okay have it only covered by macOS and Bionic CI, and to not test it in CI on Xenial.  Xenial users who want to run it could BYO pip2 install or whatever they are already doing.

**Comment by jwnimmer-tri** [comment]
It also looks like the `meshcat` API surface used by this code is extremely thin.  If this is the rough scale it will be indefinitely, then it should be trivial to stub it out for unit testing, without needing upstream `meshcat` as part of the Drake the build at all.

**Comment by RussTedrake** [comment]
I see.  So I could potentially stub out that thin meshcat implementation right in the meshcat_visualization_test.py and prove that my calls to meshcat were correct, and that would be sufficient?  of course it would not guarantee that things continue to work if meshcat moved forward... but maybe it's the right start?

**Comment by jwnimmer-tri** [comment]
The best resolution would be to add meshcat as a dependency of Drake, one way or another -- since I assume the reason you're adding the new code in this PR is that Drake will start to use meshcat in future PRs, so we'll need to solve it then anyway.  But if you don't want to wait to get that resolved, the unit test mock would let this move forward independently.

**Comment by jamiesnape** [comment]
I think if we bring in the dependencies via apt on Bionic and then use Bazel to bring in meshcat itself, then we could do the same with Mac (except with pip). Depends what we are more worried about: breakages of a given meshcat with newer versions of its dependencies, or breakages of Drake given a newer version of meshcat. Certainly having a mock meshcat would be good regardless of how we proceed.

**Comment by jwnimmer-tri** [comment]
On Ubuntu, users would not have `meshcat-server` on their default `$PATH` in any of the possibilities -- we would not `sudo pip install`, but rather `pip install --user` into `$HOME` or even `$WORKSPACE/virtualenv` for per-checkout pip's, or something else.  It would not be in `/usr/local/bin` in any case.

**Comment by jamiesnape** [comment]
@jwnimmer-tri so you are proposing potential upstream changes to get `meshcat` working with Bionic versions rather than bring in new versions via Bazel?

**Comment by jamiesnape** [comment]
Yes, I think we are on the same page. Just trying out meshcat with Bionic versions of dependencies now.

**Comment by EricCousineau-TRI** [comment]
Just to clarify, this means that these tests would not run on Xenial, either via Bazel tags or within the Python source?
And if we are incorporating `meshcat` dependencies into Bionic prereqs, does that mean we will be vendoring it in with our install?

**Comment by jamiesnape** [comment]
> Just to clarify, this means that these tests would not run on Xenial, either via Bazel tags or within the Python source?

Yes, probably not via tags.

> And if we are incorporating meshcat dependencies into Bionic prereqs, does that mean we will be vendoring it in with our install?

Most likely, yes.

**Comment by jwnimmer-tri** [comment]
I agree with Jamie.

I also think it would OK not to add meshcat to the install, at least in the first pass.

**Comment by rdeits** [comment]
The dependency versions listed in https://github.com/rdeits/meshcat-python/blob/master/setup.py are extremely conservative and were just specified from the packages I happened to have installed or could easily test. Earlier versions of those packages should be fine.

**Comment by RussTedrake** [comment]
Thanks @rdeits .  So is the recommendation that we try with the system packages, and PR a reduction in requirements to your setup.py if it works?

**Comment by rdeits** [comment]
Yup, that sounds good. In general, though, I'd still recommend using Python virtual environments over requiring users to install things system-wide.

**Comment by jamiesnape** [comment]
Ok, WIP PR using Bionic apt/Mac pip dependencies should be up shortly.

**Comment by RussTedrake** [comment]
Woot!   Great news.  Thanks.

**Comment by rdeits** [comment]
Yes, running `zmqserver.py` as a standalone script is not expected to work. The right thing would be `python -m meshcat.servers.zmqserver` or to write a python script that does: 

```py
from meshcat.servers.zmqserver import main
main()
```

which is what the existing meshcat install essentially does.

**Comment by jamiesnape** [comment]
Ok, seeing there was
```
if __name__ == '__main__':
    main()
```
in that file, I assumed it was meant to work.

**Comment by jamiesnape** [comment]
Did we lose the fixes from the last revision in the rebase?

**Comment by EricCousineau-TRI** [comment]
FYI Sorry I didn't catch this in the review, but `unittest` does not run tests unless they're prefixed with `test`; as indicated in #10007, that means this PR introduced a no-op test (well, it checks imports, but that's about it).

Docs: https://docs.python.org/2/library/unittest.html#basic-example

> The three individual tests are defined with methods whose names start with the letters `test`. This naming convention informs the test runner about which methods represent tests.

**Pull request merged**
