### PR TITLE
Toward #5204: add a dry-run option to automotive_demo.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5208)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@liangfok for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-:-KdBuzZsmrozA7Y9aWlB:b-m6pkmk)*

**Comment by liangfok** [comment]
:lgtm_strong: I verified that `--dry-run` works and that it also shows the command line flags that are passed to `automotive-demo` should they exist.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 225 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-KdCEjaW5pOYY2TUPiCi:-KdCEjaW5pOYY2TUPiCj:bxnf4s9) ([raw file](https://github.com/robotlocomotion/drake/blob/5ac056e5b283b1d3a2b62d4af9673f96d02ffe2e/drake/automotive/automotive_demo.py#L225)):*
> ```Python
>             # Await a message on the DRAKE_VIEWER_STATUS channel indicating
>             # that drake-visualizer is ready. This ensures that the demo
>             # app's LOAD_ROBOT message will be seen and processed.
> ```

BTW, why this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-:-KdCMCLSpYfZZCA1rNBX:b2rg68y)*

**Comment by rpoyner-tri** [comment]
+@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.py, line 225 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-KdCEjaW5pOYY2TUPiCi:-KdCN66FpINOjziaziaf:b-frvok6) ([raw file](https://github.com/robotlocomotion/drake/blob/5ac056e5b283b1d3a2b62d4af9673f96d02ffe2e/drake/automotive/automotive_demo.py#L225)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, why this change?
</blockquote></details>

It was editor shrapnel after several revisions. I didn't think it was worth reverting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-:-KdCNUKudGMvr56LKBk0:b-trzqz1)*

**Comment by liangfok** [comment]
BTW, I just noticed on bazel, the printed commands need to be run from `drake-distro/bazel-bin` and not from `drake-distro/`. Should this be documented?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-:-KdCO0RxCn-DSDCtHdXp:b-7vt8gf)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5208#-:-KdCP5mAxePMKCKCRLAo:bnfp4nl)*

**Pull request merged**
