### PR TITLE
Removed LcmPublisherSystem::GetMessage() method.

### PR DESCRIPTION
**Pull request by liangfok**
This is possible now that we have an LCM mocking framework (see #3643).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3779)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@sammy-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3779#-:-KTtORuc8vsyBh7B95HE:b-i1f1kk)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3779#-KTtYZv9avKCzkdiVay5:-KTtYZvAC6ObAidMmODL:bjm9hl5) ([raw file](https://github.com/robotlocomotion/drake/blob/e532d32d48352b4bebde42fa4fa6d063a38c6062/drake/automotive/test/automotive_simulator_test.cc#L71)):*
> ```cpp
>   GetLastPublishedJointValue(kJointStateChannelName,
>       state_pub.get_translator(),
>       dynamic_cast<lcm::DrakeMockLcm*>(simulator->get_lcm()), &joint_value);
> ```

BTW I would like to find a way to do this with less ceremony.  I will think on it, but feel free to merge first if this is holding things up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3779)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3779#-:-KTtlJXrUPCuWzMtmcTA:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. I will merge now and look forward to @jwnimmer-tri's ideas on how to decrease the amount of code necessary to convert from a serialized LCM message to a `BasicVector<double>`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3779#-:-KTtqxPdDXJaN40px19g:b-24ae82)*

**Comment by liangfok** [comment]
Oops. Looks like I need a LGTM from @jwnimmer-tri .

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3779#-:-KTtrIVNVf6j_kTk6Vuj:b-gxrlo8)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3779#-:-KTtroFsRwZJeB8mmCN_:bnfp4nl)*

**Pull request merged**
