### PR TITLE
Add log(det(X)) >= lower to MathematicalProgram.

### PR DESCRIPTION
**Pull request by hongkai-dai**
MathematicalProgram.AddLogDeterminantLowerConstraint imposes log(det(X)) >= lower as convex constraints.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-:-NhIox2k1kBEVPNijMHW:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
I think we need to add a test for Mosek too.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-:-NhZdrqKCJZRYQ91U6xt:b38u8g7)* status: 12 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 1214 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhWgl6R2Sip4ng2seO8:-NhWgl6R2Sip4ng2seO9:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1214)):*
> ```objc
>   /**
>    * @anchor log_determinant
>    * @name    Matrix log determinant
> ```





_Suggestion:_
```objc
 @name Matrix log determinant
```
___
*[`solvers/mathematical_program.h` line 1218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhWlBck8W1_kBK-avoa:-NhWlBck8W1_kBK-avob:b-5p4zh3) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1218)):*
> ```objc
>    * or imposes the constraint that the log determinant of X is lower-bounded.
>    * log(det(X)) is a concave function of X, so we can maximize it (or bound it
>    * from below) through convex optimization. In order to do that, we introduce
> ```

Suggesting:

```
Represents the log-determinant of `X` by introducing slack variables t, and a lower triangular matrix Z and imposing the constraints 

⌈X         Z⌉ is positive semidifinite.
⌊Zᵀ  diag(Z)⌋
   
log(Z(i, i)) >= t(i)

Since log(det(X)) is a concave function of X, we can either lower bound it's value by imposing the constraint `∑ᵢt(i) >= lower` or maximizing it's value by adding the cost  -∑ᵢt(i) using convex optimization.
```
___
*[`solvers/mathematical_program.h` line 1231 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhWkX8M5ShQ_UzGCl0S:-NhWkX8M5ShQ_UzGCl0T:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1231)):*
> ```objc
>    * @note The constraint log(Z(i, i)) >= t(i) is imposed as an exponential cone
>    * constraint. Please make sure your have a solver that supports exponential
>    * cone constraint (currently SCS does).
> ```





_Suggestion:_
```objc
SCS and Mosek do
```
___
*[`solvers/mathematical_program.h` line 1265 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZd6HA9_-4O3rOYF5D:-NhZd6HA9_-4O3rOYF5E:b-jins1w) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1265)):*
> ```objc
>    * @param X A symmetric positive semidefinite matrix X.
>    * @param lower The lower bound of log(det(X))
>    * @return (constraint, t, Z) constraint is ∑ᵢt(i) >= lower, we also return
> ```

Question. If I were to call `prog.RemoveConstraint(constraint)` immediately after calling this method, would this be sufficient to completely remove the `logdet` constraint? I believe it would be as then I can set `t` and `Z` to `0`, but it may be worth testing this.



_Code quote:_
```objc
(constraint, t, Z) constraint is ∑ᵢt(i) >= lower
```
___
*[`solvers/mathematical_program.h` line 1272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZZywz0sd8jXPZYfsZ:-NhZZyx-3E1nvBPUW3ZU:buqf73l) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1272)):*
> ```objc
>    */
>   std::tuple<Binding<LinearConstraint>, VectorX<symbolic::Variable>,
>              MatrixX<symbolic::Expression>>
> ```

Would it make more sense to return just the lower triangular part of `Z`? I know this would be a breaking change of the `AddMaximizeLogDeterminantCost`, but that way we get to return a Vector instead of a matrix.

Just a thought, not a suggestion we have to implement.



_Code quote:_
```objc
MatrixX<symbolic::Expression>
```
___
*[`solvers/mathematical_program.h` line 1273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZbmnH83503KTLWYr3:-NhZbmnH83503KTLWYr4:bmeklpp) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1273)):*
> ```objc
>   std::tuple<Binding<LinearConstraint>, VectorX<symbolic::Variable>,
>              MatrixX<symbolic::Expression>>
>   AddLogDeterminantLowerBound(
> ```

All the other `Add` methods either say constraint or cost, so I think it would be consistent to change the name even if it is longer.



_Suggestion:_
```objc
AddLogDeterminantLowerBoundConstraint
```
___
*[`solvers/mathematical_program.h` line 3084 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZ_M1uBRNuoHRg91NZ:-NhZ_M1uBRNuoHRg91N_:bu08rzf) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L3084)):*
> ```objc
>   const SolverOptions& solver_options() const {
>     return solver_options_;
>   }
> ```

Spurious change here.



_Code quote:_
```objc
    return solver_options_;
  }
```
___
*[`solvers/mathematical_program.h` line 3241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZ_P0nCaub-2vCRISR:-NhZ_P0nCaub-2vCRISS:b-yfwilt) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L3241)):*
> ```objc
>   const Eigen::VectorXd& initial_guess() const {
>     return x_initial_guess_;
>   }
> ```

Spurious change probably from clang-format.



_Code quote:_
```objc
  /** Getter for number of variables in the optimization program */
  int num_vars() const {
    return decision_variables_.size();
  }

  /** Gets the number of indeterminates in the optimization program */
  int num_indeterminates() const {
    return indeterminates_.size();
  }

  /** Getter for the initial guess */
  const Eigen::VectorXd& initial_guess() const {
    return x_initial_guess_;
  }
```
___
*[`solvers/mathematical_program.h` line 3515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZ_S3p2g58ulRzWlJg:-NhZ_S3p2g58ulRzWlJh:bs4q9np) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L3515)):*
> ```objc
>   void ClearVariableScaling() {
>     var_scaling_map_.clear();
>   }
> ```

Ditto



_Code quote:_
```objc
  void ClearVariableScaling() {
    var_scaling_map_.clear();
  }
```
___
*[`solvers/mathematical_program.cc` line 575 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZb6CYB_uI6yA9HFHi:-NhZb6CYB_uI6yA9HFHj:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.cc#L575)):*
> ```cpp
> 
> namespace {
> void LogDeterminantHelper(
> ```





_Suggestion:_
```cpp
CreateLogDeterminantConstraint
```
___
*[`solvers/test/exponential_cone_program_examples.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZc80t2pubiWboYev6:-NhZc80t2pubiWboYev7:b-a6kacz) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/test/exponential_cone_program_examples.cc#L145)):*
> ```cpp
>   auto X = prog.NewSymmetricContinuousVariables<3>();
>   const double lower = 1;
>   prog.AddLogDeterminantLowerBound(X.cast<symbolic::Expression>(), lower);
> ```

I think this test would be better if there was a cost applying downward pressure on the log determinant. Otherwise, it is hard to disambiguate whether you got lucky that the constraint wasn't active, or whether the constraint is actually being enforced.
___
*[`solvers/test/mathematical_program_test.cc` line 4448 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZdbdP6CkFAxSbWQHK:-NhZdbdP6CkFAxSbWQHL:b2lumbj) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/test/mathematical_program_test.cc#L4448)):*
> ```cpp
>     EXPECT_TRUE(constraint.variables()(i).equal_to(t(i)));
>   }
>   EXPECT_FALSE(prog.exponential_cone_constraints().empty());
> ```

I would put the actual expected number of exponential cone constraints and psd constraints in here rather than just checking emptiness.



_Code quote:_
```cpp
EXPECT_FALSE(prog.exponential_cone_constraints().empty());
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411)* status: 11 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 1214 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhWgl6R2Sip4ng2seO8:-Nh_OgFaEIlduAJo5k9e:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1214)):*
> ```objc
>   /**
>    * @anchor log_determinant
>    * @name    Matrix log determinant
> ```

Done.
___
*[`solvers/mathematical_program.h` line 1231 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhWkX8M5ShQ_UzGCl0S:-Nh_PL7G0TG2hvNa1_-O:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1231)):*
> ```objc
>    * @note The constraint log(Z(i, i)) >= t(i) is imposed as an exponential cone
>    * constraint. Please make sure your have a solver that supports exponential
>    * cone constraint (currently SCS does).
> ```

Done.
___
*[`solvers/mathematical_program.h` line 1265 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZd6HA9_-4O3rOYF5D:-Nh_QQ4c-uWMR8DtB-qt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1265)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Question. If I were to call `prog.RemoveConstraint(constraint)` immediately after calling this method, would this be sufficient to completely remove the `logdet` constraint? I believe it would be as then I can set `t` and `Z` to `0`, but it may be worth testing this.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 1272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZZywz0sd8jXPZYfsZ:-Nh_QYsY3f92tnoo1EYI:b-7b1rrg) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1272)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Would it make more sense to return just the lower triangular part of `Z`? I know this would be a breaking change of the `AddMaximizeLogDeterminantCost`, but that way we get to return a Vector instead of a matrix.

Just a thought, not a suggestion we have to implement.
</blockquote></details>

Is your concern on Vector versus Matrix, or symbolic::Variable versus symbolic::Expression? We could return `VectorX<symbolic::Variable>` instead of `Matrix<symbolic::Expression>` and I can see the appeal of Variable instead of Expression. (Variable->Expression is easy, but Expression->Variable is harder). 

Anyway, if we want to change it to VectorX<symbolic::Variable>, I would rather do it in a separate PR, as that would be a breaking change. 
___
*[`solvers/mathematical_program.h` line 1273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZbmnH83503KTLWYr3:-Nh_SMQEAbbk5Ql7ngyM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1273)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

All the other `Add` methods either say constraint or cost, so I think it would be consistent to change the name even if it is longer.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 3084 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZ_M1uBRNuoHRg91NZ:-Nh_SUI71D0E3othKbT2:bn4rc0k) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L3084)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Spurious change here.
</blockquote></details>

Done. This is just clang-format.
___
*[`solvers/mathematical_program.h` line 3241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZ_P0nCaub-2vCRISR:-Nh_ShVaBqWbxFjOc-Tu:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L3241)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Spurious change probably from clang-format.
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 3515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZ_S3p2g58ulRzWlJg:-Nh_SkaW4X3BSO2eNm7G:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L3515)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 575 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZb6CYB_uI6yA9HFHi:-Nh_SuSHBNY20RIN7Sb-:b-qvqu1l) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.cc#L575)):*
> ```cpp
> 
> namespace {
> void LogDeterminantHelper(
> ```

Done. I renamed it "CreateLogDeterminant" as it is also used in AddMaximizeLogDeterminantCost.
___
*[`solvers/test/exponential_cone_program_examples.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZc80t2pubiWboYev6:-Nh_TQZt-6Sx9grE0HLK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/test/exponential_cone_program_examples.cc#L145)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think this test would be better if there was a cost applying downward pressure on the log determinant. Otherwise, it is hard to disambiguate whether you got lucky that the constraint wasn't active, or whether the constraint is actually being enforced.
</blockquote></details>

Done.
___
*[`solvers/test/mathematical_program_test.cc` line 4448 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZdbdP6CkFAxSbWQHK:-Nh_Td7M2st1O3onXVpd:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/test/mathematical_program_test.cc#L4448)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would put the actual expected number of exponential cone constraints and psd constraints in here rather than just checking emptiness.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: minus one naming thing

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-:-NhanqFV5a1KMLyKKT70:b64r54f)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 1272 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZZywz0sd8jXPZYfsZ:-NhanDfm092peiIkcxrj:b-sqbdjv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1272)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is your concern on Vector versus Matrix, or symbolic::Variable versus symbolic::Expression? We could return `VectorX<symbolic::Variable>` instead of `Matrix<symbolic::Expression>` and I can see the appeal of Variable instead of Expression. (Variable->Expression is easy, but Expression->Variable is harder). 

Anyway, if we want to change it to VectorX<symbolic::Variable>, I would rather do it in a separate PR, as that would be a breaking change.
</blockquote></details>

I meant going from Expression to Variable, but yes I agree it is likely out of scope
___
*[`solvers/mathematical_program.h` line 1273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZbmnH83503KTLWYr3:-NhanQpv7rXd78TghV4q:be245fv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1273)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would leave it as `AddLogDeterminantLowerBoundConstraint`
___
*[`solvers/mathematical_program.h` line 1224 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-Nhan5ns6SIcE_Gb6cw0:-Nhan5ns6SIcE_Gb6cw1:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/685d6cdcc2546d448777305e9cc103bb1c6bced8/solvers/mathematical_program.h#L1224)):*
> ```objc
>    *
>    * Since log(det(X)) is a concave function of X, we can either lower bound
>    * it's value by imposing the constraint `∑ᵢt(i) >= lower` or maximizing it's
> ```





_Suggestion:_
```objc
maximize
```
___
*[`solvers/mathematical_program.h` line 1225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-Nhan8zU5htSNwDrK6w7:-Nhan8zV4USnYGREy6-K:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/685d6cdcc2546d448777305e9cc103bb1c6bced8/solvers/mathematical_program.h#L1225)):*
> ```objc
>    * Since log(det(X)) is a concave function of X, we can either lower bound
>    * it's value by imposing the constraint `∑ᵢt(i) >= lower` or maximizing it's
>    * value by adding the cost  -∑ᵢt(i) using convex optimization.
> ```





_Suggestion:_
```objc
cost -∑ᵢt(i)
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/mathematical_program.h` line 1273 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-NhZbmnH83503KTLWYr3:-NhdF97a5bt_ttUoBqU5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fd2d2dca1d36d6fb1b7bae960c7a1f4e0d6aa9c/solvers/mathematical_program.h#L1273)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would leave it as `AddLogDeterminantLowerBoundConstraint`
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.h` line 1224 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-Nhan5ns6SIcE_Gb6cw0:-NhdELYW4-qJmtYAnD8I:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/685d6cdcc2546d448777305e9cc103bb1c6bced8/solvers/mathematical_program.h#L1224)):*
> ```objc
>    *
>    * Since log(det(X)) is a concave function of X, we can either lower bound
>    * it's value by imposing the constraint `∑ᵢt(i) >= lower` or maximizing it's
> ```

Done.
___
*[`solvers/mathematical_program.h` line 1225 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-Nhan8zU5htSNwDrK6w7:-NhdEM4I1VlatxcC2yvw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/685d6cdcc2546d448777305e9cc103bb1c6bced8/solvers/mathematical_program.h#L1225)):*
> ```objc
>    * Since log(det(X)) is a concave function of X, we can either lower bound
>    * it's value by imposing the constraint `∑ᵢt(i) >= lower` or maximizing it's
>    * value by adding the cost  -∑ᵢt(i) using convex optimization.
> ```

Done.

**Review by AlexandreAmice — COMMENTED** [review]
+@sammy-tri for platform review.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-:-Nhg1QRrBYseWuEoGit6:bpk00vl)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 1 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-:-NhhFr2fBS6AqSMTAXyP:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20411#-:-NhhFta33HtT0kwjxeM0:b-l8xbmn)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),AlexandreAmice

**Pull request merged**
