### PR TITLE
[doc] Add release notes v1.1.0

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Adding label per (latent addressing of) [Drake Platform Reviewer Checklist](https://drake.mit.edu/platform_reviewer_checklist.html)

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for (eventual) full review, and for text of #16840.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-Mz0ricc7dT926LfF1x0:bwufwga)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-Mz0rz9eEBdbQqGSGPce:ba0k9zt)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[doc/_release-notes/v1.1.0.md, line 30 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz0tCqi4LHGi-znkIZd:-Mz0tCqi4LHGi-znkIZe:b-d519xq) ([raw file](https://github.com/robotlocomotion/drake/blob/cca52ff491f2f28b4f60baf5443294c629754ad5/doc/_release-notes/v1.1.0.md#L30)):*
> ```Markdown
> * TBD
> 
> ## Mathematical Program
> ```

+@hongkai-dai for review of the mathematical program section. 
___
*[doc/_release-notes/v1.1.0.md, line 57 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz0tXU472zkq3z3oi0_:-Mz0tXU472zkq3z3oi0a:bbuk8n6) ([raw file](https://github.com/robotlocomotion/drake/blob/cca52ff491f2f28b4f60baf5443294c629754ad5/doc/_release-notes/v1.1.0.md#L57)):*
> ```Markdown
> * Create new method Frame::CalcSpatialAcceleration() and improve related documentation and tests ([#16760][_#16760])
> * Add `MultibodyPlant::GetEffortLowerLimits` (and friends) ([#16835][_#16835])
> * Route SDFormat warnings through DiagnosticPolicy ([#16819][_#16819])  # This will allow us to more easily toggle their strictness.
> ```

@jwnimmer-tri do we want to do a roll-up single line for parser error plumbing?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[doc/_release-notes/v1.1.0.md, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz0vO0OA-xIcETYLm9f:-Mz0vO0OA-xIcETYLm9g:b-7jdtov) ([raw file](https://github.com/robotlocomotion/drake/blob/cca52ff491f2f28b4f60baf5443294c629754ad5/doc/_release-notes/v1.1.0.md#L143)):*
> ```Markdown
> * drake::systems::ScalarInitialValueProblem::ScalarOdeContext ([#16739][_#16739])
> * drake::TrigPoly ([#16741][_#16741])
> * TBD something something scipy ([#16840][_#16840])
> ```

@jwnimmer-tri to provide text here

**Review by jwnimmer-tri — COMMENTED** [review]
FYI I'm mostly unavailable today.  I can circle back with review (and push fixes) no later than first thing on Monday.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-Mz12WDq7_aNJnt_SKPN:b72hthh)* status: 8 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[doc/_release-notes/v1.1.0.md, line 57 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz0tXU472zkq3z3oi0_:-Mz12TrY2fI0E7Nzv03R:b-vpyjnk) ([raw file](https://github.com/robotlocomotion/drake/blob/cca52ff491f2f28b4f60baf5443294c629754ad5/doc/_release-notes/v1.1.0.md#L57)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@jwnimmer-tri do we want to do a roll-up single line for parser error plumbing?
</blockquote></details>

My vote is "yes".
___
*[doc/_release-notes/v1.1.0.md, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz0vO0OA-xIcETYLm9f:-Mz12jRx4E9RHk5JnH9w:bwtr3ky) ([raw file](https://github.com/robotlocomotion/drake/blob/cca52ff491f2f28b4f60baf5443294c629754ad5/doc/_release-notes/v1.1.0.md#L143)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@jwnimmer-tri to provide text here
</blockquote></details>

Here's a first attempt.  It might be worth copying all or parts of this into several sections of the notes: "build dependencies" and/or "newly deprecated" and/or "announcements".

* Drake's binary releases currently depend on scipy (via apt on Ubuntu, or brew on macOS); that dependency is now deprecated and will be removed on or after 2022-07-01.  Users who want to take advantage of pydrake's scipy.sparse matrices after that date need to add their own dependency on scipy to their project directly.  (There are exceedingly few uses of sparse matrices in pydrake, so most users need not take any action.)
___
*[doc/_release-notes/v1.1.0.md, line 89 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz14iOH3aQRrlH30iNe:-Mz14iOH3aQRrlH30iNf:b-uky0r5) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L89)):*
> ```Markdown
> 
> * Add realsense camera geometries to manipulation station ([#16719][_#16719])
> * Remove the camera mesh from self-perception ([#16754][_#16754])
> ```

nit I think 16754 is a hotfix for 16719, in which case it should just be an extra ticket number of the same bullet.  (I can double-check and push this fix later on, if you like.)
___
*[doc/_release-notes/v1.1.0.md, line 113 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz14_bA-0-wMpk6Omjn:-Mz14_bA-0-wMpk6Omjo:bhu2mr6) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L113)):*
> ```Markdown
> * Ensure GIL is locked when logging from a C++ worker thread ([#16724][_#16724])
> * Use NginX when on Deepnote for Meshcat connections ([#16805][_#16805])
> * Remove stray print in StartMeshcat ([#16830][_#16830])
> ```

nit I think 16830 is a hotfix for 16805, in which case it should just be an extra ticket number of the same bullet.  (I can double-check and push this fix later on, if you like.)
___
*[doc/_release-notes/v1.1.0.md, line 133 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz14EZ5A7F8p5a_fLXZ:-Mz14EZ5A7F8p5a_fLX_:b-d251vq) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L133)):*
> ```Markdown
> 
> 
> * Build yaml-cpp from source ([#16701][_#16701], [#16728][_#16728], [#16756][_#16756])
> ```

nit The yaml-cpp detail is probably slightly more relevant as a "# Build dependencies" rather than "Build system".  Shrug.
___
*[doc/_release-notes/v1.1.0.md, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz13y-NAuJTwDh0FuVD:-Mz13y-NAuJTwDh0FuVE:bb8keja) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L135)):*
> ```Markdown
> * Build yaml-cpp from source ([#16701][_#16701], [#16728][_#16728], [#16756][_#16756])
> * Enable split debug symbols on Ubuntu ([#16587][_#16587], [#16788][_#16788])
> * Update Gurobi version in CMake FindGurobi module ([#16794][_#16794])
> ```

nit I think 16794 is a hotfix for 16716, in which case it should just be an extra ticket number of the same bullet.  (I can double-check and push this fix later on, if you like.)
___
*[doc/_release-notes/v1.1.0.md, line 138 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz148kv1bIkCc9DzpvH:-Mz148kw01rNY-dbomaM:bq6sq31) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L138)):*
> ```Markdown
> * Don't build libsdformat's URDF parser ([#16772][_#16772])
> * Stop using mutable globals from SDFormat ([#16791][_#16791])
> * Update gurobi install directory on macOS ([#16803][_#16803])
> ```

nit I think 16803 is a hotfix for 16716, in which case it should just be an extra ticket number of the same bullet.  (I can double-check and push this fix later on, if you like.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862)* status: 6 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[doc/_release-notes/v1.1.0.md, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz13y-NAuJTwDh0FuVD:-MzG6nI_BzGCYkSAVnGs:b291vns) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Yes.  Please move down to ad onto 16716's line.
___
*[doc/_release-notes/v1.1.0.md, line 138 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz148kv1bIkCc9DzpvH:-MzG6vG5Dml5hAZIBHuI:b291vns) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L138)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Yes.  Please move down to ad onto 16716's line.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-MzGBUB29D85nmJxTgSS:b-om6exd)* status: 6 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[doc/_release-notes/v1.1.0.md, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz13y-NAuJTwDh0FuVD:-MzG8KwZ1hBD_87cFt_z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  Please move down to ad onto 16716's line.
</blockquote></details>

Done.
___
*[doc/_release-notes/v1.1.0.md, line 138 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16862#-Mz148kv1bIkCc9DzpvH:-MzG8XRK8F9OROpU1NZu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/774adf1da778dfa7e988cc5833ff00268d92ca20/doc/_release-notes/v1.1.0.md#L138)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  Please move down to ad onto 16716's line.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-MzGBwOvCckEUQtYv1ax:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-@hongkai-dai 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-MzGNO2F-uaBQfWfQi81:b-uz7c1m)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-MzGPZ6A6VpyJk-VfmMO:bk7giky)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16862#-:-MzGTFkW-LWlIiQ7PRLm:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Comment by rpoyner-tri** [comment]
@BetsyMcPhail  Release v1.1.0 is ready; please manually tag docker images and upload the releases to S3. Thanks!
Date: 2022-03-28
Commit: c79c94b0afcf2b2691f81b5a27e15dd32a5c3a23
Tag: https://github.com/RobotLocomotion/drake/releases/tag/v1.1.0

**Comment by BetsyMcPhail** [comment]
S3, Docker and apt packages are done

**Pull request merged**
