### PR TITLE
drake_py_unittest: Add --trace={none,user,sys} for source tracing, --stdout_to_stderr for sensible output

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I've found both of these features very useful when debugging C++ +`pybind11` + Python behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8439)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8439#-:-L8EQkLWhT9bNLJGFDcZ:bcbis2v)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/test_utilities/drake_py_unittest_main.py, line 74 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439#-L8EUAvB-GzNLbWWsfr2:-L8EUAvDB3jH5r7yLs8N:bkm9ew5) ([raw file](https://github.com/robotlocomotion/drake/blob/e076a00e7ff21452f307264399f2508603c812fa/common/test_utilities/drake_py_unittest_main.py#L74)):*
> ```Python
>     while index < len(sys.argv):
>         arg = sys.argv[index]
>         if arg == "--":
> ```

Is the only purpose of this to get help working?

If so, I suggest a simpler approach -- check when `--help` is seen, and print _all_ parser's help strings, something like:
https://github.com/RobotLocomotion/drake/blob/master/automotive/automotive_demo.py#L222-L225. 

If not, needs a comment here about exactly what's going on that I didn't understand.

---

*[common/test_utilities/drake_py_unittest_main.py, line 95 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439#-L8EUacg7l4KQzWwKo6i:-L8EUacg7l4KQzWwKo6j:b-17t9pc) ([raw file](https://github.com/robotlocomotion/drake/blob/e076a00e7ff21452f307264399f2508603c812fa/common/test_utilities/drake_py_unittest_main.py#L95)):*
> ```Python
>         "--stdout_to_stderr", action="store_true",
>         help="Pipe stdout to stderr. When running from the Bazel client " +
>              "(non-batch), output may be mixed. This streamlines the output.")
> ```

FYI Should we just always do this (maybe with an optional way to disable?).  It seems like a no-brainer.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439#-:-L8EUkes9NAN4zHxTLRd:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test_utilities/drake_py_unittest_main.py, line 74 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439#-L8EUAvB-GzNLbWWsfr2:-L8EYODNC26osLuMA9ke:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/e076a00e7ff21452f307264399f2508603c812fa/common/test_utilities/drake_py_unittest_main.py#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is the only purpose of this to get help working?

If so, I suggest a simpler approach -- check when `--help` is seen, and print _all_ parser's help strings, something like:
https://github.com/RobotLocomotion/drake/blob/master/automotive/automotive_demo.py#L222-L225. 

If not, needs a comment here about exactly what's going on that I didn't understand.
</blockquote></details>

Done. Thanks!

---

*[common/test_utilities/drake_py_unittest_main.py, line 95 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439#-L8EUacg7l4KQzWwKo6i:-L8EYQlX1t5RWOCLnxp1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e076a00e7ff21452f307264399f2508603c812fa/common/test_utilities/drake_py_unittest_main.py#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Should we just always do this (maybe with an optional way to disable?).  It seems like a no-brainer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8439#-:-L8EbObW-PQeHyLSqQDA:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
