### PR TITLE
[tools] Add push_release script to drake

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #17736.

- This is the current version (ready for focal + jammy) on s3.
- Only change: user must manually set `gpg_key` variable for now, comments added to explain.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18075)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for review please.  CC @jwnimmer-tri we're adding the most minimal set of changes here possible (only comments + a variable change), it can be improved upon.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18075#-:-NE6eKWtAyNLNlx1unlr:b6sms03)* status: LGTM missing from assignee BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail)

___
*[`tools/release_engineering/dev/push_release` line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NE6e_TX3Q9mXnTmOKQJ:-NE6e_TX3Q9mXnTmOKQK:b-pqtahw) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L117)):*
> ```
> fi
> 
> platforms=( focal jammy )
> ```

FYI Betsy we already did the update for jammy previously and put it on s3, if we run into trouble the prior version is still stored in `push_release_v1`.
___
*[`tools/release_engineering/dev/push_release` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NE6ejx1Ekfm3kk1lcVZ:-NE6ejx29dGcaOy8O6qf:b-82as0g) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L126)):*
> ```
> # TODO(svenevs): allow command line or environment variable to set this.
> # The value for this variable is currently saved in:
> #     s3://drake-infrastructure/push_release_gpg_key.txt
> ```

FYI new file location, for review it would be worth double checking against the `scripts/push_release`.

**Review by BetsyMcPhail — COMMENTED** [review]
The current plan is to run this script as part of #18064 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18075#-:-NECW1wy6TzBumnUzxds:brpeibp)* status: LGTM missing from assignee BetsyMcPhail, missing label for release notes

**Review by BetsyMcPhail — COMMENTED** [review]
I ran this version of the script for the 1.9.0 release with no issues other than the one hardcoded `focal`.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18075#-:-NEHwrWFB2hlii8WgZ0S:bhlpsi3)* status: 2 unresolved discussions, missing label for release notes (waiting on @svenevs)

___
*[`tools/release_engineering/dev/push_release` line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NEHwZg08Au_D1sGxVvs:-NEHwZg11-_c3Ftazvj9:b-6epmug) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L169)):*
> ```
>   done
> 
>   image="robotlocomotion/drake:focal-${binary_version}"
> ```

`focal` also needs to get switched to `${platform}`
___
*[`tools/release_engineering/dev/push_release` line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NEHwiLvEx8d6oI1Cdk3:-NEHwiLvEx8d6oI1Cdk4:b-y79ws4) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L172)):*
> ```
>   tag="robotlocomotion/drake:${source_version}"
> 
>   # Tag the focal Docker image without a platform prefix them and push the tag
> ```

Remove `focal` here

**Comment by BetsyMcPhail** [comment]
*[`tools/release_engineering/dev/push_release` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NE6ejx1Ekfm3kk1lcVZ:-NEHyYvb9ydd5wGbBAhq:bunnlws) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L126)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI new file location, for review it would be worth double checking against the `scripts/push_release`.
</blockquote></details>

I moved this to AWS/secrets/push_release

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18075)* status: 2 unresolved discussions, missing label for release notes (waiting on @BetsyMcPhail)

___
*[`tools/release_engineering/dev/push_release` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NE6ejx1Ekfm3kk1lcVZ:-NEIQQt6-u0UDtP7zgyk:bap0b89) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L126)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I moved this to AWS/secrets/push_release
</blockquote></details>

OK good call, updated the comment.
___
*[`tools/release_engineering/dev/push_release` line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NEHwZg08Au_D1sGxVvs:-NEIQUGA3Ew_7NDJE7l_:b34u566) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L169)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

`focal` also needs to get switched to `${platform}`
</blockquote></details>

Done, updated.
___
*[`tools/release_engineering/dev/push_release` line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18075#-NEHwiLvEx8d6oI1Cdk3:-NEIQWbj28L5TAxninFE:b-r7x8pj) ([raw file](https://github.com/robotlocomotion/drake/blob/f9034e36cbc97cf3139eaf1c0edd24b943df0b68/tools/release_engineering/dev/push_release#L172)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Remove `focal` here
</blockquote></details>

Done, removed.

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18075)* status: missing label for release notes (waiting on @svenevs)

**Pull request merged**
