### PR TITLE
[setup] Update cloud packaging for EGL

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add ubuntu dependency on libegl1 so that it can be dlopen'd.  Document the same in the pip error message sidecar.

Remove xvfb from deepnote.  Now that Drake defaults to using EGL, we no longer need a DISPLAY in the cloud.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22197)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
At some point, I should also change this exception message to give better help (e.g., link to a troubleshooting guide):

https://github.com/RobotLocomotion/drake/blob/94109b0b3f472a648f6c0c71064fd9eb572f2a03/geometry/render_vtk/internal_make_render_window.cc#L46

I can do that in this same PR if you like, or save it for a later one?

**Review by rpoyner-tri — COMMENTED** [review]
I'm fine with a separate PR for error message improvements.
:lgtm: 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22197#-:-OBm4N0j-hZStQLZxsQw:bpzsyy1)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: once remaining nits are cleared up.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22197#-:-OC0RVUw0s8oJOs0lp5x:bvinmhz)* status: 2 unresolved discussions

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22197#-OC0R767DwyB6VrXm2Yu:-OC0R767DwyB6VrXm2Yv:b5f0wgv) (no related file):*
nit: there are remaining references to a display server in `from_source.md` and `installation.md` which may be stale.
___
*[`doc/_pages/release_playbook.md` line 260 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22197#-OC0QVYS1NTSTxk1g8Zj:-OC0QVYS1NTSTxk1g8Zk:bkuqgd6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b055328f9b42eec251ed3e964942625ef27c3ddc/doc/_pages/release_playbook.md#L260)):*
> ```Markdown
>    /opt/drake/share/drake/setup/deepnote/install_nginx
>    ```
>    In case the display server is not working later on, this might be a good place to double-check.
> ```

nit: should there still be a reference to the display server here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22197)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22197#-OC0R767DwyB6VrXm2Yu:-OC0W5-I6DIkGzXe_sXb:bne447t) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: there are remaining references to a display server in `from_source.md` and `installation.md` which may be stale.
</blockquote></details>

Good point.

I am rewriting the setup scripts and docs in #22055, so I've filed two reminders there to revisit this as part of the bigger story.
___
*[`doc/_pages/release_playbook.md` line 260 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22197#-OC0QVYS1NTSTxk1g8Zj:-OC0WHTFDjolOBABduz7:b-fzj022) ([raw file](https://github.com/RobotLocomotion/drake/blob/b055328f9b42eec251ed3e964942625ef27c3ddc/doc/_pages/release_playbook.md#L260)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: should there still be a reference to the display server here?
</blockquote></details>

Done (removed).

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22197)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

**Pull request merged**
