### PR TITLE
[wheel] manylinux 3.6 and 3.7 support dropped.

### PR DESCRIPTION
**Pull request by svenevs**
Currently supported: 3.8, 3.9.

Relates: #13391, #16929.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16973)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@mwoehlke-kitware for feature review please.  Scoped this while working on #16972.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16973#-:-N-ddOrMDwjMsHuY4FWX:b-1dnf2o)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16973#-:-N-dgQNh6_-1XdSRHCkg:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@jwnimmer-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16973#-:-N-dkWZG4tOqXwccJL4f:b-qxjhdt)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16973#-:-N-dlvzfEIB7in-rXGyp:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mwoehlke-kitware (waiting on @svenevs)

**Pull request merged**
