### PR TITLE
Update recommended Bazel version to 2.0

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12526)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review. I will update the CI images on Monday.

**Comment by jwnimmer-tri** [comment]
FYI Anzu is on 2.0.0 as of yesterday.

**Comment by jamiesnape** [comment]
Just finishing up the images now. There were a lot of Mac OS/security fixes pending install.

**Pull request merged**
