### PR TITLE
Updates Maliput's Monolane's BUILD file to use drake_cc_googletest.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5121)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

\CC: @maddog-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5121#-:-KcZpHHfWvFTzhKN2JMG:b-aww28h)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5121#-:-KcZsLoJy9NMpzatqyFB:bnfp4nl)*

**Comment by maddog-tri** [comment]
:lgtm: :gtk: :mt:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5121#-:-KcZtHM9wOdZh8Gcykig:bg4cxo2)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please.

**Pull request merged**
