### PR TITLE
drake_visualizer: Install builtin scripts

### LINKED ISSUE #7050: CI coverage of pre-built drake visualizer
Drake's CI should offer coverage of pre-built drake visualizer -- for example, that is launches without faults, that it runs for a few seconds without crashing, that it is able to locate data resources.  It is not unusual for users to experience problems running this software, so we should have CI coverage to point to that demonstrates that it works (and helps us keep regressions off of master).

Relates to #5621 as the feature to be tested in CI.

Relates to #6834 as an example of a scenario that should be tested in CI.

### LINKED ISSUE #10486: Installed (and binary release) drake-visualizer lacks useful default plugins
When we run `bazel-bin/tools/drake_visualizer`, useful plugins like `show_image` are on by default.  When a user is running from an installed copy of Drake, they are off by default (and not even in the menus as an option, IIRC).  We shouldn't have to ask a user "_Which_ visualizer copy were you running" -- they should all just work the same.  Call to action: bake in the plugins to our installed drake-visualizer, as well.

\CC @EricCousineau-TRI @jamiesnape

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Put under test, both in Bazel and install

Resolves #10486 
Resolves #7050.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13127)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
New output (both Bazel and install tree):
```
$ bazel run //tools/workspace/drake_visualizer:py/drake_visualizer_bazel_help_test
...
usage: Drake Modifications [--use_builtin_scripts SCRIPTS]

Runs Drake Visualizer with builtin scripts.

optional arguments:
  --use_builtin_scripts SCRIPTS
                        Comma-separated list of Drake's builtin scripts in
                        conjunction with Drake Visualizer. Default: all.
                        Options: all, frame, hydroelastic_contact, image,
                        point_pair_contact, time

usage: drake-visualizer [-h] [-c filename] [--matlab-host hostname]
                        [--director-config filename]
                        [--data filename [filename ...]]
                        [--script filename [filename ...]]

optional arguments:
  -h, --help            show this help message and exit
  -c filename, --bot-config filename, --config_file filename
                        Robot cfg file
  --matlab-host hostname
                        hostname to connect with external matlab server
  --director-config filename, --director_config filename
                        JSON file specifying which urdfs to use
  --data filename [filename ...]
                        data files to load at startup
  --script filename [filename ...], --startup filename [filename ...]
                        python scripts to run at startup
...
```

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Yes, I have yet to get an hour free to review and test this, but I'm disinclined to install a new top-level python module just for this fix.  There has got to be a better way that is equally testable with just as few equivalence classes in the test's domain.  I plan to play with a few options locally, and only approve the new module if I cannot find an alternative.

**Comment by jwnimmer-tri** [comment]
FYI I think the most recent push is a good approach.  I might still look into simplifying it (perhaps a follow up PR), and I still need to manually test some end-user use cases with the installed workflows, but hopefully those only end up with small tweaks.

**Comment by jwnimmer-tri** [comment]
Don't worry about my potential changes, I'll open a PR to your branch if I have any urgent ones.  Most likely it would be a follow-up, or no changes anyway.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Pull request merged**
