### PR TITLE
Mention disable compiler opt. for bazel+kcov

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5306)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@rpoyner-tri , feature-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-Kdl67kiGBG6ZyhBW2uw:bsdc7tc)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-KdlGa-Xc1G66T42uFtU:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , platform-review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-KdlGpGshxIFJOKtT_zz:bq8ci7j)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-KdlUHaBI6Tap_-9gVFe:behyqt5) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
> ```reStructuredText
> 
> Consider disabling compiler-optimization (``--copt="-O"``) to have a better and
> more precise coverage report.
> ```

On first read, `bazel.rc` for `--config=kcov` already appears to change the copts, so would already trigger a full rebuild of the test(s) in question.  If that's true, then shouldn't we add `-O` into bazel.rc automatically for the user, instead of only in the instructions?

BTW Why `-O` and not `-O1`?  (What does `-O` even do in clang?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by soonho-tri** [comment]
*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-KdlWXz0QMbMKTC_ckno:b-tdvu7t) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On first read, `bazel.rc` for `--config=kcov` already appears to change the copts, so would already trigger a full rebuild of the test(s) in question.  If that's true, then shouldn't we add `-O` into bazel.rc automatically for the user, instead of only in the instructions?

BTW Why `-O` and not `-O1`?  (What does `-O` even do in clang?)
</blockquote></details>

Oops. It's a typo of `-O0`. I'll fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-KdlX3VwH-BSgGlvl8D5:bsjyvhn) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Oops. It's a typo of `-O0`. I'll fix that.
</blockquote></details>

`-O0` will make Eigen stuff significantly slow, so I think it's better not ship `-O0` with `--config=kcov`. @rpoyner-tri , what do you think?

---

*[drake/doc/bazel.rst, line 193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlHSNJEmEE60rb-fQZ:-KdlHSNK7wyOAL-oiJAH:btpu6lt) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L193)):*
> ```reStructuredText
> ===
> 
> Q: What does ``ccache: error: Could not find compiler "gcc" in PATH`` mean?
> ```

FYI, this change is to have better rendering at https://github.com/RobotLocomotion/drake/blob/master/drake/doc/bazel.rst#faq . Github interprets `Q.` as `17.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-Kdq5unBee6wBquOW8dq:b-3mz15d)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-KdwSSNBW5WHg3oxqDZI:bo6p1ef) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`-O0` will make Eigen stuff significantly slow, so I think it's better not ship `-O0` with `--config=kcov`. @rpoyner-tri , what do you think?
</blockquote></details>

My intuition is that the common case is "run my one unit test and give me a precise report" and the case of "run a slow bank of test and give me the aggregate report" (where speed could matter) is less common, and the user should opt-in to imprecision via `--copt -O2` or whatever.

However, I haven't used this kcov config more than a half dozen times, so will mark myself resolved here, and let Rick and Soonho (who have used it more) sort it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-KdwSx_Ycj3iRiu1KLTG:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-Ke-Zzu6BbZOTTNFZtIW:bcjb4r3) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My intuition is that the common case is "run my one unit test and give me a precise report" and the case of "run a slow bank of test and give me the aggregate report" (where speed could matter) is less common, and the user should opt-in to imprecision via `--copt -O2` or whatever.

However, I haven't used this kcov config more than a half dozen times, so will mark myself resolved here, and let Rick and Soonho (who have used it more) sort it out.
</blockquote></details>

Yeah, it's probably right to make -O0 the default for --config=kcov, and adjust the documentation appropriately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by rpoyner-tri** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-Ke-a8BBA2lWw3JtAqmj:b8b79qu)*

**Comment by rpoyner-tri** [comment]
per discussion below, awaiting a slightly more ambitious patch...

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-Ke-aBeQAqk-if45OSiO:b-bq9vmu)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-Ke-bHIZk1KLD3uKwCGH:b-q64h22) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Yeah, it's probably right to make -O0 the default for --config=kcov, and adjust the documentation appropriately.
</blockquote></details>

Now we have -O0 configured by default, this documentation patch should say something different ("if you have trouble with kcov and unoptimized programs, you can turn it back on by also supplying `--copt -O2`" or so?), or maybe just go away...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-KdlUHaAFiJ9cRrZnCsL:-Ke-dBf8DGgitxQsMiP4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71eec9e0d31b7e89e96dceb725211519dabd880a/drake/doc/bazel.rst#L180)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Now we have -O0 configured by default, this documentation patch should say something different ("if you have trouble with kcov and unoptimized programs, you can turn it back on by also supplying `--copt -O2`" or so?), or maybe just go away...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306#-:-Ke-dqtNpLOCLONMOHhg:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5306)*

**Pull request merged**
