### PR TITLE
Reuse mathematical program when computing pairwise intersections between g-convex sets.

### PR DESCRIPTION
**Pull request by cohnt**
As discussed in #20700, the API to remove variables from a mathematical program allows us to reuse a mathematical program when checking many pairs of sets for intersections.

+@sadraddini for feature review, please!

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21592)

### CODE REVIEW

**Review by sadraddini — COMMENTED** [review]
Do we have a unit test where `AddPointInSetConstraints` actually adds new variables and bindings? I see all tests are with hyperrectangles, where actual auxiliary variables and bindings don't get created. Maybe try one with Minkowski sum? We want to ensure this is working as intended. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-:-O-nbXs84YX6gyExnPPh:b-czx0ad)* status: 3 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/geodesic_convexity.cc` line 288 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-O-nafQf2x2da2YN7WR4:-O-nafQf2x2da2YN7WR5:bx7gudj) ([raw file](https://github.com/RobotLocomotion/drake/blob/00502483530ebe464c9bbbd53273f2a927543943/geometry/optimization/geodesic_convexity.cc#L288)):*
> ```cpp
>   Eigen::MatrixXd Aeq(dimension, 2 * dimension);
>   // Add x + offset == y by [-I, I][x; y] == [offset]
>   Aeq.leftCols(dimension) = -Eigen::MatrixXd::Identity(dimension, dimension);
> ```

How about declaring these matrices as sparse? 
___
*[`geometry/optimization/geodesic_convexity.cc` line 362 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-O-ndAnUAsKrLqtAuFXu:-O-ndAnUAsKrLqtAuFXv:b-6g0ctt) ([raw file](https://github.com/RobotLocomotion/drake/blob/00502483530ebe464c9bbbd53273f2a927543943/geometry/optimization/geodesic_convexity.cc#L362)):*
> ```cpp
>         prog.RemoveDecisionVariable(variable);
>       }
> ```

btw how about adding `DRAKE_DEMAND(prog.num_vars() == 2)` because only `x, y` are left?  
___
*[`geometry/optimization/geodesic_convexity.cc` line 368 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-O-nbrWU3kAGUKWKrxeo:-O-nbrWU3kAGUKWKrxep:b-8jwmie) ([raw file](https://github.com/RobotLocomotion/drake/blob/00502483530ebe464c9bbbd53273f2a927543943/geometry/optimization/geodesic_convexity.cc#L368)):*
> ```cpp
>       std::tie(new_variables, new_constraints) =
>           convex_sets_A.at(i)->AddPointInSetConstraints(&prog, x);
>       std::move(new_variables.begin(), new_variables.end(),
> ```

why not just use `std::vector<T,Allocator>::insert`?

**Review by AlexandreAmice — COMMENTED** [review]
Do you have evidence that this is faster than just rebuilding the program? `RemoveDecisionVariable` requires erasing an entry from a vector, mutating **all** the entries in two maps , and mutating **all** the entries of an `Eigen::VectorXd` at every call.  

Removing a lot of constraints can be similarly expensive as it requires erasing from a vector and checking that the program's `RequiredCapabilities` are updated every single call.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-:-O-v1Lim4rJONmz7dwf3:b-dyzx70)* status: 3 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by sadraddini — COMMENTED** [review]
Need to address @AlexandreAmice 's concern

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-:-O0BK_pLCPkG4_2pMSZ4:b-w2r43f)* status: LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by cohnt — COMMENTED** [review]
Per an in-person conversation, we think this is likely to be slower. Certainly, more substantial profiling will be necessary before making this change. I'm going to close the PR for now, and we can revisit in the future if it becomes relevant.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21592#-:-O0F8KqA2n7YiRd5P5ne:bblgkgq)* status: LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers

**Pull request closed without merging**
