### PR TITLE
py systems: Expose Value[] conversion between C++ and Python LCM types

### LINKED ISSUE #7820: Provide better public API for passing between C++ LCM types and Python LCM types
I don't believe this will be too challenging. One solution (perhaps the easiest) would be to make a `lcm_type_caster<>`, and expose that as a specialization `pybind11::type_caster<>`. It would handle taking taking a C++ LCM type, serialize, and then deserialize it in Python (to avoid the need to bind the C++ LCM type in Python, and provide explicit mappings).

Items that would be nice are:
- [x] #10455 Simple working prototype for Systems framework
- ~Example of mutating a C++ LCM object from Python (esp. with a callback) - would require some extra copies and assignment, but should be manageable.~ UPDATE: This is dumb.
- ~Example of mutating a Python LCM object from C++ (esp. with a callback) - same as above, with domains reversed.~ UPDATE: This is dumb.
- [ ] Ensure C++ <-> Python via `pybind11` could be done via `py::type_caster<>`
- We also provide very explicit mechanisms for this publicly?
  - #13278 was one attempt, but a bit dicey. See discussion there.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #7820

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13278)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Closing this for now. Can reopen later.

**Comment by EricCousineau-TRI** [comment]
Per latest comment, re-opened

**Comment by jwnimmer-tri** [comment]
From #14282, I can see why we'd want the part of #7820 where a C++ message object returned from a function would convert (as part of the pybind11 instrumentation) to the corresponding python message object.  I don't yet see where type-erased (`Value<foo_message_t>`) messages would come into play, which seems like what this PR is doing.

**Comment by EricCousineau-TRI** [comment]
Aye. The underlying `py::type_caster<>` instrumentation would be same-ish as the `Value[]` approach, but maybe less noisy. Will refactor this PR.

**Comment by SeanCurtis-TRI** [comment]
@EricCousineau-TRI This has gone another six months without any apparent attention. Still worth keeping open?

**Comment by EricCousineau-TRI** [comment]
Yeah, will close for now pending tangible demand. Thanks for the ping!

**Comment by EricCousineau-TRI** [comment]
(noting that Jeremy's comment above is captured as a checkbox in #7820)

**Pull request closed without merging**
