### PR TITLE
Dev/toc error experiments

### PR DESCRIPTION
**Pull request by jonathan-owens**
This will traverse the libraries to see where the lcm types static library is being used. See Issue #2385

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2600)

### CODE REVIEW

**Comment by liangfok** [comment]
I'll go ahead and test this now.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2600#-:-KKjKndlRYKjPkZ6BMq3:1241300879)*

**Comment by liangfok** [comment]
My first attempt at building after grabbing this branch failed with the following error:

```
AILED: bot2-procman-prefix/src/bot2-procman-stamp/bot2-procman-build
cd /Users/liang/dev/drake/externals/libbot/bot2-procman/pod-build && /usr/local/Cellar/cmake/3.5.0/bin/cmake --build . && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E touch /Users/liang/dev/drake-build/externals/libbot/bot2-procman-prefix/src/bot2-procman-stamp/bot2-procman-build
Error: could not load cache
[5/16] Performing build step for 'bot2-core'
FAILED: bot2-core-prefix/src/bot2-core-stamp/bot2-core-build
cd /Users/liang/dev/drake/externals/libbot/bot2-core/pod-build && /usr/local/Cellar/cmake/3.5.0/bin/cmake --build . && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E touch /Users/liang/dev/drake-build/externals/libbot/bot2-core-prefix/src/bot2-core-stamp/bot2-core-build
Error: could not load cache
[6/16] Performing build step for 'bot2-lcm-utils'
FAILED: bot2-lcm-utils-prefix/src/bot2-lcm-utils-stamp/bot2-lcm-utils-build
cd /Users/liang/dev/drake/externals/libbot/bot2-lcm-utils/pod-build && /usr/local/Cellar/cmake/3.5.0/bin/cmake --build . && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E touch /Users/liang/dev/drake-build/externals/libbot/bot2-lcm-utils-prefix/src/bot2-lcm-utils-stamp/bot2-lcm-utils-build
Error: could not load cache
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
```

I now see that this PR's source branch appears to not include #2487 and #2567. I will thus try to use `make` with an in-source build rather than `ninja` with an out-of-source build.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2600#-:-KKjOGQYbdnFx2dkwHOa:-1298632182)*

**Comment by liangfok** [comment]
Oops. I now see the "do not review" label attached to this PR. I'll stop reviewing it now.

FTR, I was also unable to compile this branch in-source using `make`. I'm not sure what the error was b/c the root cause must have been pushed beyond my terminal's buffer. I only see: `make: *** [all] Error 2`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2600#-:-KKjT1Kidpjyczp4V0F0:-1645440371)*

**Comment by jonathan-owens** [comment]
@liangfok Thanks for giving it a shot. Strange that it does not compile. Especially because it compiles on the build servers and on mine. I would expect no changes that I made stopping it from compiling. It's simply supposed to add a new test. I'll take a look at it more later today.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@jonathan-owens Is this experiment still active?  Could the PR be closed?

**Comment by jonathan-owens** [comment]
@jwnimmer-tri Sorry about that, closed now

**Pull request closed without merging**
