### PR TITLE
[workspace] Upgrade drake_models to latest commit (fix plate_8in.gltf)

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Twin PR: https://github.com/RobotLocomotion/models/pull/67

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21442)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21442)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21442#-Ny1qwE2An5SNYQcF2CD:-Ny1qwE2An5SNYQcF2CE:basiq40) ([raw file](https://github.com/RobotLocomotion/drake/blob/08eaac50bf842f3504751cb59b98a4270a9e4d03/tools/workspace/drake_models/repository.bzl#L10)):*
> ```Starlark
>         repository = "RobotLocomotion/models",
>         commit = "01e6a611ab37002658841c37f04fd6b9d7163e2f",
>         sha256 = "7220234af6fff351b55873e021a489889aac1de0eaf4d0505889451350246a34",  # noqa
> ```

Working.

Working temporary SHA1 until the models PR https://github.com/RobotLocomotion/models/pull/67 is merged.



_Code quote:_
```Starlark
        commit = "01e6a611ab37002658841c37f04fd6b9d7163e2f",
        sha256 = "7220234af6fff351b55873e021a489889aac1de0eaf4d0505889451350246a34",  # noqa
```

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

CC: @amcastro-tri @SeanCurtis-TRI 

I'm following the instruction in https://drake.mit.edu/model_version_control.html

To test the plate model files,
```
bazel run //tools:model_visualizer -- package://drake_models/dishes/plate_8in.sdf
```
and/or
```
bazel run //tools:meldis -- --open-window &
bazel run //examples/hydroelastic/ball_plate:ball_plate_run_dynamics
```

+(release notes: fix) 

Thanks to Alejandro for reporting the problem.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21442#-:-Ny1rQfXBtFDc0Td1-be:b-grug8)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by jwnimmer-tri — COMMENTED** [review]
Seems OK so far.

+(status: single reviewer ok) 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21442#-:-Ny1ywHt-6tAqy-Ohvju:b-kc04nm)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21442)* status: LGTM missing from assignee jwnimmer-tri(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21442#-Ny1qwE2An5SNYQcF2CD:-Ny2Aj31AovhUU2PnFMU:b-3qcrtm) ([raw file](https://github.com/RobotLocomotion/drake/blob/08eaac50bf842f3504751cb59b98a4270a9e4d03/tools/workspace/drake_models/repository.bzl#L10)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Working.

Working temporary SHA1 until the models PR https://github.com/RobotLocomotion/models/pull/67 is merged.
</blockquote></details>

Done. The models PR [67](https://github.com/RobotLocomotion/models/pull/67) was merged.  Use the new SHA1.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21442#-:-Ny2BJmv0-kJN19Sc7dk:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Comment by DamrongGuoy** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-experimental-debug/7627/ failed.

@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Comment by DamrongGuoy** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-experimental-debug/7628/ also failed from the same CI buildcop issue #18726.

I'll try again:
[@drake-jenkins-bot](https://github.com/drake-jenkins-bot) linux-jammy-gcc-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
I can just force it without waiting for Jenkins.  Done.

**Comment by DamrongGuoy** [comment]
Thank you!

**Pull request merged**
