### PR TITLE
Add all_of, any_of, and none_of

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8508)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Closing #8504 

+@jwnimmer-tri for feature-review, please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-:-L9BY0IwEC_SmnjQFudh:b-fu6amo)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[common/test/drake_bool_test.cc, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9BmWBa5mLe5vYBN4Pb:-L9BmWBa5mLe5vYBN4Pc:bwcvpgt) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L1)):*
> ```cpp
> #include "drake/common/drake_bool.h"
> ```

_Meta_ For all three helpers, can you test their behavior on a zero-sized matrix?  (Possibly both `Xd`-zero or `<Rows = 0, Cols = 0>`, if redux is possibly different in the two cases.)

---

*[common/test/drake_bool_test.cc, line 372 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9Bn-sqASTrmGSpcPrl:-L9Bn-sqASTrmGSpcPrm:b-6kyffu) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L372)):*
> ```cpp
>       none_of(m_, [](const Expression& v) { return isnan(v); }).value(),
>       !isnan(x_) && !isnan(y_) && !isnan(z_) && !isnan(w_));
> }
> ```

For completeness of things users might do, could you test at least one helper (like all_of) for `Matrix<Formula>` where the predicate is simply an identity?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9BmWBa5mLe5vYBN4Pb:-L9BpEK61byMsiqLvfgd:b-6ak4bs) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ For all three helpers, can you test their behavior on a zero-sized matrix?  (Possibly both `Xd`-zero or `<Rows = 0, Cols = 0>`, if redux is possibly different in the two cases.)
</blockquote></details>

FYI, we have:
```
Assertion failed: (this->rows()>0 && this->cols()>0 && "you are using an empty matrix"), function redux, file external/eigen/Eigen/src/Core/Redux.h, line 413.
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 372 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9Bn-sqASTrmGSpcPrl:-L9Brl0tEiMvniDNMFQ5:bgwthjq) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L372)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For completeness of things users might do, could you test at least one helper (like all_of) for `Matrix<Formula>` where the predicate is simply an identity?
</blockquote></details>

FYI, Bool<Formula> is not well-defined as `decltype(Formula() < Formula())` is not defined. As a result, a user will have a compile-error if she writes `all_of(Matrix<Formula>, ...)`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 372 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9Bn-sqASTrmGSpcPrl:-L9Bs8ud4ggBnH4Ht-1u:b-9n20t7) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L372)):*
> Bool is not well-defined

-> `Bool<Formula>`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9BmWBa5mLe5vYBN4Pb:-L9Bxpm39zY-9JKClnwM:b-k4xha6) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L1)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, we have:
```
Assertion failed: (this->rows()>0 && this->cols()>0 && "you are using an empty matrix"), function redux, file external/eigen/Eigen/src/Core/Redux.h, line 413.
```
</blockquote></details>

Because `std::` flavors express results when empty, I'd expect our "overloads" to do so as well?  Which means we need to special-case zero-sized and not use redux, I think?

---

*[common/test/drake_bool_test.cc, line 372 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9Bn-sqASTrmGSpcPrl:-L9By6UF7EVHyX0XVxhN:blmhtxe) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L372)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> Bool is not well-defined

-> `Bool<Formula>`
</blockquote></details>

Possibly this is out of scope then, but perhaps the return type should be influenced by the decltype of the predicate's return value, instead of assuming binary operators?  Where does that fall on the difficulty vs value spectrum?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9BmWBa5mLe5vYBN4Pb:-L9C4PhyA88Bd8IfimwA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Because `std::` flavors express results when empty, I'd expect our "overloads" to do so as well?  Which means we need to special-case zero-sized and not use redux, I think?
</blockquote></details>

Done.

---

*[common/test/drake_bool_test.cc, line 372 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9Bn-sqASTrmGSpcPrl:-L9C4mi6-qAJuRJ3TE2W:b-yf9u8x) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L372)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Possibly this is out of scope then, but perhaps the return type should be influenced by the decltype of the predicate's return value, instead of assuming binary operators?  Where does that fall on the difficulty vs value spectrum?
</blockquote></details>

In the current implementation, the type of `all_of` is `Matrix * (T -> Bool<T>::value_type) -> Bool<T>`. I think it's more natural to ask users to write a pred of type `(T -> Bool<T>::value_type)` instead of `(T -> Bool<T>)`.

Another issue is that we need to provide more functionalities to `Bool<T>` to be a scalar type of `Eigen::Matrix`. That is, in the current implementation, I avoid to have an instance of `Eigen::Matrix<Bool<T>>`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/drake_bool_test.cc, line 372 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9Bn-sqASTrmGSpcPrl:-L9C6ADR2id-KOZwOZHX:blfdt3x) ([raw file](https://github.com/robotlocomotion/drake/blob/d59a3b4d2dc958067ec54faed0808670cd51b71e/common/test/drake_bool_test.cc#L372)):*
> That is, in the current implementation, I avoid to have an instance of Eigen::Matrix<Bool<T>>.

Just to provide more information, under the common scalar types, `all_of/any_of/none_of` functions compute instances of `Eigen::Matrix<Bool<T>::value_type>` which is either `Eigen::Matrix<bool>` or `Eigen::Matrix<Formula>`. Note that we already support both of them as a scalar type of `Eigen::Matrix`.  

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by jwnimmer-tri** [comment]
:lgtm: feature

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/drake_bool.h, line 128 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9CVkOO8_YsqJx6kjb1:-L9CVkOO8_YsqJx6kjb2:b-ad0u0m) ([raw file](https://github.com/robotlocomotion/drake/blob/179e102d062cc3dbf7b3bc3ae18445da1b1941a4/common/drake_bool.h#L128)):*
> ```objc
>         const typename Derived::Scalar&)>& pred) {
>   using T = typename Derived::Scalar;
>   if (m.rows() == 0 && m.cols() == 0) {
> ```

I think these should all be `||` not `&&`?

---

*[common/drake_bool.h, line 134 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9CXPsSAK_Vt1b8lw14:-L9CXPsU8uSx0xAlVGXn:bqph0cv) ([raw file](https://github.com/robotlocomotion/drake/blob/179e102d062cc3dbf7b3bc3ae18445da1b1941a4/common/drake_bool.h#L134)):*
> ```objc
>   return m.unaryExpr(pred).redux(
>       [](const typename Bool<T>::value_type& v1,
>          const typename Bool<T>::value_type&& v2) { return v1 && v2; });
> ```

I am not sure why all of the `v2`s have `const &&` on their type?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-:-L9CYXwj0gUWGzM14gO-:bxmhyuf)*

**Comment by soonho-tri** [comment]
+@ggould-tri for platform-review, please.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-:-L9CapqZ0F9HdU4Hd1ir:b-qfhg9t)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/drake_bool_test.cc, line 141 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508#-L9G-7WX70Og0C9PEcAt:-L9G3ddTBlHVaz6F6azZ:b-ioxi27) ([raw file](https://github.com/robotlocomotion/drake/blob/35abe121f3f0567cb8c54a50f93cac7b921ca7ba/common/test/drake_bool_test.cc#L141)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This does not agree with the code below (because it is wrong).
</blockquote></details>

Done. Thank you!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8508)*

**Pull request merged**
