### PR TITLE
tools: Move relnotes out of dev, into proper support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
It seems like this tool worked well enough in the most recent release to bless it with platform review and collaborative maintenance.

+@rpoyner-tri for feature review, please.

+@sammy-tri for platform review per schedule (tomorrow, please).  **NOTE** that in moving out of dev, this needs a *full* review, not just the changed lines.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sammy-tri)

___
*[tools/release_engineering/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgTnPI5PDNOyxEQi1G:-MOgTnPI5PDNOyxEQi1H:bremlu5) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/BUILD.bazel#L1)):*
> ```Starlark
> # -*- python -*-
> ```

(status=Discussing :white_circle:  )   Is `release_engineering` a new directory?  I do not see it in my checkout of drake master (a few days ago).

I like the name `release_engineering`!  :smile: 
___
*[tools/release_engineering/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgUmaYBZn8p3rGbeY1:-MOgUmaYBZn8p3rGbeY2:b9j9xy) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/BUILD.bazel#L6)):*
> ```Starlark
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> package(default_visibility = ["//visibility:private"])
> ```

Qucik question, what does `private` here mean?
___
*[tools/release_engineering/relnotes.py, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgUycZEe2Bq1ihrF3O:-MOgUycZEe2Bq1ihrF3P:b-67fi9p) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L2)):*
> ```Python
> """Tool to help draft doc/release_notes/*.rst entries.
> This is intended for use by Drake maintainers (only).
> ```

Any link or definition of "maintainers" ?  I'm not sure whether we can do something like https://drake.mit.edu/credits.html to list developers.

I can only admire this 292-line python script, but my limited python experience prohibits me from understanding it.  I'll have to stop here around this usage documentation.
___
*[tools/release_engineering/relnotes.py, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgYRtvChoAmt2ky4gs:-MOgYRtvChoAmt2ky4gt:b-umouo4) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L5)):*
> ```Python
> This program is only supported on Ubuntu Bionic 18.04.
> 
> The usage of this tool is outlined in the Drake release playbook
> ```

Could we add a short description of what this python script does before referring to `release_playbook.html` ?  Perhaps something like this (copied from release_playbook) ?

```
The usage of this tool is to add recent commit messages to the release notes draft
as outlined in the Drake release playbook dicument:

   https://drake.mit.edu/release_playbook.html
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 6 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sammy-tri)

___
*[tools/release_engineering/relnotes.py, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgXM7r4zdwhQGSxhVQ:-MOgXM7r4zdwhQGSxhVR:b-sj9usl) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L25)):*
> ```Python
> not need any extra permissions; the default "no checkboxes are set" is good),
> and save the plaintext hexadecimal token to that file.
> """
> ```

BTW Something I didn't do in my pass over this doc, but probably should have: add examples showing typical create and update command lines, so users don't have to guess which flags are necessary in each case.
___
*[tools/release_engineering/relnotes.py, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgZVPZCfoE73Mzdxio:-MOgZVP_6ah-UYAwCTnj:b-7ybaro) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L132)):*
> ```
> Coult
> ```
typo
___
*[tools/release_engineering/relnotes.py, line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgXi9O3Ybzkf0XtXPq:-MOgXi9PBI_SQNgi2rgR:b-t8pcsa) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L228)):*
> ```Python
>         newest_commit_inclusive=prior_sha,
>     )
>     # TODO(jwnimmer-tri) Strip out "This document is the template ..."
> ```

Can this TODO get done?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 6 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 5 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @DamrongGuoy, @jwnimmer-tri, and @sammy-tri)

___
*[tools/release_engineering/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgTnPI5PDNOyxEQi1G:-MOgawtMDmSeltk-4BBl:blseu7m) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/BUILD.bazel#L1)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

(status=Discussing :white_circle:  )   Is `release_engineering` a new directory?  I do not see it in my checkout of drake master (a few days ago).

I like the name `release_engineering`!  :smile: 
</blockquote></details>

Yup!  You can see online at https://github.com/RobotLocomotion/drake/tree/master/tools to browser.  In general, if you see a PR that's adding a BUILD.bazel file, likely indicates a new folder.

Aside: In git, folders themselves are not (cannot be) version controlled.  If a filename that's committed implies a directory structure, the directory is created.  If all files in a directory are removed from git, then git will rmdir the directory when you update.
___
*[tools/release_engineering/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgUmaYBZn8p3rGbeY1:-MOgb6ph9txN-gTuSfKp:b-ionv6m) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/BUILD.bazel#L6)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Qucik question, what does `private` here mean?
</blockquote></details>

https://docs.bazel.build/versions/master/visibility.html

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @DamrongGuoy, @rpoyner-tri, and @sammy-tri)

___
*[tools/release_engineering/relnotes.py, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgUycZEe2Bq1ihrF3O:-MOgkHJzETL3FuXkwSV-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L2)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Any link or definition of "maintainers" ?  I'm not sure whether we can do something like https://drake.mit.edu/credits.html to list developers.

I can only admire this 292-line python script, but my limited python experience prohibits me from understanding it.  I'll have to stop here around this usage documentation.
</blockquote></details>

Done.
___
*[tools/release_engineering/relnotes.py, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgYRtvChoAmt2ky4gs:-MOgkado1jYQhGHA25cW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L5)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Could we add a short description of what this python script does before referring to `release_playbook.html` ?  Perhaps something like this (copied from release_playbook) ?

```
The usage of this tool is to add recent commit messages to the release notes draft
as outlined in the Drake release playbook dicument:

   https://drake.mit.edu/release_playbook.html
```
</blockquote></details>

Done.
___
*[tools/release_engineering/relnotes.py, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgXM7r4zdwhQGSxhVQ:-MOgn-mE7YX6W6Ob0OmR:blcgmca) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L25)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW Something I didn't do in my pass over this doc, but probably should have: add examples showing typical create and update command lines, so users don't have to guess which flags are necessary in each case.
</blockquote></details>

Done (TODO).
___
*[tools/release_engineering/relnotes.py, line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgZVPZCfoE73Mzdxio:-MOgkePZDOAlypViUMdK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L132)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> Coult
> ```
typo
</blockquote></details>

Done.
___
*[tools/release_engineering/relnotes.py, line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgXi9O3Ybzkf0XtXPq:-MOgkfWJ2fE1mwPpeZXW:b-5oj) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L228)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Can this TODO get done?
</blockquote></details>

My inclination is not to do that as part of the move out of `dev`, rather instead leaving it for the next batch of priority-ordered improvements to this tool overall.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456#-:-MOh02KRCiVk-kqnk89O:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @DamrongGuoy and @sammy-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[tools/release_engineering/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgUmaYBZn8p3rGbeY1:-MOhCTY_792rEkbFS4Ms:bmkqzcm) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/BUILD.bazel#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://docs.bazel.build/versions/master/visibility.html
</blockquote></details>

Thank you!  It's access control between packages.
___
*[tools/release_engineering/relnotes.py, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgUycZEe2Bq1ihrF3O:-MOhCfAR7SGbh3vL7RAj:b-n1x46i) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you.  It's very clear now.
___
*[tools/release_engineering/relnotes.py, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOgYRtvChoAmt2ky4gs:-MOhCp7W7CWyH3Z9zIQ0:b-9755fn) ([raw file](https://github.com/robotlocomotion/drake/blob/86d2c2f41e10b4cc8792c604c3364a353e19279d/tools/release_engineering/relnotes.py#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[tools/release_engineering/relnotes.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOhL5Pt0CWPGNVS2YNF:-MOhL5PuEwcwLxnuiSHX:b-td90ir) ([raw file](https://github.com/robotlocomotion/drake/blob/72bcb3452a583de374ab099574cd8abcbc81353e/tools/release_engineering/relnotes.py#L12)):*
> ```Python
> document:
> 
>   https://drake.mit.edu/release_playbook.html
> ```

I think the mentions of `tools/dev/relnotes` in the `doc/` directory likely need updated?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[tools/release_engineering/relnotes.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOhL5Pt0CWPGNVS2YNF:-MOhaomgEufsS4tJk08D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72bcb3452a583de374ab099574cd8abcbc81353e/tools/release_engineering/relnotes.py#L12)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think the mentions of `tools/dev/relnotes` in the `doc/` directory likely need updated?
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[tools/release_engineering/relnotes.py, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14456#-MOhL5Pt0CWPGNVS2YNF:-MOhdAjb3yioi0etFzl7:bd2r6cr) ([raw file](https://github.com/robotlocomotion/drake/blob/72bcb3452a583de374ab099574cd8abcbc81353e/tools/release_engineering/relnotes.py#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think there's still one mention left in left in `doc/release_notes/template.txt`.  (I guess I could have called that out in the first place...)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14456#-:-MOhhPKX-sYDyWFLOHfr:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

**Pull request merged**
