### PR TITLE
Fix for issue #2077.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2084)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@david-german-tri first review is yours -- you've already been following this.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by rpoyner-tri** [comment]
d'oh. still needs declspec markings.

**Comment by rpoyner-tri** [comment]
patch forthcoming - don't bother reviewing yet.

**Comment by rpoyner-tri** [comment]
ok, CI success looks likely now.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2084#-:-KFGUU64yLOW8NiKKGlo:1417088721)*

**Pull request merged**
