### PR TITLE
pydrake: Add guidance for binding Clone() methods

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up to #15394

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for review / discussion, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398#-:-MebEiNvBXh5hiqkWx9J:bfdjp9o)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398#-:-Meb_czf6PgqPZUIZ3BU:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 506 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Meb_25T7b3SAYJ3bIG8:-Meb_25U--HGLYhLfHPM:b-x8lc2j) ([raw file](https://github.com/robotlocomotion/drake/blob/a6a19bbc716b85b44f43c2dfde3f89ef3aeedceb/bindings/pydrake/pydrake_doxygen.h#L506)):*
> ```objc
> `__copy__()` and `__deepcopy__()` will also be defined. (It is simplest to do
> these things together.)
> Be sure to test `copy.copy()` and `copy.deepcopy()` as well.
> ```

If we're using a helper function to implement the three related bindings, then why do we need to write three test cases, instead of just one?  Can we presume that the macro is correct, and therefore if any one of the functions works correctly, then they all do?  What is a hypothetical bug that would be caught by test statements besides the first one?

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398#-:-Mefvmb203ozeOnftzKO:btfqagw)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 506 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Meb_25T7b3SAYJ3bIG8:-Mefvbz_-6dFdGKN6qvp:b4glal3) ([raw file](https://github.com/robotlocomotion/drake/blob/a6a19bbc716b85b44f43c2dfde3f89ef3aeedceb/bindings/pydrake/pydrake_doxygen.h#L506)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If we're using a helper function to implement the three related bindings, then why do we need to write three test cases, instead of just one?  Can we presume that the macro is correct, and therefore if any one of the functions works correctly, then they all do?  What is a hypothetical bug that would be caught by test statements besides the first one?
</blockquote></details>

Done.

Concern was that test cases wouldn't fail if the macro isn't used, but I think we could just defer to manual verification, or write testing sugar if it actually becomes a problem!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 506 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Meb_25T7b3SAYJ3bIG8:-Meg0_SC297iBItzOSz6:b-wuh6dk) ([raw file](https://github.com/robotlocomotion/drake/blob/a6a19bbc716b85b44f43c2dfde3f89ef3aeedceb/bindings/pydrake/pydrake_doxygen.h#L506)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.

Concern was that test cases wouldn't fail if the macro isn't used, but I think we could just defer to manual verification, or write testing sugar if it actually becomes a problem!
</blockquote></details>

As a future enhancment, maybe we can find the best advice for testing and add it here.  I'm thinking of something along the lines of `self.assertIn("__deepcopy__", dir(dut))` -- basically, asserting that a function exists that is only ever likely to occur when the macro is used.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398#-:-MejoxteAEIy7oTeYvUe:bmxilld)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Mejo3n69_mEj7MxaOoC:-Mejo3n69_mEj7MxaOoD:b-5lyd7o) ([raw file](https://github.com/robotlocomotion/drake/blob/5f631fb7c9198b361479fb9a874e1dce5b51de9a/bindings/pydrake/pydrake_doxygen.h#L504)):*
> ```objc
> 
> If you wish to bind a `Clone()` method, please use `DefClone()` so that
> `__copy__()` and `__deepcopy__()` will also be defined. (It is simplest to do
> ```

BTW Can we get a link to a concrete example? True, one can grep for `DefClone` and links here can grow stale, but it seems a bit "nicer".

I just realized we have some example code for deprecating. But we don't have a toy class for general binding guidance. That would be a nice anchor to illustrate the various properties (and we wouldn't have to worry about changing APIs invalidating links).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Mejo3n69_mEj7MxaOoC:-MekwzFB1yDYLznGO4-X:b-aybhe3) ([raw file](https://github.com/robotlocomotion/drake/blob/5f631fb7c9198b361479fb9a874e1dce5b51de9a/bindings/pydrake/pydrake_doxygen.h#L504)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Can we get a link to a concrete example? True, one can grep for `DefClone` and links here can grow stale, but it seems a bit "nicer".

I just realized we have some example code for deprecating. But we don't have a toy class for general binding guidance. That would be a nice anchor to illustrate the various properties (and we wouldn't have to worry about changing APIs invalidating links).
</blockquote></details>

FYI Personally, I find `grep` vastly better than a contrived example, because it shows the full context and breadth of the possible uses.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/pydrake_doxygen.h, line 504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Mejo3n69_mEj7MxaOoC:-Mel42BuA9SlgciEJIgL:b-wmoc7p) ([raw file](https://github.com/robotlocomotion/drake/blob/5f631fb7c9198b361479fb9a874e1dce5b51de9a/bindings/pydrake/pydrake_doxygen.h#L504)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Personally, I find `grep` vastly better than a contrived example, because it shows the full context and breadth of the possible uses.
</blockquote></details>

Certainly, the arguments for `grep` is strong in this case. In the deprecation case, having a fixed example is better because particular deprecation mechanisms come in and out of usage and finding an example may be hard depending when you look.

But in this case, "how to bind Clone()", a small `grep` should *always* provide ample fodder.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I'm deferring to you for merge, in case you want to follow up on the non-blocking discussion here.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15398)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/pydrake_doxygen.h, line 506 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Meb_25T7b3SAYJ3bIG8:-Mf-NmAf84KkfmOdibk4:b-r6vjmm) ([raw file](https://github.com/robotlocomotion/drake/blob/a6a19bbc716b85b44f43c2dfde3f89ef3aeedceb/bindings/pydrake/pydrake_doxygen.h#L506)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As a future enhancment, maybe we can find the best advice for testing and add it here.  I'm thinking of something along the lines of `self.assertIn("__deepcopy__", dir(dut))` -- basically, asserting that a function exists that is only ever likely to occur when the macro is used.
</blockquote></details>

OK Sounds good! Will merge this for now; can add in later!
___
*[bindings/pydrake/pydrake_doxygen.h, line 504 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15398#-Mejo3n69_mEj7MxaOoC:-Mf-Nfdp7plqa00QJyxB:b6g2rfo) ([raw file](https://github.com/robotlocomotion/drake/blob/5f631fb7c9198b361479fb9a874e1dce5b51de9a/bindings/pydrake/pydrake_doxygen.h#L504)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Certainly, the arguments for `grep` is strong in this case. In the deprecation case, having a fixed example is better because particular deprecation mechanisms come in and out of usage and finding an example may be hard depending when you look.

But in this case, "how to bind Clone()", a small `grep` should *always* provide ample fodder.
</blockquote></details>

OK Yeah, will defer to `grep`.

And FTR, `git log -S` is your friend for things that come in and out of existence!

**Pull request merged**
