### PR TITLE
[tools] Replace ubuntu_only rules with linux_only rules

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14967.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20576)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Question about linting on non-linux...

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-:-NkGMYIK7y6UYJFNF1Lw:b-x6z9m6)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`tools/skylark/drake_cc.bzl` line 910 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-NkGKQCL3rLFOGvfO-fh:-NkGKQCL3rLFOGvfO-fi:b-1gf8ek) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7ef2def63d1de6d9627669c17d7382c105f4f82/tools/skylark/drake_cc.bzl#L910)):*
> ```Starlark
>     Linux, the interface_deps and deps and linkopts are nulled out. The tags
>     must have "manual" set so that the library compile is skipped on macOS.
>     Note that we do NOT null out srcs; we want the linter to always find them.
> ```

BTW As I read this, we're linting files on mac that don't get built on mac? Is this against the possibility that someday they might run on mac and we'd rather not find out then that there's a bunch of mac-only lint?

Can you elaborate on why this is so important?

Especially, because it seems to make the googletest variant so much more complex.
___
*[`tools/skylark/drake_cc.bzl` line 916 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-NkGJqLA5-uOLbRrWoAA:-NkGJqLA5-uOLbRrWoAB:bwv52e2) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7ef2def63d1de6d9627669c17d7382c105f4f82/tools/skylark/drake_cc.bzl#L916)):*
> ```Starlark
>     excluded from the installation).
>     """
>     if "manual" not in (tags or []):
> ```

BTW Given that this rule explicitly changes various flags (including arbitrarily setting `internal = True`, why not just have it automatically set the `manual` tag?

It does rather seem to clutter up the bazel file. Surely developers can be trained to understand that `linux_only` --> `manual`?

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule (tomorrow), please.  Low priority.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-:-NkGV2rt46o0vNWgNN6P:b4ubyy4)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`tools/skylark/drake_cc.bzl` line 910 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-NkGKQCL3rLFOGvfO-fh:-NkGUzY7Dvo9iSHOoMdI:b-4photm) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7ef2def63d1de6d9627669c17d7382c105f4f82/tools/skylark/drake_cc.bzl#L910)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As I read this, we're linting files on mac that don't get built on mac? Is this against the possibility that someday they might run on mac and we'd rather not find out then that there's a bunch of mac-only lint?

Can you elaborate on why this is so important?

Especially, because it seems to make the googletest variant so much more complex.
</blockquote></details>

Updated the comment to hopefully be more clear now.
___
*[`tools/skylark/drake_cc.bzl` line 916 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-NkGJqLA5-uOLbRrWoAA:-NkGP1O94-PVyMirVdfy:b-1eqjqn) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7ef2def63d1de6d9627669c17d7382c105f4f82/tools/skylark/drake_cc.bzl#L916)):*
> Surely developers can be trained to understand that `linux_only` --> `manual`?

I don't think that's true, but neither do I have much evidence either way.  Let's try it the more abbreviated way and we can find out if any confusion ensues or not.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-:-NkHnE6D7IMXftgEyXXg:bmxilld)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`tools/skylark/drake_cc.bzl` line 910 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-NkGKQCL3rLFOGvfO-fh:-NkHmvto9sGr_6ScvCCi:b-1dohpw) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7ef2def63d1de6d9627669c17d7382c105f4f82/tools/skylark/drake_cc.bzl#L910)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Updated the comment to hopefully be more clear now.
</blockquote></details>

Yes.  Very.
___
*[`tools/skylark/drake_cc.bzl` line 916 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-NkGJqLA5-uOLbRrWoAA:-NkHn0807QaKaHzTgQFe:b-mzo39f) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7ef2def63d1de6d9627669c17d7382c105f4f82/tools/skylark/drake_cc.bzl#L916)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Surely developers can be trained to understand that `linux_only` --> `manual`?

I don't think that's true, but neither do I have much evidence either way.  Let's try it the more abbreviated way and we can find out if any confusion ensues or not.
</blockquote></details>

:)

I was willing to bet either way on whether they were more likely to forget the manual tag or to be confused about it not making CI angry.  :)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20576#-:-NkMBOgE7eN99PwFWBwm:bzus18)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Pull request merged**
