### PR TITLE
Fix lcmLogger link error on Windows

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
See also 849e7dc2205a, which fixed the same issue for a different binary. This should fix the CI failure on the Windows matlab build (https://drake-jenkins.csail.mit.edu/job/windows-msvc-ninja-32-continuous-matlab/148/).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2698)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Experimentals:

- https://drake-jenkins.csail.mit.edu/view/Windows/job/windows-msvc-32-experimental-matlab/12/
- https://drake-jenkins.csail.mit.edu/view/Windows/job/windows-msvc-32-experimental-matlab-open-source/2/

**Comment by mwoehlke-kitware** [comment]
...although, when I say "fix", I mean "make no less broken than the other MSVC builds"... (still investigating that; can't reproduce locally)

**Comment by jwnimmer-tri** [comment]
:lgtm:, though I wonder if there isn't a more central place in Drake to get `ws2_32` into all of the LCM-related linker commands.  But this is good enough for now.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2698#-:-KLS8Y52AsYaDFAaVGLO:-207227976)*

**Comment by mwoehlke-kitware** [comment]
> I wonder if there isn't a more central place in Drake to get `ws2_32` into all of the LCM-related linker commands

See comments in #2582 re: the `threads` (pseudo-)library. *Most* LCM users don't need to link this library directly; the two that do are using `FD_ISSET` in *their own* `.cpp` files.

The threads case was borderline, as the "user" does actually "come from" drakeLCMSystem. In this case, lcmLogger is directly using WinSock2; IMHO lcmLogger should therefore be the thing linking to what it uses.

**Comment by jwnimmer-tri** [comment]
That's fine.  Personally, I'd choose a slight bit of overly-broad linking on a crufty platform over lurking post-merge build breaks, but I can appreciate the other side of the debate as well.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2698#-:-KLSC-fBCHBSnSNV2OqX:2131047294)*

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware It looks like the experimentals are done, and have improved in that they lack the `FD_ISSET` errors and only have the lcmt header errors.  Do you agree?  If so, you can merge this PR.

**Pull request merged**
