### PR TITLE
Fix reference-argument violations in Eval methods in constraint/cost classes

### LINKED ISSUE #9069: Fix reference-argument violations in DoEval methods in constraint/cost classes
From https://github.com/robotlocomotion/drake/pull/9056#issuecomment-400768578

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #9069

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9074)

### CODE REVIEW

**Comment by soonho-tri** [comment]
This PR changes the signatures of `EvaluatorBase::{Eval,DoEval}` methods to take a pointer to `y` instead of a non-const reference of `y`. For exmaple:

```c++
  void Eval(const Eigen::Ref<const Eigen::VectorXd>& x,
            Eigen::VectorXd* y) const {
```

/cc @hongkai-dai and @RussTedrake.
/cc @mposa @kuindersma as this PR might affect your code.

**Comment by soonho-tri** [comment]
+@hongkai-dai for feature-review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9074#-:-LG6YAbB6m7W3BwpUu-w:bo8rt36)*

**Comment by soonho-tri** [comment]
+@ggould-tri for platform-review, please.

---

Review status: all discussions resolved, LGTM missing from assignee hongkai-dai, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9074#-:-LG6YHib6mASz8sJWutO:b-qfhg9t)*

**Comment by hongkai-dai** [comment]
@avalenzu this could affect the B-spline kinematic trajectory optimization as well.

:lgtm: Thanks Soonho for doing this.

---

Reviewed 35 of 35 files at r1.
Review status: all discussions resolved, LGTM missing from assignee ggould-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9074#-:-LG6_l-mAWXpru5MULQq:bcwnvty)*

**Comment by ggould-tri** [comment]
Yaaaaay! :lgtm:

---

Reviewed 35 of 35 files at r1.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9074#-:-LG6nQJ307ENcqkpnAr7:b-3b7dpl)*

**Pull request merged**
