### PR TITLE
Compute monomial basis with the degree for each variable <= 1

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

This will be used in our C_IRIS code.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222#-:-NFlYXKM23AZ_5CkmuVi:b-dn0iu1)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Some linting and pycode errors and a few small comments.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222#-:-NFot9TN570Vy2Z3CF9N:bpk868l)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`common/symbolic/monomial_util.cc` line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFopdGD5HQu6Sk1ZlOo:-NFopdGD5HQu6Sk1ZlOp:b-f58fhi) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/monomial_util.cc#L42)):*
> ```cpp
>   } else {
>     // First generate the monomials using all the variables x[start + 1] ...
>     // x[t.size() - 1]
> ```

nit: I believe you want `x.size()`



_Code quote:_
```cpp
t.size() - 1
```
___
*[`common/symbolic/monomial_util.cc` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFopgwmC88fBGFQddtY:-NFopgwmC88fBGFQddtZ:b-wofma5) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/monomial_util.cc#L47)):*
> ```cpp
>     // Construct the monomial x[start].
>     const Monomial x_start(x[start], 1);
>     // Multiply t_start to each monomial already in monomial_set, and append the
> ```

nit: I believe you want `x_start`



_Code quote:_
```cpp
t_start
```
___
*[`common/symbolic/test/monomial_util_test.cc` line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFoqUUGBXgbGuTsVc14:-NFoqUUGBXgbGuTsVc15:bfn5dmv) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L13)):*
> ```cpp
>   // First compute the unsorted vector of monomial basis.
>   const auto basis_unsort = CalcMonomialBasisOrderUpToOne(t, false);
>   const int basis_size_expected = 1 << static_cast<int>(t.size());
> ```

nit: I personally find this type of bit shit operator hard to read. Is it that much slower to use `static_cast<int>(std::pow(2, static_cast<int>(t.size()))`.

Its more casting so maybe it isn't easier to read.
___
*[`common/symbolic/test/monomial_util_test.cc` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NForcZm24CTiohJFDca:-NForcZm24CTiohJFDcb:b-h81hgk) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L23)):*
> ```cpp
>     basis_set.insert(basis_unsort(i));
>   }
>   EXPECT_EQ(basis_set.size(), basis_size_expected);
> ```

It took me a while to read this test. As I understand, you construct basis_set to be sure that there are no repeated elements in basis_unsort? If this is correct I think it would be helpful to document what you are testing here.
___
*[`common/symbolic/test/monomial_util_test.cc` line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFosGin2PjiwRMggIVb:-NFosGin2PjiwRMggIVc:b-jtk25b) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L29)):*
> ```cpp
>   EXPECT_EQ(basis_sorted.rows(), basis_size_expected);
>   for (int i = 0; i < basis_sorted.rows(); ++i) {
>     EXPECT_GT(basis_set.count(basis_sorted(i)), 0);
> ```

Shouldn't this be exactly 1? If so wouldn't it be better to test for the equality?
___
*[`common/symbolic/test/monomial_util_test.cc` line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFosYA33yd33RMb9i1L:-NFosYA33yd33RMb9i1M:b-quhayp) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L46)):*
> ```cpp
> };
> 
> TEST_F(CalcMonomialBasisTest, CalcMonomialBasisOrderUpToOne) {
> ```

For peace of mind, it may be a good idea to manually check the output of `CalcMonomialBasisOrderUpToOne` i.e. 
```EXPECT_EQ(CalcMonomialBasisOrderUpToOne(drake::symbolic::Variables({t1_, t2_}), true), #the equivalent vector)```
___
*[`bindings/pydrake/test/symbolic_test.py` line 1156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFot4ZgDGig8Q1RWJjI:-NFot4Zh89fNkBsORf_d:bn16vwp) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/bindings/pydrake/test/symbolic_test.py#L1156)):*
> ```Python
> 
>     def test_calc_monomial_basis_order_up_to_one(self):
>         basis = sym.CalcMonomialBasisOrderUpToOne(sym.Variables([x, y, z]))
> ```

Add the keyword function invocation as well to this test.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice)

___
*[`common/symbolic/test/monomial_util_test.cc` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NForcZm24CTiohJFDca:-NFqJWYE3tPa5dnW1dgC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L23)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

It took me a while to read this test. As I understand, you construct basis_set to be sure that there are no repeated elements in basis_unsort? If this is correct I think it would be helpful to document what you are testing here.
</blockquote></details>

Done.
___
*[`common/symbolic/test/monomial_util_test.cc` line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFosGin2PjiwRMggIVb:-NFqJodrCeA4s9UBwtyB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L29)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Shouldn't this be exactly 1? If so wouldn't it be better to test for the equality?
</blockquote></details>

Done.
___
*[`common/symbolic/test/monomial_util_test.cc` line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFosYA33yd33RMb9i1L:-NFqMI_AAteFzo3-eaAg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/common/symbolic/test/monomial_util_test.cc#L46)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

For peace of mind, it may be a good idea to manually check the output of `CalcMonomialBasisOrderUpToOne` i.e. 
```EXPECT_EQ(CalcMonomialBasisOrderUpToOne(drake::symbolic::Variables({t1_, t2_}), true), #the equivalent vector)```
</blockquote></details>

Done.
___
*[`bindings/pydrake/test/symbolic_test.py` line 1156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFot4ZgDGig8Q1RWJjI:-NFqMJjq34N6ICsy7XJn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/096cb6c9267a3ff8b151280ea38519826e2c13de/bindings/pydrake/test/symbolic_test.py#L1156)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Add the keyword function invocation as well to this test.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222#-:-NFt7srg4wVZTHNiQpnX:b-3lhrgq)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222#-:-NFtQRSq9xX2MCROC3re:b-cxwtpw)* status: 6 unresolved discussions (waiting on @hongkai-dai)

___
*[`common/symbolic/monomial_util.h` line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtAXNL51HQDtKwRhEC:-NFtAPJi5g6WuoXtxNzq:b-e7t84k) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.h#L3)):*
> ```objc
> #pragma once
> 
> #include <algorithm>
> ```

BTW, I believe the two new includes can be added to the .cc file instead.
___
*[`common/symbolic/monomial_util.cc` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtAgeK3roOCszPHQVg:-NFtAgeK3roOCszPHQVh:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.cc#L26)):*
> ```cpp
> 
> namespace {
> // Generate all the monomials with degree up to 1 for each variable, for all the
> ```

nit



_Suggestion:_
```cpp
Generates
```
___
*[`common/symbolic/monomial_util.cc` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtNu2h6YrpO5QADzsy:-NFtNu2h6YrpO5QADzsz:b-35ij3v) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.cc#L31)):*
> ```cpp
> void CalcMonomialBasisOrderUpToOneHelper(
>     const std::vector<Variable>& x, int start,
>     std::vector<Monomial>* monomial_basis) {
> ```

BTW probably better to clear the `monomial_basis` upon entry just to be safe?
___
*[`common/symbolic/monomial_util.cc` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtAt2_08Lyvev4f4PL:-NFtAt2_08Lyvev4f4PM:bykax4e) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.cc#L33)):*
nit, this shouldn't be a `DRAKE_UNREACHABLE()`. See its documentation:

> /// Silences a "no return value" compiler warning by calling a function that
/// always raises an exception or aborts (i.e., a function marked noreturn).
/// Only use this macro at a point where (1) a point in the code is truly
/// unreachable, (2) the fact that it's unreachable is knowable from only
/// reading the function itself (and not, e.g., some larger design invariant),
/// and (3) there is a compiler warning if this macro were removed.  The most
/// common valid use is with a switch-case-return block where all cases are
/// accounted for but the enclosing function is supposed to return a value.  Do
/// *not* use this macro as a "logic error" assertion; it should *only* be used
/// to silence false positive warnings.  When in doubt, throw an exception
/// manually instead of using this macro.
___
*[`common/symbolic/monomial_util.cc` line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtBweN3hccP13zgW9_:-NFtBweN3hccP13zgW9a:bvz2kvv) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.cc#L38)):*
> ```cpp
>     // itself.
>     monomial_basis->emplace_back();
>     monomial_basis->emplace_back(x[start], 1);
> ```

nit, this is a segfault when `x` is empty and start == -1. We should probably clean up the predicate and and DRAKE_DEMAND guards a little bit.
___
*[`common/symbolic/test/monomial_util_test.cc` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtOsspEeBe-b_8UI4C:-NFtOsspEeBe-b_8UI4D:b-47s5aw) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/test/monomial_util_test.cc#L11)):*
> ```cpp
> void CheckCalcMonomialBasisOrderUpToOne(const drake::symbolic::Variables& t) {
>   // First compute the unsorted vector of monomial basis.
>   const auto basis_unsort = CalcMonomialBasisOrderUpToOne(t, false);
> ```

nit s/basis_unsort/basis_unsorted.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`common/symbolic/monomial_util.cc` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtNu2h6YrpO5QADzsy:-NFtpQPl5ZNw2UIroSDo:b3l1rgg) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.cc#L31)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW probably better to clear the `monomial_basis` upon entry just to be safe?
</blockquote></details>

We do not want to clear `monomial_basis` upon entry. It holds all the monomials in the recursive call. I modified the documentation to make it clear.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18222)* status: :shipit: complete! all discussions resolved, LGTM from assignees AlexandreAmice,xuchenhan-tri(platform) (waiting on @hongkai-dai)

___
*[`common/symbolic/monomial_util.cc` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18222#-NFtNu2h6YrpO5QADzsy:-NFtsKfw9Ravy11RjOdM:bat734w) ([raw file](https://github.com/robotlocomotion/drake/blob/04255e3deb7f6a4309eed6808cb8d61df443dac0/common/symbolic/monomial_util.cc#L31)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We do not want to clear `monomial_basis` upon entry. It holds all the monomials in the recursive call. I modified the documentation to make it clear.
</blockquote></details>

Ah, my bad, that is actually pretty obvious. Retracted.

**Pull request merged**
