### PR TITLE
Updated Ubuntu install instructions to ensure the right compiler is selected.

### PR DESCRIPTION
**Pull request by liangfok**
I believe this is necessary since I recently encountered a user of Drake who failed to compile Drake on Ubuntu 14.04 because he didn't realize he needed to specify a different compiler when running `make options`.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2500)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Updated Ubuntu install instructions to ensure the right compiler is selected\.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-:-KJGVxAwPRSdUFmS8Ixq:163640229)*

**Comment by jwnimmer-tri** [comment]
Only 12 lines higher up in the document (fewer in HTML form), the environment setting is already well-documented.

By adding the reminder here, we'd also need to commit to sprinkling the reminder in other places, which is what we used to have in this document, but which the most recent PR rewrite here specifically avoided.  Exporting the variable in the environment (as documented on master already) may be the most reliable way for careless users to avoid getting burned.  Ny adding a one-time override to just this one `make options` invocation, we leave the door open to users forgetting to keep the environment variable set for every single Drake make invocation forever more.

Rather than trying to perfect a document that someone is bound to misinterpret no matter what we do, how about we just improve the build system?  Either give the user a clearer message (with a link to this HTML doc) if they make a mistake, and/or even better automatically default to `g++-4.9` when building on trusty, so that no special envionment variables need to be crafted.

At that point, we can even put it under test coverage -- jenkins' overrides for CC/CXX/etc could be dropped, and we'd let the "CMake does the right thing by default" be covered by continuous integration -- much better than trying to keep the docs in working order.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jwnimmer-tri for both levels of review please
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-:-KJGcDn5fznfVLwoQxRn:-1789668226)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500)*

**Comment by liangfok** [comment]
OK it turns out the user I'm working with was unable to compile drake even with the environment variable set. I will consult with them f2f and get back to this issue.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Only 12 lines higher up in the document (fewer in HTML form), the environment setting is already well-documented.
> 
> By adding the reminder here, we'd also need to commit to sprinkling the reminder in other places, which is what we used to have in this document, but which the most recent PR rewrite here specifically avoided.  Exporting the variable in the environment (as documented on master already) may be the most reliable way for careless users to avoid getting burned.  Ny adding a one-time override to just this one `make options` invocation, we leave the door open to users forgetting to keep the environment variable set for every single Drake make invocation forever more.
> 
> Rather than trying to perfect a document that someone is bound to misinterpret no matter what we do, how about we just improve the build system?  Either give the user a clearer message (with a link to this HTML doc) if they make a mistake, and/or even better automatically default to `g++-4.9` when building on trusty, so that no special envionment variables need to be crafted.
> 
> At that point, we can even put it under test coverage -- jenkins' overrides for CC/CXX/etc could be dropped, and we'd let the "CMake does the right thing by default" be covered by continuous integration -- much better than trying to keep the docs in working order.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-:-KJGgjyBarXd5FaqoECp:476865746)*

**Comment by liangfok** [comment]
I've updated the documentation based on end user's confusion that I witnesse

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK it turns out the user I'm working with was unable to compile drake even with the environment variable set. I will consult with them f2f and get back to this issue.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-:-KJI50t3JPR5O9WK3hXZ:169151370)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/ubuntu.rst, line 19 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-KJI8K4e5siqz9JrL4A3:-KJI8K4e5siqz9JrL4A4:1087421306) ([raw file](https://github.com/robotlocomotion/drake/blob/05dd9c0d5faefda9baa10528e4fdc6f3d14a71cb/drake/doc/ubuntu.rst#L19)):*
> ```reStructuredText
> 
> A compiler supporting C++11 or higher is required. The installation process
> differs depending on which version of Ubuntu you’re using.
> ```

BTW The prior author of this document carefully avoided second-person pronouns, and this PR puts many of them back.  I deeply _do not care at all_ about which phrasing is used, but thought I'd at least point it out to double-check.

If you prefer this phrasing, consider changing the `one` pronoun down below to `you` for consistency?

---

*[drake/doc/ubuntu.rst, line 121 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-KJI9Mi1SuDkddd75Jrr:-KJI9Mi1SuDkddd75Jrs:-1240392770) ([raw file](https://github.com/robotlocomotion/drake/blob/05dd9c0d5faefda9baa10528e4fdc6f3d14a71cb/drake/doc/ubuntu.rst#L121)):*
> ```reStructuredText
>     export PATH=/path/to/cmake-binary/bin
> 
> For more information, see :ref:`these instructions <cmake_on_older_ubuntu_versions>`.
> ```

Now that the doc up above tells the user a specific way to do this, I wonder if it's worth tweaking this section somehow to make it clear that _this_ export has already been accomplished (but the CC/CXX ones were not yet).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 19 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-KJI8K4e5siqz9JrL4A3:-KJIMzCfiLRCBcLG1tD6:-754491981) ([raw file](https://github.com/robotlocomotion/drake/blob/05dd9c0d5faefda9baa10528e4fdc6f3d14a71cb/drake/doc/ubuntu.rst#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW The prior author of this document carefully avoided second-person pronouns, and this PR puts many of them back.  I deeply _do not care at all_ about which phrasing is used, but thought I'd at least point it out to double-check.
> 
> If you prefer this phrasing, consider changing the `one` pronoun down below to `you` for consistency?
</details>
+@bradking since I believe he's the previous author

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/ubuntu.rst, line 19 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-KJI8K4e5siqz9JrL4A3:-KJId3wMmhuSQEdSqz6H:83905819) ([raw file](https://github.com/robotlocomotion/drake/blob/05dd9c0d5faefda9baa10528e4fdc6f3d14a71cb/drake/doc/ubuntu.rst#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@bradking since I believe he's the previous author
</details>
I removed all `you` and `one` pronouns from this file.

---

*[drake/doc/ubuntu.rst, line 121 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-KJI9Mi1SuDkddd75Jrr:-KJIfcEysVg5CeUe410U:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/05dd9c0d5faefda9baa10528e4fdc6f3d14a71cb/drake/doc/ubuntu.rst#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Now that the doc up above tells the user a specific way to do this, I wonder if it's worth tweaking this section somehow to make it clear that _this_ export has already been accomplished (but the CC/CXX ones were not yet).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500)*

**Comment by jwnimmer-tri** [comment]
Wow, it was even more of a pronoun / voice mess that I'd even realized.  Glad to have it consistent now.

:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I've updated the documentation based on end user's confusion that I witnesse
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-:-KJIgM5_SrSPdLKuav0Q:-1898204090)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500)*

**Comment by bradking** [comment]
:lgtm: 

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Wow, it was even more of a pronoun / voice mess that I'd even realized.  Glad to have it consistent now.
> 
> :lgtm:
</details>


---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2500#-:-KJLBi4MKd1AXVQm4VjB:980077423)*

**Pull request merged**
