### PR TITLE
Fix Segmentation Fault in GcsTrajectoryOptimization::AddRegions

### PR DESCRIPTION
**Pull request by cohnt**
If the user manually specifies the edges between regions and provides an index which is out-of-range, GcsTrajectoryOptimization segfaults. This PR adds a test that reveals the problem, and switches to indexing with `.at(...)` to prevent the segmentation fault.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-:-O0jwDsp8AuNANDxh11P:bmxilld)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-O0jx9GR1Rz38NY51o03:-O0jx9GR1Rz38NY51o04:bgiu8ye) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0007a680304523857407ce53fd3bd15b24bea67/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L281)):*
> ```cpp
>   for (int idx = 0; idx < ssize(edges_between_regions); ++idx) {
>     // Add edge.
>     Vertex* u = vertices_.at(edges_between_regions[idx].first);
> ```

nit: I think you need to modify the documentation on `GcsTrajectoryOptimization::AddRegions()` to indicate the required relationship between the vertices indexed by the edges and the number of regions given (with the promise of `@throw` if they aren't compatible).

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature review.

+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-:-O0jxeYLEMHfkRsz3dtx:b-4g52eb)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-O0jx9GR1Rz38NY51o03:-O0jzYLk7zWOnWNvbHUb:b-fk16dd) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0007a680304523857407ce53fd3bd15b24bea67/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L281)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I think you need to modify the documentation on `GcsTrajectoryOptimization::AddRegions()` to indicate the required relationship between the vertices indexed by the edges and the number of regions given (with the promise of `@throw` if they aren't compatible).
</blockquote></details>

Like so?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 499 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-O0kA4fT6DU_hzblzNn4:-O0kA4fT6DU_hzblzNn5:bgy26gc) ([raw file](https://github.com/RobotLocomotion/drake/blob/2287f39b2dbbbf9476c2fb0c48313b27519dd30a/planning/trajectory_optimization/gcs_trajectory_optimization.h#L499)):*
> ```objc
>   vector. For each pair representing an edge between two regions, an edge is
>   added within the subgraph. Note that the edges are directed so (i,j) will only
>   add an edge from region i to region j. Throws if any index is outside of the
> ```

nit: The typical spelling would be of the form:


```c++
/* ...

@throws std::exception if any index referenced in `edges_between_regions` is
outside the range [0, ssize(regions)).
*/
```
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 281 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-O0jx9GR1Rz38NY51o03:-O0kA1C64U_ikXD5iI-a:b3h2nhz) ([raw file](https://github.com/RobotLocomotion/drake/blob/f0007a680304523857407ce53fd3bd15b24bea67/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L281)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Like so?
</blockquote></details>

Almost...see note above.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 499 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-O0kA4fT6DU_hzblzNn4:-O0kCQbVDBQphHn2XNQs:b-xsa4m7) ([raw file](https://github.com/RobotLocomotion/drake/blob/2287f39b2dbbbf9476c2fb0c48313b27519dd30a/planning/trajectory_optimization/gcs_trajectory_optimization.h#L499)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The typical spelling would be of the form:


```c++
/* ...

@throws std::exception if any index referenced in `edges_between_regions` is
outside the range [0, ssize(regions)).
*/
```
</blockquote></details>

Done.

I put it at the end of the docstring, if that's okay?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 499 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-O0kA4fT6DU_hzblzNn4:-O0kJvN32OjpBHJp1bpE:b-qn5lay) ([raw file](https://github.com/RobotLocomotion/drake/blob/2287f39b2dbbbf9476c2fb0c48313b27519dd30a/planning/trajectory_optimization/gcs_trajectory_optimization.h#L499)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Done.

I put it at the end of the docstring, if that's okay?
</blockquote></details>

Perfect.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21658#-:-O0kw61l6k0N85bwD8nC:b8qx53o)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request merged**
