### PR TITLE
Updated unit testing instructions and location of Drake's build directory.

### LINKED ISSUE #2741: From source instructions: de-emphasize ninja option by moving it after make
Reasoning: ninja doesn't support Gurobi and is hence not as full-featured yet as the more mature make build.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #2741, #2728, and #2706.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2734)

### CODE REVIEW

**Comment by liangfok** [comment]
Between now and Tuesday: +@russtedrake for both levels of review.
From Wednesday onwards: +@jwnimmer-tri for both levels of review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2734#-:-KLkwNP4YbU380xZWR1N:855033019)*

**Comment by RussTedrake** [comment]
:lgtm: .  thanks!

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2734#-:-KLuYF1DQlOCD2RqhelW:-1072841031)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Russ has taken this one, so I'm un-assigning myself.

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2734#-:-KLzlS_a4RtLhhSqOaYc:1417088721)*

**Pull request merged**
