### PR TITLE
Fix autodiff_overloads-related build errors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This starts by moving autodiff_overloads.h from math to common.  Scalartypes should live in common, and be grouped by scalartype.  The overloaded operators that are absent from Eigen are a required part of the autodiff scalartype.

Second, this adds an include for autodiff_overloads to anywhere that instantiates Drake template using AutoDiffXd.  This is required to ensure that the correct overloads are always used when implicit instantiation happens (because many of Drake's classes place their code in the header file, so may be instantiated at any moment).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4101)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.
I'll seek feature review of the Bazel bits in a moment.

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4101#-:-KWDmc5l7QA8s4x1Xsnu:b-ny6wg7)*

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri for bazel changes, at least.

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4101#-:-KWDnWLq2SL7CMQaW9KY:b5gy4jz)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4101#-:-KWDoEVUgvjVDwOH6tZd:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/expmap.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4101#-KWE2mmOuHB3rqJrwCHO:-KWE2mmPr4RvW_ZaOK0U:b-6pre4q) ([raw file](https://github.com/robotlocomotion/drake/blob/6a1602f5da224704b8f3923a1aee7d7ca6788eec/drake/math/expmap.h#L13)):*
> ```objc
> #include "drake/math/autodiff.h"
> #include "drake/math/autodiff_gradient.h"
> #include "drake/common/autodiff_overloads.h"
> ```

Include sort order?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4101)*

**Comment by jwnimmer-tri** [comment]
Review status: 33 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/expmap.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4101#-KWE2mmOuHB3rqJrwCHO:-KWEB6pMJJaDuhHkvmty:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a1602f5da224704b8f3923a1aee7d7ca6788eec/drake/math/expmap.h#L13)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Include sort order?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4101)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r2.
Review status: 34 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4101#-:-KWEUQL39KB33m9wTnlR:bnfp4nl)*

**Pull request merged**
