### PR TITLE
Improve RigidTransform unit test

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
Slight modifications to function.
Enhanced documentation to test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849#-:-NBO5R01ATa-teNIYZVa:btdm35i)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @mitiguy and @sherm1)

___
*[`math/rigid_transform.h` line 530 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17849#-NBKjSwn4NguBEURcBo1:-NBKjSwn4NguBEURcBo2:b-vz1gv3) ([raw file](https://github.com/robotlocomotion/drake/blob/c1dd2f383c9e9c5dfc0ff762a78c3618db4aa24e/math/rigid_transform.h#L530)):*
> ```objc
>     Vector4<T> vec_A;
>     vec_A.head(3) = R_AB_ * vec_B.head(3);
>     if ((vec_A(3) = vec_B(3)) == 1) {
> ```

Could you given more context for what sense this change is an "improvement"?

Aside from the unit test rewrite, I'm less convinced about the header file change.

Doing an assignment within the predicate clause of an `if`-test is an acute readability hurdle (at best), so the header change is not strictly a _readability_ or _clarity_ improvement.

If this is supposed to be a performance improvement, could you share the benchmarking results?  It's not obvious from first principles that a non-`[[noreturn]]` branch with an addition is cheaper than an unconditional multiply-accumulate.  [Here's the godbolt disassembly](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIAHKQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BzmAMzByN5YANQmm27YeMCMAPQexJhH2CYaAIIPj14pRvun534gAGqVRGIm3QRysTzewWAnzOjBAfwBJEkIM2YOeTxMAFYrFiGCRMAQVgxMQAREn7ABuqDw6H2oVQACV8YSIGgGBN9v8HIiQWYAGwUyoAfQs81BLxeuyYCgU%2BwsdUOAHZUfsEl4IrQ8MgQC99hyEUCaagEtEmICAFQsgTszmA4Hmfnk4XzfasiZi9EK0ko8VPSXS/YAMVQqEVytV6s12qeupt3JVXlotEFNwAjl5MBNLWyCHqucQkfaBcgnS6rQR3Y8Y/qkfsWFKCNEs9bqzyHUKRaXsxWVcQ8OTTewdbL5fTBY8LILu7nbTSEmPUBZUGPJ96PV7US9Y/maUHUHDVYnk5g0xmCE2c1uC3yiyXXTmTEqh5eaeShc9V5Wb48AHQITBMdAIE2Z0jmJfZR3HQV9jNG8LF/f9AOAqc8CofYoFfYtHiAkDNjAjDhWwnCvTArgQMfaNdS/eCAOww5LFAlV50XZcpwfMC2iUfYULQ/CLFosAwAYjQyOVSi6UZAliAYCBeNFD9dTYocbkkhgvwrRT0SeZ9A2DOE6wmRs72nblC1kzt2QfUTuJk9taNAhiuEVNwHzcWC7NwoSRKHKs8xrfD31E3V/OoxCiLQudHgXJdHigmDeMIuiLDQiCJ2g2CQsIqcgrfdy8NspD5Mo5TCTUwq2P2DjMFDbzaQZJkpJs4sRVYz1xU9DhFloTgMV4PwOC0Ug9w4Zz6MsfYFGWVYqq2HhSAITQOsWABrEBJC4b8FT5DRYjMABOSQzE2BUyniLqOEkXqFsGzheAUEANDmhbFjgWAkDQFgEjoaJyEod7PvoGJgF2jE%2BDoBtiDuiAIiuiJgjqABPThZvethBAAeQYWhEf63gsDrIxxBx0h8BuKpXzuonMFUSovAbJHeGCBszoGjUImIBGPCwem5t7Fh6cWKgDGABRfjwTAAHc0eNPrZv4QQRDEdgpBkQRFBUdQid0FoDCMFBrGsfQ8AiO7YGYNgQEwGEGFIV8Yg4TZNl2xbBoSDoKYAWndiZkWJUxRosLgFX2d20bMYPiVCYlsAsOQAHFbraAE0hcBh3E8Jp/FT3oihKbJklSARRmaRJ846bP%2BlKVp2mqSYi70CoqgELp6nL2ZK4mbo6/GSZW9z0ilhWNY9AIG51h4TrusuomhtUWJeXd3lJH2YBkGQfZdu/DE0JGqxLFIT58EBOjNhafYPA%2Br7iGP0jeHmnH5mWkAju/YHdrMDQNEO3beX22JTs4C6pA%2BZcA/qQPqA0hq3Xuo9e%2BpAXqIBAMsAgqoCA/UtBfAGoRWDrFnvPReLodZQi4GYb8GhvyzUwIfEg1I9By2EKIcQys6FqzUFdLWpBxbswSPzfQk8wFXSGmjWmKD9ioFQrgheS8V5rw3lvCA59/rRGvvMW%2BT1Fh/gAgMCAj937fhPpIY6vJYiB12g7PkvDzpTwgTdWw0C75aAfhYswVjeCQJgQ4xYtsUjOEkEAA) for the two cases, for reference.  I think it's _plausible_ that this is faster, but that remains to be demonstrated.

**Review by sherm1 — COMMENTED** [review]
Updated tests look good. Feature :lgtm: pending revert of the code change (or data supporting it).

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849#-:-NBObHr9ExdmWwf_Jmd9:b-z93jwf)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`math/rigid_transform.h` line 530 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17849#-NBKjSwn4NguBEURcBo1:-NBO_Q09EseLYVaJtSA7:b2x5ybf) ([raw file](https://github.com/robotlocomotion/drake/blob/c1dd2f383c9e9c5dfc0ff762a78c3618db4aa24e/math/rigid_transform.h#L530)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Could you given more context for what sense this change is an "improvement"?

Aside from the unit test rewrite, I'm less convinced about the header file change.

Doing an assignment within the predicate clause of an `if`-test is an acute readability hurdle (at best), so the header change is not strictly a _readability_ or _clarity_ improvement.

If this is supposed to be a performance improvement, could you share the benchmarking results?  It's not obvious from first principles that a non-`[[noreturn]]` branch with an addition is cheaper than an unconditional multiply-accumulate.  [Here's the godbolt disassembly](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIAHKQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BzmAMzByN5YANQmm27YeMCMAPQexJhH2CYaAIIPj14pRvun534gAGqVRGIm3QRysTzewWAnzOjBAfwBJEkIM2YOeTxMAFYrFiGCRMAQVgxMQAREn7ABuqDw6H2oVQACV8YSIGgGBN9v8HIiQWYAGwUyoAfQs81BLxeuyYCgU%2BwsdUOAHZUfsEl4IrQ8MgQC99hyEUCaagEtEmICAFQsgTszmA4Hmfnk4XzfasiZi9EK0ko8VPSXS/YAMVQqEVytV6s12qeupt3JVXlotEFNwAjl5MBNLWyCHqucQkfaBcgnS6rQR3Y8Y/qkfsWFKCNEs9bqzyHUKRaXsxWVcQ8OTTewdbL5fTBY8LILu7nbTSEmPUBZUGPJ96PV7US9Y/maUHUHDVYnk5g0xmCE2c1uC3yiyXXTmTEqh5eaeShc9V5Wb48AHQITBMdAIE2Z0jmJfZR3HQV9jNG8LF/f9AOAqc8CofYoFfYtHiAkDNjAjDhWwnCvTArgQMfaNdS/eCAOww5LFAlV50XZcpwfMC2iUfYULQ/CLFosAwAYjQyOVSi6UZAliAYCBeNFD9dTYocbkkhgvwrRT0SeZ9A2DOE6wmRs72nblC1kzt2QfUTuJk9taNAhiuEVNwHzcWC7NwoSRKHKs8xrfD31E3V/OoxCiLQudHgXJdHigmDeMIuiLDQiCJ2g2CQsIqcgrfdy8NspD5Mo5TCTUwq2P2DjMFDbzaQZJkpJs4sRVYz1xU9DhFloTgMV4PwOC0Ug9w4Zz6MsfYFGWVYqq2HhSAITQOsWABrEBJC4b8FT5DRYjMABOSQzE2BUyniLqOEkXqFsGzheAUEANDmhbFjgWAkDQFgEjoaJyEod7PvoGJgF2jE%2BDoBtiDuiAIiuiJgjqABPThZvethBAAeQYWhEf63gsDrIxxBx0h8BuKpXzuonMFUSovAbJHeGCBszoGjUImIBGPCwem5t7Fh6cWKgDGABRfjwTAAHc0eNPrZv4QQRDEdgpBkQRFBUdQid0FoDCMFBrGsfQ8AiO7YGYNgQEwGEGFIV8Yg4TZNl2xbBoSDoKYAWndiZkWJUxRosLgFX2d20bMYPiVCYlsAsOQAHFbraAE0hcBh3E8Jp/FT3oihKbJklSARRmaRJ846bP%2BlKVp2mqSYi70CoqgELp6nL2ZK4mbo6/GSZW9z0ilhWNY9AIG51h4TrusuomhtUWJeXd3lJH2YBkGQfZdu/DE0JGqxLFIT58EBOjNhafYPA%2Br7iGP0jeHmnH5mWkAju/YHdrMDQNEO3beX22JTs4C6pA%2BZcA/qQPqA0hq3Xuo9e%2BpAXqIBAMsAgqoCA/UtBfAGoRWDrFnvPReLodZQi4GYb8GhvyzUwIfEg1I9By2EKIcQys6FqzUFdLWpBxbswSPzfQk8wFXSGmjWmKD9ioFQrgheS8V5rw3lvCA59/rRGvvMW%2BT1Fh/gAgMCAj937fhPpIY6vJYiB12g7PkvDzpTwgTdWw0C75aAfhYswVjeCQJgQ4xYtsUjOEkEAA) for the two cases, for reference.  I think it's _plausible_ that this is faster, but that remains to be demonstrated.
</blockquote></details>

I agree it is impossible to tell by inspection whether this is a performance improvement. For example, the 3-element scalar multiply in master compiles into just two multiplies by using a SIMD instruction so could be cheaper than it appears in the source. 

You could attempt to resolve this by performance testing but I don't think we know this is currently a performance bottleneck so it probably isn't worth the trouble.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`math/rigid_transform.h` line 530 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17849#-NBKjSwn4NguBEURcBo1:-NBUFzWZ8EUZ43_1yQma:b3sew9w) ([raw file](https://github.com/robotlocomotion/drake/blob/c1dd2f383c9e9c5dfc0ff762a78c3618db4aa24e/math/rigid_transform.h#L530)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I agree it is impossible to tell by inspection whether this is a performance improvement. For example, the 3-element scalar multiply in master compiles into just two multiplies by using a SIMD instruction so could be cheaper than it appears in the source. 

You could attempt to resolve this by performance testing but I don't think we know this is currently a performance bottleneck so it probably isn't worth the trouble.
</blockquote></details>

@jwnimmer-tri   Thank you for creating the godbolt disassembly to see if the code is faster.  Unfortunately, I am not fluent in assembly so I'll defer to you and Sherm's comments and revert the code.  I agree that we do not know this is currently a performance bottleneck so it probably isn't worth the trouble.   

As for clarity: Except for splitting  if ((vec_A(3) = vec_B(3)) == 1) into two lines (which I agree would be clearer), I thought the suggested new version to be more readable and clearer.  However, readability and clarity are somewhat subjective and I'll defer to status quo.

**Review by mitiguy — COMMENTED** [review]
Platform review +@ggould-tri ( for Monday -- assuming it is too late for @ericcousineau-tri ).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849#-:-NBUeDeg-1xiSbL0IKrF:b-qdh0dz)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; thanks for the very clear comments.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17849#-:-NBlne3mDpLjfZ2t3V-X:bkoutb8)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
