### PR TITLE
Zero out rows and columns in block sparse matrix

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-:-NXGdx_rDr_xboiSBCcW:b-ec6d43)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1 and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few minor nags

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-:-NXHbBW2BRsiQK_5oZt7:b96a946)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h` line 240 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXH_aTv8OTdn70OzQfh:-NXH_aTv8OTdn70OzQfi:b-tsw2xd) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h#L240)):*
> ```objc
>   /* If this matrix is symmetric, zeros out all row and column blocks whose
>    block indices are included in `indices` and sets their diagonal blocks to be
>    diagonal submatrices. This function doesn't change the sparsity pattern.
> ```

BTW per f2f writing zeroes into a sparse matrix is weird enough that it would be worth a sentence or two here saying why we have this in the code.
___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h` line 241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHXgri7cJF6POnD8IB:-NXHXgri7cJF6POnD8IC:b85q4p2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h#L241)):*
> ```objc
>    block indices are included in `indices` and sets their diagonal blocks to be
>    diagonal submatrices. This function doesn't change the sparsity pattern.
>    @pre All entries in `indices` are in [0, block_cols()).
> ```

minor: the actual test is [0, block_rows()]. Are those the same?
___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHUKE52lW3yZYSxGWh:-NXHUKE52lW3yZYSxGWi:b7dmblj) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc#L80)):*
> ```cpp
> void BlockSparseLowerTriangularOrSymmetricMatrix<MatrixType, is_symmetric>::
>     ZeroRowsAndColumns(const std::vector<int>& indices) {
>   DRAKE_THROW_UNLESS(is_symmetric);
> ```

BTW should this just be a static_assert ? Would fail at compile time in that case.
___
*[`multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc` line 187 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHWmt57Wqe_-uNG8SS:-NXHWmt57Wqe_-uNG8ST:bdoxr0k) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc#L187)):*
> ```cpp
> 
>   /* Throws if input is out of range. */
>   EXPECT_THROW(A_triangular.ZeroRowsAndColumns({42}), std::exception);
> ```

minor: wouldn't this fail because it's lower triangular? Should use DRAKE_EXPECT_THROWS_MESSAGE() here and above to distinguish the "bad matrix" from "out of range" errors.

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation. Please kick it down the line (Sammy) if it's already too late.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-:-NXHhFP552uZBK4h4z9N:b-5zh85q)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h` line 240 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXH_aTv8OTdn70OzQfh:-NXHcOoJ1Sjam0T3bGC9:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h#L240)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f writing zeroes into a sparse matrix is weird enough that it would be worth a sentence or two here saying why we have this in the code.
</blockquote></details>

Done.
___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h` line 241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHXgri7cJF6POnD8IB:-NXHccW152nN4px95Ybk:b62ybn8) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h#L241)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the actual test is [0, block_rows()]. Are those the same?
</blockquote></details>

Done. Switched the tests to columns.
___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHUKE52lW3yZYSxGWh:-NXHd3bQB85LI5AqnYLd:bdp2c9k) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc#L80)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should this just be a static_assert ? Would fail at compile time in that case.
</blockquote></details>

A static_assert here wouldn't compile for all lower triangular instantiations.  
___
*[`multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc` line 187 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHWmt57Wqe_-uNG8SS:-NXHh0I-BQFpqkWzyDJr:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d97dc7c7ec1d455e2feedd752818e10bf28668d3/multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc#L187)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: wouldn't this fail because it's lower triangular? Should use DRAKE_EXPECT_THROWS_MESSAGE() here and above to distinguish the "bad matrix" from "out of range" errors.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I gave -@rpoyner-tri a lot of reviews today. I can take this one +@jwnimmer-tri.

:lgtm: platform.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-:-NXHmNQb2mnmE77lpQwf:b-tjv6wd)* status: 1 unresolved discussion

___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h` line 240 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHlrhz2vQR52aLFH-B:-NXHlrhz2vQR52aLFH-C:bgpid4o) ([raw file](https://github.com/RobotLocomotion/drake/blob/f74080f0aa9b669bd75d7c22784d4fa06a0ceb01/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h#L240)):*
BTW

> ... sets their diagonal blocks to be diagonal submatrices.

I read this a few times without grokking it.  Once I read the code, I was able to grok it.

For me, something like "sets the off-diagnonal elements of diagonal blocks to zero" probably would have been better.

If the intended audience for this low-level function would typically understand the docs as-written, I'm OK leaving it alone.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-:-NXHoNWFB2y0xPp_8b6O:b-ucfknh)* status: 1 unresolved discussion

___
*[`multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h` line 240 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19542#-NXHlrhz2vQR52aLFH-B:-NXHnuwP2k44pxprak6K:b-4vgg3) ([raw file](https://github.com/RobotLocomotion/drake/blob/f74080f0aa9b669bd75d7c22784d4fa06a0ceb01/multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h#L240)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW

> ... sets their diagonal blocks to be diagonal submatrices.

I read this a few times without grokking it.  Once I read the code, I was able to grok it.

For me, something like "sets the off-diagnonal elements of diagonal blocks to zero" probably would have been better.

If the intended audience for this low-level function would typically understand the docs as-written, I'm OK leaving it alone.
</blockquote></details>

I slightly tweaked your suggestion to emphasize it doesn't set *all* off-diagonal entries in the *entire matrix* to zero.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19542)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Pull request merged**
