### PR TITLE
Add DRAKE_ASSERT guidance to code_style_guide

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add DRAKE_ASSERT guidance per #1935.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2635)

### CODE REVIEW

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 92 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2635#-KKzin5RF3KO9nM_My2a:-KKzin5RF3KO9nM_My2b:736875942) ([raw file](https://github.com/robotlocomotion/drake/blob/744283221b8a109952743e57de85359294eedf75/drake/doc/code_style_guide.rst#L92)):*
> ```reStructuredText
> * Never use the `assert()` macro from `<cassert>`; instead, use `DRAKE_ASSERT`.
>   Never use `DRAKE_ASSERT(false)`; instead, use `DRAKE_ABORT()`. For discussion,
>   see Drake `#1935 <https://github.com/RobotLocomotion/drake/issues/1935>`_.
> ```

I think we should also encourage use of `DRAKE_ABORT_UNLESS` for assertions that can reasonably be left in production code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2635)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 92 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2635#-KKzin5RF3KO9nM_My2a:-KKzkDoxcuSCD9PuJk7s:161893936) ([raw file](https://github.com/robotlocomotion/drake/blob/744283221b8a109952743e57de85359294eedf75/drake/doc/code_style_guide.rst#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I think we should also encourage use of `DRAKE_ABORT_UNLESS` for assertions that can reasonably be left in production code.
</details>
Good point.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2635)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2635#-:-KKzr-zqSfP0GZ9kd4Lb:1417088721)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for the second review.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2635#-:-KKzwhBDyBT78cxZgQL9:-286211846)*

**Comment by ggould-tri** [comment]
Make it so.
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2635#-:-KL1qBkfiDxvDJ-Bfrdt:-20142124)*

**Comment by jwnimmer-tri** [comment]
Jenkins was fine except for an msvc64 flake; using override-merge.

**Pull request merged**
