### PR TITLE
Add a benchmark on MathematicalProgram.

### PR DESCRIPTION
**Pull request by hongkai-dai**
benchmark constructing a sum-of-squares program, which involves computing symbolic::Polynomial and imposing linear and semidefinite constraint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900#-:-MzcZb-PCHIle9NQdI70:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
The CI fails due to a linting error, complaining that 
```cc
static void BenchMarkSosProgram1(benchmark::State& state) {
```
should use a const reference. But I cannot make it const here due to a compilation error, also google's example code doesn't use const reference either https://github.com/google/benchmark

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900#-:-Mzc_G9w4n37PT6xKiBK:b38g231)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-LaBji9q7wwsy8KdSX:-N-LaBjk6JM3qdIeqs1D:b-xkncve) (no related file):*
> The CI fails due to a linting error, complaining that ...

Check any other googlebench program in Drake.  You'll find a NOLINT line that you can copy into this one.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-LaPmf3tIeIjZjV1dV:-N-LaPmf3tIeIjZjV1dW:b-ej01g3) (no related file):*
@rpoyner-tri my proposal for organizing benchmarks is that we strongly encourage authors benchmarking code into a second-level `benchmarking` folder (by documenting that in our benchmarking README), and to discourage shuffling them in with the library code and its tests:

Specifically, we'd use:
* geometry/benchmarking/...
* multibody/benchmarking/...
* solvers/benchmarking/...
* systems/benchmarking/...

My reasoning is that the most benchmarks (and especially the best ones) will be cross-cutting, touching more than one cc_library component, so trying to layerize them alongside the library and unit tests is a mismatch.  Putting them all in once places helps us find uniformity across them and provides a places for subsystem-specific benchmarking fixtures and model files that can be shared within several different bench programs.

WDYT?

The specific request for this PR would be to move the new code into a `solvers/benchmarking` folder.

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-LaPmf3tIeIjZjV1dV:-N-Ltg6a2Hmh835F05DQ:bt3zgia) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@rpoyner-tri my proposal for organizing benchmarks is that we strongly encourage authors benchmarking code into a second-level `benchmarking` folder (by documenting that in our benchmarking README), and to discourage shuffling them in with the library code and its tests:

Specifically, we'd use:
* geometry/benchmarking/...
* multibody/benchmarking/...
* solvers/benchmarking/...
* systems/benchmarking/...

My reasoning is that the most benchmarks (and especially the best ones) will be cross-cutting, touching more than one cc_library component, so trying to layerize them alongside the library and unit tests is a mismatch.  Putting them all in once places helps us find uniformity across them and provides a places for subsystem-specific benchmarking fixtures and model files that can be shared within several different bench programs.

WDYT?

The specific request for this PR would be to move the new code into a `solvers/benchmarking` folder.
</blockquote></details>

Done. I moved the code to solvers/benchmarking folder.

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-LaPmf3tIeIjZjV1dV:-N-OIg9z614hrV6Zq6NZ:byecztf) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I moved the code to solvers/benchmarking folder.
</blockquote></details>

I'll mark this resolved, but @rpoyner-tri I'd still like to hear your thoughts.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/BUILD.bazel, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-OGdFTA8imwv3mrKla:-N-OGdFU-6MQXTkyeHpM:b9yhnui) ([raw file](https://github.com/robotlocomotion/drake/blob/193051632ec6d775cbfffe567e377d8f5321adaa/solvers/BUILD.bazel#L16)):*
> ```Starlark
>     "mosek_test_tags",
> )
> load(
> ```

nit The `benchmarking` folder should its own separate BUILD file.
___
*[solvers/benchmarking/benchmark_mathematical_program.cc, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-OGw0z-mLfwXlGISMT:-N-OGw0z-mLfwXlGISMU:b-9glwjo) ([raw file](https://github.com/robotlocomotion/drake/blob/193051632ec6d775cbfffe567e377d8f5321adaa/solvers/benchmarking/benchmark_mathematical_program.cc#L9)):*
> ```cpp
> namespace {
> 
> static void BenchMarkSosProgram1(benchmark::State& state) {  // NOLINT
> ```

nit "benchmark" is a single word.



_Suggestion:_
```cpp
BenchmarkSosProgram1
```
___
*[solvers/benchmarking/benchmark_mathematical_program.cc, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-OH1kMCkdUbHnegiNA:-N-OH1kNDKGfkoRugr_p:b-i0ei56) ([raw file](https://github.com/robotlocomotion/drake/blob/193051632ec6d775cbfffe567e377d8f5321adaa/solvers/benchmarking/benchmark_mathematical_program.cc#L13)):*
> ```cpp
>     // Formulate a mathematical program with sum-of-squares constraints. This
>     // will involve a lot of computation on symbolic::Polynomial and imposing
>     // linear constraints.
> ```

nit Consider placing this comment atop the function, like an API overview.  It will help introduce the reader to what this "benchmark case" is probing.

Possibly also worth noting in the overview is that we construct the Polynomial directly from a Monomial map, as opposed to parsing an Expression.
___
*[solvers/benchmarking/benchmark_mathematical_program.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-OHYQyDHbWtwux4k0F:-N-OHYQz8NiDNxETr58q:b-94rs68) ([raw file](https://github.com/robotlocomotion/drake/blob/193051632ec6d775cbfffe567e377d8f5321adaa/solvers/benchmarking/benchmark_mathematical_program.cc#L27)):*
> ```cpp
>         for (int k = 0; k < monomial_basis.rows(); ++k) {
>           p_map.emplace(monomial_basis(k),
>                         static_cast<double>(i * j) / 100. + k / 10. + 1);
> ```

nit GSG forbids float constants ending with the trailing period.



_Suggestion:_
```cpp
static_cast<double>(i * j) / 100.0 + k / 10.0 + 1
```
___
*[solvers/benchmarking/benchmark_mathematical_program.cc, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-OIRQIANSER-CMvmIf:-N-OIRQJAxt-e7H5Wtvf:b-cjrx4d) ([raw file](https://github.com/robotlocomotion/drake/blob/193051632ec6d775cbfffe567e377d8f5321adaa/solvers/benchmarking/benchmark_mathematical_program.cc#L29)):*
> ```cpp
>                         static_cast<double>(i * j) / 100. + k / 10. + 1);
>         }
>         p_i(j) = symbolic::Polynomial(p_map);
> ```

nit We're eating a gratuitous copy here.



_Suggestion:_
```cpp
symbolic::Polynomial(std::move(p_map))
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-LaPmf3tIeIjZjV1dV:-N-Ow4Di81ptMpFLX1vp:b52w33z) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll mark this resolved, but @rpoyner-tri I'd still like to hear your thoughts.
</blockquote></details>

Proposal seems reasonable. There are probably several existing programs that may need to move eventually (out of scope for this PR).

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900#-:-N-P0yTU1J9QVfCXb_t5:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P19F61o1t3gnlMPRr:-N-P19F61o1t3gnlMPRs:b-5yriem) (no related file):*
nit CI is timing out on the slower builds.  Looks like we should try `test_timeout = "moderate"` on the `drake_cc_googlebench_binary`.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P1cc30ExyTgQNL7OM:-N-P1cc30ExyTgQNL7ON:b-5wqq89) (no related file):*
Working

I'll try running locally to confirm its performance.

---
___
*[solvers/benchmarking/BUILD.bazel, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P0qu54XCmehbv-UGy:-N-P0qu54XCmehbv-UGz:b-62fsea) ([raw file](https://github.com/robotlocomotion/drake/blob/f044397a51a4ea13fb836f3ca7df0e7fcd9e18b4/solvers/benchmarking/BUILD.bazel#L3)):*
> ```Starlark
> # -*- python -*-
> 
> load("@drake//tools/skylark:drake_cc.bzl", "drake_cc_binary")
> ```

nit Unused drake_cc_binary.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P19F61o1t3gnlMPRr:-N-P5CD_AKSHtdBWj7Yh:b5keq7v) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit CI is timing out on the slower builds.  Looks like we should try `test_timeout = "moderate"` on the `drake_cc_googlebench_binary`.
</blockquote></details>

Or maybe just #16896 needs to merge before us?

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P1cc30ExyTgQNL7OM:-N-PdzGVBk-bDJZNVwBO:b-h9c453) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As of this PR, 44 seconds:

```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
BenchmarkSosProgram1 44039257050 ns   44034460061 ns            1
```

After 16896, 33 seconds:

```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
BenchmarkSosProgram1 33584887505 ns   33581521169 ns            1
```

Possibly we should use a slightly smaller problem for benchmarking (maybe 10 polynomials instead of 30?) but in any case maybe we should wait to see how fast it gets as you fix up the code, before we care too much about the benchmark runtime.
</blockquote></details>

I changed the test size, now it takes 11s on my Puget machine.

---

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for Tuesday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900#-:-N-PeE4E5rTEes6Wgfkj:b-hv7u2n)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai, @jwnimmer-tri, and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P19F61o1t3gnlMPRr:-N-PhY-g2BOOpCQFEwSF:b-9jv1b8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given that's its approx 30 seconds in a Release build even after 16896, we probably do need to set it as "moderate".
</blockquote></details>

Seems like still too slow for CI's 60 second limit.  Needs "moderate".

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16900#-N-P19F61o1t3gnlMPRr:-N-Pii17DkdRWiv-P0IP:b-9yfkch) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Seems like still too slow for CI's 60 second limit.  Needs "moderate".
</blockquote></details>

Done, I added "moderate".

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16900#-:-N-VvMLp-mDsBin3Rv4P:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
