### PR TITLE
Rename is_nan(const Expression&) to isnan to be consistent with std::isnan

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4963)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@liangfok , feature-review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4963#-:-KbkdM5HNWg36lAYRY8P:b1vgcw8)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4963#-KbkeLIv0kI0rTb5fgtz:-KbkeLIv0kI0rTb5fgu-:baqhx0s) (no related file):*
Is it worth perhaps keeping separate the "Cell type is kNan" (what is_nan used to be) from "Evaluates to NaN" (what std::isnan asks)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4963)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4963#-KbkeLIv0kI0rTb5fgtz:-KbkeYbGcprsGHygt9ir:b-6j5ijb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is it worth perhaps keeping separate the "Cell type is kNan" (what is_nan used to be) from "Evaluates to NaN" (what std::isnan asks)?
</blockquote></details>

I guess it seems to me like std::is_nan should be formula-valued, not bool-valued.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4963)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4963#-KbkeLIv0kI0rTb5fgtz:-KbkecdwGdZ4chkYPB76:bmwi97i) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess it seems to me like std::is_nan should be formula-valued, not bool-valued.
</blockquote></details>

Erm, make that: I guess it seems to me like `std::isnan` ADL overload on `Expression` should be `Formula`-valued, not `bool`-valued?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4963)*

**Pull request closed without merging**
