### PR TITLE
update director and robotlocomotion_lcmtypes externals

### PR DESCRIPTION
**Pull request by patmarion**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4888)

### CODE REVIEW

**Comment by patmarion** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by patmarion** [comment]
+@sammy-tri for platform review

**Comment by sammy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[externals/director, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4888#-KbM8vSs7aXYsWdBN72A:-KbM8vStwojOk1sp2xad:bkpu8f6) ([raw file](https://github.com/robotlocomotion/drake/blob/8285019753b179a3b8126b3c6e53fbd74c6601ef/externals/director#L1)):*
> ```
> Subproject commit f82ba76fcbb104228ce910fa2dc3d0335d1143b8
> ```

This looks like it makes some fairly significant changes to the initialization process for drake-visualizer...  Is the resulting app the same from a look/feel standpoint?  It seemed possible to me that this was largely a reduction in duplicated code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4888)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4888)*

**Comment by patmarion** [comment]
Yes, it is a significant refactor of drake-visualizer to delete code and re-use existing code.  The look and feel is the same.  There is now a new toolbar, some new panels, new command line options, and support for a new drawing protocol.  I just announced this in the #general channel so others may be informed.

**Comment by sammy-tri** [comment]
:lgtm:  might be worth waiting to see if anyone else chimes in for a feature review, but I think that's going to be difficult without someone downloading and building the new branch, so I guess OK with me to merge if you don't get any further comment.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4888#-:-KbMAoN8uXfh5bqqxLOZ:b-1bkn87)*

**Pull request merged**
