### PR TITLE
separate the test for rotation_constraint_internal

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6625)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for both reviews.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-:-KpYIlpu1XBrQiujirgZ:b-kystnc)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri +@SeanCurtis-tri for platform review rotation today.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: The BTWs can be ignored as this is simply a case of moving code around. However, there was some documentation that felt dissatisfying. +@sherm1 for final platform review.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp__CtkJaOSRnuu_1l2:-Kp__CtkJaOSRnuu_1l3:bkpn405) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L18)):*
> ```cpp
>                                 std::vector<Vector3d> actual) {
>   EXPECT_EQ(desired.size(), actual.size());
>   Eigen::Matrix<bool, Eigen::Dynamic, 1> used =
> ```

BTW Could this not be `auto used = ...`?

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp__lt2gqQ4BThSqyM5:-Kp__lt34T7WJXei6iD2:bdrfoot) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L29)):*
> ```cpp
>         used(j) = true;
>         found_match = true;
>         continue;
> ```

BTW This surprised me. Once a `j` has been found that matches an `i`, why keep looking?  I would expect to see a `break` here.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp_aoJ7ZTScJe40-ee-:-Kp_aoJ8jjhkAwtrNTMD:bnjpg35) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L44)):*
> ```cpp
> 
>   // 4 co-planar vertices. Due to symmetry, we only test one out of the three
>   // regions.
> ```

BTW Presumably, the fact of the symmetry is tested elsewhere?

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp_ciUGAqMMzMEwgZeQ:-Kp_ciUGAqMMzMEwgZeR:bkrfguj) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L104)):*
> ```cpp
>   // vertices pts[i], pts[j] and pts[k], determine if the halfspace coinciding
>   // with the triangle is a cutting plane (namely all vertices in pts are on one
>   // side of the halfspace). Pick the cutting plane halfspace that is farthest
> ```

BTW This comment is a bit misleading. You're not "picking the cutting plane", you are merely computing the distance of that cutting plane. "Picking" implies that you're actually capturing the parameters of that half space. In fact, you're just computing its property and its provenance becomes immaterial.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp_dW8-GIg5NflGQD1n:-Kp_dW8-GIg5NflGQD1o:brqphi5) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L166)):*
> ```cpp
> 
>   // Four points, symmetric about the plane x = y. The tightest half space
>   // relaxation is not the plane coinciding with three of the points.
> ```

BTW This last comment wasn't particularly clear to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-:-Kp_eWaHT9zLk4V5l-hz:b-ixc718)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp__CtkJaOSRnuu_1l2:-Kp_pBdqk_VMfJliVPVZ:bhvktzo) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Could this not be `auto used = ...`?
</blockquote></details>

I think it is better not to use `auto` keyword for Eigen types here. The right handside is an `Eigen::Matrix` constant type, which is not the same as `Eigen::Matrix<bool, Dynamic, 1>`. It is not a big problem here, but can sometimes `auto` can cause unexpected issues in Eigen 
https://eigen.tuxfamily.org/dox/TopicPitfalls.html

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp__lt2gqQ4BThSqyM5:-Kp_ptP1b1nN0Piq4GVo:bmfgyam) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This surprised me. Once a `j` has been found that matches an `i`, why keep looking?  I would expect to see a `break` here.
</blockquote></details>

It is comparing two vectors `desired` and `actual`. These two vectors are not sorted, but they should have the same size. So for every element in `desired`, we need to check if there is an element in `actual` with the same value. If it finds a match, then proceed to the next element in `desired`.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp_aoJ7ZTScJe40-ee-:-Kp_qoddiMVD8Jnfjpcn:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L44)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Presumably, the fact of the symmetry is tested elsewhere?
</blockquote></details>

Done. Good call.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp_ciUGAqMMzMEwgZeQ:-Kp_tnBcrYCsp9G5unJb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L104)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This comment is a bit misleading. You're not "picking the cutting plane", you are merely computing the distance of that cutting plane. "Picking" implies that you're actually capturing the parameters of that half space. In fact, you're just computing its property and its provenance becomes immaterial.
</blockquote></details>

Done.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp_dW8-GIg5NflGQD1n:-Kp_u34vvGxLzgOmX2s9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L166)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This last comment wasn't particularly clear to me.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6625)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for humoring me on code that you didn't create.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp__CtkJaOSRnuu_1l2:-Kp_w0fbdx2TTKWZZcZz:b-yyv5ru) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L18)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think it is better not to use `auto` keyword for Eigen types here. The right handside is an `Eigen::Matrix` constant type, which is not the same as `Eigen::Matrix<bool, Dynamic, 1>`. It is not a big problem here, but can sometimes `auto` can cause unexpected issues in Eigen 
https://eigen.tuxfamily.org/dox/TopicPitfalls.html
</blockquote></details>

That make sense. In this case they *look* redundant but aren't. I'm satisfied.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kp__lt2gqQ4BThSqyM5:-Kp_w5xJF4L4k2PgaQO-:beth6sg) ([raw file](https://github.com/robotlocomotion/drake/blob/346deffc0e468aefbdf5d37784837fc4439ae2a9/drake/solvers/test/rotation_constraint_internal_test.cc#L29)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is comparing two vectors `desired` and `actual`. These two vectors are not sorted, but they should have the same size. So for every element in `desired`, we need to check if there is an element in `actual` with the same value. If it finds a match, then proceed to the next element in `desired`.
</blockquote></details>

I defer to you based on our f2f.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-:-Kp_wfn7yv5EKpmutf4b:bow4fra)*

**Comment by sherm1** [comment]
:lgtm:, one ignorable BTW.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kpaj82yjEtsny19ReH0:-Kpaj82yjEtsny19ReH1:b-bgzilw) ([raw file](https://github.com/robotlocomotion/drake/blob/58cb7ac1abddd05203de6665d68deb1c1d2cf04c/drake/solvers/test/rotation_constraint_internal_test.cc#L16)):*
> ```cpp
> namespace {
> void CompareIntersectionResults(std::vector<Vector3d> desired,
>                                 std::vector<Vector3d> actual) {
> ```

BTW `const std::vector<Vector3d>&` would be conventional if you don't need to write on these, to avoid the extra copy. Author's choice though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-:-Kpaju59IZeiHASAX29t:b-4q1kjp)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/rotation_constraint_internal_test.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6625#-Kpaj82yjEtsny19ReH0:-Kpao35Rnb6JStQ2leVZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58cb7ac1abddd05203de6665d68deb1c1d2cf04c/drake/solvers/test/rotation_constraint_internal_test.cc#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `const std::vector<Vector3d>&` would be conventional if you don't need to write on these, to avoid the extra copy. Author's choice though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6625)*

**Pull request merged**
