### PR TITLE
Upgrade to bazel 6.4.0

### LINKED ISSUE #20402: Upgrade to Bazel 6.4.0
https://github.com/bazelbuild/bazel/releases/tag/6.4.0

Prior upgrade to 6.3.1 was #19858.

### PR DESCRIPTION
**Pull request by svenevs**
Resolves #20402.

Previous upgrade PR #19891 (see comments as they go down for the full array of jobs we need to pass here first).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please.
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @svenevs)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhEEVyR07pSnO7IsLXp:-NhEEVyR07pSnO7IsLXq:b-6n9jae) (no related file):*
working, the previous PR #19891 was updating something for the wheel builds.  AFAICT, the wheel build now gets its bazel via our vendored bazelisk and therefore the `drake/.bazeliskrc` is defining it? @mwoehlke-kitware does that seem right to you?

Related: I've noticed that the output coming from drake-ci for the wheel builds does **not** spit out its `bazel_version` in the output.  Compare https://drake-jenkins.csail.mit.edu/job/linux-jammy-unprovisioned-clang-bazel-experimental-release/26/consoleFull (search `CMAKE_VERSION` to get to the summary table`) and https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-unprovisioned-clang-wheel-experimental-release/59/consoleFull or https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-release/81/consoleFull and search `CMAKE_VERSION`.

This makes verifying what's happening in this upgrade PR somewhat hidden.  Is there any reason we cannot add

https://github.com/RobotLocomotion/drake-ci/blob/92bfabe99de6fcdd269b7aa654891ab0f8d4e214/driver/configurations/bazel.cmake#L278-L283

to https://github.com/RobotLocomotion/drake-ci/blob/main/driver/configurations/wheel.cmake so that it tells us what's actually going on?

___

**Comment by svenevs** [comment]
Full set of Linux jobs (copied from https://github.com/RobotLocomotion/drake/pull/19891#issuecomment-1660357655 after confirming all jobs exist or updating to their newer version e.g., docs builds on jammy now):

@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please

@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please

@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-documentation please.
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-packaging please.

### skipping

```
# wheel jobs were launched above already
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please.

# it's not clear to me why coverage is useful here, this is a provisioned
# job so the changes we're keeping an eye out for won't get tested.
# Should we have unprovisioned coverage jobs?
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please
```

**Comment by svenevs** [comment]
Mac jobs from https://github.com/RobotLocomotion/drake/pull/19891#issuecomment-1660357655

@drake-jenkins-bot mac-x86-monterey-clang-cmake-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-cmake-experimental-release please
@drake-jenkins-bot mac-x86-monterey-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-monterey-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-address-sanitizer please

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhEND6198LTUZtVFDwv:-NhEND6198LTUZtVFDww:b-965cnl) (no related file):*
working, wheel failures are because this needs to be rebased to have https://github.com/RobotLocomotion/drake/commit/348b3505944c080e78aee80eafdc6db82c08bc52 in there, going to let the rest of the jobs finish running first to see who else may need attention.

given current results, probably I will just reprovision the other parts of CI in advance of this PR.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @svenevs)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhEEVyR07pSnO7IsLXp:-NhEpsSpCHlaKSrwVr0-:bv4sg8y) (no related file):*
> The wheel build now gets its bazel via our vendored bazelisk.

Yes.

> This makes verifying what's happening in this upgrade PR somewhat hidden.

The item in the log to see is `Downloading https://releases.bazel.build/6.4.0/release/bazel-6.4.0-linux-x86_64...`

> Is there any reason we cannot add ...

The wheel builds use (/ will use) CMake -- wrapped in the wheel_builder bash script, etc)  There will be no bazel installed anywhere that the driver script can find it before starting the build.

Soon enough, we won't even have the regular Ubuntu builds using the deb package.  It will all be bazelisk, just the dotfile as the one source of truth.

I don't necessarily mind trying to make the output more clear, but it doesn't seem like a huge deal and sounds a bit complicated to get it right.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhEND6198LTUZtVFDwv:-NhEphFt9HZwo0oVbHKf:b-i68gta) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, wheel failures are because this needs to be rebased to have https://github.com/RobotLocomotion/drake/commit/348b3505944c080e78aee80eafdc6db82c08bc52 in there, going to let the rest of the jobs finish running first to see who else may need attention.

given current results, probably I will just reprovision the other parts of CI in advance of this PR.
</blockquote></details>

You can re-launch the wheel builds without re-pushing.  It will merge up to master automatically on the re-test.

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhEEVyR07pSnO7IsLXp:-NhI8IEN88iW-RNG0iyz:bo0zp6c) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> The wheel build now gets its bazel via our vendored bazelisk.

Yes.

> This makes verifying what's happening in this upgrade PR somewhat hidden.

The item in the log to see is `Downloading https://releases.bazel.build/6.4.0/release/bazel-6.4.0-linux-x86_64...`

> Is there any reason we cannot add ...

The wheel builds use (/ will use) CMake -- wrapped in the wheel_builder bash script, etc)  There will be no bazel installed anywhere that the driver script can find it before starting the build.

Soon enough, we won't even have the regular Ubuntu builds using the deb package.  It will all be bazelisk, just the dotfile as the one source of truth.

I don't necessarily mind trying to make the output more clear, but it doesn't seem like a huge deal and sounds a bit complicated to get it right.
</blockquote></details>

done, ok thank you for confirming -- this is good for now then given the expected changes in the future :+1:

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhEND6198LTUZtVFDwv:-NhI8PRP3zPPvze0C800:bshjnzx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You can re-launch the wheel builds without re-pushing.  It will merge up to master automatically on the re-test.
</blockquote></details>

done, ok good to know, thank you for relaunching!

___

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-debug please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-address-sanitizer please.

mac x86 jobs seemed to have some trouble, trying just two, noting that this may actually need to get diagnosed in the future (too many runners via jenkins?  it shouldn't have been possible but they all seemed to timeout)

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[`tools/workspace/drake_visualizer/image/provision.sh` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhSKUU_EtbHFD3JjhaZ:-NhSKUU_EtbHFD3Jjha_:bzdyti3) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a26b66e301996308fa73b8b2c8d3f2fd0c0f947/tools/workspace/drake_visualizer/image/provision.sh#L7)):*
> ```Shell
> export DEBIAN_FRONTEND=noninteractive
> 
> readonly BAZEL_VERSION=6.4.0
> ```

BTW, any reason drake_visualizer isn't using bazelisk? Do we have an Issue for that?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @svenevs)

___
*[`tools/workspace/drake_visualizer/image/provision.sh` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhSKUU_EtbHFD3JjhaZ:-NhX6n4W2HKwbgLSkW1y:b313ndb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a26b66e301996308fa73b8b2c8d3f2fd0c0f947/tools/workspace/drake_visualizer/image/provision.sh#L7)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, any reason drake_visualizer isn't using bazelisk? Do we have an Issue for that?
</blockquote></details>

As of next March, we'll be dropping support for drake-visualizer entirely (and deleting this whole directory tree).  It's probably not worth investing in refactoring it for maintainability now.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/drake_visualizer/image/provision.sh` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-NhSKUU_EtbHFD3JjhaZ:-NhY7xSs6ITdBI4MAOSl:b3f1gjr) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a26b66e301996308fa73b8b2c8d3f2fd0c0f947/tools/workspace/drake_visualizer/image/provision.sh#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As of next March, we'll be dropping support for drake-visualizer entirely (and deleting this whole directory tree).  It's probably not worth investing in refactoring it for maintainability now.
</blockquote></details>

Makes sense! :+1:

**Review by svenevs — COMMENTED** [review]
-(status: do not merge) -(status: do not review) +(status: single reviewer ok) +@sammy-tri for review please.  The only thing we didn't test in CI for this PR was `memcheck`, there are no unprovisioned versions of this and the changes in this PR would not apply.

I have both of the new provisioned AMIs ready to go, once approved I will merge and switch the jenkins AMI selection together.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-:-NhgBtpnDilGpNhHUzFT:b-7584sk)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge", missing label for release notes

**Review by sammy-tri — COMMENTED** [review]
:lgtm: I'll let you merge in case there's anything else that needs to be done at the same time?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20410#-:-Nhh3yT15Z5iGUH2gjnm:b-9q9j8l)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Comment by svenevs** [comment]
> I'll let you merge in case there's anything else that needs to be done at the same time?

Perfect, thank you!  There is something that has to happen on the jenkins side at the time of merge, likely we will be doing that later this afternoon once the queue is empty.

**Comment by svenevs** [comment]
Jenkins backend changes are in, merging now.

**Pull request merged**
