### PR TITLE
find NumPy module inside pybind11

### PR DESCRIPTION
**Pull request by rdeits**
Per my initial discussion with @mwoehlke-kitware 

This seems to resolve the fact that drake doesn't have `FindNumPy.cmake` on its cmake module path. It also seems a bit better in general, since it doesn't require other tools that use pybind11 (like IRIS) to explicitly call `find_package(NumPy)` themselves.

This unblocks #5023 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5158)

### CODE REVIEW

**Comment by rdeits** [comment]
adding `find_dependency(NumPy)` to `pybind11Config` causes `find_package(pybind11)` to fail, even if the check for numpy is successful:

```
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.6")
-- Found NumPy: version "1.10.4" /usr/local/lib/python2.7/dist-packages/numpy/core/include
CMake Error at /home/rdeits/locomotion/drake-distro/cmake/packages.cmake:61 (message):
  WITH_PYBIND11 is enabled, but could NOT find pybind11
Call Stack (most recent call first):
  /home/rdeits/locomotion/drake-distro/cmake/packages.cmake:160 (drake_find_package)
  CMakeLists.txt:15 (drake_find_packages)
```

I have no idea why. Simply calling `find_package(NumPy)` inside `pybind11Tools.cmake`, however, does not cause this problem.

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by rdeits** [comment]
Ok, this does in fact cause the python tests to actually be run. Hooray.

**Comment by rdeits** [comment]
+@sherm1 +@jamiesnape 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5158#-:-KctlBu7pKuwyH1m4rqX:bte4neq)*

**Comment by sherm1** [comment]
Platform review :lgtm:, but definitely needs a feature review from @jamiesnape!

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5158#-:-KctqTcmHY3kE44WTg7Q:b4kuq6u)*

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
I was thinking to look for `NumPy` right after `PythonLibsNew` in `pybind11Config.cmake`, but on closer inspection, that does seem redundant...

It might be preferable to add components support so that consumers can `find_package(pybind11 COMPONENTS NumPy)` and have it fail if NumPy isn't found. (Otherwise, they would need to check `NumPy_FOUND` and produce their own error message...)

**Comment by rdeits** [comment]
Mac builds are currently failing on CI (but not on my machine). The error looks like the same one I've seen when symbol visibility is set to "hidden", as is the default with pybind11. I'm explicitly setting `-fvisibility=default` in the CMakeLists, however, so I don't know how this is happening.

**Comment by rdeits** [comment]
@mwoehlke-kitware I'm fine with that, but I have no idea how cmake components work. Is that something we need to do for this PR or can it come in when we try to merge your work into upstream?

**Comment by mwoehlke-kitware** [comment]
> I have no idea how cmake components work. Is that something we need to do for this PR or can it come in when we try to merge your work into upstream?

Either works, but if we wait, in the mean time I wonder if we shouldn't at least check that NumPy was indeed found?

**Comment by rdeits** [comment]
We do already check if numpy was found in `drake/CMakeLists.txt` when enabling the python bindings. Is that what you mean?

**Comment by mwoehlke-kitware** [comment]
> We do already check if numpy was found [...]

Ah, right.

Anyway, this *should* (caveat: not tested) add components support:

```diff
diff --git a/tools/pybind11Tools.cmake b/tools/pybind11Tools.cmake
index 597b2b8..f8f5521 100644
--- a/tools/pybind11Tools.cmake
+++ b/tools/pybind11Tools.cmake
@@ -14,7 +14,18 @@ endif()
 
 set(Python_ADDITIONAL_VERSIONS 3.7 3.6 3.5 3.4)
 find_package(PythonLibsNew ${PYBIND11_PYTHON_VERSION} REQUIRED)
-find_package(NumPy)
+if(PyBind11_COMPONENTS MATCHES NumPy)
+  if(PyBind11_FIND_REQUIRED AND PyBind11_FIND_REQUIRED_NumPy)
+    find_package(NumPy REQUIRED)
+  else()
+    find_package(NumPy)
+    if(PyBind11_FIND_REQUIRED_NumPy AND NOT NumPy_FOUND)
+      set(pybind11_NOT_FOUND_MESSAGE "pybind11 could not be found because required component NumPy could not be found.")
+      set(pybind11_FOUND False)
+      return()
+    endif()
+  endif()
+endif()
 
 include(CheckCXXCompilerFlag)
 include(CMakeParseArguments)
```

...then change `drake_find_package(pybind11 CONFIG)` to  `drake_find_package(pybind11 CONFIG COMPONENTS NumPy)`. If NumPy isn't found, `pybind11_FOUND` should be `FALSE` (or you could use `OPTIONAL_COMPONENTS` instead).

**Comment by rdeits** [comment]
Ok, thanks. Independent of the cmake `find_numpy` business, I am, somehow, now able to replicate the CI mac failures on my machine. I cannot replicate them on linux, which means it's almost certainly yet another clang flag issues. Sigh.

**Comment by rdeits** [comment]
Mac failures were due to a typo which only caused problems on osx+clang. Fixed now. 

@drake-jenkins-bot mac-clang-experimental please

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by rdeits** [comment]
Ok, everything is passing, both on my machine and on CI (finally). The root cause of all the mac problems was just the one typo fixed in da75817. @jamiesnape could you take a look?

**Comment by david-german-tri** [comment]
This is fine for moving forward, but in a follow-up we should get Drake back onto master of `RobotLocomotion/pybind11`.  (And of course, getting entirely back to upstream remains a short term goal, right?)  :lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5158#-:-Kd1KmA_GkpDTB0ma5me:b-mriamg)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5158#-:-Kd1LTAZsqdiGKTT-ycS:bnfp4nl)*

**Comment by david-german-tri** [comment]
Also, @mwoehlke-kitware says, on Slack:

> I think 5158 in its current state is not _worse_, but it won't solve the problem of bindings being silently disabled if NumPy is missing in its current state

Which is also fine for the moment, but should be addressed. -> #5177

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5158#-:-Kd1LWGhrpCxqtMtNeRh:bltkydq)*

**Comment by rdeits** [comment]
That's true. It's just that until this is merged, we have the silent
failure even when numpy /is/ installed

**Comment by david-german-tri** [comment]
Great.  It sounds to me like there's a consensus for merging this then; @rdeits, I'll leave it to you to squash or otherwise curate and merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5158#-:-Kd1Nc6maPlcJznBilG6:b612iis)*

**Comment by mwoehlke-kitware** [comment]
> (And of course, getting entirely back to upstream remains a short term goal, right?)

Yes. The expected timeline for this is:
- pybind/pybind11#610 merged (basically we are "stuck" until this happens)
- refactor numpy "object" support on top of that (including changes here and in forthcoming fix for #5177)
- PR to upstream

**Comment by jagerman** [comment]
pybind/pybind11#610 just merged.

**Pull request merged**
