### PR TITLE
Irb140 urdf

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. I forgot to include the convex hull obj files for IRB140 in my previous pull request
2. Add a collision filter group for the base link in IRB140.
3. Fix a joint limit error in IRB140 URDF error.

@patmarion, could you review it?

### CODE REVIEW

**Comment by patmarion** [comment]
+1 thanks!

**Comment by RussTedrake** [comment]
The ATI_sensor.obj stands out as by far the largest mesh in this commit.  (over 2 MB).  is that intended/necessary?

**Comment by hongkai-dai** [comment]
No, I do not mean to get the ATI_sensor.obj file so big, the meshlab changed it when I try to generate the convex hull object ATI_sensor_chull.obj.

I can revert this file to the previous version, which is 600KB.

**Comment by hongkai-dai** [comment]
I reverted ATI_sensor.obj file to the previous version.

**Pull request merged**
