### PR TITLE
[framework] Use static_cast (not dynamic_cast) in hot path

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #15421.  (This is the last of the hot spots that I've found to date.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review or delegation, please.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with one question.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470#-:-MfZ98iI5hAup4qr-2Jq:b-hryn1j)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram.cc, line 1004 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15470#-MfZ8Q4JBL9OsstMMHWJ:-MfZ8Q4JBL9OsstMMHWK:b-9ztmx9) ([raw file](https://github.com/robotlocomotion/drake/blob/0e94cc54c67818f40659d707d3b9c592bf8f2b6b/systems/framework/diagram.cc#L1004)):*
> ```cpp
>   this->ValidateContext(context_base);
>   auto& diagram_context =
>       static_cast<const DiagramContext<T>&>(context_base);
> ```

BTW did you re-profile to check that it's still a win to insert ValidateContext here while removing the dynamic_cast? I'm confident that it is, but not 100% certain since optimizers can be squirrely.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram.cc, line 1004 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15470#-MfZ8Q4JBL9OsstMMHWJ:-MfZE7By4beuFqBRFdCk:bku7870) ([raw file](https://github.com/robotlocomotion/drake/blob/0e94cc54c67818f40659d707d3b9c592bf8f2b6b/systems/framework/diagram.cc#L1004)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW did you re-profile to check that it's still a win to insert ValidateContext here while removing the dynamic_cast? I'm confident that it is, but not 100% certain since optimizers can be squirrely. 
</blockquote></details>

I do remember thinking about measuring that, but I don't remember if I did the experiment or not.  I think probably not.

I know for sure that in the prior measurement it was calling the libstdc++ helper function here for the dynamic_cast, and was a hundreds-of-instructions-long hot spot.  As you say, it does not seem plausible that a single branch on an int64 constant could possibly be slower.  The documented premise of ValidateContext is that it's a-ok to use in inner loops.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470#-:-MfZLYxuC3gR3LNBMkrP:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram.cc, line 1006 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15470#-MfZKpsX0ygHBBwGAWV-:-MfZKpsX0ygHBBwGAWV0:b-4f6ngb) ([raw file](https://github.com/robotlocomotion/drake/blob/0e94cc54c67818f40659d707d3b9c592bf8f2b6b/systems/framework/diagram.cc#L1006)):*
> ```cpp
>       static_cast<const DiagramContext<T>&>(context_base);
> 
>   // Profiling revealed that it is too expensive to do a dynamic_cast here.
> ```

BTW Worth adding this `@pre` to the documentation in the header?

Likewise worth adding that `context_base` points to the instance of `DiagramContext` owned by `this` `Diagram`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram.cc, line 1006 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15470#-MfZKpsX0ygHBBwGAWV-:-MfZLqek0yZa88ItCRFT:b8iwk50) ([raw file](https://github.com/robotlocomotion/drake/blob/0e94cc54c67818f40659d707d3b9c592bf8f2b6b/systems/framework/diagram.cc#L1006)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Worth adding this `@pre` to the documentation in the header?

Likewise worth adding that `context_base` points to the instance of `DiagramContext` owned by `this` `Diagram`?
</blockquote></details>

Interesting, I'll look.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[systems/framework/diagram.cc, line 1006 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15470#-MfZKpsX0ygHBBwGAWV-:-MfZMvl-BzPX4bNMR__i:b-ftuntg) ([raw file](https://github.com/robotlocomotion/drake/blob/0e94cc54c67818f40659d707d3b9c592bf8f2b6b/systems/framework/diagram.cc#L1006)):*
> BTW Worth adding this pre to the documentation in the header?

Done.  Noting potential UB seems worthwhile!

> Likewise worth adding that context_base points to the instance of DiagramContext owned by this Diagram?

For a private method, I'm satisfied with the ValidateContext exception in that case.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15470)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
