### PR TITLE
Dense pool

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This is the whole autodiff pool allocation campaign, laid out as a sequence of reviewable-sized commits. The actual PRs will show up as the individual commits in order. This "PR" is just here to get a full scan from CI before launching the PR sequence.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLs9fmp58VJQ2awrAVK:-MLs9fmq37RiFk42O3a0:b7719r0) (no related file):*
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLs9fmp58VJQ2awrAVK:-MLs9n2u2tRijLot_8UE:b7719r0) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
</blockquote></details>

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLs9fmp58VJQ2awrAVK:-MLsBEY_Acn2G-cBgQ_m:bed5sb5) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
</blockquote></details>

This build should show whether (some of) my mods to the provisioning list are adequate, in particular, by "fixing" the eigen_dense_storage_pools_rss_test .

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLsBg_P9B0L5GIyEJch:-MLsBg_Q1zdVD4Ls8o1C:bs6e2le) (no related file):*
Build failures in the FEM dev code turned up a new exciting Eigen specialization footgun. Investigating...

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLs9fmp58VJQ2awrAVK:-MLt2uIK1XTyiWJNV0J2:byrq4sm) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This build should show whether (some of) my mods to the provisioning list are adequate, in particular, by "fixing" the eigen_dense_storage_pools_rss_test .
</blockquote></details>

That worked. So action item is to get `psutil` added to provisioned instances.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLsBg_P9B0L5GIyEJch:-MLt30xdCDsPQ5ddkLJ_:b-5se41h) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Build failures in the FEM dev code turned up a new exciting Eigen specialization footgun. Investigating...
</blockquote></details>

The easy way out is to just change the magic number.

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLsBg_P9B0L5GIyEJch:-MLteKy2En58fWA2_Y98:bnta1z6) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The easy way out is to just change the magic number.
</blockquote></details>

Am I reading the error message correctly that this is the problematic `EXPECT...`

```c++
  AutoDiffXd energy = elasticity_element_->CalcElasticEnergy(*state_);
  VectorX<AutoDiffXd> neg_force = CalcNegativeElasticForce();
  EXPECT_TRUE(CompareMatrices(energy.derivatives(), neg_force,
                              std::numeric_limits<double>::epsilon()));
```

Isn't that code mixing Eigen types in a broken way in the first place?  The first arg to Compare is a vector of doubles, the second arg to Compare is a vector of ADX?

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLsBg_P9B0L5GIyEJch:-MLtocRh1blzYvDWWm91:b-kl7tn4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Am I reading the error message correctly that this is the problematic `EXPECT...`

```c++
  AutoDiffXd energy = elasticity_element_->CalcElasticEnergy(*state_);
  VectorX<AutoDiffXd> neg_force = CalcNegativeElasticForce();
  EXPECT_TRUE(CompareMatrices(energy.derivatives(), neg_force,
                              std::numeric_limits<double>::epsilon()));
```

Isn't that code mixing Eigen types in a broken way in the first place?  The first arg to Compare is a vector of doubles, the second arg to Compare is a vector of ADX?
</blockquote></details>

IIRC there are a bunch of scalar/ADX math overloads, perhaps we are invoking them. I'll continue to investigate.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLtoxoS8Ffvg-eyQyRa:-MLtoxoT3ur-1lzK37HR:b-nqr550) (no related file):*
There is some sort of link error on focal, but not on bionic. Need to investigate that.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLs9fmp58VJQ2awrAVK:-MM28YRW5BvzlSOhINct:b-a0i5w6) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

That worked. So action item is to get `psutil` added to provisioned instances.
</blockquote></details>

nm. dependency is no longer needed.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLsBg_P9B0L5GIyEJch:-MM29jzk0g1K0QGr4Fs_:b6sahs) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

IIRC there are a bunch of scalar/ADX math overloads, perhaps we are invoking them. I'll continue to investigate.
</blockquote></details>

There are indeed a bunch of scalr/ADX comparison operators: https://github.com/RobotLocomotion/drake/blob/master/common/autodiffxd.h#L140-L164

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MLtoxoS8Ffvg-eyQyRa:-MM28kYK2FrDt5SAXl-U:byizyoc) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

There is some sort of link error on focal, but not on bionic. Need to investigate that.
</blockquote></details>

r3 ditched the problematic test. We'll see how the builds go.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14318#-MM2H_O33s2IO7ft1R_H:-MM2H_O43OoRpwFVQ3xK:b-ytnnd6) (no related file):*
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please.

---

**Review by rpoyner-tri — COMMENTED** [review]
I won't be merging this version of code. Instead, a sequence of smaller PRs with subsequent cleanups will get merged. I'll keep this PR open for a while to serve as a design reference for the actual PR train.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14318#-:-MM2xJPT-ELDJ69-HdtV:b-82p5or)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by rpoyner-tri** [comment]
Deemed too complex for amount of performance gain.

**Pull request closed without merging**
