### PR TITLE
[workspace] Upgrade rules_python to latest release 0.29.0

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This one looks like it's probably my fault.  I'll take a look.

**Comment by mwoehlke-kitware** [comment]
@jwnimmer-tri, thanks. It wasn't obvious what file is supposed to be modified. If it's just a case of I missed something, please update the `upgrade_advice` so it's easier to tell what to do in the future.

**Comment by mwoehlke-kitware** [comment]
BTW, I was debating if it would be useful if `new_release` could be taught to *also* run a script to take care of things like keeping `tools/install/bazel/test/drake_bazel_installed_test.py` in sync.

**Comment by jwnimmer-tri** [comment]
I pushed what _might_ be a fix (still running locally, no problems so far).  I cleaned up the test a little bit, but you can push any more clarifications you think would help.

More automation hooks would be fine by me, but probably for a future PR.

**Comment by jwnimmer-tri** [comment]
Okay, this passes for me locally in the nominal config.  We'll let CI test the gauntlet.

**Review by mwoehlke-kitware — COMMENTED** [review]
> I cleaned up the test a little bit

Thanks! I wasn't even close guessing where our copy of that file was; hopefully the full paths will help.

> More automation hooks would be fine by me, but probably for a future PR.

Yes, I didn't intend to suggest doing it in this PR! (Or even this week, most likely.)

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-:-Nq4jAsZ6VBnIRThRwxq:bfhr2fh)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq4k1Ci2R8ITgDfcwE1:-Nq4k1Ci2R8ITgDfcwE2:b-eurkta) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/tools/install/bazel/test/drake_bazel_installed_test.py#L57)):*
> ```Python
>     urls = {rules_python_urls!r},
> )
> load(
> ```

What does this do?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq4k1Ci2R8ITgDfcwE1:-Nq4lH4-DNVSq43xQQWq:b-wbpoch) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/tools/install/bazel/test/drake_bazel_installed_test.py#L57)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

See https://github.com/bazelbuild/rules_python/releases/tag/0.29.0.  According to upstream, we're supposed to load rules_python like this:

```
http_archive(name  = "rules_python", ...)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
```

That is, we first download the archive, then load a macro from inside the archive, then call the macro which will do arbitrary things and downloads and who knows what to our computer.  In Drake we try to bound what our repository rules do, so instead of calling `py_repositories()` we call just the one little piece of `py_repositories` that we need.

This is the same as what we already do here ...

https://github.com/RobotLocomotion/drake/blob/c4c92533dbfc5ea5704df894c90687f6f2d62401/tools/workspace/rules_python/repository.bzl#L29

... except that we in this code we can directly call the `internal_config_repo` loaded from `rules_python`, instead of the vendored copy.

I suppose this merits a comment on this line that goes something like:

```py
# Instead of calling py_repositories() here like upstream recommends,
# we just call the one tiny slice of it that we actually care about.
load(
    "@rules_python/...",
```

Could you work on a phrasing you like, and push that?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq4k1Ci2R8ITgDfcwE1:-Nq8d5vC6jNPzZ1hCZdi:bzf7bcp) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/tools/install/bazel/test/drake_bazel_installed_test.py#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

See https://github.com/bazelbuild/rules_python/releases/tag/0.29.0.  According to upstream, we're supposed to load rules_python like this:

```
http_archive(name  = "rules_python", ...)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
```

That is, we first download the archive, then load a macro from inside the archive, then call the macro which will do arbitrary things and downloads and who knows what to our computer.  In Drake we try to bound what our repository rules do, so instead of calling `py_repositories()` we call just the one little piece of `py_repositories` that we need.

This is the same as what we already do here ...

https://github.com/RobotLocomotion/drake/blob/c4c92533dbfc5ea5704df894c90687f6f2d62401/tools/workspace/rules_python/repository.bzl#L29

... except that we in this code we can directly call the `internal_config_repo` loaded from `rules_python`, instead of the vendored copy.

I suppose this merits a comment on this line that goes something like:

```py
# Instead of calling py_repositories() here like upstream recommends,
# we just call the one tiny slice of it that we actually care about.
load(
    "@rules_python/...",
```

Could you work on a phrasing you like, and push that?
</blockquote></details>

To clarify, "why is this new as of this PR" would have been a better phrasing. Am I to understand that it always should have been present and we're just lucky it was working before?

I guess the above is fine if you think a comment is warranted. If so, the same comment probably belongs in `repository.bzl`.

**Comment by mwoehlke-kitware** [comment]
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq4k1Ci2R8ITgDfcwE1:-Nq8dsKJ0kxVJgNnqmYL:b101bpy) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/tools/install/bazel/test/drake_bazel_installed_test.py#L57)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

To clarify, "why is this new as of this PR" would have been a better phrasing. Am I to understand that it always should have been present and we're just lucky it was working before?

I guess the above is fine if you think a comment is warranted. If so, the same comment probably belongs in `repository.bzl`.
</blockquote></details>

(Possibly an explanation for the above in the commit message would help in case someone stumbles on this change in the future and has the same question...)

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-:-Nq9Fgb55MqVV2YMMIHy:b2xa7ij)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq4k1Ci2R8ITgDfcwE1:-Nq9Dulm9Lz2toGmF82s:b-z6sm3u) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/tools/install/bazel/test/drake_bazel_installed_test.py#L57)):*
> To clarify, "why is this new as of this PR" would have been a better phrasing. Am I to understand that it always should have been present and we're just lucky it was working before?

I wouldn't quite say it that way.

Rather, the set of repositories that the upstream `py_repositories()` declares under the hood is subject to change with every new release they make, and whether those repositories end up being relevant to Drake's particular BUILD files will also vary with each new release.

Sometimes, all of the upstream changes end up being irrelevant for us so we don't need to take any action.  In this case, some upstream changes _were_ relevant so we needed to adapt our "pretend that we called `py_repositories()` work-around to match.

> I guess the above is fine if you think a comment is warranted.

I'm knee-deep in the weeds and I understand the mechanisms in play, so I don't need any comment for my own purposes.  The question is whether comment(s) are important for any newcomers to this code.

For that, you're probably the best judge.  What would you have wanted to see here?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`tools/install/bazel/test/drake_bazel_installed_test.py` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq4k1Ci2R8ITgDfcwE1:-Nq9O6FW2mWQjD3Bn48U:b5rrldh) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/tools/install/bazel/test/drake_bazel_installed_test.py#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> To clarify, "why is this new as of this PR" would have been a better phrasing. Am I to understand that it always should have been present and we're just lucky it was working before?

I wouldn't quite say it that way.

Rather, the set of repositories that the upstream `py_repositories()` declares under the hood is subject to change with every new release they make, and whether those repositories end up being relevant to Drake's particular BUILD files will also vary with each new release.

Sometimes, all of the upstream changes end up being irrelevant for us so we don't need to take any action.  In this case, some upstream changes _were_ relevant so we needed to adapt our "pretend that we called `py_repositories()` work-around to match.

> I guess the above is fine if you think a comment is warranted.

I'm knee-deep in the weeds and I understand the mechanisms in play, so I don't need any comment for my own purposes.  The question is whether comment(s) are important for any newcomers to this code.

For that, you're probably the best judge.  What would you have wanted to see here?
</blockquote></details>

The _original_ question was "why was this added now". That was addressed via F2F and is mostly only relevant to this review, so...

As to what would help someone newly coming across the code, your previous suggestion looks fine. I might prefix it with something like "we need to initialize the widget" (really bad phrasing, but again I don't really understand what's going on), i.e. why we are calling _anything_. (Unhelpfully, the official doc doesn't seem to explain `py_repositories()` either...)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: (feature). Per discussion, a comment near `internal_config_repo(...)` might be helpful, but it wouldn't be the end of the world if that ends up in a follow-on PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-:-Nq9PUH12rX8HtEYz8OD:b-mzt2be)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by SeanCurtis-TRI** [comment]
-@EricCousineau-TRI +@SeanCurtis-TRI

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-:-Nq9hlf7CaceqOLKDdqz:bmxilld)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq9gWHF2SrEx30vqFey:-Nq9gWHF2SrEx30vqFez:b9xjp92) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl#L64)):*
> ```Starlark
>     # py_internal global, which are necessary for the pystar implementation.
>     if pystar_requested and hasattr(native, "starlark_doc_extract"):
>         enable_pystar = pystar_requested
> ```

BTW Given that the only way this line can get executed is for `pystar_requested` to be `True`, perhaps it would be better to use the literal instead of asking the reader to reason through the contextual logic.



_Code quote:_
```Starlark
enable_pystar = pystar_requested
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq9gWHF2SrEx30vqFey:-Nq9iH6qBvxChUnDGkA8:bow7p05) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl#L64)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given that the only way this line can get executed is for `pystar_requested` to be `True`, perhaps it would be better to use the literal instead of asking the reader to reason through the contextual logic.
</blockquote></details>

The context here is perhaps not clear -- this is `third_party` code that we copy (vendor) from upstream.  We didn't write this, we just keep a "backup" here (in a sense).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20902)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20902#-Nq9gWHF2SrEx30vqFey:-Nq9iqs31JRa1f5BQtGg:bdmieqp) ([raw file](https://github.com/RobotLocomotion/drake/blob/9cfcfefee20eeab87586a0b2b1b70f1b4c4e5281/third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The context here is perhaps not clear -- this is `third_party` code that we copy (vendor) from upstream.  We didn't write this, we just keep a "backup" here (in a sense).
</blockquote></details>

Aaaah....

No, I hadn't realized that was the case. Happily retracted.

**Pull request merged**
