### PR TITLE
 [multibody] Deprecate erroneous "_continuous_" port names

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #12214
    
This patch fixes the port names that generated the original ask for port
name deprecation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Only review  r2; r1 is a copy of #16268, may need rebase after that prior patch merges.
+(status: do not merge) 
+(release notes: newly deprecated) 
+@sherm1 for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269#-:-MrQXoiF6RD6PuoG__Mf:b-f5bliz)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong:
Great to see this finally after so long complaining about it!
+@sammy-tri for platform review (Wed) per rotation

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269#-:-MrTC6C66iPiofSv9lMJ:b9p59ul)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @sammy-tri, and @sherm1)

___
*[multibody/plant/multibody_plant.cc, line 2843 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16269#-MrTB_oz-SMhbTl6__PT:-MrTB_oz-SMhbTl6__PU:brz1pwx) ([raw file](https://github.com/robotlocomotion/drake/blob/afb17dc107f7b20dd3ee85799c8d5c4f8522f7e5/multibody/plant/multibody_plant.cc#L2843)):*
> ```cpp
>                                     {this->all_state_ticket()})
>           .get_index();
>   this->DeclareDeprecatedOutputPort("2022-04-01", "continuous_state", "state");
> ```

BTW beautiful!!
___
*[multibody/plant/test/multibody_plant_test.cc, line 235 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16269#-MrTBx8r1MOVLj64RQ25:-MrTBx8s6lSqndgkzFZk:bpgtyey) ([raw file](https://github.com/robotlocomotion/drake/blob/afb17dc107f7b20dd3ee85799c8d5c4f8522f7e5/multibody/plant/test/multibody_plant_test.cc#L235)):*
> ```cpp
>   EXPECT_EQ(plant->GetOutputPort("DefaultModelInstance_continuous_state")
>             .get_name(),
>             "DefaultModelInstance_state");
> ```

BTW odd indent/line break?

**Review by sherm1 — COMMENTED** [review]
Since Wednesday is the last official platform review day for a few weeks, Sammy is the last chance. I'm hoping @rpoyner-tri has #16268 ready to go in time. I don't think a review conditional on the upcoming rebase is unreasonable under the circumstances.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269#-:-MrTX7uOEGI7KrHlir1p:b-crwjma)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @sammy-tri, and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
I doubt the other PR is going to land in time. @sammy-tri feel free to punt at your convenience.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269#-:-MrTrOVCAXNQEnW_Duqu:b-wdpf9)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri, @sammy-tri, and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
Bleh. updated to address comment, and now there are a wealth of revisions to ignore. Ignore `r1` - `r3`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269#-:-MrYP5_68qsE9vTH9-3k:bwt56v9)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @sherm1)

**Review by sammy-tri — COMMENTED** [review]
I'm still willing to review it after the holiday and #16268 is merged.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16269#-:-MrYUAoP2SOH68tFZCk4:b-88jbqw)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @sherm1)

**Comment by jwnimmer-tri** [comment]
Given the status of the base PR #16268, possibly we should close this one for now?

**Pull request closed without merging**
