### PR TITLE
Add buildifier (with wrapper); improve tutorial instructions

### LINKED ISSUE #4463: Add buildifier tool and docs
Buildifier is clang-format for BUILD files.  We should have Drake developers use it on the BUILD files.  This is a portion of #3129.

WIP at https://github.com/jwnimmer-tri/drake/tree/bazel-buildifier-in-workspace ~but we should wait for bazelbuild/buildifier#21 to merge before pushing my WIP to master~.  I can work on docs in the meantime.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #4463.  A fixed-up version of #4474.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4477)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-:-KYpOcYFlhIKDwmWQFyg:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYsq3TX9oSfhs9QB8dP:-KYspT9w_ThQgfCKh4WA:bnudghq) ([raw file](https://github.com/robotlocomotion/drake/blob/eb0fd0ed51c0daff71ce50b27a5838df0f331cbe/WORKSPACE#L69)):*
> ```
> 
> # Necessary for buildifier.
> go_repositories()
> ```

BTW do these rules download the Go compiler under the hood?  I guess that's fine...

---

*[drake/doc/bazel.rst, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYsr-CGPNVFe1xU2Q2F:-KYsr-CHoYk7giBrxp6f:bul3tl2) ([raw file](https://github.com/robotlocomotion/drake/blob/eb0fd0ed51c0daff71ce50b27a5838df0f331cbe/drake/doc/bazel.rst#L81)):*
> ```reStructuredText
>   bazel test --config=memcheck common:polynomial_test  # Run one test under memcheck (valgrind).
>   bazel test --config=asan common:polynomial_test      # Run one test under AddressSanitizer.
>   bazel build common:polynomial_test && \
> ```

`-c dbg`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYsq3TX9oSfhs9QB8dP:-KYsyCdUF0Cl3olu-m5r:b8g50lv) ([raw file](https://github.com/robotlocomotion/drake/blob/eb0fd0ed51c0daff71ce50b27a5838df0f331cbe/WORKSPACE#L69)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW do these rules download the Go compiler under the hood?  I guess that's fine...
</blockquote></details>

Yes, from e.g. `https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYsr-CGPNVFe1xU2Q2F:-KYsylLou51l_kd0ny1E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb0fd0ed51c0daff71ce50b27a5838df0f331cbe/drake/doc/bazel.rst#L81)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

`-c dbg`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-:-KYt-SfRnAfnOrJioryB:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477)*

**Comment by jwnimmer-tri** [comment]
@liangfok Curious to see if the new instructions work well for you, any questions, etc.

**Comment by liangfok** [comment]
:eye: :eye:  now.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-:-KYtAnXRj4PrGpfr_liE:b2u9t3t)*

**Comment by liangfok** [comment]
I left a few clarifying comments. PTAL. Otherwise, :lgtm: . 

FTR, I checked out this PR and tested the `bazel build //...` and `bazel test //...` commands on my local Ubuntu 16.04 machine.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/bazel.rst, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtHUzHxvqq-HgFgAzd:-KYtHUzIKSvf-yaM-C-l:b-kcn7bv) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L49)):*
> ```reStructuredText
> 
> - The "``//``" means "starting from the root of the project".
> - The "``...``" means "everything including the subdirectories' ``BUILD`` files".
> ```

BTW, I wonder whether "including the subdirectories' `BUILD` files" is necessary? Is it possible to indicate "not including the subdirectories' `BUILD` files"?

A line below says: ... above means "everything include subdirectories". Consider using that line here as well for consistency.

---

*[drake/doc/bazel.rst, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtIM7M3iQxTYKi6Hnd:-KYtIM7N7JGcP1U03T1r:bv5o5rn) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L63)):*
> ```reStructuredText
> 
>   - In the first two lines we did not precede "``...``" with "``//``", so the
>     search begins in the current directory (``common``) not from the
> ```

BTW, consider adding "and" in front of "not".

---

*[drake/doc/bazel.rst, line 84 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtIhjKu-F5CyTAfVCu:-KYtIhjKu-F5CyTAfVCv:be2nbgw) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L84)):*
> ```reStructuredText
>     gdb ../bazel-bin/drake/common/polynomial_test      # Run one test under gdb.
> 
> - The "``:``" syntax that separates target names from the directory path of the
> ```

BTW, consider deleting "that".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-:-KYtJ5lIFOtYYl_nhXFJ:b8c7ctm)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/bazel.rst, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtHUzHxvqq-HgFgAzd:-KYtQuiAYKuBuCjcCh_4:b-da4oha) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L49)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I wonder whether "including the subdirectories' `BUILD` files" is necessary? Is it possible to indicate "not including the subdirectories' `BUILD` files"?

A line below says: ... above means "everything include subdirectories". Consider using that line here as well for consistency.
</blockquote></details>

Labels like `bazel build .` and `bazel build :*` would not build the subdirectories.  Would there be a way to make this clearer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/bazel.rst, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtHUzHxvqq-HgFgAzd:-KYtTG3Nf67KYrefy8oK:bpt6wee) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Labels like `bazel build .` and `bazel build :*` would not build the subdirectories.  Would there be a way to make this clearer?
</blockquote></details>

Yeah, let's explicitly list them out as separate bullets:

```
- The "``//``" means "starting from the root of the project".
- The "``...``" means "everything including the subdirectories".
- The "`.`" and "`:*`" means "everything in the local directory only".
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/bazel.rst, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtHUzHxvqq-HgFgAzd:-KYtqON4NaWKAmaQN4QP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L49)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yeah, let's explicitly list them out as separate bullets:

```
- The "``//``" means "starting from the root of the project".
- The "``...``" means "everything including the subdirectories".
- The "`.`" and "`:*`" means "everything in the local directory only".
```
</blockquote></details>

Done.

---

*[drake/doc/bazel.rst, line 63 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtIM7M3iQxTYKi6Hnd:-KYtp35xwzVXK0NNeX8h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L63)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding "and" in front of "not".
</blockquote></details>

Done.

---

*[drake/doc/bazel.rst, line 84 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-KYtIhjKu-F5CyTAfVCu:-KYtp7xYhaQZS-dn3CHG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69ac0bbde8b6ff6b3cf4258b186c7f078c168a72/drake/doc/bazel.rst#L84)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "that".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-:-KYtqghxKdrwlyZparg3:b-83330m)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4477#-:-KYttNBpxgy9DM8Ie574:bnfp4nl)*

**Pull request merged**
