### PR TITLE
Run clang-format on drake/common

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The additional manual edits were:
- Add BR in several place to control line-wrapping
- drake_assert.h: Add whitespace; add endif comment
- polynomial.cc: Use auto
- polynomial.h: Add required braces; fix cast style

This continues the slow burn towards making clang-format our One True God.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4827)

### CODE REVIEW

**Comment by sammy-tri** [comment]
:lgtm:  I still don't like this tool, or the fact that it enforces style which the style guide indicates is discretionary.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-KasytnTe9WRgO1Dic9K:bguzb3c)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-Kat-RGHh7WSp4uL6nhR:b-7ei152)*

**Comment by ggould-tri** [comment]
These changes seem arbitrary and, although all lie well within author's discretion, on net slightly worse than before (except the manual auto'ification and cast-correction of legacy code, of course).

 * One-lining functions that are not obviously-named and trivial getters or setters worsens readability, for instance, and IMO is seldom appropriate for "capitalized name" functions.
 * On the other hand one-line consequent clauses for if statements, explicitly allowed in our code conventions and frequently the most readable form, seem to be killed.
 * Re-indenting string construction is downright foolish for an automated tool, as humans indent it to hint its semantics; the `BR` decoration is a clever hack but is in no way an improvement to readability.
 * There's an indentation case in`text_logging.h` that is a very clear case where the script has grossly worsened readability.

Overall, this change seems to be a rejection of the principles of author's discretion and readability-over-formality in our code conventions, a worsening of readability, and at best borderline.  Our existing code conventions are better than this code convention.

If there has been some organizational decision I am unaware of that we must proceed toward a totalizing tool like this, I will reluctantly lgtm it as it does not violate any explicit and precise rules of our conventions.  But frankly, apart from the manual edits which I would be happy to accept in a separate PR, this does not Look particularly Good To Me.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/text_logging.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-KawK6t0C8k2QMxcQHLq:-KawK6t1tAcpw8T1EZ_A:b-obr2d1) ([raw file](https://github.com/robotlocomotion/drake/blob/5c7a4543f51896589ef8e3a7a7de4504f5a7a08b/drake/common/text_logging.h#L91)):*
> ```objc
>   void error(const T&) {}
>   template <typename T>
>   void critical(const T&) {}
> ```

FYI -- As a perfect example -- this change obviously worsens readability without being formally defective.  No human would write or prefer code like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-KawI6xmrmDvroRejiD9:ba7y212)*

**Comment by sammy-tri** [comment]
Emphatic agreement with the above.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-KawPiFn_qreikJ14sW5:b1drdo6)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/text_logging.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-KawK6t0C8k2QMxcQHLq:-KawPpVbqqG3vunPCN1B:bquj1wm) ([raw file](https://github.com/robotlocomotion/drake/blob/5c7a4543f51896589ef8e3a7a7de4504f5a7a08b/drake/common/text_logging.h#L91)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- As a perfect example -- this change obviously worsens readability without being formally defective.  No human would write or prefer code like this.
</blockquote></details>

BTW +1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827)*

**Comment by jwnimmer-tri** [comment]
Please identify specific worsening with (possibly-_Meta_) defects marked on the specific lines, so that I can fix them.

> One-lining functions that are not obviously-named and trivial getters or setters worsens readability, for instance, and IMO is seldom appropriate for "capitalized name" functions.

Done (with a BR).

I actually think that `AllowShortFunctionsOnASingleLine: Inline` is likely the correct answer here -- it lets header files inline methods be folded up by default, but everything else is unfolded.  Try it locally and see what you think?  Or I can push it to this PR if you like.

> On the other hand one-line consequent clauses for if statements, explicitly allowed in our code conventions and frequently the most readable form, seem to be killed.

These changes seemed more readable to me.  Please mark specific defects if you have them.

> Re-indenting string construction is downright foolish for an automated tool, as humans indent it to hint its semantics; the BR decoration is a clever hack but is in no way an improvement to readability.

Where?

> There's an indentation case intext_logging.h that is a very clear case where the script has grossly worsened readability.

Done.

---

Review status: 14 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/text_logging.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-KawK6t0C8k2QMxcQHLq:-Kawm7Zuapq5T4pi6NOo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c7a4543f51896589ef8e3a7a7de4504f5a7a08b/drake/common/text_logging.h#L91)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW +1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-KawmrycmVYEjO5P5cE8:bl6f6m)*

**Comment by sherm1** [comment]
Review status: 14 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/text_logging.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-Kax3uXU8gqp24iq_CXv:-Kax3uXVraoq--QTLQXs:b-dr184t) ([raw file](https://github.com/robotlocomotion/drake/blob/76afe6d5945391113d4a7c2a01f130daccf5ec5c/drake/common/text_logging.h#L87)):*
> ```objc
>   template <typename T> void error(const T&) {}
>   template <typename T> void critical(const T&) {}
>   // clang-format on
> ```

BTW, I really don't like this solution. I don't think I should have to say "don't mess up my carefully formatted code", especially in a way that makes it uglier. IMO humans should not have to wade through comments intended for machines when trying to understand my software.

I would be willing to put `//clang-format off` at the top of the file and leave it that way, but that seems silly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827)*

**Comment by sherm1** [comment]
I agree with @sammy-tri and @ggould-tri that this is a step backwards.

---

Review status: 14 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-Kax4r86Te3kcJS6rpi5:b90zbls)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/text_logging.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-Kax3uXU8gqp24iq_CXv:-Kax4io2sD22y6yCmDqi:b-3ky862) ([raw file](https://github.com/robotlocomotion/drake/blob/76afe6d5945391113d4a7c2a01f130daccf5ec5c/drake/common/text_logging.h#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I really don't like this solution. I don't think I should have to say "don't mess up my carefully formatted code", especially in a way that makes it uglier. IMO humans should not have to wade through comments intended for machines when trying to understand my software.

I would be willing to put `//clang-format off` at the top of the file and leave it that way, but that seems silly.
</blockquote></details>

That may be true in other cases, but is it a true problem in this instance?  The purpose of using compacted lines for the above is because nobody should ever study it.  I don't think these comments make the stub more difficult to read, because its supposed to be ignored anyway?  Or is your feeling that in this one instance, the comments are a readability burden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827)*

**Comment by jwnimmer-tri** [comment]
Do you at least agree that the non-controversial changes made by the tool are am improvement.  For me, having to fight the tool occasionally is much better than having to nitpick crappy bespoke formatting during code review.

---

Review status: 14 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-Kax55DwW-MJKZmklYI7:b5lyhmw)*

**Comment by ggould-tri** [comment]
The *Meta* objection is that this is overriding reasonable exercises of author's discretion rather than leaving compliant code in place.  If this were a whitespace-only change of compliant code to slightly differently compliant code we would reject it out of hand; the only reason to consider these changes at all is the tool.

---

Review status: 14 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-Kax6cr_JdG1DaLsV3-C:bzz5tp)*

**Comment by sherm1** [comment]
> Do you at least agree that the non-controversial changes made by the tool are an improvement?

I'm not sure which ones are non-controversial. Every change involving `//BR` is definitely a negative, both because of the extra clutter and because some poor programmer had to spot (somehow) that their code got mangled and then fix it. Scanning through I saw some inoffensive changes that were neutral; mildly annoying but acceptable changes where I would have preferred the old code; and an occasional fix toward the style guide (like putting `&` in the right place). I don't think it was a net improvement.

I don't really see the problem you are trying to solve, Jeremy. clang-format is a great tool and I use it all the time. But I run it myself over code I am currently looking at, most commonly over local selections in CLion over code that I have just mangled myself. I also use it on bulk code where I don't care that much about the formatting as a quick way to keep cpplint happy. I think the cpplint requirement is enough motivation for people to submit well-formatted code and I would rather encourage people to use clang-format rather than mandate it.

---

Review status: 14 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/text_logging.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-Kax3uXU8gqp24iq_CXv:-KaxIPka-oo99Zp_plaV:b21qf66) ([raw file](https://github.com/robotlocomotion/drake/blob/76afe6d5945391113d4a7c2a01f130daccf5ec5c/drake/common/text_logging.h#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That may be true in other cases, but is it a true problem in this instance?  The purpose of using compacted lines for the above is because nobody should ever study it.  I don't think these comments make the stub more difficult to read, because its supposed to be ignored anyway?  Or is your feeling that in this one instance, the comments are a readability burden.
</blockquote></details>

In this case it is the writability burden that concerns me the most. You added those guards because someone examined the code and noticed that clang-format messed up these lines. In the wild, there won't be anyone to provide that signal so the code is likely to end up formatted against the wishes and careful work of the author. I don't like looking at the guards but here they are not really doing any damage the way they would in the middle of a hairy algorithm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-:-KaxEoGZX4a4xJxigKUd:bpnp1go)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/text_logging.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4827#-Kax3uXU8gqp24iq_CXv:-KaxJcB9NY-lMGn2e-OW:b-o4v4kh) ([raw file](https://github.com/robotlocomotion/drake/blob/76afe6d5945391113d4a7c2a01f130daccf5ec5c/drake/common/text_logging.h#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

In this case it is the writability burden that concerns me the most. You added those guards because someone examined the code and noticed that clang-format messed up these lines. In the wild, there won't be anyone to provide that signal so the code is likely to end up formatted against the wishes and careful work of the author. I don't like looking at the guards but here they are not really doing any damage the way they would in the middle of a hairy algorithm.
</blockquote></details>

Before we would ever enforce clang-format project-wide, we would first teach our editors to format on the fly (or on save), so that you would immediately see and correct any defects.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4827)*

**Comment by jwnimmer-tri** [comment]
Grant has convinced me to search for better tools (see #4843) before pushing ahead with clang-format.

**Pull request closed without merging**
