### PR TITLE
template PointPair on scalar type

### PR DESCRIPTION
**Pull request by RussTedrake**
only doubles for now.  autodiff coming next

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8167)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@seancurtis-tri for feature review, please.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-:-L69s9_lC35JmW_5Rn0P:b-t5m2ic)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: I didn't delve directly into making sure this affects all `PointPair` instances. But if CI is happy, I'm happy.

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-:-L6AKZTR9u_2-MAxTkel:b-9k5inu)*

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for platform review, please

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-:-L6BIQXp_4MWwkq_niSD:b-wcm2v)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/collision/point_pair.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-L6CUsBWzi9-Kd9G0wtV:-L6CUsBXo5YBT1JdMR_p:b-cywl9q) ([raw file](https://github.com/robotlocomotion/drake/blob/7e33ffdbdc43be314d4ee4d136237f420edb26cf/multibody/collision/point_pair.h#L13)):*
> ```objc
> 
> /** Structure containing the results of a collision query. **/
> template <typename T = double>
> ```

BTW Unclear why `= double` is used here.  This PR compiles file without it, and most other T-templated classes in Drake do not say this.

---

*[multibody/collision/point_pair.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-L6CVUWA4i2yTMKGnu1P:-L6CVUWA4i2yTMKGnu1Q:b-v28kdl) ([raw file](https://github.com/robotlocomotion/drake/blob/7e33ffdbdc43be314d4ee4d136237f420edb26cf/multibody/collision/point_pair.h#L33)):*
> ```objc
>         ptA(other.ptA), ptB(other.ptB),
>         normal(other.normal),
>         distance(other.distance) {}
> ```

FYI It would be slightly more robust to write this implementation as a delegating constructor to the above one; that way, if the number of arguments (fields) changes, the compiler would force us to update this constructor as well.  However, given that this is legacy code perhaps its not worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-:-L6CUYzdhVIC1_bQjVe2:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/collision/point_pair.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-L6CUsBWzi9-Kd9G0wtV:-L6CdY2OD_cG_y8ag1wM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e33ffdbdc43be314d4ee4d136237f420edb26cf/multibody/collision/point_pair.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Unclear why `= double` is used here.  This PR compiles file without it, and most other T-templated classes in Drake do not say this.
</blockquote></details>

Done.

---

*[multibody/collision/point_pair.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8167#-L6CVUWA4i2yTMKGnu1P:-L6Cdyb_Snti8bMad_-_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e33ffdbdc43be314d4ee4d136237f420edb26cf/multibody/collision/point_pair.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It would be slightly more robust to write this implementation as a delegating constructor to the above one; that way, if the number of arguments (fields) changes, the compiler would force us to update this constructor as well.  However, given that this is legacy code perhaps its not worth it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8167)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8167)*

**Pull request merged**
