### PR TITLE
Actuate the iiwa in the hardware_sim example

### PR DESCRIPTION
**Pull request by zachfang**
Toward #20221 

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
Thanks for the heads-up!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-:-NfWqW05A-lWjxR1qyXr:bbdbdpw)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`examples/hardware_sim/example_scenarios.yaml` line 28 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfWqhEP14kIO6mQaG_Y:-NfWqhEP14kIO6mQaG_Z:b-spv5qa) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L28)):*
> ```YAML
>       X_PF:
>         base_frame: world
>         translation: [0, -1.0, 0]
> ```

FYI, this is to avoid collisions between the gripper and the floor.



_Code quote:_
```YAML
 translation: [0, -1.0, 0]
```
___
*[`examples/hardware_sim/example_scenarios.yaml` line 51 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfWqqr2-6-RtdWpLvM1:-NfWqqr34DGObEI9z31G:ba44hsc) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L51)):*
> ```YAML
>     iiwa_command:
>       # Use a non-default LCM url to actuate the simulated IIWA arm.
>       lcm_url: udpm://239.255.2.1:6776?ttl=0
> ```

FYI. Not sure if we have a good candidate for a non-default LCM URL, so I picked one we used in another project.



_Code quote:_
```YAML
udpm://239.255.2.1:6776?ttl=0
```

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-:-NfWsuEd9Gei_TbSmkPX:b-1wvd9i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none) 

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-:-NfXd8Za5La4hK-8bKOo:b-safpmt)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/BUILD.bazel` line 101 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXeZMS0Y5JotkN_-5Z:-NfXeZMS0Y5JotkN_-5_:bretzst) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/BUILD.bazel#L101)):*
> ```Starlark
> drake_py_unittest(
>     name = "hardware_sim_cc_test",
>     allow_network = ["lcm:meshcat"],
> ```

BTW Revert all edits to existing contents of the BUILD file, per the unit test overview comment in another discussion thread.  We should only have _new_ content in BUILD.
___
*[`examples/hardware_sim/example_scenarios.yaml` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXepoA0Ngv0CXvFnO5:-NfXepoA0Ngv0CXvFnO6:bvf8n4z) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L49)):*
> ```YAML
>       child: wsg::body
>   lcm_buses:
>     iiwa_command:
> ```

It's a little bit weird to have iiwa messages on one bus and wsg message on another.  Could we use the same bus for both?  Also this bus has iiwa _status_ messages too, not only commands.

In short, this bus name is probably not what we want.

Maybe `driver_traffic` would work better as a name?
___
*[`examples/hardware_sim/example_scenarios.yaml` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXfH6l-tb5FFGggf2q:-NfXfH6l-tb5FFGggf2r:bhi591h) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L62)):*
> ```YAML
>       hand_model_name: wsg
>       lcm_bus: iiwa_command
>     wsg: !SchunkWsgDriver {}
> ```

nit Per the other discussion above, my gut feeling is that wsg and iiwa should be on the same bus.  WDYT?
___
*[`examples/hardware_sim/iiwa_commander.py` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXg2gP9DgU52z715Rv:-NfXg2gP9DgU52z715Rw:b-hml2x7) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/iiwa_commander.py#L18)):*
nit

> The initial positions (in radians). This needs to be in sync with the scenario file.

This will bitrot.  It should be easy to guard the cross-checking with a unit test.
___
*[`examples/hardware_sim/iiwa_commander.py` line 22 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXgEWE4-NfrbnD3CyO:-NfXgEWE4-NfrbnD3CyP:b-6axece) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/iiwa_commander.py#L22)):*
> ```Python
> 
> # Use a non-default LCM url to send iiwa commands.
> lcm = DrakeLcm("udpm://239.255.2.1:6776")
> ```

BTW We might as well check this URL versus the yaml with a unit test as well.  Then we don't have to rely on any manual testing of iiwa_commander.
___
*[`examples/hardware_sim/iiwa_commander.py` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXgR-u4IcbBI-tOReY:-NfXgR-vALl_xkWqauH8:b-l7fg2h) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/iiwa_commander.py#L31)):*
> ```Python
>     parser.add_argument(
>         "--iiwa_command_hz",
>         type=int,
> ```

BTW Surely we should allow floating-point values here (and for `cycle_time`)?

Ah, I see, it's the weird `range` phrasing that's tripping us up.

I expect there is a simple fix.  Something like start a counter as `i = 0`, then use a single `while True` loop.  Each time through the loop, increment `i` by one and sleep for `1 / Hz`.  The formula for `sin` will be a function of `i`.



_Suggestion:_
```Python
type=float,
```
___
*[`examples/hardware_sim/iiwa_commander.py` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXgpCh9RkJLi-dRuwR:-NfXgpCh9RkJLi-dRuwS:b-sa7bb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/iiwa_commander.py#L53)):*
> ```Python
>     iiwa_command.num_joints = 7
>     while True:
>         if args.unit_test:
> ```

nit For simplicity, there should only be exactly one place where we customize the "unit test only" hacking.  We can do it immediately after the call to `sleep` -- after sleeping, `if unit_test: sys.exit(0)`.
___
*[`examples/hardware_sim/README.md` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXduT2BQmE36b1KmQV:-NfXduT2BQmE36b1KmQW:b-5tfuvg) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/README.md#L54)):*
> ```Markdown
> 
> ```
> python3 iiwa_commander.py
> ```

nit We never told the user to copy this file, so they can't literally run this command.

I'm not sure whether it's better to add the copy to step (2), or to mention the copying in (5) again -- since step (5) is optional, adding more notes into step (2) might be unwanted.
___
*[`examples/hardware_sim/README.md` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXeTjv4VHlF89ul5I_:-NfXeTjw7LaC7LSTA-0Z:b-mmx91h) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/README.md#L54)):*
> ```Markdown
> 
> ```
> python3 iiwa_commander.py
> ```

nit They won't be able to do this unless they Ctrl-Z the prior hardware_sim.py program.  We should give instructions that don't require them to know how bash works.
___
*[`examples/hardware_sim/README.md` line 83 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXeGzm-DmrhteQ5Rwd:-NfXeGznEn6Dm_jrn4PV:bbys3p4) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/README.md#L83)):*
> ```Markdown
> ```
> 
> Additionally, to actuate the robot:
> ```

nit Consistent phrasing



_Suggestion:_
```Markdown
Optionally,
```
___
*[`examples/hardware_sim/README.md` line 85 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXeLIV53XgctZA-WAH:-NfXeLIV53XgctZA-WAI:bjamkvn) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/README.md#L85)):*
> ```Markdown
> Additionally, to actuate the robot:
> ```
> $ bazel run //examples/hardware_sim:iiwa_commander
> ```

nit They won't be able to do this unless the Ctrl-Z the prior demo_cc program.  We should give instructions that don't require them to know how bash works.
___
*[`examples/hardware_sim/test/hardware_sim_test_common.py` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXdXU5BGk1Hd2tKMUD:-NfXdXU5BGk1Hd2tKMUE:bmysd1t) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/test/hardware_sim_test_common.py#L7)):*
> ```Python
> Note that this file is only ever imported; it is never run as a unittest
> program itself; we'll use wrapper files named hardware_sim_cc_test and
> hardware_sim_py_test to actually run it.
> ```

See this overview.  This unit test is for the simulator(s) and is actually run 2x -- once for C++ and once for Python.

As such, it's not an appropriate place to add tests for the commander program.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/BUILD.bazel` line 101 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXeZMS0Y5JotkN_-5Z:-NflV9WWDi8ri55-repp:b-mzqs56) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/BUILD.bazel#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Revert all edits to existing contents of the BUILD file, per the unit test overview comment in another discussion thread.  We should only have _new_ content in BUILD.
</blockquote></details>

Working. If I am not mistaken, the two tests still need the `allow_network` tag because they load `example_scenarios.yaml` that contains a non-default LCM url.
___
*[`examples/hardware_sim/example_scenarios.yaml` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXepoA0Ngv0CXvFnO5:-NflVWYTD5C-tS3Unf0R:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's a little bit weird to have iiwa messages on one bus and wsg message on another.  Could we use the same bus for both?  Also this bus has iiwa _status_ messages too, not only commands.

In short, this bus name is probably not what we want.

Maybe `driver_traffic` would work better as a name?
</blockquote></details>

Done.
___
*[`examples/hardware_sim/example_scenarios.yaml` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXfH6l-tb5FFGggf2q:-NflVYVGArrWSV7ySlG-:bs7wumx) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Per the other discussion above, my gut feeling is that wsg and iiwa should be on the same bus.  WDYT?
</blockquote></details>

Done. 
___
*[`examples/hardware_sim/README.md` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXeTjv4VHlF89ul5I_:-NflVfUe8x-iNuJn0Hmx:b-y7z4df) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/README.md#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit They won't be able to do this unless they Ctrl-Z the prior hardware_sim.py program.  We should give instructions that don't require them to know how bash works.
</blockquote></details>

Does specify "in another terminal" work?
___
*[`examples/hardware_sim/robot_commander.py` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NflVxc_8n-BLni-NuOh:-NflVxca8uIMyU8ObpPF:b-w46wn1) ([raw file](https://github.com/RobotLocomotion/drake/blob/a11d76a73f9cf348b793cf439e5f380bc98f3e0c/examples/hardware_sim/robot_commander.py#L1)):*
> ```Python
> """A simple program to actuate the robot, an IIWA arm and a WSG gripper, with a
> ```

FYI. Maybe I changed the file too much that `git` thinks I created a new file (and deleted the old one). 



_Code quote:_
```Python
"""A simple program to actuate the robot, an IIWA arm and a WSG gripper, with a
```
___
*[`examples/hardware_sim/iiwa_commander.py` line 18 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXg2gP9DgU52z715Rv:-NflWPmr2UMiJXMZ3zP0:b-ajvqab) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/iiwa_commander.py#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit

> The initial positions (in radians). This needs to be in sync with the scenario file.

This will bitrot.  It should be easy to guard the cross-checking with a unit test.
</blockquote></details>

Working. To extract the initial pose, it takes some parsing. I will work on that but pushed the changes first to make sure it's on the right direction.
___
*[`examples/hardware_sim/test/hardware_sim_test_common.py` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfXdXU5BGk1Hd2tKMUD:-NflWVy55ODHEjfxLOKS:buvpjh4) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/test/hardware_sim_test_common.py#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

See this overview.  This unit test is for the simulator(s) and is actually run 2x -- once for C++ and once for Python.

As such, it's not an appropriate place to add tests for the commander program.
</blockquote></details>

Done. Moved to a separate test file with parameter checking.

**Review by zachfang — COMMENTED** [review]
Thanks for the patch. It's ready for review again.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-:-NfvHY7r8t0K0CmtbywI:bv2rja3)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/example_scenarios.yaml` line 51 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfWqqr2-6-RtdWpLvM1:-NfvDaVW2ZrTQZz1G-NV:bgzdlde) ([raw file](https://github.com/RobotLocomotion/drake/blob/39f5b9ba7c3d30d5aa39d18d633133ad115f3a29/examples/hardware_sim/example_scenarios.yaml#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'd rather not us re-use one of the Anzu URLs that comes from from our real hardware in the lab.

Here's our canonical spelling of a nonsense URL:

```py
def unique_lcm_url(path):
    """Returns a unique LCM url given a path."""
    rand = [int(c) for c in hashlib.sha256(path.encode("utf8")).digest()]
    return "udpm://239.{:d}.{:d}.{:d}:{:d}?ttl=0".format(
        rand[0], rand[1], rand[2], 20000 + rand[3])
```

Taking for example `hardware_sim` as the input, we have:
```console
>>> [int(c) for c in hashlib.sha256("hardware_sim".encode("utf8")).digest()][:4]
[241, 129, 92, 185]
```

So a safer URL would be `udpm://239.241.129.92:20185?ttl=0`, for example.  The high-numbered port is probably the most important piece.

I posted the fix in my PR.
</blockquote></details>

Good to know, thanks!
___
*[`examples/hardware_sim/robot_commander.py` line 26 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfuuJxEC0ayBd69h9Is:-NfvGtNJDL6syImtlDxz:bpfugy5) ([raw file](https://github.com/RobotLocomotion/drake/blob/a11d76a73f9cf348b793cf439e5f380bc98f3e0c/examples/hardware_sim/robot_commander.py#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Global variables should be simple values, not interactive objects with background threads, so that merely importing a module doesn't do real work.

I posted the fix in my PR.
</blockquote></details>

Right, thanks!
___
*[`examples/hardware_sim/robot_commander.py` line 34 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-Nfuu-YCBtp5Q2rNBaNz:-NfvFoypAvAm9bL9LDqB:b-cq5cdm) ([raw file](https://github.com/RobotLocomotion/drake/blob/a11d76a73f9cf348b793cf439e5f380bc98f3e0c/examples/hardware_sim/robot_commander.py#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This file has a weird mix of global constants and argparse "constants".  We should pick one or the other.

For simplicity, I went with global constants and I posted the fix in my PR.
</blockquote></details>

Agreed! It's way cleaner.
___
*[`examples/hardware_sim/robot_commander.py` line 44 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfvHEpr46ZSy0WVg5HR:-NfvHEpr46ZSy0WVg5HS:b-83vurc) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2c05861e70db807e3c8902a34c934ec7aa21c57/examples/hardware_sim/robot_commander.py#L44)):*
> ```Python
>         sine = np.sin(2 * np.pi * i / (CYCLE_TIME * COMMAND_HZ))
>         iiwa_command.joint_position = IIWA_Q0 + sine * IIWA_MAX_DEFLECTION
>         wsg_command.target_position_mm = 1e3 * (
> ```

FYI. I changed `1e-3` to `1e3` to convert meters to millimeters.



_Code quote:_
```Python
1e3
```
___
*[`examples/hardware_sim/test/robot_commander_test.py` line 50 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfvGLLf0uSbxkZ9uvxJ:-NfvGLLf0uSbxkZ9uvxK:bsu3av1) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2c05861e70db807e3c8902a34c934ec7aa21c57/examples/hardware_sim/test/robot_commander_test.py#L50)):*
> ```Python
>             mut.main()
>         finally:
>             mut.LCM_URL = old_url
> ```

BTW/question. Why do we need to set the `old_url` back?



_Code quote:_
```Python
        finally:
            mut.LCM_URL = old_url
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/test/robot_commander_test.py` line 50 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfvGLLf0uSbxkZ9uvxJ:-NfvQYvq3aVxYgSv2KBE:b-j1b25y) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2c05861e70db807e3c8902a34c934ec7aa21c57/examples/hardware_sim/test/robot_commander_test.py#L50)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW/question. Why do we need to set the `old_url` back?
</blockquote></details>

The other test case(s) depend on the URL.  Currently we would luck out because of the alpha-sorting of test cases, but that seemed too brittle. (Feel free to add a comment to that effect if you like.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@rpoyner-tri for platform review per schedule, please.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-:-NfvlxV5CmNOFh7yIqXx:b-gb4g9z)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`examples/hardware_sim/BUILD.bazel` line 101 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfvlUE87HhpbnAn5Mzl:-NfvlUE87HhpbnAn5Mzm:b-cqfuv) ([raw file](https://github.com/RobotLocomotion/drake/blob/568c9801535b64bd771723be16deba3bfca6214a/examples/hardware_sim/BUILD.bazel#L101)):*
> ```Starlark
> drake_py_unittest(
>     name = "hardware_sim_cc_test",
>     allow_network = ["lcm:meshcat"],
> ```

BTW It might be worth a comment here that it's safe to use `lcm` here because the  uses a nonsense URL and only transmits status messages?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 7 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-:-Nfw3Eno2JMzyQIp5xLS:bnfp4nl)* status: 1 unresolved discussion

**Comment by zachfang** [comment]
Let me add the comment in the BUILD file real quick (was planning to address it with the platform review comments).

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

___
*[`examples/hardware_sim/BUILD.bazel` line 101 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20283#-NfvlUE87HhpbnAn5Mzl:-Nfw69F_5Xa0-taRMNiB:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/568c9801535b64bd771723be16deba3bfca6214a/examples/hardware_sim/BUILD.bazel#L101)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW It might be worth a comment here that it's safe to use `lcm` here because the  uses a nonsense URL and only transmits status messages?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20283)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
