### PR TITLE
[meshcat] Add sleep to Meshcat::Flush()

### PR DESCRIPTION
**Pull request by RussTedrake**
While using Meshcat::Flush() in my experiments, I saw the dreaded "you
should never see this message" message. After even more reading of the
uWebsockets code, it seems that drainage is not actually scheduled to
occur between loop->defer calls. My attempts to request drainage
directly also failed. I believe there are no better mechanisms
available in the public API than to simply sleep.

I've documented my attempts directly in the code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16256)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16256#-:-MrJDUZh6ymCIIOiR3xi:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: question about sleep lengh/iteration limit balance and responsiveness

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16256#-:-MrNiLw10ij_ryUCJX5C:b-eo0dwg)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/meshcat.cc, line 556 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16256#-MrNhYzZ0Ft2fM7_V7Dy:-MrNhYzZ0Ft2fM7_V7Dz:b-slh8u5) ([raw file](https://github.com/robotlocomotion/drake/blob/b4dee4988210bd6b7285d2e59ea54a166029c5ed/geometry/meshcat.cc#L556)):*
> ```cpp
>       main_backpressure = f.get();
>       if (main_backpressure > 0) {
>         std::this_thread::sleep_for(std::chrono::seconds(1));
> ```

I think this overall strategy is ok; I might consider making the hard-coded sleeps shorter and the iteration limit correspondingly larger. With the current values, you'll wait roughly half a second longer than you needed to. Maybe that is ok in context -- what do you think?

**Review by RussTedrake — COMMENTED** [review]
I agree with you (and was thinking the same in my time since opening the PR).  I've adjusted the balance.
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16256#-:-MrOK5Gb-DhtqlJ8Iqbx:b-dcys2b)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

___
*[geometry/meshcat.cc, line 556 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16256#-MrNhYzZ0Ft2fM7_V7Dy:-MrOKEO029HDBuXQEBJh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4dee4988210bd6b7285d2e59ea54a166029c5ed/geometry/meshcat.cc#L556)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I think this overall strategy is ok; I might consider making the hard-coded sleeps shorter and the iteration limit correspondingly larger. With the current values, you'll wait roughly half a second longer than you needed to. Maybe that is ok in context -- what do you think?
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: An excellent comment, by the way, and it's nice to see some error message armor actually pay off :-)

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16256#-:-MrOKe086-kv0j3eNq7d:b-bdfja1)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16256)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
