### PR TITLE
Remove VectorValue; instead use Value<BasicVector>

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Now that `Value<>` handles cloneable types natively, there is no benefit to this wrapper, and the distinction between `Value<BasicVector<T>*>` vs `VectorValue<T>` being _different types_ when downcasting was getting confusing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6187)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
"Unexpected termination of the channel"
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.
+@soonho-tri you are recently familiar with this perhaps, can you feature-review?

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6187#-:-Kl4AHsBXl6QFGb6RRiT:bnfp4nl)*

**Comment by sherm1** [comment]
I'm really happy to see the last of VectorValue! Thanks, @jwnimmer-tri. :lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6187#-:-Kl4LOu3odtbQsjHTSoE:b-wzsvbs)*

**Pull request merged**
