### PR TITLE
workspace: Update pybind11 fork to latest commit

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MJxjTU_9FSOCKqV3gT2:-MJxjTUa1YDHx7eYcxuW:b-kbw7ya) (no related file):*
Working: Requires:
https://github.com/RobotLocomotion/pybind11/pull/47

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MJxjcDi9aNusCow6wKh:b-qb6q7v)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[tools/workspace/pybind11/repository.bzl, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MJxjXt0ATClGlZ9K8PG:-MJxjXt14bTKL-DaRbB4:b3omefr) ([raw file](https://github.com/robotlocomotion/drake/blob/62bd2688f868e8cf32566fa71e7307925b150961/tools/workspace/pybind11/repository.bzl#L9)):*
> ```Starlark
> _REPOSITORY = "RobotLocomotion/pybind11"
> 
> _COMMIT = "5b56e5606cf7622c13e1a6224c702b25e676862f"
> ```

Working: Needs post-merge commit.

**Comment by EricCousineau-TRI** [comment]
FTR The changes to `*.cc` files naively use the following code within the deprecated constructor:
https://github.com/pybind/pybind11/blob/0b9acc40/include/pybind11/pybind11.h#L895

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MK0GAtl5iyRZouObrTL:-MK0GAtl5iyRZouObrTM:bdfcii7) (no related file):*
Working: Requires Mac testing.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
On the FTR: The comment didn't give me any insight into what I was seeing, it merely confused me. On the one hand, "naively using deprecated constructor" sounds bad, but this seems to work. So, do I rely on CI to tell me it's good/bad or am I supposed to do something proactive given the provided information? Given that this is the first time I've looked at our pybind infrastructure, I don't have that answer.

Otherwise, I'm sure this is fine and I'll simply wait for the upstream dependency before giving my stamp.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MK0PJ829VzHiQzPyuYn:b-s4ftsw)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Comment by EricCousineau-TRI** [comment]
The goal was to tell you it's a solution (and why that API was used) based on upstream (w/o upstream changes), and rely on CI to inform you whether or not it's a viable solution; it was meant to curtail questions like "why did you do this?".

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MK0GAtl5iyRZouObrTL:-MK1_F_t7b_P7EszdZgB:b-jf3l9i) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires Mac testing.
</blockquote></details>

Done. See: https://drake-jenkins.csail.mit.edu/job/mac-catalina-clang-bazel-experimental-everything-release/43/

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
I still don't understand the change. The only information that your FTR above gives that the code itself doesn't communicate is a) the word "naively" and b) a link. The code diff clearly communicates everything else in the sentence (see what happens when I omit the word naively).

> The changes to *.cc files use the following code within the deprecated constructor: https://github.com/pybind/pybind11/blob/0b9acc40/include/pybind11/pybind11.h#L895

I can easily, mechanically see the change in the code is perfectly described by that sentence, but it gives me no actionable knowledge. There is no hint as to the *why* to which you've alluded. I would presume that this change is *necessary*, but the need isn't clear.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MTfKhGU8_ZI6rheZQ-9:bjn9kh0)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MTfPdms5gaYZrXONIeZ:-MTfPdms5gaYZrXONIe_:b-cmimku) (no related file):*
What is the trajectory for this PR. As putative reviewer, I'm having a difficult time telling what its significance is or what it'll take to make CI happy.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MTfPdms5gaYZrXONIeZ:-MTfQEJI14qiqCvDsuyl:b-3ix5gv) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What is the trajectory for this PR. As putative reviewer, I'm having a difficult time telling what its significance is or what it'll take to make CI happy.
</blockquote></details>

Ah, sorry. For now, -@seancurtis-tri 

I need to fix things upstream, and basically just drag it into a corner. Will reassign once things work again.

I can involve you more if you want to be more directly involved (e.g. making the upstream updates); but if it's just me doing it, I'd prefer to minimize comms for now.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MTfPdms5gaYZrXONIeZ:-MTfR_Bk-h_e6hUKoOPZ:by38vsd) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry. For now, -@seancurtis-tri 

I need to fix things upstream, and basically just drag it into a corner. Will reassign once things work again.

I can involve you more if you want to be more directly involved (e.g. making the upstream updates); but if it's just me doing it, I'd prefer to minimize comms for now.
</blockquote></details>

I'm only here because you assigned this to me three months ago. I have no problem with being removed while everything else gets worked out. :)

---

**Review by sherm1 — COMMENTED** [review]
+@seancurtis-tri for both reviews (previously assigned but got unassigned?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MThjmtC8CWEruGBs2xo:b-bsxqtc)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Ah, nuts! Sorry, meant to add +(status: do not review) +(status: do not merge) 

-@seancurtis-tri for now

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MThl6_E2aJci5imXQqe:b-ejnu1o)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
Confirmed this passes on macsim (commit: 608f682b56).

+@seancurtis-tri for both reviews, pretty please?

Note that the changes to some pydrake arises due to this freshly incorporated commit:
https://github.com/RobotLocomotion/pybind11/blame/58d9205d/include/pybind11/pybind11.h#L950

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MUziaVZDMNid75wih4G:b-6elyot)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MJxjTU_9FSOCKqV3gT2:-MUziNaBCcmu8QtBENV1:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires:
https://github.com/RobotLocomotion/pybind11/pull/47
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MTfPdms5gaYZrXONIeZ:-MUziOF929NtnImekh-G:b-8a1b68) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm only here because you assigned this to me three months ago. I have no problem with being removed while everything else gets worked out. :)
</blockquote></details>

Done.
And good point :sweat_smile: 

---
___
*[tools/workspace/pybind11/repository.bzl, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14225#-MJxjXt0ATClGlZ9K8PG:-MUzi_UvAqQXyGC-FfE4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/62bd2688f868e8cf32566fa71e7307925b150961/tools/workspace/pybind11/repository.bzl#L9)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Needs post-merge commit.
</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
Note that CI on our pybind11 fork (pruned from CI) now passes:
image
https://github.com/RobotLocomotion/pybind11

**Comment by EricCousineau-TRI** [comment]
As a minor precaution, see Anzu-master-Drake-PR job 98

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MVIPxOPDbJ6kcNQrlIo:bmxilld)* status: needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
@ericcousineau-tri Did you still want single reviewer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MVIQ-nc6qMIeSK7olMo:bswtk5a)* status: needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
Yup, if you're OK with it!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MVIRaZR1KrSxN8iIrch:b-3d5x6t)* status: needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
(Will wait for 15min, then merge barring any updates hehe)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MVISEJL0n_rm9_I7Qz0:bbpe5zc)* status: needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
Onwards! +(status: single reviewer ok) 

(And thank you for reviewing!)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14225#-:-MVIZHwB4hVotSaxQ9t1:bqh3l68)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
