### PR TITLE
acrobot: Fix spong LCM to actually work

### LINKED ISSUE #14524: spong_controller_w_lcm does not receive LCM
At some point, possibly #10476, `//examples/acrobot:spong_controller_w_lcm` (in concert with its friend `//examples/acrobot:run_plant_w_lcm`) stopped working.  We didn't notice because they lack a test :upside_down_face: .

The symptom is that the controller always commands zero torque, leaving the visualized plant swaying morosely forever.

Per [this slack thread[(https://app.slack.com/client/T0JNB2DS4/C0JNB2E3S/thread/C0JNB2E3S-1610547810.098800) the most likely cause of this is that `HandleSubscriptions` in a wall clock loop at `spong_controller_w_lcm.cc`:70 alone is not enough to receive the acrobot state.  The current LCM infrastructure requires creating and stepping a simulator to advance the LCM receiver state.

This issue was discovered while writing a README for the acrobot example, and will be referenced from that document.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Previously, we were never decoding the received xhat messages.

Closes #14524.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This PR doesn't add a regression test (yet?).

One obvious candidate for adding a test is to run the two separate processes from a python test launcher, and monitor that in python to assert that the acrobot reached the upright position.  However, that would mean transmitting LCM on the real network (so the two processes can communicate), which we have a pretty strong rule against doing except in the most extreme circumstances.  It makes CI super flaky.  We always want to use within-process memq transport.

So, I could factor each of the two `DoMain()` functions into a library with header file, and then have a C++ test program that ran them concurrently in separate threads, and there check that the acrobot reached upright.  I am not sure if that's worth it.

\CC @ggould-tri for thoughts

**Review by ggould-tri — COMMENTED** [review]
It's sad that we can't do IPC in a test.  None of the workarounds I can think of much improve the situation.  And the lack of updm-multicast routing by default means udpm == real network traffic no matter what.

The threaded solution is the technically correct workaround but as you say it's a bit goofy.  On the other hand LCM+Systems interaction is sufficiently fiddly that this sort of problem is definitely possible and could easily slip past us again without a test.

I think I come down on the side of doing the threaded test.  The real value of this example is to show Drake users how to separate control and simulation across a process/lcm boundary.  The knowledge of how correctly to test that arrangement is inherently part of what we want to teach them.

Alternatively, you could record an lcm log from running this correctly and then test each of the halves with a mock LCM attached to a `DrakeLcmLog` on that recorded file, checking in each case that the half sends nonzero output.  I *think* that would still exercise the bug if run on the old code.  But it might actually be even worse than your proposal.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525#-:-MQwup7R9aWlznY57APs:b-gs68ve)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[examples/acrobot/spong_controller_w_lcm.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14525#-MQwuQFg6yJm8M5c9O5t:-MQwuQFg6yJm8M5c9O5u:be8pcm) ([raw file](https://github.com/robotlocomotion/drake/blob/118935e096bef3990f88db23aaf8ae34ef5bd6ff/examples/acrobot/spong_controller_w_lcm.cc#L31)):*
> ```cpp
>               "Number of seconds to run (default: infinity).");
> DEFINE_double(realtime_factor, 1.0,
>               "Playback speed.  See documentation for "
> ```

I have no idea what the "playback speed" of a controller is, nor does the cited simulator doc make it any clearer (because the user who sees this message has no reason to believe they have asked for anything to do with a simulator).

**Comment by jwnimmer-tri** [comment]
>  The real value of this example is to show Drake users how to separate control and simulation ...

You make an interesting point.  Instead of a surgical fix, perhaps I should rework the entire message to actually demonstrate best practices, which would make this particular failure mode test-able.  The fact that there's not even a unit test of spong + plant merged into a single direct diagram is a giant red flag already.

I will give it some thought, though not soon.  If this patch helps you with your ongoing PRs, we can look into what it takes to help nudge this one along absent a rewrite.

**Review by ggould-tri — COMMENTED** [review]
I don't think this affects my PR train:  I am happy to leave the README with a TODO on this -- we've gotten along okay without any readme at all, so one that references an open issue is hardly a matter for complaint.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525#-:-MR03Y6q9R8lHPCKYOMn:btsh4wb)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[examples/acrobot/spong_controller_w_lcm.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14525#-MQwuQFg6yJm8M5c9O5t:-MS4mt5lE8BF7jBPVU_L:bvqlkn0) ([raw file](https://github.com/robotlocomotion/drake/blob/118935e096bef3990f88db23aaf8ae34ef5bd6ff/examples/acrobot/spong_controller_w_lcm.cc#L31)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I have no idea what the "playback speed" of a controller is, nor does the cited simulator doc make it any clearer (because the user who sees this message has no reason to believe they have asked for anything to do with a simulator).
</blockquote></details>

Done.

(This was a misguided attempt to allow the timeout for the controller to match the timeout of the plant, in case the user set a non-unity realtime rate for the plant process.  Leaving it at "doctor, it hurts when I do this" is probably sufficient.)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.

I think the gap from here (fixed bug) to showing Best Practices (how to tests, refactor the whole files) is too large for this PR.  It seems worthwhile to unnbreak it first.  If someone decides that improving our tutorials is worth a ticket, they can carry that torce forward, but for now it's beyond my scope.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: Okay, I think that's fine for now.  One request below.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525#-:-MS8LmKr9k_HNihMDKI_:b-famrp0)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14525#-MS8M-CO0nRVdmr57GAn:-MS8M-CP3XOl6mzJNvXZ:b-jtbyt6) (no related file):*
minor:  The README says that this binary is broken; you should remove the warning there.

---

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule (tomorrow), please.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14525#-:-MS_Hpry4IYGPpvot_y1:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

**Pull request merged**
