### PR TITLE
Tidy up LcmPublisherSystemTest.

### PR DESCRIPTION
**Pull request by liangfok**
This was extracted from #4731.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4743)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@sammy-tri for platform review please.

Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4743#-:-KaClIhdkP114xxnX0-2:bjege30)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4743#-:-KaCmbqQO9jBPAeccfbb:bnfp4nl)*

**Comment by liangfok** [comment]
This PR is now awaiting @sammy-tri's platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4743#-:-KaDhJ52te7RCC9Fw7DR:bnfp4nl)*

**Pull request merged**
