### PR TITLE
Moved header files into a directory that matches their namespaces.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3077)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review please.
+@ggould-tri for platform review please.

Thanks!

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KORFo9Xtk8nXXIsM2f7:b1m7k1p)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOXwGFslTbAyjg0tVcH:bvi7gqa)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOXx6L1hDfOf6CK9fqz:b-3f2dwx)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOe8n4ytHSnVGl4Rjd0:bnfp4nl)*

**Comment by jhoare** [comment]
Looks to me like the "drake_ros_systems" folder/package should be "drake_ros" or the headers should be in a "drake_ros_systems" subfolder. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOe8dZ0FQNAD-MAJnKm:b89s4c5)*

**Comment by liangfok** [comment]
Good point. I will move them into `drake/ros/systems`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOeRvvoqP7PGxKKh6zV:b7jz3nz)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOfNXTYvc9VvWUvbMdL:b-ujxhqu)*

**Comment by liangfok** [comment]
This PR passed all CI tests. Now waiting for feature review from @jhoare .

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOfWy7ruysQ_55eq_42:b-945rnm)*

**Comment by jhoare** [comment]
I was imagining it to be drake_ros_systems rather than drake/ros/systems to match the name of the ros package, but drake/ros/systems does match the structure of drake itself. So :lgtm: 

---

Reviewed 5 of 16 files at r1, 11 of 11 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOfXX_aFSWweSHZq8Vz:b-uyo8y3)*

**Comment by liangfok** [comment]
Yeah, I decided to adopt Drake's C++ style guide and thus think it makes sense to also adopt Drake's style of making the directory structure match the namespaces as closely as possible. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3077#-:-KOfZRYO4fpdBRApqtYg:b8hsovx)*

**Pull request merged**
