### PR TITLE
Fix runAtlasWalking on OSX in Release mode (#2165)

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes https://github.com/RobotLocomotion/drake/issues/2165.
~~Hopefully also fixes https://github.com/RobotLocomotion/drake/issues/3147 (pending CI build results). Note that `runAtlasManip` still doesn't pass on OSX Release (don't know about other configurations), but that's because the robot flips out, not because of a crash, so I think a new issue should be opened for that.~~

Crash happened when `param_sets` got move-assigned (i.e. assigned from an rvalue), but not when it was copy-assigned from an lvalue (as demonstrated by https://github.com/rdeits/drake/commit/6de25e992a321521af21cb75ac90314e248409e4). There are real differences between the implementation of a `std::map`'s move assignment operator and its copy assignment operator, so it's not that weird that there is a difference in behavior.

StackOverflow question that describes the same behavior: https://stackoverflow.com/questions/38403189/move-assigning-a-stdmap-with-an-aligned-value-type-segfaults. I was able to reproduce their minimal example on my machine, and it only results in a segfault in release mode, not in debug, consistent with what we're seeing. This example runs fine with O0, but segfaults with O1, O2 and O3.

Here's a modified version of that example that includes Eigen:

```C++
#include <iostream>
#include <map>
#include <Eigen/Core>

using Eigen::Vector4d;

struct Foo {
  double a;
  Vector4d b; // fixed size vectorizable type
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

template <typename Key, typename T>
using eigen_aligned_map =
std::map<Key, T, std::less<Key>, Eigen::aligned_allocator<std::pair<Key const, T> > >;

int main() {
//  std::map<int, Foo> m{{0, {1., Vector4d::Random()}}};
//  std::map<int, Foo> n{{1, {1., Vector4d::Random()}}};

  eigen_aligned_map<int, Foo> m{{0, {1., Vector4d::Random()}}};
  eigen_aligned_map<int, Foo> n{{1, {1., Vector4d::Random()}}};

  std::cout << "GOT HERE" << std::endl;
  m = std::move(n);  //  segfault happens here
  std::cout << "GOT HERE TOO" << std::endl;
}
```

Strangely enough, for this second example, things are fine for O0 *and* O1, but bad for O2 and O3, regardless of whether I use `std::map` or `eigen_aligned_map`. So following Eigen's standard rules for using fixed-size vectorizable types in STL containers (https://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html) does not work for this case.

I'm not sure whose bug this is (Eigen's or Clang's). I'll file a bug report with Eigen first, see what they say about it.

This PR works around the issue by using the copy-assignment operator instead, as @rdeits noticed already.

In addition, there were some pretty pervasive Eigen alignment issues. These may have contributed to #3147 as well.

Also adds `drake::eigen_aligned_std_map`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3462)

### CODE REVIEW

**Comment by tkoolen** [comment]
I think I may not have permission to trigger experimental builds. Could someone trigger all experimental matlab, matlab-open-source, matlab-release, and matlab-debug builds please?

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-open-source please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-documentation please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab-open-source please

**Comment by tkoolen** [comment]
* `linux-gcc-experimental-coverage-matlab-release`: relevant failures, shattering my hope that https://github.com/RobotLocomotion/drake/issues/3147 would also be fixed by this pull request. I'll disable those tests again when `NOT ${CMAKE_BUILD_TYPE} STREQUAL "Debug" AND UNIX`
* mac-clang-experimental-matlab-open-source: `examples/SimpleDoublePendulum/runPassiveURDF` timeout; not my fault.
* windows-msvc-ninja-64-experimental-matlab-release: `examples/Pendulum/runLQR` timeout; not my fault.

**Comment by tkoolen** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-release please

**Comment by tkoolen** [comment]
@jwnimmer-tri -bot linux-gcc-experimental-coverage-matlab-release pretty please with sugar on top :-)

**Comment by tkoolen** [comment]
By the way, `linux-gcc-experimental-coverage-matlab-release` seems to be badly named, since it's a Debug build.

**Comment by jwnimmer-tri** [comment]
Huh, I have no idea why Jenkins doesn't believe you.  @david-german-tri can we fix Twan's bits?

@drake-jenkins-bot linux-gcc-experimental-coverage-matlab-release please

**Comment by jwnimmer-tri** [comment]
Ah, there is no such build name.  Try again, @tkoolen?

**Comment by tkoolen** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage-matlab please

**Comment by tkoolen** [comment]
Alright, that was it. I was confused because https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-gcc-experimental-coverage-matlab-release-35&field2=buildstarttime&compare2=84&value2=now uses linux-gcc-experimental-coverage-matlab-release.

**Comment by RussTedrake** [comment]
great to see this!  @tkoolen, is your plan also to re-enable the tests on debug mode and non-unix?

**Comment by tkoolen** [comment]
I looked at Linux debug yesterday for an hour or two, but haven't been able
to figure it out yet. I'll continue looking (but maybe after the weekend).

**Comment by tkoolen** [comment]
Eigen bug report: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1297.

**Comment by tkoolen** [comment]
Eigen maintainer tested Clang on Ubuntu, various configurations, could not reproduce; recommended me to submit an Xcode bug report, which I did.

**Comment by tkoolen** [comment]
Another Eigen maintainer also opened an issue with LLVM (instead of Apple Xcode/developer tools): https://llvm.org/bugs/show_bug.cgi?id=30449.

**Comment by tkoolen** [comment]
@rdeits, could I ask you for one more feature review?
@jwnimmer-tri, could I ask you to be the platform reviewer, since your previous work on Eigen STL stuff is at least tangentially related to some of the changes I've made?

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-:-KS7mWGFhmFZ95_29AWh:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
A few small things.

Also be careful that the struck-through text in the OP doesn't close 3147 (or I guess just reopen if it does).

---

Reviewed 11 of 13 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/eigen_stl_types.h, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7oLZkK9-Ds3rj3Svx:-KS7oLZlut7Tb473F0Om:b-exxnki) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/common/eigen_stl_types.h#L21)):*
> ```objc
> using eigen_aligned_std_map =
>     std::map<Key, T, std::less<Key>,
>              Eigen::aligned_allocator<std::pair<Key const, T>>>;
> ```

What about a simple unit test case (duplicate the unordered_map one) to confirm that this typedef is correct?  A lot of the uses are in conditionally-compiled code.

---

*[drake/systems/controllers/controlUtil.h, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7qok1x3NG596Zv1aK:-KS7qok2dHil-apghBkD:b70p1k4) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/controlUtil.h#L4)):*
> ```objc
> 
> #include <math.h>
> #include <Eigen/Dense>
> ```

Nope, should have stayed where it was.  A blank line between std and Eigen includes will let clang-format preserve this.  #2269 would also help.

---

*[drake/systems/controllers/QPCommon.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7rox4JfYN2v7QTxyE:-KS7rox5GnRGGhonbKch:b-l4if5q) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/QPCommon.h#L172)):*
> ```objc
>   }
> 
>   EIGEN_MAKE_ALIGNED_OPERATOR_NEW
> ```

BTW I am not seeing why this is required?  Abundance of caution / consistency?

---

*[drake/util/yaml/yamlUtil.cpp, line 326 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7pMy3GVIm0dme3iuo:-KS7pMy40wcsexDdheFd:bxxt61a) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/util/yaml/yamlUtil.cpp#L326)):*
> ```cpp
> }
> 
> drake::eigen_aligned_std_map<std::string, QPControllerParams>
> ```

BTW `QPControllerParams` doesn't use`EIGEN_MAKE_ALIGNED_OPERATOR_NEW`; why does a collection of it need this map type -- just an abundance of caution?  Would you prefer to add the `_NEW` onto it also just in case?

---

*[drake/util/yaml/yamlUtil.h, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7pzrG4aIVwWj5rxAV:-KS7pzrHXIqPvhSTkC-h:b-3x17r0) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/util/yaml/yamlUtil.h#L10)):*
> ```objc
> #include "drake/systems/controllers/QPCommon.h"
> #include "drake/systems/plants/RigidBodyTree.h"
> #include "yaml-cpp/yaml.h"
> ```

Should remain prior to all drake includes (third-party library) but follow the stdlib includes.

```
...
#include <map>
 
#include "yaml-cpp/yaml.h"

#include "drake/common/eigen_stl_types.h"
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-:-KS7tCP3q2s1VP47EzJ-:b4gufmd)*

**Comment by tkoolen** [comment]
I was going to use this PR as an experiment for that :-)

---

Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/eigen_stl_types.h, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7oLZkK9-Ds3rj3Svx:-KS86F5MmeVRrr8cBWBv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/common/eigen_stl_types.h#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> What about a simple unit test case (duplicate the unordered_map one) to confirm that this typedef is correct?  A lot of the uses are in conditionally-compiled code.
</details>
Done.

---

*[drake/systems/controllers/controlUtil.h, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7qok1x3NG596Zv1aK:-KS86wXE1scinMGLoQyz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/controlUtil.h#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Nope, should have stayed where it was.  A blank line between std and Eigen includes will let clang-format preserve this.  #2269 would also help.
</details>
Done.

---

*[drake/systems/controllers/QPCommon.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7rox4JfYN2v7QTxyE:-KS876SD1c0KHtP2hlWT:bcg1gtg) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/QPCommon.h#L172)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I am not seeing why this is required?  Abundance of caution / consistency?
</details>
`Vector6d` is fixed-size vectorizable.

---

*[drake/util/yaml/yamlUtil.cpp, line 326 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7pMy3GVIm0dme3iuo:-KS87S86sE-zDO2nAfWS:b-8dqqsq) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/util/yaml/yamlUtil.cpp#L326)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW `QPControllerParams` doesn't use`EIGEN_MAKE_ALIGNED_OPERATOR_NEW`; why does a collection of it need this map type -- just an abundance of caution?  Would you prefer to add the `_NEW` onto it also just in case?
</details>
QPControllerParams *does* use EIGEN_MAKE_ALIGNED_OPERATOR_NEW (and it should).

---

*[drake/util/yaml/yamlUtil.h, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7pzrG4aIVwWj5rxAV:-KS87oAwB9gCX7nHNUN4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/util/yaml/yamlUtil.h#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Should remain prior to all drake includes (third-party library) but follow the stdlib includes.
> 
> ```
> ...
> #include <map>
>  
> #include "yaml-cpp/yaml.h"
> 
> #include "drake/common/eigen_stl_types.h"
> ...
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-:-KS854FfP1CBk93FBLtG:bn8vegh)*

**Comment by rdeits** [comment]
Review status: 11 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Atlas/CMakeLists.txt, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS8Agk7IXk7woVnsm51:-KS8Agk8p6ZMHIP3kvGJ:b-irl3c3) ([raw file](https://github.com/robotlocomotion/drake/blob/a84ef5e2105fa922c0078fa537cd17db548d07a5/drake/examples/Atlas/CMakeLists.txt#L28)):*
> ```CMake
> drake_add_matlab_test(NAME examples/Atlas/runCOMFixedPointSearch OPTIONAL bullet gurobi COMMAND runCOMFixedPointSearch)
> 
> drake_add_matlab_test(NAME examples/Atlas/runDRCDoorTask REQUIRES iris mosek COMMAND runDRCDoorTask)
> ```

I'm not familiar with the new drake_add_matlab_test, but I suspect this test should be marked `SIZE large`, right?

---

*[drake/examples/Valkyrie/CMakeLists.txt, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS8ArunyX2y0JRFYU1A:-KS8ArunyX2y0JRFYU1B:b5o50i8) ([raw file](https://github.com/robotlocomotion/drake/blob/a84ef5e2105fa922c0078fa537cd17db548d07a5/drake/examples/Valkyrie/CMakeLists.txt#L8)):*
> ```CMake
> 
> if (NOT ${CMAKE_BUILD_TYPE} STREQUAL "Debug" AND UNIX) # FIXME: see #3147.
>   drake_add_matlab_test(NAME examples/Valkyrie/runValkyrieWalking REQUIRES gurobi lcm libbot yaml-cpp COMMAND runValkyrieWalking)
> ```

again, presumably should be `SIZE large`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462)*

**Comment by jwnimmer-tri** [comment]
Awesome.

:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/controllers/QPCommon.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7rox4JfYN2v7QTxyE:-KS8Glll-ixmEB14guFJ:bpr6a30) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/QPCommon.h#L172)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> `Vector6d` is fixed-size vectorizable.
</details>
Okay.  It wasn't listed here:
https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html

BTW Is there a better list of types require the special treatment?

---

*[drake/util/yaml/yamlUtil.cpp, line 326 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7pMy3GVIm0dme3iuo:-KS8GOr-8cWwtxllGkeP:b-hb28lu) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/util/yaml/yamlUtil.cpp#L326)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> QPControllerParams *does* use EIGEN_MAKE_ALIGNED_OPERATOR_NEW (and it should).
</details>
Sorry!  I think I looked at my local checkout of master to see, which of course was not useful.  Marking resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-:-KS8GW0adgbl8yyJeUqd:b6smqe4)*

**Comment by tkoolen** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Atlas/CMakeLists.txt, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS8Agk7IXk7woVnsm51:-KS9ItHHds6BXnhesq14:bkz3ire) ([raw file](https://github.com/robotlocomotion/drake/blob/a84ef5e2105fa922c0078fa537cd17db548d07a5/drake/examples/Atlas/CMakeLists.txt#L28)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary>
> I'm not familiar with the new drake_add_matlab_test, but I suspect this test should be marked `SIZE large`, right?
</details>
See the table here: https://testing.googleblog.com/2010/12/test-sizes.html for what the test sizes mean (we're using those definitions). `drake_add_matlab_test` uses medium as the default. medium is up to 300 seconds. `runDRCDoorTask`took about 1 minute on the build server (https://drake-cdash.csail.mit.edu/viewTest.php?onlypassed&buildid=119901), so this should be alright. If it takes 5 times as long, something may actually be wrong.

---

*[drake/examples/Valkyrie/CMakeLists.txt, line 8 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS8ArunyX2y0JRFYU1A:-KS9m83z6Mll_Aidhwdm:bojllx7) ([raw file](https://github.com/robotlocomotion/drake/blob/a84ef5e2105fa922c0078fa537cd17db548d07a5/drake/examples/Valkyrie/CMakeLists.txt#L8)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary>
> again, presumably should be `SIZE large`?
</details>
This one I am going to change, because `runAtlasWalking` is also large (and needed to be).

---

*[drake/systems/controllers/QPCommon.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7rox4JfYN2v7QTxyE:-KS9JP04gDLoGINEF3TG:b-imb9vc) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/QPCommon.h#L172)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Okay.  It wasn't listed here:
> https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html
> 
> BTW Is there a better list of types require the special treatment?
</details>
"An Eigen object is called "fixed-size vectorizable" if it has fixed size and that size is a multiple of 16 bytes."
So since Vector2d is fixed-size vectorizable, VectorNd is fixed-size vectorizable for any positive integer N.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/QPCommon.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7rox4JfYN2v7QTxyE:-KSBU0rHfjA2JBWMsmS6:b-tsn2qr) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/QPCommon.h#L172)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> "An Eigen object is called "fixed-size vectorizable" if it has fixed size and that size is a multiple of 16 bytes."
> So since Vector2d is fixed-size vectorizable, VectorNd is fixed-size vectorizable for any positive integer N.
> 
</details>
Ah.  I also see now the list is "Examples include" and not all-inclusive.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462)*

**Comment by tkoolen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/QPCommon.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3462#-KS7rox4JfYN2v7QTxyE:-KSBbtsqJMh3jf3FfzoF:b-lpsytz) ([raw file](https://github.com/robotlocomotion/drake/blob/2683b3d6777ad9077bd76bb66bed0aedf73185be/drake/systems/controllers/QPCommon.h#L172)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Ah.  I also see now the list is "Examples include" and not all-inclusive.  Thanks!
</details>
Oops, I meant Vector{2 * N}d in the statement above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3462)*

**Comment by tkoolen** [comment]
@jwnimmer-tri, the strikethrough experiment failed :-)

**Comment by jwnimmer-tri** [comment]
Yeah, I saw that.  Ah well, TIL.

**Pull request merged**
