### PR TITLE
Implement AffineBall::DoAddPointInNonnegativeScalingConstraints.

### PR DESCRIPTION
**Pull request by cohnt**
+@hongkai-dai for feature review, if you have the time

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/affine_ball.cc` line 248 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6YHBKm4ulR3xl0066u:-O6YHBKnB50QVlMuJXsM:bugznja) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f66032d4306cdf776c461f2d08ebbd1e462de0c/geometry/optimization/affine_ball.cc#L248)):*
> ```cpp
>   // The constraint is Ax+b∈(c't+d)S, which can be written Ax+b=(c't+d)(By+C),
>   // where we use C to refer to the center of the AffineBall, which simplifies
>   // to -Ax+By+Cs=b, s=c't+d, and ||y||² ≤ s².
> ```

Curious why introducing `s` here, you could write it as
```
-Ax + By + C(c't + d) = b
c't + d >= |y|
```
___
*[`geometry/optimization/test/affine_ball_test.cc` line 491 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6YNavJ9BFigaYd1tss:-O6YNavJ9BFigaYd1tst:bi9yjw3) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f66032d4306cdf776c461f2d08ebbd1e462de0c/geometry/optimization/test/affine_ball_test.cc#L491)):*
> ```cpp
>       ab.AddPointInNonnegativeScalingConstraints(&prog, x, t);
> 
>   // Extract the slack variables. According to the method implementation, the
> ```

This tests the internal implementation of DoAddPointInNonnegativeScalingConstraint. I would argue that the internal implementation is not unique, and we should not fixated on one implementation.

I would suggest to test it in a different way. We can solve many optimization programs with different cost, and check if the cost and the optimal `x, t` match with the expected value.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_ball.cc` line 248 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6YHBKm4ulR3xl0066u:-O6agRhxEb4p1tr-2MpF:b-o7vuhc) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f66032d4306cdf776c461f2d08ebbd1e462de0c/geometry/optimization/affine_ball.cc#L248)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why introducing `s` here, you could write it as
```
-Ax + By + C(c't + d) = b
c't + d >= |y|
```
</blockquote></details>

Good catch! Done.
___
*[`geometry/optimization/test/affine_ball_test.cc` line 491 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6YNavJ9BFigaYd1tss:-O6bU6OR5bTbWvo8xi-r:biq3qfh) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f66032d4306cdf776c461f2d08ebbd1e462de0c/geometry/optimization/test/affine_ball_test.cc#L491)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This tests the internal implementation of DoAddPointInNonnegativeScalingConstraint. I would argue that the internal implementation is not unique, and we should not fixated on one implementation.

I would suggest to test it in a different way. We can solve many optimization programs with different cost, and check if the cost and the optimal `x, t` match with the expected value.
</blockquote></details>

Even better, I can add constraints fixing the value of `x` and `t` to be values which are feasible, and then just verify that the optimization problem is feasible. (I had done this in #21874.)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-:-O6gMuZs2qhL6PTC1h55:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_ball.cc` line 262 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6gMc5w5gchh2TIiO9A:-O6gMc5w5gchh2TIiO9B:bi1f1q6) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ec81f2324c2b8f561231d697984e9783c2e29c1/geometry/optimization/affine_ball.cc#L262)):*
> ```cpp
>       prog->AddLinearEqualityConstraint(constraint_A, b, {x, y, t}));
> 
>   // The third constraint is that ||y||² ≤ (c't+d)², which can be written as
> ```

This is the second constraint?
___
*[`geometry/optimization/test/affine_ball_test.cc` line 491 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6YNavJ9BFigaYd1tss:-O6gMrnh3ZTAuCMya-Br:b-p56br7) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f66032d4306cdf776c461f2d08ebbd1e462de0c/geometry/optimization/test/affine_ball_test.cc#L491)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Even better, I can add constraints fixing the value of `x` and `t` to be values which are feasible, and then just verify that the optimization problem is feasible. (I had done this in #21874.)
</blockquote></details>

Looks great! Thanks!

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_ball.cc` line 262 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6gMc5w5gchh2TIiO9A:-O6gNIjW2lQVA5_2aydD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ec81f2324c2b8f561231d697984e9783c2e29c1/geometry/optimization/affine_ball.cc#L262)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This is the second constraint?
</blockquote></details>

Done.
___
*[`geometry/optimization/test/affine_ball_test.cc` line 491 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O6YNavJ9BFigaYd1tss:-O6gNLdV79Ajkih8E_f6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f66032d4306cdf776c461f2d08ebbd1e462de0c/geometry/optimization/test/affine_ball_test.cc#L491)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Looks great! Thanks!
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for platform review please, thanks!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-:-O7-tMsRCL4tEYj1gk64:b-2hj6f6)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/affine_ball.cc` line 217 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O701ffU3anZEFBThl6R:-O707L1E-BqjdxrI05pG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/64594ffe97077ec2c3cba85a26eb5e6a76f77d26/geometry/optimization/affine_ball.cc#L217)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`geometry/optimization/test/affine_ball_test.cc` line 504 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O70310L3XakCCbXpVgG:-O707RszEieR28NGy3_i:bb5esia) ([raw file](https://github.com/RobotLocomotion/drake/blob/64594ffe97077ec2c3cba85a26eb5e6a76f77d26/geometry/optimization/test/affine_ball_test.cc#L504)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo -- double comment markers -- some sort of auto-formatting gone wrong?
</blockquote></details>

Yep! Removed outright due to the following comment.
___
*[`geometry/optimization/test/affine_ball_test.cc` line 513 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21898#-O703A7f7kBvzgWJ_Igb:-O707RKb9Djnt-GT9P1s:bss4a2b) ([raw file](https://github.com/RobotLocomotion/drake/blob/64594ffe97077ec2c3cba85a26eb5e6a76f77d26/geometry/optimization/test/affine_ball_test.cc#L513)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Commented-out code.
</blockquote></details>

Removed.

**Review by cohnt — COMMENTED** [review]
> Dismissed @hongkai-dai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21898)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai

**Pull request merged**
