### PR TITLE
RgbdCamera, VtkUtil: Small refactoring

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
I took a change for MakeVTKInstanceArray from #6458 which @EricCousineau-TRI wrote and closed without being merged and put it into VtkUtil since I found it would be useful.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6498)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@ericcousineau-tri  feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-:-KnulpyRVIXLLWc4qzYm:b6wtgpx)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: pending discussion comments. Thanks!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 348 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-KnutllEixn6IneOAKhv:-KnutllFT2xgjDdLTl7-:b-xyut03) ([raw file](https://github.com/robotlocomotion/drake/blob/88907e2a41ea89d829575e5a19607a66b0d039a5/drake/systems/sensors/rgbd_camera.cc#L348)):*
> ```cpp
>       kCameraFixed(fix_camera), color_palette_(tree.bodies.size()) {
>   if (!show_window) {
>     for (auto& window : VtkUtil::MakeVtkPointerArray(color_depth_render_window_,
> ```

BTW Would it be possible to add `using VtkUtil::MakeVtkPointerArray` to make it a little more brief?

---

*[drake/systems/sensors/vtk_util.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-KnuuTtNH7AH-sT16AtO:-KnuuTtONs3LMLVamea7:b7w0oqg) ([raw file](https://github.com/robotlocomotion/drake/blob/88907e2a41ea89d829575e5a19607a66b0d039a5/drake/systems/sensors/vtk_util.h#L24)):*
> ```objc
> 
> /// Utility class for the VTK library.
> class VtkUtil {
> ```

nit I believe the style guide mentions that we should avoid using purely static classes for grouping methods.
https://google.github.io/styleguide/cppguide.html#Nonmember,_Static_Member,_and_Global_Functions

Would it be possible to make this a namespace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-:-Knuv4dZUFwcFjlMBFnD:bkcheqa)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 348 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-KnutllEixn6IneOAKhv:-KnwmV6XOUGfc9azOBJO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/88907e2a41ea89d829575e5a19607a66b0d039a5/drake/systems/sensors/rgbd_camera.cc#L348)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Would it be possible to add `using VtkUtil::MakeVtkPointerArray` to make it a little more brief?
</blockquote></details>

Done.

---

*[drake/systems/sensors/vtk_util.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-KnuuTtNH7AH-sT16AtO:-KnwmYvM2kieVT3p-UWa:bt6h0zw) ([raw file](https://github.com/robotlocomotion/drake/blob/88907e2a41ea89d829575e5a19607a66b0d039a5/drake/systems/sensors/vtk_util.h#L24)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit I believe the style guide mentions that we should avoid using purely static classes for grouping methods.
https://google.github.io/styleguide/cppguide.html#Nonmember,_Static_Member,_and_Global_Functions

Would it be possible to make this a namespace?
</blockquote></details>

Thanks for catching this. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498)*

**Comment by kunimatsu-tri** [comment]
+@ggould-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-:-KoIDqwUAu_B0poxrHTh:bdmqfp3)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-:-KoIQ-NiqyGOMKTQYGkf:bnfp4nl)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/vtk_util.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-KnuuTtNH7AH-sT16AtO:-KoO1aqMp_y3aMhif7n3:bu93d5a) ([raw file](https://github.com/robotlocomotion/drake/blob/88907e2a41ea89d829575e5a19607a66b0d039a5/drake/systems/sensors/vtk_util.h#L24)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Thanks for catching this. Done.
</blockquote></details>

Eric is on vacation and so can't close this.  I am dismissing him from the discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/vtk_util.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6498#-KnuuTtNH7AH-sT16AtO:-KoO4dhf274wN5iOYC8i:bo207ic) ([raw file](https://github.com/robotlocomotion/drake/blob/88907e2a41ea89d829575e5a19607a66b0d039a5/drake/systems/sensors/vtk_util.h#L24)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Eric is on vacation and so can't close this.  I am dismissing him from the discussion.
</blockquote></details>

Thanks @ggould-tri.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6498)*

**Pull request merged**
