### PR TITLE
[doc] Add release notes v1.22.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.22.0.md` line 24 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgFcuWGC8Vg2234aAoz:-NgFcuWH3LQwz1vvV1kh:b-3y64uh) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d3f695ad08f9b09d2b4745edce2ea8231dc7d91/doc/_release-notes/v1.22.0.md#L24)):*
> ```Markdown
> 
> * In MultibodyPlant, automatically-added floating joint names no longer have a
>   ``$world_`` prefix ([#20253][_#20253]).
> ```

BTW would be good to mention this also in the Multibody New Features section. Wording something like: "Added floating joints for free bodies are given the same name as the free body if possible, with underscores prepended if necessary to avoid name clashes (#20253)"

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.22.0.md` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgKKW-RBiqPHWoEFArQ:-NgKKW-RBiqPHWoEFArR:b-96a7j0) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d3f695ad08f9b09d2b4745edce2ea8231dc7d91/doc/_release-notes/v1.22.0.md#L91)):*
> ```Markdown
> * Add more error checks when loading ``*.vtk`` files ([#20240][_#20240])
> * RenderEngineGltfClient improves how input glTFs are handled w.r.t. scene merging and extensions ([#20184][_#20184])
> * TBD(jwnimmer-tri) "Add DiscreteContactData" doesn't make sense as a release note; what should go here ([#20209][_#20209])
> ```

FYI, the issue that #20209 fixed is that computing contact results between *two rigid bodies* may incorrectly aborts when a deformable body is present and in contact. Even though deformables are excluded from release notes, I think this may still be worth noting because the apparent symptom is not directly related to deformables.

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.22.0.md` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgJxJaaEsasnvP3BG_B:-NgJxJaaEsasnvP3BG_C:b2prrct) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d3f695ad08f9b09d2b4745edce2ea8231dc7d91/doc/_release-notes/v1.22.0.md#L92)):*
> ```Markdown
> * RenderEngineGltfClient improves how input glTFs are handled w.r.t. scene merging and extensions ([#20184][_#20184])
> * TBD(jwnimmer-tri) "Add DiscreteContactData" doesn't make sense as a release note; what should go here ([#20209][_#20209])
> * TBD(jwnimmer-tri) "Implements MultibodyTreeSystem::SetDefaultParameters. This change means that model default values can now change post-Finalize, and those changes will be reflected in new default contexts." doesn't seem clear enough. What EXACTLY should go in the release notes? ([#20307][_#20307])
> ```

The only user facing change is a bug fix that prompted the work, "Calls to JointActuator::set_default_gear_ratio()/set_default_rotor_inertia() are now reflected in default contexts created after Finalize()" or something like that. The commit is mostly to explain the framework for any dev trying to implement similar default values. 



_Code quote:_
```Markdown
* TBD(jwnimmer-tri) "Implements MultibodyTreeSystem::SetDefaultParameters. This change means that model default values can now change post-Finalize, and those changes will be reflected in new default contexts." doesn't seem clear enough. What EXACTLY should go in the release notes? ([#20307][_#20307])
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.22.0.md` line 24 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgFcuWGC8Vg2234aAoz:-NgOpHnQCIGVDvg9pF0L:bpw41qf) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d3f695ad08f9b09d2b4745edce2ea8231dc7d91/doc/_release-notes/v1.22.0.md#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would be good to mention this also in the Multibody New Features section. Wording something like: "Added floating joints for free bodies are given the same name as the free body if possible, with underscores prepended if necessary to avoid name clashes (#20253)"
</blockquote></details>

Done (below).
___
*[`doc/_release-notes/v1.22.0.md` line 91 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgKKW-RBiqPHWoEFArQ:-NgOpKsnDwP30GT78pO8:bpzlbv6) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d3f695ad08f9b09d2b4745edce2ea8231dc7d91/doc/_release-notes/v1.22.0.md#L91)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, the issue that #20209 fixed is that computing contact results between *two rigid bodies* may incorrectly aborts when a deformable body is present and in contact. Even though deformables are excluded from release notes, I think this may still be worth noting because the apparent symptom is not directly related to deformables.
</blockquote></details>

Done (~3 lines prior).
___
*[`doc/_release-notes/v1.22.0.md` line 92 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgJxJaaEsasnvP3BG_B:-NgOpN5E1IGW83lZwESQ:b-gceiei) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d3f695ad08f9b09d2b4745edce2ea8231dc7d91/doc/_release-notes/v1.22.0.md#L92)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

The only user facing change is a bug fix that prompted the work, "Calls to JointActuator::set_default_gear_ratio()/set_default_rotor_inertia() are now reflected in default contexts created after Finalize()" or something like that. The commit is mostly to explain the framework for any dev trying to implement similar default values.
</blockquote></details>

Done (~7 lines prior).

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2 with one elaboration.

> Reviewed 2 of 3 files at r2, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-:-NgtIm1mBLSIHjMpAvfa:b-5k25hb)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.22.0.md` line 90 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgtHoXgBfEZNwYwhNYz:-NgtHoXgBfEZNwYwhNZ-:bhlsfzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/6304e02cc3434b64eb475a026088e82e4254e9c8/doc/_release-notes/v1.22.0.md#L90)):*
nit: I know it's buried in the issue, but it's probably worth calling out on these two features:

> RenderEngineFoo supports multiple meshes and materials in *.obj files.

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-:-NgtMQWM6UAscBMkGfqb:bnfp4nl)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20326)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.22.0.md` line 90 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20326#-NgtHoXgBfEZNwYwhNYz:-Ngteyty8v6fCdL1OuPm:bk6x10n) ([raw file](https://github.com/RobotLocomotion/drake/blob/6304e02cc3434b64eb475a026088e82e4254e9c8/doc/_release-notes/v1.22.0.md#L90)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Did I get it right?  The suggestion wasn't 100% clear to my eye.  Feel free to click the "Edit it GitHub" button and push better wording, if not.
</blockquote></details>

That's exactly it.

**Pull request merged**
