### PR TITLE
gl_renderer: Fix stub factory for macOS build

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #14255.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14256)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-cmake-experimental-release please

**Review by sherm1 — COMMENTED** [review]
:lgtm: for both but with a question about the signature change

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14256#-:-MKhIFXd62ZM207P5O9F:b-wffsd)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[geometry/render/gl_renderer/no_render_engine_gl_factory.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14256#-MKhHvxz7oMAm2WNclee:-MKhHvy-4gXoefcw6cuG:b-z62wyt) ([raw file](https://github.com/robotlocomotion/drake/blob/52d35afdae130ee26463e729306aa9519ef4ad9c/geometry/render/gl_renderer/no_render_engine_gl_factory.cc#L8)):*
> ```cpp
> namespace render {
> 
> std::unique_ptr<RenderEngine> MakeRenderEngineGl(RenderEngineGlParams) {
> ```

Since the real MakeRenderEngineGl() takes this as optional, doesn't this need to do so also? Why remove the `={}`?

**Review by sherm1 — COMMENTED** [review]
(Pending green CI)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14256#-:-MKhIbQDEzDq2DZpjA_Y:b-dusr8m)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14256)* status: needs platform reviewer assigned, needs at least one assigned reviewer

___
*[geometry/render/gl_renderer/no_render_engine_gl_factory.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14256#-MKhHvxz7oMAm2WNclee:-MKhKcsAC-u8HqTEU0_P:b-pqn7fi) ([raw file](https://github.com/robotlocomotion/drake/blob/52d35afdae130ee26463e729306aa9519ef4ad9c/geometry/render/gl_renderer/no_render_engine_gl_factory.cc#L8)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Since the real MakeRenderEngineGl() takes this as optional, doesn't this need to do so also? Why remove the `={}`?
</blockquote></details>

```console
geometry/render/gl_renderer/no_render_engine_gl_factory.cc: In function 'std::unique_ptr<drake::geometry::render::RenderEngine> drake::geometry::render::MakeRenderEngineGl(drake::geometry::render::RenderEngineGlParams)':
geometry/render/gl_renderer/no_render_engine_gl_factory.cc:8:75: error: default argument given for parameter 1 of 'std::unique_ptr<drake::geometry::render::RenderEngine> drake::geometry::render::MakeRenderEngineGl(drake::geometry::render::RenderEngineGlParams)' [-fpermissive]
 std::unique_ptr<RenderEngine> MakeRenderEngineGl(RenderEngineGlParams = {}) {
                                                                           ^
In file included from geometry/render/gl_renderer/no_render_engine_gl_factory.cc:1:0:
bazel-out/k8-opt/bin/geometry/render/gl_renderer/_virtual_includes/apple_only_no_render_engine_gl_factory/drake/geometry/render/gl_renderer/render_engine_gl_factory.h:29:31: note: previous specification in 'std::unique_ptr<drake::geometry::render::RenderEngine> drake::geometry::render::MakeRenderEngineGl(drake::geometry::render::RenderEngineGlParams)' here
 std::unique_ptr<RenderEngine> MakeRenderEngineGl(
                               ^~~~~~~~~~~~~~~~~~
```

https://quuxplusone.github.io/blog/2020/04/18/default-function-arguments-are-the-devil/#fiddly-redeclaration-rules

The rules are slightly modified in C++20, but repeating the argument at the definition is still verboten.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-cmake-experimental-release please

**Comment by jwnimmer-tri** [comment]
I could not reproduce the build error on `macsim`, so the fixup is a bit of a shot in the dark.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14256)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[geometry/render/gl_renderer/no_render_engine_gl_factory.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14256#-MKhHvxz7oMAm2WNclee:-MKhV_t-5Kq7aPOUiupw:b-hi48gq) ([raw file](https://github.com/robotlocomotion/drake/blob/52d35afdae130ee26463e729306aa9519ef4ad9c/geometry/render/gl_renderer/no_render_engine_gl_factory.cc#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

```console
geometry/render/gl_renderer/no_render_engine_gl_factory.cc: In function 'std::unique_ptr<drake::geometry::render::RenderEngine> drake::geometry::render::MakeRenderEngineGl(drake::geometry::render::RenderEngineGlParams)':
geometry/render/gl_renderer/no_render_engine_gl_factory.cc:8:75: error: default argument given for parameter 1 of 'std::unique_ptr<drake::geometry::render::RenderEngine> drake::geometry::render::MakeRenderEngineGl(drake::geometry::render::RenderEngineGlParams)' [-fpermissive]
 std::unique_ptr<RenderEngine> MakeRenderEngineGl(RenderEngineGlParams = {}) {
                                                                           ^
In file included from geometry/render/gl_renderer/no_render_engine_gl_factory.cc:1:0:
bazel-out/k8-opt/bin/geometry/render/gl_renderer/_virtual_includes/apple_only_no_render_engine_gl_factory/drake/geometry/render/gl_renderer/render_engine_gl_factory.h:29:31: note: previous specification in 'std::unique_ptr<drake::geometry::render::RenderEngine> drake::geometry::render::MakeRenderEngineGl(drake::geometry::render::RenderEngineGlParams)' here
 std::unique_ptr<RenderEngine> MakeRenderEngineGl(
                               ^~~~~~~~~~~~~~~~~~
```

https://quuxplusone.github.io/blog/2020/04/18/default-function-arguments-are-the-devil/#fiddly-redeclaration-rules

The rules are slightly modified in C++20, but repeating the argument at the definition is still verboten.
</blockquote></details>

Oh, duh -- I missed that this was a definition!

**Comment by SeanCurtis-TRI** [comment]
___
*[geometry/render/gl_renderer/no_render_engine_gl_factory.cc, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14256#-MKjZDAc1PMkeCE05G20:-MKjZDAd4C46sgi4pTdJ:b-kpzqli) ([raw file](https://github.com/robotlocomotion/drake/blob/06661387add9995b20c6f07f44aa648596cea12e/geometry/render/gl_renderer/no_render_engine_gl_factory.cc#L8)):*
> ```cpp
> namespace render {
> 
> std::unique_ptr<RenderEngine> MakeRenderEngineGl(RenderEngineGlParams = {}) {
> ```

BTW I have to wonder if the error wasn't as simple as I'd added a default to parameter to a parameter with no name.  :-/  I can't believe *I* typed it and @sherm1 missed it. But I can't even think of what that would mean.

**Comment by SeanCurtis-TRI** [comment]
___
*[geometry/render/gl_renderer/no_render_engine_gl_factory.cc, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14256#-MKjZDAc1PMkeCE05G20:-MKjZYiB7wXqtMZtb3H-:b-1ylseb) ([raw file](https://github.com/robotlocomotion/drake/blob/06661387add9995b20c6f07f44aa648596cea12e/geometry/render/gl_renderer/no_render_engine_gl_factory.cc#L8)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I have to wonder if the error wasn't as simple as I'd added a default to parameter to a parameter with no name.  :-/  I can't believe *I* typed it and @sherm1 missed it. But I can't even think of what that would mean.
</blockquote></details>

Nevermind. It's perfectly meaningful. The declaration doesn't have to provide names. Only the definition.

**Pull request merged**
