### PR TITLE
[pydrake] Add pybind11 support to yaml_load_typed

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/pull/18566 (and therefore https://github.com/RobotLocomotion/drake/issues/17112).

+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18572)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18572)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 469 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18572#-NLa_kyH06irblDsLWi6:-NLa_kyH06irblDsLWi7:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/db2ee42672b722cd5cd619d8b3dda249645a5aeb/bindings/pydrake/common/test/yaml_typed_test.py#L469)):*
> ```Python
> 
> class TestYamlTypedReadPybind11(unittest.TestCase):
>     """Tests for deseralizing into pybind11 objects."""
> ```

typo



_Suggestion:_
```Python
deserializing
```

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18572#-:-NLaa3AvDr-_TdRdH2XK:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18572)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with minor (ignorable) nit

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18572#-:-NLb6OkOBEhIGCbvQv1_:b-xjkxyt)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 473 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18572#-NLb5nkQCoDJraP5PUtP:-NLb5nkR5kE3q5cmFhLl:b-nmewdl) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e7f8e6edff017755a07d97c6aacd5b78ebb6da0/bindings/pydrake/common/test/yaml_typed_test.py#L473)):*
> ```Python
>     def test_missing_serialize_binding(self):
>         with self.assertRaisesRegex(RuntimeError, ".*lacks.*__fields__.*"):
>             yaml_load_typed(schema=Value[str], data="{}")
> ```

nit Use of `Value[str]` is not immediately clear. Consider commenting "We only want a non-serialized pybind11 class" or making something `serilaize_test_util.NonserializedData`

Related (but pre-existing defect) is no related negative test for `serialize_pybind_test`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18572)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 473 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18572#-NLb5nkQCoDJraP5PUtP:-NLb7dr9CWyw3uskDNhT:b-8l12c5) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e7f8e6edff017755a07d97c6aacd5b78ebb6da0/bindings/pydrake/common/test/yaml_typed_test.py#L473)):*
Done.

> Related (but pre-existing defect) is no related negative test for serialize_pybind_test.

I don't see that anything important is missing?  That unit test is about when people call DefAttributesUsingSerialize to confirm what happens.  If someone doesn't call that function, there's nothing to test.

**Pull request merged**
