### PR TITLE
[geometry] Introduce initial framework for characterizing distance queries

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This introduces the `CharacterizeResultTest` (and supporting classes). Its purpose is to provide a common framework through which queries that report signed-distance-related values (e.g., point penetration and signed distance) can be evaluated to determine how good the support is across geometry pairs and scalar types.

This also includes the *initial* unit test exercising the framework for the `penetration_as_point_pair::Callback`. It only evaluates sphere-sphere contact for `T = {double, AutoDiffXd}` as a small example of the framework.

Supporting classes (and functions) in `characterization_utilities.{h|cc}`:
 - `DistanceCallback` - a polymorphic class that each Callback test will implement to interface with the framework.
 - `Expectation` - declaration of what we expect the outcome of the query will be.
 - `Configuration` - a specific configuration between two shapes with the known signed distance value between them.
 - `to_string()` for `fcl::NODE_TYPE` (to improve error messages).
 - `MakeFclShape` - a reifier that turns `drake::geometry::Shape` types into the corresponding `fcl` type.

What follows in subsequent PRs:
  - expand the framework to automatically build configurations in a compact, consistent form.
  - complete the tests on penetration_as_point_pair::Callback for all other relevant shape-pairs.
  - Modification of documentation in query_object.h reporting the results found in test.
  - Extension of framework to evaluate distance_to_shape::Callback in the same manner.

Relates to #10907

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review next week.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775#-:-MVbqBiQ5jpIyKJA70Do:b-nilm45)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVbt0lC81_xExzkaiG0:-MVbt0lC81_xExzkaiG1:b-lhhasu) (no related file):*
nit Build system organizational principle -- if a test library has greater-than-private visibility, it should be in a package named "test_utilities", not a package with production code, and therefore its code does not live in a "test" folder but rather a "test_utilities" folder.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVbt0lC81_xExzkaiG0:-MVbzFqMCRFQZ4oWi5CL:b1fde2c) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Build system organizational principle -- if a test library has greater-than-private visibility, it should be in a package named "test_utilities", not a package with production code, and therefore its code does not live in a "test" folder but rather a "test_utilities" folder.
</blockquote></details>

Presumably, marking it private (which is what it should've been but for copypasta) is sufficient to resolve this?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVbt0lC81_xExzkaiG0:-MVc-sJu4_TFw2otbHmw:b-s4z0aj) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Presumably, marking it private (which is what it should've been but for copypasta) is sufficient to resolve this?
</blockquote></details>

Yes, that would be fine.

---

**Review by rpoyner-tri — COMMENTED** [review]
still looking ; here are some early comments.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775#-:-MVs5vdqE9pF3UFr3yAq:bv8405q)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[geometry/proximity/BUILD.bazel, line 588 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVrzWIhBVIet_grLYdO:-MVrzWIi09qdgXwro-hr:b930i0n) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/BUILD.bazel#L588)):*
> ```Starlark
> )
> 
> # ------------------------ TESTS ------------------------------
> ```

BTW, I don't know that there is any rule against it, but I generally dislike this sort of "horizontal line" comment.  It implies a practice that is likely to proliferate, and probably becomes a maintenance headache at some point. For thought similar to mine, see https://stackoverflow.com/questions/1342958/horizontal-lines-in-comments

Consider maybe an ordinary comment in complete sentences that explains what you expect about the file structure?
___
*[geometry/proximity/test/characterization_utilities.h, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVs1zaK6GEqhk7HL-u6:-MVs1zaK6GEqhk7HL-u7:b-m03ehq) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L6)):*
> ```objc
>  functionality specifically targets proximity queries that are signed distance
>  (or equivalent to signed distance). It allows for compact representation of
>  test scenarios, outcome expectations and provides the common code to exercise
> ```

This sentence reads as awkward to me. Consider s/scenarios,/scenarios with/ .
___
*[geometry/proximity/test/characterization_utilities.h, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVs4_9eCOlun6aFSKwO:-MVs4_9eCOlun6aFSKwP:b-34hul6) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L79)):*
> ```objc
> };
> 
> /* Render an FCL enumeration into a string to support intelligible error
> ```

Should "Render" be "Renders" for consistency?
___
*[geometry/proximity/test/characterization_utilities.h, line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVs1LcF9FMChymkDjQf:-MVs1LcF9FMChymkDjQg:bh9wcf6) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L225)):*
> ```
> values used are have been used
> ```
some grammar problem here?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775#-:-MVvlfjuDc1rnJKWMvte:bnfp4nl)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity/test/characterization_utilities.h, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVvXaKn6Uyla9Ex5b03:-MVvXaKn6Uyla9Ex5b04:b-p7ekqd) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L89)):*
> ```objc
>   explicit MakeFclShape(const Shape& shape);
> 
>   /** @name  Implementation of ShapeReifier interface  */
> ```

BTW a doxygenated comment within internal namespace.
___
*[geometry/proximity/test/characterization_utilities_test.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVvaCcf33-XF4kYl-te:-MVvaCcf33-XF4kYl-tf:b6rcfqv) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities_test.cc#L26)):*
> ```cpp
> /* These unit tests test the mathematical underpinnings of the
>  CharacterizeResultTest. Specifically, it tests that the pieces of code which
>  contribute to *configuring* a test is valid.
> ```

grammar: pieces [...] *are*
___
*[geometry/proximity/test/characterization_utilities_test.cc, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVvaXdTD0Z6pnAQc6PF:-MVvaXdTD0Z6pnAQc6PG:b-or5gen) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities_test.cc#L203)):*
> ```cpp
>    - Creates N poses mapping the configuration to another, arbitrary frame.
>      N is the number of poses reported by X_WAs().
>    - One as geometry pair (A, B) and once for (B, A) (in case there's an
> ```

s/One/Once/ for consistency with the rest of the sentence.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed.

+@soonho-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775#-:-MW-agNSEHoo6cmo_cb2:b-ciw1px)* status: 5 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[geometry/proximity/BUILD.bazel, line 588 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVrzWIhBVIet_grLYdO:-MW-_hdu8t39U_waTjSQ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/BUILD.bazel#L588)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, I don't know that there is any rule against it, but I generally dislike this sort of "horizontal line" comment.  It implies a practice that is likely to proliferate, and probably becomes a maintenance headache at some point. For thought similar to mine, see https://stackoverflow.com/questions/1342958/horizontal-lines-in-comments

Consider maybe an ordinary comment in complete sentences that explains what you expect about the file structure?
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities.h, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVs1zaK6GEqhk7HL-u6:-MW-a1APAigs3-s0iInO:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L6)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This sentence reads as awkward to me. Consider s/scenarios,/scenarios with/ .
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities.h, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVs4_9eCOlun6aFSKwO:-MW-a4975TgJGNloCh4R:b-gucqnc) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L79)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Should "Render" be "Renders" for consistency?
</blockquote></details>

Done

Not just consistency, but correctness.
___
*[geometry/proximity/test/characterization_utilities.h, line 89 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVvXaKn6Uyla9Ex5b03:-MW-aCvfBRhXLVfi_tW2:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L89)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW a doxygenated comment within internal namespace.
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities.h, line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVs1LcF9FMChymkDjQf:-MW-aTOwCkoSS8KZPKxg:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities.h#L225)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> values used are have been used
> ```
some grammar problem here?
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities_test.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVvaCcf33-XF4kYl-te:-MW-aZjo05rUPKSdKMK0:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities_test.cc#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

grammar: pieces [...] *are*
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities_test.cc, line 203 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MVvaXdTD0Z6pnAQc6PF:-MW-aexX-yrJFUXganzi:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/0774b3753b406e7c0dd72827e847b55eede276d2/geometry/proximity/test/characterization_utilities_test.cc#L203)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

s/One/Once/ for consistency with the rest of the sentence.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 8 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity/test/characterization_utilities.h, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW08Rmh2GS3_y7T4rPO:-MW08Rmh2GS3_y7T4rPP:b2rrjku) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L54)):*
> by the last call to Invoke().

I think this part is not always guaranteed?
___
*[geometry/proximity/test/characterization_utilities.h, line 71 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW01Wv_-SlJi5V2YB4L:-MW01Wv_-SlJi5V2YB4M:b10sdfa) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L71)):*
> and a description to aid in assessing

It seems that this part is missing in this struct?
___
*[geometry/proximity/test/characterization_utilities.h, line 93 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW-dMRH64qpzvBvqlqG:-MW-dMRH64qpzvBvqlqH:bo94xzd) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L93)):*
> ```objc
>   void ImplementGeometry(const Sphere& sphere, void*) final;
> 
>   const std::shared_ptr<fcl::CollisionGeometry<double>> object() const {
> ```

`const std::shared_ptr<fcl::CollisionGeometry<double>>` => `std::shared_ptr<fcl::CollisionGeometry<double>>`
___
*[geometry/proximity/test/characterization_utilities.h, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW05E7D1-goVxQC8aql:-MW05E7D1-goVxQC8aqm:bj77gif) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L230)):*
> As documented in query_object.h, at least one measure of each geometry should be approximately 20 cm.
> As documented in query_object.h, the 2mm distance/depth

nit, I couldn't find the corresponding documentation in query_object.h file. Could you double-check?
___
*[geometry/proximity/test/characterization_utilities.cc, line 21 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW-eAaV7OnsDt6RAP-g:-MW-eAaV7OnsDt6RAP-h:bxd8rs) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.cc#L21)):*
> ```cpp
> 
> using Eigen::Vector3d;
> using math::RigidTransform;
> ```

nit,`s/math::RigidTransform/RigidTransform/g` below as we have this line.
___
*[geometry/proximity/test/characterization_utilities.cc, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW06FIX1FjEMewrrVHD:-MW06FIX1FjEMewrrVHE:b-h768jv) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.cc#L91)):*
> ```cpp
>     const double distance =
>         ExtractDoubleOrThrow(callback_->GetFirstSignedDistance());
>     DRAKE_DEMAND(std::abs(expected_distance) >
> ```

To support the case where T != double, I think we need to have `using std::abs` in the body and use `abs(...)` here (also another occurrence below `return std::abs(...)`).
___
*[geometry/proximity/test/characterization_utilities_test.cc, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW-f29pEnF9Lzs0wZ77:-MW-f29pEnF9Lzs0wZ78:b3md6nk) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities_test.cc#L19)):*
> ```cpp
> using Eigen::Vector3d;
> using math::RigidTransformd;
> using std::pair;
> ```

nit, not used here.
___
*[geometry/proximity/test/penetration_as_point_pair_characterize_test.cc, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW07FSb9ayUKMPdbXcm:-MW07FSb9ayUKMPdbXcn:b1mm3lg) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/penetration_as_point_pair_characterize_test.cc#L61)):*
> ```cpp
> TYPED_TEST_SUITE(CharacterizePointPairResultTest, ScalarTypes);
> 
> TYPED_TEST(CharacterizePointPairResultTest, sphere_sphere) {
> ```

Test name, `sphere_sphere` includes an underscore.

=> https://github.com/google/googletest/blob/master/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed in various ways. PTAL

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775#-:-MW0d2U687NFsbZmPMfz:bpr1mld)* status: 6 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[geometry/proximity/test/characterization_utilities.h, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW08Rmh2GS3_y7T4rPO:-MW0aDSc1CPIcyFJqvpv:b8tzj8j) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L54)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> by the last call to Invoke().

I think this part is not always guaranteed?

</blockquote></details>

That's why it lists the precondition that `GetNumResults() > 0`.
___
*[geometry/proximity/test/characterization_utilities.h, line 71 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW01Wv_-SlJi5V2YB4L:-MW0aKjX0End1Jywa8Mi:b-mh3pgj) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L71)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> and a description to aid in assessing

It seems that this part is missing in this struct?

</blockquote></details>

That comes in the next PR that's just waiting for this to merge, a casualty of slicing up big code into small PRs, you alright if I address it in the next PR so I don't have to massage multiple commits?
___
*[geometry/proximity/test/characterization_utilities.h, line 93 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW-dMRH64qpzvBvqlqG:-MW0aarL1Ng5aw5gaO_F:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L93)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`const std::shared_ptr<fcl::CollisionGeometry<double>>` => `std::shared_ptr<fcl::CollisionGeometry<double>>`
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities.h, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW05E7D1-goVxQC8aql:-MW0aca709_IpK_rwEdd:beh2vaw) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L230)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> As documented in query_object.h, at least one measure of each geometry should be approximately 20 cm.
> As documented in query_object.h, the 2mm distance/depth

nit, I couldn't find the corresponding documentation in query_object.h file. Could you double-check?

</blockquote></details>

Same "this is actually in a follow up PR" excuse, can I let this slide for now? In full honesty, the documentation this alludes to is actually in the *fourth* PR in this train, so this won't make sense until that merges. But, they're all waiting in the wings, ready to go.
___
*[geometry/proximity/test/characterization_utilities.cc, line 21 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW-eAaV7OnsDt6RAP-g:-MW0b4MJCtpeGiyVEol0:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.cc#L21)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit,`s/math::RigidTransform/RigidTransform/g` below as we have this line.
</blockquote></details>

Done
___
*[geometry/proximity/test/characterization_utilities.cc, line 91 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW06FIX1FjEMewrrVHD:-MW0bAbeCq5pv0ECf7Rm:b-luggqp) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.cc#L91)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

To support the case where T != double, I think we need to have `using std::abs` in the body and use `abs(...)` here (also another occurrence below `return std::abs(...)`).
</blockquote></details>

This test(and the return value don't depend on T. `expected_distance` and `distance` are explicitly declared to be `double`.
___
*[geometry/proximity/test/characterization_utilities_test.cc, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW-f29pEnF9Lzs0wZ77:-MW0bOPQCUdIV2fseqqF:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities_test.cc#L19)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, not used here.
</blockquote></details>

Done
___
*[geometry/proximity/test/penetration_as_point_pair_characterize_test.cc, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW07FSb9ayUKMPdbXcm:-MW0buj17xbeyZQPM6f6:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/penetration_as_point_pair_characterize_test.cc#L61)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Test name, `sphere_sphere` includes an underscore.

=> https://github.com/google/googletest/blob/master/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore
</blockquote></details>

Done

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity/test/characterization_utilities.h, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW08Rmh2GS3_y7T4rPO:-MW0eAz7CBL7QUdoO5o4:b-111g0t) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

That's why it lists the precondition that `GetNumResults() > 0`.
</blockquote></details>

What if `GetNumResults() > 1`? Then, isn't it going to return the first result produced by the *first* `Invoke()`?
___
*[geometry/proximity/test/characterization_utilities.h, line 71 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW01Wv_-SlJi5V2YB4L:-MW0dsu5E26nJfYBHMtI:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L71)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

That comes in the next PR that's just waiting for this to merge, a casualty of slicing up big code into small PRs, you alright if I address it in the next PR so I don't have to massage multiple commits?
</blockquote></details>

OK.
___
*[geometry/proximity/test/characterization_utilities.h, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW05E7D1-goVxQC8aql:-MW0dyJM11nU_YvYrVIu:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L230)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Same "this is actually in a follow up PR" excuse, can I let this slide for now? In full honesty, the documentation this alludes to is actually in the *fourth* PR in this train, so this won't make sense until that merges. But, they're all waiting in the wings, ready to go.
</blockquote></details>

OK.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

___
*[geometry/proximity/test/characterization_utilities.h, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW08Rmh2GS3_y7T4rPO:-MW0oFPGDO1NSxsAScvv:b-1s0fyv) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L54)):*
A fair point. To address it, the technically correct comment would be more along the lines of:

> Reports the distance contained in the first result produced calling Invoke() since the last time ClearResults() was called.

It so happens that the calling code does a "clear" and an "invoke" in tandem. In fact, the documentation on `Invoke` makes it clear that the caller "is responsible for calling ClearResults() if it wants the results of this invocation to be distinct from other invocations."

So, what we're discussing here is the last, subtle nuance of legality. I'd emphasize that this code is not part of any public API, nor is it part of production code. It's support of very specific tests in a very closed ecosystem. 

So, what text would you like to see? If you feel strongly, I can apply the proposed comment above, or I'll take an alternate suggestion.
___
*[geometry/proximity/test/characterization_utilities.h, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW05E7D1-goVxQC8aql:-MW0pWcfBT43otjEBk4Z:b-6vevte) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L230)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

I just realized, it's not the fourth, it's the third. But I still appreciate your understanding in this regard.  :)

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity/test/characterization_utilities.h, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW08Rmh2GS3_y7T4rPO:-MW0qW9N-RXnq62pQDwQ:b65roo0) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L54)):*
> So, what text would you like to see?

Maybe simply removing `produced by the last call to Invoke()` ? I think it's clear that `ClearResults()` removes old results.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775#-:-MW0qtPy7mcDmk4pvZwf:bnfp4nl)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: 1 unresolved discussion (waiting on @soonho-tri)

___
*[geometry/proximity/test/characterization_utilities.h, line 54 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14775#-MW08Rmh2GS3_y7T4rPO:-MW0sJ_LAeNwZXUS2MzU:btr091b) ([raw file](https://github.com/robotlocomotion/drake/blob/ebaa139d2e4b1e2a69dde3af9624b43f79a7a7aa/geometry/proximity/test/characterization_utilities.h#L54)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> So, what text would you like to see?

Maybe simply removing `produced by the last call to Invoke()` ? I think it's clear that `ClearResults()` removes old results.
</blockquote></details>

A great suggestion. Done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14775)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),soonho-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
