### PR TITLE
[openusd_internal] Hide symbols from GNU flex output

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review.
FYI @hong-nvidia 

Discovered during work on #21405, code in OpenUSD that was generated by GNU flex was leaking exported symbols. This patch plugs the leaks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-:-NybVCwI7zpPlCUoE5A9:b-7iw37x)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-:-Nyv7_PY2idK9Zkj4eUL:b-safpmt)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-:-Nz-l9mM4vj3WxRc8PvD:bg7igkv)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/openusd_internal/repository.bzl` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-Nz-ipFIEbY2RV56f7sB:-Nz-ipFIEbY2RV56f7sC:b-thc4on) ([raw file](https://github.com/RobotLocomotion/drake/blob/3123b27e0558a9c6c55af805158e8f3c585e2cdf/tools/workspace/openusd_internal/repository.bzl#L21)):*
> ```Starlark
>             ":patches/cmake_usd_usd_shared.patch",
>             ":patches/dlopen_forbidden.patch",
>             ":patches/hide_flex_symbols.patch",
> ```

BTW For patches isolated to just one module, I've been trying to put the module name in the patch file e.g. `usd_sdf_flex_hidden.patch`.  I guess not a big deal either way, though.
___
*[`tools/workspace/openusd_internal/patches/hide_flex_symbols.patch` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-Nz-l21E7ydZ6IfUTmHd:-Nz-l21F5FALmzGaHaRg:bbajzr2) ([raw file](https://github.com/RobotLocomotion/drake/blob/3123b27e0558a9c6c55af805158e8f3c585e2cdf/tools/workspace/openusd_internal/patches/hide_flex_symbols.patch#L47)):*
> ```Diff
> index 29879c74e..feb7e7ebe 100644
> --- pxr/usd/sdf/textFileFormat.tab.cpp
> +++ pxr/usd/sdf/textFileFormat.tab.cpp
> ```

BTW I guess `Sdf_ParseLayer` isn't yelling?  It seems like that would also have needed attention.  I guess if our regression test is happy, I'm happy.

**Review by rpoyner-tri — COMMENTED** [review]
@jwnimmer-tri how do you feel about single reviewer for this one?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-:-NzTout0D08YDdEfQQ4P:bf7w3e0)* status: needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  (I wonder if you can even still generate this output with modern flex/bison?)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21477#-:-NzYpcMK8pJBfL49oXkP:b-vydr8z)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
