### PR TITLE
Excluding A Few Tests With TSan And Adding A TSan Suppression

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Ignoring some tests, suppressing a MOSEK related test. 

https://drake-jenkins.csail.mit.edu/view/Dynamic%20Analysis/job/linux-xenial-clang-bazel-experimental-memcheck-tsan-everything/3/

CDash:
https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=641780

Issue: https://github.com/RobotLocomotion/drake/issues/6179

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6309)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Let's do the `--noforce_pic` in a separate PR. I need to think about that some more first.

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/dev/BUILD, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6309#-KmTKvOJ3WPvtV9qwjg1:-KmTKvOJ3WPvtV9qwjg2:b7cyism) ([raw file](https://github.com/robotlocomotion/drake/blob/690f5deaae9e201ef30ebce6b02aa35fae5910aa/drake/multibody/dev/BUILD#L38)):*
> ```Python
>         "//drake/manipulation/models/iiwa_description:models",
>     ],
>     tags = gurobi_test_tags() + ["no_tsan"],
> ```

Add comment here and for all similar changes explaining why we exclude the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6309)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6309#-:-KmW_3foLpKoh3EFXpEZ:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6309#-:-KmX5ntrjzRdCw7Lmm0Q:bnfp4nl)*

**Pull request merged**
