### PR TITLE
pydrake rbt: Add `FindBaseBodies`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Needed for Anzu usages for rendering

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8923)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@naveenoid for review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8923#-:-LEA8ngjCTxt34XQEzNO:bj1xbhi)*

**Comment by naveenoid** [comment]
Ha! Glad I managed to show you something new :D :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8923#-:-LEACBBt4af3HGNV1XKr:b-rryxbe)*

**Comment by EricCousineau-TRI** [comment]
Glad to learn! :P

+@jwnimmer-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8923#-:-LEAU2ry6AUUVKEDknm3:bja2pdf)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/multibody/test/parsers_test.py, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8923#-LEAVXQH76Do_STbBFht:-LEAVXQI1pARx4ZMvjer:bej6tnp) ([raw file](https://github.com/robotlocomotion/drake/blob/da894385dc81267070f32685a8ab13c0f4477e17/bindings/pydrake/multibody/test/parsers_test.py#L94)):*
> ```Python
>         base_body_id, = robot.FindBaseBodies(id)
>         base_body = robot.get_body(base_body_id)
>         self.assertIs(base_body, robot.FindBody("base_link"))
> ```

FYI This formulation seems more intuitive to me, since the quantity under test is the ID integer:
```
base_body_id, = robot.FindBaseBodies(id)
expected_body_id = robot.FindBody("base_link").get_body_index()
self.assertEqual(base_body_id, expected_body_id)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8923#-:-LEAUzB80LBa5g5KIBVP:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[bindings/pydrake/multibody/test/parsers_test.py, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8923#-LEAVXQH76Do_STbBFht:-LEAXyHZBabUEepbpJ-_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/da894385dc81267070f32685a8ab13c0f4477e17/bindings/pydrake/multibody/test/parsers_test.py#L94)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This formulation seems more intuitive to me, since the quantity under test is the ID integer:
```
base_body_id, = robot.FindBaseBodies(id)
expected_body_id = robot.FindBody("base_link").get_body_index()
self.assertEqual(base_body_id, expected_body_id)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8923)*

**Pull request merged**
