### PR TITLE
[wheel] Use Eigen 3.4 on macOS

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Hotfix for #17943.

Closes #18010.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18011)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Review by svenevs — COMMENTED** [review]
+@svenevs :lgtm_strong: thanks for the fast fix!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18011#-:-NDDxBpCCDZwTU2Au7dt:bk3mpz9)* status: needs platform reviewer assigned (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18011)* status: needs platform reviewer assigned (waiting on @jwnimmer-tri)

**Review by svenevs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18011#-:-NDDxt2M14YxJJfNfBXi:bnfp4nl)* status: needs platform reviewer assigned (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18011#-:-NDE1Mcy3mwVI8M8J03q:bnfp4nl)* status: needs platform reviewer assigned (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18011#-:-NDE1Rbw1Xy_9P6ddamZ:b2no51w)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),svenevs (waiting on @jwnimmer-tri)

**Pull request merged**
