### PR TITLE
doc: Improve parsing and error reporting for @system diagram syntax

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #16148

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@russtedrake for feature review -- does this answer the need?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152#-:-MphcccVAcXU0ZQWByH6:bve9l9p)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Definitely.  :lgtm:  Thanks.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152#-:-MpiKxi69V11Fokyedsm:bz2qm31)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review -- Wednesday schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152#-:-MplsLs73YQ1nwAiVKoO:b58g9cv)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152#-:-Mplwrr24jdW5gC6Jrxc:b-cxwtpw)* status: missing label for release notes (waiting on @rpoyner-tri)

___
*[doc/doxygen_cxx/system_doxygen.py, line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16152#-MplvfyN6e8gn5AOr5H7:-MplvfyN6e8gn5AOr5H8:btyl6v2) ([raw file](https://github.com/robotlocomotion/drake/blob/da9046d7717e1d368b418d8c492930e1cea4ba11/doc/doxygen_cxx/system_doxygen.py#L104)):*
> ```Python
>         raise RuntimeError(
>             f'obsolete syntax "{obsolete_syntax}" found; use @system /'
>             f' @endsystem instead. Found in """\n{s}"""')
> ```

BTW just curious -- why the triple quotes in the error message? Is that just Pythonic style or is there a functional purpose?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152)* status: missing label for release notes (waiting on @rpoyner-tri)

___
*[doc/doxygen_cxx/system_doxygen.py, line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16152#-MplvfyN6e8gn5AOr5H7:-MplzeCR-VfeEyNR1hQT:b-m0pm1e) ([raw file](https://github.com/robotlocomotion/drake/blob/da9046d7717e1d368b418d8c492930e1cea4ba11/doc/doxygen_cxx/system_doxygen.py#L104)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW just curious -- why the triple quotes in the error message? Is that just Pythonic style or is there a functional purpose?
</blockquote></details>

It's an attempt to indicate in the output that the quoted text is multi-line. These messages typically emit a fair chunk of the source file.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16152#-:-MpmQilY2Worbs6HHLg6:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @rpoyner-tri)

**Pull request merged**
