### PR TITLE
geometry/opt: Add HPolyhedron::CartesianPower()

### PR DESCRIPTION
**Pull request by avalenzu**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371)

### CODE REVIEW

**Review by avalenzu — COMMENTED** [review]
+@russtedrake for feature review 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-MeQ0VL4BKiBUkKn7ot9:b-e8hf3u)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Looks great.  Thanks!

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-MeQvpEz8u57fzNcp2Zr:bh7juti)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @avalenzu and @RussTedrake)

___
*[geometry/optimization/hpolyhedron.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15371#-MeQvrCH-lqKLvOKS4NG:-MeQvrCH-lqKLvOKS4NH:b-htvchs) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb57216c8e9a0048d16c402a942a5413046336c/geometry/optimization/hpolyhedron.h#L95)):*
> ```objc
>   Eigen::VectorXd ChebyshevCenter() const;
> 
>   /** Returns the `n`-ary Cartesian power of `this`.
> ```

minor: could we add a one line def for the Cartesian power here?  (something with e.g. H x H x ... H?)
___
*[geometry/optimization/test/hpolyhedron_test.cc, line 347 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15371#-MeQvFNXAqB3yoNG4E7E:-MeQvFNXAqB3yoNG4E7F:b-52funk) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb57216c8e9a0048d16c402a942a5413046336c/geometry/optimization/test/hpolyhedron_test.cc#L347)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(H_2.b(), b_2));
>   EXPECT_TRUE(CompareMatrices(H_3.A(), A_3));
>   EXPECT_TRUE(CompareMatrices(H_3.b(), b_3));
> ```

This test is very similar to the implementation.  Can we also perhaps add a test of the concept?  E.g. for some x, x \in H_1 => [x;x] \in H_2 and [x;x;x] \in H_3?

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
Comments addressed. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-MejnwZi3vu6x85iMpa_:baz6201)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[geometry/optimization/hpolyhedron.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15371#-MeQvrCH-lqKLvOKS4NG:-MejnvNYBccAgr4eQ5k1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb57216c8e9a0048d16c402a942a5413046336c/geometry/optimization/hpolyhedron.h#L95)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

minor: could we add a one line def for the Cartesian power here?  (something with e.g. H x H x ... H?)
</blockquote></details>

Done.
___
*[geometry/optimization/test/hpolyhedron_test.cc, line 347 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15371#-MeQvFNXAqB3yoNG4E7E:-MejneLq9OvqnQhsgDwi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1fb57216c8e9a0048d16c402a942a5413046336c/geometry/optimization/test/hpolyhedron_test.cc#L347)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This test is very similar to the implementation.  Can we also perhaps add a test of the concept?  E.g. for some x, x \in H_1 => [x;x] \in H_2 and [x;x;x] \in H_3?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-Menwz14B7mWfybrzTs2:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for monday platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-Menx6dL0IGfMCURyLzD:b-jbsovd)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one typo and one possible drive-by polish.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-Mez5UkD3OsAS3b397YO:b-36t9uc)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

___
*[geometry/optimization/hpolyhedron.h, line 101 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15371#-Mez4Pv99TNlYJWINCqy:-Mez4Pv99TNlYJWINCqz:b-nvud2q) ([raw file](https://github.com/robotlocomotion/drake/blob/1df8e73da979d20332a389bca8b4770cb4962eaf/geometry/optimization/hpolyhedron.h#L101)):*
> ```objc
> 
>   /** Constructs a polyhedron as an axis-aligned box from the lower and upper
>    * corners. */
> ```

BTW This isn't on you. But in confirming that your new function has consistent formatting with the existing comments in the file, I noticed the file itself isn't consistent. If you're up for it, it'd be great if you'd edit out the leading `* ` on this line.
___
*[geometry/optimization/test/hpolyhedron_test.cc, line 323 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15371#-Mez55fO9sTBlWGU5CZ4:-Mez55fO9sTBlWGU5CZ5:b-vj4j7e) ([raw file](https://github.com/robotlocomotion/drake/blob/1df8e73da979d20332a389bca8b4770cb4962eaf/geometry/optimization/test/hpolyhedron_test.cc#L323)):*
> ```cpp
> GTEST_TEST(HPolyhedronTest, CartesianPowerTest) {
>   // First test the concept. If x ∈ H, then [x; x]  ∈ H x H and
>   // [x; x]  ∈ H x H x H.
> ```

nit: `[x; x; x]  ∈ H x H x H` (missing an `x`).

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[geometry/optimization/hpolyhedron.h, line 101 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15371#-Mez4Pv99TNlYJWINCqy:-MezGLf8CrbMR2_bctMc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1df8e73da979d20332a389bca8b4770cb4962eaf/geometry/optimization/hpolyhedron.h#L101)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This isn't on you. But in confirming that your new function has consistent formatting with the existing comments in the file, I noticed the file itself isn't consistent. If you're up for it, it'd be great if you'd edit out the leading `* ` on this line.
</blockquote></details>

Done.
___
*[geometry/optimization/test/hpolyhedron_test.cc, line 323 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15371#-Mez55fO9sTBlWGU5CZ4:-MezGN2D66tsrRTPbnqe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1df8e73da979d20332a389bca8b4770cb4962eaf/geometry/optimization/test/hpolyhedron_test.cc#L323)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: `[x; x; x]  ∈ H x H x H` (missing an `x`).
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15371#-:-MezS2RD2RM_pN2IWZ-S:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @avalenzu)

**Pull request merged**
