### PR TITLE
[examples] Use modern Meshcat visualization in spatula_slip_control

### LINKED ISSUE #19441: [examples/hydroelastic] Collision Geometry of spatula_slip_control in MeshCat
When I did these:
```
bazel run //tools:meldis -- -w
bazel run //examples/hydroelastic/spatula_slip_control:spatula_slip_control
```
I see MeshCat control for `DRAKE_VIEWER` (illustration geometries) but no MeshCat control for `Collision Geometry` as shown in the following picture:
image

It does have `--visualize_collision` flag, but it goes into `DRAKE_VIEWER` of MeshCat not `Collision Geometry`, as shown in the following picture:
```
bazel run //examples/hydroelastic/spatula_slip_control:spatula_slip_control -- --visualize_collision true
```
image

I want to remove `--visualize_collision` flag and have both `DRAKE_VIEWER` and `Collision Geometry` available by default like other examples in the following picture:
image

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Resolves #19441

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-:-NW4Gz5NA4yO75NOiPvl:b7bdky2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @joemasterjohn)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @joemasterjohn)

___
*[`examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc` line 182 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-NW4HP-e2IsoDMwCdHSo:-NW4HP-fBV_hMTyvAoOH:b-x35os1) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ab0de8309ba7eea45615d6d88c2aaf0491ddac7/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc#L182)):*
> ```cpp
>   auto meshcat = std::make_shared<geometry::Meshcat>();
>   visualization::ApplyVisualizationConfig(
>       visualization::VisualizationConfig(),
> ```

nit If the default config is satisfactory, then for simplicity just say `AddDefaultVisualization(&builder, meshcat)` instead of `ApplyVisualizationConfig`.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @joemasterjohn)

___
*[`examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc` line 182 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-NW4HP-e2IsoDMwCdHSo:-NW4IYQp2Imstrxh7TxQ:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ab0de8309ba7eea45615d6d88c2aaf0491ddac7/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc#L182)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If the default config is satisfactory, then for simplicity just say `AddDefaultVisualization(&builder, meshcat)` instead of `ApplyVisualizationConfig`.
</blockquote></details>

Done. Thanks.

**Comment by jwnimmer-tri** [comment]
BTW Once we fix #19464 the sliders will be on by default.

**Review by joemasterjohn — COMMENTED** [review]
Thanks for making this change, Damrong! :lgtm: +@rpoyner-tri for platform review, please.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-:-NW8dAy--qWvExbrHWB_:b-quuedt)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-:-NW9qiHw5RYc0LGd5fys:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc` line 227 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-NW9pHUK8LvgOX5NlMJa:-NW9pHUK8LvgOX5NlMJb:b-1dsr61) ([raw file](https://github.com/RobotLocomotion/drake/blob/342ca3fcc590a6a9641f468c4731b51e23c2b83a/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc#L227)):*
> ```cpp
>   meshcat->StopRecording();
> 
>   // TODO(19142) According to issue 19142, we can playback contact forces and
> ```

nit the majority of issue-number TODOs are spelled `TODO(#9999)`, rather than `TODO(9999)`. Not a style rule, but my preference; feel free to ignore.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19461)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn

___
*[`examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc` line 227 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19461#-NW9pHUK8LvgOX5NlMJa:-NWAMibECIAJUuOTZWjw:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/342ca3fcc590a6a9641f468c4731b51e23c2b83a/examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc#L227)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit the majority of issue-number TODOs are spelled `TODO(#9999)`, rather than `TODO(9999)`. Not a style rule, but my preference; feel free to ignore.
</blockquote></details>

Done. Thanks.

**Pull request merged**
