### PR TITLE
Add build_components_refresh.py script and commit its output

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a step towards better curation of `libdrake.so`'s contents, and installs some more recent elements of Drake that have been accidentally omitted, forestalling more problems like #6167.  Eventually we will want even more automation and CI checks of this.

See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7203)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri this should help with downstream users of Drake; would you be willing to feature review?
+@ggould-tri for platform review per rotation, please.

**Comment by ggould-tri** [comment]
:lgtm:, one spelling nit.

Insert obligatory grumble about checking in generated files here.  But I don't see a better alternative apart from porting build_components_refrest to skylark and making it a tool, and that might impair readability.  I will instead take on faith that we'll have an install test eventually.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/build_components_refresh.py, line 38 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7203#-KvlzpZCcjYtpm6C9uy_:-KvlzpZDwtzH4TuZyNDD:bgrobgs) ([raw file](https://github.com/robotlocomotion/drake/blob/135afd8eee840eac5560547f13246631062f567e/drake/build_components_refresh.py#L38)):*
> ```Python
>         original_lines = original.readlines()
> 
>     # Extract the header (group 0) and footer (group 2), discarging the list of
> ```

fyi typo "discarging"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7203#-:-Kvm--tKNrsg5OXRgCof:bmecmdt)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7203)*

**Comment by jwnimmer-tri** [comment]
> But I don't see a better alternative apart from porting build_components_refresh to skylark and making it a tool, and that might impair readability.

FYI You can't do a `bazel query` from Skylark last I checked, so the file will have to stay committed.  My plan would be to have either a CI linter that the component list is up-to-date, or to make curating it part of the periodic release process.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7203#-:-Kvm0i4ckIdbeQnYbRWA:b-8bkpge)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7203#-:-Kvm1NewgmFMPSdiPywc:bnfp4nl)*

**Pull request merged**
