### PR TITLE
Use dreal-4.20.09.1

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14083)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please. This addresses a compatibility issue with XCode 12.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by soonho-tri** [comment]
-@jamiesnape , I guess he is not available today.
+@sammy-tri for all reviews, please.

I have tested locally on my local macs running XCode 12.0 and XCode 11.7 (only for DrealSolver-related targets).

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  (pending mac CI, which I expect will pass since you've already tested it)

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14083#-:-MHSD15v9LDz49CgXGWW:b9iv3lj)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Comment by soonho-tri** [comment]
All checks have passed.

**Pull request merged**
