### PR TITLE
Remove CMake from automotive

### PR DESCRIPTION
**Pull request by agalbachicar**
As a previous step to include an RNDF implementation of Maliput inside the automotive section I have removed the CMakeLists.txt files and directory from the base CMakeLists.txt. This is due to the dependency of the RNDF implementation of the following libraries:

- [ignition-math](https://bitbucket.org/ignitionrobotics/ign-math)
- [ignition-rndf](https://bitbucket.org/ignitionrobotics/ign-rndf)

Both repositories are HG repositories and they are difficult to integrate as git submodules so maintaining CMake building system becomes very difficult. Moreover, this change is one step more on the path of removing CMake and adopting Bazel as default build system.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5932)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@jwnimmer-tri for all review please.

Thanks.

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
It looks like this PR omits the following `CMakeLists.txt` files?

```
./maliput/dragway/test/CMakeLists.txt
./maliput/dragway/CMakeLists.txt
./maliput/utility/test/CMakeLists.txt
./maliput/utility/CMakeLists.txt
./maliput/monolane/test/CMakeLists.txt
./maliput/monolane/CMakeLists.txt
./maliput/CMakeLists.txt
```

Was this done on purpose?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5932#-:-KiY-xPFFhzSYM6Sz13i:bm2qeer)*

**Comment by jwnimmer-tri** [comment]
@stonier (With your github admin hat on) Given the botspam above, I think @agalbachicar needs to be added to RobotLocomotion membership.  Furthermore, the reviewable assignee comment didn't take, which also indicates permission bits are missing.

@stonier (With your community hat on) This proposal was previously discussed in #4574.  What do you think about removing CMake support for `automotive` (until the superbuild-calls-Bazel puts it back)?

**Comment by jwnimmer-tri** [comment]
For the record, my position prior to this PR was that `drake/automotive/rndf` could go in a Bazel-only with unit tests, but would leave all other folders undisturbed _until_ we integrate RNDF loading into the demo at which point we have to turn off native CMake support.  I assumed that RNDF-into-demo was going to take long enough that the Bazel cutover was done (or close), but perhaps it's not worth threading that needle to finely.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please. Previous error was due to #5936.

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please.

**Comment by stonier** [comment]
> @stonier (With your github admin hat on) Given the botspam above, I think @agalbachicar needs to be added to RobotLocomotion membership. Furthermore, the reviewable assignee comment didn't take, which also indicates permission bits are missing.

Already ahead of you, invited him as soon as he PR'd. I suspect he added the feature review request before finding and accepting the invite.

> @stonier (With your community hat on) This proposal was previously discussed in #4574. What do you think about removing CMake support for automotive (until the superbuild-calls-Bazel puts it back)?

I think @jamiesnape makes some valid points in #4574. Even while not yet live (and volatile) it's good to make sure it's usable from a build and run point of view, even if no 'support' is given. I've in the past had our company shift to gems we've accidentally found that were not yet live specifically because it is also a great time to contribute and become involved in shaping features. Harder to do that after it's been released with a stable api. Volatility can always be buffered against with a fork that only updates with the latest upstream changes at a time of your own choosing. As much as possible, grant the user the ability to choose their own course.

At any rate, taking it out now would be ping-ponging on a decision which is surprising for everybody. Should be able to handle this simply - how about writing a `rndf.cc` which implements a header using the ignition libraries for bazel and a stubbed `rndf-cmake.cc` which stubs the implementation without linking and  with appropriate logging for the cmake build? @agalbachicar is that feasible and little effort with the forthcoming changes? That way we can roll up the rndf work without interfering with the build decisions and with no jobs left hanging.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5932#-:-KiZvVjsnwmZcw1iGToG:b-oofupq)*

**Comment by stonier** [comment]
We should do something about that botspam and the process that requires the contributor to finalise the squash and merge. They both raise a barrier for external contributions to drake. I'll follow up on the botspam and we shouldn't need to have everyone as a member to contribute to drake (I haven't seen this since svn days).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5932#-:-KiZzaaRdxx5esyA_G7R:bax70uc)*

**Comment by jwnimmer-tri** [comment]
It sounds like if nothing else at least this PR is premature.  The RNDF maliput backend can go in Bazel-only with unit testing in the next PR(s), and then we do some build-stubbing or something if superbuild-calls-Bazel isn't ready in time.

**Comment by agalbachicar** [comment]
@stonier I think we can work out a solution like that. We'll start working on code refactoring to reduce at a minimum code dependencies on ignition libraries and use the CMake - available ones instead.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5932#-:-KiZoph50LnfuBs8EYqH:b-r3smw8)*

**Comment by jwnimmer-tri** [comment]
I really don't think we should perturb the already-written code very much for this.  The maliput implementation should be able to go in immediately, just not wired into the pre-existing demo.  We could even write a small new standalone demo that was Bazel-only.

The goal should _not_ to make all of the new code work in CMake.  The goal should be to prevent disturbing the existing CMake-working code.

If push comes to shove, I an add Ignition to the CMake superbuild in about one day of work if we need to.

**Comment by stonier** [comment]
> The goal should not to make all of the new code work in CMake. The goal should be to prevent disturbing the existing CMake-working code.

+1 to this, that was my intent also.

@agalbachicar - start with the bazel maliput implementation and unit tests in one PR (if it's not too big), then see if you can make the cmake stub and non-disturbing automative demo changes. That keeps the PR's focused.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5932#-:-Ki_5DlQ-6fZxn9nd6NK:bkom2pi)*

**Comment by agalbachicar** [comment]
OK, thanks for the comments. I'll start working on that as soon as possible.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5932#-:-Ki_4DoPfD-dNJknB6Bi:b-ubk04h)*

**Pull request closed without merging**
