### PR TITLE
[render] Apply upstream VTK changes for a textured capsule

### LINKED ISSUE #18296: VTK capsule doesn't have the texture coordinate defined
### What happened?

This issue was discovered in the RenderRpc project when we wanted to set up an example scene to test the RenderEngine rendering. Due to the lack of texture coordinate, the capsule is not properly textured given a texture map either when loading in code or via an SDFormat file.

For example:
```
  const Capsule capsule(0.05, 0.1);
  scene_graph->RegisterAnchoredGeometry(
      source_id,
      MakeInstance(
          capsule, Vector3d(x, 0.25, 0),
          Material(texture_path, label_value), "texture_capsule"));
```

```
    <link name="textured_capsule">
      <pose>0.25 0.25 0 0 0 0</pose>
      <visual name="textured_capsule_visual">
        <geometry>
          <capsule>
            <radius>0.05</radius>
            <length>0.1</length>
          </capsule>
        </geometry>
        <material>
          <drake:diffuse_map>4_color_texture.png</drake:diffuse_map>
        </material>
      </visual>
    </link>
```
Technically, the capsule on the right should have the same texture as other primitives, but the default white color is rendered instead.

color_000_no_old_lighting_vtk

 

### Version

_No response_

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
- Apply new internal_vtk patch.
 - Update call sites.
 - Update test SDF to use the texture map on the capsule.

Additional fix:
 - VTK is inconsistent with how it defines their shapes. The "front" of a sphere faces in a different direction than a cylinder. We update the cylinder orientation so that from Drake's perspective, spheres "face" the same direction as cylinders and capsules.

resolves #18296

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+(release notes: fix)

**Comment by SeanCurtis-TRI** [comment]
+@zachfang for feature review, please.

**Comment by zachfang** [comment]
FYI. In case I am blocking anything, my plan is to review the PR today (probably the second half of the day).

**Review by SeanCurtis-TRI — COMMENTED** [review]
That's fine.  At least now I've gotten over the CI hump.

Also, I'll tie our slack conversation here. If you have a recommended recipe for updating the reference .gltf files, I'd like to add it to the README.md.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-:-NikV3Ji6pM6WSSt29vQ:b-cthi8n)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by zachfang — COMMENTED** [review]
:lgtm: I tested locally, and the example scene, specifically the capsule, is rendered correctly.

Some commands I used to aid development:

- If I want to see the renderings other than Meldis, I would do:
```
$ bazel run //geometry/render_gltf_client:server_demo
$ bazel run //geometry/render_gltf_client:client_demo -- --save_dir /TMP/PATH --cleanup=false
```

- If I want to see the exported glTF files, I would do:
```
$ bazel run //geometry/render_gltf_client:server_demo
$ bazel run //geometry/render_gltf_client:client_demo -- --cleanup=false
```
And go find the artifacts in one of the `/tmp/robot_locomotion_*` folders.

> Reviewed 6 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-:-Nillwkj97UxR_5wvnn1:b410qev)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/render_vtk/internal_render_engine_vtk_base.h` line 44 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-Nilar178CPtB_OBHqeS:-Nilar178CPtB_OBHqeT:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/b25294c4ca8e463dc75bbfe0303f77336d362bec/geometry/render_vtk/internal_render_engine_vtk_base.h#L44)):*
> ```objc
> 
> // Transforms a vtk cylinder that is y-axis aligned to be z-axis aligned, which
> // is what Drake uses. It does a further orientation so that that the
> ```

nit.

**Review by zachfang — COMMENTED** [review]
Correction.

-   If I want to see the renderings other than Meldis, I would do:

```
$ bazel run //geometry/render_gltf_client:server_demo
$ bazel run //geometry/render_gltf_client:client_demo -- --save_dir /TMP/PATH
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-:-NilnqHLCaYFYYCiK2Eb:b-9vc2gh)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks for the recipe.

I decided to revisit the topic and realized there was a simpler way to get the glTFs (and images) the test produced and evaluated. I've implemented it and extended the documentation.  PTAL.

+@sammy-tri for platform review.

A simple way to see the impact is to run:

```
bazel run //tools:model_visualizer_private -- --show_rgbd_sensor package://drake/geometry/render_gltf_client/test/example_scene.sdf
```

In the meshcat browser, you'll see a row of white, untextured geometry. This is known and orthogonal to this PR. But in the render window that gets opened, you should see the same shapes textured, including the capsule. Furthermore, the "orientation" of the textures on the capsule and cylinder should align nicely with that of the sphere and ellipsoid.


[Meschat shows textured primitives as white]


[RenderEngineVtk] shows textures on primitives -- including capsule

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-:-NiolH4o9KftbhWu3KWp:b4ph6bp)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 4 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-:-NipskojExB2K1lF4A94:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),zachfang

**Comment by jwnimmer-tri** [comment]
Well, it's too late to fix now, but this commit landed a very-much-too-big file:

```
 geometry/render_gltf_client/test/test_color_scene.gltf             | Bin 21962 -> 13817476 bytes
```

Maybe the instructions for how to regenerate that file could be improved to avoid this the next time around, though.

**Comment by jwnimmer-tri** [comment]
I guess we should still probably hotfix it to have smaller files.  As it stands, our source release archives will be somewhat bloated.

**Review by sammy-tri — COMMENTED** [review]
:facepalm:  "Diff suppressed" indeed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20492#-:-NiqDtHZ5k1Om2lW9H9W:b-gor0hk)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),zachfang

**Comment by zachfang** [comment]
I will be working on the hotfix and submit a PR tonight (in case someone has started).

**Comment by jwnimmer-tri** [comment]
(BTW I'm not working on it.)

It might also be worth having one of the tests in that folder fail-fast if the files ever get big again.

**Pull request merged**
