### PR TITLE
sensors: add documentation about the camera frame

### LINKED ISSUE #12057: RgbdSensor documentation doesn't specify in which direction the camera is looking (in camera frame B)
(sorry if I somehow missed it).

But I wasn't able to figure out which axes was front, right, and up in the camera frame by looking at the docs.  https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1sensors_1_1_rgbd_sensor.html

By contrast, the RigidBodyTree version does specify it:
https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1sensors_1_1_rgbd_camera.html

### PR DESCRIPTION
**Pull request by RussTedrake**
I found it difficult to find this basic information when I was looking before.

resolves #12057

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127#-:-MI9yuXiEM9v2f0J3vmt:b-qb6q7i)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Needs a bit more, I believe.  PTAL.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127#-:-MIJxOO8DowjDGZT6XCF:b-hbj905)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[systems/sensors/camera_info.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MIJwQMTDm35LKZdBT9R:-MIJwQMTDm35LKZdBT9S:b-nhk1hf) ([raw file](https://github.com/robotlocomotion/drake/blob/82cd9b8d4c7c521f8f5ea17c2341748e84e79fac/systems/sensors/camera_info.h#L53)):*
> ```objc
>  can be captured by the camera or intrinsic matrix which essentially maps points
>  in the camera frame C to the image plane. The camera looks along the positive
>  `z` axis, and the `y` axis points down. The projection matrix is called `A` in
> ```

nit: "... positive `Cz` axis and the `Cy` axis points down."
___
*[systems/sensors/rgbd_sensor.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MIJwfoMDwKCRa1FHXX2:-MIJwfoMDwKCRa1FHXX3:bndy0x) ([raw file](https://github.com/robotlocomotion/drake/blob/82cd9b8d4c7c521f8f5ea17c2341748e84e79fac/systems/sensors/rgbd_sensor.h#L66)):*
nit: With the frames C, D, and B, this statement becomes very ambiguous and probably requires additional elaboration.

> As documented by `CameraInfo`, the camera *model* looks down the positive `Cz`/`Dz`axis, with positive `Cy`/`Dy` pointing down (for color and depth sensors, respectively). If `X_BC != I` (or `X_BD != I`), the additional transform will have to be accounted for in determining `X_WC` to successfully aim the camera.

Or some such thing.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[systems/sensors/rgbd_sensor.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MIJwfoMDwKCRa1FHXX2:-MIJxU8c0DpY9gwyexgz:bz1y41i) ([raw file](https://github.com/robotlocomotion/drake/blob/82cd9b8d4c7c521f8f5ea17c2341748e84e79fac/systems/sensors/rgbd_sensor.h#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: With the frames C, D, and B, this statement becomes very ambiguous and probably requires additional elaboration.

> As documented by `CameraInfo`, the camera *model* looks down the positive `Cz`/`Dz`axis, with positive `Cy`/`Dy` pointing down (for color and depth sensors, respectively). If `X_BC != I` (or `X_BD != I`), the additional transform will have to be accounted for in determining `X_WC` to successfully aim the camera.

Or some such thing.
</blockquote></details>

Possibly slightly confusing because the C frame in *this* documentation doesn't mean literally the same thing as the C frame in `camera_info.h`.

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI maybe you could push the fixes to this branch, so we can get this over the finish line?

**Review by SeanCurtis-TRI — COMMENTED** [review]
A fine idea.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127#-:-MVal_PHDpvHj5NutX65:b-9wv1u3)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MIJwQMTDm35LKZdBT9R:-MVbJ0wwBtnjPPlaBwDf:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/82cd9b8d4c7c521f8f5ea17c2341748e84e79fac/systems/sensors/camera_info.h#L53)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: "... positive `Cz` axis and the `Cy` axis points down."
</blockquote></details>

Done
___
*[systems/sensors/rgbd_sensor.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MIJwfoMDwKCRa1FHXX2:-MVbL23n4-2cwCX_HTmF:btbxwir) ([raw file](https://github.com/robotlocomotion/drake/blob/82cd9b8d4c7c521f8f5ea17c2341748e84e79fac/systems/sensors/rgbd_sensor.h#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Possibly slightly confusing because the C frame in *this* documentation doesn't mean literally the same thing as the C frame in `camera_info.h`.
</blockquote></details>

A lot of water has flowed under the bridge since this was first changed. So, I overhauled the entire (now obsolete) paragraph.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri as single reviewer, please. I've no become an author and it would be better to have another pair of eyes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127#-:-MVbMDR95ZX_gFVpxAs0:bnpgm5i)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @RussTedrake, and @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MVbMdv62O-SRx1RQmrB:-MVbMdv62O-SRx1RQmrC:b-lp4drs) ([raw file](https://github.com/robotlocomotion/drake/blob/760fc5542c17303dd6ad70b3a7bfade7d087525d/systems/sensors/camera_info.h#L128)):*
> ```objc
>    parallel with Cz.
> 
>  @anchor camera_axes_in_image
> ```

Arguably, this should be hoisted *above* the glossary. Votes?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: at current state or w/ minor polish - thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127#-:-MVqAuES1qIcFHtffv1G:bantd6o)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[systems/sensors/camera_info.h, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MVbMdv62O-SRx1RQmrB:-MVqALFX7rTG-A8Y7oq9:bbshn39) ([raw file](https://github.com/robotlocomotion/drake/blob/760fc5542c17303dd6ad70b3a7bfade7d087525d/systems/sensors/camera_info.h#L128)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Arguably, this should be hoisted *above* the glossary. Votes?
</blockquote></details>

Yeah, it'd prolly look better there; that being said, existing defect, and this PR is a strict improvement, so I'm fine with it being done later.
___
*[systems/sensors/rgbd_sensor.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MIJwfoMDwKCRa1FHXX2:-MVqAjs00n12onj_Mi1C:b-g8drwt) ([raw file](https://github.com/robotlocomotion/drake/blob/82cd9b8d4c7c521f8f5ea17c2341748e84e79fac/systems/sensors/rgbd_sensor.h#L66)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

A lot of water has flowed under the bridge since this was first changed. So, I overhauled the entire (now obsolete) paragraph.
</blockquote></details>

OK Looks good to me!
Strict improvement with cross reference back to CameraInfo docs. A bit verbose on re-explanation, but I assume this provides instructive value to people new to the API.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've moved the paragraph.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127#-:-MVqDByADf1elAzTctHI:bnfl6x6)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[systems/sensors/camera_info.h, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14127#-MVbMdv62O-SRx1RQmrB:-MVqCvKABxw1y7FkTLP5:ba1y9fh) ([raw file](https://github.com/robotlocomotion/drake/blob/760fc5542c17303dd6ad70b3a7bfade7d087525d/systems/sensors/camera_info.h#L128)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, it'd prolly look better there; that being said, existing defect, and this PR is a strict improvement, so I'm fine with it being done later.
</blockquote></details>

Hoisted

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14127)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
