### PR TITLE
Optimized mesh loading

### LINKED ISSUE #1264: optimize loading of large meshes into bullet, or at least warn the user
Right now, if somebody tries to load a urdf with dense meshes as collision elements, drake simply appears to hang (in `constructModelmex`).  

Looking into it quickly, the hangup is in the looping call to `addPoint` in `BulletModel::newBulletMeshShape` (inside `BulletModel.cpp`).

It also appears that in the latest bullet rev, this method has an optional second argument which would disable the Aabb calculation on every point that gets added.  We could presumably then call `recalcLocalAabb` ourselves *after* adding all of the points. Not sure if this will make large meshes suddenly tractable for us, but we might at least make it past the load stage.  

I think we should try upgrading to the latest bullet and using this feature.  If it resolves the issue, great.  If not, we should also somehow add a warning and/or fail more gracefully if someone accidentally passes in a big mesh.

### PR DESCRIPTION
**Pull request by psiorx**
Now only recomputes the axis-aligned bounding box of a convex hull shape after adding all points.  

Requires the new version of Bullet (2.83.6)

Resolves #1264

### CODE REVIEW

**Comment by RussTedrake** [comment]
you presumably need to update the bullet git tag.

**Comment by psiorx** [comment]
Ah, that's right.  I can do that with the superbuild now. :)

**Comment by RussTedrake** [comment]
@psiorx -- the mac compile error was because the library names were wrong for the new version of bullet.  i've updated them in the bullet pod.  can you update the sha and push again?

**Comment by avalenzu** [comment]
:+1:

**Pull request merged**
