### PR TITLE
Simplified witness function isolation

### PR DESCRIPTION
**Pull request by edrumwri**
This PR works around nondeterminism that can be present in integrators (resulting in the bug described in issue #6396) and streamlines the witness function isolation process.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6434)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please (short and sweet!)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-KnbMoOrOueiddjbVm4l:b-tdekku)*

**Comment by sherm1** [comment]
Reviewed. So beautiful! Needs a fix though (that hopefully leaves it unblemished). When isolating the events, if a half-step is taken that doesn't have any witness functions changing sign, that is just an ordinary continuous interval and must return to the Simulator's main loop for per-step processing. It actually violates the preconditions of the witness function isolation method at that point -- the function can only be called if there is at least one triggered witness in the current interval. If you advance the trajectory by some interval that has no triggers, that means the original triggering was a false alarm and you just go back to normal processing until something else happens. 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 665 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knff_SYhGyV7kbh0Y4w:-Knff_SYhGyV7kbh0Y4x:b-1hzu46) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L665)):*
> ```objc
> 
>   // Check whether the witness function is to be isolated.
>   if (!witness_iso_len)
> ```

BTW add something that explains what this means, e.g. "If not, any apparently-triggered witnesses that were passed in actually did trigger."

---

*[drake/systems/analysis/simulator.h, line 670 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-KnffybG3X8lCXIRychV:-KnffybG3X8lCXIRychW:b3ykh0t) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L670)):*
> ```objc
>   // Mini function for integrating the system forward in time.
>   std::function<void(const T&)> fwd_int =
>       [t0, x0, context, this](const T& t_des) {
> ```

BTW, this is a "capture by value" list. t0 is a scalar, context & this are pointers, but x0 is a possibly-very-long list of state variables. Should be captured by reference since it isn't being modified.

---

*[drake/systems/analysis/simulator.h, line 700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knfh4yRr-ZJCAzib3ml:-Knfh4yRr-ZJCAzib3mm:b-wgslko) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L700)):*
> ```objc
>     // If no witness function triggered, we can continue integrating forward.
>     if (!trigger) {
>       a = c;
> ```

This case has to be a return to the Simulator's main loop, for per-step event handling, recalc next update time, etc. No event occurred when integrating from a to c, so we have now violated the precondition of this method: "at least one ...".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-KnfhZGze6B34t2EHKE6:b14mlat)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 665 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knff_SYhGyV7kbh0Y4w:-Kng101DendDKZoD1Rzw:bm7h3nw) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L665)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW add something that explains what this means, e.g. "If not, any apparently-triggered witnesses that were passed in actually did trigger."
</blockquote></details>

BTW Done.

---

*[drake/systems/analysis/simulator.h, line 670 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-KnffybG3X8lCXIRychV:-Kng1UhKcn-Gflb50AWw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L670)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this is a "capture by value" list. t0 is a scalar, context & this are pointers, but x0 is a possibly-very-long list of state variables. Should be captured by reference since it isn't being modified.
</blockquote></details>

Done.

---

*[drake/systems/analysis/simulator.h, line 700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knfh4yRr-ZJCAzib3ml:-KngGXUv25NxiY91E7jP:b-qu0p6v) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L700)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This case has to be a return to the Simulator's main loop, for per-step event handling, recalc next update time, etc. No event occurred when integrating from a to c, so we have now violated the precondition of this method: "at least one ...".
</blockquote></details>

Let's work this through: if a function triggered over the interval [a, b] and then didn't trigger over the interval [a, c] for a < c < b, one of two things could have occurred: either the more accurate integration step altered the state in such a way that the witness function no longer triggers- you could imagine that taking two steps of (b-a)/2 would mean the witness function no longer triggers when the time advances to b- *or* it means that we have not yet observed the sign change indicated by the "triggering" (example: f(a) < 0, f(b) > 0 and f(c) < 0).   Of course, since we have the nondeterminism in the integrator to deal with now, it's hard to reason about correctness of things, so I'll approach what we want from a different angle:

We want to ensure both that no events are missed and no event is handled twice. That means that we must terminate the function having advanced the context to the earliest time c such that (1) b > c > a and (2) one or more sign changes is detected. Because of the nondeterminism in the integrator, it's possible that a witness triggered at b and yet for any a <= c < b, no witness function will trigger again. In such a case, c will shrink to some value hardly larger than a, and the list of triggered witnesses will be cleared. The events-update-PR creates a trigger for each triggered witness (sorry for the mixed use of "trigger" here), so this will lead to no problem (no triggered witnesses = no triggers created). Going up a few levels in the simulator flow control, integration will continue from this time "hardly larger than a".

So now... how is the precondition violated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434)*

**Comment by sherm1** [comment]
Replied below -- I'm not seeing any changes though. Missing push?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.h, line 700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knfh4yRr-ZJCAzib3ml:-Kngbxb8S97QYVZZKKt8:bxzzhzq) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L700)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Let's work this through: if a function triggered over the interval [a, b] and then didn't trigger over the interval [a, c] for a < c < b, one of two things could have occurred: either the more accurate integration step altered the state in such a way that the witness function no longer triggers- you could imagine that taking two steps of (b-a)/2 would mean the witness function no longer triggers when the time advances to b- *or* it means that we have not yet observed the sign change indicated by the "triggering" (example: f(a) < 0, f(b) > 0 and f(c) < 0).   Of course, since we have the nondeterminism in the integrator to deal with now, it's hard to reason about correctness of things, so I'll approach what we want from a different angle:

We want to ensure both that no events are missed and no event is handled twice. That means that we must terminate the function having advanced the context to the earliest time c such that (1) b > c > a and (2) one or more sign changes is detected. Because of the nondeterminism in the integrator, it's possible that a witness triggered at b and yet for any a <= c < b, no witness function will trigger again. In such a case, c will shrink to some value hardly larger than a, and the list of triggered witnesses will be cleared. The events-update-PR creates a trigger for each triggered witness (sorry for the mixed use of "trigger" here), so this will lead to no problem (no triggered witnesses = no triggers created). Going up a few levels in the simulator flow control, integration will continue from this time "hardly larger than a".

So now... how is the precondition violated?


</blockquote></details>

Your comment about the integrator indeterminacy makes me think you aren't seeing this as I do yet. That is entirely irrelevant. The Simulator contract is to handle events, advance continuous state, repeat. Each time you advance the continuous state successfully, that's an irrevocable advancement of the trajectory. It doesn't matter what would have happened if you retried that step; that never happens. Here when you integrate from a to c and don't see any event occur you have now advanced the trajectory by one step. The longer step from a to b never happened and no longer has any meaning. So you shouldn't be in a method called `IsolateWitnessTriggers()` whose precondition requires at least one witness to have triggered. NO witnesses triggered. At all. Ever. Nothing happened. That was a perfectly ordinary Simulator continuous step advancing time from a to c, exactly as if the original step size had been h=(c-a). There never was a step to b. Hence you should be in the Simulator stepping loop, at the point where a continuous step has completed successfully with no witnesses triggering. The next thing should be handling other events, like per-step events that can never be missed when you advance time by a step.

If I'm not making my point successfully here let's discuss f2f in the morning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-KngeVIiRseAEK0ygv02:b-fq3m8x)*

**Comment by jwnimmer-tri** [comment]
Consider adding a unit test concurrently with the bugfix.

**Comment by edrumwri** [comment]
@jwnimmer-tri, I re-enabled the settings in the integrator that were causing an existing test to fail. We have a smorgasbord of existing tests that stress the witness function isolation capabilities.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-Knj-xRTXlfaVwjROIir:bj6wr2q)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by edrumwri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.h, line 700 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knfh4yRr-ZJCAzib3ml:-KnlH3aswvMmy1o477P2:bte7q8q) ([raw file](https://github.com/robotlocomotion/drake/blob/b7b9ce1958ed74decdbbb3f4b208bc35155bdf36/drake/systems/analysis/simulator.h#L700)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Your comment about the integrator indeterminacy makes me think you aren't seeing this as I do yet. That is entirely irrelevant. The Simulator contract is to handle events, advance continuous state, repeat. Each time you advance the continuous state successfully, that's an irrevocable advancement of the trajectory. It doesn't matter what would have happened if you retried that step; that never happens. Here when you integrate from a to c and don't see any event occur you have now advanced the trajectory by one step. The longer step from a to b never happened and no longer has any meaning. So you shouldn't be in a method called `IsolateWitnessTriggers()` whose precondition requires at least one witness to have triggered. NO witnesses triggered. At all. Ever. Nothing happened. That was a perfectly ordinary Simulator continuous step advancing time from a to c, exactly as if the original step size had been h=(c-a). There never was a step to b. Hence you should be in the Simulator stepping loop, at the point where a continuous step has completed successfully with no witnesses triggering. The next thing should be handling other events, like per-step events that can never be missed when you advance time by a step.

If I'm not making my point successfully here let's discuss f2f in the morning.
</blockquote></details>

PTAL now- I hoped to summarize our discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434)*

**Comment by edrumwri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-KnoPrqfdxw0a9V6MMAl:b-1hejgk)*

**Comment by sherm1** [comment]
Feature review -- :lgtm:, thanks Evan. +@jwnimmer-tri for platform review per rotation, please.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.h, line 645 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knr-vV5xDt23fekAPol:-Knr-vV6Q0--yO3i-ws7:b-maxgky) ([raw file](https://github.com/robotlocomotion/drake/blob/40c920ec53c8b5fbd558705eece542ea538726b4/drake/systems/analysis/simulator.h#L645)):*
> ```objc
> //       triggered witness functions change sign over [t0, tw].
> // @note We assume that, if a witness function triggers over an interval
> //       [a, b], it also triggers over any larger interval [a, d], for d > b.
> ```

BTW do you mean literally that `f(a)*f(d) < 0`? That wouldn't be true for "any" larger interval since f() might have changed sign again by the time you get to d. It would be true though if you mean "there must be a zero somewhere in the interval [a,d]. Please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-Knr1DSYPT3FHDOAoHP3:b-2sdw1n)*

**Comment by edrumwri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/simulator.h, line 645 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-Knr-vV5xDt23fekAPol:-Knt8Vj4kjSP4jBWGNbO:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/40c920ec53c8b5fbd558705eece542ea538726b4/drake/systems/analysis/simulator.h#L645)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW do you mean literally that `f(a)*f(d) < 0`? That wouldn't be true for "any" larger interval since f() might have changed sign again by the time you get to d. It would be true though if you mean "there must be a zero somewhere in the interval [a,d]. Please clarify.
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/simulator.h, line 675 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-KntLsdJaWfAazEPVnCA:-KntLsdJaWfAazEPVnCB:b-904yaq) ([raw file](https://github.com/robotlocomotion/drake/blob/bb77e0203a6f08e880eade933ae4afa6e0dab542/drake/systems/analysis/simulator.h#L675)):*
> ```objc
> 
>   // Mini function for integrating the system forward in time.
>   std::function<void(const T&)> fwd_int =
> ```

FYI (pre-existing) `fwd` presumably means "forward" and not "four-wheel drive", and thus is a disallowed abbreviation per cppguide (omitting letters inside of a word).

---

*[drake/systems/analysis/simulator.h, line 693 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-KntLRGz487DJ0M44h4p:-KntLRH-t_8MZELUtS8D:b-rd4ci9) ([raw file](https://github.com/robotlocomotion/drake/blob/bb77e0203a6f08e880eade933ae4afa6e0dab542/drake/systems/analysis/simulator.h#L693)):*
> ```objc
>   do {
>     // Compute the midpoint and evaluate the witness functions at it.
>     T c = (a + b) / 2;
> ```

FYI (pre-existing) `a`, `b`, `c` are useless as variable names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-KntMD-PCE7sUcjsPRJR:bcpz082)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 675 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-KntLsdJaWfAazEPVnCA:-KntPEHb5YyKdRLwS_wg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bb77e0203a6f08e880eade933ae4afa6e0dab542/drake/systems/analysis/simulator.h#L675)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI (pre-existing) `fwd` presumably means "forward" and not "four-wheel drive", and thus is a disallowed abbreviation per cppguide (omitting letters inside of a word).
</blockquote></details>

Done.

---

*[drake/systems/analysis/simulator.h, line 693 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-KntLRGz487DJ0M44h4p:-KntOdkfIappIZmeXq2P:b-bo92o2) ([raw file](https://github.com/robotlocomotion/drake/blob/bb77e0203a6f08e880eade933ae4afa6e0dab542/drake/systems/analysis/simulator.h#L693)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI (pre-existing) `a`, `b`, `c` are useless as variable names.
</blockquote></details>

FYI I generally agree, but a, b, and c are commonly used in implementations and pseudo-code descriptions of the bisection algorithm, which is what is being used here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434)*

**Comment by sherm1** [comment]
All good! Ready to merge pending CI.

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6434#-:-KntnyUcZjzsdyjWfImG:b-ljd2lt)*

**Pull request merged**
