### PR TITLE
[systems/primitives] Add BatchOutput to MultilayerPerceptron

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410#-:-MtrdVk32yaq5nPcApND:b-81zjv5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.cc, line 290 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MtsvUPPAx_e8Tjx1P5r:-MtsvUPPAx_e8Tjx1P5s:b-sm3o4m) ([raw file](https://github.com/robotlocomotion/drake/blob/0b518cc0448f208b5e92171666313b446d199715/systems/primitives/multilayer_perceptron.cc#L290)):*
> ```cpp
>   // TODO(russt): Try to reduce the amount of scratch memory.
>   MatrixX<T>* Wx_plus_b = &cache[0];
>   MatrixX<T>* Xn = &cache[num_weights_];
> ```

BTW, the code might be more readable, if we store the variable
```
int Wx_plus_b_cache_index_ = 0;
int Xn_cache_index_ = num_weights_;
```
in the class constructor. This would also make sure that the cache has consistent meanings across different functions `BackPropagate` and `BatchOutput`.
___
*[bindings/pydrake/systems/primitives_py.cc, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MtswK3UAW2-zMQVvTjG:-MtswK3UAW2-zMQVvTjH:b-am96fm) ([raw file](https://github.com/robotlocomotion/drake/blob/0b518cc0448f208b5e92171666313b446d199715/bindings/pydrake/systems/primitives_py.cc#L343)):*
> ```cpp
>         .def(
>             "BatchOutput",
>             [](const MultilayerPerceptron<T>* self, const Context<T>& context,
> ```

BTW, curious why we use a lambda here instead of binding `&MultilayerPerception::BatchOutput` directly. And also would it easier for Python users to return `Y` as the output, namely do
```cc
            [](const MultilayerPerceptron<T>* self, const Context<T>& context,
                const Eigen::Ref<const MatrixX<T>>& X) {
              Eigen::MatrixX<T> Y;
              self->BatchOutput(context, X, &Y);
              return Y;
            },

```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[systems/primitives/multilayer_perceptron.cc, line 290 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MtsvUPPAx_e8Tjx1P5r:-Mtwpgey6jOoz3UTgTj_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b518cc0448f208b5e92171666313b446d199715/systems/primitives/multilayer_perceptron.cc#L290)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, the code might be more readable, if we store the variable
```
int Wx_plus_b_cache_index_ = 0;
int Xn_cache_index_ = num_weights_;
```
in the class constructor. This would also make sure that the cache has consistent meanings across different functions `BackPropagate` and `BatchOutput`.
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/primitives_py.cc, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MtswK3UAW2-zMQVvTjG:-MtwigjQ7N6AXoS08x8x:brh5sel) ([raw file](https://github.com/robotlocomotion/drake/blob/0b518cc0448f208b5e92171666313b446d199715/bindings/pydrake/systems/primitives_py.cc#L343)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, curious why we use a lambda here instead of binding `&MultilayerPerception::BatchOutput` directly. And also would it easier for Python users to return `Y` as the output, namely do
```cc
            [](const MultilayerPerceptron<T>* self, const Context<T>& context,
                const Eigen::Ref<const MatrixX<T>>& X) {
              Eigen::MatrixX<T> Y;
              self->BatchOutput(context, X, &Y);
              return Y;
            },

```
</blockquote></details>

Done.  I've added that version as an alternative.  I agree it's easier, but it will be more expensive in an optimization loop.

But for this version of the binding, I *must* use a lambda. It transforms an Eigen::Ref from pybind (required to avoid the copy), into an Eigen::Ptr for c++.  You'll see that we use this same pattern in other places, like `MultibodyPlant::SetPositionsInVector()`

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410#-:-MtyIwdl4oTZet8ddTwL:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/primitives_py.cc, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MtswK3UAW2-zMQVvTjG:-MtyIWSt3zX6mI7l12Fn:b-23ocei) ([raw file](https://github.com/robotlocomotion/drake/blob/0b518cc0448f208b5e92171666313b446d199715/bindings/pydrake/systems/primitives_py.cc#L343)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I've added that version as an alternative.  I agree it's easier, but it will be more expensive in an optimization loop.

But for this version of the binding, I *must* use a lambda. It transforms an Eigen::Ref from pybind (required to avoid the copy), into an Eigen::Ptr for c++.  You'll see that we use this same pattern in other places, like `MultibodyPlant::SetPositionsInVector()`
</blockquote></details>

I see, I didn't realize that there is issue between Eigen::Ref and Eigen::Ptr.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/primitives_py.cc, line 348 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-Mu1aaGe28dSqzJtK-sN:-Mu1aaGe28dSqzJtK-sO:bmq2jff) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/bindings/pydrake/systems/primitives_py.cc#L348)):*
> ```cpp
>               self->BatchOutput(context, X, &Y);
>             },
>             py::arg("context"), py::arg("X"), py::arg("Y"),
> ```

nit See https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html.  If your intention here is to have the `Y` output argument be memory-efficient, then I'd guess that you should use `arg("Y").noconvert()` here so that it would be runtime error to pass in an output type that induced copying?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/systems/primitives_py.cc, line 348 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-Mu1aaGe28dSqzJtK-sN:-Mu1ue-y49o_dRxZYW8j:b-5w6sde) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/bindings/pydrake/systems/primitives_py.cc#L348)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit See https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html.  If your intention here is to have the `Y` output argument be memory-efficient, then I'd guess that you should use `arg("Y").noconvert()` here so that it would be runtime error to pass in an output type that induced copying?
</blockquote></details>

The same page says "Note that explicitly specifying .noconvert() is not required for mutable Eigen references (e.g. Eigen::Ref<MatrixXd> without const on the MatrixXd): mutable references will never be called with a temporary copy."

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[bindings/pydrake/systems/primitives_py.cc, line 348 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-Mu1aaGe28dSqzJtK-sN:-Mu2Tj61-5p90EThpR16:b-dcceza) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/bindings/pydrake/systems/primitives_py.cc#L348)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The same page says "Note that explicitly specifying .noconvert() is not required for mutable Eigen references (e.g. Eigen::Ref<MatrixXd> without const on the MatrixXd): mutable references will never be called with a temporary copy."
</blockquote></details>

OK you're right, good point!

**Review by RussTedrake — COMMENTED** [review]
+@ggould-tri for platform review, please, per rotation

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410#-:-Mu97JhE4_fVijSw2qJz:b-q99vgp)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: with some notes and minor confusion below.

> Reviewed 1 of 5 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410#-:-MuBiSVm6tFXRJv-duU1:b-h0jvth)* status: 2 unresolved discussions (waiting on @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.h, line 244 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MuBbNMICgP-3rUFlN0d:-MuBbNMICgP-3rUFlN0e:bniqvqc) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/systems/primitives/multilayer_perceptron.h#L244)):*
> ```objc
>   CacheEntry* hidden_layer_cache_{};
>   CacheEntry* backprop_cache_{};
>   // The following variables denote the index into the backprop_cache_ vector:
> ```

nit:  Slightly awkward phrasing here.  Diff below for a possible rewording.  Or not -- author's discretion.



_Suggestion:_
```objc
  // These values are the starting indices of the components of the
  // `backprop_cache_` vector.
```
___
*[systems/primitives/multilayer_perceptron.cc, line 99 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MuBjVZy4qGeV_KWC204:-MuBjVZy4qGeV_KWC205:bucp3m5) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/systems/primitives/multilayer_perceptron.cc#L99)):*
> ```cpp
>   dloss_dXn_cache_index_ = 2 * num_weights_;
>   dloss_dWx_plus_b_cache_index_ = 3 * num_weights_;
>   dloss_dW_cache_index_ = 4 * num_weights_;
> ```

minor:  I'm actually really confused by the layout of `backprop_cache_`.  It's a std::vector of 5*num_weights MatrixXd elements, but it looks to me like only five of the the elements of the std::vector are ever accessed.  Does anything ever access, e.g. the `cache[1]` element?
Can you clarify for me (or possibly in a comment for line 93) what the actual layout here is?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16410)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @RussTedrake)

___
*[systems/primitives/multilayer_perceptron.h, line 244 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MuBbNMICgP-3rUFlN0d:-MuBmYblBmPHlaIKjhca:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/systems/primitives/multilayer_perceptron.h#L244)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  Slightly awkward phrasing here.  Diff below for a possible rewording.  Or not -- author's discretion.
</blockquote></details>

Done.
___
*[systems/primitives/multilayer_perceptron.cc, line 99 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16410#-MuBjVZy4qGeV_KWC204:-MuBna1b7ChJYkWER4qr:b-q5njdz) ([raw file](https://github.com/robotlocomotion/drake/blob/830bd83b29ca99120fb4a39acc4d4ae9e2b61868/systems/primitives/multilayer_perceptron.cc#L99)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  I'm actually really confused by the layout of `backprop_cache_`.  It's a std::vector of 5*num_weights MatrixXd elements, but it looks to me like only five of the the elements of the std::vector are ever accessed.  Does anything ever access, e.g. the `cache[1]` element?
Can you clarify for me (or possibly in a comment for line 93) what the actual layout here is?
</blockquote></details>

Done. I've tried to improve the comments.  cache[1] is Wx_plus_b[1].

**Pull request merged**
