### PR TITLE
drake_visualizer: Enable --use_builtin_scripts

### LINKED ISSUE #9608: make common drake visualizer scripts available always?
As it stands right now, only the most advanced users can figure out how to launch drake_visualizer with the magical invocation to see what we typically see.  Is there any harm of promoting
```
cmd "0.drake_visualizer" {
    exec = "${DRAKE_WORKSPACE}/bazel-bin/tools/drake_visualizer \
        --script ${DRAKE_WORKSPACE}/multibody/rigid_body_plant/visualization/contact_viz.py \
        --script ${DRAKE_WORKSPACE}/multibody/rigid_body_plant/visualization/show_time.py \
        --script ${DRAKE_WORKSPACE}/multibody/rigid_body_plant/visualization/show_frames.py";
    host = "localhost";
}
```
so that it happens always?  (should be a simple addition to drake_visualizer.py?)

@jwnimmer-tri ?  @EricCousineau-TRI ?  @sammy-tri ?

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #9608

NEW: Finalized.

---

OLD:
Here's a coarse attempt. Off by default (my strong preference), but to use it, you can just pass `--use-drake-scripts`. To verify, press F8 to open terminal, and then print `(contact_viz, frame_viz, time_viz, image_viewer)` to see if scripts are active:
```
bazel run //tools:drake_visualizer  # Nominal
bazel run //tools:drake_visualizer --use-drake-scripts
bazel run @drake//tools:drake_visualizer --use-drake-scripts
./bazel-bin/tools/drake_visualizer --use-drake-scripts
./bazel-bin/external/drake/tools/drake_visualizer --use-drake-scripts
```

Need to verify using symlinks don't break downstream Bazel projects.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9653)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
> [...] i can see the time viewer as being opt-in, but i feel that the others should be opt-out. [...]

Hm... How's about this? I'd like to keep the design as simple as possible and predicatable a
```
# No args: Show everything but time.
./bazel-bin/tools/drake_visualization

# Specify: Explicit, csv. Can be empty.
--drake-scripts=contact,image,time
```

Whenever are drake plugins are used, they will be printed to the console so users explicitly know. It'll also give a brief suggestion on how to change, e.g.:
```
Using: --drake-scripts=contact,frame,image
  To use no scripts: --drake-scripts=
  To use all available scripts: --drake-scripts=contact,frame,image,time
```

> Some of the features of direction gui are sticky between subsequent executions of the app (eg. which panels are open). Might these options become sticky, too?

I'd prefer not to mess around with persistence settings in Director, and keep the options as simple / explicit as possible (not sure what issues this might introduce, and I'd prefer to answer as few questions as possible).

Self note: I need to ensure that this does not make collision with existing usages of `drake_visualizer` which explicitly call out the script. I'll just have it check local variables.

**Comment by RussTedrake** [comment]
sounds great to me.

**Comment by jwnimmer-tri** [comment]
I would advise against relocating the source files of these scripts into the attic.  Their pathnames are hard-coded in many places other than what is repaired here.  (We had to revert the rename once already.)  How about this PR makes them built-in, and then we give users time to migrate (remove their hard-coded paths, just use the defaults from now on).  Later on, we can move the files.

**Comment by EricCousineau-TRI** [comment]
Done. Turning all on for simplicity. Had to hack around `drake_visualizer`s greediness with arguments.

Used `singleton_func` so that way we don't duplicate the plugins in downstream projects, like Anzu.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI ping.  It would be nice to get this landed.  It's one of the last (and possibly the only) blocker to finish the RBT attic transition.

**Comment by EricCousineau-TRI** [comment]
Ew... Seems like paths may be bleeding over... Will try resolve, or just rename back to `show_{}`.

**Comment by EricCousineau-TRI** [comment]
Done.
(Also, split the backwards-compat to be separate to make it easier to view the diffs to scripts, revert, whatnot.)

**Pull request merged**
