### PR TITLE
Add perspective of positive semidefinite constraint

### PR DESCRIPTION
**Pull request by lujieyang**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@RussTedrake for feature review?

@jwnimmer-tri could you add Lu to the Drake developer group so that she can assign her own reviewers? Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-:-NvDWfrY05e8yw8lRAtV:bl4jcky)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @lujieyang)

**Review by RussTedrake — COMMENTED** [review]
I've sent the invite to the github group.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-:-NvMUGMt2UhKY_xfngRE:b-hudrb0)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @lujieyang)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvMVMy74DfG3fUQRRQ5:br5dsui) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
> ```cpp
> }
> 
> void GraphOfConvexSets::AddPerspectiveConstraint(
> ```

Can we add the line of documentation to this method to remind the reader/reviewer what's happeing?  Suggestion:
```
/*
Adds the perspective of the constraint in `binding` to `prog`.
@param binding is a constraint bound to _placeholder_ variables for yz.  
@param vars` is a list of variables [phi, yz], where `phi` is the scaling variable to be used in the perspective.
*/
```

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 781 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMUvNoB4gYbfxlslvc:-NvMUvNoB4gYbfxlslvd:b-j9itl7) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L781)):*
> ```cpp
>   } else if (PositiveSemidefiniteConstraint* pc =
>                  dynamic_cast<PositiveSemidefiniteConstraint*>(constraint)) {
>     prog->AddConstraint(binding.evaluator(), vars.tail(vars.size() - 1));
> ```

Let's add documentation here, too:
```
// Since we have ϕ ≥ 0, we have S ≽ 0 ⇔ ϕS ≽ 0.
// It is sufficient to add the original constraint to the program (with the new variables).
```
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1174 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMYeA1861NrfQwLtMU:-NvMYeA1861NrfQwLtMV:b-eaf03o) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/test/graph_of_convex_sets_test.cc#L1174)):*
> ```cpp
> 
> TEST_F(ThreeBoxes, PositiveSemidefiniteConstraint) {
>   auto constraint =
> ```

Need documentation, e.g.:
```
[ xᵤ[0], xᵤ[1]; xᵤ[1], xᵥ[0]] ≽ 0.
```
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1187 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMZEoq9pJ3hDXoqP4Q:-NvMZEoq9pJ3hDXoqP4R:b-qw179v) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/test/graph_of_convex_sets_test.cc#L1187)):*
> ```cpp
>       source_->GetSolution(result)[1], target_->GetSolution(result)[0];
>   Eigen::SelfAdjointEigenSolver<Eigen::Matrix2d> solver(mat);
>   EXPECT_GE(solver.eigenvalues()[0], 0);
> ```

I know i said to keep it simple, but this is a little two simple.  You don't need to test that MathematicalProgram does the right thing for PositiveSemidefinite constraints, you need to test that your new GCS code properly enforces the constraints. An answer that is all zeros isn't strong enough to test that.

I'd recommend:
- setting additional equality constraints to make x_u and x_v non-zero (but PSD) on the path from source to target.  That will confirm that we _can_ get a PSD matrix out.
- adding the same constraint from the source to the sink, making sure that one gets set to zero.
- Add a second test where you add additional equality constraints which prevent the matrix from being PSD on the path from source to target.  Make sure the solver fails.

**Review by lujieyang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvT9nqP97vsxlz9roHL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Can we add the line of documentation to this method to remind the reader/reviewer what's happeing?  Suggestion:
```
/*
Adds the perspective of the constraint in `binding` to `prog`.
@param binding is a constraint bound to _placeholder_ variables for yz.  
@param vars` is a list of variables [phi, yz], where `phi` is the scaling variable to be used in the perspective.
*/
```

</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 781 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMUvNoB4gYbfxlslvc:-NvT9qLY0rPa1B8wGSqI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L781)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Let's add documentation here, too:
```
// Since we have ϕ ≥ 0, we have S ≽ 0 ⇔ ϕS ≽ 0.
// It is sufficient to add the original constraint to the program (with the new variables).
```
</blockquote></details>

Done.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1174 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMYeA1861NrfQwLtMU:-NvT9pf_EU_-fr0gOi21:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/test/graph_of_convex_sets_test.cc#L1174)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Need documentation, e.g.:
```
[ xᵤ[0], xᵤ[1]; xᵤ[1], xᵥ[0]] ≽ 0.
```
</blockquote></details>

Done.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1187 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMZEoq9pJ3hDXoqP4Q:-NvT9taNC98IxKKPOGe4:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/test/graph_of_convex_sets_test.cc#L1187)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I know i said to keep it simple, but this is a little two simple.  You don't need to test that MathematicalProgram does the right thing for PositiveSemidefinite constraints, you need to test that your new GCS code properly enforces the constraints. An answer that is all zeros isn't strong enough to test that.

I'd recommend:
- setting additional equality constraints to make x_u and x_v non-zero (but PSD) on the path from source to target.  That will confirm that we _can_ get a PSD matrix out.
- adding the same constraint from the source to the sink, making sure that one gets set to zero.
- Add a second test where you add additional equality constraints which prevent the matrix from being PSD on the path from source to target.  Make sure the solver fails.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @lujieyang)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvWp-JA2hMbqUNfDyy0:biuuu4k) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
<details><summary><i>Previously, lujieyang (Lujie Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit - This should come just before the function definition, not inside.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1187 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMZEoq9pJ3hDXoqP4Q:-NvWpHb95CEUMCUWgQHZ:bqvc1hr) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/test/graph_of_convex_sets_test.cc#L1187)):*
<details><summary><i>Previously, lujieyang (Lujie Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please add a comment to each test describing roughly the bullets I wrote above.

**Review by lujieyang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvX4ZeZ2_e9iLxewKxU:b1rp7ft) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit - This should come just before the function definition, not inside.
</blockquote></details>

Got it! Done.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1187 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMZEoq9pJ3hDXoqP4Q:-NvX4dc73fKy5aDgCate:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/test/graph_of_convex_sets_test.cc#L1187)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

please add a comment to each test describing roughly the bullets I wrote above.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@xuchenhan-tri for platform review, please.

the failures look unrelated to this PR?  i'll try
@drake-jenkins-bot retest this, please 

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-:-NvdOjB1D6qKUdF9SgVo:b-9pgtgn)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @lujieyang)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this, please

**Comment by xuchenhan-tri** [comment]
*[`geometry/optimization/graph_of_convex_sets.cc` line 785 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdSEEC8mskMQbINuR6:-NvdSEEC8mskMQbINuR7:bvro69u) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ae427787189ea1f5c7ddd66b905c368078ed0fd/geometry/optimization/graph_of_convex_sets.cc#L785)):*
> ```cpp
>     prog->AddRotatedLorentzConeConstraint(A_cone,
>                                           VectorXd::Zero(rc->A().rows()), vars);
>   } else if (PositiveSemidefiniteConstraint* pc =
> ```

nit, CI is complaining about this unused variable



_Code quote:_
```cpp
PositiveSemidefiniteConstraint* pc =
```

**Comment by lujieyang** [comment]
*[`geometry/optimization/graph_of_convex_sets.cc` line 785 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdSEEC8mskMQbINuR6:-NvdTni08oN--ODYNQ1k:bmeku7z) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ae427787189ea1f5c7ddd66b905c368078ed0fd/geometry/optimization/graph_of_convex_sets.cc#L785)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, CI is complaining about this unused variable
</blockquote></details>

I removed the unused variable. How does it look now?

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm:
+(release notes: feature) 

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-:-NvdWZRF7qr91d4Ex9il:b55jxua)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @lujieyang)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvdTU707B59vMAP2Yl3:b-ufmuf5) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
<details><summary><i>Previously, lujieyang (Lujie Yang) wrote…</i></summary><blockquote>

Got it! Done.
</blockquote></details>

Sorry to pile on to this thread. Any user facing documentation (which I believe this is?) should go to the header file and be reconciled with existing documentation. Implementation notes can stay in the .cc file close to the actual implementation.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 785 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdSEEC8mskMQbINuR6:-NvdUG5U-IQh3KN13k0d:b-a3805n) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ae427787189ea1f5c7ddd66b905c368078ed0fd/geometry/optimization/graph_of_convex_sets.cc#L785)):*
<details><summary><i>Previously, lujieyang (Lujie Yang) wrote…</i></summary><blockquote>

I removed the unused variable. How does it look now?
</blockquote></details>

BTW, using RTTI is frowned upon by the styleguide.

https://drake.mit.edu/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_

But I see that this is the existing pattern. However, why deviate from the dynamic_cast pattern? You could do

`else if (dynamic_cast<PositiveSemidefiniteConstraint*>(constraint) != nullptr) { ... }`
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1202 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdVvrj1fmRQRMYRyJi:-NvdVvrj1fmRQRMYRyJj:bf7itaw) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ec9670e1c0b4da171c48a4869864c733bb366a/geometry/optimization/test/graph_of_convex_sets_test.cc#L1202)):*
> ```cpp
> }
> 
> // This test has linear constraints to prevent the matrix from being positive
> ```

BTW, writing a similar overview for the test case above (`ThreeBoxes::PositiveSemidefiniteConstraint1`) would be helpful for readers.

**Review by lujieyang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvdZCO20eUWfmVG8re_:bg5mhl3) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Sorry to pile on to this thread. Any user facing documentation (which I believe this is?) should go to the header file and be reconciled with existing documentation. Implementation notes can stay in the .cc file close to the actual implementation.
</blockquote></details>

Just removed the documentation here. There is already documentation in the header file.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 785 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdSEEC8mskMQbINuR6:-NvdZ4tIDVjVltniUBXG:b-xlm72s) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ae427787189ea1f5c7ddd66b905c368078ed0fd/geometry/optimization/graph_of_convex_sets.cc#L785)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, using RTTI is frowned upon by the styleguide.

https://drake.mit.edu/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_

But I see that this is the existing pattern. However, why deviate from the dynamic_cast pattern? You could do

`else if (dynamic_cast<PositiveSemidefiniteConstraint*>(constraint) != nullptr) { ... }`
</blockquote></details>

Thanks for the pointer! Just changed RTTI to the existing pattern.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @lujieyang)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 684 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvMVMy74DfG3fUQRRQ4:-NvgpYyE1HKvDD0UkTzw:b-7e31vg) ([raw file](https://github.com/RobotLocomotion/drake/blob/b2b533b587391bd3ad0cb5dfaaf86e2da0ef2f52/geometry/optimization/graph_of_convex_sets.cc#L684)):*
<details><summary><i>Previously, lujieyang (Lujie Yang) wrote…</i></summary><blockquote>

Just removed the documentation here. There is already documentation in the header file.
</blockquote></details>

Marking myself satisfied here. I'll leave it to you and @RussTedrake to decide if the existing documentation is satisfactory.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 785 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdSEEC8mskMQbINuR6:-Nvgpiea5nvxagwpYlc0:b6u43y8) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ae427787189ea1f5c7ddd66b905c368078ed0fd/geometry/optimization/graph_of_convex_sets.cc#L785)):*
<details><summary><i>Previously, lujieyang (Lujie Yang) wrote…</i></summary><blockquote>

Thanks for the pointer! Just changed RTTI to the existing pattern.
</blockquote></details>

To be clear, regardless of whether you are using `typeid` or `dynamic_cast`, you _are_ using RTTI, i.e. checking the type information at runtime.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1202 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdVvrj1fmRQRMYRyJi:-Nvgqv-V-qq3P2VFgyEN:b38g33l) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ec9670e1c0b4da171c48a4869864c733bb366a/geometry/optimization/test/graph_of_convex_sets_test.cc#L1202)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, writing a similar overview for the test case above (`ThreeBoxes::PositiveSemidefiniteConstraint1`) would be helpful for readers.
</blockquote></details>

I didn't see any change related to this comment. Is it dismissed intentionally or by accident?

When dismissing a comment, it's often nice to offer some explanation or at least acknowledge the comment so that the reviewer isn't left wondering if it's a misclick.

**Review by lujieyang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21296)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1202 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21296#-NvdVvrj1fmRQRMYRyJi:-NviZ37G93h52Qw54CLP:b-x3145i) ([raw file](https://github.com/RobotLocomotion/drake/blob/39ec9670e1c0b4da171c48a4869864c733bb366a/geometry/optimization/test/graph_of_convex_sets_test.cc#L1202)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I didn't see any change related to this comment. Is it dismissed intentionally or by accident?

When dismissing a comment, it's often nice to offer some explanation or at least acknowledge the comment so that the reviewer isn't left wondering if it's a misclick.
</blockquote></details>

Thanks for the heads-up! I will be more careful next time. I thought the first PSD test is pretty self-explanatory so I just resolved the comment.

**Comment by lujieyang** [comment]
:lgtm:

**Pull request merged**
