### PR TITLE
adds WrapTo system.  Adds python bindings for WrapTo and Saturation systems

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8120)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@seancurtis-tri -- could I get a feature review, please?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-:-L5qHWN2JCyL0_5M7JFR:be0iwff)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: modulo a bunch of cosmetic thoughts.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[bindings/pydrake/systems/primitives_py.cc, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5syGW3x8GSGysVgcN5:-L5syGW4fTFwtNytaC2i:bamtt3p) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/bindings/pydrake/systems/primitives_py.cc#L102)):*
> ```cpp
>   py::class_<Saturation<T>, LeafSystem<T>>(m, "Saturation")
>       .def(py::init<const VectorX<T>&, const VectorX<T>&>(), py::arg
>     ("min_value"), py::arg("max_value"));
> ```

BTW any reason you're only wrapping one of the constructors?

---

*[bindings/pydrake/systems/test/primitives_test.py, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t2LJmpsIR7UQvRLLU:-L5t2LJmpsIR7UQvRLLV:bm3w3z8) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/bindings/pydrake/systems/test/primitives_test.py#L141)):*
> ```Python
> 
>     def test_saturation(self):
>         system = Saturation((0., -1.), (1., 2.))
> ```

BTW It *might* be worth making this test with a vector of size > 2. With size 2, there's some cognitive dissonance about interpreting these as (min, max) pairs, or (min_0, min_1), (max_0, max_1) pairs. Or perhaps just a comment to call that out. Your call.

---

*[math/wrap_to.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t22O74st0D5LYLaP4:-L5t22O74st0D5LYLaP5:b4nfwiw) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/math/wrap_to.h#L16)):*
> ```objc
> ///   value + k*(high-low)
> /// for the unique integer value `k` that lands the output in the desired
> /// interval. @p low and @p high must be finite.
> ```

BTW And `low < high`?

---

*[math/wrap_to.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t1sTQWtZVzAKQHr0-:-L5t1sTQWtZVzAKQHr00:bl2jg1e) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/math/wrap_to.h#L23)):*
> ```objc
>   const T2 range = high - low;
>   return value - range * floor((value - low) / range);
>   // TODO(russt): jwnimmer preferred this implementation (which may be
> ```

FYI I suggest replacing "this" with "the following". It makes it more clear that this references the commented implementation. 

---

*[systems/primitives/wrap_to_system.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t0IGch2XBBWv72cbt:-L5t0IGdoegN_xp9QyJd:b-6m3kuy) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.cc#L34)):*
> ```cpp
> 
>   // Loop through and set the saturation values.
>   for (const auto& interval : intervals_) {
> ```

FYI The type of this is a pair but the name isn't very suggestive of it and is only revealed in the first/second shenanigans below. Perhaps a name that reflects this is a key-value pair of some sort?

---

*[systems/primitives/wrap_to_system.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t05hdJLR3Bqpguvod:-L5t05hdJLR3Bqpguvoe:b-b175k0) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.cc#L36)):*
> ```cpp
>   for (const auto& interval : intervals_) {
>     const int index = interval.first;
>     const T& low = interval.second.first;
> ```

FYI I have a particular distaste for `std::pair` as it leads to: `interval.second.first` style expressions. You could make a private nested struct (since this is strictly internal) and then you could reference `min_value` and `max_value`.  :)

---

*[systems/primitives/wrap_to_system.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-19xKxQcPtMPvpAo:-L5t-19xKxQcPtMPvpAp:b-2ovz7b) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L7)):*
> ```objc
> 
> #include "drake/common/drake_copyable.h"
> #include "drake/common/eigen_types.h"
> ```

BTW Unused?

---

*[systems/primitives/wrap_to_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5sydlW-AiOP__J-A90:-L5sydlW-AiOP__J-A91:b-x1rr8v) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L27)):*
> ```objc
> /// @ingroup primitive_systems
> template <typename T>
> class WrapTo : public LeafSystem<T> {
> ```

BTW There is a slight dissonance with the file being `wrap_to_system` and the class being `WrapTo`. The style guide *suggests* (calling it a "common case") having the file name directly map to the class name and it is a pattern that is largely propagated in Drake.

---

*[systems/primitives/wrap_to_system.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-Fw-0_YsJIJ_Lvib:-L5t-Fw-0_YsJIJ_Lvic:b-37roi1) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L32)):*
> ```objc
> 
>   /// Constructs a system to pass through a fixed-size input vector to the
>   /// output.  Additional calls to %set_interval are required to produce any
> ```

FYI Two thoughts:

1) Any reason why you didn't want this to link to the actual method?
2) methods stand out better with trailing parentheses. 

I'd strongly advocate for the trailing parentheses and weakly advocate for letting it be a hyperlink.

---

*[systems/primitives/wrap_to_system.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-bHbZGgur7TovWY8:-L5t-bHbZGgur7TovWY9:bbozunw) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L39)):*
> ```objc
>   /// interval `[low, high)`.  If this method is called multiple times for
>   /// the same index, then only the last interval will be used.
>   /// @p low and @p high should be finite.
> ```

BTW And require that `low < high`?

---

*[systems/primitives/wrap_to_system.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-h3dlMqkjzqjNUCN:-L5t-h3dlMqkjzqjNUCO:bpaf32) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L43)):*
> ```objc
> 
>   /// Returns the size.
>   int get_size() const { return input_size_; }
> ```

BTW Apparently unused; probably should, at least, invoke it in the test.

---

*[systems/primitives/wrap_to_system.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5sz9EBxlIVd9JcDbC7:-L5sz9EBxlIVd9JcDbC8:b9af83t) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L49)):*
> ```objc
>  private:
>   void CalcWrappedOutput(const Context<T>& context,
>                            BasicVector<T>* output) const;
> ```

BTW indentation

---

*[systems/primitives/wrap_to_system.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-lL0USFr2dmuh3pY:-L5t-lL0USFr2dmuh3pZ:bs6qbby) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L54)):*
> ```objc
>   // Note that this sparse representation was implemented because many
>   // use cases will only wrap a small fraction of the signals (and pass the
>   // others through), and to play nicely with symbolic::Expression.
> ```

FYI I'd like some more elaboration on the "nice playing".

---

*[systems/primitives/test/wrap_to_system_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t0upRPjk_0fCFkFZ7:-L5t0upRPjk_0fCFkFZ8:b-isqdgn) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/test/wrap_to_system_test.cc#L26)):*
> ```cpp
>   dut.CalcOutput(*context, output.get());
>   EXPECT_TRUE(CompareMatrices(output->get_vector_data(0)->CopyToVector(),
>                               expected_output, 1e-8));
> ```

FYI This feels pretty loose for double calculations. Perhaps a note explaining it?

---

*[systems/primitives/test/wrap_to_system_test.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t16CEvtYrPeVchepq:-L5t16CEvtYrPeVchepr:b-li00e4) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/test/wrap_to_system_test.cc#L39)):*
> ```cpp
>   CheckOutput<T>(dut, Vector1<T>{.5}, Vector1<T>{2.5});
>   CheckOutput<T>(dut, Vector1<T>{-.2}, Vector1<T>{2.8});
>   CheckOutput<T>(dut, Vector1<T>{32.4}, Vector1<T>{2.4});
> ```

BTW It is unclear to me that the ScalarTest  tests anything that the `SecondElementOnlyTest` doesn't cover. It's not like scalar systems get treated specially. (In fact, the latter test covers pass through when this test doesn't). Other than that, it seems redundant. Is there a particular purpose for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-:-L5t2oqWZtvy_1JLlsF4:bp38576)*

**Comment by RussTedrake** [comment]
Review status: 5 of 21 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/primitives_py.cc, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5syGW3x8GSGysVgcN5:-L5uwN0q42rKGSRKPU0m:b-967las) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/bindings/pydrake/systems/primitives_py.cc#L102)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW any reason you're only wrapping one of the constructors?
</blockquote></details>

it's the only one i need?  :-)  (that's been the philosophy in the python binding.. otherwise we fall into black holes).  plus wrapping the others requires wrapping a handful of supporting functions (like handling input ports, etc)

---

*[bindings/pydrake/systems/test/primitives_test.py, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t2LJmpsIR7UQvRLLU:-L5uwxxLAIAJVkvufH-p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/bindings/pydrake/systems/test/primitives_test.py#L141)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It *might* be worth making this test with a vector of size > 2. With size 2, there's some cognitive dissonance about interpreting these as (min, max) pairs, or (min_0, min_1), (max_0, max_1) pairs. Or perhaps just a comment to call that out. Your call.
</blockquote></details>

Done.

---

*[math/wrap_to.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t22O74st0D5LYLaP4:-L5uxC9E10b1ofCzghJm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/math/wrap_to.h#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW And `low < high`?
</blockquote></details>

Done.

---

*[math/wrap_to.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t1sTQWtZVzAKQHr0-:-L5uy6d2t-7y4pQ1MNU7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/math/wrap_to.h#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I suggest replacing "this" with "the following". It makes it more clear that this references the commented implementation. 
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t0IGch2XBBWv72cbt:-L5uzqDxmrpM2crXRNWf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.cc#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI The type of this is a pair but the name isn't very suggestive of it and is only revealed in the first/second shenanigans below. Perhaps a name that reflects this is a key-value pair of some sort?
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t05hdJLR3Bqpguvod:-L5uzrNTjsw2p8VtGH_H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.cc#L36)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I have a particular distaste for `std::pair` as it leads to: `interval.second.first` style expressions. You could make a private nested struct (since this is strictly internal) and then you could reference `min_value` and `max_value`.  :)
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-19xKxQcPtMPvpAo:-L5uzxiFacTClbFBeOyQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L7)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Unused?
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5sydlW-AiOP__J-A90:-L5v-001_nl1KfrIfG2e:b-kx6xi8) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW There is a slight dissonance with the file being `wrap_to_system` and the class being `WrapTo`. The style guide *suggests* (calling it a "common case") having the file name directly map to the class name and it is a pattern that is largely propagated in Drake.
</blockquote></details>

i avoided it only because we have a math/wrap_to.h already.  but i could be convinced.

---

*[systems/primitives/wrap_to_system.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-Fw-0_YsJIJ_Lvib:-L5v-CnpgUKmqWFav1Mc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Two thoughts:

1) Any reason why you didn't want this to link to the actual method?
2) methods stand out better with trailing parentheses. 

I'd strongly advocate for the trailing parentheses and weakly advocate for letting it be a hyperlink.
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-bHbZGgur7TovWY8:-L5v-FsMGFK_srx9FaK_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW And require that `low < high`?
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-h3dlMqkjzqjNUCN:-L5v-XqHce2lYc9mE50J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L43)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Apparently unused; probably should, at least, invoke it in the test.
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5sz9EBxlIVd9JcDbC7:-L5v-bDWrAQF1ZfwvW19:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW indentation
</blockquote></details>

Done.

---

*[systems/primitives/wrap_to_system.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t-lL0USFr2dmuh3pY:-L5v0WDua2Rnplox7h_R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I'd like some more elaboration on the "nice playing".
</blockquote></details>

Done.

---

*[systems/primitives/test/wrap_to_system_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t0upRPjk_0fCFkFZ7:-L5v0cbRWVp-Od6qyzTi:be40jpy) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/test/wrap_to_system_test.cc#L26)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This feels pretty loose for double calculations. Perhaps a note explaining it?
</blockquote></details>

Done.  (forgot you are sitting right next to the "Accuracy" sign on the whiteboard.)

---

*[systems/primitives/test/wrap_to_system_test.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t16CEvtYrPeVchepq:-L5v0zOEBYhwUsZbmg0u:b-xe5viy) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/test/wrap_to_system_test.cc#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It is unclear to me that the ScalarTest  tests anything that the `SecondElementOnlyTest` doesn't cover. It's not like scalar systems get treated specially. (In fact, the latter test covers pass through when this test doesn't). Other than that, it seems redundant. Is there a particular purpose for this?
</blockquote></details>

only that i wrote it first.  i'm fine zapping it (and have done so).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120)*

**Comment by SeanCurtis-TRI** [comment]
Ready for platform review, +@soonho-tri 

(With two more cosmetic follow-up comments.)

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/primitives/wrap_to_system.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t0IGch2XBBWv72cbt:-L5vcBh8O9iiHFdK2QgR:b-6i3rth) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.cc#L34)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI I can't *not* quibble.  :) Technically, "iter" has two issues for me:

1. Abbreviations are discouraged by the style guide (although "iter" is a rather benign abbreviation).
2. Iter is still a bit of a lie. Range iteration on a map returns a `std::pair` and not an iterator. As such, I prefer something more "pair"-like.

---

*[systems/primitives/wrap_to_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5sydlW-AiOP__J-A90:-L5vcv-j1Xe8cvvZ0W57:b-e5b5vl) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/wrap_to_system.h#L27)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i avoided it only because we have a math/wrap_to.h already.  but i could be convinced.
</blockquote></details>

The alternative, of course, is a more verbose system name: `WrapToSystem`.

---

*[systems/primitives/wrap_to_system.h, line 51 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5vd5TNZkkjjmaCMoTg:-L5vd5TNZkkjjmaCMoTh:b7dc19c) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ce009856a3993b75542759c041f1b9bf7e2861/systems/primitives/wrap_to_system.h#L51)):*
> ```objc
>   const int input_size_{};
> 
>   struct Interval {
> ```

Thanks.  :) I think this definitely increases readability.

---

*[systems/primitives/test/wrap_to_system_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5t0upRPjk_0fCFkFZ7:-L5vdJgFp5brwODMkiMY:bbtrgg5) ([raw file](https://github.com/robotlocomotion/drake/blob/d4ae28e9cf08dedce2fa5d1463019eb962c63940/systems/primitives/test/wrap_to_system_test.cc#L26)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (forgot you are sitting right next to the "Accuracy" sign on the whiteboard.)
</blockquote></details>

We do exchange a number of syllables on the subject of accuracy bounds. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-:-L5vdt-woVvUgLm7IsaH:byxeelr)*

**Comment by soonho-tri** [comment]
:lgtm: with minor comments

---

Reviewed 5 of 10 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/primitives/wrap_to_system.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5xOSIknzqFVbmoaU8x:-L5xOSIknzqFVbmoaU8y:b-w4h6ds) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ce009856a3993b75542759c041f1b9bf7e2861/systems/primitives/wrap_to_system.cc#L27)):*
> ```cpp
>   v.low = low;
>   v.high = high;
>   intervals_[index] = v;
> ```

BTW, you might prefer `intervals_[index] = Interval{low, high};` here.

---

*[systems/primitives/wrap_to_system.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5xOAFc9eP8I_0-snzZ:-L5xOAFc9eP8I_0-snz_:b9rrfx) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ce009856a3993b75542759c041f1b9bf7e2861/systems/primitives/wrap_to_system.cc#L37)):*
> ```cpp
> 
>   // Loop through and set the saturation values.
>   for (const auto& iter : intervals_) {
> ```

FYI, @seancurtis-tri 's comment on the choice of the name `iter` applies here as well.

---

*[systems/primitives/wrap_to_system.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-L5xMjNy_Ts0oS8v8lRg:-L5xMjNy_Ts0oS8v8lRh:bfvo8xm) ([raw file](https://github.com/robotlocomotion/drake/blob/c3ce009856a3993b75542759c041f1b9bf7e2861/systems/primitives/wrap_to_system.h#L52)):*
> ```objc
> 
>   struct Interval {
>     T low;
> ```

FYI, need `{}` in the end (also the following line).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120#-:-L5xQrVAIDY7a2dkbmmf:b-ij5eeu)*

**Comment by soonho-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 6 of 6 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8120)*

**Pull request merged**
