### PR TITLE
primitives: Relocate header file code to cc files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This serves as a proposal that Drake should only support the `comon/default_scalars.h` scalar types.  In future commits, we can migrate more code to follow this pattern and codify the practice into documentation.

This also serves as a prototype for how to move template code to cc files in other folders, while preserving git history.

Confirmed locally that `bazel test` passes on the first and second commit.

~Recommended review process:~
- ~review the first and second commits using GitHub's summary of the diffs, not reviewable;~
- ~review the final commit in reviewable (using r2 as the starting point of the range).~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12797)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I re-curated the commits to have proper history.  For example blame, see:
- https://github.com/jwnimmer-tri/drake/blame/primitives-cc/systems/primitives/sine.h
- https://github.com/jwnimmer-tri/drake/blame/primitives-cc/systems/primitives/sine.cc

which both show proper age for various code.

The script to create proper curation is https://gist.github.com/jwnimmer-tri/45c09a32b6da11230adecc44a3e7c1e3.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for review of curation, please.  Sherm has checked out the code changes, but I think the history-splitting here deserves a second look.

**Comment by jwnimmer-tri** [comment]
-@EricCousineau-TRI +@sammy-tri for platform review of curation, please. Sherm has checked out the code changes, but I think the history-splitting here deserves a second look.

**Comment by jwnimmer-tri** [comment]
Thanks.  Once git quiets down I'll "rebase" this later today and then merge, so that the base commit of this PR is the head of master.

**Comment by jwnimmer-tri** [comment]
The "rebase"
```
git fetch origin
git reset --hard origin/primitives-cc
git reset --hard origin/master
./git_prepare_h_to_cc.sh 
git reset --hard f0f57cd5f89b7235f8d405eab7c643d620c8a149
git cherry-pick 1176dc08cba8e422c53b8ddf19a8b580ecc92d54
git rebase --ignore-date f0f57cd5f89b7235f8d405eab7c643d620c8a149
```

**Comment by jwnimmer-tri** [comment]
Yup.  One of them is a merge commit of the other one.  (This was the same structure that Sam reviewed.)  https://devblogs.microsoft.com/oldnewthing/20190919-00/?p=102904 has more details.

**Comment by jwnimmer-tri** [comment]
(It looks better in gitk locally, less good in GitHub web views.  But the `git blame` online is a-ok: https://github.com/RobotLocomotion/drake/blame/master/systems/primitives/sine.cc)

**Comment by sherm1** [comment]
That's really neat!

**Pull request merged**
