### PR TITLE
Expand comment section in symbolic::Expression::EqualTo

### LINKED ISSUE #5162: (x * (y + z)).EqualTo(x*y + x*z) returns false.
In the current symbolic expression, it does not handle the parenthesis well. The comparison
```C++
(x * (y + z)).EqualTo(x*y + x*z)
```
returns false, when comparing the hash values in https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L120. But even if I commented out the hash value comparison, it still returns false.

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #5162

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5244)

### CODE REVIEW

**Comment by soonho-tri** [comment]
This PR only expands a comment section (requested by @hongkai-dai).

+@hongkai-dai , feature-review please.
+@david-german-tri  , platform-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5244#-:-KdWdQmUe7785OTxjfum:bytdj2j)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5244#-:-KdWhHMPlviRTd7_h2Tx:bnfp4nl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5244#-KdWsrR0CKnymOLh84hC:-KdWsrR0CKnymOLh84hD:b-fsefyx) ([raw file](https://github.com/robotlocomotion/drake/blob/1ad2392b2920da5e8b1d553ac2bd71b827659a02/drake/common/symbolic_expression.h#L205)):*
> ```objc
>    * check the following:
>    *
>    *     (p1.Expand() - p2.Expand()).EqualTo(0).
> ```

Can we also do `p1.Expand().EqualTo(p2.Expand())`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5244#-:-KdWrmqgwqBeSV4KG7Dr:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5244#-KdWsrR0CKnymOLh84hC:-KdWvKWntbYWzcgFSKY1:b2chmr) ([raw file](https://github.com/robotlocomotion/drake/blob/1ad2392b2920da5e8b1d553ac2bd71b827659a02/drake/common/symbolic_expression.h#L205)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we also do `p1.Expand().EqualTo(p2.Expand())`?
</blockquote></details>

Should be identical in theory. But in practice, I believe that the simplification that we add in `-` operation can help identify computationally equivalent expressions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5244)*

**Pull request merged**
