### PR TITLE
Made RigidBody::position_num_start and RigidBody::velocity_num_start private.

### PR DESCRIPTION
**Pull request by liangfok**
Renamed them to be Rigid/body::position_start_index_ and RigidBody::velocity_start_index_. Added accessors.

Builds upon #2905.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2907)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3174/ and is thus ready for feature review. +@amcastro-tri for feature review since this touches `RigidBody*`.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNoifU-rYvCgLQR3AaX:1864565513)*

**Comment by amcastro-tri** [comment]
I am ok with these changes that essentially "hide?" the structure of the RBT behind some accessors. Nothing changes in this case by adding these accessors. Users are still looking into the RBT implementation details. The fact that there are so many examples cases right now using these accessors IMO implies a faulty design. Again, this is not your fault.
However, you should restrain yourself from using these accessors in the future. If you find yourself doing that I feel you'd be doing something wrong because the RBT itself should be doing whatever query you need for you. Maybe we could talk about this in your specific case where you need to access these indexes.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 183 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-KNqsZ8BOsbVlFzw51p3:-KNqsZ8CA0fk8NyU46Mw:990013003) ([raw file](https://github.com/robotlocomotion/drake/blob/81489f440aa0817ed2bbaef3c21fb70f3bb4074b/drake/systems/plants/RigidBodyTree.cpp#L183)):*
> ```cpp
>     RigidBody& body = **it;
>     if (body.hasParent()) {
>       body.set_position_start_index(num_positions_);
> ```

BTW. I am ok with the RBT directly accessing these fields since clearly `RigidBody` is an RBT node and of course RBT is a (or should be) a `friend` of RigidBody.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNqtUWetxpxteh9KkXX:1811112916)*

**Comment by amcastro-tri** [comment]
Oh, I forgot, beside that big "but" note, :lgtm: since all this intertwined design of the physics engine is not the fault of this PR. Should we somehow mark these methods to discourage users from using them?

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNquM0aMX1XqaXKmjaX:1004860327)*

**Comment by liangfok** [comment]
@amcastro-tri: I agree with everything you've set. My plan is to eventually eliminate the need to use `RigidBody::get_position_start_index()`, etc., through the newly introduced `ModelElementId` abstraction (#2919 and #2976).

+@ggould-tri for platform review since it's Friday. Many thanks!!

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 183 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-KNqsZ8BOsbVlFzw51p3:-KNqutIvw1otCevnvP_w:-213636379) ([raw file](https://github.com/robotlocomotion/drake/blob/81489f440aa0817ed2bbaef3c21fb70f3bb4074b/drake/systems/plants/RigidBodyTree.cpp#L183)):*
I think I'm going to avoid making `RigidBodyTree` a friend of `RigidBody` since they are defined in different files. Here's a quote from the [style guide](https://google.github.io/styleguide/cppguide.html#Friends):

> Friends should usually be defined in the same file so that the reader does not have to look in another file to find uses of the private members of a class. A common use of friend is to have a FooBuilder class be a friend of Foo so that it can construct the inner state of Foo correctly, without exposing this state to the world. In some cases it may be useful to make a unittest class a friend of the class it tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNqviO_dYNzIdTJz7vE:217282654)*

**Comment by liangfok** [comment]
> Should we somehow mark these methods to discourage users from using them?

I will mark the methods as deprecated once we have a viable alternative based on `ModelElementId`. Until then, I don't think we can discourage their use since their is no viable alternative at this moment :cry: .

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNqwouu03deUPs_PzJ4:-514014483)*

**Comment by amcastro-tri** [comment]
`ModelElementId` is a completely different concept. I don't think it should be used to get equations' indexes. That is an internal job for RBT

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNr3A6zoM4PGHd5il3P:1807192180)*

**Comment by liangfok** [comment]
Just wait. My intent is to leverage `ModelElementId` to allow users to obtain `Model` objects through which users can obtain all relevant state about the model. This will eliminate the need for users to be exposed to the indices used to store the model's state in the `RigidBodySystem`'s state vector. Unfortunately, this is a long-term change given the need to go through incremental PRs...

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNr4I_pw8mHiiFe7ymM:-1107700742)*

**Comment by ggould-tri** [comment]
I guess this is the week of big far-reaching rename changes.  :lgtm:

---

Reviewed 6 of 25 files at r1, 9 of 13 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2907#-:-KNrfM0l31QvZTldMlH4:-391611549)*

**Pull request merged**
