### PR TITLE
Support sphere and capsule in C-IRIS collision geometry.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18375)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18375#-:-NI0-TsfCuE-iAS0jrRO:b4xbtza)* status: LGTM missing from assignee AlexandreAmice, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Note that you have a linting error in Cdash

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18375#-:-NI0M64oEKEbswqzdXu3:b-t71vgn)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI07fVR4XriMia7rwpA:-NI07fVSCS-cIAsSidBe:br7w775) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/collision_geometry.cc#L168)):*
> ```cpp
>     // If the sphere with radius r is on one side of the plane with a margin δ,
>     // it is equivalent to the following condition aᵀ*p_AS + b ≥ r + δ       if
>     // plane_side = kPositive   (1a) aᵀ*p_AS + b ≤ -(r + δ)    if plane_side =
> ```

Can you format this to:
```
// it is equivalent to the following condition
// aᵀ*p_AS + b ≥ r + δ   if plane_side = kPositive (1a)
// aᵀ*p_AS + b ≤ -(r + δ)    if plane_side = kNegative (1b)
// |a| ≤ 1 (2)
// where S is the center of the sphere
```
___
*[`geometry/optimization/dev/collision_geometry.cc` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI08W786Hzj-82H-QQo:-NI08W786Hzj-82H-QQp:b-p0bwiv) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/collision_geometry.cc#L184)):*
> ```cpp
>     // it is equivalent to the following condition
>     // aᵀ*p_AS1 + b ≥ r + δ       if plane_side = kPositive   (1a)
>     // aᵀ*p_AS2 + b ≥ r + δ       if plane_side = kPositive   (1a)
> ```

I would number these (1a), ((2a), (1b), (2b), (3)



_Code quote:_
```cpp
    // aᵀ*p_AS1 + b ≥ r + δ       if plane_side = kPositive   (1a)
    // aᵀ*p_AS2 + b ≥ r + δ       if plane_side = kPositive   (1a)
    // aᵀ*p_AS1 + b ≤ -(r + δ)    if plane_side = kNegative   (1b)
    // aᵀ*p_AS2 + b ≤ -(r + δ)    if plane_side = kNegative   (1b)
    // |a| ≤ 1                                               (2)
```
___
*[`geometry/optimization/dev/collision_geometry.cc` line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0GEPA5R63e4urMsLR:-NI0GEPA5R63e4urMsLS:bl502l2) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/collision_geometry.cc#L190)):*
> ```cpp
>     // where S1 and S2 are the center of the two spheres on the two ends of the
>     // capsule.
>     auto* reify_data = static_cast<ReifyData*>(data);
> ```

Do you want to reserve space for the rationals here or do you not care since we are only adding two things to `reify_data->rationals`?
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0Lg4S3cja_L3TNGHV:-NI0Lg4S3cja_L3TNGHW:b-uz5yjh) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/test/collision_geometry_test.cc#L321)):*
> ```cpp
>   const auto& model_inspector = scene_graph_->model_inspector();
>   CollisionGeometry capsule(&model_inspector.GetShape(body2_capsule_),
>                             body_indices_[2], body2_capsule_,
> ```

This `body_indices_[2]` feels brittle.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0LncQAugMcldykGrs:-NI0LncQAugMcldykGrt:bi1hnvh) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/test/collision_geometry_test.cc#L328)):*
> ```cpp
>   const auto X_AB_multilinear =
>       rational_forward_kin_.CalcBodyPoseAsMultilinearPolynomial(
>           q_star, body_indices_[2], expressed_body);
> ```

`body_indices_[2]` gets used again here. It'd be safer to make this a named constant.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 360 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0M-4-DMdAkORzQN4y:-NI0M-4-DMdAkORzQN4z:b77lspt) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/test/collision_geometry_test.cc#L360)):*
> ```cpp
>   Eigen::Matrix<double, 3, 2> p_AS;
>   plant_->CalcPointsPositions(
>       *plant_context_, plant_->get_body(body_indices_[2]).body_frame(), p_BS,
> ```

ditto for `body_indices_[2]`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18375)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI07fVR4XriMia7rwpA:-NI0dLRwAfhO9hbFY5eO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/collision_geometry.cc#L168)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can you format this to:
```
// it is equivalent to the following condition
// aᵀ*p_AS + b ≥ r + δ   if plane_side = kPositive (1a)
// aᵀ*p_AS + b ≤ -(r + δ)    if plane_side = kNegative (1b)
// |a| ≤ 1 (2)
// where S is the center of the sphere
```
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI08W786Hzj-82H-QQo:-NI0dUxeAe9Xilh4ZFsY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/collision_geometry.cc#L184)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would number these (1a), ((2a), (1b), (2b), (3)
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0GEPA5R63e4urMsLR:-NI0dju_DIJwL0JyIrDH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/collision_geometry.cc#L190)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Do you want to reserve space for the rationals here or do you not care since we are only adding two things to `reify_data->rationals`?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0Lg4S3cja_L3TNGHV:-NI0eL6KDGZF2wk5UKH3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/test/collision_geometry_test.cc#L321)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This `body_indices_[2]` feels brittle.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0LncQAugMcldykGrs:-NI0eLZi71bFCyOGGU__:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/test/collision_geometry_test.cc#L328)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

`body_indices_[2]` gets used again here. It'd be safer to make this a named constant.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 360 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18375#-NI0M-4-DMdAkORzQN4y:-NI0eMS6DN7ncwxB2GYX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5977c3c6ed90c8e73f4c1899d19b056b91682686/geometry/optimization/dev/test/collision_geometry_test.cc#L360)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto for `body_indices_[2]`
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18375#-:-NI2ktpY6q_DFnt7cZo9:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
