### PR TITLE
RgbdCamera: add support for SDF models to have multiple visuals

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5613)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@liangfok: can I ask you one more feature review? Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-:-Kg0Ju8G2q_Rq6ypVK8o:bv3k860)*

**Comment by liangfok** [comment]
First pass complete.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0OjYtmNRbGZPUK_Ch:-Kg0OjYtmNRbGZPUK_Ci:bd3i84q) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/rgbd_camera.cc#L356)):*
> ```cpp
> 
>     for (size_t i = 0; i < body->get_visual_elements().size(); ++i) {
>       if (i == 0) {
> ```

Instead of placing this if statement inside this for loop, can you place the body of this if statement immediately before this for loop?

---

*[drake/systems/sensors/rgbd_camera.cc, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0P2C7L3M-XwiKNm4t:-Kg0P2C7L3M-XwiKNm4u:b6d2jnu) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/rgbd_camera.cc#L357)):*
> ```cpp
>     for (size_t i = 0; i < body->get_visual_elements().size(); ++i) {
>       if (i == 0) {
>         for (auto& map : id_object_maps_) {
> ```

Consider changing the variable name "map" into something else since there's a class named `std::map`: http://en.cppreference.com/w/cpp/container/map.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0PXZQX5e7v6DCvZHI:-Kg0PXZQX5e7v6DCvZHJ:boh1733) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/test/rgbd_camera_test.cc#L159)):*
> ```cpp
> const int kHeight = 480;
> 
> struct UV {
> ```

Please add a brief comment explaining what this class is for. At first glance, I can't tell what "UV" means in this context.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 353 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0PsmaaWq5N2boDkFX:-Kg0PsmaaWq5N2boDkFY:b-7lb7o6) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/test/rgbd_camera_test.cc#L353)):*
> ```cpp
>   }
> 
>     // Verifies the color and depth of the image at the two visuals (boxes).
> ```

BTW, odd indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-:-Kg0QIKVvu233_a5lSq_:bvb1a6z)*

**Comment by kunimatsu-tri** [comment]
Addressed all the comments. PTAL.

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0OjYtmNRbGZPUK_Ch:-Kg0RikWNsjMVhydgVCZ:bvlm1kf) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/rgbd_camera.cc#L356)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Instead of placing this if statement inside this for loop, can you place the body of this if statement immediately before this for loop?
</blockquote></details>

Oh, right. I wonder why I couldn't come up with it. Thanks!

---

*[drake/systems/sensors/rgbd_camera.cc, line 357 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0P2C7L3M-XwiKNm4t:-Kg0RpWWqH-8uTLw0G_g:bb70xp9) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/rgbd_camera.cc#L357)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Consider changing the variable name "map" into something else since there's a class named `std::map`: http://en.cppreference.com/w/cpp/container/map.
</blockquote></details>

OMG!

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0PXZQX5e7v6DCvZHI:-Kg0SU3qQzl2IrV-4sfO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/test/rgbd_camera_test.cc#L159)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please add a brief comment explaining what this class is for. At first glance, I can't tell what "UV" means in this context.
</blockquote></details>

Done.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 353 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0PsmaaWq5N2boDkFX:-Kg0S-czr2bigtQds-mf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/02eeeaa23bba337865d7caedc0d4ffcc4da3f657/drake/systems/sensors/test/rgbd_camera_test.cc#L353)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, odd indentation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-:-Kg0TXi1cYs8Wy1N8IOT:b-y0j4qv)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-:-Kg0U6AZW58NH4W2AMoq:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
+@ggould-tri: platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-:-Kg0U9gc-cBzj0ciBiAl:b-szt60r)*

**Comment by ggould-tri** [comment]
:lgtm:; one minor comment below.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/rgbd_camera.cc, line 258 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0dyQatHiSWtU4RKD8:-Kg0dyQbHqNiOBd6xSZS:b-mv3vaf) ([raw file](https://github.com/robotlocomotion/drake/blob/67a2e85ca578a11b9e1b6f813e38fdde5a022488/drake/systems/sensors/rgbd_camera.cc#L258)):*
> ```cpp
>   vtkNew<vtkActor> terrain_actor_;
>   std::array<std::map<int, std::vector<vtkSmartPointer<vtkActor>>>, 2>
>       id_object_maps_;
> ```

FYI -- It was difficult for me to understand what this contained and was used for.  I suggest at least commenting what its two members are.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-:-Kg0e9nqGEqrqpab344g:b50pi55)*

**Comment by kunimatsu-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/rgbd_camera.cc, line 258 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0dyQatHiSWtU4RKD8:-Kg0mJvcGXIvGHtAq_7l:b-f8sf1p) ([raw file](https://github.com/robotlocomotion/drake/blob/67a2e85ca578a11b9e1b6f813e38fdde5a022488/drake/systems/sensors/rgbd_camera.cc#L258)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- It was difficult for me to understand what this contained and was used for.  I suggest at least commenting what its two members are.
</blockquote></details>

Added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/rgbd_camera.cc, line 258 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5613#-Kg0dyQatHiSWtU4RKD8:-Kg0mQ2lVhpDK7xWyIql:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/67a2e85ca578a11b9e1b6f813e38fdde5a022488/drake/systems/sensors/rgbd_camera.cc#L258)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- It was difficult for me to understand what this contained and was used for.  I suggest at least commenting what its two members are.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5613)*

**Pull request merged**
