### PR TITLE
Amend solvers/BUILD to tolerate a different SNOPT and optionally disable NLOPT

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6092)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6092#-:-Kk0z-shJTi_DPvwhRbb:b-9thol1)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.  (I'm on-call, so bumping ahead to someone with experience in this stack.)

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6092)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6092#-:-KkBr4oJHjG6HwQBdsSz:bnfp4nl)*

**Pull request merged**
