### PR TITLE
Add optitrack lcmtypes to drake-lcm-spy/drake-visualizer

### PR DESCRIPTION
**Pull request by sammy-tri**
I've been asked a few times about this functionality, and pointed people to patches I had on personal branches.  This kinda implies that I should push the changes in question to master.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7044)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@avalenzu for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7044#-:-KuL2LPC9uLf11GOiWd4:bvpmr17)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7044#-:-KuQHcp4GguvNso0RsZs:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review (tomorrow's reviewer based on schedule)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7044#-:-KuQIWVyLZQYfEM0c9Ft:b-gelnfu)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7044#-:-KuQWxMcF8xhxf8KKlk9:bnfp4nl)*

**Pull request merged**
