### PR TITLE
Moved timestamps to be first field in LCM message.

### PR DESCRIPTION
**Pull request by liangfok**
For context, see: https://github.com/RobotLocomotion/drake/pull/3464#issuecomment-247567046

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3475)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
LCM encodes messages in field-declaration order. If we change the field order in the message, folks will have to be sure to recompile all code that uses the message, and any binary recordings of the message will no longer load.

**Comment by liangfok** [comment]
Sounds like we need to add versioning to the messages. In fact, this should ideally be added to the upstream version of LCM itself.

I've added a CHANGELOG entry documenting this change.

+@jwnimmer-tri and +@russtedrake for review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3475#-:-KRmsrSccrZXGk5q2Mys:b-ip25vp)*

**Comment by jwnimmer-tri** [comment]
> Sounds like we need to add versioning to the messages.

That's not really the intent of LCM.

**Comment by liangfok** [comment]
Should we push the versioning of messages into the Drake layer by, for example, including a version number as a field within the message?

**Comment by jwnimmer-tri** [comment]
AIUI, the messages already have a hash to fail-fast when they change.  I'm not sure what a version number beyond that would do.

My conops for LCM is "only change messages when you really need to", and "LCM is a tight coupling, so don't expose it as an API".  The PR relates to the first part; the fact that some downstream might be using these relates to the second.

The edits look correct insofar as they go.  I'll less Russ decide the tradeoff here of breaking binary compat or not.

---

Reviewed 1 of 32 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3475#-:-KRn6ncCQSUt13KYfIbs:b-vmg0f3)*

**Comment by liangfok** [comment]
I was thinking we could analyze the raw bytes of the message to determine which version number it is prior to attempting to deserialize them into an LCM message object. That would be one way to do lacking the ability to upstream version numbers.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3475#-:-KRn7qHfsWM0cXlBNKFJ:b-geahef)*

**Comment by jwnimmer-tri** [comment]
With this technology, the better way to do that is to add the version number to the channel name, and keep around multiple versions of `*.lcm` files in-tree (drake_signal, drake_signal2, etc.).  It is easier for downstream that way.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3475#-:-KRn8FOjc6AJcOha4Y4y:b-vvm1vu)*

**Comment by liangfok** [comment]
SGTM. I'll also let @russtedrake decide whether to merge or close this PR.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3475#-:-KRn8j_F9869RCOuXACU:b1pqzem)*

**Comment by liangfok** [comment]
+@russtedrake to decide whether this PR should be merged or closed. It modifies the _order_ of fields within LCM messages, but not the names of the fields.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3475#-:-KRn8snVXTg8DETRl0WY:b-3fyj0z)*

**Comment by RussTedrake** [comment]
if you can confirm that it does not break backwards compatibility, then it’s ok to accept.  if there is any question, then we should not break backwards compatibility.

@rdeits probably knows the answer to this question.

- Russ

**Comment by rdeits** [comment]
I believe this *will* break backwards compatibility for those messages, so I wouldn't recommend making this change. 

As to your point about inspecting the messages, @liangfok, I have a terrifying prototype version of that implemented in Director: https://github.com/RobotLocomotion/director/blob/cf240fd4ebf4035f89b43f6da4755a0d0978e067/src/python/director/lcmUtils.py#L256
which inspects the LCM message fingerprint and searches the git history to find and compile a matching type definition. But it's not exactly efficient and probably not reliable.

**Comment by liangfok** [comment]
Wow! That is indeed terrifying! I am closing this issue in the name of not fixing what is not broken. Thanks for the comments.

**Pull request closed without merging**
