### PR TITLE
Rename BUILD to BUILD.bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  (This will be good feedback on whether mass renames in git cause pain for our developers' workflows.)

Fully automatic change, via:
```
$ find . \
  -name cc_toolchain -prune -o \
  -name BUILD -print0 |
  xargs -0 -n1 -I{} git mv {} {}.bazel
```

We avoid `cc_toolchain` because Bazel doesn't allow use of `BUILD.bazel` there.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7237)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for all review per rotation, please.

**Comment by jwnimmer-tri** [comment]
Interesting.  A different PR merged after this one.  GitHub showed that as a red-x conflict, even though "git rebase master" locally was able to figure it out.  I seems like PRs of this sort will have to win the Jenkins race in order to merge cleanly.  For this PR it's probably find to keep rebasing and merge off-hours; for the final #6996 PR it looks like I will need to disable all PRs for a few hours when we push that one through.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: For all

1) This is the type of PR for which it is better to be author than reviewer (I think I developed arthritis in my mouse clicking finger),
2) Simple and tedious may not be a lot better than complex,
3) This is going to cause a lot of merge headahces,  Heh, heh, heh.

---

Reviewed 218 of 218 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7237#-:-KwCaVMaNmfUF60-l-Jy:bqk23ei)*

**Comment by jwnimmer-tri** [comment]
Self-:car: approval.

> This is the type of PR for which it is better to be author than reviewer (I think I developed arthritis in my mouse clicking finger),

There is a "Mark all as reviewed", which along with "Show all files" is a good way to breeze though.

> This is going to cause a lot of merge headahces,

I want to find out!  I think it will prevent any other PR from merging without a re-push, but I _hope_ that local git operations do the obvious and easy thing.  We will see!

**Pull request merged**
