### PR TITLE
Accuracy fix

### PR DESCRIPTION
**Pull request by edrumwri**
Attempt to fix -Wmaybe-uninitialized error resulting from correct (!) use of optional

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6245)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@liangfok for feature review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6245#-:-KljDm4Llz5ABN_L-BYt:ban0tkg)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/analysis/simulator.h, line 592 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6245#-KljNbp72Eo7N-Wo8Xsd:-KljNbp8BngSNuZnnJ-i:b-4aiqv2) ([raw file](https://github.com/robotlocomotion/drake/blob/c6712974c63f6cd375e6ebc2e978f99dfbac10e4/drake/systems/analysis/simulator.h#L592)):*
> ```objc
>   // " [-Werror=maybe-unitialized]"
>   #pragma GCC diagnostic push
>   #pragma GCC diagnostic ignored "-Wmaybe-unitialized"
> ```

Typo: uninitialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6245)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6245)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please.

**Comment by liangfok** [comment]
`memcheck` is still complaining.  Maybe because of a typo?

**Comment by sherm1** [comment]
I attempted to fix the typos and will re-run memcheck.

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please.

**Comment by liangfok** [comment]
I believe this PR needs to be re-based with master. Meanwhile, I'll apply the "curate commits" label.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6245#-:-KlkK2khyx4owP6VHcTU:bnfp4nl)*

**Comment by sherm1** [comment]
Platform :lgtm:. I see only one file modified so I think this can be safely merged. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6245#-:-KlkKaEV5TpHIlPGrLkV:bgzeh9j)*

**Pull request merged**
