### PR TITLE
Make dual_kuka_simulation_test flaky

### PR DESCRIPTION
**Pull request by m-chaturvedi**
[Failure](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-tsan/457/consoleText), [Reason](https://github.com/RobotLocomotion/drake/pull/7311)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7391)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7391#-:-KxtPA4zE4TZbMD3-o2N:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@soonho-tri for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7391#-:-Kxx4u0I8w-JAPIxMvmG:bxwr5c8)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7391#-:-KxxBeup_ur_l527iTjv:bnfp4nl)*

**Comment by RussTedrake** [comment]
had to laugh when I saw this one.  Hopefully you "declared" the test as flaky, but did not actually make it flaky.  ;-)

**Comment by soonho-tri** [comment]
:-)

Bazel documentation says `*Marks* test as flaky`, not `*Makes* test as flaky`: https://docs.bazel.build/versions/master/be/common-definitions.html

**Pull request merged**
