### PR TITLE
Joint API to retrieve viscous damping.

### PR DESCRIPTION
**Pull request by amcastro-tri**
API to retrieve viscous damping at the `Joint` level.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please (Monday)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019#-:-N0HZitN8krCEStkNI3P:b-kqe6kz)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a request to deprecate the constructor. +@sammy-tri for platform review, please.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019#-:-N0_y5yq1GuYCx6C457H:buivwvm)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri and @sammy-tri)

___
*[`multibody/tree/joint.h` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0_tUIU-8W88qy5W-bm:-N0_tUIU-8W88qy5W-bn:b-e1rol6) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/joint.h#L126)):*
> ```objc
>         frame_on_parent_(frame_on_parent),
>         frame_on_child_(frame_on_child),
>         damping_(std::move(damping)),
> ```

Since `Joint` is public I think changing this constructor would require proper deprecation notice, no?

You could deprecate this constructor and create a new one with the additional damping argument. Also, in the new constructor you could change all of the `*_limits` arguments to pass by value and give them the same `std::move` treatment.
___
*[`multibody/tree/test/screw_joint_test.cc` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0_xb_f3qncytGgiGpO:-N0_xb_f3qncytGgiGpP:b-4t8nn4) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/test/screw_joint_test.cc#L107)):*
> ```cpp
>   EXPECT_EQ(joint_->acceleration_upper_limits(),
>             Vector1d::Constant(kAccelerationUpperLimit));
>   EXPECT_EQ(joint_->damping(), kDamping);
> ```

nit: Duplicate damping API test outside of the new Damping test case.
___
*[`multibody/tree/test/universal_joint_test.cc` line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0_xxQWEgQpMMCCkSti:-N0_xxQWEgQpMMCCkStj:b-42aqrx) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/test/universal_joint_test.cc#L115)):*
> ```cpp
>   EXPECT_EQ(joint_->acceleration_upper_limits(),
>             Vector2d::Constant(kAccelerationUpperLimit));
>   EXPECT_EQ(joint_->damping(), kDamping);
> ```

nit: ditto duplicate damping test here.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri, @joemasterjohn, and @sammy-tri)

___
*[`multibody/tree/joint.h` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0_tUIU-8W88qy5W-bm:-N0b0hW03_MUleHvleB6:b-63zw9b) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/joint.h#L126)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Since `Joint` is public I think changing this constructor would require proper deprecation notice, no?

You could deprecate this constructor and create a new one with the additional damping argument. Also, in the new constructor you could change all of the `*_limits` arguments to pass by value and give them the same `std::move` treatment.
</blockquote></details>

I could either deprecate or have a default constructor for the zero damping case. 
WDYT?

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @amcastro-tri and @joemasterjohn)

___
*[`multibody/tree/joint.h` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0b1_Ht514zV-K3RZAm:-N0b1_Ht514zV-K3RZAn:b-40jahw) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/joint.h#L126)):*
> ```objc
>         frame_on_parent_(frame_on_parent),
>         frame_on_child_(frame_on_child),
>         damping_(std::move(damping)),
> ```

Should there be a check on the size of `damping_` in the constructor?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @joemasterjohn and @sammy-tri)

___
*[`multibody/tree/joint.h` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0_tUIU-8W88qy5W-bm:-N0bQlIJAYumG07jb_72:b-fpk2jm) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/joint.h#L126)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I could either deprecate or have a default constructor for the zero damping case. 
WDYT?
</blockquote></details>

Added back the constructor since it's useful.
___
*[`multibody/tree/joint.h` line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17019#-N0b1_Ht514zV-K3RZAm:-N0bRfjjCX__3AtKvJrt:bn1h5gr) ([raw file](https://github.com/robotlocomotion/drake/blob/10a5927bb508d3c3d8da9b20a6673700ae3d8a2d/multibody/tree/joint.h#L126)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should there be a check on the size of `damping_` in the constructor?
</blockquote></details>

Check added.

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (assuming Joe is OK with how the constructor situation turned out)

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019#-:-N0bf5OF9J3YsXMIBMIn:b-3xw4pi)* status: 1 unresolved discussion (waiting on @joemasterjohn)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17019)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn (waiting on @amcastro-tri)

**Pull request merged**
