### PR TITLE
drake_visualizer: Ensure all upstream Python dependencies are properly exposed to Bazel.

### LINKED ISSUE #7989: drake_visualizer run via `bazel-bin` cannot import `robotlocomotion` lcmtypes
When run via `bazel run`, `show_images.py` can be used:
```
$ bazel run //tools:drake_visualizer -- --script ~+/systems/sensors/visualization/show_images.py
```

However, through `bazel-bin/`, it is not found:
```
$ ./bazel-bin/tools/drake_visualizer --script ~+/systems/sensors/visualization/show_images.py
...
ImportError: No module named robotlocomotion
```

Will look into this.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #7989.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7990)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7990#-:-L4mQCCV4r_VqoxMd-Y4:b-zd9orj)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7990#-:-L4pnXKvCigZxUlYcH4g:bnfp4nl)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/BUILD.bazel, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7990#-L4pocN40sgoJctEN6q8:-L4pocN40sgoJctEN6q9:b-107a3p) ([raw file](https://github.com/robotlocomotion/drake/blob/09c0718693503eb81944c3fc9e59cc201e84fd87/tools/BUILD.bazel#L23)):*
> ```Python
>         "//drake/lcmtypes:lcmtypes_py",
>         "@optitrack_driver//lcmtypes:py_optitrack_lcmtypes",
>         "@drake_visualizer//:drake_visualizer_python_deps",
> ```

BTW Alphabetize, perhaps?

---

*[tools/workspace/drake_visualizer/repository.bzl, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7990#-L4poRdBLlwrjqrAtECp:-L4poRdBLlwrjqrAtECq:bygb63x) ([raw file](https://github.com/robotlocomotion/drake/blob/09c0718693503eb81944c3fc9e59cc201e84fd87/tools/workspace/drake_visualizer/repository.bzl#L69)):*
> ```Python
>         "@lcm//:lcm-python",
>         "@lcmtypes_bot2_core//:lcmtypes_bot2_core_py",
>         # TODO(eric.cousineau): Expose VTK Python libraries here.
> ```

BTW For Linux. The drake-visualizer binary has logic internally to find system VTK on macOS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7990#-:-L4pob4omBdL6ZQo34-s:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/BUILD.bazel, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7990#-L4pocN40sgoJctEN6q8:-L4prX1W-bfn6JrZXFqQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09c0718693503eb81944c3fc9e59cc201e84fd87/tools/BUILD.bazel#L23)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Alphabetize, perhaps?
</blockquote></details>

Done.

---

*[tools/workspace/drake_visualizer/repository.bzl, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7990#-L4poRdBLlwrjqrAtECp:-L4proIC0pi2i7uCZRT4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09c0718693503eb81944c3fc9e59cc201e84fd87/tools/workspace/drake_visualizer/repository.bzl#L69)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW For Linux. The drake-visualizer binary has logic internally to find system VTK on macOS.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7990)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7990)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7990)*

**Pull request merged**
