### PR TITLE
 Add cmake and yaml-cpp to install_prereqs scripts and update documentation

### PR DESCRIPTION
**Pull request by jamiesnape**
See also #7293 and #7306.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7307)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@soonho-tri and +@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm: feature and platform for the Xenial changes; tested locally on Xenial.

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7307#-:-KwuKTbmmMck07LMlrWj:behgs6d)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7307#-KwuKbLdgKkQ_xIKMfse:-KwuKbLdgKkQ_xIKMfsf:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/986718655f1925401cefce55446b57917fa37cd2/setup/mac/install_prereqs.sh#L22)):*
> ```Shell
> 
> if [[ ! -f /usr/include/expat.h || ! -f /usr/include/zlib.h ]]; then
>   echo "Command Line Tools for Xcode are NOT installed" >&2
> ```

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7307#-:-KwuKgQjstzXD6J3Ze-M:bnfp4nl)*

**Pull request merged**
