### PR TITLE
pydrake manipulation: Bind differential IK

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
From @avalenzu's branch, so that we can create utility notebooks similar to what he has done.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@siyuanfeng-tri for feature review, please.
+@sammy-tri for platform review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021#-:-LFJh5YJDL_Wp6mga3tw:b-d76w32)*

**Comment by siyuanfeng-tri** [comment]
i think @avalenzu might be more appropriate for this, i am not familiar with python binding at all.. 

---

Reviewed 6 of 8 files at r1.
Review status: all discussions resolved, LGTM missing from assignee sammy-tri, LGTM missing from assignee siyuanfeng-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021#-:-LFJig8WDzVXX6rO_xO_:bfs4pg9)*

**Comment by EricCousineau-TRI** [comment]
Sounds good; talked to Sammy, and he said he's down to both reveiws.

-@siyuanfeng-tri for fetaure review

---

Review status: all discussions resolved, LGTM missing from assignee sammy-tri, LGTM missing from assignee siyuanfeng-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021#-:-LFJkxv3A45xyOsYLpwm:b8om370)*

**Comment by sammy-tri** [comment]
I'm vaguely surprised that this is sufficiently useful without the RBT/MBT overloads also being exported, but I'm not sure that counts as defective.  :lgtm: with one nit.

---

Reviewed 8 of 8 files at r1.
Review status: 1 unresolved discussion, platform LGTM from [sammy-tri]

---

*[bindings/pydrake/manipulation/test/planner_test.py, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9021#-LFJqLQk4x5jLuOIqvuG:-LFJqLQk4x5jLuOIqvuH:b-uz9wqo) ([raw file](https://github.com/robotlocomotion/drake/blob/7b4b9f453a1f1d0c7aace143a4334d6bf1896171/bindings/pydrake/manipulation/test/planner_test.py#L23)):*
> ```Python
>         self.assertEqual(obj.status, enum.kSolutionFound)
> 
>         # Test parmaeters.
> ```

nit: typo "parmaeters"

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021#-:-LFJqsJgC2BXQ1cQxQRN:bb3d3hc)*

**Comment by EricCousineau-TRI** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri]

---

*[bindings/pydrake/manipulation/test/planner_test.py, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9021#-LFJqLQk4x5jLuOIqvuG:-LFJv37hDFkNIiUxTvPI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b4b9f453a1f1d0c7aace143a4334d6bf1896171/bindings/pydrake/manipulation/test/planner_test.py#L23)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: typo "parmaeters"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9021)*

**Pull request merged**
