### PR TITLE
Fixed some mistakes in the build-from-source instructions.

### PR DESCRIPTION
**Pull request by liangfok**
This addresses some of the issues in #2768. It does not touch the MATLAB-issues; that will be in a future PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2769)

### CODE REVIEW

**Comment by liangfok** [comment]
+@hongkai-dai for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2769#-:-KMMSGZhts5Z6QIFNb63:1278764365)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2769#-:-KMMWqxZzTr-RlWXWUyc:1417088721)*

**Comment by liangfok** [comment]
I believe the CI failure is a flake (tracker: https://github.com/RobotLocomotion/drake/issues/2771).

Thus, since tomorrow is Monday, +@sherm1 for platform review / merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2769#-:-KMMdaTa5s54LoAaZw2s:-2099189975)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2769#-:-KMNAbSHyiF8RXWJaZcn:1417088721)*

**Comment by sherm1** [comment]
Not sure if CI fail is a flake but in any case it isn't caused by this PR! Merging.

**Pull request merged**
