### PR TITLE
[doc] Add release notes v1.11.0

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.11.0.md` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBYNaq1Qswbl7tO3ny:-NJBYNaq1Qswbl7tO3nz:bwsekov) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L12)):*
> ```Markdown
> # Breaking changes since v1.10.0
> 
> * A QuaternionFloatingJoint is added for each free body. MultibodyPlant::num_joints() will change in all existing plants that had previously declared at least one free body. `is_floating` is explicitly declared to mean: is mobilized by a 6-dof mobilzer AND the parent body of the mobilizer is world. ([#18390][_#18390])
> ```

minor: we don't normally talk about "mobilizers" to users -- those are intended to be internal. Better to say "joint" here.

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) 

Tagging a few feature owners for review.

+@ericcousineau-tri
+@seancurtis-tri 
+@joemasterjohn
+@sammy-tri 
+@rpoyner-tri
+@hongkai-dai 

We can target 12-14 as release date if all is well.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJBi-bgB0aUIH3StNr4:b-285u0e)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform),hongkai-dai,joemasterjohn,sammy-tri(platform),rpoyner-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @rpoyner-tri, @sammy-tri, @SeanCurtis-TRI, and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBZmP66_fpG9eEpYqV:-NJBZmP78loZWyi-UHWU:b-p4kaf9) (no related file):*
@ericcousineau-tri thanks for the review. Somehow I see your comments in github but not reviewable. Is that the case for you too?

___
___
*[`doc/_release-notes/v1.11.0.md` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBYNaq1Qswbl7tO3ny:-NJBhw7n2YpUzo64sLEy:ba4di8c) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: we don't normally talk about "mobilizers" to users -- those are intended to be internal. Better to say "joint" here.
</blockquote></details>

Done thanks.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: on solvers part.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJBju7M6wz9JHij2LMd:b8xwai1)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @joemasterjohn, @rpoyner-tri, @sammy-tri, @SeanCurtis-TRI, and @sherm1)

**Comment by EricCousineau-TRI** [comment]
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, that's weird! They show up as a draft in Reviewable - maybe I exited too quickly, or cloud nuggets weren't happy?

I will republish at possible cost of redundant noise.
</blockquote></details>

Done. Good news is that it now shows up on Reviewable (visible via private browsing) and didn't make new GitHub spam.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: on bindings and some other small bits

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJBlWCl4Mapxk2dZfj_:b-nsajym)* status: 5 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),SeanCurtis-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @rpoyner-tri, @sammy-tri, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`doc/_release-notes/v1.11.0.md` line 118 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBlQEo-vnNo-ggOjNG:-NJBlQEo-vnNo-ggOjNH:boahnyr) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L118)):*
> ```Markdown
> Fixes
> 
> * Add missing bindings to UnitInertia ([#18341][_#18341])
> ```

nit Given that this is just missing bindings, consider removing this listing? (defer to API enumeration below)
___
*[`doc/_release-notes/v1.11.0.md` line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBlUQdDdPrDjMKgyXu:-NJBlUQdDdPrDjMKgyXv:boahnyr) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L120)):*
> ```Markdown
> * Add missing bindings to UnitInertia ([#18341][_#18341])
> * Add Preferred Ordering mechanism and tests ([#18357][_#18357])
> * Bind CacheEntry.Eval for better workflow ([#18354][_#18354])
> ```

nit Given that this is just missing bindings, consider removing this listing? (defer to API enumeration below)
___
*[`doc/_release-notes/v1.11.0.md` line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBl8dh9RnPfRBi8K1J:-NJBl8di3xc8VLp9jhQE:b23d9l0) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L139)):*
> ```Markdown
> * pydrake.systems.framework.System.AllocateInputVector ([#18430][_#18430])
> * pydrake.systems.framework.InputPort.Allocate ([#18431][_#18431])
> * pydrake.geometry.optimization.HPolyhedron.FindRedundant ([#18432][_#18432])
> ```

nit Should be alpha sorted?
___
*[`doc/_release-notes/v1.11.0.md` line 153 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBlGA_2jrcRFkUWK6g:-NJBlGAaD65qRlzNSaGR:b-9qvdzy) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L153)):*
> ```Markdown
> * Remove libcurl dependency ([#18441][_#18441])
> * Use host OS VTK 9.1 when on Ubuntu 22.04 ([#18340][_#18340])
> * Update optitrack_driver for skeleton support ([#18330][_#18330])
> ```

BTW Not sure if this should follow `Upgrade` convention for externals?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),SeanCurtis-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @rpoyner-tri, @sammy-tri, and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.11.0.md` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA8Inx2Gk5taeFsnxL:-NJBlTt9B2EYGH-sPgNv:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I think this should be expanded a bit more just for user-friendly-ness e.g.:

```
- If you loop through the joints in the plant, you may need to update your code to explicitly check if the child joint is floating and ignore those joints (if they break your current analysis).
```
(this was the change we made per @sammy-tri's analysis of Anzu code w.r.t. collision remover API authored by @ggould-tri)
</blockquote></details>

Done, thanks.
___
*[`doc/_release-notes/v1.11.0.md` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA8LtR1XOxqaBE0qkt:-NJBlOXJCpOCUdrqtx4A:bxgq5w4) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Spelling, "mobilzer" => "mobilizer"
</blockquote></details>

Done. Replaced "mobilizer" with "joint"
___
*[`doc/_release-notes/v1.11.0.md` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA8wa2BwO_CzAsFmz8:-NJBlVLu3Fo1C27zvDGp:b3zwcvx) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear what the takeaway is here. Can this be expanded?
</blockquote></details>

@sammy-tri could you provide some thoughts on this one? Thanks!
___
*[`doc/_release-notes/v1.11.0.md` line 99 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA939h-5XjSmWmatzM:-NJBlaeK4RdjlFpvulP0:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L99)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Trailing whitespace.
</blockquote></details>

Done
___
*[`doc/_release-notes/v1.11.0.md` line 111 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA95XrB6byY_FgMUrX:-NJBlcqN1WfKLPOhwKaW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L111)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I don't think we explicitly list the PRs that are solely binding additions; instead, we defer those to "Newly bound"

e.g. in https://drake.mit.edu/release_notes/v1.9.0.html#pydrake-bindings, the only listed PRs are those which change functionality beyond exposure of new API
</blockquote></details>

Done.
___
*[`doc/_release-notes/v1.11.0.md` line 118 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBlQEo-vnNo-ggOjNG:-NJBmcqB53SmBoozIviz:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L118)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Given that this is just missing bindings, consider removing this listing? (defer to API enumeration below)
</blockquote></details>

Done
___
*[`doc/_release-notes/v1.11.0.md` line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBlUQdDdPrDjMKgyXu:-NJBmdOR7nvLBJxRDmyS:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L120)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Given that this is just missing bindings, consider removing this listing? (defer to API enumeration below)
</blockquote></details>

Done
___
*[`doc/_release-notes/v1.11.0.md` line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBl8dh9RnPfRBi8K1J:-NJBnOlaANiBd8U2IfL3:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L139)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should be alpha sorted?
</blockquote></details>

Done
___
*[`doc/_release-notes/v1.11.0.md` line 153 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJBlGA_2jrcRFkUWK6g:-NJBmhtU83Llxyz6xgV1:btk34ev) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L153)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Not sure if this should follow `Upgrade` convention for externals?
</blockquote></details>

Done. I don't see reason not to.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),SeanCurtis-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @rpoyner-tri, @sammy-tri, and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: on planners and geometry.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJCEKKz9bDOQJhenLOJ:b-erny2i)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),SeanCurtis-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @joemasterjohn, @sammy-tri, and @SeanCurtis-TRI)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJCNLCY279gVrqn1YMK:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`doc/_release-notes/v1.11.0.md` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA8wa2BwO_CzAsFmz8:-NJCLhFKEt5g62RvNNqP:b1jzihq) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@sammy-tri could you provide some thoughts on this one? Thanks!
</blockquote></details>

Existing LCM logs (of which there shouldn't really be any, I checked with the non-TRI optitrack users which I was aware of) won't decode using the new definitions.  C++ code built against old code will need to be recompiled for compatibility.  However, the changes to the existing types were only to add new fields, the existing fields have no behavioral changes so users which don't care about the additional data shouldn't have to change any code.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),joemasterjohn, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`doc/_release-notes/v1.11.0.md` line 66 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJClDrIACdTqSWsIUmP:-NJClDrIACdTqSWsIUmQ:boq0yqu) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L66)):*
> ```Markdown
> * Add quaternion floating joint ([#18279][_#18279])
> * Add SDFormat support for weld-type `//world/joint` ([#18322][_#18322])
> * Calculate SpatialInertia from Shape and TriangleMesh ([#18345][_#18345])
> ```

nit, is it intentional to shorten `TriangleSurfaceMesh` to `TriangleMesh` in the message?  The spelling in the code is `TriangleSurfaceMesh`.



_Suggestion:_
```Markdown
* Calculate SpatialInertia from Shape and TriangleSurfaceMesh ([#18345][_#18345])
```

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: on Multibody Dynamics and Geometry and my breaking change.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJCpcCx7URGK8eTQu--:bbo5c2k)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @SeanCurtis-TRI, and @xuchenhan-tri)

___
*[`doc/_release-notes/v1.11.0.md` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJCnJRR5_hQy4BqM_zY:-NJCnJRR5_hQy4BqM_zZ:bxhksr6) ([raw file](https://github.com/robotlocomotion/drake/blob/0c45790546071647401dc3ac5d8db84be3ed87a7/doc/_release-notes/v1.11.0.md#L13)):*
> ```Markdown
> 
> * A QuaternionFloatingJoint is added for each free body. MultibodyPlant::num_joints() will change in all existing plants that had previously declared at least one free body. `is_floating` is explicitly declared to mean: is outboard to a 6-dof joint AND the parent body of the joint is world. ([#18390][_#18390])
>   - If your code loops through all joints in the plant, you may need to update your code to explicitly check if the child of a joint is floating and ignore those joints (if they break your current analysis).
> ```

nit maybe add this small comment (feel free to rewrite):
Free body APIs that `MultibodyPlant` provides (`SetFreeBodyPose()`, `SetFreeBodySpatialVelocity()`, etc.) still exist and are equivalent alternatives to the corresponding `QuaternionFloatingJoint` APIs that affect a given body. If you wrote code that had separate logic for handling dofs corresponding to bodies with explicitly created joints using `Joint` APIs and dofs corresponding to floating bodies using plant's free body API, you might be doing some duplicate work.
___
*[`doc/_release-notes/v1.11.0.md` line 64 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJCp5hV28Am8ka5lArM:-NJCp5hV28Am8ka5lArN:b-oli2ce) ([raw file](https://github.com/robotlocomotion/drake/blob/0c45790546071647401dc3ac5d8db84be3ed87a7/doc/_release-notes/v1.11.0.md#L64)):*
> ```Markdown
> New features
> 
> * Add quaternion floating joint ([#18279][_#18279])
> ```

My original commit message should have been better, but here you can put:



_Suggestion:_
```Markdown
Adds a new 6-dof joint type: QuaternionFloatingJoint
```
___
*[`doc/_release-notes/v1.11.0.md` line 69 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJCpsTi8Bpihc924ncQ:-NJCpsTi8Bpihc924ncR:b-qjy5fc) ([raw file](https://github.com/robotlocomotion/drake/blob/0c45790546071647401dc3ac5d8db84be3ed87a7/doc/_release-notes/v1.11.0.md#L69)):*
> ```Markdown
> * Add a QuaternionFloatingJoint for each free body ([#18390][_#18390])
> * Compute generalized forces resulting from MultibodyForce ([#18406][_#18406])
> * Add PrismaticSpring and support its SDFormat parsing ([#18240][_#18240])
> ```

nit: maybe for user clarity



_Suggestion:_
```Markdown
PrismaticSpring force element
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.11.0.md` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJA8wa2BwO_CzAsFmz8:-NJD8E3375NPR2AmLGWQ:b-um5ff8) ([raw file](https://github.com/robotlocomotion/drake/blob/e34b450618444b3e800346b21d53438cd4d146bf/doc/_release-notes/v1.11.0.md#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Existing LCM logs (of which there shouldn't really be any, I checked with the non-TRI optitrack users which I was aware of) won't decode using the new definitions.  C++ code built against old code will need to be recompiled for compatibility.  However, the changes to the existing types were only to add new fields, the existing fields have no behavioral changes so users which don't care about the additional data shouldn't have to change any code.
</blockquote></details>

I added a paraphrased note.
___
*[`doc/_release-notes/v1.11.0.md` line 66 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJClDrIACdTqSWsIUmP:-NJD8iAIEe7Pk4aPBnH2:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8e00da4a4b6baf2063ae9de093755a14aab70f/doc/_release-notes/v1.11.0.md#L66)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit, is it intentional to shorten `TriangleSurfaceMesh` to `TriangleMesh` in the message?  The spelling in the code is `TriangleSurfaceMesh`.
</blockquote></details>

Done, thanks.
___
*[`doc/_release-notes/v1.11.0.md` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJCnJRR5_hQy4BqM_zY:-NJD7Z3BBe7NOfGwpa3w:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/0c45790546071647401dc3ac5d8db84be3ed87a7/doc/_release-notes/v1.11.0.md#L13)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit maybe add this small comment (feel free to rewrite):
Free body APIs that `MultibodyPlant` provides (`SetFreeBodyPose()`, `SetFreeBodySpatialVelocity()`, etc.) still exist and are equivalent alternatives to the corresponding `QuaternionFloatingJoint` APIs that affect a given body. If you wrote code that had separate logic for handling dofs corresponding to bodies with explicitly created joints using `Joint` APIs and dofs corresponding to floating bodies using plant's free body API, you might be doing some duplicate work.
</blockquote></details>

Done, thanks.
___
*[`doc/_release-notes/v1.11.0.md` line 64 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJCp5hV28Am8ka5lArM:-NJD8UqQ1wbVa-4Qj0xq:b-iry7x8) ([raw file](https://github.com/robotlocomotion/drake/blob/0c45790546071647401dc3ac5d8db84be3ed87a7/doc/_release-notes/v1.11.0.md#L64)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

My original commit message should have been better, but here you can put:
</blockquote></details>

Done, thanks
___
*[`doc/_release-notes/v1.11.0.md` line 69 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJCpsTi8Bpihc924ncQ:-NJD8nMV9gMb5UwRjq-M:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/0c45790546071647401dc3ac5d8db84be3ed87a7/doc/_release-notes/v1.11.0.md#L69)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: maybe for user clarity
</blockquote></details>

Done, thanks.

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai, @SeanCurtis-TRI, and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.11.0.md` line 19 at r5](https://reviewable.io/reviews/robotlocomotion/drake/18438#-NJF4Ei36fGViqUxzksD:-NJGhKb9BgrruQgRaFn6:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/aad07a08e0edcf7d7873b5a60ee2d35c073224f2/doc/_release-notes/v1.11.0.md#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit " C++ code built against previous Drake versions will need to be recompiled for compatibility" is true of most of these changes.

Consider removing that sentence?
</blockquote></details>

Done, thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, @joemasterjohn, @sammy-tri, and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
-@seancurtis-tri who's ooo.
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18438#-:-NJGybgc7lqKTDZV8PF5:b-4y1gzx)* status: labeled "do not merge" (waiting on @hongkai-dai)

**Comment by xuchenhan-tri** [comment]
-(status: do not merge)

**Pull request merged**
