### PR TITLE
symbolic.py: Bind and test symbolic math functions

### LINKED ISSUE #8144: python bindings for trig in symbolic expressions
Would be nice to have support for more powerful functions with the symbolic stuff in Python! In particular, having trig is enough to do coordinate transformations.

### PR DESCRIPTION
**Pull request by soonho-tri**
Closes #8144

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8179)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@gizatt for feature-review, please.

**Comment by gizatt** [comment]
:lgtm: Thanks for adding these!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-:-L6IL_Qw1G6lAl1rn5oD:b-v8uoci)*

**Comment by soonho-tri** [comment]
+@ericcousineau-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/symbolic_py.cc, line 370 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-L6IMmoX1qLtIb4k7UwL:-L6IMmoX1qLtIb4k7UwM:bbquryb) ([raw file](https://github.com/robotlocomotion/drake/blob/95824b27dd849da91c82f0095e87f1ba292a228a/bindings/pydrake/symbolic_py.cc#L370)):*
> ```cpp
>       .def("exp", &symbolic::exp)
>       .def("sqrt", &symbolic::sqrt)
>       .def("pow", py::overload_cast<const Expression&, const Expression&>(
> ```

@ericcousineau-tri , I found that `&symbolic::pow` fails (compiler says that it fails to deduce type of it). So I've added `overload_cast` here, but I still don't understand why this is necessary.

---

*[bindings/pydrake/test/symbolic_test.py, line 93 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-L6IMB950xzdXN0MdGcY:-L6IMB950xzdXN0MdGcZ:b-ytt5xw) ([raw file](https://github.com/robotlocomotion/drake/blob/95824b27dd849da91c82f0095e87f1ba292a228a/bindings/pydrake/test/symbolic_test.py#L93)):*
> ```Python
>         e_x = sym.Expression(x)
>         e_y = sym.Expression(y)
>         self.assertEqual(str(sym.sin(e_x)), "sin(x)")
> ```

@gizatt , FYI, `sym.sin(x)` fails because `x` is of `symbolic::Variable`. Since `Expression` class provides an non-explicit constructor `Expression(const Variable&)`, I expected it would work but it turns out that it's not the case. I'm trying to find a general solution for this one. I'll open another PR when I find a good solution.

/cc @ericcousineau-tri 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-:-L6ILv8M7iBZeyqJhlf6:b-6wt0vm)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending addition of `py::implicitly_convertible` since it's available.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 370 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-L6IMmoX1qLtIb4k7UwL:-L6IlIISDGdP23b_QOQ3:b-vyg6t2) ([raw file](https://github.com/robotlocomotion/drake/blob/95824b27dd849da91c82f0095e87f1ba292a228a/bindings/pydrake/symbolic_py.cc#L370)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@ericcousineau-tri , I found that `&symbolic::pow` fails (compiler says that it fails to deduce type of it). So I've added `overload_cast` here, but I still don't understand why this is necessary.
</blockquote></details>

OK TBH, I still haven't figure out precisely when this happens, especially since there are no sibling overloads of `symbolic::pow`, additionally when things like `pydrake::overload_cast_explicit<>` is needed.

---

*[bindings/pydrake/test/symbolic_test.py, line 93 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-L6IMB950xzdXN0MdGcY:-L6ImRUK5S-Lr9tVdYtZ:bf8clhj) ([raw file](https://github.com/robotlocomotion/drake/blob/95824b27dd849da91c82f0095e87f1ba292a228a/bindings/pydrake/test/symbolic_test.py#L93)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@gizatt , FYI, `sym.sin(x)` fails because `x` is of `symbolic::Variable`. Since `Expression` class provides an non-explicit constructor `Expression(const Variable&)`, I expected it would work but it turns out that it's not the case. I'm trying to find a general solution for this one. I'll open another PR when I find a good solution.

/cc @ericcousineau-tri 
</blockquote></details>

Sorry for not getting back to you earlier! It ends up that `py::implicitly_convertible` is more comprehensive than I thought:
http://pybind11.readthedocs.io/en/stable/advanced/classes.html#implicit-conversions

I originally thought that it only works if both `A` and `B` are custom types; however, it actually only needs `B` to be a custom type, `A` can be any type.

So this should make it work:
```
py::implicitly_convertible<Variable, Expression>();
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-:-L6Imuyk9cOe35l3H5e7:b8gg6wq)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/test/symbolic_test.py, line 93 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-L6IMB950xzdXN0MdGcY:-L6InLL--BKUxmhdj5OO:bdohlwg) ([raw file](https://github.com/robotlocomotion/drake/blob/95824b27dd849da91c82f0095e87f1ba292a228a/bindings/pydrake/test/symbolic_test.py#L93)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry for not getting back to you earlier! It ends up that `py::implicitly_convertible` is more comprehensive than I thought:
http://pybind11.readthedocs.io/en/stable/advanced/classes.html#implicit-conversions

I originally thought that it only works if both `A` and `B` are custom types; however, it actually only needs `B` to be a custom type, `A` can be any type.

So this should make it work:
```
py::implicitly_convertible<Variable, Expression>();
```
</blockquote></details>

GREAT!!! I'll open another PR which uses that! (and clean up bunch of redundant overloads in the file) Thank you!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179)*

**Comment by EricCousineau-TRI** [comment]
BTW Would it make sense to incorporate the conversion here, since this PR is relatively small?

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8179#-:-L6J7jvY0jQF53_XlnUN:b-b43q1t)*

**Comment by EricCousineau-TRI** [comment]
Nice!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[bindings/pydrake/test/symbolic_test.py, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8179#-L6KXUfZKdcZ6si2IEIh:-L6KXUfZKdcZ6si2IEIi:b-8081gp) ([raw file](https://github.com/robotlocomotion/drake/blob/eb0bcee87f646b3abf4b1876e3179b3a61cdd9c8/bindings/pydrake/test/symbolic_test.py#L112)):*
> ```Python
>         self.assertEqual(sym.floor(v_x), np.floor(v_x))
>         self.assertEqual(sym.if_then_else(
>           sym.Expression(v_x) > sym.Expression(v_y),
> ```

BTW Should this hanging indent be 4 spaces?
(And rather than using a visual indent, can you make the whole thing hanging?

```
self.assertEqual(
    sym.if_then_else(
        sym.Expression(v_x) > sym.Expression(v_y),
        v_x, v_y),
    v_x if v_x > v_y else v_y)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8179#-:-L6KXp4g65ivh3WnvBxu:b-83sjoh)*

**Comment by EricCousineau-TRI** [comment]
Closes #8144
Closes #8187

(@soonho-tri I believe you have to use "Closes" rather than "Closing".)

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/test/symbolic_test.py, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8179#-L6KXUfZKdcZ6si2IEIh:-L6Ltyp7udWu-c4H-nRx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb0bcee87f646b3abf4b1876e3179b3a61cdd9c8/bindings/pydrake/test/symbolic_test.py#L112)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should this hanging indent be 4 spaces?
(And rather than using a visual indent, can you make the whole thing hanging?

```
self.assertEqual(
    sym.if_then_else(
        sym.Expression(v_x) > sym.Expression(v_y),
        v_x, v_y),
    v_x if v_x > v_y else v_y)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8179)*

**Comment by soonho-tri** [comment]
Updated the PR description. BTW, #8187 needs more work.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8179#-:-L6Lu5ppim4BF7H1R_hh:b-8so0ae)*

**Pull request merged**
