### PR TITLE
[parsing] Fix typos in drake:ball_constraint documentation

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20675)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@joemasterjohn for feature review.

These were noticed while working on urdf schema checking.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20675#-:-Nl_pNthE3ZX0R6RHhdQ:b9fanr5)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: feature. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20675#-:-Nm1rPjNBOhVLF-LkV4Q:b-5glron)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review Wednesday. I'm on-call today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20675#-:-Nm2K-te2NZ6tmKim2aN:b-1hkayg)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20675#-:-Nm4O61qCqdFERo8Erlw:b-safpmt)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20675#-:-Nm79jCjB7wSbr6MHxQh:b8qx53o)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn

**Pull request merged**
