### PR TITLE
Add SOS2 constraint for both static and dynamic sized vector

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6587)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-:-KpIGLOhAAY9pKeYsRju:biagjkq)*

**Comment by hongkai-dai** [comment]
-@gizatt +@soonho-tri for both reviews.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-:-KpIsUw_K8PjKMWoGgcE:b-bud0x)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJpXrFPujJ_fOPem-_:-KpJpXrFPujJ_fOPem-a:b-mr6bo9) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L22)):*
> ```objc
>  * <pre>
>  *   λ(0) + ... + λ(n) = 1
>  *   λ(i) ≥ 0 ∀i
> ```

BTW, let's change it to either
 - `λ(i) ≥ 0 for all i` or
 - `∀i. λ(i) ≥ 0`

---

*[drake/solvers/mixed_integer_optimization_util.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJsspqyhWicD1FO6Hv:-KpJsspqyhWicD1FO6Hw:b-ve3c75) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L27)):*
> ```objc
>  * @tparam NumLambda The length of the lambda vector. NumLambda = n + 1.
>  */
> template<int NumLambda>
> ```

BTW, META, need a space between `template` and `<`.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJt9ILPBN_wdL1lGYO:-KpJt9ILPBN_wdL1lGYP:b-z7tibi) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L29)):*
> ```objc
> template<int NumLambda>
> struct LogarithmicSOS2NewBinaryVariables {
>   typedef VectorDecisionVariable<CeilLog2(NumLambda - 1)> type;
> ```

BTW, I think it's better to define `Rows` and use it:
```c++
  static constexpr int Rows = CeilLog2(NumLambda - 1);
  typedef VectorDecisionVariable<Rows> type;
```

---

*[drake/solvers/mixed_integer_optimization_util.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJyciJiXAjfwGP7KMK:-KpJyciJiXAjfwGP7KML:by7mk96) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L40)):*
> ```objc
> 
> /**
>  * Adds the special ordered set 2 (sos2) constraint,
> ```

BTW, META, I think we need to use 
 - `SOS` (all upper-case) in documentations,
 - `Sos` (Capitalized) in code according to the our naming-scheme.
What do you think? It can be changed by another PR though. 

---

*[drake/solvers/mixed_integer_optimization_util.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJx33_oVdsU9BVTyDt:-KpJx33_oVdsU9BVTyDu:b-bgr283) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L72)):*
> ```objc
>         Derived::RowsAtCompileTime>::type>::type
> AddLogarithmicSOS2Constraint(MathematicalProgram* prog, const Derived& lambda,
>                              const std::string& binary_variable_name = "y") {
> ```

I think we need to specify that `lambda` is a vector by providing either a `static_assert` or an additional constraint in SFINAE:

```c++
  static_assert(Derived::ColsAtCompileTime == 1 ||
                    Derived::ColsAtCompileTime == Eigen::Dynamic,
                "lambda should be a vector.");
// + runtime assertion on the size of cols?
```

---

*[drake/solvers/mixed_integer_optimization_util.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJxhWAsEws8YIAECXZ:-KpJxhWAsEws8YIAECX_:b-9xzmez) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L73)):*
> ```objc
> AddLogarithmicSOS2Constraint(MathematicalProgram* prog, const Derived& lambda,
>                              const std::string& binary_variable_name = "y") {
>   int binary_variable_size = CeilLog2(lambda.rows() - 1);
> ```

BTW, nit:
```c++
const int binary_variable_size =...
const auto y = ...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6587)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJpXrFPujJ_fOPem-_:-KpLWQBdIVMoWQC-VNfH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, let's change it to either
 - `λ(i) ≥ 0 for all i` or
 - `∀i. λ(i) ≥ 0`

</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJsspqyhWicD1FO6Hv:-KpLWUxLHMfx6NWCc_ZA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L27)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, META, need a space between `template` and `<`.
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJt9ILPBN_wdL1lGYO:-KpLW_qvICi_HBJnc6dx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L29)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's better to define `Rows` and use it:
```c++
  static constexpr int Rows = CeilLog2(NumLambda - 1);
  typedef VectorDecisionVariable<Rows> type;
```
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJyciJiXAjfwGP7KMK:-KpLXQ429-ok220Jvk2q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L40)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, META, I think we need to use 
 - `SOS` (all upper-case) in documentations,
 - `Sos` (Capitalized) in code according to the our naming-scheme.
What do you think? It can be changed by another PR though. 
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJx33_oVdsU9BVTyDt:-KpLX_R5AGqLTx_wurDc:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L72)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think we need to specify that `lambda` is a vector by providing either a `static_assert` or an additional constraint in SFINAE:

```c++
  static_assert(Derived::ColsAtCompileTime == 1 ||
                    Derived::ColsAtCompileTime == Eigen::Dynamic,
                "lambda should be a vector.");
// + runtime assertion on the size of cols?
```
</blockquote></details>

Done. Good call.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-KpJxhWAsEws8YIAECXZ:-KpLXdziuFvGfU2N1845:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f8043aad6b78e0ce9fb3734dc850a367771973/drake/solvers/mixed_integer_optimization_util.h#L73)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit:
```c++
const int binary_variable_size =...
const auto y = ...
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6587)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-:-KpLYaDSZOYsRmme4fUI:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6587#-:-KpLyRBkqx5KhLZWu-si:b-l70wzf)*

**Pull request merged**
