### PR TITLE
SAP holonomic constraints with non-zero bias

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards landing implicit PD control in #17674.

cc'ing @RussTedrake

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18996)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-:-NQVmM0l7QDS9-rYPHOG:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
First pass done, PTAL.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-:-NQefop9BR9PEEzO3yVS:b-v6sck1)* status: 5 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQeXHMIBnLybTqLUdNa:-NQeXHMIBnLybTqLUdNb:b-tmkhzr) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L51)):*
> ```objc
>    by CalcBiasTerm(). SAP approximates the constraint fuction as:
>      g(v) ≈ g₀ + δt⋅ġ(v) = g₀ + δt⋅(J⋅v + b)
>    With this approximation the unprojected impulses y(v) = −δt⋅k⋅(g+τ⋅ġ) can
> ```

nit: spacing



_Suggestion:_
```objc
(g + τ⋅ġ)
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 57 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQeXOa38Ify9UTHmfKi:-NQeXOa38Ify9UTHmfKj:b4yt7x3) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L57)):*
> ```objc
>      R⁻¹ = δt⋅(δt + τ)⋅k
>    and the velocity bias v̂ as:
>      v̂ = −g₀/(δt+τ)−b
> ```

nit: spacing 



_Suggestion:_
```objc
(δt + τ)
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 153 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQeXXCH7amlyW294di4:-NQeXXCH7amlyW294di5:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L153)):*
> ```objc
>    @param[in] g The value of the constraint function.
>    @param[in] J The Jacobian w.r.t. to the clique's generalized velocities.
>    @param[in] J The bias term, such that ġ = J⋅v + b.
> ```

nit: typo



_Suggestion:_
```objc
   @param[in] b The bias term, such that ġ = J⋅v + b.
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQefeGvDMeufS5fxjwl:-NQefeGvDMeufS5fxjwm:b-8qf5ti) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L50)):*
> ```cpp
> 
> template <typename T>
> SapHolonomicConstraint<T>::SapHolonomicConstraint(int first_clique,
> ```

nit: Will we eventually have the need for a two-clique version with non-zero bias?
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQeZxScAU6NltgVsJql:-NQeZxSd4MKL5HjV7AK5:bp9e964) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L66)):*
> ```cpp
> }
> 
> template <typename T>
> ```

I think as a general good c++ rule, the version of the constructor with the most number of arguments shoud be fully specified, and the other version should delegate, i.e.:

```
template <typename T>
SapHolonomicConstraint<T>::SapHolonomicConstraint(int clique, VectorX<T> g,
                                                  MatrixX<T> J, VectorX<T> b,
                                                  Parameters parameters)
    : SapConstraint<T>(clique, std::move(g), std::move(J)),
      parameters_(std::move(parameters)), bias_(std::move(b))  {
  // N.B. SapConstraint's constructor already checked the sizes of g its
  // Jacobian.
  DRAKE_DEMAND(this->constraint_function().size() ==
               parameters_.num_constraint_equations());
}

template <typename T>
SapHolonomicConstraint<T>::SapHolonomicConstraint(int clique, VectorX<T> g,
                                                  MatrixX<T> J,
                                                  Parameters parameters)
    : SapHolonomicConstraint(clique, std::move(g), std::move(J), 
                             std::move(VectorX<T>::Zero(parameters.num_constraint_equations())),
                             std::move(parameters)) {}

```

This also saves you from allocating a zero bias vector and then immediately throwing it away and replacing it with the actual specified bias.

Although this does change the constructor's signature, I do not think that it meets the need for a deprecation because the public facing API does not change nor the pre/post conditions. Platform reviewer might have more insight on that though.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: feature. +@ggould-tri for platform review, please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-:-NR4TXmo51IEXGe3bDkE:bhyr7y0)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQefeGvDMeufS5fxjwl:-NR4S1yM8DkyKHqGzg98:bb7ohn6) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I haven't needed it thus far and therefore I don't think we should push it if it won't get used. Easy to add if we happen to need it.
</blockquote></details>

sgtm
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQeZxScAU6NltgVsJql:-NR4Sua14KabdKq8sRYx:b-7s11so) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L66)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Nice suggestion. Done.
However I couldn't write the second ctor (without bias) in terms of the first one (with bias). The reason is that the compiler strangely moves `parameters` even before we can use it. 
What I did accomplishes what you want though, i.e. throwing away an extra zero vector.

</blockquote></details>

Interesting. I was worried about that before making my original comment and wrote a little test program where I used a function on a moved argument in a delegated constructor and it worked. But there's likely something more complicated happening here.

Regardless, your change looks clean and eliminates the extra vector alloc. Thanks.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; one very optional formatting readability suggestion.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-:-NR4VExRDAwE_ECCIgWr:b4raw7)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 110 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NR4UPVPAXtqO4SYLv12:-NR4UPVPAXtqO4SYLv13:b-zhf3s) ([raw file](https://github.com/RobotLocomotion/drake/blob/02192e94d7cd7c38681f845347068b07567a88a8/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L110)):*
> ```cpp
>   return -VectorX<T>(this->constraint_function().array() /
>                      (time_step + tau.array())) -
>          bias_;
> ```

nit, author's discretion:  This indentation is hard to read.  It would be a bit clearer re-grouped or with the operator moved to the front to make clear what the role of `bias_` is, if the linter will permit it.  One possible suggestion:



_Suggestion:_
```cpp
  return -(VectorX<T>(this->constraint_function().array() /
                      (time_step + tau.array()))
           + bias_);
```

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18996)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 66 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18996#-NQeZxScAU6NltgVsJql:-NR4X_2fC00E6CGxnigN:b-obrr) ([raw file](https://github.com/RobotLocomotion/drake/blob/a68223036e3a45d3291ea6b63b552f4813b3dc19/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L66)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Interesting. I was worried about that before making my original comment and wrote a little test program where I used a function on a moved argument in a delegated constructor and it worked. But there's likely something more complicated happening here.

Regardless, your change looks clean and eliminates the extra vector alloc. Thanks.
</blockquote></details>

BTW in a multi-argument function call there is no guarantee about the order in which the arguments are evaluated (they are each logically independent). So likely the `std::move(parameters)` expression for the last argument got evaluated before the reference to `parameters` in the second-to-last.

**Pull request merged**
