### PR TITLE
adds iiwa7 models.

### PR DESCRIPTION
**Pull request by RussTedrake**
derived from the same source as the rest of this directory and curated by @pangtao22 and @tlpmit. 
i've reviewed the existing license files and believe they are correct for this model as well.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9789)

### CODE REVIEW

**Comment by RussTedrake** [comment]
fwiw -- this is the box collision model that @tlpmit generated.
image

**Comment by jwnimmer-tri** [comment]
I think it would be fine to use the sibling name for iiwa7, while leaving the existing files unchanged.

**Comment by jwnimmer-tri** [comment]
In any case, if you choose to keep it this way, please fix LICENSE.TXT to mention both the 7 and 14.

**Comment by RussTedrake** [comment]
The origin has both underneath iiwa_description: https://github.com/IFL-CAMP/iiwa_stack/tree/master/iiwa_description <https://github.com/IFL-CAMP/iiwa_stack/tree/master/iiwa_description> 
and the license refers to that iiwa_description directory.

will fix the LICENSE.txt

**Comment by RussTedrake** [comment]
pushed the license to match the wording in https://github.com/IFL-CAMP/iiwa_stack/blob/master/iiwa_description/package.xml

**Comment by jwnimmer-tri** [comment]
> The directory structure seems funky to me now (iiwa14 vs. iiwa7) but I realize that fixing this would require updating lots of paths. Perhaps a TODO?

@rcory Your posture in this review should be that wherever these new files land, is where they are going to stay for the foreseeable future.  If you want them in a better layout, place the _new_ files in the right layout now, and then TODO moving the old files.  It's silly to add these files with paths you don't like now, and them immediately have to relocate them with lots of deprecation noise afterwards.  However, if you're satisfied with this PR's layout for the e.g. next year or two, then it's okay to merge.

**Comment by jwnimmer-tri** [comment]
That makes sense.

**Comment by jwnimmer-tri** [comment]
I'm adding a "Do Not Merge" tag so that Russ has a chance to review Rick's feedback.  Otherwise, the big green button is staring everyone in the face.  Russ, you can remove the tag once you've caught up with the posts.

**Comment by RussTedrake** [comment]
@SeanCurtis-TRI -- the 20 minute version would add a ton of value, and it's certainly sufficient to me for now.  Would really appreciate it.

**Comment by RussTedrake** [comment]
@tlpmit , @Sproulx -- do you have any info / suspicions / ability to diagnose the offset errors that rick pointed out above?

**Comment by Sproulx** [comment]
@RussTedrake I'm looking into the alignment issue that @rcory pointed out. Looks like there are small offset issues between all the links, but the ones in the images Rick provided are the most glaring. I'll use the CAD model to help figure out the proper alignment.

**Pull request merged**
