### PR TITLE
Add latching for iiwa_cmd_recv

### LINKED ISSUE #13465: Design of input (not parameter) for no-op IIWA command
From #13340:

@siyuanfeng-tri writes:
> sorry i didn't catch this earlier.
> i just realized that setting desired q to measured q is probably not the best thing to do before receiving a real command... since that effectively wipes out the position feed back loop. this would be more weird when we compute the desired velocity based on numeric difference between commanded q, and would be extra weird if we specified a integral gain in the pid loop downstream. we are currently doing all of these in the standard iiwa pipeline..

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Closes #13465.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13496)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This is good but I think not quite right.  Prior to the latch event occurring, the position_estimated input should feed through to the output.  If someone evaluates the output port before beginning a simulation, it should be the current position, not zero.  The calls to `UpdateFallbackValue` newly added to the unit test indicate that existing user code would break unless we adjust this PR.

Here's the system model that I think makes sense:
```
CacheEntry groomed_position_measured =
  position_measured iff connected, else the deprecated parameter

CacheEntry position_prior_to_first_message = 
  latched_position_measured iff set, else groomed_position_measured

State latched_position_measured is optional<position>
  iff unset, the update event is to copy groomed_position_measured into state

CacheEntry groomed_input =
  lcmt_iiwa_command iff non-default message, else position_prior_to_first_message
```

**Comment by siyuanfeng-tri** [comment]
> If someone evaluates the output port before beginning a simulation, it should be the current position, not zero.

Yeah, this is the part that I hate the most. From my point of view, before the latching happens, everything is in the twilight zone, it's like accessing memory without initialization. So really nobody should access the output port outside Simulator (or something that handles event correctly.)
Setting the output to input probably won't hurt more than setting it to zero (or NaN), but it hides some of this transient behavior. The new setup is very tied into Simulator's behavior, which I don't know if it's good or bad.

**Comment by jwnimmer-tri** [comment]
> The new setup is very tied into Simulator's behavior, which I don't know if it's good or bad.

If it helps, we could make public the method that copies input to latched state (taking Context as an argument)[1], so that a user could call it explicitly and thus avoid the now-event, use this without a simulator, etc.

[1] i.e. the "the update event is to copy groomed_position_measured into state" handler.

**Comment by jwnimmer-tri** [comment]
FYI I'm working on some changes to implement my notes above.

**Comment by jwnimmer-tri** [comment]
Superseded by #13540.

**Pull request closed without merging**
