### PR TITLE
tutorials: Add brief tutorial for optimization using MultibodyPlant

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Focused on custom evaluators.

This is super terse, but is catered to answer @mposa's Slack question:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1575412174070900

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12433)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Preview:
https://nbviewer.jupyter.org/github/EricCousineau-TRI/drake/blob/feature-py-mbp-constraint/tutorials/mathematical_program_multibody_plant.ipynb

**Comment by edrumwri** [comment]
I just took a look at this because I was curious (linking MultibodyPlant with MathematicalProgram = cool!)

After talking with Sean and Hongkai, I thought I'd give my feedback. At a high level, I lacked context to understand the powers that combining MBP and MP would give. I hoped that the tutorial would show me and it didn't.

At a lower level: the tutorial accomplished the first task that it promised (an example of "Creating a MultibodyPlant containing an IIWA arm") perfectly. But the second part of the tutorial, starting with "Custom evaluator for height of link 7's origin", does not connect so well to the second task (an example of "Adding a custom (but trivial) constraint to a MathematicalProgram which uses MultibodyPlant.")

**Comment by EricCousineau-TRI** [comment]
Hm... I'd expect that this tutorial (being as terse as it is) wouldn't shed that much light on the richness of MBP + MP (hence the TODO to add in stuff using `inverse_kinematics`).

However, I would've expected that at least the low-level part (How do I add a custom constraint / cost using a `MultibodyPlant`?) would have been addressed.
Can I ask how this it wasn't? Is it just a wordsmithing thing, or is the application too esoteric / useless for the tutorial? (Which I totally acknowledge, but I myself won't have time to polish any time soon.)

**Comment by edrumwri** [comment]
Re: "how this wasn't": I think the application wasn't clearly explained
(what does " height of link 7's origin" have to do with a constraint on a
mathematical program?)  I think the problem is that this tutorial exists is
an island, along with a few other tutorial islands, in the complex sea of
Drake.

**Comment by EricCousineau-TRI** [comment]
Yeah, I won't be able to solve the "this tutorial is an island" any time soon, but duly noted.

However, I would love to solve the part of the constraint being hard to connect. "height of link 7's origin" was actually carryover from a prior revision, so I'll fix that.

Are there other wording changes you'd like to see that would have made it more clear?

**Comment by edrumwri** [comment]
I think if you explain why you're going through the process in the second
part of the tutorial (a high level description of what you're using
mathematical program for in this case and how the constraint allows you
realize that), it would be much more understandable.

**Comment by EricCousineau-TRI** [comment]
Tried to make it slightly more connected in the follow-up PR: #12443.

**Pull request merged**
