### PR TITLE
output max dist in 16 bit depth channel when overflowing

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10214)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-nightly-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-nightly-undefined-behavior-sanitizer please

**Comment by siyuanfeng-tri** [comment]
@SeanCurtis-TRI you know how to kick off the 2 sanitizer builds? i failed apparently..

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please

**Comment by jamiesnape** [comment]
And we have found a bug our Jenkins configuration.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please

**Comment by kunimatsu-tri** [comment]
___
*[systems/sensors/dev/rgbd_camera.cc, line 146 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10214#-LTdRdl_4FrPgU7w7Jug:-LTd_pHp3CAdhEjxnSOe:bveeuak) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b94cc0e98ea09a78cec22bd2a771eaaa8546bd/systems/sensors/dev/rgbd_camera.cc#L146)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This isn't "max valid depth" it's the "infinity/overflow" value (i.e., one greater than the max valid depth.)

For my money, I'd rather see one of these values defined as a `static constexpr` and the other expressed in terms of that one. But I won't defect it.
</blockquote></details>

BTW, oops, that's true. Good catch. I'll withdraw this comment then.

**Pull request merged**
