### PR TITLE
add some documentation to iiwa status lcm type

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9568)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by manuelli** [comment]
My understanding is that `joint_torque_commanded` is literally just an echo of `joint_torque` field of `lcmt_iiwa_command.lcm` message. See [here](https://github.com/RobotLocomotion/drake/blob/master/lcmtypes/lcmt_iiwa_command.lcm#L17).

Usually when we are running the robots we are in joint impedance mode, this means that we send joint positions, and the kuka controller closes a joint impedance loop. When RLG commands the robot we send `joint_torque = 0` in our iiwa_command message. I'm going to go scope this on our robot now.

**Comment by manuelli** [comment]
@siyuanfeng-tri I agree with that. The Franka documentation could actually be helpful here. AFAIK it's basically the same as the kuka (internally) but it is much better documented. 

https://frankaemika.github.io/docs/libfranka.html#under-the-hood

**Comment by YeZhao** [comment]
:lgtm:

**Pull request merged**
