### PR TITLE
[geometry] Move deformable contact data out of dev

### LINKED ISSUE #17234: [geometry] New proximity query result: DeformableContactData
Add new proximity query results “DeformableContactData” that contains information on deformable-rigid contact.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Resolve #17234 
Part of #16875

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252)

### CODE REVIEW

**Comment by DamrongGuoy** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2slqWV0ZYVj1lK9Epq:-N2slqWV0ZYVj1lK9Epr:b-9wdqlx) (no related file):*
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-release please

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252#-:-N2w00fn4gVhoZQIkA9v:ba0k9zt)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by xuchenhan-tri — COMMENTED** [review]
checkpoint

> Reviewed 12 of 16 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252#-:-N2wIMjoEhvqo-mh-tpj:b-vv2shf)* status: 6 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[`geometry/proximity/BUILD.bazel` line 150 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wIBHZAo3kgSua-lEA:-N2wIBHZAo3kgSua-lEB:b-tas98g) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/BUILD.bazel#L150)):*
> ```Starlark
> 
> drake_cc_library(
>     name = "deformable_contact",
> ```

nit what's the reason that the library name is different from the sole header?
___
*[`geometry/proximity/BUILD.bazel` line 156 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wIHIw0ZC6sPYE0Bg_:-N2wIHIw0ZC6sPYE0Bga:b4fjpxj) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/BUILD.bazel#L156)):*
> ```Starlark
>     ],
>     deps = [
>         ":bvh",
> ```

nit unused dependencies.
___
*[`geometry/proximity/test/deformable_rigid_contact_pair_test.cc` line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wG9Ye1Vv9PKR3aO8h:-N2wG9Ye1Vv9PKR3aO8i:b-hv7hnp) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/test/deformable_rigid_contact_pair_test.cc#L28)):*
> ```cpp
> 
>   const math::RotationMatrix<double> expect_R_CW =
>       math::RotationMatrix<double>::MakeFromOneUnitVector(nhat_W, 2)
> ```

BTW no defect, but personally I'm not a huge fan of these tests that closely resembles the implementation. As an alternative, we could test that the rotation matrix produced here does what it promised to do -- map the world space normal to the contact space normal, (0, 0, 1).
___
*[`geometry/proximity/deformable_contact_surface.h` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wFYWNBqnhdLm_0gip:-N2wFYWNBqnhdLm_0giq:b-l1a08l) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L15)):*
> ```objc
> 
> namespace drake {
> namespace geometry {
> ```

nit can this be internal?
___
*[`geometry/proximity/deformable_rigid_contact_pair.h` line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wFb8G49ZAeQDDH5AA:-N2wFb8G49ZAeQDDH5AB:b-l1a08l) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_rigid_contact_pair.h#L10)):*
> ```objc
> 
> namespace drake {
> namespace geometry {
> ```

nit can this be internal?
___
*[`geometry/query_results/deformable_contact_data.h` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wGk0xElJdZ2HGWS3C:-N2wGk0xElJdZ2HGWS3D:b12pki4) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.h#L9)):*
> ```objc
> 
> // TODO(DamrongGuoy) Remove this when we clean up the namespace.
> using ReferenceDeformableGeometry =
> ```

nit, this doesn't need to be visible in the global namespace. Move it 4 lines lower.

Also, it seems like we can remove this dependency if just pass in the reference mesh and the signed distance field instead.

**Review by xuchenhan-tri — COMMENTED** [review]
Nice tests, thanks! :lgtm: 

+@sherm1 for platform review per rotation please. The files coming out of dev need a full review.

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252#-:-N2wOGuZAob6-2ckuPP8:b4shfyy)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @DamrongGuoy, @sherm1, and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 11 of 16 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252)* status: 18 unresolved discussions (waiting on @DamrongGuoy and @drake-jenkins-bot)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2slqWV0ZYVj1lK9Epq:-N2xcSoq31suClUg21in:bpbdnmw) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Platform checkpoint.
</blockquote></details>

Platform :lgtm: pending some minor updates

___
___
*[`geometry/query_results/test/deformable_contact_data_test.cc` line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xaHaR60sdbRdDTx3k:-N2xaHaS0edqgPwA_aPB:b-55vm8o) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/test/deformable_contact_data_test.cc#L86)):*
> ```cpp
>   //
>   const std::vector<int> kExpectedPermutedVertexIndexes{0, 4, 1, 2, 5, 3};
>   const std::vector<int> kExpectedPermutedToOriginalIndexes {0, 2, 3, 5, 1, 4};
> ```

BTW looks like I'm misunderstanding the `sort` in the code since neither of these permutations is sorted. Can you clarify what the sort is doing and why that has no effect here?
___
*[`geometry/query_results/test/deformable_contact_data_test.cc` line 188 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xbsEECoGd7FWseNd1:-N2xbsEECoGd7FWseNd2:bgyw25m) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/test/deformable_contact_data_test.cc#L188)):*
> ```cpp
>   EXPECT_EQ(dut.permuted_to_original_indexes(), expect_identity_permutation);
> }
> ```

minor: not seeing unit test for num_vertices_in_contact() and deformable_body_index()
___
*[`geometry/proximity/deformable_contact_surface.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xVFMI9vgKy6ICypCj:-N2xVFMI9vgKy6ICypCk:bklwfw3) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L22)):*
> ```objc
> //  be the case. But for now, we'll assume a homogenous scalar environment.
> 
> // TODO(xuchenhan-tri) Consider either beefing this struct upon or creating some
> ```

typo: upon -> up
___
*[`geometry/proximity/deformable_contact_surface.h` line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xVW_nBFUqQYP7TU9W:-N2xVW_nBFUqQYP7TU9X:bahbykb) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L27)):*
> ```objc
> /** The per-polygon data associated with each contact polygon in the
>  DeformableContactSurface between a deformable tetrahedral mesh and a rigid
>  triangle mesh.*/
> ```

BTW would this be sufficient for deformable/deformable contact also? If inherently limited to D/R contact consider including that in the struct name. (Not as important if you make this internal)
___
*[`geometry/proximity/deformable_contact_surface.h` line 57 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xWcmpA_M9JU0ET4DK:-N2xWcmpA_M9JU0ET4DL:b7tbleu) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L57)):*
> ```objc
> 
>   /** Constructs the contact surface from the given per-polygon data. The
>    corresponding implicit polygon mesh is indexed from 0 to
> ```

minor: I don't understand what "_implicit_ polygon mesh" means. Can you clarify in the comment?
___
*[`geometry/proximity/deformable_contact_surface.h` line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xX8zD3BloYSA8E-1w:-N2xX8zEC84iR4VYYX6K:bskbe9x) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L70)):*
> ```objc
> 
>   /** Returns the data associated with the polygon indexed by `poly_index`. */
>   const ContactPolygonData<T>& polygon_data(int poly_index) const {
> ```

BTW consider `@pre poly_index is in range`
___
*[`geometry/proximity/deformable_rigid_contact_pair.h` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xXd0a1RtJBKqg9ErH:-N2xXd0b3mcyH_9vjZks:b-2s1ik9) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_rigid_contact_pair.h#L16)):*
> ```objc
>  properties of the contacts. */
> template <typename T>
> struct DeformableRigidContactPair {
> ```

minor: this seems like too much infrastructure for a struct. Consider upgrading to a class. Here is the [styleguide discussion](https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Classes). The main consideration is whether you would be happy to allow anyone to write on one data member of the struct without making any corresponding changes to other data members. To me it looks like there are invariants among the data members here, such as that the R_CWs must represent the normals in contact_surface. A class would allow the invariants to be enforced.
___
*[`geometry/proximity/deformable_rigid_contact_pair.h` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xZ-9GD-PS6GPy9wZG:-N2xZ-9GD-PS6GPy9wZH:bws3yys) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_rigid_contact_pair.h#L39)):*
> ```objc
>   /* Returns the number of contact points between the rigid and deformable body.
>    */
>   int num_contact_points() const { return contact_surface.num_polygons(); }
> ```

BTW I see an assumption that there is just one contact point per polygon. Is that necessary and is it documented somewhere?

**Review by DamrongGuoy — COMMENTED** [review]
Thank you @xuchenhan-tri and @sherm1 for finishing the reviews quickly.

I decided that having all of DeformableContactSurface, DeformableRigidContactPair, and DeformableContactData in `internal` would be easiest for now.  This way we do not lock ourselves with the public API and documentation yet.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252#-:-N2xzD2z-jEmOtE9o9Ny:b-bpdlns)* status: 3 unresolved discussions (waiting on @DamrongGuoy, @sherm1, and @xuchenhan-tri)

___
*[`geometry/proximity/BUILD.bazel` line 150 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wIBHZAo3kgSua-lEA:-N2xXjo10sqLeIxYjh0L:bl63ic1) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/BUILD.bazel#L150)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit what's the reason that the library name is different from the sole header?
</blockquote></details>

I rename to `deformable_contact_surface` now.  It sounds better to me too.

Originally I inherited the old name from the dev.
___
*[`geometry/proximity/BUILD.bazel` line 156 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wIHIw0ZC6sPYE0Bg_:-N2xlRB54f4kcWdHOmPQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/BUILD.bazel#L156)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unused dependencies.
</blockquote></details>

Done.
___
*[`geometry/proximity/test/deformable_rigid_contact_pair_test.cc` line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wG9Ye1Vv9PKR3aO8h:-N30KdY11LK8G8zHrBzN:b-eo0x9g) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/test/deformable_rigid_contact_pair_test.cc#L28)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW no defect, but personally I'm not a huge fan of these tests that closely resembles the implementation. As an alternative, we could test that the rotation matrix produced here does what it promised to do -- map the world space normal to the contact space normal, (0, 0, 1).
</blockquote></details>

Done.  Now I test that the rotation matrix can map the contact normal in World to the basis vector Cz of the contact frame C.

As a side effect, we pay a small numerical tolerance. 
___
*[`geometry/query_results/test/deformable_contact_data_test.cc` line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xaHaR60sdbRdDTx3k:-N3M5gFa9qnlnQm79a6V:bh8w344) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/test/deformable_contact_data_test.cc#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW looks like I'm misunderstanding the `sort` in the code since neither of these permutations is sorted. Can you clarify what the sort is doing and why that has no effect here?
</blockquote></details>

Done. I added documentation for permuted_to_original_indexes() in deformable_contact_data.h.  Here I also added explanation and expanded the table to clarify.
___
*[`geometry/query_results/test/deformable_contact_data_test.cc` line 188 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xbsEECoGd7FWseNd1:-N3M9ADxBEPPkbQOwGDV:b-35czay) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/test/deformable_contact_data_test.cc#L188)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: not seeing unit test for num_vertices_in_contact() and deformable_body_index()
</blockquote></details>

Done.  Added their tests in the first unit test `(DeformableContactDataTest, TestConstructorPermutedVertex)`.
___
*[`geometry/proximity/deformable_contact_surface.h` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wFYWNBqnhdLm_0gip:-N2y-IHm4zsr9s7aywWp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit can this be internal?
</blockquote></details>

Done.
___
*[`geometry/proximity/deformable_contact_surface.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xVFMI9vgKy6ICypCj:-N2y-c8E4P4n9aMyAvoT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: upon -> up
</blockquote></details>

Done.
___
*[`geometry/proximity/deformable_contact_surface.h` line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xVW_nBFUqQYP7TU9W:-N2y0DaS28S0mgbissku:b-d4hn9p) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would this be sufficient for deformable/deformable contact also? If inherently limited to D/R contact consider including that in the struct name. (Not as important if you make this internal)
</blockquote></details>

I made it internal, so we can change it later.

My guess is that, for deformable/deformable, `b_centroid` and `tet_index` will become `b_centroid[2]` and `tet_index[2]` for two tetrahedral meshes instead of one tetrahedral mesh.
___
*[`geometry/proximity/deformable_contact_surface.h` line 57 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xWcmpA_M9JU0ET4DK:-N2y3nuA9WUU8B_j9yim:b-k0qqa4) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I don't understand what "_implicit_ polygon mesh" means. Can you clarify in the comment?
</blockquote></details>

Done. I added the explanation.
___
*[`geometry/proximity/deformable_contact_surface.h` line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xX8zD3BloYSA8E-1w:-N2y4Rv3A4ycZTRSpTQs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_contact_surface.h#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `@pre poly_index is in range`
</blockquote></details>

Done.
___
*[`geometry/proximity/deformable_contact_surface.h` line 66 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N3MGWhy6yPNM9nuoB1T:-N3MGWhy6yPNM9nuoB1U:b2kba7g) ([raw file](https://github.com/robotlocomotion/drake/blob/71a6534bfb4c14a497d74a84d4ab8d8e523a3b8e/geometry/proximity/deformable_contact_surface.h#L66)):*
> ```objc
> 
>   /* Returns the data associated with the polygon indexed by `poly_index`.
>    @pre poly_index is in [0, range. */
> ```

I need to fix typo. Set to working.
___
*[`geometry/proximity/deformable_rigid_contact_pair.h` line 10 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wFb8G49ZAeQDDH5AA:-N2y4UWk0YByWVg_QcB3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_rigid_contact_pair.h#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit can this be internal?
</blockquote></details>

Done.
___
*[`geometry/proximity/deformable_rigid_contact_pair.h` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xXd0a1RtJBKqg9ErH:-N3MAcKV8vTm1gtM8BN2:b-ibds) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_rigid_contact_pair.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this seems like too much infrastructure for a struct. Consider upgrading to a class. Here is the [styleguide discussion](https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Classes). The main consideration is whether you would be happy to allow anyone to write on one data member of the struct without making any corresponding changes to other data members. To me it looks like there are invariants among the data members here, such as that the R_CWs must represent the normals in contact_surface. A class would allow the invariants to be enforced.
</blockquote></details>

Done.  I added a TODO.  I'll try to do it in the next PR.
___
*[`geometry/proximity/deformable_rigid_contact_pair.h` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xZ-9GD-PS6GPy9wZG:-N30SZcz-X3yJ5vzHOY6:b-l0ce1y) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/proximity/deformable_rigid_contact_pair.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I see an assumption that there is just one contact point per polygon. Is that necessary and is it documented somewhere?
</blockquote></details>

Done. I add the documentation here.
___
*[`geometry/query_results/deformable_contact_data.h` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2wGk0xElJdZ2HGWS3C:-N30PT2c5HsA2G38oYgb:b-h1y9ya) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.h#L9)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this doesn't need to be visible in the global namespace. Move it 4 lines lower.

Also, it seems like we can remove this dependency if just pass in the reference mesh and the signed distance field instead.
</blockquote></details>

Done. I moved it into `internal` a few lines below.

I also added a TODO to pass mesh + signed distance instead.
___
*[`geometry/query_results/deformable_contact_data.h` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xO7q9AlQ8cECwv0OC:-N30P04nDQkl-3dwsn4m:b-j0u4f1) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.h#L15)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this is now a public class so the comments should be upgrade from `/*` to Doxygen `/**` and reformatted if needed to satisfy Doxygen.

Or was the intent to make this `internal::` ?
</blockquote></details>

Done.  It is `internal` now.  In the beginning, I wasn't sure about public or internal.  For now, I think internal is better.
___
*[`geometry/query_results/deformable_contact_data.h` line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xOkV55XWwQoF5fAOq:-N30i3JP85uDLNMB-Xn3:b-y09mdg) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.h#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this strictly for Deformable-Rigid contact or will it eventually extend to Deformable-Deformable contact? If it is intended only for D-R forever consider renaming it to reflect that, otherwise note that it is currently limited to D-R but will eventually cover all Deformable contact.
</blockquote></details>

Done.  I added the note.  @xuchenhan-tri, do I get the note correctly?
___
*[`geometry/query_results/deformable_contact_data.h` line 70 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xTcoM1tPgm87o6_Hc:-N3M2TGt8tpR2bFx6u-E:bhjc4r3) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.h#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: in this example, the inverse mapping is not sorted but from reading the code it appears that it would be (and the permuted mapping would be shuffled to match). Is that right? If so, consider modifying the example to match.

(Not sure I'm understanding this correctly)
</blockquote></details>

Done. Among vertices participating in contact, e.g. {1,2,5}, they are sorted. Among non-participating vertices, e.g., {0,3,4}, they are also sorted separetly.

I updated the documentation with the example.
___
*[`geometry/query_results/deformable_contact_data.cc` line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xSZ2-AAOp4k_pyzeo:-N30iwiM8uEWVQd2Maxq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.cc#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: return type not obvious here, spell it out
</blockquote></details>

Done.
___
*[`geometry/query_results/deformable_contact_data.cc` line 50 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xRq5z39Nn2DSxJ-hc:-N30knE4-9X6ZEajDpEb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider relocating this short case to the top and returning so that the long case above doesn't have to be indented.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`geometry/proximity/deformable_contact_surface.h` line 66 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N3MGWhy6yPNM9nuoB1T:-N3MHpGb-y12uHYWvE2Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71a6534bfb4c14a497d74a84d4ab8d8e523a3b8e/geometry/proximity/deformable_contact_surface.h#L66)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I need to fix typo. Set to working.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
The new documentation is very helpful -- thanks!

> Reviewed 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252#-:-N3MfXop0aiVc8dt4l1s:bb8mszu)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @DamrongGuoy)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

___
*[`geometry/proximity/BUILD.bazel` line 172 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N3Q0ilv3Ga-4XAPb2yq:-N3Q0ilv3Ga-4XAPb2yr:buib542) ([raw file](https://github.com/robotlocomotion/drake/blob/48c6d095b69431de9688ea55a6f52f0d623aa8c5/geometry/proximity/BUILD.bazel#L172)):*
> ```Starlark
>     ],
>     deps = [
>         ":bvh",
> ```

nit, a few unused dependencies here.
___
*[`geometry/query_results/deformable_contact_data.h` line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N2xOkV55XWwQoF5fAOq:-N3Pzurp02jSUqMZ9Ma8:brrw64p) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7c7069038bb7b4fbeb68acd74134b1c645e34/geometry/query_results/deformable_contact_data.h#L20)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  I added the note.  @xuchenhan-tri, do I get the note correctly?
</blockquote></details>

Yes, the plan is to use this data structure to hold all the contact information, DR and DD, for a single deformable geometry.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17252)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

___
*[`geometry/proximity/BUILD.bazel` line 172 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17252#-N3Q0ilv3Ga-4XAPb2yq:-N3Q7c3gEETcqJhx6Mb-:b-t34g2j) ([raw file](https://github.com/robotlocomotion/drake/blob/48c6d095b69431de9688ea55a6f52f0d623aa8c5/geometry/proximity/BUILD.bazel#L172)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thank you.  It looks like I confused myself when I switched between two computers and might have lost the change somehow.

Set to working.
</blockquote></details>

I suspected that. Happens to me often too.

**Pull request merged**
