### PR TITLE
Partial cleanup of pure Python documentation to match Google Style Guide

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9593)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by jwnimmer-tri** [comment]
For the record, we don't use GSG for Python (http://drake.mit.edu/code_style_guide.html#python-style), though that's not to say there is anything wrong with these changes, either.

**Comment by jamiesnape** [comment]
We don't? I guess I should rephrase that "Partial cleanup of pure Python documentation for Sphinx Napoleon compatibility which happens to match the Google Style Guide"...

**Comment by jwnimmer-tri** [comment]
Also, if this is the format our doc tooling expects, we should just adopt it by rule anyway.

**Comment by jamiesnape** [comment]
It is at present, though we could work it to instead support either the Sphinx py domain or NumPy, if people prefer. My understanding is that Google Style is somewhat more human readable. At the moment `mkdoc.py` generates something close to Google Style (it still needs a little work), though it is not too late to change.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Pull request merged**
