### PR TITLE
Pulled out RigidBodyLoop into its own files.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2887)

### CODE REVIEW

**Comment by liangfok** [comment]
I was motivated to do this because while I was implementing the `Model` abstraction, I found it silly to have to `#include RigidBodyTree.h` when all I wanted was the `RigidBodyLoop` class.

+@amcastro-tri for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-:-KNHZS4X_Qyo7Y6K3_Xb:-22851117)*

**Comment by david-german-tri** [comment]
:+1: for fewer `RigidBodyTree.h` inclusions.  This is important for build time.

:lgtm: preemptively for platform review. @liangfok, feel free to press the green button after there has been feature review to your satisfaction.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-:-KNHf9dBh9Ry6vUh8uLr:-1327952518)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2915/ and is thus ready for feature review. @amcastro-tri 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-:-KNI0S_DGDN8EzJx93CH:-949590635)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/plants/rigid_body_loop.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-KNIB7kBWydInUMOqucF:-KNIB7kBWydInUMOqucG:-861915887) ([raw file](https://github.com/robotlocomotion/drake/blob/c1363ed160562369c6b7405b3e08858dfd831d46/drake/systems/plants/rigid_body_loop.h#L13)):*
> ```objc
>   // Constructs a RigidBodyLoop between two frames. Is this the correct API?
>   // TODO(amcastro-tri): review the correctness of this API
>   RigidBodyLoop(std::shared_ptr<RigidBodyFrame> _frameA,
> ```

Should we move the (simple) implementation of this constructor to the cc? Also why not update the doc here while at it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2915/ and is thus ready for feature review @amcastro-tri .

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_loop.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-KNIB7kBWydInUMOqucF:-KNInt_Uwozuxx6_15C3:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c1363ed160562369c6b7405b3e08858dfd831d46/drake/systems/plants/rigid_body_loop.h#L13)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Should we move the (simple) implementation of this constructor to the cc? Also why not update the doc here while at it?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-:-KNInx4CuiOuvvR31wy1:-1746654094)*

**Comment by liangfok** [comment]
Oh wait. I just realized that the parameter names are illegal. Just a sec.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-:-KNJPyEY1eZNV_RCl6T1:926848621)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2887#-:-KNJQgng1N_ydObgm08y:1417088721)*

**Pull request merged**
