### PR TITLE
RgbdCamera: replace model instance id with body id

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Fixed a bug of inappropriate usage of model instance id

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5597)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@siyuanfeng-tri feature review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-:-KfsOHcNp_yuIBzVmHV7:ba5en07)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 467 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-Kfsdreq5BipAWurS3Bq:-Kfsdreq5BipAWurS3Br:b-cye10m) ([raw file](https://github.com/robotlocomotion/drake/blob/026e3a09f59dfe790c9fe81c138aaa549e7a2ee2/drake/systems/sensors/rgbd_camera.cc#L467)):*
> ```cpp
>       // system.
>       const int body_id = body->get_body_index();
>       const auto pose = X_CW * visual.getWorldTransform();
> ```

might as well change it to X_CV. 

---

*[drake/systems/sensors/rgbd_camera.cc, line 524 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-KfsPD9PXSH0aKMdlbfO:-KfsPD9PXSH0aKMdlbfP:b-datvuu) ([raw file](https://github.com/robotlocomotion/drake/blob/026e3a09f59dfe790c9fe81c138aaa549e7a2ee2/drake/systems/sensors/rgbd_camera.cc#L524)):*
> ```cpp
> 
>     const auto X_CVisual = X_CW * tree_.CalcBodyPoseInWorldFrame(
>         cache, *body.get()) * visual.getLocalTransform();
> ```

BTW, you can just do *body, 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-:-KfseEZ5YFzWUjZ5CuPN:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
+@sammy-tri platform review please

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 467 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-Kfsdreq5BipAWurS3Bq:-Kfsi3_Tpw1r6UYYG21A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/026e3a09f59dfe790c9fe81c138aaa549e7a2ee2/drake/systems/sensors/rgbd_camera.cc#L467)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

might as well change it to X_CV. 
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.cc, line 524 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-KfsPD9PXSH0aKMdlbfO:-Kfsi5555PNE4H63H1Y4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/026e3a09f59dfe790c9fe81c138aaa549e7a2ee2/drake/systems/sensors/rgbd_camera.cc#L524)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, you can just do *body, 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-:-Kfsi8PsoP5Nvp7-kLLy:bo1cn6e)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros-release please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-:-Kft8fORJZt38ni9yEHx:b-162f6z)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-:-Kft9IT78YjeWvXsiU6P:b-3f2dwx)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5597#-:-KfvSRGd4K_ODw61GohS:bsf2vkf)*

**Pull request merged**
