### PR TITLE
[pydrake] Add bindings for InvertAndCompose

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16573)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@ggould-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16573#-:-MvhS7Fx5Z8Uv9jJ6ckR:bgf7pv7)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16573#-:-MvslFep28XbqprW6X2N:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
