### PR TITLE
[install] Use file argument for actions, not template substitution

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #7331.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[CMakeLists.txt, line 446 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16252#-MrEKDG12u-dgNMogwhg:-MrEKDG12u-dgNMogwhh:b-vb7aaa) ([raw file](https://github.com/robotlocomotion/drake/blob/2b0e5c553f5211da15a2324a1059dff5b801711f/CMakeLists.txt#L446)):*
> ```CMake
> endif()
> 
> # N.B. If you are testing the CMake API and making changes to `install.py`,
> ```

s/install.py/installer.py/
___
*[tools/install/test/install_meta_test.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16252#-MrEKUBxA35-fCekErAq:-MrEKUBxA35-fCekErAr:b-vb7aaa) ([raw file](https://github.com/robotlocomotion/drake/blob/2b0e5c553f5211da15a2324a1059dff5b801711f/tools/install/test/install_meta_test.py#L1)):*
> ```Python
> """Tests the behavior of targets that use `install.py`."""
> ```

s/install.py/installer.py/
___
*[tools/install/installer.py, line 454 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16252#-MrEKW4k3PSD1H-ijt6G:-MrEKW4k3PSD1H-ijt6H:bjvbdnt) ([raw file](https://github.com/robotlocomotion/drake/blob/2b0e5c553f5211da15a2324a1059dff5b801711f/tools/install/installer.py#L454)):*
> ```Python
>     with open(args.actions, "r", encoding="utf-8") as f:
>         actions = f.read()
>     exec(actions)
> ```

I'd like to see some harm reduction here, like input validation (currently only 2 operations need be supported), or values of global or local dictionaries that would limit arbitrary execution.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; one nit.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252#-:-MrNgZKb4sXX87008eEo:b-4e1pp9)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[tools/install/install.bzl, line 499 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16252#-MrNfA5u4iOi3p24V-o4:-MrNfA5u4iOi3p24V-o5:b4ybz4z) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf135851d0155eda2a4b82f54eb99c008e05801/tools/install/install.bzl#L499)):*
> ```Starlark
>             "#!/bin/bash",
>             "tools/install/installer --actions {} \"$@\"".format(
>                 actions_file.short_path,
> ```

minor:  `shlex.quote(actions_file.short_path)` would be safer.
For extremely relative definitions of "safer".

If skylark doesn't have shlex then as a fallback quoting the `{}` would get most of the benefit.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[tools/install/install.bzl, line 499 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16252#-MrNfA5u4iOi3p24V-o4:-MrNhA9m-Vw37W5ho5Q6:b-5o929u) ([raw file](https://github.com/robotlocomotion/drake/blob/fbf135851d0155eda2a4b82f54eb99c008e05801/tools/install/install.bzl#L499)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  `shlex.quote(actions_file.short_path)` would be safer.
For extremely relative definitions of "safer".

If skylark doesn't have shlex then as a fallback quoting the `{}` would get most of the benefit.
</blockquote></details>

Done.

If someone puts a shell character into their bazel target name, I'll let them keep the pieces.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri this PR still needs your emoji, when you're ready.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16252#-:-MrO68Kx1gZi7vAIxrtK:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
