### PR TITLE
[geometry:drake_visualizer] Fix for disabling/enabling hydro contact plugin

### LINKED ISSUE #16841: DrakeVisualizer: Cannot Toggle Hydroelastic Contact Visualizer
When toggling off hydroelastic contact visualization in Drake Visualizer through the tools menu (`Tools->Hydroelastic Contact Visualizer`), there is no way to toggle it back on. That is, once the hydro visualization is toggled off, it remains off until Drake Visualizer is re-started again.

### PR DESCRIPTION
**Pull request by joemasterjohn**
Fixes #16841

Fixes a bug that was improperly clearing the data model for the hydroelastic plugin, resulting in disabling/re-enabling the plugin not showing hydro contact surfaces.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@damrongguoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852#-:-Mysf3tHE8_p9Yq_0LjP:b-4tfozp)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

I have tested it with examples.

+@xuchenhan-tri  for platform review, please.

+(priority: high) 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852#-:-Mysw8L997G6h1hvmny4:b-l00218)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @joemasterjohn and @xuchenhan-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 700 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-Mysu-Z-15JnpypfJHtr:-Mysu-Z-15JnpypfJHts:bnaqffa) ([raw file](https://github.com/robotlocomotion/drake/blob/e067437871d831463a3db7fe1e389e6c8584fc94/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L700)):*
> ```Python
>         om.removeFromObjectModel(self._folder)
>         self._folder = None
>         self._contacts = {}
> ```

I'm just curious. This line `self._contacts = {}` doesn't give the same effect as the `for` loop above?
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-MysqxJI4lvOXEtxVuZE:-MysqxJJ9zueAyl_Em8-:bpidmbw) ([raw file](https://github.com/robotlocomotion/drake/blob/90888140969b157eb3e013df2a17c9455ca2fc51/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1140)):*
> ```Python
>         lcmUtils.removeSubscriber(self._contact_sub)
>         self._contact_sub = None
>         om.removeFromObjectModel(om.findObjectByName(self._folder_name))
> ```

I'm just curious what's the meaning of this line?  I guess I don't know what `om` is.  Is this the most important line in this PR?

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with a couple of thoughts.
+(release notes: yes) 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852#-:-Myt2ELV-vSAAopV3wKb:b-c0ldaf)* status: 2 unresolved discussions (waiting on @joemasterjohn)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-Myt76-D7iFQ3C2ClO-3:-Myt76-D7iFQ3C2ClO-4:b-tmb9ap) ([raw file](https://github.com/robotlocomotion/drake/blob/90888140969b157eb3e013df2a17c9455ca2fc51/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1140)):*
> ```Python
>         lcmUtils.removeSubscriber(self._contact_sub)
>         self._contact_sub = None
>         om.removeFromObjectModel(om.findObjectByName(self._folder_name))
> ```

BTW, there is a subtle behavioral change resulting from this: when we toggle off the hydro option, the "Hydroelastic Contact" folder doesn't disappear along with it anymore.

I think the following would preserve the current behavior:
1. Leave the line `om.removeFromObjectModel(om.findObjectByName(self._folder_name))` in.
2. Delete the VisualModel when `remove_subscriber`
3. Reinitialize the VisualModel in `add_subscriber`.

OTOH, I'm fine with the current solution too.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-MytA7b_DBtzOoYbnSjH:-MytA7b_DBtzOoYbnSjI:b-c72f2j) ([raw file](https://github.com/robotlocomotion/drake/blob/e067437871d831463a3db7fe1e389e6c8584fc94/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
> ```Python
>             if self.visual_model is not None:
>                 self.visual_model.clear()
>                 self.message = None
> ```

BTW, probably nice to clear the message no matter what?

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852)* status: 2 unresolved discussions (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852)* status: 2 unresolved discussions (waiting on @DamrongGuoy)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 700 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-Mysu-Z-15JnpypfJHtr:-MyueON52jnhqCZxtpvQ:bt017d0) ([raw file](https://github.com/robotlocomotion/drake/blob/e067437871d831463a3db7fe1e389e6c8584fc94/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L700)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm just curious. This line `self._contacts = {}` doesn't give the same effect as the `for` loop above?
</blockquote></details>

The `_Contact` class itself has to do its own cleanup in the `clear()` method which must be explicitly called, or else data from the LCM messages will remain around in the director's object model.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-MysqxJI4lvOXEtxVuZE:-MyueywjAkcmmqEGcB3a:bzgzylx) ([raw file](https://github.com/robotlocomotion/drake/blob/90888140969b157eb3e013df2a17c9455ca2fc51/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1140)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm just curious what's the meaning of this line?  I guess I don't know what `om` is.  Is this the most important line in this PR?
</blockquote></details>

To the best of my knowledge, `om` is a data-model used by `director` to organize the scene's vtk data. But I don't know this code well enough to say for sure. 
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-Myt76-D7iFQ3C2ClO-3:-MyufRnA2KohYaTRu1fC:bln4fpi) ([raw file](https://github.com/robotlocomotion/drake/blob/90888140969b157eb3e013df2a17c9455ca2fc51/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, there is a subtle behavioral change resulting from this: when we toggle off the hydro option, the "Hydroelastic Contact" folder doesn't disappear along with it anymore.

I think the following would preserve the current behavior:
1. Leave the line `om.removeFromObjectModel(om.findObjectByName(self._folder_name))` in.
2. Delete the VisualModel when `remove_subscriber`
3. Reinitialize the VisualModel in `add_subscriber`.

OTOH, I'm fine with the current solution too.
</blockquote></details>

Thanks for the suggestion, I like that. The current changes makes the "Hydroelastic Contact" folder disappear and reappear on toggle.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-MytA7b_DBtzOoYbnSjH:-MyufddPAjhTE0T7YADw:b-f0bi48) ([raw file](https://github.com/robotlocomotion/drake/blob/e067437871d831463a3db7fe1e389e6c8584fc94/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, probably nice to clear the message no matter what?
</blockquote></details>

Actually, I think it would be nice to not clear the message. A lot of use cases stop or pause the sim and inspect the model in drake visualizer. If no new LCM messages are received then toggling the plugin off then on will cause the last message and corresponding visualizations to disappear. I've changed the behavior to reload the last received message when the plugin is toggled on, let me know what you think.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-MytA7b_DBtzOoYbnSjH:-MywVrow1eKl3hprbfQP:bomccxx) ([raw file](https://github.com/robotlocomotion/drake/blob/e067437871d831463a3db7fe1e389e6c8584fc94/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Actually, I think it would be nice to not clear the message. A lot of use cases stop or pause the sim and inspect the model in drake visualizer. If no new LCM messages are received then toggling the plugin off then on will cause the last message and corresponding visualizations to disappear. I've changed the behavior to reload the last received message when the plugin is toggled on, let me know what you think.
</blockquote></details>

I like the reload.  Indeed, I do pause-inspect-then-continue or pause-inspect-then-SingleStep a lot using `lcm-logplayer-gui`.  

It is very convenient to toggle on and off on the same published data/snapshot.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16852)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16852#-MytA7b_DBtzOoYbnSjH:-MywezS0EeqdcSVIF3ms:b-g6llew) ([raw file](https://github.com/robotlocomotion/drake/blob/e067437871d831463a3db7fe1e389e6c8584fc94/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1157)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I like the reload.  Indeed, I do pause-inspect-then-continue or pause-inspect-then-SingleStep a lot using `lcm-logplayer-gui`.  

It is very convenient to toggle on and off on the same published data/snapshot.
</blockquote></details>

Makes sense. Thanks!

**Pull request merged**
