### PR TITLE
Fix error in "is trapped" test

### LINKED ISSUE #971: Bug in rrt extend function
The distance check is done using the nearest neighbour parent instead of the nearest neighbour.
Line 230 in solvers/MotionPlanningTree.m should be changed to

if isempty(q_new) || obj.distanceMetric(q_new, q) > obj.distanceMetric(obj.getVertex(id_near), q)

### PR DESCRIPTION
**Pull request by avalenzu**
Resolves #971

### CODE REVIEW

**Comment by RussTedrake** [comment]
looks good.  will just wait for the servers.

**Comment by avalenzu** [comment]
I'm gonna go ahead and guess that this isn't related to this pull request ...

**Comment by avalenzu** [comment]
Hmm. It appears that this was caused by a merge conflict in the main CMakeLists.txt. I'll rebase this on master and reopen.

Big picture question: should we have the build servers error out if there are merge conflicts?

**Comment by avalenzu** [comment]
Wasn't able to reopen this one, so I've opened #1021

**Comment by RussTedrake** [comment]
i think erroring out when there are merge conflicts seems reasonable.  agreed we could report it more clearly.  do you have a better solution?

**Comment by avalenzu** [comment]
Sorry, I meant that they should report the merge conflict and stop immediately rather than throwing an error later in the build process.

**Comment by RussTedrake** [comment]
the more worrisome question is why this commit had a merge conflict in CMakeLists.txt .

**Comment by RussTedrake** [comment]
so, it does look like the histories had diverged... and both tried to add lots of files.

i've been using `git pull` to do the merge.  perhaps i should be doing a `git merge -no-ff` instead?  what do the git-masters think?

**Pull request closed without merging**
