### PR TITLE
[workspace] Add OpenUSD as an optional dependency

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20898.

The build rules still have plenty of TODOs before they will be ready to enable by default, but this might be enough to bootstrap #17833.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.  It's okay for this to wait until later in the week.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: I laughed, I cried.

> Reviewed 3 of 13 files at r1, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923#-:-NqooLYJ19tQ39hVwqBQ:bhh5l6i)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 13 files at r1, 11 of 11 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923#-:-Nr1MaFk29JVU5fnHyvG:bmxilld)* status: 1 unresolved discussion

___
*[`tools/BUILD.bazel` line 185 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20923#-Nr1KX6XB42adQhM-bhh:-Nr1KX6XB42adQhM-bhi:b-9xz9ju) ([raw file](https://github.com/RobotLocomotion/drake/blob/63708a5be333e49004194508a972602a74958206/tools/BUILD.bazel#L185)):*
> ```Starlark
> # See https://github.com/PixarAnimationStudios/OpenUSD for details.
> # Use `--define=WITH_USD=ON` on the bazel command line to enable it.
> # (In CI, also we have --config=everything enable it on Ubuntu 22.04 "Jammy".)
> ```

nit: typo?

Also, not uniquely Jammy, but Noble as well, yes?



_Suggestion:_
```Starlark
--config=everything to enable
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)* status: 1 unresolved discussion

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20923)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
