### PR TITLE
Change sprintf() to snprintf() to avoid security warnings/errors.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382)

### CODE REVIEW

**Comment by mitiguy** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.

**Review by mitiguy — COMMENTED** [review]
Feature review +@damrongguoy  (also for Platform review)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NI9xUoLCjvrZd7Y2Pxs:b-drt4v8)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NI9yDxhCwpcar_UQdF4:bnfp4nl)* status: needs platform reviewer assigned (waiting on @mitiguy)

**Review by DamrongGuoy — COMMENTED** [review]
-(status: single reviewer ok) 
+@xuchenhan-tri for platform review, please.

I hope we can merge this fix tonight.  The error showed up in this Buildcop discussion:
https://drakedevelopers.slack.com/archives/C270MN28G/p1669848472097319

+(priority: high) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NIA-GsjCy-Pm1HPlpLx:bpsizwz)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Drive-by platform :lgtm: in case Xuchen is busy.
+@sherm1 -@xuchenhan-tri 
OK to merge once the mac CI is successful.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NIA1NCvBrI7XIA9j3E1:bezi0gf)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @mitiguy)

**Review by DamrongGuoy — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NIA1gCV4-upJ_kxCNaY:b-ucfknh)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks. How's the file generated? Is it generated in MG and copypasted into drake? Or is it somehow generated within Drake?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NIA2AS11Zo-vBcp0a6u:b8aw20r)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @mitiguy)

**Review by DamrongGuoy — COMMENTED** [review]
Yes, Paul said it is generated in MG and copypasted into drake with slight modification.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NIA49d9E3QGTzmodSZ2:becw5jv)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
Got it. Thanks for the clarification.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382#-:-NIA50it6ye_CGH2KXJ3:b-hj23f3)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @mitiguy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18382#-NIAC7zSDC3WKKnDufiF:-NIAC7zSDC3WKKnDufiG:b-qkekfk) (no related file):*
The `mac-arm-monterey-clang-bazel-experimental-release` has passed now.

___

**Comment by SeanCurtis-TRI** [comment]
*[`multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18382#-NICp3ofAt_dqIirqQ44:-NICp3ofAt_dqIirqQ45:bnrlbmo) ([raw file](https://github.com/robotlocomotion/drake/blob/3a3d0332e6691c5d20412b0426b76c773ec6d9c5/multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc#L1)):*
> ```cpp
> // GENERATED FILE DO NOT EDIT
> ```

FYI Anyone else bothered by the juxtaposition of what this PR does and what this line says?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18382)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),DamrongGuoy

___
*[`multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18382#-NICp3ofAt_dqIirqQ44:-NIDYyTD4Co0-7XlN67q:bssjo2g) ([raw file](https://github.com/robotlocomotion/drake/blob/3a3d0332e6691c5d20412b0426b76c773ec6d9c5/multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc#L1)):*
Yes, that's a good point! This line should be edited also to say something like
> MG-generated file, slightly edited

**Comment by mitiguy** [comment]
PR #18391 added a comment to the top of the file MG_chaotic_babyboot_auto_generated.cc
Currently, that comment is
```// Note: This file was auto-generated by MotionGenesis and then slightly edited.```

**Pull request merged**
