### PR TITLE
Fix the Jaco example to work on real hardware (not just sim)

### LINKED ISSUE #14593: when running a real kinova arm the jaco_controller sends random data
externall driver for real kinova arm from https://github.com/mpatalberta/drake-jaco-driver
/example/kinova_jaco/jaco_controller.cc

The jaco_controller.cc initially received correctly the current angles of the actuators in the and broadcasts that information
Then the jaco_controller.cc starts outputing some very small number for about 10 - 20 second.
The sudden;y a series of non-zero numbers are send as angular velocity values which causes the arm to in a in correct manner.

Patrick Brown

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #14593

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203)

### CODE REVIEW

**Review by sammy-tri — COMMENTED** [review]
+@hongkai-dai for feature review if you don't mind (since our earlier discussion motivated me to finish fixing this)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203#-:-McLIV4J-TTKVDfD6Mla:b-l2wvpy)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:LGTM: with a minor comment

+@ggould-tri for Thursday's platform review (Sammy is the platform reviewer today).

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203#-:-McLPqnK0KCR4JoPdY59:b-kxd9t5)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sammy-tri)

___
*[examples/kinova_jaco_arm/jaco_controller.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McLPCmg3k_cZs_IS42p:-McLPCml3ldjBAiwvv16:b-uuyj6r) ([raw file](https://github.com/robotlocomotion/drake/blob/33ee28fb19e0520c75d80fef700e87803cd7c730/examples/kinova_jaco_arm/jaco_controller.cc#L165)):*
> ```cpp
>       diagram->GetMutableSubsystemContext(*plan_source, &diagram_context);
>   plan_source->Initialize(
>       t0, status_receiver->get_state_output_port().Eval(
> ```

Just curious why we make this change here? I would think the previous code (by setting `q0` with named field `first_status.joint_position` is more readable? As the updated version would have to assume that the first `num_joints + num_fingers` entries in the output signal correspond to the joint positions and finger positions.

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

___
*[examples/kinova_jaco_arm/jaco_controller.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McLPCmg3k_cZs_IS42p:-McLRwEO-k0QNJ-4gVYo:b-2v0lmp) ([raw file](https://github.com/robotlocomotion/drake/blob/33ee28fb19e0520c75d80fef700e87803cd7c730/examples/kinova_jaco_arm/jaco_controller.cc#L165)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious why we make this change here? I would think the previous code (by setting `q0` with named field `first_status.joint_position` is more readable? As the updated version would have to assume that the first `num_joints + num_fingers` entries in the output signal correspond to the joint positions and finger positions.
</blockquote></details>

It was a while ago when I wrote this, but IIRC it's because the finger positions in the status message aren't valid values for `q` and I didn't want to spread out the `kFingerSdkToUrdf` logic into more places than necessary (as in https://github.com/sammy-tri/drake/blob/master/manipulation/kinova_jaco/jaco_status_receiver.cc#L73 )   Of course, then I went and duplicated it again in this PR in `move_jaco_ee.cc`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sammy-tri)

___
*[examples/kinova_jaco_arm/jaco_controller.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McLPCmg3k_cZs_IS42p:-McLV1GH5R8HHePNpKJf:b6x0xk2) ([raw file](https://github.com/robotlocomotion/drake/blob/33ee28fb19e0520c75d80fef700e87803cd7c730/examples/kinova_jaco_arm/jaco_controller.cc#L165)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It was a while ago when I wrote this, but IIRC it's because the finger positions in the status message aren't valid values for `q` and I didn't want to spread out the `kFingerSdkToUrdf` logic into more places than necessary (as in https://github.com/sammy-tri/drake/blob/master/manipulation/kinova_jaco/jaco_status_receiver.cc#L73 )   Of course, then I went and duplicated it again in this PR in `move_jaco_ee.cc`.
</blockquote></details>

I see.

I am a little bit surprised that the status message aren't valid values for q. Here status_receiver fixes its input port to first_status. I would imagine if `first_status` (as the input to status_receiver) is not valid, then the output of the status_receiver is unlikely to be valid as well?

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

___
*[examples/kinova_jaco_arm/jaco_controller.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McLPCmg3k_cZs_IS42p:-McLkvd9AT0XCTca8Thd:b7x07jz) ([raw file](https://github.com/robotlocomotion/drake/blob/33ee28fb19e0520c75d80fef700e87803cd7c730/examples/kinova_jaco_arm/jaco_controller.cc#L165)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see.

I am a little bit surprised that the status message aren't valid values for q. Here status_receiver fixes its input port to first_status. I would imagine if `first_status` (as the input to status_receiver) is not valid, then the output of the status_receiver is unlikely to be valid as well?
</blockquote></details>

The status receiver contains the logic to turn the finger positions from the driver into reasonable `q` values for the model as loaded by the URDF, so evaluating the state output port will convert the message which we fixed into the input port (and subsequently received messages).

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203#-:-McPCQor1eEcCpQ3HHPQ:bnfp4nl)* status: 2 unresolved discussions (waiting on @hongkai-dai and @sammy-tri)

___
*[manipulation/kinova_jaco/jaco_command_receiver.cc, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McPBug69rd5E3pe_cpg:-McPBug69rd5E3pe_cph:bwjbmmp) ([raw file](https://github.com/robotlocomotion/drake/blob/33ee28fb19e0520c75d80fef700e87803cd7c730/manipulation/kinova_jaco/jaco_command_receiver.cc#L71)):*
> ```cpp
>   // value-initialization.
>   if (lcm::AreLcmMessagesEqual(*result, lcmt_jaco_command{})) {
>     const VectorXd arm_param = context.get_numeric_parameter(0).get_value();
> ```

minor:  Given how much offset arithmetic you do on this object's data, it would be wise to assert on its size here first.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203)* status: 1 unresolved discussion (waiting on @sammy-tri)

___
*[examples/kinova_jaco_arm/jaco_controller.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McLPCmg3k_cZs_IS42p:-McPY8PtCplyI71l7MnY:b-lg05om) ([raw file](https://github.com/robotlocomotion/drake/blob/695eb29ebfe0ea1e3f7ce4e416a43032571df4ec/examples/kinova_jaco_arm/jaco_controller.cc#L165)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The status receiver contains the logic to turn the finger positions from the driver into reasonable `q` values for the model as loaded by the URDF, so evaluating the state output port will convert the message which we fixed into the input port (and subsequently received messages).
</blockquote></details>

I see, thanks for the explanation!

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15203)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @sammy-tri)

___
*[manipulation/kinova_jaco/jaco_command_receiver.cc, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15203#-McPBug69rd5E3pe_cpg:-McPOJq5D-9otUPbrhm4:bxbuqfp) ([raw file](https://github.com/robotlocomotion/drake/blob/695eb29ebfe0ea1e3f7ce4e416a43032571df4ec/manipulation/kinova_jaco/jaco_command_receiver.cc#L71)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Given how much offset arithmetic you do on this object's data, it would be wise to assert on its size here first.
</blockquote></details>

Done.  It was already checked in `set_initial_position`, but may as well double check here since it's possible someone messed around with the context.

**Pull request merged**
