### PR TITLE
Fix for accuracy of feedthrough affine systems (#4192 fix)

### PR DESCRIPTION
**Pull request by naveenoid**
Fixes https://github.com/RobotLocomotion/drake/issues/4192 

Adds additional unit tests that verify the desired behaviour. 

+@jwnimmer-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4219)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXBkBqCPnwF-20pEVHq:-KXBkBqCPnwF-20pEVHr:b-f5b5t2) ([raw file](https://github.com/robotlocomotion/drake/blob/205ed5fe449810d771f05012319a0638bfff4515/drake/systems/framework/primitives/test/affine_system_test.cc#L87)):*
> ```cpp
> 
>   FeedthroughAffineSystemTest() {}
>   void SetUp()  {}
> ```

BTW I think the above two declarations could be removed.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXBl5HZbxWPPrEmSvFL:-KXBl5H__uZGDRQymdbT:b-f2ylwx) ([raw file](https://github.com/robotlocomotion/drake/blob/205ed5fe449810d771f05012319a0638bfff4515/drake/systems/framework/primitives/test/affine_system_test.cc#L128)):*
> ```cpp
> // when a single element of D is set to 1e-12.
> TEST_F(FeedthroughAffineSystemTest, FeedthroughTest) {
>   SetDCornerElement(1e-12);
> ```

The `1e-12` is very near the default Eigen tolerance.  Does this test indeed fail when the fix is absent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-:-KXBlHFhxr_i8MwuZGsK:bnfp4nl)*

**Comment by naveenoid** [comment]
+@sammy-tri for platform review please.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXBkBqCPnwF-20pEVHq:-KXDOYb9oq5F50eeRs2c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/205ed5fe449810d771f05012319a0638bfff4515/drake/systems/framework/primitives/test/affine_system_test.cc#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I think the above two declarations could be removed.
</details>
Done.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXBl5HZbxWPPrEmSvFL:-KXDOTti_AImKkBcHFfO:b-g79nly) ([raw file](https://github.com/robotlocomotion/drake/blob/205ed5fe449810d771f05012319a0638bfff4515/drake/systems/framework/primitives/test/affine_system_test.cc#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `1e-12` is very near the default Eigen tolerance.  Does this test indeed fail when the fix is absent?
</details>
Yes! It does indeed fail without the fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-:-KXDP4qpZ-MnCcGb_2_T:b-1zm1j3)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219)*

**Comment by jwnimmer-tri** [comment]
-@sammy-tri I am actually on-call platform for tomorrow, so will vote myself both roles for this PR.

LGTM, just some CI fixes needed.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-:-KXDQSZ-FEPALt4qgJR5:bur1elz)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219)*

**Comment by liangfok** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 89 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXGkkm-dAoPJVDSYnxH:-KXGkkm-dAoPJVDSYnxI:b-b7zwlu) ([raw file](https://github.com/robotlocomotion/drake/blob/29ff5c4032a29eace930d8644062e461f82b2ffe/drake/systems/framework/primitives/test/affine_system_test.cc#L89)):*
> ```cpp
>   }
> 
>   void InitialiseSystem() {
> ```

BTW: nit: UK spilling of "Initialize".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219)*

**Comment by liangfok** [comment]
*[drake/systems/framework/primitives/test/affine_system_test.cc, line 89 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXGkkm-dAoPJVDSYnxH:-KXGl-52q1wypZVdUOp2:b-xfyt3f) ([raw file](https://github.com/robotlocomotion/drake/blob/29ff5c4032a29eace930d8644062e461f82b2ffe/drake/systems/framework/primitives/test/affine_system_test.cc#L89)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: UK spilling of "Initialize".
</details>
*spelling :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/framework/primitives/test/affine_system_test.cc, line 89 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4219#-KXGkkm-dAoPJVDSYnxH:-KXHDDTh9QbQPEQp1rXU:bt09yhe) ([raw file](https://github.com/robotlocomotion/drake/blob/29ff5c4032a29eace930d8644062e461f82b2ffe/drake/systems/framework/primitives/test/affine_system_test.cc#L89)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> *spelling :smile: 
</details>
Man..Some habits are hard to lose!  Clion unfortunately doesnt seem to have a fix for this :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4219)*

**Pull request merged**
