### PR TITLE
Add comment about default destinations/strip prefixes in install script

### PR DESCRIPTION
**Pull request by jamiesnape**
Per comment in #6280.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6310)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware and +@soonho-tri for feature and platform review.

**Comment by soonho-tri** [comment]
:lgtm: Thank you!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6310#-:-KmDGzwei_7T_BFZaZP7:b-ae66e1)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6310)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6310#-:-KmDJNigTH75MV7_qCIr:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please

**Pull request merged**
