### PR TITLE
Disable the polishing step in rotation constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fix #8715

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-highsierra-clang-bazel-continuous-everything-release
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-highsierra-clang-bazel-nightly-everything-debug please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716#-:-LBIsaQ21zO_cmjmqwZo:b-oyl85t)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please

**Comment by hongkai-dai** [comment]
+(priority: high) 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716#-:-LBM26sj8sJ-YevA0k-3:b-z3xvff)*

**Comment by m-chaturvedi** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716#-:-LBJvu1a0veaWysQNf0U:bg7igkv)*

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716#-:-LBM2oGQ6H_u7vfMuH3v:b72l57d)*

**Comment by m-chaturvedi** [comment]
@EricCousineau-TRI for platform review, please.

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716)*

**Comment by EricCousineau-TRI** [comment]
*[solvers/rotation_constraint.cc, line 459 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8716#-LBMxWBXEXOZ0R8Nc9gv:-LBMxWBXEXOZ0R8Nc9gw:bslrdmf) ([raw file](https://github.com/robotlocomotion/drake/blob/cc8ca9df00e49dd79616e4d7d1be052863732a18/solvers/rotation_constraint.cc#L459)):*
> ```cpp
>   // guarantee that the constraints d <= nᵀ * pts.col(i), nᵀ * n = 1 are
>   // satisfied, we "polish" the optimization solution below.
>   n->normalize();
> ```

BTW Would it make sense to make an issue to revamp this feature, if it's ever necessary?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716)*

**Comment by EricCousineau-TRI** [comment]
:LGTM:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716#-:-LBMxSboEGQezg-MD2R5:bmxilld)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/rotation_constraint.cc, line 459 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8716#-LBMxWBXEXOZ0R8Nc9gv:-LBMyTIX2rgV-0SwfcjM:b9v1gtt) ([raw file](https://github.com/robotlocomotion/drake/blob/cc8ca9df00e49dd79616e4d7d1be052863732a18/solvers/rotation_constraint.cc#L459)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Would it make sense to make an issue to revamp this feature, if it's ever necessary?
</blockquote></details>

Done. Added an issue https://github.com/RobotLocomotion/drake/issues/8719

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8716)*

**Pull request merged**
