### PR TITLE
promote DirectCollocationConstraint to the public interface...

### PR DESCRIPTION
**Pull request by RussTedrake**
… because other related algorithms should be able to use the same constraint (I'm prototyping one such algorithm now).  Cleaned up the constructor and added some sugar to make it a better public API

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8355)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.  (please pass to sammy if/when you're happy with it)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8355#-:-L7VPH9wFTe3us1y-6gh:b6vo2a5)*

**Comment by hongkai-dai** [comment]
:lgtm: A few BTWs, +@sammy-tri for platform review please.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[systems/trajectory_optimization/direct_collocation.h, line 125 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VQr576ztFXEk0bmoi:-L7VQr576ztFXEk0bmoj:bnzjtvt) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/direct_collocation.h#L125)):*
> ```objc
> // Note: The order of arguments is a compromise between GSG and the desire to
> // match the AddConstraint interfaces in MathematicalProgram.
> solvers::Binding<solvers::Constraint> AddDirectCollocationConstraint(
> ```

I think the returned type should be `solvers::Binding<DirectCollocationConstraint>`?

---

*[systems/trajectory_optimization/direct_collocation.cc, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VRQCg8YpcLq9tjzsq:-L7VRQCg8YpcLq9tjzsr:b-ft0el3) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/direct_collocation.cc#L67)):*
> ```cpp
> }
> 
> void DirectCollocationConstraint::DoEval(
> ```

BTW, `initializeAutoDiff` could be expensive.

One approach to avoid `initializeAutoDiff`, is to write a template function
```C++
template <typename DerivedX, typename DerivedY>
DirectCollocationConstraint::DoEvalGeneric(const Eigen::MatrixBase<Derived>& x, Eigen::MatrixBase<DerivedY>* y) const {
...
}
```
This even works for symbolic expressions.

Feel free to dismiss this comment, if you find it not worthwhile to add the template function.

---

*[systems/trajectory_optimization/test/direct_collocation_test.cc, line 252 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VTUNW6ypq6Gp_2DQd:-L7VTUNW6ypq6Gp_2DQe:bhbjoj5) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/test/direct_collocation_test.cc#L252)):*
> ```cpp
>   EXPECT_EQ(prog.generic_constraints().size(), 1);
> 
>   // qdot = 0, u = 0 should be a fixed point for any q.  Test a simple one.
> ```

Could you add a TODO here, that we should not call `SetDecisionVariableValues`, and assign it to me? I have a PR https://reviewable.io/reviews/RobotLocomotion/drake/8344, that should only allow calling `SetDecisionVariableValues` from the solver.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-:-L7VTrW34Jk3eDeshm1z:b-frowsy)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[systems/trajectory_optimization/direct_collocation.h, line 125 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VQr576ztFXEk0bmoi:-L7VVlnMB9hlz-sodMBr:bqcs1uc) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/direct_collocation.h#L125)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the returned type should be `solvers::Binding<DirectCollocationConstraint>`?
</blockquote></details>

I had that, and actually spent a lot of time on it.  But ultimately reverted to this, because nobody can do anything with the extra type knowledge and because the python bindings require a refactor for exposing the Binding<DirectCollocationConstraint> type.  

fyi @ericcousineau-tri -- i had a version where I pulled the RegisterBinding out into a separate pybind header file, but it was getting too big for my small PR.

---

*[systems/trajectory_optimization/direct_collocation.cc, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VRQCg8YpcLq9tjzsq:-L7VWIehBYzkQgUB_dnt:b-latk1t) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/direct_collocation.cc#L67)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, `initializeAutoDiff` could be expensive.

One approach to avoid `initializeAutoDiff`, is to write a template function
```C++
template <typename DerivedX, typename DerivedY>
DirectCollocationConstraint::DoEvalGeneric(const Eigen::MatrixBase<Derived>& x, Eigen::MatrixBase<DerivedY>* y) const {
...
}
```
This even works for symbolic expressions.

Feel free to dismiss this comment, if you find it not worthwhile to add the template function.
</blockquote></details>

that is much cleaner.  i had it almost working, but it gets ugly again when I realized that my system_ and context_ are only of type autodiffxd_.  So I can't actually pass doubles through them.  

---

*[systems/trajectory_optimization/test/direct_collocation_test.cc, line 252 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VTUNW6ypq6Gp_2DQd:-L7V_1d55WnYFnc_Ey2a:b-bwxtpg) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/test/direct_collocation_test.cc#L252)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you add a TODO here, that we should not call `SetDecisionVariableValues`, and assign it to me? I have a PR https://reviewable.io/reviews/RobotLocomotion/drake/8344, that should only allow calling `SetDecisionVariableValues` from the solver.
</blockquote></details>

Done.  but why?  is there a better way to set the initial values?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/trajectory_optimization/direct_collocation.cc, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VRQCg8YpcLq9tjzsq:-L7VaCpe6JP7Sa8NVCWX:b7six7g) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/direct_collocation.cc#L67)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that is much cleaner.  i had it almost working, but it gets ugly again when I realized that my system_ and context_ are only of type autodiffxd_.  So I can't actually pass doubles through them.  
</blockquote></details>

Ah I see, thanks!

---

*[systems/trajectory_optimization/test/direct_collocation_test.cc, line 252 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VTUNW6ypq6Gp_2DQd:-L7V_gtRBr30gKD5NAVm:bgiat51) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/test/direct_collocation_test.cc#L252)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  but why?  is there a better way to set the initial values?
</blockquote></details>

Yes, we can call `SetInitialGuess` instead of `SetDecisionVariableValues`.

I think `SetDecisionVariableValues` should only be called by the solver, after it finds the solution to the problem.

You can then call
```
prog.EvalBinding(binding, prog.GetInitialGuess(prog.decision_variables()));
```
To evaluate the value of the binding. I can add some syntax sugar like `EvalBindingAtInitialGuess` in the future.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-:-L7VilcZBxxpXyxWwplD:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[systems/trajectory_optimization/test/direct_collocation_test.cc, line 252 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355#-L7VTUNW6ypq6Gp_2DQd:-L7VqFjdA_NHGrGaSCY_:bj725rd) ([raw file](https://github.com/robotlocomotion/drake/blob/7fd2124ba78e17cc1b52faddad4383c28fb05532/systems/trajectory_optimization/test/direct_collocation_test.cc#L252)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, we can call `SetInitialGuess` instead of `SetDecisionVariableValues`.

I think `SetDecisionVariableValues` should only be called by the solver, after it finds the solution to the problem.

You can then call
```
prog.EvalBinding(binding, prog.GetInitialGuess(prog.decision_variables()));
```
To evaluate the value of the binding. I can add some syntax sugar like `EvalBindingAtInitialGuess` in the future.
</blockquote></details>

sounds reasonable to me.  thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8355)*

**Pull request merged**
