### PR TITLE
Initial sim world of the PR2 simulation example

### PR DESCRIPTION
**Pull request by huihuaTRI**
I have learned several useful modeling skills when building a mobile-based robot. I would like to transfer that experience to Drake as an example for general users. Additionally, Drake does not have an example of a mobile-based robot yet. This effort will fill this vacancy.

The original plan is to use HSR as the example model. However, due to the mesh files of HSR is not open-source friendly, we have to switch to use PR2. The code will be designed to be generic. In the future, an HSR model can be easily added if the meshes files can be truly open-sourced.

This PR is the first of a series of PR train.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13240)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
An example with code in subdirectories is overkill.  Please fold all of the code into one (top level) folder before review gets too far along and we lose the threads.

**Comment by jwnimmer-tri** [comment]
If an example has ~10 files per directory (a nominal value for when using a directory is of merit) across several directories, then it's too big to be an in-tree example.  How many files total does this demo have in your WIP branch?

Also:
> This PR is the first of a series of PR train.

Take note that https://drake.mit.edu/developers.html#review-process says:
> For complex changes, especially those that will span multiple PRs, please open a GitHub issue and solicit design feedback before you invest a lot of time in code.

**Comment by sherm1** [comment]
I'd like to join the discussion also please @huihuaTRI.

**Comment by huihuaTRI** [comment]
Thanks for all the inputs. I am closing this PR for now to save some CI power. I will resubmit once it's ready.

**Pull request closed without merging**
