### PR TITLE
[py planning] Remove RobotBuilder const vs non-const distinction

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In Python, only the mutable getters make any sense when using the builder pattern.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18714)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for some review.

:lgtm: 

Is there some new latent style rule afoot here?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18714#-:-NN8gax_5nADzLDzjjBq:b-u6k1c7)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
See https://drake.mit.edu/doxygen_cxx/group__python__bindings.html at "Mutable vs. const Method Overloads":

> When a function is overloaded only by its const-ness, choose to bind the mutable overload, not the const overload.

Strictly speaking this is slightly different -- we are not literally overloaded, because we've adorned the function names to indicate const-ness.

In some cases like a `Context`, we very much care about `context.get_state()` vs `context.get_mutable_state()` both overloads, since they have very different implications.  In the case of a builder, though, I don't think it makes sense to care about constness in Python, since a "const Builder" would be an odd duck indeed.

**Comment by jwnimmer-tri** [comment]
I wonder if we should also change C++ to just use plain overloading for these, so C++ users don't need to type out `mutable_` everywhere either.  I looked at the git history in Anzu and the `mutable_` in the function name was there since 2018 when the class first appeared.

**Review by rpoyner-tri — COMMENTED** [review]
It's probably worth another look, but needn't block this patch.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18714#-:-NN95O3lCMtUeY2P-gO4:b-bfwr0g)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
Is this all new enough that no deprecation is required for the lost `mutable_` bindings?
Otherwise makes sense to me, platform :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18714#-:-NNCmIvT1q38dbl9XxHb:b42zju)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Is this all new enough that no deprecation is required for the lost mutable_ bindings?

Yes, exactly (#18650).  I should have said that in the PR overview; apologies.

**Pull request merged**
