### PR TITLE
Fixed some sign / unsigned issues in drake_mock_lcm_test.

### PR DESCRIPTION
**Pull request by liangfok**
I have no idea why these weren't detected prior to #4318.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4320)

### CODE REVIEW

**Comment by liangfok** [comment]
Minor changes. +@sammy-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-:-KXr2OYZw_4bkawzbZP9:b-s7x9g5)*

**Comment by liangfok** [comment]
This PR passed all CI tests and is this ready for review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-:-KXrcCucUIl4r3PakYse:b3kyjfm)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfcRmuQ_M_UhWqrxN:-KXrfcRmuQ_M_UhWqrxO:b-jgztws) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L33)):*
> ```cpp
>       dut.get_last_published_message(channel_name);
> 
>   EXPECT_EQ(message_size, static_cast<int>(published_message_bytes.size()));
> ```

BTW _This_ cast looks appropriate.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXrfT6CRY87F9MM0bPK:b-pdx83c) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
> ```cpp
> 
>   int get_buffer_size() {
>     return static_cast<int>(buffer_.size());
> ```

I don't understand what warning this fixes?  It seems like a habit we don't want to pursue.  Implicit conversion during return is widely used, and seems like what we want?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXroq8MP6gYzEweLDRC:b5zhre4) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand what warning this fixes?  It seems like a habit we don't want to pursue.  Implicit conversion during return is widely used, and seems like what we want?
</blockquote></details>

Not even _in an abundance of caution_?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXrpTY3Omv1ztmFutGu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Not even _in an abundance of caution_?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXrqmQJwt_BhwiJ7BOp:b-n6rdj6) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The runtime behavior is the same; the only difference is whether we call the reader's attention to the conversion that's happening.  There's fair arguments both ways, but my preference is to avoid the extra ceremony unless there's something special happening that warrants extra attention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-:-KXrqlENIDf0Qfy-9bjA:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXrv-jVW9wINufOeD8q:bqlevab) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The runtime behavior is the same; the only difference is whether we call the reader's attention to the conversion that's happening.  There's fair arguments both ways, but my preference is to avoid the extra ceremony unless there's something special happening that warrants extra attention.
</blockquote></details>

OK SGTM. This sounds like something we should add to the style guide. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by jwnimmer-tri** [comment]
*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXrvMtHNGC_K2eQC1vB:byy2l4f) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

OK SGTM. This sounds like something we should add to the style guide. What do you think?
</blockquote></details>

The proposed rule would be "don't add POD static casts unless the compiler forces you to?".

In this case I was questioning it, because I took this PR as one that fixes compiler warnings.  If an author thought the cast was helpful, I'm not sure I would want a style guide rule to get in their way of that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXsBVWvV6JemgPyC-AV:b81m9o8) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
Actually, I was thinking about adding a style guide entry that was less strong and instead simply enforces a bias:

> When a return value is being implicitly cast into a different type, prefer to not explicitly cast the type unless there is reason to call a reader's attention to this conversion taking place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by jwnimmer-tri** [comment]
*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXsCJ-izZSzyc2A_69I:bodffni) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Actually, I was thinking about adding a style guide entry that was less strong and instead simply enforces a bias:

> When a return value is being implicitly cast into a different type, prefer to not explicitly cast the type unless there is reason to call a reader's attention to this conversion taking place.
</blockquote></details>

I guess my general answer is that text in the style guide has a real cost, so adding small bits of (rarely used) advice is probably a net negative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/test/drake_mock_lcm_test.cc, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4320#-KXrfT6BMOVWyb76A-gG:-KXsDA0jORhGBW48K_BX:bcj4ntc) ([raw file](https://github.com/robotlocomotion/drake/blob/b9be5458c0a796f691468dd268635c7569e30b23/drake/lcm/test/drake_mock_lcm_test.cc#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess my general answer is that text in the style guide has a real cost, so adding small bits of (rarely used) advice is probably a net negative.
</blockquote></details>

OK, I'll just leave it in this thread :smile: .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4320)*

**Pull request merged**
