### PR TITLE
Add clang-format-includes to drakelint

### LINKED ISSUE #2269: Fix or suppress cpplint warnings for build/include_order
We should fix cpplint's `build/include_order` warnings throughout our code (and/or suppress them on a one-by-one-basis), and then stop suppressing the warning globally in `drake-distro/drake/CPPLINT.cfg`.  This is a break-out from #2064.

Depending on what fixing the errors looks like, we might also decide to permanently suppress this warning globally.  I will follow-up later with more specific recommendation for this particular warning set.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #2269.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6741)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.  (Try it locally by incorrectly sorting an `#include` statement, and see if the user experience for error reports needs any work.)

+@SeanCurtis-tri for platform review rotation, please.  I would also be curious to hear if there are any CLion hiccups here to address.

**Comment by jwnimmer-tri** [comment]
Note that the CI failures are (I think) due to #6742, and will disappear once that is resolved.  This PR passes for me locally on Xenial.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by liangfok** [comment]
:lgtm:

I test this by incorrectly sorting a `#include` statement and running `bazel test ...`:

```
$ bazel test ...
..............
INFO: Found 1100 targets and 2204 test targets...
INFO: From Executing genrule //drake/automotive:speed_bump_genrule:
[2017-08-02 10:19:31.374] [console] [info] Loading road geometry.
[2017-08-02 10:19:31.375] [console] [info] Generating OBJ.
FAIL: //drake/automotive:automotive_simulator_drake_lint (see /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake/bazel-out/clang-3.9-linux-opt/testlogs/drake/automotive/automotive_simulator_drake_lint/test.log).
INFO: From Testing //drake/automotive:automotive_simulator_drake_lint:
==================== Test output for //drake/automotive:automotive_simulator_drake_lint:
drakelint.py: Linting drake/automotive/automotive_simulator.cc
drakelint.py: Linting drake/automotive/automotive_simulator.h
error: the #include ordering is incorrect; to fix, run:
  bazel-bin/drake/tools/clang-format-includes drake/automotive/automotive_simulator.h
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
================================================================================
INFO: Elapsed time: 451.819s, Critical Path: 140.09s
//drake/automotive:automotive_simulator_drake_lint                       FAILED in 0.2s
  /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake/bazel-out/clang-3.9-linux-opt/testlogs/drake/automotive/automotive_simulator_drake_lint/test.log

Executed 2204 out of 2204 tests: 2203 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

After executing the suggested command, I re-ran `bazel test ...` without error.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-:-KqYKPlnJcBGzBp5JDDG:b-7nlvuj)*

**Comment by liangfok** [comment]
I also verified that the UX is OK when multiple files have bad `#include` ordering:

```
$ bazel test ...
INFO: Found 1100 targets and 2204 test targets...
FAIL: //drake/automotive:automotive_simulator_drake_lint (see /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake/bazel-out/clang-3.9-linux-opt/testlogs/drake/automotive/automotive_simulator_drake_lint/test.log).
INFO: From Testing //drake/automotive:automotive_simulator_drake_lint:
==================== Test output for //drake/automotive:automotive_simulator_drake_lint:
drakelint.py: Linting drake/automotive/automotive_simulator.cc
error: the #include ordering is incorrect; to fix, run:
  bazel-bin/drake/tools/clang-format-includes drake/automotive/automotive_simulator.cc
drakelint.py: Linting drake/automotive/automotive_simulator.h
error: the #include ordering is incorrect; to fix, run:
  bazel-bin/drake/tools/clang-format-includes drake/automotive/automotive_simulator.h
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
================================================================================
INFO: Elapsed time: 25.921s, Critical Path: 23.76s
//drake/automotive:automotive_simulator_drake_lint                       FAILED in 0.2s
  /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake/bazel-out/clang-3.9-linux-opt/testlogs/drake/automotive/automotive_simulator_drake_lint/test.log

Executed 2 out of 2204 tests: 2203 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-:-KqYLCnAoBq-ZGRTPo4i:b-k2yry5)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@ggould-tri  for final platform review.

The invocation of `clang-format-includes` does integrate nicely into CLion. Do you want to update `clion.rst` in this PR or shall we do a follow up PR?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-:-KqYVaOA7Og3Lr20zX4r:b-81tlxp)*

**Comment by jwnimmer-tri** [comment]
> Do you want to update clion.rst in this PR or shall we do a follow up PR?

I don't mind which PR it goes into, but I'd like a CLion user to write it up.  If someone wants to push a commit into this PR that's fine by me; or else a second PR is fine also.

**Comment by SeanCurtis-TRI** [comment]
I'll go ahead and put it on my plate after this merges.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-:-KqYXD0ssjklDuHKOpkc:bls45yr)*

**Comment by ggould-tri** [comment]
:lgtm: pending one defect below.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drakelint.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-KqYulQ0ZimJb2WQEyHR:-KqYulQ0ZimJb2WQEyHS:b-js5qkd) ([raw file](https://github.com/robotlocomotion/drake/blob/785af34bb2bf811f84d02f5c9a424cf3b228018a/tools/drakelint.py#L7)):*
> ```Python
> 
> def _check_invalid_line_endings(filename):
>     """Return 0 if all of the @p newlines are Unix, and 1 otherwise."""
> ```

This comment is now wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-:-KqYuzyFLZ1Fs790wsul:bwwjyca)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drakelint.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6741#-KqYulQ0ZimJb2WQEyHR:-KqYvoTl3sXOT6iXPjNV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/785af34bb2bf811f84d02f5c9a424cf3b228018a/tools/drakelint.py#L7)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This comment is now wrong.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741)*

**Comment by ggould-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6741)*

**Pull request merged**
