### PR TITLE
Replaced DoMain() and do_main() with main()

### PR DESCRIPTION
**Pull request by liangfok**
Fewer characters. I don't believe it's confusing given the name spaces.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3724)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ggould-tri for both levels of review please.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KTWFKNU9Ddy-aybzx4s:b-3s032)*

**Comment by ggould-tri** [comment]
You seem to be proposing a new code style convention here (and a change to existing conventions, as `Main` should be capitalized under current rules, although of course the existing `do_main` cases were already in violation).  That means that this PR should include a change to `code_style_guide.rst` and should probably get wider discussion than just the two of us.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KTix3hzVCyNvK5GC4lD:b-8rm4h)*

**Comment by ggould-tri** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724)*

**Comment by jwnimmer-tri** [comment]
I think `main` name should be allowed, under the "analogous to existing entity" exception:
https://google.github.io/styleguide/cppguide.html#Exceptions_to_Naming_Rules

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KTizWt5EoceyFlDfdyN:b-9luv7y)*

**Comment by ggould-tri** [comment]
I'm happy to agree with "allowed"!  But this PR, by changing all existing instances, seems to imply "required".  If the objective is consistency, but this is not documented as a rule, then new instances of `DoMain` are of unclear status.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KTj0GC17MDp3nZM6rLV:bik2urc)*

**Comment by jwnimmer-tri** [comment]
Okay.  I am happy to stand back and let _that_ discussion happen without me.

**Comment by liangfok** [comment]
I updated this PR to include a rule in the style guide. I will proceed to beg for comments.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KTjB6BsZflbO72asQzC:b7tkaq9)*

**Comment by david-german-tri** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 206 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-KTkX9hk4qNiX5AIdSZz:-KTkX9hk4qNiX5AIdS_-:b-1pjbk1) ([raw file](https://github.com/robotlocomotion/drake/blob/83969eb4fc21a69470ba8c9a09322735b68c1b36/drake/doc/code_style_guide.rst#L206)):*
> ```reStructuredText
> 
> * The ``main()`` method should be as brief as possible since it exists outside
>   of namespace ``drake``. It should simply call another ``main()`` that is
> ```

on this line, how about "should simply call another method"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

+@david-german-tri for platform review please.

-@liangfok

---

Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 206 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-KTkX9hk4qNiX5AIdSZz:-KToIN0698SbMC6y_lxR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83969eb4fc21a69470ba8c9a09322735b68c1b36/drake/doc/code_style_guide.rst#L206)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> on this line, how about "should simply call another method"?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KToIPDec8sd7yMqz-Et:bv2578n)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KToNtaEGrGhiDmKNfDd:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Now waiting on a review from @ggould-tri .

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KToQ5zXBHisYY0uEteP:b1quh89)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3724#-:-KToWc1cTdxo1cDQmzhU:bnfp4nl)*

**Pull request merged**
