### PR TITLE
CsdpSolver set RemoveFreeVariableMethod through SolverOptions.

### LINKED ISSUE #16732: Jupyter Kernel Dying when using AddSosConstraint
Consider the following:

 ```python
from pydrake.all import MathematicalProgram, Polynomial, Solve
import pydrake.symbolic as sym
import numpy as np
prog = MathematicalProgram()
x, u = prog.NewIndeterminates(1, "x"), prog.NewIndeterminates(1, "u")
V_sym = sym.Polynomial(u[0]**4 - 2*x[0]*u[0])
prog.AddSosConstraint(V_sym)
result = Solve(prog)
print(result.is_success())
```

If this cell is run in a Jupyter notebook, the kernel simply dies and gives no error message.

When run as a standalone python script, the terminal prints out "Constraint 2 is empty"

There appears to be some sort of parsing error in the AddSosConstraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Deprecate the constructor with RemoveFreeVariableMethod argument.
2. Change the default method to kLorentzConeSlack.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`solvers/csdp_solver.h` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30rV20-lN_LgN8brqG:-N30rV20-lN_LgN8brqH:b7umi0p) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/csdp_solver.h#L81)):*
> ```objc
>   explicit CsdpSolver(RemoveFreeVariableMethod method);
> 
>   /// Default constructor
> ```

nit Use `/** */` comment format on this ctor, for consistency with prior in the file.



_Suggestion:_
```objc
/** Default constructor */
```
___
*[`solvers/csdp_solver.h` line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30sTpQ1sso-_flnSqC:-N30sTpQ1sso-_flnSqD:bluy0rn) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/csdp_solver.h#L82)):*
> ```objc
> 
>   /// Default constructor
>   CsdpSolver();
> ```

To avoid springing a behavioral change on our users, perhaps the default value should to remain as `RemoveFreeVariableMethod::kNullspace` as it had been, until the 3-month notice period has expired?

It's technically within the Stable API policy to change a default value on a whim (_"Sometimes our software will choose a default value when nothing more specific is provided. Those defaults may change as we find better heuristics, without prior notice."_).

In this case, we need to make a trade-off between (1) possibly disrupting the behavior experienced by existing users with already-working code, and (2) improving the out-of-the-box experience for new users.

I'll let you take the final decision on whether to change the default immediately (as you have now -- improving (2) within the hazard of (1)), or postpone it for three months (deferring improvement (2) until then, with a slightly lower risk of (1) causing trouble).

Given that some of our CI tests seem to be failing due to the change in method, I would probably err of the side of keeping the default the same for now.
___
*[`solvers/csdp_solver.cc` line 479 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30zI1LEYM46dt2OZar:-N30zI1M3igRw3qgckPQ:b322u5l) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/csdp_solver.cc#L479)):*
> ```cpp
>     RemoveFreeVariableMethod method = method_;
>     if (it_method != int_options.end()) {
>       method = static_cast<RemoveFreeVariableMethod>(it_method->second);
> ```

This `static_cast<>` is undefined behavior if the user's integer is out-of-range for the enum.  We either need to bounds-check before casting, or change the switch-case below to use the bare integer with add new `default:` case that throws an error.
___
*[`solvers/test/mathematical_program_test_util.h` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31-3g97vsK4Nkbk5Uo:-N31-3g97vsK4Nkbk5Up:b-xquaj6) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/test/mathematical_program_test_util.h#L22)):*
> ```objc
>     const MathematicalProgram& prog, const SolverInterface& solver,
>     const std::optional<Eigen::VectorXd>& initial_guess = {},
>     const std::optional<SolverOptions>& solver_options = {});
> ```

Instead of wiring the options through all of the helper code, you could imagine setting CSDP's SolverOptions on the `prog` itself, instead of separately.  Would that be a simpler / worthwhile change?
___
*[`bindings/pydrake/solvers/csdp_py.cc` line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30yNqF1QHNmeI731m-:-N30yNqG9bjljzrkOn2l:bpu6l7s) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/bindings/pydrake/solvers/csdp_py.cc#L31)):*
> ```cpp
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
>   csdp_cls.def(py::init<RemoveFreeVariableMethod>(),
>       py::arg("method") = RemoveFreeVariableMethod::kLorentzConeSlack,
> ```

nit It might be worth a comment here that the default value comes from the member initializer list of the cc file.  (Usually, these defaults match with the header file, so someone reading this code needs to go hunting to find this source.)
___
*[`bindings/pydrake/solvers/test/csdp_solver_test.py` line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30yoOy7T3j0T4YuoGH:-N30yoOy7T3j0T4YuoGI:b-fznrmw) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/bindings/pydrake/solvers/test/csdp_solver_test.py#L62)):*
> ```Python
>         # Test removing free variables with a non-default method.
>         solver = CsdpSolver(
>             method=sdpa_free_format.RemoveFreeVariableMethod.kLorentzConeSlack)
> ```

I'm surprised that this isn't failing with a deprecation warning.

Looking more carefully, I see now that the bindings code failed to mark this constructor as deprecated.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`solvers/csdp_solver.h` line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30sTpQ1sso-_flnSqC:-N311cVX2IwFslG1yZw0:b-zaf9kb) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/csdp_solver.h#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To avoid springing a behavioral change on our users, perhaps the default value should to remain as `RemoveFreeVariableMethod::kNullspace` as it had been, until the 3-month notice period has expired?

It's technically within the Stable API policy to change a default value on a whim (_"Sometimes our software will choose a default value when nothing more specific is provided. Those defaults may change as we find better heuristics, without prior notice."_).

In this case, we need to make a trade-off between (1) possibly disrupting the behavior experienced by existing users with already-working code, and (2) improving the out-of-the-box experience for new users.

I'll let you take the final decision on whether to change the default immediately (as you have now -- improving (2) within the hazard of (1)), or postpone it for three months (deferring improvement (2) until then, with a slightly lower risk of (1) causing trouble).

Given that some of our CI tests seem to be failing due to the change in method, I would probably err of the side of keeping the default the same for now.
</blockquote></details>

Done. I switched back to the original default value.

Mathematically the original default value is better than the default value used in this PR, as the original one reduces the size of the optimization problem.

The CSDP failure is really a problem of CSDP, and I don't think that failure occurs often. If it really occurs, then we should provide some error message to tell the user to switch to a different RemoveFreeVariableMethod.
___
*[`solvers/csdp_solver.cc` line 479 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30zI1LEYM46dt2OZar:-N312yy714a9T4tLMsi0:bdb5my7) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/csdp_solver.cc#L479)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This `static_cast<>` is undefined behavior if the user's integer is out-of-range for the enum.  We either need to bounds-check before casting, or change the switch-case below to use the bare integer with add new `default:` case that throws an error.
</blockquote></details>

Done. TIL static_cast<> causes undefined behavior for out-of-range input.
___
*[`solvers/test/mathematical_program_test_util.h` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31-3g97vsK4Nkbk5Uo:-N3148xU2Y3HRAEkF6KM:b-r5hjac) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/test/mathematical_program_test_util.h#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Instead of wiring the options through all of the helper code, you could imagine setting CSDP's SolverOptions on the `prog` itself, instead of separately.  Would that be a simpler / worthwhile change?
</blockquote></details>

I am not sure how to change it here. This RunSolver function is called by `FindCommonLyapunov` function, which is used by all solvers. This `FIndCommonLyapunov` function constructs the MathematicalProgram internally. And in `csdp_solver_test`, we loop three three different methods to remove free variables, inside the loop we call `FindCommonLyapunov`.  So I set the method in `csdp_solver_test.cc` which doesn't have access to the prog constructed inside `FindCommonLyapunov`.
___
*[`bindings/pydrake/solvers/test/csdp_solver_test.py` line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30yoOy7T3j0T4YuoGH:-N31WT1o55tR3enYWUlq:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/bindings/pydrake/solvers/test/csdp_solver_test.py#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm surprised that this isn't failing with a deprecation warning.

Looking more carefully, I see now that the bindings code failed to mark this constructor as deprecated.
</blockquote></details>

Done. Good catch.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 12 of 18 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275#-:-N31d_5D-x11Hz716SkP:b-n37teh)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/test/mathematical_program_test_util.h` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31-3g97vsK4Nkbk5Uo:-N31_pZ68CWmQUzD_JQP:bvn2x0a) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/test/mathematical_program_test_util.h#L22)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure how to change it here. This RunSolver function is called by `FindCommonLyapunov` function, which is used by all solvers. This `FIndCommonLyapunov` function constructs the MathematicalProgram internally. And in `csdp_solver_test`, we loop three three different methods to remove free variables, inside the loop we call `FindCommonLyapunov`.  So I set the method in `csdp_solver_test.cc` which doesn't have access to the prog constructed inside `FindCommonLyapunov`.
</blockquote></details>

OK makes sense.
___
*[`solvers/test/second_order_cone_program_examples.h` line 267 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31aIR2Bwla34GGK76V:-N31aIR2Bwla34GGK76W:b-yefyid) ([raw file](https://github.com/robotlocomotion/drake/blob/bc1784747602010d0b62f6d6f719566149a4b8ec/solvers/test/second_order_cone_program_examples.h#L267)):*
> ```objc
> void SolveAndCheckSmallestEllipsoidCoveringProblems(
>     const SolverInterface& solver, double tol,
>     const std::optional<SolverOptions>& solver_options = std::nullopt);
> ```

nit It seems to me like for these various helpers we should be consistent about the order of `tol` vs `options`.  This is the only one that's different.

In other places we were happy to add `{}` at lots of call sites; I think the same applies here?

Or we could also imagine that for all of the _other_ changes the `options` should come last (preceded by `tol`) and default to nullopt, so that most call sites would not need to change?
___
*[`bindings/pydrake/solvers/csdp_py.cc` line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31_3QXBpfrL5gGurzM:-N31_3QXBpfrL5gGurzN:b-ip3vfq) ([raw file](https://github.com/robotlocomotion/drake/blob/bc1784747602010d0b62f6d6f719566149a4b8ec/bindings/pydrake/solvers/csdp_py.cc#L36)):*
> ```cpp
>       // This default value comes from the member initialization in
>       // DoSolve() function in csdp_solver.cc
>       py::arg("method") = RemoveFreeVariableMethod::kNullspace,
> ```

Oops, I'd forgotten how pybind11 works.  We should not have any default value here in the first place.  The default constructor is bound up above already, so if we reach this binding it means the user has supplied a `method=...` argument already, so the default here is inoperative in any case.
___
*[`bindings/pydrake/solvers/test/csdp_solver_test.py` line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30yoOy7T3j0T4YuoGH:-N31ZBs47Dwzd9c0TwIm:b-nrlfjp) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/bindings/pydrake/solvers/test/csdp_solver_test.py#L62)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Good catch.
</blockquote></details>

We should still retain a test of the kwarg (under `catch_drake_warnings`), to prove that the deprecated function works correctly.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`solvers/csdp_solver.h` line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30rV20-lN_LgN8brqG:-N31kOb-DnLG6WPRqc_f:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/solvers/csdp_solver.h#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Use `/** */` comment format on this ctor, for consistency with prior in the file.
</blockquote></details>

Done. 
___
*[`solvers/test/second_order_cone_program_examples.h` line 267 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31aIR2Bwla34GGK76V:-N31nb_gA1M6IQm3Xlzf:bu6wbxg) ([raw file](https://github.com/robotlocomotion/drake/blob/bc1784747602010d0b62f6d6f719566149a4b8ec/solvers/test/second_order_cone_program_examples.h#L267)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It seems to me like for these various helpers we should be consistent about the order of `tol` vs `options`.  This is the only one that's different.

In other places we were happy to add `{}` at lots of call sites; I think the same applies here?

Or we could also imagine that for all of the _other_ changes the `options` should come last (preceded by `tol`) and default to nullopt, so that most call sites would not need to change?
</blockquote></details>

Done, I put `options` before `tol` as that is less change from this revision.
___
*[`bindings/pydrake/solvers/csdp_py.cc` line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N31_3QXBpfrL5gGurzM:-N31otsFA1R3f4dc4fFA:bbx6a11) ([raw file](https://github.com/robotlocomotion/drake/blob/bc1784747602010d0b62f6d6f719566149a4b8ec/bindings/pydrake/solvers/csdp_py.cc#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I'd forgotten how pybind11 works.  We should not have any default value here in the first place.  The default constructor is bound up above already, so if we reach this binding it means the user has supplied a `method=...` argument already, so the default here is inoperative in any case.
</blockquote></details>

Done. I also forgot we removed the default argument.
___
*[`bindings/pydrake/solvers/test/csdp_solver_test.py` line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17275#-N30yoOy7T3j0T4YuoGH:-N31p_Ym50K1KMRbYBFN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/26a788aebe477e90f89ab9b3acd9de991746b42a/bindings/pydrake/solvers/test/csdp_solver_test.py#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We should still retain a test of the kwarg (under `catch_drake_warnings`), to prove that the deprecated function works correctly.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275#-:-N3fwqfN5ok76DPuF5wn:b-jarjz8)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 18 files at r1, 3 of 5 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17275#-:-N3tDiAS6Mi0gt2ypPwk:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
