### PR TITLE
Add tests for small-size LMI.

### PR DESCRIPTION
**Pull request by hongkai-dai**
LMI with matrix size 1x1 and 2x2.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OB8GNMW0R_ikl8xJUoO:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OBXJGr-7VVygx0S6uaa:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/mosek_solver_test.cc` line 567 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-OB8YpXU1VztGSLiH7z5:-OB8YpXV3Ksjs4q4Zyct:b-d0ep42) ([raw file](https://github.com/RobotLocomotion/drake/blob/569a8f7719f2ef6f01cac2948226f503184abf9c/solvers/test/mosek_solver_test.cc#L567)):*
> ```cpp
>   MosekSolver solver;
>   if (solver.available()) {
>     Test2x2LMI(solver, 1E-7, /*check_dual=*/false, /*dual_tol=*/1E-7);
> ```

Do we not get the dual variables in mosek?

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OBXUaaNETbQHY-ObwkT:b-3lhrgq)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/mosek_solver_test.cc` line 567 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-OB8YpXU1VztGSLiH7z5:-OBXUWg23dQqXg5IzRNP:b-g5fqae) ([raw file](https://github.com/RobotLocomotion/drake/blob/569a8f7719f2ef6f01cac2948226f503184abf9c/solvers/test/mosek_solver_test.cc#L567)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Do we not get the dual variables in mosek?
</blockquote></details>

Not until #22144 is merged.

**Comment by xuchenhan-tri** [comment]
**@drake-jenkins-bot** linux-jammy-gcc-bazel-experimental-debug please.

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: none) :lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OBY8_5z8LBRb_hffUxs:bxzxa9l)* status: 2 unresolved discussions

**Review by AlexandreAmice — COMMENTED** [review]
+(status: do not merge) until resolution of #22144 (otherwise I am worried we will forget to change the `check_dual` flag)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OB_x-RY1Zq8SejkoCSs:b-yzm1ua)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
@AlexandreAmice FYI, I just merged #22144.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OBaSoUbBA3VA3Pocun8:b-a5wi7)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143)* status: 1 unresolved discussion, labeled "do not merge"

___
*[`solvers/test/mosek_solver_test.cc` line 567 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-OB8YpXU1VztGSLiH7z5:-OBaqdtp7DOTU0NmAlzo:bep6n07) ([raw file](https://github.com/RobotLocomotion/drake/blob/569a8f7719f2ef6f01cac2948226f503184abf9c/solvers/test/mosek_solver_test.cc#L567)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not until #22144 is merged.
</blockquote></details>

Done, now the check is enabled.

**Review by AlexandreAmice — COMMENTED** [review]
-(status: do not merge) 

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OBbEjtQ3ghVU7QCQuyl:b-b9fcpn)* status: labeled "do not merge" (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
Good to merge

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22143#-:-OBbEqAPBZHpTkBkQur8:b-agnhyn)* status: labeled "do not merge" (waiting on @hongkai-dai)

**Pull request merged**
