### PR TITLE
Repair a few more drake subdir paths in docs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7934)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7934#-L4Lx_5u-1p23zifqGXv:-L4Lx_5vFtY7-PNNywqT:b-xppnht) ([raw file](https://github.com/robotlocomotion/drake/blob/c9b1c510d7626004d06c1a91e78e7bf89c4cb272/doc/bazel.rst#L92)):*
> ```reStructuredText
>   bazel test --config=kcov common:polynomial_test      # Run one test under kcov (see instructions below).
>   bazel build -c dbg common:polynomial_test && \
>     gdb ../bazel-bin/common/polynomial_test            # Run one test under gdb.
> ```

I think ./ is correct here now, rather than ../

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7934)*

**Comment by rpoyner-tri** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7934)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7934#-L4Lx_5u-1p23zifqGXv:-L4M2VgXdjdKdjzmJWzL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9b1c510d7626004d06c1a91e78e7bf89c4cb272/doc/bazel.rst#L92)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I think ./ is correct here now, rather than ../
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7934)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7934#-:-L4M8hroQ7sMr3SWwqEK:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Comment by sherm1** [comment]
I appreciate your ongoing efforts to make this change work, Jeremy. It also makes me a little sad since I think it was better (less brittle) before. But, since we're apparently going this way ... :lgtm:.

---

Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7934#-:-L4MX80sqc5kqXx8KGho:b-iustr1)*

**Pull request merged**
