### PR TITLE
Retrieve dual solution for conic constraint in Mosek.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As a step towards #13285

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
We believe the current CI failure is due to a bug in Mosek. Currently Drake uses Mosek 9.0. @TobiaMarcucci tested with Mosek 9.2 and the solution is correct. I will upgrade Drake's supported Mosek to 9.2, and also update TRI's Mosek license.

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383#-:-MQDoGgN6HIshjXSlcFd:b-uss1yj)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
Checkpoint

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383#-:-MQEPWGJAZi8vzddRPC8:b13s2ul)* status: 3 unresolved discussions, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu and @hongkai-dai)

___
*[solvers/mathematical_program_result.h, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQEJkTwBGNWBExaPkyi:-MQEJkTwBGNWBExaPkyj:b-fnqvq6) ([raw file](https://github.com/robotlocomotion/drake/blob/a950695a12c49da1339b0d057cc9c4145afbcfda/solvers/mathematical_program_result.h#L254)):*
> ```objc
>    * inequality, linear equality, bounding box constraints, and general
>    * nonlinear constraints), We interpret the dual variable value as the "shadow
>    * price" of the original problem. Namely if we change the constraint bound by
> ```

nit: "we" should no longer be capitalized.
___
*[solvers/mathematical_program_result.h, line 278 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQEOlXp06DAmBkgBk0P:-MQEOlXp06DAmBkgBk0Q:b-u9rjq4) ([raw file](https://github.com/robotlocomotion/drake/blob/a950695a12c49da1339b0d057cc9c4145afbcfda/solvers/mathematical_program_result.h#L278)):*
> ```objc
>    * the dual solution is the same as the linear inequality constraint.
>    *
>    * The interpretation for the dual variable to conic constraint x ∈ K can be
> ```

The overlap between the types of constraints discussed in this paragraph and the following one makes this section a bit confusing.

The conic constraint support in Gurobi is only for (rotated) Lorentz cones constraints right?

If so, it feels to me like this paragraph should come after the one about Lorentz cones and strictly deal with non-Lorentz cones in solvers other than Gurobi.
___
*[solvers/mathematical_program_result.h, line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQEOUEw0aQAC0Ql7Jjr:-MQEOUEw0aQAC0Ql7Jjs:b-2cyja1) ([raw file](https://github.com/robotlocomotion/drake/blob/a950695a12c49da1339b0d057cc9c4145afbcfda/solvers/mathematical_program_result.h#L316)):*
> ```objc
>    *    solution to the (rotated) Lorentz cone constraint doesn't have the
>    *    "shadow price" interpretation, but should lie in the dual cone, and
>    *    satisfy the KKT * condition. For more information, refer to
> ```

nit: stray "*" here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

___
*[solvers/mathematical_program_result.h, line 278 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQEOlXp06DAmBkgBk0P:-MQES4Pt4enZzgrluAAY:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a950695a12c49da1339b0d057cc9c4145afbcfda/solvers/mathematical_program_result.h#L278)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

The overlap between the types of constraints discussed in this paragraph and the following one makes this section a bit confusing.

The conic constraint support in Gurobi is only for (rotated) Lorentz cones constraints right?

If so, it feels to me like this paragraph should come after the one about Lorentz cones and strictly deal with non-Lorentz cones in solvers other than Gurobi.
</blockquote></details>

Done. Good call.

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@sherm1 for platform review.

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383#-:-MQIop-QBdPx7y2KwEIT:bol08qe)* status: LGTM missing from assignee sherm1(platform) (waiting on @avalenzu and @sherm1)

**Review by avalenzu — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few nits and possibly an additional unit test.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383#-:-MQJUok30gEPKdGbrZPe:b-lhmy0i)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_result.h, line 309 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQJRnNx0mbVYTka76Zo:-MQJRnNy8hGOQvOdOkBq:bux1z0m) ([raw file](https://github.com/robotlocomotion/drake/blob/73a734134d9481841fcfa09a336da0f8cb5d5a92/solvers/mathematical_program_result.h#L309)):*
> ```objc
>    *    https://docs.mosek.com/9.2/capi/prob-def-conic.html#duality-for-conic-optimization
>    *    as an explanation.
>    * The interpretation for the dual variable to conic constraint x ∈ K can be
> ```

nit: I believe you need a blank line here to avoid having this paragraph absorbed into paragraph number 3.
___
*[solvers/mathematical_program_result.h, line 311 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQJS5Sh52i0_7rMyLWO:-MQJS5Sh52i0_7rMyLWP:bg4ta5r) ([raw file](https://github.com/robotlocomotion/drake/blob/73a734134d9481841fcfa09a336da0f8cb5d5a92/solvers/mathematical_program_result.h#L311)):*
> ```objc
>    * The interpretation for the dual variable to conic constraint x ∈ K can be
>    * different. Here K is a convex cone, including exponential cone, power cone
>    * , PSD cone, etc. When the problem is solved by a convex solver (like SCS,
> ```

nit: misplaced comma
___
*[solvers/test/mosek_solver_test.cc, line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQJTc4I8wJx_2werp2q:-MQJTc4I8wJx_2werp2r:b-8pc0sl) ([raw file](https://github.com/robotlocomotion/drake/blob/73a734134d9481841fcfa09a336da0f8cb5d5a92/solvers/test/mosek_solver_test.cc#L468)):*
> ```cpp
> }
> 
> GTEST_TEST(MosekSolver, SocpDualSolution1) {
> ```

minor: please add comments explaining why these tests are here. It's not obvious to me what is the relationship between these tests and the new types of dual solution results. Are they all being tested? I didn't spot a test for the exponential cone constraint.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383)* status: 1 unresolved discussion (waiting on @avalenzu and @sherm1)

___
*[solvers/test/mosek_solver_test.cc, line 468 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14383#-MQJTc4I8wJx_2werp2q:-MQJyMfB0R14MXiNx2M7:buygbaq) ([raw file](https://github.com/robotlocomotion/drake/blob/73a734134d9481841fcfa09a336da0f8cb5d5a92/solvers/test/mosek_solver_test.cc#L468)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: please add comments explaining why these tests are here. It's not obvious to me what is the relationship between these tests and the new types of dual solution results. Are they all being tested? I didn't spot a test for the exponential cone constraint.
</blockquote></details>

Good call. I added the test for the exponential cone constraint dual solution.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,sherm1(platform)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest all please

**Review by avalenzu — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14383)* status: :shipit: complete! all discussions resolved, LGTM from assignees avalenzu,sherm1(platform)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
