### PR TITLE
call_python: Test plotting.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Since #7516 has landed, this enables plotting tests for `call_python`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7657)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature and platform review, please.
(This should also fix some CI failures regarding the ASan / LSan failures.)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7657#-:-L1-BTc8jK-0llbBMgaB:b-o9z28)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/BUILD.bazel, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7657#-L1-J8LcPdlM9s32Yfdd:-L1-J8LdP4fjnd0wFtJ3:b-j0n8dm) ([raw file](https://github.com/robotlocomotion/drake/blob/2028f8f8dd0c3af313212828b23554fdc17d4485/common/proto/BUILD.bazel#L114)):*
> ```Python
>     local = 1,
>     # The `call_python_test` binary is flaky with asan / lsan; however, when
>     # the binary fails, there is no diagnostic information. It simply aborts.
> ```

BTW Should this be a TODO?  (In other words, I guess its unclear to me whether we intend to live with this, or prefer to fix it.  A statement one way or the other in the comment here should suffice.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7657#-:-L1-KLyoes8DIih8AqvX:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/BUILD.bazel, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7657#-L1-J8LcPdlM9s32Yfdd:-L1-N-Xg9gAory6ZMG8Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2028f8f8dd0c3af313212828b23554fdc17d4485/common/proto/BUILD.bazel#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this be a TODO?  (In other words, I guess its unclear to me whether we intend to live with this, or prefer to fix it.  A statement one way or the other in the comment here should suffice.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7657)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7657)*

**Pull request merged**
