### PR TITLE
Convert a monomial basis element to the sum of chebyshev basis elements.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994)

### CODE REVIEW

**Review by TobiaMarcucci — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994)* status: 2 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[common/symbolic_monomial_basis_element.h, line 144 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13994#-MGD17Xf4j99sDOHbtug:-MGD17Xf4j99sDOHbtuh:b3iccmg) ([raw file](https://github.com/robotlocomotion/drake/blob/5741f504befa49c8be91742a53d527f21db94eb2/common/symbolic_monomial_basis_element.h#L144)):*
> ```objc
>    * {[T₂(x)⇒0.5], [T₀(x)⇒0.5]}
>    * when this = x²y³, then we return
>    * {[T₂(x)T₃(y)⇒1/8], [T₂(x)T₁(y)⇒3/8], [T₀(x)T₃()⇒1/8], [T₀(x)T₁(y)⇒3/8]}
> ```

Missing y in T3() in the third element of the set.
___
*[common/symbolic_monomial_basis_element.cc, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13994#-MGD2YpkEscNChiVYH8i:-MGD2YpkEscNChiVYH8j:bdi90vg) ([raw file](https://github.com/robotlocomotion/drake/blob/5741f504befa49c8be91742a53d527f21db94eb2/common/symbolic_monomial_basis_element.cc#L199)):*
> ```cpp
>   // https://archive.siam.org/books/ot99/OT99SampleChapter.pdf, we know that
>   // xⁿ = 2 ¹⁻ⁿ∑ₖ cₖ Tₙ₋₂ₖ(x), k = 0, ..., floor(n/2)
>   // where cₖ = 0.5 nchoosek(n, k) if k=n/2, and cₖ = nchoosek(n, k)
> ```

Reading the reference it seems that the term that needs the 1/2 in front is the one for k=0 and not the one for k=n/2. But I did a couple of manual checks and your formula seems the correct one. I don't understand if I'm missing something obvious here?

**Review by TobiaMarcucci — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994#-:-MGE_Q4e6jmHyX6zUnmC:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @TobiaMarcucci)

**Review by TobiaMarcucci — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994#-:-MGFOPB55bqi8q2g0WC-:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[common/symbolic_monomial_basis_element.h, line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13994#-MGFNeV19FzZ04yxs2p1:-MGFNeV19FzZ04yxs2p2:bt21fe3) ([raw file](https://github.com/robotlocomotion/drake/blob/c53240d3eec34428b79da31dc37e5e65a74f09b1/common/symbolic_monomial_basis_element.h#L137)):*
> ```objc
> 
>   /**
>    * Convert this monomial to Chebyshev polynomial basis. For example
> ```

nit, could you use this version?

```
   * Converts this monomial to Chebyshev polynomial basis. For example,
   *  - For x², it returns 0.5T₂(x) + 0.5T₀(x).
   *  - For x²y³, it returns 1/8T₂(x)T₃(y) + 3/8T₂(x)T₁(y) + 1/8T₀(x)T₃(y)
   *    + 3/8T₀(x)T₁(y).
   * We return the map from each ChebyshevBasisElement to its coefficient.
   * For example, when this = x², it returns {[T₂(x)⇒0.5], [T₀(x)⇒0.5]}.
   * When this = x²y³, it returns {[T₂(x)T₃(y)⇒1/8], [T₂(x)T₁(y)⇒3/8],
   * [T₀(x)T₃(y)⇒1/8], [T₀(x)T₁(y)⇒3/8]}.
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994)* status: :shipit: complete! all discussions resolved, LGTM from assignees TobiaMarcucci,soonho-tri(platform) (waiting on @soonho-tri and @TobiaMarcucci)

___
*[common/symbolic_monomial_basis_element.h, line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13994#-MGFNeV19FzZ04yxs2p1:-MGG5LRM8CLSvGd5kCVx:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/c53240d3eec34428b79da31dc37e5e65a74f09b1/common/symbolic_monomial_basis_element.h#L137)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, could you use this version?

```
   * Converts this monomial to Chebyshev polynomial basis. For example,
   *  - For x², it returns 0.5T₂(x) + 0.5T₀(x).
   *  - For x²y³, it returns 1/8T₂(x)T₃(y) + 3/8T₂(x)T₁(y) + 1/8T₀(x)T₃(y)
   *    + 3/8T₀(x)T₁(y).
   * We return the map from each ChebyshevBasisElement to its coefficient.
   * For example, when this = x², it returns {[T₂(x)⇒0.5], [T₀(x)⇒0.5]}.
   * When this = x²y³, it returns {[T₂(x)T₃(y)⇒1/8], [T₂(x)T₁(y)⇒3/8],
   * [T₀(x)T₃(y)⇒1/8], [T₀(x)T₁(y)⇒3/8]}.
```
</blockquote></details>

Done, thanks!

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13994)* status: :shipit: complete! all discussions resolved, LGTM from assignees TobiaMarcucci,soonho-tri(platform)

**Pull request merged**
