### PR TITLE
Tests to ensure RigidTransform<double> can work with optimization instructions.

### PR DESCRIPTION
**Pull request by mitiguy**
Optimization (e.g., AVX instructions for multiplying rigid transforms) can leverage a continuous memory layout of RigidTransform<double> as 12 sequential doubles starting with a 3x3 RotationMatrix<double> (9 doubles) immediately followed by a 3x1 position vector (3 doubles).

A unit test verifies the order is always R_AB_followed by  p_AoBo_A_.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14643)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
feature review +@sherm1 

For now, I only added a static_assert in one location.  I was thinking I could add it in all RigidTransform<T> operator*.  However, there is probably a better way to centralize this.  Instead of guessing, I just added it in one place and will wait to talk to you.  

Note: This PR #14643 relates to PR #14623 and PR #14626 and https://docs.google.com/document/d/1e8wGEkvTg3Lqke91P0UNFZzF7IRnlgtqKrquwYhfLaM/edit?pli=1#

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14643#-:-MTOCw8p3LmdZkCJPS5T:b-owp5w1)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature pass done -- you can simplify.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14643#-:-MTbAls6C-anu3CExl8y:b-jp2zqm)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[math/rigid_transform.h, line 437 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTb64H1DM_KrTTCzWEJ:-MTb64H1DM_KrTTCzWEK:bbpqs64) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/rigid_transform.h#L437)):*
> ```objc
>     static_assert(!std::is_same<double, T>() ||
>             sizeof(RigidTransform<double>) == optimal_sizeof_RigidTransformd_,
>         "Optimized instructions depend on sizeof(RigidTransform<double>).");
> ```

minor: move this to just after the definition of RigidTransformd (around line 625). Then this works fine:
```
static_assert(sizeof(RigidTransformd) == 12 * sizeof(double),
    "Low-level optimizations depend on RigidTransform<double> being "
    "stored packed in memory.");
```

(I reworded it some -- the phrase "optimized instructions" doesn't make sense to me. It is low-level optimized methods that are dependent on knowing the memory layout -- those could be written in C++ and would still have that same requirement.)

Note that this is enough by itself -- you don't need to define a separate size constant and there is not need for checking if T==double. `is_same()` wasn't doing anything here anyway since you were making an assertion about `RigidTransform<double>` not `RigidTransform<T>`.
___
*[math/rigid_transform.h, line 613 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTb4YcR6ZKLrudguB-9:-MTb4YcR6ZKLrudguB-A:b-m4jl11) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/rigid_transform.h#L613)):*
> ```objc
>   // two adjacent members not to be allocated immediately after each other.
>   // Related: https://github.com/RobotLocomotion/drake/pull/14626
>   // Related: https://github.com/RobotLocomotion/drake/pull/14623
> ```

nit: the above comment seems excessive and somewhat self-contradictory. The compiler guarantees the storage order (as you mentioned); all we're doing here is requiring packed storage. Also, likely not helpful to reference those Draft/WIP PRs which will have a very short lifetime. 
___
*[math/rigid_transform.h, line 614 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTb4FLa2AAdZkzM3AIU:-MTb4FLa2AAdZkzM3AIV:buf6zm1) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/rigid_transform.h#L614)):*
> ```objc
>   // Related: https://github.com/RobotLocomotion/drake/pull/14626
>   // Related: https://github.com/RobotLocomotion/drake/pull/14623
>   static constexpr double optimal_sizeof_RigidTransformd_ = 12 * sizeof(double);
> ```

nit: per f2f should call this compile-time constant `kRequiredSize` or something like that.
___
*[math/test/rigid_transform_test.cc, line 725 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTavhQV8ZAf6WXXN_Sx:-MTavhQV8ZAf6WXXN_Sy:b3htasy) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/test/rigid_transform_test.cc#L725)):*
> ```cpp
>   // sequential doubles starting with a 3x3 RotationMatrix<double> (9 doubles)
>   // immediately followed by a 3x1 position vector (3 doubles).  This unit test
>   // verifies the ordering remains as first R_AB_followed by  p_AoBo_A_.
> ```

minor: Shouldn't mention the member names here -- those could change and don't matter for this test anyway. What matters is that the rotation matrix occupies the first 9 double and the offset the last 3, and that's what the test is ensuring.

Something like:
"To enable low-level optimizations we insist that `RigidTransform<double>` is packed into 12 consecutive doubles, with a 3x3 `RotationMatrix<double>` in the first 9 and the translation vector occupying the last 3."

**Comment by jwnimmer-tri** [comment]
Two high-level thoughts:

(1) I would not be surprised if using https://en.cppreference.com/w/cpp/types/offsetof provided for a much simpler patch than this PR.  I think it's the offsets that you care about, not the sizes?

(2) My own sense of taste says that putting this in the RigidTransform header is ill-suited -- I would place the assertion directly adjacent to the casts which depend on it (i.e., code that isn't on master yet).  Having the check so far away from the code which depends on it seems like a maintenance headache to keep them in sync.

**Comment by sherm1** [comment]
offsetof could work too -- I think they are equivalent in this case. The optimized functions depend on the entire layout, both size and offset.

Putting this static_assert with the AVX methods doesn't work for reasons you explained before -- enabling those instructions for a compilation unit can affect how Eigen aligns things. We want to ensure that the non-AVX code that allocates the RigidTransforms is creating objects that are compatible with the low-level `double*` methods. I think putting the test in the header is the best way that no compilation unit creates these objects in a way that is incompatible with the low-level methods.

**Review by mitiguy — COMMENTED** [review]
@sherm1   This is ready for another look.
Hmmm -- would it be necessary to consider the template type when dealing with offsetof()? 
https://stackoverflow.com/questions/21577845/using-offsetof-for-template-classes

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14643#-:-MTgk2QmA7pjo7mFU_9n:b-y5pdul)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[math/rigid_transform.h, line 437 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTb64H1DM_KrTTCzWEJ:-MTgYnKPDtwuaVCfVMBo:b-i1xak) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/rigid_transform.h#L437)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: move this to just after the definition of RigidTransformd (around line 625). Then this works fine:
```
static_assert(sizeof(RigidTransformd) == 12 * sizeof(double),
    "Low-level optimizations depend on RigidTransform<double> being "
    "stored packed in memory.");
```

(I reworded it some -- the phrase "optimized instructions" doesn't make sense to me. It is low-level optimized methods that are dependent on knowing the memory layout -- those could be written in C++ and would still have that same requirement.)

Note that this is enough by itself -- you don't need to define a separate size constant and there is not need for checking if T==double. `is_same()` wasn't doing anything here anyway since you were making an assertion about `RigidTransform<double>` not `RigidTransform<T>`.
</blockquote></details>

Done and moved below so it appear near the relevant member data.
___
*[math/rigid_transform.h, line 613 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTb4YcR6ZKLrudguB-9:-MTgXPqo6Iy9SFvMD4jj:b2knjx2) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/rigid_transform.h#L613)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: the above comment seems excessive and somewhat self-contradictory. The compiler guarantees the storage order (as you mentioned); all we're doing here is requiring packed storage. Also, likely not helpful to reference those Draft/WIP PRs which will have a very short lifetime. 
</blockquote></details>

Done.  Shortened and removed references to PRs.
___
*[math/rigid_transform.h, line 614 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14643#-MTb4FLa2AAdZkzM3AIU:-MTgcMUh9xj54k92-Lgr:b-rchrk9) ([raw file](https://github.com/robotlocomotion/drake/blob/2d0f43477ce160ea32d29795db7d21f993213131/math/rigid_transform.h#L614)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per f2f should call this compile-time constant `kRequiredSize` or something like that.
</blockquote></details>

Based on your advice, no longer needed.

**Review by sherm1 — COMMENTED** [review]
Thanks, Paul. Feature :lgtm:
+@soonho-tri for platform review per rotation, please

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14643#-:-MTgu-8q-mD58BZx6mod:bxpkgg4)* status: LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14643#-:-MTkSikY8hk6Ygn5TtuJ:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
