### PR TITLE
disable tsan for diff ik test due to issue #6179

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7980)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-tsan-everything-bazel please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-tsan-everything-bazel

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-continuous-memcheck-tsan-everything-bazel please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by siyuanfeng-tri** [comment]
+@soonho-tri +@ericcousineau-tri for reviews. thanks!

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7980#-:-L4kfaSJCYNB69tMF3jf:btgc54s)*

**Comment by soonho-tri** [comment]
:lgtm: 

This should resolve the `tsan` issues but we have a timeout on macOS. See https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-highsierra-clang-bazel-continuous-everything-release/287/console

FYI, the two issues (tsan gitch, timeout on macOS) happen because it's using MOSEK, not SNOPT, when both of them are available (i.e. `--config=everything`).

I think one solution is to enable this test *only* when SNOPT is enabled but MOSEK is not.

/cc @jamiesnape 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7980#-:-L4l7qcX2yaMfD_pPFAL:b-85n8eb)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

@soonho-tri It looks like this code uses `SnoptSolver`, so having SNOPT test tags should be sufficient? (no need to exclude MOSEK?)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7980#-:-L4lIYJoE8bs4SzhEhhI:bpvbp9f)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by soonho-tri** [comment]
> so having SNOPT test tags should be sufficient? (no need to exclude MOSEK?)

It is the case now (but it was not previously ). I'm happy with it. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7980#-:-L4lJFmzArziTWZsTUNN:bw2xumm)*

**Comment by EricCousineau-TRI** [comment]
Waiting for CI tests to pass.

**Comment by soonho-tri** [comment]
MacOS test failed:

```
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.0043657506761719811, which exceeds 1e-4, where
V_WE_E(j) evaluates to 0.135871675588146,
V_WE_E_desired(j) evaluates to 0.14023742626431798, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.0015142073314830737, which exceeds 1e-4, where
V_WE_E(j) evaluates to -0.047125432157783698,
V_WE_E_desired(j) evaluates to -0.048639639489266771, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.00045928295339639491, which exceeds 1e-4, where
V_WE_E(j) evaluates to 0.014293886450927808,
V_WE_E_desired(j) evaluates to 0.014753169404324203, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.0047792679530480331, which exceeds 1e-4, where
V_WE_E(j) evaluates to -0.14874123444524651,
V_WE_E_desired(j) evaluates to -0.15352050239829454, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.0032966389645802813, which exceeds 1e-4, where
V_WE_E(j) evaluates to 0.1025985891427455,
V_WE_E_desired(j) evaluates to 0.10589522810732578, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.00058821906844488264, which exceeds 1e-4, where
V_WE_E(j) evaluates to -0.048051420420821889,
V_WE_E_desired(j) evaluates to -0.048639639489266771, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.00017841611604731134, which exceeds 1e-4, where
V_WE_E(j) evaluates to 0.014574753288276891,
V_WE_E_desired(j) evaluates to 0.014753169404324203, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.0018565862711180103, which exceeds 1e-4, where
V_WE_E(j) evaluates to -0.15166391612717653,
V_WE_E_desired(j) evaluates to -0.15352050239829454, and
1e-4 evaluates to 0.0001.
manipulation/planner/test/differential_inverse_kinematics_test.cc:154: Failure
The difference between V_WE_E(j) and V_WE_E_desired(j) is 0.0012806343361938533, which exceeds 1e-4, where
V_WE_E(j) evaluates to 0.10461459377113193,
V_WE_E_desired(j) evaluates to 0.10589522810732578, and
1e-4 evaluates to 0.0001.
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7980#-:-L4mTG-GncmjtLVkbR7o:b-b70js)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please

**Comment by soonho-tri** [comment]
@siyuanfeng-tri , please note that we still have a CI failure on mac. I've found that the following patch solves the problem:

```diff
--- a/manipulation/planner/test/differential_inverse_kinematics_test.cc
+++ b/manipulation/planner/test/differential_inverse_kinematics_test.cc
@@ -151,7 +151,7 @@ TEST_F(DifferentialInverseKinematicsTest, GainTest) {
     for (int j = 0; j < 6; j++) {
       // For the constrained dof, the velocity should match.
       if (gain_E(j) > 0) {
-        EXPECT_NEAR(V_WE_E(j), V_WE_E_desired(j), 1e-4);
+        EXPECT_NEAR(V_WE_E(j), V_WE_E_desired(j), 5e-3);
       }
     }
   }
```

I merged this PR to fix the Ubuntu CI. Could you check the above diff and open a separate PR?

**Pull request merged**
