### PR TITLE
pydrake/doc: Add new style, header, footer

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Preview available at: https://jwnimmer-tri.github.io/RobotLocomotion.github.io/pydrake/index.html

The css, images, header, and footer text were created by a TRI contractor that assigned all rights to TRI.  The only part I wrote myself was the sphinx and build system integration.

Relates #13832.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13983)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI are you available to feature review with high priority?

\CC @jamiesnape FYI

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13983)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13983)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @jamiesnape)

___
*[bindings/pydrake/doc/_static/css/custom.css, line 201 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13983#-MG9GOoD1nNsvUEfQLQb:-MHJ-6kSDswECYHhi7Co:bsuv0z5) ([raw file](https://github.com/robotlocomotion/drake/blob/6a05189aa6baa36b93e40a1a18771e261e487461/bindings/pydrake/doc/_static/css/custom.css#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

=> https://app.slack.com/client/T0JNB2DS4/C01879RNKQW/thread/C01879RNKQW-1598984546.010200
</blockquote></details>

Done (claimed).

**Comment by jwnimmer-tri** [comment]
@jamiesnape PTAL

**Review by jamiesnape — COMMENTED** [review]
I not 100% confident in this, at least in the way I was with the version in master now, but tracing through the most common cascades, I think we are ok, so :lgtm: 

> Reviewed 4 of 9 files at r1, 5 of 5 files at r3, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13983#-:-MIeg-Kr9ycZKC86bUhs:b-c6kgru)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/doc/_static/css/custom.css, line 201 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13983#-MG9GOoD1nNsvUEfQLQb:-MIeeuitESEpVjugGPRW:brw3jqo) ([raw file](https://github.com/robotlocomotion/drake/blob/6a05189aa6baa36b93e40a1a18771e261e487461/bindings/pydrake/doc/_static/css/custom.css#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done (claimed).
</blockquote></details>

Looks like the whole block needs removing actually. If you want to keep it, it would need to be `font-family: 'DejaVu Sans Mono' monospace;` What is here now does not make sense.
___
*[bindings/pydrake/doc/_static/css/custom.css, line 2 at r7](https://reviewable.io/reviews/robotlocomotion/drake/13983#-MIeeaJKDVsisOjUDY3h:-MIeeaJKDVsisOjUDY3i:b-dgmdoh) ([raw file](https://github.com/robotlocomotion/drake/blob/849fcb0c6f5fd42ab994d735a65c9b26eda963e5/bindings/pydrake/doc/_static/css/custom.css#L2)):*
> ```CSS
> /* s3://drake-web/fonts/stylesheet.css */
> @import url('https://dmn3132s4wr9m.cloudfront.net/fonts/stylesheet.css');
> ```

I think we still need this since we are still using DejaVu fonts.

**Comment by EricCousineau-TRI** [comment]
Just for the record, what's the next action item on this PR? (licensing, or something else?)

**Comment by jwnimmer-tri** [comment]
This is on "do not merge hold" because we don't want to change the pydrake style prior to changing the main site style.  Once the main site is close to ready, we'll finish this one up.

**Comment by EricCousineau-TRI** [comment]
The artifacts introduced here should be checked; if they are possibly derivatives of the original Jekyll website setup, we may want to purge them. Context:
https://github.com/RobotLocomotion/drake/issues/14575#issuecomment-772698920

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13983)* status: 3 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/doc/_static/css/custom.css, line 87 at r7](https://reviewable.io/reviews/robotlocomotion/drake/13983#-MShhYTA2wR6_B1Ss_hX:-MShhYTB2N58tMXlBd5W:b-hhm4d1) ([raw file](https://github.com/robotlocomotion/drake/blob/400e7312337d883d34c70d382e1b78134f5e5495/bindings/pydrake/doc/_static/css/custom.css#L87)):*
> ```CSS
> 
> *,
> *::before,
> ```

This appears to be derivative.

@jwnimmer-tri Can we close this PR and delete the branch?

**Comment by jwnimmer-tri** [comment]
Yup!

**Pull request closed without merging**
