### PR TITLE
Remove Core.h

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove Core.h.  The "include this file to include another group of files" is an anti-pattern.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2067)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm:

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2067#-:-KF7BQnNi-aMDNBdA89G:1417088721)*

**Comment by david-german-tri** [comment]
Out-of-date branch, no-conflict merge.  Merging.

**Comment by rpoyner-tri** [comment]
@david-german-tri @jwnimmer-tri  I claim the windows failures in jenkins #817 are just random flatulence and unrelated to my code. For reference, #811 built fine -- the code diffs are whitespace and one variable substitution of little practical effect.

FTR, I long ago disabled windows building of any of my code in this PR, and will be filing a separate issue to get that working sometime soon.

**Comment by rpoyner-tri** [comment]
sorry, wrong issue.

**Pull request merged**
