### PR TITLE
 [geometry] Fix gradient of signed distance between touching (zero distance) boxes

### LINKED ISSUE #21192: Error in query_object.ComputeSignedDistancePairClosestPoints
### What happened?

I've encountered a problem where calling `query_object.ComputeSignedDistancePairClosestPoints(geomA, geomB)` yields the error `Failure at geometry/proximity/distance_to_shape_touching.cc:73 in PointOnBoxSurfaceHelper(): condition 'n != Vector3d::Zero()' failed.`.

A standalone reproduction of this bug can be found in [this gist](https://gist.github.com/cohnt/f720c21caf07f7daf3313724e2db1676).

cc @DamrongGuoy 

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Fix #21192

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-:-NufP7C-AKyC2ffKlNPv:b-chsgxs)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review, please.

I'm not sure whether I added too much or too little.  Please let me know.  I tried to describe what we discussed yesterday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-:-NufQZd32DvOdfUGGSzR:bl725vp)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
OK full pass done. PTAL.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-:-Nuz2581Dx9jl95u0KwY:bnwmssu)* status: 6 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/distance_to_shape_touching.h` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuyzv1L33puJprvX1iq:-Nuyzv1L33puJprvX1ir:bb7lc5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/distance_to_shape_touching.h#L90)):*
> ```objc
> /* Returns the unit vector nhat_BA_W--out of box_B into box_A expressed in
>  World frame--parallel to a vector in `v_Ws` that can make a separating axis
>  between two touching boxes. If no vector in `v_Ws` can make it, returns null.
> ```

nit:



_Suggestion:_
```objc
returns std::nullopt
```
___
*[`geometry/proximity/distance_to_shape_touching.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz-MbUA4792Gd2afWc:-Nuz-MbUA4792Gd2afWd:bz9sl72) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/distance_to_shape_touching.cc#L68)):*
> ```cpp
>     // We don't want to classify a point near a vertex as being on a face
>     // because we use the face normal as the signed-distance gradient.
>     if (diff <= 0.01 * half_size(i)) {
> ```

I'm not totally convinced that a bias this large is necessary. Maybe a small multiple of `kEps` is sufficient (given the overlap bounds you stated below. Did you test without this large bias?
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 497 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz05oPEjymGVjmeCck:-Nuz05oPEjymGVjmeCcl:b-pbkr0e) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L497)):*
> ```cpp
> // Users provided data for this test case. See issue 21192. Visually the two
> // boxes touched along an edge, but numerically they overlapped within a very
> // small tolerance. Furthermore, the caller provided one of the witness points
> ```

Saying that they "visually" touched doesn't really say much. I would state very specifically the defect with the code that this case uncovered. Namely that FCL witness points made it past the check to see if the two boxes were "touching" but the gradient code failed to find a separating axis with the previous tolerances.



_Code quote:_
```cpp
// Users provided data for this test case. See issue 21192. Visually the two
// boxes touched along an edge, but numerically they overlapped within a very
// small tolerance. Furthermore, the caller provided one of the witness points
```
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 517 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz0alz9VNsVj3d5Bg6:-Nuz0alz9VNsVj3d5Bg7:b24h38v) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L517)):*
> ```cpp
>                        0.1384579999999353);
>   const Vector3d p_BCb(-0.066166999999969, 0.08869349999995851,
>                        -0.06870450000000002);
> ```

I know these magic numbers came from a reproducible example linked in the issue, but we don't track and maintain that temporary reproduction which makes this test pretty brittle. Would it too hard to come up with a case by hand that puts a box vertex `kEps` away from an edge that triggers the same defect? That would make this unit test much easier to maintain.



_Suggestion:_
```cpp
  const fcl::Boxd box_B(0.132334, 0.177387, 0.137409);
  const Vector3d half_size_B = box_B.side / 2;
  const RigidTransformd X_WA(
      RotationMatrixd(RollPitchYawd(-0.9999901072383376 * M_PI,
                                    -0.472887818233649 * M_PI,
                                    -0.5000099287557301 * M_PI)),
      Vector3d(-0.01554599999994518, 0.434174978106377, 0.6778455642817045));
  const RigidTransformd X_WB(
      RotationMatrixd(RollPitchYawd(0.5000049564737601 * M_PI,
                                    0.4301511633951143 * M_PI,
                                    0.5000038803050185 * M_PI)),
      Vector3d(-2.897114691894844e-17, 0.2298401771670561, 0.5144261282155572));
  const Vector3d p_ACa(-0.06799949999996824, 0.05315817907282317,
                       0.1384579999999353);
  const Vector3d p_BCb(-0.066166999999969, 0.08869349999995851,
                       -0.06870450000000002); 
```
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 547 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz1csA5vX7nIOFAFJQ:-Nuz1csA5vX7nIOFAFJR:b-gyng1y) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L547)):*
> ```cpp
>   // Confirm that our classifcation makes sense: p_ACa is classified on an edge,
>   // and p_BCb is classified on a vertex. (However, visually the two boxes
>   // touch along an edge.)
> ```

nit: again "visually" doesn't really say much in terms of testing this defect.



_Code quote:_
```cpp
  // and p_BCb is classified on a vertex. (However, visually the two boxes
  // touch along an edge.)
```
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 557 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz1rgM2ndjPWIOZVzl:-Nuz1rgM2ndjPWIOZVzm:b-k4oj1u) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L557)):*
> ```cpp
>   const Vector3d nhat_BA_W =
>       BoxBoxGradient(box_A, box_B, X_WA, X_WB, p_ACa, p_BCb);
>   EXPECT_TRUE(CompareMatrices(nhat_BA_W, Vector3d(0, -0.0850, 0.9963), 1e-4));
> ```

This normal comes from one of the "catch all" cases, correct? I think it would make the test much more robust to just compute the candidate normal directions here (as we do in the actual code) and then assert that the returned normal is in that set.



_Code quote:_
```cpp
  const Vector3d nhat_BA_W =
      BoxBoxGradient(box_A, box_B, X_WA, X_WB, p_ACa, p_BCb);
  EXPECT_TRUE(CompareMatrices(nhat_BA_W, Vector3d(0, -0.0850, 0.9963), 1e-4));
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266)* status: 5 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`geometry/proximity/distance_to_shape_touching.h` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuyzv1L33puJprvX1iq:-Nv4iZfbBYSts8ZXPWXW:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/distance_to_shape_touching.h#L90)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit:
</blockquote></details>

Done.
___
*[`geometry/proximity/distance_to_shape_touching.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz-MbUA4792Gd2afWc:-Nv4ia68A4UdCRwPbxEW:b-8oya23) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/distance_to_shape_touching.cc#L68)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I'm not totally convinced that a bias this large is necessary. Maybe a small multiple of `kEps` is sufficient (given the overlap bounds you stated below. Did you test without this large bias?
</blockquote></details>

I don't have a good answer.  I did change it to the multiple of `kEps` as you suggested.

 I also added documentation to explain why the problem was unstable, but I didn't have a good explanation for the selected threshold.

I might have to work more on this. Set to working.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266)* status: 4 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/proximity/distance_to_shape_touching.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz-MbUA4792Gd2afWc:-NviJm7c22BfeV1dMPd2:b-d90xwc) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/distance_to_shape_touching.cc#L68)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I don't have a good answer.  I did change it to the multiple of `kEps` as you suggested.

 I also added documentation to explain why the problem was unstable, but I didn't have a good explanation for the selected threshold.

I might have to work more on this. Set to working.
</blockquote></details>

Done.  I have created a unit test of what I said in the temporary documentation.  I hope it's good enough now.
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 497 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz05oPEjymGVjmeCck:-NviKClzEgwL57lLMXhA:berl62d) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L497)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Saying that they "visually" touched doesn't really say much. I would state very specifically the defect with the code that this case uncovered. Namely that FCL witness points made it past the check to see if the two boxes were "touching" but the gradient code failed to find a separating axis with the previous tolerances.
</blockquote></details>

Done.  I set up a simpler unit test explaining the previous defect that we found.
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 517 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz0alz9VNsVj3d5Bg6:-NviKMzNB55HVVRQhIFT:b-qv6zdk) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L517)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I know these magic numbers came from a reproducible example linked in the issue, but we don't track and maintain that temporary reproduction which makes this test pretty brittle. Would it too hard to come up with a case by hand that puts a box vertex `kEps` away from an edge that triggers the same defect? That would make this unit test much easier to maintain.
</blockquote></details>

Done.  I set up a simpler unit test that is easier to maintain.
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 547 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz1csA5vX7nIOFAFJQ:-NviKPjl8h0A-h0vvPc_:bawaej7) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L547)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: again "visually" doesn't really say much in terms of testing this defect.
</blockquote></details>

Done.  I removed it in the new unit test.
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 557 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz1rgM2ndjPWIOZVzl:-NviKWA-4l60GuZO4Qco:bo3tsot) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L557)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

This normal comes from one of the "catch all" cases, correct? I think it would make the test much more robust to just compute the candidate normal directions here (as we do in the actual code) and then assert that the returned normal is in that set.
</blockquote></details>

Done.  In the new unit test, I explained that the "catch all" cases searched all 15 directions and picked the first one.  I hope it's acceptable.

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: Thanks for the fixup, Damrong. +@EricCousineau-TRI for platform review, please.

> Reviewed 2 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-:-NvmS3cSDhjo7WKmroP5:b-hfltk8)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`geometry/proximity/distance_to_shape_touching.h` line 72 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-NvmEKEABpQgdUtXm-5e:-NvmEKEABpQgdUtXm-5f:b98hwfv) ([raw file](https://github.com/RobotLocomotion/drake/blob/da0518087b483545038c486b896ff11d81a01e35/geometry/proximity/distance_to_shape_touching.h#L72)):*
> ```objc
>  vertex(3), or it's not on the surface (0).
> 
>  @note Since we use an internal tolerance, the classification of location
> ```

nit grammar



_Suggestion:_
```objc
of the location
```
___
*[`geometry/proximity/distance_to_shape_touching.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz-MbUA4792Gd2afWc:-NvmRADlEPB0OoysI8v6:b-vs1pr4) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/distance_to_shape_touching.cc#L68)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  I have created a unit test of what I said in the temporary documentation.  I hope it's good enough now.
</blockquote></details>

Looks good.
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 517 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz0alz9VNsVj3d5Bg6:-NvmRTwV5hhste67QTNA:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L517)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  I set up a simpler unit test that is easier to maintain.
</blockquote></details>

Thanks!
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 557 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-Nuz1rgM2ndjPWIOZVzl:-NvmRnrx3V2RWE20f2yz:b-8h3hw8) ([raw file](https://github.com/RobotLocomotion/drake/blob/5c4ef4225035090b778aeef83717e95b71b261bf/geometry/proximity/test/distance_to_shape_touching_test.cc#L557)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  In the new unit test, I explained that the "catch all" cases searched all 15 directions and picked the first one.  I hope it's acceptable.
</blockquote></details>

Yes this is now a nice and self contained unit test. Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with tiny nits

> Reviewed 1 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-:-NvmXNLsAnNX4P6gBKYJ:b-2zf3wt)* status: 3 unresolved discussions

___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 173 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-NvmWvHtA6Beqe9S2_Gb:-NvmWvHtA6Beqe9S2_Gc:b-ef4j7m) ([raw file](https://github.com/RobotLocomotion/drake/blob/da0518087b483545038c486b896ff11d81a01e35/geometry/proximity/test/distance_to_shape_touching_test.cc#L173)):*
> ```cpp
>     // The noise 1e-14 is less than the internal tolerance of
>     // PointOnBoxSurfaceHelper().
>     const Vector3d p_BQ(0.125 - 1e-14, 0.125 - 1e-14, 0.125 - 1e-14);
> ```

nit Consider placing `1e-14` and `1e-13` into constants, e.g. `kEps` and `kNoise`?
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 178 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-NvmX16y9xglt7FxUmXL:-NvmX16y9xglt7FxUmXM:bbfns6p) ([raw file](https://github.com/RobotLocomotion/drake/blob/da0518087b483545038c486b896ff11d81a01e35/geometry/proximity/test/distance_to_shape_touching_test.cc#L178)):*
> ```cpp
>   {
>     // However, the noise 1e-13 is larger than the internal tolerance and
>     // triggers wrong classification in various ways.
> ```

nit Given that we have tolerances and noise, I'm not sure if I understand what "wrong" means here.

Consider clarifying "unexpected, but correct given the tolerances we've chosen" ?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

___
*[`geometry/proximity/distance_to_shape_touching.h` line 72 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-NvmEKEABpQgdUtXm-5e:-Nvn3-rv-wuP5wBdz2VU:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/da0518087b483545038c486b896ff11d81a01e35/geometry/proximity/distance_to_shape_touching.h#L72)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit grammar
</blockquote></details>

Done
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 173 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-NvmWvHtA6Beqe9S2_Gb:-Nvn543E1O5xHkimZisR:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/da0518087b483545038c486b896ff11d81a01e35/geometry/proximity/test/distance_to_shape_touching_test.cc#L173)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider placing `1e-14` and `1e-13` into constants, e.g. `kEps` and `kNoise`?
</blockquote></details>

Done. Thanks.
___
*[`geometry/proximity/test/distance_to_shape_touching_test.cc` line 178 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21266#-NvmX16y9xglt7FxUmXL:-Nvn5OGMCoQQngz_qAvI:b-82smw2) ([raw file](https://github.com/RobotLocomotion/drake/blob/da0518087b483545038c486b896ff11d81a01e35/geometry/proximity/test/distance_to_shape_touching_test.cc#L178)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Given that we have tolerances and noise, I'm not sure if I understand what "wrong" means here.

Consider clarifying "unexpected, but correct given the tolerances we've chosen" ?
</blockquote></details>

Done. Thanks for rewording.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21266)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn

**Pull request merged**
