### PR TITLE
Added two ramp tracks to the Cars example, and adjusted prius model spring stiffness

### PR DESCRIPTION
**Pull request by crogers3**

### CODE REVIEW

**Comment by RussTedrake** [comment]
these changes all look good.  we probably only need one of the two urdfs (probably jumping over the cars looks cooler).  would also like to see the video added to gallery.html

**Comment by crogers3** [comment]
I removed the canyon jump course, uploaded the videos of the prius jumping over other priuses to the RobotLocomotionGroup YouTube channel, and linked to it in the gallery.

**Comment by RussTedrake** [comment]
looks like we probably need to handle the "completely static urdf" case in the compareParsers test.  @crogers3 -- do you mind?

**Comment by crogers3** [comment]
Sure, I can take a crack at it. What exactly do I need to do? Do I need to
add some kind of check into the unit test, that bypasses the random state
and velocity calculation part?

Christopher Rogers

**Comment by RussTedrake** [comment]
that unit test crawls all of the urdf files, then skips a few which are unsupported for various reasons.  yours is unsupported because it has zero DOF.  if that case is not handled yet, then it probably should be.

**Comment by crogers3** [comment]
I added a check in the unit test that checks if r.getNumPositions == 0, and if so, skips that urdf. Is that along the lines of what you are thinking to do?

**Comment by RussTedrake** [comment]
yes, perfect.

**Pull request merged**
