### PR TITLE
Zap orphaned and unused MATLAB-related C++ and Java

### LINKED ISSUE #3982: Move matlab jar build logic into drake/matlab subdirectory
There is some logic in `drake-distro/drake/CMakeLists.txt` that is matlab-specific, and thus should be moved into `drake-distro/drake/matlab/CMakeLists.txt`.

Roughly these bits...
```
set(drake_jar_javafiles matlab/util/Transform.java)
set(drake_jar_requires)
...
  list(APPEND drake_jar_javafiles
    matlab/util/MyLCMTypeDatabase.java
    matlab/util/MessageMonitor.java
    matlab/util/CoordinateFrameData.java
    matlab/util/LCMCoder.java)
  list(APPEND drake_jar_requires lcm-java lcmtypes_drake-java)

  # add lcmgl
  ... (whole chunk of lcmgl java goop to be moved) ...

add_jar(drake SOURCES ${drake_jar_javafiles} INCLUDE_JARS ${drake_jar_requires})
install_jar(drake share/java)
pods_install_pkg_config_file(drake-java
  CLASSPATH drake
  REQUIRES ${drake_jar_requires}
  VERSION 0.0.1)
```

The test case is to checkout drake, `rm -rf drake-distro/drake/matlab`, and then run the superbuild and ensure it passes (along with its tests).

### LINKED ISSUE #6517: Orphaned MATLAB-related C/C++ and Java files
The following are unused and not included in any build files, whether Bazel or CMake:

C/C++:

* [LCMScope.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/LCMScope.h)
* [makeFunction.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/makeFunction.h)
* [mexify.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/mexify.h)
* [standardMexConversions.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/standardMexConversions.h)

Java:

* [BotLCMGLClient.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/BotLCMGLClient.java)
* [CoordinateFrameData.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/CoordinateFrameData.java)
* [MyLCMTypeDatabase.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/MyLCMTypeDatabase.java)
* [LCMCoder.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/LCMCoder.java)
* [MessageMonitor.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/MessageMonitor.java)
* [Transform.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/Transform.java)

Should they be compiled into something or removed?

_Edited to add (jwnimmer-tri): Relates #6369_.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #3982, closes #6517.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6611)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review. FYI @RussTedrake.

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@soonho-tri for platform review on-call, please.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6611#-:-KpWH7ZTHEzoQT1M0CYv:b-ipk9dc)*

**Comment by soonho-tri** [comment]
@jamiesnape , could you check the CI failures?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6611#-:-KpWHYSVFWPsRjF4E68w:b-eac5kd)*

**Comment by jwnimmer-tri** [comment]
Possibly also closes #3982 now?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6611#-:-KpWKtipNOcB7S8Fnhz4:b-uttri0)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6611)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6611)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6611#-:-KpWTkg2NqKkeBudtJvo:bnfp4nl)*

**Pull request merged**
