### PR TITLE
workspace: Upgrade libsdformat to latest release 13.0.0

### LINKED ISSUE #17873: Should upgrade to libsdformat13
Not going to be released til end of month, but would be nice to get out in front of it.

Per VC, this came in (yay)! https://github.com/gazebosim/sdformat/pull/1112
Affected code:
https://github.com/RobotLocomotion/drake/blob/a2caba14526d6d3e8b0a8e783eb7d55ed303f813/multibody/parsing/detail_sdf_parser.cc#L548-L562

There also may be name remapping for `ign*` to `gz*` for things like math components.

### LINKED ISSUE #17907: gz_math_internal needs update to latest
gz_math_internal needs to be updated to the latest release. It appears that a number of headers (and possible other files) have moved, making Bazel unhappy, and the changes are sufficiently non-trivial as to require sorting out on an individual file level (i.e. some things have changed and some apparently haven't, and someone needs to go through the files one at a time to identify which is which).

### PR DESCRIPTION
**Pull request by scpeters**
Closes #17873.
Closes #17907.

## Note: this is in draft form until the 13.0.0 stable release

Notable changes from libsdformat 12.5.0 that are relevant to Drake:

## New Features

* Default spec version is now 1.10
* Dependency on gz-math6 updated to gz-math7
* Dependency on gz-utils1 updated to gz-utils2
* Name migration from ignition -> gz reflected in header files (`gz/math/Vector3.hh`) and c++ namespaces (`gz::math::Vector3d`)
* Python bindings
* Warn by default on unrecognized elements
* Limit floating point truncation

## Bug fixes

* Better default joint limits (`-inf,inf` instead of `-1e16, 1e16`)
* Don't include the gz/math.hh header from library code (currently patched in `1043.patch`)

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I'll tell reviewable that this is +(status: do not merge) until it's pointing to the official release tag(s).  (The "Draft" mode already enforces this, but the label is a bit more direct.)

**Comment by jwnimmer-tri** [comment]
@scpeters would you like anyone to do a code review skim on this yet for any feedback, or rather wait until it's more finalized first?

**Comment by scpeters** [comment]
> @scpeters would you like anyone to do a code review skim on this yet for any feedback, or rather wait until it's more finalized first?

I don't anticipate major changes in the upstream code before its stable release, just a change in tag name and sha256, so I think this is ready for a first round of code review.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

> Reviewed 13 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-NC1S7Ss7lnRkQxdwXBq:bgm2fo4)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @scpeters)

___
*[`multibody/parsing/detail_ignition.cc` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1RQUO9WqysY2gbFyI:-NC1RQUO9WqysY2gbFyJ:bpn3pcl) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/multibody/parsing/detail_ignition.cc#L24)):*
> ```cpp
>   return gz::math::Pose3d(
>       gz::math::Vector3d(pose.translation().x(), pose.translation().y(),
>                                pose.translation().z()),
> ```

nit This needs a small alignment fixup to track the shorter namespace.



_Suggestion:_
```cpp
      gz::math::Vector3d(pose.translation().x(), pose.translation().y(),
                         pose.translation().z()),
```
___
*[`multibody/parsing/detail_sdf_parser.cc` line 558 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1S-OC93ewIotLrVas:-NC1S-OC93ewIotLrVat:bcvz2di) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/multibody/parsing/detail_sdf_parser.cc#L558)):*
> ```cpp
>   // only returns non-negative values.
>   const double velocity_limit = axis->MaxVelocity();
>   if (velocity_limit < 0) {
> ```

Given the above comment change, this check seems like it might be dead code now?
___
*[`tools/workspace/gz_utils_internal/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1PutsBPpCpAhvQfRN:-NC1PutsBPpCpAhvQfRO:bwxrpob) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/tools/workspace/gz_utils_internal/package.BUILD.bazel#L58)):*
> ```
>     "include/gz/utils/detail/ImplPtr.hh",
>     "include/gz/utils/detail/SuppressWarning.hh",
>     "include/ignition/utils/Environment.hh",
> ```

I haven't carefully looked at the transition details for these paths and namespaces, but if it's the case that Drake should only ever be using the new "gz" include paths throughout our code, and that all of these externals libraries (gz utils, gz math, sdformat) consistently use the new "gz" paths as well when referring to each other, then it would be an improvement here and throughout this PR to _enforce_ that the legacy "ignition" paths are never used by dropping the "ignition" headers from this list and adding them to the `glob_exclude` below for the consistency check.  That would also probably simplify the "replace" logic below to only require the one case.
___
*[`tools/workspace/sdformat_internal/gz_sdf_main.cc` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1PCXlE9aAPoQdaNtw:-NC1PCXlE9aAPoQdaNtx:borvz0a) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/tools/workspace/sdformat_internal/gz_sdf_main.cc#L2)):*
> ```cpp
> /*
> Provides a C++ version libsdformat's `ign sdf` ruby command-line interface.
> ```

nit Is this comment still accurate?



_Suggestion:_
```cpp
gz sdf
```

**Review by scpeters — COMMENTED** [review]
I've pushed changes in individual commits. I'll plan to squash and rebase when I update after the stable release unless I hear otherwise.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-NC7q74XEdnqhbPh03C6:brketpe)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/detail_ignition.cc` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1RQUO9WqysY2gbFyI:-NC7p2yB92zQUI9JBbf3:bhthk7g) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/multibody/parsing/detail_ignition.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This needs a small alignment fixup to track the shorter namespace.
</blockquote></details>

Done in d91b873
___
*[`multibody/parsing/detail_sdf_parser.cc` line 558 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1S-OC93ewIotLrVas:-NC7pHy18yxn0j3N9nbu:b7k7ox3) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/multibody/parsing/detail_sdf_parser.cc#L558)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given the above comment change, this check seems like it might be dead code now?
</blockquote></details>

Yes, I agree. I've removed it in e23c161
___
*[`tools/workspace/gz_utils_internal/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1PutsBPpCpAhvQfRN:-NC7pj3t2YbNrUhQs9hh:biz7ilh) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/tools/workspace/gz_utils_internal/package.BUILD.bazel#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I haven't carefully looked at the transition details for these paths and namespaces, but if it's the case that Drake should only ever be using the new "gz" include paths throughout our code, and that all of these externals libraries (gz utils, gz math, sdformat) consistently use the new "gz" paths as well when referring to each other, then it would be an improvement here and throughout this PR to _enforce_ that the legacy "ignition" paths are never used by dropping the "ignition" headers from this list and adding them to the `glob_exclude` below for the consistency check.  That would also probably simplify the "replace" logic below to only require the one case.
</blockquote></details>

Done. That's a good idea. I've excluded the `ignition/*` headers from math and utils as you suggested in ef5bbb7.
___
*[`tools/workspace/sdformat_internal/gz_sdf_main.cc` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17913#-NC1PCXlE9aAPoQdaNtw:-NC7pc-m84stCZiKPxth:bhqb7nn) ([raw file](https://github.com/robotlocomotion/drake/blob/19ec7a48b9225838b385221456a59fd05a5fcd41/tools/workspace/sdformat_internal/gz_sdf_main.cc#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Is this comment still accurate?
</blockquote></details>

Done. Fixed in f4e32cf

**Review by jwnimmer-tri — COMMENTED** [review]
Sure.  Squashing down to a single commit is fine, anytime.  We'd do that upon final merge in any case.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-NC85qXq7qPXSIwNEOiE:basm7i7)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by scpeters — COMMENTED** [review]
I've squashed the commits responding to the previous review comments, and since the stable releases have been made, I've updated to point to the stable tags and marked this as ready for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-ND-7ZCN833woMIrPgFa:botjmvf)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I'll do a final review pass shortly.

To be clear, when this goes into Drake we'll squash down into a single commit, not four.  (When merging multiple commits to master, we require that all intermediate commits pass CI, and I don't think these would.)

**Comment by scpeters** [comment]
> To be clear, when this goes into Drake we'll squash down into a single commit, not four. (When merging multiple commits to master, we require that all intermediate commits pass CI, and I don't think these would.)

that makes sense, I think this should result in just a single commit on master; I just wanted to split changes into separate commits in the pull request in case it makes it easier to review

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: from me.

Let's have +@sherm1 (on call) for extra review of **only** one file -- the `detail_sdf_parser.cc` logic changes.  Sherm -- everything else here is just boilerplate renames and such.  Please check that the new limit handling in the parser makes sense to you.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-ND3Vkpy6a2nyrmk9bgl:b-hp7o1r)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Thanks, Steve! Platform :lgtm: (for `detail_sdf_parser.cc` only) with a few minor comments.

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-ND3uF-wBODLrUGVBoXK:b-kl8uao)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @scpeters)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 144 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17913#-ND3sFaF6ITH5vvO5YRX:-ND3sFaF6ITH5vvO5YRY:b-v0d6mx) ([raw file](https://github.com/robotlocomotion/drake/blob/3dd7512c4b52ea685850b15cc431687e3717fa56/multibody/parsing/detail_sdf_parser.cc#L144)):*
> ```cpp
> }
> 
> // Given an gz::math::Inertial object, extract a RotationalInertia object
> ```

nit: ~an~ gz -> a gz
___
*[`multibody/parsing/detail_sdf_parser.cc` line 554 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17913#-ND3tF6fDkWkjCFNjNgq:-ND3tF6fDkWkjCFNjNgr:bal46yl) ([raw file](https://github.com/robotlocomotion/drake/blob/3dd7512c4b52ea685850b15cc431687e3717fa56/multibody/parsing/detail_sdf_parser.cc#L554)):*
> ```cpp
> 
>   const double lower_limit = axis->Lower();
>   const double upper_limit = axis->Upper();
> ```

minor: I assume this change is possible because SDFormat now uses ±∞ for no limits? Please add a comment to that effect if so.

**Review by scpeters — COMMENTED** [review]
thanks! I've pushed fixes and replied to your comments

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913#-:-ND5GRB4ASi0MVieCp1d:b9mki16)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 144 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17913#-ND3sFaF6ITH5vvO5YRX:-ND5GI9c92Sg4SCQkuJ5:bsi9ekg) ([raw file](https://github.com/robotlocomotion/drake/blob/3dd7512c4b52ea685850b15cc431687e3717fa56/multibody/parsing/detail_sdf_parser.cc#L144)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: ~an~ gz -> a gz
</blockquote></details>

nice catch; I found a few more and fixed them in d94448e6c05999aeb4a3bb98bfd11227e83f9aaa
___
*[`multibody/parsing/detail_sdf_parser.cc` line 554 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17913#-ND3tF6fDkWkjCFNjNgq:-ND5GNxu4bjTrk_Ycw28:bkz6siu) ([raw file](https://github.com/robotlocomotion/drake/blob/3dd7512c4b52ea685850b15cc431687e3717fa56/multibody/parsing/detail_sdf_parser.cc#L554)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I assume this change is possible because SDFormat now uses ±∞ for no limits? Please add a comment to that effect if so.
</blockquote></details>

that is correct. I've added a comment to that effect in 953248ed6b662592cbbcf58ad0633b44dd7ac341

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17913)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
