### PR TITLE
cassie_bench: Catch up on audodiff allocation improvements

### PR DESCRIPTION
**Pull request by rpoyner-tri**
These gains resulted from @sherm1's PR #13962 but went unclaimed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14115)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for both reviews.
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14115#-:-MHw6yxK7RRdsLq9t64D:bp4lnkq)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not merge) need to check the numbers again

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14115#-:-MHwUo0M018NSeJpm6m9:b-jn565b)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge" (waiting on @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not merge) numeric typo fixed

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14115#-:-MHwVVDe0epD2W1Dm19B:b-sc6wuo)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge" (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
FYI Typo in commit message and PR overview "13962".

**Review by rpoyner-tri — COMMENTED** [review]
Thanks! big day for dyslexia, apparently :)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14115#-:-MHwWHDR2o2QlvThg7qY:b-tvbfxm)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 pending CI

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14115#-:-MHwXcFHB5JpbPfmZdam:b-93ytbg)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
