### PR TITLE
Mesh now pays attention to its scale parameter

### PR DESCRIPTION
**Pull request by gizatt**
`urdf_parser` and `sdf_parser` set the `scale_` parameter of loaded `Mesh` geometry, but that parameter is ignored, as far as I can tell, after that point. This PR tweaks the `Mesh` class to consider its `scale_` when providing information about its own geometry, and provides a very simple test to verify that it operates correctly.

I'm aware that it's bad style for `scale_` to be public, but as it's among many other style inconsistencies in the Geometry code, I'm hoping y'all will let me get away with keeping this PR simple by not trying to fix those problems.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5458)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
:LGTM: You're certainly not adding any style-breaking code.  And this all seems reasonable.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keor4WVepT91KjMYSn9:-Keor4WVepT91KjMYSnA:b-an1bre) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L13)):*
> ```cpp
> 
> // Loads an origin-centered 2x2x2 cube from an .obj file,
> // and applies different scaling in the x, y, and z axes, and
> ```

remove "and"

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keor91krO0ANVS1Q5B9:-Keor91lOk3sEowYrUEC:bbpzja4) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L14)):*
> ```cpp
> // Loads an origin-centered 2x2x2 cube from an .obj file,
> // and applies different scaling in the x, y, and z axes, and
> // checks that resulting vertex coordinates are correspondingly
> ```

BTW "...checks that *the* resulting vertex coordinates are correctly scaled."

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeoqqyivEocBLgfzERK:-KeoqqyjDRLSCVJr_99d:b-38hpaf) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L28)):*
BTW This comment could be clearer, e.g.:

> Calling getPoints() causes the file to be parsed to populate the vertex data.

Otherwise, it isn't immediately apparent how the scale factor affects the data (after all, you set the scale *after* you constructed it with a file name.)

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeorevZTxvXjRGtQjbo:-Keorev_qX0jwTFT2vvN:b83i819) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L34)):*
> ```cpp
>   // Because this cube is centered on the origin,
>   // and has side length 2, the vertices will be
>   // symmetrically arranged around the origin at at
> ```

typo "at at"

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeorlTmOnU2JTrhYIMa:-KeorlTmOnU2JTrhYIMb:b1qbd10) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L35)):*
> ```cpp
>   // and has side length 2, the vertices will be
>   // symmetrically arranged around the origin at at
>   // distances along each axis equal to the scaling
> ```

Suggested change: "...equal to the scale factor along that axis."

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeoqDDZceSVHT30qbf-:-KeoqDDZceSVHT30qbf0:b-2mu3gm) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L45)):*
> ```cpp
>   // purposes to test gross scaling behavior.
>   for (int i=0; i < verts.cols(); i++) {
>     EXPECT_NEAR(fabs(verts(0, i)), 2.0, 0.01);
> ```

As the creator of the tri-cube file, I'll go ahead and state that the representation noise in this file is *not* meaningful.  I'd ask that you go ahead and clean them up into real 1s and zeros and then change your test to exact values (and, in the meantime, I'll make a voodoo doll of the Blender obj export authors.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-:-KeowpS7x9pehmwJC3ib:b5vcnn4)*

**Comment by gizatt** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keor4WVepT91KjMYSn9:-Kep0egckhkP2mh5l0VD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L13)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

remove "and"
</blockquote></details>

Done.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keor91krO0ANVS1Q5B9:-Kep0h3fLwxYeVNYZfFm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L14)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "...checks that *the* resulting vertex coordinates are correctly scaled."
</blockquote></details>

Done.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeoqqyivEocBLgfzERK:-Kep0wn9YzFjlWBRgEcz:b-fohimr) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L28)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This comment could be clearer, e.g.:

> Calling getPoints() causes the file to be parsed to populate the vertex data.

Otherwise, it isn't immediately apparent how the scale factor affects the data (after all, you set the scale *after* you constructed it with a file name.)
</blockquote></details>

Good point -- done!

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeorevZTxvXjRGtQjbo:-Kep0zT7qjBY1vmO8xyT:bjmexho) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

typo "at at"
</blockquote></details>

Done. #MarsAttacks

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeorlTmOnU2JTrhYIMa:-Kep0yrpyFN4IxtacAXv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L35)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Suggested change: "...equal to the scale factor along that axis."
</blockquote></details>

Done.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeoqDDZceSVHT30qbf-:-Kep1ZnWgqRGJzluiyar:byyq9rg) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

As the creator of the tri-cube file, I'll go ahead and state that the representation noise in this file is *not* meaningful.  I'd ask that you go ahead and clean them up into real 1s and zeros and then change your test to exact values (and, in the meantime, I'll make a voodoo doll of the Blender obj export authors.)
</blockquote></details>

Ha, I see! That's pretty incredibly bad. Manually fixed the random 0.99999s and switched this back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458)*

**Comment by SeanCurtis-TRI** [comment]
It's always asymptotic progress, isn't it?  One thing slipped through the cracks, and some typos in the new stuff.  PTAL

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keor91krO0ANVS1Q5B9:-KesoVDvBm0mYOyIVMT0:b-oq274p) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L14)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I probably should have emphasized *both* changes in my quote.  In this case, "correspondingly" doesn't scan; there's nothing in the sentence to indicate what the correspondence is.  So, I'd suggested "correctly" scaled.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KeorevZTxvXjRGtQjbo:-KesoywEN69pcfzqtaAK:bxc9md1) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L34)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done. #MarsAttacks
</blockquote></details>

BTW I assumed the Empire was attacking, heading to the shield generator.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KesonH_HtQZxuMERnkU:-KesonH_HtQZxuMERnkV:b-cyacwz) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf39ed180d83e3168707aa02d350013223e997d/drake/multibody/shapes/test/mesh_scaling_test.cc#L29)):*
> ```cpp
> 
>   // Calling getPoints() causes the mesh file the be parsed to populate
>   // the vertex data, so vertices extracted will this call will
> ```

BTW Two things. "...data. So, vertices..."  (new sentence) and
"...extracted *by* this call will..." (replace incorrect "will" with "by")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-:-KespN-0UxmVMBQU4Jv7:beo5ih9)*

**Comment by gizatt** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keor91krO0ANVS1Q5B9:-Ket9dw5mH4LzhqHoqBY:bmfpuqf) ([raw file](https://github.com/robotlocomotion/drake/blob/de89b054abef592da48413bf83e479a2098ed0d9/drake/multibody/shapes/test/mesh_scaling_test.cc#L14)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I probably should have emphasized *both* changes in my quote.  In this case, "correspondingly" doesn't scan; there's nothing in the sentence to indicate what the correspondence is.  So, I'd suggested "correctly" scaled.
</blockquote></details>

I'd argue that "correspondingly" points back to "different scaling in the x, y, z axes" but it's definitely a stretch. This is much better. Thanks!

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KesonH_HtQZxuMERnkU:-KetBYcy2bwjHdKgCfJZ:buaq8nj) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf39ed180d83e3168707aa02d350013223e997d/drake/multibody/shapes/test/mesh_scaling_test.cc#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Two things. "...data. So, vertices..."  (new sentence) and
"...extracted *by* this call will..." (replace incorrect "will" with "by")
</blockquote></details>

Done. And caught another typo ("the be parsed")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458)*

**Comment by SeanCurtis-TRI** [comment]
Go ahead and foist this off on platform review.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-KesonH_HtQZxuMERnkU:-KetJKqEm0TNMF3zVmuA:b-wgpsnb) ([raw file](https://github.com/robotlocomotion/drake/blob/2bf39ed180d83e3168707aa02d350013223e997d/drake/multibody/shapes/test/mesh_scaling_test.cc#L29)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done. And caught another typo ("the be parsed")
</blockquote></details>

Well spotted.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-:-KetJO-cdLV475fZkFaM:bdyxhht)*

**Comment by gizatt** [comment]
Thanks! +@ggould-tri, could you help with platform review?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-:-KetSGLLRji9752n-Ipq:bojb7dz)*

**Comment by ggould-tri** [comment]
+(status: curate commits before merging) 

On `Mesh.scale_` I'm willing to accept your TODO as a temporary accommodation given the general standards-and-practices disaster that is `geometry.h`.  I do suggest doing a ~10 line PR to add the methods if you have the time -- you can assign it to me as single reviewer and we can blast it through quickly.

:lgtm: pending notes below.

---

Reviewed 3 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keu7Ycukgpdb7StVW8H:-Keu7YcvY2VQSGKga8cl:bg2xl84) ([raw file](https://github.com/robotlocomotion/drake/blob/af8dd5ecea03137539801c9ae10dc41a69321bbb/drake/multibody/shapes/test/mesh_scaling_test.cc#L39)):*
> ```cpp
>   // distances along each axis equal to the scale factor
>   // along that axis.
>   for (int i=0; i < verts.cols(); i++) {
> ```

Style guide prefers spaces around the `=` https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keu7c6sskyEJwg5aYTc:-Keu7c6tR9lFx-3AVCqs:bg2xl84) ([raw file](https://github.com/robotlocomotion/drake/blob/af8dd5ecea03137539801c9ae10dc41a69321bbb/drake/multibody/shapes/test/mesh_scaling_test.cc#L53)):*
> ```cpp
>   // As above, given our scaling, we confirm that vertices
>   // have been scaled in the appropriate directions.
>   for (size_t i=0; i < vertices.size(); i++) {
> ```

Style guide prefers spaces around the `=` https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-:-Keu2KpYvkPYxyClitKY:bowhcax)*

**Comment by gizatt** [comment]
Thanks! I'll see about getting that in. Making the complete will require some mods of the places that access `Mesh.scale_`, which is a big part of why I punted this time around. 

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keu7Ycukgpdb7StVW8H:-KeuNlks6FWssW2x9cDL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af8dd5ecea03137539801c9ae10dc41a69321bbb/drake/multibody/shapes/test/mesh_scaling_test.cc#L39)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Style guide prefers spaces around the `=` https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
</blockquote></details>

Done.

---

*[drake/multibody/shapes/test/mesh_scaling_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-Keu7c6sskyEJwg5aYTc:-KeuNmMszkLFX5BMvQOG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af8dd5ecea03137539801c9ae10dc41a69321bbb/drake/multibody/shapes/test/mesh_scaling_test.cc#L53)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Style guide prefers spaces around the `=` https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458#-:-KeuQuSPgR7rJiGYT7mD:b-a2cmma)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5458)*

**Pull request merged**
