### PR TITLE
Iris from clique cover

### PR DESCRIPTION
**Pull request by RussTedrake**
@calderpg-tri -- FYI, this is my first c++ draft of the "full algorithm" that I discussed.  It's the main initial motivation for #19914.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20013)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[`planning/iris_clique_cover.cc` line 194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20013#-Nc7nu3q7JvclhW-ASWe:-Nc7nu3rDkSGwlcgdukJ:bjnc6f9) ([raw file](https://github.com/RobotLocomotion/drake/blob/56009e9ee7947a4e535ad7fd2caba0cbfcb602c3/planning/iris_clique_cover.cc#L194)):*
> ```cpp
> #if defined(_OPENMP)
> #pragma omp parallel for num_threads(num_threads_to_use)
> #endif
> ```

@calderpg-tri -- could you take a quick look at the threading i'm doing here (and above)?  My understanding is that the UpdatePositions is viable for this implicit context parallelism, but a student saw some multithreading issues when calling this from python.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20013)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

___
*[`planning/iris_clique_cover.cc` line 194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20013#-Nc7nu3q7JvclhW-ASWe:-NcNtVc_0HGW0KNq9pnv:bvhgptm) ([raw file](https://github.com/RobotLocomotion/drake/blob/56009e9ee7947a4e535ad7fd2caba0cbfcb602c3/planning/iris_clique_cover.cc#L194)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@calderpg-tri -- could you take a quick look at the threading i'm doing here (and above)?  My understanding is that the UpdatePositions is viable for this implicit context parallelism, but a student saw some multithreading issues when calling this from python.
</blockquote></details>

The parallel code here looks OK. A couple things for them to check:
- make sure they are using a default-constructed `SceneGraphCollisionChecker` or have constructed one with a `DistanceAndInterpolationProvider`
- have they added any additional logging, and if so, is it redirected through python? To be safe they can turn off logging redirection entirely via function or environment variable.
___
*[`planning/iris_regions_from_clique_cover.cc` line 108 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20013#-NcNZ46gAS4s0eEIDxL5:-NcNZ46gAS4s0eEIDxL6:bd54uqa) ([raw file](https://github.com/RobotLocomotion/drake/blob/c66b293d842e5492e5b3d36dd70100df33af0049/planning/iris_regions_from_clique_cover.cc#L108)):*
> ```cpp
> 
>   // Remove points in collision.
>   int num_points = 0;
> ```

This should be `std::atomic<int> num_points{0}` and the `++num_points` should be `num_points.fetch_add(1)`
___
*[`planning/iris_regions_from_clique_cover.cc` line 213 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20013#-NcNv9fCDO1unNZa1HDe:-NcNv9fCDO1unNZa1HDf:bxkj4m6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c66b293d842e5492e5b3d36dd70100df33af0049/planning/iris_regions_from_clique_cover.cc#L213)):*
> ```cpp
>     o.starting_ellipse = starting_ellipse[i];
>     o.iteration_limit = 1;
>     regions[i] = IrisInConfigurationSpace(
> ```

While this appears to work now, this is the wrong approach. #18830 is necessary to do this properly; "raw" SG operations on a collision checker context simply aren't the same behavior that the collision checker itself provides. At best, the only case in which equivalence can currently be expected is when using SGCC with no padding. Using any padding or any other collision checker implementation will lead to significantly different behavior.

For the time being, this could be written as
```
std::vector<HPolyhedron> IrisRegionsFromCliqueCover(
    const SceneGraphCollisionChecker& checker,
    const Eigen::Ref<const Eigen::MatrixXd>& original_points,
    const IrisOptions& options, const int minimum_clique_size, const bool parallelize) {
  const auto maybe_env_padding = checker.MaybeGetUniformRobotEnvironmentPadding();
  const auto maybe_self_padding = checker.MaybeGetUniformRobotRobotPadding();
  if (!maybe_env_padding || maybe_env_padding.value() > 0.0) {
    throw std::runtime_error("SGCC does not have uniform zero robot-environment padding, SGCC operations and IRIS region generation will disagree");
  }
  if (!maybe_self_padding || maybe_self_padding.value() > 0.0) {
    throw std::runtime_error("SGCC does not have uniform zero robot-robot padding, SGCC operations and IRIS region generation will disagree");
  }
  ...
```

**Comment by jwnimmer-tri** [comment]
Adding +(status: do not review) so platform reviewers know this is already under control.

**Comment by RussTedrake** [comment]
Closing for now, as this has stalled.  Will open again soon, building off of the incoming implementation of max clique coming in #20401 .

**Pull request closed without merging**
