### PR TITLE
Added method to set x(n) in the context for vector-valued ZeroOrderHold

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22005)

### CODE REVIEW

**Comment by AdityaBhat-TRI** [comment]
+@sammy-tri For review please!

**Review by sammy-tri — COMMENTED** [review]
:lgtm: +@sherm1 for platform review

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-:-O8nADr3EcIZzwXwpEZ4:bc8zi0o)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`systems/primitives/zero_order_hold.h` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-O8n9dX2-dxzNeR6TaP5:-O8n9dX2-dxzNeR6TaP6:b-a5omtm) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ae37bff9db2050d007205c24a541b669d5a117/systems/primitives/zero_order_hold.h#L87)):*
> ```objc
>   /// @p value must be a column vector of the appropriate size. This can only be
>   /// used to initialize a vector-valued state.
>   void set_vector_state(Context<T>* context,
> ```

Per https://drake.mit.edu/styleguide/cppguide.html#Function_Names I think this should be CamelCase but it's kinda on the edge.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22005)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`systems/primitives/zero_order_hold.h` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-O8nI2JH9HV_7eUxswng:-O8nI2JH9HV_7eUxswnh:boirern) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ae37bff9db2050d007205c24a541b669d5a117/systems/primitives/zero_order_hold.h#L87)):*
> ```objc
>   /// @p value must be a column vector of the appropriate size. This can only be
>   /// used to initialize a vector-valued state.
>   void set_vector_state(Context<T>* context,
> ```

nit We should aim for this function to be consistent with the other systems/primitives functions that can initialize the state.  In that light, I'm not sure that saying "vector" here as part of the name is a good idea?  My quick-skim take is that in case we decide to overload this to allow initializing abstract state, we would want to use the same function name for both cases, just with a different argument type?

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending name change to CamelCase to satisfy style guide.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-:-O8nYMEaBPI83Y99CwE3:bfde2ms)* status: 2 unresolved discussions, missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`systems/primitives/zero_order_hold.h` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-O8n9dX2-dxzNeR6TaP5:-O8nUm_V6yLh0rCVx1Q4:b-mww7mb) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ae37bff9db2050d007205c24a541b669d5a117/systems/primitives/zero_order_hold.h#L87)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Per https://drake.mit.edu/styleguide/cppguide.html#Function_Names I think this should be CamelCase but it's kinda on the edge.
</blockquote></details>

This should definitely be CamelCase -- writing to the state both (a) copies an arbitrary-length vector, and (b) invalidates an indeterminate number of cache entries in the Context. snake_case should be reserved for do-nothing accessors like period() and offset() above.
___
*[`systems/primitives/zero_order_hold.h` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-O8nI2JH9HV_7eUxswng:-O8nWEJp6bLeWsKXE1sc:b-1sbnk4) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ae37bff9db2050d007205c24a541b669d5a117/systems/primitives/zero_order_hold.h#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We should aim for this function to be consistent with the other systems/primitives functions that can initialize the state.  In that light, I'm not sure that saying "vector" here as part of the name is a good idea?  My quick-skim take is that in case we decide to overload this to allow initializing abstract state, we would want to use the same function name for both cases, just with a different argument type?
</blockquote></details>

Looking at systems/primitives I didn't see much good to model this on. I'm satisfied with `SetVectorState()` and a possible `SetAbstractState()` later. We might decide to templatize SetAbstractState() to take the concrete type -- that would be marginally easier without overloading `SetState()` and I think the call sites would be clearer.
___
*[`systems/primitives/zero_order_hold.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-O8nY-3-5szUZzzco1lA:-O8nY-3-5szUZzzco1lB:bfyhv8o) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ae37bff9db2050d007205c24a541b669d5a117/systems/primitives/zero_order_hold.cc#L53)):*
> ```cpp
>   DRAKE_ASSERT(!is_abstract());
>   this->ValidateContext(context);
>   BasicVector<T>& state_vector = context->get_mutable_discrete_state_vector();
> ```

FYI cache invalidation occurs here when the context is made to give up a mutable reference.

**Comment by AdityaBhat-TRI** [comment]
*[`systems/primitives/zero_order_hold.h` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22005#-O8n9dX2-dxzNeR6TaP5:-O8sU6WU3F__5e0IWAFl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e7ae37bff9db2050d007205c24a541b669d5a117/systems/primitives/zero_order_hold.h#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should definitely be CamelCase -- writing to the state both (a) copies an arbitrary-length vector, and (b) invalidates an indeterminate number of cache entries in the Context. snake_case should be reserved for do-nothing accessors like period() and offset() above.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22005)* status: 1 unresolved discussion, missing label for release notes

**Review by sherm1 — COMMENTED** [review]
> Dismissed @sammy-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22005)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Pull request merged**
