### PR TITLE
Adds time-stepping mode to RigidBodyPlant

### PR DESCRIPTION
**Pull request by RussTedrake**
Only handles the unconstrained case so far.  This first PR mostly brings in the logic to build up and initialize discrete state instead of continuous state, and the corresponding tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5226)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@edrumwri for feature review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-:-KdJ9UUleaYxSFbviE3r:b29uq9e)*

**Comment by hongkai-dai** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 584 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJWPyGSOlLMfdtSfod:-KdJWPyGSOlLMfdtSfoe:b-m4dhj9) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L584)):*
> ```cpp
>   VectorX<T> right_hand_side =
>       tree_->dynamicsBiasTerm(kinsol, no_external_wrenches);
>   if (num_actuators > 0) right_hand_side -= tree_->B * u;
> ```

I find it easier to understand, if we do not put a negative sign before the right hand side. I feel it is more natural to use `H * (vn - v) / h = right_hand_side`.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 865 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJV9ptnFAw0Tl8X8eL:-KdJV9puBiDw2v9-4fe7:btgqoha) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L865)):*
> ```cpp
>       if (this->EvalVectorInput(context, input_map_[instance_id]) == nullptr) {
>         throw runtime_error(
>             "RigidBodyPlant::DoCalcTimeDerivatives(): ERROR: "
> ```

`DoCalcTimeDerivatives()` -> `EvaluateActuatorInputs()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226)*

**Comment by liangfok** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 554 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZ3ZQoXjjrf9_BvcW:-KdJZ3ZQoXjjrf9_BvcX:b-kb1c5j) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L554)):*
> ```cpp
>   static_assert(std::is_same<double, T>::value,
>                 "Only support templating on double for now");
>   DRAKE_ASSERT_VOID(System<T>::CheckValidContext(context));
> ```

BTW, this might be redundant to the following: https://github.com/RobotLocomotion/drake/blob/9439f4d7e716dc5f39a2d5ae9564d634f9b71f97/drake/systems/framework/system.h#L423.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 577 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZQg4C2nMHQvEwKa0:-KdJZQg4C2nMHQvEwKa1:b-cgokfq) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L577)):*
> ```cpp
> 
>   // There are no external wrenches, but it is a required argument in
>   // dynamicsBiasTerm.
> ```

BTW, consider adding "()" after "dynamicsBiasTerm" so readers will know it's a method.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 635 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZapMEuLkB5I3Hz6F:-KdJZapMEuLkB5I3Hz6G:b-unlrb5) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L635)):*
> ```cpp
>   // TODO(amcastro-tri): we would like to compile here with `auto` instead of
>   // `VectorX<T>`. However it seems we get some sort of block from a block
>   // which
> ```

BTW, odd newline.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 670 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZc6aKjoXcA-BdhEd:-KdJZc6aKjoXcA-BdhEe:b-unlrb5) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L670)):*
> ```cpp
>   // TODO(amcastro-tri): we would like to compile here with `auto` instead of
>   // `VectorX<T>`. However it seems we get some sort of block from a block
>   // which
> ```

BTW, odd newline.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 738 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZcerB10V725tSQCn:-KdJZcesm95Tm6Z3j47X:b-unlrb5) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L738)):*
> ```cpp
>   u.minCoeff(&minAxis);
>   // The world axis corresponding to the smallest component of the local
>   // z-axis
> ```

BTW, odd newline.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 870 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZiqhMzlSU4dcj409:-KdJZiqhMzlSU4dcj40A:bhy0u4j) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L870)):*
> ```cpp
>             std::to_string(get_num_model_instances()) +
>             " actuator command "
>             "input ports must be connected.");
> ```

BTW, consider combining with the previous line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 554 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZ3ZQoXjjrf9_BvcW:-KdL9J3bzhQ5D3mGtlPn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L554)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this might be redundant to the following: https://github.com/RobotLocomotion/drake/blob/9439f4d7e716dc5f39a2d5ae9564d634f9b71f97/drake/systems/framework/system.h#L423.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 577 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZQg4C2nMHQvEwKa0:-KdL9N9aGWD7tpInStcv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L577)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding "()" after "dynamicsBiasTerm" so readers will know it's a method.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 584 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJWPyGSOlLMfdtSfod:-KdL9PC9etqZjm9jS9P7:bw0thgb) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L584)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I find it easier to understand, if we do not put a negative sign before the right hand side. I feel it is more natural to use `H * (vn - v) / h = right_hand_side`.
</blockquote></details>

i completely agree.  but i'm being consistent with the usage above (which did not come from me).  

actually... yes, I'll just change both.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 635 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZapMEuLkB5I3Hz6F:-KdLAk7q-R1HvyAvPoeM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L635)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, odd newline.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 670 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZc6aKjoXcA-BdhEd:-KdLAkhw_tWk0izaO_9M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L670)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, odd newline.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 738 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZcerB10V725tSQCn:-KdLAz4H4ZJbIkKz9Sxa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L738)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, odd newline.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 865 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJV9ptnFAw0Tl8X8eL:-KdLB4tw4Jw4T1slOZxh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L865)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`DoCalcTimeDerivatives()` -> `EvaluateActuatorInputs()`
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 870 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdJZiqhMzlSU4dcj409:-KdLBDZ06AUeNhtQGQ9F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fed6266a8620783a05ce44c7b35b0723b46b0778/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L870)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider combining with the previous line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226)*

**Comment by edrumwri** [comment]
First pass complete. Looks pretty good, Russ, but I will recommend refactoring comments in a separate commit in the future to allow your reviews to focus on the technical meat (and since Reviewable thankfully allows one to isolate some of the commit history).

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 449 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdMH2Kr-_Gofu4VRjwh:-KdMH2Kr-_Gofu4VRjwi:b-u8sksc) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L449)):*
> ```cpp
>   static_assert(std::is_same<double, T>::value,
>                 "Only support templating on double for now");
>   DRAKE_DEMAND(timestep_ == 0.0);
> ```

This should not be an assertion- you'll cause Simulator to crash, even though there are no continuous state variables. For the time stepping system, it should just return. 

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 488 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdMIi6EIq_zZ8WS4TsR:-KdMIi6EIq_zZ8WS4TsS:bel2wq8) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L488)):*
> ```cpp
>   // of dynamicsBiasTerm().
>   const typename RigidBodyTree<T>::BodyToWrenchMap no_external_wrenches;
>   // right_hand_side is the right hand side of the system's equations:
> ```

Could we call this something  than "right hand side"? It appears as if it should represent external wrenches, according to dynamicsBiasTerm() documentation. Correct?

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 489 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdMH_xU4XFjZa0yUjft:-KdMH_xVLvR4-HW1vuCR:bjv03yh) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L489)):*
> ```cpp
>   const typename RigidBodyTree<T>::BodyToWrenchMap no_external_wrenches;
>   // right_hand_side is the right hand side of the system's equations:
>   // H*vdot -J^T*f = right_hand_side.
> ```

Why did you remove the negation on the rhs in the comment? Documentation for dynamicsBiasTerm() indicates that it should be retained.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 587 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdML26l0l6Z_rc3T-i5:-KdML26mlKk9uW0FRkOJ:b-z9emgb) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L587)):*
> ```cpp
>   // TODO(russt): Handle contact constraints.
> 
>   // Add H*(vn - v)/h = right_hand_side
> ```

It looks like you're preparing to go down the route of solving this as a mixed linear complementarity problem. I advise against this. If you use a pivoting solver to solve it, you'll have to use a solver with weaker guarantees (P-matrix solvability rather than copositive solvability). I'm sure one of your suite of optimizers _can_ solve the MLCP, albeit with some residual error, but why make the problem harder and bigger (more variables) than it needs to be? Solve the linear complementarity problem first, then solve the remaining positive definite linear system to find vn. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-:-KdMNfFU9yXOf_T7zaJl:b-b8cbky)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 449 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdMH2Kr-_Gofu4VRjwh:-KdN9BEXPL-J7pcUiKyG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L449)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This should not be an assertion- you'll cause Simulator to crash, even though there are no continuous state variables. For the time stepping system, it should just return. 
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 488 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdMIi6EIq_zZ8WS4TsR:-KdN9IbuXidiRxz_eCNF:bxom74t) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L488)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Could we call this something  than "right hand side"? It appears as if it should represent external wrenches, according to dynamicsBiasTerm() documentation. Correct?
</blockquote></details>

no.  it is B*u - C*qdot - G.  I don't love the name right_hand_side, but it was there for the continuous-time version so I kept it.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 489 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdMH_xU4XFjZa0yUjft:-KdNA4BKNR4CMjZvwGlV:b-vdzruw) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L489)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why did you remove the negation on the rhs in the comment? Documentation for dynamicsBiasTerm() indicates that it should be retained.
</blockquote></details>

i believe the negation is now correct, and that the comments match.  dynamicsBiasTerm returns the C*qdot+G, but -dynamicsTerm puts those elements on the "right hand side".  Note: dynamicsBiasTerm is called with "no_external_wrenches"; it ONLY returns C*qdot+G

plus, hongkai asked me to flip the sign in this morning's review.  :)

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 587 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdML26l0l6Z_rc3T-i5:-KdNAdy-Nfn2VFwhzmVm:b-erjbcx) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L587)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It looks like you're preparing to go down the route of solving this as a mixed linear complementarity problem. I advise against this. If you use a pivoting solver to solve it, you'll have to use a solver with weaker guarantees (P-matrix solvability rather than copositive solvability). I'm sure one of your suite of optimizers _can_ solve the MLCP, albeit with some residual error, but why make the problem harder and bigger (more variables) than it needs to be? Solve the linear complementarity problem first, then solve the remaining positive definite linear system to find vn. 
</blockquote></details>

I want to make sure I understand your proposal (perhaps we can f2f) -- but I'm actually hoping that you will write this eventually.  I think that porting the matlab version (admittedly MLCP) is a reasonable sprint goal, and making it much better with Evan-power is absolutely the long-term plan.  Reformulations might complicate my A-B tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226)*

**Comment by edrumwri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 587 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-KdML26l0l6Z_rc3T-i5:-KdNTmXe2rh0QmzmC1r6:b6zrfcj) ([raw file](https://github.com/robotlocomotion/drake/blob/fc557c346f83c575670eade239079a1bf9d7dbf1/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L587)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I want to make sure I understand your proposal (perhaps we can f2f) -- but I'm actually hoping that you will write this eventually.  I think that porting the matlab version (admittedly MLCP) is a reasonable sprint goal, and making it much better with Evan-power is absolutely the long-term plan.  Reformulations might complicate my A-B tests.
</blockquote></details>

We can discuss f2f if you like, but I agree that it's reasonable to test against trusted, existing code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-:-KdNhV1hW8GROfWl41y-:bnfp4nl)*

**Comment by RussTedrake** [comment]
thanks @edrumwri .  +@sherm1 for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-:-KdNl-d8knFd6E63cJRR:b-xdc7tm)*

**Comment by RussTedrake** [comment]
-@sherm1 +@sammy-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-:-Kd_IoZA9IZ8541oPLhA:b-l97y0w)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5226#-:-KdaQp0OOAWz4ph6Uw2y:bsf2vkf)*

**Pull request merged**
