### PR TITLE
Updated documentation for scalar and vector differentiation

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6636)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@amcastro-tri 
Platform review +@sherm1 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-:-KpcHhGUs0o3WDvn44z0:b-re2b78)*

**Comment by amcastro-tri** [comment]
Thank you for writing this @mitiguy, it looks great!. Just a few comments. :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 285 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpoizLl8vtCvwgMCPC-:-KpoizLm2PPRBN0OxZpr:b9tr7f5) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L285)):*
> ```objc
> Quantities of interest in multibody dynamics have distinct types. For example,
> a rotation matrix is denoted with `R` and a position vector with `p`. New
> quantities can be created by differentiation an existing quantity (see
> ```

BTW,  differentiation **of** an existing quantity 

---

*[drake/multibody/multibody_doxygen.h, line 293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpojHrwY_czckrAl0rs:-KpojHrwY_czckrAl0rt:b-gb6mu8) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L293)):*
> ```objc
> are _expressed_ in a particular basis to provide numerical values for the
> vector elements. For example, the velocity of a point P moving in a reference
> frame F is a vector quantity with _target_ point P and _reference_ F.  In
> ```

BTW, and _reference_ **frame** P. 
To make it consistent with firs part of sentence before "and"

---

*[drake/multibody/multibody_doxygen.h, line 309 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpojvQmo4AGE3Th-Fui:-KpojvQmo4AGE3Th-Fuj:bzbkjnj) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L309)):*
> ```objc
> We adhere to this pattern for all quantities and it is quite useful once you get
> familiar with it. As a second example, consider the position vector of point Bcm
> (body B's center of mass) from point Bo (the origin of B) and expressed in B.
> ```

BTW, I would say "the origin of **frame** B" at least the first time I mention it to introduce it. Subsequent mentions of B then could drop the word "frame" if we wish

---

*[drake/multibody/multibody_doxygen.h, line 326 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpokTF8AgLBE_Ewp7Y5:-KpokTF8AgLBE_Ewp7Y6:b-2obipp) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L326)):*
> ```objc
> Rotation matrix     |  R   |@f$^BR^C@f$     |`R_BC`    |Frame C's orientation in B
> Position vector     |  p   |@f$^Pp^Q@f$     |`p_PQ`    |Position from point P to point Q
> Transform           |  X   |@f$^BX^C@f$     |`X_BC`    |Frame C's pose in B
> ```

BTW, maybe call it "Transform/Pose"? since we many times say `X_AB` is the pose of frame B in frame A.

---

*[drake/multibody/multibody_doxygen.h, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpolGe_0IeslUs0qeX2:-KpolGe_0IeslUs0qeX3:b28i6i7) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L333)):*
> ```objc
> Acceleration        |  a   |@f$^Ba^Q@f$     |`a_BQ`    |%Point Q's acceleration in B
> Spatial acceleration|  A   |@f$^BA^C@f$     |`A_BC`    |Frame C's spatial acceleration in B
> Torque              |  t   |@f$\tau^B@f$    |`t_B`     |Resultant torque on frame B
> ```

Question for you. In our book you use a notation like so @f$ M^{S/B_p} @f$ to denote the moment of all forces on a system S about a point `Bp`. I wonder how that would translate to our monogram notation.
Therefore, is it implicit in this table that `t_B` would be the moment on B about `Bo`?

---

*[drake/multibody/multibody_doxygen.h, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-Kpomdj6cJcz_ptYRtUS:-Kpomdj6cJcz_ptYRtUT:bq1y6rj) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L372)):*
> ```objc
> spatial acceleration A_BC, the derivative <b>must</b> be taken in B.
> However, the resulting expressed-in frame is arbitrary, e.g., a frame F.
> The expressed-in frame E for `V_BC` does not impact the final result. The
> ```

here I would keep using the same expressed-in frame F introduced in the previous sentence for consistency. Personally I'd prefer to use E instead of F since it refers to "Expressed". However up to you what letter to use as long as it is kept consistent across the text.

---

*[drake/multibody/multibody_doxygen.h, line 377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KponCug1Tt9Qi06bHC3:-KponCug1Tt9Qi06bHC4:bxufcs8) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L377)):*
> ```objc
> result, not the quantity being differentiated. The resulting vector happens to
> be `A_BC_F`, but that is only because the derivative was taken in frame B.
> If the derivative was taken in F (or C or E or any frame other than B), there
> ```

Somehow a continuation of the previous comment on E vs F: To avoid confusion with the previous "expressed-in" frame, I would call the expressed-in frame E and then you can freely use F here as another arbitrary frame in which to take the time derivative.

---

*[drake/multibody/multibody_doxygen.h, line 384 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KponljRfoC6x3yxgvw9:-KponljRfoC6x3yxgvwA:b-aa8gds) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L384)):*
> ```objc
> _always_ specified at the end of the symbol.  However there is _never_ an
> expressed-in frame specified for the quantity being differentiated. For
> example, given a vector quantity v, an expression like `DtG(v_E)_F` is spurious.
> ```

BTW, instead of "spurious" maybe "erroneous" or "misguided"? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-:-KpooFJohVs4mMnnfhNo:bpcfbkx)*

**Comment by sherm1** [comment]
Very nice! A few minor BTWs and resolution of @amcastro-tri's comments, then :lgtm:.

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 302 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KppKFIuuXwgrV57cl-E:-KppKFIuuXwgrV57cl-F:bgpyjr4) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L302)):*
> ```objc
> @f$[^Fv^P]_W@f$.
> 
> The typeset symbol @f$[^Fv^P]@f$ is translated to monogram notation as `v_FP`.
> ```

BTW shouldn't have brackets on this symbol.

---

*[drake/multibody/multibody_doxygen.h, line 387 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KppM5RzDk3z6w3mzswG:-KppM5RzDk3z6w3mzswH:bq4uqla) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L387)):*
> ```objc
> Use valid notation such as `DtG(v)_F`.
> 
> In Unicode comment involving vector derivatives, use `ᴬd/dt Q` (preferred if
> ```

BTW "In **a** Unicode comment"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-:-KppMNXCC-vJCXbRCPhB:b8opt8y)*

**Comment by mitiguy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpolGe_0IeslUs0qeX2:-KpqjhVCabFxnbSBrFQ2:b-hkrb4h) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L333)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Question for you. In our book you use a notation like so @f$ M^{S/B_p} @f$ to denote the moment of all forces on a system S about a point `Bp`. I wonder how that would translate to our monogram notation.
Therefore, is it implicit in this table that `t_B` would be the moment on B about `Bo`?
</blockquote></details>

Done.  Information in the table was updated.  A footnote was added.

---

*[drake/multibody/multibody_doxygen.h, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-Kpomdj6cJcz_ptYRtUS:-KprEK-xR92b7xQemPL1:bixj0ck) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L372)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

here I would keep using the same expressed-in frame F introduced in the previous sentence for consistency. Personally I'd prefer to use E instead of F since it refers to "Expressed". However up to you what letter to use as long as it is kept consistent across the text.
</blockquote></details>

Done.  I like using E for the expressed-in frame, and use it frequently in code/comments.
However, here I think two expressed-in frames are necessary to make the point.
I discussed with Sherm, and he agrees that this is a place where both E and F are helpful/useful.

---

*[drake/multibody/multibody_doxygen.h, line 377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KponCug1Tt9Qi06bHC3:-KprEZ46p-Arsn8G8_O-:brcyeae) ([raw file](https://github.com/robotlocomotion/drake/blob/7813360da25dde9b5220a843ef8f77a88a2befaa/drake/multibody/multibody_doxygen.h#L377)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Somehow a continuation of the previous comment on E vs F: To avoid confusion with the previous "expressed-in" frame, I would call the expressed-in frame E and then you can freely use F here as another arbitrary frame in which to take the time derivative.
</blockquote></details>

Done.  See above response.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[drake/multibody/multibody_doxygen.h, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptrcdT2UEf0zLRO9Zr:-KptrcdT2UEf0zLRO9Zs:b4bmkix) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L335)):*
> ```objc
> Torque              |  t   |@f$\tau^S@f$    |`t_S`     |Torque from a set S of forces
> Force               |  f   |@f$f^{So}@f$    |`f_So`    |Force on a point So
> Spatial force       |  F   |@f$F^{So}@f$    |`F_So`    |Torque/force for a set S of forces ††
> ```

BTW. I ask you because I am writing code right now for this. How would you denote, in monogram notation, the spatial force `F` that applies on a body `B` about a point `Mo` on that body? `F_BMo`? or just `F_Mo`? 

---

*[drake/multibody/multibody_doxygen.h, line 338 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptqGvge0ZHnGNAY9_p:-KptqGvge0ZHnGNAY9_q:bi43z1m) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L338)):*
> ```objc
> 
> † In code, a vector has an expressed-in-frame which appears after the quantity.
> <br>Example: w_BC_E is C's angular velocity in B, expressed in frame E, typeset
> ```

BTW, missing backticks for w_BC_E, `w_BC_E`

---

*[drake/multibody/multibody_doxygen.h, line 342 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptqTBkMbSq1hH1XcY2:-KptqTBkMbSq1hH1XcY3:bdxmw8x) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L342)):*
> ```objc
> 
> †† A set S of forces can be <b>replaced</b> by an equivalent set consisting of
> the set's resultant force Fˢᵒ placed at an arbitrary point So together with a
> ```

BTW. in the table, you used uppercase `F` for spatial forces and lower case `f` for a 3D force. Should this be f_So instead?
also, in my browser the `Fˢᵒ` does not render very nicely. Consider just using the monogram notation only in this case.

---

*[drake/multibody/multibody_doxygen.h, line 343 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-Kptr4l4nuLfhTA6qJ1s:-Kptr4l4nuLfhTA6qJ1t:b98i3de) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L343)):*
> ```objc
> †† A set S of forces can be <b>replaced</b> by an equivalent set consisting of
> the set's resultant force Fˢᵒ placed at an arbitrary point So together with a
> torque Tˢ whose moment is equal to moment of S about So.  Replacement by
> ```

BTW, same comment as for the force. In the table, 3D torque vector was denoted with lowercase `t`, not uppercase `T` (which for us usually is the scalar type parameter `<T>`)

---

*[drake/multibody/multibody_doxygen.h, line 344 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptrR7_ffW9fRZSmBUl:-KptrR7_ffW9fRZSmBUm:bh3r293) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L344)):*
> ```objc
> the set's resultant force Fˢᵒ placed at an arbitrary point So together with a
> torque Tˢ whose moment is equal to moment of S about So.  Replacement by
> equivalent sets is useful in simulation/analyses of <b>rigid</b> bodies.
> ```

I would say "in the simulation/analyses of mechanical systems", being more general not only for rigid bodies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636)*

**Comment by sherm1** [comment]
I don't think the "set of forces" stuff is working here, Paul, please see below.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpuenQlBscs7n0Dd4X2:-KpuenQlBscs7n0Dd4X3:bczb9yk) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L335)):*
> ```objc
> Torque              |  t   |@f$\tau^S@f$    |`t_S`     |Torque from a set S of forces
> Force               |  f   |@f$f^{So}@f$    |`f_So`    |Force on a point So
> Spatial force       |  F   |@f$F^{So}@f$    |`F_So`    |Torque/force for a set S of forces ††
> ```

This doesn't make sense to me. The right superscript represents the application point, not the original set of forces. You seem to be using it two different ways here. I don't think the "set of forces" idea is clarifying here at all -- I would rather it not get introduced as part of the notational conventions unless it is clarifying something. So I think (a) the "_S" should be removed from the torque symbol, and (b) the "set" discussion should be removed from the explanation for `F_So` which should just explain which body is being affected by F and where the translational component is being applied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-:-Kpufqw6F0lLiXw369Xg:bhx8b4v)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptrcdT2UEf0zLRO9Zr:-KpuhtvCResaSS2_qaj9:b-nqih5q) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L335)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW. I ask you because I am writing code right now for this. How would you denote, in monogram notation, the spatial force `F` that applies on a body `B` about a point `Mo` on that body? `F_BMo`? or just `F_Mo`? 
</blockquote></details>

@amcastro-tri, it doesn't make sense to say the spatial force is *about* a point. Instead the translational force is applied *at* a point, and the rotational component is a pure torque applied to the rigid body. The SpatialVector section defines the spatial force notation with just a single F_P where P is the application point on a particular body, with the implication that the torque is applied to the same body. So I think just `F_Mo` would be fine for a spatial force applied at frame M's origin, provided that M has already been defined to be rigidly fixed to some particular body. We could define a two-symbol version but I think it is likely to be less clear -- while I can parse `F_BMo`, what would `F_PMo` mean (assuming M is not fixed on P)? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636)*

**Comment by mitiguy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptrcdT2UEf0zLRO9Zr:-KpvMmi98uO0Pmw3sIne:b-ahxxnu) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L335)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@amcastro-tri, it doesn't make sense to say the spatial force is *about* a point. Instead the translational force is applied *at* a point, and the rotational component is a pure torque applied to the rigid body. The SpatialVector section defines the spatial force notation with just a single F_P where P is the application point on a particular body, with the implication that the torque is applied to the same body. So I think just `F_Mo` would be fine for a spatial force applied at frame M's origin, provided that M has already been defined to be rigidly fixed to some particular body. We could define a two-symbol version but I think it is likely to be less clear -- while I can parse `F_BMo`, what would `F_PMo` mean (assuming M is not fixed on P)? 
</blockquote></details>

Done.  I agree with Sherm.  `F_Mo` is preferable if  `M` as been defined as fixed on B. 

---

*[drake/multibody/multibody_doxygen.h, line 335 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpuenQlBscs7n0Dd4X2:-KpvMuS1FMPa2Eo5Ljow:b-tgzr8l) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L335)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This doesn't make sense to me. The right superscript represents the application point, not the original set of forces. You seem to be using it two different ways here. I don't think the "set of forces" idea is clarifying here at all -- I would rather it not get introduced as part of the notational conventions unless it is clarifying something. So I think (a) the "_S" should be removed from the torque symbol, and (b) the "set" discussion should be removed from the explanation for `F_So` which should just explain which body is being affected by F and where the translational component is being applied.
</blockquote></details>

Done.  Documentation updated.  The S and So has been removed.
There is a mention of a set in the footnote -- but not as a rigorous definition of SpatialForce.
Instead, the helpful footnote describes a practical use of a SpatialForce.  

---

*[drake/multibody/multibody_doxygen.h, line 344 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KptrR7_ffW9fRZSmBUl:-KpvT_pURHdzDEeb02dG:brpnmz4) ([raw file](https://github.com/robotlocomotion/drake/blob/a06daca6f1c69fab9dd9be23e62003ae63c418e9/drake/multibody/multibody_doxygen.h#L344)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would say "in the simulation/analyses of mechanical systems", being more general not only for rigid bodies.
</blockquote></details>

Done.  Modified

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636)*

**Comment by sherm1** [comment]
:lgtm: except for one typo (see BTW below).

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 333 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-KpviWVDvSmVMDpSwWEQ:-KpviWVDvSmVMDpSwWER:b-tdt7ix) ([raw file](https://github.com/robotlocomotion/drake/blob/2612347bb958cb4ae36800116217374c76f14540/drake/multibody/multibody_doxygen.h#L333)):*
> ```objc
> Acceleration        |  a   |@f$^Ba^Q@f$     |`a_BQ`    |%Point Q's acceleration in B
> Spatial acceleration|  A   |@f$^BA^C@f$     |`A_BC`    |Frame C's spatial acceleration in B
> Torque              |  t   |@f$\tau^S@f$    |`t`       |Torque
> ```

BTW the superscript S is still present in the typeset torque column.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636#-:-Kpvj60EER_BpDMYzlEk:bpc956h)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6636)*

**Pull request merged**
