### PR TITLE
multibody: Add parsing for PlanarJoint

### PR DESCRIPTION
**Pull request by mpetersen94**
Follow up to #13747. Adds parsing for Planar Joint.

Relates #12404

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13824)

### CODE REVIEW

**Comment by mpetersen94** [comment]
I don't fully understand how to parse poses for joints in sdf.  If someone could point me in the right direction that would be great!

**Comment by soonho-tri** [comment]
I've added `do not review` label. Please feel free to remove it when you find a feature-reviewer.

**Comment by EricCousineau-TRI** [comment]
Per f2f with @SeanCurtis-TRI, @azeey, @scpeters, will go for the `//drake:joint` route. Will revisit once libsdformat supports something like `//joint/@type="custom"`.

I'll finish up review of this PR later today.

**Comment by mpetersen94** [comment]
___
*[multibody/parsing/detail_sdf_parser.cc, line 644 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13824#-ME9Lrik9v1H0lRlsVe8:-MEGFQWe1ZvOEFHM74vf:b-e20xno) ([raw file](https://github.com/robotlocomotion/drake/blob/e56a420b433371b622d4e7acdc28c0fa958ece4d/multibody/parsing/detail_sdf_parser.cc#L644)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unfortunately not :( I don't see the action item in this code, I only see the fail-fast for `//pose` per the above comment.
</blockquote></details>

What should I add besides the "TODO(eric.cousineau): Add support for parsing joint pose."

**Comment by jwnimmer-tri** [comment]
FYI The problem that libsdformat lets garbage through is pre-existing and pervasive: https://github.com/osrf/sdformat/issues/228 and https://github.com/RobotLocomotion/drake/issues/12610.

**Pull request merged**
