### PR TITLE
Update to Bazel 0.10.1 on Ubuntu and improve CLion integration

### LINKED ISSUE #7586: Removal of top-level drake-distro broke CLion
Per discussion on Slack #clion channel, the rename _(JN edit: in #7575 for #6996)_ of all files from `drake/blah` to just `blah` had some unforseen consequences. Our header includes look like `drake/common/something.h` which could be resolved by starting at the top-level directory (`drake-distro` or whatever). Now there is no such file name so we are crafting symbolic links in `~/.cache/bazel` in a mock top-level directory.

CLion is not amused by this. When following symbols, instead of opening header files under their original names it opens the (very long named) symbolic links, which are read only and not recognized as being part of the project. Edits made to the correctly-named files do not trigger re-indexing so the new symbols are not recognized until a manual Bazel Sync is done (a slow process). It is not clear whether other source-aware IDEs or tools would have similar confusion.

Other projects deal with this issue in various ways. However, a popular one is to introduce an extra level in the git repo, for example @jwnimmer-tri found [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow). That is what we were doing before -- maybe it was fine as it was?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See commit messages for details.

Closes #7586.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8016)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/developers.rst, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4utICS3c80wKvO1xkD:-L4utICS3c80wKvO1xkE:bxg04zy) ([raw file](https://github.com/robotlocomotion/drake/blob/3bd2f206147efb383ddf8b6ee700ddf52ed0f5ab/doc/developers.rst#L84)):*
> ```reStructuredText
> |                             | | CMake 3.5.1  | | GCC 5.4       |            |                   |        |
> +-----------------------------+----------------+-----------------+------------+                   +--------+
> | macOS 10.12 ("Sierra")      | | Bazel 0.6.1  | Apple Clang 9.0 | Oracle 1.8 |                   | 2.7.14 |
> ```

BTW You can definitely update Mac now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI could I ask you do to the code review portion of feature review?  I'm working on recruiting users to test this locally, separately.

**Comment by SeanCurtis-TRI** [comment]
I'll serve as a volunteer.

**Comment by EricCousineau-TRI** [comment]
+@seancurtis-tri as feature reviewer (local testing).

:lgtm: codewise, pending minor comments.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/clion/bazel_wrapper, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wCtzIid5kYSLadGF_:-L4wCtzIid5kYSLadGFa:bcp38p7) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L5)):*
> ```
> import os
> import subprocess
> import re
> ```

BTW Imports are not alphabetical.

---

*[tools/clion/bazel_wrapper, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wCxCE7cpAKq7-NCke:-L4wCxCFmOVi453DWIhI:b-urjge) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L10)):*
> ```
> # Always use stderr for diagnostics; somehow, stdout is silenced in CLion.
> def _write_stderr(bytes):
>     os.write(2, bytes)
> ```

BTW Can you rewrite this as `sys.stderr.write(bytes)`?

---

*[tools/clion/bazel_wrapper, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wDMLj9umLj5BrBPin:-L4wDMLkkFzE6Y9VnINl:bb10j0j) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L16)):*
> ```
>     workspace_contents = ""
>     try:
>         with open(os.path.join(os.getcwd(), "WORKSPACE"), "r") as f:
> ```

BTW Can this be rewritten as `workspace_file = os.path.join(...); if os.path.exists(workspace_file):` ?

---

*[tools/clion/bazel_wrapper, line 41 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wDbDWnbI0hh4iFyU4:-L4wDbDWnbI0hh4iFyU5:b-bvj2pm) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L41)):*
> ```
>     if nostream_magic in args:
>         args.pop(args.index(nostream_magic))
>         execvp("bazel", ["bazel"] + args)
> ```

BTW Can a quick comment here mention that this program's execution effectively ends here? (It's implied with `execv`, but just for people who are not familiar?)

---

*[tools/clion/bazel_wrapper, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wE5t7ZqdhbUgWLqu2:-L4wE5t7ZqdhbUgWLqu3:b-amf2bf) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L78)):*
> ```
> 
>     # Cleanup.
>     bazel.terminate()
> ```

BTW Why is `terminate` needed here? Is `wait` sufficient?

---

*[tools/clion/test/bazel_wrapper_test.py, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wEms_cTtamUXhzUHT:-L4wEmsazIjLUsL7fQ0h:bqm10rq) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/test/bazel_wrapper_test.py#L121)):*
> ```Python
>         self._bazel_subprocess_mock.stderr = StringIO.StringIO("")
>         old_magic = "--aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect"  # noqa
>         new_magic = "--aspects=@drake//tools/clion:aspect.bzl%intellij_info_aspect"  # noqa
> ```

`new_magic` is unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-:-L4wFAEoYkDI8CPi80vC:b-cgt7xp)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/clion/bazel_wrapper, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wCtzIid5kYSLadGF_:-L4wQJ383neDx0SbrXwK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L5)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Imports are not alphabetical.
</blockquote></details>

Done.

---

*[tools/clion/bazel_wrapper, line 41 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wDbDWnbI0hh4iFyU4:-L4wQCBpkPfoqrCkQOM5:b-9bcii4) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L41)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can a quick comment here mention that this program's execution effectively ends here? (It's implied with `execv`, but just for people who are not familiar?)
</blockquote></details>

Done.  (Up above.)

---

*[tools/clion/test/bazel_wrapper_test.py, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wEms_cTtamUXhzUHT:-L4wQD2LAWAjr7Rk9rm2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/test/bazel_wrapper_test.py#L121)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

`new_magic` is unused?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/clion/bazel_wrapper, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wCxCE7cpAKq7-NCke:-L5-ptT7m9dyn33zx9FN:bwqa6ad) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L10)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you rewrite this as `sys.stderr.write(bytes)`?
</blockquote></details>

Done (added comment).

---

*[tools/clion/bazel_wrapper, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wDMLj9umLj5BrBPin:-L5-plK2Gfdf81NJa4BG:b-23s9q6) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L16)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can this be rewritten as `workspace_file = os.path.join(...); if os.path.exists(workspace_file):` ?
</blockquote></details>

This way handles correctly handles files that exist but are unreadable.

---

*[tools/clion/bazel_wrapper, line 78 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L4wE5t7ZqdhbUgWLqu2:-L5-pff05L9iW5XQ4PCf:b9adje9) ([raw file](https://github.com/robotlocomotion/drake/blob/bf4dbc27de6449452d5637e3aaee333ebd60246e/tools/clion/bazel_wrapper#L78)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Why is `terminate` needed here? Is `wait` sufficient?
</blockquote></details>

It's not obvious to me that EOF from stderr is the same thing as the process terminating.  Better safe than sorry?  I would even say its conventional by rote to always call terminate before wait (unless we already saw a CalledProcessError or non-None returncode).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016)*

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI I am wondering if I can revise this PR to use 0.10.1 instead of 0.10.0?  Unless you've already starting testing with 0.10.0, I think it would be better to revise to the newest and test that.

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri Go for it.

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-:-L5Ph3k2L9Ls0J5uoKsc:b-if0n7e)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
Hmm.  On CMake + Clang, something with the CXX wrapper script is failing now on 0.10.1.

**Comment by jamiesnape** [comment]
Same failure on 0.10.0, it seems: https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-xenial-unprovisioned-clang-cmake-experimental/2/.

**Comment by jwnimmer-tri** [comment]
Yup, I've repro'd locally.  Initial evidence is that the argv of the "give me your includes" is different now, though it looked to me unchanged on bazel master.  Still digging.

**Comment by jwnimmer-tri** [comment]
Ah.  It looks like Bazel stopped pass `-E` when sniffing for include directories, so (1) our realpathing branch wasn't even firing and (2) even if it did, the returncode 1 from the compiler was tripping our pipefail and aborting the script.  Yaks galore.

**Comment by jwnimmer-tri** [comment]
It then also seems like we've hit bazelbuild/bazel#4572.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/cc_toolchain/wrapper.sh.in, line 45 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-L5QCUKW5fcPoRIR5tfZ:-L5QCUKW5fcPoRIR5tf_:b70uhz9) ([raw file](https://github.com/robotlocomotion/drake/blob/1056836ed4f41ae4f14db1f5f021496b35f1b236/tools/cc_toolchain/wrapper.sh.in#L45)):*
> ```
>       # bazel sees the include path /usr/lib/clang/4.0.0/include get used.
>       # That resolves to /usr/lib/llvm-4.0/lib/clang/4.0.0/include, which is
>       # already detected during include sniffing (its just one more respelling
> ```

BTW it's / it is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016)*

**Comment by jwnimmer-tri** [comment]
With the latest fixes, the unprovisioned builds pass now.  I'll do a final launch of those after final LGTMs are in.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
Is this close to being ready? I have to update the Linux images for other reasons, so it would be good if I could do the bazel update at the same time.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: generally with one annoying artifact called out:

Running something defined as a `drake_cc_binary` has some unexpected aspects. 

First,  by default, CLion wants to run all executables as `bazel test`. That is the default configuration. However, one can change the configuration to be the equivalent of `bazel run`.

Using `examples/contact_model:bowling_ball` as an example, we have the following:

What should happen
---------------------------
  - `bazel test` should load geometry and simulate for 0.01 s (due to a test only rule parameter).
  - `bazel run` should load geometry and simulate for the default 3 seconds (sufficient for the ball to knock over the pints.

What *does* happen
---------------------------
  - Clion's "test" configuration: Nothing is apparently executed. No geometry gets loaded no simulation is run.
  - Clion's "run" configuration: geometry is loaded but simulation follows the test-only rule and runs 0.01 s.

Below I've  added the logs for the two Clion iterations

*Caveat*: I haven't tested this explicitly in the previous version. I *do* know that the most recent, previous versions of Clion/bazel plugin have changed how programs get run -- all via some kind of test. I realize that there may not be a thing we can do about this. I thought I'd just call it out.


Bazel console for bowling ball and `test`:
------------------------------------------------------------
```
Testing started at 12:00 PM ...
/home/sean/code/drake/tools/clion/bazel_wrapper test --tool_tag=ijwb:CLion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --runs_per_test=1 --flaky_test_attempts=1 --experimental_build_event_binary_file=/tmp/intellij-bep-cc81994e-fca2-41e8-96f3-5d16d1c3424b --noexperimental_build_event_binary_file_path_conversion -- //examples/contact_model:bowling_ball_test
Another command (pid=25138) is running.  Waiting for it to complete on the server...
INFO: Loading complete.  Analyzing...
INFO: Found 1 test target...
INFO: Building...

Building complete.
Target //examples/contact_model:bowling_ball_test up-to-date:

INFO:   bazel-bin/examples/contact_model/bowling_ball_test
INFO: Executed 0 out of 1 test: 1 test passes.
Elapsed time: 5.650s, Critical Path: 0.03s

Process finished with exit code 0
```


Bazel console for bowling ball and `run`:
------------------------------------------------------------
```
/home/sean/code/drake/tools/clion/bazel_wrapper run --tool_tag=ijwb:CLion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no -- //examples/contact_model:bowling_ball_test
INFO: Loading complete.  Analyzing...
INFO: Found 1 target...
INFO: Building...
Target //examples/contact_model:bowling_ball_test up-to-date:
  bazel-bin/examples/contact_model/bowling_ball_test
INFO: Elapsed time: 0.756s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/examples/contact_model/bowling_ball_test '--sim_duration=0.01'
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
[2018-02-23 12:01:31.401] [console] [warning] Meshes are only supported for drake_visualizer (/home/sean/.cache/bazel/_bazel_sean/e9a81359c04a94f591059ffdea1b7b12/execroot/drake/bazel-out/k8-opt/bin/examples/contact_model/bowling_ball_test.runfiles/drake/examples/contact_model/./pin.obj)
Parameters:
	timestep:         0.0002
	v:                12
	ω:                25
	young's modulus:  1e+08
	static friction:  0.4
	dynamic friction: 0.2
	slip threshold:   0.01
	Contact radius:   0.001
	dissipation:      2
	pin count:        10
```

---

Reviewed 1 of 6 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 4 files at r5.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8016#-:-L63C6yK9DLXsAnsO570:b-yt3yfs)*

**Comment by jwnimmer-tri** [comment]
> Clion's "test" configuration: Nothing is apparently executed. No geometry gets loaded no simulation is run.

I think that's because the test result was already cached (for you):
```console
INFO: Executed 0 out of 1 test: 1 test passes.
```
Use https://docs.bazel.build/versions/master/user-manual.html#flag--cache_test_results to force-run a test.

---

> Clion's "run" configuration: geometry is loaded but simulation follows the test-only rule and runs 0.01 s.

I think that's because you ran the test rule (which embeds the arguments), and not the binary:
```console
.../bazel_wrapper run ... -- //examples/contact_model:bowling_ball_test
```
If you did `run //examples/contact_model:bowling_ball` I would expect to see the full 3 seconds.

---

I'll take a few minutes to see if I can find any gotchas locally, but my inclination is to chalk this up to "Doctor!  It hurts when I use add_test_rule!".

---

Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-:-L6P5Zcx7BOUsYYGnMRt:b-msmj62)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI could you update your green-eyeball status and/or re-LGTM this to make sure you've reviewed everything new here?  In particular it looks like perhaps you haven't looked over the wrapper.sh.in changes yet.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-:-L6P9NSSEEKokQhFcx6j:b-qpkew9)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 4 files at r5, 1 of 2 files at r6, 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/cc_toolchain/wrapper.sh.in, line 51 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-L6PdmDJ9Y1bYLSs487n:-L6PdmDJ9Y1bYLSs487o:b-frk3ep) ([raw file](https://github.com/robotlocomotion/drake/blob/58b6a78459269bfb648c6f29a25f47efb75a5e45/tools/cc_toolchain/wrapper.sh.in#L51)):*
> ```
>         line_extra=/usr/lib/clang/4.0.0/include
>         # Escape slashes to be able to use the string in `sed`
>         line_extra=$(echo $line_extra | sed -e 's/\//\\\//g')
> ```

BTW Can this sed script be changed to `s#/#\\/#g`?

---

*[tools/cc_toolchain/wrapper.sh.in, line 52 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-L6PdZNAAFIQFdMU98QL:-L6PdZNAAFIQFdMU98QM:bv8v24r) ([raw file](https://github.com/robotlocomotion/drake/blob/58b6a78459269bfb648c6f29a25f47efb75a5e45/tools/cc_toolchain/wrapper.sh.in#L52)):*
> ```
>         # Escape slashes to be able to use the string in `sed`
>         line_extra=$(echo $line_extra | sed -e 's/\//\\\//g')
>         # Adds the same number of space at the beginning of the line
> ```

BTW minor grammar error, "space**s**"

---

*[tools/cc_toolchain/wrapper.sh.in, line 54 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-L6Pdwdn1eaN1mOgrte8:-L6Pdwdn1eaN1mOgrte9:bxf8xuh) ([raw file](https://github.com/robotlocomotion/drake/blob/58b6a78459269bfb648c6f29a25f47efb75a5e45/tools/cc_toolchain/wrapper.sh.in#L54)):*
> ```
>         # Adds the same number of space at the beginning of the line
>         # as there was in the original string.
>         echo "$line" | sed -e "s/\/usr.*/$line_extra/" >&2
> ```

BTW Same thing here, can `#` be used as the `s` sentinels here, rather than `/`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016)*

**Comment by jwnimmer-tri** [comment]
The "unprovisioned" passed in the prior push, so -(status: do not merge).  This push is only comment changes so I won't bother to re-run them.

---

Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/cc_toolchain/wrapper.sh.in, line 51 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-L6PdmDJ9Y1bYLSs487n:-L6Pld_D7LqRqYLv5UTv:bsjw9w3) ([raw file](https://github.com/robotlocomotion/drake/blob/58b6a78459269bfb648c6f29a25f47efb75a5e45/tools/cc_toolchain/wrapper.sh.in#L51)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can this sed script be changed to `s#/#\\/#g`?
</blockquote></details>

OK Indeed, that would be possible.  However, this it how it was done above and I don't mind it.

---

*[tools/cc_toolchain/wrapper.sh.in, line 52 at r7](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-L6PdZNAAFIQFdMU98QL:-L6Pmh-N1qyo-y4G7l2U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58b6a78459269bfb648c6f29a25f47efb75a5e45/tools/cc_toolchain/wrapper.sh.in#L52)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW minor grammar error, "space**s**"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8016#-:-L6PmU-RAz4P4-rkgr_o:b-6up9ln)*

**Pull request merged**
