### PR TITLE
[workspace] Use sdformat hidden visibility

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
When building C++ code, we can't use `-fvisibility=hidden` because it infects all #included code, even the standard library. Instead, we should wrap the third-party C++ code in a inline hidden namespace. That way, only the third-party code itself is hidden.

Towards #17231.

Requires:
- [x] #17278
- [x] #17303
- [x] #17334

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17230)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17230)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform reviewed as best I can with limited understanding of the build system. I think I get the idea though and it looks good.
:lgtm:

> Reviewed 2 of 10 files at r1, 5 of 13 files at r2, 4 of 15 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17230#-:-N439AP7CUExfhAyn-uJ:b-jlspo9)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`tools/workspace/gz_math_internal/package.BUILD.bazel` line 42 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17230#-N437IJ3EDG6_-qvA-EM:-N437IJ3EDG6_-qvA-EN:b-wvyvby) ([raw file](https://github.com/robotlocomotion/drake/blob/2588da64495e1aa8feaf5d3cb15d51d5a90736c5/tools/workspace/gz_math_internal/package.BUILD.bazel#L42)):*
> ```
>     defines = [
>         "IGN_DESIGNATION=math",
>         "PROJECT_VERSION_MAJOR=0",
> ```

BTW I gather the version numbers don't matter anymore but it isn't clear why. Consider adding a comment to explain why (a) they don't matter, and (b) why we have to define them at all.
___
*[`tools/workspace/gz_math_internal/package.BUILD.bazel` line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17230#-N4379W91_iEEPjZlAPy:-N4379W91_iEEPjZlAPz:bwjhngy) ([raw file](https://github.com/robotlocomotion/drake/blob/2588da64495e1aa8feaf5d3cb15d51d5a90736c5/tools/workspace/gz_math_internal/package.BUILD.bazel#L43)):*
> ```
>         "IGN_DESIGNATION=math",
>         "PROJECT_VERSION_MAJOR=0",
>         "PROJECT_VERSION_MINOR=%0",
> ```

nit: `%0` -> `0`
___
*[`tools/workspace/gz_utils_internal/package.BUILD.bazel` line 36 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17230#-N438H7Q9pcjnzjTExPr:-N438H7Q9pcjnzjTExPs:blblo0c) ([raw file](https://github.com/robotlocomotion/drake/blob/2588da64495e1aa8feaf5d3cb15d51d5a90736c5/tools/workspace/gz_utils_internal/package.BUILD.bazel#L36)):*
> ```
>         "PROJECT_VERSION_PATCH=0",
>         "PROJECT_VERSION=0.0",
>         "PROJECT_VERSION_FULL=0.0.0",
> ```

BTW consider same comment here -- why all these zeros?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17230)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[`tools/workspace/gz_math_internal/package.BUILD.bazel` line 42 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17230#-N437IJ3EDG6_-qvA-EM:-N43G2Hi85nu5vlU8lUD:b-g8g9qm) ([raw file](https://github.com/robotlocomotion/drake/blob/2588da64495e1aa8feaf5d3cb15d51d5a90736c5/tools/workspace/gz_math_internal/package.BUILD.bazel#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I gather the version numbers don't matter anymore but it isn't clear why. Consider adding a comment to explain why (a) they don't matter, and (b) why we have to define them at all.
</blockquote></details>

Using zeros here is actually the typical convention (see below).  Basically, no C++ code does anything with these definitions, so their value doesn't matter and it's easier to perform upgrades when we don't need to keep this information in sync.  The fact that these used to have real version numbers was vestigial from when we shipped this code as a shared library.

```
tools/workspace/fcl/package.BUILD.bazel:61: "OCTOMAP_MAJOR_VERSION=0",
tools/workspace/fcl/package.BUILD.bazel:62: "OCTOMAP_MINOR_VERSION=0",
tools/workspace/fcl/package.BUILD.bazel:63: "OCTOMAP_PATCH_VERSION=0",
tools/workspace/libcmaes/package.BUILD.bazel:34: "LIBCMAES_VERSION_STRING=0.0.0",
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17230)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
