### PR TITLE
Python bind RigidTransform::GetMaximumAbsoluteTranslationalDifference, etc.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18173)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR #18173 resolves issue #18071.

**Review by mitiguy — COMMENTED** [review]
Feature review +@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18173#-:-NFBmy393mJVNJyyoXLu:b-59nlc1)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) LGTM feature and platform, modulo some nits.

I double-checked that all of `RigidTransform` API is bound now.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18173#-:-NFBpPem-yqNNggL5eaO:bgs1prw)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @mitiguy)

___
*[`bindings/pydrake/math_py.cc` line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18173#-NFBoRmz1bjafyQL3HKT:-NFBoRn-6jIArWELngKk:bggymad) ([raw file](https://github.com/robotlocomotion/drake/blob/fca85b9a416cec3dc0e0d9c3c8c2c69e97eb036e/bindings/pydrake/math_py.cc#L124)):*
> ```cpp
>         .def("GetMaximumAbsoluteTranslationDifference",
>             &Class::GetMaximumAbsoluteTranslationDifference, py::arg("other"),
>             cls_doc.GetMaximumAbsoluteTranslationDifference.doc)
> ```

nit Broadly, the order of Python function bindings should match the order of functions declarations in the class's C++ header file.  That makes it easier for a Drake developer to help match up the C++ code with the Python code.

For cases like `operator*` (C++) vs `"multiply"` (Python), I think it's OK to allow things to be out of order by placing "multiply" at the end (since overloading the multiplication operator is special business), but here some of the newly-bound non-operator functions are not in order.  (Even prior to this PR, some of the functions were imperfectly ordered.)

To resolve this, it's OK to adjust either the Python order and/or the C++ header order (in case the C++ order is aesthetically "wrong").
___
*[`bindings/pydrake/math_py.cc` line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18173#-NFBpkp-EJmKQ_uN0Yum:-NFBpkp0DK6303jZscTR:bpryxnh) ([raw file](https://github.com/robotlocomotion/drake/blob/fca85b9a416cec3dc0e0d9c3c8c2c69e97eb036e/bindings/pydrake/math_py.cc#L157)):*
> ```cpp
>     DefCast<T>(&cls, cls_doc.cast.doc);
>     // .def("IsNearlyEqualTo", ...)
>     // .def("IsExactlyEqualTo", ...)
> ```

nit Remove these vestigial comments now.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18173#-:-NFGVVW2A93xScX_meO5:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
