### PR TITLE
[workspace] Upgrade curl_internal to latest release 7.86.0

### LINKED ISSUE #18232: Upgrade externals to latest - November 2022
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #18023

- #18244 
- #17910. Related, usockets cannot be updated without updating uwebsockets (link to error [here](https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1646951)).

```
In file included from geometry/meshcat.cc:21:
external/uwebsockets/src/App.h:89:5: error: static_assert failed due to requirement 'sizeof(us_socket_context_options_t) == sizeof(uWS::SocketContextOptions)' "Mismatching uSockets/uWebSockets ABI"
    static_assert(sizeof(struct us_socket_context_options_t) == sizeof(SocketContextOptions), "Mismatching uSockets/uWebSockets ABI");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
```

- curl_internal still working

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18232.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18285)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for feature review, please.

**Review by BetsyMcPhail — COMMENTED** [review]
Thanks for finishing this up. :lgtm: assuming CI is happy.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18285#-:-NGSenP961w-LOnyn1t9:b-m4l8pq)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please (tomorrow).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18285#-:-NGY1t3PBFN5-mel-RY5:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),BetsyMcPhail (waiting on @jwnimmer-tri)

**Pull request merged**
