### PR TITLE
geometry:optimization: Add Point isa ConvexSet

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
Contains PR #15286 .  Please review only the second commit.
+@hongkai-dai for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302#-:-MdZLSbW3FiihnKIIwG0:bww1te5)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
cc @tobiamarcucci 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302#-:-MdZMM0u-fLn83Qe2O0D:b-4fk4qb)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @RussTedrake)

___
*[geometry/optimization/point.cc, line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdZggIY7P_l_t8KIqRg:-MdZggIZ3BFB3z0aNvZg:b-gwabhz) ([raw file](https://github.com/robotlocomotion/drake/blob/44b196884f02341289f1dcb31f6455c4f726bbb5/geometry/optimization/point.cc#L65)):*
> ```cpp
>   constraints.emplace_back(prog->AddLinearEqualityConstraint(
>       Aeq, VectorXd::Zero(n), {x, Vector1<Variable>(t)}));
>   return constraints;
> ```

Also need the constraint that t >= 0?
___
*[geometry/optimization/test/point_test.cc, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdZfEOg8Z1evYhuhA-4:-MdZfEOg8Z1evYhuhA-5:b-d1l78c) ([raw file](https://github.com/robotlocomotion/drake/blob/44b196884f02341289f1dcb31f6455c4f726bbb5/geometry/optimization/test/point_test.cc#L38)):*
> ```cpp
>   EXPECT_TRUE(P.PointInSet(p_W));
>   EXPECT_FALSE(P.PointInSet(p_W + Vector3d::Constant(0.01)));
>   EXPECT_TRUE(P.PointInSet(p_W + Vector3d::Constant(0.01), 0.01 + 1e-16));
> ```

This doesn't look right to me. The distance between p_W + Vector3d::Constant(0.01) and p_W is not 0.01, but sqrt(0.0003), approximately 0.0173. Are we using infinity norm instead of 2 norm here to measure the point distance? If so I would think we need to document the behavior of `Point::DoPointInSet`.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[geometry/optimization/point.cc, line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdZggIY7P_l_t8KIqRg:-Md_7Qpp7mfBw08UK1nb:b-p6ul8q) ([raw file](https://github.com/robotlocomotion/drake/blob/44b196884f02341289f1dcb31f6455c4f726bbb5/geometry/optimization/point.cc#L65)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Also need the constraint that t >= 0?
</blockquote></details>

This is implemented in the NVI (and confirmed via the test)
___
*[geometry/optimization/test/point_test.cc, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdZfEOg8Z1evYhuhA-4:-Md_7V40BudANCcRwnp7:b-g1yvf5) ([raw file](https://github.com/robotlocomotion/drake/blob/44b196884f02341289f1dcb31f6455c4f726bbb5/geometry/optimization/test/point_test.cc#L38)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This doesn't look right to me. The distance between p_W + Vector3d::Constant(0.01) and p_W is not 0.01, but sqrt(0.0003), approximately 0.0173. Are we using infinity norm instead of 2 norm here to measure the point distance? If so I would think we need to document the behavior of `Point::DoPointInSet`.
</blockquote></details>

Done.  I've added documentation in the header.  (yes, it's using the abstol method).

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@soonho-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302#-:-Md_8pMc2wyTvPTaTQ3I:b-fstt78)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

___
*[geometry/optimization/point.cc, line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdZggIY7P_l_t8KIqRg:-Md_8afA45MLswaskXz7:be6sz78) ([raw file](https://github.com/robotlocomotion/drake/blob/44b196884f02341289f1dcb31f6455c4f726bbb5/geometry/optimization/point.cc#L65)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This is implemented in the NVI (and confirmed via the test)
</blockquote></details>

I see, my local check out uses an old version of master, which did not contain the t>= 0 constraint in the NVI.

**Review by soonho-tri — COMMENTED** [review]
:lgtm: PTAL my comments.

> Reviewed 4 of 10 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302#-:-MdbiQtI33rYyXAXrxyy:blxwjd4)* status: 8 unresolved discussions (waiting on @RussTedrake)

___
*[geometry/optimization/point.h, line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbE2Mm3l_Ng35T8qe-:-MdbE2Mn2xYNGAHszanL:bl0mmwb) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L27)):*
> ```objc
>   frame is std::nullopt, then it will be expressed in the world frame.
> 
>   @throws std::exception if geometry_id does not correspond to a Sphere or iif
> ```

nit, `iif` => `if`?
___
*[geometry/optimization/point.h, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbHaVb0j_P7gQa_Xbh:-MdbHaVc39ZTxQZXI4oE:b7j0j25) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L28)):*
> ```objc
> 
>   @throws std::exception if geometry_id does not correspond to a Sphere or iif
>   the Sphere has radius greater than @p maximum_allowable_radius. */
> ```

In `.cc`, we use `DRAKE_DEMAND` to check this condition, but this sentence is in `@throws` section.
___
*[geometry/optimization/point.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbHTez6NbAE_mh9yS6:-MdbHTez6NbAE_mh9yS7:bcqtoju) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L36)):*
> ```objc
> 
>   /** Returns true if the point is within @p tol of x(), under the L∞-norm. */
>   using ConvexSet::PointInSet;
> ```

nit, is this `using` statement necessary? (for documentation purpose?)
___
*[geometry/optimization/point.h, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbHZpP2etVMg_rFvJ7:-MdbHZpP2etVMg_rFvJ8:bqyrsp) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L59)):*
> ```objc
> 
>   // Implement support shapes for the ShapeReifier interface.
>   using ShapeReifier::ImplementGeometry;
> ```

nit, is this `using` statement necessary?
___
*[geometry/optimization/point.cc, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbhb-88KGsHE2tns0Z:-Mdbhb-88KGsHE2tns0_:b-8lp6pr) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L3)):*
> ```cpp
> #include "drake/geometry/optimization/point.h"
> 
> #include <limits>
> ```

nit, unused?
___
*[geometry/optimization/point.cc, line 6 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbhc1X-gy3nLv2XiDl:-Mdbhc1X-gy3nLv2XiDm:b-hmmmdn) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L6)):*
> ```cpp
> #include <memory>
> 
> #include <Eigen/Eigenvalues>
> ```

nit, both `Eigen/Eigenvalues` and `fmt/format.h` are unused?
___
*[geometry/optimization/point.cc, line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbFRGI9s2HVmVUgL8H:-MdbFRGI9s2HVmVUgL8I:biu5n4m) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L39)):*
> ```cpp
>                                    ? query_object.GetPoseInWorld(*expressed_in)
>                                    : RigidTransformd::Identity();
>   const RigidTransformd X_WG = query_object.GetPoseInWorld(geometry_id);
> ```

`const RigidTransformd X_WG` => `const RigidTransformd& X_WG` as `GetPoseInWorld` returns a const ref.
___
*[geometry/optimization/point.cc, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbez_iAsc_zs-d8gap:-Mdbez_iAsc_zs-d8gaq:b8xba9b) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L80)):*
> ```cpp
> 
> void Point::ImplementGeometry(const Sphere& sphere, void* data) {
>   double* radius = reinterpret_cast<double*>(data);
> ```

For `void*` => `T*`, I think we should prefer `static_cast<T*>`.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302)* status: 5 unresolved discussions (waiting on @soonho-tri)

___
*[geometry/optimization/point.h, line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbE2Mm3l_Ng35T8qe-:-Mdc9IYK6jpRe66yYg7l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L27)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `iif` => `if`?
</blockquote></details>

Done.
___
*[geometry/optimization/point.h, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbHaVb0j_P7gQa_Xbh:-Mdc9JQz0IDy3NJgCGnx:b3ymga9) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

In `.cc`, we use `DRAKE_DEMAND` to check this condition, but this sentence is in `@throws` section.
</blockquote></details>

Done.  (it now throws, and I confirm with a test).
___
*[geometry/optimization/point.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbHTez6NbAE_mh9yS6:-Mdc9Nlk0DLKPHaxTjx6:b-u8vnow) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L36)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, is this `using` statement necessary? (for documentation purpose?)
</blockquote></details>

yes.  for documentation purposes.
___
*[geometry/optimization/point.h, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbHZpP2etVMg_rFvJ7:-Mdc9R5T0yb-R9pisl9Q:b-5z2utm) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.h#L59)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, is this `using` statement necessary?
</blockquote></details>

yes.  i need to import the default implementations of the reifier for the overloads that I don't implement here.
___
*[geometry/optimization/point.cc, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbhb-88KGsHE2tns0Z:-Mdc9YOd67LXbXm_UyMc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, unused?
</blockquote></details>

Done.
___
*[geometry/optimization/point.cc, line 6 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbhc1X-gy3nLv2XiDl:-Mdc9_4w8stNhBIPGq0W:b9cz9wz) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L6)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, both `Eigen/Eigenvalues` and `fmt/format.h` are unused?
</blockquote></details>

Done.  (but fmt is used now)
___
*[geometry/optimization/point.cc, line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-MdbFRGI9s2HVmVUgL8H:-MdcAJLn70OwbgfjTdAl:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L39)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`const RigidTransformd X_WG` => `const RigidTransformd& X_WG` as `GetPoseInWorld` returns a const ref.
</blockquote></details>

Done.  
___
*[geometry/optimization/point.cc, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbez_iAsc_zs-d8gap:-MdcB5uD2fWIGW7gUtlO:b-xxi2n2) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L80)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

For `void*` => `T*`, I think we should prefer `static_cast<T*>`.
</blockquote></details>

Done.  But the use of reinterpret_cast is recommended explicitly in the documentation.   Is that a defect?  https://github.com/RobotLocomotion/drake/blob/master/geometry/shape_specification.h#L351

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15302)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @RussTedrake)

___
*[geometry/optimization/point.cc, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15302#-Mdbez_iAsc_zs-d8gap:-MdcHvTYBmmZOQV3XYr9:b1tlt4r) ([raw file](https://github.com/robotlocomotion/drake/blob/bf55c4550be9a1a99734b87cdf1b31575f55e11b/geometry/optimization/point.cc#L80)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  But the use of reinterpret_cast is recommended explicitly in the documentation.   Is that a defect?  https://github.com/RobotLocomotion/drake/blob/master/geometry/shape_specification.h#L351
</blockquote></details>

OK. I'll bring this question to the `#cpp` channel in Slack.

**Pull request merged**
