### PR TITLE
SetSolverId can only be called in MathematicalProgramSolverInterface

### PR DESCRIPTION
**Pull request by hongkai-dai**
Reopens #8193

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8229)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-:-L6coJduxiWF0QL_DHql:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.
Have you passed this by @jwnimmer-tri, regarding plans to seal future methods?

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dovov_v2h98FIsA-w:-L6dovowKp2xQ56nNkjB:b-lg8s7r) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program.h#L2119)):*
> ```objc
>   /**
>    * Sets the ID of the solver that was used to solve this program.
>    * @Note This method is only meant to be called by the solver, as a child
> ```

BTW `@Note` is a doxygen directive, so it should be `@note`

---

*[solvers/mathematical_program.h, line 2126 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dp-uCZLL8OfAIWh-b:-L6dp-uDsMMP_gsRjTm-:b6ekx4h) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program.h#L2126)):*
> ```objc
>    * \endcode
>    *
>    * We use passkey idiom to restrict that this function can only be called
> ```

BTW grammar nit "We use **the** pass-key idiom [...]"

---

*[solvers/mathematical_program.h, line 2127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dp5wCNtG3EJn9ZnJk:-L6dp5wDqgndG7XEvFZz:bwrl2ox) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program.h#L2127)):*
> ```objc
>    *
>    * We use passkey idiom to restrict that this function can only be called
>    * inside MathematicalProgramSolverInterface. Notice that MathematicalProgramKey 
> ```

BTW Trailing whitespace

---

*[solvers/mathematical_program_solver_interface.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dpGeF4G4E-uunlfmU:-L6dpGeGUCC9hicpjLyd:b-ufkmyb) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program_solver_interface.h#L26)):*
> ```objc
> };
> 
> /**
> ```

Rather than put this key here, can you put this in `mathematical_program.h`?

And possibly scope the key, call it `MathematicalProgram::PassKey`, since `Key` is rather generic (and may be confusing at some poitn).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-:-L6dpnBOvbIpx1rzAcuF:b8uh9e)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review please.

I think instead of renaming the function, we can prevent the user from calling the function using the passkey idiom.

---

Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dovov_v2h98FIsA-w:-L6hAmwKSmZBZ6opVUqT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program.h#L2119)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW `@Note` is a doxygen directive, so it should be `@note`
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2126 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dp-uCZLL8OfAIWh-b:-L6hApcyzvctksi1sdzf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program.h#L2126)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW grammar nit "We use **the** pass-key idiom [...]"
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dp5wCNtG3EJn9ZnJk:-L6hAsirtKf9gdBwZ2sN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program.h#L2127)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Trailing whitespace
</blockquote></details>

Done.

---

*[solvers/mathematical_program_solver_interface.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-L6dpGeF4G4E-uunlfmU:-L6hB1vEKA4EXfWQmcMy:b9ujazf) ([raw file](https://github.com/robotlocomotion/drake/blob/16f207d7840b793a20c1a8a257cc453ab029f0f1/solvers/mathematical_program_solver_interface.h#L26)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Rather than put this key here, can you put this in `mathematical_program.h`?

And possibly scope the key, call it `MathematicalProgram::PassKey`, since `Key` is rather generic (and may be confusing at some poitn).
</blockquote></details>

But this key should be created in `mathematical_program_solver_interface.h`, which does not include `mathematical_program.h`.

I think this key is used by `MathematicalProgramSolverInterface`, so it can live in `mathematical_program_solver_interface.h`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-:-L6hBV6BlP9JeyWr5gkE:bv8l663)*

**Comment by jwnimmer-tri** [comment]
So the proposal is to put the passkey warts on every single callback method?  What is the thought process behind that solution vs my proposal of a callback interface that groups them all together?

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-:-L6m0bZG8RU6PLYCI6tA:bxq7img)*

**Comment by hongkai-dai** [comment]
@jwnimmer-tri . Sorry I didn't realize that you mean to group all them together. 

Currently we only return the solver ID from `MathematicalProgramSolverInterface` to `MathematicalProgram`. The other data are not guaranteed to be returned (such as the solution, which is only returned upon successful solve). So I do not think we have much use case on grouping them? And I <i> think </i> if we have more data to return, whether they will be returned, depends on how the solution runs (like returning warm-starting information). On the other hand, the solver ID is <b> always </b> returned, so may we should treat it separately?

I use the pass-key idiom to guarantee that the `SetSolverId` function (or `GetSolverReportResult` function, if we decide to group them) can only be called by `MathematicalProgramSolverInterface`, and the user cannot call this function. Do you think this is a valid concern? @pangtao22 has mistakenly called `SetSolverId`, assuming it specifies which solver to be used, rather than which solver has been used. So I want to make sure the user can't call this function at all, by using the pass-key idiom.

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8229#-:-L6r2PVqabPeNljzbEdF:b-a8gtxy)*

**Comment by jwnimmer-tri** [comment]
Aren't all of the following methods only intended to be called by a solver (or something pretending to be a solver)?
- SetDecisionVariableValues (x2)
- SetDecisionVariableValue
- SetSolverId
- SetOptimalCost
- SetLowerBoundCost
- GetSolverData

It seems like the intent to guard them from the user of MP seems equally strong as for SetSolverId on its own, and grouping them into a unified callback interface (even if only certain solvers call a subset of them) seems vastly superior to my judgement.  It also is one more step on decoupling MP from the solvers suite, so that users can add new solvers in downstream code, and so that we could for-example use a plug-in architecture for solver back-ends.

**Comment by jwnimmer-tri** [comment]
Proposal:

```c++
// Solvers use this to report their results back to the MathematicalProgram problem.
class MathematicalProgramResultReportingInterface {
 public:
  ~MathematicalProgramResultReportingInterface();
  virtual void SetSolverId(SolverId) = 0;
  // ... also SetOptimalCost ... etc.
};

class MathematicalProgram
  : private MathematicalProgramResultReportingInterface {
 public:
  MathematicalProgramResultReportingInterface* GetResultReportingInterface() {
    return this;
  }
 private:
  void SetSolverId(SolverId solver_id) override { solver_id_ = solver_id; }
}

MySolver::Solve() {
  // ...
  prog.GetResultReportingInterface()->SetSolverId(id());
}
```

**Pull request closed without merging**
