### PR TITLE
Add a tutorial on quadratic program.

### PR DESCRIPTION
**Pull request by hongkai-dai**
nbviewer Preview: https://nbviewer.jupyter.org/github/hongkai-dai/drake/tree/qp_tutorial/tutorials/

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403#-:-MNZ7ltcBl8vKS45biTu:b-8hqkno)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Sweet!

FYI I added a preview link to your overview.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403#-:-MNaLwOyDEktvuF8N1nU:bd7h85)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403#-:-MNaNGiz9XPa6UuSok8r:b-uwkowd)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaNIrD8D3-GomF2CZ0:-MNaNIrD8D3-GomF2CZ1:bol4967) (no related file):*
nit While readers can find links to Wikipedia / search the codebase, it may still be good to reference (slightly nontrivial) applications within Drake that use a QP solver.

Perhaps refer to Diff IK?
https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1manipulation_1_1planner.html#ab53fd2e1578db60ceb43b754671ae539

(briefly tried to find nontrivial, non-test examples in Drake, but couldn't find any pure QP's easily...)

---
___
*[tutorials/mathematical_program.ipynb, line 563 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaMDaOEh0dDwxXfh9Y:-MNaMDaOEh0dDwxXfh9Z:b-2t7okw) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/mathematical_program.ipynb#L563)):*
> ```
>     "[Linear program](./linear_program.ipynb)\n",
>     "\n",
>     "[Quadratic program](./quadratic_program.ipynb)\n",
> ```

FYI Confirmed this link works from `nbviewer`.
___
*[tutorials/quadratic_program.ipynb, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaMNow9YCz0azrFEMz:-MNaMNow9YCz0azrFEN-:b-plixmr) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/quadratic_program.ipynb#L24)):*
> ```
>    "metadata": {},
>    "source": [
>     "A (convex) quadratic program (QP) is a special type of convex optimization. Its cost function is a convex quadratic function. Its constraints are linear, same as the constraints in linear program. A (convex) quadratic program has the following form\n",
> ```

nit While this is probably a widely known thing, it'd still be good to somehow mention it in an external reference.

Below, when you refer to Doxygen, can you also state that the "QP" link refers to useful stuff?

e.g. "of supported solvers, and relevant reading material"?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaNIrD8D3-GomF2CZ0:-MNaOha-0oNk-NaUJyLU:b-mzqi70) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit While readers can find links to Wikipedia / search the codebase, it may still be good to reference (slightly nontrivial) applications within Drake that use a QP solver.

Perhaps refer to Diff IK?
https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1manipulation_1_1planner.html#ab53fd2e1578db60ceb43b754671ae539

(briefly tried to find nontrivial, non-test examples in Drake, but couldn't find any pure QP's easily...)
</blockquote></details>

And mayhaps references to Underactuated / Manipulation?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ggould-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403#-:-MNaOsYEEIfLlned1NvM:bcav8qn)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; a really nice addition to our docs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403#-:-MNclt6i3NdjVy31KESw:b-cse2th)* status: 5 unresolved discussions (waiting on @hongkai-dai)

___
*[tutorials/mathematical_program.ipynb, line 563 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaMDaOEh0dDwxXfh9Y:-MNckGcZ8Xy7l-Kemqbw:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/mathematical_program.ipynb#L563)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Confirmed this link works from `nbviewer`.
</blockquote></details>

Thanks!
___
*[tutorials/quadratic_program.ipynb, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNckZpNC8E-QwXUN8we:-MNckZpNC8E-QwXUN8wf:b1dxulg) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/quadratic_program.ipynb#L39)):*
> ```
>     "### AddQuadraticCost function\n",
>     "\n",
>     "The easist way to add a quadratic cost is to call `AddQuadraticCost` function. In the following code snippet, we first construct a program with 2 decision variables, and then show how to call `AddQuadraticCost` function."
> ```

minor: Grammar:  In both instances here, "call `AddQuadraticCost` function" needs a "the".
___
*[tutorials/quadratic_program.ipynb, line 101 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNclDU6EqW5xEC6BPX2:-MNclDU6EqW5xEC6BPX3:b8p3jzr) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/quadratic_program.ipynb#L101)):*
> ```
>    "metadata": {},
>    "source": [
>     "If you know the coefficient of the quadratic cost `Q, b, c`, you could also add the cost without using the symbolic expression, as shown in the following code snippet"
> ```

minor: Grammar:  "Coefficient" -> "coefficients"
___
*[tutorials/quadratic_program.ipynb, line 167 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNclS7U0Cj_VCHmOiQQ:-MNclS7U0Cj_VCHmOiQR:b7c1zbw) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/quadratic_program.ipynb#L167)):*
> ```
>     "## Add linear cost\n",
>     "\n",
>     "You could also add linear costs to quadratic program. For an introduction on the different APIs on adding linear cost, please refer to our [linear programming tutorial](./linear_program.ipynb). Here is an example"
> ```

minor: Grammar: "to quadratic program" -> "to  quadratic program" ;  "adding linear cost" -> "adding a linear cost" OR "adding linear costs".

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14403)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaNIrD8D3-GomF2CZ0:-MNdFyuD8sSsqywEx5gY:bsd0qy5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

And mayhaps references to Underactuated / Manipulation?
</blockquote></details>

Done, added links to diffIK and underactuated github repo

---
___
*[tutorials/quadratic_program.ipynb, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14403#-MNaMNow9YCz0azrFEMz:-MNdGsWM3EIm-o3PWBfV:bnemwiu) ([raw file](https://github.com/robotlocomotion/drake/blob/4af82cb834bf8cadb19512eded58ee3543be362a/tutorials/quadratic_program.ipynb#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit While this is probably a widely known thing, it'd still be good to somehow mention it in an external reference.

Below, when you refer to Doxygen, can you also state that the "QP" link refers to useful stuff?

e.g. "of supported solvers, and relevant reading material"?
</blockquote></details>

Done. I added some reading materials in the last cell.

I didn't add the link in this cell, since our form of QP is slightly different from many others (we include a constant term in the cost function).

**Pull request merged**
