### PR TITLE
[tutorials] Fix title of hydroelastic tutorial

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19583)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

Notify @zachfang

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19583#-:-NXpI8Z9DqOYgEYZJbWU:b-lmgkvn)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19583#-:-NXpMOIu5fwUMJRnKDX5:b3dcro0)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19583#-NXpIT4j3K1A0j0byokD:-NXpMLWf3uubmTAsr_I-:bazytf8) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I wasn't sure about the release notes tag. Please feel free to change it to `release notes: none`.
</blockquote></details>

+(release notes: none) -(release notes: fix) 

___
___
*[`tutorials/hydroelastic_basics.ipynb` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19583#-NXpLsKP1oNcIL_OyRFv:-NXpLsKP1oNcIL_OyRFw:bxmh0jx) ([raw file](https://github.com/RobotLocomotion/drake/blob/27b2679864cca5dc4ead885f60ca4f4c323f1e96/tutorials/hydroelastic_basics.ipynb#L7)):*
> ```
>    "metadata": {},
>    "source": [
>     "# Hydroelastic Contact: Basics\n",
> ```

Given this new title, I would expect the filename to be `hydroelastic_contact_basics.ipynb`.  Is there a good reason to break the pattern?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19583)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`tutorials/hydroelastic_basics.ipynb` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19583#-NXpLsKP1oNcIL_OyRFv:-NXpTPrc5IgyLaP7nCvW:b-soil4a) ([raw file](https://github.com/RobotLocomotion/drake/blob/27b2679864cca5dc4ead885f60ca4f4c323f1e96/tutorials/hydroelastic_basics.ipynb#L7)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Will do. Set to working.
</blockquote></details>

Done.  Thanks.

BTW, perhaps we should update (in another PR) _developers.md to say the title of the tutorial and the file name should be the same?

**Comment by DamrongGuoy** [comment]
*[`tutorials/hydroelastic_basics.ipynb` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19583#-NXpLsKP1oNcIL_OyRFv:-NXpXsCn8yJz0_zBhLDO:b-eq9z32) ([raw file](https://github.com/RobotLocomotion/drake/blob/27b2679864cca5dc4ead885f60ca4f4c323f1e96/tutorials/hydroelastic_basics.ipynb#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

A coding standard can't encompass every mistake that authors might make.  There is a real cost (in developer overhead) to writing down new rules -- for authors to learn them, and for reviewers to cross-check them. Sometimes, we just need to rely on common sense and call it good enough.

(If we cared strongly, we could add a rule to our tutorials linter to cross-check it, not a style guide change.)
</blockquote></details>

I agree that we don't want overhead. Thanks.

**Pull request merged**
