### PR TITLE
Added style guide clarification to "use of const" rule.

### PR DESCRIPTION
**Pull request by liangfok**
For context, see: https://reviewable.io/reviews/robotlocomotion/drake/3643#-KTCS6cxqqxTRsQNMSI1

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3689)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3689#-:-KTL5D0-IpVpoSsb0F_h:bnfp4nl)*

**Comment by david-german-tri** [comment]
(and by :lgtm: I mean that I agree this should be a rule)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3689#-:-KTL5GgWpY5iHqWUR1uz:bsdbxf7)*

**Comment by liangfok** [comment]
Strange! When I created this PR, I selected labels "priority: low" and "type: documentation". However, it initially showed up as "configuration: linux" and "configuration: mac".

**Comment by jwnimmer-tri** [comment]
:lgtm: though you should probably seek any dissenting opinions; David and I are hivemind on this one.

Also pleasea add the PR number into the document before merging, as usual.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3689#-:-KTL673c4QYBSOEw-QwH:b-ssccoz)*

**Comment by liangfok** [comment]
Done. I posted a plea for comments on the DrakeDeveloper's #general Slack channel.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3689#-:-KTL79GE_94Wob3YOhmN:b-34po1a)*

**Comment by sherm1** [comment]
:lgtm: too -- can I join the hive?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3689#-:-KTL7W_G3cOcESapVqSN:blokt7a)*

**Comment by liangfok** [comment]
-@liangfok 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3689#-:-KTLG4Kp452nCM30tHcx:b-5dj57h)*

**Pull request merged**
