### PR TITLE
[workspace] Add private curl build from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This solves the problem of what curl to use for full builds vs wheel builds.

Deprecate the libcurl repository rule.
No longer require host-installed curl during setup.

Towards #15915 and related to #17697.

Requires #17747.

\CC @zachfang FYI

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/cmake_configure_file.py` line 132 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17755#-NAGcUN71S5K4Pb0qQmG:-NAGcUN71S5K4Pb0qQmH:b8n3y50) ([raw file](https://github.com/robotlocomotion/drake/blob/fd60c0184d5b35e4041fe4a4977aac36ed37c759/tools/workspace/cmake_configure_file.py#L132)):*
> ```Python
>             result[key] = value
>         else:
>             result[item] = '1'
> ```

FYI This fixes a corner-case error:

```
cmake_configure_file.py", line 93, in _transform
    line = before + value + after + newline
TypeError: can only concatenate str (not "int") to str
```

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @svenevs @zachfang FYI

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
Looks good so far. Mac linking is still sad.

> Reviewed 12 of 18 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755#-:-NAKjvgQ724P4EvrXPfB:b-1l9k4a)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tools/workspace/cmake_configure_file.py` line 122 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17755#-NAKgQaT0jJZboLdmSwG:-NAKgQaUDLdeKniunuRd:bovwlcw) ([raw file](https://github.com/robotlocomotion/drake/blob/fd60c0184d5b35e4041fe4a4977aac36ed37c759/tools/workspace/cmake_configure_file.py#L122)):*
> ```Python
> 
> # Load our definitions dict, given the command-line args:
> # - A command-line '-Dfoo' will add ('foo', 1) to the result.
> ```

nit Given the change below, should this doc get updated to match?



_Suggestion:_
```Python
('foo', '1')
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755#-:-NAL7h1VAYAdGDOKU2k7:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.  OK to wait until next week if you like.

**Comment by jwnimmer-tri** [comment]
@sammy-tri ping

**Review by rpoyner-tri — COMMENTED** [review]
Sam had to split this afternoon. Since I'm on-call on Tuesday I would pick this up but I already read it. Maybe try Sean if you think that works?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755#-:-NAuf1350j6C6VP8kLT5:b-sogtla)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 18 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17755#-:-NBJcgwD7sRqEyso6UIT:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/curl_internal/cmakedefines.bzl` line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17755#-NBJby_GBp7aW5Jc3mur:-NBJby_GBp7aW5Jc3mus:bk488jz) ([raw file](https://github.com/robotlocomotion/drake/blob/71e702df8e95321607047f02d71395d9d4472e57/tools/workspace/curl_internal/cmakedefines.bzl#L9)):*
> ```Starlark
> # In our package.BUILD.bazel we invoke the cmake_configure_file() bazel macro
> # in strict mode using these definitions, which means that any missing or
> # extra definitions here will result in a build failure.
> ```

BTW I did not manually read this entire file to make sure the definitions appeared sane, instead relying mostly on the fail-fast promise above to at least catch totally bogus items.

**Pull request merged**
