### PR TITLE
Add gflags as a required dependency

### LINKED ISSUE #3027: Add gflags as a required external dependency and make use of it in Drake's executables
One of the first places to use it would be in `drake-distro/drake/examples/Cars/car_simulation.cc`.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add gflags as a required dependency, along with a sample use (in the only non-example program that used drakeAppUtil).

Fixes #3027.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3183)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Tagging DNM, because I should get some post-merge builds tested here as well before we push this into master.

**Comment by david-german-tri** [comment]
+@david-german-tri (I'd like to review this due to prior experience with gflags)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPSgI5GPZhLlGcHEvGk:b-d049x7)*

**Comment by david-german-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPSgaCZ1CMLdRx95UIZ:-KPSgaCZ1CMLdRx95UI_:b6dw7q4) ([raw file](https://github.com/robotlocomotion/drake/blob/d1edd5d255d799e25982d46bb087ee1389ab8008/drake/doc/developers.rst#L82)):*
> ```reStructuredText
> the superbuild. This is configured by turning off all externals using
> ``ccmake`` or ``cmake-gui`` except for ``WITH_EIGEN``, ``WITH_GOOGLETEST``,
> and  ``WITH_GFLAGS``, which should be set to ``ON``.
> ```

You're gonna need a drake-ci change.  I think the conventional approach here is to add the repo and option in one PR to drake, then set the option in a PR to drake-ci, then start using the option in another PR to drake?  @jamiesnape to confirm

---

*[drake/systems/plants/rigidBodyLCMNode.cpp, line 52 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPShArNYBgRAp1bdz6d:-KPShArNYBgRAp1bdz6e:bq2q40j) ([raw file](https://github.com/robotlocomotion/drake/blob/d1edd5d255d799e25982d46bb087ee1389ab8008/drake/systems/plants/rigidBodyLCMNode.cpp#L52)):*
> ```cpp
>   } else if (FLAGS_base == "RPY") {
>     floating_base_type = DrakeJoint::ROLLPITCHYAW;
>     std::cout << "base RPY";
> ```

Was this just for debugging purposes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by david-german-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by jamiesnape** [comment]
I can add the option in advance. Enabled for all builds?

**Comment by david-german-tri** [comment]
> I can add the option in advance. 

Oh - great!

> Enabled for all builds?

That's my understanding.

**Comment by jwnimmer-tri** [comment]
> I can add the option in advance.

Great!  Though I want to get a +1 from a reviewer that the `WITH_` chosen name here is an acceptable spelling.

> Enabled for all builds?

Yes, unless a reviewer asks me to make it optional (stubbed).

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPSgaCZ1CMLdRx95UIZ:-KPStLES1k19WGbwfe2N:b-1bwosi) ([raw file](https://github.com/robotlocomotion/drake/blob/d1edd5d255d799e25982d46bb087ee1389ab8008/drake/doc/developers.rst#L82)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> You're gonna need a drake-ci change.  I think the conventional approach here is to add the repo and option in one PR to drake, then set the option in a PR to drake-ci, then start using the option in another PR to drake?  @jamiesnape to confirm
</details>
But it defaults to `ON`, which is the correct answer in all cases; why should `drake-ci` need to care about that any more than a random developer would?

---

*[drake/systems/plants/rigidBodyLCMNode.cpp, line 52 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPShArNYBgRAp1bdz6d:-KPStW6z1VApDRscV88y:bhmzuca) ([raw file](https://github.com/robotlocomotion/drake/blob/d1edd5d255d799e25982d46bb087ee1389ab8008/drake/systems/plants/rigidBodyLCMNode.cpp#L52)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Was this just for debugging purposes?
</details>
Yes, oops, that snuck into the commit.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by jamiesnape** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPSgaCZ1CMLdRx95UIZ:-KPSw5xtMNQC8Wdvppa9:bghwcpr) ([raw file](https://github.com/robotlocomotion/drake/blob/d1edd5d255d799e25982d46bb087ee1389ab8008/drake/doc/developers.rst#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> But it defaults to `ON`, which is the correct answer in all cases; why should `drake-ci` need to care about that any more than a random developer would?
</details>
Not in all cases on CI, though. We do not build drake and its externals on cpplint builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/developers.rst, line 82 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPSgaCZ1CMLdRx95UIZ:-KPSx83FwlzbdXTFDxjl:b-mjh5x4) ([raw file](https://github.com/robotlocomotion/drake/blob/d1edd5d255d799e25982d46bb087ee1389ab8008/drake/doc/developers.rst#L82)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Not in all cases on CI, though. We do not build drake and its externals on cpplint builds.
</details>
Good point!  So we'd be passing, but have wasteful / undesirable build artifacts.  A good reason to fix `drake-ci` promptly, but we don't need to interlock the PRs it seems.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by jwnimmer-tri** [comment]
@jamiesnape or @mwoehlke-kitware, could I ask one of you to self-assign here and review the CMake / superbuild bits for me?  Thank you in advance!

**Comment by mwoehlke-kitware** [comment]
Oh, joy, #3186 conflicts...

> I want to get a +1 from a reviewer that the `WITH_` chosen name here is an acceptable spelling.

It isn't "just acceptable", it's as it *must* be. The `WITH_<NAME>` option shall have `<NAME>` be the upper-case of the name of the external as given to `drake_add_external`. (Otherwise the test whether to enable the external won't find the option.)

---

Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 138 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPTF_1mVGMZhhSZNz63:-KPTF_1ygMTKYRs5qtmf:bn55dvh) ([raw file](https://github.com/robotlocomotion/drake/blob/035cbf7e28f5e2f54a0306322fbbbd4623b32e8d/CMakeLists.txt#L138)):*
> ```CMake
> 
> # gflags
> drake_add_external(gflags PUBLIC CMAKE)
> ```

This can (should?) go in the first list of "trivial" externals, since it is trivial (no arguments to `drake_add_external` besides the name and `PUBLIC`/`CMAKE` flags as applicable).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTGG5UWQGntElV6xsk:bh14k02)*

**Comment by jwnimmer-tri** [comment]
> The WITH_<NAME> option shall have <NAME> be the upper-case of the name of the external as given to drake_add_external...

Right.  But I could have called it `googleflags` or `google_gflags` pervasively everywhere, if that were preferred.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTUiN_kyp7uTwGGTNq:b-7nk9no)*

**Comment by jwnimmer-tri** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 138 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPTF_1mVGMZhhSZNz63:-KPTVFqvFRiI4aqw1eO8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/035cbf7e28f5e2f54a0306322fbbbd4623b32e8d/CMakeLists.txt#L138)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This can (should?) go in the first list of "trivial" externals, since it is trivial (no arguments to `drake_add_external` besides the name and `PUBLIC`/`CMAKE` flags as applicable).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot mac-clang-experimental	please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jwnimmer-tri** [comment]
For clarity:
@mwoehlke-kitware for feature review please
@david-german-tri for platform review please

**Comment by mwoehlke-kitware** [comment]
> I could have called it googleflags or [...]

Ah, I see... the question is not about the `WITH_` specifically, but the name in general.

In that case... "googleflags" would be consistent with "googletest", except that I would have used "gtest" in the first place :smile:. That said, I disclaim that my opinion matters. I'm fine with (and inclined to prefer) "gflags", but someone with a more weighty opinion could override that.

---

Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 255 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPT_bABqyAO3862T2my:-KPT_bAD-UqGWOx9M349:bnlcx7t) ([raw file](https://github.com/robotlocomotion/drake/blob/53f661feef5a27b5d840e592550cd8bed8d8f50e/CMakeLists.txt#L255)):*
> ```CMake
>     google_styleguide
>     googletest
>     gflags
> ```

Pedantic: alphabetize. (Didn't notice earlier; sorry.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTXEJ1KM1Hh3D9KqqN:b3b2fne)*

**Comment by david-german-tri** [comment]
:lgtm: If I could do it over again, I probably would have used "gtest" also.  (That dates from my first week on the job, IIRC.)

---

Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTbmnOwbYbsty_uRpN:b8r5r4n)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 255 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-KPT_bABqyAO3862T2my:-KPTbtreqGeqvNFPaUP2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f661feef5a27b5d840e592550cd8bed8d8f50e/CMakeLists.txt#L255)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Pedantic: alphabetize. (Didn't notice earlier; sorry.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183)*

**Comment by mwoehlke-kitware** [comment]
:lgtm: but I haven't tested it (yet; build still going). Go ahead and merge if @david-german-tri tested and/or if you're okay without a second human build-test.

---

Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTcnOPb4HtNb-N-Z5Q:bxmvhoj)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri I will let you merge when ready.  One comment still needs an ack or override, and dunno if you've tested locally yet.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTfvutaY0bDflJSppq:bzi44rz)*

**Comment by david-german-tri** [comment]
merge conflicts!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3183#-:-KPTidMUpnO3vNdFBidn:bt6l2dp)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jwnimmer-tri** [comment]
Merge conflicts resolved.  Should be ready to merge if and when all of the jenkins stuff passes.

**Comment by jwnimmer-tri** [comment]
Jenkins likes it.  Anyone else need to do a local test before we merge?

**Comment by mwoehlke-kitware** [comment]
I don't know how to actually *use* rigidBodyLCMNode, but it built, and I ran it (with no arguments) and confirm that it a) didn't crash and b) produces a lot of spew about options. GEFM.

**Comment by jwnimmer-tri** [comment]
Having it built seems good enough.

**Pull request merged**
