### PR TITLE
Add Gurobi to the Bazel build.

### PR DESCRIPTION
**Pull request by david-german-tri**
@jwnimmer-tri for initial design review.  I hope this will be a template for other optional externals in the Bazel build, which I hope will be few.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4518)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Very exciting!

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZ3yJ8c-hunJ6aJUp70:bvbyvqt)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Thanks for slogging through this!

---

Reviewed 11 of 11 files at r1, 1 of 12 files at r2.
Review status: 1 of 12 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[WORKSPACE, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ406fZy1adNJfhCfqN:-KZ406f_cHyQLXau67xi:b-xx7b9d) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/WORKSPACE#L85)):*
> ```
> 
> load("//tools:gurobi.bzl", "gurobi_repository")
> gurobi_repository(name = "gurobi", workspace_dir = __workspace_dir__)
> ```

BTW Is it really true that the only way to access`workspace_dir` in a `bzl` file is by passing it explicitly like this?

If so, perhaps just pass `build_file = "tools/gurobi.BUILD"` here instead of the workspace; that way at least it looks more like the other workspace rules?

---

*[drake/doc/bazel.rst, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3zofoNB86WSFBmfL_:-KZ3zofoNB86WSFBmfLa:b2878u0) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/doc/bazel.rst#L109)):*
> ```reStructuredText
> Proprietary Solvers
> ===================
> The Drake Bazel build currently supports the following proprietary solvers:
> ```

BTW Check this output on a local sphinx run.  I would naively expect to need a blank line both before and after this sentence.

---

*[drake/doc/bazel.rst, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ43iw7wqdlPX7O1iRW:-KZ43iw7wqdlPX7O1iRX:b-gdcagp) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/doc/bazel.rst#L120)):*
> ```reStructuredText
> 4. Unzip it in a local directory, e.g. ``/home/myuser/bin/gurobi``
> 5. ``export GUROBI_PATH=/home/myuser/bin/gurobi/gurobi605/linux64``
> 6. Run the tests that require gurobi: ``bazel test --config gurobi ...``
> ```

Ah.  This is _only_ the tests that require gurobi, not all tests _plus_ gurobi tests?  If so, make that more explicit here?

---

*[drake/examples/Valkyrie/BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3yiubO7ToC8QtvQtC:-KZ3yiucXP37HQeXLQSo:bgx1f0t) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/examples/Valkyrie/BUILD#L13)):*
> ```Python
>         "**/*.urdf",
>         "**/*.xml",
>         "**/*.dae",
> ```

BTW Alpha-sort?  Or maybe buildifier doesn't care.

---

*[drake/examples/Valkyrie/BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3z2RftV2-ylCnMmX5:-KZ3z2RftV2-ylCnMmX6:bgfj32s) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/examples/Valkyrie/BUILD#L13)):*
> ```Python
>         "**/*.urdf",
>         "**/*.xml",
>         "**/*.dae",
> ```

FYI In other directories, I've been using the (original four) globs across the board for the "models" or "test_models" labels, even if at the current moment there's no hits for a certain type.  Do we want to preserve that idiom (and thus add *.dae to the prior uses of this kind of glob in other dirs?).

---

*[drake/solvers/BUILD, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ41uhfwb2nGgNTx7p2:-KZ41uhgNkQ4j1SCL4RW:b1g43dz) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/solvers/BUILD#L137)):*
> ```Python
>         "//drake/common:polynomial",
>     ],
>     visibility = ["//visibility:private"],
> ```

FYI Great!  I should have done this with collison_api, eh?

---

*[drake/solvers/BUILD, line 162 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ429oWxpXkujbE-R1I:-KZ429oXIIVWtkt4NF1g:blbkju5) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/solvers/BUILD#L162)):*
> ```Python
>             ":mathematical_program_api",
>         ],
>     }),  
> ```

BTW Trailing whitespace.

---

*[drake/solvers/BUILD, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ40o_Tn_6BvCpgxuNZ:-KZ40o_Tn_6BvCpgxuN_:b-wu90ut) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/solvers/BUILD#L192)):*
> ```Python
>         "@gtest//:main",
>     ],
>     # This test uses Gurobi if present, but does not require it.
> ```

BTW Here (and for the same below), should we have a TODO to factor the test to be more specific, were the test cases are specifically matched to solvers, rather than the "if available" logic (which while not completely brittle is a bit of a hazard in terms of tests disappearing and nobody noticing)?

Similarly, we could keep the non-license-server-dependent runs of the test non-exclusive in that case also.

---

*[drake/systems/robotInterfaces/BUILD, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3zcwBJP9aZtAju82B:-KZ3zcwBJP9aZtAju82C:b-yo6h1j) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/systems/robotInterfaces/BUILD#L9)):*
> ```Python
>     linkstatic = 1,
>     deps = [],
> )
> ```

BTW Missing newline at EOF.

---

*[tools/bazel.rc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ444FoSHHiuciZNTEK:-KZ444FoSHHiuciZNTEL:bp3shyg) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/tools/bazel.rc#L36)):*
> ```
> test:gurobi --test_tag_filters=gurobi
> 
> ### A configuration that enables all optional dependencies. ###
> ```

BTW Add this to the `bazel.rst` instructions?  Or is it only relevant for CI, and unlikely to be used by developers.  Perhaps only CI, since ~no developers have access to _all_ licenses.

---

*[tools/gurobi.BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ45SiQ8NlaJoc1ub6D:-KZ45SiQ8NlaJoc1ub6E:b-dhmhzz) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/tools/gurobi.BUILD#L15)):*
> ```
>         "gurobi-distro/include/gurobi_c++.h",
>     ],
>     linkstatic = 1,
> ```

BTW I'm not entirely sure what this accomplishes?  Comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZ455lEbG-P8RZ_ok-r:b-5yeiv7)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ46gmwHoYZ73GeOuQh:-KZ46gmwHoYZ73GeOuQi:b-npjgkp) (no related file):*
It seems like CI and my local machine don't understand build_tag_filters:
```
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ echo `bazel | head -n1`
[bazel release 0.3.1]
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel build ...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=105
INFO: Reading options for 'build' from /home/jwnimmer/tmp/david-german-tri/drake/tools/bazel.rc:
  'build' options: -c opt --strip=never --copt -Werror=all --cxxopt -std=c++1y --build_tag_filters=-gurobi
Unrecognized option: --build_tag_filters=-gurobi
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ46gmwHoYZ73GeOuQh:-KZ47bWewiUUStrvLFBR:b-400m0z) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like CI and my local machine don't understand build_tag_filters:
```
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ echo `bazel | head -n1`
[bazel release 0.3.1]
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel build ...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=105
INFO: Reading options for 'build' from /home/jwnimmer/tmp/david-german-tri/drake/tools/bazel.rc:
  'build' options: -c opt --strip=never --copt -Werror=all --cxxopt -std=c++1y --build_tag_filters=-gurobi
Unrecognized option: --build_tag_filters=-gurobi
```
</blockquote></details>

Upgrading to Bazel 0.4.2 (the supported version per bazel.rst) fixed it for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by jwnimmer-tri** [comment]
*[tools/gurobi.BUILD, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ45SiQ8NlaJoc1ub6D:-KZ4A01vRGr9mZm1fE1J:b4vqsfi) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/tools/gurobi.BUILD#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I'm not entirely sure what this accomplishes?  Comment?
</blockquote></details>

Oh nevermind.  I see now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by jwnimmer-tri** [comment]
Reviewed 11 of 12 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by jwnimmer-tri** [comment]
*[tools/gurobi.bzl, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ4Lz4JWGGO0V6PV80l:-KZ4Lz4Lf7DCxbS0bpOb:bqjre2y) ([raw file](https://github.com/robotlocomotion/drake/blob/252c1f9acacab62334a1b9f7bcca9d418e61851d/tools/gurobi.bzl#L8)):*
> ```Python
> def _gurobi_impl(repository_ctx):
>     gurobi_path = repository_ctx.os.environ['GUROBI_PATH']
>     if gurobi_path:
> ```

BTW I'm not sure this `if` is necessary?  

On a clean build, if I leave `GUROBI_PATH` unset in my environment, I get this ...
```
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel test --config gurobi ...
ERROR: /home/jwnimmer/tmp/david-german-tri/drake/drake/solvers/BUILD:145:1: no such package '@gurobi//': Key "GUROBI_PATH" not found in dictionary and referenced by '//drake/solvers:gurobi_solver'.
```
... so its already failing -- the environ key error is a hard-fail it seems, not None.

Note that having set `GUROBI_PATH=` once and then `bazel test --config gurobi ...` it's latched the workspace already and the error message changes.  But I still don't think the `if` is adding anything?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by jwnimmer-tri** [comment]
*[tools/gurobi.bzl, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ4OEA75TgJk3wD6nXw:-KZ4OEA75TgJk3wD6nXx:b-bonqke) ([raw file](https://github.com/robotlocomotion/drake/blob/252c1f9acacab62334a1b9f7bcca9d418e61851d/tools/gurobi.bzl#L7)):*
> ```Python
> # TODO(david-german-tri): Add support for OS X.
> def _gurobi_impl(repository_ctx):
>     gurobi_path = repository_ctx.os.environ['GUROBI_PATH']
> ```

The gurobi exclusion isn't working during an explicit `bazel fetch`.  With `GUROBI_PATH` unset, I get:
```
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel clean
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel fetch ...
ERROR: /home/jwnimmer/tmp/david-german-tri/drake/drake/solvers/BUILD:145:1: no such package '@gurobi//': Key "GUROBI_PATH" not found in dictionary and referenced by '//drake/solvers:gurobi_solver'.
```

Perhaps we _do_ need to avoid the key error here, and keep the if (in contrast to my immediately-below comment).

Or perhaps `bazel.rc` needs to negate gurobi targets during `fetch` as well as `build` and `test`.  (Or maybe there's an "any command" wildcard?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by jwnimmer-tri** [comment]
Blocked on #4526. +(status: do not merge) 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZ77jYS3dVQ5dIoCjlE:b-il5ing)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/doc/bazel.rst, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3zofoNB86WSFBmfL_:-KZ7FkKRqpYvJj_gu8oO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/doc/bazel.rst#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Check this output on a local sphinx run.  I would naively expect to need a blank line both before and after this sentence.
</blockquote></details>

Done.

---

*[drake/doc/bazel.rst, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ43iw7wqdlPX7O1iRW:-KZ7GDcE6xq89eGjcXBs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/doc/bazel.rst#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah.  This is _only_ the tests that require gurobi, not all tests _plus_ gurobi tests?  If so, make that more explicit here?
</blockquote></details>

Done.

---

*[drake/examples/Valkyrie/BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3yiubO7ToC8QtvQtC:-KZ7GJgqPQoMxmE8LO3G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/examples/Valkyrie/BUILD#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Alpha-sort?  Or maybe buildifier doesn't care.
</blockquote></details>

Done.

---

*[drake/examples/Valkyrie/BUILD, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ3z2RftV2-ylCnMmX5:-KZ7GK5aBvpIRqCU8DMf:b-3yb5dq) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/examples/Valkyrie/BUILD#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI In other directories, I've been using the (original four) globs across the board for the "models" or "test_models" labels, even if at the current moment there's no hits for a certain type.  Do we want to preserve that idiom (and thus add *.dae to the prior uses of this kind of glob in other dirs?).
</blockquote></details>

Seems reasonable to me, but I'll kick it to a follow-up PR.

---

*[drake/solvers/BUILD, line 162 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ429oWxpXkujbE-R1I:-KZ7G_n4c6b0-8mqFqhV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/solvers/BUILD#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Trailing whitespace.
</blockquote></details>

Done.

---

*[drake/solvers/BUILD, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ40o_Tn_6BvCpgxuNZ:-KZ7GnYbNdO8L-So2ta_:bi8fas9) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/drake/solvers/BUILD#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Here (and for the same below), should we have a TODO to factor the test to be more specific, were the test cases are specifically matched to solvers, rather than the "if available" logic (which while not completely brittle is a bit of a hazard in terms of tests disappearing and nobody noticing)?

Similarly, we could keep the non-license-server-dependent runs of the test non-exclusive in that case also.
</blockquote></details>

Done.  @hongkai-dai, I named you in the TODO since unlike me you actually understand how these tests work.

---

*[tools/bazel.rc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ444FoSHHiuciZNTEK:-KZ7H2wtkIBXO0MqbTYS:b-ya4zpv) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/tools/bazel.rc#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Add this to the `bazel.rst` instructions?  Or is it only relevant for CI, and unlikely to be used by developers.  Perhaps only CI, since ~no developers have access to _all_ licenses.
</blockquote></details>

Improved the comment.

---

*[tools/gurobi.bzl, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ4OEA75TgJk3wD6nXw:-KZ7JSXJJGuFVfL_5OWN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/252c1f9acacab62334a1b9f7bcca9d418e61851d/tools/gurobi.bzl#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The gurobi exclusion isn't working during an explicit `bazel fetch`.  With `GUROBI_PATH` unset, I get:
```
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel clean
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel fetch ...
ERROR: /home/jwnimmer/tmp/david-german-tri/drake/drake/solvers/BUILD:145:1: no such package '@gurobi//': Key "GUROBI_PATH" not found in dictionary and referenced by '//drake/solvers:gurobi_solver'.
```

Perhaps we _do_ need to avoid the key error here, and keep the if (in contrast to my immediately-below comment).

Or perhaps `bazel.rc` needs to negate gurobi targets during `fetch` as well as `build` and `test`.  (Or maybe there's an "any command" wildcard?)
</blockquote></details>

Done.

---

*[tools/gurobi.bzl, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ4Lz4JWGGO0V6PV80l:-KZ7JX5H7m-LCNGzAhxK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/252c1f9acacab62334a1b9f7bcca9d418e61851d/tools/gurobi.bzl#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I'm not sure this `if` is necessary?  

On a clean build, if I leave `GUROBI_PATH` unset in my environment, I get this ...
```
jwnimmer@call-cc:~/tmp/david-german-tri/drake$ bazel test --config gurobi ...
ERROR: /home/jwnimmer/tmp/david-german-tri/drake/drake/solvers/BUILD:145:1: no such package '@gurobi//': Key "GUROBI_PATH" not found in dictionary and referenced by '//drake/solvers:gurobi_solver'.
```
... so its already failing -- the environ key error is a hard-fail it seems, not None.

Note that having set `GUROBI_PATH=` once and then `bazel test --config gurobi ...` it's latched the workspace already and the error message changes.  But I still don't think the `if` is adding anything?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 4 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-KZ406fZy1adNJfhCfqN:-KZ7RVHaVXwwZsn1h92n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d324a69a2e9121c5d13c53bb289f3a5fd010dc63/WORKSPACE#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is it really true that the only way to access`workspace_dir` in a `bzl` file is by passing it explicitly like this?

If so, perhaps just pass `build_file = "tools/gurobi.BUILD"` here instead of the workspace; that way at least it looks more like the other workspace rules?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZ7RdTJGKT5mwVETt6d:b-fffduh)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZ7RwylQzfVJ-7K-CSj:bnfp4nl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZ7o_eIBltg7aRIzq6G:ba41p59)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri do you want to assign a second pair of reviewer eyes on this, so that it can merge once CI has a new-enough Bazel?  It also looks like it needs merge conflicts fixed still.

**Comment by david-german-tri** [comment]
+@sammy-tri

---

Review status: 5 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZYNbd80WPplEV4eWCl:b38cofj)*

**Comment by david-german-tri** [comment]
-(status: do not merge) 

---

Review status: 5 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZYNetxskH0DPHUis4W:b-b9fcpn)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 5 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZYNhT-eANe1rZXfAcJ:b-wkqpq5)*

**Comment by david-german-tri** [comment]
On #4526 @jamiesnape notes that we won't get Bazel 0.4.2 until all the worker AMIs reboot, so I'm going to let this sit.  @jwnimmer-tri @sammy-tri , feel free to re-test and merge if I'm not at keyboard to do so.

---

Review status: 5 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZYQcwAeAQFoDY8jaaC:b-qgrzw5)*

**Comment by sammy-tri** [comment]
:lgtm: (obviously pending the CI issue)

---

Reviewed 3 of 12 files at r2, 2 of 7 files at r3, 5 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4518#-:-KZYQzownOw20_EeDFXK:b6y46lp)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Hopefully the builders have more or less cycled through now (for other PRs).

**Pull request merged**
