### PR TITLE
Move trajectory wrappers from humanoids to /manipulation

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
move some trajectory wrappers from humanoids to manip.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6104)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature, +@sammy-tri for platform review. thanks!
this is pure git mv. 
+@sammy-tri if you want, i can go replaces the relevant stuff in kuka_iiwa when i am really bored.. 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-:-KkCXKZBmlTxg6h-d2ly:b-3lsatl)*

**Comment by sammy-tri** [comment]
I'm OK with moving to manipulation as is, but I'm curious about your opinion on (1) splitting the two classes into their own files (piecewise_{cubic,cartesian}_trajectory.{h,cc}) and (2) moving to common/trajectories

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-KkCbCLpetLHEZZxsplM:-KkCbCLpetLHEZZxsplN:b-ifa9px) ([raw file](https://github.com/robotlocomotion/drake/blob/9884908a9fe9b0e37c6baa1bdae21d77616bf448/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L70)):*
> ```objc
> 
>   void UpdateQpInputGenericPlanDerived(
>       const HumanoidStatus&, const param_parsers::ParamSet&,
> ```

BTW in general I'm opposed to mixing formatting-only changes into PR's with code changes (this file doesn't seem to have any actual differences?)

---

*[drake/manipulation/util/BUILD, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-KkCaxloL_R4mOK6EpXc:-KkCaxlpeCsxqF-xH2s_:b-a6iiy4) ([raw file](https://github.com/robotlocomotion/drake/blob/9884908a9fe9b0e37c6baa1bdae21d77616bf448/drake/manipulation/util/BUILD#L36)):*
> ```Python
>         "//drake/common/trajectories:piecewise_polynomial",
>         "//drake/common/trajectories:piecewise_quaternion",
>         "//drake/multibody:rigid_body_tree",
> ```

I don't think this is actually used

---

*[drake/manipulation/util/trajectory_utils.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-KkCaYMt39qqTzJBobYR:-KkCaYMuN-InG-wKUBNy:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/9884908a9fe9b0e37c6baa1bdae21d77616bf448/drake/manipulation/util/trajectory_utils.h#L9)):*
> ```objc
> #include "drake/common/trajectories/piecewise_polynomial.h"
> #include "drake/common/trajectories/piecewise_quaternion.h"
> #include "drake/multibody/rigid_body_tree.h"
> ```

unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-:-KkCbRmMTyuWHaT-txfG:b-xcirk5)*

**Comment by siyuanfeng-tri** [comment]
i suppose i could, but i am afraid that we will end up with an exploding /utils folder. in any case, these are pretty thing wrappers, so i feel it's ok. 
i am indifferent to move it to common. i am moving it here simply because this is the most relevant place, and on one has been screaming for this in the outside world. 

---

Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/util/BUILD, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-KkCaxloL_R4mOK6EpXc:-KkCczTl_LbcnkCcAvxQ:bdr28vi) ([raw file](https://github.com/robotlocomotion/drake/blob/9884908a9fe9b0e37c6baa1bdae21d77616bf448/drake/manipulation/util/BUILD#L36)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think this is actually used
</blockquote></details>

good catch. 
this was for the contact state stuff that i moved to generic_plan.h 

---

*[drake/manipulation/util/trajectory_utils.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-KkCaYMt39qqTzJBobYR:-KkCdVQqRU41GLFo-YOh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9884908a9fe9b0e37c6baa1bdae21d77616bf448/drake/manipulation/util/trajectory_utils.h#L9)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-KkCbCLpetLHEZZxsplM:-KkCcjLyDoQRDXfCYfNW:b-d1wou5) ([raw file](https://github.com/robotlocomotion/drake/blob/9884908a9fe9b0e37c6baa1bdae21d77616bf448/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L70)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW in general I'm opposed to mixing formatting-only changes into PR's with code changes (this file doesn't seem to have any actual differences?)
</blockquote></details>

opps. i just run clangform on *.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-:-KkCcU5sgye0zuHISxNd:b51t3ml)*

**Comment by sammy-tri** [comment]
:lgtm: if I decide I care later about the split/move I'll do it myself.  :)

---

Reviewed 1 of 15 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-:-KkCeyfwlAuG-9M2zXb1:b-ik2bok)*

**Comment by siyuanfeng-tri** [comment]
sounds good :) 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-:-KkCfb2HhNf9K9sedjVo:b-6ay3bv)*

**Comment by siyuanfeng-tri** [comment]
-@naveenoid since sammy checked it. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6104#-:-KkCrafqoq1AQtSYRTii:b-i49bdi)*

**Pull request merged**
