### PR TITLE
Upgrade to Gurobi 10.0.2

### LINKED ISSUE #18352: Upgrade to Gurobi 10
Gurobi 10 is released https://www.gurobi.com/whats-new-gurobi-10-0/

I will contact the gurobi vendor to check if we need to upgrade our licenses.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #18352

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@mwoehlke-kitware @jwnimmer-tri could you upgrade the Gurobi on the CI station to Gurobi 10?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-N_CVCeX6lxOWaxfOIAC:bymn4fo)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-N_V87gCAiwhgV2Igcw3:-N_V87gCAiwhgV2Igcw4:b-gcnquh) (no related file):*
Working

Test against Anzu CI before merging.

___

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)* status: 2 unresolved discussions, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-Na7vJ3PBpv1ChlMKS9o:-Na7vJ3PBpv1ChlMKS9p:b5l4w3y) (no related file):*
Based on the previous update to 9.5 (#16604) it looks like we're missing an update to FindGurobi.cmake

https://github.com/RobotLocomotion/drake/blob/3fdd74cae58f672fe16b1f305e5a606f7f85c2e3/cmake/modules/FindGurobi.cmake#L5-L7

___

**Comment by svenevs** [comment]
The mac-arm-ventura queue has been broken today, I cleared out all jobs and am relaunching the one needed for your PR.

Though I'm pretty sure this PR will not pass.

@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Comment by svenevs** [comment]
We've got CI setup to be able to test unprovisioned builds.  You have to do this by logging into jenkins, navigating the jobs, choosing "Build with parameters", and choosing `sha1` (for drake) of `pr/19766/head` and `ci_sha1` of `pr/237/head`

https://github.com/RobotLocomotion/drake-ci/pull/237#issuecomment-1664337431

`//multibody/inverse_kinematics:global_inverse_kinematics_reachable_test` needs some tolerance love on this PR it seems.

macOS capabilities of launching with a new gurobi just got added, CI results expected in a few hours.

**Review by BetsyMcPhail — COMMENTED** [review]
Some test jobs:

https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-x86-monterey-unprovisioned-clang-bazel-experimental-everything-release/2/
https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-everything-release/2/console
https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/37/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-NbHKAHvEEj-nlEARjlF:b5q7ey)* status: 2 unresolved discussions, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by hongkai-dai** [comment]
Thanks @BetsyMcPhail , I also just started https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/38/, I will close this job then.

**Comment by svenevs** [comment]
> https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-everything-release/2/console

I had to cancel this (to prepare provisioned images for this PR).  I will relaunch after the maintenance is complete.

**Comment by svenevs** [comment]
> https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/37/

SUCCESS!

> https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-x86-monterey-unprovisioned-clang-bazel-experimental-everything-release/2/

I cleared out the queue, the new jobs in x86 flavor are VERY slow.

---

Some additional macOS arm64 builds (note: ventura queue is kind of long right now):

- https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-everything-release/3/consoleFull
- https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-monterey-unprovisioned-clang-bazel-experimental-everything-release/2/consoleFull

> I had to cancel this (to prepare provisioned images for this PR)

macOS arm64 provisioned images are ready.  We cannot prepare x86 ahead of time, when we do the switchout I'll just do that one on the fly as fast as possible.

**Review by BetsyMcPhail — COMMENTED** [review]
Current testing status:
* https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/37/ **--> passed**
* https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-x86-monterey-unprovisioned-clang-bazel-experimental-everything-release/2/ **--> passed**
* https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-everything-release/3/ **--> timed out, probably unrelated to Gurobi update**
* https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-everything-release/3/ **--> test failure**

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-NbL5mrL5Roq2QTvaJJ3:br131bw)* status: 2 unresolved discussions, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by hongkai-dai** [comment]
Thanks @BetsyMcPhail I just changed the code and launched the build https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-unprovisioned-clang-bazel-experimental-everything-release/3/

**Review by BetsyMcPhail — COMMENTED** [review]
Thanks! I added the 'do not merge' tag. @svenevs will coordinate CI updates with merging this PR when it's ready.

:lgtm:

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-NbL_bbu1bDzduknfAIx:b-xgxxru)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
> ... I just changed the code and launched the build .../3/

=> https://drake-cdash.csail.mit.edu/test/1163923346

@hongkai-dai still waiting on you to work on the one remaining test failure.

**Comment by hongkai-dai** [comment]
Sorry, I just changed the tolerance and launched https://drake-jenkins.csail.mit.edu/view/Everything/job/mac-arm-monterey-unprovisioned-clang-bazel-experimental-everything-release/4/

**Review by jwnimmer-tri — COMMENTED** [review]
Adding +@jwnimmer-tri.  It looks like the TRI Anzu side of this upgrade has not been prepared yet.  I'll put a block on this PR while I work on that this week.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-NblC083ADzJnwS4kiJm:b-5377zh)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
> I'll put a block on this PR while I work on that this week.

Actually, Anzu has its own rules for Gurobi that are unaffected by this, because there are no changes here to `gurobi_solver.cc` (e.g., calling some new version-10-only APIs).  Anzu is not a blocker here, so -@jwnimmer-tri.

**Review by svenevs — COMMENTED** [review]
-@BetsyMcPhail +@svenevs I'll be finishing this one off for us.  Tests are almost there.  If we get them fixed then I can land this on Friday (once we get a platform reviewer involved), we will be leaving this in a merge-ready state and that will enable me to do the final pieces when TRI will not be affected.

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-NbotLN-CnpDTAw9xa1j:b46g2k5)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

___
*[`tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in` line 28 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NbotDQQAPWbGh4flvvW:-NbotDQQAPWbGh4flvvX:bvmu9ct) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb0ad25c749a249f5f3f53e1c5bb5ddc4333b87f/tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in#L28)):*
> ```
> ]) or [":error-message.h"]
> 
> # In the Gurobi package, libgurobi100.so is a symlink to libgurobi.so.10.0.*.
> ```

blocking (location of this irrelevant)

https://drake-cdash.csail.mit.edu/test/1167053873

tests still need some love

**Comment by hongkai-dai** [comment]
I disabled the line that causes failure on the Mac machine. It would take quite some efforts to make the test less brittle, which I will do it separately. Now the mac build passes.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule (on Monday), please.

There is no rush here.  We don't plan to merge this until the later part of next week.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 11 of 13 files at r1, 1 of 1 files at r2, 3 of 5 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-:-NcNxsUq50eTPGPASKfW:b-cxwtpw)* status: 5 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

___
*[`doc/_pages/bazel.md` line 183 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNvmpzEhOqDNto8en1:-NcNvmq-Bk2ssw7AGUaL:b-78cu3r) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/doc/_pages/bazel.md#L183)):*
> ```Markdown
> 2. Set up your Gurobi license file in accordance with Gurobi documentation.
> 3. ``export GRB_LICENSE_FILE=/path/to/gurobi.lic``.
> 4. Download ``gurobi10.0.2_linux64.tar.gz``. You may need to manually edit the URL to get the correct version.
> ```

minor, I don't see the url here. Is it "https://packages.gurobi.com/10.0/gurobi10.0.2_linux64.tar.gz"?
Same for the mac pkg.



_Code quote:_
```Markdown
``gurobi10.0.2_linux64.tar.gz``
```
___
*[`solvers/gurobi_solver.h` line 99 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNxQb76QLu7eMEPIye:-NcNxQb8Bk7fkiPNqCFw:bsq2oyh) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/solvers/gurobi_solver.h#L99)):*
> ```objc
>   /// finds an intermediate solution node, which may not be feasible.
>   /// See Gurobi reference manual for more detail on callbacks:
>   /// https://www.gurobi.com/documentation/10.0/refman/callback_codes.html.
> ```

BTW, this link is dead. Ditto below for the same link.



_Code quote:_
```objc
https://www.gurobi.com/documentation/10.0/refman/callback_codes.html
```
___
*[`solvers/gurobi_solver.cc` line 543 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNx3ZC9_HfN4b7bYjz:-NcNx3ZC9_HfN4b7bYk-:b5ejt8s) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/solvers/gurobi_solver.cc#L543)):*
> ```cpp
>     // Gurobi uses a matrix Q to differentiate Lorentz cone and rotated Lorentz
>     // cone constraint.
>     // https://www.gurobi.com/documentation/10.0/refman/c_grbaddqconstr.html
> ```

BTW, this link is dead.



_Code quote:_
```cpp
https://www.gurobi.com/documentation/10.0/refman/c_grbaddqconstr.html
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", missing label for release notes

___
*[`doc/_pages/bazel.md` line 183 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNvmpzEhOqDNto8en1:-NcNzij-4la5VkM14mDl:bpar5m8) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/doc/_pages/bazel.md#L183)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, I don't see the url here. Is it "https://packages.gurobi.com/10.0/gurobi10.0.2_linux64.tar.gz"?
Same for the mac pkg.
</blockquote></details>

Done. I added the URL
___
*[`solvers/gurobi_solver.h` line 99 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNxQb76QLu7eMEPIye:-NcO-hbSE6_rMo599PM-:b9cedjm) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/solvers/gurobi_solver.h#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this link is dead. Ditto below for the same link.
</blockquote></details>

Done. Thanks for catching it!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

___
*[`doc/_pages/bazel.md` line 183 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNvmpzEhOqDNto8en1:-NcO0sIn14Ui5TBSmxUN:b-awakk) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/doc/_pages/bazel.md#L183)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I added the URL
</blockquote></details>

Nope, you need to undo this.

Gurobi purposefully obscures the URL downloads, to enforce their click-through license.  We must not expose their company secrets, copied _from a portal that requires our login credentials_, into our public documentation.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", missing label for release notes

___
*[`doc/_pages/bazel.md` line 183 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19766#-NcNvmpzEhOqDNto8en1:-NcO2AN96oHIuWoN4BCM:bgcbmhk) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac47e8472fda62602ef96a0b5615817979a8e74e/doc/_pages/bazel.md#L183)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Nope, you need to undo this.

Gurobi purposefully obscures the URL downloads, to enforce their click-through license.  We must not expose their company secrets, copied _from a portal that requires our login credentials_, into our public documentation.
</blockquote></details>

Done. Thanks Jeremy

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19766)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", missing label for release notes (waiting on @hongkai-dai)

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

**Pull request merged**
