### PR TITLE
[tools] Offer option to disable drake-visualizer

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates to #16215.

At the moment, the _only_ CI coverage of this build option is the wheel builds, which are run nightly (not pre-merge).

FYI -- Anzu-master-Drake-PR has passed vs this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16221)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @mwoehlke-kitware @svenevs FYI on the change to Drake's wheel build.  It will no longer download and install the visualizer binary, only to throw it away later when making the whl.  This will especially help once the visualizer download starts incorporating VTK 8 as part of #16132.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16221#-:-MqzVFVJ5zKyCisX8NCG:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule (tomorrow), please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: per PR and issue description - thanks!

> Reviewed 7 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16221#-:-Mr2i91t7NFBT3Bsvoq_:b4vvath)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[tools/workspace/drake_visualizer/drake_visualizer_disabled.py, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16221#-Mr2hy6N6u0KG164NEFK:-Mr2hy6N6u0KG164NEFL:b-30fm12) ([raw file](https://github.com/robotlocomotion/drake/blob/d77340f443de894d3ec4594537ff1f15c2c49a1d/tools/workspace/drake_visualizer/drake_visualizer_disabled.py#L6)):*
> ```Python
> 
> assert __name__ == "__main__"
> print("error: drake-visualizer was disabled in this build of Drake", file=sys.stderr)  # noqa
> ```

BTW `error:` seems inconsistent w/ other messages I've seen, in Drake at least.
Consider `ERROR:`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16221)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[tools/workspace/drake_visualizer/drake_visualizer_disabled.py, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16221#-Mr2hy6N6u0KG164NEFK:-Mr2rzdc5tUwcifxHeq5:bnlqohp) ([raw file](https://github.com/robotlocomotion/drake/blob/d77340f443de894d3ec4594537ff1f15c2c49a1d/tools/workspace/drake_visualizer/drake_visualizer_disabled.py#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW `error:` seems inconsistent w/ other messages I've seen, in Drake at least.
Consider `ERROR:`?
</blockquote></details>

OK meh.

**Pull request merged**
