### PR TITLE
Add a clutter clearing example with DOPE objects to ManipulationStation

### PR DESCRIPTION
**Pull request by kmuhlrad**
This adds another setup option to `ManipulationStation` similar to the `ClutterClearing` option, but with the YCB objects from DOPE instead of abstract objects. There is a Python binding to the new method, as well as tests. `proof_of_life.cc` includes the option of using this new setup.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10703)

### CODE REVIEW

**Comment by kmuhlrad** [comment]
Here are the object locations without randomization: dope_clutter_clearing

**Comment by kmuhlrad** [comment]
There is a lot of copy and pasted code. The main differences are the objects, their poses, and the presence of an `RgbdCamera`.

One option is `SetupClutterClearingStation` could take in a list of meshes and poses. For the camera, we could either always add this camera in (I don't know what the goals in Anzu are), or pass in a boolean or something to the method of whether to include the camera.

Thoughts?

**Comment by kmuhlrad** [comment]
Yes I meant model files.

Ok, I can make those changes. You have both approved this PR as is. Do you want to merge this in now and I'll make the changes in a follow up, or should I make the changes directly in this PR?

**Comment by kmuhlrad** [comment]
I’ll do it in this PR.

**Comment by kmuhlrad** [comment]
Is it a problem for Anzu if I completely change the `SetupClutterClearing` method to take in those parameters instead of just adding a second overloaded function? I'll make sure not to change the behavior of the method as exists, but it's much cleaner if I change the original function.

**Comment by kmuhlrad** [comment]
Fixed the rebase but killed the PR in the process... Whoops.

I'll make the suggested changes in the new branch, add Python bindings, and open up a new PR.

**Comment by rcory** [comment]
___
*[examples/manipulation_station/manipulation_station.h, line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10703#-LZCpKsrEiTTMuLnojWn:-LZFlrXUAYmqBbBpiKvQ:bz2j07r) ([raw file](https://github.com/robotlocomotion/drake/blob/2d318f93ca3955b42420e901e7fc734e14c33251/examples/manipulation_station/manipulation_station.h#L165)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

sorry to disagree with @rcory -- but i think you could always add the camera.  there will be no cost unless someone evaluates the output port.
</blockquote></details>

Good point. After discussing with @seancurtis-tri , it seems it's not entirely cost free (e.g., caching still gets updated even if the output ports are not evaluated), but he thinks these caching costs are in the noise for any meaningful simulation. 

So the conclusion is, yes, having a camera there shouldn't noticeably affect the simulation (as long as it's not connected).

**Comment by kmuhlrad** [comment]
New PR: https://github.com/RobotLocomotion/drake/pull/10748

**Pull request closed without merging**
