### PR TITLE
Quadratic expression in lorentz cone

### PR DESCRIPTION
**Pull request by hongkai-dai**
Now we can accept 
```C++
AddLorentzConeConstraint(const Expression& v1, const Expression& v2)
```
To impose the Lorentz cone constraint `v1 >= sqrt(v2)`, where `v1` is a linear expression, `v2` is a quadratic expression.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5433)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-:-KebVZVCo5mqYp7Ug2Mv:bpno49v)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 354 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedsZIQkJ_AtwCag15X:-KedsZIQkJ_AtwCag15Y:bbz4di7) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L354)):*
> ```cpp
> 
> /**
>  * Given a quadratic expression e, decompose it into the form
> ```

This part of the documentation doesn't seem to be accurate since it doesn't take `e` as an argument. 

---

*[drake/solvers/mathematical_program.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kedu_cVxAZY-rdqoGe6:-Kedu_cVxAZY-rdqoGe7:b-b3wbt7) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L356)):*
> ```cpp
>  * Given a quadratic expression e, decompose it into the form
>  * e = 0.5 * x' * Q * x + b' * x + c
>  * @param[in] monomial_to_coeff_map. Map the monomial to the coefficient, this is
> ```

FYI, This line is 81-char long.

---

*[drake/solvers/mathematical_program.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedubbTonEHS34XwPYJ:-KedubbTonEHS34XwPYK:b-2khkcv) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L358)):*
> ```cpp
>  * @param[in] monomial_to_coeff_map. Map the monomial to the coefficient, this is
>  * the result of calling DecomposePolynomialIntoMonomial(e).
>  * @param[in] map_var_to_index maps variables in monomial_to_coeff_map.GetVariables()
> ```

FYI, This line is 85-char long.

---

*[drake/solvers/mathematical_program.cc, line 370 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedupiUqSPUSMQ8lOHc:-KedupiUqSPUSMQ8lOHd:b-msxgwd) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L370)):*
> ```cpp
>     int num_variables,
>     Eigen::MatrixXd* Q, Eigen::VectorXd* b, double* c) {
>   Q->resize(num_variables, num_variables);
> ```

FYI, these `resize` calls are not necessary since it's already guaranteed by the call-sites. Probably better to change them to `DRAKE_ASSERT` or `DRAKE_DEMAND` and have the conditions in the documentation?

---

*[drake/solvers/mathematical_program.cc, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebjCSQnMnW6n_unj0d:-KebjCSRJppCXavGiml7:barqv29) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L410)):*
> ```cpp
>         // linear term b * x.
>         (*b)(x_index) += coefficient;
>       } else {
> ```

I think this case is never taken because we eliminate the case `x^0`. Could you double-check?

---

*[drake/solvers/mathematical_program.cc, line 855 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedwO3Sc6ZxiG5MiMOP:-KedwO3Sc6ZxiG5MiMOQ:b1kwp3n) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L855)):*
> ```cpp
>     // Q is not strictly positive definite.
>     // First check if Q is zero.
>     bool is_Q_zero = true;
> ```

FYI, consider the following line instead of the for-loops.
```c++
    const bool is_Q_zero = (Q.array() == 0.0).all();
```
AFAIK, there will be no performance penalty.

---

*[drake/solvers/mathematical_program.cc, line 867 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedxlRw77KGCrq5rzKq:-KedxlRw77KGCrq5rzKr:bqnca0a) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L867)):*
> ```cpp
>       }
>     }
>     if (is_Q_zero) {
> ```

BTW, `is_Q_zero` is true under all of the unit tests. Does this mean we need more test cases?

---

*[drake/solvers/mathematical_program.cc, line 871 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kedwmj7plg4a5QQEVUa:-Kedwmj7plg4a5QQEVUb:bdt3n2r) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L871)):*
> ```cpp
>       // add the linear constraint linear_expr >= sqrt(a); otherwise throw a
>       // runtime error.
>       bool is_b_zero = true;
> ```

Similarly, consider the following:
```c++
      const bool is_b_zero = (b.array() == 0.0).all();
```

---

*[drake/solvers/mathematical_program.cc, line 911 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedyfBwm6LwevyHkAEA:-KedyfBwm6LwevyHkAEB:bwiihl4) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L911)):*
> ```cpp
>         R1(i, j) = 0;
>       }
>       double d_sqrt = std::sqrt(ldlt_Q.vectorD()(i));
> ```

BTW, consider marking it as `const`.

---

*[drake/solvers/mathematical_program.cc, line 912 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedyjjNAZWA4hyuubSp:-KedyjjNAZWA4hyuubSq:b-s1dtg2) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L912)):*
> ```cpp
>       }
>       double d_sqrt = std::sqrt(ldlt_Q.vectorD()(i));
>       for (int j = 0; j < R1.cols(); ++j) {
> ```

Is `int j = 0;` a typo of `int j = i`?

---

*[drake/solvers/mathematical_program.h, line 1482 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebfRdma9lltqw3HZAB:-KebfRdma9lltqw3HZAC:b-9ibk8s) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1482)):*
> ```objc
>    * Adds Lorentz cone constraint on the linear expression v1 and quadratic
>    * expression v2, such that v1 >= sqrt(v2)
>    * @param linear_expr     The linear expression v1.
> ```

BTW, I think the uses of `v1/v2` and `linear_expr/quadratic_expr` are a bit confusing. Probably better to use `v1` and `v2` in the API but to document that they are 'linear expression'/'quadratic' expression?

---

*[drake/solvers/mathematical_program.h, line 1486 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kebf9p-bzwpFcNa_bng:-Kebf9p-bzwpFcNa_bnh:bhj6474) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1486)):*
> ```objc
>    * @retval binding The newly added Lorentz cone constraint, together with the
>    * bound variables.
>    * @pre{1. `linear_expr` is a linear expression, in the form of c'*x + d.
> ```

BTW, today I learned from @sherm1 that the curly braces `{` and `}` are not necessary here. Could you double-check it by running Doxygen and checking the result?

---

*[drake/solvers/mathematical_program.h, line 1492 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebfmBLiIB9Ewn7Y3sD:-KebfmBLiIB9Ewn7Y3sE:btinyo5) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1492)):*
> ```objc
>    *          positive semidefinite matrix, and the quadratic expression needs
>    *          to be non-negative for any x.}
>    * Throws a runtime error if the preconditions are not satisfied.
> ```

BTW, I think it's better to have `runtime_error` instead of `runtime error`.

---

*[drake/solvers/mathematical_program.h, line 1495 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kebg8Eo5cXYiKnWvQ8D:-Kebg8Eo5cXYiKnWvQ8E:b-m146ad) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1495)):*
> ```objc
>    * Notice this constraint is equivalent to the vector [z;y] is within a
>    * Lorentz cone, where
>    * z = v1
> ```

BTW, I think it's more readable if we indent `z = ...` and `y = ...` (four spaces?)

---

*[drake/solvers/mathematical_program.h, line 1497 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebgGtBBQDgkUe9isi6:-KebgGtBBQDgkUe9isi7:bbp0m7s) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1497)):*
> ```objc
>    * z = v1
>    * y = [1 / sqrt(2) * R * x + R⁻ᵀb; sqrt(a - 0.5 * bᵀ * Q⁻¹ * a)]
>    * where R satisfies Rᵀ * R = Q
> ```

BTW, probably better to avoid the repeated `where` here?
Is `while` better?

---

*[drake/solvers/test/mathematical_program_test.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedrFaieilbPkZUlAbw:-KedrFaieilbPkZUlAbx:b-9mx9vg) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L15)):*
> ```cpp
> #include "drake/math/matrix_util.h"
> #include "drake/solvers/constraint.h"
> #include "drake/solvers/mathematical_program.h"
> ```

FYI, `#include "drake/solvers/mathematical_program.h"` should be atop this file.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-3CcwE2M71Iwv0G_:-Kee-3CcwE2M71Iwv0Ga:b-m4b72z) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1141)):*
> ```cpp
>     }
>   }
>   for (const auto& p : poly_diff) {
> ```

FYI, consider the following code:
```c++
  return std::all_of(poly_diff.begin(), poly_diff.end(), [&tol](const auto& p) {
    return std::abs(symbolic::get_constant_value(p.second)) <= tol;
  });
```
Note that you need `#include <algorithm>` to use `std::all_of`.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-rf0Oqmxakkz3o7_:-Kee-rf0Oqmxakkz3o7a:b-xeekra) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1166)):*
> ```cpp
>       e_parsed.tail(e_parsed.rows() - 1).squaredNorm();
>   // Due to the small numerical error, quadratic_expr and quadratic_expr_parsed
>   // do not match
> ```

Consider reflowing this section.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-zouwUu6nXnr6zew:-Kee-zouwUu6nXnr6zex:b-uwnnxp) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1168)):*
> ```cpp
>   // do not match
>   // exactly.So we will compare each term in the two polynomials, and regard
>   // them to beequal if the error in the coefficient is sufficiently small.
> ```

FYI, typo of `be equal`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebjCSQnMnW6n_unj0d:-Kee0igBrJrEaBAtT0iI:br641ib) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L410)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think this case is never taken because we eliminate the case `x^0`. Could you double-check?
</blockquote></details>

FYI, at least, we don't have a unit test covering this branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433)*

**Comment by soonho-tri** [comment]
*[drake/solvers/mathematical_program.cc, line 867 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedxlRw77KGCrq5rzKq:-KefB47uY6o1bj24IDHg:b-hj3hn5) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L867)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `is_Q_zero` is true under all of the unit tests. Does this mean we need more test cases?
</blockquote></details>

Withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 19 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 354 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedsZIQkJ_AtwCag15X:-Kef7YzSUrDHOFRiwvRL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L354)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

This part of the documentation doesn't seem to be accurate since it doesn't take `e` as an argument. 
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 356 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kedu_cVxAZY-rdqoGe6:-Kef7ZIhRaQS_zM83DSA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L356)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, This line is 81-char long.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 358 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedubbTonEHS34XwPYJ:-Kef7ZpscYOjMW0ZR2wz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L358)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, This line is 85-char long.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 370 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedupiUqSPUSMQ8lOHc:-Kef7nI970nLaMVdP39q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L370)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, these `resize` calls are not necessary since it's already guaranteed by the call-sites. Probably better to change them to `DRAKE_ASSERT` or `DRAKE_DEMAND` and have the conditions in the documentation?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebjCSQnMnW6n_unj0d:-Kef8JkbPLcu2WOu3l_w:b-xiixi5) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L410)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, at least, we don't have a unit test covering this branch.
</blockquote></details>

Done. Add a `DRAKE_DEMAND(it->second == 2 || it->second == 1)`, since the constant term has size zero in the `monomial_powers`.

---

*[drake/solvers/mathematical_program.cc, line 855 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedwO3Sc6ZxiG5MiMOP:-Kef8q9cHm686IK9hr7p:b-7jalp2) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L855)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, consider the following line instead of the for-loops.
```c++
    const bool is_Q_zero = (Q.array() == 0.0).all();
```
AFAIK, there will be no performance penalty.
</blockquote></details>

Done. I think there is slight performance penalty, which checks all entries in Q, while the for loop only checks the lower triangular part of Q. But the one line code is a lot more simple and I like it. In the future, we should not worry about this problem, since we will write `Q` in a sparse matrix.

---

*[drake/solvers/mathematical_program.cc, line 867 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedxlRw77KGCrq5rzKq:-KefAxfIZ6O2csOkPnzy:bg125e4) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L867)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `is_Q_zero` is true under all of the unit tests. Does this mean we need more test cases?
</blockquote></details>

Done. Based on a f2f discussion, the test covers the other branch.

---

*[drake/solvers/mathematical_program.cc, line 871 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kedwmj7plg4a5QQEVUa:-KefB7bu_1fPWt-OR6rp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L871)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Similarly, consider the following:
```c++
      const bool is_b_zero = (b.array() == 0.0).all();
```
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 911 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedyfBwm6LwevyHkAEA:-KefBQYmkUhoptn3EMxm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L911)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, consider marking it as `const`.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 912 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedyjjNAZWA4hyuubSp:-KefBbS0XZ4s3fpjEo3k:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L912)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is `int j = 0;` a typo of `int j = i`?
</blockquote></details>

Done. Good call.

---

*[drake/solvers/mathematical_program.h, line 1482 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebfRdma9lltqw3HZAB:-KefBr8IwoBf8GW6jRF-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1482)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think the uses of `v1/v2` and `linear_expr/quadratic_expr` are a bit confusing. Probably better to use `v1` and `v2` in the API but to document that they are 'linear expression'/'quadratic' expression?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1486 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kebf9p-bzwpFcNa_bng:-KefG926pcjMYhftveAe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1486)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, today I learned from @sherm1 that the curly braces `{` and `}` are not necessary here. Could you double-check it by running Doxygen and checking the result?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1492 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebfmBLiIB9Ewn7Y3sD:-KefIUwAXd-PK_hv90Uu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1492)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's better to have `runtime_error` instead of `runtime error`.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1495 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kebg8Eo5cXYiKnWvQ8D:-KefGySBlD3Wig5azHY7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1495)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think it's more readable if we indent `z = ...` and `y = ...` (four spaces?)
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1497 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KebgGtBBQDgkUe9isi6:-KefH0-HsKtzf-30F2Zn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.h#L1497)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, probably better to avoid the repeated `where` here?
Is `while` better?
</blockquote></details>

Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedrFaieilbPkZUlAbw:-KefH7A1a93KVigSjkPS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `#include "drake/solvers/mathematical_program.h"` should be atop this file.
</blockquote></details>

Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-3CcwE2M71Iwv0G_:-KefHHA90g2yoOfAIkhX:bw4zdjh) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1141)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, consider the following code:
```c++
  return std::all_of(poly_diff.begin(), poly_diff.end(), [&tol](const auto& p) {
    return std::abs(symbolic::get_constant_value(p.second)) <= tol;
  });
```
Note that you need `#include <algorithm>` to use `std::all_of`.
</blockquote></details>

Done. Is there a speed advantage using `all_of`

---

*[drake/solvers/test/mathematical_program_test.cc, line 1166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-rf0Oqmxakkz3o7_:-KefI6bx8e5O2jLN3RsF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1166)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Consider reflowing this section.
</blockquote></details>

Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-zouwUu6nXnr6zew:-KefI7ypGkFt3DRd-Cip:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1168)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, typo of `be equal`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-:-KefKdLyf1Luct__bbZF:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 855 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-KedwO3Sc6ZxiG5MiMOP:-KefKm7f4yP6-T0dDvmQ:bjbai6e) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/mathematical_program.cc#L855)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I think there is slight performance penalty, which checks all entries in Q, while the for loop only checks the lower triangular part of Q. But the one line code is a lot more simple and I like it. In the future, we should not worry about this problem, since we will write `Q` in a sparse matrix.
</blockquote></details>

You're right. Good to know!

---

*[drake/solvers/test/mathematical_program_test.cc, line 1141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kee-3CcwE2M71Iwv0G_:-KefL36SKw4axlnIe4Lf:b-6evas0) ([raw file](https://github.com/robotlocomotion/drake/blob/6f8c869bc7ea4bf316258c5fe621d7c84178872e/drake/solvers/test/mathematical_program_test.cc#L1141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Is there a speed advantage using `all_of`
</blockquote></details>

Probably not right now, just cleaner I think. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-:-KefLxHLgSnzGrJiGCie:bpk00vl)*

**Comment by sammy-tri** [comment]
:lgtm:  (with the note that I'm trusting the feature reviewer on the math to some extent...)

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1211 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kej40TNdUonhN6uGFay:-Kej40TNdUonhN6uGFaz:b-u2ie17) ([raw file](https://github.com/robotlocomotion/drake/blob/a62724100288ddd5e7d16894fce7e843ea921800/drake/solvers/test/mathematical_program_test.cc#L1211)):*
> ```cpp
> }  // namespace
> 
> class SymbolicLorentzConeTest : public ::testing::Test {
> ```

BTW this file is pretty long, I wonder if it's worth moving the tests for the lorentz cone constraints into their own .cc file.  No need to do that as part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-:-Kej4GtcqfdaxcPboEfQ:bhoper2)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1211 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5433#-Kej40TNdUonhN6uGFay:-Kej6RNJsm6Lt8vPcHer:bwymgh3) ([raw file](https://github.com/robotlocomotion/drake/blob/a62724100288ddd5e7d16894fce7e843ea921800/drake/solvers/test/mathematical_program_test.cc#L1211)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW this file is pretty long, I wonder if it's worth moving the tests for the lorentz cone constraints into their own .cc file.  No need to do that as part of this PR.
</blockquote></details>

Good point, I will refactor this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5433)*

**Pull request merged**
