### PR TITLE
[doc] Add a tip for improving DiagramBuilder performance

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16384)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews, please.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with one ignorable suggestion

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16384#-:-MtOxW6JA-ldXw_HMH1f:b-ck4afu)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram_builder.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16384#-MtOxBPC5sBJidtfqR5b:-MtOxBPD8WOjnURt6-8m:byl7van) ([raw file](https://github.com/robotlocomotion/drake/blob/e42c542eb0394845fc67e93e4e2e3c00aea6a6e9/systems/framework/diagram_builder.h#L53)):*
> ```objc
> /// DeclareOutputPort family of functions.  If the default value is used (i.e.,
> /// when no prerequisites are provided), the default is to assume the output
> /// port value is dependent on all possible sources.
> ```

BTW consider mentioning `all_sources_except_input_ports_ticket()` either here or as an additional DeclareLeafOutputPort_feedthrough example.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16384)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @sherm1)

___
*[systems/framework/diagram_builder.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16384#-MtOxBPC5sBJidtfqR5b:-MtP5d2l5IXYclb0NvYJ:b-ftow0a) ([raw file](https://github.com/robotlocomotion/drake/blob/e42c542eb0394845fc67e93e4e2e3c00aea6a6e9/systems/framework/diagram_builder.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider mentioning `all_sources_except_input_ports_ticket()` either here or as an additional DeclareLeafOutputPort_feedthrough example.
</blockquote></details>

I like it.  Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16384)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
