### PR TITLE
Annotate packages with their licenses

### PR DESCRIPTION
**Pull request by jamiesnape**
This is toward distilling the information into #4045 into something that we can programmatically enforce. Of course, really every `BUILD` file in Drake also needs annotating, but this is a start.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8447)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Review status: 0 of 63 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/expat/repository.bzl, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8JDwBD6CeWPn3_bQ0G:-L8JDwBD6CeWPn3_bQ0H:b-dvgo3h) ([raw file](https://github.com/robotlocomotion/drake/blob/71353a820d7934ae904fece37e5bd987240724ee/tools/workspace/expat/repository.bzl#L68)):*
> ```Python
> 
> expat_repository = repository_rule(
>     # TODO(jamiesnape): Pass down licenses to setup_pkg_config_repository.
> ```

BTW You would think this would be easy, but Bazel crashes and burns with an internal exception when you add `"licenses": attr.string_list(default = ["notice"])` to the `attrs` below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8447)*

**Comment by jamiesnape** [comment]
Note this is not the whole story as we have undeclared transitive dependences pulled in only via pkg-config.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 54 of 63 files at r1, 2 of 4 files at r2.
Review status: 56 of 64 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KBWsiQqmYNAUbcrUV:-L8KBWsiQqmYNAUbcrUW:b-il7zpg) (no related file):*
> Note this is not the whole story as we have undeclared transitive dependences pulled in only via pkg-config.

This seems worth keeping track of.  Maybe this should be a TODO in pkg_config_repository.bzl?

---

*[tools/workspace/pkg_config.bzl, line 257 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8K-Xq9SXm8jx7N0DuR:-L8K-Xq9SXm8jx7N0DuS:b-n0dy2l) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/pkg_config.bzl#L257)):*
> ```Python
> Args:
>     name: A unique name for this rule.
>     licenses: Licenses of the library.
> ```

BTW Is this a good place to cite https://docs.bazel.build/versions/master/be/functions.html#licenses_args?

---

*[tools/workspace/bullet/package.BUILD.bazel, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8K7cBTcArMUDFgr0wt:-L8K7cBTcArMUDFgr0wu:bsalb6f) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/bullet/package.BUILD.bazel#L13)):*
> ```
> licenses([
>     "notice",  # Zlib
>     "restricted",  # LGPL-2.1+
> ```

So at first I was confused because Bullet's top-level LICENSE.txt didn't mention anything but ZLib (we don't use "Extras" or "examples").

But then I found the Gimpact files and understood where the LGPL note came from per #7582.

However, now on second look, it seems to me like all of the Gimpact sources allow LGPL **or** BSD3 **or** Zlib.  So I think we can just be Zlib here (possibly with a comment about this oddity).

(FYI I suppose we could also open an issue to go back to linking bullet statically and even privately -- it looks plausible to we could isolate its headers to be cc-only, withi a little refactoring.)

---

*[tools/workspace/drake_visualizer/repository.bzl, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KCcTgdho7SvBBO2HV:-L8KCcTgdho7SvBBO2HW:b-w5hh7n) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/drake_visualizer/repository.bzl#L70)):*
> ```Python
>     "notice",  # Apache-2.0 AND BSD-3-Clause
>     "restricted",  # LGPL-2.1+
> ])
> ```

Is there some more detailed reasoning (comments) we could add here?  I assume that some of its compile-time dependencies are what gets us these licenses.  A TODO to add such a comment would also be OK by me.

---

*[tools/workspace/godotengine/package.BUILD.bazel, line 108 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KDrOFdiKe6_mXSVWJ:-L8KDrOFdiKe6_mXSVWK:b-9x0d5w) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/godotengine/package.BUILD.bazel#L108)):*
> ```
>     "thirdparty/misc/**",
>     "thirdparty/zstd/**",
> ]
> ```

FYI Do you want a reminder comment here about double-checking for any new licenses?

---

*[tools/workspace/stx/package.BUILD.bazel, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KGenqeC28gOUP52mj:-L8KGenqeC28gOUP52mk:b-su8vci) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/stx/package.BUILD.bazel#L10)):*
> ```
> )
> 
> licenses(["notice"])  # BSL-1.0
> ```

The `stx::variant` class is `BSD-3-Clause`.   We're not using it yet, though there is interest, so might as well list it now?

Or in the alternative, add a reminder below about it, for if / when we do add `variant`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-:-L8KI-6igj86Y5_2PfrE:by96gdd)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 63 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[tools/workspace/freetype2/repository.bzl, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8Khoy32XSuQ10UFsa4:-L8Khoy32XSuQ10UFsa5:b-pzic1f) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/freetype2/repository.bzl#L12)):*
> ```Python
>         licenses = [
>             "notice",  # BSD-2-Clause AND BSD-3-Clause
>             "restricted",  # FTL OR GPL-2.0+
> ```

I haven't looked deeply, but it seems like FTL is `"notice"`, such that we'd chose to use that license and not have any `"restricted"` provisions?

---

*[tools/workspace/freetype2/repository.bzl, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KiEF--mG_6nL2Y7Eu:-L8KiEF--mG_6nL2Y7Ev:bn0ltcw) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/freetype2/repository.bzl#L15)):*
> ```Python
>         ],
>         modname = "freetype2",
>         pkg_config_paths = ["/usr/local/opt/freetype/lib/pkgconfig"],
> ```

BTW Please mention this change in the commit message.

---

*[tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KjxmZ0pfYgqCdS7s_:-L8KjxmZ0pfYgqCdS7sa:b-5pk0nr) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel#L4)):*
> ```
> 
> licenses([
>     "none",
> ```

Where does `"none"` arise from?  I thought that RobotLocomotion/lcmtypes#2 had covered everything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8447)*

**Comment by jamiesnape** [comment]
Review status: 59 of 64 files reviewed at latest revision, 10 unresolved discussions.

---

*[tools/workspace/pkg_config.bzl, line 257 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8K-Xq9SXm8jx7N0DuR:-L8UdVk8VI4nIjI1yAqO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/pkg_config.bzl#L257)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this a good place to cite https://docs.bazel.build/versions/master/be/functions.html#licenses_args?
</blockquote></details>

Done.

---

*[tools/workspace/bullet/package.BUILD.bazel, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8K7cBTcArMUDFgr0wt:-L8UeLDjxa7c_cD1cf0k:b-7q28it) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/bullet/package.BUILD.bazel#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So at first I was confused because Bullet's top-level LICENSE.txt didn't mention anything but ZLib (we don't use "Extras" or "examples").

But then I found the Gimpact files and understood where the LGPL note came from per #7582.

However, now on second look, it seems to me like all of the Gimpact sources allow LGPL **or** BSD3 **or** Zlib.  So I think we can just be Zlib here (possibly with a comment about this oddity).

(FYI I suppose we could also open an issue to go back to linking bullet statically and even privately -- it looks plausible to we could isolate its headers to be cc-only, withi a little refactoring.)
</blockquote></details>

Done. The google3 way of structuring this would be put Gimpact as a separate target since it is licensed differently, which would make things more explicit.

---

*[tools/workspace/freetype2/repository.bzl, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8Khoy32XSuQ10UFsa4:-L8UdZQ4cGonRPaF2kuc:b-6cfvtr) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/freetype2/repository.bzl#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I haven't looked deeply, but it seems like FTL is `"notice"`, such that we'd chose to use that license and not have any `"restricted"` provisions?
</blockquote></details>

Done. You are correct; it is BSD-style.

---

*[tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KjxmZ0pfYgqCdS7s_:-L8UdgN_S5Ah9ET3hxw2:b-3smg3f) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Where does `"none"` arise from?  I thought that RobotLocomotion/lcmtypes#2 had covered everything.
</blockquote></details>

Done. It did, removed.

---

*[tools/workspace/stx/package.BUILD.bazel, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KGenqeC28gOUP52mj:-L8UdkoyJHRx2I3K1_8f:bbzyphn) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/stx/package.BUILD.bazel#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `stx::variant` class is `BSD-3-Clause`.   We're not using it yet, though there is interest, so might as well list it now?

Or in the alternative, add a reminder below about it, for if / when we do add `variant`.
</blockquote></details>

Done. Possibly per target license tags would be better, but since they are both `notice`, I guess it does not really matter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8447)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8447)*

**Comment by jamiesnape** [comment]
Review status: 61 of 64 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447#-L8KBWsiQqmYNAUbcrUV:-L8Y8Gts6sKfovKJOtNQ:b-8po0tb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Note this is not the whole story as we have undeclared transitive dependences pulled in only via pkg-config.

This seems worth keeping track of.  Maybe this should be a TODO in pkg_config_repository.bzl?
</blockquote></details>

Done. Part of me wonders whether using `pkg-config` is the greatest idea in this respect. Not using it makes things brittle, but using it means hidden dependencies. I guess there is nothing stopping us adding extra `pkg-config` calls for the `deps` even if they are semi-redundant.

---

*[tools/workspace/drake_visualizer/repository.bzl, line 70 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447#-L8KCcTgdho7SvBBO2HV:-L8Y8zROCOF-NIXM3uNA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/drake_visualizer/repository.bzl#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is there some more detailed reasoning (comments) we could add here?  I assume that some of its compile-time dependencies are what gets us these licenses.  A TODO to add such a comment would also be OK by me.
</blockquote></details>

Done.

---

*[tools/workspace/freetype2/repository.bzl, line 15 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447#-L8KiEF--mG_6nL2Y7Eu:-L8Y93yQ12NF0QZbA9ZC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/freetype2/repository.bzl#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Please mention this change in the commit message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447)*

**Comment by jamiesnape** [comment]
Review status: 60 of 64 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/workspace/godotengine/package.BUILD.bazel, line 108 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447#-L8KDrOFdiKe6_mXSVWJ:-L8YAsWO9Ljmc9Oguhxq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/342333b1447449eb4262bd8aec490ad3acd3b6ef/tools/workspace/godotengine/package.BUILD.bazel#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Do you want a reminder comment here about double-checking for any new licenses?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@sammy-tri for platform review, please.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-L8KBWsiQqmYNAUbcrUV:-L8Ywk-SFhJbH3ocQ5mI:bc215ci) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done. Part of me wonders whether using `pkg-config` is the greatest idea in this respect. Not using it makes things brittle, but using it means hidden dependencies. I guess there is nothing stopping us adding extra `pkg-config` calls for the `deps` even if they are semi-redundant.
</blockquote></details>

OK

Yeah my intuition would be to still call `pkg-config` but to somehow interlock that its recursive `-lfoo` flags (or possibly `Requires:` instead) turn into `@name` deps instead of `linkopts = ["-lname"]`.  So if a `.pc` file mentions something new, we (by default) fail.  This would be listing out all of the transitive deps in WORKSPACE, but that is probably good in any case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8447#-:-L8Yx_0PA9-7uZ-lJDvB:b-3v5mxt)*

**Comment by jamiesnape** [comment]
(resolved merge conflict)

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 52 of 63 files at r1, 3 of 4 files at r2, 4 of 5 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8447#-:-L8Z9n4gBgaIzuW9VS1e:bnfp4nl)*

**Pull request merged**
