### PR TITLE
Warn the user if the psd constraint has 1 or 2 rows.

### PR DESCRIPTION
**Pull request by hongkai-dai**
It is better to impose a linear inequality constraint or rotated Lorentz cone constraint in this case.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21657)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-:-O0jlLl4EBVT2Bwyi7o8:b7vod24)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-:-O0t1O0T8n95LGgqBdKe:bg7igkv)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/constraint.h` line 936 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t0SMh0MFfLhxmG7a5:-O0t0SMh0MFfLhxmG7a6:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.h#L936)):*
> ```objc
>    * @note `rows` should be a positive integer. If `rows`==1 or `rows`==2, then
>    * reconsider to impose a linear inequality or rotated Lorentz cone constraint
>    * respectively.
> ```

nit



_Suggestion:_
```objc
   * @note `rows` should be a positive integer. If `rows`==1 or `rows`==2, then
   * consider imposing a linear inequality or rotated Lorentz cone constraint
   * respectively.
```
___
*[`solvers/constraint.h` line 1032 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t0lLt7bIgrFLPC6ra:-O0t0lLt7bIgrFLPC6rb:bb7lc5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.h#L1032)):*
> ```objc
>  * a rotated Lorentz cone constraint, since a 2 x 2 matrix X being p.s.d is
>  * equivalent to the constraint [X(0, 0), X(1, 1), X(0, 1)] in the rotated
>  * Lorentz cone.
> ```

nit:



_Suggestion:_
```objc
 * @note if the matrices Fᵢ all have 1 row, then it is better to impose a linear
 * inequality constraints; if they all have 2 rows or fewere, then it is better to impose
 * a rotated Lorentz cone constraint, since a 2 x 2 matrix X being p.s.d is
 * equivalent to the constraint [X(0, 0), X(1, 1), X(0, 1)] in the rotated
 * Lorentz cone.
```
___
*[`solvers/constraint.cc` line 657 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t1-XSAsdsTfqb5OSh:-O0t1-XSAsdsTfqb5OSi:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L657)):*
> ```cpp
>         "PositiveSemidefiniteConstraint: rows==1, please consider to "
>         "re-formulate this as a linear inequality constraint for better "
>         "speed/numerics.");
> ```





_Suggestion:_
```cpp
        "PositiveSemidefiniteConstraint: rows==1, please consider "
        "reformulating this as a linear inequality constraint for better "
        "speed/numerics.");
```
___
*[`solvers/constraint.cc` line 662 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t12XcDEjcZ0oXezKZ:-O0t12XcDEjcZ0oXezK_:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L662)):*
> ```cpp
>         "PositiveSemidefiniteConstraint: rows==2, please consider to "
>         "re-formulate this as a rotated Lorentz cone constraint for better "
>         "speed/numerics.");
> ```





_Suggestion:_
```cpp
        "PositiveSemidefiniteConstraint: rows==2, please conside "
        "reformulating this as a rotated Lorentz cone constraint for better "
        "speed/numerics.");
```
___
*[`solvers/constraint.cc` line 742 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t1DUS6QYvekn_dUiO:-O0t1DUS6QYvekn_dUiP:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L742)):*
> ```cpp
>         "LinearMatrixInequalityConstraint: the matrix has size 1. Please "
>         "impose it as a linear inequality constraint for better "
>         "speed/numerics.");
> ```





_Suggestion:_
```cpp
        "LinearMatrixInequalityConstraint: the matrix has size 1. Please consider "
        "reformulating this as a linear inequality constraint for better "
        "speed/numerics."");
```
___
*[`solvers/constraint.cc` line 747 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t1I75AnYDX6KXOijq:-O0t1I75AnYDX6KXOijr:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L747)):*
> ```cpp
>         "LinearMatrixInequalityConstraint: the matrix has size 2. Please "
>         "impose it as a rotated Lorentz cone constraint for better "
>         "speed/numerics.");
> ```





_Suggestion:_
```cpp
        "LinearMatrixInequalityConstraint: the matrix has size 2. Please consider "
        "reformulating this as a rotated Lorentz cone constraint for better "
        "speed/numerics.");
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21657)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/constraint.h` line 1032 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t0lLt7bIgrFLPC6ra:-O18QSbn4ZZE_VjxkkiN:b-914wfg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.h#L1032)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit:
</blockquote></details>

All of Fi should have the same number of rows, so they should all have 1 rows, or all have 2 rows, etc.
___
*[`solvers/constraint.cc` line 657 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t1-XSAsdsTfqb5OSh:-O18QeZSDyEBtcXOhrRV:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L657)):*
> ```cpp
>         "PositiveSemidefiniteConstraint: rows==1, please consider to "
>         "re-formulate this as a linear inequality constraint for better "
>         "speed/numerics.");
> ```

Done.
___
*[`solvers/constraint.cc` line 662 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t12XcDEjcZ0oXezKZ:-O18Qhm63Lq4Aakhx_VZ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L662)):*
> ```cpp
>         "PositiveSemidefiniteConstraint: rows==2, please consider to "
>         "re-formulate this as a rotated Lorentz cone constraint for better "
>         "speed/numerics.");
> ```

Done.
___
*[`solvers/constraint.cc` line 742 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t1DUS6QYvekn_dUiO:-O18QqnE4j-n1QwGlFk6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L742)):*
> ```cpp
>         "LinearMatrixInequalityConstraint: the matrix has size 1. Please "
>         "impose it as a linear inequality constraint for better "
>         "speed/numerics.");
> ```

Done.
___
*[`solvers/constraint.cc` line 747 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O0t1I75AnYDX6KXOijq:-O18QwZ9Arzh4ovIMNBQ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4040b354604617941427cb8160f90eff4323e399/solvers/constraint.cc#L747)):*
> ```cpp
>         "LinearMatrixInequalityConstraint: the matrix has size 2. Please "
>         "impose it as a rotated Lorentz cone constraint for better "
>         "speed/numerics.");
> ```

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With editorial comment.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-:-O1I5wE34XUsTUtWI4ev:b-79zqp9)* status: 1 unresolved discussion

___
*[`solvers/constraint.cc` line 655 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21657#-O1I5lUg1Dwo1bQEGJw_:-O1I5lUg1Dwo1bQEGJwa:bw4jhkq) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e6a5f652f78de01fe7069559f5d41f28757eaab/solvers/constraint.cc#L655)):*
> ```cpp
>   if (matrix_rows_ == 1) {
>     drake::log()->warn(
>         "PositiveSemidefiniteConstraint: rows==1, please consider to "
> ```

nit: Edit; simply remove "to"

(Same below)



_Code quote:_
```cpp
 to 
```

**Pull request merged**
