### PR TITLE
Implements Newton method with bisection fallback

### PR DESCRIPTION
**Pull request by amcastro-tri**
This method is used as our "exact" line search option in SAP.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N3WAcHo8buroAtVXKUF:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
-@xuchenhan-tri (out of office)

+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N3Ze2cO1k91qku4TB5A:boubjlf)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a few questions. This is a fairly robust root finder, I addressed some possible numerical issues below but as is for typical functions and arguments I think this is ready to go. +@ericcousineau-tri for platform review, please.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N48GWTW1dsTXWls83hz:b-mpu0s5)* status: 7 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/contact_solvers/newton_with_bisection.h` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N47y2TO3a3E21NXtmum:-N47y2TO3a3E21NXtmun:b-u2kva5) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.h#L22)):*
> ```objc
>   tolerance `abs_tolerance`, i.e. when |xᵏ⁺¹ - xᵏ| < abs_tolerance.
> 
>   This method iteratively shrinks the bracket containing the root. Moreover, it
> ```

nit: Not sure if it is important to say that the function may not shrink the bracket at all if it happens to get lucky and land exactly on a root.
You don't violate the tolerance statement, but you might not be able to give a witness bracket (case of a double root, etc.)



_Code quote:_
```objc
This method iteratively shrinks the bracket containing the root.
```
___
*[`multibody/contact_solvers/newton_with_bisection.h` line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N48E0fAEAACx0vTY0RW:-N48E0fAEAACx0vTY0RX:bybldyo) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.h#L38)):*
> ```objc
>   H(x) - 1/2, with H(x) the Heaviside function. While discontinuous at x = 0,
>   this method will return x = 0 as the root.
> ```

nit: Consider adding a TODO here to explore things like using a secant method as opposed to subdivision when Newton is slow (of course still needing to fallback to subdivision for robustness. Also would there ever be the possibility of using Householder methods, or are higher order derivatives for the expected functions expected to not be available?
You could also try backtracking here when Newton's method goes wildly out of the interval. Just some possibilities.
___
*[`multibody/contact_solvers/newton_with_bisection.h` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N483YRx427Hlm6k4hcq:-N483YRx427Hlm6k4hcr:b-ya9awp) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.h#L44)):*
> ```objc
>   @pre x_guess is in [x_lower, x_upper]
>   @pre sign(function(x_lower)) != sign(function_x_upper)
>   @pre abs_tolerance > 0
> ```

nit: If I give an abnormally small `abs_tolerance`, say a de-normalized double like `1e-300` will this pose a problem? I suppose for a well behaved function that Newton or bisection will eventually land on the root exactly (given it is a representable double) and return it, and that iterate will have 0 error?



_Code quote:_
```objc
@pre abs_tolerance > 0
```
___
*[`multibody/contact_solvers/newton_with_bisection.cc` line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N489dVVBHeHsIVQ_sNH:-N489dVVBHeHsIVQ_sNI:bwjukvk) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.cc#L41)):*
> ```cpp
>   // Verify there is a root inside the bracket. Notice that f_lower * f_upper !=
>   // 0 since the case f_lower == 0 || f_upper == 0 has been ruled out above.
>   DRAKE_THROW_UNLESS(f_lower * f_upper < 0);
> ```

nit: This might be a little dangerous as a sign checking function. Take for example the following test case:
```
{.description = "y = x",
                    [](double x) {
                      return std::make_pair(x, 1);
                    },
                    .a = -1e-162,
                    .b = 1e-162,
                    .guess = 0.0,
                    .root = 0.0,
                    .max_iterations = 100}
```

This case will fail on this line, even though I would argue that it is a valid interval and the function evaluates correctly. I know it is a bit of an adversarial case, but it is a slight numerical bug nonetheless. A proper `sign(x)` function with `sign(f_lower) != sign(f_upper)`would do, or even just:
```
(f_lower < 0 && f_upper > 0) || (f_lower > 0 && f_upper < 0)
```



_Code quote:_
```cpp
  DRAKE_THROW_UNLESS(f_lower * f_upper < 0);
```
___
*[`multibody/contact_solvers/newton_with_bisection.cc` line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N48DQS39Jt8WT38UUei:-N48DQS39Jt8WT38UUej:b-uo3x6n) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.cc#L85)):*
> ```cpp
>     // |fᵏ⁻¹|. That is, we use Newton's method when |fᵏ| < |fᵏ⁻¹|/2. Otherwise
>     // we use bisection which guarantees convergence, though linearly.
>     const bool newton_is_slow = 2.0 * abs(f) > abs(minus_dx * df);
> ```

nit: Is it worth checking this on each iteration? Even if Newton's method is converging slowly, will it ever be sublinear? (i.e. *worse* than subdivision). You might find that doing this check every other iteration or even less frequent might save some CPU cycles.



_Code quote:_
```cpp
    const bool newton_is_slow = 2.0 * abs(f) > abs(minus_dx * df);
```
___
*[`multibody/contact_solvers/newton_with_bisection.cc` line 115 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N48FQeT0GZuBQRh-0kT:-N48FQeT0GZuBQRh-0kU:bwlubny) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.cc#L115)):*
> ```cpp
>     // Update the bracket around root to guarantee that there exist a root
>     // within the interval [x_lower, x_upper].
>     if (f * f_upper < 0.0) {
> ```

nit: again this might pose numerical issues.



_Code quote:_
```cpp
if (f * f_upper < 0.0)
```
___
*[`multibody/contact_solvers/newton_with_bisection.cc` line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N48FaBu116SaQgO5H4M:-N48FaBu116SaQgO5H4N:b7t6ti6) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.cc#L128)):*
> ```cpp
>   // small.
>   throw std::runtime_error(
>       fmt::format("NewtonWithBisectionFallback did not converge.\n"
> ```

nit: It might be useful to also just spit out the actual values of `x_lower` and `x_upper` in this error.



_Code quote:_
```cpp
  throw std::runtime_error(
      fmt::format("NewtonWithBisectionFallback did not converge.\n"
                  "|dx| = {}. |x_upper - x_lower| = {}",
                  abs(minus_dx), abs(x_upper - x_lower)));
```
___
*[`multibody/contact_solvers/test/newton_with_bisection_test.cc` line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N48GHc8C9_ejkPId0gB:-N48GHc8C9_ejkPId0gC:b-deicxg) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/test/newton_with_bisection_test.cc#L51)):*
> ```cpp
>   std::optional<int> num_iterations;
> };
> ```

BTW very nice tests! I can't really think of another case to stress test it other than the one mentioned above. :+1:

**Review by amcastro-tri — COMMENTED** [review]
I made some updates to this code as I profiled some cases with SAP.
Would you guys prefer to merge this as is and update in a follow up PR or would you like me to make the updates in this same PR?
I'm ok either way.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N4S5u7Q2q-v8gPJJviG:b-vjc3ia)* status: 9 unresolved discussions (waiting on @amcastro-tri)

**Review by joemasterjohn — COMMENTED** [review]
I don't mind if you make updates in this same PR. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N4S_bt_-d6rlgdvZbzg:bbc6w69)* status: 9 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
ok, I pushed my latest updates to this PR. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N4d96qE6icMI8PzjgIv:b-scbl4)* status: 11 unresolved discussions (waiting on @amcastro-tri, @EricCousineau-TRI, and @joemasterjohn)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @joemasterjohn)

___
*[`multibody/contact_solvers/newton_with_bisection.h` line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N4SfjiGEsi7wH2G_FDA:-N4d9Mng2HcycUzQ8C4X:b-l8v1bn) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.h#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear what a discontinuous function should look like in its returned gradient.

Do you have a recommendation on how to indicate a non-existent gradient? Return zero, a subgradient, inf, or NaN?
</blockquote></details>

Now only continuous functions are allowed. 
___
*[`multibody/contact_solvers/newton_with_bisection.h` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N49LE_YCF4EIaZH2r1b:-N4dA-hI0khAoxVmWww9:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.h#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit While internal + implicit to fact it's Newton-Raphson, I didn't see description of what `function` should return. From code, I see it's `f, df = function(x)`.

Can that be mentioned briefly in docstring?
</blockquote></details>

Done
___
*[`multibody/contact_solvers/newton_with_bisection.cc` line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N489dVVBHeHsIVQ_sNH:-N4dA2_RAMlr9Jw1pt5m:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.cc#L41)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: This might be a little dangerous as a sign checking function. Take for example the following test case:
```
{.description = "y = x",
                    [](double x) {
                      return std::make_pair(x, 1);
                    },
                    .a = -1e-162,
                    .b = 1e-162,
                    .guess = 0.0,
                    .root = 0.0,
                    .max_iterations = 100}
```

This case will fail on this line, even though I would argue that it is a valid interval and the function evaluates correctly. I know it is a bit of an adversarial case, but it is a slight numerical bug nonetheless. A proper `sign(x)` function with `sign(f_lower) != sign(f_upper)`would do, or even just:
```
(f_lower < 0 && f_upper > 0) || (f_lower > 0 && f_upper < 0)
```
</blockquote></details>

Done
___
*[`multibody/contact_solvers/newton_with_bisection.cc` line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N48DQS39Jt8WT38UUei:-N4dA7v954rxgMwnNFc6:b65surt) ([raw file](https://github.com/robotlocomotion/drake/blob/1b518703045b05b3c5d55982270d220a46c717de/multibody/contact_solvers/newton_with_bisection.cc#L85)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Is it worth checking this on each iteration? Even if Newton's method is converging slowly, will it ever be sublinear? (i.e. *worse* than subdivision). You might find that doing this check every other iteration or even less frequent might save some CPU cycles.
</blockquote></details>

Good question. I'll double check.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313)* status: 2 unresolved discussions (waiting on @amcastro-tri and @joemasterjohn)

___
*[`multibody/contact_solvers/newton_with_bisection.h` line 40 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N4dSVEw0O2K7Pq_ECFj:-N4dSVEx5-58eazgUAHb:bqod5oi) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0870b824f4d5aa42ec7df58ac792257ee93071/multibody/contact_solvers/newton_with_bisection.h#L40)):*
> ```objc
>     using std::abs;
>     using std::max;
>     // const double scale = max(max(abs(x_lower_),abs(x_upper_)), abs(x));
> ```

nit Dead code?

**Review by joemasterjohn — COMMENTED** [review]
I think these changes look great! Adding the function convergence criteria seems like a smart way to eliminate unneeded iterations. :lgtm_strong:  

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17313#-:-N5AxXLe7xH6Kce9dpCQ:bxt1mpn)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/newton_with_bisection.h` line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17313#-N5Au2uCDw91Qkvbv3Sy:-N5Au2uCDw91Qkvbv3Sz:b6zzob8) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0870b824f4d5aa42ec7df58ac792257ee93071/multibody/contact_solvers/newton_with_bisection.h#L110)):*
> ```objc
>   @pre `function` is a C⁰ function.
>   @pre x_lower <= x_upper
>   @pre x_guess is in braket.
> ```

nit: spelling



_Suggestion:_
```objc
bracket
```

**Pull request merged**
