### PR TITLE
[workspace] Upgrade nanoflann_internal to latest release v1.6.2

### PR DESCRIPTION
**Pull request by nicolecheetham**
Upgrades nanoflann_internal to latest v1.6.2

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22130)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot retest linux-noble-clang-bazel-experimental-release please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-noble-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) +(status: single reviewer ok) +@rpoyner-tri for both reviews.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22130#-:-OBBL2Jh5sEk2dnknGmk:b-5rl3xw)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22130#-:-OBBLGHK-eqgcmAOd6-d:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
