### PR TITLE
Render BranchPoints explicitly in maliput::utility::GenerateObj().

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6118)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please.  

(Easy way to get an idea of what the rendering looks like:  view one of the OBJ files in `test/data`.)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkHrcD7DE-icpXB2bJn:b-yswshl)*

**Comment by liangfok** [comment]
When I open the `.obj` files using MeshLab, I get the following error:

screenshot from 2017-05-18 18-18-26

Looking in the `.obj` file, I see it is referencing the following:
```
$ cat StackedBranchPointsObjContent.obj | grep 'usemtl\|mtllib'
mtllib StackedBranchPointsObjContent.mtl
usemtl bland_asphalt
usemtl lane_haze
usemtl marker_paint
usemtl branch_point_glow
```
Should the `.mtl` files be added to this PR?

**Comment by maddog-tri** [comment]
Hmm... well, I did not add the corresponding MTL file because it is not actually needed by the unit-test --- all the MTL files produced are identical at this point (which means that you could copy the one MTL in the `test/data` directory to the appropriate name and get the viewer to work).

I'm kinda divided on whether it is better to have them in or not.  (Heh, can one commit symlinks in git?)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkSjlfj8L4_iLJUlWzS:b-7scrzb)*

**Comment by maddog-tri** [comment]
@drake-jenkins-bot retest this please

(Why did (only) those two builds fail?)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkSlFdFBVOJ-qB1oWwc:b-fyf94a)*

**Comment by liangfok** [comment]
OK I agree the `.mtl` files should not be committed then since they are all identical and are not accessed by the unit test.

From http://stackoverflow.com/questions/15465436/git-how-to-handle-symlinks, git does appear symbolic links!

> Git can handle symlinks just fine as long as the operating system used by all developers supports them.

**Comment by liangfok** [comment]
After generating an OBJ for monolane-onramp-merge, I get the following two errors when I attempt to open the file using Meshlab:






The resulting display does not show any arrows on top of the 10 branch points. Can you take a look? Here is the code I used: 

https://github.com/liangfok/drake/commit/449df2470da6282c83ae8f04d5ef1e64359f6515

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 259 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkTBQ4eSsqfQTjLlM0P:-KkTBQ4eSsqfQTjLlM0Q:b-gyaiqk) ([raw file](https://github.com/robotlocomotion/drake/blob/ab79da223196cb3b47d645b89d546aaaa4f3f580/drake/automotive/maliput/utility/generate_obj.cc#L259)):*
> ```cpp
> // A `Lane`-frame face: a sequence of vertices expressed in the (s,r,h)
> // coordinates of an api::Lane (which is not referenced here).  Each
> // vertex has normal vector also expressed in the `Lane`-frame.
> ```

BTW: nit: missing "a" before "normal".

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 566 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkT8pmQWAF2F2Ku3FF-:-KkT8pmRBBWMH4uoFu1e:b-72oy4j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab79da223196cb3b47d645b89d546aaaa4f3f580/drake/automotive/maliput/utility/generate_obj.cc#L566)):*
> ```cpp
>     const double base_elevation, const double height,
>     GeoMesh* mesh,
>     std::vector<api::GeoPosition>* previous_centers) {
> ```

Consider adding a docstring. In particular, it's not obvious to me what is "previous_centers".

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkSkid-DA1tcz8W4haL:-KkSkid-DA1tcz8W4haM:bioblqv) ([raw file](https://github.com/robotlocomotion/drake/blob/ab79da223196cb3b47d645b89d546aaaa4f3f580/drake/automotive/maliput/utility/test/generate_obj_test.cc#L48)):*
> ```cpp
>     std::ifstream is(path.getStr());
>     std::stringstream ss;
>     std::cout << "FILE '" << path.getStr() << "'\n";
> ```

Remove debug print statements. (I assume this is only for debugging purposes.)

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkT7l0Yztc9Ssw_9-ls:-KkT7l0ZuLPSeBSFcLQf:b-usagn0) ([raw file](https://github.com/robotlocomotion/drake/blob/ab79da223196cb3b47d645b89d546aaaa4f3f580/drake/automotive/maliput/utility/test/generate_obj_test.cc#L234)):*
> ```cpp
>     b.Connect("0", start0, 1., kZeroZ);
>     b.Connect("1", start1, 1., kZeroZ);
>     const std::unique_ptr<const api::RoadGeometry> dut = b.Build({"dut"});
> ```

This line can be deleted. In fact, with this line, this unit test doesn't pass on my machine! I did not investigate why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkTBG7yJVgca2zilJjg:bq59wao)*

**Comment by liangfok** [comment]
The branch points appear OK using `view3dscene` so the aforementioned problems only show up using Meshlab. The following screenshot shows the branch points using `branch_point_elevation = 5.5` and `branch_point_height = 5`.



Since the branch point visualization appears fine using `view3dscene`, I will not hold up this PR because of Meshlab incompatibility, though it would be nice if the generated OBJ files were compatible with Meshlab.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkTGmsfprp5VVrNiqyF:bvsurwm)*

**Comment by maddog-tri** [comment]
I'll take a look.  I am also flummoxed as to why this branch is failing on Jenkins.  :^/

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkU6tM0a7y14srr_meX:b-f7f8yo)*

**Comment by maddog-tri** [comment]
Question:  was the meshlab problem introduced by this branch-point-rendering PR, or did it already occur with the rendering of the onramp?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkU8MYHRpHpx9fZByYd:b-5fu378)*

**Comment by liangfok** [comment]
Good point. The Meshlab problem existed prior to this PR. I simply didn't notice until now. In fact, the branch point arrows do show up in Meshlab (I failed to notice them earlier because they were so small using their default elevation and height settings):




I thus retract my comment about the branch point arrows not showing up in Meshlab.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkVTlOthXm45Jnqixhu:b-noj5jo)*

**Comment by jwnimmer-tri** [comment]
I will do platform review on this, at Daniel's request to help facilitate Matt's PRs merging faster.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkWEfqSxp9H1HsAMup-:bnfp4nl)*

**Comment by maddog-tri** [comment]
Hopefully this commit resolves the unit-test failure in CI.  Let me know if you prefer this in a separate PR.

---

Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkWhao0N5G_AkBg-FdS:b99l6on)*

**Comment by jwnimmer-tri** [comment]
I am OK in same PR.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/maliput/monolane/builder.h, line 309 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkWivSDyNTj2eHrCT5P:-KkWivSEUNIoOXGp_znm:b-paq48q) ([raw file](https://github.com/robotlocomotion/drake/blob/9ef93d9ed2de4842ea49fefff99fd5fb72c00725/drake/automotive/maliput/monolane/builder.h#L309)):*
> ```objc
>  private:
>   std::string id_;
>   std::set<const Connection*> connection_set_;
> ```

FYI `s/set/unordered_set/` would be more conventional C++ (when only membership, not iteration order, is needed).  No defect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkWj5HH_CXkwZi4mDAt:bu30htt)*

**Comment by maddog-tri** [comment]
Review status: 7 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/maliput/monolane/builder.h, line 309 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkWivSDyNTj2eHrCT5P:-KkWkbiSaf9TgYkMJxqL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9ef93d9ed2de4842ea49fefff99fd5fb72c00725/drake/automotive/maliput/monolane/builder.h#L309)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `s/set/unordered_set/` would be more conventional C++ (when only membership, not iteration order, is needed).  No defect.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 259 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkTBQ4eSsqfQTjLlM0P:-KkWiGab8zIJup8zmCVC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/337d6dfd0204f4d7523ba6ecb18f040a26ba93d5/drake/automotive/maliput/utility/generate_obj.cc#L259)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: missing "a" before "normal".
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 566 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkT8pmQWAF2F2Ku3FF-:-KkWkLBk3bGvqXzpW71c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/337d6dfd0204f4d7523ba6ecb18f040a26ba93d5/drake/automotive/maliput/utility/generate_obj.cc#L566)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Consider adding a docstring. In particular, it's not obvious to me what is "previous_centers".
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkSkid-DA1tcz8W4haL:-KkWjnuFJTMlhzm4lSlJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/337d6dfd0204f4d7523ba6ecb18f040a26ba93d5/drake/automotive/maliput/utility/test/generate_obj_test.cc#L48)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Remove debug print statements. (I assume this is only for debugging purposes.)
</blockquote></details>

Done.

---

*[drake/automotive/maliput/utility/test/generate_obj_test.cc, line 234 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-KkT7l0Yztc9Ssw_9-ls:-KkWk7T0K-jdC4eUnZ1H:b-n43n9u) ([raw file](https://github.com/robotlocomotion/drake/blob/337d6dfd0204f4d7523ba6ecb18f040a26ba93d5/drake/automotive/maliput/utility/test/generate_obj_test.cc#L234)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This line can be deleted. In fact, with this line, this unit test doesn't pass on my machine! I did not investigate why.
</blockquote></details>

Done.  (And, two other places, too!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkWlDZCEERSSfbplWVp:b-s794vx)*

**Comment by jwnimmer-tri** [comment]
@liangfok PTAL.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkXFMP2QRbaXI2daLbJ:bnfp4nl)*

**Comment by maddog-tri** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6118#-:-KkXNaxHlAKvr6eE914M:b-l70wzf)*

**Pull request merged**
