### PR TITLE
Consistently use drake::solvers namespace 

### PR DESCRIPTION
**Pull request by sammy-tri**
The drakeOptimization library previously contained a mix of items defined in the Drake and drake::solvers namespaces.  Move everything into drake::solvers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2571)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Added ggould-tri for feature review

**Comment by ggould-tri** [comment]
Lots of nitpicks.  General goodness.  Thanks for taking on this somewhat tedious work.

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/solvers/Constraint.h, line 55 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPb3Q1J0b7R3rycJkC:-KKPb3Q1J0b7R3rycJkD:-1479749313) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/Constraint.h#L55)):*
> ```objc
>   virtual void eval(const Eigen::Ref<const Eigen::VectorXd>& x,
>                     Eigen::VectorXd& y) const = 0;
>   // move this to DifferentiableConstraint derived class if/when we
> ```

(1) cappunc
(2) consider marking this as TODO?

---

*[drake/solvers/IpoptSolver.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbyUdDS-Sor-HhHjH:-KKPbyUdDS-Sor-HhHjI:1394524990) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/IpoptSolver.h#L20)):*
> ```objc
> 
> }  // namespace drake
> }  // namespace solvers
> ```

order here is probably backwards.

---

*[drake/solvers/MathematicalProgram.cpp, line 201 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbv9ZzlCEFmwfQrjh:-KKPbv9ZzlCEFmwfQrji:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/MathematicalProgram.cpp#L201)):*
> ```cpp
> MathematicalProgramSolverInterface::~MathematicalProgramSolverInterface() {}
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---

*[drake/solvers/MathematicalProgram.h, line 52 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbuKfrHIV4WLnrZyV:-KKPbuKfrHIV4WLnrZyW:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/MathematicalProgram.h#L52)):*
> ```objc
> };
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---

*[drake/solvers/MobyLCP.cpp, line 1309 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbfgapZoULvdBEnSm:-KKPbfgapZoULvdBEnSn:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/MobyLCP.cpp#L1309)):*
> ```cpp
> }
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---

*[drake/solvers/NloptSolver.cpp, line 380 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPc5yEThMLehXZxrQH:-KKPc5yEThMLehXZxrQI:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/NloptSolver.cpp#L380)):*
> ```cpp
> }
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---

*[drake/solvers/NloptSolver.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPc7kxCYIQ7yMyaTMF:-KKPc7kxCYIQ7yMyaTMG:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/NloptSolver.h#L19)):*
> ```objc
> };
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---

*[drake/solvers/SnoptSolver.cpp, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcG08Fxww6z08zY0s:-KKPcG08Fxww6z08zY0t:677247605) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.cpp#L26)):*
> ```cpp
> namespace drake {
> namespace solvers {
> namespace {
> ```

Yay!

---

*[drake/solvers/SnoptSolver.cpp, line 248 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcbE2UOW2uLEuipCW:-KKPcbE2UOW2uLEuipCX:-880326281) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.cpp#L248)):*
> ```cpp
>   return 0;
> }
> }
> ```

code conventions prefer `// anon namespace` or similar here

---

*[drake/solvers/SnoptSolver.cpp, line 478 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcJpelOw8yKSGb3yM:-KKPcJpelOw8yKSGb3yN:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.cpp#L478)):*
> ```cpp
> }
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---

*[drake/solvers/SnoptSolver.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcLqcRx6lyKkHM_-Z:-KKPcLqcRx6lyKkHM_-_:489950687) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.h#L19)):*
> ```objc
> };
> 
> }
> ```

code conventions prefer `// namespace solvers` etc. here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-:-KKPchzV1cGHW5L5Nq3u:-743887784)*

**Comment by liangfok** [comment]
Reviewed 17 of 19 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/solvers/Constraint.h, line 92 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPciVOfSFHCiMnrtmj:-KKPciVPoIoWTb5hhvyt:469850698) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/Constraint.h#L92)):*
> ```objc
>     y = .5 * x.transpose() * Q_ * x + b_.transpose() * x;
>   }
>   void eval(const Eigen::Ref<const Drake::TaylorVecXd>& x,
> ```

BTW. Consider putting `using Drake::TaylorVecXd;` at the top of this file so once `TailorVecXd` is moved into namespace `drake` we only need to change one line in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2571)*

**Comment by liangfok** [comment]
Reviewed 2 of 19 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2571)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/solvers/Constraint.h, line 55 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPb3Q1J0b7R3rycJkC:-KKPdrVdg7w41isnLdfz:-246705022) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/Constraint.h#L55)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> (1) cappunc
> (2) consider marking this as TODO?
</details>
Done.  I'm not sure it's actually a TODO, since the idea of DifferentiableConstraint seems itself to be speculative.  I'm almost tempted to delete the comment instead.

---

*[drake/solvers/Constraint.h, line 92 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPciVOfSFHCiMnrtmj:-KKPe3uM8dxHAz3AdD_e:-1310759693) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/Constraint.h#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW. Consider putting `using Drake::TaylorVecXd;` at the top of this file so once `TailorVecXd` is moved into namespace `drake` we only need to change one line in this file.
</details>
I hesitate to use using directives in .h files for fear it might leak into random .cc files without the author's knowledge.  Otherwise I'd agree.

---

*[drake/solvers/IpoptSolver.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbyUdDS-Sor-HhHjH:-KKPeInfSUgddsQTk-eD:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/IpoptSolver.h#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> order here is probably backwards.
</details>
Done.

---

*[drake/solvers/MathematicalProgram.cpp, line 201 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbv9ZzlCEFmwfQrjh:-KKPeOkVAiw-ooPj0Kz3:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/MathematicalProgram.cpp#L201)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---

*[drake/solvers/MathematicalProgram.h, line 52 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbuKfrHIV4WLnrZyV:-KKPeTCzMR9FAdHi7Ukg:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/MathematicalProgram.h#L52)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---

*[drake/solvers/MobyLCP.cpp, line 1309 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPbfgapZoULvdBEnSm:-KKPeVszO98OefIcPyZE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/MobyLCP.cpp#L1309)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---

*[drake/solvers/NloptSolver.cpp, line 380 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPc5yEThMLehXZxrQH:-KKPeZhzZ5PI5BPA82VD:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/NloptSolver.cpp#L380)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---

*[drake/solvers/NloptSolver.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPc7kxCYIQ7yMyaTMF:-KKPebY0_XReB_OxfNSq:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/NloptSolver.h#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---

*[drake/solvers/SnoptSolver.cpp, line 248 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcbE2UOW2uLEuipCW:-KKPedxBwQ619_A-0ssZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.cpp#L248)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// anon namespace` or similar here
</details>
Done.

---

*[drake/solvers/SnoptSolver.cpp, line 478 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcJpelOw8yKSGb3yM:-KKPejD0KTX11HWDvZDq:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.cpp#L478)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---

*[drake/solvers/SnoptSolver.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-KKPcLqcRx6lyKkHM_-Z:-KKPelouT831i6BJGXHT:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/4811d48841e9d5c5f77b0c41895bf4cc472ffe2e/drake/solvers/SnoptSolver.h#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> code conventions prefer `// namespace solvers` etc. here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2571)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
:lgtm:

:ship: :it: 

---

Reviewed 8 of 9 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-:-KKPlO1CdSpD52TMKuN_:-1887528576)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2571#-:-KKQ-I36KLqhy4x8CPSl:-1868698381)*

**Pull request merged**
