### PR TITLE
Improve buildifier on WORKSPACE

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify Bazel style tools to include `WORKSPACE` in files that are automatically processed. Add name priority tables for rules used in `WORKSPACE` to prevent unhelpful reordering. Add `bazel_lint` to root `BUILD` so that it is enforced against `WORKSPACE` (and also, incidentally, against the root `BUILD`). Make necessary style changes so `WORKSPACE` is `bazel_lint`-clean.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6494)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
FYI: The second commit is automated changes only. The changes to the existing table entries are strictly whitespace.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6494#-:-KnuIpM8LjJVonMrhi3B:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
I wonder if there is some way to whitelist from bazel_lint any line that has `sha256 = "` in it.  Shrug.

:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6494#-:-KnuNXLQgXXi1OIYwjQr:byzce1z)*

**Comment by mwoehlke-kitware** [comment]
> I wonder if there is some way to whitelist from bazel_lint any line that has `sha256 = "` in it. 

I thought about that. I'm sure I could disable that check entirely and then copy it into `bzlcodestyle.py` with necessary modifications... I'm just not sure that's worth the effort. I looked around a little but didn't immediately spot any obvious alternatives.

That all said, I wouldn't be surprised if pycodestyle upstream would accept a (configurable) feature along those lines... probably as an option for a regex to exempt from that check.

**Pull request merged**
