### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Companion PR: https://github.com/RobotLocomotion/models/pull/33.

To check that this is satisfactory, we can run the following command:

```
bazel run //tools:model_visualizer -- package://drake_models/tri_homecart/homecart.dmd.yaml
````

The display should be the same on master versus this PR, except that the lighting comes out more nicely.  All of the shapes should still be facing the same way, and all of the textures (metal vs wood) should be the same.

Towards #20932.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039#-:-NrWbuiS51T6VICqdb_z:b-fqjuvi)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21039#-NrWbwEV7TGTdN3HgEXj:-NrWbwEV7TGTdN3HgEXk:brr52r2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4d7dc9dcda897e08fcaa743210a40cd8f0e47cf/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "512978dc9819b8f595bbbd701b90cba2c34caf53",
> ```

Working

Needs bump to the merge commit on master, after the companion PR lands.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Deferring this until we're done with the models PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039#-:-NrfG6Df2lDHvCb6zpvc:b-mcph9m)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039#-:-Nrg4qjfDevD1kYxtGVG:bg7igkv)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21039#-NrWbwEV7TGTdN3HgEXj:-Nrg5P3QAN06KTprSE9_:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d4d7dc9dcda897e08fcaa743210a40cd8f0e47cf/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs bump to the merge commit on master, after the companion PR lands.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039#-:-NrgA8OCB0rSWqrnnQbF:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
Ah, bugger.  It's actually the Xacro & CI pull request that breaking us, not the homecart changes.

I'll see what I can figure out.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21039)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
