### PR TITLE
Added CImg as an external library for image parsing

### PR DESCRIPTION
**Pull request by crogers3**
Adding image parsing external library for parsing Height Maps in C++

### CODE REVIEW

**Comment by rdeits** [comment]
Somehow this broke Matlab's builtin `boolean` command?

**Comment by RussTedrake** [comment]
If we only need the single header file (+ license files), then I recommend adding it to the thirdParty subdirectory of drake instead of having a new external?  Based on a very quick read of the license it seems like that's ok.  But I'd appreciate a second set of eyes on that.

**Comment by crogers3** [comment]
I've restored the main CMakeLists and added the CImg header along with licences and readmes to drake/thirdParty. Please let me know if I am including the library properly in drake/CMakeLists.txt

**Comment by psiorx** [comment]
> Please let me know if I am including the library properly in drake/CMakeLists.txt

Looks right to me.

**Pull request merged**
