### PR TITLE
Add the sliding bricks contact model example

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Two bricks are loaded onto a plane.  A constant force is applied to each.
The brick with zero initial velocity remains "stationary" the brick with
slight initial velocity accelerates.

Illustrates the difference between the static and dynamic friction regimes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5296)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@liangfok for feature review (let me know if you have problems running the demo) +@jwnimmer-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-Kdh2opv8cGt5yaDEdbZ:b-qnrsrg)*

**Comment by SeanCurtis-TRI** [comment]
-@jwnimmer-tri pending successful feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-Kdh67eyc4Zlxek2a4aO:b-ld6xgc)*

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[drake/examples/contact_model/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiWLYrqAHG4Fh33hlF:-KdiWLYrqAHG4Fh33hlG:b-pho4n3) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/CMakeLists.txt#L2)):*
> ```CMake
> if (lcm_FOUND AND Bullet_FOUND)
>   add_executable(sliding_brick sliding_brick.cc)
> ```

BTW, "sliding_brick" should be "sliding_bricks".

---

*[drake/examples/contact_model/sliding_brick.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiWfjI2uhmSdjuesTN:-KdiWfjI2uhmSdjuesTO:b12eli2) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L7)):*
> ```XML
> 
>

**Comment by SeanCurtis-TRI** [comment]
Comments addressed

---

Review status: 1 of 4 files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/examples/contact_model/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiWLYrqAHG4Fh33hlF:-KeFowX40RofUEIrrPVF:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/CMakeLists.txt#L2)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, "sliding_brick" should be "sliding_bricks".
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_brick.urdf, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiWfjI2uhmSdjuesTN:-KeFp64MkAwmsuOSgviK:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding a citation to #4153 after "joints".
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_brick.urdf, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiWxqQS9OEPQ9RdrNV:-KeFpIAIezH5oMXoypdl:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"They the" should be "The".
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_brick.urdf, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiXP92IJLcH8lwMRLQ:-KeFpNNIih88NnPVzf5D:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is it worth adding "world frame's" before "axis"?
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_brick.urdf, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiXCaEDf5FGvFA7MA0:-KeFpRQfA-y9s9IQFnPU:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L23)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I notice you're using capital `{X, Y, Z}` here but you used lower case letters in the diagram above. Consider making it consistent.
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_brick.urdf, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiYguQ8FsuhaUubPDY:-KeFpbkz2NCIJLwbFVMk:bozynrn) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, given the (IMHO) exotic collision model employed, consider add a description of it here.
</blockquote></details>

BTW I've added a TODO to link to the documentation that is to come.

---

*[drake/examples/contact_model/sliding_brick.urdf, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiY5k_rmqn10CUi_PH:-KeFphVgSp77-B-1Y2jx:bg4j6dl) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L47)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW. Wow. I'm surprised a sphere of radius zero is legal. Did you verify that this works in Gazebo? (That's the test I typically do to verify URDF correctness. :blush:)
</blockquote></details>

I hadn't.  I know we've got other URDF files that do this.  I also know, that in Drake, we automatically inflate them to the arbitrary value of 1e-7. (e.g., FallingBrickContactPoints.urdf, CompastGait.urdf, soft_hand.urdf, etc.)

---

*[drake/examples/contact_model/sliding_brick.urdf, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiYyt09ly0Z8x8Hsyt:-KeFqDU4_PpIq2X_Nz0E:bhdzz9l) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_brick.urdf#L111)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, what is `/trunk/j1`?
</blockquote></details>

Done

Haven't a clue.  This is me mindlessly copying and pasting stuff from another functional file.  :)  However, I went ahead and culled a couple of lines that proved to be unnecessary here.  

---

*[drake/examples/contact_model/sliding_bricks.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiZP3DGzT5mwm9xI3Y:-KeFuuwWHz3UiwRAdR2f:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Grammar issue:

> the stationary block a force

</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_bricks.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiZUj00Q1gAjm4cP6m:-KeFux3uTA_NnvCh9TTk:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, extra space after "friction".
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_bricks.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiZdxNOR4_5qmPt2lR:-KeFuz22QakTA1z9Jqq2:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing

> being looping performing

with:

> loop displaying
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_bricks.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KdiZmi3H6jwIDuybsAf:-KeFv4BB-AjZ4w58A2GO:b-x22kxd) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "real-time playback" with "replay in wall clock time" lest a future reader think certain latency guarantees will be met. :smile: 
</blockquote></details>

Done (real-time is the most overloaded, and therefore ambiguous, term in all of computers.)

---

*[drake/examples/contact_model/sliding_bricks.cc, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_DJosiM3VOgc0CUz:-KeFw9ggK3RctUKcR13S:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L36)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing verb and period at end of sentence.

(per style guide)
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_bricks.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_KVJm3ItZ5tH_IL4:-KeFvHlWWkMcH6z6iBFW:b-64bonl) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, that "0" seems superfluous.
</blockquote></details>

Done Or, sadly, it represents a bad type converting the documented 0.1 m/s into 1.0 m/s.  D'oh.

---

*[drake/examples/contact_model/sliding_bricks.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_mBwhIkga9imWpCw:-KeFvUfMY8Jmbyp43_lM:bbvsgxg) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L95)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this fragility can be overcome by using the returned model instance ID when calling `drake::parsers::urdf::AddModelInstanceFromUrdfFile()`.
</blockquote></details>

BTW Isn't there still a couple of levels of indirection?  Am I guaranteed that the model instance id correlates with position in the state vector?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-KeFw5wqwwG5GoR8xjaH:bu9a4i4)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/sliding_bricks.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_mBwhIkga9imWpCw:-KeGInKaIkpJVee-qYPZ:b-p00plj) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L95)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Isn't there still a couple of levels of indirection?  Am I guaranteed that the model instance id correlates with position in the state vector?
</blockquote></details>

You're right, sorry. Eliminating this fragility will require resolving #4371.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-KeGJ67By88Pke28h4Br:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
+@ggould-tri for platform review ... lurking in your queue, waiting to strike as you boot up your machine...

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/contact_model/sliding_bricks.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_mBwhIkga9imWpCw:-KeGJW_6B5qOEsymBYRp:bykwrhn) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L95)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

You're right, sorry. Eliminating this fragility will require resolving #4371.
</blockquote></details>

@4371 impacts everything.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-KeGJiGoZ6c0g1ExakJs:bz0vz5b)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/contact_model/sliding_bricks.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_mBwhIkga9imWpCw:-KeGL-TwV77y1mAYDjD9:b4bbpn1) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L95)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@4371 impacts everything.  :)
</blockquote></details>

#4371 is about diagrams, and about interally-assigned port indices while populating one.  Neither of those two is relevant to the `0` and `1` here.  Only the RBP's design faults are to blame, not the framework.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/sliding_bricks.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-Kdi_mBwhIkga9imWpCw:-KeGWmZ16zjXOJOn03-C:bk5cpmm) ([raw file](https://github.com/robotlocomotion/drake/blob/ab91d02cb7772e7dac030155de3897af90157166/drake/examples/contact_model/sliding_bricks.cc#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

#4371 is about diagrams, and about interally-assigned port indices while populating one.  Neither of those two is relevant to the `0` and `1` here.  Only the RBP's design faults are to blame, not the framework.
</blockquote></details>

Good point! @amcastro-tri, let's make sure `MultibodyWorld` has better accessors that allow obtaining input ports based on model instance ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296)*

**Comment by ggould-tri** [comment]
This is a really nice test -- very clear, and corresponds well to the static friction problems we've had in the past. :lgtm: pending one small remark below.

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/sliding_brick.urdf, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KeJcZKjsj1cdSEnp_sU:-KeJcZKjsj1cdSEnp_sV:b-bst77h) ([raw file](https://github.com/robotlocomotion/drake/blob/3ab6526d863e2fcc6d3022cebd4f06182f8c09da/drake/examples/contact_model/sliding_brick.urdf#L26)):*
> ```XML
> 
>  The fixed joint is implied by how the URDF is added to the tree.  In all other
>  cases, the joint of the body and the name of the body's parent are coordinated.
> ```

I think you probably need to also explain here why a brick is made of zero-radius collision spheres, which is not what most bricks look like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-KeJfDqmIAW2e2XsSdTz:b7g0q4s)*

**Comment by SeanCurtis-TRI** [comment]
Comment addressed.  PTAL if interested.  Otherwise, after CI, I'll merge.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/sliding_brick.urdf, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KeJcZKjsj1cdSEnp_sU:-KeJpofiDikMycI9Z6Ad:b-v303pt) ([raw file](https://github.com/robotlocomotion/drake/blob/3ab6526d863e2fcc6d3022cebd4f06182f8c09da/drake/examples/contact_model/sliding_brick.urdf#L26)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I think you probably need to also explain here why a brick is made of zero-radius collision spheres, which is not what most bricks look like.
</blockquote></details>

I've added a tentative documentation; the full explanation will be in a more complete and general explanation of the contact model and *working* with that contact model.  When that's written, I'll link this to that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-:-KeJq-cZ-fcstXu_w3Mr:b-ocld7g)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/contact_model/sliding_brick.urdf, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5296#-KeJcZKjsj1cdSEnp_sU:-KeJrwSsfy8n9powouhd:b-89q77k) ([raw file](https://github.com/robotlocomotion/drake/blob/3ab6526d863e2fcc6d3022cebd4f06182f8c09da/drake/examples/contact_model/sliding_brick.urdf#L26)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've added a tentative documentation; the full explanation will be in a more complete and general explanation of the contact model and *working* with that contact model.  When that's written, I'll link this to that.
</blockquote></details>

Cool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5296)*

**Pull request merged**
