### PR TITLE
Introduce symbolic PixelFormat, PixelType, and Image.

### PR DESCRIPTION
**Pull request by soonho-tri**
/cc @BachiLi

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8055)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@kunimatsu-tri for feature-review, please.

FYI, this is needed for the symbolic renderer. Please feel free to suggest better names/comments.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-:-L5EtF1H_dd9aKdALN3n:b-258iv)*

**Comment by kunimatsu-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/image.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-L5FHzu1PZpy7BFl5gv1:-L5FHzu1PZpy7BFl5gv2:bcpj24z) ([raw file](https://github.com/robotlocomotion/drake/blob/3dcae8cb79068ceae5bb624049878ade8dd0141f/systems/sensors/image.h#L46)):*
> ```objc
> /// The type for monochrome image where the channel has the type of
> /// symbolic::Expression.
> using ImageExpr1E = Image<PixelType::kExpr1E>;
> ```

In the current convention, the number represents the number of bit for a value in a channel.
For instance,  kRgb8U means a pixel holds four channels where each channel has a 8 bits unsigned int value.

But I honestly don't know if we could apply the same convention for symbolic::Expression as well.

Any idea?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055)*

**Comment by jwnimmer-tri** [comment]
FWIW My vote would be to say `PixelType::kExpr` and `systems::sensors::ImageExpr`.

**Comment by soonho-tri** [comment]
That sounds good to me. I'm still wondering a proper value for `ImageTraits<PixelType::kExpr>::kNumChannels`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8055#-:-L5FKehPE8W-LfSvEYti:b-q3lick)*

**Comment by kunimatsu-tri** [comment]
I'm fine with that.

As for `kNumChannels`, I think 1 is good assuming that we won't hold multiple `simbolic::Expression` in a pixel. Please correct if I'm wrong.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-:-L5FLE71LimWOHN44sq1:bpluxrr)*

**Comment by soonho-tri** [comment]
> we won't hold multiple simbolic::Expression in a pixel.

I can tell this assumption holds. I'll update this PR shortly. Thanks for the inputs! 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8055#-:-L5FLvk61L7oIsi17WkZ:bndqzx5)*

**Comment by SeanCurtis-TRI** [comment]
As long as we stay away from the practice of encoding different pieces of information in different channels, this seems good.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-:-L5FMozSitUnXYpx06CP:b-r9v8w9)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/image.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-L5FHzu1PZpy7BFl5gv1:-L5FWGmFbEQJf0xIU6S9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3dcae8cb79068ceae5bb624049878ade8dd0141f/systems/sensors/image.h#L46)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

In the current convention, the number represents the number of bit for a value in a channel.
For instance,  kRgb8U means a pixel holds four channels where each channel has a 8 bits unsigned int value.

But I honestly don't know if we could apply the same convention for symbolic::Expression as well.

Any idea?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-:-L5FZRCEhpAP3Fpk9FW6:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-:-L5FabVhsSpMTOVWcW6X:b-3ojlqy)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8055#-:-L5Fbfw-g7bao1bosVHX:bnfp4nl)*

**Pull request merged**
