### PR TITLE
[render_vtk] Obey extensionsUsed and extensionsRequired

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
When given a glTF with an unsupported extensionsRequired, throw an error. (Previously, we would print an error to stderr but bash on regardless.)

When given a glTF with an unsupported extensionsUsed (not required), don't report errors about known image formats (e.g., `image/ktx2`), rather only about images we need but cannot actually load. The warning about the unsupported texture extension is sufficient on its own.

Towards #20935.

---

FYI on what the warning looks like as of this PR:

```
[ RUN      ] RenderEngineVtkTest.GltfTextureSupport
[2024-03-04 22:33:12.439] [console] [warning] warning: Warning: In vtkGLTFDocumentLoaderInternals.cxx, line 1350: vtkGLTFDocumentLoader (0x559b25a9ffe0): glTF extension KHR_texture_basisu is used in this model, but not supported by this loader. The extension will be ignored.
[       OK ] RenderEngineVtkTest.GltfTextureSupport (275 ms)
```

---

I created the ktx2 files with the `ktx` tool from https://github.com/KhronosGroup/KTX-Software, e.g., `ktx create --encode=basis-lz --format=R8G8B8_UNORM --assign-oetf=linear /home/jwnimmer/jwnimmer-tri/drake/geometry/render/test/meshes/fully_textured_pyramid_omr.{png,ktx2}`.  Integrating that tool into Drake is future work.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21090)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. One issue with the patch not quite doing what I believe it's intended to accomplish.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-:-NsEGdpF6aSmEWBuujJi:brmfofz)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEFZ63-cjqmI5Jlbb0:-NsEFZ63-cjqmI5Jlbb1:brq7vlb) (no related file):*
BTW Is updating the documentation on using glTF part of your roadmap?

___
___
*[`geometry/render/test/meshes/fully_textured_pyramid.gltf` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEEylH6OEpKAlfqBYc:-NsEEylI4prVwmPIS2oZ:b98olrw) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/geometry/render/test/meshes/fully_textured_pyramid.gltf#L71)):*
> ```JSON
> 		{
> 			"sampler":0,
> 			"source":0,
> ```

BTW Something to consider. What behavior would you want if someone specified a texture with the "used-but-not-required" extension but didn't provide a back up texture (like you've done here)?

Currently, if you remove this line, Drake dies with the message:

```
ERROR: In vtkGLTFImporter.cxx, line 85
(nullptr): Image not found
```

I can imagine we'd *like* something more, but I haven't poked into the code enough to determine if it's practical to provide something more helpful. (See related note below on the vtk patch.)
___
*[`tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch` line 20 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsECckb6aDfHXB5gf7h:-NsECckc2nsDAxFelmcY:b5hn0s2) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch#L20)):*
BTW This comment might benefit from further elaboration. If a reader only looks at the [glTF specification](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_image_mimetype) which clearly claims mimetype only allwos "image/jpeg" or "image/png", they might disagree.

The existence of extensions relaxes that documented requirement. A small tweak, perhaps?

> We must not report any error here; extensions allow other image types. It is perfectly valid to declare other, extension-supported image types, so long as they are never required by the scene. Therefore, the possible error is deferred til later.

I also tweaked the phrase "referenced by the scene" because it's ambiguous (are you referring to the contents of the glTF file, or the parsed result?) The scene can reference them, it just can't require them, as your test shows.
___
*[`tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEDqUV2Eq3qp_tE2au:-NsEDqUV2Eq3qp_tE2av:bjsxhqn) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch#L54)):*
> ```Diff
> +      {
> +        vtkErrorWithObjectMacro(this,
> +          "A required image had an unsupported mimeType.");
> ```

BTW Your test doesn't trip over this error message. It appears we're tripping over a null image earlier in the code (see the note above).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21090)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEFZ63-cjqmI5Jlbb0:-NsF5U0N53noXvtPISnj:bwpxc7c) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is updating the documentation on using glTF part of your roadmap?
</blockquote></details>

Can you be more specific?

I do have a little checklist under https://github.com/RobotLocomotion/drake/issues/20935, in case that answers the question.

___
___
*[`geometry/render/test/meshes/fully_textured_pyramid.gltf` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEEylH6OEpKAlfqBYc:-NsFFZIb8ZpVOTCGXW87:b-xlqmac) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/geometry/render/test/meshes/fully_textured_pyramid.gltf#L71)):*
> Currently, if you remove this line ...

Well, lacking a "source" image entirely for an optional extension is a very broken glTF, so I don't much care what the error looks like if we remove that line.  An artist tool is unlikely to produce such a thing.

I think the more relevant question is what happens when the primary texture image is something other than png or jpeg (e.g. `image/x-exr`).  I've explored that with some extra manual testing, and adjusted the code to match now.
___
*[`tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEDqUV2Eq3qp_tE2au:-NsFFVTp4IP4BSeF2Gjf:b-nhruja) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Your test doesn't trip over this error message. It appears we're tripping over a null image earlier in the code (see the note above).
</blockquote></details>

Removed, and replace with more patching to the `Importer.cxx` now, which is the code that's most relevant.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-:-NsFi6OnBPiU6kzWzwqD:bmxilld)* status: 1 unresolved discussion, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEFZ63-cjqmI5Jlbb0:-NsFg836813EvhQ_MpR0:b-e8ruan) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can you be more specific?

I do have a little checklist under https://github.com/RobotLocomotion/drake/issues/20935, in case that answers the question.
</blockquote></details>

I was thinking in terms of the file format documentation. Particularly as regards to what can/cannot be done w.r.t. extensions and the guidance along the lines of providing ktx *and* parallel png files and the like.

___
___
*[`geometry/render/test/meshes/fully_textured_pyramid.gltf` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEEylH6OEpKAlfqBYc:-NsFgTPTEJg7ZIoyS7WV:b-r1cm2b) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/geometry/render/test/meshes/fully_textured_pyramid.gltf#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Currently, if you remove this line ...

Well, lacking a "source" image entirely for an optional extension is a very broken glTF, so I don't much care what the error looks like if we remove that line.  An artist tool is unlikely to produce such a thing.

I think the more relevant question is what happens when the primary texture image is something other than png or jpeg (e.g. `image/x-exr`).  I've explored that with some extra manual testing, and adjusted the code to match now.
</blockquote></details>

Well, it *is* a valid glTF to do omit it. I don't think you realize how permissive the spec is. `source` is not required.  However, if absent, and no alternative texture source is provided, behavior *is* undefined.

My question is, how did you make *this* glTF? I've never used blender to export a glTF file that would create the extension-source and the backup source. So, I'm not sure how you can be so confident that "an artist tool is unlikely to produce such a thing." If this target format is achieved by after-the-fact manipulation, the odds of making this mistake seems to go up in my estimation. Presumably, the solution is to claim that people should use approved tooling to create this effect and never touch the file directly. And, if they do, they deserve unhelpful error messages.

I'm not in love with it, but, meh.

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-:-NsFiwLm1fJPXnKi7rtt:b-2gnyz2)* status: LGTM missing from assignee xuchenhan-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEFZ63-cjqmI5Jlbb0:-NsFiqL28Eq_FqbqE2Jc:b-i1qikl) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was thinking in terms of the file format documentation. Particularly as regards to what can/cannot be done w.r.t. extensions and the guidance along the lines of providing ktx *and* parallel png files and the like.
</blockquote></details>

Yup.  That's what I intent for the first checkbox in that issue.

___
___
*[`geometry/render/test/meshes/fully_textured_pyramid.gltf` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-NsEEylH6OEpKAlfqBYc:-NsFiTYMBuX0w3udvJ30:bbxdstw) ([raw file](https://github.com/RobotLocomotion/drake/blob/a96087c21254355b0ab873e6ba503379139202da/geometry/render/test/meshes/fully_textured_pyramid.gltf#L71)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Well, it *is* a valid glTF to do omit it. I don't think you realize how permissive the spec is. `source` is not required.  However, if absent, and no alternative texture source is provided, behavior *is* undefined.

My question is, how did you make *this* glTF? I've never used blender to export a glTF file that would create the extension-source and the backup source. So, I'm not sure how you can be so confident that "an artist tool is unlikely to produce such a thing." If this target format is achieved by after-the-fact manipulation, the odds of making this mistake seems to go up in my estimation. Presumably, the solution is to claim that people should use approved tooling to create this effect and never touch the file directly. And, if they do, they deserve unhelpful error messages.

I'm not in love with it, but, meh.
</blockquote></details>

The next PR (the one I was rubber ducking in slack) will produce a tool to automatically rewrite a glTF file akin what I did in this PR.  Here, I did it manually but my objective is that all of the future conversions will be fully automatic.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21090#-:-NsK3RQJ-xF_VVm66MOF:b-cxwtpw)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Pull request merged**
