### PR TITLE
[multibody] Clean up some Body comments

### LINKED ISSUE #18570: Use of the term "floating" in inconsistent in the `Body` class
#18390 changed the definition of a "floating body" to "a body that's mobilized by a 6-dof mobilzer AND parent body of the mobilizer is world". However, some documentation in the `Body` class uses the term "floating" inconsistently with this definition. Some uses are just wrong.

For example, the documentation of `Body::has_quaternion_dofs()` claims 
> If `true`, this body is a floating body modeled with a quaternion floating mobilizer. By implication, is_floating() is also `true`.

which is incorrect, when the body's parent is not world.

Other functions whose documentation needs a fix include

- Body::floating_positions_start
- Body::floating_velocities_start
- Body::floating_position_suffix
- Body::floating_velocity_suffix
- Body::Lock
- Body::Unlock

### PR DESCRIPTION
**Pull request by sherm1**
Cleans up outdated/incorrect/messy comments in multibody::Body.

Resolves #18570

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@xuchenhan-tri for both reviews, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578#-:-NLb7g464VelI2tzc8QG:bn51x43)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2 with one question.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578#-:-NLclBPt9upQ1haolXlD:b-ycue45)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[`multibody/tree/body.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18578#-NLckfe67a7hKRmwFOoK:-NLckfe67a7hKRmwFOoL:bpy9tg0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ada98a61d69883956bb5d3daa5ebce1e4f93129f/multibody/tree/body.h#L285)):*
> ```objc
>   }
> 
>   /// (Advanced) For floating bodies (see is_floating()) this method returns the
> ```

minor, if I can this function (or the velocity or suffix variants) on a body that is not floating, what would happen? Do I just get garbage? If that's the case, it would be better to forbid doing that altogether.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/tree/body.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18578#-NLckfe67a7hKRmwFOoK:-NLx7zX46GH6fzE7zsLI:bd8qyx8) ([raw file](https://github.com/RobotLocomotion/drake/blob/ada98a61d69883956bb5d3daa5ebce1e4f93129f/multibody/tree/body.h#L285)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, if I can this function (or the velocity or suffix variants) on a body that is not floating, what would happen? Do I just get garbage? If that's the case, it would be better to forbid doing that altogether.
</blockquote></details>

Done. Good catch! The suffix variants were already protected by a DRAKE_DEMAND (incorrectly documented as a throw). I added missing DRAKE_DEMANDs to the "start" functions and marked all of these as having an is_floating precondition. PTAL

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @sherm1)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @sherm1)

___
*[`multibody/tree/body.h` line 285 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18578#-NLckfe67a7hKRmwFOoK:-NM-eYib0DNGkK3i_FIB:b-gmzmso) ([raw file](https://github.com/RobotLocomotion/drake/blob/ada98a61d69883956bb5d3daa5ebce1e4f93129f/multibody/tree/body.h#L285)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. Good catch! The suffix variants were already protected by a DRAKE_DEMAND (incorrectly documented as a throw). I added missing DRAKE_DEMANDs to the "start" functions and marked all of these as having an is_floating precondition. PTAL
</blockquote></details>

It looks like this assertion caught something!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18578)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @sherm1)

**Pull request merged**
