### PR TITLE
[drake_gym] Add info_handler callback

### LINKED ISSUE #21899: Add a "timestamp" item to the `info` return value from `DrakeGymEnv.step(...)`
It is often helpful to have the simulation timestamp after a call to `env.step()` to, e.g. render a video of image observations with simulation time as the video's timestamp.

https://github.com/RobotLocomotion/drake/blob/59a15c38f3489d3b97406baa9c3b2e3eaa8cea4a/bindings/pydrake/gym/_drake_gym_env.py#L209

### PR DESCRIPTION
**Pull request by samzapo**
Closes #21899.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I am not very familiar with Gym, so let me ask a few questions and then also invite others to comment.

(1) Is the `info["timestep"]` a convention in the Gym community?  If yes, they we should add a comment in the code with cross-reference(s) to existing practice, in which case my other questions are moot.

(2) If not, then for users who want this kind of metadata, why would the following not be a better solution (in their own code, with no changes to Drake)?

```py
observation, reward, terminated, truncated, info = env.step(action)
info["timestamp"] = env.simulator.get_context().get_time()
```

With this technique, users can add any metadata they like.  Perhaps the problem is that the user is not directly calling `env.step`, because it's called from a framework?  In that case ...

(3) If we _do_ need to populate `info` during `DrakeGymEnv.step` and neither option 2 nor subclassing is a viable solution, possibly we should following the existing pattern of `self.reward` and add a `self.into` constructor argument, so that the user can pass into the constructor any kind of info-callback they like.  Certainly the timestamp won't be the only kind of info ever requested / useful, so hard-coding it be exactly one thing seems unwise?  Flexibility seems like the better approach, at first glance.

+@JoseBarreiros-TRI for discussion and feature review, please.

**Comment by samzapo** [comment]
@jwnimmer-tri This is a great suggestion and works, but I'd prefer to support multiple gym environments, some not using `Drake` (e.g.: [huggingface/gym-aloha](https://github.com/huggingface/gym-aloha)).

Since it is not a convention to provide time data in `info`  I'd lean toward requesting an optional "info handler" `DrakeGymEnv` construction parameter, mentioned here:
https://github.com/RobotLocomotion/drake/issues/21899#issuecomment-2348764263
 rather than wrapping `DrakeGymEnv` and overriding `step()`, as I've done here: [samzapo/gym-drake-lca](https://github.com/samzapo/gym-drake-lca/blob/06a4d34e9bb48e41dbbdba92cdb70f5e5213c279/gym_drake_lca/envs/lift_cube_env.py#L357-L361) as stop-gap.
 
 If this PR is dismissed, as the desired behavior is possible with the current setup (thanks @JoseBarreiros-TRI ).  That's fine too.

**Comment by jwnimmer-tri** [comment]
> ... I'd lean toward requesting an optional "info handler" ...

Ah, thanks for the pointer; I'd missed that detail.

It sounds like everyone is happy with the "info handler" proposal, so that's probably the way to proceed.

**Review by jwnimmer-tri — COMMENTED** [review]
@samzapo Jenkins is showing linter errors.  You can run the linters locally via `bazel test --config=lint //bindings/pydrake/...`.

@JoseBarreiros-TRI do you have time/interest in serving as the reviewer here?  If not, I can recruit someone else.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-:-O70c4SPEDhlbNRIAbpe:b20y2cu)* status: 1 unresolved discussion, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O70cUt1C1iGQY7TeWWI:-O70cUt1C1iGQY7TeWWJ:b-zd9yzv) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db20237c3b8ae30f1cb5058c94e90ef7aca418c/bindings/pydrake/gym/_drake_gym_env.py#L256)):*
> ```Python
>             terminated = False
>             reward = 0
>             info = dict() if self.info_handler is None else self.info_handler(self.simulator)
> ```

nit Instead of copy-pasting the if-None-else logic multiple times, we can probably do something less brittle, e.g.

(1) Don't allow the info handler be `None`; instead, change the default value in the constructor args to be`dict` (i.e., the callable constructor that does what we want as a default).

(2) Add a private helper method `def _info(self):` on `DrakeGymEnv` with the None-handling logic, and change this to `info = self._info()` or similar.

**Review by JoseBarreiros-TRI — COMMENTED** [review]
happy to review this

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-:-O74NTWeDHxktubfgVpM:b-tgyyi)* status: 1 unresolved discussion, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

**Review by samzapo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O70cUt1C1iGQY7TeWWI:-O74ObJFEYjEQeZEWPTl:bdw6vw4) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db20237c3b8ae30f1cb5058c94e90ef7aca418c/bindings/pydrake/gym/_drake_gym_env.py#L256)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Instead of copy-pasting the if-None-else logic multiple times, we can probably do something less brittle, e.g.

(1) Don't allow the info handler be `None`; instead, change the default value in the constructor args to be`dict` (i.e., the callable constructor that does what we want as a default).

(2) Add a private helper method `def _info(self):` on `DrakeGymEnv` with the None-handling logic, and change this to `info = self._info()` or similar.
</blockquote></details>

Done. I've chosen to do (1), see assignment to `self.info_handler` logic

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: 1 unresolved discussion, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O70cUt1C1iGQY7TeWWI:-O74T4F60UUJTSBGvUow:b-7w6gia) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db20237c3b8ae30f1cb5058c94e90ef7aca418c/bindings/pydrake/gym/_drake_gym_env.py#L256)):*
<details><summary><i>Previously, samzapo (Samuel Zapolsky) wrote…</i></summary><blockquote>

Done. I've chosen to do (1), see assignment to `self.info_handler` logic
</blockquote></details>

BTW I expect that `foo = lambda _: dict()` can be shortened to just `foo = dict`.  The constructor is already a callable.

**Review by samzapo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O70cUt1C1iGQY7TeWWI:-O74aL_O6MqdnVpwjIfx:b4ul3yv) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db20237c3b8ae30f1cb5058c94e90ef7aca418c/bindings/pydrake/gym/_drake_gym_env.py#L256)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I expect that `foo = lambda _: dict()` can be shortened to just `foo = dict`.  The constructor is already a callable.
</blockquote></details>

Would this work if `self.info_handler(simulator)` is called (i.e., with a parameter)?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 256 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O70cUt1C1iGQY7TeWWI:-O74dpGV-pf27J4stnsK:b-vjalpa) ([raw file](https://github.com/RobotLocomotion/drake/blob/2db20237c3b8ae30f1cb5058c94e90ef7aca418c/bindings/pydrake/gym/_drake_gym_env.py#L256)):*
<details><summary><i>Previously, samzapo (Samuel Zapolsky) wrote…</i></summary><blockquote>

Would this work if `self.info_handler(simulator)` is called (i.e., with a parameter)?
</blockquote></details>

Oops, nevermind.   I forgot the callback took argument.

**Review by JoseBarreiros-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: 2 unresolved discussions, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/examples/gym/envs/cart_pole.py` line 418 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O7Va2MeB9SieKgcvSk4:-O7Va2MeB9SieKgcvSk5:b1uw1v1) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fcaaf30306682ba8fa92577ada60267414c153/bindings/pydrake/examples/gym/envs/cart_pole.py#L418)):*
> ```Python
>         observation_port_id="observations",
>         reset_handler=reset_handler,
>         info_handler=lambda _: dict(),
> ```

why not set this to None or better provide a nice example of an info handler
___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 257 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O7Va7FwBUWpliKe5Wk_:-O7Va7FwBUWpliKe5Wka:b-b2jmtd) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fcaaf30306682ba8fa92577ada60267414c153/bindings/pydrake/gym/_drake_gym_env.py#L257)):*
> ```Python
>             terminated = False
>             reward = 0
>             info = self.info_handler(self.simulator)
> ```

I'm not sure about the expected behavior here. I think that if the run gets to this point it means that the simulator faulted which would cause an unexpected behavior when called by the info_handler(). Consider setting the info to an empty dict or info["sim_runtime_error"]=True.

**Review by JoseBarreiros-TRI — COMMENTED** [review]
@samzapo I'm happy to help land this PR, let me know if you have any questions. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-:-O84_dr_Akn1s-ahShvy:bd19af5)* status: 2 unresolved discussions, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

**Review by samzapo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: 2 unresolved discussions, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/examples/gym/envs/cart_pole.py` line 418 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O7Va2MeB9SieKgcvSk4:-O87-LIc1E7V0reBFASO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fcaaf30306682ba8fa92577ada60267414c153/bindings/pydrake/examples/gym/envs/cart_pole.py#L418)):*
<details><summary><i>Previously, JoseBarreiros-TRI wrote…</i></summary><blockquote>

why not set this to None or better provide a nice example of an info handler
</blockquote></details>

Done.

**Review by JoseBarreiros-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: 1 unresolved discussion, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 257 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O7Va7FwBUWpliKe5Wk_:-O8dCI3L0ft3QNZ5mHaF:bv7uber) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fcaaf30306682ba8fa92577ada60267414c153/bindings/pydrake/gym/_drake_gym_env.py#L257)):*
<details><summary><i>Previously, samzapo (Samuel Zapolsky) wrote…</i></summary><blockquote>

I don't want to add anything to info that isn't standard.  
This is what motivated adding an info handler over explicitly adding `info["timestamp"]`

I think it's likely that `simulator` will still behave normally after most runtime errors, but this is a good point
I'd go for just returning an empty dict in this case, and adding documentation that says, e.g.,
 "if the simulator emits a runtime error while advancing, the provided info handler will not be called and will return an empty dict instead".

Would that work?
</blockquote></details>

yes, that is reasonable.

**Review by samzapo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900)* status: 1 unresolved discussion, LGTM missing from assignee JoseBarreiros-TRI, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[`bindings/pydrake/gym/_drake_gym_env.py` line 257 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-O7Va7FwBUWpliKe5Wk_:-O8hcAXW0dKwx8EHZALP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fcaaf30306682ba8fa92577ada60267414c153/bindings/pydrake/gym/_drake_gym_env.py#L257)):*
<details><summary><i>Previously, JoseBarreiros-TRI wrote…</i></summary><blockquote>

yes, that is reasonable.
</blockquote></details>

Done.

**Review by JoseBarreiros-TRI — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-:-O8iAB9rEYZ9dyct5FUO:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:
+(status: squashing now) 

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21900#-:-OB1ik5A7Y4mRpUtB7qe:b-9kn1by)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees JoseBarreiros-TRI,sammy-tri(platform)

**Pull request merged**
