### PR TITLE
[workspace] Upgrade gz_utils_internal, gz_math_internal, sdformat_internal to latest

### PR DESCRIPTION
**Pull request by nicolecheetham**
Towards: #22240

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-:-ODDmjBM6tSO8xqnmmw7:b-chsgxs)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
pending CI:
+(status: single reviewer ok) +@sherm1 for both reviews, Wednesday schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-:-ODDn7X_ASE7aQlKYY7q:b-z8bfkg)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
-@sherm1 +@SeanCurtis-TRI for both reviews.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-:-ODMrZLB6TC4UdklVV1q:blya6l)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-:-ODNle6GDACkAJV0U8A6:bmxilld)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-ODNlbpFCpMBglxEx11t:-ODNlbpFCpMBglxEx11u:b-guc7of):*
nit: The summary line mentions `gz_math_internal` but it isn't explicitly touched by any change in this PR. Is that implicit from one of the other libraries? And, if so, why does it get mentioned explicitly?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-ODNlbpFCpMBglxEx11t:-ODNlqMRE8xmNjbc1Rjz:b-rxszb2):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The summary line mentions `gz_math_internal` but it isn't explicitly touched by any change in this PR. Is that implicit from one of the other libraries? And, if so, why does it get mentioned explicitly?
</blockquote></details>

There *is* a new version: [8.1.0](https://github.com/gazebosim/gz-math/tags). So, it seems it might be an oversight?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22259#-:-ODluNoc2ihkJGXqNXSG:b-jzc2h8)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
