### PR TITLE
[solvers] Add SpecificOptions sugar for solvers to map their options

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21345 (which ports all solvers to use this new sugar) and thus also #20967.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.  (If you have time?  No particular ETA, maybe within a week is okay.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-:-O9jMHW9BCh9FPHV7rbW:bnfp4nl)* status: 5 unresolved discussions, needs at least two assigned reviewers

___
*[`solvers/specific_options.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jH-wy1Muq_nr1HPs2:-O9jH-wy1Muq_nr1HPs3:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.h#L25)):*
> ```objc
> generic SolverOptions struct into the specific solver's options API.
> 
> This class is intended a short-lived helper (i.e., a local variable on the call
> ```

typo?



_Suggestion:_
```objc
This class is intended as a short-lived helper (i.e., a local variable on the call
```
___
*[`solvers/specific_options.h` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jHIEoCO_2vv_nKlOd:-O9jHIEoCO_2vv_nKlOe:bcaprwu) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.h#L53)):*
> ```objc
>   participate in the Method 1 or 2 copying / callbacks.
> 
> For examples of use, refer to all of the existing Drake solver wrappers. */
> ```

nit , a less herculean task.



_Suggestion:_
```objc
any
```
___
*[`solvers/specific_options.h` line 60 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jHuWT3KXfOoYMCJkC:-O9jHuWT3KXfOoYMCJkD:b-t2dw) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.h#L60)):*
> ```objc
>   /* Creates a converter that reads the subset of `all_options` destined for the
>   given `id`. Both arguments are aliased, so must outlive this object. */
>   SpecificOptions(const SolverId* id, const SolverOptions* all_options);
> ```

BTW:  I don't love a ctor aliasing default-copyable objects, and `...* id` is very odd to read, but I assume that this is justified by callers expecting inner-loop performance.



_Code quote:_
```objc
  given `id`. Both arguments are aliased, so must outlive this object. */
  SpecificOptions(const SolverId* id, const SolverOptions* all_options);
```
___
*[`solvers/specific_options.h` line 153 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jNMtD78xreI3XGAnx:-O9jNMtD78xreI3XGAny:b-80ayoo) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.h#L153)):*
> ```objc
>   //@}
> 
>   // The solver we're operating on behalf of (as passed to our constructor).
> ```

nit:  Mixing `/*` and `//` comment styles make styleguide sad.
___
*[`solvers/specific_options.cc` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jK0cM9kFk1Nov1Egq:-O9jK0cM9kFk1Nov1Egr:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.cc#L149)):*
> ```cpp
>   // already been set.
>   for (const auto& [respelled_key, boxed_value] : respelled_) {
>     // Pedantially, lambdas cannot capture a structured binding so we need to
> ```

typo



_Suggestion:_
```cpp
Pedantically
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-:-O9jgmo6AWsuEfrw3EO2:bbnvyd5)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`solvers/specific_options.h` line 60 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jHuWT3KXfOoYMCJkC:-O9jfSdj9pEQs7y5N3YY:btqqu5l) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.h#L60)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  I don't love a ctor aliasing default-copyable objects, and `...* id` is very odd to read, but I assume that this is justified by callers expecting inner-loop performance.
</blockquote></details>

Correct.
___
*[`solvers/specific_options.h` line 153 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jNMtD78xreI3XGAnx:-O9jg6Vx4FgFN6EESVQm:b7gj0ot) ([raw file](https://github.com/RobotLocomotion/drake/blob/10ffba67348419d05bfdf65567dc30183ce91219/solvers/specific_options.h#L153)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  Mixing `/*` and `//` comment styles make styleguide sad.
</blockquote></details>

The rule is to be consistent, and this is consistent.  Functions specifications are `/*` and implementation notes are `//`.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some cosmetic stuff.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-:-O9kP35Q8fr64aoAVY5e:b-ri068m)* status: 7 unresolved discussions

___
*[`solvers/specific_options.h` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jwz1qEnPu6sEEJ0YU:-O9jwz1qEnPu6sEEJ0YV:b-4ondcq) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.h#L29)):*
> ```objc
> convenient tools to map those options into whatever back-end is necessary. Two
> different mechanisms are offered, depending on whether the solver's option names
> are static or dynamic: CopyToCallbacks or CopyToSerializableStruct.
> ```

The ordering of the adjectives doesn't match the ordering of the methods.



_Suggestion:_
```objc
dyanmic or static
```
___
*[`solvers/specific_options.h` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jy3So1wWoB1sie3js:-O9jy3So1wWoB1sie3jt:b-ag0y5o) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.h#L79)):*
> ```objc
> 
>   /* Returns and effectively removes the value of the option named `key`. (To be
>   specific -- `all_options` remain unchanged; instead, the `key` is memorized
> ```

btw This always a weird conflict between code and language. `all_options` is a pointer to a single thing, so should be singular. However, the *idea* of the options it holds are plural. British English would probably simplify this.

Either we can refer to `all_options` the C++ object as unchanged, or we can refer to "all options provided at construction remain unchanged", but the mixture is what causes weirdness.

That said, it's basically clear what's being communicated.



_Suggestion:_
```objc
remains 
```
___
*[`solvers/specific_options.h` line 84 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jywpb25ticxsoe_qf:-O9jywpb25ticxsoe_qg:bi01z91) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.h#L84)):*
> ```objc
>   set, this checks `all_options` for our `id` as well as any options added
>   during a Respell().
>   @tparam T must be one of: double, int, std::string. */
> ```

nit: No note on the possible disagreement between `T` and the actual type of the option.
___
*[`solvers/specific_options.h` line 101 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jzKRzERuvv9_9EQNZ:-O9jzKRzERuvv9_9EQN_:bvj6aym) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.h#L101)):*
> ```objc
>   /* Helper for "Method 2 - static", per our class overview. Converts options
>   when the solver uses an options struct with names known at compile time. The
>   `Output` struct must obey Drake's Serialize() protocol, for us to interrogate
> ```

nit: The struct formerly known as `Output`.



_Suggestion:_
```objc
`Result`
```
___
*[`solvers/specific_options.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9kKAjh2wdn-IWJhnJe:-O9kKAjh2wdn-IWJhnJf:b-sak7fx) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.cc#L279)):*
> ```cpp
>               id_->name(), name, value));
>         }
>         if (static_cast<int64_t>(value) >
> ```

BTW What am I missing here? How can a value encoded as an `int` *ever* be bigger than the maximum `uint32_t` value?  Is this simply protecting us from the C++ specification's only-lower-bound- language for defining `sizeof(int)`?
___
*[`solvers/test/specific_options_test.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9kMcnS1Jvci5gmPdJ9:-O9kMcnS1Jvci5gmPdJA:bxufnel) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/test/specific_options_test.cc#L79)):*
> ```cpp
> 
> GTEST_TEST(SpecificOptionsTest, CopyToCallbacksNoop) {
>   // This is a code-coverage test to cover the early return no-op.
> ```

btw: This doesn't really test the early return. The test result is the same whether there's an early return or not (each for loop that would exercise the callbacks get exercised zero times). All one can *really* say about this test is that no options implies no problems.
___
*[`solvers/test/specific_options_test.cc` line 89 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9kN-AR3G048e_0I0eZ:-O9kN-AR3G048e_0I0e_:byldrzz) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/test/specific_options_test.cc#L89)):*
> ```cpp
> }
> 
> GTEST_TEST(SpecificOptionsTest, CopyToCallbacksEarlyReturn) {
> ```

nit: This test is an exact duplicate of the previous (but with a rename).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043)* status: 8 unresolved discussions

___
*[`solvers/specific_options.h` line 104 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jzY4F9Z6LUAk4aF4D:-O9jzY4F9Z6LUAk4aF4E:bcmqqke) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.h#L104)):*
> ```objc
>   the option names.
>   @param [in,out] result The solver's specific options struct; any options not
>   mentioned in `solver_options` will remain unchanged. */
> ```

nit: unclear reference...should this be `all_options`?



_Code quote:_
```objc
solver_options
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043)* status: 1 unresolved discussion

___
*[`solvers/specific_options.h` line 29 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9jwz1qEnPu6sEEJ0YU:-O9kRoBJ825XaLaLBEvz:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/specific_options.h#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The ordering of the adjectives doesn't match the ordering of the methods.
</blockquote></details>

Done.
___
*[`solvers/test/specific_options_test.cc` line 79 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22043#-O9kMcnS1Jvci5gmPdJ9:-O9kcaSC8C4_m0r4u05Z:bgd2ae5) ([raw file](https://github.com/RobotLocomotion/drake/blob/aabd27bd4dd67745b322c76bee81b7446fd6ca0d/solvers/test/specific_options_test.cc#L79)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: This doesn't really test the early return. The test result is the same whether there's an early return or not (each for loop that would exercise the callbacks get exercised zero times). All one can *really* say about this test is that no options implies no problems.
</blockquote></details>

Yeah.  Maybe the short-circuit isn't that valuable anyway, so I just punted it.  We can add it back later if profiling tells us to.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22043)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
