### PR TITLE
Add script for building drake-visualizer binaries for Ubuntu

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #10729. This just a [slightly cleaned up] code dump at present.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14573)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@jwnimmer-tri if there are any changes that you know for certain you want now, I could make them here as they would probably (and maybe counterintuitively) reduce the amount of code here that I need to clean up.

**Comment by jwnimmer-tri** [comment]
I took a quick skim, and I don't see anything here that would need changing.  I think I'd rather merge what's already working (+ adding TODOs for any stuff we hate), instead of polishing it more.  If we think the cleanups are important, we can do them promptly right after, but committing what actually got run is an important first step.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review. I think this is as about as good as it is going to get as a starting point, unfortunately.

**Comment by jamiesnape** [comment]
If you are testing locally it is better to have BuildKit off (if it is even available) so that the still-quite-verbose console output is easier to read, though it will not change the end result.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM on the code and comments.  Will test locally later today (or soon).

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14573#-:-MTqVIJACm2VzH2tagwQ:b-6mrv61)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Sorry, I got backlogged on this.  I plan to look Thursday evening or Friday morning.

**Comment by jamiesnape** [comment]
Not urgent. I would not be able to respond until then anyway.

**Comment by jwnimmer-tri** [comment]
:lgtm: feature review.

I've confirmed that I can run this and create binaries locally without any errors.  (I didn't bother running them.)

+@ggould-tri for platform review per schedule (yesterday), please.  I almost rubber-stamped this in myself but I figured getting a second opinion is useful.

The intent here is to capture what we already have and then subsequently evolve.  I'm curious if you think this meets the minimum bar to hit master, or if there's some area we need to improve before that point.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: I think this PR claims ground, and its ugliness is mitigated by its obscure location where it is unlikely to cause much confusion.  I've flagged one nit, but otherwise I'd say it might as well land.

> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14573#-:-MUV8M86DjQIZx6YtOvp:b-h2hye3)* status: 1 unresolved discussion (waiting on @jamiesnape)

___
*[tools/workspace/drake_visualizer/Dockerfile, line 218 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14573#-MUV8FTv2bwRAa_QEExW:-MUV8FTv2bwRAa_QEExX:bbjk5jc) ([raw file](https://github.com/robotlocomotion/drake/blob/be1bd02f1ccd780aba87b1bcbff362ea53d4a823/tools/workspace/drake_visualizer/Dockerfile#L218)):*
> ```Dockerfile
>     /opt/director/lib/python3.*/site-packages/director/thirdparty/*.so
> RUN cd /opt/director \
>   && tar --create --gzip --file dv-0.1.0-406-g4c3e570a-python-$(python3 --version 2>&1 | sed --quiet --expression 's/^.*\n*Python \([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\).*/\1.\2.\3/p')-qt-$(qmake --version | sed --quiet --expression 's/^.*\n*Qt version \([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\).*/\1.\2.\3/p')-vtk-8.2.0-$(lsb_release --codename --short)-$(uname --processor).tar.gz -- *
> ```

minor: This line really, really, really needs a comment.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14573)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
