### PR TITLE
[geometry/optimization] Make Point mutable

### PR DESCRIPTION
**Pull request by RussTedrake**
This has proven useful in a number of unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@avalenzu for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368#-:-MeLkyzGCnQ3qdEgj9I3:b-fcohnv)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
One naming request.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368#-:-MeRKva353ZqhIjUs5yd:bpkk0t4)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/optimization/point.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15368#-MeRKaBS0adPbXx_UZjT:-MeRKaBS0adPbXx_UZjU:bsa2a90) ([raw file](https://github.com/robotlocomotion/drake/blob/292a5639178362565777969e3d0f3eb2b30c90f2/geometry/optimization/point.h#L47)):*
> ```objc
>   /** Changes the element @p x describing the set.
>   @pre @p x must be of size ambient_dimension(). */
>   void set(const Eigen::Ref<const Eigen::VectorXd>& x);
> ```

This reads nicely with named arguments in Python, but I think it's a bit to vague in C++, especially for a class that represents a set. Could this be `set_x`?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

___
*[geometry/optimization/point.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15368#-MeRKaBS0adPbXx_UZjT:-Mee4ZZg6sMwaz7XhCXR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/292a5639178362565777969e3d0f3eb2b30c90f2/geometry/optimization/point.h#L47)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

This reads nicely with named arguments in Python, but I think it's a bit to vague in C++, especially for a class that represents a set. Could this be `set_x`?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
+@ericcousineau-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368#-:-Mee4aCNA7P642QPxrZx:bvtjo57)* status: 1 unresolved discussion, LGTM missing from assignees avalenzu,EricCousineau-TRI(platform) (waiting on @avalenzu and @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368#-:-Mee4tLgAUc1VM-oM0Xu:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu (waiting on @avalenzu)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Dismissed @avalenzu from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15368)* status: LGTM missing from assignee avalenzu (waiting on @RussTedrake)

**Pull request merged**
