### PR TITLE
add binding for SubstituteAndExpand

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-:-NPJU8De66lP9_QN4NhU:bggbbet)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/symbolic_py.cc` line 817 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAf1W8RQrq6KTMUoj:-NPKAf1W8RQrq6KTMUok:b-i7xk7t) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L817)):*
> ```cpp
>       .def(
>           "SubstituteAndExpand",
>           [](const Polynomial& self,
> ```

Not sure why returning the `cached_subs` as well, why not to just modify `substitutions_optional` in place, as we did in the C++ case? I think now the python code behaves differently with the C++ code, when `substitutions_optional=None`. In the C++ case, if `substitutions_optional=std::nullopt` or `nullptr`, then after calling `SubstituteAndExpand`, this `substitutions_optional` is still empty. In the python code, now we will return an extra `cached_subs`.
___
*[`bindings/pydrake/symbolic_py.cc` line 828 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAQeOERABfD-v0pBg:-NPKAQeOERABfD-v0pBh:beoljzl) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L828)):*
> ```cpp
>               cached_subs = std::move(substitutions_optional.value());
>             }
>             const symbolic::Polynomial& poly_ret = self.SubstituteAndExpand(
> ```

Why return const reference here? I think you can return a const value, the reference is not useful?

**Comment by jwnimmer-tri** [comment]
*[`bindings/pydrake/symbolic_py.cc` line 817 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAf1W8RQrq6KTMUoj:-NPLMmw5-2NFUsA-nXNO:b-xsxaq1) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L817)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Not sure why returning the `cached_subs` as well, why not to just modify `substitutions_optional` in place, as we did in the C++ case? I think now the python code behaves differently with the C++ code, when `substitutions_optional=None`. In the C++ case, if `substitutions_optional=std::nullopt` or `nullptr`, then after calling `SubstituteAndExpand`, this `substitutions_optional` is still empty. In the python code, now we will return an extra `cached_subs`.
</blockquote></details>

The problem here is a leaky abstraction.  We've exposed to the use the raw details about caching -- i.e., the exact `std::map` type that this function uses from one call to the next.

If the cache storage was declared like this instead:

```c++
class SubstituteAndExpandCacheData {
 private:
  friend class Polynomial;
  std::map<...> data_;
}
```

and the expand function was like this:

```c++
  /// @param[in,out] cache ... (docs) ...
  [[nodiscard]] Polynomial SubstituteAndExpand(
      const std::unordered_map<Variable, Polynomial>&
          indeterminate_substitution,
       SubstituteAndExpandCacheData* = nullptr) const;
````

then we could bind naturally into pydrake, and moreover it would be _way faster_ because pybind11 wouldn't need to transmogrify (copy) the cache every time it goes back and forth between languages.

**Review by AlexandreAmice — COMMENTED** [review]
Updated the implementation of `SubstituteAndExpand` to reflect @jwnimmer-tri suggestion.

+(release notes: breaking change) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-:-NPNeEeyB3MpEWmOVt1V:b-gwlc19)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[`bindings/pydrake/symbolic_py.cc` line 817 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAf1W8RQrq6KTMUoj:-NPNeU_y-YtPslNfEhAl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L817)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The problem here is a leaky abstraction.  We've exposed to the use the raw details about caching -- i.e., the exact `std::map` type that this function uses from one call to the next.

If the cache storage was declared like this instead:

```c++
class SubstituteAndExpandCacheData {
 private:
  friend class Polynomial;
  std::map<...> data_;
}
```

and the expand function was like this:

```c++
  /// @param[in,out] cache ... (docs) ...
  [[nodiscard]] Polynomial SubstituteAndExpand(
      const std::unordered_map<Variable, Polynomial>&
          indeterminate_substitution,
       SubstituteAndExpandCacheData* = nullptr) const;
````

then we could bind naturally into pydrake, and moreover it would be _way faster_ because pybind11 wouldn't need to transmogrify (copy) the cache every time it goes back and forth between languages.
</blockquote></details>

Done.
___
*[`bindings/pydrake/symbolic_py.cc` line 828 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAQeOERABfD-v0pBg:-NPNevIJ7iWX6FWw2DxX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L828)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why return const reference here? I think you can return a const value, the reference is not useful? 
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
We actually don't need -(release notes: breaking change).  There has not been any release subsequent to #18752.  I think +(release notes: none) should be OK.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice and @jwnimmer-tri)

___
*[`common/symbolic/polynomial.h` line 314 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPOE6ev-KJfbu06h-nV:-NPOE6ev-KJfbu06h-nW:b56h9l2) ([raw file](https://github.com/RobotLocomotion/drake/blob/c6311cdb2ba4e4bc657eb5e9f5663c1a709006d5/common/symbolic/polynomial.h#L314)):*
> ```objc
>       const std::unordered_map<Variable, Polynomial>&
>           indeterminate_substitution,
>       std::optional<SubstituteAndExpandCacheData*> substitutions_cached_data =
> ```

BTW, why we do `std::optional<SubstituteAndExpandCacheDat*>`? If we want to indicate no cached data, I think we can do `SubstituteAndExpandCacheDat* substitutions_cached_data=nullptr`? The `optional` part seems unnecessary to me.
___
*[`bindings/pydrake/symbolic_py.cc` line 817 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAf1W8RQrq6KTMUoj:-NPOEroz28Fa2Aecoq0S:bknuvf) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L817)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think the Jeremy's suggestion also include using `SubstituteAndExpandCacheData* = nullptr`, instead of `std::optional<SubstituteAndExpandCacheData*> = std::nullopt`?

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`common/symbolic/polynomial.cc` line 831 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPOVNHk8CTQ-lWyTH-U:-NPOVNHl2_l_JPL0Gtz1:blc1m1t) ([raw file](https://github.com/RobotLocomotion/drake/blob/46b099799ce0b8c44819de1d3aa69d9cc06849c1/common/symbolic/polynomial.cc#L831)):*
> ```cpp
>   if (substitutions_cached_data == nullptr) {
>     SubstituteAndExpandCacheData substitutions_default_obj;
>     substitutions_cached_data = &substitutions_default_obj;
> ```

I don't think it is right here? `substitutions_default_obj` is created within this `if` statement. When we exit this `if` statement in the `}` one line below, this `substitutions_default_obj` is destroyed, and `substitutions_cached_data` becomes dangling pointer. I would expect there is a test to catch the bug when `substitutions_cached_data = nullptr`.

I would recommend doing this
```cc
SubstituteAndExpandCacheData substitutions_default_obj;
SubstituteAndExpandCacheData* cached_data_ptr = substitutions_cached_data == nullptr ? &substitutions_default_obj : substitutions_cached_data;
```
and then use this `cached_data_ptr` object in the remaining lines of this function.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887)* status: 1 unresolved discussion, LGTM missing from assignees hongkai-dai,ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @hongkai-dai)

___
*[`common/symbolic/polynomial.h` line 314 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPOE6ev-KJfbu06h-nV:-NPOSHu30Ga2dZlrIj67:bfwygde) ([raw file](https://github.com/RobotLocomotion/drake/blob/c6311cdb2ba4e4bc657eb5e9f5663c1a709006d5/common/symbolic/polynomial.h#L314)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, why we do `std::optional<SubstituteAndExpandCacheDat*>`? If we want to indicate no cached data, I think we can do `SubstituteAndExpandCacheDat* substitutions_cached_data=nullptr`? The `optional` part seems unnecessary to me.
</blockquote></details>

This was changed to an optional by request of +@ggould-tri in the review of #18752. Personally I agree that using `nullptr` and eliminating the optional is preferable.   
___
*[`common/symbolic/polynomial.cc` line 831 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPOVNHk8CTQ-lWyTH-U:-NPOa2GE-u83ARGfOcpK:bbvtl4i) ([raw file](https://github.com/RobotLocomotion/drake/blob/46b099799ce0b8c44819de1d3aa69d9cc06849c1/common/symbolic/polynomial.cc#L831)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think it is right here? `substitutions_default_obj` is created within this `if` statement. When we exit this `if` statement in the `}` one line below, this `substitutions_default_obj` is destroyed, and `substitutions_cached_data` becomes dangling pointer. I would expect there is a test to catch the bug when `substitutions_cached_data = nullptr`.

I would recommend doing this
```cc
SubstituteAndExpandCacheData substitutions_default_obj;
SubstituteAndExpandCacheData* cached_data_ptr = substitutions_cached_data == nullptr ? &substitutions_default_obj : substitutions_cached_data;
```
and then use this `cached_data_ptr` object in the remaining lines of this function.
</blockquote></details>

Done. There is indeed a test to catch that.
___
*[`bindings/pydrake/symbolic_py.cc` line 817 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPKAf1W8RQrq6KTMUoj:-NPOSpFH9XQE_3adWJX1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/967df80d4b9965fbb2715c68b3751203642bee1f/bindings/pydrake/symbolic_py.cc#L817)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the Jeremy's suggestion also include using `SubstituteAndExpandCacheData* = nullptr`, instead of `std::optional<SubstituteAndExpandCacheData*> = std::nullopt`?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@rpoyner-tri for platform review please.

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-:-NPOaRgS-jlGSONYnJqH:bnie4ov)* status: LGTM missing from assignees ggould-tri(platform),rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
*[`common/symbolic/polynomial.h` line 314 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-NPOE6ev-KJfbu06h-nV:-NPOajppEY2hO3zakS-_:bol7w4h) ([raw file](https://github.com/RobotLocomotion/drake/blob/c6311cdb2ba4e4bc657eb5e9f5663c1a709006d5/common/symbolic/polynomial.h#L314)):*
Grant's request was:

> ... either directly or by making this parameter a std::optional defaulted to std::nullopt?

The "either directly" phrasing meant "cached = nullptr" as the default.  It's a fine choice, and the correct one here.  An optional pointer is silly and confusing, as Hongkai notes.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-:-NPP76FF7XVDsbvRT-LD:bnfp4nl)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
I think that -@ggould-tri got assigned by mistake in discussions below.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-:-NPP7MAV7IL211Xebe96:b-hxoldg)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Is there anything more I need to do to get this merged?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18887#-:-NPTZwUy0z0Elj2bk-UC:b-kgvyq1)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Comment by hongkai-dai** [comment]
You can squash and merge the commit. Maybe edit the commit message when you click the "squash and merge" button on github.

**Comment by jwnimmer-tri** [comment]
I merged it.

For the record, the intended workflow is that platform review (@rpoyner-tri) would have merged it for you, once it was ready.  It's also OK for Hongkai or yourself to do it.

See https://drake.mit.edu/reviewable.html#curated-commits (which was linked from the reviewable status modeline, though it's very subtle).

**Pull request merged**
