### PR TITLE
[SAP] Implements SapContactProblem::AddConstraint()

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards landing the [SapSolver](https://github.com/RobotLocomotion/drake/projects/10). Full working prototype in https://github.com/RobotLocomotion/drake/pull/16543.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16618)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with two unblocking thoughts.
+@jwnimmer-tri for platform review per rotation please.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16618#-:-Mw84ptf3tIfpzlh7hiY:b-r2yt8a)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw7s16L4CCIx3EkyOfP:-Mw7s16L4CCIx3EkyOfQ:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L85)):*
> ```objc
>    [0, num_cliques()).
>    @throws if the number of columns of the Jacobian matrices in `constraint` are
>    not consistent with the number of velocities for the cliques in this problem
> ```

nit



_Suggestion:_
```objc
   @throws if the number of columns of the Jacobian matrices in `constraint` is
```
___
*[multibody/contact_solvers/sap/sap_contact_problem.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw7uXYh59LejOnZ6xuB:-Mw7uXYh59LejOnZ6xuC:bw65o4s) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.cc#L34)):*
> ```cpp
> 
> template <typename T>
> int SapContactProblem<T>::AddConstraint(std::unique_ptr<SapConstraint<T>> c) {
> ```

BTW, if we embrace the std::vector of cliques (with the requirement that the vector size is between 1 and 2) idea in the API of SapConstraint, then the implementation of this method can be 
```
  for (int clique : c->cliques()) {
    if (clique >= num_cliques()){
      throw ...
    }
    if (c->clique_jacobians()[clique].cols() != num_velocities(clique)){
      throw ...
    }
  }
  // Update graph.
  const int ni = c->num_constraint_equations();
  const int constraint_index = graph_.AddConstraint(c->cliques(), ni);

  constraints_.push_back(std::move(c));
```
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw83duGEw1HfrPxzrFG:-Mw83duGEw1HfrPxzrFH:b6nofc) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L184)):*
> ```cpp
>   EXPECT_EQ(graph.num_total_constraint_equations(), 17);
> 
>   // Verify clusters were created as expected in the diagram above:
> ```

BTW, here I think it would be enough to test that the `AddConstraint()` call is correctly forwarded to the graph, and the tests you have up to this line is good evidence of that. The rest is tested already in the ContactProblemGraph.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16618#-:-Mw8H_fE7eLdYravbF7s:b-vtj4vo)* status: 7 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8DVdO6KSz38TGo6bc:-Mw8DVdO6KSz38TGo6bd:bnoj3r7) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L8)):*
> ```objc
> #include "drake/common/drake_copyable.h"
> #include "drake/common/eigen_types.h"
> #include "drake/common/sorted_pair.h"
> ```

nit Unused header.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8D0pb74I62ZS3Ix9E:-Mw8D0pd-FhwbLsndvb5:brtmgex) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L82)):*
> ```objc
> 
>   /* Adds `constraint` to this problem.
>    @throws if the clique indexes referenced by `constraint` are not in the range
> ```

nit Even in private comments, if we use Doxygen markup then we need to use it correctly.  The `@throws` markup requires an exception name or type.



_Suggestion:_
```objc
@throws exception if
```
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 109 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8EU2b0y8JWLPOn5om:-Mw8EU2b0y8JWLPOn5on:b9xsbxz) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L109)):*
> ```objc
>    ni is the number of constraint equations for the i-th constraint, see
>    SapConstraint::num_constraint_equations(). */
>   int num_constraint_equations() const {
> ```

nit If one function is named `num_constraint_equations` and the other is named `num_total_constraint_equations`, then there needs to be a good reason why the two names differ.  We should always strive to use the same words to refer to the same idea, and only vary in terminology when we're trying to draw a distinction.

For example, the two functions might be referring to distinct concepts, but that does not seem to be the case here, since this one just calls the other one.

Or, in one API there might be ambiguity about whether the number is a total count or not, but in an other API there is no ambiguity.  That might be the case here, but on first look it seems not.

I suspect that the `num_total_constraint_equations` is just an accident and should be named `num_constraint_equations`, but I'll let author & feature review decide whether they are supposed to be distinct concepts.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8EL2yDlMF494P7mEK:-Mw8EL2yDlMF494P7mEL:bmf6znj) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L113)):*
> ```objc
>   }
> 
>   /* Access constraint with index `constraint_index` as assigned by the call to
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Function_Comments



_Suggestion:_
```objc
Accesses
```
___
*[multibody/contact_solvers/sap/sap_contact_problem.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8GNwJDooQb2u61dx2:-Mw8GNwK8g9ueiILgtU-:b-fszvmk) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.cc#L37)):*
> ```cpp
>   if (c->first_clique() >= num_cliques())
>     throw std::runtime_error(
>         "First clique index must be strictly lower than num_cliques()");
> ```

We need curly braces here, when using multiple lines.

https://drake.mit.edu/styleguide/cppguide.html#Conditionals
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw83duGEw1HfrPxzrFG:-Mw8HJfn3z3COxIwfxaY:bm83lqx) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L184)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, here I think it would be enough to test that the `AddConstraint()` call is correctly forwarded to the graph, and the tests you have up to this line is good evidence of that. The rest is tested already in the ContactProblemGraph.
</blockquote></details>

Yeah, the less copy-pasta we can have across unit tests, the better.  It's a real drain on our eyeball resources.  If there's no plausible way that I could change the sap_contact_problem.cc file to break these checks, then they don't belong here.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16618)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 109 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8EU2b0y8JWLPOn5om:-MwRlqZ_AM3UpIH_K8LP:blchv76) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If one function is named `num_constraint_equations` and the other is named `num_total_constraint_equations`, then there needs to be a good reason why the two names differ.  We should always strive to use the same words to refer to the same idea, and only vary in terminology when we're trying to draw a distinction.

For example, the two functions might be referring to distinct concepts, but that does not seem to be the case here, since this one just calls the other one.

Or, in one API there might be ambiguity about whether the number is a total count or not, but in an other API there is no ambiguity.  That might be the case here, but on first look it seems not.

I suspect that the `num_total_constraint_equations` is just an accident and should be named `num_constraint_equations`, but I'll let author & feature review decide whether they are supposed to be distinct concepts.
</blockquote></details>

I think you are absolutely right @jwnimmer-tri. I think in the review of that PR somehow we started confusing the names withing the scope of the graph with those within the scope of a clique, a different class. However there is no ambiguity given the class nicely scopes these concepts. 
Therefore I decided to follow your suggestion and name the graph's method consistently to `num_constraint_equations()`.
I did it in this same PR, leh me know if you prefer me doing the change as a separate PR.
___
*[multibody/contact_solvers/sap/sap_contact_problem.cc, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw7uXYh59LejOnZ6xuB:-MwRoCPA-mrlB2fkR-6j:bv8f0dd) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.cc#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, if we embrace the std::vector of cliques (with the requirement that the vector size is between 1 and 2) idea in the API of SapConstraint, then the implementation of this method can be 
```
  for (int clique : c->cliques()) {
    if (clique >= num_cliques()){
      throw ...
    }
    if (c->clique_jacobians()[clique].cols() != num_velocities(clique)){
      throw ...
    }
  }
  // Update graph.
  const int ni = c->num_constraint_equations();
  const int constraint_index = graph_.AddConstraint(c->cliques(), ni);

  constraints_.push_back(std::move(c));
```
</blockquote></details>

I added this in #16575 (in the project's TODOs already so we don't loose track of it) so that we have this nice example, I like it.
I'll however wait to see how this API helps in other places before committing to it.
___
*[multibody/contact_solvers/sap/sap_contact_problem.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8GNwJDooQb2u61dx2:-MwRpDdg2v1qaFBK9Tws:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.cc#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We need curly braces here, when using multiple lines.

https://drake.mit.edu/styleguide/cppguide.html#Conditionals
</blockquote></details>

Done.
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw83duGEw1HfrPxzrFG:-MwRqtOu5FvVduJDzvCN:b-bkhtke) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L184)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, the less copy-pasta we can have across unit tests, the better.  It's a real drain on our eyeball resources.  If there's no plausible way that I could change the sap_contact_problem.cc file to break these checks, then they don't belong here.
</blockquote></details>

Fair, the indirect tests above actually are enough. I tried breaking the code in the source and these tests always failed. So yes, they are enough.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16618)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 109 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16618#-Mw8EU2b0y8JWLPOn5om:-MwRsnxNBjnX9H2DNABK:bkw5s8e) ([raw file](https://github.com/robotlocomotion/drake/blob/d7191e099f4be70096d1aca9cb963d9ace3199ec/multibody/contact_solvers/sap/sap_contact_problem.h#L109)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think you are absolutely right @jwnimmer-tri. I think in the review of that PR somehow we started confusing the names withing the scope of the graph with those within the scope of a clique, a different class. However there is no ambiguity given the class nicely scopes these concepts. 
Therefore I decided to follow your suggestion and name the graph's method consistently to `num_constraint_equations()`.
I did it in this same PR, leh me know if you prefer me doing the change as a separate PR.
</blockquote></details>

OK LGTM!

**Pull request merged**
