### PR TITLE
[pydrake/common] Bind default constructor for TypeSafeIndex

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17825)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

I am curious, though, why this is useful in Python.  In C++ we only have it for STL compatibility, e.g., `std::vector<FooIndex>` can be  pre-allocated with a bunch of invalid elements which are then reset later on.

What's the Python use case for this constructor?

(Remember that adding in-earnest control flow based on `foo_index.is_valid()` is against the API docs, e.g., as a defaulted "null" argument; rather we need `std::optional<FooIndex>` if we want to represent missing values.)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17825#-:-NAzgJFi2l-vOsroKlbr:bkw2c96)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
If that control flow is discouraged, I can certainly accomplish my goals another way.  (e.g. setting my index to None in python).  If that's the preferred approach, then we could just zap this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17825#-:-NAzh6J22EYM-3BztPew:bcbl7wr)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
or perhaps instead put a comment like you've written above instead of the binding, to remind me of the logic for not binding this constructor when I go to do the same thing a year from now.

**Comment by jwnimmer-tri** [comment]
Yes; see:

https://github.com/RobotLocomotion/drake/blob/6745bdf757c1ec976ae62cbdd805d8733e4463d3/common/type_safe_index.h#L55-L63

(Using the invalid value as a sentinel is outlawed by the class documentation.)

I don't mind binding this. Perhaps someone wants to pre-fill a ndarray with invalid indices at some point?  It's probably best to keep the binding, just for parity.

If you decide not to bind, it though, we should probably add a placeholder comment explaining why for the next person who tries it -- either `@exclude_from_pydrake_mkdoc` in the C++ header, or a comment in the bindings saying "Don't bind 0args because there are no STL containers in Python."

**Comment by jwnimmer-tri** [comment]
> It's probably best to keep the binding, just for parity.

I'm pretty convinced this is the correct plan, so I'll merge this now.

**Pull request merged**
