### PR TITLE
Add eigen_stl_types.h and BodyToWrenchMap

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Two clean-ups related to external wrenches:
- Rename f_ext to to external_wrenches and add BodyToWrenchMap alias.
- Extract eigen_aligned_std_unordered_map into common.

... which contributes to #3278.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3405)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@tkoolen I'd appreciate if you have any input on this, or time to fully review it.

I wonder specifically if this is an improvement, or if you'd rather that I keep the generic `eigen_aligned_unordered_map` typedef and put it into `drake/common/eigen_...h` somewhere?

I can sit on it for perhaps a week or so if that helps.

**Comment by tkoolen** [comment]
I think having a convenience typedef for this is a good idea. I would perhaps change the name to `WrenchMap`, or `BodyToWrenchMap`. `f_ext` was used as the argument name primarily because I was still trying to match the Matlab code at the time. `external_wrenches` would be better now as the argument name.

I would prefer to keep `eigen_aligned_unordered_map` somewhere, maybe in eigen_types.h. Perhaps rename, since it doesn't adhere to the current code standard. I remember it took quite a while to figure out how to fix alignment issues with `unordered_map`s that map to a fixed-size vectorizable Eigen type. This change hides that knowledge somewhat.

`inverseDynamics` and `dynamicsBiasTerm` are often called with an empty map as the `f_ext` argument. It would be nice to add some delegating functions that streamline this case.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRH36GhLissCM-1wbGQ:b-4gbsr8)*

**Comment by jwnimmer-tri** [comment]
That all sounds good.  I will rework this a bit.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRHH868Ac3uwRKh0G9Z:b61s0lx)*

**Comment by jwnimmer-tri** [comment]
+@tkoolen I've revised the PR, PTAL when you have time.

> I would perhaps change the name to ... BodyToWrenchMap, ...

Done.

> I would prefer to keep eigen_aligned_unordered_map somewhere, maybe in eigen_types.h.

Done (`eigen_stl_types.h`).  I have a future PR on deck that adds `std::vector` conveniences there next.

> Perhaps rename, since it doesn't adhere to the current code standard. 

I thought there was an exception to the rule for STL-mimicing classes, but I'm not seeing it now.  I will consult with platform reviewer, but I think we can still review this version usefully.

> inverseDynamics and dynamicsBiasTerm are often called with an empty map as the f_ext argument. It would be nice to add some delegating functions that streamline this case.

Now it's a bit nicer now with a `no_external_wrenches` mnemonic at every call site.  I started trying to do more, but hit the #3114 / #2201 rats nest, and this PR was already fairly large.  I think it would make sense for one person to design a new comprehensive API set for `inverseDynamics` and its efficiency / convenience overloads (or defaults) all at once, rather than me trying to chip away at it here.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KROQGI4UOp77Exdl_sN:bklc1r1)*

**Comment by tkoolen** [comment]
Looks good to me, no comments about the code, and I agree with your proposal of designing a new API set for `inverseDynamics`.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KROegZ2RJE8kiO8qiOp:b-xs2jif)*

**Comment by tkoolen** [comment]
:lgtm:

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KROfhDCS2sg35oXWiEJ:bnfp4nl)*

**Comment by tkoolen** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by tkoolen** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KROfx9qk2NNyflTUaTi:bnfp4nl)*

**Comment by tkoolen** [comment]
Sorry, still getting the hang of Reviewable from a reviewer's perspective.

**Comment by jwnimmer-tri** [comment]
No worries, thanks for the read-through and suggestions.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

What did we decide about `snake_case` for typenames that mimic the STL?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KROlR8OpNympidSp2ur:brrtk8d)*

**Comment by sherm1** [comment]
Per [Google style guide](https://google.github.io/styleguide/cppguide.html#Exceptions_to_Naming_Rules): "If you are naming something that is analogous to an existing C or C++ entity then you can follow the existing naming convention scheme.". They give an (outdated) example `sparse_hash_map` that I think is analogous to the case here. So, :+1: for `eigen_aligned_unordered_map` from this platform reviewer.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRR1LVIpDUjrslnv92P:bg7f3tp)*

**Comment by sherm1** [comment]
Platform review pass done: Looks good with a few comments, PTAL.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/test/eigen_stl_types_test.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR3JZRfsGoF7OqOazE:-KRR3JZRfsGoF7OqOazF:b-19s27h) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/common/test/eigen_stl_types_test.cc#L15)):*
> ```cpp
> GTEST_TEST(EigenStlTypesTest, UnorderedMapTest) {
>   // The device under test ("dut").
>   eigen_aligned_std_unordered_map<int, Vector2d> dut0;
> ```

Please repeat the test for `Vector4d`, to ensure that we are actually getting alignment in Eigen 3.3 with [AVX support](http://eigen.tuxfamily.org/index.php?title=3.3#Vectorization) which requires 32-byte alignment.

---

*[drake/common/test/eigen_stl_types_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR2vrnImbqzUN-q_l5:-KRR2vrnImbqzUN-q_l6:bnav42n) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/common/test/eigen_stl_types_test.cc#L21)):*
> ```cpp
>   dut1->insert(std::make_pair(1, Vector2d::Ones()));
> 
>   EXPECT_TRUE(true);
> ```

BTW, this statement gives me a pleasant, Zen-like feeling of calm.

---

*[drake/examples/Acrobot/test/urdfDynamicsTest.cpp, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR87OnvVVDQuMObT4m:-KRR87OnvVVDQuMObT4n:b-whm8qy) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/examples/Acrobot/test/urdfDynamicsTest.cpp#L50)):*
> ```cpp
>     /*
>     auto kinsol_urdf = r_urdf.getRigidBodyTree()->doKinematics(x0_rb.topRows(2),
>     x0_rb.bottomRows(2));
> ```

BTW, any reason not to nuke this comment rather than maintain it?

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 793 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR8VVZmzRla5z6rj7N:-KRR8VVZmzRla5z6rj7O:b-dgn2y0) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/controllers/InstantaneousQPController.cpp#L793)):*
> ```cpp
>   }
> 
>   // handle external wrenches to compensate for
> ```

BTW, should fix comment punctuation while you are hacking here.

---

*[drake/systems/plants/RigidBodyTree.h, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR5X5h0yLT2Pl1X9f4:-KRR5X5iAdb8aKcp5XzV:b-g2ec1k) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L343)):*
> ```objc
>   template <typename Scalar>
>   using BodyToWrenchMap = drake::eigen_aligned_std_unordered_map<
>     RigidBody const*, drake::TwistVector<Scalar>>;
> ```

In screw theory a "twist" is a velocity, *not* a force. So the vector type here should be `drake::WrenchVector<Scalar>`. Unfortunately that doesn't appear to be defined (its definition in eigen_types.h would be identical to `TwistVector`).

@tkoolen, is there some reason you defined TwistVector but not WrenchVector? (A generic 6-element type useful for both of these and other quantities ought to have a more generic name like `SpatialVector`.)

---

*[drake/systems/plants/RigidBodyTree.h, line 360 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR6IC8C0xiQQq0yyKe:-KRR6IC8C0xiQQq0yyKf:b-ogdynb) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L360)):*
> ```objc
>       KinematicsCache<Scalar>& cache,
>       const drake::eigen_aligned_std_unordered_map<
>           RigidBody const*, drake::TwistVector<Scalar>>& external_wrenches,
> ```

BTW, can't this use `BodyToWrenchMap`?

---

*[drake/systems/plants/RigidBodyTree.h, line 394 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR6OeChmq4KmcQRhhD:-KRR6OeChmq4KmcQRhhE:b-u9l07r) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L394)):*
> ```objc
>       KinematicsCache<Scalar>& cache,
>       const drake::eigen_aligned_std_unordered_map<
>           RigidBody const*, drake::TwistVector<Scalar>>& external_wrenches,
> ```

BTW, `BodyToWrenchMap`?

---

*[drake/util/drakeUtil.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR8xbFnTfUYe64Q5uL:-KRR8xbGeJHATBANvNvx:b-csa2bx) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/util/drakeUtil.h#L24)):*
> ```objc
> using eigen_aligned_unordered_map
> #ifndef _MSC_VER
>     DRAKE_DEPRECATED("Use drake::eigen_aligned_std_unordered_map")
> ```

BTW, why did you have to exclude Windows here? (Not that this will be relevant for long.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRR9BC0Vbqm3Ytcdkm_:b-itmgoa)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/Acrobot/test/urdfDynamicsTest.cpp, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR87OnvVVDQuMObT4m:-KRRSvFXEBRCDtIT-K5P:b26rdua) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/examples/Acrobot/test/urdfDynamicsTest.cpp#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, any reason not to nuke this comment rather than maintain it?
</details>
I looked at the git history and it seemed like something Russ might want to keep.

---

*[drake/systems/plants/RigidBodyTree.h, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR5X5h0yLT2Pl1X9f4:-KRRTii0LmXxiUzrZxVU:b5aighw) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L343)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> In screw theory a "twist" is a velocity, *not* a force. So the vector type here should be `drake::WrenchVector<Scalar>`. Unfortunately that doesn't appear to be defined (its definition in eigen_types.h would be identical to `TwistVector`).
> 
> @tkoolen, is there some reason you defined TwistVector but not WrenchVector? (A generic 6-element type useful for both of these and other quantities ought to have a more generic name like `SpatialVector`.)
</details>
#3262 Uses `Matrix6X<T>` for I think this reason, but you've seen that PR already.  I will happily change this spelling to whatever you all agree on.

---

*[drake/systems/plants/RigidBodyTree.h, line 360 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR6IC8C0xiQQq0yyKe:-KRRTDObGmD3kIWLECK2:b-nkmgwo) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L360)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, can't this use `BodyToWrenchMap`?
</details>
Possibly, but then SWIG emits a warning that it might not handle the signature correctly.  Rather than chase that down, I left it more similar to the existing code.

---

*[drake/systems/plants/RigidBodyTree.h, line 394 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR6OeChmq4KmcQRhhD:-KRRTKwiPToNwZZVpsZT:bs4q9op) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L394)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `BodyToWrenchMap`?
</details>
Ditto.

---

*[drake/util/drakeUtil.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR8xbFnTfUYe64Q5uL:-KRRSXY4cRU4aEw5mAcl:b-15jlhd) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/util/drakeUtil.h#L24)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, why did you have to exclude Windows here? (Not that this will be relevant for long.)
</details>
It emitted a compile error when I left it in:
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=107954

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by jwnimmer-tri** [comment]
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/eigen_stl_types_test.cc, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR3JZRfsGoF7OqOazE:-KRU5XAxU5HQ3anf9UhJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/common/test/eigen_stl_types_test.cc#L15)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Please repeat the test for `Vector4d`, to ensure that we are actually getting alignment in Eigen 3.3 with [AVX support](http://eigen.tuxfamily.org/index.php?title=3.3#Vectorization) which requires 32-byte alignment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by sherm1** [comment]
:lgtm: pending response from @tkoolen and probable name change to WrenchVector or something more generic.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/drakeUtil.h, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR8xbFnTfUYe64Q5uL:-KRUKKyD056-z3o27rcr:bb70xp9) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/util/drakeUtil.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> It emitted a compile error when I left it in:
> https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=107954
</details>
OMG!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRUKV8XDxR10gxGWIaJ:b-199cbm)*

**Comment by tkoolen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR5X5h0yLT2Pl1X9f4:-KRUORLiRvE4sMDHWbVr:b-o2uudc) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L343)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #3262 Uses `Matrix6X<T>` for I think this reason, but you've seen that PR already.  I will happily change this spelling to whatever you all agree on.
</details>
I never created `TwistVector`. A `WrenchVector` type alias is a good solution until we make a proper `Wrench` class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR5X5h0yLT2Pl1X9f4:-KRZM3dXQHCAlZo0ahQF:bgesjhz) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L343)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I never created `TwistVector`. A `WrenchVector` type alias is a good solution until we make a proper `Wrench` class.
</details>
Done.

I think I renamed all of the places this PR touches where Wrench should be used instead of Twist.  I see a few more likely candidates in RBT, but I'm not planning on touching them in this PR.

PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by jwnimmer-tri** [comment]
Review status: 13 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 343 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-KRR5X5h0yLT2Pl1X9f4:-KR_2Cmqki-4YwqXo5sJ:bbwg2tc) ([raw file](https://github.com/robotlocomotion/drake/blob/a2ad0d296164cd20396e022095f7b80686329667/drake/systems/plants/RigidBodyTree.h#L343)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Done.
> 
> I think I renamed all of the places this PR touches where Wrench should be used instead of Twist.  I see a few more likely candidates in RBT, but I'm not planning on touching them in this PR.
> 
> PTAL.
</details>
@sherm1 PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by tkoolen** [comment]
Sorry, this was blocked on me, ready to go.

---

Review status: 13 of 21 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRaJ1zFZix35IZm6uW_:b-y5n7li)*

**Comment by tkoolen** [comment]
Reviewed 1 of 1 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405)*

**Comment by jwnimmer-tri** [comment]
Thanks!  Also still blocked on @sherm1 though. 
(And probably will conflict with #3262, so I was going to let that one to go in first.)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRaJkIpZXsdAEun249X:b2dv3u4)*

**Comment by jwnimmer-tri** [comment]
Merge conflicts resolved.  PTAL.

(Note that reviewable isn't quite showing the merge edits on RBT perfectly, so consider flipping it back to ⊥ for re-review).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRadtuYfQ32n9HmPzew:b7b3xb)*

**Comment by tkoolen** [comment]
Looks good to me, compliments for being on top of my new usages of `inverseDynamics` right away.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRafvl2WAYbB812xdj1:b-34folo)*

**Comment by sherm1** [comment]
:lgtm:, thanks for the `WrenchVector`! (I only reviewed the changes I saw here, didn't check to see if there are any other TwistVectors that need upgrading.) There is one blocking comment from @tkoolen.

---

Reviewed 6 of 8 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3405#-:-KRaluANcOoYdRpLXp-2:b-xh303w)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to tonight's permanent windows flake.

**Pull request merged**
