### PR TITLE
Add AddL2NormCost to MathematicalProgram

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in #15366

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092#-:-MoL98JA7IEX6kGG8g_U:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Thanks!  One request below.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092#-:-MoYlnqp7zqmc3OnOkhQ:b-xzpomd)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoYlee72RytRRTTY-zh:-MoYlee72RytRRTTY-zi:b27bkbo) ([raw file](https://github.com/robotlocomotion/drake/blob/8033eb6392b912203003eede5c27987122a219ba/solvers/mathematical_program.h#L1130)):*
> ```objc
>    * Adds an L2 norm cost |Ax+b|₂ (notice this cost is not quadratic since we
>    * don't take the square of the L2 norm).
>    */
> ```

i think it's obviously good to do this PR as the first step.  i only worry that this is a bit of a trap right now, since no solvers actually support it.  can we add a comment to that effect here to warn / redirect a potential user?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[solvers/mathematical_program.h, line 1130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoYlee72RytRRTTY-zh:-MoZQFqc-QPosCRvTE7J:b-4zxw0m) ([raw file](https://github.com/robotlocomotion/drake/blob/8033eb6392b912203003eede5c27987122a219ba/solvers/mathematical_program.h#L1130)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think it's obviously good to do this PR as the first step.  i only worry that this is a bit of a trap right now, since no solvers actually support it.  can we add a comment to that effect here to warn / redirect a potential user?
</blockquote></details>

Done. I added a TODO here.

Currently if the user calls `AddL2NormCost`, then program.required_capabilities() will include `kL2NormCost`. None of the solvers support this capability, so when the users call `Solve` function, it would throw an message complaining about `kL2NormCost`.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoYlee72RytRRTTY-zh:-MoZ_HCt2NH0t_iQoIrB:b-8zils4) ([raw file](https://github.com/robotlocomotion/drake/blob/8033eb6392b912203003eede5c27987122a219ba/solvers/mathematical_program.h#L1130)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I added a TODO here.

Currently if the user calls `AddL2NormCost`, then program.required_capabilities() will include `kL2NormCost`. None of the solvers support this capability, so when the users call `Solve` function, it would throw an message complaining about `kL2NormCost`.
</blockquote></details>

Thanks.  I thought the TODO had to go before the doxgyen, not after?  but i was actually asking for it to appear in the doxygen, rather than in a TODO that is only visible in the code.  If you feel strongly that it should be a TODO, I'm ok with it.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[solvers/mathematical_program.h, line 1130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoYlee72RytRRTTY-zh:-MoZbD5I9PyPe0mxSXbP:b3ur7h9) ([raw file](https://github.com/robotlocomotion/drake/blob/8033eb6392b912203003eede5c27987122a219ba/solvers/mathematical_program.h#L1130)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Thanks.  I thought the TODO had to go before the doxgyen, not after?  but i was actually asking for it to appear in the doxygen, rather than in a TODO that is only visible in the code.  If you feel strongly that it should be a TODO, I'm ok with it.
</blockquote></details>

Done. I moved the text to the doxygen, and added a TODO to support the solver.

**Review by hongkai-dai — COMMENTED** [review]
@russtedrake is it OK if I pass this PR to the platform reviewer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092#-:-MojSeWy7PntWqceWVUi:b-poeblf)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  +@ericcousineau-tri for platform review, please.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092#-:-MonYDKi46F0clA5zoTe:bga7hqf)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, with very minor nit (feel free to ignore)
+(release notes: yes) 

> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092#-:-MonjNBD5jYHdBdyyu9A:buvjdvq)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1130 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-Monh7zu7uXivPiFiPVh:-Monh7zu7uXivPiFiPVi:b-oopez2) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1130)):*
> ```objc
>    * Adds an L2 norm cost |Ax+b|₂ (notice this cost is not quadratic since we
>    * don't take the square of the L2 norm).
>    * @note currently no solver supports kL2NormCost, and the user will
> ```

nit Capitalization, `@note Currently`

See existing usages: `$grep -rnI '@note'`
___
*[solvers/mathematical_program.h, line 1133 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-Mongwif0PlZIEMZTkOd:-Mongwif0PlZIEMZTkOe:b-92z76x) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1133)):*
> ```objc
>    * receive an error message if they add L2NormCost and call Solve().
>    */
>   // TODO(hongkai.dai): support L2NormCost in each solver.
> ```

BTW I thought interleaved comments would break `mkdoc`, but seems that's no longer the case ae856bcbe7
___
*[solvers/mathematical_program.h, line 1138 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoniwrKBTDIaudf3YM2:-MoniwrKBTDIaudf3YM3:b-kb0u6) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1138)):*
> ```objc
>   /**
>    * Adds an L2 norm cost |Ax+b|₂
>    */
> ```

BTW These are clearly overloads of the above `AddCost(Binding<L2NormCost>)`, but it isn't explicitly clear (thus, users may ignore the caveats / notes in original method).

However, this is a pre-existing defect w/ other overloads.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[solvers/mathematical_program.h, line 1130 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-Monh7zu7uXivPiFiPVh:-MonpKC9ARusg1a7esRn:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1130)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Capitalization, `@note Currently`

See existing usages: `$grep -rnI '@note'`
</blockquote></details>

Done. Thanks!
___
*[solvers/mathematical_program.h, line 1138 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoniwrKBTDIaudf3YM2:-MonptIOAJXcMnbu0mEy:bcoo7e7) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW These are clearly overloads of the above `AddCost(Binding<L2NormCost>)`, but it isn't explicitly clear (thus, users may ignore the caveats / notes in original method).

However, this is a pre-existing defect w/ other overloads.
</blockquote></details>

I added @pydrake_mkdoc_identifier for the overloaded version to disambiguate from `AddCost(Binding<L2NormCost>)`.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1138 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoniwrKBTDIaudf3YM2:-MontqA8E2lLyu_vmAGV:bj3ssfo) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1138)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added @pydrake_mkdoc_identifier for the overloaded version to disambiguate from `AddCost(Binding<L2NormCost>)`. 
</blockquote></details>

OK Ah, defect isn't w/ Python bindings, but rather documentation itself. A user may see the docs for the `AddL2NormCost`, and ignore the notes / caveats mentioned in `AddCost(Binding<>)`.

That being said, it's pre-existing b/c other overloads above do about the same thing.

Possible solution: Move notes to method with qualified name (e.g. `AddL2NormCost`), and reference that method from other flavors `AddCost(Binding<>)` and other overloads.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI)

___
*[solvers/mathematical_program.h, line 1138 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoniwrKBTDIaudf3YM2:-MonwFbx4xWKKma9SioK:b-kufkxf) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, defect isn't w/ Python bindings, but rather documentation itself. A user may see the docs for the `AddL2NormCost`, and ignore the notes / caveats mentioned in `AddCost(Binding<>)`.

That being said, it's pre-existing b/c other overloads above do about the same thing.

Possible solution: Move notes to method with qualified name (e.g. `AddL2NormCost`), and reference that method from other flavors `AddCost(Binding<>)` and other overloads.
</blockquote></details>

I see, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16092)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1138 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16092#-MoniwrKBTDIaudf3YM2:-MonxQpID4Dp3_KPZZd8:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake/blob/130ad1230df8505881741f01e26283b599a7161e/solvers/mathematical_program.h#L1138)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, thanks!
</blockquote></details>

OK Sweet, thanks!

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI you added "release notes: yes" to this -- but given that _"Currently no solver supports kL2NormCost, and the user will receive an error message if they add L2NormCost and call Solve"_ do we **actually** want to announce this new feature in the release notes yet?

**Comment by hongkai-dai** [comment]
Agreed, it is better to keep this feature unnoticed for the moment until the solvers support this new cost form.

**Pull request merged**
