### PR TITLE
Move SHARED option to superbuild

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Move the option to enable shared libraries (***`ON`** by default!*) to the superbuild. This fixes unintentionally making drake build static libraries. Note that this also propagates to externals, so some externals may newly build shared libraries. (Several externals already force shared libraries; these will continue to do so.)

@jamiesnape for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4141)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please	 
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by mwoehlke-kitware** [comment]
+@david-german-tri for platform review

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4141#-:-KWhxCle_iK_iGk13Lsn:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Apparently, xfoil shared ends badly...

**Comment by jamiesnape** [comment]
There is probably a clash between the shared library names. In any case, they should be static only.

**Comment by mwoehlke-kitware** [comment]
> There is probably a clash between the shared library names.

I don't think that's it; it's trying to link non-PIC code into a (newly) shared library.

> In any case, they should be static only.

Why?

**Comment by jamiesnape** [comment]
Building XFOIL PIC does not make sense. It is a single executable. In any case, if XFOIL is PIC, AVL would need to be PIC. The code is literally identical.

**Comment by jamiesnape** [comment]
You now have two `libplt.so` from two different externals.

**Comment by mwoehlke-kitware** [comment]
> Building XFOIL PIC does not make sense. It is a single executable.

The error happens when trying to link `plotlib/libplt.so`.

**Comment by jamiesnape** [comment]
Indeed. That is a purely private library because the author was sharing code.

**Comment by mwoehlke-kitware** [comment]
Probably upstream should be making it explicitly `STATIC` then. Alas, I suspect upstream is dead for both of these?

**Comment by jamiesnape** [comment]
It is, but the CMake build is not. I will fix it. Can you make it explicitly static for now?

**Comment by mwoehlke-kitware** [comment]
Done. I also added a `TODO(jamiesnape)` to fix the projects themselves.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by mwoehlke-kitware** [comment]
Apparently this is blocked by dreal/dreal3#316.

**Comment by jamiesnape** [comment]
Could BUILD_SHARED_LIBS=OFF work around the problem for now?

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot retest this please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by mwoehlke-kitware** [comment]
I'm currently working with @soonho-tri to resolve the dReal issues, which will likely happen soon enough that it makes sense to just wait and then have this update dReal rather than working around it.

@soonho-tri, besides dreal/dreal3#318, are there other changes you'd like to see included in the dReal update?

**Comment by soonho-tri** [comment]
> @soonho-tri, besides dreal/dreal3#318, are there other changes you'd like to see included in the dReal update?

Nope. Thanks for all the helps today!!

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by david-german-tri** [comment]
This is currently do-not-review (as discussed f2f this morning), right?

**Comment by jamiesnape** [comment]
I think it was momentarily ready for review post-f2f and then the mac builds failed.

**Comment by mwoehlke-kitware** [comment]
This will be getting another dReal bump (probably tomorrow) to fix the macOS breakage (see dreal/dreal3#321).

@soonho-tri, now that it works, should I add `-DSUPPORT_ODE=OFF` while I'm at it? (Note to all: this turns of CAPD, which takes ages to `autoreconf`, and so should speed up the build a bit.)

**Comment by soonho-tri** [comment]
> @soonho-tri, now that it works, should I add -DSUPPORT_ODE=OFF while I'm at it? (Note to all: this turns of CAPD, which takes ages to autoreconf, and so should speed up the build a bit.)

Yes, that's fine for now.

**Comment by mwoehlke-kitware** [comment]
> I think it was momentarily ready for review post-f2f and then the mac builds failed.

Exactly :smile:. (I *think* that's in line to get fixed, though, but I'm *trying* to call it a night; I expect to be able to bump dReal again tomorrow and then it will hopefully be ready.)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

...should be ready if the builds pass...

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

(Forgot to turn off ODE; done now...)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r4.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4141#-:-KWshpcay5eKdCGARXI2:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4141)*

**Pull request merged**
