### PR TITLE
[workspace] Fix OpenUSD plugin loading

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20898.

~Something is still weird with `operator==` stuff on the stage, but I'm hoping we can co-evolve that with real parser regression tests.  This at least moves us closer.~

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
OMG I really hate custom smart pointers, but I think I finally got to the root cause and this should be ready to go now.

+@rpoyner-tri for feature review, please.

\CC @hong-nvidia FYI

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

___
*[`tools/workspace/openusd_internal/patches/dlopen_forbidden.patch` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-NxLE43-7l9Tf0wv2ufT:-NxLE430CZ8Ul_wy20-3:b-vj5doc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ea3b359d623df4bfe8bceb92f7b5a17d69be005/tools/workspace/openusd_internal/patches/dlopen_forbidden.patch#L1)):*
> ```Diff
> WIP
> ```

Working

On the next push, I'll write some explanatory text here.

**Review by jwnimmer-tri — COMMENTED** [review]
With fresh eyes this morning I noticed a few tweaks, and pushed some changes just now.

> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 12 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-:-NxTJw1J-m1SYNap9Jqi:b-u5h55f)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 12 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-:-NxTKYFe25WB-pLy26WR:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/workspace/openusd_internal/patches/weakptrfacade_cxx20.patch` line 11 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-NxTK0JP6C1l59vO0BLz:-NxTK0JP6C1l59vO0BM-:b-1lr4fl) ([raw file](https://github.com/RobotLocomotion/drake/blob/d836cdaa009778aeb101fde17c106714bc2f1fd4/tools/workspace/openusd_internal/patches/weakptrfacade_cxx20.patch#L11)):*
> ```Diff
> `this` and `p` were different, so the swapped ordering was formally
> ambiguous. We can fix this by using matching the type of `this` and
> `p`. There's no need to downcast to the derived type for any reason.
> ```

nit the grammar of this sentence lost me. Not sure what to suggest exactly.



_Code quote:_
```Diff
ambiguous. We can fix this by using matching the type of `this` and
`p`. There's no need to downcast to the derived type for any reason.
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-:-NxTOsqQESXnLvif9PT0:bybe5xg)* status: LGTM missing from assignee sherm1(platform)

___
*[`tools/workspace/openusd_internal/patches/weakptrfacade_cxx20.patch` line 11 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-NxTK0JP6C1l59vO0BLz:-NxTOv9G2DoaLtd76Edj:b-kybl7n) ([raw file](https://github.com/RobotLocomotion/drake/blob/d836cdaa009778aeb101fde17c106714bc2f1fd4/tools/workspace/openusd_internal/patches/weakptrfacade_cxx20.patch#L11)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit the grammar of this sentence lost me. Not sure what to suggest exactly.
</blockquote></details>

I gave it another shot.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408)* status: LGTM missing from assignee sherm1(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 12 of 12 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-:-NxTz-iWCjNoxxbMGCYa:b8qx53o)* status: 1 unresolved discussion

___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 18 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-NxTy1p365l0pYMPvkao:-NxTy1p365l0pYMPvkap:b-adavby) ([raw file](https://github.com/RobotLocomotion/drake/blob/578b39a99342e2095c22e7d343c3b065c2b9587f/multibody/parsing/test/usd_parser_test/box_plane.usda#L18)):*
> ```
>     }
>     def Cube "boxActor" (
>         prepend apiSchemas = ["PhysicsCollisionAPI", "PhysicsRigidBodyAPI", "PhysicsMassAPI"]
> ```

BTW consider wrapping these to 80 chars for easier reading

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21408)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

___
*[`multibody/parsing/test/usd_parser_test/box_plane.usda` line 18 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21408#-NxTy1p365l0pYMPvkao:-NxTzfnb5BwkqCYhCvc7:b-qcfrd7) ([raw file](https://github.com/RobotLocomotion/drake/blob/578b39a99342e2095c22e7d343c3b065c2b9587f/multibody/parsing/test/usd_parser_test/box_plane.usda#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider wrapping these to 80 chars for easier reading
</blockquote></details>

This is an good thought, but I'm going to put it on the back burner for now.  I think many times these files are saved by a GUI, not written by hand.  As we work with more and more USD files, we'll need to come up with a policy one way or another.

**Pull request merged**
