### PR TITLE
Fix Wunused-parameter in multibody/collision and multibody/shapes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6011)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.  This is using the new `unused` helper function ([docs](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0)).

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6011#-:-KjDfrWNQg802CebmrMl:bmxilld)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

**Comment by soonho-tri** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/collision/bullet_model.cc, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6011#-KjIwsQ9i8BAmNqS1qRZ:-KjIwsQ9i8BAmNqS1qR_:b-jnjbfo) ([raw file](https://github.com/robotlocomotion/drake/blob/634b4a7959a7f7695627e6b8d9bff856f42f5a4f/drake/multibody/collision/bullet_model.cc#L136)):*
> ```cpp
> 
> std::unique_ptr<btCollisionShape> BulletModel::newBulletSphereShape(
>     const DrakeShapes::Sphere& geometry, bool use_margins) {
> ```

This line can be 
```c++
const DrakeShapes::Sphere& geometry, bool) {
```
without using `drake::unused`, right?

Ditto for the following two cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6011)*

**Comment by soonho-tri** [comment]
Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/collision/fcl_model.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6011#-KjJKrZgCaUIkIPUhkwt:-KjJKrZgCaUIkIPUhkwu:bks3o49) ([raw file](https://github.com/robotlocomotion/drake/blob/634b4a7959a7f7695627e6b8d9bff856f42f5a4f/drake/multibody/collision/fcl_model.cc#L12)):*
> ```cpp
> // TODO(jamiesnape): Implement the model.
> 
> void FCLModel::DoAddElement(const Element& element) {
> ```

I thought that it's still good to leave the name of the parameter,`element`, in the definition of a virtual method (because it's not a declaration and shouldn't affect the documentation). Could you clarify if I'm wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6011)*

**Comment by jwnimmer-tri** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/collision/bullet_model.cc, line 136 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6011#-KjIwsQ9i8BAmNqS1qRZ:-KjKAYx9lQjVoEzfscO-:b-5clrub) ([raw file](https://github.com/robotlocomotion/drake/blob/634b4a7959a7f7695627e6b8d9bff856f42f5a4f/drake/multibody/collision/bullet_model.cc#L136)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

This line can be 
```c++
const DrakeShapes::Sphere& geometry, bool) {
```
without using `drake::unused`, right?

Ditto for the following two cases.
</blockquote></details>

Done.  (I'd left them in there because of "WAT?!" but I should have marked with a TODO.)

---

*[drake/multibody/collision/fcl_model.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6011#-KjJKrZgCaUIkIPUhkwt:-KjK7-N4E0I9qbz_lD_g:b-kdmpmt) ([raw file](https://github.com/robotlocomotion/drake/blob/634b4a7959a7f7695627e6b8d9bff856f42f5a4f/drake/multibody/collision/fcl_model.cc#L12)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I thought that it's still good to leave the name of the parameter,`element`, in the definition of a virtual method (because it's not a declaration and shouldn't affect the documentation). Could you clarify if I'm wrong?
</blockquote></details>

In most cases I would have removed the names here.  But in this case, the intent is to actually implement these methods (and use the parameters) -- the exception-stub nature of this file is temporary.  As such, I thought I would save the future implementor some time and leave them here for now, so they don't have to re-transcribe the names from the header into here when they go to implement this class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6011)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6011#-:-KjKvjF9A-zDgbq-JaNk:bnfp4nl)*

**Pull request merged**
