### PR TITLE
MonteCarlo (parallel): serialize ScalarSystemFunction calls

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17753)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Comment by calderpg-tri** [comment]
@RussTedrake @jwnimmer-tri as previously mentioned on slack and in #17363 , a restructure of `MonteCarloSimulationParallel` that would serialize calls to the output function, thus allowing the output function to be Python code via bindings. If combined with Python system detection mentioned in #17363, it would be possible to enable thread-based parallel simulation through bindings.

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Comment by jwnimmer-tri** [comment]
Good day, @calderpg-tri. This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer. If not, then please label it “status: do not review”.

**Comment by calderpg-tri** [comment]
Closing as serializing `ScalarSystemFunction` is not itself that important - serialization for functions provided in pydrake bindings can be handled via proper GIL handling instead.

The cv-rather-than-polling-wait elements of this PR will be done separately along the lines of CRU's `async`-based `DynamicParallelFor` loop.

**Pull request closed without merging**
