### PR TITLE
Overload Trajectory::vector_values to accept Eigen::VectorXd

### PR DESCRIPTION
**Pull request by RussTedrake**
This makes it easier (in c++) to, for instance, using Eigen::LinSpaced to sample at regular intervals from a trajectory.

+@xuchenhan-tri for both reviews, please (if it's not too late).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19422)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19422)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`common/trajectories/trajectory.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-NVfW71-CksFjW0102SW:-NVfW71-CksFjW0102SX:b-vgcsc1) ([raw file](https://github.com/RobotLocomotion/drake/blob/b50b072e48225468c79eb03706dc17b239668ef6/common/trajectories/trajectory.h#L56)):*
> ```objc
>    * @throws std::exception if both cols and rows are not equal to 1.
>    */
>   MatrixX<T> vector_values(const Eigen::Ref<const Eigen::VectorXd>& t) const;
> ```

BTW Why is this overload limited to double-valued times, while the other one allows for autodiff times (etc)?



_Suggestion:_
```objc
VectorX<T>
```
___
*[`common/trajectories/trajectory.cc` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-NVfWFCS7sv84T7z7Vix:-NVfWFCS7sv84T7z7Viy:bmg6685) ([raw file](https://github.com/RobotLocomotion/drake/blob/b50b072e48225468c79eb03706dc17b239668ef6/common/trajectories/trajectory.cc#L9)):*
> ```cpp
> 
> template <typename T>
> MatrixX<T> Trajectory<T>::vector_values(const std::vector<T>& t) const {
> ```

BTW If the other overload accepts `<T>` instead of `double`, then this function should switch to calling the other one using an `Eigen::Map` to avoid the duplication.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: pending Jeremy's comment.

BTW should we include this in the release notes? It'd be something new for C++ users.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-:-NVfegV5269dui9Sph7g:b9frm8t)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`common/trajectories/trajectory.cc` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-NVfcpvdB38BhdCB0OwZ:-NVfcpvdB38BhdCB0Ow_:bgucvaz) ([raw file](https://github.com/RobotLocomotion/drake/blob/b50b072e48225468c79eb03706dc17b239668ef6/common/trajectories/trajectory.cc#L37)):*
> ```cpp
>   if (cols() == 1) {
>     MatrixX<T> values(rows(), t.size());
>     for (int i = 0; i < static_cast<int>(t.size()); i++) {
> ```

nit, preincrement here and throughout the PR



_Suggestion:_
```cpp
++i
```

**Review by jwnimmer-tri — COMMENTED** [review]
Yes +(release notes: fix) -(release notes: none) this is a new API so we should mention it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-:-NVgE-4755a58O9cGboN:bqdobkg)* status: 3 unresolved discussions

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19422)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

___
*[`common/trajectories/trajectory.h` line 56 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-NVfW71-CksFjW0102SW:-NW27U6LC8gaur6xTvNZ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b50b072e48225468c79eb03706dc17b239668ef6/common/trajectories/trajectory.h#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Why is this overload limited to double-valued times, while the other one allows for autodiff times (etc)?
</blockquote></details>

Done.
___
*[`common/trajectories/trajectory.cc` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-NVfWFCS7sv84T7z7Vix:-NW27Uuj5YLXjwHlQGAd:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b50b072e48225468c79eb03706dc17b239668ef6/common/trajectories/trajectory.cc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW If the other overload accepts `<T>` instead of `double`, then this function should switch to calling the other one using an `Eigen::Map` to avoid the duplication.
</blockquote></details>

Done.
___
*[`common/trajectories/trajectory.cc` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19422#-NVfcpvdB38BhdCB0OwZ:-NW27_6DEALSTcBZvknX:b3iievr) ([raw file](https://github.com/RobotLocomotion/drake/blob/b50b072e48225468c79eb03706dc17b239668ef6/common/trajectories/trajectory.cc#L37)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, preincrement here and throughout the PR
</blockquote></details>

Done.  (old habits die hard)

**Pull request merged**
