### PR TITLE
Add PolynomialBasisElement class, and an implementation of ChebyshevBasisElement

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in #13602 , we want to support richer set of polynomial basis. In this PR, I introduce the base class `PolynomialBasis`, and the derived class `ChebyshevBasis`. In the future I will add `MonomialBasis` and probably other basis like Legendre.

I still need to add more functions to `ChebyshevBasis`, including `Differentiation`, `operator<<`, hash function, etc. But this PR is already large (>600 LOC), so I will add these functions in a future PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13796)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I've only just started to look at this PR train now.

The `//common:symbolic` library is included by most of the code in Drake -- most things want the `symbolic::Expression` scalar type, even if only indirectly.  However, the proportion that will _also_ want these supplemental classes seems much lower.  It seems like there is false coupling.

The reason that Expression, Formula, Variable, etc. are all in the same `cc_library` is that they are intimately related -- once you have Expression, to define comparison operators you need Formula as part of the essential algebra.  There is a dependency cycle between these core objects (as evidenced by the forward declarations in their header files).

However, the same cycle reasoning does not apply to `ChebyshevPolynomial`, the new basis classes, etc.  I think they could be a distinct physical dependency layer that sits above the basic types, so that users only pay for them in compilation and linking cost when they actually need them.  In short, a new `cc_library` target (or targets) to separate them out of `//common:symbolic`.

Perhaps even the basic symbolic_polynomial + symbolic_monomial classes should be split into their own library, distinct from the scalar, for the same reasons.

Also of note, the use of `namespace symbolic` for files not in a directory named `symbolic` is contrary to GSG.  We have grandfathered in the `Expression` type & files etc. but we should not really be extending the pattern.  We should actually be moving `symbolic_expression.h` into `common/symbolic/expression.h` to undo the legacy, eventually.

Also of note, the `BsplineBasis` lives in `//math/...`.  Perhaps that's a good place for some of these classes as well?  The `//common` folder is pretty full already.  Though perhaps a `symbolic` subdirectory would also solve that.

\CC @soonho-tri to weigh in and help guide this architecture.

**Comment by soonho-tri** [comment]
> We have grandfathered in the Expression type & files etc. but we should not really be extending the pattern. We should actually be moving symbolic_expression.h into common/symbolic/expression.h to undo the legacy, eventually.

I'll open a PR for this task.

We can provide multiple targets under `common/symbolic`. I think we can provide `common` which includes `symbolic::Expression` and its dependencies. @jwnimmer-tri , what do you think?

**Comment by jwnimmer-tri** [comment]
I think `#include "drake/common/symbolic.h"` and `deps = ["@drake//common:symbolic"]` are pervasive.  It would be nice to leave those alone without any deprecation warnings, at least for now while we iterate on the newer spellings across several PRs.

As for the `cc_library` names, before voting I'd have to know the contents of the thing we're naming.  It's unclear to me so far exactly which files are in the fundamental subset vs add-ons.

**Comment by TobiaMarcucci** [comment]
As said in #13803, I think that both `PolynomialBasisElement` and `PolynomialBasisFunction` are valid choices.

**Pull request merged**
