### PR TITLE
Update nightly release URL

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7736)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7736#-:-L2_kzrgAMyESl7jE-5J:b-e6xkj)*

**Comment by soonho-tri** [comment]
+@soonho-tri 
platform :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7736#-:-L2_l11OBDgHAyVPodyL:bexm2qz)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7736#-:-L2_o3z6iQur0WXNz_PY:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
`linux-xenial-gcc-bazel-experimental` and `linux-xenial-gcc-cmake-experimental-matlab` passed but the GitHub API was down when they completed.

**Comment by EricCousineau-TRI** [comment]
:(

@jwnimmer-tri Would you be OK with a force-merge here?

**Comment by jwnimmer-tri** [comment]
Wilco.  Confirmed docs-only PR that already passed linux-xenial-clang-bazel-experimental-debug .

**Comment by RussTedrake** [comment]
why did you switch the urls from drake-packages.csail to the s3 link?

**Pull request merged**
