### PR TITLE
Move core/Function.h to solvers/Function.h and put into solvers::detail namespace

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Move Function.h and function_test.cc to solvers.
- Update build for new home of solvers/Function.h
- Delete InputOutputRelation -- dead code.
- Delete function_test -- only testing dead code.
- Move FunctionTraits into drake::solvers::detail namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3004)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@ggould-tri for feature review before anything else.
(Not sure yet if this is a good idea.)

**Comment by ggould-tri** [comment]
This change seems obviously correct and sensible to me: `Function` is used only to describe solver inputs.  :lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3004#-:-KO50ukJBrLJG4G5dw2s:-1551093452)*

**Comment by jwnimmer-tri** [comment]
@sherm1 for today's platform review, please.

**Comment by jwnimmer-tri** [comment]
(Using DNM tag solely to await second review.)

**Comment by sherm1** [comment]
Platform: :lgtm:. A couple of BTWs.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/Function.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3004#-KO6EhqwLAnCgZuT7w1_:-KO6EhqwLAnCgZuT7w1a:-1676104829) ([raw file](https://github.com/robotlocomotion/drake/blob/c68883c67f205c87afe7f79a0adc782083b98b98/drake/solvers/Function.h#L14)):*
> ```objc
> using VecIn = Eigen::Ref<Eigen::Matrix<ScalarType, Eigen::Dynamic, 1> const>;
> template <typename ScalarType>
> using VecOut = Eigen::Matrix<ScalarType, Eigen::Dynamic, 1>;
> ```

BTW, could use `VectorX<ScalarType>` here and avoid some ugliness.

---

*[drake/solvers/Function.h, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3004#-KO6F6PANRhNgODfHavh:-KO6F6PANRhNgODfHavi:1722944422) ([raw file](https://github.com/robotlocomotion/drake/blob/c68883c67f205c87afe7f79a0adc782083b98b98/drake/solvers/Function.h#L17)):*
> ```objc
> 
> /** FunctionTraits
>  * @brief Define interface to a function of the form y = f(x).
> ```

BTW,  doxygen won't format correctly with that spurious `FunctionTraits` ahead of the brief. Should be just `/** Define interface ... = f(x). */` Not marking as a defect because I know you just moved this code here intact.

---

*[drake/solvers/Optimization.h, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3004#-KO6ENkXV4ebtofYYKfI:-KO6ENkXV4ebtofYYKfJ:-980463567) ([raw file](https://github.com/robotlocomotion/drake/blob/c68883c67f205c87afe7f79a0adc782083b98b98/drake/solvers/Optimization.h#L5)):*
> ```objc
> #include <algorithm>
> #include <initializer_list>
> #include <iostream>
> ```

BTW, did you mean to add this include? I didn't see anything new that required it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3004#-:-KO6FjOawW6uXYLfdFHb:-874416740)*

**Comment by jwnimmer-tri** [comment]
*[drake/solvers/Optimization.h, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3004#-KO6ENkXV4ebtofYYKfI:-KO6Hz3e3dn_7p2_SjMq:-872774016) ([raw file](https://github.com/robotlocomotion/drake/blob/c68883c67f205c87afe7f79a0adc782083b98b98/drake/solvers/Optimization.h#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, did you mean to add this include? I didn't see anything new that required it.
</details>
Yup.  There are some `std::cout`s buried down below, that were relying on `Function.h` bringing in `<iostream`>.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3004)*

**Pull request merged**
