### PR TITLE
doc: Add release notes v0.17.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See a [rendered preview](https://github.com/jwnimmer-tri/drake/blob/release_notes-v0.17.0/doc/release_notes/v0.17.0.rst).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13020)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake in case you'd like to wordsmith any of the announcements or trajectory-related notes.

**Comment by jwnimmer-tri** [comment]
Well for one, because I wasn't reading the playbook (oops), and for two I don't think past tense is tractable when approximately 100% of the commit messages are already imperative.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , could you include https://github.com/RobotLocomotion/drake/pull/13076 in this release? It addresses a problem introduced by https://github.com/RobotLocomotion/drake/pull/12973.

**Comment by jwnimmer-tri** [comment]
> Could you include #13076 in this release?

Done.

The plan is to release on Monday subject to builds this weekend being clean.

**Comment by jwnimmer-tri** [comment]
The only ongoing nightly builds are two coverage (which we ignore), and two macOS (each of which has a catalina/mojave sibling that has already passed, so are highly likely to also pass).  I'm going to pull the trigger on release publication now.

**Pull request merged**
