### PR TITLE
Add python binding for AffineSubspace::OrthogonalComplementBasis.

### PR DESCRIPTION
**Pull request by cohnt**
I added this method in #19975, but realized today I hadn't made a python binding for it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20341)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@hongkai-dai for feature review?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20341#-:-NgWRu2fDlZVzzB0uWU2:bl5ccwu)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@sammy-tri for platform review please, thanks!

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20341#-:-NgWXPEF6jo6gPqD4gtW:bptxe99)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @cohnt)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20341#-NgWXJ5H-Rmzs95jrYzE:-NgWXJ5H-Rmzs95jrYzF:bg76wkb) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e6f6da69e16f904f671ba58fb5638e5d0b9d197/bindings/pydrake/geometry/test/optimization_test.py#L93)):*
> ```Python
>         self.assertEqual(dut.AffineDimension(), 2)
>         complement_basis = dut.OrthogonalComplementBasis()
>         self.assertEqual(complement_basis.shape[0], 3)
> ```

BTW, you coud do `self.assertEqual(complement_basis.shape, (3, 1))`

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20341)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20341#-NgWXJ5H-Rmzs95jrYzE:-NgWf2ma1X7zabK8JGms:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5e6f6da69e16f904f671ba58fb5638e5d0b9d197/bindings/pydrake/geometry/test/optimization_test.py#L93)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, you coud do `self.assertEqual(complement_basis.shape, (3, 1))`
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20341#-:-NgZrvJr8d4TbexH_6ch:bnfp4nl)* status: missing label for release notes (waiting on @cohnt)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20341#-:-NgZs0bC7nWoYwmP3S97:b-l8xbmn)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai

**Pull request merged**
