### PR TITLE
URDF text cleanups

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Add standardized namespace definition for drake:
* Delete a variety of no-op text

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21067)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
This is progress toward eventually landing #20824. Kill dead model code found by running schema checks. On the theory that this is all dead code or (not-yet-important) namespace adjustment, +(release notes: none) 

Still working on a review assignment plan.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-:-NrlbYTz3PjzSPyQM-3f:b-tsarcq)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@RussTedrake for feature review of dead-code removal in 
* `bindings/pydrake/geometry/test/optimization_test.py`

Everything else, I'll add the single-review tag once Russ' file is approved, and pass it to the on-duty platform reviewer.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-:-NrlsxOa78jLuPCH4qW7:b-tqnwip)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
I looked over the entire PR and am ok signing off on both reviews.
+@RussTedrake for both reviews.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-:-NruBomSE6HT80hOI8V9:b2n8bcf)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`examples/quadrotor/office.urdf` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-NruApdr71ZtzmynsOjc:-NruApdr71ZtzmynsOjd:bckcsio) ([raw file](https://github.com/RobotLocomotion/drake/blob/1dd7381234b12e1ee580ac3014417d8dea489485/examples/quadrotor/office.urdf#L33)):*
> ```XML
>         <box size="10 .1 2."/>
>       </geometry>
>       <material name="Brown"/>
> ```

btw -- i've confirmed that all material removals are in the collision geos only. that might be worth mentioning explicitly in the commit message?  (it wasn't immediately obvious from the reviewable diff).  
___
*[`manipulation/models/ur3e/ur3e.urdf.xacro` line 551 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-NruBWZp87BpdXAfBHr-:-NruBWZp87BpdXAfBHr0:byp3t48) ([raw file](https://github.com/RobotLocomotion/drake/blob/1dd7381234b12e1ee580ac3014417d8dea489485/manipulation/models/ur3e/ur3e.urdf.xacro#L551)):*
> ```XML
> 
>     <link name="${prefix}wrist_2_link">
>       <origin rpy="${pi / 2} 0 0" xyz="0.0 0.0 0.0"/>
> ```

btw -- wow.  was this one really not doing anything?
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 852 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-NruBi382Lk70Co2oTmg:-NruBi382Lk70Co2oTmh:b32bz60) ([raw file](https://github.com/RobotLocomotion/drake/blob/1dd7381234b12e1ee580ac3014417d8dea489485/bindings/pydrake/geometry/test/optimization_test.py#L852)):*
> ```Python
>                      <geometry>
>                           <sphere radius="0.2"/>
>                      </geometry>
> ```

fyi @AlexandreAmice .  i guess those tags were not actually doing anything.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-:-NruByfA6dWCFO7wOdKb:bnfp4nl)* status: 2 unresolved discussions

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21067)* status: 1 unresolved discussion

___
*[`examples/quadrotor/office.urdf` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-NruApdr71ZtzmynsOjc:-NrumGe_-WJMEqyjMB6E:b-tpvg2p) ([raw file](https://github.com/RobotLocomotion/drake/blob/1dd7381234b12e1ee580ac3014417d8dea489485/examples/quadrotor/office.urdf#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i've confirmed that all material removals are in the collision geos only. that might be worth mentioning explicitly in the commit message?  (it wasn't immediately obvious from the reviewable diff).
</blockquote></details>

I can add something.
___
*[`manipulation/models/ur3e/ur3e.urdf.xacro` line 551 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-NruBWZp87BpdXAfBHr-:-NrukmHH7Tm6yY11cIw-:b-awtc7t) ([raw file](https://github.com/RobotLocomotion/drake/blob/1dd7381234b12e1ee580ac3014417d8dea489485/manipulation/models/ur3e/ur3e.urdf.xacro#L551)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- wow.  was this one really not doing anything?
</blockquote></details>

Yeah, it turns out that link/origin is not a thing. Of course link-attached things have origins -- geometries, inertia tensors -- but links themselves, no. I'm guessing it was maybe a thing at some point about a decade ago. I found some archaeology in the ROS repos that blamed @EricCousineau-TRI . But, in contemporary usage, it's dead code.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 852 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21067#-NruBi382Lk70Co2oTmg:-NrulfqQ1laiSfzf4lNy:b-ab67xf) ([raw file](https://github.com/RobotLocomotion/drake/blob/1dd7381234b12e1ee580ac3014417d8dea489485/bindings/pydrake/geometry/test/optimization_test.py#L852)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

fyi @AlexandreAmice .  i guess those tags were not actually doing anything.
</blockquote></details>

Geometries need to be wrapped in a `visual` or a `collision`. I couldn't tell from casually reading the test if these were actually needed somewhere.

**Pull request merged**
