### PR TITLE
[pydrake] Fold pydrake.examples into a single module

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The shorter import path and consolidated API docs are more typical of Python modules than deeply-nested paths, and so are easier for users.

The single shared library also reduces the zipped size of our whl releases by approximately 3 MiB by reducing the zipped size of the `pydrake.examples` directory by 74%.

Add shim modules so that the old, longer module names continue to work. Leave the unit tests for `pydrake.examples` unchanged (using the old names) to confirm that the shim modules are operating correctly.

Update tutorials and example program to prefer the new, shorter names. Update tests for other (non-examples) modules to prefer the new, shorter names.

Also remove `examples.multibody` main programs from pydrake API reference docs.

Also remove coverage reporting for the examples folder. We do not plan to bind all example libraries, so the statistics are a waste of resources.

Towards #11802.

Relates to #15631 and #15628.

See #17453 for the similar treatment of `pydrake.solvers`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17454)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI do you have time to review this week?  As the subject matter expert, I'd like your blessing on this general idea before I start carrying the same pattern forward across many other modules.

**Review by EricCousineau-TRI — COMMENTED** [review]
Yup! :lgtm:, straightforward given summary, linked issues, and changes, thanks!

> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17454#-:-N6iS7cg5IOanly5zk46:b-yjjfit)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17454)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`bindings/pydrake/examples/examples_py.cc` line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17454#-N6ifC-vCkV-W4mCqNrQ:-N6j1umH9-N46idqVVAR:b-ue6qkt) ([raw file](https://github.com/robotlocomotion/drake/blob/2894dacb52432e69244ff50a1f5c5c3be05a0a01/bindings/pydrake/examples/examples_py.cc#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Suggested word juggling due to English language crap.

> Provides bindings of both existing C++...

("both bindings" implies there are two bindings. "bindings of both" imply there are an indeterminate number of bindings of two categories.)
</blockquote></details>

Indeed, I didn't even read it since it was just copied from the prior implementation unchanged.  But it's definitely confusing as it was written!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17454)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Huh.  Jenkins never ran.

@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Huh.  The status values are not updating.

It **did** actually run previously, just never updated to GH.  I just went and manually found all of the pre-merge test results, and they all passed, so I'll force this in now.

**Pull request merged**
