### PR TITLE
Add drake_cc_package_library and library_lint

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a re-application of #8582, whose overview description was:
> This should be substantially easier to maintain correct lists, and document for authors the purpose of the package-level library without repeating identical comments everywhere.
> 
> This is also a step along the way to #6464, where libdrake will depend on just these package-summary libraries, instead of listing out each individual component.

Now that #8667 has merged, we can rely on `genquery()` to work even on macOS, and thus the original commits can go back in without any additional edits.

~New in this PR is the first commit, that adds some stubs for macOS support.~ _Edit: Submitted separately as #8667.  This PR is now a plain revert-of-revert._

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8664)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for sole review.  I think the only review goal here is to reaffirm that this indeed is only a re-application of two commits that had been previously reviewed and merged, but then reverted.

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 41 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8664#-:-LAtRTjE5qaVaxaqD9zM:bnfp4nl)*

**Pull request merged**
