### PR TITLE
Upgrade to Xcode 12 on Catalina

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Relates to #14085

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14142)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jamiesnape for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14142#-:-MIPFL633dHljWVcfqPE:bdx3wf2)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14142#-:-MIPVN2H7UQaAE5HLLp2:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

___
*[doc/developers.rst, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14142#-MIPUqXL7BJK6hAQtOki:-MIPUqXM75dB9RSF-mqH:bi9cmi2) ([raw file](https://github.com/robotlocomotion/drake/blob/ae0623875f556a65e5b6915224373a31a9e305f9/doc/developers.rst#L91)):*
> ```reStructuredText
> |                                  |       |       | | (Xcode 11.3)      | | (HotSpot JVM)   |        |
> +----------------------------------+       |       +---------------------+                   |        |
> | macOS Catalina (10.15)           |       |       | | Apple LLVM 11.0.3 |                   |        |
> ```

12.0.0

**Review by BetsyMcPhail — COMMENTED** [review]
+@sherm1 for platform review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14142#-:-MIPdBsn9E99JP5SkCvA:bu0bkqk)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @BetsyMcPhail, @jamiesnape, and @sherm1)

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14142)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14142#-:-MIQXacA9INcRfvhE527:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jamiesnape,sherm1(platform)

**Pull request merged**
