### PR TITLE
Port some primitives to SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
FYI The Doxygen at http://drake.mit.edu/doxygen_cxx/group__system__scalar__conversion.html helps explain what's going on here.

Details:
- Port Gain to SystemScalarConverter
- Port PassThrough to SystemScalarConverter
- Port Demultiplexer to SystemScalarConverter
- Port FirstOrderLowPassFilter to SystemScalarConverter

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7047)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@jadecastro for feature review

**Comment by jadecastro** [comment]
:lgtm: 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7047#-:-KuRCyjFl98-N0TG69AK:bg7igkv)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per rotation, please.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7047#-:-KuUUxDIqynsWDExgikf:bnfp4nl)*

**Pull request merged**
