### PR TITLE
Make the Bazel build fail fast if ccache is on the path.

### LINKED ISSUE #4464: Deal with ccache in PATH for bazel builds
When a user has the magic `ccache` directory in their `$PATH`, bazel shows weird error messages that don't indicate the root cause of the problem and then fails.

Given that `ccache` is essentially required to have a good experience when using the CMake backends (ninja, make, etc.), and we can't (or at least shouldn't) have CMake inject ccache onto the path for us, we should do our best to accommodate developers who need to use both build systems from time to time.

If possible, we should either fail-fast in the case of `.../lib/ccache` on the path, or even better we should automatically remove the entry or otherwise fix the compiler variable(s) so that bazel is happy.

Part of #3129.

### PR DESCRIPTION
**Pull request by david-german-tri**
@ggould-tri for feature review, @jwnimmer-tri for platform review

Fixes #4464 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5130)

### CODE REVIEW

**Comment by david-german-tri** [comment]
+@soonho-tri for platform shadow

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-KcdhevDM-T45dyb0jlq:bd24akw)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-KcdiYkuA4SzZch2qx3x:-KcdiYkuA4SzZch2qx3y:bdjb7qf) (no related file):*
I didn't test locally, @ggould-tri or @soonho-tri can you be sure to do so and post back a confirmation here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdjyzy47jtiKBjBhjS:-Kcdjyzy47jtiKBjBhjT:bv9jpre) (no related file):*
@david-german-tri , you're right. I just checked that if you install `ccache` via homebrew, you can find the scripts under `/usr/local/opt/ccache/libexec`. I just didn't know that there are these scripts shipped with `ccache`.

---

*[tools/BUILD, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdi6f0KhsAR7YZCPEN:-Kcdi6f0KhsAR7YZCPEO:b-przl34) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/BUILD#L64)):*
> ```Python
> # This genrule will fail loudly if ccache is on the path.
> genrule(
>     name = "ccache_is_bad",
> ```

:100:  for the choice of rule name!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdjyzy47jtiKBjBhjS:-KcdlE7HHz6j8NYRZiM_:bt0nbip) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@david-german-tri , you're right. I just checked that if you install `ccache` via homebrew, you can find the scripts under `/usr/local/opt/ccache/libexec`. I just didn't know that there are these scripts shipped with `ccache`.
</blockquote></details>

Added additional documentation per f2f.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/BUILD, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdi41XL9mKBZM9i8op:-Kcdi41XL9mKBZM9i8oq:b66yqu) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/BUILD#L74)):*
> ```Python
> filegroup(
>     name = "empty",
>     srcs = ["ccache.txt"],
> ```

This is no longer "empty".  (I think a different filegroup would be okay -- or do you need to bring it into the dependency chain of externals like Eigen, in which case document that?)

---

*[tools/complain_about_ccache.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdh_IVMKxIXJIvpkiv:-Kcdh_IVMKxIXJIvpkiw:banh1v9) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/complain_about_ccache.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> echo $PATH | grep ccache 2> /dev/null
> ```

This could have false positives.  I believe a tighter pattern would insist on a preceding `/` and trailing either `/` or `:` or end-of-string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by ggould-tri** [comment]
I'm not going to get around to testing this today.  Feel free to dismiss me from the review if you want to land it sooner.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-KcdnEQhA9of8Rxu24bZ:b-vmxyua)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/complain_about_ccache.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdh_IVMKxIXJIvpkiv:-KcdnU8DrvctQm26XeRy:btd51a6) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/complain_about_ccache.sh#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This could have false positives.  I believe a tighter pattern would insist on a preceding `/` and trailing either `/` or `:` or end-of-string.
</blockquote></details>

I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-KcdoIlKZ_ZLqABv3OMn:-KcdoIlKZ_ZLqABv3OMo:b-ii4efs) (no related file):*
This probably needs an OSX opt-in CI test as well, once its finalized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by david-german-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/BUILD, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdi41XL9mKBZM9i8op:-KcdooCPpK0EmDyHnBr7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/BUILD#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is no longer "empty".  (I think a different filegroup would be okay -- or do you need to bring it into the dependency chain of externals like Eigen, in which case document that?)
</blockquote></details>

Done.

---

*[tools/complain_about_ccache.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdh_IVMKxIXJIvpkiv:-Kcdoouu1gVCe6tPA4PL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/complain_about_ccache.sh#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I agree.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by david-german-tri** [comment]
-@ggould-tri

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-KcdoqGSsgNmvJXyIp6c:b-88goz0)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-Kcdpg4NPVD8GuaABsOV:bjwebpu)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-KcdiYkuA4SzZch2qx3x:-Kcdq6csGsDDjnSwWaws:bhsdhsh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I didn't test locally, @ggould-tri or @soonho-tri can you be sure to do so and post back a confirmation here?
</blockquote></details>

I tested it on a mac, and it worked as expected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-KcdqQ0OeYMOAAOVJWwC:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[tools/complain_about_ccache.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdh_IVMKxIXJIvpkiv:-Kcdq5N6Cld0Yr_Pou-z:b-ec8efe) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/complain_about_ccache.sh#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this will no longer catch when ccache is the last thing on the path, which is a common case?  I suggest `egrep` with a disjunction between the current expression, and one that ends a line, so approximately `/ccache([:/]|$)` or maybe `(/ccache[/:]|/ccache$)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-Kcdqflq-h4_626bALi_:buvdl6p)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/complain_about_ccache.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdh_IVMKxIXJIvpkiv:-KcduC5-Gv7eWvffIfx3:bqkkv5a) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/complain_about_ccache.sh#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this will no longer catch when ccache is the last thing on the path, which is a common case?  I suggest `egrep` with a disjunction between the current expression, and one that ends a line, so approximately `/ccache([:/]|$)` or maybe `(/ccache[/:]|/ccache$)`.
</blockquote></details>

`egrep` + `/ccache([:/]|$)` works on OSX.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/complain_about_ccache.sh, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-Kcdh_IVMKxIXJIvpkiv:-KcdvZ7dgN3g-nWD4dzb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03679c198b20e8e8c7547bfa57319279bcd5c49f/tools/complain_about_ccache.sh#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`egrep` + `/ccache([:/]|$)` works on OSX.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by david-german-tri** [comment]
> @drake-jenkins-bot mac-clang-bazel-experimental please

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-KcdviZl8xdOCg1RNvbW:b-o8hpuy)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130#-:-KcdvkQf1eDR5Wqp8MbW:b-mdoeiw)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5130)*

**Pull request merged**
