### PR TITLE
Mathematical program additional bindings

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-:-O34GEM7E9T-nPWxCPkD:bggbbet)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754)* status: 6 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc` line 884 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O354sy6A36_vh7MBDdX:-O354sy6A36_vh7MBDdY:b-osmle8) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc#L884)):*
> ```cpp
>           },
>           py::arg("binding"),
>           doc.MathematicalProgram.AddConstraint.doc_1args_constEigenDenseBase)
> ```

This should be `doc.MathematicalProgram.AddConstraint.doc_1args_binding`. You can find the information in `bazel-bin/bindings/pydrake/documentation_pybind.h`
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 108 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355H7XCJK2F-Kjleix:-O355H7XCJK2F-Kjleiy:b-1hrndu) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L108)):*
> ```Python
>         self.assertTrue(cost == cost)
>         self.assertTrue(cost == cost2)
>         self.assertEqual(cost, cost2)
> ```

Add a test where two bindings are not equal?
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 116 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355LK--I-2DASCXijm:-O355LK--I-2DASCXijn:b-yeokql) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L116)):*
> ```Python
>         cost = mp.ExpressionCost(e=e)
>         cost2 = cost
>         self.assertEqual(hash(cost), hash(cost2))
> ```

Add a test where the hash are not equal?
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 268 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355S82DEwtxmehrKMK:-O355S82DEwtxmehrKML:bs4q9op) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L268)):*
> ```Python
>         self.assertTrue(constraint == constraint)
>         self.assertTrue(constraint == constraint2)
>         self.assertEqual(constraint, constraint2)
> ```

Ditto.
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 278 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355TK26IyvX2Xghy09:-O355TK26IyvX2Xghy0A:b-89a4l7) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L278)):*
> ```Python
>                                              ub=np.array([2.0]))
>         constraint2 = constraint
>         self.assertEqual(hash(constraint), hash(constraint2))
> ```

Ditto
___
*[`bindings/pydrake/solvers/test/program_attribute_test.py` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355htM7DGUn7XIHR1d:-O355htM7DGUn7XIHR1e:bb1sacr) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/program_attribute_test.py#L25)):*
> ```Python
>                          ProgramAttribute.kBinaryVariable,
>                          ProgramAttribute.kCallback,
>                          ]
> ```

This test doesn't have any self.assert(...), do you just want to list all the enums to make sure they exist? If so, then please document the purpose of this test. Same for the `test_program_attribute_enum` test below.

**Review by AlexandreAmice — COMMENTED** [review]
I realized I meant to test `__eq__` and `__hash__` for `Binding<Constraint>` not `Constraint`. So the tests have been updated to reflect this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-:-O39CUbq2a8BW_ZPBUpW:b-n0ob60)* status: 6 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc` line 884 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O354sy6A36_vh7MBDdX:-O391Ly-8dXFw0vXD-BA:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc#L884)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This should be `doc.MathematicalProgram.AddConstraint.doc_1args_binding`. You can find the information in `bazel-bin/bindings/pydrake/documentation_pybind.h`
</blockquote></details>

Done.
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 108 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355H7XCJK2F-Kjleix:-O392WA4DBx719qbYO2-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L108)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add a test where two bindings are not equal?
</blockquote></details>

Done.
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 116 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355LK--I-2DASCXijm:-O392XfOBt8sh5G2Xc6c:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L116)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add a test where the hash are not equal?
</blockquote></details>

Done.
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 268 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355S82DEwtxmehrKMK:-O3946BU88b7JtPcfqmC:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L268)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 278 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355TK26IyvX2Xghy09:-O3946lP-BPvozgJB1Hs:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/evaluators_test.py#L278)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/solvers/test/program_attribute_test.py` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O355htM7DGUn7XIHR1d:-O3D5obG8sz94pswfULo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d489a7cec785ee4d7d57bab4af2e4d4ef742884/bindings/pydrake/solvers/test/program_attribute_test.py#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This test doesn't have any self.assert(...), do you just want to list all the enums to make sure they exist? If so, then please document the purpose of this test. Same for the `test_program_attribute_enum` test below.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: fix) :lgtm: platform

> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-:-O3DfJzl7ITo3aW52ZHG:borzf47)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/solvers/test/mathematicalprogram_test.py` line 1122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-O3Dk2nZE4qs7Om_rNOl:-O3Dk2nZE4qs7Om_rNOm:b-anuinh) ([raw file](https://github.com/RobotLocomotion/drake/blob/29b3eebe990a052026b2427541999dffb35fed7a/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1122)):*
> ```Python
>         prog.AddConstraint(x[0] <= 2)
>         # This ensures that constraint is off time Binding<Constraint> and not
>         # a more specific type.
> ```

nit, typo?



_Suggestion:_
```Python
        # This ensures that constraint is of type Binding<Constraint> and not
        # a more specific type.
```

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754#-:-O3E3Nmi2lfu34ZLqCwz:bm9o57a)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21754)* status: 1 unresolved discussion

**Pull request merged**
