### PR TITLE
py geometry: Expose RenderEngine API and trampoline for inheritance

### LINKED ISSUE #13834: py geometry: Should permit RenderEngine to be extended in Python
This permits prototyping towards #11748 

Per convo with @thduynguyen 

FYI @RussTedrake @SeanCurtis-TRI

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #13834

FYI @thduynguyen and @SeanCurtis-TRI Review will be coming y'all's way once this is ready ;)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@thduynguyen Handing off to you for completion. Feel free to push here and/or start a separate PR.

**Comment by EricCousineau-TRI** [comment]
See PR: https://github.com/EricCousineau-TRI/drake/pull/13

**Comment by EricCousineau-TRI** [comment]
Tagging @takuya-ikeda-tri

**Comment by EricCousineau-TRI** [comment]
@thduynguyen Does this happen to have your latest changes? (I just merged your PR in)

**Comment by EricCousineau-TRI** [comment]
From Duy:
https://github.com/thduynguyen/drake/commit/fbe17ba2d6a2c287a88f5e654d34968c61a7561c

**Review by EricCousineau-TRI — COMMENTED** [review]
+@thduynguyen for feature review, please
+@seancurtis-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835#-:-MK71kyMClGti5mnARiD:b47itzj)* status: LGTM missing from assignees SeanCurtis-TRI(platform),thduynguyen (waiting on @SeanCurtis-TRI and @thduynguyen)

**Review by thduynguyen — COMMENTED** [review]
:lgtm: with some nits. Thanks!

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835#-:-MKBawPmD5nRQzXP0txx:b-5uhfw5)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI, @SeanCurtis-TRI, and @thduynguyen)

___
*[bindings/pydrake/test/geometry_test.py, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBYkXREk91WZKTsSdb:-MKBYkXREk91WZKTsSdc:b-e6bvs8) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L18)):*
> ```Python
> from pydrake.common.value import AbstractValue, Value
> from pydrake.lcm import DrakeLcm, Subscriber
> from pydrake.math import RigidTransform, RigidTransform_
> ```

BTW, what's the difference between `RigidTransform` and `RigidTransform_`? There are many re-definitions of `RigidTransform = RigidTransform_[float]` below in this file and that causes confusion. Can you either remove this or change the aliases to `RigidTransformf`?
___
*[bindings/pydrake/test/geometry_test.py, line 636 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBXoYB6pi2C-zVMv0g:-MKBXoYC7LAWNFKM9y_e:b-h6s7he) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L636)):*
> ```Python
>         Value[mut.render.RenderLabel]
> 
>     def test_render_camera_api(self):
> ```

BTW, are these 2 lines needed?
___
*[bindings/pydrake/test/geometry_test.py, line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKB_vLO8lD8NLhmbk7l:-MKB_vLO8lD8NLhmbk7m:bet0j40) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L643)):*
> ```Python
>             """Mirror of C++ DummyRenderEngine."""
> 
>             latest_intance = None
> ```

nit,  variable name typo: `latest_instance`
___
*[bindings/pydrake/test/geometry_test.py, line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBa7Da3_7M-dsoTo8Q:-MKBa7Da3_7M-dsoTo8R:b-wyyavd) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L643)):*
> ```Python
>             """Mirror of C++ DummyRenderEngine."""
> 
>             latest_intance = None
> ```

nit, can you add a comment here stating this's only needed for testing (and why)?
___
*[bindings/pydrake/test/geometry_test.py, line 682 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBZYXYAK6KQqJ94jm5:-MKBZYXYAK6KQqJ94jm6:biaiiqs) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L682)):*
> ```Python
>             def ImplementGeometry(self, shape, user_data):
>                 DummyRenderEngine.latest_instance = self
>                 pass
> ```

nit, redundant `pass`.
___
*[bindings/pydrake/test/geometry_test.py, line 703 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBaftt68h6rNvFnbP5:-MKBaftt68h6rNvFnbP6:b1gphni) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L703)):*
> ```Python
> 
>             def DoClone(self):
>                 DummyRenderEngine.latest_instance = self
> ```

nit, shouldn't `latest_instance = new` in this case?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @thduynguyen)

___
*[bindings/pydrake/test/geometry_test.py, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBYkXREk91WZKTsSdb:-MKBfYGWCNwsXG-mzXcP:b796eoo) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L18)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW, what's the difference between `RigidTransform` and `RigidTransform_`? There are many re-definitions of `RigidTransform = RigidTransform_[float]` below in this file and that causes confusion. Can you either remove this or change the aliases to `RigidTransformf`?
</blockquote></details>

OK I'd like to keep it as-is for now. See here:
https://drake.mit.edu/python_bindings.html#differences-with-c-api

(Could consider as a separate PR focused on that, but I wanna punt for now ;)
___
*[bindings/pydrake/test/geometry_test.py, line 636 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBXoYB6pi2C-zVMv0g:-MKBggc50JSQhqWcBmIC:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L636)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW, are these 2 lines needed?
</blockquote></details>

Done. Oops!
___
*[bindings/pydrake/test/geometry_test.py, line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKB_vLO8lD8NLhmbk7l:-MKBgi2Z7doPQWy-Cflr:bt5r2cp) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L643)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

nit,  variable name typo: `latest_instance`
</blockquote></details>

Done. Oops as well!
___
*[bindings/pydrake/test/geometry_test.py, line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBa7Da3_7M-dsoTo8Q:-MKBgj8G0b3vhLq5hzDB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L643)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

nit, can you add a comment here stating this's only needed for testing (and why)?
</blockquote></details>

Done.
___
*[bindings/pydrake/test/geometry_test.py, line 682 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBZYXYAK6KQqJ94jm5:-MKBgjo3AJ-94qchELQX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L682)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

nit, redundant `pass`.
</blockquote></details>

Done.
___
*[bindings/pydrake/test/geometry_test.py, line 703 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKBaftt68h6rNvFnbP5:-MKBgkSpDcOKQjTzMYOs:bd6cqvy) ([raw file](https://github.com/robotlocomotion/drake/blob/d05a866b70d0bb53c7d35fd6938253e355aef09d/bindings/pydrake/test/geometry_test.py#L703)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

nit, shouldn't `latest_instance = new` in this case?
</blockquote></details>

OK Nah, that smells a tad odd. I can explain more if you like.

**Comment by EricCousineau-TRI** [comment]
Removed excess bindings / `using` statements, and made a comment here: https://github.com/RobotLocomotion/drake/issues/13834#issuecomment-713893844

PTAL!

**Comment by EricCousineau-TRI** [comment]
Er... On second though, mayhaps I should keep the pure virtual NVI methods?
Otherwise, they won't appear in Sphinx docs....

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 316 at r3](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKC80YHCh-GrlT75m4s:-MKC80YHCh-GrlT75m4t:b7cga9o) ([raw file](https://github.com/robotlocomotion/drake/blob/88c334b48cdd5b4777e145617e9e5eb856890353/bindings/pydrake/geometry_py.cc#L316)):*
> ```cpp
>                 &Class::default_render_label),
>             cls_doc.default_render_label.doc)
>         .def("GetRenderLabelOrThrow",
> ```

is it worth adding a comment explaining that we're deliberately binding to the trampoline even though https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python says not to?  (I assume it's something to do with moving these functions into the `public` section).

**Review by EricCousineau-TRI — COMMENTED** [review]
Per Slack, will keep the pure virtual NVI methods out for now. Yes, there may be a lack of docs; we can always come back and cherry-pick from `r2` if need be.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835#-:-MKC9pOm4066l5eGeY9F:b-ru1j4z)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[bindings/pydrake/geometry_py.cc, line 316 at r3](https://reviewable.io/reviews/robotlocomotion/drake/13835#-MKC80YHCh-GrlT75m4s:-MKC9wld8jQnBmqZ6m4M:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/88c334b48cdd5b4777e145617e9e5eb856890353/bindings/pydrake/geometry_py.cc#L316)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

is it worth adding a comment explaining that we're deliberately binding to the trampoline even though https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python says not to?  (I assume it's something to do with moving these functions into the `public` section).
</blockquote></details>

Done. Thanks!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13835#-:-MKCA1LoAiy-HBfznILM:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),thduynguyen

**Comment by EricCousineau-TRI** [comment]
Skipping slow build

**Comment by SeanCurtis-TRI** [comment]
@thduynguyen @EricCousineau-TRI 

In looking at the bindings in `PyRenderEngine`, we've bound the API that should be deprecated (the ones that take `CameraProperties` and `DepthCameraProperties`). Life would be easiest if we can simply *kill* those APIs from the bindings. All rendering logic should be in the `DoRender*Image` methods and not in the `Render*Image` methods.

Given it's only been 16 days since the merge, do you think we can get away with this (without deprecation, that is)?

**Comment by EricCousineau-TRI** [comment]
Yeah, I'd be fine with that!

**Pull request merged**
