### PR TITLE
 Introduce refine_mesh tool

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This is dependent (and completely contingent) on #19550, and contains a copy of it. It should not land until that PR is resolved.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FYI @DamrongGuoy @SeanCurtis-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-Ng5U6Sn9jO-GfFxSmWs:b-uqaetk)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
For r3 and r4, I rebased in master and fixed the merge conflict in BUILD.bazel.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NlPPsSS4HM7rJawKPNn:byk80yp)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
As discussed f2f at  the on-site, this formulation of the tool isn't much use unless one builds from source. An alternative or addition would be to  make a tool similar to `//tools:fix_inertia` that could be used from binary installs as well.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NlQ9NvwBjMH4BnJXUwE:bszpk7d)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
The prequel #19550 was merged. I'll resolve the merge conflict, and this PR will look smaller.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NnotCy31e0SKUmhX-3N:b-k72lqd)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
After rebasing on master, this PR shrinks from 5 files down to 2 files now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-Nnou3ygB6z4Uehl0MWD:b1fn32l)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/proximity/BUILD.bazel` line 886 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnowGoT0R48PDHN9MBO:-NnowGoU6fV5cw1whoEc:b1rkyil) ([raw file](https://github.com/RobotLocomotion/drake/blob/86d6b02122be161e441e83a4346414bb315a130e/geometry/proximity/BUILD.bazel#L886)):*
> ```Starlark
> 
> drake_cc_binary(
>     name = "mesh_refiner_manual_test",
> ```

Here's an idea I had, based on some other review feedback elsewhere:
* rename this to just `mesh_refiner`
* move the cc file out of test/, to just geometry/proximity/mesh_refiner.cc
* the build rule here changes a tiny bit, but i don't think the c++ code has to change at all.

Rationale: I don't think the `test/*manual_test` naming pattern is particularly helpful. Plus, we end up with a generated target `mesh_refiner_manual_test_test`, which is at best hilarious, at worst maybe confusing.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/BUILD.bazel` line 886 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnowGoT0R48PDHN9MBO:-Nnq3DSX5Okc2u4xNJtm:b-dk2t9v) ([raw file](https://github.com/RobotLocomotion/drake/blob/86d6b02122be161e441e83a4346414bb315a130e/geometry/proximity/BUILD.bazel#L886)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here's an idea I had, based on some other review feedback elsewhere:
* rename this to just `mesh_refiner`
* move the cc file out of test/, to just geometry/proximity/mesh_refiner.cc
* the build rule here changes a tiny bit, but i don't think the c++ code has to change at all.

Rationale: I don't think the `test/*manual_test` naming pattern is particularly helpful. Plus, we end up with a generated target `mesh_refiner_manual_test_test`, which is at best hilarious, at worst maybe confusing.
</blockquote></details>

Set to Working.  I like the idea. Thanks!

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/BUILD.bazel` line 886 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnowGoT0R48PDHN9MBO:-NntiV9l2k9Kk0Oe8IFk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/86d6b02122be161e441e83a4346414bb315a130e/geometry/proximity/BUILD.bazel#L886)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Set to Working.  I like the idea. Thanks!
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`geometry/proximity/BUILD.bazel` line 886 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NntjpxGDSXy5iAGjQ03:-NntjpxGDSXy5iAGjQ04:bm4axus) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c1a20023ede6dc96546dd8fa134f06d67ac9cc0/geometry/proximity/BUILD.bazel#L886)):*
> ```Starlark
> 
> drake_cc_binary(
>     name = "mesh_refiner",
> ```

minor One last quibble: Since we are building a binary here, they usually have verb names, not noun names. One last rename to `refine_mesh` ?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/BUILD.bazel` line 886 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NntjpxGDSXy5iAGjQ03:-Nntnsk79KKRwN0qZAM3:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c1a20023ede6dc96546dd8fa134f06d67ac9cc0/geometry/proximity/BUILD.bazel#L886)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor One last quibble: Since we are building a binary here, they usually have verb names, not noun names. One last rename to `refine_mesh` ?
</blockquote></details>

Done. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/refine_mesh.cc` line 12 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnuDiEv1lIeIW-niuER:-NnuDiEv1lIeIW-niuES:b-6c49rh) ([raw file](https://github.com/RobotLocomotion/drake/blob/0547afd0fe8df37bc5373669b40446a673793c11/geometry/proximity/refine_mesh.cc#L12)):*
> ```cpp
> 
> DEFINE_bool(scene_graph, true, "include/exclude scene graph");
> DEFINE_bool(strict, false, "enable strict parsing");
> ```

nit remove these

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/refine_mesh.cc` line 12 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnuDiEv1lIeIW-niuER:-NnuSg-J8fbrWDaIvaXN:b-smvxt9) ([raw file](https://github.com/RobotLocomotion/drake/blob/0547afd0fe8df37bc5373669b40446a673793c11/geometry/proximity/refine_mesh.cc#L12)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit remove these
</blockquote></details>

Done. Removed `scene_graph` and `strict` flags. They were there unintentionally.

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not merge) -(status: do not review) 

+@rcory would you be interested in a feature review?  Please let us know if you're too busy.

```
bazel-bin/geometry/proximity/refine_mesh --helpshort
refine_mesh: [INPUT-FILE] [OUTPUT-FILE]

Refine a tetrahedral mesh of a compliant-hydroelastic geometry in
the input VTK file to eliminate problemtic tetrahedra,
internal triangles, and internal edges with all boundary vertices.
They define zero pressure in the interior volume creating a void
space of no hydroelastic contact.

If the input has no problems, no output file is written.

After building this tool from source; for example:
 drake $ bazel build //geometry/proximity:refine_mesh
Run it in your data directory; for example:
 data $ /path/to/drake/bazel-bin/geometry/proximity/refine_mesh input.vtk output.vtk

  No modules matched: use -help
```

CC: @dmcconachie-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NnuWCwn9aNeJIxumKLW:bx407hl)* status: LGTM missing from assignee rcory, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
Reference Slack https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1704996695683919

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NnuXais8pu7AUrdrImc:b9wmw0k)* status: LGTM missing from assignee rcory, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 2 unresolved discussions, LGTM missing from assignee rcory, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/BUILD.bazel` line 890 at r13](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnuZDFX-n8DO78OJs61:-NnuZDFY76lDFan3rcP5:bcver6s) ([raw file](https://github.com/RobotLocomotion/drake/blob/e17a07c7faf1de32b7517a2683bccb8cb99176ba/geometry/proximity/BUILD.bazel#L890)):*
> ```Starlark
>     srcs = ["refine_mesh.cc"],
>     add_test_rule = 1,
>     data = ["//geometry:test_vtk_files"],
> ```

nit These files are test inputs, not dependencies of the actual program itself.



_Suggestion:_
```Starlark
test_rule_data = ["//geometry:test_vtk_files"],
```
___
*[`geometry/proximity/refine_mesh.cc` line 71 at r13](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnuYSwb9oazkYnerdkZ:-NnuYSwb9oazkYnerdk_:b2mu1nx) ([raw file](https://github.com/RobotLocomotion/drake/blob/e17a07c7faf1de32b7517a2683bccb8cb99176ba/geometry/proximity/refine_mesh.cc#L71)):*
> ```cpp
>   if (test_dir != nullptr) {
>     // Redirect the output when run as a bazel test.
>     outfile = std::filesystem::path(test_dir) / outfile;
> ```

It's inappropriate to output to a file other than the one the user asked for explicitly on the command line.

The `add_test_rule` sugar is intended to allow us to add tests under simple conditions.  When the testing needs go beyond what `add_test_rule` can do, it's time to use a different approach -- write the test code in a new file `geometry/proximity/test/refine_mesh_test.py`.  That test code can call `subprocess.run(..., check=True)` to invoke the C++ program with suitable arguments.  If you like, it can also look at the output file, or the console output, check the return code, & etc.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 2 unresolved discussions, LGTM missing from assignee rcory, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by rcory — COMMENTED** [review]
Took it for a test run on [this PR](https://reviewable.shared-services.aws.tri.global/reviews/robotics/anzu/11385#-) and it worked great.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NoJznRBCm-L7m52amPs:bipcwk5)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`geometry/proximity/refine_mesh.cc` line 71 at r13](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NnuYSwb9oazkYnerdkZ:-NoNXpK04QGaIZd0sJdR:b31z1d1) ([raw file](https://github.com/RobotLocomotion/drake/blob/e17a07c7faf1de32b7517a2683bccb8cb99176ba/geometry/proximity/refine_mesh.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's inappropriate to output to a file other than the one the user asked for explicitly on the command line.

The `add_test_rule` sugar is intended to allow us to add tests under simple conditions.  When the testing needs go beyond what `add_test_rule` can do, it's time to use a different approach -- write the test code in a new file `geometry/proximity/test/refine_mesh_test.py`.  That test code can call `subprocess.run(..., check=True)` to invoke the C++ program with suitable arguments.  If you like, it can also look at the output file, or the console output, check the return code, & etc.
</blockquote></details>

@rpoyner-tri said he would help me with this. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +@sherm1 for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NoOCYEm6qhZcVoDyaIl:b-5uis2i)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some comments

> Reviewed 3 of 5 files at r7, 1 of 2 files at r12, 1 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-:-NoOe7b4ARJRcE7XFN0v:b-ev0zvy)* status: 3 unresolved discussions

___
*[`geometry/proximity/refine_mesh.cc` line 20 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOWeiA80HUiIvuEz-A:-NoOWeiA80HUiIvuEz-B:baq92fz) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L20)):*
> ```cpp
>       "\n"
>       "Refine a tetrahedral mesh of a compliant-hydroelastic geometry in\n"
>       "the input VTK file to eliminate problemtic tetrahedra,\n"
> ```

typo: problemtic -> problematic
___
*[`geometry/proximity/refine_mesh.cc` line 25 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOWrMpDeO0YaewjR1N:-NoOWrMpDeO0YaewjR1O:b-50xx9i) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L25)):*
> ```cpp
>       "space of no hydroelastic contact.\n"
>       "\n"
>       "If the input has no problems, no output file is written.\n"
> ```

BTW this surprised me -- I would have expected the output to be a copy of the input file in the "no problems" case so that a user could always work with the output without having to test for existence. No defect, just wanted to confirm this is really the behavior you want.  As written, this feels like it is combining two functions: (1) a filter that takes a sketchy mesh as input and outputs one that has only good tets, and (2) a checker that tells you whether there is anything wrong with a mesh. An alternative design might have a "check only" flag that would report on the sketchiness of a mesh, while the normal behavior would be to take whatever mesh you have and always produce one that is safe to use. Not sure whether that's better. (A Unix-y version could read from stdin and write to stdout)
___
*[`geometry/proximity/refine_mesh.cc` line 69 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOdBtiEi-BeJ7h-MAP:-NoOdBtiEi-BeJ7h-MAQ:blc67ny) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L69)):*
> ```cpp
>   std::filesystem::path outfile(argv[2]);
>   internal::WriteVolumeMeshToVtk(outfile.string(), refined_mesh,
>                                  "Refine tetrahedral mesh by Drake for "
> ```

nit: I'm not sure how to parse this. Is it a noun phrase "Tet mesh as refined by Drake" or a command like "Refine a tet mesh for Drake"? Please clarify.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: 3 unresolved discussions

___
*[`geometry/proximity/refine_mesh.cc` line 25 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOWrMpDeO0YaewjR1N:-NoOezF9AxN4NeCxc_ai:b-3ubnl7) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this surprised me -- I would have expected the output to be a copy of the input file in the "no problems" case so that a user could always work with the output without having to test for existence. No defect, just wanted to confirm this is really the behavior you want.  As written, this feels like it is combining two functions: (1) a filter that takes a sketchy mesh as input and outputs one that has only good tets, and (2) a checker that tells you whether there is anything wrong with a mesh. An alternative design might have a "check only" flag that would report on the sketchiness of a mesh, while the normal behavior would be to take whatever mesh you have and always produce one that is safe to use. Not sure whether that's better. (A Unix-y version could read from stdin and write to stdout)
</blockquote></details>

Keep in mind that this was thrown together in a hurry, and (in the plan) will likely be thrown away in a hurry. The successor will be a python tool (for distribution reasons) that will likely be more explicit about  checking vs. repairing. The other existing program that will get superseded by the successor tool is `geometry/proximity/zero_simplex_manual_test`, which is just a checker and reporter.
___
*[`geometry/proximity/refine_mesh.cc` line 69 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOdBtiEi-BeJ7h-MAP:-NoOfjeB-a0ZTbH5w2A0:b-1yg80h) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: I'm not sure how to parse this. Is it a noun phrase "Tet mesh as refined by Drake" or a command like "Refine a tet mesh for Drake"? Please clarify.
</blockquote></details>

My thought is that we don't have to say the word "Drake" here at all.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),rcory

___
*[`geometry/proximity/refine_mesh.cc` line 69 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOdBtiEi-BeJ7h-MAP:-NoOj-spCe2fWx_U-Q31:b-h5plgi) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L69)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

My thought is that we don't have to say the word "Drake" here at all.
</blockquote></details>

The string in question is written into the file as a "title" (more like a comment). My thought is just to leave a breadcrumb to the tool that wrote the file; interested users can follow it and read the documentation and/or code here.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),rcory

___
*[`geometry/proximity/refine_mesh.cc` line 25 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOWrMpDeO0YaewjR1N:-NoOkd-f-0MSMYMpt8Yc:b-dxcbu5) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L25)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Keep in mind that this was thrown together in a hurry, and (in the plan) will likely be thrown away in a hurry. The successor will be a python tool (for distribution reasons) that will likely be more explicit about  checking vs. repairing. The other existing program that will get superseded by the successor tool is `geometry/proximity/zero_simplex_manual_test`, which is just a checker and reporter.
</blockquote></details>

Makes sense!
___
*[`geometry/proximity/refine_mesh.cc` line 69 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/20324#-NoOdBtiEi-BeJ7h-MAP:-NoOkjvs3EzcoCjzurMj:b-wdj8z5) ([raw file](https://github.com/RobotLocomotion/drake/blob/aeacccea0fc34a931eb85d85c9910a587412697d/geometry/proximity/refine_mesh.cc#L69)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The string in question is written into the file as a "title" (more like a comment). My thought is just to leave a breadcrumb to the tool that wrote the file; interested users can follow it and read the documentation and/or code here.
</blockquote></details>

Nice, thanks.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 3 of 5 files at r7, 1 of 2 files at r12, 1 of 3 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20324)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),rcory

**Pull request merged**
