### PR TITLE
[py systems] Ensure DiscreteValues accessors work for T != double

### LINKED ISSUE #21221: DiscreteValues accessors don't work for non-double scalar types
### What happened?

```
from pydrake.all import LinearSystem_, AutoDiffXd

# make any arbitrary system with discrete state:
sys = LinearSystem_[AutoDiffXd](A=[[0]], B=[[1]], C=[[1]], D=[[0]], time_period=0.1)
context = sys.CreateDefaultContext()
print(context.get_discrete_state().value())
```
returns
```
RuntimeError: dtype=object arrays must be copied, and cannot be referenced
```

This was discussed before in [slack](https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1616653855015600) which turned into #14823. Looking at the bindings for `DiscreteValues`, it seems that many methods currently attempt to return a reference.  I believe we should probably be eating a copy here.

The BasicVector overloads also fail with the same error:
```
print(context.get_discrete_state_vector().value())
```
In BasicVector I see a work-around binding for `_get_value_copy`, which suggests that you knew this was a problem.

### Version

master

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #21221

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21236)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@RussTedrake for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21236#-:-NuR72rYAv2qti8lgqvW:b-cb1jfb)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@xuchenhan-tri any chance I could get your eyes for platform review on Mon?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21236#-:-NudcSfo-Y7cDEbiqF-i:b-v04at1)* status: LGTM missing from assignees RussTedrake(platform),xuchenhan-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: +(release notes: fix) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21236#-:-Nue78x470gaZvGDJepY:b-jl99ix)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform)

___
*[`bindings/pydrake/systems/framework_py_semantics.cc` line 1077 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21236#-Nue6ZsqCqE34sHsBeKz:-Nue6ZsqCqE34sHsBeL-:bs75qqt) ([raw file](https://github.com/RobotLocomotion/drake/blob/c74c2d7657f71e56b5b5e560d4694032eac4612c/bindings/pydrake/systems/framework_py_semantics.cc#L1077)):*
> ```cpp
>             return self->get_mutable_value(index);
>           },
>           // N.B. We explicitly want a failure when T != double.
> ```

BTW, I assume this is due to the limitation of numpy. Is that right? 

It'd be nice to properly document this instead of just leaving an implementation note, but I'm not sure how to achieve that. I'll leave it to you to see what's best here.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thank you

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21236#-:-NuxoUKf4uEwUozx3G9B:bqgsewo)* status: 1 unresolved discussion

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21236)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

___
*[`bindings/pydrake/systems/framework_py_semantics.cc` line 1077 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21236#-Nue6ZsqCqE34sHsBeKz:-NuxuKN073aKU2C47gpg:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c74c2d7657f71e56b5b5e560d4694032eac4612c/bindings/pydrake/systems/framework_py_semantics.cc#L1077)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I assume this is due to the limitation of numpy. Is that right? 

It'd be nice to properly document this instead of just leaving an implementation note, but I'm not sure how to achieve that. I'll leave it to you to see what's best here.
</blockquote></details>

Done.

**Pull request merged**
