### PR TITLE
Fail fast if SystemScalarConverter is mis-used

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In particular, detect cases where the user forgot to specify the most derived type while constructing a `LeafSystem`.

This is an important interlock for transmogrification in the presence of subclass hierarchies, such as in #6743.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6785)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@sherm1 are you game for a feature review of this?

**Comment by sherm1** [comment]
Yes -- feature review: I like it! :lgtm:, one ignorable BTW.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system_scalar_converter.h, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6785#-KqxdXKJ1XzB-dxb_ZJA:-KqxdXKJ1XzB-dxb_ZJB:bcyz50d) ([raw file](https://github.com/robotlocomotion/drake/blob/92688f488bd58e184900e24a8b28bff39f1e32b5/drake/systems/framework/system_scalar_converter.h#L184)):*
> ```objc
>         << NiceTypeName::Get<S<T>>() << " but was called with a "
>         << NiceTypeName::Get(other) << " at runtime";
>     throw std::runtime_error(msg.str());
> ```

BTW I would call that an `std::logic_error` (yes I know it doesn't matter much, not a defect). The distinction in my mind is that logic errors are mistakes in the calling program (here it misused the Drake API) while runtime errors are mistakes in the use or environment of a correctly-functioning calling program (such as an end user supplied it a malformed .sdf file, or a needed resource is missing).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6785#-:-KqxfZDxswVCrHQftoJq:bk7pijs)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with one nit.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system_scalar_converter.h, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6785#-KqxkxDl8rhtknCEn0ez:-KqxkxDl8rhtknCEn0f-:bsi85yt) ([raw file](https://github.com/robotlocomotion/drake/blob/92688f488bd58e184900e24a8b28bff39f1e32b5/drake/systems/framework/system_scalar_converter.h#L183)):*
> ```objc
>         << NiceTypeName::Get<S<U>>() << " into a "
>         << NiceTypeName::Get<S<T>>() << " but was called with a "
>         << NiceTypeName::Get(other) << " at runtime";
> ```

BTW nit: Final period?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6785#-:-KqxlX_oVjXtStJ3TR_r:bxq2awq)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system_scalar_converter.h, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6785#-KqxkxDl8rhtknCEn0ez:-Kqxm1u5nylFwdQH3YCW:bojffch) ([raw file](https://github.com/robotlocomotion/drake/blob/92688f488bd58e184900e24a8b28bff39f1e32b5/drake/systems/framework/system_scalar_converter.h#L183)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW nit: Final period?
</blockquote></details>

For no good reason, I abhor periods in exception messages; how much do you care?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6785)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system_scalar_converter.h, line 183 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6785#-KqxkxDl8rhtknCEn0ez:-KqxmsxgfAUrtuTLkONx:bj2m58k) ([raw file](https://github.com/robotlocomotion/drake/blob/92688f488bd58e184900e24a8b28bff39f1e32b5/drake/systems/framework/system_scalar_converter.h#L183)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The "BTW" communicates how much I care. I have a personal preference for punctuation. But certainly not strong enough to counter an abhorrence.
</blockquote></details>

OK (I use BTW for "Fix this but don't nag me to ack it" and FYI for "Consider".)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6785)*

**Pull request merged**
