### PR TITLE
Use iris version that uses FindMatlab instead of mex.cmake

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes in part #3596.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3620)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
+@rdeits for feature review and +@david-german-tri for platform review.

**Comment by rdeits** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSqwZFUn4fhFpkTU5o7:-KSqwZFUn4fhFpkTU5o8:b-f4jspu) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L240)):*
> ```CMake
>     -DIRIS_WITH_EIGEN=OFF
>     -DIRIS_WITH_MOSEK=OFF
>     -DMatlab_ROOT_DIR=${MATLAB_ROOT_DIR}
> ```

Why the inconsistent capitalization here? Is it actually necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSqwZFUn4fhFpkTU5o7:-KSqwnZIBELgQCT5--G8:bqjc7ic) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L240)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary>
> Why the inconsistent capitalization here? Is it actually necessary?
</details>
Very much necessary, yes. Basically, there are different conventions for variable names and casing, and CMake variable names are case sensitive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSqwZFUn4fhFpkTU5o7:-KSqxJnhFrIaxJVjk6Di:b-3uya98) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L240)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Very much necessary, yes. Basically, there are different conventions for variable names and casing, and CMake variable names are case sensitive.
</details>
(`Matlab_ROOT_DIR` is defined in CMake itself.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by rdeits** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSqwZFUn4fhFpkTU5o7:-KSqyB8PEsTuN7wpdDVQ:b620a90) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L240)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> (`Matlab_ROOT_DIR` is defined in CMake itself.)
</details>
I see. So where does the all-caps version come from? I just searched the whole codebase  and I don't see it being set anywhere. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 240 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSqwZFUn4fhFpkTU5o7:-KSr11cyRDjQUP3WWlaX:bml4jpx) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L240)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary>
> I see. So where does the all-caps version come from? I just searched the whole codebase  and I don't see it being set anywhere. 
</details>
There is a fix for that in #3186, though it is not of huge consequence if it is empty since it only used a hint to FindMatlab.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by rdeits** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-:-KSr5wrmuSQLLphksfQm:bnfp4nl)*

**Comment by rdeits** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSrwAgMyoacARQtDyzz:-KSrwAgMyoacARQtDz--:b-wrf7gf) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L235)):*
> ```CMake
> # iris
> drake_add_external(iris PUBLIC CMAKE
>   CMAKE_ARGS
> ```

Where did these come from?  Why are they hard-coded (e.g. eigen, mosek)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSrwAgMyoacARQtDyzz:-KSrwc7552oFa2eZm8me:bx9zrsj) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L235)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Where did these come from?  Why are they hard-coded (e.g. eigen, mosek)?
</details>
Iris. We already have Eigen and MOSEK provided by drake. We do not need to download and build them in two separate places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSrwAgMyoacARQtDyzz:-KSrx3s4IGu2DCxnAZ44:b3wnpwt) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L235)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Iris. We already have Eigen and MOSEK provided by drake. We do not need to download and build them in two separate places.
</details>
Compare with "configure-ccd-only" before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-KSrwAgMyoacARQtDyzz:-KSrxrSElqHU9R_BHpiy:ba5xgj6) ([raw file](https://github.com/robotlocomotion/drake/blob/67954066a8162be96f6f8bd829ca15e6fb1d1526/CMakeLists.txt#L235)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Compare with "configure-ccd-only" before.
</details>
(Not relevant here, but for completeness, Iris requires both.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620)*

**Comment by jamiesnape** [comment]
Strictly speaking, this needs rdeits/iris-distro#49, though this is not actually built using any multi-configuration generators.

**Comment by jamiesnape** [comment]
SHA updated.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
PTAL @david-german-tri.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3620#-:-KTBW9TVUZNQ3ydIiK-T:bnfp4nl)*

**Pull request merged**
