### PR TITLE
Check the variable type in AddDecisionVariables

### PR DESCRIPTION
**Pull request by hongkai-dai**
This bug was noticed by @jwnimmer-tri in https://github.com/RobotLocomotion/drake/issues/15178#issuecomment-865494916

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253#-:-MdJwmY06Zelfo1R5Y1H:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdKDEzi8PE5D8H9MzlX:blzptw1) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
> ```cpp
>     decision_variable_index_.insert(std::make_pair(
>         decision_variables(i).get_id(), num_existing_decision_vars + i));
>     switch (decision_variables(i).get_type()) {
> ```

The sanity checking (e.g., throwing on RANDOM_GAUSSIAN) should happen before we make any mutations to our instance variables.  Otherwise, our program will be left in an internally-inconsistent state when the user makes a mistake, and could segfault later with an out-of-bounds lookup.  (This was already a problem with the "is already a decision variable" checks, but is further magnified here.)
___
*[solvers/mathematical_program.cc, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKE0SA7h72ou1UHrpv:-MdKE0SA7h72ou1UHrpw:b-ui9j17) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L145)):*
> ```cpp
>         break;
>       case VarType::BINARY:
>         required_capabilities_.insert(ProgramAttribute::kBinaryVariable);
> ```

The mapping from the VarType enum to a set of program attributes (including the list of which types are disallowed) is duplicated between here and `NewVariables_impl` in the header.  Given some of the subtleties in play, I think it's important to keep it to only a single implementation.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdL4Pp6EvklNn6utcAV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The sanity checking (e.g., throwing on RANDOM_GAUSSIAN) should happen before we make any mutations to our instance variables.  Otherwise, our program will be left in an internally-inconsistent state when the user makes a mistake, and could segfault later with an out-of-bounds lookup.  (This was already a problem with the "is already a decision variable" checks, but is further magnified here.)
</blockquote></details>

Done.
___
*[solvers/mathematical_program.cc, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKE0SA7h72ou1UHrpv:-MdL4QAx-YmriDV6zcwB:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The mapping from the VarType enum to a set of program attributes (including the list of which types are disallowed) is duplicated between here and `NewVariables_impl` in the header.  Given some of the subtleties in play, I think it's important to keep it to only a single implementation.
</blockquote></details>

Done. Good call.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdL6CqM3tT_OekKYDBs:b8tzgtd) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is slightly better by virtue of being just before the `decision_variable_index_` line within the for-all-i loop instead of just after it, but it still has the problem that if a variable other than the first one contains an unsupported type, the `decision_variable_index_` changes from prior loop iterations will still be in intact.

The boring solution is to use two for-all-i loops, the first one to validate the input, and the second one to update the `decision_variable_index_` mapping.  The second loop could even appear a bit lower in the file (e.g., just before we call `AppendNanToEnd`, if that's clearer.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253#-:-MdNgDNO-yAkp2f3ku7W:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdNgJfc7fiwbqxYHLQP:b8h3ycs) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is slightly better by virtue of being just before the `decision_variable_index_` line within the for-all-i loop instead of just after it, but it still has the problem that if a variable other than the first one contains an unsupported type, the `decision_variable_index_` changes from prior loop iterations will still be in intact.

The boring solution is to use two for-all-i loops, the first one to validate the input, and the second one to update the `decision_variable_index_` mapping.  The second loop could even appear a bit lower in the file (e.g., just before we call `AppendNanToEnd`, if that's clearer.
</blockquote></details>

Actually I remember now, the boring solution doesn't work, because `CheckVariableType` is not just validation, it's also mutating the attributes of `this`.  Instead of mutating the attributes member field, it could take an attributes and an in/out argument.  We could update a temporary attributes set here, and then once all the validation is done we could merge that set into the member field.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdNhELb28pDmAVmjPFh:b-ml6dr8) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually I remember now, the boring solution doesn't work, because `CheckVariableType` is not just validation, it's also mutating the attributes of `this`.  Instead of mutating the attributes member field, it could take an attributes and an in/out argument.  We could update a temporary attributes set here, and then once all the validation is done we could merge that set into the member field.
</blockquote></details>

Another issue with the boring solution, is that if we have duplicated variables like `AddDecisionVariables([x, x])`, the boring solution won't catch it. Currently within the for loop, we append the new variable to `decision_variables_`, and then check for duplication for the next iteration. If we change to two for loops, with `decision_variables_` only changed in the second loop, then this duplication check is bypassed.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdNhzD4Ep-DT2cXjl7Y:bkls8oe) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Another issue with the boring solution, is that if we have duplicated variables like `AddDecisionVariables([x, x])`, the boring solution won't catch it. Currently within the for loop, we append the new variable to `decision_variables_`, and then check for duplication for the next iteration. If we change to two for loops, with `decision_variables_` only changed in the second loop, then this duplication check is bypassed.
</blockquote></details>

Another solution direction would be to replicate all of the member fields of interest as local variables, like so:

(1) copy member to locals
(2) loop through the arguments just once, updating and validating the locals as we go
(3) once the loop succeeds, move of the locals back into the members

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdPJkioExTYAHIeYkXE:b-oik0ef) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Another solution direction would be to replicate all of the member fields of interest as local variables, like so:

(1) copy member to locals
(2) loop through the arguments just once, updating and validating the locals as we go
(3) once the loop succeeds, move of the locals back into the members
</blockquote></details>

Before I try to implement the solution, may I ask why we care whether the program is in an internally inconsistent state? If the user pass in wrong `decision_variables`, the program will throw an error, why the program needs to stay consistent when an error is thrown? I would think that the program just terminates. Are you implying that some user might catch the error, and then make some modification to the program?

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253#-:-MdSlaQJC98f8I-VstOQ:b-e8yba)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdSlgWm5bTDuEr3q5VF:b7ofyc8) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I would think that the program just terminates. 

In pydrake, runtime exceptions do not necessarily crash the interpreter -- the user can resume at any point (especially in an interactive session, like a notebook).

As such, it can sometimes be useful to implement the  "Basic Exception Safety Guarantee" (see https://en.wikipedia.org/wiki/Exception_safety).

However, on further thought, it's probably a step too far to ask for that in this PR, even though it makes the problem a little bit worse.  It would be solved best as part of a larger refactor, so I'll mark this satisfied.
</blockquote></details>

Got it, I didn't realize pydrake doesn't crash with a runtime exception.

I will change this in a future PR. It is kind of hard to write a unit test to safegaurd "Basic Exception Safety Guarantee".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[solvers/mathematical_program.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15253#-MdKDEzi8PE5D8H9MzlW:-MdT0LxCDh1Je_PZtwCw:bfyysca) ([raw file](https://github.com/robotlocomotion/drake/blob/8c382f917da2646d37f34b0f2ab563ccb66645a2/solvers/mathematical_program.cc#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Got it, I didn't realize pydrake doesn't crash with a runtime exception.

I will change this in a future PR. It is kind of hard to write a unit test to safegaurd "Basic Exception Safety Guarantee".
</blockquote></details>

I don't think there's a hurry, but if you do get interested please ping me for help / co-development.  There's probably a few happy tricks we can use to make it much easier.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15253#-:-MdU9kZzDhDym1pAy2IU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
