### PR TITLE
Made RigidBody::collision_elements_ids and RigidBody::collision_element_groups private.

### PR DESCRIPTION
**Pull request by liangfok**
Added accessors for these member variables.
Builds upon #2908.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2909)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

Thanks!!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KNz2AJT8aMOQRnxRqYd:224703267)*

**Comment by sherm1** [comment]
Platform pass done. Definitely needs @amcastro-tri to take a look -- I think the comments about collision elements aren't right.

---

Reviewed 5 of 6 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 152 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2F87Jm9NstWqQvUkL:-KO2F87Jm9NstWqQvUkM:2070054217) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L152)):*
> ```objc
>    * collision element with this ID may collide against this rigid body and thus
>    * must be checked when computing collision reaction forces.
>    */
> ```

I don't think this comment makes sense. Collision elements are attached to a rigid body to provide it some collision geometry. Otherwise the rigid body can't collide with anything. It certainly doesn't collide with its own collision elements! @amcastro-tri, can you provide better wording?

---

*[drake/systems/plants/RigidBody.h, line 160 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2FqE6uoHYVjd_hpv6:-KO2FqE7IT_QmPvpzM20:-623429408) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L160)):*
> ```objc
>    * Those in different collision groups cannot collide with each other.
>    */
>   void AddCollisionElementToGroup(const std::string& group_name,
> ```

I'm confused by this method. Shouldn't this be restricted only to the collision elements on this body? @amcastro-tri, can you clarify? Should this be a private method only callable by friend RigidBodyTree? Or maybe this and the previous method should be combined into one that adds a collision element and records its group membership in one shot?

---

*[drake/systems/plants/RigidBody.h, line 164 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2HrTgeGdi2GDwTy6K:-KO2HrTgeGdi2GDwTy6L:-1333313816) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L164)):*
> ```objc
> 
>   /**
>    * Returns a reference to a vector of collision element IDs belonging to the
> ```

Should say "to an `std::vector`" rather than just vector to disambiguate -- could have been an Eigen vector, e.g.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KO2GR12v4CqH-nTT6dw:-15616191) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
> ```objc
>   /**
>    * Returns a reference to a vector of collision element IDs belonging to the
>    * collision elements that this rigid body can be in collision with.
> ```

This comment seems wrong -- @amcastro-tri?

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KO2GVCxyr2cvz1U1bq5:1065457293) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
> ```objc
>   /**
>    * Returns a reference to a vector of collision element IDs belonging to the
>    * collision elements that this rigid body can be in collision with.
> ```

Seems wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO2I7ZsYZ5AcoaAh5an:1772202436)*

**Comment by sherm1** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909)*

**Comment by liangfok** [comment]
I addressed as many of @sherm1's comments as I could at this point in time. Now waiting for input from @amcastro-tri.

---

Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 164 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2HrTgeGdi2GDwTy6K:-KO3IufuPzEowp6rPdj2:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L164)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should say "to an `std::vector`" rather than just vector to disambiguate -- could have been an Eigen vector, e.g.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO3J1FM-asgx_xrMV9H:1918054034)*

**Comment by amcastro-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 152 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2F87Jm9NstWqQvUkL:-KO5OMRbABwA9tRDjhwZ:-1854242671) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L152)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't think this comment makes sense. Collision elements are attached to a rigid body to provide it some collision geometry. Otherwise the rigid body can't collide with anything. It certainly doesn't collide with its own collision elements! @amcastro-tri, can you provide better wording?
</details>
@sherm1 is correct here. When you add a collision element to a rigid body (unfortunately now by id) what you are doing is adding collision geometry to the rigid body. The above documentation should read more like:
`Adds a collision element to this rigid body by collision element id. This effectively defines the collision geometry of this rigid body. If more than one collision element is added the resulting collision geometry is the union of the individual geometries of each collision element.`

---

*[drake/systems/plants/RigidBody.h, line 160 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2FqE6uoHYVjd_hpv6:-KO5UFx45pcz-XNqgF3_:-1141746005) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm confused by this method. Shouldn't this be restricted only to the collision elements on this body? @amcastro-tri, can you clarify? Should this be a private method only callable by friend RigidBodyTree? Or maybe this and the previous method should be combined into one that adds a collision element and records its group membership in one shot?
</details>
Collision groups in Drake are not what we think of, they are definitely not cliques. This is a convenience functionality used from Matlab, the bindings are pretty fuzzy but clearly they do use it from Matlab. Essentially what they do is to flag each collision element in a urdf file (I don't think the capability is there for sdf's) with a string like so: [`<collision group="heel">`](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Atlas/urdf/atlas_convex_hull.urdf#L40).
They use to simplify their models for speed. For instance see [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Atlas/runAtlasBalancing.m#L17) where they remove all the collision elements except those flagged to belong to the "heel" and "toe" groups.

Based on this little summary I just gave you the above documentation should read something more like:
`Adds a collision element represented by its @p id to the collision group @p group_name. Collision groups are just a convenient way to group a collection of collision elements so that they can be referenced by a group name they belong to. There is no implication on whether these elements can collide between them or not.`

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KO5XJsCzyNu4HiTJgBY:-659368663) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This comment seems wrong -- @amcastro-tri?
</details>
Yes it is. Should read something like:
`@returns the vector collision elements that represent the collision geometry of this rigid body.`

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KO5XalEelAbXd-_xonQ:1445757442) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Seems wrong.
</details>
see above for suggestion. 

---

*[drake/systems/plants/RigidBody.h, line 293 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5XjxV3pwuVOe0hcxY:-KO5XjxWnSuN8s4XsgS9:-14423573) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L293)):*
> ```objc
>   // A list of collision element IDs of collision elements that may collide with
>   // this rigid body.
>   std::vector<DrakeCollision::ElementId> collision_element_ids_;
> ```

This is wrong also. See comments above.

---

*[drake/systems/plants/RigidBody.h, line 298 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5Xq2633dIo8CfNmL-:-KO5Xq2633dIo8CfNmL0:-14423573) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L298)):*
> ```objc
>   // elements that may collide with each other. Collision groups in different
>   // groups do not collide with each other.
>   std::map<std::string, std::vector<DrakeCollision::ElementId>>
> ```

This is wrong also. See comments above.

---

*[drake/systems/plants/RigidBody.h, line 176 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5YVrAexIwWrJvDtbt:-KO5YVrAexIwWrJvDtbu:-1526962482) ([raw file](https://github.com/robotlocomotion/drake/blob/37172b8e46c486ba5a5e271d8776b950e8d0f5ca/drake/systems/plants/RigidBody.h#L176)):*
> ```objc
>   std::vector<DrakeCollision::ElementId>& get_mutable_collision_element_ids();
> 
>   const std::map<std::string, std::vector<DrakeCollision::ElementId>>&
> ```

Missing documentation here.  Though consider renaming to `get_group_to_collision_ids_map`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL @amcastro-tri and @sherm1. Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 152 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2F87Jm9NstWqQvUkL:-KO5aKhgNmWC1JGEWAuI:-46073160) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L152)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> @sherm1 is correct here. When you add a collision element to a rigid body (unfortunately now by id) what you are doing is adding collision geometry to the rigid body. The above documentation should read more like:
> `Adds a collision element to this rigid body by collision element id. This effectively defines the collision geometry of this rigid body. If more than one collision element is added the resulting collision geometry is the union of the individual geometries of each collision element.`
</details>
Done. Thanks for providing the correct text!

---

*[drake/systems/plants/RigidBody.h, line 160 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2FqE6uoHYVjd_hpv6:-KO5arZiGA87yNUx_rGH:-458682554) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L160)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Collision groups in Drake are not what we think of, they are definitely not cliques. This is a convenience functionality used from Matlab, the bindings are pretty fuzzy but clearly they do use it from Matlab. Essentially what they do is to flag each collision element in a urdf file (I don't think the capability is there for sdf's) with a string like so: [`<collision group="heel">`](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Atlas/urdf/atlas_convex_hull.urdf#L40).
> They use to simplify their models for speed. For instance see [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Atlas/runAtlasBalancing.m#L17) where they remove all the collision elements except those flagged to belong to the "heel" and "toe" groups.
> 
> Based on this little summary I just gave you the above documentation should read something more like:
> `Adds a collision element represented by its @p id to the collision group @p group_name. Collision groups are just a convenient way to group a collection of collision elements so that they can be referenced by a group name they belong to. There is no implication on whether these elements can collide between them or not.`
</details>
Done.  Thanks for providing the correct text!

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KO5b3NLtXlFYQH33tZX:1508991519) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Yes it is. Should read something like:
> `@returns the vector collision elements that represent the collision geometry of this rigid body.`
</details>
Done. Thanks!

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KO5b81iT9wuzU5rCWn6:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> see above for suggestion. 
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 293 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5XjxV3pwuVOe0hcxY:-KO5baWnbeo7L0cswtag:676689246) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L293)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This is wrong also. See comments above.
</details>
Fix.

---

*[drake/systems/plants/RigidBody.h, line 298 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5Xq2633dIo8CfNmL-:-KO5eWOwjsHStXqOsBAi:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L298)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This is wrong also. See comments above.
</details>
Fixed.

---

*[drake/systems/plants/RigidBody.h, line 176 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5YVrAexIwWrJvDtbt:-KO5bTtKP8At8inbnU5v:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/37172b8e46c486ba5a5e271d8776b950e8d0f5ca/drake/systems/plants/RigidBody.h#L176)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Missing documentation here.  Though consider renaming to `get_group_to_collision_ids_map`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO5eb01hSKFpLhMSc99:-2106348965)*

**Comment by sherm1** [comment]
Review pass done -- a few comments remaining.

---

Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 160 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2FqE6uoHYVjd_hpv6:-KO6er5siflmXhf_BqdM:-1398983051) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L160)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.  Thanks for providing the correct text!
</details>
Is this method restricted to collision elements that were previously added to this rigid body? I'm still fuzzy on how this method and `AddCollisionElement()` are related.

---

*[drake/systems/plants/RigidBody.h, line 164 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2HrTgeGdi2GDwTy6K:-KO6f9MqkBGMcBzO60-I:1282955042) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L164)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
I don't see the change to `std::vector`?

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KO6fOtc9FY3RyIYXjjS:-179827506) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
Also needs to note that you mean literally an `std::vector`, not just any vector-shaped thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO6fkq4dHtgn4gQdQWo:559793455)*

**Comment by liangfok** [comment]
@sherm1 I addressed your comments. PTAL. Thanks.

---

Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 160 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2FqE6uoHYVjd_hpv6:-KO6k9wGT5kWVLi0o9e4:1209554000) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Is this method restricted to collision elements that were previously added to this rigid body? I'm still fuzzy on how this method and `AddCollisionElement()` are related.
</details>
The only call site for this method is in RigidBodyTree::addCollisionElement():  

https://github.com/RobotLocomotion/drake/blob/30693ac57a0ec04feca2bbb416c933c8514bd9f2/drake/systems/plants/RigidBodyTree.cpp#L350

Here is the code:

```
DrakeCollision::ElementId RigidBodyTree::addCollisionElement(
    const RigidBodyCollisionElement& element, RigidBody& body,
    const string& group_name) {
  DrakeCollision::ElementId id = collision_model->addElement(element);
  if (id != 0) {
    body.collision_element_ids.push_back(id);
    body.collision_element_groups[group_name].push_back(id);
  }
  return id;
}
```

Clearly, the collision element ID that's passed to this method was already passed to `AddCollisionElement()`.

I've updated the documentation stating this requirement but did not add code to enforce it.

---

*[drake/systems/plants/RigidBody.h, line 164 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2HrTgeGdi2GDwTy6K:-KO6lSI1G-P-AT4kH03z:734464133) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L164)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't see the change to `std::vector`?
</details>
Oops! Done.

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KO6lWxQQcunsnsSXbwo:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Also needs to note that you mean literally an `std::vector`, not just any vector-shaped thing.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO6lz_aozszw4Tsm4N7:1448456820)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO76readIrB5t3WqXff:1058782226)*

**Comment by sherm1** [comment]
This is waiting for @amcastro-tri's acknowledgments.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KO77FcbbPKhp0YQqeAd:757908499)*

**Comment by amcastro-tri** [comment]
a few more comments. Besides that :lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KOA46Gg5CJhhFETSiha:-137993728) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. Thanks!
</details>
...reference to **an** `std::vector`...

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KOA4TjG6_cy6vNMlWCX:-838356550) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
to **an** `std::vector` of

---

*[drake/systems/plants/RigidBody.h, line 176 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5YVrAexIwWrJvDtbt:-KOA5IHmcB9WICNZEt-q:2143694340) ([raw file](https://github.com/robotlocomotion/drake/blob/37172b8e46c486ba5a5e271d8776b950e8d0f5ca/drake/systems/plants/RigidBody.h#L176)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
and the doc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KOA5Z_YgENDKuT7INK2:-521464591)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL  @amcastro-tri and @sherm1.

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KOA8YVh-8H4DBCtpOTy:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> ...reference to **an** `std::vector`...
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 172 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GVCxyr2cvz1U1bq4:-KOA7vnJuFndZzldom9K:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L172)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> to **an** `std::vector` of
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 176 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO5YVrAexIwWrJvDtbt:-KOA8TEW4ZnDOumoWySe:-1916060152) ([raw file](https://github.com/robotlocomotion/drake/blob/37172b8e46c486ba5a5e271d8776b950e8d0f5ca/drake/systems/plants/RigidBody.h#L176)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> and the doc?
</details>
Oops. Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KOA8VseV1Y_4WFrgDJ5:1261567251)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KOA9QIKLw5MdCGXaQ5S:-206704113)*

**Comment by amcastro-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KOADWWNxRu2s4COW_V9:1924181877) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
this one didn't make it through

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL @amcastro-tri and @sherm1.

@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBody.h, line 165 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-KO2GR12v4CqH-nTT6dv:-KOAEDVUOzIlXFA_rcsV:1035844726) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9b4f2c65f99b2a1401ef6313babe2a6a8e4684/drake/systems/plants/RigidBody.h#L165)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> this one didn't make it through
</details>
Oops. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2909#-:-KOAEFEl02iIwWLEnIgV:1757877677)*

**Pull request merged**
