### PR TITLE
ubuntu.rst: update installation instructions

### PR DESCRIPTION
**Pull request by scpeters**
add -y to several commands
add-apt-repository -> apt-add-repository
install software-properties-common to get apt-add-repository

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2223)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@scpeters Thanks for the corrections!  A few questions follow.

(You should be able to use reviewable to respond if you like, or also feel free to just use github comments/)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu.rst, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZXCrxkku-FS3opo8w:-KGZXCrxkku-FS3opo8x:-660134014) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L8)):*
I am of two minds about adding `-y` to the `upgrade` and `install [tiny list]` steps.  It's my understanding that by running these commands, we might end up removing a package that the user had wanted to keep (due to some Conflicts appearing in upgraded or new packages), though Essential packages would stay intact.  On one hand, I would frown at a user who had set up their system such that an `upgrade` or an `install` of a few very basic packages might do that to them.  On the other hand, is it worth the risk to remove a couple 'yes' prompts from a one-time procedure?

I am leaning toward keeping the `-y`, but want to wait for a concurring opinion as a sanity check.

---

*[drake/doc/ubuntu.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZa7jJjmkKQEC8acPi:-KGZa7jJjmkKQEC8acPj:840184506) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L9)):*
Good catch on needing`software-properties-common`

It looks like `python-software-properties` is perhaps a holdover from the 12.04 instructions, and can be removed now.  Would you agree?

---

*[drake/doc/ubuntu.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZWoxHMHdgqDvEt1P7:-KGZWoxHMHdgqDvEt1P8:477953378) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L10)):*
Do you have a citation for `add-apt-repository -> apt-add-repository` being preferred?   They are symlinked to be the same thing (at least on 14.04), and https://help.ubuntu.com/community/Repositories/CommandLine seems to prefer the add-apt-... spelling (even though I agree its a little weird).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-:-KGZWUYX5DeB6lloxFGQ:-1458132055)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by scpeters** [comment]
The `-y` is not necessary. I'm setting up a docker instance, so I was thinking in docker mode, which isn't the same as user-facing installation docs. I can revert them if that is preferred.

Good point, `software-properties-common` depends on `python3-software-properties`, so we could probably remove `python-software-properties` from the list.

I thought it was an error during testing, but it just wasn't installed on my docker image, and I hadn't realized they are symlinks. I can revert this change as well.

**Comment by scpeters** [comment]
I've never used reviewable before, so I'll just use github comments until I get used to it.

**Comment by jwnimmer-tri** [comment]
> I've never used reviewable before, so I'll just use github comments until I get used to it.

No problem.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu.rst, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZXCrxkku-FS3opo8w:-KGZodjwUQLJ6Tz-g5ym:-662452860) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L8)):*
> The -y is not necessary. I'm setting up a docker instance, so I was thinking in docker mode, which isn't the same as user-facing installation docs. I can revert them if that is preferred.

Let's see what other reviewers think.  This change may be a good thing.

---

*[drake/doc/ubuntu.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZa7jJjmkKQEC8acPi:-KGZopHl3C7YWeDiI62W:-1480316227) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L9)):*
> Good point, software-properties-common depends on python3-software-properties, so we could probably remove python-software-properties from the list.

Great, could you update the PR with this change?

---

*[drake/doc/ubuntu.rst, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZWoxHMHdgqDvEt1P7:-KGZowpUBP7Q-EMtMLZ4:-1185418447) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L10)):*
> I thought it was an error during testing, but it just wasn't installed on my docker image, and I hadn't realized they are symlinks. I can revert this change as well.

Ah, makes sense.  Yeah, I'd say let's leave it alone then.  Could you update the PR with this change (both places) taken out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-:-KGZpCU-UhzQ0AfGQMJO:412759248)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu.rst, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZXCrxkku-FS3opo8w:-KGZvjGWicaAwfI-2Rim:1574457182) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L8)):*
I vote no to the `-y` since everybody's system is slightly different so we really don't know what we're saying yes to. Also, ROS' [official installation instructions](http://wiki.ros.org/jade/Installation/Ubuntu) do not include the `-y` option and it'll probably be best to remain consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223)*

**Comment by scpeters** [comment]
Ok, I've reverted to `add-apt-repository` and removed `python-software-properties`. Waiting on consensus for `-y`

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 8 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-KGZXCrxkku-FS3opo8w:-KGefybHdow0s5hrrT7U:-1612372682) ([raw file](https://github.com/robotlocomotion/drake/blob/6569a624c87bb176581f88e30b6ca20b1485efb8/drake/doc/ubuntu.rst#L8)):*
Aha, that is a helpful link to ROS.  It reminds me that there are certain times where your xserver or mesa or dev packages or nvidia stuff can all fight, and try to hose your system.  I don't think lsb-core, wget, or software-properties-common should be able to trigger that -- but yeah, let's not take the risk.

So @scpeters could you remove the -y additions as well?

We'll just stick with the missing dependency fixup (replacement) for now, and call it a day.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223)*

**Comment by scpeters** [comment]
ok, reverted the `-y` in fa50ed3

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-:-KGgDTbJWFCWocsfWmoV:-1868698381)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2223#-:-KGgXU7Mey3mUEhp5PwR:1417088721)*

**Pull request merged**
