### PR TITLE
Use latest pip to build wheels

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
When setting up the Python environment for building wheels, also ensure we are using the latest version of pip.

+@jwnimmer-tri for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16834)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16834#-:-Myn-2lw7dzmwZwJsrjE:b3dcro0)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/image/provision-python.sh, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16834#-MymzvGq8aeOKZKPCMkR:-MymzvGq8aeOKZKPCMkS:bazsxof) ([raw file](https://github.com/robotlocomotion/drake/blob/d4a68f1646bf0bdbc71d19dabd6c91b19cae6cd6/tools/wheel/image/provision-python.sh#L14)):*
> ```Shell
> ${PYTHON} -m venv /usr/local
> 
> pip install --upgrade pip
> ```

I'm not a huge fan of using unpinned dependencies.  We were already doing that with `wheel` and `setuptools` and etc. so I guess it's not hugely worse to toss `pip` into that as well.

How about a TODO comment here, though, to pin all of these with some kind of lockfile (requirements.txt?) so that our builds of any given version of Drake have less variation as pypi evolves out from under us?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16834)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

___
*[tools/wheel/image/provision-python.sh, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16834#-MymzvGq8aeOKZKPCMkR:-Myn7S2yANcwRTshymYT:b5y3y4j) ([raw file](https://github.com/robotlocomotion/drake/blob/d4a68f1646bf0bdbc71d19dabd6c91b19cae6cd6/tools/wheel/image/provision-python.sh#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not a huge fan of using unpinned dependencies.  We were already doing that with `wheel` and `setuptools` and etc. so I guess it's not hugely worse to toss `pip` into that as well.

How about a TODO comment here, though, to pin all of these with some kind of lockfile (requirements.txt?) so that our builds of any given version of Drake have less variation as pypi evolves out from under us?
</blockquote></details>

Hmm... I definitely get where you're coming from. The reason I made this change in the first place, however, is that I noticed macOS was using a much newer version of pip, and wanted to improve consistency. (Well, also, I was having an issue at the time that I thought might be pip-related, and wanted to test Linux using the same version.) TBH, arranging for Linux to have the same version of pip as macOS is really the whole point of the PR; otherwise it isn't especially needed, and it's actually a regression in terms of version stability.

So, I agree in principle (and can think about / look into a TODO), but in practice I'm not sure we'll be able to pin down pip on macOS, other than perhaps making a concerted effort to update when that changes.

Does that additional insight change your thoughts at all?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16834)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/image/provision-python.sh, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16834#-MymzvGq8aeOKZKPCMkR:-MynpYHiETcIl_65QjAT:b-y5drib) ([raw file](https://github.com/robotlocomotion/drake/blob/d4a68f1646bf0bdbc71d19dabd6c91b19cae6cd6/tools/wheel/image/provision-python.sh#L14)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Hmm... I definitely get where you're coming from. The reason I made this change in the first place, however, is that I noticed macOS was using a much newer version of pip, and wanted to improve consistency. (Well, also, I was having an issue at the time that I thought might be pip-related, and wanted to test Linux using the same version.) TBH, arranging for Linux to have the same version of pip as macOS is really the whole point of the PR; otherwise it isn't especially needed, and it's actually a regression in terms of version stability.

So, I agree in principle (and can think about / look into a TODO), but in practice I'm not sure we'll be able to pin down pip on macOS, other than perhaps making a concerted effort to update when that changes.

Does that additional insight change your thoughts at all?
</blockquote></details>

It's true that on macOS having a repeatable build is basically impossible once homebrew is involved.  I'm OK to have things remain unpinned on macOS.

Once we have version pinning here on linux (which we want for setuptools, wheel, auditwheel, etc, even if we leave 'pip' alone), then that pip lockfile would go in scope for the "monthly bumps to pinned externals" chore (https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/new_release.py), which would help linux stay reasonably similar to mac.

**Comment by jwnimmer-tri** [comment]
Ping.  Still waiting on @mwoehlke-kitware here.

Is the plan still to try to merge this, and does it need to happen prior to #16872?

**Pull request closed without merging**
