### PR TITLE
Implements SAP holonomic constraint

### PR DESCRIPTION
**Pull request by amcastro-tri**
Generic holonomic constraint. This will allow us to quickly implement welds, couplers and distance constraints in the manager.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628#-:-N7uf8Rd7SKbsEKkc0yH:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with some nits and questions.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628#-:-N7vfjarATY30VjZwbSa:b24481b)* status: 12 unresolved discussions, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vLkxjBAUIdCG_WGMG:-N7vLkxjBAUIdCG_WGMH:b5ue5lm) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L16)):*
> ```objc
> 
> /* Implements an arbitrary holonomic constraint for the SAP formulation [Castro
>  et al., 2022].
> ```

nit, should we mention that this is an extension to the paper? We don't discuss arbitrary holonomic constraint in the paper.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vKp_n5Z-Mq88jnPyn:-N7vKp_n5Z-Mq88jnPyo:b91r2x6) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L23)):*
> ```objc
>   This constraint can be written at the velocity level by taking the time
>   derivative to obtain
>     ġ(q, t) = J⋅v + b = 0
> ```

Consider if you want to update the class doc in `SapConstraint`where we didn't consider explicit dependency on `t` and instead have `ġ = J⋅v`.



_Code quote:_
```objc
 ġ(q, t) = J⋅v + b = 0
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vKe1CAklrdyRjrc9R:-N7vKe1D6IoN_U_RVT5J:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L24)):*
> ```objc
>   derivative to obtain
>     ġ(q, t) = J⋅v + b = 0
>   where J is the contraint's Jacobian, v the vector of generalized velocities of
> ```

typo



_Code quote:_
```objc
contraint
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vM89mEmRN9aNZ9xWL:-N7vM89mEmRN9aNZ9xWM:b-4fqty) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L35)):*
> ```objc
>   Constraints in the SAP formulation model a compliant impulse γ according to:
>     y/dt = −k⋅(g+τ⋅ġ)
>     γ/δt = P(y)
> ```

nit mixed use of dt and δt

BTW perhaps call out in words that the first equation is on "y" and the second is on "γ". They are extremely hard to distinguish.



_Code quote:_
```objc
    y/dt = −k⋅(g+τ⋅ġ)
    γ/δt = P(y)
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vNQkS-TVfjoIP9DP3:-N7vNQkS-TVfjoIP9DP4:b-k1mcaq) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L66)):*
> ```objc
>      @param stiffnesses vector of stiffnesses kᵢ for each constraint.
>      @param relaxation_times vector of relaxation times τᵢ for each constraint.
>      @param beta Rigid approximation constant: Rₙ = β²/(4π²)⋅w when the
> ```

BTW, a thought:

We should probably provide a better intuition of how to choose `beta` than "go read the paper". Or, alternatively, always default `beta` to 1.0 and have some "advanced" API to modify it.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vOxHn1jVWJjU34Zuw:-N7vOxHn1jVWJjU34Zux:bd0onqp) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L108)):*
> ```objc
>    @param[in] clique The clique involved in the constraint.
>    @param[in] g The value of the constraint function.
>    @param[in] J The Jacobian, such that vc = J⋅v.
> ```

nit, we didn't introduce vc in this class, should we?
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7v_YmvCD5O9AHP1aK8:-N7v_YmvCD5O9AHP1aK9:b-i6fqe5) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L136)):*
> ```objc
> 
>   /* Implements the projection operation P(y) = max(γₗ, min(γᵤ, y)), independent
>    of the regularization R. Refer to SapConstraint::Project() for details. */
> ```

IIUC, the result of the projection is the same regardless of what norm we use. Is that correct?
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vUC-OCTS95U0fjBMN:-N7vUC-OCTS95U0fjBMO:b-v9j66t) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L76)):*
> ```cpp
>   const VectorX<T>& k = parameters_.stiffnesses();
>   VectorX<T> tau = parameters_.relaxation_times();
>   const VectorX<T> R =
> ```

nit, we use Rn in the paper.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vUTVmAMcjYQ9226lq:-N7vUTVmAMcjYQ9226lr:bqv3h2c) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L83)):*
> ```cpp
>   // a critically damped constraint, [Castro et al., 2022].
>   for (int e = 0; e < this->num_constraint_equations(); ++e) {
>     // If the elastic relaxation R_elastic is smaller than the near-rigid regime
> ```

nit mismatch of variable names -- R_elastic vs. R



_Code quote:_
```cpp
R_elastic
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vUb0UBn1KL22_SU7k:-N7vUb0UBn1KL22_SU7l:b82ccue) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L83)):*
> ```cpp
>   // a critically damped constraint, [Castro et al., 2022].
>   for (int e = 0; e < this->num_constraint_equations(); ++e) {
>     // If the elastic relaxation R_elastic is smaller than the near-rigid regime
> ```

nit, consider if this is going to make sense to the intended reader. Alternatively, this is equation (29) in the paper, and this strategy is discussed in detail in section V.B. 



_Code quote:_
```cpp
    // If the elastic relaxation R_elastic is smaller than the near-rigid regime
    // relaxation R_near_rigid, that means that time_step will not be able to
    // resolve the dynamics introduced by this constraint. We call this the
    // "near-rigid" regime. Here we clamp relaxation time to the time step.
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vZcyx8MsuK_Cb4t-J:-N7vZcyx8MsuK_Cb4t-K:b-qrbegl) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L127)):*
> ```cpp
>   if (dPdy != nullptr) {
>     const int nk = this->num_constraint_equations();
>     // Resizing is no-op if already the proper size.
> ```

nit this comment seems unrelated?
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vaAl14eIvU7Tu3Nug:-N7vaAl14eIvU7Tu3Nuh:b1mrxo) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L19)):*
> ```cpp
> 
> constexpr double kEps = std::numeric_limits<double>::epsilon();
> constexpr double kInf = std::numeric_limits<double>::infinity();
> ```

nit unused.
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vavio07Gll_fRJuOn:-N7vavio07Gll_fRJuOo:b-svdrux) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L74)):*
> ```cpp
>   const int clique1 = 12;
>   const int clique2 = 34;
>   const VectorXd g = g_;
> ```

nit antipattern to copy to const local variables and then attempt to move from them.

**Review by amcastro-tri — COMMENTED** [review]
working...

+@rpoyner-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628#-:-N7w5K9T22rNeAzANpcc:b-y5qt5g)* status: 9 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri, @rpoyner-tri, and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vLkxjBAUIdCG_WGMG:-N7w4AB9D41lgu2Am2Kd:b-lvnpfl) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L16)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, should we mention that this is an extension to the paper? We don't discuss arbitrary holonomic constraint in the paper.
</blockquote></details>

Fair. Added TODO instead to reference the next paper with more details on our new implementation.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vKp_n5Z-Mq88jnPyn:-N7w4eUv3nDN_xNuDFWU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Consider if you want to update the class doc in `SapConstraint`where we didn't consider explicit dependency on `t` and instead have `ġ = J⋅v`.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: buncha minor stuff

> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628#-:-N7wLTRs-BsGUZ7Ehucu:b-z3rilj)* status: 15 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wKcEdAsrADTIsKiqE:-N7wKcEdAsrADTIsKiqF:b-jmepyd) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L3)):*
> ```objc
> #pragma once
> 
> #include <limits>
> ```

unused
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wH6QHEsjBPrHV8UpA:-N7wH6QHEsjBPrHV8UpB:b-7ilvfu) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L39)):*
> ```objc
>     y/δt = −k⋅(g+τ⋅ġ)
>     γ/δt = P(y)
>   where we use the romman character y for the "unprojected impulses",
> ```

typo?



_Suggestion:_
```objc
Roman
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wHJKg7SrwuKru5BgH:-N7wHJKg7SrwuKru5BgI:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L52)):*
> ```objc
> 
>  @tparam_nonsymbolic_scalar */
> // TODO(amcastro-tri): allow to instantinate holonomic constraints with a non
> ```

typo



_Suggestion:_
```objc
instantiate
```
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wJOBSDIKu-w14vy4M:-N7wJOBSDIKu-w14vy4N:b-6ot5k1) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L53)):*
> ```objc
>  @tparam_nonsymbolic_scalar */
> // TODO(amcastro-tri): allow to instantinate holonomic constraints with a non
> // zero bias term b = ∂g/∂t.
> ```

Nit I believe `nonzero` is a word, and definitely less error-prone than splitting across lines. FWIW: https://gcc.gnu.org/legacy-ml/gcc/2001-10/msg00610.html



_Code quote:_
```objc
zero
```
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 141 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wHdn7Ds-YIA80eQ8T:-N7wHdn7Ds-YIA80eQ8U:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L141)):*
> ```cpp
>   }
> 
>   // Arbitrary combination of impulses below/ubove limits.
> ```

typo



_Suggestion:_
```cpp
above
```
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 183 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wHmIjA9JI-gzlqzN7:-N7wHmIjA9JI-gzlqzN8:b-tv2r4w) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L183)):*
> ```cpp
>       beta * beta / (4.0 * M_PI * M_PI) * delassus_inverse_approximation;
> 
>   // Expected regularization for the provided paramters of compliance.
> ```

typo (also again below)



_Suggestion:_
```cpp
parameters
```

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: 3 unresolved discussions (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vNQkS-TVfjoIP9DP3:-N7wIuw93ygV1jjbAPR3:b-10imvr) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L66)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, a thought:

We should probably provide a better intuition of how to choose `beta` than "go read the paper". Or, alternatively, always default `beta` to 1.0 and have some "advanced" API to modify it.
</blockquote></details>

I agree. Thus far I have not exposed this parameter to users so I really didn't come up with a good way to explain it.
I think the only reason I'd expose it is in the case in which the "near-rigid" regime is not "rigid enough" for a give applications, particularly at large time steps.
For those cases the user would probably set beta=0 so that the regularization is a direct function of the user provided stiffness and dissipation.
I haven't figured out how to expose this yet but definitely in my radar since I know for sure this case will come up.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7v_YmvCD5O9AHP1aK8:-N7wJyoa2x_IaNg6hlXB:bkgxpjs) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L136)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

IIUC, the result of the projection is the same regardless of what norm we use. Is that correct?
</blockquote></details>

that is correct. I paraphrased. Hopefully more clear now.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wKcEdAsrADTIsKiqE:-N7wMEll50EpEquZa_s7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/974e0678060cb733f0aec56fe7fd99c80c3e0c22/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vUC-OCTS95U0fjBMN:-N7wK4sP1cOD65lyLOgR:b5jv06h) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L76)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, we use Rn in the paper.
</blockquote></details>

we use Rn for the regularization "in the normal direction". We use R for the positive diagonal matrix of all regularization parameters.
However a follow up paper is missing. I'll update the class' docs as soon as we get an arxiv version at least.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vUb0UBn1KL22_SU7k:-N7wKrNIACBEobaTCf8Q:b-f0mqq6) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, consider if this is going to make sense to the intended reader. Alternatively, this is equation (29) in the paper, and this strategy is discussed in detail in section V.B. 
</blockquote></details>

I was thinking the intended readers are those Drake developers working on this code and therefore very familiar with the SAP paper. I updated the text to include a reference to that specific section.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vZcyx8MsuK_Cb4t-J:-N7wLjGSC9vnpb0KC650:bzgo38b) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L127)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit this comment seems unrelated?
</blockquote></details>

Added more text.
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vavio07Gll_fRJuOn:-N7wLucd65_TP7-9fdCb:btd880i) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L74)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit antipattern to copy to const local variables and then attempt to move from them.
</blockquote></details>

good catch. My fingers' muscle memory often type `const` when working in C++.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vNQkS-TVfjoIP9DP3:-N7wSCPx9njIZw6udlEs:b-mdg67o) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L66)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I agree. Thus far I have not exposed this parameter to users so I really didn't come up with a good way to explain it.
I think the only reason I'd expose it is in the case in which the "near-rigid" regime is not "rigid enough" for a give applications, particularly at large time steps.
For those cases the user would probably set beta=0 so that the regularization is a direct function of the user provided stiffness and dissipation.
I haven't figured out how to expose this yet but definitely in my radar since I know for sure this case will come up.
</blockquote></details>

Sounds good. Thanks for the explanation.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.h` line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7v_YmvCD5O9AHP1aK8:-N7wTpAjAFzemL4MJXN8:bx6pboa) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.h#L136)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

that is correct. I paraphrased. Hopefully more clear now.
</blockquote></details>

Yes, it is clear now. Thanks!
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vUC-OCTS95U0fjBMN:-N7wU4wY5H1O5i8eJP1w:b-epjblk) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L76)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

we use Rn for the regularization "in the normal direction". We use R for the positive diagonal matrix of all regularization parameters.
However a follow up paper is missing. I'll update the class' docs as soon as we get an arxiv version at least.
</blockquote></details>

Right. Thanks for the reminder.
___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vZcyx8MsuK_Cb4t-J:-N7wUDR_7ivF3-Ja_Hou:b-hfkifa) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L127)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Added more text.
</blockquote></details>

The connection between the comment and the code is lost on me because even though I buy the statement in the comment, I don't see why that's important in this case. In particular, we are not calling Resize() here, so whether resizing is no-op is irrelevant. Are you trying to convey that "no memory allocation happens if dPdy is already of the proper size"? Surely if you pass in a matrix of the right size but with all 1s, this won't be a no-op.
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 84 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wVAmA0JZ_6N1nugkb:-N7wVAmB9RmN9gCKOLxl:b-app24a) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d062db96c7418172a9cb1ec9dcc6ae16926f65/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L84)):*
> ```cpp
>   EXPECT_EQ(dut_->first_clique(), clique1);
>   EXPECT_EQ(dut_->second_clique(), clique2);
>   EXPECT_EQ(dut_->constraint_function(), g);
> ```

Now you are attempting to access moved from quantities. I would simply restore the "const" and not call std::move on the constructor.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vZcyx8MsuK_Cb4t-J:-N7wW2Cl9EYYhTsGECUt:bbslctk) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L127)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The connection between the comment and the code is lost on me because even though I buy the statement in the comment, I don't see why that's important in this case. In particular, we are not calling Resize() here, so whether resizing is no-op is irrelevant. Are you trying to convey that "no memory allocation happens if dPdy is already of the proper size"? Surely if you pass in a matrix of the right size but with all 1s, this won't be a no-op.
</blockquote></details>

The added text doesn't provide any additional clarification -- no one would invoke operator= and expect object on the lhs to have a different size from the object on the right hand side...

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7vZcyx8MsuK_Cb4t-J:-N7wdL0h2vPqoI6hjsYs:b-911lzb) ([raw file](https://github.com/robotlocomotion/drake/blob/40f59280d2a75c13730f09157b31fd98da2b4572/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L127)):*
> "no memory allocation happens if dPdy is already of the proper size"

Yes, that was my intetion. But you are right, it's not a "no-op" but really a "no heap allocation". Comment reworded.
___
*[`multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc` line 84 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17628#-N7wVAmA0JZ_6N1nugkb:-N7weikQ-MiDwXpKa4bk:bum266c) ([raw file](https://github.com/robotlocomotion/drake/blob/a0d062db96c7418172a9cb1ec9dcc6ae16926f65/multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Now you are attempting to access moved from quantities. I would simply restore the "const" and not call std::move on the constructor.
</blockquote></details>

clearly I didn't think that through....

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17628)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
