### PR TITLE
Deleted obsolete Kuka IIWA System1.0 examples

### PR DESCRIPTION
**Pull request by naveenoid**
Resolves a part of https://github.com/RobotLocomotion/drake/issues/3977

+ @sammy-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4251)

### CODE REVIEW

**Comment by liangfok** [comment]
+@liangfok :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4251#-:-KXMUJNPuViJlPkdNUg6:b-3x80r7)*

**Comment by liangfok** [comment]
Looks like the `CMakeLists.txt` need to be updated to reflect the removal of these files.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4251#-:-KXMUUa51u1Akdg7YdSR:b-n234di)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4251)*

**Comment by liangfok** [comment]
This PR passed all unit tests and is now awaiting @sammy-tri's review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4251#-:-KXXJHkGT5kTece_43PK:bdks5jp)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4251#-:-KXfi5J7UYujE-KkknyT:bnfp4nl)*

**Comment by naveenoid** [comment]
Thanks!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4251#-:-KXflwZqLQ41Dx2OpcRf:b-ucfknh)*

**Pull request merged**
