### PR TITLE
pybind AddFlatTerrainToWorld

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7979)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for both reviews, please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-:-L4k5Pf_IGMKOQyx6rO5:borg022)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-L4lDn-DxfnUHATbxHDu:-L4lDn-DxfnUHATbxHDv:b-c2tkrr) ([raw file](https://github.com/robotlocomotion/drake/blob/15db32431180aac4a8faab560a8f10e2271622b3/bindings/pydrake/multibody/rigid_body_tree_py.cc#L239)):*
> ```cpp
>         &drake::multibody::AddFlatTerrainToWorld,
>         py::arg("tree"),
>         py::arg("box_size") = 1000,
> ```

BTW Should a note be added here to synchronize this with the default arguments of the C++ method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-:-L4lDmNYd53CjZozR20j:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-L4lDn-DxfnUHATbxHDu:-L4mEMYtpXDW0ecSLGzG:b-nzw30y) ([raw file](https://github.com/robotlocomotion/drake/blob/15db32431180aac4a8faab560a8f10e2271622b3/bindings/pydrake/multibody/rigid_body_tree_py.cc#L239)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Should a note be added here to synchronize this with the default arguments of the C++ method?
</blockquote></details>

Isn’t that implied always in this framework?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7979)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-L4lDn-DxfnUHATbxHDu:-L4mGCOOb-zRWsIZZmRF:bvhfi92) ([raw file](https://github.com/robotlocomotion/drake/blob/15db32431180aac4a8faab560a8f10e2271622b3/bindings/pydrake/multibody/rigid_body_tree_py.cc#L239)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Isn’t that implied always in this framework?
</blockquote></details>

For trivial defaults (true, false, nullptr / nullopt), I'd say definitely yes - but for numeric constants, I'm just a wee bit tentative. However, I'd be fine with establishing that as a convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7979)*

**Comment by RussTedrake** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-L4lDn-DxfnUHATbxHDu:-L4mx-wpVft4BL1JsJsK:b7lrtpm) ([raw file](https://github.com/robotlocomotion/drake/blob/15db32431180aac4a8faab560a8f10e2271622b3/bindings/pydrake/multibody/rigid_body_tree_py.cc#L239)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For trivial defaults (true, false, nullptr / nullopt), I'd say definitely yes - but for numeric constants, I'm just a wee bit tentative. However, I'd be fine with establishing that as a convention.
</blockquote></details>

Let's see.  Anytime a pybind binding wants to support default arguments used in C++, it MUST type them in again.  And I would argue that the binding layer should not introduce new default arguments to existing functions.  So if I see any default arguments in the bindings/pydrake directory, I should know that it should correspond to a default value in c++, and should be sync'd. 

More subtle is the question of whether we should leave a breadcrumb in the C++ code saying "better change this in the bindings, too!".  But I would argue that a C++ comment would be easy to miss, and that we should not sacrifice the elegance of the C++ code (much) to support the bindings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7979)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7979#-L4lDn-DxfnUHATbxHDu:-L4nUfL8cG2-U0cvznhu:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/15db32431180aac4a8faab560a8f10e2271622b3/bindings/pydrake/multibody/rigid_body_tree_py.cc#L239)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Let's see.  Anytime a pybind binding wants to support default arguments used in C++, it MUST type them in again.  And I would argue that the binding layer should not introduce new default arguments to existing functions.  So if I see any default arguments in the bindings/pydrake directory, I should know that it should correspond to a default value in c++, and should be sync'd. 

More subtle is the question of whether we should leave a breadcrumb in the C++ code saying "better change this in the bindings, too!".  But I would argue that a C++ comment would be easy to miss, and that we should not sacrifice the elegance of the C++ code (much) to support the bindings.
</blockquote></details>

OK Sounds good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7979)*

**Pull request merged**
