### PR TITLE
Use package instead of relative path for allegro model files

### PR DESCRIPTION
**Pull request by huihuaTRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252)

### CODE REVIEW

**Review by huihuaTRI — COMMENTED** [review]
+@jwnimmer-tri for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKbMi4B1PwNIvuZ3zIC:b-1wvd9i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@IanTheEngineer for feature review as a step along fixing #10531.  One or both of you (Ian and/or Huihua) should confirm locally that viewing the model in drake-visualizer still works.  See manipulation/util for geometry_inspector and show_model.

I'll handle platform review.  It seems fine on first glance.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252)* status: LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer (waiting on @IanTheEngineer)

**Review by huihuaTRI — COMMENTED** [review]
I have run locally and the model looks fine.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKcFbP64kF_HkEuMQl0:b-1l5b6o)* status: LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
Could you please describe how you tested the visualization locally? I might be building or invoking things incorrectly, but `bazel-bin/manipulation/util/show_model.runfiles` appears to only have access to `iiwa_description`, `wsg_50_description`, and `ycb` packages, which leads the following commands to fail (with a meshcat server in the background):

```
./bazel-bin/manipulation/util/show_model \
--meshcat default  --find_resource \
drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
```
and
```
./bazel-bin/manipulation/util/show_model   --meshcat default \
 ${PWD}/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
```

The `allegro_hand_description` tests themselves pass with the package URI change. Once I can replicate a visualization locally, I'll give the green light for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKgrROBBZAJvihhUrOs:b-chgt78)* status: LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer (waiting on @IanTheEngineer)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform assuming the preview thing gets figured out.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKhFe2P1V_J2tSkhyxK:bj9c0q9)* status: LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer)

**Review by huihuaTRI — COMMENTED** [review]
You have to provide the package_path for it to find the file. Here is what I did `./bazel-bin/manipulation/util/show_model ./manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf --package_path manipulation/models/allegro_hand_description`

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKhb5al2OpzIVw--12b:bs13c3w)* status: LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer)

**Review by huihuaTRI — COMMENTED** [review]
I have added the explanation in the show_model file. PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKhcEBs1MwuseXOqK98:bjex428)* status: LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
Thanks for the updates. I was able to visualize using the package path using the command you used, specifying the `package_path` and a full or relative path to the sdf file. However, the command you added to the documentation is not able to find the `allegro_hand_description` with `find_resource` in my testing. See the details below. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKjGoTKAP9Z4TXMwNQL:b-8jgjnj)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @huihuaTRI, @IanTheEngineer, and @jwnimmer-tri)

___
*[manipulation/util/show_model.py, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14252#-MKjE2Ky4ACJf7P-oEgJ:-MKjE2Ky4ACJf7P-oEgK:b-cguacq) ([raw file](https://github.com/robotlocomotion/drake/blob/91efb8f55ddf2dea1395f88adc9f8095144f2938/manipulation/util/show_model.py#L41)):*
> ```Python
>         manipulation/models/iiwa_description \
>         --find_resource \
>         drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
> ```

Thank you for the explanation. In my testing, `show_model --find_resource` seems to require the `allegro_hand_description` files to be available under `show_model.runfiles`:

```
./bazel-bin/manipulation/util/show_model    --package_path manipulation/models/allegro_hand_description   --find_resource         drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
Using FindResourceOrThrow('drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf')
Traceback (most recent call last):
  File "/path/to/drake/./bazel-bin/manipulation/util/show_model.runfiles/drake/manipulation/util/show_model.py", line 210, in <module>
    main()
  File "/path/to/drake/./bazel-bin/manipulation/util/show_model.runfiles/drake/manipulation/util/show_model.py", line 186, in main
    filename, make_parser = parse_filename_and_parser(args_parser, args)
  File "/path/to/drake/./bazel-bin/manipulation/util/show_model.runfiles/drake/manipulation/util/show_model.py", line 110, in parse_filename_and_parser
    filename = FindResourceOrThrow(res_path)
RuntimeError: Sought 'drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf' in runfiles directory '/path/to/drake/bazel-bin/manipulation/util/show_model.runfiles' but the file does not exist at that location nor is it on the manifest; perhaps a 'data = []' dependency is missing.
```

However, fully specifying the location of the sdf file works, as long as the `package_path` is supplied, works:

```
./bazel-bin/manipulation/util/show_model   --package_path manipulation/models/allegro_hand_description    ${PWD}/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
[2020-10-28 08:27:04.588] [console] [warning] Currently MultibodyPlant does not handle joint limits for continuous models. However some joints do specify limits. Consider setting a non-zero time step in the MultibodyPlant constructor; this will put MultibodyPlant in discrete-time mode, which does support joint limits.
[2020-10-28 08:27:04.588] [console] [warning] Joints that specify limits are: `joint_8`, `joint_9`, `joint_10`, `joint_11`, `joint_12`, `joint_13`, `joint_14`, `joint_15`, `joint_4`, `joint_5`, `joint_6`, `joint_7`, `joint_0`, `joint_1`, `joint_2`, `joint_3`.
[2020-10-28 08:27:04.594] [console] [warning] Currently MultibodyPlant does not handle joint limits for continuous models. However some joints do specify limits. Consider setting a non-zero time step in the MultibodyPlant constructor; this will put MultibodyPlant in discrete-time mode, which does support joint limits.
[2020-10-28 08:27:04.594] [console] [warning] Joints that specify limits are: `joint_8`, `joint_9`, `joint_10`, `joint_11`, `joint_12`, `joint_13`, `joint_14`, `joint_15`, `joint_4`, `joint_5`, `joint_6`, `joint_7`, `joint_0`, `joint_1`, `joint_2`, `joint_3`.
```
I don't think you need to necessarily handle all of `show_model`'s use cases with this PR, but since you're updating the documentation, I think it should reflect the functional case using a fully specified path.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @huihuaTRI)

**Review by huihuaTRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer and @jwnimmer-tri)

___
*[manipulation/util/show_model.py, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14252#-MKjE2Ky4ACJf7P-oEgJ:-MKk3LjpD1d5tazdGXzU:bgzf1yb) ([raw file](https://github.com/robotlocomotion/drake/blob/91efb8f55ddf2dea1395f88adc9f8095144f2938/manipulation/util/show_model.py#L41)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Thank you for the explanation. In my testing, `show_model --find_resource` seems to require the `allegro_hand_description` files to be available under `show_model.runfiles`:

```
./bazel-bin/manipulation/util/show_model    --package_path manipulation/models/allegro_hand_description   --find_resource         drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
Using FindResourceOrThrow('drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf')
Traceback (most recent call last):
  File "/path/to/drake/./bazel-bin/manipulation/util/show_model.runfiles/drake/manipulation/util/show_model.py", line 210, in <module>
    main()
  File "/path/to/drake/./bazel-bin/manipulation/util/show_model.runfiles/drake/manipulation/util/show_model.py", line 186, in main
    filename, make_parser = parse_filename_and_parser(args_parser, args)
  File "/path/to/drake/./bazel-bin/manipulation/util/show_model.runfiles/drake/manipulation/util/show_model.py", line 110, in parse_filename_and_parser
    filename = FindResourceOrThrow(res_path)
RuntimeError: Sought 'drake/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf' in runfiles directory '/path/to/drake/bazel-bin/manipulation/util/show_model.runfiles' but the file does not exist at that location nor is it on the manifest; perhaps a 'data = []' dependency is missing.
```

However, fully specifying the location of the sdf file works, as long as the `package_path` is supplied, works:

```
./bazel-bin/manipulation/util/show_model   --package_path manipulation/models/allegro_hand_description    ${PWD}/manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
[2020-10-28 08:27:04.588] [console] [warning] Currently MultibodyPlant does not handle joint limits for continuous models. However some joints do specify limits. Consider setting a non-zero time step in the MultibodyPlant constructor; this will put MultibodyPlant in discrete-time mode, which does support joint limits.
[2020-10-28 08:27:04.588] [console] [warning] Joints that specify limits are: `joint_8`, `joint_9`, `joint_10`, `joint_11`, `joint_12`, `joint_13`, `joint_14`, `joint_15`, `joint_4`, `joint_5`, `joint_6`, `joint_7`, `joint_0`, `joint_1`, `joint_2`, `joint_3`.
[2020-10-28 08:27:04.594] [console] [warning] Currently MultibodyPlant does not handle joint limits for continuous models. However some joints do specify limits. Consider setting a non-zero time step in the MultibodyPlant constructor; this will put MultibodyPlant in discrete-time mode, which does support joint limits.
[2020-10-28 08:27:04.594] [console] [warning] Joints that specify limits are: `joint_8`, `joint_9`, `joint_10`, `joint_11`, `joint_12`, `joint_13`, `joint_14`, `joint_15`, `joint_4`, `joint_5`, `joint_6`, `joint_7`, `joint_0`, `joint_1`, `joint_2`, `joint_3`.
```
I don't think you need to necessarily handle all of `show_model`'s use cases with this PR, but since you're updating the documentation, I think it should reflect the functional case using a fully specified path.
</blockquote></details>

Done. Thanks for checking it and sorry for my carelessness. Now updated and tested locally. It should work this time.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
Your new instructions work well. One final comment on line length, and we're good to go (assuming the rest of the tests then pass).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKkJoxiDDr0PpbEjdyK:b-uovs03)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @huihuaTRI)

___
*[manipulation/util/show_model.py, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14252#-MKkIj_s6zu6bDmXMcLL:-MKkIj_tDROZKbFXdoPA:b-ut9tln) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1be261c693db95c28b1c2802db4f91f7e16b11/manipulation/util/show_model.py#L35)):*
> ```Python
>         ${PWD}/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
> 
> If the model is using package path (e.g. "package://package_name/model_sdf.obj")
> ```

This line is one character beyond the 79 char limit. It's is quite pedantic, but it is causing the CI tests to fail.

**Review by huihuaTRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer and @jwnimmer-tri)

___
*[manipulation/util/show_model.py, line 35 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14252#-MKkIj_s6zu6bDmXMcLL:-MKkj_g2E3vgm_kp4AkM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e1be261c693db95c28b1c2802db4f91f7e16b11/manipulation/util/show_model.py#L35)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

This line is one character beyond the 79 char limit. It's is quite pedantic, but it is causing the CI tests to fail.
</blockquote></details>

Done.

**Review by huihuaTRI — COMMENTED** [review]
The CI is happy now. PTAL. Thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKkrBlBBBvMmM8Y2ZNh:b1uldm9)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer and @jwnimmer-tri)

**Review by IanTheEngineer — COMMENTED** [review]
:lgtm: thanks for the iterations. Looks like Jeremy has given the thumbs up for platform as well.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKkzTyNElcwIe7BlFwq:b-jzfu5t)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),IanTheEngineer (waiting on @jwnimmer-tri)

**Review by huihuaTRI — COMMENTED** [review]
Yep. Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14252#-:-MKl16DF0UISg-biHBk3:b-8wlglo)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),IanTheEngineer (waiting on @jwnimmer-tri)

**Pull request merged**
