### PR TITLE
Fix sporadic segfault in RemoveVertex

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16330)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by sherm1 — COMMENTED** [review]
Thanks, Mark!
+@sherm1 for both reviews
:lgtm: pending one minor change and green CI
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16330#-:-MsljIfU3iwBSzx6dO83:blgrkgh)* status: 1 unresolved discussion, missing label for release notes (waiting on @mpetersen94)

___
*[geometry/optimization/graph_of_convex_sets.cc, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16330#-Mslj0u-C6L7SRtEg_GW:-Mslj0u-C6L7SRtEg_GX:brupst9) ([raw file](https://github.com/robotlocomotion/drake/blob/58dec09dbe6670f691977220276a83c2e813b873/geometry/optimization/graph_of_convex_sets.cc#L168)):*
> ```cpp
>       e = edges_.erase(e);
>     } else {
>       e++;
> ```

nit: per [style guide](https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement) this should be `++e`

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16330)* status: missing label for release notes (waiting on @sherm1)

___
*[geometry/optimization/graph_of_convex_sets.cc, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16330#-Mslj0u-C6L7SRtEg_GW:-MslkcvZ-F9gwc262HD_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58dec09dbe6670f691977220276a83c2e813b873/geometry/optimization/graph_of_convex_sets.cc#L168)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per [style guide](https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement) this should be `++e`
</blockquote></details>

Done.

**Comment by mpetersen94** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16330)* status: missing label for release notes (waiting on @mpetersen94)

**Pull request merged**
