### PR TITLE
Adjust pydrake unit tests for when IPOPT is disabled

### LINKED ISSUE #6500: pydrake_mathematical_program_ipopt_solver_test fails when NO_IPOPT=ON
my .bazelrc defines 
```
build --define=NO_IPOPT=ON
test --define=NO_IPOPT=ON
```
and I see
```
//drake/bindings:pydrake_mathematical_program_ipopt_solver_test          FAILED 
```

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #6500.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6512)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.

**Comment by RussTedrake** [comment]
:lgtm:  (tested on my linux box and confirmed that all tests now pass)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6512#-:-KoRuoTFzUP8QZVwZKAB:b8kchwd)*

**Comment by jwnimmer-tri** [comment]
I'm on deck for Monday, so perhaps +@soonho-tri for platform review, please?

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6512#-:-KoYAyamsl7PH67dkTqG:bnfp4nl)*

**Pull request merged**
