### PR TITLE
Added spatial inertia calculator for solid cuboid.

### PR DESCRIPTION
**Pull request by liangfok**
Since this is a utility that is of general use, I figured it should go under common. I placed it in a sub-directory since there will be many more calculators, one for each primitive shape.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3387)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KR9VfNHpDxCLT1DFd3X:-KR9VfNHpDxCLT1DFd3Y:b4f4dzi) ([raw file](https://github.com/robotlocomotion/drake/blob/5e68a3c8e96fe0f2b78ee8b2d0d92a88421dc710/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L28)):*
> iyy = m / 12.0 * (w ** 2 + d ** 2)
> izz = m / 12.0 * (w ** 2 + h ** 2)
I think these 2 formulas are swapped?  The formulas are in terms of the other terms, so y (depth) is in terms of w and h.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KR9VfNHpDxCLT1DFd3X:-KR9eeKL8Bjz76VF19zk:b-q0rk34) ([raw file](https://github.com/robotlocomotion/drake/blob/5e68a3c8e96fe0f2b78ee8b2d0d92a88421dc710/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L28)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > iyy = m / 12.0 * (w ** 2 + d ** 2)
> > izz = m / 12.0 * (w ** 2 + h ** 2)
> I think these 2 formulas are swapped?  The formulas are in terms of the other terms, so y (depth) is in terms of w and h.
</details>
See also formulas here:  http://ocw.mit.edu/courses/aeronautics-and-astronautics/16-07-dynamics-fall-2009/lecture-notes/MIT16_07F09_Lec26.pdf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387)*

**Comment by Lucy-tri** [comment]
I don't know python so I'm not qualified to review the test program and the makelists (tho I can understand and review spatial_inertia_solid_cuboid.py).  

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRAc92mBJRyT3fvgO_6:-KRAc92mBJRyT3fvgO_7:buldhlz) ([raw file](https://github.com/robotlocomotion/drake/blob/49b040311daf35d59587275e0496fd7210ced98d/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L13)):*
> ```Python
>     ['ixx', 'iyy', 'izz'])
> 
>   # Assmes X = depth, Y = width, Z = height
> ```

typo: should be "Assumes".  
I thought x is width, y is depth?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KRAeIS-ev1EguAVu-9o:bfpsrob)*

**Comment by liangfok** [comment]
@lucy-tri, thanks for reviewing `spatial_inertia_solid_cuboid.py`.

Since I copied the unit test from `cpplint_wrapper_test.py`, +@jwnimmer-tri for feature review of it please.

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 28 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KR9VfNHpDxCLT1DFd3X:-KRB7Gr1vO-RJ3_rsn8C:b-xvohb6) ([raw file](https://github.com/robotlocomotion/drake/blob/5e68a3c8e96fe0f2b78ee8b2d0d92a88421dc710/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L28)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> See also formulas here:  http://ocw.mit.edu/courses/aeronautics-and-astronautics/16-07-dynamics-fall-2009/lecture-notes/MIT16_07F09_Lec26.pdf
</details>
You're right. Done.

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 13 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRAc92mBJRyT3fvgO_6:-KRB6w1M1gXozp8OIsz1:b-jkixey) ([raw file](https://github.com/robotlocomotion/drake/blob/49b040311daf35d59587275e0496fd7210ced98d/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L13)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> typo: should be "Assumes".  
> I thought x is width, y is depth?
</details>
Oops. This comment is deprecated because I decided to ditch the terms "width", "depth", and "height" since they are ambiguous. Instead, I'm now using x axis, y axis, and z axis in the cuboid's body frame.

I deleted the comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KRB7KWgmMHQZJ1vrQgx:baa9iii)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KRE9ynydNXruKuToomO:bnfp4nl)*

**Comment by liangfok** [comment]
@lucy-tri: Thanks!
@jwnimmer-tri: I'm now waiting on you to feature review the Python unit testing code. Actually, maybe you can also do the platform review?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KREAoi2Y3MCOG_ittA-:bslrxfb)*

**Comment by jwnimmer-tri** [comment]
So to be honest, 136 LOC to express 3 simple equations seems a bit of overkill.
How often will this tool be run?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KREKhgWFjm9kcE3Zv8h:b-wff6pi)*

**Comment by liangfok** [comment]
I predict it'll be run increasingly often as we develop more and more models. This code can eventually be called by the code that procedurally generates a model.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KREQCGnuJ-KIig5stqv:b-i89zn1)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 5 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/CMakeLists.txt, line 62 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRFO0CNed1Z_MI_m1Ni:-KRFO0COz5wlBVCoO6xy:b-1znkku) ([raw file](https://github.com/robotlocomotion/drake/blob/c545cede4a7c2c073d64594f05618139e9247546/drake/common/CMakeLists.txt#L62)):*
> ```CMake
> 
> add_subdirectory(test)
> add_subdirectory(spatial_inertia_calculators)
> ```

BTW Consider if a whole new directory is premature organization?  If the future is one program to do inertia for many kinds of objects, a directory may be unwanted?

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRFSXWbuQUpckizbcxs:-KRFSXWbuQUpckizbcxt:b-qpwvet) ([raw file](https://github.com/robotlocomotion/drake/blob/c545cede4a7c2c073d64594f05618139e9247546/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L9)):*
> ```Python
> import collections
> 
> def ComputeSpatialInertia(x, y, z, m):
> ```

Even without a formal rule, I think https://www.python.org/dev/peps/pep-0008/#function-names should still be followed.

---

*[drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py, line 23 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRFSGUEeRcUZzx79Jx5:-KRFSGUFVruOZzGJg-Il:bdwdlle) ([raw file](https://github.com/robotlocomotion/drake/blob/c545cede4a7c2c073d64594f05618139e9247546/drake/common/spatial_inertia_calculators/spatial_inertia_solid_cuboid.py#L23)):*
> ```Python
>       description='Computes the spatial inertia of a solid cuboid.')
> 
>   parser.add_argument('x_length', metavar='x', type=float,
> ```

Please use named arguments (`--x` here, so callers do `--x=1.0`); otherwise, the position arguments may become mixed up / confused.

---

*[drake/common/spatial_inertia_calculators/test/spatial_inertia_solid_cuboid_test.py, line 1 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRFRrGug6f4feldIcY0:-KRFRrGveYJSfh1yEtMV:b-999xy8) ([raw file](https://github.com/robotlocomotion/drake/blob/c545cede4a7c2c073d64594f05618139e9247546/drake/common/spatial_inertia_calculators/test/spatial_inertia_solid_cuboid_test.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Per f2f, for brevity / clarity, please refactor this file to import the python code under test, instead of shelling out to it.  The `cpplint_wrapper_test.py` was an unusual case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/CMakeLists.txt, line 62 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-KRFO0CNed1Z_MI_m1Ni:-KRFh-Kg7Z20O-P0V5jx:b32v57) ([raw file](https://github.com/robotlocomotion/drake/blob/c545cede4a7c2c073d64594f05618139e9247546/drake/common/CMakeLists.txt#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider if a whole new directory is premature organization?  If the future is one program to do inertia for many kinds of objects, a directory may be unwanted?
</details>
+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387)*

**Comment by sherm1** [comment]
I don't understand the need for a standalone calculator for such a simple shape. If this is because you want to generate model files, where will the original geometry come from for those files? CAD packages like SolidWorks can calculate inertias for arbitrary shapes. [Meshlab](http://meshlab.sourceforge.net/) will do it for free. For Drake wouldn't this tool be far more valuable in C++, associated with Drake's geometric shapes? Isn't there a need for calculating inertias when building models directly through the API?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KRM4PwFQFuAoZ_G5jFS:bq9uf06)*

**Comment by liangfok** [comment]
Good point! I will re-implement this in C++ within Drake's geometric shapes. I will close this PR and issue a new one when that's complete.

For the record, I'm using this calculator for debugging purposes. In #3258, I have a model of a Prius that rolls over _way_ too easily. I want to evaluate various spatial inertia models for it to see if I can reduce the probability of it rolling over. Doing it through SolidWorks or Meshlab felt too heavyweight for my purposes.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3387#-:-KRMEj_Q1CygDJELj4ph:b302a4d)*

**Pull request closed without merging**
