### PR TITLE
Require java

### PR DESCRIPTION
**Pull request by jonathan-owens**
Please don't merge yet. This currently points toward my fork of libbot. I just want to test it.  issue #1774

### CODE REVIEW

**Comment by jonathan-owens** [comment]
@billhoffman Are these failures the ones we discussed yesterday morning? They don't seem to be related to any changes I pushed.

Also, I'm not sure the best way to prove that this works. Given the bug described in issue #1774, my way of locally testing the fix (on Ubuntu 14.04) was:

1. Remove the Java package (``openjdk-6-*``) installed when one runs the ``install_prereqs.sh`` script. Note that it's important to watch and see if the package manager installs ``openjdk-7-*`` packages during the removal of 6 packages. If so, go ahead and ``apt-get remove openjdk-7-*`` as well.
2. I then blow away my clone of Drake and then check my fork of Drake out, making sure to switch to my ``require_java`` branch, which points to the ``libbot`` commit with the ``FORCE_JAVA`` flag.
3. Follow the steps to install on Ubuntu, outlined [here](http://drake002.csail.mit.edu/drake/sphinx/ubuntu.html), skipping the ``install_prereqs.sh`` step.
4. Run ``make``. It will configure and build a while, but when it tries to configure ``libbot`` and find Java, the ``make`` command will fail, saying Java isn't found.
5. Go ahead and run the ``install_prereqs.sh`` step.
6. Run ``make`` again, and ``libbot`` should successfully configure and Drake should successfully build. In the past, this is where the ``bot2-lcmg`` error would occur. Now, since ``libbot`` was never configured, it successfully configure, as it can find Java.

The error or fix check will not be appropriately checked by the build servers, as far as I can tell, so not sure how to move forward.

**Comment by RussTedrake** [comment]
it looks like this is adding the find java to drake-distro/drake/CMakeLists.txt, but the point was to add it to drake-distro/CMakeLists.txt?
will close this one, as it also started by forking from the bad commit on master.

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, that would require java is installed before doing anything (in particular, before `make download-all` can be run). Will that be a problem?

**Comment by RussTedrake** [comment]
if the workflow documented in the from-source instructions remains intact, then i don't see a problem.  please check?

**Comment by jonathan-owens** [comment]
@RussTedrake Last week, @billhoffman and @mwoehlke-kitware and I had a discussion which resulted in the design decision we made to modify the ``libbot`` POD instead of adding the check for Java at the super-build level. They can both feel free to chime in if I'm mistaken or they have anything to add, but there were a couple of main driving forces behind this decision.

There was talk about ``libbot`` going away after stripping out some of the ``lcm`` stuff. Since that is what is causing the problem, it's good that we've only _really_ modified ``libbot`` and not much of anything else.

Additionally, the implemented fix addressed what @mwoehlke-kitware brought up above. To clarify on what he is saying, if the ``find_package`` call is done in the super-build and can't find java, then it will error out on ``make options``. This fixes the issue of getting ``libbot`` configured without Java, but causes a new issue that the user has to install Java before he can do anything. So in some sense it's breaking the workflow that is outlined in the from-source instructions, because you're installing one of the pre-reqs before actually calling ``install_prereqs.sh``.

Of course, the quickest fix would probably be to add an instruction for them to ``apt-get`` java before make is ever run, at the same time you're installing CMake and build-essential. If this step is not there, and they install Java 7, then after running ``install_prereqs.sh`` you have the unfortunate situation of having two different Javas on your system.

Couple this with the possibility of removing ``libbot``, we decided it would be more consistent with the current from-source workflow to have Java checked for in the ``libbot`` POD.

Honestly, I think this all leads into a bigger discussion about getting ``make clean`` to work properly. This issue would not arise if one were to follow the instructions laid out in from-source to begin with. They would run the ``install_prereqs.sh`` script before running the general ``make`` command, so Java would be installed and ``libbot`` would be configured without a hitch. We're essentially implementing a fix to a problem that arises when someone fails to follow the installation instructions. If, however, ``make clean`` worked as expected, then ``libbot`` could reconfigure after a failure to find Java and all would be good.

Let us know what you think.

**Comment by RussTedrake** [comment]
thank you for the clear explanation.  i think failing at make options is ok if it is a required prereq.  The same would happen if they did not have a compiler installed.  no?

making java mandatory in libbot would be ok for drake, but could break other projects which use libbot as a submodule.

but i also think that the install_prereqs is causing unnecessary pain.  we should replace that logic with clear install instructions at the superbuild level with a single apt-get call (as decided at the bottom of #1281).

**Comment by jonathan-owens** [comment]
> ...The same would happen if they did not have a compiler installed. no?

> making java mandatory in libbot would be ok for drake, but could break other projects which use libbot as a submodule.

Ah, fair enough. I'll move forward with adding the ``find_package`` at the super-build level then.

> but i also think that the install_prereqs is causing unnecessary pain. we should replace that logic with clear install instructions at the superbuild level with a single apt-get call ...

I agree wholeheartedly with this!

**Comment by mwoehlke-kitware** [comment]
> making java mandatory in libbot would be ok for drake, but could break other projects which use libbot as a submodule.

The idea was that we would pass an option when configuring libbot to turn on this behavior; other users would only be affected if they opt in by passing the same option.

Just clarifying... we'll still go with whatever approach you think is best...

**Comment by RussTedrake** [comment]
That is a fine solution, as well.  @jamiesnape is moving all of the install_prereqs logic to an instruction at the drake superbuild level, which i think further justifies requiring java right at the superbuild.

**Comment by jamiesnape** [comment]
Yes, that is my thinking.

**Comment by jonathan-owens** [comment]
So we're going forward with the fix in request #1871, then?

**Pull request closed without merging**
