### PR TITLE
Minor fixes for flake8's F821 (undefined name) error

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Command-line:
```
$ flake8 --select=F821 **/*.py \
    | grep -v _extra.py | grep -v drake_visualizer | grep -v schunk_buttons.py
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14293)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ggould-tri for both reviews, please!

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14293#-:-MLLNuKp7_np1oXroX3m:b-meaw5r)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

**Review by ggould-tri — COMMENTED** [review]
:lgtm: pending the `AngleAxis` trouble that CI has identified.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14293#-:-MLNbaUz-mQDVq-5d0YU:b-f288jc)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

___
*[examples/manipulation_station/differential_ik.py, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14293#-MLNbYcf4S6nOcegqrZc:-MLNbYcg6sDzRrh3F2Ol:b-7aoo99) ([raw file](https://github.com/robotlocomotion/drake/blob/41f54b2929f1d5217024177464ac8461e150835e/examples/manipulation_station/differential_ik.py#L4)):*
> ```Python
> 
> from pydrake.manipulation.planner import DoDifferentialInverseKinematics
> from pydrake.math import AngleAxis, RigidTransform, RollPitchYaw
> ```

FYI:  CI thinks you're wrong about this.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14293)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[examples/manipulation_station/differential_ik.py, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14293#-MLNbYcf4S6nOcegqrZc:-MLNoF0B0cnCnVwWgTtg:b6nzx5y) ([raw file](https://github.com/robotlocomotion/drake/blob/41f54b2929f1d5217024177464ac8461e150835e/examples/manipulation_station/differential_ik.py#L4)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI:  CI thinks you're wrong about this.
</blockquote></details>

OK Bah! What does CI know? Clearly I'm in the right!

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14293)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

**Pull request merged**
