### PR TITLE
Use shared tinyobjloader

### PR DESCRIPTION
**Pull request by jamiesnape**
Part of the effort to slim `libdrake.so` and simplify `drake.cps`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7773)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
Does removing `tinyobjloader` from `drake.cps` make it a private dependency? If so, could the commit be renamed to specify this?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7773#-:-L3AX-TcSjDhUj_FhGJu:b-1jok4z)*

**Comment by jamiesnape** [comment]
Done.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7773#-:-L3Ajh-wJPSxCGCcQyIr:b-896fix)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor BTW (that's probably another issue)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/tinyobjloader/package.BUILD.bazel, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7773#-L3TMDwav-SqCkYu65T2:-L3TMDwav-SqCkYu65T3:b-8d885d) ([raw file](https://github.com/robotlocomotion/drake/blob/4127d51961b693ee0dcf303071a252d7b82fa35f/tools/workspace/tinyobjloader/package.BUILD.bazel#L33)):*
> ```
> install(
>     name = "install",
>     targets = [":libtinyobjloader.so"],
> ```

BTW If we're distributing binaries without headers, should we have any indication of version numbers in the binary itself?
(Possibly to be captured by another issue?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7773#-:-L3TMiTjyRYVNZd89uKP:b1bi4q2)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/tinyobjloader/package.BUILD.bazel, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7773#-L3TMDwav-SqCkYu65T2:-L3TN-5aXLL8-JlZac0h:b-a5i77r) ([raw file](https://github.com/robotlocomotion/drake/blob/4127d51961b693ee0dcf303071a252d7b82fa35f/tools/workspace/tinyobjloader/package.BUILD.bazel#L33)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW If we're distributing binaries without headers, should we have any indication of version numbers in the binary itself?
(Possibly to be captured by another issue?)
</blockquote></details>

Yes, it would be an idea. I think we need to abstract this code by now anyway. I was hoping for Bazel itself to step up to the plate, but I will probably be waiting forever...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7773)*

**Comment by jwnimmer-tri** [comment]
Do we have a documented rationale anywhere for making private dependencies linked dynamically (exposing them to users), versus just making them hidden visibility and linked statically?  If it's just for `.so` size, FWIW I think that's a bad trade-off.

**Comment by EricCousineau-TRI** [comment]
I was curious about this too when testing out the "all is shared" prototype.
I'd still like things to split into shared libs if possible. Perhaps there is a way to achieve some analog of `-fvisibility=hidden` for a solib?

(One hacky workaround, such as `drake_cc_shared_library(..., hide_namespace = {"orig": "new"})`, which could handle doing a quick namespace swap at some level (assuming the library is properly namespaced in the first place)...)

**Comment by jamiesnape** [comment]
> Do we have a documented rationale anywhere for making private dependencies linked dynamically (exposing them to users), versus just making them hidden visibility and linked statically? If it's just for .so size, FWIW I think that's a bad trade-off.

So you are looking for something like `-Wl,--exclude-libs,ALL` (or at least `-Wl,--exclude-libs,<libname>` if I can work out `<libname>`?

**Comment by jwnimmer-tri** [comment]
I guess I was thinking maybe `tools/workspace/tinyobjloader/package.BUILD.bazel` edits `cc_library(name = "tinyobjloader", ...)` to add `copts = ["-fvisibility=hidden"]` and set `linkstatic = 1`.

**Comment by jamiesnape** [comment]
> I guess I was thinking maybe tools/workspace/tinyobjloader/package.BUILD.bazel edits cc_library(name = "tinyobjloader", ...) to add copts = ["-fvisibility=hidden"] and set linkstatic = 1.

My understanding is that `-fvisibility=hidden` would only affect the static library itself (say `libtinyobjloader.a`), not the symbols incorporated into `libdrake.so`, but it is quite possible I am wrong.

**Comment by jwnimmer-tri** [comment]
Yeah, it would need some exploration.  I think the object code from `libtinyobjloader.a` stays private, but perhaps weak (template) symbols and such would also go into `multibody/shapes/geometry.o`, and then not be private (though would be weak)?  I guess that's still pollution, though it seems like `libtinyobjloader.so` has the same symptom.

In any case, I guess that's all a separate PR.

Reading more, I see now that this PR is merely removing cruft -- we're already installing the `.so` (and having downstreams link it), _as well as_ installing `.cmake` stuff so that `lib/cmake/drake/drake-config.cmake` can refer to it.  This PR just prunes all that cruft, so I support this going in even without the wider discussion.

**Pull request merged**
