### PR TITLE
Cleans up gain_test.cc and combines it with gain_scalartype_test.cc.

### PR DESCRIPTION
**Pull request by liangfok**
For increased clarity, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3816)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUAk3bO04xd50PDq3B3:b-9j5084)*

**Comment by sherm1** [comment]
My guess is that the AutoDiff include was there because the author intended to add a test that instantiates Gain with an n AutoDiffScalar, which seems like a good idea. How about adding a short test rather than removing that include?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUE64gpPrpm3xD3TJTR:b-odt7xe)*

**Comment by liangfok** [comment]
I had considered doing that but then I found the following tests which I think covers `AutoDiffScalar`: https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/primitives/test/gain_scalartype_test.cc

Should I merge the two files?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUE8efgubI1LyO3qQ4O:bf0usge)*

**Comment by sherm1** [comment]
Oh, I see it is split because of the `gain-inl.h` dependence of the autodiff test. Yes, I think it would be better if they were combined into a single test. For now that can include both `gain.h` and `gain-inl.h` but ultimately we should have all the necessary instantiations in `gain.cc` so the test case can go back to including just `gain.h` while still testing an autodiffed version. But we don't yet know all the instantiations we'll need so I think including `gain-inl.h` makes sense. In any case I don't think splitting the unit tests into two files is a good precedent.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUECh7wwwIpA0CQh4Il:bd2410j)*

**Comment by jwnimmer-tri** [comment]
I would also support going back to a single test file for this module, but I dispute the idea that the `inl` file should be included in said test.  It's important to confirm that the module under test work without having the `inl` file included.

I see no reason to tie up this PR in the template-instantiation discussion.  However, if @liangfok wants to combine the two test files, then concurrently the types needed for autodiff test cases need to be added to the `gain.cc` file so that the `inl` file is not needed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUHfjBjrsAj-C4BYygH:b-thlwvi)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. The two tests are now merged into one and I added the necessary explicit template instantiation to avoid needing to include the `-inl.h` file by the unit test.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUIZn8B6RaLxejRA3ng:b-64vtph)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/gain.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-KUIbwb9c-2hGVxrgb3y:-KUIbwbAQKgtxo7QNqsr:bsvgpdm) ([raw file](https://github.com/robotlocomotion/drake/blob/1ef33d087363ec83a2d2350c222ff780044def5e/drake/systems/framework/primitives/gain.cc#L11)):*
> ```cpp
> template class DRAKE_EXPORT Gain<AutoDiffXd>;
> template class DRAKE_EXPORT Gain<Eigen::AutoDiffScalar<Eigen::Matrix<double, 2,
>     1, Eigen::DontAlign>>>;
> ```

The header file comment is now out of date https://github.com/RobotLocomotion/drake/blob/baf072fe6751f2e4fd4e9119708df31bc5d3112f/drake/systems/framework/primitives/gain.h#L16

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUIbp0hostZNB0zRWYw:bv95ifn)*

**Comment by liangfok** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/gain.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-KUIbwb9c-2hGVxrgb3y:-KUIfBC7hjf9rRiPpQ8n:b-fgyg89) ([raw file](https://github.com/robotlocomotion/drake/blob/1ef33d087363ec83a2d2350c222ff780044def5e/drake/systems/framework/primitives/gain.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The header file comment is now out of date https://github.com/RobotLocomotion/drake/blob/baf072fe6751f2e4fd4e9119708df31bc5d3112f/drake/systems/framework/primitives/gain.h#L16
</details>
Done, see `gain.h`. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816)*

**Comment by jwnimmer-tri** [comment]
Thanks!  -@jwnimmer-tri.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUIfSqJE6i5zhZULGsI:bozr5o5)*

**Comment by sherm1** [comment]
>  if @liangfok wants to combine the two test files, then concurrently the types needed for autodiff test cases need to be added to the gain.cc file so that the inl file is not needed.

@jwnimmer-tri, looking at this now I'm not sure it makes sense. @liangfok added an essentially arbitrary AutoDiff type for testing purposes, but now it is enshrined in gain.cc and in the user documentation for the Gain system. I don't see any reason why this particular AutoDiff scalar would be one of the ones we would want to promise to instantiate. I think it is too early for us to be committing to which instantiations we will provide so we ought to allow `-inl.h` in tests. Do you have a better idea?

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/gain.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-KUIbwALOR7CDkDfiiuT:-KUIbwALOR7CDkDfiiuU:b-looqyk) ([raw file](https://github.com/robotlocomotion/drake/blob/1ef33d087363ec83a2d2350c222ff780044def5e/drake/systems/framework/primitives/gain.cc#L10)):*
> ```cpp
> template class DRAKE_EXPORT Gain<double>;
> template class DRAKE_EXPORT Gain<AutoDiffXd>;
> template class DRAKE_EXPORT Gain<Eigen::AutoDiffScalar<Eigen::Matrix<double, 2,
> ```

BTW, should be `Eigen::Vector2d`?

---

*[drake/systems/framework/primitives/gain.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-KUIgdZwHvtyUc4fhkkL:-KUIgdZxm4RaZjAIvL1n:b-7czn14) ([raw file](https://github.com/robotlocomotion/drake/blob/1ef33d087363ec83a2d2350c222ff780044def5e/drake/systems/framework/primitives/gain.cc#L11)):*
> ```cpp
> template class DRAKE_EXPORT Gain<AutoDiffXd>;
> template class DRAKE_EXPORT Gain<Eigen::AutoDiffScalar<Eigen::Matrix<double, 2,
>     1, Eigen::DontAlign>>>;
> ```

Why DontAlign?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUJGPnKCrN5tbFrRtGJ:b-qyrd87)*

**Comment by jwnimmer-tri** [comment]
IMO, a better idea would be to leave well-enough alone, and accept a version of the original PR that just removes a few stray lines.  The detour here for seems to have driven us into a dead-end.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUJHQrvw47oAU9uyA4-:b-z8op16)*

**Comment by sherm1** [comment]
@liangfok, would the Autodiff part of the test work using the already-instantiated AutoDiffXd so that you don't have to commit to a new instantiation? If so that would allow the combined test to work without including `gain-inl.h` and without requiring we sort out issues we aren't ready to deal with yet. If not, I would prefer that you include `gain-inl.h` in the consolidated test case. That doesn't make anything worse IMO since the original split-off test case was doing that anyway. Also, including `-inl.h` where needed is currently permitted by our `-inl.h` documentation. I would rather have an include to get rid of later than whole tests.

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUJKyCDKZyu3hCGGYcM:b8apd2w)*

**Comment by liangfok** [comment]
@sherm1 I will test and let you know.

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUPGv1N4bV8vL45YF3m:bfqveda)*

**Comment by liangfok** [comment]
@jwnimmer-tri  and @sherm1, commit https://github.com/RobotLocomotion/drake/commit/b7ea0905174e9a9305ffce8f0ff3585d4998e02d#diff-d38a8f38827f4c056c6cd722bcd3d257, @soonho-tri added another instantiation of `Gain` using `T = drake::symbolic::Expression`. Is it OK if I explicitly instantiate it?

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUSWtqgYD_lEH3tUzRi:bf8ha2h)*

**Comment by liangfok** [comment]
I just spoke with @jwnimmer-tri and decided to revert this PR back to R1. We can combine `gain_test.cc` and `gain_scalartype_test.cc` into a single file and decide which types to explicitly instantiate in a future PR.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/gain.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-KUIbwALOR7CDkDfiiuT:-KUSk15HCsBmc5LB7PsH:bv8wlyn) ([raw file](https://github.com/robotlocomotion/drake/blob/1ef33d087363ec83a2d2350c222ff780044def5e/drake/systems/framework/primitives/gain.cc#L10)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, should be `Eigen::Vector2d`?
</details>
I reverted back to R1 and thus am no longer explicitly instantiating this type.

---

*[drake/systems/framework/primitives/gain.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-KUIgdZwHvtyUc4fhkkL:-KUSk7-UiXN9Mjl1eqGO:b-h7e033) ([raw file](https://github.com/robotlocomotion/drake/blob/1ef33d087363ec83a2d2350c222ff780044def5e/drake/systems/framework/primitives/gain.cc#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Why DontAlign?
</details>
I'm not sure. I copied it from @amcastro-tri's original code in `cain_scalartype_test.cc`. Maybe he was having memory alignment issues on certain systems?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUSahFb132dGVoBXcsR:b54sfou)*

**Comment by liangfok** [comment]
I cleaned up `gain_test.cc` some more by adding a `using std::unique_ptr`. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUSpgiiw4JiLJZP2g8u:b-szdj9p)*

**Comment by jwnimmer-tri** [comment]
-@sherm1 +@jwnimmer-tri for both reviews.

:lgtm:

If there is a reason to do further cleanup, the person or team with that reason can do the follow-up PR.  Neither Liang nor our team care at this point.

---

Reviewed 2 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3816#-:-KUSr603vMdJ5qUn-BBr:b-yolavh)*

**Pull request merged**
