### PR TITLE
[pydrake] Add example of memory leaks

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14387.

The objective of this PR is to bootstrap the virtuous cycle of making reproducers of the problem, finding good diagnostic tools to help explain the problem, fixing bugs in prototypes, re-instrumenting, adding more examples, etc.

---

Sample output of `bazel run //bindings/pydrake:memory_leak_test` as of today:

```
RUNNING: dut_simple_source
RepetitionDetail(i=0, blocks=3)
RepetitionDetail(i=1, blocks=4)
RepetitionDetail(i=2, blocks=5)
RepetitionDetail(i=3, blocks=5)
RepetitionDetail(i=4, blocks=6)
RepetitionDetail(i=5, blocks=7)
RepetitionDetail(i=6, blocks=8)
RepetitionDetail(i=7, blocks=8)
RepetitionDetail(i=8, blocks=9)
RepetitionDetail(i=9, blocks=9)
RepetitionDetail(i=10, blocks=9)
RepetitionDetail(i=11, blocks=10)
RepetitionDetail(i=12, blocks=10)
RepetitionDetail(i=13, blocks=10)
RepetitionDetail(i=14, blocks=10)
RepetitionDetail(i=15, blocks=11)
RepetitionDetail(i=16, blocks=12)
RepetitionDetail(i=17, blocks=12)
RepetitionDetail(i=18, blocks=12)
RepetitionDetail(i=19, blocks=12)
RepetitionDetail(i=20, blocks=12)
RepetitionDetail(i=21, blocks=12)
RepetitionDetail(i=22, blocks=12)
RepetitionDetail(i=23, blocks=12)
RepetitionDetail(i=24, blocks=12)
RUNNING: dut_trivial_simulator
RepetitionDetail(i=0, blocks=4)
RepetitionDetail(i=1, blocks=7)
RepetitionDetail(i=2, blocks=14)
RepetitionDetail(i=3, blocks=17)
RepetitionDetail(i=4, blocks=23)
RepetitionDetail(i=5, blocks=25)
RepetitionDetail(i=6, blocks=29)
RepetitionDetail(i=7, blocks=36)
RepetitionDetail(i=8, blocks=42)
RepetitionDetail(i=9, blocks=45)
RepetitionDetail(i=10, blocks=48)
RepetitionDetail(i=11, blocks=52)
RepetitionDetail(i=12, blocks=57)
RepetitionDetail(i=13, blocks=65)
RepetitionDetail(i=14, blocks=72)
RepetitionDetail(i=15, blocks=78)
RepetitionDetail(i=16, blocks=84)
RepetitionDetail(i=17, blocks=91)
RepetitionDetail(i=18, blocks=96)
RepetitionDetail(i=19, blocks=102)
RepetitionDetail(i=20, blocks=107)
RepetitionDetail(i=21, blocks=112)
RepetitionDetail(i=22, blocks=122)
RepetitionDetail(i=23, blocks=131)
RepetitionDetail(i=24, blocks=137)
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21951)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21951)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21951#-O7zi4a47jrkamInzihV:-O7zi4a47jrkamInzihW:bdiusv) (no related file):*
Got a bit of data. As far as I can tell "simple_source" doesn't leak or is too slow to worry about. On the other hand, "trivial_simulator" leaks about 1Mib/sec, as show in the graph:


The initial working set for both is about 300Mib, so it takes maybe 5.5 minutes for "trivial_simulator" to double the initial working set.

The above graph and the monitoring were done with `apt install python3-mprof`.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21951)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21951#-O7zi4a47jrkamInzihV:-O82W5Xm7JVSazw4D8uq:b-g9u51k) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Got a bit of data. As far as I can tell "simple_source" doesn't leak or is too slow to worry about. On the other hand, "trivial_simulator" leaks about 1Mib/sec, as show in the graph:


The initial working set for both is about 300Mib, so it takes maybe 5.5 minutes for "trivial_simulator" to double the initial working set.

The above graph and the monitoring were done with `apt install python3-mprof`.
</blockquote></details>

Excellent.  Does that mean this reproducer is a sufficient MVP and we can merge it and keep going?

___

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review tomorrow per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; I hope this bears fruit!

BTW, an idea for a future PR, if I were working with this a lot I would definitely toss a https://pypi.org/project/sparklines/ graph into the text output.  The difference between logistic (e.g. finite cache), logarithmic (e.g. unbounded dict), and linear (traditional leak) would then be visually obvious.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21951#-:-O87Mgyd-QJQA-49pTfz:bypyujk)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Pull request merged**
