### PR TITLE
[doc] Add release notes v1.19.0

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: 19 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 15 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4qG6N6DuFaRt9G_la:-N_4qG6O1VAwvw9m83Qs:bnn6jc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L15)):*
> ```Markdown
> * `geometry::optimization::ConvexSet::AddPointInSetConstraints` now returns the new variables/constraints created.  This is a breaking change for subclasses of `ConvexSet`, which must now implement the new return type in their NVI overrides. ([#19634][_#19634])
> * Methods previously returning `multibody::ConstraintIndex` (which could not be used) now return `multibody::MultibodyConstraintId` (which can be used to get constraint information from the multibody plant). ([#19698][_#19698])
> * `multibody::MultibodyPlant` now rejects duplicate frame names. ([#19724][_#19724])
> ```

BTW Maybe this break should be listed first in the bullet list?  It seems like the one more likely to affect real users.
___
*[`doc/_release-notes/v1.19.0.md` line 30 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4qeOD-p3e_ICcMNN5:-N_4qeOE9xLUJQISs2xe:b-6bcqy3) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L30)):*
> ```Markdown
> * Allow specifying a time offset in `ZeroOrderHold`. ([#19650][_#19650])
> * Add `systems::System<T>::ExecuteInitializationEvents`. ([#19577][_#19577])
> * Split RgbdSensorDiscrete into its own file. ([#19649][_#19649])
> ```

nit 19649 is not a new feature; it's just a fix.
___
*[`doc/_release-notes/v1.19.0.md` line 36 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4r-CG5o3h2hp3en_l:-N_4r-CG5o3h2hp3en_m:b-r1gqkz) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L36)):*
> ```Markdown
> 
> * [#19419][_#19419]: Fix a crash in `FiniteHorizonLinearQuadraticRegulator`. ([#19653][_#19653])
> * [#19198][_#19198]: `RgbdSensorDiscrete` and `RgbdSensorAsync` add missing ports and fail cleanly on invalid ports and values. ([#19696][_#19696])
> ```

The commit message 19696 listed 1 feature and 3 fixes as bullet points.  All four bullet points should have been independently transcribed into the release notes.
___
*[`doc/_release-notes/v1.19.0.md` line 43 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4rCiV1PtjFCmJTTHy:-N_4rCiV1PtjFCmJTTHz:b-8s73q6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L43)):*
> ```Markdown
> 
> * Add `solvers::MakeSemidefiniteRelaxation` to constructs a new MathematicalProgram which implements the SDP relaxation of the original program. ([#19632][_#19632])
> * MosekSolver can now take in convex `QuadraticConstraint`s. ([#19705][_#19705])
> ```

nit The prior two points should fall under the "New features" heading.
___
*[`doc/_release-notes/v1.19.0.md` line 55 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4rSGPDEUuKfRL2EDm:-N_4rSGPDEUuKfRL2EDn:byti56a) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L55)):*
> ```Markdown
> Fixes
> 
> * [#19657][#19657]: GurobiSolver acquires a local license at most once per process. ([#19713][_#19713])
> ```

nit The 19657 hyperlink does not render correctly.
___
*[`doc/_release-notes/v1.19.0.md` line 64 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4rcTzBiGSYOaIhcDQ:-N_4rcTzBiGSYOaIhcDR:b-rd7bnn) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L64)):*
> ```Markdown
> New features
> 
> * For `geometry::optimization::CspaceFreePolytope` subclasses, fix state dependencies for computing separating planes from kinematic chains. ([#19609][_#19609])
> ```

nit 19609: geometry/optimization changes should be filed under the "Mathematical Program" section, not "... and Geometry".

(Would you be interested in teach `relnotes.py`'s default section binning about this rule?)
___
*[`doc/_release-notes/v1.19.0.md` line 65 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4rkd96-EesFb6b29t:-N_4rkd96-EesFb6b29u:b-ragimq) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L65)):*
> ```Markdown
> 
> * For `geometry::optimization::CspaceFreePolytope` subclasses, fix state dependencies for computing separating planes from kinematic chains. ([#19609][_#19609])
> * Add Serialize to Hyperellipsoid. ([#19670][_#19670])
> ```

nit 19670: geometry/optimization changes should be filed under the "Mathematical Program" section, not "... and Geometry".
___
*[`doc/_release-notes/v1.19.0.md` line 68 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4rve44JgydbErDqRe:-N_4rve44JgydbErDqRf:b5teup8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L68)):*
> ```Markdown
> * Meshcat can handle glTF meshes. ([#19635][_#19635])
> * [#19592][_#19592]: New method `multibody::ContactResults::SelectHydroelastic` allows selecting a subset of hydroelastic ContactResults. ([#19663][_#19663])
> * `geometry::optimization::VPolytope` and `IrisInConfigurationSpace` support `geometry::Mesh` geometry. ([#19672][_#19672])
> ```

nit 19672: geometry/optimization changes should be filed under the "Mathematical Program" section, not "... and Geometry".
___
*[`doc/_release-notes/v1.19.0.md` line 70 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4s1OEAWtDsaCmgEHH:-N_4s1OEAWtDsaCmgEHI:b-1b76fm) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L70)):*
> ```Markdown
> * `geometry::optimization::VPolytope` and `IrisInConfigurationSpace` support `geometry::Mesh` geometry. ([#19672][_#19672])
> * New methods `multibody::MultibodyPlant::MakeVelocityToQDotMap` and `MakeQDotToVelocityMap`. ([#19675][_#19675])
> * Support for `num_positions != num_velocities` in DifferentialIK. ([#19522][_#19522])
> ```

nit 19522: Perhaps IK should be filed under "Planning" not "Multibody Dynamics"?
___
*[`doc/_release-notes/v1.19.0.md` line 73 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4s7G-Ej27C6lZJCWE:-N_4s7G-Ej27C6lZJCWF:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L73)):*
> ```Markdown
> * SAP solver supports joint locking. ([#18983][_#18983])
> * Add `geometry::Meshcat::GetRealtimeRate`. ([#19700][_#19700])
> * `RenderEngineGltfClient` can now accept gltf files. ([#19684][_#19684])
> ```

typo



_Suggestion:_
```Markdown
glTF
```
___
*[`doc/_release-notes/v1.19.0.md` line 74 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4sBRb45kVQYDlg0d1:-N_4sBRc1OmvTWEg9lHf:bmmwu2o) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L74)):*
> ```Markdown
> * Add `geometry::Meshcat::GetRealtimeRate`. ([#19700][_#19700])
> * `RenderEngineGltfClient` can now accept gltf files. ([#19684][_#19684])
> * A variety of fixes to the sampling and guessing logic in `IrisInConfigurationSpace`. ([#19728][_#19728])
> ```

nit 19728: geometry/optimization changes should be filed under the "Mathematical Program" section, not "... and Geometry".
___
*[`doc/_release-notes/v1.19.0.md` line 80 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4sRG-EGSK3dvzjSy-:-N_4sRG-EGSK3dvzjSy0:bn8mnxa) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L80)):*
> ```Markdown
> * Avoid copying the mesh in distance queries. ([#19679][_#19679])
> * Meshcat "realtime rate" calculation no longer shows incorrect values after pausing/resuming simulation. ([#19667][_#19667])
> * `geometry::optimization::GraphOfConvexSets` returns `kInfeasibleConstraints` when no path exists. ([#19719][_#19719])
> ```

nit 19719: geometry/optimization changes should be filed under the "Mathematical Program" section, not "... and Geometry".
___
*[`doc/_release-notes/v1.19.0.md` line 99 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4saBX2A7_s6zjj6AH:-N_4saBX2A7_s6zjj6AI:b-wznetr) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L99)):*
> ```Markdown
> 
> 
> * ([#19641][_#19641]) Fix images and formatting of _Hydroelastic Contact: Basics_ in Deepnote. ([#19660][_#19660], [#19643][_#19643])
> ```

nit Inconsistent line-opener formatting `(#19641) ...` here vs `#NNNNN: ...` elsewhere in this document.
___
*[`doc/_release-notes/v1.19.0.md` line 106 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4sojL2H_3JmLhHumV:-N_4sojL2H_3JmLhHumW:bpssnhi) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L106)):*
> ```Markdown
> 
> * InertiaVisualizer shows proper rotations. ([#19589][_#19589])
> * Add `math::SoftOverMax`, `SoftOverMin`,`SoftUnderMax`, `SoftUnderMin`. ([#19591][_#19591])
> ```

nit 19591 could plausibly be filed under the "Mathematical Program" section.
___
*[`doc/_release-notes/v1.19.0.md` line 112 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4tEy36WgLByIEAMiy:-N_4tEy36WgLByIEAMiz:bg6y876) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L112)):*
> ```Markdown
> * Avoid false self collisions in `iiwa_primitive_collision.urdf` by adding collision filters. ([#19674][_#19674])
> * Improve error message for YAML parser when parsing a non-Mapping root node. ([#19730][_#19730])
> * Warn when visualizing glTF meshes instead of crashing. ([#19692][_#19692])
> ```

nit 19692: We lost the context that this fix is for `drake_visualizer` specifically.
___
*[`doc/_release-notes/v1.19.0.md` line 121 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4t_XJ9-ASVNUD_UCY:-N_4t_XJ9-ASVNUD_UCZ:b1jij8e) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L121)):*
> ```Markdown
> New features
> 
> * `systems.CacheEntry.is_out_of_date` ([#19669][_#19669])
> ```

BTW It is not a requirement anymore to itemize the bound function names; using the general PR subject line is fine ("Bind more CacheEntry stuff") as a one-liner.

It's fine to keep this text as-is if you like it, but I wanted to at least make sure you were aware of the policy change (#18523).
___
*[`doc/_release-notes/v1.19.0.md` line 147 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4uFOB4RCGlfnfiHnG:-N_4uFOB4RCGlfnfiHnH:b88aret) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L147)):*
> ```Markdown
> * Update default Ubuntu version for Docker to be Jammy. ([#19701][_#19701])
> * Add environment variable DRAKE_PYTHON_LOGGING to disable redirection of the
>   text log. ([#19685][_#19685])
> ```

nit 19685 should be filed under "pydrake bindings", not build system.
___
*[`doc/_release-notes/v1.19.0.md` line 157 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4uqQ0621CW6xUK7in:-N_4uqQ13UZ1J5gXzFfA:b-8e75dr) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L157)):*
> ```Markdown
> ## Newly-deprecated APIs
> 
> * Use of non-convex quadratic constraints with convex solvers reject non-convex quadratic constraints. ([#19668][_#19668])
> ```

nit 19668 "use of non-convex ..." is not what's deprecated.  The pre-existing function `FindNonconvexQuadraticCost` is what's newly deprecated.
___
*[`doc/_release-notes/v1.19.0.md` line 159 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4uZuT6nW-0nl344g_:-N_4uZuU1Mp_Tt8gjSJ4:b-bq78vd) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L159)):*
> ```Markdown
> * Use of non-convex quadratic constraints with convex solvers reject non-convex quadratic constraints. ([#19668][_#19668])
> * `solvers::MinimumValueConstraint::minimum_value`. ([#19665][_#19665])
> * `geometry::optimization::CSpaceSeparatingPlane`. five-argument constructor ([#19526][_#19526])
> ```

typo punc in wrong place?



_Suggestion:_
```Markdown
`geometry::optimization::CSpaceSeparatingPlane` five-argument constructor.
```

**Comment by jwnimmer-tri** [comment]
BTW also remember to use merges, not force-push.  We want to allow other developers to push their desired edits, without everyone stepping on each other.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 36 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_4r-CG5o3h2hp3en_l:-N_4wvqQ5PmAuOw_aeEk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4660fd7d1aaa107a1287e5a31328efa907a9aaf/doc/_release-notes/v1.19.0.md#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The commit message 19696 listed 1 feature and 3 fixes as bullet points.  All four bullet points should have been independently transcribed into the release notes.
</blockquote></details>

Done.

**Comment by ggould-tri** [comment]
Apologies for the force-pushes -- my git aliases are more aggressive than they should be :-(
I don't think I've stomped any content, and am checking to be sure.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 36 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_ADH1V1D56gC0lUaC8:-N_ADH1V1D56gC0lUaC9:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/28c9827eb776f7ecdc75dbe5564288fd2836ff60/doc/_release-notes/v1.19.0.md#L36)):*
> ```Markdown
> 
> * [#19419][_#19419]: Fix a crash in `FiniteHorizonLinearQuadraticRegulator`. ([#19653][_#19653])
> * [#19198][_#19198]: `RgbdSensorDiscrete` now has a zero-order hold on its output. ([#19696][_#19696])
> ```

nit



_Suggestion:_
```Markdown
on its pose output
```
___
*[`doc/_release-notes/v1.19.0.md` line 144 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_ADcab79wofVmtMc88:-N_ADcab79wofVmtMc89:b-5d0yne) ([raw file](https://github.com/RobotLocomotion/drake/blob/28c9827eb776f7ecdc75dbe5564288fd2836ff60/doc/_release-notes/v1.19.0.md#L144)):*
> ```Markdown
> Fixes
> 
> * Fix incorrect type casting in `SortedPair<T>`; add test. ([#19753][_#19753])
> ```

nit Tests are non-notable



_Suggestion:_
```Markdown
Fix incorrect type casting in `SortedPair<T>`.
```

**Review by ggould-tri — COMMENTED** [review]
+@EricCousineau-TRI per schedule.  +(status: single reviewer ok) 
FYI @rpoyner-tri @amcastro-tri @sherm1 @hongkai-dai   please comment or amend as you like.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-:-N_EOgiFBEYSUfYAYrWX:b-jz6nk8)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-:-N_F8o-V0TWDAqH87LjX:bg7igkv)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 54 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_F8TkO5oBsxl4wPtsH:-N_F8TkO5oBsxl4wPtsI:b-w10mgt) ([raw file](https://github.com/RobotLocomotion/drake/blob/cabd5c0b4061883c83e1a85c59e4010cdb964472/doc/_release-notes/v1.19.0.md#L54)):*
> ```Markdown
> * A variety of fixes to the sampling and guessing logic in `IrisInConfigurationSpace`. ([#19728][_#19728], [#19751][_#19751])
> * `geometry::optimization::GraphOfConvexSets` returns `kInfeasibleConstraints` when no path exists. ([#19719][_#19719])
> * Add `solvers::MakeSemidefiniteRelaxation` to construct a new `MathematicalProgram` which implements the SDP relaxation of the original program. ([#19632][_#19632])
> ```

Maybe we can make it more explicit
```
which implements the SDP relaxation of the original program with non-convex quadratic constraints.
```

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 54 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_F8TkO5oBsxl4wPtsH:-N_F92xQ5WYBoWdrtHPm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cabd5c0b4061883c83e1a85c59e4010cdb964472/doc/_release-notes/v1.19.0.md#L54)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe we can make it more explicit
```
which implements the SDP relaxation of the original program with non-convex quadratic constraints.
```
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 62 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_FEg_B-fgMDcOeVLBm:-N_FEg_B-fgMDcOeVLBn:bgxjwav) ([raw file](https://github.com/RobotLocomotion/drake/blob/645672b500d532d4a11fefb804a71d7f0ff82534/doc/_release-notes/v1.19.0.md#L62)):*
> ```Markdown
> * Add new optional default options for `geometry::optimization::GraphOfConvexSets`. ([#19720][_#19720])
> * Add method `geometry::optimization::HPolyhedron::Scale()`. ([#19733][_#19733])
> * Use `BlockSparseSuperNodalSolver` in SAP solver by default. ([#19757][_#19757])
> ```

This is a Multibody Dynamics feature.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 62 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_FEg_B-fgMDcOeVLBm:-N_FFSKM-rwViXZqcYBq:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/645672b500d532d4a11fefb804a71d7f0ff82534/doc/_release-notes/v1.19.0.md#L62)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is a Multibody Dynamics feature.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Dismissed @hongkai-dai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`doc/_release-notes/v1.19.0.md` line 54 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-N_F8TkO5oBsxl4wPtsH:-N_FQbMmA1v84pG46rT0:b65n5df) ([raw file](https://github.com/RobotLocomotion/drake/blob/cabd5c0b4061883c83e1a85c59e4010cdb964472/doc/_release-notes/v1.19.0.md#L54)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am dismissing this now, since I just pasted your text in.

**Review by ggould-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19748#-:-N_FQmtI-YM0-vQFABsW:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
