### PR TITLE
[tools] Fix kcov merging

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21188)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
I didn't actually review this in detail, but I took it as a patch locally, and it worked for me.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21188#-:-Ntwz4ZY0CPjM_2_-ccJ:b2weskp)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
FYI before moving this PR forward, my goal is to do something like a 5-whys (maybe 3-whys) about how we lost this without noticing.  There are probably a few places in the code that should have screamed and halted the CI job, but didn't.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21188)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Per f2f, I'm handing this over to @rpoyner-tri to decide what to do with.  He can open a new PR as needed.

**Comment by rpoyner-tri** [comment]
This work is resuming in `drake-ci#288` and a Drake PR to be named later.

**Comment by rpoyner-tri** [comment]
Revival Drake PR is #21859.

**Pull request closed without merging**
