### PR TITLE
Fix Segmentation Fault in GraphOfConvexSets::SolveShortestPath

### PR DESCRIPTION
**Pull request by cohnt**
Suppose one solves a GCS problem using the relax-and-round strategy. If the relaxation is feasible (or at least, not shown to be infeasible by the solver, which I have caused in practice by using loose tolerances), but the mixed-integer problem is indeed infeasible, then there is a bug in the rounding procedure causing a segfault (or various other memory errors), due to running out of feasible paths.

It has a `DRAKE_ASSERT`, but this will not help someone using a release build. (Indeed, I found the bug by accident, and it took quite a while to both identify what I was doing wrong, and where in Drake the problem was even coming from.) I've added an informative error message, and a test case exposing this bug.

Tagging with priority high since this can segfault and it's on drake master.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-:-O0kospc7Qo9ayrPSueK:b1ikduc)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kous79s6CNM-BnP3Q:-O0kous79s6CNM-BnP3R:bel0mwp) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/graph_of_convex_sets.cc#L1329)):*
> ```cpp
>                 "result.is_success() is true. This could be due to tighter "
>                 "constraint tolerances on the rounding solution than the "
>                 "relaxation solution.");
> ```

let's resolve the discussion in slack to make sure we're happy with the explanation message.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 2841 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kp33eE9Ve72YS1d_Z:-O0kp33eE9Ve72YS1d__:bchhgjq) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/test/graph_of_convex_sets_test.cc#L2841)):*
> ```cpp
> }
> 
> GTEST_TEST(ShortestPathTest, InaccurateRelaxationSolve) {
> ```

perhaps we can also get an example that doesn't require solver tolerance games to make it happen? (again, discussing in slack)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kous79s6CNM-BnP3Q:-O0kpr1E4hB3825Ze9rs:b-6948m5) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/graph_of_convex_sets.cc#L1329)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

let's resolve the discussion in slack to make sure we're happy with the explanation message.
</blockquote></details>

Even once we agree on the explanation, i think we need a more helpful message for the user. Something like

"GCS rounding failed. The convex relaxation has a feasible solution, but there are (definitely) no integer-feasible solutions to the GCS problem. You can set options.max_rounded_paths=0 to disable rounding and return the solution to the relaxation instead."

**Review by RussTedrake — COMMENTED** [review]
:lgtm: thanks for bearing with me while I understood. i think the test is good. wdyt about my suggested error message?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-:-O0q78cl9Y1TCz5FQ7Nq:bk0gtqb)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kous79s6CNM-BnP3Q:-O0q66ceB-Q8JTPlJIYM:b-uo0ore) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/graph_of_convex_sets.cc#L1329)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Even once we agree on the explanation, i think we need a more helpful message for the user. Something like

"GCS rounding failed. The convex relaxation has a feasible solution, but there are (definitely) no integer-feasible solutions to the GCS problem. You can set options.max_rounded_paths=0 to disable rounding and return the solution to the relaxation instead."
</blockquote></details>

Based on our discussion, how about

"GCS rounding failed. The convex relaxation returned a feasible solution, but there is (definitely) no path from the source to the target using only edges with flows > options.flow_tolerance. You can set options.max\_rounded\_paths=0 to disable rounding and return the solution to the relaxation instead."

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1329 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kous79s6CNM-BnP3Q:-O0tHmNw7MeQfJ-MCU4t:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/graph_of_convex_sets.cc#L1329)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Based on our discussion, how about

"GCS rounding failed. The convex relaxation returned a feasible solution, but there is (definitely) no path from the source to the target using only edges with flows > options.flow_tolerance. You can set options.max\_rounded\_paths=0 to disable rounding and return the solution to the relaxation instead."
</blockquote></details>

Done.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 2841 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kp33eE9Ve72YS1d_Z:-O0tHj2g-U0Z-Nslr7XL:bh7rcf4) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/test/graph_of_convex_sets_test.cc#L2841)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

perhaps we can also get an example that doesn't require solver tolerance games to make it happen? (again, discussing in slack)
</blockquote></details>

Assuming you're okay with the tolerance games then?

**Review by RussTedrake — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-:-O12dmoLBzryGmO3sMQ2:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 2841 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-O0kp33eE9Ve72YS1d_Z:-O12ddLX-JSxRpyF7gQW:bwmxd4v) ([raw file](https://github.com/RobotLocomotion/drake/blob/0556c7f59949c52c0bb2367b0b76c20f0ed11309/geometry/optimization/test/graph_of_convex_sets_test.cc#L2841)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Assuming you're okay with the tolerance games then?
</blockquote></details>

Yes. It's not ideal, but i understand now that it's fundamental to hitting the error.

**Review by RussTedrake — COMMENTED** [review]
Change of plans.  We're going to close this in favor of #21402.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21662#-:-O138KI0D36vi_jWf6TZ:b-y61gub)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Pull request closed without merging**
