### PR TITLE
Use --strict_system_includes for bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is helpful / required for caching to be safe.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8223)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all review, please.

Internal to TRI this has only caught one problem (for an external that Drake doesn't happen to use), so its unlikely to be terribly noisy but should help ensure things are slightly more correct for caching.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8223#-:-L6wbxPOhQfZK4iqKxZW:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
The macOS errors seem to _only_ be the known XML flake; merging.

**Pull request merged**
