### PR TITLE
mujoco parser assigns unique names to default geometries

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously, we failed when parsing https://github.com/google-deepmind/mujoco_menagerie/blob/d1e7d678c986788c8597e88111b4d94f000cf31e/aloha/scene.xml with a message of the form "already has a geometry named geom0".

+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-:-NravxJ11okexmo66VKp:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 906 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-Nravixi7SbopLdgAyK4:-Nravixi7SbopLdgAyK5:baf7vqk) ([raw file](https://github.com/RobotLocomotion/drake/blob/d9f948b561a97033271986033262e70a1afd7a17/multibody/parsing/detail_mujoco_parser.cc#L906)):*
> ```cpp
>   void ParseWorldBody(XMLElement* node) {
>     if (plant_->geometry_source_is_registered()) {
>       std::vector<MujocoGeometry> geometries;
> ```

nit consider replacing this vector with just an integer count of successfully added geometries. I don't see that it gets used for anything other than the `.size()` call here.

**Review by RussTedrake — COMMENTED** [review]
+sherm1 for platform review, pretty please?  This one didn't get pushed forward today, and Rico is the on-call for tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-:-NrcVTd51h1vAbciP-Vr:b-jl50r5)* status: needs at least two assigned reviewers

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 906 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-Nravixi7SbopLdgAyK4:-NrcVL3T7uNNf0iHqjOS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d9f948b561a97033271986033262e70a1afd7a17/multibody/parsing/detail_mujoco_parser.cc#L906)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider replacing this vector with just an integer count of successfully added geometries. I don't see that it gets used for anything other than the `.size()` call here.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for platform review, please?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-:-NrcVf_U6XOas4LwC6D5:bppyor7)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one nit

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-:-Nrf_cjb9KhxF6t-H-WU:b-8gq7ov)* status: 1 unresolved discussion

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 920 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21045#-Nrf_Hvf6opYJyjsuKxI:-Nrf_Hvg1PQ9h2Q8ZvHn:b-vic2gt) ([raw file](https://github.com/RobotLocomotion/drake/blob/75787cfcef1ba3c52c24e97659a2995e478d7418/multibody/parsing/detail_mujoco_parser.cc#L920)):*
> ```cpp
>                                             geom.friction);
>         }
>         num_geometries++;
> ```

nit: per [styleguide](https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement) prefer prefix `++num_geometries`

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045)* status: 1 unresolved discussion

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21045)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
