### PR TITLE
Remove hooks, packaging, and tools from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6443)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-KnjOnofTYrjEBsZKpOo:-KnjOnogYRy2vtNXTatj:b-4d4la3) (no related file):*
It seems like `Continuous Production` still contains some tool variants that are being removed here.  Or maybe I'm misreading?

---

*[cmake/test.cmake, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-KnjNCloqinPi12BTnJ7:-KnjNCloqinPi12BTnJ8:b-xnpulr) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/cmake/test.cmake#L89)):*
> ```CMake
>       set_tests_properties(${_NAME} PROPERTIES
>         ENVIRONMENT "${TESTS_ENVIRONMENT}")
>     endif()
> ```

FYI I don't understand what this relates to or why it's disappearing.  Is there a second pair of eyes from Kitware that could sanity-check this?

---

*[cmake/git/hooks.cmake, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-KnjNWkBYnX0NBEMxHYn:-KnjNWkCpkAhZRgstmFU:b-qbidpr) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/cmake/git/hooks.cmake#L32)):*
> ```CMake
>   endif()
> 
>   # Install the hook launcher, but replace an existing launcher
> ```

BTW Is there any  way we can help the user remove the now-irrelevant hook, either through code, documentation, or one-time announcement?  (Or maybe it doesn't hatter?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-:-KnjOwIA8Fz9jkRFy27i:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-KnjOnofTYrjEBsZKpOo:-KnjURnCtNrq19Vhcjda:bynaoee) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like `Continuous Production` still contains some tool variants that are being removed here.  Or maybe I'm misreading?
</blockquote></details>

No, these were only ever local developer tools. CI uses `ctest_memcheck()`.

---

*[cmake/test.cmake, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-KnjNCloqinPi12BTnJ7:-KnjUcLkT-e3tOk3xDe8:b-dvzzjp) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/cmake/test.cmake#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I don't understand what this relates to or why it's disappearing.  Is there a second pair of eyes from Kitware that could sanity-check this?
</blockquote></details>

The only environment variables that were ever set were *SAN_OPTIONS: https://github.com/RobotLocomotion/drake/commit/7b0c00ab39b357ed0fce650e56d8372bec037dd3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6443)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/git/hooks.cmake, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-KnjNWkBYnX0NBEMxHYn:-KnjV_csONACYH_Os_qx:bvuqneg) ([raw file](https://github.com/robotlocomotion/drake/blob/2e63cdd7af5072a025e58f1dfe0f6ae00b4939ff/cmake/git/hooks.cmake#L32)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there any  way we can help the user remove the now-irrelevant hook, either through code, documentation, or one-time announcement?  (Or maybe it doesn't hatter?)
</blockquote></details>

It is basically a no-op now. All the hook did was check for a file in the repo and then exec it if it existed. Now that file is gone. I can say something on Slack for people that want a clear hooks dir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6443)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6443#-:-KnjeeiCYPDn8lt7CJBI:bnfp4nl)*

**Pull request merged**
