### PR TITLE
Add OpenCL support

### PR DESCRIPTION
**Pull request by calderpg-tri**
Adds OpenCL build support, and enables the OpenCL backend implementation in `voxelized_geometry_tools`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
Tested locally on 18.04 and Big Sur, OpenCL backend works on both.

Note that at least on my Mac Mini + Big Sur, Apple provides two OpenCL devices, the CPU and GPU, in that order.

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
In service of #14431, adds OpenCL support following the pattern of `tools/workspace/opengl`. Unprovisioned and Mac CI passes.

+@jamiesnape for feature review, thanks!

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by calderpg-tri** [comment]
I've changed the location of `cl.hpp` in `voxelized_geometry_tools` to use the normal catkin/ament include path to make redistribution there work as well.

cc @EricCousineau-TRI

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)* status: 6 unresolved discussions, LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri and @jamiesnape)

___
*[setup/ubuntu/binary_distribution/packages-bionic.txt, line 47 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCt0c6Eei00t_2vw2S:-MXCt0c6Eei00t_2vw2T:bslwzhb) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/binary_distribution/packages-bionic.txt#L47)):*
> ```vimhelp
> libxt6
> libyaml-cpp-dev
> ocl-icd-opencl-dev
> ```

`ocl-icd-libopencl1`?
___
*[setup/ubuntu/binary_distribution/packages-focal.txt, line 47 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCtFgh2nYfktxvINiH:-MXCtFgh2nYfktxvINiI:bx8157) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/binary_distribution/packages-focal.txt#L47)):*
> ```vimhelp
> libxt6
> libyaml-cpp-dev
> ocl-icd-opencl-dev
> ```

`ocl-icd-libopencl1`?
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 32 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCtOdzD1roMibhFJmR:-MXCtOdzD1roMibhFJmS:b-q8gbr0) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/source_distribution/packages-bionic.txt#L32)):*
> ```vimhelp
> libtool
> libx11-dev
> opencl-headers
> ```

and `ocl-icd-opencl-dev`?
___
*[setup/ubuntu/source_distribution/packages-focal.txt, line 34 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCtVSeDOTfo-vnA6Rb:-MXCtVSeDOTfo-vnA6Rc:b-q8gbr0) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/source_distribution/packages-focal.txt#L34)):*
> ```vimhelp
> libtool
> libx11-dev
> opencl-headers
> ```

and `ocl-icd-opencl-dev`?
___
*[tools/workspace/opencl/package-macos.BUILD.bazel, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCvA7KDqZtpAxgXN9A:-MXCvA7KDqZtpAxgXN9B:b-8ddsuf) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/tools/workspace/opencl/package-macos.BUILD.bazel#L3)):*
> ```
> # -*- python -*-
> 
> licenses(["permissive"])  # OpenCL license
> ```

I make the license `BSD-2-Clause AND Expat`
___
*[tools/workspace/opencl/package-ubuntu.BUILD.bazel, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCu8l_C9H8Q8QFg7rg:-MXCu8l_C9H8Q8QFg7rh:b-8ddsuf) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/tools/workspace/opencl/package-ubuntu.BUILD.bazel#L3)):*
> ```
> # -*- python -*-
> 
> licenses(["permissive"])  # OpenCL license
> ```

I make the license `BSD-2-Clause AND Expat`

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)* status: 6 unresolved discussions, LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jamiesnape)

___
*[setup/ubuntu/binary_distribution/packages-bionic.txt, line 47 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCt0c6Eei00t_2vw2S:-MXCy5t3EMDZcbo-8-X1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/binary_distribution/packages-bionic.txt#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`ocl-icd-libopencl1`?
</blockquote></details>

Done.
___
*[setup/ubuntu/binary_distribution/packages-focal.txt, line 47 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCtFgh2nYfktxvINiH:-MXCy6SZ9hvZjYraU7ak:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/binary_distribution/packages-focal.txt#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`ocl-icd-libopencl1`?
</blockquote></details>

Done.
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 32 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCtOdzD1roMibhFJmR:-MXCy78S-ZS5D12Qrltc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/source_distribution/packages-bionic.txt#L32)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

and `ocl-icd-opencl-dev`?
</blockquote></details>

Done.
___
*[setup/ubuntu/source_distribution/packages-focal.txt, line 34 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCtVSeDOTfo-vnA6Rb:-MXCy8ms3kjiFEXuxSg2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/setup/ubuntu/source_distribution/packages-focal.txt#L34)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

and `ocl-icd-opencl-dev`?
</blockquote></details>

Done.
___
*[tools/workspace/opencl/package-macos.BUILD.bazel, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCvA7KDqZtpAxgXN9A:-MXCyBvlAV-IYNWuGUdP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/tools/workspace/opencl/package-macos.BUILD.bazel#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I make the license `BSD-2-Clause AND Expat`
</blockquote></details>

Done.
___
*[tools/workspace/opencl/package-ubuntu.BUILD.bazel, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXCu8l_C9H8Q8QFg7rg:-MXCyCOC3-sUyNdF-USB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2abe91f11c927c24e71ebb131f7d138c3ac0d96f/tools/workspace/opencl/package-ubuntu.BUILD.bazel#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I make the license `BSD-2-Clause AND Expat`
</blockquote></details>

Done.

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
For the record, adding OpenCL as a dependency here is uncontroversial because it's only being used by tests.  Before using it as part of production code (libdrake & our installed images) in the future, we'll need to ensure that has no deleterious effects in cases where the Drake user is not invoking any features that use it, e.g., that there are no linking conflicts with other versions in the robotics ecosystem, and that the library does not have any global constructors that effect things even without it being called.  I suspect the chance of any problems there are low (compared with, e.g., OpenMP), but a quick sanity check probably is still worthwhile.  (If it does have downsides, we might need the option to disable it.)

**Comment by EricCousineau-TRI** [comment]
> [...] but a quick sanity check probably is still worthwhile. (If it does have downsides, we might need the option to disable it.)

Perhaps OpenCV should be part of the checklist? (From brief investigations here, I think it enables it by default; dunno about static vs. dynamic linking: [repro/.../opencv_cvtcolor_slow](https://github.com/EricCousineau-TRI/repro/tree/d578c0e551/bug/opencv_cvtcolor_slow))

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 1 of 5 files at r4, 2 of 2 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843#-:-MXI5lyp8tU-TK_zQdpU:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 7 files at r1, 1 of 5 files at r4, 2 of 2 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843#-:-MXIEoyu5CpZgfIXcfFo:b-vtj4vo)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[tools/workspace/opencl/repository.bzl, line 35 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXIG1kq3__Uiv-OHzXY:-MXIG1kq3__Uiv-OHzXZ:b-bxcf26) ([raw file](https://github.com/robotlocomotion/drake/blob/46a146e2f150903b94636f133967dcb491e9171e/tools/workspace/opencl/repository.bzl#L35)):*
> ```Starlark
> opencl_repository = repository_rule(
>     local = True,
>     configure = True,
> ```

nit This rule doesn't actually change its behavior upon reconfigure -- it's doing the same thing every time, without searching.  Thus, we don't need `configure = True`.
___
*[tools/workspace/voxelized_geometry_tools/package.BUILD.bazel, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXIF64CBH7Xq8_BTlB4:-MXIF64CBH7Xq8_BTlB5:b1omupd) ([raw file](https://github.com/robotlocomotion/drake/blob/46a146e2f150903b94636f133967dcb491e9171e/tools/workspace/voxelized_geometry_tools/package.BUILD.bazel#L8)):*
> ```
> cc_library(
>     name = "cl_hpp",
>     hdrs = ["include/voxelized_geometry_tools/cl.hpp"],
> ```

nit This file is "Copyright (c) 2008-2015 The Khronos Group Inc." with a notice requirement in the license text.  We will need to install that notice, once we start using vgt in production code.

Maybe add a TODO reminder?

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri and @jwnimmer-tri)

___
*[tools/workspace/opencl/repository.bzl, line 35 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXIG1kq3__Uiv-OHzXY:-MXIeRPM9MuHXnqdELUt:bkv582v) ([raw file](https://github.com/robotlocomotion/drake/blob/46a146e2f150903b94636f133967dcb491e9171e/tools/workspace/opencl/repository.bzl#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This rule doesn't actually change its behavior upon reconfigure -- it's doing the same thing every time, without searching.  Thus, we don't need `configure = True`.
</blockquote></details>

So I understand, is there something different going on here versus OpenGL such that `opencl_repository` doesn't need `configure = True` but `opengl_repository` does? (Or do neither, and I can/should get rid of it in both locations?)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[tools/workspace/opencl/repository.bzl, line 35 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXIG1kq3__Uiv-OHzXY:-MXIgWQRARy8OwM75Gm9:brbm99t) ([raw file](https://github.com/robotlocomotion/drake/blob/46a146e2f150903b94636f133967dcb491e9171e/tools/workspace/opencl/repository.bzl#L35)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

So I understand, is there something different going on here versus OpenGL such that `opencl_repository` doesn't need `configure = True` but `opengl_repository` does? (Or do neither, and I can/should get rid of it in both locations?)
</blockquote></details>

A prior revision of the OpenGL repository rule used `setup_pkg_config_repository`, in which case `configure = True` was correct.  When 86c2795 moved away from pkg-config, it left the configure in place, which was an oversight.  The current OpenGL rule should not have `configure = True` either.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jamiesnape and @jwnimmer-tri)

___
*[tools/workspace/opencl/repository.bzl, line 35 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXIG1kq3__Uiv-OHzXY:-MXIi_gaC4WUD8ez-9xf:ba3dfob) ([raw file](https://github.com/robotlocomotion/drake/blob/46a146e2f150903b94636f133967dcb491e9171e/tools/workspace/opencl/repository.bzl#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

A prior revision of the OpenGL repository rule used `setup_pkg_config_repository`, in which case `configure = True` was correct.  When 86c2795 moved away from pkg-config, it left the configure in place, which was an oversight.  The current OpenGL rule should not have `configure = True` either.
</blockquote></details>

Removed
___
*[tools/workspace/voxelized_geometry_tools/package.BUILD.bazel, line 8 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14843#-MXIF64CBH7Xq8_BTlB4:-MXIigin6jGmMFEScvMS:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/46a146e2f150903b94636f133967dcb491e9171e/tools/workspace/voxelized_geometry_tools/package.BUILD.bazel#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This file is "Copyright (c) 2008-2015 The Khronos Group Inc." with a notice requirement in the license text.  We will need to install that notice, once we start using vgt in production code.

Maybe add a TODO reminder?
</blockquote></details>

Done

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14843)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Comment by calderpg-tri** [comment]
@jamiesnape Can you update the provisioned CI instances please? Thanks!

**Comment by jamiesnape** [comment]
Yes, please create an issue and assign it to me.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
