### PR TITLE
Revert "[visualization] Add sliders for geometry alpha in MeshcatVisu…

### PR DESCRIPTION
**Pull request by rpoyner-tri**
…alizer (#18454)"

This reverts commit 60f7b0d97207dd96ad36e32b1963e1dd40c5586b.

This patch introduced a breaking change, and needs to be reconsidered.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18463)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) +@ericcousineau-tri for both reviews.
FYI @trowell-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18463#-:-NJLLYJF90Bk3su7m3Ul:b3qg21y)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Confirmed discussion and implications of breaking change:
https://github.com/RobotLocomotion/drake/pull/18454#issuecomment-1352909287

:lgtm: in that light, thanks!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18463#-:-NJLM32W0rweawUUD_6P:b-8rtwov)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

**Review by trowell-tri — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18463#-:-NJLMJbO8Nl2tAl8pfzo:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

**Review by trowell-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18463)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

**Pull request merged**
