### PR TITLE
Change SolverOptions to SolverId not SolverType

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6515)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature review, please.

**Comment by sammy-tri** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1992 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6515#-KoNElqM58N0jI5zaje3:-KoNElqN-ejQpZB5sshU:b7zhnzs) ([raw file](https://github.com/robotlocomotion/drake/blob/dda02b92e7ffdc8c2640e2a525f1d360dc5d2535/drake/solvers/mathematical_program.h#L1992)):*
> ```objc
>    * https://www.gurobi.com/documentation/6.5/refman/parameters.html
>    */
>   void SetSolverOption(SolverId solver_id, const std::string& solver_option,
> ```

It seems odd that there's a string passed by reference next to a struct which contains a string being passed by value.  Any reason we shouldn't make both const ref?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6515)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1992 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6515#-KoNElqM58N0jI5zaje3:-KoNHOgMaanLenb4Mw18:bbzj6un) ([raw file](https://github.com/robotlocomotion/drake/blob/dda02b92e7ffdc8c2640e2a525f1d360dc5d2535/drake/solvers/mathematical_program.h#L1992)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems odd that there's a string passed by reference next to a struct which contains a string being passed by value.  Any reason we shouldn't make both const ref?
</blockquote></details>

Done.

Good catch; it was a search-replace oversight.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6515)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6515#-:-KoNI5M9lN_8Gi9B-Tz0:bxwr5c8)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6515#-:-KoNK9cZjefSTxjIR_QX:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6515#-:-KoTbeMVdIFx46MbAvca:bnfp4nl)*

**Pull request merged**
