### PR TITLE
Add transmorgification to RotationMatrix class

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7722)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@seancurtis-tri 
Platform review +@sherm1 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-:-L2SvOvany3R7ZRdEQer:b-tsw22x)*

**Comment by SeanCurtis-TRI** [comment]
First pass done. PTAL.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VjkD9LjQKlRIOc_BF:-L2VjkD9LjQKlRIOc_BG:b1b3rx8) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L216)):*
> ```cpp
> 
> // Test transmogrification of a RotationMatrix from AutoDiffXd to double.
> GTEST_TEST(RotationMatrix, TransmogrifyA) {
> ```

BTW The test name "TransmogrifyA" doesn't tell much. (Similarly for "TransmogrifyB" below).

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VjvH6XwZIEqvv_Ju9:-L2VjvH6XwZIEqvv_JuA:b-csdj3f) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L218)):*
> ```cpp
> GTEST_TEST(RotationMatrix, TransmogrifyA) {
>   const RotationMatrix<AutoDiffXd> I_autodiff =
>       RotationMatrix<AutoDiffXd>::Identity();
> ```

I'd rather see a *non*-identity matrix get pushed through. Particularly in light of the fact that the default constructor initializes to the identity matrix. This test lacks sufficient discriminating power between a proper conversion and a default construction. (Same below).

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VkeqSiAXOIHksCthk:-L2VkeqSiAXOIHksCthl:b-jgz2xr) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L233)):*
> ```cpp
> 
> // Test transmogrification of a RotationMatrix from double to AutoDiffXd.
> GTEST_TEST(RotationMatrix, TransmogrifyB) {
> ```

Given test C below, what's the value of this test? What does this give us that the next test doesn't implicitly cover?

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VkMIhqdJRj_wO6Lfi:-L2VkMIhqdJRj_wO6Lfj:blxkum4) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L243)):*
> ```cpp
>       const double mij_double = m_double(i, j);
>       const AutoDiffXd mij_autodiff = m_autodiff(i, j);
>       EXPECT_EQ(mij_double, mij_autodiff.value());
> ```

FYI The semantics of `EXPECT_EQ` has the value *being* tested first and the reference value second. You've copied and pasted this from the previous tests without having reversed the arguments.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VkXV1dHQ9FAC2Bad6:-L2VkXV1dHQ9FAC2Bad7:bu38c0z) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L248)):*
> ```cpp
> }
> 
> // Test transmogrification of a RotationMatrix from double to AutoDiffXd.
> ```

Same exact comment as test "B".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-:-L2Vknda29tUKYwDhcdG:b-1tzs3z)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VxfMRYliWpfLYCF6I:-L2VxfMRYliWpfLYCF6J:b-wigxp3) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/rotation_matrix.h#L61)):*
> ```objc
>   /// @param[in] source a %RotationMatrix templatized on scalar type U.
>   template <typename U>
>   RotationMatrix(const RotationMatrix<U>& source) {
> ```

BTW I think it would be worth adding a note and warning:
- Note: this is not used as a copy constructor; if T and U are the same type then the default copy constructor is used instead.
- Note: type U must have an available numerical value.
- Warning: only the numerical value of the source object is preserved. For example, if T and U are two different AutoDiffScalar types, none of the derivative values in `source` are preserved in the new RotationMatrix.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VkMIhqdJRj_wO6Lfi:-L2Vzcmwv3ml1OE92MTu:b-nzkxss) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L243)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI The semantics of `EXPECT_EQ` has the value *being* tested first and the reference value second. You've copied and pasted this from the previous tests without having reversed the arguments.
</blockquote></details>

FYI Could be a good use for the `dut` (device under test) convention?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*
<!-- Sent from Reviewable.io -->

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VxfMRYliWpfLYCF6I:-L2X1-I_GVvQaM5gRlcG:b8q3dhq) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/rotation_matrix.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I think it would be worth adding a note and warning:
- Note: this is not used as a copy constructor; if T and U are the same type then the default copy constructor is used instead.
- Note: type U must have an available numerical value.
- Warning: only the numerical value of the source object is preserved. For example, if T and U are two different AutoDiffScalar types, none of the derivative values in `source` are preserved in the new RotationMatrix.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
</blockquote></details>

BTW I'm not sure how meaningful the first note is. It feels like telling people not to think about elephants. Any attempt to "use this as a copy constructor", calls the copy constructor. There's no action the end user *can* take to use this as a copy constructor for which they'll get an unexpected result.

But I'm 100% on board with the other suggestions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*
<!-- Sent from Reviewable.io -->

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VxfMRYliWpfLYCF6I:-L2XULiseEbLq4M5Qwu2:b-3k4ubs) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/rotation_matrix.h#L61)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm not sure how meaningful the first note is. It feels like telling people not to think about elephants. Any attempt to "use this as a copy constructor", calls the copy constructor. There's no action the end user *can* take to use this as a copy constructor for which they'll get an unexpected result.

But I'm 100% on board with the other suggestions.
</blockquote></details>

BTW good point. Per f2f with Sean: a better note would be something like:
- Note: although _this_ method preserves only values, there is _also_ a fully-functional copy constructor, invoked when T==U, and that of course preserves everything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*

**Comment by mitiguy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 218 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VjvH6XwZIEqvv_Ju9:-L30Bc1k7O9t3tHee5cU:bm6vtnq) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L218)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd rather see a *non*-identity matrix get pushed through. Particularly in light of the fact that the default constructor initializes to the identity matrix. This test lacks sufficient discriminating power between a proper conversion and a default construction. (Same below).
</blockquote></details>

Done.  Single test was generalized, other tests were removed.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VkeqSiAXOIHksCthk:-L30Bf0OrgZ6A9Pjl9xf:bm6vtnq) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L233)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Given test C below, what's the value of this test? What does this give us that the next test doesn't implicitly cover?
</blockquote></details>

Done.  Single test was generalized, other tests were removed.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 248 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L2VkXV1dHQ9FAC2Bad6:-L30DDiAQJnrH15MBZ_w:bm6vtnq) ([raw file](https://github.com/robotlocomotion/drake/blob/5818643afd598b487c87cc9120dc6b3670f3051e/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L248)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Same exact comment as test "B".
</blockquote></details>

Done.  Single test was generalized, other tests were removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*

**Comment by sherm1** [comment]
+@amcastro-tri for feature review -@SeanCurtis-TRI 

Alejandro, Paul modeled this after your cast() methods per our discussion.

Platform review: :lgtm: with a few BTWs.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L30d4G81wW6NK4Dub5M:-L30d4G81wW6NK4Dub5N:buysch6) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f426963a05ff023833b2802461a7812f3c46f/multibody/multibody_tree/math/rotation_matrix.h#L57)):*
> ```objc
>   /// ```
>   /// RotationMatrix<double> source = RotationMatrix::Identity();
>   /// RotationMatrix<AutoDiffXd> Fred = source.cast<AutoDiffXd>();
> ```

BTW Fred -> fred (not a class)

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 240 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L30dKpLAiTzM3_SAeLr:-L30dKpLAiTzM3_SAeLs:blzof06) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f426963a05ff023833b2802461a7812f3c46f/multibody/multibody_tree/math/rotation_matrix.h#L240)):*
> ```objc
>   // %RotationMatrix templatized on any other typename T.
>   // This is needed for the method RotationMatrix<T>::cast<U>() to be able to
>   // use the private constructor RotationMatrix<T>(const Eigen::MatrixBase&)
> ```

BTW this isn't the right signature for the private constructor, which has a second parameter. Consider saying just: "This is needed for the transmogrifying cast() method to be able to use the necessary private constructor." (If anyone cares they will be able to look around to get the details.)

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L30dnrIkveHvwNKL-H5:-L30dnrIkveHvwNKL-H6:bqpqlpv) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f426963a05ff023833b2802461a7812f3c46f/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L18)):*
> ```cpp
> // templated on double is exactly equal to the corresponding elements of a
> // Matrix3 templated on AutoDiffXd.
> void ExpectEqualMatrix3TemplatedOnAutoDiffXdAndDouble(
> ```

BTW can't you just do this by comparing `m_autodiff.cast<double>()` with `m_double` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-:-L30ceTCScnGlv_BqS_r:b-a3baq5)*

**Comment by mitiguy** [comment]
Ready for re-review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-:-L30slDSEUULT0Qe1MM2:bf8hsj9)*

**Comment by sherm1** [comment]
All good -- just waiting for @amcastro-tri's review (small PR, Alejandro).

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-:-L31PY3abmVAIFm25qjY:bhqam3z)*

**Comment by amcastro-tri** [comment]
:lgtm:, just some minor BTW's.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33fhlp5eLP-tW7x9ul:-L33fhlp5eLP-tW7x9um:b-psckt8) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/rotation_matrix.h#L56)):*
> ```objc
>   /// %RotationMatrix templatized on scalar type T.  For example,
>   /// ```
>   /// RotationMatrix<double> source = RotationMatrix::Identity();
> ```

sry, I've been using `@code` for code examples with nice results in Doxygen (see example [here](http://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_tree.html#a6be0be8d01ed09d7a22b2e2e15c74114)). Just double checking, does this render ok?

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33gAGV-34x4nBSbXgd:-L33gAGV-34x4nBSbXge:b5isi1d) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/rotation_matrix.h#L56)):*
> ```objc
>   /// %RotationMatrix templatized on scalar type T.  For example,
>   /// ```
>   /// RotationMatrix<double> source = RotationMatrix::Identity();
> ```

BTW `RotationMatrix::` --> `RotationMatrix<double>::`

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33gZitTOLfDSiqRtiT:-L33gZitTOLfDSiqRtiU:b-grrw0w) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/rotation_matrix.h#L61)):*
> ```objc
>   /// @tparam U Scalar type on which the returned %RotationMatrix is templated.
>   /// @note This cast works in accordance with Eigen's cast method for the
>   /// %Matrix3 that underlies this %RotationMatrix.  For example, Eigen
> ```

BTW I don't know if I like blaming Eigen for this. The documentation should reflect that the cast only works if it does make sense. Casting from `AutoDiff` to `double` does not make sense unless you are willing to loose the derivatives information. Not super strong on how I did it in the past but I do believe we'd like to keep them consistent with [SpatialInertia](https://github.com/RobotLocomotion/drake/blob/master/multibody/multibody_tree/spatial_inertia.h#L162) and also `RotationalInertia`. I believe we'd like all the `cast() ` methods to have homogeneous signature and documentation to avoid user's frustration (I am ok if you decide modifying those is best that modifying this one)

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 64 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33hPtSFQUuUNUWCtGY:-L33hPtSFQUuUNUWCtGZ:bxdqfpg) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/rotation_matrix.h#L64)):*
> ```objc
>   /// currently allows cast from type double to AutoDiffXd, but not vice-versa.
>   template <typename U>
>   RotationMatrix<U> cast() const {
> ```

BTW, again for consistency with previously merged code, we might like to use `To` and `From` as [in here](https://github.com/RobotLocomotion/drake/blob/master/multibody/multibody_tree/spatial_inertia.h#L162)?
Whichever convention we decide to use I believe we'd like to keep consistency for users.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33doPn4_Ylv2CYZ4ay:-L33doPn4_Ylv2CYZ4az:bwe9mzq) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L20)):*
> ```cpp
> // q1, q2, q3, as these matrices are used in conjunction with MotionGenesis
> // pre-computed solutions based on these exact matrices.
> Matrix3d GetRotationMatrixBodyXYZ() {
> ```

BTW, just to be consistent with other namings out there in Drake, maybe use verb `MakeXXX` instead of `GetXXX`. We tipcally reserve the verb `get` for simple getters, while verb `Make` does allude to actually creating a new object.

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 247 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33fH0TQw1I5XHbnlsp:-L33fH0TQw1I5XHbnlsq:b-3j3fd9) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L247)):*
> ```cpp
>     for (int j = 0; j < 3; j++) {
>       const double mij_double = m_double(i, j);
>       const AutoDiffXd mij_autodiff = m_autodiff(i, j);
> ```

BTW `const AutoDiffXd&`

---

*[multibody/multibody_tree/math/test/rotation_matrix_test.cc, line 248 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33f1vY8bbTVr1MhOnH:-L33f1vY8bbTVr1MhOnI:b-fmzgle) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/test/rotation_matrix_test.cc#L248)):*
> ```cpp
>       const double mij_double = m_double(i, j);
>       const AutoDiffXd mij_autodiff = m_autodiff(i, j);
>       EXPECT_EQ(mij_autodiff.value(), mij_double);
> ```

BTW, also `EXPECT_TRUE(mij_autodiff.derivs().size() == 0);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-:-L33hk0ds0xYaP3-bfAc:b-l3c1gb)*

**Comment by mitiguy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33fhlp5eLP-tW7x9ul:-L34aE0Mv2tdYr4KSBLQ:b-rsniuv) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/rotation_matrix.h#L56)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sry, I've been using `@code` for code examples with nice results in Doxygen (see example [here](http://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_tree.html#a6be0be8d01ed09d7a22b2e2e15c74114)). Just double checking, does this render ok?
</blockquote></details>

Done.  Sean Curtis alerted me to this nice Doxygent feature for examples.
Yes - this provides nice documentation (I checked Doxygen and it looks fine).

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 61 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7722#-L33gZitTOLfDSiqRtiT:-L34rco122PZN319bK9a:b-pqhoer) ([raw file](https://github.com/robotlocomotion/drake/blob/4065d54d9fae3fd09aa0cee1d7cc9b112b981328/multibody/multibody_tree/math/rotation_matrix.h#L61)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW I don't know if I like blaming Eigen for this. The documentation should reflect that the cast only works if it does make sense. Casting from `AutoDiff` to `double` does not make sense unless you are willing to loose the derivatives information. Not super strong on how I did it in the past but I do believe we'd like to keep them consistent with [SpatialInertia](https://github.com/RobotLocomotion/drake/blob/master/multibody/multibody_tree/spatial_inertia.h#L162) and also `RotationalInertia`. I believe we'd like all the `cast() ` methods to have homogeneous signature and documentation to avoid user's frustration (I am ok if you decide modifying those is best that modifying this one)
</blockquote></details>

Done.  Talked to Sherm.  I like the reference to Eigen (in case Eigen was to change how it functioned).
Per your request, I changed documentation for SpatiallInertia and RotationalInertia to match RotationMatrix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*

**Comment by amcastro-tri** [comment]
Reviewed 3 of 4 files at r4.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7722)*

**Pull request merged**
