### PR TITLE
Suppress memcheck when VTK file reader compares header line with garbage

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Fixed nightly CI problems found in 
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-clang-bazel-nightly-everything-valgrind-memcheck/209/

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17863)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17863#-:-NBP9EnMDb4yXm82M_xn:b-z97laq)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17863)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @DamrongGuoy)

___
*[`tools/dynamic_analysis/valgrind.supp` line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17863#-NBPWNdU1M4b4dAOS92J:-NBPWNdU1M4b4dAOS92K:b-cz6taw) ([raw file](https://github.com/robotlocomotion/drake/blob/ff5ad354ecd3515c3c1428b4e1d5007a3b814e1b/tools/dynamic_analysis/valgrind.supp#L239)):*
> ```
>    Memcheck:Cond
>    fun:_ZN13vtkDataReader10ReadHeaderEPKc
>    fun:_ZN25vtkUnstructuredGridReader14ReadMeshSimpleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEP13vtkDataObject
> ```

We don't want to match the entire stack trace -- that's brittle with respect to changes in how VTK gets compiled.  We should use a `...` line (see elsewhere in this file for examples) to elide all expect some key places in the stack -- something like ReadHeader (the first line) and the Drake function (ReadVtkToVolumeMesh down below).

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17863)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[`tools/dynamic_analysis/valgrind.supp` line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17863#-NBPWNdU1M4b4dAOS92J:-NBPpQHT8JvyRPfT1hvK:b-eythqk) ([raw file](https://github.com/robotlocomotion/drake/blob/ff5ad354ecd3515c3c1428b4e1d5007a3b814e1b/tools/dynamic_analysis/valgrind.supp#L239)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We don't want to match the entire stack trace -- that's brittle with respect to changes in how VTK gets compiled.  We should use a `...` line (see elsewhere in this file for examples) to elide all expect some key places in the stack -- something like ReadHeader (the first line) and the Drake function (ReadVtkToVolumeMesh down below).
</blockquote></details>


Done.  I hope I get it right this time.  Thanks.

**Review by DamrongGuoy — COMMENTED** [review]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17863#-:-NBPpXNx0mSd_acruMpP:b-i4slid)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please

**Pull request merged**
