### PR TITLE
[SAP] Implements ContactProblemGraph

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements a class to describe the connectivity graph of a SAP problem.

Towards landing the [SapSolver](https://github.com/RobotLocomotion/drake/projects/10). Full working prototype in #16543.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature checkpoint. Looks great so far.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570#-:-MveImAFBZYOZSkb3-3l:bnvj8oj)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @amcastro-tri and @sherm1)

___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveEdUHCvERaWyIE085:-MveEdUHCvERaWyIE086:bg372co) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.h#L17)):*
> ```objc
> the graph corresponds to a clique and each edge in the graph corresponds to a
> "constraint cluster", see ConstraintCluster. A cluster of constraints or
> "constraint cluster" is defined as the set of constraints between one or two
> ```

minor: for clarity, consider "A constraint cluster is the set of all constraints acting on the same clique, or on the same pair of cliques."
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveFE4c0w2dJ51E7Pf7:-MveFE4c0w2dJ51E7Pf8:bz5822f) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.h#L21)):*
> ```objc
> 2021].
> 
> NOTE: This code in Drake is an extension to the ideas in [Castro et al., 2021].
> ```

nit: "to" -> "of"
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveFbzhCSqsK6kbU8gF:-MveFbzhCSqsK6kbU8gG:b-s8cysa) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.h#L25)):*
> ```objc
> is extended to the more general concept of "cliques" for any mechanical system.
> Similarly, while [Castro et al., 2021] refers to as "patches" to the the set of
> constact constraints between one or two trees, this concept has been extended to
> ```

nit: reword "Similarly, while [Castro] refers to the set of contact constraints between one or two trees as "patches", this concept ..."
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveGDbVEkHComBx_gz2:-MveGDbVEkHComBx_gz3:bw6uj7s) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.h#L33)):*
> ```objc
>  added, a cluster is created. Subsequent addition of more constraints between
>  the same set of cliques (one or two) will be associated with the already
>  existing cluster in the problem. */
> ```

nit: inconsistent indent for this paragraph
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveHTKV5TRJbnncVvms:-MveHTKV5TRJbnncVvmt:b-8a20s5) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.h#L67)):*
> ```objc
> 
>   /* Add constraint within a single clique with `num_constraint_equations`. An
>    exception is thrown if `clique` is not in (0, num_cliques()) or if
> ```

minor: should be (0, num_cliques-1). Or you could write it [0, num_cliques). (also below)
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveIPss7gtUuZi0W8Cz:-MveIPss7gtUuZi0W8D-:bk2x3ga) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.h#L119)):*
> ```objc
>   /* Helper to add a constraint between a pair of cliques. */
>   int AddConstraint(const SortedPair<int>& cliques_pair,
>                     int num_constrained_dofs);
> ```

nit: per [styleguide](https://drake.mit.edu/styleguide/cppguide.html#Declaration_Order), method declarations should precede data members

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending a few minor things. Also needs a rebase due to conflict with master.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570#-:-MveT74v9qCc-vzut9ey:b-ordfdt)* status: 14 unresolved discussions, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveMMYqClR9aCek12vr:-MveMMYqClR9aCek12vs:b9wuur2) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.cc#L15)):*
> ```cpp
> int ContactProblemGraph::AddConstraint(const SortedPair<int>& cliques_pair,
>                                        int num_constraint_equations) {
>   const int cluster_index = clusters_.size();
> ```

minor: this is a little confusing because `cluster_index` here is not necessarily the actual cluster index! That's only if it is a new cluster. I'll suggest some cleanup below.
___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveL91898npN3UcIIUj:-MveL91898npN3UcIIUk:bv7foo2) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.cc#L19)):*
> ```cpp
>   auto [iterator, new_cluster] = pair_to_cluster_index_.insert(
>       std::make_pair(cliques_pair, cluster_index));
>   if (new_cluster) clusters_.push_back(ConstraintCluster());
> ```

FYI you can write this `clusters_.emplace_back()` to avoid the extra copy (it will default construct in place).

However a cleaner approach would be to add a constructor to struct ConstraintCluster that takes the `cliques_pair` as an argument. Then the `cliques` member can be const as it should be, and you can remove several lines below.
___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveNGzrC3fI7YZhDTRh:-MveNGzrC3fI7YZhDTRi:b-tfxkaz) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.cc#L30)):*
> ```cpp
>   num_constraint_equations_ += num_constraint_equations;
>   return constraint_index;
> }
> ```

Suggested (untested) change for easier reading (assumes a one-arg constructor for ConstraintCluster):



_Code snippet:_
```cpp
int ContactProblemGraph::AddConstraint(const SortedPair<int>& cliques_pair,
                                       int num_constraint_equations) 
{
  auto [iterator, new_cluster] = pair_to_cluster_index_.insert(
      std::make_pair(cliques_pair, clusters_.size()));
  if (new_cluster) clusters_.emplace_back(cliques);
  const int cluster_index = iterator->second;
  const int constraint_index = num_constraints_++;
  ConstraintCluster& cluster = clusters_[cluster_index];
  cluster.num_constraint_equations += num_constraint_equations;
  cluster.constraint_index.push_back(constraint_index);
  cluster.constraint_num_equations.push_back(num_constraint_equations);
  num_constraint_equations_ += num_constraint_equations;
  return constraint_index;
}
```
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveQQ5O7bNbooa7jY_H:-MveQQ5O7bNbooa7jY_I:b-oapl8l) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L15)):*
> ```cpp
> // cluster of constraints connecting one or more cliques.
> // As documented in ContactProblemGraph's documentation, clusters are created
> // (and assigned a non-negative incrasing index) the first time a constraint
> ```

typo: incrasing -> increasing
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveQWLE87vibtUjjGjS:-MveQWLF24_4vuQ25Z4v:b98lrt2) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L16)):*
> ```cpp
> // As documented in ContactProblemGraph's documentation, clusters are created
> // (and assigned a non-negative incrasing index) the first time a constraint
> // between two cliques is added with a call to AddConstraint(). The graph below
> ```

nit: two cliques (or just one)
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveQnsN7mmMYns_TYpg:-MveQnsN7mmMYns_TYph:b-pu3iav) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L22)):*
> ```cpp
> // The labels for the clusters below correspond to:
> //  1. The first number corresponds to the expected cluster index.
> //  2. The numbers in squared brackets corresponds to the constraint index,
> ```

nit: squared -> square
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveQzzpA5fnNc4aEKoN:-MveQzzpA5fnNc4aEKoO:bn31rma) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L25)):*
> ```cpp
> //     assigned by each call to AddConstraint in the order it was called.
> //  3. The numbers in parentheses correspond to the size of each of the
> //     constraints in the cluster, also in the order they were added.
> ```

minor: clarify that by "size" you mean "number of equations"
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvePxDS6iczHjJlBMhs:-MvePxDS6iczHjJlBMht:b-kv4b4g) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L36)):*
> ```cpp
> //   └───────────────────────┘
> //         2[2, 4](6,5)
> //
> ```

BTW you could use `/* ... */` style comments here as you did in the code to avoid the `// ` fluff (if you want).

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri platform.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570#-:-Mvy2mIb52EkIsEeX6tN:b6uibm1)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MveL91898npN3UcIIUj:-MvyOrk5C78idVQf0xbm:b-lnujn6) ([raw file](https://github.com/robotlocomotion/drake/blob/5ccd27799fcf4ea9022c3250b1e438f4436c29a4/multibody/contact_solvers/sap/contact_problem_graph.cc#L19)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

SGTM. In the process I upgraded the cluster into its own class.
</blockquote></details>

Much nicer than what I proposed!

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform (with a few comments).

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570#-:-Mvymr_4DAlQwqcZowGu:b-gcjlqo)* status: 9 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyRGBU8WIk0FWUnWLG:-MvyRGBU8WIk0FWUnWLH:bsf6q5s) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L15)):*
> ```objc
> 
> /* This class represents the graph for a SapContactProblem where each node in
>  the graph corresponds to a clique and each edge in the graph corresponds to a
> ```

BTW you could add a reference of clique (`SapContactProblem::clique()`) if you'd like that.
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvySvoW1IhX1SPZhchz:-MvySvoW1IhX1SPZhci-:b-7m6tg8) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L47)):*
> ```objc
> 
>     /* Constructor for a cluster of constraints between the cliques specified by
>      `cliques_pair`. Indexes in `cliques_pair` must be non-negative. or an
> ```

nit, 



_Suggestion:_
```objc
Indexes in `cliques_pair` must be non-negative, or an
```
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyScTA22ybTBkUtjEr:-MvyScTA22ybTBkUtjEs:b-vqrihe) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L49)):*
> ```objc
>      `cliques_pair`. Indexes in `cliques_pair` must be non-negative. or an
>      exception is thrown.*/
>     explicit ConstraintCluster(SortedPair<int> cliques);
> ```

nit, mismatch between documentation and code: `cliques_pair` vs `cliques`



_Suggestion:_
```objc
explicit ConstraintCluster(SortedPair<int> cliques_pair);
```
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 58 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyTTSm6ZV5m576gzMu:-MvyTTSm6ZV5m576gzMv:b26jlz4) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L58)):*
> ```objc
>                                      int num_constraint_equations);
> 
>     const drake::SortedPair<int>& cliques() const { return cliques_; }
> ```

BTW, do you want to call the getter cliques_pair() as well?
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 58 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyTpmR4_K3BMEtZoMl:-MvyTpmR4_K3BMEtZoMm:bvt8jlm) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L58)):*
> ```objc
>                                      int num_constraint_equations);
> 
>     const drake::SortedPair<int>& cliques() const { return cliques_; }
> ```

BTW, is the `drake::` scope resolution necessary?
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 78 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyWd4U2UeC7LahtztM:-MvyWd4U2UeC7LahtztN:b-8022zy) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L78)):*
> ```objc
> 
>     /* Total number of constraint equations contributed by this cluster. */
>     int num_constraint_equations_{0};
> ```

nit,  Having both`num_constraint_equations` and `constraint_num_equations` is confusing. Consider `num_constraint_equations[i]` for the number of constraint equations for the i-th constraints and `total_num_constraint_equations` for the total number of constraint equations?
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 90 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyUUQV5egw1PI0J609:-MvyUUQV5egw1PI0J60A:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L90)):*
> ```objc
>   };
> 
>   /* Constructor for a graph with `num_cliques`. */
> ```





_Suggestion:_
```objc
Constructor for a graph with `num_cliques` nodes.
```
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 104 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyUpSKD6Jpbj63jige:-MvyUpSL1oSfzC4XjKeA:b-7m6tg8) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L104)):*
> ```objc
>    index to the newly added constraint. */
>   int AddConstraint(int first_clique, int second_clique,
>                     int num_constrained_dofs);
> ```

nit, 



_Suggestion:_
```objc
  int AddConstraint(int first_clique, int second_clique,
                    int num_constraint_equations);
```
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 126 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyVH0R1rYf66sf_sMF:-MvyVH0R1rYf66sf_sMG:bsohwmn) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L126)):*
> ```objc
>    indexed by `cluster_index`. */
>   const ConstraintCluster& get_cluster(int cluster_index) const {
>     return clusters_[cluster_index];
> ```

There should be an out-of-bound check here.
___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyZO263B_Dz4_5dlsD:-MvyZO263B_Dz4_5dlsE:b-cq98es) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.cc#L27)):*
> ```cpp
> 
> ContactProblemGraph::ContactProblemGraph(int num_cliques)
>     : num_cliques_(num_cliques) {}
> ```

nit, should verify that `num_cliques > 0`.
___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 46 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyYu6r-1esg9UBP6Wl:-MvyYu6v96VzkXq9yi3X:ba13jdh) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.cc#L46)):*
> ```cpp
>   DRAKE_THROW_UNLESS(0 <= clique && clique < num_cliques());
>   DRAKE_THROW_UNLESS(num_constraint_equations >= 0);
>   return AddConstraint(drake::MakeSortedPair(clique, clique),
> ```

nit, `drake::` needed?
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyZy4I597mwdAMPEgw:-MvyZy4I597mwdAMPEgx:b-7m6tg8) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L12)):*
> ```cpp
> 
> /* We test ContactProblemGraph with the graph setup sketched below where each
>  box corresponds to a cluster (a node in the graph) and edges correspond to a
> ```

nit, 



_Suggestion (i):_
```cpp
box corresponds to a clique (a node in the graph)
```



_Suggestion (ii):_
```cpp
and an edge corresponds to a
```
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-Mvy_faODb76n7_8Yg7S:-Mvy_faODb76n7_8Yg7T:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L22)):*
> ```cpp
>  The labels for the clusters below correspond to:
>   1. The first number corresponds to the expected cluster index.
>   2. The numbers in square brackets corresponds to the constraint index,
> ```





_Suggestion:_
```cpp
The numbers in square brackets correspond to the constraint index,
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyRGBU8WIk0FWUnWLG:-MvzHKGaB3GdDguATr_1:b-p5luid) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

There is no such thing as SapContactProblem::clique() thogh. 
As an alternative, I pointed to the SpaContactProblem's constructor docs.

</blockquote></details>

I was thinking of `num_cliques()`, but the class doc is probably better.
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 78 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyWd4U2UeC7LahtztM:-MvzIHBa0nWl-wjonPwa:b-vmrj41) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/contact_problem_graph.h#L78)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see the problem. I proposed different naming though. I like to prepend constraint quantities with `constraint_` and thus the names `constraint_index()` and `constraint_num_equations()`. I am using now num_total_constraint_equations() for the total number of equations in the cluster.
</blockquote></details>

SGTM, thanks.
___
*[multibody/contact_solvers/sap/contact_problem_graph.cc, line 28 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvzIXq90sA9VcRfxbJC:-MvzIXq90sA9VcRfxbJD:b-fnbsj0) ([raw file](https://github.com/robotlocomotion/drake/blob/85c88dac31c264b8d90da8a1358d02e47d2afc7f/multibody/contact_solvers/sap/contact_problem_graph.cc#L28)):*
> ```cpp
> ContactProblemGraph::ContactProblemGraph(int num_cliques)
>     : num_cliques_(num_cliques) {
>   DRAKE_THROW_UNLESS(num_cliques >= 0);
> ```

BTW, not sure if it's meaningful to have `num_cliques == 0` since you can't perform any meaning operations on that graph, but it's fine.
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16570#-MvyZy4I597mwdAMPEgw:-MvzIrdwAUPzfcssspfp:bbrompi) ([raw file](https://github.com/robotlocomotion/drake/blob/8d5ac6c85a8e0bc4d661901453094781105fdcee/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, 
</blockquote></details>

nit, plural vs. singular mismatch.
The proposed change is 
"and edges correspond to ..."

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16570)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
