### PR TITLE
Update primitives and examples to use modern event API

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Overriding the event dispatching will soon be deprecated.

Towards #13799.

+@sherm1 for feature review, please.

For testonly systems, I've only made the minimal adjustments.  For systems available to users, I tried to ensure the behavior remains the same by declaring both periodic and forced triggers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20114)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few questions

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-:-NdbCaGXAP32Y7Oolu-s:b-8xpzlb)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/controllers/linear_model_predictive_controller.cc` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-Ndb6xhk7wVtSdonGMp3:-Ndb6xhk7wVtSdonGMp4:b-cfc469) ([raw file](https://github.com/RobotLocomotion/drake/blob/746c69f6d708ace61e75e9a0345a3722c9d5fa88/systems/controllers/linear_model_predictive_controller.cc#L70)):*
> ```cpp
>       &LinearModelPredictiveController<T>::CalcDiscreteUpdate);
>   this->DeclareForcedDiscreteUpdateEvent(
>       &LinearModelPredictiveController<T>::CalcDiscreteUpdate);
> ```

minor: do you know why this apparently non-functional periodic discrete update is here? Is it just to get the integrator steps to complete at every time_period? If that is all then you don't need the Forced event here since it will do nothing when called. Or is the intent that users will derive from this class and override DoCalcDiscreteVariableUpdates() which will then be invoked periodically? In that case this change would break the derived classes since their override won't get called any more.

If you happen to know what this is for, it would be good to document it. Even if not, consider adding a TODO to track down the intent.
___
*[`systems/framework/test/system_symbolic_inspector_test.cc` line 100 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-NdbBRkM8flLCBt3-PJp:-NdbBRkM8flLCBt3-PJq:bmfnejv) ([raw file](https://github.com/RobotLocomotion/drake/blob/746c69f6d708ace61e75e9a0345a3722c9d5fa88/systems/framework/test/system_symbolic_inspector_test.cc#L100)):*
> ```cpp
>   }
> 
>   void CalcDiscreteUpdate(
> ```

minor: this test passes just the same without this function and the event you added. May as well remove altogether.
___
*[`systems/framework/test_utilities/initialization_test_system.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-NdbBq6I74V4w8fYvoZA:-NdbBq6I74V4w8fYvoZB:b4xkd6m) ([raw file](https://github.com/RobotLocomotion/drake/blob/746c69f6d708ace61e75e9a0345a3722c9d5fa88/systems/framework/test_utilities/initialization_test_system.h#L32)):*
> ```objc
>         &InitializationTestSystem::InitializationDiscreteUpdateHandler);
>     DeclareInitializationEvent(
>         UnrestrictedUpdateEvent<double>(TriggerType::kInitialization));
> ```

BTW did you intentionally leave this unrestricted update done the to-be-deprecated way?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20114)* status: needs at least two assigned reviewers

___
*[`systems/controllers/linear_model_predictive_controller.cc` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-Ndb6xhk7wVtSdonGMp3:-Ndf2TUqBEF73mW6VXC5:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/746c69f6d708ace61e75e9a0345a3722c9d5fa88/systems/controllers/linear_model_predictive_controller.cc#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: do you know why this apparently non-functional periodic discrete update is here? Is it just to get the integrator steps to complete at every time_period? If that is all then you don't need the Forced event here since it will do nothing when called. Or is the intent that users will derive from this class and override DoCalcDiscreteVariableUpdates() which will then be invoked periodically? In that case this change would break the derived classes since their override won't get called any more.

If you happen to know what this is for, it would be good to document it. Even if not, consider adding a TODO to track down the intent.
</blockquote></details>

Done
___
*[`systems/framework/test/system_symbolic_inspector_test.cc` line 100 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-NdbBRkM8flLCBt3-PJp:-Ndf4wII8VY26THTHUj9:b-4wljz4) ([raw file](https://github.com/RobotLocomotion/drake/blob/746c69f6d708ace61e75e9a0345a3722c9d5fa88/systems/framework/test/system_symbolic_inspector_test.cc#L100)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this test passes just the same without this function and the event you added. May as well remove altogether.
</blockquote></details>

Yikes!  That's because the test was incomplete, and the event trigger I used was wrong.
___
*[`systems/framework/test_utilities/initialization_test_system.h` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-NdbBq6I74V4w8fYvoZA:-Ndf7PuI1AlxpA2XVBXp:bau1wcg) ([raw file](https://github.com/RobotLocomotion/drake/blob/746c69f6d708ace61e75e9a0345a3722c9d5fa88/systems/framework/test_utilities/initialization_test_system.h#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW did you intentionally leave this unrestricted update done the to-be-deprecated way?
</blockquote></details>

Oops.  Fixed.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 12 of 16 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20114#-:-NdgT1so3t-KfECqEd3B:bzus18)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

**Pull request merged**
