### PR TITLE
[doc] Add release notes v1.13.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri to kick off platform review, please.  Note that there are some lines still TBDTBD which I'll be expanding upon shortly.  I just want to get reviews going now since I think we'll land this tomorrow morning.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: so far

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782#-:-NOGl_fi9t_KlCwhhx2b:b-vlbdz2)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: on mathematical optimization.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782#-:-NOH41wt3YiUNQwIvo5O:b-3k4ddx)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782#-:-NOH5ZMn5l-r2ZAPqTKQ:bg7igkv)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782#-:-NOHFkk73bhVwO3Z9hSQ:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18782)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Pull request merged**
