### PR TITLE
Add MOSEK to Bazel build

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5383)

### CODE REVIEW

**Comment by jamiesnape** [comment]
FYI @BetsyMcPhail @david-german-tri.

**Comment by david-german-tri** [comment]
Cool.  Do you have a follow-up PR that adds MOSEK to `MathematicalProgram`?

@hongkai-dai FYI

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/bazel.rc, line 65 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFo8Dibv-4W_shXm4D:-KeFo8Dibv-4W_shXm4E:b-ttv8ex) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/bazel.rc#L65)):*
> ```
> test:everything --test_env=GRB_LICENSE_FILE
> # -- Options for MOSEK.
> build:everything --define=WITH_SNOPT=ON
> ```

`WITH_MOSEK`

---

*[tools/mosek.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFpAY0S4Dt5dQW4HgB:-KeFpAY0S4Dt5dQW4HgC:b6crdri) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/mosek.bzl#L76)):*
> ```Python
> cc_library(
>     name = "mosek",
>     srcs = ["empty.cc"],
> ```

Ordinarily, I'd expect the `srcs` to be the dynamic library files, as in `gurobi.bzl` or `ipopt.BUILD`.  I think that would make the `linkopts` below unnecessary, and possibly also the `install_name_tool` tinkering above.  Did you try it?  (This will be the first time we've  added a dylib to the Drake Bazel build, so there could very well be problems I'm not anticipating.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-:-KeFoJ3efa-AW4SfPAoJ:b-xesfca)*

**Comment by david-german-tri** [comment]
Oh, I just saw the `do not review`.  Sorry.  Feel free to ignore the comments if they're not useful.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-:-KeFrKdQsx3dbPCVsUEs:b9dg8q2)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/mosek.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFpAY0S4Dt5dQW4HgB:-KeFsm65ieej3zMeFwuI:bat9c3b) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/mosek.bzl#L76)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Ordinarily, I'd expect the `srcs` to be the dynamic library files, as in `gurobi.bzl` or `ipopt.BUILD`.  I think that would make the `linkopts` below unnecessary, and possibly also the `install_name_tool` tinkering above.  Did you try it?  (This will be the first time we've  added a dylib to the Drake Bazel build, so there could very well be problems I'm not anticipating.)
</blockquote></details>

Yes, I tried that first. It crashed and burned in a very big way, unfortunately,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/mosek.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFpAY0S4Dt5dQW4HgB:-KeFu0wHeSttmmll_YFW:bzi1tmc) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/mosek.bzl#L76)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, I tried that first. It crashed and burned in a very big way, unfortunately,
</blockquote></details>

Would be interested in more details.  Crashed and burned on both platforms, or just Mac?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by hongkai-dai** [comment]
there is a `mosek_solver_test.cc` in `solvers/test`. It is not built in bazel yet.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-:-KeFyDw1erOmOngkN3BS:b-hwwrx5)*

**Comment by jamiesnape** [comment]
I will add building that to this PR. I actually mostly tested this on IRIS as I was primarily trying to get pybind11 Python bindings built.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/mosek.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFpAY0S4Dt5dQW4HgB:-KeFzRNYO4K-2N1YZOLI:b-3tg4ah) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/mosek.bzl#L76)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Would be interested in more details.  Crashed and burned on both platforms, or just Mac?
</blockquote></details>

Both. Mac was more spectacular. It either choked on the symbolic link, could not extract the correct library from the versioned shared object, or would not set the rpath correctly. It is definitely quite ugly, but this was the only way I could get a sandboxed binary to both link and run correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-:-KeG0OGFk15DmdM_IPSi:b-tg1lhn)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf7D5y8LLxh0TqopgrB:b-uxlpa1) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
> ```Python
> )
> 
> drake_cc_googletest(
> ```

I'm troubled that this test appears to test without Mosek.  @hongkai-dai, any thoughts on that?

https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/2539/console

Also, I'm surprised this doesn't need the `local` tag to root around in the homedir for the license file.

---

*[tools/mosek.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFpAY0S4Dt5dQW4HgB:-Kf7GHaJdZMwWAx0zu9Z:ba3vfjk) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/mosek.bzl#L76)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Both. Mac was more spectacular. It either choked on the symbolic link, could not extract the correct library from the versioned shared object, or would not set the rpath correctly. It is definitely quite ugly, but this was the only way I could get a sandboxed binary to both link and run correctly.
</blockquote></details>

I'm super happy to see that it turned out to work on Linux.  I can live with the ugliness on Mac.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-:-Kf7GsC2R1KppRu0diSW:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf7L03mgixAFiJPeCOA:b-qh1t1b) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I'm troubled that this test appears to test without Mosek.  @hongkai-dai, any thoughts on that?

https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/2539/console

Also, I'm surprised this doesn't need the `local` tag to root around in the homedir for the license file.
</blockquote></details>

I checked out the branch and tested it locally on my machine. I do not think it uses mosek in the test. The way I did is

```
$ bazel build --config mosek //drake/solvers:mosek_solver_test
$ bazel test --config mosek --test_tag_filters=mosek //drake/solvers:mosek_solver_test
```
But I receive the error
```
ERROR: No test targets were found, yet testing was requrested.
```

If I run the test as
```
$ bazel test --config mosek //drake/solvers:mosek_solver_test
```
Then it runs the test immediately, without calling mosek solver.

It actually fails at the assertion at https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/test/mathematical_program_test_util.cc#L16, that it thinks the solver is not available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf7YG-WAZsNAqGQjApP:b-p7gjgy) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I checked out the branch and tested it locally on my machine. I do not think it uses mosek in the test. The way I did is

```
$ bazel build --config mosek //drake/solvers:mosek_solver_test
$ bazel test --config mosek --test_tag_filters=mosek //drake/solvers:mosek_solver_test
```
But I receive the error
```
ERROR: No test targets were found, yet testing was requrested.
```

If I run the test as
```
$ bazel test --config mosek //drake/solvers:mosek_solver_test
```
Then it runs the test immediately, without calling mosek solver.

It actually fails at the assertion at https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/test/mathematical_program_test_util.cc#L16, that it thinks the solver is not available.
</blockquote></details>


I am missing a "mosek" test tag, certainly, so the no test targets error is correct. I will fix that now.

---

*[tools/mosek.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-KeFpAY0S4Dt5dQW4HgB:-Kf7HOfxQgTX9ai30Xfg:b7bw9ly) ([raw file](https://github.com/robotlocomotion/drake/blob/791479aefbf13d6e01f5dd9ccbdb7d2367d1156b/tools/mosek.bzl#L76)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I'm super happy to see that it turned out to work on Linux.  I can live with the ugliness on Mac.
</blockquote></details>

Yes, I think would have to upstream something to get Mac working in the same way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

**Comment by david-german-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf89j2uUSSFlUfTJptc:bu9evt1) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I am missing a "mosek" test tag, certainly, so the no test targets error is correct. I will fix that now.
</blockquote></details>

That tag is disabling the test by default, which is good, but it still smells like the test might not actually exercise MOSEK.  See @hongkai-dai's report of an assertion failure, and the fact that the sandbox shouldn't let it find a license file.  I'm going to see what I can learn by testing this locally, although the fact that TRI doesn't have a MOSEK license may be an impediment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by jamiesnape** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf8AqNyPUbrFAuHktnt:b-nvp9oc) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

That tag is disabling the test by default, which is good, but it still smells like the test might not actually exercise MOSEK.  See @hongkai-dai's report of an assertion failure, and the fact that the sandbox shouldn't let it find a license file.  I'm going to see what I can learn by testing this locally, although the fact that TRI doesn't have a MOSEK license may be an impediment.
</blockquote></details>

I certainly don't disagree with you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by david-german-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf8Bdzv_MuLNM5Heo5I:b-ar7kl8) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I certainly don't disagree with you.
</blockquote></details>

Heh, okay.  We should figure out what's going on before merging this PR, though, because once the test does try to exercise MOSEK, I expect the sandbox-vs-license-file problem to appear, and that the resolution will be to add the "local" tag as for gurobi.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by jamiesnape** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf8BxsEvkd5k9PqeAQ-:b-yu77ek) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Heh, okay.  We should figure out what's going on before merging this PR, though, because once the test does try to exercise MOSEK, I expect the sandbox-vs-license-file problem to appear, and that the resolution will be to add the "local" tag as for gurobi.
</blockquote></details>

I had MOSEK tests running through Bazel over at the IRIS repo without a local tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf8D6eUO9buyTM2B7dW:b-e18ihs) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I had MOSEK tests running through Bazel over at the IRIS repo without a local tag.
</blockquote></details>

Locally (where I have no license, I get lots of "Solver Mosek fails to find the solution"...so I guess this is exercising mosek after all.  Cool.  :lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-:-Kf8DM07P9q0BkSpAdVG:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf8Pt03gIVGL6jpwnWC:bdhdbp8) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Locally (where I have no license, I get lots of "Solver Mosek fails to find the solution"...so I guess this is exercising mosek after all.  Cool.  :lgtm:
</blockquote></details>

I tested this locally on my machine, but I do not see the mosek solver running.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 465 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5383#-Kf7D5y8LLxh0TqopgrA:-Kf8RZ1tlFMb4zQ4Q_gy:b-3xx719) ([raw file](https://github.com/robotlocomotion/drake/blob/6c5423d4679ed3c075ee0f1053aef53d015f117f/drake/solvers/BUILD#L465)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I tested this locally on my machine, but I do not see the mosek solver running.
</blockquote></details>

Sorry, I retract that. The solver runs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5383)*

**Pull request merged**
