### PR TITLE
clang-format-includes on Valkyrie and etc.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Changes (almost?) all `#include` statements in `drake/systems/{controllers,robotInterfaces}` and `drake/examples/{QPInverseDynamicsForHumanoids,Valkyrie,ZMP}` to obey `cppguide` and `code_style_guide`.

Relates #2269.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5556)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for all review, please.

:lgtm: does not need platform review.

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5556#-:-Kfb76uYQVJqxIWwUZPK:bksx8qq)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 27 of 32 files at r1.
Review status: 27 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5556)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Reviewed 4 of 32 files at r1.
Review status: 31 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5556#-:-KfbDuOkej1sRbV8jvz6:bg7igkv)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
