### PR TITLE
Add FixedSizeConstitutiveModel and FixedSizeDeformationGradientCacheEntry.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14408)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14408)* status: 2 unresolved discussions, needs at least one assigned reviewer, labeled "do not merge"

___
*[multibody/fem/dev/fixed_size_constitutive_model.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14408#-MNeeJBf-aTlagfajXRX:-MNeeJBf-aTlagfajXRY:bkjce0j) ([raw file](https://github.com/robotlocomotion/drake/blob/8f8068c095a99c9d3f5ea8508be941cc2ab01f99/multibody/fem/dev/fixed_size_constitutive_model.h#L65)):*
> ```objc
>    being available. Ideally, the signature of the method would be
>    void CalcFirstPiolaStress(
>         const typename Derived::DeformationGradientCacheEntryType&,
> ```

Too bad I can't use the typedef in the derived class!
___
*[multibody/fem/dev/fixed_size_linear_constitutive_model.h, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14408#-MNee-If0eC1IUPTOEm9:-MNee-Ig2nrPhHSHJ2E7:bdviy71) ([raw file](https://github.com/robotlocomotion/drake/blob/8f8068c095a99c9d3f5ea8508be941cc2ab01f99/multibody/fem/dev/fixed_size_linear_constitutive_model.h#L27)):*
> ```objc
>   using Base = FixedSizeConstitutiveModel<
>       FixedSizeLinearConstitutiveModel<T, NumLocations>>;
>   using DeformationGradientCacheEntryType =
> ```

Public typedef to specify the DeformationGradientCacheEntry compatible with this model.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14408)* status: 2 unresolved discussions, needs at least one assigned reviewer, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_constitutive_model.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14408#-MNeeJBf-aTlagfajXRX:-MNfW3z50cds2L8F94YZ:bl16c52) ([raw file](https://github.com/robotlocomotion/drake/blob/8f8068c095a99c9d3f5ea8508be941cc2ab01f99/multibody/fem/dev/fixed_size_constitutive_model.h#L65)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Too bad I can't use the typedef in the derived class!
</blockquote></details>

BTW per f2f and playing around -- adding a small traits class seems the cleanest approach.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14408)* status: 2 unresolved discussions, needs at least one assigned reviewer, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_constitutive_model.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14408#-MNhq6UpCJa0za--_Jgs:-MNhq6UqCyxqS4A4Uj0v:b-hvln6r) ([raw file](https://github.com/robotlocomotion/drake/blob/8f8068c095a99c9d3f5ea8508be941cc2ab01f99/multibody/fem/dev/fixed_size_constitutive_model.h#L44)):*
> ```objc
>    not and cannot verify the cache entries provided are up-to-date. */
> 
>   /** Calculates the energy density, in unit J/m³, given the model cache entry.
> ```

nit. I believe per unit reference volume? please always state this non-obvious fact for future devs that will run into this. (I always forget myself :-) ).
___
*[multibody/fem/dev/fixed_size_constitutive_model.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14408#-MNeeJBf-aTlagfajXRX:-MNhqvNyAPPZX3HRacMn:bkz6cmf) ([raw file](https://github.com/robotlocomotion/drake/blob/8f8068c095a99c9d3f5ea8508be941cc2ab01f99/multibody/fem/dev/fixed_size_constitutive_model.h#L65)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f and playing around -- adding a small traits class seems the cleanest approach.
</blockquote></details>

I agree, I believe it'd work better in this case. I imagine a traits for FixedSizeConstitutiveModel? is that it?

Question, where would those traits live? in their own header file? Since say, fixed_size_constitutirve_model.h needs to include the traits file, would we forward declare the derived classes for the traits? 
That is, still not clear to me what the inclusion pattern is and if that could potentially lead to cyclic dependencies we need to think about. 
In any case, Eigen does this all the time, so doable in principle.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14408)* status: 2 unresolved discussions, needs at least one assigned reviewer, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/fixed_size_constitutive_model.h, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14408#-MNeeJBf-aTlagfajXRX:-MNido635OulpkOLAdMS:b-jovl7i) ([raw file](https://github.com/robotlocomotion/drake/blob/8f8068c095a99c9d3f5ea8508be941cc2ab01f99/multibody/fem/dev/fixed_size_constitutive_model.h#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I agree, I believe it'd work better in this case. I imagine a traits for FixedSizeConstitutiveModel? is that it?

Question, where would those traits live? in their own header file? Since say, fixed_size_constitutirve_model.h needs to include the traits file, would we forward declare the derived classes for the traits? 
That is, still not clear to me what the inclusion pattern is and if that could potentially lead to cyclic dependencies we need to think about. 
In any case, Eigen does this all the time, so doable in principle.
</blockquote></details>

Here's a little program we worked up that demonstrates the traits idea:
```c++
template<typename DerivedType, typename DerivedTraits>
class Base {
public:
 using T = typename DerivedTraits::Scalar;
};
template <typename T>
class DerivedTraits {
public:
   using Scalar = T;
};
template <typename T>
class Derived : public Base<Derived<T>, DerivedTraits<T>> {
public:
   using Scalar = typename DerivedTraits<T>::Scalar;
};
int main() {
    Derived<double> d;
    return 0;
}
```
DerivedTraits and Derived would always appear together in the same header file.

**Pull request closed without merging**
