### PR TITLE
Added drake_ros_common and its unit tests.

### PR DESCRIPTION
**Pull request by liangfok**
This PR was broken out of #3103.

This adds a ROS package called `drake_ros_common` containing code that is of general use for other Drake ROS packages. It also includes a separate package called `drake_ros_common_test` that contains unit tests for `drake_ros_common`. I had to keep the unit tests in a separate package to link against the library that's exported by `drake_ros_common`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3409)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this involves ROS, +@jhoare  for feature review please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRHaB4Qz5LvW20t6cmr:b2uqw3w)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by liangfok** [comment]
Win32 CI had an upload flake.

@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
@jhoare, I added two additional unit tests to the Drake / ROS code:

```
    $ rostest drake_ros_common_test parameter_server_test.test
    $ rostest drake_ros_common_test simulation_abort_function_test.test
```

Looking through the [console log](https://drake-jenkins.csail.mit.edu/job/linux-clang-experimental-ros/60/console), I see that they successfully executed. However, they do not appear in [CDash](https://drake-cdash.csail.mit.edu/index.php?project=Drake-ROS&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-experimental-ros-release-3409-60&field2=buildstarttime&compare2=84&value2=now). Is this expected?

**Comment by jhoare** [comment]
I'm confused as to why you need the _test version of the package as opposed to doing what is in ``drake_ros_systems`` for its test. The only reason I could see is that you want to test that the package is exporting the correct libraries and headers to be compiled against. Is that the case? 

As far as everything not showing up on CDash we will need to look into that. It was working at one point but it looks like none of the tests are being correctly uploaded now. 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[ros/drake_ros_common/CMakeLists.txt, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO18JF_F9fwV1tqPvj:-KRO18JGLorGMp5j7qHu:byipmhq) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/CMakeLists.txt#L4)):*
> ```CMake
> project(drake_ros_common)
> 
> set(CMAKE_CXX_STANDARD 14)
> ```

I don't believe that this existed in version 2.8.3 of CMake. You should likely just increase the minimum cmake version to match drake proper's. 

---

*[ros/drake_ros_common/CMakeLists.txt, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO05QM7j2ozx94SzPL:-KRO05QNOD847qrXMBLS:bf9skj8) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/CMakeLists.txt#L22)):*
> ```CMake
> )
> 
> file(GLOB ${PROJECT_NAME}_SRCS src/*.cc)
> ```

It is better to explicitly list the source files out rather than globbing.

---

*[ros/drake_ros_common/include/drake/ros/parameter_server.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO39HorR3Pzhwuj4fa:-KRO39Hp4NG0b3ebKTmz:bpp08qf) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/include/drake/ros/parameter_server.h#L13)):*
> ```objc
>  * parameter does not show up prior to @p max_wait_time elapsing.
>  */
> void WaitForParameter(const ::ros::NodeHandle& ros_node_handle,
> ```

I assume you picked the version that takes in a Nodehandle for a reason? I generally prefer the API that doesn't take in a NodeHandle, but functionally its the same. 

---

*[ros/drake_ros_common/include/drake/ros/simulation_abort_function.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO594Cy-PosJ3u7Dt-:-KRO594Cy-PosJ3u7Dt0:b-id5w3f) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/include/drake/ros/simulation_abort_function.h#L15)):*
> ```objc
> /**
>  * Adds a custom stop function that (1) checks whether the simulation should
>  * abort based on a call to ros::ok(), and (2) publishes a clock message so
> ```

I don't see where (2) is happening here. 

---

*[ros/drake_ros_common_test/CMakeLists.txt, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO5ENqa2-Ma_l9HHt5:-KRO5ENqa2-Ma_l9HHt6:bxacjf7) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common_test/CMakeLists.txt#L4)):*
> ```CMake
> project(drake_ros_common_test)
> 
> set(CMAKE_CXX_STANDARD 14)
> ```

Same issue as in the other CMakeLists.txt  regarding minimum version.

---

*[ros/drake_ros_common_test/package.xml, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO4VWpM9vfZ-Dcd624:-KRO4VWpM9vfZ-Dcd625:b6v78fn) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common_test/package.xml#L19)):*
> ```XML
> 
> 
>   
> ```

A lot of generated comments that should probably be cleared out. 

---

*[ros/drake_ros_common_test/include/README.md, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO3nSh3HeJvQA3fTIz:-KRO3nSh3HeJvQA3fTJ-:b-9a1xv8) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common_test/include/README.md#L1)):*
> ```Markdown
> This include directory is necessary to prevent Catkin from using the wrong
> ```

How does the existence of this folder with the README.md fix this problem? This line was supposed to work-around the issue: https://github.com/RobotLocomotion/drake/blob/master/ros/drake_ros_systems/CMakeLists.txt#L15

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRO3VwzinM-QNuTh0uk:bt32c8j)*

**Comment by liangfok** [comment]
Yes, I placed the unit tests for package `drake_ros_common` in a separate package to evaluate whether `drake_ros_common` correctly exports its library and header files. If there's a better way to do that, please let me know!

Actually, now that I think about it some more, I no longer think it's necessary to unit test whether the library and header files are correctly exported because a problem with that will be detected by packages that depend on `drake_ros_common` and their unit tests (I will soon follow up with PRs containing those packages). I'll thus update this PR by moving the unit tests into `drake_ros_common`.

---

Review status: 4 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[ros/drake_ros_common/CMakeLists.txt, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO18JF_F9fwV1tqPvj:-KROS9xYFzOkasP8e6hd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/CMakeLists.txt#L4)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> I don't believe that this existed in version 2.8.3 of CMake. You should likely just increase the minimum cmake version to match drake proper's. 
</details>
Done.

---

*[ros/drake_ros_common/CMakeLists.txt, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO05QM7j2ozx94SzPL:-KROSJG9pptLoRLx3OxE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/CMakeLists.txt#L22)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> It is better to explicitly list the source files out rather than globbing.
</details>
Done.

---

*[ros/drake_ros_common/include/drake/ros/parameter_server.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO39HorR3Pzhwuj4fa:-KRQ92SnhsMd8p_6OWrc:bxci804) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/include/drake/ros/parameter_server.h#L13)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> I assume you picked the version that takes in a Nodehandle for a reason? I generally prefer the API that doesn't take in a NodeHandle, but functionally its the same. 
</details>
I forgot there was a version that didn't require a `NodeHandle`. I've switched the API and implementation to use that version. Thanks.

---

*[ros/drake_ros_common/include/drake/ros/simulation_abort_function.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO594Cy-PosJ3u7Dt-:-KRQ8xHd1Ia_cM0PzNTE:b8r3asj) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common/include/drake/ros/simulation_abort_function.h#L15)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> I don't see where (2) is happening here. 
</details>
Oops. I forgot to update the comment. Fixed. Thanks.

---

*[ros/drake_ros_common_test/CMakeLists.txt, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO5ENqa2-Ma_l9HHt5:-KRQ8o3ZGKizvlMm7EYI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common_test/CMakeLists.txt#L4)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> Same issue as in the other CMakeLists.txt  regarding minimum version.
</details>
Done.

---

*[ros/drake_ros_common_test/package.xml, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO4VWpM9vfZ-Dcd624:-KRQA_C3BHPF_ZJ6XJ28:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common_test/package.xml#L19)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> A lot of generated comments that should probably be cleared out. 
</details>
Done.

---

*[ros/drake_ros_common_test/include/README.md, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRO3nSh3HeJvQA3fTIz:-KRQxWQj3e_kHrzr6GpQ:byui1gf) ([raw file](https://github.com/robotlocomotion/drake/blob/91733c8cbae7cdc161d66ae53e9eb3b0eeec6b01/ros/drake_ros_common_test/include/README.md#L1)):*
<details><summary><i>Previously, jhoare (John Hoare) wrote…</i></summary>
> How does the existence of this folder with the README.md fix this problem? This line was supposed to work-around the issue: https://github.com/RobotLocomotion/drake/blob/master/ros/drake_ros_systems/CMakeLists.txt#L15
</details>
Ah. Thanks. I misunderstood what that line was for. I deleted this README.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRORL_dSK3z-ZGhuneV:bstl7cc)*

**Comment by jhoare** [comment]
Changes so far look good. :lgtm: I wouldn't block the _test package, but I'll re-review if you want to do it. 

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRTWX-0ToS02MlmYu1p:bjyyfat)*

**Comment by liangfok** [comment]
OK here's what I'll do. I'll keep the `drake_ros_common_test` package as it since there are currently no other packages that depend on it meaning there's currently no other way to verify that the library and header files in `drake_ros_common` are being correctly exported. In an upcoming PR that does contain a dependent package, I will fold `drake_ros_commont_test` into `drake_ros_common`.

Since today's Monday, +@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRTX3UZU1U8xHSMThvR:b-pb49jf)*

**Comment by sherm1** [comment]
Platform review: :lgtm: with caveat that I am not fluent in ROS. A few BTW comments, PTAL.

---

Reviewed 4 of 13 files at r1, 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ros/drake_ros_common/CMakeLists.txt, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRWb1VoNuFnBPU1meQ7:-KRWb1VprUmz3CXZiYi2:b-kctvgd) ([raw file](https://github.com/robotlocomotion/drake/blob/b27a13c99c1e696d5325bb6d8a8d062ae9f64d63/ros/drake_ros_common/CMakeLists.txt#L13)):*
> ```CMake
>   LIBRARIES ${PROJECT_NAME}
>   CATKIN_DEPENDS
>   #DEPENDS
> ```

BTW, commented out -- remove?

---

*[ros/drake_ros_common_test/CMakeLists.txt, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRWc32l7v3hhseIdXNH:-KRWc32mV7vQdt5dh1Bq:bdefrd1) ([raw file](https://github.com/robotlocomotion/drake/blob/b27a13c99c1e696d5325bb6d8a8d062ae9f64d63/ros/drake_ros_common_test/CMakeLists.txt#L12)):*
> ```CMake
>   #LIBRARIES
>   #CATKIN_DEPENDS
>   #DEPENDS
> ```

BTW, all commented out above -- remove?

---

*[ros/drake_ros_common_test/package.xml, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRWcNnx6ueVMpOvZqci:-KRWcNnx6ueVMpOvZqcj:bw9j19u) ([raw file](https://github.com/robotlocomotion/drake/blob/b27a13c99c1e696d5325bb6d8a8d062ae9f64d63/ros/drake_ros_common_test/package.xml#L5)):*
> ```XML
>   <name>drake_ros_common_test</name>
>   <version>0.0.0</version>
>   <description>This package contains unit tests for drake_ros_common.</description>
> ```

BTW, line length > 80.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRWdXmKv6dNXl3gp17V:b-wmjf07)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. Just waiting on CI now.

---

Review status: 11 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[ros/drake_ros_common/CMakeLists.txt, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRWb1VoNuFnBPU1meQ7:-KRYuHBhPXkADhFynbQu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b27a13c99c1e696d5325bb6d8a8d062ae9f64d63/ros/drake_ros_common/CMakeLists.txt#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, commented out -- remove?
</details>
Done.

---

*[ros/drake_ros_common_test/CMakeLists.txt, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRWc32l7v3hhseIdXNH:-KRYtlrTr9Ke6NGup7Hb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b27a13c99c1e696d5325bb6d8a8d062ae9f64d63/ros/drake_ros_common_test/CMakeLists.txt#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, all commented out above -- remove?
</details>
Done.

---

*[ros/drake_ros_common_test/package.xml, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-KRWcNnx6ueVMpOvZqci:-KRYtuRlKOqvaxhOtYw9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b27a13c99c1e696d5325bb6d8a8d062ae9f64d63/ros/drake_ros_common_test/package.xml#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, line length > 80.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3409#-:-KRYtxMxG1jRK6QR1rCy:bv8axsv)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by liangfok** [comment]
The Drake/ROS/Clang CI test failed due to #3429. Let's see how repeatable it is.

@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
Hmm, #3429 apparently is not repeatable. I shall thus merge.

**Pull request merged**
