### PR TITLE
Bind EvalBodySpatialAccelerationInWorld

### PR DESCRIPTION
**Pull request by nepfaff**
Adds a binding for [MultibodyPlant::EvalBodySpatialAccelerationInWorld](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#a725008fd74cc0c6c30e938eeaaf902e2).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161)

### CODE REVIEW

**Comment by nepfaff** [comment]
I'm getting this error:
```
A_base = plant.EvalBodySpatialAccelerationInWorld(context, base)
ValueError: This method doesn't support T = drake::symbolic::Expression.
```

Did I do something wrong with the binding? It looks the same like `EvalBodySpatialVelocityInWorld`. I think it should also support the same template types?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-NtXL4rn1NuteoMQLiKR:-NtXL4roA693cyMTzsm7:bbvc41u) ([raw file](https://github.com/RobotLocomotion/drake/blob/6749119e70afed1f11104d936507239a21fe138a/bindings/pydrake/multibody/test/plant_test.py#L1224)):*
> ```Python
> 
>         # Compute spatial accelerations for base.
>         A_base = plant.EvalBodySpatialAccelerationInWorld(context, base)
> ```

hm... looking at the code, I only see `This method doesn't support T = drake::symbolic::Expressions` in what looks like spots for contact calculations.

the plant in this test case doesn't have a scene graph, so not immediately clear why this is being triggered

@amcastro-tri Any chance you're familiar with this?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nepfaff)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-NtXL4rn1NuteoMQLiKR:-NtXOUNZ98OM8b8IXLii:b-ie6gds) ([raw file](https://github.com/RobotLocomotion/drake/blob/6749119e70afed1f11104d936507239a21fe138a/bindings/pydrake/multibody/test/plant_test.py#L1224)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

hm... looking at the code, I only see `This method doesn't support T = drake::symbolic::Expressions` in what looks like spots for contact calculations.

the plant in this test case doesn't have a scene graph, so not immediately clear why this is being triggered

@amcastro-tri Any chance you're familiar with this?
</blockquote></details>

@nepfaff one option to move this forward is to file an issue, mentioning this, and then working around by guarding

```
if T == Expression:
     # TODO(#issue): Fix this error
     with self.asesrtRaises(ValueError) as cm:
         ... the call
     self.assertIn("This method doesn't support T = drake::symbolic::Expression", str(cm.exception)
else:
    ... the call (normal)
```

then at least we have active point of doc + issue

**Comment by jwnimmer-tri** [comment]
I don't think we need an issue?  If you call the same function in C++, I assume it would throw as well?  If it does, then there is nothing wrong with the bindings, and the only problem is the unit test is calling a function that's known to throw, and should simply not call that function for T=symbolic.

**Comment by nepfaff** [comment]
> I don't think we need an issue? If you call the same function in C++, I assume it would throw as well? If it does, then there is nothing wrong with the bindings, and the only problem is the unit test is calling a function that's known to throw, and should simply not call that function for T=symbolic.

I checked the C++ tests, and they don't test for `Expression`. I excluded `Expression` from the binding test.

I agree with Eric, though, that it seems weird that this method doesn't support symbolic. Direct dynamics computations (e.g. `CalcInverseDynamics`) do support symbolic, so this one should also be able to?

**Review by nepfaff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-NtXL4rn1NuteoMQLiKR:-NtYEVli0EXb51IRAx3P:b-vlxanv) ([raw file](https://github.com/RobotLocomotion/drake/blob/6749119e70afed1f11104d936507239a21fe138a/bindings/pydrake/multibody/test/plant_test.py#L1224)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@nepfaff one option to move this forward is to file an issue, mentioning this, and then working around by guarding

```
if T == Expression:
     # TODO(#issue): Fix this error
     with self.asesrtRaises(ValueError) as cm:
         ... the call
     self.assertIn("This method doesn't support T = drake::symbolic::Expression", str(cm.exception)
else:
    ... the call (normal)
```

then at least we have active point of doc + issue
</blockquote></details>

I added this (without the issue as discussed). However, I'm getting
```
with self.assertRaises(ValueError) as cm:
AssertionError: ValueError not raised
```

However, `cm.exception` contains the correct message. It still fails if I replace `ValueError` with a general `Exception`. Something weird seems to be going on here. Could it be that the exception isn't translated correctly between C++ and python?

**Comment by jwnimmer-tri** [comment]
> Direct dynamics computations (e.g. CalcInverseDynamics) do support symbolic, so this one should also be able to?

With a discrete-time plant, the (forward dynamics) accelerations depend on the contact solver result, which doesn't support symbolic (yet?).

**Review by EricCousineau-TRI — COMMENTED** [review]
ah, gotcha; I guess I was surprised that contact solvers were still involved without a scene graph being registered
but at least it's clear to see continuous vs discrete case.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-:-NtZB6PO6nn_K8gu7QiR:b-twr4j7)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-NtXL4rn1NuteoMQLiKR:-NtZAQTREK3wEvdeartW:b-zamr0b) ([raw file](https://github.com/RobotLocomotion/drake/blob/6749119e70afed1f11104d936507239a21fe138a/bindings/pydrake/multibody/test/plant_test.py#L1224)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

I added this (without the issue as discussed). However, I'm getting
```
with self.assertRaises(ValueError) as cm:
AssertionError: ValueError not raised
```

However, `cm.exception` contains the correct message. It still fails if I replace `ValueError` with a general `Exception`. Something weird seems to be going on here. Could it be that the exception isn't translated correctly between C++ and python?
</blockquote></details>

per Jeremy's point above, the following patch allowed it to pass on my machine:
```diff
diff --git a/bindings/pydrake/multibody/test/plant_test.py b/bindings/pydrake/multibody/test/plant_test.py
index a5edf69fe0..d7c3bb1f0c 100644
--- a/bindings/pydrake/multibody/test/plant_test.py
+++ b/bindings/pydrake/multibody/test/plant_test.py
@@ -1223,3 +1223,5 @@ class TestPlant(unittest.TestCase):
         # Compute spatial accelerations for base.
-        if T == Expression:
+        if T == Expression and plant.time_step() != 0:
+            # N.B. Discrete time dynamics are not supported for symbolic
+            # scalars.
             with self.assertRaises(ValueError) as cm:
```

can you apply that here and see if it works?

reason is that this func is called 6 times; 3 per scalar x 2 for continuous vs discrete
in continuous case, it won't raise; in discrete case, it will raise
for example, if I remove `with` statement and let exception escape:
```
ERROR [0.138s]: test_multibody_tree_kinematics_discrete (plant_test.TestPlant)
----------------------------------------------------------------------
...
ValueError: This method doesn't support T = drake::symbolic::Expression.
```

note that it only reports error in discrete mode

**Review by nepfaff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-NtXL4rn1NuteoMQLiKR:-NtbQ0bi-yeZcCYJAg-e:beszuxf) ([raw file](https://github.com/RobotLocomotion/drake/blob/6749119e70afed1f11104d936507239a21fe138a/bindings/pydrake/multibody/test/plant_test.py#L1224)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

per Jeremy's point above, the following patch allowed it to pass on my machine:
```diff
diff --git a/bindings/pydrake/multibody/test/plant_test.py b/bindings/pydrake/multibody/test/plant_test.py
index a5edf69fe0..d7c3bb1f0c 100644
--- a/bindings/pydrake/multibody/test/plant_test.py
+++ b/bindings/pydrake/multibody/test/plant_test.py
@@ -1223,3 +1223,5 @@ class TestPlant(unittest.TestCase):
         # Compute spatial accelerations for base.
-        if T == Expression:
+        if T == Expression and plant.time_step() != 0:
+            # N.B. Discrete time dynamics are not supported for symbolic
+            # scalars.
             with self.assertRaises(ValueError) as cm:
```

can you apply that here and see if it works?

reason is that this func is called 6 times; 3 per scalar x 2 for continuous vs discrete
in continuous case, it won't raise; in discrete case, it will raise
for example, if I remove `with` statement and let exception escape:
```
ERROR [0.138s]: test_multibody_tree_kinematics_discrete (plant_test.TestPlant)
----------------------------------------------------------------------
...
ValueError: This method doesn't support T = drake::symbolic::Expression.
```

note that it only reports error in discrete mode
</blockquote></details>

Ah, now I understand. Thank you for this. I pushed the changes

**Review by EricCousineau-TRI — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-:-NtgHN0I5oS1EKD1hLeu:b3dcro0)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @nepfaff)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-NtXL4rn1NuteoMQLiKR:-NtgHGs6BnfHLTHAhpes:b4dt6q2) ([raw file](https://github.com/RobotLocomotion/drake/blob/6749119e70afed1f11104d936507239a21fe138a/bindings/pydrake/multibody/test/plant_test.py#L1224)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

Ah, now I understand. Thank you for this. I pushed the changes
</blockquote></details>

Awesome, and you're welcome!
Thanks Jeremy for steering us onto the right path.

**Review by EricCousineau-TRI — COMMENTED** [review]
+@EricCousineau-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-:-NtgHRbM1D6l1PdjpuT7:b-43n95z)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: (sorry, should have done these three things in one go)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21161#-:-NtgHUy-1mN4-NWtt4y3:b-qr34nn)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
