### PR TITLE
multibody: Update SDF parsing code to reflect SDFormat doc frame names

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
SDFormat docs: http://sdformat.org/tutorials?tut=spec_model_kinematics

\cc @scpeters @azeey

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11230)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
wow! those new [SDF docs](http://sdformat.org/tutorials?tut=spec_model_kinematics) are beautiful! good job guys!
A few passing comments regarding those docs:
1. when talking about joint frames Jp, Jc and J, why do we need to talk about J at all? what is it even? I'd remove that.
2. It'd be nice adding Jp and Jc to your schematics showing the poses X_CJc and X_PJp.

**Comment by scpeters** [comment]
@amcastro-tri that's a good point about preferring `Jp` and `Jc`. I've made a pull request to update the SDF documentation:

* https://bitbucket.org/osrf/sdf_tutorials/pull-requests/13/replace-joint-frame-references-with-jc-and/diff

**Comment by amcastro-tri** [comment]
Thank you @scpeters! I am flying on Monday but I'll see to look at it ASAP.

**Comment by amcastro-tri** [comment]
Sorry for the delay due to travel @scpeters, I added my two cents. Thanks for the update!

**Comment by jwnimmer-tri** [comment]
Happy New Year, and thanks for your interest in contributing to Drake!  Since this PR has not received any updates over the past 6+ months, we are closing it automatically.  To resume the PR again, you may reopen it with updates, or open a new one.

**Pull request closed without merging**
