### PR TITLE
vtk_util_test: Fix errors on Mac

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Relates #6498.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6524)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by kunimatsu-tri** [comment]
+@sammy-tri both level of review please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6524#-:-KoS88KL1v5QhMd3jvHN:be9uthv)*

**Comment by jwnimmer-tri** [comment]
:lgtm: all review

**Comment by kunimatsu-tri** [comment]
-@sammy-tri 

Thanks @jwnimmer-tri!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6524#-:-KoS9RLp0pebUBPZ8B3R:b-wivfey)*

**Comment by jwnimmer-tri** [comment]
The OSX build is still running, but it also serves no purpose, so I'm going to merge anyway.

**Pull request merged**
