### PR TITLE
[meshcat] Add JointSliders system

### LINKED ISSUE #16385: Add MeshcatJointSliders
Our upcoming tutorial related to MultibodyPlant wants to make use of the [MeshcatJointSliders](https://github.com/RussTedrake/manipulation/blob/008cec6343dd39063705287e6664a3fee71a43b8/manipulation/meshcat_cpp_utils.py#L236) leaf system from the https://github.com/RussTedrake/manipulation repository.

We should incorporate that class into Drake, porting it to C++ in the meantime (and binding into pydrake).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Based on [meshcat_cpp_utils.py](https://github.com/RussTedrake/manipulation/blob/008cec6343dd39063705287e6664a3fee71a43b8/manipulation/meshcat_cpp_utils.py#L236) from Russ.

Part of #16385.

This PR only adds the System itself (and the pydrake bindings).  It does not yet offer the `Run` loop.

Requires:
- [x] #16407

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[multibody/meshcat/joint_sliders.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MtpKHbz44vs9okKyX5Z:-MtpKHbz44vs9okKyX5_:bewz7uk) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L18)):*
> ```objc
> namespace meshcat {
> 
> /** Adds one Meshcat slider per joint of the MultibodyPlant.
> ```

I should probably add more text to the overview here.  This probably not clear enough to a first-time reader.
___
*[bindings/pydrake/common/monostate_pybind.h, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MtpKQPJ2tlU54nagF5k:-MtpKQPJ2tlU54nagF5l:bou6sko) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/bindings/pydrake/common/monostate_pybind.h#L1)):*
> ```objc
> #pragma once
> ```

Working

Carve this into another PR.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

___
*[multibody/meshcat/joint_sliders.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MtpKHbz44vs9okKyX5Z:-MtrspPu1SZrLBDs4v5S:bqog80t) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I should probably add more text to the overview here.  This probably not clear enough to a first-time reader.
</blockquote></details>

Agreed
___
*[multibody/meshcat/joint_sliders.h, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MtrtBHMBsuEl3Ewtwow:-MtrtBHN5RYvFuFY1hgd:b-1cyvyh) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L36)):*
> ```objc
> values, even if evaluated by multiple different downstream input ports during a
> single computation.  If you need to have a synchronized view of the slider data,
> place a ZeroOrderHold system between the sliders and downstream calculations.
> ```

btw -- i worried about this, too, and like this doc string as a sufficient solution.
___
*[multibody/meshcat/joint_sliders.h, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-Mtrtk78EQ3aJ77_PAAo:-Mtrtk78EQ3aJ77_PAAp:b-pcagbf) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L57)):*
> ```objc
>   @param lower_limit (Optional) the lower limit of the slider will be the
>   maximum value of this number and any limit specified in the Joint.
>   May be a single value or else a vector of length plant.num_positions().
> ```

If unspecified in multibody plant, then the default limits will be +/- infinity (right?).  those are not usable for the sliders.

I think the analogy to what I did in python would be e.g. `std::variant<double, Eigen::VectorXd> lower_limit = -1.0`?
___
*[multibody/meshcat/joint_sliders.h, line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-Mts0kldE-i5O8buUKh8:-Mts0kldE-i5O8buUKh9:b-jv02pb) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L64)):*
> ```objc
> 
>   @param step (Optional) the step argument of the slider.
>   May be a single value or else a vector of length plant.num_positions().
> ```

i think this one deserves an explicit default value, too?  and perhaps not everybody knows what a "step" means for a gui slider element?  can we just say determinies the discretization size of the slider values?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[multibody/meshcat/joint_sliders.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MtpKHbz44vs9okKyX5Z:-MtsLiRpB49Hqg7WJwJr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L18)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Done.
___
*[multibody/meshcat/joint_sliders.h, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-Mtrtk78EQ3aJ77_PAAo:-MtsGp4G4M3uY-uWavwd:bx0nhx2) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L57)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

If unspecified in multibody plant, then the default limits will be +/- infinity (right?).  those are not usable for the sliders.

I think the analogy to what I did in python would be e.g. `std::variant<double, Eigen::VectorXd> lower_limit = -1.0`?
</blockquote></details>

Done (added documentation).  The cc file had defaults (same as yours +10.0 / -10.0), it's just wasn't spelled out here. 
___
*[multibody/meshcat/joint_sliders.h, line 64 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16400#-Mts0kldE-i5O8buUKh8:-MtsHI3D85-dp7Fa7vom:bxut7f5) ([raw file](https://github.com/robotlocomotion/drake/blob/3ba2c7eb6d37842a404f3f12b51a547b7eb545f0/multibody/meshcat/joint_sliders.h#L64)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think this one deserves an explicit default value, too?  and perhaps not everybody knows what a "step" means for a gui slider element?  can we just say determinies the discretization size of the slider values?
</blockquote></details>

Done.

The cc file had defaults (same as yours 0.01), it's just wasn't spelled out here.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 14 files at r2, 3 of 5 files at r3, 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),RussTedrake(platform), missing label for release notes (waiting on @rpoyner-tri and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),RussTedrake(platform), missing label for release notes (waiting on @jwnimmer-tri, @rpoyner-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MttO1Sa63YmfiOdxqEI:-MttO1Sa63YmfiOdxqEJ:bevupra) (no related file):*
Working

Still needs a platform reviewer assignment (after feature is done).

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: comment nit

> Reviewed 3 of 14 files at r2, 1 of 5 files at r3, 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400#-:-MttrLOzElzBxvHdQYQR:b-lz9blj)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

___
*[multibody/meshcat/joint_sliders.cc, line 59 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MttofuXDUGxwyhWpKCF:-MttofuY3Iyd4vUjX6UD:b-nu8xl6) ([raw file](https://github.com/robotlocomotion/drake/blob/d6f34cc6271c3deb7fecefa354570a2b0789ebec/multibody/meshcat/joint_sliders.cc#L59)):*
> ```cpp
> // When use_model_instance_name is set, both the joint name and model name will
> // be used to to form the slider name; otherwise, only the joint name is used,
> // unless there are duplicate join names in which case this is force to "true".
> ```

nit: s/this is force to/this is forced to/

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400#-:-Mtxhrdq-JX-hbFnY5H6:b-c7f1bi)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400#-:-MuBjaYh-tjMiNj8vvt5:b4mx0my)* status: 2 unresolved discussions, LGTM missing from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @ggould-tri and @RussTedrake)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 14 files at r2, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400#-:-MuCbv61CDc5YiMtwuqP:bnfp4nl)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[multibody/meshcat/joint_sliders.cc, line 59 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MuCaKuT1Ka2gHvPbgCm:-MuCaKuT1Ka2gHvPbgCn:b-7ilvfz) ([raw file](https://github.com/robotlocomotion/drake/blob/0b6fe985367c29cb23b88194a6a9de3c46190ec0/multibody/meshcat/joint_sliders.cc#L59)):*
> ```cpp
> // When use_model_instance_name is set, both the joint name and model name will
> // be used to to form the slider name; otherwise, only the joint name is used,
> // unless there are duplicate join names in which case this is forced to "true".
> ```

typo:



_Suggestion:_
```cpp
joint
```
___
*[multibody/meshcat/test/joint_sliders_test.cc, line 20 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MuCeM598TokTjs9txpF:-MuCeM598TokTjs9txpG:b-uzhxom) ([raw file](https://github.com/robotlocomotion/drake/blob/0b6fe985367c29cb23b88194a6a9de3c46190ec0/multibody/meshcat/test/joint_sliders_test.cc#L20)):*
> ```cpp
> using geometry::Meshcat;
> 
> class JointSlidersTest : public ::testing::Test {
> ```

minor:  No test coverage of the free body / floating joint case here; I don't know if that's intentional but it would be trivial to test in the current semantics (add a free body to the sdf; nothing else changes).

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @RussTedrake from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @ggould-tri and @rpoyner-tri)

___
*[multibody/meshcat/test/joint_sliders_test.cc, line 20 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16400#-MuCeM598TokTjs9txpF:-MuCmXrN10RpMa6KdLlc:bogkdu7) ([raw file](https://github.com/robotlocomotion/drake/blob/0b6fe985367c29cb23b88194a6a9de3c46190ec0/multibody/meshcat/test/joint_sliders_test.cc#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  No test coverage of the free body / floating joint case here; I don't know if that's intentional but it would be trivial to test in the current semantics (add a free body to the sdf; nothing else changes).
</blockquote></details>

Done (L226 below).

**Comment by jwnimmer-tri** [comment]
Removing -@RussTedrake to keep moving.  Please feel free to post any additional comments after the fact, and I'll work on them.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16400)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Comment by RussTedrake** [comment]
*[multibody/meshcat/joint_sliders.h, line 78 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16400#-N-lQME38fcLIs4LXI8b:-N-lQME38fcLIs4LXI8c:brb2avf) ([raw file](https://github.com/robotlocomotion/drake/blob/46e60f0b62f7f70905651d8547ce1a59228f33f2/multibody/meshcat/joint_sliders.h#L78)):*
> ```objc
>       std::shared_ptr<geometry::Meshcat> meshcat,
>       const MultibodyPlant<T>* plant,
>       std::optional<Eigen::VectorXd> initial_value = {},
> ```

So the reason that my version took a context (not an initial value) is because this version does not allow us to change the Parameters in the Context.  Was there a specific objection to that approach, or perhaps I could open an issue to restore that functionality?

**Comment by jwnimmer-tri** [comment]
I don't recall for certain anymore why I omitted the context.  Mostly likely just to avoid implementation and testing complexity, if I didn't find any extant uses for it.

I think adding an optional argument `const Context<T>* diagram_context = nullptr` to `Run()` sounds fine.  (An overload using a const-reference is also an option, though would be more boilerplate when adding to pydrake bindings.)

**Comment by jwnimmer-tri** [comment]
(If you decide to file an issue, please include an example use case where changing the Parameters is useful.)

**Pull request merged**
