### PR TITLE
[workspace] Improve new_release heuristics

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Address some issues found in #16301

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335#-:-MsqfgcXEWzZI1iefhZv:b-n9fr1a)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[tools/workspace/new_release.py, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16335#-MsuQNFEDpyXV7DIXueB:-Mt3lGCN3uNvf2WPSvNk:b-xcbhrv) ([raw file](https://github.com/robotlocomotion/drake/blob/a69611d2dba5aeb4491c9376d664a17f81cfc977/tools/workspace/new_release.py#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The effect of incorporating the `(\d+)` here is to pin the major version indefinitely.  For the ROS stuff (intel_realsense_ros, ros_xacro) we _do_ want that pin on purpose (to track the last stable ROS for our platforms), but I don't think for petsc nor qhull we want to pin the major version.  I think just `r"v"` might be what we want here?
</blockquote></details>

petsc starting with "v" and qhull staring with a number should be sufficient.
___
*[tools/workspace/new_release.py, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16335#-Mt3eFrD4pgaQ2ltgr-Q:-Mt3laoOA72XgLPhIn2F:bulziez) ([raw file](https://github.com/robotlocomotion/drake/blob/a69611d2dba5aeb4491c9376d664a17f81cfc977/tools/workspace/new_release.py#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I wonder if swapping the true/false sense of this function might end up making the code easier to read.  Could you try it and see what you think?  I am fine with whatever you decide.

If this function was named `def _is_prerelease`, then the calling code would look like this:

```py
if _is_prerelease(commit):
    print("Skipping [etc]")
    continue
```

It's highlighting the out-of-normal condition and the loop retry.  The normal condition would not be part of the else, it could be intended as-normal within the remainder of the loop.

On a related note, we could imagine that the printing happens here as well:
```
def _is_prerelease(commit, workspace):
    prerelease = not any(...)
    if prerelease:
        print("Skipping .... {workspace} ...")
    return prerelease

if _is_prerelease(commit):
    continue  # No printing necessary at all of the callers.
```

</blockquote></details>

Thanks for the suggestion. I was struggling to find a good name in this case, 'prerelease' is what I was searching for.
___
*[tools/workspace/new_release.py, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16335#-MsuQmexAmyLKM6JU7Hp:-Mt3xIrc5myjLFp06hSj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a69611d2dba5aeb4491c9376d664a17f81cfc977/tools/workspace/new_release.py#L122)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If this for-loop doesn't match anything, that should be reported as a problem to the user -- something like "could not find any matching tag for {workspace}".  The important point is that we do _not_ continue on to the subsequent code within this function.  Possibly returning "old_commit, None" would be fine also?  In any case, we can't keep going into `tags_pattern is not None` below.
</blockquote></details>

Done.
___
*[tools/workspace/new_release.py, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16335#-MsuRBQW3de6Vm4e42m9:-Mt4O4fbA9tTcTFWQeg1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a69611d2dba5aeb4491c9376d664a17f81cfc977/tools/workspace/new_release.py#L140)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the assignment to new_commit should only happen when the `_is_stable...` check is true (i.e., move it one line lower)?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335#-:-Mt4X_Qi5sTZrIaUX7-r:b-n37teh)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

___
*[tools/workspace/new_release.py, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16335#-MsuQNFEDpyXV7DIXueB:-Mt4WKySDZdsj1wMr5vt:bjn94lt) ([raw file](https://github.com/robotlocomotion/drake/blob/a69611d2dba5aeb4491c9376d664a17f81cfc977/tools/workspace/new_release.py#L68)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

petsc starting with "v" and qhull staring with a number should be sufficient.
</blockquote></details>

Anything covered by the `()` grouping needs be invariant for all releases of interest to Drake; thus, we don't want to use `+` wilcard.

The syntax for petsc would be:

```
r"^(v)"
```

The  syntax for qhull would be:
```
r"^(2)"
```

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[tools/workspace/new_release.py, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16335#-MsuQNFEDpyXV7DIXueB:-Mt5-8CL-KMnJrUc0SXY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a69611d2dba5aeb4491c9376d664a17f81cfc977/tools/workspace/new_release.py#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Anything covered by the `()` grouping needs be invariant for all releases of interest to Drake; thus, we don't want to use `+` wilcard.

The syntax for petsc would be:

```
r"^(v)"
```

The  syntax for qhull would be:
```
r"^(2)"
```

</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335#-:-Mt51gpn6C9xV6_FSCfW:b-z0s7k5)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335#-:-Mt99LL_5oEuZyrVcCw5:bnfp4nl)* status: missing label for release notes (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16335#-:-Mt99R5d2D-e_TpGShEJ:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
