### PR TITLE
doc/python_bindings: Add caveat for python2 on Mac.

### LINKED ISSUE #7507: Improve drake's python bindings instructions
After running `bazel run install -- ~/drake-build` and add `~/drake-build/lib/python2.7/site-packages` to `PYTHONPATH`, python interpreter crashed when I tried to import pydrake on Mac:
```
dhcp-18-189-90-216:drake-distro pangtao$ python
Python 2.7.14 |Anaconda, Inc.| (default, Oct  5 2017, 02:28:52)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrake
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
dhcp-18-189-90-216:drake-distro pangtao$
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses Russ's [follow-up comment](https://github.com/RobotLocomotion/drake/issues/7507#issuecomment-361097496) in #7507.

Closes #7507.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7894)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@jwnimmer-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-:-L41roNmfpQu6M0omt2Q:btq61i8)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/python_bindings.rst, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L41t-RKZdznDm7Jsr7p:-L41t-RLz-tc-5ypTTfV:b-p4qzhm) ([raw file](https://github.com/robotlocomotion/drake/blob/16641ecf9e95be00d2148fa5e3de3428d5bfb3d6/doc/python_bindings.rst#L75)):*
> ```reStructuredText
>         add the following to ~/.bash_profile:
>           export PATH="/usr/local/opt/python/libexec/bin:$PATH"
> ```

FYI Consider if you want to add (unrendered) comments to both here and `drake/setup/mac/install_prereqs_user_environment.sh` noting how the two are related (editing the paths in one probably means matching edits to the other).  On the other hand, maybe they are unlikely to change often anyway, and divergence would be caught in user testing easily enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-:-L41tMqA78qA3BYeXcoB:bcpz082)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/python_bindings.rst, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L41tVz2XMtbBHiy9M5C:-L41tVz2XMtbBHiy9M5D:b-7fxj7b) ([raw file](https://github.com/robotlocomotion/drake/blob/16641ecf9e95be00d2148fa5e3de3428d5bfb3d6/doc/python_bindings.rst#L66)):*
> ```reStructuredText
> .. note::
> 
>     If you are on Mac, you must ensure that you are using ``python2`` to
> ```

"Homebrew Python" would be more descriptive. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/python_bindings.rst, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L41tVz2XMtbBHiy9M5C:-L42n-MwZE8sxEVgnA9z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16641ecf9e95be00d2148fa5e3de3428d5bfb3d6/doc/python_bindings.rst#L66)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

"Homebrew Python" would be more descriptive. 
</blockquote></details>

Done.

---

*[doc/python_bindings.rst, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L41t-RKZdznDm7Jsr7p:-L42n0EAODF3Y8xONZmV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16641ecf9e95be00d2148fa5e3de3428d5bfb3d6/doc/python_bindings.rst#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider if you want to add (unrendered) comments to both here and `drake/setup/mac/install_prereqs_user_environment.sh` noting how the two are related (editing the paths in one probably means matching edits to the other).  On the other hand, maybe they are unlikely to change often anyway, and divergence would be caught in user testing easily enough.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/python_bindings.rst, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L41tVz2XMtbBHiy9M5C:-L42nF2o1y9nlN3ZWZ-0:b-co85d8) ([raw file](https://github.com/robotlocomotion/drake/blob/16641ecf9e95be00d2148fa5e3de3428d5bfb3d6/doc/python_bindings.rst#L66)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, sorry, I meant if you are on Mac, you need to use Homebrew Python. `python2` is just a symlink that the system Python does not have (the actual binary for Homebrew is called `python2.7` for the record).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/python_bindings.rst, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L41tVz2XMtbBHiy9M5C:-L42oqg1kavVLAPiT9_m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/16641ecf9e95be00d2148fa5e3de3428d5bfb3d6/doc/python_bindings.rst#L66)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

No, sorry, I meant if you are on Mac, you need to use Homebrew Python. `python2` is just a symlink that the system Python does not have (the actual binary for Homebrew is called `python2.7` for the record).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-:-L42pL_IFjraQ35AuA8g:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs_user_environment.sh, line 7 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7894#-L42pecU7qw31UlMdyL6:-L43QPEsqvxRtPS1ER8z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b4a0f96fdadfc970b29b711c576b73090a5891a/setup/mac/install_prereqs_user_environment.sh#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW typo `rts` vs `rst.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7894)*

**Pull request merged**
