### PR TITLE
Switch to Python 3.9 on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
Needs CI update. I cannot get this through without disabling Drake Visualizer for a short while because VTK 8.2 is not allowing Python 3.8 and Python 3.9 to coexist (it just gets very confused, calls the wrong utility library, and crashes, and is an unsupported configuration in any case). Note that I am very deliberately trying to avoid hardcoding Python locations where possible.

(Amazing what a couple of months and a newer Tcl/Tk changes.)

Toward #14243.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
Probably do not want the disabled Drake Visualizer to go into a monthly release, so this may have to wait to merge regardless of review and CI updates.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@soonho-tri for review. Probably lower priority since I do not want this in 0.27.0 (unless I can re-enable Drake Visualizer in time once this merges).

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605#-:-MTcw87NClSAfUv42881:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform), labeled "do not merge" (waiting on @jamiesnape and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTcufPk0FbG5qNfICgM:-MTcufPlC1-nrCAIMu3s:b-83ew90) (no related file):*
nit In the commit message and every place in the code that disclaims visualizer support (e.g., sys.exit error message, unittest explanatory string, etc.), I would like to see an issue citation (probably to a new issue, for clarity) so that a developer who reads the code, or a user who experiences the error message, knows where to go look for more details.  That could be in the form of `TODO(#issue)` or a hyperlink, or whatever.

---

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605#-:-MTevb5U9PgeBb8EFkkC:bnfp4nl)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jamiesnape)

___
*[doc/developers.md, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTewPza0xnX6HfD5DzG:-MTewPza0xnX6HfD5DzH:b1wrowm) ([raw file](https://github.com/robotlocomotion/drake/blob/0f46119e76b0e82366bd2d2b7a7e2575f4abd3d6/doc/developers.md#L69)):*
BTW,

> AdoptOpenJDK 15

Do we still need this while we have https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb#L16 ?
___
*[tools/py_toolchain/interpreter_paths.bzl, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTevnQh1IKeIp8fKTz6:-MTevnQh1IKeIp8fKTz7:bdw1rgo) ([raw file](https://github.com/robotlocomotion/drake/blob/0f46119e76b0e82366bd2d2b7a7e2575f4abd3d6/tools/py_toolchain/interpreter_paths.bzl#L15)):*
> ```Starlark
> # Default value of interpreter_path used by the py_runtime in the default
> # Python toolchain registered on the @platforms//os:osx platform.
> MACOS_INTERPRETER_PATH = "/usr/local/bin/python3.9"
> ```

BTW, this is the only place we use the full path, `/usr/local/bin/python3.9`. Is it possible to find it from `python3.9`?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTcufPk0FbG5qNfICgM:-MTf6Hxm22CA2EJeAMLX:bdmx7z4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In the commit message and every place in the code that disclaims visualizer support (e.g., sys.exit error message, unittest explanatory string, etc.), I would like to see an issue citation (probably to a new issue, for clarity) so that a developer who reads the code, or a user who experiences the error message, knows where to go look for more details.  That could be in the form of `TODO(#issue)` or a hyperlink, or whatever.
</blockquote></details>

So, one of the versions made the case the that disablement was temporary, but I really do not want to commit to that. If I cannot fix it within a release cycle, it may need to be removed completely, and the alternative, staying on Python 3.8 is only going to viable for so long.

I can create an issue saying re-enable Drake Visualizer on macOS, but at the moment, all I know is that it appears to build. If you think a URL is going to comfort users, then, sure I will add it (and basically recount this story), but getting a Python version and a VTK version that work and coexist with an a VTK version that works for Drake is not going to be easy if VTK 8.2 with Python 3.9 does not work (and there aren't really any unit tests of note that make my life particularly easy, and the two Drake-based tests actually make things worse).

FWIW The Drake test suite is completely reliant on a specific VTK version at present, which is no doubt a bug somewhere, since the VTK API is unchanged.

---
___
*[doc/developers.md, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTewPza0xnX6HfD5DzG:-MTf5oTV3bx8crDP2WGV:bnlf7na) ([raw file](https://github.com/robotlocomotion/drake/blob/0f46119e76b0e82366bd2d2b7a7e2575f4abd3d6/doc/developers.md#L69)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW,

> AdoptOpenJDK 15

Do we still need this while we have https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb#L16 ?
</blockquote></details>

My understanding is yes. We have tools that need a Java runtime in the usual location. Bazel is a little vague on whether a JDK is needed (a JRE is certainly not). Jenkins also needs Java, which is why there is a version condition.
___
*[tools/py_toolchain/interpreter_paths.bzl, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTevnQh1IKeIp8fKTz6:-MTf9f6l4WBQtMjayaFy:bmv8ql9) ([raw file](https://github.com/robotlocomotion/drake/blob/0f46119e76b0e82366bd2d2b7a7e2575f4abd3d6/tools/py_toolchain/interpreter_paths.bzl#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this is the only place we use the full path, `/usr/local/bin/python3.9`. Is it possible to find it from `python3.9`?
</blockquote></details>

Good question, I will check, but I think it needs to be a constant. There should also be an autodetecting toolchain now, but not sure if it meets our needs or not.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTcufPk0FbG5qNfICgM:-MTfENC77VKTeJ1Rdwod:b-z5tzc9) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So, one of the versions made the case the that disablement was temporary, but I really do not want to commit to that. If I cannot fix it within a release cycle, it may need to be removed completely, and the alternative, staying on Python 3.8 is only going to viable for so long.

I can create an issue saying re-enable Drake Visualizer on macOS, but at the moment, all I know is that it appears to build. If you think a URL is going to comfort users, then, sure I will add it (and basically recount this story), but getting a Python version and a VTK version that work and coexist with an a VTK version that works for Drake is not going to be easy if VTK 8.2 with Python 3.9 does not work (and there aren't really any unit tests of note that make my life particularly easy, and the two Drake-based tests actually make things worse).

FWIW The Drake test suite is completely reliant on a specific VTK version at present, which is no doubt a bug somewhere, since the VTK API is unchanged.
</blockquote></details>

That's all fine -- and yes, putting that text into an issue is sufficient (perhaps titled "Explore re-enabling drake-visualizer on macOS"?).  I expect that a user who sees the "not supported" message will have questions, and we should provide more information to them.  If nothing else, it's a place where they can subscribe for updates to see the eventual resolution.

---

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605)* status: labeled "do not merge"

**Comment by jamiesnape** [comment]
Ok, I will let the release happen and update the Mac images. If either of you thinks this needs an extra feature review, please assign one, as I am going to be pretty busy with both of those.

**Comment by jwnimmer-tri** [comment]
I think we can count both feature and platform review as satisfied on this one.  It can merge once you're ready.

**Review by soonho-tri — COMMENTED** [review]
Sure.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605#-:-MTfSa8A-v13fdqtiVRK:b-80tlqk)* status: labeled "do not merge"

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @jamiesnape)

___
*[tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py, line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTk9DKQ-hdCCGXdgQAp:-MTk9DKQ-hdCCGXdgQAq:b4frx8y) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bde7dedc1514e7b1e8d03436d6a31b80ccd90b/tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py#L14)):*
> ```Python
>     @unittest.skipIf(
>         sys.platform == "darwin",
>         "Drake Visualizer is disabled on macOS, see see https://git.io/Jt1BG "
> ```

nit, `see see`
___
*[tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py, line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14605#-MTk9Ea71jdYcwYbWKYc:-MTk9Ea71jdYcwYbWKYd:b4frx8y) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bde7dedc1514e7b1e8d03436d6a31b80ccd90b/tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py#L15)):*
> ```Python
>     @unittest.skipIf(
>         sys.platform == "darwin",
>         "Drake Visualizer is disabled on macOS, see see https://git.io/Jt1BG "
> ```

nit, `see see`

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14605)* status: labeled "do not merge"

**Pull request merged**
