### PR TITLE
Add rudimentary ASAN and memcheck builds to Bazel.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4313)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqXH6VecsPZU3Jdm-0:-KXqXH6VecsPZU3Jdm-1:brm9a6t) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L22)):*
> ```
> # Memcheck build.
> build:memcheck -c dbg
> build:memcheck --run_under="/usr/bin/valgrind --leak-check=full --error-exitcode=1"
> ```

This hard-coded path is probably not the right thing to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4313)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/bazel.rc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqYvmarHU6Ou7OdBzh:-KXqYvmarHU6Ou7OdBzi:bx9j3xk) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L14)):*
> ```
> 
> # ASAN build.
> build:asan --strip=never 
> ```

BTW These lines all have trailing whitespace.

---

*[tools/bazel.rc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqZQ1XuZUNuYzvQAVI:-KXqZQ1YaR77E1MTcnbk:bjzo8fy) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L21)):*
> ```
> 
> # Memcheck build.
> build:memcheck -c dbg
> ```

From f2f: the reason for `dbg` was to get line numbers for errors.  I think we can do that with strip=never, and thus get back -O2 which is nicer for performance.  The user can still do `-c dbg` if they in fact wanted non-inlined backtraces.

---

*[tools/bazel.rc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqXH6VecsPZU3Jdm-0:-KXqYLwXvWvyzyVIUyyp:b-scvglj) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L22)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This hard-coded path is probably not the right thing to do?
</blockquote></details>

On Ubuntu, `/usr/bin/valgrind` is 100% fine with me.  We need to see what OSX says, I guess?

---

*[tools/bazel.rc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqYhz_28iuwuZfLL4T:-KXqYhz_28iuwuZfLL4U:b-g59did) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L23)):*
> ```
> build:memcheck -c dbg
> build:memcheck --run_under="/usr/bin/valgrind --leak-check=full --error-exitcode=1"
> ```

BTW Consider adding a `docs/bazel.rst` example of how to invoke these configurations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-:-KXqZl80DLg-98mFGVWV:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4313)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/bazel.rc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqYvmarHU6Ou7OdBzh:-KXqwqkW8HmWTMGahiRc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW These lines all have trailing whitespace.
</blockquote></details>

Done.

---

*[tools/bazel.rc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqZQ1XuZUNuYzvQAVI:-KXqwtl7NsbDSk9uT-uD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

From f2f: the reason for `dbg` was to get line numbers for errors.  I think we can do that with strip=never, and thus get back -O2 which is nicer for performance.  The user can still do `-c dbg` if they in fact wanted non-inlined backtraces.
</blockquote></details>

Done.

---

*[tools/bazel.rc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqXH6VecsPZU3Jdm-0:-KXqxtXorLS2vSTmyNiB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On Ubuntu, `/usr/bin/valgrind` is 100% fine with me.  We need to see what OSX says, I guess?
</blockquote></details>

Done.

---

*[tools/bazel.rc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-KXqYhz_28iuwuZfLL4T:-KXqxIjLn7ILe-eKFw6K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/836b0d7639baac9beb8eef0bbd81793ff1308e9f/tools/bazel.rc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Consider adding a `docs/bazel.rst` example of how to invoke these configurations?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4313)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
ZOMG why didn't I do this weeks ago!  :lgtm_strong: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4313#-:-KXrLPoBq2anB2j7XFvk:bdsf557)*

**Comment by jwnimmer-tri** [comment]
The Bazel build passed; the reds are some kind of superbuild hiccup.  Using override-merge.

**Pull request merged**
