### PR TITLE
[multibody] Add deformable integration test

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
The test exercises the entire discrete update for deformable simulation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105#-:-NEbl4T-AW29OL6iPL9g:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Excellent! just a few notes.

:lgtm: 

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105#-:-NEmFUQG2GKTqH8eLPFN:b89i73w)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.h` line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEm43nyEZCOhsw8cFVr:-NEm43nyEZCOhsw8cFVs:b-a4z9r9) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/deformable_driver.h#L162)):*
> ```objc
>   friend class DeformableDriverContactTest;
>   friend class DeformableDriverContactKinematicsTest;
>   friend class DeformableDriverMultiplexerTest;
> ```

nit, is this friendship  needed anymore?



_Code quote:_
```objc
DeformableDriverMultiplexerTest;
```
___
*[`multibody/plant/test/deformable_integration_test.cc` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmCi9o75AHyj6MgZ5y:-NEmCi9o75AHyj6MgZ5z:b-j8gm3o) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L57)):*
> ```cpp
> /* Contact parameters. */
> const double kSlopeAngle = M_PI / 12.0;             // unit: radian
> const CoulombFriction<double> kFriction{0.4, 0.4};  // tan(π/12) ≈ 0.27 < 0.4.
> ```

minor, This might not be obvious to others. State in the comment why the relevance of `tan(π/12) ≈ 0.27 < 0.4`
___
*[`multibody/plant/test/deformable_integration_test.cc` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmDvTRCYtpsbm0_X3z:-NEmDvTSDjKLnOBdeP1W:bgj42ki) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L61)):*
> ```cpp
> /* Sets up a deformable simulation with a deformable octrahedron centered at the
>  origin of the world frame and a rigid slope weld to the world body. The setup
>  is used to test the discrete updates for deformable bodies in a simulator. */
> ```

nit, add comment on how to visualize this test.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmDPFh1lDSIS_OfXdj:-NEmDPFh1lDSIS_OfXdk:bpeowhc) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L146)):*
> ```cpp
>     body_config.set_mass_density(kMassDensity);
>     body_config.set_stiffness_damping_coefficient(kStiffnessDamping);
>     /* Make the resolution hint large enough so that we get an octahedron. */
> ```

btw, this is a funky way to build the mesh for an octahedron. It relies on the inner workings of the shape reification.
I'd either make this a box or add a check on the number of vertices. Definitely we don't want a sphere or other faceted shape rolling around.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmAsOq3XDLp7Z-CSX9:-NEmAsOq3XDLp7Z-CSXA:b5zabxn) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L159)):*
> ```cpp
>  large enough friction coefficient, the deformable body eventually reaches a
>  static steady state. Verify the contact force applied by the ground to the
>  deformable octahedron balances gravity in the steady state. */
> ```

would you add instructions here on how to properly visualize this?
___
*[`multibody/plant/test/deformable_integration_test.cc` line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmBXGK0-TOqJ68pPq3:-NEmBXGL8fdZOxDL3qeU:b-qtt9uv) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L176)):*
> ```cpp
>   const VectorXd& a = fem_state.GetAccelerations();
>   EXPECT_TRUE(
>       CompareMatrices(a, VectorXd::Zero(a.size()), kVelocityThreshold / kDt));
> ```

nit, the tolerance on acceleration should relate to how close we are to steady state. In this case, if you use `kVelocityThreshold/10`, this test passes.
For velocity, the tolerance has to do more with the regularization of friction used by SAP, so not quite related to acceleration in this case.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmFC1zAhJ0Wpxxggb0:-NEmE1EhDrVmEVjA-ALg:b-ihgmbh) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L184)):*
> ```cpp
>   Vector3d total_contact_force = Vector3d::Zero();
>   for (int i = 0; i < tau_contact.size(); i += 3) {
>     total_contact_force += tau_contact.segment<3>(i);
> ```

nit, probably worth using monogram for `total_contact_force` and a lil explanation on why the expectation for: 1) these additions to be valid and 2) each of these forces to be expressed in the world frame.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)* status: 7 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105#-:-NEbl4T-AW29OL6iPL9g:b-i35568)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/plant/deformable_driver.h` line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEm43nyEZCOhsw8cFVr:-NEqgwTwC8U8LvuRagXd:b-83og3x) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/deformable_driver.h#L162)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, is this friendship  needed anymore?
</blockquote></details>

Nope.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmCi9o75AHyj6MgZ5y:-NEqhtMBDyU71-yu8UHx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L57)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, This might not be obvious to others. State in the comment why the relevance of `tan(π/12) ≈ 0.27 < 0.4`
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmDvTRCYtpsbm0_X3z:-NEqiP-x4DNOmUptmZSr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L61)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, add comment on how to visualize this test.
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmDPFh1lDSIS_OfXdj:-NEqiRAR-qQVaQjLeKmO:b-ae7mia) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L146)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, this is a funky way to build the mesh for an octahedron. It relies on the inner workings of the shape reification.
I'd either make this a box or add a check on the number of vertices. Definitely we don't want a sphere or other faceted shape rolling around.
</blockquote></details>

Done.
We don't have a mesh builder for deformable box yet so I added a check on the number of vertices.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmAsOq3XDLp7Z-CSX9:-NEqjWmh0cwcE1j2gXtH:bo76zj4) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L159)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

would you add instructions here on how to properly visualize this?
</blockquote></details>

Done.

Added a note in the class doc.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmBXGK0-TOqJ68pPq3:-NEqkq3x934BxWgawA6E:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L176)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, the tolerance on acceleration should relate to how close we are to steady state. In this case, if you use `kVelocityThreshold/10`, this test passes.
For velocity, the tolerance has to do more with the regularization of friction used by SAP, so not quite related to acceleration in this case.
</blockquote></details>

Done, thanks.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmFC1zAhJ0Wpxxggb0:-NEqo6DhE0kNTvRkOnR7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L184)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, probably worth using monogram for `total_contact_force` and a lil explanation on why the expectation for: 1) these additions to be valid and 2) each of these forces to be expressed in the world frame.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform with small nits and and q

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105#-:-NEqqNc432o5gxX5YT9N:bhimpci)* status: 5 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/plant/test/deformable_integration_test.cc` line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpZAR6EV4HzSaImm3:-NEqpZAR6EV4HzSaImm4:b-knlstt) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L62)):*
> ```cpp
> const CoulombFriction<double> kFriction{0.4, 0.4};
> 
> /* Sets up a deformable simulation with a deformable octrahedron centered at the
> ```

nit spelling, `octahedron`
___
*[`multibody/plant/test/deformable_integration_test.cc` line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpb7CBnXjMeaNm-SX:-NEqpb7CBnXjMeaNm-SY:b-txie5p) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L63)):*
> ```cpp
> 
> /* Sets up a deformable simulation with a deformable octrahedron centered at the
>  origin of the world frame and a rigid slope weld to the world body. The setup
> ```

nit grammar `weld => welded`, I think?
___
*[`multibody/plant/test/deformable_integration_test.cc` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpJ46A1a8c2Rx-9Tp:-NEqpJ46A1a8c2Rx-9Tq:b-43dtdx) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L66)):*
> ```cpp
>  is used to test the discrete updates for deformable bodies in a simulator.
>  Run
>    `bazel run //tools:meldis -- --open-window` and
> ```

nit Indentation could be considered as formatting for escaped code / shell.

Consider rewriting just as:
```
Run:
   bazel run //tools:meldis -- --open-window
   bazel run //multibody/plant:deformable_integration_test
```
___
*[`multibody/plant/test/deformable_integration_test.cc` line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqq7S94KWFBam5obZP:-NEqq7SA-CNcczGIl8PL:bis2lgd) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L208)):*
> ```cpp
>   /* Computes the total gravitational force on the body. */
>   const double volume = CalcDeformableReferenceVolume();
>   const Vector3d expected_contact_force =
> ```

BTW This is a bit of a dumb question, but is there any way to compute center of pressure as well and somehow relate that to an expected moment?

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)* status: 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/plant/test/deformable_integration_test.cc` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmCi9o75AHyj6MgZ5y:-NEqsByB4ypDL_uhVUgU:bd5l6mr) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L57)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks!
___
*[`multibody/plant/test/deformable_integration_test.cc` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmDvTRCYtpsbm0_X3z:-NEqu_GlB0fryNmE-_lm:b-iptug1) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L61)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks! I can visualize it now 
___
*[`multibody/plant/test/deformable_integration_test.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEmDPFh1lDSIS_OfXdj:-NEqt2To4WhRE5f_yEPV:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/c818a61f348ebe503a79603a2b6afa2990e1dec4/multibody/plant/test/deformable_integration_test.cc#L146)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
We don't have a mesh builder for deformable box yet so I added a check on the number of vertices.
</blockquote></details>

Thanks!

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)* status: 4 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/test/deformable_integration_test.cc` line 62 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpZAR6EV4HzSaImm3:-NErCA4z0rAU8x6APH3W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L62)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit spelling, `octahedron`
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpb7CBnXjMeaNm-SX:-NErCAk86gxQbb7HE23Y:b-puqiz7) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L63)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit grammar `weld => welded`, I think?
</blockquote></details>

Done.

How is "held" past participle but "weld" is not? Sigh.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 66 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpJ46A1a8c2Rx-9Tp:-NErCd3W3MzWKfra96DA:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Indentation could be considered as formatting for escaped code / shell.

Consider rewriting just as:
```
Run:
   bazel run //tools:meldis -- --open-window
   bazel run //multibody/plant:deformable_integration_test
```
</blockquote></details>

Done, thanks.
___
*[`multibody/plant/test/deformable_integration_test.cc` line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqq7S94KWFBam5obZP:-NErCjacAtUZGtF6nm4O:b-d4fym7) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L208)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This is a bit of a dumb question, but is there any way to compute center of pressure as well and somehow relate that to an expected moment?
</blockquote></details>

You could figure out the center of mass from the FEM setup and then get the calculated moment, but right now we don't support that functionality yet. If that turns out to be useful in the future, I'll add it!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/test/deformable_integration_test.cc` line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqpb7CBnXjMeaNm-SX:-NErGman7gdK5LJhIPrq:b-rdq335) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L63)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.

How is "held" past participle but "weld" is not? Sigh.
</blockquote></details>

OK Yay English!
___
*[`multibody/plant/test/deformable_integration_test.cc` line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqq7S94KWFBam5obZP:-NErGqWOEz0VdpVFMXyT:bifkxdp) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L208)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You could figure out the center of mass from the FEM setup and then get the calculated moment, but right now we don't support that functionality yet. If that turns out to be useful in the future, I'll add it!
</blockquote></details>

OK Sounds great, thank you!

Currently, I could see it as a nice feature for say bipedal walking w/ soft feet and doing some level of CoP regulation.
W.r.t. food prep, perhaps there's a table that can topple if as you're rolling dough or what not, where CoP regulation could be done too.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18105)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/test/deformable_integration_test.cc` line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18105#-NEqq7S94KWFBam5obZP:-NErIonk6uVEdWda_BpG:b-c4j8v2) ([raw file](https://github.com/robotlocomotion/drake/blob/8b0dcf43fbdb83a5cee123ea54054095bb89c07b/multibody/plant/test/deformable_integration_test.cc#L208)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Sounds great, thank you!

Currently, I could see it as a nice feature for say bipedal walking w/ soft feet and doing some level of CoP regulation.
W.r.t. food prep, perhaps there's a table that can topple if as you're rolling dough or what not, where CoP regulation could be done too.
</blockquote></details>

Thanks for the context! Yeah, it shouldn't be a hard feature to implement by itself. Feel free to open an issue for tracking when it becomes a priority.

**Pull request merged**
