### PR TITLE
Reenable pydrake common_install_test for everything builds

### LINKED ISSUE #7283: install pydrake tests will fail for -everything (missing libgurobi.so)
When importing pydrake from the installed directory, an error will be thrown:

 ImportError: libgurobi70.so: cannot open shared object file: No such file or directory

Either the install needs to be updated, or `libgurobi70.so` needs to be added to the dynamic library environment variable (e.g. `LD_LIBRARY_PATH`)

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #7283. Fixed by #7592.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7873)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
mac-sierra-clang-bazel-continuous-everything-release

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-continuous-everything-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature and platform review.

**Comment by EricCousineau-TRI** [comment]
:lgtm_strong: :

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7873#-:-L3ov-utCh9z8-oqvDsH:b-yncq55)*

**Pull request merged**
