### PR TITLE
Fix gurobi solver

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Fix the off-diagnoal bug in gurobi_solver, that when adding quadratic costs `0.5 *x'*Q*x+b'*x`, if there exists off-diagonal terms in quadratic cost `Q`, there was a factor of 2 missing.
2. Now `gurobi_solver` can take multiple costs for the same variables, like
`0.5*x'*Q1*x+b1'*x + 0.5*x'*Q2*x+b2'*x`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3792)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@naveenoid for feature review, @jwnimmer-tri for platform review 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KTvpSgck_dZ9hkqrnsx:b9sms2v)*

**Comment by naveenoid** [comment]
Thanks for this very very needed fix. Going to take a pass at it today. 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KTwRvJpgXO5_5uE1Wb_:b-hb2ohi)*

**Comment by naveenoid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-w-ZsALX_iEL370O0:-KU-w-Zt-8Ik8UUKZL8w:b379zr5) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L11)):*
> ```cpp
> template <typename T, int options>
> void checkTriplet(const Eigen::SparseMatrix<T, options>& sp_mat) {
>   auto triplets1 = SparseMatrixToTriplets(sp_mat);
> ```

BTW: Maybe a better name can be found for this variable?

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-w40HIfXakodbXWPv:-KU-w40HIfXakodbXWPw:b-yetike) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L13)):*
> ```cpp
>   auto triplets1 = SparseMatrixToTriplets(sp_mat);
>   Eigen::SparseMatrix<T, options> sp_mat_expected1(sp_mat.rows(),
>                                                    sp_mat.cols());
> ```

BTW: Better name maybe?

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-wO-ODGJQa6XYmCdF:-KU-wO-ODGJQa6XYmCdG:b-yetike) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L24)):*
> ```cpp
>   EXPECT_TRUE(row_indices.size() == col_indices.size());
>   EXPECT_TRUE(row_indices.size() == val.size());
>   std::vector<Eigen::Triplet<T>> triplets2;
> ```

BTW: Better name maybe?

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-wPsKXY3NRR9Rt3dr:-KU-wPsKXY3NRR9Rt3ds:b-i88rly) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L34)):*
> ```cpp
>   EXPECT_TRUE(sp_mat.isApprox(sp_mat_expected2));
> }
> ```

Could you maybe insert a couple of lines identifying what the test is for? (I think I understand but nevertheless..)

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-wcrP_S5wrbdjMXFA:-KU-wcrQXRv6O_i4Yz-o:b-43vizj) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L55)):*
> ```cpp
>   sp_mat3.setFromTriplets(triplet.begin(), triplet.end());
>   checkTriplet(sp_mat3);
> }
> ```

BTW: Perhaps would be good for safety to also have a Gtest for the trivial case of a matrix with no zeros.

---

*[drake/solvers/gurobi_solver.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KTwSMzajRewK2vk35UN:-KTwSMzajRewK2vk35UO:b-ymi4hu) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L79)):*
> ```cpp
>   using std::abs;
>   // record the non-zero entries in the cost 0.5*x'*Q*x + b'*x
>   std::vector<T> Q_nonzero_coefs;
> ```

I see only 2-3 usages of the Eigen::Triplet<double> within a std::vector, maybe you can eliminate the typedef above for clarity?

---

*[drake/solvers/gurobi_solver.cc, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-uGSt1BimHaKELqNw:-KU-uGSt1BimHaKELqNx:b-mxopg9) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L100)):*
> ```cpp
>     }
>     for (int i = 0; i < Q.rows(); i++) {
>       const double Qii = 0.5 * Q(i, i);
> ```

Name of variable. 

---

*[drake/solvers/gurobi_solver.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-uFLkXA5IsNqtzjVd:-KU-uFLkXA5IsNqtzjVe:b-rwp65b) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L106)):*
> ```cpp
>       }
>       for (int j = i + 1; j < Q.cols(); j++) {
>         const double Qij = 0.5 * (Q(i, j) + Q(j, i));
> ```

Name of variable.
https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/solvers/gurobi_solver.cc, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-rcXtpn940QxMbmBy:-KU-rcXtpn940QxMbmBz:b-vbr3e) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L150)):*
> ```cpp
>   }
> 
>   const int error1 = GRBaddqpterms(
> ```

The name of the variable must change https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/solvers/gurobi_solver.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-rm-OwWU0tmVy1Tdq:-KU-rm-OwWU0tmVy1Tdr:b-rwp65b) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L157)):*
> ```cpp
>   }
>   for (int i = 0; i < static_cast<int>(linear_row.size()); i++) {
>     const int error = GRBsetdblattrarray(
> ```

Name of variable.
https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/solvers/test/gurobi_solver_test.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-y3cubgh0urzgcefn:-KU-y3cubgh0urzgcefo:brprggr) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/test/gurobi_solver_test.cc#L68)):*
> ```cpp
> // min 0.5x'Qx + bx = -Q^(-1) * b
> // The values were chosen at random but were hardcoded
> // to enable test reproducibility.
> ```

Maybe you can have a comment in here saying that this test also verifies the solution for an off-diagonal quadratic cost.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-yMArz-zzN65GNu3Q:-KU-yMArz-zzN65GNu3R:bm37iwr) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/test/gurobi_solver_test.cc#L146)):*
> ```cpp
>       CompareMatrices(x.value(), expected, 1e-8, MatrixCompareType::absolute));
> }
> ```

BTW : How about one test comparing Gurobi and Snopt (for instance) on a dense Q matrix and with multiple cost definitions on the decision variables? We can that way also ensure gurobi solution is within some bounds wrt the snopt solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by naveenoid** [comment]
One pass completed. PTAL.

---

Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KU-yhKiQV09GGyH_lEt:bk6bcj6)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-w-ZsALX_iEL370O0:-KU0DvIvNuWamXEEVdko:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L11)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Maybe a better name can be found for this variable?
</details>
Done.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-w40HIfXakodbXWPv:-KU0E64YNdrnviiaODNn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L13)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Better name maybe?
</details>
Done.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-wO-ODGJQa6XYmCdF:-KU0ED_PWl2KxNcTuRWn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L24)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Better name maybe?
</details>
Done.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-wPsKXY3NRR9Rt3dr:-KU0Dc_qzlYXJDmV6kQh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L34)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Could you maybe insert a couple of lines identifying what the test is for? (I think I understand but nevertheless..)
</details>
Done.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-wcrP_S5wrbdjMXFA:-KU0EUSyj5d4L738H3z2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/math/test/eigen_sparse_triplet_test.cc#L55)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: Perhaps would be good for safety to also have a Gtest for the trivial case of a matrix with no zeros.
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KTwSMzajRewK2vk35UN:-KU07V-div2VBQ5ohdpu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L79)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> I see only 2-3 usages of the Eigen::Triplet<double> within a std::vector, maybe you can eliminate the typedef above for clarity?
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-uGSt1BimHaKELqNw:-KU08MmOloUW6QHHWKcX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L100)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Name of variable. 
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-uFLkXA5IsNqtzjVd:-KU08NJFxYv9E72EPtBN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L106)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Name of variable.
> https://google.github.io/styleguide/cppguide.html#Constant_Names
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-rcXtpn940QxMbmBy:-KU08YkKC0wHKnHbfTWD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L150)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> The name of the variable must change https://google.github.io/styleguide/cppguide.html#Constant_Names
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-rm-OwWU0tmVy1Tdq:-KU08ZDd9uh1w4a4dOzC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L157)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Name of variable.
> https://google.github.io/styleguide/cppguide.html#Constant_Names
</details>
Done.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-y3cubgh0urzgcefn:-KU08lE9MDSmllgJi8st:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/test/gurobi_solver_test.cc#L68)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Maybe you can have a comment in here saying that this test also verifies the solution for an off-diagonal quadratic cost.
</details>
Done.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-yMArz-zzN65GNu3Q:-KU0BFzBI3x3qoF41Qy_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/test/gurobi_solver_test.cc#L146)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : How about one test comparing Gurobi and Snopt (for instance) on a dense Q matrix and with multiple cost definitions on the decision variables? We can that way also ensure gurobi solution is within some bounds wrt the snopt solution.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by naveenoid** [comment]
One more pass done. PTAL.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-rcXtpn940QxMbmBy:-KU0iFpYJraiF5729vbR:b-6ord76) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L150)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Done.
</details>
Perhaps you can call it something other than kError1 ? How about `kQAdditionError`?

---

*[drake/solvers/test/CMakeLists.txt, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU0iwPOydA0-5ymEOiW:-KU0iwPPEyPgQQstzsTV:b-hnxqga) ([raw file](https://github.com/robotlocomotion/drake/blob/b78a5fb5f7c07023d20257662736e514b10e0fe1/drake/solvers/test/CMakeLists.txt#L21)):*
> ```CMake
>   drake_add_cc_test(gurobi_solver_test)
>   target_link_libraries(gurobi_solver_test drakeOptimization)
> endif()
> ```

Since you have added a test with Ipopt, I suspect you need to also add a check for if gurobi_FOUND as well as ipopt_FOUND. Or else the test might break Mac builds (ipopt is disabled on Mac AFAIK). OTOH, snopt_c is present in all platforms but still might need a flag check.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-yMArz-zzN65GNu3Q:-KU0jOOsrJmMEelCjYvL:b-cua276) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/test/gurobi_solver_test.cc#L146)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Done.
</details>
There might be a build problem, look at my comment in the test/CMakeLists.txt above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KU0jYdreLQpVOCCh4aw:b-9upnw8)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/CMakeLists.txt, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU0iwPOydA0-5ymEOiW:-KU0lRNCCvHwAk6MJfvx:b-pxt2nw) ([raw file](https://github.com/robotlocomotion/drake/blob/b78a5fb5f7c07023d20257662736e514b10e0fe1/drake/solvers/test/CMakeLists.txt#L21)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Since you have added a test with Ipopt, I suspect you need to also add a check for if gurobi_FOUND as well as ipopt_FOUND. Or else the test might break Mac builds (ipopt is disabled on Mac AFAIK). OTOH, snopt_c is present in all platforms but still might need a flag check.
</details>
On a second through, I feel we should not call snopt in `gurobi_solver_test`. Since we already compute the analytical solution, if the gurobi result matches with the analytical solution, that is already good enough.

Instead, in `mathematical_program_test.cc`, we should add a test to solve QP as a nonlinear optimization problem. I added a test to solve `0.5*x'*Q*x+b'*x` in `mathematical_program_test.cc`. IPOPT works while SNOPT and NLopt fail. I will look into the problem tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/gurobi_solver.cc, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-rcXtpn940QxMbmBy:-KU4SCwa53LTDdo73irj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/gurobi_solver.cc#L150)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Perhaps you can call it something other than kError1 ? How about `kQAdditionError`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/CMakeLists.txt, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU0iwPOydA0-5ymEOiW:-KU4SFisUUjBZ-ptAgdj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b78a5fb5f7c07023d20257662736e514b10e0fe1/drake/solvers/test/CMakeLists.txt#L21)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> On a second through, I feel we should not call snopt in `gurobi_solver_test`. Since we already compute the analytical solution, if the gurobi result matches with the analytical solution, that is already good enough.
> 
> Instead, in `mathematical_program_test.cc`, we should add a test to solve QP as a nonlinear optimization problem. I added a test to solve `0.5*x'*Q*x+b'*x` in `mathematical_program_test.cc`. IPOPT works while SNOPT and NLopt fail. I will look into the problem tomorrow.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/test/gurobi_solver_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KU-yMArz-zzN65GNu3Q:-KU4TyFodGQwS1Fr4RQi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca00a0f2775736c1b351fb472787f6a5e44b3c0/drake/solvers/test/gurobi_solver_test.cc#L146)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> There might be a build problem, look at my comment in the test/CMakeLists.txt above.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KUDr5DXOI7abDZAOUW2:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Thank @naveenoid for the feature review. +@sherm1 for platform review since it is almost Monday

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KUEo76JQ0L792gFfynW:b-i18w64)*

**Comment by sherm1** [comment]
Platform review: A few minor things to fix, then :lgtm:. PTAL.

---

Reviewed 1 of 9 files at r1, 1 of 5 files at r2, 3 of 3 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFI4enYatC3NpOhEao:-KUFI4enYatC3NpOhEap:brcbefs) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/math/test/eigen_sparse_triplet_test.cc#L13)):*
> ```cpp
>  * SparseMatrixToRowColumnValueVectors to get the triplets
>  * (row_index, column_index, value) of the non-zero entries. Then reconstruct
>  * the sparse matrix using setFromTriplets, anch check if the reconstructed
> ```

BTW, typo

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFKApMicMvE10HkJ9z:-KUFKApMicMvE10HkJA-:b-ywxpwa) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/math/test/eigen_sparse_triplet_test.cc#L14)):*
> ```cpp
>  * (row_index, column_index, value) of the non-zero entries. Then reconstruct
>  * the sparse matrix using setFromTriplets, anch check if the reconstructed
>  * sparse matrix is the same as the original one
> ```

BTW, missing ".".

---

*[drake/solvers/gurobi_solver.cc, line 93 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFL36ofgkYkcV54Dr1:-KUFL36ofgkYkcV54Dr2:b-m8qx0c) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/solvers/gurobi_solver.cc#L93)):*
> ```cpp
>     int constraint_variable_count = 0;
>     for (const DecisionVariableView& var : binding.variable_list()) {
>       for (int i = 0; i < static_cast<int>(var.size()); i++) {
> ```

BTW, per [style guide](https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement) pre-increment `++i` is preferred to postincrement `i++` because preincrement is more efficient for object type. For simple types like `int` it doesn't matter and either is allowed. However, I suggest always using pre-increment as a habit so that you'll use it when it does matter. Author's discretion.

---

*[drake/solvers/gurobi_solver.cc, line 158 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFMEusaRlAzh6iED1h:-KUFMEusaRlAzh6iED1i:b4gw3jn) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/solvers/gurobi_solver.cc#L158)):*
> ```cpp
>   }
>   for (int i = 0; i < static_cast<int>(linear_row.size()); i++) {
>     const int kError = GRBsetdblattrarray(
> ```

This is just a variable holding the error routine and should uses a k-is-for-constant name, even though it is const here. See style guide [here](https://google.github.io/styleguide/cppguide.html#Constant_Names) for when to use kNames.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-:-KUFMpMsl7fgH5RYKWob:b-clnlej)*

**Comment by sherm1** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 13 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFI4enYatC3NpOhEao:-KUFPKJTHfpF7pqq41e2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/math/test/eigen_sparse_triplet_test.cc#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, typo
</details>
Done.

---

*[drake/math/test/eigen_sparse_triplet_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFKApMicMvE10HkJ9z:-KUFPLiOSkd95YAA6SJz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/math/test/eigen_sparse_triplet_test.cc#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, missing ".".
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 93 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFL36ofgkYkcV54Dr1:-KUFPWKZrg4thVCPoaYI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/solvers/gurobi_solver.cc#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, per [style guide](https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement) pre-increment `++i` is preferred to postincrement `i++` because preincrement is more efficient for object type. For simple types like `int` it doesn't matter and either is allowed. However, I suggest always using pre-increment as a habit so that you'll use it when it does matter. Author's discretion.
</details>
Done.

---

*[drake/solvers/gurobi_solver.cc, line 158 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3792#-KUFMEusaRlAzh6iED1h:-KUFQMz4cVVEbihQffem:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/92c9cba8285a4a7818328c844364f6d6e283d678/drake/solvers/gurobi_solver.cc#L158)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is just a variable holding the error routine and should uses a k-is-for-constant name, even though it is const here. See style guide [here](https://google.github.io/styleguide/cppguide.html#Constant_Names) for when to use kNames.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3792)*

**Pull request merged**
