### PR TITLE
Adds a dragway_to_urdf application.

### PR DESCRIPTION
**Pull request by liangfok**
Here is a 10 lane dragway that's 120.5m long with lanes that are 3.7 m wide and shoulders that are 3 m wide:

screenshot from 2017-02-15 14 52 49

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5161)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review please. I did not include a unit test because I believe this program is so simple that knowing it compiles is sufficient.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-KczxMuEJlBEqCi7YlMq:b9ks4xf)*

**Comment by liangfok** [comment]
Also, I notice that only one lane in the above screenshow is correctly textured. Is this expected?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-KczxbQxWtb9MC3p10_c:br47yah)*

**Comment by maddog-tri** [comment]
W.r.t. to lack of unit test:  I don't buy the simplicity argument (e.g., it's currently producing slightly broken output already), but any test is going to be some kind of regression test against 3 pretty opaque files, so it is probably not worth it.  (I defer to the platform reviewer on this.)

As for the one-lane of 'lane haze' in the screenshot:  that's a bug!  You should please just fix it in this PR (since this is the first PR to `GenerateObjFile()` for multiple lanes).  The bug is quite obvious in hindsight:  look for `CoverLaneWithQuads(&lane_mesh, segment->lane(0), grid_unit,` [HINT HINT] in `utility/generate_obj.cc`.

Finished initial review, PTAL.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/dragway/test/dragway_to_urdf.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd-7E2sjr36zhqBT09S:-Kd-7E2sjr36zhqBT09T:bnr9128) ([raw file](https://github.com/robotlocomotion/drake/blob/70d1d277a797f46609d36df2317a01eb495c4aef/drake/automotive/maliput/dragway/test/dragway_to_urdf.cc#L38)):*
> ```cpp
>       FLAGS_shoulder_width);
> 
>   const std::string fileroot = "dragway";
> ```

Why is this not a command line option?

If it remains a constant, the output destination should be documented in the command-line help text.

---

*[drake/automotive/maliput/dragway/test/README.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd-8fuJMm8N9JqJku4W:-Kd-8fuJMm8N9JqJku4X:balabul) ([raw file](https://github.com/robotlocomotion/drake/blob/70d1d277a797f46609d36df2317a01eb495c4aef/drake/automotive/maliput/dragway/test/README.md#L5)):*
> ```Markdown
> To run `dragway_to_urdf`, execute:
> 
>     $ cd [directory for holding the generated URDF and OBJ files]
> ```

Do you mean `cd`, or do you mean `mkdir`?  This command should reference `[dirpath]` to tie it together with the next command. 

The most important piece of info is actually `[dirpath] must already exist`.  (User will probably assume sane behavior of relative and absolute directory paths.)

Also... don't forget to mention the `MTL` file, too!  Yay!

---

*[drake/automotive/maliput/dragway/test/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd-8ONFJXZY-jstqygl:-Kd-8ONFJXZY-jstqygm:b-hffx9j) ([raw file](https://github.com/robotlocomotion/drake/blob/70d1d277a797f46609d36df2317a01eb495c4aef/drake/automotive/maliput/dragway/test/README.md#L10)):*
> ```Markdown
>           --length=[length of road in meters] \
>           --num_lanes=[number of lanes] \
>           --shoulder_width=[width of shoulder in meters]
> ```

This text should explain what files will be produced and how they will be named (esp if they are always named "dragway.*" which may be surprising).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd-A3ahb0nHtp1cclQF:b-8730s8)*

**Comment by liangfok** [comment]
> but any test is going to be some kind of regression test against 3 pretty opaque files

I wonder if we could employ some computer vision algorithm to verify that the generated `.urdf`, `.obj`, and `.mtl` files have the correct number of lane and shoulders.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd1HPG6B4BBwaGjepsz:b7imstl)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/dragway/test/dragway_to_urdf.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd-7E2sjr36zhqBT09S:-Kd2JigW9nL4vkmC1JbJ:b-wt0q05) ([raw file](https://github.com/robotlocomotion/drake/blob/70d1d277a797f46609d36df2317a01eb495c4aef/drake/automotive/maliput/dragway/test/dragway_to_urdf.cc#L38)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Why is this not a command line option?

If it remains a constant, the output destination should be documented in the command-line help text.
</blockquote></details>

Done. I made it a command line option.

---

*[drake/automotive/maliput/dragway/test/README.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd-8fuJMm8N9JqJku4W:-Kd2JhGPpoehEHwhIpLp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/70d1d277a797f46609d36df2317a01eb495c4aef/drake/automotive/maliput/dragway/test/README.md#L5)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Do you mean `cd`, or do you mean `mkdir`?  This command should reference `[dirpath]` to tie it together with the next command. 

The most important piece of info is actually `[dirpath] must already exist`.  (User will probably assume sane behavior of relative and absolute directory paths.)

Also... don't forget to mention the `MTL` file, too!  Yay!
</blockquote></details>

Done.

---

*[drake/automotive/maliput/dragway/test/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd-8ONFJXZY-jstqygl:-Kd2JhvjGwdOoS4XaYoc:b-74jach) ([raw file](https://github.com/robotlocomotion/drake/blob/70d1d277a797f46609d36df2317a01eb495c4aef/drake/automotive/maliput/dragway/test/README.md#L10)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

This text should explain what files will be produced and how they will be named (esp if they are always named "dragway.*" which may be surprising).
</blockquote></details>

Done. I expanded the text. The new README.md can be seen here: https://github.com/liangfok/drake/tree/feature/dragway_to_urdf/drake/automotive/maliput/dragway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd2K1UY_gba6XhTIY0e:b-1edt96)*

**Comment by maddog-tri** [comment]
PTAL; one remaining nit with the generate_obj fix.

---

Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 574 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd2g9U4F7eALajH8Ox2:-Kd2g9U4F7eALajH8Ox3:bwpsgoi) ([raw file](https://github.com/robotlocomotion/drake/blob/66db9f76be5938cb332ff045578eb4912fb45766/drake/automotive/maliput/utility/generate_obj.cc#L574)):*
> ```cpp
>                                               features.min_grid_resolution);
>         if (features.draw_lane_haze) {
>           CoverLaneWithQuads(&lane_mesh, segment->lane(li), grid_unit,
> ```

Er, sorry I wasn't more specific before --- but I was imagining replacing `segment->lane(0)` with simply `lane`, i.e., same as the three calls above/below. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd2iefNXQhCuIFOELSI:b60rzk7)*

**Comment by liangfok** [comment]
@maddog-tri I addressed your comment. PTAL. Thanks!

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 574 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-Kd2g9U4F7eALajH8Ox2:-Kd2z3zrQFzbhcgZAruV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66db9f76be5938cb332ff045578eb4912fb45766/drake/automotive/maliput/utility/generate_obj.cc#L574)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Er, sorry I wasn't more specific before --- but I was imagining replacing `segment->lane(0)` with simply `lane`, i.e., same as the three calls above/below. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd2z7SyspMMbWFC3OqO:beb1s44)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd3Uni_Qc7KONuWAd7V:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks! +@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd3WbBjibE0tIb9IpVx:b-2h737r)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5161#-:-Kd7QtBE4g_Mvovqk3LA:bnfp4nl)*

**Pull request merged**
