### PR TITLE
quadrotor: Port dynamics demo to MultibodyPlant

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also port the dynamics acceptance test to `MultibodyPlant`, including removing some directly-tested conditions (e.g., `EvalTimeDerivatives`).  In the rewrite, we only inspect the final pose after falling.  This is MUCH simpler given the differing generalized coordinates, but should still be sufficient coverage to discover any errors in the velocities or accelerations.

Relates #12158.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12726)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This still needs some polish, and in particular one unit test is failing.

**Comment by jwnimmer-tri** [comment]
Yeah, I knew I should be using the MbP accessor APIs -- it's just such a pain.  I'll update to use those soon.

**Comment by sherm1** [comment]
cc @mitiguy -- RollPitchYaw saves the day!

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by jwnimmer-tri** [comment]
Or maybe split it and merge the unit test changes now, but leave the demo for later?

**Pull request merged**
