### PR TITLE
Overhaul maliput's RightOfWayRule in order to handle yield logic.

### PR DESCRIPTION
**Pull request by maddog-tri**
The overall design is much improved, even without the yield aspect
(which, it turns out, is a really important aspect).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature-review.  (Welcome back!)

@stonier in case he is interested in the code which accompanies the design doc changes.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDOgnhc8xAHBLQ6i_hY:b-emvdls)*

**Comment by liangfok** [comment]
Completed first pass.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDmfKt09RVhUsomzC2N:-LDmfKt09RVhUsomzC2O:b-6jo17d) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L55)):*
> ```objc
>                     ///  exit the zone.
>     kStopAllowed    ///< Vehicles are allowed to stop within the zone.
>   };
> ```

Are we anticipating additional zone types in the future? If not, would a bool be sufficient?

I'm also wondering whether `kStopProhibited` would be clearer.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqd2hR-UgxK6Si7CGX:-LDqd2hR-UgxK6Si7CGY:b-3jpj0y) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L62)):*
> ```objc
>   /// basically "Go", "Stop", or "Stop, Then Go".  A RightOfWayRule
>   /// may have multiple possible States, thus each State has an Id
>   /// which must be unique within the context of the RightOfWayRule.
> ```

BTW, consider "a RightOfWayRule" instead of "the RightOfWayRule".

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqeyfiC39iuC4217ow:-LDqeyfiC39iuC4217ox:b-7og8sf) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L66)):*
> ```objc
>   /// A State also describes the yield logic of a RightOfWayRule, via
>   /// a list of Id's of other RightOfWayRules (and thus the zones
>   /// which they control) which have priority over this rule.  An
> ```

This documentation should specify what happens when another rule has priority over this rule. What state does this rule take on when it is overridden by a higher priority rule?

(Or maybe this should simply cite the appropriate section in the documentation being added in #8885).

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqclw10gnogcDsOlGC:-LDqclw10gnogcDsOlGD:b-bm77ye) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L82)):*
> ```objc
>     enum Type {
>       kGo = 0,              ///< Vehicle has right-of-way and may proceed if
>                             ///. safe to do so.
> ```

BTW, extra period after ///?

(Same comment regarding kStop below.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqgLAY6DwUXejnx_6m:-LDqgLAY6DwUXejnx_6n:b-hd65jc) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L147)):*
> ```objc
> 
>   /// Returns true if the rule is static, i.e., has no dynamic state,
>   /// otherwise false..
> ```

Extra period.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 191 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqbQOJCzvVQj7i9RK4:-LDqbQOJCzvVQj7i9RK5:bxihyp0) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L191)):*
> ```objc
>     RightOfWayRule::State::Id current_id;
>     /// Information about the rule's upcoming State if a state transition
>     /// is known to be imminent.
> ```

BTW, consider deleting "to be imminent" since the transition time is specified by `Next::duration_until`.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.h, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDrB09S26xcSYuijKbD:-LDrB09S26xcSYuijKbE:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.h#L3)):*
> ```objc
> #pragma once
> 
> #include <unordered_map>
> ```

Unused.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDrAxRi1uKxXRRhO7X_:-LDrAxRi1uKxXRRhO7Xa:b-9xm2iq) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.h#L17)):*
> ```objc
> 
> ```

BTW, extra newline.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDro_Ix0EYpaR60Rqsq:-LDro_Ix0EYpaR60Rqsr:b-5tt6xn) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc#L42)):*
> ```cpp
>   AssertionResultCollector c;
>   MALIPUT_ADD_RESULT(c, MALIPUT_IS_EQUAL(a.size(), b.size()));
>   int smallest = std::min(a.size(), b.size());
> ```

BTW, `const`.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDrrEmx6WYWI3ING00D:-LDrrEmx6WYWI3ING00E:b-t2u2ub) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/simplerulebook/yaml_io.cc#L120)):*
> ```cpp
>   RightOfWayRule::State::YieldGroup group;
>   for (const YAML::Node element : node) {
>     group.emplace_back(element.as<std::string>());
> ```

BTW, should there be a check here verifying that the yield-to rule ID exists?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDruRT93TSqOFodNLE4:bl4rucz)*

**Comment by maddog-tri** [comment]
Comments addressed.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDmfKt09RVhUsomzC2N:-LDsOFt5EhcouIeBBGGD:b39h69d) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Are we anticipating additional zone types in the future? If not, would a bool be sufficient?

I'm also wondering whether `kStopProhibited` would be clearer.
</blockquote></details>

I'm not particularly anticipating any more types, but either way, a two-value enum with descriptive names generally leads to better clarity than a bare bool.

(Personally, I like "excluded" better than "prohibited" --- that latter seems overly strict, and the former has (for me) the imagery of stopped cars being nudged/pushed out of the zone.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqd2hR-UgxK6Si7CGX:-LDsDHuv9efZ_IZwfKv1:bmg28hl) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L62)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider "a RightOfWayRule" instead of "the RightOfWayRule".
</blockquote></details>

How about this?

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqeyfiC39iuC4217ow:-LDsGKBlCi8feOerkJt2:b-6mr40b) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L66)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This documentation should specify what happens when another rule has priority over this rule. What state does this rule take on when it is overridden by a higher priority rule?

(Or maybe this should simply cite the appropriate section in the documentation being added in #8885).
</blockquote></details>

Done, as in "I done something."  Does this help?

The rule doesn't change its "type"... it's just that the lower-priority vehicles have to yield, which generally means to stay out of the way of higher priority vehicles --- but that doesn't, e.g., mean that they have to stop.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqclw10gnogcDsOlGC:-LDsHDaB-ZC00y_fcHFN:b-v0gj5c) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L82)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, extra period after ///?

(Same comment regarding kStop below.)
</blockquote></details>

Done (I suspect some quirk of emacs re-wrapping.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqgLAY6DwUXejnx_6m:-LDsHQIv6HJyYn27zncZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L147)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Extra period.
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 191 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDqbQOJCzvVQj7i9RK4:-LDsIwDM19HLgTVLjfcW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/rules/right_of_way_rule.h#L191)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "to be imminent" since the transition time is specified by `Next::duration_until`.
</blockquote></details>

Done.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.h, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDrB09S26xcSYuijKbD:-LDsJ65A4VVtpfCBJDRD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.h#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDrAxRi1uKxXRRhO7X_:-LDsJ9U24lZURiCNeYt7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.h#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, extra newline.
</blockquote></details>

Done.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDro_Ix0EYpaR60Rqsq:-LDsJPjZ5rBYxJbKPCBi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 120 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDrrEmx6WYWI3ING00D:-LDsJfQL6gvyiklJlHoL:b-7ymofj) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/simplerulebook/yaml_io.cc#L120)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should there be a check here verifying that the yield-to rule ID exists?
</blockquote></details>

Such a check would have to occur after all the rules have been loaded (since these ID's could reference other yet-to-be-loaded RightOfWayRule instances).

It could be good to have an structure-checker method for SimpleRulebook, but I wouldn't want to futz with that in this PR.  I'll add a TODO, though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDsPXu43lxbJlJnVH5X:bel95ya)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDro_Ix0EYpaR60Rqsq:-LDsdhrV3XD5AaCIX2P8:b3qgb7o) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc#L42)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, no change?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDse4-A2swciEuYobqd:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDro_Ix0EYpaR60Rqsq:-LDsttRgCTOyn4O7YL3h:btadbqb) ([raw file](https://github.com/robotlocomotion/drake/blob/4ce8a64458f23f54e4b24450e52944ad63314b85/automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, no change?
</blockquote></details>

Oops... accidentally undid it before the commit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDsuh-_AtEdZsLTF9Oj:bxwr5c8)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 82 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtdvA6B7tNLKKJWGhG:-LDtdvA6B7tNLKKJWGhH:bryej5) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/api/rules/right_of_way_rule.h#L82)):*
> ```objc
> 
>     /// Basic semantic type of a rule state.
>     enum Type {
> ```

BTW, can we make it `enum class Type` as we have `enum class ZoneType` above?

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 111 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtczt9Czrgs-_Fc4PK:-LDtcztABBDd0sxLBQrX:b-7pdhm9) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/api/rules/right_of_way_rule.h#L111)):*
> ```objc
>    private:
>     Id id_;
>     Type type_;
> ```

Need `{}` per C++ guide.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 167 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDte8yQ-a5E408g3zRh:-LDte8yQ-a5E408g3zRi:b-7pdhm9) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/api/rules/right_of_way_rule.h#L167)):*
> ```objc
>   Id id_;
>   LaneSRoute zone_;
>   ZoneType zone_type_;
> ```

Need `{}` per C++ guide.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtaN3o979Obf2atP4m:-LDtaN3o979Obf2atP4n:b-uptkxh) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/simplerulebook/yaml_io.cc#L99)):*
> ```cpp
> 
> 
> RightOfWayRule::State::Type UnpackRightOfWayStateType(YAML::Node node) {
> ```

META, `YAML::Node` -> `const YAML::Node&` in function arguments in the file

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 121 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtbCrMASL0JLHx9zO9:-LDtbCrN66quuq02Dc0-:b7wymgh) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/simplerulebook/yaml_io.cc#L121)):*
> ```cpp
>   DRAKE_THROW_UNLESS(node.IsSequence());
>   RightOfWayRule::State::YieldGroup group;
>   for (const YAML::Node element : node) {
> ```

META, `for (const YAML::Node ` -> `for (const YAML::Node& ` in the file

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDwAnWW8KRpdE0Dc4k9:bnfp4nl)*

**Comment by maddog-tri** [comment]
Comments addressed.

---

Review status: 8 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 82 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtdvA6B7tNLKKJWGhG:-LDwHecb2f1IDdsSlnZ3:b-uaj3ua) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/api/rules/right_of_way_rule.h#L82)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, can we make it `enum class Type` as we have `enum class ZoneType` above?
</blockquote></details>

Done.  (Yeah: the lack of implicit conversion to `int` makes scoped enums +1 if such a conversion is not necessary and especially if the underlying integer values are irrelevant.)

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 111 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtczt9Czrgs-_Fc4PK:-LDwCCY19w-Spyc62tby:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/api/rules/right_of_way_rule.h#L111)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Need `{}` per C++ guide.
</blockquote></details>

Done.

---

*[automotive/maliput/api/rules/right_of_way_rule.h, line 167 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDte8yQ-a5E408g3zRh:-LDwCEu2AZcNe8PjclA6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/api/rules/right_of_way_rule.h#L167)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Need `{}` per C++ guide.
</blockquote></details>

Done.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtaN3o979Obf2atP4m:-LDwFztHDJJw5lmdRkSw:ble2km6) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/simplerulebook/yaml_io.cc#L99)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META, `YAML::Node` -> `const YAML::Node&` in function arguments in the file
</blockquote></details>

Done.  

(I had stopped bothering with `const YAML::Node&` because of YAML::Node is basically a smart-pointery/referency thing anyway.  Gah, the `yaml-cpp` documentation is so bad.)

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 121 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtbCrMASL0JLHx9zO9:-LDwHNti23nPklPULgxo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/simplerulebook/yaml_io.cc#L121)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META, `for (const YAML::Node ` -> `for (const YAML::Node& ` in the file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886#-:-LDwOZaMCYfpHRc9sAAZ:bel95ya)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/simplerulebook/yaml_io.cc, line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtaN3o979Obf2atP4m:-LDwQt_r19kcAYpjyIDo:b-z8hlaz) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/simplerulebook/yaml_io.cc#L99)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Done.  

(I had stopped bothering with `const YAML::Node&` because of YAML::Node is basically a smart-pointery/referency thing anyway.  Gah, the `yaml-cpp` documentation is so bad.)
</blockquote></details>

OK.

I'm new to the `yaml-cpp` stuff. But I thought that `YAML::Node`'s definition is at https://github.com/jbeder/yaml-cpp/blob/master/include/yaml-cpp/node/node.h#L29-L135 (I might be wrong). FYI, I have `sizeof(YAML::Node) == 32` on my mac.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886)*

**Comment by maddog-tri** [comment]
*[automotive/maliput/simplerulebook/yaml_io.cc, line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8886#-LDtaN3o979Obf2atP4m:-LDwVcG583s8B_3dIXPb:b74amct) ([raw file](https://github.com/robotlocomotion/drake/blob/8b24410e7b979abbff96d5dbab0389c3c2e8f66b/automotive/maliput/simplerulebook/yaml_io.cc#L99)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK.

I'm new to the `yaml-cpp` stuff. But I thought that `YAML::Node`'s definition is at https://github.com/jbeder/yaml-cpp/blob/master/include/yaml-cpp/node/node.h#L29-L135 (I might be wrong). FYI, I have `sizeof(YAML::Node) == 32` on my mac.
</blockquote></details>

Yeah, I didn't say it was teeny-tiny, I just meant that it's not copying a graph of other node objects --- just a bool, a shared_ptr, and a plain pointer.  (But, yes, there was no good reason not to use `const YAML::Node&`.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8886)*

**Pull request merged**
