### PR TITLE
Update Eigen to recent commit on default branch

### PR DESCRIPTION
**Pull request by tkoolen**
Only required two minor fixes.
See https://github.com/RobotLocomotion/eigen-pod/pull/7.
Fixes https://github.com/RobotLocomotion/drake/issues/3211.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3227)

### CODE REVIEW

**Comment by tkoolen** [comment]
I don't understand why the msvc-ninja-32 build failed; seems like there are no build errors and no failed tests. Can someone help me understand?

**Comment by jwnimmer-tri** [comment]
CDash is down (#3230):
>   Error when uploading file: C:/Users/Administrator/workspace/experimental/0b4ef046/drake/build/Testing/20160823-1555/Test.xml
>   Error message was: The requested URL returned error: 404 Not Found
>   Problems when submitting via HTTP
>   Error when uploading file: C:/Users/Administrator/workspace/experimental/0b4ef046/drake/build/Testing/20160823-1555/Upload.xml
>   Error message was: The requested URL returned error: 404 Not Found
>   Problems when submitting via HTTP

**Comment by tkoolen** [comment]
Ah, OK.

**Comment by jwnimmer-tri** [comment]
+@bradking could you review the `FunctionForm` changes for us?

**Comment by ggould-tri** [comment]
I was impressed by how wrong Eigen's documentation indexing is when I tried to track down the motivation for these changes.  The changelog is useless and the docs show the wrong version number.

Anyway I believe the `Literal` below is correct.  The `Div` usage isn't documented, but I pawed through Eigen source enough to be confident that it is right, although surprising.

I can't find any justification for the `dot` fix, although it looks obviously correct.

From my state of relative ignorance, :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3227#-:-KPsifq3S91bE--XctmR:bf4jyq4)*

**Comment by bradking** [comment]
:lgtm:

Ideally the commit that changes `FunctionalForm` should explain in its commit message that Eigen 3.3 introduces additional `NumTraits` that we need to provide.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3227#-:-KPst0h3z5hWI8odJv2f:bd8wx6t)*

**Comment by amcastro-tri** [comment]
Excellent! Eager to try with #3145!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3227#-:-KPwIYojZdrP_zHz9_Tp:b-khgm49)*

**Comment by tkoolen** [comment]
@ggould-tri, yes the `Div` thing appears to currently be undocumented. Literal is explained in the devel docs: http://eigen.tuxfamily.org/dox-devel/structEigen_1_1NumTraits.html.

Do note that this is not an official release version, so maybe they just didn't get around to updating the docs yet. I ran into several issues with the latest official release, 3.3 beta 2, related to `AutoDiffScalar`. These have been fixed in the commit I'm currently pointing to.

How does this work these days, am I just allowed to merge this myself?

**Comment by jwnimmer-tri** [comment]
@tkoolen Yeah, once you have two LGTMs (and jenkins passes) you can merge yourself.  (I almost merged this already, but wasn't sure if you wanted to rebase-amend the commit message per Brad's suggestion.)

**Pull request merged**
