### PR TITLE
Update drake instructions to include cpp lint integration with CLion

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This gives instructions (and appropriate user warnings) for setting up cpp lint to run within CLion such that the warning messages become clickable links.  The instructions have been run through by one independent part so far with success (@sherm1).

+@sammy-tri for platform review and +@amcastro-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4027)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
My branch was *not* what I was expecting to see...I'm going to resolve it before renewing this PR.

**Comment by SeanCurtis-TRI** [comment]
Branch is now good and ready for review.  PTAL

+@sammy-tri for platform review and +@amcastro-tri for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVkE76Zjb0o3WEP3h6g:bcd47c3)*

**Comment by amcastro-tri** [comment]
It still doesn't work for me....

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/clion.rst, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkeUn3uOR1QOpG67wt:-KVkeUn3uOR1QOpG67wu:bcpntmu) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L121)):*
> ```reStructuredText
> 
>    :Name: Cpp Lint File
>    :Description: Apply cpp lint to the current file.
> ```

BTW, should it say `cpplint`? (with no space)

---

*[drake/doc/clion.rst, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkebRm-lCR4S00ptxV:-KVkebRm-lCR4S00ptxW:b-8qmszq) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L122)):*
> ```reStructuredText
>    :Name: Cpp Lint File
>    :Description: Apply cpp lint to the current file.
>    :Program: $ProjectFileDir$/common/test/cpplint_wrapper.py
> ```

BTW, nice!

---

*[drake/doc/clion.rst, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkcKtp1aVzYr6XHHgs:-KVkcKtp1aVzYr6XHHgt:b-qovgq7) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L125)):*
> ```reStructuredText
>    :Parameters: $FilePath$
>    :Working directory: $ProjectFileDir$
> 5. Make sure that *only* the following Options are checked (the "Synchronize files after execution" is unnecessary because cpp lint is a read-only operation):
> ```

BTW, `cpplint` as one "word" with no spaces?

---

*[drake/doc/clion.rst, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkg8sUSca_6VdKv9xh:-KVkg8sVsHh76iwrHJJr:b9p30uw) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L158)):*
> ```reStructuredText
> ^^^^^^^^^
> The external tools can be executed by going to Tools > External Tools > [Tool Name].
> ```

I just right click on a file tab and run it form the "External tools" menu. Could you add how to do this on a per-file basis?

---

*[drake/doc/clion.rst, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkfY1LCFefaIGGYVtS:-KVkfY1LCFefaIGGYVtT:budon9z) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L167)):*
> ```reStructuredText
> cpp lint on the full project, but it is still possible.  So, confirm that the
> console reports zero warnings. This is particularly important when evaluating
> the full project; cpplint wil print hundreds of "." characters which the 
> ```

typo "wil"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVkgBh7njH6UUS0ZIpX:bbtf3fc)*

**Comment by amcastro-tri** [comment]
The first time I just run into the "race condition" issue @seancurtis-tri mentions in the doc. This really works! (besides the race condition which is a CLion problem) and I like it uses Drake's `cpplint_wrapper`. Besides some little comments :lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVkhWf_HPEjlV658m0q:bzhlu40)*

**Comment by sherm1** [comment]
I have also tested out Sean's instructions with great results (except for the race condition which happened once). This is *really* helpful! :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVkr-huvHyRf_3jjKQW:b-mxinlc)*

**Comment by SeanCurtis-TRI** [comment]
I've added a change which *should* eliminate the race condition.  It requires an update to the cpplint_wrapper.py. 

In short: the script writes progress to std out and warnings to std err.  In CLion they both go to the same console.  The race condition between these two streams is what appears to cause the problem.  I've added a new argument where CLion can tell the script to serialize all output to a common stream.  This seems to eliminate the race condition. 

PTAL

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVkuwpnFIErklH-mBda:b-bw8vpy)*

**Comment by sherm1** [comment]
@jwnimmer-tri, do you want to feature review the change to cpplint_wrapper.py?

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVkyEDyrkQtNVUOgjk8:b-t9x5qv)*

**Comment by jwnimmer-tri** [comment]
I think it should be fine for everything to go to stdout.  I suggest changing the `print >>sys.stderr, line` to just use stdout unconditionally.

**Comment by sammy-tri** [comment]
:lgtm: though I did not verify the CLion functionalify (thanks to those who did)

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVlCO_b0pYvv9FVln8l:b7cqq6q)*

**Comment by SeanCurtis-TRI** [comment]
I'd assumed stderr was there for a reason.  If I can dump straight to stdout without the flag I'll do so.

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/doc/clion.rst, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkeUn3uOR1QOpG67wt:-KVlM4E13QAMxQoIic3T:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L121)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, should it say `cpplint`? (with no space)
</details>
Done

---

*[drake/doc/clion.rst, line 122 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkebRm-lCR4S00ptxV:-KVlM58CbmefTRT7G01m:bqotzd) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L122)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, nice!
</details>
BTW thanks

---

*[drake/doc/clion.rst, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkcKtp1aVzYr6XHHgs:-KVlM6rq4ExluyN5OMxr:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L125)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, `cpplint` as one "word" with no spaces?
</details>
Done

---

*[drake/doc/clion.rst, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkg8sUSca_6VdKv9xh:-KVlQqAZkj1TMPQK3myD:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L158)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I just right click on a file tab and run it form the "External tools" menu. Could you add how to do this on a per-file basis?
</details>
Done

---

*[drake/doc/clion.rst, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkfY1LCFefaIGGYVtS:-KVlQrUxCQDYIoWru8WF:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L167)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> typo "wil"
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVlQwGa8ZQe_-wOLMjP:b-2ihf38)*

**Comment by jwnimmer-tri** [comment]
Looks :ok: on the cpplint_wrapper code changes, thanks!  (I probably had a reason for stderr originally, but I think at this point (after some rewrites) it's since became vestigial.  I'm glad to have it gone.)

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/clion.rst, line 101 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVllWphg42TT0QXNes6:-KVllWphg42TT0QXNes7:b-smpi8o) ([raw file](https://github.com/robotlocomotion/drake/blob/03ef3c2bb1d8244f84e47592d8d02eda0372abaa/drake/doc/clion.rst#L101)):*
> ```reStructuredText
> 4. On the right panel, choose Set from > Predefined Style > Google
> 
> Integrating Cpplint in CLion
> ```

BTW: consider adding a named anchor before this line. Something like:

```
.. _integrating_cpplint_with_clion:
```

---

*[drake/doc/clion.rst, line 103 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVlloGxaZpDef97dplQ:-KVlloGxaZpDef97dplR:b4lo9td) ([raw file](https://github.com/robotlocomotion/drake/blob/03ef3c2bb1d8244f84e47592d8d02eda0372abaa/drake/doc/clion.rst#L103)):*
> ```reStructuredText
> Integrating Cpplint in CLion
> ============================
> This will give you the ability to execute cpplint on a single file or the full
> ```

BTW, consider surrounding `cpplint` with double-backticks so it shows up in mono-space font, which indicates it's a thing.

---

*[drake/doc/clion.rst, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVlmMV91m2Oemt8BPPa:-KVlmMV91m2Oemt8BPPb:b-ecfieg) ([raw file](https://github.com/robotlocomotion/drake/blob/03ef3c2bb1d8244f84e47592d8d02eda0372abaa/drake/doc/clion.rst#L176)):*
> ```reStructuredText
> To check the whole project, in the menu bar, select ``Tools`` > 
> ``External Tools`` > ``Cpplint Project`` (alternatively, this can also be
> done through the right-click context menu.)
> ```

BTW: nit: missing period at end of sentence. Also, consider making the text inside of the parenthesis its own sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/clion.rst, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVkg8sUSca_6VdKv9xh:-KVvVos1MaIaURZ0TS2K:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/5c38d880b998ab82524d91a2409f8ab223d117a1/drake/doc/clion.rst#L158)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary>
> Done
</details>
Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027)*

**Comment by SeanCurtis-TRI** [comment]
The stderr-ectomy is complete.  I also do appendices and wisdom teeth.

---

Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/clion.rst, line 101 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVllWphg42TT0QXNes6:-KVzkkgSDObG7y363paL:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/03ef3c2bb1d8244f84e47592d8d02eda0372abaa/drake/doc/clion.rst#L101)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: consider adding a named anchor before this line. Something like:
> 
> ```
> .. _integrating_cpplint_with_clion:
> ```
</details>
Done

---

*[drake/doc/clion.rst, line 103 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVlloGxaZpDef97dplQ:-KVzklsI10th4FyCv5AI:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/03ef3c2bb1d8244f84e47592d8d02eda0372abaa/drake/doc/clion.rst#L103)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider surrounding `cpplint` with double-backticks so it shows up in mono-space font, which indicates it's a thing.
</details>
Done

---

*[drake/doc/clion.rst, line 176 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-KVlmMV91m2Oemt8BPPa:-KVzkvRy2aEkphHE-qR_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/03ef3c2bb1d8244f84e47592d8d02eda0372abaa/drake/doc/clion.rst#L176)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: missing period at end of sentence. Also, consider making the text inside of the parenthesis its own sentence.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4027#-:-KVzl-DohBJC6q_NvBLa:b-symb58)*

**Pull request merged**
