### PR TITLE
Adds Workaround Documentation For "No module named vtkCommonCorePython" Error.

### LINKED ISSUE #4738: VTK issues with drake_visualizer when ros-indigo-tmc-desktop-full installed
When trying to run the drake_visualizer via
```bash
roscd
..
./install/bin/drake_visualizer
```
The following error appears:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/toyota/dev/drake_catkin_workspace/install/lib/python2.7/dist-packages/director/drakevisualizer.py", line 5, in <module>
    import director.objectmodel as om
  File "/home/toyota/dev/drake_catkin_workspace/install/lib/python2.7/dist-packages/director/objectmodel.py", line 4, in <module>
    from director.propertyset import PropertySet, PropertyAttributes, PropertyPanelHelper
  File "/home/toyota/dev/drake_catkin_workspace/install/lib/python2.7/dist-packages/director/propertyset.py", line 2, in <module>
    from director.fieldcontainer import FieldContainer
  File "/home/toyota/dev/drake_catkin_workspace/install/lib/python2.7/dist-packages/director/fieldcontainer.py", line 1, in <module>
    import vtk
  File "/usr/lib/python2.7/dist-packages/vtk/__init__.py", line 39, in <module>
    from vtkCommonCore import *
  File "/usr/lib/python2.7/dist-packages/vtk/vtkCommonCore.py", line 1, in <module>
    from vtkCommonCorePython import *
ImportError: No module named vtkCommonCorePython
```

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4738.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4765)

### CODE REVIEW

**Comment by liangfok** [comment]
+@kunimatsu-tri for feature review please.
+@jwnimmer-tri for platform review please.
\CC: @athackst

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaISym7oZbVrkTZyLN-:b-e23q7f)*

**Comment by kunimatsu-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 342 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJAl2_i5Oivvixpxys:-KaJAl2_i5Oivvixpxyt:bqgfum0) ([raw file](https://github.com/robotlocomotion/drake/blob/38fd923fe4c626e6585b9c410e8bc2e7d8dbcb8c/drake/doc/from_source.rst#L342)):*
> ```reStructuredText
> (``drake-visualizer`` is built on Director, which is built on VTK5)::
> 
>     cd drake-distro/build/drake/externals/director
> ```

This part also should be:
```
cd drake-distro/build/externals/director
```

---

*[drake/doc/from_source.rst, line 352 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJBkWXgL7uKFKuFb1H:-KaJBkWYyyJm0-Nehf8f:brwmhp3) ([raw file](https://github.com/robotlocomotion/drake/blob/38fd923fe4c626e6585b9c410e8bc2e7d8dbcb8c/drake/doc/from_source.rst#L352)):*
> ```reStructuredText
>     cd drake-distro
>     export LD_LIBRARY_PATH=`pwd`/build/install/lib/vtk-5.10:$LD_LIBRARY_PATH
>     export PYTHONPATH=`pwd`/build/externals/director/src/vtk-build/Wrapping/Python:`pwd`/build/externals/director/src/vtk-build/bin:$PYTHONPATHPython:$HOME/dev/drake_catkin_workspace/build/drake/externals/director/src/vtk-build/bin:$PYTHONPATH
> ```

I guess this is just mistakenly copied/pasted, but the correct path is perhaps:
```
export PYTHONPATH=`pwd`/build/externals/director/src/vtk-build/Wrapping/Python:`pwd`/build/externals/director/src/vtk-build/bin:$PYTHONPATH
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by liangfok** [comment]
@kunimatsu-tri I addressed your comments. PTAL. Thanks!

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 342 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJAl2_i5Oivvixpxys:-KaJGYwhz6xiTtQRNzlU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fd923fe4c626e6585b9c410e8bc2e7d8dbcb8c/drake/doc/from_source.rst#L342)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

This part also should be:
```
cd drake-distro/build/externals/director
```
</blockquote></details>

Done.

---

*[drake/doc/from_source.rst, line 352 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJBkWXgL7uKFKuFb1H:-KaJGZlaHMaOHg9YCmKG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fd923fe4c626e6585b9c410e8bc2e7d8dbcb8c/drake/doc/from_source.rst#L352)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I guess this is just mistakenly copied/pasted, but the correct path is perhaps:
```
export PYTHONPATH=`pwd`/build/externals/director/src/vtk-build/Wrapping/Python:`pwd`/build/externals/director/src/vtk-build/bin:$PYTHONPATH
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJGluDwMKVgP0iMXYU:bslvl2g)*

**Comment by jwnimmer-tri** [comment]
Please re-add me (or whoever) for review once feature review and local testing is entirely completed.
-@jwnimmer-tri 

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJH3UKrxHNpAdzRAPj:b-1s6d6p)*

**Comment by kunimatsu-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJHUYl27K-OpZt5See:bnfp4nl)*

**Comment by liangfok** [comment]
@kunimatsu-tri: Thanks.
+@jwnimmer-tri for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJHfAE-tNrehd2p08b:barjsl9)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJI-cwsUmkqI3naDEq:-KaJI-cxxZK5vZxV1A84:b-vefnjr) ([raw file](https://github.com/robotlocomotion/drake/blob/493812d316509149b1bf06db27aa6c94c0bbbd23/drake/doc/from_source.rst#L314)):*
> ```reStructuredText
>     bazel
> 
> .. _drake_fix_drake_visualizer:
> ```

This new text seems much more appropriate for http://drake.mit.edu/faq.html instead of the common-mode instructions?

The content looks okay to me though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJIVsVnq2Fuuw28hrf:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJI-cwsUmkqI3naDEq:-KaJIgVwjozhdfcQ4BUj:bc5ohei) ([raw file](https://github.com/robotlocomotion/drake/blob/493812d316509149b1bf06db27aa6c94c0bbbd23/drake/doc/from_source.rst#L314)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This new text seems much more appropriate for http://drake.mit.edu/faq.html instead of the common-mode instructions?

The content looks okay to me though.
</blockquote></details>

Good point. I think adding a FAQ is a good idea. I've updated this PR to include a short FAQ.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJN-0t7azPw4e-z2aQ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJI-cwsUmkqI3naDEq:-KaJN1m1WjsuB1D6jm1-:b-4znbv2) ([raw file](https://github.com/robotlocomotion/drake/blob/493812d316509149b1bf06db27aa6c94c0bbbd23/drake/doc/from_source.rst#L314)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Good point. I think adding a FAQ is a good idea. I've updated this PR to include a short FAQ.
</blockquote></details>

I meant that all this detail clutters up the main instructions, such that this text should _only_ live in the FAQ.  That's where all of the other "Derp!  My build doesn't work" help goes.

At most, a single line in this doc that says "if you see error message FOO check the FAQ" would be my preference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/from_source.rst, line 314 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJI-cwsUmkqI3naDEq:-KaJNYjdGZGWSUtxnSrk:b-lk6jdu) ([raw file](https://github.com/robotlocomotion/drake/blob/493812d316509149b1bf06db27aa6c94c0bbbd23/drake/doc/from_source.rst#L314)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I meant that all this detail clutters up the main instructions, such that this text should _only_ live in the FAQ.  That's where all of the other "Derp!  My build doesn't work" help goes.

At most, a single line in this doc that says "if you see error message FOO check the FAQ" would be my preference.
</blockquote></details>

OK I'll do that. Stay tuned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by jwnimmer-tri** [comment]
Actually one more request.  Once this is updated, could you ask jamiesnape or mwoehlke-kitware for an extra feature review?  Possibly they will spot something that the rest of us missed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJNxjCkDf2ySDNXovN:b25723z)*

**Comment by liangfok** [comment]
@jwnimmer-tri: I addressed your comments. PTAL. Thanks.

+@jamiesnape for a second feature review please. Thanks.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJQPbEwW4uIFFOWGLc:bocyai0)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 4 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/faq.rst, line 55 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJRHPAaTrSg8k8IXcC:-KaJRHPAaTrSg8k8IXcD:b-2b2kpg) ([raw file](https://github.com/robotlocomotion/drake/blob/267db20faf98d72acc5006fa4e254813585f35ba/drake/doc/faq.rst#L55)):*
> ```reStructuredText
>     make (or ninja)
> 
> Next, modify a couple environment variables before starting
> ```

`a couple of` or `two` or `these`

---

*[drake/doc/faq.rst, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJRXSon0M3RluR4g_f:-KaJRXSon0M3RluR4g_g:b-qhwsz3) ([raw file](https://github.com/robotlocomotion/drake/blob/267db20faf98d72acc5006fa4e254813585f35ba/drake/doc/faq.rst#L60)):*
> ```reStructuredText
>     cd drake-distro
>     export LD_LIBRARY_PATH=`pwd`/build/install/lib/vtk-5.10:$LD_LIBRARY_PATH
>     export PYTHONPATH=`pwd`/build/externals/director/src/vtk-build/Wrapping/Python:`pwd`/build/externals/director/src/vtk-build/bin:$PYTHONPATH
> ```

In the unlike event of a having a space in `LD_LIBRARY_PATH` or `PYTHONPATH` in `pwd` would this break?

---

*[drake/doc/faq.rst, line 79 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJSJYw2jI_bYkVe5S-:-KaJSJYw2jI_bYkVe5S0:b-2b2kpg) ([raw file](https://github.com/robotlocomotion/drake/blob/267db20faf98d72acc5006fa4e254813585f35ba/drake/doc/faq.rst#L79)):*
> ```reStructuredText
>     catkin build
> 
> Next, modify a couple environment variables before starting
> ```

`a couple of` or `two` or `these`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/faq.rst, line 55 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJRHPAaTrSg8k8IXcC:-KaJU9DsN7HrN93D6Shy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/267db20faf98d72acc5006fa4e254813585f35ba/drake/doc/faq.rst#L55)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`a couple of` or `two` or `these`
</blockquote></details>

Done.

---

*[drake/doc/faq.rst, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJRXSon0M3RluR4g_f:-KaJUng4bkr875-UgfvQ:bc7c5c2) ([raw file](https://github.com/robotlocomotion/drake/blob/267db20faf98d72acc5006fa4e254813585f35ba/drake/doc/faq.rst#L60)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

In the unlike event of a having a space in `LD_LIBRARY_PATH` or `PYTHONPATH` in `pwd` would this break?
</blockquote></details>

Good question. I will need to test this to find out. For now, I've added a brief note saying it's only been tested on directory paths containing no spaces.

---

*[drake/doc/faq.rst, line 79 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-KaJSJYw2jI_bYkVe5S-:-KaJUBe5_YODt_95vZOY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/267db20faf98d72acc5006fa4e254813585f35ba/drake/doc/faq.rst#L79)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`a couple of` or `two` or `these`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by kunimatsu-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765#-:-KaJXmxfnB4Swuj-76AR:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4765)*

**Pull request merged**
