### PR TITLE
Add ellipsoid shape specification

### PR DESCRIPTION
**Pull request by tehbelinda**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12256)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@damrongguoy for feature review please

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.h, line 203 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12256#-LsOF17T4ri5Vg6X50I6:-LsP-t_u5eW-hRuSlCFv:bcdx8ga) ([raw file](https://github.com/robotlocomotion/drake/blob/97fafbe3d2b376fb72672d076c6b1f24783c0fc0/geometry/shape_specification.h#L203)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I've been regretting the "get_" prefix on these simple accessors for a while. We might want to do a follow-up PR where we deprecate all of the `get_` variants in favor of just `radius()`, `length()`, etc.
</blockquote></details>

should I make an issue for it?
actually this one doesn't have an issue either so not sure if it all needs to be

**Comment by tehbelinda** [comment]
+@soonho-tri for platform review please

**Comment by jwnimmer-tri** [comment]
Many big changes on master, let's make sure PRs are up to date:
@drake-jenkins-bot retest this please

**Comment by tehbelinda** [comment]
___
*[geometry/shape_specification.h, line 203 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12256#-LsOF17T4ri5Vg6X50I6:-LsXiQwPDc9rqFHm_fRC:b-k6u4ue) ([raw file](https://github.com/robotlocomotion/drake/blob/97fafbe3d2b376fb72672d076c6b1f24783c0fc0/geometry/shape_specification.h#L203)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Ok. @tehbelinda could create a Github issue and assign to all three of us, so we won't forget.
</blockquote></details>

https://github.com/RobotLocomotion/drake/issues/12290

**Pull request merged**
