### PR TITLE
Adds a 10-Lane Dragway Demo With 10 TrajectoryCar Vehicles and One SimpleCar Vehicle.

### LINKED ISSUE #4990: Implement a Multi-Lane Demo Using Hard-Coded Dragway
This will build upon #4989 . Perhaps using the "MOBIL" lane-change decision model.

This will also need a lane change planner. The planner could be as simple as specifying the time by which the car must be in the new lane.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4990.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5185)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-Kd6m7Ha8yJX_H8mt6Uq:b-5klkw7)*

**Comment by liangfok** [comment]
@jwnimmer-tri just informed me that there shoudn't be a "demo enum" selector. I'm thus going to apply the "do not review" label while I remove this feature.

**Comment by liangfok** [comment]
I've updated this PR to have a "road network enum" rather than a "demo enum". @maddog-tri, this PR is now ready to be reviewed.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdBVU4sRtSYBwxITwgx:b-sq19a6)*

**Comment by liangfok** [comment]
I'm labeling this "Do No Review" until after I resolve the merge conflicts that were caused by the recent merging of #5167 into `master`.

**Comment by liangfok** [comment]
Dear @maddog-tri, I resolved all merge conflicts and believe this PR is ready to be reviewed again.

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review please. Thanks!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdR9WO4jUpTGrZUN9FK:b-1bcdxl)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/BUILD, line 374 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS2fZW7KcrzJjI58eR:-KdS2fZW7KcrzJjI58eS:b8zlxmx) ([raw file](https://github.com/robotlocomotion/drake/blob/756e07e3b2f28b14ccbcad69f78ab982ad82b11c/drake/automotive/BUILD#L374)):*
> ```Python
> 
> py_binary(
>     name = "demo_dragway_with_trajectory_car",
> ```

Having an explosion of py_binary names seems wrong.  Why not just let the user be able to type in these flags with help from README.md instructions?  The dragway params here can turn into the defaults in the binary (so they never need to be written down anywhere else, be it here or the README), and so then the user just chooses the `--road_network` on the command-line (and the default stays as "1").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS71YQUKt_9niPuzmT:-KdS71YQUKt_9niPuzmU:b-64pjfp) (no related file):*
+(status: do not review) 

The substantial `automotive_demo` refactoring is impossible to inspect when mixed in with the functional changes of adding dragway.  How were you even able to self-review this PR with diffs like that?  Please either (1) rework this PR so that the automotive_demo diffs are minimal (e.g. by shuffling the order functions around -- I can't tell if this would work or not) or else (2) submit a feature-neutral `automotive_demo` refactoring PR that separates out a portion of these changes to review and merge first, and then we'll return to this PR.

---

*[drake/automotive/automotive_simulator.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS4FPCEnFKjy554tzN:-KdS4FPCEnFKjy554tzO:b-hf5sxp) ([raw file](https://github.com/robotlocomotion/drake/blob/756e07e3b2f28b14ccbcad69f78ab982ad82b11c/drake/automotive/automotive_simulator.h#L149)):*
> ```objc
>   /// @pre Start() has NOT been called.
>   const maliput::api::RoadGeometry* SetRoadGeometry(
>       std::unique_ptr<const maliput::api::RoadGeometry>* road);
> ```

When transferring ownership of a unique_ptr, pass it by-value, not by-pointer.  (And in that case, the ownership transfer is obvious and doesn't need the parenthetical API comment.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by liangfok** [comment]
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS71YQUKt_9niPuzmT:-KdSPr-jintLsJhOIPTn:b-18rj5l) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

+(status: do not review) 

The substantial `automotive_demo` refactoring is impossible to inspect when mixed in with the functional changes of adding dragway.  How were you even able to self-review this PR with diffs like that?  Please either (1) rework this PR so that the automotive_demo diffs are minimal (e.g. by shuffling the order functions around -- I can't tell if this would work or not) or else (2) submit a feature-neutral `automotive_demo` refactoring PR that separates out a portion of these changes to review and merge first, and then we'll return to this PR.
</blockquote></details>

I will submit a sequence of PRs that eventually cumulate in this PR.

---

*[drake/automotive/automotive_simulator.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS4FPCEnFKjy554tzN:-KdSRdGanrXVW4gsY2CN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/756e07e3b2f28b14ccbcad69f78ab982ad82b11c/drake/automotive/automotive_simulator.h#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When transferring ownership of a unique_ptr, pass it by-value, not by-pointer.  (And in that case, the ownership transfer is obvious and doesn't need the parenthetical API comment.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS71YQUKt_9niPuzmT:-KdSbGbbhEw7dQ6zkxGz:bhjwzb8) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I will submit a sequence of PRs that eventually cumulate in this PR.
</blockquote></details>

I also read through master a bit more.  Really, the problem is that endless / infinite have no business being part of this demo or codebase, so rather than curating them, I think we should evict them.  I can help discuss and implement that a bit later this evening.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 5 files at r2.
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by liangfok** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS71YQUKt_9niPuzmT:-KdSuxd2_H4aNjR_c20O:buv87p9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I also read through master a bit more.  Really, the problem is that endless / infinite have no business being part of this demo or codebase, so rather than curating them, I think we should evict them.  I can help discuss and implement that a bit later this evening.
</blockquote></details>

Aha. I'm happy to discuss. Just let me know when / where.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by liangfok** [comment]
I've addressed all reviewer comments. PTAL. Thanks.

---

Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/BUILD, line 374 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdS2fZW7KcrzJjI58eR:-KdVRwj8qsdHqMr-ZTyF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/756e07e3b2f28b14ccbcad69f78ab982ad82b11c/drake/automotive/BUILD#L374)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Having an explosion of py_binary names seems wrong.  Why not just let the user be able to type in these flags with help from README.md instructions?  The dragway params here can turn into the defaults in the binary (so they never need to be written down anywhere else, be it here or the README), and so then the user just chooses the `--road_network` on the command-line (and the default stays as "1").
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdVS1rvsfHO-8MbAgWG:b-j0bpur)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 115 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVkp2U0qS1GlIBrRs0:-KdVkp2VHf50uIF8x6al:bj4b6pz) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/automotive_demo.cc#L115)):*
> ```cpp
> // flags.
> const maliput::api::RoadGeometry*
>     AddDragway(AutomotiveSimulator<double>* simulator) {
> ```

_Meta_ Bad indent.

---

*[drake/automotive/automotive_demo.cc, line 127 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVl0RQwwqKLPglRZTo:-KdVl0RQwwqKLPglRZTp:b-lpg086) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/automotive_demo.cc#L127)):*
> ```cpp
> 
> // Adds the terrain to the world. The type of terrain added depends on command
> // line flag `road_network`. See `enum RoadNetworkType` above for the types of
> ```

Stale comment about "command line flag road_network".

---

*[drake/automotive/automotive_demo.cc, line 163 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVlMTNufPhP85BK-NH:-KdVlMTOBBlYjawzSTWR:bjxju2q) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/automotive_demo.cc#L163)):*
> ```cpp
>   const maliput::api::RoadGeometry* road_geometry =
>       AddTerrain(road_network_type, simulator.get());
>   AddVehicles(road_network_type, simulator.get(), road_geometry);
> ```

_Meta_ The simulator argument to be modified should be consistently either first or last, not in the middle.

---

*[drake/automotive/README.md, line 36 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVk2ync3gLWoEVbCQS:-KdVk2yo7nKbtt5bIqDc:blbkju5) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/README.md#L36)):*
> ```Markdown
> any window, or Ctrl-C in the terminal.  All of the launched programs will be
> closed.
>  
> ```

BTW Trailing whitespace.

---

*[drake/automotive/README.md, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVkGN6D5hhx7gDMkJX:-KdVkGN6D5hhx7gDMkJY:b-rujjkw) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/README.md#L76)):*
> ```Markdown
>        --dragway_length=150 \
>        --dragway_lane_width=3.7 \
>        --dragway_shoulder_width=3 \
> ```

Why make us type the prior three lines?  Either they are sensible defaults that go into `automotive_demo.cc`, or they are unusual and shouldn't be in the README.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 115 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVkp2U0qS1GlIBrRs0:-KdVtlLeQjcBp0vzB7ZK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/automotive_demo.cc#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Bad indent.
</blockquote></details>

Done.

---

*[drake/automotive/automotive_demo.cc, line 127 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVl0RQwwqKLPglRZTo:-KdVtyMQaDh-TgHLP9bp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/automotive_demo.cc#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Stale comment about "command line flag road_network".
</blockquote></details>

Done.

---

*[drake/automotive/automotive_demo.cc, line 163 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVlMTNufPhP85BK-NH:-KdVu6O8caikqOWtccXY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/automotive_demo.cc#L163)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ The simulator argument to be modified should be consistently either first or last, not in the middle.
</blockquote></details>

Done.

---

*[drake/automotive/README.md, line 36 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVk2ync3gLWoEVbCQS:-KdVuBaSBtjwll1eQqYt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/README.md#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Trailing whitespace.
</blockquote></details>

Done.

---

*[drake/automotive/README.md, line 76 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdVkGN6D5hhx7gDMkJX:-KdVuHUj8vOLGGT7OIu3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1194c21d8cbc694371973d656280c04db4d598a5/drake/automotive/README.md#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why make us type the prior three lines?  Either they are sensible defaults that go into `automotive_demo.cc`, or they are unusual and shouldn't be in the README.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdVufBVv9fgeMIsUJXl:bblnx7i)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdVxcNpbGbiGWXU3OrW:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@liangfok Sorry, this conflicts a little with master now that #5237 went in and will need a merge.

**Comment by liangfok** [comment]
Thanks for the note. Done.

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by maddog-tri** [comment]
Reviewed 3 of 8 files at r1, 1 of 2 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 24 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWpGaM2GjJHnhKqV3W:-KdWpGaNzBOyiIGHZieS:b-jlf804) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L24)):*
> ```cpp
>               "Number of seconds to simulate.");
> 
> DEFINE_int32(num_dragway_lanes, 0, "The number of lanes on the dragway.");
> ```

Zero is a surprising default value.   (E.g., does it really mean "a dragway with no lanes"?)

---

*[drake/automotive/automotive_demo.cc, line 27 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWjV6lgOKD2IQaILT5:-KdWjV6mYNUfzIGUDGIC:bds8upo) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L27)):*
> ```cpp
> DEFINE_double(dragway_length, 100, "The length of the dragway.");
> DEFINE_double(dragway_lane_width, 3.7, "The dragway lane width.");
> DEFINE_double(dragway_shoulder_width, 3.0, "The dragway's shoudler width.");
> ```

Misspelilng.

---

*[drake/automotive/automotive_demo.cc, line 155 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWpgE-KwVMYSxtgcqK:-KdWpgE-KwVMYSxtgcqL:b-l66fnk) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L155)):*
> ```cpp
> 
> int main(int argc, char* argv[]) {
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
> ```

BTW:  For the record, I think `gflags` is a terrible design ("Let's pretend it's 1992 again.  Party on, Global Variables!").  Use of a `FLAGS_*` global anywhere besides `main()` means that you have poorly documented functions with underspecified declarations and contracts, and it is difficult to understand what such functions will do by looking at their call sites.

---

*[drake/automotive/create_trajectory_params.h, line 36 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWkD2kUhKSEXZbzQdR:-KdWkD2kUhKSEXZbzQdS:b-oe00s4) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/create_trajectory_params.h#L36)):*
> ```objc
>  * @return tuple of curve, speed, start_time
>  */
> std::tuple<Curve2<double>, double, double> CreateTrajectoryParamsForDragway(
> ```

This function only operates correctly on a `maliput::dragway::RoadGeometry`, yet it accepts a generic `maliput::api::RoadGeometry` input.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/automotive_demo.cc, line 24 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWpGaM2GjJHnhKqV3W:-KdWt1pWgX6jgWnngzhc:b-n89xoz) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L24)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Zero is a surprising default value.   (E.g., does it really mean "a dragway with no lanes"?)
</blockquote></details>

Yes. It is by default zero to disable the dragway. I added a comment clarifying this.

---

*[drake/automotive/automotive_demo.cc, line 27 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWjV6lgOKD2IQaILT5:-KdWtf3_S0Rxd88sCCeH:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L27)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Misspelilng.
</blockquote></details>

Done. Thanks.

---

*[drake/automotive/automotive_demo.cc, line 155 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWpgE-KwVMYSxtgcqK:-KdWtlmXb377nw3vYevG:b-dvtgtq) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L155)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

BTW:  For the record, I think `gflags` is a terrible design ("Let's pretend it's 1992 again.  Party on, Global Variables!").  Use of a `FLAGS_*` global anywhere besides `main()` means that you have poorly documented functions with underspecified declarations and contracts, and it is difficult to understand what such functions will do by looking at their call sites.
</blockquote></details>

That's a good point. Maybe a future PR can modify this file to only use `FLAGS_*` in `main()`?

---

*[drake/automotive/create_trajectory_params.h, line 36 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWkD2kUhKSEXZbzQdR:-KdWudMVUDAS6-vZVvCu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/create_trajectory_params.h#L36)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

This function only operates correctly on a `maliput::dragway::RoadGeometry`, yet it accepts a generic `maliput::api::RoadGeometry` input.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdWueswfZax2QOHdZU5:bblnx7i)*

**Comment by maddog-tri** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.cc, line 24 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWpGaM2GjJHnhKqV3W:-KdWzcdPA0ocyN-V0KR1:b-i8i4jf) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes. It is by default zero to disable the dragway. I added a comment clarifying this.
</blockquote></details>

How about moving the sentiment of that comment into the help-string for `num_dragway_lanes` instead?  It's kind of vital to understanding what `--num_dragway_lanes` does; no need to bury it in the source code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by liangfok** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.cc, line 24 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-KdWpGaM2GjJHnhKqV3W:-KdX1E1dplaD52e6L5s1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8577c58aabe9a527da0dc97d401ddfa09d28cf28/drake/automotive/automotive_demo.cc#L24)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

How about moving the sentiment of that comment into the help-string for `num_dragway_lanes` instead?  It's kind of vital to understanding what `--num_dragway_lanes` does; no need to bury it in the source code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185#-:-KdX6BdoZtdsBeAbhkwp:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. I'm now waiting on CI.

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 4 files at r6, 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5185)*

**Pull request merged**
