### PR TITLE
Adds Missing explicit instantiation of RigidBodyTree::doKinematics(q,v,bool)

### PR DESCRIPTION
**Pull request by liangfok**
Where `q` and `v` are blocks of matrices.
Resolves https://github.com/RobotLocomotion/drake/issues/2634.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2637)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for feature review since he identified the problem and solution.
+@ggould-tri for platform review since it's Friday.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KL-b69UjMljc8ywB70F:541756249)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KL1r7CLDE0Pae8sP-Ln:1417088721)*

**Comment by david-german-tri** [comment]
nit for PR description: `q` and `v` are blocks of vectors.

:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2413 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1sFtkwyaMN3ENo4WQ:-KL1sFtkwyaMN3ENo4WR:-1159547610) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/RigidBodyTree.cpp#L2413)):*
> ```cpp
>     Eigen::MatrixBase<Eigen::Map<VectorXd const>> const&,
>     Eigen::MatrixBase<Eigen::Map<VectorXd const>> const&, bool) const;
> template DRAKERBM_EXPORT KinematicsCache<double> RigidBodyTree::doKinematics(
> ```

Nit: This should live alongside the `const` version above.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 189 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1sTwu9M3U-jlaGR-m:-KL1sTwu9M3U-jlaGR-n:788082933) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L189)):*
> ```cpp
> 
> // Ensures RigidBodyTree::doKinemantics(q, v, bool) is explicitly instantiated
> // with matrix block input parameters. For more information, see:
> ```

vector block

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 201 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1s_2w5RV8lS-S4rdT:-KL1s_2xot_eepJHpZXd:1416411079) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L201)):*
> ```cpp
>   v.setZero();
> 
>   auto q_block = q.head(q.size());
> ```

BTW, it might be more readable to use explicit types here, even though they're verbose (since those types are the point of the test).  Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KL1s7L_4wRsjkuPgHDo:-512484932)*

**Comment by amcastro-tri** [comment]
Minor comments. Besides those :lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 2 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL2ahYc1eiBOVOSnX-j:-KL2ahYd6sHfldeLp3AC:-212355193) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L2)):*
> ```cpp
> #include <iostream>
> ```

In PR #2596 I am adding a test in `drake/systems/plants/test/rigid_body_tree/rbt_collisions_test.cc`. Probably a good idea to create this folder in this PR? (since it'll get merged faster I think) so we have all the RBT tests in one place and also it gets organized in a similar way to the tests for RBS in the `rigid_body_system` directory.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 194 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL2c-xRtP0aRojUUfoX:-KL2c-xSeQrEokhgZ1j5:-766017207) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L194)):*
> ```cpp
>   tree->addRobotFromURDF(Drake::getDrakePath() +
>           "/systems/plants/test/two_dof_robot.urdf");
>   Eigen::Matrix<double, Eigen::Dynamic, 1> q;
> ```

Notice now you can include `#include "drake/common/eigen_types.h"` and use `VectorX<double>`.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 201 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1s_2w5RV8lS-S4rdT:-KL2bPocV_Xt1hr9RIxk:-2097997214) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L201)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, it might be more readable to use explicit types here, even though they're verbose (since those types are the point of the test).  Up to you.
</details>
+1 to more verbose types here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KL2cDyjGzdSKjhD15-4:-1520125628)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2413 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1sFtkwyaMN3ENo4WQ:-KL4NOJLLNdNj78ILFoO:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/RigidBodyTree.cpp#L2413)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Nit: This should live alongside the `const` version above.
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 2 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL2ahYc1eiBOVOSnX-j:-KL2d5iwhVPvgLPi0J7l:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> In PR #2596 I am adding a test in `drake/systems/plants/test/rigid_body_tree/rbt_collisions_test.cc`. Probably a good idea to create this folder in this PR? (since it'll get merged faster I think) so we have all the RBT tests in one place and also it gets organized in a similar way to the tests for RBS in the `rigid_body_system` directory.
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 189 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1sTwu9M3U-jlaGR-m:-KL2_DQfjMYdZzf6Bga6:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L189)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> vector block
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 194 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL2c-xRtP0aRojUUfoX:-KL2duki7sY_M4sUj9Wb:-994610322) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L194)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Notice now you can include `#include "drake/common/eigen_types.h"` and use `VectorX<double>`.
</details>
Nice. fixed.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 201 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1s_2w5RV8lS-S4rdT:-KL2_PTcndo4x0q8pce4:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree_test.cc#L201)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, it might be more readable to use explicit types here, even though they're verbose (since those types are the point of the test).  Up to you.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KL4PipyEiRYxnLb8LnA:-84625242)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2288/ and is thus ready for review.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KL6KR72CZeyhDNST20e:-1383474118)*

**Comment by liangfok** [comment]
Looks like there are a few unresolved comments from +@amcastro-tri and @david-german-tri.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KLGgKAlFxT7QKFJFsPn:-340486227)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/CMakeLists.txt, line 1 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KLH1kbAsTKs3ZZmmlsX:-KLH1kbBmcqqBYnXls8n:2078987901) ([raw file](https://github.com/robotlocomotion/drake/blob/8414195cfad05405f5e03d0a0ed0a8c5a4b2cb90/drake/systems/plants/test/rigid_body_system/CMakeLists.txt#L1)):*
> ```CMake
> add_executable(rigid_body_system_test rigid_body_system_test.cc)
> ```

why do we need to remove the `GTEST_FOUND` here?

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 201 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1s_2w5RV8lS-S4rdT:-KLH32mD12dUrILW3ndH:811421009) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L201)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
I  am pretty sure Eigen determines the `InnerPanel` argument automatically for you (in none of their examples the user explicitly provides it). Also, the first `-1` corresponds to `Eigen::Dynamic`.
So, would this compile? (I think it'd read better): 

```C++
Eigen::VectorBlock<VectorX> q_block;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637)*

**Comment by david-german-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_system/CMakeLists.txt, line 1 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KLH1kbAsTKs3ZZmmlsX:-KLH9NGHpABVkOxhetsC:838897092) ([raw file](https://github.com/robotlocomotion/drake/blob/8414195cfad05405f5e03d0a0ed0a8c5a4b2cb90/drake/systems/plants/test/rigid_body_system/CMakeLists.txt#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> why do we need to remove the `GTEST_FOUND` here?
</details>
GTest is required in the superbuild, so `GTEST_FOUND` is not useful.  (I introduced the `GTEST_FOUND` virus back in March, and it's been copy-pasted all over since then.  My bad.  Kudos to @liangfok for helping clean it up.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_system/CMakeLists.txt, line 1 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KLH1kbAsTKs3ZZmmlsX:-KLHKLaHePW4IFoNC6if:1266549400) ([raw file](https://github.com/robotlocomotion/drake/blob/8414195cfad05405f5e03d0a0ed0a8c5a4b2cb90/drake/systems/plants/test/rigid_body_system/CMakeLists.txt#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> GTest is required in the superbuild, so `GTEST_FOUND` is not useful.  (I introduced the `GTEST_FOUND` virus back in March, and it's been copy-pasted all over since then.  My bad.  Kudos to @liangfok for helping clean it up.)
</details>
I see, thanks!. I've been propagating this virus also. I'll help fixing in future PR's with GTests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637)*

**Comment by ggould-tri** [comment]
Reviewed 6 of 8 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 201 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1s_2w5RV8lS-S4rdT:-KLHtcrsce6_eNRnx1Iu:-687627188) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L201)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I  am pretty sure Eigen determines the `InnerPanel` argument automatically for you (in none of their examples the user explicitly provides it). Also, the first `-1` corresponds to `Eigen::Dynamic`.
> So, would this compile? (I think it'd read better): 
> 
> ```C++
> Eigen::VectorBlock<VectorX> q_block;
> ```
> 
</details>
Done and it appears to work. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KLHtfykBayaTEuPbsjA:-84625242)*

**Comment by amcastro-tri** [comment]
:lgtm: 

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 201 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-KL1s_2w5RV8lS-S4rdT:-KLHuPAxwnM3b2HwqQmy:-866683504) ([raw file](https://github.com/robotlocomotion/drake/blob/7f9536b8c2ac23d00ab0159e4e27d40a7f0d5bc9/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L201)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done and it appears to work. PTAL.
</details>
Excellent!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KLHuV9wIwTFUXK7wyzz:980077423)*

**Comment by liangfok** [comment]
Great. Just waiting on CI now. Thanks!

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2637#-:-KLHv4Ogm6B02Z0Sqtto:2042301526)*

**Pull request merged**
