### PR TITLE
Consolidate Ubuntu prerequisite install scripts and cleanup associated Dockerfiles

### LINKED ISSUE #10123: Binary packages for Bionic contain prerequisite setup scripts for Xenial
This assumption is invalid:

https://github.com/RobotLocomotion/drake/blob/4c886e1d29c63c0bb84ec65f9f0c4fb7d163f02e/setup/BUILD.bazel#L17-L20

Relates #7882.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #10123. Loosely relates  #7882.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10141)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
I guess #10123 is high priority, so this should be labeled as such too.

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI please do not merge this PR until you've prepared ahead of time the matching Anzu PR that tracks the package list txt renames (`16.04` => `xenial`), so that we can merge the Anzu PR soon after this hits Drake master.

**Comment by jamiesnape** [comment]
> @EricCousineau-TRI please do not merge this PR until you've prepared ahead of time the matching Anzu PR that tracks the package list txt renames (16.04 => xenial), so that we can merge the Anzu PR soon after this hits Drake master.

Can you elaborate since this is completely hidden to the PR author (the read-only mirror of anzu no longer mirrors)?

**Comment by EricCousineau-TRI** [comment]
Sounds good; will prepare the Anzu PR.

**Comment by jamiesnape** [comment]
@EricCousineau-TRI Please remove the tag and merge this when you have the Anzu PR ready.

**Comment by jwnimmer-tri** [comment]
Yup, the "High" priority was elected by Eric, so I figure I'd let him balance when this gets merged vs dealing with TRI-internal fallout.

**Comment by EricCousineau-TRI** [comment]
Needed to do experiment work yesterday, and had to travel yesterday; will address Anzu bits now.

**Pull request merged**
