### PR TITLE
Fixes and polishes DrakeMockLcm documentation comments.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4906)

### CODE REVIEW

**Comment by liangfok** [comment]
Minor documentation-only change. +@sammy-tri for both levels of review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-:-KbLppVzTWObkEVS2G0F:b-4b0tzy)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/drake_mock_lcm.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-KbMBVLDbTsAbwk2mbAj:-KbMBVLDbTsAbwk2mbAk:bxaujob) ([raw file](https://github.com/robotlocomotion/drake/blob/7d0dfdaf2e6d1d1229fb213e62b7ad2392371d80/drake/lcm/drake_mock_lcm.h#L25)):*
> ```objc
> 
>   /**
>    * A constructor that creates a DrakeMockLcm with loopback is disabled, i.e.,
> ```

"with loopback is disabled" sounds a bit awkward

---

*[drake/lcm/drake_mock_lcm.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-KbMBo7qo_7NIDcC12zn:-KbMBo7rstx85ASIJuu4:b-izqjf7) ([raw file](https://github.com/robotlocomotion/drake/blob/7d0dfdaf2e6d1d1229fb213e62b7ad2392371d80/drake/lcm/drake_mock_lcm.h#L33)):*
> ```objc
>   /**
>    * Enables loopback behavior. With loopback enabled, a call to Publish() will
>    * result in subscriber callback functions being called.
> ```

so Subscribe() does nothing unless EnableLoopBack() is called?  I think that should perhaps be documented there if correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4906)*

**Comment by liangfok** [comment]
@sammy-tri: I addressed your comments. PTAL. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/drake_mock_lcm.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-KbMBVLDbTsAbwk2mbAj:-KbMLza0BHqdUIaqp-ZO:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/7d0dfdaf2e6d1d1229fb213e62b7ad2392371d80/drake/lcm/drake_mock_lcm.h#L25)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"with loopback is disabled" sounds a bit awkward
</blockquote></details>

Done. Thanks.

---

*[drake/lcm/drake_mock_lcm.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-KbMBo7qo_7NIDcC12zn:-KbMMHX_y3Zz3GmsevLV:b-7oqfsn) ([raw file](https://github.com/robotlocomotion/drake/blob/7d0dfdaf2e6d1d1229fb213e62b7ad2392371d80/drake/lcm/drake_mock_lcm.h#L33)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

so Subscribe() does nothing unless EnableLoopBack() is called?  I think that should perhaps be documented there if correct.
</blockquote></details>

I clarified the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-:-KbMMZrjgDBuHcuhvxlC:b-khza9j)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-:-KbMOgC_jU9aiBGXmmWs:bnfp4nl)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4906#-:-KbMOqRy1KvHwqPGBk_d:b-goi7bm)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please.

**Pull request merged**
