### PR TITLE
Polished PidControlledSystem In Preparation for Generalizing It

### PR DESCRIPTION
**Pull request by liangfok**
I modified it to use more standard terminology and fixed / added documentation comments. This is in preparation for future PRs that further generalize and improve PidControlledSystem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3903)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sammy-tri for feature review please.
+@david-german-tri for platform review please.

Many thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3903#-:-KUxYltAh6Ya8z4KxXNd:b-fzfkix)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3903#-:-KUxbfcFRFojEaaVedMF:bnfp4nl)*

**Comment by liangfok** [comment]
@sammy-tri: I added member initialization to the pointer member variables in `PidControlledSystem`. PTAL. Thanks.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3903#-:-KUyuMSxekjc3tS8G5f3:b5019ug)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3903)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/6127/ and is thus ready for platform review @david-german-tri.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3903#-:-KV0b60dDLG4YzAiv-WM:b-gh5e54)*

**Comment by david-german-tri** [comment]
:lgtm: nice!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3903#-:-KV5TH1JWWHD_kPjN9xv:b-7yytuz)*

**Pull request merged**
