### PR TITLE
Extracted URDF parser from RigidBodyTree

### PR DESCRIPTION
**Pull request by liangfok**
This contributes towards https://github.com/RobotLocomotion/drake/issues/2676. It contains no functional changes; it is just a refactor. The next step is to further decouple the `RigidBodyTree` from the URDF parser by making them only exchange information using a `Model` container object.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2707)

### CODE REVIEW

**Comment by sherm1** [comment]
BTW, I like the use of "Model" here to mean a logical grouping of components (esp. since that is the widely-used sdf/gazebo terminology), but we also need to rename the collision library abstraction that is currently called a "Model" in Drake. @amcastro-tri, is that on your contact rehab list?

**Comment by liangfok** [comment]
I see the following bullet in @amcastro-tri's TODO list (https://github.com/RobotLocomotion/drake/issues/2709):

> The collision dispatcher is called "Model", a word having other meanings in Drake. Something like CollisionWorld would be more appropriate.

**Comment by amcastro-tri** [comment]
I'd be even more specific. Maybe "RobotModel"?. I feel like the single word "Model" will get very easily overloaded.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLXE8TqKYSfbG28BdYY:1814067279)*

**Comment by liangfok** [comment]
"RobotModel" may be too specific since stuff in URDF / SDF may include elements in the world like a table, tree, mail box, etc.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLXEkznTxPD3vYxOG_W:1373619756)*

**Comment by sherm1** [comment]
I think Model is OK if we use world+models the same way Gazebo does in sdf, and then don't use plain "Model" anywhere else in Drake.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLXPB2nlhtQmnEZMl8g:787540281)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2425/ and is thus ready for review.

+@amcastro-tri for feature review.
+@ggould-tri for platform review.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLYAC8pBqEHu6PkQmjU:-250919030)*

**Comment by liangfok** [comment]
Even though this PR passed pre-merge CI, it appears to fail post-merge CI:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-32-experimental-matlab/16/

Investigating...

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLZPEXmAv8I6CyMF97r:-1126186133)*

**Comment by ggould-tri** [comment]
This seems mostly good to me.  I have a couple of minor consistency nits around namespacing, and a more serious concern about the types in `urdf_parser`.  But on the whole this is a big improvement in the factoring of Drake, and I'm happy to see it.

---

Reviewed 2 of 12 files at r1, 7 of 11 files at r2, 1 of 1 files at r3, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 1105 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-KLaWlpKCu9YFY972M77:-KLaWlpKCu9YFY972M78:-316258016) ([raw file](https://github.com/robotlocomotion/drake/blob/598506eeb6f2988f8565c7841d78eb4eb6bfb662/drake/systems/plants/parser_urdf.cc#L1105)):*
> ```cpp
>     const string& urdf_string,
>     PackageMap& package_map,
>     const std::string& root_dir,
> ```

FYI:  Explicit `std` inconsistent with bare `string` two lines earlier.  Better to either namespace-qualify all of the strings here or none.

---

*[drake/systems/plants/parser_urdf.h, line 1 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-KLaXrjWTSugvztiRWc5:-KLaXrjXZOUlpICIcNBP:83839968) ([raw file](https://github.com/robotlocomotion/drake/blob/598506eeb6f2988f8565c7841d78eb4eb6bfb662/drake/systems/plants/parser_urdf.h#L1)):*
> ```objc
> #pragma once
> ```

Meta on the whole file:

This file manages to use nearly every possible C++ argument passing form:  const-and non-const bare pointers, shared pointers, const- and non-const references, and value passing.

I am willing to accept the author's assurance that each of these are justified, but the proliferation makes me very suspicious.

In addition, every use of bare pointers and most uses of smart pointers should have documented null semantics: The reason to choose these types over references is that null is permitted, so it must be documented.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 890 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-KLa_0UD8EH4vrZyBduq:-KLa_0UD8EH4vrZyBdur:2047087639) ([raw file](https://github.com/robotlocomotion/drake/blob/598506eeb6f2988f8565c7841d78eb4eb6bfb662/drake/systems/plants/RigidBodySystem.cpp#L890)):*
> ```cpp
>     const DrakeJoint::FloatingBaseType floating_base_type) {
>   // first add the urdf to the rigid body tree
>   ::drake::parsers::urdf::addRobotFromURDFString(urdf_string, root_dir,
> ```

FYI --
We seem to be explicitly qualifying drake as `::drake` here but not elsewhere in the file (eg, fifteen lines after this point).  It would be better to be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLa_liGZZ22fD6OIzFi:529582478)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

Unfortunately, post-merge linux-gcc-ninja-matlab also fails:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-ninja-experimental-matlab/6/

Investigating...

---

Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 1105 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-KLaWlpKCu9YFY972M77:-KLaq0m57czTnRO8IRwx:-1839224674) ([raw file](https://github.com/robotlocomotion/drake/blob/598506eeb6f2988f8565c7841d78eb4eb6bfb662/drake/systems/plants/parser_urdf.cc#L1105)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI:  Explicit `std` inconsistent with bare `string` two lines earlier.  Better to either namespace-qualify all of the strings here or none.
</details>
Done. I went ahead and refactored every instance of `std::string` to be `string` in this PR.

---

*[drake/systems/plants/parser_urdf.h, line 1 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-KLaXrjWTSugvztiRWc5:-KLaqLfcpFrM81qLvyGe:-1747984449) ([raw file](https://github.com/robotlocomotion/drake/blob/598506eeb6f2988f8565c7841d78eb4eb6bfb662/drake/systems/plants/parser_urdf.h#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Meta on the whole file:
> 
> This file manages to use nearly every possible C++ argument passing form:  const-and non-const bare pointers, shared pointers, const- and non-const references, and value passing.
> 
> I am willing to accept the author's assurance that each of these are justified, but the proliferation makes me very suspicious.
> 
> In addition, every use of bare pointers and most uses of smart pointers should have documented null semantics: The reason to choose these types over references is that null is permitted, so it must be documented.
</details>
I believe most of the awkward C++ argument passing forms are part of legacy code and is thus considered technical debt. This is because pretty much everything within the newly introduced `::drake::parsers::urdu::[anonymous]` namespace is a straight copy/paste from the original `RigidBodyTreeURDF.cpp`.

I went through the methods in namespace `drake::parsers::urdf` and documented the null semantics of the raw pointers. All of these methods will soon be replaced anyway; I added a TODO for that.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 890 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-KLa_0UD8EH4vrZyBduq:-KLb1rKKdtx5L42MVqCg:1852294035) ([raw file](https://github.com/robotlocomotion/drake/blob/598506eeb6f2988f8565c7841d78eb4eb6bfb662/drake/systems/plants/RigidBodySystem.cpp#L890)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI --
> We seem to be explicitly qualifying drake as `::drake` here but not elsewhere in the file (eg, fifteen lines after this point).  It would be better to be consistent.
</details>
Done. I removed the initial `::`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLao873X8W7BVh3I3y7:-1166600229)*

**Comment by ggould-tri** [comment]
:lgtm: (pending whatever is bothering CI of course)

---

Reviewed 1 of 12 files at r1, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLbYo8WXmPdlEBSE2_A:412801529)*

**Comment by liangfok** [comment]
I started another post-merge test here to see if the problem continues to exist:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-ninja-experimental-matlab/7/

**Comment by liangfok** [comment]
Numerous post-merge unit tests are still failing. The biggest and most common problem appears to be a segmentation fault when running certain MATLAB-based unit tests:

https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=45942

**Comment by liangfok** [comment]
The list below contains the unit tests that failed in the above-mentioned CI build sorted by whether they are available on my local machine (using `cmake` flag `-DLONG_RUNNING_TESTS=ON`):

**Available on my local machine:**
* examples/Atlas/runAtlasHandControl - _unable to reproduce failure_
* examples/Strandbeest/runPassiveDownhill - _unable to reproduce failure_
* examples/Valkyrie/runValkyrieBalancing - _unable to reproduce failure_
* examples/Valkyrie/runValkyrieBalancingPerturb - _unable to reproduce failure_
* solvers/test/testMultipleTaskSpaceRRTStar - Can produce an error; not sure if it's the same error:
  *  Error using setenv. Argument must contain a string.
* solvers/test/testTaskSpaceRRT - Can produce an error; not sure if it's the same error:
  *  Error using setenv. Argument must contain a string.
* util/test/testGeometryGradientsComparison - _unable to reproduce failure_

**Not available on my local machine:**
* examples/Atlas/runAtlasBalancing
* examples/Atlas/runAtlasBalancingPerturb
* examples/Atlas/runAtlasBalancingWithContactSensor
* examples/Atlas/runAtlasManip

Since I'm unable to reproduce the vast majority of the unit test failures and those that do fail appear to be due to an unset environment variable, I'm going to declare that the post-merge unit tests failures are false positives and that this PR is ready for feature review.

---

Review status: 3 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707#-:-KLnY9M7rodv1sBy_t5X:-1435101379)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
Reviewed 1 of 12 files at r1, 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2707)*

**Comment by mwoehlke-kitware** [comment]
This appears to have broken CI, possibly everywhere... I wonder how it ever passed pre-merge tests?

The file `rigid_body_tree_urdf.h` was removed but is still mentioned in `drake/systems/plants/CMakeLists.txt`.

**Comment by jwnimmer-tri** [comment]
Here's why this failure didn't show up in pre-merge testing:
- The last pre-merge test was 19 hours ago.
- The #2700 fix was merged 1 hour later, 18 hours ago.
- There are two `drake_install_headers` stanzas in `plants/CMakeLists.txt`, so git did not detect it as a possible merge conflict.

We should fix `plants/CMakeLists.txt` to only have one stanza.  @liangfok Can you take that on?

**Comment by mwoehlke-kitware** [comment]
> There are two `drake_install_headers` stanzas

Oy, I missed that :blush:. Good catch; thanks for following up!

**Comment by jhoare** [comment]
I can fix this, PR coming soon.

**Comment by liangfok** [comment]
@jwnimmer-tri: Thanks for the post merge analysis! @jhoare and @mwoehlke-kitware: Thanks for the PRs fixing the problems caused by this PR.

**Pull request merged**
