### PR TITLE
Switch to SNOPT 7.6.1 2018-01-20 release

### LINKED ISSUE #1647: Test new version of SNOPT
The SNOPT version we are using now is 7.2. The newest version on http://www.sbsi-sol-optimize.com/asp/sol_product_snopt.htm is SNOPT 7.5. The interface is changed slightly between the two versions. In the newer version, it requires to pass the multiplier (xmul,Fmul,xstate,Fstate) as the input to the snopt call, in the MATLAB interface. But the C interface look the same to me. @javieralonso get the C++ interface of SNOPT 7.5 working on his machine.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #1647.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8263)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all review per schedule, please.

**Comment by jwnimmer-tri** [comment]
\CC @jamiesnape FYI

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/bazel.rst, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8263#-L6vhpq83izFUHUumC7M:-L6vhpq83izFUHUumC7N:byidfog) ([raw file](https://github.com/robotlocomotion/drake/blob/8efe7389e00407a5c115bd31592beb126a51ca43/doc/bazel.rst#L201)):*
> ```reStructuredText
> 
> 1. Download the SNOPT sources from the distributor in ``.tar.gz`` format (e.g.,
>    named ``snopt7.6.tar.gz``).
> ```

BTW The only download option I had was a ZIP named `snopt7.zip`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8263)*

**Comment by jwnimmer-tri** [comment]
Ullgralugh.  Using the newer SNOPT breaks two whole-robot integration tests.  I guess I will investigate that first.

**Comment by EricCousineau-TRI** [comment]
Should we label this as `do not review` until you've confirmed investigated the breakdown?

If not, would you like me to review what's already here?

**Comment by jwnimmer-tri** [comment]
You meat me to it, I was just removing you.  -@EricCousineau-TRI until I have feature review complete.

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.
+@EricCousineau-TRI for platform review per schedule, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8263#-:-L6xHhKWdtcx7P9trNxA:bnfp4nl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8263#-:-L6xKSeyRu_Gdf3h8iXS:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
Some pick-and-place test is failing on macOS, along with the known XML complaints that have since been fixed.  I'm going to wait for macOS master to go blue again and then retest.

**Comment by jwnimmer-tri** [comment]
The macOS builds are working on master again, so let's see how this PR does now:
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by hongkai-dai** [comment]
Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8263)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
All build passed.

**Pull request merged**
