### PR TITLE
Update BUILD for common to track recent PRs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4223)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri feature +@david-german-tri platform, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4223#-:-KXC85AacEsv5631UQkZ:bwlydpb)*

**Comment by soonho-tri** [comment]
*[drake/common/cond.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4223#-KXCD6UOpDIRJkuGIbQM:-KXCD6UOpDIRJkuGIbQN:b-gfpvtw) ([raw file](https://github.com/robotlocomotion/drake/blob/e7407d5fc4074c705753d320247846e121f3d198/drake/common/cond.h#L6)):*
> ```objc
> #include <type_traits>
> 
> #include "drake/common/double_overloads.h"
> ```

@jwnimmer-tri , you're right. We don't need this line (all CI builds passed).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4223)*

**Comment by soonho-tri** [comment]
Stupid question: where can I get the instructions for a bazel build?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4223#-:-KXCE2XM2V403rV36WLM:b-v0id2h)*

**Comment by jwnimmer-tri** [comment]
> Stupid question: where can I get the instructions for a bazel build?

We are working on getting a (beta) write-up in-tree.  For now, http://bazel.build for installation, then just `bazel test //...` in `drake-distro` and just Watch The Magic Happen.

(FTR, I have the Bazel 0.3.1 deb installed on my Xenial workstation.)

**Comment by soonho-tri** [comment]
I'm sure that the problem that I'm experiencing on OSX is not coming from this commit. Let me give :lgtm: to this. I'll try to fix the OSX-related issue and (possibly) make another PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4223#-:-KXCGQhuL7FJnOs0kbHq:bc9x6kj)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4223)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4223#-:-KXCYa6jOAGMI1FLQ8_V:bnfp4nl)*

**Pull request merged**
