### PR TITLE
Update recommended bazel version to 1.1

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12124)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Given that 1.0.0 is out, should the title here be reworded? (to remove the RC portion?)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
Both 1.0.1 and 1.1.0 were just released.

**Comment by EricCousineau-TRI** [comment]
That's, uh, a really quick cadence?

**Comment by jamiesnape** [comment]
They were a month late with 1.0.

**Comment by jwnimmer-tri** [comment]
FYI I just upgraded Anzu to 1.1.0, and it's working fine for us.  I have no objection to Drake going to either 1.0.1 or 1.1.0.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-python2-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Pull request merged**
