### PR TITLE
Change drpy2rotmat to new RollPitchYaw methods -- create ordinary and partial derivative of rotation matrix with respect to roll pitch yaw.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@seancurtis-tri 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778#-:-LC5AbR98iAyhTH78xtI:b-5jrdcp)*

**Comment by SeanCurtis-TRI** [comment]
I'm going to wait until feature review is done.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778#-:-LC6EZbD1uuyNM7oUSQ9:b-65fguo)*

**Comment by hongkai-dai** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[examples/quadrotor/quadrotor_plant.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tkCE4Y9fwBW95q0w:-LC6tkCFB9-maXjum3Hx:b-d93gbx) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/examples/quadrotor/quadrotor_plant.cc#L72)):*
> ```cpp
> 
>   // Extract orientation and angular velocities.
>   const drake::math::RollPitchYaw<T> rpy(state.segment(3, 3));
> ```

BTW, it is better to use `state.segment<3>(3)` to avoid creating a dynamic-sized vector. Same for `rpyDt` below.

---

*[examples/quadrotor/quadrotor_plant.cc, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6u2rH25FZ-EXJKLdf:-LC6u2rH25FZ-EXJKLdg:b-bxim0j) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/examples/quadrotor/quadrotor_plant.cc#L90)):*
> ```cpp
>   const Vector3<T> xyzDDt = (Fg + R * F) / m_;
> 
>   Vector3<T> pqr;
> ```

Out of curiosity, what is `pqr`?

---

*[examples/quadrotor/quadrotor_plant.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6uKYH5edRgypiUlyi:-LC6uKYH5edRgypiUlyj:b-vlcmq5) ([raw file](https://github.com/robotlocomotion/drake/blob/b8b91ffd3cf251c49aeffbe479bed3650df2db0c/examples/quadrotor/quadrotor_plant.cc#L113)):*
> ```cpp
>   // Recomposing the derivatives vector.
>   VectorX<T> xdot(12);
>   xdot << state.tail(6), xyz_ddot, rpy_ddot;
> ```

state.tail<6>()

---

*[math/roll_pitch_yaw.h, line 317 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6t8q86myKia7Jzj2t:-LC6t8q86myKia7Jzj2u:bs4lwja) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L317)):*
> ```objc
>                    0,                c1 * c0,               -c1 * s0;
> 
>     *R_p << -c2 * s1,             c2_c1 * s0,             c2_c1 * c0,
> ```

`c2 * s1` can be replaced by `c2_s1`

---

*[math/roll_pitch_yaw.h, line 318 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tF0a6v0b0m1NXfCe:-LC6tF0a6v0b0m1NXfCf:b-4xjtoq) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L318)):*
> ```objc
> 
>     *R_p << -c2 * s1,             c2_c1 * s0,             c2_c1 * c0,
>             -s2 * s1,             s2_c1 * s0,             s2_c1 * c0,
> ```

`s2 * s1` can be replaced by `s2_s1`

---

*[math/roll_pitch_yaw.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tLkW06RguTdHpu7Z:-LC6tLkW06RguTdHpu7_:b-7xcutm) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L321)):*
> ```objc
>                  -c1,               -s1 * s0,               -s1 * c0;
> 
>     *R_y << -s2 * c1,  -s2_s1 * s0 - c2 * c0,  -s2_s1 * c0 + c2 * s0,
> ```

`s2 * c1` can be replaced by `s2_c1`

---

*[math/roll_pitch_yaw.h, line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tP430XFT04upDio2:-LC6tP430XFT04upDio3:b-27dkaw) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L322)):*
> ```objc
> 
>     *R_y << -s2 * c1,  -s2_s1 * s0 - c2 * c0,  -s2_s1 * c0 + c2 * s0,
>              c2 * c1,   c2_s1 * s0 - s2 * c0,   c2_s1 * c0 + s2 * s0,
> ```

`c2 * c1` can be replaced by `c2_c1`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/quadrotor/quadrotor_plant.cc, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCAYsXZCfTQ7_tNRGXJ:-LCAYsXZCfTQ7_tNRGXK:b8bo2jx) ([raw file](https://github.com/robotlocomotion/drake/blob/8f01f3ea516f3cbf6e6df062b824e78d72039f80/examples/quadrotor/quadrotor_plant.cc#L72)):*
> ```cpp
> 
>   // Extract orientation and angular velocities.
>   Vector3<T> rpy = state.segment(3, 3);
> ```

state.segment(3, 3) -> state.segment<3>(3);
state.segment(9, 3) -> state.segment<3>(9);

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[examples/quadrotor/quadrotor_plant.cc, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCAk3_o42JBRyr-H4rd:-LCAk3_o42JBRyr-H4re:b-n2n3wx) ([raw file](https://github.com/robotlocomotion/drake/blob/495196e9b72c20478d3082fd70872167e9cf8844/examples/quadrotor/quadrotor_plant.cc#L75)):*
> ```cpp
>   const Vector3<T> rpyDt = state.segment(9, 3);
> 
>   // Convert orientation to the R_NB rotation matrix (N is world and B is body).
> ```

BTW "N" is world? Why  not "W"? It seems if you're going to go with"N", then you should double down with "inertial frame". But since we typically discuss the "world" frame, we should go with the more common symbol in drake: "W".

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by jwnimmer-tri** [comment]
Moving code between h and cc file should be in its own PR, with no other functional or refactoring changes intertwined.

**Comment by mitiguy** [comment]
Reviewed 2 of 5 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/quadrotor/quadrotor_plant.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tkCE4Y9fwBW95q0w:-LCAQzC61JA348g1ejVq:b-c8dgsl) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/examples/quadrotor/quadrotor_plant.cc#L72)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, it is better to use `state.segment<3>(3)` to avoid creating a dynamic-sized vector. Same for `rpyDt` below.
</blockquote></details>

 Seems to cause compiler issues if I change this.

---

*[examples/quadrotor/quadrotor_plant.cc, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6u2rH25FZ-EXJKLdf:-LCAGFay1sHkZG-kaUMo:b-kuwbw3) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/examples/quadrotor/quadrotor_plant.cc#L90)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Out of curiosity, what is `pqr`?
</blockquote></details>

It is used twice.   The code has been changed to try to make this clearer.

This system seems to contain a rigid body B in the world N.
The first time it is used, it seems to be
w_BN_N  (B's angular velocity in N, expressed in N).

The second time it is used, it seems to be
w_BN_N  (B's angular velocity in N, expressed in N).

---

*[examples/quadrotor/quadrotor_plant.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6uKYH5edRgypiUlyi:-LCAeAPU8zZRfDyfR6hF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b8b91ffd3cf251c49aeffbe479bed3650df2db0c/examples/quadrotor/quadrotor_plant.cc#L113)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

state.tail<6>()
</blockquote></details>

Done.

---

*[examples/quadrotor/quadrotor_plant.cc, line 72 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCAYsXZCfTQ7_tNRGXJ:-LCAe60Y3mDzk8zO7PBT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f01f3ea516f3cbf6e6df062b824e78d72039f80/examples/quadrotor/quadrotor_plant.cc#L72)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

state.segment(3, 3) -> state.segment<3>(3);
state.segment(9, 3) -> state.segment<3>(9);
</blockquote></details>

Done.

---

*[examples/quadrotor/quadrotor_plant.cc, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCAk3_o42JBRyr-H4rd:-LCFifM3Cqi7-tDACtAx:bfdwhqy) ([raw file](https://github.com/robotlocomotion/drake/blob/495196e9b72c20478d3082fd70872167e9cf8844/examples/quadrotor/quadrotor_plant.cc#L75)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "N" is world? Why  not "W"? It seems if you're going to go with"N", then you should double down with "inertial frame". But since we typically discuss the "world" frame, we should go with the more common symbol in drake: "W".
</blockquote></details>

BTW Done. Changed comments.

---

*[math/roll_pitch_yaw.h, line 317 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6t8q86myKia7Jzj2t:-LCAQ0cs5uvqpbACsZch:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L317)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`c2 * s1` can be replaced by `c2_s1`
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 318 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tF0a6v0b0m1NXfCe:-LCAQ1lt69bYo0Ng_YOi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L318)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`s2 * s1` can be replaced by `s2_s1`
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tLkW06RguTdHpu7Z:-LCAQ2TbBTg12T7dWpB6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L321)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`s2 * c1` can be replaced by `s2_c1`
</blockquote></details>

Done.

---

*[math/roll_pitch_yaw.h, line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6tP430XFT04upDio2:-LCAQ32e7DwVuiLKSvhD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/math/roll_pitch_yaw.h#L322)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`c2 * c1` can be replaced by `c2_c1`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 5 files at r3, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/quadrotor/quadrotor_plant.h, line 86 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCGAJdXDIRM8MLu9snK:-LCGAJdXDIRM8MLu9snL:b-w278on) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd5178a76beffbb66ca18684600ab02057d6e73/examples/quadrotor/quadrotor_plant.h#L86)):*
> ```objc
> }  // namespace quadrotor
> }  // namespace examples
> ```

BTW, maybe add some documentation here, explaining why we need to define this trait for `QuadrotorPlant`? You could say "Prevent transmogrification  to and from symbolic scalar types. This NonSymbolicTraits is explained in drake/systems/framework/system_scalar_converter.h"

---

*[examples/quadrotor/quadrotor_plant.cc, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC6u2rH25FZ-EXJKLdf:-LCGBGPeDUy3P9ZskJiY:b-wsvasg) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc231d54eece16dd6424b174b4f34545ad188ae/examples/quadrotor/quadrotor_plant.cc#L90)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

It is used twice.   The code has been changed to try to make this clearer.

This system seems to contain a rigid body B in the world N.
The first time it is used, it seems to be
w_BN_N  (B's angular velocity in N, expressed in N).

The second time it is used, it seems to be
w_BN_N  (B's angular velocity in N, expressed in N).
</blockquote></details>

Thanks for the explanation!

---

*[examples/quadrotor/quadrotor_plant.cc, line 112 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCGBdr033O1RdiPiKei:-LCGBdr033O1RdiPiKej:bo5yliv) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd5178a76beffbb66ca18684600ab02057d6e73/examples/quadrotor/quadrotor_plant.cc#L112)):*
> ```cpp
>   angularvel2rpydotMatrix(rpy.vector(), Phi, &dPhi, ddPhi);
> 
>   VectorX<T> dPhi_x_rpyDt_vec = dPhi * rpyDt;
> ```

`const VectorX<T>`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778#-:-LCV3kLdBKO7Nfjjw1vb:b-s794vx)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with a couple of small items.

---

Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 2 of 5 files at r3, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/quadrotor/quadrotor_plant.cc, line 90 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCV6uzJ-WvqnjXlHqBN:-LCV6uzJ-WvqnjXlHqBO:b-i0olx1) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd5178a76beffbb66ca18684600ab02057d6e73/examples/quadrotor/quadrotor_plant.cc#L90)):*
> ```cpp
>   // Calculate the net force on body B, expressed in N.  Next,
>   // calculate the resultant linear acceleration due to the forces.
>   const Vector3<T> net_force = Fg + R_NB * F;
> ```

BTW erratic naming. There's no monogram notation here or on the forces computed above. But this one jumps out particularly, because it isn't even a symbol.

---

*[math/roll_pitch_yaw.h, line 303 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCV8t6l90iv2tqWCvOV:-LCV8t6l90iv2tqWCvOW:b-i6ow2y) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd5178a76beffbb66ca18684600ab02057d6e73/math/roll_pitch_yaw.h#L303)):*
> ```objc
>                                        Matrix3<T>* R_y) const {
>     DRAKE_ASSERT(R_r != nullptr && R_r != nullptr && R_r != nullptr);
>     const T &r = get_roll_angle();
> ```

BTW Placement of &.

---

*[math/test/rotation_matrix_test.cc, line 422 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCV9Jfk691p7RzgTuis:-LCV9Jfk691p7RzgTuit:b-abnlcy) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd5178a76beffbb66ca18684600ab02057d6e73/math/test/rotation_matrix_test.cc#L422)):*
> ```cpp
>          -s1*c0*pDt - s0*c1*rDt;
> 
>   const Matrix3d R_difference = RDt - MDt;
> ```

BTW Use `CompareMatrices`instead. That way , in the case of failure, the matrices are output with the erroneous cells highlighted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778#-:-LCV9Ud-7XgYH1wL7ykr:beg5c4a)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778#-:-LCV9tqr-rfH3hMNHpua:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/quadrotor/quadrotor_plant.h, line 87 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCVZH-P3VBglozWCeR5:-LCVZH-P3VBglozWCeR6:bur9qt8) ([raw file](https://github.com/robotlocomotion/drake/blob/0bc50688be56ff9bb7804e2574d80db5d09ebdff/examples/quadrotor/quadrotor_plant.h#L87)):*
BTW Bad news. This doesn't work. We can't use the word "transmogrification" in the code. I recommend:

> Prevent scalar conversion to symbolic scalar types. The QuadrotorPlant makes use of classes that are not compatible with the symbolic scalar.

---

*[examples/quadrotor/quadrotor_plant.cc, line 79 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCVZXsE9fIo3wbEk5gq:-LCVZXsE9fIo3wbEk5gr:bgw3vog) ([raw file](https://github.com/robotlocomotion/drake/blob/0bc50688be56ff9bb7804e2574d80db5d09ebdff/examples/quadrotor/quadrotor_plant.cc#L79)):*
> ```cpp
>   const drake::math::RotationMatrix<T> R_NB(rpy);
> 
>   // Compute Bz measure of the net aerodynamic/rotor (input) force on B.
> ```

BTW This comment is incomplete. It addresses the first line, but not the second line. I tried rewording it but wasn't entirely comfortable with the nuance of what you'd written. I'd try something like:

// Compute the measure of the force from each rotor (wholly in the Bz direction) based on control signal and the net rotor force, expressed in B.

It's not as complete as yours, but it, at least, covers both lines (and, to a certain extent, their relationship). I'll let you massage that into something more complete.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by mitiguy** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/quadrotor/quadrotor_plant.cc, line 112 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LCGBdr033O1RdiPiKei:-LCV3eYZ0goOhLk4l60r:b-tje023) ([raw file](https://github.com/robotlocomotion/drake/blob/3fd5178a76beffbb66ca18684600ab02057d6e73/examples/quadrotor/quadrotor_plant.cc#L112)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const VectorX<T>`
</blockquote></details>

Done.  Hongkai - thank you for your help.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[examples/quadrotor/quadrotor_plant.cc, line 91 at r6](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC_h4dE5N5sKHl7J69R:-LC_h4dE5N5sKHl7J69S:b-5fqdh4) ([raw file](https://github.com/robotlocomotion/drake/blob/1b3a7b1ec59262baf10ee50db6112b84a97a67a6/examples/quadrotor/quadrotor_plant.cc#L91)):*
> ```cpp
>   const T Mz = uM_Bz(0) - uM_Bz(1) + uM_Bz(2) - uM_Bz(3);
> 
>   // Calculate the net moment on B, expressed in B, which is the sum of moments
> ```

BTW This comment got away from you; there is no moment attributable to gravity. `M` is expressed only in terms of the aero forces.

Also "calculate" is probably not appropriate for this one line -- the quantities have already been calculated, this just combines them.

---

*[examples/quadrotor/quadrotor_plant.cc, line 119 at r6](https://reviewable.io/reviews/robotlocomotion/drake/8778#-LC_hjnR0aEvxEoJ7B7k:-LC_hjnR0aEvxEoJ7B7l:b-ik0yb8) ([raw file](https://github.com/robotlocomotion/drake/blob/1b3a7b1ec59262baf10ee50db6112b84a97a67a6/examples/quadrotor/quadrotor_plant.cc#L119)):*
> ```cpp
>   const Vector3<T> w_BN_B = R_NB.inverse() * w_BN_N;
> 
>   // To calculate B's angular acceleration in N, expressed in B due to the net
> ```

BTW "...expressed in B due to the net..." is missing a comma. As is, it implies that it's expressed in B due to the net moment on B. Should be "...expressed in B, due to the next..."

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8778)*

**Pull request merged**
