### PR TITLE
Move PackageMap from //multibody/parsing into //common

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The old path is deprecated.

(Note: This version does not maintain history of package_map.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgVmcHs0hKh3RIrTjQy:-NgVmcHs0hKh3RIrTjQz:bnwm5ti) (no related file):*
@jwnimmer-tri I have several questions. I'd like you to take a look at this.

1. I haven't maintained history. Do we want to jump through the hoops so that the history is shared between old and new files?
2. Is the deprecation on the library inappropriate? I get a warning including it into the package. Of the two, inclusion of the package seems more important than the deprecation warning.
3. Should I provide a deprecation-like `#warning` in the old header?
4. I'm not sure where the bindings should go in pulling them out of multibody/parsing_py.cc.  Suggestions?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgVmcHs0hKh3RIrTjQy:-NgVn_H58MtO3hH6aG9k:biny00i) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@jwnimmer-tri I have several questions. I'd like you to take a look at this.

1. I haven't maintained history. Do we want to jump through the hoops so that the history is shared between old and new files?
2. Is the deprecation on the library inappropriate? I get a warning including it into the package. Of the two, inclusion of the package seems more important than the deprecation warning.
3. Should I provide a deprecation-like `#warning` in the old header?
4. I'm not sure where the bindings should go in pulling them out of multibody/parsing_py.cc.  Suggestions?
</blockquote></details>

(1) Yes, since it so very easy to do it.  Shall I push the patch?

(2) For core classes, my opinion is that we should add the new name first, and not deprecate _anything_ until 3+ months later.  That makes it a lot easier for people to deal with the renaming.  They can upgrade at will, and then at whatever point they can port to the new names.  They don't need to do both in lockstep.

(3) Not necessary when the typedef in the old header is already marked as deprecated.

(4) I'm not sure yet.  I'm not even sure the C++ code should live in `//common` directly.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgVmcHs0hKh3RIrTjQy:-NgZ45IQBRJfrLcjaS9K:bqv7z9p) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(1) Yes, since it so very easy to do it.  Shall I push the patch?

(2) For core classes, my opinion is that we should add the new name first, and not deprecate _anything_ until 3+ months later.  That makes it a lot easier for people to deal with the renaming.  They can upgrade at will, and then at whatever point they can port to the new names.  They don't need to do both in lockstep.

(3) Not necessary when the typedef in the old header is already marked as deprecated.

(4) I'm not sure yet.  I'm not even sure the C++ code should live in `//common` directly.
</blockquote></details>

(1) Remember the "stub" directory trick: https://github.com/RobotLocomotion/drake/pull/18697/files#diff-491646e0fbfda86a2a743bd5ba505ae59b33a5ad5a71abe7fc133e4551e13d8e

___

**Comment by SeanCurtis-TRI** [comment]
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

(1) Have you figured out a new incantation? My recollection of moving the *contents* of a file (with history) while keeping the old file in place required several coordinated commits that had to be put into master without merging. Is there a new technique? (Ha! You hit publish right before I did.)
(2) Deferring the deprecation works for the lazy part of my soul. :)
</blockquote></details>

I'd forgotten the stub. I'll revisit it. Thanks for the reminder.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgVmcHs0hKh3RIrTjQy:-NgZ4zrW1mzvznoe2UbC:b-qutdec) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd forgotten the stub. I'll revisit it. Thanks for the reminder.
</blockquote></details>

(The other way to keep history is to use two commits, adding back the old filename in the second commit.)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgZ3GkJEa-OzIgE6aOm:-NgZ5KL8DOXINRzDEB0U:b35am7i) (no related file):*
> It seems to me the best we can do is append an additional defaulted parameter and if the user applies a config file that needed package resolution, they'll find out when the config function attempts to do so and the defaulted `package_map` complains it doesn't know about the package.

That sounds like a fine answer to get us going.  It might even work OK indefinitely.

The other design alternative you didn't mention is to pivot so that _all_ apply functions always have access to the package map; to do that, it means creating and storing the PackageMap (and making it accessible) as part of AddMultibodyPlantSceneGraph, so either inside MbP or SG or as part of the Diagram.  It's probable that this would improve the situation for even more use cases than just the ApplyConfig problem.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgVmcHs0hKh3RIrTjQy:-NgyT-w54Vm2IiKiRjV5:b-pbdqz3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If the bindings were already in the modern style where we had `DefineParsingPackageMap(py::module)` as a helper function in a dedicated file, then it would be easy to preserve history.  However, since its still in the legacy style, the only way to preserve history is with the tricky multi-merge commit shenanigans, and for bindings code I do not think that's worthwhile.
</blockquote></details>

Agreed.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgZ3GkJEa-OzIgE6aOm:-NgyT4ZkCTSnWGQM9A8z:b-di3alj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure a review thread on this PR is a useful place to work on this design.  How about one or both of us work up a prototype bid, in code?  That's really the only way to surface the relevant concerns.
</blockquote></details>

Sounds fine. I just wanted to see if you had a clear vision already.

I guess I'm not sure what problem is truly being solved. Are we trying to maximize backwards compatibility? Convenience? Correctness (whatever that may entail)?

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgyI1mpDJZe_5XSQLfR:-NgyT9pA6SzCiIVI2aCE:b-1jf83q) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the current version, I could use some guidance on how to make sure that the symbol `pydrake.common.parsing.PackageMap` is aliased as `pydrake.multibody.parsing.PackageMap`.  Thanks.
</blockquote></details>

@jwnimmer-tri Did you see this one?

___
___
*[`bindings/pydrake/common/parsing_py.cc` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgyPBnh8dONcTuvYsso:-NgyTQ3S7m2byQ3pTWQx:bwrv6y4) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1013ccb59f7d0e2a0990c7dc407a439f8623359/bindings/pydrake/common/parsing_py.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Since we're starting fresh anyway, I think this module should use the modern style (ala geometry, planning, etc) where all of the bindings are in helper functions (`DefineParsingPackageMap`) that the overall module calls as subroutines.  That will allow it to scale up as we move more classes into this module.
</blockquote></details>

Ok.

I toyed with whether I'd create a `planning` directory under `pydrake/binding/common`. That fully mirrors the pattern seen in `geometry` and `planning`. However, it doesn't seem the pydrake folders go deep. So, shall I just put a `parsing_py.cc` and `parsing_py_package_map.cc` in the common folder with everything else?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgZ3GkJEa-OzIgE6aOm:-NgyUpO74XZpr8oUnFXu:blkqiva) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Sounds fine. I just wanted to see if you had a clear vision already.

I guess I'm not sure what problem is truly being solved. Are we trying to maximize backwards compatibility? Convenience? Correctness (whatever that may entail)?
</blockquote></details>

Asking users to correctly plumb the `package_map` reference into every apply function is a boilerplatey and thus risks them missing some and ending up with bugs.  Conceptually it is a per-diagram singleton so if we can reflect that in the code then everyone's life will be easier.  New Apply functions that we introduce later will immediately have access to the map, without every single one needing to declare and document the same argument everywhere.  It's similar in spirit to `ApplyVisualizationConfig` not mandating the user to pass in their plant pointer.  In almost all cases, there should be only one and we should look it up instead of using an argument.  The same kind of strategy would also be an improvement for the handling of `LcmBuses`.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgyI1mpDJZe_5XSQLfR:-NgyV_-j6JBBhrqpsRE3:blstzq3) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@jwnimmer-tri Did you see this one?
</blockquote></details>

```patch
diff --git a/bindings/pydrake/multibody/BUILD.bazel b/bindings/pydrake/multibody/BUILD.bazel
index ddc9146628..f0a6990f33 100644
--- a/bindings/pydrake/multibody/BUILD.bazel
+++ b/bindings/pydrake/multibody/BUILD.bazel
@@ -167,6 +167,9 @@ drake_pybind_library(
         "//bindings/pydrake/common:parsing_py",
         "//bindings/pydrake/common:schema_py",
     ],
+    py_srcs = [
+        "_parsing_extra.py",
+    ],
 )
 
 drake_pybind_library(
diff --git a/bindings/pydrake/multibody/_parsing_extra.py b/bindings/pydrake/multibody/_parsing_extra.py
new file mode 100644
index 0000000000..ed2cec627e
--- /dev/null
+++ b/bindings/pydrake/multibody/_parsing_extra.py
@@ -0,0 +1,2 @@
+# For backwards compatibility.
+from pydrake.common.parsing import PackageMap
diff --git a/bindings/pydrake/multibody/parsing_py.cc b/bindings/pydrake/multibody/parsing_py.cc
index b1d94f8b3b..ac12c11187 100644
--- a/bindings/pydrake/multibody/parsing_py.cc
+++ b/bindings/pydrake/multibody/parsing_py.cc
@@ -212,6 +212,8 @@ PYBIND11_MODULE(parsing, m) {
       py::return_value_policy::reference,
       py::keep_alive<0, 1>(),  // `return` keeps `plant` alive.
       doc.parsing.GetScopedFrameByName.doc);
+
+  ExecuteExtraPythonCode(m);
 }
 
 }  // namespace pydrake
```

___
___
*[`bindings/pydrake/common/parsing_py.cc` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgyPBnh8dONcTuvYsso:-NgyXdToDu55nzdGfHzQ:bh9d6cs) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1013ccb59f7d0e2a0990c7dc407a439f8623359/bindings/pydrake/common/parsing_py.cc#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ok.

I toyed with whether I'd create a `planning` directory under `pydrake/binding/common`. That fully mirrors the pattern seen in `geometry` and `planning`. However, it doesn't seem the pydrake folders go deep. So, shall I just put a `parsing_py.cc` and `parsing_py_package_map.cc` in the common folder with everything else?
</blockquote></details>

Working

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgZ3GkJEa-OzIgE6aOm:-Ngyn7Lc5A-RvRe6-hwF:b-q9pm6c) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'll ask the obvious question: why not a singleton? Instead of one `PackageMap` per `Diagram`, we have one per process? The more I think about it, the more I like it.

Unless you have an strong reason against it, I'm game to knock out a prototype.
</blockquote></details>

Because different simulations in the same process might want to use different maps.  The user might be loading code from another library that uses Drake, and we must not bleed those two maps together.

Process-scoped singletons are very strongly defective in 99% of cases.  The valid uses of singletons are very rare, e.g. (1) memoization / interning, where the effect is invisible to the user other than perf speedup and (2) logging configuration.

___
___
*[`bindings/pydrake/common/parsing_py.cc` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgyPBnh8dONcTuvYsso:-NgynhjF6nhvoggtHeW9:brll9jd) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1013ccb59f7d0e2a0990c7dc407a439f8623359/bindings/pydrake/common/parsing_py.cc#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm pushing a version.
</blockquote></details>

The common package is a mess and I have a WIP refactor of the whole thing that will enable you to make progress.  The latest push is still wrong.

Thus, "Working".

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgZ3GkJEa-OzIgE6aOm:-NgyvJYUAVP2pt-7Lqgj:b-9qnmw6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Because different simulations in the same process might want to use different maps.  The user might be loading code from another library that uses Drake, and we must not bleed those two maps together.

Process-scoped singletons are very strongly defective in 99% of cases.  The valid uses of singletons are very rare, e.g. (1) memoization / interning, where the effect is invisible to the user other than perf speedup and (2) logging configuration.
</blockquote></details>

I had originally pondered that. I was hard-pressed to imagine a case where I needed the same package to resolve to two different paths in a single process. The possibility of collisions seemed to be the only danger in "merging maps".

You also raise the issue of transitivity and that seems a messier proposition. But, again, the only problem I can perceive comes down to duplicate package names. I get the sense that the ROS world is well aware of that danger and people would consider such a scenario to be defective. Is that overly naive?

The primary problem I have with bundling a package map with a specific entity is that there are code paths that require the package map that don't have access to that entity.

___
___
*[`bindings/pydrake/common/parsing_py.cc` line 12 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgyPBnh8dONcTuvYsso:-NgyuzpH5ThKQLXw3ZSF:b-6dt9fe) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1013ccb59f7d0e2a0990c7dc407a439f8623359/bindings/pydrake/common/parsing_py.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The common package is a mess and I have a WIP refactor of the whole thing that will enable you to make progress.  The latest push is still wrong.

Thus, "Working".
</blockquote></details>

Ah...

I have a proposal. I'm going to wrap up the VTK Environment map PR *without* package support (it'll strictly be file path) and submit it for review. I'll follow up with package support after we resolve all this. While we work out plumbing issues, there's no reason to tie people's hands.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20356)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20356#-NgZ3GkJEa-OzIgE6aOm:-NgywQooDhc19rdGD0-4:b-tcuso8) (no related file):*
> I get the sense that the ROS world is well aware of that danger and people would consider such a scenario to be defective.

A memoized const singleton for "a directory that matches the ROS_PACKAGE_PATH when the program started" might be a valid proposal.  Our PackageMap class though is a lot more generic and useful than ROS_PACKAGE_PATH, and cannot itself be a singleton.

> Is that overly naive?

Yes.

Consider a batch simulation runner process, that uses threads to run multiple simulations at the same time.  Maybe it's being used to bisect where a model file went wrong.  There might be multiple versions of the same package being loaded by different simulators, under a the same name.

Or maybe a user always names their models `package://my_models/...` but then in different simulations populate a different subset of models into there, where there is not one single directory on disk where they all live that would be suitable for a global variable.

___

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI my sudafed-addled brain cannot recall the bigger picture around this PR.  Could you remind me where we were thinking of using a `PackageMap` elsewhere than the Parser?  I seem to recall I thought it was a good idea, but I've lost the discussion.

**Comment by SeanCurtis-TRI** [comment]
I wish I could blame sudafed. I also have no specific recollection of the motivation. If I were to guess, I'd say it would be related to resolving package URIs in geometry, but I'll have to do a bit more exploring to feel more confident. I'll do that this morning to see if I can't come up with something more definitive.

**Comment by SeanCurtis-TRI** [comment]
Ok, looking at the context, I'm 99% convinced it was the ability to specify an environment map in a config file such that the environment map was part of a package. I think it ultimately comes down to [this comment](https://github.com/RobotLocomotion/drake/blob/master/geometry/render_vtk/render_engine_vtk_params.h#L37-L40).

**Comment by jwnimmer-tri** [comment]
Okay, that makes sense.  Let's shelve this PR until we return to that feature.  When we cycle back, we should develop and end-to-end WIP proving the idea, before we commit to the source code shuffling here.

**Pull request closed without merging**
