### PR TITLE
Adds a Jaco arm demo using inverse kinematics

### PR DESCRIPTION
**Pull request by rcory**
and inverse dynamics for executing a simple setpoint task. 
Also added minor comments to set pose demo.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6204)

### CODE REVIEW

**Comment by rcory** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-:-KlPSjMGvR-Un6y4pASj:bltox9h)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQTeBq40eONLDyD7cL:-KlQTeBq40eONLDyD7cM:b-qubj6h) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L3)):*
> ```cpp
> /// @file
> ///
> /// This demo sets up a position controlled and gravity compensated KUKA iiwa
> ```

`KUKA iiwa` -> `Kinova Jaco`

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQ_wGkSprkZstZofSM:-KlQ_wGkSprkZstZofSN:b-yu4hol) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L45)):*
> ```cpp
> 
> std::unique_ptr<PiecewisePolynomialTrajectory> MakePlan() {
>   std::string kUrdfPath = drake::GetDrakePath() + std::string(kRelUrdfPath);
> ```

`const std::string`?

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQbJg0_m3ri3sTtI1N:-KlQbJg1yFcVBlLl_yuC:bhzwl09) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L92)):*
> ```cpp
>   // below is a collection of offsets into the state vector referring to the
>   // positions of the joints to be constrained.
>   VectorXi joint_position_start_idx(1);
> ```

Use `Vector1<int>` instead of `VectorXi`? Prefer static-size object to the dynamic sized ones.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQeZSbAesWpGYBcIUH:-KlQeZSbAesWpGYBcIUI:b-yu4hol) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L157)):*
> ```cpp
>   DRAKE_DEMAND(FLAGS_simulation_sec > 0);
> 
>   std::string kUrdfPath = drake::GetDrakePath() + std::string(kRelUrdfPath);
> ```

`const std::string`?

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 199 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQh7W7xWeWdqVHnbJ_:-KlQh7W8UlSQJ6pMvflI:bvazu00) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L199)):*
> ```cpp
> 
>   // Connects the state port to the controller.
>   static const int kInstanceId =
> ```

Do not have to be `static const`. A `const int` is probably more clear.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQj6TTQBUzFs2D9Cw4:-KlQj6TTQBUzFs2D9Cw5:b-1b6rqz) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L206)):*
> ```cpp
> 
>   // Connects the controller torque output to plant.
>   const auto& torque_out_port =
> ```

Rename it to `torque_input_port`, as it is the input port of the plant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204)*

**Comment by rcory** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQTeBq40eONLDyD7cL:-KlQvouvIYh8M-QF8tgr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L3)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`KUKA iiwa` -> `Kinova Jaco`
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQ_wGkSprkZstZofSM:-KlQwQMX4cwraZ3qD0fk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L45)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const std::string`?
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQbJg0_m3ri3sTtI1N:-KlQxJ-NRjrUkUaNceNH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L92)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Use `Vector1<int>` instead of `VectorXi`? Prefer static-size object to the dynamic sized ones.
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQeZSbAesWpGYBcIUH:-KlQxQDTkEC3HccuxHSD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L157)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const std::string`?
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 199 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQh7W7xWeWdqVHnbJ_:-KlQxVgNrqAe8EZN0kDM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L199)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do not have to be `static const`. A `const int` is probably more clear.
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlQj6TTQBUzFs2D9Cw4:-KlQyKL7sopIkO_kHCnx:baagbxm) ([raw file](https://github.com/robotlocomotion/drake/blob/c34079400d2a39ccfe64c3c9019ded203cf8c581/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L206)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Rename it to `torque_input_port`, as it is the input port of the plant?
</blockquote></details>

Done. Also fixed the same problem in run_setpose_jaco_demo.cc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-:-KlROfNXCug4JfdRv5LY:b-t6qajt)*

**Comment by rcory** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/BUILD, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlTlnjkKEzxt9e5s6zT:-KlUZ3ZoTfKhOR6Fxiid:b-vt5him) ([raw file](https://github.com/robotlocomotion/drake/blob/7de82dbe1568191babfe556f6307c09aff31e1f5/drake/examples/kinova_jaco_arm/BUILD#L39)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Based on a quick search of other BUILD files, I think being at the end of the list is more idiomatic for the drake source tree.  (and two more of these below)
</blockquote></details>

Done. Upgraded the CLion with Bazel plugin to avoid non-idiomatic automatic ordering.

---

*[drake/examples/kinova_jaco_arm/BUILD, line 84 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlTnuFoVJt_KtEnKttF:-KlUc3HU2NfCzZ40ZUUA:b-ywc8nf) ([raw file](https://github.com/robotlocomotion/drake/blob/7de82dbe1568191babfe556f6307c09aff31e1f5/drake/examples/kinova_jaco_arm/BUILD#L84)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this need medium even with the 0.1sec simulation time?  
</blockquote></details>

Nope it doesn't. Removing this.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlTnV0YJfMOMJuUAORZ:-KlUchdkCs8nGumILkf4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7de82dbe1568191babfe556f6307c09aff31e1f5/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L10)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlToR_MA9HQM5MX-TjV:-KlUfMVWPkc645vPxyqW:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/7de82dbe1568191babfe556f6307c09aff31e1f5/drake/examples/kinova_jaco_arm/run_controlled_jaco_demo.cc#L137)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure why this is here.
</blockquote></details>

Removed.

---

*[drake/examples/kinova_jaco_arm/run_setpose_jaco_demo.cc, line 11 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-KlTm9ax_4b6sOmhUKp3:-KlUi72_pv4IZErr5ibg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7de82dbe1568191babfe556f6307c09aff31e1f5/drake/examples/kinova_jaco_arm/run_setpose_jaco_demo.cc#L11)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This alpha sorted better in the previous location
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-:-KlV8yr5RBP0Xl1L3ltd:bnfp4nl)*

**Comment by rcory** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6204#-:-KlZwruYROcHRP-gPskC:b-l70wzf)*

**Pull request merged**
