### PR TITLE
Suppress some Mac-specific linker warnings.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #5183.

@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5338)

### CODE REVIEW

**Comment by liangfok** [comment]
I just did a clean build on OSX and encountered both "compact unwind" and, surprisingly, "pthread" warnings:

https://gist.github.com/liangfok/a4efc3c5cf4400aaa5d14fbc23deb051

I'm surprised because I was fairly sure the pthread warnings were addressed by #5333.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke1bC1hJoRcAXh7pn57:b-eoqgw5)*

**Comment by liangfok** [comment]
^^^ I'm using 4c12faa0623c773e252661db935e65f6a469223b.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke1bYFtpMv9hX9rDEfK:bl1u6mc)*

**Comment by david-german-tri** [comment]
> encountered both "compact unwind"

Are you sure?  I don't see any of those after you do `git checkout ct` in your gist.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke4snHVkGmwQjB15JoH:b-hkycxd)*

**Comment by liangfok** [comment]
Here is an example of the "compact unwind" warning from my gist:

> INFO: From Linking drake/solvers/mathematical_program_test:
ld: warning: could not create compact unwind for ___dmumps_parallel_analysis_MOD_dmumps_715: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _write_float: stack subq instruction is too different from dwarf stack size

Based on my web browser's search bar, there are 87 instances of it in the gist.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke4v88ak7llsSGt73kC:b-vsxjro)*

**Comment by liangfok** [comment]
Oh, sorry, I must have accidentally mixed up two outputs into a single gist. I think you're right. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke4vOZ_YrE0QhHdpskg:blx832w)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke4wFlGIJ_mL9TegOQH:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5338#-:-Ke5ezbfWSnuLx5XcJXa:bnfp4nl)*

**Pull request merged**
