### PR TITLE
Extract symbolic extraction routines into symbolic_extraction

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This implements Step 3 / 7 of the PR Plan in Issue #5890.

This merge can be squashed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5972)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please.
+@soonho-tri for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-KiqU55PJhp8MUS3oXFh:bq4p0lu)*

**Comment by hongkai-dai** [comment]
As we have separate files `symbolic_extraction.h/cc`, could you add tests for the functions inside these files?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-KiqVZWWKsbP79iqkX8k:b-6tfju2)*

**Comment by soonho-tri** [comment]
First pass done. Only minor comments since this PR is about code-migration without changing functionalities. PTAL.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/solvers/symbolic_extraction.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuLjevuGeSrnzatnjW:-KiuLjevuGeSrnzatnjX:b-kn69k1) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L3)):*
> ```cpp
> #include "drake/solvers/symbolic_extraction.h"
> 
> #include <algorithm>
> ```

FYI, the following `#include`s are sufficient for this file:
```c++
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
```

---

*[drake/solvers/symbolic_extraction.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuLrPik2-DwN_l8x6a:-KiuLrPik2-DwN_l8x6b:bn98s5o) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L24)):*
> ```cpp
> namespace internal {
> 
> using std::enable_if;
> ```

FYI, the following `using std::`s are sufficient for this file:
```c++
using std::endl;
using std::make_pair;
using std::map;
using std::numeric_limits;
using std::ostringstream;
using std::pair;
using std::runtime_error;
using std::string;
using std::unordered_map;
```

---

*[drake/solvers/symbolic_extraction.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuKzPjVd5oTPr4RZyF:-KiuKzPjVd5oTPr4RZyG:b516lx3) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L41)):*
> ```cpp
> using std::unordered_map;
> using std::vector;
> ```

then, thanks to `using std::...`, we can do the following substitution for the rest of the file:
`std::string` -> `string`
`std::ostringstream` -> `ostringstream`
`std::runtime_error` -> `runtime_error`

---

*[drake/solvers/symbolic_extraction.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuM1XGFu1YF4nEysZR:-KiuM1XHQL-ru7b33pt7:b-abz41c) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L89)):*
> ```cpp
>   }
> 
>   // 2. Construct decompose v as
> ```

nit: `2.` -> `1.`

---

*[drake/solvers/symbolic_extraction.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuJtzBXzY6PqdgA7ls:-KiuJtzCSC053Qm6xp3b:bleng7m) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L1)):*
> ```objc
> #include <algorithm>
> ```

FYI, the following `#include`s are sufficient for this file:
```c++
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
```

---

*[drake/solvers/symbolic_extraction.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8gt-9i5lnp4Rs8R0:-Kiu8gt-9i5lnp4Rs8R1:b-8375fn) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L23)):*
> ```objc
> namespace internal {
> 
> class SymbolicError : public std::runtime_error {
> ```

Needs a Doxygen class description.

---

*[drake/solvers/symbolic_extraction.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu7xf_5l55ZgVh10xq:-Kiu7xf_5l55ZgVh10xr:bnmzwwx) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L26)):*
META `const double` -> `double` in `.h` files.

Reference: http://drake.mit.edu/code_style_guide.html
> You must not use const in a function declaration where it adds no meaning. That occurs in pass-by-value parameter declarations, where const int i and int i mean the same thing, and in return-by-value declarations, where int f() and const int f() are also synonymous. You may add const to such parameter declarations in the function definition, where it does indicate that the implementation will not modify its own copy of the parameter value. The C++ standard explicitly states that the signatures are identical with or without the const in these cases, see Overloadable declarations. (This applies to volatile also.)

---

*[drake/solvers/symbolic_extraction.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8SG9jZbiEdL6Yn5F:-Kiu8SGASTdic9HxBr5l:b-1hdfgr) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L36)):*
> ```objc
> };
> 
> // Given an expression `e`, extract all variables inside `e`, append these
> ```

META: needs Doxygen-style comments (`///` or `/**`). 
Probably better to use `/**` to have consistency in the file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-KiuMUKzu7uivD5Ukj3F:b-h5bwiv)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-KiudIUZ1SiHpYo7PDgZ:b-3mz15d)*

**Comment by EricCousineau-TRI** [comment]
@hongkai-dai I've started some initial unittests here: https://github.com/EricCousineau-TRI/drake/pull/3/files#diff-e12fbdefca6a2f2c07585533d4a073fa
@soonho-tri: Can I ask if you already have something like this planned?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-KixEh23hZci8EKkXbvE:binztvd)*

**Comment by soonho-tri** [comment]
No, I don't have anything written yet. The tests look nice!

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-KizVF8K_7MG0T-Di5PR:bap14zf)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/symbolic_extraction.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuLjevuGeSrnzatnjW:-Kj3g59FDjV1ebXYH4ul:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L3)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, the following `#include`s are sufficient for this file:
```c++
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
```
</blockquote></details>

Done.

---

*[drake/solvers/symbolic_extraction.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuLrPik2-DwN_l8x6a:-Kj3g5n4ienqAZtX2rsr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L24)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, the following `using std::`s are sufficient for this file:
```c++
using std::endl;
using std::make_pair;
using std::map;
using std::numeric_limits;
using std::ostringstream;
using std::pair;
using std::runtime_error;
using std::string;
using std::unordered_map;
```
</blockquote></details>

Done.

---

*[drake/solvers/symbolic_extraction.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuKzPjVd5oTPr4RZyF:-Kj3g6Vu9FxQ5_r8JV__:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L41)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

then, thanks to `using std::...`, we can do the following substitution for the rest of the file:
`std::string` -> `string`
`std::ostringstream` -> `ostringstream`
`std::runtime_error` -> `runtime_error`

</blockquote></details>

Done.

---

*[drake/solvers/symbolic_extraction.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuM1XGFu1YF4nEysZR:-Kj3g7zFdsaxRWVNf7R7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.cc#L89)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit: `2.` -> `1.`
</blockquote></details>

Done.

---

*[drake/solvers/symbolic_extraction.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-KiuJtzBXzY6PqdgA7ls:-Kj4AY0V-l9NuGSnx4C8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L1)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, the following `#include`s are sufficient for this file:
```c++
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
```
</blockquote></details>

Done.

---

*[drake/solvers/symbolic_extraction.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8gt-9i5lnp4Rs8R0:-Kj3gAP2XXZNh_t2SVM7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Needs a Doxygen class description.
</blockquote></details>

Done.

---

*[drake/solvers/symbolic_extraction.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu7xf_5l55ZgVh10xq:-Kj4AjX7P1H0BhWMZhfS:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L26)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META `const double` -> `double` in `.h` files.

Reference: http://drake.mit.edu/code_style_guide.html
> You must not use const in a function declaration where it adds no meaning. That occurs in pass-by-value parameter declarations, where const int i and int i mean the same thing, and in return-by-value declarations, where int f() and const int f() are also synonymous. You may add const to such parameter declarations in the function definition, where it does indicate that the implementation will not modify its own copy of the parameter value. The C++ standard explicitly states that the signatures are identical with or without the const in these cases, see Overloadable declarations. (This applies to volatile also.)
</blockquote></details>

Done. Thanks!

---

*[drake/solvers/symbolic_extraction.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8SG9jZbiEdL6Yn5F:-Kj3gJAWTPiPTNA9EPtV:b-6u4icp) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L36)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META: needs Doxygen-style comments (`///` or `/**`). 
Probably better to use `/**` to have consistency in the file?
</blockquote></details>

Done. We may want to consider switching to internal-only Doxygen, `/*`, but will defer to that to the platform reviewer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/test/symbolic_extraction_test.cc, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kj4C0lEkpfBBW2MRnfu:-Kj4C0lFZAs5-_EVZJTQ:bmri4ff) ([raw file](https://github.com/robotlocomotion/drake/blob/bf80151ed2727847553c2c3a879afe5244780cf3/drake/solvers/test/symbolic_extraction_test.cc#L75)):*
> ```cpp
> namespace {
> 
> const double tol = 1e-14;
> ```

styleguide says we should name it as `kTol` https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/solvers/test/symbolic_extraction_test.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kj4CTfopIaQEdxJMPnJ:-Kj4CTfopIaQEdxJMPnK:byuqrnr) ([raw file](https://github.com/robotlocomotion/drake/blob/bf80151ed2727847553c2c3a879afe5244780cf3/drake/solvers/test/symbolic_extraction_test.cc#L81)):*
> ```cpp
>   Variable y("y");
>   Variable z("z");
>   VectorXDecisionVariable vars_expected(3);
> ```

Use `VectorDecisionVariable<3>` instead?

---

*[drake/solvers/test/symbolic_extraction_test.cc, line 143 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kj4GkFI9VSZiPLIsmF0:-Kj4GkFI9VSZiPLIsmF1:b-hcqip2) ([raw file](https://github.com/robotlocomotion/drake/blob/bf80151ed2727847553c2c3a879afe5244780cf3/drake/solvers/test/symbolic_extraction_test.cc#L143)):*
> ```cpp
>   Variable z("z");
> 
>   VectorXDecisionVariable vars_expected(num_var);
> ```

Would you add more `Q_in` to test?  such as a diagonal matrix, a non-diagonal but symmetric matrix, etc, so that we have more granularity in the test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972)*

**Comment by EricCousineau-TRI** [comment]
*[drake/solvers/symbolic_extraction.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8SG9jZbiEdL6Yn5F:-Kj4HkapRGH08YXSCf5O:b-9iuxe0) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. We may want to consider switching to internal-only Doxygen, `/*`, but will defer to that to the platform reviewer.
</blockquote></details>

Derp, I forgot that you were platform reviewer. What do you prefer? Public Doxygen, `/**`, or private, `/*`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/test/symbolic_extraction_test.cc, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kj4C0lEkpfBBW2MRnfu:-Kj4IeEDEjFTZOWmj1pg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf80151ed2727847553c2c3a879afe5244780cf3/drake/solvers/test/symbolic_extraction_test.cc#L75)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

styleguide says we should name it as `kTol` https://google.github.io/styleguide/cppguide.html#Constant_Names
</blockquote></details>

Done.

---

*[drake/solvers/test/symbolic_extraction_test.cc, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kj4CTfopIaQEdxJMPnJ:-Kj4IefSGvpB0jttYMB9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf80151ed2727847553c2c3a879afe5244780cf3/drake/solvers/test/symbolic_extraction_test.cc#L81)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Use `VectorDecisionVariable<3>` instead?
</blockquote></details>

Done.

---

*[drake/solvers/test/symbolic_extraction_test.cc, line 143 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kj4GkFI9VSZiPLIsmF0:-Kj4LEDfGGgp9TPYiA9M:b-8qsv0o) ([raw file](https://github.com/robotlocomotion/drake/blob/bf80151ed2727847553c2c3a879afe5244780cf3/drake/solvers/test/symbolic_extraction_test.cc#L143)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Would you add more `Q_in` to test?  such as a diagonal matrix, a non-diagonal but symmetric matrix, etc, so that we have more granularity in the test?
</blockquote></details>

Done.
Made it as a quick for-loop. Let me know if you would like me to extract it into another function if you would like, for easier debugging if it fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-Kj4MLM1mwMnCXjhla8u:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 4 files at r2, 2 of 3 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/symbolic_extraction.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8SG9jZbiEdL6Yn5F:-Kj4RJuNdzAgi12rGnbc:bpfvir2) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L36)):*
> switching to internal-only Doxygen, `/*`

Let's go to this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/symbolic_extraction.h, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-Kiu8SG9jZbiEdL6Yn5F:-Kj4ZYNFZDEQ6-_nNXzQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20b41a9e2056af829fe8b6f0141b21b25311e2b2/drake/solvers/symbolic_extraction.h#L36)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> switching to internal-only Doxygen, `/*`

Let's go to this way.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5972#-:-Kj4iYHLYYwTcoC3ml0k:bnfp4nl)*

**Pull request merged**
