### PR TITLE
Added allegro hand model for simulation

### PR DESCRIPTION
**Pull request by WenzhenYuan-TRI**
Add the model files, both .urdf and .sdf files, under the manipulation/models folder. 
Add the demo of running the simulation hand under constant load on all the joints. 
@naveenoid @amcastro-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9250)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Note that @WenzhenYuan-TRI needs to be added to the RobotLocomotion GitHub organization.

@drake-jenkins-bot ok to test

**Comment by WenzhenYuan-TRI** [comment]
+@naveenoid + @amcastro-tri  for feature review

**Comment by amcastro-tri** [comment]
FTR. @WenzhenYuan-TRI found many problems with the physical parameters of the original model she obtained. Thus she had to hack her way around these problems to get something running in sim.
Per f2f, now she'll work on making good physical estimations of these parameters (inertias and damping mostly) using geometry processing tools. Thanks to @rcory for providing notes on how to do this using Meshlab.

**Comment by jwnimmer-tri** [comment]
The text works anywhere except the original PR description (first post) -- but only for organizational members; @WenzhenYuan-TRI didn't have the bits.

**Comment by WenzhenYuan-TRI** [comment]
Hi Rick @rcory , 
Yes the .STL files are not used for the simulation. I added them because they are the original reference for the model, and I converted the .obj files from them. 

I'm about to submit another pull request with multiple modifications on this work. I'll remove the .STL files in the new request.

Wenzhen

**Pull request closed without merging**
