### PR TITLE
pybind: Add drake_optional_pybind to address #7844.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I believe this should address #7844; will try to test directly on a Mac once I gain access to one.

\cc @RussTedrake 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7847)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-release

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-release please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please.

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri for feature and platform review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7847#-:-L3auV0MM4wcl7qw_bEa:bym8s3v)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7847#-:-L3cXfzfZ-uJVJw1Xjel:bnfp4nl)*

**Pull request merged**
