### PR TITLE
[meldis] Auto-quit when idle for more than 15 minutes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri feature.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445#-:-MuRUUOu5FWpx5WKnSQm:b-lub94m)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a couple of questions.
+@ggould-tri for platform review on Monday per schedule please, thank you.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445#-:-MuXPcqrB_ECMWVpd0dy:b-vjulo1)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXLgf93OLdWwzK8P8T:-MuXLgf93OLdWwzK8P8U:b-38wvhe) (no related file):*
BTW, when I run `meldis` it seems like there's a ton a dependency that comes from pydrake. Are those necesssary? I'd imagine all it depends on is Meshcat.

---
___
*[geometry/meshcat.cc, line 523 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXMIsjDoqO7eFMaIrh:-MuXMIsk85_eYGd1ApuI:b-w9glqz) ([raw file](https://github.com/robotlocomotion/drake/blob/a7a6ab7aff76a1c9dcf599381673cb62d1273215/geometry/meshcat.cc#L523)):*
> ```cpp
>     std::promise<int> p;
>     std::future<int> f = p.get_future();
>     loop_->defer([this, p = std::move(p)]() mutable {
> ```

BTW, This seems to be the conventional way to pass to the websocket thread, but I'm still trying to figure out how exactly the websocket thread "catches" it. The link to uWebSockets' documentation provided below doesn't help much. Can you explain?
___
*[bindings/pydrake/visualization/meldis.py, line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXD3XS9DzJaAUuQ57X:-MuXD3XS9DzJaAUuQ57Y:b-v7gbq5) ([raw file](https://github.com/robotlocomotion/drake/blob/a7a6ab7aff76a1c9dcf599381673cb62d1273215/bindings/pydrake/visualization/meldis.py#L198)):*
> ```Python
>             return
> 
>         # One-time initialiation.
> ```

nit, s/initialiation/initialization

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXLgf93OLdWwzK8P8T:-MuXRSSz6sckJ6uTlXGg:b-f4r714) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, when I run `meldis` it seems like there's a ton a dependency that comes from pydrake. Are those necesssary? I'd imagine all it depends on is Meshcat.
</blockquote></details>

Yes, the imports (shown below) are necessary and relevant.  If things like "how to display a contact surface" ever get added to this tool, that feature would similarly import that C++ code from pydrake to do it, instead of re-implementing it from scratch.

```
from pydrake.common.eigen_geometry import (
    Quaternion,
)
from pydrake.geometry import (
    Box,
    Capsule,
    Cylinder,
    Ellipsoid,
    Mesh,
    Meshcat,
    Rgba,
    Sphere,
)
from pydrake.lcm import (
    DrakeLcm,
)
from pydrake.math import (
    RigidTransform,
    RotationMatrix,
)
from pydrake.multibody.meshcat import (
    _PointContactVisualizer,
    _PointContactVisualizerItem,
    ContactVisualizerParams,
)
```

---
___
*[geometry/meshcat.cc, line 523 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXMIsjDoqO7eFMaIrh:-MuXSE0TArUr5t5wEiQX:b-omw0tu) ([raw file](https://github.com/robotlocomotion/drake/blob/a7a6ab7aff76a1c9dcf599381673cb62d1273215/geometry/meshcat.cc#L523)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, This seems to be the conventional way to pass to the websocket thread, but I'm still trying to figure out how exactly the websocket thread "catches" it. The link to uWebSockets' documentation provided below doesn't help much. Can you explain?
</blockquote></details>

OK I haven't ever tracked it down in detail, no.  I know the constructor launches a `std::thread`, which shares the `loop_` with our main thread.  We toss functors into the loop, and it wakes up to handle them once it sees any (or has any IP traffic, or etc).  I mentally mapped it to "standard event loop idiom" and didn't dig down to see this particular API set.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXLgf93OLdWwzK8P8T:-MuXhLskCKb9k7zMjIaB:b-g6llej) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, the imports (shown below) are necessary and relevant.  If things like "how to display a contact surface" ever get added to this tool, that feature would similarly import that C++ code from pydrake to do it, instead of re-implementing it from scratch.

```
from pydrake.common.eigen_geometry import (
    Quaternion,
)
from pydrake.geometry import (
    Box,
    Capsule,
    Cylinder,
    Ellipsoid,
    Mesh,
    Meshcat,
    Rgba,
    Sphere,
)
from pydrake.lcm import (
    DrakeLcm,
)
from pydrake.math import (
    RigidTransform,
    RotationMatrix,
)
from pydrake.multibody.meshcat import (
    _PointContactVisualizer,
    _PointContactVisualizerItem,
    ContactVisualizerParams,
)
```
</blockquote></details>

Makes sense. Thanks.

---
___
*[geometry/meshcat.cc, line 523 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MuXMIsjDoqO7eFMaIrh:-MuXirNP-vdCDwY4VYwL:b-aty4ee) ([raw file](https://github.com/robotlocomotion/drake/blob/a7a6ab7aff76a1c9dcf599381673cb62d1273215/geometry/meshcat.cc#L523)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I haven't ever tracked it down in detail, no.  I know the constructor launches a `std::thread`, which shares the `loop_` with our main thread.  We toss functors into the loop, and it wakes up to handle them once it sees any (or has any IP traffic, or etc).  I mentally mapped it to "standard event loop idiom" and didn't dig down to see this particular API set.
</blockquote></details>

Reading more in the class (WebSocketMain) helped with my understanding. Thanks.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:, minor quibbles below.
My availability may be intermittent so feel free to dismiss me from discussions at your discretion.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445#-:-MukQCERBs3h8-RAdWra:b-ykme70)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[geometry/meshcat.h, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MukH4iQ2e6UiaN3kKv_:-MukH4iQ2e6UiaN3kKva:btb0lme) ([raw file](https://github.com/robotlocomotion/drake/blob/174200da03ea402e87634b6ab9f5bb58c661cec8/geometry/meshcat.h#L106)):*
> ```objc
>   std::string ws_url() const;
> 
>   /** (Advanced) Returns the number of currently-open websocket connections. */
> ```

minor, at author's discretion, it might be worth calling out explicitly that this call can take a surprising amount of time (being inter-thread communication).  This is a method that would be unusually tempting to let slip into a tight loop.
___
*[geometry/meshcat.cc, line 524 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MukNdQR87iUUM4x3iW4:-MukNdQR87iUUM4x3iW5:b-b2lh3o) ([raw file](https://github.com/robotlocomotion/drake/blob/174200da03ea402e87634b6ab9f5bb58c661cec8/geometry/meshcat.cc#L524)):*
> ```cpp
>     std::future<int> f = p.get_future();
>     loop_->defer([this, p = std::move(p)]() mutable {
>       DRAKE_DEMAND(IsThread(websocket_thread_id_));
> ```

minor:  Have you checked what happens when a DRAKE_DEMAND fails inside of a deferred promise?  In many frameworks this loses stack or error text information.
___
*[bindings/pydrake/visualization/meldis.py, line 226 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MukOev8DgcmA3uTIkax:-MukOev8DgcmA3uTIkay:b-91b5t) ([raw file](https://github.com/robotlocomotion/drake/blob/174200da03ea402e87634b6ab9f5bb58c661cec8/bindings/pydrake/visualization/meldis.py#L226)):*
> ```Python
>         self._lcm.Subscribe(channel=channel, handler=_parse_and_handle)
> 
>     def serve_forever(self, *, idle_timeout=0):
> ```

minor:  Zero is a bad "forever" sentinel value for times, because it is also a meaningful time itself and results in perplexing behaviour if the caller messes up.  Consider `-1` or explicit `None` (and changing `<=` correspondingly to `<` or `is None` in the check below, and also the argument help).

(or https://stackoverflow.com/a/70811103 if you want to get fancy with the argparse arg, but that's perhaps excessive)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri (waiting on @ggould-tri and @xuchenhan-tri)

___
*[geometry/meshcat.h, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MukH4iQ2e6UiaN3kKv_:-Muko5z89cdusLYb5FQc:blgcwmg) ([raw file](https://github.com/robotlocomotion/drake/blob/174200da03ea402e87634b6ab9f5bb58c661cec8/geometry/meshcat.h#L106)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor, at author's discretion, it might be worth calling out explicitly that this call can take a surprising amount of time (being inter-thread communication).  This is a method that would be unusually tempting to let slip into a tight loop.
</blockquote></details>

Done (by making it faster).
___
*[geometry/meshcat.cc, line 524 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MukNdQR87iUUM4x3iW4:-MukkB-j1lwYZJ4G0ZtT:b-34yeo1) ([raw file](https://github.com/robotlocomotion/drake/blob/174200da03ea402e87634b6ab9f5bb58c661cec8/geometry/meshcat.cc#L524)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Have you checked what happens when a DRAKE_DEMAND fails inside of a deferred promise?  In many frameworks this loses stack or error text information.
</blockquote></details>

Done (removed it).
___
*[bindings/pydrake/visualization/meldis.py, line 226 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16445#-MukOev8DgcmA3uTIkax:-MukmC4gCBxaENY4_kZ0:bnlfime) ([raw file](https://github.com/robotlocomotion/drake/blob/174200da03ea402e87634b6ab9f5bb58c661cec8/bindings/pydrake/visualization/meldis.py#L226)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Zero is a bad "forever" sentinel value for times, because it is also a meaningful time itself and results in perplexing behaviour if the caller messes up.  Consider `-1` or explicit `None` (and changing `<=` correspondingly to `<` or `is None` in the check below, and also the argument help).

(or https://stackoverflow.com/a/70811103 if you want to get fancy with the argparse arg, but that's perhaps excessive)
</blockquote></details>

Done (for the API); the command-line still accepts zero as the sentinel.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16445)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
