### PR TITLE
Add jpg,png,vtm,vtp to list of known data-file extensions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As discovered in #6834, our install rules (and thus also our internal model-data labels) were omitting some files.

With this PR, all of the `valkyrie` model data is being installed (except for the xacro file, which I understand to be a source artifact, not a runtime resource):
```console
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel run :install -- $PWD/prefix > /dev/null
...
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ diff -r prefix/share/drake/drake/examples/valkyrie/urdf drake/examples/valkyrie/urdf
Only in drake/examples/valkyrie/urdf/model/meshes/materials: materials.xacro
```

(Before this PR, the diff command shown here would list many files as only being in the source tree.)

This PR also removes some `png` files that appeared to be unused, and were un-installable because their names contained spaces.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6919)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for all review, please.

Note that I've curated multiple commits here and asked reviewable to show them independently, in case that's more useful to review.

**Comment by RussTedrake** [comment]
:lgtm: -- all of the changes look reasonable to me, but I'm not sure my .bzl is strong enough to catch any subtle errors.  I agree with the concept (all of those extensions should be included along with the models that reference them)

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6919#-:-KsR2nJCOV1lL0mMxgVr:b-h97g7s)*

**Comment by jwnimmer-tri** [comment]
+@jamiesnape or +@stonier for second review (of the `bzl` changes), please.  First one wins; you can untag the other party.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6919#-:-KsR5iqK7qMYXPftebZm:b-a6r6tr)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6919#-:-KsTs5TsK9O-kz41Ml8I:bnfp4nl)*

**Pull request merged**
