### PR TITLE
Add a tutorial on the debugging tips for MathematicalProgram.

### LINKED ISSUE #13091: mathematicalprogram: add constraint naming/debugging workflow to tutorials
I just responded to a student question, and realized that I might have been hiding a pretty useful debugging workflow.  @hongkai-dai -- would you consider adding this to your MP tutorials?

> But please know that there are some good tools for debugging constraints in mathematical program.  > I'm sorry we haven't advertised them better.
> 
> Take a look at the trick shot example in https://github.com/RussTedrake/underactuated/blob/master/examples/contact.ipynb e.g.
```
prog.AddConstraint(xdot[1] == -e * xdot[0]).evaluator().set_description('xdot_wall')
prog.AddConstraint(zdot[1] == 3.*zdot_pre/5. - 2.*r*thetadot[0]/5.).evaluator().set_description('zdot_wall')
```
> You can add names for each constraints with that (slightly clunky) API.  
> then later, you can do something like:
```
result = Solve(prog)
if not result.is_success():
    infeasible = GetInfeasibleConstraints(prog, result)
    print("Infeasible constraints:")
    for i in range(len(infeasible)):
        print(infeasible[i])
```
> to get a super useful display that tells you which constraints are failing.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #13091 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815#-:-MWWsx2wASUDJFTrlcMK:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
This is great.  Minor comments below.!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815#-:-MWdYnPp27gB1XPePs5l:b-jl9b0j)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[tutorials/debug_mathematical_program.ipynb, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdXzxZ4if_RnTyTF3r:-MWdXzxZ4if_RnTyTF3s:bw0rk26) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L43)):*
> ```
>     "def constraint(x):\n",
>     "    return [np.cos(x[0]) + 2 * np.cos(x[0] - x[1])]\n",
>     "# Find a solution satisfying\n",
> ```

nit: add a whitespace line here?
___
*[tutorials/debug_mathematical_program.ipynb, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdXBgk37nnuEqD1Eiv:-MWdXBgk37nnuEqD1Eiw:bdt4dmr) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L44)):*
> ```
>     "    return [np.cos(x[0]) + 2 * np.cos(x[0] - x[1])]\n",
>     "# Find a solution satisfying\n",
>     "# 1 <= cos(x[0]) + 2 * cos(x[0] - x[1]) <= 2\n",
> ```

perhaps you could even plot this landscape here?  it would probably help...
___
*[tutorials/debug_mathematical_program.ipynb, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdXXIJ9n8LrcxhhQ9T:-MWdXXIJ9n8LrcxhhQ9U:bftdwew) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L69)):*
> ```
>    "metadata": {},
>    "source": [
>     "In the example above, you could see that with a bad initial guess $x = [0, 0]$, the solver gets stuck and reports the problem being infeasible (the reason for getting stuck is that the gradient of the constraint function $cos(x[0]) + 2cos(x[0]-x[1])$ is zero at the initial guess $x=[0, 0]$, hence the gradient-based solver doesn't know how to move the decision variables. This phenominon also appears when solving an inverse-kinematics problem with an initial pose at singularity, or solving a unit-length constraint $x^Tx=1$ with initial guess $x=0$); but by changing the initial guess, the solver can find a solution.\n",
> ```

typo: should be "phenomenon"
___
*[tutorials/debug_mathematical_program.ipynb, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdY6Ld432sqRothERh:-MWdY6Ld432sqRothERi:b-a27q23) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L165)):*
> ```
>     "constraint1 = prog.AddConstraint(lambda z: [z.dot(z)], [1], [np.inf], x)\n",
>     "constraint1.evaluator().set_description(\"outside unit circle\")\n",
>     "# Add the constraint x[0]**2 + 4 * x[1]**2 <= 4\n",
> ```

nit: this is a wall of text/code.  add some whitespace lines?
___
*[tutorials/debug_mathematical_program.ipynb, line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdYPHj99bOSWTGXNhZ:-MWdYPHj99bOSWTGXNh_:buf2o6d) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L259)):*
> ```
>     "ax.axis('equal')\n",
>     "\n",
>     "def update(x):\n",
> ```

can we choose a better name for this function?  even "visualization_callback"?
___
*[tutorials/debug_mathematical_program.ipynb, line 301 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdYfy61b7bS1EfuUUV:-MWdYfy61b7bS1EfuUUW:b8bqqdz) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L301)):*
> ```
>     "p1 = prog.NewContinuousVariables(2, \"p1\")\n",
>     "p2 = prog.NewContinuousVariables(2, \"p2\")\n",
>     "# Add the constraint that p1 is in an ellipsoid (p1(0)-1)**2 + 4*(p1(1)-2)**2 <= 1\n",
> ```

nit: whitespace
___
*[tutorials/debug_mathematical_program.ipynb, line 335 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdYeOR55joHu_G0PTP:-MWdYeOR55joHu_G0PTQ:b8bqqdz) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L335)):*
> ```
>     "prog = mp.MathematicalProgram()\n",
>     "x = prog.NewContinuousVariables(2)\n",
>     "# Add the constraint x^T * x <= 1\n",
> ```

nit: whitespace

**Comment by RussTedrake** [comment]
___
*[tutorials/debug_mathematical_program.ipynb, line 203 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdZi5k3Fbz5FKUxmCa:-MWdZi5l0KLB9RoCuHRW:b-8ecjkt) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L203)):*
> ```
>     "4. For Gurobi, call `prog.SetSolverOption(GurobiSolver().solver_id(), \"OutputFlag\", True)`.\n",
>     "5. For SCS, call `prog.SetSolverOption(ScsSolver().solver_id(), \"verbose\", 1)`.\n",
>     "6. For OSQP, call `prog.SetSolverOption(OsqpSolver().solver_id(), \"verbose\", 1)`."
> ```

anything for MixedIntegerBranchAndBound?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[tutorials/debug_mathematical_program.ipynb, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdXBgk37nnuEqD1Eiv:-MWe6vJr-OknAug_C0DO:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L44)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

perhaps you could even plot this landscape here?  it would probably help...
</blockquote></details>

Done. Good call.
___
*[tutorials/debug_mathematical_program.ipynb, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdXXIJ9n8LrcxhhQ9T:-MWe77dG0fRLIafDiLAX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L69)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

typo: should be "phenomenon"
</blockquote></details>

Done.
___
*[tutorials/debug_mathematical_program.ipynb, line 203 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdZi5k3Fbz5FKUxmCa:-MWe9VkG5hxiOnIITD5V:b-kr1oq8) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L203)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

anything for MixedIntegerBranchAndBound?
</blockquote></details>

Good call. Currently I haven't implemented anything print out method for the MixedIntegerBranchAndBound class. I will add that later. I filed the issue #14822 
___
*[tutorials/debug_mathematical_program.ipynb, line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWdYPHj99bOSWTGXNhZ:-MWeALJG6_QL3tVKY-Qe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/afe932dd252cf60bfbd6e6be77286e0b260d9bd2/tutorials/debug_mathematical_program.ipynb#L259)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can we choose a better name for this function?  even "visualization_callback"?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks for doing this!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815#-:-MWeOyLO256n1Zp5ovos:bg5ss8t)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815#-:-MWeQqAq2KTZgSTRMIVL:b-2hj6f6)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; one note below.

FYI I'm hoping to bring in Anzu's collision remover code soon, so being able to reference this tutorial in the documentation when I do so will make my life much easier!

> Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815#-:-MWee_zL6VbpavEY6eZu:bp99aff)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[tutorials/debug_mathematical_program.ipynb, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWedec2755lTDKnMv1Q:-MWedec2755lTDKnMv1R:b-ahpn88) ([raw file](https://github.com/robotlocomotion/drake/blob/be7b35eef637c60204a87a84c4659a70334b729c/tutorials/debug_mathematical_program.ipynb#L25)):*
> ```
>     "After constructing and solving an optimization problem through Drake's `MathematicalProgram` interface, you might not get the desired results. For example, you might expect the problem to have a solution, while `MathematicalProgram` reports that the problem is not solved succesfully. In this tutorial we provide some tips to debug `MathematicalProgram` when it doesn't behave desirably.\n",
>     "\n",
>     "First you should understand whether the optimization problem is convex or not. For a convex problem (like LP, QP, SDP), when the problem is feasible, then theoretically the solver should always find a solution; on the other hand if the problem is non-convex and solved through gradient-based solvers (like SNOPT/IPOPT), then the solver might fail to find a solution even if one exists. When the gradient-based solver (like SNOPT/IPOPT) reports the problem being infeasible, it only means that locally in the search region, the optimization problem doesn't have a solution. A solution could exist far away from where the solver gets stuck, but the solver is trapped in a certain region and can't jump to the distant solution. Often if you improve the initial guess, then the solver might be able to find the solution.\n",
> ```

This isn't really a correct description of SNOPT, which can report infeasibility even if the initial guess was feasible or it has reached feasible points in the search if its most recent guess is infeasible when it hits its iteration limit.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @ggould-tri and @RussTedrake)

___
*[tutorials/debug_mathematical_program.ipynb, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14815#-MWedec2755lTDKnMv1Q:-MWexdExEE4L708fSmtA:b-n0ub1d) ([raw file](https://github.com/robotlocomotion/drake/blob/be7b35eef637c60204a87a84c4659a70334b729c/tutorials/debug_mathematical_program.ipynb#L25)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This isn't really a correct description of SNOPT, which can report infeasibility even if the initial guess was feasible or it has reached feasible points in the search if its most recent guess is infeasible when it hits its iteration limit.
</blockquote></details>

Done, good call. I added a paragraph on SNOPT to explain that it could jump to an infeasible solution from a feasible one.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14815)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
