### PR TITLE
Add ReconstructStateTrajectory() to Dircol and implement cubic spline.

### PR DESCRIPTION
**Pull request by Lucy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4575)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@sammy-tri  for feature review, please. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-:-KZYhM3DYe4qoAk3ufhY:broya48)*

**Comment by sammy-tri** [comment]
:lgtm: pending feature review.  It might be worth having either Russ or Hongkai take a quick look to make sure we guessed correctly on the functionality of the MATLAB implementation we're duplicating here?  (or maybe that's overkill, we probably got it)

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-:-KZbAZYXzXGgV5daVJNp:b-uib42p)*

**Comment by Lucy-tri** [comment]
@siyuanfeng-tri might be interested in the use of the spline. @naveenoid and @hongkai-dai might was to know about this, and any comments welcome. 
@jwnimmer-tri for platform review. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-:-KZbBWZhSmzUSNdH9njN:b-sv3oy6)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-:-KZbDomIceYVY-ndCEXu:b-3kogyb)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbMTz7nVFeRv8pdyEd:-KZbMTz82whc3Ov1jIj8:be3lm8b) (no related file):*
BTW I have done only a coding rules pass.  Has feature review already checked that the semantics are correct versus the surrounding code?  Else I can dive in and do that.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbKcogxrjdIREu5oor:-KZbKcogxrjdIREu5oos:b1hmh6a) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.h#L39)):*
> ```objc
>  *    with unbounded/unreasonable numerical integration errors.
>  */
> class DircolTrajectoryOptimization : public DirectTrajectoryOptimization {
> ```

This class is missing disable of copy & assignment, per cppguide.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbKTizfm-5hx8_FSXr:-KZbKTizfm-5hx8_FSXs:b-kimeu2) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.h#L52)):*
> ```objc
> 
>  private:
>   const System<double>* system_;
> ```

Missing value-initialization on POD member field per code_style_guide.  (Add `{}`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-:-KZbSumUqHIh1Ez2RenP:by96gdd)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbbJyhllKekqz9aa8E:-KZbbJyiMxTmOTyAPXI4:b-ltfalh) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc#L76)):*
> ```cpp
>   // regression test.
>   double abs_diff =
>       fabs(linear_avr_of_2_points(0, 0) - spline_interpolation(0, 0));
> ```

Missing `std::` on `fabs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbaTCb8dZ2i120nD1O:-KZbaTCb8dZ2i120nD1P:bk1c2t9) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc#L76)):*
> ```cpp
>   // regression test.
>   double abs_diff =
>       fabs(linear_avr_of_2_points(0, 0) - spline_interpolation(0, 0));
> ```

BTW, i am not sure what's the point of this test. i might just hard code some number here and test against those as a regression test.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbbfC5DDdvGBpcwCDK:-KZbbfC6o_rHp6MNmOp6:b-2jn16o) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.cc#L137)):*
> ```cpp
>     context_->get_mutable_continuous_state()->SetFromVector(state_vec[i]);
>     system_->CalcTimeDerivatives(*context_, continuous_state_.get());
>     derivatives.push_back(continuous_state_->CopyToVector());
> ```

I don't think this part is correct for the anything with floating base joints. More strongly, we can't just do independent spline for any joints that coupled degrees of freedom. @hongkai-dai did you guys handle this before? I am fine letting this pass now, but put a TODO here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbaTCb8dZ2i120nD1O:-KZbeUt7u6_1piV4K3vP:b-gg9xh8) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc#L76)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, i am not sure what's the point of this test. i might just hard code some number here and test against those as a regression test.
</blockquote></details>

The point of the test is to make sure some kind of spline is used, and not a first order hold or zero order hold. The results are different depending on what solver is used, but at this early point in the trajectory they should diverge from linear by about 0.1 (value found by testing snopt, nlopt and ipopt solvers). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by Lucy-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbMTz7nVFeRv8pdyEd:-KZblWbfFFbdlgd68p3P:ba494kl) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I have done only a coding rules pass.  Has feature review already checked that the semantics are correct versus the surrounding code?  Else I can dive in and do that.
</blockquote></details>

@sammy-tri was the designated feature reviewer, and @siyuanfeng-tri also had comments. 

---

*[drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbbJyhllKekqz9aa8E:-KZblDw9tt2xfGbU9Jwr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/examples/Pendulum/test/pendulum_trajectory_optimization_test.cc#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing `std::` on `fabs`.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbbfC5DDdvGBpcwCDK:-KZblIhKv2hMAgTUBmkg:b-dve2gk) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.cc#L137)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I don't think this part is correct for the anything with floating base joints. More strongly, we can't just do independent spline for any joints that coupled degrees of freedom. @hongkai-dai did you guys handle this before? I am fine letting this pass now, but put a TODO here. 
</blockquote></details>

Done: TODO added (happy to add or change it).

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbKcogxrjdIREu5oor:-KZblQCse7MHXvQQ02qX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This class is missing disable of copy & assignment, per cppguide.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbKTizfm-5hx8_FSXr:-KZblRNfrewlx6IqO0pE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.h#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing value-initialization on POD member field per code_style_guide.  (Add `{}`.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbbfC5DDdvGBpcwCDK:-KZbmTMgN57GqudxCFy3:bmzccuc) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.cc#L137)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

Done: TODO added (happy to add or change it).
</blockquote></details>

nit, can you move this to the header file? so it's more obvious. thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by Lucy-tri** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation.cc, line 137 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbbfC5DDdvGBpcwCDK:-KZbp15QNpiLoxRebilp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/90c76b38965deeb44e38980f825e03f054da935f/drake/systems/trajectory_optimization/direct_collocation.cc#L137)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

nit, can you move this to the header file? so it's more obvious. thanks
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by siyuanfeng-tri** [comment]
*[drake/systems/trajectory_optimization/direct_collocation.h, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbqHgQALCBvC0_wnvX:-KZbqHgQALCBvC0_wnvY:bxgs5e0) ([raw file](https://github.com/robotlocomotion/drake/blob/68b61d7f35a8113576bea7340c35cc5dcbbb872b/drake/systems/trajectory_optimization/direct_collocation.h#L52)):*
> ```objc
>   // TODO(Lucy-tri) According to @siyuanfeng-tri, the calculation of
>   // derivatives is not correct for floating base joints. More strongly, we
>   // can't just do independent spline for any joints that coupled degrees of
> ```

use independent splines for joints with coupled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbMTz7nVFeRv8pdyEd:-KZbs2hi25rjRSjBdXL4:b-9gkb06) (no related file):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

@sammy-tri was the designated feature reviewer, and @siyuanfeng-tri also had comments. 
</blockquote></details>

@sammy-tri and @siyuanfeng-tri are you okay with me only doing a style pass?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending discussions.

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 53 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbsTDVJywgxMrd71uJ:-KZbsTDVJywgxMrd71uK:b-4gm6ey) ([raw file](https://github.com/robotlocomotion/drake/blob/68b61d7f35a8113576bea7340c35cc5dcbbb872b/drake/systems/trajectory_optimization/direct_collocation.h#L53)):*
> ```objc
>   // derivatives is not correct for floating base joints. More strongly, we
>   // can't just do independent spline for any joints that coupled degrees of
>   // freedom.
> ```

BTW Is there any way to fail-fast with an assertion on this?  I think not, but would be good to add if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-:-KZbsb7ObEfHqVNhRds5:b67tr8b)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbMTz7nVFeRv8pdyEd:-KZbvJIfDcDUoRLaDM-W:bjery3f) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sammy-tri and @siyuanfeng-tri are you okay with me only doing a style pass?
</blockquote></details>

i am fine with that.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 53 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbsTDVJywgxMrd71uJ:-KZbv5gN314RZPv5sO3l:b-qp4k3f) ([raw file](https://github.com/robotlocomotion/drake/blob/68b61d7f35a8113576bea7340c35cc5dcbbb872b/drake/systems/trajectory_optimization/direct_collocation.h#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there any way to fail-fast with an assertion on this?  I think not, but would be good to add if possible.
</blockquote></details>

hmm, good point. I don't see it either. The system can by any arbitrary thing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbMTz7nVFeRv8pdyEd:-KZbwaMtdt-ZDqZwiZcg:bb7sa0c) (no related file):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i am fine with that.
</blockquote></details>

yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by jwnimmer-tri** [comment]
CI flake
@drake-jenkins-bot linux-clang-experimental-debug please

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbqHgQALCBvC0_wnvX:-KZby4HslAueCkXh_VAX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68b61d7f35a8113576bea7340c35cc5dcbbb872b/drake/systems/trajectory_optimization/direct_collocation.h#L52)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

use independent splines for joints with coupled
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_collocation.h, line 52 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4575#-KZbqHgQALCBvC0_wnvX:-KZbykAab4Qql7-2NASV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/68b61d7f35a8113576bea7340c35cc5dcbbb872b/drake/systems/trajectory_optimization/direct_collocation.h#L52)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4575)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
