### PR TITLE
Make bullet static and hidden and do not install headers

### LINKED ISSUE #8511: Bullet should be a private, statically-linked dependency
See https://github.com/RobotLocomotion/drake/pull/8447#issuecomment-375827867. I looked into it and it does not seem too difficult.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #8511.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8512)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8512#-L9Cae5K7nyp96v3Dmot:-L9Cae5M1dAyEnBh8srY:b-fkeotr) (no related file):*
On master, we currently install `drake/include/drake/multibody/collision/bullet_model.h`, which needs bullet headers.

I haven't pulled this PR locally to test, but I think we need to blacklist that header or else it will still be installed because its transitively referred to?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8512)*

**Comment by jamiesnape** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8512#-L9Cae5K7nyp96v3Dmot:-L9DLnsqCwOnoBICBjkD:bkd346m) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On master, we currently install `drake/include/drake/multibody/collision/bullet_model.h`, which needs bullet headers.

I haven't pulled this PR locally to test, but I think we need to blacklist that header or else it will still be installed because its transitively referred to?
</blockquote></details>

You are correct. Fixed now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8512)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@ggould-tri for platform review, please.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8512#-:-L9DMX2O-zpBk5yYhJdr:bdfvlq8)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8512#-:-L9GOgTP-8x07vIKUxiE:bnfp4nl)*

**Pull request merged**
