### PR TITLE
Add BUILD for gurobi-specific code; remove zmpCoMObserverStateVisualizer

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6303)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review please.  (Sorry, we are a bit short on platform reviewers this week, otherwise I'd push it to someone else.)

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/BUILD, line 563 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6303#-KmCE5KBY6Dwp99tgme3:-KmCE5KBY6Dwp99tgme4:bwg1kha) ([raw file](https://github.com/robotlocomotion/drake/blob/b25ccc5a4230039d341a01a6b02cd868c0045ae7/drake/multibody/BUILD#L563)):*
> ```Python
>     ],
> )
> ```

BTW, let have the comment here as well? (ditto in `systems/controllers/BUILD`) I'm fine with a separate dust-off PR. 
```
# The extra_srcs are required here because cpplint() doesn't understand how to
# extract labels from select() functions yet.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6303#-:-KmCDyUwg87AUo08eoRp:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/BUILD, line 563 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6303#-KmCE5KBY6Dwp99tgme3:-KmCHs4_7UWYn7ix3O9H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b25ccc5a4230039d341a01a6b02cd868c0045ae7/drake/multibody/BUILD#L563)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, let have the comment here as well? (ditto in `systems/controllers/BUILD`) I'm fine with a separate dust-off PR. 
```
# The extra_srcs are required here because cpplint() doesn't understand how to
# extract labels from select() functions yet.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6303)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6303)*

**Pull request merged**
