### PR TITLE
workspace: Upgrade libsdformat to latest release 12.5.0

### PR DESCRIPTION
**Pull request by azeey**
Notable changes from libsdformat 12.0.0 that are relevant to Drake:

## New Features
* Add support for merge-include in the Interface API
* Make `computeMergedModelProxyFrameName` public
* Added `Friction` and `ODE` classes
* Replace custom cmake code with ign-cmake2
* Support printing sdf poses in degrees and allow snapping to commonly used angles

## Bug Fixes
* Allow model frames (`__model__`) to be used as joint parent or child
* Check joint parent link names in `Model::Load`.
* Check joint parent/child names in `Root::Load`.
* Documentation: clarify behavior of `//model/model/static`
* Documentation: only allow one `canonical_link` attribute
* Fix bug where `//include/pose` was ignored when using the Interface API
* Fix bug where a `sdf::ParserConfig` object was not passed to all `sdf::readFile` calls
* Fix joint parent/child frame existence checks to include interface elements
* Fix loading nested include with custom attributes
* Handle `__model__` in joint parent or child when using merge-include
* Use `ParserConfig` more in `parser.cc`
* `inertial.sdf`: fix ambiguities in documentation

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Odd CI flakes regarding `remote_coverage_tools`

@drake-jenkins-bot retest this please

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review

Looks good, but blocking comment / question on need for visibility patch.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250#-:-N2mnFYrDbHhZRLj0hzu:bpkzabt)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @azeey)

___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2mn0IH04ZCp6rTnODc:-N2mn0IH04ZCp6rTnODd:bwfvk9s) ([raw file](https://github.com/robotlocomotion/drake/blob/46e7ce6788064447a42b9409f62a60987e6cb3cf/tools/workspace/sdformat/package.BUILD.bazel#L58)):*
> ```
> #pragma once
> 
> // IGN_DEPRECATED is defined by all ignition libraries, but the version below
> ```

I'm not sure if I understand motivation here.

When do we mix drake-compiled and regular ignition libraries?

**Comment by azeey** [comment]
*[`tools/workspace/sdformat/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2mn0IH04ZCp6rTnODc:-N2n1oJFEMxJWxXp6ghv:b-m2bc9x) ([raw file](https://github.com/robotlocomotion/drake/blob/46e7ce6788064447a42b9409f62a60987e6cb3cf/tools/workspace/sdformat/package.BUILD.bazel#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure if I understand motivation here.

When do we mix drake-compiled and regular ignition libraries?
</blockquote></details>

I actually based most of this on https://github.com/RobotLocomotion/drake/blob/a7ca623fea11d791b62d6eaedf66140e00a487a2/tools/workspace/ignition_math/package.BUILD.bazel. I assumed there was a good reason for it, but I too was confused about mixing drake compiled vs regular ignition libraries.

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for review also.  (I'm on-call for platform on Tuesday anyway, but I should look at this specifically.  Some of the build fixes that are now obsolete were my doing.)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), missing label for release notes (waiting on @azeey and @jwnimmer-tri)

___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2mn0IH04ZCp6rTnODc:-N2nRFjy6ywC5oeIqqhp:b-6lnlol) ([raw file](https://github.com/robotlocomotion/drake/blob/46e7ce6788064447a42b9409f62a60987e6cb3cf/tools/workspace/sdformat/package.BUILD.bazel#L58)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I actually based most of this on https://github.com/RobotLocomotion/drake/blob/a7ca623fea11d791b62d6eaedf66140e00a487a2/tools/workspace/ignition_math/package.BUILD.bazel. I assumed there was a good reason for it, but I too was confused about mixing drake compiled vs regular ignition libraries.
</blockquote></details>

From looking at GitHub blame, it may not apply any more - it was from ~4 yrs ago, and users shouldn't be seeing both.

Can you try removing both instances (this one and in math)?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform), missing label for release notes (waiting on @azeey and @jwnimmer-tri)

___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2mn0IH04ZCp6rTnODc:-N2nWEfmCHEjRUiwftnu:b3qido1) ([raw file](https://github.com/robotlocomotion/drake/blob/46e7ce6788064447a42b9409f62a60987e6cb3cf/tools/workspace/sdformat/package.BUILD.bazel#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From looking at GitHub blame, it may not apply any more - it was from ~4 yrs ago, and users shouldn't be seeing both.

Can you try removing both instances (this one and in math)?
</blockquote></details>

Ah, not remove, but perhaps simplify: https://github.com/azeey/drake/pull/2
(no need for `#ifdef` stuff)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, with two small nits - thanks!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250#-:-N2qQ56KCP8EJiEfaTnC:bvawo0b)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @azeey and @jwnimmer-tri)

___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qQ-7-5Jh1e2hGMe0N:-N2qQ-7-5Jh1e2hGMe0O:b73jh1m) ([raw file](https://github.com/robotlocomotion/drake/blob/46e7ce6788064447a42b9409f62a60987e6cb3cf/tools/workspace/sdformat/package.BUILD.bazel#L58)):*
> ```
> #pragma once
> 
> // IGN_DEPRECATED is defined by all ignition libraries, but the version below
> ```

nit Ah, this is also in `.../ignition_utils/package.BUILD.bazel`. Can you apply analogous patch there too?
(sorry for missing that!)
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qQLFY8tJKOZl0HK_I:-N2qQLFY8tJKOZl0HK_J:b-8y11g5) ([raw file](https://github.com/robotlocomotion/drake/blob/53571e1d65d1716d8b4b72ae8d3571ee89fa36cf/tools/workspace/sdformat/patches/no_global_config.patch#L1)):*
> ```Diff
> Change the global singleton into a bomb.
> ```

nit Can you preserve this comment?

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qQ-7-5Jh1e2hGMe0N:-N2q_tNW3s6iyMmQtjNZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46e7ce6788064447a42b9409f62a60987e6cb3cf/tools/workspace/sdformat/package.BUILD.bazel#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Ah, this is also in `.../ignition_utils/package.BUILD.bazel`. Can you apply analogous patch there too?
(sorry for missing that!)
</blockquote></details>

Done.
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qQLFY8tJKOZl0HK_I:-N2qcO0L838E7W3AmiF-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53571e1d65d1716d8b4b72ae8d3571ee89fa36cf/tools/workspace/sdformat/patches/no_global_config.patch#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you preserve this comment?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by azeey** [comment]
*[`tools/workspace/sdformat/ign_sdf_main.cc` line 51 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qnS7HERt7iY051vjH:-N2qo5M5CKXaL1g8QPI0:baptdri) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/ign_sdf_main.cc#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why do we set preserveIncludes to false?

Given that the purpose of this tool is to upgrade `*.sdf` files from say 1.9 to 1.10 in order to commit the upgrade patch into source control, I would have thought that we should _not_ flatten the include statements.

Maybe I've misunderstood something?

\CC @EricCousineau-TRI
</blockquote></details>

That's just the default behavior and what the tool used to do before the `preserveIncludes` feature was added.  We can change it if needed.

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint on the build system changes.  I'll circle back later to review the config-related patching.

> Reviewed 5 of 10 files at r1, 2 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250#-:-N2qy7fH5z3k0AnGDtU4:b-kxoijs)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @azeey, @EricCousineau-TRI, and @jwnimmer-tri)

___
*[`multibody/parsing/detail_sdf_geometry.cc` line 106 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qwt6A5HYJFTjC09OG:-N2qwt6A5HYJFTjC09OH:b-rvjg05) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/multibody/parsing/detail_sdf_geometry.cc#L106)):*
> ```cpp
>     "heightmap",
>     "mesh",
>     "plane",
> ```

This is missing `"polyline"`.
___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 40 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qluII9qQVE7KVu3Ol:-N2qluII9qQVE7KVu3Om:bg65ycw) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/package.BUILD.bazel#L40)):*
> ```
>         "PROJECT_NAME=SDFormat",
>         "SDF_VERSION_NAME=",
>         "PROJECT_VERSION_MAJOR=%d" % (PROJECT_MAJOR),
> ```

Keeping the version number macros in sync is extra work for us whenever we upgrade.  If we can skip that manual work, we should.

If we just fill in zeros for all of the version numbers, does anything fail?  I don't think Drake will ever check the value of this macro, so as long as libsdformat doesn't branch based on these macros, I think we will probably be able to ignore them.



_Suggestion:_
```
"PROJECT_VERSION_MAJOR=0"
```
___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 127 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qrVVS4xWLPAWvF5aC:-N2qrVVS4xWLPAWvF5aD:b-7attb1) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/package.BUILD.bazel#L127)):*
> ```
>     "include/sdf/parser.hh",
>     "include/sdf/sdf.hh",
>     "include/sdf/sdf_config.h",
> ```

These files are **not** part of `include/sdf/CMakeLists.txt` (as required by the comment atop this list).

For `sdf.hh`, we should just drop all mentions of it entirely.  We do not use it.

For `sdf_config.h`, it looks like we'll need it add it to the list at `SDFORMAT_ALL_PUBLIC_HDRS` instead of here.
___
*[`tools/workspace/sdformat/repository.bzl` line 12 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qmm_h8JTMExJDInrF:-N2qmm_i7LVCwEUrwotM:b-mebm77) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/repository.bzl#L12)):*
> ```Starlark
>         repository = "gazebosim/sdformat",
>         # Make sure to update the PROJECT_* version numbers in
>         # package.BUILD.bazel
> ```

Working

Hopefully this reminder will not be necessary.  Circle back later once the BUILD file is updated.

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`multibody/parsing/detail_sdf_geometry.cc` line 106 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qwt6A5HYJFTjC09OG:-N2rTTFoBHUc9bm2uJJZ:bpgffc9) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/multibody/parsing/detail_sdf_geometry.cc#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is missing `"polyline"`.
</blockquote></details>

I don't think Drake supports `polyline`. Shouldn't it complain that it's not supported?
___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 40 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qluII9qQVE7KVu3Ol:-N2rNqPEDTOJVqtAlnIP:b-iu5kj6) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/package.BUILD.bazel#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Keeping the version number macros in sync is extra work for us whenever we upgrade.  If we can skip that manual work, we should.

If we just fill in zeros for all of the version numbers, does anything fail?  I don't think Drake will ever check the value of this macro, so as long as libsdformat doesn't branch based on these macros, I think we will probably be able to ignore them.
</blockquote></details>

Done. libsdformat doesn't branch on on these, so I think it's safe to do.
___
*[`tools/workspace/sdformat/package.BUILD.bazel` line 127 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qrVVS4xWLPAWvF5aC:-N2rXR191EHJmH6Wq1TX:bn22gxd) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/package.BUILD.bazel#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These files are **not** part of `include/sdf/CMakeLists.txt` (as required by the comment atop this list).

For `sdf.hh`, we should just drop all mentions of it entirely.  We do not use it.

For `sdf_config.h`, it looks like we'll need it add it to the list at `SDFORMAT_ALL_PUBLIC_HDRS` instead of here.
</blockquote></details>

OK, removed `sdf.hh` and put `sdf_config`.h` in `SDFORMAT_ALL_PUBLIC_HDRS`
___
*[`tools/workspace/sdformat/repository.bzl` line 12 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qmm_h8JTMExJDInrF:-N2rXcZM5R7_krkgSN8_:b-uri30h) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/tools/workspace/sdformat/repository.bzl#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Hopefully this reminder will not be necessary.  Circle back later once the BUILD file is updated.
</blockquote></details>

OK, removed per the changes in `package.BUILD.bazel`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @azeey and @EricCousineau-TRI)

___
*[`multibody/parsing/detail_sdf_geometry.cc` line 106 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qwt6A5HYJFTjC09OG:-N2rYBpbAf_UHZIcTsak:b-yyir8q) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/multibody/parsing/detail_sdf_geometry.cc#L106)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

I don't think Drake supports `polyline`. Shouldn't it complain that it's not supported?
</blockquote></details>

Neither does Drake support `heightmap` (#17257) but we still list that here as well.  My guess is that the diagnostic for "not supported" will end up in the caller of this function, instead of here directly.  Mostly for now, I'm just looking for consistency, so matching `GeometryType::HEIGHTMAP` at least keeps everything easy to clean up later, one way or another.

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`multibody/parsing/detail_sdf_geometry.cc` line 106 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2qwt6A5HYJFTjC09OG:-N2rbkw70doNbBNKvFRG:b-lg3qd4) ([raw file](https://github.com/robotlocomotion/drake/blob/3059502c72d6cb21617c6e7109a6afa266273248/multibody/parsing/detail_sdf_geometry.cc#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Neither does Drake support `heightmap` (#17257) but we still list that here as well.  My guess is that the diagnostic for "not supported" will end up in the caller of this function, instead of here directly.  Mostly for now, I'm just looking for consistency, so matching `GeometryType::HEIGHTMAP` at least keeps everything easy to clean up later, one way or another.
</blockquote></details>

Sounds good. Added "polyline" and a test in `detail_sdf_geometry_test`

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 2 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @azeey)

___
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 71 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rceyRBeE7L0jKCA2u:-N2rceyRBeE7L0jKCA2v:b-1dfg2d) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/multibody/parsing/test/detail_sdf_geometry_test.cc#L71)):*
> ```cpp
>   sdf::SDFPtr result(new sdf::SDF());
>   sdf::ParserConfig config = MakeStrictConfig();
>   sdf::init(result, config);
> ```

This seems a little suspicious.  Previously we loaded the schema outline using the default configuration.  Now, we're using the _test's_ configuration even while loading the schema outline?  That seems wrong -- I would have thought that the test config should only be used for the _test's_ data, not the `sdformat/sdf/1.9/*.sdf` schema data?  Maybe I'm misunderstanding?
___
*[`tools/workspace/sdformat/patches/deprecation_unit_testing.patch` line 8 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2r_aMm16d-ngVEcmzS:-N2r_aMm16d-ngVEcmzT:bkrmh7v) ([raw file](https://github.com/robotlocomotion/drake/blob/a5d317c519ae0378b33b5ff90622b1b78d815780/tools/workspace/sdformat/patches/deprecation_unit_testing.patch#L8)):*
> ```Diff
> definition that will always be available.
> 
> --- src/parser.cc.orig	2022-04-07 11:39:06.881088965 -0500
> ```

nit I'm not sure where this timestamp is coming from?  If we're not going to reflect the mtime of the upstream 12.5.0 copy of this file in the "orig" timestamp here (`2022-04-04 11:35:34 -0700`), then we might as well elide both timestamps entirely (since they are noise in that case).  That's probably easier than trying to keep this timestamp correctly maintained as we upgrade.
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 7 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rbQp7BWffDWfWyyFZ:-N2rbQp7BWffDWfWyyF_:b-xk5vgb) ([raw file](https://github.com/robotlocomotion/drake/blob/a5d317c519ae0378b33b5ff90622b1b78d815780/tools/workspace/sdformat/patches/no_global_config.patch#L7)):*
> ```Diff
> 
> diff --git src/ParserConfig.cc src/ParserConfig.cc
> index 77de4e9e..3a73846e 100644
> ```

nit The "diff" and "index" seem to be line noise, and so should be removed from source control.  Ditto throughout this file.
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 29 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rc89N0bZYk2nz6kqT:-N2rc89N0bZYk2nz6kqU:b-mt2gap) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/tools/workspace/sdformat/patches/no_global_config.patch#L29)):*
> ```Diff
>    SDFPtr sdfParsed(new SDF());
> -  init(sdfParsed);
> +  init(sdfParsed, _config);
> ```

This seems a little suspicious.  Previously we loaded the schema outline using the default configuration.  Now, we're using the _user's_ configuration even while loading the schema outline?  That seems wrong -- I would have thought that the user-config should only be used for the _user's_ data, not the `sdformat/sdf/1.9/*.sdf` schema data?  Maybe I'm misunderstanding?

**Comment by azeey** [comment]
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 71 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rceyRBeE7L0jKCA2u:-N2rkiH5E1z37nkdw35e:b-7q4ug) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/multibody/parsing/test/detail_sdf_geometry_test.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems a little suspicious.  Previously we loaded the schema outline using the default configuration.  Now, we're using the _test's_ configuration even while loading the schema outline?  That seems wrong -- I would have thought that the test config should only be used for the _test's_ data, not the `sdformat/sdf/1.9/*.sdf` schema data?  Maybe I'm misunderstanding?
</blockquote></details>

A new signature of `sdf::init` that takes a `ParserConfig` was added in libsdformat 12.4.0. The original `sdf::init` now calls the new one with a `GlobalConfig()`. The intention is for end users that provide their own schema files to be able to configure file lookup through `ParserConfig`, just like what's done for regular SDFormat files. However, the ability to provide custom schema files is not supported when using `sdf::Root` and related classes (what we call DOM classes), so those classes don't need to forward their `ParserConfig` objects, which is why the patch to `sdf::Root::LoadSdfString` was necessary.

This could instead be `sdf::init(result, sdf::ParserConfig{})`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @azeey)

___
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 71 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rceyRBeE7L0jKCA2u:-N2roFy3-xXmaUAZ3y8m:b-7vhy7l) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/multibody/parsing/test/detail_sdf_geometry_test.cc#L71)):*
> This could instead be `sdf::init(result, sdf::ParserConfig{})`.

That seems more in line with prior behavior, and actually a better match for what the drake `Parser` class is doing anyway?  Seems better to me, but I'm open to other suggestions.

**Comment by azeey** [comment]
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 71 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rceyRBeE7L0jKCA2u:-N2rzP3u4kWFhD1HrPi2:b-4ywpla) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/multibody/parsing/test/detail_sdf_geometry_test.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> This could instead be `sdf::init(result, sdf::ParserConfig{})`.

That seems more in line with prior behavior, and actually a better match for what the drake `Parser` class is doing anyway?  Seems better to me, but I'm open to other suggestions.
</blockquote></details>

Will do. I would, however, suggest migrating to the newer and currently recommended API of `sdf::Root::LoadString` instead of a combination of `sdf::init` and `sdf::readString`.

**Comment by azeey** [comment]
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 7 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rbQp7BWffDWfWyyFZ:-N2s-mekCdqOHzIeeBQB:bggw956) ([raw file](https://github.com/robotlocomotion/drake/blob/a5d317c519ae0378b33b5ff90622b1b78d815780/tools/workspace/sdformat/patches/no_global_config.patch#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The "diff" and "index" seem to be line noise, and so should be removed from source control.  Ditto throughout this file.
</blockquote></details>

Will do. I generated this using `git diff`. Is there an easier way to create the patch in the same format as the patch in `master`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @azeey)

___
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 71 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rceyRBeE7L0jKCA2u:-N2s-mXQBnN0Ayrh52Hr:b8jma20) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/multibody/parsing/test/detail_sdf_geometry_test.cc#L71)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Will do. I would, however, suggest migrating to the newer and currently recommended API of `sdf::Root::LoadString` instead of a combination of `sdf::init` and `sdf::readString`.
</blockquote></details>

TODO to that effect would be fine.
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 7 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rbQp7BWffDWfWyyFZ:-N2s0E3o9DBi_yujk2IW:bl7ncm2) ([raw file](https://github.com/robotlocomotion/drake/blob/a5d317c519ae0378b33b5ff90622b1b78d815780/tools/workspace/sdformat/patches/no_global_config.patch#L7)):*
<details><summary><i>Previously, azeey (Addisu Z. Taddese) wrote…</i></summary><blockquote>

Will do. I generated this using `git diff`. Is there an easier way to create the patch in the same format as the patch in `master`?
</blockquote></details>

I believe I just used `diff -u`, but that has timestamps which maybe we don't actually want.  A little manual clean-up of the diff output in order to put into this patch file is fine by me.

**Review by azeey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`multibody/parsing/test/detail_sdf_geometry_test.cc` line 71 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rceyRBeE7L0jKCA2u:-N2s4dMM616iUuILuKg-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/multibody/parsing/test/detail_sdf_geometry_test.cc#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

TODO to that effect would be fine.
</blockquote></details>

Done.
___
*[`tools/workspace/sdformat/patches/deprecation_unit_testing.patch` line 8 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2r_aMm16d-ngVEcmzS:-N2s4fdw2bdaFa1ZAdOV:b9x56q5) ([raw file](https://github.com/robotlocomotion/drake/blob/a5d317c519ae0378b33b5ff90622b1b78d815780/tools/workspace/sdformat/patches/deprecation_unit_testing.patch#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure where this timestamp is coming from?  If we're not going to reflect the mtime of the upstream 12.5.0 copy of this file in the "orig" timestamp here (`2022-04-04 11:35:34 -0700`), then we might as well elide both timestamps entirely (since they are noise in that case).  That's probably easier than trying to keep this timestamp correctly maintained as we upgrade.
</blockquote></details>

OK, removed the timestamps.
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 7 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rbQp7BWffDWfWyyFZ:-N2s4nv91yFssHjQHBeZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a5d317c519ae0378b33b5ff90622b1b78d815780/tools/workspace/sdformat/patches/no_global_config.patch#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I believe I just used `diff -u`, but that has timestamps which maybe we don't actually want.  A little manual clean-up of the diff output in order to put into this patch file is fine by me.
</blockquote></details>

Done.
___
*[`tools/workspace/sdformat/patches/no_global_config.patch` line 29 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17250#-N2rc89N0bZYk2nz6kqT:-N2s4rzh1OVFxIl2PYfh:b-ajjpoi) ([raw file](https://github.com/robotlocomotion/drake/blob/af45faace083b24794af89d0e15f03afb1b719da/tools/workspace/sdformat/patches/no_global_config.patch#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems a little suspicious.  Previously we loaded the schema outline using the default configuration.  Now, we're using the _user's_ configuration even while loading the schema outline?  That seems wrong -- I would have thought that the user-config should only be used for the _user's_ data, not the `sdformat/sdf/1.9/*.sdf` schema data?  Maybe I'm misunderstanding?
</blockquote></details>

Done. Now uses `ParserConfig{}` instead.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17250#-:-N2sN5by2uFNo91HEbz8:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @azeey)

**Pull request merged**
