### PR TITLE
[tools] On macOS add /usr/sbin and /sbin to $PATH

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Some font hunting stuff inside matplotlib needs `/usr/sbin/system_profiler`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21465)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please

**Review by ggould-tri — COMMENTED** [review]
+@ggould-tri :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21465#-:-NyQlNbA7A_pABFWWjej:b2k9fdi)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21465)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21465#-NyRQXwK4tuKJplrc8a_:-NyRQXwK4tuKJplrc8aa:b-2a8zyz) (no related file):*
BTW:  Reviewable is showing the status green circle as randomly varying fractions of green every time I reload.   I'm going to assume that it's just confused, not trying to communicate, and punch merge on this shortly regardlesss.

___

**Comment by jwnimmer-tri** [comment]
Yup, CI is happy.  Merged now.

**Pull request merged**
