### PR TITLE
Add valkyrie IK test

### PR DESCRIPTION
**Pull request by pangtao22**
continued from #4009 .
@hongkai-dai for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4030)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KVl8uZFhW8VSG3HGM5k:-KVl8uZFhW8VSG3HGM5l:b6060bq) ([raw file](https://github.com/robotlocomotion/drake/blob/a8594cd7d4b9cda319bb249f85a4fc32f1000c06/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L140)):*
> ```cpp
>   // Position and quaternion constraints are relaxed to make the problem
>   // solvable by IPOPT.
>   lfoot_pos_lb(0) -= 0.0001;
> ```

You could write this as
```
lfoot_pos_lb -= 0.0001*Vector4d::Ones()
```

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KVl9KqDkE1yFrQ7ATWY:-KVl9KqDkE1yFrQ7ATWZ:b-e43u2g) ([raw file](https://github.com/robotlocomotion/drake/blob/a8594cd7d4b9cda319bb249f85a4fc32f1000c06/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L174)):*
> ```cpp
>   FindJointAndInsert(tree.get(), "torsoPitch", &torso_idx);
>   FindJointAndInsert(tree.get(), "torsoRoll", &torso_idx);
>   Vector3d torso_nominal = Vector3d::Zero(3);
> ```

You do not need to add `3` there, it could be
```
Vector3d::Zero();
```

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KVl9ZRJc2KZv8RfSwlV:-KVl9ZRJc2KZv8RfSwlW:b-do8rls) ([raw file](https://github.com/robotlocomotion/drake/blob/a8594cd7d4b9cda319bb249f85a4fc32f1000c06/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L189)):*
> ```cpp
>   Vector2d knee_lb = knee_nominal;
>   Vector2d knee_ub = knee_nominal;
>   knee_ub(0) += 108.9 / 180 * M_PI;
> ```

What is the joint limit for the knee? I think it is more likely this knee_ub is computed from the joint limit of the knee, not from knee_nominal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030)*

**Comment by pangtao22** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KVl9ZRJc2KZv8RfSwlV:-KVlGsYgI1-jSJICIQ6S:b1bzg34) ([raw file](https://github.com/robotlocomotion/drake/blob/a8594cd7d4b9cda319bb249f85a4fc32f1000c06/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L189)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> What is the joint limit for the knee? I think it is more likely this knee_ub is computed from the joint limit of the knee, not from knee_nominal.
</details>
Joint limits found in URDF file are used instead. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review, +@sherm1 for platform review.
@pangtao22 , you will need to add a plus sign, and then @ one of us as the feature or platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KVmJ6HfyCwjfypJfQFF:b3qr4yh)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KVmJOCXMXUm2UEOLogE:bnfp4nl)*

**Comment by sherm1** [comment]
Platform review: a few minor comments, PTAL.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3wRgTG5MnUD-XfWqA:-KW3wRgTG5MnUD-XfWqB:b-c40ygr) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L4)):*
> ```cpp
> // visualizer.
> 
> #include <iostream>
> ```

Should `#include <numeric>` for `std::iota`.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3wZSAsQRswyNVsnV8:-KW3wZSAsQRswyNVsnV9:b2pa41m) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L48)):*
> ```cpp
>   // sequentially increasing indices starting at
>   // `joint_child_body->get_position_start_index()`.
>   iota(ret.begin(), ret.end(), joint_child_body->get_position_start_index());
> ```

Should be `std::iota`. Not sure where it's finding this one.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3vPZhIAyIZ8yjOQqg:-KW3vPZhIAyIZ8yjOQqh:b8yb0sz) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L64)):*
> ```cpp
> }
> 
> GTEST_TEST(ValkyrieIK__Test, ValkyrieIK__Test_StandingPose_Test) {
> ```

Double underscores in variable names are forbidden by the C++ standard (reserved for the implementation). Please don't use them.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3x2PB_eEG5r8Qu4d2:-KW3x2PB_eEG5r8Qu4d3:b-g5ttwy) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L89)):*
> ```cpp
>       0.0,             // 9 lowerNeckPitch
>       // 0.0,                  // 10 neckYaw
>       // 0.0,                  // 11 upperNeckPitch
> ```

BTW, with these commented out aren't all the indices afterwards wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KW3yDZ_q6bikTX922Cn:b6yqrpb)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by pangtao22** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3wRgTG5MnUD-XfWqA:-KWDqUpVDhn_wjTsU0U1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should `#include <numeric>` for `std::iota`.
</details>
Done.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3wZSAsQRswyNVsnV8:-KWDqXFctjktWZtjbMpw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should be `std::iota`. Not sure where it's finding this one.
</details>
Done.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3vPZhIAyIZ8yjOQqg:-KWDs08ti5yOvdkk0h4a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Double underscores in variable names are forbidden by the C++ standard (reserved for the implementation). Please don't use them.
</details>
Done.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3x2PB_eEG5r8Qu4d2:-KWDs6gcYi-RszsheU0a:b-tjlzx6) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, with these commented out aren't all the indices afterwards wrong?
</details>
There are two versions of Valkyrie models I am working with. The one in Drake has two DOFs less (the two commented out) than the other. The indices in the comment are for reference only and are not hard coded in the code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030)*

**Comment by sherm1** [comment]
I see "Done"s but no changes -- did you forget to push new commits to your branch?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KWDxE_ZauPNEe55MbRn:b-79ovpm)*

**Comment by pangtao22** [comment]
Sorry, I had to make a few other changes because of Drake API changes. Next time I'll publish comments only after pushing a working commit. Thank you!

---

Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KWE6m6vSPhzOVX5Bmyf:bjvyndm)*

**Comment by sherm1** [comment]
One non-blocking comment (please address though). Then :lgtm:.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3x2PB_eEG5r8Qu4d2:-KWGnJtY5hcTOw5BQTyN:bqrp59p) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L89)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary>
> There are two versions of Valkyrie models I am working with. The one in Drake has two DOFs less (the two commented out) than the other. The indices in the comment are for reference only and are not hard coded in the code. 
</details>
Please add a comment like your response here so that the next reader of the code won't have to wonder about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KWGnVgzKRhl3qnux_Jv:b-10nmiw)*

**Comment by pangtao22** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/examples/Valkyrie/test/valkyrie_IK_test.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-KW3x2PB_eEG5r8Qu4d2:-KWJ2IDkfL1XlT2NrLr6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/918608318f8c1fad506b4e9fc1e863ef9a47ee6e/drake/examples/Valkyrie/test/valkyrie_IK_test.cc#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Please add a comment like your response here so that the next reader of the code won't have to wonder about that.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030)*

**Comment by sherm1** [comment]
:lgtm: - ready to merge when CI finishes.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KWJ93VPNgLmF-Om-oWd:b-froc8l)*

**Comment by jwnimmer-tri** [comment]
Did we nerf the cppguide rules for Valkyrie?  I don't see a README.md about it yet.  If not, then the filename with uppercase `IK` is not allowed.  All filenames must be lowercase.

**Comment by pangtao22** [comment]
Done! File name changed to lowercase. 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4030#-:-KWJl64uTs6jr_8gJJNs:bx5iazl)*

**Comment by hongkai-dai** [comment]
Yeah for @pangtao22 first PR!

**Pull request merged**
