### PR TITLE
Add lcm-python support and use in automotive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
With this PR, the automotive keyboard UI runs:
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro/drake/automotive$ bazel run :steering_command_driver 
INFO:** Found 1 target...
Target //drake/automotive:steering_command_driver up-to-date:
  bazel-bin/drake/automotive/steering_command_driver
INFO: Elapsed time: 0.131s, Critical Path: 0.00s
INFO: Running command line: bazel-bin/drake/automotive/steering_command_driver
cannot find DRAKE_DIST_BUILD_DIR at /home/jwnimmer/jwnimmer-tri/drake-distro/build
Initializing...
--- Keyboard Control Instruction --- 
To increase the throttle/brake: press and hold the Up/Down Arrow
To decrease the throttle/brake: release the Up/Down Arrow
To keep the the current throttle/brake: press the Space Bar
To increase left/right steering: press the Left/Right Arrow
------------------------------------ 
Ready
```

The full demo launcher doesn't run yet (future PR).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4571)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@david-german-tri feature, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-:-KZXWtwBwGPVcgDxLZTe:b23dkqr)*

**Comment by jwnimmer-tri** [comment]
*[tools/lcm.bzl, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXX3OQCkvWtKzlmuwI:-KZXX3OQCkvWtKzlmuwJ:bwy3khq) ([raw file](https://github.com/robotlocomotion/drake/blob/d97c071015e33e49fbb6ac27148fb6b95efc170d/tools/lcm.bzl#L130)):*
> ```Python
>     sources.  The lcm_package= string parameter must match the `package ...;`
>     statement in all of the `*.lcm` files in lcm_srcs.  The Bazel-standard
>     deps= and imports= parameters are passed through to cc_library after
> ```

Typo `cc_library` should be `py_library`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/lcm.BUILD, line 117 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXguFAvev3JU8bJGHS:-KZXguFAvev3JU8bJGHT:b-g1evb) ([raw file](https://github.com/robotlocomotion/drake/blob/96049f7992c4bc7d7301077fc92306a08c74c20a/tools/lcm.BUILD#L117)):*
> ```
> )
> 
> # Downstream users of lcm-python expect to say "import lcm".  However, in the
> ```

BTW, wow, this is an unfortunate pileup of problems.

---

*[tools/lcm.bzl, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXgBCh-HOHbn8M3WmX:-KZXgBCi9MExLDnsCFJ6:b-4m0nj3) ([raw file](https://github.com/robotlocomotion/drake/blob/96049f7992c4bc7d7301077fc92306a08c74c20a/tools/lcm.bzl#L90)):*
> ```Python
>         fail("lcm_srcs must be provided")
> 
>     # Note that only C++ codegen is supported for now.  If desired in the
> ```

This is now untrue, right?

---

*[tools/lcm.bzl, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXctQJKEW4RxBL9NSY:-KZXctQKGzwoni_zMiIg:b-10xz2w) ([raw file](https://github.com/robotlocomotion/drake/blob/96049f7992c4bc7d7301077fc92306a08c74c20a/tools/lcm.bzl#L127)):*
> ```Python
>         **kwargs):
>     """Declares a py_library target based on python message classes generated
>     from `*.lcm` files.  The lcm_src= list parameter specifies the `*.lcm`
> ```

BTW `lcm_srcs`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-:-KZXhGUwg-xZkLI4ZuAf:bnfp4nl)*

**Comment by david-german-tri** [comment]
> @drake-jenkins-bot linux-gcc-bazel-experimental please
> @drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-:-KZXiXjBxYNeN50oWG47:b-om31y1)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/lcm.bzl, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXgBCh-HOHbn8M3WmX:-KZXiGts6HVzazVgWzXR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96049f7992c4bc7d7301077fc92306a08c74c20a/tools/lcm.bzl#L90)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This is now untrue, right?
</blockquote></details>

Done.

---

*[tools/lcm.bzl, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXctQJKEW4RxBL9NSY:-KZXiKitwdBfkI31I45u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/96049f7992c4bc7d7301077fc92306a08c74c20a/tools/lcm.bzl#L127)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW `lcm_srcs`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-:-KZXiNzx_zW5e1KYQVHU:bz1t39v)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by sammy-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/drake_paths.py, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXtRlzt_uyauiFQ10K:-KZXtRlzt_uyauiFQ10L:b49x9wt) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6a9664894d8110cffdc5bce7812feb61640da4/drake/automotive/drake_paths.py#L19)):*
> ```Python
> 
> if not os.path.exists(DRAKE_INSTALL_BIN_DIR):
>     print >>sys.stderr, (
> ```

Is it actually OK for this to become non-fatal when it's used in the next few lines of code?  I think it's probably at least work a comment to explain why we want to keep going.

---

*[tools/lcm.bzl, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXsbHdbgc4bbKX2D0m:-KZXsbHex-RHn868QuE4:b-g3ddrc) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6a9664894d8110cffdc5bce7812feb61640da4/tools/lcm.bzl#L10)):*
> ```Python
> 
> def _lcm_srcs_to_outs(lcm_package, lcm_srcs, extension):
>     """Return the list of filenames (prefixed by the package directory and switched
> ```

BTW long line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/drake_paths.py, line 19 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXtRlzt_uyauiFQ10K:-KZXv3vjW4ZfnftHSAlV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6a9664894d8110cffdc5bce7812feb61640da4/drake/automotive/drake_paths.py#L19)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is it actually OK for this to become non-fatal when it's used in the next few lines of code?  I think it's probably at least work a comment to explain why we want to keep going.
</blockquote></details>

Done.

---

*[tools/lcm.bzl, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-KZXsbHdbgc4bbKX2D0m:-KZXv2jUWT_9-RPlWaen:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d6a9664894d8110cffdc5bce7812feb61640da4/tools/lcm.bzl#L10)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW long line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4571#-:-KZXzG0EfYh4UzngqKQG:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Using override-merge; only outstanding build is MATLAB.

**Pull request merged**
