### PR TITLE
MBT Jacobian tests

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR moves the Jacobian tests originally in `multibody/benchmarks/kuka_iiwa_robot/` to `multibody_tree_test.cc`. 
Those unit tests will expand to include other Jacobian computations.

This replaces #7947.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8009)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@siyuanfeng-tri for feature review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-:-L4rIXjzEwMwqECmPFVD:bakb6i6)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 
i had some minor comments. 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/multibody_tree.h, line 888 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-L4sMj2IE-TtsrDUWFsv:-L4sMj2IE-TtsrDUWFsw:b-ulat5z) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/multibody_tree.h#L888)):*
> ```objc
>   ///   **must** be in `ℝ³ˣⁿᵖ`.
>   ///
>   /// @note Both `p_BQi` and `p_AQi` must have three rows. Otherwise this
> ```

BTW the throw section is different from #7947, not sure which version you want to use. 

---

*[multibody/multibody_tree/multibody_tree.h, line 904 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-L4sMz574YD-hfn8-dWq:-L4sMz574YD-hfn8-dWr:b-v0id87) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/multibody_tree.h#L904)):*
> ```objc
>   /// @{
> 
>   /// Given a set of points `Qi` with fixed position vectors `p_BQi` in a frame
> ```

BTW i like the docs in 7947 better, not sure which one you want to keep. also Jv.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 194 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-L4sO5zO3gPLLGbkRYBv:-L4sO5zO3gPLLGbkRYBw:bb6ykz6) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L194)):*
> ```cpp
>       const Context<T>& context_on_T,
>       const MatrixX<T>& p_EPi,
>       MatrixX<T>* p_WPi, MatrixX<T>* J_WPi) const {
> ```

Jv? 

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 350 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-L4sPH862ndx9vRrI_ep:-L4sPH862ndx9vRrI_eq:bb6y9ur) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L350)):*
> ```cpp
> 
> // Given a set of points Pi attached to the end effector frame G, this test
> // computes the analytic Jacobian J_WPi of these points using two methods:
> ```

Jg? 

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 388 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-L4sPidHC6CbqgPQpcV4:-L4sPidHC6CbqgPQpcV5:bb6ykz6) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L388)):*
> ```cpp
> 
>   MatrixX<double> p_WPi(3, kNumPoints);
>   MatrixX<double> J_WPi(3 * kNumPoints, kNumPositions);
> ```

Jv? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8009#-:-L4sQLnt-6b2DZjXJU8x:bas49km)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.h, line 888 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L4sMj2IE-TtsrDUWFsv:-L4vK5t2s_Yn28ThYBir:b-w1xt55) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/multibody_tree.h#L888)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW the throw section is different from #7947, not sure which version you want to use. 
</blockquote></details>

BTW Yes, the contract changed so slightly. This method is now a user facing API and so I throw if something is wrong.

---

*[multibody/multibody_tree/multibody_tree.h, line 904 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L4sMz574YD-hfn8-dWq:-L4vLMvw_RZp9F6t13qh:bmrxu) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/multibody_tree.h#L904)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i like the docs in 7947 better, not sure which one you want to keep. also Jv.
</blockquote></details>

BTW I agree, that one was better. The only change is that now I throw if sizes are wrong. I can provide another API taking `MarixX<T>*` if needed which would resize matrices if they are not the right size.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 194 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L4sO5zO3gPLLGbkRYBv:-L4vM7HcADS0YjI7P4PF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L194)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Jv? 
</blockquote></details>

Done.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 350 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L4sPH862ndx9vRrI_ep:-L4vMIBbwBmfB0YRIo0Z:bp5kcpp) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L350)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Jg? 
</blockquote></details>

Didn't we agree on `Jq` on Slack? the convention being that the "sub-index" indicates the variable used in the derivative (not quite since Jv is not a real Jacobian, but you get what I mean)

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 388 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L4sPidHC6CbqgPQpcV4:-L4vMyX97sGsPRvo8M2z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L388)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Jv? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8009)*

**Comment by amcastro-tri** [comment]
+@sherm1 for platform please.

---

Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-:-L4vR3X7GumYLYb98zPU:b-af1gxe)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 350 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L4sPH862ndx9vRrI_ep:-L4yl5EMiNwFnya4Pl_J:bov391a) ([raw file](https://github.com/robotlocomotion/drake/blob/c7a5e5fbc79a9309e7ac7ce70e8708349d044317/multibody/multibody_tree/test/multibody_tree_test.cc#L350)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Didn't we agree on `Jq` on Slack? the convention being that the "sub-index" indicates the variable used in the derivative (not quite since Jv is not a real Jacobian, but you get what I mean)
</blockquote></details>

opps, i meant Jq. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8009)*

**Comment by sherm1** [comment]
:lgtm: with a few BTWs ...

---

Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.h, line 861 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A6g9qKHUn-UR35xXn:-L5A6g9rBCJxZIUFPCUA:b-dtt37b) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/multibody_tree.h#L861)):*
> ```objc
>   Isometry3<T> CalcRelativeTransform(
>       const systems::Context<T>& context,
>       const Frame<T>& to_frame_A, const Frame<T>& from_frame_B) const;
> ```

BTW consider just calling these `frame_A` and `frame_B`. I can see why the `to` and `from` are here, but I'm not sure that adds anything since the definitions above are unambiguous. The reason not to do it would be that the to/from idea is ambiguous in other contexts and maybe we don't want to encourage its use anywhere? There are more instances below, some with to/from and some without.

---

*[multibody/multibody_tree/multibody_tree.h, line 955 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A7cZI3vKPPaKrh7ha:-L5A7cZI3vKPPaKrh7hb:b-4rbj3) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/multibody_tree.h#L955)):*
> ```objc
>   /// @throws an exception if `Jv_WQi` is nullptr or if it does not have the
>   /// appropriate size, see documentation for `Jv_WQi` for details.
>   void CalcPointsGeometricJacobianExpressedInWorld(
> ```

BTW consider adding an `@note` that applying a Jacobian in operator form can be a lot cheaper that generating this matrix, especially if there are a lot of points. For one or two points it is probably a wash.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 166 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A8eAgWZdSPJsMHn8s:-L5A8eAgWZdSPJsMHn8t:b-o4ax5f) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/test/multibody_tree_test.cc#L166)):*
> ```cpp
>       const Context<T>& context_on_T) const {
>     std::vector<SpatialVelocity<T>> V_WB_array;
>     model_on_T.CalcAllBodySpatialVelocitiesInWorld(context_on_T, &V_WB_array);
> ```

BTW this seems an expensive way to get the velocity of one body! I guess it would be fine with Eval though -- generally they all have to be calculated at once.  The extra expense here is just the copy out to the V array.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 351 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A9QaiU7WmD8uDSF_9:-L5A9QaiU7WmD8uDSF_A:b88lwp9) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/test/multibody_tree_test.cc#L351)):*
> ```cpp
> // Given a set of points Pi attached to the end effector frame G, this test
> // computes the analytic Jacobian Jq_WPi of these points using two methods:
> // 1. Since for the Kuka iiwa arm v = q̇, the analytic Jacobian equals the
> ```

BTW would be nice to have a test somewhere for v != q̇.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-:-L5A9YjhyT7AncjDmbCa:b-inpauq)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree.h, line 955 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A7cZI3vKPPaKrh7ha:-L5ByqfgtKvwJogQMFWk:buigw8o) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/multibody_tree.h#L955)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding an `@note` that applying a Jacobian in operator form can be a lot cheaper that generating this matrix, especially if there are a lot of points. For one or two points it is probably a wash.
</blockquote></details>

BTW. I will when we have the operator form and I'll add a reference to it here.

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 166 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A8eAgWZdSPJsMHn8s:-L5Bz5EkIyDdCVo2hDif:bfyr2jc) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/test/multibody_tree_test.cc#L166)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems an expensive way to get the velocity of one body! I guess it would be fine with Eval though -- generally they all have to be calculated at once.  The extra expense here is just the copy out to the V array.
</blockquote></details>

BTW. This is just a unit test though and we don't have caching to refine on the API yet. 

---

*[multibody/multibody_tree/test/multibody_tree_test.cc, line 351 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8009#-L5A9QaiU7WmD8uDSF_9:-L5BzET_Hi5OFxItPxIE:b-644fnv) ([raw file](https://github.com/robotlocomotion/drake/blob/0458c80e8f2ec86f810edbd4fe09161ff7362847/multibody/multibody_tree/test/multibody_tree_test.cc#L351)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would be nice to have a test somewhere for v != q̇.
</blockquote></details>

BTW. That'd be great, yes. I have floating mobilizers in my dev branch. I'll try pushing those after my visit to HQ.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8009)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8009)*

**Pull request merged**
