### PR TITLE
[multibody] Adjust test tolerances for mac arm64

### PR DESCRIPTION
**Pull request by RussTedrake**
+@sherm1 for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17204)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please

When fixing test tolerances for M1, we should run a CI build to make sure that the tests changed by this PR actually passing now.  (Other, unrelated tests may still be expected to fail.)

Here are the links to the test failures from the prior nightly build:
- https://drake-cdash.csail.mit.edu/test/730818968
- https://drake-cdash.csail.mit.edu/test/730817307
- https://drake-cdash.csail.mit.edu/test/730817370

---

@drake-jenkins-bot  linux-focal-clang-bazel-experimental-leak-sanitizer please

Seems like a spurious timeout from the first push.

**Comment by RussTedrake** [comment]
Towards #17009

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please.

**Comment by RussTedrake** [comment]
To be clear, the M1 CI tests are not expected to pass.  A summary of the failures is in #17009.  If the feature review can just focus on the code change, I can work with platform to get the M1 CI correct.

**Review by sherm1 — COMMENTED** [review]
All these look very reasonable. Feature :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17204#-:-N2FPFJo50mSAH5Qz7Tu:b3d2hcg)* status: needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17204#-:-N2FPQHj6-DTLVJRxiTk:b-64fgp2)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: whitespace grumble

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17204#-:-N2HyQaS4UxImfXA0DEY:b-5f3sqk)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`multibody/fem/test/corotated_model_data_test.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17204#-N2Hy-5T4QqA_wGqyNuA:-N2Hy-5T4QqA_wGqyNuB:bsgm1q9) ([raw file](https://github.com/robotlocomotion/drake/blob/5ab1f9bc475e333f257f5dad0b1e609c2b7e39a3/multibody/fem/test/corotated_model_data_test.cc#L64)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(corotated_model_data.R()[0], R, kTol));
>   EXPECT_TRUE(CompareMatrices(corotated_model_data.S()[0], S, kTol));
>   EXPECT_NEAR(corotated_model_data.Jm1()[0], S.determinant() - 1.0, 10*kTol);
> ```

nit I'm a bit surprised our style checkers don't complain about the lack of whitespace surrounding `*`.

(Oh, nevermind, probably an entire c++ front-end parse would be necessary to detect that.)

**Comment by jwnimmer-tri** [comment]
*[`multibody/fem/test/corotated_model_data_test.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17204#-N2Hy-5T4QqA_wGqyNuA:-N2HzUPU4xJ8OoWkcbOR:b-v30e0i) ([raw file](https://github.com/robotlocomotion/drake/blob/5ab1f9bc475e333f257f5dad0b1e609c2b7e39a3/multibody/fem/test/corotated_model_data_test.cc#L64)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit I'm a bit surprised our style checkers don't complain about the lack of whitespace surrounding `*`.

(Oh, nevermind, probably an entire c++ front-end parse would be necessary to detect that.)
</blockquote></details>

That's actually allowed by GSG.

https://drake.mit.edu/styleguide/cppguide.html#Horizontal_Whitespace

"OK to remove spaces around factors"

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17204)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @RussTedrake)

___
*[`multibody/fem/test/corotated_model_data_test.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17204#-N2Hy-5T4QqA_wGqyNuA:-N2HzUUa5AkPGV51-kK7:bt7r6f) ([raw file](https://github.com/robotlocomotion/drake/blob/5ab1f9bc475e333f257f5dad0b1e609c2b7e39a3/multibody/fem/test/corotated_model_data_test.cc#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That's actually allowed by GSG.

https://drake.mit.edu/styleguide/cppguide.html#Horizontal_Whitespace

"OK to remove spaces around factors"
</blockquote></details>

BTW dang you beat me again, Jeremy! I was just about to post that.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17204)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @RussTedrake)

___
*[`multibody/fem/test/corotated_model_data_test.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17204#-N2Hy-5T4QqA_wGqyNuA:-N2I1ZYkCAvLfLNCnAtC:b-t2rhch) ([raw file](https://github.com/robotlocomotion/drake/blob/5ab1f9bc475e333f257f5dad0b1e609c2b7e39a3/multibody/fem/test/corotated_model_data_test.cc#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW dang you beat me again, Jeremy! I was just about to post that.
</blockquote></details>

huh. TIL

**Pull request merged**
