### PR TITLE
[py systems] Bind System.{AllocateInputVector,AllocateInputAbstract}

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #13581

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18430)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for +(status: single reviewer ok) review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18430#-:-NIymyW8DjBXzNfQfsyq:b-2qt4g2)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18430)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18430#-NJ68M9a7mFUyEJWAnkh):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will do for the sake of progress.

However, is it really proper to block a PR based on doing someone a favor?
Shouldn't you propose this somewhere else?
And is a commit message the best place, or should we encode this in PR overview, where it can be edited?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18430)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18430#-NJ68M9a7mFUyEJWAnkh):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Several thoughts:

I thought I set this to be non-blocking; my status is discussing. If you'd marked yourself as satisifed, the block should have gone away. In fact, Reviewable says as much.

The PR messages don't come through the release management scraper, but the commit messages do. True, if it were in the description, the release engineer could visit the PR and scrape it from there as well. 

Finally, you didn't have to re-push a commit. Just editing the commit message when you merged would've been sufficient.

I'm sorry that you felt the request was onerous. I assure you, I thought I was making the tiniest of requests that shouldn't have slowed this PR in any appreciable way. Clearly, it didn't play out that way and now I need to figure out which of my assumptions was flawed so I don't do it again in the future.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18430)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18430#-NJ68M9a7mFUyEJWAnkh):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Several thoughts:

I thought I set this to be non-blocking; my status is discussing. If you'd marked yourself as satisifed, the block should have gone away. In fact, Reviewable says as much.

The PR messages don't come through the release management scraper, but the commit messages do. True, if it were in the description, the release engineer could visit the PR and scrape it from there as well. 

Finally, you didn't have to re-push a commit. Just editing the commit message when you merged would've been sufficient.

I'm sorry that you felt the request was onerous. I assure you, I thought I was making the tiniest of requests that shouldn't have slowed this PR in any appreciable way. Clearly, it didn't play out that way and now I need to figure out which of my assumptions was flawed so I don't do it again in the future.
</blockquote></details>

Gotcha, all good points! On my part, I should've paid more attention / thought a bit more.
I don't typically pay attention to disposition marker on Reviewable, I pay attention to "nit" or "FYI". Will think about paying closer attention if I think something shouldn't be blocking.
And yeah, derp on not just editing commit message, though a suggestion to that effect would've helped my derpery.

Additionally, I do think you should try to systematize your (very valid and useful) request - have you posted this to Drake `#releases` or `#platform`?

**Comment by EricCousineau-TRI** [comment]
Sweet, sounds great, thanks!

**Comment by EricCousineau-TRI** [comment]
Alas, I think `pydrake.systems.System` was incorrect; it should instead be `pydrake.systems.framework.System`. Perhaps a good data point to have this information be placed outside of the commit, and instead in something else. (perhaps even automated)

FYI @xuchenhan-tri

**Comment by SeanCurtis-TRI** [comment]
Ouch...Alternatively, a good reason to have in the commit so that it's properly *reviewed* and versioned? One can argue either way. One path produces a more rigorous review process the other produces a process less sensitive to error.

**Comment by EricCousineau-TRI** [comment]
I do like turning my brain off as much as possible, so I'd vote for automated route ;) But barring that, yes, more attention to detail would work!

**Comment by jwnimmer-tri** [comment]
=> See https://github.com/RobotLocomotion/drake/pull/18523 for my proposed release process updates.

**Pull request merged**
