### PR TITLE
Extend convex hull computation

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
MakeConvexHull() now
  - supports vtk files
  - handles planar geometry
    - preconditions the data to protect the qhull call.
  - detects and actively calls out degenerate inputs.

Relates to #20618

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@DamrongGuoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-:-NrlX1_7AwvjNlRPkkYj:b-feiw5h)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
Checkpoint.  I'll check the _test.cc next.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-:-NrqN_ko8_CHNZRZXUyB:bumrhds)* status: 3 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.h` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqLln8B7xyS-Jps14H:-NrqLln8B7xyS-Jps14I:b-5owbzw) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.h#L20)):*
> ```objc
>             vertices, co-linear or coincident vertices, etc.)
>  @throws if there is an unforeseen error in computing the convex hull. */
> PolygonSurfaceMesh<double> MakeConvexHull(const Shape& shape);
> ```

BTW, should we add a note that a 2D shape is ok?  Please feel free to change my writing.



_Suggestion:_
```objc
 @throws if there is an unforeseen error in computing the convex hull.
 @note `shape` can be a planar geometry. */
PolygonSurfaceMesh<double> MakeConvexHull(const Shape& shape);
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 205 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqKUD7EULdiwM4ilEI:-NrqKUD80CG4D60Hzc6_:b-vc4y69) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L205)):*
> ```cpp
>       throw std::runtime_error(
>           fmt::format("MakeConvexHull failed because all vertices in the mesh "
>                       "were within a sphere with radius 1e-14 for file: {}.",
> ```

BTW, typo?  sqrt(1e-24) = 1e-12, not 1e-14, and is it radius or diameter?

Alternatively, could we say it without "sphere"?



_Suggestion:_
```cpp
                      "were closer than 1e-12 meters for file: {}.",
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 218 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqFoxw6dAuM5TnX5Rr:-NrqFoxx2tJCKY1xdQli:b-flwdyu) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L218)):*
> ```cpp
>     }
> 
>     if (v == ssize(vertices)) {
> ```

BTW, it took me a long time to convince myself that the `do {} while(_&&_)` and the `while((_||_)&&_){}` are correct.  It's hard for me to read complex boolean expressions and check that the counter `v` iterates correctly.

Would you like to use the standard `for` and `break` to separate each condition, please?

```diff
diff --git a/geometry/proximity/make_convex_hull_mesh.cc b/geometry/proximity/make_convex_hull_mesh.cc
index c3c1d55e5e..2d9f6f2abc 100644
--- a/geometry/proximity/make_convex_hull_mesh.cc
+++ b/geometry/proximity/make_convex_hull_mesh.cc
@@ -195,9 +195,12 @@ class VertexReader final : public ShapeReifier {
     // their mesh.
     int v = 0;
     Vector3d a;
-    do {
-      a = vertices[++v] - vertices[0];
-    } while (a.squaredNorm() < 1e-24 && v < ssize(vertices));
+    for (; v < ssize(vertices); ++v) {
+      a = vertices[v] - vertices[0];
+      if (a.squaredNorm() >= 1e-24) {
+        break;
+      }
+    }
 
     if (v == ssize(vertices)) {
       throw std::runtime_error(
@@ -207,12 +210,13 @@ class VertexReader final : public ShapeReifier {
     }
     a.normalize();
 
-    Vector3d b = vertices[++v] - vertices[0];
-    Vector3d n_candidate = a.cross(b);
-    while ((b.squaredNorm() < 1e-24 || n_candidate.squaredNorm() < 1e-24) &&
-           v < ssize(vertices)) {
-      b = vertices[++v] - vertices[0];
+    Vector3d n_candidate;
+    for (++v; v < ssize(vertices); ++v) {
+      Vector3d b = vertices[v] - vertices[0];
       n_candidate = a.cross(b);
+      if (b.squaredNorm() >= 1e-24 && n_candidate.squaredNorm() >= 1e-24) {
+        break;
+      }
     }
 
     if (v == ssize(vertices)) {
```



_Code quote:_
```cpp
    // their mesh.
    int v = 0;
    Vector3d a;
    do {
      a = vertices[++v] - vertices[0];
    } while (a.squaredNorm() < 1e-24 && v < ssize(vertices));

    if (v == ssize(vertices)) {
      throw std::runtime_error(
          fmt::format("MakeConvexHull failed because all vertices in the mesh "
                      "were within a sphere with radius 1e-14 for file: {}.",
                      filename));
    }
    a.normalize();

    Vector3d b = vertices[++v] - vertices[0];
    Vector3d n_candidate = a.cross(b);
    while ((b.squaredNorm() < 1e-24 || n_candidate.squaredNorm() < 1e-24) &&
           v < ssize(vertices)) {
      b = vertices[++v] - vertices[0];
      n_candidate = a.cross(b);
    }

    if (v == ssize(vertices)) {
```

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-:-NrqdPX5-zWqVwtZPu0J:bnfp4nl)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-Nrqaxhi2bR2Src0wn2K:-Nrqaxhi2bR2Src0wn2L:b-x11h6w) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L122)):*
> ```cpp
>   void ImplementGeometry(const Convex& convex, void* user_data) {
>     ReadVertices(convex.filename(), convex.extension(), convex.scale(),
>                  user_data);
> ```

BTW, kcov said that this function was untested.



_Code quote:_
```cpp
  void ImplementGeometry(const Convex& convex, void* user_data) {
    ReadVertices(convex.filename(), convex.extension(), convex.scale(),
                 user_data);
```
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 280 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqbJ1c0irYtDaX69ls:-NrqbJ1c0irYtDaX69lt:bgp54nm) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L280)):*
> ```cpp
>         fmt::format("MakeConvexHull failed. Qhull terminated with status {} "
>                     "and message:\n{}",
>                     qhull.qhullStatus(), qhull.qhullMessage()));
> ```

BTW, kcov said that these lines were untested.



_Code quote:_
```cpp
    throw std::runtime_error(
        fmt::format("MakeConvexHull failed. Qhull terminated with status {} "
                    "and message:\n{}",
                    qhull.qhullStatus(), qhull.qhullMessage()));
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-:-NrqksHaEK5i4duR1LY3:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 205 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqKUD7EULdiwM4ilEI:-NrqjHJYEdzC3ToxLkNf:blkufc7) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L205)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, typo?  sqrt(1e-24) = 1e-12, not 1e-14, and is it radius or diameter?

Alternatively, could we say it without "sphere"?
</blockquote></details>

Thanks for catching the typo.

I don't think the alternate phrasing is equivalent or necessarily correct. If I have three co-linear points such that vertex 0 is between them and each of the other points lie on opposite sides at the distance of 1e-12 meters, this error will get triggered but saying that **all**vertices are closer than 1e-12 is either imprecise or incorrect. But it's definitively true that I can define a sphere with vertex 0 at the origin and I've shown that all points lie within that sphere.
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 218 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqFoxw6dAuM5TnX5Rr:-NrqkTVc6uWAGK5ueC7M:bt2ce2a) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L218)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, it took me a long time to convince myself that the `do {} while(_&&_)` and the `while((_||_)&&_){}` are correct.  It's hard for me to read complex boolean expressions and check that the counter `v` iterates correctly.

Would you like to use the standard `for` and `break` to separate each condition, please?

```diff
diff --git a/geometry/proximity/make_convex_hull_mesh.cc b/geometry/proximity/make_convex_hull_mesh.cc
index c3c1d55e5e..2d9f6f2abc 100644
--- a/geometry/proximity/make_convex_hull_mesh.cc
+++ b/geometry/proximity/make_convex_hull_mesh.cc
@@ -195,9 +195,12 @@ class VertexReader final : public ShapeReifier {
     // their mesh.
     int v = 0;
     Vector3d a;
-    do {
-      a = vertices[++v] - vertices[0];
-    } while (a.squaredNorm() < 1e-24 && v < ssize(vertices));
+    for (; v < ssize(vertices); ++v) {
+      a = vertices[v] - vertices[0];
+      if (a.squaredNorm() >= 1e-24) {
+        break;
+      }
+    }
 
     if (v == ssize(vertices)) {
       throw std::runtime_error(
@@ -207,12 +210,13 @@ class VertexReader final : public ShapeReifier {
     }
     a.normalize();
 
-    Vector3d b = vertices[++v] - vertices[0];
-    Vector3d n_candidate = a.cross(b);
-    while ((b.squaredNorm() < 1e-24 || n_candidate.squaredNorm() < 1e-24) &&
-           v < ssize(vertices)) {
-      b = vertices[++v] - vertices[0];
+    Vector3d n_candidate;
+    for (++v; v < ssize(vertices); ++v) {
+      Vector3d b = vertices[v] - vertices[0];
       n_candidate = a.cross(b);
+      if (b.squaredNorm() >= 1e-24 && n_candidate.squaredNorm() >= 1e-24) {
+        break;
+      }
     }
 
     if (v == ssize(vertices)) {
```
</blockquote></details>

A fine suggestion. Changed.
___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 280 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqbJ1c0irYtDaX69ls:-NrqkXwg0vKWBESP4aN6:bfhp98y) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L280)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, kcov said that these lines were untested.
</blockquote></details>

And, for now, it'll remain so. But I have put a note in the test indicating we know it's not covered.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_convex_hull_mesh.cc` line 205 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-NrqKUD7EULdiwM4ilEI:-Nrqm1wF-U_b9rCw8KUC:b-ntl03t) ([raw file](https://github.com/RobotLocomotion/drake/blob/9312a89e71cb97691886eb2d2cc35bfab0e4fcca/geometry/proximity/make_convex_hull_mesh.cc#L205)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Thanks for catching the typo.

I don't think the alternate phrasing is equivalent or necessarily correct. If I have three co-linear points such that vertex 0 is between them and each of the other points lie on opposite sides at the distance of 1e-12 meters, this error will get triggered but saying that **all**vertices are closer than 1e-12 is either imprecise or incorrect. But it's definitively true that I can define a sphere with vertex 0 at the origin and I've shown that all points lie within that sphere.
</blockquote></details>

Thanks for the explanation.  I forgot that all distances are measured from vertices[0], not between all pairs of vertices.  The sphere is centered at vertices[0].  It makes sense now.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 296 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-Nrqr4R51tGR3bRNxNWI:-Nrqr4R51tGR3bRNxNWJ:b-bagqyz) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc20eae8334f8933749376a4daa41e7582d86244/geometry/proximity/test/make_convex_hull_mesh_test.cc#L296)):*
> ```cpp
> 
>   MeshesAreEquivalent(dut, expected, 1e-14);
> }
> ```

BTW, I'm afraid calling `Convex(...cube_with_hole.obj)` is misleading. (If, in the future, we demand convexity of a Convex instance, the test will break.)

How about we use both `Convex` and `Mesh` in `MeshIsHull`? The `box.obj` is already convex, so it's qualified to be both `Convex` and `Mesh`.



_Suggestion:_
```cpp
/* This tests the case where the obj is its own convex hull.
   A convex obj is qualified to be either a Mesh or a Convex
   shape. */
GTEST_TEST(MakeConvexHullMeshTest, IsHull) {
  const double scale = 2.0;
  const PolyMesh expected = MakeCube(scale);

  const PolyMesh dut1 = MakeConvexHull(Mesh(
      FindResourceOrThrow("drake/geometry/render/test/meshes/box.obj"), scale));

  MeshesAreEquivalent(dut1, expected, 1e-14);
  
  const PolyMesh dut2 = MakeConvexHull(Convex(
      FindResourceOrThrow("drake/geometry/render/test/meshes/box.obj"), scale));

  MeshesAreEquivalent(dut2, expected, 1e-14);
}

/* A more elaborate non-convex obj - a cube with a hole punched through. */
GTEST_TEST(MakeConvexHullMeshTest, HullIsSubset) {
  const double scale = 2.0;
  const PolyMesh expected = MakeCube(scale);

  const PolyMesh dut = MakeConvexHull(Mesh(
      FindResourceOrThrow("drake/geometry/test/cube_with_hole.obj"), scale));

  MeshesAreEquivalent(dut, expected, 1e-14);
}
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 296 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-Nrqr4R51tGR3bRNxNWI:-Nrqz1aC8Qh2okn6dLDh:b-st2bb1) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc20eae8334f8933749376a4daa41e7582d86244/geometry/proximity/test/make_convex_hull_mesh_test.cc#L296)):*
In this case, I'll say "no". The reason is that I don't agree with your premise:

> If, in the future, we demand convexity of a Convex instance, the test will break.

I don't think we'll *ever* demand that a `Convex` references a mesh that is already convex. What's more likely is we'll stop forcing `Mesh` to use a convex hull under the hood. In that world, `Convex` would mean, use the convex hull of whatever I'm passing you. And `Mesh` would mean, use what I'm referencing literally. I doubt we'll ever *require* the mesh referenced by `Convex` to *be* convex (which we'd then have to validate) when we can simply compute the convex hull ourselves.

So, calling Convex with a mesh that is obviously not convex is a good thing for long term testing stability.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-:-Nrr1Tou2eCXWmviGMEX:bnfp4nl)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/test/make_convex_hull_mesh_test.cc` line 296 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-Nrqr4R51tGR3bRNxNWI:-Nrr43xfBU3TlcZMwNjH:b-ej4nm8) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc20eae8334f8933749376a4daa41e7582d86244/geometry/proximity/test/make_convex_hull_mesh_test.cc#L296)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In this case, I'll say "no". The reason is that I don't agree with your premise:

> If, in the future, we demand convexity of a Convex instance, the test will break.

I don't think we'll *ever* demand that a `Convex` references a mesh that is already convex. What's more likely is we'll stop forcing `Mesh` to use a convex hull under the hood. In that world, `Convex` would mean, use the convex hull of whatever I'm passing you. And `Mesh` would mean, use what I'm referencing literally. I doubt we'll ever *require* the mesh referenced by `Convex` to *be* convex (which we'd then have to validate) when we can simply compute the convex hull ourselves.

So, calling Convex with a mesh that is obviously not convex is a good thing for long term testing stability.
</blockquote></details>

Thank you for the clarification.  I misunderstood the definition of Convex class, then.  I thought Doxygen said it had to be convex.

https://github.com/RobotLocomotion/drake/blob/master/geometry/shape_specification.h#L187
```C++
/** Definition of a *convex* surface mesh.
```
https://github.com/RobotLocomotion/drake/blob/master/geometry/shape_specification.h#L200
```C++
   * We assume that the polyhedron is convex.
```

I'm not against merging this PR.  I'm just confused about what `shape_specification.h` said and what you said _"I don't think we'll _ever_ demand that a `Convex` references a mesh that is already convex."_

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm_strong: 

I'm not sure why Reviewable didn't show my lgtm badge in the list of participants. Do it again.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21066#-:-NrrDOmaAFFLwyBMUmL-:bnww75t)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
This seems like "notes: none", so I've marked as such.  You can go back anytime before the release notes kick off and fix it.

**Pull request merged**
