### PR TITLE
Gurobi Suppressions

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Relevant Build: https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=131618

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6174)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot  linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please

**Pull request closed without merging**
