### PR TITLE
Improve documentation and tests for ComposeWithMovingFrameVelocity().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@russtedrake 
 
PR #18373 resolves issue #18374.

1. The "relative" wording has been removed in favor of "measured in".
2. There is a new test (with sub-proof) that shows that
V_MB_E.ComposeWithMovingFrameVelocity(p_BM_E, V_BM_E) = V_MM_E  = zero.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373#-:-NI-fZGqE0j4pXGeWSAZ:bnhdpz6)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by mitiguy — COMMENTED** [review]
Feature review -@russtedrake 
Feature review +@sherm1   

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373#-:-NIAxrJI5vLVm_u8Fst7:b-q1ahwi)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: thanks!
(feel free to use me as feature or platform)

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373#-:-NICWZ9wD9BDGLwbjDHf:b9q2cue)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Great tests! Platform and/or feature :lgtm: pending a few minor issues

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373#-:-NIDpTrp3ZVjt2Nb418u:b-fc4f5t)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/math/spatial_acceleration.h` line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18373#-NIDkYQADsCgaNcLW9Sd:-NIDkYQB4PAy4_IB1LsS:btevrn2) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1fe7e5a3104b3a3eb1a17bc9825bce9a8ebe7a/multibody/math/spatial_acceleration.h#L190)):*
I couldn't tell from this intro sentence what this method does. For example, it took me a while to guess which frames were the ones associated with `this` and which were describing the moving frame. Given that we removed the frames from the named arguments, it seems odd to introduce them here in the intro. Consider something like (not sure this is exactly correct):
> Compose `this` acceleration (in some frame M) with the relative spatial acceleration of another frame to find that frame's acceleration in M.

(Recall that the first sentence (the "brief") is what users see in Doxygen next to the function names in the compact list. This should be sufficient for them to scan to find likely functions of interest; in general it can't be completely detailed and unambiguous due to space limitations. It just has to be enough to get them to click on the function name to get the longer description.)

Then introduce the rest of the frame symbols in the next sentence for purposes of exposition. The text should be specific about which symbols are `this` and which are the "other" -- don't bury that in the @param descriptions.
___
*[`multibody/math/spatial_velocity.h` line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18373#-NIDoMXu8xASWHLfHQ_l:-NIDoMXu8xASWHLfHQ_m:b-ir67qc) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1fe7e5a3104b3a3eb1a17bc9825bce9a8ebe7a/multibody/math/spatial_velocity.h#L117)):*
> ```objc
>   /// Given a frame C's spatial velocity measured in a frame B, and frame B's
>   /// spatial velocity measured in a frame M, returns frame C's spatial velocity
>   /// measured in frame M.
> ```

Same comment here as for the acceleration version.
___
*[`multibody/math/test/spatial_algebra_test.cc` line 526 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18373#-NIDpMNyADm8uCP3Loxd:-NIDpMNyADm8uCP3Loxe:bvtfaqm) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1fe7e5a3104b3a3eb1a17bc9825bce9a8ebe7a/multibody/math/test/spatial_algebra_test.cc#L526)):*
> ```cpp
>   //      =  ᴹd/dt ᴮᵒ𝐩ᴹᵒ + ᴮ𝛚ᴹ × ᴮᵒ𝐩ᴹᵒ.  Use ᴮᵒ𝐩ᴹᵒ = -ᴹᵒ𝐩ᴮᵒ and ᴮ𝛚ᴹ = -ᴹ𝛚ᴮ
>   //      = -ᴹd/dt ᴹᵒ𝐩ᴮᵒ − ᴹ𝛚ᴮ × ᴮᵒ𝐩ᴹᵒ.  Use ᴹ𝐯ᴮᵒ ≡ ᴹd/dt ᴹᵒ𝐩ᴮᵒ.
>   //      =        -ᴹ𝐯ᴮᵒ − ᴹ𝛚ᴮ × ᴮᵒ𝐩ᴹᵒ
> ```

BTW awesome!

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/math/test/spatial_algebra_test.cc` line 526 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18373#-NIDpMNyADm8uCP3Loxd:-NIE8wdl-nSEzicfCL1Q:bza61gn) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1fe7e5a3104b3a3eb1a17bc9825bce9a8ebe7a/multibody/math/test/spatial_algebra_test.cc#L526)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@sherm1 - btw -- that's exactly the equation from my notes we discussed yesterday.  Everything is consistent.  :-)
</blockquote></details>

Woo hoo!

**Review by mitiguy — COMMENTED** [review]
@sherm1   Please take a look at new wording.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373#-:-NIF0yfAEaRl2sN67ACx:bpw8x5v)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @sherm1)

**Review by mitiguy — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/math/spatial_acceleration.h` line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18373#-NIDkYQADsCgaNcLW9Sd:-NIFCy1sCfkaxQtsbzUT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1fe7e5a3104b3a3eb1a17bc9825bce9a8ebe7a/multibody/math/spatial_acceleration.h#L190)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I couldn't tell from this intro sentence what this method does. For example, it took me a while to guess which frames were the ones associated with `this` and which were describing the moving frame. Given that we removed the frames from the named arguments, it seems odd to introduce them here in the intro. Consider something like (not sure this is exactly correct):
> Compose `this` acceleration (in some frame M) with the relative spatial acceleration of another frame to find that frame's acceleration in M.

(Recall that the first sentence (the "brief") is what users see in Doxygen next to the function names in the compact list. This should be sufficient for them to scan to find likely functions of interest; in general it can't be completely detailed and unambiguous due to space limitations. It just has to be enough to get them to click on the function name to get the longer description.)

Then introduce the rest of the frame symbols in the next sentence for purposes of exposition. The text should be specific about which symbols are `this` and which are the "other" -- don't bury that in the @param descriptions.
</blockquote></details>

Done.
___
*[`multibody/math/spatial_velocity.h` line 117 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18373#-NIDoMXu8xASWHLfHQ_l:-NIFCzFY-ARjMIVjCd8O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef1fe7e5a3104b3a3eb1a17bc9825bce9a8ebe7a/multibody/math/spatial_velocity.h#L117)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Same comment here as for the acceleration version.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Beautiful, I love it!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18373#-:-NIFDw0z-Jk-k76ekmNk:btm06xr)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
