### PR TITLE
Enable removing Vertices and Edges from GraphOfConvexSets

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@RussTedrake for feature review or delegation.

**Review by RussTedrake — COMMENTED** [review]
+@russtedrake for feature review.
:lgtm: 
+@sherm1 for platform review tomorrow.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299#-:-MsWQvwg658gHKXkFE56:b-8gurc2)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few minor changes.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299#-:-Msa80q6-bI-45P5DPPh:b-mykmj2)* status: 3 unresolved discussions (waiting on @mpetersen94)

___
*[geometry/optimization/graph_of_convex_sets.h, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa6q9D6RjFrvsN_Yv7:-Msa6q9D6RjFrvsN_Yv8:b48d1t9) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L270)):*
nit: VertexId and EdgeId derive from the Identifier class. Those are always supposed to be passed by value (same as for TypeSafeIndex objects). From the Identifier doxygen:
>  It is the designed intent of this class, that ids derived from this class can
 be passed and returned by value.

Also see Drake style guide [on this topic](https://drake.mit.edu/styleguide/cppguide.html#Pass_By_Value_Primitives).
___
*[geometry/optimization/graph_of_convex_sets.h, line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa4ADC3gXo4NtHEoWR:-Msa4ADC3gXo4NtHEoWS:b-aopqg4) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L276)):*
> ```objc
>   @pydrake_mkdoc_identifier{by_reference}
>   */
>   void RemoveVertex(const Vertex& vertex);
> ```

minor: for both RemoveVertex() methods, please mention that the execution time is O(nₑ) where nₑ is the total number of edges. A caller might reasonably expect this only to involve edges incident to the vertex, making it O(1)-ish like RemoveEdge(). (I'm not complaining about the implementation which seems fine; just saying it should be noted to set caller expectations properly.)
___
*[geometry/optimization/graph_of_convex_sets.h, line 281 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa7Pr46RwLvJO4Wudg:-Msa7Pr46RwLvJO4Wudh:b41sau8) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L281)):*
> ```objc
>   @pydrake_mkdoc_identifier{by_id}
>   */
>   void RemoveEdge(const EdgeId& edge_id);
> ```

minor: should note the precondition that the edge_id must exist (same for vertex_id). An alternative implementation might ignore non-existent edges and vertices, so we should note that this one does not do that.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @RussTedrake and @sherm1)

___
*[geometry/optimization/graph_of_convex_sets.h, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa6q9D6RjFrvsN_Yv7:-MskWwr-BI0fj9NpYFPL:b-l5uhw6) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L270)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: VertexId and EdgeId derive from the Identifier class. Those are always supposed to be passed by value (same as for TypeSafeIndex objects). From the Identifier doxygen:
>  It is the designed intent of this class, that ids derived from this class can
 be passed and returned by value.

Also see Drake style guide [on this topic](https://drake.mit.edu/styleguide/cppguide.html#Pass_By_Value_Primitives).


</blockquote></details>

Done.  Looks like this is abused in other places in this file.  Should I clean those up as well while I'm here?
___
*[geometry/optimization/graph_of_convex_sets.h, line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa4ADC3gXo4NtHEoWR:-MskXp_d023T2YQGFNj7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L276)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: for both RemoveVertex() methods, please mention that the execution time is O(nₑ) where nₑ is the total number of edges. A caller might reasonably expect this only to involve edges incident to the vertex, making it O(1)-ish like RemoveEdge(). (I'm not complaining about the implementation which seems fine; just saying it should be noted to set caller expectations properly.)
</blockquote></details>

Done.
___
*[geometry/optimization/graph_of_convex_sets.h, line 281 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa7Pr46RwLvJO4Wudg:-MskbG8w7vylbHgE2UmY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L281)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should note the precondition that the edge_id must exist (same for vertex_id). An alternative implementation might ignore non-existent edges and vertices, so we should note that this one does not do that.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
CI failed -- you need to make corresponding signature changes to the Python bindings.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299#-:-MskpxqfDUSBaiqgTSC7:b8n1wfu)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @mpetersen94)

___
*[geometry/optimization/graph_of_convex_sets.h, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa6q9D6RjFrvsN_Yv7:-Mskp5BLBWe8ISSzKSLc:byjr5dh) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L270)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Done.  Looks like this is abused in other places in this file.  Should I clean those up as well while I'm here?
</blockquote></details>

Thanks. Assuming it doesn't add much to this PR, fixing the others here would be good to avoid future cargo culting. The change should be invisible to callers.

**Review by mpetersen94 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299#-:-MskxcJ6Dv9toYFeHYzM:b-896fix)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @RussTedrake and @sherm1)

___
*[geometry/optimization/graph_of_convex_sets.h, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16299#-Msa6q9D6RjFrvsN_Yv7:-Mskxmeu18AgNNaK7yh9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cafe2fa4b5eacd526a2e5dc4aaf899b8a7fc175c/geometry/optimization/graph_of_convex_sets.h#L270)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Thanks. Assuming it doesn't add much to this PR, fixing the others here would be good to avoid future cargo culting. The change should be invisible to callers.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Thanks, Mark!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16299#-:-MslE7AOEI41uWAmOYwu:bnqzgtu)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @mpetersen94)

**Pull request merged**
