### PR TITLE
pydrake trajectory: Add more bindings for PiecewisePolynomial

### PR DESCRIPTION
**Pull request by mpetersen94**
Also binds `drake::common::Polynomial` and cleans up previous bindings/tests for PiecewisePolynomial.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11783)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Sorry, got caught up in a few meetings these past few days. Will try to review tomorrow.

**Comment by EricCousineau-TRI** [comment]
Started making some changes here:
https://github.com/mpetersen94/drake/pull/3

Re-cap on questions:

> A few notes that came up in the process:
> 1) The bindings and tests for `PiecewisePolynomial` were a little messy/old style.  I tried to clean them up a bit but didn't want to do too much without input.  If you have thoughts on ways to restructure it/clean it up, I'm happy to make more changes.
> 2) I wasn't sure where to put the `Polynomial` bindings so for now, they are in the `trajectory_py.cc` file.
> 3) I couldn't find the docstrings for the `Polynomial`-based `PiecewisePolynomial` constructors because they were anchored into a different section.
> 4) The methods that take Matrices of `Polynomial` objects could not be bound because Numpy complained that `Polynomial` was a "non-POD or unimplemented POD type".  Any idea what that means and the best way to fix it?
> Thanks again for all of your help!

1 - Not exactly sure if I know what you mean by old-style. I do see `py::arg` added, which is awesome! Can I ask what you meant about testing? That it doesn't use `numpy_compare`?

2 - Would suggest putting them in `pydrake.polynomial`, since that's where our current dtypes are :(

3 - Will look into it...

4 - Fixed it with the pybind dtype stuff.

That being said, I'm not sure if I know what the future is for `Polynomial`... @RussTedrake @avalenzu Can I ask if y'all are actively using `drake/common/polynomial.h`?

**Comment by mpetersen94** [comment]
Changes look good, I'll merge them into this PR branch.

1. By old style I had meant that it was missing a lot of `py::arg` and the test methods seemed weirdly organized (and didn't use kwargs for testing methods).  It was more of an aesthetic comment than a critical one.  The numpy compare stuff probably matters more if either of these classes get typed beyond double sometime in the future.

2. That seems like a fine place for that.  I see you have already created that file in the PR and moved the bindings for `Polynomial` there.  I'm assuming they were also left in `trajectory_py.cc` by mistake so I will remove them after the merge.

3.  Thanks for looking into it. I tried investigating on my own but didn't really understand how the docstrings were generated in the first place.

4. Thanks for the fix.

Even if Polynomial doesn't survive long term, having some method of creating `PiecewisePolynomials` from the individual polynomial coefficients would be nice.  I'm using this to do traj opt on a differentially flat system and then replay the full state trajectory.

**Comment by mpetersen94** [comment]
The changes to make `Polynomial` a dtype have been fixed so they compile and tests for the new methods this enabled have been added.  Modulo finding out why docstrings for two of the constructors aren't building, this should be ready for review!

**Comment by EricCousineau-TRI** [comment]
@mpetersen94 Want me to squash + merge this?

**Comment by mpetersen94** [comment]
Go for it!

**Pull request merged**
