### PR TITLE
Cleans up Pendulum.urdf.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5164)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5164#-:-Kcx7JO8WHC227sexKiZ:b-jzcju5)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5164#-:-Kcx85ip5LI-KT4Gf3bf:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5164)*

**Comment by liangfok** [comment]
Actually, I am no longer sure about the `xsi:schemaLocation` change I made in this PR. Looking at [this tutorial](http://www.w3schools.com/xml/schema_schema.asp), I found the following quote regarding the `xsi:schemaLocation` attribute:

> This attribute has two values, separated by a space. The first value is the namespace to use. The second value is the location of the XML schema to use for that namespace.

Given the above, I will revert the change.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5164#-:-KcxDfwRCx-jb0P8B7Ho:bu2kl51)*

**Comment by liangfok** [comment]
^^^ Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5164#-:-KcxF89vFacTA1KL5oxI:b2e1jl1)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5164)*

**Pull request merged**
