### PR TITLE
Remove rst indentation warning

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3182)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Fixes `/home/ubuntu/workspace/experimental/c5b85b52/drake/doc/buildcop.rst:174: ERROR: Unexpected indentation.` as seen in e.g. https://drake-cdash.csail.mit.edu/viewBuildError.php?type=1&buildid=82861

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all reviews and merge.

**Comment by jwnimmer-tri** [comment]
Windows build executor flake
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3182#-:-KPSf_EIhm3DIQ6nOhpg:bnfp4nl)*

**Pull request merged**
