### PR TITLE
[parsing] Modernize parser.AddAllModelsFromFile

### PR DESCRIPTION
**Pull request by rpoyner-tri**
No deprecations yet; just add the new modernized method.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for review.

See #18157 for prior draft with motivating discussions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208#-:-NFVmGWm-iF6EPVElyCF:b-kk7svx)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208#-:-NFW0marABhjVPppR_vC:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`multibody/parsing/parser.h` line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18208#-NFW-xmE1uZ28CG7RP_c:-NFW-xmF4DGrqiRAm9Ks:ba61e2k) ([raw file](https://github.com/robotlocomotion/drake/blob/56dcdbf1ac305182e15dc2d7df462815b36c5acb/multibody/parsing/parser.h#L47)):*
> ```objc
> /// added as a single model instance in the @p plant.
> ///
> /// Drake Model Directives are only available via AddModels. The
> ```

nit Do strings also work?



_Suggestion:_
```objc
via AddModels or AddModelsFromString
```
___
*[`multibody/parsing/test/parser_test.cc` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18208#-NFW1OcYA5XohwekR4FY:-NFW1OcYA5XohwekR4FZ:butgr1) ([raw file](https://github.com/robotlocomotion/drake/blob/56dcdbf1ac305182e15dc2d7df462815b36c5acb/multibody/parsing/test/parser_test.cc#L26)):*
> ```cpp
> }
> 
> GTEST_TEST(FileParserTest, BasicTest) {
> ```

nit It's almost not worth it, but since it _is_ so easy do to, I think we should keep one test case intact that calls the legacy name.  Either one of the existing tests with a TODO nearby, or a new "LegacyToBeDeprecatedTest" that would eventually disappear.
___
*[`bindings/pydrake/multibody/parsing_py.cc` line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18208#-NFW0VvQ-us83m8cJhXL:-NFW0VvQ-us83m8cJhXM:becdf6p) ([raw file](https://github.com/robotlocomotion/drake/blob/56dcdbf1ac305182e15dc2d7df462815b36c5acb/bindings/pydrake/multibody/parsing_py.cc#L85)):*
> ```cpp
>             "AddModels",
>             [](Parser& self, const std::string& file_name) {
>               return self.AddModels(file_name);
> ```

nit It would help to somehow reminder the reader here why this is a lambda instead of the `&Parser::AddModels` pointer (because of the string => fs::path conversion).  That could be via a comment, or by writing the `path{file_name}` conversion explicitly within the lambda.

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for Wednesday schedule platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208#-:-NFjouwV6zn4abbX35x2:bnz375r)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) Deprecations are suggested as TODO, but not actively forcing any diagnostics.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208#-:-NFjp5rr7vGVzvvk8JWx:byot6kw)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18208#-:-NFjrw_o8LMirOmeWTAZ:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
