### PR TITLE
Added instructions on how to use clang on ubuntu.

### PR DESCRIPTION
**Pull request by liangfok**
I tested this on my local Ubuntu machine.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2845)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-:-KN3k8V0NVOvRkzyZNPC:-1800536653)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/ubuntu.rst, line 124 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-KN49erY-KepAbfPqLBX:-KN49erY-KepAbfPqLBY:-276565767) ([raw file](https://github.com/robotlocomotion/drake/blob/437e0e6f1e7e9b371890c76c709fa80c1dc49ba7/drake/doc/ubuntu.rst#L124)):*
> ```reStructuredText
> 
> The above examples result in the use of ``gcc`` as the compiler. If you want to
> use ``clang`` as the compiler, place the following in your ``~/.bashrc`` file::
> ```

I wonder if it is clear enough that this "If you want to use clang as the compiler..." is in the context of "If the system's default compiler is not being used ...".  If you are on OS X, you'd not want to do any of these commands, because you'd already have clang by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/doc/ubuntu.rst, line 124 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-KN49erY-KepAbfPqLBX:-KN4G5XLwQHvSfsenUcK:-1656229710) ([raw file](https://github.com/robotlocomotion/drake/blob/437e0e6f1e7e9b371890c76c709fa80c1dc49ba7/drake/doc/ubuntu.rst#L124)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I wonder if it is clear enough that this "If you want to use clang as the compiler..." is in the context of "If the system's default compiler is not being used ...".  If you are on OS X, you'd not want to do any of these commands, because you'd already have clang by default.
</details>
I guess the fact that this is `ubuntu.html` is good enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-:-KN4G9bHWLGyG0tUyZDG:1417088721)*

**Comment by liangfok** [comment]
CI failure was due to a MATLAB flake. Should we override merge? https://drake-jenkins.csail.mit.edu/job/experimental/2804/compiler=gcc,label=linux_matlab/

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-:-KN4HV5CNaGxAfiq-CJ9:1883495743)*

**Comment by jwnimmer-tri** [comment]
Unfortunately, the matlab configuration is the one that builds the documentation as well.

**Comment by liangfok** [comment]
OK. @drake-jenkins-bot: retest this please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-:-KN4ZYmgGB7Tmo0w-L1R:2082280276)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2818/. Since tomorrow's Wednesday, +@sammy-tri for platform review and merge.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-:-KN4o8D1HI0uIgrajvzD:-1530138148)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/doc/ubuntu.rst, line 124 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-KN7nc74Ov80eH2CPDpV:-KN7nc75uxeWRr1ExRd6:-358989243) ([raw file](https://github.com/robotlocomotion/drake/blob/437e0e6f1e7e9b371890c76c709fa80c1dc49ba7/drake/doc/ubuntu.rst#L124)):*
> ```reStructuredText
> 
> The above examples result in the use of ``gcc`` as the compiler. If you want to
> use ``clang`` as the compiler, place the following in your ``~/.bashrc`` file::
> ```

FYI, I'm not personally a fan of asking people to edit their .bashrc files (hell, I'm not even a bash user) but it's pervasive throughout this document and more advanced ubuntu users will understand setting environment variables anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-:-KN7ntioJCD8yCKvddKW:1417088721)*

**Comment by liangfok** [comment]
*[drake/doc/ubuntu.rst, line 124 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-KN7nc74Ov80eH2CPDpV:-KN7qwoX_wfa34YQxXym:1232981353) ([raw file](https://github.com/robotlocomotion/drake/blob/437e0e6f1e7e9b371890c76c709fa80c1dc49ba7/drake/doc/ubuntu.rst#L124)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI, I'm not personally a fan of asking people to edit their .bashrc files (hell, I'm not even a bash user) but it's pervasive throughout this document and more advanced ubuntu users will understand setting environment variables anyway.
</details>
Would it help to qualify the above sentence with the phrase "and you're using bash"? If so, I'll submit another PR with that change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/ubuntu.rst, line 124 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2845#-KN7nc74Ov80eH2CPDpV:-KN7u9UzGQ5dmOPnjLbj:855554139) ([raw file](https://github.com/robotlocomotion/drake/blob/437e0e6f1e7e9b371890c76c709fa80c1dc49ba7/drake/doc/ubuntu.rst#L124)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Would it help to qualify the above sentence with the phrase "and you're using bash"? If so, I'll submit another PR with that change.
</details>
LGTM as is...  I was mostly just being whiny.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2845)*

**Pull request merged**
