### PR TITLE
[workspace] Enable SDP support in Clarabel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19449.

The release notes are "fix" because we need to list the new externals in the release notes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20475#-NiLli7813K9mkiDkITw):*
Working

We need to itemize the new crates here, for the release notes to mention as new dependencies.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475#-:-NiLzSX7ExigydC8FoNo:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475#-:-NiLzz6J8jCXfpcAUmy0:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20475#-NiLli7813K9mkiDkITw):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

We need to itemize the new crates here, for the release notes to mention as new dependencies.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 7 of 17 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20475#-:-NiaTJc_8_iDOncwOINg:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
