### PR TITLE
Adds offset between the vehicle model's frame and the Prius visualization's frame.

### LINKED ISSUE #5341: Automotive demo cars rendering has wrong origin for rotation
(This is just from watching the demo, but I'm pretty sure I'm right.  Someone who does a code / model dive can confirm.)

The automotive demo's cars rendering uses the wrong yaw-rotation origin.  We are using the prius SDF model and mapping x,y,yaw to a floating joint.  A turning car should curve around the center of the rear axle, but to my eye we are pivoting around the rear bumper (approximately).

It's possible that this isn't worth fixing until PoseAggregator is in place, depending on how much rework is RigidBodyTree specific vs applicable to the PoseAggregator design as well.

/CC @david-german-tri @liangfok

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5341. Hopefully for real this time.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5658)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review please since you reviewed #5470.
+@jwnimmer-tri for car review please.

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgQhq8F6GeNLLMCm5__:bfam9ef)*

**Comment by jwnimmer-tri** [comment]
:car: beep beep

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgQuxds-1DvsO4ba1iM:b-ymhpdx)*

**Comment by jadecastro** [comment]
Pass complete. PTAL.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/car_vis.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgRBvU8Qvu7yTVarpc2:-KgRBvU8Qvu7yTVarpc3:b8v6au9) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/car_vis.h#L45)):*
> ```objc
>   /// visualization. The provided `X_WM` is the pose of the vehicle model in the
>   /// world frame. The origin of the model's frame is assumed to be in the
>   /// middle of the vehicle's rear axle. The poses in the returned PoseBundle
> ```

I don't think this comment is necessary, since `CarVis` doesn't seem to have any specific math to warrant imposing such a restriction on child classes?

---

*[drake/automotive/test/prius_vis_test.cc, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgUHYXi_abKA8X7sV4G:-KgUHYXi_abKA8X7sV4H:bl7kofk) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L151)):*
> ```cpp
>   // offset from the model's pose. See prius_vis.cc, method CalcPoses(), for
>   // more details.
>   const double kVisOffset{1.40948};
> ```

BTW, consider storing this value within `PriusVis` and accessing via a named getter

---

*[drake/automotive/test/prius_vis_test.cc, line 176 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgTxHyx4HTmdZSd8-cZ:-KgTxHyx4HTmdZSd8-c_:b-xlek0) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L176)):*
> ```cpp
>   EXPECT_DOUBLE_EQ(
>       floor_pose_down_hill.translation().x(),
>       kVisOffset * cos(M_PI_4));
> ```

BTW, `std::cos`

---

*[drake/automotive/test/prius_vis_test.cc, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgTxPQI6Vi69sPMot8b:-KgTxPQI6Vi69sPMot8c:b3yg5nc) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L179)):*
> ```cpp
>   EXPECT_DOUBLE_EQ(
>       floor_pose_down_hill.translation().z(),
>       -kVisOffset * cos(M_PI_4) + floor_pose_identity.translation().z());
> ```

BTW, std::cos

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgUHgiFrDWooWpsN1rK:b-wjpjkm)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/test/prius_vis_test.cc, line 182 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgUIZAp3BzFC0_jHlnu:-KgUIZAp3BzFC0_jHlnv:bsvxphi) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L182)):*
> ```cpp
> 
>   // Tests the visualization's pose when the model is rotated 45 degrees about
>   // its +X axis. In other words, the vehicle is leaning to its left side due to
> ```

BTW, `right side`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/car_vis.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgRBvU8Qvu7yTVarpc2:-KgUIyMqkbvefrdwQc_P:bpo82l1) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/car_vis.h#L45)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

I don't think this comment is necessary, since `CarVis` doesn't seem to have any specific math to warrant imposing such a restriction on child classes?
</blockquote></details>

This is an interesting question. Suppose a future user wants to implement another child class of `CarVis`. How should this user interpret the semantics of `X_WM`? It clearly depends on `M`, which is the model for which a visualization is being applied. Since there can be many versions of `M` (e.g., we already have `SimpleCar`, `TrajectoryCar`, `MaliputRailcar`, etc.), don't we need a "standard" by which the semantics of `M` can be conveyed to the visualizer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658)*

**Comment by jadecastro** [comment]
Thinking specifically in terms of BicycleCar where the correct
visualization of yaw rotation would not be the axle but instead about the
CG. Would I not be able to make use of CarVis in this case?

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/car_vis.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgRBvU8Qvu7yTVarpc2:-KgUNz30CTjnG1ujNsfM:b-3inr5w) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/car_vis.h#L45)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This is an interesting question. Suppose a future user wants to implement another child class of `CarVis`. How should this user interpret the semantics of `X_WM`? It clearly depends on `M`, which is the model for which a visualization is being applied. Since there can be many versions of `M` (e.g., we already have `SimpleCar`, `TrajectoryCar`, `MaliputRailcar`, etc.), don't we need a "standard" by which the semantics of `M` can be conveyed to the visualizer?
</blockquote></details>

(See above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658)*

**Comment by liangfok** [comment]
This is where things get interesting. Should we introduce another transform within the model, say `X_MC`, that converts from the "model" frame (`M`) to the "center of the model" frame (`C`)? That way, the poses of all models can be converted into a standard "center" frame, against which the visualizations are then based?

**Comment by jwnimmer-tri** [comment]
For automotive, the pose in PoseAggregaor the point at which curvature originates.  There's no need for more than one `X_Msomething`.  CarVar just has to map from that to whatever visual geometry has been chosen.

**Comment by liangfok** [comment]
`PoseAggregator` contains the poses of many types of models. The frames of some models originate in the middle of the rear axle (e.g., `SimpleCar`). The frames of other models originate in the "center" (e.g., `BicycleModel`). Are you saying these discrepancies should be resolved prior to the model poses being added to the `PoseAggregator`?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgUSpmxGr4iNJe6pi7g:b-fbh614)*

**Comment by liangfok** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/car_vis.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgRBvU8Qvu7yTVarpc2:-KgUqt9q0ToQje-VXDMF:b6tthvu) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/car_vis.h#L45)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

(See above)
</blockquote></details>

Per F2F discussion, we decided for now to require that the `PoseVector` outputs of all vehicle models be in terms of the middle of the rear axle. In the future, we may generalize this to be in the middle of the non-steering axle, or even support vehicles with multiple steering axles.

---

*[drake/automotive/test/prius_vis_test.cc, line 151 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgUHYXi_abKA8X7sV4G:-KgUtck0oekRcrd8Ds2n:b6nt2k2) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L151)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, consider storing this value within `PriusVis` and accessing via a named getter
</blockquote></details>

Done. I made it a static const if that's OK.

---

*[drake/automotive/test/prius_vis_test.cc, line 176 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgTxHyx4HTmdZSd8-cZ:-KgUuLYGU45SbBbsywfM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L176)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, `std::cos`
</blockquote></details>

Done.

---

*[drake/automotive/test/prius_vis_test.cc, line 179 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgTxPQI6Vi69sPMot8b:-KgUuMVcT4yBjo5oGfl4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L179)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, std::cos
</blockquote></details>

Done.

---

*[drake/automotive/test/prius_vis_test.cc, line 182 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-KgUIZAp3BzFC0_jHlnu:-KgUuTVMcttiHoXOU0nK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/893aabd9594720a8cdfc07c5bb53ff6c3cfb12b0/drake/automotive/test/prius_vis_test.cc#L182)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, `right side`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please.

**Comment by jadecastro** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgV7cBtQjyB51nIIFLA:bnfp4nl)*

**Comment by liangfok** [comment]
+@soonho-tri for platform review please. Thanks.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgV7jPStXR8889NRdly:b-lnsuq7)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5658#-:-KgVI8nvCoYudcbyvDKE:bnfp4nl)*

**Pull request merged**
