### PR TITLE
Adds more meshcat visualizations for IrishInConfigurationSpace tests.

### PR DESCRIPTION
**Pull request by RussTedrake**
+@cohnt for feature review, please?

To see these, use
```
bazel build //geometry/optimization:iris_in_configuration_space_test && bazel-bin/geometry/optimization/iris_in_configuration_space_test
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@cohnt for feature (attempt #2)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834)* status: 1 unresolved discussion, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 626 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na2Aa0xA8de1y1ctyQa:-Na2Aa0xA8de1y1ctyQb:bj4pz8a) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L626)):*
> ```cpp
>   const Vector2d sample{1.0, 0.0};
>   IrisOptions options;
>   options.num_collision_infeasible_samples = 10;
> ```

happily this can be removed once #19835 lands.
cc @rhjiang

**Review by cohnt — COMMENTED** [review]
Looks like double pendulum region grows outside of the feasible set:

Is this behavior expected/acceptable?

Besides that, the code all looks good.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-:-Na7DAEQ2so6U-65mcon:bd2zzej)* status: 2 unresolved discussions, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 863 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na7EhUJBA2-lvbgm6x_:-Na7EhUJBA2-lvbgm6xa:b-wj1i7y) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L863)):*
> ```cpp
>   options.prog_with_additional_constraints = &ik.prog();
>   // We required > 10 samples to pass the test on mac CI with ipopt.
>   options.num_additional_constraint_infeasible_samples = 15;
> ```

Note: I had to set this to 50 for the double pendulum IRIS region to not grow out of the feasible set.

**Review by RussTedrake — COMMENTED** [review]
Right.  That's expected!  (unless we further increase the infeasible samples).  I see that you did that below.
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-:-Na7YPxEDcDVlFBxC9Pf:b-qderzx)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: minor stuff

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-:-Na8E_X58vZEEB7EK6TE:bo23mka)* status: 3 unresolved discussions

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 762 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na8DvuW9gZufBD6amkB:-Na8DvuW9gZufBD6amkC:bnzm9ug) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L762)):*
> ```cpp
>     meshcat->SetObject("Test point", Sphere(0.03), Rgba(1, 0, 0));
>     meshcat->SetTransform("Test point", math::RigidTransform(Eigen::Vector3d(
>                                             z_test, theta_test, 0)));
> ```

minor I wonder if there will be more of these meshcat drawings of 2D test case math? If so, it might be worth considering factoring out a little helper class for this group of tests. I don't think it's quite necessary now, but worth a moment's thought.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 764 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na8Cl8sAkweROby93ZD:-Na8Cl8sAkweROby93ZE:b-lha92n) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L764)):*
> ```cpp
>                                             z_test, theta_test, 0)));
> 
>     // Note: This will not pause execution when running as a bazel test.
> ```

This "pause for user" stanza feels like it could be an anonymous namespace free function, rather than pasted thrice. To be clear, I doubt it will save line count, but it will give a single point of code to hang the documentation on.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),cohnt

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 626 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na2Aa0xA8de1y1ctyQa:-Na8_UDF2EzHb0l7kUzl:bdza5nz) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L626)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

happily this can be removed once #19835 lands.
cc @rhjiang 
</blockquote></details>

It will be easier to merge this one first; I will remove this line when merging the other PR.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 762 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na8DvuW9gZufBD6amkB:-Na8_IzH4PWbKQFjOxc1:b-t9hvk6) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L762)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor I wonder if there will be more of these meshcat drawings of 2D test case math? If so, it might be worth considering factoring out a little helper class for this group of tests. I don't think it's quite necessary now, but worth a moment's thought.
</blockquote></details>

Agreed. I would actually like to add features to the meshcat class itself to make these easier.  But I'll defer that for future work.
___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 764 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19834#-Na8Cl8sAkweROby93ZD:-Na8rCjp7t69Xb388CSN:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/63b98463e2380ae66b881220183a4d481af2fe81/geometry/optimization/test/iris_in_configuration_space_test.cc#L764)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This "pause for user" stanza feels like it could be an anonymous namespace free function, rather than pasted thrice. To be clear, I doubt it will save line count, but it will give a single point of code to hang the documentation on.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19834)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),cohnt

**Pull request merged**
