### PR TITLE
Fix Wdeprecated warnings in multibody

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See individual commit message for the why and how of each patch.
See #8288 for the entire feature branch.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8303)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review of the pieces related to `RigidBodyFrame`, please (the file in `examples` and the files directly within `multibody/*.[ch]*`).

+@SeanCurtis-TRI for the rest of feature and platform review, please.

**Comment by amcastro-tri** [comment]
Reviewed 6 of 16 files at r1.
Review status: 6 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8303)*

**Comment by SeanCurtis-TRI** [comment]
Thanks @jwnimmer-tri all of the `const box = ...` stuff really underscores the significance of wrong code being copied-and-pasted a lot.

:LGTM:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8303#-:-L77-Rwdi3PIS7SSoE0o:bjwo275)*

**Comment by jwnimmer-tri** [comment]
@amcastro-tri waiting on your LGTM when you're ready.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8303#-:-L772YeBKVTXzRPHS1-x:bvkc8vs)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 10 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8303#-:-L7AF0uY_6gD--91cwMB:bnfp4nl)*

**Pull request merged**
