### PR TITLE
Create an IK test using the iiwa arm

### PR DESCRIPTION
**Pull request by sammy-tri**
Add a new test to testIK which uses the iiwa arm

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2702)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Platform review: +@jwnimmer-tri 
Feature review: +@ggould-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLSaWQCPuy-tyIa3SaX:937273743)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please (unexpected windows builder failure)

**Comment by ggould-tri** [comment]
While I appreciate that nothing else in `testIK.cpp` is commented, I do think that you need comments here -- to explain what the positions are, what variable names like `tspan` mean, and to justify that `expected` vector and why it is the unique correct answer to the IK problem.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLSdd3pWf3GdFGtKRcB:1488599558)*

**Comment by sammy-tri** [comment]
Will do.  Marking "do not review" for a bit while I finish that since things are gonna change a bit.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLShkzgc55WvlJS-sH1:1933621854)*

**Comment by sammy-tri** [comment]
Added comments and fixed some other issues.  I think we're again good to review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLT8nrmX7cSNJ0VMBWs:-1400921401)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/test/testIK.cpp, line 10 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTbclCjksjtFuKHX-6:-KLTbclCjksjtFuKHX-7:-2054349139) ([raw file](https://github.com/robotlocomotion/drake/blob/bf237892e7c6e6a64601445e7defb96cc4fef49c/drake/systems/plants/test/testIK.cpp#L10)):*
> ```cpp
> #include "drake/systems/plants/RigidBodyTree.h"
> #include "drake/util/eigen_matrix_compare.h"
> #include "gtest/gtest.h"
> ```

BTW Pre-existing defect, but this should precede the drake includes.

---

*[drake/systems/plants/test/testIK.cpp, line 59 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTbrRKP5LlEF0MQjP_:-KLTbrRKP5LlEF0MQjPa:-729621696) ([raw file](https://github.com/robotlocomotion/drake/blob/bf237892e7c6e6a64601445e7defb96cc4fef49c/drake/systems/plants/test/testIK.cpp#L59)):*
> ```cpp
> 
> GTEST_TEST(testIK, iiwaIK) {
>   RigidBodyTree model("examples/kuka_iiwa_arm/urdf/iiwa14.urdf");
> ```

I disagree with code in `systems/plants/test` depending on `examples`.  I should be able to do anything I want in `examples/**` and Drake itself should still compile and pass its unit tests.  See #2548 for a little background.

---

*[drake/systems/plants/test/testIK.cpp, line 71 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTcS483zvVsEX6lnds:-KLTcS49EKi3oFP9yOMn:-165696) ([raw file](https://github.com/robotlocomotion/drake/blob/bf237892e7c6e6a64601445e7defb96cc4fef49c/drake/systems/plants/test/testIK.cpp#L71)):*
> ```cpp
>   VectorXd q0 = model.getZeroConfiguration();
> 
>   // Constraint iiwa_link_7 (the end effector) to move 0.57 on the X
> ```

BTW Is the 0.57 here and 0.58 below being different intentional?

---

*[drake/systems/plants/test/testIK.cpp, line 95 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTcsifBv5xeJWbx5oa:-KLTcsig44XnTQaZZMXA:-886238889) ([raw file](https://github.com/robotlocomotion/drake/blob/bf237892e7c6e6a64601445e7defb96cc4fef49c/drake/systems/plants/test/testIK.cpp#L95)):*
> ```cpp
>   IKoptions ikoptions(&model);
> 
>   VectorXd q_sol(model.number_of_positions());
> ```

BTW consider zeroing this, for better determinism.

---

*[drake/systems/plants/test/testIK.cpp, line 96 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTcpRGdOgET0hocnop:-KLTcpRGdOgET0hocnoq:-886238889) ([raw file](https://github.com/robotlocomotion/drake/blob/bf237892e7c6e6a64601445e7defb96cc4fef49c/drake/systems/plants/test/testIK.cpp#L96)):*
> ```cpp
> 
>   VectorXd q_sol(model.number_of_positions());
>   int info;
> ```

BTW consider zeroing this, for better determinism.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/testIK.cpp, line 59 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTbrRKP5LlEF0MQjP_:-KLWX4C-4zBXO-3nd2SR:1687422326) ([raw file](https://github.com/robotlocomotion/drake/blob/26065478bcb14915e830b8b7a7273a514cc0dc25/drake/systems/plants/test/testIK.cpp#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I disagree with code in `systems/plants/test` depending on `examples`.  I should be able to do anything I want in `examples/**` and Drake itself should still compile and pass its unit tests.  See #2548 for a little background.
</details>
That's nice.   Personally, I've got mixed feelings about the designated hitter rule, but I'm not sure what you'd like for me to do about that either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLWYpsnJdGmGN98XLJf:1417088721)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/test/testIK.cpp, line 10 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTbclCjksjtFuKHX-6:-KLWa-Cwd10dicpoBupd:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/26065478bcb14915e830b8b7a7273a514cc0dc25/drake/systems/plants/test/testIK.cpp#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Pre-existing defect, but this should precede the drake includes.
</details>
Done.

---

*[drake/systems/plants/test/testIK.cpp, line 71 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTcS483zvVsEX6lnds:-KLW_zRDx3kzB52KpBdO:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/26065478bcb14915e830b8b7a7273a514cc0dc25/drake/systems/plants/test/testIK.cpp#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Is the 0.57 here and 0.58 below being different intentional?
</details>
Done.

---

*[drake/systems/plants/test/testIK.cpp, line 95 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTcsifBv5xeJWbx5oa:-KLWaSOsb41vEdZ52ORj:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/26065478bcb14915e830b8b7a7273a514cc0dc25/drake/systems/plants/test/testIK.cpp#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW consider zeroing this, for better determinism.
</details>
Done.

---

*[drake/systems/plants/test/testIK.cpp, line 96 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-KLTcpRGdOgET0hocnop:-KLW_uSxgPUAh31rLMWI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/26065478bcb14915e830b8b7a7273a514cc0dc25/drake/systems/plants/test/testIK.cpp#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW consider zeroing this, for better determinism.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLXB7Tzy683jRanhY3O:1417088721)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702)*

**Comment by ggould-tri** [comment]
Reviewable is refusing to let this go green because discussions are "short-handed."  This is a test comment to see if I caused that.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLXDv75D--RlVHPUp78:1443003591)*

**Comment by jwnimmer-tri** [comment]
Nope, it was the "Done" to the 4 "BTW" comments, which means Sam was discussing only with himself.  An "Ack" button on those would have been enough.  I have marked those 4 as "Satisfied" for me, in order to close the discussions.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2702#-:-KLXED7IFBkwrb_KXoa6:1953385804)*

**Pull request merged**
