### PR TITLE
[solvers] Remove fast_qp and gurobi_qp

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
These files contain years-old functions that are not up to par with Drake's present-day standards for our library (e.g., they have no unit tests at all), and are entirely unused within Drake itself.

These files were only available if Gurobi was enabled, so have never been part of Drake's modern binary releases.  It's possible that users building from source have been using these functions.  If so, those users should copy these files into their own project's source tree, and continue using them there.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15817)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.  \CC @hongkai-dai @RussTedrake FYI

**Review by siyuanfeng-tri — COMMENTED** [review]
:lgtm: @hongkai-dai if i remember correctly, i think these were used by the old humanoid stuff in drake from drc days, correct? i don't think we use these anywhere else? 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15817#-:-MkOjoxyBt9VyfmWCIFe:bkjkv1e)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by hongkai-dai — COMMENTED** [review]
@siyuanfeng-tri that is right, gurobi_qp and fast_qp were used during the DRC days. I don't think we use it anywhere else.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15817#-:-MkPM7_G4A0gg1O05qyj:bu74jv3)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15817#-:-Mkbhc_o8z8bGJErGS2A:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),siyuanfeng-tri (waiting on @jwnimmer-tri)

**Pull request merged**
