### PR TITLE
Ask whether build --python_path= can be added to .bazelrc on Mac

### PR DESCRIPTION
**Pull request by jamiesnape**
Broken out of #7323, @soonho-tri's comments addressed, and rebased on master.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7535)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jadecastro** [comment]
It seems to work for me. `setup/mac/install_prereqs.sh` seems to behave as expected - it creates/populates a `.bazelrc` file as advertised, and only the first time that it's run. Should I also be running any unit tests?

**Comment by jamiesnape** [comment]
Run the pydrake ones.

**Comment by jadecastro** [comment]
+@jadecastro feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7535#-:-L-CafKDrZAOiIJbcmSd:b-ejn9ja)*

**Comment by jadecastro** [comment]
All pydrake tests passed. :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7535#-:-L-CinScn5BfnBUI5VRO:b-j79yzx)*

**Comment by jadecastro** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7535)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
Platform :lgtm: with one BTW.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7535#-L-DjT-uQ81c0S6aqNkP:-L-DjT-uQ81c0S6aqNkQ:bdrpp64) ([raw file](https://github.com/robotlocomotion/drake/blob/7c65385786bf0fcf9657365c69654333900255f1/setup/mac/install_prereqs.sh#L86)):*
> ```Shell
> 
> if [[ ! -f "${HOME}/.bazelrc" ]] || ! grep -q "^build --python_path=/usr/local/opt/python/libexec/bin/python$" "${HOME}/.bazelrc"; then
>   echo "Using a python other than /usr/local/opt/python/libexec/bin/python is NOT supported" >&2
> ```

BTW does this need an `exit 4` or something to indicate failure?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7535#-:-L-DjcPPsh4i15EqSajn:blp31u9)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/mac/install_prereqs.sh, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7535#-L-DjT-uQ81c0S6aqNkP:-L-DlXzhO2whWmVjk3ut:bvm9jnl) ([raw file](https://github.com/robotlocomotion/drake/blob/7c65385786bf0fcf9657365c69654333900255f1/setup/mac/install_prereqs.sh#L86)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW does this need an `exit 4` or something to indicate failure?
</blockquote></details>

BTW No, it is just a warning 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7535)*

**Pull request merged**
