### PR TITLE
[sensors] Add internal helpers in anticipation of ImageIo support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20447.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-:-Ni071Z499STYG9A_Xvg:b-6eu8fg)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done; most of my issues are with `CopyRaw` and there are a number of ways of resolving them. I'm open to them all and defer to you on which you prefer.

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-:-Ni0MDRK8TGFgdpkBBEL:bqaxwnv)* status: 8 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`systems/sensors/image_io_internal.h` line 34 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0BeQr74uYrOO0X-3N:-Ni0BeQr74uYrOO0X-3O:bkppwzq) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L34)):*
> ```objc
> 
> /* Returns true iff the PixelType's channel ordering is BGR (in which case it
> will need to be reversed to match ImageIo's convention of RGB ordering). */
> ```

nit ImageIo (as of this PR) doesn't document any such convention. Presumably that's present in a more evolved branch? Probably better if the convention entered at the same point as the class and the dependency.
___
*[`systems/sensors/image_io_internal.h` line 36 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0Dvn38eIgH1YpPGZk:-Ni0Dvn38eIgH1YpPGZl:bs59g1u) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L36)):*
> ```objc
> will need to be reversed to match ImageIo's convention of RGB ordering). */
> template <PixelType kPixelType>
> constexpr bool NeedsSwizzle() {
> ```

BTW The term "swizzle" strikes me as imprecise. While reversing BGR to RGB is one form of swizzling, swizzling is a much bigger space of operations. It doesn't seem to me that we'll ever want to implement swizzling generally. We could be more targeted simply by swapping "Swizzle" with "ChannelReverse" or some such thing.

(Same applies to `CopyRaw`'s `swizzle` parameter.)
___
*[`systems/sensors/image_io_internal.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0Cp-77SNIV51HK9G8:-Ni0Cp-77SNIV51HK9G9:b-il8gp5) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L54)):*
> ```objc
>       return false;
> #pragma GCC diagnostic pop
>   }
> ```

nit: For consistency, do we want to conclude this with a `DRAKE_UNREACHABLE()` as you did for `GetVtkScalarType`?
___
*[`systems/sensors/image_io_internal.h` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0DFc8-QL0HBB1RynG:-Ni0DFc8-QL0HBB1RynH:b-uo0eoj) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L89)):*
> ```objc
> }
> 
> /* Copies pixel data from one memory buffer to another, flipping the image
> ```

BTW In the context of Drake, this is probably OK (the types of images that Drake plays with are quite limited). But, generally, pixel data can be less compact than this implementation implies. I.e., image data may be padded so that a row length in memory satisfies certain size requirements. We're not going to support any of this, but it might be worth being explicit about properties of the pixel data that are assumed.
___
*[`systems/sensors/image_io_internal.h` line 99 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0Ee8nAOJWkra-pnDa:-Ni0Ee8nAOJWkra-pnDb:bj13iqi) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L99)):*
> ```objc
> @param dest Destination memory buffer.
> @param width Image width.
> @param height Image height. */
> ```

nit  I infer that the source/dest channel counts are to implicitly handle truncating RGBA to RGB (for example, the RGB->RGBA path would not benefit from the default value; making every pixel transparent as a default doesn't make a great deal of sense). 

However, the one-channel (luminance) image seems problematic. When going from 1 -> 3/4 channels, you're basically turning luminance into a red-tinted image. And when going from rgb/rgba -> luminance, you're not getting the images real luminance, but simply returning the red channel.

We should say/do something about this.
___
*[`systems/sensors/image_io_internal.h` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0DLDj1p7s6o8s9Zvi:-Ni0DLDj1p7s6o8s9Zvj:b-1btc0c) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L102)):*
> ```objc
> template <typename T, int source_channels, bool swizzle,
>           int dest_channels = source_channels, uint8_t dest_pad = 0>
> void CopyRaw(const T* source, T* dest, int width, int height) {
> ```

BTW "Flipping" seems like such a significant operation that it seems the name should reflect it, `CopyAndFlipRaw` might be a better name.
___
*[`systems/sensors/image_io_internal.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0GUXtBJdZzDUxFhIw:-Ni0GUXtBJdZzDUxFhIx:b-f2kof0) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L112)):*
> ```objc
>         *(dest++) = source[source_channel];
>       }
>       source += min_channels;
> ```

nit: This can't be right. If source is rgba and dest is rgb and we're truncating the alphas, source should *still* be stepping from one pixel to the next (four channels). But this is only stepping three channels. So, the first dest pixel gets r0, g0, b0. But the second pixel gets a0, r1, b1.

(I note that truncation wasn't tested.)
___
*[`systems/sensors/test/image_io_internal_test.cc` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0JrTL94WVjVDEZVEU:-Ni0JrTL94WVjVDEZVEV:bb5wl45) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/test/image_io_internal_test.cc#L16)):*
> ```cpp
> namespace fs = std::filesystem;
> 
> GTEST_TEST(ImageIoInternalTest, FileFormatFromExtension) {
> ```

nit Feels like at least some of these should've had different capitalization. Right now, I can remove the lower-casing and the test can pass.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`systems/sensors/image_io_internal.h` line 34 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0BeQr74uYrOO0X-3N:-Ni0PjzB4_dfwfUxw8gO:buiyc8x) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit ImageIo (as of this PR) doesn't document any such convention. Presumably that's present in a more evolved branch? Probably better if the convention entered at the same point as the class and the dependency.
</blockquote></details>

Done (it's the VTK convention, actually).
___
*[`systems/sensors/image_io_internal.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0Cp-77SNIV51HK9G8:-Ni0Pbg05rWrG_zYAjzI:b-879u3v) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: For consistency, do we want to conclude this with a `DRAKE_UNREACHABLE()` as you did for `GetVtkScalarType`?
</blockquote></details>

No need.  The compiler will yell at us if our switch-case missed an enum.  The VTK one is an `int` not an `enum`, so needs the special handling for fall-through.
___
*[`systems/sensors/image_io_internal.h` line 99 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0Ee8nAOJWkra-pnDa:-Ni0Q2Ao22PJYduAYpTN:bcjtd2s) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L99)):*
I tried to make it somewhat more clear.  Given that this private function will be used in literally just this one library, I am not overly concerned about a developer holding it wrong and breaking things.  This is not a big public function that lots of people will be calling.

> ... for example, the RGB->RGBA path would not benefit from the default value ...

The default value of 0 was to _force_ the caller to provide something better when necessary -- it was never a good value for any use case.  The only call site in the branch that uses this was passing 0xff, so I've changed the default to use that value.
___
*[`systems/sensors/image_io_internal.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0GUXtBJdZzDUxFhIw:-Ni0Qc9D3OcnBGBJtyqo:biijw85) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L112)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This can't be right. If source is rgba and dest is rgb and we're truncating the alphas, source should *still* be stepping from one pixel to the next (four channels). But this is only stepping three channels. So, the first dest pixel gets r0, g0, b0. But the second pixel gets a0, r1, b1.

(I note that truncation wasn't tested.)
</blockquote></details>

Done (via assertion).  That use case was not intended to be supported.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

___
*[`systems/sensors/image_io_internal.h` line 112 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0GUXtBJdZzDUxFhIw:-Ni0UeYJ5JybmVsX1R-R:bbxqdpj) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Actually, we do need this (for some arcane cases).  I'll rework (with test).
</blockquote></details>

Done again.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@xuchenhan-tri for platform review (as today's and tomorrow's platform have already been used up on this PR.)

> Reviewed 1 of 9 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-:-Ni0VTZ29B4qig4NtF_Q:b-woablo)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/sensors/image_io_internal.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni0Cp-77SNIV51HK9G8:-Ni0TMgU1G_gnL_MA3HE:b-xn2cdh) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3234bdfafc059e081b22f7697c17aedacce74dd/systems/sensors/image_io_internal.h#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No need.  The compiler will yell at us if our switch-case missed an enum.  The VTK one is an `int` not an `enum`, so needs the special handling for fall-through.
</blockquote></details>

Some clarification:

Both `GetVtkScalarType` and `NeedsBgrSwizzle` have switches on `enum`-valued template parameters. So, my question about consistency still stands, but it suggests the use of `DRAKE_UNREACHABLE()` in `GetVtkScalarType()` is the weirdo that deserves correction. It should simply be removed (for the reason you gave).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 7 of 9 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-:-Ni671wo-5oZCZ-1YPH5:bg7igkv)* status: 3 unresolved discussions

___
*[`systems/sensors/image_io_internal.h` line 98 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni62FMnC0uAHILccDAw:-Ni62FMnC0uAHILccDAx:b2nhzy8) ([raw file](https://github.com/RobotLocomotion/drake/blob/f277cb1479eae13d1d62f994f777d17cc5dfcdb6/systems/sensors/image_io_internal.h#L98)):*
> ```objc
>  option is intended to either add or remove the alpha channel, so it must be
>  within ±1 of source_channels.
> @param dest_pad Filler value to use when when dest_channels > source_channels.
> ```

btw



_Suggestion:_
```objc
@tparam T Channel type scalar (typically uint8_t, uint16_t, or float).
@tparam source_channels Number of source channels (typically 1, 3, or 4).
@tparam swizzle Whether to swizzle channels (i.e., changing BGR to RGB).
@tparam dest_channels Number of destination channels (typically 1, 3, or 4). This
 option is intended to either add or remove the alpha channel, so it must be
 within ±1 of source_channels.
@tparam dest_pad Filler value to use when when dest_channels > source_channels.
```
___
*[`systems/sensors/image_io_internal.h` line 122 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni63vOkBjLbcHG5rnSy:-Ni63vOkBjLbcHG5rnSz:bmxmhiu) ([raw file](https://github.com/RobotLocomotion/drake/blob/f277cb1479eae13d1d62f994f777d17cc5dfcdb6/systems/sensors/image_io_internal.h#L122)):*
> ```objc
>       }
>     }
>     dest -= 2 * width * dest_channels;
> ```

BTW, took me a while to realize you need to go two lines up from the end of the next line to the top of the previous line. Consider putting a note here if you think it's worth it.
___
*[`systems/sensors/image_io_internal.cc` line 68 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20448#-Ni64yloDTIYRT9ZFjHx:-Ni64yloDTIYRT9ZFjHy:bmhdk5c) ([raw file](https://github.com/RobotLocomotion/drake/blob/f277cb1479eae13d1d62f994f777d17cc5dfcdb6/systems/sensors/image_io_internal.cc#L68)):*
> ```cpp
>   const std::array<uint8_t, 2> header = ReadHeader<2>(input_any);
>   // https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format
>   if (header[0] == 0xff && header[1] == 0xd8) {
> ```

BTW, TIL, interesting!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20448)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Pull request merged**
