### PR TITLE
Resolved a couple AutoDiffX-induced issues in RBP.

### PR DESCRIPTION
**Pull request by liangfok**
Note that even with these changes RBP still doesn't support being templated on `AutoDiffX`. See https://github.com/RobotLocomotion/drake/issues/4897#issuecomment-275114870.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4903)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-:-KbL3Ye8wNQXSR1a1LFc:b-esv3jy)*

**Comment by amcastro-tri** [comment]
A small comment. :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 641 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-KbL4F6eg8O_lvhwiQ2G:-KbL4F6eg8O_lvhwiQ2H:b-djs4b6) ([raw file](https://github.com/robotlocomotion/drake/blob/d9d203d99088c11d3f5214ccaff41734ef689f3e/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L641)):*
> ```cpp
>         (-joint_stiffness * violation * (1 + joint_dissipation * velocity));
>     // The following two lines are necessary to support templating on AutoDiffX.
>     // See: https://github.com/RobotLocomotion/drake/issues/4897#issuecomment-275099824.
> ```

This is documented in `autodiff_overloads.h`. I would reference that documentation here. You can leave the github thread if you want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-:-KbL4R4lKJZyBi791qSu:b8dufz4)*

**Comment by liangfok** [comment]
@amcastro-tri, I addressed your comment. PTAL.

+@sammy-tri for platform review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 641 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-KbL4F6eg8O_lvhwiQ2G:-KbL68dO9Na8YbbfYtuy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d9d203d99088c11d3f5214ccaff41734ef689f3e/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L641)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This is documented in `autodiff_overloads.h`. I would reference that documentation here. You can leave the github thread if you want.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-:-KbL6AcmvXiyGFBAoA02:b3d5j49)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 641 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-KbL4F6eg8O_lvhwiQ2G:-KbLF1fA8nE28RQsRFH0:boclk3j) ([raw file](https://github.com/robotlocomotion/drake/blob/d9d203d99088c11d3f5214ccaff41734ef689f3e/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L641)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This comment is still way too overboard to the point of defectively obscuring the logic.  I think _no_ comment is best, but could live with some short end-of-line comment like "// Needed for ADL".  The using-std with ADL pattern is _pervasive_ throughout all of our code and I think commenting it everywhere, especially with 3 lines of comment, is an anti-pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4903)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/rigid_body_plant.cc, line 641 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-KbL4F6eg8O_lvhwiQ2G:-KbLQlDqYFW_3Xq3Cri_:b-ktx0pw) ([raw file](https://github.com/robotlocomotion/drake/blob/d9d203d99088c11d3f5214ccaff41734ef689f3e/drake/multibody/rigid_body_plant/rigid_body_plant.cc#L641)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment is still way too overboard to the point of defectively obscuring the logic.  I think _no_ comment is best, but could live with some short end-of-line comment like "// Needed for ADL".  The using-std with ADL pattern is _pervasive_ throughout all of our code and I think commenting it everywhere, especially with 3 lines of comment, is an anti-pattern.
</blockquote></details>

Done.

_prays for the next person who reads this code..._ :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4903)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4903#-:-KbLSPGr-GsLrWiSTt8M:bnfp4nl)*

**Pull request merged**
