### PR TITLE
[C-IRIS] Do not use all threads in cspace_free_polytope_test

### PR DESCRIPTION
**Pull request by hongkai-dai**
From slack thread https://drakedevelopers.slack.com/archives/C270MN28G/p1674142473151599

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18622)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by hongkai-dai — COMMENTED** [review]
When we do memcheck, it does memory check into Mosek solver, this significantly increases the computation time. I tested some of the optimization problem in cspace_free_polytope_test.cc, that running the program in the debug mode, without memcheck the Mosek solver time is about 1 second, with memcheck it takes about 1500 seconds. I am surprised that memcheck would slow down the computation by this much.

@jwnimmer-tri I don't think it makes sense to run memcheck into Mosek optimizer. Is it possible to run memcheck only on Drake code, but not into Mosek's code?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18622#-:-NMC81LZ7UjfdSYvbpJD:bajo81b)* status: needs at least one assigned reviewer, missing label for release notes

**Comment by jwnimmer-tri** [comment]
> Is it possible to run memcheck only on Drake code, but not into Mosek's code?

I don't know.  If Mosek and Drake pass memory back and forth to each other, it's probably not possible.

Typically, we never run memcheck on tests that use Mosek.  Adding `mosek_test_tags()` to the build rule for the test adds the tag "mosek" ...

https://github.com/RobotLocomotion/drake/blob/8a0f43bb5d652f4b76eda9e167812bf875c2d98b/tools/skylark/test_tags.bzl#L42-L43

... and our filter for Memcheck builds disables those tests ...

https://github.com/RobotLocomotion/drake/blob/8a0f43bb5d652f4b76eda9e167812bf875c2d98b/tools/dynamic_analysis/bazel.rc#L230

This test looks like maybe it has some Mosek-required code and some okay-without-Mosek code.  It would be better if you could split those test cases into different test programs, tag the mosek half as `mosek_test_tags()`, and remove the `solver.available()` guards.

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy, I will file a PR to split the test cases into two files, after PR #18627 is merged (which touches the same file).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18622#-:-NMCIdDQAUWuUZLVWKyW:btxajvf)* status: needs at least one assigned reviewer, missing label for release notes

**Pull request closed without merging**
