### PR TITLE
[py visualization] Disable some macOS bin-install tests

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See #21023.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21024)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release

**Comment by jwnimmer-tri** [comment]
Lol, I forgot the magic word!  Literally!

@drake-jenkins-bot mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

I was hoping to have a CI result before assigning review, but it looks like it'll be about an hour or two until that's ready.

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) :lgtm: x 2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21024#-:-NrHzJGg39fo_je8qTcU:bbyzcw6)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
