### PR TITLE
Removes dragway .cc files from libdrakeAutomotive to avoid ODR-violation.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6083)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-continuous-memcheck-asan please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6083#-:-Kjtq0Xd7ag9P-mR08uU:bnfp4nl)*

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6083#-:-Kju5ngBXhGQTIb6rYHL:b-4jbvnb)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please.
@drake-jenkins-bot linux-clang-continuous-memcheck-asan please.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6083)*

**Pull request merged**
