### PR TITLE
add AggregateLinearCosts.

### PR DESCRIPTION
**Pull request by hongkai-dai**
change AggregateQuadraticCosts to AggregateQuadraticAndLinearCosts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190#-:-MJEfN_r1gjpMvzbKIRU:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint with some initial thoughts.

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190#-:-MJSronX4zIjr77EOp-t:b3d5hzn)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.cc, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSqQs85Fy1l_t-qSDp:-MJSqQs85Fy1l_t-qSDq:b6chji3) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L12)):*
> ```cpp
> // coefficient.
> // @param vars_vec A vector containing all the variables shown up in the
> // quadratic cost.
> ```

This is misnamed (and the params listed here are incomplete).
___
*[solvers/aggregate_costs_constraints.cc, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSpcjT429DKs_i_qfe:-MJSpcjUEFZpXOrWjptA:b-kfyn60) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L14)):*
> ```cpp
> // quadratic cost.
> // @param var_to_index_map Records the index of a variable in vars_vec.
> // @param constant_cost The total constant term in the quadratic cost.
> ```

Some of these params are `[out]` and some are `[in,out]`, and it's very important to know which are which from the documentation.
___
*[solvers/aggregate_costs_constraints.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSqc0T6mcGEliixMn7:-MJSqc0T6mcGEliixMn8:b-99wpu4) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L19)):*
> ```cpp
>     Eigen::SparseMatrix<double>* Q_lower,
>     std::vector<symbolic::Variable>* quadratic_vars_vec,
>     std::map<symbolic::Variable::Id, int>* quadratic_var_to_index_map,
> ```

We are missing a useful abstraction here.

We have
```c++
vector<Variable> vars;
map<Variable, int> vars_index;
```

Those have a representation invariant that the two collections must match, which we are laboriously maintaining in a few places.

What if we had an abstraction instead
```c++
class VariableVector {
 public:
  int GetOrAdd(Variable);  // returns index, adds when not found
  VectorX<Variable> CopyToEigen();
 private:
  vector<Variable> vars_;
  map<Variable, int> vars_index_;
}
```

That would help with the labor of passing around two collections as in,out arguments that must be kept in sync across multiple methods.
___
*[solvers/aggregate_costs_constraints.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSoaQE4PHdYlur5z-k:-MJSoaQE4PHdYlur5z-l:b2vbkwq) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L25)):*
> ```cpp
>     double* constant_cost) {
>   std::vector<Eigen::Triplet<double>> Q_lower_triplets;
>   *constant_cost = 0;
> ```

It's super confusing for one of the helpers (quadratic) to zero this, but the other to just add into it.  Be consistent.  Probably the clearest choice is to have `[in,out] constant_cost` for the helpers and then zero it atop the public functions.
___
*[solvers/aggregate_costs_constraints.cc, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSnz-tE_zr-g1K1o1j:-MJSnz-tE_zr-g1K1o1k:b-nmlowd) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L160)):*
> ```cpp
>   for (int i = 0; i < static_cast<int>(quadratic_vars_vec.size()); ++i) {
>     (*quadratic_vars)(i) = quadratic_vars_vec[i];
>   }
> ```

This is the third copy of this vector-conversion boilerplate (two copies here; one in the above function), so we should factor it into a helper function for conciseness.

Alternatively, the "group the two map directions into a useful helper class" advice above.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.cc, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSqQs85Fy1l_t-qSDp:-MJT2y9XBK_Rp06IKdZF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is misnamed (and the params listed here are incomplete).
</blockquote></details>

Done.
___
*[solvers/aggregate_costs_constraints.cc, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSpcjT429DKs_i_qfe:-MJT2z1B-7cjmt38BXCW:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Some of these params are `[out]` and some are `[in,out]`, and it's very important to know which are which from the documentation.
</blockquote></details>

Done. Good call.
___
*[solvers/aggregate_costs_constraints.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSqc0T6mcGEliixMn7:-MJT87bx-aMjGdfJBpYC:b-sh6367) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We are missing a useful abstraction here.

We have
```c++
vector<Variable> vars;
map<Variable, int> vars_index;
```

Those have a representation invariant that the two collections must match, which we are laboriously maintaining in a few places.

What if we had an abstraction instead
```c++
class VariableVector {
 public:
  int GetOrAdd(Variable);  // returns index, adds when not found
  VectorX<Variable> CopyToEigen();
 private:
  vector<Variable> vars_;
  map<Variable, int> vars_index_;
}
```

That would help with the labor of passing around two collections as in,out arguments that must be kept in sync across multiple methods.
</blockquote></details>

Done.

Thanks! That is a really good idea!
___
*[solvers/aggregate_costs_constraints.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSoaQE4PHdYlur5z-k:-MJT3JZv-8i-YNgmB_xU:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's super confusing for one of the helpers (quadratic) to zero this, but the other to just add into it.  Be consistent.  Probably the clearest choice is to have `[in,out] constant_cost` for the helpers and then zero it atop the public functions.
</blockquote></details>

Done. Good call.
___
*[solvers/aggregate_costs_constraints.cc, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJSnz-tE_zr-g1K1o1j:-MJT8ApX2JJQ67R6TIEi:buu4hj5) ([raw file](https://github.com/robotlocomotion/drake/blob/a20778d0bee6a77bed584a498a63352af1c3dac8/solvers/aggregate_costs_constraints.cc#L160)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is the third copy of this vector-conversion boilerplate (two copies here; one in the above function), so we should factor it into a helper function for conciseness.

Alternatively, the "group the two map directions into a useful helper class" advice above.
</blockquote></details>

Done. I adopted the VariableVec advice above.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190#-:-MJTA_bFDurSe4McwWyG:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/aggregate_costs_constraints.cc, line 117 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJT94SS56mXTrbVTSis:-MJT94SS56mXTrbVTSit:b-ag3xfo) ([raw file](https://github.com/robotlocomotion/drake/blob/75b1c213abac84a3930b6ed843b957081e39a5b7/solvers/aggregate_costs_constraints.cc#L117)):*
> ```cpp
>                           double* constant_cost) {
>   std::vector<Eigen::Triplet<double>> linear_coeff_triplets;
>   // We first store all the variables in vars_vec, and convert it to VectorX
> ```

nit Typo `vars_vec` vs `var_vec`.

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190#-:-MJTExOmCNghJgbJ9Xb_:bi4se7j)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with a minor nit on testing

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190#-:-MJTed2K2ndTI_9ChODP:b-s6y95h)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/aggregate_costs_constraints.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJTcaju8SHa934y88hk:-MJTcaju8SHa934y88hl:b-9tn0vw) ([raw file](https://github.com/robotlocomotion/drake/blob/6b47f3e0f688eecd5c25b0d43cd4ced7037bbc3d/solvers/aggregate_costs_constraints.h#L1)):*
> ```objc
> #pragma once
> ```

BTW It's odd to see the name "constraints" in this file when there are no constraints.

Should this instead be focused on evaulators at some point?
___
*[solvers/test/aggregate_costs_constraints_test.cc, line 228 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJTeFBP3E5QnatiulFh:-MJTeFBP3E5QnatiulFi:b6lza83) ([raw file](https://github.com/robotlocomotion/drake/blob/6b47f3e0f688eecd5c25b0d43cd4ced7037bbc3d/solvers/test/aggregate_costs_constraints_test.cc#L228)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(
>       Eigen::MatrixXd(Q_lower),
>       Eigen::MatrixXd(Q_expected.triangularView<Eigen::Lower>())));
> ```

nit The upper triangle portion of `Q_expected` isn't used at all here.

Can you set those entries to `nan` to indicate as much?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14190)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

___
*[solvers/aggregate_costs_constraints.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJTcaju8SHa934y88hk:-MJTkJUe-r4KiWhjvFKk:bauxy8x) ([raw file](https://github.com/robotlocomotion/drake/blob/6b47f3e0f688eecd5c25b0d43cd4ced7037bbc3d/solvers/aggregate_costs_constraints.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW It's odd to see the name "constraints" in this file when there are no constraints.

Should this instead be focused on evaulators at some point?
</blockquote></details>

I plan to add `AggregateBoundingBoxConstraints` later, which takes the tightest bounds across all BoundingBoxConstraints.
___
*[solvers/test/aggregate_costs_constraints_test.cc, line 228 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14190#-MJTeFBP3E5QnatiulFh:-MJTkzkb8qR8Bzql89Qn:b-mzhn1v) ([raw file](https://github.com/robotlocomotion/drake/blob/6b47f3e0f688eecd5c25b0d43cd4ced7037bbc3d/solvers/test/aggregate_costs_constraints_test.cc#L228)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The upper triangle portion of `Q_expected` isn't used at all here.

Can you set those entries to `nan` to indicate as much?
</blockquote></details>

Done. I set them to 0.

**Pull request merged**
