### PR TITLE
ProjectMatToRotMatWithAxis should handle any joint bounds

### PR DESCRIPTION
**Pull request by hongkai-dai**
Previously it only handles joint bounds with [-2pi, 2pi]. Unfortunately our IRB140 robot has a joint exceeding these bounds.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5882)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki2A6t1aznS_SIg7iBf:b-sriflu)*

**Comment by RussTedrake** [comment]
:lgtm:  this seems much better.  i was expecting to see a few lines added to global IK, too, to support joint limits?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki2Bn94iB3WRMT0o9l-:b-c8oi0p)*

**Comment by hongkai-dai** [comment]
Done. Modified the joint limit in global IK test, such that the joint bounds exceed 2pi.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki2CMGySSvIARNfZOdI:b-m6f6fx)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review please.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki2Fvh8GdwJScNvZX86:b-1zm1j3)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/rotation_matrix.h, line 325 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5X_8sTYNDak7HMdFB:-Ki5X_8t36tTx7YgXKhl:b-ag5l7x) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/math/rotation_matrix.h#L325)):*
> ```objc
>   Scalar alpha =
>       atan2(-(M.transpose() * A * A).trace(), (A.transpose() * M).trace());
>   Scalar theta;
> ```

Variables should be initialized at declaration (obviously I missed this last time).
https://google.github.io/styleguide/cppguide.html#Local_Variables

---

*[drake/math/test/rotation_matrix_test.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5XenRTGo6WDyRIhfh:-Ki5XenRTGo6WDyRIhfi:b-up947d) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/math/test/rotation_matrix_test.cc#L92)):*
> ```cpp
>   const double R_error = (R - M).squaredNorm();
>   const int kNumAngles = 100;
>   double theta_lb, theta_ub;
> ```

Variables should be initialized at declaration.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test_util.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5Ymf2XE5DwUzDRc5D:-Ki5Ymf3FkAICCYAOkkU:b-jl9p4b) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/multibody/dev/test/global_inverse_kinematics_test_util.cc#L35)):*
> ```cpp
>   AddFlatTerrainToWorld(rigid_body_tree.get());
>   // Manually change the joint limits.
>   rigid_body_tree->joint_limit_min(6) = -2.1 * M_PI;
> ```

BTW That's a pretty big change from -π/2 (well, -175 degree).  This doesn't affect anything else later in the tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki5jDn5PkxvLZU8GEdd:b-s794vx)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/rotation_matrix.h, line 325 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5X_8sTYNDak7HMdFB:-Ki67MKFxDf5kR4EzZHx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/math/rotation_matrix.h#L325)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Variables should be initialized at declaration (obviously I missed this last time).
https://google.github.io/styleguide/cppguide.html#Local_Variables
</blockquote></details>

Done.

---

*[drake/math/test/rotation_matrix_test.cc, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5XenRTGo6WDyRIhfh:-Ki67UsRN7t48hbRKPS6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/math/test/rotation_matrix_test.cc#L92)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Variables should be initialized at declaration.
</blockquote></details>

Done.

---

*[drake/multibody/dev/test/global_inverse_kinematics_test_util.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5Ymf2XE5DwUzDRc5D:-Ki67XlYzu8dYxtl7dR2:b-u9gblr) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/multibody/dev/test/global_inverse_kinematics_test_util.cc#L35)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW That's a pretty big change from -π/2 (well, -175 degree).  This doesn't affect anything else later in the tests?
</blockquote></details>

I ran `global_inverse_kinematics_test` and `global_inverse_kinematics_reachable_test`, and they are both OK. The infeasible case is still infeasible. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/rotation_matrix.h, line 325 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5X_8sTYNDak7HMdFB:-Ki6QbNn1eTT03xYD8Tf:bocxtk7) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/math/rotation_matrix.h#L325)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/rotation_matrix.h, line 325 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-Ki5X_8sTYNDak7HMdFB:-Ki6WOi3SvNsh-ewp1ID:b-ifsslq) ([raw file](https://github.com/robotlocomotion/drake/blob/6d8523ad58c540d1cd39e37bc9f171f906e8268e/drake/math/rotation_matrix.h#L325)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't see the change?
</blockquote></details>

Done. I pushed to the wrong branch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki7D674nBoDxyIbKEjb:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5882#-:-Ki7DSJqlgQaqcUuuZzE:b-l70wzf)*

**Pull request merged**
