### PR TITLE
Do not use BLAS vendored with SNOPT/Fortran

### LINKED ISSUE #11501: Do not use BLAS version vendored with SNOPT
Relates https://github.com/RobotLocomotion/drake/pull/11489#pullrequestreview-239132919. See https://github.com/RobotLocomotion/snopt/blob/2015-02-26/csrc/snblas.c for instance.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #11501.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11505)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-debug please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
I think the issue is somehow with the remote cache.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

**Comment by jamiesnape** [comment]
> I think the issue is somehow with the remote cache.

Yes. How frustrating.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
We don't have macOS SNOPT/Fortran yet, but it passes locally.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Pull request merged**
