### PR TITLE
Adds suppression of deprecation warnings when compiling SWIG bindings.

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2657.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2674)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review since he has the most context and this is such a simple change.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2674#-:-KLMZGiGgDm9s6kX-Cmu:-49488204)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/swig/CMakeLists.txt, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2674#-KLM_iNhpytcq8xVQ47a:-KLM_iNiWWu98NrEjA_H:1543408186) ([raw file](https://github.com/robotlocomotion/drake/blob/f26df0a694b35bbc5356f85601671ad047dcaf33/drake/bindings/swig/CMakeLists.txt#L16)):*
> ```CMake
> if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
>   # The autodiff.i in swig has for-loop variable warnings.
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-sign-compare -Wno-deprecated-declarations")
> ```

By adding the new flag here, the comment on the prior line no longer makes sense.

I recommend adding a second new line, with its own comment, explaining why we have to suppress this warning in particular.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2674)*

**Comment by liangfok** [comment]
Ready for another round of review.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/swig/CMakeLists.txt, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2674#-KLM_iNhpytcq8xVQ47a:-KLMb786bl6EbTMPUvpt:-1620626842) ([raw file](https://github.com/robotlocomotion/drake/blob/f26df0a694b35bbc5356f85601671ad047dcaf33/drake/bindings/swig/CMakeLists.txt#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> By adding the new flag here, the comment on the prior line no longer makes sense.
> 
> I recommend adding a second new line, with its own comment, explaining why we have to suppress this warning in particular.
</details>
Done. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2674#-:-KLMb51XiWfUkATIJ5OO:-1455727467)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2674#-:-KLMbRL3aGkvT7Jz5KLj:1417088721)*

**Pull request merged**
