### PR TITLE
py multibody math: Add repr() for spatial vectors

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
py math:
- Add slight adjustment to logic / imports
- Add note about where `__repr__` is defined

Motivated by doing some math for haptic stuff
Following / adapting pattern from #14993

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri might you be up for reviewing, when you have time?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112#-:-NERLtmh6VNmvgv4Ewuw:b-adjvpd)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review.

+(release notes: feature) 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112#-:-NERTyoUBDVsTY9zbegF:b-ol6mf)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/multibody/test/math_test.py` line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18112#-NERTMBh1Ml0yCZjv5oi:-NERTMBi2Zc_9PmJ98Dx:b-m26aic) ([raw file](https://github.com/robotlocomotion/drake/blob/359a130ea98d67ae9c011759e3bb98ac24962606/bindings/pydrake/multibody/test/math_test.py#L110)):*
> ```Python
>             globals_ = {}
>             locals_ = {base_name: cls}
>             roundtrip = eval(repr(original), globals_, locals_)
> ```

Why is it important to place demands on the `locals` and `globals` used by `eval`?  (What kind of implementation defect(s) is it guarding against?)  I haven't yet been able to figure it out.

As we add uses of AutoDiffXd, Expression, numpy, etc. to the repr we're just going to need to keep adding to this list, creating a maintenance headache for (maybe?) no gain.

Or if there is a benefit, perhaps a comment here would help explain the reasoning.
___
*[`bindings/pydrake/multibody/test/math_test.py` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18112#-NERRqpwDS0gGCzmRbST:-NERRqpwDS0gGCzmRbSU:b-63xx5u) ([raw file](https://github.com/robotlocomotion/drake/blob/359a130ea98d67ae9c011759e3bb98ac24962606/bindings/pydrake/multibody/test/math_test.py#L112)):*
> ```Python
>             roundtrip = eval(repr(original), globals_, locals_)
>             # TODO(jwnimmer-tri) Once IsExactlyEqualTo is bound, we can easily
>             # check the contents of the roundtrip object here.
> ```

nit There is no such function `IsExactlyEqualTo` for spatial vectors.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/multibody/test/math_test.py` line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18112#-NERTMBh1Ml0yCZjv5oi:-NESUGmy1Fi5u3te8iuk:b-c28wv7) ([raw file](https://github.com/robotlocomotion/drake/blob/359a130ea98d67ae9c011759e3bb98ac24962606/bindings/pydrake/multibody/test/math_test.py#L110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why is it important to place demands on the `locals` and `globals` used by `eval`?  (What kind of implementation defect(s) is it guarding against?)  I haven't yet been able to figure it out.

As we add uses of AutoDiffXd, Expression, numpy, etc. to the repr we're just going to need to keep adding to this list, creating a maintenance headache for (maybe?) no gain.

Or if there is a benefit, perhaps a comment here would help explain the reasoning.
</blockquote></details>

Done.
Was namely concerned about having an unused variable that `flake8` would complain about, and was being lazy :sweat_smile: 
However, I just added the workaround.
___
*[`bindings/pydrake/multibody/test/math_test.py` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18112#-NERRqpwDS0gGCzmRbST:-NESUQXA7hIU_qvm_6T0:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/359a130ea98d67ae9c011759e3bb98ac24962606/bindings/pydrake/multibody/test/math_test.py#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit There is no such function `IsExactlyEqualTo` for spatial vectors.
</blockquote></details>

Done. Oops!

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112#-:-NESUcSB3Qb96xRZBvNY:btfqagw)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`bindings/pydrake/multibody/test/math_test.py` line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18112#-NESehG9BzqMqQ3rPjeP:-NESehG9BzqMqQ3rPjeQ:b-jpqt3v) ([raw file](https://github.com/robotlocomotion/drake/blob/38630a3ed8148a223b6861ccaee56e79249817bc/bindings/pydrake/multibody/test/math_test.py#L28)):*
> ```Python
>     def suppress_flake8_F401(self):
>         # These symbols are used in `eval()` for testing `repr()` roundtrip.
>         # N.B. Adding `#noqa` or `#noqa: F401` did not silence flake8==3.7.9.
> ```

nit Drake doesn't run flake8 in CI though, does it?  Or in other words, if I delete this method nothing fails.  Thus, it's dead code and should be removed.

Alternatively, this method could be renamed to `def test_default_aliases()` and then it wouldn't be dead code.  It would be a somewhat of a redundant test (the `cpp_template.py` is unlikely to be broken without us otherwise noticing) but I can live with a few lines of boring extra bindings tests if you think keeping it around is helpful.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`bindings/pydrake/multibody/test/math_test.py` line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18112#-NESehG9BzqMqQ3rPjeP:-NEa3cOS-yS-dKdoClp4:bn66v6f) ([raw file](https://github.com/robotlocomotion/drake/blob/38630a3ed8148a223b6861ccaee56e79249817bc/bindings/pydrake/multibody/test/math_test.py#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Drake doesn't run flake8 in CI though, does it?  Or in other words, if I delete this method nothing fails.  Thus, it's dead code and should be removed.

Alternatively, this method could be renamed to `def test_default_aliases()` and then it wouldn't be dead code.  It would be a somewhat of a redundant test (the `cpp_template.py` is unlikely to be broken without us otherwise noticing) but I can live with a few lines of boring extra bindings tests if you think keeping it around is helpful.
</blockquote></details>

Done. Went for `test_default_aliases`.
At some point, I'd like to enable some simple version of `flake8` (if not too much overhead). I'm thinking to do it for Anzu at some point.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18112#-:-NEahrsKEVKPx2XQQgui:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
