### PR TITLE
resolving new issues found by massively parallel builds on drake005

### PR DESCRIPTION
**Pull request by RussTedrake**

### CODE REVIEW

**Comment by RussTedrake** [comment]
@rdeits -- please take a look at the failing tests on drake005.  apart from the maxROA (a separate issue), every one of them appears to crash right after loading a java class -- either mosek or lcm.  not sure what to make of that, but I wonder if it's correlated with #1239?

**Comment by rdeits** [comment]
The drake005 failures are all segfaults, which shouldn't be related to #1239 (since that just throws matlab errors). 

But I notice that drake005 is using java 1.7, while drake006 is using java 1.6. Perhaps that's a clue? I'll keep looking.

**Comment by RussTedrake** [comment]
Keep in mind this is doing massively parallel stuff -- so i wonder if two matlab instances are hitting some java cache file on disk at the same time or something?

**Comment by rdeits** [comment]
I can't find anything through some quick googling, and I don't know anything about the matlab java internals. Just how massively parallel is this build?

**Comment by RussTedrake** [comment]
24 cores

**Comment by RussTedrake** [comment]
this is only better than the current standard.  @rdeits recommended i merge.  will do so manually (because of the merge conflict).

**Pull request merged**
