### PR TITLE
Add new closed-form pose test using data from LabelFusion.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This adds a simple closed-form pose test using a very small cropped point cloud from LabelFusion, to address #6655.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6848)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

**Comment by kunimatsu-tri** [comment]
I've just left one comment. PTAL. 
Also, `linux-xenial-clang-bazel-experimental-debug` has failed.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-KrftLyf74J6ViBN223R:-KrftLyf74J6ViBN223S:b56n9zb) ([raw file](https://github.com/robotlocomotion/drake/blob/7c0fddcd071d3eeff3118ce5bc8c8fabb4f8ef35/drake/perception/estimators/dev/test/articulated_icp_test.cc#L73)):*
> ```cpp
> };
> 
> class ArticulatedIcpTest : public TestWithParam<ObjectTestType> {
> ```

BTW, it's good to know about this functionality!

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-KrfsOdcbD0geH42Cj9P:-KrfsOdcbD0geH42Cj9Q:b8i1vu3) ([raw file](https://github.com/robotlocomotion/drake/blob/7c0fddcd071d3eeff3118ce5bc8c8fabb4f8ef35/drake/perception/estimators/dev/test/articulated_icp_test.cc#L192)):*
> ```cpp
>   for (int i = 0; i < 5; ++i) {
>     VectorXd q = q_init_;
>     q(0) += 0.1 * i;
> ```

Why does this change happen? I'm asking just because it's a bit hard to track.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-:-Krg1owf9el0JI-1k-px:b-12lbqj)*

**Comment by EricCousineau-TRI** [comment]
Yup, was due to a test timeout. Added some simple down-sampling to lower the test time. Thanks!

---

Review status: 13 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-KrftLyf74J6ViBN223R:-Krgfw58mjOKkNkUV8hV:bgby5ha) ([raw file](https://github.com/robotlocomotion/drake/blob/7c0fddcd071d3eeff3118ce5bc8c8fabb4f8ef35/drake/perception/estimators/dev/test/articulated_icp_test.cc#L73)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, it's good to know about this functionality!
</blockquote></details>

BTW Yeah, but it's really clunk to have to use templates to specify parameters :(
(Andres had pointed that out)

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-KrfsOdcbD0geH42Cj9P:-Krgg1MtFB7RU4WaAy8w:be9cbw1) ([raw file](https://github.com/robotlocomotion/drake/blob/7c0fddcd071d3eeff3118ce5bc8c8fabb4f8ef35/drake/perception/estimators/dev/test/articulated_icp_test.cc#L192)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Why does this change happen? I'm asking just because it's a bit hard to track.
</blockquote></details>

Clarified with a comment, and tried to make persistence more clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-:-KrghJNolE-9Q-VRiJev:b88nx57)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-KrftLyf74J6ViBN223R:-KrkJJ7nkjF3OwNIrn-X:b-v2y5ji) ([raw file](https://github.com/robotlocomotion/drake/blob/7c0fddcd071d3eeff3118ce5bc8c8fabb4f8ef35/drake/perception/estimators/dev/test/articulated_icp_test.cc#L73)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Yeah, but it's really clunk to have to use templates to specify parameters :(
(Andres had pointed that out)
</blockquote></details>

BTW, haha, good point, that's true. 

---

*[drake/perception/estimators/dev/test/articulated_icp_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-KrfsOdcbD0geH42Cj9P:-KrkKAjeL4s3o1v29Eo3:btq517o) ([raw file](https://github.com/robotlocomotion/drake/blob/7c0fddcd071d3eeff3118ce5bc8c8fabb4f8ef35/drake/perception/estimators/dev/test/articulated_icp_test.cc#L192)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Clarified with a comment, and tried to make persistence more clear.
</blockquote></details>

BTW, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-:-KrkKFf-GLjeQp8DH1WA:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for platform review of non-dev portion (`vtk.bzl`), please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-:-Krle6Uvg5geVqFFr2R1:b-ffoclb)*

**Comment by soonho-tri** [comment]
Platform :lgtm: for non-dev portion.

---

Reviewed 1 of 16 files at r1, 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6848#-:-KrllrdXpA4AoCyrXU0v:bb0qfh1)*

**Pull request merged**
