### PR TITLE
[workspace] Disable drake-visualizer on macOS

### LINKED ISSUE #16944: Remove drake-visualizer on macOS
Per #16215, now that 2022-04-01 has passed we should remove drake-visualizer on macOS.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #16944.

Tested locally on macsim:
```
macsim:drake jwnimmer$ bazel run //tools:drake_visualizer
...
INFO: Build completed successfully, 1 total action
error: drake-visualizer was disabled in this build of Drake
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16945)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

+@svenevs for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> bazel build //tools:drake_visualizer succeeds on mac, run is what fails.  If making that fail is easy then probably build should fail too, otherwise it's not very important.

I don't understand -- maybe there is a typo in the above?

We need `bazel build //...` to pass on mac.  We can't have `bazel build //tools:drake_visualizer` fail to build.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16945#-:-N-V7cvR9bKI_PEcvFjW:b-fg2ym2)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[setup/mac/binary_distribution/install_prereqs.sh, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16945#-N-V5JomBZut4U3jFGG_:-N-V7pKxAi9TMo_-Dbmx:b-mm4il6) ([raw file](https://github.com/robotlocomotion/drake/blob/e56a0da0427b7d76aa37274bd05dc736b347ab66/setup/mac/binary_distribution/install_prereqs.sh#L68)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

BTW I get the impression that this is so it gets deleted for current users who have already had it installed, is that right?
</blockquote></details>

Yes, this is to kindly free up disk space (and maybe remove the opportunity for users to accidentally use our unmaintained VTK 8 for something in earnest).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

+@sammy-tri for platform review per schedule, please.

**Review by svenevs — COMMENTED** [review]
> I don't understand -- maybe there is a typo in the above?
> We need bazel build //... to pass on mac.  We can't have bazel build //tools:drake_visualizer fail to build.

Nope, just a misunderstanding / oversight -- agreed it needs to be able to build!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16945#-:-N-VKb71E6rLV4pEC92r:bn5tdi4)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[setup/mac/binary_distribution/install_prereqs.sh, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16945#-N-V5JomBZut4U3jFGG_:-N-VKjxx3avrbcQD2Lq9:bvn2wzx) ([raw file](https://github.com/robotlocomotion/drake/blob/e56a0da0427b7d76aa37274bd05dc736b347ab66/setup/mac/binary_distribution/install_prereqs.sh#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, this is to kindly free up disk space (and maybe remove the opportunity for users to accidentally use our unmaintained VTK 8 for something in earnest).
</blockquote></details>

OK makes sense!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16945#-:-N-_-_cF6mJl2xdpi1VU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),svenevs (waiting on @jwnimmer-tri)

**Pull request merged**
