### PR TITLE
Fix NLP parsing BoundingBoxConstraint

### LINKED ISSUE #3879: BoundingBoxConstraint is parsed incorrectly in snopt_solver and and ipopt_solver
This caused the problem in https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-continuous-matlab-open-source/changes

Quick summary: if the bounding box constraint is imposed for a list of variables
```
prog.AddBoundingBoxConstraint(lb, ub, {x(0), x(1), x(2)});
```
In `snopt_solver.cc` and `ipopt_solver.cc`, what it actually imposes is
```
lb(0) <= x(0) <= ub(0)
lb(0) <= x(1) <= ub(0)
lb(0) <= x(2) <= ub(0)
```
Namely, only `lb(0), ub(0)` are used, `lb(1), lb(2), ub(1), ub(2)` are not used.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #3879

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3880)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for feature review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-:-KUiseDedKp-5-zUpRKY:b-an7kl2)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-:-KUjFohmmYvMdKmrqKQM:buasbda)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-:-KUqyqJOv8_SjftSGT0U:bnfp4nl)*

**Comment by sherm1** [comment]
A few non-blocking comments, PTAL. Then, :lgtm:.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/ipopt_solver.cc, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-KUsDkXc8lTEV6Mx6CE2:-KUsDkXc8lTEV6Mx6CE3:blfjmpi) ([raw file](https://github.com/robotlocomotion/drake/blob/139262226f794ea38258deef5ec95da257930b51/drake/solvers/ipopt_solver.cc#L230)):*
> ```cpp
>           x_l[idx] = std::max(lower_bound(var_count), x_l[idx]);
>           x_u[idx] = std::min(upper_bound(var_count), x_u[idx]);
>           var_count++;
> ```

BTW, prefer `++var_count` (optional); here and in nlopt & snopt.

---

*[drake/solvers/test/mathematical_program_test.cc, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-KUsC6j-K6VEGOnRF4cD:-KUsC6j-K6VEGOnRF4cE:b9f5aml) ([raw file](https://github.com/robotlocomotion/drake/blob/139262226f794ea38258deef5ec95da257930b51/drake/solvers/test/mathematical_program_test.cc#L112)):*
> ```cpp
> }
> 
> GTEST_TEST(testMathematicalProgram, boundingboxTest) {
> ```

BTW, these are class names so should be capitalized.

---

*[drake/solvers/test/mathematical_program_test.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-KUsCal6Dw7eTZpF29AT:-KUsCal6Dw7eTZpF29AU:b-mkpcnm) ([raw file](https://github.com/robotlocomotion/drake/blob/139262226f794ea38258deef5ec95da257930b51/drake/solvers/test/mathematical_program_test.cc#L121)):*
> ```cpp
>                                 {x(1), x(3)});
>   prog.AddBoundingBoxConstraint(Vector3d(-1, -0.5, -3), Vector3d(2, -0.2, -0.1),
>                                 {x(0), x(1), x(2)});
> ```

BTW, I see x(1) gets bounds both times but that the tighter ones get used. Might want to mention that in a comment here to make that clear. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-:-KUsE43w0L_NCgeVPOVR:b-kv5c53)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/ipopt_solver.cc, line 230 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-KUsDkXc8lTEV6Mx6CE2:-KUsGL09WmFrQhVPxUIj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/139262226f794ea38258deef5ec95da257930b51/drake/solvers/ipopt_solver.cc#L230)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, prefer `++var_count` (optional); here and in nlopt & snopt.
</details>
Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-KUsC6j-K6VEGOnRF4cD:-KUsGMJHQ1Zius2ti53T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/139262226f794ea38258deef5ec95da257930b51/drake/solvers/test/mathematical_program_test.cc#L112)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, these are class names so should be capitalized.
</details>
Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 121 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-KUsCal6Dw7eTZpF29AT:-KUsGMx-Nd_EazLK96ik:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/139262226f794ea38258deef5ec95da257930b51/drake/solvers/test/mathematical_program_test.cc#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I see x(1) gets bounds both times but that the tighter ones get used. Might want to mention that in a comment here to make that clear. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3880)*

**Comment by sherm1** [comment]
:lgtm: -- ready to merge.

---

Reviewed 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3880#-:-KUslazDYACd9_a3cpFu:btme7u5)*

**Pull request merged**
