### PR TITLE
support systems with no inputs in dircol trajectory optimization

### PR DESCRIPTION
**Pull request by RussTedrake**
this sounds silly, but we can still optimize over initial conditions, etc.  this is the use case we care about (initially) for automotive.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5858)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-:-Khw--y81KDPUL1We9zr:b-81zjv5)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-:-KhwoMHSlGb2v_zW08Ta:bozh2sc)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please.

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-:-KhxGXGH57IIXGXqKShS:bvi7gqa)*

**Comment by sherm1** [comment]
:lgtm: except for one minor style guide fix needed, ptal.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-KhxIO1fA1WrzKdDUxL7:-KhxIO1fA1WrzKdDUxL8:bijlkef) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccbf807ad72faf9cc258f10751c96c56a6ae65f/drake/systems/trajectory_optimization/direct_collocation_constraint.cc#L95)):*
> ```cpp
>   // Set derivatives of all parameters in the context to zero (but with the
>   // correct size).
>   int num_gradients = 1 + 2 * num_states_ + 2 * num_inputs_;
> ```

BTW member access has to be through accessors -- see below.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-KhxI9bUdBwRG8kqUk4f:-KhxI9bUdBwRG8kqUk4g:b-b9x8i4) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccbf807ad72faf9cc258f10751c96c56a6ae65f/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L52)):*
> ```objc
> 
>   int num_states_;
>   int num_inputs_;
> ```

BTW [per styleguide](https://google.github.io/styleguide/cppguide.html#Access_Control) data members must be private. Please add accessors to allow derived classes to access these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-:-KhxIhysmGxvxUlRaQfa:b-i1dvq4)*

**Comment by RussTedrake** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-KhxIO1fA1WrzKdDUxL7:-Ki-Wcm-xJ8VGpJZPTOy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccbf807ad72faf9cc258f10751c96c56a6ae65f/drake/systems/trajectory_optimization/direct_collocation_constraint.cc#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW member access has to be through accessors -- see below.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_collocation_constraint.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5858#-KhxI9bUdBwRG8kqUk4f:-Ki-VRzt1BxC83cKSS9b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccbf807ad72faf9cc258f10751c96c56a6ae65f/drake/systems/trajectory_optimization/direct_collocation_constraint.h#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW [per styleguide](https://google.github.io/styleguide/cppguide.html#Access_Control) data members must be private. Please add accessors to allow derived classes to access these.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5858)*

**Pull request merged**
