### PR TITLE
Document a gotcha in input_port.Eval's argument.

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21166)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@xuchenhan-tri (tomorrow's platform reviewer)
+(status: single reviewer ok) 
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21166#-:-NtN3r0q2dkkB2Qmnn_C:b-blezp)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
Let me propose +@sherm1 for feature review -- he might want to specifically guide the comment language we use here.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with a suggestion

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21166#-:-NtOPQpGB4xVnx2NXdOd:bqp6mfs)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`systems/framework/input_port.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21166#-NtOOKIEBMJBUtpZ7uFN:-NtOOKIEBMJBUtpZ7uFO:bmdru0w) ([raw file](https://github.com/RobotLocomotion/drake/blob/d50615a507d5e0e856dffe094db435649cbce4b5/systems/framework/input_port.h#L64)):*
> ```objc
>   If the value is not up-to-date it must also be a subcontext of a Diagram
>   that contains the corresponding output port so that that port can be
>   evaluated.
> ```

BTW Consider adding an `@param context` instead of or as well as the warning. Something like
```
@param context A Context for this System that also contains the value source for this input port. If that source is an output port of another System then `context` must be a subcontext of the Diagram that contains both this System and the one providing the output port.
```

(If the port has a fixed value in its own Context then it would be OK to use a standalone one.)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21166#-:-NtRz0bQ-9U8aNiCg8Ro:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

**Pull request merged**
