### PR TITLE
ports known issue logic over from the build server scripts

### PR DESCRIPTION
**Pull request by RussTedrake**
in preparation for the jenkins server having matlab.  @jamiesnape -- you'll obviously still need to integrate this, but it should get you close.

### CODE REVIEW

**Comment by billhoffman** [comment]
@RussTedrake now it is crashing for us: https://drake-cdash.csail.mit.edu/testDetails.php?test=8516&build=1871

**Comment by RussTedrake** [comment]
what changed?

**Comment by billhoffman** [comment]
No idea.  :)

**Comment by RussTedrake** [comment]
this passed all tests that were expected to pass.  @jamiesnape -- is it helpful for the build server matlab integration?  if yes, i can merge.  if no, then i almost certainly will not.

**Comment by jamiesnape** [comment]
I will look over the code and let you know. I am more than likely to port some of the code or functionality to CMake or Python.

**Comment by RussTedrake** [comment]
ok.  will close the PR, but you know where to look.

**Pull request closed without merging**
