### PR TITLE
Update SapFrictionConeConstraint to use new SapConstraint APIs 

### PR DESCRIPTION
**Pull request by amcastro-tri**
Follow up to #19402, this PR implements the SAP contact constraints in terms of the newly introduced APIs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19429)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-:-NVjyolpArHTKEbzSB2Y:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a few small nits. +@ggould-tri for platform review, please.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-:-NW3IYeaBjcPmqIPn99s:beoiuuy)* status: 5 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.h` line 86 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2mMD7E-QT6uTKPrnr:-NW2mMD7E-QT6uTKPrns:b-3hd2rl) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L86)):*
> ```objc
>   //  2. Sliding: -mu_hat * yr < yn && yn < yn < yr/mu
>   //  3. No contact: yn < -mu * yr
>   int region_{-1};
> ```

nit: consider using an enum class to give this parameter strong typing. It will give more semantic meaning in the places in the places you currently use the parameter and have a comment to inform what the int means. It would also make it less likely to have a bug where the wrong region int is used.
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.h` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2od006rJN13z6mFcu:-NW2od006rJN13z6mFcv:bk3cv77) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L88)):*
> ```objc
>   int region_{-1};
> 
>   Vector3<T> y_;         // Un-projected impulse y = −R⁻¹⋅(vc−v̂)
> ```

nit: consider initializing these all to NANs.
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.h` line 250 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2pab_DFhBDUPk98Ma:-NW2pab_DFhBDUPk98Mb:bkpy21b) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L250)):*
> ```objc
>    defined and follow the same equations presented in [Castro et al., 2021]
>    where regular norms are simply replaced by soft norms. */
>   static T SoftNorm(const Eigen::Ref<const VectorX<T>>& x) {
> ```

nit: SoftNorm seems like a generic enough operation to live outside of this specific class. Consider a TODO to consolidate math helper functions into a utility location.
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.h` line 261 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2s0SI01BpIqjiCXkP:-NW2s0SI01BpIqjiCXkQ:bqh1z9j) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L261)):*
> ```objc
>       1. Stiction: yr < mu * yn
>       2. Sliding: -mu_hat * yr < yn && yn < yn < yr/mu
>       3. No contact: yn < -mu * yr */
> ```

nit: the comment ending on the same line makes reading the math a bit confusing.



_Suggestion:_
```objc
      3. No contact: yn < -mu * yr
  */
```
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.cc` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2xg-U9qC5RApX9ACl:-NW2rLQH3qESs9-VmVkU:b-6qnms7) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L54)):*
> ```cpp
>     const T& mu, const T& Rt, const T& Rn, const T& vn_hat) {
>   parameters_.mu = mu;
>   parameters_.mu_tilde = mu * sqrt(Rt / Rn);
> ```

nit: missing `using std::sqrt`.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-:-NW3hQKe1iiDovfr9X4r:bnfp4nl)* status: 7 unresolved discussions

___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.cc` line 159 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW3cm7F23L-yeyZ-W2p:-NW3cm7F23L-yeyZ-W2q:bebi5rt) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L159)):*
> ```cpp
>       break;
>     }
>   }
> ```

minor:  The silent fallthrough here on an invalid region value is not great.  This should have a default clause or other can't-happen-error handling to ensure fail-fast if the region is not one of the allowed magic numbers.
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.cc` line 231 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW3dCdg5qLul43vwazk:-NW3dCdg5qLul43vwazl:b-jk3vsf) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L231)):*
> ```cpp
>       break;
>     }
>   }
> ```

minor:  Also a silent fallthrough without error.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19429)* status: 1 unresolved discussion

___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.h` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2od006rJN13z6mFcu:-NW4Ndg_0pe7q5ri5aTj:b-6xlczo) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L88)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: consider initializing these all to NANs.
</blockquote></details>

I am leaving them uninitialized on purpose. I added comment in the ctor.
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.h` line 250 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW2pab_DFhBDUPk98Ma:-NW4NmOsEXOh_xxpp2Q8:bfhv1po) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L250)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: SoftNorm seems like a generic enough operation to live outside of this specific class. Consider a TODO to consolidate math helper functions into a utility location.
</blockquote></details>

not, really until we have more use cases. 
___
*[`multibody/contact_solvers/sap/sap_friction_cone_constraint.cc` line 159 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19429#-NW3cm7F23L-yeyZ-W2p:-NW4QRIf0wtlWeOK8P3y:bpggscl) ([raw file](https://github.com/RobotLocomotion/drake/blob/47439c407ccffd3844c9e362e3303f5cd8e591fc/multibody/contact_solvers/sap/sap_friction_cone_constraint.cc#L159)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The silent fallthrough here on an invalid region value is not great.  This should have a default clause or other can't-happen-error handling to ensure fail-fast if the region is not one of the allowed magic numbers.
</blockquote></details>

using an enum now.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19429)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),joemasterjohn

**Pull request merged**
