### PR TITLE
[geometry/dev] add HttpServiceCurl implementation

### LINKED ISSUE #15916: RenderRpc: Evaluate and select RPC protocol
Evaluate different RPC protocols and select the most promising one for the initial implementation. The decision can be revisited later on if needed.

### PR DESCRIPTION
**Pull request by svenevs**
Cannot merge until

- [X] #16702 is merged.
- [X] This branch is rebased.

Closes #15916.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@zachfang for review please.  To keep things manageable, this takes most of the code from `RenderClient` and moves it to this `HttpServiceCurl`, however removing that code from `RenderClient` will happen in a followup PR -- this is just adding the `HttpService` and the tests that can be performed without a server.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723#-:-Mx_82dg445gIlLWXV7U:b-xw2c9g)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[geometry/render/dev/http_service_curl.cc, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_8_fu0LdDiD8u8TN0:-Mx_8_fu0LdDiD8u8TN1:b-xv6f7) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L180)):*
> ```cpp
>   static drake::never_destroyed<std::atomic<int64_t>> global_temp_id;
>   return ++(global_temp_id.access());
> }
> ```

FYI this is similar to how things used to work, but not identical.  Previously, `RenderClient` would save server responses for scene `XYZ.gltf` in `XYZ.bin`, and then rename things to either `XYZ.png` or `XYZ.tiff` if successful, or try and read text from `XYZ.bin` before throwing an error in the failure case.

Since `HttpServiceCurl` is not aware of the API (`RenderClient` is what implements the client / server relationship), we use a scheme to create new file id's in the same way, but they do not necessarily correspond to `XYZ.gltf`.  This is why `HttpService::data_path` exists, to allow us to state where the file got saved to.
___
*[geometry/render/dev/http_service_curl.cc, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_9TJdEgicV-u60gju:-Mx_9TJdEgicV-u60gjv:bjbx10k) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L199)):*
> ```cpp
>    documentation in render_engine_gltf_client_factory.h */
>   static CURLcode ignored =
>       curl_global_init(CURL_GLOBAL_ALL | CURL_GLOBAL_ACK_EINTR);
> ```

FYI rather than tracking number of clients, [Jeremy said to do this instead](https://drakedevelopers.slack.com/archives/C02HMU7B15Y/p1646322552402929).  Those docs on `MakeRenderEngineGltfClient` do not exist (yet), they come in followup PR.  There will just be a mention that this is how we initialize, consumer applications also doing their own curl stuff need to know.
___
*[geometry/render/dev/http_service_curl.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_9pHE7vs3VC5SORIb:-Mx_9pHE7vs3VC5SORIc:b-sgh21w) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L234)):*
> ```cpp
>     if (headerlist != nullptr) curl_slist_free_all(headerlist);
>     curl_easy_cleanup(curl);
>   };
> ```

FYI this is new, before throwing an exception we can clean things up.  Not sure it's strictly necessary though... 
___
*[geometry/render/dev/http_service_curl.cc, line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_AABxABMuxmcCkO89:-Mx_AABxABMuxmcCkO8A:bex3xud) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L324)):*
> ```cpp
>     try {
>       fs::remove(bin_out_path);
>     } catch (...) {
> ```

I don't know if this is acceptable, the code just checks if the file has content.  If so, the returned `HttpResponse` passes "ownership" of the file back to the caller.  Otherwise, we delete it.  In the event that the file cannot be deleted though, I just ignore it.  Seems obnoxious to throw an error in that event (cannot delete a size zero file for mysterious reason).

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723)* status: 2 unresolved discussions, LGTM missing from assignee zachfang, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/http_service_curl.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_9pHE7vs3VC5SORIb:-Mx_BYzq4RUM5mcBHDkr:bxoaum7) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L234)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI this is new, before throwing an exception we can clean things up.  Not sure it's strictly necessary though... 
</blockquote></details>

Working, turning into blocking, on second look -- I am not sure that `headerlist` gets freed now because I define this too early (the capture happens before it is created).  Options:

1. We do not care about calling `curl_slist_free_all(headerlist)` / `curl_easy_cleanup(curl)` before throwing an exception.  If so I will just move that back to the end of the method.
2. We should do this before throwing an exception -- I will initialize the `headerlist` before the capture.

Let me know what you prefer.

**Review by zachfang — COMMENTED** [review]
Checkpoint. I think I went through most of the curl-related code changes except the curl callbacks. Will come back tomorrow.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723#-:-Mxbi3XXE2yxc2eE5tLD:bbl0v1b)* status: 4 unresolved discussions, LGTM missing from assignee zachfang, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-MxbUzfxEmZri1IkuUYa:b662476) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
> ```objc
>   explicit HttpServiceCurl(const std::string& temp_directory,
>                            const std::string& url, int32_t port, bool verbose);
>   ~HttpServiceCurl();
> ```

nit: should we put `= default` here as we have the empty destructor definition in the cc file.
___
*[geometry/render/dev/http_service_curl.cc, line 199 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_9TJdEgicV-u60gju:-MxbT_7W-3xJcX2U-QuG:b-gs94nn) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L199)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI rather than tracking number of clients, [Jeremy said to do this instead](https://drakedevelopers.slack.com/archives/C02HMU7B15Y/p1646322552402929).  Those docs on `MakeRenderEngineGltfClient` do not exist (yet), they come in followup PR.  There will just be a mention that this is how we initialize, consumer applications also doing their own curl stuff need to know.
</blockquote></details>

OK. Sounds good, thanks for the clarification.
___
*[geometry/render/dev/http_service_curl.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_9pHE7vs3VC5SORIb:-MxbfZ1t0Lz8YOwl1gIT:b-usxbww) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L234)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Sorry for spam. `CC=clang-9 CXX=clang++-9 bazel test --cache_test_results=no --compilation_mode=dbg --config=lsan //geometry/render/dev:http_service_curl_test` has answered most of this: (2) is the correct approach, curl cleanup needs to happen before throwing.

The unresolved part here: is it acceptable to keep this as a lambda or should this become a helper method (there is no capture, it just takes the parameters)?  I don't have a strong preference, it was only created to make sure the same cleanup code happens in the locations where curl needs to be cleaned up (rather than pasting the same code in each place).
</blockquote></details>

OK. I am also fine with the lambda function here as it's a tiny function tightly coupled with the other curl related code inside `PostForm()`.
___
*[geometry/render/dev/http_service_curl.cc, line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_AABxABMuxmcCkO89:-Mxbe_3c8WDB_awdcB4w:b-urihb8) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L324)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I don't know if this is acceptable, the code just checks if the file has content.  If so, the returned `HttpResponse` passes "ownership" of the file back to the caller.  Otherwise, we delete it.  In the event that the file cannot be deleted though, I just ignore it.  Seems obnoxious to throw an error in that event (cannot delete a size zero file for mysterious reason).
</blockquote></details>

OK. Maybe log a message instead?
___
*[geometry/render/dev/test/http_service_curl_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbhK3F4TtRgWIqNrti:-MxbhK3F4TtRgWIqNrtj:b-xs42v6) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/test/http_service_curl_test.cc#L82)):*
> ```cpp
>     EXPECT_TRUE(res_1.service_error_message.has_value());
>     EXPECT_EQ(res_1.service_error_message.value(),
>               "Couldn't resolve host name");
> ```

nit: just to confirm, the error message `Couldn't resolve host name` is from other parts of the code that is not in this PR right? I am simply curious where the error message is set in this test case.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-MxbiwDZCWCh9SAjVk_U:b-4bdz34) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: should we put `= default` here as we have the empty destructor definition in the cc file.
</blockquote></details>

Actually I recommend keeping this as-is.

For a virtual class, there is a significant difference in how the object code looks with the destructor (i.e., the lexically first virtual function) defined in the header file versus the cc file.  When defined in the header file (e.g., via `= default`), then _every_ translation unit that uses this header will get a copy of the entire vtable and RTTI symbols for this class.

Marking `= default` in a header is useful if we want to create a "trivially destructible" data type (for things like TypeSafeIndex or similarly small structs), but generally isn't helpful for thick classes.

However, note that per GSG all overrides must be marked "override" or "final" so we do want `~HttpServiceCurl() override;` here.

https://drake.mit.edu/styleguide/cppguide.html#Inheritance

**Review by svenevs — COMMENTED** [review]
Sounds good, the callbacks are more or less identical to `RenderClient` current implementation fwiw.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723#-:-MxeRShx3os9ujH9HhlZ:b-k05035)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-MxeODsgEA6BH1o6zCKq:bv65f97) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually I recommend keeping this as-is.

For a virtual class, there is a significant difference in how the object code looks with the destructor (i.e., the lexically first virtual function) defined in the header file versus the cc file.  When defined in the header file (e.g., via `= default`), then _every_ translation unit that uses this header will get a copy of the entire vtable and RTTI symbols for this class.

Marking `= default` in a header is useful if we want to create a "trivially destructible" data type (for things like TypeSafeIndex or similarly small structs), but generally isn't helpful for thick classes.

However, note that per GSG all overrides must be marked "override" or "final" so we do want `~HttpServiceCurl() override;` here.

https://drake.mit.edu/styleguide/cppguide.html#Inheritance
</blockquote></details>

OK, works for me -- keeping as is.
___
*[geometry/render/dev/http_service_curl.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_9pHE7vs3VC5SORIb:-MxeP7JA2PMj6wC4Dc7I:b548ztu) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L234)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. I am also fine with the lambda function here as it's a tiny function tightly coupled with the other curl related code inside `PostForm()`.
</blockquote></details>

OK fixed with non-shadowed parameters and updated comment above the lambda.
___
*[geometry/render/dev/http_service_curl.cc, line 324 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mx_AABxABMuxmcCkO89:-MxeQL587rl_IdaTMfzV:b-ll1viz) ([raw file](https://github.com/robotlocomotion/drake/blob/dda4e76c0956ce2cd0439e14822a68e6b55ff74b/geometry/render/dev/http_service_curl.cc#L324)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. Maybe log a message instead?
</blockquote></details>

Done, logging works for me.
___
*[geometry/render/dev/test/http_service_curl_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbhK3F4TtRgWIqNrti:-MxeQTI1-7D9lqZDKFEn:b-tzgpoc) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/test/http_service_curl_test.cc#L82)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: just to confirm, the error message `Couldn't resolve host name` is from other parts of the code that is not in this PR right? I am simply curious where the error message is set in this test case.
</blockquote></details>

Actually that message is the response from `curl`, there's no `.` in the url I'm using so it just comes back and says "I have no idea what you are talking about."  It is also possible to get a `"Couldn't connect to server"` error message out of curl, by using say `HttpServiceCurl service{temp_dir, "127.0.0.1", 1, true};` in that test.  However, if port `1` is currently being used by anything then the error message will likely be different (e.g., a server may respond with an error message).  For the purposes of these tests, I felt it was more reliable to have an invalid url that will not resolve rather than "hope this URL / port aren't active".

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs and @zachfang)

___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-Mxf0cB9EVIBHCQpnbXp:b-v04mfj) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

OK, works for me -- keeping as is.
</blockquote></details>

OK. Thanks for the pointers, I will try to dig more on the `=default` usage.
___
*[geometry/render/dev/http_service_curl.h, line 21 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mxf0xIJ3Vh4PujoW2Og:-Mxf0xIKArCVELJpF6l6:bdonej7) ([raw file](https://github.com/robotlocomotion/drake/blob/e240cb094d737283589a8608bd99450250593e60/geometry/render/dev/http_service_curl.h#L21)):*
> ```objc
>  public:
>   /** Constructs a libcurl based HttpService.  @sa HttpService::HttpService */
>   explicit HttpServiceCurl(const std::string& temp_directory,
> ```

nit: same as #16702, the `explicit` is probably not needed.
___
*[geometry/render/dev/test/http_service_curl_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbhK3F4TtRgWIqNrti:-Mxf-aeABUHT8ejemmfM:b-4ekr2z) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/test/http_service_curl_test.cc#L82)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Actually that message is the response from `curl`, there's no `.` in the url I'm using so it just comes back and says "I have no idea what you are talking about."  It is also possible to get a `"Couldn't connect to server"` error message out of curl, by using say `HttpServiceCurl service{temp_dir, "127.0.0.1", 1, true};` in that test.  However, if port `1` is currently being used by anything then the error message will likely be different (e.g., a server may respond with an error message).  For the purposes of these tests, I felt it was more reliable to have an invalid url that will not resolve rather than "hope this URL / port aren't active".
</blockquote></details>

OK. Thanks!

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-MxfGIu_AFpit0z5zcY5:b-dsw9da) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. Thanks for the pointers, I will try to dig more on the `=default` usage.
</blockquote></details>

Done for reviewable, needs approval from @jwnimmer-tri :upside_down_face:
___
*[geometry/render/dev/http_service_curl.h, line 21 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16723#-Mxf0xIJ3Vh4PujoW2Og:-MxfGAqeB637ONTcx1Bs:b-6ny8qy) ([raw file](https://github.com/robotlocomotion/drake/blob/e240cb094d737283589a8608bd99450250593e60/geometry/render/dev/http_service_curl.h#L21)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: same as #16702, the `explicit` is probably not needed.
</blockquote></details>

Gah! Sorry I meant to fix that here when you called it out... Done in latest commit.
___
*[geometry/render/dev/test/http_service_curl_test.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbhK3F4TtRgWIqNrti:-MxfGSK20fU14u2zF-A3:beua8sw) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/test/http_service_curl_test.cc#L82)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

OK. Thanks!
</blockquote></details>

OK cool, we'll keep the test as is!

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-MxfIPWCAUsn_HOOnmyy:b-26oh3h) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done for reviewable, needs approval from @jwnimmer-tri :upside_down_face:
</blockquote></details>

Reviewable does not agree with you that my approval is needed here.

**Review by svenevs — COMMENTED** [review]
:lgtm: provided CI passes after rebasing.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723#-:-MxfPCYoBT84dQC5sta4:b-d15f70)* status: LGTM missing from assignee zachfang (waiting on @zachfang)

___
*[geometry/render/dev/http_service_curl.h, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16723#-MxbUzfw0TmPF-5c_aCd:-MxfPKW28SaoGnCbC6S9:b-1ulsxk) ([raw file](https://github.com/robotlocomotion/drake/blob/28e2cbcc6cda486f48d37caf533a85efc00dcf99/geometry/render/dev/http_service_curl.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Reviewable does not agree with you that my approval is needed here.



</blockquote></details>

OK, my apologies ... TIL of the neutral grey circle... not being red.  Sorry!

**Review by zachfang — COMMENTED** [review]
Done with the curl callback portion. :lgtm: 

> Reviewed 2 of 7 files at r1, 1 of 2 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16723#-:-MxgFSve07a3PQjr0Vyz:b-sd06jy)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang, exempt from platform review (waiting on @svenevs)

**Pull request merged**
