### PR TITLE
Drop the underactuated textbook from Drake

### PR DESCRIPTION
**Pull request by stonier**
Discussion over in https://github.com/RobotLocomotion/drake-shambhala/issues/31.

+@RussTedrake for feature review please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6889)

### CODE REVIEW

**Comment by RussTedrake** [comment]
I think there are also some cmake references to the textbook that will need to be cleaned up, too?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6889#-:-KsF7sMaIedGm57p24wZ:ba1nuf9)*

**Comment by stonier** [comment]
CMake references cleaned.

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6889#-:-KsFBSRz-iuI-VVM6Q5E:bnfp4nl)*

**Comment by stonier** [comment]
+@ggould-tri for platform review

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6889#-:-KsFXZb6vVMYpM74HtE4:bnfp4nl)*

**Pull request merged**
