### PR TITLE
Rotation constraint corner

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves the corner case (literally) that the box and the unit sphere intersect at a unique corner point.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5546)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-:-KfTeZZ-fPmdiIy8FLeX:b-sriflu)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-:-KfTkTz8XJgoy17cyjZB:bvi7gqa)*

**Comment by RussTedrake** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/solvers/BUILD, line 503 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-Kfa22qVFuckZOJiuaaC:-Kfa22qVFuckZOJiuaaD:b-2x42hh) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/BUILD#L503)):*
> ```Python
>         "test/rotation_constraint_test.cc",
>     ],
>     tags = ["mosek"],
> ```

do we need the 'explicit', yada here?

---

*[drake/solvers/rotation_constraint.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdS_yAmgAPloLI86Pu:-KfdS_yAmgAPloLI86Pv:b-ha2job) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L445)):*
> ```cpp
>         double box_min_norm = box_min.lpNorm<2>();
>         double box_max_norm = box_max.lpNorm<2>();
>         if (box_min_norm <= 1.0 + 1E-10 && box_max_norm >= 1.0 - 1E-10) {
> ```

where does this tolerance come from?

---

*[drake/solvers/rotation_constraint.cc, line 460 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdTGtHuS1O00U-1r5u:-KfdTGtHuS1O00U-1r5v:b-ee5pwv) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L460)):*
> ```cpp
>             //     vᵀ * v1 = 0
>             //     vᵀ * v2 = 0
>             //     v.cross(v1) = v2
> ```

BTW -- wow, you're thorough!  

---

*[drake/solvers/rotation_constraint.cc, line 635 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdT-Vn_Z7mhkT76atA:-KfdT-VoTsoxEKEkun4o:b-h10iog) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L635)):*
> ```cpp
>           }
>         } else {
>           // This box does not intersect with the sphere.
> ```

yes it does!  it just doesn't intersect at one of the corners.

---

*[drake/solvers/rotation_constraint.h, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdRuQXQvtbBUrXKCOW:-KfdRuQXQvtbBUrXKCOX:bfbsl34) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.h#L119)):*
> ```objc
>  * @param prog The mathematical program to which the constraints are added.
>  * @param R The rotation matrix
>  * @param num_binary_vars_per_half_axis # of binary variables for a half axis.
> ```

BTW, is the # sign ok here?

---

*[drake/solvers/rotation_constraint.h, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdRzq0Atk4NcTAN_Tj:-KfdRzq0Atk4NcTAN_Tk:b-726txs) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.h#L121)):*
> ```objc
>  * @param num_binary_vars_per_half_axis # of binary variables for a half axis.
>  * @param limits The angle joints for space fixed z-y-x representation of the
>  * rotation. @default is no constraint.
> ```

reference the other method or the enum directly?

---

*[drake/solvers/rotation_constraint.h, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdSCCVXo_U3-Aeu3aX:-KfdSCCVXo_U3-Aeu3aY:b27ohdx) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.h#L123)):*
> ```objc
>  * rotation. @default is no constraint.
>  * @retval p  `p.first` is the binary variables CRpos, `p.second` is the binary
>  * variables CRneg. The definition for these variables are
> ```

CRpos and CRneg are continuous variables, not binary variables. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/BUILD, line 503 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-Kfa22qVFuckZOJiuaaC:-KfdVm_Ux7YJpUlfFZHe:b-fvyf6) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/BUILD#L503)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

do we need the 'explicit', yada here?
</blockquote></details>

Do you mean `exclusive` and `local`, as we have for the gurobi test https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/BUILD#L376~L378? I am following the example for the mosek test, https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/BUILD#L475, and it only uses `mosek` tag. According to https://github.com/RobotLocomotion/drake/blob/master/tools/bazel.rc#L24, I think we do not need `exclusive` and `local` tags.

---

*[drake/solvers/rotation_constraint.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdS_yAmgAPloLI86Pu:-KfdZvuON0LuhRuHrRQb:b-43se9e) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L445)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

where does this tolerance come from?
</blockquote></details>

Done. Changed to 2 * eps.

The analysis is that if each box_min(i) is off by eps, denote as `[x(0) + eps, x(1) + eps, x(2) + eps]`, then the sum-of-squares is off by 
`2 * (x(0) + x(1) + x(2)) * eps <= 4 * eps` (due to the fact that `x(0)^2 + x(1)^2 + x(2)^2 = 1 => x(0) + x(1) + x(2) <= sqrt(3) < 2`. So the square root of `(x(0) + eps)^2 + (x(1) + eps)^2 + (x(2) + eps)^2 ` is off by 2 eps.

---

*[drake/solvers/rotation_constraint.cc, line 635 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdT-Vn_Z7mhkT76atA:-KfdXPOnxA13vjqFmq25:b-puszmd) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L635)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

yes it does!  it just doesn't intersect at one of the corners.
</blockquote></details>

This is the case that either `bmin` is outside of the unit sphere, or `bmax` is inside the sphere, so we impose the constraint that `c[xi](0) + c[yi](1) + c[zi](2) <= 2`. I think the box does not intersect the sphere.

To make it clear, it does not intersect with the surface of the sphere.

---

*[drake/solvers/rotation_constraint.h, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdRuQXQvtbBUrXKCOW:-KfdY7n0bR2qQB1KkiZH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.h#L119)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW, is the # sign ok here?
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.h, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdRzq0Atk4NcTAN_Tj:-KfdZn_lIa92MWYZiINU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.h#L121)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

reference the other method or the enum directly?
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.h, line 123 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdSCCVXo_U3-Aeu3aX:-KfdY8j7Cvf2GYHkJYxr:b-f9w2ud) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.h#L123)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

CRpos and CRneg are continuous variables, not binary variables. 
</blockquote></details>

I think they are binary valued variables (can only take either 0 or 1). I modified the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Comment by RussTedrake** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/rotation_constraint.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdS_yAmgAPloLI86Pu:-Kfdn1yePxquZpGlzdZ0:b-ekbakk) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L445)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Changed to 2 * eps.

The analysis is that if each box_min(i) is off by eps, denote as `[x(0) + eps, x(1) + eps, x(2) + eps]`, then the sum-of-squares is off by 
`2 * (x(0) + x(1) + x(2)) * eps <= 4 * eps` (due to the fact that `x(0)^2 + x(1)^2 + x(2)^2 = 1 => x(0) + x(1) + x(2) <= sqrt(3) < 2`. So the square root of `(x(0) + eps)^2 + (x(1) + eps)^2 + (x(2) + eps)^2 ` is off by 2 eps.
</blockquote></details>

looks like you typed just eps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 445 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdS_yAmgAPloLI86Pu:-Kfe31Nq1YrpgUuH1NpR:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L445)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

looks like you typed just eps?
</blockquote></details>

Done. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/rotation_constraint.cc, line 460 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfdTGtHuS1O00U-1r5u:-KfeAGJ7XC2cvRiCdDtY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4bcb9bd6abd7498b0395599bb205783ecbca9a8b/drake/solvers/rotation_constraint.cc#L460)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

BTW -- wow, you're thorough!  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-:-KffS5PLQzNoyz-qqMDC:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-:-KfgTtuuZCHq0v4IGuXN:b-vt9vbo)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-:-KfhQOwXKOHfarov1AXp:b-rm2p6t)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhTOhgO8WyauC7TRO3:-KfhTOhgO8WyauC7TRO4:bn7z916) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L4)):*
> ```cpp
> #include "drake/solvers/rotation_constraint_internal.h"
> 
> #include <algorithm>
> ```

We need:
```c++
#include <cmath>
```
because of `std::abs`.

---

*[drake/solvers/rotation_constraint.cc, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhTJL-_QjuPw0LsagP:-KfhTJL-_QjuPw0LsagQ:b-7h2kp8) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L8)):*
> ```cpp
> #include <limits>
> 
> #include "drake/math/cross_product.h"
> ```

We need
```c++
#include "drake/common/symbolic_expression.h"
```

---

*[drake/solvers/rotation_constraint.cc, line 444 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhVCTfqlDKD7zy79yA:-KfhVCTgigxevz40FcbQ:blwhdc8) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L444)):*
> ```cpp
>         this_cneg << cneg[xi](0), cneg[yi](1), cneg[zi](2);
> 
>         double box_min_norm = box_min.lpNorm<2>();
> ```

FYI, these two can be `const`.

---

*[drake/solvers/rotation_constraint.cc, line 497 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhVToWOKfpnya34Oq1:-KfhVToWOKfpnya34Oq2:b-tgyd7c) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L497)):*
> ```cpp
>               // TODO(hongkai.dai): remove this for loop when we can handle
>               // Eigen::Array of symbolic formulae.
>               Expression orthant_c_sum = orthant_c.cast<Expression>().sum();
> ```

FYI, this and the the two `v_dot_v1` and `v_dot_v2` can be marked as `const`.

---

*[drake/solvers/rotation_constraint.cc, line 790 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhW5rLdmSwbmGkWrN-:-KfhW5rLdmSwbmGkWrN0:bpy8mzn) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L790)):*
> ```cpp
>                                   R.row((i + 2) % 3).transpose());
>   }
>   return std::pair<std::vector<MatrixDecisionVariable<3, 3>>,
> ```

FYI, we can have
```c++
return make_pair(Cpos, Cneg);
```
meaning the same thing.

---

*[drake/solvers/rotation_constraint.h, line 97 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhReyumx6Y49j_i_7L:-KfhReyvUvpusyQGJ3Aj:bqeo40u) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.h#L97)):*
> ```objc
>  * constraints as an MILP.  Specifically, for column vectors Ri, we constrain:
>  * - forall i, |Ri| = 1 +/- envelope,
>  * - forall i,j!=i, Ri.dot(Rj) = 0 +/- envelope,
> ```

BTW, consider the following line:
```
 - forall i, j. i ≠ j ⇒ Ri ⋅ Rj = 0 ± envelope,
```

---

*[drake/solvers/rotation_constraint.h, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhSpe-cHg2ikLV_cE7:-KfhSpe-cHg2ikLV_cE8:brenvqb) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.h#L104)):*
> ```objc
>  * is increased.
>  *
>  * Note: Creates 9*2*num_binary_variables_per_half_axis binary variables named
> ```

FYI, it's easier to read if we have `@p num_binary_variables_per_half_axis`.

---

*[drake/solvers/rotation_constraint.h, line 114 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhTtQh28wgZIKiJ1sh:-KfhTtQh28wgZIKiJ1si:buin8cx) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.h#L114)):*
> ```objc
>  *    variables as the constraints on R), and
>  *  - to facilitate branch-and-bound solution techniques -- binary regions are
>  *    layered so that constraining one region provides establishes constraints
> ```

`provides establishes` => typo of `provides/establishes`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Comment by soonho-tri** [comment]
Nice work!

:lgtm: (aside some comments). 

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-:-KfhYrUcQW6UY7NKSIXu:b5ht7wp)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 4 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhTOhgO8WyauC7TRO3:-KfhYj6Pl67VPRRymQ-Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L4)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We need:
```c++
#include <cmath>
```
because of `std::abs`.
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhTJL-_QjuPw0LsagP:-KfhYs_P6M40z17w_wzn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L8)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We need
```c++
#include "drake/common/symbolic_expression.h"
```
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 444 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhVCTfqlDKD7zy79yA:-KfhZ4mowB3_cAMiG1XU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L444)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, these two can be `const`.
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 497 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhVToWOKfpnya34Oq1:-KfhZ9cIaRn6fSOIdv0v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L497)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this and the the two `v_dot_v1` and `v_dot_v2` can be marked as `const`.
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 790 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhW5rLdmSwbmGkWrN-:-KfhZKIBpSVpeU5A-bWx:b-433ptk) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.cc#L790)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, we can have
```c++
return make_pair(Cpos, Cneg);
```
meaning the same thing.
</blockquote></details>

Done. Good to know.

---

*[drake/solvers/rotation_constraint.h, line 97 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhReyumx6Y49j_i_7L:-KfhZn2dq-yflCskYZlV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.h#L97)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, consider the following line:
```
 - forall i, j. i ≠ j ⇒ Ri ⋅ Rj = 0 ± envelope,
```
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.h, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhSpe-cHg2ikLV_cE7:-Kfh_NBf6dM_r0ueqSg1:b-sxme2v) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.h#L104)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, it's easier to read if we have `@p num_binary_variables_per_half_axis`.
</blockquote></details>

Done. I use `` as I feel it is easier to read. 

---

*[drake/solvers/rotation_constraint.h, line 114 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5546#-KfhTtQh28wgZIKiJ1sh:-Kfh_jomWFa97aK9FaGj:b-qjn244) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3543609a8f852e07dc91f3c0ed1bd3a56d1460/drake/solvers/rotation_constraint.h#L114)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`provides establishes` => typo of `provides/establishes`?
</blockquote></details>

Done. I think `establishes` is the right word here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5546)*

**Pull request merged**
