### PR TITLE
py containers: Allow namedview() to nest

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per: https://github.com/RobotLocomotion/drake/issues/10736#issuecomment-829284713

FYI @RussTedrake - took me 30min to get this far, but it'd prolly only take another 15min to make it work fully as intended

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973)

### CODE REVIEW

**Comment by RussTedrake** [comment]
Looks great to me!  Would be great to use/have this.
Can you throw in one more test where you call `MyNestedView` on a 5 x N numpy array, and make sure that the *rows* are accessible by the field names?  That's turned out to be a super useful thing when dealing with `NewContinuousVariables()`, etc.

**Comment by EricCousineau-TRI** [comment]
Sweet! Spent rest of today doing some hw stuff, but will revisit tomorrow or next week!

**Comment by EricCousineau-TRI** [comment]
Done; took 1hr to fully flesh out the contracts. Still some rough edges, but good for a start?

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for feature review, please! (any chance you can beta-test this to what you want in this dev branch, and let me know if there're missing features/tests?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-MZYVu50Blk_ajQg_cq1:bvipn98)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by EricCousineau-TRI** [comment]
Russ - I'll wait til you have a chance for test spin to either act or ignore my above discussion items.

**Review by RussTedrake — COMMENTED** [review]
cc @weigao95 , since we were just talking about this, and he's excited about pushing it forward.  i'll get back to it this weekend.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-MbvgujeAMxLwT6Jm3R1:b63pgeu)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

**Comment by EricCousineau-TRI** [comment]
Sweet, sounds good!

**Review by RussTedrake — COMMENTED** [review]
I think this is awesome and I'd love to see it pushed through.  (Sorry for my being slow).  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-Mc8mw1M4C1I-iLWlD4W:bzgdbau)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[bindings/pydrake/common/containers.py, line 158 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-Mc8n3X08DQsx5vqzx-I:-Mc8n3X08DQsx5vqzx-J:btsu4oe) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L158)):*
> ```Python
>     def __repr__(self):
>         """Provides human-readable breakout of each field and value, using
>         flattend representation."""
> ```

nit: flattend =" flattened
___
*[bindings/pydrake/common/containers.py, line 291 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MZYZW2c-0CTLv7PynwN:-Mc8o0rn8LbRtCEm-A4M:b-qh921m) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L291)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should specify "consistency" contract for top-level (all str-with-period, or all str-and-subview).
</blockquote></details>

agreed.  my proposal: simplify these two bullets to simply: Field names cannot contain a ``.``?
___
*[bindings/pydrake/common/containers.py, line 300 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MZYZTBP8bp0KIJtrURT:-Mc8jrmF4iXytUxeAzh5:bjhbaid) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L300)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should show nested view stuff here.
</blockquote></details>

agreed.  i was going to recommend the same.
___
*[bindings/pydrake/common/containers.py, line 336 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-Mc8lJ__331y7P181Qrp:-Mc8lJ__331y7P181Qrq:b3vlimh) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L336)):*
> ```Python
>                 raise RuntimeError(
>                     f"Nested subview class name must end with `_`: "
>                     f"{subview_cls}"
> ```

see comment below (I don't like requiring users to provide the "_" suffix).  Since you use `issubclass` here, I don't see yet why you can't add a new class member that remembers which elements are subviews (e.g. view_cls_dict['_is_subview']) and pass that to e.g. _unflatted_fields?
___
*[bindings/pydrake/common/test/containers_test.py, line 122 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MZYZfd-4TEerqIat2op:-Mc8nQ9L0LWciGwjYqZY:b40xi9f) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/test/containers_test.py#L122)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: This contract is actually asymmetric; it can be enforced at top-level field definitions, but is not presently enforced at lower levels of nesting. e.g. the following is valid, I believe:

```
nestedview("maybe_good", ["a", nestedview("b_", ["c.x", "c.y"])])
```

Options:
- Just capture the nuance.
- Enforce this by adding `_nest_mode` to the `view_cls_dict` to be checked
- Remove constraint, and cross fingers that mixed-up stuff ain't painful.
</blockquote></details>

i would think it would be simpler to simply enforce that field names do not contain a "."?  e.g. that the nesting must be explicit?
___
*[bindings/pydrake/common/test/containers_test.py, line 196 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-Mc8koLy8QqMz2nnXEq3:-Mc8koLy8QqMz2nnXEq4:b-ktwns2) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/test/containers_test.py#L196)):*
> ```Python
>         MyNestedView = namedview(
>             "MyNestedView",
>             [namedview("a_", ["x", "y"]), "b", namedview("c_", ["qw", "qx"])],
> ```

is there a way to avoid users having to specify the trailing "_" in the subview names?  e.g. `namedview("a_", ["x", "y"]) => namedview("a", ["x", "y"])`

I think this would be too error prone and cause confusion?  and because people can still access `view.a` and get the less impressive behavior, we will have only added functionality?
___
*[bindings/pydrake/common/test/containers_test.py, line 244 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-Mc8mjwz8_UoFDX5zRrx:-Mc8mjx-9hVuzLWhG5qz:biviwxa) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/test/containers_test.py#L244)):*
> ```Python
>         self.assertEqual(
>             repr(view.a),
>             "MyNestedView.a_(x=1, y=2)",
> ```

yet another good example of why the trailing "_" is not ideal.

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/common/containers.py, line 291 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MZYZW2c-0CTLv7PynwN:-Mc8oggqACnsBtlMR6iE:bpkkoah) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L291)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

agreed.  my proposal: simplify these two bullets to simply: Field names cannot contain a ``.``?
</blockquote></details>

I suspect you were trying to support this case so that MBP element names automatically parse into the nested view, but I would think that we are going to want a method in the binding layer to create a namedview from the MBP contex, anyhow?  and/or from the diagram context, etc?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[bindings/pydrake/common/containers.py, line 291 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MZYZW2c-0CTLv7PynwN:-McCRpXe3KII4FZiURlY:b-3regqf) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L291)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I suspect you were trying to support this case so that MBP element names automatically parse into the nested view, but I would think that we are going to want a method in the binding layer to create a namedview from the MBP contex, anyhow?  and/or from the diagram context, etc?  
</blockquote></details>

I'd be fine to defer to binding layer!

However, there's the workflow "symmetry" - I think `get_fields()` would ideally retrieve the flattened form (e.g `a.x, a.y, b.qw, b.qx`). But there might be an expectation that people could still construct a nested class using `namedview(duplicate, my_cls.get_fields() + ["new_field"])`.

Options:
(a) Document that symmetry isn't there.
(b) Make `get_fields(flat=False)` be the default (currently, `flat=True` is default).
(c) Keep as is.

WDYT?
___
*[bindings/pydrake/common/containers.py, line 336 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14973#-Mc8lJ__331y7P181Qrp:-McCSM-57Ylcr1m5fh9a:bkbza29) ([raw file](https://github.com/robotlocomotion/drake/blob/f41f682b684b2bdb881a46a91dfb692c7287fe28/bindings/pydrake/common/containers.py#L336)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

see comment below (I don't like requiring users to provide the "_" suffix).  Since you use `issubclass` here, I don't see yet why you can't add a new class member that remembers which elements are subviews (e.g. view_cls_dict['_is_subview']) and pass that to e.g. _unflatted_fields?
</blockquote></details>

Unfortunately, there's a "collision" between two facets of the interface:

(1) If you have a nested `namedview`, you can still refer to the *type* directly, e.g. `MyNestedView.a`.
(2) You also have the *field descriptor*, e.g. `MyNestedView.a`, where you can use that as a functor to *get the value* of the field; concretely `getter = MyNestedView.a; getter(my_view)`.

Options:
(a) Stick with `_` suffix so you have a distinction.
(b) `MyNestedView.a` will refer to descriptor. Users can no longer refer to the type explicitly.
(c) Still assign `MyNestedView.a_`, but it's the *type*. `MyNestedView.a` is the accessor. You now have *asymmetry* between the printed repr (`MyNestedView.a(...)`) and how you actually access the type (`MyNestedView.a_(...)`).

WDYT?

**Review by EricCousineau-TRI — COMMENTED** [review]
No worries! Unfortunately, I have some counterpoints on design suggestions, so it may take a bit longer :sweat_smile: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-McCTOUE4huVxXDNyuwg:bbq96qt)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Sorry this stalled on me.  It took me a long time to think through your descriptions.  ;-)   I still feel like asking users to use/remember the trailing _ is pretty bad, but don't have a strong opinion about if one of  your work-arounds is better than another.

I'm going to phone a friend on this one.  @rpoyner-tri -- can you weigh in?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-Mfh2q4RCxXbU3lqF6i_:b-qu5pn8)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
:eyes:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-MgLl2lWBNmiBB_4D496:bd5ty4n)* status: 7 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
-@russtedrake +@rpoyner-tri for feature review. Russ, please jump back in if you see any concerns un-addressed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-MgRO74UAzH2Cz1T_OU7:bdgvko4)* status: 7 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @rpoyner-tri, and @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973)* status: 7 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @rpoyner-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MgROiMYAxQsfgufGLpF:-MgROiMYAxQsfgufGLpG:buk92c6) (no related file):*
FYI I rebased my review copy to current master to avoid some long-fixed `mkdoc` breakage.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @rpoyner-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14973#-MgSWoo1Eqa9GTFcLAVI:-MgSWoo26MlkDpNVYNVD:b3wumkr) (no related file):*
Still scratching my head trying to understand what's going on, and feeling the lack of a motivating example. That said, it feels to me like there's some level violation, or weakness of notation that is creating the subview _ situation. Whatever name we give the top-level "type", As far as i can tell it is pretty much never used again. However, when we create a sub-view, we place on the "type" name the dual role of naming the view type, and of generating the field name _in the containing view_. I think that is where things start to go off the rails.

To help clarify things for myself, I tried to set up a nested example of `namedtuple`, since that is the examplar we claim to be working from. Improvising in ipython, I came up with something like this:

```
In [1]: import collections

In [2]: Soldier = collections.namedtuple('Soldier', 'name, rank, serial_number')

In [3]: Patrol = collections.namedtuple('Patrol', 'leader, assistant, pleb')

In [4]: le = Soldier('Abraham', 'G3', '222')

In [5]: asst = Soldier('George', 'G2', '999')

In [6]: pleb = Soldier('Benjamin', 'G1', '333')

In [7]: pat = Patrol(le, asst, pleb)

[... various bungling ...]

In [9]: print(pat)
Patrol(leader=Soldier(name='Abraham', rank='G3', serial_number='222'), assistant=Soldier(name='George', rank='G2', serial_number='999'), pleb=Soldier(name='Benjamin', rank='G1', serial_number='333'))

In [10]: pat.leader
Out[10]: Soldier(name='Abraham', rank='G3', serial_number='222')

In [11]: type(le)
Out[11]: __main__.Soldier

In [12]: type(pat)
Out[12]: __main__.Patrol

In [15]: pat.leader.rank
Out[15]: 'G3'

In [16]: pat.leader.Soldier
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-e41957961214> in <module>()
----> 1 pat.leader.Soldier

AttributeError: 'Soldier' object has no attribute 'Soldier'

```

I don't know if the above is relevant to where you are trying to go, but it helped me think through what I might want from the nested naming -- mainly that I don't want to care about the subview names at all, maybe other than at definition time.

That probably means that we would have to fiddle with the definition-time syntax for nested views, but AFAIK that's still a green field.

---

**Comment by EricCousineau-TRI** [comment]
> we place on the "type" name the dual role of naming the view type [...] I think that is where things start to go off the rails.

Yup! Basically, the tensions is between the noise of naming the type (ensuring it's still accessible and doesn't get overwritten by the new `property()`) and having an "anonymous" type.
FTR, I strongly disprefer attempting an "anonymous" type b/c it could be noisy and/or a lie (and a lie can hurt pickling).

> As far as i can tell it is pretty much never used again.

Maybe. Per above, I don't think anonymous types are usable; but perhaps we just auto-name the subfield's class?

Possible construction options (some more explicit, per Russ's suggestion above):
```py
# 1.a. Optional 2-tuple, (field, subview_cls) (kinda messy, but allows composition).
# Some hacks could be done to check refcnt to see if it's a new subview, or an existing view type.
namedview("MyView", [
  "field_1",
  (
     "subview",
     namedview("SubView", ["subfield_1", "subfield_2"]),
  ),
])

# 1.b. Use Dict, but use `None` for direct fields (kinda messy).
namedview("MyView", {
  "field_1": None,
  "subview": namedview("SubView", ["subfield_1", "subfield_2"]),
})

# 2.a. Be explicit. Have subview dictate both class name and field name.
namedview("MyView", [
  "field_1",
  subview("SubView", "subview", ["subfield_1", "subfield_2"]),
])

# 2.b. Be kinda implicit. Have subview dictate field name, then assign class name.
namedview("MyView", [
  "field_1",
  subview("subview", ["subfield_1", "subfield_2"]),
])

# 3. Keep as-is.
```

WDYT? Any other (simpler) options I'm not thinking of?

---

The general workflow you outlined is in a similar vein, but isn't strongly typed like a nested `namedview`.
However, using nested `dataclass`'s would be more relevant since we want typing, and could nest the defined type in the class itself.
(FWIW Not sure what `Out[16]` was supposed to illustrate, as I don't see any why for it `pat.leader.Soldier` to make its way through?)

**Review by rpoyner-tri — COMMENTED** [review]
Good run-down of the construction possibilities. I had considered 1a and 1b, but not 2a or 2b. I agree 1b is disappointing (unless you are an old-timey lisp fan, where all data structures end at `nil`).

All of the examples shown above assume that the entire edifice will be built at once. How would they work in a situation like DiagramContext, where individual pieces (leaf systems and contexts) can stand alone, but later get composed into larger structures?

Where/how do we get any leverage out of repeated use of the same type across a structure? Say:

Point3d = namedview("x", "y", "z")
Quat = namedview ("w", "x", "y", "z")
Pose3d = namedview(("translation", Point3d), ("rotation", Quat))  # using  1b syntax for now

RobotPose = (("some_frame", Pose3d), ("another_frame", Pose3d), ...)

In the existing proposal, it seems like we will end up with identical types named "some_frame", "another_frame", just for the sake of a tight syntax for construction (which I hope) humans will rarely have to write at scale. Maybe I'm still missing a motivating example that undermines my assumptions?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-MgunBPvCGgHMTa3nwL-:bu9el0c)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

**Comment by EricCousineau-TRI** [comment]
Sorry for delay; it OK if we resume this PR in early October?

**Review by rpoyner-tri — COMMENTED** [review]
October is ok with me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14973#-:-Mhxgz07EzY_2huxQx7y:b-yhmc7l)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @RussTedrake)

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI what's the plan here?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI shall we close this now, as abandoned?  I'll plan to do so in mid-July if I don't hear otherwise.

**Pull request closed without merging**
