### PR TITLE
Add operator overloading for symbolic::Variable

### PR DESCRIPTION
**Pull request by soonho-tri**
related issue: #4623, #4619

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4630)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@jwnimmer-tri  , platform-review please.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-:-K_5eptPv0qRdLCf2kCt:b56cjq7)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_variable_test.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5lcmJnfk06-d06ZlU:-K_5lcmJnfk06-d06ZlV:b-x77q1l) ([raw file](https://github.com/robotlocomotion/drake/blob/103f22b8375a0ed5d00a79c689de3ff2864a6444/drake/common/test/symbolic_variable_test.cc#L12)):*
> ```cpp
> #include "gtest/gtest.h"
> 
> #include "drake/common/symbolic_expression.h"
> ```

Why put this new test code in this file, versus symbolic_expression_test?  The code under test is in symbolic_expression.h.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_variable_test.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5lcmJnfk06-d06ZlU:-K_5rwLJ82HS9nQiYDET:b-1ftmuk) ([raw file](https://github.com/robotlocomotion/drake/blob/103f22b8375a0ed5d00a79c689de3ff2864a6444/drake/common/test/symbolic_variable_test.cc#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why put this new test code in this file, versus symbolic_expression_test?  The code under test is in symbolic_expression.h.
</blockquote></details>

Done. (Moved to `symbolic_expression_test.cc`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_test.cc, line 1363 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5sbm7Mf645_GFxNjs:-K_5tsIzNuCVqqCOI2IX:b3kqk) ([raw file](https://github.com/robotlocomotion/drake/blob/1eefc60727f220feeada6d780b6e310e2431a842/drake/common/test/symbolic_expression_test.cc#L1363)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing `override`?
</blockquote></details>

!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_test.cc, line 1363 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5sbm7Mf645_GFxNjs:-K_5uR2jOiMrVqOaqIgH:bs7170n) ([raw file](https://github.com/robotlocomotion/drake/blob/1eefc60727f220feeada6d780b6e310e2431a842/drake/common/test/symbolic_expression_test.cc#L1363)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

!
</blockquote></details>

Done. (it was META)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/symbolic_expression_test.cc, line 1369 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5xbdv3eRmCveFtwdi:-K_5xbdv3eRmCveFtwdj:brdutoh) ([raw file](https://github.com/robotlocomotion/drake/blob/ac80e502fde3faf6d6a411062c4eddbdb2b14880/drake/common/test/symbolic_expression_test.cc#L1369)):*
> ```cpp
>     var_mat_ << x_, y_,
>                 z_, w_;
>     exp_mat_ << (x_ + z_), (x_ + w_),
> ```

`exp` also stands for `exponential`. Can we use `expr` instead?

---

*[drake/common/test/symbolic_variable_test.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5y21XwOWVeztQX0Yo:-K_5y21XwOWVeztQX0Yp:bd1qybi) ([raw file](https://github.com/robotlocomotion/drake/blob/103f22b8375a0ed5d00a79c689de3ff2864a6444/drake/common/test/symbolic_variable_test.cc#L23)):*
> ```cpp
> using std::vector;
> 
> static bool ExpEqual(const Expression& e1, const Expression& e2) {
> ```

Rename this to `ExprEqual`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-:-K_5y6IdPE8ZndVsHfLf:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/symbolic_expression_test.cc, line 1369 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5xbdv3eRmCveFtwdi:-K_60nkj0Wk5mCR4yz70:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac80e502fde3faf6d6a411062c4eddbdb2b14880/drake/common/test/symbolic_expression_test.cc#L1369)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`exp` also stands for `exponential`. Can we use `expr` instead?
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_variable_test.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4630#-K_5y21XwOWVeztQX0Yo:-K_60qzcS2ACoV6aFA84:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/103f22b8375a0ed5d00a79c689de3ff2864a6444/drake/common/test/symbolic_variable_test.cc#L23)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Rename this to `ExprEqual`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4630)*

**Pull request merged**
