### PR TITLE
Introduce System<T>

### LINKED ISSUE #2872: Move *SystemInterface out of the System2 API
Per discussion with @sherm1 and @RussTedrake, we will instead have a `System` class from which all Systems, including Diagrams, inherit.  There will be default implementations of methods that don't necessarily apply to all Systems - i.e. everything that is not part of the current `SystemInterface`.

For clarity, and just in case we change our minds later, I plan to keep `ContinuousSystemInterface` et. al. around as parents of `System`, as suggested by @jwnimmer-tri.  This will have no impact on implementers, and will make the transition more gradual as a side benefit.

### PR DESCRIPTION
**Pull request by david-german-tri**
This abstract non-interface base class template specifies all the methods that any System might implement. Functions that consume Systems should detect the System capabilities by inspection at runtime.

Resolves #2872.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2991)

### CODE REVIEW

**Comment by david-german-tri** [comment]
CI should chew on this before anyone spends time reviewing, but @amcastro-tri @sherm1 FYI.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot: retest this please

**Comment by david-german-tri** [comment]
+@amcastro-tri for feature review, +@sherm1 for platform review.

**Comment by sherm1** [comment]
Platform review: looks great! A few minor comments. I have been attempting to collect a full list of System methods in the Solver 2 doc, updated [here](https://drive.google.com/open?id=0B-dn8WKPpzq4YkdZZDUzanJkaWc) (see page 6).

---

Reviewed 18 of 21 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/continuous_system_interface.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO6zRf1xnPt5FwtUQz8:-KO6zRf1xnPt5FwtUQz9:-2095900269) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/continuous_system_interface.h#L18)):*
> ```objc
> /// from System<T> instead.
> template <typename T>
> class ContinuousSystemInterface {
> ```

What is the purpose of this class? It declares only a small subset of the continuous system methods (not, for example, any of the methods involving derivatives). Is it really doing anything useful now?

---

*[drake/systems/framework/system.cc, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO6zz092fjZ85bb6AVy:-KO6zz092fjZ85bb6AVz:1625948794) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.cc#L4)):*
> ```cpp
> // system.h is a stand-alone header.
> 
> #include "drake/systems/framework/system.h"
> ```

BTW, consider adding a `System<double>` template instantiation here.

---

*[drake/systems/framework/system.h, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO7-EPMtG_66bdzPQ50:-KO7-EPMtG_66bdzPQ51:-525834054) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.h#L53)):*
> ```objc
>   }
> 
>   /// By default, returns zero. Physical systems should override.
> ```

"*Continuous* physical systems should override."

---

*[drake/systems/framework/system.h, line 60 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO7-OpiBR5ABMW400pp:-KO7-OpjmK9ngA4Fomve:-525834054) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.h#L60)):*
> ```objc
>   }
> 
>   /// By default, returns zero. Physical systems should override.
> ```

"*Continuous* physical systems should override."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-:-KO70UkXkVKur33E436g:-640344022)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/continuous_system_interface.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO6zRf1xnPt5FwtUQz8:-KO7AoBRuAM-uRL5YQOH:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/continuous_system_interface.h#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> What is the purpose of this class? It declares only a small subset of the continuous system methods (not, for example, any of the methods involving derivatives). Is it really doing anything useful now?
</details>
Done.

---

*[drake/systems/framework/system.cc, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO6zz092fjZ85bb6AVy:-KO7AqmmajQs8qJGvya2:-107211959) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, consider adding a `System<double>` template instantiation here.
</details>
`System` has pure virtual methods.

---

*[drake/systems/framework/system.h, line 53 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO7-EPMtG_66bdzPQ50:-KO7AwAMT28krAWQ0TzM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "*Continuous* physical systems should override."
</details>
Done.

---

*[drake/systems/framework/system.h, line 60 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO7-OpiBR5ABMW400pp:-KO7AwS3hQDVzaM7J3iX:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.h#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "*Continuous* physical systems should override."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991)*

**Comment by sherm1** [comment]
Platform review: I like it! :lgtm: -- one BTW.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.cc, line 4 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO6zz092fjZ85bb6AVy:-KO7L4r4TvI4r_gnumWR:1658263628) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8e92817374e141ad7153485f7077a177999b2b/drake/systems/framework/system.cc#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> `System` has pure virtual methods.
</details>
Oops -- sorry!

---

*[drake/systems/framework/system.h, line 141 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO7LT8LK7nlaqPnCMhG:-KO7LT8LK7nlaqPnCMhH:1048832165) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L141)):*
> ```objc
>   }
> 
>   // TODO(david-german-tri): Add MapConfigurationDerivativesToVelocity.
> ```

BTW, and `MapAccelerationToConfigurationSecondDerivatives()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-:-KO7Lx0m-udRJDZdW1TB:460261381)*

**Comment by amcastro-tri** [comment]
My half cent on this. Besides small observations :lgtm_strong: 

---

Reviewed 1 of 21 files at r1, 1 of 3 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[drake/systems/framework/system.h, line 40 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOASQTlcpEwolUHRAfp:-KOASQTlcpEwolUHRAfq:-807951870) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L40)):*
> ```objc
>                           SystemOutput<T>* output) const = 0;
> 
>   /// Return the potential energy currently stored in the configuration provided
> ```

`Return` -> `Returns` here and also in docs below to be consistent throughout the file.

---

*[drake/systems/framework/system.h, line 127 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOATGuVAg4qmnY88tpH:-KOATGuVAg4qmnY88tpI:-138949614) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L127)):*
> ```objc
>     if (generalized_velocity.size() != configuration_derivatives->size()) {
>       throw std::out_of_range(
>           "generalized_velocity.size() " +
> ```

This message will simply put the number next to the string. What about (I added parentheses):

```C++
"(generalized_velocity.size() = " +
          std::to_string(generalized_velocity.size()) +
          ") != (configuration_derivatives.size() = " +
          std::to_string(configuration_derivatives->size()) +
          "). Do you need to override the default implementation of " +
          "MapVelocityToConfigurationDerivatives?");
```

---

*[drake/systems/framework/system.h, line 143 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOATnc75EVD91sZfi4j:-KOATnc8ltVP8nxzwoGb:1745147817) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L143)):*
> ```objc
>   // TODO(david-german-tri): Add MapConfigurationDerivativesToVelocity.
> 
>   virtual void set_name(const std::string& name) { name_ = name; }
> ```

Do these need to be virtual?

---

*[drake/systems/framework/primitives/adder.h, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOAUNy8qnL_4aptkkLa:-KOAUNy8qnL_4aptkkLb:-1158328899) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/primitives/adder.h#L38)):*
> ```objc
> 
>  private:
>   std::string name_;
> ```

Is `name_` used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-:-KOAVfJ53BFxX3hEiRxy:1400527696)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/system.h, line 40 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOASQTlcpEwolUHRAfp:-KOB-LpbNLrX1sFTAJcC:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> `Return` -> `Returns` here and also in docs below to be consistent throughout the file.
</details>
Done.

---

*[drake/systems/framework/system.h, line 127 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOATGuVAg4qmnY88tpH:-KOB0C25d6d4BwEzh9Bo:711825379) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L127)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> This message will simply put the number next to the string. What about (I added parentheses):
> 
> ```C++
> "(generalized_velocity.size() = " +
>           std::to_string(generalized_velocity.size()) +
>           ") != (configuration_derivatives.size() = " +
>           std::to_string(configuration_derivatives->size()) +
>           "). Do you need to override the default implementation of " +
>           "MapVelocityToConfigurationDerivatives?");
> ```
</details>
I think the error messages are equally readable, and the code you propose is slightly less readable.  Regardless, this is pre-existing code that I don't want to mess with in this PR.

---

*[drake/systems/framework/system.h, line 141 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KO7LT8LK7nlaqPnCMhG:-KOB-cbHTSwykRKWXYw1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L141)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, and `MapAccelerationToConfigurationSecondDerivatives()`.
</details>
Done.

---

*[drake/systems/framework/system.h, line 143 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOATnc75EVD91sZfi4j:-KOB-sR_vh37SjrQ5ocO:156593572) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L143)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Do these need to be virtual?
</details>
Not sure.  Procedurally generated names have been suggested before, so I figured we might as well allow it.

---

*[drake/systems/framework/primitives/adder.h, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOAUNy8qnL_4aptkkLa:-KOB06AUQrNLskH7GGNl:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/primitives/adder.h#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Is `name_` used?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 52 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOBK2GrrigSoNyjNNqa:-KOBK2GrrigSoNyjNNqb:616967294) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L52)):*
> ```objc
>   }
> 
>   /// Return the rate at which mechanical energy is being converted *from*
> ```

Returns

---

*[drake/systems/framework/system.h, line 65 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOBK3YURl-OxQfwkYse:-KOBK3YURl-OxQfwkYsf:616967294) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L65)):*
> ```objc
>   }
> 
>   /// Return the rate at which mechanical energy is being generated (positive)
> ```

Returns

---

*[drake/systems/framework/primitives/adder.h, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOAUNy8qnL_4aptkkLa:-KOBK67-x7hk3q4cWz2H:762785614) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/primitives/adder.h#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Done.
</details>
Humm... I still see `name_` but maybe you still didn't push it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991)*

**Comment by david-german-tri** [comment]
Yeah, Reviewable didn't pick up on the push for some reason.  Seems to have snapped out of it now.

---

Review status: 18 of 20 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/framework/system.h, line 52 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOBK2GrrigSoNyjNNqa:-KOBLzdIX2erl8BlEbW-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L52)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Returns
</details>
Done.

---

*[drake/systems/framework/system.h, line 65 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOBK3YURl-OxQfwkYse:-KOBLzR2uQbzKWW2imCw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/system.h#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Returns
</details>
Done.

---

*[drake/systems/framework/primitives/adder.h, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-KOAUNy8qnL_4aptkkLa:-KOBM-eWe17KCFGEH6PM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ffd795b8ffb2daae1f143f5dbf420627e6cb16d2/drake/systems/framework/primitives/adder.h#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Humm... I still see `name_` but maybe you still didn't push it?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2991#-:-KOBM2Qi9hKNIK0ekXmi:1795948350)*

**Pull request merged**
