### PR TITLE
Use map::contains() where we previously used count to simulate contains

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This updates Drake's code base to be C++20 friendly. Various stl map and set types now directly support a `contains(x)` method. Previously, we would call `count(x)` and do some numerical comparison to determine if a key was found. Now, we're spelling it directly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok) 

+@rpoyner-tri for both reviews.

To help make review a bit saner, I've sliced this into revisions. Each revision consists of a single replacement pattern (as documented in the commit message). The hope is that the review will be a bit more mindless when you don't have to attention slice between the various spellings of `contains()` and `!contains()`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051#-:-Nrf3Agi2kV4837YHc3t:bzet5ki)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 23 of 43 files at r2, 12 of 14 files at r3, 15 of 19 files at r4, 5 of 6 files at r5, 3 of 6 files at r6, 41 of 43 files at r7, 3 of 3 files at r8, 5 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051#-:-NrfvJliDDSj9Vjjzdgp:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`common/symbolic/expression/test/formula_test.cc` line 1072 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/21051#-Nrfnfi6BWZlX4QW6mhw:-Nrfnfi74FZgXvc37pVd:boo7h8e) ([raw file](https://github.com/RobotLocomotion/drake/blob/df60df300a2d78a28b42edcf9a08b516e30554d8/common/symbolic/expression/test/formula_test.cc#L1072)):*
> ```cpp
>   EXPECT_EQ(formulas.count(f2_), 1u);
>   EXPECT_EQ(formulas.count(f3_), 1u);
>   EXPECT_EQ(formulas.count(f4_), 1u);
> ```

btw the `1` vs `1u` in this file is uhm ... special.. Good riddance.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`solvers/test/mathematical_program_test.cc` line 1949 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/21051#-NrfxZFy3XaAq4zDtk0t:-NrfxZFy3XaAq4zDtk0u:b5hv808) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d3ba01435f8454fd392100371a430a22c70f276/solvers/test/mathematical_program_test.cc#L1949)):*
> ```cpp
>     if (!std::isinf(lb_in_constraint(i))) {
>       // Either `Ax - lb` or `-(Ax - lb)` should be in the constraint set.
>       EXPECT_NE(constraint_set.contains(Ax(i) - lb_in_constraint(i)),
> ```

minor: As I go through the logic in my head, it seems to me that this transformation has turned OR into XOR. That might still be good enough for a test program, but let's at least ponder the case of both-in-set. Is it always a bad outcome?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

___
*[`solvers/test/mathematical_program_test.cc` line 1949 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/21051#-NrfxZFy3XaAq4zDtk0t:-NrgB_s52ecCln0WVaBL:b4tyj3j) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d3ba01435f8454fd392100371a430a22c70f276/solvers/test/mathematical_program_test.cc#L1949)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: As I go through the logic in my head, it seems to me that this transformation has turned OR into XOR. That might still be good enough for a test program, but let's at least ponder the case of both-in-set. Is it always a bad outcome?
</blockquote></details>

No, you're right. I weirdly interpreted it as xor, but shouldn't have. I think I was just lucky it passed.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

___
*[`solvers/test/mathematical_program_test.cc` line 1949 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/21051#-NrfxZFy3XaAq4zDtk0t:-NrgCGA--cnAfFd1-x83:biefm09) ([raw file](https://github.com/RobotLocomotion/drake/blob/8d3ba01435f8454fd392100371a430a22c70f276/solvers/test/mathematical_program_test.cc#L1949)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

No, you're right. I weirdly interpreted it as xor, but shouldn't have. I think I was just lucky it passed.
</blockquote></details>

And now a follow up. I was looking at the original code and now I remember why I used XOR. It was the fact that they were *adding* the two counts and comparing it to one. That *is* an exclusive or. If they're both 1, you get the wrong value, if they're both 0, you get the wrong value. XOR is the only condition that would match the old semantics.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21051)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
