### PR TITLE
[framework] Add DiagramBuilder::ConnectToSame sugar

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16476.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @sherm1 in case you'd like to comment on the API.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[systems/framework/diagram_builder.h, line 322 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvW9lOhAxEcDQjcfYYh:-MvW9lOiEyMnECh05Fh0:b-r2j6ci) ([raw file](https://github.com/robotlocomotion/drake/blob/74c76a118d7f9a7c3d3b6be4d48d38d1863d768c/systems/framework/diagram_builder.h#L322)):*
> ```objc
>       InputPortIndex diagram_port_index, const InputPort<T>& input);
> 
>   /// Connects whatever is already upstream of the given @p connected_input of
> ```

None of the `@p` annotations in this paragraph match parameters. I found this disturbing enough that I haven't yet made sense of the rest of the text.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[systems/framework/diagram_builder.h, line 322 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvW9lOhAxEcDQjcfYYh:-MvWFihl4MC_WsTwNFsb:b-tlmddt) ([raw file](https://github.com/robotlocomotion/drake/blob/74c76a118d7f9a7c3d3b6be4d48d38d1863d768c/systems/framework/diagram_builder.h#L322)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

None of the `@p` annotations in this paragraph match parameters. I found this disturbing enough that I haven't yet made sense of the rest of the text.
</blockquote></details>

Oops, those got left behind during rework.  Fixed now.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[systems/framework/diagram_builder.h, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvWDwc7Djty6tBTLXa5:-MvWDwc7Djty6tBTLXa6:b-eigtgq) ([raw file](https://github.com/robotlocomotion/drake/blob/74c76a118d7f9a7c3d3b6be4d48d38d1863d768c/systems/framework/diagram_builder.h#L329)):*
As Rico says, the description seems to have come unmoored from signature, but looking at the implementation I think I understand now. Something like:
> Given an input port that is already connected to some data source, and a second input port that is not connected to anything, connect the second port to the same data source as the first one and return true. 

I like the sugar since it is tricky to implement. The name seems OK, but maybe something more explicit like `ConnectToSameDataSource()` or `ConnectByCopyingConnection()`?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[systems/framework/diagram_builder.h, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvWDwc7Djty6tBTLXa5:-MvXKP_r6V4wyO9i39sj:b-otmf37) ([raw file](https://github.com/robotlocomotion/drake/blob/74c76a118d7f9a7c3d3b6be4d48d38d1863d768c/systems/framework/diagram_builder.h#L329)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

As Rico says, the description seems to have come unmoored from signature, but looking at the implementation I think I understand now. Something like:
> Given an input port that is already connected to some data source, and a second input port that is not connected to anything, connect the second port to the same data source as the first one and return true. 

I like the sugar since it is tricky to implement. The name seems OK, but maybe something more explicit like `ConnectToSameDataSource()` or `ConnectByCopyingConnection()`?
</blockquote></details>

I'm more-or-less in agreement with Sherm on the function name -- Likewise doesn't seem suggestive enough to me (yet), or maybe I'm not quite convinced by the documentation.

I think one problem I'm still having is the conceptual overloading of `src` (the thing to imitate), and `source` (the upstream output or diagram port). Maybe change `src` to something like `exemplar`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[systems/framework/diagram_builder.h, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvWDwc7Djty6tBTLXa5:-MvZVjkz1tKHOOWzuMHo:b-8mw1ad) ([raw file](https://github.com/robotlocomotion/drake/blob/74c76a118d7f9a7c3d3b6be4d48d38d1863d768c/systems/framework/diagram_builder.h#L329)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm more-or-less in agreement with Sherm on the function name -- Likewise doesn't seem suggestive enough to me (yet), or maybe I'm not quite convinced by the documentation.

I think one problem I'm still having is the conceptual overloading of `src` (the thing to imitate), and `source` (the upstream output or diagram port). Maybe change `src` to something like `exemplar`?
</blockquote></details>

These are good points.  I tried to make a clarification pass all around.  Let me know if there are more things that could still improve.

**Review by sherm1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[systems/framework/diagram_builder.h, line 333 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvZc0Xg3dzYCJe8JaCI:-MvZc0Xg3dzYCJe8JaCJ:b-hz5e7l) ([raw file](https://github.com/robotlocomotion/drake/blob/cb436a89134f14f9afb068662bdc6e3f34223001/systems/framework/diagram_builder.h#L333)):*
> ```objc
>   /// have already been added to this diagram.
>   ///
>   /// @return True iff any connection or was made; or false when a no-op.
> ```

BTW "true" rather than "True"
___
*[systems/framework/diagram_builder.h, line 334 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvZcMPFEB62O5HLZoHu:-MvZcMPFEB62O5HLZoHv:b-bg3ljg) ([raw file](https://github.com/robotlocomotion/drake/blob/cb436a89134f14f9afb068662bdc6e3f34223001/systems/framework/diagram_builder.h#L334)):*
> ```objc
>   ///
>   /// @return True iff any connection or was made; or false when a no-op.
>   bool ConnectToSame(const InputPort<T>& exemplar, const InputPort<T>& dest);
> ```

BTW great idea to call this "exemplar" (h/t Rico)! And `ConnectToSame` is great too.

Is there a similar improvement possible for the second parameter? Brainstorming: recipient, follower, fanboy, receiver ?
___
*[systems/framework/diagram_builder.cc, line 212 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvZcoTl3Yw6GVHKivq7:-MvZcoTl3Yw6GVHKivq8:b51hxlu) ([raw file](https://github.com/robotlocomotion/drake/blob/cb436a89134f14f9afb068662bdc6e3f34223001/systems/framework/diagram_builder.cc#L212)):*
> ```cpp
> template <typename T>
> bool DiagramBuilder<T>::ConnectToSame(
>       const InputPort<T>& src, const InputPort<T>& dest) {
> ```

nit: exemplar

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri, @rpoyner-tri, and @sherm1)

___
*[systems/framework/diagram_builder.h, line 334 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16563#-MvZcMPFEB62O5HLZoHu:-MvZdxQY8ygTJsuqCCz4:b-vb1313) ([raw file](https://github.com/robotlocomotion/drake/blob/cb436a89134f14f9afb068662bdc6e3f34223001/systems/framework/diagram_builder.h#L334)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW great idea to call this "exemplar" (h/t Rico)! And `ConnectToSame` is great too.

Is there a similar improvement possible for the second parameter? Brainstorming: recipient, follower, fanboy, receiver ?
</blockquote></details>

We use "dest" throughout this class to refer to the input port that is being connected.  I'd prefer to keep that consistent here, as well.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 6 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16563#-:-Mv_lnorDbUwwzVKUlMR:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

___
*[systems/framework/diagram_builder.h, line 334 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16563#-Mv_k4sE4UpQH7KkX_xO:-Mv_k4sE4UpQH7KkX_xP:b-qhmwxw) ([raw file](https://github.com/robotlocomotion/drake/blob/cc0cd722f45ce02d796327ccd95a1e87104ddfb3/systems/framework/diagram_builder.h#L334)):*
> ```objc
>   ///
>   /// @return True iff any connection or was made; or false when a no-op.
>   bool ConnectToSame(const InputPort<T>& exemplar, const InputPort<T>& dest);
> ```

BTW I've been trying to decide how dangerous the silent no-op behavior could be for potential users. and I eventually decided I was OK with it.  Presumably some other piece of code is going to try to get a value from `dest` eventually, so either (1) the user is informed of the failure to connect the input port or (2) `dest` is also unused so whatever.

**Comment by jwnimmer-tri** [comment]
___
*[systems/framework/diagram_builder.h, line 334 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16563#-Mv_k4sE4UpQH7KkX_xO:-Mv_maF72OFxhOML6kNd:bot7v3l) ([raw file](https://github.com/robotlocomotion/drake/blob/cc0cd722f45ce02d796327ccd95a1e87104ddfb3/systems/framework/diagram_builder.h#L334)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I've been trying to decide how dangerous the silent no-op behavior could be for potential users. and I eventually decided I was OK with it.  Presumably some other piece of code is going to try to get a value from `dest` eventually, so either (1) the user is informed of the failure to connect the input port or (2) `dest` is also unused so whatever.
</blockquote></details>

Agreed.  Also, I hope that for cases where a failure to connect would cause a problem later, the caller would demand that the return value was `true` after this call.

**Pull request merged**
