### PR TITLE
Enable building things that didn't work on MSVC 2010

### LINKED ISSUE #1205: compilation error in QPLocomotionPlan.cpp on msvc 2011
it doesn't like these initializations (starting around lines 600)

```
const std::map<SupportLogicType, std::vector<bool> > QPLocomotionPlan::createSupportLogicMaps()
{
  std::map<SupportLogicType, std::vector<bool> > ret;
  ret[REQUIRE_SUPPORT] = { {true, true, true, true} };
  ret[ONLY_IF_FORCE_SENSED] = { {false, false, true, true} };
  ret[KINEMATIC_OR_SENSED] = { {false, true, true, true} };
  ret[PREVENT_SUPPORT] = { {false, false, false, false} };
  return ret;
}
```

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes #1205.

### CODE REVIEW

**Comment by tkoolen** [comment]
Fatal Java Exceptions on drake004...

**Comment by RussTedrake** [comment]
wow. you're not kidding about the fatal java errors.  what happened there?  restarting build.

**Comment by RussTedrake** [comment]
looking more carefully at drake004, the compiler was running out of heap space when compiling RigidBodyManipulator (possibly because there was another build happening in the background?).  if increased the size of the swap disk, which seems to have helped.  http://windows.microsoft.com/en-us/windows/change-virtual-memory-size#1TC=windows-7 )

**Comment by tkoolen** [comment]
drake006 failed to clone octomap, strange.

#1350 is based off of this branch and builds fine on drake006.

**Comment by RussTedrake** [comment]
Yup.  Don't consider that a blocker

**Pull request merged**
