### PR TITLE
[meshcat] Provides StartMeshcat() for Deepnote/Colab

### LINKED ISSUE #16099: [meshcat] Port StartMeshcat to Drake
@rpoyner-tri ... you probably recall the PR where you didn't want Meshcat in C++ to be able to advertise unconfirmed URLs.  My work-around at that time was the `StartMeshcat` python method in manipulation:

https://github.com/RussTedrake/manipulation/blob/b6d32c075dd78d268580b098378ccdb008640ec0/manipulation/meshcat_cpp_utils.py#L27

As we start to encourage the use of Drake+Meshcat on deepnote/colab, this is missing functionality; not a good reason to add a dependency on the entire manipulation repo.

Do you have any objections to moving this (python-only) method to Drake?  I believe it instantiates your previous recommendation, but want to confirm before I open the PR.

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #16099

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTZheb04DBywwabr58:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Is _geometry_extra.py missing from the changeset here? maybe not commited?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrT_XdG71Jotdrd9xWa:b-mvj2p8)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Ah yes. I guess you need that.  It's there now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTbie5A1zflFxUetNG:b-2yydra)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:confetti_ball: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTbzKP0f1lB0uk_t3N:br4fkav)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTdO4rCyEqGJD2fCLo:bnfp4nl)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTdeq91rgGn4o_zxfl:b-azei6o)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTntzsCW_kEuyzd6D4:b8qx53o)* status: missing label for release notes (waiting on @RussTedrake)

**Review by sherm1 — COMMENTED** [review]
Needs a release notes tag -- is this release notes: none?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16273#-:-MrTo4Ts5FOAQcv7H1V7:b5mp3nk)* status: missing label for release notes (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
I'm going to go with release notes:yes.  I *think* that is a CI flake.  Do you agree?

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please

**Comment by sherm1** [comment]
Looks like a flake to me also.

**Comment by RussTedrake** [comment]
I reran the failing configuration, and it passed.  So will merge.

**Pull request merged**
