### PR TITLE
[plant] Factor MakeDiscreteUpdateManager out into a separate header

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
As a result changes in CompliantContactManager and SAP related changes won't trigger recompiling MultibodyPlant all together.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677#-:-N8Vt_Nf3DBuZx0ZUlDL:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
I'm so happy you fixed this @xuchenhan-tri! thank you so much!
Only minor request to document how clever you are ;-)

:lgtm_strong: 

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677#-:-N8Z2PHv8aXORO6iJtq2:b-dg6qye)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8Yy1EQ8U1mlkSHwr0d):*
nit, "changes" twice in the same sentence is a bit weird.
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8YyAPy2PZM-wcpqimM):*
nit, I think you'd like to explain here that "changes in the headers" will no longer trigger the recompilation of MultibodyPlant. As of today changes in the cc files do not trigger MultibodyPlan's compilation but only changes in the headers. This is so nice!
___
*[`multibody/plant/multibody_plant.cc` line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8Z18903vDkHt_vhal-:-N8Z18915z3eLUupsorf:b-6cvo8d) ([raw file](https://github.com/robotlocomotion/drake/blob/323b3cb08b6ae55878fea3dfdc084fcf088bedd6/multibody/plant/multibody_plant.cc#L28)):*
> ```cpp
> #include "drake/multibody/plant/externally_applied_spatial_force.h"
> #include "drake/multibody/plant/hydroelastic_traction_calculator.h"
> #include "drake/multibody/plant/make_discrete_update_manager.h"
> ```

This is so subtle that can easily get missed. Even though I tried I couldn't figure out the right combination!
That is, in the bazel file `multibody_plnat_core` still depends on dicrete_update_manager, compliant_contact_manager and SAP.
However the trick I couldn't figure out is that the plant files do not include any of these headers. Smart!

Long story short, I'd like that to be captured somewhere in the source. Maybe document this trick in the `make_discrete_update_manager.h` file?
___
*[`multibody/plant/test/make_discrete_update_manager_test.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8Z2D09CrYWZd0Y--do:-N8Z2D09CrYWZd0Y--dp:b-ojvm4) ([raw file](https://github.com/robotlocomotion/drake/blob/323b3cb08b6ae55878fea3dfdc084fcf088bedd6/multibody/plant/test/make_discrete_update_manager_test.cc#L22)):*
> ```cpp
>   std::unique_ptr<DiscreteUpdateManager<AutoDiffXd>> autodiff_manager =
>       MakeDiscreteUpdateManager<AutoDiffXd>(DiscreteContactSolver::kSap);
> ```

minor, for consistency with test above, you might want to remove this space and add a space between the last EXPECT_TRUE and the DRAKE_EXPECT_THROWS

**Review by amcastro-tri — COMMENTED** [review]
+@sherm1 for platform please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677#-:-N8Z2qo1120G34JLFbU6:b-af1gxe)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few nits and some feature review comments remaining

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677#-:-N8ZUCkM1f-5_qfpgv7D:b-9xoosq)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/plant/make_discrete_update_manager.h` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8ZShC34WCDeSMQMsnZ:-N8ZShC34WCDeSMQMsn_:b-o8x5hr) ([raw file](https://github.com/robotlocomotion/drake/blob/323b3cb08b6ae55878fea3dfdc084fcf088bedd6/multibody/plant/make_discrete_update_manager.h#L17)):*
> ```objc
>  contact solver type is `kTamsi`.
>  @throws an exception if invoked with incompatible contact solver and scalar
>  type.
> ```

nit: we normally write this
`@throws std::exception if invoked ...`
___
*[`multibody/plant/test/make_discrete_update_manager_test.cc` line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8ZU3yn2SAvpXX7cYdw:-N8ZU3yn2SAvpXX7cYdx:b-3pijsa) ([raw file](https://github.com/robotlocomotion/drake/blob/323b3cb08b6ae55878fea3dfdc084fcf088bedd6/multibody/plant/test/make_discrete_update_manager_test.cc#L29)):*
> ```cpp
>                               "SAP.*not supported.*symbolic::Expression.");
> }
> GTEST_TEST(MakeDiscreteUpdateManagerTest, Tamsi) {
> ```

nit: insert blank line between tests

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677)* status: 2 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8_3Dnj9MVHntoGJbDf:bujco5k) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
> ```objc
> // classes) in multibody_plant.cc, we avoid recompiling MultibodyPlant every
> // time some concrete update manager changes. Instead, we only need to relink
> // them.
> ```

btw, nice!
Consider saying something else about how the BUILD.bazel field is wired up. It wasn't obvious to me that what mattered in terms of dependencies was who included what (vs. how we packed them together into a library with Bazel)

**Comment by xuchenhan-tri** [comment]
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8_OtiTCQE4NGLcF0S3:b-9l5hjs) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, nice!
Consider saying something else about how the BUILD.bazel field is wired up. It wasn't obvious to me that what mattered in terms of dependencies was who included what (vs. how we packed them together into a library with Bazel)
</blockquote></details>

I don't quite understand the requested clarification is. Can you provide some sample note that conveys what you think should be captured? I can work it into the comment.

I don't think there's anything special about how the BUILD file is set up here. We do what we do with every other library -- include just enough header and cc files so that the compiler can compile.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8__giZCnih6uR6UHQW:ber157l) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't quite understand the requested clarification is. Can you provide some sample note that conveys what you think should be captured? I can work it into the comment.

I don't think there's anything special about how the BUILD file is set up here. We do what we do with every other library -- include just enough header and cc files so that the compiler can compile.


</blockquote></details>

How bazel dealt with dependencies was not clear to me before this PR. Maybe it was to you?

That is; the bazel file says "place manager.h and plant.h in the same library". I thought that was enough to imply "if manager.h changes, then recompile plant.h/.cc files". Clearly my understanding was incorrect. Maybe obvious? but judging from the need to go and ask for help in Slack I believe it wasn't that obvious really?

**Comment by xuchenhan-tri** [comment]
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8_aWYR2rhZsVcuMp-i:b-r9hb5j) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

How bazel dealt with dependencies was not clear to me before this PR. Maybe it was to you?

That is; the bazel file says "place manager.h and plant.h in the same library". I thought that was enough to imply "if manager.h changes, then recompile plant.h/.cc files". Clearly my understanding was incorrect. Maybe obvious? but judging from the need to go and ask for help in Slack I believe it wasn't that obvious really?






</blockquote></details>

My understanding is that Bazel has nothing to do with compilation by itself, it simply feed the files and configs to the compiler and invokes it, and the compiler does the compiling. So to me this is a question about how "#include" and compilation work if some files are modified, not about Bazel.

Like I said above, if you can supply a note that you would put in if you were the author, I think it'd communicate better what you intend to capture in this file-level message.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8d2jaN2Tvmy6jjlH5C:bkkmsxc) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
> Like I said above, if you can supply a note that you would put in if you were the author, I think it'd communicate better what you intend to capture in this file-level message.

I still do not understand exactly why this particular combination works. So I would not even know what to put in the note!

> My understanding is that Bazel has nothing to do with compilation by itself, it simply feed the files and configs to the compiler and invokes it,

Clearly my understanding of Bazel is lacking then. If this is true, are you saying that bazel is simply calling `gcc -c` (to generate objects) followed `gcc -o` (to link) mindlessly?
Somone here is "caching" additional iformation. Someone remembers that `mbp.h` only depends on `make_discrete_update_manger.h` and nothing else. I thought that someone was bazel? The part that still confuses me in this process is that I still see `mbp.h` and `compliant_contact_manger.h` listed as part of the library, but it'd seem that that information alone is not what determines what gets compiled?  This is probably basic bazel knowledge, but since it took us some thinking to get it right, I think it'd be nice to explain (or link a reference?) what really happens. 
Maybe @jwnimmer-tri can say more about this?

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8dHiAt6AF7oEkXJj_C:b-hacyle) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> Like I said above, if you can supply a note that you would put in if you were the author, I think it'd communicate better what you intend to capture in this file-level message.

I still do not understand exactly why this particular combination works. So I would not even know what to put in the note!

> My understanding is that Bazel has nothing to do with compilation by itself, it simply feed the files and configs to the compiler and invokes it,

Clearly my understanding of Bazel is lacking then. If this is true, are you saying that bazel is simply calling `gcc -c` (to generate objects) followed `gcc -o` (to link) mindlessly?
Somone here is "caching" additional iformation. Someone remembers that `mbp.h` only depends on `make_discrete_update_manger.h` and nothing else. I thought that someone was bazel? The part that still confuses me in this process is that I still see `mbp.h` and `compliant_contact_manger.h` listed as part of the library, but it'd seem that that information alone is not what determines what gets compiled?  This is probably basic bazel knowledge, but since it took us some thinking to get it right, I think it'd be nice to explain (or link a reference?) what really happens. 
Maybe @jwnimmer-tri can say more about this?
</blockquote></details>

If you're happy with how it works in practice, I'd say just leave well enough along and move on.

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8dHnrxAwcTzIA1Un8d:b-lngsxa) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you're happy with how it works in practice, I'd say just leave well enough along and move on.
</blockquote></details>

... leave well enough alone* and ...

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/make_discrete_update_manager.h` line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17677#-N8_3Dnj9MVHntoGJbDe:-N8dIbXT7MVYSYbzLluS:be7b41s) ([raw file](https://github.com/robotlocomotion/drake/blob/a8f9d7a9b5ccea2e1128c760ac4fb70cd672885f/multibody/plant/make_discrete_update_manager.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... leave well enough alone* and ...
</blockquote></details>

oh, I'm very happy with this. I'd love to understand it better in case I can use similar tricks in the future.
That being said, my question might be super dumb so please feel free to move on and merge @xuchenhan-tri. 
You guys can always teach me how this actually works at a latter date.

**Comment by jwnimmer-tri** [comment]
@amcastro-tri When building C++ code, Bazel is aware of the `#include` statements graph.  It doesn't necessarily recompile all C++ files in a library when a library header changes.

**Review by rpoyner-tri — COMMENTED** [review]
More build pedantry: bazel has its own dependency graph built from the BUILD rules, but (for c/c++) that graph has to provide all the dependencies induced by include statements (caveats apply, but don't matter for Drake style). If the BUILD graph has too few dependencies, the build will fail with "can't find include file" or some such. On the other hand, Bazel doesn't stop you from including *more* dependencies than you need, and (AFAIK) will penalize incremental builds accordingly.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17677#-:-N8dSqlnCEnZJkIBYIw8:b-nr8im1)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
