### PR TITLE
[solvers] IbexSolver supports more constraints / costs

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15607)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@RussTedrake for feature-review, please.

**Review by RussTedrake — COMMENTED** [review]
+@ericcousineau-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15607#-:-MgvfZIb9VEDz9RyjNdK:bvtjo57)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with nits on testing

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15607#-:-MgvhzeW7AcyA3EjRvPc:b6qe2xl)* status: 3 unresolved discussions (waiting on @soonho-tri)

___
*[solvers/test/ibex_solver_test.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15607#-Mgvhb-f0d2Q-u_k0xqj:-Mgvhb-f0d2Q-u_k0xqk:b-jg82ko) ([raw file](https://github.com/robotlocomotion/drake/blob/4b8fbbf5965f047f4e1c226d19b60733bd98c656/solvers/test/ibex_solver_test.cc#L27)):*
> ```cpp
> class IbexSolverTest : public ::testing::Test {
>  protected:
>   void SetUp() override { x_ = prog_.NewContinuousVariables(3, "x"); }
> ```

nit Not sure why pre-defining `x_` to be of size 3 here, especially when different formulations use different sizes.

Can you remove `x_` from here?
___
*[solvers/test/ibex_solver_test.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15607#-MgvhmfoETuqwB7N23JK:-MgvhmfpDT6GYVo2y-5n:b65z9jr) ([raw file](https://github.com/robotlocomotion/drake/blob/4b8fbbf5965f047f4e1c226d19b60733bd98c656/solvers/test/ibex_solver_test.cc#L37)):*
> ```cpp
> // https://github.com/ibex-team/ibex-lib/blob/master/benchs/optim/easy/ex3_1_3.bch
> TEST_F(IbexSolverTest, IbexEasyEx3_1_3) {
>   MathematicalProgram prog;
> ```

nit This was converted to a fixture, but does not use `prog_` or `x_`.
___
*[solvers/test/ibex_solver_test.cc, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15607#-Mgvhu-04cMREljtLNzw:-Mgvhu-04cMREljtLNzx:b65z9jr) ([raw file](https://github.com/robotlocomotion/drake/blob/4b8fbbf5965f047f4e1c226d19b60733bd98c656/solvers/test/ibex_solver_test.cc#L70)):*
> ```cpp
> 
> TEST_F(IbexSolverTest, OnlyConstraints) {
>   MathematicalProgram prog;
> ```

nit This was converted to a fixture, but does not use `prog_` or `x_`.

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15607)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[solvers/test/ibex_solver_test.cc, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15607#-Mgvhb-f0d2Q-u_k0xqj:-MgvsuBMEqyottRdjJ2H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b8fbbf5965f047f4e1c226d19b60733bd98c656/solvers/test/ibex_solver_test.cc#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not sure why pre-defining `x_` to be of size 3 here, especially when different formulations use different sizes.

Can you remove `x_` from here?
</blockquote></details>

Done.
___
*[solvers/test/ibex_solver_test.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15607#-MgvhmfoETuqwB7N23JK:-MgvsvCD9jics5d5KpKk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b8fbbf5965f047f4e1c226d19b60733bd98c656/solvers/test/ibex_solver_test.cc#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This was converted to a fixture, but does not use `prog_` or `x_`.
</blockquote></details>

Done.
___
*[solvers/test/ibex_solver_test.cc, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15607#-Mgvhu-04cMREljtLNzw:-Mgvsvrs3iJ2K_XGdFZV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b8fbbf5965f047f4e1c226d19b60733bd98c656/solvers/test/ibex_solver_test.cc#L70)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This was converted to a fixture, but does not use `prog_` or `x_`.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15607)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @soonho-tri)

**Pull request merged**
