### PR TITLE
Adds to AutomotiveSimulator the ability to specify the initial state of a SimpleCar.

### PR DESCRIPTION
**Pull request by liangfok**
This allows us to start a simulation where each `SimpleCar` starts at a different location.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5473)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jadecastro for feature review since this will allow you to better initialize a world for testing MOBIL / IDM.
+@jwnimmer-tri for platform and car reviews please.

Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-:-Kf-kbD9zzXDjNyV_vIl:bdn6xq7)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 520 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6pZ3yxrqwjgOMypPA:-Kf6pZ3yxrqwjgOMypPB:be03ied) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/automotive_simulator.cc#L520)):*
> ```cpp
> 
>   // Initialize the state of the SimpleCars.
>   for (auto& pair : simple_car_initial_states_) {
> ```

`const auto& pair`

---

*[drake/automotive/automotive_simulator.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6pNqtRlEC-du4h91F:-Kf6pNquI-3FXYwULTUH:b-tzwmkd) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/automotive_simulator.h#L251)):*
> ```objc
>   std::unique_ptr<const maliput::utility::InfiniteCircuitRoad> endless_road_{};
>   std::map<EndlessRoadCar<T>*, EndlessRoadCarState<T>> endless_road_cars_;
>   std::map<SimpleCar<T>*, SimpleCarState<T>> simple_car_initial_states_;
> ```

I don't think this is used during simulation, only during building, so as such it's in the wrong section of member fields?

---

*[drake/automotive/automotive_simulator.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6pyKPiGAohHbZ2rWf:-Kf6pyKPiGAohHbZ2rWg:bbbuu9y) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/automotive_simulator.h#L251)):*
> ```objc
>   std::unique_ptr<const maliput::utility::InfiniteCircuitRoad> endless_road_{};
>   std::map<EndlessRoadCar<T>*, EndlessRoadCarState<T>> endless_road_cars_;
>   std::map<SimpleCar<T>*, SimpleCarState<T>> simple_car_initial_states_;
> ```

We aren't modifying the`SimpleCar` from this map, so the key should be `const SimpleCar<T>*`.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6rUcWsPeB4DkybB-c:-Kf6rUcWsPeB4DkybB-d:b-hpqwwl) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/test/automotive_simulator_test.cc#L171)):*
> ```cpp
>   lcm::DrakeMockLcm* mock_lcm =
>       dynamic_cast<lcm::DrakeMockLcm*>(simulator->get_lcm());
>   DRAKE_DEMAND(mock_lcm != nullptr);
> ```

ASSERT_NE

---

*[drake/automotive/test/automotive_simulator_test.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6rqzYNcsleRlX8uGA:-Kf6rqzZkyGxDJmY9OmD:bq8tdh3) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/test/automotive_simulator_test.cc#L174)):*
> ```cpp
>   const lcmt_simple_car_state_t state_message =
>       mock_lcm->DecodeLastPublishedMessageAs<lcmt_simple_car_state_t>(
>           "0_SIMPLE_CAR_STATE");
> ```

FYI Checking the LCM output is an obscene way to test this new feature, but given that I don't immediately have a better example to cite, I'll let this go and fix it myself in a follow-up PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5473)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6unTFkQV1X11FhNVe:-Kf6unTFkQV1X11FhNVf:b-hfer1a) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/test/automotive_simulator_test.cc#L158)):*
> ```cpp
>   initial_state.set_x(kX);
>   initial_state.set_y(kY);
>   initial_state.set_heading(M_PI_2);
> ```

BTW, `kheading`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5473)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 520 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6pZ3yxrqwjgOMypPA:-Kf8CK3KjyJGu4AgjDg4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/automotive_simulator.cc#L520)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`const auto& pair`
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6pNqtRlEC-du4h91F:-Kf8BnaCKMz-8Hh00T-6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/automotive_simulator.h#L251)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think this is used during simulation, only during building, so as such it's in the wrong section of member fields?
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 251 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6pyKPiGAohHbZ2rWf:-Kf8BqBIJ7EqXXuD6AoX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/automotive_simulator.h#L251)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We aren't modifying the`SimpleCar` from this map, so the key should be `const SimpleCar<T>*`.
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6unTFkQV1X11FhNVe:-Kf8BxUSyDp6CtQuCeZh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/test/automotive_simulator_test.cc#L158)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, `kheading`?
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 171 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6rUcWsPeB4DkybB-c:-Kf8C2fPgbR6rH0JZ0VO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/test/automotive_simulator_test.cc#L171)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

ASSERT_NE
</blockquote></details>

Done.

---

*[drake/automotive/test/automotive_simulator_test.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-Kf6rqzYNcsleRlX8uGA:-Kf8C4NC0KYYnras8f2K:b-cztha6) ([raw file](https://github.com/robotlocomotion/drake/blob/c59a9477641e9b7a367ac652feddc09f2e9e32b5/drake/automotive/test/automotive_simulator_test.cc#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Checking the LCM output is an obscene way to test this new feature, but given that I don't immediately have a better example to cite, I'll let this go and fix it myself in a follow-up PR.
</blockquote></details>

OK. Thanks. I'll be happy to review the redesign.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5473)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-:-Kf8Mr3EOJ77IBXPwt2O:bnfp4nl)*

**Comment by jadecastro** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5473#-:-Kf8Yf5YMvoguyGKvpys:bnfp4nl)*

**Pull request merged**
