### PR TITLE
Use quoted includes for lcm and external lcmtypes

### PR DESCRIPTION
**Pull request by jamiesnape**
This was the other hotspot for system conflicts, if I recall correctly from Slack.

Toward #8155.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8151)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
So this turns out to be a partial fix to #8155, but if possible I would like to get it into master before it gets stale and then address the rest of that issue.

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review and +@jwnimmer-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8151#-:-L6I1XT3FLbQbmAYEyXz:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8151#-:-L6I4oXIZS6-ZTUoJJlc:bnfp4nl)*

**Pull request merged**
