### PR TITLE
Use doxygen 1.8.15 on Mac

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #13964. FYI @BetsyMcPhail.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14169)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: code review.

+@soonho-tri for local testing, please.
https://drake.mit.edu/documentation_instructions.html#when-using-bazel

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14169#-:-MJ8078M9FazxFf2jHbz:b3bqk4e)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14169#-:-MJ867hUB2eu3ESSbomX:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform)

**Pull request merged**
