### PR TITLE
[py common] Centralize some test utilities

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
To aid in the solution to a pydrake dependency cycle (#20465), it's convenient for pydrake.autodiffutils and pydrake.math to simply be Python modules, not Python packages. (A package is a module that has sub-modules.)

To that end, we ditch the `test` packages and move those modules into the pydrake.common.test_utilities package, instead.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20464)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for both reviews, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20464#-:-NiBTIa0AxkyMChABfR2:bks4n6x)* status: 1 unresolved discussion

___
*[`bindings/pydrake/common/test_utilities/BUILD.bazel` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20464#-NiBRkqn97I9N5xsnl-6:-NiBRkqoBBnqpLC0rafE:b-eh1zan) ([raw file](https://github.com/RobotLocomotion/drake/blob/8089d6eb33a41014b1a66083446becafb2c8b8d6/bindings/pydrake/common/test_utilities/BUILD.bazel#L47)):*
> ```Starlark
> 
> drake_pybind_library(
>     name = "autodiffutils_test_util_py",
> ```

BTW, I'm curious why we name the module `autodiffutils` instead of just `autodiff` to begin with.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20464)* status: 1 unresolved discussion

___
*[`bindings/pydrake/common/test_utilities/BUILD.bazel` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20464#-NiBRkqn97I9N5xsnl-6:-NiBU5830r4EMKKCfk0X:b-n55p3n) ([raw file](https://github.com/RobotLocomotion/drake/blob/8089d6eb33a41014b1a66083446becafb2c8b8d6/bindings/pydrake/common/test_utilities/BUILD.bazel#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm curious why we name the module `autodiffutils` instead of just `autodiff` to begin with.
</blockquote></details>

Not sure if you're asking about the `pydrake.autodiffutils` name or the test utility name, but anyway the `pydrake.autodiffutils` is just a bad legacy choice that we haven't renamed yet, and the test utililty name just mimics that name.

Down the road, my hope is to just move everything in `pydrake.autodiffutils` into somewhere else (either `pydrake.common` or `pydrake.math`) and deprecate the weird name for removal (rather than trying to rename it).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20464)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

___
*[`bindings/pydrake/common/test_utilities/BUILD.bazel` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20464#-NiBRkqn97I9N5xsnl-6:-NiBYy-I19jWmWBRnwqP:b-jrybhz) ([raw file](https://github.com/RobotLocomotion/drake/blob/8089d6eb33a41014b1a66083446becafb2c8b8d6/bindings/pydrake/common/test_utilities/BUILD.bazel#L47)):*
> if you're asking about the `pydrake.autodiffutils` name

yes, that.

> Down the road, my hope is to just move everything in `pydrake.autodiffutils` into somewhere else (either `pydrake.common` or `pydrake.math`) and deprecate the weird name for removal (rather than trying to rename it).

That sounds good, thanks!

**Pull request merged**
