### PR TITLE
[WIP] Add warning if pydrake log redirection happens in non-main thread

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20755)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
Relates to #19680 - we have again been bitten by a deadlock resulting from logging redirection from bound multithreaded C++ code. While a few of us at TRI are familiar enough with the issue to quickly diagnose it, it is rarely one of these people who initially encounters the deadlock, let alone users outside TRI who are less familiar with this part of pydrake. This is an attempt at explicitly warning the user if they are about to encounter the buggy behavior; ideally even if they get a deadlock, the last thing printed will be a warning sufficient to identify and fix their problem.

@EricCousineau-TRI @ggould-tri @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
Could you paint a bit more of a picture for how we get into this situation?

The logging redirect happens upon `import pydrake` (or any `import pydrake.foo` or `from pydrake.foo import [bar]`, which necessarily implies `import pydrake` under the hood first).  Are you saying there are times where Python code launches worker threads, and then one those does `import pydrake` but where the main thread has not yet imported `pydrake`?  Or is the problem that two threads execute `MaybeRedirectPythonLogging` concurrently, leading to data races during the setup? 

Maybe you could post some code sample that hazards the deadlock.  We have a bunch of logging-vs-threading tests under `drake/bindings/pydrake/common/test/*.py` and ideally we'd capture this new situation with another regression test there.

**Comment by jwnimmer-tri** [comment]
Ah.  Maybe you're not trying to say that initializing the logging is the problem, but rather that if multiple worker threads are all logging at once, we can get a deadlock?  That's _supposed_ to work correctly, so if that is the problem then we need to reproduce a sample and fix the actual bug, not issue a warning.  We shouldn't be yelling merely because different worker threads are all logging at once.  It certainly might slow things down to have threads fight with each other to be able to log, but it should never deadlock.  If it's deadlocking, there is a logic error somewhere.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20755)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @calderpg-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20755#-NniWrKw1HLT6ICupREl:-NniWrKx4RbA6keCViuN:bpdawwa) (no related file):*
Expanding on / redundant with  Jeremy's comment, this needs a test that (even if unreliably) reproduces the failure case.

___

**Review by calderpg-tri — COMMENTED** [review]
> Maybe you're not trying to say that initializing the logging is the problem, but rather that if multiple worker threads are all logging at once, we can get a deadlock? 

This is the issue, same as what motivated #19680: if you have multithreaded operations bound and logging occurs in those threads, you can get deadlock (or maybe poor performance?) when the spdlog redirection is enabled.

> That's _supposed_ to work correctly, so if that is the problem then we need to reproduce a sample and fix the actual bug, not issue a warning.

I don't think it's ever worked. Both the incidents motivating this and #19680 happened well after #16724 that I understand was intended to make this work.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20755#-:-Nnie1WxE0WxeG-1Qp-0:b-gfoinb)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by jwnimmer-tri** [comment]
> I don't think it's ever worked.

Did you properly [release the GIL](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil) in the binding that launches C++ worker threads?

Anyway, I believe there _is_ some problem here, but we can't meaningfully discuss it until you provide sample code to demonstrate the failure mode so that we're all on the same page.

**Review by calderpg-tri — COMMENTED** [review]
> Did you properly [release the GIL](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil) in the binding that launches C++ worker threads?

I don't see any `gil_scoped_release` in Drake (outside of text logging redirection) or anzu, so the answer has to be no. Scattering `gil_scoped_release` calls around anzu and hoping that doesn't cause other problems is hardly a good solution either, though, and that still doesn't address the need for debugging help when the deadlock happens.

The most recent code which reliably encounters this deadlock is in anzu, and looks roughly like this:
1. Create a bound `RobotModelsAndInterfaces` that uses `RosImageBasedPointCloud2Sensor` sensors
2. Within `RosImageBasedPointCloud2Sensor::Start()`, a long-lived worker thread is created, which logs when the pointcloud->frame mapping is first determined from received data
3. Deadlock occurs when the first worker thread tries to log

Obviously too much code is involved there to be a useful example. I believe one of the simplest cases that produces deadlock I've seen looks like
```
# Set python logging to the equivalent of debug or trace

checker = pydrake.planning.SceneGraphCollisionChecker(...)

# q1 and q2 need to be far enough away require multiple intermediate checks
q1 = np.array([-1.0] * checker.plant().num_positions())
q2 = np.array([1.0] * checker.plant().num_positions())

edge_free = checker.CheckEdgeCollisionFreeParallel(q1=q1, q2=q2, parallelize=True)
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20755#-:-NnikxZBBYOyOVcjFP4I:b-f2uzee)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by jwnimmer-tri** [comment]
> [Fixing the bugs] doesn't address the need for debugging help when the deadlock happens.

Full agree.  I would love to have any kind of warning or exception or console breadcrumb or anything when this happens.

My current understanding of this WIP seems like it would have false positives -- it would trigger even when the `py::gil_scoped_acquire` was going to be OK.

I don't immediately have any ideas how to accomplish a better warning, but we can work on it.

I wonder if people tripping on this typically look at a core file of the stuck program?  We could probably have the backtrace have a symbol something like `if_you_see_this_your_python_logging_got_stuck` in it.  Or maybe if we dig inside the `py::gil_scoped_acquire` implementation we can find a way to timeout and then throw or something.

> I believe one of the simplest cases that produces deadlock I've seen looks like ...

Good idea.  I was able to turn that into a regression test as part of #20759.  (The only trick was to make sure there was a collision in play; it looks like we only spdlog from worker threads when things are actually in collision; we don't have progress logging that I can see.)

> I don't see any gil_scoped_release in Drake (outside of text logging redirection) ..., so the answer has to be no.

Right indeed -- the bindings we added last year for parallelized collision checking called from Python were broken.  The changes in #20759 fix that problem.  We can use that PR to discuss sugar / style guide / linters for how to make that more robust.

> Scattering gil_scoped_release calls around anzu and hoping that doesn't cause other problems is hardly a good solution either, though ...

It might be somewhat challenging, but it seems like basically the right approach?  I'm curious where the pain points would be.  Generally speaking, as I understand the rules only bindings code that operates on python types like `py::str` directly needs to care about it.  Any code bindings that only speaks vanilla C++ will be fine.  The GIL is re-acquired during any `std::function` callbacks, or virtual overrides of C++ that trampoline into Python.  We could use some Anzu WIP PRs to see/discuss whether the approach is viable, but my gut feeling is that places which need scoped_release will be obvious -- they either touch `Parallelism` in some way, or they are top-level long-running objects with functions like `Start()` that are not too hard to track down.  Even reading all of the bindings code over again line by line wouldn't really take _that_ long.

**Comment by AlexandreAmice** [comment]
FWIW. I just got bit by this when writing the `IrisFromCliqueCover` code. In this code, I have IRIS working in many worker threads which works correctly in my C++ tests, but other students have encountered deadlock issues when running my Python bindings. Hopefully this thread can help resolve my issue.

**Comment by ggould-tri** [comment]
@AlexandreAmice Is there any chance you can share your code / diff / whatever here?  It would be good to see a worked example so that we can figure out what different affordances, APIs, or documentation that we should have presented, and where any such documentation could have been encountered.

**Comment by AlexandreAmice** [comment]
> @AlexandreAmice Is there any chance you can share your code / diff / whatever here? It would be good to see a worked example so that we can figure out what different affordances, APIs, or documentation that we should have presented, and where any such documentation could have been encountered.

The example I have in mind comes from #20831. In that PR, Iris gets called from worker threads. I had a labmate copy and paste [this test](https://github.com/AlexandreAmice/drake/blob/bd5dd0974d7afc2d49511810217aa52bcb35b4c2/bindings/pydrake/planning/test/iris_from_clique_cover_test.py#L80) into a normal python file and run the file. Her code deadlocked silently. This is particularly concerning given that if you run this with `bazel build bindings/pydrake/planning:py/iris_from_clique_cover_test` everything runs fine.

**Comment by jwnimmer-tri** [comment]
> Her code deadlocked silently.

Yes, I think we all agree that if we can find a way to give an error or warning message in case of a deadlock, that would be wonderful!  I don't think we have a good way of doing that yet.

The obvious answer would be to set a timeout on the try-lock of the GIL (and then print a message if we hit the timeouit), but the CPython API does not appear to offer any timeout option that I could find.

> The example I have in mind comes from https://github.com/RobotLocomotion/drake/pull/20831.

Platform review of that PR would have identified the bug in the bindings: when a function takes a `parallelism` as an argument, then its binding must have the `py::call_guard<py::gil_scoped_release>(),` annotation to release the GIL.

**Review by calderpg-tri — COMMENTED** [review]
r2 has an approach for warning if the `gil_scoped_acquire` takes too long. It feels like it might be too expensive, particularly in the (presumably common) uncontended case.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20755#-:-NrY8i6x2bQtTq-kgM2v:bot17oj)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by ggould-tri — COMMENTED** [review]
I think spawning a new thread on every log message is too expensive.  A single static thread that periodically checks a `last_time_someone_tried_to_acquire_the_gil_` atomic time or something like that would be more reasonable IMO.

I do wish there were a timeoutful version of the scoped lock object, but it's not immediately clear to me from the source that that's possible.  I wonder if there's a design possible where you create a wrapper around `gil_scoped_acquire` that wraps it in a `std::timed_mutex` in a simple RAII box.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20755#-:-Nrf3OvZCYAZ7X9uGP5l:bahyjc7)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Comment by jwnimmer-tri** [comment]
The discussion is good, but the forward progress seems to have stalled.

Closing as abandoned. When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
