### PR TITLE
Partition private headers into their own library

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

Because we want to fiddle with include paths, we *must* have all header files listed as `hdrs`; the `include_prefix` does not apply to `srcs`.

The full WIP feature branch is found at https://github.com/jwnimmer-tri/drake/commits/build-drake-folder-6996.  This PR is somewhat difficult to _test_ on its own; only when code moves up a folder is the `include_prefix` logic put to the test.  I think really the only way to test is to pull the feature branch, run `./hoist-up`, and then compile.  I think what I'm looking for in this review is to make sure the code, documentation, and rationale as-written is clearly expressed; my assertion is that we can defer until the final PR hits CI to prove that all of the corner cases have been covered.

In local testing, I've confirmed that Drake's list of installed files is unchanged by this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7478)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@ericcousineau-tri for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-:-Kz1xZa1P6AMhbgWr2o8:b-7eskas)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with one minor comment on consolidation, and one question clarifying a comment.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 277 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz4IlkAKgDWJWt3W2ko:-Kz4IlkBkFQaLLKfBirG:b-bjl3iz) ([raw file](https://github.com/robotlocomotion/drake/blob/2847f0038dbace3c96c2c297b1d67481354d32d3/tools/skylark/drake_cc.bzl#L277)):*
> ```Python
> 
>     By default, we produce only static libraries, to reduce compilation time
>     on all platforms, and to avoid mysterious dyld errors on OS X. This default
> ```

BTW minor aside Is this the SIP stuff for usage in Python? Or something else?

---

*[tools/skylark/drake_cc.bzl, line 432 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz4JLT5cGdXX3Bty9Ai:-Kz4JLT5cGdXX3Bty9Aj:bqomlld) ([raw file](https://github.com/robotlocomotion/drake/blob/2847f0038dbace3c96c2c297b1d67481354d32d3/tools/skylark/drake_cc.bzl#L432)):*
> ```Python
>     # Because we want to monkey with include paths, we *must* have all header
>     # files listed as hdrs; the include_prefix does not apply to srcs.
>     new_srcs, private_hdrs = _prune_private_hdrs(srcs)
> ```

BTW This looks like a copy+paste of the above two sections (modulo some testing and installation flags).
Could this be made into a utility function?
```
new_deps = _partition_private_headers(name, srcs, copts, deps, gcc_copts, cc_test, **kwargs)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-:-Kz4LKOlpMROybT4NxVV:boqocb5)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 277 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz4IlkAKgDWJWt3W2ko:-Kz8yxGs-ivdMPQcQR5r:bjzu4kn) ([raw file](https://github.com/robotlocomotion/drake/blob/2847f0038dbace3c96c2c297b1d67481354d32d3/tools/skylark/drake_cc.bzl#L277)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor aside Is this the SIP stuff for usage in Python? Or something else?
</blockquote></details>

OK I don't have the details at hand, that was from David's experimentation.  I have some vague memory that RTTI across dylibs was finicky on macOS, as well as using debugging environments like CLion.

---

*[tools/skylark/drake_cc.bzl, line 432 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz4JLT5cGdXX3Bty9Ai:-Kz9A7WsTkQFNyWM-6Gh:b-r958k1) ([raw file](https://github.com/robotlocomotion/drake/blob/2847f0038dbace3c96c2c297b1d67481354d32d3/tools/skylark/drake_cc.bzl#L432)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This looks like a copy+paste of the above two sections (modulo some testing and installation flags).
Could this be made into a utility function?
```
new_deps = _partition_private_headers(name, srcs, copts, deps, gcc_copts, cc_test, **kwargs)
```
</blockquote></details>

Done.  I think this is much improved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz9AC0o4Ml_Hc1iJBvb:-Kz9AC0o4Ml_Hc1iJBvc:bz4t2m9) (no related file):*
Do not merge; need more reviewers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478)*

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for additional feature review, please.

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 423 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz9Vfuby5DtEkOn288l:-Kz9VfucYzksxCyjQZlo:b9bsflv) ([raw file](https://github.com/robotlocomotion/drake/blob/3e4759d005044237452365a675ff95b1de8304f1/tools/skylark/drake_cc.bzl#L423)):*
> ```Python
>         copts = [],
>         gcc_copts = [],
>         testonly = 1,
> ```

What is the use case for a `drake_cc_test` that is not `testonly = 1`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 423 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz9Vfuby5DtEkOn288l:-Kz9X9KLWoBbq5HQ7ziu:b-a4de5p) ([raw file](https://github.com/robotlocomotion/drake/blob/3e4759d005044237452365a675ff95b1de8304f1/tools/skylark/drake_cc.bzl#L423)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

What is the use case for a `drake_cc_test` that is not `testonly = 1`?
</blockquote></details>

I was trying to find an elegant way to have testonly=1 consistently applied across all of the actions that come out of this rule.  I've pushed another attempt -- is the new way better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 423 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz9Vfuby5DtEkOn288l:-Kz9Y3iUjrF016nxkWVe:b-k614gh) ([raw file](https://github.com/robotlocomotion/drake/blob/3e4759d005044237452365a675ff95b1de8304f1/tools/skylark/drake_cc.bzl#L423)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was trying to find an elegant way to have testonly=1 consistently applied across all of the actions that come out of this rule.  I've pushed another attempt -- is the new way better?
</blockquote></details>

Yes, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-:-Kz9Y6wrQQ9dtSQ2SPgj:bnfp4nl)*

**Comment by sherm1** [comment]
Platform :lgtm:. One BTW -- ptal.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/skylark/drake_cc.bzl, line 348 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz9yW45wAKchrDOmHPA:-Kz9yW45wAKchrDOmHPB:bfgufrj) ([raw file](https://github.com/robotlocomotion/drake/blob/585c9798ed2fd28167258e60445726900a682b1d/tools/skylark/drake_cc.bzl#L348)):*
> ```Python
>         copts = [],
>         gcc_copts = [],
>         linkshared = 0,
> ```

BTW this seems unrelated to the rest of the PR. Is it just an opportunistic improvement to drake_cc_binary()? If so might be worth adding to the commit & PR description.

Since there aren't corresponding usage changes elsewhere I'm assuming any existing drake_cc_binary() calls are using default argument values by the time they get to this one. Is that right? Otherwise it would be possible that some of the trailing int arguments would acquire new meanings but there would be no diagnostic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-:-KzA-2VJA37ueAtq7cqM:b-ktg0jq)*

**Comment by jwnimmer-tri** [comment]
Feature reviewers please take another look.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/skylark/drake_cc.bzl, line 348 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-Kz9yW45wAKchrDOmHPA:-KzA4XJApJXbN0eHPsIK:bmrvdjo) ([raw file](https://github.com/robotlocomotion/drake/blob/585c9798ed2fd28167258e60445726900a682b1d/tools/skylark/drake_cc.bzl#L348)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems unrelated to the rest of the PR. Is it just an opportunistic improvement to drake_cc_binary()? If so might be worth adding to the commit & PR description.

Since there aren't corresponding usage changes elsewhere I'm assuming any existing drake_cc_binary() calls are using default argument values by the time they get to this one. Is that right? Otherwise it would be possible that some of the trailing int arguments would acquire new meanings but there would be no diagnostic.
</blockquote></details>

Done.

As far as disrupting the argument order goes, in Bazel files the convention is to call using named arguments at call sites when the declaration uses named defaults.  In other words, the only argument ever passed positionally here is `name`; call sites look like, e.g., `drake_cc_binary(name = "foo", deps = ["bar"], testonly = 1)`.  So I don't think the "acquire new meanings" concern ends up being relevant.

The reason it was added to the arguments here (with the same default as `native.cc_binary` has) was to prevent `kwargs` from containing a value for `linkshared` -- in the call to `_maybe_add...` below, we need to avoid propagating the `linkshared` choice from our _binary_ here to the private headers _library_.  By adding `linkshared` here and forwarding in the `native.cc_binary` only, it was effectively removed from the `kwargs` of `_maybe_add...`.

However, since I originally wrote this line, I've pivoted from making call sites clean up `kwargs`, to having `_maybe_add...` do it instead.  As such, I've removed the change here, and added a `kwargs.remove()` call to `_maybe_add...` to align with how `linkstatic` is handled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-:-KzA6xEdK6csQlNpyhS8:b-sis15e)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7478#-:-KzACp60AjcMEakjePBp:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Pull request merged**
