### PR TITLE
[doc] Add xuchenhan-tri as a platform reviwer

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16520)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 and +@xuchenhan-tri for review, please.a

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16520#-:-Mv5-YmE3QEZNX08OzUx:b-uwkowd)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16520)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm_strong: :lgtm_strong:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16520#-:-Mv6U0S15irldw9UzPGV:b4tkv4v)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

**Pull request merged**
