### PR TITLE
Revert "Modified URDF parser to support URDFs that include the world as a link."

### PR DESCRIPTION
**Pull request by jonathan-owens**
Reverts RobotLocomotion/drake#2171. See http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html.

Dear @liangfok,

The oncall build cop, @jonathan-owens, believes that your PR #2171 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration on presubmit, because additional
platforms and tests are built in postsubmit.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/job/windows-msvc-32-continuous-debug/197/changes

Therefore, the build cop has created this revert PR and started a complete
postsubmit build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2438)

### CODE REVIEW

**Comment by liangfok** [comment]
Browsing through the [log file](https://drake-jenkins.csail.mit.edu/job/windows-msvc-32-continuous-debug/197/consoleFull), this appears to be the error:

```
08:26:48 27: Assertion failed: (reinterpret_cast<size_t>(array) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****", file c:\projects\xnuv8cec\build\include\eigen3\eigen\src/Core/DenseStorage.h, line 109
...
08:26:48 31/41 Test #27: load_model_test ..........................***Failed    1.67 sec
```

[Here](https://drake-cdash.csail.mit.edu/testDetails.php?test=739017&build=25049) is the CDash report.

I am working on debugging this on a new branch: [feature/urdf_world_link_v2](https://github.com/liangfok/drake/tree/feature/urdf_world_link_v2).

**Comment by liangfok** [comment]
Initial attempt at reproducing bug in Windows 32-bit failed:

load_model_test_output

**Comment by liangfok** [comment]
My previous test omitted the new model-to-world unit tests. After restoring them, I was still unable to reproduce the error:

local_model_test_output_2

**Comment by jonathan-owens** [comment]
@liangfok Interesting. Since you can't reproduce it locally, try to re-open the pull request and see if it builds on the CI server.

**Comment by liangfok** [comment]
@jonathan-owens I created https://github.com/RobotLocomotion/drake/pull/2491. Can you initiate a continuous build test on it?

**Comment by jonathan-owens** [comment]
Done. FYI, all you have to do is say "test this please" in a comment on the PR and tag the `jenkins-build-bot`.

**Pull request merged**
