### PR TITLE
Add visit_polynomial and re-implement Degree using it

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5182)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-:-Kd2o6wEMKST2wjK8zTa:b-utjvo1)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review.

---

Reviewed 10 of 12 files at r1.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression_cell.cc, line 1577 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd2pDhOoRG39I_yiBkq:-Kd2pDhPDwYzM17ip_tL:b-javwre) ([raw file](https://github.com/robotlocomotion/drake/blob/9510580732ea8f6a6c658c0f73fb33f534b8274d/drake/common/symbolic_expression_cell.cc#L1577)):*
> ```cpp
> shared_ptr<ExpressionDiv> to_division(
>     const shared_ptr<ExpressionCell> expr_ptr) {
>   DRAKE_ASSERT(is_division(*expr_ptr));
> ```

Is it expensive to call `is_division()`? If not, I think we should use `DRAKE_DEMAND`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-:-Kd2tQbMjYIflwJBnRw3:b-xrxq0n)*

**Comment by soonho-tri** [comment]
@ggould-tri , it would be great if we can have your comments.

---

Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 1577 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd2pDhOoRG39I_yiBkq:-Kd30H9PHVbPcW4I1LXB:b8pijki) ([raw file](https://github.com/robotlocomotion/drake/blob/9510580732ea8f6a6c658c0f73fb33f534b8274d/drake/common/symbolic_expression_cell.cc#L1577)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is it expensive to call `is_division()`? If not, I think we should use `DRAKE_DEMAND`.
</blockquote></details>

I'd like to keep `DRAKE_ASSERT` because 1) `to_*` method is not exposed to general users (it's in `_cell.h` file, 2) I'm sure that `to_*` method is called either after its kind is checked or `is_*` method is called.

---

*[drake/common/symbolic_expression_visitor.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd30hfBnpeNiQ3WIJhs:-Kd30hfC1bRLT3EaN2En:b-25jicy) ([raw file](https://github.com/robotlocomotion/drake/blob/9510580732ea8f6a6c658c0f73fb33f534b8274d/drake/common/symbolic_expression_visitor.h#L23)):*
> ```objc
> /// \pre{e.is_polynomial() is true.}
> template <typename Result, typename Visitor, typename... Args>
> Result visit_polynomial(const Visitor& v, const Expression& e, Args&&... args) {
> ```

I forgot to rename this to `VisitPolynomial`. I will fix it soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-:-Kd305_eBoTvZs_B7gXj:bq80bax)*

**Comment by soonho-tri** [comment]
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd30te6Juh2F2EHb3eb:-Kd30te6Juh2F2EHb3ec:bbl2l96) ([raw file](https://github.com/robotlocomotion/drake/blob/9510580732ea8f6a6c658c0f73fb33f534b8274d/drake/common/monomial.cc#L215)):*
> ```cpp
> 
> int Degree(const Expression& e, const Variables& vars) {
>   return visit_polynomial<int>(DegreeVisitor(), e, vars);
> ```

@jwnimmer-tri , I was not sure if `DegreeVisitor()` part is an overhead or not (because `Degree` function is recursively called by DegreeVisitor::operator()` function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Comment by soonho-tri** [comment]
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_visitor.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd30hfBnpeNiQ3WIJhs:-Kd38_w2CvyOvEJAVSEK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9510580732ea8f6a6c658c0f73fb33f534b8274d/drake/common/symbolic_expression_visitor.h#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I forgot to rename this to `VisitPolynomial`. I will fix it soon.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Comment by hongkai-dai** [comment]
-@jwnimmer-tri for platform review, +@ggould-tri for platform review.

---

Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-:-Kd3X6Zi_T_cNIGUmf6D:b5vo7ky)*

**Comment by soonho-tri** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/monomial.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd30te6Juh2F2EHb3eb:-Kd63SgAgHvOqYEClrPB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9510580732ea8f6a6c658c0f73fb33f534b8274d/drake/common/monomial.cc#L215)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@jwnimmer-tri , I was not sure if `DegreeVisitor()` part is an overhead or not (because `Degree` function is recursively called by DegreeVisitor::operator()` function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Comment by ggould-tri** [comment]
This is really nice code, and a great improvement in factoring. :lgtm: pending a couple of nits below.

---

Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 199 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6TJ_4AFkkqoZcfpZ3:-Kd6TJ_4AFkkqoZcfpZ4:bgr71ma) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/monomial.cc#L199)):*
> ```cpp
>           const Expression& base{p.first};
>           const Expression& exponent{p.second};
>           return degree +
> ```

FYI -- The indentation here seems curious (indent-matching on "return", different indent of the `+` and `*` operends).  Check that your formatter likes it.

---

*[drake/common/symbolic_expression_visitor.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6UOpAOQMNaIJPlNb0:-Kd6UOpBAHYibVLqKuOB:bobjgo8) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/symbolic_expression_visitor.h#L19)):*
> ```objc
> ///
> /// See the implementation of @c DegreeVisitor class and @c Degree function in
> /// drake/common/monomial.cc as an example usage.
> ```

This is a super-helpful comment!  Thanks!

---

*[drake/common/test/monomial_test.cc, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6VFreJt94410B3yfg:-Kd6VFrf5WcvwGlfTsr6:bd5d7pv) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/test/monomial_test.cc#L457)):*
> ```cpp
>   EXPECT_EQ(Degree(e10, {var_y_, var_z_}), 0);
>   EXPECT_EQ(Degree(e10, {var_x_, var_y_, var_z_}), 1);
>   EXPECT_EQ(Degree(e10), 1);
> ```

The only things I don't see tested here are that degree is invariant under commutativity and associativity; consider adding cases to demonstrate those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-:-Kd6W1SZzYrxIDOJxESo:b4mh0np)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 199 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6TJ_4AFkkqoZcfpZ3:-Kd6XJsbfBlGlOqA8RZN:b-40n2gx) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/monomial.cc#L199)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- The indentation here seems curious (indent-matching on "return", different indent of the `+` and `*` operends).  Check that your formatter likes it.
</blockquote></details>

I'm using `clang-format-4.0`. I just double-checked that this was clang-format formatted.

---

*[drake/common/test/monomial_test.cc, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6VFreJt94410B3yfg:-Kd6c92woA03Xg29EFYf:b-i043qx) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/test/monomial_test.cc#L457)):*
> degree is invariant under commutativity and associativity

Do you mean something like followings?

```c++
EXPECT_EQ(Degree(e1 + e2), Degree(e2 + e1));
EXPECT_EQ(Degree(e1 * e2), Degree(e2 * e1));
...
EXPECT_EQ(Degree(e1 + (e2 + e3)), Degree((e1 + e2) + e3));
EXPECT_EQ(Degree(e1 * (e2 * e3)), Degree((e1 * e2) * e3));
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 199 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6TJ_4AFkkqoZcfpZ3:-Kd6cq-v1jhGQ8_LjNxA:b-gtaj7j) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/monomial.cc#L199)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm using `clang-format-4.0`. I just double-checked that this was clang-format formatted.
</blockquote></details>

Huh, TIL.

---

*[drake/common/test/monomial_test.cc, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6VFreJt94410B3yfg:-Kd6ctCDDv5_yKdwg728:b-vxyff9) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/test/monomial_test.cc#L457)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> degree is invariant under commutativity and associativity

Do you mean something like followings?

```c++
EXPECT_EQ(Degree(e1 + e2), Degree(e2 + e1));
EXPECT_EQ(Degree(e1 * e2), Degree(e2 * e1));
...
EXPECT_EQ(Degree(e1 + (e2 + e3)), Degree((e1 + e2) + e3));
EXPECT_EQ(Degree(e1 * (e2 * e3)), Degree((e1 * e2) * e3));
...
```

</blockquote></details>

Yes.  (Old `Polynomial` had this bug).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/monomial_test.cc, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6VFreJt94410B3yfg:-Kd6dAmMgJD6cbBS5whS:b-k9tqkn) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/test/monomial_test.cc#L457)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Yes.  (Old `Polynomial` had this bug).
</blockquote></details>

Thanks for the confirmation.

Actually we normalize additive and multiplicative expressions so the following pairs should be structurally equal:
```
e1 + e2, e2 + e1
e1 * e2, e2 * e1
...
e1 + (e2 + e3), e1 + (e2 + e3)
(e1 + e2) + e3, (e1 + e2) + e3
...
```

and when we have this structural equality, we have the invariance for free.

If you don't mind, I'll have another PR adding those tests to `symbolic_expression_test.cc` file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/monomial_test.cc, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5182#-Kd6VFreJt94410B3yfg:-Kd6fviC43cBubKQ2bFC:brxqzbq) ([raw file](https://github.com/robotlocomotion/drake/blob/41cd759640d1f9bfe1cf01280c059ebbf549e147/drake/common/test/monomial_test.cc#L457)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Thanks for the confirmation.

Actually we normalize additive and multiplicative expressions so the following pairs should be structurally equal:
```
e1 + e2, e2 + e1
e1 * e2, e2 * e1
...
e1 + (e2 + e3), e1 + (e2 + e3)
(e1 + e2) + e3, (e1 + e2) + e3
...
```

and when we have this structural equality, we have the invariance for free.

If you don't mind, I'll have another PR adding those tests to `symbolic_expression_test.cc` file.
</blockquote></details>

Sounds great

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5182)*

**Pull request merged**
