### PR TITLE
workspace: Upgrade libsdformat to latest release 9.2.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13201)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI As of libsdformat 9.2, calling `HasElement("friction")` on a `<surface/>` now returns false (used to be true), I assume because `sdf::Surface` got added as of 9.2.  Can you push a patch to fix Drake (or ask OSRC to)?

Doing `bazel test //multibody/parsing:common_parser_test` is a quick way to see the failure.

**Comment by EricCousineau-TRI** [comment]
Gotcha, will try it out.
Also a good point to see how we can avoid silent errors like this in the future. Thanks!

**Comment by EricCousineau-TRI** [comment]
Code in question, I believe:
https://github.com/RobotLocomotion/drake/blob/13e0024dc29c94f8cba75cf4d43adfd369eaf656/multibody/parsing/detail_scene_graph.cc#L434-L449

**Comment by jwnimmer-tri** [comment]
Sorry, I should have hyperlinked it.  For me, it was
https://github.com/RobotLocomotion/drake/blob/13e0024dc29c94f8cba75cf4d43adfd369eaf656/multibody/parsing/detail_scene_graph.cc#L472
```
Catchpoint 1 (exception thrown), 0x00007ffff7aded1d in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7aded1d in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555556173e5 in drake::multibody::internal::(anonymous namespace)::GetChildElementOrThrow(sdf::v9::Element const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#2  0x000055555561840e in drake::multibody::internal::MakeCoulombFrictionFromSdfCollisionOde(sdf::v9::Collision const&) ()
#3  0x000055555561aa5b in drake::multibody::internal::MakeProximityPropertiesForCollision(sdf::v9::Collision const&) ()
#4  0x0000555555615880 in drake::multibody::internal::(anonymous namespace)::AddModelFromSpecification(sdf::v9::Model const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, drake::multibody::MultibodyPlant<double>*, drake::multibody::PackageMap const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
...
```

But probably, both sites are broken anyway.

**Comment by scpeters** [comment]
I think the assumption in the following comment is incorrect:

https://github.com/RobotLocomotion/drake/blob/13e0024dc29c94f8cba75cf4d43adfd369eaf656/multibody/parsing/detail_scene_graph.cc#L470-L474

A `<surface>` element can hold a number of different types of parameters but is not required to contain the `//surface/friction/ode/mu*` parameters.

**Comment by scpeters** [comment]
I think the behavior change is caused by the following line of code that adds an empty `<surface/>` element to any `<collision>` elements that don't yet have a `<surface>`. I'll go ahead an add a `HasElement` check before calling that `Load` function, but I think the code I linked above in detail_scene_graph is brittle and should improve its logic.

**Comment by scpeters** [comment]
reverting the behavior change in https://github.com/osrf/sdformat/pull/268, and available for discussion about how to reduce the brittleness of the afore-mentioned code

**Comment by EricCousineau-TRI** [comment]
> A <surface> element can hold a number of different types of parameters but is not required to contain the //surface/friction/ode/mu* parameters.

Gotcha. It's stated in the spec (1.7) as being optional:
http://sdformat.org/spec?ver=1.7&elem=collision#friction_ode

So in this case, just change the logic to not require them?

Also, for solving this acute PR, I will push (fast-forward) onto Jeremy's current branch, but with your PR's commit to see if it solves the issue without changes to Drake.

After that, will file an additional PR to Drake that makes it less brittle, without the workspace bump.

Both should pass, and should be able to be merged independently.

**Comment by EricCousineau-TRI** [comment]
Steve's PR fixes the failure in `detail_scene_graph_test`, and I'd assume elsewhere:
https://github.com/jwnimmer-tri/drake/pull/5

**Comment by jwnimmer-tri** [comment]
Thanks for the investigation and fixes, @scpeters and @EricCousineau-TRI. I'm not surprised Drake's parser was brittle.

It's possible that @amcastro-tri's intent was to subset the domain of valid inputs -- that Drake would only accept a subset of the files that sdformat specifies.  I agree that doing so is suboptimal in this case, even though for other cases it's fine in general for Drake to only support a subset of sdformat.

**Comment by jwnimmer-tri** [comment]
Yes the "1.0" defaults are documented http://sdformat.org/spec?ver=1.7&elem=collision#ode_mu

**Comment by EricCousineau-TRI** [comment]
Er, for simplicity, I'm going to close this in lieu of https://github.com/RobotLocomotion/drake/pull/13206.
I will make sure that this upgrade is called out in the commit text.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews per schedule (tomorrow), please.

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/sdformat/3bbd303.patch, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/13201#-M7OGwU6E0VuFZqps-Th:-M7OL4t50XUEeJw5B_TW:b-hev6p) ([raw file](https://github.com/robotlocomotion/drake/blob/d75d2f062b895b768be67bf793b4063b4f82da0f/tools/workspace/sdformat/3bbd303.patch#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's just to make Eric happy.  It's not better or worse.
</blockquote></details>

OK I kinda agree with Sherm in that there should be raw command line for the starting bits. But meh overall.

**Comment by sherm1** [comment]
___
*[tools/workspace/sdformat/repository.bzl, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/13201#-M7OJaMQEMfbCJJwDe63:-M7OarIO7F51_kEBwFtp:bt8urcj) ([raw file](https://github.com/robotlocomotion/drake/blob/d75d2f062b895b768be67bf793b4063b4f82da0f/tools/workspace/sdformat/repository.bzl#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For everything under `tools/workspace/....` the answer for "what should the sha256 be" is always "leave it blank, run a build, get an error, and paste the suggestion here"..

https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#finalizing-github_archive-changes
</blockquote></details>

Oh, that's a checksum rather than a commit id! No wonder I couldn't find it.

**Pull request merged**
