### PR TITLE
Made RigidBody::body_index private. Renamed it to be body_index_. Added accessors

### PR DESCRIPTION
**Pull request by liangfok**
Builds upon #2904 by making `RigidBody::body_index` private with get/set accessors. I also renamed the member variable to be `body_index_` to conform to style guide.

Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2905)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
+@amcastro-tri for feature review since this touches `RigidBody*`.
+@david-german-tri for platform review since today is Thursday.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNlk5NXNwUxmdSwDtRz:1983506044)*

**Comment by david-german-tri** [comment]
-@david-german-tri +@jwnimmer-tri, since today is Thursday.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNlowfhLkKlEF0lw_Ji:662479594)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 16 files at r1, 5 of 7 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 27 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-KNlr02d-p0_ZujatVe5:-KNlr02e-qNQXIb9Kl-g:-1005429884) ([raw file](https://github.com/robotlocomotion/drake/blob/51ba4916ce0a7188808927e740eab39e4e8fd593/CHANGELOG.md#L27)):*
> ```Markdown
> 
>  - [#2923][] Updated member variables of `RigidBodyLoop` and `RigidBodActuator` to conform to style guide.
>  - [#2905][] Made `RigidBody::body_index` private. Re-named it to be `RigidBody::body_index_`. Added necessary accessors.
> ```

The second (middle) sentence is irrelevant for a changelog.
Line too long (80).

---

*[drake/systems/plants/RigidBody.h, line 257 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-KNlrU-zxRmRfFRF1HuN:-KNlrU-zxRmRfFRF1HuO:-1765240967) ([raw file](https://github.com/robotlocomotion/drake/blob/51ba4916ce0a7188808927e740eab39e4e8fd593/drake/systems/plants/RigidBody.h#L257)):*
> ```objc
> 
>   // The index of this rigid body in the rigid body tree.
>   int body_index_;
> ```

http://drake.mit.edu/code_style_guide.html#additional-rules
_Always use in-class member initialization for built-in data types that would would otherwise be uninitialized..._

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905)*

**Comment by liangfok** [comment]
@jwnimmer-tri I addressed your comments. PTAL. Thanks!

---

Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 27 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-KNlr02d-p0_ZujatVe5:-KNltsrEDdFFMMGlhpEt:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/51ba4916ce0a7188808927e740eab39e4e8fd593/CHANGELOG.md#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The second (middle) sentence is irrelevant for a changelog.
> Line too long (80).
</details>
Done.

---

*[drake/systems/plants/RigidBody.h, line 257 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-KNlrU-zxRmRfFRF1HuN:-KNluClR1LaHbVF-t6IP:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/51ba4916ce0a7188808927e740eab39e4e8fd593/drake/systems/plants/RigidBody.h#L257)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> http://drake.mit.edu/code_style_guide.html#additional-rules
> _Always use in-class member initialization for built-in data types that would would otherwise be uninitialized..._
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNluEp-f6i-25--eMAl:-785648134)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

To be clear: this (and its related PRs) are changing the swig python APIs as well as the C++ APIs.  We could be adding compatibility shims to the `*.i` files if we cared, but to my understanding it's alright to rev the python APIs as long as we CHANGELOG it.

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNluR1Ljl_cvQKCn3ij:-508252124)*

**Comment by liangfok** [comment]
Agreed regarding revising the python APIs when the need arises. Now awaiting feature review from @amcastro-tri.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNlv8ZHAZ_m7d04m2XW:-953371427)*

**Comment by liangfok** [comment]
The CI failure was due to https://github.com/RobotLocomotion/drake/issues/2959.

@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNmJwe5bk3LsJfZpRaM:248756269)*

**Comment by jwnimmer-tri** [comment]
I added a DNM tag to help remind me that @amcastro-tri still needs to finish feature review.  Feel free to remove it once that is done.

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3152/ and is thus ready for @amcastro-tri's feature review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNn2Msc7YFFnarOCV3F:1675018631)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 4 of 16 files at r1, 2 of 7 files at r3, 2 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2905#-:-KNnGjyDSnZoch3p_Dk6:1417088721)*

**Pull request merged**
