### PR TITLE
Add getters for if-then-else symbolic::Expression

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8054)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai for feature-review, please.
+@sammy-tri for platform-review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8054#-:-L5Etnd4dwrG2Z2G8-wH:b-qhjvrr)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/symbolic_expression.h, line 630 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8054#-L5EyUSVb0B7CiW46hTg:-L5EyUSVb0B7CiW46hTh:bunu5fo) ([raw file](https://github.com/robotlocomotion/drake/blob/85e92a0a90eeb5fe6d5ca830877f888d41dc1fec/common/symbolic_expression.h#L630)):*
> ```objc
> 
> /** Returns the conditional formula in the if-then-else expression @p e.
>  * @pre @p e is an if-then-else expression.
> ```

Will `get_conditional_formula` throw an error if the precondition fails?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8054#-:-L5EyllCkZ4AcaozoWcI:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/symbolic_expression.h, line 630 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8054#-L5EyUSVb0B7CiW46hTg:-L5EzMqjAGbUvCkTY-8X:b-xubmnw) ([raw file](https://github.com/robotlocomotion/drake/blob/85e92a0a90eeb5fe6d5ca830877f888d41dc1fec/common/symbolic_expression.h#L630)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Will `get_conditional_formula` throw an error if the precondition fails?
</blockquote></details>

It's using `to_if_then_else(const Expression& e)` which has `DRAKE_ASSERT` to check if `e` is indeed an if-then-else expr.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8054)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/symbolic_expression.h, line 630 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8054#-L5EyUSVb0B7CiW46hTg:-L5F4xKNBr_oQPxSgNoO:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/85e92a0a90eeb5fe6d5ca830877f888d41dc1fec/common/symbolic_expression.h#L630)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It's using `to_if_then_else(const Expression& e)` which has `DRAKE_ASSERT` to check if `e` is indeed an if-then-else expr.
</blockquote></details>

Got it, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8054)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8054#-:-L5F7B3zwfSneXi30cgN:bnfp4nl)*

**Pull request merged**
