### PR TITLE
Package LCM

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add missing bits (namely, the license stuff) so that Bazel can package external LCM. Add `//drake/lcm` to `libdrake.so` so that consumers can use those bits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6041)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake.bzl, line 193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6041#-KjOjdchUkxsQCjIclVr:-KjOjdchUkxsQCjIclVs:bthsgab) ([raw file](https://github.com/robotlocomotion/drake/blob/98d37e744c5feb18b436ef6e86fc99b6a350d698/tools/drake.bzl#L193)):*
> ```Python
>   headers = set()
>   for dep in ctx.attr.deps:
>     # TODO(jwnimmer-tri): Figure out a better way to exclude system headers
> ```

Per Google Style Guide convention, TODOs do not assign a responsible party for resolution, they document who introduced the concern in order to ask what the note means in case something is unclear.  In that case, this should be `mwoehlke-kitware` and not me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6041#-:-KjOkEIrBtiAFU8bcQf1:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6041)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6041)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6041#-:-KjOnz_JI3wWm8Q7SDd4:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
:lgtm: with one BTW. Please feel free to add comments when you modify Bazel BUILD files. These are at least as obscure as a typical piece of code and could use a little English translation.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lcm.BUILD, line 197 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6041#-KjOwws6sOaABBQdc1tD:-KjOwws6sOaABBQdc1tE:b-klp5dz) ([raw file](https://github.com/robotlocomotion/drake/blob/4f4f59a85427b48c2e50f0d76b9943792eef0dbe/tools/lcm.BUILD#L197)):*
> ```
>     files = ["COPYING"],
>     package_dir = "lcm",
> )
> ```

BTW it would be help to have some comments in BUILD for those of us who are not Bazel wizards. What is the intent of this package and what does it produce? Is the output file actually "COPYING.tar.gz"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6041#-:-KjOxKlJ3c4R6nYqN9sb:b-ef6b8g)*

**Comment by jwnimmer-tri** [comment]
*[tools/lcm.BUILD, line 197 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6041#-KjOwws6sOaABBQdc1tD:-KjOyBWgB4T798F8qLgD:b7ippe6) ([raw file](https://github.com/robotlocomotion/drake/blob/4f4f59a85427b48c2e50f0d76b9943792eef0dbe/tools/lcm.BUILD#L197)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW it would be help to have some comments in BUILD for those of us who are not Bazel wizards. What is the intent of this package and what does it produce? Is the output file actually "COPYING.tar.gz"?
</blockquote></details>

FYI The _what_ should be fairly clear from docs at https://bazel.build/versions/master/docs/be/pkg.html#pkg_tar.  The comment here could be something like the intent: `# Collect the required copyright and license notices to use by Drake's binary release.` or similar.

That of course would need to be duplicated in the ~6 places this pattern appears, but perhaps its worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6041)*

**Pull request merged**
