### PR TITLE
Fix mathprog tutorial link

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12022)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
On the blob-as-preview link here:

(1) The latex array markdown sections are not rendering correctly for me (FF 69, Ubuntu):
image

(2) There is also a delay while it's thinking about those array sections.  They start out empty (try in a private browser window to confirm) and then fill in with wrong-text later.

I don't think linking to the preview blob is a good idea.

Our drake.mit.edu website is published from the outputs of the build system.  Does Jupyter have a way to render the notebook to HTML, and we could publish that version instead of a live link?

**Comment by jwnimmer-tri** [comment]
Maybe we need to remove the use of tex for now -- respelling it with a little unicode / markdown tables instead?  Until you get some help with how to properly build / release this document?

**Comment by jwnimmer-tri** [comment]
At minimum, the PR would need to contain instructions for the developer how to regenerate the HTML.  But really, we should not check in HTML to master.  If this is the route you want, we need to have the build system create the HTML on the fly.

**Comment by hongkai-dai** [comment]
As replaced by #12023

**Pull request closed without merging**
