### PR TITLE
Fix some RgbdCamera problems

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Problems:
- `AssertIntNear` doesn't work.  Its name implies that it halts the test after the first error, but it doesn't.  Also, it's needlessly obscure, because `ASSERT_NEAR` (an absolute-tolerance comparison) was just fine.
- VTK's `SetInput` is deprecated as of VTK5; you're supposed to use `SetInputConnection` (in our case), which also then works for VTK6 & VTK7.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5565)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@kunimatsu-tri for feature review (and manual testing), please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-:-KfdeN3jBLIl2xuwMcjP:b-frcptm)*

**Comment by kunimatsu-tri** [comment]
Thanks jwnimmer-tri!

It's good to know that it's OK for `int` to use `ASSERT_NEAR`.

Manually tested, and confirmed there is no problem.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-:-Kfg8nb22SS6sswGs4_w:b-v1f2a1)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-:-Kfg99jRqp08WSoJId3z:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-:-Kfg9FGx-4yjWSBOBf06:bxwr5c8)*

**Comment by soonho-tri** [comment]
:lgtm: (aside one BTW)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 320 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-KfgABh4gxsBMhfE7ZjQ:-KfgABh4gxsBMhfE7ZjR:b-1nmadl) ([raw file](https://github.com/robotlocomotion/drake/blob/a611ef50659bfd48fca2436f33299a6f421b2f5e/drake/systems/sensors/test/rgbd_camera_test.cc#L320)):*
> ```cpp
> 
>     // We need a tolerance because the result varies depending on the CPU.
>     ASSERT_NEAR(expected_horizon, actual_horizon, 1.001);
> ```

BTW, `1.001` -> `kColorPixelTolerance`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-:-KfgAFU5qVn2_fQ37qdE:bm9b64f)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 320 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5565#-KfgABh4gxsBMhfE7ZjQ:-KfgAQnwHlsWQErtRjqZ:b2azpem) ([raw file](https://github.com/robotlocomotion/drake/blob/a611ef50659bfd48fca2436f33299a6f421b2f5e/drake/systems/sensors/test/rgbd_camera_test.cc#L320)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, `1.001` -> `kColorPixelTolerance`?
</blockquote></details>

hmm. never mind. It seems that it means different stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5565)*

**Pull request merged**
