### PR TITLE
[pydrake] Add missing module to pydrake/solvers/all

### PR DESCRIPTION
**Pull request by hongkai-dai**
cc @TobiaMarcucci

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16933)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16933#-:-N-Pu1Hp617MwvyQfZt2:be2t5nx)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
FYI our intention is that `all_test.py` mentions a name from each module at least once, to guard against any regressions here.  It seems to be missing quite a few checks, at the moment:

https://github.com/RobotLocomotion/drake/blob/9c662722b02707c2de7d016160b30b74aacf7964/bindings/pydrake/test/all_test.py#L140-L154

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy, I added the missing checks for solvers folder.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16933#-:-N-PxdZu7uHjEx5V9Vel:b-6a3rjg)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Rubber stamp :lgtm: x 2
+(release notes: none) 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16933#-:-N-ToE603DtljQIx_UGc:b-jxombw)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
