### PR TITLE
manip. station: Use same extrinsics+intrinsics for color+depth

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Otherwise, point clouds are a lie

A short-term workaround for #12125
Motivated by review of #14991

\cc @RussTedrake @jwnimmer-tri @SeanCurtis-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15186)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI what remains before this is ready for review?  From a quick skim at least, it seems plausible already.

**Comment by EricCousineau-TRI** [comment]
Was namely concerned about breaking workflow, but if it looks good, then I'm down!

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review, please
+@russtedrake for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15186#-:-MqWJztT-IHqqlKgpuFr:b-w6al1s)* status: LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15186#-:-Mq_GBaJ8vRIe4gU8wyo:bnfp4nl)* status: LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15186#-:-Mr7L2lYDq4hUwOj1knS:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @RussTedrake)

**Pull request merged**
