### PR TITLE
Bnb solve by rounding

### PR DESCRIPTION
**Pull request by hongkai-dai**
In each node of the branch-and-bound tree, if the optimization hasn't found an integral solution yet, the user could choose to search for an integral solution, by fixing the remaining binary variables to the closest binary values in the solution, and search the continuous variables.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8063)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L5Gjf1qe2CnbmNK-dgW:bll7v0f)*

**Comment by avalenzu** [comment]
Review pass done. PTAL.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[solvers/branch_and_bound.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5Pm01k8dgQdVW1EmI3:-L5Pm01k8dgQdVW1EmI4:b-fx7xx2) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L42)):*
> ```cpp
>       optimal_solution_is_integral_{OptimalSolutionIsIntegral::kUnknown},
>       solver_id_{solver_id} {
>   if (solver_id != GurobiSolver::id() && solver_id != ScsSolver::id()) {
> ```

It would be nice if this `solver_id` logic could be isolated to a function with a signature along the lines of
```c++
std::unique_ptr<MathematicalProgramSolverInterface> MakeSolver(const SolverId& id)
```
The "does not support solver" exception could be thrown inside that function.

Then the body of this constructor could shrink to
```c++
std::unique_ptr<MathematicalProgramSolverInterface> solver = MakeSolver(solver_id);
DRAKE_ASSERT(solver);
if (!solver.available()) {
  throw std::runtime_error(solver_id.name() + " is unavailable.");
}
// Check if there are still binary variables.
DRAKE_ASSERT(!MathProgHasBinaryVariables(*prog_));
// Set Gurobi DualReductions to 0, to differentiate infeasible from unbounded.
prog_->SetSolverOption(GurobiSolver::id(), "DualReductions", 0);
```

---

*[solvers/branch_and_bound.cc, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PnTJbr42Rx136pI2E:-L5PnTJbr42Rx136pI2F:bbuf2zm) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L110)):*
> ```cpp
> SolutionResult SolveProgramWithSolver(MathematicalProgram* prog,
>                                       const SolverId& solver_id) {
>   if (solver_id == GurobiSolver::id()) {
> ```

If you follow the approach I suggest above, then the body of this method could become
```c++
std::unique_ptr<MathematicalProgramSolverInterface> solver = MakeSolver(solver_id);
DRAKE_ASSERT(solver);
solver->Solve(*prog)
```

---

*[solvers/branch_and_bound.cc, line 711 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PqpAuwbVtN8mxbhjX:-L5PqpAuwbVtN8mxbhjY:b-9nbpye) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L711)):*
> ```cpp
>     // The same solution should have the same cost, up to some numerical
>     // tolerance.
>     if (std::abs(cost_solution.first - cost) < tol) {
> ```

Could you replace this if statement with something like

```c++
bool found_match =
    std::abs(cost_solution.first - cost) < tol &&
    (cost_solution.second - solution).cwiseAbs().maxCoeff() < tol;
```

---

*[solvers/branch_and_bound.cc, line 760 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PsXdQ6JfciUObhQWG:-L5PsXdQ6JfciUObhQWH:bs0xzw3) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L760)):*
> ```cpp
>     // solution to the MIP, and we get an upper bound on the MIP optimal cost.
>     auto new_prog = node.prog()->Clone();
>     // Go through each remaining binary variables, constraint them to either 0
> ```

", constraint" -> "and constrain"

---

*[solvers/branch_and_bound.cc, line 761 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PsgP_-OEEGjDhkiUg:-L5PsgP_-OEEGjDhkiUh:b-qfrltb) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L761)):*
> ```cpp
>     auto new_prog = node.prog()->Clone();
>     // Go through each remaining binary variables, constraint them to either 0
>     // or 1, by rounding the solution to the integer.
> ```

Remove comma in this line.

---

*[solvers/branch_and_bound.cc, line 765 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PsuzzvMeRL8FP2rMk:-L5PsuzzvMeRL8FP2rMl:bivac8e) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L765)):*
Consider replacing 
> because adding constraint requires the bound being of type double.

with
> because `AddBoundingBoxConstraint()` requires bounds of type double.

---

*[solvers/branch_and_bound.h, line 276 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PuTFAO5dAJPO54_ew:-L5PuTFAO5dAJPO54_ex:b-gl2837) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.h#L276)):*
> ```objc
>       const MixedIntegerBranchAndBoundNode&)>;
>   /** The function signature for user defined node callback function. */
>   using NodeCallbackFun = std::function<void(
> ```

Is this a remnant of a previous implementation? I don't see the node callbacks being used anywhere.

---

*[solvers/test/branch_and_bound_test.cc, line 1118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PuZnd0jS-ylgMBexQ:-L5PuZnd0jS-ylgMBexR:bwk208i) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/test/branch_and_bound_test.cc#L1118)):*
> ```cpp
> 
> GTEST_TEST(MixedIntegerBranchAndBoundTest, SearchIntegralSolutionByRounding2) {
>   // Test the node callback to search an integral solution by rounding the
> ```

I don't think you're using a node callback here. Same comment for the next two tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L5Puj8sjXT_9BHMcegD:b837gv3)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[solvers/branch_and_bound.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5Pm01k8dgQdVW1EmI3:-L6cuFB04aokS1Ty-Xjw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L42)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

It would be nice if this `solver_id` logic could be isolated to a function with a signature along the lines of
```c++
std::unique_ptr<MathematicalProgramSolverInterface> MakeSolver(const SolverId& id)
```
The "does not support solver" exception could be thrown inside that function.

Then the body of this constructor could shrink to
```c++
std::unique_ptr<MathematicalProgramSolverInterface> solver = MakeSolver(solver_id);
DRAKE_ASSERT(solver);
if (!solver.available()) {
  throw std::runtime_error(solver_id.name() + " is unavailable.");
}
// Check if there are still binary variables.
DRAKE_ASSERT(!MathProgHasBinaryVariables(*prog_));
// Set Gurobi DualReductions to 0, to differentiate infeasible from unbounded.
prog_->SetSolverOption(GurobiSolver::id(), "DualReductions", 0);
```
</blockquote></details>

Done.

---

*[solvers/branch_and_bound.cc, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PnTJbr42Rx136pI2E:-L6cuY9670U_Gg_njxZf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L110)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

If you follow the approach I suggest above, then the body of this method could become
```c++
std::unique_ptr<MathematicalProgramSolverInterface> solver = MakeSolver(solver_id);
DRAKE_ASSERT(solver);
solver->Solve(*prog)
```
</blockquote></details>

Done.

---

*[solvers/branch_and_bound.cc, line 711 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PqpAuwbVtN8mxbhjX:-L6cvFdMrqIOyqTdPLJr:b8t1atm) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L711)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Could you replace this if statement with something like

```c++
bool found_match =
    std::abs(cost_solution.first - cost) < tol &&
    (cost_solution.second - solution).cwiseAbs().maxCoeff() < tol;
```
</blockquote></details>

Done. Thanks! That is a lot more cleaner!

---

*[solvers/branch_and_bound.cc, line 760 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PsXdQ6JfciUObhQWG:-L6cvP6OnNkiJDlpQTqw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L760)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

", constraint" -> "and constrain"
</blockquote></details>

Done.

---

*[solvers/branch_and_bound.cc, line 761 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PsgP_-OEEGjDhkiUg:-L6cvRpFRdkV2mJvA05X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L761)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Remove comma in this line.
</blockquote></details>

Done.

---

*[solvers/branch_and_bound.cc, line 765 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PsuzzvMeRL8FP2rMk:-L6cvZwE-zZxZOqY9mm7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.cc#L765)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Consider replacing 
> because adding constraint requires the bound being of type double.

with
> because `AddBoundingBoxConstraint()` requires bounds of type double.
</blockquote></details>

Done.

---

*[solvers/branch_and_bound.h, line 276 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PuTFAO5dAJPO54_ew:-L6cvbqYyxzB-bSy4LBQ:b-6zqk1t) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/branch_and_bound.h#L276)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Is this a remnant of a previous implementation? I don't see the node callbacks being used anywhere.
</blockquote></details>

Done. Good call, I added the test on the node call back.

---

*[solvers/test/branch_and_bound_test.cc, line 1118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L5PuZnd0jS-ylgMBexQ:-L6cvybwv9qUmNw-geYc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e4234902e96fcf2960b3b7e6dfe96f7732110d46/solvers/test/branch_and_bound_test.cc#L1118)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I don't think you're using a node callback here. Same comment for the next two tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063)*

**Comment by hongkai-dai** [comment]
Sorry for not getting back to the PR for a long time. Just made the changes based on the comments. PTAL.

---

Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L6d2BOUMiYbH8cGJ2NU:btsqzuz)*

**Comment by avalenzu** [comment]
:lgtm:. One minor BTW. +@sammy-tri  for platform review.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/branch_and_bound.cc, line 763 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6r7DMipihRjop-sMHh:-L6r7DMipihRjop-sMHi:b-wcu4qa) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.cc#L763)):*
> ```cpp
>          node.remaining_binary_variables()) {
>       // Notice that roundoff_integer_val is of type double here. This is
>       // because AddBoundingBoxConstraint(...) requires the bounds of type
> ```

BTW "requires ~the~ bounds..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L6r7VRTv2dwDs5yVUnb:b-f9puwr)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/branch_and_bound.cc, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rHKkTdr4sbGeCnWLE:-L6rHKkTdr4sbGeCnWLF:bl2duvi) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.cc#L67)):*
> ```cpp
>       optimal_solution_is_integral_{OptimalSolutionIsIntegral::kUnknown},
>       solver_id_{solver_id} {
>   std::unique_ptr<MathematicalProgramSolverInterface> solver =
> ```

It's a little odd that the result for this isn't actually used.  I think it might at least be worth a commend explaining that this is just an early check to make sure `solver_id` is valid.

Also I'm not sure the early check is worth much.  The line in `ConstructRootNode` (or `Branch') immediately after constructing the node (which would cause this check to fail) it calls `SolveProblemWithSolver` which has the same check.No

---

*[solvers/branch_and_bound.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rHBVqQhNzMXXCJ2R1:-L6rHBVqQhNzMXXCJ2R2:bvczz2g) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.cc#L69)):*
> ```cpp
>   std::unique_ptr<MathematicalProgramSolverInterface> solver =
>       MakeSolver(solver_id);
>   DRAKE_ASSERT(solver.get());
> ```

MakeSolver can't actually return an empty unique_ptr (it always throws), so I don't think this assert does anything.

---

*[solvers/branch_and_bound.h, line 492 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rG4THOQntdm89Oj5D:-L6rG4THOQntdm89Oj5E:bi7cnu6) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.h#L492)):*
> ```objc
>    * The user can set a defined callback function in each node. This function is 
>    * called after the optimization is solved in each node, if the user has 
>    * called SetNodeCallbackMethod(NodeCallbackMethod::kUserDefined).
> ```

I don't see a function called `SetNodeCallbackMethod` on master or in this PR.nmo

---

*[solvers/branch_and_bound.h, line 617 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rG_RNP84f6MKq5jG7:-L6rG_RNP84f6MKq5jG8:bsq6oa9) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.h#L617)):*
> ```objc
>    * 1. The optimization problem in this node is feasible.
>    * 2. The optimal solution to the problem in this node is not integral.
>    * 3. node_callback_method =
> ```

`node_callback_method` and `NodeCallbackMethod` are only mentioned in this comment and do not appear in code.

---

*[solvers/test/branch_and_bound_test.cc, line 1150 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rKFO9Jq8H0nSURxlw:-L6rKFOBl5aVZE9ty9qs:b-e4salo) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/test/branch_and_bound_test.cc#L1150)):*
> ```cpp
>                               MatrixCompareType::absolute));
> 
>   // Now test to solve the mip with the callback to search for integral solution
> ```

I don't see where we're setting/using a callback here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L6rKcsXl2ua1KWeEwyz:bvb1a6z)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/branch_and_bound.cc, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rHKkTdr4sbGeCnWLE:-L6rRf0Nqx1CZUhDBP0r:b-xu345q) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.cc#L67)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's a little odd that the result for this isn't actually used.  I think it might at least be worth a commend explaining that this is just an early check to make sure `solver_id` is valid.

Also I'm not sure the early check is worth much.  The line in `ConstructRootNode` (or `Branch') immediately after constructing the node (which would cause this check to fail) it calls `SolveProblemWithSolver` which has the same check.No
</blockquote></details>

Done. Good call, I removed this early check.

---

*[solvers/branch_and_bound.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rHBVqQhNzMXXCJ2R1:-L6rRmUHeVKR8nQZkQP4:b-mk74bk) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.cc#L69)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

MakeSolver can't actually return an empty unique_ptr (it always throws), so I don't think this assert does anything.
</blockquote></details>

Done. Removed the assert.

---

*[solvers/branch_and_bound.cc, line 763 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6r7DMipihRjop-sMHh:-L6rRuRBU3TFMzU4Ze10:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.cc#L763)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW "requires ~the~ bounds..."
</blockquote></details>

Done.

---

*[solvers/branch_and_bound.h, line 492 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rG4THOQntdm89Oj5D:-L6rS8RHDozXRfhRk-Q5:b-3adzl7) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.h#L492)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't see a function called `SetNodeCallbackMethod` on master or in this PR.nmo
</blockquote></details>

Done. Good call, the function `SetNodeCallbackMethod` has been removed.

---

*[solvers/branch_and_bound.h, line 617 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rG_RNP84f6MKq5jG7:-L6rSfm79TuQUaCLqqw8:brxr1lb) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/branch_and_bound.h#L617)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

`node_callback_method` and `NodeCallbackMethod` are only mentioned in this comment and do not appear in code.
</blockquote></details>

Done. Good call. I changed the API within the PR, that I removed NodeCallbackMethod, but forgot to update the documentation.

---

*[solvers/test/branch_and_bound_test.cc, line 1150 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-L6rKFO9Jq8H0nSURxlw:-L6rT5Ze6LiruAlOjtdj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1153dc1e49e7acc24056067e90161775d5c8cf65/solvers/test/branch_and_bound_test.cc#L1150)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't see where we're setting/using a callback here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063)*

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L6rwHukEj4MD3x7akoK:b-pu9q93)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8063#-:-L6rwQAAQk4occ1-VhPW:b-l70wzf)*

**Pull request merged**
