### PR TITLE
[geometry/optimization] CartesianProduct isa ConvexSet

### PR DESCRIPTION
**Pull request by RussTedrake**
This is a general concept from geometry, but in particular it adds support for parsing Cylinder geometry for SceneGraph.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@tobiamarcucci for feature review, please
+@avalenzu for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-MgMUFNhE-WROxKS360W:b-bfqk5v)* status: LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @avalenzu and @TobiaMarcucci)

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571)* status: 5 unresolved discussions, LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @avalenzu, @RussTedrake, and @TobiaMarcucci)

___
*[geometry/optimization/cartesian_product.h, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgN90oD4Fm7KNDZi6VO:-MgN90oD4Fm7KNDZi6VP:b1clqoc) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L37)):*
> ```objc
> 
>   /** Constructs the product of convex sets in the rotated coordinates:
>   Ax + b ∈ Y₁ × Y₂ × ⋯ × Yₙ. */
> ```

Are the `Yi`'s here the `Xi`'s above?
___
*[geometry/optimization/cartesian_product.cc, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgND3rxE9QQyWQ224vG:-MgND3rxE9QQyWQ224vH:b-jgfb4x) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L52)):*
> ```cpp
> }
> 
> CartesianProduct::CartesianProduct(const ConvexSets& sets,
> ```

Can `A` be any matrix? I think that if `A` is not invertible some of the assumptions we made break?
___
*[geometry/optimization/cartesian_product.cc, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNE3456qk9Yoxy_oNy:-MgNE3456qk9Yoxy_oNz:b-8lzev3) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L97)):*
> ```cpp
> }
> 
> bool CartesianProduct::DoIsBounded() const {
> ```

If `A` is not invertible this is not true? A set `Q = {x : A x + b in S}` can be unbounded also if `S` is bounded, because `A` has a nontrivial nullspace, no?
___
*[geometry/optimization/cartesian_product.cc, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNBTEEE1Lad0O2YCuv:-MgNBTEEE1Lad0O2YCuw:b-2v1ayc) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L142)):*
> ```cpp
> 
> std::vector<Binding<Constraint>>
> CartesianProduct::DoAddPointInNonnegativeScalingConstraints(
> ```

This can be dangerous? If I understand correctly, your set is `Q = {x : A x + b in S}`, with `S` Cartesian product of convex sets (which I assume are bounded?). I agree that if `Q` is bounded, we have `t Q = {x : A x + b t in t S}`. But this is false if `Q` is unbounded. Take `t=0`: on the left you have `t Q = 0 Q = {0}`, on the right you get `{x : A x + b t in t S} = {x : A x = 0}`. If `A` has a nontrivial nullspace the the two sets are different.

Maybe we need a check that `A` is full column rank to add this constraint?
___
*[geometry/optimization/test/cartesian_product_test.cc, line 174 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNFLWcCBzDIYZEslPN:-MgNFLWcCBzDIYZEslPO:b-m6qu6y) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/test/cartesian_product_test.cc#L174)):*
> ```cpp
>   const Vector2d out_S = in_S + Vector2d{0.0, 0.01};
> 
>   Matrix<double, 4, 2> A;
> ```

This is a tall matrix so everything should work. If we care also about the case of a fat matrix I would test it? I would verify then that `IsBounded` does the right thing and that `AddPointInNonnegativeScalingConstraints` complains when `A` has nontrivial nullspace?

**Comment by TobiaMarcucci** [comment]
Everything seems in order to me, but I'd like to understand what kind of `A` matrices we plan to handle. In particular, if `A` can have a nontrivial nullspace, I think that we have a couple of issues. It seems that at the moment any `A` would be acceptable? What would we loose to require `A` to be invertible (I think it'd avoid many headaches)?

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571)* status: 6 unresolved discussions, LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @avalenzu, @RussTedrake, and @TobiaMarcucci)

___
*[geometry/optimization/cartesian_product.h, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNHHwG3X0xIFNVN2CP:-MgNHHwHBD4i784Qz1aR:b-q68tyw) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L19)):*
> ```objc
> 
> This class also supports a generalization of this concept in which the
> coordinates are transformed by the linear map, Ax + b \in S, with the default
> ```

This set is `{x : A x + b in S}`, right? I think it's pretty clear, but I'd write it down so that nobody gets confused. I particular, one might wonder if we mean `{A x + b : x in S}` instead.

**Comment by TobiaMarcucci** [comment]
Everything seems in order to me, but I'd like to understand what kind of `A` matrices we plan to handle. In particular, if `A` can have a nontrivial nullspace, I think that we have a couple of issues. It seems that at the moment any `A` would be acceptable? What would we loose to require `A` to be invertible (I think it'd avoid many headaches)?

**Review by avalenzu — COMMENTED** [review]
Review pass done.

> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-Mgfdr9HDR3aWeXD_6cY:b-l0f5b4)* status: 12 unresolved discussions, LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @RussTedrake and @TobiaMarcucci)

___
*[geometry/optimization/cartesian_product.h, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNHHwG3X0xIFNVN2CP:-Mgf6UzR5Gskz71KTuhd:bteshny) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L19)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

This set is `{x : A x + b in S}`, right? I think it's pretty clear, but I'd write it down so that nobody gets confused. I particular, one might wonder if we mean `{A x + b : x in S}` instead.
</blockquote></details>

I also think this would be clearer if it were " ... by a linear map, {x : Ax + b ∈ S} . . ." That way you can see that the parenthetical refers to the set, not the linear map.
___
*[geometry/optimization/cartesian_product.h, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfBYgUEgfR1jotiXON:-MgfBYgUEgfR1jotiXOO:b9fopyx) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L36)):*
> ```objc
>   CartesianProduct(const ConvexSet& setA, const ConvexSet& setB);
> 
>   /** Constructs the product of convex sets in the rotated coordinates:
> ```

minor: Consider "transformed" rather than "rotated," as there's no guarantee that the provided map will actually be a rotation.
___
*[geometry/optimization/cartesian_product.h, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfCl76AP2uPwmVLxpX:-MgfCl76AP2uPwmVLxpY:b-e11plp) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L50)):*
> ```objc
>   (trivial) CartesianProduct, we restrict this constructor to handling Cylinder
>   geometry, which constructs the (non-trivial) Cartesian product of a
>   HyperEllipsoid and an HPolyhedron. Most SceneGraph geometry types are
> ```

nit: Consider "Most other SceneGraph geometry types ..."
___
*[geometry/optimization/cartesian_product.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfDvlX9HUruWlGi3ZZ:-MgfDvlX9HUruWlGi3Z_:b-pn3hdk) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L60)):*
> ```objc
>   ~CartesianProduct() final;
> 
>   /** The number of terms (or sets) used in the product. */
> ```

nit: Consider "factors" instead of "terms" here.e
___
*[geometry/optimization/cartesian_product.cc, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNE3456qk9Yoxy_oNy:-MgfG5U_EbEV9RVc19G5:b-pbdqz3) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L97)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

If `A` is not invertible this is not true? A set `Q = {x : A x + b in S}` can be unbounded also if `S` is bounded, because `A` has a nontrivial nullspace, no?
</blockquote></details>

Agreed.
___
*[geometry/optimization/minkowski_sum.h, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfbW9F-pGQFMhjS0EX:-MgfbW9F-pGQFMhjS0EY:bxi1z9o) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/minkowski_sum.h#L43)):*
> ```objc
> 
>   @throws std::exception if geometry_id does not correspond to a Capsule. */
>   MinkowskiSum(const QueryObject<double>& query_object, GeometryId geometry_id,
> ```

Meta: Did you consider supporting cylinders via the Minkowski sum of a line segment and a degenerate ellipsoid?
___
*[geometry/optimization/test/cartesian_product_test.cc, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfcGRz-4Z1TTvl2dzU:-MgfcGRz-4Z1TTvl2dzV:b-1dvxlr) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/test/cartesian_product_test.cc#L76)):*
> ```cpp
>   // clang-format off
>   in_G << 0, 0,           kRadius,     kRadius/std::sqrt(2.0),
>           0, 0,           0,           kRadius/std::sqrt(2.0),
> ```

nit: The elements in the first and second rows of the third column are off by one space from the one in the third row.
___
*[geometry/optimization/test/cartesian_product_test.cc, line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfdDu2Eq5iRPbCQUvN:-MgfdDu2Eq5iRPbCQUvO:bh2je0z) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/test/cartesian_product_test.cc#L150)):*
> ```cpp
> 
>   // 2 from P1, 2 from P2, and t>=0 3 times.
>   EXPECT_EQ(constraints.size(), 5);
> ```

2 + 2 + 3 = 7?

**Review by RussTedrake — COMMENTED** [review]
Updated.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-Mk2DWD7EcDc7HcBudMD:bqyk4pz)* status: 8 unresolved discussions, LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @avalenzu and @TobiaMarcucci)

___
*[geometry/optimization/cartesian_product.h, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNHHwG3X0xIFNVN2CP:-Mk1ujO-EoAH3lfxNrzN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L19)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I also think this would be clearer if it were " ... by a linear map, {x : Ax + b ∈ S} . . ." That way you can see that the parenthetical refers to the set, not the linear map.
</blockquote></details>

Done.
___
*[geometry/optimization/cartesian_product.h, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfBYgUEgfR1jotiXON:-Mk1uuHSCHK7pGv3bstB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L36)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

minor: Consider "transformed" rather than "rotated," as there's no guarantee that the provided map will actually be a rotation.
</blockquote></details>

Done.
___
*[geometry/optimization/cartesian_product.h, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgN90oD4Fm7KNDZi6VO:-Mk1v7qc3Akj27B5UfdT:b22oi24) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L37)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

Are the `Yi`'s here the `Xi`'s above?
</blockquote></details>

Yes.  I feel they should not be called Xi anymore since xi may not live in Yi/Xi.  I've updated the notation here and above.
___
*[geometry/optimization/cartesian_product.h, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfCl76AP2uPwmVLxpX:-Mk1wmSe3Ykya5_blHNe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L50)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Consider "Most other SceneGraph geometry types ..."
</blockquote></details>

Done.
___
*[geometry/optimization/cartesian_product.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfDvlX9HUruWlGi3ZZ:-Mk1wsdr8cDq7nRmUGhy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.h#L60)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Consider "factors" instead of "terms" here.e
</blockquote></details>

Done.
___
*[geometry/optimization/cartesian_product.cc, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgND3rxE9QQyWQ224vG:-Mk1yRMfAEQlsvg5X5PQ:bptnw41) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L52)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

Can `A` be any matrix? I think that if `A` is not invertible some of the assumptions we made break?
</blockquote></details>

Done.  I agree that requiring that A is always full column rank is the best solution.
___
*[geometry/optimization/cartesian_product.cc, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNE3456qk9Yoxy_oNy:-Mk1z_gV0IscmlfoGeZT:b-x5qw8a) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L97)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Done.  Good catch.  Thanks.
___
*[geometry/optimization/cartesian_product.cc, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNBTEEE1Lad0O2YCuv:-Mk2-6cz9tVFgVQm0k9i:bqc34dt) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L142)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

This can be dangerous? If I understand correctly, your set is `Q = {x : A x + b in S}`, with `S` Cartesian product of convex sets (which I assume are bounded?). I agree that if `Q` is bounded, we have `t Q = {x : A x + b t in t S}`. But this is false if `Q` is unbounded. Take `t=0`: on the left you have `t Q = 0 Q = {0}`, on the right you get `{x : A x + b t in t S} = {x : A x = 0}`. If `A` has a nontrivial nullspace the the two sets are different.

Maybe we need a check that `A` is full column rank to add this constraint?
</blockquote></details>

Done.  I've added that constraint in the constructor.  Do we agree that is sufficient, even if the sets Yi are potentially unbounded?
___
*[geometry/optimization/minkowski_sum.h, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfbW9F-pGQFMhjS0EX:-Mk20eYm1FZ99Mq3_Bfr:b3eol0m) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/minkowski_sum.h#L43)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Meta: Did you consider supporting cylinders via the Minkowski sum of a line segment and a degenerate ellipsoid?
</blockquote></details>

I suppose you are right that I could have done that, too, since we do support degenerate hyperellipsoids.  This seems cleaner (apart from the transform stuff)? (and also useful to have around)?
___
*[geometry/optimization/test/cartesian_product_test.cc, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfcGRz-4Z1TTvl2dzU:-Mk21OCz7ROd92E5OZ5X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/test/cartesian_product_test.cc#L76)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: The elements in the first and second rows of the third column are off by one space from the one in the third row.
</blockquote></details>

Done.
___
*[geometry/optimization/test/cartesian_product_test.cc, line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfdDu2Eq5iRPbCQUvN:-Mk23s3a-SygWImBJ6Mt:b-m08nl6) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/test/cartesian_product_test.cc#L150)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

2 + 2 + 3 = 7?
</blockquote></details>

Done.  P1 and P2 add one constraint (with 2 variables).  It took me a few minutes of checking to realize it was my comment that was wrong!  
___
*[geometry/optimization/test/cartesian_product_test.cc, line 174 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNFLWcCBzDIYZEslPN:-Mk24wql8w1b0kP68k9f:bmtibjd) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/test/cartesian_product_test.cc#L174)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

This is a tall matrix so everything should work. If we care also about the case of a fat matrix I would test it? I would verify then that `IsBounded` does the right thing and that `AddPointInNonnegativeScalingConstraints` complains when `A` has nontrivial nullspace?
</blockquote></details>

Done.  We don't need it anymore, since we've constrained A to have full column rank, and therefor dis-allowed short matrices.

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571)* status: 3 unresolved discussions, LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @avalenzu, @RussTedrake, and @TobiaMarcucci)

___
*[geometry/optimization/cartesian_product.cc, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNE3456qk9Yoxy_oNy:-Mk2mpGt-ZPymKn4cG52:bu38ueo) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L97)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Good catch.  Thanks.
</blockquote></details>

One thing, sorry I didn't realize this in the first pass. This method only checks a sufficient condition for boundedness of `Q`. In fact, while `S = Y₁ × Y₂ × ⋯ × Yₙ` is bounded iff all the `Yi` are bounded, it can be the case that the set `Q = {x : A x + b in S}` is bounded when `S` is not. Take `A = [1; 0]`, `b = [0;0]`, `Y₁ = [0,1]`, `Y₂ = [0,inf)` and let `Q = {x | y = Ax + b, y ∈ S = Y₁ × Y₂}`. Then `S` is unbounded since `Y₂` is unbounded, `A` is full column rank, but `Q = {x | x in Y1} = [0,1]` is bounded. Am I correct?

I might think of a more general way to check boundedness of `Q` but I believe the simplest thing would just be to assume the sets `Yi` to be bounded?
___
*[geometry/optimization/cartesian_product.cc, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNBTEEE1Lad0O2YCuv:-Mk2kci2AG4F-fS1rzZa:b-fukt39) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L142)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I've added that constraint in the constructor.  Do we agree that is sufficient, even if the sets Yi are potentially unbounded?
</blockquote></details>

No, if a set `Yi` is unbounded, then the set `Q = {x | y = Ax + b, y ∈ Y₁ × Y₂ × ⋯ × Yₙ}` *can* be unbounded. (Take `Y₁ × Y₂ × ⋯ × Yₙ = R^n`, then `Q = col_space(A) + b` which is unbounded.) Even though there are cases in which `Yi` is unbounded but `Q` is bounded (see example in previous comment), I think for simplicity we should assume `Yi` to be bounded for all `i`.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571)* status: 3 unresolved discussions, LGTM missing from assignees TobiaMarcucci,avalenzu, needs platform reviewer assigned (waiting on @avalenzu and @TobiaMarcucci)

___
*[geometry/optimization/cartesian_product.cc, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNE3456qk9Yoxy_oNy:-Mk3gU224meKeA33BbIy:bz33yot) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L97)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

One thing, sorry I didn't realize this in the first pass. This method only checks a sufficient condition for boundedness of `Q`. In fact, while `S = Y₁ × Y₂ × ⋯ × Yₙ` is bounded iff all the `Yi` are bounded, it can be the case that the set `Q = {x : A x + b in S}` is bounded when `S` is not. Take `A = [1; 0]`, `b = [0;0]`, `Y₁ = [0,1]`, `Y₂ = [0,inf)` and let `Q = {x | y = Ax + b, y ∈ S = Y₁ × Y₂}`. Then `S` is unbounded since `Y₂` is unbounded, `A` is full column rank, but `Q = {x | x in Y1} = [0,1]` is bounded. Am I correct?

I might think of a more general way to check boundedness of `Q` but I believe the simplest thing would just be to assume the sets `Yi` to be bounded?
</blockquote></details>

Done.  The constructor now enforces that all sets are bounded.
___
*[geometry/optimization/cartesian_product.cc, line 142 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgNBTEEE1Lad0O2YCuv:-Mk3gP4s--Ia7jv29kMe:bz33yot) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/cartesian_product.cc#L142)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

No, if a set `Yi` is unbounded, then the set `Q = {x | y = Ax + b, y ∈ Y₁ × Y₂ × ⋯ × Yₙ}` *can* be unbounded. (Take `Y₁ × Y₂ × ⋯ × Yₙ = R^n`, then `Q = col_space(A) + b` which is unbounded.) Even though there are cases in which `Yi` is unbounded but `Q` is bounded (see example in previous comment), I think for simplicity we should assume `Yi` to be bounded for all `i`.
</blockquote></details>

Done.  The constructor now enforces that all sets are bounded.
___
*[geometry/optimization/minkowski_sum.h, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15571#-MgfbW9F-pGQFMhjS0EX:-Mk3dsv874TK7guBqDWq:br7v0n9) ([raw file](https://github.com/robotlocomotion/drake/blob/7e3560b928ea0e9ebade0a516d7048e2eed3f87a/geometry/optimization/minkowski_sum.h#L43)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I suppose you are right that I could have done that, too, since we do support degenerate hyperellipsoids.  This seems cleaner (apart from the transform stuff)? (and also useful to have around)?
</blockquote></details>

FTR -- the minkowski sum version would need the transform logic, too.

**Review by TobiaMarcucci — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-Mk4RZwU5fchkx5BCaK6:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee avalenzu, needs platform reviewer assigned (waiting on @avalenzu and @TobiaMarcucci)

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-Mk4onzd7NkcCR8hrcuC:b-syrr9x)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),avalenzu (waiting on @avalenzu, @rpoyner-tri, and @TobiaMarcucci)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 2 of 7 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-Mk8n1G-9BnO0M4xeWX4:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee avalenzu (waiting on @avalenzu)

**Review by RussTedrake — COMMENTED** [review]
-@avalenzu (I think he was happy, but simply hasn't cleared the last bits yet).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15571#-:-Mk99WrF6AlVbvrscOJU:bggdrub)* status: 2 unresolved discussions (waiting on @avalenzu)

**Pull request merged**
