### PR TITLE
return the right type for nonlinear program with linear complementary constraints

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 may I ask you to do a feature review on this PR, given your knowledge on LCP?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625#-:-MhS-mU9B5kunJDOCFTq:b-ntz1fd)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I'm not sure I have the expertise you seek, Hongkai! Nevertheless, feature :lgtm: pending a few minor comments.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625#-:-MhUZLhE-ZRtmV3ROQ-E:b-76au3v)* status: 6 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/get_program_type.cc, line 193 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUTSUMAz2jmdfzNYFo:-MhUTSUMAz2jmdfzNYFp:bgno2gq) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/get_program_type.cc#L193)):*
> ```cpp
> 
> bool IsNLP(const MathematicalProgram& prog) {
>   // A program is nonlinear program (NLP) if it satisfies all the following
> ```

nit "is nonlinear program" -> "is a nonlinear program"
___
*[solvers/get_program_type.cc, line 198 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUSB1H-pfpmZt6KhG9:-MhUSB1H-pfpmZt6KhGA:b51u3il) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/get_program_type.cc#L198)):*
> ```cpp
>   // costs.
>   // 2. It has no binary variables.
>   // 3. If it has linear complementarity constraints, then it must has other
> ```

nit "must has" -> "must have"
___
*[solvers/get_program_type.cc, line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUWSfA4Yvhh93dWn-h:-MhUWSfA4Yvhh93dWn-i:b-avkep2) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/get_program_type.cc#L200)):*
> ```cpp
>   // 3. If it has linear complementarity constraints, then it must has other
>   // types of constraints/costs (hence it is not a Linear Complementarity
>   // Problem).
> ```

minor: The comments here don't match the code below or the new unit tests. You've written the comments as an "and" of all three conditions, but the code below allows condition 1 to be false as long as condition 3 is true. As I understand this the conditions are
1. no binary variables
2. not an LCP
3. has one of: generic cost, generic constraint, nonconvex cost, linear complementarity constraint

That's not the same as what the comment says now.
___
*[solvers/get_program_type.cc, line 218 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUSkio6Wde63cMqBK-:-MhUSkio6Wde63cMqBK0:b-sclzbd) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/get_program_type.cc#L218)):*
> ```cpp
>           ((has_generic_cost || has_nonconvex_quadratic_cost ||
>             has_generic_constraint) ||
>            (has_linear_complementarity_constraint)));
> ```

minor: spurious parentheses -- this is just four conditions or'ed together.
___
*[solvers/test/get_program_type_test.cc, line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUYTmYAtdRxS4flKpZ:-MhUYTmYAtdRxS4flKp_:b-pa2o66) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/test/get_program_type_test.cc#L127)):*
> ```cpp
>   }
>   {
>     // problem with linear complementarity constraint and a cost.
> ```

nit: needs initial cap (and below)
___
*[solvers/test/get_program_type_test.cc, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUZ-BsDW3tGaJKKGs5:-MhUZ-BsDW3tGaJKKGs6:b-x1k3fg) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/test/get_program_type_test.cc#L158)):*
> ```cpp
>   // LCP doesn't accept linear constraint.
>   prog.AddLinearConstraint(x[0] + x[1] >= 1);
>   EXPECT_NE(GetProgramType(prog), ProgramType::kLCP);
> ```

minor: I think you could be more specific here and say this should be an NLP? In any case there needs to be a unit test that shows that an LCP plus some other constraint type is an NLP.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/get_program_type.cc, line 200 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUWSfA4Yvhh93dWn-h:-MhUe0G28Sx5YOP1dGDL:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/get_program_type.cc#L200)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: The comments here don't match the code below or the new unit tests. You've written the comments as an "and" of all three conditions, but the code below allows condition 1 to be false as long as condition 3 is true. As I understand this the conditions are
1. no binary variables
2. not an LCP
3. has one of: generic cost, generic constraint, nonconvex cost, linear complementarity constraint

That's not the same as what the comment says now.
</blockquote></details>

Done. Good call.
___
*[solvers/test/get_program_type_test.cc, line 158 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUZ-BsDW3tGaJKKGs5:-MhUeKMDAnwK3XXiLcpY:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/1e9d80f2b3455f9416370e0f20480e265113e7f6/solvers/test/get_program_type_test.cc#L158)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think you could be more specific here and say this should be an NLP? In any case there needs to be a unit test that shows that an LCP plus some other constraint type is an NLP.
</blockquote></details>

Done. Good call.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/get_program_type.cc, line 217 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15625#-MhUjEEv7tzEKAfinHvN:-MhUjEEw5uHNePtk7SAP:b-tnd6mr) ([raw file](https://github.com/robotlocomotion/drake/blob/273a96102a48b3d24b55d4db03aecbee0ac47327/solvers/get_program_type.cc#L217)):*
> ```cpp
>           ((has_generic_cost || has_nonconvex_quadratic_cost ||
>             has_generic_constraint) ||
>            has_linear_complementarity_constraint));
> ```

BTW this is still oddly phrased since any of the four conditions will do. Writing it like this would be more straightforward and would match the new phrasing of condition 3 in the comment above:
```
... && 
(has_generic_cost || has_nonconvex_quadratic_cost ||
 has_generic_constraint || has_linear_complementarity_constraint);
```

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625#-:-MhVEW9u4jPJtyX1GEgx:buxscyd)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15625#-:-MhVF5nT3OowXXu4P6vz:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
