### PR TITLE
[workspace] Upgrade to Mosek 10

### PR DESCRIPTION
**Pull request by hongkai-dai**
cc @jwnimmer-tri 

A step towards #17026

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@jwnimmer-tri according to https://www.mosek.com/downloads/10.0.16/, on our Ubuntu 20.04, we should not use 64bit X86, but 64bit ARM.

**Comment by hongkai-dai** [comment]
> I think the "18.04" on that page means "18.04 or newer" not "18.04 only".

Got it, that makes sense.

**Comment by hongkai-dai** [comment]
Thanks Jeremy, I often just send an email to support@mosek.com.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri I tried the new Mosek 10 and one of the test `TestInitialGuess` fails. I think there is some behavioral change on the Mosek side. I sent an email to Mosek and cc'ed you

**Comment by hongkai-dai** [comment]
@jwnimmer-tri I am not sure if this is the right protocal for collaborating on dev branch, but I just rebased this branch on top of master and force pushed the branch. Should I continue doing this in the future?

**Comment by jwnimmer-tri** [comment]
My usual advice would be to only ever use merge commits on shared branches.  Merges make it almost impossible to lose any changes, whereas forced pushes mean we each need to be very careful that we don't push atop each other.

**Comment by hongkai-dai** [comment]
Sounds good, I will only do merge commits then.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
The official (non-beta) Mosek 10 is released.  I've updated this PR to use it.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 3 of 5 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`-- commits` line 3 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKTXpM30yIB0RYyHUv):*
nit Here's the proper syntax



_Suggestion:_
```
  Co-authored-by: Jeremy Nimmer <jeremy.nimmer@tri.global>
```
___
*[`solvers/test/mosek_solver_test.cc` line 135 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKU3JY9P9Ru3ZRV-yv:-NAKU3JY9P9Ru3ZRV-yw:bklxrjp) ([raw file](https://github.com/robotlocomotion/drake/blob/7dabc7044fc833d5d1f07c539548a83ed697a2c4/solvers/test/mosek_solver_test.cc#L135)):*
> ```cpp
>   MosekSolver solver;
>   // Mosek 10 returns a solution that is accurate up to 1.2E-5 for this specific
>   // problem. Might need to change the tolerance when we upgrade Mosek.
> ```

Do we need to adjust this tolerance now?  Or if not, do we need to adjust the comment to be more specific about the problems to check for upon upgrading?
___
*[`tools/workspace/mosek/repository.bzl` line 80 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKTmzwDRgoGa5qFt3a:-NAKTmzwDRgoGa5qFt3b:bcpxaaw) ([raw file](https://github.com/robotlocomotion/drake/blob/7dabc7044fc833d5d1f07c539548a83ed697a2c4/tools/workspace/mosek/repository.bzl#L80)):*
> ```Starlark
>         files = [
>             # TODO(jwnimmer-tri) libcilk is no longer correct as of Mosek 10.
>             # "bin/libcilkrts.5.dylib",  FIXME
> ```

Working

This needs fixing.
___
*[`tools/workspace/mosek/repository.bzl` line 166 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKTrux-pdPMNPF95kd:-NAKTrux-pdPMNPF95ke:b-ed3f7l) ([raw file](https://github.com/robotlocomotion/drake/blob/7dabc7044fc833d5d1f07c539548a83ed697a2c4/tools/workspace/mosek/repository.bzl#L166)):*
> ```Starlark
>        # TODO(jwnimmer-tri) MOSEK uses TBB now, so upstream should probably
>        # be shipping the required Apache 2.0 notice in their Downloads (but
>        # isn't yet) and Drake should propgatate the TBB license here also.
> ```

Working

Still needs a fix.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`tools/workspace/mosek/repository.bzl` line 166 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKTrux-pdPMNPF95kd:-NAPm1M47pfmoENmxMan:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/7dabc7044fc833d5d1f07c539548a83ed697a2c4/tools/workspace/mosek/repository.bzl#L166)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Still needs a fix.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
I've done what I can here.  Feel free to squash, rebase, and force-push anytime.  I'll be mostly unavailable next week.

Be sure to launch "experimetal" job CI testing for macOS, sanitizer, wheels, etc. before landing this.

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490#-:-NAPt_1oApG34JLqwkCs:bowpnv7)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[`tools/workspace/mosek/repository.bzl` line 80 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKTmzwDRgoGa5qFt3a:-NAPtVLp42IMgZ1Fvy5w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7dabc7044fc833d5d1f07c539548a83ed697a2c4/tools/workspace/mosek/repository.bzl#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This needs fixing.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`solvers/test/mosek_solver_test.cc` line 135 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAKU3JY9P9Ru3ZRV-yv:-NAvZos65oTu_npXxk0s:b8k9yfp) ([raw file](https://github.com/robotlocomotion/drake/blob/7dabc7044fc833d5d1f07c539548a83ed697a2c4/solvers/test/mosek_solver_test.cc#L135)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do we need to adjust this tolerance now?  Or if not, do we need to adjust the comment to be more specific about the problems to check for upon upgrading?
</blockquote></details>

Done. I tested smaller tolerance and the test fails. So 1.2E-5 is still an accurate tolerance.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature but I think CI will show >80 linter errors.

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490#-:-NAvc6Z31CHskfwgowxQ:bl2ybu7)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver.cc` line 2003 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAvbOIp3aZVNqUZeSmy:-NAvbOIp3aZVNqUZeSmz:b-sctjbe) ([raw file](https://github.com/robotlocomotion/drake/blob/32cd3675493897c3555e364c0707dca7dcb41f98/solvers/mosek_solver.cc#L2003)):*
> ```cpp
>       initial_guess.unaryExpr([](double g) { return std::isfinite(g); }).any();
>   if (has_any_finite_initial_guess) {
>     // Set the initial guess for the integer/binary variables.
> ```

nit Is this comment stale now?  I think we have continuous vars supported now as well?
___
*[`solvers/mosek_solver.cc` line 2005 at r11](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAvbmy73tSoNfNbeEGg:-NAvbmy73tSoNfNbeEGh:bwk816g) ([raw file](https://github.com/robotlocomotion/drake/blob/32cd3675493897c3555e364c0707dca7dcb41f98/solvers/mosek_solver.cc#L2005)):*
> ```cpp
>     // Set the initial guess for the integer/binary variables.
>     DRAKE_ASSERT(initial_guess.size() == prog.num_vars());
>     MSKint32t num_mosek_vars{0};
> ```

nit `num_mosek_vars` here seems like dead code.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/test/mosek_solver_test.cc` line 324 at r12](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NAzh0EwE_VQcy6Vjms9:-NAzh0EwE_VQcy6VjmsA:b-556jr9) ([raw file](https://github.com/robotlocomotion/drake/blob/ffe09e908aeb3f65a5a33919b47b78e39681c824/solvers/test/mosek_solver_test.cc#L324)):*
> ```cpp
>   MosekSolver solver;
>   SolverOptions solver_options;
>   // Allow only one solution (the one corresponding to the initial guess)
> ```

nit Missing period at end of sentence.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
Still one more tolerance failure on macOS.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for Wednesday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490#-:-NBJokAbAK2VRXeL3DG1:b-k77w94)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Looks like a lot of work to get the update through, thanks!

platform :lgtm: 

> Reviewed 3 of 9 files at r1, 2 of 5 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 2 of 3 files at r8, 1 of 1 files at r10, 1 of 2 files at r12, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17490#-:-NBKO0Ew3INNXyUQncnJ:b97f0gb)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`solvers/test/mosek_solver_test.cc` line 341 at r15](https://reviewable.io/reviews/robotlocomotion/drake/17490#-NBK8xmS2c5UYuPgQIM7:-NBK8xmS2c5UYuPgQIM8:b-ozawj0) ([raw file](https://github.com/robotlocomotion/drake/blob/4aa20e4e7577c9bad7d92e67782a04aaf75aa851/solvers/test/mosek_solver_test.cc#L341)):*
> ```cpp
>   // By setting MSK_IPAR_MIO_CONSTRUCT_SOL=1, Mosek will first try to construct
>   // the continuous solution given the initial binary variable solutions. In
>   // this case it searchers the point on line segment A2A3 that is closest
> ```

typo s/searchers/searches.

**Pull request merged**
