### PR TITLE
Switch dependencies towards new RotationMatrix and Transform classes

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8065)

### CODE REVIEW

**Comment by mitiguy** [comment]
feature review +@hongkai-dai 
platform review +@seancurtis-tri 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8065#-:-L5GqaFO4reP1YTUAOqU:b6wsovb)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with some passing fancy noted

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5JPAL08IJnigiyonh5:-L5JPAL08IJnigiyonh6:b-6c48i2) ([raw file](https://github.com/robotlocomotion/drake/blob/15706e8a9034e0bfc100a57afe04679fa35a72c0/math/rotation_matrix.h#L195)):*
> ```objc
> Matrix3<T> XRotation(const T& theta) {
>   using drake::multibody::RotationMatrix;
>   RotationMatrix<T> R = RotationMatrix<T>::MakeRotationMatrixX(theta);
> ```

FYI (this isn't a defect). I've always hated lines of the form:

`Fool f = Foo::MakeFoo();`

How many times do I need to see 'Foo' in the same line? As I said, not a defect. But if you're inspired by this thought and have an idea for making the call sites look less redundant, I would not be against that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-:-L5JPtFCytN7z6lvxbm2:b-k5ge7p)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5JPAL08IJnigiyonh5:-L5KFsQNnPsewC0eiAAY:b-igerkx) ([raw file](https://github.com/robotlocomotion/drake/blob/15706e8a9034e0bfc100a57afe04679fa35a72c0/math/rotation_matrix.h#L195)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI (this isn't a defect). I've always hated lines of the form:

`Fool f = Foo::MakeFoo();`

How many times do I need to see 'Foo' in the same line? As I said, not a defect. But if you're inspired by this thought and have an idea for making the call sites look less redundant, I would not be against that.
</blockquote></details>

A slightly shorter version
```
return RotationMatrix<T>::MakeRotationMatrixX(theta).matrix();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-:-L5KG2Cx4Fk474RyKCa8:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5JPAL08IJnigiyonh5:-L5Ljr1xfGX93NfGjX3X:bga3yk7) ([raw file](https://github.com/robotlocomotion/drake/blob/15706e8a9034e0bfc100a57afe04679fa35a72c0/math/rotation_matrix.h#L195)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

A slightly shorter version
```
return RotationMatrix<T>::MakeRotationMatrixX(theta).matrix();
```
</blockquote></details>

FYI AN even shorter version:
return `RotationMatrix<T>::RotateX(theta).matrix();`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065)*

**Comment by mitiguy** [comment]
Review status: 1 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5JPAL08IJnigiyonh5:-L5RXxtW9FagVqE7OwUB:b-mq1vmz) ([raw file](https://github.com/robotlocomotion/drake/blob/15706e8a9034e0bfc100a57afe04679fa35a72c0/math/rotation_matrix.h#L195)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI AN even shorter version:
return `RotationMatrix<T>::RotateX(theta).matrix();`
</blockquote></details>

Done.  Upgraded to new names (similarly for other functions).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 517 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5UtvUEsRb8yX1Sxrt0:-L5UtvUEsRb8yX1Sxrt1:bu5cpaa) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/math/rotation_matrix.h#L517)):*
> ```objc
>   // https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-241j-dynamic-systems-and-control-spring-2011/readings/MIT6_241JS11_chap04.pdf
>   template <typename Derived>
>   static Matrix3<typename Derived::Scalar> ProjectMatrix3ToOrthonormalMatrix3(
> ```

Is it possible that `Derived::Scalar` is not the same as `T`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-:-L5UuHrDfj7kBLMwFcyT:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
1.5 small leftovers.

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/space_xyz_mobilizer.h, line 130 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5Uvj7ufSZnvzw_Givo:-L5Uvj7ufSZnvzw_Givp:bedtnx) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/space_xyz_mobilizer.h#L130)):*
> ```objc
>   /// into its closest element in `SO(3)` and then computes the space x-y-z
>   /// angles θ₁, θ₂, θ₃ that correspond to this rotation.
>   /// See RotationMatrix<T>::ProjectToRotationMatrix().
> ```

FYI Does this get a proper link in doxygen?

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 517 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5UtvUEsRb8yX1Sxrt0:-L5Uy3eZag8ZBOoPhRPs:bn0t00i) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/math/rotation_matrix.h#L517)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is it possible that `Derived::Scalar` is not the same as `T`?
</blockquote></details>

I agree this is a meaningful issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-:-L5Uy6fVfLsgL5jl2H9k:bdw421o)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 517 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5UtvUEsRb8yX1Sxrt0:-L5V1AXrs4HMSgDP3mIT:bkmifzc) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/math/rotation_matrix.h#L517)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I agree this is a meaningful issue.
</blockquote></details>

Resolved after a face to face discussion. `M` can have scalar type different from `T`, but the quality factor should be of type `T`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 518 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5V1NOb5ghm-5_QE3mt:-L5V1NOb5ghm-5_QE3mu:bjfmsy6) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/math/rotation_matrix.h#L518)):*
> ```objc
>   template <typename Derived>
>   static Matrix3<typename Derived::Scalar> ProjectMatrix3ToOrthonormalMatrix3(
>       const Eigen::MatrixBase<Derived>& M, double* quality_factor) {
> ```

Should we change it to `T* quality_factor`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065)*

**Comment by mitiguy** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 517 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5UtvUEsRb8yX1Sxrt0:-L5VQf_FkNZJsQvwpRWx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/math/rotation_matrix.h#L517)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Resolved after a face to face discussion. `M` can have scalar type different from `T`, but the quality factor should be of type `T`.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/math/rotation_matrix.h, line 518 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-L5V1NOb5ghm-5_QE3mt:-L5VQgw7oqOq0FSb4DCy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18c01694b73a85587debc708e46a8ba6e50e24e5/multibody/multibody_tree/math/rotation_matrix.h#L518)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we change it to `T* quality_factor`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 
:LGTM:

@hongkai-dai you have some blocking comments.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8065#-:-L5VSYSc79Hu6APi7IhL:b-xy2z4x)*

**Pull request merged**
