### PR TITLE
py value: Register Value[float] for use with ProximityProperties

### LINKED ISSUE #15640: pydrake: GetPropertyOrDefault() error, "Requested 'double', but found 'drake::pydrake::Object'"
Per Slack: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1629426512085800?thread_ts=1629402163.077600&cid=C2WBPQDB7

Found by @Brian-Acosta; reproduction code here:
https://github.com/DAIRLab/dairlib/tree/5c2ef7c3291e4c8cad00f11f9547e13153a2603a/examples/cubesim

Seems to be setting values with doubles, but instead getting cryptic errors like:
```
Traceback (most recent call last):
  File "{runfiles}/drake/tmp/cube_sim_test.py", line 91, in <module>
    sim.simulate(2.0)
  File "{runfiles}/drake/tmp/cube_sim_test.py", line 80, in simulate
    self.sim.AdvanceTo(time)
RuntimeError: GetPropertyOrDefault(): The property ('material', 'hunt_crossley_dissipation') exists, but is of a different type. Requested 'double', but found 'drake::pydrake::Object'
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #15640

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for feature review, please!

I'd like to limit my time on this if possible; if you'd like better testing for the workflow shown in issue, could I ask for help in that regard?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641#-:-MhWWXZO8vK1TGa55sFc:b9qvm5w)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
K, added bare minimum workflow test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641#-:-MhWZR0k55K4S0mDclSV:bjfbg8x)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Basically, :LGTM:.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641#-:-MhZdF5g4KtEp8CiMHPd:b-pgsb4j)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZd8Ek9xtxukCM217K:-MhZd8Ek9xtxukCM217L:bc4jgi3) ([raw file](https://github.com/robotlocomotion/drake/blob/0df7dbc57c4636bd7d3e0a5ab4f1d43d8128ccaa/-- commits#L1)):*
Is it your intent to squash this? If so, what will the commit message look like?
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZZeKGB9EXylRsSjiF:-MhZZeKGB9EXylRsSjiG:b3n2vic) ([raw file](https://github.com/robotlocomotion/drake/blob/0df7dbc57c4636bd7d3e0a5ab4f1d43d8128ccaa/bindings/pydrake/multibody/test/plant_test.py#L2107)):*
> ```Python
>         contact_info.F_Ac_W().get_coeffs()
> 
>     def test_issue_15640(self):
> ```

FYI I *desperately* wanted a more direct method for testing this. Essentially, all we need is *some* code anywhere that attempts to read a double-valued property. I'd briefly considered instantiating a `SceneGraph` and registering a geometry with hydroelastic properties. But we have insufficient bindings to do that.  :-P

Could you add this TODO:
```
TODO(15643) Remove this test, and move it into geometry_test.py as:
        scene_graph = mut.SceneGraph_[float]()
        source_id = scene_graph.RegisterSource("my example")
        ball_id = scene_graph.RegisterAnchoredGeometry(
            source_id,
            mut.GeometryInstance(RigidTransform_[float](), mut.Sphere(1.0),
                                 "sphere"))
        rigid_props = mut.ProximityProperties()
        mut.AddRigidHydroelasticProperties(0.25, rigid_props)
        # Assigning proximity properties with hydroelastic properties will force
        # SceneGraph to read the double-valued property "resolution_hint".
        scene_graph.AssignRole(source_id, ball_id, rigid_props)
```

As `ProximityProperties` is properly a geometry member this should ultimately be tested there and it is only lack of bindings that prevents us. 

-----------------------------------

That said, there's a *very* direct method. I could introduce a function whose sole purpose is (in C++) to read a double-valued property. I'd want to stash it in some pydrake test utility. I notice that there are a couple of .cc files in `pybind/test`. What is the advisibility of doing something like that? I'm happy to do the leg work, I just want to make sure it's consistent with what we're trying to achieve.

**Review by EricCousineau-TRI — COMMENTED** [review]
Would be OK serving as platform too?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641#-:-MholdVD8NTvS4gPh6mX:btp8yxh)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZd8Ek9xtxukCM217K:-Mhoemt25t6NpnqwPYKf:bghkfih) ([raw file](https://github.com/robotlocomotion/drake/blob/0df7dbc57c4636bd7d3e0a5ab4f1d43d8128ccaa/-- commits#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Is it your intent to squash this? If so, what will the commit message look like?
</blockquote></details>

Intent is to squash and use PR overview. That work?
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZZeKGB9EXylRsSjiF:-Mhol9dq4tzV3KbljSmk:b-l9yhgz) ([raw file](https://github.com/robotlocomotion/drake/blob/0df7dbc57c4636bd7d3e0a5ab4f1d43d8128ccaa/bindings/pydrake/multibody/test/plant_test.py#L2107)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I *desperately* wanted a more direct method for testing this. Essentially, all we need is *some* code anywhere that attempts to read a double-valued property. I'd briefly considered instantiating a `SceneGraph` and registering a geometry with hydroelastic properties. But we have insufficient bindings to do that.  :-P

Could you add this TODO:
```
TODO(15643) Remove this test, and move it into geometry_test.py as:
        scene_graph = mut.SceneGraph_[float]()
        source_id = scene_graph.RegisterSource("my example")
        ball_id = scene_graph.RegisterAnchoredGeometry(
            source_id,
            mut.GeometryInstance(RigidTransform_[float](), mut.Sphere(1.0),
                                 "sphere"))
        rigid_props = mut.ProximityProperties()
        mut.AddRigidHydroelasticProperties(0.25, rigid_props)
        # Assigning proximity properties with hydroelastic properties will force
        # SceneGraph to read the double-valued property "resolution_hint".
        scene_graph.AssignRole(source_id, ball_id, rigid_props)
```

As `ProximityProperties` is properly a geometry member this should ultimately be tested there and it is only lack of bindings that prevents us. 

-----------------------------------

That said, there's a *very* direct method. I could introduce a function whose sole purpose is (in C++) to read a double-valued property. I'd want to stash it in some pydrake test utility. I notice that there are a couple of .cc files in `pybind/test`. What is the advisibility of doing something like that? I'm happy to do the leg work, I just want to make sure it's consistent with what we're trying to achieve.
</blockquote></details>

Done. Went ahead and took a 15min stab at the direct method.

Regarding how test-only bindings, I'm a tad inconsistent, sorry. Yes, it can either be in a `pybind/test` directory, or you can stash it in the module itself, e.g. `pydrake.my_module._testing`. In this case, `pydrake.geometry._testing` already existed.

If this smells funny, then yeah, I can revert and do the TODO.

WDYT?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 1519 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MholqQPD460Wv4m-7Xw:-MholqQPD460Wv4m-7Xx:bq5xn8b) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1519)):*
> ```cpp
> void DefGetPropertyCpp(py::module m) {
>   auto func = [](const geometry::GeometryProperties& properties,
>                   const std::string& group, const std::string& name) {
> ```

BTW This passed linting; not a biggie for now?

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641#-:-MhsLEwO404IQsRbDV33:b3dcro0)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZd8Ek9xtxukCM217K):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Intent is to squash and use PR overview. That work?
</blockquote></details>

You tend to be more terse than I am. If I merge, I'll probably go a bit further in providing text in the commit message that limits the amount of spelunking developers have to do. But the message you propose is certainly minimally sufficient.
___
*[bindings/pydrake/geometry_py.cc, line 1516 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsOzSCAAp4fC0QLU50:-MhsOzSCAAp4fC0QLU51:bjyh97m) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1516)):*
> ```cpp
> }
> 
> template <typename T>
> ```

nit: This would benefit from an explanation of why it's here and what it accomplishes. For people less savvy with python bindings, weird examples really interfere with the monkey-see-monkey-do approach.
___
*[bindings/pydrake/geometry_py.cc, line 1536 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsLpBaDW3PD4TOowmE:-MhsLpBaDW3PD4TOowmF:be7368r) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1536)):*
> ```cpp
> 
>   // Ensures that Value[T] is registered and properly plumbed through in C++
>   // and Python.
> ```

nit: Do you want to reference the issue?
___
*[bindings/pydrake/test/geometry_test.py, line 627 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsM4eVBe_vizdBvQpZ:-MhsM4eVBe_vizdBvQp_:bf6qwe0) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/test/geometry_test.py#L627)):*
nit: I'm not sure that C++ plumbing is particularly meaningful (or accurate):

1. Part of this test is simply exercising the bindings (e.g., `GetProperty()`).
2. "C++ plumbing" won't mean anything to anyone in the future.

Here are my thoughts:

1. Evaluation of `value_2` seems to be mostly redundant of the tests on `GetProperty()` previously in the test (40 lines higher).
2. That said, this is a superset of that because it's focused on showing specific support for python built-in types.
3. It'd be nice to rephrase the test to reduce the redundancy.
4. The *significance* of calling `GetPropertyCpp` is lost in "C++ plumbing"; we should elaborate.

Here's what I propose:

1. Put a TODO with my name on this to clean up the test and reduce redundancies.
2. Change the current code comment to:

> Confirm that types stored in properties in python, resolve to expected types in C++ (with particular emphasis on python built in types as per issue 15640).
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZZeKGB9EXylRsSjiF:-MhsOFMC0xL2Qwk5EU2t:beoh0pa) ([raw file](https://github.com/robotlocomotion/drake/blob/0df7dbc57c4636bd7d3e0a5ab4f1d43d8128ccaa/bindings/pydrake/multibody/test/plant_test.py#L2107)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Went ahead and took a 15min stab at the direct method.

Regarding how test-only bindings, I'm a tad inconsistent, sorry. Yes, it can either be in a `pybind/test` directory, or you can stash it in the module itself, e.g. `pydrake.my_module._testing`. In this case, `pydrake.geometry._testing` already existed.

If this smells funny, then yeah, I can revert and do the TODO.

WDYT?
</blockquote></details>

I love it. I'd love it a bit more with some accompanying documentation, but it's *everything* I'd hoped for and more.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZd8Ek9xtxukCM217K):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You tend to be more terse than I am. If I merge, I'll probably go a bit further in providing text in the commit message that limits the amount of spelunking developers have to do. But the message you propose is certainly minimally sufficient.
</blockquote></details>

OK SGTM! I'll let you merge.
___
*[bindings/pydrake/geometry_py.cc, line 1516 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsOzSCAAp4fC0QLU50:-MhtVfQ56W0ItOit2dpx:b-ekz1uu) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1516)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This would benefit from an explanation of why it's here and what it accomplishes. For people less savvy with python bindings, weird examples really interfere with the monkey-see-monkey-do approach.
</blockquote></details>

OK Not sure how to put helpful comment here; just forward referencing Python test for now, and placing in `testing` namespace to try and delineate for more meaningful (public-facing) code.
___
*[bindings/pydrake/geometry_py.cc, line 1536 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsLpBaDW3PD4TOowmE:-MhtViJo4bpNw-ZjJBQS:bqym6a8) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1536)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Do you want to reference the issue?
</blockquote></details>

OK Referencing Python test for now.
___
*[bindings/pydrake/test/geometry_test.py, line 627 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsM4eVBe_vizdBvQpZ:-MhtVlaF7nIQ7uK9zw6V:b-h1k9lk) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/test/geometry_test.py#L627)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'm not sure that C++ plumbing is particularly meaningful (or accurate):

1. Part of this test is simply exercising the bindings (e.g., `GetProperty()`).
2. "C++ plumbing" won't mean anything to anyone in the future.

Here are my thoughts:

1. Evaluation of `value_2` seems to be mostly redundant of the tests on `GetProperty()` previously in the test (40 lines higher).
2. That said, this is a superset of that because it's focused on showing specific support for python built-in types.
3. It'd be nice to rephrase the test to reduce the redundancy.
4. The *significance* of calling `GetPropertyCpp` is lost in "C++ plumbing"; we should elaborate.

Here's what I propose:

1. Put a TODO with my name on this to clean up the test and reduce redundancies.
2. Change the current code comment to:

> Confirm that types stored in properties in python, resolve to expected types in C++ (with particular emphasis on python built in types as per issue 15640).
</blockquote></details>

Done. Split into separate test, referenced issue w/ suggested text.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 2107 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhZZeKGB9EXylRsSjiF:-MhtWLXP1BipV-kTBsMF:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/0df7dbc57c4636bd7d3e0a5ab4f1d43d8128ccaa/bindings/pydrake/multibody/test/plant_test.py#L2107)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I love it. I'd love it a bit more with some accompanying documentation, but it's *everything* I'd hoped for and more.
</blockquote></details>

OK Sweet!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15641)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 1516 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsOzSCAAp4fC0QLU50:-MhtkAET8PrqEdsEqt9t:by35dzg) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1516)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Not sure how to put helpful comment here; just forward referencing Python test for now, and placing in `testing` namespace to try and delineate for more meaningful (public-facing) code.
</blockquote></details>

The network of comments serves perfectly. Thanks.
___
*[bindings/pydrake/geometry_py.cc, line 1536 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15641#-MhsLpBaDW3PD4TOowmE:-MhtkEwT2sE8MSq9KWYJ:by35dzg) ([raw file](https://github.com/robotlocomotion/drake/blob/1b4f160390b08babaea7756cc6c50c4e71ca7f25/bindings/pydrake/geometry_py.cc#L1536)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Referencing Python test for now.
</blockquote></details>

The network of comments serves perfectly. Thanks.

**Pull request merged**
