### PR TITLE
[workspace] Avoid crashes in python repository rule

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(Refer to the commit message for details.)

Towards #20556 and #14967.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562)

### CODE REVIEW

**Comment by lepalom** [comment]
I have cherry picked the changes in a debian bookworm, but I still have a crash. Changes are [here](https://github.com/lepalom/drake). Take care because there are more changes related to build it in Debian. Please. @jwnimmer-tri test it.

**Comment by jwnimmer-tri** [comment]
Here's some results from my experimentation: https://github.com/jwnimmer-tri/drake/commits/bookworm.

The first commit just adds some Dockerfile stuff to make it easier for me to test (along with a list of Build-Depends, in effect).
The next two commits implement the "Presume unknown systems works like Ubuntu Jammy" trick I mentioned before.
The last commit fixes a hard-coded path to libclang.
With all of that together, the `make install` step passes.

Longer term, trying to add "Debian" as a distinct OS flavor from "Ubuntu" like you were trying to do in your branch will not scale.  Instead, we need to refactor Drake to ask "is_linux" instead of "is_ubuntu".

The Python change here is probably useful once we have "is_linux" more generally, but I'm not sure it's of much help just on its own.

For now though, those patches should let you build from source and keep exploring from there.

**Comment by lepalom** [comment]
The repo builds in debian bookworm as root and docker. However, after have done some modifications about the path, I have not been able to build it in my bookworm. I got:

```
ERROR: /home/users/leopold.palomo/robotica/projects/drake.git/systems/framework/BUILD.bazel:531:17: //systems/framework:_leaf_system_compiled_cc_impl depends on @abseil_cpp_internal//absl/container:inlined_vector in repository @abseil_cpp_internal which failed to fetch. no such package '@abseil_cpp_internal//absl/container': com.google.devtools.build.lib.vfs.FileAccessException: /var/cache/bazel/repository_cache/content_addressable/sha256 (S?ha denegat el perm�s)
ERROR: Analysis of target '//:install' failed; build aborted: 
INFO: Elapsed time: 7.080s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (238 packages loaded, 10417 targets configured)
    Fetching https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-linux_x64.tar.gz; 106.0 MiB (55.9%)
make[2]: *** [CMakeFiles/drake_cxx_python.dir/build.make:86: drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:839: CMakeFiles/drake_cxx_python.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

Also, I have noticed that if you have installed bazel (4.2.3 in bookworm) you got a lot of errors and it doesn't build. So, I had to remove bazel to build drake.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
Dropping the supported-version check is okay. The changes to how we specify test programs on the command line is fine. The other refactoring seems unnecessary and unhelpful?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-:-NpLXX1u34EdUCo38gc5:b-pit5gv)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLUcdCD-f4ZIcp7E-s):*
"in the a rule"? I think the "a" doesn't belong? (Is Reviewable even going to preserve this information on merge? I can never remember which of the commit(s) or description gets used under what circumstances.)
___
*[`tools/workspace/python/repository.bzl` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLVAw28O8eapMAgMBU:-NpLVAw28O8eapMAgMBV:b-1xkkjy) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdae85e30de6197289e0d61bf298e9293bcaa377/tools/workspace/python/repository.bzl#L46)):*
> ```Starlark
>     """
> 
>     # - `is_any_macos`
> ```

Why "is_**any**_macos"? Why not "is_macos" like `os_result`?

Note: if the reason is to set this `if osr.is_macos or osr.is_macos_wheel`, it would be clearer to retain `determine_os` and say thusly. It would also avoid duplicating the `homebrew_prefix` logic. (Why isn't `determine_os` being used, anyway?)

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> The other refactoring seems unnecessary and unhelpful?

I'm happy to work on these but I'm not sure exactly what you mean.  Was it only the `is_any_macos` discussion, or more than that?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-:-NpLYzOQ5F8gpMkjDEbu:b6viwhu)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLUcdCD-f4ZIcp7E-s):*
> "in the a rule"? I think the "a" doesn't belong?

Yup, fixed.

> (Is Reviewable even going to preserve this information on merge? I can never remember which of the commit(s) or description gets used under what circumstances.)

The commit message(s) are always intact (and the PR description is always ignored), **unless** the platform reviewer edits the text in the merge button drop-down box as they are merging.  (Typically they will only do that when the PR is cluttered with uncurated incremental pushes of "fix", "typo" etc.)
___
*[`tools/workspace/python/repository.bzl` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLVAw28O8eapMAgMBU:-NpLZKekDo6gplj0YLK8:bxa0az5) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdae85e30de6197289e0d61bf298e9293bcaa377/tools/workspace/python/repository.bzl#L46)):*
> Why isn't `determine_os` being used, anyway?

The overall goal of the PR train is to delete `determine_os` entirely.  There's only a couple more places to purge after this one.

Thus, the `homebrew_prefix` duplication is only temporary.  (The only other use of `os_result.homebrew_prefix` is `libjpeg/repository.bzl` which is deprecated and will be deleted later this week.)

> Why not "is_macos" like `os_result`?

Your intuition was right -- in `os_result`, the variable `is_macos` meant "Building a full release from source, using Homebrew", so in wheel builds on OS X `is_macos` would be false.  Since this variable had different semantics, I was using a different name for it.

While considering how to choose a better name, I took a more careful look and found a bunch of other things, now pushed as changes:

- There was really no reason to return _anything_ about macOS in the helper struct, so this now is just deleted entirely.

- Purging `-lpython3.#` out of the module linkopts seems like it was vestigial from the days of Ubuntu 16.04 or earlier, so that's deleted now too.  (No `python3.#-config` I tested on any platform seems to produce that flag anymore.)

- The explanation for the two different link flavors was awkward.  I rewrote the docs (and variable names) to hopefully better explain what we're trying to do, and how we're doing it.

PTAL.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
Okay, I think it :lgtm:, though the nitty-gritty of Python linking is somewhat outside my area of expertise and might not hurt to have another set of eyes. (Of course, we still have platform review...)

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-:-NpLndXF7dgduMFVkdOh:b-yavhfz)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/python/repository.bzl` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLVAw28O8eapMAgMBU:-NpLlA0tDzVjCgBu7e5p:b-vu69y8) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdae85e30de6197289e0d61bf298e9293bcaa377/tools/workspace/python/repository.bzl#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Why isn't `determine_os` being used, anyway?

The overall goal of the PR train is to delete `determine_os` entirely.  There's only a couple more places to purge after this one.

Thus, the `homebrew_prefix` duplication is only temporary.  (The only other use of `os_result.homebrew_prefix` is `libjpeg/repository.bzl` which is deprecated and will be deleted later this week.)

> Why not "is_macos" like `os_result`?

Your intuition was right -- in `os_result`, the variable `is_macos` meant "Building a full release from source, using Homebrew", so in wheel builds on OS X `is_macos` would be false.  Since this variable had different semantics, I was using a different name for it.

While considering how to choose a better name, I took a more careful look and found a bunch of other things, now pushed as changes:

- There was really no reason to return _anything_ about macOS in the helper struct, so this now is just deleted entirely.

- Purging `-lpython3.#` out of the module linkopts seems like it was vestigial from the days of Ubuntu 16.04 or earlier, so that's deleted now too.  (No `python3.#-config` I tested on any platform seems to produce that flag anymore.)

- The explanation for the two different link flavors was awkward.  I rewrote the docs (and variable names) to hopefully better explain what we're trying to do, and how we're doing it.

PTAL.
</blockquote></details>

Okay; that's rather important information to know... I will be interested to see what happens to the (by my count) other eight uses...

BTW, the 'determine homebrew prefix' logic also exists in `tools/workspace/execute.bzl`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/python/repository.bzl` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLVAw28O8eapMAgMBU:-NpMy5jjBuaU7lkxAXYc:b-kk724t) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdae85e30de6197289e0d61bf298e9293bcaa377/tools/workspace/python/repository.bzl#L46)):*
> Okay; that's rather important information to know...

Good point!  Disclaimer added.

> I will be interested to see what happens to the (by my count) other eight uses...

Several of them are in deprecated rules that will be deleted later this week.

> BTW, the 'determine homebrew prefix' logic also exists in `tools/workspace/execute.bzl`.

Ah, I missed that in my searching (because it was the bin path instead of the whole prefix).  I've refactored now to reduce duplication.

**Comment by jwnimmer-tri** [comment]
> The nitty-gritty of Python linking is somewhat outside my area of expertise and might not hurt to have another set of eyes.

Luckily @rpoyner-tri knows a bit about this.  I'll also \CC @EricCousineau-TRI for awareness, and/or in case you'd like to take a look.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-wheel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/execute.bzl` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpQaF8F8bQc3PRg-LE6:-NpQaF8G65xUrrzCsXGa:b-vdzg9z) ([raw file](https://github.com/RobotLocomotion/drake/blob/74e759d20a9c955fb70645b15fc75a257795e460/tools/workspace/execute.bzl#L9)):*
> ```Starlark
>     # paths.
>     if repo_ctx.os.name == "mac os x":
>         arch_result = repo_ctx.execute(["/usr/bin/arch"])
> ```

FYI, we're confident `/usr/bin/arch` and `repo_ctx.os.arch` are the same? (I guess CI is likely to fail otherwise?)
___
*[`tools/workspace/python/repository.bzl` line 46 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpLVAw28O8eapMAgMBU:-NpQ_oAp4LoKUFt9UaSo:b-ioxs9f) ([raw file](https://github.com/RobotLocomotion/drake/blob/cdae85e30de6197289e0d61bf298e9293bcaa377/tools/workspace/python/repository.bzl#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Okay; that's rather important information to know...

Good point!  Disclaimer added.

> I will be interested to see what happens to the (by my count) other eight uses...

Several of them are in deprecated rules that will be deleted later this week.

> BTW, the 'determine homebrew prefix' logic also exists in `tools/workspace/execute.bzl`.

Ah, I missed that in my searching (because it was the bin path instead of the whole prefix).  I've refactored now to reduce duplication.
</blockquote></details>

I meant in terms of "why is the review making this change", but okay, the disclaimer won't hurt. :slightly_smiling_face:

Thanks for refactoring `homebrew_prefix`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/execute.bzl` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpQaF8F8bQc3PRg-LE6:-NpQkN0H2A4rfcYVSahq:b-8t59s5) ([raw file](https://github.com/RobotLocomotion/drake/blob/74e759d20a9c955fb70645b15fc75a257795e460/tools/workspace/execute.bzl#L9)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, we're confident `/usr/bin/arch` and `repo_ctx.os.arch` are the same? (I guess CI is likely to fail otherwise?)
</blockquote></details>

Yup.  The string names they use to notate the arches differ, but whether they return the intel name vs the aarch name is consistent.

**Comment by mwoehlke-kitware** [comment]
*[`tools/workspace/execute.bzl` line 9 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpQaF8F8bQc3PRg-LE6:-NpQrAfKBzJ6BtV-otJo:b-jaq5fi) ([raw file](https://github.com/RobotLocomotion/drake/blob/74e759d20a9c955fb70645b15fc75a257795e460/tools/workspace/execute.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yup.  The string names they use to notate the arches differ, but whether they return the intel name vs the aarch name is consistent.
</blockquote></details>

:+1:  (And, sure, string names aren't important.)

FYI, I subsequently remembered where it is that we play games with `arch` and reexecing into a different environment. I *thought* I recalled that wheel builds did something funky, which was why I was concerned, but it's CI (Jenkins always launches jobs in x86 mode; n.b. logic in `ctest_driver_script_wrapper.bash`). That gets sorted early enough that I wouldn't expect problems by the time Bazel is running. Now that I remember what specifically was making me suspicious, I am more confident it isn't an issue here.

**Comment by mwoehlke-kitware** [comment]
I think this is ready to be kicked over to @rpoyner-tri for platform review?

**Comment by jwnimmer-tri** [comment]
Oops, I thought I had.  +@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-:-NpRln4l7m6jeU71_MyE:bnfp4nl)* status: 1 unresolved discussion

___
*[`tools/workspace/python/repository.bzl` line 140 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20562#-NpRlj0bDplNFfYLjyNh:-NpRlj0bDplNFfYLjyNi:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/98c95af361fc10ca43c0e5eb4f905f3758c88568/tools/workspace/python/repository.bzl#L140)):*
> ```Starlark
>     linkopts = [linkopt for linkopt in linkopts if linkopt]
> 
>     # Undo whitepsace splits for options with a positional argument, e.g., we
> ```

typo



_Suggestion:_
```Starlark
whitespace
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20562)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware

**Pull request merged**
