### PR TITLE
Move jchart2d install into tools/install

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6425)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6425#-:-Knf3opxkdmO67L9Bphu:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6425)*

**Comment by sammy-tri** [comment]
This looks basically OK to me, but I haven't looked at anything installation related before.   I'm currently looking for a platform reviewer who has to assist with a sanity check.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6425#-:-Knf5vMpdEYlopbMv9g8:b49g841)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for additional platform review.  :lgtm: as far as I understand it

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6425#-:-KnfCjoOQ6Z2VRpAw5EX:b6h3d37)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6425#-:-KnfEJ3U4KwjAAWHL7XI:bnfp4nl)*

**Pull request merged**
