### PR TITLE
Declare and port to drake_py_* wrappers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7243)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review per rotation, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7243#-:-KwFvW1a5ZySiegchfLp:bnfp4nl)*

**Comment by soonho-tri** [comment]
@jwnimmer-tri , FYI, "automotive lgtm missing".

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7243#-:-KwFv_LWj6-jPDKPFEzv:bwwpn8z)*

**Comment by jwnimmer-tri** [comment]
Self-:car: honk honk.

**Pull request merged**
