### PR TITLE
Avoid huge-integer accidents on invalid input

### LINKED ISSUE #3852: Mysterious Unit Test Error - Polynomial<double>("!") Failed To Throw Exception
# The Error

```
/home/ubuntu/workspace/linux-clang-ninja-continuous-debug/drake/common/test/polynomial_test.cc:218: Failure
Expected: Polynomial<double>("!") throws an exception of type std::runtime_error.
  Actual: it throws nothing.
```

# Example CI Test Logs

* https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-continuous-debug/797/

# Prognosis

Maybe there's something stochastic in this test? @jwnimmer-tri might have experienced it months ago. Not sure.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #3852.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3877)

### CODE REVIEW

**Comment by liangfok** [comment]
+@liangfok :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3877#-:-KUeFoBaerAw19uSIan9:b-3x80r7)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please (unless someone else steals it first).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3877#-:-KUg6xSHBgzm_QxSaw8G:b7xivi5)*

**Comment by sherm1** [comment]
:lgtm: (one ignorable non-blocking comment)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/polynomial.cc, line 532 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3877#-KUhr0KjwsdSBeRGs9PG:-KUhr0Kki2UxcmmzBMuE:bb6c7nd) ([raw file](https://github.com/robotlocomotion/drake/blob/40bf97f36615a68e9365e7085ea5e5e737fd1304/drake/common/polynomial.cc#L532)):*
> ```cpp
> template <typename CoefficientType>
> typename Polynomial<CoefficientType>::VarType
> Polynomial<CoefficientType>::VariableNameToId(const string name,
> ```

BTW, better if this were `const string&` (in case you feel like changing it while you're here). Feel free to ignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3877#-:-KUhrX9dMA3LMH4nGQjz:b-21cxxt)*

**Comment by jwnimmer-tri** [comment]
Yeah.  _So many things_ to want to fix in this file, but I will keep my hands clean.

**Pull request merged**
