### PR TITLE
[performance] Add allocation reporting

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #17487 to restore heap reporting.

Looking carefully at the `compare.py` report for the `CassieAutoDiff/MassMatrix/1` data with repetitions=100, it definitively shows that this new instrumentation costs exactly 3 extra CPU cycles per allocation.  On my 3 GHz machine, that's +1 ns per allocation, scaled up by 31,400 allocations is a difference of +31us on benchmark (~2%).

This probably the most extreme case; of all the benchmarks, MassMatrix has one of the highest fraction of allocations per instruction.

We could imagine automatically offering benchmark binaries that do not link in the malloc hooks, but for me the 3 cycle penalty is a reasonable enough one to leave unconditionally enabled.  Any relative before/after measurements for performance improvements should still hold true.

---

Sample output for cassie now:
```
----------------------------------------------------------------------------------------
Benchmark                                    Time             CPU    Allocs   Iterations
----------------------------------------------------------------------------------------
CassieDouble/MassMatrix/0                 12.8 us         12.8 us         0        49308
CassieDouble/InverseDynamics/0            16.5 us         16.5 us         3        42641
CassieDouble/ForwardDynamics/0            35.9 us         35.9 us         5        19442
CassieAutoDiff/MassMatrix/0                402 us          402 us         0         1753
CassieAutoDiff/MassMatrix/1               1256 us         1255 us     31.4k          530
CassieAutoDiff/MassMatrix/2                410 us          410 us         0         1707
CassieAutoDiff/MassMatrix/3               1491 us         1491 us     31.4k          467
CassieAutoDiff/InverseDynamics/0           504 us          503 us         3         1358
CassieAutoDiff/InverseDynamics/1          1492 us         1491 us     36.9k          475
CassieAutoDiff/InverseDynamics/2           858 us          858 us     10.8k          817
CassieAutoDiff/InverseDynamics/3          1897 us         1896 us     37.4k          377
CassieAutoDiff/InverseDynamics/4           720 us          719 us      6.9k          981
CassieAutoDiff/InverseDynamics/5          1856 us         1855 us     37.5k          376
CassieAutoDiff/InverseDynamics/6          1011 us         1010 us     12.0k          686
CassieAutoDiff/InverseDynamics/7          2287 us         2285 us     38.0k          309
CassieAutoDiff/ForwardDynamics/0           821 us          820 us        73          856
CassieAutoDiff/ForwardDynamics/1          2563 us         2562 us     55.9k          274
CassieAutoDiff/ForwardDynamics/2          1209 us         1209 us     11.6k          581
CassieAutoDiff/ForwardDynamics/3          3278 us         3276 us     57.4k          215
CassieAutoDiff/ForwardDynamics/8           897 us          897 us      3.4k          775
CassieAutoDiff/ForwardDynamics/9          2964 us         2962 us     56.2k          238
CassieAutoDiff/ForwardDynamics/10         1225 us         1224 us     11.6k          567
CassieAutoDiff/ForwardDynamics/11         3524 us         3521 us     57.7k          198
CassieExpression/MassMatrix/0             1772 us         1771 us      7.0k          397
CassieExpression/MassMatrix/1             8557 us         8552 us     48.2k           83
CassieExpression/MassMatrix/2             1769 us         1768 us      7.0k          399
CassieExpression/MassMatrix/3             8468 us         8465 us     48.2k           83
CassieExpression/InverseDynamics/0        2275 us         2274 us      8.4k          308
CassieExpression/InverseDynamics/1       29690 us        29675 us     73.4k           24
CassieExpression/InverseDynamics/2        7509 us         7502 us     48.6k           91
CassieExpression/InverseDynamics/3       27136 us        27115 us     74.5k           26
CassieExpression/InverseDynamics/4        4294 us         4291 us     32.5k          162
CassieExpression/InverseDynamics/5       27763 us        27745 us     74.2k           26
CassieExpression/InverseDynamics/6       10374 us        10368 us     50.3k           64
CassieExpression/InverseDynamics/7       26030 us        26011 us     75.2k           28
CassieExpression/ForwardDynamics/0        3625 us         3623 us     13.8k          189
CassieExpression/ForwardDynamics/2       17187 us        17175 us     88.3k           41
CassieExpression/ForwardDynamics/8        4738 us         4736 us     29.6k          147
CassieExpression/ForwardDynamics/10      16944 us        16932 us     88.4k           42
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri what do you think about this?

Another tack would be to use [`RegisterMemoryManager`](https://github.com/google/benchmark/blob/main/docs/user_guide.md#memory-usage) to report it that way.  I don't know if you tried exploring that API yet?

**Review by rpoyner-tri — COMMENTED** [review]
I'm not wild about this particular construction; why do you need to count allocations every time through the benchmark inner loop?  Prior versions of this program went so some trouble to disentangle memory tracking from benchmarking; see for  example dd1c83bfc575ca3d3f344f6cfdb2360dec69001c .

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518#-:-N6O8_LI32xZy2TqZJng:b-hbnju5)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
Yup, I had seen that in the history, but before the change I did run the benchmark a bunch of times with and without the counters it didn't appear to affect the reported timings.  Maybe I didn't run it enough, or made a PEBKAC?

I would like to get a bit more heap telemetry than just the two or three samples we had before -- I think some cases will have a bit more variation as things settle out.

Maybe I'll take a shot at a `RegisterMemoryManager` that doesn't use `LimitMalloc` at all, to be more obviously on the side of "will never affect the timings in any meaningful way".

Aside: I'm also not sure why I used a mutex in `limit_malloc`.  Upon re-reading it, I think a simple `std::atomic<std::shared_ptr>` (spelled in the awkward C++17 form for now) would suffice.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
Once the #17581 refactor is merged, I'll return to here and try to (1) measure the instrumentation overhead, and (2) add instructions to display the heap results.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 12 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
I just pushed a rebase, plus some clean-ups.  I think it's ready for high-level inspection now @rpoyner-tri.

The basic heap reporting is available the default output table.  If you look into to the json report, there's additional heap data as well (beyond just the number of allocs).  I think maybe the current reporting is good enough.

I haven't tried to measure the additional instrumentation overhead.  Possibly you'd be game for trying to do that?

**Review by rpoyner-tri — COMMENTED** [review]
I remember the overhead being non-0, but no details at all beyond that. I'll see what I can recall or rediscover.

> Reviewed 1 of 7 files at r2, 3 of 18 files at r4, 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17518#-:-NOv5ibi01P0-cHDOY3d:b-vg8hpr)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`tools/BUILD.bazel` line 86 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17518#-NOv60AI-NVENsBM31C5:-NOv60AI-NVENsBM31C6:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/30497d8c5f969590aa6e34262c5aca3f20a97c1b/tools/BUILD.bazel#L86)):*
> ```Starlark
> 
> config_setting(
>     name = "using_sanitizier",
> ```

typo



_Suggestion:_
```Starlark
sanitizer
```
___
*[`tools/dynamic_analysis/bazel.rc` line 62 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17518#-NOv9dzN1M7sVtnHfqj6:-NOv9dzN1M7sVtnHfqj7:b-9g3j4d) ([raw file](https://github.com/RobotLocomotion/drake/blob/30497d8c5f969590aa6e34262c5aca3f20a97c1b/tools/dynamic_analysis/bazel.rc#L62)):*
> ```
> # See https://clang.llvm.org/docs/AddressSanitizer.html
> build:asan --test_timeout=150,750,2250,9000  # 2.5x
> build:asan --define=HAS_SANITIZER=ON
> ```

Above file says `USING`; this says `HAS`. Are they supposed to match?
___
*[`tools/performance/BUILD.bazel` line 41 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17518#-NOv9qMY5jy3f5e_ZW0f:-NOv9qMY5jy3f5e_ZW0g:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/30497d8c5f969590aa6e34262c5aca3f20a97c1b/tools/performance/BUILD.bazel#L41)):*
> ```Starlark
>         ":apple": ["fixture_memory_no.cc"],
>         "//tools:using_memcheck": ["fixture_memory_no.cc"],
>         "//tools:using_sanitizier": ["fixture_memory_no.cc"],
> ```

typo



_Suggestion:_
```Starlark
sanitizer
```

**Comment by jwnimmer-tri** [comment]
Yup.  With `limit_malloc` the overhead would have been more.  I'm hoping that an extra couple of integer operations + predicted function call will be way down in the noise.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17518)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

___
*[`tools/dynamic_analysis/bazel.rc` line 62 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/17518#-NOv9dzN1M7sVtnHfqj6:-NOvD69p6LbCCQ7KWdrL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/30497d8c5f969590aa6e34262c5aca3f20a97c1b/tools/dynamic_analysis/bazel.rc#L62)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Above file says `USING`; this says `HAS`. Are they supposed to match?
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17518)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17518)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17518)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> > I think it's ready for high-level inspection now @rpoyner-tri. I haven't tried to measure the additional instrumentation overhead for leaving this unconditionally enabled. Possibly you'd be game for trying to do that?
>
> I'll see what I can recall or rediscover.

@rpoyner-tri are you still planning to look into this?

Or we could ask @sherm1 to join in and help, since his major goals these days are runtime performance.

**Review by rpoyner-tri — COMMENTED** [review]
Let's tag @sherm1; I'm not sure I'm going to get to it soon.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/17518#-:-NSCRGI8ECrYuwnI-R2U:b-z74l73)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Am I correct that this has zero overhead if we don't enable tracking? If so I like it!

See above.  I estimated the penalty as 3 cycles per malloc.  I was hoping Rico (now you) could double-check that, and then also bless that we don't care.

**Review by sherm1 — COMMENTED** [review]
Is that because it overrides malloc(), etc. unconditionally even when we're not benchmarking? I wouldn't object to burning a few cycles per malloc during benchmarking but it seems a shame to do that otherwise. Is it possible to override only when benchmarking or testing?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518#-:-NSCzD_DBkXgFab7yvKP:b-kiucp0)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Is that because it overrides malloc(), etc. unconditionally even when we're not benchmarking

Yes.  As of this PR, in benchmarking programs (not application code) we unconditionally redirect malloc.  So all benchmarks would be tallying the mallocs.  The command-line flag here only toggles some one-time begin/end stats and the output reporting.

> I wouldn't object to burning a few cycles per malloc during benchmarking but it seems a shame to do that otherwise. Is it possible to override only when benchmarking or testing?

I think maybe you thought that this hooks malloc in production code?  The hook is _only_ in the benchmarking programs.

**Review by sherm1 — COMMENTED** [review]
Ah, yes -- that's what I was worried about. With that correction, I endorse this wholeheartedly! And I understand now that the MemoryManager name is inherited from Google Bench, so fine.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518#-:-NSDS0CFBQOrNKd17QYx:bkdgx0z)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Okay.  It's been a while since I skimmed this code, so I'll plan to do that soon and then we should be ready for feature review.

**Comment by jwnimmer-tri** [comment]
Ping @sherm1?

**Review by sherm1 — COMMENTED** [review]
Oops slipped by, sorry -- feature :lgtm:

> Reviewed 2 of 7 files at r2, 2 of 18 files at r4, 4 of 12 files at r5, 10 of 15 files at r6, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518#-:-NWyIhk21bWXogi8zDqD:bapb067)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

+@ggould-tri for platform review or delegation per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; consider release notes since external contributors have cared about memory benchmarking in the past?

> Reviewed 2 of 7 files at r2, 3 of 18 files at r4, 4 of 12 files at r5, 11 of 15 files at r6, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518#-:-NXB0VSu-7sj83U6AAcO:bx36d77)* status: 2 unresolved discussions

___
*[`tools/performance/fixture_memory_yes.cc` line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake/17518#-NXB246pDVzufpiWxP1Q:-NXB246pDVzufpiWxP1R:b-pzqji0) ([raw file](https://github.com/robotlocomotion/drake/blob/e5411da3f88f9c868dc65d970ebd0187a43e2b76/tools/performance/fixture_memory_yes.cc#L38)):*
> ```cpp
>   }
> 
>   static int64_t g_num_allocs;
> ```

minor:  IMO, this block of static globals deserves a comment explaining their thread safety story.

(as I read it, the story is something like, "drake is largely single-threaded and anyway we're willing to accept the occasional hazard here for speed"?)
___
*[`tools/performance/fixture_memory_yes.cc` line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/17518#-NXB7VFe0zHTTztkN-A1:-NXB7VFe0zHTTztkN-A2:b-8g0jqb) ([raw file](https://github.com/robotlocomotion/drake/blob/e5411da3f88f9c868dc65d970ebd0187a43e2b76/tools/performance/fixture_memory_yes.cc#L40)):*
> ```cpp
>   static int64_t g_num_allocs;
>   static int64_t g_total_allocated_bytes;
>   static struct mallinfo2 g_mallinfo_tare;
> ```

minor, author's discretion, consider `static_assert(is_trivially_constructible<mallinfo2>());` here to document style guide compliance.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518)* status: 2 unresolved discussions

___
*[`tools/performance/fixture_memory_yes.cc` line 40 at r9](https://reviewable.io/reviews/robotlocomotion/drake/17518#-NXB7VFe0zHTTztkN-A1:-NXBBTw76-jaW2lTBJYL:bqjnmra) ([raw file](https://github.com/robotlocomotion/drake/blob/e5411da3f88f9c868dc65d970ebd0187a43e2b76/tools/performance/fixture_memory_yes.cc#L40)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor, author's discretion, consider `static_assert(is_trivially_constructible<mallinfo2>());` here to document style guide compliance. 
</blockquote></details>

... and obviously I meant `destructible` here :man_facepalming:

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518)* status: 2 unresolved discussions

**Review by jwnimmer-tri — COMMENTED** [review]
> Consider release notes since external contributors have cared about memory benchmarking in the past?

The bazel visibility of the benchmarking library prevents anyone downstream from using it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518#-:-NXBP5p85hfD6pVU8s3p:b-73r2s5)* status: 1 unresolved discussion

___
*[`tools/performance/fixture_memory_yes.cc` line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake/17518#-NXB246pDVzufpiWxP1Q:-NXBRelz6O7LHTIgULac:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/e5411da3f88f9c868dc65d970ebd0187a43e2b76/tools/performance/fixture_memory_yes.cc#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  IMO, this block of static globals deserves a comment explaining their thread safety story.

(as I read it, the story is something like, "drake is largely single-threaded and anyway we're willing to accept the occasional hazard here for speed"?)
</blockquote></details>

Done?

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17518)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

**Pull request merged**
