### PR TITLE
website: Add link to drake-ros

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Merge "From Other Languages" into new "Integrations" section
Add reference to LCM
Remove Python logo

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Current preview:

> image

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake and +@jwnimmer-tri for review, please!

+@iantheengineer for additional review
\cc @sloretz

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941#-:-NC7MlBs8TRaz3ms1Rgy:b40ayu6)* status: 1 unresolved discussion, LGTM missing from assignees RussTedrake(platform),jwnimmer-tri(platform),IanTheEngineer, missing label for release notes (waiting on @EricCousineau-TRI, @IanTheEngineer, @jwnimmer-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NC7LyLi3TE544P6bvQQ:-NC7LyLi3TE544P6bvQR:bpys4oj) (no related file):*
Working: Briefly (2min) looked for explicit licensing on ROS logo. Filed this for website:
https://github.com/ros-infrastructure/www.ros.org/issues/39

But found press kit, will incorporate that
https://www.ros.org/blog/media/

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform),IanTheEngineer, missing label for release notes (waiting on @IanTheEngineer, @jwnimmer-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NC7LyLi3TE544P6bvQQ:-NC7PSNeAHBAqUhp45zS:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Briefly (2min) looked for explicit licensing on ROS logo. Filed this for website:
https://github.com/ros-infrastructure/www.ros.org/issues/39

But found press kit, will incorporate that
https://www.ros.org/blog/media/

</blockquote></details>

Done.

___
___
*[`doc/third_party/images/ros.README.txt` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NC7PTLY0eyMJ9tigMDX:-NC7PTLY0eyMJ9tigMDY:b8w3m94) ([raw file](https://github.com/robotlocomotion/drake/blob/0fb3e700c3409e53e4f1b3b199ebae1b6dda521c/doc/third_party/images/ros.README.txt#L5)):*
> ```help
> https://github.com/ros-infrastructure/artwork/blob/6172606e17/orgunits/ros.svg
> 
> License is CC-NC 4.0
> ```

Not sure about CC-NC usage?

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  Thanks!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941#-:-NC85nXQB4H8qAVYz0Aq:b-e7bejd)* status: LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer, missing label for release notes (waiting on @IanTheEngineer and @jwnimmer-tri)

**Review by IanTheEngineer — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer, missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`doc/index.md` line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCAzUIh1KPnBRl-1YwF:-NCAzUIh1KPnBRl-1YwG:b17g15r) ([raw file](https://github.com/robotlocomotion/drake/blob/0fb3e700c3409e53e4f1b3b199ebae1b6dda521c/doc/index.md#L202)):*
> ```Markdown
> Native to Drake.
> 
> <h3>ROS 2 </h3>
> ```

We should check with Open Robotics on this, but the "ROS Branding Guide" states that references to ROS and ROS 2 should have the bolt pattern precede the letters "ROS" with a space and the number "2":

https://www.ros.org/imgs/ROSBrandGuide.pdf

Similarly, that guide states:
"ROS™ should have a trademark symbol the first time it appears in a creative."

Based on all of that guidance, we should probably just use the full logo incorporating "bolt" ROS 2™. Otherwise perhaps we could rework the line like the following:



_Suggestion:_
```Markdown
<h3><img src="/third_party/images/ros.svg" height="15em"/>ROS 2&trade;</h3>
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer, missing label for release notes (waiting on @IanTheEngineer)

___
*[`doc/index.md` line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCAzUIh1KPnBRl-1YwF:-NCB3_ZP0jLaDk1x1fLK:b8bedh5) ([raw file](https://github.com/robotlocomotion/drake/blob/0fb3e700c3409e53e4f1b3b199ebae1b6dda521c/doc/index.md#L202)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

We should check with Open Robotics on this, but the "ROS Branding Guide" states that references to ROS and ROS 2 should have the bolt pattern precede the letters "ROS" with a space and the number "2":

https://www.ros.org/imgs/ROSBrandGuide.pdf

Similarly, that guide states:
"ROS™ should have a trademark symbol the first time it appears in a creative."

Based on all of that guidance, we should probably just use the full logo incorporating "bolt" ROS 2™. Otherwise perhaps we could rework the line like the following:
</blockquote></details>

Good points.

FYI the Drake website infrastructure has trademark helpers already:

(1) Add the ROS information to `drake/doc/_pages/tm.md`.

(2) Use the unicode `™` (not `&trade;`) and it will be auto-hyperlinked to our https://drake.mit.edu/tm.html page.

**Comment by jwnimmer-tri** [comment]
Let's do +(release notes: feature) so that we remember to announce this support in the next (October) release notes.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRbH8Z5zS4nVvg58T8:-NCRbH8Z5zS4nVvg58T9:b-6806f6) (no related file):*
I don't like how this bloats the page length (when in 2-column layout in particular, i.e., desktop not mobile).

Perhaps "Other Languages" and "Middleware Integration" can be combined somehow?

___
___
*[`doc/third_party/images/ros.README.txt` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRc2DAEuF4U9sIpfuz:-NCRc2DAEuF4U9sIpfv-:b-77jegr) ([raw file](https://github.com/robotlocomotion/drake/blob/0fb3e700c3409e53e4f1b3b199ebae1b6dda521c/doc/third_party/images/ros.README.txt#L5)):*
> ```help
> https://github.com/ros-infrastructure/artwork/blob/6172606e17/orgunits/ros.svg
> 
> License is CC-NC 4.0
> ```

Check the `doc/third_party/README.md`.  We need to explain this license in `website_licenses.md` per our rules.

Also, one of the terms of CC-NC is that we hyperlink to the license (not just say its name).

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer, @jwnimmer-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRbH8Z5zS4nVvg58T8:-NC_ZIKKA0HzEx525xF2:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't like how this bloats the page length (when in 2-column layout in particular, i.e., desktop not mobile).

Perhaps "Other Languages" and "Middleware Integration" can be combined somehow?
</blockquote></details>

Done.

___
___
*[`doc/index.md` line 202 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCAzUIh1KPnBRl-1YwF:-NC_ZLqC7656-NGPj1za:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0fb3e700c3409e53e4f1b3b199ebae1b6dda521c/doc/index.md#L202)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Good points.

FYI the Drake website infrastructure has trademark helpers already:

(1) Add the ROS information to `drake/doc/_pages/tm.md`.

(2) Use the unicode `™` (not `&trade;`) and it will be auto-hyperlinked to our https://drake.mit.edu/tm.html page.
</blockquote></details>

Done.
___
*[`doc/third_party/images/ros.README.txt` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRc2DAEuF4U9sIpfuz:-NC_ZMpJ284AIqxt0U6R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0fb3e700c3409e53e4f1b3b199ebae1b6dda521c/doc/third_party/images/ros.README.txt#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Check the `doc/third_party/README.md`.  We need to explain this license in `website_licenses.md` per our rules.

Also, one of the terms of CC-NC is that we hyperlink to the license (not just say its name).
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941#-:-NCa16do6UPve4NmMysy:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRbH8Z5zS4nVvg58T8:-NCa0Zkx7qa_WAguDk7z:b-247ssz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still find the layout to be too florid and eat inordinately much vertical space.

I don't think we need to spoon-feed people a "programming language" vs "middleware" subsubsubheadings.  If they don't know what the thing is, then (1) it's easy to search it anyway and (2) they probably don't care about the integration in the first place.

Here's one way that looks better to me:


```
--- a/doc/index.md
+++ b/doc/index.md
@@ -180,32 +180,13 @@ The Drake developers would like to acknowledge significant support from the
 <article markdown="1">
 ## Integrations
 
-### Language Bindings
+[Python](./python_bindings.html)
 
-#### Python
+[LCM](./doxygen_cxx/namespacedrake_1_1systems_1_1lcm.html)
 
-<a href="/python_bindings.html">
-  <img src="/third_party/images/python-logo-generic.svg" width="150px"/>
-</a>
+[ROS 2](https://github.com/RobotLocomotion/drake-ros)™ (unsupported)
 
-#### Others
-
-[Julia](./julia_bindings.html)
-
-### Middleware
-
-#### [LCM](https://lcm-proj.github.io/)
-
-Included with Drake
-
-<h4>
-  <a href="https://ros.org">
-    <img src="/third_party/images/ros.svg" height="10em"/> ROS 2™
-  </a>
-</h4>
-
-[`drake-ros`](https://github.com/RobotLocomotion/drake-ros) (separate from Drake,
-experimental)
+[Julia](./julia_bindings.html) (unsupported)
 
 </article>
 
```

If you buy this, then you can also rm the ROS logo and Python logo from git.  I find the logos to be more distracting than helpful.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 2 unresolved discussions, LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRbH8Z5zS4nVvg58T8:-NCa1ddy94--c16LyJbp:bz9i42y) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I still find the layout to be too florid and eat inordinately much vertical space.

I don't think we need to spoon-feed people a "programming language" vs "middleware" subsubsubheadings.  If they don't know what the thing is, then (1) it's easy to search it anyway and (2) they probably don't care about the integration in the first place.

Here's one way that looks better to me:


```
--- a/doc/index.md
+++ b/doc/index.md
@@ -180,32 +180,13 @@ The Drake developers would like to acknowledge significant support from the
 <article markdown="1">
 ## Integrations
 
-### Language Bindings
+[Python](./python_bindings.html)
 
-#### Python
+[LCM](./doxygen_cxx/namespacedrake_1_1systems_1_1lcm.html)
 
-<a href="/python_bindings.html">
-  <img src="/third_party/images/python-logo-generic.svg" width="150px"/>
-</a>
+[ROS 2](https://github.com/RobotLocomotion/drake-ros)™ (unsupported)
 
-#### Others
-
-[Julia](./julia_bindings.html)
-
-### Middleware
-
-#### [LCM](https://lcm-proj.github.io/)
-
-Included with Drake
-
-<h4>
-  <a href="https://ros.org">
-    <img src="/third_party/images/ros.svg" height="10em"/> ROS 2™
-  </a>
-</h4>
-
-[`drake-ros`](https://github.com/RobotLocomotion/drake-ros) (separate from Drake,
-experimental)
+[Julia](./julia_bindings.html) (unsupported)
 
 </article>
 
```

If you buy this, then you can also rm the ROS logo and Python logo from git.  I find the logos to be more distracting than helpful.
</blockquote></details>

(Possibly https://drake.mit.edu/doxygen_cxx/group__message__passing.html is a better link for "LCM" than the namespace link I provided in the patch.)

___

**Review by IanTheEngineer — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRbH8Z5zS4nVvg58T8:-NCaVBW-07ZbcPKczTT0:b-ssdf11) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(Possibly https://drake.mit.edu/doxygen_cxx/group__message__passing.html is a better link for "LCM" than the namespace link I provided in the patch.)
</blockquote></details>

I agree with Jeremy's take here. My preference would be to remove the logos all together. The blue ROS bolt pattern coupled with the Drake website's bold red letter styling seems odd. It might also go against those brand recommendations about recoloring the logo, as here the "[bolt pattern] ROS™" could be considered trying to recreate the logo. Removing the logos but keeping the text and hyperlinks is less flashy, but clearer and more concise to my eye.

___
___
*[`doc/_pages/tm.md` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCaYVcP2gEqomrTuUG-:-NCaYVcQ--1Yzsc7dBBo:b-7j4fzl) ([raw file](https://github.com/robotlocomotion/drake/blob/0f254173fb3d11384b99de9b07ae0ab8c19e4fee/doc/_pages/tm.md#L16)):*
> ```Markdown
> Note: Both "ROS 2" and "ROS2" appear in the wild, e.g.
> "ROS 2": https://www.ros.org/
> "ROS2": https://www.ros.org/imgs/ROSBrandGuide.pdf
> ```

FYI the brand guide seems to indicate a space between "ROS" and "2" as well, unless you're referring to hashtag #ROS2  .



_Code quote:_
```Markdown
"ROS2": https://www.ros.org/imgs/ROSBrandGuide.pdf
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer, @jwnimmer-tri, and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCRbH8Z5zS4nVvg58T8:-NCamxSa-_74Sl7qC-SL:bj2pzpd) (no related file):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

I agree with Jeremy's take here. My preference would be to remove the logos all together. The blue ROS bolt pattern coupled with the Drake website's bold red letter styling seems odd. It might also go against those brand recommendations about recoloring the logo, as here the "[bolt pattern] ROS™" could be considered trying to recreate the logo. Removing the logos but keeping the text and hyperlinks is less flashy, but clearer and more concise to my eye.
</blockquote></details>

Done. Nice, fewer licenses ftw!

___
___
*[`doc/_pages/tm.md` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCaYVcP2gEqomrTuUG-:-NCaZtuG65NauXPJuEJe:bxiq1yy) ([raw file](https://github.com/robotlocomotion/drake/blob/0f254173fb3d11384b99de9b07ae0ab8c19e4fee/doc/_pages/tm.md#L16)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

FYI the brand guide seems to indicate a space between "ROS" and "2" as well, unless you're referring to hashtag #ROS2  .
</blockquote></details>

OK Ah, thanks! Missed p.1 and somehow fixated on p.11 (file names).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`doc/_pages/website_licenses.md` line 12 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCapDHC1PXyVTnJQUK7:-NCapDHDBsyOyuJPLV50:b8qlhni) ([raw file](https://github.com/robotlocomotion/drake/blob/52e5ee38874ee0906e2e09cb426f5885ef7fdfd2/doc/_pages/website_licenses.md#L12)):*
> ```Markdown
> * [`third_party/images/GitHub-Mark.README.txt`](third_party/images/GitHub-Mark.README.txt)
> * [`third_party/images/python.README.txt`](third_party/images/python.README.txt)
> * [`third_party/images/ros.README.txt`](third_party/images/ros.README.txt)
> ```

vestigial?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer and @jwnimmer-tri)

___
*[`doc/_pages/website_licenses.md` line 12 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17941#-NCapDHC1PXyVTnJQUK7:-NCaq0lp48wh7nabELjW:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/52e5ee38874ee0906e2e09cb426f5885ef7fdfd2/doc/_pages/website_licenses.md#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

vestigial?
</blockquote></details>

Done, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941)* status: LGTM missing from assignee IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by IanTheEngineer — COMMENTED** [review]
:lgtm: Thanks for the updates!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17941#-:-NCcLIy5Aj5w8soYMw1g:bi6r1b9)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Pull request merged**
