### PR TITLE
Revert "[pybind] Moves a historically flaky RenderEngine test into its own test (#14724)"

### LINKED ISSUE #14686: geometry_test:test_unimplemented_rendering fails sporadically on Mac
Calling what should be a pure virtual function(*) isn't raising an exception (sometimes). This issue seems very similar to #11424

On a local Catalina machine, I'm able to reproduce the issue with the following command:

```
bazel test --test_summary=short --runs_per_test=100 //bindings/pydrake:py/geometry_render_engine_subclass_test --test_arg=TestRenderEngineSubclass.test_unimplemented_rendering
```

EDIT(eric): Updated for #14724

It fails about 2% of the time.

Slack discussions:
https://drakedevelopers.slack.com/archives/C270MN28G/p1613504306108500
https://drakedevelopers.slack.com/archives/C270MN28G/p1612967089031600

(*) Although we're calling [PYBIND11_OVERLOAD_PURE ](https://pybind11.readthedocs.io/en/stable/reference.html#c.PYBIND11_OVERRIDE_PURE) [here](https://github.com/RobotLocomotion/drake/blob/c3e739095beff4c52b7bb9a8e239a80cb9d10428/bindings/pydrake/geometry_py.cc#L106) the [C++ function](https://github.com/RobotLocomotion/drake/blob/5b5d6aa8efbd57cbf1fc7b1fdd95d78210290668/geometry/render/render_engine.h#L403) is not actually a pure virtual function, but the desired behavior is that it should throw an exception if not implemented. See #14300.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This reverts commit 5a7203e357756229e5fc3508c5d68684750088e7 (#14724)

Closes #14686
This is a proactive solution given that the most likely fixes for pybind11 have been incorporated via #14225

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14748#-MVI6dBX2GptI2zmYRPu:-MVI6dBY0gzkNchLkjlu:b1tdzlb) (no related file):*
Working: Requires #14225

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748)* status: needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14748#-MVI6dBX2GptI2zmYRPu:-MVIZc3h1PmRqY83bqOC:b-pnpo0i) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires #14225
</blockquote></details>

Done (merged)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748)* status: needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14748#-MVI6dBX2GptI2zmYRPu:-MVIZc3h1PmRqY83bqOC:b-pnpo0i) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires #14225
</blockquote></details>

Done (merged)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews (as part of platform review), please!

+(status: single reviewer ok) 

As a note, the failure mode is that the pybind11 fixes didn't actually fix it, in which case we un-revert the PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748#-:-MVI_39M4fniBjbWpzYz:bg7flp6)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I have to make a confession:

In creating the original PR, I didn't just copy and paste the code, I fixed it. Mostly it was correcting a typo and introducing some documentation as to what the test was doing. This reversion loses that....polish.

I'll leave it up to you if this simple revert is the way we want to go.

:LGTM:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748#-:-MVIyque8XjOFnwiCZzI:b-ql1zgd)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
Lemme try out xfer'ing your polish.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748#-:-MVIzFgdBalkmH7g6sOr:b-3ejmra)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14748#-MVIzIVA8_i5XOSbR4j3:-MVIzIVA8_i5XOSbR4j4:b-tn7ds2) (no related file):*
Working: Transfer the polish!

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14748)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14748#-MVIzIVA8_i5XOSbR4j3:-MVJ-2ai8kxfziqjd02H:blflyn0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Transfer the polish!
</blockquote></details>

Done. Xfer'd everything but `np.pi` to `math.pi` change.

---

**Comment by EricCousineau-TRI** [comment]
Welcome!

**Pull request merged**
