### PR TITLE
Add CopyFrom to State and ContinuousState.

### LINKED ISSUE #4535: Issue copying state of type State<AutoDiffX>
I am attempting to do the following:

If I add the following function to ContinuousState:

```
  void SetFrom(const ContinuousState<AutoDiffXd>& other) {
    DRAKE_DEMAND(size() == other.size());
    DRAKE_DEMAND(get_generalized_position().size() ==
        other.get_generalized_position().size());
    DRAKE_DEMAND(get_generalized_velocity().size() ==
        other.get_generalized_velocity().size());
    DRAKE_DEMAND(get_misc_continuous_state().size() ==
        other.get_misc_continuous_state().size());
    state_->SetFromVector(other.CopyToVector());
  }

```
and the following function to State:
```
  void SetFrom(const State<AutoDiffXd>& other) {
    continuous_state_->SetFrom(*other.get_continuous_state());
    discrete_state_->SetFrom(*other.get_discrete_state());
    abstract_state_->CopyFrom(*other.get_abstract_state());
  }

```

I get the following syntax error when attempting to compile a Simulator<AutoDiffXd>:

```
In file included from /home/drum/drake/drake/systems/framework/continuous_state.cc:1:0:
/home/drum/drake/drake/../drake/systems/framework/continuous_state.h: In instantiation of ‘void drake::systems::ContinuousState<T>::SetFrom(const drake::systems::ContinuousState<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> > >&) [with T = double]’:
/home/drum/drake/drake/systems/framework/continuous_state.cc:6:16:   required from here
/home/drum/drake/drake/../drake/systems/framework/continuous_state.h:168:5: error: no matching function for call to ‘drake::systems::VectorBase<double>::SetFromVector(drake::VectorX<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> > >)’
     state_->SetFromVector(other.CopyToVector()); 
```

This issue will cause the Simulator<AutoDiffXd> instantiation to be disabled on the unrestricted updates PR (#4382).

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #4535.

@jwnimmer-tri for both levels of review, in the hopes we can land this before Palo Alto wakes up.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4543)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/continuous_state.h, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4543#-KZMnT3FYBltCgEeEm70:-KZMnT3H4-TqZyH3aVqj:b-r2m3et) ([raw file](https://github.com/robotlocomotion/drake/blob/4bc1fbb5acaa7481bf18cc026278552b2c9bfb75/drake/systems/framework/continuous_state.h#L152)):*
> ```objc
>   void CopyFrom(const ContinuousState<T>& other) {
>     SetFromGeneric(other);
>   }
> ```

BTW Do you want a blank line between methods?  (I don't care either way.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4543#-:-KZMnqbsKp7kXuWWyjlb:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/continuous_state.h, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4543#-KZMnT3FYBltCgEeEm70:-KZMpRqdbiaJtQ7riAPR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4bc1fbb5acaa7481bf18cc026278552b2c9bfb75/drake/systems/framework/continuous_state.h#L152)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do you want a blank line between methods?  (I don't care either way.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4543)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4543#-:-KZMpTW4gsm3Jn2xcOq-:b-wkqpq5)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4543)*

**Comment by sherm1** [comment]
Too late -- we're awake! Thanks though. :lgtm:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4543#-:-KZMr0HYVFEFXoSC3jGK:btmdwmv)*

**Pull request merged**
