### PR TITLE
Symbolic linear cost

### PR DESCRIPTION
**Pull request by hongkai-dai**
Support adding symbolic linear cost in MathematicalProgram

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4894)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 188 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbHwrZGwxFhCLZ-eMxf:-KbHwrZGwxFhCLZ-eMxg:b-iuqkgf) ([raw file](https://github.com/robotlocomotion/drake/blob/ce8799a7105e16a705ed0ab1dc3ebf4fbd856a28/drake/solvers/mathematical_program.cc#L188)):*
> ```cpp
> }
> 
> void MathematicalProgram::AddCost(const Binding<Constraint>& binding) {
> ```

I did not remove these code. For some reason when reviewable diffed the changes, it thinks I removed this code and then added it back. If the reviewer scroll down he/she will find these "deleted" code were added back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbHxHkfcJuEdtRRQaT_:b-k8t9z5)*

**Comment by soonho-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLHh3IEh2jkPAE_ft9:-KbLHh3IEh2jkPAE_ftA:b-d3c5p6) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L222)):*
> ```cpp
> void ExtractVariablesFromExpression(
>     const symbolic::Expression& e, VectorXDecisionVariable* vars,
>     unordered_map<size_t, int>* map_var_to_index) {
> ```

Suggestion: let's have `DRAKE_ASSERT(map_var_to_index.size() == vars->size());`.

---

*[drake/solvers/mathematical_program.cc, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLLZD4XQjlVG55vGTl:-KbLLZD4XQjlVG55vGTm:b6o84q9) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L243)):*
> ```cpp
>    *  combination.
>    *
>    *  \pre{1. @c coeffs is a row vector of double, whose length matches with the
> ```

Let's get rid of `1.` here. 

---

*[drake/solvers/mathematical_program.cc, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLO5lzwsueyuKfvN2I:-KbLO5lzwsueyuKfvN2J:b-tz2gy6) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L282)):*
> ```cpp
>         get_base_to_exp_map_in_multiplication(e);
>     if (map_base_to_exponent.size() == 1) {
>       for (const pair<Expression, Expression>& p : map_base_to_exponent) {
> ```

We know that this loop is executed exactly once. How about removing the `for` loop and have `const pair<Expression, Expression>& p = *map_base_to_exponent.begin();` instead?

---

*[drake/solvers/mathematical_program.cc, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLP10FWwqEHAi-c2AJ:-KbLP10FWwqEHAi-c2AK:b3wp6ix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L332)):*
> ```cpp
>   for (int i{0}; i < v.size(); ++i) {
>     const Expression& e_i{v(i)};
>     DecomposeLinearExpression(e_i, map_var_to_index, A->row(i), b->data() + i);
> ```

:-) I learned something today!

---

*[drake/solvers/mathematical_program.cc, line 370 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLQASJU1XLFGfEM-GF:-KbLQASJU1XLFGfEM-GG:b-iwxila) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L370)):*
> ```cpp
>   double constant_term;
>   DecomposeLinearExpression(e, map_var_to_index, c, &constant_term);
>   // The constant term is ignored now.
> ```

Let's have a `TODO` here?

---

*[drake/solvers/mathematical_program.cc, line 469 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLPGTAcUWCNE0Y6OlL:-KbLPGTAcUWCNE0Y6OlM:b-b35hf7) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L469)):*
> ```cpp
>           get_base_to_exp_map_in_multiplication(e_i);
>       if (map_base_to_exponent.size() == 1) {
>         for (const pair<Expression, Expression>& p : map_base_to_exponent) {
> ```

Same as above. We can replace this for-loop with `const pair<Expression, Expression>& p = *map_base_to_exponent.begin();`

---

*[drake/solvers/mathematical_program.cc, line 865 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLPh9vqhtVVhgyaY1p:-KbLPh9vqhtVVhgyaY1q:b-rq6327) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L865)):*
> ```cpp
> 
> void MathematicalProgram::SetDecisionVariableValue(const Variable& var,
>                                                    double value) {
> ```

nitpick: have `const double value`?

---

*[drake/solvers/mathematical_program.h, line 808 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLPlfHpP0NXYf5ajpr:-KbLPlfHpP0NXYf5ajps:b-ngix2) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.h#L808)):*
> ```objc
>    * Adds a linear cost term of the form c'*x.
>    * @param e A linear symbolic expression.
>    * @pre{ e is a linear expression c'*x, where each entry of x is a decision
> ```

nitpick: `@pre{ e` => `@pre{e`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLHh3IEh2jkPAE_ft9:-KbMDEwuNtSUaQC1I1KY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L222)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Suggestion: let's have `DRAKE_ASSERT(map_var_to_index.size() == vars->size());`.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLLZD4XQjlVG55vGTl:-KbMQLAj0Ux5DmtGSrIP:b2n29tu) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L243)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Let's get rid of `1.` here. 
</blockquote></details>

Sorry, why we want to do that? It is still a valid prerequisite.

---

*[drake/solvers/mathematical_program.cc, line 282 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLO5lzwsueyuKfvN2I:-KbMQtxB7PzNX2GeM-nz:b35wj2g) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L282)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We know that this loop is executed exactly once. How about removing the `for` loop and have `const pair<Expression, Expression>& p = *map_base_to_exponent.begin();` instead?
</blockquote></details>

Done. Good point.

---

*[drake/solvers/mathematical_program.cc, line 370 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLQASJU1XLFGfEM-GF:-KbMRnJA8TCJ4q0oOad_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L370)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Let's have a `TODO` here?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 469 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLPGTAcUWCNE0Y6OlL:-KbMSgfUS2Wi40O4Xaey:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L469)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Same as above. We can replace this for-loop with `const pair<Expression, Expression>& p = *map_base_to_exponent.begin();`
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 865 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLPh9vqhtVVhgyaY1p:-KbMSruVzs2wjo-64Sdc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L865)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nitpick: have `const double value`?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 808 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLPlfHpP0NXYf5ajpr:-KbMSwzq4DDHd5xCohlH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.h#L808)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nitpick: `@pre{ e` => `@pre{e`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by soonho-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/solvers/mathematical_program.cc, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLLZD4XQjlVG55vGTl:-KbMYkJiGfBdNyvh6V1R:b-p2b60c) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L243)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry, why we want to do that? It is still a valid prerequisite.
</blockquote></details>

I meant only the "1. " part since there only one precondition here now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-clang-ninga-experimental-open-source please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbMZGsgNnEN8QeTQ-_I:b3gyakx)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbMZV9S6MzsCSApyCMe:b-goi7bm)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 243 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbLLZD4XQjlVG55vGTl:-KbM_1tUIDjBrIBLXQaC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/49a7278dec0960106760cdcba7543e868deeeb46/drake/solvers/mathematical_program.cc#L243)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I meant only the "1. " part since there only one precondition here now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbM_Cl0MKuHqQ1U8FUt:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbM_J9p7t4rfJ5ucUy9:bpk00vl)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1939 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbReLCLJFpPqcStcqY9:-KbReLCLJFpPqcStcqYA:bk93keu) ([raw file](https://github.com/robotlocomotion/drake/blob/8c38a5834f3fdf5d1d27956390045fb12e2e5c09/drake/solvers/mathematical_program.h#L1939)):*
> ```objc
>    */
>   void SetDecisionVariableValue(const symbolic::Variable& var,
>                                 const double value);
> ```

Adding const before POD types passed by value is unusual.  Is there a particular reason to do so here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1939 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbReLCLJFpPqcStcqY9:-KbRgumx08tEJbfWr_TX:b8cf0sy) ([raw file](https://github.com/robotlocomotion/drake/blob/8c38a5834f3fdf5d1d27956390045fb12e2e5c09/drake/solvers/mathematical_program.h#L1939)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Adding const before POD types passed by value is unusual.  Is there a particular reason to do so here?
</blockquote></details>

No I do not have a reason, @soonho-tri suggested this, and I think there is no harm to add the const.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1939 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbReLCLJFpPqcStcqY9:-KbRh87q87-95QwBf6ZY:b-20f1si) ([raw file](https://github.com/robotlocomotion/drake/blob/8c38a5834f3fdf5d1d27956390045fb12e2e5c09/drake/solvers/mathematical_program.h#L1939)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

No I do not have a reason, @soonho-tri suggested this, and I think there is no harm to add the const.
</blockquote></details>

It's my bad. I know that it's discouraged in a header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 1939 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-KbReLCLJFpPqcStcqY9:-KbRhv6IA_L7hRCC-ERq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c38a5834f3fdf5d1d27956390045fb12e2e5c09/drake/solvers/mathematical_program.h#L1939)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It's my bad. I know that it's discouraged in a header file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbRiES92z9AjnDlPkWZ:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4894#-:-KbRtFxrF-O4iVNBzJJT:b-l70wzf)*

**Pull request merged**
