### PR TITLE
[render_vtk] Use EGL by default on Ubuntu

### LINKED ISSUE #21700: [render_vtk] Remove X server requirement
(This was split out of #21050.)

**Is your feature request related to a problem? Please describe.**

There's no real reason for an X server to be a strict requirement for this renderer. It makes it harder to deploy to headless environments for containerized environments.

**Describe the solution you'd like**

Build VTK and RenderEngineVtk with EGL support, and provide a `RenderEngineVtkParams` config option to select EGL instead of GLX.

**Describe alternatives you've considered**

Users can do `xvfb` but that does non-HW-accelerated rendering and would be a bottleneck.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This also fixes RenderEngineGltfClient to not require a DISPLAY.

Closes #21700.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OA3P-2V7AuFgnM9_djx:-OA3P-2V7AuFgnM9_djy:bbo14uu) (no related file):*
Quick drive by. You should also revisit the `ColorRenderCamera::show_window()` method documentation (`render_camera.h`). Worth indicating that by default, it won't have any effect.

___

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review, please.

> Reviewed 14 of 14 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-:-OADvayS6cGocoipq_w8:b-pq7hn8)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OA3P-2V7AuFgnM9_djx:-OADvao4--LF8yj6y7Dc:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Quick drive by. You should also revisit the `ColorRenderCamera::show_window()` method documentation (`render_camera.h`). Worth indicating that by default, it won't have any effect.
</blockquote></details>

Done.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 13 of 14 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-:-OAIOalk0Jhp75YtZ41v:bmxilld)* status: 2 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OA3P-2V7AuFgnM9_djx:-OAIMIni5J3cQ7c2g7jl:b-wmc3n4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And in the same spirit, the `CameraConfig::show_rgb` documentation probably also needs to be updated. In retrospect, that was probably the more important one as that would be the expected point at which users configure it.

___
___
*[`geometry/render/render_camera.h` line 157 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OAIMchUBRQ9BLGW5Rlv:-OAIMchUBRQ9BLGW5Rlw:brczq24) ([raw file](https://github.com/RobotLocomotion/drake/blob/57a1e3be7aead34a98fd0359c570d3d9db4f88b9/geometry/render/render_camera.h#L157)):*
BTW This feels insufficient. The implication of "all render engines" is that the behavior is differentiated via *type*. But it's more nuanced than that. How about:

> Whether or not the image is displayed depends on engine type and configuration.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-:-OAOFSsjAKOc6HwBnHaF:b-z0s7k5)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OA3P-2V7AuFgnM9_djx:-OAOFQlLBjW3SXgaG5HG:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

And in the same spirit, the `CameraConfig::show_rgb` documentation probably also needs to be updated. In retrospect, that was probably the more important one as that would be the expected point at which users configure it.
</blockquote></details>

Done.

___
___
*[`geometry/render/render_camera.h` line 157 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OAIMchUBRQ9BLGW5Rlv:-OAOFO_JEDGqdABcT8wo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/57a1e3be7aead34a98fd0359c570d3d9db4f88b9/geometry/render/render_camera.h#L157)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This feels insufficient. The implication of "all render engines" is that the behavior is differentiated via *type*. But it's more nuanced than that. How about:

> Whether or not the image is displayed depends on engine type and configuration.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/render/render_camera.h` line 158 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OAOTOLA1PtZIPvXKneQ:-OAOTOLA1PtZIPvXKneR:by9569p) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2a58e7ecba8e54780caff3337bf0ba7c34a5026/geometry/render/render_camera.h#L158)):*
> ```objc
>   /** If true, requests that the RenderEngine display the rendered image.
>   Whether or not the image is able to be displayed depends on the specific
>   render engine its configuration. */
> ```

nit; typo



_Suggestion:_
```objc
 render engine and its configuration
```
___
*[`systems/sensors/camera_config.h` line 415 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-OAOTVZh5bez9m6APHjI:-OAOTVZh5bez9m6APHjJ:b-qrf9xs) ([raw file](https://github.com/RobotLocomotion/drake/blob/f2a58e7ecba8e54780caff3337bf0ba7c34a5026/systems/sensors/camera_config.h#L415)):*
> ```objc
>    `ColorRenderCamera`, this setting applies to both images. Even when set to
>    true, whether or not the image is able to be displayed depends on the
>    specific render engine its configuration.
> ```

nit typo



_Suggestion:_
```objc
render engine and its configuration
```

**Comment by jwnimmer-tri** [comment]
Derp, +@ggould-tri is on call today, not-@rpoyner-tri.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 14 files at r1, 8 of 9 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22081#-:-OAObjr36Hv4jqSHEtJV:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
