### PR TITLE
Add linter for Python files and fix code style

### PR DESCRIPTION
**Pull request by jamiesnape**
Runs the `pycodestyle` PEP 8 code style checker on all Python source files declared in rules in a BUILD file. I almost have `pydocstyle` working too, but that would be a new PR (which would also add support for `setup.cfg` files).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5728)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@david-german-tri and +@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/BUILD, line 562 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-Kgz9lSf6vmx6LhNDeV3:-Kgz9lSf6vmx6LhNDeV4:b-cazmf7) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/drake/automotive/BUILD#L562)):*
> ```Python
> cpplint()
> 
> python_lint()
> ```

FYI _Meta_ I think this is fine, but for ongoing maintenance we should really just have a single e.g. `drake_final_rules()` at the end of every `BUILD` file by rote no matter its contents, and that macro should delegate to the language-specific lint macros or whatever.  But we can do a follow-up PR for that.

---

*[drake/bindings/python/pydrake/solvers/ik.py, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-KgzALIsS9gEJ2LycOr-:-KgzALIsS9gEJ2LycOr0:b-w9uybv) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/drake/bindings/python/pydrake/solvers/ik.py#L29)):*
> ```Python
>             # requirement is made, we can delete this entire class and the
>             # renamed _WorldPositionConstraint
>             # import.
> ```

BTW Should this re-wrap up to the prior line?

---

*[tools/python_lint.bzl, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-KgzAqwuhW4sD9TA8uzE:-KgzAqwuhW4sD9TA8uzF:b-a7m7dv) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/tools/python_lint.bzl#L28)):*
> ```Python
> 
>             py_labels = [
>                 src_label for src_label in src_labels if src_label.endswith(".py")
> ```

BTW >80 cols

---

*[tools/python_lint.bzl, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-KgzB1A9wur_rZCsiHGH:-KgzB1AAfSF8CB4WJC0W:bwqt5t) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/tools/python_lint.bzl#L43)):*
> ```Python
>                     args = py_locations,
>                     main = "@pycodestyle//:pycodestyle.py",
>                     srcs_version = "PY2AND3",
> ```

BTW _Meta_ for all of the uses of `PY2AND3` in this PR, have you tested this tooling with python3?  If not, I would prefer to omit it and keep the default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-:-KgzBkS6xxEWBS0xM_VG:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/BUILD, line 562 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-Kgz9lSf6vmx6LhNDeV3:-KgzEBqrJt3E_FyuTWyI:ba59294) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/drake/automotive/BUILD#L562)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ I think this is fine, but for ongoing maintenance we should really just have a single e.g. `drake_final_rules()` at the end of every `BUILD` file by rote no matter its contents, and that macro should delegate to the language-specific lint macros or whatever.  But we can do a follow-up PR for that.
</blockquote></details>

BTW I agree wholeheartedly.

---

*[tools/python_lint.bzl, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-KgzB1A9wur_rZCsiHGH:-KgzFCBrDP2c7BWJzbdI:b-t6afyb) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/tools/python_lint.bzl#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ for all of the uses of `PY2AND3` in this PR, have you tested this tooling with python3?  If not, I would prefer to omit it and keep the default.
</blockquote></details>

BTW This one definitely works with 3.x. The others, I will check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5728)*

**Comment by david-german-tri** [comment]
:lgtm: nice, thanks!

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-:-KgzQ9K4DL2VpHYQwwjm:b4mua48)*

**Comment by jamiesnape** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/python/pydrake/solvers/ik.py, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-KgzALIsS9gEJ2LycOr-:-KgzXGlhrfk3buU5r_q5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/drake/bindings/python/pydrake/solvers/ik.py#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this re-wrap up to the prior line?
</blockquote></details>

Done.

---

*[tools/python_lint.bzl, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5728#-KgzAqwuhW4sD9TA8uzE:-KgzXF4l3R5V10KcIcEv:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/2450e7d285bad539a87faa1525a8174ea326e165/tools/python_lint.bzl#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW >80 cols
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5728)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5728)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5728)*

**Comment by jwnimmer-tri** [comment]
The prior OSX build passed.

**Pull request merged**
