### PR TITLE
[plant] Add MultibodyPlant::GetDefaultPositions()

### LINKED ISSUE #19203: Missing MultibodyPlant::GetDefaultPositions()?
**Is your feature request related to a problem? Please describe.**
I would like to access the default positions in the same way that I mutate them via `SetDefaultPositions()`.

**Describe the solution you'd like**
`GetDefaultPositions()` (both full and model-instance variant) exist

**Describe alternatives you've considered**
Inverting and rewriting the `SetDefaultPositions()` logic from scratch

**Additional context**
Control involving more than one model instance / a mask set.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #19203 (at least one way)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@amcastro-tri for feature review, please!
(\cc @jwnimmer-tri @xuchenhan-tri)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-NT4PPZi1GozbySzqFvh:b-5mnc0o)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
drive-by :lgtm: you can take me either as feature as platform.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-NTKaEeCEijdReeUok8_:bnddv3x)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/plant/multibody_plant.h` line 2172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKa3qm7P1yfUC5m4QR:-NTKa3qm7P1yfUC5m4QS:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.h#L2172)):*
> ```objc
>   }
> 
>   /// Gets the default positions for the plant, which can be canged via
> ```

typo



_Code quote:_
```objc
canged
```
___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-NTKRskx7poXShjxc8z-:bj4txn9) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
> ```cpp
>         joint.default_positions();
>   }
>   for (BodyIndex i : GetFloatingBaseBodies()) {
> ```

minor This may be unnecessary. IIRC, all free bodies have a quaternion joint to world so they should have been taken care of in the previous loop?

BTW, the current tests pass with this removed.

**Review by EricCousineau-TRI — COMMENTED** [review]
I'll take it! -@amcastro-tri +@jwnimmer-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-NTKdnSp6YDg-gatiRZF:bqjag8c)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.h` line 2172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKa3qm7P1yfUC5m4QR:-NTKenxw2vIOebNPbs1V:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.h#L2172)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-NTKcoNH85ft4pypI8uy:b-lw9gte) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor This may be unnecessary. IIRC, all free bodies have a quaternion joint to world so they should have been taken care of in the previous loop?

BTW, the current tests pass with this removed.
</blockquote></details>

Hmmm... I'm a bit confused now about the joint's default state and the following:
https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.h#L5326-L5328

I tried removing the general pattern in 1ca3bcb53f, but the test failed in other ways.
I think it's because pre-Finalize `SetDefaultPositions` *must* depend on `SetDefaultFreeBodyPose`, whereas post-Finalize does not really depend on it.

I guess the question is, who do we want to win post-Finalize? `joint.default_positions()`, or `GetDefaultFreeBodyPose()`?
For backwards compat, I would assume the latter.

WDYT?
I can update the testing to better encode these expectations.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.h` line 2178 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKkNZSCKbjkHjvpJDi:-NTKkNZSCKbjkHjvpJDj:b-xmhi1i) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/multibody/plant/multibody_plant.h#L2178)):*
> ```objc
> 
>   /// Gets the default positions for the plant for a given model instance,
>   /// which can be changed via SetDefaultPositions(ModelInstanceIndex).
> ```

nit This fails to hyperlink properly in Doxygen.

Fixing the specific link is a lot of boilerplate, so probably just linking to the overload set instead of a specific function would be the best compromise.



_Suggestion:_
```objc
  /// which can be changed via SetDefaultPositions().
```
___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-NTKjw7S7wiR-UZemHK4:byiwff1) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hmmm... I'm a bit confused now about the joint's default state and the following:
https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.h#L5326-L5328

I tried removing the general pattern in 1ca3bcb53f, but the test failed in other ways.
I think it's because pre-Finalize `SetDefaultPositions` *must* depend on `SetDefaultFreeBodyPose`, whereas post-Finalize does not really depend on it.

I guess the question is, who do we want to win post-Finalize? `joint.default_positions()`, or `GetDefaultFreeBodyPose()`?
For backwards compat, I would assume the latter.

WDYT?
I can update the testing to better encode these expectations.
</blockquote></details>

To my first skim, you've identified a latent bug in the implementation.  If the member field is only used pre-finalize, then it should be commented as such and cleared out post-finalize to prevent accidental mis-use.
___
*[`multibody/plant/multibody_plant.cc` line 1327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKjeH92lVaY1CxDQrE:-NTKjeH92lVaY1CxDQrF:bi23dul) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/multibody/plant/multibody_plant.cc#L1327)):*
> ```cpp
>   VectorX<T> q(num_positions());
>   for (int i = 0; i < num_joints(); ++i) {
>     const Joint<T>& joint = get_joint(JointIndex(i));
> ```

BTW Simplify and clarify?



_Suggestion:_
```cpp
  for (JointIndex i{0}; i < num_joints(); ++i) {
    const Joint<T>& joint = get_joint(i);
```
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4059 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKijEf6YiIrna17EGa:-NTKijEgEEcO82TaIu6m:burhhmn) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/multibody/plant/test/multibody_plant_test.cc#L4059)):*
> ```cpp
> }
> 
> GTEST_TEST(MultibodyPlantTest, SetDefaultPositions) {
> ```

Somewhere in this file, we should check that the positions returned by `plant.GetDefaultPositions()` vs `plant.GetPositions(*plant.CreateDefaultContext())` are identical.  Ideally, both prior to and after any calls to `SetDefaultPositions`.
___
*[`bindings/pydrake/multibody/plant_py.cc` line 1073 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKhyCXA-3uPSikYsMO:-NTKhyCXA-3uPSikYsMP:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/bindings/pydrake/multibody/plant_py.cc#L1073)):*
> ```cpp
>             "GetDefaultPositions",
>             [](const MultibodyPlant<T>* self,
>                 multibody::ModelInstanceIndex model_instance) {
> ```

nit



_Suggestion:_
```cpp
ModelInstanceIndex
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-NTR1x8oCufrSzLlcTwd:b-3ngkjl) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> I think it's because pre-Finalize SetDefaultPositions must depend on SetDefaultFreeBodyPose, whereas post-Finalize does not really depend on it.

Not exactly. You can't call `SetDefaultPositions` pre-finalize. 

However, I think you are right that we can't remove the free body stuff just yet. If you call `SetDefaultPositions` followed up another call to `SetDefaultFreeBodyPose`, then the default positions will use the provided values in the call to `SetDefaultFreeBodyPose` instead of the call to `SetDefaultPositions`. Capturing that in the unit test would be nice.

IMO, this non-single-source-of-truth is very confusing and cumbersome, we should eliminate `X_WB_default_list` in favor of the default joint positions.
</blockquote></details>

With https://github.com/RobotLocomotion/drake/pull/19230, you should be able to apply the pattern you use in https://github.com/RobotLocomotion/drake/commit/1ca3bcb53f04e6547a82f22be97c9ef1ca8577b2 and not fail.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-NTTtuJs32LTLMC0xJ-O:bq65gvx) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With https://github.com/RobotLocomotion/drake/pull/19230, you should be able to apply the pattern you use in https://github.com/RobotLocomotion/drake/commit/1ca3bcb53f04e6547a82f22be97c9ef1ca8577b2 and not fail.
</blockquote></details>

Working: Sweet! Will await that PR passing.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-NTtG-LT1CbOC7FYAcGQ:bekxjbj) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Sweet! Will await that PR passing.
</blockquote></details>

FYI #19230 is now merged.

**Review by RussTedrake — COMMENTED** [review]
Seems like this one is extremely close to finished?  (I almost went to write it myself)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-NcvId825UJqyVonT4GY:bbfih5j)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`multibody/plant/multibody_plant.h` line 2178 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKkNZSCKbjkHjvpJDi:-Nd0poRg-zkvJ4shfZfp:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/multibody/plant/multibody_plant.h#L2178)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This fails to hyperlink properly in Doxygen.

Fixing the specific link is a lot of boilerplate, so probably just linking to the overload set instead of a specific function would be the best compromise.
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 1331 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKRskx7poXShjxc8yz:-Nd0ppwsDTTPeF98zlDf:b2zwa5) ([raw file](https://github.com/RobotLocomotion/drake/blob/a51d3c7e37bd1a99884613eb985f3970218c57ae/multibody/plant/multibody_plant.cc#L1331)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI #19230 is now merged.
</blockquote></details>

Done, thanks (and sorry for the delay!)
___
*[`multibody/plant/multibody_plant.cc` line 1327 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKjeH92lVaY1CxDQrE:-Nd0ppMY1eCIpgFytoQm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/multibody/plant/multibody_plant.cc#L1327)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Simplify and clarify?
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 4059 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKijEf6YiIrna17EGa:-Nd0psHkDOWMyM0jXhr6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/multibody/plant/test/multibody_plant_test.cc#L4059)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Somewhere in this file, we should check that the positions returned by `plant.GetDefaultPositions()` vs `plant.GetPositions(*plant.CreateDefaultContext())` are identical.  Ideally, both prior to and after any calls to `SetDefaultPositions`.
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/plant_py.cc` line 1073 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-NTKhyCXA-3uPSikYsMO:-Nd0pu435pG1ah8VXq0X:bcx4rmt) ([raw file](https://github.com/RobotLocomotion/drake/blob/75b3f974cb31bed5d4eaa2f17563783964195506/bindings/pydrake/multibody/plant_py.cc#L1073)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done (here and elsewhere)

**Review by EricCousineau-TRI — COMMENTED** [review]
Done, sorry for the delay!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-Nd0qB9MEEvLBIn9je8n:b1ixcjm)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
Before I finish up my platform review, I'll let @xuchenhan-tri cycle through feature review again.

> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-Nd17h5A2uHYQv2CIbFL:b-aojzqi)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/plant/multibody_plant.cc` line 1374 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-Nd16Xof1FH0xxPKp2yU:-Nd16Xog9Cmzn6kEY51G:b4yqrl7) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b56bc64373479508a938afda09076f126e42231/multibody/plant/multibody_plant.cc#L1374)):*
> ```cpp
> VectorX<T> MultibodyPlant<T>::GetDefaultPositions() const {
>   DRAKE_MBP_THROW_IF_NOT_FINALIZED();
>   VectorX<T> q(num_positions());
> ```

BTW How confident are we that the joints will fully cover all positions (even when users subclass their own joints and mobilizers?).



_Suggestion:_
```cpp
VectorX<T> q;
q.setConstant(num_positions(), std::numeric_limits<double>::quiet_NaN());
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`multibody/plant/multibody_plant.cc` line 1374 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-Nd16Xof1FH0xxPKp2yU:-Nd1IcYa4E9KdnXQqh1H:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b56bc64373479508a938afda09076f126e42231/multibody/plant/multibody_plant.cc#L1374)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW How confident are we that the joints will fully cover all positions (even when users subclass their own joints and mobilizers?).
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: 

> Reviewed 4 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-:-Nd1Spdz-eLwRO6KN1OD:b-37uu3f)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`multibody/plant/test/multibody_plant_test.cc` line 4253 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-Nd1D7xl5rRCOWXDIlTG:-Nd1D7xm5P68sTyErxO_:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b56bc64373479508a938afda09076f126e42231/multibody/plant/test/multibody_plant_test.cc#L4253)):*
> ```cpp
>   const double kTol = 1e-15;
> 
>   EXPECT_FALSE(CompareMatrices(plant->GetDefaultPositions(), q, kTol));\
> ```

typo?



_Suggestion:_
```cpp
EXPECT_FALSE(CompareMatrices(plant->GetDefaultPositions(), q, kTol));
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19204)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`multibody/plant/test/multibody_plant_test.cc` line 4253 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19204#-Nd1D7xl5rRCOWXDIlTG:-Nd1XGyMAtmfvbKZ6Uq5:b-emrda) ([raw file](https://github.com/RobotLocomotion/drake/blob/1b56bc64373479508a938afda09076f126e42231/multibody/plant/test/multibody_plant_test.cc#L4253)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done - oops!

**Pull request merged**
