### PR TITLE
disable explicit instantiation of inverse dynamics on autodiffxd.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
e.g. https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=428934

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5366)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@amcastro-tri for feature review since you volunteered. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5366#-:-KeAzH51Mmq3DSVLmOan:b5svyzx)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-continuous-minimal-release please
@drake-jenkins-bot mac-clang-ninja-continuous-minimal-debug please
@drake-jenkins-bot mac-clang-continuous-minimal-debug please

**Comment by soonho-tri** [comment]
@liangfok , could you check the current `master` in your local mac (need to cherry-pick #5362)? I can't reproduce this issue on my mac but apparently we have issues on Mac CIs. I guess it could be an El-Capitan-specific issue.

**Comment by liangfok** [comment]
Sure, I'm looking now.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5366#-:-KeB7J49cchgGX0-PPEF:b-g5d9sc)*

**Comment by amcastro-tri** [comment]
The changes in this PR are correct. Whether they fix the current mac builds or not they are an improvement and should definitely go in. :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5366#-:-KeB7UB4OTjf9Vhkhqoy:b-ublngf)*

**Comment by soonho-tri** [comment]
:lgtm:

But we still need a platform-review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5366#-:-KeB7wkhEHkiH2-yRXrG:bhiu13f)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/inverse_dynamics.cc, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5366#-KeB7uNH2CWU_WLnXFwY:-KeB7uNH2CWU_WLnXFwZ:bqz2z65) ([raw file](https://github.com/robotlocomotion/drake/blob/4771ceb565650009f76e242ba23c37dc62d107b9/drake/systems/controllers/inverse_dynamics.cc#L74)):*
> ```cpp
> template class InverseDynamics<double>;
> // TODO(siyuan): some linking issue on mac.
> // template class InverseDynamics<AutoDiffXd>;
> ```

BTW, in the past, I've been defected leaving commented out code in a PR. I'll leave it to the discretion of the revewers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5366)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Comment by jwnimmer-tri** [comment]
Reviewable is down, but all builds passed so I'll override-merge over the "It doesn't look like platform LGTM happened".

**Pull request merged**
