### PR TITLE
Nerf pick_and_place_scenario_1 on mac builds (for now).

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6649)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

**Comment by sammy-tri** [comment]
+@m-chaturvedi for review (assuming the experimental mac build passes)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6649#-:-KpqNYX5n50LavmMdE7M:b-n204nz)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6649#-:-Kpqe6vFzf8zXt35h0l0:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Code is in `dev` so only needs feature review; the button is green (mac passed) so I'll hit merge.

**Pull request merged**
