### PR TITLE
Improve tests for non-positive definite articulated hinge inertia matrices.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

PR# 18329 is progress towards resolution of issue #17081. 
This PR creates a GTEST fixture to streamline tests/documentation that were created in PR# 18153.  That PR changed factorization of the articulated body hinge inertia matrix from LDLT to LLT.  PR #18153 introduced exceptions and tests cases when LLT detected a non-positive definite matrix.  The fixture in this PR #18329 will also help streamline a future PR that will throws exceptions when the articulated hinge matrix is <b>near-singular</b> (but slightly positive definite).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NH7MK-fB2STw7cmEZgE:b-3ltvov)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending some minor things

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NHH1ri9-Syv8RUxFAn0:bcntfqm)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 323 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGpCyV6fCU1hJWWR06:-NHGpCyV6fCU1hJWWR07:b-e28sks) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L323)):*
> ```cpp
>   //   to world at the world origin Wo.
>   // @param[in] mA mass of link A (1ˢᵗ link in the multibody plant).
>   // @param[in] LA length of uniform-density link A.
> ```

nit: style guide requires this to begin with lower case like mA did. The fact that "l" looks like a one won't cause any confusion here. (Also for lB below)
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 342 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGpus62ipC_Sdt6IFv:-NHGpus62ipC_Sdt6IFw:b-7o1tj2) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L342)):*
> ```cpp
>     jointWA_ = AddJointToTestPlant(jointA_type_name, world_body, X_WF, *bodyA_);
> 
>     // Connect bodyB to bodyA with the designate joint type. Create a "fixed"
> ```

nit: designate -> designated (and below)
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 386 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGqLWE1HxIJFKmPkSD:-NHGqLWE1HxIJFKmPkSE:bjeb4ii) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L386)):*
> ```cpp
>   // @note A joint_type_name of prismatic allows translation in the Fx direction
>   //   (Fx is a unit vector of the fixed_frame F). A joint_type_name of revolute
>   //   allows rotation in the Fz direction.
> ```

btw consider "about" instead of "in" here
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 428 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGzUI2EHsOYFVDH1Gc:-NHGzUI325VNgwxSv2ax:b916csn) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L428)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(plant_.EvalForwardDynamics(*context_),
>     "An internal mass matrix .+ body world to body bodyA "
>     "is not positive-definite. .+ allows translation,[^]*");
> ```

`[^]` does not appear to be a legal regular expression. What are you trying to match? If you want a character that matches any character including newline you can use `[\\S\\s]` (not space or space) as you did in rotation_matrix_test.cc.

I _believe_ (not 100% certain) the pattern as written is interpreted as `[^ab]` where a=] and b=*, that is, a character that is not a right bracket or an asterisk. (There is not closing bracket but it may be assumed.)

**Review by mitiguy — COMMENTED** [review]
PTAL -- there is one blocking comment.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NIZyJrT8J6J3bWbwJWF:bc3oz4q)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 323 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGpCyV6fCU1hJWWR06:-NIZaAesC9kLGIfP7smU:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L323)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: style guide requires this to begin with lower case like mA did. The fact that "l" looks like a one won't cause any confusion here. (Also for lB below)
</blockquote></details>

Done here and elsewhere.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 342 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGpus62ipC_Sdt6IFv:-NIZaQM3AaZtkmqSg2QH:b-snh328) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L342)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: designate -> designated (and below)
</blockquote></details>

Done here and elsewhere.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 386 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGqLWE1HxIJFKmPkSD:-NIZaa1ABxOW-8THmUCK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L386)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

btw consider "about" instead of "in" here
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 428 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGzUI2EHsOYFVDH1Gc:-NIZaoa-EbHiljfdT2J6:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L428)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

`[^]` does not appear to be a legal regular expression. What are you trying to match? If you want a character that matches any character including newline you can use `[\\S\\s]` (not space or space) as you did in rotation_matrix_test.cc.

I _believe_ (not 100% certain) the pattern as written is interpreted as `[^ab]` where a=] and b=*, that is, a character that is not a right bracket or an asterisk. (There is not closing bracket but it may be assumed.)
</blockquote></details>

OK.

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation, please

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NIcQGUPC34ZMEyRVJhx:b-64fgp2)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 428 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NHGzUI2EHsOYFVDH1Gc:-NIcQ62jCBcbSZMsVZ5y:bakey3l) ([raw file](https://github.com/robotlocomotion/drake/blob/874ed6e32c96d0da1dd023d3cb1fb50578d436ed/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L428)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

My bad -- `[^]` does actually mean any character including newline

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: one defect, doc grumbling

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NIclpoqA5eQYuNi3vXi:b-ruxpkx)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 334 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NIcWeXX-usdAY2TtpRV:-NIcWeXY4WlvIJVCx-UF:bcdcfgh) ([raw file](https://github.com/robotlocomotion/drake/blob/06357e0942818241b0a205e38cb397e364b9dfc8/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L334)):*
> ```cpp
>                  const std::string* jointB_type_name = nullptr,
>                  const double mB = 0, const double lB = 0,
>                  const std::string* jointC_type_name = nullptr,
> ```

These blahC parameters are not documented above. Consider maybe skipping the repetitive `@param` enumeration and just writing down the three properties and explain that they repeat for bodies A, B, and C.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 355 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NIcgdov1yZ58dDSXSnc:-NIcgdov1yZ58dDSXSnd:b-427rff) ([raw file](https://github.com/robotlocomotion/drake/blob/06357e0942818241b0a205e38cb397e364b9dfc8/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L355)):*
> ```cpp
>       bodyC_ = &AddCubicalLink(&plant_, "bodyC", mC, lC);
>       const RigidTransform<double> X_BF(Vector3<double>(lB, 0, 0));
>       jointBC_ = AddJointToTestPlant(*jointB_type_name, *bodyB_, X_BF, *bodyC_);
> ```

Shouldn't this line be using `jointC_type_name`?

FWIW, this kind of code (named variables for sequence instead of say, std::vector) is error-prone in exactly this way. I even tried rewriting portions of this file -- that's how I found the defect. That said, I can see why the named bodies and joints may be didactically useful in this test.

**Review by mitiguy — COMMENTED** [review]
@rpoyner-tri   Ready for another look.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NIe6yFMC61Bdt2auLkj:bs3yu50)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 334 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NIcWeXX-usdAY2TtpRV:-NIdaOq52h5uRYK0gD7T:b-qh1v2t) ([raw file](https://github.com/robotlocomotion/drake/blob/06357e0942818241b0a205e38cb397e364b9dfc8/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L334)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

These blahC parameters are not documented above. Consider maybe skipping the repetitive `@param` enumeration and just writing down the three properties and explain that they repeat for bodies A, B, and C.
</blockquote></details>

Reworded and hoping this is Kaizen.
___
*[`multibody/plant/test/multibody_plant_forward_dynamics_test.cc` line 355 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18329#-NIcgdov1yZ58dDSXSnc:-NIdabhq2MRbaQtY2AD8:bqnf10a) ([raw file](https://github.com/robotlocomotion/drake/blob/06357e0942818241b0a205e38cb397e364b9dfc8/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L355)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Shouldn't this line be using `jointC_type_name`?

FWIW, this kind of code (named variables for sequence instead of say, std::vector) is error-prone in exactly this way. I even tried rewriting portions of this file -- that's how I found the defect. That said, I can see why the named bodies and joints may be didactically useful in this test.
</blockquote></details>

Fixed -- good catch!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18329#-:-NIgs7aFCDkAjwI4OG0E:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
