### PR TITLE
[parsing] Support drake:joint involving links in nested models

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
Closes: #20345 
+@sammy-tri (or delegate?) for feature review.
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-:-Ngz6STnC3XtD1GnZ_ne:borw13x)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1097 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-NgzD3sv3YLGkNt9T-G3:-NgzD3sv3YLGkNt9T-G4:b-mafoe5) ([raw file](https://github.com/RobotLocomotion/drake/blob/e405a1ff9ce849f06bddcfd0eed2c4ab205e1154/multibody/parsing/detail_sdf_parser.cc#L1097)):*
> ```cpp
>   // references are permitted.  See
>   // http://sdformat.org/tutorials?tut=composition#composition
>   const std::string current_model_name =
> ```

I don't think this implementation is wrong, but I'm not sure why it's a different implementation than `GetResolvedModelInstanceAndLocalName`.  Can you elaborate?  (or maybe add a comment?)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1097 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-NgzD3sv3YLGkNt9T-G3:-NgzDnhtDG8AJ-rUub61:b-6xbqtx) ([raw file](https://github.com/RobotLocomotion/drake/blob/e405a1ff9ce849f06bddcfd0eed2c4ab205e1154/multibody/parsing/detail_sdf_parser.cc#L1097)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think this implementation is wrong, but I'm not sure why it's a different implementation than `GetResolvedModelInstanceAndLocalName`.  Can you elaborate?  (or maybe add a comment?)
</blockquote></details>

Ha. I did not know about GetResolvedModelInstanceAndLocalName. Let me see about whether I can use that instead.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1097 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-NgzD3sv3YLGkNt9T-G3:-NgzGVhh-LLjtMRMtY_z:b-f0hu9r) ([raw file](https://github.com/RobotLocomotion/drake/blob/e405a1ff9ce849f06bddcfd0eed2c4ab205e1154/multibody/parsing/detail_sdf_parser.cc#L1097)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ha. I did not know about GetResolvedModelInstanceAndLocalName. Let me see about whether I can use that instead.
</blockquote></details>

Ok, I tried Get*Name instead. It "works", but in error cases it throws from mbp instead of checking inputs and issuing diagnostics. So, not only do my new tests (for error messages) then fail, but a few other existing tests do too. 

I should probably undertake to rewrite Get*Name to be more pessimistic and diagnostic issuing, but I'm maybe not going to promise to do that today.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-:-NgzHgms8mzDgrmARvVW:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1097 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-NgzD3sv3YLGkNt9T-G3:-NgzH_9X4us0OXMijVwZ:bx1u7ge) ([raw file](https://github.com/RobotLocomotion/drake/blob/e405a1ff9ce849f06bddcfd0eed2c4ab205e1154/multibody/parsing/detail_sdf_parser.cc#L1097)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ok, I tried Get*Name instead. It "works", but in error cases it throws from mbp instead of checking inputs and issuing diagnostics. So, not only do my new tests (for error messages) then fail, but a few other existing tests do too. 

I should probably undertake to rewrite Get*Name to be more pessimistic and diagnostic issuing, but I'm maybe not going to promise to do that today.
</blockquote></details>

LGTM  then.  This implementation does seem better anyway.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381)* status: needs at least two assigned reviewers

___
*[`multibody/parsing/detail_sdf_parser.cc` line 1097 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-NgzD3sv3YLGkNt9T-G3:-NgzI1ZW8II1Vi-nokjT:b-skz9r7) ([raw file](https://github.com/RobotLocomotion/drake/blob/e405a1ff9ce849f06bddcfd0eed2c4ab205e1154/multibody/parsing/detail_sdf_parser.cc#L1097)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

LGTM  then.  This implementation does seem better anyway.
</blockquote></details>

I can add a TODO at least noting the family resemblance.

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review, by schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-:-NgzJdey8Aad3_UVVmzJ:b-vwbesh)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20381#-:-NgzixWC-Q6Z9JLVznfa:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
