### PR TITLE
fix the random seed in testIKtraj and testKinCnst

### LINKED ISSUE #1418: testIKtraj and testKinCnst can timeout on the build servers
this could just be a slow test, but it could also be a crash that is reporting badly.  we need to resolve. 

http://drake005.csail.mit.edu/drake/pull-RussTedrake-win32-into-RobotLocomotion-master_20151010-2310-Continuous

<matlab_test>strcmp(error_id,'timeout') && (strcmp(test_name,'systems/plants/test/testIKtraj') || strcmp(test_name,'systems/plants/constraint/test/testKinCnst'))</matlab_test>

### PR DESCRIPTION
**Pull request by hongkai-dai**
fix #1418

### CODE REVIEW

**Comment by RussTedrake** [comment]
the matlab unit tests should not be random anymore.  (perhaps different on different platforms, but we are not generating a random seed on matlab startup anymore by default).  i'm not sure why this would have any effect?

**Comment by hongkai-dai** [comment]
@tkoolen mentions that fix the random seed solves the timeout issue in `testIK` in https://github.com/RobotLocomotion/drake/pull/1588

**Comment by RussTedrake** [comment]
Well I guess fixing it to 1 is potentially different than fixing it to whatever is the default when matlab is launched.  if that works, then I guess it’s reasonable.

**Comment by hongkai-dai** [comment]
I think although the build server fixes the random seed to a given value at the test of each unitTest call, since we are adding or deleting test scripts between each pull request, the actual random seed for `testIK` is different, depending on how many tests have run before `testIK`, that's probably why sometimes we see `testIKtraj` times out, but not always.

**Comment by RussTedrake** [comment]
That shouldn’t be how it works.  matlab uses the same initial seed every time it launches, and is launched independently for every test.  perhaps if it is close to timeout, then differences in the load on the system could cause it to go one way or the other randomly…?

**Pull request merged**
