### PR TITLE
SNOPT only IIWA IK test

### LINKED ISSUE #6026: iiwa_ik_test fails on LLVM coverage builds
```
LLVM Profile Note: Set profile file path to "default.profraw" via default setting.
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from testInverseKinematics
[ RUN      ] testInverseKinematics.SolveIkFromFk
Welding joint iiwa_joint_ee
Welding joint tool0_joint
Welding joint iiwa_joint_ee
Welding joint tool0_joint
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:55:14.553] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:55:23.588] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:55:44.889] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:56:46.912] [console] [warning] IK FAILED at max constraint relaxing iter: 11
[2017-05-04 04:56:47.769] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:58:10.468] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:58:30.121] [console] [warning] IK FAILED at max constraint relaxing iter: 11
[2017-05-04 04:58:35.364] [console] [warning] IK FAILED at max constraint relaxing iter: 11
[2017-05-04 04:58:36.167] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[2017-05-04 04:58:52.753] [console] [warning] IK FAILED at max constraint relaxing iter: 11
[2017-05-04 04:59:08.840] [console] [warning] IK FAILED at max constraint relaxing iter: 11
[2017-05-04 04:59:14.790] [console] [warning] IK FAILED at max constraint relaxing iter: 11
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:78: Failure
Value of: (pos_diff.array() <= kUpperBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:79: Failure
Value of: (pos_diff.array() >= kLowerBound.array()).all()
  Actual: false
Expected: true
/home/ubuntu/workspace/linux-clang-nightly-coverage-open-source/drake/examples/kuka_iiwa_arm/dev/test/iiwa_ik_test.cc:82: Failure
Value of: std::cos(rot_diff) + kEpsilon >= std::cos(wp.rot_tol)
  Actual: false
Expected: true
[  FAILED  ] testInverseKinematics.SolveIkFromFk (257687 ms)
[----------] 1 test from testInverseKinematics (257688 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (257688 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] testInverseKinematics.SolveIkFromFk

 1 FAILED TEST
```

https://drake-cdash.csail.mit.edu/testDetails.php?test=12298860&build=574569
https://drake-cdash.csail.mit.edu/testDetails.php?test=12296003&build=574593
https://drake-cdash.csail.mit.edu/testDetails.php?test=12301779&build=574796

### PR DESCRIPTION
**Pull request by naveenoid**
I think this might tentatively resolve #6026

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6090)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyGwyNbW40H_ehIcOr:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
you may or may not want to change the BUILD file for the bazel guys. i think you do it with the tags thing. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyI0UMOfVPKWDbnPeC:bczmy1e)*

**Comment by jamiesnape** [comment]
FYI Coverage builds on CI for Bazel are close to the top of TODO list.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyIKhysEAoQf6EEaOe:b-uf5b3g)*

**Comment by naveenoid** [comment]
added a bazel tag rule for this test. What do you guys think?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyKpExJD2dVr2WXDjY:bih5ebc)*

**Comment by siyuanfeng-tri** [comment]
well i am not seeing it.? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyMI0QnOqfs9p0Fvn1:b-q3ey28)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyOCmPYWBOdKzuzv4R:bnfp4nl)*

**Comment by naveenoid** [comment]
Will merge once CI is happy.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyOHUYFI8gXW7y8u2b:bn4te2g)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyR3KrSnZ7bGKh4Eyn:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental  please

**Comment by naveenoid** [comment]
-(status: curate commits before merging) 
Moving to squash merge

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6090#-:-KjyjeXs-wC5-ZQxB2yZ:b-sjao1d)*

**Comment by sammy-tri** [comment]
This strikes me as a very suspect change for a couple of reasons.

 * It turns off the test in all open source configurations, even those in which it was working.
 * We don't have any idea what was actually going wrong with the configuration which was failing
 * The comment in CMakeLists.txt is misleading, because it implies that (at least IPOPT) doesn't solve the problem when it actually does work except for one specific permutation of compiler and compilation options.

(I assumed above that this isn't the only open source build.  If it is some points may not be valid)

**Comment by siyuanfeng-tri** [comment]
You are correct. In the ideal case, I think disabling it for just that particular build is better. I don't know how to do that. @jamiesnape if there is an easy way for this, might be a better option. 
We can play the tolerance game, or disable everything. I picked the least effort route, since internally we all snopt, and this is dev code anyway.

**Comment by jamiesnape** [comment]
There is not an easy way at present, unfortunately.

**Comment by sammy-tri** [comment]
Do we have a guess at what's different in that build?  "coverage" sounds like the kind of thing which should be harmless.   (I apologize for not doing this research myself.)

**Comment by jamiesnape** [comment]
For coverage using Clang, no IPOPT, since `llvm-cov` has issues with `gfortran`. Memcheck builds do have IPOPT enabled, but they timeout rather than fail.

**Comment by sammy-tri** [comment]
oh!  So would it be feasible to require SNOPT or IPOPT like we do for some of the IK tests in multibody/test (and remove the misleading comment about IPOPT having issues)?

I'm not particularly surprised NLopt didn't find a solution.

The timeout issue with IPOPT on memcheck builds (is there an issue for that) is probably more-or-less an extension of #3128 (IPOPT tuning would speed up IK, I've done some trial modifications which helped).

**Pull request merged**
