### PR TITLE
Add CI coverage of pick and place test scenarios

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6577)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-Kp1Bet5XwgxD_jmQ-59:b-psw9ws)*

**Comment by naveenoid** [comment]
Only BTWs..

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpMOF3fvjHx9h85_3yn:-KpMOF3fvjHx9h85_3yo:biry5jd) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L39)):*
> ```cpp
> DEFINE_double(realtime_rate, 0.0,
>               "Rate at which to run the simulation, relative to realtime");
> DEFINE_bool(quick, false, "Run only a brief simulation and return success");
> ```

BTW: Maybe you want a comment out saying "only a brief simulation without executing the entire task and return success"

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpMQBc-Uzz7NRPvdm_Q:-KpMQBc-Uzz7NRPvdm_R:b-vmb3g5) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L21)):*
> ```cpp
> // Computes the desired end effector pose in the world frame given the object
> // pose in the world frame.
> Isometry3<double> ComputeGraspPose(const Isometry3<double>& X_WObj) {
> ```

BTW: I know this is not the intention of this PR but some minor bike-shedding - I feel this method should be called "ComputePreGraspPose" 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpMQLvdKinrv3qPsCSx:bpfj3y5)*

**Comment by naveenoid** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpMQSmXgCAtbxYEX0GY:bg7igkv)*

**Comment by sammy-tri** [comment]
+@ericcousineau-tri for platform review

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpMOF3fvjHx9h85_3yn:-KpQUHtqtg8DzFY2EdeD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L39)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Maybe you want a comment out saying "only a brief simulation without executing the entire task and return success"
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpMQBc-Uzz7NRPvdm_Q:-KpQUVS6xfyItZAXqbNV:b4jmg4k) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L21)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: I know this is not the intention of this PR but some minor bike-shedding - I feel this method should be called "ComputePreGraspPose" 
</blockquote></details>

I think it's actually the grasp pose.  When we're moving to a pregrasp position we add `kPreGraspHeightOffset` to the return value of this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpQVaWwfTZrcrdDjdon:b-6jso97)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQaDwPv7Wm7Uau9XkC:-KpQaDwQdnuR1BB30cSX:b-yrjr7z) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L121)):*
> ```Python
> pick_and_place_test(
>     name = "pick_and_place_scenario_5",
>     srcs = ["monolithic_pick_and_place_demo"],
> ```

All of these tests seem to be related to `monolithic_pick_and_place_demo` (especially given the flags).
Should `srcs` default to `["monolithic_pick_and_place_demo"]`?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQ_JbTv3Oi0fzMLCda:-KpQ_JbTv3Oi0fzMLCdb:b3lsjxj) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L86)):*
> ```cpp
> 
>   const int num_targets = 4;
>   if (FLAGS_target >= num_targets) {
> ```

Since `target` is now of type `int32`, should this also check `FLAGS_target < 0`?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 170 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQ_-NXlGcigFuHHwzu:-KpQ_-NZQb41hJ6F75at:b-wcp1m0) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L170)):*
> ```cpp
>   // further forward.  The position is right at the edge of what we
>   // can plan to, so this 4cm change does matter.
>   Eigen::Vector3d table_position(0.86, -0.36, -0.07);  // position C
> ```

nit Should this be marked as `const`?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQ_48e7LGi9LMua2ok:-KpQ_48e7LGi9LMua2ol:bqlujp1) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L174)):*
> ```cpp
>   // The offset from the top of the table to the top of the post, used for
>   // calculating the place locations in iiwa relative coordinates.
>   Eigen::Vector3d post_height_offset(0, 0, 0.26);
> ```

nit This too? (`const`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577)*

**Comment by sammy-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQaDwPv7Wm7Uau9XkC:-KpQvwIdoyWNZnzheNpT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L121)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

All of these tests seem to be related to `monolithic_pick_and_place_demo` (especially given the flags).
Should `srcs` default to `["monolithic_pick_and_place_demo"]`?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQ_JbTv3Oi0fzMLCda:-KpQuEMiPqAdq81-uIXi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L86)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Since `target` is now of type `int32`, should this also check `FLAGS_target < 0`?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 170 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQ_-NXlGcigFuHHwzu:-KpQuItV7Td13BbkUmdP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L170)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Should this be marked as `const`?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpQ_48e7LGi9LMua2ok:-KpQuKMIQLcNh4Ufu070:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc16ad272c3d22fe062b59051e5da1fffa00545/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L174)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit This too? (`const`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpRGrGNoEGEUwJNEb1f:bpqxd5f)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577)*

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri to finalize platform review, please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpRGxlkMUOuwdzq0KFn:bjk08oi)*

**Comment by ggould-tri** [comment]
:lgtm:; one nit below.

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpRHwcE0yXWUIcKYEGY:-KpRHwcE0yXWUIcKYEGZ:b-fqkyxq) ([raw file](https://github.com/robotlocomotion/drake/blob/a73c604a515e16395f3e98db47ebedbb018fc433/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L62)):*
> ```Python
>     # when #3128 is fixed.
>     tags = ["snopt"],
>    # TODO(sam.creasey) This should be target 1, but that requries
> ```

FYI odd indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpRIjmkOZcs8oOhSXkt:b6mouok)*

**Comment by sammy-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-KpRHwcE0yXWUIcKYEGY:-KpRLgbeOIwp_FlMi8BE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a73c604a515e16395f3e98db47ebedbb018fc433/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L62)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI odd indent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577)*

**Comment by sammy-tri** [comment]
@jwnimmer-tri Can I ask why you added "curate commits before merging"?  I think the current list of commits leaves a functional build at any break between them, and I've been fixing the issues in the PR by amending the individual commits as appropriate.  (I would be open to reducing the number of commits by merging some changes which are on the same file if that's desirable...   or I can just squash if you think that's the best way)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpRON3Fufr0Xflah_EI:b-y22heh)*

**Comment by jwnimmer-tri** [comment]
Apologies, I must have misread the commit history last week!  I'm more than happy to defer to authors if they think the commits are already curated.

**Comment by ggould-tri** [comment]
(FTR I also inspected the commits and decided that no curation was needed)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6577#-:-KpRPVTMic51RRzF6Y4b:bo1q2x4)*

**Pull request merged**
