### PR TITLE
Bind more of RigidBody, VisualElement, CollisionElement, and Joints

### PR DESCRIPTION
**Pull request by gizatt**
Also splits RigidBody / Collision / Joints stuff to their own files, which made resolving their various dependencies on each other easier.

@EricCousineau-TRI, maybe? (Sorry to load you with lots of stuff!)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
To @EricCousineau-TRI or else you can delegate.

**Comment by EricCousineau-TRI** [comment]
First pass done, PTAL. Thanks!

---

Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/multibody/joints_py.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4iyea3MBggqhLTtdD:-LD4iyea3MBggqhLTtdE:bj3hr9c) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/joints_py.cc#L24)):*
> ```cpp
>       m, "PrismaticJoint")
>       .def(py::init([](const std::string& name,
>                        const Eigen::Matrix4d& transform_to_parent_body,
> ```

`pydrake` actually has bindings for `Isometry3` - can you include `pydrake.util.eigen_geometry` as a Python module, and `//bindings/pydrake/util/eigen_geometry_pybind` as the C++ library?

---

*[bindings/pydrake/multibody/rigid_body_py.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jZ_wBFFL6UfSWiF9:-LD4jZ_wBFFL6UfSWiFA:b-7ktif3) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/rigid_body_py.cc#L18)):*
> ```cpp
>   py::module::import("pydrake.multibody.joints");
> 
>   py::class_<RigidBody<double> >(m, "RigidBody")
> ```

Can I ask what the motivation is for placing this in a separate file is?
If there's a good one (i.e. dependency management), I'm gung-ho for it; otherwise, would it be OK if we kept this where it is?

---

*[bindings/pydrake/multibody/shapes_py.cc, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jRpVD0po0UYQAVuc:-LD4jRpVD0po0UYQAVud:bbz22i) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/shapes_py.cc#L87)):*
> ```cpp
>          py::arg("material_in"))
>     .def(py::init([](const Geometry& geometry_in,
>                      const Eigen::Matrix4d& T_element_to_local,
> ```

Same as above; can you use the `Isometry3` bindings?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846#-:-LD4jzam5HIiUJKeGlHo:bqqdw9z)*

**Comment by gizatt** [comment]
Thanks! Sorry for the long turnaround!

---

Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/multibody/joints_py.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4iyea3MBggqhLTtdD:-LD8_eKNAlASPtLGXKoV:b-jynk8f) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/joints_py.cc#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`pydrake` actually has bindings for `Isometry3` - can you include `pydrake.util.eigen_geometry` as a Python module, and `//bindings/pydrake/util/eigen_geometry_pybind` as the C++ library?
</blockquote></details>

Done, I think -- I left the Matrix4d-supporting constructor in as a convenience.

---

*[bindings/pydrake/multibody/rigid_body_py.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jZ_wBFFL6UfSWiF9:-LD8J3wfC5iixYkNYQzr:b-1fjio8) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/rigid_body_py.cc#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can I ask what the motivation is for placing this in a separate file is?
If there's a good one (i.e. dependency management), I'm gung-ho for it; otherwise, would it be OK if we kept this where it is?
</blockquote></details>

I think I had to separate it out to prevent a dependency cycle between RBT and collision -- RBT depends on both RB and collision stuff, while collision depends on RB, so RB couldn't live alongside RBT if collision was to be in its own file (which seems a lot more natural). I'm open to other solutions, though!

---

*[bindings/pydrake/multibody/shapes_py.cc, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jRpVD0po0UYQAVuc:-LD8_r-zCLqFfCQtIdDd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/shapes_py.cc#L87)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above; can you use the `Isometry3` bindings?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846#-:-LD8_bYwDXzjY5HOFHj5:b-rnwb5j)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 9 files at r1, 4 of 5 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/multibody/joints_py.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4iyea3MBggqhLTtdD:-LD8fyWpBMISHrfmbZPk:b-ax0vfc) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/joints_py.cc#L24)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done, I think -- I left the Matrix4d-supporting constructor in as a convenience.
</blockquote></details>

I'd prefer that we not put too many custom shims, especially given the intent of the ctor.
If you'd like, I'm fine with making `Isometry3` implicitly convertible from a `np.ndarray[float, 4, 4]`, which I think is easy to teach `pybind` via something like `py::implicitly_convertible<Eigen::Matrix4<T>, Eigen::Isometry3<T>>()`.

Would you want to add this? If not, I can add it in in a separate PR or this PR (if you checked the permission-to-push box things in the PR).

---

*[bindings/pydrake/multibody/rigid_body_py.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jZ_wBFFL6UfSWiF9:-LD8gO_8-rHseyTPLWeq:b-fshgts) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/rigid_body_py.cc#L18)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I think I had to separate it out to prevent a dependency cycle between RBT and collision -- RBT depends on both RB and collision stuff, while collision depends on RB, so RB couldn't live alongside RBT if collision was to be in its own file (which seems a lot more natural). I'm open to other solutions, though!
</blockquote></details>

Gotcha. In this case, can you hide `rigid_body` as `_rigid_body`, so that people do not import from this library? You can still import symbols into `rigid_body_tree` to keep the symbols the same.

If you want, I can push a change to this branch to work this in.

---

*[bindings/pydrake/multibody/shapes_py.cc, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jRpVD0po0UYQAVuc:-LD8ghBv8LSV6DId120Z:bdi4wty) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/shapes_py.cc#L87)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Er, no change?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/multibody/joints_py.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4iyea3MBggqhLTtdD:-LDCLSGI9r_eln36iLH4:b-6f7mq6) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/joints_py.cc#L24)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

That would be great, and very convenient! I've already got that box ticked -- I'll leave it to you to put in, as I don't know exactly where the right place for it is. I've eliminated the shims I added, and one or two extras in the related code that will go away with that change.
</blockquote></details>

Done. Tests should pass now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/multibody/rigid_body_py.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4jZ_wBFFL6UfSWiF9:-LDCMNO19il_8alwdSON:bmjz4g6) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/rigid_body_py.cc#L18)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

If you could make that change, I'd really appreciate it!
</blockquote></details>

OK After looking at the structure a little more, I realize that this does keep the structure consistent with the rest of `pydrake`.

It will add some additional work when deprecating these utilities, but should be relatively small amount of overhead.
Sorry about that!

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 127 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCLwi9-SI0XTShk0eF:-LDCLwi9-SI0XTShk0eG:bt8glk0) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/rigid_body_tree_py.cc#L127)):*
> ```cpp
>          py::return_value_policy::reference)
>     .def("get_position_name", &RigidBodyTree<double>::get_position_name)
>     .def("transformPoints", [](const RigidBodyTree<double>& tree,
> ```

Hup, these look like stale carry-overs before #8845 merged in. (See Line 197)
Can you remove the stale portions of this section? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending resolution of stale stuff.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846#-:-LDCMgwSCDDaIKP33cay:bmrz1ok)*

**Comment by gizatt** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[bindings/pydrake/multibody/joints_py.cc, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LD4iyea3MBggqhLTtdD:-LDDPiI0EtwaYX0MvjOi:b-psd8pq) ([raw file](https://github.com/robotlocomotion/drake/blob/3dbf98fda2fed06b67f55cc5249e66c770d2eb25/bindings/pydrake/multibody/joints_py.cc#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Tests should pass now.
</blockquote></details>

Thanks so much!

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 127 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCLwi9-SI0XTShk0eF:-LDDLT1X1UWIxuixLeWs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/rigid_body_tree_py.cc#L127)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hup, these look like stale carry-overs before #8845 merged in. (See Line 197)
Can you remove the stale portions of this section? 
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 304 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCWm_i1t9Py7SaIb38:-LDDOlWP1BSlHB0BjUX0:b10aoem) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L304)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW While I'm all in favor of a big test that makes sure the pieces work correctly together, this monolithic test does too much -- I'm thinking *particularly* of exercising alternate constructors and then throwing out the result. That kind of thing would be better served in a dedicated unit test.

It might be worth decomposing this into different tests -- where the nitty gritty of a particular object's interface is tested independently of the integration functionality.
</blockquote></details>

I split out as much as I could -- the RBT programmatic assembly test is now pretty specifically for testing the integration part of programmatic RBT assembly.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 313 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCW97W7G8ToHj50pZo:-LDDLwx24o0RcCxm0pcz:b-svhzwu) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L313)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Why not a single line?
</blockquote></details>

This one doesn't quite fit

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 316 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCVlP8EDiD4HnG2i9x:-LDDOj0p8fMAMRm4iBBZ:b-34vmyd) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L316)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd recommend adding to the comment that the joint is unused that it *only* tests construction. (Same below...although, that would probably be better served in its *own* test.)
</blockquote></details>

See above

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 317 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCVUCzELSLVSRGBogL:-LDDKqvPCqTeTSdIW-U5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L317)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Rather than defining the name on what it isn't, perhaps what it is? e.g., `body_1_joint_np` vs `body_1_joint_isom` (or some such thing)?
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 329 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCWA_jCEem_EjR0byq:-LDDM6nG0QuJXsX6GO9F:b-nvsno2) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L329)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Why not a single line?
</blockquote></details>

Wow that one does barely fit, done.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 342 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCWVlbBDnHmVTsPFuT:-LDDMSoJBV6CcbexJxqJ:bglwfjf) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L342)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI It wasn't immediately obvious to me why this is the only object that gets constructed *only* via `np.eye(4)`. The absence of the `Isometry` version makes this seem erroneous.
</blockquote></details>

Added a test for that in `shapes_test.py`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 3 files at r6.
Review status: 9 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/multibody/test/shapes_test.py, line 55 at r6](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDDRyDXBwGe6sLmpcJW:-LDDRyDXBwGe6sLmpcJX:b-81y72c) ([raw file](https://github.com/robotlocomotion/drake/blob/866e7fe22d3ac51c174121b3f991e180305a4d1e/bindings/pydrake/multibody/test/shapes_test.py#L55)):*
> ```Python
>         visual_element_np = shapes.VisualElement(box, np.eye(4), material_in)
>         visual_element_isom = shapes.VisualElement(
>             box, Isometry3(np.eye(4)), material_in)
> ```

BTW `Isometry3.Identity()` is provided; while a few more characters, it seems like a more succinct representation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Comment by gizatt** [comment]
Review status: 8 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/multibody/test/shapes_test.py, line 55 at r6](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDDRyDXBwGe6sLmpcJW:-LDDTnXsESUWDL3u9V4Z:b-l4yggl) ([raw file](https://github.com/robotlocomotion/drake/blob/866e7fe22d3ac51c174121b3f991e180305a4d1e/bindings/pydrake/multibody/test/shapes_test.py#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW `Isometry3.Identity()` is provided; while a few more characters, it seems like a more succinct representation?
</blockquote></details>

Good idea, done

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Comment by SeanCurtis-TRI** [comment]
Great

---

Reviewed 1 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 304 at r5](https://reviewable.io/reviews/robotlocomotion/drake/8846#-LDCWm_i1t9Py7SaIb38:-LDDVruL9brw1h3CN568:b-te6jdy) ([raw file](https://github.com/robotlocomotion/drake/blob/02f4271a43d7d8ee38b53ed5c3701c7cddb6fc05/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L304)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I split out as much as I could -- the RBT programmatic assembly test is now pretty specifically for testing the integration part of programmatic RBT assembly.
</blockquote></details>

I like this -- much more to the point. Thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846#-:-LDDWLRP66lLEj9yAouG:b-87hbi0)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8846)*

**Pull request merged**
