### PR TITLE
Add the demo of using IK to do in-hand manipulation with Allegro hand

### PR DESCRIPTION
**Pull request by WenzhenYuan-TRI**
cc'ing @amcastro-tri for the help with future maintenance

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9528)

### CODE REVIEW

**Comment by WenzhenYuan-TRI** [comment]
+ @hongkai-dai for feature review please

**Comment by WenzhenYuan-TRI** [comment]
+@hongkai-dai for feature review please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Can you either push fixes for Eric's review, or else designate someone else to own getting this into master, or else close this PR?

**Comment by hongkai-dai** [comment]
Thanks for the reminder. I will take this PR and fix it later.

**Comment by hongkai-dai** [comment]
Close this PR now. It uses the old RBT IK. I will rewrite it with the new MBP IK

**Pull request closed without merging**
