### PR TITLE
Snopt handles duplicated variables.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401#-:-NIWAs6BDNrPqEtET4Ud:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Wonderful.  Thank you!  One variable naming request.  Otherwise :lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401#-:-NIXL-dp2tgCiJSBjcs2:bdwde4u)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/snopt_solver.cc` line 319 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXJRfY1lqHxsqYvlA8:-NIXJRfY1lqHxsqYvlA9:byxzedw) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/snopt_solver.cc#L319)):*
> ```cpp
>   // G_remove_duplication_ has the same length as G_w_duplicate. We add
>   // G_w_duplicate[i] to G[G_remove_duplication[i]].
>   std::vector<int> G_remove_duplication_;
> ```

Can we rename this?  G is not a matrix here, and remove_duplication_ is a verb.  Perhaps duplicate_to_G_index_map_ or var_index_to_G_index_ or something more like that?
___
*[`solvers/snopt_solver.cc` line 1271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXI0MS9-TCy3O2ES3v:-NIXI0MS9-TCy3O2ES3w:bw2bqll) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/snopt_solver.cc#L1271)):*
> ```cpp
>   for (int i = 0; i < linear_constraints_A.outerSize(); ++i) {
>     for (Eigen::SparseMatrix<double>::InnerIterator it(linear_constraints_A, i);
>          it; ++it) {
> ```

btw -- this is an improvement in that it can utilize sparse A.  but what impact (if any) does it have on possible duplicates?
___
*[`solvers/test/nonlinear_program_test.cc` line 543 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXIbzV8Gx90YEQTTYp:-NIXIbzV8Gx90YEQTTYq:bn5nfjn) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/test/nonlinear_program_test.cc#L543)):*
> ```cpp
> 
> TEST_F(DuplicatedVariableNonlinearProgram1, Test) {
>   SnoptSolver snopt_solver;
> ```

nit: Why put this here instead of snopt_solver?  (and the linear program test in snopt_solver?)
___
*[`solvers/test/optimization_examples.cc` line 917 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXJ80x91PdR2hVRF3U:-NIXJ80x91PdR2hVRF3V:b-kzwapo) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/test/optimization_examples.cc#L917)):*
> ```cpp
>                  Vector3<symbolic::Variable>(x_(0), x_(1), x_(1)));
>   prog_->AddConstraint(std::make_shared<DummyConstraint>(),
>                        Vector3<symbolic::Variable>(x_(0), x_(0), x_(1)));
> ```

btw -- nice!
___
*[`solvers/test/snopt_solver_test.cc` line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXIhRj-9alHQwoWKZM:-NIXIhRj-9alHQwoWKZN:b-7yth32) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/test/snopt_solver_test.cc#L69)):*
> ```cpp
> }
> 
> TEST_F(DuplicatedVariableLinearProgramTest1, Test) {
> ```

btw -- hoorah!  I had typed in a request for this above before seeing this. ;-)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`solvers/snopt_solver.cc` line 319 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXJRfY1lqHxsqYvlA8:-NIYEkwyCetSuGW9SZJg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/snopt_solver.cc#L319)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Can we rename this?  G is not a matrix here, and remove_duplication_ is a verb.  Perhaps duplicate_to_G_index_map_ or var_index_to_G_index_ or something more like that?
</blockquote></details>

Done.
___
*[`solvers/snopt_solver.cc` line 1271 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXI0MS9-TCy3O2ES3v:-NIYEmGa4Nbzeo8i0PVL:b-7i21nq) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/snopt_solver.cc#L1271)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- this is an improvement in that it can utilize sparse A.  but what impact (if any) does it have on possible duplicates?
</blockquote></details>

`Eigen::SparseMatrix<double>::setFromTriplets` handles the duplication. I added documentation above to make it more clear.
___
*[`solvers/test/nonlinear_program_test.cc` line 543 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18401#-NIXIbzV8Gx90YEQTTYp:-NIYF3xv8jXqvSomyqF1:bx86gwd) ([raw file](https://github.com/robotlocomotion/drake/blob/cb9b3f5a7d0dba9662c4130e9738567954af1ba1/solvers/test/nonlinear_program_test.cc#L543)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: Why put this here instead of snopt_solver?  (and the linear program test in snopt_solver?)
</blockquote></details>

All other nonlinear optimization programs are tested in this `nonlinear_program_test.cc`.  In snopt_solver_test.cc it tests the linear programs and solver-specific options (like printing the result, etc).

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401#-:-NIYGEDeE95FB7_GcsaI:b-c9pjop)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @RussTedrake and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18401#-:-NIYwOBDA_RvgSxhC8-x:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
