### PR TITLE
Fix IK C++ tests to run in out-of-source builds.

### PR DESCRIPTION
**Pull request by sammy-tri**
Also some additional cleanup while in there.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2864)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for feature review

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-:-KN8o5BGUWGZE5JPXCEn:-1973176957)*

**Comment by ggould-tri** [comment]
You have done a great service to humanity in cleaning up these messes. :lgtm_strong: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/test/testIK.cpp, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-KN8sH0EjCZZI6vI3kPr:-KN8sH0EjCZZI6vI3kPs:403565532) ([raw file](https://github.com/robotlocomotion/drake/blob/a56ad2a0e96bdc6cdadde890ab85393b1b2ac038/drake/systems/plants/test/testIK.cpp#L6)):*
> ```cpp
> #include "gtest/gtest.h"
> 
> #include "drake/Path.h"
> ```

FYI -- This scares me but I took it to slack for further discussion as nothing about it is specific to this PR.

---

*[drake/systems/plants/test/testIK.cpp, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-KN8rb1xMr9hlcP94zZj:-KN8rb1xMr9hlcP94zZk:677247605) ([raw file](https://github.com/robotlocomotion/drake/blob/f045a30bf049724caf899d7437eefbd31d1e38ce/drake/systems/plants/test/testIK.cpp#L13)):*
> ```cpp
> #include "drake/util/eigen_matrix_compare.h"
> 
> using namespace std;
> ```

Yay!

---

*[drake/systems/plants/test/testIK.cpp, line 57 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-KN8rj8lCguAbXdMFz0o:-KN8rj8lCguAbXdMFz0p:677247605) ([raw file](https://github.com/robotlocomotion/drake/blob/f045a30bf049724caf899d7437eefbd31d1e38ce/drake/systems/plants/test/testIK.cpp#L57)):*
> ```cpp
>   memcpy(mxGetPrSafe(pqsol), q_sol.data(), sizeof(double)model.num_dof);
>   matPutVariable(presultmat,"q_sol", pqsol);
>   matClose(presultmat);*/
> ```

Yay!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-:-KN8vQSBBzhXKBUE4KVO:-414536007)*

**Comment by sammy-tri** [comment]
I need a platform reviewer anyway, so +@jwnimmer-tri for that and the other question above...

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-:-KN8xSyGqMI1HTc3yB_9:-871900601)*

**Comment by jwnimmer-tri** [comment]
Which question -- the bot?  We can ignore that, its just jenkins2 whining.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-:-KN9-3HrNVRuZIPgo4Am:-1071903098)*

**Comment by sammy-tri** [comment]
I didn't realize jenkins was spewing it all over the place and didn't mean anything...   so yeah, just the normal platform review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-:-KN9-EPe73IMYmoT860x:386428310)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-KN9-oLVLUa2J1ty8cAS:-KN9-oLVLUa2J1ty8cAT:2101727773) ([raw file](https://github.com/robotlocomotion/drake/blob/f045a30bf049724caf899d7437eefbd31d1e38ce/drake/systems/plants/test/testIKtraj.cpp#L17)):*
> ```cpp
> 
>   if (!model) {
>     cerr << "ERROR: Failed to load model" << endl;
> ```

I bet this was fun.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2864#-:-KN90MfTc2S5Z6bvbkns:1417088721)*

**Pull request merged**
