### PR TITLE
Vendor gflags

### LINKED ISSUE #17831: Use source build of gflags
_Edit: Original issue title was **[wheel] Use host OS build of gflags**._

In our [regular builds](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/gflags/repository.bzl), we obtain gflags from the host operating system:

```
setup/mac/binary_distribution/Brewfile:15:brew 'gflags'
setup/ubuntu/source_distribution/packages-jammy.txt:14:libgflags-dev
setup/ubuntu/source_distribution/packages-focal.txt:14:libgflags-dev
setup/ubuntu/binary_distribution/packages-jammy.txt:14:libgflags2.2
setup/ubuntu/binary_distribution/packages-focal.txt:14:libgflags2.2
```

For some reason, in the wheel builds we recompile it from sources:

https://github.com/RobotLocomotion/drake/blob/8dff9ef0a7385c96c89d833682328807a5ebbd51/tools/wheel/image/dependencies/projects.cmake#L72-L77

None of pydrake depends on gflags, so should be no problem with needing a pic-static gflags or anything along those lines.

Using two different builds hazards possible build shear or unexpected bugs, and rebuilding gflags from source wastes time.

We should drop gflags from the wheel list of projects to rebuild, and instead just brew- or apt-install the host OS version.

(Relates tangentially to the #17231 project to unify our dependency infrastructure.)

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Vendor gflags ourselves rather than relying on the host to provide it. This ensures that we are always using the same version across wheel and non-wheel builds, and across platforms.

Fixes #17831.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18586)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please

**Comment by jwnimmer-tri** [comment]
Since Drake installs some excutable programs linked with gflags, we also need to install it's (BSD) license notice as part of our install targets.  You can cult the install rule from `tools/workspace/abseil_cpp_internal/BUILD.bazel`, adjusting for whatever `gflags` names its license files.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

For the record:

I've tested that the installed binaries use a static link of gflags, so still work fine.  (I'm pretty sure we have an automated test of this anyway, but better safe than sorry.)

I also tested that Anzu CI passes.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18586#-:-NLhH7Y32Bpf3GAYK5jE:b-hk3k10)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18586#-NLhH97b-kY3EOcNnFiU:-NLhH97b-kY3EOcNnFiV:bemxmnc) (no related file):*
nit Needs license text install; see main thread above.

___

**Comment by jwnimmer-tri** [comment]
I expect we should be able to match how our `abseil_cpp_internal` license installation does it:

https://github.com/RobotLocomotion/drake/blob/4a898b526ea405d92fac190b24b497b7c9fc4f99/tools/workspace/BUILD.bazel#L109

https://github.com/RobotLocomotion/drake/blob/4a898b526ea405d92fac190b24b497b7c9fc4f99/tools/workspace/abseil_cpp_internal/BUILD.bazel#L6

**Comment by mwoehlke-kitware** [comment]
That's what I'm doing?
```
load("@drake//tools/install:install.bzl", "install_files")
load("//tools/lint:lint.bzl", "add_lint_tests")

install_files(
    name = "install",
    dest = "share/doc/gflags",
    files = [
        "@gflags//:AUTHORS.txt",
        "@gflags//:COPYING.txt",
    ],
    allowed_externals = [
        "@gflags//:AUTHORS.txt",
        "@gflags//:COPYING.txt",
    ],
    visibility = ["//tools/workspace:__pkg__"],
)

add_lint_tests()
```
...results in the above error. (The line in `tools/workspace/BUILD.bazel` doesn't seem to have an effect.)

**Review by jwnimmer-tri — COMMENTED** [review]
> That's what I'm doing?

You didn't post any code, so how was I supposed to know?  And you mentioned `package.BUILD.bazel` which implied you were doing something other than the snippet that showed up later, which was a change to `BUILD.bazel`.

The problem with that snippet was that `AUTHORS.txt` is not exported by upstream in their `BUILD` file.  That file isn't really required for the install anyway, so skipping it and only installing `COPYING.txt` should work okay.

I've pushed the fix.

+@rpoyner-tri for platform review per schedule (tomorrow), please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18586#-:-NLvPbxE-D9m6wsQCnnD:bplz3dx)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18586#-NLhH97b-kY3EOcNnFiU:-NLvPfi8B_b_2s0xeqi2:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Needs license text install; see main thread above.
</blockquote></details>

Done.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18586#-:-NM-Oqon1Okc0fcDo6qO:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18586#-:-NM-OwYc6sIVeUPh_bMu:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
