### PR TITLE
[geometry] Make VolumeMesh from VTK specified in geometry::Mesh

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Support #17780

Predecessor: #17817
Successor: #17828

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[`geometry/proximity/make_nonconvex_mesh.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAywrtxCkbvSuo67idM:-NAywrty-upDqXiOXxg0:byir0k) ([raw file](https://github.com/robotlocomotion/drake/blob/c5736c087c5c3f62ad2ade79d14539c349acef71/geometry/proximity/make_nonconvex_mesh.h#L10)):*
> ```objc
> namespace internal {
> 
> /* Generates a tetrahedral non-convex volume mesh by reading a VTK file
> ```

BTW Drive by thought. There's nothing in this function that requires the output to be non-convex. It can be *used* to create a non-convex mesh but could just as easily create a convex one. 

Might be better to name things `vtk_to_volume_mesh.h` and `MakeVolumeMeshFromVtk`.

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820#-:-NAzfhZWBd-RThzzt5KJ:ba0k9zt)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
+@xuchenhan-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820#-:-NAzfqKXCHAANQJRnpAe:b-7t62t7)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAzhtvZ3GDt7Rc5MRNB:-NAzhtvZ3GDt7Rc5MRNC:b81h8vc) (no related file):*
+(status: do not merge) pending the prequel #17817.

___

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: 7 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[`geometry/proximity/BUILD.bazel` line 498 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIinr91F8BVLG6hXBv:-NBIinr91F8BVLG6hXBw:b1mrxo) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/BUILD.bazel#L498)):*
> ```Starlark
>     hdrs = ["make_nonconvex_mesh.h"],
>     deps = [
>         ":triangle_surface_mesh",
> ```

nit unused.
___
*[`geometry/proximity/BUILD.bazel` line 500 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIioxOCDyWKet3pYfA:-NBIioxOCDyWKet3pYfB:b1mrxo) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/BUILD.bazel#L500)):*
> ```Starlark
>         ":triangle_surface_mesh",
>         ":volume_mesh",
>         ":volume_to_surface_mesh",
> ```

nit unused.
___
*[`geometry/proximity/make_nonconvex_mesh.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAywrtxCkbvSuo67idM:-NBIcrWkExPBvk7OmVRU:b-6b37w3) ([raw file](https://github.com/robotlocomotion/drake/blob/c5736c087c5c3f62ad2ade79d14539c349acef71/geometry/proximity/make_nonconvex_mesh.h#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Drive by thought. There's nothing in this function that requires the output to be non-convex. It can be *used* to create a non-convex mesh but could just as easily create a convex one. 

Might be better to name things `vtk_to_volume_mesh.h` and `MakeVolumeMeshFromVtk`.
</blockquote></details>

+1. The word "non-convex" is a little misleading.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIepC489iEitAD9yFu:-NBIepC489iEitAD9yFv:b-hrtapt) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L19)):*
> ```cpp
>   const std::string& vtk_file_name = mesh_spec.filename();
>   VolumeMesh<double> read_mesh =
>       ReadVtkToVolumeMesh(vtk_file_name, mesh_spec.scale());
> ```

Are we concerned about the case where this mesh spec actually contains a path to a .obj file?
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIgNfo8T1h7xaWkCW8:-NBIgNfo8T1h7xaWkCW9:b-hoxq7z) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L22)):*
> ```cpp
> 
>   for (int e = 0; e < read_mesh.num_elements(); ++e) {
>     if (read_mesh.CalcTetrahedronVolume(e) < 0.) {
> ```

Should we also forbid zero volume tets? They would make deformable sim unhappy for sure. We should probably forbid it if hydro doesn't like it either.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIgpCwB42oL0K9CubX:-NBIgpCx8yYrJGGRbeMh:bvukl3s) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L24)):*
> ```cpp
>     if (read_mesh.CalcTetrahedronVolume(e) < 0.) {
>       throw std::runtime_error("MakeNonConvexVolumeMeshFromVtk: "
>                                "negative-volume tetrahedron.");
> ```

BTW, consider providing hints on how to fix this issue -- perhaps by reordering the tet indexes so that it follows our convention? (I'm actually not sure what our winding convention is).
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIh7eL-uk-TnUju6ym:-NBIh7eL-uk-TnUju6yn:b-qal3dq) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L28)):*
> ```cpp
>   }
> 
>   if constexpr (std::is_same_v<T, double>) {
> ```

nit, if we want to support autodiff, why not just template ReadVtkToVolumeMesh?
___
*[`geometry/test/non_convex_mesh.vtk` line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIiF_Q72CFcLdIJEev:-NBIiF_Q72CFcLdIJEew:b-uscgr2) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/test/non_convex_mesh.vtk#L29)):*
> ```
> 10
> ```

nit, are there conventions about leaving empty lines toward the end of vtk files? If not, consider removing these. Ditto below,

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAzhtvZ3GDt7Rc5MRNB:-NBPtgEe05Kgv7iYRMml:b-3zyime) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

+(status: do not merge) pending the prequel #17817.
</blockquote></details>

#17817 has been merged.

___
___
*[`geometry/proximity/BUILD.bazel` line 498 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIinr91F8BVLG6hXBv:-NBPb9TjEqjjsi7gczwB:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/BUILD.bazel#L498)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unused.
</blockquote></details>

Done. Thanks.
___
*[`geometry/proximity/BUILD.bazel` line 500 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIioxOCDyWKet3pYfA:-NBPbK7U3LzLITU8sYbY:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/BUILD.bazel#L500)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unused.
</blockquote></details>

Done. Thanks.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIepC489iEitAD9yFu:-NBPbp7_1hWb676ZN1uW:b4lwp4) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Are we concerned about the case where this mesh spec actually contains a path to a .obj file?
</blockquote></details>

It will throw as shown in this unit test:
https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/test/vtk_to_volume_mesh_test.cc#L76-L81

I updated the doc in `make_nonconvex_mesh.h` to clarify.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIgNfo8T1h7xaWkCW8:-NBPd7mB8XbqSgm1STf8:bqyakyp) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Should we also forbid zero volume tets? They would make deformable sim unhappy for sure. We should probably forbid it if hydro doesn't like it either.
</blockquote></details>

Done.  Change `<` to `<=` and update documentation.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIgpCwB42oL0K9CubX:-NBPeadR66JtwSKjglWC:b-4hb6k0) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, consider providing hints on how to fix this issue -- perhaps by reordering the tet indexes so that it follows our convention? (I'm actually not sure what our winding convention is).
</blockquote></details>

Done.  I added more info into the error message.

The convention is the ordering of vertices A,B,C,D should have this determinant positive.
```
      | 1 Ax Ay Az |
      | 1 Bx By Bz |
      | 1 Cx Cy Cz |
      | 1 Dx Dy Dz |
```
Equivalently, D sees A,B,C in CCW order.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIh7eL-uk-TnUju6ym:-NBPfTaB74BAn4oWbSvk:b-8yik96) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L28)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, if we want to support autodiff, why not just template ReadVtkToVolumeMesh?
</blockquote></details>

It's never clear to me that we want to. I'm just being consistent with other files in `proximity/make_*_mesh.*` for now.
___
*[`geometry/test/non_convex_mesh.vtk` line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIiF_Q72CFcLdIJEev:-NBPgJmq82ZB6Jw_zU1a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/test/non_convex_mesh.vtk#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, are there conventions about leaving empty lines toward the end of vtk files? If not, consider removing these. Ditto below,
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) since the previous PR was merged.

Two more thoughts, PTAL, thanks.

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820#-:-NBSsRM88oh9_K9HLkzS:b-289l2f)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @SeanCurtis-TRI)

___
*[`geometry/proximity/make_nonconvex_mesh.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAywrtxCkbvSuo67idM:-NBSsBV23EMV1CIKz_Y0:b-cmliux) ([raw file](https://github.com/robotlocomotion/drake/blob/c5736c087c5c3f62ad2ade79d14539c349acef71/geometry/proximity/make_nonconvex_mesh.h#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

+1. The word "non-convex" is a little misleading.
</blockquote></details>

Bumping this up to blocking in case it was overlooked.
___
*[`geometry/proximity/make_nonconvex_mesh.cc` line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBIh7eL-uk-TnUju6ym:-NBSrfhgDWk6ZG5uhG5k:b-rml7up) ([raw file](https://github.com/robotlocomotion/drake/blob/d027eeb285a2e1f1cf591128efbef4442b2d11a3/geometry/proximity/make_nonconvex_mesh.cc#L28)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

It's never clear to me that we want to. I'm just being consistent with other files in `proximity/make_*_mesh.*` for now.
</blockquote></details>

Let me clarify -- it's awkward to parse the mesh as double and convert to autodiff here. If we want to be consistent with `proximity/make_*_mesh.*`, we should allow parsing autodiff mesh in `ReadVtkToVolumeMesh` instead of performing scalar conversion here.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[`geometry/proximity/make_nonconvex_mesh.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAywrtxCkbvSuo67idM:-NBUN-R9Azg4nQXe0OOc:blt23d8) ([raw file](https://github.com/robotlocomotion/drake/blob/c5736c087c5c3f62ad2ade79d14539c349acef71/geometry/proximity/make_nonconvex_mesh.h#L10)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Bumping this up to blocking in case it was overlooked.
</blockquote></details>

Per f2f discussion, we agree to rename to `MakeVolumeMeshFromVtk`. Set to Working.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`geometry/proximity/make_nonconvex_mesh.h` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NAywrtxCkbvSuo67idM:-NBUY73b2Vuix20X4vqX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5736c087c5c3f62ad2ade79d14539c349acef71/geometry/proximity/make_nonconvex_mesh.h#L10)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Per f2f discussion, we agree to rename to `MakeVolumeMeshFromVtk`. Set to Working.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: +@ggould-tri for platform review on Monday by rotation please.

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820#-:-NBUeWqI7WWcrBZj_UUF:b-7fa0sg)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: , a couple of small items.

> Reviewed 2 of 4 files at r3, 5 of 9 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820#-:-NBmFg5T6SAtPIA92mx-:b-uh9jke)* status: 2 unresolved discussions (waiting on @DamrongGuoy)

___
*[`geometry/proximity/make_mesh_from_vtk.h` line 18 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBm6QLoCcIn5P7vjFr4:-NBm6QLoCcIn5P7vjFr5:bkopjho) ([raw file](https://github.com/robotlocomotion/drake/blob/9da8c43453d485b607229cd6dde967aa1f55e1fb/geometry/proximity/make_mesh_from_vtk.h#L18)):*
> ```objc
> 
>  @throw std::exception if a tetrahedral element has non-positive volume.
>         std::exception if the `mesh` specification refers to non-VTK file.
> ```

minor:  As I read it, this will also happen if the vtk file doesn't contain a tetmesh (`vtkUnstructuredGrid`) element?
___
*[`geometry/proximity/make_mesh_from_vtk.cc` line 36 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBmA8m46sxTt0im2aTo:-NBmA8m46sxTt0im2aTp:buj7dtp) ([raw file](https://github.com/robotlocomotion/drake/blob/9da8c43453d485b607229cd6dde967aa1f55e1fb/geometry/proximity/make_mesh_from_vtk.cc#L36)):*
> ```cpp
>     return read_mesh;
>   } else {
>     // Scalar conversion from double to T, which is supposedly AutoDiffXd.
> ```

minor:  "supposedly" sounds a lot like `static_assert` to me; can this be code rather than a comment?
(the static assertion, like the comment, will compile to zero lines of object code, so there's no cost.)



_Suggestion:_
```cpp
    static_assert(std::is_same_v<T, AutoDiffXd>);
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

___
*[`geometry/proximity/make_mesh_from_vtk.h` line 18 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBm6QLoCcIn5P7vjFr4:-NBmQNFbCKpE0CCOHxzH:bdni3e) ([raw file](https://github.com/robotlocomotion/drake/blob/9da8c43453d485b607229cd6dde967aa1f55e1fb/geometry/proximity/make_mesh_from_vtk.h#L18)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  As I read it, this will also happen if the vtk file doesn't contain a tetmesh (`vtkUnstructuredGrid`) element?
</blockquote></details>

Correct. Done. Thanks.
___
*[`geometry/proximity/make_mesh_from_vtk.cc` line 36 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17820#-NBmA8m46sxTt0im2aTo:-NBmQ_hLD4yBT6b4NmgY:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/9da8c43453d485b607229cd6dde967aa1f55e1fb/geometry/proximity/make_mesh_from_vtk.cc#L36)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  "supposedly" sounds a lot like `static_assert` to me; can this be code rather than a comment?
(the static assertion, like the comment, will compile to zero lines of object code, so there's no cost.)
</blockquote></details>

Done. Thanks!

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17820)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @DamrongGuoy)

**Pull request merged**
