### PR TITLE
Add pick-and-place configuration structs.

### PR DESCRIPTION
**Pull request by avalenzu**
These will be used in subsequent pick-and-place PRs. I've split them out into their own PR because they are not in a `dev` folder (whereas most of what will follow is).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7437)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@sammy-tri for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-:-KyWL8_64nuLnoDQz-4t:bp61js4)*

**Comment by sammy-tri** [comment]
:lgtm: +@ericcousineau-tri for platform review per rotation

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-Kyq5-FHzEXhm3aE3fSv:-Kyq5-FIFSZUGk3JZeZG:b-e0xnek) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccaf21d32aa300cb7a29acb4e3d782d6691d23f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L17)):*
> ```objc
> using TargetIndex = TypeSafeIndex<class TargetTag>;
> 
> struct OptitrackInfo {
> ```

BTW consider a struct-level doxygen comment (META throughout this file)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-:-Kyq5K-eHPdtrq2NzK0e:b-p8z0bu)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, agreeing with Sammy's comment on struct-level comments, if they are appropriate.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-KyqGtIssMia8tvHm7DW:-KyqGtItb9WNzelS3Sho:bvpd78o) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccaf21d32aa300cb7a29acb4e3d782d6691d23f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L62)):*
> ```objc
>   /// World poses of the model origin of each object in the scenario.
>   std::vector<Isometry3<double>> object_poses;
>   /// Contact parameters for the simulation.
> ```

BTW Could you use a [Member Group](https://www.stack.nl/~dimitri/doxygen/manual/grouping.html#memgroup) here?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-KyqGxFEDpjyIVHOEUr9:-KyqGxFFbq3zWHRy1pRG:b-wtizuv) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccaf21d32aa300cb7a29acb4e3d782d6691d23f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L71)):*
> ```objc
> 
> struct OptitrackConfiguration {
>   std::vector<OptitrackInfo> robot_base_optitrack_info{};
> ```

BTW No need for member declaration initialization here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-:-KyqGbADRxTWCKOUnp_d:bo5ze3k)*

**Comment by avalenzu** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-Kyq5-FHzEXhm3aE3fSv:-KyqQZguHmWiVQdFQNSQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccaf21d32aa300cb7a29acb4e3d782d6691d23f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW consider a struct-level doxygen comment (META throughout this file)
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-KyqGtIssMia8tvHm7DW:-KyqQ_SmESFA-9taiWSn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccaf21d32aa300cb7a29acb4e3d782d6691d23f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L62)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could you use a [Member Group](https://www.stack.nl/~dimitri/doxygen/manual/grouping.html#memgroup) here?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-KyqGxFEDpjyIVHOEUr9:-KyqQa9DxYnjfE0OoMZG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ccaf21d32aa300cb7a29acb4e3d782d6691d23f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h#L71)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW No need for member declaration initialization here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437)*

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-:-KyqRNcAsw8DwybWvppC:bks4c2c)*

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437#-:-KyqRzmk2Tvsj6CZXuBj:bh6gmpc)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7437)*

**Pull request merged**
