### PR TITLE
[tools] Use libibex-dev_2.7.4.20210515

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15531)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@BetsyMcPhail for feature-review, please.

**Review by BetsyMcPhail — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15531#-:-Mfri5zC7RzkfuC_mexx:bb6ywmx)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15531)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonho-tri)

**Comment by BetsyMcPhail** [comment]
:lgtm:

**Review by soonho-tri — COMMENTED** [review]
FYI, `.deb` is only used in Ubuntu and we do not need to check the mac CIs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15531#-:-MfriRMi-qkwHhBr-cV1:bge8a02)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonho-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15531#-:-MfrohU542XC53sPjeio:bmxilld)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
+@seancurtis-tri , thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15531#-:-Mfrr-tY6kF5GhpRWj2X:b726g5z)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @soonho-tri)

**Pull request merged**
