### PR TITLE
[doxygen_cxx] Fail-fast when section anchors go missing

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This prevents failure like the one induced by #15404 from reaching the website.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by sherm1 — COMMENTED** [review]
Some drive-by questions.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfEu1m1-QLsXCd8c5uG:bs4hjog)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/build.py, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtCL50wYBcHmJJ99d:-MfEtCL50wYBcHmJJ99e:b-2si288) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L108)):*
> ```Python
>     Dumps the log to the console iff in verbose mode.
>     """
>     # Throw away useless lines.
> ```

BTW I can't follow the logic here. What lines are considered useless? Maybe it would be obvious if I understood the formatting of the doxygen.log but I don't and likely other readers wouldn't either?
___
*[doc/doxygen_cxx/build.py, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfErYRXCbNT69M5ELjn:-MfErYRXCbNT69M5ELjo:bope8tq) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L110)):*
> ```Python
>     # Throw away useless lines.
>     lines = []
>     ignoring_pameters = False
> ```

nit: pameters -> parameters
___
*[doc/doxygen_cxx/build.py, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtdbpEo6NPtrG1GPI:-MfEtdbpEo6NPtrG1GPJ:b-yn1yiu) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L129)):*
> ```Python
>     errors = []
>     if not modules:
>         if "unable to resolve reference" in line:
> ```

BTW to me it looks like `line` here is undefined or just the last value of one of the for loops above it? Is that just my pygnorance?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/build.py, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtCL50wYBcHmJJ99d:-MfEwFJ-2DWMEhfs6DuK:bhxax6o) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L108)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I can't follow the logic here. What lines are considered useless? Maybe it would be obvious if I understood the formatting of the doxygen.log but I don't and likely other readers wouldn't either?
</blockquote></details>

Great point.  I will add a specific example here pasted from a real log.

The gist of the pattern will be like this:
```
warning: Here's an important point.
warning: The following parameters of some_function are not documented:
parameter foo
parameter bar
warning: Here's the next important point.
```

We want the first and last line, but not the middle three.
___
*[doc/doxygen_cxx/build.py, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtdbpEo6NPtrG1GPI:-MfEwXmg0bqWy21G6Wvl:bf5jg0z) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L129)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW to me it looks like `line` here is undefined or just the last value of one of the for loops above it? Is that just my pygnorance?
</blockquote></details>

Gah!  I made mincemeat here while debugging and rewriting.  You're right that I should be looping again here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

___
*[doc/doxygen_cxx/build.py, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtCL50wYBcHmJJ99d:-MfF-3jQ0SWAHgTTY2Xe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Great point.  I will add a specific example here pasted from a real log.

The gist of the pattern will be like this:
```
warning: Here's an important point.
warning: The following parameters of some_function are not documented:
parameter foo
parameter bar
warning: Here's the next important point.
```

We want the first and last line, but not the middle three.
</blockquote></details>

Done.
___
*[doc/doxygen_cxx/build.py, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtdbpEo6NPtrG1GPI:-MfEze4I74s8d0WuQ1cM:b-pskmzq) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Gah!  I made mincemeat here while debugging and rewriting.  You're right that I should be looping again here.
</blockquote></details>

Hah!

`drake/geometry/proximity_properties.h:141: error: unable to resolve reference to MODULE_NOT_WRITTEN_YET for \ref command`

... plus a bunch of other gripes now.

I'll check what's easy to fix, and suppress the rest.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @sherm1)

___
*[doc/doxygen_cxx/build.py, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfEtdbpEo6NPtrG1GPI:-MfF7nWc2gdGnr9g7z9X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3cfc0e7f92db63b22dca44cad7b293420b3dbdfd/doc/doxygen_cxx/build.py#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hah!

`drake/geometry/proximity_properties.h:141: error: unable to resolve reference to MODULE_NOT_WRITTEN_YET for \ref command`

... plus a bunch of other gripes now.

I'll check what's easy to fix, and suppress the rest.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: 4 unresolved discussions, LGTM missing from assignees sherm1(platform),SeanCurtis-TRI(platform),hongkai-dai (waiting on @hongkai-dai, @SeanCurtis-TRI, and @sherm1)

___
*[common/type_safe_index.h, line 15 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfOAr5K1m7teVjHpUcS:-MfOAr5K1m7teVjHpUcT:b8fh1fj) ([raw file](https://github.com/robotlocomotion/drake/blob/d913874889f4e75f8c0170be91c33c0e0f8eeb8b/common/type_safe_index.h#L15)):*
> ```objc
> 
> /// A type-safe non-negative index class.
> ///
> ```

+@SeanCurtis-TRI for feature review of this file, please.
___
*[common/trajectories/piecewise_polynomial.h, line 520 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfOBYSb7D49ohWdLWNm:-MfOBYSb7D49ohWdLWNn:bffbyi7) ([raw file](https://github.com/robotlocomotion/drake/blob/d913874889f4e75f8c0170be91c33c0e0f8eeb8b/common/trajectories/piecewise_polynomial.h#L520)):*
> ```objc
>    * @warning See warning in the @ref polynomial_warning "constructor overview"
>    *          above.
>    */
> ```

+@hongkai-dai for feature review of this file, please, per #10844.
___
*[geometry/query_object.h, line 174 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfOAxV535aw_F809mxP:-MfOAxV535aw_F809mxQ:b8fh1fj) ([raw file](https://github.com/robotlocomotion/drake/blob/d913874889f4e75f8c0170be91c33c0e0f8eeb8b/geometry/query_object.h#L174)):*
> ```objc
>    @anchor collision_queries
>    @name                Collision Queries
> ```

+@SeanCurtis-TRI for feature review of this file, please.
___
*[multibody/constraint/constraint_doxygen.h, line 320 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfGslK86wDyib2XpyuR:-MfGslK9-4EfrKHV30yt:b4ksz84) ([raw file](https://github.com/robotlocomotion/drake/blob/d913874889f4e75f8c0170be91c33c0e0f8eeb8b/multibody/constraint/constraint_doxygen.h#L320)):*
> ```objc
>     "ConstraintVelProblemData")
> */
> ```

+@sherm1 for feature review of this file, please.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: for my assignment below pending a nit.

> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfP6AAJBRKazRlLzFLf:bp0l89z)* status: 5 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @hongkai-dai, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[multibody/constraint/constraint_doxygen.h, line 324 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfP5nr6CU2IIX42cN6E:-MfP5nr6CU2IIX42cN6F:b5rhtv1) ([raw file](https://github.com/robotlocomotion/drake/blob/d913874889f4e75f8c0170be91c33c0e0f8eeb8b/multibody/constraint/constraint_doxygen.h#L324)):*
> ```objc
> @ingroup constraint_overview
> 
> (To be written. Refer to
> ```

nit: this doesn't format correctly in doxygen because the brief ends up with an unbalanced parenthesis:


I suggest just not parenthesizing here.

**Review by hongkai-dai — COMMENTED** [review]
Feature :lgtm: for my assignment below

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfTTmLAEj-Dl4dXdqfL:b-tii1sa)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri, @SeanCurtis-TRI, and @sherm1)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review of the `build.py` and `Doxygenfile_CXX` changes, please (tomorrow is fine).

+@SeanCurtis-TRI for platform review of the whole PR per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With two passing question.

> Reviewed 4 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfYBuk_5HJeLZD929Fe:b-ffrb46)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/doxygen_cxx/build.py, line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY8Gnw5aqTP7-smtjw:-MfY8Gnw5aqTP7-smtjx:b-m4i0x5) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L115)):*
> ```Python
>         # For now, don't error on broken function signatures; only error on the
>         # more important links such as section cross-references.
>         if "(" in line:
> ```

BTW For my own edification, does this logic work based on how doxygen classifies references or on our "soft" practice of adding () when we reference functions? I'm assuming the latter, because I presume that doxygen's inability to resolve a reference goes hand in hand with an inability to classify it as a function.
___
*[doc/doxygen_cxx/build.py, line 127 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY9n2f8fBwzuET317v:-MfY9n2f8fBwzuET317w:blwr286) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L127)):*
> ```Python
> 
> 
> def _postprocess_doxygen_log(modules, original_lines):
> ```

nit The significance of `modules` is not clear to me. I had to go spelunking to figure out why error messages depended on it being "not False" (in some sense). The documentation doesn't help in this regard.

I'm inferring that modules is simply a list of the modules that were built (possibly everything, possibly some subset of modules). And if no modules were built, no errors are possible.

With that inference, I'm equally unsure if the dependency on `modules` is a correctness issue or an optimization issue.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/doxygen_cxx/build.py, line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY8Gnw5aqTP7-smtjw:-MfYChQM3X3YyGT1N7H7:ba5lrcf) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L115)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW For my own edification, does this logic work based on how doxygen classifies references or on our "soft" practice of adding () when we reference functions? I'm assuming the latter, because I presume that doxygen's inability to resolve a reference goes hand in hand with an inability to classify it as a function.
</blockquote></details>

Working.

Not sure specifically.  The kind of error message seen was is always printing out what looked like a _function_ name.  I should go back and add a concrete example literal for each kind of match, in a comment.
___
*[doc/doxygen_cxx/build.py, line 127 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY9n2f8fBwzuET317v:-MfYCPbt3zMGzblRVTDk:b-mauw4r) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L127)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit The significance of `modules` is not clear to me. I had to go spelunking to figure out why error messages depended on it being "not False" (in some sense). The documentation doesn't help in this regard.

I'm inferring that modules is simply a list of the modules that were built (possibly everything, possibly some subset of modules). And if no modules were built, no errors are possible.

With that inference, I'm equally unsure if the dependency on `modules` is a correctness issue or an optimization issue.
</blockquote></details>

Working

Ah, good, I see now how this is confusing.  I'll add some more variable names and comments to explain.

The short answer is that it's a correctness issue.  If we're only building a subset of the docs, we should expect that some cross-references might be broken (since we might have omitted the section they are citing).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/doxygen_cxx/build.py, line 127 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY9n2f8fBwzuET317v:-MfYKpSi26K6VzuYOzTm:b-v7l32m) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Ah, good, I see now how this is confusing.  I'll add some more variable names and comments to explain.

The short answer is that it's a correctness issue.  If we're only building a subset of the docs, we should expect that some cross-references might be broken (since we might have omitted the section they are citing).
</blockquote></details>

In that case, that's a subtle behavioral thing that should be clearly documented. Using this feature is *only* meaningful if you build the whole of doxygen. Trying to catch your own "local" changes will not actually have the effect you hope.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri, @SeanCurtis-TRI, and @sherm1)

___
*[doc/doxygen_cxx/build.py, line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY8Gnw5aqTP7-smtjw:-MfYYRDg74v6YOniXchh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working.

Not sure specifically.  The kind of error message seen was is always printing out what looked like a _function_ name.  I should go back and add a concrete example literal for each kind of match, in a comment.
</blockquote></details>

Done.
___
*[doc/doxygen_cxx/build.py, line 127 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY9n2f8fBwzuET317v:-MfYYSZ2ENbYTDozp5zi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L127)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In that case, that's a subtle behavioral thing that should be clearly documented. Using this feature is *only* meaningful if you build the whole of doxygen. Trying to catch your own "local" changes will not actually have the effect you hope.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfYaR2u1plDKphPzcDD:b-zcjvte)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[doc/doxygen_cxx/build.py, line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY8Gnw5aqTP7-smtjw:-MfY_yde5rxW_9aga5PX:b-yncp2x) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So, this looks like the kind where an overload is being referenced but misspelled?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[doc/doxygen_cxx/build.py, line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY8Gnw5aqTP7-smtjw:-MfYajdR56DDysN8R1a5:b-katrxl) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L115)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

So, this looks like the kind where an overload is being referenced but misspelled?
</blockquote></details>

That seems accurate, yes.  For many of them, it looks like we were citing one specific overload, and then that overload got a new (defaulted) argument added, and so the cross-reference no longer resolved.

Places where we just mention `MyFunction()` without a `\ref` preceding it will not trigger this guard (because they don't even match the "unable to resolve reference" check, above).

FYI For reference, here's the present status of the full list of ignored warnings via this clause:
```
"drake/geometry/proximity/obj_to_surface_mesh.h:36: warning: unable to resolve reference to `ReadObjToSurfaceMesh(const std::string&, double)' for \\ref command"
"drake/geometry/proximity/obj_to_surface_mesh.h:36: warning: unable to resolve reference to `ReadObjToSurfaceMesh(const std::string&, double)' for \\ref command"
"drake/geometry/proximity/obj_to_surface_mesh.h:36: warning: unable to resolve reference to `ReadObjToSurfaceMesh(const std::string&, double)' for \\ref command"
"drake/geometry/geometry_state.h:323: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, ProximityProperties)' for \\ref command"
"drake/geometry/geometry_state.h:330: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, PerceptionProperties)' for \\ref command"
"drake/geometry/geometry_state.h:337: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, IllustrationProperties)' for \\ref command"
"drake/geometry/geometry_state.h:323: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, ProximityProperties)' for \\ref command"
"drake/geometry/geometry_state.h:330: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, PerceptionProperties)' for \\ref command"
"drake/geometry/geometry_state.h:337: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, IllustrationProperties)' for \\ref command"
"drake/geometry/scene_graph.h:669: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,ProximityProperties)' for \\ref command"
"drake/geometry/scene_graph.h:696: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,PerceptionProperties)' for \\ref command"
"drake/geometry/scene_graph.h:721: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,IllustrationProperties)' for \\ref command"
"drake/geometry/scene_graph.h:669: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,ProximityProperties)' for \\ref command"
"drake/geometry/scene_graph.h:696: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,PerceptionProperties)' for \\ref command"
"drake/geometry/scene_graph.h:721: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,IllustrationProperties)' for \\ref command"
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[doc/doxygen_cxx/build.py, line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15455#-MfY8Gnw5aqTP7-smtjw:-MfYdx5R1sH45N2Xd3Po:b-fz2nzg) ([raw file](https://github.com/robotlocomotion/drake/blob/ddabce217b54c4c048145f16ceb87e0819c148bd/doc/doxygen_cxx/build.py#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That seems accurate, yes.  For many of them, it looks like we were citing one specific overload, and then that overload got a new (defaulted) argument added, and so the cross-reference no longer resolved.

Places where we just mention `MyFunction()` without a `\ref` preceding it will not trigger this guard (because they don't even match the "unable to resolve reference" check, above).

FYI For reference, here's the present status of the full list of ignored warnings via this clause:
```
"drake/geometry/proximity/obj_to_surface_mesh.h:36: warning: unable to resolve reference to `ReadObjToSurfaceMesh(const std::string&, double)' for \\ref command"
"drake/geometry/proximity/obj_to_surface_mesh.h:36: warning: unable to resolve reference to `ReadObjToSurfaceMesh(const std::string&, double)' for \\ref command"
"drake/geometry/proximity/obj_to_surface_mesh.h:36: warning: unable to resolve reference to `ReadObjToSurfaceMesh(const std::string&, double)' for \\ref command"
"drake/geometry/geometry_state.h:323: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, ProximityProperties)' for \\ref command"
"drake/geometry/geometry_state.h:330: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, PerceptionProperties)' for \\ref command"
"drake/geometry/geometry_state.h:337: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, IllustrationProperties)' for \\ref command"
"drake/geometry/geometry_state.h:323: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, ProximityProperties)' for \\ref command"
"drake/geometry/geometry_state.h:330: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, PerceptionProperties)' for \\ref command"
"drake/geometry/geometry_state.h:337: warning: unable to resolve reference to `SceneGraph::AssignRole(SourceId, GeometryId, IllustrationProperties)' for \\ref command"
"drake/geometry/scene_graph.h:669: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,ProximityProperties)' for \\ref command"
"drake/geometry/scene_graph.h:696: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,PerceptionProperties)' for \\ref command"
"drake/geometry/scene_graph.h:721: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,IllustrationProperties)' for \\ref command"
"drake/geometry/scene_graph.h:669: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,ProximityProperties)' for \\ref command"
"drake/geometry/scene_graph.h:696: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,PerceptionProperties)' for \\ref command"
"drake/geometry/scene_graph.h:721: warning: unable to resolve reference to `AssignRole(SourceId,GeometryId,IllustrationProperties)' for \\ref command"
```
</blockquote></details>

Thanks for the list. I'll take a pass through and see about fixing them.

**Review by SeanCurtis-TRI — COMMENTED** [review]
@rpoyner-tri, this is apparently waiting on you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfZJuYd8KLhqUsuDnXr:bhhpyv5)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Nevermind. You're platform for tomorrow. I'd gone over it as platform today (you know how is, after a while, everything looks like pork pies.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfZK-BB-3M0zAGINVIH:bw0wl27)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 6 files at r3, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15455#-:-MfdUZkaDaAvIREu_bUv:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),sherm1(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Pull request merged**
