### PR TITLE
[workspace] Upgrade openusd_internal to latest release v24.08

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #21759

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Either @rpoyner-tri or @hong-nvidia should please take this one over, and push fix(es) to this branch for the build problems.  (Or if it's easier, open a new pull request from your own fork, to supplant this PR.)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3cwKPQ3-sbj32fhix7:-O3cwKPQ3-sbj32fhix8:b-mg89f8) (no related file):*
working:
* some patches needed adjusting
* some may go away -- still looking
* a naive `upgrade --relock` didn't quite work -- still looking

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3cwKPQ3-sbj32fhix7:-O3dJRVl0a8b6CfXKpf5:b2sa5pb) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

working:
* some patches needed adjusting
* some may go away -- still looking
* a naive `upgrade --relock` didn't quite work -- still looking
</blockquote></details>

Got things working locally. Fixes arriving here shortly.

___

**Review by rpoyner-tri — COMMENTED** [review]
Mostly fixed. Let's see how CI builds do with it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-:-O3dMXqcDM-13v4epXd7:baac84s)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3d_QfO6D1TANX6q4ej:-O3d_QfO6D1TANX6q4ek:b-ll2cdf) (no related file):*
looks like more `exported_symbols` to deal with.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3d_QfO6D1TANX6q4ej:-O3dyK8L0XJGDlu6ppBK:bxgxpr0) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

looks like more `exported_symbols` to deal with.
</blockquote></details>

symbol hiding is largely done.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+@jwnimmer-tri for 2nd pair of eyes on build and symbol hiding fixes.

> Reviewed 8 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-:-O3h9fdO9QNClBC4Q6Zs:btdcjkj)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[`tools/workspace/openusd_internal/patches/nanocolor_namespace.patch` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3hY4ZY1i2Ts3KFaoMs:-O3hY4ZY1i2Ts3KFaoMt:b-o874s6) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a93ba42698c502d1cb697fab2e4781ce52ac800/tools/workspace/openusd_internal/patches/nanocolor_namespace.patch#L1)):*
> ```Diff
> commit 2094ed9dc4cab6e5506b95740a6ed586785a079f
> ```

working: needs explanation.
___
*[`tools/workspace/openusd_internal/patches/pegtl_workaround.patch` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3hYAFs3A1vFvZoDUE2:-O3hYAFs3A1vFvZoDUE3:bm4qmjo) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a93ba42698c502d1cb697fab2e4781ce52ac800/tools/workspace/openusd_internal/patches/pegtl_workaround.patch#L1)):*
> ```Diff
> commit 5a745155fdbdd0d58c6fb2290569e11dcdd213df
> ```

working: needs explanation

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
BTW it's probably reaching time for us to upstream some of the patches we've collected?  (Probably grouped into 1-2 cohesive PRs, not each `*.patch` file one by one.)

> Reviewed 7 of 9 files at r2, 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-:-O3hfRAr-1SRcyxLAcIr:bse0j59)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[`tools/workspace/openusd_internal/patches/nanocolor_namespace.patch` line 9 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-O3hh5NnEb9skGoqhJw3:-O3hh5NnEb9skGoqhJw4:b2vde9r) ([raw file](https://github.com/RobotLocomotion/drake/blob/1148bd9d937d787589d7fa297f854f0c442a8eae/tools/workspace/openusd_internal/patches/nanocolor_namespace.patch#L9)):*
> ```Diff
> should not be.
> 
> --- pxr/base/gf/nc/nanocolor.c
> ```

Most (all?) of these cc changes seem like the wrong tactics to me.

Some of these functions changed here are dead code, so deletion or `#if 0` is the right tool for those.

Some of these functions are intended to be cc-local helpers (not declared in the header), so should be marked `static` instead of NCAPI visibility.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-:-O3hhOZ92Lu9FLOXIVXM:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri as reviewer.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-:-O3nStwt6hBUJ6HGwodg:b-rva1ks)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
> Dismissed @jwnimmer-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21768#-:-O3naXvWBLBHrb6qVx9_:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
