### PR TITLE
Add drake-specific which() command that does not use user’s PATH

### LINKED ISSUE #8456: Do not use PATH in which.bzl or when otherwise searching for executables
Proposal would be to instead only search `["/usr/bin"]` on Linux and `["/usr/local/bin", "/usr/bin"]` on Mac.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #8456.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8602)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@sammy-tri for platform review per schedule, please.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/which.bzl, line 26 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602#-LAIw13YEZEFi3xouNyP:-LAIw13YEZEFi3xouNyQ:bc0nuak) ([raw file](https://github.com/robotlocomotion/drake/blob/521d2fd4a7b217d67daad9a2d9405ee2d393470c/tools/workspace/which.bzl#L26)):*
> ```Python
>     attrs = {
>         "command": attr.string(mandatory = True),
>     },
> ```

FYI I can foresee needing `additional_search_paths = []` here in the future if there are debs that go into libexec or something, but in my survey of Anzu and related downstream code, we don't have any examples of that yet, so I am a-ok deferring an extra attr until we need it.

---

*[tools/workspace/which.bzl, line 36 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602#-LAIwhzd-OkIedxESEn7:-LAIwhzd-OkIedxESEn8:b-4ey1ng) ([raw file](https://github.com/robotlocomotion/drake/blob/521d2fd4a7b217d67daad9a2d9405ee2d393470c/tools/workspace/which.bzl#L36)):*
> ```Python
> variable is ignored.
> 
> Changes to any WORKSPACE or BUILD file will cause this rule to be re-evaluated
> ```

BTW `BUILD.bazel` for consistency (existing defect).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602#-:-LAIwmOE9I44KSzROm-j:b-zfiiwp)*

**Comment by sammy-tri** [comment]
:lgtm: (pending existing issues)

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602#-:-LAJHplLAsfcmIuJzpC5:b-u3yh2c)*

**Comment by jamiesnape** [comment]
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/which.bzl, line 26 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602#-LAIw13YEZEFi3xouNyP:-LAJd8Ih0S6CnYVu6QrU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/521d2fd4a7b217d67daad9a2d9405ee2d393470c/tools/workspace/which.bzl#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I can foresee needing `additional_search_paths = []` here in the future if there are debs that go into libexec or something, but in my survey of Anzu and related downstream code, we don't have any examples of that yet, so I am a-ok deferring an extra attr until we need it.
</blockquote></details>

Done.

---

*[tools/workspace/which.bzl, line 36 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602#-LAIwhzd-OkIedxESEn7:-LAJd8s99FL7dWrcqDLS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/521d2fd4a7b217d67daad9a2d9405ee2d393470c/tools/workspace/which.bzl#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `BUILD.bazel` for consistency (existing defect).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8602)*

**Pull request merged**
