### PR TITLE
Increase test size for dynamic_programming_test

### PR DESCRIPTION
**Pull request by soonho-tri**
/cc @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8052)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot , linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot , mac-highsierra-clang-bazel-experimental-memcheck-tsan please

**Comment by soonho-tri** [comment]
+@sammy-tri for all reviews, please (per rotation).

**Comment by RussTedrake** [comment]
totally reasonable.  thanks!

**Comment by soonho-tri** [comment]
@sammy-tri, the failure in `mac-highsierra-clang-bazel-experimental-memcheck-tsan` is not from this particular test.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8052#-:-L5EoWEL1ZYI2n0y2zY5:bdefuh5)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8052#-:-L5F1D06KQu9vE8apH96:bnfp4nl)*

**Pull request merged**
