### PR TITLE
Update URLs to drake-mirror and drake-packages S3 buckets via CloudFront

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7114)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Note that there needs a switch to be enabled on AWS, so the builds of this PR prior to merge are using the alternative URL.

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for feature and platform review.

**Comment by SeanCurtis-TRI** [comment]
Just some documentation updates.  Otherwise :LGTM:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/bitbucket.bzl, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-Kv4-5Dv_4uxv-YqBPA_:-Kv4-5DwAoLxVktrZX8q:b-usxjz) ([raw file](https://github.com/robotlocomotion/drake/blob/efbf1f008873e541c58a460b146c4bcf4f8d0a30/tools/bitbucket.bzl#L42)):*
> ```Python
>         fail("Missing strip_prefix=")
> 
>     # Packages are mirrored from Bitbucket to CloudFront backed by an S3
> ```

BTW Comment now a lie?

---

*[tools/github.bzl, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-Kv4-9gf8ZaNLzIPHEcB:-Kv4-9gf8ZaNLzIPHEcC:b-usxjz) ([raw file](https://github.com/robotlocomotion/drake/blob/efbf1f008873e541c58a460b146c4bcf4f8d0a30/tools/github.bzl#L41)):*
> ```Python
>         sha256 = "0" * 64
> 
>     # Packages are mirrored from GitHub to CloudFront backed by an S3 bucket.
> ```

BTW Comment now a lie?

---

*[tools/pypi.bzl, line 90 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-Kv4-ED2Vb6skdR4vlRP:-Kv4-ED2Vb6skdR4vlRQ:b-usxjz) ([raw file](https://github.com/robotlocomotion/drake/blob/efbf1f008873e541c58a460b146c4bcf4f8d0a30/tools/pypi.bzl#L90)):*
> ```Python
>         strip_prefix = "{0}-{1}".format(package, version)
> 
>     # Packages are mirrored from PyPI to CloudFront backed by an S3 bucket.
> ```

BTW Comment now a lie?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-:-Kv4-V8a74KJgpJYJ4pY:bow51of)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/bitbucket.bzl, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-Kv4-5Dv_4uxv-YqBPA_:-Kv4-tl1chi3GWK9g0SF:bb6ssg0) ([raw file](https://github.com/robotlocomotion/drake/blob/efbf1f008873e541c58a460b146c4bcf4f8d0a30/tools/bitbucket.bzl#L42)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Comment now a lie?
</blockquote></details>

BTW 

---

*[tools/github.bzl, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-Kv4-9gf8ZaNLzIPHEcB:-Kv404Q73v2KKQx96bHp:bnrg7oa) ([raw file](https://github.com/robotlocomotion/drake/blob/efbf1f008873e541c58a460b146c4bcf4f8d0a30/tools/github.bzl#L41)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Comment now a lie?
</blockquote></details>

BTW No, still CloudFront: ```$ ping drake-mirror.csail.mit.edu
PING d2tbce6hkathzp.cloudfront.net (13.32.240.247): 56 data bytes
64 bytes from 13.32.240.247: icmp_seq=0 ttl=246 time=39.224 ms```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7114)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tools/bitbucket.bzl, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7114#-Kv4-5Dv_4uxv-YqBPA_:-Kv44Yt9OrWWfWpx0qo3:b-gsno61) ([raw file](https://github.com/robotlocomotion/drake/blob/efbf1f008873e541c58a460b146c4bcf4f8d0a30/tools/bitbucket.bzl#L42)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW 
</blockquote></details>

BTW Still creates cognitive dissonance. A mention of the alias would prevent future people from saying, "Where da CloudFront at?"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7114)*

**Pull request merged**
