### PR TITLE
[geometry] Serve the environment map over http

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19598.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-:-NotWc0b0bdBgMdcLFgl:b-pq7hn8)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 5 files at r4, 8 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Nowj0Zq70mkKoCJAVnh:-Nowj0Zq70mkKoCJAVni:b1z2fg6) (no related file):*
Working

I'll also plan to add a FileStorage thread stress test into this PR.  That should be purely additive, though, so it's fine to review anytime.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Nowj0Zq70mkKoCJAVnh:-NoxfjNCBEL8NF_wMxmf:bb6un1j) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'll also plan to add a FileStorage thread stress test into this PR.  That should be purely additive, though, so it's fine to review anytime.
</blockquote></details>

Done

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-NoytW_40EHHpuy9q_3s:-NoytW_40EHHpuy9q_3t:b-uc0bio) (no related file):*
Working

On paper this should work in Deepnote (i.e., with the nginx proxy).  I should probably hero test it, though, before we merge.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/meshcat.cc` line 1656 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Np1iKssEvsrQjp5pDuK:-Np1tVqkE9xwksj3M88Z:bbluhsv) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd71362b8bd1c1caea26a18a8d562c25a77ad593/geometry/meshcat.cc#L1656)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The static html stores the assets in a base64 encoding. But when we host the files, we simply return the bytes. That seems...weird?
</blockquote></details>

I'm not quite sure where you're going with that.  When serving the assets over http, using base64 encoding would be unconventional.  But when embedding the assets into HTML, I don't know anything better than a `data:` URI.
___
*[`geometry/meshcat_file_storage_internal.cc` line 92 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Np1XX3M04WULg-n3bzR:-Np1xWoZChdX7kAijHSL:b4d6vpg) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd71362b8bd1c1caea26a18a8d562c25a77ad593/geometry/meshcat_file_storage_internal.cc#L92)):*
Your link says "After the destruction, the smart pointers that shared ownership ... will report a use_count() that is one less than its previous value.".

That statement is a post-condition; it does not specify an order of operations.  In fact, the order of operations are:
- use_count is decremented, reaching zero
- memory fence
- the managed object's destructor runs

The docs for `weak_ptr` are more helpful, for example here:
https://en.cppreference.com/w/cpp/memory/weak_ptr/expired

> expired() is equivalent to use_count() == 0. The destructor for the managed object may not yet have been called, but this object's destruction is imminent (or may have already happened).

However, this did make me take a more careful look, and I've pushed another fix.

In case we ever support >1 user thread doing SetObject & SetProperty calls onto a threadsafe Meshcat, the file storage had one lurking race condition.  I've fixed that now.
___
*[`geometry/meshcat_file_storage_internal.cc` line 105 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Np1cOtuD5j3wx-iGvfd:-Np1t3HX0sarL1hpCjzD:b-d8ivm6) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd71362b8bd1c1caea26a18a8d562c25a77ad593/geometry/meshcat_file_storage_internal.cc#L105)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Why don't we get a complaint about `sha256` being an unused variable? Worth replacing it with `_` to make it clear we don't care?
</blockquote></details>

Not sure why no warning, but anyway I like the idea of `_`.

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.  (Or if you've timed out, feel free to unassign.)

> Reviewed 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-:-Np293Ys7FmGYoCtFTPy:bj2h5sr)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: 3 unresolved discussions

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-NoytW_40EHHpuy9q_3s:-Np5gfiy2AmCb_jwdi7C:b5ibke9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

On paper this should work in Deepnote (i.e., with the nginx proxy).  I should probably hero test it, though, before we merge.
</blockquote></details>

Worked perfectly!

(I took the screenshot after shutting down Deepnote, thus the yellow bar.)



___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 3 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20793)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

___
*[`geometry/meshcat.cc` line 1656 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Np1iKssEvsrQjp5pDuK:-Np5wAnb3CKR4PyLL8Zu:b-icglag) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd71362b8bd1c1caea26a18a8d562c25a77ad593/geometry/meshcat.cc#L1656)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not quite sure where you're going with that.  When serving the assets over http, using base64 encoding would be unconventional.  But when embedding the assets into HTML, I don't know anything better than a `data:` URI.
</blockquote></details>

I wasn't sure either. I have some mental residue of fighting with meshcat for supporting STL files. There was, if I recall correctly, a quirk where it wasn't correctly resolving the type of the data. And the difference between a legitimate byte array and a base64 data string here tickled the part of my brain. However, it's clear in this case, that meshcat is doing the right thing.  So, this should simply be ignored.

**Comment by SeanCurtis-TRI** [comment]
One last thought -- serving files with sha names is good for all the reasons. The though occurred to me that it might be nice to combine sha with some vestige of the original name so it'd be easier to look at the browser's developer tools and account for what you're seeing. Thoughts?

**Comment by jwnimmer-tri** [comment]
In my screenshot above (https://github.com/RobotLocomotion/drake/pull/20793#pullrequestreview-1846137181), you can see `meshcat-cas-filename` appear in the response headers with the original filename.  That was the best place I could find for debugging.

I had also tried putting in the URL fragment `ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad#env_256_cornell_box.png` and while that actually _worked_ (the images fetch fine), it was nearly impossible to find the fragment in the debugger console -- in only ever appeared in a hovertip, only in firefox (IIRC), and was nearly always truncated prior to the fragment.

**Comment by jwnimmer-tri** [comment]
I considered having the URL be `cas/sha256/ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad/env_256_cornell_box.png` (and the server would just ignore any path components after the actual checksum), but then the browser could end up with multiple copies of the file saved (in cases where the basename evolved, or if multiple models share an identical texture file that has a different basename in each).  Putting it in the response header seemed like a good balance.  As we gain experience with debugging challenges, I'm happy to (re)consider more options.

**Comment by jwnimmer-tri** [comment]
*[`geometry/meshcat.cc` line 1656 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20793#-Np1iKssEvsrQjp5pDuK:-Np62aE06adtVzCHQ7Cm:bgs9hb4) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd71362b8bd1c1caea26a18a8d562c25a77ad593/geometry/meshcat.cc#L1656)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I wasn't sure either. I have some mental residue of fighting with meshcat for supporting STL files. There was, if I recall correctly, a quirk where it wasn't correctly resolving the type of the data. And the difference between a legitimate byte array and a base64 data string here tickled the part of my brain. However, it's clear in this case, that meshcat is doing the right thing.  So, this should simply be ignored.
</blockquote></details>

Ah, that's probably https://github.com/meshcat-dev/meshcat/pull/138.  That still needs attention (even if we _can_ serve STLs over http, people still may choose to send them inline in msgpack, so we should get it working again).

In terms of STL over http, we might need to be careful about mime-type, and/or make sure our javascript side converts whatever format is necessary.  (It's possible the same fix would apply to both inline STL files as well as http STL files).

**Comment by SeanCurtis-TRI** [comment]
Oh, yeah. `meshcat-cas-filename`. I'd somehow missed that.  I consider that itch scratched.

**Pull request merged**
