### PR TITLE
Remove if block from snopt BUILD file

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8249)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental-snopt-packaging please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review and local testing.

**Comment by soonho-tri** [comment]
:lgtm:

It's interesting that they allow an if-then-else 'expression' but not a statement.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8249#-:-L6rUqzoHrLOgUvacn5H:b-t01pfs)*

**Comment by soonho-tri** [comment]
Tested on :apple: and :ubuntu:.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8249#-:-L6rUzOReRblf9Rb_3nL:b-2t8ttd)*

**Comment by soonho-tri** [comment]
+@sammy-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8249#-:-L6rV2UTqvhmDv8k_Mpd:b-3ojlqy)*

**Comment by jwnimmer-tri** [comment]
@soonho-tri Did you test with TRI SNOPT 7.5?

**Comment by soonho-tri** [comment]
:lgtm_cancel: 

just realized that I'm using the MIT robotlocomotion one. let me try the TRI one.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8249#-:-L6rVjQdRzPrAeHINohy:b4rwg7q)*

**Comment by soonho-tri** [comment]
:lgtm: 

`bazel test //solvers:snopt_solver_test -c dbg --config=everything` passed on both Mac/Ubuntu with TRI SNOPT 7.5-1.4.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8249#-:-L6rYVoCFNTw67W-71gV:b-fedk59)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8249#-:-L6ryCxoYaOUIthZ_cAk:bnfp4nl)*

**Pull request merged**
