### PR TITLE
Gurobi handles duplicated variables in its linear constraints.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in #18275

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18291)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@mpetersen94 for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18291#-:-NGTjv-q-aD8_Dl1ZJiB:b3ej2ph)* status: LGTM missing from assignee mpetersen94, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
:lgtm: For the support of duplicated variables. I'm not sure I know enough about Gurobi to review the conversion to use sparse matrices for the linear constraints but it looks reasonable and passes all the tests.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18291#-:-NGXDFDu2WVxiz52lbfF:b-l0qe2n)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/gurobi_solver.cc` line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18291#-NGXD0XH5aCTLZTByxpd:-NGXD0XH5aCTLZTByxpe:blmbh1i) ([raw file](https://github.com/robotlocomotion/drake/blob/7615e23a54817395575ad0a276a6a7339547a815/solvers/gurobi_solver.cc#L402)):*
> ```cpp
>                          &cval,
>                          &A_gurobi_rows](int i, double bound, char row_sense) {
>     // Add A_row_major.row(i) * vars <= lb(i)
> ```

Should this be `<= bound` for generality?

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18291#-:-NGXTycA2-C2C1q3iCT1:b-c9pjop)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @mpetersen94 and @sammy-tri)

___
*[`solvers/gurobi_solver.cc` line 402 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18291#-NGXD0XH5aCTLZTByxpd:-NGXSHtl4BqlgQyaFvo4:bpqgy0x) ([raw file](https://github.com/robotlocomotion/drake/blob/7615e23a54817395575ad0a276a6a7339547a815/solvers/gurobi_solver.cc#L402)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Should this be `<= bound` for generality?
</blockquote></details>

Done. I removed this line, it isn't correct. And this lambda function already has the documentation on top.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18291#-:-NGY1ZKr7smMwpN7sLSK:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),mpetersen94 (waiting on @hongkai-dai)

**Pull request merged**
