### PR TITLE
Upgrade Externals September 2023

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #20108

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20148)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@EricCousineau-tri for both reviews please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20148#-:-Ndl7A9V7jR57xHCp01a:bdi1n4u)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20148#-:-NdlCoEZ7C_N7AkIgjT-:bks4n6x)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

**Comment by EricCousineau-TRI** [comment]
It OK if I defer to y'all for doing the rebased merge?

**Review by BetsyMcPhail — COMMENTED** [review]
No problem, I'll take care of the rebasing.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20148#-:-NdlRva4CRFCrVVY4Smk:bdajzkk)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-everything-release please.

**Pull request merged**
