### PR TITLE
Minor Prep Work Towards Generalizing AutomotiveSimulator To Support Multi-Body Vehicle Models.

### PR DESCRIPTION
**Pull request by liangfok**
Switched AutomotiveSimulator to use model_index_id instead of a pointer to a RigidBody. Added some comments and changed some variable names in preparation for generalization to support multi-body vehicle models.

Towards #3919.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3921)

### CODE REVIEW

**Comment by liangfok** [comment]
+@maddog-tri for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-:-KV5Y2uD1NnfGQQInChE:bbtxxez)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_tvAke9mHMLDBXTB:-KV5_tvBTVOfPBNBWh0K:b30rfv3) (no related file):*
Is there a feature branch that carries this concept forward?  This PR is very confusing on its own; this middle ground on between Boxcar world and GeometryWorld with even more obscure index math doesn't seem like a place we want to go.

---

*[drake/automotive/automotive_simulator.cc, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_DX0c_TbwFDLl8FS:-KV5_DX0c_TbwFDLl8FT:b-t65nj1) ([raw file](https://github.com/robotlocomotion/drake/blob/40202a5be00dbf04d76b5c7dc8227a3c1f0ea8e4/drake/automotive/automotive_simulator.cc#L202)):*
> ```cpp
>     // the position input to the publisher, and then also need to feed zeros
>     // for all of the joint velocities.
>     const int num_joints = rigid_body_tree_publisher_inputs_.size();
> ```

This isn't really `num_joints` anymore though, is it?  It's `num_models` or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_tvAke9mHMLDBXTB:-KV5b2tLcpsBtm9ra5i-:b579rkf) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Is there a feature branch that carries this concept forward?  This PR is very confusing on its own; this middle ground on between Boxcar world and GeometryWorld with even more obscure index math doesn't seem like a place we want to go.
</details>
I have a local feature branch that charges forward some but it's not ready to be reviewed (it's very messy).

Did I introduce index math in this PR? Are you referring to the use of `model_instance_id` instead of `Rigidbody*`? I believe this is going in the right direction because we will soon support models with more than one `RigidBody` and all of the `RigidBody` objects that belong to a particular model can be accessed via the `model_instance_id`.

---

*[drake/automotive/automotive_simulator.cc, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_DX0c_TbwFDLl8FS:-KV5aqOQB1xddHyBEcRj:beztnfx) ([raw file](https://github.com/robotlocomotion/drake/blob/40202a5be00dbf04d76b5c7dc8227a3c1f0ea8e4/drake/automotive/automotive_simulator.cc#L202)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This isn't really `num_joints` anymore though, is it?  It's `num_models` or something?
</details>
Yes. Good point. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_tvAke9mHMLDBXTB:-KV5gJfP3DYL3KpC-G-_:b-ycz9tz) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I have a local feature branch that charges forward some but it's not ready to be reviewed (it's very messy).
> 
> Did I introduce index math in this PR? Are you referring to the use of `model_instance_id` instead of `Rigidbody*`? I believe this is going in the right direction because we will soon support models with more than one `RigidBody` and all of the `RigidBody` objects that belong to a particular model can be accessed via the `model_instance_id`.
</details>
I think I've finally wrapped my head around this (see specific notes below).  Marking resolved.

The index math isn't so much the new code in this PR, as the comments and new variable names implying a future flowering of matlab-meme-infected-vector-index-manipulation that I would really prefer to see handled by GeometryWorld using proper encapsulation if at all possible.

---

*[drake/automotive/automotive_simulator.cc, line 212 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5fOOSNVG-8JCz8aCq:-KV5fOOTxDU28htgXhu-:bpz6e4e) ([raw file](https://github.com/robotlocomotion/drake/blob/533ac4e6e791b9e8023d54e099fb1797d29a4fbb/drake/automotive/automotive_simulator.cc#L212)):*
> ```cpp
>     // assumes:
>     //
>     //   (1) There are `num_ports_into_mux` vehicles.
> ```

This will continue to be true, won't it?  The names in the math above suggest so to me, but having it listed here implies that you think it's an over-constrained assumption?

---

*[drake/automotive/automotive_simulator.cc, line 213 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5fnKwX47TEszJjAbK:-KV5fnKxDk0x-PKbaoRJ:b-hetbeo) ([raw file](https://github.com/robotlocomotion/drake/blob/533ac4e6e791b9e8023d54e099fb1797d29a4fbb/drake/automotive/automotive_simulator.cc#L213)):*
> ```cpp
>     //
>     //   (1) There are `num_ports_into_mux` vehicles.
>     //   (2) Each vehicle has `num_joint_states_per_model` joint states.
> ```

To be clear -- the thing to generalize is that the "num_joint_states_per_model" concept will still exist, but it will have a different value for different model instances?  Is that correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-:-KV5gj7Os-i6yo-Tp4HZ:bnfp4nl)*

**Comment by maddog-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_tvAke9mHMLDBXTB:-KV5e_xqjmWUJqnqQ1Ht:b-bxzk8m) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I think I've finally wrapped my head around this (see specific notes below).  Marking resolved.
> 
> The index math isn't so much the new code in this PR, as the comments and new variable names implying a future flowering of matlab-meme-infected-vector-index-manipulation that I would really prefer to see handled by GeometryWorld using proper encapsulation if at all possible.
</details>
Yah, I too am a bit confused as to what this PR is for --- by itself, it doesn't add any features or make anything more tidy. The call to `FindModelInstanceBodies()` has been pushed to later in the code, and an `int` is being used as a promise to execute that method, instead of just passing the same eventual `RigidBody*`.  I'm not quite sure how this helps even in a future where a model has more than one `RigidBody`.  Why not wait until a PR which exercises/justifies this change in some tangible way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_tvAke9mHMLDBXTB:-KV5ncC_tjDWbUoToFEP:b-3slg9d) (no related file):*
<details><summary><i>Previously, maddog-tri wrote…</i></summary>
> Yah, I too am a bit confused as to what this PR is for --- by itself, it doesn't add any features or make anything more tidy. The call to `FindModelInstanceBodies()` has been pushed to later in the code, and an `int` is being used as a promise to execute that method, instead of just passing the same eventual `RigidBody*`.  I'm not quite sure how this helps even in a future where a model has more than one `RigidBody`.  Why not wait until a PR which exercises/justifies this change in some tangible way?
</details>
I'll create a follow-up PR soon that builds upon this PR. I mistakenly thought the changes in this PR would be relatively uncontroversial.

I believe there are benefits to maintaining a `model_instance_id` rather than a vector of pointers to `RigidBody` objects that we have not considered yet. For example, there may be a future where the number of `RigidBody` objects that are a part of a particular model instance may change over time. Or maybe certain `RigidBody` objects are loaded and unloaded into the `RigidBodyTree` over time due to tiling? @sherm1 can you shed some light? Is it generally preferable to maintain indices to `RigidBody` objects rather than pointers to `RigidBody` objects?

---

*[drake/automotive/automotive_simulator.cc, line 212 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5fOOSNVG-8JCz8aCq:-KV5n2wou65aRaiPXGrK:bqhzuhf) ([raw file](https://github.com/robotlocomotion/drake/blob/533ac4e6e791b9e8023d54e099fb1797d29a4fbb/drake/automotive/automotive_simulator.cc#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This will continue to be true, won't it?  The names in the math above suggest so to me, but having it listed here implies that you think it's an over-constrained assumption?
</details>
Yes, I believe it's overconstrained because we'll eventually have much more than just vehicles. For example, we may have models representing obstacles, buildings, sidewalks, etc. For the models that are not moving in the world, I'm not sure they will be represented in `rigid_body-tree_publisher_inputs_`. We'll see...

---

*[drake/automotive/automotive_simulator.cc, line 213 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5fnKwX47TEszJjAbK:-KV5nRBJL2PW9rfIxcso:b-121t92) ([raw file](https://github.com/robotlocomotion/drake/blob/533ac4e6e791b9e8023d54e099fb1797d29a4fbb/drake/automotive/automotive_simulator.cc#L213)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> To be clear -- the thing to generalize is that the "num_joint_states_per_model" concept will still exist, but it will have a different value for different model instances?  Is that correct?
</details>
Yes. That's my plan.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 212 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5fOOSNVG-8JCz8aCq:-KV5zGWCoLUgZHyyJtcI:b-jo3fvv) ([raw file](https://github.com/robotlocomotion/drake/blob/533ac4e6e791b9e8023d54e099fb1797d29a4fbb/drake/automotive/automotive_simulator.cc#L212)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yes, I believe it's overconstrained because we'll eventually have much more than just vehicles. For example, we may have models representing obstacles, buildings, sidewalks, etc. For the models that are not moving in the world, I'm not sure they will be represented in `rigid_body-tree_publisher_inputs_`. We'll see...
</details>
Okay.  In the context of the TODO ("More varieties of vehicles") it's confusing, then, since it has nothing to do with non-vehicle elements.  But whatever, it's a TODO, we can let it skate.  Marking resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by liangfok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 212 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5fOOSNVG-8JCz8aCq:-KV62cbeIq1ySTNmIWu0:by3zo07) ([raw file](https://github.com/robotlocomotion/drake/blob/533ac4e6e791b9e8023d54e099fb1797d29a4fbb/drake/automotive/automotive_simulator.cc#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Okay.  In the context of the TODO ("More varieties of vehicles") it's confusing, then, since it has nothing to do with non-vehicle elements.  But whatever, it's a TODO, we can let it skate.  Marking resolved.
</details>
Ah. Good point. I updated the TODO to mention non-vehicle models.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-KV5_tvAke9mHMLDBXTB:-KV6j_xOgMP3VSI7rB5H:b-ef1mh4) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I'll create a follow-up PR soon that builds upon this PR. I mistakenly thought the changes in this PR would be relatively uncontroversial.
> 
> I believe there are benefits to maintaining a `model_instance_id` rather than a vector of pointers to `RigidBody` objects that we have not considered yet. For example, there may be a future where the number of `RigidBody` objects that are a part of a particular model instance may change over time. Or maybe certain `RigidBody` objects are loaded and unloaded into the `RigidBodyTree` over time due to tiling? @sherm1 can you shed some light? Is it generally preferable to maintain indices to `RigidBody` objects rather than pointers to `RigidBody` objects?
</details>
@maddog-tri  please see the followup PR #3933 that builds upon this one. Does it help clarify the reasoning behind the changes in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921)*

**Comment by maddog-tri** [comment]
Is there some aspect of PR culture that I don't understand?  By itself, this PR neither adds any features nor improves the code; it makes the code worse. It may be a precursor to other better things, but those things are purely speculative at this point.  And now there is a subsequent PR that kinda builds on this one, but ends up deleting code added by this PR.

Is there some reason not to just complete "Spiral 1" of #3919, with an actual Prius with immovable wheels, and then review that?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-:-KV6iOix1Xh7uINBybtk:bagy23v)*

**Comment by liangfok** [comment]
Basically the culture is to keep PRs small any manageable for reviewers. In what way does this PR make the code worse? If we wait for spiral one, the PR will likely be huge.

**Comment by maddog-tri** [comment]
For one, there are now duplicate calls to `FindModelInstanceBodies(model_instance_id)` in different places.  And the original call is actually better positioned for diagnostic value, which calls into question why make the change to passing model_instance_id's instead of RigidBody*'s.

How huge can a full Spiral 1 PR possibly be?  I'd rather wait for a cohesive self-contained PR.  If I have to piece together the effects of 2 or 3 or more PR's, and/or make guesses about what the future PR's are going to show me, then smaller chunks doesn't really help me.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-:-KV6pF7ARRbvmlbDIUdW:b-nxe4q9)*

**Comment by liangfok** [comment]
The first call should ideally be replaced with a call to a new method called `GetNumBodies ()`. Alright I will charge  forward with spiral 1 so you can see why the changes in this PR are needed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-:-KV6xiXUWwhDkgjfJaa-:b-i3c5r1)*

**Comment by maddog-tri** [comment]
Great!  I am looking forward to Spiral 1.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3921#-:-KV70cQN1ksX_BFA5RiR:b9hxhcz)*

**Pull request closed without merging**
