### PR TITLE
Mark `gym_py` as not to be upgraded.

### PR DESCRIPTION
**Pull request by ggould-tri**
* See tools/workspace/gym_py/README.md for details.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18534)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@mwoehlke-kitware as an alternative to #18520

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18534#-:-NKy9JDIBEV9ugmXeM1Z:b-6p8sy4)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18534#-:-NKyI2IoE7P0wmjG4Atw:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+@sherm1 for platform review per rotation
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18534#-:-NKyIL2Q1iHfa7SR4X0o:b-8bma47)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18534#-:-NKyQIWmB2NNIM7g1uYw:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),mwoehlke-kitware (waiting on @ggould-tri)

**Pull request merged**
