### PR TITLE
Port Acrobot and Pendulum to SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This does not add any new conversions; it is only a re-phrasing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6748)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@naveenoid for feature review, please.

**Comment by naveenoid** [comment]
only a minor BTW. :lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/pendulum/pendulum_plant.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6748#-KqZ0rXXDUjcYYgsb_W5:-KqZ0rXXDUjcYYgsb_W6:b-hzjoj2) ([raw file](https://github.com/robotlocomotion/drake/blob/101c71c9756d1ea845f632d179012d6237941121/drake/examples/pendulum/pendulum_plant.cc#L13)):*
> ```cpp
> PendulumPlant<T>::PendulumPlant()
>     : systems::LeafSystem<T>(
>           systems::SystemTypeTag<pendulum::PendulumPlant>{}) {
> ```

BTW: Is the pendulum:: really needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6748#-:-KqZ1QYqO-J_ChaAjUiN:b-ncbz9m)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/pendulum/pendulum_plant.cc, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6748#-KqZ0rXXDUjcYYgsb_W5:-KqZ1m-RO4H-U6VRG_Nj:b-laphe6) ([raw file](https://github.com/robotlocomotion/drake/blob/101c71c9756d1ea845f632d179012d6237941121/drake/examples/pendulum/pendulum_plant.cc#L13)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Is the pendulum:: really needed here?
</blockquote></details>

OK Yes, sadly.  It disambiguates whether we're naming the constructor or the class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6748)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per rotation, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With one passing thought. The testing strategy on the `PendulumPlant` is that there's a test that converts to `AutoDiffXd` and `print_symbolic_dynamics.cc` has the smoke-test flag on, yes? +@ggould-tri for final review.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6748#-:-KqZ7-3GshsrPbTstUCD:bna6g9s)*

**Comment by ggould-tri** [comment]
:lgtm:, this is a nice renovation of some of our colder code.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6748#-:-KqZ8MEIs0HuOhB71w1f:b-qaokt2)*

**Comment by jwnimmer-tri** [comment]
>  The testing strategy on the PendulumPlant ...

Well, I am disappointed in the testing for these examples, but I decided not to fix it in this PR.

**Pull request merged**
