### PR TITLE
DeformableDriver computes dynamic data for contact solver

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Calculate linear dynamics matrices and participating free motion velocities for deformable bodies.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993#-:-NDA3tKv6j86xCqlW3cs:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Comments addressed. PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993#-:-NDZ2uJU2ZBT34jzTPPd:b-pr0h6x)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYF5_F0iqWiTJbbxQe:-NDYiKzgALVaNizw3dsq:b-9zgltk) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Not related to this PR, just a thought that came to me while reviewing.
Right now we have "participating = in-contact". When adding capability for constraints (and in particular to apply BCs on moving rigid components) we'll need to take into account dofs that participate through these constraints. In that case I imagine then we'd have "participating = in-contact + constrained". Have you considered how your design would accommodate for this?


</blockquote></details>

Good question! I haven't thought of this before, but it seems like it would be natural to have the constraints internally maintain a `ContactParticipation` data structure and "merge" it with the participation structure coming from contact.

___
___
*[`multibody/plant/deformable_driver.h` line 65 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYFiIY5tmdn_bxNjrE:-NDYw8_D6wBtEnIX51W_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.h#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, to avoid repeating this ordering every time, consider having a section in the class documentation we can refer to.
Also, probably worth adding a small section on the definition of "participating" and how things are indexes for participating dofs.
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.h` line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYEbIt8BmtR-XUAAXc:-NDYwL_q0zsbeUN_h0mS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.h#L75)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, without looking into the source I'd imagine this will be used to setup A for SAP. Therefore this only includes "participating dofs"? clarify in the docs.
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 195 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYIKPq03kJYT-leEzT:-NDYwb-TBdN-o0FoxnmB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.cc#L195)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this implementation seems to indicate that all bodies are added, even if not participating and therefore zero size matrices can be added. Is this correct? request to simply document this in the header.
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 400 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYJy50EH9qrAUX2BPA:-NDYwgkpBsSCUTmbwdu2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.cc#L400)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, DEMAND result!=nullptr
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 411 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYKCND1yvK1pEhNDjj:-NDYwpr382nJH1NsRsSs:b-1jvde8) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.cc#L411)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, consider an in-place version of Multiplex/Demultiplex. i.e. `Multiplex(std::move(participating_v_star), result)`
</blockquote></details>

Done. Added a TODO.
___
*[`multibody/plant/deformable_driver.cc` line 425 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYLG2pD8QVNck2Bjtc:-NDYz-hC8FjDYcTAkUCG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.cc#L425)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, DEMAND pre-condition !=nullptr, here and below.
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 457 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYM-Pf00qTmQIn2_q7:-NDYzQxZ3P8z9IBJMCiI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/deformable_driver.cc#L457)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, explain in the docs an empty complement is possible.
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYUB3T69DQnKhbYIUk:-NDZ0Jcv67_wfZ4LoDz3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/test/deformable_driver_contact_test.cc#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, It'd be nice having a summary of the purpose of this fixture:
 - problem setup and configuration.
 - Problem sizes: dofs, participating dofs, number of contacts, etc.
 - Driver functionality to be tested.
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 217 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYVfKPBglCAybFRrj9:-NDZ0KT89PnO5jCFpOAn:bwch0zk) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/test/deformable_driver_contact_test.cc#L217)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

document this number her or in the fixture's docs.
</blockquote></details>

Done in class doc.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 239 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYW63u0nmdYs6YedsY:-NDZ0h-ODjmTZiDq18Lk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/test/deformable_driver_contact_test.cc#L239)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I'd avoid saying "above" since usually this kind of comments goes out of sync as code moves around over the years.
Maybe something like: "... which are tested separately by DeformbablyDriverTest"
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 257 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYWRchE-GzEZFZxf3A:-NDZ0NO1BIOBCLuRHlLt:bwch0zk) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/test/deformable_driver_contact_test.cc#L257)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, document this fixed number (6)
</blockquote></details>

Done in class doc.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 302 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYXdZcAps5T7lR3mTf:-NDZ2QvjDUNDUopAHyUm:b716fm4) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/test/deformable_driver_contact_test.cc#L302)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Consider either moving this schematic to the fixture's documentation or somehow making a connection with the expected configuration of the fixture. There is some context here that I feel is not captured by only in your knowledge of the test.
Ditto with sizes/indexes below.
</blockquote></details>

I augmented the schematics. PTAL.

**Review by amcastro-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993#-:-NDZtNug6U_I9H4WwdOh:b-qxjhdt)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri and @jwnimmer-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYF5_F0iqWiTJbbxQe:-NDZuPkWC5SwgFV2fcDF:bpzv5sa) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Good question! I haven't thought of this before, but it seems like it would be natural to have the constraints internally maintain a `ContactParticipation` data structure and "merge" it with the participation structure coming from contact.
</blockquote></details>

That seems to make sense. One step at a time, but I figured a good idea to start thinking about this.

___
___
*[`multibody/plant/deformable_driver.h` line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZtXC32Cc5dAOI6L2g:-NDZtXC32Cc5dAOI6L2h:b-m7pi3v) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.h#L29)):*
> ```objc
> 
>  For any vertex in a deformable body, we say that it is "participating in
>  contact and constraints" (or participating" in short) if it is incident to a
> ```

minor, spurious quotes
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDYUB3T69DQnKhbYIUk:-NDZu27RCuNT2gmKUj9e:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/ba6261f375a44373d234d4e22628436ee436af7e/multibody/plant/test/deformable_driver_contact_test.cc#L41)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 310 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZuBuG6Mb4jyEulReO:-NDZuBuH8onV5sePyR2w:b-m5nsvf) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/test/deformable_driver_contact_test.cc#L310)):*
> ```cpp
>   /* Schematically the participating block (A), the non-participating block (D),
>    and the off-diagonal block (B) look like
>                            ______________________________________
> ```

minor, the top line looks like offset to the left. Not sure if a fix is possible but maybe either removing a character on the left or adding one to the right

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/deformable_driver.h` line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZtXC32Cc5dAOI6L2g:-NDZx7gl7SJaX7Nu54EX:b-qnrxp) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.h#L29)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, spurious quotes
</blockquote></details>

Actually not spurious -- just missing the open-quote.

`(or "participating" for short)`

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993#-:-ND_1V60BQfdef8kmGz_:bnfp4nl)* status: 6 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/plant/deformable_driver.cc` line 197 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZz10g0lHEgVPkFygK:-NDZz10g0lHEgVPkFygL:bx4pskc) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.cc#L197)):*
> ```cpp
>   DRAKE_DEMAND(A != nullptr);
>   const int num_bodies = deformable_model_->num_bodies();
>   A->reserve(A->size() + num_bodies);
> ```

nit I can't offer specific advice here from just this PR (it's not clear what call pattern this function will have), but you need to be very careful when reserving a _relative_ size on a vector.

If you were to call `AppendLinearDynamicsMatrix` repeatedly on the same `A` object, you would experience _quadratic_ computation time as it repeatedly allocates a vector of (say) 5 bodies, then 10 bodies (copying all of the data), then 15 bodies (copying the data again), etc.

In other words, it's easy to defeat the default geometric growth of `std::vector`, which is what gives us linear-time appending.

The rule is that to call `reserve` on a given vector object _at most once_.  If we can't guarantee that as a precondition of how this function gets used, then either we remove the `reserve` or else we guard it with `if (A->empty())` so it only happens once in practice.
___
*[`multibody/plant/deformable_driver.cc` line 404 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-ND_-D4i8BcTT-mW4awh:-ND_-D4i8BcTT-mW4awi:b-b8g6he) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.cc#L404)):*
> ```cpp
>   const int num_bodies = deformable_model_->num_bodies();
>   std::vector<VectorX<T>> participating_v_star(num_bodies);
>   for (DeformableBodyIndex i(0); i < num_bodies; ++i) {
> ```

BTW I just had a random thought...

It would be super convenient if `TypeSafeIndex` had a range generator, so we could write:

```c++
for (auto i : DeformableBodyIndex::range(num_bodies)) {
```

I suspect this pattern comes up a _lot_.  Maybe a nice Friday project someday.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 289 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-ND_0pm-CkJqZzKEhgmT:-ND_0pm0E5jLG3Ih57-c:b-xwpgsk) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/test/deformable_driver_contact_test.cc#L289)):*
> ```cpp
>   const PetscSymmetricBlockSparseMatrix& calculated_tangent_matrix =
>       EvalFreeMotionTangentMatrix(plant_context, body_index);
>   /* Make the matrix mutable so that we can assemble the Petsc matrix. */
> ```

nit Would it make sense to _copy_ (or clone) the `calculated_tangent_matrix` in this case instead of aliasing the one from the context's cache?

It's fairly clear that no code afterwards here will be corrupted by writing into the cache through a const_cache, but copying seems like would be somewhat more future-proof?
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 304 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-ND_1CL842ItYeuS1VN4:-ND_1CL9DJIozErG7Myi:b-sct9fm) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/test/deformable_driver_contact_test.cc#L304)):*
> ```cpp
>   const PetscSymmetricBlockSparseMatrix& tangent_matrix =
>       EvalFreeMotionTangentMatrix(plant_context, body_index);
>   /* Make the matrix mutable so that we can assemble the Petsc matrix. */
> ```

Ah.  Now there is a _lot_ of code after the `tangent_matrix` calculation, so we definitely can't `const_cast<>` away the cache constness here; too brittle.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993)* status: 1 unresolved discussion (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[`multibody/plant/deformable_driver.h` line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZtXC32Cc5dAOI6L2g:-ND_Ka4j7ChlIYXVeShq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually not spurious -- just missing the open-quote.

`(or "participating" for short)`
</blockquote></details>

Done.
___
*[`multibody/plant/deformable_driver.cc` line 197 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZz10g0lHEgVPkFygK:-ND_Kcen1-6O-hQKGzrB:bm04v86) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.cc#L197)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I can't offer specific advice here from just this PR (it's not clear what call pattern this function will have), but you need to be very careful when reserving a _relative_ size on a vector.

If you were to call `AppendLinearDynamicsMatrix` repeatedly on the same `A` object, you would experience _quadratic_ computation time as it repeatedly allocates a vector of (say) 5 bodies, then 10 bodies (copying all of the data), then 15 bodies (copying the data again), etc.

In other words, it's easy to defeat the default geometric growth of `std::vector`, which is what gives us linear-time appending.

The rule is that to call `reserve` on a given vector object _at most once_.  If we can't guarantee that as a precondition of how this function gets used, then either we remove the `reserve` or else we guard it with `if (A->empty())` so it only happens once in practice.
</blockquote></details>

Done. 

`AppendLinearDynamicsMatrix` is called only once with a potentially non-empty A, so the problem you described shouldn't happen. I removed the reserve anyway because of the danger you mentioned and that I don't the reserve isn't likely to be overly useful with MatrixXd.
___
*[`multibody/plant/deformable_driver.cc` line 404 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-ND_-D4i8BcTT-mW4awh:-ND_M3FgDVzedcTpRA3Y:b-wrs1g0) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/deformable_driver.cc#L404)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I just had a random thought...

It would be super convenient if `TypeSafeIndex` had a range generator, so we could write:

```c++
for (auto i : DeformableBodyIndex::range(num_bodies)) {
```

I suspect this pattern comes up a _lot_.  Maybe a nice Friday project someday.
</blockquote></details>

Yes, that's indeed a common pattern.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 289 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-ND_0pm-CkJqZzKEhgmT:-ND_MVwxD2-j6s-jZ8kQ:ba4di8c) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/test/deformable_driver_contact_test.cc#L289)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Would it make sense to _copy_ (or clone) the `calculated_tangent_matrix` in this case instead of aliasing the one from the context's cache?

It's fairly clear that no code afterwards here will be corrupted by writing into the cache through a const_cache, but copying seems like would be somewhat more future-proof?
</blockquote></details>

Done thanks.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 304 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-ND_1CL842ItYeuS1VN4:-ND_MZfR1LNUEhNu041u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/test/deformable_driver_contact_test.cc#L304)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah.  Now there is a _lot_ of code after the `tangent_matrix` calculation, so we definitely can't `const_cast<>` away the cache constness here; too brittle.
</blockquote></details>

Done.
___
*[`multibody/plant/test/deformable_driver_contact_test.cc` line 310 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17993#-NDZuBuG6Mb4jyEulReO:-ND_Mg-g3VKlj2hYD6_L:beyxhd6) ([raw file](https://github.com/robotlocomotion/drake/blob/aff442ec9e8ab5aca3f87f9582452b8c6287ff65/multibody/plant/test/deformable_driver_contact_test.cc#L310)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, the top line looks like offset to the left. Not sure if a fix is possible but maybe either removing a character on the left or adding one to the right
</blockquote></details>

Done. I added one to the right. (Removing one on the left makes it tilt to the right.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Cleaned up some sloppiness in r4.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993#-:-ND_QP6sD6i98_BzCTQQ:b-7w7bst)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17993)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
