### PR TITLE
restore nlohmann/json dependency

### PR DESCRIPTION
**Pull request by svenevs**
Proposed json library choice for the render client.  It seems ideal to choose the header only version since jsoncpp was just removed.

Relates: #16234

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
CI doesn't actually run this new bazel code unless it's used somewhere.  An "add a new external" PR should also add a program or test that (trivially) uses the new dependency.  Something small in the `dev` folder should suffice.

**Review by svenevs — COMMENTED** [review]
Added a test.  It seems that `<filesystem>` header is verboten? AFAICT we're in C++17, the compilation failures come from `#include <filesystem>`...

If that header is verboten, I will try resurrecting an older version of `json`?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231#-:-Mr8xQmt5_P30dCqQzhh:b-fecx94)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by jwnimmer-tri — COMMENTED** [review]
> It seems that `<filesystem>` header is verboten? AFAICT we're in C++17, the compilation failures come from #include `<filesystem>` ...

Yes, we do put our compilers into C++17 mode, but that doesn't mean that the toolchains' standard library implementations have 100% of the C++17 classes available.  The subset of C++17 feature that we can use is defined by whatever our compiler support matrix allows for.  Indeed, almost none of our supported build platforms offer `<filesystem>`.

It looks like if we set the `JSON_HAS_CPP_14` preprocessor symbol, then json will omit its `<filesystem>` (and `<string_view>`) integration, which should allow us stick with recent json releases, instead of pinning to something old.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231#-:-Mr9IDIg42VnxBQ9ynrx:bd8v1s5)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[tools/workspace/json/package.BUILD.bazel, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16231#-Mr9IyO5BYBrqNln2M3u:-Mr9IyO5BYBrqNln2M3v:b-kxk2j0) ([raw file](https://github.com/robotlocomotion/drake/blob/033b2d4a02c172a6a13fb8f36a23c62b46b37d7b/tools/workspace/json/package.BUILD.bazel#L20)):*
> ```
> )
> 
> install(
> ```

This rule is dead code.  We must tie the license file into the top-level install target exactly when non-dev code starts using this library.  For now, remove this stanza.
___
*[geometry/render/dev/BUILD.bazel, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16231#-Mr9IdVy6NK9Kfzq6WoV:-Mr9IdVz6emqOEhgZcIt:b-id7006) ([raw file](https://github.com/robotlocomotion/drake/blob/033b2d4a02c172a6a13fb8f36a23c62b46b37d7b/geometry/render/dev/BUILD.bazel#L54)):*
> ```Starlark
> drake_cc_test(
>     name = "json_compile_test",
>     srcs = ["json_compile_test.cc"],
> ```

nit Place tests in the `test` sub-directory.

**Review by svenevs — COMMENTED** [review]
OK, I think I added it correctly to the `defines` property so all consumers should receive it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231#-:-Mr9XQeC0Uru3_ypqxUc:b1fpoyb)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/workspace/json/package.BUILD.bazel, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16231#-Mr9IyO5BYBrqNln2M3u:-Mr9Xhek54JLee-wz2oX:b-jkyjd0) ([raw file](https://github.com/robotlocomotion/drake/blob/033b2d4a02c172a6a13fb8f36a23c62b46b37d7b/tools/workspace/json/package.BUILD.bazel#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This rule is dead code.  We must tie the license file into the top-level install target exactly when non-dev code starts using this library.  For now, remove this stanza.
</blockquote></details>

Done.  Deleted.
___
*[geometry/render/dev/BUILD.bazel, line 54 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16231#-Mr9IdVy6NK9Kfzq6WoV:-Mr9XkTzCUaglmX8BcdP:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/033b2d4a02c172a6a13fb8f36a23c62b46b37d7b/geometry/render/dev/BUILD.bazel#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Place tests in the `test` sub-directory.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231#-:-Mr9y0pLDXySvb2ADx2W:b-b5dc06)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[tools/workspace/json/package.BUILD.bazel, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16231#-Mr9xvEW7CATOJxwNyVs:-Mr9xvEW7CATOJxwNyVt:b-ji4x25) ([raw file](https://github.com/robotlocomotion/drake/blob/7842201526a8d0ed755314b8f8c0e32f1a3a92dc/tools/workspace/json/package.BUILD.bazel#L18)):*
> ```
>     hdrs = ["single_include/nlohmann/json.hpp"],
>     includes = ["single_include"],
>     defines = ["JSON_HAS_CPP_14"],  # Avoid <filesystem>
> ```

nit Punctuate.



_Suggestion:_
```
# Avoid <filesystem>.
```

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by svenevs — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231#-:-MrMyZ_39Bu3QoFHIx_g:bg7igkv)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/workspace/json/package.BUILD.bazel, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16231#-Mr9xvEW7CATOJxwNyVs:-MrMyboa6LDSqBUndT-7:bkz5cki) ([raw file](https://github.com/robotlocomotion/drake/blob/7842201526a8d0ed755314b8f8c0e32f1a3a92dc/tools/workspace/json/package.BUILD.bazel#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Punctuate.
</blockquote></details>

Done.  Good catch!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16231)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Pull request merged**
