### PR TITLE
Add pydrake bindings for IpoptSolver

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6159.

Hopefully this is useful on its own, but the immediately motivating purpose is to be able to unit test the pybind infrastructure for individual solver back-ends (such as gurobi and mosek), without requiring access to commercially-licensed software.

This PR also fixes a typo in related test case name.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6450)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/BUILD, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6450#-Knj9rqU495X8so4QTf0:-Knj9rqU495X8so4QTf1:b-4mz8kg) ([raw file](https://github.com/robotlocomotion/drake/blob/d722b120953b1cd404b90cb4465646f1a761efe5/drake/bindings/BUILD#L192)):*
> ```Python
>         ":autogenerated_path_py_genrule",
>     ],
>     data = [
> ```

FYI We should make this list a variable since it is reused in the install (my omission before, unfortunately).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6450#-:-KnjAGM4TsTiOzMl2XCu:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/BUILD, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6450#-Knj9rqU495X8so4QTf0:-KnjDrHhwQRII-WXUjdR:b-xi5nqk) ([raw file](https://github.com/robotlocomotion/drake/blob/d722b120953b1cd404b90cb4465646f1a761efe5/drake/bindings/BUILD#L192)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI We should make this list a variable since it is reused in the install (my omission before, unfortunately).
</blockquote></details>

Ah, well ideally the `install` rules would install the `data=` here just by my saying `:pydrake` (since it already lists that data).  But you're right -- since we need to list it out manually for now, I should DRY this.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6450)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
:lgtm:.  Always nice to see a PR of multiple orthogonal commits not needing the curate tag.

---

Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6450#-:-KnjR8KHMbizRdn2jW65:b-j6pwmu)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/BUILD, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6450#-Knj9rqU495X8so4QTf0:-KnjiARX8LehlWq-zEFv:b-fyph9x) ([raw file](https://github.com/robotlocomotion/drake/blob/d722b120953b1cd404b90cb4465646f1a761efe5/drake/bindings/BUILD#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, well ideally the `install` rules would install the `data=` here just by my saying `:pydrake` (since it already lists that data).  But you're right -- since we need to list it out manually for now, I should DRY this.

Done.
</blockquote></details>

@jamiesnape PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6450)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6450)*

**Pull request merged**
