### PR TITLE
Revert "Re-factor monolithic pick and place demo"

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Reverts RobotLocomotion/drake#7474

Dear @avalenzu ,

The on-call build cop, @m-chaturvedi, believes that your PR #7474 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
[1](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-asan-everything/700/), [2](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-tsan-everything/529/console), [3](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-ubsan-everything/177/), [4](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-lsan-everything/881/)

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7522)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please

**Comment by avalenzu** [comment]
Hopefully #7523 will pass CI in its current state so that it can be merged instead of this. If not, this :lgtm: .

---

Review status: 0 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7522#-:-KzzK1f0TULRQF7cOCnx:b-5ex3oh)*

**Comment by avalenzu** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7522)*

**Comment by m-chaturvedi** [comment]
Resolved via #7523

**Pull request closed without merging**
