### PR TITLE
Add symbolic uninterpreted function

### LINKED ISSUE #5537: Add UninterpretedFunction kind in symbolic expression
WIP branch at https://github.com/soonho-tri/drake/tree/pr-add-symbolic-uninterpreted-function

/cc @jwnimmer-tri

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #5537.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5680)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , feature-review please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-:-Kg_YhD2hNe78CEaL7Z0:b8y8nlm)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 5 of 9 files at r1.
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_expression.h, line 469 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga4YnAAO11vKrZTrwH:-Kga4YnAAO11vKrZTrwI:b3ig2yk) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression.h#L469)):*
> ```objc
> /** Constructs an uninterpreted-function expression with @p name and @p vars. An
>  * uninterpreted function is identified by its name and the set of variables
>  * attached to it. */
> ```

Either here, or maybe atop the file, I think we'd do well with a bit more elaboration of what U.F. _means_... something about an opaque function that depends _only_ on the named variables, and we presume name is globally unique within the program, etc.  And maybe one canonical example of what you'd use it for.

---

*[drake/common/symbolic_expression.h, line 589 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga5UEopL6r2NqPqASa:-Kga5UEopL6r2NqPqASb:b-hkiyzy) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression.h#L589)):*
> ```objc
>  *  \pre{@p e is an uninterpreted-function expression.}
>  */
> const std::vector<Variable>& get_arguments(const Expression& e);
> ```

These method names seem like quite a name-grab; would it be better to `uninterpreted_function_get_name()` and `uninterpreted_function_get_arguments()` or something like that?

---

*[drake/common/symbolic_expression.h, line 589 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga6CHciTqV3TJTHO4E:-Kga6CHdiakGjYMOcZdd:b-7kyg90) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression.h#L589)):*
> ```objc
>  *  \pre{@p e is an uninterpreted-function expression.}
>  */
> const std::vector<Variable>& get_arguments(const Expression& e);
> ```

I am not finding the method bodies or tests for these two new functions?

---

*[drake/common/symbolic_expression_cell.cc, line 1643 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga8ZO4ByXn0uQp-5bQ:-Kga8ZO4ByXn0uQp-5bR:b53wcdx) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression_cell.cc#L1643)):*
> ```cpp
>                      hash_combine(hash_value<string>{}(name), vars), false},
>       name_{name},
>       variables_{vars} {}
> ```

FYI To confirm my understanding: we allow U.F. of zero variables, because it's a way to say "some constant value, but I'm not telling you what it is"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-:-Kga9bOfadoICVq4C8Ty:by96gdd)*

**Comment by soonho-tri** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 1643 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga8ZO4ByXn0uQp-5bQ:-KgaA7jB9U1fwAa3K5jR:b-hw3l8f) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression_cell.cc#L1643)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI To confirm my understanding: we allow U.F. of zero variables, because it's a way to say "some constant value, but I'm not telling you what it is"?
</blockquote></details>

Yes, that's correct. Also, we might end up with this case after substitution. For example:

```c++
const Expression e1 = uninterpreted_function("uf", {var_x_});
const Expression e2 = Substitute(var_x_, 42.0);
// FYI, e2 is `uf({})`.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680)*

**Comment by soonho-tri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_expression.h, line 469 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga4YnAAO11vKrZTrwH:-KgaO3zqj69YsVsy84IW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression.h#L469)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Either here, or maybe atop the file, I think we'd do well with a bit more elaboration of what U.F. _means_... something about an opaque function that depends _only_ on the named variables, and we presume name is globally unique within the program, etc.  And maybe one canonical example of what you'd use it for.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression.h, line 589 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga5UEopL6r2NqPqASa:-KgaK2hiLDedaJvuu2Xo:b-niyqve) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression.h#L589)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These method names seem like quite a name-grab; would it be better to `uninterpreted_function_get_name()` and `uninterpreted_function_get_arguments()` or something like that?
</blockquote></details>

Done. 
 - `get_name` => `get_uninterpreted_function_name`.
 - `get_arguments` => gone. (because we already have `.GetVariables()` which extracts the variables inside).

---

*[drake/common/symbolic_expression.h, line 589 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-Kga6CHciTqV3TJTHO4E:-KgaKKB3VaRVpmqXNXPy:b-jeevfz) ([raw file](https://github.com/robotlocomotion/drake/blob/cfa0cdcc592cf8a43cdf00fd993cc0c878007451/drake/common/symbolic_expression.h#L589)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not finding the method bodies or tests for these two new functions?
</blockquote></details>

Done. (added definition for `get_uninterpreted_function_name` and tests for that)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_substitution_test.cc, line 396 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-KgaV7OPwAe5BUOwVlFw:-KgaV7OQabTETFyRpcTv:boanhz4) ([raw file](https://github.com/robotlocomotion/drake/blob/ab77bcfaa1115eb50cc4a6dcc53b2502a8e1be21/drake/common/test/symbolic_substitution_test.cc#L396)):*
> ```cpp
>   EXPECT_PRED2(ExprEqual, uf2.Substitute(s2),
>                uninterpreted_function("uf2", {var_y_, var_z_}));
> }
> ```

I think we should test that substituting a variable with a constant removes it from the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-:-KgaX1OmSXoVD1rhTkZL:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_substitution_test.cc, line 396 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5680#-KgaV7OPwAe5BUOwVlFw:-KgaYXJ2f6o7-EmhfY7l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ab77bcfaa1115eb50cc4a6dcc53b2502a8e1be21/drake/common/test/symbolic_substitution_test.cc#L396)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we should test that substituting a variable with a constant removes it from the list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5680)*

**Pull request merged**
