### PR TITLE
Add gflags to drake.cps for drake/common/text_logging_gflags.h

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed for https://github.com/RobotLocomotion/drake-shambhala/pull/72.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7646)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by jwnimmer-tri** [comment]
I really don't want to have libdrake link to libgflags, even as an interim measure.  Let's just stop installing text_logging_gflags for now instead, until we can fix this properly.  The Shambhala demo doesn't really need that functionality, it was just a proof that the include worked.

**Comment by jamiesnape** [comment]
It really should not actually link into `libdrake.so` since it is not used by `libdrake.so`, so in effect this just populates the includes.

**Comment by jwnimmer-tri** [comment]
My guess was that this would force `-lflags` onto users' link line though, if they ask to link drake?  Are you saying that they would not end up with DT_NEEDED libgflags.so if they weren't using it though?  Maybe I'm misunderstanding what the cps / cmake syntax means.

**Comment by jwnimmer-tri** [comment]
I am okay with not installing `drake/common/text_logging_gflags.h` as an interim measure.  I think a separate target is a good endgame, and fine now too if its easy.

**Comment by jamiesnape** [comment]
The separate target is easier; see the latest push. Ideally the header would be in different folder to the drake headers, but I think this should be fine for now.

**Comment by jwnimmer-tri** [comment]
Agreed -- a step in the right direction.

:lgtm: platform and some feature.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/install/libdrake/drake.cps, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7646#-L0kYtNGkKKZs2aukk0J:-L0kYtNGkKKZs2aukk0K:b-upn6vf) ([raw file](https://github.com/robotlocomotion/drake/blob/bff7a2173f047b7c47793bb25bb4032f5b1f7e40/tools/install/libdrake/drake.cps#L35)):*
> ```delphi
>     },
>     "gflags": {
>       "Version": "2.2.0",
> ```

FYI I didn't double-check this hopefully @fbudin69500 does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7646#-:-L0kYrOFe60DxogawyEq:byhdlzx)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7646#-:-L0kaqqRNHD-uDe3bRY7:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7646)*

**Pull request merged**
