### PR TITLE
zap early examples of converting between matlab and C++ 

### PR DESCRIPTION
**Pull request by RussTedrake**
(msspoly <--> c++ polynomial class and taylorVar <--> autodiff).

I believe these have been replaced/improved by @tkoolen's wrappers.  

@tkoolen for feature review
@jwnimmer-tri for platform (since it's quick and he requested the purge :)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4043)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4043#-:-KVz38Edt_61b-KXeJMK:bnfp4nl)*

**Comment by tkoolen** [comment]
:lgtm: 
Not important, but I was confused by 'replaced/improved by [my] wrappers'. Do you mean that they *could* be written in a better way using `mexify.h` (but have not yet)? I guess I don't see what actually replaced this functionality.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4043#-:-KW-B89dobhSqgOMpIH8:b2gjvox)*

**Comment by jwnimmer-tri** [comment]
FTR, I am not merging this yet (even though reviewable really wants me to) in case tkoolen's aside means that some of this should not be removed yet.

**Comment by RussTedrake** [comment]
just had a f2f w/ tkoolen to confirm.

**Pull request merged**
