### PR TITLE
Restore RenderEngineVtk MultiMaterialObject test for EGL

### LINKED ISSUE #22044: RenderEngineVtk cloning yields rendering artifacts
### What happened?

In #22025, a test in `render_engine_vtk_test.cc` had to be disabled for EGL. This failure is *not* unique to the EGL backend. More robust testing shows that EGL merely provided a context which exposed an underlying problem.

Do the following:

```bash
bazel run //tools:model_visualizer_private -- --show_rgbd_sensor \
    package://drake/geometry/render/test/meshes/rainbow_box.obj
```

As you rotate the view and look at the box's blue face, you'll observe something like the following:

output

What you see is that the blue, green, and red faces are always drawn. However, they are drawn with incorrect classification of "in front". The red face is always considered in front of the green and the green is always considered in front of the blue. And this is with the GLX backend. In fact, the test in `render_engine_vtk_test.cc` would also fail if it were phrased differently. It's simply insufficiently sufficient to recognize this failure.

In fact, from bisection, it becomes apparent that the failure was introduced in #20944. Checkout 949aa201e265b51c0c3607de8c2b21b2d948534c and run the command above and you'll observe the same artifacts. (For this older commit, it may be necessary to place the .obj in a dummy .sdf file to facilitate the parsing functionality at the time of that commit.)

Note: this only happens with the *cloned* `RenderEngineVtk` engine. The original render engine produces correct images (which can be observed by looking at the test output for the `MultiMaterialObject`.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The crux of this was that rainbow_stripes.png has an alpha channel. When we enabled shadows in VTK, we swapped out rendering pipelines which treated meshes with those images differently. The test never really noticed that these changed. Changing the backend merely caused the change to manifest in a way that the test noticed (merely by happenstance).

The solution:
 - Remove the alpha channel.
 - Modify the test so it will be more sensitive to those kinds of changes.
   - Refactor the CompareImage code to use more widely (removing its behavior of saving the image to compare).
   - Make use of VTK's automatically save rendered image functionality.
   - Update callsites to CompareImage accordingly.

This does mean we don't have a test of transparent things. This is not a problem:
  1. We only accidentally had one before.
  2. We don't support transparency with any kind of uniformity or reliability.
  3. We need a test that tracks what we *do* support and document supported transparency appropriately (a follow up PR).

Resolves #22044

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053)

### CODE REVIEW

**Comment by sherm1** [comment]
Please choose a feature reviewer if this is ready, or switch to Draft.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-:-O9VYvBk0wTk_Smjl6-r:b-1tks9q)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-:-O9VZ-PO7-P4QEtOVl-R:b-safpmt)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-:-O9aMkMo6Ey6hOGRsBC3:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 309 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-O9aLkT-CSoZ5Oh0gRKU:-O9aLkT-CSoZ5Oh0gRKV:b6coheo) ([raw file](https://github.com/RobotLocomotion/drake/blob/faf218e906d9847dfb3bb2356c20dad362c59154/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L309)):*
> ```cpp
> // located at `ref_filename` to within the given tolerance.
> template <typename ImageType>
> void CompareImages(const ImageType& test_image, const std::string& ref_filename,
> ```

nit This is a resource path, not a filename.  Maybe "ref_resource" or "ref_resource_path" or "ref_respath" or something?



_Code quote:_
```cpp
ref_filename
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 996 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-O9aL92qCLp1Jw6CzDGc:-O9aL92qCLp1Jw6CzDGd:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/faf218e906d9847dfb3bb2356c20dad362c59154/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L996)):*
> ```cpp
>           "drake/geometry/render/test/meshes/rainbow_box.obj"))};
> 
>   // The camera has a smaller image (640 x 480), a narrower field of view (so
> ```

typo



_Suggestion:_
```cpp
480 x 360
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1040 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-O9aMcCL7_RqQGkmabyT:-O9aMcCL7_RqQGkmabyU:b-wwr62i) ([raw file](https://github.com/RobotLocomotion/drake/blob/faf218e906d9847dfb3bb2356c20dad362c59154/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1040)):*
> ```cpp
>     // PBR. OBJs get rendered using Phong materials. It leads to slightly
>     // different levels of illumination, requiring a bit more tolerance (about
>     // 10%). When looking at the images, they should be qualitatively similar.
> ```

BTW Another way to do this would be to use two different goal images (both committed into git), so that tolerance is tight in both cases.  Maybe that's better?  You can decide.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-:-O9oo7WG2XvB_PxD3E37:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1040 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-O9aMcCL7_RqQGkmabyT:-O9onc-W-dDcjRh-J55f:bxyrt2p) ([raw file](https://github.com/RobotLocomotion/drake/blob/faf218e906d9847dfb3bb2356c20dad362c59154/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1040)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Another way to do this would be to use two different goal images (both committed into git), so that tolerance is tight in both cases.  Maybe that's better?  You can decide.
</blockquote></details>

I'd considered that. In this case, I'm going for a note. If this test is too brittle in the future, we'll address it then.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22053#-:-O9pZ8c62trn_VxyUKDV:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
