### PR TITLE
Scs socp solver

### PR DESCRIPTION
**Pull request by hongkai-dai**
Enable SCS for second order conic program, and quadratic programming.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7508)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-Kzy3Xf6Xh1fMg5eDSHT:bll7v0f)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-2wFhFLfPK69jV3e0L:bzcj60u)*

**Comment by avalenzu** [comment]
Review pass done. Sorry for the delay!

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/scs_solver.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-HryTB8XTZV4uba3Y0:-L-HryTB8XTZV4uba3Y1:b-f8rqj5) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/scs_solver.cc#L20)):*
> ```cpp
> namespace solvers {
> namespace {
> std::vector<int> FindAllDecisionVariableIndices(
> ```

`FindAllDecisionVariableIndices` seems like it should just return a vector of consecutive integers from 0 to the number of constraints - 1. Could this just be `FindDecisionVariableIndices`? 

---

*[drake/solvers/scs_solver.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-IX2YY9pnbnmsuBCnC:-L-IX2YY9pnbnmsuBCnD:bvkd3js) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/scs_solver.cc#L105)):*
> ```cpp
>   // A QuadraticCost encodes cost of the form
>   //   0.5 zᵀQz + pᵀz + r
>   // Since SCS only supports linear cost, we consider to introduce a new slack
> ```

"we consider to introduce" -> "we introduce"

---

*[drake/solvers/scs_solver.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-IXVvYw2dTDxUTO2Zn:-L-IXVvYw2dTDxUTO2Zo:b-wtupy6) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/scs_solver.cc#L106)):*
> variable y, with the rotated Lorentz cone constraint

Maybe mention that y the Lorentz cone constraint implies that y is an upper bound of the cost, just to make the next sentence seem like less of a jump.

---

*[drake/solvers/test/scs_solver_test.cc, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-IYB-JHBMVpZuK3Ajx:-L-IYB-JHBMVpZuK3Ajy:b-rcpnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/test/scs_solver_test.cc#L156)):*
> ```cpp
>   ScsSolver scs_solver;
>   if (scs_solver.available()) {
>     SolveAndCheckSolution(scs_solver, 1.3e-3);
> ```

It would be nice to have some explanation of why all these tests have different tolerances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-IYhcCPNp-3zfUa_RR:bfp4dhj)*

**Comment by hongkai-dai** [comment]
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/scs_solver.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-HryTB8XTZV4uba3Y0:-L-IdHwCSvSgDKk8IjP9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/scs_solver.cc#L20)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

`FindAllDecisionVariableIndices` seems like it should just return a vector of consecutive integers from 0 to the number of constraints - 1. Could this just be `FindDecisionVariableIndices`? 
</blockquote></details>

Done.

---

*[drake/solvers/scs_solver.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-IX2YY9pnbnmsuBCnC:-L-IbCGm2EPaOLpMW-mP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/scs_solver.cc#L105)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

"we consider to introduce" -> "we introduce"
</blockquote></details>

Done.

---

*[drake/solvers/scs_solver.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-IXVvYw2dTDxUTO2Zn:-L-IbO1UcqWHyLUZ6GqI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/scs_solver.cc#L106)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> variable y, with the rotated Lorentz cone constraint

Maybe mention that y the Lorentz cone constraint implies that y is an upper bound of the cost, just to make the next sentence seem like less of a jump.
</blockquote></details>

Done.

---

*[drake/solvers/test/scs_solver_test.cc, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-IYB-JHBMVpZuK3Ajx:-L-IbrSwdFOuw8ONBfX_:b-a0xn99) ([raw file](https://github.com/robotlocomotion/drake/blob/e9159edc35865c93ae5bb8a6abe09fcd6fb3ce88/drake/solvers/test/scs_solver_test.cc#L156)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

It would be nice to have some explanation of why all these tests have different tolerances.
</blockquote></details>

Hmm, because the checks fail with smaller tolerance? 

SCS is inaccurate, that it does not try to satisfy the constraints to a high tolerance, as other solvers do. To make it worse, the constraints are normalized in SCS, even all the tests violate the normalized constraints by the same amount, it doesn't mean the same accuracy for the original un-normalized problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-IyA9mA_vrbfBs7BGM:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-IyUATa1rJJ7pdlYLk:b-vt9vbo)*

**Comment by soonho-tri** [comment]
Checkpoint.

---

Reviewed 8 of 10 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/cost.h, line 114 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-L78DcNguudh8hi9rg:-L-L78DcNguudh8hi9rh:b-mz80lg) ([raw file](https://github.com/robotlocomotion/drake/blob/bdb88864b0d9e7b317892dbaf215681f4c6cc275/drake/solvers/cost.h#L114)):*
> ```objc
>   ~QuadraticCost() override {}
> 
>   // Returns the symmetric matrix Q, as the Hessian of the cost.
> ```

BTW, did you mean to use `///` instead of `//`?

---

*[drake/solvers/cost.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-L6q4xpG8vquH43abI:-L-L6q4xpG8vquH43abJ:b-w1w1yg) ([raw file](https://github.com/robotlocomotion/drake/blob/bdb88864b0d9e7b317892dbaf215681f4c6cc275/drake/solvers/cost.h#L141)):*
> ```objc
>     }
> 
>     Q_ = new_Q;
> ```

Do we need to have `Q_ = (new_Q + new_Q.transpose()) / 2` to be consistent with the update in the constructor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-L8J7fE2PotdQvXHaM:by96gdd)*

**Comment by hongkai-dai** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/cost.h, line 114 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-L78DcNguudh8hi9rg:-L-LKbgN9JNX4goDoMFq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bdb88864b0d9e7b317892dbaf215681f4c6cc275/drake/solvers/cost.h#L114)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, did you mean to use `///` instead of `//`?
</blockquote></details>

Done.

---

*[drake/solvers/cost.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-L6q4xpG8vquH43abI:-L-LKcWcWmswCoNRPh4p:b-s5tguo) ([raw file](https://github.com/robotlocomotion/drake/blob/bdb88864b0d9e7b317892dbaf215681f4c6cc275/drake/solvers/cost.h#L141)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Do we need to have `Q_ = (new_Q + new_Q.transpose()) / 2` to be consistent with the update in the constructor?
</blockquote></details>

Done. Good catch! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508)*

**Comment by avalenzu** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508)*

**Comment by soonho-tri** [comment]
:lgtm: Thanks for the patience. PTAL the minor comments.

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/scs_solver.cc, line 45 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-X8q-u0S8o_Ut-aAu8:-L-X8q-u0S8o_Ut-aAu9:b-wlud30) ([raw file](https://github.com/robotlocomotion/drake/blob/89d5feb868615a023415db5f76afd8483371bd4b/drake/solvers/scs_solver.cc#L45)):*
> ```cpp
> // Add a rotated Lorentz cone constraint that A_cone * x + b_cone is in the
> // rotated Lorentz cone.
> // @param A_cone_triplets The triplets of non-zero entries in A_cone.
> ```

BTW, having only two `@param` entries out of seven parameters looks unusual. Is it because `A_cone_triplets` and `x_indices` do need extra explanations? 

---

*[drake/solvers/scs_solver.cc, line 480 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-XDUVkI0cQO03DzKr8:-L-XDUVkI0cQO03DzKr9:bo7oc6k) ([raw file](https://github.com/robotlocomotion/drake/blob/89d5feb868615a023415db5f76afd8483371bd4b/drake/solvers/scs_solver.cc#L480)):*
> ```cpp
> 
>   // `c` is the coefficient in the linear cost cᵀx
>   std::vector<double> c(num_x);
> ```

FYI, I don't think we need the following loop. If you still want to be explicit, you can have `std::vector<double> c(num_x, 0.0);` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-XE0mgiPr7PU7WE0JB:b-lfqbmo)*

**Comment by hongkai-dai** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/scs_solver.cc, line 45 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-X8q-u0S8o_Ut-aAu8:-L-XFB2gXw0BuugkeXjQ:b-hhua6y) ([raw file](https://github.com/robotlocomotion/drake/blob/89d5feb868615a023415db5f76afd8483371bd4b/drake/solvers/scs_solver.cc#L45)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, having only two `@param` entries out of seven parameters looks unusual. Is it because `A_cone_triplets` and `x_indices` do need extra explanations? 
</blockquote></details>

Because this is in the private interface, I did not document every variable.

---

*[drake/solvers/scs_solver.cc, line 480 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-XDUVkI0cQO03DzKr8:-L-XGAYn1eyCc2_URlul:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/89d5feb868615a023415db5f76afd8483371bd4b/drake/solvers/scs_solver.cc#L480)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, I don't think we need the following loop. If you still want to be explicit, you can have `std::vector<double> c(num_x, 0.0);` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508)*

**Comment by soonho-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/scs_solver.cc, line 45 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-L-X8q-u0S8o_Ut-aAu8:-L-XH0QI-XBhkRnIgCES:b-4hvi0m) ([raw file](https://github.com/robotlocomotion/drake/blob/89d5feb868615a023415db5f76afd8483371bd4b/drake/solvers/scs_solver.cc#L45)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Because this is in the private interface, I did not document every variable.
</blockquote></details>

Got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7508#-:-L-XQ98drHofeQb8e2EQ:b-l70wzf)*

**Pull request merged**
