### PR TITLE
Modified parameters names of RigidBodyLoop and RigidbodyActuator.

### LINKED ISSUE #2922: Modify API of RigidBodyActuator and RigidBodyLoop to not have parameters ending in "_in"
For background, see: https://reviewable.io/reviews/robotlocomotion/drake/2901#-KNXymWyP7H-j3K9N1_E

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #2922.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2923)

### CODE REVIEW

**Comment by sherm1** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 87 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-KNYMxdDXAPf_fweOg5g:-KNYMxdDXAPf_fweOg5h:921674605) ([raw file](https://github.com/robotlocomotion/drake/blob/45c9b72982cb82f5a03137503ffaeb8935d00c6d/CHANGELOG.md#L87)):*
> ```Markdown
> [#2779]: https://github.com/RobotLocomotion/drake/issues/2779
> [#2900]: https://github.com/RobotLocomotion/drake/issues/2900
> [#2920]: https://github.com/RobotLocomotion/drake/issues/2920
> ```

needs a newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923)*

**Comment by liangfok** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 87 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-KNYMxdDXAPf_fweOg5g:-KNYNRXU4wn1x0yxnOE5:1508991532) ([raw file](https://github.com/robotlocomotion/drake/blob/45c9b72982cb82f5a03137503ffaeb8935d00c6d/CHANGELOG.md#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> needs a newline
</details>
Done. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3062/ and is thus ready for review.

**Comment by liangfok** [comment]
+@amcastro-tri  for feature review.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-:-KNZxTtbdYoknMYiEODu:-715039275)*

**Comment by liangfok** [comment]
+@sherm1 for platform review.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-:-KN_1bEFViFDAEsrEVjj:960604000)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 2 of 6 files at r1, 3 of 4 files at r2, 1 of 4 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-:-KN_BeQTpQr_PqAdGulc:1058782226)*

**Comment by liangfok** [comment]
@sherm1: Thanks! Now waiting on @amcastro-tri for feature review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-:-KN_CagD9GTUI5hBYqCe:1776762310)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2923#-:-KNbVVz3oRTyyJQTRVVy:1417088721)*

**Pull request merged**
