### PR TITLE
[render_gltf_client] Add 16U PNG and TIFF depth support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Rendering software does **not** commonly support floating-point TIFFs, which are what we currently require for RPC depth images.

Such software **does** commonly have built-in support for 16-bit unsigned integer TIFF images.  This commit allows the RPC server to return unsigned 16-bit PNG or TIFF data for the depth image.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang I think this basically ready, except maybe for any missing comment polishing or missing test cases.  Would you like to take this over (or delegate it)?

**Comment by zachfang** [comment]
I created [a feature branch](https://github.com/zachfang/drake/tree/feature/16u-depth-support) on top of your modifications. I assume a better workflow is to merge it here before proceeding with the review.

One major change of mine is to support 16U PNG instead of 16U TIFF. As we are already in the 16U regime, I think PNG is probably more common. Another cosmetic change is to replace `16 bit` with `16-bit` since it's grammatically correct (I think) and it's what other files in Drake are using.

**Comment by zachfang** [comment]
FYI, I also tested the PNG loading branch against Anzu 9793. The plumbing and the visualization seem correct even though I still need to run some quantitative image differencing to confirm.

**Comment by jwnimmer-tri** [comment]
> I assume a better workflow is to merge it here before proceeding with the review.

Several strategies would work fine.  You could push changes here into the PR directly (but try to avoid force-pushes), or we could close this PR and you can open a new one under your account, if that's easier.  Either way, we can do a mutual feature-author review, where we each feature-review each other's contributions.

> One major change of mine is to support 16U PNG instead of 16U TIFF. As we are already in the 16U regime, I think PNG is probably more common.

I think adding PNG is fine.  I do think we should also support 16-bit integer TIFF -- really, I think we should support anything with the right number of channels (1) and channel depth (16-bit unsigned integer as millimeters, or 32-bit float as meters) to make life easier for the RPC implementers.

The only reason not to "extra" image types is the burden of the extra implementation or tests, and both here seem like a minuscule extra amount of work for us?

**Comment by zachfang** [comment]
Close #16456

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not review) 

:lgtm: co-feature / co-author.

+@rpoyner-tri for platform review per schedule, please.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205#-:-NGNkMDiCi7faMMUzJVl:bb67qe5)* status: 3 unresolved discussions, LGTM missing from assignees zachfang,rpoyner-tri(platform) (waiting on @rpoyner-tri and @zachfang)

___
*[`geometry/render_gltf_client/internal_render_client.cc` line 398 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGNj7KO4bzXXsahZf3J:-NGNj7KO4bzXXsahZf3K:b30i07e) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/internal_render_client.cc#L398)):*
> ```cpp
>       ReadPngFile(path, image_exporter);
>   } else if (ext == ".tiff") {
>       ReadTiffFile(path, image_exporter);
> ```

nit Wrong indentation



_Suggestion:_
```cpp
  if (ext == ".png") {
    ReadPngFile(path, image_exporter);
  } else if (ext == ".tiff") {
    ReadTiffFile(path, image_exporter);
```
___
*[`geometry/render_gltf_client/render_gltf_client_doxygen.h` line 254 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGNjX5YCP3YnSeda9fL:-NGNjX5Z2CTPC9tHGg3U:b-tncoch) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/render_gltf_client_doxygen.h#L254)):*
> ```objc
>     - A 16-bit integer single channel TIFF or PNG image.  The client will
>       interpret this rendering as units of millimeters.  Pixels at their maximum
>       value (2**16-1) will be interpreted as kTooFar (i.e., infinity).
> ```

nit In docs we can use Unicode, if you like.



_Suggestion:_
```objc
2¹⁶-1
```
___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN5m2X3G8L06w-IdL0:-NGNjuiw8jvXXnHO_-Vg:b23npxa) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L26)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Should we move this template to `system::sensors` (if it's useful, not specifically here) so that it's not buried in a test.cc file?
</blockquote></details>

When we have another test that wants that, then we could do that, sure.
___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN7LXP2HmW96HVkp5L:-NGNjyZH5apTRBr5ghB-:b-gd16nj) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L40)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Can I ask when this will actually be invoked and what exactly it will output, e.g., the entire pixel values within an image?
</blockquote></details>

If you edit `internal_sample_image_data.cc` to contain wrong answers and then re-run the unit test, you should see an example of this output.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),zachfang (waiting on @rpoyner-tri and @zachfang)

___
*[`geometry/render_gltf_client/internal_render_client.cc` line 398 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGNj7KO4bzXXsahZf3J:-NGNlKTz9KaClBC71VCd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/internal_render_client.cc#L398)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Wrong indentation
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/render_gltf_client_doxygen.h` line 254 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGNjX5YCP3YnSeda9fL:-NGNlL6f0Rya50Tehfsl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/render_gltf_client_doxygen.h#L254)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In docs we can use Unicode, if you like.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@zachfang technically we want your LGTM emoji here as co-feature / co-author, once you're satisfied.

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205#-:-NGNxnsQAheG4oap17Al:b-uwkowd)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN7LXP2HmW96HVkp5L:-NGNxU3S4NHbcw1x92Ya:b-6o8bkj) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you edit `internal_sample_image_data.cc` to contain wrong answers and then re-run the unit test, you should see an example of this output.
</blockquote></details>

For future reference, this is the output when I changed one of the depth values in the sample depth image.
```
eometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc:267: Failure
Expected equality of these values:
  depth_image
    Which is: 32-byte object <03-00 00-00 02-00 00-00 B0-DD 6D-6C E5-55 00-00 C8-DD 6D-6C E5-55 00-00 C8-DD 6D-6C E5-55 00-00>
  CreateTestDepthImage()
    Which is: 32-byte object <03-00 00-00 02-00 00-00 C0-D3 9A-6C E5-55 00-00 D8-D3 9A-6C E5-55 00-00 D8-D3 9A-6C E5-55 00-00>
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN7LXP2HmW96HVkp5L:-NGNzTi--Rrcnp7FR0fv:bgst05k) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L40)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

For future reference, this is the output when I changed one of the depth values in the sample depth image.
```
eometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc:267: Failure
Expected equality of these values:
  depth_image
    Which is: 32-byte object <03-00 00-00 02-00 00-00 B0-DD 6D-6C E5-55 00-00 C8-DD 6D-6C E5-55 00-00 C8-DD 6D-6C E5-55 00-00>
  CreateTestDepthImage()
    Which is: 32-byte object <03-00 00-00 02-00 00-00 C0-D3 9A-6C E5-55 00-00 D8-D3 9A-6C E5-55 00-00 D8-D3 9A-6C E5-55 00-00>
```
</blockquote></details>

That was from master, or this PR?

It's supposed to be much nicer in this PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN7LXP2HmW96HVkp5L:-NGO-uVwAdgn0qbC68Tk:b-z4ewmf) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That was from master, or this PR?

It's supposed to be much nicer in this PR.
</blockquote></details>

I see this on the PR:

```
geometry/render_gltf_client/test/internal_render_client_test.cc:530: Failure
Expected equality of these values:
  rgba
    Which is: 
Channel 0:
 0 10 20
30 40 50
Channel 1:
 1 11 21
31 41 51
Channel 2:
 2 12 22
32 42 52
Channel 3:
 3 13 23
33 43 53

  CreateTestColorImage(false)
    Which is: 
Channel 0:
 0 10 20
30 40 50
Channel 1:
 1 11 21
31 41 51
Channel 2:
 2 12 22
32 42 52
Channel 3:
  3  13  23
 33  43 222

[  FAILED  ] RenderClientTest.LoadColorImageGood (0 ms)
[ RUN      ] RenderClientTest.LoadColorImageBad
[       OK ] RenderClientTest.LoadColorImageBad (0 ms)
[ RUN      ] RenderClientTest.LoadDepth32FGood
geometry/render_gltf_client/test/internal_render_client_test.cc:567: Failure
Expected equality of these values:
  depth
    Which is: 
Channel 0:
0 1 2
3 4 5

  CreateTestDepthImage()
    Which is: 
Channel 0:
  0   1   2
  3   4 222

[  FAILED  ] RenderClientTest.LoadDepth32FGood (0 ms)
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN7LXP2HmW96HVkp5L:-NGOEelF2TYmgWaNKv2Z:b-cdvolc) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I see this on the PR:

```
geometry/render_gltf_client/test/internal_render_client_test.cc:530: Failure
Expected equality of these values:
  rgba
    Which is: 
Channel 0:
 0 10 20
30 40 50
Channel 1:
 1 11 21
31 41 51
Channel 2:
 2 12 22
32 42 52
Channel 3:
 3 13 23
33 43 53

  CreateTestColorImage(false)
    Which is: 
Channel 0:
 0 10 20
30 40 50
Channel 1:
 1 11 21
31 41 51
Channel 2:
 2 12 22
32 42 52
Channel 3:
  3  13  23
 33  43 222

[  FAILED  ] RenderClientTest.LoadColorImageGood (0 ms)
[ RUN      ] RenderClientTest.LoadColorImageBad
[       OK ] RenderClientTest.LoadColorImageBad (0 ms)
[ RUN      ] RenderClientTest.LoadDepth32FGood
geometry/render_gltf_client/test/internal_render_client_test.cc:567: Failure
Expected equality of these values:
  depth
    Which is: 
Channel 0:
0 1 2
3 4 5

  CreateTestDepthImage()
    Which is: 
Channel 0:
  0   1   2
  3   4 222

[  FAILED  ] RenderClientTest.LoadDepth32FGood (0 ms)
```
</blockquote></details>

Right, it's the output from this PR, but I copied from the wrong test, i.e., RenderEngineGltfClientTest.DoRenderDepthImage.

Now I can't figure out why the image diff output in `RenderEngineGltfClientTest` doesn't use the prettier format. Is there a special hook for RenderClinetTest (other than it's implemented in that file)? They both have a similar call: `EXPECT_EQ(depth_image, CreateTestDepthImage());`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18205#-NGN7LXP2HmW96HVkp5L:-NGOGMOZ6kMN19J9gMYf:b-xfovng) ([raw file](https://github.com/robotlocomotion/drake/blob/c7df29ee4e240a06bf7fda7a7ff3c95bc50481a2/geometry/render_gltf_client/test/internal_render_client_test.cc#L40)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Right, it's the output from this PR, but I copied from the wrong test, i.e., RenderEngineGltfClientTest.DoRenderDepthImage.

Now I can't figure out why the image diff output in `RenderEngineGltfClientTest` doesn't use the prettier format. Is there a special hook for RenderClinetTest (other than it's implemented in that file)? They both have a similar call: `EXPECT_EQ(depth_image, CreateTestDepthImage());`

</blockquote></details>

Yes, this printer would _only_ be used for this one test file, because it's in this cc file and not in a common header.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18205#-:-NGOUWxx42ggXzkQHEyb:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),zachfang (waiting on @jwnimmer-tri)

**Pull request merged**
