### PR TITLE
Remove cost from MathematicalProgram

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

I will add RemoveConstraint in my next PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311#-:-Mddu8nK9sQpwiXngWqa:bese7wn)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdwjRg78c7M8HXGE_I7:-MdwjRg84c89FfRiKj_Z:b-hfdjtz) ([raw file](https://github.com/robotlocomotion/drake/blob/1288dd7866dfccc63642074f946a3b9c98d1ad3c/solvers/mathematical_program.h#L3127)):*
> ```objc
>    * See @ref remove_cost_constraint for more details.
>    */
>   void RemoveQuadraticCost(const Binding<QuadraticCost>& cost);
> ```

Naively, I would have expected that `Binding<QuadraticCost>` is implicitly convertible to a `Binding<Cost>` in which case we only need the last overload (below) and we could nix the Linear and Quadratic overloads.  If we _do_ need these two extra overloads, then I'd expect we need `PolynomialCost` and any others.  Can you help clarify for me what's going on here?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdwjRg78c7M8HXGE_I7:-MdwojJnEwems_L_TejC:b7prrtp) ([raw file](https://github.com/robotlocomotion/drake/blob/1288dd7866dfccc63642074f946a3b9c98d1ad3c/solvers/mathematical_program.h#L3127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Naively, I would have expected that `Binding<QuadraticCost>` is implicitly convertible to a `Binding<Cost>` in which case we only need the last overload (below) and we could nix the Linear and Quadratic overloads.  If we _do_ need these two extra overloads, then I'd expect we need `PolynomialCost` and any others.  Can you help clarify for me what's going on here?
</blockquote></details>

In MathematicalProgram, we store `PolynomialCost` objects as generic `Cost` in `generic_costs_`. So I didn't add `RemovePolynomialCost`. Would you suggest to add `RemovePolynomialCost`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdwjRg78c7M8HXGE_I7:-MdwreDmEDp4QFpH6Ypw:bgisoto) ([raw file](https://github.com/robotlocomotion/drake/blob/1288dd7866dfccc63642074f946a3b9c98d1ad3c/solvers/mathematical_program.h#L3127)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

In MathematicalProgram, we store `PolynomialCost` objects as generic `Cost` in `generic_costs_`. So I didn't add `RemovePolynomialCost`. Would you suggest to add `RemovePolynomialCost`?
</blockquote></details>

No, my desire is to _remove_ this and the prior method if we don't need them, leaving only the `RemoveCost(Binding<Cost>)`.  I pulled this PR locally and marked these two methods as private and the unit test still passes.  Therefore, I'm not clear on why these two methods are useful for the end-user?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdwjRg78c7M8HXGE_I7:-MdxAn5nBkjMvwzzH8qW:b-h8v6ro) ([raw file](https://github.com/robotlocomotion/drake/blob/1288dd7866dfccc63642074f946a3b9c98d1ad3c/solvers/mathematical_program.h#L3127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No, my desire is to _remove_ this and the prior method if we don't need them, leaving only the `RemoveCost(Binding<Cost>)`.  I pulled this PR locally and marked these two methods as private and the unit test still passes.  Therefore, I'm not clear on why these two methods are useful for the end-user?
</blockquote></details>

I added `RemoveLinearCost` for the python binding part. If I only have `RemoveCost`, then the following code not work
```py
linear_cost = prog.AddCost(x[0] + x[1])
prog.RemoveCost(linear_cost)
```
It complains
```
TypeError: RemoveCost(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, arg0: drake::solvers::Binding<drake::solvers::Cost>) -> None

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7fa9e4b33e70>, <pydrake.solvers.mathematicalprogram.Binding_LinearCost object at 0x7fa9e4b33db0>
```
I don't know enough about converting Binding_LinearCost to drake::solvers::Binding<drake::solvers::Cost>. What would be your suggestion? Thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdwjRg78c7M8HXGE_I7:-MdxHb_sATjAdZYar-vb:b5rzuwo) ([raw file](https://github.com/robotlocomotion/drake/blob/1288dd7866dfccc63642074f946a3b9c98d1ad3c/solvers/mathematical_program.h#L3127)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added `RemoveLinearCost` for the python binding part. If I only have `RemoveCost`, then the following code not work
```py
linear_cost = prog.AddCost(x[0] + x[1])
prog.RemoveCost(linear_cost)
```
It complains
```
TypeError: RemoveCost(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, arg0: drake::solvers::Binding<drake::solvers::Cost>) -> None

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7fa9e4b33e70>, <pydrake.solvers.mathematicalprogram.Binding_LinearCost object at 0x7fa9e4b33db0>
```
I don't know enough about converting Binding_LinearCost to drake::solvers::Binding<drake::solvers::Cost>. What would be your suggestion? Thanks!

</blockquote></details>

Ah, that's https://github.com/RobotLocomotion/drake/issues/15272 biting you.

Until that bug is fixed, I bet you could change the bindings to declare three separate overloads (all with the same _function name_, just with different argument types) that all call the same underlying C++ member function.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdwjRg78c7M8HXGE_I7:-MdyiSyZ1vWUwBRUn_0L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1288dd7866dfccc63642074f946a3b9c98d1ad3c/solvers/mathematical_program.h#L3127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, that's https://github.com/RobotLocomotion/drake/issues/15272 biting you.

Until that bug is fixed, I bet you could change the bindings to declare three separate overloads (all with the same _function name_, just with different argument types) that all call the same underlying C++ member function.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint.  Waiting on a few bigger questions before I start in on the unit test.

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311#-:-MdyonUw-yER0u-bUOif:bu60uqo)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3094 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdyklaM2CTakuPtkjnv:-MdyklaM2CTakuPtkjnw:b-mr1pix) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3094)):*
> ```objc
>   //@}
> 
>   /**
> ```

Working

I still need to review these docs in html format.
___
*[solvers/mathematical_program.h, line 3100 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdymfvk3KuGWQlyhsLC:-Mdymfvl80jWjDLlhTKW:b7voxez) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3100)):*
> If this program doesn't contain this cost, then the code does nothing.

On first read, I am skeptical that we want to define the contract here to ignore stuff that didn't seem to be added the first place.  Broadly speaking, failing fast is preferable, and especially here it seems odd that the user would blindly throw costs at us to remove, without expecting that they were ever added?

My intuition is that we want an exception in this case, though I could also be convinced that returning a success boolean would also be valid.

Can you explain your use cases related to removing costs that don't actually exist?
___
*[solvers/mathematical_program.h, line 3119 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdykWBhCy_PRChhDOzx:-MdykWBhCy_PRChhDOzy:byyqz4d) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3119)):*
> ```objc
> 
>   // @{
>   /** Removes costs @p cost from this mathematical program.
> ```

nit Typo s/costs/cost/
___
*[solvers/mathematical_program.h, line 3130 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdykvJ0Cg0z_s4ffi7p:-MdykvJ0Cg0z_s4ffi7q:blfeo5g) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3130)):*
> ```objc
>   // Remove a cost or constraint @p removal stored inside this mathematical
>   // program in @p existings. If @p removal does not belong to @p existing,
>   // then do nothing. If @p removal appears multiple times in @p existing, then
> ```

nit Typo s/existing/existings/ in several places.
___
*[solvers/mathematical_program.cc, line 1414 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdynWlCCAWAOOj7o8tD:-MdynWlCCAWAOOj7o8tE:bv2m68f) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1414)):*
> ```cpp
>   for (auto it = existings->begin(); it != existings->end();) {
>     bool same_cost = true;
>     if (it->evaluator().get() == removal.evaluator().get()) {
> ```

We have `Binding::operator==` already available.  It seems like we should use it here, or if we can't then we have to explain very clearly why not.

If the only problem is the `DRAKE_DEMAND` embedded inside of it, well, that's a defect in the first place.  The equality operator is not supposed to fail, it's just supposed to return false.
___
*[solvers/mathematical_program.cc, line 1430 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdynxjb-mrBii9kEjYk:-Mdynxjb-mrBii9kEjYl:bljqqkx) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1430)):*
> ```cpp
>     } else {
>       ++it;
>     }
> ```

This seems like https://en.cppreference.com/w/cpp/algorithm/remove written out longhand?  Can we use the std algorithm instead?
___
*[solvers/mathematical_program.cc, line 1432 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdyoDno1rAW4EJiEdhR:-MdyoDno1rAW4EJiEdhS:b-stgu4z) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1432)):*
> ```cpp
>     }
>   }
>   auto it_capability = required_capabilities_.find(affected_capability);
> ```

It seems wasteful to do a `find` here when the existings are still non-empty.  Since `erase` has an overload that takes a value (not iterator) anyway, and erasing a non-existent unordered_set element is not an error, something like this seems both cleaner and more efficient:

```c++
if (existings->empty()) {
  required_capabilities_.erase(affected_capability);
}
```
___
*[solvers/mathematical_program.cc, line 1440 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdymLxa1bQuX69ZT1NW:-MdymLxa1bQuX69ZT1NX:b-9xvzag) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1440)):*
> ```cpp
> void MathematicalProgram::RemoveCost(const Binding<Cost>& cost) {
>   Cost* cost_evaluator = cost.evaluator().get();
>   if (dynamic_cast<QuadraticCost*>(cost_evaluator)) {
> ```

nit All of these dynamic cases violate GSG, though the pattern is endemic in MathematicalProgram so I don't think it should block process here.  However, please cite #8349 in a TODO here so that we can fix it later.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3100 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdymfvk3KuGWQlyhsLC:-MdzDIWM0UpjPYvwvcxX:bf9d2uz) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> If this program doesn't contain this cost, then the code does nothing.

On first read, I am skeptical that we want to define the contract here to ignore stuff that didn't seem to be added the first place.  Broadly speaking, failing fast is preferable, and especially here it seems odd that the user would blindly throw costs at us to remove, without expecting that they were ever added?

My intuition is that we want an exception in this case, though I could also be convinced that returning a success boolean would also be valid.

Can you explain your use cases related to removing costs that don't actually exist?
</blockquote></details>

How about changing the return value to the number of cost being removed? The user can throw an error if he/she wants, when the return value is 0.
___
*[solvers/mathematical_program.cc, line 1414 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdynWlCCAWAOOj7o8tD:-MdzEjfQ0_N6iNihnyHd:bkpnv7e) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1414)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We have `Binding::operator==` already available.  It seems like we should use it here, or if we can't then we have to explain very clearly why not.

If the only problem is the `DRAKE_DEMAND` embedded inside of it, well, that's a defect in the first place.  The equality operator is not supposed to fail, it's just supposed to return false.
</blockquote></details>

Done. Good call, I forgot we have operator==.
___
*[solvers/mathematical_program.cc, line 1430 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdynxjb-mrBii9kEjYk:-MdzFeo83dfv_rKJmTIc:b2363j0) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1430)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems like https://en.cppreference.com/w/cpp/algorithm/remove written out longhand?  Can we use the std algorithm instead?
</blockquote></details>

std::remove won't change the size of the vector. So after I call std::remove, the last few entries of `existings` will just contain garbage values?
___
*[solvers/mathematical_program.cc, line 1432 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdyoDno1rAW4EJiEdhR:-MdzNYHfDiIje6Y1M_29:b-8u22ks) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1432)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems wasteful to do a `find` here when the existings are still non-empty.  Since `erase` has an overload that takes a value (not iterator) anyway, and erasing a non-existent unordered_set element is not an error, something like this seems both cleaner and more efficient:

```c++
if (existings->empty()) {
  required_capabilities_.erase(affected_capability);
}
```
</blockquote></details>

Done. I see, I didn't know erasing a non-existent unordered_set element is not an error.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 3100 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdymfvk3KuGWQlyhsLC:-MdzQxJ09LxtIVPvepbp:b-gt4ax5) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3100)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

How about changing the return value to the number of cost being removed? The user can throw an error if he/she wants, when the return value is 0.
</blockquote></details>

That's fine.  It means within Drake code we'll have to add a check after every call to RemoveCost in our own code to confirm that it worked, but if you need to enable the use case of ignoring errors sometimes, then that's probably the best we can do.
___
*[solvers/mathematical_program.h, line 3123 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdzRC4C86EduZE4p0J0:-MdzRC4C86EduZE4p0J1:b-lb44sy) ([raw file](https://github.com/robotlocomotion/drake/blob/d073e03d3af5ccf14024455434bdd79b2324db74/solvers/mathematical_program.h#L3123)):*
> ```objc
>    * @return number of cost objects removed from this program. If this program
>    * doesn't contain @p cost, then return 0. If this program contains multiple
>    * @p cost objects, then return the repeatition of @p cost in this program.
> ```

nit Typo `repeatition`
___
*[solvers/mathematical_program.h, line 3136 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdzREqxBr4dN5qGBNif:-MdzREqxBr4dN5qGBNig:bq3wzfd) ([raw file](https://github.com/robotlocomotion/drake/blob/d073e03d3af5ccf14024455434bdd79b2324db74/solvers/mathematical_program.h#L3136)):*
> ```objc
>   // all matching terms are removed. After removing @p removal, we check if we
>   // need to erase @p affected_capability from required_capabilities_.
>   // @return The number of @p removal object in @p existins.
> ```

nit Typo `existins`
___
*[solvers/mathematical_program.cc, line 1430 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdynxjb-mrBii9kEjYk:-MdzRXXV1Answ7JNVfoL:b-7d1f4a) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1430)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

std::remove won't change the size of the vector. So after I call std::remove, the last few entries of `existings` will just contain garbage values?
</blockquote></details>

Look at the example at the end of that page.  We'd call `erase` after `remove_if`.

(Our `DrakeLcm::Subscribe` function has another example.)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 1430 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Mdynxjb-mrBii9kEjYk:-Mdzg0ea1vp9scLB-rxm:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.cc#L1430)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Look at the example at the end of that page.  We'd call `erase` after `remove_if`.

(Our `DrakeLcm::Subscribe` function has another example.)
</blockquote></details>

Done. Thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311#-:-Me0MRp12xzLUWBWld0z:b-n37teh)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 3094 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15311#-MdyklaM2CTakuPtkjnv:-Me0Kapu4wAps1nHE0HI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d827e03af07c83054c2f4f0b185c06472894410f/solvers/mathematical_program.h#L3094)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I still need to review these docs in html format.
</blockquote></details>

Done.
___
*[solvers/mathematical_program.h, line 3114 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me0Jlqm82kWpM2pSC8l:-Me0Jlqm82kWpM2pSC8m:bp4xw10) ([raw file](https://github.com/robotlocomotion/drake/blob/029b2c33d973590a4fd60cba31e1b564a3cfa235/solvers/mathematical_program.h#L3114)):*
> ```objc
>    * prog.RemoveCost(cost1);
>    * std::cout << prog.linear_costs()[0].evaluator().get() ==
>    * cost2.evaluator().get() << "\n";  // This will print true.
> ```

nit Especially with the line wrap, this statement is difficult to read.  Maybe this:

```c++
// This will print true.
std::cout << (prog.linear_costs()[0] == cost2) << "\n";
```
___
*[solvers/mathematical_program.h, line 3120 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me0KShq70in3w2eK9I6:-Me0KShq70in3w2eK9I7:b8yaxa3) ([raw file](https://github.com/robotlocomotion/drake/blob/029b2c33d973590a4fd60cba31e1b564a3cfa235/solvers/mathematical_program.h#L3120)):*
> ```objc
>   // @{
>   /** Removes @p cost from this mathematical program.
>    * See @ref remove_cost_constraint for more details.
> ```

nit Doxygen doesn't auto-title this link, we need to provide one:

```
See @ref remove_cost_constraint "Remove costs or constraints"
for more details.
```
___
*[solvers/mathematical_program.h, line 3122 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me0K9Pf5CQE0SVp5zIU:-Me0K9Pf5CQE0SVp5zIV:b-dysf2t) ([raw file](https://github.com/robotlocomotion/drake/blob/029b2c33d973590a4fd60cba31e1b564a3cfa235/solvers/mathematical_program.h#L3122)):*
> ```objc
>    * See @ref remove_cost_constraint for more details.
>    * @return number of cost objects removed from this program. If this program
>    * doesn't contain @p cost, then return 0. If this program contains multiple
> ```

nit s/return/returns/ in the prose.

Ditto on the next line.
___
*[solvers/test/mathematical_program_test.cc, line 3304 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me0MKxMDTKqMbyomrPc:-Me0MKxMDTKqMbyomrPd:b-9md2iy) ([raw file](https://github.com/robotlocomotion/drake/blob/029b2c33d973590a4fd60cba31e1b564a3cfa235/solvers/test/mathematical_program_test.cc#L3304)):*
> ```cpp
>   auto cost3 = prog->AddCost(cost1.evaluator(), cost3_vars);
>   EXPECT_EQ(prog->RemoveCost(cost1), 1);
>   EXPECT_EQ(program_costs->size(), 1u);
> ```

nit We might as well check `EXPECT_GT(prog->required_capabilities().count(affected_capability), 0);` here again, if only for consistency?
___
*[solvers/test/mathematical_program_test.cc, line 3310 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me0LYat7hMRwsi04VwC:-Me0LYat7hMRwsi04VwD:b-hbrb4a) ([raw file](https://github.com/robotlocomotion/drake/blob/029b2c33d973590a4fd60cba31e1b564a3cfa235/solvers/test/mathematical_program_test.cc#L3310)):*
> ```cpp
> GTEST_TEST(TestMathematicalProgram, RemoveLinearCost) {
>   MathematicalProgram prog;
>   auto x = prog.NewContinuousVariables<3>();
> ```

nit All of these tests declare 3 variables, but then only use 2 of them in the expressions, and I'm unclear why.  Perhaps add a comment?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/test/mathematical_program_test.cc, line 3310 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me0LYat7hMRwsi04VwC:-Me126wV6lT40sfSk8Eh:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/029b2c33d973590a4fd60cba31e1b564a3cfa235/solvers/test/mathematical_program_test.cc#L3310)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit All of these tests declare 3 variables, but then only use 2 of them in the expressions, and I'm unclear why.  Perhaps add a comment?
</blockquote></details>

Done, good call.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@soonho-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311#-:-Me16AjI3MgeLUOtiu3z:balbw5e)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, 1 of 4 files at r5, 1 of 2 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311#-:-Me1hAFm84LRKyBp1GNJ:bnfp4nl)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 3099 at r7](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me1WE87-9j_a3GpHADk:-Me1WE87-9j_a3GpHADl:bgfes8s) ([raw file](https://github.com/robotlocomotion/drake/blob/3da9c9421ed1e2e5ddd03f02e9c069b8d56361a0/solvers/mathematical_program.h#L3099)):*
> ```objc
>    * Removes costs or constraints from this program. If this program contains
>    * multiple costs/constraints objects matching the given argument, then all of
>    * these costs/constraints are removed. If this program doesn't contain this
> ```

nit, `If 'this' program doesn't contain 'this' cost` => `If this program doesn't contain the specified cost`
___
*[solvers/mathematical_program.h, line 3132 at r7](https://reviewable.io/reviews/robotlocomotion/drake/15311#-Me1doup3YZPq1Kbzzgq:-Me1doup3YZPq1Kbzzgr:bw0h45v) ([raw file](https://github.com/robotlocomotion/drake/blob/3da9c9421ed1e2e5ddd03f02e9c069b8d56361a0/solvers/mathematical_program.h#L3132)):*
> ```objc
>   static void AppendNanToEnd(int new_var_size, Eigen::VectorXd* vector);
> 
>   // Remove a cost or constraint @p removal stored inside this mathematical
> ```

nit, IMO, `inside this mathematical program` part is redundant and makes it difficult to understand.  How about the following?

```
// Removes a binding of a cost/constraint, @p removal, from a given vector of bindings, @p existings.
```

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15311)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
