### PR TITLE
Make DirectTrajectoryOptimization into an abstract class, as in Matlab.

### PR DESCRIPTION
**Pull request by Lucy-tri**
In the test, create an instance of DirectTrajectoryOptimization.
Run Clang format.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3197)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@sammy-tri for feature review please.

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYrpJLCh7cWNfxFE2T:-KPYrpJLCh7cWNfxFE2U:bsvqyoo) ([raw file](https://github.com/robotlocomotion/drake/blob/ffff51f4e35a7a8a6ddffb6436ae6f6206e6ad31/drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h#L26)):*
> ```objc
>                                double trajectory_time_upper_bound);
> 
>   void AddDynamicConstraint(
> ```

Should we go ahead and move this into the .cc file since it's not templated anymore?

---

*[drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYs-n-n90aISutIlZN:-KPYs-n-n90aISutIlZO:bgjgyx4) ([raw file](https://github.com/robotlocomotion/drake/blob/ffff51f4e35a7a8a6ddffb6436ae6f6206e6ad31/drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h#L54)):*
> ```objc
>       !std::is_convertible<F, std::shared_ptr<Constraint>>::value,
>       std::shared_ptr<Constraint>>::type
>   AddRunningCost(F&& f) {
> ```

I think this helper/overload should move to the parent class?

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYreOFlu_agqgBR8NV:-KPYreOGyyaHTnOIIY0Z:b4ij0se) ([raw file](https://github.com/robotlocomotion/drake/blob/ffff51f4e35a7a8a6ddffb6436ae6f6206e6ad31/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L22)):*
> ```objc
>  *  addRunningCost()
>  * and
>  *  addDynamicConstraints()
> ```

Capitalization differs from actual method name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYrpJLCh7cWNfxFE2T:-KPZGgDhC-0si96S0dzm:b-zdu9mn) ([raw file](https://github.com/robotlocomotion/drake/blob/e00d435298ddfc845c88745d48da7229dcc81b7f/drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h#L26)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Should we go ahead and move this into the .cc file since it's not templated anymore?
</details>
Done, thanks for catching that.

---

*[drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYs-n-n90aISutIlZN:-KPZGjgbEIEC2B8c2nEI:b99vy1m) ([raw file](https://github.com/robotlocomotion/drake/blob/e00d435298ddfc845c88745d48da7229dcc81b7f/drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h#L54)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think this helper/overload should move to the parent class?
</details>
Done. Removed comment since it's now commented in parent class. 

---

*[drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYreOFlu_agqgBR8NV:-KPZGa7pQyuAGmPe6sB5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e00d435298ddfc845c88745d48da7229dcc81b7f/drake/solvers/trajectoryOptimization/direct_trajectory_optimization.h#L22)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Capitalization differs from actual method name.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYs-n-n90aISutIlZN:-KPZV2YMeGUE4NiRjLLJ:b6vo3sc) ([raw file](https://github.com/robotlocomotion/drake/blob/e00d435298ddfc845c88745d48da7229dcc81b7f/drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h#L54)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Done. Removed comment since it's now commented in parent class. 
</details>
I don't think we need this code in the child at all...  Shouldn't the declaration in the parent be sufficient?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197)*

**Comment by Lucy-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-KPYs-n-n90aISutIlZN:-KPnfYzl46SuzsSYj3Sd:bxoi055) ([raw file](https://github.com/robotlocomotion/drake/blob/e00d435298ddfc845c88745d48da7229dcc81b7f/drake/solvers/trajectoryOptimization/dircol_trajectory_optimization.h#L54)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I don't think we need this code in the child at all...  Shouldn't the declaration in the parent be sufficient?
</details>
Right. Had to rename this to AddRunningCostFunc(F&& f) to avoid a C++ name confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-:-KPnhQMLKEMiLR4H0bZx:bnfp4nl)*

**Comment by Lucy-tri** [comment]
+@sherm1  for platform review, please. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-:-KPnhyjm0n7GRO6XMG3R:bcmopha)*

**Comment by sherm1** [comment]
Apologies, but I must pass this over to our illustrious Tuesday platform reviewer, +@david-german-tri -@sherm1.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-:-KPpY3LTMpPRyPM9Zexh:b-b7sz18)*

**Comment by david-german-tri** [comment]
:lgtm: Sorry for the delay!

---

Reviewed 1 of 4 files at r3, 4 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3197#-:-KPt3yBAdFCfvKRJbctb:b-8yidu2)*

**Pull request merged**
