### PR TITLE
pydrake: Remove catching of deprecation errors in `.all` modules

### LINKED ISSUE #11363: pydrake attic shims fail to generate warnings
In #11358, I removed the attic shims for pydrake import paths, but then in #11361 we put them back, because `underactuated` builds were broken and apparently had not been triggering the deprecation warnings.  Probably users other than underactuated could have experienced the same breaks.

We should figure out if indeed the warnings were not triggering, and then try to make them trigger again.  Maybe even push back the date beyond 2019-06-01.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #11363

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11645)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Maybe a simpler counter-proposal is to always and immediately omit the deprecated name from `.all` as soon as it's deprecated.  Then we never need to nerf any warnings?

**Comment by EricCousineau-TRI** [comment]
That would be beautiful! Caveat is that `.all` has much sharper edges, but would be nice to put failure solely on that.
Lemme try that out.

**Comment by EricCousineau-TRI** [comment]
Done. (Reformulated)

**Comment by EricCousineau-TRI** [comment]
To (try to) answer your earlier question:

> What is the case where importing via all leads off a cliff without any warnings?

In Russ's case, it was a module forwarding alias (`(old) pydrake.multibody.rigid_body_tree ==> (new) pydrake.attic.multibody.rigid_body_tree`), where later import of the module was suppressed because the module was already in memory.

The run-down was:
1. Some code imported `pydrake.all`, which imported `(old)`, and swallowed the deprecation used in the module.
2. Some later code imported `(old)`; it was already in memory, so regardless of the deprecation statement being there, it didn't get executed again. (It would have triggered if `reload(old)` had been called.)

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/11645#-LhKzDQv5Z4HrwfLWq1L:-Li8lj6_4oGnjvG1Jr3b:b-uxbhdb) (no related file):*
EC:
> In Russ's case, it was a module forwarding alias ((old) pydrake.multibody.rigid_body_tree ==> (new) pydrake.attic.multibody.rigid_body_tree), where later import of the module was suppressed because the module was already in memory.
>
> The run-down was:
> 
> Some code imported pydrake.all, which imported (old), and swallowed the deprecation used in the module.
> Some later code imported (old); it was already in memory, so regardless of the deprecation statement being there, it didn't get executed again. (It would have triggered if reload(old) had been called.)

---

**Comment by jwnimmer-tri** [comment]
CI shows the all_test as failing.

**Comment by jwnimmer-tri** [comment]
I see now that I was asked for platform review, not feature, but I ended up doing a more feature-like review.  I think this changed out enough that +@sammy-tri for platform review would make sense for an extra set of eyes.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri -@sammy-tri for platform review per schedule, please.

**Pull request merged**
