### PR TITLE
Removed some "using namespace" lines from SDF parser.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3437)

### CODE REVIEW

**Comment by liangfok** [comment]
Seemingly unrelated but extremely suspicious CI Error:

https://drake-jenkins.csail.mit.edu/job/experimental/4590/compiler=gcc,label=linux,type=release/

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3437#-:-KR_gQBQPNYrSVUMQ82H:b-ms2lve)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
Platform :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3437#-:-KRaDdUAIJnozgbwCgm4:b8qx53o)*

**Comment by jwnimmer-tri** [comment]
Using override-merge.  The windows build failed with some kind of flake after all of the tests had passed, and this PR seems unlikely to have windows-specific failure modes.

**Comment by liangfok** [comment]
Many thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3437#-:-KRaHr9j0LhXJ-h17XgO:b-adxy90)*

**Pull request merged**
