### PR TITLE
Add unit length constraint on quaternion variables.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141#-:-MIPXMMWDvTYLl4nBczH:b-uss1yj)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@rpoyner-tri for platform review.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141#-:-MIz26w-DDRr1cK2oXyI:bcpyunn)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[multibody/inverse_kinematics/unit_quaternion_constraint.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIy8avX5pOYU870wc_1:-MIy8AgI-2JSYhYlTpgB:bbz90l1) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.h#L41)):*
> ```objc
> 
> /**
>  * Add unit length constraint to all the variables representing quaternion in
> ```

nit: s/constraint/constraints/
___
*[multibody/inverse_kinematics/unit_quaternion_constraint.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyAUZIB7J8ft2Juv61:-MIyAUZIB7J8ft2Juv62:bbz90l1) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.h#L44)):*
> ```objc
>  * `q_vars`. Namely the quaternions for floating base joints in `plant` will be
>  * enforced to have a unit length.
>  * @param plant The plant on which we impose the unit quaternion constraint.
> ```

nit: s/constraint/constraints/
___
*[multibody/inverse_kinematics/unit_quaternion_constraint.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyAWhc-GXGjfu_8rYV:-MIyAWhc-GXGjfu_8rYW:b-851h6r) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.h#L47)):*
> ```objc
>  * @param q_vars The decision variables for the generalized position of the
>  * plant.
>  * @param prog The unit quaternion constraint is added to this prog.
> ```

nit: s/constraint is/constraints are/
___
*[multibody/inverse_kinematics/unit_quaternion_constraint.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyAjELA83av2lwvlgV:-MIyAjEM-UHwqkgBt53d:b-icczhg) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.h#L53)):*
> ```objc
>     const MultibodyPlant<T>& plant,
>     const Eigen::Ref<const VectorX<symbolic::Variable>>& q_vars,
>     solvers::MathematicalProgram* prog) {
> ```

Does this implementation need to be in the header?
___
*[multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyYJAfBsuy--cyu3sn:-MIyYJAfBsuy--cyu3so:bu0y20f) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc#L47)):*
> ```cpp
>   const auto result = solvers::Solve(prog, q_val);
>   EXPECT_TRUE(result.is_success());
>   EXPECT_NEAR(result.GetSolution(q.head<4>()).norm(), 1, 1E-5);
> ```

This feels like a pretty loose tolerance - what's keeping it from being tighter?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending open discussion fixes

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141#-:-MIzCI9RDXkCR_on20Tj:b1jvqa1)* status: 5 unresolved discussions (waiting on @hongkai-dai)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141)* status: 5 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/inverse_kinematics/unit_quaternion_constraint.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIzYYlA3D3eBDEYyhxk:-MIzYYlB3fjibpiy7GnK:b-77mcv4) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.cc#L21)):*
> ```cpp
>     const Eigen::Ref<const VectorX<symbolic::Variable>>& x,
>     VectorX<symbolic::Expression>* y) const {
>   DoEvalGeneric(x, y);
> ```

BTW, this method is not reached by unit tests.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141)* status: 2 unresolved discussions (waiting on @avalenzu)

___
*[multibody/inverse_kinematics/unit_quaternion_constraint.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyAjELA83av2lwvlgV:-MJ-ivBe5FysewY9GtEK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.h#L53)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Does this implementation need to be in the header?
</blockquote></details>

Done.
___
*[multibody/inverse_kinematics/unit_quaternion_constraint.cc, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIzYYlA3D3eBDEYyhxk:-MJ-jqi51aXUMaUq6MSU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/unit_quaternion_constraint.cc#L21)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, this method is not reached by unit tests.
</blockquote></details>

Done.
___
*[multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyYJAfBsuy--cyu3sn:-MJ-jsO96gR9tsvONCTl:b-lso1ra) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc#L47)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

This feels like a pretty loose tolerance - what's keeping it from being tighter?
</blockquote></details>

The solver accuracy is usually just 1E-6. To be safe I choose a larger tolerance than the solver accuracy.

**Review by avalenzu — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),avalenzu

___
*[multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14141#-MIyYJAfBsuy--cyu3sn:-MJ27kbj7VpRbYE_7NB_:b-4hvi0m) ([raw file](https://github.com/robotlocomotion/drake/blob/a49c5004ed37fc2d2f32ce8aa2271cf6340fda56/multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The solver accuracy is usually just 1E-6. To be safe I choose a larger tolerance than the solver accuracy.
</blockquote></details>

Got it.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),avalenzu

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14141)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),avalenzu

**Pull request merged**
