### PR TITLE
Adds python bindings for rimless wheel example.

### PR DESCRIPTION
**Pull request by RussTedrake**
(also adds the last line of documentation request from @edrumwri).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8522)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for both reviews, please

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8522#-:-L9KafBl8JOOLRgqrVz5:b7dx0uv)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/examples/rimless_wheel_py.cc, line 9 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8522#-L9L73WL4iD4cw6ML_wS:-L9L73WL4iD4cw6ML_wT:b4dhqxc) ([raw file](https://github.com/robotlocomotion/drake/blob/030b00b2cbf2998b550e3013c4b207abfb80d171/bindings/pydrake/examples/rimless_wheel_py.cc#L9)):*
> ```cpp
> #include "drake/examples/rimless_wheel/rimless_wheel.h"
> 
> using std::make_unique;
> ```

BTW, all three `using` statements are unused in this file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8522#-:-L9L7l-b3ECsobtzPHQl:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8522)*

**Pull request merged**
