### PR TITLE
Dev/val sim pr

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
I am taking over pr #4004 from @tkoolen , this is essentially that rebased on the new master. 
@david-german-tri for platform review. @siyuanfeng-tri already did the feature review. 

@sherm1 @amcastro-tri @SeanCurtis-TRI might also be interested.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4152)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please

**Comment by sherm1** [comment]
Per discussion with @siyuanfeng-tri , we are very interested and are working on:
- improved friction model to provide stiction (@amcastro-tri)
- investigating possible misuse of n^2 collision detection (@SeanCurtis-TRI)
- recent slowdown due to new RBPlant contact force output (@SeanCurtis-TRI)
- improved linear algebra (@edrumwri)
- doing a quick check to see whether unnecessary reallocation of KinematicsCache is a major cost (@amcastro-tri )

We'll sprint needed fixes next week after investigating.

**Comment by david-german-tri** [comment]
I've opened #4158 to document that examples/Valkyrie doesn't require platform review, as previously discussed on Slack. I'll update the Reviewable enforcement script also. Could you split the changes to Drake proper into a separate PR?

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4152#-:-KWog1cN3Vc5DfAFrV-x:bn83fov)*

**Comment by david-german-tri** [comment]
-@david-german-tri.  The changes outside examples/Valkyrie are now in #4159.  Once you remove them here, Reviewable should let you merge without platform review.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4152#-:-KWrxXMnhWKSKQBhbd2l:b-ibb36i)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4152#-:-KWu2ap9gXHHLzTvrIBf:bg7igkv)*

**Comment by SeanCurtis-TRI** [comment]
The contact force performance is initially addressed in #4206. A more complete discussion of the contact force *computation* can be found in #4204.  Some of the additional slow-down issues due to the `ContactResults` output on the `RigidBodyPlant` can be seen in #4155.

**Pull request merged**
