### PR TITLE
add libcurl dependency

### LINKED ISSUE #16125: can we integrate libcurl for the render client?
CC: @jwnimmer-tri @mwoehlke-kitware 

- License validation.
- Dependencies:
    - zlib
    - zstd (?)
    - TLS of some kind, default is libopenssl. Can also be disabled.

Where pip wheel builds are concerned, the CMake build had some strange link order problem with `zstd` but the autotools build was fine.  Did not investigate closely, but should be fixable.

### PR DESCRIPTION
**Pull request by svenevs**
For communicating with the render server.

Fixes #16125.

What do we want to do about the `apt-get satisfy` scenario?

Relates: #16234

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3KnMWEDMLJyrpCCA9:-Mr3KnMWEDMLJyrpCCAA:b8fm0fu) (no related file):*
> What do we want to do about the apt-get satisfy scenario?

The posting at https://github.com/RobotLocomotion/drake/issues/16125#issuecomment-981876592 has my advice.  ("Second", "Third", "Finally".)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3L4x8C4PHyLg58VN6:-Mr3L4x8C4PHyLg58VN7:b528nws) (no related file):*
CI doesn't actually run this new bazel code unless it's used somewhere. An "add a new external" PR should also add a program or test that (trivially) uses the new dependency. Something small in the dev folder should suffice.

---
___
*[tools/workspace/libcurl/repository.bzl, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3JvTK-hyMtNBsAkF9:-Mr3JvTL6f-UDPfai3B3:b-1pv80w) ([raw file](https://github.com/robotlocomotion/drake/blob/10c45f0f6d9031376910e6b2dba86f865e95fa7b/tools/workspace/libcurl/repository.bzl#L11)):*
> ```Starlark
>         name,
>         # ISC with advertising exception:
>         # https://github.com/curl/curl/blob/master/COPYING
> ```

For licenses, we use SPDX naming conventions, not github links.

According to `/usr/share/doc/libcurl**/copyright`, the primary license is "curl" not "ISC", so the SPDX identifier for the comment here is just "curl".
___
*[tools/workspace/libcurl/repository.bzl, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3JCd95vGiOilQ7Fv7:-Mr3JCdA-f7dfgbQyl-I:b-ra14e9) ([raw file](https://github.com/robotlocomotion/drake/blob/10c45f0f6d9031376910e6b2dba86f865e95fa7b/tools/workspace/libcurl/repository.bzl#L15)):*
> ```Starlark
>         modname = "libcurl",
>         pkg_config_paths = [
>             "/usr/lib/x86_64-linux-gnu/pkgconfig",  # Ubuntu
> ```

nit This Ubuntu path is already on the default search path.  We should not repeat it here.  (Thus, the "macOS" comment on the next line should disappear, as well.)

**Review by svenevs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233#-:-Mr8a-_tCXVGu0wi2gbN:bnfp4nl)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3KnMWEDMLJyrpCCA9:-Mr8TBBt6CH7bb85IOBH:b5wkhr) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> What do we want to do about the apt-get satisfy scenario?

The posting at https://github.com/RobotLocomotion/drake/issues/16125#issuecomment-981876592 has my advice.  ("Second", "Third", "Finally".)
</blockquote></details>

Done.  I was not sure if you wanted it in this PR or a followup.  I've added a single `packages-satisfy.txt` with the package.  I'm assuming we do not need a separate file per-${codename}.  Notes:

- Order needs to be reversed, `'libcurl4-dev | libcurl4-gnutls-dev'`.  If you `apt-get install libcurl4-openssl-dev` and satisfy `'libcurl4-gnutls-dev | libcurl4-dev '` then it will remove openssl and install gnutls version.
- Entries in this file should be quoted.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3L4x8C4PHyLg58VN6:-Mr8Z20V8jIxq0Cis2Vc:b-mvud5y) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

CI doesn't actually run this new bazel code unless it's used somewhere. An "add a new external" PR should also add a program or test that (trivially) uses the new dependency. Something small in the dev folder should suffice.
</blockquote></details>

Done.  Makes sense :slightly_smiling_face:

---
___
*[tools/workspace/libcurl/repository.bzl, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3JvTK-hyMtNBsAkF9:-Mr8_R8f1JMlIXgJGZ5r:ba3cqwq) ([raw file](https://github.com/robotlocomotion/drake/blob/10c45f0f6d9031376910e6b2dba86f865e95fa7b/tools/workspace/libcurl/repository.bzl#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For licenses, we use SPDX naming conventions, not github links.

According to `/usr/share/doc/libcurl**/copyright`, the primary license is "curl" not "ISC", so the SPDX identifier for the comment here is just "curl".
</blockquote></details>

Done.  Set to `curl`.
___
*[tools/workspace/libcurl/repository.bzl, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr3JCd95vGiOilQ7Fv7:-Mr8_56lEHo5f5YGAHd1:bfsuxtr) ([raw file](https://github.com/robotlocomotion/drake/blob/10c45f0f6d9031376910e6b2dba86f865e95fa7b/tools/workspace/libcurl/repository.bzl#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This Ubuntu path is already on the default search path.  We should not repeat it here.  (Thus, the "macOS" comment on the next line should disappear, as well.)
</blockquote></details>

Done. Fixed the `pkg_config_paths`, it was incorrect path for macOS and has been corrected and verified on the tri macbook rather than the mini... sorry about that!

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[setup/ubuntu/binary_distribution/install_prereqs.sh, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8aWemBNqL2uBzQhYY:-Mr8aWemBNqL2uBzQhYZ:biz3cym) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/binary_distribution/install_prereqs.sh#L36)):*
> ```Shell
>   maybe_yes='-y'
> else
>   maybe_yes=''
> ```

FYI I updated binary and source install files (anywhere using `$apt_get_install`) to `${maybe_yes}` for consistency.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8el8dChg46z1oCWHc:-Mr8el8dChg46z1oCWHd:bjj09fe) (no related file):*
Here's a patch to fix the problems I noted below

```patch
index 565f19fa08..f48daa69f3 100755
--- a/setup/ubuntu/source_distribution/install_prereqs.sh
+++ b/setup/ubuntu/source_distribution/install_prereqs.sh
@@ -99,7 +99,7 @@ packages=$(cat "${BASH_SOURCE%/*}/packages-${codename}.txt")
 apt-get install ${maybe_yes} --no-install-recommends ${packages}
 
 cat "${BASH_SOURCE%/*}/packages-satisfy.txt" | \
-  xargs apt-get satisfy ${maybe_yes} --no-install-recommends
+  xargs -I{} apt-get satisfy ${maybe_yes} --no-install-recommends {}
 
 # Ensure that we have available a locale that supports UTF-8 for generating a
 # C++ header containing Python API documentation during the build.
diff --git a/setup/ubuntu/source_distribution/packages-bionic.txt b/setup/ubuntu/source_distribution/packages-bionic.txt
index 6668e25de8..fc6327bedd 100644
--- a/setup/ubuntu/source_distribution/packages-bionic.txt
+++ b/setup/ubuntu/source_distribution/packages-bionic.txt
@@ -10,7 +10,6 @@ git
 libblas-dev
 libbz2-dev
 libclang-9-dev
-libcurl4-gnutls-dev
 libdouble-conversion-dev
 libexpat1-dev
 libgflags-dev
diff --git a/setup/ubuntu/source_distribution/packages-focal.txt b/setup/ubuntu/source_distribution/packages-focal.txt
index e668071d71..5cfb58cabc 100644
--- a/setup/ubuntu/source_distribution/packages-focal.txt
+++ b/setup/ubuntu/source_distribution/packages-focal.txt
@@ -10,7 +10,6 @@ git
 libblas-dev
 libbz2-dev
 libclang-9-dev
-libcurl4-gnutls-dev
 libdouble-conversion-dev
 libexpat1-dev
 libgflags-dev
diff --git a/setup/ubuntu/source_distribution/packages-satisfy.txt b/setup/ubuntu/source_distribution/packages-satisfy.txt
index 60460f8154..091086bba5 100644
--- a/setup/ubuntu/source_distribution/packages-satisfy.txt
+++ b/setup/ubuntu/source_distribution/packages-satisfy.txt
@@ -1 +1 @@
-'libcurl4-dev | libcurl4-gnutls-dev'
+libcurl4-dev | libcurl4-gnutls-dev
```

---
___
*[setup/ubuntu/binary_distribution/packages-bionic.txt, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8bhwI4kW8Wo5VgFJp:-Mr8bhwJ3gbwLOnipk33:bndy5fz) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/binary_distribution/packages-bionic.txt#L10)):*
> ```help
> libboost-all-dev
> libbz2-1.0
> libcurl4
> ```

If we're building with gnutls our suggested default (in the `satisfy.txt`), then this needs to be `libcurl3-gnutls` as the runtime dependency, not `libcurl4`.  Ditto for focal.
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8bL9cDz2xNUSfj9GW:-Mr8bL9cDz2xNUSfj9GX:beml0jn) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/source_distribution/packages-bionic.txt#L13)):*
> ```help
> libbz2-dev
> libclang-9-dev
> libcurl4-gnutls-dev
> ```

Why is curl still mentioned in `source_distribution/packages-bionic.txt` and `source_distribution/packages-focal.txt`?  My expectation was that the `satisfy.txt` file would be sufficient on its own.
___
*[setup/ubuntu/source_distribution/packages-satisfy.txt, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8etUjE6FKgbF_pURA:-Mr8etUk6YWTmLur-kUP:b6q4fwe) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/source_distribution/packages-satisfy.txt#L1)):*
> ```help
> 'libcurl4-dev | libcurl4-gnutls-dev'
> ```

We shouldn't make developers or users deal with brittle shell quoting.  See the attached patch to force line-at-a-time handling of this file.
___
*[geometry/render/dev/BUILD.bazel, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8apNs14AQ8KPTpTQl:-Mr8apNt6RGBtQZJCP0F:bvpo42c) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/geometry/render/dev/BUILD.bazel#L51)):*
> ```Starlark
> 
> # TODO(svenevs): delete this rule and file after the client merges.
> drake_cc_binary(
> ```

Did you want to make this `drake_cc_test` instead?  Right now the program is compiled, but is never run.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8el8dChg46z1oCWHc:-Mr8pHYtEas6jTLykJr9:b-7h01zd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here's a patch to fix the problems I noted below

```patch
index 565f19fa08..f48daa69f3 100755
--- a/setup/ubuntu/source_distribution/install_prereqs.sh
+++ b/setup/ubuntu/source_distribution/install_prereqs.sh
@@ -99,7 +99,7 @@ packages=$(cat "${BASH_SOURCE%/*}/packages-${codename}.txt")
 apt-get install ${maybe_yes} --no-install-recommends ${packages}
 
 cat "${BASH_SOURCE%/*}/packages-satisfy.txt" | \
-  xargs apt-get satisfy ${maybe_yes} --no-install-recommends
+  xargs -I{} apt-get satisfy ${maybe_yes} --no-install-recommends {}
 
 # Ensure that we have available a locale that supports UTF-8 for generating a
 # C++ header containing Python API documentation during the build.
diff --git a/setup/ubuntu/source_distribution/packages-bionic.txt b/setup/ubuntu/source_distribution/packages-bionic.txt
index 6668e25de8..fc6327bedd 100644
--- a/setup/ubuntu/source_distribution/packages-bionic.txt
+++ b/setup/ubuntu/source_distribution/packages-bionic.txt
@@ -10,7 +10,6 @@ git
 libblas-dev
 libbz2-dev
 libclang-9-dev
-libcurl4-gnutls-dev
 libdouble-conversion-dev
 libexpat1-dev
 libgflags-dev
diff --git a/setup/ubuntu/source_distribution/packages-focal.txt b/setup/ubuntu/source_distribution/packages-focal.txt
index e668071d71..5cfb58cabc 100644
--- a/setup/ubuntu/source_distribution/packages-focal.txt
+++ b/setup/ubuntu/source_distribution/packages-focal.txt
@@ -10,7 +10,6 @@ git
 libblas-dev
 libbz2-dev
 libclang-9-dev
-libcurl4-gnutls-dev
 libdouble-conversion-dev
 libexpat1-dev
 libgflags-dev
diff --git a/setup/ubuntu/source_distribution/packages-satisfy.txt b/setup/ubuntu/source_distribution/packages-satisfy.txt
index 60460f8154..091086bba5 100644
--- a/setup/ubuntu/source_distribution/packages-satisfy.txt
+++ b/setup/ubuntu/source_distribution/packages-satisfy.txt
@@ -1 +1 @@
-'libcurl4-dev | libcurl4-gnutls-dev'
+libcurl4-dev | libcurl4-gnutls-dev
```
</blockquote></details>

Done.  Applied and remarked in other threads.  It's double :cool: that you can do this!

---
___
*[setup/ubuntu/binary_distribution/packages-bionic.txt, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8bhwI4kW8Wo5VgFJp:-Mr8lgvZ9T17ppnc2xeY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/binary_distribution/packages-bionic.txt#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If we're building with gnutls our suggested default (in the `satisfy.txt`), then this needs to be `libcurl3-gnutls` as the runtime dependency, not `libcurl4`.  Ditto for focal.
</blockquote></details>

Done.
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8bL9cDz2xNUSfj9GW:-Mr8nCZuA0KO-vgfBmka:b-cclmuy) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/source_distribution/packages-bionic.txt#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why is curl still mentioned in `source_distribution/packages-bionic.txt` and `source_distribution/packages-focal.txt`?  My expectation was that the `satisfy.txt` file would be sufficient on its own.
</blockquote></details>

Done.  This was absolutely an oversight on my part... sorry :confused: 
___
*[setup/ubuntu/source_distribution/packages-satisfy.txt, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8etUjE6FKgbF_pURA:-Mr8nNHb04WMbGgCxBEx:bql6792) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/setup/ubuntu/source_distribution/packages-satisfy.txt#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We shouldn't make developers or users deal with brittle shell quoting.  See the attached patch to force line-at-a-time handling of this file.
</blockquote></details>

Done.  Very cool :sunglasses:
___
*[geometry/render/dev/BUILD.bazel, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr8apNs14AQ8KPTpTQl:-Mr8p4WK955Of6yhsxg1:b-6vhkzn) ([raw file](https://github.com/robotlocomotion/drake/blob/eee601ca4387fda91539679e6fd2b3c6c27a4631/geometry/render/dev/BUILD.bazel#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Did you want to make this `drake_cc_test` instead?  Right now the program is compiled, but is never run.
</blockquote></details>

Done.  Modified to always `return 0`, we don't care about curl being able to do stuff, just that it links and runs.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Comment by jwnimmer-tri** [comment]
Checking the https://drake.mit.edu/jenkins.html#updating-installation-prerequisites now:

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
For the Focal failure, as best I can guess, it's bailing out because it wants a yes/no answer but there is no tty.  We have https://github.com/RobotLocomotion/drake-ci/blob/main/setup/ubuntu/install_prereqs#L48 already, but I think we'll also need something like `echo 'APT::Get::Assume-Yes "true";' | sudo tee /etc/apt/apt.conf.d/90yes` nearby?  I'm not sure why other apt commands are working, with that one as the only failure.  I thought we already had a configuration setting in place to handle that.  Maybe @BetsyMcPhail can help you figure it out.

For the Bionic failure, I guess that the 'satisfy' command is not available at all, either with `apt` or `apt-get`.  I suppose we'll need to just hard-code a specific dev package in that case (in `packages-bionic.txt`, with an empty `satisfy` file for Bionic).  I think that will need to be the openssl flavor, though, to be compatible with ROS.

**Review by svenevs — COMMENTED** [review]
Interesting.  I updated to use openssl libs on bionic and skip satisfy in the script.  We are looking into the drake-ci issue next week.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233#-:-Mr99xU46T2PznAKiTrT:b-yc1a6g)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[setup/ubuntu/binary_distribution/packages-bionic.txt, line 10 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr9KKLf0F_i3aOGqIXW:-Mr9KKLf0F_i3aOGqIXX:b-spqjzt) ([raw file](https://github.com/robotlocomotion/drake/blob/b7727686a0fd882f4f61e78cb7152846505879c2/setup/ubuntu/binary_distribution/packages-bionic.txt#L10)):*
> ```help
> libboost-all-dev
> libbz2-1.0
> libcurl3
> ```

I think it should be `libcurl4`?
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr9K22b1s6vjWMU49Yk:-Mr9K22b1s6vjWMU49Yl:bhuc3o3) ([raw file](https://github.com/robotlocomotion/drake/blob/b7727686a0fd882f4f61e78cb7152846505879c2/setup/ubuntu/source_distribution/packages-bionic.txt#L13)):*
> ```help
> libbz2-dev
> libclang-9-dev
> libcurl-openssl1.0-dev
> ```

I think the one we want is called `libcurl4-openssl-dev`?
https://packages.ubuntu.com/bionic-updates/libcurl4-openssl-dev

I think this one is the old curl3 version.
https://packages.ubuntu.com/bionic/libcurl-openssl1.0-dev
___
*[setup/ubuntu/source_distribution/packages-satisfy.txt, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr9KR_KA1miIXJEiDiG:-Mr9KR_KA1miIXJEiDiH:b-6ca5st) ([raw file](https://github.com/robotlocomotion/drake/blob/b7727686a0fd882f4f61e78cb7152846505879c2/setup/ubuntu/source_distribution/packages-satisfy.txt#L1)):*
> ```help
> libcurl4-dev | libcurl4-gnutls-dev
> ```

This needs to be named `packages-focal-satisfy.txt`.  (Sorry I missed this earlier.)

These files must _always_ be version-specific.  Even if the contents are identical on multiple platforms, we always just do the boring thing and assume they differ, keeping two different copies of them.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[setup/ubuntu/binary_distribution/packages-bionic.txt, line 10 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr9KKLf0F_i3aOGqIXW:-Mr9OTIQ381y_OMb2aC1:b-lca5kb) ([raw file](https://github.com/robotlocomotion/drake/blob/b7727686a0fd882f4f61e78cb7152846505879c2/setup/ubuntu/binary_distribution/packages-bionic.txt#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it should be `libcurl4`?
</blockquote></details>

Done, corrected to `libcurl4` per `bionic-updates` rather than `bionic` repo.
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr9K22b1s6vjWMU49Yk:-Mr9ODUB8ZdcKwSGczn8:b-ebb0eg) ([raw file](https://github.com/robotlocomotion/drake/blob/b7727686a0fd882f4f61e78cb7152846505879c2/setup/ubuntu/source_distribution/packages-bionic.txt#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the one we want is called `libcurl4-openssl-dev`?
https://packages.ubuntu.com/bionic-updates/libcurl4-openssl-dev

I think this one is the old curl3 version.
https://packages.ubuntu.com/bionic/libcurl-openssl1.0-dev
</blockquote></details>

Done.  Yes, the package names do seem to have changed.  I selected the ones from `bionic`, but it seems like the policy here is `*-updates` when searching for packages (including focal / future distros).
___
*[setup/ubuntu/source_distribution/packages-satisfy.txt, line 1 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16233#-Mr9KR_KA1miIXJEiDiG:-Mr9O5CbE-ANMso-nzny:b-idzy8w) ([raw file](https://github.com/robotlocomotion/drake/blob/b7727686a0fd882f4f61e78cb7152846505879c2/setup/ubuntu/source_distribution/packages-satisfy.txt#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This needs to be named `packages-focal-satisfy.txt`.  (Sorry I missed this earlier.)

These files must _always_ be version-specific.  Even if the contents are identical on multiple platforms, we always just do the boring thing and assume they differ, keeping two different copies of them.
</blockquote></details>

OK, thank you for explaining that -- renamed the file and `cat` statement.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Review by svenevs — COMMENTED** [review]
:lgtm:

+@sherm1 for platform review please.  Added do not merge status since we will be rebuilding the provisioned images prior to merging this and will merge after (a) platform review is approved and (b) provisioned images are updated.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233#-:-MrSfisB3PhhDw_PjU8a:bea9p2f)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge" (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 8 files at r1, 2 of 6 files at r2, 1 of 8 files at r3, 5 of 6 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16233#-:-MrTW76EAoQvv756lgP_:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @svenevs)

**Pull request merged**
