### PR TITLE
MBP cart pole example

### PR DESCRIPTION
**Pull request by amcastro-tri**
Prismatic joint parsing, cart pole unit test and example demo.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775#-:-LC0bGHuAlKA3PFSKONS:bll7v0f)*

**Comment by sherm1** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[examples/multibody/cart_pole/BUILD.bazel, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC0g6Lp5DCOKYwiJIng:-LC0g6Lp5DCOKYwiJInh:bz325kr) ([raw file](https://github.com/robotlocomotion/drake/blob/5d948033f0dbe581574415529ffbbdc7cd40d62e/examples/multibody/cart_pole/BUILD.bazel#L26)):*
> ```Python
>     srcs = ["cart_pole_passive_simulation.cc"],
>     add_test_rule = 1,
>     #data = [":models"],
> ```

FYI commented-out line?

---

*[examples/multibody/cart_pole/cart_pole.sdf, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC0fVL56vyXeEk97Sed:-LC0fVL56vyXeEk97See:b-fy1j9o) ([raw file](https://github.com/robotlocomotion/drake/blob/5d948033f0dbe581574415529ffbbdc7cd40d62e/examples/multibody/cart_pole/cart_pole.sdf#L12)):*
> ```
>

**Comment by amcastro-tri** [comment]
Thanks @sherm1 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775#-:-LC12Gl66WpfiB4wJFN-:bhjfics)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775#-:-LC59Uvf4_cuwcsFr_Z7:bnfp4nl)*

**Comment by avalenzu** [comment]
+@seancurtis-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775#-:-LC59_uF12POwpw3YRdm:b9zwisr)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with a few cosmetic and passing comments

---

Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[examples/multibody/cart_pole/BUILD.bazel, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC67CA-2Lesqe56SBaS:-LC67CA-2Lesqe56SBaT:b-lbiilx) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/BUILD.bazel#L8)):*
> ```Python
>     "drake_cc_googletest",
>     "drake_cc_library",
>     "drake_cc_binary",
> ```

BTW These are typically alphabetized too.

---

*[examples/multibody/cart_pole/cart_pole_passive_simulation.cc, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC68T5L6AdklwqFF3qk:-LC68T5L6AdklwqFF3ql:b-s4h1hk) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/cart_pole_passive_simulation.cc#L29)):*
> ```cpp
> using multibody::Body;
> using multibody::multibody_plant::MultibodyPlant;
> using multibody::UniformGravityFieldElement;
> ```

BTW Alphabetize these to be a nice citizen

---

*[examples/multibody/cart_pole/cart_pole_passive_simulation.cc, line 111 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC68w7H63wWi384X-uk:-LC68w7H63wWi384X-ul:bkcjfgo) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/cart_pole_passive_simulation.cc#L111)):*
> ```cpp
>       diagram->CreateDefaultContext();
>   diagram->SetDefaultContext(diagram_context.get());
>   systems::Context<double>& acrobot_context =
> ```

BTW copypasta "acrobot_context".

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC69r3qAj3GDbkaDvyU:-LC69r3qAj3GDbkaDvyV:bmjpt1i) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L19)):*
> ```cpp
> namespace drake {
> 
> using multibody::Body;
> ```

BTW Why put the aliases into the `drake` namespace?

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC69iIV4GeRKcEsOGfs:-LC69iIV4GeRKcEsOGft:bmpe7z5) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L21)):*
> ```cpp
> using multibody::Body;
> using multibody::multibody_plant::MultibodyPlant;
> using multibody::UniformGravityFieldElement;
> ```

BTW Alphabetize

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC6AjrV0hcirl7arCFv:-LC6AjrV0hcirl7arCFw:byy56is) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L37)):*
> ```cpp
>     // Make the cart_pole model.
>     const std::string full_name = FindResourceOrThrow(
>         "drake/examples/multibody/cart_pole/cart_pole.sdf");
> ```

BTW Rather than fighting to make sure that the sdf file and the named_vector file maintain the same constant values, why not just write on the unfinalized tree with the default values? That's *one* way to guarantee that they both are parameterized the same and reduces the brittleness. After all, this isn't a test of the parser, but of the MBP computation, right?

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 56 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC6A0bjCaNHfym1jUq5:-LC6A0bjCaNHfym1jUq6:b-evprru) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L56)):*
> ```cpp
> 
>   // Makes the mass matrix for the cart-pole system.
>   // See http://underactuated.csail.mit.edu/underactuated.html?chapter=acrobot.
> ```

BTW: Copy pasta "acrobot"

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775#-:-LC6B6aR2xzhCHJSIBAj:b-fkw7f9)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC69r3qAj3GDbkaDvyU:-LCA0LOnCBXrELP696NB:b-xdmd6i) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L19)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW so that I don't have to type the extra `drake::`...
</blockquote></details>

FTR you don't have to have `drake` in the aliases when you pull it down. When resolving symbols, C++ starts in your current namespace and works its way up. Since `drake` is a common namespace to your tests and what it is you're using, you don't need it.

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC6AjrV0hcirl7arCFv:-LCA0cvk-3zprPyeXPKA:brxp9sq) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L37)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW I was actually looking at it as a test of the parser. Otherwise I would've created it programmatically. Also, there is no API to set, say length `l()`, on the un-finalized tree. I was thinking that'd get cleanup when we add a proper parameters  API.
</blockquote></details>

Sounds good.

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 56 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC6A0bjCaNHfym1jUq5:-LCA0gay59xPnpMSIQUa:b-xpnptu) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L56)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, no, that one is correct. The chapter is labeled "acrobot" but it contains the discussion for both.
</blockquote></details>

Aaaah. I'd followed the link and ignored the text -- I just saw a picture of the acrobot and mentally moved on. The *chapter* title even says cart pole.  :)  Ooops.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8775#-LC69r3qAj3GDbkaDvyU:-LCA7HmZ0TOjrjSUsVnZ:b-fhnckx) ([raw file](https://github.com/robotlocomotion/drake/blob/d287da51794661fb99062ec279af81c7a01e5dc8/examples/multibody/cart_pole/test/cart_pole_test.cc#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FTR you don't have to have `drake` in the aliases when you pull it down. When resolving symbols, C++ starts in your current namespace and works its way up. Since `drake` is a common namespace to your tests and what it is you're using, you don't need it.
</blockquote></details>

FTR. Nope, I tried and it didn't even compiled. Sometimes our C++ compilers are not that smart. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8775)*

**Comment by SeanCurtis-TRI** [comment]
Oh right...it's because the test is in `drake::examples::multibody::cart_pole`. So, any alias that comes from `drake::multibody::*` is going to get angry because they both go back to `multibody`. Well, at the very least it would work for `systems::Context`. :)

**Pull request merged**
