### PR TITLE
Toward #2852: enforce -Werror=shadow in systems/test/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove excuse from systems/test/ cmake file.
 * Fix AffineSystem class:
   * Yay! data is already private, so we can just fix it by obeying:
   * https://google.github.io/styleguide/cppguide.html#Variable_Names

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2886)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Another bite of #2852.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2886#-:-KNFYcJXfzpE62Fsktmr:1417088721)*

**Comment by rpoyner-tri** [comment]
+@ggould-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2886#-:-KNHl2L-Z-0zDS_uWt-Z:-528524630)*

**Comment by ggould-tri** [comment]
Yay! :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2886#-:-KNHmh-8qS9EjFa9FLvj:-913903255)*

**Pull request merged**
