### PR TITLE
Pose estimation dev work

### PR DESCRIPTION
**Pull request by RussTedrake**
Implements a sketch of a (global) pose estimation algorithm.  

Reviewers:  note that pose_estimation_test.cc and rotation.h are in a dev directory (ok that they don't have test coverage nor complete documentation yet).

PR'ing this now because I've added a few methods (with test coverage) and bug fixes to MathematicalProgram and constraints, and would like this to stay in sync with the API changes in MathematicalProgram.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4634)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review
+@jwnimmer-tri for platform review (though it may get bumped to tomorrow)
fyi @gizatt 

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-:-K_7EdkhJyeebdO1e0VH:b-v8et8j)*

**Comment by jwnimmer-tri** [comment]
Yup, -@jwnimmer-tri +@ggould-tri for platform tomorrow.  Would be good to get Grant's eyes on MathematicalProgram again, too.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-:-K_7G-4YFVYwWoFMLfMU:babcse4)*

**Comment by ggould-tri** [comment]
Small concerns noted below.  I will re-review after feature review has happened, as I want an expert to ensure the math is right before I dive too far into it.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/models/box.urdf, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_AAft0tuvEZbuaG254:-K_AAdRh0e1MHfy2F5Eh:b-p4irgi) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/multibody/models/box.urdf#L6)):*
> ```XML
>     <inertial>
>       <mass value="1"/>
>

**Comment by ggould-tri** [comment]
Note that this will have some merge conflict with #4637 around `mathematical_program`; consider coordinating which of these PRs should land first.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-:-K_AzrJKMJYAfli-8239:bvov4h0)*

**Comment by hongkai-dai** [comment]
This PR should land before #4637. 

Checkpoint

---

Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/estimators/dev/rotation.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B0uKXIHFmUck23_c1:-K_B0uKXIHFmUck23_c2:b-9edfqg) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/rotation.h#L11)):*
> ```objc
> namespace solvers {
> 
> DecisionVariableMatrixX AddRotationMatrixSpectrahedralSdpRelaxation(
> ```

The polar is also a spectrahedral, it would help if the documentation says this is the convex hull of all the rotation matrix in 3D.

Also, would it be better if we put the definition of this function in a `.cc` file?

This function also adds an LMI constraint to the program, that LMI constraint is not returned to the user. Maybe we can change the return type to `pair<DecisionVariableMatrixX, LinearMatrixInequalityConstraint>`?

---

*[drake/systems/estimators/dev/rotation.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B1w4yogKuMhXjymob:-K_B1w4yogKuMhXjymoc:b-46xczh) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/rotation.h#L16)):*
> ```objc
> 
>   // Add constraint (10) from https://arxiv.org/pdf/1403.4914.pdf .
>   // TODO(russt): Clean this up using symbolic expressions!
> ```

Totally agree on the symbolic expression!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-:-K_B2_VZMzqlC7pBggZx:bsfhsdn)*

**Comment by hongkai-dai** [comment]
Reviewed 8 of 12 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 859 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B63xPZAbfUPDIl2qw:-K_B63xPZAbfUPDIl2qx:bjy7i2m) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mathematical_program.h#L859)):*
> ```objc
>   /**
>    * Adds a cost term of the form | Ax - b |^2.
>    */
> ```

The constant term `b.transpose()*b` is not added to the cost.

---

*[drake/solvers/mosek_solver.cc, line 470 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B7WH2VtH9QvJxPrLP:-K_B7WH2VtH9QvJxPrLQ:bcfqkwx) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mosek_solver.cc#L470)):*
> ```cpp
>           } else {
>             Q_lower_triplets.push_back(
>               Eigen::Triplet<double>(var_indices[j], var_index_i, Qij));
> ```

Palmface, good catch!

---

*[drake/solvers/test/convex_optimization_test.cc, line 987 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B8H6ckW5ldEKptZx8:-K_B8H6ckW5ldEKptZx9:b-slhl2d) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/test/convex_optimization_test.cc#L987)):*
> ```cpp
>   std::shared_ptr<QuadraticConstraint> obj2 = prog.AddL2NormCost(A, b, {x});
> 
>   // Test the objective at an arbitrary x.
> ```

Maybe we can test the objective at 6 arbitrary x? The quadratic form would be guaranteed to be the same, if their values are the same with 6 different inputs (The quadratic form a0*x0^2+a1*x0*x1+a2*x1^2+a3*x0+a4*x1+a5 has 6 parameters a0, ..., a5).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 12 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[drake/multibody/models/box.urdf, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_AAft0tuvEZbuaG254:-K_Bf2AAwWdJKd3RYBeN:b-d84j3z) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/multibody/models/box.urdf#L6)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW: Use of tabs rather than spaces is inconsistent with the rest of this file.
BTW:  Please capitalize and punctuate complete sentences in comments.
</blockquote></details>

done.  (was playing with a new editor).

---

*[drake/solvers/mathematical_program.h, line 429 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_ABNwDigvI0hKRDlYI:-K_BfZlwRdxXS7niv1kx:bohbef1) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mathematical_program.h#L429)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW: Long line.
</blockquote></details>

it was just under the limit.  but i've 

---

*[drake/solvers/mathematical_program.h, line 534 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_ABncWepaKK9YOctUF:-K_Bg0WRXClhJjkAYvIG:b-74bls4) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mathematical_program.h#L534)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The "x" here is now wrong.

BTW Also (though not new with your change) the use of quotes around "name" and "x" are semantically different; `"name"` should be `@p name` to avoid confusion.
</blockquote></details>

done.  i've reverted my changes so that the "x" is correct again.  I didn't feel strongly about it (and the "x" appears in many more places than I'd realized).

---

*[drake/solvers/mathematical_program.h, line 596 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_AC7N4rl8kd4mxQpau:-K_Bgb6xPKjruvlF0Xv3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mathematical_program.h#L596)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

"b" here is now incorrect.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 859 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B63xPZAbfUPDIl2qw:-K_BginExfdE0I1anPCz:bj7s5go) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mathematical_program.h#L859)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The constant term `b.transpose()*b` is not added to the cost.
</blockquote></details>

agreed.  unfortunately, this is a known issue (assigned to you :).  #3500.

---

*[drake/solvers/mosek_solver.cc, line 470 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B7WH2VtH9QvJxPrLP:-K_BgrMzsbr7bHpCuC2D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mosek_solver.cc#L470)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Palmface, good catch!
</blockquote></details>

Done.

---

*[drake/solvers/test/convex_optimization_test.cc, line 987 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B8H6ckW5ldEKptZx8:-K_Bhkln1krap6tuf6GI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/test/convex_optimization_test.cc#L987)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe we can test the objective at 6 arbitrary x? The quadratic form would be guaranteed to be the same, if their values are the same with 6 different inputs (The quadratic form a0*x0^2+a1*x0*x1+a2*x1^2+a3*x0+a4*x1+a5 has 6 parameters a0, ..., a5).
</blockquote></details>

Done.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BL8jEKYMylkzvoN7m:-K_Bi-93uoUCSKcEu4Nv:bllqhy4) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L25)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think you mean RR^T = I? RR^{-1} is always I.
</blockquote></details>

oops.  good catch.  done.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BLk-H0m5uwiqQrIY9:-K_BiP0PihsPQz-X_Ovh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L46)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe add a documentation to say faces.col(i) contains the indices of the vertices on i'th face?
</blockquote></details>

Done.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BZAfMIRwor863osJn:-K_BierOSrKcBgS13Vr3:bc4sjck) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L64)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

AddLinearEqualityConstraint
</blockquote></details>

Done.  Good call.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 104 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BMYoM8gqDTTo81LOc:-K_BiuCkVw1zIgQUrVTe:b583ld7) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L104)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If we really want the original objective, we can use the rotated Lorentz cone
sigma_k * dummy >= z0^2 + ... z2^2
dummy = 1
</blockquote></details>

Good point.  Added a comment for now.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BXTBFJGtLeNnpOKQy:-K_Bjk6K5tB5oATlrO4N:b-7bsu5u) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L120)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is probably easier to read, if we write it as
```
A <<points(0,k)*Matrix3d::Identity(), points(1, k)*Matrix3d::Identity(), points(2,k)*Matrix3d::Identity(), Matrix3d::Identity(), -vertices, -Matrix3d::Identity()
```
</blockquote></details>

but i don't like all of the extra copying that it implies.  I've re-ordered the lines to reveal the structure you're pointing out.  

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 131 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BZ6kFviwzysqfNLJc:-K_Bk4xhDQqX2zaN5SXG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L131)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

AddLinearEqualityConstraint
</blockquote></details>

Done.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BYQb4YYCX1xuQA-Un:-K_BkBv08AVyC5vcdcom:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L152)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

AddLinearEqualityConstraint?
</blockquote></details>

Done.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B_NeCUhSY7b5HvTFn:-K_BkEjDUGN7oRk7oSeB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L157)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`<=` instead of `<`
</blockquote></details>

Done.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 172 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_Bal_AgfKUY5vAVns2:-K_BkNu3mOQARKouIP5-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L172)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We do not need to use drake::Vector1d, `MathematicalProgram` has a function 
```
AddLinearConstraint(const Eigen::MatrixBase<DerivedA>& a, double lb, double ub, const VariableListRef& vars)
```
</blockquote></details>

Done.

---

*[drake/systems/estimators/dev/rotation.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B0uKXIHFmUck23_c1:-K_BkdVh_h3kf9EnU9U0:b-pa576c) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/rotation.h#L11)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The polar is also a spectrahedral, it would help if the documentation says this is the convex hull of all the rotation matrix in 3D.

Also, would it be better if we put the definition of this function in a `.cc` file?

This function also adds an LMI constraint to the program, that LMI constraint is not returned to the user. Maybe we can change the return type to `pair<DecisionVariableMatrixX, LinearMatrixInequalityConstraint>`?
</blockquote></details>

All good comments.  I'll add the convex hull remark, but call "dev directory" on the rest.  My intent is to move it to .cc, define an interface that works for many of the constraints, and provide test coverage.  But not today.  :)

---

*[drake/systems/estimators/dev/rotation.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B1w4yogKuMhXjymob:-K_BlEIOXQyqWO0-4ZqH:bf0w0hb) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/rotation.h#L16)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Totally agree on the symbolic expression!
</blockquote></details>

Done.  Thanks for the detailed review!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634)*

**Comment by hongkai-dai** [comment]
:lgtm: This is a very smart approach to convexify the problem!

---

Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/convex_optimization_test.cc, line 987 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B8H6ckW5ldEKptZx8:-K_Bmhhy7MBOJ2fAxxI5:b-svazb0) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/test/convex_optimization_test.cc#L987)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`x0` is not changed in these 6 tests?

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BZAfMIRwor863osJn:-K_BmvXGCN3rcvm-bjWa:b-eb3mqr) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L64)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Good call.
</blockquote></details>

We do not have to use `drake::Vector1d` here, I think `MathematicalProgram` has the function
```
AddLinearEqualityConstraint( const Eigen::MatrixBase<DerivedA>& a, double beq,  const VariableListRef& vars)
```

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BYQb4YYCX1xuQA-Un:-K_BnSq7IxjXCBYoY9Vk:bddguz1) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L152)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same on `drake::Vector1d`, I feel it is more readable to use `double` version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-:-K_BnoDNTFbUWcFloTkC:bydv9ag)*

**Comment by RussTedrake** [comment]
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/test/convex_optimization_test.cc, line 987 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_B8H6ckW5ldEKptZx8:-K_BpqJHA9j77rG3uTtV:b-lbl07s) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/test/convex_optimization_test.cc#L987)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`x0` is not changed in these 6 tests?
</blockquote></details>

i increment the value by 2 (to get 9,10, then 11,12, etc) at the bottom of the for loop.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BYQb4YYCX1xuQA-Un:-K_BqE9gaoPfPaILE11m:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L152)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Same on `drake::Vector1d`, I feel it is more readable to use `double` version.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634)*

**Comment by RussTedrake** [comment]
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_BZAfMIRwor863osJn:-K_BqYcTrbBd8Q046VzE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/systems/estimators/dev/pose_estimation_test.cc#L64)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We do not have to use `drake::Vector1d` here, I think `MathematicalProgram` has the function
```
AddLinearEqualityConstraint( const Eigen::MatrixBase<DerivedA>& a, double beq,  const VariableListRef& vars)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 429 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-K_ABNwDigvI0hKRDlYI:-K_V0H0O7MegTyKLwM_j:b-qxfc5z) ([raw file](https://github.com/robotlocomotion/drake/blob/2552caf2f2cd75333c456b930989d91780de47de/drake/solvers/mathematical_program.h#L429)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it was just under the limit.  but i've 
</blockquote></details>

Odd, reviewable wrapped it.  I have filed an issue against reviewable https://github.com/Reviewable/Reviewable/issues/441 for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4634#-:-K_V2lifxH9xaeW8GwVw:bnfp4nl)*

**Pull request merged**
