### PR TITLE
Add contact visualisation to planar scene_graph visualizer

### PR DESCRIPTION
**Pull request by kamiradi**
This PR addresses #13214 

It extends the `PlanarSceneGraphVisualizer` matplotlib visualisation functionality to add contact information, `PlanarSceneGraphContactVisualizer`. 

Possible points of improvement,
- Have one class for both `scene_graph` and `contact_results` visualization, and give the user the option to select if they want to visualise contact. This is as opposed to having `PlanarSceneGraphVisualizer` and `PlanarSceneGraphContactVisualizer`.
- At the moment, only 10 contact force lines are drawn by the matplotlib plot. I haven't found a way to dynamically register artists and update their data for each frame. This small addition can then allow all contact forces to be shown. In my experience using it, I work in an experimental setting where not more than 10 c ontacts need to be rendered. Althought, this may be needful for more contact-rich settings
- Ability to render contact forces between specified bodies. This would be handy if you want to visualise only a subset of contact forces. 

Let me know what you think. Looking forward to your feedback.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-Nrq1n8s3NKsLg6vMKu1:b-7evfmk)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @kamiradi)

**Comment by SeanCurtis-TRI** [comment]
+@bernhardpg I'll defer to you if you want to do the feature review (as per your volunteering in the issue).

**Review by bernhardpg — COMMENTED** [review]
@SeanCurtis-TRI I am happy to review.

@kamiradi Thank you for opening the PR! I see that much of this code is duplicated from the `PlanarSceneGraphVisualizer` code, and I would propose modifying this PR to rather extend that class. Specifically, we could render the contact results only if the contact input port to the `PlanarSceneGraphVisualizer` is connected. Do you agree with this proposal @SeanCurtis-TRI ?

@kamiradi  Also it would be great if you could add some tests for the new functionality. See 
[here](https://github.com/RobotLocomotion/drake/blob/f39a26667920b4b6924cb341f9bb3da9580172d8/bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py) for some references.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-NrvoA568umU40-xUIjw:bmiqwa7)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I haven't delved into it so I don't have a strong opinion about the structure. I'm not sure how much code is shared between the two classes. We're balancing sharing code vs bloating a class. For arcane reasons, most of Drake visualization does separate model visualization from contact visualization. However, it would be a shame to duplicate extensive amounts of code.

Do you have a rough estimate of what percentage of this PR is novel and what duplicates the model visualizer?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-Ns9aOI210V8ZAjBDO8M:b-al9axp)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Review by bernhardpg — COMMENTED** [review]
Most seems to be copied from the other class, I'd say around 80%.

The functions `_contact_projection` and `_contact_force_projection` are new, as well as a a few short sections in some of the existing functions. The new section in `draw` could be moved to an `if` statement based on whether the ContactResult port is connected or not. The rest can simply be added as new functionality.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-Ns9tIo52RC67Q_h00H4:b-1mz6od)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Review by SeanCurtis-TRI — COMMENTED** [review]
That's a good argument for your suggestion.  I give it my vote.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-NsA0T46B3IzFIKWErhX:b-e1souw)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Comment by kamiradi** [comment]
Hi,
Indeed, I would say that most of the code is duplicated into the new class. I did initially think of extending `PlanarSceneGraphVisualizer` itself, however I thought from a users perspective giving a separate scene_graph and contact+scene_graph class would be beneficial. I'll do the relevant modifications. Thanks for your feedback @bernhardpg @SeanCurtis-TRI.

**Comment by kamiradi** [comment]
Hi @RussTedrake @bernhardpg @SeanCurtis-TRI,

I have made changes to the existing `PlanarSceneGraphVisualizer` and removed the `PlanarSceneGraphContactVisualizer` as per the comments above. I am running some sanity check tests on these modifications against the new `MakeHardwareStation` as used in [hybrid_force_motion](https://github.com/kamiradi/manipulation/blob/master/book/force/exercises/hybrid_force_position.ipynb) and have been facing a few issues.

Is there a change in the way contact results are being returned from the hardware station. I see that there is a `prefinalize_parser_callback` pointing to the `Setup` function, is this changing the contacts reported from the plant?

**Comment by RussTedrake** [comment]
`MakeHardwareStation` should simply be exporting the contact results output port; it doesn't make any changes.  In case it's useful, I also have this [contact_inspector](https://github.com/RussTedrake/manipulation/blob/master/book/clutter/contact_inspector.ipynb) notebook; one could potentially add a planar scenegraph visualizer there (and compare the visualizations/recordings with Meshcat's).

**Comment by kamiradi** [comment]
> `MakeHardwareStation` should simply be exporting the contact results output port; it doesn't make any changes. In case it's useful, I also have this [contact_inspector](https://github.com/RussTedrake/manipulation/blob/master/book/clutter/contact_inspector.ipynb) notebook; one could potentially add a planar scenegraph visualizer there (and compare the visualizations/recordings with Meshcat's).

On further investigation, I see that the contacts reported back from the `MakerHardwareStation` are purely hydroelastic (which makes sense). This was helpful as I was not differentiating between hydroelastic and point_contact. So it helped catching the fact that I was completly missing visualizing Hydroelastic contact.

However, a new error when trying to visualise the hydroelastic contact is that quadrature data is not populated even though the `num_hydroelastic_contacts` is returning a single contact (the book lying on the table). Either that, or I am missing something in the way Im gathering `hydroelastic_info` from `contact_results`.
```
Cell In[23], line 437, in PlanarSceneGraphVisualizer.draw(self, context)
    435 for id in range(contact_results.num_hydroelastic_contacts()):
    436     contact_info = contact_results.hydroelastic_contact_info(id)
--> 437     qp_data = contact_info.quadrature_point_data()
    438     spatial_force = contact_info.SpatialForce()
    439     points.append(qp_data.p_WQ)

AttributeError: 'pydrake.multibody.plant.HydroelasticContactInfo' object has no attribute 'quadrature_point_data'
```
I'll give the `contact_inspector` a shot, thanks for the suggestion.

**Review by SeanCurtis-TRI — COMMENTED** [review]
On the python side, you won't be able to handle the quadrature point data. It [hasn't been bound](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/multibody/plant_py.cc#L88-L100). Only `contact_surface()` and `F_Ac_W` have been bound. On the other hand, we generally don't visualize that data in the meshcat contact visualizer either. Its greatest value was in debugging the initial implementation, but seeing a see of points, tractions, tangential velocities, and the like, doesn't provide much helpful feedback.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-NtadwOr9Ed47I5wygsj:bo6u0nl)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Comment by kamiradi** [comment]
> On the python side, you won't be able to handle the quadrature point data. It [hasn't been bound](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/multibody/plant_py.cc#L88-L100). Only `contact_surface()` and `F_Ac_W` have been bound. On the other hand, we generally don't visualize that data in the meshcat contact visualizer either. Its greatest value was in debugging the initial implementation, but seeing a see of points, tractions, tangential velocities, and the like, doesn't provide much helpful feedback.
> 
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-NtadwOr9Ed47I5wygsj:bo6u0nl)_ status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

Ah I see, then i guess i can extract the `c` in `F_Ac_W` as the contact point in the world frame visualize the magnitude of the force on that point. How can I extract that point? Can you point me in the direction of where this alreadty done?

**Comment by SeanCurtis-TRI** [comment]
The C++ code provides some hints to that (check out the links below).
  - In [`contact_visualizer.cc`](https://github.com/RobotLocomotion/drake/blob/master/multibody/meshcat/contact_visualizer.cc#L215-L227), we store the contact surface centroid.
  - In [`hydroelastic_contact_visualizer.cc`](https://github.com/RobotLocomotion/drake/blob/master/multibody/meshcat/hydroelastic_contact_visualizer.cc#L65-L67) that quantity is used to position the contact. I'd interpret that the point at which the contact force is applied.

**Comment by kamiradi** [comment]
Is there a way that I can just run the python unittests?

**Comment by SeanCurtis-TRI** [comment]
The spelling you're looking for is:

`bazel test //bindings/pydrake/systems:py/planar_scenegraph_visualizer_test`

Note how the `.py` at the end has become a `py/` at the beginning of the test name.

TO check for lint, do:

`//bindings/pydrake/systems:py/planar_scenegraph_visualizer_py_pycodestyle`

**Comment by kamiradi** [comment]
@SeanCurtis-TRI Thanks for this. I am running into another problem, when trying to run the test, and building it looks like the build process a lot of memory an RAM and the whole system gets stuck, and slows down. My system specifications are as follows:

1. Building inside a docker container
2. RAM - 16gb
3. Processor: Intel Core i5-8365U CPU @ 1.6-GHz x 8
4. 64 bit

**Comment by SeanCurtis-TRI** [comment]
It sounds like you need to throttle the number of threads of build you have.

Here are your options:

1. Add the `-j N`argument to a particular invocation (e.g., `bazel test -j 2 //bindings/pydrake/systems:py/planar_scenegraph_visualizer_test` to limit it to two threads.
2. Edit your `~/.bazrlc` file to include the line `build -j 2` to limit builds to two threads, system wide.
3. Edit your `~/.bazrlc` file to include the line `build -j HOST_CPUS*0.5` to limit builds to half of your available CPUs, system wide.

**Comment by SeanCurtis-TRI** [comment]
Sorry. that had a typo. it should be the `~/.bazelrc` file.

**Comment by kamiradi** [comment]
Thanks for this @SeanCurtis-TRI. Although I don't think my laptop is capable of building the repository, I tried with the steps you mentioned. As an alternative, do I need to build the repository to just perform the `planar_scenegraph_visualizer_test`? Can I somehow side step the build by testing against pre-built binaries (I guess not but wanted to see if I am missing something)?

**Comment by SeanCurtis-TRI** [comment]
Sadly, anything that depends on `pydrake` has to build *all* of Drake. If your machine isn't up to it, you can take the slower step of relying on CI to do the test for you.

That said, if you can get through the full build once, successive changes to the test or to `planar_scenegraph_visualizer.py` should *not* require further builds. So, you just have to let it grind through one long build.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Comment by kamiradi** [comment]
@SeanCurtis-TRI Thank you for your feedback. Turns out once I build it on a slightly beefier machine, the build goes through (along with some limits on CPU and memory usage on docker's side).
I am currently testing on the existing set of `planar_scenegraph_visualizer_test`s. I have modified the class such that the existing API for this class does not break. However, it seems that the `test_mesh_file_parsing` test fails with the following message. Any hints on where I could be going wrong here
```
Running tests...
----------------------------------------------------------------------
...E.
======================================================================
ERROR [0.047s]: test_mesh_file_parsing (planar_scenegraph_visualizer_test.TestPlanarSceneGraphVisualizer)
This test ensures we can load obj files or provide a reasonable error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bazel-working-directory/drake/bazel-out/k8-opt/bin/bindings/pydrake/systems/py/planar_scenegraph_visualizer_test.runfiles/drake/bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py", line 167, in test_mesh_file_parsing
    PlanarSceneGraphVisualizer(scene_graph)
  File "/tmp/bazel-working-directory/drake/bazel-out/k8-opt/bin/bindings/pydrake/systems/py/planar_scenegraph_visualizer_test.runfiles/drake/bindings/pydrake/systems/planar_scenegraph_visualizer.py", line 143, in __init__
    self._build_body_patches(use_random_colors,
  File "/tmp/bazel-working-directory/drake/bazel-out/k8-opt/bin/bindings/pydrake/systems/py/planar_scenegraph_visualizer_test.runfiles/drake/bindings/pydrake/systems/planar_scenegraph_visualizer.py", line 285, in _build_body_patches
    raise RuntimeError(
RuntimeError: The given file /tmp/bazel-working-directory/drake/bazel-out/k8-opt/bin/bindings/pydrake/systems/py/planar_scenegraph_visualizer_test.runfiles/drake_models/iiwa_description/meshes/iiwa14/visual/link_0.STL is not supported and no alternate /tmp/bazel-working-directory/drake/bazel-out/k8-opt/bin/bindings/pydrake/systems/py/planar_scenegraph_visualizer_test.runfiles/drake_models/iiwa_description/meshes/iiwa14/visual/link_0.obj could be found.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
Ok, at some point, while you were merging into master, you undid some changes introduced by PRs #21131, #21079, and #21189. This has harmed the visualizer's code to find a fallback file. I've noted below where such things have happened.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-Nv3C9Nl7NAdV-Q_ml6-:bky4nw5)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

___
*[`bindings/pydrake/systems/planar_scenegraph_visualizer.py` line 275 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-Nv3EEJS50cc5fF_6lo6:-Nv3EEJS50cc5fF_6lo7:b-xj4lcp) ([raw file](https://github.com/RobotLocomotion/drake/blob/d215d6b3d2fa48f06e2a46366959fbeaee5f1d70/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L275)):*
> ```Python
>                     # Legacy behavior for looking for a .obj when the extension
>                     # is not recognized.
>                     filename = shape.filename()
> ```

nit: all of these changes should be backed out. This will make the test pass happily.

**Comment by kamiradi** [comment]
Ah I see, thanks for pointing that out. Then I guess I have one follow up meta question. What are the best practices when you are merging from the master to update all changes to your development branch (in this case 2dcontact). Mostly in the case that something like this happens.

This is more of a noob open source contribution question so that I can get my habits in order. Thanks in advance.

**Review by kamiradi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

___
*[`bindings/pydrake/systems/planar_scenegraph_visualizer.py` line 275 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-Nv3EEJS50cc5fF_6lo6:-Nv6d96GAZXWlFq7XX8q:bs9og5p) ([raw file](https://github.com/RobotLocomotion/drake/blob/d215d6b3d2fa48f06e2a46366959fbeaee5f1d70/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L275)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: all of these changes should be backed out. This will make the test pass happily.
</blockquote></details>

This worked. Thanks for your comment.

**Comment by SeanCurtis-TRI** [comment]
There are competing views about workflow. I can tell you *my* workflow and *why* I do it the way I do and you can decide if you like. Both workviews require addressing merge conflicts (which was undoubtedly the source of your problems here).

I almost always work with a curated branch. What does that mean? Git makes commits cheap. So, it's easy to start a branch and commit, commit, commit. There's nothing wrong with that. The challenge is when you master moves and you need to reconcile your branch with master. You can attempt to rebase your branch onto master, or you can merge master. When you have a long commit chain, it's generally easier to merge master into your branch. This, of course, extends your commit chain, often making it difficult to fully understand what in the chain you've changed.

What I (generally) do is have my branch consist of a single commit, always. When I make further changes on an existing branch, I *amend* commit the changes into the existing commit. This requires *force* pushing it to my remote fork repository. But it has the benefit that all of my branch's changes exist in a single commit and I can look at the contents of that commit and understand exactly what I've changed. With this single commit, if master changes, I can rebase the single commit on top of master. I really like the mental model of having my branch "floating on top" of master. It also makes it easier for reviewers to check out my branch and see the change in a single package. (And it means its ready to merge as is, as Drake requires these kind of curated commits for merging into master.)

The worst work flow would be to have a long commit chain *and* rebase. The reason for this is that there may be no conflicts between master and the *final* state of your branch, but there may be conflicts based on changes made in intermediate commits. Things you tried and then subsequently changed. So, don't do this.  :)

**Review by kamiradi — COMMENTED** [review]
This was very helpful, Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-NvBZkKhE1ubx2Zxpr-4:b-w3hcpu)* status: LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Review by bernhardpg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074)* status: 4 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

___
*[`bindings/pydrake/systems/planar_scenegraph_visualizer.py` line 485 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-NwLM86wCC2UyQUINI_G:-NwMBj1e0vBXKFk1n6EY:bs5zs1u) ([raw file](https://github.com/RobotLocomotion/drake/blob/68a0f7c091cca1071376a945e71cb48be6e22867/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L485)):*
<details><summary><i>Previously, bernhardpg wrote…</i></summary><blockquote>

This should be done similarly to the force scaling for contact forces in meshcat.

I had a look at the [contact_visualizer](https://github.com/RobotLocomotion/drake/blob/2bc4fb9d4ce9d75d27e58c666926d0f3b56a2b88/multibody/meshcat/contact_visualizer.cc) but could not find anything related to force scaling there, so I suppose that this might be done on meshcat's end. @SeanCurtis-TRI WDYT?
</blockquote></details>

@RussTedrake helped me find the relevant line.

The relevant line for meshcat visualization of contact forces is [here](https://github.com/RobotLocomotion/drake/blob/e561e4d8f295040923fd870121203a3cbe861dd5/multibody/meshcat/point_contact_visualizer.cc#L70).

The relevant dataclass is [here](https://drake.mit.edu/doxygen_cxx/structdrake_1_1multibody_1_1meshcat_1_1_contact_visualizer_params.html).

As inspiration/clarification, a notebook showing how this is used with meshcat can be found [here](https://github.com/RobotLocomotion/drake/blob/e561e4d8f295040923fd870121203a3cbe861dd5/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb#L254).

I think the most natural thing is to have an optional argument to `PlanarSceneGraphVisualizer` where the user can pass a custom `ContactVisualizerParams`, and if none is provided, one with the default arguments is constructed and used.

e.g.
```
def __init__( ... , contact_visualizer_params = ContactVisualizerParams(), ...)
```

**Review by bernhardpg — COMMENTED** [review]
@kamiradi  I just had a look at the visualization output of the unit test, and it seems that there is no contact happening in the test. The unit test should trigger the contact visualization code to be used, and should therefore be adjusted accordingly. It does not have to be complex, for instance it could just be adding a table and a box that is resting on the table.

If you're curious, the way I rendered the output of the unit test was by just copy/pasting the unit test code to a separate script that I run, adding these lines at the end:
```
    simulator = Simulator(diagram, diagram_context)

    visualizer_contact.start_recording()  # type: ignore

    simulator.Initialize()
    simulator.AdvanceTo(2.0)

    visualizer_contact.stop_recording()  # type: ignore
    ani = visualizer_contact.get_recording_as_animation()  # type: ignore

    # Playback the recording and save the output.
    print("Saving!")

    ani.save("contact_visualization.mp4", fps=30)
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21074#-:-NwPkzDK0F0caHew_1qU:becjgvy)* status: 4 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),bernhardpg, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @kamiradi)

**Comment by jwnimmer-tri** [comment]
Hi folks.  Thanks for all of your work on this!  It looks like it has received a lot of attention for a while this spring, but has stalled out now?  Is there a plan / intention to circle back here and finish up the work?  If not, we'd ask that you please close the paused PR, until such a time as it's ready to proceed again, in order to conserve CI resources.  Let me know, thanks!

**Comment by kamiradi** [comment]
Hi, yes I'll get back to this in some time, until then please close it. I'll reopen it when I am back on this again.

**Comment by jwnimmer-tri** [comment]
Thank you!

**Pull request closed without merging**
