### PR TITLE
Filter out subcomponents in build_components_refresh

### LINKED ISSUE #6464: Improvements to `libdrake.so` list of components
Pasted from https://github.com/RobotLocomotion/drake/pull/6452#issuecomment-311767755:

FYI Here's some nice-to-haves that don't need to block this PR:
- [ ] When e.g. `//drake/systems/framework:framework` exists (as a rollup of everything in the folder), we should only list that, instead of writing out every individual component.
  - WIP https://github.com/jwnimmer-tri/drake/commits/build-libdrake-all-stash
- [x] We should add more folder rollup libraries (possibly some of them should only be visible to this install target), so that more folders use the above simplification.
  - WIP https://github.com/jwnimmer-tri/drake/commits/build-libdrake-all-stash
- [x] We should make the "update to a new list of exported targets" more automated, such as relocating the "here's the `bazel query()` you should run" code from a comment into a script that emits a `.bzl` file that gets `load()`ed here.  (Writing it in python would allow us to easily capture our heuristics like the folder-rollup suggestions above, or other exceptional cases.)
  - A regression test could confirm that the script's output matched the checked-in version.
- [x] We should install `drake/thirdParty` libraries via `WORKSPACE` not here.

Perhaps not all of these are worth doing, but I didn't want to lose track of them.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #6464.

Ideally we would continue to work on components still marked as `# unpackaged` in the list, but for now at least it seems worth locking in this stage before moving on to fix the stragglers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8792)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@ggould-tri for platform review per schedule, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8792#-:-LCEe5EKEw4Viw_Yhsgs:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/build_components.bzl, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8792#-LCE7R6t-KNqgiQ9kXyG:-LCEfSMzB1AMEShsIn0u:b99ly0u) ([raw file](https://github.com/robotlocomotion/drake/blob/e0d07273b4a71e9253dad7673593e92832efb76e/tools/install/libdrake/build_components.bzl#L8)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Author's discretion as it is not part of this PR, but it seems odd to me to put "when adding new components" right after "don't update this list".  Perhaps this comment is in the wrong place?
</blockquote></details>

Done.  Wow, that comment was _old_ and very, very stale.

---

*[tools/install/libdrake/build_components_refresh.py, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8792#-LCE8IxvBHO-R9RWT_hK:-LCEgLyy0qM0FM2Zeobe:b-6amisr) ([raw file](https://github.com/robotlocomotion/drake/blob/e0d07273b4a71e9253dad7673593e92832efb76e/tools/install/libdrake/build_components_refresh.py#L123)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is going to disturb the sort you do above (line 64) , resulting in surprising sorts like the position of `//multibody/rigid_body_plant` in the generated file.  I'm a little bit surprised that buildifier allowed it.

Perhaps it would be better to sort after this step rather than in `_find_libdrake_components`?
</blockquote></details>

Done.  Great point.  It even fixed a bug (rigid_body_plant should have been commented as unpackaged).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8792)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8792)*

**Comment by jwnimmer-tri** [comment]
I tested this locally; the only difference in the install is that `include/drake/multibody/multibody_tree:/parsing/*.h` are newly installed, since that package is now mentioned due to the refresh.  (The PRs that added that code to master did not run build_components_refresh.)

**Pull request merged**
