### PR TITLE
[workspace] Upgrade nlopt_internal to latest release v2.9.1

### PR DESCRIPTION
**Pull request by nicolecheetham**
Towards: #22240

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @nicolecheetham)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-ODE1CmPEpNOF5C9E69Y:-ODE1CmPEpNOF5C9E69Z:b-3zggyi) (no related file):*
This one is a bit of a hairball. I've figured out how to fix the build system, but a bunch of drake tests subsequently fail.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @nicolecheetham)

___
*[`tools/workspace/nlopt_internal/patches/repair_luksan_config.patch` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-ODE2n7r91rCPKtJvvwU:-ODE2n7r91rCPKtJvvwV:bnrw2nx) ([raw file](https://github.com/RobotLocomotion/drake/blob/080a0a5de56352814e0e51e4f2d6712e2316d957/tools/workspace/nlopt_internal/patches/repair_luksan_config.patch#L1)):*
> ```Diff
> diff --git nlopt_config.h.in nlopt_config.h.in
> ```

This patch file needs cleanup, doc, and probably relocation to `patches/upstream/'.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @nicolecheetham)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-ODE1CmPEpNOF5C9E69Y:-ODHk88k-NIZV33rTqdd:b1zo3f3) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This one is a bit of a hairball. I've figured out how to fix the build system, but a bunch of drake tests subsequently fail.
</blockquote></details>

The hand-maintained enums needed an update. Testing now, and updating branch shortly.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri :lgtm: 
+(release notes: fix) 
+sherm1 for second pair of eyes on platform review; I'm pretty much a co-author at this point.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-:-ODHxy0o-7CKujnx2aU9:b8rta6m)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by rpoyner-tri — COMMENTED** [review]
erm, +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-:-ODI9rGZ5N_t8i6Lepjz:b-b15zkc)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:
Would be good to modify the PR description and commit message to note that in addition to updating, this removes LUKSAN as a dependency to avoid ugly LGPL license.

> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-:-ODJ6Yl9D2ZR-RFHiAPD:b-r6bmkm)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Comment by jwnimmer-tri** [comment]
> ... this removes LUKSAN as a dependency to avoid ugly LGPL license.

It has always been removed.  This only changes the spelling of how we remove it.

**Review by sherm1 — COMMENTED** [review]
OK, all good then -- thanks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22257#-:-ODJCHzN6Eb0CaFakVgn:b-7dsps7)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @nicolecheetham)

**Pull request merged**
