### PR TITLE
Doxygen on how to estimate hydroelastic forces and parameters

### PR DESCRIPTION
**Pull request by amcastro-tri**
We might want (maybe) to expand these a bit further to add a couple more case (e.g. grippers), but I think this is a good start.
It'll help me reference  estimations for #21463.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
First pass done.

Awesome! A few questions and comments. I'll make another pass when the figures are in.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-:-O8Jxlg07SWSBRYbjzBU:bfkxkdc)* status: 14 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 8 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JwB-18ddg0QaLmuR1:-O8JwB-18ddg0QaLmuR2:b-sj1eqt) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L8)):*
> ```objc
> /** @addtogroup hydro_params Estimation of Hydroelastic Parameters
> 
> Similarly to Hertz's theory of contact mechanics, in this section we derive
> ```

BTW you can call this "Hertz theory" (rather than "Hertz's theory") and avoid the extra punctuation and weird pronunciation. 
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8Ju6UC9hwxexUZXMT7:-O8Ju6UC9hwxexUZXMT8:b8u2j76) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L9)):*
> ```objc
> 
> Similarly to Hertz's theory of contact mechanics, in this section we derive
> analytical formulae to estimate the elastic force that establishes between two
> ```

BTW consider using "formulas" as the plural. Google says that form is used in "everyday writing", i.e. it isn't as uppity as "formulae".
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8Jx_N45CRDbw2jD9Co:-O8Jx_N45CRDbw2jD9Cp:b-d7m0u5) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L11)):*
> ```objc
> analytical formulae to estimate the elastic force that establishes between two
> bodies in contact. As in Hertz's theory, we assume small deformations, allowing
> us to introduce geometrical approximations.
> ```

BTW consider adding a short paragraph on how this section could be useful to a person using Drake. How should someone make use of this information?
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JuZLsAWSe1-otrKdd:-O8JuZLsAWSe1-otrKde:b-9xgfm0) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L23)):*
> ```objc
> The table below summarizes analytical formulae to compute the contact force
> between a body of a given geometric shape with a half-space. The body penetrates
> a distance `x` into the table.
> ```

BTW later you re-use "x" to mean a generic point on the contact surface, while here it is a scalar penetration depth. It's confusing to use the same symbol for two different things in the same paper. Consider using some other symbol for the few places where penetration depth is used in this section -- maybe "d" or "δ"?
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JtdA67J55XicGOwsN:-O8JtdA67J55XicGOwsO:b6e1q0a) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L29)):*
> ```objc
> Cylinderᵃ       |         R          |@f$\pi R^2 x@f$              |@f$\pi E R x@f$
> Sphereᵇ         |         R          |@f$\pi R x^2@f$              |@f$\pi E x^2@f$
> Coneᶜ           |         H          |@f$\pi/3\tan^2(\theta)x^3@f$ |@f$\pi/3 \tan^2(\theta) E/H x^3@f$
> ```

BTW what is the source for these formulas? KL Johnson? I'd like to double check in case of typos or whatever.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 31 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JtCMQ6TdIYLT23rIr:-O8JtCMQ6TdIYLT23rIs:b-yvuqex) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L31)):*
> ```objc
> Coneᶜ           |         H          |@f$\pi/3\tan^2(\theta)x^3@f$ |@f$\pi/3 \tan^2(\theta) E/H x^3@f$
> 
> ᵃ Compliant cylinder of radius R and length L > R. Rigid half-space.
> ```

minor: should state explicitly that you are considering the case where the cylinder's end cap is contacting the half space. It could also be lying on its side in which case the contact would be very different.

I guess you could call it a "cylindrical indenter". Or a coffee cup!
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JvSng2lDjhhJI4QTg:-O8JvSnh3Kv6S67bHoke:b-nr48g4) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L37)):*
> ```objc
> ᶜ Rigid conic indenter of apex angle θ. Compliant half-space.
> 
> One final observation. As with Hert'z contact theory, the contact force between
> ```

typo: spurious apostrophe Hert'z -> Hertz
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JviRECKxI3LhcnHri:-O8JviRECKxI3LhcnHrj:bxrx9hw) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L69)):*
> ```objc
> degrade numerical conditioning and therefore users must choose a value that is
> acceptable for their application. Experience shows that for modeling "rigid"
> (once again, stiff) objects, there is no much gain in accurately resolving
> ```

typo: no -> not
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 71 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8Jvloj94QM1OCalLPE:-O8Jvloj94QM1OCalLPF:b-wv7pu6) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L71)):*
> ```objc
> (once again, stiff) objects, there is no much gain in accurately resolving
> penetrations below the submillimeter range (~10⁻⁴ m). Therefore moduli in the
> order of 10⁷-10⁸ Pa will be more than enough, we no good practical reason to use
> ```

typo: we -> with
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 128 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JsntW96oD7kAde4Pf:-O8JsntW96oD7kAde4Pg:baf2a9g) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L128)):*
> ```objc
> advantages over traditional EFM
>   - Hydroelastic contact generalizes to arbitrary non-convex geometry
>   - Large _deformations_ (interpenetration) are allowed
> ```

BTW consider "deformations" (in quotes) rather than _italics_. Quotes are better assuming you are trying to emphasize that these are fictional (since there isn't really any deformation).
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 135 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JwnOL94wqepU9I0sh:-O8JwnOL94wqepU9I0si:bjl5yzl) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L135)):*
> ```objc
> 
> Given the clear connection between hydroelastic contact and EFM, we use this
> analogy to derive analytical formula to estimate contact forces. More precisely,
> ```

typo: derive -> derive an
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 155 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8Jx4tq3v8zUldMRC2Y:-O8Jx4tq3v8zUldMRC2Z:b97t75l) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L155)):*
> ```objc
> where κ = κᵃ⋅κᵇ/(κᵃ+κᵇ) is the effective stiffness and κᵃ = Eᵃ/Hᵃ and κᵇ = Eᵇ/Hᵇ
> are the stiffness of bodies A and B respectively. V is the volume the original
> geometries would overlap if the did not deform.
> ```

typo: the -> they
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JxS5L15NlqDgsOVxe:-O8JxS5L15NlqDgsOVxf:bmoiqyg) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L162)):*
> ```objc
> Hydroelastic contact model, where the balance of normal stresses (pressure)
> determines the location of the contact surface. Still, we find that this
> derivation leads to exactly the same result in (2).
> ```

BTW cool!
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8Jsd5K7yDtlv0p9QdZ:-O8Jsd5L7eGpXT5Cc7fX:bvxwk02) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L172)):*
> ```objc
> We use the EFM approximation (1) to model the normal stress (pressure) that
> results from deforming each body A and B amounts ϕᵃ(x) and ϕᵇ(x) respectively.
> With this, the balance of momentum at each point on the contact surface is
> ```

minor: momentum -> pressure

**Review by amcastro-tri — COMMENTED** [review]
Thanks @sherm1. Comments addressed and added the missing schematics. PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-:-O9Bn1wk50kbVTOMZJlQ:b-f0jcta)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8Jx_N45CRDbw2jD9Co:-O9BJWd70nKLn7jo96H7:b-fznogt) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding a short paragraph on how this section could be useful to a person using Drake. How should someone make use of this information?
</blockquote></details>

Good idea, done.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JuZLsAWSe1-otrKdd:-O9BH9OU8xiNDTydAXJ4:b-ac4ai3) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW later you re-use "x" to mean a generic point on the contact surface, while here it is a scalar penetration depth. It's confusing to use the same symbol for two different things in the same paper. Consider using some other symbol for the few places where penetration depth is used in this section -- maybe "d" or "δ"?
</blockquote></details>

good point. I use `r` now for the position vector. This is a common notation in many physics books.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JtdA67J55XicGOwsN:-O9BO5Ns6g9-2WewMJz1:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW what is the source for these formulas? KL Johnson? I'd like to double check in case of typos or whatever.
</blockquote></details>

Done
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O8JxS5L15NlqDgsOVxe:-O9BQXqjCg_57VVTi_h2:b-ucfknh) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb8057804dc49e7e2cd32c1982da7639f00a6104/multibody/plant/doxygen_hydroelastic_parameters.h#L162)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW cool!
</blockquote></details>

Thanks!

**Review by sherm1 — COMMENTED** [review]
Beautiful, thanks! Feature :lgtm_strong: with one ignorable suggestion.
I noticed that you have both the png and svg checked in here although only the png is used. I presume that's intentional for future flexibility; just noting it in case not.

+@jwnimmer-tri for platform review per rotation, please

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-:-O9BtjXQAqCx1kZGF6ws:b-nl75m0)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 39 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9BtB7G4ZfiHN-JChXi:-O9BtB7G4ZfiHN-JChXj:b-1bwkbh) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L39)):*
> ```objc
> between a body of a given geometric shape with a half-space. These formulas are
> obtained by substituting an estimate of the intersection volume as a function of
> a small interpenetration distance `x`, see column "Overlap Volume V" in the
> ```

BTW the notation is fine now. One thing to consider: here penetration distance is x and below it is ϕ. You _could_ make that slightly more clear (I think) by using ϕ for penetration here and ϕ(r) below. Feel free to ignore.

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none)

:lgtm: platform

> Reviewed 1 of 2 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-:-O9FbIen-YXH1EmI929i:bhnmqoy)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9Fbpe56f_X2SLEpukL:-O9Fbpe56f_X2SLEpukM:bdyt1mk) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L1)):*
> ```objc
> /** @file
> ```

In our dozens of existing doxygen header files, the word `doxygen` appears as the last word in the filename, not the first.  The pattern is `foo_bar_doxygen.h` not `doxygen_foo_bar.h`.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FgNbR3XEjmgyDGX3K:-O9FgNbR3XEjmgyDGX3L:b5vnhsh) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L62)):*
> ```objc
> between a sphere of effective radius R = Rᵃ⋅Rᵇ/(Rᵃ+Rᵇ) and a half-space.
> 
> @subsection study_case_manipuland Study Case: Manipuland resting on a table
> ```

BTW The `@section` and `@subsection` names like `study_case_manipuland` are global identifiers in our Drake Doxygen.

If they ever get accidentally reused elsewhere in Drake docs for a different section, very bad things will happen -- doxygen will silently and arbitrarily choose one of the two section titles, make all of the references link to it, and _re-title_ the other section to use the linked name.

Consider making the identifiers here less ambiguious and maybe even all of them should share a common prefix like "hydro_param_{something}" for consistency, clarity, and safety.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 116 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FeC_-3F9j4_rmjP8w:-O9FeC_-3F9j4_rmjP8x:b-xgvzh9) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L116)):*
> ```objc
> two contacting bodies. 
> 
> @image html drake/multibody/plant/images/elastic_foundation.png "Figure 1: Elastic Foundation Model." width=35%
> ```

There is no need to convert to png and commit both svg and png into git.  The Doxygen can directly refer to the svg image, and it shows up fine.  You can just delete the png files.

Right now the svg is a full-size A4 page.  To crop the extra whitespace on the page, open in Inkscape, select document properties, then click the "resize to content" button.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 212 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FfghP398YeClACM67:-O9FfghP398YeClACM68:b-dnx7et) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L212)):*
> ```objc
> The total contact force is found by integrating (5) over the contact surface
> <pre>
>   fₙ(r) = ∫p(r)d²r = κ⋅∫ϕ(r)d²r.                                            (6) 
> ```

nit This line and at least one more above end with trailing whitespace.  Please remove all trailing whitespace from the whole file.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 252 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FhXKv20n6VLFsJxV4:-O9FhXKv20n6VLFsJxV5:b-xrm6gt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L252)):*
> ```objc
>       penetration depth, the modulus would have to increase with the scale of
>       the geometry.
>   - Notes on choosing a value:
> ```

These notes are harmfully wrong, I believe?  Is this PR the place we should fix the lies in this section?  Seems like yes to me.  Or maybe at least the new xref should move down to here, instead of 20 lines up above.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: 2 unresolved discussions

___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 39 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9BtB7G4ZfiHN-JChXi:-O9Flg9iCSHuDTpM3GvY:bck96vq) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the notation is fine now. One thing to consider: here penetration distance is x and below it is ϕ. You _could_ make that slightly more clear (I think) by using ϕ for penetration here and ϕ(r) below. Feel free to ignore.
</blockquote></details>

not sure, I still like x for penetration and ϕ(r) for the SDF. 
I could maybe use `u` or `t` instead of `x`? I don't want to use `d` because we use that for H&C dissipation, and we use `h` for time step.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 62 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FgNbR3XEjmgyDGX3K:-O9FnGox9IKOINn4qtpt:bfbq99i) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The `@section` and `@subsection` names like `study_case_manipuland` are global identifiers in our Drake Doxygen.

If they ever get accidentally reused elsewhere in Drake docs for a different section, very bad things will happen -- doxygen will silently and arbitrarily choose one of the two section titles, make all of the references link to it, and _re-title_ the other section to use the linked name.

Consider making the identifiers here less ambiguious and maybe even all of them should share a common prefix like "hydro_param_{something}" for consistency, clarity, and safety.
</blockquote></details>

Good point, done.
___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 116 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FeC_-3F9j4_rmjP8w:-O9FocWF8BTprs60hY_X:b6lqmqd) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L116)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is no need to convert to png and commit both svg and png into git.  The Doxygen can directly refer to the svg image, and it shows up fine.  You can just delete the png files.

Right now the svg is a full-size A4 page.  To crop the extra whitespace on the page, open in Inkscape, select document properties, then click the "resize to content" button.
</blockquote></details>

wow, I didn't know that! great tip!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: 1 unresolved discussion

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: 2 unresolved discussions

___
*[`multibody/plant/hydroelastic_parameters_doxygen.h` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FqOr6AqaxUhly__lb:-O9FqOr6AqaxUhly__lc:b-dkla8z) ([raw file](https://github.com/RobotLocomotion/drake/blob/6afa73464584d3406d6def4fd08754e1a952fbd1/multibody/plant/hydroelastic_parameters_doxygen.h#L57)):*
> ```objc
> Cylindrical punchᵃ |                                R                                |@f$\pi R^2 x@f$              |@f$\pi E R x@f$
> Sphereᵇ            |                                R                                |@f$\pi R x^2@f$              |@f$\pi E x^2@f$
> Conic indenterᶜ    | @f$R\left(\frac{1-\sin(\theta)}{1+\sin(\theta)}\right)^{1/2}@f$ |@f$\pi/3\tan^2(\theta)x^3@f$ |@f$\frac{\pi}{3}\frac{E}{R}x^3\tan^2(\theta)\left(\frac{1+\sin(\theta)}{1-\sin(\theta)}\right)^{1/2}@f$
> ```

@sherm1 I decided to update the conic indenter formulas to be expressed in terms of the base of its radius and apex angle, instead of an arbitrary depth parameter H. I think that makes for a more consistent set of results, where all the pressue fields use the EFM with maximum pressure E at the point of maximum distance. PTAL.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: 2 unresolved discussions

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 252 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FhXKv20n6VLFsJxV4:-O9FuxS5DlJGsUQo1fys:bobzwnt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L252)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These notes are harmfully wrong, I believe?  Is this PR the place we should fix the lies in this section?  Seems like yes to me.  Or maybe at least the new xref should move down to here, instead of 20 lines up above.
</blockquote></details>

good catch Jeremy. I should've caught that earlier. I removed all text that is not based on true facts and added a few edits.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: 1 unresolved discussion

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21987)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

___
*[`multibody/plant/doxygen_hydroelastic_parameters.h` line 39 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9BtB7G4ZfiHN-JChXi:-O9G07dFAWk0LFyRc2Pv:b-gh5ywm) ([raw file](https://github.com/RobotLocomotion/drake/blob/f12182b48fc906386470ec33b0bb05e7147c8052/multibody/plant/doxygen_hydroelastic_parameters.h#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not sure, I still like x for penetration and ϕ(r) for the SDF. 
I could maybe use `u` or `t` instead of `x`? I don't want to use `d` because we use that for H&C dissipation, and we use `h` for time step.
</blockquote></details>

I'm happy with `x` for penetration. 
___
*[`multibody/plant/hydroelastic_parameters_doxygen.h` line 57 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21987#-O9FqOr6AqaxUhly__lb:-O9G3PsU5ryA-NdehX-g:b-ovwaw7) ([raw file](https://github.com/RobotLocomotion/drake/blob/6afa73464584d3406d6def4fd08754e1a952fbd1/multibody/plant/hydroelastic_parameters_doxygen.h#L57)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

@sherm1 I decided to update the conic indenter formulas to be expressed in terms of the base of its radius and apex angle, instead of an arbitrary depth parameter H. I think that makes for a more consistent set of results, where all the pressue fields use the EFM with maximum pressure E at the point of maximum distance. PTAL.
</blockquote></details>

Good idea.

**Comment by jwnimmer-tri** [comment]
FYI if you run our Doxygen build with `--verbose`, it has this warning:

```
[doxygen] drake/multibody/plant/hydroelastic_parameters_doxygen.h:229: warning: multiple use of section label 'hydro_params_analytical' while adding section, (first occurrence: drake/multibody/plant/hydroelastic_parameters_doxygen.h, line 202)
```

**Pull request merged**
