### PR TITLE
Tease apart models_filegroup vs install_data

### LINKED ISSUE #11010: install_data: Make explicit, remove unused cruft
(Warning: Rant-y)

At present, `install_data` implicitly names its target `models`. I've always been confused by this, and I want that to change.

Additionally, there are *zero* usages of any customization of `prod_models_prefix` or `test_models_prefix`. Those should be explicitly defined too, rather than arbitrary prefixes. The `extra_prod_models` story also makes me sad.

This should be broken into two parts:
* Model globbing should be consolidated, to permit globbing install + test data. (Test data isn't even installed; why is it even part of `install_data`???)
* Installation for models should be consolidated (and named specifically for `drake`, as it does that with its `dest` prefix).

EDIT: More complaint: Why do we even concatenate `prod_models` + `test_models` into `models`??? We should only have `models` and `test_models`; if anything, `test_models` should depend on `models` (if we even really want that combination.)

Ran into this when considering #11009

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Delete unused `PendulumWithFriction.urdf`.

---

I've tested locally and the list of installed files is the same between this PR and the master branch.

Closes #11010.

Towards #15774.

FYI https://drake.mit.edu/stable.html#model-files

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18923)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI I think you get right of first refusal for this review.  If you're busy, we can push it to @sammy-tri instead.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 34 of 34 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18923)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, beautimous! Small nit on globbing, though maybe it's pre-existing.

> Reviewed 23 of 34 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18923#-:-NPXlOLk6XlTpoQqHSjQ:b-drk5qs)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/skylark/drake_data.bzl` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18923#-NPXkzhcDhnCEIFGV1Jk:-NPXkzhdC7znHxgCz9cX:b-a07odz) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ece06b5372da38c26db7a5b09c05d88249d72c1/tools/skylark/drake_data.bzl#L36)):*
> ```Starlark
>     ]
>     exclude = glob_exclude + [
>         "**/test/*",
> ```

nit (pre-existing) It's not clear to me how intuitive this exclude pattern will be for `testonly = True`.

Possible options:
- TODO
- `glob_exclude` gains these defaults only when `testonly = False`
- The default values are these, explicitly, perhaps via global constant `DEFAULT_GLOB_EXCLUDE`, but users can override them. Docstring says they should?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18923)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`tools/skylark/drake_data.bzl` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18923#-NPXkzhcDhnCEIFGV1Jk:-NPXyEmO8_y2qdqQmTjR:bmxjmc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ece06b5372da38c26db7a5b09c05d88249d72c1/tools/skylark/drake_data.bzl#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (pre-existing) It's not clear to me how intuitive this exclude pattern will be for `testonly = True`.

Possible options:
- TODO
- `glob_exclude` gains these defaults only when `testonly = False`
- The default values are these, explicitly, perhaps via global constant `DEFAULT_GLOB_EXCLUDE`, but users can override them. Docstring says they should?
</blockquote></details>

Aha!  Thanks, I'd meant to circle back here and totally forgot.

There are no tests that use this.  I've update the docs.

PTAL.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18923)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`tools/skylark/drake_data.bzl` line 36 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18923#-NPXkzhcDhnCEIFGV1Jk:-NPYdigU3iYHsu29bgJo:b-o58whx) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ece06b5372da38c26db7a5b09c05d88249d72c1/tools/skylark/drake_data.bzl#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Aha!  Thanks, I'd meant to circle back here and totally forgot.

There are no tests that use this.  I've update the docs.

PTAL.
</blockquote></details>

OK Sweet ,thanks!

**Pull request merged**
