### PR TITLE
[RgbdSensor] Expose `X_PB_` via a const getter function

### LINKED ISSUE #21788: [RgbdSensor] `X_PB_` is not externally accessible
### Problem
- In `RgbdSensor`, the member `X_PB_` is private and cannot be accessed externally. However, it can be pretty useful to access it.
- Both [RgbdSensorAsync](https://github.com/RobotLocomotion/drake/blob/fb4a2eb7d5b4332549441a35041126876f9ef728/systems/sensors/rgbd_sensor_async.h#L130-L131) and [SimRgbdSensor](https://github.com/RobotLocomotion/drake/blob/fb4a2eb7d5b4332549441a35041126876f9ef728/systems/sensors/sim_rgbd_sensor.h#L68) expose their X_PB transforms. I don't see a reason why `RgbdSensor` shouldn't also do the same.

### Solution
- It is straightforward to expose the private member `X_PB_` through a const getter function:
  ```c++
  const RigidTransformd& RgbdSensor::X_PB() const { return X_PB_; }
  ```
  similar to `X_BC()` and `X_BD()`.
 - It is also straightforward to create Python bindings for this function.
 
### Pull request
 The above solution is implemented in #21789

### PR DESCRIPTION
**Pull request by siddancha**
Fixes #21788

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Good day, @siddancha . I’m assigning +@SeanCurtis-TRI as the most relevant team member to assist with this pull request. If you already had a different team member in mind, please let us know. To @SeanCurtis-TRI, feel free to delegate in case there is someone else more suitable.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-:-O3mfEVsEA7agfSGqVrN:b-mysaha)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @siddancha)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

I can't imagine why it wasn't exposed in the first place.

+@EricCousineau-TRI -- back to you for platform.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-:-O3mhl49BzqUIH4y9awT:b-91qlsq)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @siddancha)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-:-O3mij7cAuaBQy5Fc11V:bpqxd5f)* status: missing label for release notes (waiting on @siddancha)

**Review by siddancha — COMMENTED** [review]
:lgtm: 

I don't have drake developer permissions, so I can't add a label for release notes. Pls help?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-:-O3mmvB63HMeV1k3CuCV:b-oeqyc3)* status: missing label for release notes (waiting on @siddancha)

**Comment by SeanCurtis-TRI** [comment]
+(release notes: fix)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot ok to test

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot test this please

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(release notes: fix) 
+(release notes: feature) 

I changed my mind -- the new API is a new feature even though its lack *feels* like a defect that got fixed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-:-O3moc8_Bg_uua0BT-VQ:b-5j567q)* status: 1 unresolved discussion

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-O3moJIGAkwNvgHVP0U9):*
When we merge this

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789)* status: 1 unresolved discussion

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-O3momRJ4L_UQj3m5B5t):*
When we merge this, let's make sure the mention clearly mentions new bindings.

**Review by siddancha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21789)* status: 1 unresolved discussion

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-O3momRJ4L_UQj3m5B5t):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

When we merge this, let's make sure the mention clearly mentions new bindings.
</blockquote></details>

@SeanCurtis-TRI Sounds good! Ready to merge!

**Comment by SeanCurtis-TRI** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21789#-O3momRJ4L_UQj3m5B5t):*
<details><summary><i>Previously, siddancha (Siddharth Ancha) wrote…</i></summary><blockquote>

@SeanCurtis-TRI Sounds good! Ready to merge!
</blockquote></details>

Huzzah! Thanks for the ping.

**Pull request merged**
