### PR TITLE
Locate pkg-config using drake-specific which()

### PR DESCRIPTION
**Pull request by jamiesnape**
Omitted from #8602, it appears.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8629)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8629#-:-LAPUhU1DJP2BfnL_kc0:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8629#-:-LAP_we49XPefg8yTELF:bnfp4nl)*

**Pull request merged**
