### PR TITLE
[plant] Shore up enum-string conversion implementation

### LINKED ISSUE #17524: Pattern for using constexpr std::array
From @rpoyner-tri in the review of #17400:

> I feel like some style suggestions against using constexpr std::array might be in order, precisely because it's too easy to make uninitialized data with it

@jwnimmer-tri provided a nice pattern so that we get a compiler error:

```diff
--- a/multibody/plant/multibody_plant_config_functions.cc
+++ b/multibody/plant/multibody_plant_config_functions.cc
@@ -42,14 +42,19 @@ constexpr const char* ContactModelToChars(ContactModel contact_model) {
   }
 }
 
-constexpr auto MakeContactModelPair(ContactModel value) {
-  return std::pair(value, ContactModelToChars(value));
-}
-
-constexpr std::array<std::pair<ContactModel, const char*>, 3> kContactModels{{
-  MakeContactModelPair(ContactModel::kPointContactOnly),
-  MakeContactModelPair(ContactModel::kHydroelasticsOnly),
-  MakeContactModelPair(ContactModel::kHydroelasticWithFallback),
+struct ContactModelItem {
+  constexpr ContactModelItem(ContactModel value_in)
+    : value(value_in),
+      name(ContactModelToChars(value_in)) {}
+
+  const ContactModel value;
+  const char* const name;
+};
+
+constexpr std::array<ContactModelItem, 3> kContactModels{{
+  {ContactModel::kPointContactOnly},
+  {ContactModel::kHydroelasticsOnly},
+  {ContactModel::kHydroelasticWithFallback},
 }};
 
 // Take an alias to limit verbosity, especially in the constexpr boilerplate.
```

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17524.  Follow-up from #17400.

+@amcastro-tri for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Simply beautiful, thanks. :lgtm_strong: 
+@rpoyner-tri for platform review please.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529#-:-N6mnZlp8ulxXJDovXJF:bwqhdj1)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant_config_functions.cc` line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17529#-N6mmepB2BwiyhY9fuUW:-N6mmepB2BwiyhY9fuUX:bpdrp83) ([raw file](https://github.com/robotlocomotion/drake/blob/c99e52f7fb3c912359c3050422aee4a24024983b/multibody/plant/multibody_plant_config_functions.cc#L67)):*
> ```cpp
> // when somebody add a new value to the enum. New values must be listed here
> // as well as in the list of (enum, name) pairs kContactReps below.
> constexpr const char* EnumToChars(ContactRep contact_model) {
> ```

nit, not part of this PR, but `contact_model` here seems like a copy/pasta from previous pattern?
I'd say `surface_representation` or `surface_tessellation` better represent the name of this variable.
___
*[`multibody/plant/multibody_plant_config_functions.cc` line 78 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17529#-N6mn0npDOg8Wp532Yk3:-N6mn0npDOg8Wp532Yk4:bpcy72s) ([raw file](https://github.com/robotlocomotion/drake/blob/c99e52f7fb3c912359c3050422aee4a24024983b/multibody/plant/multibody_plant_config_functions.cc#L78)):*
> ```cpp
> template <typename Enum>
> struct NamedEnum {
>   // NOLINTNEXTLINE(runtime/explicit)
> ```

for my own education. Why is it that the linter complains here? or why is it we cannot mark this `explicit`? does it collide with `constexpr`?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[`multibody/plant/multibody_plant_config_functions.cc` line 78 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17529#-N6mn0npDOg8Wp532Yk3:-N6mopel5FQ_tsvNvKO9:b-fgrz7k) ([raw file](https://github.com/robotlocomotion/drake/blob/c99e52f7fb3c912359c3050422aee4a24024983b/multibody/plant/multibody_plant_config_functions.cc#L78)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for my own education. Why is it that the linter complains here? or why is it we cannot mark this `explicit`? does it collide with `constexpr`?
</blockquote></details>

I think the implicit conversion is desired behavior here, to make the std::array definitions less verbose. Since we have a 1-arg constructor, the `explicit` lint will complain, so the lint-control comment should be read as "no, i really mean it this time."

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @amcastro-tri and @rpoyner-tri)

___
*[`multibody/plant/multibody_plant_config_functions.cc` line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17529#-N6mmepB2BwiyhY9fuUW:-N6mqg_m48f7UauV1oTa:byey3r8) ([raw file](https://github.com/robotlocomotion/drake/blob/c99e52f7fb3c912359c3050422aee4a24024983b/multibody/plant/multibody_plant_config_functions.cc#L67)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

fyi, Docs for `HydroelasticContactRepresentation` state: "Reports on how a hydroelastic contact surface is represented".
So it'd seem `surface_representation` or similar is probably best.
</blockquote></details>

Done.

Using the same arg name throughout leaves less room for mistakes during future repetitions on the pattern in case we add even more kinds of enum here.
___
*[`multibody/plant/multibody_plant_config_functions.cc` line 78 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17529#-N6mn0npDOg8Wp532Yk3:-N6mpkTMAH91kc4I9VYU:b-b2lt81) ([raw file](https://github.com/robotlocomotion/drake/blob/c99e52f7fb3c912359c3050422aee4a24024983b/multibody/plant/multibody_plant_config_functions.cc#L78)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for my own education. Why is it that the linter complains here? or why is it we cannot mark this `explicit`? does it collide with `constexpr`?
</blockquote></details>

If we add `explicit` here, the compiler will not accept the array's initializer lists anymore (unless we put `NamedEnum<...>` around each list item, which would be quite noisy).

`multibody_plant_config_functions.cc:88:2: error: converting to 'NamedEnum<ContactModel>' from initializer list would use explicit constructor 'constexpr NamedEnum<Enum>::NamedEnum(Enum) [with Enum = ContactModel]'`

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17529#-:-N6mr6weC94DU_6YxMq9:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),amcastro-tri (waiting on @jwnimmer-tri)

**Pull request merged**
