### PR TITLE
Adds an "under construction" notice to sphinx

### PR DESCRIPTION
**Pull request by RussTedrake**
As discussed on the drake developer channels, this PR puts a big warning on the front page telling everyone that we are making API-breaking changes.  

**I consider this a green light for the developers.  let's move fast!**

I also took the chance to update the credits.  Developers -- please add yourself if I didn't add you already, and feel free to add a link under your name.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3678)

### CODE REVIEW

**Comment by liangfok** [comment]
When I generate the documentation, I see the following warning:

```
/home/liang/dev/drake-distro-3/drake/doc/index.rst:30: WARNING: Duplicate explicit target name: "toyota research institute".
```

I'm still trying to root cause it.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-:-KTJxAuizY-ndT-mUX1-:bq4kbb2)*

**Comment by liangfok** [comment]
This might offer an explanation: http://stackoverflow.com/questions/5464627/how-to-have-same-text-in-two-links-with-restructured-text

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-:-KTJyrAgiIxxxWIvqQ4K:bkoxl9e)*

**Comment by liangfok** [comment]
:lgtm: The changes look good. I just left a couple BTW comments that should prevent the above-mentioned warning from appearing.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/index.rst, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTK2dBmZlRbJIk6uruo:-KTK2dBnVEET8VBsbIZv:bl8ng4f) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/index.rst#L34)):*
BTW, consider changing:

> `Toyota Research Institute <http://tri.global/>`_

to be:

> `Toyota Research Institute <http://tri.global/>`__

to avoid possible "Duplicate explicit target name" warning.

---

*[drake/doc/index.rst, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTK2pwPgkJv3NVo3zNs:-KTK2pwPgkJv3NVo3zNt:b2e1bd8) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/index.rst#L107)):*
BTW, consider changing:

> `Toyota Research Institute <http://tri.global>`_

to be:

> `Toyota Research Institute <http://tri.global/>`__

to avoid possible "Duplicate explicit target name" warning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-:-KTK2wKv8dHlt_Iymsj6:bpjp5s0)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/credits.rst, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTKcHGT3JQYVlyQt098:-KTKEmRQDLz7X9kC-hdy:b-ggxcrf) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/credits.rst#L9)):*
> ```reStructuredText
> 
> .. this is modeled directly, and shamelessly, on: http://eigen.tuxfamily.org/index.php?title=Main_Page#Credits
> ```

BTW, Jamie Snape, Bill Hoffman, Brad King, Matthew Woehlke, Betsy McPhail

---

*[drake/doc/index.rst, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTKcDEiw_RhZHE1YPb6:-KTKcDEiw_RhZHE1YPb7:b-k43msq) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/index.rst#L107)):*
> ```reStructuredText
> ================
> 
> The Drake developers would like to acknowledge significant supported from the `Toyota Research Institute <http://tri.global>`_, `DARPA <http://www.darpa.mil/>`_, the `National Science Foundation <https://nsf.gov/>`_, the `Office of Naval Research <http://www.onr.navy.mil/>`_, `Amazon.com <https://www.amazon.com/>`_, and `The MathWorks <http://www.mathworks.com/>`_.
> ```

BTW typo, s/suppported/support

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-:-KTKc3g3odFfpV38dU7j:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/credits.rst, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTKcHGT3JQYVlyQt098:-KTMZ0joqS0y6ecbYW_c:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/credits.rst#L9)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, Jamie Snape, Bill Hoffman, Brad King, Matthew Woehlke, Betsy McPhail
</details>
done

---

*[drake/doc/index.rst, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTK2dBmZlRbJIk6uruo:-KTMZ2EnvMqSAIl1voNB:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/index.rst#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider changing:
> 
> > `Toyota Research Institute <http://tri.global/>`_
> 
> to be:
> 
> > `Toyota Research Institute <http://tri.global/>`__
> 
> to avoid possible "Duplicate explicit target name" warning.
</details>
done

---

*[drake/doc/index.rst, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTKcDEiw_RhZHE1YPb6:-KTMZ3T0sHP8EK828fm7:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/index.rst#L107)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW typo, s/suppported/support
</details>
done

---

*[drake/doc/index.rst, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3678#-KTK2pwPgkJv3NVo3zNs:-KTMZ4sP2PWXImIOVOkj:bb7f2mf) ([raw file](https://github.com/robotlocomotion/drake/blob/731457419b4065fe97565508dcd0e86c66cacd51/drake/doc/index.rst#L107)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, consider changing:
> 
> > `Toyota Research Institute <http://tri.global>`_
> 
> to be:
> 
> > `Toyota Research Institute <http://tri.global/>`__
> 
> to avoid possible "Duplicate explicit target name" warning.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3678)*

**Pull request merged**
