### PR TITLE
Remove the workspace entry for find_protobuf_cmake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Using a workspace to identify these files isn't terribly useful, because there isn't great cause for allowing Drake downstreams to replace them with a different copy.  Using `new_local_repository` is a bit tricky to get right so we are trying to avoid it, thus its worth just dropping this down to package-level dependencies instead of a workspace.

Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7744)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all review, please.

FYI @jamiesnape or @clalancette feel free to jump in for review if you desire.

**Comment by clalancette** [comment]
No objections from me, though this was at the behest of @jamiesnape, so we should make sure it is good with him.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7744#-:-L2ekHfM0po5vfDIT1qG:b-k1r38f)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7744#-:-L2eokJBRn_SaYG3v4J5:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a minor BTW.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7744#-L2f5vdiZ3ZulLKFKi0V:-L2f5vdiZ3ZulLKFKi0W:b-dnlvtk) ([raw file](https://github.com/robotlocomotion/drake/blob/6e44b3b22f7e578b97f2283827f455db75abb23e/third_party/BUILD.bazel#L28)):*
> ```Python
> 
> exports_files(
>     glob(["com_kitware_gitlab_cmake_cmake/**"]),
> ```

BTW Does this glob capture directories (as `.../**`), or just files (I would think with `.../**/*`)?

If it's directories, can this add a comment indicating as much? (And stating that it's fine for `install`, possibly because Bazel will get confused by package boundaries?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7744#-:-L2f7ovCyMsnp9jAv6CK:b-lsk0ew)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/BUILD.bazel, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7744#-L2f5vdiZ3ZulLKFKi0V:-L2fAI3OuuE2jfSgex9v:b-9oyxt7) ([raw file](https://github.com/robotlocomotion/drake/blob/6e44b3b22f7e578b97f2283827f455db75abb23e/third_party/BUILD.bazel#L28)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Does this glob capture directories (as `.../**`), or just files (I would think with `.../**/*`)?

If it's directories, can this add a comment indicating as much? (And stating that it's fine for `install`, possibly because Bazel will get confused by package boundaries?)
</blockquote></details>

OK Nope, its just files.  I added a `print()` and it shows the result as:
```
"com_kitware_gitlab_cmake_cmake/3.10/Copyright.txt",
"com_kitware_gitlab_cmake_cmake/3.10/Modules/FindMatlab.cmake",
"com_kitware_gitlab_cmake_cmake/3.10/Modules/FindProtobuf.cmake",
"com_kitware_gitlab_cmake_cmake/3.10/Modules/MatlabTestsRedirect.cmake",
"com_kitware_gitlab_cmake_cmake/3.10/vendor.txt"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7744)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Pull request merged**
