### PR TITLE
setup: Upgrade to Bazel 0.14.1

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Concurrently, document support for CLion 2018.1.2.

---

Tested manually in CLion:
- debugging / inspecting / single-stepping a unit test;
- jump to include at point;
- jump to definition of symbol at point.
- typos in headers show as non-mangled include paths.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8988)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for review per schedule, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [soonho-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8988#-:-LEyS49Z5ra4ynrCpgEp:bnfp4nl)*

**Pull request merged**
