### PR TITLE
[pydrake] Unify binding strategy for config structs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17112.

Marked as "priority: high" to avoid merge conflict hell.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@SeanCurtis-TRI for platform review, please.

\CC @EricCousineau-TRI @zachfang FYI

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: I really like the concision inherent in binding via serialization.

I *do* have a couple of questions

1. Serialization has been added that ostensibly serializes `RenderLabel` and `Rgba`. Do those serialize. I wouldn't have thought so. But I've not worked directly with any of the YAML functionality, so I don't have an intuitive grasp of where the sharp edges are.
2. This doesn't introduce any tests on the newly serializable classes. Is there a plan for filling those in?

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618#-:-N7pu7re11XnFcF4kVQl:bvd8jn3)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`geometry/drake_visualizer_params.h` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqPDDAfsh5gXudjyk:-N7pqPDDAfsh5gXudjyl:biz4rdf) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/drake_visualizer_params.h#L17)):*
> ```objc
>   void Serialize(Archive* a) {
>     a->Visit(DRAKE_NVP(publish_period));
>     a->Visit(DRAKE_NVP(role));
> ```

Does `Role` serialize?
___
*[`geometry/drake_visualizer_params.h` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqQvhD_vqpS3UXILp:-N7pqQvhD_vqpS3UXILq:b-6fidv3) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/drake_visualizer_params.h#L18)):*
> ```objc
>     a->Visit(DRAKE_NVP(publish_period));
>     a->Visit(DRAKE_NVP(role));
>     a->Visit(DRAKE_NVP(default_color));
> ```

Does `Rgba` serialize?
___
*[`geometry/render_gl/render_engine_gl_params.h` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqAND-aWhXihMsWFk:-N7pqAND-aWhXihMsWFl:b-khs5wh) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/render_gl/render_engine_gl_params.h#L17)):*
> ```objc
>   template <typename Archive>
>   void Serialize(Archive* a) {
>     a->Visit(DRAKE_NVP(default_label));
> ```

Does `RenderLabel`?
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqruK-j_qbVcDDr25:-N7pqruK-j_qbVcDDr26:b3x4ao1) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/render_vtk/render_engine_vtk_params.h#L20)):*
> ```objc
>   void Serialize(Archive* a) {
>     a->Visit(DRAKE_NVP(default_label));
>     a->Visit(DRAKE_NVP(default_diffuse));
> ```

BTW The color types of this struct should match those for the gl renderer (i.e., using `Rgba`). Does this interfere with your efforts here at all?
___
*[`bindings/pydrake/geometry_py_render.cc` line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7ps1GGAfGyn2waLyw6:-N7ps1GGAfGyn2waLyw7:b1bu68d) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/bindings/pydrake/geometry_py_render.cc#L322)):*
> ```cpp
>     constexpr auto& cls_doc = doc_geometry.RenderEngineVtkParams;
>     py::class_<Class> cls(m, "RenderEngineVtkParams", cls_doc.doc);
>     cls  // BR
> ```

BTW (meta) From a formatting perspective, this break seems....odd. I assume this is akin to a terminal comma (the addition of further `def` will minimize the churn of the previous lines)? If that's the motivation, for this kind of class, that seems highly speculative.

**Review by jwnimmer-tri — COMMENTED** [review]
(1) See inline discussion below.

(2) For the `a->Visit(DRAKE_NVP(...))` lines, the only way I've thought of to unit test them is to add a congruent line of test code.  Since the future hazard we're guarding against is that someone adds a new field but forgets to visit it, unit tests that repeat the visited fields do not offer any power.  It's the unit testing sin of copy-pasting the implementation into the test.  I haven't been able to think of any property-based unit tests that check for correct visitation. If you have ideas to get around that, I'd love to hear them!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618#-:-N7pwn9eCj1DEFnO5xzb:bs2plb)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`geometry/drake_visualizer_params.h` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqPDDAfsh5gXudjyk:-N7pwoyxAqKZnEPZf8Ps:b95562j) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/drake_visualizer_params.h#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Does `Role` serialize?
</blockquote></details>

Serialize is for more than just YAML.  It's a generic visitation scheme whose promise is to provide for introspection of an object's member fields.

In the future, we could add a YAML-related free-function overload that knows how to serialize Role and/or Rgba, but for now visiting them only for the purposes of bindings is a fine use of serialization.
___
*[`geometry/render_vtk/render_engine_vtk_params.h` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqruK-j_qbVcDDr25:-N7pxOkQ4t-L453KoVMy:b-4ui57r) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/render_vtk/render_engine_vtk_params.h#L20)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The color types of this struct should match those for the gl renderer (i.e., using `Rgba`). Does this interfere with your efforts here at all?
</blockquote></details>

For the purposes of python bindings, the visitation will just bind whatever is declared as the C++ member field type, and that seems OK to me.
___
*[`bindings/pydrake/geometry_py_render.cc` line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7ps1GGAfGyn2waLyw6:-N7pxidW6WP2295h4Mho:b4hw8qx) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/bindings/pydrake/geometry_py_render.cc#L322)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW (meta) From a formatting perspective, this break seems....odd. I assume this is akin to a terminal comma (the addition of further `def` will minimize the churn of the previous lines)? If that's the motivation, for this kind of class, that seems highly speculative. 
</blockquote></details>

Right, it's a question of how much thought (entropy) we want to put into the formatting here.  I went with "Keep the boilerplate 100% identical for all classes, without trying to read the tea leaves of their future evolution."

**Review by SeanCurtis-TRI — COMMENTED** [review]
(2) A mechanism that could detect "missing" fields would truly be wonderful. And in a universe where we have such a thing, then the new tests you've done in the bindings would be compact and sufficient.

However, we don't have that mechanism. It is absolutely true that the old tests could not tell if a newly added field has been mistakenly skipped in `Serialize()`. But the old tests did successfully broadcast which fields we *knew* to be visited. It feels that we've lost that information. And it's not clear that it is to Drake's benefit. In fact, the test of `repr()` would be the *only* place where the evaluation of our expectation of what has been visited is even attempted. Now, it exists nowhere.

That said, I'm not going to block on this.

:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618#-:-N7qDhxpACs-Exv3S6gH:b-mntswh)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`geometry/drake_visualizer_params.h` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqPDDAfsh5gXudjyk:-N7qD8PfAKciCqBeSkBE:b9gwpxr) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/drake_visualizer_params.h#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Serialize is for more than just YAML.  It's a generic visitation scheme whose promise is to provide for introspection of an object's member fields.

In the future, we could add a YAML-related free-function overload that knows how to serialize Role and/or Rgba, but for now visiting them only for the purposes of bindings is a fine use of serialization.
</blockquote></details>

If there's any cause for concern, it would be the mistake I made. We've got a name-value pair clearly declared. So, it would imply that both name and *value* would be meaningfully archived. As it is, we have a "partially workable" `Serialize` method.
___
*[`bindings/pydrake/geometry_py_render.cc` line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7ps1GGAfGyn2waLyw6:-N7qF9Dw0Sgu9bylm6SE:bpqtmf2) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/bindings/pydrake/geometry_py_render.cc#L322)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right, it's a question of how much thought (entropy) we want to put into the formatting here.  I went with "Keep the boilerplate 100% identical for all classes, without trying to read the tea leaves of their future evolution."
</blockquote></details>

I can buy that argument.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[`geometry/drake_visualizer_params.h` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7pqPDDAfsh5gXudjyk:-N7qRM3u0Ej7iKiHBFuj:bwpl5pj) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/geometry/drake_visualizer_params.h#L17)):*
> ... it would imply that both name and value would be meaningfully archived.

And indeed, both the name and value _are_ meaningfully archived.

Sure, if your Archive is YamlLoadFile it won't compile (yet), but that's a question of YAML's support footprint, not any defect of this class of this function.  Serialize is for more than just YAML.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618#-:-N7qY3JV4HqXABzSsBBT:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/test/geometry_render_engine_gl_test.py` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7qXnoaBmimZRT8FnHX:-N7qXnoaBmimZRT8FnHY:blwnleu) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/bindings/pydrake/test/geometry_render_engine_gl_test.py#L3)):*
> ```Python
> import pydrake.geometry as mut
> 
> import copy
> ```

BTW this "looks" unused (but something something python). Am I missing something?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/test/geometry_render_engine_gl_test.py` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17618#-N7qXnoaBmimZRT8FnHX:-N7qYK0bB0_k1jrXRQpw:b-zbicr5) ([raw file](https://github.com/robotlocomotion/drake/blob/9af42d34835e58418aa52c795c8a7dbe8efbff70/bindings/pydrake/test/geometry_render_engine_gl_test.py#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW this "looks" unused (but something something python). Am I missing something?
</blockquote></details>

Merge shrapnel.  Will fix.

**Review by jwnimmer-tri — COMMENTED** [review]
(2) Note that in pydrake at least, the unit tests for the constructor kwargs check a lower bound on which fields are serialized.  (The constructor's available kwargs are exactly the list of bound attributes, which all come from Serialize.)  Since repr and ctor both use the serialized list of fields for what to bind, we only need to carefully check the ctor; for the repr it's sufficient to check that at least one field made it out.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618#-:-N7qZ--b46eyDR8A3Cl3:b-7f5ld5)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17618)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
