### PR TITLE
Remove mention of drake-distro in automotive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7579)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7579#-:-L067YmP_kYNj3Ys2Jvh:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review (tomorrow) per schedule, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7579#-:-L06ExnBmQ-vLlSGEbqh:bnfp4nl)*

**Pull request merged**
