### PR TITLE
Add guard in CMakeList for snopt

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
@drake-jenkins-bot linux-gcc-experimental-minimal please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3800)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-minimal please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-minimal please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please

**Comment by jwnimmer-tri** [comment]
:lgtm: assuming CI agrees.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3800#-:-KU-JSOqSGZccSorg0L8:b-o8g8mj)*

**Comment by jwnimmer-tri** [comment]
So a matlab test failed with `Undefined function or variable 'ismac'` during `testTransform`.  I'm going so attribute that to general flakiness unrelated to this PR.  Everything else passed.  Using override-merge.

**Pull request merged**
