### PR TITLE
perception, sensors: Improve support for 16U depth images

### LINKED ISSUE #10223: DepthImageToPointCloud should support ImageDepth16U
`DepthImageToPointCloud.depth_image_input_port()` can no longer be connected to the `camera_i_depth_image` output ports of `ManipulationStation`.

https://travis-ci.org/RobotLocomotion/6-881-examples/jobs/467722327#L6792

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #10223.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10250)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
In adding the 16U support, there were more challenges than I'd anticipated.

For example, the 16U too-far magic number wasn't promoted anywhere yet (now fixed).  Also, the CameraInfo passed to the system was kept as a dangling reference forever (now fixed).  Also the system didn't defend itself against wrong channel types like color being present in the PointCloud (now fixed).

I still need to work through updating the unit tests cover the additional capabilities and bugs fixed in the rewrite, but I wanted to publish the WIP for others to chime in on any big-picture problems.

\CC @siyuanfeng-tri @SeanCurtis-TRI @kunimatsu-tri @EricCousineau-TRI @pangtao22 @kmuhlrad FYI

**Comment by kunimatsu-tri** [comment]
___
*[perception/depth_image_to_point_cloud.h, line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10250#-LTwbvx0-f16Xgd3IkmG:-LTwo-uh9gSdQ2piV9Vl:bc3jttk) ([raw file](https://github.com/robotlocomotion/drake/blob/a4d30bdf8efc4b591ad51b8a5c5ef82de400708e/perception/depth_image_to_point_cloud.h#L36)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

sounds good to me 
</blockquote></details>

From the space perspective, we probably want to support [organized point cloud](http://pointclouds.org/documentation/tutorials/basic_structures.php) at some point.
Then, we won't be able to squash the space and we'll need some values to express invaid points.
Natural choice for that would be zero and inf since it's already used in depth image.

So, I agree with dropping NaN, but not inf.

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
Sorry for the confusion!  It should be a-ok for platform review.

The "do not merge" just means that _I_ want to be the one who pushes the merge button, not a reviewer.  (So that I can control whether its rebased first, or squash-merged, or etc -- as well as that I'll be online when the post-merge builds run so that I can deal with the fallout, instead of eating a buildcop revert while offline, etc.)

**Comment by kunimatsu-tri** [comment]
___
*[systems/sensors/camera_info.cc, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10250#-LU6ngKA5ZhY6yvIfbHi:-LUB7nKw45gD362O0Quh:b6uae06) ([raw file](https://github.com/robotlocomotion/drake/blob/8b5a2b0e5a30a157558142271870c7c416cd71eb/systems/sensors/camera_info.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done (reverted).
</blockquote></details>

FYI, what @jwnimmer-tri said is correct, i.e. for a 1-pixel camera, the center is (0, 0), not (0.5, 0.5) because pixel locations denoted by integer pixel indices are at its centers, not at top-left corners of pixels.

Just to give another concrete example to be clear, for 2x2 pixel camera, the center is (0.5, 0.5), not (1, 1).

**Pull request merged**
