### PR TITLE
Fix issues noticed during 0.36.0 release process

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16110)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
Two small issues I noticed while doing the release.
+@jwnimmer-tri 
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16110#-:-MoeOEPX4qWOdPjEkO1Q:b-of6dt2)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16110#-:-MoePQjS5TkCu3mowCHh:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

___
*[doc/_pages/release_playbook.md, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16110#-MoeP98D4XYCnvZZ1juJ:-MoeP98D4XYCnvZZ1juK:b-37qpp5) ([raw file](https://github.com/robotlocomotion/drake/blob/263e0a14befc686a3d4842b63e007f03ddc42518/doc/_pages/release_playbook.md#L136)):*
> ```Markdown
> 11. Re-enable CI by reverting the commit you added in step 3.
> 12. Merge the release notes PR
>    1. Squash your commits locally rather than using squash-merge:  This will prevent github creating a commit message for you.
> ```

FYI The author has full control over the commit message during squash, both in Reviewable UI or GitHub UI.  I don't mind providing adding this statement here, but it is not strictly necessary.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16110)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

___
*[doc/_pages/release_playbook.md, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16110#-MoeP98D4XYCnvZZ1juJ:-MoePZEv6Kj9eGh0swXR:bgs7gvi) ([raw file](https://github.com/robotlocomotion/drake/blob/263e0a14befc686a3d4842b63e007f03ddc42518/doc/_pages/release_playbook.md#L136)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The author has full control over the commit message during squash, both in Reviewable UI or GitHub UI.  I don't mind providing adding this statement here, but it is not strictly necessary.
</blockquote></details>

I was surprised by an auto-generated commit message, probably because I was not paying enough attention.  Rewording to focus on the "pay attention" part.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16110)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

___
*[doc/_pages/release_playbook.md, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16110#-MoeP98D4XYCnvZZ1juJ:-MoeQHwtEdBFRywnTOVQ:b-65lsaw) ([raw file](https://github.com/robotlocomotion/drake/blob/263e0a14befc686a3d4842b63e007f03ddc42518/doc/_pages/release_playbook.md#L136)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I was surprised by an auto-generated commit message, probably because I was not paying enough attention.  Rewording to focus on the "pay attention" part.
</blockquote></details>

Ya.  I should probably spend some with with our Reviewable config to remove that footgun.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16110)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

___
*[doc/_pages/release_playbook.md, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16110#-MoeP98D4XYCnvZZ1juJ:-MoeQabD2wgSnVL2e7X2:b-4mfday) ([raw file](https://github.com/robotlocomotion/drake/blob/263e0a14befc686a3d4842b63e007f03ddc42518/doc/_pages/release_playbook.md#L136)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ya.  I should probably spend some with with our Reviewable config to remove that footgun.
</blockquote></details>

I would be happy to pair with you when you do so, to better understand reviewable config magic.

**Pull request merged**
