### PR TITLE
Design documentation for maliput's RoadRulebook.

### PR DESCRIPTION
**Pull request by maddog-tri**
Also, tweak structure/layout of the maliput design doc a little bit,
in preparation for more new sections.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature review, please.  (You will probably want to follow the instructions in the `.org` file to generate a PDF.)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LBaz1TyEOYwtP1jJ7vl:boikpl0)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/doc/maliput-design.org, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LBbJfos2l6sYAvFfYzt:-LBbJfos2l6sYAvFfYzu:b-jw0j3c) ([raw file](https://github.com/robotlocomotion/drake/blob/1292fe3070c0b17c129a54564586ece249d67eae/automotive/maliput/doc/maliput-design.org#L15)):*
> ```Org
> #+TITLE: maliput: Modeling Road Networks for Simulation
> #+AUTHOR: Matt Marjanović (maddog@tri.global)
> #+DATE: April 20, 2018
> ```

BTW, should this be updated?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754)*

**Comment by liangfok** [comment]
*[automotive/maliput/doc/maliput-design.org, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LBcHWf549c2DjzSHK80:-LBcHWf549c2DjzSHK81:b-acvvqb) ([raw file](https://github.com/robotlocomotion/drake/blob/1292fe3070c0b17c129a54564586ece249d67eae/automotive/maliput/doc/maliput-design.org#L6)):*
> ```Org
> #     apt install org-mode
> #    (emacs ships with org-mode, installing it specifically will get you a
> #    more up-to-date version, along with all the important LaTeX dependencies.)
> ```

Should also add:

```
apt install texlive-latex-extra
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754)*

**Comment by jwnimmer-tri** [comment]
@maddog-tri I think you can add `@pkarasev3-tri` as an assignee if you want, it just doesn't autocomplete it.

**Comment by maddog-tri** [comment]
I was getting an actual error message: "pkarasev3-tri is not a valid assignee for this repo".  

(Daniel may have done something to fix this since I told him about it last Thursday.  Either way, Liang has a long head start on this particular PR.)

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LC-NZdM-bxKLe2QT6L4:b6zpjby)*

**Comment by liangfok** [comment]
Sorry for the delay. I will complete the review today.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LC0GvZI9kn6s0kgorPM:bhc5sfj)*

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/doc/maliput-design.org, line 462 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0M1sCCrSe3JWb0moI:-LC0M1sD6NjNXDGTgeDf:b-7i5922) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L462)):*
> ```Org
> right-hand side here.").  =RoadRulebook= abstracts away from both the
> physical artifacts and the symbolic state of such signals, and directly
> represents the intended use of a road network at a semantic level.
> ```

I found it odd how this paragraphs uses the terms "semantic", "symbolic" and "physical" prior to them being defined two paragraphs below.

---

*[automotive/maliput/doc/maliput-design.org, line 470 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0MBrW-oABFOzk-rok:-LC0MBrW-oABFOzk-rol:b3j0qyg) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L470)):*
> ```Org
> 
> Note that =RoadRulebook= is an abstract API.  =maliput= also provides a
> simple concrete implementation of this API, =SimpleRulebook=.
> ```

Can you elaborate on why we anticipate multiple different implementations of RoadRulebook? For example, in what sense is SimpleRulebook "simple"? What features does it lack?

---

*[automotive/maliput/doc/maliput-design.org, line 511 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0NFs4ErVcC8eXL-tv:-LC0NFs4ErVcC8eXL-tw:bk5sw9x) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L511)):*
> ```Org
> state. Dynamic state needs to be managed during the runtime of a
> simulation, and different simulation frameworks have different
> requirements for how they represent and manage dynamic state.  In
> ```

Is the representation different across simulators? Must they always be `RightOfWayRule::DynamicState`?

---

*[automotive/maliput/doc/maliput-design.org, line 558 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0P_8gDyxrwiO5PLW6:-LC0P_8gDyxrwiO5PLW7:bvyg8ta) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L558)):*
> ```Org
> It comprises:
>    * id
>    * zone (longitudinal range on a =LaneId=)
> ```

Should "LaneId" be "Lane"? Or maybe referencing the actual type (`LaneSRange`) would be even better.

---

*[automotive/maliput/doc/maliput-design.org, line 558 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0QETj6vJhDe846l9B:-LC0QETj6vJhDe846l9C:b-k7kqlp) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L558)):*
> ```Org
> It comprises:
>    * id
>    * zone (longitudinal range on a =LaneId=)
> ```

What is the motivation behind making the zone a `LaneSRange` rather than a `LaneSRoute`?

(Consider adding this detail to this document.)
(`LaneSRange` should be defined in an earlier section.)

---

*[automotive/maliput/doc/maliput-design.org, line 568 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0PnBJC0VaxNVHr3c8:-LC0PnBJC0VaxNVHr3c9:b-7uywho) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L568)):*
> ```Org
>      * trucks
>      * ...
>    * /TODO/ time-of-day/calendar condition
> ```

Why is this part of this rule's static definition and not out-sourced to a dynamic state provider?

(Consider adding this detail to this document.)

---

*[automotive/maliput/doc/maliput-design.org, line 580 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0RV551WQ3ZXbdgKl2:-LC0RV551WQ3ZXbdgKl3:bxnc3md) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L580)):*
> ```Org
> =RightOfWayRule= comprises the static state of such rules:
>     * id
>     * controlled zone
> ```

Consider referencing the actual data type (`LaneSRoute`).

(`LaneSRoute` should be defined in an earlier section.)

---

*[automotive/maliput/doc/maliput-design.org, line 587 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0SEU9CcLDG8iNzAho:-LC0SEU9CcLDG8iNzAhp:b-v3esiv) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L587)):*
> ```Org
>     * type
>       * /Proceed/:  Vehicles have right of way, but should avoid stopping
>         within the controlled zone (e.g., pedestrian crosswalk).
> ```

The use of "Vehicles have right of way" and "pedestrian crosswalk" in the same sentence might confuse readers since I doubt there are many crosswalks where vehicles always have right-of-way over pedestrians. Consider replacing "pedestrian crosswalk" with "the intersection between multiple roads".

---

*[automotive/maliput/doc/maliput-design.org, line 610 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0TBsl4-bykVjAD1s0:-LC0TBsl4-bykVjAD1s1:bqy425c) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L610)):*
> ```Org
>       * /ProceedWithCaution/
>       * /Yield/
>       * /StopThenGo/
> ```

Consider alpha sorting this list, unless there is meaning to this order, in which case the meaning should be added to this document.

---

*[automotive/maliput/doc/maliput-design.org, line 615 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0T_D57tFYdcjrKW5x:-LC0T_D57tFYdcjrKW5y:b-lsvge9) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L615)):*
> ```Org
> /Captures allowed direction-of-travel./
>    * id
>    * zone (longitudinal range on a =LaneId=)
> ```

BTW, I think "LaneId" should be "Lane" or "Lane as specified by its ID".

(Same comment regarding LaneChangeRule below.)

---

*[automotive/maliput/doc/maliput-design.org, line 633 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0UBBS5y73X0E9Jlqj:-LC0UBBS5y73X0E9Jlqk:btpiqj2) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L633)):*
> ```Org
>      * to-right
>    * constraint
>      * allowed
> ```

I wonder whether we need "allowed" since this could be the default.

---

*[automotive/maliput/doc/maliput-design.org, line 671 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0UmYwAOcuoqzOF4SV:-LC0UmYwAOcuoqzOF4SW:bhvzw3m) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L671)):*
> ```Org
> 
> ** /(TODO)/ Furniture and Physical Features
> Database of physical features with spatial location and extent.  In many
> ```

This is not a full sentence. Maybe "A database...extent is provided."

---

*[automotive/maliput/doc/maliput-design.org, line 671 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0VeZmAKR20dddI1r1:-LC0VeZmAKR20dddI1r2:b-99zqqg) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L671)):*
> ```Org
> 
> ** /(TODO)/ Furniture and Physical Features
> Database of physical features with spatial location and extent.  In many
> ```

BTW, is this really restricted to physical features? Couldn't this also include symbolic details?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LC0VwV10Esz62jcLGJd:bl4rucz)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC4iIoa6c0UNhJeYaho:-LC4iIoa6c0UNhJeYahp:b-jlk58w) (no related file):*
BTW, I just noticed that generating the PDF resulted in some untracked files in my local clone:

```
$ git status
On branch feature/derive_lane_s_route
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	automotive/maliput/doc/#maliput-design.org#
	automotive/maliput/doc/maliput-design.pdf
	automotive/maliput/doc/maliput-design.tex

nothing added to commit but untracked files present (use "git add" to track)
```

Consider adding these to .gitignore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754)*

**Comment by maddog-tri** [comment]
Comments addressed, PTAL.

---

Review status: 2 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC4iIoa6c0UNhJeYaho:-LCZexL6Eo385g539R7E:b-wwzgp9) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I just noticed that generating the PDF resulted in some untracked files in my local clone:

```
$ git status
On branch feature/derive_lane_s_route
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	automotive/maliput/doc/#maliput-design.org#
	automotive/maliput/doc/maliput-design.pdf
	automotive/maliput/doc/maliput-design.tex

nothing added to commit but untracked files present (use "git add" to track)
```

Consider adding these to .gitignore.
</blockquote></details>

Done.  (The `#maliput-design.org#` is an emacs autosave file, however; I'm not adding that.)

---

*[automotive/maliput/doc/maliput-design.org, line 462 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0M1sCCrSe3JWb0moI:-LCZr6HS6bB8mTnEN5cF:b-knzqd3) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L462)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I found it odd how this paragraphs uses the terms "semantic", "symbolic" and "physical" prior to them being defined two paragraphs below.
</blockquote></details>

Done.  I removed the intervening paragraph which came between this first introductory use and the formal definitions.

---

*[automotive/maliput/doc/maliput-design.org, line 470 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0MBrW-oABFOzk-rok:-LCZrf0ECR49pU20msPp:bfkj1lo) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L470)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Can you elaborate on why we anticipate multiple different implementations of RoadRulebook? For example, in what sense is SimpleRulebook "simple"? What features does it lack?
</blockquote></details>

Done, in that I just took out this extraneous paragraph altogether.

But to answer your question:  `SimpleRulebook` is simple because it is simply a collection of literal rule instances.  One could imagine backends which handle queries by consulting a database, or fusing the results from several other backends, or which allow expressing definitions of general/abstract rules ("This intersection disallows right-turn-on-red.") and synthesize query results appropriately.

---

*[automotive/maliput/doc/maliput-design.org, line 511 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0NFs4ErVcC8eXL-tv:-LCZfoSbBcJq0HeaA9YO:bi7dcpp) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L511)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Is the representation different across simulators? Must they always be `RightOfWayRule::DynamicState`?
</blockquote></details>

Done. I changed "represent" to "store", which is more what I had in mind.

Someone can do whatever they want inside the guts of the simulator, but if they have an agent that understands this API, then they are going to have to emit `RightOfWayRule::DynamicState` at some point.

---

*[automotive/maliput/doc/maliput-design.org, line 558 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0QETj6vJhDe846l9B:-LCZgiAi2tHZ0ikbNBaS:b-ym0d9t) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L558)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

What is the motivation behind making the zone a `LaneSRange` rather than a `LaneSRoute`?

(Consider adding this detail to this document.)
(`LaneSRange` should be defined in an earlier section.)
</blockquote></details>

The motivation is that it is the representation which directly captures the required functionality, which is to yield a function mapping `LaneSRange`'s to speed limits. 

(You could condense multiple `LaneSRange` into a single `LaneSRoute`, but then you would have to maintain the constraint that none of those `LaneSRoute`'s would overlap.)

---

*[automotive/maliput/doc/maliput-design.org, line 558 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0P_8gDyxrwiO5PLW6:-LC_HYR92y3u2-0ze9Z4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L558)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should "LaneId" be "Lane"? Or maybe referencing the actual type (`LaneSRange`) would be even better.
</blockquote></details>

Done.

---

*[automotive/maliput/doc/maliput-design.org, line 568 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0PnBJC0VaxNVHr3c8:-LCZjQpjA9VxlBko6339:b-me9xux) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L568)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Why is this part of this rule's static definition and not out-sourced to a dynamic state provider?

(Consider adding this detail to this document.)
</blockquote></details>

Because it is a fixed relationship that is simple enough that it can be defined and known ahead of time, e.g. "no stop required between 2am and 5am".

I think it is ok for some `TODO`'s to be idea placeholders/reminders, not 100% fleshed-out designs.  (E.g., would any right-of-way rule actually have a TOFD/calendar condition on it???)

---

*[automotive/maliput/doc/maliput-design.org, line 580 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0RV551WQ3ZXbdgKl2:-LC_I6yVCTOlHJhxk6e1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L580)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Consider referencing the actual data type (`LaneSRoute`).

(`LaneSRoute` should be defined in an earlier section.)
</blockquote></details>

Done.

---

*[automotive/maliput/doc/maliput-design.org, line 587 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0SEU9CcLDG8iNzAho:-LCZlemX96r0lG9mAHuv:b-11v06a) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L587)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The use of "Vehicles have right of way" and "pedestrian crosswalk" in the same sentence might confuse readers since I doubt there are many crosswalks where vehicles always have right-of-way over pedestrians. Consider replacing "pedestrian crosswalk" with "the intersection between multiple roads".
</blockquote></details>

Done.  I clarified the language (to be about vehicle-vehicle interactions on intersecting paths).  I really did mean "pedestrian crosswalk" as the example, though.

---

*[automotive/maliput/doc/maliput-design.org, line 610 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0TBsl4-bykVjAD1s0:-LCZm9k3AztYQX3ZbM-M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L610)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Consider alpha sorting this list, unless there is meaning to this order, in which case the meaning should be added to this document.
</blockquote></details>

Done.

---

*[automotive/maliput/doc/maliput-design.org, line 615 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0T_D57tFYdcjrKW5x:-LC_IBVq0En2ta_qMm6z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L615)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I think "LaneId" should be "Lane" or "Lane as specified by its ID".

(Same comment regarding LaneChangeRule below.)
</blockquote></details>

Done.

---

*[automotive/maliput/doc/maliput-design.org, line 633 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0UBBS5y73X0E9Jlqj:-LCZmMdM3dCuIkaHcm1d:bj28iu9) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L633)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I wonder whether we need "allowed" since this could be the default.
</blockquote></details>

It is the default if there is no rule at all --- but it is still good to be able to affirmatively represent all the states.

(E.g. a backend/format in which you can specify a "forbidden" default for long stretches of road along with a "allowed" overrides for specific sections... and the values get merged together appropriately to answer a query for a specific location.)

---

*[automotive/maliput/doc/maliput-design.org, line 671 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8754#-LC0UmYwAOcuoqzOF4SV:-LCZon7C6NTxOWMPyk3-:b99gugi) ([raw file](https://github.com/robotlocomotion/drake/blob/e3fb1d0c2033791df7d675a476bc53b32b841ec5/automotive/maliput/doc/maliput-design.org#L671)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This is not a full sentence. Maybe "A database...extent is provided."
</blockquote></details>

Done.  I rephrased it in the form of a TODO, i.e., an imperative.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LC_JZ8T5t3Y-wd3z4A-:b-idmig1)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LC_P53M0ZeV0Q80GS3G:bnfp4nl)*

**Comment by maddog-tri** [comment]
+@sammy-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8754#-:-LC_UjD76XMWyEpSFURu:bpk00vl)*

**Pull request merged**
