### PR TITLE
Implements example on parameter derivatives

### PR DESCRIPTION
**Pull request by amcastro-tri**
We were having some fun with plant's parameters with @aespielberg today and this example came out.
This little example shows how to take derivatives of the forward dynamics of a pendulum with respect to its mass parameter.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@naveenoid for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823#-:-LCezGPz3PHE547ztYAM:b-jlfufc)*

**Comment by naveenoid** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[examples/pendulum/pendulum_parameters_derivatives.cc, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8823#-LCiUYjk8EMpsbj-sA7a:-LCiUYjlDhVBdJ1HVhhX:b9ukgok) ([raw file](https://github.com/robotlocomotion/drake/blob/9576f0d72bf36970f0c99aa40b1fc3487811b2f6/examples/pendulum/pendulum_parameters_derivatives.cc#L40)):*
> ```cpp
> 
>   // Mass is our independent variable for this example and therefore we set its
>   // vector of derivatives to one.
> ```

BTW: Sounds a bit clunky..why not just say "..therefore we set its derivative to one".

---

*[examples/pendulum/pendulum_parameters_derivatives.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8823#-LCiVCTB3ipKWKHHzTYo:-LCiVCTB3ipKWKHHzTYp:b1m7pw1) ([raw file](https://github.com/robotlocomotion/drake/blob/9576f0d72bf36970f0c99aa40b1fc3487811b2f6/examples/pendulum/pendulum_parameters_derivatives.cc#L61)):*
> ```cpp
>   // Partial of xdot with respect to mass parameter.
>   fmt::print(
>       "Partial of the forward dynamics with respect to mass, i.e. ∂ẋ/∂m:\n");
> ```

BTW: Why not just say "partial derivative of.."? both here and the comment above.

---

*[examples/pendulum/pendulum_parameters_derivatives.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8823#-LCiVZgn44OzwB4eI66N:-LCiVZgn44OzwB4eI66O:b-f7i09r) ([raw file](https://github.com/robotlocomotion/drake/blob/9576f0d72bf36970f0c99aa40b1fc3487811b2f6/examples/pendulum/pendulum_parameters_derivatives.cc#L63)):*
> ```cpp
>       "Partial of the forward dynamics with respect to mass, i.e. ∂ẋ/∂m:\n");
>   // θ̇ is independent of the mass parameter. We verify it by checking the
>   // derivatives size before printing a lie.
> ```

what do you mean "printing a lie"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823)*

**Comment by naveenoid** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823)*

**Comment by amcastro-tri** [comment]
+@soonho-tri for platform please.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/pendulum/pendulum_parameters_derivatives.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8823#-LCiVZgn44OzwB4eI66N:-LCifNoE3k9fzcbvRqTU:b-bgi99s) ([raw file](https://github.com/robotlocomotion/drake/blob/9576f0d72bf36970f0c99aa40b1fc3487811b2f6/examples/pendulum/pendulum_parameters_derivatives.cc#L63)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

what do you mean "printing a lie"?
</blockquote></details>

I'll see how to rephrase but with `AutoDiffXd` you don't get an actual "zero" value but rather a zero sized vector of derivatives. Therefore, before printing a hard-coded zero value, I check that the derivatives vector effectively has zero size.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823#-:-LCifj948qpQQoj7bpbl:b7l9t04)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/pendulum/pendulum_parameters_derivatives.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8823#-LCiVZgn44OzwB4eI66N:-LCkUhlj5lth85_ZG3EU:bzi1zz7) ([raw file](https://github.com/robotlocomotion/drake/blob/9576f0d72bf36970f0c99aa40b1fc3487811b2f6/examples/pendulum/pendulum_parameters_derivatives.cc#L63)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'll see how to rephrase but with `AutoDiffXd` you don't get an actual "zero" value but rather a zero sized vector of derivatives. Therefore, before printing a hard-coded zero value, I check that the derivatives vector effectively has zero size.
</blockquote></details>

So its not rephrased yet?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823#-:-LCmp6Fh62e2Ypwa83br:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm: Im not sure why you didnt address the comments but since its only on the wording of the comments Im ok for now.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823#-:-LCn3tNL3sJjbnrYQ3T6:b-4x6fzc)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8823)*

**Pull request merged**
