### PR TITLE
Find resource helper via the C++ API

### PR DESCRIPTION
**Pull request by stonier**
Right now programs external to drake can find Drake's resources via the `DRAKE_RESOURCE_ROOT` environment variable (works). This also provides a means to add additional search paths via the c++ api, in case the Drake location was discovered differently (e.g. via CMake).

Shambhala will test this on Jenkins via the tests in https://github.com/RobotLocomotion/drake-shambhala/pull/30, but a test case has been added here for completeness.

Also removes the comment about adding more search heuristics for installed copies of drake - with this PR we now have two methods that work fine.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6897)

### CODE REVIEW

**Comment by stonier** [comment]
+@ericcousineau-tri for feature review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-:-KsG7Kd9V0v8KSms6tTe:bvhsv4m)*

**Comment by stonier** [comment]
aha, pydrake

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending some small suggestions and nits. Thanks!

(BTW, I believe there may still be lint errors.)

---

Reviewed 1 of 4 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/bindings/pybind11/pydrake_common.cc, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJWZBHCVUm2vA0WrRF:-KsJWZBIpgfJ-0T5ptMf:b-ununzr) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/bindings/pybind11/pydrake_common.cc#L40)):*
> ```cpp
>         "e.g., drake/examples/pendulum/Pendulum.urdf. Raises an exception "
>         "if the resource was not found.",
>         py::arg("resource_path"), 
> ```

BTW super minor - Trailing space.

---

*[drake/common/find_resource.cc, line 179 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJWu3j6nwYWzVOWfyQ:-KsJWu3j6nwYWzVOWfyR:bixaxir) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L179)):*
> ```cpp
>   // (1) Any programmatically provided search paths. Try this first
>   // if it is non-empty. If it works, it should always win.
>   // TODO(stonier) Should we split on colons, making this a PATH?
> ```

BTW Rather than supplying a string potentially delimited by a `pathsep`, could we rather supply a vector of candidate directories, in order, since this is via the API? (Could the TODO be re-worded to that?)

---

*[drake/common/find_resource.cc, line 180 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJWgtyindgEGl-xE2j:-KsJWgtyindgEGl-xE2k:b-1oejt6) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L180)):*
> ```cpp
>   // if it is non-empty. If it works, it should always win.
>   // TODO(stonier) Should we split on colons, making this a PATH?
>   if ( !candidate_directory.empty() ) {
> ```

Formatting, extra spaces on each side of the `if (...)` conditional.

---

*[drake/common/find_resource.cc, line 208 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJX3aG1p_IXnKUZMni:-KsJX3aG1p_IXnKUZMnj:b-956fpc) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L208)):*
> ```cpp
> std::string FindResourceOrThrow(std::string resource_path,
>                                 string candidate_directory
> ) {
> ```

BTW Formatting, I believe this could up on the previous line, perhaps with `clang-format`?

---

*[drake/common/test/find_resource_test.cc, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJXYjDvDGxQVA4ZoJw:-KsJXYjDvDGxQVA4ZoJx:bb7iv3) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L59)):*
> ```cpp
> 
> GTEST_TEST(FindResourceTest, AlternativeDirectory) {
>   // until std::tmpfile has a cross platform way of extracting filename
> ```

BTW Grammar, capitalization, punctuation.

---

*[drake/common/test/find_resource_test.cc, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJXiWgRmx1F5ITradQ:-KsJXiWhTnciVyItvjlt:b-ayc5h8) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L59)):*
> ```cpp
> 
> GTEST_TEST(FindResourceTest, AlternativeDirectory) {
>   // until std::tmpfile has a cross platform way of extracting filename
> ```

Could we instead leverage `spruce`, specifically `spruce::path(std::tmpnam(nullptr)).split()` (since this normalizes to be cross-platform)? (and maybe rewritten to be more legible?)

---

*[drake/common/test/find_resource_test.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJYidM7pVLCeROR1Qg:-KsJYidNEuWzrvtBbPJH:b-3se96i) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L61)):*
> ```cpp
>   // until std::tmpfile has a cross platform way of extracting filename
>   std::string absolute_path = std::tmpnam(nullptr);
>   std::FILE* fp = std::fopen(absolute_path.c_str(), "w");
> ```

What was the motivation for using `fopen` here? Should this be comparing file contents?

---

*[drake/common/test/find_resource_test.cc, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJYd3E38znq79puVLI:-KsJYd3FgyaoikQmEsN6:b-q5vbt1) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L66)):*
> ```cpp
>   std::string candidate_directory = absolute_path.substr(
>       0, absolute_path.find_last_of("\\/"));
>   auto result = drake::FindResourceOrThrow(
> ```

BTW `result` is unused. Consider removing it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-:-KsJYT8E3gQbcCCLAIUU:bdqm6pw)*

**Comment by stonier** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_common.cc, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJWZBHCVUm2vA0WrRF:-KsOF0JSNFFbShtLsqMo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/bindings/pybind11/pydrake_common.cc#L40)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW super minor - Trailing space.
</blockquote></details>

Done.

---

*[drake/common/find_resource.cc, line 179 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJWu3j6nwYWzVOWfyQ:-KsOFBG4HPNrC0PBH7Wf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L179)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Rather than supplying a string potentially delimited by a `pathsep`, could we rather supply a vector of candidate directories, in order, since this is via the API? (Could the TODO be re-worded to that?)
</blockquote></details>

Done.

---

*[drake/common/find_resource.cc, line 180 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJWgtyindgEGl-xE2j:-KsOFFnQXJ3EvBWOzYcA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L180)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Formatting, extra spaces on each side of the `if (...)` conditional.
</blockquote></details>

Done.

---

*[drake/common/find_resource.cc, line 208 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJX3aG1p_IXnKUZMni:-KsOFH0-iWCOUXkM-VEG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L208)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Formatting, I believe this could up on the previous line, perhaps with `clang-format`?
</blockquote></details>

Done.

---

*[drake/common/test/find_resource_test.cc, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJXiWgRmx1F5ITradQ:-KsOJw5yn84BdHHTG8CF:b-zfzdk2) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L59)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could we instead leverage `spruce`, specifically `spruce::path(std::tmpnam(nullptr)).split()` (since this normalizes to be cross-platform)? (and maybe rewritten to be more legible?)
</blockquote></details>

Actually, that spruce function is not cross platform, it is using the *nix delimiters only. This here is guaranteed to be portable, with the only awkwardness the warning that you should use std::tmpfile. But for that, there is no portable function to retrieve the filename.

That is something that could go into spruce. Along with the delimiter fix. Another PR though.

---

*[drake/common/test/find_resource_test.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJYidM7pVLCeROR1Qg:-KsOIFiAWPAAY1TTIK3m:b7wypcg) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L61)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

What was the motivation for using `fopen` here? Should this be comparing file contents?
</blockquote></details>

Needed to create the file. There is no portable way of doing that without opening it (linux has a mknod).

---

*[drake/common/test/find_resource_test.cc, line 66 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJYd3E38znq79puVLI:-KsOMItzEhsnR-dxXq0I:b-oh5ipi) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L66)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW `result` is unused. Consider removing it?
</blockquote></details>

Good catch, I was supposed to test the result! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897)*

**Comment by stonier** [comment]
*[drake/common/test/find_resource_test.cc, line 59 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJXYjDvDGxQVA4ZoJw:-KsONBfOnnPwlpJsw4y2:b176ahv) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/test/find_resource_test.cc#L59)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Grammar, capitalization, punctuation.
</blockquote></details>

Added a todo note to add such a capability to spruce.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897)*

**Comment by stonier** [comment]
+@sherm1 for platform review please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-:-KsONWgmnMmAR2DWMMsO:bu0bkqk)*

**Comment by jwnimmer-tri** [comment]
This is very similar to the `hint` proposal of #6772, which has already been discussed in other PRs that inspired it.  While I am not averse to a hint, adding an optional second argument to every API ever is not a good design.  I will circle back and post more details when time permits.

**Comment by stonier** [comment]
Ach, looks like Jamie and I misfired on being sync'd. I'll reach out to them as well.

-@sherm1 for platform review.

**Comment by stonier** [comment]
@fbudin69500 is out for a couple of weeks, so I'll push forward on this one. He can rebase and add the extra features he was interested in.

@jwnimmer-tri With respect to the optional arguments, agreed. Second pair of overloaded functions with the extended signature? We could also push for more completeness - directories instead of a single directory, or a map in which additional paths could be registered. I'd be inclined to fill those needs only as they arrive though.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-:-KsPCdH17WnJSejtyHwl:b-oq6pg2)*

**Comment by jwnimmer-tri** [comment]
IIRC I was thinking more like a single function call like `AddResourceSearchPath(string root_directory)` that is persistent for the duration of the process, and then keep the existing signatures unchanged.  But I haven't had a chance yet to page back in all of the context here.

Another option would be teaching the installed version of Drake how to search for its sibling resource automatically, without users having to opt-in to it.  (Even if we do this, having an option like `AddResourceSearchPath` is still reasonable.)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-:-KsPEctSl8iSQRj9MKOc:b-h8ftv6)*

**Comment by stonier** [comment]
Aye, the `AddResourceSearchPath(string root_directory)` was what I was alluding to in my comment. We do now have a `drake_RESOURCE_ROOT` going into the `drake-config.cmake` now, but teaching it how to find itself is not going to be quite hacky. With a deb we can enable that kind of functionality easily by dropping in a file in `/etc/profile.d` that sets the `DRAKE_RESOURCE_ROOT` appropriately. I imagine this can be achieved for other packaging types as well.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-:-KsPKZg5Qlx21l-e3UvZ:bw177wm)*

**Comment by jwnimmer-tri** [comment]
For "teaching the installed version of Drake how to search for its sibling resource automatically", I was thinking more like https://stackoverflow.com/questions/5103443/how-to-check-what-shared-libraries-are-loaded-at-run-time-for-a-given-process -- look at a `/proc/pid/maps` or `dlopen` to see where `libdrake.so` is coming from, and then infer `$PREFIX` from there.  Whether that's hacky or not, I believe it should be robust, and not require any user or packaging-system intervention.

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/find_resource.cc, line 208 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6897#-KsJX3aG1p_IXnKUZMni:-KsnPwjnsjsfwfFT5PDv:b-9jmqg4) ([raw file](https://github.com/robotlocomotion/drake/blob/9fe9721939984c99c1cf0fabe1c73002cb5810c8/drake/common/find_resource.cc#L208)):*
<details><summary><i>Previously, stonier (Daniel Stonier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW Sorry, I meant that the parenthesis should be up on the previous line: `candidate_directory) {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6897)*

**Comment by stonier** [comment]
Closing, this is getting incorporated into #6772

**Comment by fbudin69500** [comment]
@jwnimmer-tri Looking at the implementation of ``FindResource()``, it looks like these are functions (I was expecting a ``class``). So to have a persistent ``AddResourceSearchPath``, I could use a Singleton pattern, with all the complications that can come from it, or a static variable, with the limitations of this implementation. Any thought?

**Pull request closed without merging**
