### PR TITLE
Upgrade meshcat and meshcat_python to the latest commit

### LINKED ISSUE #16879: Upgrade externals to latest - April 2022
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #16675

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves #16879

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16925)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
I confirmed that `drake/geometry:meshcat_manual_test` ran as expected on my local (Linux Focal) system

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16925#-:-N-O4Ys8AC3UCIlEZZAz:blwunbh)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by BetsyMcPhail — COMMENTED** [review]
+@ggould-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16925#-:-N-OaAvGABw3rvhak2tW:bjfm66p)* status: LGTM missing from assignee ggould-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

FYI the apparent upstream CI failure on this `meshcat-python` sha is a code coverage alert and is not a regression.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16925#-:-N-OdJ9jCEoJEvZLGskF:b-y3fdnd)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
After a rebase, we have a test failure:

```
[3:33:18 PM]  ==================== Test output for //bindings/pydrake/visualization:py/meldis_test:
[3:33:18 PM]  
[3:33:18 PM]  Running tests...
[3:33:18 PM]  ----------------------------------------------------------------------
[3:33:18 PM]  INFO:drake:Meshcat listening for connections at http://localhost:7001
[3:33:18 PM]  .INFO:drake:Meldis is listening for LCM messages at memq://
[3:33:18 PM]  INFO:drake:Meshcat listening for connections at http://localhost:7000
[3:33:18 PM]  .
[3:33:18 PM]  ----------------------------------------------------------------------
[3:33:18 PM]  Ran 2 tests in 0.192s
[3:33:18 PM]  
[3:33:18 PM]  OK
[3:33:18 PM]  
[3:33:18 PM]  Generating XML reports...
[3:33:18 PM]  [*** LOG ERROR #0001 ***] [2022-04-11 19:33:17] [console] {Unknown exception in logger}
[3:33:18 PM]  FATAL: exception not rethrown
```

Any ideas @jwnimmer-tri ?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16925#-:-N-PEE3t571BtSz9Wa6L:bo7scvv)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform), base commit is latest master (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
That almost looks like a race condition in the logging infrastructure.  It failed in CI in the default configuration; I'll see if I can reproduce it locally.

**Comment by jwnimmer-tri** [comment]
`bazel test //bindings/pydrake/visualization:py/meldis_test --runs_per_test=100` passes for me on Focal with this PR.

@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
FWIW it passed previously on CI. Merging before I need to do another rebase!

**Pull request merged**
