### PR TITLE
Half explicit DAE1 solver.

### PR DESCRIPTION
**Pull request by edrumwri**
This PR adds a barebones differential algebraic equation initial value problem solver. Error control is not implemented. First order. Stabilizes constraints automatically.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5221)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review (if you are willing- this PR is still 50% larger than our "limit") and +@sherm1 for platform review please (I need your feedback in particular as few have the technical background to review this and because this PR will form much of the technical basis for the upcoming implicit euler integrator- this PR is critical to that effort).

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-:-KdOBUR45QSeOGNEcLZo:b-5li2jv)*

**Comment by amcastro-tri** [comment]
Reviewed 3 of 8 files at r1.
Review status: 3 of 8 files reviewed at latest revision, 17 unresolved discussions.

---

*[drake/examples/bead_on_a_wire/bead_on_a_wire-inl.h, line 170 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcH4ub7N3JNynhHwxx:-KdcH4ub7N3JNynhHwxy:bxxs23v) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/examples/bead_on_a_wire/bead_on_a_wire-inl.h#L170)):*
> ```objc
> template <class T>
> Eigen::VectorXd BeadOnAWire<T>::DoCalcVelocityChangeFromConstraintImpulses(
>     const systems::Context<T>& context, const Eigen::MatrixXd& J,
> ```

per f2f I believe you'll change this to something like `DoCalcGeneralizedForce(const context, const lambda);`?, i.e. to an operator form.

---

*[drake/systems/analysis/half_explicit_DAE1_solver.cc, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcHdfgvMaQtTMdTL0N:-KdcHdfhUcZb7vvhK7vf:b6ua0kn) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.cc#L13)):*
> ```cpp
> // template class
> // drake::systems::HalfExplicitDAE1Solver<
> // Eigen::AutoDiffScalar<drake::Vector1d>>;
> ```

Could this be solved in this PR? why is it that it does not compile?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcLDiLExKVIPyAsPuu:-KdcLDiMvLr5gTfR1Otg:bb6o683) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L81)):*
> ```objc
>   HalfExplicitDAE1Solver(const HalfExplicitDAE1Solver<T>& other) = delete;
>   HalfExplicitDAE1Solver& operator=(const HalfExplicitDAE1Solver<T>& other) =
>       delete;
> ```

Use `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcRyIU6dbiggZh16O7:-KdcRyIVPBS66dmjkBtW:b-dn1ptg) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L83)):*
> ```objc
>       delete;
> 
>   /**
> ```

Use `///` for consistentcy

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcLK-pUytHfBqEz7b5:-KdcLK-pUytHfBqEz7b6:baz754j) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L95)):*
> ```objc
>    */
>   HalfExplicitDAE1Solver(const System<T>& system, const T& max_step_size,
>                           Context<T>* context = nullptr)
> ```

odd indentation

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcLM_NTrvObbtRzG-S:-KdcLM_NTrvObbtRzG-T:brl2ng4) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L103)):*
> ```objc
>   /**
>    * Solver does not currently support error estimation.
>    */
> ```

use `///` for consistency

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 104 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcLQhB87zY0QbOwsD_:-KdcLQhB87zY0QbOwsDa:bivhbi2) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L104)):*
> ```objc
>    * Solver does not currently support error estimation.
>    */
>   bool supports_error_estimation() const override { return false; }
> ```

`final`?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcLU27oWNwbjg8ZiKD:-KdcLU27oWNwbjg8ZiKE:bivhbi2) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L107)):*
> ```objc
> 
>   /// Solver does not provide an error estimate.
>   int get_error_estimate_order() const override { return 0; }
> ```

`final`?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcS6O160-YOYwpnI3P:-KdcS6O160-YOYwpnI3Q:bkg1oby) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L141)):*
> ```objc
>                                const Eigen::MatrixXd& J,
>                                double dt) const;
>   void DoStepOnceFixedSize(const T& dt) override;
> ```

Place documentation in header (not -inl.h). Use `final` unless you foresee this class to be extended.

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcR0vcYgOY1DvaGzuX:-KdcR0vcYgOY1DvaGzuY:b-hdyhn4) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L2)):*
> ```cpp
> #include <cmath>
> #include "drake/common/drake_path.h"
> ```

not used?

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcRVfupfW2wq_WcO-Q:-KdcRVfupfW2wq_WcO-R:bj9p8fq) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L7)):*
> ```cpp
> #include "drake/examples/bead_on_a_wire/bead_on_a_wire-inl.h"
> #include "drake/systems/analysis/half_explicit_DAE1_solver.h"
> #include "drake/systems/analysis/test/my_spring_mass_system.h"
> ```

"drake/systems/plants/spring_mass_system/spring_mass_system.h"

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcKRxU7R3cQ9_Cdzvn:-KdcKRxU7R3cQ9_Cdzvo:b-bdhviz) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L27)):*
> ```cpp
> 
>   // Create the spring-mass system.
>   SpringMassSystem<double> spring_mass(spring_k, mass, 0.);
> ```

`spring_mass(spring_k, mass, false /* not forced */);`

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcOIeHJZUSoTRs9DUa:-KdcOIeHJZUSoTRs9DUb:bjsgg18) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L69)):*
> ```cpp
>   // Check the solution.
>   EXPECT_NEAR(c1 * std::cos(omega * t) + c2 * std::sin(omega * t), x_final,
>               5e-3);
> ```

So you perform one million time steps and the best accuracy you get is `5e-3`?

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 73 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcOWNCQLLTOyQB6MOZ:-KdcOWNCQLLTOyQB6MO_:bksxb0l) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L73)):*
> ```cpp
>   // Verify that integrator statistics are valid
>   EXPECT_GE(integrator.get_previous_integration_step_size(), 0.0);
>   EXPECT_GE(integrator.get_largest_step_size_taken(), 0.0);
> ```

This are very loose. I think you know the exact values here right?

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 101 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcP-dlK8UIHxgNaeJ8:-KdcP-dlK8UIHxgNaeJ9:b-22sae7) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L101)):*
> ```cpp
>   std::unique_ptr<BasicVector<double>> input_min =
>       std::make_unique<BasicVector<double>>(1);
>   input_abs->SetAtIndex(0, 0.0);
> ```

can you add comments right next to these indicating what they are?

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 122 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcQBNjVchNDVX9oTQ0:-KdcQBNjVchNDVX9oTQ1:b-q5qlxf) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L122)):*
> ```cpp
>   // Integrate for a single step.
>   integrator_abs.StepOnceAtMost(inf, inf, dt);
>   integrator_min.StepOnceAtMost(inf, inf, dt);
> ```

What about integrating for a longer time as you did with the spring-mass system?

---

*[drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc, line 127 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcQXAO8yoVKWOXHPvi:-KdcQXAPA3lS0ZaviuNh:b-gkwohx) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/test/half_explicit_DAE1_solver_test.cc#L127)):*
> ```cpp
>   // we should expect last index of absolute coordinates and only index of
>   // minimal coordinate to match.
>   const double tol = 25*integrator_abs.get_constraint_error_tolerance();
> ```

Here you could do `bw_min->helix_function(s)` and also compare the other two coordinates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5221)*

**Comment by amcastro-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, 29 unresolved discussions.

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcTRVPHmDXUenSzO6i:-KdcTRVPHmDXUenSzO6j:bmjtoik) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L24)):*
> ```objc
> /// forces `λ`, using the first order relationship:
> /// <pre>
> /// x(t+Δt) = x(t) + Δt⋅d(x(t), λ)
> ```

Please state on what time `lambda` is evaluated 

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcV-9ca-3Q-RoMIyFA:-KdcV-9ca-3Q-RoMIyFB:b-aedpiw) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L26)):*
> ```objc
> /// x(t+Δt) = x(t) + Δt⋅d(x(t), λ)
> /// </pre>
> /// to solve the following nonlinear system of equations for λ:
> ```

"satisfying" instead of "to solve"?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcVwtGSimFBt4BHXia:-KdcVwtGSimFBt4BHXib:b-ujrila) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L28)):*
> ```objc
> /// to solve the following nonlinear system of equations for λ:
> /// <pre>
> /// g(x(t)+ Δt⋅d(x(t), λ) = 0
> ```

missing closing parenthesis.

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcVaw8zRmo1XFT88-E:-KdcVaw8zRmo1XFT88-F:brni93j) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L30)):*
> ```objc
> /// g(x(t)+ Δt⋅d(x(t), λ) = 0
> /// </pre>
> /// After the value of `λ` has been obtained *implicitly*, `x(t+Δt)` is computed
> ```

ah, ok, so maybe we could also write λ(t+Δt)?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcVjK8uwf_gRBcOY53:-KdcVjK8uwf_gRBcOY54:b-6k3csa) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L30)):*
> ```objc
> /// g(x(t)+ Δt⋅d(x(t), λ) = 0
> /// </pre>
> /// After the value of `λ` has been obtained *implicitly*, `x(t+Δt)` is computed
> ```

BTW, do you need quotes around lambda?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcWO8KZDEd8ZDE7Ox5:-KdcWO8KZDEd8ZDE7Ox6:b-b3nkr4) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L33)):*
> ```objc
> /// *explicitly* using the second to last equation above.
> 
> /// Let us now consider the state variables as representing a mechanical system
> ```

per f2f, do we need to limit ourselves to only mechanical systems?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcWhfKKRPH7L5DDewk:-KdcWhfLspFsiExt5pcm:bfix5bc) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L42)):*
> ```objc
> /// J = ∂g/∂q
> /// </pre>
> /// The time derivative of the constraint equations `dg/dt = Jv` yields-
> ```

Above you define `J` as the derivative with respect to the quasi-coordinates but here it appears multiplied by `v`. We could have `Jq = ∂g/∂ꝗ` and `Jv = Jq * N(q)`

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcXWqUdxxfpNY_j8xn:-KdcXWqUdxxfpNY_j8xo:bmuk6fi) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L47)):*
> ```objc
> /// above as:
> /// <pre>
> /// v(t+Δt) = v(t) + Δt⋅e() + M⁻¹Jᵀλ
> ```

did you mean here to only have `e()`? also, not clear to me what `e()` is.

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcXgRba5gAS1FEyAdB:-KdcXgRba5gAS1FEyAdC:b8laep6) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L48)):*
> ```objc
> /// <pre>
> /// v(t+Δt) = v(t) + Δt⋅e() + M⁻¹Jᵀλ
> /// q(t+Δt) = q(t) + Δt⋅Nv(t+Δt)
> ```

Δt⋅N(q)⋅v(t+Δt), otherwise it looks like Nv is a new variable.

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcYPMIyP5nlgePGtin:-KdcYPMIyP5nlgePGtio:bdeo711) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L57)):*
> ```objc
> /// algorithm for solving nonlinear systems of equations)
> /// requires computing the Jacobian matrix `∂g/∂λ`. Focusing
> /// only on configuration-dependent constraints, i.e., assuming that `g(.)` is a
> ```

also known as holonomic constraints

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcYx5VMCE2Ve3egFpf:-KdcYx5VMCE2Ve3egFpg:b8lwk9k) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L67)):*
> ```objc
> /// </pre>
> /// but `∂g(q(t+Δt))/∂λ` is not. This exercise shows that the necessary
> /// Jacobian matrix is not neatly provided as the output of some typical
> ```

could you clarify here you mean the Newton-Raphson Jacobian ∂g/∂q to disambiguate with from  `J`?

---

*[drake/systems/analysis/half_explicit_DAE1_solver.h, line 72 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5221#-KdcZ838j4d7dNJUgGWQ:-KdcZ839TSXa8HcGdfzL:b-gxat7y) ([raw file](https://github.com/robotlocomotion/drake/blob/73f410a10d7956c233e68c9346c9043462ec2739/drake/systems/analysis/half_explicit_DAE1_solver.h#L72)):*
> ```objc
> ///
> /// This class uses Drake's `-inl.h` pattern.  When seeing linker errors from
> /// this class, please refer to http://drake.mit.edu/cxx_inl.html.
> ```

missing @tparam doc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5221)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@edrumwri This PR seems to be stale?  Consider closing it until it's going to be worked again.

**Comment by edrumwri** [comment]
Closing until we have bandwidth to pursue such directions.

**Pull request closed without merging**
