### PR TITLE
[sensors] Factor out and improve image load/save test infrastructure

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20447.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20557)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.
+@SeanCurtis-TRI for platform review, please.

**Review by zachfang — COMMENTED** [review]
:lgtm: feature

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20557#-:-NjeNx2l2blS6l3mpr4W:bxmhyuf)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule (tomorrow), please.  (It turns out that -@SeanCurtis-TRI is not available today.)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20557#-:-NjmoYdVAwxh-XUPDPiJ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),zachfang

**Pull request merged**
