### PR TITLE
Remove unused distance_to_point_with_gradient

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This includes the deprecation of the struct `SignedDistanceToPointWithGradient`. It's worth noting that the internal code is only exercised in its own unit test and that the deprecated struct is not part of any public API (either produced or consumed).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
+@soonho-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW0ZKWeBoeNpXr13yUj:bnwhygc)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm: for code change.

I'm slightly more inclined to deprecate `SignedDistanceToPointWithGradient` first instead of removing it. Can you find another platform reviewer who can support this removal?

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW0eWzAC8snckAzLljZ:bbtxahn)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri would you be willing to weigh in on the viability of this breaking change?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW0pqma-Oil3EpSdGU1:b-9548m4)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
The way I think about a deprecation decision is to balance the cost of doing the deprecation (how much more work is deprecating an item, compared to a straight removal) against the potential benefit to users (how likely is the removal to be noticed in the first place, or difficult to work around in the second place).

Your overview in the top post makes the case that its unlikely that users would notice the removal.  I'll accept that at face value.  I'll also go so far as to say that even if they did notice, copying a few lines of header-only struct definition into their own code is not a huge burden compared to, e.g., needing to copy over a computational class that has unit tests.

On the flip side, though, is the cost -- this seems like one of the most trivial instances to implement a deprecation: it seems like a `DRAKE_DEPRECATED("2021-07-01", "This struct is no longer used, and so is being removed.");` one-liner along with one new include statement.

Given that each side of the cost-benefit balance is minor, we have a tie -- and in my mind, we should resolve ties on the side of generosity, by deprecating the struct.

**Review by soonho-tri — COMMENTED** [review]
:+1: Can you also update the PR title? (remove `(breaking change)` part)

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW4dCd0DIYHBudIr79z:bfo8fj8)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Done

@hongkai-dai you'd orginally written this code two years ago, although it never got plugged in to anything. This is your big chance to veto this removal.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW4f6xZ1r86--0c9Y6O:b-9nuj38)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW4jOJS89VQGq87kuib:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm going to stall merging just long enough to see if the original author (@hongkai-dai) has any insight that would contradict my conclusions.

+(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW4mgh8DDOW57_2Xuol:b-5ibtg6)* status: labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Comment by hongkai-dai** [comment]
I opt for removing it if the code was never used elsewhere. As Damrong mentioned the other day, code is a liability, not an asset.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks
-status: do not merge

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14793#-:-MW5K9F500gHE70LhSco:b58gz27)* status: labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Pull request merged**
