### PR TITLE
Fix a trivial sign error in the joint limit logic

### PR DESCRIPTION
**Pull request by ggould-tri**
...and add a unit test for basic sanity.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3786)

### CODE REVIEW

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Whoops! Funny after all that careful testing of the force itself. Sorry I didn't notice that. :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 453 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-KTuWJpK6MBW412thbuf:-KTuWJpK6MBW412thbug:b-wzcasq) ([raw file](https://github.com/robotlocomotion/drake/blob/36ff92e21e7bfa231bcd5da8554a649dd2d73493/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L453)):*
> ```cpp
>   auto context = rigid_body_sys.CreateDefaultContext();
>   rigid_body_sys.SetZeroConfiguration(context.get());
>     context->get_mutable_continuous_state()
> ```

indent-2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-:-KTuXQ0_xr_q22OirVtm:bk8huul)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 474 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-KTuYS8e3R-6NbtE3t_I:-KTuYS8e3R-6NbtE3t_J:bmsi3sz) ([raw file](https://github.com/robotlocomotion/drake/blob/36ff92e21e7bfa231bcd5da8554a649dd2d73493/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L474)):*
> ```cpp
> GTEST_TEST(rigid_body_plant_test, TestJointLimitForces) {
>   // Test that joint limit forces are applied correctly in the rigid body
>   // tree.  This tests for a sign error at rigid_body_plant.cc:240.
> ```

BTW, this comment seems brittle against changes to rigid_body_plant.cc`. Maybe reference a commit SHA instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786)*

**Comment by ggould-tri** [comment]
+@sherm1 and @liangfok who reviewed #3746 that probably introduced this error.

(I say "probably" because the behaviour was also untested and wrong before #3746, I just suspect it was not _this_ wrong before I stuck my foot in it)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-:-KTuS8TiZzGHMYEXd_Kj:b-4lo3qn)*

**Comment by ggould-tri** [comment]
Thanks for reviewing this before I even got around to assigning it :)

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc, line 453 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-KTuWJpK6MBW412thbuf:-KTu_KLcQdqAmaKf6cRI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/36ff92e21e7bfa231bcd5da8554a649dd2d73493/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc#L453)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> indent-2
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-:-KTu_N2H-_joBN8gndBi:b-a447ts)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786)*

**Comment by ggould-tri** [comment]
@drake-jenkins-bot retest this please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-:-KTujgj6QUPQiiRPTyP0:bvi7gqa)*

**Comment by liangfok** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/plants/rigid_body_plant/test/limited_prismatic.sdf, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-KTv_oaXBGaA7ioXk5ZM:-KTv_oaXBGaA7ioXk5ZN:b7mbt1x) ([raw file](https://github.com/robotlocomotion/drake/blob/5dc0b7ba75ac38e4f11cc9da99905bb0a143504e/drake/systems/plants/rigid_body_plant/test/limited_prismatic.sdf#L3)):*
> ```
> <?xml version='1.0'?>
> <sdf version='1.6'>
>   <model name='Schunk_Gripper'>
> ```

Let's rename this since it's not actually the Schunk gripper. How about "limited_prismatic_test_model"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786)*

**Comment by ggould-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_plant/test/limited_prismatic.sdf, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-KTv_oaXBGaA7ioXk5ZM:-KTyDzUTM5KKx4fvVIH1:b-hn7wb8) ([raw file](https://github.com/robotlocomotion/drake/blob/5dc0b7ba75ac38e4f11cc9da99905bb0a143504e/drake/systems/plants/rigid_body_plant/test/limited_prismatic.sdf#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Let's rename this since it's not actually the Schunk gripper. How about "limited_prismatic_test_model"?
</details>
Yep, that name is left over (I discovered this test case by progressively removing things from the Schunk and hoping that solved the problem).  Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3786#-:-KTyEzBAKN-p1te7onUi:bnfp4nl)*

**Pull request merged**
