### PR TITLE
Fixing ASan, UBSan, LSan Suppression Files With gcc-5.4

### PR DESCRIPTION
**Pull request by m-chaturvedi**
gcc-5 can't take empty suppressions' files.
To reproduce:
https://gist.github.com/m-chaturvedi/65ce877176035071f7b7bca1f44a583b

Seems like GCC checks for file size of the suppressions file:
https://gist.github.com/m-chaturvedi/77442d5eb70285a0176f9d8da404ccdb#file-sanitizer_suppressions-cc-L87

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6154)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6154)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6154#-:-KklJFvkwDdGnSYnKoBA:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6154#-:-KklKdJdDBvLdaod3ltQ:bnfp4nl)*

**Pull request merged**
