### PR TITLE
SignalLogger: Remove context-per-thread hazard

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #10228

Move the internal SignalLog member to become a cache entry. Abandon the data
access methods on SignalLogger, and instead provide ergonomic lookup methods to
get the SignalLog itself.

Make SignalLog copyable and movable for compatibility with the cache.

Provide complete python bindings for SignalLogger and SignalLog.

Update numerous tests and examples.

This patch is breaking; it removes existing (if problematic) APIs without
deprecation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+(release notes: breaking change)

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for feature review, as existing code author and issue co-assignee.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MezZgidDExI-o8q2c-j:bn5ynfo)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezYeMb7rlIYwL0wSof:-MezYeMb7rlIYwL0wSog:b-2wqnyl) (no related file):*
potential issue: representing log as non-updated cache entry vs. representing log as State(tm). I've had conflicting advice here.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezYpOj0LEV1wo_yXCx:-MezYpOj0LEV1wo_yXCy:b268vm5) (no related file):*
potential issue: porting one of the Anzu client programs introduced numeric tolerance exceeded errors I can't yet explain. /cc @hongkai-dai I will provide a patch to discuss in other channels.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezZOd9-TTWmWJgsXvC:-MezZOd9-TTWmWJgsXvD:b-fhxh0p) (no related file):*
potential issue: I'm not entirely convinced the const/mutable model of this patch is either coherent or necessary. Advice welcome.

---

**Comment by jwnimmer-tri** [comment]
In my estimation, the existing `data()` API is widely used and deserves a deprecation period.  This is borne out in the extent of the disturbances here (and in Anzu).

It doesn't seem to me like implementing the deprecation affordances would be very difficult.

**Review by rpoyner-tri — COMMENTED** [review]
What's your deprecation design? Retain unsafe data? Fork on class name? Something else?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-Mez_UCoCe5_DipgslvW:b-phh2dq)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
I think a constructor `bool data_in_context = false` should suffice?  The member functions that don't make sense with a given `data_in_context` value would throw.

**Review by rpoyner-tri — COMMENTED** [review]
Mmm, feature-flag constructor. I guess it's ok since it will disappear eventually.

I'll roll a patch with that and see where it gets.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MezaCB8Bh4eOI9ZGXYs:b-mt295x)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
-(release notes: breaking change) no longer breaking in r2.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-Mf4P_szDmm3wooPUlYv:b-vuilwe)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezYpOj0LEV1wo_yXCx:-Mf4PfGV5L4WsQeejSjs:b-keuy0j) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

potential issue: porting one of the Anzu client programs introduced numeric tolerance exceeded errors I can't yet explain. /cc @hongkai-dai I will provide a patch to discuss in other channels.
</blockquote></details>

Deferred in r2 via deprecation.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-Mf4PpsO0DsdcDscT7D9:-Mf4PpsO0DsdcDscT7DA:buixv7h) (no related file):*
A wart of r2 is the spamming of the (perhaps unnecessary) magic constant 1000 to every non-deprecated usage. Makes me wonder if I should just replace the log allocation scheme first in a breaking change, then wait a release and fix the thread hazard afterward.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-Mf4PpsO0DsdcDscT7D9:-Mf4QwHV1E4e1_XYYnV6:b68j38o) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

A wart of r2 is the spamming of the (perhaps unnecessary) magic constant 1000 to every non-deprecated usage. Makes me wonder if I should just replace the log allocation scheme first in a breaking change, then wait a release and fix the thread hazard afterward.
</blockquote></details>

It seems like overloading the constructor with a `(int size, enum mode)` would solve that?  I don't think that would be ambiguous with `(int size, int batch)`?

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-Mf4PpsO0DsdcDscT7D9:-Mf4SFip4ojLCgxzho3l:b5ewv8a) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like overloading the constructor with a `(int size, enum mode)` would solve that?  I don't think that would be ambiguous with `(int size, int batch)`?
</blockquote></details>

Let me see if I understand.

1. keep the existing constructor and mark it deprecated.
2. add a new constructor for the new behavior. Maybe it doesn't even need an enum in the API any more; perhaps SignalLog(ArbitraryTagType, int, int)?
2. also overload systems::LogOutput() in a similar way.

---

**Review by sherm1 — COMMENTED** [review]
Checkpoint.

> Reviewed 2 of 21 files at r1, 9 of 18 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MfAMrLjDLWlEN9J38Sf:by96gdd)* status: 8 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[systems/primitives/signal_logger.h, line 19 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfA77lg6huni8VJrzYR:-MfA77lg6huni8VJrzYS:b7lh3lp) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L19)):*
> ```objc
> namespace systems {
> 
> /// Allow coexistence of the deprecated usafe usage, and replacement safe
> ```

nit: usafe -> unsafe
___
*[systems/primitives/signal_logger.h, line 33 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfADGnl9g7lyM23iGqS:-MfADGnl9g7lyM23iGqT:b-oezxsp) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L33)):*
> ```objc
> /// is then retrievable (e.g. after a simulation).  The stored log (a
> /// SignalLog) holds a large, mutable Eigen matrix for data storage, where each
> /// column corresponds to a data point. The SignalLogger a data point and the
> ```

minor: _saves_ a data point
___
*[systems/primitives/signal_logger.h, line 94 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAEQgYALh4BUsdMJOW:-MfAEQgYALh4BUsdMJOX:bjaf0bp) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L94)):*
> ```objc
>   /// @param storage_mode Which storage mode to use.
>   /// @see LogOutput() helper function for a convenient way to add %logging.
>   SignalLogger(int input_size, LogStorageMode storage_mode);
> ```

Can you explain the intent of this new constructor? After deprecation of the mutables I assume we will only have the log-per-context mode in which case we'll have to deprecate this signature.
___
*[systems/primitives/signal_logger.h, line 151 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAMP4M4MNVcZBqfQvP:-MfAMP4N5groJwVJr2-b:buvpdzw) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L151)):*
> ```objc
>   /// system and its matching context.
>   const SignalLog<T>& GetLog(const System<T>& outer_system,
>                              const Context<T>& outer_context) const;
> ```

minor: the terms outer_system and outer_context are new to me. Consider using diagram and diagram_context instead? Then you can say "containing diagram" which is a common Drake idiom. (and below)
___
*[systems/primitives/signal_logger.h, line 240 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAI9RZ1MTIob-XOAx5:-MfAI9RZ1MTIob-XOAx6:b-wco608) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L240)):*
> ```objc
>     const OutputPort<T>& src,
>     DiagramBuilder<T>* builder,
>     LogStorageMode storage_mode) {
> ```

Same question here -- this will have to be deprecated later. Is it worthwhile to add it now?
___
*[systems/primitives/signal_logger.cc, line 26 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAJ0gk2KnDofjulT9p:-MfAJ0gk2KnDofjulT9q:b-df89sg) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L26)):*
> ```cpp
>                   // TODO(jwnimmer-tri) Improve ValueProducer constructor sugar.
>                   internal::AbstractValueCloner(
>                       SignalLog<T>(input_size, batch_allocation_size)),
> ```

BTW I _think_ this can already work with an explicit call to AbstractValueCloner()?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)* status: 9 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezYeMb7rlIYwL0wSof:-MfAPAvY6CYtsJjYj2iN:b-nmur9g) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

potential issue: representing log as non-updated cache entry vs. representing log as State(tm). I've had conflicting advice here.
</blockquote></details>

The log of past values is unambiguously state information, since it can't be re-created from the other state variables (legit cache values can always be recalculated). However, that distinction only matters if the additional state information can be used to affect the evolution of a simulation. If the intent of the log is that it is only examined after the fact, and never in a manner that could affect the trajectory, then putting it in the cache is harmless. But we should document that the contents of a SignalLog should never be used to modify system behavior.

The reason we have to use a mutable (cache) value here is just that we trigger on Publish events rather than UnrestrictedUpdate events. In the latter case the WriteLog() method could be given a non-const Context which would allow an abstract state variable update. All things being equal, it would be better to put the log in an AbstractStateVariable. But I can see the appeal of logging on Publish() calls, and I believe there are some analyses that are made more difficult if there are extra state variables. So on balance I think using the cache and making people promise not to treat it like state is probably the best approach.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezZOd9-TTWmWJgsXvC:-MfASGva4GMDvlA0iD0l:bfmdt33) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

potential issue: I'm not entirely convinced the const/mutable model of this patch is either coherent or necessary. Advice welcome.
</blockquote></details>

Does my comment above address this?

---
___
*[systems/primitives/signal_logger.cc, line 50 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAO8kM2x2P63tC7eVR:-MfAO8kM2x2P63tC7eVS:b-ik59m0) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L50)):*
> ```cpp
> template <typename U>
> SignalLogger<T>::SignalLogger(const SignalLogger<U>& other)
>     : SignalLogger<T>(other.get_input_port().size()) {
> ```

I think this scalar-converting copy constructor needs updating? It isn't copying `storage_mode_` at least. Possibly needs an updated unit test that would have caught the problem.

**Review by sherm1 — COMMENTED** [review]
I'll stop here for now so we can discuss a change to the API for GetLog() from the diagram context (see comments below).

> Reviewed 1 of 21 files at r1, 4 of 18 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MfAWN2O3c42ZcCHcXKB:b-dk1ag1)* status: 10 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[systems/primitives/signal_logger.cc, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfATvLC4SZQvnTAe71k:-MfATvLC4SZQvnTAe71l:byixuaf) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L143)):*
> ```cpp
>   DRAKE_THROW_UNLESS(storage_mode_ == kLogPerContext);
>   return GetMutableLog(
>       outer_system.GetSubsystemContext(*this, outer_context));
> ```

You don't need the diagram (`outer_system`) here to extract the local subcontext. This would work here:
```c++
GetMutableLog(this->GetMyContextFromRoot(outer_context));
```
Search for "Subcontext access" in the [doxygen for System](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html).

In cases where you have access to the local subsystem, it is much preferable to use the GetMyContext... methods. 

But ... that would call for some redesign here, since you are using the presence of the diagram System to distinguish the two GetLog() overloads. My first thought is that it would be better to have a single method GetLog(context) and GetMutableLog(context) that will work with either the correct local subcontext or if given a root (diagram) context. From the many examples here it seems the latter is much more common so I'd rather see GetLog() than GetLogFromRoot() or some other long-winded name.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezYeMb7rlIYwL0wSof:-MfDuioeD_E29vKXebXm:bnzuzii) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The log of past values is unambiguously state information, since it can't be re-created from the other state variables (legit cache values can always be recalculated). However, that distinction only matters if the additional state information can be used to affect the evolution of a simulation. If the intent of the log is that it is only examined after the fact, and never in a manner that could affect the trajectory, then putting it in the cache is harmless. But we should document that the contents of a SignalLog should never be used to modify system behavior.

The reason we have to use a mutable (cache) value here is just that we trigger on Publish events rather than UnrestrictedUpdate events. In the latter case the WriteLog() method could be given a non-const Context which would allow an abstract state variable update. All things being equal, it would be better to put the log in an AbstractStateVariable. But I can see the appeal of logging on Publish() calls, and I believe there are some analyses that are made more difficult if there are extra state variables. So on balance I think using the cache and making people promise not to treat it like state is probably the best approach.
</blockquote></details>

So, the action item I gleaned is to document the intent to not feed back log data into a simulation.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezZOd9-TTWmWJgsXvC:-MfDv-YJ1RsSfoGGc2NU:b6bl69o) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Does my comment above address this?
</blockquote></details>

I don't think so? I guess my question here could have been more clear. The underlying SignalLog has const accessors and two mutators: write-to-log and reset. The old API mimicked those methods directly on the logger, giving access to per-system data.

Since the new API just refers to a SignalLog object elsewhere, is it still useful to offer GetLog/GetMutableLog? Do either one have to be not (SignalLogger) object const?  The reason this is troubling of course is that the python APIs completely disregard const-ness, since python doesn't have a convenient way to represent it.

---
___
*[systems/primitives/signal_logger.h, line 94 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAEQgYALh4BUsdMJOW:-MfDwBZa5Thdw2ncvQvu:b-ck0zeo) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Can you explain the intent of this new constructor? After deprecation of the mutables I assume we will only have the log-per-context mode in which case we'll have to deprecate this signature.
</blockquote></details>

This is the result of prior consultation with @jwnimmer-tri, given the unsatisfactory spamming of magic 1000 values in `r2` . His advice toward a deprecation strategy was to think not of the specific layout of the overloads, but rather of the call-site patterns allowed to compile. The current set of patterns is

(int)
(int, int)
(int, mode)
(int, int, mode)

Ultimately, the patterns would be

(int)
(int, int)

But as you point out, to achieve that, we would have to have a second deprecation of mode-containing patterns. The same problem applies to LogOutput, which is pretty much just a sugar over these constructors.

Suppose we were able to ignore or do away with the batch size parameter. It seems to me that we would still end up with a two-step deprecation process, since the introduced mode parameter (or defaulted boolean, or take your pick), would still turn up in call sites under the first deprecation, and have to itself be deprecated.

This makes me (of course) want to prefer the breaking change as the simplest possible step forward. Absent that, maybe forking on class name is just cleaner all around?
___
*[systems/primitives/signal_logger.h, line 151 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAMP4M4MNVcZBqfQvP:-MfE-NmP9cmA2kKZTlKW:b-wwh55a) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L151)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the terms outer_system and outer_context are new to me. Consider using diagram and diagram_context instead? Then you can say "containing diagram" which is a common Drake idiom. (and below)
</blockquote></details>

sure, but maybe these 2arg APIs are going away?
___
*[systems/primitives/signal_logger.h, line 240 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAI9RZ1MTIob-XOAx5:-MfE-UrzEwIzEmKxeRMS:b-2bgqur) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L240)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Same question here -- this will have to be deprecated later. Is it worthwhile to add it now?
</blockquote></details>

Maybe I'm missing something, but it seems to me that 2-step deprecation is an inevitable consequence of the deprecation strategies attempted so far. See ctor discussion above.
___
*[systems/primitives/signal_logger.cc, line 26 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAJ0gk2KnDofjulT9p:-MfE-qBI0DN5enx_sgFL:b-7ovbna) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I _think_ this can already work with an explicit call to AbstractValueCloner()?
</blockquote></details>

I'm not sure what you are suggesting. Don't we have an explicit call to AbstactvalueCloner in the present code?
___
*[systems/primitives/signal_logger.cc, line 50 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAO8kM2x2P63tC7eVR:-MfE02PK4krJSUSHqpt8:b-kl8g3z) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think this scalar-converting copy constructor needs updating? It isn't copying `storage_mode_` at least. Possibly needs an updated unit test that would have caught the problem.
</blockquote></details>

good catch.
___
*[systems/primitives/signal_logger.cc, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfATvLC4SZQvnTAe71k:-MfE0F_eADX4NLROHH5g:b-3jl5hp) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L143)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You don't need the diagram (`outer_system`) here to extract the local subcontext. This would work here:
```c++
GetMutableLog(this->GetMyContextFromRoot(outer_context));
```
Search for "Subcontext access" in the [doxygen for System](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system.html).

In cases where you have access to the local subsystem, it is much preferable to use the GetMyContext... methods. 

But ... that would call for some redesign here, since you are using the presence of the diagram System to distinguish the two GetLog() overloads. My first thought is that it would be better to have a single method GetLog(context) and GetMutableLog(context) that will work with either the correct local subcontext or if given a root (diagram) context. From the many examples here it seems the latter is much more common so I'd rather see GetLog() than GetLogFromRoot() or some other long-winded name.
</blockquote></details>

This makes me wonder -- should we have an idiom (everywhere) that permits passing local context or containing context, and the implementation just figures it out?

**Review by sherm1 — COMMENTED** [review]
Feature pass done, lots of discussion below.

> Reviewed 1 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MfETxlO5g9GU1CL1444:b-6mgkjw)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezYeMb7rlIYwL0wSof:-MfEC0Cv-unRCBYNXRsS:bcwx73x) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, the action item I gleaned is to document the intent to not feed back log data into a simulation.
</blockquote></details>

Yes, I think that's all that's needed.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezZOd9-TTWmWJgsXvC:-MfECGP-6wrlNikHUAwy:bn5n94i) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I don't think so? I guess my question here could have been more clear. The underlying SignalLog has const accessors and two mutators: write-to-log and reset. The old API mimicked those methods directly on the logger, giving access to per-system data.

Since the new API just refers to a SignalLog object elsewhere, is it still useful to offer GetLog/GetMutableLog? Do either one have to be not (SignalLogger) object const?  The reason this is troubling of course is that the python APIs completely disregard const-ness, since python doesn't have a convenient way to represent it.
</blockquote></details>

I think I understand the question now, thanks. If SignalLogger provides methods `reset(context) const`, `sample_times(const context) const`, and `data(const context) const` is there any need for direct access to the SignalLog? It would be nice to avoid the GetXLog() methods altogether.

---
___
*[systems/primitives/signal_logger.h, line 94 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAEQgYALh4BUsdMJOW:-MfEFevm8_v-Cpje9ZsD:beezgzs) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.h#L94)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This is the result of prior consultation with @jwnimmer-tri, given the unsatisfactory spamming of magic 1000 values in `r2` . His advice toward a deprecation strategy was to think not of the specific layout of the overloads, but rather of the call-site patterns allowed to compile. The current set of patterns is

(int)
(int, int)
(int, mode)
(int, int, mode)

Ultimately, the patterns would be

(int)
(int, int)

But as you point out, to achieve that, we would have to have a second deprecation of mode-containing patterns. The same problem applies to LogOutput, which is pretty much just a sugar over these constructors.

Suppose we were able to ignore or do away with the batch size parameter. It seems to me that we would still end up with a two-step deprecation process, since the introduced mode parameter (or defaulted boolean, or take your pick), would still turn up in call sites under the first deprecation, and have to itself be deprecated.

This makes me (of course) want to prefer the breaking change as the simplest possible step forward. Absent that, maybe forking on class name is just cleaner all around?
</blockquote></details>

I see. It does seem like a good idea to stop proliferating the 1000s everywhere! That's orthogonal to the primary purpose of this PR but I can see the appeal of doing it here. I suppose a two-step deprecation isn't that terrible.

But now I'm sold on your idea of creating a new class, say SignalLogger2, and deprecating the entire SignalLogger class. Then a 2-step deprecation would have its final step be to rename SignalLogger2 -> SignalLogger. Or if there's a name just as good as SignalLogger we could switch to that and have only a single deprecation. I think that would be cleaner than trying to make the change by contorting the individual APIs.
___
*[systems/primitives/signal_logger.cc, line 26 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAJ0gk2KnDofjulT9p:-MfESCjLAtFJd04oxevq:ba0unff) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm not sure what you are suggesting. Don't we have an explicit call to AbstactvalueCloner in the present code?
</blockquote></details>

No, not as of a recent merge. I just tried removing the AbstractValueCloner() from this code -- it builds fine and the tests pass.
___
*[systems/primitives/signal_logger.cc, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfATvLC4SZQvnTAe71k:-MfESUgn3yOFsR8mTDBW:bhtz0hs) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L143)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This makes me wonder -- should we have an idiom (everywhere) that permits passing local context or containing context, and the implementation just figures it out?
</blockquote></details>

That's a great thought. I'm not sure I would do this as a blanket change (at least without checking the performance implications). But we should at least have a reusable method like `subsystem.GetMyContext(context)` (`FindMyContext()` ?) where the context is allowed to be the right one or the top-level diagram context for the diagram containing the subsystem. Since the right context has a matching system ID we can check it very fast, then punt to GetMyContextFromRoot() if it doesn't match (maybe with a different error message).

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/primitives/signal_logger.cc, line 26 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfAJ0gk2KnDofjulT9p:-MfEySeu8XlB_B_0d9Wh:bmbd51j) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

No, not as of a recent merge. I just tried removing the AbstractValueCloner() from this code -- it builds fine and the tests pass.
</blockquote></details>

ah. maybe there is some with/without confusion in the original comment.
___
*[systems/primitives/signal_logger.cc, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfATvLC4SZQvnTAe71k:-MfEydCNEYULebFBeBMA:bow8bh7) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L143)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That's a great thought. I'm not sure I would do this as a blanket change (at least without checking the performance implications). But we should at least have a reusable method like `subsystem.GetMyContext(context)` (`FindMyContext()` ?) where the context is allowed to be the right one or the top-level diagram context for the diagram containing the subsystem. Since the right context has a matching system ID we can check it very fast, then punt to GetMyContextFromRoot() if it doesn't match (maybe with a different error message).
</blockquote></details>

Do we only ever have one level of enclosure (leaf --> root)? Going way down the rabbit hole here, and probably off topic, but I started wondering about diagram { diagram { leaf } } situations, if they even exist.

**Review by rpoyner-tri — COMMENTED** [review]
Given some other f2f discussions, I think I'm going instead to try a PR that forks on class name. We can then either leave the old class(es) around, or deprecate them as a separate step.
+(status: do not review) until I've had a chance to try the separate class approach.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MfFETF87Q2999kiUVMw:bfc3ora)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MezZOd9-TTWmWJgsXvC:-MfF-12H1X5bSbMQpkDL:b-5httq2) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think I understand the question now, thanks. If SignalLogger provides methods `reset(context) const`, `sample_times(const context) const`, and `data(const context) const` is there any need for direct access to the SignalLog? It would be nice to avoid the GetXLog() methods altogether.
</blockquote></details>

I gave up on the direct data access methods when I concluded that they needed multiple overloads to support convenient access. Having 2 or 3 copies of all the accessors already available on SignalLog smells like duplicate code and "feature envy" to me.

That said, if we boil log access down, then maybe it's ok.

---

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[systems/primitives/signal_logger.cc, line 143 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15428#-MfATvLC4SZQvnTAe71k:-MfFGFU8A4SNoX70t9sP:bduvd87) ([raw file](https://github.com/robotlocomotion/drake/blob/a8497ee75feefda13118a3db523594e070a7e985/systems/primitives/signal_logger.cc#L143)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do we only ever have one level of enclosure (leaf --> root)? Going way down the rabbit hole here, and probably off topic, but I started wondering about diagram { diagram { leaf } } situations, if they even exist.
</blockquote></details>

We frequently have nested Diagrams but we don't treat the non-root Diagrams with any significance. It would be possible to permit non-root Diagram contexts to be supplied and searched for the local subcontext, but the need for that doesn't come up because our Diagrams are so neutered. You can't really add any functional code to a Diagram, so we deal almost exclusively either with LeafSystem or top-level Diagram objects.

If we have a FindMyContext() method we could make it require leaf or root contexts for now and extend it later to reasonable intermediate contexts should the need arise later.

**Review by rpoyner-tri — COMMENTED** [review]
draft of new strategy at #15482.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-MfZStHXD_FEkNkQOCz2:b-t364vy)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
Now that the alternative PR train has started to roll, I think I will close this one.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15428#-:-Mfj5EC66iVH4mz9x_py:b-u8gfyh)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

**Pull request closed without merging**
