### PR TITLE
Append CMAKE_INSTALL_PREFIX to CMAKE_PREFIX_PATH

### PR DESCRIPTION
**Pull request by jamiesnape**
@david-german-tri for feature and platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3459)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/config.cmake, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3459#-KRiZX01HUPcVh0JT_ZP:-KRiZX02wwq84n5ctPoi:b-jmr7nj) ([raw file](https://github.com/robotlocomotion/drake/blob/29c3a176a55bc7d6b274d8cee176eb16e44db3b2/cmake/config.cmake#L163)):*
> ```CMake
>   set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON)
>   set(CMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY ON)
> ```

Please add a comment explaining why this matters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3459#-:-KRiZZHYoY51cNnmeCd_:bnfp4nl)*

**Pull request merged**
