### PR TITLE
Rewrite maven rules to use java_import_external 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is Bazel's new best practice.  Most acutely for us, it allows for multiple mirror URLs to be used.

Here we also update the repository names to match upstream's latest recommendations for mapping maven names into repository names.

Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7739)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.
+@soonho-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/maven.bzl, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7739#-L2eegkSrRQTNyNzDOEK:-L2eegkSrRQTNyNzDOEL:bdugdv9) ([raw file](https://github.com/robotlocomotion/drake/blob/87e9da32c63bb09a15f4b9e13298cc129e74aa2d/tools/workspace/maven.bzl#L6)):*
> ```Python
> MAVEN_BASE_URLS = [
>     "https://jcenter.bintray.com/",
>     "http://repo1.maven.org/maven2/",
> ```

BTW `https`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7739#-:-L2ef4KFqv62K2IoPB_n:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 16 of 18 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7739#-:-L2ezYUn3_f8VPDXtTVQ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Pull request merged**
