### PR TITLE
MBT acrobot example

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR implements an acrobot passive simulation modeled with MBT and visualized with GS.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7814)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@avalenzu for feature review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-:-L3FUvv9EpUHmRg3djeb:bll7v0f)*

**Comment by avalenzu** [comment]
Review pass finished. Two minor points inline. PTAL

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3Yc9PIUFM1V-L9Ah0z:-L3Yc9PIUFM1V-L9Ah1-:b-x81fb6) ([raw file](https://github.com/robotlocomotion/drake/blob/c0bc5cbe0825621448c809ccea8135ee13ed0a1c/examples/multibody/acrobot/acrobot_plant.h#L201)):*
> Kgr

I've never seen this abbreviation for killograms before. `kg` would be standard right?

---

*[examples/multibody/acrobot/passive_simulation.cc, line 193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3YbU0exwh692jSIiRa:-L3YbU0exwh692jSIiRb:b3ztez1) ([raw file](https://github.com/robotlocomotion/drake/blob/c0bc5cbe0825621448c809ccea8135ee13ed0a1c/examples/multibody/acrobot/passive_simulation.cc#L193)):*
> ```cpp
>       "with GeometrySystem visualization. "
>       "Launch drake-visualizer before running this example.");
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
> ```

Could you add a call to `drake::logging::HandleSpdlogGflags()` here, so that the logging level can be controlled from the command line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-:-L3Ycm1s_l554Q04CiDP:bv6vjgo)*

**Comment by amcastro-tri** [comment]
Thanks @avalenzu. +@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 201 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3Yc9PIUFM1V-L9Ah0z:-L3Yxa3Xc27HxbFQ6xEI:bk9fop1) ([raw file](https://github.com/robotlocomotion/drake/blob/c0bc5cbe0825621448c809ccea8135ee13ed0a1c/examples/multibody/acrobot/acrobot_plant.h#L201)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

> Kgr

I've never seen this abbreviation for killograms before. `kg` would be standard right?
</blockquote></details>

Good observation. Thanks.

---

*[examples/multibody/acrobot/passive_simulation.cc, line 193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3YbU0exwh692jSIiRa:-L3YzWcOEDzPISfOCCEI:b-m0z6fp) ([raw file](https://github.com/robotlocomotion/drake/blob/c0bc5cbe0825621448c809ccea8135ee13ed0a1c/examples/multibody/acrobot/passive_simulation.cc#L193)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Could you add a call to `drake::logging::HandleSpdlogGflags()` here, so that the logging level can be controlled from the command line?
</blockquote></details>

I am not using logging at all. But I believe it doesn't hurt for completeness. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-:-L3Z-14-eCHI6JYdMzhX:b-1v1dcu)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-:-L3ZcH30hwE9QG8rhw1c:bnfp4nl)*

**Comment by sammy-tri** [comment]
First pass complete.  Left a few comments (mostly about comments).

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/multibody/acrobot/acrobot_plant.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZakOtjNOlAsbw9CsT:-L3ZakOu4zCad0oN4BY8:b-mpyiqk) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.cc#L50)):*
> ```cpp
> using drake::multibody::UnitInertia;
> using drake::multibody::VelocityKinematicsCache;
> using systems::BasicVector;
> ```

BTW (nitpicky) inconsistent use of `drake::` for `multibody` namespace using lines but not `systems`.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZXQoY9yZMc_0SYjxP:-L3ZXQoY9yZMc_0SYjxQ:b-dzqkjf) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.h#L44)):*
> ```objc
> ///
> /// The parameters are defaulted to values in Spong's paper (see
> /// acrobot_spong_controller.cc for more details).
> ```

It might be clearer to use the full path to `examples/acrobot/acrobot_spong_controller` (though there is no `.cc` version of the file there either) if that's what this is referring to.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZY9-5CKJXmC3bQRa2:-L3ZY9-6LVMnb9YnUOJN:b-ucst48) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.h#L152)):*
> ```objc
>   }
> 
>   // No inputs implies no feedthrough; this makes it explicit.
> ```

This system appears to have an input port, so I'm confused by this comment (and the override).

---

*[examples/multibody/acrobot/acrobot_plant.h, line 159 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZZRq7PZ6FopyuRL1y:-L3ZZRq8jP9apMpTJLzf:b-6ryfrp) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.h#L159)):*
> ```objc
>   // It creates an empty context with no state or parameters.
>   // This override gives System::AllocateContext() the chance to create a more
>   // specialized context type, in this case, a MultibodyTreeContext.
> ```

It looks to me like this context will be created with state (making the comment unclear)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-:-L3ZdZqqLJjhu55Dwhj0:bh4a4jf)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZXQoY9yZMc_0SYjxP:-L3_3o1q5c9xQiwwfDf0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.h#L44)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It might be clearer to use the full path to `examples/acrobot/acrobot_spong_controller` (though there is no `.cc` version of the file there either) if that's what this is referring to.
</blockquote></details>

Done.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZY9-5CKJXmC3bQRa2:-L3_4HR2wTdeGH5IwkF0:bb61x8) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.h#L152)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This system appears to have an input port, so I'm confused by this comment (and the override).
</blockquote></details>

Copy/paste. Done.

---

*[examples/multibody/acrobot/acrobot_plant.h, line 159 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-L3ZZRq7PZ6FopyuRL1y:-L3_4UU3pKRmlok9NNoa:b-enpb3b) ([raw file](https://github.com/robotlocomotion/drake/blob/fa874d2ecdd9e52bafcd593fa518a41fc1c999ba/examples/multibody/acrobot/acrobot_plant.h#L159)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It looks to me like this context will be created with state (making the comment unclear)
</blockquote></details>

True. I don't really know where I got that from. Comment updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7814#-:-L3cnId42mc7aXFB1d_J:bnfp4nl)*

**Pull request merged**
