### PR TITLE
Update xenial install script

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4802)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4802#-:-KahG-IUsaPzm0fH4IPN:bnfp4nl)*

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by BetsyMcPhail** [comment]
(The previous unprovisioned run failed because I killed it - was doing some sanity checks)

**Comment by david-german-tri** [comment]
> (The previous unprovisioned run failed because I killed it - was doing some sanity checks)

Oops, sorry for starting another.  Feel free to kill it if it's not useful.

**Comment by BetsyMcPhail** [comment]
Not a problem, I'm happy to see another successful build

**Comment by BetsyMcPhail** [comment]
+@david-german-tri for platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4802#-:-KaiBmpT4Swn3wMzT1PW:b-buchyz)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4802#-:-KaiCwl0PDG_1Am2KF3Z:bnfp4nl)*

**Pull request merged**
