### PR TITLE
[geometry] Clean up meshcat tests for maintainability

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Use a variable to more easily space out the x-axis offsets.
Obey GSG's formatting rule for floating point literals.

Inspired by #19635.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19645)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews per schedule, please.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with a few questions

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19645#-:-NYTwk604qJeGxlaI8wu:b-jkmbin)* status: 2 unresolved discussions

___
*[`geometry/test/meshcat_manual_test.cc` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19645#-NYTw1U-5KF-emij5ODV:-NYTw1U00HHoXzYrxulA:b-i4acej) ([raw file](https://github.com/RobotLocomotion/drake/blob/3000ec80d66a1fdb9c1b1f52c90b7dbf9bff0321/geometry/test/meshcat_manual_test.cc#L69)):*
> ```cpp
>                       "drake/geometry/render/test/meshes/box.obj"),
>                   0.25));
>   meshcat->SetTransform("obj", RigidTransformd(Vector3d{2, 0, 0}));
> ```

BTW this object still has x=2, I was expecting ++x. Is this intentional? If so a comment noting the difference would be helpful.
___
*[`geometry/test/meshcat_manual_test.cc` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19645#-NYTwEeNELv5wr-tGAhG:-NYTwEeNELv5wr-tGAhH:b-dqnh5y) ([raw file](https://github.com/RobotLocomotion/drake/blob/3000ec80d66a1fdb9c1b1f52c90b7dbf9bff0321/geometry/test/meshcat_manual_test.cc#L70)):*
> ```cpp
>                   0.25));
>   meshcat->SetTransform("obj", RigidTransformd(Vector3d{2, 0, 0}));
>   meshcat->SetTransform("gltf", RigidTransformd(Vector3d{++x, 0, 0}));
> ```

BTW this new line for "gltf" surprised me based on the PR description. Is it intentional? If so consider updating the commit message.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19645)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

___
*[`geometry/test/meshcat_manual_test.cc` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19645#-NYTw1U-5KF-emij5ODV:-NYUCKB85zAa_H8yAXNX:b7cxajx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3000ec80d66a1fdb9c1b1f52c90b7dbf9bff0321/geometry/test/meshcat_manual_test.cc#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this object still has x=2, I was expecting ++x. Is this intentional? If so a comment noting the difference would be helpful.
</blockquote></details>

Oops.  You found a merge conflict I resolved incorrectly.  Thanks!
___
*[`geometry/test/meshcat_manual_test.cc` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19645#-NYTwEeNELv5wr-tGAhG:-NYUCMdP2OaI8S4KW0gh:b7cxajx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3000ec80d66a1fdb9c1b1f52c90b7dbf9bff0321/geometry/test/meshcat_manual_test.cc#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this new line for "gltf" surprised me based on the PR description. Is it intentional? If so consider updating the commit message.
</blockquote></details>

Oops.  You found a merge conflict I resolved incorrectly.  Thanks!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19645)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
