### PR TITLE
[lcm] Add option for a channel name suffix

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@zachfang for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337#-:-N3uN7TX36mX2_c_PbQV:b-dl33jj)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N3uN9US8CAy3h8SUQey:-N3uN9US8CAy3h8SUQez:buvriqj) (no related file):*
Working

Do not merge until we've proved out this proposed API in Anzu.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @zachfang)

___
*[`lcm/drake_lcm.cc` line 88 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N43l6nf1bW2Z7mp0HNZ:-N44Azit4SxPPvek7L-J:btxdfff) ([raw file](https://github.com/robotlocomotion/drake/blob/cd0ae1416fb66728a98975f909522a7bd820ee95/lcm/drake_lcm.cc#L88)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW
TIL a C++ struct can be initialized via a designated initializer! Isn't it a [C++20 feature](https://en.cppreference.com/w/cpp/language/aggregate_initialization)?
</blockquote></details>

This is a case where C++20 standardized the syntax that major compilers already supported.  So this is not C++17-compliant code, but rather relies on GCC and Clang to support it (which they do) even in pre-C++-20 mode.
___
*[`lcm/drake_lcm_params.cc` line 6 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N440kpvA6oVC7-ODf3A:-N44BAed3ikACa_vIbJq:b5qgor5) ([raw file](https://github.com/robotlocomotion/drake/blob/cd0ae1416fb66728a98975f909522a7bd820ee95/lcm/drake_lcm_params.cc#L6)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW
Question: is the reason to split the destructor in a `.cc` file because the actual code of a destructor can be large?  
</blockquote></details>

Yes.  I was on the fence about whether this was worth putting into a cc file, but I erred on the side of placing it here.  We have a GSG update coming soon that will (hopefully) help clarify this.
___
*[`bindings/pydrake/lcm_py.cc` line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N442dQ89J2HrExeP5cT:-N44AbFq-2UuOnhcSTlt:b5fqfz) ([raw file](https://github.com/robotlocomotion/drake/blob/cd0ae1416fb66728a98975f909522a7bd820ee95/bindings/pydrake/lcm_py.cc#L75)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: does `BR` stand for something here?
</blockquote></details>

It's borrowed from HTML terminology [`<br/>`](https://html.com/tags/br/).  It's what we tend to use in pydrake code to force a clang-format linebreak.

(For the pydrake bindings, we have a linter that enforces clang-format idempotency on all C++ files, so if we want a linebreak, we need to insert a comment to force one.)

**Review by zachfang — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N3uN9US8CAy3h8SUQey:-N44vnVY2hSnqiwxa9nW:b-gb1yo8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Do not merge until we've proved out this proposed API in Anzu.
</blockquote></details>

Will start working on the Anzu side to incorporate the changes here.

___
___
*[`bindings/pydrake/lcm_py.cc` line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N442dQ89J2HrExeP5cT:-N44uVHU6_2gXffUCOpw:b-4ekr2m) ([raw file](https://github.com/robotlocomotion/drake/blob/cd0ae1416fb66728a98975f909522a7bd820ee95/bindings/pydrake/lcm_py.cc#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's borrowed from HTML terminology [`<br/>`](https://html.com/tags/br/).  It's what we tend to use in pydrake code to force a clang-format linebreak.

(For the pydrake bindings, we have a linter that enforces clang-format idempotency on all C++ files, so if we want a linebreak, we need to insert a comment to force one.)
</blockquote></details>

OK. Thanks.

**Review by zachfang — COMMENTED** [review]
+@xuchenhan-tri for platform review. Thanks!
This PR is related to Anzu Issue 8925 and the corresponding changes in Anzu PR 8936.

> Reviewed 5 of 5 files at r5.
> Dismissed @jwnimmer-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337#-:-N4Y_SjHDhXEC4Urmrc-:b99ei1q)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@zachfang thanks for the reference!

platform :lgtm: with one question.

+(release notes: newly deprecated) 

> Reviewed 6 of 7 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337#-:-N4Z8Ww7DY7ODl7uzxsc:b-y64uqj)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/lcm_py.cc` line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N4Z86OkA3bhoEBbaD3T:-N4Z86OkA3bhoEBbaD3U:bo06l0w) ([raw file](https://github.com/robotlocomotion/drake/blob/3089354e16867440d4c17c0a5c290c683e2d5af4/bindings/pydrake/lcm_py.cc#L99)):*
> ```cpp
>     const char* const doc_deprecated =
>         cls_doc.ctor
>             .doc_deprecated_deprecated_2args_lcm_url_defer_initialization;
> ```

nit, does this doc still exist when the C++ documentation is deleted?

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N3uN9US8CAy3h8SUQey:-N4Zrf7_ENqeUP0XwJk_:b-tn2oev) (no related file):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Will start working on the Anzu side to incorporate the changes here.
</blockquote></details>

OK (attempt to resolve the working comment).

___
___
*[`bindings/pydrake/lcm_py.cc` line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N4Z86OkA3bhoEBbaD3T:-N4Zq-5s-pt7v6XN0iGG:bdnoe9f) ([raw file](https://github.com/robotlocomotion/drake/blob/3089354e16867440d4c17c0a5c290c683e2d5af4/bindings/pydrake/lcm_py.cc#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, does this doc still exist when the C++ documentation is deleted?
</blockquote></details>

From my understanding, the documentation is essentially the deprecation message, i.e., [`Use DrakeLcmParams instead`](https://github.com/RobotLocomotion/drake/blob/3089354e16867440d4c17c0a5c290c683e2d5af4/lcm/drake_lcm.h#L41).

From digging it a bit more, it follows the example to [deprecate a ctr](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/common/test/deprecation_example/cc_module_py.cc#L57_L62).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17337)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`bindings/pydrake/lcm_py.cc` line 99 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17337#-N4Z86OkA3bhoEBbaD3T:-N4ZuKyqEwHji9CdCTDc:blvnboh) ([raw file](https://github.com/robotlocomotion/drake/blob/3089354e16867440d4c17c0a5c290c683e2d5af4/bindings/pydrake/lcm_py.cc#L99)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

From my understanding, the documentation is essentially the deprecation message, i.e., [`Use DrakeLcmParams instead`](https://github.com/RobotLocomotion/drake/blob/3089354e16867440d4c17c0a5c290c683e2d5af4/lcm/drake_lcm.h#L41).

From digging it a bit more, it follows the example to [deprecate a ctr](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/common/test/deprecation_example/cc_module_py.cc#L57_L62).
</blockquote></details>

Got it, that makes sense. Thanks for the explanation!

**Comment by zachfang** [comment]
Thank you, Xuchen!

**Pull request merged**
