### PR TITLE
Upgrade to Bazel 6.2.0

### LINKED ISSUE #19389: Upgrade to Bazel 6.2.0
https://github.com/bazelbuild/bazel/releases/tag/6.2.0

The prior upgrade to 6.1.1 was #18946.

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves #19389

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19502)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
Full set of Linux jobs (copied from 6.1.1 update #19012 ):
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please

@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please

@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging please

@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Review by BetsyMcPhail — COMMENTED** [review]
+@xuchenhan-tri for both reviews please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19502#-:-NWm4bJ8CsIWyVS6VXcx:bdnkd7p)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: both.
+(release notes: fix) 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19502#-:-NWmYQA34mk7fSYpyTwo:bc9598n)* status: needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19502#-:-NWmYlxdB1HT1IcJ1CLN:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Pull request merged**
