### PR TITLE
type_safe_index_pybind: Make implicitly convertible from int

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Motivated by #15707

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for feature review / discussion

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726#-:-Mii4MnwDneGjRK7_NjD:b-mz3ror)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/common/test/type_safe_index_pybind_test.cc, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii4zXoAtxsbw2kH9zK:-Mii4zXoAtxsbw2kH9zL:b-nzslds) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8c50818cce30c735d60bb56de91724ab5437f6/bindings/pydrake/common/test/type_safe_index_pybind_test.cc#L61)):*
> ```cpp
>   // puke if another `TypeSafeIndex<U>` is encountered.
>   ASSERT_THROW(py::eval("pass_thru_index(10)"), std::runtime_error);
>   CheckValue("pass_thru_index(Index(10))", 10);
> ```

FYI I removed this test comparing directly to `int`, as it's more-or-less tested above.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-Mii5_A_B12dg5MOedK9:b-g7i6b7) (no related file):*
We already have some functions where the _only_ way to know which overload to select (and thus, which semantics to incur) is via the static type tag of the integer:

* https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a15f7c6ac560befe20d2607611bfecfc3
* https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a60b72f3a421d0dacc918c304649b6573
* https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#ae5a6b16b54a2ae435e3e89980e4229e9

It's possible that _some_ of the `TypeSafeIndex` tags should be implicitly convertible from `int`, but I very much doubt that _all_ of them should have that on by default.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-MilWsUvAhvLI0uEfBy_:b320qo2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We already have some functions where the _only_ way to know which overload to select (and thus, which semantics to incur) is via the static type tag of the integer:

* https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a15f7c6ac560befe20d2607611bfecfc3
* https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a60b72f3a421d0dacc918c304649b6573
* https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#ae5a6b16b54a2ae435e3e89980e4229e9

It's possible that _some_ of the `TypeSafeIndex` tags should be implicitly convertible from `int`, but I very much doubt that _all_ of them should have that on by default.
</blockquote></details>

Ooh, did not realize.

Some options:
(a) Only make some implicitly convertible - will require some discussion on which to admit; starting set are those in Sean's PR.
(b) Make all of the implicitly convertible to int, but prevent conversion for those arguments, e.g. `py::arg("state_index").noconvert()` - https://pybind11.readthedocs.io/en/stable/advanced/functions.html#non-converting-arguments
 (c) Make them all implicitly convertible, and in Python require distinction by kwarg.

Out of all of those, yeah, (a) sounds best. Will consider more minimal set.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-Mj-c3Fj3gmle9TgQpz0:b3xlleu) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ooh, did not realize.

Some options:
(a) Only make some implicitly convertible - will require some discussion on which to admit; starting set are those in Sean's PR.
(b) Make all of the implicitly convertible to int, but prevent conversion for those arguments, e.g. `py::arg("state_index").noconvert()` - https://pybind11.readthedocs.io/en/stable/advanced/functions.html#non-converting-arguments
 (c) Make them all implicitly convertible, and in Python require distinction by kwarg.

Out of all of those, yeah, (a) sounds best. Will consider more minimal set.
</blockquote></details>

I can fully support option (a). The mesh indices are definitely more of a hindrance than a help.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
What's the plan here -- it's blocking a number of PRs on my side.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726#-:-Mj5EgTe76xv6tGTtIpW:b-nbf42z)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
See below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726#-:-Mj5Id6A7o-JjATbMH3_:b-pnhr4h)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-Mj5I0-S0PzX9BKeI6pI:b-gh3vvn) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I can fully support option (a). The mesh indices are definitely more of a hindrance than a help.
</blockquote></details>

Done. Simplest support for option (a) is to add `py::implicitly_convertible<int, MyIndex>()` at the call-site. See expanded test.

Therefore, the feature of this PR isn't strictly necessary for your PR, but only serves to test / illustrate how it should function.
I'd be fine if this PR merges or gets abandoned.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-Mj5IUWr4yTblnF0QlXL:bidpm4m) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Simplest support for option (a) is to add `py::implicitly_convertible<int, MyIndex>()` at the call-site. See expanded test.

Therefore, the feature of this PR isn't strictly necessary for your PR, but only serves to test / illustrate how it should function.
I'd be fine if this PR merges or gets abandoned.
</blockquote></details>

@jwnimmer-tri how do you feel about option a? It would be as simple as providing an add'l parameter to `BindTypeSafeIndex` indicating whether it should be convertible or not.

The primary argument against it, as I see it, is that some would be convertible, some would not. That might lead to confusion. But we could append documentation in the "convertible" case so that the difference is, at least, documented.

The alternative would be to do what I've tentatively done in #15707.  Thoughts?

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15726)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-Mj5bn578Q1o-nYHZLxb:b-vfhom9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I dislike #15707 as it stands currently, because it incorporates conversion at the point-of-use, rather than being intrinsic to the index type.

I'll also note that whether the conversion should be implicit is best assessed via sample code, which #15707 does not really have much of.  My proposal to move forward would be to change #15707 to _only_ have the well-typed safe ints, with no conversion.  That should suffice to unblock any relevant uses (even though they might be verbose).

Then, separately, you could demonstrate sample code that showed the tradeoffs associated with implicit conversion, by adding some conversions.
</blockquote></details>

1. The assessment of conversion of point-at-use is valid. But I don't understand the significance.  Can you elaborate?
2. I respectfully disagree with the *implication* of insufficient code to asses via sample code. The code in the unit test succinctly contrasts the possible invocations based on on convertibility (regardless of how/where it is defined):

```py
        f_a = mut.SurfaceFace(v0=mut.SurfaceVertexIndex(3),
                              v1=mut.SurfaceVertexIndex(1),
                              v2=mut.SurfaceVertexIndex(2))
        f_b = mut.SurfaceFace(v0=2, v1=1, v2=0)
```

Admittedly, I don't have a solid mental model for just *how* interchangable a `FooIndex` is with an `int`, so this mix might lead to problems.

Still, I conclude that without any strong argument (beyond my own aesthetic distaste), I can't sufficiently justify this conversion (in any form). So, to unblock my work, I'll do a simple uncontroversial binding and defer streamlining to the hypothetical future.

@ericcousineau-tri Feel free to simply close this PR and I'll change how #15707 works.

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15726#-Mii5_A_B12dg5MOedK8:-Mj5l2al2zY31P0V7I-l:b-nhnozp) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

1. The assessment of conversion of point-at-use is valid. But I don't understand the significance.  Can you elaborate?
2. I respectfully disagree with the *implication* of insufficient code to asses via sample code. The code in the unit test succinctly contrasts the possible invocations based on on convertibility (regardless of how/where it is defined):

```py
        f_a = mut.SurfaceFace(v0=mut.SurfaceVertexIndex(3),
                              v1=mut.SurfaceVertexIndex(1),
                              v2=mut.SurfaceVertexIndex(2))
        f_b = mut.SurfaceFace(v0=2, v1=1, v2=0)
```

Admittedly, I don't have a solid mental model for just *how* interchangable a `FooIndex` is with an `int`, so this mix might lead to problems.

Still, I conclude that without any strong argument (beyond my own aesthetic distaste), I can't sufficiently justify this conversion (in any form). So, to unblock my work, I'll do a simple uncontroversial binding and defer streamlining to the hypothetical future.

@ericcousineau-tri Feel free to simply close this PR and I'll change how #15707 works.

</blockquote></details>

(1) It boils down to consistency / predictability / understand-ability.  My hypothesis is that having it sometimes convert, and sometimes not, would be a speed bump for users learning the codebase.

(2) I was coming at it from the point of view that the implicit integer conversions are sugar.  To assess the merit of sugar, the unit  test along is not worth much; we would want to see the implications of the sugar _in situ_ to reason about improvements to clarity / ease of use.

---

**Comment by EricCousineau-TRI** [comment]
> Feel free to simply close this PR and I'll change how #15707 works.

:+1:

**Pull request closed without merging**
