### PR TITLE
Adds And Implements maliput::api::Lane::EvalGeoMotionDerivatives().

### LINKED ISSUE #5390: Need a maliput::api::Lane API That Provides Motion Derivative in Geo-Space
# Problem Definition

Maliput lanes currently provide a way to get motion derivatives via [maliput::api::Lane:::EvalMotionDerivatives()](http://drake.mit.edu/doxygen_cxx/classdrake_1_1maliput_1_1api_1_1_lane.html#ab82fa390b6bc325473c13dc85dd02401). This method, however, returns the motion derivatives in lane-space `(s, r, h)`. To integrate with car models that operate in geo-space `(x, y, z)`, we need a version of this method that returns the motion derivatives in geo-space.

# Suggested Course of Action

Add a method called `maliput::api::Lane::EvalGeoMotionDerivatives()` that takes the same parameters as [maliput::api::Lane:::EvalMotionDerivatives()](http://drake.mit.edu/doxygen_cxx/classdrake_1_1maliput_1_1api_1_1_lane.html#ab82fa390b6bc325473c13dc85dd02401) but returns the motion derivatives in geo-space.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5390.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5392)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Explain why `EvalMotionDerivatives` and `GetOrientation` together don't already fully express this information?  This doesn't seem like the kind of thing that every backend should have to compute.

**Comment by liangfok** [comment]
How do I get the motion derivatives in (x, y, z) space using `EvalMotionDerivatives` and `GetOrientation`?

**Comment by jwnimmer-tri** [comment]
My intuition says it should be possible, but I haven't done the math.  I suspect five minutes with mechanics domain expert would answer it one way or another.

**Comment by liangfok** [comment]
Alright, I will investigate. Thanks!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5392#-:-KeHRcwAvqeZiVoPGXOt:b-r68qle)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please.

**Comment by liangfok** [comment]
Upon further inspection, I believe I can get the geo-space derivatives from lane-space derivatives using information contained in the following two methods:

- [Lane::ToGeoPosition()](http://drake.mit.edu/doxygen_cxx/classdrake_1_1maliput_1_1api_1_1_lane.html#a7835f1780f884bdfdebf11f02d2f7722)
- [Lane::GetOrientation()](http://drake.mit.edu/doxygen_cxx/classdrake_1_1maliput_1_1api_1_1_lane.html#aef43ce588dfcb9c2c5ecdb40dc472bdd)

I will thus close this issue, and allow rule-of-three to determine whether a `EvalGeoMotionDerivatives()` is warranted.

**Pull request closed without merging**
