### PR TITLE
[C-IRIS] combine rational_for_point and rational_for_matrix_sos.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also if a Lagrangian multiplier should be zero, we set it to zero polynomial directly, instead of adding its Gram matrix with bounding-box constraints gram_var = 0

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-:-NMB_E0n1X6Ql7bG9LBX:b7vod24)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
@AlexandreAmice as we talked in #18583, there is really no need to differentiate between rational_for_point and rational_for_matrix_sos. They are both rationals. The major difference between them is the number of `y` slack variable in the rational. In #18583 we hard-code the `y_slack_size()` function into `CollisionGeometry` class. But the number of `y` variables can be directly obtained from the rational function. Hence we don't need to store `y_slack_size` in CollisionGeometry, and we can handle `rational_for_point` and `rational_for_matrix_sos` together.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-:-NMBaNoD4Ghrk73aOZ3t:b403p3f)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Its a very nice change IMO thanks for doing it.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-:-NMEZsYQ8wu31L4yP-7w:b-jf3xms)* status: 9 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.h` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMERXR78Iahz7cFJVN2:-NMERXR78Iahz7cFJVN3:bke0n7z) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/collision_geometry.h#L90)):*
> ```objc
>    non-polytopic geometries.
>    @param[out] rationals The rational functions that need to be
>    positive to represent the geometry is on a given side of the plane.
> ```

nit grammar"that the geometry"
___
*[`geometry/optimization/dev/collision_geometry.cc` line 449 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZRwS78owj9tlTgl0:-NMEZRwS78owj9tlTgl1:bi79ml6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/collision_geometry.cc#L449)):*
> ```cpp
> 
>   void ImplementGeometry(const Cylinder&, void* data) {
>     auto* num = static_cast<int*>(data);
> ```

Now I think it is essential to comment on why the number of rationals is in each case.



_Code quote:_
```cpp
  using ShapeReifier::ImplementGeometry;

  void ImplementGeometry(const Box&, void* data) {
    auto* num = static_cast<int*>(data);
    *num = 8;
  }

  void ImplementGeometry(const Convex& convex, void* data) {
    auto* num = static_cast<int*>(data);
    const Eigen::Matrix3Xd p_GV = GetVertices(convex);
    *num = p_GV.cols();
  }

  void ImplementGeometry(const Sphere&, void* data) {
    auto* num = static_cast<int*>(data);
    *num = 2;
  }

  void ImplementGeometry(const Capsule&, void* data) {
    auto* num = static_cast<int*>(data);
    *num = 3;
  }

  void ImplementGeometry(const Cylinder&, void* data) {
    auto* num = static_cast<int*>(data);
    *num = 3;
  }
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 536 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMESvacC7b_tAZ-PhHZ:-NMESvacC7b_tAZ-PhH_:b-hv50p0) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/cspace_free_polytope.cc#L536)):*
> ```cpp
>                separating_plane.negative_side_geometry->type() !=
>                    GeometryType::kPolytope) {
>       // Do not add the negative side rationals that has no y_slack variable.
> ```

nit grammar "has no -> have no"
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 551 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMETsg0Bz5JWZH7KWdu:-NMETsg0Bz5JWZH7KWdv:blgwe1m) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/cspace_free_polytope.cc#L551)):*
> ```cpp
>                separating_plane.negative_side_geometry->type() ==
>                    GeometryType::kPolytope) {
>       // Do not add the positive side rationals that has no y_slack variables.
> ```

nit: grammar "has no" to "have no"
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 308 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEY_7p3i7v68zcJ2ah:-NMEY_7p3i7v68zcJ2ai:bphbq6w) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L308)):*
> ```cpp
>           .radius();
> 
>   CheckPolynomialWSlack(rationals[0], env, -a_expr.dot(p_AS) - b_expr,
> ```

assumes an order to the rationals which we don't promise anywhere, namely that the matrix sos conditions are first. I think we should have a 'CheckPolynomial' method which checks whether y_slack is in the indeterminates and then branches to these two methods



_Code quote:_
```cpp
  CheckPolynomialWSlack(rationals[0], env, -a_expr.dot(p_AS) - b_expr,
                        Eigen::Matrix3d::Identity(), a_expr, y_slack_, radius);
  CheckRationalExpression(rationals[1], env, -1 - a_expr.dot(p_AS) - b_expr);
```
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 319 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZ3gdDaEc-NHTq-bV:-NMEZ3gdDaEc-NHTq-bW:b-mwuyzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L319)):*
> ```cpp
>   CheckPolynomialWSlack(rationals[0], env, a_expr.dot(p_AS) + b_expr,
>                         Eigen::Matrix3d::Identity(), a_expr, y_slack_, radius);
>   CheckRationalExpression(rationals[1], env, a_expr.dot(p_AS) + b_expr - 1);
> ```

ditto on order of 'rationals'



_Code quote:_
```cpp
  CheckPolynomialWSlack(rationals[0], env, a_expr.dot(p_AS) + b_expr,
                        Eigen::Matrix3d::Identity(), a_expr, y_slack_, radius);
  CheckRationalExpression(rationals[1], env, a_expr.dot(p_AS) + b_expr - 1);
```
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 374 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZF1V1sMagf_iXFMt:-NMEZF1V1sMagf_iXFMu:b-mwuyzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L374)):*
> ```cpp
>                           capsule_shape.radius());
>   }
>   CheckRationalExpression(rationals[2], env, -a_expr.dot(p_AO) - b_expr - 1);
> ```

ditto on order of 'rationals'



_Code quote:_
```cpp
    CheckPolynomialWSlack(rationals[i], env, -a_expr.dot(p_AS.col(i)) - b_expr,
                          Eigen::Matrix3d::Identity(), a_expr, y_slack_,
                          capsule_shape.radius());
  }
  CheckRationalExpression(rationals[2], env, -a_expr.dot(p_AO) - b_expr - 1);
```
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 386 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZIVP3wvKeqj07kYB:-NMEZIVP3wvKeqj07kYC:b-mwuyzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L386)):*
> ```cpp
>                           capsule_shape.radius());
>   }
>   CheckRationalExpression(rationals[2], env, a_expr.dot(p_AO) + b_expr - 1);
> ```

ditto on order of 'rationals'



_Code quote:_
```cpp
    CheckPolynomialWSlack(rationals[i], env, a_expr.dot(p_AS.col(i)) + b_expr,
                          Eigen::Matrix3d::Identity(), a_expr, y_slack_,
```
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZL4AAsXEnkj_iU0h:-NMEZL4AAsXEnkj_iU0i:b-mwuyzs) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L443)):*
> ```cpp
>   // clang-format on
>   for (int i = 0; i < 2; ++i) {
>     CheckPolynomialWSlack(rationals[i + 1], env,
> ```

ditto on order of 'rationals'



_Code quote:_
```cpp
  for (int i = 0; i < 2; ++i) {
    CheckPolynomialWSlack(rationals[i + 1], env,
                          a_G_expr(2) * height[i] + b_G_expr, P, a_G_expr,
                          y_slack_.head<2>(), radius);
  }
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 449 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZRwS78owj9tlTgl0:-NMFMU1L8OtWjmG3pvk3:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/collision_geometry.cc#L449)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Now I think it is essential to comment on why the number of rationals is in each case.
</blockquote></details>

Done. Good call.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 308 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEY_7p3i7v68zcJ2ah:-NMFMwLz-2nQFkijtwff:bn32gt8) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L308)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

assumes an order to the rationals which we don't promise anywhere, namely that the matrix sos conditions are first. I think we should have a 'CheckPolynomial' method which checks whether y_slack is in the indeterminates and then branches to these two methods
</blockquote></details>

Done. Good call.

We still assume the order within rationals_for_points and rationals_for_matrix_sos. So I created a function to split `rationals` into two arrays, `rationals_no_y` and `rationals_with_y`, and test them separately.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 319 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZ3gdDaEc-NHTq-bV:-NMFUt051oZuNX8sJjQk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L319)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto on order of 'rationals'
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 374 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZF1V1sMagf_iXFMt:-NMFUtSy6SHa9JF9VUtw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L374)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto on order of 'rationals'
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 386 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZIVP3wvKeqj07kYB:-NMFUtsiAdwd4Le1CN_D:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L386)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto on order of 'rationals'
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/test/collision_geometry_test.cc` line 443 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMEZL4AAsXEnkj_iU0h:-NMFUuNy8JBrvCXn3K3U:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c20b369c655c6a4021d145e6fce51fabb87489c7/geometry/optimization/dev/test/collision_geometry_test.cc#L443)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto on order of 'rationals'
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 3 of 8 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 731 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMFWG2lDQADNE26RJqY:-NMFWG2mBocr2i0OeN_N:bkah0ac) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff3a87200b40a4d7817b978994c7791880b1cbd/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L731)):*
> ```cpp
>         negative_side_rational_lagrangians_result, plane.decision_variables,
>         plane_decision_var_vals, C, d, tester, 0);
>         plane_decision_var_vals, C, d, tester, 1E-5);
> ```

What's going on in this line?



_Code quote:_
```cpp
        plane_decision_var_vals, C, d, tester, 0);
        plane_decision_var_vals, C, d, tester, 1E-5);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 731 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-NMFWG2lDQADNE26RJqY:-NMFZf9rDIJjakUfhLQp:bo7escx) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ff3a87200b40a4d7817b978994c7791880b1cbd/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L731)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

What's going on in this line?
</blockquote></details>

Done.

Oops, that was a glitch in rebasing code. Just fixed.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18627#-:-NMFiVcg5jdX4-BeVsvX:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
