### PR TITLE
[multibody] Parse MuJoCo joint elements

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #16369

The relevant XML documentation is here: https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-joint

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@joemasterjohn for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525#-:-Mv9CHmuDXrXeP4A_Hgr:b7bdky2)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm:. +@rpoyner-tri for platform review, please.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525#-:-MvPPCPACC_dI4CJms9M:becwctl)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri and @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPIDTc832LUWmFDRa8:-MvPIDTc832LUWmFDRa9:b-17ibqm) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L171)):*
> ```cpp
>     }
> 
>     if (type == "free") {
> ```

nit: Since in Drake we do not determine whether a body is floating or not until `Finalize()` time, this opens up the possibility for 'free' joint types or 'freejoint' being defined for a body that is attached to a non-free joint. Setting the "DefaultFreeBodyPose" of that joint won't adversely affect the sim (it will effectively be ignored) but we might want to eventually detect this as an error. Could you add a small TODO here for that situation, please?
___
*[multibody/parsing/detail_mujoco_parser.cc, line 202 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPFA6j7zm6QUiSUAmJ:-MvPFA6j7zm6QUiSUAmK:b8euyf5) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L202)):*
> ```cpp
>     WarnUnsupportedAttribute(*node, "solimpfriction");
>     WarnUnsupportedAttribute(*node, "stiffness");
>     WarnUnsupportedAttribute(*node, "range");
> ```

nit: Any reason for not supporting "range" right now?
___
*[multibody/parsing/detail_mujoco_parser.cc, line 206 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPDq6460dAEoHl4kjS:-MvPDq6460dAEoHl4kjT:byiwb1x) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L206)):*
> ```cpp
>     WarnUnsupportedAttribute(*node, "ref");
>     WarnUnsupportedAttribute(*node, "springref");
>     WarnUnsupportedAttribute(*node, "armature");
> ```

nit: A bit frustrating because we do have support for "armature" (reflected inertia) but it is associated with Drake's `JointActuator` class and not the `Joint` class. Would you mind putting in `TODO(joemasterjohn): Parse and stash "armature" tag for the appropriate JointActuator attached to this joint.`? We can stash it the same way we do joint effort limits today.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 654 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPOi9d2ahg91EoHjeC:-MvPOi9d2ahg91EoHjeD:b-e71j1n) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/test/detail_mujoco_parser_test.cc#L654)):*
> ```cpp
>                   .IsNearlyEqualTo(X_WB, 1e-14));
> 
>   EXPECT_TRUE(
> ```

nit: You could also look up the implicitly created weld joint:
```
const WeldJoint<double>& weld_joint = plant.GetJointByName<WeldJoint>("world_welds_to_weld");
EXPECT_TRUE(weld_joint.X_PC().IsNearlyEqualTo(X_WB));
```

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: non-blocking test coverage questions

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525#-:-MvQ3Pt2CkhwqOze6uHt:b-vuqro9)* status: 4 unresolved discussions, missing label for release notes (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvQ2xJ18oDiXjTmioa-:-MvQ2xJ18oDiXjTmioa0:b1t2qe6) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L152)):*
> ```cpp
>     if (!ParseStringAttribute(node, "name", &name)) {
>       // Use "parent-body" as the default joint name.
>       name = fmt::format("{}-{}", parent.name(), child.name());
> ```

btw, this branch is unreached by unit tests -- is it interesting enough to want coverage now? Similarly for default names of bodies from a prior pr.

I'll let you decide.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525)* status: missing label for release notes (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 152 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvQ2xJ18oDiXjTmioa-:-MvRCA8l1Qq5_6otgcwH:bqmjwcz) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L152)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw, this branch is unreached by unit tests -- is it interesting enough to want coverage now? Similarly for default names of bodies from a prior pr.

I'll let you decide.
</blockquote></details>

Added.
___
*[multibody/parsing/detail_mujoco_parser.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPIDTc832LUWmFDRa8:-MvRKFRd4PN_TVNg-ERT:b-lmdwuq) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L171)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Since in Drake we do not determine whether a body is floating or not until `Finalize()` time, this opens up the possibility for 'free' joint types or 'freejoint' being defined for a body that is attached to a non-free joint. Setting the "DefaultFreeBodyPose" of that joint won't adversely affect the sim (it will effectively be ignored) but we might want to eventually detect this as an error. Could you add a small TODO here for that situation, please?
</blockquote></details>

Done.  I went ahead and handled it.  (note that due to the tree structure, we can't have loops).
___
*[multibody/parsing/detail_mujoco_parser.cc, line 202 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPFA6j7zm6QUiSUAmJ:-MvRKNHC6DHlJLnv_2nM:by9mln0) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L202)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Any reason for not supporting "range" right now?
</blockquote></details>

Done.  I went ahead and implemented them for hinges and sliders (+the tests).
___
*[multibody/parsing/detail_mujoco_parser.cc, line 206 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPDq6460dAEoHl4kjS:-MvRKr1y9Q7yNjqrRWqx:b-duyaok) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L206)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: A bit frustrating because we do have support for "armature" (reflected inertia) but it is associated with Drake's `JointActuator` class and not the `Joint` class. Would you mind putting in `TODO(joemasterjohn): Parse and stash "armature" tag for the appropriate JointActuator attached to this joint.`? We can stash it the same way we do joint effort limits today.
</blockquote></details>

Done!  I'll add ParseActuator in my next PR -- which will be the last substantial one in this first pass.
___
*[multibody/parsing/test/detail_mujoco_parser_test.cc, line 654 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPOi9d2ahg91EoHjeC:-MvRLRiM987pjEwto0UZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/test/detail_mujoco_parser_test.cc#L654)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: You could also look up the implicitly created weld joint:
```
const WeldJoint<double>& weld_joint = plant.GetJointByName<WeldJoint>("world_welds_to_weld");
EXPECT_TRUE(weld_joint.X_PC().IsNearlyEqualTo(X_WB));
```
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525)* status: missing label for release notes (waiting on @RussTedrake)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: again after r2 changes.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16525#-:-MvUI1Fj5-t9DkmkG1rt:bx8a8pk)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn (waiting on @RussTedrake)

___
*[multibody/parsing/detail_mujoco_parser.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16525#-MvPIDTc832LUWmFDRa8:-MvUHxR3DHmg9j--VPO_:b-wdj8zi) ([raw file](https://github.com/robotlocomotion/drake/blob/7d2f978898780040b659f4f3077755e48161489b/multibody/parsing/detail_mujoco_parser.cc#L171)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I went ahead and handled it.  (note that due to the tree structure, we can't have loops).
</blockquote></details>

Nice, thanks!

**Pull request merged**
