### PR TITLE
put matlab side of call_matlab_client_test under test.  towards #6707.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6823)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jamiesnape for feature review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-:-KrHCJcGoLWGal7F9q0Z:b-3u0d0w)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-:-KrVsWsG50ggY3OLCFX6:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental-matlab please
@drake-jenkins-bot linux-xenial-clang-experimental-matlab please
@drake-jenkins-bot linux-xenial-gcc-experimental-matlab please

**Comment by RussTedrake** [comment]
@jamiesnape .  all but one of the failures that i see in your additional tests are due to the servers not having run the fix for libstdc++ described in #6707.  I think those build servers will need to be updated.

for the other error (failed to load '/tmp/matlab_rpc')... i'm not sure.  it appears to have not parsed the command line arguments properly.  it should be calling "call_matlab_client('call_matlab_client_test.rpc')" and not trying to load from /tmp/matlab_rpc

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-:-KrWPCcekrZcKVwV14Oi:b-9vwc7e)*

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for platform review (should be safe despite sorting out the build server issues).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-:-KrWPkFp0wF1qRDLsV11:ba97jgp)*

**Comment by jamiesnape** [comment]
@RussTedrake I will look into the build server issues now.

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/common/proto/call_matlab.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWTv_UGuh7ODQM55wB:-KrWTv_VkVCDzL8qKnzp:b-xqyac3) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/common/proto/call_matlab.cc#L81)):*
> ```cpp
>   static google::protobuf::io::FileOutputStream raw_output(
>       open("/tmp/matlab_rpc", O_WRONLY | O_CREAT, S_IRWXU));
>   raw_output.SetCloseOnDelete(true);
> ```

Given the `raw_output.Flush()` down below, does this statement have any effect?

---

*[drake/common/proto/call_matlab.cc, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWT4KKdb9_kSPwN_ay:-KrWT4KLw0PQLUuFGJwY:b-g9cnf) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/common/proto/call_matlab.cc#L83)):*
> ```cpp
>   raw_output.SetCloseOnDelete(true);
> 
>   {  // Defines the lifetime of the CodedOutputStream.
> ```

FYI At one point, I believe that GSG said "do not introduce a local scope merely to control lifetime", but I can't find that anymore so I think it's been removed.

Another way to close the `output` on demand is to put it in a `unique_ptr` and then `unique_ptr.reset()` when you want to flush it, which provides a nice location to comment why we are destroying on demand, and to make the output-then-raw_output sequence even more obvious.

No defect.

---

*[drake/matlab/util/call_matlab_client.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWRyunjHJcwYhRz1ZE:-KrWRyunjHJcwYhRz1ZF:b84yx8j) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L11)):*
> ```cpp
> #include <mex.h>
> 
> #include <errno.h>
> ```

Prefer C++ headers when available: http://en.cppreference.com/w/cpp/header/cerrno.

---

*[drake/matlab/util/call_matlab_client.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWU_dyK4RE1sGNlcYK:-KrWU_dyK4RE1sGNlcYL:b-r1dun5) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L44)):*
> ```cpp
>   int file_descriptor = open(filename.c_str(), O_RDONLY);
>   if (file_descriptor == -1) {
>     mexErrMsgTxt(("Failed to open " + filename + ": " + strerror(errno)).c_str());
> ```

Line too long.

---

*[drake/matlab/util/call_matlab_client.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWUiFBHhBlyGclfFnr:-KrWUiFCRXBZMqtXnIQu:b-x8eq88) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L44)):*
> ```cpp
>   int file_descriptor = open(filename.c_str(), O_RDONLY);
>   if (file_descriptor == -1) {
>     mexErrMsgTxt(("Failed to open " + filename + ": " + strerror(errno)).c_str());
> ```

Once you are into the land of subexpressions, especially ones involving `std::string`, you can no longer rely on `errno` maintaining its value.  Things like heap allocation during string concatenation are allowed to reset it.  You should capture the errno to, e.g. , `const int open_errno = errno;` before calling any other functions and then use `strerror(open_errno)` in the message so that you're sure to get the correct string.

---

*[drake/matlab/util/call_matlab_client.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWVL9kwjpnKIrKLC_4:-KrWVL9l3Nv2ZLRCgOWB:b-tzr73g) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L44)):*
> ```cpp
>   int file_descriptor = open(filename.c_str(), O_RDONLY);
>   if (file_descriptor == -1) {
>     mexErrMsgTxt(("Failed to open " + filename + ": " + strerror(errno)).c_str());
> ```

The function is named `std::strerror`, so needs either a `using` above, or the `std::` decoration here.

---

*[drake/matlab/util/test/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWRla1uuYEWzUnkdwL:-KrWRla2azguUFrujy-t:b-qzfhwu) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/test/CMakeLists.txt#L1)):*
> ```CMake
> drake_add_matlab_test(NAME matlab/util/test/call_matlab_client_test COMMAND call_matlab_client('call_matlab_test.rpc'))
> ```

FYI If there is a way to line-wrap this <= 80 cols, that would be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823)*

**Comment by RussTedrake** [comment]
@jamiesnape -- fyi.. i've resolved the tmp/matlab_rpc issue with a few additional quotes in my CMakeLists.txt.  

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/common/proto/call_matlab.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWTv_UGuh7ODQM55wB:-KrWXIDMU4JXv2BlUoLP:b2kejft) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/common/proto/call_matlab.cc#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given the `raw_output.Flush()` down below, does this statement have any effect?
</blockquote></details>

i wouldn't have thought so, but experimentally it seemed that both were required to completely avoid the read failure on input.  

---

*[drake/matlab/util/call_matlab_client.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWRyunjHJcwYhRz1ZE:-KrWbM2JM1GVfmdqZQRc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Prefer C++ headers when available: http://en.cppreference.com/w/cpp/header/cerrno.
</blockquote></details>

Done.

---

*[drake/matlab/util/call_matlab_client.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWU_dyK4RE1sGNlcYK:-KrWbMZyKg9LC-5sYYm_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.

---

*[drake/matlab/util/call_matlab_client.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWUiFBHhBlyGclfFnr:-KrWbaSFH1FCcYZ2IM69:by2jgrc) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Once you are into the land of subexpressions, especially ones involving `std::string`, you can no longer rely on `errno` maintaining its value.  Things like heap allocation during string concatenation are allowed to reset it.  You should capture the errno to, e.g. , `const int open_errno = errno;` before calling any other functions and then use `strerror(open_errno)` in the message so that you're sure to get the correct string.
</blockquote></details>

nice catch.  thanks.  done.

---

*[drake/matlab/util/call_matlab_client.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWVL9kwjpnKIrKLC_4:-KrWbhbJkH56G8Tw6MPf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/call_matlab_client.cc#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The function is named `std::strerror`, so needs either a `using` above, or the `std::` decoration here.
</blockquote></details>

Done.

---

*[drake/matlab/util/test/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWRla1uuYEWzUnkdwL:-KrWbpc0SIjQDr-OTxnZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/matlab/util/test/CMakeLists.txt#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If there is a way to line-wrap this <= 80 cols, that would be nice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-:-KrWtNylcBvgDwDnxzl-:bvxksw8)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/proto/call_matlab.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWTv_UGuh7ODQM55wB:-KrX-AjjEhjPLBEIi-eB:b-9i6exy) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/common/proto/call_matlab.cc#L81)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i wouldn't have thought so, but experimentally it seemed that both were required to completely avoid the read failure on input.  
</blockquote></details>

So at a minimum, because this diverges from GSG requirements (by running code at `__fini__`-time)  there should be a comment explaining why we are doing so.

I read the protobuf code here, and I still have no idea why this would matter.  We are already flushing (below), and closing the filedes shouldn't have any bearing beyond that, since the process is about to end and so the OS will close the filedes  anyway.  But I guess for some unknown reason this is required, so you should put up a Chesteron's Wall comment so that the fix stays intact here.

---

*[drake/matlab/util/call_matlab_client.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWuuaaUqkIfbsSl7Wf:-KrWuuabwF86NQuj9Nan:b-r1dun5) ([raw file](https://github.com/robotlocomotion/drake/blob/6e86983ce5ddb5dc5742602593bae0e70c7b10f0/drake/matlab/util/call_matlab_client.cc#L46)):*
> ```cpp
>     const int open_errno = errno;
>     mexErrMsgTxt(
>         ("Failed to open " + filename + ": " + std::strerror(open_errno)).c_str());
> ```

Line too long.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-:-KrX-whBb45AehubDCUy:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/proto/call_matlab.cc, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWTv_UGuh7ODQM55wB:-KrX5t69ZFP5X7kE-vpX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d85a7e8ddde3a9a694b4a764a1cf0da51b7532bb/drake/common/proto/call_matlab.cc#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So at a minimum, because this diverges from GSG requirements (by running code at `__fini__`-time)  there should be a comment explaining why we are doing so.

I read the protobuf code here, and I still have no idea why this would matter.  We are already flushing (below), and closing the filedes shouldn't have any bearing beyond that, since the process is about to end and so the OS will close the filedes  anyway.  But I guess for some unknown reason this is required, so you should put up a Chesteron's Wall comment so that the fix stays intact here.
</blockquote></details>

Done.

---

*[drake/matlab/util/call_matlab_client.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6823#-KrWuuaaUqkIfbsSl7Wf:-KrX26QConUn3DtO_Pq9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6e86983ce5ddb5dc5742602593bae0e70c7b10f0/drake/matlab/util/call_matlab_client.cc#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Line too long.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6823)*

**Pull request merged**
