### PR TITLE
Use cubic interpolation in kuka_plan_runner

### PR DESCRIPTION
**Pull request by sammy-tri**
Since it looks like it's gonna stick around for a while...

This does make the arm move much more smoothly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5719)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-:-KgurgkVHEJPhlY7e6gp:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-KgutgB2K4PSBPH5brkb:-KgutgB2K4PSBPH5brkc:b-nv4mi8) ([raw file](https://github.com/robotlocomotion/drake/blob/977b82603518065d8f2192071cd0e8ed5c70c6d5/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L152)):*
> ```cpp
>       input_time.push_back(plan->plan[k].utime / 1e6);
>     }
>     if (knots.size() >= 3) {
> ```

you could conveniently just do cubic spline even with 2 knot points here, as long as you pass it end velocities. i think i fixed that in the spline generator. so no more foh, unless you have strong emotional attachment to it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-KgutgB2K4PSBPH5brkb:-KguwpOx4YavMuSrcI47:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/977b82603518065d8f2192071cd0e8ed5c70c6d5/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L152)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

you could conveniently just do cubic spline even with 2 knot points here, as long as you pass it end velocities. i think i fixed that in the spline generator. so no more foh, unless you have strong emotional attachment to it. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-:-Kgux2655sNzqerhONpJ:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-:-KguyPPe5ZmGV5GYZss5:b-gbk9vg)*

**Comment by ggould-tri** [comment]
Build failures appear unrelated.
The change appears reasonable.
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-:-KgyHtKrBnG1Ipsf_0Af:b-2ena2i)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5719#-:-KgzJdZhrY39ahbnxC12:bq323eq)*

**Pull request merged**
