### PR TITLE
Increase unit test tolerance for mac builds (#6208 patch)

### PR DESCRIPTION
**Pull request by amcastro-tri**
The unit test `PendulumKinematicTests::CalcPositionKinematics` from `double_pendulum_test.cc` (introduced in #6208) is failing in mac clang builds.
The problem is solved by a small increase of the tolerance used for floating point comparisons within this unit test. Tested in `macsim`.

Thanks @siyuanfeng-tri for finding this out and @soonho-tri and @jwnimmer-tri for helping with `macsim`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6334)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@siyuanfeng-tri for feature review please.
+@ggould-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6334#-:-KmavEOiJlagI0YN-g0l:b-14djlt)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6334#-:-KmavtBF53COPHa66eU1:bnfp4nl)*

**Comment by ggould-tri** [comment]
I think you're dancing on the cliff-edge here numerically.

`std::numeric_limits<double>::epsilon()` is the difference between 1.0 and the next representable value.  Because floating point precision halves with each doubling, and because `EXPECT_NEAR` uses absolute rather than relative error, `EXPECT_NEAR(x, y, constant*numerics_epsilon)` will be logically unattainable for many cases where `max(x,y) > constant`.

Since you are using this to compare angles, which can get as high as 2pi, comparisons with 2*epsilon or 3*epsilon can only succeed by luck.  I recommend at least 2pi*epsilon, or possibly 8*epsilon to be on the safe side.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6334#-:-Kmb-Z39kZ-MCbwkjrtP:b-4xhni)*

**Comment by soonho-tri** [comment]
@amcastro-tri : please consider adding the following (probably after addressing Grant's comment.

```
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
```

**Comment by amcastro-tri** [comment]
Per f2f discussion with @ggould-tri:
 - We agreed that tests using `isApprox()` can use a close to machine precision tolerances since the comparison is not absolute but relative.
 - However the comparison on angles should've actually been performed with `EXPECT_EQ` instead of `EXPECT_NEAR`  since those tests are only testing setters/getters. I therefore updated to use `EXPECT_EQ`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6334#-:-Kmc4I4NjeqWp-_le6VW:b-50enaz)*

**Comment by ggould-tri** [comment]
Awesome. :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6334#-:-Kmc6NeF1mGpeN9EgR8P:byzw5lo)*

**Pull request merged**
