### PR TITLE
Deprecate get mutable state functions in MultibodyPlant

### LINKED ISSUE #10636: `MbP::GetMutableFoo()` methods can dangerously bypass cache invalidation
For instance, if I do `auto my_qs = MBP::GetMutablePositions(context)` to retrieve a reference to the positions vector, everything depending on q's will get invalidated. Say I compute a pose and therefore position kinematics gets validated. If I later do `my_qs.setZero()`, nothing depending on qs will get invalidated leading to very obscure and difficult to track faulty computations. 

The proposed solution is to deprecate the `GetMutableFoo()` methods in favor of `SetFoo()` methods.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #10636

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-Nhbgz2U5Fln_dFCjilC:b-57wv8n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-NhgcJzXAqWKG9AAQBm9:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1290 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Nhgc7GIDxsS8vDwiWQW:-Nhgc7GIDxsS8vDwiWQX:b-kc319) ([raw file](https://github.com/RobotLocomotion/drake/blob/6d329bf95f73dc80c8575f3784fea2eb8364e15b/bindings/pydrake/multibody/test/plant_test.py#L1290)):*
> ```Python
>             # Write into a mutable reference to the state vector.
>             with catch_drake_warnings(expected_count=1) as w:
>                 x_ref = plant.GetMutablePositionsAndVelocities(context)
> ```

nit, we should proabably also unit test that GetMutablePosition and GetMutableVelocities are also properly deprecated

**Review by xuchenhan-tri — COMMENTED** [review]
+@sammy-tri for platform review per rotation please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-NhhNqc60c2NdtCfaxpC:b-nozcsa)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1290 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Nhgc7GIDxsS8vDwiWQW:-NhgxY1K4XmGlQ7JzGyX:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/6d329bf95f73dc80c8575f3784fea2eb8364e15b/bindings/pydrake/multibody/test/plant_test.py#L1290)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, we should proabably also unit test that GetMutablePosition and GetMutableVelocities are also properly deprecated
</blockquote></details>

Done

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee sammy-tri(platform)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee sammy-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: do not merge) while I test Anzu against the PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-NhhoN_f66lFUjI-WJ_C:b4kr4zr)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) CI passed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-Nhi7oH712-er9M7jFQ8:b-e8x0lz)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-@sammy-tri +@SeanCurtis-TRI for platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-Ni0ec5XCZT5DnzgOlai:bsyi41d)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done. A couple of small things (and some editorial comments about the state of Drake).

> Reviewed 4 of 7 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-Ni0qoAF0PDi4HDV8qaw:b-xzgv8a)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`multibody/plant/multibody_plant.h` line 2496 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0o0y4AWKk0v_gR1DC:-Ni0o0y4AWKk0v_gR1DD:b-j0nl5w) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/multibody/plant/multibody_plant.h#L2496)):*
> ```objc
>     Eigen::VectorBlock<VectorX<T>> q =
>         internal_tree().GetMutablePositions(context);
>     internal_tree().SetPositionsInArray(model_instance, q_instance, &q);
> ```

BTW Can I just make a passing comment on how silly this looks? We're acquiring the positions of the internal tree to pass in to the internal tree to write positions to the array.  Not a defect, but one would kind of expect something a bit more direct (a la `internal_tree().SetPositions(model_instance, q_instance)`). Same with velocities. But, meh, outside the scope of this PR.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 2865 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pIr69ZHvtKa9RdaL:-Ni0pIr69ZHvtKa9RdaM:byld9et) ([raw file](https://github.com/RobotLocomotion/drake/blob/5ad380e19f4e035c450ce41c57916c321eb0732a/multibody/plant/test/multibody_plant_test.cc#L2865)):*
> ```cpp
>   for (int i = 0; i < plant_->num_velocities(); ++i)
>     xc_expected[i + plant_->num_positions()] *= -1;
>   plant_->GetMutableVelocities(context_.get()) =
> ```

nit: The deprecated APIs should still be under test until the APIs are removed.
___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni0pvOO4AaKwf5F9yUV:bkcydgg) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
> ```cpp
>     const Body<double>& body0 = plant.GetBodyByName("b0");
>     plant.SetFreeBodyPose(context.get(), body0, X_B0);
>     VectorXd positions = plant.GetPositions(*context);
> ```

BTW Wow! The before and after seem quite different. The new version is definitely better than the old (no side effects). And as the tests pass, we can assume that the old side effect was neither intended nor required.
___
*[`bindings/pydrake/systems/test/controllers_test.py` line 235 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0qOmJ048tIp4ZCPcN:-Ni0qOmJ048tIp4ZCPcO:b90yqac) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/bindings/pydrake/systems/test/controllers_test.py#L235)):*
> ```Python
>         # Set the plant's context.
>         plant_context = plant.CreateDefaultContext()
>         with catch_drake_warnings(expected_count=1) as w:
> ```

nit: Surely this should be respelled in terms of the undeprecated API. The test, over all, requires the *effect* of the API (setting x in the context) but should do so without incurring deprecation warnings. I believe this should become, simply,

```py
plant.SetPositionsAndVelocities(plant_context, x)
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`multibody/plant/multibody_plant.h` line 2496 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0o0y4AWKk0v_gR1DC:-Ni1VEOtDY6cqOCkLm8n:b-6j7kmm) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/multibody/plant/multibody_plant.h#L2496)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Can I just make a passing comment on how silly this looks? We're acquiring the positions of the internal tree to pass in to the internal tree to write positions to the array.  Not a defect, but one would kind of expect something a bit more direct (a la `internal_tree().SetPositions(model_instance, q_instance)`). Same with velocities. But, meh, outside the scope of this PR.
</blockquote></details>

Agreed. I would have used the spelling you mentioned if it exists.
One step at a time.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 2865 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pIr69ZHvtKa9RdaL:-Ni1UCf8CV8y2HuwQHfe:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/5ad380e19f4e035c450ce41c57916c321eb0732a/multibody/plant/test/multibody_plant_test.cc#L2865)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The deprecated APIs should still be under test until the APIs are removed.
</blockquote></details>

Done
___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni1UIsk57HCztF6Jmrg:bnmiter) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Wow! The before and after seem quite different. The new version is definitely better than the old (no side effects). And as the tests pass, we can assume that the old side effect was neither intended nor required.
</blockquote></details>

Yeah, from the comment immediately above, it doesn't seem like the side effect is intended.
___
*[`bindings/pydrake/systems/test/controllers_test.py` line 235 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0qOmJ048tIp4ZCPcN:-Ni1UlbjCqw8d2b2BFOs:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/bindings/pydrake/systems/test/controllers_test.py#L235)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Surely this should be respelled in terms of the undeprecated API. The test, over all, requires the *effect* of the API (setting x in the context) but should do so without incurring deprecation warnings. I believe this should become, simply,

```py
plant.SetPositionsAndVelocities(plant_context, x)
```
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni1_lGSEfNN_n6bsvpW:b-u800wt) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yeah, from the comment immediately above, it doesn't seem like the side effect is intended.
</blockquote></details>

The call to `SetFreeBodyPose` still has a side effect though, so now we're splitting the difference.

Really, the problem seems like the `context` is scoped too widely.  If it were just a temporary within the lambda, that would be cleaner?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 2865 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pIr69ZHvtKa9RdaL:-Ni531aK5E4pHXmEGpev:b-fe4mgn) ([raw file](https://github.com/RobotLocomotion/drake/blob/5ad380e19f4e035c450ce41c57916c321eb0732a/multibody/plant/test/multibody_plant_test.cc#L2865)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

This is fine. I generally have a bias for wrapping the deprecated API tests into a single test case that can be deleted wholesale. It makes finalization simpler.  But this gets it done and the blocks are pretty obvious.
___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni53rPC5JRvLhbXg9sR:b-q01vnt) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
True.

Still, it's a lambda within the test. So, if it wants to mutate the context, it's not the end of the world. So, I'm marking myself as satisfied. If there were any change, I'd limit to the lambda's comment:

> Given a pose of the free body and the angle theta between bodies b0 and b1, updates the plant's state in the context and return's the plant's q.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni56tNwDCnR5zTElnXf:bvfewb1) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

True.

Still, it's a lambda within the test. So, if it wants to mutate the context, it's not the end of the world. So, I'm marking myself as satisfied. If there were any change, I'd limit to the lambda's comment:

> Given a pose of the free body and the angle theta between bodies b0 and b1, updates the plant's state in the context and return's the plant's q.
</blockquote></details>

My premise is that the change in this PR induced by your discussion here is _worse_ than what's on master.  The new halfway code begs the question of why we're sometimes mutating the context and sometimes not.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni5Ad6d00xWt5e4bt3c:bxsbspb) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My premise is that the change in this PR induced by your discussion here is _worse_ than what's on master.  The new halfway code begs the question of why we're sometimes mutating the context and sometimes not.
</blockquote></details>

I see, you're saying that at the conclusion of the call, the state does not reflect the full act. It should either leave the state untouched or it should have it fully mutated. But half way is a bad thing.

I can certainly get aboard simply allocating the context within the lambda. It's only called three times and the context isn't used otherwise. It makes the test a bit more computationally expensive, but it's clearer.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni5BpwT4g55M2SuZUEt:b-ij29gc) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
> I can certainly get aboard simply allocating the context within the lambda.

Yes, either that or call `RevoluteJoint::set_angle(context.get(), theta);`.  Using the Joint to set the angle in the context would be a more typical call sequence, and the least confusing spelling of the intended result.

> ... PR induced by your discussion here ...

Oops, my mistake. This was from r1, not a review-motivated changes.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni5Cnyc6raBRXzu8ssZ:broe3da) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I can certainly get aboard simply allocating the context within the lambda.

Yes, either that or call `RevoluteJoint::set_angle(context.get(), theta);`.  Using the Joint to set the angle in the context would be a more typical call sequence, and the least confusing spelling of the intended result.

> ... PR induced by your discussion here ...

Oops, my mistake. This was from r1, not a review-motivated changes.
</blockquote></details>

I thought about the revolute joint as well. I figured getting the right joint would take more code than simply allocating the context. That merely moves the line from outside the lambda to inside the lambda.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni5b-Tz6EkO73iD8uM-:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I thought about the revolute joint as well. I figured getting the right joint would take more code than simply allocating the context. That merely moves the line from outside the lambda to inside the lambda.
</blockquote></details>

Done

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`planning/test/collision_checker_test.cc` line 1562 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-Ni0pvOO4AaKwf5F9yUU:-Ni5bKix38kcAtPzjphO:b5gpjpu) ([raw file](https://github.com/RobotLocomotion/drake/blob/151efa9a2823f41cb93d615c530f77fa601ecd03/planning/test/collision_checker_test.cc#L1562)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

FTR The allocated context (up on 1534) is no longer used. I'm surprised there isn't an unused variable complalint.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Oops.  Sorry, I forgot.

:LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20424#-:-NiAA-0b1sWS029BU618:b8wl2yd)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,SeanCurtis-TRI(platform)

**Pull request merged**
