### PR TITLE
Add MakeMatrixVariable and its type-variants

### PR DESCRIPTION
**Pull request by soonho-tri**
Part of #8230

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8252)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by soonho-tri** [comment]
+@hongkai-dai for feature-review, please.
+@sammy-tri for platform-review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8252#-:-L6s0SyD2FnIOfs1isbO:b-qhjvrr)*

**Comment by sammy-tri** [comment]
:lgtm: (pending feature review)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8252#-:-L6w1AdXAwJDBdTtKPwc:boh4pyd)*

**Comment by hongkai-dai** [comment]
:lgtm: BTW, will you also provide `MakeVectorVariable` and `MakeSymmetricMatrixVariable` in the future?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8252#-:-L6w5D5SiveRYVoZcltM:b-viunmt)*

**Comment by soonho-tri** [comment]
Thanks for the reviews.

`MakeVectorVariable` and its variants are already here in `symbolic_variable.{h,cc}`.
I'll first update `MP` codebase to use these. Then I'll add `MakeSymmetricMatrixVariable` as requested.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8252#-:-L6w6g6DBvxKAV0TZzVI:by18ih4)*

**Pull request merged**
