### PR TITLE
Removes experimental ContactSolver workflow from MultibodyPlant

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards #16955.

This PR effectively removes the experimental workflow of setting a ContactSolver.
This will allow for a cleaner transition of TAMSI code into its own TamsiDriver as documented in #17741. 
We can reconsider later if we'd like to bring the ContactSolver workflow back or revamp it to a more useful form.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: pending one testing question.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121#-:-NEbnSC398CosqzQ5qN1:b-xexyxc)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/test/contact_solver_test.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbnHVKC9XBR_sT9y2m:-NEbnHVKC9XBR_sT9y2n:br9fvfa) ([raw file](https://github.com/robotlocomotion/drake/blob/eeb62d2590624c972e154275221383a87cbd80eb/multibody/contact_solvers/test/contact_solver_test.cc#L1)):*
> ```cpp
> #include "drake/multibody/contact_solvers/contact_solver.h"
> ```

Why is this unit test removed but the code under test untouched?
___
*[`multibody/plant/multibody_plant.h` line 4944 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbmwOS6eF3K6pm8Huq:-NEbmwOS6eF3K6pm8Hur:bsn68ah) ([raw file](https://github.com/robotlocomotion/drake/blob/ff65bdcce5ed5381dadddf027e1247f33c74f24d/multibody/plant/multibody_plant.h#L4944)):*
> ```objc
>   }
> 
>   // Helper to invoke our TamsiSolver. This method and `CallContactSolver()` are
> ```

nit `CallContactSolver` no longer exists.
___
*[`multibody/plant/multibody_plant.h` line 4956 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbmccjBOuzRyRBG6aU:-NEbmcck2CSyXZonRIhl:b-7keryk) ([raw file](https://github.com/robotlocomotion/drake/blob/ff65bdcce5ed5381dadddf027e1247f33c74f24d/multibody/plant/multibody_plant.h#L4956)):*
> ```objc
>   // Helper to invoke ContactSolver when one is available. This method and
>   // `CallTamsiSolver()` are disjoint methods. One should only use one or the
>   // other, but not both.
> ```

nit, this needs to go, along with the corresponding forward declare specialization on line 5351.



_Code quote:_
```objc
  // Helper to invoke ContactSolver when one is available. This method and
  // `CallTamsiSolver()` are disjoint methods. One should only use one or the
  // other, but not both.
  void CallContactSolver(
      contact_solvers::internal::ContactSolver<T>* contact_solver,
      const T& time0, const VectorX<T>& v0, const MatrixX<T>& M0,
      const VectorX<T>& minus_tau, const VectorX<T>& phi0, const MatrixX<T>& Jc,
      const VectorX<T>& stiffness, const VectorX<T>& damping,
      const VectorX<T>& mu,
      contact_solvers::internal::ContactSolverResults<T>* results) const;
```

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @xuchenhan-tri)

___
*[`multibody/contact_solvers/test/contact_solver_test.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbnHVKC9XBR_sT9y2m:-NEbobTAB6Q_65YOMrmN:bm8h9h8) ([raw file](https://github.com/robotlocomotion/drake/blob/eeb62d2590624c972e154275221383a87cbd80eb/multibody/contact_solvers/test/contact_solver_test.cc#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Why is this unit test removed but the code under test untouched?
</blockquote></details>

you mean the code for `ContactSolver`?
My reasoning is this:
 1. PgsSolver implements the ContactSolver API, and it's tested.
 2. ContactSolver will die eventually (maybe now is a good time if you agree?). So no need to spend time refining `internal::` work we used for experiments in the past.

Thoughts?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/test/contact_solver_test.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbnHVKC9XBR_sT9y2m:-NEc7GmU4VMbHkcQGYlm:b-qavqi) ([raw file](https://github.com/robotlocomotion/drake/blob/eeb62d2590624c972e154275221383a87cbd80eb/multibody/contact_solvers/test/contact_solver_test.cc#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

you mean the code for `ContactSolver`?
My reasoning is this:
 1. PgsSolver implements the ContactSolver API, and it's tested.
 2. ContactSolver will die eventually (maybe now is a good time if you agree?). So no need to spend time refining `internal::` work we used for experiments in the past.

Thoughts?

</blockquote></details>

IMO it makes sense to delete the test when the code is deleted. So we either delete `ContactSolver` along with the test here in this PR, or keep the test in this PR and delete it when `ContactSolver` is deleted in a future PR.
___
*[`multibody/plant/multibody_plant.h` line 4956 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbmccjBOuzRyRBG6aU:-NEc6x62-TVPm4hxJJOs:b-fy909p) ([raw file](https://github.com/robotlocomotion/drake/blob/ff65bdcce5ed5381dadddf027e1247f33c74f24d/multibody/plant/multibody_plant.h#L4956)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this needs to go, along with the corresponding forward declare specialization on line 5351.
</blockquote></details>

The forward declare specialization below also needs to be removed.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/test/contact_solver_test.cc` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18121#-NEbnHVKC9XBR_sT9y2m:-NEg-H_G3T8cgE_sZXws:byu4wfn) ([raw file](https://github.com/robotlocomotion/drake/blob/eeb62d2590624c972e154275221383a87cbd80eb/multibody/contact_solvers/test/contact_solver_test.cc#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

IMO it makes sense to delete the test when the code is deleted. So we either delete `ContactSolver` along with the test here in this PR, or keep the test in this PR and delete it when `ContactSolver` is deleted in a future PR.
</blockquote></details>

Per f2f. The unit test here covers setting up and invoking contact solvers from MbP which is deleted in this PR. I'm fine with removing the test.

**Comment by xuchenhan-tri** [comment]
+(release notes: none)

**Review by amcastro-tri — COMMENTED** [review]
Thanks @xuchenhan-tri.

+@ggould-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121#-:-NFAAzyGCDeS6Ee_iqyH:baz2s0n)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18121#-:-NFAN93FBUXxRW894Zne:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
