### PR TITLE
[ycb] Swich models demo to use meshcat

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16216.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16220)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI would you like to feature-review?  It's fine if you'd rather punt on this.

\CC @xuchenhan-tri @RussTedrake FYI

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16220#-:-MquY0q1AmnAYVz9D0ta:b-bsbi30)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[manipulation/models/ycb/test/parse_test.cc, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16220#-MquYh9z5FkX1rVHZ5FW:-MquYh9z5FkX1rVHZ5FX:bqrj7av) ([raw file](https://github.com/robotlocomotion/drake/blob/1834981240dc70b4c5d0ec3fc577e6a0759478e3/manipulation/models/ycb/test/parse_test.cc#L92)):*
> ```cpp
>   ScopeExit guard([&visualizer]() {
>     visualizer.Delete();
>   });
> ```

BTW Possibly a `MeshcatVisualizer` should auto-Delete itself, in its destructor?  Or offer the option to do so?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, nice!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16220#-:-MqvJWBL85sATTXs601l:b9lq5t5)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[manipulation/models/ycb/test/parse_test.cc, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16220#-MquYh9z5FkX1rVHZ5FW:-MqvJPrE2q6lmf7WqsVq:b-jwv7z0) ([raw file](https://github.com/robotlocomotion/drake/blob/1834981240dc70b4c5d0ec3fc577e6a0759478e3/manipulation/models/ycb/test/parse_test.cc#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Possibly a `MeshcatVisualizer` should auto-Delete itself, in its destructor?  Or offer the option to do so?
</blockquote></details>

+1 ! (unless there's a workflow we're missing?)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule (tomorrow), please.

**Comment by RussTedrake** [comment]
Re: should MeshcatVisualizer autodelete in its destructor -- of course I wouldn't object to having the option.  But I would definitely want it to be disabled by default.  One of the most common workflows is:

```
def my_experiment():
  builder = ...
  visualizer = MeshcatVisualizerCpp.AddToBuilder(...)
  visualizer.StartRecording()
  # simulate
  visualizer.PublishRecording()
  
my_experiment()
```
Here the visualizer is created and destroyed (or at least it goes out of scope and is subject to python garbage collection, if we do the reference counting properly).  But I very much still want the objects in the scene.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

I can see why you wrote `never_destroyed<std::shared_ptr<...>>` and it's clearly correct but wow is that weird construction to see written down.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16220#-:-MqyZk8n-qXbP945gk1N:b-63030m)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16220)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[manipulation/models/ycb/test/parse_test.cc, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16220#-MquYh9z5FkX1rVHZ5FW:-MqydUwgCGTaoxPIJ9l9:b-drij6a) ([raw file](https://github.com/robotlocomotion/drake/blob/1834981240dc70b4c5d0ec3fc577e6a0759478e3/manipulation/models/ycb/test/parse_test.cc#L92)):*
> Re: should MeshcatVisualizer autodelete in its destructor -- of course I wouldn't object to having the option. But I would definitely want it to be disabled by default.

OK SGTM.  We'll see what common use cases show up as we proceed through the porting.

**Pull request merged**
