### PR TITLE
Port planar_scenegraph_visualizer from underactuated

### PR DESCRIPTION
**Pull request by tehbelinda**
Originally known as planar_multibody_visualizer. Examples were separated into their own section under multibody.

Mesh support is removed for now. Follow up bindings to come

For #11104.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12218)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
For copyright purposes, please rebase this commit to contain a "Co-authored-by" stanza at the bottom listing all of the contributes to the underactuated file(s).  Details of the required format are under https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors.

**Comment by tehbelinda** [comment]
+@ericcousineau-tri for feature review please

**Comment by jwnimmer-tri** [comment]
According to https://github.com/RussTedrake/underactuated/commits/master/src/underactuated/planar_scenegraph_visualizer.py the list of Co-authored-by is still insufficient.

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LrtgV_1CsUcW_feCG0a:-LruaqJvD1oMqxjwRLoq:b-9hz5gm) ([raw file](https://github.com/robotlocomotion/drake/blob/f0a7f1acee03901429146016efe86c839a2c6aab/bindings/pydrake/systems/pyplot_visualizer.py#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is the only usage of this class is for `planar_scenegraph_visualizer`?

If so, perhaps we hide this class (and this file) for now, and only expose it if / when it's useful? (otherwise, it's an API commitment...)
</blockquote></details>

yes, sure hiding it makes sense. Are you suggesting I move the functionality into PlanarSceneGraphVisualizer directly and remove the PyplotVisualizer class altogether? (as opposed to just moving the class out of this file and into planar_scene_graph_visualizer.py)

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrtfza929YHz82NJ1Kx:-Lrubpz_74OxZwyTDE5q:b-bhnafi) ([raw file](https://github.com/robotlocomotion/drake/blob/f0a7f1acee03901429146016efe86c839a2c6aab/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L92)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you hide all members that are not intended to be public by prefixing them with `_`?
</blockquote></details>

sure, although I realised this particular one (Tview_pinv) isn't even used for anything

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LrtkdFg61dQvLb0WQff:-Lruyi3L8nSGwCw2eZSk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f0a7f1acee03901429146016efe86c839a2c6aab/bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py#L91)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you wrap all main code into a `main()` function, and then change this stanze to:
```
if __name__ == "__main__":
     main()
```

Rationale: It prevents leaking scope (e.g. the above functions could access `parser` or `model` since they are globals).

(Also, it makes using `trace.runfunc` easier:
https://drake.mit.edu/python_bindings.html#debugging-with-the-python-bindings )
</blockquote></details>

Done.

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LrtgV_1CsUcW_feCG0a:-LruzTcw0BBKTDV5R0Jv:b-x8jvx) ([raw file](https://github.com/robotlocomotion/drake/blob/f0a7f1acee03901429146016efe86c839a2c6aab/bindings/pydrake/systems/pyplot_visualizer.py#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... Thinking through them, maybe it is best that this be public API, but I think that it should be polished, possibly updated to be more generalizable.

If it's to remain here, I will go through it and scrutinize it a little bit more, and perhaps ask for a unittest using a toy implementation of this interface - perhaps using `DoubleIntegratorVisualizer` as the toy example to use the interface?
Sound good to you?

Verbose notes:

### Option 1: Use private file
Maybe simplest, if we can somehow indicate that `PlanarSceneGraphVisualizer` should only show members inherited from `PyPlotVisualizer`
* Rename this file to `_pyplot_visualizer.py`.
* In `planar_scenegraph_visualizer.py`, you can then just import the module but keep it module (so that the symbol `PyPlotVisualizer` is still hidden, e.g. `from pydrake.systems import _pyplot_visualizer`, and then inherit form this symbol explicitly:
```
class PlanarSceneGraphVisualizer(_pyplot_visualizer.PyPlotVisualizer):
```

Though writing this out now, this may hide the inherited methods from documetation - but they will still ultimately be public API.

### Option 2: Move it into `planar_scene_graph_visualizer.py`
You'd still have the same problems with functions not being documented, and would have a more cluttered file.

### Option 3: Merge functionality directly into `class PlanarSceneGraphVisualizer`
Would be simpler for documentation, but then this may not be usable for other instances (e.g. some time-varying bar chart or whatever).

### Option 4: keep it as-is, public
Perhaps simplest overall, though if that's the case, then we should have a unittest directly on this interface.
</blockquote></details>

Ok sounds good to me! After reading this and looking at usages of PyPlotVisualizer in underactuated, I'm leaning towards public API too, i.e. Option 4. Please scrutinise away

I also have some additional proposals/thoughts/questions:
1. Remove the SliderSystem class that's also in this file since that's not used anywhere in Drake
2. Raise NotImplementedError instead of printing in abstract methods, i.e. draw. Could even use the abstractmethod decorator but maybe that's overkill?
3. Making the draw_period/draw_timestep variable more consistent between the two classes - at the moment I'm thinking the one in PlanarSceneGraphVisualizer ought to match the base class?
4. Clarify which members should be public vs private, unless I'm missing something it looks like only `self.timestep`, `self.ax` and `self.fig` need to be public?

**Comment by jwnimmer-tri** [comment]
> Also, if you look at the commits in underactuated directly, I suspect they are using Russ's MIT email, not TRI. The Co-authored-by should be the same -- literally take the Author: line's spellings from all of the original commit(s).

Russ's email is still wrong in the Co-authored-by.

Here's how to check:
```console
jwnimmer@call-cc:~/tmp/underactuated$ git log src/underactuated/planar_scenegraph_visualizer.py | grep ^Author | sort -u
Author: Eric Cousineau <eric.cousineau@tri.global>
Author: Gregory Izatt <gregory.izatt@gmail.com>
Author: Russ Tedrake <russt@mit.edu>
```

Please squash-rebase in the next update with the fix to Co-authored-by.

**Comment by tehbelinda** [comment]
neat, thanks! and it looks like it's only Russ from before the rename

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 93 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv0W2zA5Kh1bdpsTMA:-LrvBN0nDDpZAnSwStb8:b6betuy) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L93)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can this PR only introduce one term for drawing period, either `draw_timestep` or `draw_period`?
(FTR, `MeshcatVisualizer` uses `draw_period`.)
</blockquote></details>

ok, sticking with draw_period for consistency with existing code. I'll change PyPlot to match

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv13b4ES1-sikexZcg:-LrvC5wb75K_-rgSkBw3:b-vlwv0z) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `lcm_visualization` seems like a misnomer here. Perhaps `pose_bundle` instead?

... but feel free to dimiss, as `SceneGraph` currently also uses `lcm_visualization` as it's output port :(
Relates #12214
</blockquote></details>

looks like MeshcatVisualizer does the same thing so at least it's a consistent misnomer... would it help if I added a TODO in both of them and link to that issue 12214?

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv2Dca2nJUjvWmu6_4:-LrvNjbrBWVKka4vh-ft:b-h3a86d) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L262)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can this class store the input bundle port (or index), and use the updated API, `OutputPort.Eval()`?
https://drake.mit.edu/pydrake/pydrake.systems.framework.html#pydrake.systems.framework.OutputPort_[float].Eval

e.g.
```
pose_bundle = self._pose_bundle_port.Eval(context)
```
</blockquote></details>

Hmm not sure I fully understand, quite possibly due to my lack of understanding of how the ports work in general.

I thought this was an input port, so would it be InputPort.Eval() ? Or are you saying that because it's the same as OutputPort anyway, e.g. from the docs for InputPort: `The actual value will be either the value of an OutputPort to which this is connected...` 

Which leads to my follow up question, when you say store the port do you mean setting it on init using `scene_graph.get_pose_bundle_output_port`? Looking at the bindings in geometry_py.cc there's only an output version

Or maybe I just need @seancurtis-tri  to explain this to me more :)

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 289 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv2x-w1gMuwaqioLg_:-LrvSju6EK17XrLY1VRf:bj6rkd7) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L289)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can this line break use parentheses instead of `\`?
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

e.g.
```
n_verts = (
    self._body_fill_dict[full_name][i].get_path().vertices.shape[0])
```

Alternatively, use a temporary variable to condense it, like `body_fill = self._body_fill_dict[full_name][i] ... body_fill.get_path().vertices.shape[0]`?

(Same for other instances here)
</blockquote></details>

Ah yes. I'll use the body_fill variable since it's going to be used multiple times below anyway

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv3mDoAHlQpYlEYv_U:-LrvTSTF9qZSDvGPJWMK:bgrox0) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/pyplot_visualizer.py#L96)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's unclear what type exactly `x` is. It's passed directly to `draw(self, context)`, but I'd assume `context` is of type `Context`...
</blockquote></details>

hmm so looking at the original C++, `log.data()` gives
```
Eigen::Block<const MatrixX<T>, Eigen::Dynamic, Eigen::Dynamic, true> data() const {
  return const_cast<const MatrixX<T>&>(data_).leftCols(num_samples_);
}
```
Would `plant_state` be a better name? or `state_vector`? 

the same term is used in PlanarSceneGraphVisualizer's `def draw` docstring: `...Can be passed either a raw state vector, or an input context.`
```
```

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv48y15IiGvs2nj1CW:-LrvVTdZEMSVGa6Rc3yp:bpbewpf) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/pyplot_visualizer.py#L96)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's unclear what the role of `get_recording` is vs. `animate`.
They both seem to kinda serve the same role-ish, except the `animate(...)` is intended for vector-valued systems (and provides interpolation / resampling)?
</blockquote></details>

it looks `get_recording` can also playback recorded frames as opposed to `animate` running on real time state?

cc @russtedrake if you have any insights into this

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 262 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv2Dca2nJUjvWmu6_4:-Lrz-GDc1a__BiR8SgXr:b-1yvtnh) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L262)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@ericcousineau-tri is alluding to the fact that when a port is delcared, it returns a reference to that port. He's suggesting you actually save that reference as a member (`self._pose_bundle_port`) and then you can evaluate the port directly (`self._pose_bundle_port.Eval(context)`) in place of the more indirect `System` API that requires *a priori* knowledge of the port's index (either hard-coded as zero or stored as a member).
</blockquote></details>

Ah ok, got it

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv4-o4BF9JVXo-jQMa:-Lrz-tGCD5qUYGyz83yS:b-q7fh97) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/pyplot_visualizer.py#L128)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's unclear why the magic `1000` is here. Should this instead be user-specified with a default value? (and what functionality does it provide?)
</blockquote></details>

interval is in milliseconds as opposed to timestep being in seconds - would a comment be enough? I see a few other places using a comment for this sort of thing, unless there is some util conversion function to use instead

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/BUILD.bazel, line 291 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lrv4lcx5Ll1a_TKISUG:-LrzoDz02xm7UjtzUTKT:b58ccgh) ([raw file](https://github.com/robotlocomotion/drake/blob/7b8c7f10c8577b14f797c779ad988e72700c51d3/bindings/pydrake/systems/BUILD.bazel#L291)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would it be possible to add a localized unittest for this, possibly building off of the double integrator version in `underactated`? (per above comment)
</blockquote></details>

I'm wondering if you have any suggestions on how to verify this test actually works? Maybe I'm missing something in how the ports ought to be connected, but I tried running just the same code in a __main__ function and I don't get any animation, just an empty plot... 
Also I thought it might be simpler to use the SimpleContinuousTimeSystem model instead, and that way there's less code for the policy/input aspects

For testing the recording API, does it make sense to keep an image in the test folder and compare it the result? It's almost getting to an integration test by that point. Or is it enough to unit test the values of the private variables have changed... Looking at the existing visualizer tests, they don't really unit test in the traditional sense either

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 77 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lsc4eK51lF9jeSr4Nd_:-LscD5Uq01PBNDvjjROl:bciq3zm) ([raw file](https://github.com/robotlocomotion/drake/blob/2f328b7862f467b5182a8a9ed545a31328e3f093/bindings/pydrake/systems/pyplot_visualizer.py#L77)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Could you remove these recording functions too?
</blockquote></details>

oh right, didn't realise it was for all recording functionality, sure! That solves my other questions too then

**Comment by tehbelinda** [comment]
do you have any tips on how to reproduce/debug the pydrake all_test failing? I naively tried to copy the command line from cdash but that didn't work out in my environment

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 233 at r6](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LsdDmMp207P-vjQ6TEY:-LsdG3VQ7h55z1cSeOJb:bn1f2aj) ([raw file](https://github.com/robotlocomotion/drake/blob/472016b41f59b1f1a04ea338c13f4af83413f54f/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L233)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Here, it looks like like this is a homogeneous array, so perhaps this can be simplified to something like this:
```
patch_G = ...  # When defining the coordinates, they should be defined in frame G.
...
# Compute pose in world.
patch_W = X_WG @ patch_G
```

This works because we've defined `RigidTransform.__matmul__` for arrays of vectors, so you can remove the homogeneous stacking of `np.ones(...)`. (You may need a transpose, though).
Example: https://github.com/RobotLocomotion/drake/blob/0f3045b6340571c32691fbaf4f5aa1390bf985ec/bindings/pydrake/test/math_test.py#L166-L184
</blockquote></details>

(note that `X_AB.multiply(p_B)` is equivalent to `X_AB @ p_B` in Python 3)

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 83 at r6](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LsdGb1xB5OzDvFrWKe9:-LsdGb1xB5OzDvFrWKeA:b-xtn7w0) ([raw file](https://github.com/robotlocomotion/drake/blob/472016b41f59b1f1a04ea338c13f4af83413f54f/bindings/pydrake/systems/pyplot_visualizer.py#L83)):*
> ```Python
>             repeat: Whether the resulting animation should repeat.
>         """
>         if type(log) is SignalLogger:
> ```

nit Instead of `type(x) is y` can you use `isinstance(x, y)` - here and below?

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LsdILi23eJl-xBzwkXf:-LsdJMP37S6cSb5LD51H:b-zhsyn4) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Debugging the import error, if I apply this hack patch:
```
diff --git a/bindings/pydrake/test/all_test.py b/bindings/pydrake/test/all_test.py
index e1a6637e7..39c03657a 100644
--- a/bindings/pydrake/test/all_test.py
+++ b/bindings/pydrake/test/all_test.py
@@ -17,3 +17,4 @@ class TestAll(unittest.TestCase):
         # Enable *all* warnings, and ensure that we don't trigger them.
-        with warnings.catch_warnings(record=True) as w:
+        # with warnings.catch_warnings(record=True) as w:
+        if True:
             # TODO(eric.cousineau): Figure out a more conservative filter to
@@ -21,3 +22,3 @@ class TestAll(unittest.TestCase):
             # warnings.
-            warnings.simplefilter("always", Warning)
+            warnings.simplefilter("error", Warning)
             warnings.filterwarnings(
```
And run it like so:
```
bazel run //bindings/pydrake:py/all_test -- TestAll.test_import_warnings
```

I get the full stacktrace:
```
======================================================================
ERROR: test_import_warnings (all_test.TestAll)
Prints if we encounter any warnings (primarily from `pybind11`) when
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../drake/bindings/pydrake/test/all_test.py", line 27, in test_import_warnings
    import pydrake.all
  File ".../drake/bindings/pydrake/all.py", line 49, in <module>
    from .systems.all import *
  File ".../drake/bindings/pydrake/systems/all.py", line 7, in <module>
    from .planar_scenegraph_visualizer import *
  File ".../drake/bindings/pydrake/systems/planar_scenegraph_visualizer.py", line 6, in <module>
    import scipy as sp
  File "/usr/lib/python3/dist-packages/scipy/__init__.py", line 114, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/usr/lib/python3/dist-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "scipy/_lib/_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c (scipy/_lib/_ccallback_c.c:3479)
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

So it seems like Ubuntu's scipy may make things sad? :(

Lemme see if there's a way around this without suppressing that warning...
```
</blockquote></details>

Min repro per current formulation:
```
$ python3 -c 'import warnings; warnings.simplefilter("always", Warning); import scipy'
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

---


<!-- Sent from Reviewable.io -->

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LsdILi23eJl-xBzwkXf:-LsslU4Q8rtovi8Jhn9t:b-ku8da5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Seems like it's only necessary for `scipy<=0.19.1`. From tinkering with it, it's fixed in the version after that, `scopy>=1.0.0`:
https://github.com/scipy/scipy/issues/11000#issuecomment-548990247
</blockquote></details>

so should I add a TODO to remove once scipy is upgraded? Or will we just move to only supporting later scipy in CI too? (I realised i have > 1 installed too so I guess that's why I never ran into it)

---

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 103 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lsw4NRb3LFzhzHK-t9S:-LsyCJJ39YkfffEmtRNW:bzgqw0y) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L103)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

There're debug CI errors about orthonormality here:
```
RuntimeError: Error: Rotation matrix is not orthonormal.
  Measure of orthonormality error: 1  (near-zero is good).
  To calculate the proper orthonormal rotation matrix closest to the alleged rotation matrix, use the SVD (expensive) method RotationMatrix::ProjectToRotationMatrix(), or for a less expensive (but not necessarily closest) rotation matrix, use the constructor RotationMatrix<T>(ToQuaternion(your_Matrix3)).  Alternately, if using quaternions, ensure the quaternion is normalized.
```

I think this *shouldn't* be a `RigidTransform`, but instead just a 3x4 matrix, since it's for a projection from 3d to 2d. (sorry for missing that earlier!)
</blockquote></details>

Hmm ok, but then does that mean I need to bring the np.ones back to make the patches a 4xN instead of 3xN so the sizes match since there's no longer the RigidTransform class to take care of it?

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 103 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lsw4NRb3LFzhzHK-t9S:-Lt0HyXl8TQFsmOcVYXx:buggv5t) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L103)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

Hmm ok, but then does that mean I need to bring the np.ones back to make the patches a 4xN instead of 3xN so the sizes match since there's no longer the RigidTransform class to take care of it?
</blockquote></details>

Ah, my bad again :( Yup, you'll need the homogeneous part back - sorry!

Tried writing out a class to encapsulate that logic, but it doesn't make things all that better...

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 94 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LswSNba7WDruDQnmZd-:-Lt0lseX9s7tkOBtKX7E:bg2vp4k) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/pyplot_visualizer.py#L94)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The `Trajectory` version of this function is neither tested or documented, afaict.   what's its purpose?
</blockquote></details>

Hmm maybe it's no longer needed... @RussTedrake do you have a use for this still?

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py, line 18 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lsws31GBVXwSBDeJlNF:-Lt0n-_ADa6Y7lKhYLWV:bniuap4) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py#L18)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure any of these tests even make sure `draw` was called.  Is there some way we can at least verify that the code being tested executed at all?  (look for the time in the axis name?  I'm not really sure.)   Or is the test rule for the example sufficient?
</blockquote></details>

Is code coverage meant to work with Python code too? I tried with --config kcov but no dice

Looking at the other existing visualizer tests this has been sufficient so far... When I run it I can visually inspect that it's working, but unless we build in some sort of image capturing / comparison that's hard to capture in a unit test

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/planar_scenegraph_visualizer.py, line 103 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lsw4NRb3LFzhzHK-t9S:-Lt0qzqh1H0L25oJgo5x:b-cujjk0) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/planar_scenegraph_visualizer.py#L103)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, my bad again :( Yup, you'll need the homogeneous part back - sorry!

Tried writing out a class to encapsulate that logic, but it doesn't make things all that better...
</blockquote></details>

All good!

**Comment by tehbelinda** [comment]
___
*[bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py, line 18 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-Lsws31GBVXwSBDeJlNF:-Lt1755O871cp1kkDqb0:bdv9yok) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Perhaps you can add `ani = visualizer.animate(...); self.assertIsInstance(ani, ...)` to the end of these tests, as you did for the pyplot visualizer?
</blockquote></details>

Actually calling draw seems to work well with the title in the axis check? that way it's also directly planar scenegraph's API as opposed to repeating calling pyplot's API

**Comment by RussTedrake** [comment]
___
*[bindings/pydrake/systems/pyplot_visualizer.py, line 94 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12218#-LswSNba7WDruDQnmZd-:-Lt1QqwZ5SlPoEFq6ZJN:b9xuq0c) ([raw file](https://github.com/robotlocomotion/drake/blob/85d287dabf5bbee6481cb1284824d203ee3f666c/bindings/pydrake/systems/pyplot_visualizer.py#L94)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

Hmm maybe it's no longer needed... @RussTedrake do you have a use for this still?
</blockquote></details>

We have three main visualizers in play now -- DrakeVisualizer (c++), MeshcatVisualizer (python only, for now), PyPlotVisualizer (python only, forever).  Ideally they would all have a similar interface for playing back outside of simulation.  Currently, it's clear that they do not.

`DrakeVisualizer` has `PlaybackTrajectory` which is basically this  https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_drake_visualizer.html#a873c92ceec89505b77400469dc9c96e1
It no longer has a method that plays back from a signal log -- I believe it was @seancurtis-tri that implemented an internal caching mechanism instead.

MeshcatVisualizer has no interfaces of this type (but should).

I think that this class should be consistent with the `DrakeVisualizer` api... even if the `enable_playback` feature is left as a TODO for now.

**Comment by mitiguy** [comment]
BTW Post Squash-Merge-Thoughts.  Regarding the following piece of code:
https://reviewable.io/reviews/robotlocomotion/drake/12218#-LrteaVzAPmF_AfyOSJa

It would be helpful to understand if it may make sense for this projection to be part of the RigidTransform class.  I have questions about this -- particularly whether the projection is interpretable as relating two frames.  I checked in with Bel today and will talk to Sean after he returns. 
Eric - if you have thoughts, let us know.
@ericcousineau-tri @tehbelinda @seancurtis-tri  @sherm1

**Comment by EricCousineau-TRI** [comment]
I had misspoken earlier about trying to make this a `RigidTransform` - sorry about that!
I'm not sure if that projection should be part of the `RigidTransform` class, because it's not even isometric - it's intended to collapse a dimension - and possibly go beyond just orthographic projections (per the comments in the code).

However, it would still be nice somehow leverage the monogram notation (or some form of it) when going between 2D frames (the view, `V`, or whatevs) and 3D frames (the world `W`), hence possibly using `T_VW` (for a general transform?) instead of `X_VW`.
I'd totes understand if that's a stretch of monogram, but it's nice to know what "space" a matrix is projecting from/to.

**Comment by EricCousineau-TRI** [comment]
Er, mayhaps I missed the proper use of the term "isometric" here... sorry! But in my mind, I'd think it would be simpler if `RigidTransform` stuck to transform stuff in 3D Euclidean space, which this particular projection does not.

**Comment by sherm1** [comment]
The reason I chose "X" for rigid transform long ago was so that "T" could remain available for general transforms (with scale, skew, reflection, etc. as in OpenGL).

But I have used X_AB notation in 2d as well -- as long as it just translates and rotates in the plane without any distortions (a 2d isometry). The representation for X_AB can be more compact but the concept is unchanged.

A projection from 3d to 2d seems out of scope for the rigid transform and rigid rotation classes since it is a different transformation.

**Pull request merged**
