### PR TITLE
Updates to windows build doc

### PR DESCRIPTION
**Pull request by ggould-tri**
Added in a missing path.
Noted that build instructions as written preclude snopt.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3044)

### CODE REVIEW

**Comment by ggould-tri** [comment]
These are issues that prevented me from getting a windows build working yesterday.

+@david-german-tri on-call platform reviewer.
+@sherm1 an actual windows user.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-:-KOGsHRWO_pUB5Jb3ndI:-2132715733)*

**Comment by ggould-tri** [comment]
-@david-german-tri is not actually on-call today.  Oops.
+@jwnimmer-tri is!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-:-KOGsrG9RHrCiQZ_xRK9:1097014462)*

**Comment by jwnimmer-tri** [comment]
Fine by me :lgtm:.

Probably should also tag someone at Kitware for review.  I can't quite recall who is the windows build guru of the moment there.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/windows.rst, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-KOGyeabNxKKG9d9XGw4:-KOGyeabNxKKG9d9XGw5:-670252023) ([raw file](https://github.com/robotlocomotion/drake/blob/739e282d1455b18dac86515c154ac3a6d67ba2e0/drake/doc/windows.rst#L102)):*
> ```reStructuredText
> NOTE:  If you want to use the `WITH_SNOPT` build option, you will need to
> use ssh rather than https access to github.  Follow github's instructions
> for setting up ssh key access.
> ```

BTW This is true for more than just SNOPT -- the `.gitmodules` files indicates which modules come in over ssh.  Consider adding the full list (or explaining how to find out from the `.gitmodules`?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-:-KOGyr9oDPy0BkPNtKC7:-614307206)*

**Comment by david-german-tri** [comment]
+@mwoehlke-kitware, would that be you?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-:-KOGzR9eQZKfbMQX6ss_:317722689)*

**Comment by sherm1** [comment]
:lgtm: I'm no help regarding the ssh/https requirements though. I have never tried to build Drake with anything but the default set of externals and those all seem to work fine.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/doc/windows.rst, line 176 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-KOHMGSYUoeaiMiTFyMa:-KOHMGSYUoeaiMiTFyMb:-1660952523) ([raw file](https://github.com/robotlocomotion/drake/blob/739e282d1455b18dac86515c154ac3a6d67ba2e0/drake/doc/windows.rst#L176)):*
> ```reStructuredText
> 
> * ``[build artifacts directory]\install\lib``
> * ``[build artifacts directory]\install\bin``
> ```

BTW, I agree that `bin` is necessary. Eventually we  should be able to get rid of `lib`. See issue #2869.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-:-KOHMhSNaO_32aT-bJhG:-2091454147)*

**Comment by jwnimmer-tri** [comment]
To be safe, tagging "do not merge" until we get a look from kitware.  Please feel free to remove the label once that happens, or if @ggould-tri elects to skip it.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/windows.rst, line 176 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-KOHMGSYUoeaiMiTFyMa:-KOKjdMexxgjyqNmt9lA:-294724836) ([raw file](https://github.com/robotlocomotion/drake/blob/739e282d1455b18dac86515c154ac3a6d67ba2e0/drake/doc/windows.rst#L176)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, I agree that `bin` is necessary. Eventually we  should be able to get rid of `lib`. See issue #2869.
</details>
BTW, I'm less certain that `bin` is needed, at least in the long run. Certainly it's convenient, though, as it allows running drake applications without giving the full path or already being in that directory. However, it should only be *needed* if you're trying to run an executable that needs the drake libraries and isn't in `<install>/bin`. (Needing `lib` is just a bug: #2869 as noted.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-:-KOKkvI1maIszwKXjtBl:1417088721)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/doc/windows.rst, line 102 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3044#-KOGyeabNxKKG9d9XGw4:-KOKqC4p5Ga26lPXsKRO:-1283531307) ([raw file](https://github.com/robotlocomotion/drake/blob/739e282d1455b18dac86515c154ac3a6d67ba2e0/drake/doc/windows.rst#L102)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This is true for more than just SNOPT -- the `.gitmodules` files indicates which modules come in over ssh.  Consider adding the full list (or explaining how to find out from the `.gitmodules`?).
</details>
I'm going to leave this is as is because I am not going to speculate a millimeter beyond my experience with Windows.  More ambitious editing of this file should rely on people who actually know anything about windows development.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3044)*

**Pull request merged**
