### PR TITLE
Add FAQ for DualABI incompatibility with gcc-4.9.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This addresses #7467 per the discussion.

\cc @jamiesnape @jwnimmer-tri @naveenoid 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7491)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-Kz2Sr8ucgPlPhcvtvlP:b-g5v4cm)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/faq.rst, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz3uSaa6cTTxxQ0YWdG:-Kz3uSaa6cTTxxQ0YWdH:b-6kin3f) ([raw file](https://github.com/robotlocomotion/drake/blob/64c7bc18bcc96bee9f7cf6631ba4b9258274328f/doc/faq.rst#L120)):*
> ```reStructuredText
> **Solution**: This is most likely due to an incompatibilty between the compiler used to produce Drake (e.g. ``clang-4``) and the compiler that CMake has selected (e.g. ``gcc-4.9``). Specifically, ``gcc-4.9`` or before does not tend to handle the DualABI well when linking against ``clang``-compiled code [#dual_abi]_. You may be able to use other functions, because only functions that return an ABI-dependent class (e.g. ``std::string``) are tagged with the ABI that they are using (since they cannot be distinguished in the function signature).
> 
> The fix is to change the compiler CMake is using. One way to do this is to set the ``CC`` and ``CXX`` environment variables to use the correct compiler, e.g. a later version of ``gcc``, or the same compiler that Bazel built the shared library with.
> ```

BTW Change "correct compiler" to "supported compiler" and link to the supported platforms matrix? Also maybe you could add a note to below that matrix saying that the binary packages are built with Clang 4.0 on Ubuntu 16.04 and Apple Clang 9.0 on macOS 10.13 and then link somewhere in the last part of sentence there (if the binary packages are being used).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-Kz3vJTGhETjuhALQ0HF:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/faq.rst, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz3uSaa6cTTxxQ0YWdG:-Kz4PaV0IH5pwsb3ihDT:b-5qsmxw) ([raw file](https://github.com/robotlocomotion/drake/blob/64c7bc18bcc96bee9f7cf6631ba4b9258274328f/doc/faq.rst#L120)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Change "correct compiler" to "supported compiler" and link to the supported platforms matrix? Also maybe you could add a note to below that matrix saying that the binary packages are built with Clang 4.0 on Ubuntu 16.04 and Apple Clang 9.0 on macOS 10.13 and then link somewhere in the last part of sentence there (if the binary packages are being used).
</blockquote></details>

Done. How does this look?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/faq.rst, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz3uSaa6cTTxxQ0YWdG:-Kz4RouTpSL13UT1V0tF:b-87j110) ([raw file](https://github.com/robotlocomotion/drake/blob/64c7bc18bcc96bee9f7cf6631ba4b9258274328f/doc/faq.rst#L120)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. How does this look?
</blockquote></details>

Good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-Kz4UPiJkn78KSlpxf-C:bz1t39v)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/developers.rst, line 100 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4hA3ZLtiDxLoCJ69N:-Kz4hA3ZLtiDxLoCJ69O:bqfb63k) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L100)):*
> ```reStructuredText
> ---------------
> 
> The binary releases of Drake are built with Clang 4.0 on Ubuntu 16.04 and Apple Clang 9.0 on macOS 10.13.
> ```

Per offline conversation change Clang 4.0 to GCC 5.4.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by sammy-tri** [comment]
first pass (mostly) complete

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/developers.rst, line 97 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4htHjVhRyWxzmehdH:-Kz4htHjVhRyWxzmehdI:bf0o8xt) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L97)):*
> ```reStructuredText
> .. _binary-packages:
> 
> Binary Packages
> ```

I feel like this section might be premature as there are no binary packages available at this time.

---

*[doc/faq.rst, line 110 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4j9o2TDgMWpnvyu2V:-Kz4j9o3NJp8-DJLj-q3:b75t746) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/faq.rst#L110)):*
> ```reStructuredText
> =======================================================================================================
> 
> **Symptom**: You have followed one of the options in the :ref:`installation_and_quick_start` instructions, and are writing a CMake project to use Drake.
> ```

I can't figure out what options this text refers to.

---

*[doc/faq.rst, line 120 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4jeBezI38JfRA8_pk:-Kz4jeBfCdtURwMmKYzF:b-h4hlrf) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/faq.rst#L120)):*
> ```reStructuredText
> **Solution**: This is most likely due to an incompatibilty between the compiler used to produce Drake (e.g. ``clang-4``) and the compiler that CMake has selected (e.g. ``gcc-4.9``). Specifically, ``gcc-4.9`` or before does not tend to handle the DualABI well when linking against ``clang``-compiled code [#dual_abi]_. You may be able to use other functions, because only functions that return an ABI-dependent class (e.g. ``std::string``) are tagged with the ABI that they are using (since they cannot be distinguished in the function signature).
> 
> The fix is to change the compiler CMake is using. One way to do this is to set the ``CC`` and ``CXX`` environment variables to use a supported compiler. For a list of supported compilers, see :ref:`supported-configurations`. If you are using pre-compiled binaries [#binary_install]_, please refer to the :ref:`binary-packages` for the compilers used.
> ```

I don't know where the reader would have gotten a pre-compiled binary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-Kz4jp1ZQjxZ6gvNijmG:btkj0by)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/developers.rst, line 97 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4htHjVhRyWxzmehdH:-Kz59HFZjF5-rY9-x3_p:b-9txvt7) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L97)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I feel like this section might be premature as there are no binary packages available at this time.
</blockquote></details>

We have them (see below), but they are not linked into the documentation.

@jamiesnape Should we include these links in the documentation? (So that way people don't have to dig in the issue? We can still say it's experimental at this point.)

---

*[doc/developers.rst, line 100 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4hA3ZLtiDxLoCJ69N:-Kz59sXz5ubWacF7cpWN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L100)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Per offline conversation change Clang 4.0 to GCC 5.4.
</blockquote></details>

Done.

---

*[doc/faq.rst, line 110 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4j9o2TDgMWpnvyu2V:-Kz5956M-aTA38dLG_dF:bn8ly4u) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/faq.rst#L110)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I can't figure out what options this text refers to.
</blockquote></details>

One of the three methods: Binary, Source, Docker.
Is there a rewording that would clarify this?

---

*[doc/faq.rst, line 120 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4jeBezI38JfRA8_pk:-Kz591uEjK87_bMnfMVn:b2hdoly) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/faq.rst#L120)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't know where the reader would have gotten a pre-compiled binary.
</blockquote></details>

These ones?
https://github.com/RobotLocomotion/drake/issues/1766#issuecomment-318955338
(At least, the ones tested in `drake-shambhala`...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/developers.rst, line 97 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4htHjVhRyWxzmehdH:-Kz5eHQTEN6AH38w8xcs:b-80tlqk) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L97)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

We have them (see below), but they are not linked into the documentation.

@jamiesnape Should we include these links in the documentation? (So that way people don't have to dig in the issue? We can still say it's experimental at this point.)
</blockquote></details>

Sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by jamiesnape** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/developers.rst, line 100 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4hA3ZLtiDxLoCJ69N:-Kz5egYPPAx2DQJpyiYx:bvdbqeu) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L100)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. The jobs on Jenkins have been updated also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/faq.rst, line 110 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4j9o2TDgMWpnvyu2V:-Kz5fJ5OJvUenpE7UKC9:b-wtdqjg) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/faq.rst#L110)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

One of the three methods: Binary, Source, Docker.
Is there a rewording that would clarify this?
</blockquote></details>

I don't think any of those documents describes running the install step and then building a project which links to drake libraries which isn't built inside drake, but I could have missed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/developers.rst, line 97 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4htHjVhRyWxzmehdH:-KzAz-atmtsKCGPS3inz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/developers.rst#L97)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Done.

---

*[doc/faq.rst, line 110 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-Kz4j9o2TDgMWpnvyu2V:-KzAyrwuG_kitdsbM8lF:b-mpkkhk) ([raw file](https://github.com/robotlocomotion/drake/blob/31a4eb3151eb0288f7255183bcf8cd1ab98ff07d/doc/faq.rst#L110)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think any of those documents describes running the install step and then building a project which links to drake libraries which isn't built inside drake, but I could have missed it.
</blockquote></details>

Done. Added text regarding experimental CMake projects, linked to the `drake_cmake_installed` examples in Shambhala.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-KzPjAGbLWola7fOrndp:bnfp4nl)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-KzPjF0dPvQkg9BlWDM-:b-s794vx)*

**Comment by sammy-tri** [comment]
-(status: curate commits before merging) Sorry about that!  I should have paid more attention to the contents  of the individual commits.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7491#-:-KzTjHZek8vAyAmEK_uD:b7d26qd)*

**Pull request merged**
