### PR TITLE
Added updated models of the IIWA 14 with estimated rotor inertia and gear ratio

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)

### CODE REVIEW

**Comment by AdityaBhat-TRI** [comment]
+@EricCousineau-TRI For review please!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AdityaBhat-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarEYZ1WXQTamvjJR2:-NUarEYZ1WXQTamvjJR3:b-4m0k20) (no related file):*
Can you confirm that this passes tests for Anzu? (alternatively, can you 

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUasOU99k_WPnF_Uw0W:-NUasOUAEROJVyeBsFYd:b63c8h7) (no related file):*
This is missing a consistency check among the models.

Can you update `iiwa14_variants_parsing_test.cc` to ensure we're consistent?

I believe you only need to update `CompareActuatorLimits` to check rotor inertias and gear ratios.

___
___
*[`manipulation/models/iiwa_description/README.md` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarylDEVRt67LMC4Jm:-NUarylE018jXUhtXTYa:b-sdxyz9) ([raw file](https://github.com/RobotLocomotion/drake/blob/56b3eaa58c61f567dceadd84cf08669804d26ec1/manipulation/models/iiwa_description/README.md#L83)):*
> ```Markdown
> 
> ### Rotor Inertia and Gear Ratio
> The rotor inertias and gear ratios are estimated based on the specifications of a similar robot, i.e. DLR LWR III.
> ```

nit Can you cite the paper that may have details on these drives / rotors?
___
*[`manipulation/models/iiwa_description/README.md` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarML-BIRp5guGxmYO:-NUarML-BIRp5guGxmYP:b-4cj4rr) ([raw file](https://github.com/RobotLocomotion/drake/blob/56b3eaa58c61f567dceadd84cf08669804d26ec1/manipulation/models/iiwa_description/README.md#L84)):*
> ```Markdown
> ### Rotor Inertia and Gear Ratio
> The rotor inertias and gear ratios are estimated based on the specifications of a similar robot, i.e. DLR LWR III.
> The motors and gears are assumed to be the RoboDrive ILM series and Harmonic Drive CSG series. These values are to 
> ```

nit Trailing whitespace.
___
*[`manipulation/models/iiwa_description/README.md` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarbpx3TBA07c7DY5b:-NUarbpx3TBA07c7DY5c:b-iti2wr) ([raw file](https://github.com/RobotLocomotion/drake/blob/56b3eaa58c61f567dceadd84cf08669804d26ec1/manipulation/models/iiwa_description/README.md#L90)):*
> ```Markdown
> |Axis data  | motor      | gear            | gear ratio | rotor inertia (kg m^2) |
> |-----------|-----------:|----------------:|-----------:|-----------------------:|
> |Axis 1 (A1)|ILM 85x23   |CSG-32-160-2A-GR |160         |0.0001321               |
> ```

nit Consider using scientific notation (here and in URDF files), e.g. `1.321e-4`, `4.54e-5`?

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-:-NUassQfAu2s_ArDr3iq:b-v6scke)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AdityaBhat-TRI and @EricCousineau-TRI)

**Comment by AdityaBhat-TRI** [comment]
*[`manipulation/models/iiwa_description/README.md` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarylDEVRt67LMC4Jm:-NUvt1QQAw-tDS_ZCg-4:b-99sm6k) ([raw file](https://github.com/RobotLocomotion/drake/blob/56b3eaa58c61f567dceadd84cf08669804d26ec1/manipulation/models/iiwa_description/README.md#L83)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you cite the paper that may have details on these drives / rotors?
</blockquote></details>

Cited the website

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: pending CI fixes
+@ggould-tri for platform, please!

> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-:-NUwwDYA9ol0kTcWL-k4:b-wther1)* status: 5 unresolved discussions, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI and @ggould-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUasOU99k_WPnF_Uw0W:-NUww6hd0WYIod5Fy6bH:b-ucfknh) (no related file):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

___
___
*[`manipulation/models/iiwa_description/README.md` line 97 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwul0u1m8GA_JguwSH:-NUwul0u1m8GA_JguwSI:b-mqb8x9) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/README.md#L97)):*
> ```Markdown
> |Axis 4 (A4)|ILM 70x18   |CSG-32-160-2A-GR |160         |1.321e-4               |
> |Axis 5 (A5)|ILM 70x18   |CSG-32-100-2A-GR |100         |1.321e-4               |
> |Axis 6 (A6)|ILM 50x08   |CSG-20-160-2A-GR |160         |1.321e-4               |
> ```

Did you mean to change this value? (before, was `4.54e-5`?)
___
*[`multibody/plant/test/joint_limits_test.cc` line 208 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwwRzy8_RZQjDHU8eJ:-NUwwRzy8_RZQjDHU8eK:b-kvgpt2) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/multibody/plant/test/joint_limits_test.cc#L208)):*
> ```cpp
> // builds.
> GTEST_TEST(JointLimitsTest, KukaArm) {
>   const double time_step = 2.0e-4;
> ```

This is timing out in debug builds, most likely due to 10x smaller timestep and increase in sim time.

Can you perhaps revert the timestep changes, and only rely on your increase in torque?
___
*[`multibody/plant/test/multibody_plant_reflected_inertia_test.cc` line 56 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwv8Qr9RWQHZND_OFY:-NUwv8Qs5fWrscUmYQ5D:b28b6pk) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/multibody/plant/test/multibody_plant_reflected_inertia_test.cc#L56)):*
> ```cpp
>     LoadIiwaWithGripper(&plant_);
>     LoadIiwaWithGripper(&plant_ri_);
>     ResetReflectedInertia(&plant_);
> ```

nit Need for this may be unclear to future readers - can you comment as to why? e.g.,

```
// These tests expect nominal model to have no reflected rotor inertia.
```
___
*[`multibody/plant/test/multibody_plant_reflected_inertia_test.cc` line 147 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwvvgoEuAJZeSrOBEC:-NUwvvgoEuAJZeSrOBED:bspubc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/multibody/plant/test/multibody_plant_reflected_inertia_test.cc#L147)):*
> ```cpp
>   }
> 
>   void ResetReflectedInertia(MultibodyPlant<double>* plant) {
> ```

BTW "Reset" may be ambiguous. Consider renaming to something like `SetReflectedInertiaToZero()`?

**Review by ggould-tri — COMMENTED** [review]
:lgtm: but (repetitive) nits on copypasta value that is either wrong or misdocumented.

> Reviewed 1 of 12 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-:-NUwz1rZ4PtsiSE2SVs-:b-yhfad1)* status: 28 unresolved discussions, missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf` line 409 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyEdh7Z-g6nzF9YjQ:-NUwyEdh7Z-g6nzF9YjR:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L409)):*
> ```
>       </axis>
>       <drake:gear_ratio>160.0</drake:gear_ratio>
>       <drake:rotor_inertia>0.0000454</drake:rotor_inertia>
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf` line 460 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyGHOBDES95aikjUu:-NUwyGHOBDES95aikjUv:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L460)):*
> ```
>       </axis>
>       <drake:gear_ratio>160.0</drake:gear_ratio>
>       <drake:rotor_inertia>0.0000454</drake:rotor_inertia>
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf` line 397 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyA6R627gUGRzkby9:-NUwyA6R627gUGRzkbyA:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf#L397)):*
> ```
>       </axis>
>       <drake:gear_ratio>160.0</drake:gear_ratio>
>       <drake:rotor_inertia>0.0000454</drake:rotor_inertia>
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf` line 464 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyC_08Lk1DWcp8tVy:-NUwyC_08Lk1DWcp8tVz:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf#L464)):*
> ```
>       </axis>
>       <drake:gear_ratio>160.0</drake:gear_ratio>
>       <drake:rotor_inertia>0.0000454</drake:rotor_inertia>
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf` line 448 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyMQ8BExR2wlm1NuB:-NUwyMQ8BExR2wlm1NuC:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf#L448)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyN7p--HWUo59ejiH:-NUwyN7p--HWUo59ejiI:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf#L461)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf` line 864 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyO8UDbjxJ3YX4iXO:-NUwyO8UDbjxJ3YX4iXP:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf#L864)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf` line 877 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyOx59xFaBMugbUJ0:-NUwyOx59xFaBMugbUJ1:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf#L877)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14.xacro` line 348 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyQ_a-9F4eP_DWQnb:-NUwyQ_a-9F4eP_DWQnc:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14.xacro#L348)):*
> ```XML
>       <dynamics damping="${joint_damping}"/>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia>0.0000454</drake:rotor_inertia>
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14.xacro` line 404 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyRBEBff1SYErKDVR:-NUwyRBEBff1SYErKDVS:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14.xacro#L404)):*
> ```XML
>       <dynamics damping="${joint_damping}"/>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia>0.0000454</drake:rotor_inertia>
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf` line 430 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyTAv36LzY6rZ7a3Y:-NUwyTAv36LzY6rZ7a3Z:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf#L430)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf` line 443 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyTkU30Sjiye9RC9n:-NUwyTkU30Sjiye9RC9o:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf#L443)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf` line 443 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyUkP07CVdqZKINOs:-NUwyUkP07CVdqZKINOt:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf#L443)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf` line 456 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyWE_5c1GLaa7OEX_:-NUwyWE_5c1GLaa7OEXa:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf#L456)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf` line 498 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyXNi8D9EcDWSH7pB:-NUwyXNi8D9EcDWSH7pC:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf#L498)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf` line 511 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyXn8CjvR3f8wEYcs:-NUwyXn8CjvR3f8wEYct:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf#L511)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf` line 529 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyYsCDZQUxSnCyfRE:-NUwyYsCDZQUxSnCyfRF:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf#L529)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf` line 542 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyZZy-Q7XEoF6eS6N:-NUwyZZy-Q7XEoF6eS6O:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf#L542)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf` line 760 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwy_eo-jbpdSrCyza0:-NUwy_eo-jbpdSrCyza1:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf#L760)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf` line 773 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwya25802depd1hFum:-NUwya25802depd1hFun:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf#L773)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf` line 592 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwybFy8YQX7ac_xCoQ:-NUwybFy8YQX7ac_xCoR:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf#L592)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf` line 605 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwybyr2Ewf9G7kdw28:-NUwybyr2Ewf9G7kdw29:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf#L605)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.
___
*[`manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf` line 516 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwyedY5Isg5DoEH_cR:-NUwyedY5Isg5DoEH_cS:b-r92zg6) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf#L516)):*
> ```XML
>       <mechanicalReduction>1</mechanicalReduction>
>       <drake:gear_ratio value="160.0" />
>       <drake:rotor_inertia value="0.0000454" />
> ```

minor:  Value does not match README.

**Comment by AdityaBhat-TRI** [comment]
*[`manipulation/models/iiwa_description/README.md` line 97 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwul0u1m8GA_JguwSH:-NUx6QKdCXoMk-e6xmob:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/manipulation/models/iiwa_description/README.md#L97)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Did you mean to change this value? (before, was `4.54e-5`?)
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AdityaBhat-TRI)

**Comment by AdityaBhat-TRI** [comment]
*[`multibody/plant/test/joint_limits_test.cc` line 208 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwwRzy8_RZQjDHU8eJ:-NUxAiyR0K1BHyf7jxXF:bqln2ip) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/multibody/plant/test/joint_limits_test.cc#L208)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This is timing out in debug builds, most likely due to 10x smaller timestep and increase in sim time.

Can you perhaps revert the timestep changes, and only rely on your increase in torque?
</blockquote></details>

I couldn't get the velocity to converge with increasing torque values alone. Had to modify the time-step and the sim time to get the robot velocity to be close to 0. The alternative, i.e increase the velocity tolerance may not be ideal either.

**Comment by AdityaBhat-TRI** [comment]
*[`multibody/plant/test/multibody_plant_reflected_inertia_test.cc` line 56 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwv8Qr9RWQHZND_OFY:-NUxCsKiBasszOfihWR8:bpcitlp) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/multibody/plant/test/multibody_plant_reflected_inertia_test.cc#L56)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Need for this may be unclear to future readers - can you comment as to why? e.g.,

```
// These tests expect nominal model to have no reflected rotor inertia.
```
</blockquote></details>

Updated at the top of the class

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 3 unresolved discussions, missing label for release notes (waiting on @AdityaBhat-TRI)

**Comment by AdityaBhat-TRI** [comment]
*[`multibody/plant/test/joint_limits_test.cc` line 208 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUwwRzy8_RZQjDHU8eJ:-NV04P0f3RynF_X3rM5j:b-905lkl) ([raw file](https://github.com/RobotLocomotion/drake/blob/20a762430d94744a0e0d9060325f92cd6bfabdac/multibody/plant/test/joint_limits_test.cc#L208)):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

I couldn't get the velocity to converge with increasing torque values alone. Had to modify the time-step and the sim time to get the robot velocity to be close to 0. The alternative, i.e increase the velocity tolerance may not be ideal either.
</blockquote></details>

After discussing with the dynamics team, we have decided to reset the reflected inertia to 0 for the iiwa for this test as it takes too long for the unit test to run and hit the tolerance values.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 3 unresolved discussions, missing label for release notes

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 4 unresolved discussions, missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`multibody/plant/test/joint_limits_test.cc` line 218 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NV10dft9e4k-8_iVfjv:-NV10dft9e4k-8_iVfjw:bntziaa) ([raw file](https://github.com/RobotLocomotion/drake/blob/603c02c794f5c5f069c6b5222e6b654d5dfa4d50/multibody/plant/test/joint_limits_test.cc#L218)):*
> ```cpp
> // builds.
> // This test sets the value of reflected inertia to zero (even though model has
> // non zero reflected inertia) to avoid issues relating to very small step sizes
> ```

minor:  Do these issues have an issue number, and if so can this be a TODO to that issue number?



_Code quote:_
```cpp
// non zero reflected inertia) to avoid issues relating to very small step sizes
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 2 unresolved discussions, missing label for release notes (waiting on @AdityaBhat-TRI)

**Comment by AdityaBhat-TRI** [comment]
*[`multibody/plant/test/joint_limits_test.cc` line 218 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NV10dft9e4k-8_iVfjv:-NV1A65z2c3iKBTR16HJ:b-3qm3sx) ([raw file](https://github.com/RobotLocomotion/drake/blob/603c02c794f5c5f069c6b5222e6b654d5dfa4d50/multibody/plant/test/joint_limits_test.cc#L218)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Do these issues have an issue number, and if so can this be a TODO to that issue number?
</blockquote></details>

Sorry, the comment was misleading. I updated the comment: there is no issue per se. As it takes a long time to run this test if reflected inertia gets added, we decided to reset reflected inertia to 0 for this test (as it's not relevant to the joint limit test).

**Comment by AdityaBhat-TRI** [comment]
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you confirm that this passes tests for Anzu? (alternatively, can you 
</blockquote></details>

Couple of tests failed in intuitive: https://robotics-enabling-jenkins.awsinternal.tri.global/job/Integrations/job/Anzu-master-Drake-PR/204/#showFailuresLink

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 1 unresolved discussion, missing label for release notes (waiting on @AdityaBhat-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: 1 unresolved discussion, missing label for release notes (waiting on @AdityaBhat-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarEYZ1WXQTamvjJR2:-NV1o4bWEhy0NZ8QucuT:b-ta7d6l) (no related file):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

Couple of tests failed in intuitive: https://robotics-enabling-jenkins.awsinternal.tri.global/job/Integrations/job/Anzu-master-Drake-PR/204/#showFailuresLink
</blockquote></details>

Working: Will draft up PR as most failures are in code that I'm futzing with.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19344)* status: missing label for release notes (waiting on @AdityaBhat-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19344#-NUarEYZ1WXQTamvjJR2:-NV1vew9Djcgp8Z-X0DX:bqgc0w9) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will draft up PR as most failures are in code that I'm futzing with.
</blockquote></details>

Done. Just minor tweaks needed.

One of the Anzu control tests has lower precision, but not sure if that's anything to be worried about.

___

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri I forget - since models aren't part of our stability guideline, do we still add in release notes?
(I assume so, just for user visibility, hence current release notes tag)

**Comment by jwnimmer-tri** [comment]
Yes.  Changes to installed models should appear in the release notes, so "fix" is good.

**Pull request merged**
