### PR TITLE
Mow over all XML files with xmllint

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #8271

Diff generated using:
```sh
find . \
    -name '*.config' \
    -o -name '*.rsdf' \
    -o -name '*.sdf' \
    -o -name '*.urdf' \
    -o -name '*.xacro' \
    -o -name '*.xml' \
    -o -name '*.world' \
    | xargs -t -n 1 bash -c 'xmllint --format ${1} -o ${1}' _
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13768)

### CODE REVIEW

**Comment by jamiesnape** [comment]
FWIW there are some (all?) `*.config` files that are XML (as are `*.dae`, `*.svg`, `*.vtm` `*.vtp` files, though doubt you would lint those).

**Comment by EricCousineau-TRI** [comment]
Added in the `*.config` files - thanks! (And yeah, don't care about SVG's etc. unless we ever get to a point of hand-crafting them)

**Comment by jamiesnape** [comment]
>  unless we ever get to a point of hand-crafting them

I hope that never happens.

One more: `./examples/atlas/sdf/drc_practice_task_2.world` (I grepped `xml version`)

**Comment by EricCousineau-TRI** [comment]
Oh ya, forgot that one! Sorry, I had seen your list in the linked issue, and just, uh, hadn't used it - sorry!

**Comment by jwnimmer-tri** [comment]
I'm okay to go solo.

**Comment by EricCousineau-TRI** [comment]
Pushing latest then merging.

**Pull request merged**
