### PR TITLE
[geometry] Deprecate RenderEngineGl's default_label option

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See #19906 for discussion.

+@SeanCurtis-TRI for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With two suggestions.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-:-Naojusy4Q6O_yY3yEgg:brcl3dq)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 717 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-NaohrcSAJkCwX2fqKFQ:-NaohrcSAJkCwX2fqKFR:brfz7bb) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c4a0af87a4fa11157c5cac9e4b0a32eca6ddc26/geometry/render_gl/internal_render_engine_gl.cc#L717)):*
> ```cpp
>       texture_library_(make_shared<TextureLibrary>()),
>       parameters_(CleanupLights(std::move(params))) {
>   if (params.default_label != RenderLabel::kDontCare) {
> ```

Perhaps it would be better if `default_label` became `optional`. That way, if someone sets it *at all*, even to `kDontCare`, we can give them the warning?
___
*[`geometry/render_gl/test/render_engine_gl_params_test.cc` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-Naoj3FJBSeYoZWGUAjp:-Naoj3FJBSeYoZWGUAjq:b-tajhsa) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c4a0af87a4fa11157c5cac9e4b0a32eca6ddc26/geometry/render_gl/test/render_engine_gl_params_test.cc#L15)):*
> ```cpp
>   const Params original{
>       .default_diffuse = Rgba{1.0, 0.5, 0.25},
>       .default_clear_color = Rgba{0.25, 0.5, 1.0},
> ```

nit: We should add at least one default light. Two would be best.

```c++
GTEST_TEST(RenderEngineGlParams, Serialization) {
  using Params = RenderEngineGlParams;
  const Params original{
      .default_diffuse = Rgba{1.0, 0.5, 0.25},
      .default_clear_color = Rgba{0.25, 0.5, 1.0},
      .lights = {{.type="point"}, {.type="spot"}}
  };
  const std::string yaml = yaml::SaveYamlString<Params>(original);
  const Params dut = yaml::LoadYamlString<Params>(yaml);
  EXPECT_EQ(dut.default_diffuse, original.default_diffuse);
  EXPECT_EQ(dut.default_clear_color, original.default_clear_color);
  ASSERT_EQ(dut.lights.size(), 2);
  EXPECT_EQ(dut.lights[0].type, "point");
  EXPECT_EQ(dut.lights[1].type, "spot");
}
```
___
*[`bindings/pydrake/geometry/geometry_py_render.cc` line 378 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-Naok04_4WbxOt1eyTIE:-Naok04_4WbxOt1eyTIF:bt9nrvk) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c4a0af87a4fa11157c5cac9e4b0a32eca6ddc26/bindings/pydrake/geometry/geometry_py_render.cc#L378)):*
> ```cpp
>     cls.def_property("default_label",
>         WrapDeprecated(cls_doc.default_label.doc,
>             [](const Class& self) { return self.default_label; }),
> ```

nit If you buy the `optional<RenderLabel>` argument, I believe this should become a `value_or` on `kUnspecified` to maintain the semantics.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 717 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-NaohrcSAJkCwX2fqKFQ:-NaoplN60oLiL8QZw9p1:b-e6bg30) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c4a0af87a4fa11157c5cac9e4b0a32eca6ddc26/geometry/render_gl/internal_render_engine_gl.cc#L717)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Perhaps it would be better if `default_label` became `optional`. That way, if someone sets it *at all*, even to `kDontCare`, we can give them the warning?
</blockquote></details>

Wrapping `RenderEngineGlParams::default_label` in `optional<>` would be a breaking change for any users who are _accessing_ the value (in C++, or Python).

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912)* status: needs at least two assigned reviewers

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 717 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-NaohrcSAJkCwX2fqKFQ:-NaotFOM55YofrSiGz21:bcb72nj) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c4a0af87a4fa11157c5cac9e4b0a32eca6ddc26/geometry/render_gl/internal_render_engine_gl.cc#L717)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Wrapping `RenderEngineGlParams::default_label` in `optional<>` would be a breaking change for any users who are _accessing_ the value (in C++, or Python).
</blockquote></details>

Silly me. I felt that fixing it on the python side was easy (as noted below). But I hadn't thought about the C++ side. Comment retracted. There really is no solution for anyone that was configuring this value to `kDontCare`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912)* status: needs at least two assigned reviewers

___
*[`geometry/render_gl/internal_render_engine_gl.cc` line 717 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-NaohrcSAJkCwX2fqKFQ:-Naqcgue3UW7bsTecgaY:bteiz8z) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c4a0af87a4fa11157c5cac9e4b0a32eca6ddc26/geometry/render_gl/internal_render_engine_gl.cc#L717)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Silly me. I felt that fixing it on the python side was easy (as noted below). But I hadn't thought about the C++ side. Comment retracted. There really is no solution for anyone that was configuring this value to `kDontCare`.
</blockquote></details>

You're right, the Python adjustment would have been easy.  It's the C++ that's the real break.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-:-NarU5r45Zaew5-QsYmb:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Why `release notes: feature` here?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19912#-:-NarUCZV9ovFTDIxTEUx:b-oz1vg)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Comment by jwnimmer-tri** [comment]
"... the params are compatible now with YAML serialization."

**Pull request merged**
