### PR TITLE
[manipulation] Expose utime as an output from received iiwa status

### PR DESCRIPTION
**Pull request by aykut-tri**
- Adds utime as an output port to the iiwa status receiver
- Adds relevant python bindings

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)

### CODE REVIEW

**Comment by aykut-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Review by aykut-tri — COMMENTED** [review]
+@sammy-tri for feature review please, thanks!

cc: @JoseBarreiros-TRI and @ggould-tri

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761#-:-NA6OQyeETIQzZxfWiWb:bft5n9z)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @aykut-tri and @sammy-tri)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAAAaYR3LxEZFZbJtad:-NAAAaYS4shFgVzE1_Nx:b8sgakf) ([raw file](https://github.com/robotlocomotion/drake/blob/907dcffb5e32f227b319000354222279d3ace3ba/manipulation/kuka_iiwa/iiwa_status_receiver.h#L31)):*
> ```objc
> /// - lcmt_iiwa_status
> /// output_ports:
> /// - utime
> ```

The purpose of this class is to transform lcm message data into Drake-conventional signals.

Drake's output ports are floating point (real numbers), and time in Drake (e.g., context.get_time()) is a float-point number of seconds.

Why is this output port using the weird `utime` integer convention from the message encoding, instead of a floating-point number of seconds?  (The number of microseconds since the epoch fits into a 64-bit double mantissa without loss of precision.)
___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAAAziB-UdCG87o6kp9:-NAAAziB-UdCG87o6kpA:b-48xd0i) ([raw file](https://github.com/robotlocomotion/drake/blob/907dcffb5e32f227b319000354222279d3ace3ba/manipulation/kuka_iiwa/iiwa_status_receiver.h#L31)):*
> ```objc
> /// - lcmt_iiwa_status
> /// output_ports:
> /// - utime
> ```

The meaning of the port name "time" (or "utime") is unclear.

The concept of "time" here, I believe, is `time_measured()` i.e. the hardware clock time at which the `position_measured()` etc were measured at, which is not necessarily related to the time in the Context?   Is that correct?

Even after improving the port name, the overview prose prior to this block diagram should explain what this port means.

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sammy-tri)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAAAaYR3LxEZFZbJtad:-NABH9vKC3AiKIZNh-fE:b-x9x5v6) ([raw file](https://github.com/robotlocomotion/drake/blob/907dcffb5e32f227b319000354222279d3ace3ba/manipulation/kuka_iiwa/iiwa_status_receiver.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The purpose of this class is to transform lcm message data into Drake-conventional signals.

Drake's output ports are floating point (real numbers), and time in Drake (e.g., context.get_time()) is a float-point number of seconds.

Why is this output port using the weird `utime` integer convention from the message encoding, instead of a floating-point number of seconds?  (The number of microseconds since the epoch fits into a 64-bit double mantissa without loss of precision.)
</blockquote></details>

That's a good point, thank you! Now, the universal time in microseconds is cast into a double and converted into seconds.
___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAAAziB-UdCG87o6kp9:-NABHTBpBImkv5Wpq1YM:bdcr4c8) ([raw file](https://github.com/robotlocomotion/drake/blob/907dcffb5e32f227b319000354222279d3ace3ba/manipulation/kuka_iiwa/iiwa_status_receiver.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The meaning of the port name "time" (or "utime") is unclear.

The concept of "time" here, I believe, is `time_measured()` i.e. the hardware clock time at which the `position_measured()` etc were measured at, which is not necessarily related to the time in the Context?   Is that correct?

Even after improving the port name, the overview prose prior to this block diagram should explain what this port means.
</blockquote></details>

That's correct. This is the timestamp from the hardware, and hence I believe, unrelated to the time in the context.

The naming and the overview have been updated as you recommended. Thank you for these helpful comments!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:   +@seancurtis-tri for platform review

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761#-:-NABILnnBDWQQVhG-WTS:b-nzr5kj)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @aykut-tri and @SeanCurtis-TRI)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.cc` line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NABMn8gEJJ-Bsv6B13a:-NABMn8gEJJ-Bsv6B13b:b-5s70ic) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7b7c989a46e33eaae2082a28b03d78e263fb1/manipulation/kuka_iiwa/iiwa_status_receiver.cc#L81)):*
> ```cpp
>         Eigen::Map<const Eigen::VectorXd>(status_field.data(), num_joints_);
>   }
> }
> ```

nit It looks like clang-format reflowed some whitespace in this otherwise-unchagned function?  (Around L65 for the function signature, and here at L79 for the Eigen::Map call.) Please undo these unrelated whitespace changes.

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@seancurtis-tri +@rpoyner-tri for today's on-call platform reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761#-:-NABPAk736QY42ZcBJ3e:b5kk7hn)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @aykut-tri and @rpoyner-tri)

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri, @rpoyner-tri, and @sammy-tri)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.cc` line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NABMn8gEJJ-Bsv6B13a:-NABQ8t581sinfXPTxKA:b28pmkh) ([raw file](https://github.com/robotlocomotion/drake/blob/9bd7b7c989a46e33eaae2082a28b03d78e263fb1/manipulation/kuka_iiwa/iiwa_status_receiver.cc#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It looks like clang-format reflowed some whitespace in this otherwise-unchagned function?  (Around L65 for the function signature, and here at L79 for the Eigen::Map call.) Please undo these unrelated whitespace changes.
</blockquote></details>

Good catch, fixed, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
This is a new feature, so we want +(release notes: feature) not -(release notes: none).

**Review by aykut-tri — COMMENTED** [review]
Oh I see, does that require adding anything else on my end?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761#-:-NABSMeA-haKUqjFjHub:b-qg0scc)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
No, my comment already repaired the PR labels via the magic keywords.

**Review by aykut-tri — COMMENTED** [review]
Awesome, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761#-:-NABVGj478eITmlIDk9k:b556ppi)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: except for me invoking Gould's Law, below.

> Reviewed 4 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761#-:-NAFTXPp40Up5F-uQQSI:bz6f0mq)* status: 1 unresolved discussion (waiting on @aykut-tri)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 23 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAFRAQm-VDrSU_ZV1uy:-NAFRAQm-VDrSU_ZV1uz:b-mn2su0) ([raw file](https://github.com/robotlocomotion/drake/blob/5091266209155315f17d4675484a32ddba2ab0a1/manipulation/kuka_iiwa/iiwa_status_receiver.h#L23)):*
> ```objc
> ///
> /// This system has many vector-valued output ports, each of which has exactly
> /// num_joints elements except for a one-dimensional measured time output in
> ```

somehow, I was able to misread this the first time through. I got something like "output ports have num_joints elements *and* a one-dimensional time output (vector size num_joints + 1)" instead of "most output ports have num_joints-sized vector outputs, except for `time_measured`, which has a one-dimensional time in seconds".

I'd like this to be a little clearer, but I am open to wording that you think may be better than the above.

Possibly related, does the time port emit zeros until input, like the other ports, or does it emit timestamps before that? I can see in the code that it does, but let's make sure whatever doc changes retain the sense that some ports are vector-valued, one is time-valued, but all are 0 until an input happens.

OK, since I've blabbed this much, here is a suggested text:

```
This system has many output ports, most of which emit vector values of exactly
`num_joints` elements. The exception is `time_measured`, which has a
one-dimensional measured time output in seconds. All ports will output zeros
until an input message is received.
```



_Code quote:_
```objc
except for a one-dimensional measured time output
```

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: 1 unresolved discussion (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: 1 unresolved discussion (waiting on @jwnimmer-tri, @rpoyner-tri, and @sammy-tri)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 23 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAFRAQm-VDrSU_ZV1uy:-NAFsyie7IHr4OHb_bTM:b4rl2fs) ([raw file](https://github.com/robotlocomotion/drake/blob/5091266209155315f17d4675484a32ddba2ab0a1/manipulation/kuka_iiwa/iiwa_status_receiver.h#L23)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

somehow, I was able to misread this the first time through. I got something like "output ports have num_joints elements *and* a one-dimensional time output (vector size num_joints + 1)" instead of "most output ports have num_joints-sized vector outputs, except for `time_measured`, which has a one-dimensional time in seconds".

I'd like this to be a little clearer, but I am open to wording that you think may be better than the above.

Possibly related, does the time port emit zeros until input, like the other ports, or does it emit timestamps before that? I can see in the code that it does, but let's make sure whatever doc changes retain the sense that some ports are vector-valued, one is time-valued, but all are 0 until an input happens.

OK, since I've blabbed this much, here is a suggested text:

```
This system has many output ports, most of which emit vector values of exactly
`num_joints` elements. The exception is `time_measured`, which has a
one-dimensional measured time output in seconds. All ports will output zeros
until an input message is received.
```
</blockquote></details>

Good to learn about Gould's law, makes sense, and thanks for providing a suggested text! I've just added some more details about `time_measured` being the timestamp from the hardware and the unit conversion.

We already have [a test case checking the time outputs a 1D zero vector until input](https://github.com/aykut-tri/drake/blob/1206e92ea7861aedc2ca0a528aa70282abbb6f58/manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc#L50).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17761)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @aykut-tri)

___
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 23 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAFRAQm-VDrSU_ZV1uy:-NAG47vh4oP-DohIAiBm:bcir1nk) ([raw file](https://github.com/robotlocomotion/drake/blob/5091266209155315f17d4675484a32ddba2ab0a1/manipulation/kuka_iiwa/iiwa_status_receiver.h#L23)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Good to learn about Gould's law, makes sense, and thanks for providing a suggested text! I've just added some more details about `time_measured` being the timestamp from the hardware and the unit conversion.

We already have [a test case checking the time outputs a 1D zero vector until input](https://github.com/aykut-tri/drake/blob/1206e92ea7861aedc2ca0a528aa70282abbb6f58/manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc#L50).
</blockquote></details>

In case you haven't heard the story, "Gould's law" is from our own @ggould-tri . Something like "If your reviewer is confused by something, it is therefore objectively confusing." A wise, wise man he is.

**Comment by aykut-tri** [comment]
*[`manipulation/kuka_iiwa/iiwa_status_receiver.h` line 23 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17761#-NAFRAQm-VDrSU_ZV1uy:-NAKE_yrBN7IwTOvDRo3:b-riuimp) ([raw file](https://github.com/robotlocomotion/drake/blob/5091266209155315f17d4675484a32ddba2ab0a1/manipulation/kuka_iiwa/iiwa_status_receiver.h#L23)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

In case you haven't heard the story, "Gould's law" is from our own @ggould-tri . Something like "If your reviewer is confused by something, it is therefore objectively confusing." A wise, wise man he is.
</blockquote></details>

I haven't but agree 100%, thanks for sharing!

**Comment by ggould-tri** [comment]
I usually phrase it as just, "if it confuses, it is confusing" :-)

**Pull request merged**
