### PR TITLE
Remove support for macOS Mojave 10.14

### LINKED ISSUE #14328: Withdrawing macOS Mojave (10.14) support
We are planning on dropping support for macOS Mojave (10.14) support in future releases.

Our usual policy is to keep N, N-1 versions alive for macOS -- so the most recent Apple release, and the one immediately prior.

With Big Sur on the way (#13648) it's time to drop Mojave to make room for it.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #14328.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14352)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@rpoyner-tri for platform review per schedule, please +(priority: high).

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14352#-:-MMMczYt2ZowIM1Dp1N8:b-uyxtfr)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jamiesnape and @rpoyner-tri)

___
*[doc/developers.rst, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14352#-MMMdUrTAD05earqxR9z:-MMMdUrTAD05earqxRA-:b-k5qw92) ([raw file](https://github.com/robotlocomotion/drake/blob/966aa60ca59809c1adcca963a7efcd76875c6d06/doc/developers.rst#L126)):*
> ```reStructuredText
> 
> The binary releases of Drake are built with GCC 7.5 on Ubuntu 18.04 (Bionic),
> GCC 9.3 on Ubuntu 20.04 (Focal), and Apple LLVM 12.0.0 on macOS Catalina
> ```

nit Should this say "12.2.0" or something now?  The above table says "12.2".

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14352)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/developers.rst, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14352#-MMMdUrTAD05earqxR9z:-MMMdmkA0Y-rFSKyRG33:boddm4c) ([raw file](https://github.com/robotlocomotion/drake/blob/966aa60ca59809c1adcca963a7efcd76875c6d06/doc/developers.rst#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Should this say "12.2.0" or something now?  The above table says "12.2".
</blockquote></details>

No, only the major compiler version tracks the Xcode version (which was a coincidence originally). The changes to Xcode 12.2 was support for Big Sur with practically the same compiler modulo build number.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14352#-:-MMMw7YwAWHaMZ85YZAR:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14352)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14352#-MMMxBhS250tbNi2dYUQ:-MMMxBhTChrOIuovdJJ6:b-cdot5m) (no related file):*
Not waiting for the catalina build to finish; I assume the hazards from this PR would have been front-loaded.

---

**Pull request merged**
