### PR TITLE
Bump our cpplint sha

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Update `google_styleguide` to latest master (mwoehlke's fork had a fix for false-positive warnings on code that we've since deleted or something).
- Fix all of the missing `#include` portability problems that newer cpplint finds.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4636)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review, please +(priority: low).

---

Review status: 0 of 104 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4636#-:-K_7gK8ch5AzgaLssUwq:b4kkl9k)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 104 of 104 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4636#-:-K_A0OtB0kjWTpnQeFJH:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 102 of 104 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4636#-:-K_AA7yxPgQzBdOz4jis:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 104 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4636)*

**Pull request merged**
