### PR TITLE
[doc] Add VS Code and Emacs integration tips

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18175.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for emacs review and overall feature review, please.
+@ggould-tri for vscode review and overall platform review, please.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[`doc/_pages/vscode.md` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18681#-NMqUZju50AiDGnsXjcD:-NMqUZju50AiDGnsXjcE:b-e67y5q) ([raw file](https://github.com/RobotLocomotion/drake/blob/3e899fa8564501f1e63ade02ac27caae7e2919b9/doc/_pages/vscode.md#L5)):*
> ```Markdown
> ---
> 
> This guide describes how to edit the Drake codebase using VS Code.
> ```

BTW, does VS Code requires plugin for bazel?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

___
*[`doc/_pages/vscode.md` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18681#-NMqUZju50AiDGnsXjcD:-NN2BYrV4RJreUCSc0oJ:bz2esca) ([raw file](https://github.com/RobotLocomotion/drake/blob/3e899fa8564501f1e63ade02ac27caae7e2919b9/doc/_pages/vscode.md#L5)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, does VS Code requires plugin for bazel?
</blockquote></details>

I was able to edit C++ files without it (still running `bazel test` on the command line).

If there are tips from everyday VS Code users, we'd welcome pull requests and suggestions to add them here.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681#-:-NN2N-Q_7tgJ1rwUfwP4:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_pages/emacs.md` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18681#-NN2KaqNAimNHaA61Try:-NN2KaqNAimNHaA61Trz:b-8e72c4) ([raw file](https://github.com/RobotLocomotion/drake/blob/3e899fa8564501f1e63ade02ac27caae7e2919b9/doc/_pages/emacs.md#L29)):*
> ```Markdown
> Use ``(require 'clang-format)`` to enable the ``M-x clang-format-...`` family of
> functions. Also check that the customize variable ``clang-format-executable`` is
> set to Drake's preferred value ``clang-format-12``.
> ```

minor:  I'm a bit surprised that `'google-c-style` isn't here, given that it's provided by our styleguide repo.  Is this a deliberate choice because it's complicated?
___
*[`doc/_pages/vscode.md` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18681#-NN2L0Eu8HJ1h2hXbDAl:-NN2L0Eu8HJ1h2hXbDAm:b-gjf4e) ([raw file](https://github.com/RobotLocomotion/drake/blob/3e899fa8564501f1e63ade02ac27caae7e2919b9/doc/_pages/vscode.md#L9)):*
> ```Markdown
> If you have tips that would help out other developers, drop us a line and we
> can add them here!
> ```

Suggest some text about the header location issue, since it is pretty much the first thing anyone trying vscode will see.



_Code snippet:_
```Markdown
Because VS Code wants to locate all included headers, but bazel does
not provide those headers in a single consistent location, it is
common to get "red squiggles" for included headers, particularly for
externals like LCM.  So far this does not seem to be avoidable; the
`"C_Cpp.errorSquiggles": "enabledIfIncludesResolve"` setting does not
work to solve this problem.
```

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681#-:-NN2XQS06hOJId2QmFVE:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18681)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
