### PR TITLE
Add more dev versions of libraries to install_prereqs

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed for actually using libdrake.so, e.g., by MATLAB in #7293.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7333)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
FYI the fragment PR about to be reborn of #7330 is going to add `coinor-libclp-dev` to Xenial prereqs.  Probably worth getting that onto master before new AMIs happen.

/CC @soonho-tri

**Comment by jamiesnape** [comment]
I have no objections to adding that to this PR.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by soonho-tri** [comment]
👍 for adding `coinor-libclp-dev`!

**Comment by jamiesnape** [comment]
FYI @BetsyMcPhail.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7333#-:-KxKOvl7KBHd3O_izcUS:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for platform review.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: platform (with reliance on feature reviewer for full functional correctness).

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7333#-:-KxKW6C15vI9V3L16J3L:bvzzihu)*

**Pull request merged**
