### PR TITLE
Fix range-loop-construct warnings

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #13102.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13357)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Oh, actually I hadn't realized that clang had gotten scoped in for focal.  I actually think we should explicitly not support new-clang on focal, and not try to adapt our code for it, specifically for the reason Sean alludes to -- developer have no easy local ability to reproduce the errors.  If macOS evolves down the road to use (a fork of) clang 10, then we can re-evaluate.

**Comment by jwnimmer-tri** [comment]
(We can still land this PR since it's already a sunk cost, but we should not pursue additional work to placate clang 10.)

**Comment by jamiesnape** [comment]
This was actually in Clang 9 as part of `-Wrange-loop-analysis` (though not necessarily in `-Wall`) and macOS will be forking off of LLVM master soon (if it has not already, I have not checked yet).

With respect to drake, there seems to have been an author split on this (even with the same types at times), so all you really had was inconsistency.

Also you are probably going to lose some of the sanitizer builds unless we jump though hoops to make them all consistently work with GCC on CI again, and dealing with this is a million times easier.

**Comment by jwnimmer-tri** [comment]
Undoubtedly we will want newer clang support eventually, and can still accept this PR as improving uniformity and already sunk cost.  However, my posture remains that the only near-term value focal-clang support brings is to anticipate macOS support as its tools are upgraded.  In the case of this new warning, though, we could specifically turn it off on macOS even though it's in Wall now.  I would like to spend our build component budget on higher priority features, and place focal-clang as future work down the road.

**Comment by jamiesnape** [comment]
>  BTW Is there a link for the change in clang 10 so I can educate myself more?

Not that I am immediately aware of. I will look into that.

> It seems the principle in play here is that range iteration must always be via reference. 

To an extent. There are also times when const/non-const and signed/unsigned disagreement will cause an unnecessary copy.

> Or do we risk bleeding new ones in?

Yes, this is true for all the recent strings of PR's. I imagine we will get plenty of regressions with respect to `std::move` too. Fortunately, the diagnostics are good and the fixes are trivial, so I am not worried about that.

> I would like to spend our build component budget on higher priority features, and place focal-clang as future work down the road.

I think this was the one difference and second opinion on a couple of errors was instructive. But, obviously, I will stop as I am hired help.

**Comment by jamiesnape** [comment]
These are some examples:

```
geometry/proximity_engine.cc:582:21: error: loop variable 'num' has type
    'const int &' but is initialized with type 'const unsigned char' resulting
    in a copy [-Werror,-Wrange-loop-construct]
geometry/proximity_engine.cc:582:10: note: use non-reference type 'int' to keep
    the copy or type 'const unsigned char &' to prevent copying
```

```
geometry/proximity/test/make_sphere_field_test.cc:45:32: error: loop variable
    'v' of type 'const drake::geometry::VolumeVertexIndex' (aka
    'const TypeSafeIndex<class VolumeVertexTag>') creates a copy from type
    'const drake::geometry::VolumeVertexIndex' [-Werror,-Wrange-loop-construct]
geometry/proximity/test/make_sphere_field_test.cc:45:8: note: use reference
    type 'const drake::geometry::VolumeVertexIndex &' (aka
    'const TypeSafeIndex<class VolumeVertexTag> &') to prevent copying
```

```
solvers/test/mathematical_program_test.cc:2438:44: error: loop variable 'p' has
    type 'const pair<Variable::Id, drake::symbolic::Variable> &' (aka
    'const pair<unsigned long, drake::symbolic::Variable> &') but is
    initialized with type
    'const std::pair<const unsigned long, drake::symbolic::Variable>' resulting
    in a copy [-Werror,-Wrange-loop-construct]
solvers/test/mathematical_program_test.cc:2438:8: note: use non-reference type
    'pair<Variable::Id, drake::symbolic::Variable>' (aka
    'pair<unsigned long, drake::symbolic::Variable>') to keep the copy or
    type 'const std::pair<const unsigned long, drake::symbolic::Variable> &' to
    prevent copying
```

**Comment by sherm1** [comment]
I like this change. Seems like a good habit to get into.

**Comment by jamiesnape** [comment]
I guess we may as well get this merged regardless of future overall Clang support (though I forgot to mention that we need LLVM support of some form for Python documentation generation and future automated Python binding generation).

+@jwnimmer-tri for feature review and +@sherm1 for platform review. @SeanCurtis-TRI is more than welcome to review too.

As I said, I am literally following the compiler in all cases here (though I do not see much, if anything, that I disagree with, to be honest). The compiler is prescriptive enough that I wonder whether there is perhaps even a `clang-tidy` fix to automate this.

**Pull request merged**
