### PR TITLE
Add install_prereqs scripts for bionic and related install_prereqs fixes for xenial

### PR DESCRIPTION
**Pull request by jamiesnape**
A `Dockerfile` is included for local testing of the bionic `install_prereqs` script. Note that this PR is far from enabling drake to be build on 18.04. Success would be the `install_prereqs` script succeeding.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8785)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 7 of 13 files at r1.
Review status: 7 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8785#-:-LC9FYhA6YgfVTYX-K9J:by96gdd)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@SeanCurtis-TRI for platform review, please.

I tested locally in a fresh schroot and the setup scripts succeeded, and also `bazel build //common` passed.

---

Reviewed 6 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8785#-:-LC9JYDK4B9UXbkDjul5:bwjff0k)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8785#-:-LC9O0k15OYQPkHTJz5m:bmxilld)*

**Pull request merged**
