### PR TITLE
Render capsule in vtk and ospray engines

### PR DESCRIPTION
**Pull request by tehbelinda**
Represented using a cylinder and two spheres

Relates to #10153

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12293)

### CODE REVIEW

**Comment by tehbelinda** [comment]
+@seancurtis-tri for feature review please

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_vtk_base.h, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12293#-LsbIJuQCwReYxBLBoGx:-LscCnAh0cO8-JY8hQ-8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6cbf1a2e7c5517a6cc38acf79eb53043106a9e9b/geometry/render/render_engine_vtk_base.h#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This should get some documentation. 
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/render/render_engine_ospray.cc, line 217 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12293#-Lsbjh5x0pyD2JHhhpcQ:-LscQNGU8uqXd6AQaOPS:b-e0acy8) ([raw file](https://github.com/robotlocomotion/drake/blob/6cbf1a2e7c5517a6cc38acf79eb53043106a9e9b/geometry/render/render_engine_ospray.cc#L217)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

My inclination for a small piece of utilitarian code like this would be to grab it and include it in our source (retaining attribution and the original license), but afterwards just maintain it ourselves (if it ever needs to change). @jwnimmer-tri do you think that's reasonable in this case: https://github.com/finetjul/bender/tree/master/Libs/VTK/Filters/Sources
(this is a straightforward use of VTK's  obscure API to make a capsule).
</blockquote></details>

On first look, yes it would be OK to copy the h and cxx into `drake/third_party/com_github_com_finetjul_bender/...` and maintain it there.

We'd need to document the upstream location and git sha we've copied.

We'd need to copy (or extract) a LICENSE.txt file for those files and add that license file to the install rules so we provide the notice required by the upstream copyright.

We'd need to be sure not to install the header, and to compile the cc_library with `-fvisibility=hidden` to keep the symbols private.

**Comment by tehbelinda** [comment]
typo fail...fixing

**Comment by tehbelinda** [comment]
now I can verify if my reviewable circle goes grey or stays red :)

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_ospray.cc, line 217 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12293#-LscG-Z51mTRFqEm2eCY:-LscgCKV-IUfX1UXUW8P:b-6u7hp0) ([raw file](https://github.com/robotlocomotion/drake/blob/d6db06961fad18351d2e19fa0d6b2a64a5570a15/geometry/render/render_engine_ospray.cc#L217)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this TODO doesn't seem necessary now that you got rid of the duplicated code (and thanks for doing that!).
</blockquote></details>

Ok, no worries!

**Comment by tehbelinda** [comment]
___
*[geometry/render/render_engine_ospray.cc, line 217 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12293#-Lsbjh5x0pyD2JHhhpcQ:-Lsch0ex0yuTyOVWb4cA:b1qdm9y) ([raw file](https://github.com/robotlocomotion/drake/blob/6cbf1a2e7c5517a6cc38acf79eb53043106a9e9b/geometry/render/render_engine_ospray.cc#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On first look, yes it would be OK to copy the h and cxx into `drake/third_party/com_github_com_finetjul_bender/...` and maintain it there.

We'd need to document the upstream location and git sha we've copied.

We'd need to copy (or extract) a LICENSE.txt file for those files and add that license file to the install rules so we provide the notice required by the upstream copyright.

We'd need to be sure not to install the header, and to compile the cc_library with `-fvisibility=hidden` to keep the symbols private.
</blockquote></details>

Ok sounds good, thank you both

**Comment by tehbelinda** [comment]
ok my circle resets to grey

**Pull request merged**
