### PR TITLE
Bind DeclareAbstractOutputPort

### PR DESCRIPTION
**Pull request by gizatt**
I'm not 100% convinced I'm using some of this code right (especially the allocator callback), but nonetheless I've been needing this functionality for making systems that operate on e.g. Images.

@EricCousineau-TRI, would you mind taking a look?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor comments. The allocator callback stuff all looks correct to me - thanks!

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/systems/test/custom_test.py, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH-iMg-4RpcURwQ0C8:-LEH-iMh9TPSsmLTLEeD:btt5qhd) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L327)):*
> ```Python
>         for T in [float, AutoDiffXd, Expression]:
> 
>             def MakeAbstractValue():
> ```

FYI Can you name this `make_abstract_value`?

---

*[bindings/pydrake/systems/test/custom_test.py, line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH3Kf36qbrTIkbhpyj:-LEH3Kf402hHZO58auMg:b-il11d8) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L328)):*
> ```Python
> 
>             def MakeAbstractValue():
>                 return AbstractValue.Make(("test_string", T(np.pi)))
> ```

Can you move the literal `("test_string", T(np.pi))` to `test_abstract_io_port`, something like:
```
expected_value= ("test_string", T(np.pi))
```

---

*[bindings/pydrake/systems/test/custom_test.py, line 334 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH1Cp27wEYX3wlF814:-LEH1Cp3DMQpednQR3cS:b-32zdoh) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L334)):*
> ```Python
>                     LeafSystem_[T].__init__(self)
>                     test_input_type = MakeAbstractValue()
>                     self.input_port = \
> ```

FYI For line wrapping, I generally prefer using parentheses `(...)` to allow statements to break across lines, unless it just looks ugly or doesn't work.

PEP-8 doesn't state a hard and fast rule about it disprefering `\` for continuation, though, so I'm fine with it as is if you want:
https://www.python.org/dev/peps/pep-0008/#indentation

---

*[bindings/pydrake/systems/test/custom_test.py, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2l9Y6yvnycoxRGkp:-LEH2l9Z3py2PsVA-c8b:b-90k908) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L343)):*
> ```Python
>                     input_value = \
>                         self.EvalAbstractInput(context, 0).get_value()
>                     print(y_data.get_mutable_value())
> ```

Would you be OK with removing this print statement?

---

*[bindings/pydrake/systems/test/custom_test.py, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2uLb3Z_fpXl10eXN:-LEH2uLb3Z_fpXl10eXO:b-8xg8w0) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L343)):*
> ```Python
>                     input_value = \
>                         self.EvalAbstractInput(context, 0).get_value()
>                     print(y_data.get_mutable_value())
> ```

On the first line of `test_abstract_io_port`, can you set `test = self`, and then on this line, do a quick sanity check (to ensure that the value passed in here is what we expect)?
```
test.assertTupleEqual(y_data.get_value(), expected_value)
```

---

*[bindings/pydrake/systems/test/custom_test.py, line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2G2i7f95UDYk3XKZ:-LEH2G2i7f95UDYk3XK_:b-3ijn34) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L353)):*
> ```Python
>             context.FixInputPort(0, fixed_input)
>             output = system.AllocateOutput(context)
>             self.assertEqual(output.get_num_ports(), 1)
> ```

BTW This comment is just an aside - was looking at `System.get_num_output_ports` out of curiosity, and just realized that I had bound it to `System::get_num_input_ports()` - d'oh!
Will submit a bugfix for that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936#-:-LEH3ZrxEifcy-Bw0leH:bycjosm)*

**Comment by EricCousineau-TRI** [comment]
+@sherm1 for platform review, please.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936#-:-LEH3xq6D80af-gixNKU:bppyoqq)*

**Comment by sherm1** [comment]
Platform :lgtm: pending open comments.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936#-:-LEH9NrW2taQGtkMN5_6:b-9hxbaf)*

**Comment by gizatt** [comment]
Made relatively major changes to the test (switching to a lambda function and differentiating the default, input, and output values to the custom system).

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/systems/test/custom_test.py, line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH3Kf36qbrTIkbhpyj:-LEHi-PcAJOkKPaFuRQ0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L328)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you move the literal `("test_string", T(np.pi))` to `test_abstract_io_port`, something like:
```
expected_value= ("test_string", T(np.pi))
```
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/custom_test.py, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2l9Y6yvnycoxRGkp:-LEHi2BxCNQNNmcE_YU-:bcry0bd) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L343)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would you be OK with removing this print statement?
</blockquote></details>

Oops, of course!

---

*[bindings/pydrake/systems/test/custom_test.py, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2uLb3Z_fpXl10eXN:-LEHlZ5mAPtrTZjWf98-:b-rx6805) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L343)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

On the first line of `test_abstract_io_port`, can you set `test = self`, and then on this line, do a quick sanity check (to ensure that the value passed in here is what we expect)?
```
test.assertTupleEqual(y_data.get_value(), expected_value)
```
</blockquote></details>

I wound up editing the test a bit more thoroughly, to differentiate the default constructed value in the output container, and the desired output container.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936#-:-LEHljGK-T03Rm6kh7re:b-dydez3)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/systems/test/custom_test.py, line 343 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2uLb3Z_fpXl10eXN:-LEIRhIbCDp6_pw3WsQC:b-l0ehxq) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L343)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

I wound up editing the test a bit more thoroughly, to differentiate the default constructed value in the output container, and the desired output container.
</blockquote></details>

Awesome, looks great!

---

*[bindings/pydrake/systems/test/custom_test.py, line 347 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEIRXVXArDtCjnRGUeS:-LEIRXVY6DUdnWb4ZRj0:b-5qwvnr) ([raw file](https://github.com/robotlocomotion/drake/blob/e890a22ced7f3a2157503784ee5cc13d96067b63/bindings/pydrake/systems/test/custom_test.py#L347)):*
> ```Python
>                     # The allocator function will populate the output with
>                     # the "input"
>                     test.assertTupleEqual(y_data.get_value(),
> ```

FYI It feels a little odd to be testing the default-constructed output port value - would you be OK with switching this statement to test the value of `input_value` (which should be `expected_input_value`)?

If not, I'm fine with it as is for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936)*

**Comment by gizatt** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[bindings/pydrake/systems/test/custom_test.py, line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEH2G2i7f95UDYk3XKZ:-LEIUYD-73Bho7gLDKwH:b-c7b3c4) ([raw file](https://github.com/robotlocomotion/drake/blob/5f22a8795a2323479f3db7976aafdf012c0acf84/bindings/pydrake/systems/test/custom_test.py#L353)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This comment is just an aside - was looking at `System.get_num_output_ports` out of curiosity, and just realized that I had bound it to `System::get_num_input_ports()` - d'oh!
Will submit a bugfix for that.
</blockquote></details>

Wow, oops. Bet that'd cause a confusing issue eventually :P

---

*[bindings/pydrake/systems/test/custom_test.py, line 347 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8936#-LEIRXVXArDtCjnRGUeS:-LEIUF2WAzWigVPIagCH:b-4ua0o2) ([raw file](https://github.com/robotlocomotion/drake/blob/e890a22ced7f3a2157503784ee5cc13d96067b63/bindings/pydrake/systems/test/custom_test.py#L347)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI It feels a little odd to be testing the default-constructed output port value - would you be OK with switching this statement to test the value of `input_value` (which should be `expected_input_value`)?

If not, I'm fine with it as is for now.
</blockquote></details>

Yeah, happy to make that change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please.

Got a timeout on `external_data_pkg_test` - unrelated to this, but still my fault :(

**Comment by gizatt** [comment]
Thanks!

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8936#-:-LEL-Lge7MgYlBQYg_lW:b-ucfknh)*

**Pull request merged**
