### PR TITLE
Update RenderEngineVtk to use RenderMaterial

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
`RenderEngineVtk` stops using `vtkOBJReader` and defers to `RenderMesh` and `RenderMaterial` to get OBJ mesh data and appearance.

Behavior implications

While the "if foo.png exists for foo.obj, apply it" behavior isn't *gone*,m it *has* been supplanted in the case where foo.obj actually has a material library (mtl). So, if models out there had let the mtl file rot when they catered to Drake's former idiosyncracies, this will cause the appearance to shift back towards the actual material specification.

Implementation details

  - The render engine is simply responsible for mapping those types to the VTK-specific representation.
  - `internal_render_engine_vtk_base` defines a new vtk polygon source based on the `RenderMesh` data. This is what replaces `vtkOBJReader`.
  - All non-mesh `Shape` types now use the `RenderMaterial` APIs to map from geometry properties to `RenderMaterial`.
  - The unit tests have simplified vis a vis meshes and textures. Now that it simply translates, we can rely on `RenderMaterial` tests to confirm the protocol logic and we just need to confirm `RenderEngineVtk` is exercising it and translating it correctly.
  - The `RenderMesh` -> `vtkPolyData` is capable of providing a more compact representation of the mesh than the `vtkOBJReader` (it created unique vertex data for each triangle). The gltf server code uses VTK to create gltf files. The reference gltf files used in the tests reflected the old, bloated mesh descriptions. They have been updated to the newer compact sizes.

Some incidental clean up:
 - Default diffuse color is properly stored as `Rgba` now.
 - Optimized the normal case of not scaling the texture.
 - Added note for clarity about the utility of the scaling factor; it seems to pass in test, but it isn't clear *why*. This needs further investigation.

Relates https://github.com/RobotLocomotion/drake/issues/18844

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@zachfang for feature review -- this'll give you a chance to see how materials are getting introduced to the `RenderEngine` family. I'm not sure what we'll do vis a vis the remote servers. Some of the core functionality isn't bound in pythong.

+(release notes: breaking change) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NUxCSaz-WR2gW4hawNz:b-o5f2wv)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI and @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383)* status: 2 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI and @zachfang)

___
*[`geometry/render/BUILD.bazel` line 104 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0z37wCaXjK8pdgEmU:-NV0z37wCaXjK8pdgEmV:b-hlwast) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/BUILD.bazel#L104)):*
> ```Starlark
>     testonly = 1,
>     srcs = glob([
>         "test/meshes/**/*.*",
> ```

nit Requiring a period (i.e., `*.*`) while globbing is somewhat unusual.



_Suggestion:_
```Starlark
"test/meshes/*",
```
___
*[`geometry/render/test/meshes/box_no_mtl.obj` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0yeXF0nO67_i9Snbp:-NV0yeXHDpixnTn56KfV:bo3d417) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/test/meshes/box_no_mtl.obj#L1)):*
> ```
> # N.B. Do not include a mtllib in this file!
> ```

nit Is it important that this file remain identical to `box.obj` modulo the mtllib and usemtl lines?

If yes, then we should either enforce that with a linter or else have a BUILD rule generate this file on the fly using `sed` instead of omitting it.

**Review by zachfang — COMMENTED** [review]
First pass done with some minor nits.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NV115aHABsqeSTkEpZ5:bsk67pv)* status: 5 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/render/BUILD.bazel` line 104 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0z9t71sC-nKpOVd7K:-NV0z9t71sC-nKpOVd7L:byhaha9) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/BUILD.bazel#L104)):*
> ```Starlark
>     testonly = 1,
>     srcs = glob([
>         "test/meshes/**/*.*",
> ```

BTW. There are no subfolders under `test/meshes`, I assume the recursive `**` is mainly due to a common glob pattern.
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV100hi6qZLfwHtnga5:-NV100hi6qZLfwHtnga6:b-6bt19n) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render_vtk/internal_render_engine_vtk.h#L227)):*
> ```objc
>   // Performs the common setup for all shape types.
>   void ImplementGeometry(vtkPolyDataAlgorithm* source,
>                          const geometry::internal::RenderMaterial& material,
> ```

BTW. Based on IWYU, we also need `#include "drake/geometry/render/render_material.h`. And, if I understand correctly, `render_mesh.h` is only needed in the `.cc` file.
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 380 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0s-jL5dCK1CdSOTos:-NV0s-jL5dCK1CdSOTot:b-r1p3v4) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L380)):*
> ```cpp
>     material.AddProperty("label", "id", expected_label_);
>     if (use_texture) {
>       // The simple material's texture is always should always reproduce the
> ```

nit. (Somehow I couldn't quote the text.) The simple material's texture ~~is always~~ should always reproduce the

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed. @zachfang let me know when you feel good about this going to platform.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NV5E4Cn3VVAMgO88_pT:bhrhvaj)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI and @zachfang)

___
*[`geometry/render/BUILD.bazel` line 104 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0z9t71sC-nKpOVd7K:-NV58pgJ6DRzf2yO4l0u:ba36ab7) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/BUILD.bazel#L104)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. There are no subfolders under `test/meshes`, I assume the recursive `**` is mainly due to a common glob pattern.
</blockquote></details>

Yep. Mostly just copypasta (and if a sub-folder were added, it would still work.
___
*[`geometry/render/test/meshes/box_no_mtl.obj` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0yeXF0nO67_i9Snbp:-NV5ALxSDeVRY1_8WkjJ:b93o6g5) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/test/meshes/box_no_mtl.obj#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Is it important that this file remain identical to `box.obj` modulo the mtllib and usemtl lines?

If yes, then we should either enforce that with a linter or else have a BUILD rule generate this file on the fly using `sed` instead of omitting it.
</blockquote></details>

Excellent point.

BTW I wasn't 100% clear on the proper bazel spelling. I've added the generated file as `data` to the file group. I also tried adding it as one of the `srcs`. Both work but I'm not sure which would be preferred.
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 227 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV100hi6qZLfwHtnga5:-NV59YQuDd9qxSOLayud:b-oxqd81) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render_vtk/internal_render_engine_vtk.h#L227)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Based on IWYU, we also need `#include "drake/geometry/render/render_material.h`. And, if I understand correctly, `render_mesh.h` is only needed in the `.cc` file.
</blockquote></details>

Done

(While it's not enforced for non C++ libraries, it's always good. Thanks for catching it for me.)

**Review by zachfang — COMMENTED** [review]
:lgtm: except for the `box_no_mtl` part, which I will leave to Jeremy.

(I plan to spend more time on the relevant merged PRs, but I will do that in the background.)

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NV5FZMH4a17N70ZAfnh:b-7f2mc6)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`geometry/render/BUILD.bazel` line 104 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV5HR4C-qnqrRB9KD7p:-NV5HR4C-qnqrRB9KD7q:b-v20p1a) ([raw file](https://github.com/RobotLocomotion/drake/blob/917b70a4d8f9e88ee71d803dcdab4fa2abefc88e/geometry/render/BUILD.bazel#L104)):*
> ```Starlark
>     srcs = ["test/meshes/box.obj"],
>     outs = ["test/meshes/box_no_mtl.obj"],
>     cmd = "sed '/mtllib\\|usemtl/d' $< > $@",
> ```

nit This sed-ism works on Ubuntu, but not macOS.  Here's one that works on both:

```
cmd = "sed '/mtllib/d; /usemtl/d' $< > $@",
```
___
*[`geometry/render/test/meshes/box_no_mtl.obj` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0yeXF0nO67_i9Snbp:-NV5I7A5DhAylN0tRczJ:b-ivjf8h) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/test/meshes/box_no_mtl.obj#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Excellent point.

BTW I wasn't 100% clear on the proper bazel spelling. I've added the generated file as `data` to the file group. I also tried adding it as one of the `srcs`. Both work but I'm not sure which would be preferred.
</blockquote></details>

I think `srcs` is nominally correct.  It's a direct member of the group of files, just like the other objs and pngs and mtls and etc.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NV5L1pE3EGqqhaNhd10:bppyoqq)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`geometry/render/test/meshes/box_no_mtl.obj` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV0yeXF0nO67_i9Snbp:-NV5L9A02k7-rt06QGGO:b-zcjvte) ([raw file](https://github.com/RobotLocomotion/drake/blob/6726c0e79bc77b96ee82c3b1886a57dc96cfc6c5/geometry/render/test/meshes/box_no_mtl.obj#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think `srcs` is nominally correct.  It's a direct member of the group of files, just like the other objs and pngs and mtls and etc.
</blockquote></details>

Thanks

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`geometry/render_vtk/internal_render_engine_vtk_base.cc` line 318 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV5apFt4ULL5lZvmugA:-NV5f3PAD_5GomC34vLu:b5r9gku) ([raw file](https://github.com/RobotLocomotion/drake/blob/7eca5d73b82d380807bfc54743e2dfebf3a98cba/geometry/render_vtk/internal_render_engine_vtk_base.cc#L318)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW not sure exactly what you're saying here. Did this come from copying an example and you're not sure if it is still needed? Is it a TODO?
</blockquote></details>

Simply removed it.

**Review by jwnimmer-tri — COMMENTED** [review]
Feature :lgtm: on the changes to the `BUILD.bazel` files.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NV5itZn6h7LL9Z0ys7a:bl4xw05)* status: 1 unresolved discussion

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383)* status: 2 unresolved discussions

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 545 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-NV5rxH70Szw9xTWyLz0:-NV5rxH70Szw9xTWyLz1:b-fjr27t) ([raw file](https://github.com/RobotLocomotion/drake/blob/6fab7a5b831303d880af65d26d2d3be8d57c393a/geometry/render_vtk/internal_render_engine_vtk.cc#L545)):*
> ```cpp
>           "Texture map '{}' has an unsupported bit depth, casting it to uchar "
>           "channels.",
>           material.diffuse_map);
> ```

nit Build fix for macOS:



_Suggestion:_
```cpp
material.diffuse_map.string()
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
D'oh....I'm glad you thought of doing that mac test.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19383#-:-NV6BJ1BBVUFifhvbIZs:b-rcl5hm)* status: 1 unresolved discussion

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot](https://github.com/drake-jenkins-bot) mac-arm-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Comment by SeanCurtis-TRI** [comment]
Wasn't paying attention. Siiiiiigh.

**Pull request merged**
