### PR TITLE
lint: Enable W504 for python

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #13197.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13204)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @EricCousineau-TRI for your input.  This is the fallout of restoring W504 to its default (enabled) state.  Are we happy with these kinds of changes?

**Comment by EricCousineau-TRI** [comment]
Looks fine by me! (I always forget personally, so this is helpful!)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews per schedule (tomorrow), please.

**Comment by jwnimmer-tri** [comment]
FTR I also hated it when I first saw it while prototyping this, but I grew to appreciate it.

**Pull request merged**
