### PR TITLE
Rename Context to LeafContext (part 1 of ContextBase rename)

### PR DESCRIPTION
**Pull request by sherm1**
This is part 1 of two PRs for addressing #3200, which ultimately wants:
1. `Context`  --> `LeafContext`
2. `ContextBase`  -->  `Context`

I believe doing both at the same time would be a reviewing nightmare, so this one just renames `Context` to `LeafContext` (along with the file names). When this lands we'll have:
```
ContextBase
    LeafContext
    DiagramContext
```
After that is safely tucked away, I'll rename ContextBase to Context.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3354)

### CODE REVIEW

**Comment by sherm1** [comment]
+@amcastro-tri for feature review, +@david-german-tri for platform review please.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-:-KQxSJ5OxaruUN9c5okQ:b-3enpxr)*

**Comment by david-german-tri** [comment]
:lgtm: aside from one small comment.  IMO this doesn't need two reviewers; unless you specifically wanted input from @amcastro-tri on something, feel free to merge.

---

Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-KR-El2az6d0cy22xBRl:-KR-El2az6d0cy22xBRm:b-c9ksqz) ([raw file](https://github.com/robotlocomotion/drake/blob/f9f16b0165e01a48704492fac99859b5a1b5f845/drake/systems/analysis/simulator.h#L9)):*
> ```objc
> #include "drake/common/eigen_autodiff_types.h"
> #include "drake/drakeSystemAnalysis_export.h"
> #include "drake/systems/framework/leaf_context.h"
> ```

Given the interface change below (which IMO is clearly correct), this change is unnecessary, right?

---

*[drake/systems/analysis/simulator.h, line 174 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-KR-E_ocSCPS1ZVfIeC_:-KR-E_odx-bYIehw6Y6N:btrunt4) ([raw file](https://github.com/robotlocomotion/drake/blob/f9f16b0165e01a48704492fac99859b5a1b5f845/drake/systems/analysis/simulator.h#L174)):*
> ```objc
>   current Context is deleted. This is useful for supplying a new set of initial
>   conditions. You should invoke Initialize() after replacing the Context. **/
>   void reset_context(std::unique_ptr<ContextBase<T>> context) {
> ```

BTW, this seems correct, but see above

---

*[drake/systems/framework/leaf_context.cc, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-KR-F4QVQ3LjfbxXbUJF:-KR-F4QVQ3LjfbxXbUJG:b-c9spjp) ([raw file](https://github.com/robotlocomotion/drake/blob/f9f16b0165e01a48704492fac99859b5a1b5f845/drake/systems/framework/leaf_context.cc#L4)):*
> ```cpp
> // leaf_context.h is a stand-alone header.
> 
> #include "drake/systems/framework/leaf_context.h"
> ```

BTW, you could add an explicit instantiation here if you want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-:-KR-FGubGD4X51NQSawF:b-un1di3)*

**Comment by david-german-tri** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3354)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-:-KR-uMX8IlcOrdlEyl0W:bnfp4nl)*

**Comment by sherm1** [comment]
Thanks, all comments addressed. Will merge after CI.

---

Review status: 20 of 22 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/simulator.h, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-KR-El2az6d0cy22xBRl:-KR0k3pysW8dpw9oscFd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9f16b0165e01a48704492fac99859b5a1b5f845/drake/systems/analysis/simulator.h#L9)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Given the interface change below (which IMO is clearly correct), this change is unnecessary, right?
</details>
Done.

---

*[drake/systems/analysis/simulator.h, line 174 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-KR-E_ocSCPS1ZVfIeC_:-KR0k4cDKYiDnzTA8kyC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9f16b0165e01a48704492fac99859b5a1b5f845/drake/systems/analysis/simulator.h#L174)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this seems correct, but see above
</details>
Done.

---

*[drake/systems/framework/leaf_context.cc, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-KR-F4QVQ3LjfbxXbUJF:-KR0kVFpjBRowcQthA1d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9f16b0165e01a48704492fac99859b5a1b5f845/drake/systems/framework/leaf_context.cc#L4)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, you could add an explicit instantiation here if you want.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3354#-:-KR0kXYrw6KwVxtM6_yb:b-hnhfso)*

**Pull request merged**
