### PR TITLE
Trajectory optimization visualization callbacks

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds methods to visualize the trajectories constructed during trajectory optimization.  

Also adds python bindings (and the prerequisite bindings for `MathematicalProgram::AddVisualizationCallback`).

Commits are already curated.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8598)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@avalenzu for feature review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-:-LA7c11D9bkXSnrv67Fp:b-fcohnv)*

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/trajectory_optimization/multiple_shooting.h, line 198 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-LAFLLNo0_73L5Zhv9n0:-LAFLLNo0_73L5Zhv9n1:btlg6tu) ([raw file](https://github.com/robotlocomotion/drake/blob/8093dd3bf2c6950143954a2d2a0718c2618c7bfd/systems/trajectory_optimization/multiple_shooting.h#L198)):*
> ```objc
>    *
>    * Note: Just like other costs/constraints, not all solvers support callbacks.
>    * Adding a callback here may change will force MathematicalProgram::Solve to
> ```

"may change" looks vestigial here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-:-LAFqgGj697Y9edHqKlr:bnfp4nl)*

**Comment by avalenzu** [comment]
+@sammy-tri  for platform review

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-:-LAItNK-0xYCzcL3qM5X:b-axdrep)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/trajectory_optimization/multiple_shooting.h, line 341 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-LAJFM9Q98cyhHq3C_Xe:-LAJFM9Q98cyhHq3C_Xf:bsp1f7f) ([raw file](https://github.com/robotlocomotion/drake/blob/8093dd3bf2c6950143954a2d2a0718c2618c7bfd/systems/trajectory_optimization/multiple_shooting.h#L341)):*
> ```objc
> 
>   solvers::VectorXDecisionVariable h_vars_;  // Time deltas between each
>   // input/state sample or the empty vector (if timesteps are fixed).
> ```

BTW I'm not sure if this reflow is any better than how it looked before...   I suspect the comment was originally spaced to the right so that the `//` were aligned?

---

*[systems/trajectory_optimization/test/multiple_shooting_test.cc, line 298 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-LAJG-Gn-u2StaVRf8Mi:-LAJG-Gn-u2StaVRf8Mj:bl6r63j) ([raw file](https://github.com/robotlocomotion/drake/blob/8093dd3bf2c6950143954a2d2a0718c2618c7bfd/systems/trajectory_optimization/test/multiple_shooting_test.cc#L298)):*
> ```cpp
>   was_called = false;
>   prog.EvalBindingAtInitialGuess(b);
>   EXPECT_TRUE(was_called);
> ```

I'm not sure that this tells us if the state callback was invoked vs. the input callback getting run a second time (also below).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-:-LAJGK3p-DF4SfW6zX_F:bvb1a6z)*

**Comment by sammy-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/trajectory_optimization/test/multiple_shooting_test.cc, line 262 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-LAKJJF6Ebu17xa0JUGM:-LAKJJF6Ebu17xa0JUGN:b-84pz1t) ([raw file](https://github.com/robotlocomotion/drake/blob/607533948e0331997057a7c7856854996b3839f7/systems/trajectory_optimization/test/multiple_shooting_test.cc#L262)):*
> ```cpp
> 
>   bool input_callback_was_called = false;
>   auto my_input_callback = [&was_called](
> ```

Does this capture need to be updated to reflect the new variable name?  (and below)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598)*

**Comment by RussTedrake** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/trajectory_optimization/test/multiple_shooting_test.cc, line 262 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-LAKJJF6Ebu17xa0JUGM:-LAKUjLm31xiAl0N7HMm:byoan7v) ([raw file](https://github.com/robotlocomotion/drake/blob/607533948e0331997057a7c7856854996b3839f7/systems/trajectory_optimization/test/multiple_shooting_test.cc#L262)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this capture need to be updated to reflect the new variable name?  (and below)
</blockquote></details>

Done.   (sorry for the aggressive push... was waiting for mosek to download over a poor connection)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8598#-:-LAKZl-CALy3mPLyfbWA:bnfp4nl)*

**Pull request merged**
