### PR TITLE
Update prerequisites installation instructions and scripts

### LINKED ISSUE #3729: remove bertini and gloptipoly from drake_ci and prereq instructions
following on #3727 .
in addition to removing the WITH_ args from ci, we should remove any requirements from the source installation instructions.  i believe mpich is only there due to bertini.  are there others?

### PR DESCRIPTION
**Pull request by jamiesnape**
Removes:

`bison`, `flex`, `mpich` (bertini)
`subversion` (`cmake`, `git`, and `wget` handle everything)
`swig` (use swig_matlab)

Closes #3729.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3744)

### CODE REVIEW

**Comment by sherm1** [comment]
(there are conflicts needing resolution)

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/fedora.rst, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3744#-KTkSMCqn9umDH5nvMfy:-KTkSMCqn9umDH5nvMfz:b3z699p) ([raw file](https://github.com/robotlocomotion/drake/blob/2573976073a3fe5ffbc020d01f2fe9c532708518/drake/doc/fedora.rst#L16)):*
> ```reStructuredText
>     sudo yum-config-manager --enable rhel-7-server-extras-rpms \
>       rhel-7-server-optional-rpms rhel-server-rhscl-7-rpms
>     wget -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
> ```

Instead of maintaining this doc (which has been wrong since forever anyway), could you just delete it and the references to it?

Sorry, I know it's unrelated, but since you're here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3744#-:-KTkSsAbl5p-Du9ZZLXe:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/fedora.rst, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3744#-KTkSMCqn9umDH5nvMfy:-KTkTUmTTdVXpNOKDUzN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2573976073a3fe5ffbc020d01f2fe9c532708518/drake/doc/fedora.rst#L16)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Instead of maintaining this doc (which has been wrong since forever anyway), could you just delete it and the references to it?
> 
> Sorry, I know it's unrelated, but since you're here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3744)*

**Comment by david-german-tri** [comment]
Thanks!  :lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3744#-:-KTkWIvHC8atLU7XU5wM:brchk5b)*

**Pull request merged**
