### PR TITLE
Stop assigning names to systems which are no better than GetMemoryObjectName

### PR DESCRIPTION
**Pull request by sammy-tri**
This came about because two instances of the resulting systems couldn't live in the same diagram.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7470)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@seancurtis-tri for feature review (since you made the unfortunate mistake of being the only person to chime in)

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7470#-:-KyzyoXgz2lBI4ZyWecm:b-2vnsi1)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: I think you missed on though.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/inverse_dynamics_controller.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7470#-Kz0uJ02WDBQl5EUAga6:-Kz0uJ02WDBQl5EUAga7:b-94qtcd) ([raw file](https://github.com/robotlocomotion/drake/blob/d83c63d6c6f55cfb209e480258028a7bafce0f72/drake/systems/controllers/inverse_dynamics_controller.cc#L89)):*
> ```cpp
>         builder.template AddSystem<ConstantVectorSource<T>>(
>             VectorX<T>::Zero(robot.get_num_velocities()));
>     zero_feedforward_acceleration->set_name("zero");
> ```

How about this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7470#-:-Kz0ugOZyVxnaNC6Uc0b:b-oryzku)*

**Comment by sammy-tri** [comment]
+@sherm1 per review schedule

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/inverse_dynamics_controller.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7470#-Kz0uJ02WDBQl5EUAga6:-Kz4eIcrWT4z9zwizdyJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d83c63d6c6f55cfb209e480258028a7bafce0f72/drake/systems/controllers/inverse_dynamics_controller.cc#L89)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

How about this one?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7470#-:-Kz4eSpAtNhhqYGIVdSW:bmfilr0)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7470)*

**Comment by sherm1** [comment]
Platform :lgtm:

---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7470#-:-KzAE6UGMHq-gMSHOFxO:b8qx53o)*

**Pull request merged**
