### PR TITLE
MBT getters refactor

### PR DESCRIPTION
**Pull request by amcastro-tri**
A necessary cleanup, where `get_foo(void)` getters in MBT code get simplified to `foo(void)`.
The comment [here](https://reviewable.io/reviews/robotlocomotion/drake/8147#-L62T11-23jEeR9QLYii) was the final push I needed to do it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8206)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
This is just a refactor as stated in the PR text. Therefore @seancurtis-tri for both feature and platform (I'd believe having two reviewers is not necessary).

cc'ing @edrumwri 

---

Review status: 0 of 47 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-:-L6SXMTV_QUjPwCXlewi:b84odxt)*

**Comment by SeanCurtis-TRI** [comment]
+@seancurtis-tri  for both reviews

---

Review status: 0 of 47 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-:-L6SeN-YU3H4t8XEjQsq:b7dbb3c)*

**Comment by SeanCurtis-TRI** [comment]
I'm going to wait until this passes CI.

---

Review status: 0 of 47 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-:-L6Si7BHFVvJePkfVp8y:b-pnk0zf)*

**Comment by amcastro-tri** [comment]
woops, I forgot about Siyuan's work. I think this time I fixed it.

---

Review status: 0 of 47 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-:-L6Sl10FqIOcdutQM62d:bp2h6g2)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: I like this. I need to do this to `GeometrySystem`.

I have two minor things (well, one minor thing and a passing suggestion).   (Both negotiable in the name of getting this PR through).

Is this going to cause any merge conflicts with any other live PRs?  Or are you already anticipating that?

---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/mobilizer_impl.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-L6TdrZSFeYN6ck9dB7m:-L6TdrZSFeYN6ck9dB7n:bvlzy0u) ([raw file](https://github.com/robotlocomotion/drake/blob/66eabeb482685f658f7b708cb7d01f67def00f7c/multibody/multibody_tree/mobilizer_impl.h#L35)):*
> ```objc
> /// @tparam T The scalar type. Must be a valid Eigen scalar.
> template <typename T,
>     int compile_time_num_positions, int compile_time_num_velocities>
> ```

FYI An alternative would be `position_count` and `velocity_count`. But what you have is just fine. (In some ways better.)

---

*[multibody/multibody_tree/multibody_tree.h, line 510 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-L6Te9zvDLBZFNegRr-Q:-L6Te9zwljca6ycXlncP:bp03qcs) ([raw file](https://github.com/robotlocomotion/drake/blob/66eabeb482685f658f7b708cb7d01f67def00f7c/multibody/multibody_tree/multibody_tree.h#L510)):*
> ```objc
>   ///     model.AddJoint<RevoluteJoint>(
>   ///       "Elbow",                /* joint name */
>   ///       model.world_body(), /* parent body */
> ```

BTW Lost nice formatting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-:-L6Tg5uRaqwLbWWea5IX:b-dj12fz)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/multibody_tree.h, line 510 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-L6Te9zvDLBZFNegRr-Q:-L6TrE3ybjTM2S_gjyjY:b-og6elm) ([raw file](https://github.com/robotlocomotion/drake/blob/66eabeb482685f658f7b708cb7d01f67def00f7c/multibody/multibody_tree/multibody_tree.h#L510)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Lost nice formatting
</blockquote></details>

BTW good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206)*

**Comment by SeanCurtis-TRI** [comment]
Youre' good - merge when it's done.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8206#-:-L6TrTVWAWIZDybHMi5B:b8u8a29)*

**Pull request merged**
