### PR TITLE
[misc] Remove deprecated code 2022-12

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441#-:-NJ7T_gSBtlLPSDRpHGR:b-9t2qsm)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Note: I still see the string `2022-12-01` in:

- geometry_py_hydro.cc
- plant_py.cc
- tree_py.cc
- plant_test.py
- pip.md
- frame.cc
- frames_test.cc
- libcurl/repository.bzl

Are these an oversight or is there a plan?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441#-:-NJ7Tg3F-0yrsVsRr8s1:b4o03rc)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441#-:-NJ7UcIbBVZybUO3Smyf:b-te4kzy)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the quick review! This is still WIP, I'll ping here when it's finished.
+(status: do not review) to get off the radar for now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441#-:-NJ7UrjM8hyKYQaUa5dD:b-uzvkyb)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
This is ready for another look. -(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441#-:-NJ7qvH22vHKQsV4BTaU:bsqgrqb)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18441#-:-NJB6wVcCkSqJSYenxpT:bmxilld)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18441#-NJB5TVV8C2Rz-KVvXmN:-NJB5TVW1RlSRnaYNjpM:b-279fs3) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf112ba00d7da9508d3506b2b293a3c0005aa/geometry/optimization/test/graph_of_convex_sets_test.cc#L57)):*
> ```cpp
> 
> namespace {
> bool MixedIntegerSolverAvailable() {
> ```

BTW You have a number of ancillary style changes: white space, inclusion of `// namespace`, etc. Probably best to keep those separate from the actual deprecation removals.

**Pull request merged**
